### ISSUE TITLE
bug: 上拉加载onReachBottom

### ISSUE THREAD

**Issue by 00feng00** [dcloudio/uni-app#100]
onReachBottom有个bug：
1、上拉的速度快的话，onReachBottom事件触发一次后，就不再触发，只能把界面拉上去再拉下来。
不能持续触发。

**Comment by zhetengbiji** [comment]
> onReachBottom有个bug：
> 1、上拉的速度快的话，onReachBottom事件触发一次后，就不再触发，只能把界面拉上去再拉下来。
> 不能持续触发。

是特指的H5端吗？
