### ISSUE TITLE
input输入框的input事件在微信小程序的开发工具中不能触发，双向绑定数据失败

### ISSUE THREAD

**Issue by Jonny-china** [dcloudio/uni-app#1003]
**问题描述**
input输入框的input事件在微信小程序的开发工具中不能触发,在真机上是正常的
开发工具版本： 1.02.1911082

_应该不是开发者工具的问题，mpvue的input是正常的_

`<input type="text" @input="handleInput" />`
`handleInput(e: any) {
    console.log(e)
  }`

**预期结果**
input 事件触发并打印出结果

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 MAC 10.15.1
 - uni-app v2.4.1
   uni-app cli v2.0.0-24120191114004
 - 设备信息: 微信开发者工具版本： 1.02.1911082

**Comment by Wangyaqi** [comment]
看一下微信开发工具调试基础库版本，微信开发工具2.9.3版本的调试基础库有Bug

**Comment by Jonny-china** [comment]
> 看一下微信开发工具调试基础库版本，微信开发工具2.9.3版本的调试基础库有Bug，https://developers.weixin.qq.com/community/develop/doc/000a067cd0c6102d0d79558e65bc00?highLine=bindinput

感谢感谢，mpvue项目是2.9.2，用uni-app新建项目是2.9.3，搞了半天原来是基础库的问题，差点放弃uni-app

**Comment by Jonny-china** [comment]
@Wangyaqi

**Comment by Jonny-china** [comment]
@Wangyaqi 
感谢感谢，mpvue项目是2.9.2，用uni-app新建项目是2.9.3，搞了半天原来是基础库的问题
