### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by swiftest0** [dcloudio/uni-app#1004]
**问题描述**

选择视频和图片时会引起内存泄漏
[https://github.com/dcloudio/uni-app/blob/9ef8f36ba0e70c57f1a34c45563fc5f574ff172d/src/platforms/h5/helpers/file.js#L51-L63](https://github.com/dcloudio/uni-app/blob/9ef8f36ba0e70c57f1a34c45563fc5f574ff172d/src/platforms/h5/helpers/file.js#L51-L63)

**Comment by zhetengbiji** [comment]
已知，后续会考虑优化方案
