### ISSUE TITLE
uni.setStorage() 等 API 不是异步的

### ISSUE THREAD

**Issue by helsonxiao** [dcloudio/uni-app#1005]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
如题

**复现步骤**
```
      uni.clearStorageSync();
      uni.setStorage({
        key: 'count',
        data: 10,
        success: function() {
          console.log('我是异步回调代码');
          console.log(uni.getStorageSync('count'));
        },
      });
      console.log('我是同步代码');
```

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
先 log 出“我是同步代码”，然后 log 出回调函数里的东西

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/26411634/68992769-03899700-08ab-11ea-947b-7084234146c3.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号] 2.4.1.20191114
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
具体的使用场景是什么？

**Comment by helsonxiao** [comment]
> 具体的使用场景是什么？

这个问题似乎无关紧要？文档里几个异步的接口测试下来好像都没有异步效果。

**Comment by zhetengbiji** [comment]
> > 具体的使用场景是什么？
> 
> 这个问题似乎无关紧要？文档里几个异步的接口测试下来好像都没有异步效果。

在部分平台的实现上有些API底层只有同步，所以封装的同步和异步可能等效（切勿将异步接口当作同步接口使用）。

**Comment by zhetengbiji** [comment]
你能否说一下具体的需求？

**Comment by helsonxiao** [comment]
> 你能否说一下具体的需求？

我在教学生同步异步概念的时候想用这个接口进行演示，然而在 HBuilder 内置浏览器里无法实现异步操作，文档里也没有发现支持情况的说明。

**Comment by zhetengbiji** [comment]
> > 你能否说一下具体的需求？
> 
> 我在教学生同步异步概念的时候想用这个接口进行演示，然而在 HBuilder 内置浏览器里无法实现异步操作，文档里也没有发现支持情况的说明。

底层使用localStorage实现，因对功能无影响，并未特殊说明。
