### ISSUE TITLE
无法进行事件委托

### ISSUE THREAD

**Issue by qingtianiii** [dcloudio/uni-app#1006]
**问题描述**
无法通过事件委托的方式获取实际触发事件的元素

**复现步骤**
[复现问题的步骤]
1.  demo
```
<template>
  <div class="container">
    <div class="aside">
      <div class="aside-header">{{ asideTitle }}</div>
      <div @click="handleClick">
        <div class="list-item" v-for="item in list" :key="item.id">
          <div class="item-title">
            {{item.title}}
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data () {
    return {
      list: []
    }
  },
  methods: {
    handleClick (e) {
      console.log('e', e);
    }
  }
}
</script>
```

**预期结果**
希望可以从 `console.log(e.target)` 中获取到对应点击的 element

**实际结果**
只是打印出了一个对象，无法通过该对象区分到底是点击了哪个元素

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [mac]

**Comment by javascriptchen** [comment]
把div换成view标签就好了

**Comment by xdkaka** [comment]
> 把所有div标签换成view标签就好了

换上也一样，获取不到代理元素

<img width="846" alt="QQ20220116-005335@2x" src="https://user-images.githubusercontent.com/3340436/149630390-9184a889-a0e9-44c2-83ec-fd7e20b34139.png">

**Comment by magicLaLa** [comment]
这个问题是解决了吗？没有搜索到相关解决方案
