### ISSUE TITLE
// #ifdef 如何添加 or 的判断

### ISSUE THREAD

**Issue by liuyingqq123** [dcloudio/uni-app#1008]
**问题描述**
[我自定义了四个个环境变量, 但是判断的时候想加入or的逻辑, 不好用]

**复现步骤**
package.json中加入了
    "scripts": {
      "mp-doctor": {
        "title": "医生",
        "env": {
          "UNI_PLATFORM": "mp-weixin"
        },
        "define": {
          "MP-DOCTOR": true
        }
      },
      "mp-patient": {
        "title": "患者",
        "env": {
          "UNI_PLATFORM": "mp-weixin"
        },
        "define": {
          "MP-PATIENT": true
        }
      },
      "mp-community": {
        "title": "社区",
        "env": {
          "UNI_PLATFORM": "mp-weixin"
        },
        "define": {
          "MP-COMMUNITY": true
        }
      },
      "mp-specialist": {
        "title": "专员",
        "env": {
          "UNI_PLATFORM": "mp-weixin"
        },
        "define": {
          "MP-SPECIALIST": true
        }
      }
  }

想在业务中, 进行or的逻辑判断, 我加入如下代码
// #ifdef MP-DOCTOR || MP-PATIENT
debugger;
console.log('我是医生或者患者')
// #endif

**预期结果**
用医生运行, 或者患者运行时, 可以执行这个判断

**实际结果**
医生或者患者的运行, 都没有执行到这里

**系统信息:**
 - 发行平台: [微信小程序]
 - 操作系统 [安卓]
 - HBuilderX版本 [2.3.3.20190923]
 - 设备信息 [华为荣耀9]

**Comment by Wangyaqi** [comment]
升级一下HBuilderX测试一下，测试使用2.4.2是正常的

**Comment by liuyingqq123** [comment]
> 升级一下HBuilderX测试一下，测试使用2.4.2是正常的

非常感谢, 果然升级完就好使了

**Comment by liuyingqq123** [comment]
> 升级一下HBuilderX测试一下，测试使用2.4.2是正常的

已经升级到最新, 发现, 只有前一个条件能判断到, || 后面的条件判断不到

**Comment by fxy060608** [comment]
在每一个define 中都定义好其他值，如：
```
"define": {
            "MP-DOCTOR": true,
            "MP-PATIENT": false,
            "MP-COMMUNITY": false,
            "MP-SPECIALIST": false
        }
```

**Comment by dcloudhdx** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
