### ISSUE TITLE
list组件在app端，触发loadmore上拉加载事件，只触发一次，这个为什么

### ISSUE THREAD

**Issue by 17602260250** [dcloudio/uni-app#1009]
<template>
	<view class="index">
		<list @loadmore="load_more_v" class="list_v" loadmoreoffset="10">
			<cell>
				<view class="box_v">1</view>
				<view class="box_v">2</view>
				<view class="box_v">3</view>
				<view class="box_v">4</view>
				<view class="box_v">5</view>
				<view class="box_v">6</view>
				<view class="box_v">7</view>
				<view class="box_v">8</view>
				<view class="box_v">9</view>
				<view class="box_v">10</view>
				<view class="box_v">44</view>
				<view class="box_v">55</view>
				<view class="box_v">77</view>
				<view v-if="box">
					<view class="box_v">99</view>
					<view class="box_v">66</view>
					<view class="box_v">55</view>
					<view class="box_v">44</view>
					<view class="box_v">44</view>
					<view class="box_v">33</view>
					<view class="box_v">778888</view>
				</view>
			</cell>
		</list>
	</view>
</template>

load_more_v(){
	console.log(1)
	console.log(new Date().getTime())
	this.box=true
},

这个load_more_v函数第一次滑动到底部的时候执行了，但是之后再次滑动到底部为啥就不执行了，这是怎么回事

**Comment by 17602260250** [comment]
![捕获](https://user-images.githubusercontent.com/38834732/69036810-8fbdca80-0a21-11ea-8a6c-43ef699dee2e.PNG)

**Comment by 17602260250** [comment]
![捕获55](https://user-images.githubusercontent.com/38834732/69036878-ad8b2f80-0a21-11ea-8e97-ad2d046a0686.PNG)

**Comment by 17602260250** [comment]
怎么load_more_v函数只触发一次呀，第一次上拉到底部执行了，之后上拉不在执行，只是为什么

**Comment by Wangyaqi** [comment]
上传一下你精简之后的demo，我们验证一下

**Comment by 17602260250** [comment]
[new_file.zip](https://github.com/dcloudio/uni-app/files/3857575/new_file.zip)

**Comment by 17602260250** [comment]
没人吗

**Comment by myssru** [comment]
> 没人吗

你应该问：在吗？

**Comment by Wangyaqi** [comment]
看附件，list和cell应该这么用，不能用H5的触底加载的思路来考虑

**Comment by Wangyaqi** [comment]
[index.zip](https://github.com/dcloudio/uni-app/files/3857631/index.zip)

**Comment by 17602260250** [comment]
现在我把，每个需要加载的list都嵌套了一个cell，可是为啥直接在外层嵌套一个cell不行吗

**Comment by Wangyaqi** [comment]
直接套一个cell就不要使用list了，list的回收机制是按照cell回收的，不会给你回收半个cell

**Comment by 17602260250** [comment]
![捕获888888888888855555](https://user-images.githubusercontent.com/38834732/69038993-052b9a00-0a26-11ea-894d-52dbd885ae36.PNG)

**Comment by 17602260250** [comment]
现在我这个第一个cell不存在回收机制，底下循环的有回收机制，这是为什么，我的第一个cell加载的是一个自定义的组件

**Comment by Wangyaqi** [comment]
你怎么判断有没有被回收的

**Comment by 17602260250** [comment]
我滚动的时候，没有动画显示呀，我的底下循环成的cell中的图片，滑动会有渐显的动画效果，而第一个中的cell，加载自定义组件中的图片，滑动没有渐显的效果呀？这是不是，就没有回收机制呀

**Comment by Wangyaqi** [comment]
weex官方应该也没说怎么判断有没有回收，如果影响不大就先别纠结这个了

**Comment by 17602260250** [comment]
好吧，搞了好办天这个，一开始以为list组件中，用一个cell，包裹起来就行了
