### ISSUE TITLE
打包h5报路径错误

### ISSUE THREAD

**Issue by klren0312** [dcloudio/uni-app#101]
![](https://s1.ax1x.com/2018/12/03/FMr1wn.png)

**Comment by zhetengbiji** [comment]
一般是由于组件引用错误导致，找不到具体问题的话，发社区附上demo。

**Comment by klren0312** [comment]
好的

**Comment by klren0312** [comment]
这个问题用条件编译解决了   [](https://github.com/klren0312/ironInfoWeapp/commit/4c98c66f3fe6c11fa62a20c1e4bb68d1539c8a60)
