### ISSUE TITLE
app-plus的webview中uni.getEnv是undefined

### ISSUE THREAD

**Issue by lmf** [dcloudio/uni-app#1011]
**问题描述**
web-view组件中引用的网页加载了uni.webview.1.5.2.js，然后在UniAppJSBridgeReady事件回调中执行uni.getEnv时候报undefined

**补充信息**
[可选]
看了下uni js sdk的代码，判断如果该h5页面是uni-app生成的，则uni-app的api会覆盖js sdk上的，建议js sdk上的api挂到uni的子属性下如uni.sdk

**Comment by lmf** [comment]
这问题只有h5页面是用uni-app生成的且引用了uni的js sdk后会有

**Comment by lmf** [comment]
@fxy060608 帮忙看下这个问题

**Comment by dcloudhdx** [comment]
已更新线上的 uni.webview.1.5.2.js
