### ISSUE TITLE
nvue怎么使用canvas

### ISSUE THREAD

**Issue by 17602260250** [dcloudio/uni-app#1012]
nave怎么使用canvas呀

**Comment by Wangyaqi** [comment]
nvue的canvas正在开发中，感谢关注

**Comment by wakaryry** [comment]
https://github.com/dcloudio/NvueCanvasDemo

紧急的话参考这个？

**Comment by 17602260250** [comment]
现在用的就是这个，但是获取图片像素信息获取不到https://github.com/dcloudio/NvueCanvasDemo，这个说是支持获取图片像素信息呀？测试了一下，返回数据是空的

**Comment by dcloudhdx** [comment]
获取图片像素信息，在Android上存在问题，尽快修复

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/NvueCanvasDemo
