### ISSUE TITLE
scss文件里的条件编译失败

### ISSUE THREAD

**Issue by devilwjp** [dcloudio/uni-app#1013]
**问题描述**
版本2.0.0-24120191114004，在scss文件内使用条件编译变得无效，老版本可以
App.vue中引入common.scss，编译后，添加了条件编译的样式也被编译进了main.wxss中

**复现步骤**
common.scss
```
/* #ifdef H5 */
::-webkit-scrollbar {
    width: 0;
    height: 0;
}  
/* #endif */
```

App.vue
```
<script>
	export default {
		onLaunch: function() {
			console.log('App Launch')
		},
		onShow: function() {
			console.log('App Show')
		},
		onHide: function() {
			console.log('App Hide')
		}
	}
</script>

<style lang="scss">
@import "./scss/common.scss";
@import './scss/theme.scss';

/*每个页面公共css */
uni-page-body {
  height: 100%;
}
</style>
```

**预期结果**
**main.wxss中应该不包含**
```
::-webkit-scrollbar {
    width: 0;
    height: 0;
}  
```

**实际结果**
main.wxss中包含了
`::-webkit-scrollbar{width:0;height:0}`

**系统信息:**
 - 发行平台: [微信小程序]
 - 操作系统 [windows]
 - uni-app版本 [2.0.0-24120191114004，npm run dev:mp-weixin]
 - 设备信息 [微信开发工具]

**补充信息**
老版本的scss不会被压缩，注释也不会被去除，2.0.0-24120191114004会去除注释并且压缩，我分析可能uni是对scss先进行了压缩去除了注释，导致了条件编译被过滤

**Comment by javascriptchen** [comment]
你写的条件编译不是h5的吗？你写小程序的才能不被编译到小程序的

**Comment by devilwjp** [comment]
> 你写的条件编译不是h5的吗？你写小程序的才能不被编译到小程序的

我希望通过这个条件编译，只在H5里生效，在打包成微信小程序不希望出现这个样式，请注意我的系统信息，npm run dev:mp-weixin

**Comment by devilwjp** [comment]
再提供一个线索，在css文件里，条件编译有效，在scss文件里无效 @javascriptchen

**Comment by javascriptchen** [comment]
好的，我们检查一下

**Comment by javascriptchen** [comment]
`App.vue中引入common.scss`
```
/* #ifdef H5 */
.test-class{
	color:red;
}
/* #endif */
```
`h5`
![image](https://user-images.githubusercontent.com/26818851/69121934-71ff6c80-0ad8-11ea-9473-e6fbf3092e1e.png)
`微信小程序`
![image](https://user-images.githubusercontent.com/26818851/69121953-7f1c5b80-0ad8-11ea-8652-97c65dd7ec88.png)

`测试代码`
[1013-scss.zip](https://github.com/dcloudio/uni-app/files/3862265/1013-scss.zip)
不过我的版本是2.0.0-24220191115005，你看下是不是更新了就好了

**Comment by liuyingqq123** [comment]
> 好的，我们检查一下

能帮忙看下https://github.com/dcloudio/uni-app/issues/1008这个问题吗?
自定义的平台, 
// #ifdef 无法用or的条件

**Comment by devilwjp** [comment]
@javascriptchen 你的测试用例里，如果将App.vue的<style>标签加上lang="scss"，就会导致common.scss中的条件编译失败

**Comment by devilwjp** [comment]
> @javascriptchen 你的测试用例里，如果将App.vue的<style>标签加上lang="scss"，就会导致common.scss中的条件编译失败

@javascriptchen 这个应该是个比较明确的bug了，所以我们现在只能退回0.9.503的版本了，希望尽快进行修复

**Comment by javascriptchen** [comment]
[1013-scss.zip](https://github.com/dcloudio/uni-app/files/3873529/1013-scss.zip)
![image](https://user-images.githubusercontent.com/26818851/69319648-8d09e200-0c7a-11ea-8c83-74ffed59a1c2.png)
![image](https://user-images.githubusercontent.com/26818851/69319737-b88ccc80-0c7a-11ea-83eb-296e1145e23c.png)
![image](https://user-images.githubusercontent.com/26818851/69319740-b9bdf980-0c7a-11ea-94e3-4fbc93273d95.png)

**Comment by devilwjp** [comment]
@javascriptchen 我们没有使用hbuiderX开发

**Comment by javascriptchen** [comment]
> @javascriptchen 我们没有使用hbuiderX开发，直接走本地node_modules安装的，你提供的用例，在style标签加上lang="scss"之后，提示没有安装sass-loader和node-sass，手动安装之后，运行npm run dev:mp-weixin，common.css里的条件编译就会失败，微信小程序的main.wxss里还是会出现test-class

是一样的，你重新打开我新发的测试用例试试？我这边也是用命令行起的服务。
![image](https://user-images.githubusercontent.com/26818851/69320889-fee32b00-0c7c-11ea-871e-da4ddfd371de.png)
![image](https://user-images.githubusercontent.com/26818851/69320890-ff7bc180-0c7c-11ea-8be6-9f50d4fd4f9c.png)

**Comment by devilwjp** [comment]
@javascriptchen 
我又重新跑了一点，可以肯定问题依旧存在，我是windows系统，我在其他的mac系统上也是如此，截图日志如下

npm源用的是taobao
![1](https://user-images.githubusercontent.com/38802722/69324087-cb0b0400-0c82-11ea-8800-67f76f1bf716.jpg)

![2](https://user-images.githubusercontent.com/38802722/69324175-efff7700-0c82-11ea-8765-a766d74cbbfc.jpg)

修改完lang="scss"后报sass-loader未安装
![3](https://user-images.githubusercontent.com/38802722/69324204-fc83cf80-0c82-11ea-989b-29626149f68a.jpg)

然后安装sass-loader和node-sass，安装后的版本如下
![4](https://user-images.githubusercontent.com/38802722/69324248-12919000-0c83-11ea-86af-9b7364f453ed.jpg)

然后npm run dev:mp-weixin进行编译，编译完成后，进入dist/dev/mp-weixin/common/main.wxss查看，发现出现了.test-class（PS，App.vue中去除lang="scss"，main.wxss中就不会出现test-class）
![5](https://user-images.githubusercontent.com/38802722/69324323-35bc3f80-0c83-11ea-99cb-c163191ec912.jpg)

**Comment by javascriptchen** [comment]
你用我最新发的代码压缩包，看你用的是老的
我新的代码里面依赖有node-sass
![image](https://user-images.githubusercontent.com/26818851/69324822-1e318680-0c84-11ea-8c1b-84415f2ccbb1.png)

**Comment by devilwjp** [comment]
@javascriptchen 不好意思，前面没看到最新包，刚才下了，但是问题依旧，也不是我一个人的情况，但是在0.9.503的版本是好的

**Comment by javascriptchen** [comment]
> @javascriptchen 不好意思，前面没看到最新包，刚才下了，但是问题依旧，也不是我一个人的情况，但是在0.9.503的版本是好的

我也在App.vue里面设置了lang=“scss“啊 你node版本多少，我装一个试试，我是8.12

**Comment by devilwjp** [comment]
@javascriptchen 10.8.0

**Comment by javascriptchen** [comment]
![image](https://user-images.githubusercontent.com/26818851/69339682-d8cf8200-0ca0-11ea-8dbb-ac49ac4167fa.png)
![image](https://user-images.githubusercontent.com/26818851/69339683-da994580-0ca0-11ea-8f8a-8884d96f439d.png)
你装nvm，用8.12.0就可以了，我这边一直用的就是8.12.0

**Comment by devilwjp** [comment]
@javascriptchen 

实在没办法，看了下源码，发现确实有问题，@dcloudio/vue-cli-plugin-uni/lib/chain-webpack.js中，是在sass-loader之前，插入的webpack-preprocess-loader，因为common.scss不是在js中被引入的，是在style里引入的，是直接被sass-loader内部消费，消费前就直接是@import "common.scss"，而默认没有设置sassOptions的outputStyle，默认是nested的，最新版本的node-sass的nested是去除注释的，导致在css-loader之后已经消费不到条件编译了。

我尝试在@dcloudio/vue-cli-plugin-uni/lib/option.js里设置sassOption的outputStyle为expanded就完全正常了，因为css-loader之后可以消费到


**chain-webpack.js**
![6](https://user-images.githubusercontent.com/38802722/69365319-092e1500-0ccf-11ea-93c2-e20b076076af.jpg)

**option.js**
![7](https://user-images.githubusercontent.com/38802722/69365476-64600780-0ccf-11ea-91cd-b39b94e0ca01.jpg)

**Comment by devilwjp** [comment]
@javascriptchen 

我现在直接在vue.config.js里修改了sassOptions，这样我的项目就可以用最新的uni版本了


**vue.config.js**
```
module.exports = {
    css: {
        loaderOptions: {
            sass: {
                sassOptions:{
                    outputStyle: 'expanded'
                }
            }
        }
    }
}
```

**Comment by fxy060608** [comment]
> @javascriptchen
> 
> 实在没办法，看了下源码，发现确实有问题，@dcloudio/vue-cli-plugin-uni/lib/chain-webpack.js中，是在sass-loader之前，插入的webpack-preprocess-loader，因为common.scss不是在js中被引入的，是在style里引入的，是直接被sass-loader内部消费，消费前就直接是@import "common.scss"，而默认没有设置sassOptions的outputStyle，默认是nested的，最新版本的node-sass的nested是去除注释的，导致在css-loader之后已经消费不到条件编译了。
> 
> 我尝试在@dcloudio/vue-cli-plugin-uni/lib/option.js里设置sassOption的outputStyle为expanded就完全正常了，因为css-loader之后可以消费到
> 
> **chain-webpack.js**
> ![6](https://user-images.githubusercontent.com/38802722/69365319-092e1500-0ccf-11ea-93c2-e20b076076af.jpg)
> 
> **option.js**
> ![7](https://user-images.githubusercontent.com/38802722/69365476-64600780-0ccf-11ea-91cd-b39b94e0ca01.jpg)

出现该问题是，是因为 build 模式下，sass-loader 如果不主动传入 outputStyle，会默认成 compressed

**Comment by flyromance** [comment]
怎么还有这个问题？我在pages中某个vue文件，<style lang="scss" scoped>中写 条件注释页不生效。。。

**Comment by devilwjp** [comment]
@flyromance  应该已经没有这个问题了，问题已经关闭了，你uni-app什么版本？

**Comment by wusp1994** [comment]
问题依然存在，https://ask.dcloud.net.cn/question/85884

**Comment by wusp1994** [comment]
现在变成了，dev可以，build后scss文件中能不能实现条件编译。 @javascriptchen
