### ISSUE TITLE
Bad attr `data-event-opts` with message,父子组件处理函数多参数传递问题

### ISSUE THREAD

**Issue by dingshiwei** [dcloudio/uni-app#1016]
小程序自定义组件模式编译，出现上述问题, H5正常
子组件 ![image](https://user-images.githubusercontent.com/12472771/69120920-d2d97580-0ad5-11ea-938b-e6b6b1184249.png)
父组件 
![image](https://user-images.githubusercontent.com/12472771/69120942-e4228200-0ad5-11ea-8025-eb20336092b7.png)
报错提示
![image](https://user-images.githubusercontent.com/12472771/69120959-f00e4400-0ad5-11ea-8e79-bbd81e413a34.png)

**Comment by fxy060608** [comment]
暂不支持模板中使用扩展符

**Comment by dingshiwei** [comment]
![image](https://user-images.githubusercontent.com/12472771/69121445-5d6ea480-0ad7-11ea-9889-988bb18c3f3b.png)
我换成这种写法，小程序正常了，但是h5中无法获取第二个参数
![image](https://user-images.githubusercontent.com/12472771/69121490-75debf00-0ad7-11ea-91cc-f3932dd400f7.png)
是不是最后，只能使用arguemnts 让参数通过类似数组的方式传递？

**Comment by fxy060608** [comment]
h5 确认有问题，可以先使用单参数传递
