### ISSUE TITLE
switch组件不能灵活的处理业务

### ISSUE THREAD

**Issue by mayunxuan** [dcloudio/uni-app#1019]
我的需求是触发switch的change事件的时候不要改变switch状态,而是等待接口返回结果再去根据条件来判断是否要改变状态. 我看到源码里先 this.switchChecked = !this.switchChecked 取反,然后再绑定change事件的. 有人遇到类似问题,还望指点.

**Comment by myssru** [comment]
你去插件市场找找有这样的么，没有的话，自己写一个
