### ISSUE TITLE
HbuilderX 可以增加自动保存代码的功能吗

### ISSUE THREAD

**Issue by lzcdev** [dcloudio/uni-app#102]

**Comment by lzcdev** [comment]
特别是修改多个文件时很容易忘记保存

**Comment by wanganxp** [comment]
有的。
默认有类似word的临时文件自动保存机制，不怕断电、崩溃。再启动时会恢复最近的修改。
也可以在设置里设标签卡失去焦点自动保存真实文件。

**Comment by lzcdev** [comment]
> 有的。
> 默认有类似word的临时文件自动保存机制，不怕断电、崩溃。再启动时会恢复最近的修改。
> 也可以在设置里设标签卡失去焦点自动保存真实文件。

我现在的问题是修改了几个文件不保存的话，运行的时候修改过的不起作用，必须手动保存一下才能起作用。

**Comment by wanganxp** [comment]
哦，那是对的。可以全部保存，ctrl+alt+s。也可以在设置里设失去焦点自动保存。但每次保存会自动触发编译，所以大家的习惯一般都是先不保存，运行前全部保存一下，然后自动就触发编译运行了，也不需要手动点运行

**Comment by lzcdev** [comment]
好的，我试一下，感谢
