### ISSUE TITLE
uni-app编译模式，.js文件中使用store与.nvue文件中的store不一致，像是独立的一样

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-app#1020]
uni-app编译模式，.js文件中使用store与.nvue文件中的store不一致，像是独立的一样。
如我在.js文件中store.dispatch('setToken',token) ，然后在某.vue文件发现this.$store.state.token无任何变化。反过来在.nvue设置token，在.js中token也没变化。

HBuilderX 2.4.2

**Comment by wakaryry** [comment]
不能在独立的工具类js中使用store。只能页面级js使用。如果需要 在工具类 js中同步数据，可以使用 globalData。 getApp是全局 通用的。

**Comment by wakaryry** [comment]
https://github.com/dcloudio/uni-app/issues/989

参考这个。

**Comment by huanghaodong** [comment]
> 页面级js

诶，要是支持支持就爽歪歪了。只有凑合用getApp了
