### ISSUE TITLE
开发工具打包百度小程序onShow只执行一次的问题，详细请看描述

### ISSUE THREAD

**Issue by zmzxn** [dcloudio/uni-app#1021]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
开发工具运行百度小程序之后，页面可以正常打开，此时onshow是正常执行的，当我跳转到内页的时候，再从内页返回到这个页面，这个时候页面的onShow不会执行，页面是不会刷新的（业务场景描述：地址列表展示->内页添加地址，添加完成之后返回到地址列表页面，这个时候页面需要重新加载，但是这个是页面不会去执行onshow），其他小程序正常
编译工具2.4.2.20191115
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Wangyaqi** [comment]
周四alpha版本修复此问题

**Comment by zmzxn** [comment]
> 下个alpha版本修复此问题

这个大概有没有时间节点，项目等着上线呢，还望告知一下，这边做下安排

**Comment by zmzxn** [comment]
请问官方大哥，你们alpha什么时候发版呢，目前项目一直停滞，你们也没有给个大致的时间点！

**Comment by changan12** [comment]
> 请问官方大哥，你们alpha什么时候发版呢，目前项目一直停滞，你们也没有给个大致的时间点！

今天晚些时候应该可以发布

**Comment by zmzxn** [comment]
> > 请问官方大哥，你们alpha什么时候发版呢，目前项目一直停滞，你们也没有给个大致的时间点！
> 
> 今天晚些时候应该可以发布
昨天没有发版吧，今天能发版吗？

**Comment by Wangyaqi** [comment]
HBuilderX 2.4.4-alpha版本已修复
