### ISSUE TITLE
Nvue中list组件，做上拉加载，下拉刷新，刷新之后，无法正常上拉加载数据

### ISSUE THREAD

**Issue by 17602260250** [dcloudio/uni-app#1022]
![捕获01](https://user-images.githubusercontent.com/38834732/69224887-4653b380-0bb8-11ea-900a-fb36fc862196.PNG)
![捕获02](https://user-images.githubusercontent.com/38834732/69224894-494ea400-0bb8-11ea-9f1c-e117889bcae2.PNG)
![捕获03](https://user-images.githubusercontent.com/38834732/69224900-4b186780-0bb8-11ea-843e-2c6165989a9f.PNG)

**Comment by 17602260250** [comment]
正常上拉加载，没有问题，但是上拉两页数据之后，下拉刷新一次，之后再上拉加载数据，就不会触发load_more事件了

**Comment by 17602260250** [comment]
如果上拉两页以上数据，下拉刷新之后，是可以正常，上拉加载数据的

**Comment by 17602260250** [comment]
只是上拉两页数据，下拉刷新之后，就无法正常上拉加载了，根本无法触发load_more函数

**Comment by Wangyaqi** [comment]
下次直接发代码比较好，不然我们还得重新敲一遍

**Comment by 17602260250** [comment]
代码写的太多了呀，单独提出来，实在太麻烦了

**Comment by 17602260250** [comment]
现在问题是，上拉加载数据两次之后，下拉刷新一次之后，滚动到底部就无法触发load_more事件

**Comment by Wangyaqi** [comment]
简单测试未复现
```
<template>
	<list class="list" @loadmore="loadList" loadmoreoffset="100">
		<refresh @refresh="refresh" :display="refreshing?'show':'hide'">
			<text class="refresh-text">Refreshing...</text>
		</refresh>
		<cell v-for="(v,i) in rows" :key="i" class="row">
			<div class="item">
				<view class="">
					<text class="item-title">row {{v}}</text>
				</view>
			</div>
		</cell>
	</list>
</template>

<script>
	export default {
		data() {
			return {
				rows: [0],
				refreshing: false
			}
		},
		onLoad() {
			this.loadList()
		},
		methods: {
			loadList() {
				for (let i = 1; i <= 20; i++) {
					this.rows.push(this.rows[this.rows.length - 1] + 1)
				}
			},
			refresh() {
				uni.showLoading({
					title: '加载中...'
				})
				this.refreshing = true
				setTimeout(() => {
					this.refreshing = false
					uni.hideLoading()
					this.rows = [0]
					for (let i = 1; i <= 20; i++) {
						this.rows.push(this.rows[this.rows.length - 1] + 1)
					}
				}, 1000)
			}
		}
	}
</script>

<style>
	.list {
		height: 500px;
	}

	.refresh-text {
		text-align: center;
		color: #007AFF;
	}

	.item-title {
		height: 40px;
		line-height: 40px;
		text-align: center;
	}
</style>

```

**Comment by 17602260250** [comment]
我给list设置高度为啥不起作用呀

**Comment by 17602260250** [comment]
![555555](https://user-images.githubusercontent.com/38834732/69302744-9d5b9600-0c55-11ea-9ebc-be944c309fe3.PNG)
![捕获11111111](https://user-images.githubusercontent.com/38834732/69302747-a0568680-0c55-11ea-8f50-7af6d5fbf722.PNG)

**Comment by 17602260250** [comment]
设置list宽度和高度都没起作用呀

**Comment by Wangyaqi** [comment]
运行我发的代码高度正常吗

**Comment by 17602260250** [comment]
你的代码正常，没问题

**Comment by 17602260250** [comment]
我把代码简单上传一下

**Comment by Wangyaqi** [comment]
可以先自己删代码缩小一下问题范围，看看是不是删掉哪句就正常了

**Comment by 17602260250** [comment]
我用的这个插件，https://ext.dcloud.net.cn/plugin?id=103

**Comment by 17602260250** [comment]
我把这个插件市场的下载下来之后，和我现在的情况一样

**Comment by 17602260250** [comment]
把list单独拿出来可以设置宽高，但是放在slider中无法设置呀

**Comment by 17602260250** [comment]
还有插件市场的那个和我情况是一样的，都是上拉两次之后，下拉刷新数据，之后再上拉加载，上拉加载函数就不会触发了

**Comment by 17602260250** [comment]
上拉加载两次以上没啥问题，就是上拉两次，之后，下拉刷新数据，之后再上拉加载，上拉加载函数就不会触发了

**Comment by dcloudhdx** [comment]
HBuilderX 版本多少？

**Comment by 17602260250** [comment]
hbuilderX  2.4.2.20191115

**Comment by 17602260250** [comment]
怎么解决呀，是代码有问题吗

**Comment by 17602260250** [comment]
没人在吗

**Comment by myssru** [comment]
> 没人在吗

哈哈哈，还在吗？你当这是QQ聊天呢

**Comment by 17602260250** [comment]
微信不行吗

**Comment by lincenying** [comment]
this.newsList[e]['end'] == 'false'
===>
this.newsList[e]['end'] == false

**Comment by wakaryry** [comment]
我也有这个问题来了。

- 安卓下，内容满一个list高度后，无法继续加载更多；
- 加载更多之后，刷新一下，然后无法触发加载更多；

**Comment by dcloudhdx** [comment]
举例说明下
第一次显示为10条，每次下拉增加10条，当第一次上拉触发loadmore事件，记录数据长度为10，数据被更新为20后，记录的仍然是10
开始下拉刷新，数据又被重置10，此时进行上拉加载操作，数据长度没有发生变化，所以没有再次触发loadmore，需要在下拉刷新后重置loadmore，`this.$refs["list"].resetLoadmore()`;
参考文档 https://uniapp.dcloud.net.cn/component/list

**Comment by wakaryry** [comment]
https://github.com/dcloudio/uni-app/issues/1958

解决了。谢谢
