### ISSUE TITLE
uni-app 组件编译模式 +"renderer":"native"原生渲染模式模式打出来的app是不是纯原生的而不是基于webview的？

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-app#1023]
uni-app 组件编译模式 +"renderer":"native"原生渲染模式模式打出来的app是不是纯原生的而不是基于webview的？
我看离线打包出来的东西，是放到www文件夹下的，这不就是webview么？我要打包后是纯原生项目怎么办呢？

**Comment by fxy060608** [comment]
renderer:native 表示渲染是原生渲染，编译打包的内容是 js 代码，可选择混淆加密
