### ISSUE TITLE
App nvue专用组件中的list能否添加代码控制滚动呢?

### ISSUE THREAD

**Issue by lincenying** [dcloudio/uni-app#1024]
**新功能描述**
list组件可以实现用代码控制滚到到何处, 或者当`pagingEnabled="true"`时, 可以控制跳转到某页

**现状及问题**
比如我拿list组件来做仿抖音上下滑动的视频, 我想在当前视频播放完后, 自动跳到下一个视频, 现在好像实现不了

**尝试方案**
没有找到有效的方案

**补充信息**
[其它你认为有参考价值的信息]

**Comment by Wangyaqi** [comment]
list也可以使用scrollToElement ，参考 [https://weex.apache.org/zh/docs/components/list.html#%E6%89%A9%E5%B1%95](https://weex.apache.org/zh/docs/components/list.html#%E6%89%A9%E5%B1%95)

**Comment by lincenying** [comment]
@Wangyaqi 实现了, 非常感谢...
