### ISSUE TITLE
mpvue微信小程序转uni-app，组件内的样式不生效

### ISSUE THREAD

**Issue by foreverrice** [dcloudio/uni-app#1025]
之前的mpvue微信小程序转uni-app,mpvue是没有自定义组件这一说；
目前写的组件的页面样式不生效，放到页面中才生效；
写看了微信小程序文档：
Component({
  options: {
    styleIsolation: 'isolated'
  }
})
这块配置代码应该放哪可以生效？

**Comment by wukuy** [comment]
同问
