### ISSUE TITLE
h5端与app端new Date()处理结果不一致

### ISSUE THREAD

**Issue by vanbolee** [dcloudio/uni-app#1029]
**问题描述**
new Date('2019-11-22T12:53:26.66')在h5端与app端显示时间不同，app返回时间多了8小时

**复现步骤**
1.输入console.log(new Date('2019-11-22T12:53:26.66'))
2.查看打印数据

**系统信息:**
 - 发行平台: h5,app
 - HBuilderX版本 2.4.2.20191115

**Comment by Wangyaqi** [comment]
用运行这个app的手机打开这个h5也是不一致吗？

**Comment by vanbolee** [comment]
> 用运行这个app的手机打开这个h5也是不一致吗？

重新测试了下，用手机运行h5跟app目前均返回正常
目前问题有：用数据线连接电脑，运行到手机，hbx控制台打印结果不正确
