### ISSUE TITLE
Android开局bug帮忙看一下，无法进去应用

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#1031]
![image](https://user-images.githubusercontent.com/7576559/69537139-68837200-0fba-11ea-9a7f-0cb85e4d9e23.png)

![image](https://user-images.githubusercontent.com/7576559/69537171-7cc76f00-0fba-11ea-9e1c-c5d0be2198ad.png)

![image](https://user-images.githubusercontent.com/7576559/69537189-8650d700-0fba-11ea-870e-ee8c042ef8ed.png)

![image](https://user-images.githubusercontent.com/7576559/69537222-a2ed0f00-0fba-11ea-8d1a-ee65d7837031.png)

![image](https://user-images.githubusercontent.com/7576559/69537241-ada7a400-0fba-11ea-851e-42b95dcdfd43.png)

![image](https://user-images.githubusercontent.com/7576559/69537249-b4361b80-0fba-11ea-8632-f5c3d17116c7.png)

![image](https://user-images.githubusercontent.com/7576559/69537257-ba2bfc80-0fba-11ea-8d5f-1fb228a2b06f.png)

**Comment by wakaryry** [comment]
mp正常，h5正常，ios正常。就安卓不正常。无法进去。

**Comment by wakaryry** [comment]
我提取了一个最简单的示范，安卓虽然能够进去（有报错，不过能看到一个tab的内容），但是切换tab依然无法显示其它内容。

而且在nvue的调试下看了，安卓的样式很奇怪，又是left，又是margin的。

求帮忙一起解决下这个问题。app第一版即将上线，催得紧。

**Comment by Wangyaqi** [comment]
运行你发的压缩包里面的代码，没出现报错，其他tab是因为你的 myp-tab-page-container 只有一屏宽。写一下宽度就好了

**Comment by wakaryry** [comment]
![image](https://user-images.githubusercontent.com/7576559/69938125-73d52100-1517-11ea-9402-6286bd3a5269.png)

打开调试器就可以看到报错了。而且我的项目里面使用的时候里面会包裹scroll-view，安卓下就白屏。

以上的所有问题都只是在 **安卓** 上面可以出现。

现在加上屏宽已经可以切换了。

**Comment by wakaryry** [comment]
用2.4.4alpha去掉最外层scroll就好了。安卓也不白屏了。
