### ISSUE TITLE
ios app如何禁止测滑返回

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-app#1034]
ios app如何禁止测滑返回

**Comment by huanghaodong** [comment]
因为业务逻辑，必须禁止返回，但是ios 由测滑返回机制。请问这种情况如何处理，感觉这需求还是挺刚需的啊....

**Comment by Wangyaqi** [comment]
[https://uniapp.dcloud.io/collocation/manifest](https://uniapp.dcloud.io/collocation/manifest) 在这里搜popGesture

**Comment by huanghaodong** [comment]
非常感谢
