### ISSUE TITLE
css 问题

### ISSUE THREAD

**Issue by i5920** [dcloudio/uni-app#1035]
**问题描述**
正常开发中包括H5 ,app 调试都正常，在线打包app时出问题
css变灰属性
filter: grayscale(1);

**Comment by Wangyaqi** [comment]
没能复现？你说的出问题是filter: grayscale(1);不生效吗？ios端还是安卓端

**Comment by i5920** [comment]
> 没能复现？你说的出问题是filter：grayscale（1）;不强制吗？ios端还是安卓端

今天测试正常了
