### ISSUE TITLE
input无法保持焦点

### ISSUE THREAD

**Issue by qinkaiyuan** [dcloudio/uni-app#1037]
**问题描述**
uniapp开发，微信小程序平台

场景：聊天窗口

点击发送消息按钮后，input框会失去焦点，从而导致键盘隐藏；

但实际业务，参考微信，点击发送按钮后键盘也不会隐藏；

但目前uniapp并不支持此功能。

目前能想到的解决方案
1. 点击发送按钮后，通过延迟让input再次获取焦点，但存在键盘抖动问题，键盘收起又展开，用户体验极差，无法接受，

请问还有其他更好地实现方式吗

**Comment by zhetengbiji** [comment]
目前h5支持prevent修饰符，后续app端也将支持，小程序平台目前无法支持，也需要的话可以去小程序社区提需求。

**Comment by zhetengbiji** [comment]
> 阻止默认行为可以使用prevent事件修饰符，目前仅h5端支持，后续app端也将支持，小程序平台目前无法支持，需要的话可以去小程序社区提需求。

**Comment by qinkaiyuan** [comment]
> > 阻止默认行为可以使用prevent事件修饰符，目前仅h5端支持，后续app端也将支持，小程序平台目前无法支持，需要的话可以去小程序社区提需求。

是否可以理解为此需求在小程序平台无解？

**Comment by zhetengbiji** [comment]
> > > 阻止默认行为可以使用prevent事件修饰符，目前仅h5端支持，后续app端也将支持，小程序平台目前无法支持，需要的话可以去小程序社区提需求。
> 
> 是否可以理解为此需求在小程序平台无解？

不可以这样理解，当我们看到用户提出的需求后，app平台就开始支持，小程序平台的开发人员也一样，用户去提需求，开发人员就会考虑支持。

**Comment by qinkaiyuan** [comment]
> > > > 阻止默认行为可以使用prevent事件修饰符，目前仅h5端支持，后续app端也将支持，小程序平台目前无法支持，需要的话可以去小程序社区提需求。
> > 
> > 
> > 是否可以理解为此需求在小程序平台无解？
> 
> 不可以这样理解，当我们看到用户提出的需求后，app平台就开始支持，小程序平台的开发人员也一样，用户去提需求，开发人员就会考虑支持。

那是不是此时此刻，还没有解决办法？

您说的提需求去哪里提，在这里提出来可以吗？

**Comment by myssru** [comment]
> > > > > 阻止默认行为可以使用prevent事件修饰符，目前仅h5端支持，后续app端也将支持，小程序平台目前无法支持，需要的话可以去小程序社区提需求。
> > > 
> > > 
> > > 是否可以理解为此需求在小程序平台无解？
> > 
> > 
> > 不可以这样理解，当我们看到用户提出的需求后，app平台就开始支持，小程序平台的开发人员也一样，用户去提需求，开发人员就会考虑支持。
> 
> 那是不是此时此刻，还没有解决办法？
> 
> 您说的提需求去哪里提，在这里提出来可以吗？

这吧：https://developers.weixin.qq.com/community/develop/mixflow

**Comment by CheJJ** [comment]
兄弟，别听他们瞎说，就这在里提。
尽管提，你先写下来。
回头我打电话给麻花腾，让他支持一下。

**Comment by zhetengbiji** [comment]
H5 以及 App 平台V3编译模式已 支持 prevent 修饰符
