### ISSUE TITLE
不支持微信小程序的 <page-meta> 组件

### ISSUE THREAD

**Issue by Cople** [dcloudio/uni-app#1042]
**问题描述**
<page-meta> 不起作用

**复现步骤**
```
<page-meta
  page-style="color: green"
></page-meta>
```

**预期结果**
更改页面属性

**实际结果**
无效

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
<page-meta> 必须是页面内的第一个节点。
https://developers.weixin.qq.com/miniprogram/dev/component/page-meta.html

**Comment by dcloudhdx** [comment]
HBuilderX 2.5.2+ 已支持
