### ISSUE TITLE
横竖屏适配BUG

### ISSUE THREAD

**Issue by trojanliu** [dcloudio/uni-app#1043]
### 问题描述

横屏打开示例页面, 手机旋转为竖屏, 则页面格局乱了.被撑爆了.  

### 复现步骤

1. 

并非个例, 示例代码大部分都这样
https://uniapp.dcloud.io/h5/pages/extUI/grid/grid

2. 
![22491574761171_ pic](https://user-images.githubusercontent.com/8016811/69617854-d50e7780-1073-11ea-9236-27e77acd0099.jpg)
![22501574761172_ pic](https://user-images.githubusercontent.com/8016811/69617877-df307600-1073-11ea-812b-627ba10b71e0.jpg)

4. 
页面挤爆

### 期望行为

感觉源码没有考虑横竖屏问题, 应该采用min(宽度, 高度)作为字体大小等适配的依据.

### 报错信息

![22491574761171_ pic](https://user-images.githubusercontent.com/8016811/69617854-d50e7780-1073-11ea-9236-27e77acd0099.jpg)
![22501574761172_ pic](https://user-images.githubusercontent.com/8016811/69617877-df307600-1073-11ea-812b-627ba10b71e0.jpg)

以及横屏标题显示不全

### 系统信息

ios, android, chrome模拟器均可重现

**Comment by fish-uncle** [comment]
有解决方案吗？

**Comment by trojanliu** [comment]
应该是取横竖屏最小的宽度为宽度，取最大的高度为高度。无论方向



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: fish uncle <notifications@github.com&gt;
发送时间: 2019年12月10日 17:31
收件人: dcloudio/uni-app <uni-app@noreply.github.com&gt;
抄送: trojanliu <1017803223@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[dcloudio/uni-app] 横竖屏适配BUG (#1043)




有解决方案吗？

**Comment by trojanliu** [comment]
应该是取横竖屏最小的宽度为min(width,height)宽度，取最大的高度为max(width,height)高度。无论方向



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: fish uncle <notifications@github.com&gt;
发送时间: 2019年12月10日 17:31
收件人: dcloudio/uni-app <uni-app@noreply.github.com&gt;
抄送: trojanliu <1017803223@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[dcloudio/uni-app] 横竖屏适配BUG (#1043)




有解决方案吗？

**Comment by zfy199466** [comment]
请问这个问题解决了吗？我在iPhone上面也发现了这个问题

**Comment by Wangyaqi** [comment]
> 请问这个问题解决了吗？我在iPhone上面也发现了这个问题

更新到最新的HX试试
