### ISSUE TITLE
mac 升级10.15.1版本后就运行不了小程序环境

### ISSUE THREAD

**Issue by Mixlong** [dcloudio/uni-app#1046]
**问题描述**
 22:53:41.553 [微信小程序开发者工具] StatusCodeError: 400 - "{\"code\":40000,\"error\":\"错误 Error: EPERM: operation not permitted, open '/Users/huangjianglong/Desktop/Desktop/waibao/waibao/unpackage/dist/dev/mp-weixin/project.config.json'\"}"
22:53:41.557 [微信小程序开发者工具]
22:53:41.578 微信开发者工具打开项目失败，请参阅启动日志！
22:53:41.594 注：
22:53:41.610 1. 如果微信开发者工具已打开，关闭并重试
22:53:41.620 2. 请将微信开发者工具升级到最新版本！

**Comment by Wangyaqi** [comment]
重新安装微信开发者工具试试
