### ISSUE TITLE
uni.onNetworkStatusChange 检测网络状态是不是没用啊！急急急

### ISSUE THREAD

**Issue by lanfanxiou** [dcloudio/uni-app#1049]
uni.onNetworkStatusChange 检测网络状态是不是没用啊！急急急，
为什么uni.getNetworkType有效而uni.onNetworkStatusChange无效

**Comment by Wangyaqi** [comment]
测试onNetworkStatusChange可以正常使用，你用的HBuilderX版本是多少？运行在什么系统的手机上？说明一下系统版本

**Comment by lanfanxiou** [comment]
HBuilderX版本是:2.4.2 运行在网页和手机都不可以，
我为此新建了个项目，发现他会打印，但是是在过了两到三分钟后打印。
代码：onLoad() {
			var data=new Date;
			uni.onNetworkStatusChange(function(res){
				console.log("网络类型:"+res.networkType+data.getHours()+":"+data.getMinutes());
				console.log("网络状态:"+res.isConnected+data.getHours()+":"+data.getMinutes());
			})
		},












------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"王亚琪"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月28日(星期四) 晚上10:20
收件人:&nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&gt;;
抄送:&nbsp;"恋言叶N次方"<2723095144@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] uni.onNetworkStatusChange 检测网络状态是不是没用啊！急急急 (#1049)




测试onNetworkStatusChange可以正常使用，你用的HBuilderX版本是多少？运行在什么系统的手机上？说明一下系统版本

**Comment by Wangyaqi** [comment]
补充说明一下是安卓还是ios，还有系统版本

**Comment by lanfanxiou** [comment]
&nbsp;android 系统：逍遥模拟器|夜神模拟器，好像5.~|7.~，既然你测试没有问题，那就不必要深究下去，我百度了，也有人遇到这样的问题，都没有答案，那么可能就是当前设备的问题吧，
检查网络状态还有很多方法，还是谢谢你的回复。辛苦了。








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"王亚琪"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月29日(星期五) 晚上6:24
收件人:&nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&gt;;
抄送:&nbsp;"恋言叶N次方"<2723095144@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] uni.onNetworkStatusChange 检测网络状态是不是没用啊！急急急 (#1049)




补充说明一下是安卓还是ios，还有系统版本
