### ISSUE TITLE
nvue app ，web-view不显示

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-app#1050]
![image](https://user-images.githubusercontent.com/24872469/69778694-3b180d80-11e0-11ea-89a9-9ae2228907c5.png)

**Comment by huanghaodong** [comment]
没办法，改.vue了

**Comment by Wangyaqi** [comment]
给web-view一个高度试试，这块的实现可能有点问题，我看一下

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
