### ISSUE TITLE
编译版本 2.3.7 uni-app使用npm 导入的 mint-ui组件，在使用的时候报错

### ISSUE THREAD

**Issue by Thekingofweb** [dcloudio/uni-app#1051]
**问题描述**
[编译版本 2.3.7 uni-app使用npm 导入的 mint-ui组件，在使用的时候报错]

**复现步骤**
[复现问题的步骤]
安装成功以后 ，使用 
1、import {myButton} from "mint-ui"
2、Vue.component("my-button", myButton)
3、然后去 index.vue 中使用<my-button>test</mybutton>
4、真机运行的时候编译报错

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]
jsEnginScriptError
14:31:49.779 Component is not found in path "node-modules/muse-ui/dist/muse-ui.esm" (using by "pages/index/index");onAppRoute
14:31:49.800 e
14:31:49.819 e
14:31:49.860 value
14:31:49.879 Ct
14:31:49.899 xt
14:31:49.919 It
14:31:49.979 emit
14:31:49.999 emit
14:31:50.059 subscribeHandler
14:31:50.079 S
14:31:50.099 e
14:31:50.119 invokeHandler
14:31:50.159 invoke
14:31:50.179 invoke
14:31:50.199 X
14:31:50.239 jc
14:31:50.359 _loaded
14:31:50.419 consume
14:31:50.439 map@[native code]

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 Android 7.0
 - HBuilderX版本   HBuilderX 2.3.7.20191024
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [小米5]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by lincenying** [comment]
检查babel的配置,   都跑去加载  node-modules/muse-ui/dist/muse-ui.esm
