### ISSUE TITLE
nvue app 富文本显示异常，急急急

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-app#1054]
官网演示例子上的富文本字符串为：`'<div style="text-align:center;"><img src="https://img-cdn-qiniu.dcloud.net.cn/uniapp/images/uni@2x.png"/></div>'`

通过html-parser转成nodes后为
`
[{
  "name": "div",
  "attrs": {
    "style": "text-align:center;"
  },
  "children": [{
    "name": "img",
    "attrs": {
      "src": "https://img-cdn-qiniu.dcloud.net.cn/uniapp/images/uni@2x.png"
    }
  }]
}]
`

**nvue app**上
`<rich-text :nodes="nodes" ></rich-text>`
展示不出来

.vue上可以显示，没有看到相关差异说明，是bug吗？HBuilder X 2.4.2.20191115

**Comment by dcloudhdx** [comment]
参考新闻模板，https://github.com/dcloudio/uni-template-news/tree/master/pages/detail

```
function parseImgs(nodes) {
	nodes.forEach(node => {
		if (
			node.name === 'img' &&
			node.attrs &&
			node.attrs['data-img-size-val']
		) {
			const sizes = node.attrs['data-img-size-val'].split(',')
			const width = uni.upx2px(720 * 0.9)
			const height = parseInt(width * (sizes[1] / sizes[0]))
			node.attrs.style = `width:${width};height:${height};`
		}
		if (Array.isArray(node.children)) {
			parseImgs(node.children)
		}
	})
	return nodes
}
```

**Comment by Wangyaqi** [comment]
长时间未回复，暂时关闭
