### ISSUE TITLE
非H5端支持 Vue官方文档：Class 与 Style 绑定 中的 classObject 和 styleObject 语法

### ISSUE THREAD

**Issue by xlfsummer** [dcloudio/uni-app#1055]
**新功能描述**
非H5端支持 Vue官方文档：Class 与 Style 绑定 中的 classObject 和 styleObject 语法

**现状及问题**
非H5端不支持 Vue官方文档：Class 与 Style 绑定 中的 classObject 和 styleObject 语法
动态样式传递不方便

**尝试方案**
可将 style / class 对象转为字符串赋值

**Comment by Wangyaqi** [comment]
v3版本app端已经支持，其他端在完善中
