### ISSUE TITLE
打包安卓APP白屏，错误提示找不到任何相关信息

### ISSUE THREAD

**Issue by jerryyan1990** [dcloudio/uni-app#1057]
**问题描述**
打包成安卓APP后，在手机上安装白屏。真机调试出现如图错误，在论坛和网上找不到任何相关信息。
**复现步骤**
1.打包APP
2.在手机上安装APP
3.启动APP

**预期结果**
进入登录页面

**实际结果**
白屏

**系统信息:**
 - 发行平台: app
 - 操作系统：Android 10，Android 8
 - HBuilderX版本：2.4.2.20191115
 - uni-app版本 编译器版本：2.4.2
 - 设备信息 华为mate30pro5G，小米K20pro，一加3T，魅族16s

**补充信息**
错误信息：
 reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->TypeError: undefined is not an object (evaluating 'navigator.appName')

getTemplateInfo== template md5 c292fa8147f7c6de71ec6f85b55fab56 length 3250475 base64 md5 wpL6gUf3xt5x7G+FtV+rVg== response header {"templateSourceBase64MD5":["wpL6gUf3xt5x7G+FtV+rVg=="],"templateSourceMD5":["c292fa8147f7c6de71ec6f85b55fab56"]}

<img width="1251" alt="WX20191129-181703@2x" src="https://user-images.githubusercontent.com/12929365/69862014-86abe380-12d4-11ea-8aa7-86e4215da821.png">

**Comment by mdzxy** [comment]
我也碰见这个问题，现在一直卡住了，请问这个有解决方案吗？

**Comment by 393197906** [comment]
换技术吧  官方解决不好的  我看更新日志都两次提到 解决白屏问题了  结果到现在 ，也就是 2.4.6.20191210 这个版本  还是白屏  我是服了 毛用没有

**Comment by zhetengbiji** [comment]
从报错提示看，你是否有访问：navigator.appName
不可以使用dom、bom等接口

**Comment by AdminQQZ** [comment]
reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Exception: TypeError: undefined is not an object (evaluating 'navigator.appName')

**Comment by dcloudhdx** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
