### ISSUE TITLE
使用vue-cli创建项目，编译H5的upx转化成了%??%

### ISSUE THREAD

**Issue by YHaven** [dcloudio/uni-app#1058]
**问题描述**
使用vue-cli新建安装启动项目
npm install -g @vue/cli
vue create -p dcloudio/uni-preset-vue my-project
选择新闻或者helloword模板
运行H5 
npm run dev:h5

打开http://localhost:8080

样式错乱。
![image](https://user-images.githubusercontent.com/16415735/69863821-a80ece80-12d8-11ea-8f50-1ddcd9e1c00e.png)

**系统信息:**
 - 发行平台: H5平台
 - 如使用Vue-cli创建/运行项目

**补充信息**
环境问题？
_@dcloudio_vue-cli-plugin-uni 包里的webpackConfig
resolveLoader: {
        alias: {
          'vue-style-loader': resolve('packages/h5-vue-style-loader')
        }
      },

webpack 运行loader的时候引用了上层目录的vue-style-loader，没有引用当前目录下的packages/h5-vue-style-loader

导致upx无法转化

**希望信息**
希望能用vue-cli够正常编译

**Comment by lincenying** [comment]
+1

**Comment by yanxiaoleng** [comment]
+1

**Comment by yanxiaoleng** [comment]
![TIM截图20191202100611](https://user-images.githubusercontent.com/38320471/69925539-b8e35e00-14eb-11ea-947a-5261fe9d7071.png)

**Comment by zhetengbiji** [comment]
将依赖 @vue/cli-service 切换为3.x

**Comment by YHaven** [comment]
@vue/cli换成3.10.0  还是炸，换成3.12.1就好了
