### ISSUE TITLE
选择地址  实现全国范围内选择 uni.chooseLocation

### ISSUE THREAD

**Issue by zfjhui** [dcloudio/uni-app#1060]
**新功能描述**
uni.chooseLocation 实现全国范围内的选择 就像小程序端那样

**现状及问题**
不能统一开发  不是方便
**尝试方案**
自行封装 感觉不爽  感觉是个重复的轮子  官方实现  造福大家

**Comment by Wangyaqi** [comment]
你是指哪端这个api跟小程序不一样

**Comment by zfjhui** [comment]
app端  目前h5 小程序端的都是可以随便搜索全国范围内的地址的   就app端  另类

**Comment by Wangyaqi** [comment]
了解了，后续会优化这块

**Comment by a516117636** [comment]
uni.chooseLocation的bug这么多，这么久了，为什么不修复啊！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

**Comment by zhetengbiji** [comment]
> uni.chooseLocation的bug这么多，这么久了，为什么不修复啊！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！

有顺序

**Comment by a516117636** [comment]
> > uni.chooseLocation的bug这么多，这么久了，为什么不修复啊！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
> 
> 有顺序

修复uni.chooseLocation的bug有时间表吗？我看很多人都需要这个api，插件市场也没有完美的轮子。

**Comment by zhetengbiji** [comment]
> > > uni.chooseLocation的bug这么多，这么久了，为什么不修复啊！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
> > 
> > 
> > 有顺序
> 
> 修复uni.chooseLocation的bug有时间表吗？我看很多人都需要这个api，插件市场也没有完美的轮子。

虽然还没有具体的时间安排，但是将会提升此需求的优先级

**Comment by a516117636** [comment]
> > > > uni.chooseLocation的bug这么多，这么久了，为什么不修复啊！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
> > > 
> > > 
> > > 有顺序
> > 
> > 
> > 修复uni.chooseLocation的bug有时间表吗？我看很多人都需要这个api，插件市场也没有完美的轮子。
> 
> 虽然还没有具体的时间安排，但是将会提升此需求的优先级

强烈要求尽快修复，这个api不是说凑活能用，是完全没法用，相当于uniapp功能缺失，很难受的，尽快吧大佬们
