### ISSUE TITLE
ios13.2.3安装基座失败

### ISSUE THREAD

**Issue by qumin111** [dcloudio/uni-app#1061]
**问题描述**
开发一个app项目，在Hbuilder X2.4.4模拟真机运行ios，提示基座安装失败，在itools和pp助手上都手动安装了给定的iphone_base.ipa，但是还是安装不了。如下

**复现步骤**
提示：
**在hbuilderX /提示：**
正在安装手机端HBuilder调试基座...
21:45:06.967 安装失败 return code=-402620403，请手动安装D:\HBuilderX.2.4.4.20191129-alpha.full\HBuilderX\plugins\launcher\base\iPhone_base.ipa到手机上（可使用iTools安装），并重新运行真机调试。
21:45:06.988 已停止运行...
![微信截图_20191130215337](https://user-images.githubusercontent.com/15045461/69901391-ea5d0c00-13bb-11ea-9e74-d63384c67a94.png)

**在助手软件上安装提示：**
安装包失败
![微信截图_20191130215346](https://user-images.githubusercontent.com/15045461/69901393-f2b54700-13bb-11ea-80a6-21981cb2a730.png)

我用的ios是 13.2.3的系统，不管怎么弄都是上面这个结果；后来我用同事的手机，她是旧系统，就一下安装成功了，是ios最新系统不兼容吗？该怎么解决这个问题啊 ，很着急啊

**Comment by zhetengbiji** [comment]
截图看不到

**Comment by calmchang** [comment]
我也是 安装失败了我是14.2的系统，现在没人用itools这种工具了吧，麻烦官方尽快修正哦

**Comment by ArrayDC** [comment]
请更新到最新版本HBuilderX
