### ISSUE TITLE
checkbox组件无法点击

### ISSUE THREAD

**Issue by ay8yt** [dcloudio/uni-app#1062]
浏览器环境下测试

![image](https://user-images.githubusercontent.com/14680564/69915634-3c6d6280-148c-11ea-956b-54b62a6360d0.png)

`
<view>
	<checkbox-group>
					<label>
						<checkbox value="cb" checked="true" />选中
					</label>
					<label>
						<checkbox value="cb" />未选中
					</label>
				</checkbox-group>
			</view>
			 <view>
				 <radio-group>
					<label class="radio"><radio value="r1" checked="true" />选中</label>
					<label class="radio"><radio value="r2" />未选中</label>
				 </radio-group>
			</view>
`
这是官方文档的代码案例
代码中的radio是为了进行对比。
checkbox点击是无效的。

**Comment by Wangyaqi** [comment]
没发现你说的不能点击的问题，看下有没有报错什么的

**Comment by qinkaiyuan** [comment]
switch type="checkbox"  无法显示选中效果， 删除type="checkbox"   使用swtich则正常

**Comment by Wangyaqi** [comment]
> switch type="checkbox" 无法显示选中效果， 删除type="checkbox" 使用swtich则正常

新问题开新帖说明一下，也方便其他有同样问题的人查看。我在app端、微信小程序端、H5端都没有复现你说的这个问题

**Comment by Wangyaqi** [comment]
长时间未回复，暂时关闭
