### ISSUE TITLE
@click、@touchmove等事件中， Event对象的e.stopPropagation()为空函数，无法阻止事件冒泡

### ISSUE THREAD

**Issue by kang0221** [dcloudio/uni-app#1067]
**问题描述**
@click、@touchmove等事件中， e.stopPropagation()无法阻止事件冒泡

**复现步骤**
```
<view @touchmove="touchmove1" style="width: 100%;height: 200px; background-color: #000000;">
  <view @touchmove="touchmove2" style="width: 50%;height: 100px; background-color: #F0AD4E;">
    点击
  </view>
</view>

method:{
  touchmove1(e) {
    console.log("touchmove1")
  },
  touchmove2(e) {
    console.log("touchmove2")
    e.stopPropagation();
    e.preventDefault();
    return false
  }
}
```
**预期结果**
touchmove2

**实际结果**
touchmove2
touchmove1

**系统信息:**
 - 发行平台: [5+ App]
 - 操作系统[ Android 10.0]
 - HBuilderX版本 [2.4.2.20191115]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [一加6T]

**补充信息**
Event对象的 e.stopPropagation(); e.preventDefault();都是function noop() {}函数

**Comment by zhetengbiji** [comment]
只支持使用修饰符，不支持使用stopPropagation，因为这里的event对象并非浏览器的evnet对象，其本来没有stopPropagation方法，文档中也从未提及支持stopPropagation方法，实现中有stopPropagation方法是为了避免开发者使用引用的第三方代码使用了stopPropagation后报错。

**Comment by kang0221** [comment]
@zhetengbiji 没用办法通过js实现阻止冒泡吗？

**Comment by zhetengbiji** [comment]
> @zhetengbiji 没用办法通过js实现阻止冒泡吗？

目前不支持，当前架构逻辑层和视图层是分离的，异步通讯，即使部分平台（除H5）勉强支持，由于通讯的延时，效果也不理想。

**Comment by kang0221** [comment]
> > @zhetengbiji 没用办法通过js实现阻止冒泡吗？
> 
> 目前不支持，当前架构逻辑层和视图层是分离的，异步通讯，即使部分平台（除H5）勉强支持，由于通讯的延时，效果也不理想。

好吧，明白啦！谢谢

**Comment by gd4Ark** [comment]
@kang0221 遇到相同的问题，请问有解决方案吗？

**Comment by kang0221** [comment]
> @kang0221 遇到相同的问题，请问有解决方案吗？

没有办法。要么用修饰符，要么避免这种写法。
