### ISSUE TITLE
page.json app-plus buttons text文字只能显示2个吗？

### ISSUE THREAD

**Issue by i5920** [dcloudio/uni-app#1068]
page.json app-plus buttons text文字只能显示2个吗？

**Comment by zhetengbiji** [comment]
设置width属性应该可以放更多的字

**Comment by i5920** [comment]
@zhetengbiji 在h5没有问题就在app上面有问题

**Comment by zhetengbiji** [comment]
> @zhetengbiji 在h5没有问题就在app上面有问题

h5本来没有plus相关的东西，为了方便开发者模拟了app端的部分功能，不过由于和原生渲染存在差异，部分细节模拟的不是很一致。
