### ISSUE TITLE
rpx在h5上 不起作用

### ISSUE THREAD

**Issue by cwwise** [dcloudio/uni-app#1069]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
升级npm依赖后 rpx在h5上就不起作用，之前是可以的。

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看
通过 vue create -p dcloudio/uni-preset-vue my-project 创建项目，然后运行在h5上。
yarn serve

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
使用rpx应该是可以达到适配的效果，现在的结果是出现乱码。

**实际结果**
[这里请贴上你的报错截图或文字]
css样式中 设置为rpx之后，会显示成下面这样。
![截屏2019-12-03上午11 23 25](https://user-images.githubusercontent.com/15242824/70018352-d0d8e180-15c0-11ea-8a11-3ee34720a7bb.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]
uni-app v2.4.2
uni-app cli v2.0.0-24220191115006

Environment Info:

  System:
    OS: macOS 10.15.1
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 12.12.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: Not Found
    Safari: 13.0.3
  npmPackages:
    @dcloudio/uni-app-plus: ^2.0.0-24220191115006 => 2.0.0-24220191115006 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-cli-shared: ^2.0.0-24220191115006 => 2.0.0-24220191115006 
    @dcloudio/uni-h5: ^2.0.0-24220191115006 => 2.0.0-24220191115006 
    @dcloudio/uni-helper-json: * => 1.0.3 
    @dcloudio/uni-mp-alipay: ^2.0.0-24220191115006 => 2.0.0-24220191115006 
    @dcloudio/uni-mp-baidu: ^2.0.0-24220191115006 => 2.0.0-24220191115006 
    @dcloudio/uni-mp-qq: ^2.0.0-24220191115006 => 2.0.0-24220191115006 
    @dcloudio/uni-mp-toutiao: ^2.0.0-24220191115006 => 2.0.0-24220191115006 
    @dcloudio/uni-mp-weixin: ^2.0.0-24220191115006 => 2.0.0-24220191115006 
    @dcloudio/uni-stat: ^2.0.0-24220191115006 => 2.0.0-24220191115006 
    @dcloudio/uni-template-compiler: ^2.0.0-24220191115006 => 2.0.0-24220191115006 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-24220191115006 => 2.0.0-24220191115006 
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-24220191115006 => 2.0.0-24220191115006 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-24220191115006 => 2.0.0-24220191115006 
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-24220191115006 => 2.0.0-24220191115006 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-24220191115006 => 2.0.0-24220191115006 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  3.12.1 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.1.1 
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1 
    @vue/cli-plugin-router:  4.1.1 
    @vue/cli-plugin-vuex:  4.1.1 
    @vue/cli-service: ^4.1.0 => 4.1.1 
    @vue/cli-shared-utils:  4.1.1 
    @vue/component-compiler-utils:  3.0.2 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.10 => 2.6.10 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.7.2 
    vue-router:  3.0.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.0.1 => 3.1.2 
  npmGlobalPackages:
    @vue/cli: 4.0.4

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
这个问题我也不太明白，主要是没有记录package.json，所以不知道之前的依赖版本号。之前的版本是可以的，前两天提示升级之后 在h5上就不起作用了。也不知道是我哪里写的有问题。

**Comment by Wangyaqi** [comment]
使用vue-cli 3.10 , 下版会适配4.x

**Comment by lincenying** [comment]
"@vue/cli-plugin-babel": "3.12.1",
"@vue/cli-service": "3.12.1",

**Comment by i5920** [comment]
使用upx

**Comment by cwwise** [comment]
换成3.1的版本就可以了
