### ISSUE TITLE
swiper组件滑动过程会突然卡住过几秒后恢复正常

### ISSUE THREAD

**Issue by zbjy** [dcloudio/uni-app#107]
压缩文件里的是视频文件，需要下载下来观看效果
[swiper滑动bug.zip](https://github.com/dcloudio/uni-app/files/2666571/swiper.bug.zip)

**Comment by mengerzhuanyong** [comment]
这个怎么直接就关闭了，是怎么解决的呀，当item个数大于3的时候卡顿非常明显，可以说是必卡！～
