### ISSUE TITLE
vue-cli创建的项目安装sass报错

### ISSUE THREAD

**Issue by qianjingxxxi** [dcloudio/uni-app#1070]
**问题描述**
[问题描述：vue-cli创建项目，使用uni-ui需要安装sass，然后报错

**复现步骤**
[复现问题的步骤]
1. 创建项目：vue create -p dcloudio/uni-preset-vue my-project
2. 安装插件：插件市场按文档安装
3. 安装sass：cnpm sass-loader node-sass --save-dev

**实际结果**
![屏幕快照 2019-12-03 11 44 18](https://user-images.githubusercontent.com/22724932/70018822-498c6d80-15c2-11ea-80ed-dac47478ab62.png)

**系统信息:**
 -  "node-sass": "^4.13.0",
 - "sass-loader": "^8.0.0",
 - "node.js":v10.15.3

 - HBuilderX版本:2.4.2.20191115
 - uni-app版本 :> xnserve-pro@0.1.0 info /Users/qianjing/xnserve-pro
> node node_modules/@dcloudio/vue-cli-plugin-uni/commands/info.js

uni-app v2.4.2
uni-app cli v2.0.0-24220191115006

Environment Info:

  System:
    OS: macOS Sierra 10.12.6
    CPU: (4) x64 Intel(R) Core(TM) i5-5250U CPU @ 1.60GHz
  Binaries:
    Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
    Yarn: Not Found
    npm: 6.12.1 - ~/.nvm/versions/node/v10.15.3/bin/npm
  Browsers:
    Chrome: 78.0.3904.108
    Firefox: 65.0.1
    Safari: 12.1.2
  npmPackages:
    @dcloudio/uni-app-plus: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-h5: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-helper-json: * => 1.0.3
    @dcloudio/uni-mp-alipay: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-mp-baidu: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-mp-qq: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-mp-toutiao: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-mp-weixin: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-stat: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-template-compiler: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  3.12.1
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.1.1
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-plugin-router:  4.1.1
    @vue/cli-plugin-vuex:  4.1.1
    @vue/cli-service: ^4.1.0 => 4.1.1
    @vue/cli-shared-utils:  3.12.1
    @vue/component-compiler-utils:  3.0.2
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.2
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.2
  npmGlobalPackages:
    @vue/cli: 4.1.1

**补充信息**

**Comment by Wangyaqi** [comment]
在HBuilderX里面设置一下node路径试试

**Comment by qianjingxxxi** [comment]
> 在HBuilderX里面设置一下node路径试试无用

**Comment by Wangyaqi** [comment]
用npm或者yarn不用cnpm也是报这种错吗

**Comment by Wangyaqi** [comment]
更新HBuilderX到最新alpha版，重新配置HBuilderX内使用的node路径为本机node路径
