### ISSUE TITLE
Error: Loading chunk * failed.

### ISSUE THREAD

**Issue by QTTQ** [dcloudio/uni-app#1072]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
H5端页面首次加载时有时会 报Error: Loading chunk * failed .  

 这是个很严重的问题，严重影响H5端 用户体验 流失公司用户
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Wangyaqi** [comment]
可以配置一下超时时间  https://uniapp.dcloud.io/collocation/manifest?id=h5-async

**Comment by cathe-zhang** [comment]
同遇到，经常性的出现，总是有某些页面loading chunk failed，但是在pc端看了对应的chunk文件是可以访问的，求解决啊

**Comment by cathe-zhang** [comment]
网上查到的都是说超时时间，但是根本就不是超时时间的问题，一进页面就报这个错误。

**Comment by zhetengbiji** [comment]
> 网上查到的都是说超时时间，但是根本就不是超时时间的问题，一进页面就报这个错误。

可以在网络面板查看加载时间

**Comment by cathe-zhang** [comment]
> > 网上查到的都是说超时时间，但是根本就不是超时时间的问题，一进页面就报这个错误。
> 
> 可以在网络面板查看加载时间

我抓个包试试

**Comment by cathe-zhang** [comment]
> > 网上查到的都是说超时时间，但是根本就不是超时时间的问题，一进页面就报这个错误。
> 
> 可以在网络面板查看加载时间

大佬问一下，manifest.json文件，在外层配了async还需要在h5的对象下配置async吗

**Comment by cathe-zhang** [comment]
> > 网上查到的都是说超时时间，但是根本就不是超时时间的问题，一进页面就报这个错误。
> 
> 可以在网络面板查看加载时间

我抓了一下包，加载失败的那个chunk的链接好像被encode了，然后就找不到这个js了

**Comment by cathe-zhang** [comment]
> > 网上查到的都是说超时时间，但是根本就不是超时时间的问题，一进页面就报这个错误。
> 
> 可以在网络面板查看加载时间

只有手机端有问题，PC端不会出现，跟用的是npm私有仓库有关系吗

**Comment by zhetengbiji** [comment]
> > > 网上查到的都是说超时时间，但是根本就不是超时时间的问题，一进页面就报这个错误。
> > 
> > 
> > 可以在网络面板查看加载时间
> 
> 只有手机端有问题，PC端不会出现，跟用的是npm私有仓库有关系吗

无，和网络有关系，手机用Chrome远程调试看看

**Comment by baicuhaha** [comment]
> > > 网上查到的都是说超时时间，但是根本就不是超时时间的问题，一进页面就报这个错误。
> > 
> > 
> > 可以在网络面板查看加载时间
> 
> 只有手机端有问题，PC端不会出现，跟用的是npm私有仓库有关系吗

大佬解决这个问题了吗？ 我现在也遇到这个问题 ，界面不停的报  网络有问题  超时时间也设置了 但是还是没有用

**Comment by cathe-zhang** [comment]
我这边好像暂时没问题了，之前是服务器文件缓存问题，加了CDN之后就好了

**Comment by caizhuorongs** [comment]
遇到了相同的问题，求解决的方法，加了cdn也没用

**Comment by zhetengbiji** [comment]
> 遇到了相同的问题，求解决的方法，加了cdn也没用

排查参考： https://ask.dcloud.net.cn/article/37065
