### ISSUE TITLE
微信小程序下v-if v-else-if v-else无法预期执行,会默认进入到v-if，不管判断条件是否正确,依旧会渲染

### ISSUE THREAD

**Issue by delfws** [dcloudio/uni-app#1075]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
微信小程序下v-if v-else-if v-else无法预期执行,会默认进入到v-if，不管判断条件是否正确
**复现步骤**
[复现问题的步骤]
1.  写一端v-if v-else-if的html
![image](https://user-images.githubusercontent.com/24715927/70115544-018d4980-169b-11ea-84dc-080936729aaa.png)

2.在v-if里面使用方法调用
![image](https://user-images.githubusercontent.com/24715927/70115683-7a8ca100-169b-11ea-8438-236954e0f3ab.png)

v-if总是会被优先渲染，不管条件是否正确。
encodeTextMessage方法总会被执行
很烦，我需要在二级下做判断。

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 mac 10.15.1
 - HBuilderX版本 HBuilderX 2.4.2.20191115
 - uni-app版本 使用HBuilderX工具创建
 - 设备信息 微信开发者工具

**Comment by Wangyaqi** [comment]
没能复现此问题，可以上传一下精简之后的项目

**Comment by delfws** [comment]
> 没能复现此问题，可以上传一下精简之后的项目

不好意思精简之后好像确实无法复现，暂时不知道怎么复现。
