### ISSUE TITLE
嵌套v-for内层获取不到item

### ISSUE THREAD

**Issue by MarvinXu** [dcloudio/uni-app#1077]
**问题描述**
内层调用click时报错 “v-for 暂不支持循环数据： ”，获取到的item为当前vue实例
仅微信小程序报错，h5正常

**复现步骤**
1. cli创建项目，选择默认模板
`vue create -p dcloudio/uni-preset-vue my-project`
2. demo代码
```vue
<template>
  <view class="content">
    <view v-for="item in objList" :key="item.dataKey">
      <text>{{item.name}}</text>
      <button 
        :class="{active: isActive(child)}"
        v-for="child in obj[item.dataKey]" 
        :key="child.key" 
        @click="onClick(child)"
      >
        {{child.value}}
      </button>
    </view>
  </view>
</template>

<script>
  export default {
    data() {
      return {
        title: 'Hello',
        objList: [
          {
            name: 'aa',
            dataKey: 'a'
          },
          {
            name: 'bb',
            dataKey: 'b'
          }
        ],
        obj: {
            a: [
              {
                key: 1,
                value: 1
              },
              {
                key: 2,
                value: 2
              }
            ],
            b: [
              {
                key: 1,
                value: 3
              },
              {
                key: 4,
                value: 4
              }
            ]
        }
      }
    },
    methods: {
      onClick(child){
        console.log(child)
      },
      isActive(child){
        return false
      }
    }
  }
</script>

```

**预期结果**
内层循环能正确获取到数据

**实际结果**
![image](https://user-images.githubusercontent.com/7382357/70137318-9fe3d400-16c8-11ea-95aa-56615e6efe04.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
System:
    OS: Windows 7
    CPU: (8) x64 Intel(R) Core(TM) i7-5700HQ CPU @ 2.70GHz
  Binaries:
    Node: 12.7.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.17.3 - C:\Program Files\nodejs\yarn.CMD
    npm: 6.10.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @dcloudio/uni-app-plus: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-h5: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-helper-json: * => 1.0.3
    @dcloudio/uni-mp-alipay: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-mp-baidu: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-mp-qq: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-mp-toutiao: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-mp-weixin: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-stat: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-template-compiler: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  3.12.1
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.1.1
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-plugin-router:  4.1.1
    @vue/cli-plugin-vuex:  4.1.1
    @vue/cli-service: ^4.1.0 => 4.1.1
    @vue/cli-shared-utils:  4.1.1
    @vue/component-compiler-utils:  3.0.2
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.2
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.2
  npmGlobalPackages:
    @vue/cli: Not Found
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
加上`:class="{active: isActive(child)}"` 就报错，去掉正常

**Comment by MarvinXu** [comment]
补充例子， 把普通list做chunk处理后也取不到内层item

```vue
<template>
  <view class="content">
    <view class="row" v-for="(row, index) in chunkedList" :key="`row${index}`">
      <button v-for="item in row" :key="item.id" @click="onClick(item)">{{item.id}}</button>
    </view>
  </view>
</template>

<script>
  export default {
    data() {
      return {
        chunkedList: [
          [
            {
              id: 1
            },
            {
              id: 2
            }
          ],
          [
            {
              id: 3
            },
            {
              id: 4
            }
          ]
        ]
      }
    },
    methods: {
      onClick(child){
        console.log(child)
      }
    }
  }
</script>
```

**Comment by dcloudhdx** [comment]
HBuilderX 2.4.8+ 已修复

**Comment by ben-lau** [comment]
@dcloudhdx 我还是有这种情况  我不是hbuilder创建的项目  跟题主问题一模一样  小程序才出现

Environment Info:

System:
OS: Windows 10
CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
Binaries:
Node: 12.12.0 - C:\Program Files\nodejs\node.EXE
Yarn: Not Found
npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
Browsers:
Edge: 44.18362.449.0
npmPackages:
@dcloudio/uni-app-plus: ^2.0.0-26120200226001 => 2.0.0-26120200226001
@dcloudio/uni-app-plus-nvue: 0.0.1
@dcloudio/uni-app-plus-nvue-v8: 0.0.1
@dcloudio/uni-cli-shared: ^2.0.0-26120200226001 => 2.0.0-26120200226001
@dcloudio/uni-h5: ^2.0.0-26120200226001 => 2.0.0-26120200226001
@dcloudio/uni-migration: ^2.0.0-26120200226001 => 2.0.0-26120200226001
@dcloudio/uni-mp-alipay: ^2.0.0-26120200226001 => 2.0.0-26120200226001
@dcloudio/uni-mp-baidu: ^2.0.0-26120200226001 => 2.0.0-26120200226001
@dcloudio/uni-mp-qq: ^2.0.0-26120200226001 => 2.0.0-26120200226001
@dcloudio/uni-mp-toutiao: ^2.0.0-26120200226001 => 2.0.0-26120200226001
@dcloudio/uni-mp-weixin: ^2.0.0-26120200226001 => 2.0.0-26120200226001
@dcloudio/uni-stat: 2.0.0-26120200226001
@dcloudio/uni-template-compiler: ^2.0.0-26120200226001 => 2.0.0-26120200226001
@dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-26120200226001 => 2.0.0-26120200226001
@dcloudio/vue-cli-plugin-uni: ^2.0.0-26120200226001 => 2.0.0-26120200226001
@dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-26120200226001 => 2.0.0-26120200226001
@dcloudio/webpack-uni-mp-loader: ^2.0.0-26120200226001 => 2.0.0-26120200226001
@dcloudio/webpack-uni-nvue-loader: 0.0.1
@dcloudio/webpack-uni-pages-loader: ^2.0.0-26120200226001 => 2.0.0-26120200226001
@vue/babel-helper-vue-jsx-merge-props: 1.0.0
@vue/babel-plugin-transform-vue-jsx: 1.0.0
@vue/babel-preset-app: 3.12.1
@vue/babel-preset-jsx: 1.1.1
@vue/babel-sugar-functional-vue: 1.0.0
@vue/babel-sugar-inject-h: 1.0.0
@vue/babel-sugar-v-model: 1.1.1
@vue/babel-sugar-v-on: 1.1.0
@vue/cli-overlay: 3.12.1
@vue/cli-plugin-babel: ^3.11.0 => 3.12.1
@vue/cli-service: ^3.11.0 => 3.12.1
@vue/cli-shared-utils: 3.12.1
@vue/component-compiler-utils: 3.0.0 (3.0.0)
@vue/preload-webpack-plugin: 1.1.1
@vue/web-component-wrapper: 1.2.0
mpvue-page-factory: 1.0.1
mpvue-template-compiler: 1.0.13
uni-h5-vue: 2.6.10
uni-mp-vue: 2.6.10
vue: ^2.6.11 => 2.6.11
vue-hot-reload-api: 2.3.4
vue-loader: 15.7.1 (15.7.1)
vue-router: 3.0.1
vue-style-loader: 4.1.2
vue-template-compiler: ^2.6.11 => 2.6.11
vue-template-es2015-compiler: 1.9.1
vuex: ^3.1.2 => 3.1.2
vuex-persistedstate: ^2.7.1 => 2.7.1
npmGlobalPackages:
@vue/cli: Not Found

**Comment by MarvinXu** [comment]
> HBuilderX 2.4.8+ 已修复

抱歉因为项目已经做完搁置一段时间了，一直没来得及验证，刚才重新试了一遍依旧有问题。
ps：提问说的是cli创建的项目，跟HBuilderX没有关系啊。。

**Comment by RadioAc** [comment]
> > HBuilderX 2.4.8+ 已修复
> 
> 抱歉因为项目已经做完搁置一段时间了，一直没来得及验证，刚才重新试了一遍依旧有问题。
> ps：提问说的是cli创建的项目，跟HBuilderX没有关系啊。。

@MarvinXu 解决了吗?

**Comment by MarvinXu** [comment]
官方没回复应该没解决吧……现在没做这块了。项目中遇到只能换个写法绕过这个问题



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 陈坤 <notifications@github.com&gt;
发送时间: 2020年5月14日 17:15
收件人: dcloudio/uni-app <uni-app@noreply.github.com&gt;
抄送: Marvin <272077995@qq.com&gt;, Mention <mention@noreply.github.com&gt;
主题: 回复：[dcloudio/uni-app] 嵌套v-for内层获取不到item (#1077)





   
HBuilderX 2.4.8+ 已修复
  
抱歉因为项目已经做完搁置一段时间了，一直没来得及验证，刚才重新试了一遍依旧有问题。
 ps：提问说的是cli创建的项目，跟HBuilderX没有关系啊。。
  
@MarvinXu 解决了吗?

**Comment by zjians** [comment]
遇到了同样问题，传递的参数变为了当前实例。。传参时用对象包一下可以在方法中获取到正确参数，@click=handleClick({item})这样能获取到正取参数，@click=handleClick(item)，这时的参数变为了Vue实例
