### ISSUE TITLE
请问nvue怎么设置图片高度自适应，设置了mode="widthFix"没有效果呀？

### ISSUE THREAD

**Issue by Liu-Peter** [dcloudio/uni-app#1078]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

请问nvue怎么设置图片高度自适应？

**复现步骤**

` <template>
	<div>
		<image class="test_img" src="../../static/images/test.png" mode="widthFix"></image>
	</div>
</template>
`
`<style>.div{width: 750rpx;}.test_img{width: 750rpx;}</style>`
**实际结果**
是的我的用法不对吗？目前没有什么效果，图片还拉伸了

**Comment by Wangyaqi** [comment]
需要自行设定宽高

**Comment by Liu-Peter** [comment]
> 需要自行设定宽高

意思是只能固定宽高是吧

**Comment by Wangyaqi** [comment]
对的

**Comment by Liu-Peter** [comment]
> 对的
好吧
