### ISSUE TITLE
编译钉钉小程序 宫格组件不能用。

### ISSUE THREAD

**Issue by lijx2018github** [dcloudio/uni-app#1079]
**问题描述**

Injection "grid" not found
 
**复现步骤** 

1.  官方demo 宫格部分无法使用

**Comment by Wangyaqi** [comment]
修复中

**Comment by Wangyaqi** [comment]
使用真机测试一下看，这个可能是支付宝小程序ide的Bug

**Comment by Wangyaqi** [comment]
使用真机测试一下看，这个可能是支付宝小程序ide的Bug
