### ISSUE TITLE
nvue使用barcode组件扫码成功后，返回值格式与文档不符

### ISSUE THREAD

**Issue by jaylin0522** [dcloudio/uni-app#1085]
**问题描述**
nvue中使用barcode组件，扫码成功后，返回值的格式与文档描述不符

**复现步骤**
[复现问题的步骤]
1.  访问带有barcode组件的nvue页面
2. 扫码，打印扫码成功返回值

**预期结果**
扫码结果存在message中
![image](https://user-images.githubusercontent.com/22398861/70291100-20afe680-1815-11ea-9eae-8f2d77174594.png)

**实际结果**
扫码结果存在detail.message中
![image](https://user-images.githubusercontent.com/22398861/70291137-40dfa580-1815-11ea-8544-7ff25076b8c5.png)

**系统信息:**
 - 发行平台: 5+APP
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本：2.4.2
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
猜测HBuilderX升级，更新返回值，文档未及时更新

**Comment by dcloudhdx** [comment]
感谢反馈，文档没有描述清楚，应该在 detail 中
