### ISSUE TITLE
nvue app中 与 小程序中使用@tap和@click是否有响应延迟区别

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-app#1092]
nvue app中 与 小程序中使用@tap和@click是否有响应延迟区别？
虽然感觉不出区别，但是还是想问设计者这个问题

**Comment by wakaryry** [comment]
应该是有的。至少在点击之后的效果设置上，hover-class的响应时间，感觉 Android 和 iOS就不一样。

**Comment by Wangyaqi** [comment]
没有区别
