### ISSUE TITLE
微信小程序 onError  未捕获生命周期函数中的异常

### ISSUE THREAD

**Issue by hxzAugustinus** [dcloudio/uni-app#1093]
**问题描述**
编译成微信小程序后  onError函数  未捕获异常

**复现步骤**
当报错的代码在page生命周期函数里时，不会触发；在methods下定义的函数会触发
![代码截图](https://user-images.githubusercontent.com/14306029/70372874-69ec5d00-191f-11ea-82a1-c628e8231b00.png)

**预期结果**
onError函数 有输出生命周期函数中的错误

**实际结果**
onError函数 无输出生命周期函数中的错误

**系统信息:**
 - 发行平台:  微信小程序
 - 操作系统 ：微信开发者工具
 - HBuilderX版本 ：2.4.2.20191115
 - uni-app v2.2.4
 - uni-app cli v2.0.0-24220191115006

**Comment by dcloudhdx** [comment]
更新HBuilderX 或 cli 已修复此问题
