### ISSUE TITLE
picker在iphone6p中无法弹出弹窗，其他机型正常

### ISSUE THREAD

**Issue by wYuJian** [dcloudio/uni-app#1097]
在H5中，picker在iphone6p中无法弹出弹窗，其他机型正常，
<view class="cu-form-group">
				<picker @change="PickerChangeTime" :value="indexTime" :range="picker2" range-key='a_username'>
					<view class="picker Custom-style flex justify-between">
						<text >{{indexTime>-1?picker2[indexTime].a_username+'-'+picker2[indexTime].a_name:placeholderTxt}}</text>
						<view class="flex align-center">
							<view class="right-img"></view>
						</view>
					</view>
				</picker>
			</view>

**Comment by wYuJian** [comment]
<view class="cu-form-group">
				<picker @change="PickerChangeTime" :value="indexTime" :range="picker2" range-key='a_username'>
					<view class="picker Custom-style flex justify-between">
						<text >{{indexTime>-1?picker2[indexTime].a_username+'-'+picker2[indexTime].a_name:placeholderTxt}}</text>
						<view class="flex align-center">
							<view class="right-img"></view>
						</view>
					</view>
				</picker>
			</view>

**Comment by wYuJian** [comment]
<view class="cu-form-group">
				<picker @change="PickerChangeTime" :value="indexTime" :range="picker2" range-key='a_username'>
					<view class="picker Custom-style flex justify-between">
						<text >{{indexTime>-1?picker2[indexTime].a_username+'-'+picker2[indexTime].a_name:placeholderTxt}}</text>
						<view class="flex align-center">
							<view class="right-img"></view>
						</view>
					</view>
				</picker>
			</view>

**Comment by wYuJian** [comment]
<picker @change="PickerChangeTime" :value="indexTime" :range="picker2" range-key='a_username'>
					<view class="picker Custom-style flex justify-between">
						<text >{{indexTime>-1?picker2[indexTime].a_username+'-'+picker2[indexTime].a_name:placeholderTxt}}</text>
						<view class="flex align-center">
							<view class="right-img"></view>
						</view>
					</view>
				</picker>

**Comment by zhetengbiji** [comment]
哪个浏览器？

**Comment by zhetengbiji** [comment]
测试无法复现，暂时关闭
