### ISSUE TITLE
createAnimation导出动画应该加入-webkit-

### ISSUE THREAD

**Issue by ben-lau** [dcloudio/uni-app#1099]
**问题描述**
uni.createAnimation的api创建、导出的动画，在h5端没加入-webkit-，导致在iPhone11promax微信中动画失效

**系统信息:**
Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.21.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.13.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @dcloudio/uni-app-plus: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-h5: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-mp-alipay: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-mp-baidu: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-mp-qq: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-mp-toutiao: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-mp-weixin: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/uni-stat:  2.0.0-24220191115006
    @dcloudio/uni-template-compiler: ^2.0.0-24220191115006 => 2.0.0-24220191115006       
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-24220191115006 => 2.0.0-24220191115006    
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-24220191115006 => 2.0.0-24220191115006 
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-24220191115006 => 2.0.0-24220191115006       
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-24220191115006 => 2.0.0-24220191115006
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.12.1
    @vue/babel-preset-jsx:  1.1.1
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.1.1
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.12.1
    @vue/cli-plugin-babel: ^3.11.0 => 3.12.1
    @vue/cli-service: ^3.11.0 => 3.12.1
    @vue/cli-shared-utils:  3.12.1
    @vue/component-compiler-utils:  3.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.1
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.1.2 => 3.1.2
    vuex-persistedstate: ^2.5.4 => 2.7.0
  npmGlobalPackages:
    @vue/cli: Not Found

**Comment by Wangyaqi** [comment]
目前测试不添加-webkit-在ios 13.3系统微信浏览器内访问可以正常动画，现代浏览器大多已经支持了标准属性。可以用无法正常动画的手机访问此链接[https://uniapp.dcloud.io/h5/pages/API/animation/animation](https://uniapp.dcloud.io/h5/pages/API/animation/animation) 看是否正常

**Comment by ben-lau** [comment]
目前出现问题就是在11promax上  我自己的css动画不添加-webkit-会没显示，加上了就显示了

**Comment by Wangyaqi** [comment]
试了Hello uni-app吗

**Comment by ben-lau** [comment]
hello的可以  但是我的代码的话  dev的可以  build的不行  build的话pc的都没动画

**Comment by ben-lau** [comment]
build出来之后动画连pc都不显示了  dev里是可以的
@Wangyaqi

**Comment by Wangyaqi** [comment]
你把你的项目精简一下发来我验证验证

**Comment by ben-lau** [comment]
这里是部分manifest配置
`
  "h5": {
    "title": "",
    "publicPath": "./",
    "router": { "base": "" },
    "async": { "delay": 600 },
    "optimization": { "treeShaking": { "enable": true } }
  },
`

这里是index.vue

`
<template>
  <view class="content">
    <view
      class="button"
      @click="buttonOnClick"
    >加入购物车</view>
    <view class="footer">
      <view
        class="cart"
        :animation="cartAnimationData"
      ></view>
    </view>
  </view>
</template>

<script>
const throttle = (func, wait) => {
  let timer;
  let previous = 0;
  return function() {
    let now = +new Date();
    let remaining = wait - (now - previous);
    if (remaining < 0) {
      if (timer) {
        clearTimeout(timer);
        timer = null;
      }
      previous = now;
      func.apply(this, arguments);
    } else if (!timer) {
      timer = setTimeout(() => {
        previous = new Date().getTime();
        timer = null;
        func.apply(this, arguments);
      }, remaining);
    }
  };
};
export default {
  data() {
    return {
      cartAnimationData: {}
    };
  },
  onLoad() {
    this._$data = {
      cartAnimation: uni.createAnimation()
    };
  },
  methods: {
    cartAction: throttle(function() {
      this._$data.cartAnimation
        .scale(1.2, 1.2)
        .step({ duration: 200, delay: 400 });
      this._$data.cartAnimation.scale(1, 1).step({ duration: 200, delay: 0 });
      this.cartAnimationData = {};
      setTimeout(() => {
        this.cartAnimationData = this._$data.cartAnimation.export();
      });
    }, 900),
    buttonOnClick() {
      this.cartAction();
    }
  }
};
</script>

<style>
.button {
  height: 100rpx;
  position: relative;
  background: #c4c4c4;
  text-align: center;
  line-height: 100rpx;
}

.footer {
  position: fixed;
  width: 100%;
  height: 100rpx;
  bottom: 0;
  padding: 0 30rpx;
  background: #c4c4c4;
}
.cart {
  width: 96rpx;
  height: 96rpx;
  position: absolute;
  top: -30rpx;
  background: #000;
}
</style>

`

这样子运行时有动画  build出来就没了
刚试了关闭treeshaking就出来了

**Comment by ben-lau** [comment]
@Wangyaqi 请问复现出来了么  我都找到原因了：是开了treeshaking就动画没了

**Comment by Wangyaqi** [comment]
处理中，感谢反馈

**Comment by zhetengbiji** [comment]
2.5.5 alpha 已修复

**Comment by ben-lau** [comment]
@zhetengbiji 
2.5.5alpha是哪个版本  我现在"^2.0.0-25120200103006"都还是没修复  动画依旧没有

**Comment by Wangyaqi** [comment]
> @zhetengbiji
> 2.5.5alpha是哪个版本 我现在"^2.0.0-25120200103006"，你们npm上最新版本都还是没修复 动画依旧没有

https://uniapp.dcloud.io/quickstart?id=_2-%e9%80%9a%e8%bf%87vue-cli%e5%91%bd%e4%bb%a4%e8%a1%8c 使用cli也可以创建alpha版本

**Comment by ben-lau** [comment]
这种bugfix不应该跟稳定版一起发的么

**Comment by ben-lau** [comment]
@Wangyaqi 什么时候更新到稳定版呢  不可能让我又重新创一个项目吧
