### ISSUE TITLE
nvue下纯native渲染post with application/x-www-form-urlencoded 有问题

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#1100]
- 2.4.2/2.4.4 alpha，其它未测试；
- nvue页面；
- uni-app模式；
- native渲染；

content-type 为 application/x-www-form-urlencoded 时，data 数据 打包有问题，后台接收数据异常。

```
b'{\n  "phone" : "17610779055",\n  "type" : "register",\n  "product" : 4\n}'
```

关掉native开关之后，数据正常：

```
b'phone=17610779055&type=register&product=4'
```

# 测试用例

就一个按钮，点击提交数据到服务器。没有任何的依赖。

```vue
<template>
	<view>
		<view style="height: 100rpx;"></view>
		<button @tap="toUni">uni request</button>
	</view>
</template>

<script>
	export default {
		methods: {
			toUni() {
				uni.request({
					header: {'Content-Type': 'application/x-www-form-urlencoded'},
					data: {
						phone: '17610771234',
						type: 'register',
						product: 4
					},
					method: 'POST',
					url: 'your url',
					success(res) {
						console.log("请求发送成功")
						console.log(res)
					},
					fail(err) {
						console.log("请求发送失败")
						console.log(err)
					}
				})
			}
		}
	}
</script>

<style>

</style>

```

希望确认一下这个问题，因为我 nvue 页面，关闭掉 native 之后，白屏，没有任何报错。打开 native 之后，数据打包又存在问题。

谢谢。

这个问题花费了差不多一个多星期才知道是什么地方引起的。

**Comment by Wangyaqi** [comment]
按照weex官方的文档 [https://weex.apache.org/zh/docs/modules/stream.html#fetch](https://weex.apache.org/zh/docs/modules/stream.html#fetch)

- 默认 Content-Type 是 application/x-www-form-urlencoded。
- 如果你需要通过 POST 发送 json 数据， 需要将 Content-Type 设为 application/json

**Comment by wakaryry** [comment]
意思时，`native`的时候，我设置了`Content-Type` 为 `application/x-www-form-urlencoded`，传入的 `data` 需要我自己打包成字符串？

**Comment by Wangyaqi** [comment]
看了下源码，我上面说的有点问题，这块我们内部应该处理了才对，我再验证一下

**Comment by wakaryry** [comment]
> 看了下源码，我上面说的有点问题，这块我们内部应该处理了才对，我再验证一下

好的。感觉这个是数据打包的问题。按照uni.request的接口，我们都是给Object，uni自己会根据content-type打包一次，然后再提交给weex。不知道是不是这样处理的。

**Comment by wakaryry** [comment]
https://github.com/dcloudio/uni-app/issues/1098

**Comment by leixingqiang** [comment]
新手入门
看你们说关闭掉 native 就能正常请求
但是 native 怎么关闭啊

**Comment by wakaryry** [comment]
@leixingqiang 应该已经解决了这个问题了的。另外在manifest.json里面有是否native的配置。
