### ISSUE TITLE
点击Slider值变化没有收到回调

### ISSUE THREAD

**Issue by xxfenxx** [dcloudio/uni-app#1101]
**问题描述**
Slider 滑动能改变value的值
点击 Slider 不能改变value的值

**Comment by Wangyaqi** [comment]
运行到哪端？

**Comment by xxfenxx** [comment]
> 运行到哪端？

iOS上

**Comment by xxfenxx** [comment]
@Wangyaqi 请问修复了没

**Comment by Wangyaqi** [comment]
没能复现这个问题，可以尝试更新HBuilderX最新的alpha版验证一下是不是还存在

**Comment by xxfenxx** [comment]
HBuilderX 2.4.6.20191210 依旧有这个问题，点击用于拖动的圆点，值没有变化，要用拖动手势拖动只才能发送变化 @Wangyaqi

**Comment by Wangyaqi** [comment]
ios版本多少
