### ISSUE TITLE
微信小程序中 $refs.xxx 不能获取到原生元素，可以获取到自定义组件的引用

### ISSUE THREAD

**Issue by UnableRegister** [dcloudio/uni-app#1102]
```
<w-tabs ref="tabs" />
<div ref="test" />
```
```
onReady () {
  console.log('$refs.tabs', this.$refs.tabs) // VueComponent
  console.log('$refs.test', this.$refs.test) // undefined
}
```
![编译后的模板](https://user-images.githubusercontent.com/38139058/70438105-0ea99e80-1ac8-11ea-80e6-343a5da1b89e.png)

![output](https://user-images.githubusercontent.com/38139058/70438265-6811cd80-1ac8-11ea-8cdb-d443617f32b2.png)

**Comment by Wangyaqi** [comment]
设定如此

**Comment by maicWorkGithub** [comment]
不解释一下或者扔个文档链接吗？

**Comment by zhetengbiji** [comment]
> 不解释一下或者扔个文档链接吗？

收到：

解释：view 是小程序的内置组件，不是 vue 组件，也没办法取到对应的 dom 节点。

[相关文档](https://uniapp.dcloud.io/use?id=%E5%AE%9E%E4%BE%8B%E5%B1%9E%E6%80%A7)

**Comment by maicWorkGithub** [comment]
谢谢
