### ISSUE TITLE
setStorageSync API只能在当前页面生效，到其它页面刷新时会被清空

### ISSUE THREAD

**Issue by ckisme** [dcloudio/uni-app#1103]
**问题描述**
在A页面里通过 uni.setStorageSync('state', '9999') 设置了个存储，在A页面刷新时没有问题，但是当你跳转到B页面时，刷新页面，setStorage记录被清除，

**预期结果**
在任何页面，只要是不主动清除，Storage记录不应该被清除

**实际结果**
只要不是设置存储的页面刷新，都会被清除

**系统信息:**
 - 发行平台:  微信小程序、H5平台
 - HBuilderX版本  2.4.5.2.2091209

**Comment by wakaryry** [comment]
async设置有问题吗？同步存储没有用过，我们直接使用的异步存储接口，好像没有问题。

**Comment by ckisme** [comment]
> async设置有问题吗？同步存储没有用过，我们直接使用的异步存储接口，好像没有问题。

就直接调用   uni.setStorageSync(key, value)  ，其它没做任何关于存储相关操作

**Comment by Wangyaqi** [comment]
运行到H5端吗？什么浏览器

**Comment by ckisme** [comment]
> 运行到H5端吗？什么浏览器

H5和微信小程序都是一样，小程序保存代码，重新加载时会把所有的存储清空。这是个新的空白项目测试。
chrome 版本 78.0.3904.108（正式版本） （64 位）

**Comment by zhetengbiji** [comment]
> > 运行到H5端吗？什么浏览器
> 
> H5和微信小程序都是一样，小程序保存代码，重新加载时会把所有的存储清空。这是个新的空白项目测试。
> chrome 版本 78.0.3904.108（正式版本） （64 位）

测试未复现，你可以在调试面板看一下存储的内容是否真的被删除了

**Comment by ckisme** [comment]
重新安装一次HBuilderX就不会自动删除了。不知道什么原因！

**Comment by zhetengbiji** [comment]
> 重新安装一次HBuilderX就不会自动删除了。不知道什么原因！

理论上没有关联
