### ISSUE TITLE
有没有类似fultter中类似dart:io开一个子进程/child process的功能

### ISSUE THREAD

**Issue by hugetiny** [dcloudio/uni-app#1105]
**新功能描述**
有没有类似fultter中类似dart:io开一个子进程/child process的功能

**现状及问题**
找不到类似dart:io的API

**Comment by Wangyaqi** [comment]
具体什么需求，对应dart或者flutter文档在哪

**Comment by zhetengbiji** [comment]
未内置此功能，可以参考官方的插件开发文档，自己扩展插件实现。

**Comment by hugetiny** [comment]
dart:io的文档：
https://api.dartlang.org/stable/2.7.0/dart-io/dart-io-library.html
参考Process说明 里面可以开一个子进程

**Comment by hugetiny** [comment]
dart:io的文档：
https://api.dartlang.org/stable/2.7.0/dart-io/dart-io-library.html
参考Process说明 里面可以开一个子进程

**Comment by zhetengbiji** [comment]
> dart:io的文档：
> https://api.dartlang.org/stable/2.7.0/dart-io/dart-io-library.html
> 参考Process说明 里面可以开一个子进程

暂无计划，可以参考官方的插件开发文档，自己扩展插件实现。

**Comment by hugetiny** [comment]
https://tencent.github.io/Hippy/#/core/introduction
参考腾讯新开源的框架Hippy
类似Hippy Core架构。uni-app有什么类似的功能去写一些C++的代码
