### ISSUE TITLE
nvue app 的refresh在某些情况下组件下拉后不消失

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-app#1107]
nvue app 的refresh组件在如下情况下拉后不消失：
[gif图片](http://chuantu.xyz/t6/703/1576047331x1033347913.gif)
**list列表内容不足一屏且不为空的情况下。**

经测试，bug出现时，请求已成功，且refresh的display属性已设为hide。
写法完全参照的nvue app 新闻项目模板，列表超过一屏或者列表为空时正常。

HBuilderX2.4.6.20191210

**Comment by dcloudhdx** [comment]
Android 还是 iOS，系统版本多少？

**Comment by huanghaodong** [comment]
> Android 还是 iOS，系统版本多少？

苹果6s plus ios 12.1.2

**Comment by huanghaodong** [comment]
> > Android 还是 iOS，系统版本多少？
> 
> 苹果6s plus ios 12.1.2



> Android 还是 iOS，系统版本多少？

另外能不能看一下这个问题

**Comment by hangaoke1** [comment]
同

**Comment by wakaryry** [comment]
我封装的list现在出现：

- 安卓下内容不足一个屏幕时可以加载更多，超过一个屏幕内容后，无法触发加载更多；
- 安卓和iOS加载更多之后，下拉刷新一下，然后就无法触发加载更多；

打算排查，直接写的list和封装之后list的区别。

**Comment by dcloudhdx** [comment]
Bug 已确认

**Comment by zhetengbiji** [comment]
HBuilderX 2.8.11 已修复
