### ISSUE TITLE
app端 uniapp 的 拿到的文件类型如何转换为file 对象 

### ISSUE THREAD

**Issue by cometang** [dcloudio/uni-app#1108]
第一次发现有框架 给个临时地址 不给文件的。不能给一个file对象？

**Comment by zhetengbiji** [comment]
已有计划，对原小程序风格File对象进行增强

**Comment by zhetengbiji** [comment]
H5端已有计划对原小程序风格“File”对象进行增强：返回原始File对象
App端运行在jsCore内，并非浏览器环境，并没有File类，后续会增加FileSystemManager，以获取文件的ArrayBuffer对象。

**Comment by bxpxqxd** [comment]
> 第一次发现有框架 给个临时地址 不给文件的。不能给一个file对象？

牛逼第一次。Weex有没有File对象？RN有没有File对象？Flutter有没有File对象？小程序有没有File对象？你咋不要document对象？
