### ISSUE TITLE
 uni-app小程序项目实战

### ISSUE THREAD

**Issue by zengxiaozeng** [dcloudio/uni-app#1110]
**新功能描述**
 uni-app小程序项目实战：https://juejin.im/post/5dcb77e9f265da4d260447c8

**现状及问题**
开发到上线全流程介绍  以及一些要踩的坑

**Comment by zengxiaozeng** [comment]
欢迎指教

**Comment by Wangyaqi** [comment]
欢迎到论坛或者QQ群去宣传
