### ISSUE TITLE
webview 安卓环境 postMessage没反应

### ISSUE THREAD

**Issue by javaAjun** [dcloudio/uni-app#1113]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  我在webview页面UniAppJSBridgeReady初始化完成后绑定一个按钮,点击调用 uni.postMessage ,uniapp端没反应,接收不到消息.
[或者可以直接贴源代码]
view - html代码: 
js: <script type="text/javascript" src="https://js.cdn.aliyun.dcloud.net.cn/dev/uni-app/uni.webview.1.5.2.js"></script>

![image](https://user-images.githubusercontent.com/38597827/70694835-7693fb00-1cfb-11ea-9313-510e479c2fdb.png)

uniapp端代码:
![image](https://user-images.githubusercontent.com/38597827/70694809-6b40cf80-1cfb-11ea-8102-4fe71f44bdbb.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号] 2.4.2
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus] 华为P20

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by javaAjun** [comment]
测试多次,确认有问题,点击按钮,点击事件是触发的,也调用了uni.postMessage方法,但是uniapp端就是收不到
QQ:594147030 可在官方群23私我

**Comment by Wangyaqi** [comment]
没能复现此问题，可以使用Hello uni-app测试一下是不是依然如此

**Comment by ldc2726** [comment]
@Wangyaqi 怎么会复现不了呢，就是接收不到啊
