### ISSUE TITLE
纯内网环境开发uniapp

### ISSUE THREAD

**Issue by LeoDys** [dcloudio/uni-app#1114]
**新功能描述**
纯内网环境开发uniapp

**现状及问题**
不了解如何在纯内网环境下开发和打包相关操作

**Comment by zhetengbiji** [comment]
https://ask.dcloud.net.cn/docs/#//ask.dcloud.net.cn/article/104

**Comment by bxpxqxd** [comment]
你的内网有多“纯”，如果真的彻底断网，你可能需要放弃，iOS或安卓应用的签名步骤似乎需要联网校验。

**Comment by LeoDys** [comment]
> 你的内网有多“纯”，如果真的彻底断网，你可能需要放弃，iOS或安卓应用的签名步骤似乎需要联网校验。

jks文件啥的都是现成的
真的是一点儿外网都没有的地儿
做好的app在纯内网环境下运行

**Comment by LeoDys** [comment]
> https://ask.dcloud.net.cn/docs/#//ask.dcloud.net.cn/article/104

看到离线打包教程了  谢谢你
