### ISSUE TITLE
支付宝自定义组件 slot 中 ref 无效

### ISSUE THREAD

**Issue by xlfsummer** [dcloudio/uni-app#1115]
**问题描述**
支付宝自定义组件 slot 中 ref 无效

**复现步骤**
![image](https://user-images.githubusercontent.com/20750969/70713978-2aa87c80-1d22-11ea-91cc-4fe762fa060a.png)

![image](https://user-images.githubusercontent.com/20750969/70713961-22504180-1d22-11ea-8833-b969eb5958ef.png)

demo repo:
https://github.com/xlfsummer/uniapp-demo-alipay-slot-ref

**预期结果**
$ref.b2 能取到 b 组件的实例

**实际结果**
![image](https://user-images.githubusercontent.com/20750969/70714007-35631180-1d22-11ea-8886-a4c53c13ccaf.png)

**Comment by Wangyaqi** [comment]
需要勾选“启用 component2 编译”
![image](https://user-images.githubusercontent.com/12015319/71245711-44fcde80-2350-11ea-96d4-4d05aff46691.png)
