### ISSUE TITLE
uniapp使用经验

### ISSUE THREAD

**Issue by 393197906** [dcloudio/uni-app#1118]
这是我迄今为止用过最SB的技术
做小程序还好
做app能坑哭你 
白屏
图片无法上传
基本没有兼容性
我真是服了  
不知道一群白痴在这干嘛
我要是再用我他妈就是个臭傻逼

**Comment by 393197906** [comment]
用户规模小还好
有一定用户规模 千万别用 坑哭你

**Comment by lincenying** [comment]
图片都传不了, 确定不是你自己的问题? 别人怎么都用的好好的?

**Comment by wakaryry** [comment]
程序员何必为难程序员。你这不仅骂了uni，还把用uni的人全给骂了一遍。甚至把weex还给骂了一遍。

**Comment by 393197906** [comment]
> 图片都传不了, 确定不是你自己的问题? 别人怎么都用的好好的?
拜托 你才测过几个机型啊   试试安卓大规模铺开坑不坑哭你再来说话  
难道我就那么欠想发牢骚吗
光一个白屏的问题官方休了几次了 现在还有 
不就是爱用用不用滚吗 
好 我滚 滚之前我觉得我可以来吐槽一下

**Comment by 393197906** [comment]
> 程序员何必为难程序员。你这不仅骂了uni，还把用uni的人全给骂了一遍。甚至把weex还给骂了一遍。

没有群嘲 你们要是觉得香 就当我在这放了一个屁

**Comment by wakaryry** [comment]
并不是香不香的问题。白屏我又不是没有遇到过。只不过我的白屏解决了。我以前还提过好几次白屏。要是我的白屏没有解决，我肯定也弃坑了。

当你觉得无法满足自己的需求或者影响到了自己的时候，选择放弃是应该的。
