### ISSUE TITLE
希望textarea能设置最大高度，在自动增高时超出最大高度可滚动

### ISSUE THREAD

**Issue by accp102** [dcloudio/uni-app#1119]
**新功能描述**
类似微信聊天输入框，高度可自动增高，当大于5行以上出现滚动条可滚动

**现状及问题**
目前设置固定高度编译APP，不能滚动，设置自增高页面又不好看

**尝试方案**
嵌套了一层scroll-view，但软件盘的换行不能自动滚动到底部，或一直输入文字每次换行超出一个字时也不会滚动到底部。
目前做法：监听输入框高度变化设置scroll-top，感觉不是很流畅

**Comment by zhetengbiji** [comment]
H5和App(V3)设置max-height即可，其他端效果如有问题可以同时监听linechange事件关闭auto-height

**Comment by accp102** [comment]
设置了max-height会有一个固定高度，期望效果是默认显示一行的高度，当输入高度超过3行就自动出现滚动条。目前是用 scroll-view + auto-height + 监听linechange  实现的

**Comment by zhetengbiji** [comment]
> 设置了max-height会有一个固定高度，期望效果是默认显示一行的高度，当输入高度超过3行就自动出现滚动条。目前是用 scroll-view + auto-height + 监听linechange 实现的

不需要scroll-view

**Comment by zhetengbiji** [comment]
此用户已在非nvue下使用类似效果 #1122

**Comment by accp102** [comment]
> 此用户已在非nvue下实验过类似效果 #1122
这链接是问题，并没有解决方案啊。我的问题和他查不多，加了max-height也没滚动效果，而且不能开始显示一行自动增高，然后出滚动条。回头我再试试

**Comment by accp102** [comment]
> 此用户已在非nvue下实验过类似效果 #1122

这链接是问题，并没有解决方案啊。我的问题和他查不多，加了max-height也没滚动效果，而且不能开始显示一行自动增高，然后出滚动条。回头我再试试

**Comment by zhetengbiji** [comment]
> > 此用户已在非nvue下实验过类似效果 #1122
> 
> 这链接是问题，并没有解决方案啊。我的问题和他查不多，加了max-height也没滚动效果，而且不能开始显示一行自动增高，然后出滚动条。回头我再试试

是问题，不过他反馈的nvue页面的问题，已先说明mp和小程序正常。

**Comment by zhetengbiji** [comment]
演示效果：
![未命名](https://user-images.githubusercontent.com/6326057/71176220-54265280-22a4-11ea-9736-30ab3725965e.gif)

**Comment by accp102** [comment]
> 演示效果GIF图：
> ![未命名](https://user-images.githubusercontent.com/6326057/71176220-54265280-22a4-11ea-9736-30ab3725965e.gif)

非常感谢，回头试试

**Comment by wakaryry** [comment]
小程序和h5是正常可以使用的。linechange就可以实现动态高度变化。

我那个是nvue页面，在app端linechange无法监听。所以一直在找app端的替代方案。后来ios上面出来了一个差不多的替代方案，但是安卓不正常。

**Comment by accp102** [comment]
> 小程序和h5是正常可以使用的。linechange就可以实现动态高度变化。
> 
> 我那个是nvue页面，在app端linechange无法监听。所以一直在找app端的替代方案。后来ios上面出来了一个差不多的替代方案，但是安卓不正常。

我的是APP而且是vue页面，只用max-height + auto-height，样式正常，但超出高度为啥上下滑不动

**Comment by wakaryry** [comment]
> > 小程序和h5是正常可以使用的。linechange就可以实现动态高度变化。
> > 我那个是nvue页面，在app端linechange无法监听。所以一直在找app端的替代方案。后来ios上面出来了一个差不多的替代方案，但是安卓不正常。
> 
> 我的是APP而且是vue页面，只用max-height + auto-height，样式正常，但超出高度为啥上下滑不动

auto-height 不支持 滚动。

nvue页面在mp/h5实现的，在vue页面照样实现，是一样的。

**Comment by accp102** [comment]
> > > 小程序和h5是正常可以使用的。linechange就可以实现动态高度变化。
> > > 我那个是nvue页面，在app端linechange无法监听。所以一直在找app端的替代方案。后来ios上面出来了一个差不多的替代方案，但是安卓不正常。
> > 
> > 
> > 我的是APP而且是vue页面，只用max-height + auto-height，样式正常，但超出高度为啥上下滑不动
> 
> auto-height 不支持 滚动。
> 
> nvue页面在mp/h5实现的，在vue页面照样实现，是一样的。

那怎么实现类似聊天的底部输入框，高度自动变化，当超过一定高度，就让他出滚动条，可上下滑动看之前输入的内容

**Comment by wakaryry** [comment]
不是说了用linachange莫。linechange监听到的时候，直接设置高度，而不是max-ehight。

这个在vue页面是可以的。不管那个端。

不过记得设置line-height，否则无法获取到当前有几行。

**Comment by accp102** [comment]
> 不是说了用linachange莫。linechange监听到的时候，直接设置高度，而不是max-ehight。
> 
> 这个在vue页面是可以的。不管那个端。
> 
> 不过记得设置line-height，否则无法获取到当前有几行。

嗯，明白了，感谢

**Comment by EVINK** [comment]
可用用纯css实现，只需要在input外包裹两层textarea

**Comment by anchao-lu** [comment]
> 不是说了用linachange莫。linechange监听到的时候，直接设置高度，而不是max-ehight。
> 
> 这个在vue页面是可以的。不管那个端。
> 
> 不过记得设置line-height，否则无法获取到当前有几行。

这种方案对于键盘输入是可以，但是有个问题，如果是直接拷贝粘贴大段文本，linechange 就不能及时更新，导致高度无限增加

<img width="370" alt="截屏2022-05-13 10 51 47" src="https://user-images.githubusercontent.com/54097292/168201950-e8a383f1-e052-4330-9580-352271b7f9f0.png">

**Comment by yanghao0825** [comment]
> > 不是说了用linachange莫。linechange监听到的时候，直接设置高度，而不是max-ehight。
> > 这个在vue页面是可以的。不管那个端。
> > 不过记得设置line-height，否则无法获取到当前有几行。
> 
> 这种方案对于键盘输入是可以，但是有个问题，如果是直接拷贝粘贴大段文本，linechange 就不能及时更新，导致高度无限增加
> 
> <img alt="截屏2022-05-13 10 51 47" width="370" src="https://user-images.githubusercontent.com/54097292/168201950-e8a383f1-e052-4330-9580-352271b7f9f0.png">
请问下这种情况有解决办法吗

**Comment by accp102** [comment]
不好意思，没处理过这类问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dcloudio/uni-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年2月13日(星期一) 下午2:51
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] 希望textarea能设置最大高度，在自动增高时超出最大高度可滚动 (#1119)





   
不是说了用linachange莫。linechange监听到的时候，直接设置高度，而不是max-ehight。
 这个在vue页面是可以的。不管那个端。
 不过记得设置line-height，否则无法获取到当前有几行。
  
这种方案对于键盘输入是可以，但是有个问题，如果是直接拷贝粘贴大段文本，linechange 就不能及时更新，导致高度无限增加
   
请问下这种情况有解决办法吗

**Comment by baby5** [comment]
> > > 不是说了用linachange莫。linechange监听到的时候，直接设置高度，而不是max-ehight。
> > > 这个在vue页面是可以的。不管那个端。
> > > 不过记得设置line-height，否则无法获取到当前有几行。
> > 
> > 
> > 这种方案对于键盘输入是可以，但是有个问题，如果是直接拷贝粘贴大段文本，linechange 就不能及时更新，导致高度无限增加
> > <img alt="截屏2022-05-13 10 51 47" width="370" src="https://user-images.githubusercontent.com/54097292/168201950-e8a383f1-e052-4330-9580-352271b7f9f0.png">
> 
> 请问下这种情况有解决办法吗

可以监控下输入的长度，手动触发linechange

**Comment by chocho-1115** [comment]
小程序原生代码是支持的
`

          <textarea class="input" placeholder="发消息" maxlength="-1" value="{{inputText}}" auto-height style="height: 48rpx"
            wx:if="{{ inputType == 'text' }}"
            confirm-type="send"
            show-confirm-bar="{{false}}"
            adjust-position="{{false}}"
            bindblur="textBlur"
            bindfocus="textFocus"
            bindconfirm="sendQuestion"
            bindinput="inputTextChange"
          ></textarea>

.input { // 高度85rpx
      display:block;
      border: none;
      min-height: 48rpx;
      max-height: 384rpx; // 最大8行
      line-height: 48rpx; // 1.6的行高
      padding: 22rpx 25rpx 0;
      font-size: 30rpx;
      height: auto;
      width: auto;
    }
`
