### ISSUE TITLE
cover-image 多个异常

### ISSUE THREAD

**Issue by fish-uncle** [dcloudio/uni-app#1124]
`<map>
<cover-image/>
<cover-image/>
</map>`
map下放了两个<cover-image/>
一个会跟着整个视图销毁
一个不会跟着整个视图销毁
![微信图片_20191214172039](https://user-images.githubusercontent.com/47963826/70846626-184f4f80-1e96-11ea-8fc0-d0a6a2841dbd.jpg)
![微信图片_20191214172044](https://user-images.githubusercontent.com/47963826/70846627-184f4f80-1e96-11ea-9728-1585becec2d0.jpg)

**Comment by zhetengbiji** [comment]
可以试试alpha版，[v3模式](https://ask.dcloud.net.cn/article/36599)对此有改进
