### ISSUE TITLE
uniapp H5 上传图片在ios10版本上传图片成功后不会执行success，巨大Bug！

### ISSUE THREAD

**Issue by freezyh** [dcloudio/uni-app#1129]
上传图片的伪代码：
`let res = await uni.uploadFile({
		url: url, 
		filePath: params.fileurl,
		fileType: 'image',
		name: 'file',
		header: header,
		formData: data
	});`
如上代码目前基本手机上传都没有问题，前后端也没有限制上传图片大小，
但在iphone7 ios10的系统中嵌入uniapp编译生成的H5，上传图片很大概率出现后端接口有正常数据返回，就是success不会执行或者await没有值，导致图片后端正常接收和返回了结果前端无法判断图片是否上传成功。
uniapp ios 上传bug！！！
如果有在线uniapp H5上传的链接，麻烦发下，谢谢！！！

**Comment by zhetengbiji** [comment]
关于反馈的这个多大概率，有没有进一步的规律发现？

**Comment by freezyh** [comment]
> 关于反馈的这个多大概率，有没有进一步的规律发现？

一般超过4M的图片概率可能会大些，有没有在线上传图片的链接，发下我这边真机测试下？

**Comment by zhetengbiji** [comment]
> > 关于反馈的这个多大概率，有没有进一步的规律发现？
> 
> 一般超过4M的图片概率可能会大些，有没有在线上传图片的链接，发下我这边真机测试下？

https://uniapp.dcloud.io/h5/pages/API/upload-file/upload-file

**Comment by freezyh** [comment]
> > > 关于反馈的这个多大概率，有没有进一步的规律发现？
> > 
> > 
> > 一般超过4M的图片概率可能会大些，有没有在线上传图片的链接，发下我这边真机测试下？
> 
> https://uniapp.dcloud.io/h5/pages/API/upload-file/upload-file

试了官方的案例链接，iphone7 ios10的环境，H5上传图片会先执行fail失败回调，后面什么都不执行，但后端接口后面返回了成功的数据，期待官方解决处理！！！！

**Comment by zhetengbiji** [comment]
> > > > 关于反馈的这个多大概率，有没有进一步的规律发现？
> > > 
> > > 
> > > 一般超过4M的图片概率可能会大些，有没有在线上传图片的链接，发下我这边真机测试下？
> > 
> > 
> > https://uniapp.dcloud.io/h5/pages/API/upload-file/upload-file
> 
> 试了官方的案例链接，iphone7 ios10的环境，H5上传图片会先执行fail失败回调，后面什么都不执行，但后端接口后面返回了成功的数据，期待官方解决处理！！！！

大文件吗？默认timeout是6秒，是不是超时了？你可以试试修改默认超时配置

**Comment by freezyh** [comment]
> > > > > 关于反馈的这个多大概率，有没有进一步的规律发现？
> > > > 
> > > > 
> > > > 一般超过4M的图片概率可能会大些，有没有在线上传图片的链接，发下我这边真机测试下？
> > > 
> > > 
> > > https://uniapp.dcloud.io/h5/pages/API/upload-file/upload-file
> > 
> > 
> > 试了官方的案例链接，iphone7 ios10的环境，H5上传图片会先执行fail失败回调，后面什么都不执行，但后端接口后面返回了成功的数据，期待官方解决处理！！！！
> 
> 大文件吗？默认timeout是6秒，是不是超时了？你可以试试修改默认超时配置

应该不是超时，设置了20s
"networkTimeout": {
        "request": 20000
    },

**Comment by zhetengbiji** [comment]
> > > > > > 关于反馈的这个多大概率，有没有进一步的规律发现？
> > > > > 
> > > > > 
> > > > > 一般超过4M的图片概率可能会大些，有没有在线上传图片的链接，发下我这边真机测试下？
> > > > 
> > > > 
> > > > https://uniapp.dcloud.io/h5/pages/API/upload-file/upload-file
> > > 
> > > 
> > > 试了官方的案例链接，iphone7 ios10的环境，H5上传图片会先执行fail失败回调，后面什么都不执行，但后端接口后面返回了成功的数据，期待官方解决处理！！！！
> > 
> > 
> > 大文件吗？默认timeout是6秒，是不是超时了？你可以试试修改默认超时配置
> 
> 应该不是超时，设置了20s
> "networkTimeout": {
> "request": 20000
> },

不是request是downloadFile

**Comment by freezyh** [comment]
> > > > > > > 关于反馈的这个多大概率，有没有进一步的规律发现？
> > > > > > 
> > > > > > 
> > > > > > 一般超过4M的图片概率可能会大些，有没有在线上传图片的链接，发下我这边真机测试下？
> > > > > 
> > > > > 
> > > > > https://uniapp.dcloud.io/h5/pages/API/upload-file/upload-file
> > > > 
> > > > 
> > > > 试了官方的案例链接，iphone7 ios10的环境，H5上传图片会先执行fail失败回调，后面什么都不执行，但后端接口后面返回了成功的数据，期待官方解决处理！！！！
> > > 
> > > 
> > > 大文件吗？默认timeout是6秒，是不是超时了？你可以试试修改默认超时配置
> > 
> > 
> > 应该不是超时，设置了20s
> > "networkTimeout": {
> > "request": 20000
> > },
> 
> 不是request是downloadFile

上传图片请求不都配置request，怎么配置了downloadFile？downloadFile是下载吧

**Comment by zhetengbiji** [comment]
> > > > > > > > 关于反馈的这个多大概率，有没有进一步的规律发现？
> > > > > > > 
> > > > > > > 
> > > > > > > 一般超过4M的图片概率可能会大些，有没有在线上传图片的链接，发下我这边真机测试下？
> > > > > > 
> > > > > > 
> > > > > > https://uniapp.dcloud.io/h5/pages/API/upload-file/upload-file
> > > > > 
> > > > > 
> > > > > 试了官方的案例链接，iphone7 ios10的环境，H5上传图片会先执行fail失败回调，后面什么都不执行，但后端接口后面返回了成功的数据，期待官方解决处理！！！！
> > > > 
> > > > 
> > > > 大文件吗？默认timeout是6秒，是不是超时了？你可以试试修改默认超时配置
> > > 
> > > 
> > > 应该不是超时，设置了20s
> > > "networkTimeout": {
> > > "request": 20000
> > > },
> > 
> > 
> > 不是request是downloadFile
> 
> 上传图片请求不都配置request，怎么配置了downloadFile？downloadFile是下载吧

是uploadFile

**Comment by freezyh** [comment]
原来配置uploadFile就行了。。。
