### ISSUE TITLE
请求header中cookie sessionid每次都会变化？

### ISSUE THREAD

**Issue by helxm** [dcloudio/uni-app#113]
小程序、h5都如此
设置cookie session不起作用，每次response header cookie中都会带有HttpOnly

**Comment by helxm** [comment]
手动设置request header 的set-cookie:JSESSIONID=6561B8A212C171CF667B30D4C6C17D23;path=/; 也不起作用

**Comment by helxm** [comment]
服务端接收的JSESSIONID就变了

**Comment by zhetengbiji** [comment]
框架未对cookie做任何操作，cookie由浏览器（或webview）管理。看一下百度搜索结果是否对你由帮助：[百度：cookie sessionid每次都会变化](https://www.baidu.com/s?wd=cookie+sessionid%E6%AF%8F%E6%AC%A1%E9%83%BD%E4%BC%9A%E5%8F%98%E5%8C%96&tn=84053098_3_dg&ie=utf-8)
