### ISSUE TITLE
版本2.0.0-24220191115006，yarn run dev:mp-weixin 使用import { uniSwipeAction,   uniSwipeActionItem } from "@dcloudio/uni-ui"模式引入组件，生成的index.wxs文件没有打包到对应的\dist\dev\mp-weixin\node-modules\@dcloudio\uni-ui\lib\uni-swipe-action-item路径下，而是在dist\dev\node-modules\@dcloudio\uni-ui\lib\uni-swipe-action-item路径下单独创建了；

### ISSUE THREAD

**Issue by Chale0524** [dcloudio/uni-app#1134]
版本2.0.0-24220191115006，yarn run dev:mp-weixin 使用import { uniSwipeAction,   uniSwipeActionItem } from "@dcloudio/uni-ui"模式引入组件，生成的index.wxs文件没有打包到对应的\dist\dev\mp-weixin\node-modules\@dcloudio\uni-ui\lib\uni-swipe-action-item路径下，而是在dist\dev\node-modules\@dcloudio\uni-ui\lib\uni-swipe-action-item路径下单独创建了；

**Comment by mehaotian** [comment]
测试环境 cli ：2.0.0-24220191115006
测试步骤： 使用yarn 安装依赖，yarn run dev:mp-weixin  运行到微信小程序平台

并没有出现你说的编译到错误目录下的情况

![image](https://user-images.githubusercontent.com/26707388/70970580-abc49280-20d9-11ea-8184-6480445fa27a.png)

看看是不是有什么地方操作错误，或者上传一个你的demo ，我用你的项目验证一下

**Comment by Chale0524** [comment]
> 测试环境cli：2.0.0-24220191115006
> 测试步骤：使用yarn安装依赖，yarn run dev：mp- weixin 运行到微信小程序平台
> 
> 并没有出现你说的编译到错误目录下的情况
> 
> ![图片](https://user-images.githubusercontent.com/26707388/70970580-abc49280-20d9-11ea-8184-6480445fa27a.png)
> 
> 看看是不是有什么地方操作错误，或者上传一个你的demo，我用你的项目验证一下

![微信截图_20191218142521](https://user-images.githubusercontent.com/43983622/71061163-6750f980-21a2-11ea-8b2a-357e933e5af8.png)

**Comment by mehaotian** [comment]
你的 uni-ui 是什么版本的 ？

**Comment by Chale0524** [comment]
通过vue-cli命令创建的工程，选的默认模板；
![微信截图_20191218163559](https://user-images.githubusercontent.com/43983622/71069939-b9027f80-21b4-11ea-8829-90ed7633de58.png)
