### ISSUE TITLE
底部TabBar能否支持图标或者网络文件

### ISSUE THREAD

**Issue by zhongku** [dcloudio/uni-app#1135]
**新功能描述**
1. 底部支持图标
2. 支持网络文件图片或者base64格式

**现状及问题**
小程序或app发布后，我们先动态修改底部tabbar的内容

**Comment by zhetengbiji** [comment]
结合uni.downloadFile与uni.setTabBarItem

**Comment by StrivingRabbit** [comment]
由于长时间没有回复，此issue关闭，如果还有问题可以重开或提新issue
