### ISSUE TITLE
控制台报错【QQ 小程序暂不支持 setNavigationBarColor】

### ISSUE THREAD

**Issue by qhbhq** [dcloudio/uni-app#1137]
**问题描述**

setNavigationBarColor 接口没有适配 QQ 小程序，导致控制台报错【QQ 小程序暂不支持 setNavigationBarColor】

**复现步骤**

uni.setNavigationBarColor 会报错，换成 qq.setNavigationBarColor 则正常

**预期结果**

uni.setNavigationBarColor 正常

**实际结果**

uni.setNavigationBarColor 报错

**系统信息**
 - 发行平台: QQ 小程序
 - uni-app v2.4.2
 - uni-app cli v2.0.0-24220191115006

**Comment by Wangyaqi** [comment]
感谢反馈，已修改
