### ISSUE TITLE
使用typescript定义类型声明，提示找不到vue/types/vue模块

### ISSUE THREAD

**Issue by huxuezhi** [dcloudio/uni-app#1138]
import Vue from 'vue';

declare module 'vue/types/vue' {
  interface Vue {
    $themes: PalettesProps;
  }
}

错误提示如下：
10:45:08.627   TS2664:Invalid module name in augmentation, module '@/node_modules/vue/types/vue' cannot be found.
10:45:08.629 [tsl] ERROR at pages\index\index.vue:23
10:45:08.629   TS2339:Property '$themes' does not exist on type 'CombinedVueInstance<Vue, {}, {}, {}, Readonly<Record<never, any>>>'.

**Comment by TechnicalGod** [comment]
我也遇到这个问题，求官方给个答案
