### ISSUE TITLE
Cannot find module 'vue-loader/lib/codegen/utils'

### ISSUE THREAD

**Issue by zhangchenna** [dcloudio/uni-app#1141]
不知道为什么 突然提示 Cannot find module 'vue-loader/lib/codegen/utils'

**Comment by zhetengbiji** [comment]
能否说明事情发生的经过

**Comment by zhangchenna** [comment]
> 能否说明事情发生的经过

不能 就是更新了 alpha 后  报错 切换回来依旧报错 ，查看了文件存在可以调用。。

**Comment by zhangchenna** [comment]
安装 "vue-loader":"15.8.3", 就正常了

**Comment by zhangchenna** [comment]
vue-loader@^15.7.2: 会报错

**Comment by zhetengbiji** [comment]
是更新了@vue/cli-service到4.x版本么

**Comment by zhangchenna** [comment]
是的

**Comment by zhangchenna** [comment]
> 是更新了@vue/cli-service到4.x版本么

是的

**Comment by zhangchenna** [comment]
模板默认出来就是4.1.0

**Comment by zhetengbiji** [comment]
> > 是更新了@vue/cli-service到4.x版本么
> 
> 是的

理论上更新@vue/cli-service会自动更新vue-loader

**Comment by zhangchenna** [comment]
模板默认出来就是4.1.0

> > > 是更新了@vue/cli-service到4.x版本么
> > 
> > 
> > 是的
> 
> 理论上更新@vue/cli-service会自动更新vue-loader


突然出现可能 跟安装依赖有关

**Comment by zhangchenna** [comment]
模板默认出来就是4.1.0

> > > 是更新了@vue/cli-service到4.x版本么
> > 
> > 
> > 是的
> 
> 理论上更新@vue/cli-service会自动更新vue-loader


突然出现可能 跟安装依赖有关

**Comment by zhangchenna** [comment]
确认了问题是 yarn 造成的 npm 就正常
