### ISSUE TITLE
编译到钉钉小程序调用showModal直接调用返回fail函数

### ISSUE THREAD

**Issue by qiaoqiao10001** [dcloudio/uni-app#1142]
**问题描述**
使用
编译到钉钉小程序调用showModal直接调用返回fail函数

**复现步骤**
1.  启动 '...'
2. 点击 显示模态框
3. 查看  当前界面

```javascript
uni.showModal({
					title:'确定删除当前关键人？',
					cancelText:'取消',
					confirmText:'确认',
					success:function(){
						deleteThePerson(id).then(res => {
							// 刷新列表
							getKeyPersonList({
								school_id: that.schoolId
							}).then(res => {
								that.personLists = res.data.data
							})
						})
					},
					fail:function(){
						uni.showToast({
							title:'已取消删除'
						})
					}
				})

```

**预期结果**
应该显示模态框, 调用结果

**实际结果**
实际返回了fail函数里面，提示已取消删除

**系统信息:**
 - 发行平台: 钉钉小程序-企业内部应用
 - 操作系统 Android9.0 MIUI 10
 - HBuilderX版本 2.4.2.20191115
 - uni-app版本 hbuilder 创建项目
 - 设备信息 小米mix2s

**补充信息**

**Comment by Wangyaqi** [comment]
钉钉小程序真机跟模拟器有差异，真机要求title、content均不为空，已补充文档说明。
