### ISSUE TITLE
vue-cli-plugin-uni 更新到 2.0.0-24220191115008 样式乱码

### ISSUE THREAD

**Issue by xiashui1994** [dcloudio/uni-app#1144]
**问题描述**
vue-cli-plugin-uni 更新到 2.0.0-24220191115008 样式乱码
**复现步骤**
[复现问题的步骤]
使用cli 脚手架更新包到最新版本，打包运行h5平台，样式错乱，出现如: height: %?200?%

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
样式正常编译 height: 200px;
**实际结果**
[这里请贴上你的报错截图或文字]

![image](https://user-images.githubusercontent.com/34127278/71054149-d8d17d80-218b-11ea-8e3c-b792a5998479.png)

*系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Sanmouren** [comment]
为什么@ vue / cli-service依赖安装为4.0以下版还有这个问题，是还有其他依赖么

**Comment by Sanmouren** [comment]
> 最新的cli-alpha已经修复此问题，如果不想使用alpha版本可以将@ vue / cli-service依赖安装为4.0以下版本

本身就是4.0以下还有这问题

**Comment by Wangyaqi** [comment]
我看下你的package.json

**Comment by Sanmouren** [comment]
在 2019-12-18 17:41:54，"王亚琪" <notifications@github.com> 写道：

我看下你的package.json

**Comment by Sanmouren** [comment]
> 我看下你的package.json

发给你了

**Comment by Wangyaqi** [comment]
你是不是直接发到邮件附件里面了，那个在github上面是看不到的

**Comment by Sanmouren** [comment]
{
"name": "uniappclient",
"version": "0.1.0",
"private": true,
"scripts": {
"clean": "rm -rf ./dist",
"serve": "npm run dev:h5",
"build": "npm run build:h5",
"build:app-plus": "cross-env NODE_ENV=production UNI_PLATFORM=app-plus vue-cli-service uni-build",
"build:h5": "cross-env NODE_ENV=production UNI_PLATFORM=h5 vue-cli-service uni-build",
"build:mp-alipay": "cross-env NODE_ENV=production UNI_PLATFORM=mp-alipay vue-cli-service uni-build",
"build:mp-baidu": "cross-env NODE_ENV=production UNI_PLATFORM=mp-baidu vue-cli-service uni-build",
"build:mp-qq": "cross-env NODE_ENV=production UNI_PLATFORM=mp-qq vue-cli-service uni-build",
"build:mp-toutiao": "cross-env NODE_ENV=production UNI_PLATFORM=mp-toutiao vue-cli-service uni-build",
"build:mp-weixin": "cross-env NODE_ENV=production UNI_PLATFORM=mp-weixin vue-cli-service uni-build",
"dev:app-plus": "cross-env NODE_ENV=development UNI_PLATFORM=app-plus vue-cli-service uni-build --watch",
"dev:h5": "cross-env NODE_ENV=development UNI_PLATFORM=h5 vue-cli-service uni-serve",
"dev:mp-alipay": "cross-env NODE_ENV=development UNI_PLATFORM=mp-alipay vue-cli-service uni-build --watch",
"dev:mp-baidu": "cross-env NODE_ENV=development UNI_PLATFORM=mp-baidu vue-cli-service uni-build --watch",
"dev:mp-qq": "cross-env NODE_ENV=development UNI_PLATFORM=mp-qq vue-cli-service uni-build --watch",
"dev:mp-toutiao": "cross-env NODE_ENV=development UNI_PLATFORM=mp-toutiao vue-cli-service uni-build --watch",
"dev:mp-weixin": "cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch",
"info": "node node_modules/@dcloudio/vue-cli-plugin-uni/commands/info.js"
},
"dependencies": {
"@dcloudio/uni-app-plus": "*",
"@dcloudio/uni-h5": "*",
"@dcloudio/uni-mp-alipay": "*",
"@dcloudio/uni-mp-baidu": "*",
"@dcloudio/uni-mp-qq": "*",
"@dcloudio/uni-mp-toutiao": "*",
"@dcloudio/uni-mp-weixin": "*",
"@dcloudio/uni-ui": "0.0.8",
"flyio": "^0.6.2",
"jweixin-module": "^1.4.1",
"less-loader": "^5.0.0",
"node-sass": "^4.12.0",
"qs": "^6.7.0",
"regenerator-runtime": "^0.12.1",
"sass-loader": "^7.1.0",
"vue": "^2.6.10",
"vuex": "^3.0.1"
},
"devDependencies": {
"@dcloudio/uni-cli-shared": "*",
"@dcloudio/uni-template-compiler": "*",
"@dcloudio/vue-cli-plugin-hbuilderx": "latest",
"@dcloudio/vue-cli-plugin-uni": "latest",
"@dcloudio/webpack-uni-mp-loader": "*",
"@dcloudio/webpack-uni-pages-loader": "*",
"@types/html5plus": "*",
"@types/uni-app": "*",
"@vue/cli-plugin-babel": "3.5.1",
"@vue/cli-service": "3.12.1",
"babel-plugin-import": "^1.11.0",
"less": "^3.9.0",
"postcss-comment": "^2.0.0",
"vue-template-compiler": "^2.6.10"
},
"browserslist": [
"last 3 versions",
"Android >= 4.4",
"ios >= 8"
],
"description": "## Project setup ``` yarn install ```",
"main": "babel.config.js",
"keywords": [],
"author": "xiaofuxu&daxinning",
"license": "ISC"
}



在 2019-12-18 17:50:59，"王亚琪" <notifications@github.com> 写道：

你是不是直接发到邮件附件里面了，那个在github上面是看不到的

**Comment by Sanmouren** [comment]
> 你是不是直接发到邮件附件里面了，那个在github上面是看不到的，邮箱也看不到，那是github的通知邮箱

发过来了

**Comment by Wangyaqi** [comment]
依赖版本你是手动修改成* 的吗？

**Comment by Rockergmail** [comment]
有同样的问题，解决了么？

**Comment by Rockergmail** [comment]
@Wangyaqi 麻烦检查一下最近你们的包的更新导致的问题。昨天还好好的。今天因为合并代码的原因，重新安装依赖了，就出现这个问题了。同样是h5打包的时候样式出现%? %?，导致样式错误

**Comment by Wangyaqi** [comment]
了解了，感谢反馈。可以先把@vue/cli-service改为4.0以上版本，稍后会对这个问题进行修复

**Comment by Sanmouren** [comment]
是4.0以上还是以下？



在 2019-12-18 19:38:13，"王亚琪" <notifications@github.com> 写道：

了解了，感谢反馈。可以先把@vue/cli-service改为4.0以上版本，稍后会对这个问题进行修复

**Comment by Wangyaqi** [comment]
这次是以上

**Comment by Sanmouren** [comment]
刚用了4.1.1也不行 麻烦尽快跟进一下这个问题吧



在 2019-12-18 19:42:06，"王亚琪" <notifications@github.com> 写道：

这次是以上

**Comment by Wangyaqi** [comment]
我测试是可以的，你可以新建一个cli项目看一下，对照一下依赖版本

**Comment by Sanmouren** [comment]
是4.0以上还是以下版本的



在 2019-12-18 19:59:14，"王亚琪" <notifications@github.com> 写道：

我测试是可以的，你可以新建一个cli项目看一下，对照一下依赖版本

**Comment by Wangyaqi** [comment]
![image](https://user-images.githubusercontent.com/12015319/71084908-418f1900-21d1-11ea-9165-603a5fdcfa95.png)

**Comment by Sanmouren** [comment]
发的图片加载不出来 你看一下



在 2019-12-18 20:02:07，"王亚琪" <notifications@github.com> 写道：

**Comment by Wangyaqi** [comment]
```
"devDependencies": {
    "@dcloudio/uni-cli-shared": "^2.0.0-24220191115008",
    "@dcloudio/uni-template-compiler": "^2.0.0-24220191115008",
    "@dcloudio/vue-cli-plugin-hbuilderx": "^2.0.0-24220191115008",
    "@dcloudio/vue-cli-plugin-uni": "^2.0.0-24220191115008",
    "@dcloudio/vue-cli-plugin-uni-optimize": "^2.0.0-24220191115008",
    "@dcloudio/webpack-uni-mp-loader": "^2.0.0-24220191115008",
    "@dcloudio/webpack-uni-pages-loader": "^2.0.0-24220191115008",
    "@types/html5plus": "*",
    "@types/uni-app": "*",
    "@vue/cli-plugin-babel": "3.5.1",
    "@vue/cli-service": "^4.1.0",
    "babel-plugin-import": "^1.11.0",
    "mini-types": "*",
    "miniprogram-api-typings": "^2.8.0-2",
    "postcss-comment": "^2.0.0",
    "vue-template-compiler": "^2.6.10"
},
```

**Comment by Sanmouren** [comment]
当前应用未配置Appid，无法使用uni统计，详情参考：https://ask.dcloud.net.cn/article/36303

/opt/common/dev-h5-uniapp/node_modules/@dcloudio/vue-cli-plugin-uni/lib/env.js:318
initAutoImportComponents(pagesJsonObj.easycom)
^

TypeError: initAutoImportComponents is not a function
    at Object.<anonymous> (/opt/common/dev-h5-uniapp/node_modules/@dcloudio/vue-cli-plugin-uni/lib/env.js:318:1)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/opt/common/dev-h5-uniapp/node_modules/@dcloudio/vue-cli-plugin-uni/index.js:6:5)
    at Module._compile (internal/modules/cjs/loader.js:778:30)

你们编译有遇到这个问题么

**Comment by Sanmouren** [comment]
当前应用未配置Appid，无法使用uni统计，详情参考：https://ask.dcloud.net.cn/article/36303

/opt/common/dev-h5-uniapp/node_modules/@dcloudio/vue-cli-plugin-uni/lib/env.js:318
initAutoImportComponents(pagesJsonObj.easycom)
^

TypeError: initAutoImportComponents is not a function
at Object.<anonymous> (/opt/common/dev-h5-uniapp/node_modules/@dcloudio/vue-cli-plugin-uni/lib/env.js:318:1)
at Module._compile (internal/modules/cjs/loader.js:778:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
at Function.Module._load (internal/modules/cjs/loader.js:585:3)
at Module.require (internal/modules/cjs/loader.js:692:17)
at require (internal/modules/cjs/helpers.js:25:18)
at Object.<anonymous> (/opt/common/dev-h5-uniapp/node_modules/@dcloudio/vue-cli-plugin-uni/index.js:6:5)
at Module._compile (internal/modules/cjs/loader.js:778:30)

有遇到这个问题么？



在 2019-12-26 16:27:22，"王亚琪" <notifications@github.com> 写道：

Closed #1144.
