### ISSUE TITLE
video组件direction不设置，默认没有根据视频宽高自动检测

### ISSUE THREAD

**Issue by phpjishu** [dcloudio/uni-app#1145]
**问题描述**

video组件direction不设置，APP_PLUS 默认没有根据视频宽高自动检测旋转方向，微信小程序是正确的

文档上的解释：direction  设置全屏时视频的方向，**不指定则根据宽高比自动判断**。有效值为 0（正常竖向）, 90（屏幕逆时针90度）, -90（屏幕顺时针90度）

我的这个例子小视频是一个抖音的视频，应该是竖屏显示

**复现步骤**
[复现问题的步骤]
1.  启动 '随便写个video启动，src=“https://move-1251497594.cos.ap-chengdu.myqcloud.com/6771803978592870059.MP4”'
2. 点击  '全屏按钮'
3. 查看

**预期结果**
在APP_PLUS里像微信小程序一样显示的效果，竖屏显示视频！

**实际结果**
横屏显示了视频

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 Android 8.0
 - HBuilderX版本 [2.4.6]
 - 设备信息 [华为、oppo]

**补充信息**
应该是对视频的宽高未作检测

**Comment by dcloudhdx** [comment]
vue 还是 nvue ？

**Comment by dcloudhdx** [comment]
已确认在 Android 上有问题

**Comment by dcloudhdx** [comment]
HBuilderX 2.6.8+ 已修复
