### ISSUE TITLE
webview获取app缓存中的内容

### ISSUE THREAD

**Issue by fish-uncle** [dcloudio/uni-app#1146]
webview中，h5页面与uni的app页面
怎么通信，app的缓存中的内容
`uni.getStorageSync('user')`

目前想到的是，app获取后放到h5的url参数中
http://example.com?user=user

只能这样吗？

**Comment by zhetengbiji** [comment]
http://www.html5plus.org/doc/zh_cn/storage.html

**Comment by fish-uncle** [comment]
这里的方法都是5+的方法，
很多h5并不支持

**Comment by zhetengbiji** [comment]
> 这里的方法都是5+的方法，
> 很多h5并不支持

5+的方法在非5+环境是100%不支持。h5的话，用localStorage（受跨域限制）。

**Comment by fish-uncle** [comment]
谢谢，
'plusrequire': 'none'
我之前设置了这个属性
