### ISSUE TITLE
hook:onPageScroll 没有返回 scrollTop

### ISSUE THREAD

**Issue by hminghe** [dcloudio/uni-app#1147]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
在page面使用 this.$on('hook:onPageScroll') 没有返回event

[或者可以直接贴源代码]

this.$on('hook:onPageScroll', (event) => {
  console.log(event); // => null
})

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
this.$on('hook:onPageScroll', (event) => {
  console.log(event); // => {scrollTop: 100}
})
**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
- 只测试了H5

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
是事件无法触发，还是事件触发后获取不到事件对象？

**Comment by hminghe** [comment]
> 是事件无法触发，还是事件触发后获取不到事件对象？

事件可以触发，是触发后获取不了事件对象

**Comment by Wangyaqi** [comment]
此问题已修复，可以更新验证一下
