### ISSUE TITLE
scroll的pagingEnabled的可以设置paging的width/height吗？

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#1148]
nvue-app端，scroll的pagingEnabled的可以设置每一次paging的宽度或者高度吗？

现在是不想每一次都滑动 整个 scroll 的 宽度或者高度，想每一次 滚动 固定的 距离，这样就非常好实现 各种各样的 banner 了。

就是想知道有没有这个设置。

**Comment by Wangyaqi** [comment]
你是说nvue的list组件吗？list不能设置page的宽高

**Comment by wakaryry** [comment]
嗯嗯。哎。那算了。

谢谢
