### ISSUE TITLE
扫码回调后无法设置焦点属性

### ISSUE THREAD

**Issue by cmkcmk181** [dcloudio/uni-app#115]
使用扫码回调后，无法设置焦点，通过按钮是可以的。
环境：微信模拟器及安卓APP9.0
HbuilderX:1.3.2.20181214
<template>
  <view>
       <input  :focus="bFocus" />
      <button class="bottom-btn" @tap="doFocus" hover-class="button-hover">设置焦点</button>
 </view>
</template>
<script>
  export default {
		data() {
			return {
                             bFocus:false
                        }
                }
                methods: {	
			doFocus:function(){
				let me=this;
                                //me.bFocus=true ;//这里可以正常修改焦点
                                uni.scanCode({
                                      success: function(res) {
                                           me.bFocus=true;//这里修改焦点没反应
                                      }
                                });			
			}
              }
 }
</script>

**Comment by xiaoyucoding** [comment]
可否提供完整一些的代码，从目前提供的代码里面没有看到 `bFocus` 作用于何处。
