### ISSUE TITLE
自定义配置webpack

### ISSUE THREAD

**Issue by LeiSe7en** [dcloudio/uni-app#1150]
**新功能描述**
是否有地方可以自己设置`webpack`的配置？如果已经支持，烦请告知。

**现状及问题**
想要配置一些`plugin`或者`alias`

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by zhetengbiji** [comment]
https://uniapp.dcloud.io/collocation/vue-config

**Comment by LeiSe7en** [comment]
> https://uniapp.dcloud.io/collocation/vue-config
Thanks
