### ISSUE TITLE
引入自定义组件时报错

### ISSUE THREAD

**Issue by littleBelle** [dcloudio/uni-app#1152]
![image](https://user-images.githubusercontent.com/53242999/71237570-dbbfa000-233c-11ea-89a8-b189c80640e5.png)
第一次使用uniapp，烦请指教，谢谢谢谢

**Comment by Wangyaqi** [comment]
150行 去掉花括号

**Comment by littleBelle** [comment]
> 150行 去掉花括号

多谢，我搞混了，
