### ISSUE TITLE
钉钉中打开h5页面，导航栏标题显示异常

### ISSUE THREAD

**Issue by xiashui1994** [dcloudio/uni-app#1153]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
钉钉中打开h5页面，导航栏标题显示异常
**复现步骤**
[复现问题的步骤]
1.  启动钉钉
2. 扫描官方示例h5版二维码
3. 切换底部tab或者点击进入任意页面，导航栏标题没有变化，或显示异常

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
导航栏标题正常显示
**实际结果**
[这里请贴上你的报错截图或文字]
导航栏标题显示异常

![image](https://user-images.githubusercontent.com/34127278/71251506-8051da00-235d-11ea-898d-853c9421a97a.png)

![image](https://user-images.githubusercontent.com/34127278/71251532-9495d700-235d-11ea-9077-9302c8ac381f.png)
**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
钉钉
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
安卓、ios
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Wangyaqi** [comment]
钉钉小程序不支持动态修改title

**Comment by xiaofuliang** [comment]
@xiashui1994 请问找到解决办法了吗
