### ISSUE TITLE
uni-storage-keys 这个键怎么取消掉

### ISSUE THREAD

**Issue by vkcyan** [dcloudio/uni-app#1155]
**问题描述**
在安卓APP的webview里面打开uniapp的h5页面,会出现这样的报错
`chromium: [INFO:CONSOLE(1)] "Uncaught TypeError: Cannot read property 'getItem' of null"`
查看打包后的代码,猜测是因为webview的限制导致,导致在页面没加载出来之前会出现执行
`localStorage.getItem("uni-storage-keys")` 这样的代码导致的报错,但是这个代码并不知道如何取消

**系统信息:**
 - 发行平台: H5平台
 - uni-app版本
    uni-app v2.4.2
    uni-app cli v2.0.0-24220191115011
 - 设备信息 android

希望可以在webview里面正常使用

**Comment by zhetengbiji** [comment]
你的webview未启用localStorage导致，如果不启用会导致storage相关接口报错无法使用，相关文章[安卓webview使用localStorage](https://www.baidu.com/s?wd=%E5%AE%89%E5%8D%93webview%E4%BD%BF%E7%94%A8localStorage&tn=84053098_3_dg&ie=utf-8)

**Comment by zhetengbiji** [comment]
针对storage接口的报错信息，后续将优化一下，使其看起来更直观。

**Comment by vkcyan** [comment]
我们知道这样的解决,但是webview是第三方合作商的app提供的,我方不方便让他们在做出协调,麻烦您考虑一下,我们项目之前版本使用taro开发的,可以正常使用的,但是我们团队觉得uniapp的h5表现形式更好,也完成了项目的移植,所以希望您考虑一下,我们对uniapp非常支持,但是这个问题不解决,我们可能无法使用uniapp了,希望官方协调一下

**Comment by Wangyaqi** [comment]
关闭uni统计试试，[https://ask.dcloud.net.cn/article/36303](https://ask.dcloud.net.cn/article/36303)

**Comment by vkcyan** [comment]
嗯嗯,谢谢我再看看怎么解决这个吧
