### ISSUE TITLE
recycle-list  WARNING: "export 'recyclableRender' was not found

### ISSUE THREAD

**Issue by Vitaminaq** [dcloudio/uni-app#1156]
我在.nvue文件recycle-list的cell-slot里使用了自定义组件
```bash
<recycle-list for="item in list" @loadmore="loadmore" switch="type">
  <cell-slot class="list-item"  case="item">
     <component :is="itemSolt" :item="item"></component>
  </cell-slot>
</recyle-list>
```
按文档上说的给自定义的子组件加上了
```bash
<template recyclable><template>
```
就出现了如下错误：
WARNING: "export 'recyclableRender' was not found in './forum-item.nvue?vue&type=template&id=5b28e695&recyclable=true&'

请问recycle-list里面支持使用自定义组件吗？

**Comment by zhetengbiji** [comment]
https://weex.apache.org/zh/docs/components/recycle-list.html
