### ISSUE TITLE
背景样式混乱了, 背景都跑到 body.pages-XXXX上去了 

### ISSUE THREAD

**Issue by trojanliu** [dcloudio/uni-app#1157]
**问题描述**
H5上出现背景错误

**复现步骤**

`<style lang="less">
page {
	background-color: @primary-background-color;
	.model{
		background-color: yellow;
		.modelCoupon {
			background-color: #038FF9;
			.imgCoupon {
				background-image: url(../../static/img/coupon/coupon.png);
			}
                }
        }
}
</style>`

从下图可以看到, 背景相关的都重叠到body.pages-XXXX上去了
`.page-xxxxx {
	background-color: @primary-background-color;
	background-color: yellow;
	background-color: #038FF9;
	background-image: url(../../static/img/coupon/coupon.png);
}`

<img width="722" alt="bug" src="https://user-images.githubusercontent.com/8016811/71304327-0e7e9c80-2400-11ea-82c7-32a662e98ed2.png">

**Comment by Wangyaqi** [comment]
此问题已修复，可以更新后验证
