### ISSUE TITLE
video 组件没有支持 loadedmetadata 事件

### ISSUE THREAD

**Issue by ColinLQ** [dcloudio/uni-app#1158]

**Comment by Wangyaqi** [comment]
运行到哪端？什么版本的HBuilderX或者cli

**Comment by ColinLQ** [comment]
@Wangyaqi 微信小程序，cli 版本 `2.0.0-23220190921001`

**Comment by ColinLQ** [comment]
看你们官方文档上面，好像也没有写有这个事件

**Comment by zhetengbiji** [comment]
微信小程序直接使用@loadedmetadata即可，小程序开发工具可能不支持该事件，请以真机为准
文档稍后补充

**Comment by pitilesszgw** [comment]
> 运行到哪端？什么版本的HBuilderX或者cli

HBuilderX 3.9.9
app端什么时候可以支持loadedmetadata、后续有这个计划嘛
