### ISSUE TITLE
uni-app能不能使用原生的SDK（jar形式）

### ISSUE THREAD

**Issue by jahnli** [dcloudio/uni-app#116]
我看文档说项目中可以使用5+sdk  但是并没有说怎么具体把5+sdk集成到uni-app项目中去，求解答或者Demo、

**Comment by zhetengbiji** [comment]
集成方式和普通5+项目一样：[Android平台5+插件开发](http://ask.dcloud.net.cn/docs/#//ask.dcloud.net.cn/article/66)
[uniapp离线打包日记（安卓）](https://www.jianshu.com/p/a44b1e6fe27e)
