### ISSUE TITLE
如何选择文件上传？需要编译到钉钉小程序的

### ISSUE THREAD

**Issue by qiaoqiao10001** [dcloudio/uni-app#1160]
**新功能描述**
希望能有类似chooseImage的api

**现状及问题**
只能通过chooseImage选择图片文件，如果其他文件就不能选择了，只能通过webview来使用inputFile来达到功能

**尝试方案**
只能自己写webview来实现文件上传

**补充信息**
暂时没有

**Comment by zhetengbiji** [comment]
目前钉钉小程序未支持，你可以可以到钉钉平台去反馈一下此需求
