### ISSUE TITLE
只能选择图片或者视频文件上传；其他文件无法上传

### ISSUE THREAD

**Issue by qiaoqiao10001** [dcloudio/uni-app#1161]
**问题描述**
chooseImage接口只能选择图片或者视频来上传

**复现步骤**
点击选择文件
打开系统图库
不能打开文件管理器

[或者可以直接贴源代码]

**预期结果**
预期打开文件选择

**实际结果**
只打开图片，拍照或者传递相册

**Comment by zhetengbiji** [comment]
chooseImage 设计上就是用来上传图片类，其他的可以参考一下此文章：[uni-app 选择和上传非图像、视频文件](https://ask.dcloud.net.cn/article/35547)
