### ISSUE TITLE
关于uniapp typescript eslint 问题

### ISSUE THREAD

**Issue by bigGoodMan** [dcloudio/uni-app#1163]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
会出现一个无法解决的
`Parsing error: '>' expected.`
![image](https://user-images.githubusercontent.com/21271880/71340000-41579a80-2590-11ea-9223-a8dd6365a552.png)

**复现步骤**
[复现问题的步骤]
1.  安装 `vue create -p dcloudio/uni-preset-vue my-project`
2. 点击 typescript
3. 配置eslint
`module.exports = {
  // "extends": "eslint:recommended",
  // parser: 'babel-eslint',
  // "env": {
  //   "amd": true,
  //   "es6": true,
  //   "browser": true,
  //   "node": false
  // },
  // "extends": "plugin:vue/base",
  root: true,
  env: {
    node: true,
  },
  // extends: [
  //   // add more generic rulesets here, such as:
  //   // 'eslint:recommended',
  //   'plugin:vue/recommended'
  // ],
  parserOptions: {
    // "parser": "babel-eslint",
    parser: '@typescript-eslint/parser', //['@typescript-eslint/parser', 'vue-eslint-parser'],
    "ecmaVersion": 2018, //ES2018解析
    "sourceType": "module",
    "ecmaFeatures": {
      "modules": true
    },
    "project": "./tsconfig.json"
  },
  plugins: ['@typescript-eslint'],
  rules: {
    // 禁止使用 var
    'no-var': "error",
    // 优先使用 interface 而不是 type
    '@typescript-eslint/consistent-type-definitions': [
      "error",
      "interface"
    ]
  }
}`

[或者可以直接贴源代码]

**预期结果**
实际应该vue文件中的template里面的标签不会报该问题

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/21271880/71340105-add29980-2590-11ea-8701-dc8c7797fe60.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Silence-dream** [comment]
可以用过vue add eslint 自动配置

**Comment by 2321605193** [comment]
安装vue-eslint-parser即可解决

![image](https://github.com/dcloudio/uni-app/assets/39330227/eb5d4e59-cb3e-4772-a584-44aebaafe422)
