### ISSUE TITLE
给自定义组件设置 id 会报警告

### ISSUE THREAD

**Issue by jin-yufeng** [dcloudio/uni-app#1167]
**问题描述**
使用一个自定义组件时，如果设置一个动态的 `id`，编译时会报警告 “提示：id 作为属性保留名,不允许在自定义组件 xxx 中定义为 props”，实际上自定义组件内没有定义 `id`
```html
<demo :id="test" />
```
`demo.vue` 是一个空文件，没有定义任何属性

**复现步骤**
1. 打开 [demo](https://github.com/dcloudio/uni-app/files/3994536/test.zip) 项目
2. 编译到小程序平台

**预期结果**
没有警告

**实际结果**
![1](https://user-images.githubusercontent.com/48236054/71352314-f39f5a00-25b0-11ea-8522-c96475207242.png)

**系统信息:**
 - 发行平台：小程序
 - HBuilderX版本：2.4.6

**Comment by Wangyaqi** [comment]
你再读读这句话

**Comment by jin-yufeng** [comment]
这句话说 `id` 不允许在自定义组件中定义为 `props`，但是 `demo` 组件根本就没有定义任何 `props`，这是给这个标签设置 `id` 就会出现这个警告
