### ISSUE TITLE
有没有兼容小程序setData的方法，处理列表数据局部更新，避免全部数据更新、渲染引起的卡顿问题???

### ISSUE THREAD

**Issue by yimihua001** [dcloudio/uni-app#117]
使用该框架开发小程序，下拉加载数据，data数据越来越大，基本到达200多条，页面渲染就瘫痪，崩溃。

**Comment by jiuwuxiaohun** [comment]
对,我们这边也遇到了同样的问题,,哥们,有没有解决途径啊说说啊..还是只能等官方更新啊

**Comment by jiuwuxiaohun** [comment]
今天晚上我们测试了下这个问题,感觉是因为大列表的时候,列表渲染的东西太多导致的,比如你直接渲染一个简单的图片,可以渲染每页20个图片,渲染30页每页问题,,,但是如果每页都是复杂的组件组成的,,则渲染开始很快,随着列表的加大,越来越卡,我们正在优化我们的组件代码,,尽量的精简dom结构,,还在弄.

**Comment by xiaoyucoding** [comment]
微信小程序端做了大幅优化，详见：[uni-app 1.8发布，微信端性能翻倍，并增加若干 Vue 语法支持](https://ask.dcloud.net.cn/article/35699)
