### ISSUE TITLE
uni.previewImage预览图片h5版在微信中无法放大缩小

### ISSUE THREAD

**Issue by xiashui1994** [dcloudio/uni-app#1170]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
uni.previewImage预览图片h5版在微信中无法放大缩小
**复现步骤**
[复现问题的步骤]
1.  用微信扫码h5版官方示例
2. 接口-媒体-图片 上传图片后预览
3. 在预览中放大缩小

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
预览中能够放大缩小
**实际结果**
[这里请贴上你的报错截图或文字]
在预览中不能放大缩小

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
未实现此功能？

**Comment by Wangyaqi** [comment]
目前没有支持放大缩小功能
