### ISSUE TITLE
打包为app后长按事件会触发点击事件

### ISSUE THREAD

**Issue by zhouxiaofu** [dcloudio/uni-app#1171]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
打包为app @longtap事件触发@click事件

**Comment by zhouxiaofu** [comment]
控制台提示可以使用 longpress 替换 longtap，问题解决了，但是官方文档为什么没有说明？https://uniapp.dcloud.io/use?id=%E4%BA%8B%E4%BB%B6%E5%A4%84%E7%90%86%E5%99%A8

**Comment by Wangyaqi** [comment]
已修改文档，感谢反馈
