### ISSUE TITLE
QQ 开发者工具重复启动

### ISSUE THREAD

**Issue by qhbhq** [dcloudio/uni-app#1172]
**问题描述**

在 HBuilder X 2.4.6 运行 QQ 小程序项目时，如果当前已启动 QQ 开发者工具，发现会重复启动一个新的 QQ 开发者工具，并且应用程序显示无响应，也强退不了，macOS 10.15.2

**预期结果**

不应该重复启动 QQ 开发者工具

**实际结果**

![截屏2019-12-25上午12 14 15](https://user-images.githubusercontent.com/17266004/71419660-84f2f700-26ab-11ea-8841-38963f63b95e.png)

**Comment by wandali2019** [comment]
关于应用程序没有响应的问题，这是qq小程序开发工具自身的bug，请反馈给他们官方
