### ISSUE TITLE
文档有误

### ISSUE THREAD

**Issue by Lyn4ever29** [dcloudio/uni-app#1174]
![image](https://user-images.githubusercontent.com/25952589/71435583-93c9c000-2724-11ea-8ff1-045e96458cf3.png)

https://uniapp.dcloud.io/api/ui/navigationbar?id=hidehomebutton

**Comment by Wangyaqi** [comment]
已修改，感谢反馈，也欢迎点击文档底部的 在 GitHub 上编辑此页面！向我们提交PR
