### ISSUE TITLE
使用 v-slot插槽时，修改不是当前使用的页面 内容后项目编译后会显示空白，每次需要停止微信开发工具或者编辑修改一下当前的页面才会显示出来

### ISSUE THREAD

**Issue by xiaofuliang** [dcloudio/uni-app#1177]
**问题描述**
在一个列表页面使用了一个插槽，子组件是List.vue，当不是修改列表页面代码时，项目自动重新编译后会变成空白
![11](https://user-images.githubusercontent.com/23289722/71442311-596e1c00-2740-11ea-9b62-558cb763ed43.png)
![2](https://user-images.githubusercontent.com/23289722/71442389-9803d680-2740-11ea-8b8b-1f6a0be5e769.png)

**复现步骤**
demo地址：
https://github.com/xiaofuliang/uniapp-demo

**预期结果**
修改其他地方的代码，列表页面v-slot使用是正常显示

**实际结果**
修改其他地方的代码，列表页面v-slot使用是没有了

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 2.4.9.20191223-alpha
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**Comment by zhetengbiji** [comment]
后续已修复
