### ISSUE TITLE
可以在微信小程序端支持自定义组件的 `class` `style` 的绑定吗？

### ISSUE THREAD

**Issue by Riant** [dcloudio/uni-app#1180]
**新功能描述**
希望能够在自定义组件上也支持 `class` `style` 的绑定

**现状及问题**
> 非H5端暂不支持在自定义组件上使用 `Class` 与 `Style` 绑定

微信小程序的自定义组件本身是支持的，可以覆盖一下微信小程序吗？

谢谢。

**Comment by guohuihot** [comment]
原来不是我一个人遇到这问题

**Comment by zhetengbiji** [comment]
详情请参考最新文档：https://uniapp.dcloud.net.cn/tutorial/vue-basics.html#class-%E4%B8%8E-style-%E7%BB%91%E5%AE%9A

**Comment by guohuihot** [comment]
这个问题不在于合并style, 与vue组件的区别是uniapp自定义组件会多包一层
```js
//com-button.vue
<button/>
// 调用
<com-button style="width: 10px"/>
```
期望
```js
<button style="width: 10px"/>
```
但得到的是
```js
<com-button style="width: 10px">
      <button/>
</com-button>
```

**Comment by zhetengbiji** [comment]
> 这个问题不在于合并style, 与vue组件的区别是uniapp自定义组件会多包一层
> 
> ```js
> //com-button.vue
> <button/>
> // 调用
> <com-button style="width: 10px"/>
> ```
> 
> 期望
> 
> ```js
> <button style="width: 10px"/>
> ```
> 
> 但得到的是
> 
> ```js
> <com-button style="width: 10px">
>       <button/>
> </com-button>
> ```

处理方案：

* 组件使用虚拟节点
* 全局配置 mergeVirtualHostAttributes

相关更新：

> 3.5.3
>
> 微信小程序、支付宝小程序 新增 manifest.json 支持 mergeVirtualHostAttributes 配置，用于合并虚拟节点外部样式 [详情](https://uniapp.dcloud.net.cn/collocation/manifest.html#mp-weixin)

**Comment by zhetengbiji** [comment]
使用 mergeVirtualHostAttributes 后，在微信小程序、支付宝小程序平台组件表现更加接近于 Web 平台。

随着开发者使用和提议的人数增加，其他小程序平台也会考虑跟进微信小程序的 virtualHost 配置。

**Comment by guohuihot** [comment]
多谢反馈
