### ISSUE TITLE
App平台 @click 绑定事件 无法传入 v-for="n in 3" 的循环变量 n，H5平台可以

### ISSUE THREAD

**Issue by Yangson-Hung** [dcloudio/uni-app#1181]
**问题描述**
App平台 @click 绑定事件 无法传入 v-for="n in 3" 的循环变量 n，H5平台可以

```vue
<view class="content">
	<block v-for="n in 3" :key="n">
		<view @click="fun(n)">
			{{n}}
		</view>
	</block>
</view>
```
```vue
methods: {
	fun: function(n) {
		console.log(n)
	}
}	
```

**错误信息**
![image](https://user-images.githubusercontent.com/32238889/71455908-0e9ce480-27d2-11ea-9e0a-34e9e5919164.png)

**系统信息:**
 - 发行平台:：5+ App
 - 操作系统：Android 8.0
 - HBuilderX版本：2.4.6.20191210

**Comment by zhangyq233** [comment]
将数字3 换成变量。 就不会报错

**Comment by Yangson-Hung** [comment]
可以了，谢谢老哥
