### ISSUE TITLE
编译出来的图片、css文件名都没有带hash，对cdn极其不友好

### ISSUE THREAD

**Issue by jasperchou** [dcloudio/uni-app#1183]
**问题描述**
编译出来的图片、css文件名都没有带hash，对cdn极其不友好

**复现步骤**
[复现问题的步骤]
打包h5平台可以看到

**预期结果**
如同vue默认编译打包的文件一样
```
.
├── css
│   ├── about.b1fea8d8.css
│   └── app.27e4a8b9.css
├── favicon.ico
├── img
│   ├── btn_android@2x.b8ff7715.png
│   ├── btn_ios@2x.68fbbb2a.png
│   ├── head.0887223a.png
│   ├── logo@2x.e30dcfbd.png
│   └── pic@2x.115118db.png
├── index.html
├── js
│   ├── about.d7d45ec5.js
```

**实际结果**
```
├── index.html
└── static
    ├── images
    │   ├── c
    │   │   ├── check-box
    │   │   │   ├── icon-checked.png
    │   │   │   └── icon-circle.png
    ├── index.css
    ├── js
    │   ├── chunk-vendors.f7ec7a1a.js
    │   ├── index.d0d34e90.js
    │   ├── pages-activate-card-activate-card.9d1a761e.js
```

**Comment by zhetengbiji** [comment]
最新alpha版，css文件文件名已包含hash，对于其他静态文件由于是运行时动态拼接路径，暂时无法修改文件名。

**Comment by jasperchou** [comment]
请问需要更改什么配置吗？我下载最新Alpha工具直接发行还是没有hash

**Comment by zhetengbiji** [comment]
> 请问需要更改什么配置吗？我下载最新Alpha工具直接发行还是没有hash

如果你是cli工程需要更新相关uni依赖，如果自己定义了html模板，需要将原来的index.css 改为 index.<%= VUE_APP_INDEX_CSS_HASH %>.css

**Comment by jasperchou** [comment]
非常感谢。亲测确实css可以带上hash值了。

只剩下image的hash问题，还有image好像也不受publicPath作用？
目前只能是拿生成文件去替换路径。
期望有更好的办法。

**Comment by jamieYou** [comment]
@zhetengbiji  图片现在有解决方法吗？因为反向代理设了缓存，更新图片后，网页看到的图片还是旧的。

**Comment by fxy060608** [comment]
下个alpha版本，h5平台，template，style中引用的相对路径图片，均会编译为带hash模式

**Comment by jasperchou** [comment]
> 下个alpha版本，h5平台，template，style中引用的相对路径图片，均会编译为带hash模式

主要是html上的图片。
