### ISSUE TITLE
在Angular的页面中用postMessage， 失效

### ISSUE THREAD

**Issue by cieldon32** [dcloudio/uni-app#1184]
我的页面是
`
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <title>ProfileUiV2</title>
    <base href="/" />

    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="icon" type="image/x-icon" href="favicon.ico" />
    <script
      src="assets/jweixin.js"
      charset="utf-8"
    ></script>
    <script
      src="assets/uni.webview.1.5.2.js"
      charset="utf-8"
    ></script>
    
    <script
      src="assets/webcomponentsjs/custom-elements-es5-adapter.js"
      charset="utf-8"
    ></script>
    <script
      src="assets/webcomponentsjs/webcomponents-lite.js"
      charset="utf-8"
    ></script>
    
    <link
      rel="import"
      href="assets/webcomponents/es5/src/web_components.html"
    />
  </head>
  <body style="margin: 0">
    <app-root></app-root>
    
  <script src="runtime.js"></script><script src="polyfills.js"></script><script src="styles.js"></script><script src="vendor.js"></script><script src="main.js"></script></body>
</html>

`

**实际结果**
在uni-app中新建API的示例项目， 把url换成本地angular页面地址， 在点击back的时候， 没有触发message的事件。 望帮助。

**Comment by Wangyaqi** [comment]
只看这些看不出来啥，有没有精简之后的项目

**Comment by dcloudhdx** [comment]
参考 hello uni-app 示例代码 https://github.com/dcloudio/hello-uniapp/tree/master/pages/component/web-view

**Comment by dcloudhdx** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
