### ISSUE TITLE
uniapp写小程序时给view动态添加类名不生效

### ISSUE THREAD

**Issue by littleBelle** [dcloudio/uni-app#1186]
uniapp写小程序时给view动态添加类名不生效
![image](https://user-images.githubusercontent.com/53242999/71470773-37d86780-2808-11ea-91e0-7a59ba6a2400.png)
![image](https://user-images.githubusercontent.com/53242999/71470854-86860180-2808-11ea-9cd6-615204fcd3c2.png)

目的是想根据thirdCategoryList的长度判断，如果长度大于0，则给他添加一个类名，样式为margin-top：84rpx，但是，thirdCategoryList的长度确实大于0，类名却加不上
找了很久，不知道是哪里写错了，请求帮助，多谢谢谢了

**Comment by Wangyaqi** [comment]
微信小程序模板上length有点问题可以用computed计算好之后再放到模版使用，https://developers.weixin.qq.com/community/develop/article/doc/0000ec6fe2c960e426a9fcf4151c13

**Comment by littleBelle** [comment]
> 微信小程序模板上length有点问题可以用computed计算好之后再放到模版使用，https://developers.weixin.qq.com/community/develop/article/doc/0000ec6fe2c960e426a9fcf4151c13

![image](https://user-images.githubusercontent.com/53242999/71471955-1ed1b580-280c-11ea-8d1a-d7aa337e1bfe.png)
但是这边v-if是有效果的，这是什么原因呢

**Comment by Wangyaqi** [comment]
v-if会重新渲染

**Comment by littleBelle** [comment]
> v-if会重新渲染

多谢指点，谢谢谢谢
