### ISSUE TITLE
waterfall组件高度问题

### ISSUE THREAD

**Issue by zjzmyh** [dcloudio/uni-app#1188]
**问题描述**
nvue组件多列的时候，页面高度是单列的高度，导致页面下很大空白

**复现步骤**
`<template>
    <view class="cm-main">
		<waterfall column-count="2" column-gap="20" left-gap="20" right-gap="20">
		    <cell v-for="item in photoList">
			  <view :style="{width:'315rpx',height:item.height}" style="margin-bottom: 40rpx;background-color: red;">
				  <text>asdasda</text>
			  </view>
		    </cell>
		  </waterfall>
    </view>
</template>`
**预期结果**
实际应该是没有大面积空白

**实际结果**
![image](https://user-images.githubusercontent.com/33221131/71481222-e2b44a00-2837-11ea-872f-9e462d6cc2e6.png)

**系统信息:**
 - 发行平台: uni-app
 - 操作系统 :ios11.2 
 - HBuilderX版本: 2.4.6
 - 设备信息 :iphone5s模拟器

**Comment by JM5788** [comment]
这个问题官方一直没有给解决，我就无语了
