### ISSUE TITLE
【bug】在 iPhone 8 中样式变大了

### ISSUE THREAD

**Issue by CaptainLiao** [dcloudio/uni-app#1189]
**问题描述**
 iPhone 8 ，微信浏览器，样式异常，刷新页面后正常，其他手机正常。

异常情况如下：
<img width="268" alt="微信截图_20191227101949" src="https://user-images.githubusercontent.com/17636663/71497310-9c400900-2892-11ea-9a45-adbc2b227393.png">

**源码**
````
.a-text-16 {
  font-size: 32rpx;
}
````

**Comment by zhetengbiji** [comment]
rpx的实际大小是根据页面宽度计算得到的，应该是微信浏览器的bug某些情况获取宽度值不正确。后续rpx的计算方式会进行改善，可以先改用rem或者vw。另外字体大小不推荐使用rpx，横屏或大屏适配很差。

**Comment by zhetengbiji** [comment]
试试最新 alpha 版，有相关优化

**Comment by dcloudhdx** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
