### ISSUE TITLE
阿里小程序IDE uni.createSelectorQuery(...).in is not a function

### ISSUE THREAD

**Issue by diablosin** [dcloudio/uni-app#1190]
**问题描述**
阿里小程序IDE uni.createSelectorQuery(...).in is not a function

**复现步骤**
HBuilder X 运行钉钉小程序项目，调用阿里小程序IDE打开编译后项目，执行相关代码uni.createSelectorQuery().in(this)

**实际结果**
uni.createSelectorQuery(...).in is not a function

**系统信息:**
 - 发行平台: 阿里小程序
 - HBuilderX版本 2.4.6
阿里小程序IDE 1.1.3

**Comment by Wangyaqi** [comment]
阿里系列小程序不支持in(this)  ， 请使用条件编译
// #ifndef MP-ALIPAY
.in(this)
// #endif

**Comment by Wangyaqi** [comment]
现已修改为使用`in(this)`不报错
