### ISSUE TITLE
关于picker中array Obj

### ISSUE THREAD

**Issue by ka-miWei** [dcloudio/uni-app#1194]
发现在使用array-key时，不需要使用冒号（：），且直接使用obj的value值，有点不太懂，是特定用法还？如下：
`						<picker :value="departObjIndex" :range="departObjarr" range-key="name">
							<view class="uni-input">{{departObjarr[departObjIndex].name}}</view>
						</picker>`

**Comment by fxy060608** [comment]
这个是 picker 组件的 props，就跟 value,range 这些一样，是组件自身提供的规范，概念与 vue 的 key 特性不一样。
