### ISSUE TITLE
请求报错 webview里面出现failed to set the "responsetype" property on "xmlhttprequest"

### ISSUE THREAD

**Issue by vkcyan** [dcloudio/uni-app#1195]
**问题描述**
在移动惠生活的webview中请求出现报错
![微信图片_20191227172644](https://user-images.githubusercontent.com/33681955/71511667-1c379480-28ce-11ea-8377-baf76d9f0042.jpg)

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
这个也不能算uniapp的bug,但是不知道为什么在他这个环境就会出现这个报错
并且进入页面时候的第一个请求都没问题

**Comment by vkcyan** [comment]
**问题描述**
在移动惠生活的webview中请求出现报错


**预期结果**
在移动惠生活的webview里面正常使用
 
**实际结果**
 ![微信图片_20191227172644](https://user-images.githubusercontent.com/33681955/71511667-1c379480-28ce-11ea-8377-baf76d9f0042.jpg)
![db350c40392370c1b750e963e6de3c6](https://user-images.githubusercontent.com/33681955/71514749-14cab800-28db-11ea-89ff-ec940e204cab.jpg)
![78a080c387e00e4fdea5affacb3d813](https://user-images.githubusercontent.com/33681955/71514750-15634e80-28db-11ea-8630-b9e5d6e6b923.jpg)


 **系统信息:**
uni-app v2.4.2
uni-app cli v2.0.0-24220191115011
 
 **补充信息**
 这个也不能算uniapp的bug,但是不知道为什么在他这个环境就会出现这个报错
进入页面第一个请求一定没问题的,但是后面莫名奇妙的就会报这个错
也无法搜索到相关解决方案,之前怀疑是localStorage的问题,后面逐步排查发现是因为request的请求问题导致页面异常的
与对方技术调试的过程在,测试包都是没啥问题的,惟独线上出现问题,因为之前taro开发的是没问题的,所以想请教一下官方,对此报错可有什么见解

**Comment by zhetengbiji** [comment]
尝试直接使用XMLHttpRequest试试，uni.request 的实现位于：https://github.com/dcloudio/uni-app/blob/dev/src/platforms/h5/service/api/network/request.js
