### ISSUE TITLE
H5项目在部分安卓手机自带浏览器打开白屏

### ISSUE THREAD

**Issue by wanzijinx** [dcloudio/uni-app#1197]
H5项目大部分手机自带浏览器表现正常，但是部分手机（例如OPPO A5）在自带浏览器打开后白屏，没有报错提示

**Comment by Wangyaqi** [comment]
打开Hello uni-app也是一样的吗？[https://uniapp.dcloud.io/h5](https://uniapp.dcloud.io/h5)

**Comment by wanzijinx** [comment]
> 打开Hello uni-app也是一样的吗？https://uniapp.dcloud.io/h5

这个可以打开

**Comment by Wangyaqi** [comment]
没有报错是在哪看的？vconsole吗？

**Comment by wanzijinx** [comment]
> 没有报错是在哪看的？vconsole吗？

vconsole都出不来，一片空白，页面没有报错是指正常人看不到有页面错误，没有控制台我们也看不到

**Comment by Wangyaqi** [comment]
> > 没有报错是在哪看的？vconsole吗？
> 
> vconsole都出不来，一片空白，页面没有报错是指正常人看不到有页面错误，没有控制台我们也看不到

试一下spy-debugger，看看能不能看出来点啥

**Comment by wanzijinx** [comment]
> > > 没有报错是在哪看的？vconsole吗？
> > 
> > 
> > vconsole都出不来，一片空白，页面没有报错是指正常人看不到有页面错误，没有控制台我们也看不到
> 
> 试一下spy-debugger，看看能不能看出来点啥

已解决，是es6的问题

**Comment by ZhongJianHui** [comment]
> > > > 没有报错是在哪看的？vconsole吗？
> > > 
> > > 
> > > vconsole都出不来，一片空白，页面没有报错是指正常人看不到有页面错误，没有控制台我们也看不到
> > 
> > 
> > 试一下spy-debugger，看看能不能看出来点啥
> 
> 已解决，是es6的问题

具体是es6的什么问题呢
