### ISSUE TITLE
5+SDK,以widget方式集成，在原生和5+之间切换时，偶现崩溃：最后崩溃：[PDRManagerDownloader serialize] 

### ISSUE THREAD

**Issue by Sijia-NR** [dcloudio/uni-app#1198]
1、5+SDK通过widget的方式集成到原生应用中（离线打包），在原生和小程序之前不断切换时，会crash,如下：
![crash](https://user-images.githubusercontent.com/28914359/71570119-5000fd00-2b0e-11ea-951e-5f69595393fa.jpg)
2、原生进入小程序，用的是示例HBuilder-Integrate中WebAppController的方式；
3、小程序退出到原生，是通过在小程序中调用JS：
function iosquit(){
	var Wac = plus.ios.importClass("WebAppControllerManager");
	var manager = Wac.shareManager();
	manager.deallocWebApp(plus.runtime.appid);
	plus.runtime.quit();
}
4、其中WebAppControllerManager是一个包含WebAppController实例的类：
deallocWebApp方法：
-(void)deallocWebApp:(NSString*) appid{
    dispatch_async(dispatch_get_main_queue(), ^{
        [self.app closeSelf];//调用navigationController pop方法退出
        self.app=nil;//self.app是WebAppController实例对象
   });
}

求大神看下，到底是什么原因导致crash的，这crash出现的频率不高，尤其是第一次crash后，再后面就很难出现==

**Comment by dcloudhdx** [comment]
目前不支持这种用法，以后发布的小程序 SDK 会支持

这个需求需要写原生插件 ，用 controlor 实现切换
