### ISSUE TITLE
mpvue微信小程序(自定义组件模式)fail canvas is empty的问题

### ISSUE THREAD

**Issue by UFOwl** [dcloudio/uni-app#1199]
mpvue代码迁移uni-app，已经传入组件实例this，仍然报错。
由于是mpvue，组件实例this与原生小程序组件实例有所不同，也试过传入this.$scope，字段与小程序组件实例相同，未能解决问题。
详情已发论坛：https://ask.dcloud.net.cn/question/86479

**Comment by fxy060608** [comment]
建议上传一个最小化可重现的demo工程

**Comment by UFOwl** [comment]
原来的代码没有commit，现在按当时的思路改回去，又能正常绘制canvas了，怀疑是把this误传至draw函数了，尴尬😅
顺便提一下，直接传`this`就可以，不需要传`this.$scope`（传`this.$scope`也是可以正常绘制的）。
