### ISSUE TITLE
前端框架怎么icons部分的教程都没有

### ISSUE THREAD

**Issue by guyuewuren** [dcloudio/uni-app#12]
前端框架肯定会使用到icons的，可是uni-app框架中怎么使用，官方演示中提供了一个常用的icons，不知道如何使用

**Comment by xiaoyucoding** [comment]
参考 hello uni-app 中的示例，目前仅支持网络字体资源。在项目中，正确引入相关的 css，css 中指向正确的网络字体库。

**Comment by hbcui1984** [comment]
参考：[icon图标](https://uniapp.dcloud.io/extendUI?id=icon-%E5%9B%BE%E6%A0%87)
