### ISSUE TITLE
BUG：打包成APP onUnload里面放uni.switchTab 方法报错

### ISSUE THREAD

**Issue by wuearl** [dcloudio/uni-app#120]
console : Cannot read property 'split' of undefined; at wx.switchTab
console : TypeError: Cannot read property 'split' of undefined

代码我写的
uni.switchTab({
url: '/pages/tabBar/users/users',
})

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
