### ISSUE TITLE
uniapp支持使用mapbox-gl吗

### ISSUE THREAD

**Issue by Mrxpj** [dcloudio/uni-app#1204]
**问题描述**
引入mapbox-gl
地图无法显示出来
控制台报错
Uncaught ReferenceError: **_create is not defined**
    at 16755152-56de-480f-9793-c88bd7e46a16:1
    at 16755152-56de-480f-9793-c88bd7e46a16:1
    at 16755152-56de-480f-9793-c88bd7e46a16:1

-

**Comment by zhetengbiji** [comment]
这个库是否使用了dom、bom等API，如果有使用，不可以在非H5端使用

**Comment by Mrxpj** [comment]
> 这个库是否使用了dom、bom等API，如果有使用，不可以在非H5端使用

你好，请问如何看出他有没有使用dom(是指dom操作吗)、bom等api呢？（我去看了这个库的js文件是有操作dom的）。我在vue-cli初始化的目录是可以在网页上显示出来，然后在uniapp下，本地运行在浏览器上就报上面的那个错了。

**Comment by zhetengbiji** [comment]
> > 这个库是否使用了dom、bom等API，如果有使用，不可以在非H5端使用
> 
> 你好，请问如何看出他有没有使用dom(是指dom操作吗)、bom等api呢？（我去看了这个库的js文件是有操作dom的）。我在vue-cli初始化的目录是可以在网页上显示出来，然后在uniapp下，本地运行在浏览器上就报上面的那个错了。

可以尝试让其作者协助排查一下。

**Comment by Mrxpj** [comment]
> > > 这个库是否使用了dom、bom等API，如果有使用，不可以在非H5端使用
> > 
> > 
> > 你好，请问如何看出他有没有使用dom(是指dom操作吗)、bom等api呢？（我去看了这个库的js文件是有操作dom的）。我在vue-cli初始化的目录是可以在网页上显示出来，然后在uniapp下，本地运行在浏览器上就报上面的那个错了。
> 
> 可以尝试让其作者协助排查一好的，谢谢

**Comment by sai-zhang1123** [comment]
你好，请问uniapp 下可以使用mapbox-gl吗

**Comment by Mrxpj** [comment]
> 你好，请问uniapp下可以使用mapbox-gl吗

如果你做的是非h5端，可以考虑使用改造后的react-native-mapbox-gl或者flutter-mapbox-gl

**Comment by MYyuting** [comment]
可以使用 在app端用renderjs渲染方式
