### ISSUE TITLE
onShareAppMessage无法分享

### ISSUE THREAD

**Issue by aiplat** [dcloudio/uni-app#1208]
**问题描述**
typescript版本的uni-app，onShareAppMessage里面的代码没有执行，标题和路由设置失败。

**复现步骤**
已经写了onShareAppMessage与methods同级，但是无法分享。

在onShow方法添加uni.showShareMenu({
withShareTicket: true,
});

[或者可以直接贴源代码]

**预期结果**
onShareAppMessage里面的代码可以执行正常

**实际结果**
已经写了onShareAppMessage与methods同级，但是无法分享。

在onShow方法添加uni.showShareMenu({
withShareTicket: true,
});

后，点右上 ‘发送给朋友’ 在开发工具上是有如附件报错，但是在微信中 能正常分享出去。

onShareAppMessage里面的代码没有执行，标题和路由设置失败。

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: 所有
 - uni-app版本
uni-app v2.4.2
uni-app cli v2.0.0-24220191115011

**补充信息**
package.json

"dependencies": {
    "@dcloudio/uni-app-plus": "^2.0.0-24220191115006",
    "@dcloudio/uni-h5": "^2.0.0-24220191115006",
    "@dcloudio/uni-helper-json": "*",
    "@dcloudio/uni-mp-alipay": "^2.0.0-24220191115006",
    "@dcloudio/uni-mp-baidu": "^2.0.0-24220191115006",
    "@dcloudio/uni-mp-qq": "^2.0.0-24220191115006",
    "@dcloudio/uni-mp-toutiao": "^2.0.0-24220191115006",
    "@dcloudio/uni-mp-weixin": "^2.0.0-24220191115006",
    "@dcloudio/uni-stat": "^2.0.0-24220191115006",
    "flyio": "^0.6.2",
    "regenerator-runtime": "^0.12.1",
    "vue": "^2.6.10",
    "vue-class-component": "^6.3.2",
    "vue-property-decorator": "^8.0.0",
    "vuex": "^3.1.2"
  },
  "devDependencies": {
    "@babel/plugin-syntax-typescript": "^7.7.4",
    "@dcloudio/types": "*",
    "@dcloudio/uni-cli-shared": "^2.0.0-24220191115006",
    "@dcloudio/uni-template-compiler": "^2.0.0-24220191115006",
    "@dcloudio/vue-cli-plugin-hbuilderx": "latest",
    "@dcloudio/vue-cli-plugin-uni": "latest",
    "@dcloudio/vue-cli-plugin-uni-optimize": "^2.0.0-24220191115006",
    "@dcloudio/webpack-uni-mp-loader": "^2.0.0-24220191115006",
    "@dcloudio/webpack-uni-pages-loader": "^2.0.0-24220191115006",
    "@vue/cli-plugin-babel": "3.5.1",
    "@vue/cli-plugin-typescript": "^3.5.1",
    "@vue/cli-service": "^4.1.1",
    "babel-plugin-import": "^1.13.0",
    "crypto-js": "^3.1.9-1",
    "less": "^3.9.0",
    "less-loader": "^4.1.0",
    "postcss-comment": "^2.0.0",
    "shelljs": "^0.8.3",
    "typescript": "^3.7.3",
    "vue-template-compiler": "^2.6.10"
  },

**Comment by aiplat** [comment]
Uncaught TypeError: Cannot read property 'apply' of null;

**Comment by aiplat** [comment]
https://tongji.dcloud.io 不在以下 request 合法域名列表中 ,   

现在点击分享经常弹出这个

**Comment by Wangyaqi** [comment]
HBuilderX 2.2.3起，新增了uni统计，一份报表看全端数据，详见 https://tongji.dcloud.io 。
在小程序端，使用uni统计需在安全域名名单中新增 tongji.dcloud.io 。如不需要uni统计，可在manifest中关闭。开通和关闭详见：https://ask.dcloud.net.cn/article/36303

**Comment by Wangyaqi** [comment]
测试了一下没遇到你说的分享问题，是不是别的代码导致的
