### ISSUE TITLE
npm  run  dev:mp-weixin  开启压缩代码

### ISSUE THREAD

**Issue by hxzAugustinus** [dcloudio/uni-app#1209]
HBuilder X   运行->运行到小程序模拟器 -> 运行时是否压缩代码  选项，如何在npm   run  dev:mp-weixin 编译时添加该选项
![1](https://user-images.githubusercontent.com/14306029/71662690-50f39200-2d8d-11ea-999f-4fe58e14b6a6.png)

**Comment by Wangyaqi** [comment]
照着这个试一下，[vendor.js过大的处理方式](https://uniapp.dcloud.io/matter?id=vendorjs%E8%BF%87%E5%A4%A7%E7%9A%84%E5%A4%84%E7%90%86%E6%96%B9%E5%BC%8F)

**Comment by hxzAugustinus** [comment]
多谢，有效果了

**Comment by 772778995** [comment]
请问 vite 构建方式如何运行时压缩？
`"dev:mp-weixin": "uni -p mp-weixin"`

**Comment by Ym-wei** [comment]
> 请问 vite 构建方式如何运行时压缩？ `"dev:mp-weixin": "uni -p mp-weixin"`

你好, 请问vite 知道怎么运行时压缩么

**Comment by fxy060608** [comment]
vite.config.js 
build:{minify:true}
