### ISSUE TITLE
uni.getProvider()在H5环境中返回的provider为空，调用uni.login()时报[system] API `login` is not yet implemented

### ISSUE THREAD

**Issue by bulldg** [dcloudio/uni-app#121]
uni.getProvider({
    service: 'oauth',
    success: oauthRes => {
	uni.login({
            provider: oauthRes.provider[0],
	    success: res => {
	         consoe.log(res.code);
             },
         });
    },
});

**Comment by zhetengbiji** [comment]
H5端并未封装此类功能，具体请参考文档

**Comment by bulldg** [comment]
那么请问，如果我想在h5上获取Code，应该怎么处理呢，之前单纯做h5时，可以用sdk鉴权的那一套，现在怎么处理好呢
