### ISSUE TITLE
h5 input赋值成功 但是input中得值没更新

### ISSUE THREAD

**Issue by myjustify** [dcloudio/uni-app#1211]
**问题描述**
h5 input赋值成功 但是input中得值没更新
使用了
this.$nextTick(()=>{
	this.$forceUpdate();
})
还是不更新

**复现步骤**
`<input type='digit' :value="truckLoadingWeight" @input="weightInput($event,'truckLoadingWeight')" maxlength='8' placeholder='请输入装车重量'></input>`

```
weightInput(e,filed){
  let newVal = e.detail.value;
  let oldVal = this[filed];
  if(newVal>100){
     this[filed] = oldVal;
     this.$nextTick(()=>{
     this.$forceUpdate();					
     })
  }else{
     this[filed] = newVal;
  }
}
```

预期结果：
  不会输入大于100得值

实际结果：
输入框的值不会限制 但是data 内的值是小于100的

**Comment by zhetengbiji** [comment]
试试把this[filed] = oldVal;放this.$nextTick里

**Comment by myjustify** [comment]
> 试试把this[filed] = oldVal;放this.$nextTick里

不行的

**Comment by bxpxqxd** [comment]
input、textarea 组件的 input 事件处理函数内实时修改当前值不生效，可以延迟设置，例如：setTimeout(() => { this.value = 100 }, 0)

**Comment by myjustify** [comment]
老哥，这样也是不行的，你在浏览器测试一下我这确实是不生效的

**Comment by myjustify** [comment]
由
`if(newVal>100){
  setTimeout(()=>{
    this.weight = oldVal;
  },0)
}else{
  this.weight = newVal;
}`
改成
`this.weight = newVal;
if(newVal>100){
 setTimeout(()=>{
   this.weight = oldVal;
},0)
}`
就可以实现
