### ISSUE TITLE
多级页面跳转回退，页面刷新问题

### ISSUE THREAD

**Issue by telfordNiu** [dcloudio/uni-app#1212]
**问题描述**
遇到一个多级页面回退刷新的问题：
如果a页面是首页，b页面是二级页面，a进入b，然后回退，a页面不会刷新。
但是如果b页面进入到c页面，从c返回到b页面，b页面就刷新了，
现在不想让b页面刷新，请问如何解决？谢谢

**系统信息:**
 - 发行平台: [H5平台]

**Comment by Wangyaqi** [comment]
没出现你说的刷新，onLoad没有重复执行，看下是不是你B页面的onShow里面有什么逻辑
