### ISSUE TITLE
uniPush - 离线推送 - 华为厂商配置无效

### ISSUE THREAD

**Issue by jianguiweilai** [dcloudio/uni-app#1213]
**问题描述**
配置华为厂商离线消息配置后，通过unipush后台发送消息，华为手机获取不到离线消息；
联系个推客服人员后：（clientid  ：c62bd733acd4dac908e7e0f6f17949a2）
![image](https://user-images.githubusercontent.com/15683188/71711120-7b4f5900-2e3a-11ea-928f-f93b71247248.png)

**Comment by tonlion** [comment]
如果在华为手机应用退出后无法接收到推送消息，可尝试以下操作：

1. 更新“华为移动服务”到最新版本；
2. 进入手机“设置”，在[应用和通知]->[应用管理]->[华为移动服务]->[存储]页面选择“删除数据”。
重新启动应用，退出后再下发推送消息。

**Comment by jianguiweilai** [comment]
设置以后也走不通，客服说是uniapp客户端集成华为消息推送有问题， deviceToken 缺失

**Comment by jianguiweilai** [comment]
最后离线推送配置好了
