### ISSUE TITLE
livepush组件在ios中无法使用

### ISSUE THREAD

**Issue by wh521518** [dcloudio/uni-app#1214]
**问题描述**
在uniapp的webview中调用的livepush组件进行直播推流，在andorid中可以正常使用，但是在ios中报如下错误

 [14:52:47] <ERROR> [s|undefined]  getUserMedia error observed TypeError: undefined is not an object (evaluating 'navigator.mediaDevices.getUserMedia') 

14:52:48.225  failed initialize localStream TypeError: undefined is not an object (evaluating 'navigator.mediaDevices.getUserMedia')

**系统信息:**
 - 发行平台: 5+APP
 - 操作系统 IOS 12.0 
 - HBuilderX版本 [2.4.6.20191210]
 - 设备信息 [ipad iphonex]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Wangyaqi** [comment]
你说的这个livepush组件是什么？自己实现的吗？

**Comment by wh521518** [comment]
> 你说的这个livepush组件是什么？自己实现的吗？

emmm 我在uniapp中嵌套web-view然后在web-view中调用plus.LivePusher进行直播，在ios端有的时候只有音频！！

**Comment by Wangyaqi** [comment]
可以上传一个demo上来我们验证一下

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
