### ISSUE TITLE
props传递Object的咨询

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#1219]
我现在在父组件有一个列表，列表里面存的全是Object对象。

父组件传递每一个Object给子组件，然后在 子组件 里面给这个 Object 增加了一个key。

现在我想在父组件里面取出这个Object新增的key的值。

# 结果

- 微信小程序，取值为undefined；
- h5可以取出来正确的结果；
- app-nvue下ios端取值正确；

微信下为啥子取不到值？难道这个Object不应该始终是同一个对象吗？有点迷惑。

谢谢。

**Comment by lincenying** [comment]
vue是极不推荐在子组件修改prop的值

https://cn.vuejs.org/v2/guide/components-props.html#%E5%8D%95%E5%90%91%E6%95%B0%E6%8D%AE%E6%B5%81

https://cn.vuejs.org/v2/guide/components-custom-events.html#sync-%E4%BF%AE%E9%A5%B0%E7%AC%A6

**Comment by wakaryry** [comment]
是不推荐。

不过因为是对象的某个属性，而且我只在父组件里面根据用户动作获取这个属性，而不是实时响应，所以为了方便，更改并不会影响任何的内容。

而且，按照道理来说，不管我是不是更改某个属性。我props传递过去的Object，在小程序里面会被复制一份？已经变得不再是以前的它了。

正常应该不是这个变量还是维持以前的地址莫。
