### ISSUE TITLE
组件 hidden 属性失效

### ISSUE THREAD

**Issue by xiaoyucoding** [dcloudio/uni-app#1225]
**问题描述**
通过组件的 hidden 属性，控制组件的显示/隐藏失败。

**复现步骤**
``` html
<template>
  <view>
    <view class="content" :hidden="hide">
      这是内容
    </view>
    <button type="primary" @click="changeStatus">click me</button>
  </view>
</template>

<script>
  export default {
    data() {
      return {
        hide: false
      }
    },
    methods: {
      changeStatus() {
        this.hide = !this.hide;
      }
    }
  }
</script>

<style>
  .content {
    display: flex;
  }
</style>
```

**预期结果**
hide 为 true 时隐藏内容区域。

**实际结果**
内容区域始终处于可见状态，未能隐藏。

**系统信息:**
 - 发行平台: H5平台，其它平台未测试。
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本
    - uni-app v2.5.1
    - uni-app cli v2.0.0-alpha-25120200103006
 - 设备信息 Chrome

**补充信息**
主动设置了组件的`display`属性，会覆盖掉`[hidden]`属性选择器的样式。

**Comment by fxy060608** [comment]
建议使用v-show

**Comment by xiaoyucoding** [comment]
经测试，微信小程序也存在同样的问题，看来目前只能通过主动修改样式来处理了。

**Comment by wangQiaoBrother** [comment]
> 建议使用v-show

这个不行 现在还有问题

**Comment by wanxchao** [comment]
> > 建议使用v-show
> 
> 这个不行 现在还有问题

还是不能通过 v-show 控制组件的展示与隐藏，目前只能通过 v-if 控制

**Comment by zhetengbiji** [comment]
> > > 建议使用v-show
> > 
> > 
> > 这个不行 现在还有问题
> 
> 还是不能通过 v-show 控制组件的展示与隐藏，目前只能通过 v-if 控制

在 App.vue 增加 [hidden]{display: none !important;}

**Comment by zhetengbiji** [comment]
> > > 建议使用v-show
> > 
> > 
> > 这个不行 现在还有问题
> 
> 还是不能通过 v-show 控制组件的展示与隐藏，目前只能通过 v-if 控制

在 App.vue 增加 [hidden]{display: none !important;}
