### ISSUE TITLE
微信登陆授权

### ISSUE THREAD

**Issue by yujun96** [dcloudio/uni-app#1227]
**问题描述**
uni-app调用微信登陆。第一次授权登陆正常。第二次授权登陆，授权页面闪退。直接登陆了。uni.login直接走success了。应该是微信缓存问题

**预期结果**
1.点击微信授权登陆，进行授权。进入页面，退出登陆，在进行微信授权，进入授权页面。登陆成功

**实际结果**
1.点击微信授权登陆，进行授权。进入页面，退出登陆，在进行微信授权，页面闪退，直接登陆成功了

**系统信息:**
 - 发行平台: [5+ App等]
 - 操作系统 [Android 7.0]
 - HBuilderX版本 HBuilderX，
 - uni-app版本  2.4.6
 - 设备信息 小米，华为，三星

**补充信息**
[可选]
微信缓存

**Comment by Wangyaqi** [comment]
是要每次都进入授权页面等用户同意吗？

**Comment by yujun96** [comment]
不是啊，是第一次进入授权登陆。退出登陆后。在授权微信登陆，不会唤起授权页面，直接登陆了。

**Comment by yujun96** [comment]
> 是要每次都进入授权页面等用户同意吗？

不是啊，是第一次进入授权登陆。退出登陆后。在授权微信登陆，不会唤起授权页面，直接登陆了

**Comment by Wangyaqi** [comment]
[https://www.html5plus.org/doc/zh_cn/oauth.html#plus.oauth.AuthService.logout](https://www.html5plus.org/doc/zh_cn/oauth.html#plus.oauth.AuthService.logout) 用的是这个退出登录吗？

**Comment by yujun96** [comment]
> https://www.html5plus.org/doc/zh_cn/oauth.html#plus.oauth.AuthService.logout 用的是这个退出登录吗？目前就是这样的，微信那边的缓存我们也没啥好办法

没用这个退出。我仿照官方给的login模版写的。 而且官方的login的微信登陆也存在这个问题

**Comment by yujun96** [comment]
> > https://www.html5plus.org/doc/zh_cn/oauth.html#plus.oauth.AuthService.logout 用的是这个退出登录吗？目前就是这样的，微信那边的缓存我们也没啥好办法
> 
> 没用这个退出。我仿照官方给的login模版写的。 而且官方的login的微信登陆也存在这个问题

> https://www.html5plus.org/doc/zh_cn/oauth.html#plus.oauth.AuthService.logout 用的是这个退出登录吗？目前就是这样的，微信那边的缓存我们也没啥好办法

**Comment by yujun96** [comment]
> https://www.html5plus.org/doc/zh_cn/oauth.html#plus.oauth.AuthService.logout 用的是这个退出登录吗？目前就是这样的，微信那边的缓存我们也没啥好办法

刚刚使用了5+app的那个退出接口，依然存在相同的问题

**Comment by Kole6** [comment]
这个问题解决了吗，怎么关闭了
