### ISSUE TITLE
web网页怎么获取微信code

### ISSUE THREAD

**Issue by sunweihao1116** [dcloudio/uni-app#123]
uni.login()在网页里会报错，想知道怎么在网页里拿微信code

**Comment by zhetengbiji** [comment]
请说清楚

**Comment by sunweihao1116** [comment]
想在网页里拿微信code，就是微信鉴权那一套

**Comment by zhetengbiji** [comment]
H5未对此功能封装（文档有说明），UNI-APP 开发微信公众号（H5）JS-SDK 的使用方式：http://ask.dcloud.net.cn/article/35380
