### ISSUE TITLE
微信缓存

### ISSUE THREAD

**Issue by yujun96** [dcloudio/uni-app#1232]
问题描述
uni-app调用微信登陆。第一次授权登陆正常。第二次授权登陆，授权页面闪退。直接登陆了。uni.login直接走success了。应该是微信缓存问题

预期结果
1.点击微信授权登陆，进行授权。进入页面，退出登陆，在进行微信授权，进入授权页面。登陆成功

实际结果
1.点击微信授权登陆，进行授权。进入页面，退出登陆，在进行微信授权，页面闪退，直接登陆成功了

系统信息:

发行平台: [5+ App等]
操作系统 [Android 7.0]
HBuilderX版本 HBuilderX，
uni-app版本 2.4.6
设备信息 小米，华为，三星
补充信息
[可选]
微信缓存

**Comment by yujun96** [comment]
刚刚使用了5+app的那个退出接口，依然存在相同的问题

**Comment by yujun96** [comment]
官方的demo也存在这个问题

**Comment by Wangyaqi** [comment]
这不算是个问题吧，现在为什么要出授权页面？你更换微信账号的话确实会出，不换账号微信那边确实没必要让用户重新点那个按钮吧
