### ISSUE TITLE
hbuilderx全屏状态下会卡住

### ISSUE THREAD

**Issue by MikuBlog** [dcloudio/uni-app#1234]
**问题描述**

最小化后再打开全屏`hbuilderx`会概率卡住，缩放一下即可解决。

**复现步骤**
[复现问题的步骤]
1. 启动`hbuilderx`并全屏化
2. `hbuilderx`最小化
3. 点击`hbuilderx`

**预期结果**

正常运行

**实际结果**

概率卡住

**系统信息:**

 - 操作系统 win10（1909）
 - HBuilderX版本 2.5.1

**补充信息**

无

**Comment by wandali2019** [comment]
菜单【帮助】【查看运行日志】，提供下日志

**Comment by MikuBlog** [comment]
可能是系统问题，后面重启电脑后暂时没有发现该问题
