### ISSUE TITLE
uni.canvasGetImageData()在h5端获取的数据都是0

### ISSUE THREAD

**Issue by BiggerWu** [dcloudio/uni-app#1235]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
需要实现获取图片的颜色，然后使用了canvas，在使用uni.canvasGetImageData()时无论发送的坐标是什么，都是返回0值，我用微信小程序测试发现，微信小程序能正常获取。

**Comment by zhetengbiji** [comment]
图片需要允许跨域

**Comment by BiggerWu** [comment]
问题解决了，谢谢，问题出在获取颜色的坐标值，我用了touch属性的值，这个值是以窗体左上角为原点的，应该以canvas的左上角为原点。

**Comment by zhetengbiji** [comment]
> 问题解决了，谢谢，问题出在获取颜色的坐标值，我用了touch属性的值，这个值是以窗体左上角为原点的，应该以canvas的左上角为原点。

是以canvas左上角为原点的，你使用的版本是多少？是不是比较早起的版本
