### ISSUE TITLE
编译时 Cannot find module '../../vue-cli-plugin-uni/packages/vue-template-compiler'

### ISSUE THREAD

**Issue by zzlit** [dcloudio/uni-app#1237]
只在这一台电脑上安装依赖之后`npm run dev:mp-weixin`有问题，其他的都没有问题，创建一个新项目也能跑起来，
```
-  开始编译当前项目至 mp-weixin 平台... ERROR  Error: Cannot find module '../../vue-cli-plugin-uni/packages/vue-template-compiler'
Require stack:
- D:\git\top-boom\node_modules\_@dcloudio_uni-template-compiler@2.0.0-25120200103006@@dcloudio\uni-template-compiler\lib\index.js
- D:\git\top-boom\node_modules\_@dcloudio_uni-cli-shared@2.0.0-25120200103006@@dcloudio\uni-cli-shared\lib\platform.js
- D:\git\top-boom\node_modules\_@dcloudio_uni-cli-shared@2.0.0-25120200103006@@dcloudio\uni-cli-shared\lib\index.js
- D:\git\top-boom\node_modules\_@dcloudio_vue-cli-plugin-hbuilderx@2.0.0-25120200103006@@dcloudio\vue-cli-plugin-hbuilderx\module-alias.js
- D:\git\top-boom\node_modules\_@dcloudio_vue-cli-plugin-hbuilderx@2.0.0-25120200103006@@dcloudio\vue-cli-plugin-hbuilderx\index.js
- D:\git\top-boom\node_modules\_@vue_cli-service@4.1.2@@vue\cli-service\lib\Service.js
- D:\git\top-boom\node_modules\_@vue_cli-service@4.1.2@@vue\cli-service\bin\vue-cli-service.js
Error: Cannot find module '../../vue-cli-plugin-uni/packages/vue-template-compiler'
Require stack:
- D:\git\top-boom\node_modules\_@dcloudio_uni-template-compiler@2.0.0-25120200103006@@dcloudio\uni-template-compiler\lib\index.js
- D:\git\top-boom\node_modules\_@dcloudio_uni-cli-shared@2.0.0-25120200103006@@dcloudio\uni-cli-shared\lib\platform.js
- D:\git\top-boom\node_modules\_@dcloudio_uni-cli-shared@2.0.0-25120200103006@@dcloudio\uni-cli-shared\lib\index.js
- D:\git\top-boom\node_modules\_@dcloudio_vue-cli-plugin-hbuilderx@2.0.0-25120200103006@@dcloudio\vue-cli-plugin-hbuilderx\module-alias.js
- D:\git\top-boom\node_modules\_@dcloudio_vue-cli-plugin-hbuilderx@2.0.0-25120200103006@@dcloudio\vue-cli-plugin-hbuilderx\index.js
- D:\git\top-boom\node_modules\_@vue_cli-service@4.1.2@@vue\cli-service\lib\Service.js
- D:\git\top-boom\node_modules\_@vue_cli-service@4.1.2@@vue\cli-service\bin\vue-cli-service.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._resolveFilename (D:\git\top-boom\node_modules\_module-alias@2.2.2@module-alias\index.js:49:29)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (D:\git\top-boom\node_modules\_@dcloudio_uni-template-compiler@2.0.0-25120200103006@@dcloudio\uni-template-compiler\lib\index.js:11:5)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at getPlatformCompiler (D:\git\top-boom\node_modules\_@dcloudio_uni-cli-shared@2.0.0-25120200103006@@dcloudio\uni-cli-shared\lib\platform.js:556:14)
    at D:\git\top-boom\node_modules\_@dcloudio_vue-cli-plugin-uni@2.0.0-25120200103006@@dcloudio\vue-cli-plugin-uni\lib\vue-loader.js:32:17
    at Object.tap (D:\git\top-boom\node_modules\_webpack-chain@6.3.0@webpack-chain\src\Use.js:14:20)
    at modifyVueLoader (D:\git\top-boom\node_modules\_@dcloudio_vue-cli-plugin-uni@2.0.0-25120200103006@@dcloudio\vue-cli-plugin-uni\lib\vue-loader.js:30:6)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! topboom@0.1.0 dev:mp-weixin: `cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the topboom@0.1.0 dev:mp-weixin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zzlit\AppData\Roaming\npm-cache\_logs\2020-01-07T16_28_23_501Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! topboom@0.1.0 serve: `npm run dev:mp-weixin`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the topboom@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

这是`npm run info`的信息
```
uni-app v2.5.1
uni-app cli v2.0.0-25120200103006

Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4200H CPU @ 2.80GHz
  Binaries:
    Node: 12.14.0 - D:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.4 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @dcloudio/uni-app-plus: ^2.0.0-24220191115011 => 2.0.0-25120200103006
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: ^2.0.0-24220191115011 => 2.0.0-25120200103006
    @dcloudio/uni-h5: ^2.0.0-24220191115011 => 2.0.0-25120200103006
    @dcloudio/uni-helper-json: * => 1.0.4
    @dcloudio/uni-mp-alipay: ^2.0.0-24220191115011 => 2.0.0-25120200103006
    @dcloudio/uni-mp-baidu: ^2.0.0-24220191115011 => 2.0.0-25120200103006
    @dcloudio/uni-mp-qq: ^2.0.0-24220191115011 => 2.0.0-25120200103006
    @dcloudio/uni-mp-toutiao: ^2.0.0-24220191115011 => 2.0.0-25120200103006
    @dcloudio/uni-mp-weixin: ^2.0.0-24220191115011 => 2.0.0-25120200103006
    @dcloudio/uni-stat: ^2.0.0-24220191115011 => 2.0.0-25120200103006
    @dcloudio/uni-template-compiler: ^2.0.0-24220191115011 => 2.0.0-25120200103006
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-24220191115011 => 2.0.0-25120200103006
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-24220191115011 => 2.0.0-25120200103006
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-24220191115011 => 2.0.0-25120200103006
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-24220191115011 => 2.0.0-25120200103006
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-24220191115011 => 2.0.0-25120200103006
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  3.12.1
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.1.2
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-plugin-router:  4.1.2
    @vue/cli-plugin-vuex:  4.1.2
    @vue/cli-service: ^4.1.0 => 4.1.2
    @vue/cli-shared-utils:  4.1.2
    @vue/component-compiler-utils:  3.1.1 (3.1.1, 3.1.1, 3.1.1)
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.11
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.8.3
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.2
  npmGlobalPackages:
    @vue/cli: Not Found
```
vue-cli也重新安装过了，求大佬解答一下~

**Comment by zzlit** [comment]
```
> topboom@0.1.0 dev:mp-weixin D:\git\top-boom
> cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch

请注意运行模式下，因日志输出、sourcemap以及未压缩源码等原因，性能和包体积，均不及发行模式。若要正式发布，请点击发行菜单或使用cli发布命令进行发布

-  开始编译当前项目至 mp-weixin 平台... ERROR  Error: No matching use for foo.js
Error: No matching use for foo.js
    at updateJsLoader (D:\git\top-boom\node_modules\@dcloudio\vue-cli-plugin-uni\lib\configure-webpack.js:58:13)
    at D:\git\top-boom\node_modules\@dcloudio\vue-cli-plugin-uni\lib\configure-webpack.js:162:5
    at D:\git\top-boom\node_modules\@vue\cli-service\lib\Service.js:255:21
    at Array.forEach (<anonymous>)
    at Service.resolveWebpackConfig (D:\git\top-boom\node_modules\@vue\cli-service\lib\Service.js:252:30)
    at PluginAPI.resolveWebpackConfig (D:\git\top-boom\node_modules\@vue\cli-service\lib\PluginAPI.js:132:25)
    at module.exports (D:\git\top-boom\node_modules\@vue\cli-service\lib\commands\build\resolveAppConfig.js:39:25)
    at getWebpackConfig (D:\git\top-boom\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:49:88)
    at getWebpackConfigs (D:\git\top-boom\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:75:13)
    at build (D:\git\top-boom\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:112:26)
    at D:\git\top-boom\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:40:11
    at Service.run (D:\git\top-boom\node_modules\@vue\cli-service\lib\Service.js:234:12)
    at Object.<anonymous> (D:\git\top-boom\node_modules\@vue\cli-service\bin\vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! topboom@0.1.0 dev:mp-weixin: `cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the topboom@0.1.0 dev:mp-weixin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zzlit\AppData\Roaming\npm-cache\_logs\2020-01-08T16_45_35_878Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! topboom@0.1.0 serve: `npm run dev:mp-weixin`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the topboom@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
更新一下错误代码。。。该删的重装的都试过了，版本也都更新了，就是不行

**Comment by dcloudhdx** [comment]
第一个问题已确认，请贴第二个问题的 npm run info

**Comment by ChrisDowney1996** [comment]
> cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch

请注意运行模式下，因日志输出、sourcemap以及未压缩源码等原因，性能和包体积，均不及发行模式。若要正式发布，请点击发行菜单或使用cli发布命令进行发布

-  开始编译当前项目至 mp-weixin 平台... ERROR  Error: Cannot find module '../../vue-cli-plugin-uni/packages/vue-template-compiler'
Require stack:

我也有这个问题，官方有时间解决一下吗？

**Comment by zzlit** [comment]
@dcloudhdx 更新了包无法复现了，只有第一个问题稳定复现

**Comment by dcloudhdx** [comment]
> > cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch
> 
> 请注意运行模式下，因日志输出、sourcemap以及未压缩源码等原因，性能和包体积，均不及发行模式。若要正式发布，请点击发行菜单或使用cli发布命令进行发布
> 
> * 开始编译当前项目至 mp-weixin 平台... ERROR  Error: Cannot find module '../../vue-cli-plugin-uni/packages/vue-template-compiler'
>   Require stack:
> 
> 我也有这个问题，官方有时间解决一下吗？

Alpha 版已修复

**Comment by zzlit** [comment]
@dcloudhdx 
```
-  开始编译当前项目至 mp-weixin 平台... ERROR  Error: No matching use for foo.js
Error: No matching use for foo.js
    at updateJsLoader (D:\git\top-boom\node_modules\@dcloudio\vue-cli-plugin-uni\lib\configure-webpack.js:58:13)
    at D:\git\top-boom\node_modules\@dcloudio\vue-cli-plugin-uni\lib\configure-webpack.js:162:5
    at D:\git\top-boom\node_modules\@vue\cli-service\lib\Service.js:255:21
    at Array.forEach (<anonymous>)
    at Service.resolveWebpackConfig (D:\git\top-boom\node_modules\@vue\cli-service\lib\Service.js:252:30)
    at PluginAPI.resolveWebpackConfig (D:\git\top-boom\node_modules\@vue\cli-service\lib\PluginAPI.js:132:25)
    at module.exports (D:\git\top-boom\node_modules\@vue\cli-service\lib\commands\build\resolveAppConfig.js:39:25)
    at getWebpackConfig (D:\git\top-boom\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:49:88)
    at getWebpackConfigs (D:\git\top-boom\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:75:13)
    at build (D:\git\top-boom\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:112:26)
    at D:\git\top-boom\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:40:11
    at Service.run (D:\git\top-boom\node_modules\@vue\cli-service\lib\Service.js:234:12)
    at Object.<anonymous> (D:\git\top-boom\node_modules\@vue\cli-service\bin\vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:959:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
    at Module.load (internal/modules/cjs/loader.js:815:32)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! topboom@0.1.0 dev:mp-weixin: `cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the topboom@0.1.0 dev:mp-weixin script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zzlit\AppData\Roaming\npm-cache\_logs\2020-01-10T16_36_29_105Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! topboom@0.1.0 serve: `npm run dev:mp-weixin`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the topboom@0.1.0 serve script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

npm run info
```
uni-app v2.5.1
uni-app cli v2.0.0-25120200103006

Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4200H CPU @ 2.80GHz
  Binaries:
    Node: 12.14.0 - D:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.4 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @dcloudio/uni-app-plus: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/uni-h5: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/uni-helper-json: ^1.0.5 => 1.0.5
    @dcloudio/uni-mp-alipay: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/uni-mp-baidu: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/uni-mp-qq: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/uni-mp-toutiao: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/uni-mp-weixin: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/uni-stat: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/uni-template-compiler: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-25120200103006 => 2.0.0-25120200103006
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.1.2
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.1.2
    @vue/cli-plugin-babel: ^4.1.2 => 4.1.2
    @vue/cli-plugin-router:  4.1.2
    @vue/cli-plugin-vuex:  4.1.2
    @vue/cli-service: ^4.1.2 => 4.1.2
    @vue/cli-shared-utils: ^4.1.2 => 4.1.2
    @vue/component-compiler-utils:  3.1.1 (3.1.1)
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.11 => 2.6.11
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.8.3
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.1.2 => 3.1.2
  npmGlobalPackages:
    @vue/cli: Not Found
```

我记得脚手架npm update 就直接是alpha版本的吧？

**Comment by JimboXie** [comment]
猜测是 国内的npm包与国外不一致导致的！
`npm i` 安装一下运行就可以

**Comment by hezhenrong** [comment]
你好解决了吗
我也是这个问题。同事电脑可以运行，我的电脑运行就不行

**Comment by zzlit** [comment]
@hezhenrong 我重新安装了一遍node和npm，然后npm update就好了。。

**Comment by hezhenrong** [comment]
@zzlit 你是覆盖安装吗，还是卸载了再安装的

**Comment by hezhenrong** [comment]
我也可以了。安装node和npm感觉不是关键，关键是一开始我是用cnpm install安装依赖的，然后用npm去运行，然后就报错了。后面我删掉了node_modules，然后改用npm install去安装依赖，然后报错node-sass和Python的错误。这个错误的原因是国内会过滤掉GitHub去安装依赖，所以得再用cnpm去安装（cnpm install node-sass sass-loader）。安装完成后，再用npm run dev:mp-weixin就可以运行成功了。
总结：
0、删除之前安装的依赖（删除node_modules文件夹）
1、npm install安装依赖
2、cnpm install node-sass sass-loader安装sass（如果需要安装sass的话）
3、npm run dev:mp-weixin运行

**Comment by AK47-dadada** [comment]
我醉了 更新以后项目炸了，'@dcloudio/vue-cli-plugin-uni/packages/@vue/component-compiler-utils'，解决方案哪个有，给一个吧，跪求

**Comment by magxl** [comment]
写着写着，重启服务后，vuecliservice丢了，再安不行了

**Comment by yb81312043** [comment]
本来想从新构建个项目，被这个问题困扰了一天。我总结出的原因是@dcloudio整体包的版本+（@vue/cli-plugin-babel，@vue/cli-service）的版本导致的问题。我降级为之前使用的版本就可以了。https://github.com/dcloudio/uni-app/pull/2103 说是解决了，我弄了半天也没通。
贴一份能使用的npm info：
uni-app v2.8.11
uni-app cli v2.0.0-alpha-28920200917001

Environment Info:

  System:
    OS: macOS High Sierra 10.13.6
    CPU: (4) x64 Intel(R) Core(TM) i5-7267U CPU @ 3.10GHz
  Binaries:
    Node: 12.18.4 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.6 - /usr/local/bin/npm
  Browsers:
    Chrome: 85.0.4183.102
    Firefox: Not Found
    Safari: 13.1.2
  npmPackages:
    @dcloudio/types: * => 2.0.7 
    @dcloudio/uni-app-plus: ^2.0.0-alpha-26420200309006 => 2.0.0-alpha-28920200917001 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-cli-shared: ^2.0.0-alpha-26420200309006 => 2.0.0-alpha-28920200917001 
    @dcloudio/uni-h5: ^2.0.0-alpha-26420200309006 => 2.0.0-alpha-28920200917001 
    @dcloudio/uni-helper-json: * => 1.0.6 
    @dcloudio/uni-migration: ^2.0.0-alpha-26420200309006 => 2.0.0-alpha-28920200917001 
    @dcloudio/uni-mp-alipay: ^2.0.0-alpha-26420200309006 => 2.0.0-alpha-28920200917001 
    @dcloudio/uni-mp-baidu: ^2.0.0-alpha-26420200309006 => 2.0.0-alpha-28920200917001 
    @dcloudio/uni-mp-qq: ^2.0.0-alpha-26420200309006 => 2.0.0-alpha-28920200917001 
    @dcloudio/uni-mp-toutiao: ^2.0.0-alpha-26420200309006 => 2.0.0-alpha-28920200917001 
    @dcloudio/uni-mp-weixin: ^2.0.0-alpha-26420200309006 => 2.0.0-alpha-28920200917001 
    @dcloudio/uni-stat: ^2.0.0-alpha-26420200309006 => 2.0.0-v3-24020191018001 
    @dcloudio/uni-template-compiler: ^2.0.0-alpha-26420200309006 => 2.0.0-alpha-28920200917001 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-alpha-26420200309006 => 2.0.0-alpha-28920200917001 
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-alpha-26420200309006 => 2.0.0-alpha-28920200917001 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-alpha-26420200309006 => 2.0.0-alpha-28920200917001 
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-alpha-26420200309006 => 2.0.0-alpha-28920200917001 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-alpha-26420200309006 => 2.0.0-alpha-28920200917001 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  3.12.1 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.5.6 
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1 
    @vue/cli-plugin-router:  4.5.6 
    @vue/cli-plugin-typescript: * => 4.5.6 
    @vue/cli-plugin-vuex:  4.5.6 
    @vue/cli-service: ^4.2.3 => 4.5.6 
    @vue/cli-shared-utils:  4.5.6 
    @vue/component-compiler-utils:  3.2.0 (3.2.0)
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/web-component-wrapper:  1.2.0 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.11 => 2.6.12 
    vue-class-component: ^6.3.2 => 6.3.2 (7.2.6)
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.3 (16.0.0-beta.7, 15.9.3)
    vue-property-decorator: ^8.0.0 => 8.5.1 
    vue-router:  3.0.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.12 (2.6.12)
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.0.1 => 3.5.1 
  npmGlobalPackages:
    @vue/cli: 4.5.6

**Comment by Wxh16144** [comment]
> 我醉了 更新以后项目炸了，'@dcloudio/vue-cli-plugin-uni/packages/@vue/component-compiler-utils'，解决方案哪个有，给一个吧，跪求

请问你找到解决方案了吗，这边也遇到这个问题了。(((φ(◎ロ◎;)φ)))

**Comment by AK47-dadada** [comment]
最后找他们那边开发解决的。。。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dcloudio/uni-app"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月16日(星期五) 上午10:53
收件人:&nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&gt;;
抄送:&nbsp;"You are the hero丶"<2734339436@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] 编译时 Cannot find module '../../vue-cli-plugin-uni/packages/vue-template-compiler' (#1237)





  
我醉了 更新以后项目炸了，'@dcloudio/vue-cli-plugin-uni/packages/@vue/component-compiler-utils'，解决方案哪个有，给一个吧，跪求
  
请问你找到解决方案了吗，这边也遇到这个问题了。(((φ(◎ロ◎;)φ)))

**Comment by Nicolana** [comment]
我也遇到了这个问题，然后我切换源为npm官方源就好了。 之前是taobao的

**Comment by Wxh16144** [comment]
> @AK47-dadada 请问你找到解决方案了吗，这边也遇到这个问题了。(((φ(◎ロ◎;)φ)))

我后面找到问题了，在安装依赖之后，发现 `node_modules\@dcloudio\vue-cli-plugin-uni\packages\@vue\component-compiler-utils/` 目录下缺少 `package.json` 文件

所以我的解决方案是添加一个 `package.json` 文件
```json
{
  "main": "./dist"
}

```

**Comment by AK47-dadada** [comment]
是他们的开发人员帮忙解决的 很久了 我都忘了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dcloudio/uni-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月22日(星期四) 下午3:53
***@***.***&gt;;
抄送:&nbsp;"You are the ***@***.******@***.***&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] 编译时 Cannot find module '../../vue-cli-plugin-uni/packages/vue-template-compiler' (#1237)





  
@AK47-dadada 请问你找到解决方案了吗，这边也遇到这个问题了。(((φ(◎ロ◎;)φ)))
  
我后面找到问题了，在安装依赖之后，发现 ***@***.******@***.***\component-compiler-utils/ 目录下缺少 package.json 文件
 
所以我的解决方案是添加一个 package.json 文件
 {   "main": "./dist" }

**Comment by lss-33** [comment]
请问大家有遇到我这个问题嘛～项目跑不起来，不清楚为啥～

> cross-env NODE_ENV=development UNI_PLATFORM=h5 vue-cli-service uni-serve

请注意运行模式下，因日志输出、sourcemap以及未压缩源码等原因，性能和包体积，均不及发行模式。
 INFO  Starting development server...
 ERROR  Error: No matching use for foo.js
Error: No matching use for foo.js
    at updateJsLoader (/Users/lishanshan/Documents/selfContent/my-project/node_modules/@dcloudio/vue-cli-plugin-uni/lib/configure-webpack.js:58:13)
    at /Users/lishanshan/Documents/selfContent/my-project/node_modules/@dcloudio/vue-cli-plugin-uni/lib/configure-webpack.js:162:5
    at /Users/lishanshan/Documents/selfContent/my-project/node_modules/@vue/cli-service/lib/Service.js:251:21
    at Array.forEach (<anonymous>)
    at Service.resolveWebpackConfig (/Users/lishanshan/Documents/selfContent/my-project/node_modules/@vue/cli-service/lib/Service.js:248:30)
    at PluginAPI.resolveWebpackConfig (/Users/lishanshan/Documents/selfContent/my-project/node_modules/@vue/cli-service/lib/PluginAPI.js:132:25)
    at serve (/Users/lishanshan/Documents/selfContent/my-project/node_modules/@dcloudio/vue-cli-plugin-uni/commands/serve.js:47:31)
    at Service.run (/Users/lishanshan/Documents/selfContent/my-project/node_modules/@vue/cli-service/lib/Service.js:230:12)
    at Object.<anonymous> (/Users/lishanshan/Documents/selfContent/my-project/node_modules/@vue/cli-service/bin/vue-cli-service.js:36:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
