### ISSUE TITLE
折叠的代码块会被自动展开

### ISSUE THREAD

**Issue by sunrui1996** [dcloudio/uni-app#1239]
**问题描述**
未折叠的代码进行修改时，有概率会自动将未修改部分的折叠代码块自动展开；
template标签内有多层嵌套结构时，展开最外层代码块时内部已折叠的代码块会全部展开

**复现步骤**
1. 写一串多层标签嵌套的html代码
2. 由内之外依次折叠代码块
3. 展开最外层代码块
4. 内层代码块被全部展开

**预期结果**
如果折叠的代码块内部还有折叠代码块的话，展开最外层代码块时，内层折叠代码块不应该一起被展开

**实际结果**
折叠的代码块内部还有折叠代码块的话，展开最外层代码块时，内层折叠代码块会一起被展开

**Comment by wandali2019** [comment]
内部已修复，请静待下次发版

**Comment by dcloudhdx** [comment]
HBuilderX 2.5.3+ 已修复
