### ISSUE TITLE
H5环境下 iphone 自带输入法在input输入中文时 input框输入的时失去焦点

### ISSUE THREAD

**Issue by fncong** [dcloudio/uni-app#124]
官方线上的案例是正常的，但是HBuilder X创建出来的hello uni-app 案例，编译后访问就出现这种情况。无任何报错提示。测试多款iphone机子都出现类似问题，如果iphone使用如搜狗输入法则没有出现这种情况

微信浏览器 UC浏览器  都出现这样的问题

**Comment by zhetengbiji** [comment]
测试未发现该问题，问题发到社区，附上demo。

**Comment by Gallery2000** [comment]
只要使用了v-model百分比复现！用ip10-13然后切换到拼音，快速输入选中
`
<template>
<input v-model="value" style="width: 100%; border: 1px solid #000" type="text" />
</template>

<script lang="ts" setup>
const value = ref('')`
</script>

**Comment by Gallery2000** [comment]
是unibest的问题，我再uniapp模板中创建的vue3就没有这个问题，这个问题的复现条件是iPhone12，13使用拼音快速输入选中
`
<template>
  <view
    :style="{ marginTop: safeAreaInsets?.top + 'px' }"
    class="bg-white overflow-hidden pt-2 px-4"
  >
    <input v-model="value" style="width: 100%; border: 1px solid #000" type="text" />
  </view>
</template>

<script lang="ts" setup>
const value = ref('')
</script>

`
