### ISSUE TITLE
uni.downloadFile按照官方示例无法触发onProgressUpdate

### ISSUE THREAD

**Issue by 295431414** [dcloudio/uni-app#1242]
**问题描述**
创建下载任务，无法触发onProgressUpdate
**复现步骤**
按照官网示例
const downloadTask = uni.downloadFile({
    url: 'http://www.example.com/file/test', //仅为示例，并非真实的资源
    success: (res) => {
        if (res.statusCode === 200) {
            console.log('下载成功');
        }
    }
});

downloadTask.onProgressUpdate((res) => {
    console.log('下载进度' + res.progress);
    console.log('已经下载的数据长度' + res.totalBytesWritten);
    console.log('预期需要下载的数据总长度' + res.totalBytesExpectedToWrite);

    // 测试条件，取消下载任务。
    if (res.progress > 50) {
        downloadTask.abort();
    }
});
**预期结果**
无法触发onProgressUpdate，但是可以触发success

**Comment by 295431414** [comment]
> **问题描述**
> 创建下载任务，无法触发onProgressUpdate
> **复现步骤**
> 按照官网示例
> const downloadTask = uni.downloadFile({
> url: 'http://www.example.com/file/test', //仅为示例，并非真实的资源
> success: (res) => {
> if (res.statusCode === 200) {
> console.log('下载成功');
> }
> }
> });
> 
> downloadTask.onProgressUpdate((res) => {
> console.log('下载进度' + res.progress);
> console.log('已经下载的数据长度' + res.totalBytesWritten);
> console.log('预期需要下载的数据总长度' + res.totalBytesExpectedToWrite);
> 
> ```
> // 测试条件，取消下载任务。
> if (res.progress > 50) {
>     downloadTask.abort();
> }
> ```
> 
> });
> **预期结果**
> 无法触发onProgressUpdate，但是可以触发success

**Comment by zhetengbiji** [comment]
哪端？

**Comment by 295431414** [comment]
> 哪端？

APP端

**Comment by 295431414** [comment]
![image](https://user-images.githubusercontent.com/24306884/72236465-f6222c00-3611-11ea-83d4-00aa2dc0685d.png)
H5端触发反馈，progress为未知类型

**Comment by StrivingRabbit** [comment]
实测可以触发，现在情况如何了？
