### ISSUE TITLE
uniapp写的小程序怎么把图片直接分享到朋友圈

### ISSUE THREAD

**Issue by littleBelle** [dcloudio/uni-app#1243]
**问题描述**
用uniapp写的小程序，生成的海报图片，希望可以一键分享到到朋友圈
**复现步骤**
无

[或者可以直接贴源代码]

**预期结果**

**实际结果**

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]

**Comment by Wangyaqi** [comment]
哪家的小程序可以直接分享朋友圈的

**Comment by littleBelle** [comment]
> 哪家的小程序可以直接分享朋友圈的

是小程序里面  生成的海报图片，转发到朋友圈

**Comment by Wangyaqi** [comment]
小程序没有分享到朋友圈的功能，只能引导用户手动去分享

**Comment by littleBelle** [comment]
> 小程序没有分享到朋友圈的功能，只能引导用户手动去分享

了解了，谢谢

**Comment by lkc-10** [comment]
所以小程序是不能直接分享海报到朋友圈对吧？
