### ISSUE TITLE
引入数字输入框时出错

### ISSUE THREAD

**Issue by littleBelle** [dcloudio/uni-app#1244]
**问题描述**
需要使用数字输入框组件，但是按照文档引入报错

**复现步骤**
此处引入
![image](https://user-images.githubusercontent.com/53242999/71963536-cb615d80-3236-11ea-9617-1f4d6413e5c7.png)

出现报错如下
![image](https://user-images.githubusercontent.com/53242999/71963576-e2a04b00-3236-11ea-8e3b-10367b1319f8.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
按照文档的方式引入的，但是会报错，请大神指示什么原因，多谢

**Comment by Wangyaqi** [comment]
uni-number-box

**Comment by littleBelle** [comment]
> uni-number-box

![image](https://user-images.githubusercontent.com/53242999/71964902-94407b80-3239-11ea-95a2-fb7d9d4c0371.png)
![image](https://user-images.githubusercontent.com/53242999/71964917-9acef300-3239-11ea-80db-7813c01a9592.png)
我之前有这么改过，也是会报错

**Comment by littleBelle** [comment]
> uni-number-box，文档有误，已修改
我之前有这么改过，也是会报错
![image](https://user-images.githubusercontent.com/53242999/72119697-3bcfc200-3390-11ea-8207-ef3af688d852.png)
![image](https://user-images.githubusercontent.com/53242999/72119712-44c09380-3390-11ea-95a0-99d4dec094a9.png)
