### ISSUE TITLE
上传图片的时候在手机上打开为什么会有摄像机和录音，这个要怎么设置呀？谢谢

### ISSUE THREAD

**Issue by renxiao1218** [dcloudio/uni-app#1246]

**Comment by zhetengbiji** [comment]
哪端？

**Comment by renxiao1218** [comment]
h5 在微信中打开没有，支付宝中打开有的，录完页面上是空白的


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"折腾笔记"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月11日(星期六) 下午4:25
收件人:&nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&gt;;
抄送:&nbsp;"那一抹&amp;阳光"<1967609349@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] 上传图片的时候在手机上打开为什么会有摄像机和录音，这个要怎么设置呀？谢谢 (#1246)




哪端？

**Comment by zhetengbiji** [comment]
> h5 在微信中打开没有，支付宝中打开有的，录完页面上是空白的
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"折腾笔记"<notifications@github.com&gt;; 发送时间:&nbsp;2020年1月11日(星期六) 下午4:25 收件人:&nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 抄送:&nbsp;"那一抹&amp;阳光"<1967609349@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [dcloudio/uni-app] 上传图片的时候在手机上打开为什么会有摄像机和录音，这个要怎么设置呀？谢谢 (#1246) 哪端？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

试试普通H5在支付宝是否这样，应该是支付宝内置浏览器的问题

**Comment by renxiao1218** [comment]
应该是的&nbsp; 我试了demo&nbsp; 也是一样的&nbsp;&nbsp;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"折腾笔记"<notifications@github.com&gt;;
发送时间:&nbsp;2020年1月11日(星期六) 下午4:30
收件人:&nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&gt;;
抄送:&nbsp;"那一抹&amp;阳光"<1967609349@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] 上传图片的时候在手机上打开为什么会有摄像机和录音，这个要怎么设置呀？谢谢 (#1246)



 
h5 在微信中打开没有，支付宝中打开有的，录完页面上是空白的
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"折腾笔记"<notifications@github.com&gt;; 发送时间:&nbsp;2020年1月11日(星期六) 下午4:25 收件人:&nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 抄送:&nbsp;"那一抹&amp;阳光"<1967609349@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [dcloudio/uni-app] 上传图片的时候在手机上打开为什么会有摄像机和录音，这个要怎么设置呀？谢谢 (#1246) 哪端？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
试试普通H5在支付宝是否这样，应该是支付宝内置浏览器的问题

**Comment by zhetengbiji** [comment]
> 应该是的&nbsp; 我试了demo&nbsp; 也是一样的&nbsp;&nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"折腾笔记"<notifications@github.com&gt;; 发送时间:&nbsp;2020年1月11日(星期六) 下午4:30 收件人:&nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 抄送:&nbsp;"那一抹&amp;阳光"<1967609349@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [dcloudio/uni-app] 上传图片的时候在手机上打开为什么会有摄像机和录音，这个要怎么设置呀？谢谢 (#1246) h5 在微信中打开没有，支付宝中打开有的，录完页面上是空白的 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"折腾笔记"<notifications@github.com&gt;; 发送时间:&nbsp;2020年1月11日(星期六) 下午4:25 收件人:&nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 抄送:&nbsp;"那一抹&amp;阳光"<1967609349@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [dcloudio/uni-app] 上传图片的时候在手机上打开为什么会有摄像机和录音，这个要怎么设置呀？谢谢 (#1246) 哪端？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 试试普通H5在支付宝是否这样，应该是支付宝内置浏览器的问题 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

哦，那应该和框架无关，如果认为支付宝内置浏览器的行为不妥，可以反馈给支付宝开发团队
