### ISSUE TITLE
VM74:1 未找到 app.json 中的定义的 pages "pages/login/login" 对应的 WXML 文件

### ISSUE THREAD

**Issue by ppaa-H** [dcloudio/uni-app#1248]
隔了一天用HBuilderX重新编译之后，在微信小程序开发工具中运行，就出现了这个错误

**Comment by dcloudhdx** [comment]
重新编译是否正常，请提供一个简单工程

**Comment by ppaa-H** [comment]
代码都是用的HBuilderX登录模板还有Hello uni-app，只是在这基础上去改东西，改的话也只是改Vue文件，其他的配置文件都没改，甚至js都没改，然后不知怎么的就不能找到wxml。
重新编译了，HBuilderX和微信开发工具关了重新打开都没用。
会不会我改到vue文件影响到它生成wxml？其他没改的vue都可以生成
