### ISSUE TITLE
vm.$slots 什么时候有比较正式的支持

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#1250]
现在需要在父组件里面获取到动态数量的所有子组件，而且可能随时刷新数据。

显然我如果只是通过created将子组件push进入父组件的某个值里面不合适。动态的数据会导致数据更换时新的条数会继续created，然后父组件里面保持的变量里面存在的子组件个数就无法和真正视图上渲染的个数一致。

这种我就想通过 vm.$slots 来获取子组件，然后更改子组件的某些属性。

现在小程序端无法实现，输出为true。

测试发现app和h5没有问题。我是nvue页面。

没有开启v3.

什么时候会有一个比较好的支持。

现在我就想做一个 类似于 select/option 这样的单/多选。

选择项是动态的数据，随时可能会刷新。

我不太想每一次都写一堆重复的代码，所以想封装一个壳子。

**Comment by E2875888382** [comment]
mark

**Comment by wakaryry** [comment]
还以为官方给我答案了。白惊喜

**Comment by hotbinz** [comment]
我也插个眼

**Comment by SimonPower** [comment]
原来是uniapp问题，在写vue3，原来vue2就没支持，求支持！！！写组件很常用啊！

**Comment by zhetengbiji** [comment]
在小程序端是转为小程序原生组件，目前的方案未支持。

1. 获取不到 $slots，是因为没有 vnode（处于性能考虑）。
2. 即使有 vnode，由于小程序原生组件的限制，也不能在运行时动态转换成对应的组件插入，vnode 能利用到的信息有限。

**Comment by twtylkmrh** [comment]
> 还以为官方给我答案了。白惊喜
目前你有什么好的兼容方式吗？
