### ISSUE TITLE
uniapp开发时键盘mode正常, 打包之后键盘mode不生效

### ISSUE THREAD

**Issue by liaohui5** [dcloudio/uni-app#1254]
**问题描述**
因为需求原因, 需要些一个要写一个功能类似QQ发布说说的页面, 手机QQ发布说说在键盘的上方有一个跟随键盘的显示和隐藏的功能菜单, 在开发模式下, 这两个Api功能正常
http://www.html5plus.org/doc/zh_cn/key.html#plus.key.hideSoftKeybord
http://www.html5plus.org/doc/zh_cn/key.html#plus.key.showSoftKeybord
我在manifest 和 pages.json 中也都配置了mode 为 adjustPan 参考[]这个](
https://uniapp.dcloud.io/component/input?id=%e5%85%b3%e4%ba%8e%e8%bd%af%e9%94%ae%e7%9b%98%e5%bc%b9%e5%87%ba%e7%9a%84%e9%80%bb%e8%be%91%e8%af%b4%e6%98%8e) 配置的

**复现步骤**
[复现问题的步骤]
1.  用一个按钮监听click事件, 然后 显示键盘,并且显示功能条
2.  用另外一个按钮监听click事件, 然后 隐藏键盘,并且隐藏 功能菜单
3. 打包前没有问题, 打包键盘会遮挡住 功能菜单

**预期结果**
希望官方早点修复这个bug
![image](https://user-images.githubusercontent.com/29266093/72073439-da293c80-332a-11ea-9cf9-a8a6fe774607.png)

**实际结果**
打包之后跟随键盘不生效

**系统信息:**
 - 发行平台: Android
 - 操作系统: Android 7.1,2,  Android 10
 - HBuilderX版本: 2.5.1 20200103
 - uni-app版本: 2.5
 - 设备信息 小米8

**Comment by zhetengbiji** [comment]
manifest.json 内是否有键盘相关配置？

**Comment by liaohui5** [comment]
有, manifest.json 和 pages.json 还有每一个页面的style属性的 app-plus 都有设置, 就是不生效




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "折腾笔记"<notifications@github.com&gt;; 
发送时间: 2020年1月11日(星期六) 下午4:29
收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 
抄送: "廖辉"<1182468610@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dcloudio/uni-app] uniapp开发时键盘mode正常, 打包之后键盘mode不生效 (#1254)




manifest.json 内是否有键盘相关配置？

**Comment by zhetengbiji** [comment]
> 有, manifest.json 和 pages.json 还有每一个页面的style属性的 app-plus 都有设置, 就是不生效
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "折腾笔记"<notifications@github.com&gt;; 发送时间: 2020年1月11日(星期六) 下午4:29 收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 抄送: "廖辉"<1182468610@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [dcloudio/uni-app] uniapp开发时键盘mode正常, 打包之后键盘mode不生效 (#1254) manifest.json 内是否有键盘相关配置？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

仅在pages.json设置，去掉manifest.json冲突设置

**Comment by liaohui5** [comment]
那我应该在 globalStyle 中设置, 还是在每一个页面的 app-plus 中设置呢?



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "折腾笔记"<notifications@github.com&gt;; 
发送时间: 2020年1月11日(星期六) 下午4:32
收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 
抄送: "廖辉"<1182468610@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dcloudio/uni-app] uniapp开发时键盘mode正常, 打包之后键盘mode不生效 (#1254)



 
有, manifest.json 和 pages.json 还有每一个页面的style属性的 app-plus 都有设置, 就是不生效
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "折腾笔记"<notifications@github.com&gt;; 发送时间: 2020年1月11日(星期六) 下午4:29 收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 抄送: "廖辉"<1182468610@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [dcloudio/uni-app] uniapp开发时键盘mode正常, 打包之后键盘mode不生效 (#1254) manifest.json 内是否有键盘相关配置？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
仅在pages.json设置，去掉manifest.json冲突设置

**Comment by zhetengbiji** [comment]
> 那我应该在 globalStyle 中设置, 还是在每一个页面的 app-plus 中设置呢?
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "折腾笔记"<notifications@github.com&gt;; 发送时间: 2020年1月11日(星期六) 下午4:32 收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 抄送: "廖辉"<1182468610@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [dcloudio/uni-app] uniapp开发时键盘mode正常, 打包之后键盘mode不生效 (#1254) 有, manifest.json 和 pages.json 还有每一个页面的style属性的 app-plus 都有设置, 就是不生效 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "折腾笔记"<notifications@github.com&gt;; 发送时间: 2020年1月11日(星期六) 下午4:29 收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 抄送: "廖辉"<1182468610@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [dcloudio/uni-app] uniapp开发时键盘mode正常, 打包之后键盘mode不生效 (#1254) manifest.json 内是否有键盘相关配置？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 仅在pages.json设置，去掉manifest.json冲突设置 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

均可

**Comment by liaohui5** [comment]
好的, 谢谢, 那我先试试



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "折腾笔记"<notifications@github.com&gt;; 
发送时间: 2020年1月11日(星期六) 下午4:35
收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 
抄送: "廖辉"<1182468610@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dcloudio/uni-app] uniapp开发时键盘mode正常, 打包之后键盘mode不生效 (#1254)



 
那我应该在 globalStyle 中设置, 还是在每一个页面的 app-plus 中设置呢?
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "折腾笔记"<notifications@github.com&gt;; 发送时间: 2020年1月11日(星期六) 下午4:32 收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 抄送: "廖辉"<1182468610@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [dcloudio/uni-app] uniapp开发时键盘mode正常, 打包之后键盘mode不生效 (#1254) 有, manifest.json 和 pages.json 还有每一个页面的style属性的 app-plus 都有设置, 就是不生效 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "折腾笔记"<notifications@github.com&gt;; 发送时间: 2020年1月11日(星期六) 下午4:29 收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 抄送: "廖辉"<1182468610@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 主题: Re: [dcloudio/uni-app] uniapp开发时键盘mode正常, 打包之后键盘mode不生效 (#1254) manifest.json 内是否有键盘相关配置？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 仅在pages.json设置，去掉manifest.json冲突设置 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
均可
