### ISSUE TITLE
在非微信端小程序全局组件注册问题

### ISSUE THREAD

**Issue by 2460392754** [dcloudio/uni-app#1256]
**问题描述**
直接使用 hbuilderx 工具启动非微信端小程序项目会造成在页面中使用main.js中注册的全局组件加载失败的问题。
但是修改代码或文字让小程序代码热重载，就会在页面组件中的`xxx.json`的`usingComponents`里显示原本使用到的全局组件

**系统信息:**
 - 发行平台: 字节小程序、支付宝小程序
 - HBuilderX版本 HBuilderX2.5.1.20200103

**Comment by dcloudhdx** [comment]
请提供测试工程

**Comment by xiaokar** [comment]
和我同个问题 #2463 ，我用了colorui全局组件，热加载后才能正常使用，导致现在每个页面需要手动更改并热加载，发线上也是使用开发版本去发

**Comment by StrivingRabbit** [comment]
使用`2.0.0-31920210514002`测试，执行`build:mp-toutiao`app.json第一次编译也是正常的，usingComponents内也不是空。可以提供一个示例吗？

**Comment by xiaokar** [comment]
> 使用`2.0.0-31920210514002`测试，执行`build:mp-toutiao`app.json第一次编译也是正常的，usingComponents内也不是空。可以提供一个示例吗？

你们五六月份开发工具修好了，感谢

**Comment by zhetengbiji** [comment]
> > 使用`2.0.0-31920210514002`测试，执行`build:mp-toutiao`app.json第一次编译也是正常的，usingComponents内也不是空。可以提供一个示例吗？
> 
> 你们五六月份开发工具修好了，感谢

好的，此问题暂时关闭，如再出现，可以继续反馈
