### ISSUE TITLE
请问nvue web-view组件支持本地html吗？

### ISSUE THREAD

**Issue by Liu-Peter** [dcloudio/uni-app#1263]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
请问nvue web-view组件支持本地html吗？按照官方的例子在nvue使用打开是白屏，是不是不支持nvue啊

**Comment by dcloudhdx** [comment]
Android 支持，iOS目前有Bug

**Comment by Liu-Peter** [comment]
好的

**Comment by wuwenyuan111** [comment]
我们使用的本地Html，iOS和安卓都正常。
