### ISSUE TITLE
2.5.1 app端，input组件password与type = 'number' 一起用，type无效

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-app#1264]
2.5.1 app端，input组件password与type = 'number' 一起用，type无效。
nvue页面和vue页面都有这个问题
测试机iphone X

不是说HBuilder 2.1.3就修复了吗 ？ https://github.com/dcloudio/uni-app/issues/556

**Comment by wakaryry** [comment]
是有这个问题。我这边似乎也是。

**Comment by zhetengbiji** [comment]
> 是有这个问题。我这边似乎也是。

你是vue还是nvue？

**Comment by zhetengbiji** [comment]
> 2.5.1 app端，input组件password与type = 'number' 一起用，type无效。
> nvue页面和vue页面都有这个问题
> 测试机iphone X
> 
> 不是说HBuilder 2.1.3就修复了吗 ？ #556

是否启用v3模式？

**Comment by huanghaodong** [comment]
> > 2.5.1 app端，input组件password与type = 'number' 一起用，type无效。
> > nvue页面和vue页面都有这个问题
> > 测试机iphone X
> > 不是说HBuilder 2.1.3就修复了吗 ？ #556
> 
> 是否启用v3模式？

未启动

**Comment by zhetengbiji** [comment]
> > > 2.5.1 app端，input组件password与type = 'number' 一起用，type无效。
> > > nvue页面和vue页面都有这个问题
> > > 测试机iphone X
> > > 不是说HBuilder 2.1.3就修复了吗 ？ #556
> > 
> > 
> > 是否启用v3模式？
> 
> 未启动

问题复现概率如何？

**Comment by huanghaodong** [comment]
100%

> > > > 2.5.1 app端，input组件password与type = 'number' 一起用，type无效。
> > > > nvue页面和vue页面都有这个问题
> > > > 测试机iphone X
> > > > 不是说HBuilder 2.1.3就修复了吗 ？ #556
> > > 
> > > 
> > > 是否启用v3模式？
> > 
> > 
> > 未启动
> 
> 问题复现概率如何？



> > > > 2.5.1 app端，input组件password与type = 'number' 一起用，type无效。
> > > > nvue页面和vue页面都有这个问题
> > > > 测试机iphone X
> > > > 不是说HBuilder 2.1.3就修复了吗 ？ #556
> > > 
> > > 
> > > 是否启用v3模式？
> > 
> > 
> > 未启动
> 
> 问题复现概率如何？

100%

**Comment by huanghaodong** [comment]
> > > > 2.5.1 app端，input组件password与type = 'number' 一起用，type无效。
> > > > nvue页面和vue页面都有这个问题
> > > > 测试机iphone X
> > > > 不是说HBuilder 2.1.3就修复了吗 ？ #556
> > > 
> > > 
> > > 是否启用v3模式？
> > 
> > 
> > 未启动
> 
> 问题复现概率如何？

100%

**Comment by zhetengbiji** [comment]
> > > > > 2.5.1 app端，input组件password与type = 'number' 一起用，type无效。
> > > > > nvue页面和vue页面都有这个问题
> > > > > 测试机iphone X
> > > > > 不是说HBuilder 2.1.3就修复了吗 ？ #556
> > > > 
> > > > 
> > > > 是否启用v3模式？
> > > 
> > > 
> > > 未启动
> > 
> > 
> > 问题复现概率如何？
> 
> 100%

其他iOS机型能复现吗？
能否提供一个示例工程？

**Comment by huanghaodong** [comment]
> > > > > > 2.5.1 app端，input组件password与type = 'number' 一起用，type无效。
> > > > > > nvue页面和vue页面都有这个问题
> > > > > > 测试机iphone X
> > > > > > 不是说HBuilder 2.1.3就修复了吗 ？ #556
> > > > > 
> > > > > 
> > > > > 是否启用v3模式？
> > > > 
> > > > 
> > > > 未启动
> > > 
> > > 
> > > 问题复现概率如何？
> > 
> > 
> > 100%
> 
> 我这没有iPhoneX，使用其他机型测试未复现
> 其他iOS机型能复现吗？
> 能否提供一个示例工程？

你给我个联系方式，我发工程给你

**Comment by zhetengbiji** [comment]
> > > > > > > 2.5.1 app端，input组件password与type = 'number' 一起用，type无效。
> > > > > > > nvue页面和vue页面都有这个问题
> > > > > > > 测试机iphone X
> > > > > > > 不是说HBuilder 2.1.3就修复了吗 ？ #556
> > > > > > 
> > > > > > 
> > > > > > 是否启用v3模式？
> > > > > 
> > > > > 
> > > > > 未启动
> > > > 
> > > > 
> > > > 问题复现概率如何？
> > > 
> > > 
> > > 100%
> > 
> > 
> > 我这没有iPhoneX，使用其他机型测试未复现
> > 其他iOS机型能复现吗？
> > 能否提供一个示例工程？
> 
> 你给我个联系方式，我发工程给你

service02@dcloud.io

**Comment by huanghaodong** [comment]
> service02@dcloud.io

我只有iphoneX还有iphone7均出现

**Comment by zhetengbiji** [comment]
https://uniapp.dcloud.net.cn/component/input.html#inputmode
