### ISSUE TITLE
cli创建的项目npm update之后app不能正常显示

### ISSUE THREAD

**Issue by Tron1234** [dcloudio/uni-app#1268]
**问题描述**
[问题描述：为可以使用路径别名我用cli创建的项目，昨天npm update之后小程序和h5显示都正常，app上出现了问题

**复现步骤**
[复现问题的步骤]
更新npm update

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
希望回到以前路径别名可以正常使用的状态

**实际结果**
[这里请贴上你的报错截图或文字]
启用v3编译
http://flyyn2.top/D9361BE1DB94205E7CBB4FF467CB74E7.png
未启用v3编译
http://flyyn2.top/EE9AB25682941A48149045D21816CC80.png
正常情况 npm update之前 小程序、h5、app    更新之后小程序、h5正常、app异常
http://flyyn2.top/QQ截图20200113125147.png

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]   微信小程序、H5平台、5+ App
 - 操作系统 [如 iOS 12.1.2、Android 7.0]   ios 13.3   android 9.0
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]  2.5.5.20200111-alpha
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]  

uni-app v2.5.5
uni-app cli v2.0.0-alpha-25520200111001

Environment Info:

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 8.9.3 - D:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.4 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @dcloudio/uni-app-plus: ^2.0.0-alpha-25520200111001 => 2.0.0-alpha-25520200111001
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: ^2.0.0-alpha-25520200111001 => 2.0.0-alpha-25520200111001
    @dcloudio/uni-h5: ^2.0.0-alpha-25520200111001 => 2.0.0-alpha-25520200111001
    @dcloudio/uni-helper-json: ^1.0.5 => 1.0.5
    @dcloudio/uni-migration: ^3.0.0-alpha-24320191125019 => 3.0.0-alpha-24320191125019
    @dcloudio/uni-mp-alipay: ^2.0.0-alpha-25520200111001 => 2.0.0-alpha-25520200111001
    @dcloudio/uni-mp-baidu: ^2.0.0-alpha-25520200111001 => 2.0.0-alpha-25520200111001
    @dcloudio/uni-mp-qq: ^2.0.0-alpha-25520200111001 => 2.0.0-alpha-25520200111001
    @dcloudio/uni-mp-toutiao: ^2.0.0-alpha-25520200111001 => 2.0.0-alpha-25520200111001
    @dcloudio/uni-mp-weixin: ^2.0.0-alpha-25520200111001 => 2.0.0-alpha-25520200111001
    @dcloudio/uni-stat: ^2.0.0-v3-24020191018001 => 2.0.0-v3-24020191018001
    @dcloudio/uni-template-compiler: ^2.0.0-alpha-25520200111001 => 2.0.0-alpha-25520200111001
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-alpha-25520200111001 => 2.0.0-alpha-25520200111001
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-alpha-25520200111001 => 2.0.0-alpha-25520200111001
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-alpha-25520200111001 => 2.0.0-alpha-25520200111001
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-alpha-25520200111001 => 2.0.0-alpha-25520200111001
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-alpha-25520200111001 => 2.0.0-alpha-25520200111001
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  3.12.1
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.1.2
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-plugin-router:  4.1.2
    @vue/cli-plugin-vuex:  4.1.2
    @vue/cli-service: ^4.1.2 => 4.1.2
    @vue/cli-shared-utils:  3.12.1
    @vue/component-compiler-utils:  3.1.1 (3.1.1)
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.11
    vue-hot-reload-api:  2.3.4
    vue-i18n: ^8.15.3 => 8.15.3
    vue-loader:  15.8.3
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.2
  npmGlobalPackages:
    @vue/cli: Not Found

 - 设备信息 [如 iPhone8 Plus]
iphone8   samsung note4

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
编译器的问题无法编译vue.config.js文件了

**Comment by Wangyaqi** [comment]
可以提供一下精简之后的项目我们验证一下

**Comment by zlab** [comment]
用HBuilderX吧，打开src目录，不要打开根目录

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
