### ISSUE TITLE
调用组件，css在h5端显示异常 

### ISSUE THREAD

**Issue by jahnli** [dcloudio/uni-app#127]
![qq 20181223023225](https://user-images.githubusercontent.com/20943608/50377602-4622ff00-065b-11e9-84ba-09f7dccb0edc.png)
![qq 20181223023326](https://user-images.githubusercontent.com/20943608/50377603-46bb9580-065b-11e9-8039-b038400e00f5.png)
![qq 20181223023410](https://user-images.githubusercontent.com/20943608/50377604-46bb9580-065b-11e9-8f61-577ea5978869.png)

 你好 我用的uni-tab-bar 我在我引用的组件里 设置class (uni-navbar-header) 的样式 在h5不生效 但是app和小程序是ok的

**Comment by xiaoyucoding** [comment]
H5 平台的样式都是 scoped 模式，如果需要修改组件的样式，有两种方式。
1、直接在组件的代码里面调整
2、如果不修改组件的代码的话，相关的样式需要写在  App.vue 里面。

后续会进行优化，提供更加便捷的方案。

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
