### ISSUE TITLE
2.5.5,更新之后input组件失效，真给跪了。

### ISSUE THREAD

**Issue by cruelwolfking** [dcloudio/uni-app#1271]
**问题描述**
2.5.5，input表单不显示

修复了一个bug，又留下新bug，bug复bug，bug无穷多，用uniapp就是在不断的踩坑，烦不胜烦，下个项目放弃。

**Comment by zhetengbiji** [comment]
哪端？

**Comment by cruelwolfking** [comment]
ios

**Comment by zhetengbiji** [comment]
> ios

nvue还是vue？是否使用了v3编译模式？

**Comment by cruelwolfking** [comment]
nvue vue 混合模式，没用v3，2.5.4正常，2.5.5就不显示了

**Comment by cruelwolfking** [comment]
<view class="main">
				
				<w-input
					v-model="phoneData"
					type="text"
					maxlength="11"
					placeholder="用户名/电话"
				></w-input>
				<wInput
					v-model="passData"
					type="password"
					maxlength="11"
					placeholder="密码"
				></wInput>
			</view>
			<wButton 
				text="登 录"
				:rotate="isRotate" 
				@click.native="startLogin()"
			></wButton>

**Comment by cruelwolfking** [comment]
wInput是封装的组件，
<input 
			class="main-input" 
			:value="value" 
			:type="_type" 
			:maxlength="maxlength" 
			:placeholder="placeholder" 
			:password="type==='password'&&!showPassword" 
			@input="onInput"
		/>

**Comment by cruelwolfking** [comment]
还有input标签，在ios可以自动换行，在安卓无法自动换行，nvue下

**Comment by cruelwolfking** [comment]
还有一个bug，安卓录音有问题，不能播放，ios可以

**Comment by cruelwolfking** [comment]
然后还有一个就是list 的refresh 组件，也有问题，安卓下 <loading-indicator></loading-indicator>这个是没有效果的，ios可以

**Comment by cruelwolfking** [comment]
然后还有一个就是ios 获取定位的问题，安卓获取当前点击的x,y坐标是正常的，但是在ios，就会错误，好像只有页面第一次打开的时候获取到的X，y坐标正常，后面再获取就是错误的

**Comment by cruelwolfking** [comment]
> > ios
> 
> nvue还是vue？是否使用了v3编译模式？

麻烦可以的话，这些问题都看下。。。。。

**Comment by cruelwolfking** [comment]
nvue模式，web-view组件不能用，vue可以，这个是不是bug，我看文档显示支持app，但是实际上是不支持

**Comment by cruelwolfking** [comment]
> 然后还有一个就是list 的refresh 组件，也有问题，安卓下 这个是没有效果的，ios可以

<loading-indicator></loading-indicator> 这个组件不生效

**Comment by zhetengbiji** [comment]
> > > ios
> > 
> > 
> > nvue还是vue？是否使用了v3编译模式？
> 
> 麻烦可以的话，这些问题都看下。。。。。

为避免混乱，你可以把不同的问题单独提出

**Comment by zhetengbiji** [comment]
> nvue模式，web-view组件不能用，vue可以，这个是不是bug，我看文档显示支持app，但是实际上是不支持

可以用

**Comment by zhetengbiji** [comment]
> 然后还有一个就是ios 获取定位的问题，安卓获取当前点击的x,y坐标是正常的，但是在ios，就会错误，好像只有页面第一次打开的时候获取到的X，y坐标正常，后面再获取就是错误的

是什么时候发现的？近期版本吗？

**Comment by cruelwolfking** [comment]
> > 然后还有一个就是ios 获取定位的问题，安卓获取当前点击的x,y坐标是正常的，但是在ios，就会错误，好像只有页面第一次打开的时候获取到的X，y坐标正常，后面再获取就是错误的
> 
> 是什么时候发现的？近期版本吗？

这个2.5.1都有了，我也一直没管，不过一直存在

**Comment by cruelwolfking** [comment]
> > nvue模式，web-view组件不能用，vue可以，这个是不是bug，我看文档显示支持app，但是实际上是不支持
> 
> 可以用

不会吧，我测试了很久哦，显示加载完全但是是空白界面，把官网代码复制上去的哦，但是换了vue，直接又可以出来了

**Comment by zhetengbiji** [comment]
> 还有一个bug，安卓录音有问题，不能播放，ios可以

使用mp3格式

**Comment by zhetengbiji** [comment]
> > > nvue模式，web-view组件不能用，vue可以，这个是不是bug，我看文档显示支持app，但是实际上是不支持
> > 
> > 
> > 可以用
> 
> 不会吧，我测试了很久哦，显示加载完全但是是空白界面，把官网代码复制上去的哦，但是换了vue，直接又可以出来了

本地还是网络路径？iOS还是安卓？

**Comment by cruelwolfking** [comment]
> > 还有一个bug，安卓录音有问题，不能播放，ios可以
> 
> 使用mp

> > > > nvue模式，web-view组件不能用，vue可以，这个是不是bug，我看文档显示支持app，但是实际上是不支持
> > > 
> > > 
> > > 可以用
> > 
> > 
> > 不会吧，我测试了很久哦，显示加载完全但是是空白界面，把官网代码复制上去的哦，但是换了vue，直接又可以出来了
> 
> 本地还是网络路径？iOS还是安卓？

我放的百度链接，网络的

**Comment by zhetengbiji** [comment]
> > > 还有一个bug，安卓录音有问题，不能播放，ios可以
> > 
> > 
> > 使用mp
> 
> > > > > nvue模式，web-view组件不能用，vue可以，这个是不是bug，我看文档显示支持app，但是实际上是不支持
> > > > 
> > > > 
> > > > 可以用
> > > 
> > > 
> > > 不会吧，我测试了很久哦，显示加载完全但是是空白界面，把官网代码复制上去的哦，但是换了vue，直接又可以出来了
> > 
> > 
> > 本地还是网络路径？iOS还是安卓？
> 
> 我放的百度链接，网络的

iOS还是安卓不显示？

**Comment by cruelwolfking** [comment]
> > > > 还有一个bug，安卓录音有问题，不能播放，ios可以
> > > 
> > > 
> > > 使用mp
> > 
> > 
> > > > > > nvue模式，web-view组件不能用，vue可以，这个是不是bug，我看文档显示支持app，但是实际上是不支持
> > > > > 
> > > > > 
> > > > > 可以用
> > > > 
> > > > 
> > > > 不会吧，我测试了很久哦，显示加载完全但是是空白界面，把官网代码复制上去的哦，但是换了vue，直接又可以出来了
> > > 
> > > 
> > > 本地还是网络路径？iOS还是安卓？
> > 
> > 
> > 我放的百度链接，网络的
> 
> iOS还是安卓不显示？

ios，安卓好像都是不可以

**Comment by cruelwolfking** [comment]
> > > > > 还有一个bug，安卓录音有问题，不能播放，ios可以
> > > > 
> > > > 
> > > > 使用mp
> > > 
> > > 
> > > > > > > nvue模式，web-view组件不能用，vue可以，这个是不是bug，我看文档显示支持app，但是实际上是不支持
> > > > > > 
> > > > > > 
> > > > > > 可以用
> > > > > 
> > > > > 
> > > > > 不会吧，我测试了很久哦，显示加载完全但是是空白界面，把官网代码复制上去的哦，但是换了vue，直接又可以出来了
> > > > 
> > > > 
> > > > 本地还是网络路径？iOS还是安卓？
> > > 
> > > 
> > > 我放的百度链接，网络的
> > 
> > 
> > iOS还是安卓不显示？
> 
> ios，安卓好像都是不可以

就一样的代码，文件后缀.nvue的是不显示的，.vue是可以出来的

**Comment by zhetengbiji** [comment]
> > > > > 还有一个bug，安卓录音有问题，不能播放，ios可以
> > > > 
> > > > 
> > > > 使用mp
> > > 
> > > 
> > > > > > > nvue模式，web-view组件不能用，vue可以，这个是不是bug，我看文档显示支持app，但是实际上是不支持
> > > > > > 
> > > > > > 
> > > > > > 可以用
> > > > > 
> > > > > 
> > > > > 不会吧，我测试了很久哦，显示加载完全但是是空白界面，把官网代码复制上去的哦，但是换了vue，直接又可以出来了
> > > > 
> > > > 
> > > > 本地还是网络路径？iOS还是安卓？
> > > 
> > > 
> > > 我放的百度链接，网络的
> > 
> > 
> > iOS还是安卓不显示？
> 
> ios，安卓好像都是不可以

nvue页面是weex编译模式还是uni-app编译模式？

**Comment by cruelwolfking** [comment]
> > > > > > 还有一个bug，安卓录音有问题，不能播放，ios可以
> > > > > 
> > > > > 
> > > > > 使用mp
> > > > 
> > > > 
> > > > > > > > nvue模式，web-view组件不能用，vue可以，这个是不是bug，我看文档显示支持app，但是实际上是不支持
> > > > > > > 
> > > > > > > 
> > > > > > > 可以用
> > > > > > 
> > > > > > 
> > > > > > 不会吧，我测试了很久哦，显示加载完全但是是空白界面，把官网代码复制上去的哦，但是换了vue，直接又可以出来了
> > > > > 
> > > > > 
> > > > > 本地还是网络路径？iOS还是安卓？
> > > > 
> > > > 
> > > > 我放的百度链接，网络的
> > > 
> > > 
> > > iOS还是安卓不显示？
> > 
> > 
> > ios，安卓好像都是不可以
> 
> nvue页面是weex编译模式还是uni-app编译模式？

uni-app模式，不是纯原生的，因为很多插件纯原生都没法用。。。只能用混合模式了

**Comment by cruelwolfking** [comment]
> > > > > > > 还有一个bug，安卓录音有问题，不能播放，ios可以
> > > > > > 
> > > > > > 
> > > > > > 使用mp
> > > > > 
> > > > > 
> > > > > > > > > nvue模式，web-view组件不能用，vue可以，这个是不是bug，我看文档显示支持app，但是实际上是不支持
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 可以用
> > > > > > > 
> > > > > > > 
> > > > > > > 不会吧，我测试了很久哦，显示加载完全但是是空白界面，把官网代码复制上去的哦，但是换了vue，直接又可以出来了
> > > > > > 
> > > > > > 
> > > > > > 本地还是网络路径？iOS还是安卓？
> > > > > 
> > > > > 
> > > > > 我放的百度链接，网络的
> > > > 
> > > > 
> > > > iOS还是安卓不显示？
> > > 
> > > 
> > > ios，安卓好像都是不可以
> > 
> > 
> > nvue页面是weex编译模式还是uni-app编译模式？
> 
> uni-app模式，不是纯原生的，因为很多插件纯原生都没法用。。。只能用混合模式了

`/* 5+App特有相关 */
	"app-plus" : 
	{
		//"renderer": "native",
		"nvueCompiler" : "uni-app",
		"usingComponents" : true,
		"splashscreen" : `

**Comment by cruelwolfking** [comment]
> 然后还有一个就是ios 获取定位的问题，安卓获取当前点击的x,y坐标是正常的，但是在ios，就会错误，好像只有页面第一次打开的时候获取到的X，y坐标正常，后面再获取就是错误的



> > 然后还有一个就是ios 获取定位的问题，安卓获取当前点击的x,y坐标是正常的，但是在ios，就会错误，好像只有页面第一次打开的时候获取到的X，y坐标正常，后面再获取就是错误的
> 
> 是什么时候发现的？近期版本吗？

`long(e){
				let x = 0
				let y = 0
				// #ifdef APP-PLUS-NVUE
				if (Array.isArray(e.changedTouches) && e.changedTouches.length > 0) {
					x = e.changedTouches[0].screenX
					y = e.changedTouches[0].screenY
				}
				// #endif
				// #ifdef MP
				x = e.detail.x
				y = e.detail.y
				// #endif
				this.$emit('long',{
					x,
					y,
					index:this.index
				})
			},`

这个是我获取x，y的代码，安卓没问题，ios获取不准确

**Comment by zhetengbiji** [comment]
> nvue vue 混合模式，没用v3，2.5.4正常，2.5.5就不显示了

试一下临时解决方案：启用v3编译模式

**Comment by zhetengbiji** [comment]
> 还有input标签，在ios可以自动换行，在安卓无法自动换行，nvue下



> > > > > > > > 还有一个bug，安卓录音有问题，不能播放，ios可以
> > > > > > > 
> > > > > > > 
> > > > > > > 使用mp
> > > > > > 
> > > > > > 
> > > > > > > > > > nvue模式，web-view组件不能用，vue可以，这个是不是bug，我看文档显示支持app，但是实际上是不支持
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 可以用
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 不会吧，我测试了很久哦，显示加载完全但是是空白界面，把官网代码复制上去的哦，但是换了vue，直接又可以出来了
> > > > > > > 
> > > > > > > 
> > > > > > > 本地还是网络路径？iOS还是安卓？
> > > > > > 
> > > > > > 
> > > > > > 我放的百度链接，网络的
> > > > > 
> > > > > 
> > > > > iOS还是安卓不显示？
> > > > 
> > > > 
> > > > ios，安卓好像都是不可以
> > > 
> > > 
> > > nvue页面是weex编译模式还是uni-app编译模式？
> > 
> > 
> > uni-app模式，不是纯原生的，因为很多插件纯原生都没法用。。。只能用混合模式了
> 
> `/* 5+App特有相关 */ "app-plus" : { //"renderer": "native", "nvueCompiler" : "uni-app", "usingComponents" : true, "splashscreen" : `

nvue 内无法自动铺满全屏，需要手动指的宽高，已更新文档注明

**Comment by XSBYAPP** [comment]
bug复bug，bug无穷多。这是事实，官方确实留下太多Bug.有些致命bug,你提问题，有时还当你不存在，搞得我现在不提了。

**Comment by XSBYAPP** [comment]
一个好产品，需要工匠精神，目前看来，dcloud在这方面缺欠！感觉像赶集一样，急急忙忙的。急急忙忙正体现bug多。你们可以收一些服务费，这样你们也有动力，做的东西也精致。
