### ISSUE TITLE
注册全局组件无法拆分js文件

### ISSUE THREAD

**Issue by zoneccc** [dcloudio/uni-app#1273]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
注册全局组件无法拆分js文件，只能在main.js使用Vue.component。

**复现步骤**
![image](https://user-images.githubusercontent.com/46894228/72325144-74043700-36e7-11ea-9c9b-95adf97c5268.png)
如图，把Vue抛给init方法，去初始化自定义的全局方法和组件，init下面又拆分N个js文件，分别初始化filter、component等。
```javascript
//初始化js文件
import initComponent from './component'
import initMixin from './mixin'
import initPrototype from './prototype'
import filter from './filter'

export default function (Vue) {
    initComponent(Vue)
    initMixin(Vue)
    initPrototype(Vue)
    filter(Vue)
}
```

**预期结果**
小程序、H5能正常初始化。

**实际结果**
小程序、H5能正常初始化。但是小程序组件没法正常初始化。

**系统信息:**
 - 发行平台: 微信小程序、H5平台
 - HBuilderX版本 2.5.1.20200103

**补充信息**
检查unpackage编译文件，app.json中全局组件没有注册。

**Comment by Wangyaqi** [comment]
可以发一个精简的项目上来，另外也欢迎体验新上线的功能easycom  [https://uniapp.dcloud.io/collocation/pages?id=easycom](https://uniapp.dcloud.io/collocation/pages?id=easycom)

**Comment by z1900** [comment]
同样问题 +1

**Comment by zlab** [comment]
同样问题 +1

**Comment by zoneccc** [comment]
@Wangyaqi 复先很容易，或者你这边可行的demo放出来我学习下。新特性我试试，刚升上去版本，回头反馈。

**Comment by fxy060608** [comment]
建议使用 easycom 机制，全局组件只支持在 main.js 中使用 Vue.component 注册

https://uniapp.dcloud.io/collocation/pages?id=easycom

**Comment by zoneccc** [comment]
@fxy060608 嗯，切成easycom机制了，不想在main.js写，概念多容易乱。
