### ISSUE TITLE
微信小程序中自定义组件不支持 model 选项

### ISSUE THREAD

**Issue by z1900** [dcloudio/uni-app#1274]
**问题描述**
微信小程序中自定义组件使用 v-model 时不支持 model 选项

**复现步骤**
官方文档：[自定义组件的 v-model](https://cn.vuejs.org/v2/guide/components-custom-events.html#%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E7%9A%84-v-model)
**预期结果**
通过 model 中的选项来指定触发双向绑定的事件和绑定值

**实际结果**
设置 model 选项无效

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: iOS 13.3
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本: uni-app v2.4.2, uni-app cli v2.0.0-24220191115011
 - 设备信息: iPhone8

**Comment by wakaryry** [comment]
先用 value 和 input 这两个默认的吧。

**Comment by z1900** [comment]
现在就是用的默认值，但是在遍历一个 objectArray 的时候 v-model 其中的一个属性，在触发 picker 的 change 事件的时候 emit input 事件会报错，只有 input 类型组件是正常的 @wakaryry

**Comment by wakaryry** [comment]
我这边v-model正常。不过只是绑定过 array/String/Number 这些类型。

**Comment by farzer** [comment]
改了半天，发现真的就只是改成 { prop: 'value', event: 'input'} 才正常.... : )

**Comment by 1273082756** [comment]
哇, 我也是改成{ prop: 'value', event: 'input'} 才正常, uniapp真tm坑啊

> 改了半天，发现真的就只是改成 { prop: 'value', event: 'input'} 才正常.... : )
