### ISSUE TITLE
使用SDK.startWebApp 方式启动UniApp加载不出来问题

### ISSUE THREAD

**Issue by chenhao1041661180** [dcloudio/uni-app#1280]
下载Android-SDK@2.5.1.72759_20200104 ，根据demo中的配置集成了对应的SDK ;通过HBuilderX 2.5.1版本打包生成两个(A、B) UniApp; 并使用SDK.startWebApp方式启动 A  UniApp能启动；用同样的方式启动B 却启动不了。
 ps:另外做了其他尝试；下载了2.5.6版本的SDK,并集成了SDK ；此版本SDK能启动2.5.1 版本的B UniApp;却启动不了2.5.1版本的A.

**Comment by tianyatmq** [comment]
同样问题，开发人员有在维护这个框架? 纯nvue的项目离线包无法通过startWebApp方式启动

**Comment by tonlion** [comment]
widget模式已经不再维护，建议使用小程序sdk。https://nativesupport.dcloud.net.cn/
