### ISSUE TITLE
IOS端H5在微信环境下打开调用uni.chooseVideo没有进入任何回调

### ISSUE THREAD

**Issue by shizhongzheng** [dcloudio/uni-app#1281]
**问题描述**
IOS端H5在微信环境下调用uni.chooseVideo无论成功或者失败都没有进入任何回调？在safari中是可以正常调用的！

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码]
```
uni.chooseVideo({
  count: 1,
  sourceType: ['camera', 'album'],
  complete: () => {
    console.log('进入回调')
  }
})
```

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 iOS
 - HBuilderX版本 [2.5.1.20200103]
 - uni-app版本
 - 设备信息 iPhone 微信环境中打开网址

**Comment by zhetengbiji** [comment]
HBuilderX alpha 最新版已修复
