### ISSUE TITLE
h5的history模式访问index.html页面空白

### ISSUE THREAD

**Issue by haizhilin2013** [dcloudio/uni-app#1283]
**问题描述**
[问题描述：h5的history模式访问index.html页面空白]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

链接：https://uniapp.dcloud.io/h5/index.html

**预期结果**
预期是带不带index.html都能正常打开
我在nginx这么配置也不行
![image](https://user-images.githubusercontent.com/5070345/72521262-119d6900-3896-11ea-9559-12351eeac84b.png)

**实际结果**
h5的history模式访问index.html页面空白
![image](https://user-images.githubusercontent.com/5070345/72504631-23244800-3879-11ea-8e5f-7aff4c7736c4.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
参考：https://router.vuejs.org/zh/guide/essentials/history-mode.html

**Comment by lingdianguole** [comment]
我现在也是页面空白，使用的前端网页托管，要怎么配置？
