### ISSUE TITLE
H5版本在微信环境下，调用uni.chooseImage，部分安卓机型在选择相册图片之后没有进入任何回调

### ISSUE THREAD

**Issue by lijjLyb** [dcloudio/uni-app#1286]
问题描述
H5版本在微信环境下，调用uni.chooseImage，部分安卓机型在选择相册图片之后没有进入任何回调。ios 和 其他安卓下正常。

复现步骤
uni.chooseImage({
  count: 1,
  sizeType: ['original'],
  sourceType: ['album'],
  success: () => {
    console.log('进入回调')
  }，
  fail: () => {
    console.log('进入回调')
  }，
  complete: () => {
    console.log('进入回调')
  }
})

系统信息:
发行平台: H5平台
操作系统: 安卓-微信内打开
HBuilderX版本 [2.5.1.20200103]

**Comment by dcloudhdx** [comment]
直接用原生 html  正常吗？

**Comment by lijjLyb** [comment]
> 直接用原生 html 正常吗？

我试着用原生的 input 标签，被 uni 替换成 uni 的 input 了。

现在只能用原生的 html 重写项目。。回头测试过了告诉你。

**Comment by lijjLyb** [comment]
> 直接用原生 html 正常吗？

应该是手机问题，原生一样也没有任何回调。但是用摄像头却能正常获得图片。。

**Comment by zhetengbiji** [comment]
> > 直接用原生 html 正常吗？
> 
> 应该是手机问题，原生一样也没有任何回调。但是用摄像头却能正常获得图片。。

可能是微信内置浏览器对部分手机有兼容问题，试试使用微信 jssdk

**Comment by AudreyHepbur** [comment]
a's'dasd
