### ISSUE TITLE
app端的v-for中，key使用唯一id，click事件传递的参数在列表变化后不正确

### ISSUE THREAD

**Issue by alaj** [dcloudio/uni-app#1289]
**问题描述**
安卓app端的v-for中，key使用唯一id，click事件传递的参数在列表变化后不正确。
h5端正常

**复现步骤**
如下代码分别在h5端和app端运行：
```vue
<template>
    <view class="content">
        <view v-for="user in userList" :key="user.id">
            <view>
                {{ user.name }}
                <button @click="deleteUser(user.id)">删除{{ user.name }}</button>
            </view>
        </view>
    </view>
</template>

<script>
export default {
    data() {
        return {
            userList: [{ id: 1, name: '张三' }, { id: 2, name: '李四' }]
        };
    },
    methods: {
        deleteUser(userId) {
            console.log(userId);
            this.userList = this.userList.filter(user => {
                return user.id !== userId;
            });
        }
    }
};
</script>

<style></style>
```
界面如下：
![image](https://user-images.githubusercontent.com/17949209/72658206-a44e1d00-39e8-11ea-8e55-3f93eb94b400.png)
在h5端，依次点击“删除张三”、“删除李四”。
在app端，依次点击”删除张三“、”删除李四“。

**预期结果**
h5端和app端表现相同，张三和李四被删除，控制台输出“1”和“2”。

**实际结果**
在h5端，张三和李四被删除，控制台输出”1“和”2“。
在app端，张三被删除，李四无法删除，控制台输出”1“和”1“。

**系统信息:**
 - 发行平台: h5、uniapp
 - 操作系统 EMUI 9.1.0、Android 9
 - HBuilderX版本 2.5.1
 - uni-app版本 2.5.1
 - 设备信息 HUAWEI P20

**补充信息**
可能与该issue是相同问题
https://github.com/dcloudio/uni-app/issues/838
如果key使用index而不是user.id，则app端正常，但有唯一id的情况下，使用index不是v-for的推荐使用方式。

**Comment by fxy060608** [comment]
是不是v3模式？编译时显示的是2.5.1(v3)？

**Comment by alaj** [comment]
> 是不是v3模式？编译时显示的是2.5.1(v3)？

是的，编译器版本：2.5.1（v3）

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/commit/0047ce6102ea16f43705b780a0deada328601fe8
