### ISSUE TITLE
picker-view h5端源代码问题

### ISSUE THREAD

**Issue by freedom2012** [dcloudio/uni-app#1290]
**问题描述**
之前发了一个帖子说的是picker-view设置下标为零不起作用，之后看了源代码，发现代码有问题。
文件是uni-app/src/core/view/components/picker-view/index.vue
![github](https://user-images.githubusercontent.com/5584118/72660296-eb4b0b00-3a06-11ea-9c8f-5a0264389b8e.png)
1、val===oldVal 个人认为这个判断是没有意义的
2、val.find((item, index) => item !== oldVal[index]) 如果oldVal为[1]，而val为[0]的时候结果还是0，这样会导致页面不更新。

**Comment by zhetengbiji** [comment]
此条判断是用于过滤 app-v3 service 层数据回流的
1. val===oldVal 用于短路数组内部数据变更，如：this.value.splice(0, 1, 0)
2. 感谢提醒，使用 find 确实存在缺陷，已修正

**Comment by freedom2012** [comment]
感谢大神的帮助
