### ISSUE TITLE
uin.d.ts里RequestOptions接口缺少timeout选项

### ISSUE THREAD

**Issue by jdz321** [dcloudio/uni-app#1294]
**问题描述**
uin.d.ts里RequestOptions接口缺少timeout选项

**复现步骤**

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/uni-app/lib/uni.d.ts#L1096

还有 `@dcloudio/types` 里的也要加一下  更新uni-cli插件依赖

**Comment by zhetengbiji** [comment]
@dcloudio/types 已更新，另外由于 @types/uni-app 每次更新周期较长，使用 CLI 创建的工程也已经默认改用 @dcloudio/types。
