### ISSUE TITLE
h5 全量更新后   查看localstrorage 发现  储存格式不正确  导致uni.getStorage  报错 JSON.parse err

### ISSUE THREAD

**Issue by webXLing** [dcloudio/uni-app#1297]
**问题描述**
h5 全量更新后   查看localstrorage 发现  储存格式不正确  
导致uni.getStorage  报错 JSON.parse err

使用中 缓存
uni.setStorage({
    key: 'platform',
    data: 'H5'});

正确的格式
platform   {"type":"string","data":"H5"}

但是全量更新 查看localstrorage 发现为
platform   H5

导致  uni.getStorage  报错

**系统信息:**
H5 微信平台  目前  ios 安卓  都可能出现这种情况

**Comment by Wangyaqi** [comment]
更新到最新alpha看还有没有问题
