### ISSUE TITLE
2.5.8（v3）自定义返回按钮被video组件覆盖

### ISSUE THREAD

**Issue by missy0u** [dcloudio/uni-app#1298]
**问题描述**
2.5.8（v3）自定义返回按钮被video组件覆盖，**测试 2.5.1（v3）没问题**
```JSON
			"style": {
				"app-plus": {
					"titleNView": {
						"type": "transparent",
						"autoBackButton": false,
						"buttons": [{
							"type": "back",
							"float": "left",
							"background": "rgba(0,0,0,0)"
						}]
					}
				}
			}
```

**系统信息:**
操作系统 Android 5.1.1
HBuilderX版本 2.5.8.20200128-alpha
编译器版本：2.5.8（v3）

**Comment by dcloudhdx** [comment]
Bug已确认，尽快修复

**Comment by dcloudhdx** [comment]
更新 HBuilderX 到最新 alpha 版本

**Comment by missy0u** [comment]
@dcloudhdx 

更新到2.5.11 v3 问题依然存在

**Comment by dcloudhdx** [comment]
请提供一个完整的简单工程

**Comment by missy0u** [comment]
[bug-demo.zip](https://github.com/dcloudio/uni-app/files/4302907/bug-demo.zip)

@dcloudhdx 
更新到最新版本v3依然还存在这问题，应该不是video组件问题，直接插入文字也一样，估计与样式有关，非v3正常，抽空打包了个demo

操作系统： Android 5.1.1
编译器版本： 2.6.1 v3、2.6.3.20200305-alpha v3

**Comment by missy0u** [comment]
@dcloudhdx 

position: fixed; 的原因

**Comment by dcloudhdx** [comment]
HBuilderX 2.6.6+ 已修复
