### ISSUE TITLE
app端v3版本v-for动态数据，传参永远只传递第一次加载的数据项

### ISSUE THREAD

**Issue by missy0u** [dcloudio/uni-app#1299]
**问题描述**
app端v3版本v-for动态数据，传参永远只传递第一次加载的数据项

> h5、微信小程序、非v3版本均没有问题。

**实际结果**
![uni-app](https://user-images.githubusercontent.com/3926664/73566199-3ef53400-449e-11ea-96e1-c61b317004c2.gif)

**系统信息:**
 - 发行平台: APP
 - 操作系统 Android 5.1.1
 - HBuilderX版本 2.5.1 v3 、 2.5.8 v3

**Comment by fxy060608** [comment]
建议发一个可重现该问题的demo工程

**Comment by missy0u** [comment]
@fxy060608 

更新到2.5.11 v3 发现此问题已解决
