### ISSUE TITLE
发现一个问题单个js文件超过500k就报错了

### ISSUE THREAD

**Issue by zxyaust** [dcloudio/uni-app#13]
[BABEL] Note: The code generator has deoptimised the styling of "unknown" as it exceeds the max of "500KB".
希望官方能解决一下，引入第三方库的时候总是有这个问题

**Comment by xiaoyucoding** [comment]
文件大小超出了编译器的大小限制，建议不要直接引入打包后的文件。

参考 [uni-app引用npm第三方库](http://ask.dcloud.net.cn/article/19727) 的方法，引入源码库。

如果无法通过此方式引入，建议转为 5+ App 没有此类限制。后续，会看情况调整此限制。

**Comment by xiaoyucoding** [comment]
不好意思，在问答社区处理了此问题，就随手关掉了，抱歉。

**Comment by xiaoyucoding** [comment]
不好意思，因为在问答社区看到了重复的问题，就随手点掉了。
造成误会，表示抱歉，以后会注意的。(/ □ \)

**Comment by zxyaust** [comment]
好的
