### ISSUE TITLE
IOS设备图片选择后空白，选择多张图片，最后一张图片不显示

### ISSUE THREAD

**Issue by tbto** [dcloudio/uni-app#1300]
**问题描述**
IOS设备图片选择后空白，选择多张图片，最后一张图片不显示

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]
<img width="932" alt="image" src="https://user-images.githubusercontent.com/3437980/73588233-7a751a00-4501-11ea-8d23-443b4e085cf2.png">

**系统信息:**
 - 发行平台:  App
 - 操作系统 iOS 12.1
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 
uni-app v2.5.1
uni-app cli v2.0.0-25120200103006

Environment Info:

  System:
    OS: macOS 10.14.4
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
  Binaries:
    Node: 12.14.1 - ~/.nvm/versions/node/v12.14.1/bin/node
    Yarn: Not Found
    npm: 6.13.6 - ~/.nvm/versions/node/v12.14.1/bin/npm
  Browsers:
    Chrome: 79.0.3945.130
    Firefox: 67.0
    Safari: 12.1
  npmPackages:
    @dcloudio/uni-app-plus: ^2.0.0-25120200103006 => 2.0.0-25120200103006 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-cli-shared: ^2.0.0-25120200103006 => 2.0.0-25120200103006 
    @dcloudio/uni-h5: ^2.0.0-25120200103006 => 2.0.0-25120200103006 
    @dcloudio/uni-helper-json: * => 1.0.5 
    @dcloudio/uni-migration: ^2.0.0-25120200103006 => 2.0.0-25120200103006 
    @dcloudio/uni-mp-alipay: ^2.0.0-25120200103006 => 2.0.0-25120200103006 
    @dcloudio/uni-mp-baidu: ^2.0.0-25120200103006 => 2.0.0-25120200103006 
    @dcloudio/uni-mp-qq: ^2.0.0-25120200103006 => 2.0.0-25120200103006 
    @dcloudio/uni-mp-toutiao: ^2.0.0-25120200103006 => 2.0.0-25120200103006 
    @dcloudio/uni-mp-weixin: ^2.0.0-25120200103006 => 2.0.0-25120200103006 
    @dcloudio/uni-stat: ^2.0.0-25120200103006 => 2.0.0-25120200103006 
    @dcloudio/uni-template-compiler: ^2.0.0-25120200103006 => 2.0.0-25120200103006 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-25120200103006 => 2.0.0-25120200103006 
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-25120200103006 => 2.0.0-25120200103006 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-25120200103006 => 2.0.0-25120200103006 
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-25120200103006 => 2.0.0-25120200103006 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-25120200103006 => 2.0.0-25120200103006 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  3.12.1 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.1.2 
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1 
    @vue/cli-plugin-router:  4.1.2 
    @vue/cli-plugin-vuex:  4.1.2 
    @vue/cli-service: ^4.1.0 => 4.1.2 
    @vue/cli-shared-utils:  3.12.1 
    @vue/component-compiler-utils:  3.1.1 (3.1.1)
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.10 => 2.6.11 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.8.3 
    vue-router:  3.0.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.0.1 => 3.1.2 
  npmGlobalPackages:
    @vue/cli: 4.1.2
 - 设备信息  iPhone6s

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by dcloudhdx** [comment]
根据你的描述无法定位问题，请提供示例工程
