### ISSUE TITLE
nvue不支持在main.js中全局注册组件

### ISSUE THREAD

**Issue by zhongku** [dcloudio/uni-app#1301]
**问题描述**
在nvue页面中不支持在main.js中全局注册组件，以及Vue.prototype

请问下，这个问题在最新的版本中什么时候可以解决？

**Comment by dcloudhdx** [comment]
目前暂不支持，可以用easycom解决，不需要单独引用组件
[参考文档](https://uniapp.dcloud.io/collocation/pages?id=easycom)
