### ISSUE TITLE
ajax请求无法设置xhrFields: {withCredentials: true}参数

### ISSUE THREAD

**Issue by DisMirror** [dcloudio/uni-app#1304]
**问题描述**
网络请求中除了提供的设置，还需要其他的设置，比如xhrFields

**复现步骤**
在后端程序里设置request session，发现每次请求的request都是新的。因此需要设置xhrFields

**Comment by fxy060608** [comment]
h5平台？

**Comment by zhetengbiji** [comment]
uni.request目前无此参数，h5可以直接使用xhr对象

**Comment by DisMirror** [comment]
> h5平台？

安卓，因为后端设计的是shiro+ajax登录，需要请求带cookie取session id

**Comment by zhetengbiji** [comment]
> > h5平台？
> 
> 安卓，因为后端设计的是shiro+ajax登录，需要请求带cookie取session id

安卓没有此类配置
