### ISSUE TITLE
uni.createBLEConnection没有success事件

### ISSUE THREAD

**Issue by boronlin** [dcloudio/uni-app#1305]
**问题描述**
在Ios和安卓中，连接蓝牙（uni.createBLEConnection）没有 success，只有complete，
所以，在demo中，一直显示链接状态无法进不入下一个操作

**Comment by dcloudhdx** [comment]
测试 hello uni-app 示例是可以连接成功的，对比下代码

**Comment by boronlin** [comment]
是从该项目Clone出来，直接运行到真机，无论是安桌机或iphoneh，用uni.createBLEConnection都不能执行到success方，只能执行到complete，采用把uni改成 plus.bluetooth.就没问题.
同样的，调用 uni.writeBLECharacteristicValue是会出错或导至app闪退，解决方法一样是把uni改成 plus.bluetooth.

**Comment by boronlin** [comment]
我们是做运动设备智能化的公司，主要通信是蓝牙，在技术评估时，感觉蓝牙的问题很多
比如，获取iPhone和安卓的特征属性不太一样，同样是write的，iphone是true, 安卓为false, 如果用plus.bluetooth. 安卓又能够正常写入，如果用uni. 安卓将无法写入，而且会闪退。

**Comment by boronlin** [comment]
请问是否有人可以做技术支持
我的微信或电话  17750658808

**Comment by dcloudhdx** [comment]
HBuilderX 版本多少？

**Comment by boronlin** [comment]
HBuilderX是最新版本是 2.5.1.20200103

试了 Alpha版 v2.5.11也是一样的问题

**Comment by yfm10** [comment]
一样的问题，HBuilderX， 2.5.1
1.执行不到success 
2.安卓监听不到蓝牙特征值变化，微信小程序可以 
3.hello示例选设备列表和特征值有问题

**Comment by boronlin** [comment]
> 一样的问题，HBuilderX， 2.5.1
> 1.执行不到success
> 2.安卓监听不到蓝牙特征值变化，微信小程序可以
> 3.hello示例选设备列表和特征值有问题

把蓝牙相关的uni替换成plus.bluetooth.就可以进入到success，也可以监听到蓝牙特征值变化，但在安卓版可，可能会看到蓝牙属性值不同，如，我的writew值,在iPhone里true, 在安卓里为false,但仍然能够写入。

微信:  boronlin

**Comment by yfm10** [comment]
> > 一样的问题，HBuilderX， 2.5.1
> > 1.执行不到success
> > 2.安卓监听不到蓝牙特征值变化，微信小程序可以
> > 3.hello示例选设备列表和特征值有问题
> 
> 把蓝牙相关的uni替换成plus.bluetooth.就可以进入到success，也可以监听到蓝牙特征值变化，但在安卓版可，可能会看到蓝牙属性值不同，如，我的writew值,在iPhone里true, 在安卓里为false,但仍然能够写入。
> 
> 微信: boronlin
plus.bluetooth可以进入success事件了，但安卓app还是监听不到特征值变化了，微信小程序可以。

**Comment by loyalove** [comment]
在HBuilderX 2.6.5.20200314
v3模式存在如题相同问题，uni.writeBLECharacteristicValue会导致APP闪退
v2模式运行正常

**Comment by Wangyaqi** [comment]
2.6.7-alpha发布之后可以再试试

**Comment by boronlin** [comment]
我们直接自己用原生重新写，等官方解决，黄花菜都凉了

**Comment by StrivingRabbit** [comment]
新版已修复
