### ISSUE TITLE
uni-app怎么控制webview的缓存方式？

### ISSUE THREAD

**Issue by lmf** [dcloudio/uni-app#1306]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
看很早之前文档支持在manifest文件中配置cache: { mode: 'noCache'}，现在uni-app还支持这种吗？不支持的话有什么方式控制缓存

**Comment by lmf** [comment]
@fxy060608 @ArrayDC

**Comment by lmf** [comment]
@fxy060608 @zhetengbiji 有没有办法呢

**Comment by ArrayDC** [comment]
vue页面中的web-view组件仍然可以使用此方式控制
