### ISSUE TITLE
非v3模式App启动后白屏，点击tab没反应

### ISSUE THREAD

**Issue by he426100** [dcloudio/uni-app#1307]
**问题描述**
去掉v3后模拟器中启动App白屏

**复现步骤**
[复现问题的步骤]
修改mainfest，去掉v3

**预期结果**
正常启动

**实际结果**
11:38:00.690 reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Exception: TypeError: $gwx is not a function. (In '$gwx('./app.wxml')', '$gwx' is undefined)
11:38:00.710 global code@weex createInstanceContext:22:31
11:38:00.752 getTemplateInfo== template md5 43aa0d44433d257d96ab0b04c04db226 length 6559135 base64 md5 Q6oNREM9JX2WqwsEwE2yJg== response header {"templateSourceBase64MD5":["Q6oNREM9JX2WqwsEwE2yJg=="],"templateSourceMD5":["43aa0d44433d257d96ab0b04c04db226"]}
11:38:00.896 TypeError: $gwx is not a function
11:38:00.915 at file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/app-view.js:115:27 at uniapp://ready:182
11:38:00.936 webviewScriptError
11:38:00.956 $gwx is not a function
11:38:00.977 TypeError: $gwx is not a function
11:38:00.997 at file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/app-view.js:115:27 at uniapp://ready:182
11:38:01.020 Uncaught TypeError: $gwx is not a function at app-view.js:115

**系统信息:**
 - 发行平台: App
 - 操作系统 android 6.0.1
 - HBuilderX版本 2.5.1
 - uni-app版本 
 - 设备信息 mumu模拟器

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by dcloudhdx** [comment]
检查 js 中使用了不兼容的语法
