### ISSUE TITLE
canvas drawImage 在app端的自定义组件中无效

### ISSUE THREAD

**Issue by ialmost** [dcloudio/uni-app#1310]
直接用官网 drawImage 的例子就可以复现
在页面内是可以的，但是在组件里无效，app 端都不行

**Comment by dcloudhdx** [comment]
开启 V3 编译吧

**Comment by luvletterldl** [comment]
微信小程序端同样是无效的，开启V3编译也不行 HBuilder: 2.6.11.20200409

**Comment by luvletterldl** [comment]
> 开启 V3 编译吧

有没有其他的尝试解决的方法，现在比较急🙏

**Comment by luvletterldl** [comment]
> 开启 V3 编译吧

我开启V3编译就会白屏，没有用nvue，这是什么情况

**Comment by luvletterldl** [comment]
> 直接用官网 drawImage 的例子就可以复现
> 在页面内是可以的，但是在组件里无效，app 端都不行

你的这个drawImage在app端的自定义组件中无效这个解决了吗，怎么解决的

**Comment by ialmost** [comment]
> > 直接用官网 drawImage 的例子就可以复现
> 
> > 在页面内是可以的，但是在组件里无效，app 端都不行
> 
> 
> 
> 你的这个drawImage在app端的自定义组件中无效这个解决了吗，怎么解决的

组件加上 this
uni.createCanvasContext(canvasId, this)

**Comment by luvletterldl** [comment]
> > > 直接用官网 drawImage 的例子就可以复现
> > 
> > 
> > > 在页面内是可以的，但是在组件里无效，app 端都不行
> > 
> > 
> > 你的这个drawImage在app端的自定义组件中无效这个解决了吗，怎么解决的
> 
> 组件加上 this
> uni.createCanvasContext(canvasId, this)
我的在Android端可以，但是iOS上面还是不行

**Comment by ialmost** [comment]
> > > > 直接用官网 drawImage 的例子就可以复现
> 
> > > 
> 
> > > 
> 
> > > > 在页面内是可以的，但是在组件里无效，app 端都不行
> 
> > > 
> 
> > > 
> 
> > > 你的这个drawImage在app端的自定义组件中无效这个解决了吗，怎么解决的
> 
> > 
> 
> > 组件加上 this
> 
> > uni.createCanvasContext(canvasId, this)
> 
> 
> 
> 我的在Android端可以，但是iOS上面还是不行，有没有办法解决一下

去社区提bug

**Comment by luvletterldl** [comment]
> > > > > 直接用官网 drawImage 的例子就可以复现
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 在页面内是可以的，但是在组件里无效，app 端都不行
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 你的这个drawImage在app端的自定义组件中无效这个解决了吗，怎么解决的
> > 
> > 
> > > 
> > 
> > 
> > > 组件加上 this
> > 
> > 
> > > uni.createCanvasContext(canvasId, this)
> > 
> > 
> > 我的在Android端可以，但是iOS上面还是不行，有没有办法解决一下
> 
> 去社区提bug

我终于发现这个bug怎么解决了！！！！！！
如果drawImage的图片的url如果是uni.getImageInfo()就不行，必须通过uni.downloadFile()去获得临时url

**Comment by keyiis** [comment]
我传的是这样的临时路径 http://tmp/MWI13a72rYx24acd4dfd8cd058c1d845b0d080ef4933.JPG 小程序环境一直不行，找不到原因
