### ISSUE TITLE
关于云开发uniCloud的几点问题

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#1314]
我个人是比较倾向于使用云开发的。

现在主要是有几点疑问，以前也没有使用过云开发，对于腾讯云以及阿里云提供的云开发的服务/技术范围也不熟，不知道对于某些业务是不是有些限制。

1. 现在的业务中难免会有一些 消息队列(mq) 的业务，不知道能不能直接实现；
2. 实时推送，数据实时刷新，聊天功能；
3. 离线推送；
4. 大都数产品都有一个自己的数据后台管理页面(PC端管理后台)，能不能实现；
5. 能不能配合现有的服务器接口进行合作，比如一些直播业务可能用的就是别人的sdk/服务；

谢谢。

**Comment by freew01f** [comment]
mqtt了解一下

**Comment by SheepYang1993** [comment]
还有数据能否导出/导入？

**Comment by Wangyaqi** [comment]
1、2目前不能直接实现，3、4、5没问题
