### ISSUE TITLE
小程序无法正常使用 webpack bundle analyzer

### ISSUE THREAD

**Issue by WangLeto** [dcloudio/uni-app#1316]
**问题描述**
使用 uniapp 框架开发小程序，添加 webpack bundle analyzer 插件后，无法查看每个 chunk 中具体含有哪些模块，丢失了很多关键信息。

**Comment by fxy060608** [comment]
请具体说明

**Comment by WangLeto** [comment]
![image](https://user-images.githubusercontent.com/25009314/74918002-6be49900-5403-11ea-81dd-a1a3441e92cb.png)
上图是正常shi'y使用 webpack-bundle-analyzer 的截图，可以看到一个 chunk 中含有数个模块，如 lodash 等。
下图s是采用 uniapp 框架开发的项目添加该插件后的分析截图，可以看到 chunk 中缺失模块信息。
![image](https://user-images.githubusercontent.com/25009314/74918244-c3830480-5403-11ea-8a0c-28cbc185fca0.png)

**Comment by fxy060608** [comment]
可以把Treemap sizes切换到stat模式看看
