### ISSUE TITLE
关于mp-weixin分包优化-静态资源放入分包中的问题？

### ISSUE THREAD

**Issue by frylstar** [dcloudio/uni-app#1317]
**问题描述**
1. 在打包为微信小程序时，直接将静态资源放入分包中是不会被编译进去的，试了几次发现只有当放入分包目录下的静态资源目录名为 **static** 时才会被编译进去（其他情况下不行），想问下官方是这样的吗？

[官方文档 关于分包优化的说明](https://uniapp.dcloud.io/collocation/manifest?id=%E5%85%B3%E4%BA%8E%E5%88%86%E5%8C%85%E4%BC%98%E5%8C%96%E7%9A%84%E8%AF%B4%E6%98%8E)
![{E63A4390-7A13-4945-8380-1CD4029D8A89}_20200213172111](https://user-images.githubusercontent.com/36854177/74419707-47c60c80-4e85-11ea-9dd4-50957c7089ae.jpg)
2. 问下这个目前支持的分包内静态资源拷贝是指如何支持？谢谢

相关问题链接：[https://ask.dcloud.net.cn/question/76614](https://ask.dcloud.net.cn/question/76614)
[https://ask.dcloud.net.cn/question/68773](https://ask.dcloud.net.cn/question/68773)

**系统信息:**
 - 发行平台: [微信小程序]
 - HBuilderX版本 [2.5.1.20200103]

**Comment by zhetengbiji** [comment]
是的，相关文档已更新 https://github.com/dcloudio/uni-app/commit/ecbd508c187f8b9842f043ec8f937ffedce463d5#diff-653ce139a553a4ce567d5bcf90bb23b9

**Comment by frylstar** [comment]
了解了，谢谢回复！

**Comment by Primary-Traxex** [comment]
终于找到原因了
官方文档没有更新, 链接: [关于分包优化的说明](https://uniapp.dcloud.io/collocation/manifest?id=%e5%85%b3%e4%ba%8e%e5%88%86%e5%8c%85%e4%bc%98%e5%8c%96%e7%9a%84%e8%af%b4%e6%98%8e)
请尽快更新吧, 避免误导更多人
