### ISSUE TITLE
v-for在微信小程序中@tap无法获取index

### ISSUE THREAD

**Issue by chendanlin** [dcloudio/uni-app#1318]
**问题描述**
v-for在微信小程序中 v-for="(item, index) in array"无法在事件中使用index，在h5端运行正常

**复现步骤**
`
<view v-for="(item, index) in [1,2,3]" :key="item" @tap="selectdIndex = index">
			  {{item}}-{{index}}
			</view>
`

selectdIndex是data中的数据，在h5端没问题可以运行，在微信开发工具中单击时报错如下
[Vue warn]: Property or method "index" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

**系统信息:**
 - 发行平台: 微信小程序（微信开发者工具）
 - 操作系统 window10
 - HBuilderX版本 2.5.1.20200103，微信开发者工具1.02.1911180

**Comment by Wangyaqi** [comment]
@tap="selectdIndex = index" 这种写法是在哪看到的

**Comment by chendanlin** [comment]
具体在什么时候已经忘了，主要是在vue的h5是可以使用这种语法的，如果在uni中这种写法是错误的，在点击时获取数组的下标，正确的方式是怎样的

**Comment by Wangyaqi** [comment]
了解了，小程序端使用应该是有限制的，事件只能接收function

**Comment by zhetengbiji** [comment]
96443deec87a2734b367a35fec0ab101c431fbc6

**Comment by zhetengbiji** [comment]
HBuilderX 2.8.4 已发布，有对应优化
