### ISSUE TITLE
如何在uni-app的App端 ,即安卓/ios的手机端,上使用原生 nodejs 的API?

### ISSUE THREAD

**Issue by masx200** [dcloudio/uni-app#1319]
**新功能描述**
简洁描述你希望补充完善的增强功能
如何在uni-app的App端 ,即安卓/ios的手机端,上运行原生 nodejs 程序?

或者如果有开发者制作原生nodejs插件,发布在插件市场里也好

**现状及问题**
[当前现状及由此导致的不便]
目前在App端上能使用的API只有 HTML5+plus和扩展原生插件,但是插件市场没有找到原生的nodejs插件

原生开发对于前端入门开发人员来说难度太高了

在App端 的 提供的功能还不够用,很多的原生能力难以实现,而且nodejs的生态非常丰富

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by zhetengbiji** [comment]
未内置node运行环境，需要自己集成：https://code.janeasystems.com/nodejs-mobile

**Comment by cc4dogman** [comment]
可以用cordova开发把,技术老了点但原生能力还是有的,uniapp只输出h5,外面套个APP的壳
