### ISSUE TITLE
地图map组件circles属性无效

### ISSUE THREAD

**Issue by diablosin** [dcloudio/uni-app#1320]
**问题描述**
uni-app的地图map组件，设置属性circles，阿里小程序开发者工具中的模拟器可以显示，在真机钉钉中无效

**复现步骤**
[复现问题的步骤]
参照map组件使用文档，并设置circles属性

**系统信息:**
 - 发行平台: 钉钉小程序
 - 操作系统：iOS 13.3.1
 - HBuilderX版本：2.5.1.20200103
 - 阿里小程序IDE：1.5.5
 - 设备信息 iPhone 7

**Comment by Wangyaqi** [comment]
使用支付宝官方示例测试，应该是钉钉不支持circle

**Comment by niefang2017** [comment]
地图map组件circles属性，js就报错
而且marker 上的标签 label里面的属性，x，y，bgColor无效，
基本做不了业务需求

**Comment by dcloudhdx** [comment]
基础库 1.x 已支持 circles，更新IDE更换基础库试试
