### ISSUE TITLE
picker日期模式下，粒度为day的时候，范围约束不生效，仍可以显示在约束外的日期

### ISSUE THREAD

**Issue by han3sui** [dcloudio/uni-app#1322]
**问题描述**
picker日期模式下，粒度为day的时候，范围约束不生效，选择的时候仍会显示约束外的日期，但是是无法选择的，粒度为month或者year的时候，可以正常约束，超出的时间会被隐藏

**复现步骤**
<picker mode="date" :value="date" :start="startDate" :end="endDate" @change="bindDateChange">

**系统信息:**
Iphone XR，IOS13

**Comment by hbcui1984** [comment]
运行到哪个平台？

**Comment by han3sui** [comment]
> 运行到哪个平台？

微信小程序

**Comment by zhetengbiji** [comment]
> > 运行到哪个平台？
> 
> 微信小程序

设计就是如此

**Comment by han3sui** [comment]
> > > 运行到哪个平台？
> > 
> > 
> > 微信小程序
> 
> 设计就是如此

无法理解

**Comment by zhetengbiji** [comment]
> > > > 运行到哪个平台？
> > > 
> > > 
> > > 微信小程序
> > 
> > 
> > 设计就是如此
> 
> 无法理解

可以找微信小程序团队反馈一下

**Comment by zhetengbiji** [comment]
App 和 H5 端 设置了不同 mode 时表现一致：范围之外可以显示，不可以选择

**Comment by vibesudi** [comment]
> > > > 运行到哪个平台？
> > > 
> > > 
> > > 微信小程序
> > 
> > 
> > 设计就是如此
> 
> 无法理解

能看不能选！显示的意义何在！

**Comment by zhetengbiji** [comment]
> > > > > 运行到哪个平台？
> > > > 
> > > > 
> > > > 微信小程序
> > > 
> > > 
> > > 设计就是如此
> > 
> > 
> > 无法理解
> 
> 能看不能选！显示的意义何在！

无特殊意义，只是未增加隐藏逻辑。
