### ISSUE TITLE
android原生界面能点进去不同的uni-app项目么？

### ISSUE THREAD

**Issue by sunny635533** [dcloudio/uni-app#1323]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
目前我按照官方的demo测试，只能打开一个uniapp项目。
**复现步骤**
[复现问题的步骤]
1.  首先我先把uni-app在HuilderX打包成本地资源文件，如图：
![image](https://user-images.githubusercontent.com/4737071/74602057-cb7b3580-50df-11ea-8982-d408d8da7155.png)

2. 把打包好的资源文件放进android原生的assets目录，并在dcloud_control该uni-app的appId配置，如图：
![image](https://user-images.githubusercontent.com/4737071/74602080-15641b80-50e0-11ea-8a39-edb4fc8d7792.png)

3. 在AndroidMainfest.xmnl配置启动的uni-app的activity类，如图：
![image](https://user-images.githubusercontent.com/4737071/74602097-53f9d600-50e0-11ea-9ba7-68297ed9cbe4.png)

之前老的SDK版本，能用SDK_WebApp类去打开多个不同uni-app的项目，现在最新的sdk并不支持用SDK_WebApp类去打开。期望官方技术支持能尽快回复这个问题。到底是这期sdk的bug，还是以后原生项目集成uni-app的sdk，只能是启动一个uni-app项目？？？

**预期结果**
这种方式只能打开一个uni-app项目，无法向PandoraEntry类动态传递appId参数。

**系统信息:**
 - 发行平台:uni-app
 - 操作系统：Android 9.0
 - HBuilderX版本 ：2.5.1.20200103
 - uni-app版本：sdk版本是Android-SDK@2.5.1.72759_20200104
 - 设备信息：android真机或模拟器

**补充信息**
SDK提供的PandoraEntryActivity是否能提供appID参数，用以打开动态的uni-app项目。

**Comment by dcloudhdx** [comment]
欢迎体验 uni小程序 SDK
`https://ask.dcloud.net.cn/docs/#https://ask.dcloud.net.cn/article/36941`
