### ISSUE TITLE
nvue向vue通讯，报错uni.postMessage is not a function

### ISSUE THREAD

**Issue by Liu-Peter** [dcloudio/uni-app#1324]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

按照文档nvue向vue页面通讯，uni.postMessage报is not a function

**复现步骤**

`<template><div @click="test"><text>点击页面发送数据</text></div></template>
<script>
    export default {
        methods: {
            test(e) {
                uni.postMessage({test: "数据",value:"数据"});
            }
        }
    }
</script>`
求解决？

**Comment by fxy060608** [comment]
推荐使用:uni.$on,uni.$emit
https://uniapp.dcloud.io/api/window/communication

**Comment by Liu-Peter** [comment]
好的
