### ISSUE TITLE
移动端 首次加载h5 会出现绿色进度条 导致系统页面返回 和 navigate Api 都失效 官方demo也是这样

### ISSUE THREAD

**Issue by webXLing** [dcloudio/uni-app#1327]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
uniapp 打包的h5   移动端 首次加载h5  一定概率 会出现绿色进度条 导致系统页面返回 和 navigate Api 都失效 

官方的api实例demo 手机访问也会出现该问题

目前发现通过 uniapp开发的 h5  似乎都有这个问题
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/37230321/74625991-29b02300-5189-11ea-835d-1972ffb67ab3.png)

**系统信息:**
 - 发行平台：h5
环境  微信下

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
说明框架还没有加载完，尽量使用cdn
