### ISSUE TITLE
何时添加webassembly模块的支持？ 

### ISSUE THREAD

**Issue by masx200** [dcloudio/uni-app#1329]
**新功能描述**
简洁描述你希望补充完善的增强功能

何时添加webassembly模块的支持？ 

**现状及问题**
[当前现状及由此导致的不便]
无法在uniapp中调用其他可执行文件，进行高性能的计算。
**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by dcloudhdx** [comment]
使用 renderjs 可以支持
`https://uniapp.dcloud.io/frame?id=renderjs`

**Comment by dcloudhdx** [comment]
在app平台推荐使用原生插件的方式，性能上要高于wasm(在不频繁和原生通信时)，在H5平台无效

如果想跨平台且要求最高性能，原生插件代码推荐用 C/C++ 编写，可以移植到H5平台

**Comment by puti94** [comment]
需求 +1

**Comment by zhetengbiji** [comment]
> 需求 +1

参考上方回复

**Comment by ginkosen** [comment]
+1
