### ISSUE TITLE
官方文档中找了很久都没有找到table相关的组件

### ISSUE THREAD

**Issue by hugetiny** [dcloudio/uni-app#1331]
**新功能描述**
我之前用Quasar有很好的table组件，可以根据数据自动生成，也可以静态，uni-app是否也有？

**现状及问题**
官方文档中找了很久都没有找到官方table的组件

**尝试方案**
找到类似的组件代替，或者添加table组件

**Comment by klren0312** [comment]
table 我是自己用flex布局画的...

**Comment by hbcui1984** [comment]
参考：https://ext.dcloud.net.cn/plugin?id=3270
