### ISSUE TITLE
自定义组件几率性渲染错误

### ISSUE THREAD

**Issue by he426100** [dcloudio/uni-app#1334]
**问题描述**
自定义组件几率性渲染错误，一会正常，一会不正常

**复现步骤**
[复现问题的步骤]
1.  启动 正常
2. 再次启动 异常
3. ...

**预期结果**
每次都正常

**实际结果**
随机异常

**系统信息:**
 - 发行平台: app
 - 操作系统 Android 7.0
 - HBuilderX版本 [2.5.1, 2.5.11]
 - uni-app版本 v3
 - 设备信息 [夜神模拟器安卓5、夜神模拟器安卓7、华为p30 pro]

**补充信息**
自定义了两个组件，一个flex-row，一个flex-col
模板代码分别如下
```javascript
<template>
    <view
      :style="style"
      :class="classes"
    >
      <slot></slot>
    </view>
</template>
```
```javascript
<template>
    <view :class="classes" :style="style">
      <slot></slot>
    </view>
</template>
```

[点此查看组件源码](https://github.com/he426100/uni-vant/tree/master/components/flex-row)

在App首页使用
```javascript
<flex-row justify="space-between" gutter="10" wrap class="plr38">
          <flex-col :span="12" v-for="(item, index) in newProjects" :key="index">
          </flex-col>
</flex-row>
```

h5上完全正常，App上一会正常一会不正常，不正常的表现在我查看元素时发现有的区域flex-col变成了flex-row，有的区域flex-row消失了，某一次打开APp是正常的，重启一次它就可能不正常了，包括打包出来正式版本的App装到手机上都是这样。
hbx 2.5.1正式版 跟 2.5.11 alpha 版都这样。
我在项目中大量使用了这两个组件（flex布局），目前只发现首页是异常的。
去除组件，改回view.class形式就完全正常了，可以确定flex布局本身毫无问题，就是组件渲染的时候出错了，渲染出错就导致了样式紊乱

**Comment by fxy060608** [comment]
可以发一个重现的demo工程
描述下测试步骤
截图说明错误内容

**Comment by he426100** [comment]
又出来一个新的BUG
`
<block 1><my-component/></block>
<block 2><my-component/></block>
<block 3><my-component/></block>
`
block指的是一个页面中不同的区域
只有1 的时候正常，加上2和3异常（概率性），异常指的是my-component的内容变成了 undefined，控制台疯狂报错：

> my-component.vue: [8427c72c]$r[47][sc] is undefined at view.umd.min.js:1
my-component.vue: [8427c72c]$r[47][v-model] is undefined at view.umd.min.js:1
...

这个新的错误是在我把页面不同区域的内容（结构相似）整合为组件后出现的，新错误出来后老错误不出现了。

demo我还在弄，概率性的问题不好整，单独弄一个页面出来他又不出错

**Comment by he426100** [comment]
发一个群里的聊天记录，我们两出错的原因不同，但是表现差不多
> 我首页隔很久打开 循环的数据也是出现undefined

![1](https://user-images.githubusercontent.com/9689137/75008395-e02a4580-54b2-11ea-868f-5d790f73da97.jpg)
![2](https://user-images.githubusercontent.com/9689137/75008400-e4566300-54b2-11ea-8ab2-4d14bc88289b.png)

**Comment by fxy060608** [comment]
已处理过类似Bug，https://github.com/dcloudio/uni-app/commit/8b892049ece9bd66d44f9f5903f84127af613810
需要demo验证一下是否是同一问题

**Comment by he426100** [comment]
- demo 和 截图

[uni-vant.zip](https://github.com/dcloudio/uni-app/files/4234742/uni-vant.zip)
![正常](https://user-images.githubusercontent.com/9689137/75012779-b4608d00-54bd-11ea-8c1e-32ce0f231801.png)
![异常](https://user-images.githubusercontent.com/9689137/75012783-b62a5080-54bd-11ea-824a-a887cee5fb1d.png)

**Comment by fxy060608** [comment]
基本确认该问题就是之前修复过的。预计下个Alpha版本会带上

**Comment by he426100** [comment]
两个问题都是吗？ 我在demo上把第一个错误也重现了（反复启动）
![9L7{KT}264OZ 355R4UN95I](https://user-images.githubusercontent.com/9689137/75014259-d576ad00-54c0-11ea-8136-1f45b2ec8a61.png)

**Comment by fxy060608** [comment]
> 两个问题都是吗？ 我在demo上把第一个错误也重现了（反复启动）
> ![9L7{KT}264OZ 355R4UN95I](https://user-images.githubusercontent.com/9689137/75014259-d576ad00-54c0-11ea-8136-1f45b2ec8a61.png)

应该是同一个Bug导致的，我这里修复后，不停重启，没发现排版异常和undefined错误了

**Comment by he426100** [comment]
好的，谢谢

**Comment by dcloudhdx** [comment]
HBuilderX 2.6.3+ 已修复

**Comment by he426100** [comment]
实测已修复
