### ISSUE TITLE
form 标签没有高度，并form>view不生效

### ISSUE THREAD

**Issue by pureshine** [dcloudio/uni-app#1338]
![image](https://user-images.githubusercontent.com/40712758/75037237-aaa34d80-54ee-11ea-92ad-7df4eccf81fe.png)

如上图，form如果不设置display：block则没有高度，加上display：block后 有高度，但是在scss中使用form>view给form中的view设置样式不生效，当然可以有别的解决方案，但是想了解下这到底是什么原因，是否为组件的bug，望回复

**Comment by dcloudhdx** [comment]
HBuilderX 版本多少？运行到哪个平台？如果是App，请提供设备信息
