### ISSUE TITLE
组件中单独设置disabled属性不生效

### ISSUE THREAD

**Issue by he426100** [dcloudio/uni-app#1339]
**问题描述**
不生效表现为模板中不生效，
```
<view>{{disabled ? 'disabled' : 'not disable'}}</view>
```
比如这种的他不会变化，再比如
```
<button :disabled="disabled"/>
``` 
这个disabled属性也不起作用，不是变量命名的原因，换个名字一样。一模一样的代码移到页面中就可以，在组件里就是不行（已反复测试，可以确定就是组件中有问题，vue项目中是没问题的）。

**复现步骤**
```
<button @click.stop="disabled = true">{{disabled ? 'disabled' : 'not disable'}}</button>

data () { return { disabled: false } }
```

**预期结果**
对disabled值的改变应该在模板中体现出来

**实际结果**
值变了，模板无变化

**系统信息:**
 - 发行平台: [h5]
 - 操作系统 []
 - HBuilderX版本 [2.5.11]
 - uni-app版本 []
 - 设备信息 []

**补充信息**
在修改disabled值的同时再去修改另一个属性的值就可以了，比如 @click = this.disabled = true,  this.showText = '已经禁止啦' 就完全正常了

**Comment by y1324** [comment]
为什么关闭了？现在还存在这个问题。微信小程序内有问题。H5下没问题

**Comment by he426100** [comment]
@y1324  关闭问题是我发现这个问题是不存在的，是我自己代码写错了
