### ISSUE TITLE
slot-scope 支持了吗？

### ISSUE THREAD

**Issue by q-jason** [dcloudio/uni-app#1342]
**问题描述**
查询文档和百度了好久，v-slot 完美支持了
这代表 slot-scope 支持了吗？
我本地测试只要一写 slot-scope 就会报错
是否是版本的原因？

**Comment by Wangyaqi** [comment]
报什么错？运行到哪端？使用的是什么版本的HBuilderX？有没有启用v3版本编译器

**Comment by q-jason** [comment]
@Wangyaqi 
抱歉..解决了 是个其他问题
