### ISSUE TITLE
微信小程序实时获取地理位置(前后台)

### ISSUE THREAD

**Issue by Joey-996** [dcloudio/uni-app#1345]
**问题描述**
[问题描述：微信原生小程序,可以获取实时得地理位置,包括切换在后台的时候,想请问以下,uni-app,如何获取,看到过获取地理位置是uni.getLocation(OBJECT),但是他不包含后台实时获取,官方文档说的如果实时获取需求申请台持续定位权限,但是也不知道在哪里申请,如果申请过后,还是用这个函数自己定时调用吗

**复现步骤**
[复现问题的步骤]
无

**预期结果**

**实际结果**
无

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本 HBuilderX  2.5.1.20200103

**补充信息**
无

**Comment by dcloudhdx** [comment]
1.manifest.json 配置
```
"mp-weixin" : {
    "requiredBackgroundModes": ["location"]
}
```
2.
`uni.startLocationUpdateBackground({success,fail,complete})`
