### ISSUE TITLE
请问在nvue项目中定义全局公共方法？

### ISSUE THREAD

**Issue by Liu-Peter** [dcloudio/uni-app#1346]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
Vue.prototype定义的，一调用就报错

**Comment by Wangyaqi** [comment]
可以使用vuex

**Comment by Liu-Peter** [comment]
> 可以使用vuex

globalData可以定义函数吗？我开启了Nvue 首页快速启动模式文档里说vuex不支持nvue首页

**Comment by Wangyaqi** [comment]
globalData可以定义函数

**Comment by Liu-Peter** [comment]
> globalData可以定义函数，开启首页快速启动之后需要在nvue首页设置globalData

好的，谢谢
