### ISSUE TITLE
打包出来的支付宝小程序是否支持provide/inject写法？

### ISSUE THREAD

**Issue by ZXHHHH123** [dcloudio/uni-app#1347]
**问题描述**
下载官方的uni-ui库:https://github.com/dcloudio/uni-ui  ，运行于支付宝小程序环境，打开Grid宫格组件，Console栏报错:'[Vue warn]: Injection "grid" not found'，看了一下大致是由于provide/inject的写法导致报错进而使得Grid组件并不能照着预期的展现方式展现。

**复现步骤**
1.  下载uni-ui库:https://github.com/dcloudio/uni-ui 
2. 运行支付宝小程序环境
3. 点击‘布局组件--Grid宫格组件’
4.展示效果预期的展现效果且Console栏里报错

**预期结果**
和微信小程序的展现效果一致，如下图
![image](https://user-images.githubusercontent.com/23452655/75239314-6d480400-57fd-11ea-9e09-b8a8dfd12487.png)

**实际结果**
![image](https://user-images.githubusercontent.com/23452655/75238914-bc416980-57fc-11ea-8f93-b43e03bc7bb9.png)

**系统信息:**
 - 发行平台: [支付宝小程序]
 - 操作系统 [Mac 10.15.3]
 - HBuilderX版本 [2.5.1.20200103]
 - 设备信息 [支付宝小程序开发者工具模拟器]

**Comment by Wangyaqi** [comment]
使用真机看一下是不是正常的

**Comment by ZXHHHH123** [comment]
嗯 我使用真机是正常展现的。
但是在Android机型上，uni-ui的展现速度极慢。iPhone的效果是正常的
#### 重现方式：
扫描支付宝开发者工具生成的‘预览二维码’
在点击Grid宫格组件到组件展现

#### 展现结果
-  而扫描二维码到展现小程序首页的过程花了将近50s （机型为小米Note3，荣耀9x未出现）
- 从点击Grid宫格组件到出现宫格组件的效果花了将近一分钟的时间（机型为小米Note3（54s）、荣耀9x（34s））

**Comment by ZXHHHH123** [comment]
麻烦问一下 上面说的支付宝开发者工具模拟器报错的问题可以解决吗？

**Comment by Wangyaqi** [comment]
开发工具里面的问题要等阿里解决，先使用真机调试吧

**Comment by ZXHHHH123** [comment]
麻烦告知一下你mac版的支付宝开发工具版本是多少呢？我的版本1.5.2 在mac是有问题的

**Comment by mehaotian** [comment]
打开支付宝详情，勾选 启动components2 编译 ， 在默认编译模式下，有些功能不支持
![image](https://user-images.githubusercontent.com/26707388/86333014-ea88f700-bc7d-11ea-9c9d-f6be80533e90.png)
