### ISSUE TITLE
2.6.0版本升级后uni.getSystemInfoSync()出现样式问题

### ISSUE THREAD

**Issue by Kole6** [dcloudio/uni-app#1348]
**2.6.0版本升级后uni.getSystemInfoSync()出现样式问题**

在H5版本中，uni.getSystemInfoSync().windowHeight 现在变得非常小，已经不是窗口大小了！！！

**Comment by zhetengbiji** [comment]
> **2.6.0版本升级后uni.getSystemInfoSync()出现样式问题**
> 
> 在H5版本中，uni.getSystemInfoSync().windowHeight 现在变得非常小，已经不是窗口大小了！！！

获取的值和实际的值分别是多少？

**Comment by Kole6** [comment]
在H5版本中，uni.getSystemInfoSync().windowHeight现在版本获取的值不是实际的窗口大小，不知道是什么

**Comment by zhetengbiji** [comment]
> 在H5版本中，uni.getSystemInfoSync().windowHeight现在版本获取的值不是实际的窗口大小，不知道是什么

你不是认为获取的值小么？那现在值是多少？比实际的小多少？有没有测试工程？

**Comment by Kole6** [comment]
![image](https://user-images.githubusercontent.com/29592422/75315879-da5fa600-589e-11ea-95c4-5e36f2223ba0.png)

**Comment by zhetengbiji** [comment]
chrome测试能复现么？能否提供一个示例

**Comment by Kole6** [comment]
现在浏览器的修复了，微信小程序有同样的问题没有修复，期待尽快修复

**Comment by dcloudhdx** [comment]
小程序平台`getSystemInfoSync()`由小程序提供，用原生小程序试试
