### ISSUE TITLE
运行环境判断问题

### ISSUE THREAD

**Issue by lscho** [dcloudio/uni-app#135]
文档中提到"uni-app 编译为小程序时均为生产环境"。经测试，编译为小程序时均为开发环境。

![](https://ws2.sinaimg.cn/large/006tNbRwly1fymwerl7a6j314s052402.jpg)

![](https://ws2.sinaimg.cn/large/006tNbRwly1fymwepb8srj30vm0mujuk.jpg)

**Comment by hulinNeil** [comment]
这是文档有误，已更改，感谢反馈！
