### ISSUE TITLE
Android 能否添加长截图或者滚动截图功能api

### ISSUE THREAD

**Issue by Kole6** [dcloudio/uni-app#1350]
**新功能描述**
Android 能否添加长截图或者滚动截图功能api 或者整页截屏

**Comment by Wangyaqi** [comment]
可以考虑使用renderjs实现  [https://uniapp.dcloud.io/frame?id=renderjs](https://uniapp.dcloud.io/frame?id=renderjs)

**Comment by Kole6** [comment]
能不能不用v3使用renderjs，一用v3样式乱了很多
