### ISSUE TITLE
华为手机微信浏览器内var(--window-top)的问题

### ISSUE THREAD

**Issue by ben-lau** [dcloudio/uni-app#1356]
**问题描述**
我的弹窗mask遮罩占满全屏，使用样式为
```
.goods-popover-mask {
  position: fixed;
  top: var(--window-top);
  bottom: var(--window-bottom);
  left: 0;
  right: 0;
  background: rgba(0, 0, 0, 0.5);
  z-index: 501;

  .activated>& {
    display: block;
  }

  .deactivated>& {
    display: none;
  }
}
```

在华为手机微信浏览器内，如果开启导航栏则异常，top定位在了屏幕正中间。在别的华为手机浏览器内没问题，在微信浏览器内如果开启自定义头部（navigationStyle:custom）则没问题。

Environment Info:

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 12.12.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.13.7 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @dcloudio/uni-app-plus: ^2.0.0-26120200226001 => 2.0.0-26120200226001
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: ^2.0.0-26120200226001 => 2.0.0-26120200226001
    @dcloudio/uni-h5: ^2.0.0-26120200226001 => 2.0.0-26120200226001
    @dcloudio/uni-migration: ^2.0.0-26120200226001 => 2.0.0-26120200226001
    @dcloudio/uni-mp-alipay: ^2.0.0-26120200226001 => 2.0.0-26120200226001
    @dcloudio/uni-mp-baidu: ^2.0.0-26120200226001 => 2.0.0-26120200226001
    @dcloudio/uni-mp-qq: ^2.0.0-26120200226001 => 2.0.0-26120200226001
    @dcloudio/uni-mp-toutiao: ^2.0.0-26120200226001 => 2.0.0-26120200226001
    @dcloudio/uni-mp-weixin: ^2.0.0-26120200226001 => 2.0.0-26120200226001
    @dcloudio/uni-stat:  2.0.0-26120200226001
    @dcloudio/uni-template-compiler: ^2.0.0-26120200226001 => 2.0.0-26120200226001
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-26120200226001 => 2.0.0-26120200226001
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-26120200226001 => 2.0.0-26120200226001
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-26120200226001 => 2.0.0-26120200226001
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-26120200226001 => 2.0.0-26120200226001
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-26120200226001 => 2.0.0-26120200226001
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.12.1
    @vue/babel-preset-jsx:  1.1.1
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.1.1
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.12.1
    @vue/cli-plugin-babel: ^3.11.0 => 3.12.1
    @vue/cli-service: ^3.11.0 => 3.12.1
    @vue/cli-shared-utils:  3.12.1
    @vue/component-compiler-utils:  3.0.0 (3.0.0)
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.11 => 2.6.11
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.1 (15.7.1)
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.1.2 => 3.1.2
    vuex-persistedstate: ^2.7.1 => 2.7.1
  npmGlobalPackages:
    @vue/cli: Not Found

**Comment by zhetengbiji** [comment]
其他手机的微信浏览器测试过吗？
