### ISSUE TITLE
调用自定义组件的时  给组件加class和style 小程序无效

### ISSUE THREAD

**Issue by idujiayou** [dcloudio/uni-app#136]
问题一 
如 <u-icon class="xxx" style="position: relative; top: 2px;" type="icon-order"></u-icon>
在小程序里style class没赋值成功 

问题二
h5 生成了两个data-v 
![image](https://user-images.githubusercontent.com/16297776/50532092-22762200-0b4f-11e9-9b61-471175da4835.png)

小程序只生成一个data-v 
![image](https://user-images.githubusercontent.com/16297776/50532106-68cb8100-0b4f-11e9-8874-f5990a564844.png)
导致小程序在调用的页面上 无法使用scoped写样式

**Comment by zhetengbiji** [comment]
能否附一下示例代码

**Comment by guohuihot** [comment]
怎么解决的？
