### ISSUE TITLE
挂载数据到Vue.prototype上，view无法映射

### ISSUE THREAD

**Issue by annder** [dcloudio/uni-app#1361]
**问题描述**
当我在`main.js`中写一个全局数据，其他页面上需要将这个数据展示出来时，它报undefined文字。

**复现步骤**

挂载的数据：
```js
import Vue from 'vue';
import App from './App';
Vue.config.productionTip = false;
App.mpType = 'app';


Vue.prototype.aa = 'Hello World';

const app = new Vue({
  ...App
});
app.$mount();
```

在`pages/index/index`中使用：

```vue
<template>
  <view>
    {{aa}}
  </view>
</template>
```

**预期结果**

页面中显示`Hello World`

**实际结果**

![image](https://user-images.githubusercontent.com/12369444/75618396-90c9d080-5ba8-11ea-8f45-41527c29e439.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 iPhone 6
 - HBuilderX版本 HBuilderX 2.6.1
 - 设备信息 iPhone 6

**Comment by social-uni** [comment]
+1

**Comment by StrivingRabbit** [comment]
微信小程序平台不支持
