### ISSUE TITLE
遗漏 生成sitemap.json 文件, 导致微信小程序打开报错.

### ISSUE THREAD

**Issue by trojanliu** [dcloudio/uni-app#1366]
npm run build:mp-weixin

生成的目录, 遗漏 sitemap.json 文件, 导致微信小程序打开报错.

**Comment by fxy060608** [comment]
src下自行增加sitemap.json，编译器不会自动生成

**Comment by ZQun** [comment]
之前npm run dev:mp-weixin和npm run build:mp-weixin可以自动生成来着，今天升级了下依赖，发现不能生成sitemap.json了
