### ISSUE TITLE
建议可配置打包目录

### ISSUE THREAD

**Issue by trojanliu** [dcloudio/uni-app#1367]
建议可配置打包目录

**Comment by youki1213** [comment]
同意，uni-app用Hbuilder打包文件就放在unpackage下，用命令行打包则就放在dist下，工具打包比命令行打包多了一层父级unpackage

**Comment by fxy060608** [comment]
可以修改package.json中的脚本命令，传入UNI_OUTPUT_DIR（支持绝对路径和./相对路径）
`"build:mp-weixin": "cross-env NODE_ENV=production UNI_PLATFORM=mp-weixin UNI_OUTPUT_DIR=./custom-dist vue-cli-service uni-build",`

**Comment by tieniu1** [comment]
> 
好人一生平安
