### ISSUE TITLE
新建uni-app项目，运行到小程序模拟器上，[JSHINT] 16:24:07.667 进程已崩溃

### ISSUE THREAD

**Issue by liukeyan** [dcloudio/uni-app#1369]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by wandali2019** [comment]
原因：node运行异常造成的额。

1. 点击菜单【帮助】【查看运行日志】，看下日志中，提示什么错误。
2. 进入HBuilderX所在目录，进入`plugins/node/`, 点击下node程序，看下node能否正常运行

**Comment by dcloudhdx** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
