### ISSUE TITLE
picker组件

### ISSUE THREAD

**Issue by xdlover** [dcloudio/uni-app#137]
picker组件
 mode = multiSelector

@columnchange 某一列的值改变时触发 columnchange 事件，event.detail = {column: column, value: value}，column 的值表示改变了第几列（下标从0开始），value 的值表示变更值的下标

这个columnchange 事件不能触发
![qq 20190102172932](https://user-images.githubusercontent.com/21051235/50586328-fc84b080-0eb3-11e9-85a8-89f7d81d2112.png)

**Comment by zhetengbiji** [comment]
使用的HBuilderX版本多少，是否最新版本？

**Comment by zhetengbiji** [comment]
长时间未响应，测试未重现此问题，暂时关闭。
