### ISSUE TITLE
android 直接加载assess文件目录下面的 index.html 显示空白

### ISSUE THREAD

**Issue by hubangmao** [dcloudio/uni-app#1371]
我想在已有的android项目上直接加载打包的uniapp ，支持这样操作吗 ？非常的急 ！！！

android 代码是这样的：webView.loadUrl("file:////android_asset/test/index.html")

**Comment by hubangmao** [comment]
急急急 ！

**Comment by Wangyaqi** [comment]
[https://ask.dcloud.net.cn/article/36940](https://ask.dcloud.net.cn/article/36940) 这个看看符合你的要求不

**Comment by hubangmao** [comment]
> https://ask.dcloud.net.cn/article/36940 这个看看符合你的要求不

https://ask.dcloud.net.cn/article/80
