### ISSUE TITLE
微信小程序 运行在ios上报错  安卓上可以运行

### ISSUE THREAD

**Issue by LvJing520** [dcloudio/uni-app#1374]
![image](https://user-images.githubusercontent.com/25576929/75840829-1e0a6080-5e07-11ea-903d-0f42241b614c.png)
求大神看看！！！

**Comment by LvJing520** [comment]
![image](https://user-images.githubusercontent.com/25576929/75849611-376bd680-5e20-11ea-8087-80e1159f9853.png)

**Comment by dcloudhdx** [comment]
请提供测试代码，HBuilderX版本，微信开发者工具版本
