### ISSUE TITLE
webpack自定义vue相关的loader功能支持

### ISSUE THREAD

**Issue by Rockergmail** [dcloudio/uni-app#1375]
**新功能描述**
希望官网支持我们自定义loader

**现状及问题**
虽然现在已近开放了自定义webpack的权限，但是当我们的loader跟vue文件挂钩，就需要我们先引用vue-loader

**尝试方案**
1. 尝试过用vue.config.js官方文档的方法，引入vue-loader，添加vueLoaderPlugin，还是有各种问题
2. 尝试过用dcloud提供的vueLoaderPlugin类，也不行。

**补充信息**
初衷是我司产品很多渠道，代码为了兼容多渠道，已经很难维护和交接了。所以想自己写一个条件编译，且与平台条件编译不冲突，串行编译（平台编译、渠道编译不冲突）。抄了dcloud的preprocessor方案，打算在webpack自定义loader使用。

在网上找过方案，如在package.json加script，但不能满足。

**Comment by fxy060608** [comment]
```javascript
// vue.config.js
module.exports = {
  chainWebpack: config => {
// 访问到vue的规则配置，添加自己的loader相关逻辑，具体api自行参考https://github.com/neutrinojs/webpack-chain
    config.module
      .rule('vue') 
//如果不清楚最终的webpack配置，可以输出一下，根据自己的需求，通过api调整最终规则
console.log(config.toString());
  }
}
```

**Comment by li1753846989** [comment]
怎么获取loader中该vue文件的路径
