### ISSUE TITLE
父子组件使用props传值，支付宝小程序中出现错误

### ISSUE THREAD

**Issue by zguiyang** [dcloudio/uni-app#1378]
**问题描述**
父子组件使用props传值，支付宝小程序中出现错误
[Vue warn]: Avoid mutating a prop directly since the value will be overwritten whenever the parent component re-renders. Instead, use a data or computed property based on the prop's value. Prop being mutated: "loadstate"

found in

---> /components/uni-load-more/uni-load-more
       <Root>
我并没有在子组件中直接改动props参数，并且在微信小程序中运行正常
**复现步骤**
[复现问题的步骤]
父组件
![image](https://user-images.githubusercontent.com/24975063/76045345-bcc5c700-5f97-11ea-9437-b98c1e421efd.png)

子组件
![image](https://user-images.githubusercontent.com/24975063/76045374-cfd89700-5f97-11ea-9916-f4822dc89b29.png)

**预期结果**
不会出现错误

**实际结果**
![image](https://user-images.githubusercontent.com/24975063/76045409-ec74cf00-5f97-11ea-83b7-3c90be307ad5.png)

**系统信息:**
 - 发行平台: 支付宝小程序
 - 操作系统 macos 10.15.3
 - HBuilderX版本  2.6.1.20200226
 - 运行：支付宝小程序开发工具1.5.7

**补充信息**
我在子组件并没有直接改动props中的参数，data中用其他字段进行备份也不行，如果父组件传人的是一个静态字符串就不会报错。并且运行到h5、微信小程序中并没有报错

**Comment by auven** [comment]
同样发现这个问题

**Comment by moshuchao** [comment]
都没有人回答么？

**Comment by zhetengbiji** [comment]
1. 除了报错，功能上是否出现异常？
2. 报错的属性传入的数据是什么类型的？

**Comment by moshuchao** [comment]
在淘宝小程序里运行，重现步骤：在onLoad里改变foo的值会触发这个bug，但如果是在mounted里放到一个延迟函数了有一定几率不会触发。prop与类型无关，功能上看起来是正常的。
``` js
// Parent.vue
<template>
    <view>
        <Child :foo="foo"/>
    </view>
</template>
<script>
// import 

export default {
    data() {
        return {
            foo: ''
        }
    },
    onLoad(query) {
        this.foo = query.foo;
    }
}
</script>
```

```js
// Child.vue

<template>
    <view>{{foo}}</view>
</template>
<script>
export default {
    props:['foo']
}
</script>

```

**Comment by shenxiaai** [comment]
> 在淘宝小程序里运行，重现步骤：在onLoad里改变foo的值会触发这个bug，但如果是在mounted里放到一个延迟函数了有一定几率不会触发。prop与类型无关，功能上看起来是正常的。
> 
> ```js
> // Parent.vue
> <template>
>     <view>
>         <Child :foo="foo"/>
>     </view>
> </template>
> <script>
> // import 
> 
> export default {
>     data() {
>         return {
>             foo: ''
>         }
>     },
>     onLoad(query) {
>         this.foo = query.foo;
>     }
> }
> </script>
> ```
> 
> ```js
> // Child.vue
> 
> <template>
>     <view>{{foo}}</view>
> </template>
> <script>
> export default {
>     props:['foo']
> }
> </script>
> ```

你好，请问最后这个bug解决了吗？

**Comment by Otto-J** [comment]
按照 https://github.com/dcloudio/uni-app/issues/1378#issuecomment-659798587 提供的测试方案，运行到 vue3 到支付宝小程序，未能复现问题。考虑到时间较久，可能已经修复，本 issue close，如果有问题，请 reopen 或者新开 issues
