### ISSUE TITLE
switchTab会触发onshow两次，并且会执行到历史页面的onshow

### ISSUE THREAD

**Issue by IvanJYF** [dcloudio/uni-app#1379]
**问题描述**
switchTab返回到指定的也里，onshow里面的代码会执行两次，返回的过程中会触发到一个tab页面的onshow。

**复现步骤**
1. 选择tabbar的tabA(商城首页)
2. 进入到a1(商品详情)
3. 再进入到a2(确认订单)
4.在a2(确认订单)使用switchTab返回到tabbar的tabB(个人中心)

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
能直接返回到指定的页面，onshow只会执行一次，并且不会触发历史页面的生命周期

**实际结果**
生命周期返回顺序：tabB(onshow) > tabA(onshow) > tabB(onshow)
相当于连续进入tabB
![image](https://user-images.githubusercontent.com/22184146/76064659-11336b80-5fc5-11ea-8337-8bd32fc92777.png)

**系统信息:**
 - 发行平台:微信小程序
 - 操作系统：ios13.3.1
 - HBuilderX版本 [2.6.1]
 - 设备信息 iPhone7

**Comment by dcloudhdx** [comment]
HBuilderX 2.6.6+ 已修复

**Comment by kafeidouzi** [comment]
发行平台:微信小程序
操作系统：ios14.4.2
HBuilderX版本 3.1.11.20210423
设备信息 iPhone12

这个bug又出现了

**Comment by kafeidouzi** [comment]
tabA页面进入到列表页，从列表页进入tabB中，此时AB俩tab页都会触发onshow
