### ISSUE TITLE
uni.request 请求网页，返回的数据里汉字为黑色菱形方块问号乱码

### ISSUE THREAD

**Issue by mrpengfei** [dcloudio/uni-app#1386]
**问题描述**
uni.request 请求网页，返回的数据里汉字为黑色菱形方块问号乱码

**复现步骤**
[复现问题的步骤]
uni.request({
					url: 'http://www.biquge.tv/23_23981/13418739.html',
					method: 'GET',
					success(res) {
						console.log(res.data)
					}
				})

**预期结果**
正确打印网页内容

**实际结果**
![image](https://user-images.githubusercontent.com/5754718/76156420-4a8ae900-6135-11ea-9d7e-a0aa1cc0fed4.png)

**系统信息:**
 - HBuilderX版本 [2.6.1.20200226]

**补充信息**
在uni.request哪里可以设置目标网页的编码格式呢，例如从utf-8变为gbk

**Comment by hbcui1984** [comment]
试试header节点中设置编码，不过`uni.request`一般是请求接口数据的，很少会去请求html网页。

**Comment by dcloudhdx** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
