### ISSUE TITLE
使用命令行工具初始化项目后，样式未生效

### ISSUE THREAD

**Issue by zxzhgk** [dcloudio/uni-app#139]
项目中使用到了SCSS, 在HBuilderX里面正常，看官方文档迁移到使用vue-cl初始化的项目中后，编译后没报任何错误，也生成了对应的.wxss 文件，但是页面样式异常，页面节点没有渲染对应的样式, 项目也安装了对应的node-scss 和 scss-loader，使用官方hello-uniapp 生成项目正常，对比发现官方未使用scss/less等样式预处理库，是否是因为不支持样式预处理导致

**Comment by zxzhgk** [comment]
![微信图片_20190103113940.png](https://upload-images.jianshu.io/upload_images/3356839-e531b07b12486f44.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
![b3ff091b02052eeb8ae1642df5d76b6.png](https://upload-images.jianshu.io/upload_images/3356839-d6ebb0e8fc98ba0d.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
![![df805031b6c04aea89aaa98af98f9ee.png](https://upload-images.jianshu.io/upload_images/3356839-0b572db000e10dc2.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
](https://upload-images.jianshu.io/upload_images/3356839-8bfc74a6b57c7109.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

**Comment by zxzhgk** [comment]
发现是
`<style scoped lang=scss>` 
使用了scoped 会导致这个问题，目前项目去掉scoped 样式会被正常引入，但是样式比例出现异常，然后全局查找替换PX为upx  后比例正常，但是这样修改会导致部分JS中的px 也被替换，希望官方能提供修改转换比例的方式

**Comment by xiaoyucoding** [comment]
scoped 问题已修复，请通过 npm update 升级。

**Comment by zxzhgk** [comment]
> scoped 问题已修复，请通过 npm update 升级。

能麻烦问下px 转rpx/upx 可以在项目的什么位置可以修改，由于目前项目是用px开发的，目前整个项目比例都有问题

**Comment by zxzhgk** [comment]
好的，谢谢啦

**Comment by zxzhgk** [comment]
试了下 无论 "transformPx"  设置为true还是false 项目编译后在开发工具看到的还是px,没有转换成rpx

**Comment by xiaoyucoding** [comment]
> 试了下 无论 "transformPx" 设置为true还是false 项目编译后在开发工具看到的还是px,没有转换成rpx

设置为 false 是不保留 px 单位不进行转化，默认是 true 也就是将 px 作为 rpx 这种动态单位来处理的。

**Comment by xiaoyucoding** [comment]
> 试了下 无论 "transformPx" 设置为true还是false 项目编译后在开发工具看到的还是px,没有转换成rpx

uni-cli 创建时，确认存在此问题。

**Comment by xiaoyucoding** [comment]
> 试了下 无论 "transformPx" 设置为true还是false 项目编译后在开发工具看到的还是px,没有转换成rpx
transformPx 的问题已修复，请通过 npm update 更新。
