### ISSUE TITLE
微信小程序中uni.scss变量在css文件中无法使用

### ISSUE THREAD

**Issue by CrazyChildren** [dcloudio/uni-app#1390]
**问题描述**
为了编程方便，将vue文件<style>标签中的代码剪切到一个新的css文件中，并在vue文件<style>中使用@improt导入了此css文件，uni.scss变量将失效。

**系统信息:**
 - 发行平台: 微信小程序模拟器
 - HBuilderX版本 如使用HBuilderX2.6.1

**Comment by fxy060608** [comment]
uni.scss变量，只在scss文件中生效
