### ISSUE TITLE
第三方微信登录获取到code

### ISSUE THREAD

**Issue by QuiGong** [dcloudio/uni-app#1391]
**新功能描述**
登录中Appsecret可以不填，然后登录的uni.login接口中可以返回code

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by jackluo2012** [comment]
遇到同样的问题，我看官方的api 文档也没有

**Comment by jackluo2012** [comment]
> **新功能描述**
> 登录中Appsecret可以不填，然后登录的uni.login接口中可以返回code
> 
> **现状及问题**
> [当前现状及由此导致的不便]
> 
> **尝试方案**
> [如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]
> 
> **补充信息**
> [其它你认为有参考价值的信息]

你试试
onGotUserInfo(e){			
			uni.getProvider({
				service: 'oauth',
				success: function (res) {
					if (~res.provider.indexOf('weixin')) {
						uni.login({
							provider: 'weixin',
							success: function (loginRes) {
								console.log('登陆code: ',loginRes.code);
								// 获取用户信息
								uni.getUserInfo({
								  provider: 'weixin',
								  success: function (infoRes) {
									  console.log(infoRes);
								    console.log('用户昵称为：' + infoRes.userInfo.nickName);
								  }
								});
							}
						});
					}
				}				
			});
        },
