### ISSUE TITLE
官方能不能提供一个吸顶组件，插件市场的组件兼容性都比较差

### ISSUE THREAD

**Issue by Kole6** [dcloudio/uni-app#1392]
**问题描述**
官方能不能提供一个吸顶组件，插件市场的组件兼容性比较差，用v3编译之后都不能用了

用  js 获取元素top ，性能也跟不上

**系统信息:**
安卓

**Comment by dcloudhdx** [comment]
预计在 HBuilderX 2.6.4 提供一个多选项卡吸顶模板

**Comment by Kole6** [comment]
HBuilderX2.6.5版本有了吗

**Comment by dcloudhdx** [comment]
HBuilderX 2.6.6 已提供，见 Hello uni-app 模板页签
