### ISSUE TITLE
uni app打包H5时打包不了

### ISSUE THREAD

**Issue by xiaofuliang** [dcloudio/uni-app#1393]
使用hbuilder 发行-网站-H5手机版时，提示
[HBuilder] 09:31:07.309 文件查找失败：'uni-view/components/open-data' at ..\..\Program Files\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\vue-cli-plugin-uni-optimize\.tmp\components.js:25

hbuilder版本 2.6.1.20200226

**Comment by fxy060608** [comment]
h5平台不支持open-data组件，建议条件编译一下

**Comment by xiaofuliang** [comment]
> h5平台不支持open-data组件，建议条件编译一下

谢谢了，加了条件编译可以了
