### ISSUE TITLE
升级@vue/cli-plugin-babel至4.2.3,编译后组件的样式文件没有和js文件是空的

### ISSUE THREAD

**Issue by Jonny-china** [dcloudio/uni-app#1394]
**问题描述**
升级@vue/cli-plugin-babel至4.2.3,编译后组件的样式文件没有和js文件是空的

**复现步骤**
[复现问题的步骤]
1.  @vue/cli-plugin-babel 从3.12.1升级至4.2.3

**预期结果**
跟3.12.1一样，可以正常编译组件

**系统信息:**
uni-app v2.6.1
uni-app cli v2.0.0-26120200226001

Environment Info:

  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7300HQ CPU @ 2.50GHz
  Binaries:
    Node: 12.14.0 - ~/.nvm/versions/node/v12.14.0/bin/node
    Yarn: 1.22.0 - ~/.yarn/bin/yarn
    npm: 6.13.7 - ~/.nvm/versions/node/v12.14.0/bin/npm
  Browsers:
    Chrome: 80.0.3987.132
    Firefox: 71.0
    Safari: 13.0.5
  npmPackages:
    @dcloudio/types: 0.4.4 => 0.4.4 
    @dcloudio/uni-app-plus: 2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-cli-shared: 2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-h5: 2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-helper-json: 1.0.5 => 1.0.5 
    @dcloudio/uni-migration: ^2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-mp-alipay: 2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-mp-baidu: 2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-mp-qq: 2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-mp-toutiao: 2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-mp-weixin: 2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-stat: 2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/uni-template-compiler: 2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/vue-cli-plugin-hbuilderx: 2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/vue-cli-plugin-uni: 2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/vue-cli-plugin-uni-optimize: 2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/webpack-uni-mp-loader: 2.0.0-26120200226001 => 2.0.0-26120200226001 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: 2.0.0-26120200226001 => 2.0.0-26120200226001 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  3.12.1 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.2.3 
    @vue/cli-plugin-babel: 3.12.1 => 3.12.1 
    @vue/cli-plugin-eslint: ^4.2.3 => 4.2.3 
    @vue/cli-plugin-router:  4.2.3 
    @vue/cli-plugin-typescript: ^4.2.3 => 4.2.3 
    @vue/cli-plugin-vuex:  4.2.3 
    @vue/cli-service: ^4.2.3 => 4.2.3 
    @vue/cli-shared-utils:  4.2.3 
    @vue/component-compiler-utils:  3.1.0 
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0 
    @vue/eslint-config-typescript: ^5.0.2 => 5.0.2 
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue: ^6.2.2 => 6.2.2 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.11 => 2.6.11 
    vue-class-component: ^7.2.3 => 7.2.3 (7.1.0)
    vue-eslint-parser:  7.0.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.0 (15.9.0)
    vue-property-decorator: ^8.4.0 => 8.4.0 
    vue-router:  3.0.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.1.3 => 3.1.3 
    vuex-module-decorators: ^0.16.1 => 0.16.1

**Comment by rocketxujia** [comment]
遇到相同问题，同问！ 
现象为：执行 npm run dev:mp-weixin 命令时，发现自定义组件对应的js代码仅为
````
Component({})
````
而真正代码被build到页面组件级别的js中了，造成最终小程序打开页面后，自定义组件渲染失败。
