### ISSUE TITLE
App端视频列表中的video播放器脱离位置并无法随页面滚动

### ISSUE THREAD

**Issue by frylstar** [dcloudio/uni-app#1395]
**问题描述**
在app端多栏tab切换长列表内容中的视频会脱离位置，无法跟随列表滚动？（android和ios都会这样）h5端和mp-weixin是没问题的。
[相关社区问题链接：https://ask.dcloud.net.cn/question/84027](https://ask.dcloud.net.cn/question/84027)

**系统信息:**
 - 发行平台: [5+ App]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [2.4.6]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by DoveAz** [comment]
附议

**Comment by dcloudhdx** [comment]
app平台 vue 页面 video 为原生组件，仅支持页面级滚动，如果在<scroll-view> 中使用导致不跟随滚动
