### ISSUE TITLE
自定义事件无法使用回调式传参

### ISSUE THREAD

**Issue by xusidu** [dcloudio/uni-app#1397]
**问题描述**
当v-for循环想把额外的参数传入自定义事件时，自定义事件绑定失效

**复现步骤**
[复现问题的步骤]
<SomeComponent v-for="(item, index) in list" @custom-event="val => customEvent(val, index)" />
这样传入的自定义事件在调用时没有反应

**预期结果**
希望像原始的vue template那样可以让自定义事件传这种回调式传参

**实际结果**
传入的事件没有任何响应

**Comment by 271293794** [comment]
事件好像不是你这样绑定的，你都没有触发，this.$emit(`custom-event`)都没有用。
