### ISSUE TITLE
ts下中getFileSystemManager检查错误

### ISSUE THREAD

**Issue by Iongtao** [dcloudio/uni-app#1399]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
uni-app在typescript环境下出现检查错误
----类型“Uni”上不存在属性“getFileSystemManager”----

**实际结果**
![image](https://user-images.githubusercontent.com/24762616/76480935-1708d100-644b-11ea-863a-f41585168269.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 macos
 - uni-app版本^2.0.0-26120200226001
 - 设备信息 微信开发者工具

**Comment by zhetengbiji** [comment]
先用wx.
