### ISSUE TITLE
var(--status-bar-height)不起作用

### ISSUE THREAD

**Issue by magicsgxie** [dcloudio/uni-app#14]
<template>
	<view class="index">
        <view class="status">
            <view class="top_view"></view>
        </view>
        <view class="content"> Hello </view>
    </view>
</template>

<script>
	export default {
		
	}
</script>

<style>
  .index {
        flex: 1;
        flex-direction: column;
    }
    .status {
        height: var(--status-bar-height);
        width: 100%;
    }
	.top_view{
        height: var(--status-bar-height);
        width: 100%;
        position: fixed;
        top: 0;
    }
    .content{
        justify-content: center;
        align-items: center;
    }
</style>
	"globalStyle": {
		"navigationStyle": "custom"
	},
这里已经开启了
在andriod 6.0的手机上不起作用？这个是不是BUG，还是不支持

**Comment by xiaoyucoding** [comment]
首先检查下 HBuilderX 版本是否已顺利升级至 20180810 版，请前往[问答社区](https://ask.dcloud.net.cn/explore/)单独发帖详细说明问题，并上传可以重现问题的示例项目。

**Comment by Zhjoker** [comment]
@magicsgxie 你的问题解决了吗  

·<template name="page-head">
	<view class="page-head">
		<view class=" status top-view"></view>
	</view>
</template>

<script>
	export default {
		name: "page-head",
		props: {
			title: {
				type: String,
				default: ""
			}
		}
	}
</script>
<style>
	.page-head{
		height:calc(var(--status-bar-height) + 88px);
		background-color: #007AFF;
	}
	.top-view{
		width: 100%;
		position: fixed;
		top: 0;
	}
	.status{
		height:var(--status-bar-height);
	}
</style>·

**Comment by Zhjoker** [comment]
版本 0905

**Comment by Zhjoker** [comment]
Android7.1.1

**Comment by Zhjoker** [comment]
@xiaoyucoding

**Comment by hbcui1984** [comment]
@Zhjoker 

建议通过微信开发者工具，去调试一下css定义，确认是css变量值未生效，还是flex布局错乱。

**Comment by hbcui1984** [comment]
issue超过1个月不回应，暂时关闭，若继续有问题，可以重开或发新issues
