### ISSUE TITLE
支付宝小程序特有的组件需要在相应的json文件里配置usingComponents，怎么实现？

### ISSUE THREAD

**Issue by huchun666** [dcloudio/uni-app#140]

**Comment by huchun666** [comment]
"usingComponents": {
    "list": "mini-antui/es/list/index",
    "list-item": "mini-antui/es/list/list-item/index",
    "input-item": "mini-antui/es/input-item/index",
    "picker-item": "mini-antui/es/picker-item/index",
    "modal": "mini-antui/es/modal/index"
  }

**Comment by huchun666** [comment]
`"usingComponents": {
"list": "mini-antui/es/list/index",
"list-item": "mini-antui/es/list/list-item/index",
"input-item": "mini-antui/es/input-item/index",
"picker-item": "mini-antui/es/picker-item/index",
"modal": "mini-antui/es/modal/index"
}`

**Comment by huchun666** [comment]
比如上面的配置

**Comment by xiaoyucoding** [comment]
usingComponents 的配置在 page->style 下，详见文档：[小程序组件支持](https://uniapp.dcloud.io/frame?id=%E5%B0%8F%E7%A8%8B%E5%BA%8F%E7%BB%84%E4%BB%B6%E6%94%AF%E6%8C%81)
