### ISSUE TITLE
期望uni.share支持钉钉分享

### ISSUE THREAD

**Issue by jaylin0522** [dcloudio/uni-app#1403]
**新功能描述**
期望uni.share支持钉钉分享

**现状及问题**
uni.share仅支持微信、qq、微博分享

**尝试方案**
编译器版本 2.6.1 有尝试过uni.shareWithSystem，但是方法undefined，不可用
有尝试过plus.share.sendWithSystem原生分享，能用但不美观

**补充信息**
[其它你认为有参考价值的信息]

**Comment by ArrayDC** [comment]
建议使用uni原生插件扩展，参考：https://nativesupport.dcloud.net.cn/NativePlugin/README
