### ISSUE TITLE
web-view 内嵌html 中返回app首页 真机调试ok，打包后手机上不ok

### ISSUE THREAD

**Issue by rhzqjqdywhjx** [dcloudio/uni-app#1404]
![image](https://user-images.githubusercontent.com/40160329/76503316-a381b680-6480-11ea-9e12-5c8fd6abdb8b.png)

**Comment by Wangyaqi** [comment]
你的项目目录结构是什么样的，或者你直接把demo发来我试一下

**Comment by rhzqjqdywhjx** [comment]
![image](https://user-images.githubusercontent.com/40160329/76505611-bd24fd00-6484-11ea-9fab-f162af5bb70b.png)

**Comment by rhzqjqdywhjx** [comment]
help中web-view 包含一个上线网站首页

**Comment by dcloudhdx** [comment]
请提供一个简单测试工程
