### ISSUE TITLE
h5模式下，浏览器访问按F5刷新页面，url参数会丢失

### ISSUE THREAD

**Issue by xlkit456852** [dcloudio/uni-app#1408]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动项目
2. 浏览器输入http://localhost:8080/#/pages/project/edit?type=add
3. 按F5刷新页面，url会变成http://localhost:8080/#/pages/project/edit

**预期结果**
url参数不会丢失

**实际结果**
url参数丢失了

**系统信息:**
 - 发行平台: [h5]
 - 操作系统 [win10]
 - HBuilderX版本 [2.6.1]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [谷歌浏览器]

**补充信息**
暂无

**Comment by 271293794** [comment]
![img](https://dyh-1254206153.cos.ap-chengdu.myqcloud.com/img/%E5%8E%9F%E5%9E%8B%E4%B8%8A%E6%B7%BB%E5%8A%A0%E5%B1%9E%E6%80%A7.gif)我不是cli创建的，查询参数没有丢

**Comment by 271293794** [comment]
https://dyh-1254206153.cos.ap-chengdu.myqcloud.com/img/%E5%8E%9F%E5%9E%8B%E4%B8%8A%E6%B7%BB%E5%8A%A0%E5%B1%9E%E6%80%A7.gif 图片没有显完

**Comment by weixisheng** [comment]
没有解决方案么

**Comment by dcloudhdx** [comment]
无法复现问题，请提供测试工程或在线地址

**Comment by ChanKingBooo** [comment]
> 无法复现问题，请提供测试工程或在线地址

https://hellouniapp.dcloud.net.cn/pages/API/navigator/new-page/new-vue-page-1?data=Hello 浏览器地址栏输入然后回车，?后的内容丢失

**Comment by ZhangJiaLei123** [comment]
2023年8月31日, 这个问题依旧存在, 复现:
