### ISSUE TITLE
在app端choosevideo 在小米8 vivo手机上无法从相册选择视频也无法上传

### ISSUE THREAD

**Issue by pullgo** [dcloudio/uni-app#1410]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
第一次点击上传可以唤起相册或者摄像头  选择相册-在到视频 之后就返回到上传界面  视频选择上了
 但是不上传   第二次在点击上传 可以唤起相册与摄像头 在点击相册 无反应  第三次点击相册摄像头都换不起  

我直接运行官方的示例代码也是一样的效果  测试手机是小米8
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
帖子：https://ask.dcloud.net.cn/question/67479?item_id=116113&rf=false 
  以及我发的视频 https://www.99spapp.com/choosevideoBug.mp4
**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [App等]
 - 操作系统 
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号2.5.6]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]
[如小米8 、Android 8.0  vivoX20 plusA]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by hbcui1984** [comment]
该问题已修复，详见：https://ask.dcloud.net.cn/question/67479
