### ISSUE TITLE
自定义的组件在微信小程序端运行时报错

### ISSUE THREAD

**Issue by yue00xl** [dcloudio/uni-app#1411]
**问题描述**
components 中新建的组件,  如果缺少 <script></script>标签， 在微信小程序端运行报错

**复现步骤**
[复现问题的步骤]
1.  新建组件， 如果组件中没有<script></script>

2、npm run dev:mp-weixin

3、导入微信开发工具中报错 

Component is not found in path "components/uni-demo/uni-demo" (using by "pages/index/index");onAppRoute
Error: Component is not found in path "components/uni-demo/uni-demo" (using by "pages/index/index")

**预期结果**
正常运行

**实际结果**
报错

**补充信息**

**Comment by dcloudhdx** [comment]
HBuilderX 2.6.6+ 已修复
