### ISSUE TITLE
nvue App端，picker组件日期选择，android端太丑，使用起来太不方便

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-app#1413]
nvue App端，picker组件日期选择，android端太丑，使用起来太不方便。建议改成类似ios端端picker滚动样式

**Comment by zhetengbiji** [comment]
使用最新alpha版，设置一下fields

**Comment by liulb** [comment]
> 使用最新alpha版，设置一下fields即可

我用的是Hbuilder X 2.6.5，确实那个日期效果，在安卓下很难用，年份那个地方，很多人不知道可以点。具体是给picker组件 加入 fields 参数？值呢，fields="month 吗？

**Comment by zhetengbiji** [comment]
> > 使用最新alpha版，设置一下fields即可
> 
> 我用的是Hbuilder X 2.6.5，确实那个日期效果，在安卓下很难用，年份那个地方，很多人不知道可以点。具体是给picker组件 加入 fields 参数？值呢，fields="month 吗？

传入文档里允许的合理值即可
