### ISSUE TITLE
获取WiFi信息的组件能不能加上获取WiFiSSID的返回值

### ISSUE THREAD

**Issue by AnkerLeng** [dcloudio/uni-app#1414]
**新功能描述**
获取WiFi信息的组件能不能加上获取WiFiSSID的返回值

**现状及问题**

**尝试方案**

**补充信息**

**Comment by AnkerLeng** [comment]
如何调用原生接口呢

**Comment by ArrayDC** [comment]
请使用uni原生插件扩展，也可以在插件市场 https://ext.dcloud.net.cn/ 搜索是否已经存在满足需求的插件
