### ISSUE TITLE
uniapp下，v-for 迭代数字 下标有时候从0开始，有时候从1开始。

### ISSUE THREAD

**Issue by liulb** [dcloudio/uni-app#1415]
v-for 迭代数字

`<view  v-for="count in 10">`

count的值 在2.4.6下 是从0开始 

count的值 在2.5.1 及之后的版本下是从1开始 

我了解了一下vue语法下，这个count应该是从1开始的才对。为什么会出现两种情况？

**Comment by dcloudhdx** [comment]
因其他平台的差异，V3 从1开始建议判断 index `v-for="(item, index) in 10"`
参考文档
```
https://uniapp.dcloud.io/use?id=%e6%b3%a8%e6%84%8f%e4%ba%8b%e9%a1%b9
```
