### ISSUE TITLE
page-meta 建议放在与 template script style 同级。

### ISSUE THREAD

**Issue by hminghe** [dcloudio/uni-app#1416]
**新功能描述**
简洁描述你希望补充完善的增强功能
page-meta 建议放在与 template script style 同级，而不是放在template

**现状及问题**
[当前现状及由此导致的不便]
放在template里失去了vue的标准， template里只能一个最高级的节点

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]
page-meta 建议放在与 template script style 同级

**补充信息**
[其它你认为有参考价值的信息]
最后文件格式如下
```vue
<page-meta></page-meta>
<template></template>
<script></script>
<style></style>
```

可以参考vue-loader的自定块
https://vue-loader.vuejs.org/zh/guide/custom-blocks.html#example

**Comment by fxy060608** [comment]
vue3 将会支持多节点，而且page-meta是一个组件概念，绑定数据，事件都与其他的组件类似，单独放置，似乎也不太合理
