### ISSUE TITLE
picker 多列选择代码缺陷

### ISSUE THREAD

**Issue by Mr-JCG** [dcloudio/uni-app#1422]
picker 多列选择组件  不指定value报错

valueSync: this.value || 0
var val = this.valueSync
valueArray = [...val]

![image](https://user-images.githubusercontent.com/36749957/76730637-9c1b1f80-6796-11ea-9e52-26862495e985.png)

**Comment by zhetengbiji** [comment]
fixed at [9ccd8f](https://github.com/dcloudio/uni-app/commit/9ccd8f640e84ee513ad20e2db43b14810534486a)

**Comment by dcloudhdx** [comment]
HBuilderX 2.6.7+ 已修复
