### ISSUE TITLE
Andriod启动图片变形

### ISSUE THREAD

**Issue by Kole6** [dcloudio/uni-app#1423]
**问题描述**
现在的全面屏手机都很长，比如19年之后出来的oppo vivo手机，屏幕尺寸是 20:9，配置提供的三种比例过小

![image](https://user-images.githubusercontent.com/29592422/76742446-0f7b5c00-67ac-11ea-8af9-ee82f48887e5.png)

**Comment by dcloudhdx** [comment]
推荐使用 .9解决
