### ISSUE TITLE
关于typescript下 uni.createIntersectionObserver()实例属性方法relativeToViewport()传参问题

### ISSUE THREAD

**Issue by Iongtao** [dcloudio/uni-app#1428]
**问题描述**
typescript下 uni.createIntersectionObserver()实例属性方法relativeToViewport()参数类型是margins: any[]
![image](https://user-images.githubusercontent.com/24762616/76843693-1b802000-6877-11ea-85f0-5a0bb51607ce.png)
我想设置窗口下100px的距离触发效果，但是不知道如何填写这个参数，官网上搜索不到解决方案
relativeToViewport([{bottom: 100}])
无效果

**预期结果**
微信的参数是这样的
relativeToViewport({bottom: 100})

**实际结果**
relativeToViewport([{bottom: 100}]) 无效

请求解决

**Comment by Iongtao** [comment]
relativeToViewport([0, 0, 100, 0}]) 也无效

**Comment by Iongtao** [comment]
我尝试用了对象 结果功能是正常的

**Comment by zhetengbiji** [comment]
更新 @dcloudio/types 到 0.4.7
