### ISSUE TITLE
showToast H5无法显示

### ISSUE THREAD

**Issue by unlock-lee** [dcloudio/uni-app#1430]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
uni.showToast H5编译执行如下代码后[system] Not Found：Page[4] 

**复现步骤**
[复现问题的步骤]
https://github.com/LeeChang-GitHub/uniapp_showToast_test

**预期结果**
微信 APP  H5内置浏览器显示showToast信息

**实际结果**
微信 APP 可以显示showToast信息，但HBuilder H5内置浏览器无显示

**系统信息:**
 - 发行平台: 微信小程序 APP H5
 - 操作系统 windows 10
 - HBuilderX版本 2.6.1.20200226
 - uni-app版本 
 - 设备信息 HUAWEI P20 安卓9

**Comment by fxy060608** [comment]
临时解决方案：
showToast之后，延迟reLaunch
```
setTimeout(() => {
                        uni.reLaunch({
                            url: '../main/start',
                        })
                    }, 200)
```

**Comment by LeeChang-GitHub** [comment]
setTimeout是可以的，同时showToast设置了duratio以后内置浏览器 console  warn提示是否不合理？
  [system] 请注意 showToast 与 hideToast 必须配对使用
