### ISSUE TITLE
dev开发中，wxcomponents目录貌似不会编译到dist目录下

### ISSUE THREAD

**Issue by jameslahm** [dcloudio/uni-app#1432]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by jameslahm** [comment]
抱歉 已解决

**Comment by wangQiaoBrother** [comment]
您好 怎么解决的 我现在是wxcomponents文件里面引用了外部的js 开发运行的时候 wxcomponents里面的文件获取不到外部js路径

**Comment by jameslahm** [comment]
我的貌似是因为hot reload时不会编译新的文件夹 因为我原本是没有wxComponents目录的 这个目录是我后面新加的
您现在是怎么引用外部js文件的呢？
![1](https://user-images.githubusercontent.com/43805318/78017276-9b7dae00-737e-11ea-9615-fa983fa64193.jpg)
（这里有官方的引用方法

**Comment by wangQiaoBrother** [comment]
wxcomponents里面 我也是官方这样引用的 但是运行到微信开发工具 wxcomponents就报找不到引用的js

**Comment by jameslahm** [comment]
您dist目录下有您引用的js文件吗？能看一下微信开发者工具的目录吗？
