### ISSUE TITLE
原生微信小程序可以通过hbuilder转换成h5，其他小程序和安卓，iosapp吗？

### ISSUE THREAD

**Issue by ymmagic** [dcloudio/uni-app#1434]
原生微信小程序可以通过hbuilder转换成h5，其他小程序和安卓，ios app吗？

**Comment by hbcui1984** [comment]
- 微信小程序转换uni-app指南及转换器：https://ask.dcloud.net.cn/article/35786
- vue h5项目转换uni-app指南：https://ask.dcloud.net.cn/article/36174
