### ISSUE TITLE
不支持全局引入小程序组件

### ISSUE THREAD

**Issue by ranwawa** [dcloudio/uni-app#144]
- 在小程序的`app.json`中可以使用`usingComponents`全局引用组件
- 这样在所有页面中就可以直接使用了

但是`univue`不支持.在`globalStyle`中配置后,页面引入不生效
```
...
"globalStyle": {
   ...
    "usingComponents": {
      "van-button": "/wx_components/button/index"
    }
```

**Comment by hbcui1984** [comment]
下版更新将支持。

不过支付宝小程序不支持全局组件，uni-app编译器做了兼容处理，当页面使用了全局组件，自动在该页面生成 usingComponents 配置

**Comment by xiaoyucoding** [comment]
HBuilderX 1.5 版本已发布，请更新。
如果是通过 cli 创建的项目，请通过 npm update 更新依赖。

**Comment by chen-can** [comment]
目前最新版只支持微信小程序的全局引入 我测试了支付宝小程序还不支持
