### ISSUE TITLE
uniapp 分包优化，将两个不同的分包vendor打包到了一起

### ISSUE THREAD

**Issue by loveonelong** [dcloudio/uni-app#1440]
**问题描述**

uniapp 开启分包优化后，将两个不同的分包vendor打包到了一起
```
    "optimization": {
      "subPackages": true
    }
```
这两个包，目录命名分别为
- pages-me
- pages-messager

但是pages-messager里面却引用了pages-me的common/vendor.js。
pages-messager里面却没有自己独立的vendor.js
经排查，两个分包的代码之间并没有引用关系，不知道为何开启优化后会这样。

**Comment by huadong** [comment]
碰到类似问题：
分包A：
>packages/subA/index.vue
引入
import util '../../utils/subA/test.js

分包B:
>packages/subB/index.vue
引入
import util '../../utils/subA/test'

这时候会出现上述问题。
如果把分包packages/subA改名packages/**subAA**，则不会有问题。

估计是优化时候：../../utils/subA/test和packages/subA有什么bug。

**Comment by loveonelong** [comment]
@fxy060608  麻烦看一下这个bug

**Comment by loveonelong** [comment]
这个bug的fixed会在哪个版本发布？

**Comment by zhetengbiji** [comment]
2.6.12及以上的版本已经包含
