### ISSUE TITLE
uniCloud.httpclient.request或者是不是基于axios或者fly的封装？

### ISSUE THREAD

**Issue by hugetiny** [dcloudio/uni-app#1441]
**新功能描述**
uniCloud.httpclient.request或者是不是基于axios或者fly的封装？

**现状及问题**
如果unicloud是标准node环境的话，是不是没必要弄一个uniCloud.httpclient？自己拿axios或者fly去请求不就行了？

**Comment by hugetiny** [comment]
如果后期支持函数打包上传的话，是不是没必要uniCloud.httpclient 因为服务端不存在小程序之类的兼容性问题

**Comment by Wangyaqi** [comment]
uniCloud.httpclient.request是运行在云端的代码，跟客户端没有关系，封装的是urllib
