### ISSUE TITLE
uni-swipe-action组件内使用uni-list时在支付宝小程序报错"list" not found

### ISSUE THREAD

**Issue by CaoMeiYouRen** [dcloudio/uni-app#1444]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
uni-swipe-action组件内使用uni-list时在支付宝小程序报错
具体报错如下
[Vue warn]: Injection "list" not found
found in
---> /components/uni-list-item/uni-list-item
       <Root>
vendor.js:8191 TypeError: Cannot read property 'firstChildAppend' of undefined
    at VueComponent.mounted (uni-list-item.js:264)

**复现步骤**
[复现问题的步骤]
1. 创建一个空项目
2. 从插件市场下载uni-swipe-action、uni-list
3. demo如下
```
<template>
	<view class="content">
		<uni-swipe-action>
		    <uni-swipe-action-item :options="options">
		        <uni-list class="list">
		            <uni-list-item  class="item" :title="title" :note="note" :show-arrow="false" ></uni-list-item>
		        </uni-list>
		    </uni-swipe-action-item>
		</uni-swipe-action>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				title: 'Hello 这是一个测试标题',
                note:'这是一段测试简介',
                options: [
                {
                    text: '取消',
                    style: {
                        backgroundColor: '#007aff'
                    }
                },
                {
                    text: '删除',
                    style: {
                        backgroundColor: '#dd524d'
                    }
                }
            ]
			}
		},
		onLoad() {

		},
		methods: {

		}
	}
</script>

<style>
	.content{
        margin-top: 100rpx;//顺便还存在定位出错的问题
    }
</style>

```
4. 运行到支付宝小程序开发者工具
**预期结果**
至少不报错。具体样式可以暂时不管

**实际结果**
[这里请贴上你的报错截图或文字]
[Vue warn]: Injection "list" not found
found in
---> /components/uni-list-item/uni-list-item
       <Root>
vendor.js:8191 TypeError: Cannot read property 'firstChildAppend' of undefined
    at VueComponent.mounted (uni-list-item.js:264)

**系统信息:**
 - 发行平台:支付宝小程序【其他平台 H5、Android、微信、QQ均通过】
 - 操作系统：支付宝小程序开发者工具 1.5.10
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
2.6.5.20200314
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
我看了下uni-list的源代码，感觉没有问题，并且 支付宝小程序开发者工具 中也找不到 list 标签。所以这个问题有点迷惑

**Comment by dcloudhdx** [comment]
用真机试试，支付宝的模拟器有Bug

**Comment by TangWenZERO** [comment]
其实看了，跟任何都没有关系，就是单纯的uniapp在飞书小程序里面根本就没有这个组件。

**Comment by TangWenZERO** [comment]
你可以到https://uniapp.dcloud.net.cn/ 官网扫他们的飞书小程序，然后在手机端看看，里面有支持的组件，里面并不包含uni-swipe-action，。。。。。。。
