### ISSUE TITLE
unicloud中node_modules整个上传太不合理了

### ISSUE THREAD

**Issue by hugetiny** [dcloudio/uni-app#1445]
**新功能描述**
希望官方能有云函数压缩上传的方式提供

**现状及问题**
unicloud中node_modules整个上传太不合理了
引用一些库后node_modules很容易超过10m的上限
官方的案例中rollup并不能webpack那样打包所需要的控制大小.

**尝试方案**
现在用webpack手动打包再上传有些问题，db插不进数据，不知道为什么

**Comment by hugetiny** [comment]
云函数还不支持本地调试，这点也不太方便

**Comment by Wangyaqi** [comment]
阿里云正在完善，后续会提供云端安装依赖功能

**Comment by hugetiny** [comment]
阿里云本身支持所有文件压缩为zip上传 不知道unicloud这个支持不支持

**Comment by hugetiny** [comment]
我觉得阿里云本身不支持在线安装的话，本地webpack打包压缩成单个文件可能是最好选择

**Comment by Wangyaqi** [comment]
插件市场有用rollup处理的[https://ext.dcloud.net.cn/plugin?id=1268](https://ext.dcloud.net.cn/plugin?id=1268)，但是还是云端安装依赖更合理一些，阿里也正在做这方面的支持

**Comment by Wangyaqi** [comment]
> 云函数还不支持本地调试，这点也不太方便

3.0.0版本起已支持客户端直连本地云函数进行调试，但是暂不支持断点
