### ISSUE TITLE
是否支持使用sass或者less

### ISSUE THREAD

**Issue by NextBoy** [dcloudio/uni-app#145]

**Comment by ranwawa** [comment]
支持的啊.........自己装组件

**Comment by NextBoy** [comment]
@ranwawa 通过vue-cli生成的项目，并没有暴露相关的webpack配置，我怎么装？。。。

**Comment by zxzhgk** [comment]
直接 npm install 对应的包就可以啊，会自动添加到项目的package.json里面的  ，但是目前使用样式预编译的不支持官方的条件编译，得等他们后续支持

**Comment by xiaoyucoding** [comment]
## 预编译语言的支持
检测到使用了 sass/scss、less 等预编译语言但未安装相关依赖，则会有提示信息缺少 XXX 模块。
按照提示信息安装相关模块即可，例如：
```
$ npm install node-sass sass-loader --save-dev
```
目前支持的预编译语言有：

* sass/scss
* less
* stylus
* pug
## 预编译语言中条件编译
最新版的 cli 已经支持在预编译语言中使用条件编译，但是注意注释的格式。
### 有效写法
```csss
/* #ifdef APP-PLUS */
.text {
    color: #FF3333
}
/* #endif */
```
### 无效写法
```csss
// #ifdef APP-PLUS
.text {
    color: #FF3333
}
// #endif
```

**Comment by NextBoy** [comment]
@xiaoyucoding 没有暴露相关的webpack配置，那我如何注入全局样式文件？有一些公共的全局变量，我并不希望每次都去import, 按照原来的web项目，是可以配置全局注入的，而且一些第三方的插件是不是也就没法用了？因为没有webpack配置

**Comment by fxy060608** [comment]
1.src/uni.scss会自动导入
2.如果要个性化配置，参考https://cli.vuejs.org/zh/config/#vue-config-js
