### ISSUE TITLE
巨大特大建议

### ISSUE THREAD

**Issue by Laney911** [dcloudio/uni-app#1452]
既然你们能发展这样的，技术肯定是有的。但是uniapp开发体验效果并不理想。

所以给你们就一个特大建议：

开发调试时候不要再编译渲染这样低级操作了。
应该原生渲染，就像微信小程序开发工具那样，虽然我知道他们也是编译，但是人家做出来接近原生渲染的那种速度，很快，而你们的编译器编译的时候问题很严重，常常出现莫名其妙问题。开发你们的uniapp感觉教程知识杂乱，出现的问题也很杂乱，开发体验很不好。
还有一个就是你们编辑器基本无用，什么语法提示VUE语法，这些都是浮云好不好。
你们HX编辑器，首先布局欠缺一点，应该重新布局，对于15.6寸笔记本显示器来说，浪费了很多画面，尽可能做到像微信小程序那样的布局是最好，或者其他优秀布局，对于你们的编译控制台占用那么大空间，对15.6寸屏幕来说不好，没必要，还有就是字体大小虽然都可调，但是你们做出的空隙很大方，但没体现出你们编辑器有多么高大上，反而累赘，建议有个页面的参数可调并保存配置，每次打开编辑器加载一次就可以了，参数常驻内存就行。。。。。。。我用你们编辑器真的很无语。。。。。。。。。还有很多开发体验建议，如果们愿意听，我就继续提建议，如果不愿意改变。那就当我没说。

**Comment by ouzhou** [comment]
1技术上很难实现，毕竟微信开发工具在管制
2提供了cli可不用官方的编辑器 爱用不用

感觉你是无知 ，什么叫巨大特大，什么叫

> 如果们愿意听，我就继续提建议，如果不愿意改变。那就当我没说

很难理解，你又不给钱，又不提供pr
如果你是老板，这样说手下人 ，他们肯定会听你的，因为你是老板你发工资
但是你不是，那你就是瞎bb

**Comment by Laney911** [comment]
你谁啊，有没看清楚啊，就在瞎BB啊

**Comment by Laney911** [comment]
我的意思很简单
第一改变hx布局，尽可能优化
第二让内置浏览器更能原生渲染，而不是改变标签在渲染。

微信管制跟我说的有毛关系啊，还不是要转换成微信小程序运行，这个符合不就行了吗。


你到底在瞎BB神马啊

**Comment by Laney911** [comment]
你瞎BB什么，真搞不懂！！！！原生渲染跟微信小城开发者工具，到底有什么关系？

难道不用转编译成微信小程序？

**Comment by ouzhou** [comment]
素质堪忧

**Comment by Laney911** [comment]
有时候不就如此吗，巨大特大不是让你看废话
，是想让官方看到，建议也不也是如此吗。

是你素质有问题，别喷别人好不好

**Comment by Laney911** [comment]
有事说事，你别BB就行

**Comment by ouzhou** [comment]
担心你看不懂特意给你找了一份中文版的
[提问的智慧](https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way/blob/master/README-zh_CN.md)

![image](https://user-images.githubusercontent.com/7693866/77814669-40ce2300-70ee-11ea-9594-a98c01511b92.png)
![image](https://user-images.githubusercontent.com/7693866/77814687-72df8500-70ee-11ea-8485-b0ce9b6098bb.png)

**Comment by Laney911** [comment]
哦  ，你能看懂你去看不就得了嘛，关键你能看懂吗，

我看不看得懂跟你没关系，起码我能看懂大意英文，不劳你费心。
