### ISSUE TITLE
uniCloud.callFunction怎么手动终止

### ISSUE THREAD

**Issue by hugetiny** [dcloudio/uni-app#1453]
**新功能描述**
uniCloud.callFunction怎么终止

**现状及问题**
第二个请求的时候我想终止第一个请求

**Comment by hugetiny** [comment]
类似axios的interceptors的功能

**Comment by Wangyaqi** [comment]
目前不支持，可以给请求加一个标志，不终止前面一个但是舍弃前面一个的结果
