### ISSUE TITLE
map组件的marker属性的label属性没有z-index属性，label不能置于marker只上。

### ISSUE THREAD

**Issue by AAZero** [dcloudio/uni-app#1454]
map组件的marker属性的label属性没有z-index属性，label不能置于marker只上。
然后我在代码里面看了一下，没找到map组件源码，能否告诉我map源码路径，我给扩展一个z-index属性。

**Comment by AAZero** [comment]
另外，刚才发现一个doc的bug，就是map组件的marker属性的label属性的x，y属性不是Number类型的，是String类型的，例如：‘10px’。我已经提交了修改，请尽快更新doc。

**Comment by zhetengbiji** [comment]
你指的是哪端？

**Comment by AAZero** [comment]
H5

**Comment by zhetengbiji** [comment]
> H5

map的实现在此位置：https://github.com/dcloudio/uni-app/blob/dev/src/platforms/h5/view/components/map/index.vue
另外单独修改H5端不太好，需要考虑和其他端是否表现一致？或者说其他端是否有类似设置

**Comment by AAZero** [comment]
源码这个project怎么跑起来？npm install之后npm run dev:h5，报错。

**Comment by AAZero** [comment]
想调试一下

**Comment by zhetengbiji** [comment]
> 源码这个project怎么跑起来？npm install之后npm run dev:h5，报错。

改用 yanr 初始化 npm 依赖
仍然是执行 npm run dev:h5
将输出文件内容替换到cli项目或者HBuilderX下对应的包（uni-h5）内

**Comment by AAZero** [comment]
将输出文件内容替换到cli项目或者HBuilderX下对应的包（uni-h5）内
---------------------------------------------------------------------------
对应的包是指什么包？
运行为h5的时候，跟小程序不一样，并没有在unpackage下生成包

**Comment by zhetengbiji** [comment]
> ## 将输出文件内容替换到cli项目或者HBuilderX下对应的包（uni-h5）内
> 对应的包是指什么包？
> 运行为h5的时候，跟小程序不一样，并没有在unpackage下生成包

替换 @dcloudio/uni-h5 中的
