### ISSUE TITLE
问一下uni-page-body不设置height 100%的原因

### ISSUE THREAD

**Issue by star7th** [dcloudio/uni-app#1457]
**问题描述**

比如说在页面内容撑不起高度到全屏的时候，我必须设置全屏。此时将高度设置为100% 。但是元素的高度100%是跟父元素的高度有关的。父元素没有设置100%的话无法继承。我发现html标签`<uni-page-body></uni-page-body>`没有设置height 100% /这导致我组件里的元素设置height 100%的时候依然无法填充整个页面。

**Comment by mayday5555** [comment]
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/13862901/176403048-32bb9479-464f-4299-9a12-552892ae5cf1.png">
