### ISSUE TITLE
picker在微信小程序下正常，编译成h5就出错，system] TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by myfengstyle** [dcloudio/uni-app#1459]
`<view class="flex-row line">
				<view class="line-title">预约部门{{ department[1].id }}</view>

				<picker @change="bindDeptChange" class="picker" name="department" :range="department" :rangeKey="'name'" mode="selector" :value="department[dept_index].id">
					<view class="unselected" v-if="dept_index == null">请选择预约部门</view>
					<view class="picker-value">{{ department[dept_index].name }}</view>
				</picker>

				<view class="arrow-right"></view>
			</view>`

在h5下面提示‘system] TypeError: Cannot read property 'id' of undefined’，h5下整个页面空白

**Comment by zhetengbiji** [comment]
检查你的 department[1] 是否为 undefined

**Comment by hbcui1984** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
