### ISSUE TITLE
使用组件遇到微信小程序和H5表现不一致的问题

### ISSUE THREAD

**Issue by d0apga** [dcloudio/uni-app#146]
在尝试使用uniapp将几个有赞的组件改写成vue格式的组件后，发现了下面两个问题：
- 在微信小程序端，vue组件共用了页面的数据： 第一个问号那一栏不应该显示Hello，这个Hello是定义在页面的数据里面，并没有传值给组件
- 一些组件的内容不显示：用户名那一栏传递了icon属性，在H5端图标显示正常，微信小程序端未显示图标

详情见图对比：
小程序：
![bug](https://user-images.githubusercontent.com/1168900/50745616-2c420880-1266-11e9-89b8-99ccbefeda0f.png)
H5：
![bug](https://user-images.githubusercontent.com/1168900/50745617-2c420880-1266-11e9-8dc5-2fb284393d95.png)
附源码：
[uniapp-demo.zip](https://github.com/dcloudio/uni-app/files/2731199/uniapp-demo.zip)

**Comment by d0apga** [comment]
进度有更新吗？

**Comment by xiaoyucoding** [comment]
目前看来，是 title 这个字段和组件内部的 title 重名了。
目前的架构下，的确会存在此类问题，后续会优化升级转换成标准的小程序规范的自定义组件，就不会有此类问题了。
目前的解决办法，只能是尽可能自己避免这种重名的情况。

**Comment by d0apga** [comment]
好的，那图标的问题呢

**Comment by xiaoyucoding** [comment]
> 好的，那图标的问题呢

后面优化，请关注更新日志或社区公告。

**Comment by xiaoyucoding** [comment]
微信小程序端做了重大优化，详见：[微信小程序端性能翻倍](https://ask.dcloud.net.cn/article/35699)
