### ISSUE TITLE
子组件Props的默认值在父组件传递undefined的时候不会被覆盖，但是小程序中被覆盖成null

### ISSUE THREAD

**Issue by dying318** [dcloudio/uni-app#1460]
**问题描述**
子组件Props的默认值在父组件传递undefined的时候不会被覆盖，但是小程序中被覆盖成null

**复现步骤**
`
            pickerKey: {
                value: Object,
                default() {
                    return {
                        value: 'value',
                        label: 'label',
                        children: 'children'
                    }
                }
            },
// 调用：
:picker-key="type =='undefined"
`

**预期结果**
子组件使用pickerKey默认值

**实际结果**
子组件显示pickerKey为null

**系统信息:**
 - 发行平台: 微信小程序

**Comment by zhetengbiji** [comment]
小程序端不支持更新数据的值为 undefined，框架内部将会替换为 null，需要自行绕过一下，后续将在文档内增加相关注意事项。

**Comment by leeviok** [comment]
> 小程序端不支持更新数据的值为 undefined，框架内部将会替换为 null，需要自行绕过一下，后续将在文档内增加相关注意事项。

如果没有设置default，替换成null没有问题，但如果有default，不是应该用default值吗

**Comment by zhetengbiji** [comment]
> > 小程序端不支持更新数据的值为 undefined，框架内部将会替换为 null，需要自行绕过一下，后续将在文档内增加相关注意事项。
> 
> 如果没有设置default，替换成null没有问题，但如果有default，不是应该用default值吗

此问题已处理结束，其他问题单独讨论
