### ISSUE TITLE
希望增强报错提示

### ISSUE THREAD

**Issue by liaohui5** [dcloudio/uni-app#1461]
**新功能描述**
希望对下图这样的报错,增加更友好的提示,这样的报错, 虽然不影响程序运行, 但是根本找不到在哪?

**现状及问题**
![image](https://user-images.githubusercontent.com/29266093/77296254-5b854e00-6d22-11ea-876a-aba10d6a198a.png)
 

**补充信息**
![image](https://user-images.githubusercontent.com/29266093/77296416-98514500-6d22-11ea-8f25-2d351d2c8fa9.png)

**Comment by dcloudhdx** [comment]
更新 HBuilderX 2.8.0 alpha + 已优化错误提示
