### ISSUE TITLE
uni.openLocation 这个API，在IOS 端打开地图后，返回按钮执行了两次

### ISSUE THREAD

**Issue by pillarBoy** [dcloudio/uni-app#1465]
**问题描述**
uni.openLocation 这个API，在IOS 端打开地图后，在点击左上角返回按钮时，会返回历史路由上两级页面

**复现步骤**
[复现问题的步骤]
1.  启动 'APP'
2. 点击  '景点首页'
3. 点击 '景区详情页'
4.点击 '景区详情页' 里面的 '导航' 按钮 打开地图
    此时调用了uni.openLocation,打开位置正常
5.点击 地图左上角 '返回按钮'
6.返回到 '景点首页'
这里直接跳过了'景点详情页'

补充： 测试发现，IPhone 6 和 6Plus都有这个问题，安卓没有这个问题

**预期结果**
IOS 跟安卓一样，返回上级个页面即可。

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [5+ App等]
 - 操作系统 [ iOS 12.4.3]
 - HBuilderX版本 [2.6.5.20200314]
 - 设备信息 [iPhone6 Plus ]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
uni.openLocation这API打开的页面，返回事件那里出了什么问题

**Comment by dcloudhdx** [comment]
Bug已确认

**Comment by dcloudhdx** [comment]
HBuilderX 2.6.10+ 已修复
