### ISSUE TITLE
uniCloud colletion.count()不可直接调用

### ISSUE THREAD

**Issue by amusiq** [dcloudio/uni-app#1467]
**问题描述**
uniCloud colletion.count()不可直接调用，必须跟在where后面。

**复现步骤**
[复现问题的步骤]
1. 编写云函数get
```
'use strict';
const db = uniCloud.database()
exports.main = async (event, context) => {
  const { start, limit } = event;
  const collection = db.collection('uniCloud-test');
  let res = await collection.count()
  let countResult = res.total;
  return countResult;
};

```
2. 客户端调用云函数get
```
uniCloud.callFunction({
	name: 'get',
	data:{
		start: 0,
		limit: 5
	}
})
```

**预期结果**
返回数字。

**实际结果**
![image](https://user-images.githubusercontent.com/28551646/77377735-fdeb1300-6dae-11ea-85b0-f4c88a8142a7.png)

**系统信息:**
 - 发行平台:微信小程序
 - 操作系统 微信开发者工具
 - HBuilderX版本 2.6.5.20200314

**Comment by Wangyaqi** [comment]
确认有这个问题后续修复

**Comment by Wangyaqi** [comment]
此问题已修复
