### ISSUE TITLE
支付宝h5支付[object%20object]

### ISSUE THREAD

**Issue by vkcyan** [dcloudio/uni-app#1468]
**问题描述**
h5中对接支付宝支付，支付完成回调url就会出现[object%20object]，由于支付宝回调地址不是开发者可以控制的，所以真的无从下手

**复现步骤**
可访问我们的线上商城
https://m.591wsh.com
点击视频会员 腾讯视频 随便点击一个商品 账号输入00000，会自动退款
然后支付完成后url就会变成
https://lt.591wsh.com/pages/orderResult/[object%20Object]
一旦刷新就会白屏

**预期结果**
希望不要出现[object%20Object]

**实际结果**
出现了[object%20Object]

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [全平台]
uni-app v2.6.5
uni-app cli v2.0.0-26520200314001

**Comment by fxy060608** [comment]
#1433 #1082 #661 #445

**Comment by vkcyan** [comment]
已经修复，感谢
