### ISSUE TITLE
头条小程序 $emit 无法传递函数

### ISSUE THREAD

**Issue by jin-yufeng** [dcloudio/uni-app#1469]
**问题描述**
头条小程序中使用 `$emit` 向父组件传递数据时无法传递函数

**复现步骤**
```javascript
this.$emit('xxx', data, function() {
  // callback 无法被传递
})
```

**预期结果**
函数能被传递和调用

**实际结果**
变成 `null` 或没有了

**系统信息:**
 - 发行平台：头条小程序
 - HBuilderX版本：2.6.5

**补充信息**
[根据你的分析，出现这个问题的原因可能在哪里？]
应该是被 `JSON` 化了  
根据 [头条官网介绍](https://developer.toutiao.com/dev/cn/mini-app/develop/framework/custom-component/correspondence-and-event-among-components) 事件是可以传递任意类型的，应该能做得到？

**Comment by xiaoyao96** [comment]
你仔细看下文档吧... $emit只有两个参数，你这第三个参数干嘛的

**Comment by jin-yufeng** [comment]
@xiaoyao96 `vue` 里 [$emit](https://cn.vuejs.org/v2/api/#vm-emit) 的声明是 `vm.$emit( eventName, […args] )`，是可以输入多个参数的
在 `data` 里放一个函数结果也是这样

**Comment by StrivingRabbit** [comment]
新版实测可行
