### ISSUE TITLE
多端支持缺点

### ISSUE THREAD

**Issue by isharrrry** [dcloudio/uni-app#1472]
**新功能描述**
传统windows桌面端，OS X桌面端，Linux 桌面端跨平台应用，很多应用一直受限于平台，界面的发展很慢，能不能考虑这一部分应用上H5开发，这样传统桌面应用和移动端应用可以同步维护

**现状及问题**
目前uni-app虽然使用chrome浏览器可以在PC桌面端使用，但是浏览器的权限还是太广，比如一个图书借阅客户端应用，只需要一个窗口，浏览器的话很容易搞出其他使用上的问题。
另一方面是chrome下不方便用于做一些需要长时间保留后台服务的桌面应用。

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]
7端兼容下增加windows桌面端，OS X桌面端，Linux 桌面端兼容，实现10端全兼容。

**补充信息**

**Comment by celizi** [comment]
你说的是 Electron打包 ?  毕竟PC和手机屏幕差异很大，操作方式差异也大（滑动触摸长按，左键右键细致点击），如果一套代码会加大开发者的难度，感觉至少要2套代码，如果你有更好的建议那就更好了

**Comment by myssru** [comment]
我目前就是发布H5以后使用Electron打包，感觉还可以，就是做出来的UI界面像手机

**Comment by hugetiny** [comment]
这个具体实现超级难，因为本身以upx作为主要的布局单位的话，放到桌面部分元素就会放的非常大。
当然是H5之后用Electron打包了，样式上只能遵从手机的
