### ISSUE TITLE
renderjs脚本如何与逻辑层通信

### ISSUE THREAD

**Issue by Asuka109** [dcloudio/uni-app#1473]
文档和 demo 里都没有相关描述，尝试 watch data 和 watch props 或者把 props 移到 renderjs 内都无法工作，也不能使用 uni.$emit，求解答...

**Comment by zhetengbiji** [comment]
> 文档和 demo 里都没有相关描述，尝试 watch data 和 watch props 或者把 props 移到 renderjs 内都无法工作，也不能使用 uni.$emit，求解答...

demo 里有，点击监听部分就是，你仔细看下
