### ISSUE TITLE
v3编译模式下，MQTT.js报错的问题

### ISSUE THREAD

**Issue by jokerwho** [dcloudio/uni-app#1476]
**问题描述**
错误内容：TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object. __ERROR
出现平台：测试了H5和APP，问题出在APP端

**复现步骤**
https://ext.dcloud.net.cn/plugin?id=854
mqtt-demo在基座调试和打包后运行均出现该错误

**预期结果**
如v2编译一样正常使用MQTT

**系统信息:**
 - 发行平台: uni-app
 - 操作系统 Android10
 - HBuilderX版本 2.6.6 Alpha

**Comment by Wangyaqi** [comment]
是自定义基座和云打包有问题？标准基座运行正常吗？

**Comment by jokerwho** [comment]
> 是自定义基座和云打包有问题？标准基座运行正常吗？

都不正常，都是同样的报错

**Comment by Wangyaqi** [comment]
可以上传一份云打包的apk上来，我这边无法复现这个问题

**Comment by jokerwho** [comment]
> 可以上传一份云打包的apk上来，我这边无法复现这个问题

非v3编译模式：

**Comment by jokerwho** [comment]
> 可以上传一份云打包的apk上来，我这边无法复现这个问题
更改了demo里的链接以及加上了option，可能是option的问题？（猜测）
非V3编译模式：http://qiniu.zaigie.com/pack.apk
V3编译模式：http://qiniu.zaigie.com/v3pack.apk

**Comment by jokerwho** [comment]
> 可以上传一份云打包的apk上来，我这边无法复现这个问题

您好，我参照插件市场上：https://ext.dcloud.net.cn/plugin?id=854，用npm下载github上的mqtt，然后require会出现这个错误。
但是照您说的我导入插件市场另一个更新的demo：https://ext.dcloud.net.cn/plugin?id=1419，引入js的方式使用mqtt，不会出现这个错误。

**Comment by jokerwho** [comment]
您好，我参照插件市场上：https://ext.dcloud.net.cn/plugin?id=854
用npm下载github上的mqtt，然后require会出现这个错误。
但是照您说的我导入插件市场另一个更新的demo：https://ext.dcloud.net.cn/plugin?id=1419
引入js的方式使用mqtt，不会出现这个错误。

**Comment by Wangyaqi** [comment]
我还以为你直接运行插件市场的示例就有问题， 可以把你的代码发一份到我邮箱， wangyaqi988@163.com

**Comment by jokerwho** [comment]
> 我还以为你直接运行插件市场的示例就有问题， 可以把你的代码发一份到我邮箱， [wangyaqi988@163.com](mailto:wangyaqi988@163.com)

发给您了

**Comment by Wangyaqi** [comment]
我这运行你的demo还是没问题，感觉只有一步可能不太一样就是`npm i`安装`mqtt`的时候，你有使用淘宝镜像吗？

**Comment by jokerwho** [comment]
> 我这运行你的demo还是没问题，感觉只有一步可能不太一样就是`npm i`安装`mqtt`的时候，你有使用淘宝镜像吗？你可以直接运行你发我的demo到你手机上，然后把项目里面unpackage\dist\dev\app-plus目录发给我，我对比一下跟我运行的到底有什么差异

好的，发了，没有使用其它镜像

**Comment by jokerwho** [comment]
> 我这运行你的demo还是没问题，感觉只有一步可能不太一样就是`npm i`安装`mqtt`的时候，你有使用淘宝镜像吗？你可以直接运行你发我的demo到你手机上，然后把项目里面unpackage\dist\dev\app-plus目录发给我，我对比一下跟我运行的到底有什么差异

小程序端和H5均运行正常

**Comment by jokerwho** [comment]
> 我这运行你的demo还是没问题，感觉只有一步可能不太一样就是`npm i`安装`mqtt`的时候，你有使用淘宝镜像吗？你可以直接运行你发我的demo到你手机上，然后把项目里面unpackage\dist\dev\app-plus目录发给我，我对比一下跟我运行的到底有什么差异

您好，目前我这里测试了**三种**在V3编译下连接MQTT的方法，均会出现不同的错误，且我**换了电脑以及重新安装HbuilderX**试，依然存在这些问题，所以我认为是**可以复现的BUG**。我的电脑环境是**Windows10**。

1.使用官方demo**(未更改任何代码)**通过npm mqtt并var mqtt = require('mqtt')，会报错**TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object.**

2.使用官方demo**(未更改任何代码)**通过import mqtt from (.../mqtt.js)，**能够成功连接MQTT**，但是收发**超过36个字符的数据**时，sub会卡住，且36个字符后的内容**规律性乱码**，之后重连才能正常接收消息。（朋友说他用这个在**mac**上编译后完全正常实现，所以可能会有系统版本的问题）

3.使用paho-mqtt，基础代码：https://ask.dcloud.net.cn/article/36460
仅微改了服务器和option，V2编译正常，而V3编译则会报错**ReferenceError: Can't find variable: global**

希望官方能在修复了这个BUG后再强制下线旧版本编译，MQTT全部不能用了，拜托了！🙏

**Comment by jokerwho** [comment]
> 可以上传一份云打包的apk上来，我这边无法复现这个问题

您好，目前我这里测试了**三种**在V3编译下连接MQTT的方法，均会出现不同的错误，且我**换了电脑**以及**重装系统和重新安装HbuilderX**，依然存在这些问题，所以我认为是**可以复现的BUG**。
电脑环境：**Windows10**
手机调试环境：**Android10**

1.使用官方demo(**未更改任何代码**)通过npm mqtt并var mqtt = require('mqtt')，会报错**TypeError: First argument must be a string, Buffer, ArrayBuffer, Array, or array-like object**.

2.使用官方demo(**未更改任何代码**)通过import mqtt from (.../mqtt.js)，能够成功连接MQTT，但是收发**超过36个字符的数据**时，sub会卡住内容被截取，且36个字符后的内容**规律性乱码**，重连才能再接收消息，但同样不能超过36个字符。（**在ios上调试不会出现这个问题，而安卓则会出现**）
**问题截图**：http://qiniu.zaigie.com/question.jpg

3.使用paho-mqtt，基础代码：https://ask.dcloud.net.cn/article/36460
仅微改了服务器和option，V2编译正常，而V3编译则会报错**ReferenceError: Can't find variable: global**

希望官方能在修复了这个BUG后再强制下线旧版本编译，MQTT全部不能用了，拜托了！🙏

**Comment by Wangyaqi** [comment]
了解，已经重现，正在排查

**Comment by zhetengbiji** [comment]
使用第二种方式，下次更新将解决乱码问题。另外第三个的示例工程能否提供一下。

**Comment by jokerwho** [comment]
> 使用第二种方式，下次更新将解决乱码问题。另外第三个的示例工程能否提供一下。
您好，就是这个帖子里面的代码：https://ask.dcloud.net.cn/article/36460

**Comment by zhetengbiji** [comment]
> > 使用第二种方式，下次更新将解决乱码问题。另外第三个的示例工程能否提供一下。
> > 您好，就是这个帖子里面的代码：https://ask.dcloud.net.cn/article/36460

第三种方式可以先修改一下mqttws31.js第一处global为undefined，后续优化一下
