### ISSUE TITLE
uni.scss使用条件编译不生效

### ISSUE THREAD

**Issue by elevenyes** [dcloudio/uni-app#1479]
**问题描述**
uni.scss使用条件编译不生效。无论使用#ifdef还是#ifndef，在所有平台均会有效果，没有达到条件编译的目的

**复现步骤**
/* #ifndef H5 */
$qhee-unit: rpx;
/* #endif */

/* #ifdef H5 */
$qhee-unit: rem;
/* #endif */

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 所有平台，所有系统

**Comment by Wangyaqi** [comment]
更新到最新alpha试试

**Comment by elevenyes** [comment]
> 更新到最新alpha试试

是因为编辑器版本的原因吗？还是说最新的alpha修复了这个问题？我目前是最新的稳定版

**Comment by Wangyaqi** [comment]
2.6.6-alpha已修复此问题

**Comment by elevenyes** [comment]
> 2.6.6-alpha已修复此问题

看到官方日志说是修复了，但是我下载了2.6.6-alpha版，经测试还是一样没有生效，不知道为什么。给官方提了bug也还没有回复

**Comment by Wangyaqi** [comment]
正在排查，感谢反馈

**Comment by flyromance** [comment]
真的坑

**Comment by EdifierCN** [comment]
v2.8.8正式版、v2.8.9alpha版依然无效

**Comment by pandashuai** [comment]
2.9.8.20201110 也没生效

**Comment by pandashuai** [comment]
修复了吗？

**Comment by StrivingRabbit** [comment]
新版已修复
