### ISSUE TITLE
[Feature Request] 自定义配置功能增强

### ISSUE THREAD

**Issue by F-loat** [dcloudio/uni-app#148]
h5 模式直接把 router 的 base 属性作为了 vue-cli 的 baseUrl，导致无法使用完整 url 配置 cdn 资源

``` js
const {
  title,
  router: {
    base: baseUrl
  },
  template,
  devServer
} = getH5Options()

module.exports = {
  vueConfig: {
    baseUrl,
    pages: {
      index: {
        // page 的入口
        entry: path.resolve(process.env.UNI_INPUT_DIR, getMainEntry()),
        // 模板来源
        template,
        // 在 dist/index.html 的输出
        filename: 'index.html',
        // 当使用 title 选项时，
        // template 中的 title 标签需要是 <title><%= htmlWebpackPlugin.options.title %></title>
        title,
        // 在这个页面中包含的块，默认情况下会包含
        // 提取出来的通用 chunk 和 vendor chunk。
        chunks: ['chunk-vendors', 'chunk-common', 'index'],
        baseUrl
      }
    },
    ...
  },
  ...
}
```

**Comment by fxy060608** [comment]
@F-loat 是 static 下的所有资源都放到 cdn？增加一个 publicPath，仅在 production 下生效？

**Comment by F-loat** [comment]
主要是指生成的 js 和 css 文件，希望把路由和资源配置分开，目前其实通过转发也可以支持，但是 url 也会跟着变

**Comment by fxy060608** [comment]
dev模式下如果启用 publicPath，那么 dev server 也会使用，导致访问的静态资源不是本地环境新生成的

**Comment by fxy060608** [comment]
cli已更新
暂定逻辑
1.开发期间，仅 base 生效，默认"/"
2.发行期间，publicPath > base

**Comment by F-loat** [comment]
这个我还是觉得开发者来控制不同模式的具体配置好一点，目前的 manifest.json 有点不够灵活，主要没办法根据环境变量做区分，能支持 js 格式是最好的，或者支持条件编译也行，条件编译可以和环境变量做些关联，例如获取下 webpack.DefinePlugin 的配置，

```
// #ifdef process.env.DEV
这部分代码，会出现在 process.env.DEV 存在时
// #endif
```

不太清楚你们这里的实现，能做基础的逻辑判断就更好，另外支持下 else 什么的，

**Comment by fxy060608** [comment]
通常来说，是开发者在 webpack.config.js中根据环境自己决定 publicPath.
只是目前还牵扯到 HBuilderX 中的使用，两种项目类型（cli 创建，HBuilderX 创建），结构有些差别，导致有些东西不太好开放出来，manifest.json是可以加条件编译，不过也满足不了复杂配置，后边可以看看如何开放 webpack 的相关配置

**Comment by F-loat** [comment]
好的，目前 cli 创建的项目里 vue.config.js 大部分配置还是有效的，但是 baseUrl 之类的会被 manifest 的配置覆盖，期待后面的优化，只是配置 cdn 的话上面的方式基本可以支持了

**Comment by F-loat** [comment]
有个类似的问题，我们需要在某些情况下强制开启 css.extract（浏览器端修改 less 变量），但目前 vue.config.js 中的配置会被覆盖，希望可以优化下这部分的处理

```
vueConfig: {
  publicPath,
  ...
  css: {
    extract: true
  }
}
```

**Comment by fxy060608** [comment]
css 的 extract 强制为 false 是因为需要运行时处理部分样式内容，比如 page 的背景，upx，rpx 单位换算，你这个浏览器修改 less 变量的需求，是 extract 出来的都是 less 文件？还是部分 less，部分 css？如果都是 less，而且浏览器引入了 less.js，对 less 进行动态解析，那倒是可以把 uni-app 的运行时 css 处理逻辑在动态解析 less 的时候也补上，如果还包含直接引用结果 css，那就不用使用 upx，rpx单位，page 元素的相关样式可能也会受影响

**Comment by F-loat** [comment]
建议默认为 false，但是 vue.config.js 中有配置的话，以开发者的配置为准

我现在的处理是把源码里的 extract 改为环境相关，然后自定义 less-loader，只对 source 做 upx 替换处理，所以 extract 出来的都是 less 了，然后配合 html 的插件修改 rel 属性，再引入浏览器端的 less 就可以

``` js
// loader
module.exports = function (source) {
  const result = source.replace(/[^:]\/\/.*/g, '')
  return result
}
```

``` js
// plugin
class ThemePlugin {
  apply(compiler) {
    compiler.hooks.compilation.tap('ThemePlugin', (compilation) => {
      compilation.hooks.htmlWebpackPluginAlterAssetTags.tapAsync(
        'ThemePlugin',
        (data, cb) => {
          data.head = data.head.map(item => {
            if (item.attributes && /\.css$/.test(item.attributes.href)) {
              item.attributes.rel = 'stylesheet/less'
            }
            return item
          })
          return cb(null, data);
        }
      )
    })
  }
}

module.exports = ThemePlugin
```

**Comment by F-loat** [comment]
> 把 uni-app 的运行时 css 处理逻辑在动态解析 less 的时候也补上

这样肯定更好了，可以作为 less 插件这样？我们这边的需求目前 extract 能够改为 true 就可以满足

**Comment by fxy060608** [comment]
ok，稍后会整理下相关配置逻辑，争取均以开发者 vue.config.js 配置为准，当配置可能出现异常情况时，以告警形式给出

**Comment by kailcc** [comment]
开放设置了吗

**Comment by fangdiao** [comment]
请问目前是不是还不支持在vue.config.js中修改outputDir，设置后并未生效

**Comment by fxy060608** [comment]
vue.config.js 配置支持的详细说明
https://uniapp.dcloud.io/collocation/vue-config

**Comment by pengleelove** [comment]
> 请问目前是不是还不支持在vue.config.js中修改outputDir，设置后并未生效

现在不支持这个配置

**Comment by zencodex** [comment]
> 请问目前是不是还不支持在vue.config.js中修改outputDir，设置后并未生效

@fxy060608 ，看下官方的封装就行了，很多东西是官方文档是没有提及的。更改输出路径，添加编译的环境变量 UNI_OUTPUT_DIR 就行了。

比如打开 package.json，修改指定的命令。

`"build:h5": "cross-env NODE_ENV=production UNI_PLATFORM=h5 UNI_OUTPUT_DIR=customOutDir vue-cli-service uni-build",`

**Comment by tianxiawuzhe** [comment]
> > 请问目前是不是还不支持在vue.config.js中修改outputDir，设置后并未生效
> 
> @fxy060608 ，看下官方的封装就行了，很多东西是官方文档是没有提及的。更改输出路径，添加编译的环境变量 UNI_OUTPUT_DIR 就行了。
> 
> 比如打开 package.json，修改指定的命令。
> 
> `"build:h5": "cross-env NODE_ENV=production UNI_PLATFORM=h5 UNI_OUTPUT_DIR=customOutDir vue-cli-service uni-build",`

请教大神，我在package.json中配置了UNI_OUTPUT_DIR这种参数，可是用HBuilderX->发行->网站-H5手机版，最后打包出来的还是默认的dist/build/h5目录呀，感觉这个参数并未生效？
如果配置这个参数必须得使用cli命令才能发布的话，那是否有办法配置让HBuilderX能直接将相同平台（如H5）的不同环境（如开发、测试、预测试、生产等）打包到不同子目录的方法呀？

**Comment by zencodex** [comment]
> > > 请问目前是不是还不支持在vue.config.js中修改outputDir，设置后并未生效
> > 
> > 
> > @fxy060608 ，看下官方的封装就行了，很多东西是官方文档是没有提及的。更改输出路径，添加编译的环境变量 UNI_OUTPUT_DIR 就行了。
> > 比如打开 package.json，修改指定的命令。
> > `"build:h5": "cross-env NODE_ENV=production UNI_PLATFORM=h5 UNI_OUTPUT_DIR=customOutDir vue-cli-service uni-build",`
> 
> 请教大神，我在package.json中配置了UNI_OUTPUT_DIR这种参数，可是用HBuilderX->发行->网站-H5手机版，最后打包出来的还是默认的dist/build/h5目录呀，感觉这个参数并未生效？
> 如果配置这个参数必须得使用cli命令才能发布的话，那是否有办法配置让HBuilderX能直接将相同平台（如H5）的不同环境（如开发、测试、预测试、生产等）打包到不同子目录的方法呀？

UNI_OUTPUT_DIR 这个是CLI中指定的，如果是IDE 里，可以试试下面方法修改这个环境变量（至于环境不同，控制不同输出位置，可以添加一个 process.env.NODE_ENV 的环境判断）

在IDE工程根目录下，创建vue.config.js， 添加如下代码：

```.js
const webpack = require('webpack')

module.exports = {
	configureWebpack: {
		plugins: [
			new webpack.DefinePlugin({
				"process.env": {
                                         // 不同环境判断， if (process.env.NODE_ENV == 'production') { .. } else {....}
					'UNI_OUTPUT_DIR': '指向你要输出的位置'
				}
			})
		]
	}
}

```
