### ISSUE TITLE
打包npm库在npm link的情况下无法正常处理npm包的位置 

### ISSUE THREAD

**Issue by 997282173** [dcloudio/uni-app#1483]
**问题描述**
正常的npm包会通过打包过程打包的mp-weixin的文件目录下的node-modules文件下面, 但是如果是npm link的包就无法打包到微信的根目录下导致组件引用失败.

**复现步骤**
1. 下载一个npm包
2. 通过npm link在uniapp代码中进行引用
3. 编译查看npm包的位置

**预期结果**
npm包被打包到小程序的node-modules文件夹下

**实际结果**
npm包被处理到了dist的更目录下, 并且所有的usecomponent字段中的路径都是不正确的

**系统信息:**
uni-app v2.6.5
uni-app cli v2.0.0-26520200314001

Environment Info:

  System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-7360U CPU @ 2.30GHz
  Binaries:
    Node: 12.9.1 - ~/.nvm/versions/node/v12.9.1/bin/node
    Yarn: 1.17.3 - ~/.nvm/versions/node/v12.9.1/bin/yarn
    npm: 6.11.3 - ~/.nvm/versions/node/v12.9.1/bin/npm
  Browsers:
    Chrome: 80.0.3987.149
    Firefox: 72.0.2
    Safari: 13.0.5
  npmPackages:
    @dcloudio/uni-app-plus: ^2.0.0-26520200314001 => 2.0.0-26520200314001 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-cli-shared: ^2.0.0-26520200314001 => 2.0.0-26520200314001 
    @dcloudio/uni-h5: ^2.0.0-26520200314001 => 2.0.0-26520200314001 
    @dcloudio/uni-helper-json: * => 1.0.5 
    @dcloudio/uni-migration: ^2.0.0-26520200314001 => 2.0.0-26520200314001 
    @dcloudio/uni-mp-alipay: ^2.0.0-26520200314001 => 2.0.0-26520200314001 
    @dcloudio/uni-mp-baidu: ^2.0.0-26520200314001 => 2.0.0-26520200314001 
    @dcloudio/uni-mp-qq: ^2.0.0-26520200314001 => 2.0.0-26520200314001 
    @dcloudio/uni-mp-toutiao: ^2.0.0-26520200314001 => 2.0.0-26520200314001 
    @dcloudio/uni-mp-weixin: ^2.0.0-26520200314001 => 2.0.0-26520200314001 
    @dcloudio/uni-stat: ^2.0.0-26520200314001 => 2.0.0-26520200314001 
    @dcloudio/uni-template-compiler: ^2.0.0-26520200314001 => 2.0.0-26520200314001 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-26520200314001 => 2.0.0-26520200314001 
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-26520200314001 => 2.0.0-26520200314001 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-26520200314001 => 2.0.0-26520200314001 
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-26520200314001 => 2.0.0-26520200314001 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-26520200314001 => 2.0.0-26520200314001 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  3.12.1 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.2.3 
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1 
    @vue/cli-plugin-router:  4.2.3 
    @vue/cli-plugin-vuex:  4.2.3 
    @vue/cli-service: ^4.2.0 => 4.2.3 
    @vue/cli-shared-utils:  4.2.3 
    @vue/component-compiler-utils:  3.1.1 (3.1.1)
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    babel-helper-vue-jsx-merge-props:  2.0.3 
    mpvue:  2.0.6 
    mpvue-page-factory:  1.0.1 
    mpvue-router-patch:  2.0.0 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.11 => 2.6.11 
    vue-draggable-resizable:  1.7.5 
    vue-hot-reload-api:  2.3.4 
    vue-lazyload:  1.3.3 
    vue-loader:  15.9.0 (15.9.0)
    vue-router:  3.0.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.11 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.0.1 => 3.1.3 
  npmGlobalPackages:
    @vue/cli: 4.2.3

**补充信息**

个人怀疑是对软连接的处理问题

**Comment by fxy060608** [comment]
在根目录创建vue.config.js
```javascript
// vue.config.js  
module.exports = {  
    configureWebpack: {  
        resolve: {  
            symlinks: false  
        }  
    }  
} 
```

**Comment by 997282173** [comment]
> 在根目录创建vue.config.js
> 
> ```js
> // vue.config.js  
> module.exports = {  
>     configureWebpack: {  
>         resolve: {  
>             symlinks: false  
>         }  
>     }  
> } 
> ```

关闭symlink就可以了, 看来还是对webpack的了解不够深入啊, 多谢了
