### ISSUE TITLE
uni.getBackgroundAudioManager()报一些奇奇怪怪的问题总结

### ISSUE THREAD

**Issue by yebanapp** [dcloudio/uni-app#1484]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
问题列表：1.总时长获取不对     2.paused获取状态一直是true    3.buffered也不对无变化一直是0   4.currentTime有时也不变，是0    5.所有数值都不会变化，我的意思是该变化的没有变化
还有就是官方文档能否写的详细一些？示例就几行代码，那点够干啥的

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

> <template>
	<view class="">
		<cu-custom bgColor="bg-gradual-blue" isStatusBar />
		测试背景音频
		<view class="">
			{{audio.duration}}
		</view>
		<view class="">
			{{audio.currentTime}}
		</view>
		<view class="">
			{{audio.paused ? '暂停或停止' : '播放中'}}
		</view>
		<view class="">
			{{audio.startTime}}
		</view>
		<view class="">
			{{audio.buffered}}
		</view>
		<view class="">
			{{audio.title}}
		</view>
		<view class="">
			{{audio.epname}}
		</view>
		<view class="">
			{{audio.singer}}
		</view>
		<view class="">
			{{audio.coverImgUrl}}
		</view>
		<view class="text-center">
			<view class="margin-tb">
				<button class="cu-btn lines-mauve round lg shadow" @click="play">播放</button>
			</view>
			<view class="margin-tb">
				<button class="cu-btn lines-mauve round lg shadow" @click="pause">暂停</button>
			</view>
			<view class="margin-tb">
				<button class="cu-btn lines-mauve round lg shadow" @click="stop">停止</button>
			</view>
			<view class="margin-tb">
				<button class="cu-btn lines-mauve round lg shadow" @click="seek">seek</button>
			</view>
		</view>
	</view>
</template>

> <script>
	const BgAudioMannager = uni.getBackgroundAudioManager();
	export default {
		data() {
			return {
				audio: {
					duration: 0,	//当前音频的长度（单位：s）
					currentTime: 0,	//当前音频的播放位置
					paused: true,	//当前是是否暂停或停止状态，true 表示暂停或停止，false 表示正在播放
					src: 'https://img-cdn-qiniu.dcloud.net.cn/uniapp/audio/music.mp3',	//音频的数据源
					startTime: 0,	//音频开始播放的位置
					buffered: 0,	//音频缓冲的时间点
					title: '致爱丽丝',	//音频标题
					epname: '',	//专辑名
					singer: '暂无',	//歌手名
					coverImgUrl: 'https://img-cdn-qiniu.dcloud.net.cn/uniapp/audio/music.jpg',	//封面图url
					webUrl: '',	//页面链接
					protocol: 'https'	//音频协议 http|https|hls等
				}
			}
		},
		methods: {
			init: function() {
				const _this = this
				BgAudioMannager.title = _this.audio.title;
				BgAudioMannager.singer = _this.audio.singer;
				BgAudioMannager.coverImgUrl = _this.audio.coverImgUrl;
				BgAudioMannager.src = _this.audio.src;
				
				BgAudioMannager.onCanplay(function(res){
					console.log('背景音频进入可以播放状态', res);
				})
				BgAudioMannager.onPlay(function(res){
					console.log('背景音频播放事件', res);
				})
				BgAudioMannager.onPause(function(res){
					console.log('背景音频暂停事件', res);
				})
				BgAudioMannager.onStop(function(res){
					console.log('背景音频停止事件', res);
				})
				BgAudioMannager.onEnded(function(res){
					console.log('背景音频自然播放结束事件', res);
				})
				BgAudioMannager.onTimeUpdate(function(res){
					const onTime = BgAudioMannager.currentTime
					_this.audio.currentTime = Math.ceil(onTime)
					// console.log('背景音频播放进度更新事件', res, onTime);
				})
				BgAudioMannager.onPrev(function(res){
					console.log('用户在系统音乐播放面板点击上一曲事件（iOS only）', res);
				})
				BgAudioMannager.onNext(function(res){
					console.log('用户在系统音乐播放面板点击下一曲事件（iOS only）', res);
				})
				BgAudioMannager.onError(function(res){
					console.log('背景音频播放错误事件', res);
				})
				BgAudioMannager.onWaiting(function(res){
					console.log('音频加载中事件，当音频因为数据不足，需要停下来加载时会触发', res);
				})
				this.audio.duration = Math.ceil(BgAudioMannager.duration / 60)
				this.audio.paused = BgAudioMannager.paused
				this.audio.startTime = BgAudioMannager.startTime
				this.audio.buffered = BgAudioMannager.buffered
			},
			play: function() {
				BgAudioMannager.play()
			},
			pause: function() {
				BgAudioMannager.pause()
			},
			stop: function() {
				BgAudioMannager.stop()
			},
			seek: function() {
				BgAudioMannager.seek()
			}
		},
		created() {
			this.init()
		}
	}
</script>

<style>
</style>

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [app]
 - 操作系统: [安卓]
 - HBuilderX版本 [HBuilderX, 2.6.5.20200314]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 小米cc9]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by yebanapp** [comment]
<template>
	<view class="">
		<cu-custom bgColor="bg-gradual-blue" isStatusBar />
		测试背景音频
		<view class="">
			{{audio.duration}}
		</view>
		<view class="">
			{{audio.currentTime}}
		</view>
		<view class="">
			{{audio.paused ? '暂停或停止' : '播放中'}}
		</view>
		<view class="">
			{{audio.startTime}}
		</view>
		<view class="">
			{{audio.buffered}}
		</view>
		<view class="">
			{{audio.title}}
		</view>
		<view class="">
			{{audio.epname}}
		</view>
		<view class="">
			{{audio.singer}}
		</view>
		<view class="">
			{{audio.coverImgUrl}}
		</view>
		<view class="text-center">
			<view class="margin-tb">
				<button class="cu-btn lines-mauve round lg shadow" @click="play">播放</button>
			</view>
			<view class="margin-tb">
				<button class="cu-btn lines-mauve round lg shadow" @click="pause">暂停</button>
			</view>
			<view class="margin-tb">
				<button class="cu-btn lines-mauve round lg shadow" @click="stop">停止</button>
			</view>
			<view class="margin-tb">
				<button class="cu-btn lines-mauve round lg shadow" @click="seek">seek</button>
			</view>
		</view>
	</view>
</template>

<script>
	const BgAudioMannager = uni.getBackgroundAudioManager();
	export default {
		data() {
			return {
				audio: {
					duration: 0,	//当前音频的长度（单位：s）
					currentTime: 0,	//当前音频的播放位置
					paused: true,	//当前是是否暂停或停止状态，true 表示暂停或停止，false 表示正在播放
					src: 'https://img-cdn-qiniu.dcloud.net.cn/uniapp/audio/music.mp3',	//音频的数据源
					startTime: 0,	//音频开始播放的位置
					buffered: 0,	//音频缓冲的时间点
					title: '致爱丽丝',	//音频标题
					epname: '',	//专辑名
					singer: '暂无',	//歌手名
					coverImgUrl: 'https://img-cdn-qiniu.dcloud.net.cn/uniapp/audio/music.jpg',	//封面图url
					webUrl: '',	//页面链接
					protocol: 'https'	//音频协议 http|https|hls等
				}
			}
		},
		methods: {
			init: function() {
				const _this = this
				BgAudioMannager.title = _this.audio.title;
				BgAudioMannager.singer = _this.audio.singer;
				BgAudioMannager.coverImgUrl = _this.audio.coverImgUrl;
				BgAudioMannager.src = _this.audio.src;
				
				BgAudioMannager.onCanplay(function(res){
					console.log('背景音频进入可以播放状态', res);
				})
				BgAudioMannager.onPlay(function(res){
					console.log('背景音频播放事件', res);
				})
				BgAudioMannager.onPause(function(res){
					console.log('背景音频暂停事件', res);
				})
				BgAudioMannager.onStop(function(res){
					console.log('背景音频停止事件', res);
				})
				BgAudioMannager.onEnded(function(res){
					console.log('背景音频自然播放结束事件', res);
				})
				BgAudioMannager.onTimeUpdate(function(res){
					const onTime = BgAudioMannager.currentTime
					_this.audio.currentTime = Math.ceil(onTime)
					// console.log('背景音频播放进度更新事件', res, onTime);
				})
				BgAudioMannager.onPrev(function(res){
					console.log('用户在系统音乐播放面板点击上一曲事件（iOS only）', res);
				})
				BgAudioMannager.onNext(function(res){
					console.log('用户在系统音乐播放面板点击下一曲事件（iOS only）', res);
				})
				BgAudioMannager.onError(function(res){
					console.log('背景音频播放错误事件', res);
				})
				BgAudioMannager.onWaiting(function(res){
					console.log('音频加载中事件，当音频因为数据不足，需要停下来加载时会触发', res);
				})
				this.audio.duration = Math.ceil(BgAudioMannager.duration / 60)
				this.audio.paused = BgAudioMannager.paused
				this.audio.startTime = BgAudioMannager.startTime
				this.audio.buffered = BgAudioMannager.buffered
			},
			play: function() {
				BgAudioMannager.play()
			},
			pause: function() {
				BgAudioMannager.pause()
			},
			stop: function() {
				BgAudioMannager.stop()
			},
			seek: function() {
				BgAudioMannager.seek()
			}
		},
		created() {
			this.init()
		}
	}
</script>

<style>
</style>

**Comment by zhetengbiji** [comment]
新版已优化
