### ISSUE TITLE
nvue页面scroll-view在Android端app设置:scroll-y="false"会使横向滚动失效

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#1487]
开启了scroll-x，如果设置了scroll-y为false，android端app无法横向滚动。

nvue页面。

只要去掉scroll-y的设置就可以滚动。

虽然没有必要设置scroll-y，只是很多人估计会不小心就被坑了。

**Comment by dcloudhdx** [comment]
Bug 已确认
