### ISSUE TITLE
引导页白屏问题

### ISSUE THREAD

**Issue by Kole6** [dcloudio/uni-app#1488]
**问题描述**
我说的引导页是指首次打开app的一些介绍页面等轮播；
官方有例子，做一个引导页，第一页面使用 swiper 组件，然后禁用原生导航栏，判断缓存第一次打开，然后进入引导页；
但是总是牺牲进入首屏的时间；
然后我用首页跳转引导页，第一次还是有打开首页的影响；

实在没有办法了，官方能不能实现onLaunch下配置一个引导页路由，第一次打开app进入这个路由，或者在manifest.json增加一个引导页配置选项

**复现步骤**
https://ext.dcloud.net.cn/plugin?id=192

**Comment by ouzhou** [comment]
这样，你把这个swiper用v-if全屏覆盖，首页还是正常的首页，只不过swiper层级更高一些，遮挡住就行

**Comment by Kole6** [comment]
> 这样，你把这个swiper用v-if全屏覆盖，首页还是正常的首页，只不过swiper层级更高一些，遮挡住就行

首页的tabbar怎么办？首页的底部v-if隐藏不了，启动页还是想在单独的页面配置。

**Comment by ouzhou** [comment]
自定义tabbar
