### ISSUE TITLE
封装安卓IJKplayer 报错

### ISSUE THREAD

**Issue by ouzhou** [dcloudio/uni-app#1489]
**问题描述**
测试都是正常的，打包基座后使用报错

`reportJSException >>>> exception function:callAddElement, exception:java.lang.NullPointerException: Attempt to invoke virtual method 'com.taobao.weex.dom.WXAttr com.taobao.weex.ui.component.WXComponent.getAttrs()' on a null object reference
`

`21:21:35.270 at com.taobao.weex.ui.RenderContextImpl.registerComponent(RenderContextImpl.java:86)
21:21:35.291 at com.taobao.weex.ui.WXRenderManager.registerComponent(WXRenderManager.java:306)
21:21:35.312 at com.taobao.weex.ui.action.GraphicActionAbstractAddElement.createComponent(GraphicActionAbstractAddElement.java:62)
21:21:35.333 at com.taobao.weex.ui.action.GraphicActionAddElement.<init>(GraphicActionAddElement.java:86)
21:21:35.354 at com.taobao.weex.bridge.WXBridgeManager.callAddElement(WXBridgeManager.java:2799)
21:21:35.374 at com.taobao.weex.bridge.WXBridge.callAddElement(WXBridge.java:535)
21:21:35.395 at com.taobao.weex.base.SystemMessageHandler.nativeRunWork(Native Method)
21:21:35.416 at com.taobao.weex.base.SystemMessageHandler.handleMessage(SystemMessageHandler.java:104)
21:21:35.436 at android.os.Handler.dispatchMessage(Handler.java:107)
21:21:35.457 at android.os.Looper.loop(Looper.java:213)
21:21:35.477 at android.os.HandlerThread.run(HandlerThread.java:67)`

**Comment by ouzhou** [comment]
让人迷惑的是在调试下都可以，一但打包了自定义基座，然后运行就报这个错

**Comment by ArrayDC** [comment]
在manifest.json文件的“App模块权限配置”中的“打包模块配置”项下勾选“VideoPlayer（视频播放）”，保存后重新生成自定义基座。
