### ISSUE TITLE
云数据库初始化文件大一点时候就会报Allowed memory si (truncated...)

### ISSUE THREAD

**Issue by hugetiny** [dcloudio/uni-app#1490]
**问题描述**
初始化文件大一点时候就会报Allowed memory si (truncated...)

**复现步骤**
[复现问题的步骤]
1.  将JSON文件复制到db_init.json中
2. 点击  '初始化云数据库'

**预期结果**
初始化成功

**实际结果**
[xxx] 09:13:17.935 [阿里云:xxx]初始化云数据库失败。失败原因: 创建数据表 api 成功
	数据表 api 数据导入失败：Server error: `POST http://ali-mp-serverless.dcloud.net.cn/api/mpserverless/database/runDbCommand` resulted in a `500 Internal Server Error` response:
<!doctype html>
<html class="theme-light">
<!--
Symfony\Component\Debug\Exception\FatalErrorException: Allowed memory si (truncated...)

**系统信息:**
 - 操作系统 [Windows10]
 - HBuilderX版本 [2.6.5]

**Comment by Wangyaqi** [comment]
后续会优化此问题
