### ISSUE TITLE
picker组件内子标签不能撑满picker，导致picker触发事件无效，不能正常调出弹框

### ISSUE THREAD

**Issue by Echo0326** [dcloudio/uni-app#1491]
**问题描述**
在picker组件内，写的子组件用来接收显示picker的值，但是子组件样式无效，不能撑满picker,导致只有子组件占用的地方才能触发picker事件，其他空白未被占用的地方不能触发事件，不能掉出picker选择框

**复现步骤**
![picker2](https://user-images.githubusercontent.com/25999328/77718557-2f1d4a80-701e-11ea-98f5-73369bf991df.gif)

![img1](https://user-images.githubusercontent.com/25999328/77718927-12354700-701f-11ea-84a1-f753449d1e49.png)

![img2](https://user-images.githubusercontent.com/25999328/77718932-15c8ce00-701f-11ea-84c3-8f00075f0abb.png)

**预期结果**
希望能像微信小程序原生组件一样,picker组件内的组件可以撑满picker，点击空白的地方能够正常掉出picker选择器

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 : iOS 13.3.1、Android 10.0]
 - uni-app版本  uni-app v2.4.2
                      uni-app cli v2.0.0-24220191115006

 - 设备信息 : iPhone11 pro   华为荣耀9

**Comment by zhetengbiji** [comment]
你写的组件运行到小程序上就是小程序原生组件，你可以试试不用uni-app直接写小程序示例，如果发现有不同，可以提供一个示例工程帮你排查一下。

**Comment by Echo0326** [comment]
> 你写的组件运行到小程序上就是小程序原生组件，你可以试试不用uni-app直接写小程序示例，如果发现有不同，可以提供一个示例工程帮你排查一下。

根据您的提示，试了试不用uni-app来写，发现也会产生这种情况，对比以前的代码才发现产生这种情况的原因竟然是picker组件不能被display:flex，一旦被display:flex内部组件将失去宽度上的css效果，也就不会撑满。
目前原因不明，应该是微信小程序自身遗留的bug。
感谢您~~~
