### ISSUE TITLE
v3模式下"titleNView": false 不生效

### ISSUE THREAD

**Issue by Kole6** [dcloudio/uni-app#1493]
**问题描述**
v3模式下"titleNView": false 不生效

其他的页面生效，只有首页"titleNView": false不生效
`"pages": [{
			"path": "pages/tabBar/index/index",
			"style": {
				"app-plus": {
					"titleNView": false
				}
			}
		}]`
**系统信息:**
iphone6s  

ios 10.2

**Comment by Wangyaqi** [comment]
是不是设置了导航栏颜色，用的HBuilderX是什么版本

**Comment by Kole6** [comment]
2.6.5版本，安卓的没问题，只有iphone有这个问题，在基座上打开

**Comment by dcloudhdx** [comment]
HBuilderX 2.6.10 + alpha 版已修复
