### ISSUE TITLE
scroll-view中的text组件宽高失效了

### ISSUE THREAD

**Issue by chenzefeng09** [dcloudio/uni-app#1496]
**问题描述**
scroll-view中的text组件宽高失效了

**复现步骤**
将uni-app示例工程中，scroll-view示例中的子控件由view改为text，就没有宽高了
![image](https://user-images.githubusercontent.com/7556537/77819195-e8aa1780-7113-11ea-848b-457f033c2b09.png)

**预期结果**
![image](https://user-images.githubusercontent.com/7556537/77819218-0bd4c700-7114-11ea-9e9f-f468433c79ad.png)

**实际结果**
![image](https://user-images.githubusercontent.com/7556537/77819204-f6f83380-7113-11ea-9ad6-94f3bec8b92a.png)

**系统信息:**
 - 发行平台: [百度小程序]
 - 操作系统 [模拟器]
 - uni-app版本 [2.6.5.20200314]
 - 设备信息 [模拟器]

**Comment by wakaryry** [comment]
text组件是有可能在很多地方宽度与你预期的不一样，所以开发的时候如果遇到不一致的，通过flex或者width等进行限制。

**Comment by bfc846958672** [comment]
正常现象，text是内联元素，宽高基于内容
