### ISSUE TITLE
应用名称为中文时进不去微信开发者工具

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#1498]
- hbx：2.6.7-alpha
- OS：Mac
- 微信开发者工具：1.0.2.20003250

**应用名称为中文时，编译后会一直在微信开发者工具里面卡住：加载中，初始化应用通信能力**

在iOS和h5可以正常运行。

看过微信开发者工具调试的内容，好像是找不到文件什么之类的。

# 复现过程1

- 创建一个英文目录项目 `abc`
- 进入`manifest.json`修改应用名称为中文 `猜猜猜`
- 运行到微信开发者工具

# 复现过程2

- 创建一个中文目录项目 `您好`
- 运行到微信开发者工具

# 在微信开发者工具里面测试

直接在微信开发者工具里面创建中文名字的项目，是可以运行的。

# 另外
`hello uni-app` 这个名字也无法进去。

**Comment by dcloudhdx** [comment]
名字确实影响命令行或HTTP启动，微信的Bug，微信社区已有多人反馈，换个版本试试
