### ISSUE TITLE
app拍照上传后导致页面空白，可以说是基本毕现。问题链接http://ask.dcloud.net.cn/question/64018?notification_id-522828__rf-false__comment_unfold-question

### ISSUE THREAD

**Issue by 18390211712** [dcloudio/uni-app#150]
app拍照上传后导致页面空白，可以说是基本毕现。

问题链接
http://ask.dcloud.net.cn/question/64018?notification_id-522828__rf-false__comment_unfold-question

**Comment by 18390211712** [comment]
这个白屏问题现在还是存在的，比之前稍微好一点点。白屏问题不解决审核通不过呀。
问题链接 1）http://ask.dcloud.net.cn/question/64018?notification_id-522828__rf-false__comment_unfold-question

2）http://ask.dcloud.net.cn/question/66851

**Comment by dcloudhdx** [comment]
试下HBuilderX 1.9.5 alpha版本，此版本已解决因内存问题白屏
