### ISSUE TITLE
pages.json无法用uni.scss中的变量

### ISSUE THREAD

**Issue by hugetiny** [dcloudio/uni-app#1501]
**问题描述**
pages.json无法用uni.scss中的变量

**复现步骤**
[复现问题的步骤]
1.  pages.json配置项中“tabBar” backgroundColor写成uni.scss中的变量

[或者可以直接贴源代码]

**预期结果**
无法通过编译

**实际结果**
pages.json无法用uni.scss中的变量

**系统信息:**
 - 发行平台: [调试H5]
 - 操作系统 [Windows10]
 - HBuilderX版本 [2.6.8]

**Comment by Wangyaqi** [comment]
uni.scss内的变量只在scss文件或者 <style lang="scss">内生效

**Comment by hugetiny** [comment]
后续可以优化下，毕竟pages.json文件比较特殊

**Comment by Mity1299** [comment]
请问有优化的打算吗
