### ISSUE TITLE
hbuilder编辑器注释功能的改进

### ISSUE THREAD

**Issue by hugetiny** [dcloudio/uni-app#1507]
**问题描述**
折叠代码注释和已包含注释的代码块注释均会出现注释错误

**复现步骤**
注释折叠代码注释
注释已包含注释的代码块

**预期结果**
就像webstorm等主流编辑器一样，已经包含注释的代码块的注释代码应该做一层转义
折叠代码的注释也要改进下

**实际结果**
会出现注释乱掉的情况

**系统信息:**
 - 操作系统 [Windows10]
 - HBuilderX版本 [2.6.8]

**补充信息**
自己平时webstorm用的多了，用hbuilderX不顺手，现在反过来uni-app的程序也在webstorm写，hbuilderX就编译预览

**Comment by wandali2019** [comment]
请详细说明。截图或上传附件
