### ISSUE TITLE
条件编译 APP-PLUS  和 APP-PLUS-NVUE是包含关系吗？

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-app#1508]
条件编译 APP-PLUS  包含 APP-PLUS-NVUE吗 ？
另外，为什么我看官方demo条件编译写的的是APP-NVUE而不是APP-PLUS-NVUE，这俩有区别吗？

**Comment by zhetengbiji** [comment]
APP-PLUS 包含 APP-PLUS-NVUE
APP-NVUE 是 APP-PLUS-NVUE 简写

**Comment by huanghaodong** [comment]
> APP-PLUS 包含 APP-PLUS-NVUE
> APP-NVUE 是 APP-PLUS-NVUE 简写

谢谢
