### ISSUE TITLE
vue-cli-plugin-uni不兼容sassOptions配置

### ISSUE THREAD

**Issue by bigBron** [dcloudio/uni-app#1509]
需求：使用dart-sass

重现步骤：
```js
// 0.创建新项目 vue create -p dcloudio/uni-preset-vue test && cd test

// 1.安装 sass-loader@7.x 及 dart-sass 依赖
yarn add -D sass-loader@7.3.0 sass 

// 2.创建src/vue.config.js
module.exports = { 
    css: {
        loaderOptions: {
            sass: {
                implementation: require("sass"), // 指定使用 dart-sass
                sassOptions: {
                    outputStyle: "compressed"
                }
            }
        }
    }
}

// 3. yarn dev:app-plus 出现错误
.Module build failed (from ./node_modules/sass-loader/dist/cjs.js): Invalid argument(s): Unsupported output style "nested".
```

目前可以确认问题出现在 [node_modules/@dcloudio/vue-cli-plugin-uni/lib/options.js文件76行](https://github.com/dcloudio/uni-app/blob/830e0b27f647249de91f8866b59921ab33c87b45/packages/vue-cli-plugin-uni/lib/options.js#L76)，硬编码修改了sassOptions配置，dart-sass并不支持nested：
```js
  options.css.loaderOptions.sass.sassOptions.outputStyle = 'nested'
```

这样硬编码处理是否妥当？很多时候node-sass并不是很好的选择，它对sass某些语法并不兼容，希望对dart-sass提供更多支持。

版本：@dcloudio/vue-cli-plugin-uni@2.0.0-26820200330001

**Comment by fxy060608** [comment]
强制nested，是因为条件编译需要保留原始注释

**Comment by bigBron** [comment]
希望能有个跟好的解决方案，如果不使用nested是否会造成大的影响？

**Comment by fxy060608** [comment]
> 希望能有个更好的解决方案，如果不使用nested是否会造成大的影响？

会导致scss里的条件编译可能失效，我找时间验证下dart-sass的支持吧

**Comment by bigBron** [comment]
> > 希望能有个更好的解决方案，如果不使用nested是否会造成大的影响？
> 
> 会导致scss里的条件编译可能失效，我找时间验证下dart-sass的支持吧

好的，上一个版本2.0.0-26520200314001使用dart-sass与条件编译是完全没问题的。

**Comment by bigBron** [comment]
刚测试了下，把下面文件 outputStyle = 'nested' 硬编码都注释掉：
- node_modules/@dcloudio/vue-cli-plugin-hbuilderx/build/css-loader.conf.js
- node_modules/@dcloudio/vue-cli-plugin-uni/lib/options.js

然后在vue单页文件测试条件编译：
```vue
<template>
    <view class="box" ref="box">
	<text>test</text>
    </view>
</template>

<script>
    export default {
        name: "Test"
    }
</script>

<style lang="scss" scoped>
    .box {
        /* #ifdef APP-NVUE */
        width: 100px;
        height: 100px;
        background-color: #ff0004;
        /* #endif */
        /* #ifndef APP-NVUE */
        width: 200px;
        height: 200px;
        background-color: #1eff78;
        /* #endif */
    }
</style>
```

测试结果：**H5端，App端能正常执行。**
测试版本：@dcloudio/vue-cli-plugin-uni@2.0.0-26820200330001

**Comment by fxy060608** [comment]
应该是scss里边使用@import进来的scss文件

**Comment by bigBron** [comment]
> 应该是scss里边使用@import进来的scss文件

我又去测试了下在vue单页文件style标签@import导入scss文件，还是能正常编译的，效果正确，后面就靠你了，兄弟。

**Comment by fxy060608** [comment]
1.使用scss的@import语法(这样import语法就会被sass解析，读取文件内容)
```
@import "../../common/common.scss";
```
2.确保outputStyle是compressed（这样sass解析import文件里的内容后会压缩掉条件编译注释代码）
3.当满足以上两个条件时，条件编译失效

目前vue cli版本，sass-loader版本，不匹配的话，可能outputStyle配置不生效，你可以写死sass-loader或sass里的outputStyle为compressed，然后测试。

**Comment by bigBron** [comment]
> 1.使用scss的@import语法(这样import语法就会被sass解析，读取文件内容)
> 
> ```
> @import "../../common/common.scss";
> ```
> 
> 2.确保outputStyle是compressed（这样sass解析import文件里的内容后会压缩掉条件编译注释代码）
> 3.当满足以上两个条件时，条件编译失效
> 
> 目前vue cli版本，sass-loader版本，不匹配的话，可能outputStyle配置不生效，你可以写死sass-loader或sass里的outputStyle为compressed，然后测试。

outputStyle=compressed确实是会导致编译条件失败。
我之前测试是用vue.config.js配置，然后用hbuilderx编译，hbuilderx编译不使用vue.config.js配置，所以没看到效果。

---

我这里给出个解决方法：
```
node-sass的outputStyle支持四种模式：nested，compact，compressed，expanded
dart-sass的outputStyle支持两种种模式：expanded，compressed
我简单测试了下，使用expanded能兼容条件编译
```

**Comment by bigBron** [comment]
@fxy060608  @dcloudio/vue-cli-plugin-hbuilderx还没修复

**Comment by fxy060608** [comment]
> @fxy060608 @dcloudio/vue-cli-plugin-hbuilderx还没修复

版本号多少？你怎么配置的outputStyle，如何确认的没修复？

**Comment by bigBron** [comment]
> > @fxy060608 @dcloudio/vue-cli-plugin-hbuilderx还没修复
> 
> 版本号多少？你怎么配置的outputStyle，如何确认的没修复？

https://github.com/dcloudio/uni-app/blob/aa60b3cc05cc99de69f3fc84af40214684677cd0/packages/vue-cli-plugin-hbuilderx/build/css-loader.conf.js#L72-L90

hbuilderx编译还是走旧的逻辑

**Comment by bigBron** [comment]
hbuilderx编译没有读取到vue.config.js

**Comment by fxy060608** [comment]
> hbuilderx编译没有读取到vue.config.js

你是说nvue里边没生效吧？

**Comment by bigBron** [comment]
> > hbuilderx编译没有读取到vue.config.js
> 
> 你是说nvue里边没生效吧？

你们这编译走两套插件的，cli下走的vue-cli-plugin-uni，在hbuilderx编辑器里又走的vue-cli-plugin-hbuilderx，你之前改动是vue-cli-plugin-uni的能正常修复了，但是用户用hbuilderx来编译就不行了

**Comment by fxy060608** [comment]
> > > hbuilderx编译没有读取到vue.config.js
> > 
> > 
> > 你是说nvue里边没生效吧？
> 
> 你们这编译走两套插件的，cli下走的vue-cli-plugin-uni，在hbuilderx编辑器里又走的vue-cli-plugin-hbuilderx，你之前改动是vue-cli-plugin-uni的能正常修复了，但是用户用hbuilderx来编译就不行了

你发的那个文件，仅针对nvue的编译，nvue目前暂不支持vue.config.js配置

**Comment by bigBron** [comment]
@fxy060608 好的，顺便问下一个问题，现在更新到最新的2.0.0-27920200618002版本，然后在production模式编译报错了：
```js
[HBuilder] 15:18:37.339  ERROR  TypeError: config.optimization.minimizer(...).tap is not a function
[HBuilder] 15:18:37.340 TypeError: config.optimization.minimizer(...).tap is not a function
[HBuilder] 15:18:37.344     at chainWebpack (F:\code\repo\xxx\node_modules\@dcloudio\uni-app-plus\lib\uni.config.js:57:47)
[HBuilder] 15:18:37.349     at F:\code\repo\xxx\node_modules\@dcloudio\vue-cli-plugin-uni\index.js:82:14
[HBuilder] 15:18:37.350     at F:\code\repo\xxx\node_modules\@vue\cli-service\lib\Service.js:242:40
[HBuilder] 15:18:37.357     at Array.forEach (<anonymous>)
[HBuilder] 15:18:37.358     at Service.resolveChainableWebpackConfig (F:\code\repo\xxx\node_modules\@vue\cli-service\lib\Service.js:242:26)
[HBuilder] 15:18:37.364     at PluginAPI.resolveChainableWebpackConfig (F:\code\repo\xxx\node_modules\@vue\cli-service\lib\PluginAPI.js:151:25)
[HBuilder] 15:18:37.364     at module.exports (F:\code\repo\xxx\node_modules\@vue\cli-service\lib\commands\build\resolveAppConfig.js:2:22)
[HBuilder] 15:18:37.373     at getWebpackConfig (F:\code\repo\xxx\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:53:88)
[HBuilder] 15:18:37.381     at getWebpackConfigs (F:\code\repo\xxx\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:89:32)
[HBuilder] 15:18:37.382     at build (F:\code\repo\xxx\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:119:26)
[HBuilder] 15:18:37.392     at F:\code\repo\xxx\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:44:11
[HBuilder] 15:18:37.402     at Service.run (F:\code\repo\xxx\node_modules\@vue\cli-service\lib\Service.js:236:12)
[HBuilder] 15:18:37.403     at Object.<anonymous> (F:\code\repo\xxx\node_modules\@vue\cli-service\bin\vue-cli-service.js:37:9)
[HBuilder] 15:18:37.414     at Module._compile (internal/modules/cjs/loader.js:956:30)
[HBuilder] 15:18:37.415     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
[HBuilder] 15:18:37.426     at Module.load (internal/modules/cjs/loader.js:812:32)
```

https://github.com/dcloudio/uni-app/blob/aa60b3cc05cc99de69f3fc84af40214684677cd0/packages/uni-app-plus/lib/uni.config.js#L56-L63

是少了什么插件？每次更新你们东西都提心吊胆的

**Comment by fxy060608** [comment]
> @fxy060608 好的，顺便问下一个问题，现在更新到最新的2.0.0-27920200618002版本，然后在production模式编译报错了：
> 
> ```js
> [HBuilder] 15:18:37.339  ERROR  TypeError: config.optimization.minimizer(...).tap is not a function
> [HBuilder] 15:18:37.340 TypeError: config.optimization.minimizer(...).tap is not a function
> [HBuilder] 15:18:37.344     at chainWebpack (F:\code\repo\xxx\node_modules\@dcloudio\uni-app-plus\lib\uni.config.js:57:47)
> [HBuilder] 15:18:37.349     at F:\code\repo\xxx\node_modules\@dcloudio\vue-cli-plugin-uni\index.js:82:14
> [HBuilder] 15:18:37.350     at F:\code\repo\xxx\node_modules\@vue\cli-service\lib\Service.js:242:40
> [HBuilder] 15:18:37.357     at Array.forEach (<anonymous>)
> [HBuilder] 15:18:37.358     at Service.resolveChainableWebpackConfig (F:\code\repo\xxx\node_modules\@vue\cli-service\lib\Service.js:242:26)
> [HBuilder] 15:18:37.364     at PluginAPI.resolveChainableWebpackConfig (F:\code\repo\xxx\node_modules\@vue\cli-service\lib\PluginAPI.js:151:25)
> [HBuilder] 15:18:37.364     at module.exports (F:\code\repo\xxx\node_modules\@vue\cli-service\lib\commands\build\resolveAppConfig.js:2:22)
> [HBuilder] 15:18:37.373     at getWebpackConfig (F:\code\repo\xxx\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:53:88)
> [HBuilder] 15:18:37.381     at getWebpackConfigs (F:\code\repo\xxx\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:89:32)
> [HBuilder] 15:18:37.382     at build (F:\code\repo\xxx\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:119:26)
> [HBuilder] 15:18:37.392     at F:\code\repo\xxx\node_modules\@dcloudio\vue-cli-plugin-uni\commands\build.js:44:11
> [HBuilder] 15:18:37.402     at Service.run (F:\code\repo\xxx\node_modules\@vue\cli-service\lib\Service.js:236:12)
> [HBuilder] 15:18:37.403     at Object.<anonymous> (F:\code\repo\xxx\node_modules\@vue\cli-service\bin\vue-cli-service.js:37:9)
> [HBuilder] 15:18:37.414     at Module._compile (internal/modules/cjs/loader.js:956:30)
> [HBuilder] 15:18:37.415     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
> [HBuilder] 15:18:37.426     at Module.load (internal/modules/cjs/loader.js:812:32)
> ```
> 
> https://github.com/dcloudio/uni-app/blob/aa60b3cc05cc99de69f3fc84af40214684677cd0/packages/uni-app-plus/lib/uni.config.js#L56-L63
> 
> 是少了什么插件？每次更新你们东西都提心吊胆的

npm run build:app-plus?

你执行下npm run info，然后贴一下环境信息，我看看是不是跟vue cli版本有关

**Comment by bigBron** [comment]
@fxy060608 
```js
uni-app v2.7.14
uni-app cli v2.0.0-27920200618002

Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 2.80GHz
  Binaries:
    Node: 12.13.0 - C:\Users\xxx\AppData\Local\Temp\yarn--1593329496004-0.26476464697123525\node.CMD
    Yarn: 1.15.2 - C:\Users\xxx\AppData\Local\Temp\yarn--1593329496004-0.26476464697123525\yarn.CMD    npm: 6.12.0 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.831.0
  npmPackages:
    @dcloudio/types: * => 1.0.2
    @dcloudio/uni-app-plus: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-automator: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @dcloudio/uni-cli-shared: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @dcloudio/uni-h5: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @dcloudio/uni-helper-json: * => 1.0.5
    @dcloudio/uni-migration: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @dcloudio/uni-mp-360: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @dcloudio/uni-mp-alipay: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @dcloudio/uni-mp-baidu: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @dcloudio/uni-mp-qq: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @dcloudio/uni-mp-toutiao: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @dcloudio/uni-mp-weixin: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @dcloudio/uni-quickapp-native: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @dcloudio/uni-quickapp-webview: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @dcloudio/uni-stat: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @dcloudio/uni-template-compiler: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-27920200618002 => 2.0.0-27920200618002
    @hap-toolkit/dsl-vue:  0.6.13
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  3.12.1
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  3.12.1
    @vue/cli-plugin-babel: ^3.12.0 => 3.12.1
    @vue/cli-service: ^3.12.0 => 3.12.1
    @vue/cli-shared-utils:  3.12.1
    @vue/component-compiler-utils:  3.1.2 (3.1.2)
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.11
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.3 (15.9.3)
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.2.0 => 3.4.0
  npmGlobalPackages:
    @vue/cli: Not Found
```

**Comment by fxy060608** [comment]
你的vue cli版本感觉很老啊。工程里的vue cli也比较老，现在最新的都4.4.6了，建议可以升级下最新的vue cli及相关依赖

**Comment by bigBron** [comment]
> 你的vue cli版本感觉很老啊。工程里的vue cli也比较老，现在最新的都4.4.6了，建议可以升级下最新的vue cli及相关依赖

vue-cli已经更新到最新的4.4.6，还是包一样的错误
`ERROR  TypeError: config.optimization.minimizer(...).tap is not a function`

难搞了，每次都不想更新的，但是你们那个云打包又是最新版本，不能选版本的

**Comment by bigBron** [comment]
@fxy060608  解决了，是@vue/cli-service版本太旧了。

说回@dcloudio/vue-cli-plugin-hbuilderx兼容dart-sass问题，
https://github.com/dcloudio/uni-app/blob/aa60b3cc05cc99de69f3fc84af40214684677cd0/packages/vue-cli-plugin-hbuilderx/build/css-loader.conf.js#L72-L90
既然nvue目前暂不支持vue.config.js配置，能不能把outputStyle改成expanded，这样就能最大程度兼容各种sass插件，我已经手动改这里用了好久，没发现额外问题

**Comment by AK47-dadada** [comment]
> @fxy060608 解决了，是@vue/cli-service版本太旧了。
> 
> 说回@dcloudio/vue-cli-plugin-hbuilderx兼容dart-sass问题，
> 
> https://github.com/dcloudio/uni-app/blob/aa60b3cc05cc99de69f3fc84af40214684677cd0/packages/vue-cli-plugin-hbuilderx/build/css-loader.conf.js#L72-L90
> 
> 
> 既然nvue目前暂不支持vue.config.js配置，能不能把outputStyle改成expanded，这样就能最大程度兼容各种sass插件，我已经手动改这里用了好久，没发现额外问题

兄弟，我现在cli项目也是提示outStyle找不到，有最终的解决方案没，求~
