### ISSUE TITLE
uni.chooseImage 是否能返回File对象

### ISSUE THREAD

**Issue by dying318** [dcloudio/uni-app#1510]
**新功能描述**
在尝试使用腾讯私信Web sdk发生图片消息的时候，sdk需要提供dom或者file作为图片消息参数，考虑多平台兼容所以用uni.chooseImage，但是这里返回的是tempFilePaths无法用作sdk的参数。
具体sdk参见：https://imsdk-1252463788.file.myqcloud.com/IM_DOC/Web/SDK.html#createImageMessage

**Comment by dying318** [comment]
很奇怪，我小程序环境下测试，对比官方的小程序demo，同样的的chooseImage success回调，res格式也相同，但是官方demo createImageMessage的结果是正常的，在uni项目下，createImageMessage生成的message的图片格式为unknown，大小也为0

**Comment by zhetengbiji** [comment]
> 很奇怪，我小程序环境下测试，对比官方的小程序demo，同样的的chooseImage success回调，res格式也相同，但是官方demo createImageMessage的结果是正常的，在uni项目下，createImageMessage生成的message的图片格式为unknown，大小也为0

你使用的这个sdk小程序和web端是否是用同一个sdk？如果有小程序版就用小程序版

**Comment by dying318** [comment]
`
// import TIM from 'tim-js-sdk';
import TIM from 'tim-wx-sdk';
// import COS from 'cos-js-sdk-v5';
import COS from 'cos-wx-sdk-v5';
`
使用的是小程序版本，两个版本测试效果是一样的。也对比了demo的sdk，同一个版本

**Comment by zhetengbiji** [comment]
> ```
> // import TIM from 'tim-js-sdk';
> import TIM from 'tim-wx-sdk';
> // import COS from 'cos-js-sdk-v5';
> import COS from 'cos-wx-sdk-v5';
> ```
> 
> 使用的是小程序版本，两个版本测试效果是一样的。也对比了demo的sdk，同一个版本，版本号也相同

你意思是一个uni-app工程和一个原始的小程序工程，引入同样的sdk，调用同一个方法，传入同样的参数，但是uni-app中的出现问题是吧？

**Comment by dying318** [comment]
对的，uni工程和官方的小程序demo，引入相同的sdk，一个是uni.chooseImage的success回调参数，一个是wx.chooseImage的success回调参数，没有处理直接传递给sdk的createImageMessage，返回的message不一致，uni-app中message的图片格式和大小数据都是空的

**Comment by dying318** [comment]
请问打算跟进吗？需要提供测试代码或者参数吗？

**Comment by zhetengbiji** [comment]
> 请问打算跟进吗？需要提供测试代码或者参数吗？

对的，在调用createImageMessage前先打印一下参数，看看有没有什么差异。
能提供测试工程和操作步骤最好。

**Comment by dying318** [comment]
```
<template>
    <div>
        <button @click="chooseImg">上传</button>
    </div>
</template>

<script>
    import TIM from 'tim-wx-sdk';

    export default {
        data() {
            return {}
        },
        mounted() {
            this.initIm()
        },
        methods: {
            initIm() {
                this.tim = TIM.create({
                    SDKAppID: '1400003872'
                });
                this.tim.login({
                    userID: 'user1',
                    userSig: 'eJyrVgrxCdYrSy1SslIy0jNQ0gHzM1NS80oy0zLBwqXFqUWGUInilOzEgoLMFCUrQxMDIDC2MDeCyJRk5qYCRU0tzE2MDSwszCGiqRUFmUVAcTMDEwsDA6gZmelAU419HB19CtySCoKzC0wK9NPLk00DvaN8U9y8Q8KSPSLKqjz9TS3KXQ3T-SJtlWoBuJEwtg__',
                })
            },
            chooseImg() {
                uni.chooseImage({
                    count: 1,
                    sourceType: ['album'],
                    success: res => {
                        let message = this.tim.createImageMessage({
                            to: 'user0',
                            conversationType: 'C2C',
                            payload: {file: res},
                            onProgress: () => {}
                        });
                        console.log(message)
                    }
                });
            },
        },
    }
</script>

```
可以查看`message.payload`判断是否创建正常。

**Comment by dying318** [comment]
请问测试是否有相同问题？

**Comment by zhetengbiji** [comment]
由于对应的改动已经发布，系统自动关闭了相关问题。

**Comment by zhetengbiji** [comment]
> 请问测试是否有相同问题？

我这测试小程序能打印 payload，H5端确实提示参数不符，目前新版已经支持返回File对象，你试试在H5端使用web版sdk传入File对象：payload: {file: res.tempFiles[0]}

**Comment by dying318** [comment]
payload是可以打印的，要查看下payload里面的参数是否正常，比如`imageFormat`是否正常

**Comment by dying318** [comment]
非正常的：
![Alt text](http://shobo-test.oss-cn-hangzhou.aliyuncs.com/WX20200420-111754@2x.png)
正常的：
![Alt text](http://shobo-test.oss-cn-hangzhou.aliyuncs.com/WX20200420-111900@2x.png)

**Comment by dying318** [comment]
H5中使用res.tempFiles[0]出现和小程序同样的payload，同样的报错。请问下，你那边的payload是正常的吗

**Comment by zhetengbiji** [comment]
> H5中使用res.tempFiles[0]出现和小程序同样的payload，同样的报错。请问下，你那边的payload是正常的吗

我新建了一个小程序工程（不使用uni-app）进行测试，返回的和使用uni-app测试一样。都是你说的这个非正常的返回。

你能否将你的两个对比工程发来？

**Comment by dying318** [comment]
[SDK下载](https://github-1252463788.cos.ap-shanghai.myqcloud.com/imsdk/TIMSDK.zip?_ga=1.117708801.927134297.1565084543)，使用文件夹里面的WXMini项目。
```
// 修改static/utils/GenerateTestUserSig.js

const _SDKAPPID = 1400003872;
const _SECRETKEY = 'ad65928afa5c03dfd14335ee49911acdd974a2e3805dc10a3cb1b703cb045d9e';

```
使用`user1`登录，如果会话列表空，在通讯录-发起会话输入`user0`;
可在pages/chat/index.vue中调试sendPhoto方法；

**Comment by zhetengbiji** [comment]
> 正常的返回是在官方的Demo中，非正常的就不发了。
> [Demo下载](https://github-1252463788.cos.ap-shanghai.myqcloud.com/imsdk/TIMSDK.zip?_ga=1.117708801.927134297.1565084543)，使用文件夹里面的WXMini项目。
> 
> ```
> // 修改static/utils/GenerateTestUserSig.js
> 
> const _SDKAPPID = 1400003872;
> const _SECRETKEY = 'ad65928afa5c03dfd14335ee49911acdd974a2e3805dc10a3cb1b703cb045d9e';
> 
> // 小程序开发者工具需要勾选不检验合法域名，或者使用appId: wx74fc5070f4d42182，配置了tim的request域名
> ```
> 
> 使用`user1`登录，如果会话列表空，在通讯录-发起会话输入`user0`;
> 可在pages/chat/index.vue中调试sendPhoto方法；
> 
> 麻烦了，十分感谢！

这样的话小程序测试和uni-app测试的方式差别很大呢
你没有试过新建小程序工程，然后用你上面的示例代码进行测试？
```
initIm() {
                this.tim = TIM.create({
                    SDKAppID: '1400003872'
                });
                this.tim.login({
                    userID: 'user1',
                    userSig: 'eJyrVgrxCdYrSy1SslIy0jNQ0gHzM1NS80oy0zLBwqXFqUWGUInilOzEgoLMFCUrQxMDIDC2MDeCyJRk5qYCRU0tzE2MDSwszCGiqRUFmUVAcTMDEwsDA6gZmelAU419HB19CtySCoKzC0wK9NPLk00DvaN8U9y8Q8KSPSLKqjz9TS3KXQ3T-SJtlWoBuJEwtg__',
                })
            },
            chooseImg() {
                wx.chooseImage({
                    count: 1,
                    sourceType: ['album'],
                    success: res => {
                        let message = this.tim.createImageMessage({
                            to: 'user0',
                            conversationType: 'C2C',
                            payload: {file: res},
                            onProgress: () => {}
                        });
                        console.log(message)
                    }
                });
            },
```

**Comment by zhetengbiji** [comment]
你用相同的逻辑测试，看结果是否不同：

新建小程序工程引入小程序SDK，用你这部分逻辑测试

新建Web工程引入WebSDK，用你这部分逻辑测试

不要用你这几行代码直接和这个复杂的demo进行对比，而且这个复杂的demo不是一个原始的小程序工程是一个mpvue的工程。

**Comment by dying318** [comment]
嗯，好的，我试一下。

**Comment by marlti7** [comment]
> 嗯，好的，我试一下。

同样问题 你解决了吗
