### ISSUE TITLE
取消监听网络状态变化bug

### ISSUE THREAD

**Issue by twb123** [dcloudio/uni-app#1511]
微信小程序上有个api：wx.offNetworkStatusChange.
uni-app文档上没有写，但是能够调用。调用的时候一直报错。
报错：offNetworkstatusChange should accept a function instead of object。
我传的确实是function。源码如下：
uni.offNetworkStatusChange(function (res) {
	console.log('end')
})

**Comment by zhetengbiji** [comment]
先直接调用 wx.offNetworkStatusChange

**Comment by twb123** [comment]
谢谢。可以直接调用 wx.offNetworkStatusChange()解决,不要带参数，带参数会报错
