### ISSUE TITLE
支付宝小程序下，grid组件下不能再用grid

### ISSUE THREAD

**Issue by ChenXiaoSong12321** [dcloudio/uni-app#1514]
**问题描述**
支付宝小程序下，grid组件下不能再用grid
原因：支付宝小程序如果组件以slot形式插入，该组件的this不会插入到在父节点的$children中
该问题会导致支付宝小程序下，有slot插入，父子关系的树无法生成，$parents/$children，provide/inject 等功能均失效

**复现步骤**
[复现问题的步骤]
1.  启动官方示例 Hello uni-app 项目
2. 将代码做此修改

![image](https://user-images.githubusercontent.com/22720517/78206860-8f0a6a00-74d2-11ea-8de5-bb44d5890445.png)

**预期结果**
生成正常的节点树结构

**实际结果**
报错

![image](https://user-images.githubusercontent.com/22720517/78206879-a0ec0d00-74d2-11ea-9917-62955542449c.png)

$parent,$children在slot插入后就没有了

**系统信息:**
 - 发行平台: [支付宝小程序]
 - uni-app版本 [
                  uni-app v2.6.5
                  uni-app cli v2.0.0-26520200314001
]

**Comment by ChenXiaoSong12321** [comment]
开启components2编译后解决

**Comment by Jewill** [comment]
@ChenXiaoSong12321 
大佬，你是怎么解决的，我这边还是出现问题，已经更新了最新版本的 uni-app 版本，并且开启了 components2编译，已经报错。

![image](https://user-images.githubusercontent.com/7111487/78229280-597d7500-7502-11ea-83e3-57f9bc5c00ef.png)

**Comment by ChenXiaoSong12321** [comment]
> @ChenXiaoSong12321
> 大佬，你是怎么解决的，我这边还是出现问题，已经更新了最新版本的 uni-app 版本，并且开启了 components2编译，已经报错。
> 
> ![image](https://user-images.githubusercontent.com/7111487/78229280-597d7500-7502-11ea-83e3-57f9bc5c00ef.png)

比较尴尬的是我搞错了，解决的是我另一个问题，这个issue我要reopen了

**Comment by hbcui1984** [comment]
请以真机效果为准，不同平台的开发者工具模拟器实现不一致。
