### ISSUE TITLE
全面屏  获取的键盘高度不对

### ISSUE THREAD

**Issue by 1438343098** [dcloudio/uni-app#1518]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
小米手机  开启全面屏模式 键盘高度获取出问题了
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
这个是input事件
handleFocusPl(e) {
				if (uni.getSystemInfoSync().platform === "android") {
					this.plBottom = e.detail.height + 'px'
				} else if (uni.getSystemInfoSync().platform === "ios") {
					this.plBottom = e.detail.height - 34 + 'px'
				}
				this.active = true
			},
**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]
安卓，全面屏都有

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
关闭全面屏模式获取的高度又高了，开启全面屏获取的键盘高度低了好多

**Comment by 1438343098** [comment]
uni.onKeyboardHeightChange    使用这个方法获取的是正确的

**Comment by StrivingRabbit** [comment]
使用 `uni.onKeyboardHeightChange` 获取
