### ISSUE TITLE
v3模式下，ios真机调试，配置{"titleNView": false}的BUG

### ISSUE THREAD

**Issue by tjztj** [dcloudio/uni-app#1519]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.在pages.json中，配置某一个页面的 titleNView 未 false；
2.在titleNView为false的页面中，使用方法：uni.setNavigationBarColor(）改变背景颜色与字体颜色；
3.使用 v3 模式ios真机调试
 
[或者可以直接贴源代码]

**预期结果**
改变手机通知栏颜色，同时隐藏默认的 nav ，使用自定义的 nav

**实际结果**
未隐藏默认的 nav，且会显示 nav 的标题为 view 或 当前路由地址

**系统信息:**
 - HBuilderX版本 2.6.7.20200326-alpha

**Comment by Wangyaqi** [comment]
此问题会在下个alpha版本修复

**Comment by tjztj** [comment]
> 此问题会在下个alpha版本修复

希望尽快吧。我ios只能不用v3打包，但是就会出现 这个 [https://ask.dcloud.net.cn/m/article/35627
](url)
