### ISSUE TITLE
crypto.getRandomValues() not supported

### ISSUE THREAD

**Issue by qinkaiyuan** [dcloudio/uni-app#1521]
**问题描述**
uniapp开发微信小程序
需要生成uuid
使用了npm uuid包

import { v4 as uuidv4 } from 'uuid';
uuidv4();

报错提示

crypto.getRandomValues() not supported.

查看官方论坛，其中说明app需要额外注意的地方说不支持 crypto.getRandomValues

可我这个是小程序为什么也不支持呢？还有未来什么时候会支持，这都一年多了

https://ask.dcloud.net.cn/article/35851

App额外注意事项
App使用自定义组件模式，Android会增加6M左右的包体积。原因是App端增加了一个独立的v8以减少js的阻塞。iOS不变化，因为iOS的jscore是iOS自带的。
离线打包的项目需要在原生工程里引入 ：离线sdk包里的liblibWeex.a库 和 weex-main-jsfm.js 和 weex-polyfill.js文件。
在自定义组件编译模式下，目前不支持crypto.getRandomValues方法，一些区块链应用的框架会用到此api，建议修改js源码绕过，或者改用老的模板编译模式。
在自定义组件编译模式下，uni.request 和 websocket 暂时不支持传输 ArrayBuffer 类型的数据，且 websocket 只能创建一个连接，有需求的用户可改用老的模板编译模式。

**Comment by dcloudhdx** [comment]
App 平台 HBuilderX 2.4.0+ 支持 crypto.getRandomValues 方法
微信小程序不支持 `https://developers.weixin.qq.com/community/develop/doc/000800f97c0790fbd7f86a93c51400`

**Comment by dcloudhdx** [comment]
最新版本已支持，长时间无回复，暂时关闭，如果仍然有问题可重新打开

**Comment by kingStrong2022** [comment]
HBuilderX 3.8.7 Android 平台 不支持 crypto.getRandomValues 方法

> 最新版本已支持，长时间无回复，暂时关闭，如果仍然有问题可重新打开

**Comment by ouou12138** [comment]
> 最新版本已支持，长时间无回复，暂时关闭，如果仍然有问题可重新打开

2025年这个功能还能支持吗
