### ISSUE TITLE
h5构建产物文件名太长

### ISSUE THREAD

**Issue by msdlisper** [dcloudio/uni-app#1523]
**问题描述**
比入产出了一个chunk, 可能长这样: 
`pages-card-all-questions~pages-card-index~pages-card-payment~pages-exit-exit~pages-index-h5-index~pa~83bbaec5.c9495214.js`

这个名字可以再长点不..

版本: 2.0.0-26120200226001

**Comment by msdlisper** [comment]
应该是内部做了动态加载的原因, 导致comment太长 [webpack import](https://webpack.js.org/api/module-methods/#import-1)

**Comment by fxy060608** [comment]
如果觉得这样的文件命名不好，可以自行修改vue.config.js
```javascript
module.exports = {
configureWebpack() {
        if (process.env.UNI_PLATFORM === 'h5') {// 仅限h5平台
            return {
                output: {
                    chunkFilename: "static/js/[contenthash].js"
                }
            }
        }
    }
}
```

**Comment by msdlisper** [comment]
感谢~  不过还是比较好好奇如何定制splitChunks的name, 因为`chunkFilename: "static/js/[contenthash].js"` 这种方式始终是把chunk的name给干掉了,不太友好..

**Comment by zhetengbiji** [comment]
> 感谢~ 不过还是比较好好奇如何定制splitChunks的name, 因为`chunkFilename: "static/js/[contenthash].js"` 这种方式始终是把chunk的name给干掉了,不太友好..

可以使用函数返回一个自定义的缩略名称（具体参考webpack文档）。
