### ISSUE TITLE
H5的input框的input事件不触发

### ISSUE THREAD

**Issue by SnowLittleStone** [dcloudio/uni-app#1526]
**问题描述**
在页面上放两个input框，一个登录按钮，在iOS上用uc浏览器打开，然后使用ios原生的键盘（调到简体拼音，这一步很重要），然后输入admin字母，直接输入admin这四个字母，直接输中间不要按键盘的换行，输完后直接点击第二个输入框，输入内容，点击登录时，第一个输入框输入的内容是空的，但是里面是有内容的。

<template>
	<view class="login">
		<view class="account">
			<text class="label">账号：</text>
			<input class="accountValue" placeholder="请输入账号" type="text" @input="accountInput" />
		</view>
		<view class="pw">
			<text class="label">密码：</text>
			<view class="inputView">
				<input class="pwValue" placeholder="请输入密码" type="text" :password="hidePw" @input="pwInput" />
				<text class="iconfont icon-bukejian visible" v-if="hidePw" @click="pwVisibleClicked"></text>
				<text class="iconfont icon-kejian visible" v-else @click="pwVisibleClicked"></text>
			</view>
		</view>
		<button class="loginBt" @click="loginClicked">登录</button>
	</view>
</template>
export default {
		data() {
			return {
				accountValue: "",
				pwValue: "",
				hidePw: true
			};
		},
		onUnload() {
			setIsInLoginPage(false);
		},
		methods: {
			accountInput(e) {
				alert(e.target);
				this.accountValue = e.target.value;
			},
			pwInput(e) {
				this.pwValue = e.target.value;
			},
			pwVisibleClicked() {
				this.hidePw = !this.hidePw;
			},
			loginClicked() {
				if (this.accountValue.trim() === "") {
					this.$toast("请输入账号");
					return;
				}
				if (this.pwValue.trim() === "") {
					this.$toast("请输入密码");
					return;
				}

				var playload = {
					"username": this.accountValue.trim(),
					"password": md5(this.pwValue.trim()).toLowerCase()
				};
				this.$sendPost({
					type: this.$apiType.Login,
					payload: playload,
					needLogin: false,
					success: (res) => {
						setUserInfo(res.userId, res.token, this.accountValue);
						uni.$emit(EventName.LoginEvent);
						uni.switchTab({
							url: "../contract/contractList"
						});
					}
				});
			},
		}
	}
</script>

**系统信息:**
 - 发行平台: H5平台
 - 操作系统: iOS 13.4
 - HBuilderX版本:2.6.9.20200403
 - 设备信息:iPhone8

**Comment by SnowLittleStone** [comment]
在微信小程序上，版本库大于2.9.3，输入法改成手写，在华为、小米部分手机最后一个字在input事件中获取不到。（操作方式，用手写依次输入，不要选择字，直接打字，然后在最后一个字下面显示光标的状态下，直接点击第二个输入框，这样第一个输入框获取的元素就少一个字），调试出来发现input事件中的值只有前几个字，最后一个没有

**Comment by zhetengbiji** [comment]
HBuilderX 2.9.0+ 已修复
