### ISSUE TITLE
canvas的@touchstart方法在Android上每次点击获取的位置一样

### ISSUE THREAD

**Issue by sy1995** [dcloudio/uni-app#1528]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
canvas的@touchstart方法在Android上每次点击获取的位置一样
**复现步骤**
[复现问题的步骤]
@touchstart="touchMethod($event)
touchMethod(e){
	console.log(e.touches[0])
	//手指的位置
	const x = e.touches[0].x
	const y = e.touches[0].y

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
每次点击获得当前位置
**实际结果**
[这里请贴上你的报错截图或文字]
在Android上点击每次都到相同位置

**系统信息:**
 - 发行平台: QQ小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 任一Android设备，iOS和h5没问题

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
需要把bug报告到QQ小程序社区
