### ISSUE TITLE
cover-view

### ISSUE THREAD

**Issue by Kevin-ox** [dcloudio/uni-app#153]
cover-view 相同css代码在小程序和app上样式展示不同

**Comment by xiaoyucoding** [comment]
* 5+App中 cover-view、cover-image 中不支持嵌套其它组件。
* 5+App中暂不支持 cover-view、cover-image 组件之间的嵌套。

详见文档：[https://uniapp.dcloud.io/component/cover-view?id=cover-view](https://uniapp.dcloud.io/component/cover-view?id=cover-view)

**Comment by Kevin-ox** [comment]
什么时候能统一 有排期计划吗

**Comment by xiaoyucoding** [comment]
> 什么时候能统一 有排期计划吗

暂时没有明确的计划公布，请关注更新日志及社区公告。

**Comment by Kevin-ox** [comment]
期待！
