### ISSUE TITLE
接入澳门支付

### ISSUE THREAD

**Issue by sohenk** [dcloudio/uni-app#1531]
**新功能描述**
我是澳门这边的开发商，觉得uniapp不错，但是想问一下可否接入澳门支付（macaupay澳门通）呢

**现状及问题**
现在只有国内主流的支付。但是澳门的还没有，希望引入

**Comment by hbcui1984** [comment]
建议方案：
1、将澳门支付封装为原生SDK，发布到插件市场（[https://ext.dcloud.net.cn/](https://ext.dcloud.net.cn/?cat1=5&cat2=51)）
2、离线打包，通过原生SDK集成的方式实现

但两种方案都需要具备原生开发基础。

产品短期内不会将澳门支付集成到主产品线中。

**Comment by zsirfs** [comment]
@sohenk 你们可以赞助。然后应该就会有实现

**Comment by eastjie** [comment]
我们也集成了国际支付，通过第三方的支付公司的API，调用最基本UNI-APP的HTTP，是没有问题的，和基本的javascript太多的区别，只要对应的数据正确传输入API就好了，这个应该属于非常小的plugin

**Comment by shinken008** [comment]
> @sohenk 你们可以赞助。然后应该就会有实现

有钱能使鬼推磨

**Comment by kokiy** [comment]
> **新功能描述**
> 我是澳门这边的开发商，觉得uniapp不错，但是想问一下可否接入澳门支付（macaupay澳门通）呢
> 
> **现状及问题**
> 现在只有国内主流的支付。但是澳门的还没有，希望引入

你是做赌场的吗

**Comment by YienCheng** [comment]
澳门du厂开业啦！性感荷官，在线发牌～

**Comment by Valar103769** [comment]
澳门是中国的领土, 必须使用大陆流行的支付宝, 微信等, 自己搞一套就是企图分裂国家  哼
