### ISSUE TITLE
VUEX在view中的数据绑定

### ISSUE THREAD

**Issue by hongweishang** [dcloudio/uni-app#1532]
**问题描述**
在view中使用Store进行数据绑定， 发现不生效。
请问这是bug还是uniapp不支持这样的使用方式？

[或者可以直接贴源代码]
<view>{{$store.getters.user.nickname}}</view>

**预期结果**
可以实现数据绑定， （VUE中是可以的）

**实际结果**
界面始终显示undefined， 即使在store中commit数据之后依然显示undefined。

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Wangyaqi** [comment]
小程序端暂不支持这种写法
