### ISSUE TITLE
pages.json虽然支持条件编译，但还是静态的不方便

### ISSUE THREAD

**Issue by hugetiny** [dcloudio/uni-app#1533]
问题描述
因为是静态的
所以改变主题（暗黑模式）等不行
原生navbar在pages.json里面配，定了就不能变了。有什么方法能实现类似主题切换等效果
还有国际化时候，pages.json是静态的也不方便

预期结果
pages.json里的字段能够用变量控制

系统信息:

发行平台: [调试H5]
操作系统 [Windows10]
HBuilderX版本 [2.6.8]

**Comment by hugetiny** [comment]
还有标题动态文字等，希望全局暴露些变量 能控制下

**Comment by Otto-J** [comment]
哦，这个好像有了
https://uniapp.dcloud.net.cn/tutorial/i18n.html#pages
