### ISSUE TITLE
给checkbox添加color属性修改选中之后的颜色无效

### ISSUE THREAD

**Issue by littleBelle** [dcloudio/uni-app#1535]
**问题描述**
给checkbox添加color属性修改选中之后的颜色无效

**复现步骤**
[复现问题的步骤]
<checkbox :value="item.id" color="#007AFF" style="transform:scale(0.7)"/>{{item.name}}

**预期结果**
希望能修改选中之后的颜色

**实际结果**
选中之后在小程序中显示还是绿色
**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**

**Comment by littleBelle** [comment]
<checkbox :value="item.id" color="#007AFF" style="transform:scale(0.7)"/>{{item.name}}

**Comment by mehaotian** [comment]
贴一下代码片段
