### ISSUE TITLE
canvasPutImageData 不起作用 

### ISSUE THREAD

**Issue by woaigmz** [dcloudio/uni-app#1538]
问题：uni.canvasPutImageData 方法没有报错，但是无法渲染到画布 Canvas 上
调用:

				const blurImage = await that._getBlurImageData(ctx,logo.path,that);
				var isComplete = await that._ctxPutImage(blurImage,that);
				console.log("isComplete",isComplete)

方法
1: getImageData 并高斯模糊 图片像素数组

			async _getBlurImageData(ctx,path,that){
				ctx.drawImage(path,0,0,that.sysWidth,that.canvasHeight);
				return new Promise((resolve,reject)=>{
					ctx.draw(false,()=>{
						uni.canvasGetImageData({
							canvasId:'shareCanvas',
							x:0,
							y:0,
							width:that.sysWidth,
							height:that.canvasHeight,
							success: (res) => {
								console.log("res",res);
								const ret = stackBlurCanvasRGBA(res,that.sysWidth/2);
								console.log("ret",ret);
								resolve(ret)
							},
							fail: (err) => {
								reject(err)
							}
						},that);
					},that)
				})
			}

2: 将图像数组渲染到 Canvas

			async _ctxPutImage(blurImage,that){
				return new Promise((resolve,reject)=>{
					uni.canvasPutImageData({
						canvasId:'shareCanvas',
						x:0,
						y:0,
						width:blurImage.width,
						height:blurImage.height,
						data: blurImage.data,
						success: (res) => {
							console.log("success",res)
							resolve(true)
						},
						fail: (err) => {
							console.log("error",err)
							reject(false)
						}
					},that);
				})	
			}

**Comment by woaigmz** [comment]
get put ，之后不能再添加其他 方法操纵 canvas

**Comment by lmxdawn** [comment]
> get put ，之后不能再添加其他 方法操纵 canvas

麻烦问下，你uniapp 使用 canvas 怎么实现的高斯模糊
