### ISSUE TITLE
否有某种写法可以将不用于wxml的数据挂载到 vm.__data 上，避免传入到data中

### ISSUE THREAD

**Issue by lbb00** [dcloudio/uni-app#1539]
**新功能描述**
运行小程序性能工具，检查发现提醒：

> 存在将未绑定在 WXML的变量传入setData。

是否有某种写法可以将不用于wxml的数据挂载到 vm._data 上，避免传入到data中。

**现状及问题**

有一些需要处理的长列表，但这些列表本身并不会用于wxml上的渲染，但会导致小程序性能方面的问题

**Comment by fxy060608** [comment]
可以考虑，不过目前阶段，如果你不需要再模板上渲染，那直接不写在data里就行了吧

**Comment by loveonelong** [comment]
@fxy060608 
https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/pure-data.html
我在微信文档中开到了这个配置，纯数据字段。
不清楚uniapp是否可以适配一下

**Comment by loveonelong** [comment]
如果能支持options的配置，让小程序自己来完成这个适配也是极好的
