### ISSUE TITLE
@input 在自定义组件中报错

### ISSUE THREAD

**Issue by magicwing** [dcloudio/uni-app#1541]
**问题描述**
		把input放在自定义组件中@input报错

**复现步骤**
		0、把input放到自定义组件中
		1、引用自定义组件并在输入框随便输入东西
		2、点击外部空白区域，此时键盘回缩
		3、再点击输入框，此时键盘弹出
		4、这个时候调试输出区域提示thirdScriptError：onChange is not a function

[或者可以直接贴源代码]
demo代码
[demo.zip](https://github.com/dcloudio/uni-app/files/4454162/demo.zip)

**实际结果**
详细操作动画
![1](https://user-images.githubusercontent.com/7157683/78860497-f2614280-7a64-11ea-91fc-d75b741f37f9.gif)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 Android 7.0
 - HBuilderX版本 2.6.5
 - 设备信息 红米Note4

**Comment by benlypan** [comment]
这个事件不知道为啥传递到包含了这个自定义组件的 Page 那个模块去了。我暂时在 Page 那个级别的 methods 里加同名事件函数把这个错误给吸收了。这个 bug 存在好久好久了。

**Comment by magicwing** [comment]
好的，暂时按照提供的方法处理
