### ISSUE TITLE
小程序编译scss时没有区分预编译平台标识

### ISSUE THREAD

**Issue by magicwing** [dcloudio/uni-app#1542]
**问题描述**
HBuilderX2.6.9版本 小程序编译scss时没有区分预编译平台标识，会去判断APP-PLUS预编译标识下 src 文件是否存在，造成编译失败

**预期结果**
HBuilderX2.6.5版本没有问题

**实际结果**
[报错.zip](https://github.com/dcloudio/uni-app/files/4454203/default.zip)

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本 2.6.9

**Comment by fxy060608** [comment]
临时解决方案：
直接写绝对路径试试
```
src: url('/static/uni.ttf') format('truetype');
```
