### ISSUE TITLE
form表单提交函数无法获取picker的name值

### ISSUE THREAD

**Issue by Yangson-Hung** [dcloudio/uni-app#1545]
**问题描述**
form组件内的picker组件设置了name属性，点击设置了form-type属性的button，返回值里没有picker的name属性的变量值
**代码**
精简过
```vue
<form @submit="formSubmit" @reset="formReset">
    <picker name="picker" @change="bindPickerChange" :value="index" :range="array" range-key="name">
        <view class="uni-input">{{array[index].name}}</view>
    </picker>
    <view class="uni-btn-v">
        <button form-type="submit">Submit</button>
	<button type="default" form-type="reset">Reset</button>
    </view>
</form>
```
```js
    formSubmit: function(e) {
       console.log('form发生了submit事件，携带数据为：' + JSON.stringify(e.detail.value))
    }
```
![image](https://user-images.githubusercontent.com/32238889/78895864-2149d980-7aa2-11ea-8e41-d6bfc5d07c59.png)

**预期结果**
点击submit按钮后，返回值里要有picker的name属性变量picker值的，实际没有

**实际结果**
![image](https://user-images.githubusercontent.com/32238889/78895651-ce702200-7aa1-11ea-81e6-6e8fee368e3c.png)
![image](https://user-images.githubusercontent.com/32238889/78895964-476f7980-7aa2-11ea-99b2-2d9773c9654d.png)

**系统信息:**
 - 发行平台: 5+app
 - 操作系统: Android 9.0
 - HBuilderX版本 2.6.9.20200403
 - uni-app版本 
 - 设备信息 坚果Pro3

**补充信息**
在H5平台测试过了，没有问题

**Comment by kidEckel** [comment]
我也遇到，可以看下我的(1534)，原因就是因为V3编译，可以看下2.6.9的更新日志，app编译默认V3编译

**Comment by Wangyaqi** [comment]
此问题会在下个alpha版本修复

**Comment by zhetengbiji** [comment]
HBuilderX 2.6.12 alpha 已修复
