### ISSUE TITLE
执行同步变成异步

### ISSUE THREAD

**Issue by Dave-miao** [dcloudio/uni-app#1547]
以前这样写可以
let _this = this;
uni.getStorage({
   key: 'userId',
   success: res => {
	_this.userId = res.data;
   },
 });
_this.getInfo();
现在_this.getInfo()方法里面获取不到缓存赋值的userId
let _this = this;
uni.getStorage({
	key: 'userId',
	success: res => {
		_this.userId = res.data;
		_this.getInfo()
	},
});
这样写才可以
有什么好的解决方法吗除了Vuex.Store

**Comment by fxy060608** [comment]
uni.getStorage 本身就是异步方法
换成 uni.getStorageSync
参考文档：https://uniapp.dcloud.io/api/storage/storage?id=getstoragesync
