### ISSUE TITLE
video标签暂停播放之后controls不见了，再次点击视频也不出来controls

### ISSUE THREAD

**Issue by Duanzihuang** [dcloudio/uni-app#1548]
**问题描述**
当我们使用video标签播放视频的时候，他有控制条(controls)，但是一旦点击了暂停播放，controls就消息了，并且点击视频也不再出来了。

[或者可以直接贴源代码]
<video
        autoplay
        :src="http://wxsnsdy.tc.qq.com/105/20210/snsdyvideodownload?filekey=30280201010421301f0201690402534804102ca905ce620b1241b726bc41dcff44e00204012882540400&bizid=1023&hy=SH&fileparam=302c020101042530230204136f"
        :controls="true"
      ></video>

**Comment by dcloudhdx** [comment]
HBuilderX 版本多少，运行到哪个平台？

**Comment by y1324** [comment]
官方demo也有这个问题，运行在微信小程序上。

**Comment by zzlbt** [comment]
没人解决吗，我也碰到这个问题了

**Comment by zzlbt** [comment]
运行在手机上就好了，在微信模拟器上面不行

**Comment by dcloudhdx** [comment]
微信小程序的问题，以真机为准，长时间无回复，暂时关闭
