### ISSUE TITLE
在某些设备上会出现 $refs undefined 及 $emit 事件丢失问题

### ISSUE THREAD

**Issue by LoeiFy** [dcloudio/uni-app#1549]
**问题描述**

出现是组件引入组件的情况下，但 page 引入组件不会出问题

**复现步骤**

![2](https://user-images.githubusercontent.com/2193211/78970174-476f8800-7b3b-11ea-9a21-c0353b3799c0.png)

如果这个组件引入多个组件的话，后面的 ref 组件会覆盖掉前面的，然后全部都是 undefined

另外 $emit 也会丢失，无法触发

**预期结果**

但如果是 page 引入组件，就不存在这个 undefined 问题

$emit 也正常触发

![1](https://user-images.githubusercontent.com/2193211/78970189-4e969600-7b3b-11ea-87e1-322e19971267.png)

平台是飞书的小程序平台，代码不好展示，想了解下出现这种状况大概原因是什么，或者有什么相关思路

**Comment by EryouHao** [comment]
请问 $emit 这个 bug 解决了吗？我也遇到了，使用开发者工具（IDE）是可以正常触发的，使用客户端预览就失效了
