### ISSUE TITLE
transparentTitle设置成auto滑动自适应一开始看不见标题

### ISSUE THREAD

**Issue by Kole6** [dcloudio/uni-app#1550]
**问题描述**
page.json 的 transparentTitle设置成auto滑动自适应一开始看不见标题
进入设置成滑动自适应的页面后，导航栏透明是透明的，文字也没了，文字标题开始的时候显示不出来，文字需要在渐变的过程中改变颜色

```
{
			"path": "pages/index",
			"style": {
				"navigationBarTitleText": "报告",
				"navigationBarTextStyle": "white",
				"navigationBarBackgroundColor": "#6451FC",
				"transparentTitle": "auto"
			}
		}
```

**Comment by dcloudhdx** [comment]
是这样的效果

**Comment by Kole6** [comment]
怎样一开始让文字显示出来，然后背景渐变呢

**Comment by mehaotian** [comment]
如果文字在一开始就显示出来，在很多场景下 会导致视觉上的错误 ， 对比度不够，很难分清那个是内容，那个是标题，所以背景透明不会显示文字，只有背景从透明渐变到不透明标题文字才会渐变显示出来。
