### ISSUE TITLE
Error: No matching use for foo.js

### ISSUE THREAD

**Issue by huahua0** [dcloudio/uni-app#1551]
**问题描述**
![image](https://user-images.githubusercontent.com/38969316/78983206-56afff00-7b56-11ea-8f5d-fa994ef45ade.png)

**复现步骤**
[复现问题的步骤]
最新安装node_modules，启动时报错

**Comment by fxy060608** [comment]
贴一下npm run info

**Comment by ImKarson** [comment]
遇到同样问题

**Comment by ufologist** [comment]
错误是 `vue-cli-plugin-uni/lib/configure-webpack.js` 抛出的, 定位在 `updateJsLoader` 上, `vue-cli-plugin-uni` 的版本是: `2.0.0-25120200103006`

尝试注释了 `updateJsLoader` 方法后, 就不会抛出错误了

查找官方的最新版本, 发现 `vue-cli-plugin-uni@2.0.0-alpha-27620200521003` 已经解决了这个问题, 因此尝试修改了一下 node_modules 文件夹中的 [`vue-cli-plugin-uni/lib/configure-webpack.js`](https://github.com/dcloudio/uni-app/blob/13980d00e3e09d9c1930908a93a5297898923584/packages/vue-cli-plugin-uni/lib/configure-webpack.js#L166) 就没有这个问题了

```javascript
// js preprocess
updateJsLoader(rawRules, 'foo.js', /^babel-loader|(\/|\\)babel-loader/, {
  loader: resolve('packages/webpack-preprocess-loader'),
  options: jsPreprocessOptions
})
```
