### ISSUE TITLE
picker组件的value值设为-1时，在APP、H5和微信小程序平台，返回结果不一样

### ISSUE THREAD

**Issue by Yangson-Hung** [dcloudio/uni-app#1553]
**问题描述**
picker组件的value值设为-1，在app，H5端选择第一个时，返回值为-1，无法选择picker的range内容的第一项，但是在编译到微信小程序平台，可以选择。

**代码**
![image](https://user-images.githubusercontent.com/32238889/78994042-c97aa380-7b71-11ea-87ce-5fbb0779d2d3.png)
![image](https://user-images.githubusercontent.com/32238889/78994180-08105e00-7b72-11ea-9cab-9d6424f33e56.png)
![image](https://user-images.githubusercontent.com/32238889/78994184-08a8f480-7b72-11ea-86b4-5a277df23530.png)

**结果**
app平台结果：
![image](https://user-images.githubusercontent.com/32238889/78994253-2d04d100-7b72-11ea-8e0e-d07dc4de9875.png)
H5结果：
![image](https://user-images.githubusercontent.com/32238889/78994282-39892980-7b72-11ea-94ee-c0730da4b332.png)
微信小程序结果：
![image](https://user-images.githubusercontent.com/32238889/78994306-49087280-7b72-11ea-9310-f199058c3858.png)

**说明**
app和H5平台都不能选择picker组件range属性的内容第一项，但是微信小程序可以。
app和H5平台返回值为-1，类型number；小程序返回0，类型string

**系统信息:**
 - 发行平台: 微信小程序、H5平台、5+ App
 - 操作系统 Android 9.0、电脑谷歌浏览器、微信小程序官方客户端
 - HBuilderX版本 2.6.9.20200403
 - uni-app版本 
 - 设备信息 坚果PRO3

**补充说明**

![image](https://user-images.githubusercontent.com/32238889/78994881-ba94f080-7b73-11ea-9ffb-cdfa9dc15af9.png)

![image](https://user-images.githubusercontent.com/32238889/78994698-4d815b00-7b73-11ea-9d45-cf32aac6c9aa.png)

直接点击确定无法选择，出现上述情况。但是如果手指稍微上下滑动红色框区域，让它动一下，点击确定就能选择第一项。
![image](https://user-images.githubusercontent.com/32238889/78994837-9b965e80-7b73-11ea-8064-e8f87bc39bb3.png)

**Comment by Fasttian** [comment]
确认bug，等待修复。h5 和 andriod 有这个问题，小程序和 iOS 正常。
