### ISSUE TITLE
多页面使用WebView时报错，提示请求的页面无法打开

### ISSUE THREAD

**Issue by EThan-Jam** [dcloudio/uni-app#1554]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
例如:
**A** 页面有一个 webview ，**B** 页面 也有一个 webview,
需求是: A页面webView里的内容被点击了并且返回消息给A页面接收并使用uni.navigateTo打开B页面,进行访问 A页面传递过来的url ，但是返回的时候，IDE 编译时 就提示一个错误 红色的"error"和一串消息 **请求的页面无法打开：file:///storage/emulated/0/Android/data/io.dcloud.HBuilder/apps/HBuilder/www/pages/detail/http:/www.baidu.com at file:///android_asset/data/dcloud_error.html:41**  
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
    启动A 页面的 webview 并打开指定的url，呈现数据
2. 点击  '....'
   点击 A 页面中的 某一数据项，向 A 页面的WebView的 @onPostMessage 接收数据，并使用
uni.navigateTo 打开 B 页面，
3. 查看
     使用 B 页面的 webview 展现 A 页面传递过来的 url
[或者可以直接贴源代码]
   **A 页面**
    <template>
	<view class="web-view">
		<web-view class="web-view" :src="url" ref="webview" @pagestart="onPageStart" @onPostMessage="handlePostMessage"
		 @pagefinish="onPageFinish" @error="onError" @receivedtitle="onReceivedTitle"></web-view>
		<view class="sendMessage">
			<button type="primary" @click="sendMessageToWebview">点我给webview传参</button>
		</view>
	</view>
</template>

<script>
	var currentWebview;
	export default {
		data() {
			return {
				params: {},
				url: 'http://www.jalon888.com/webview.html',
				webviewStyles: {
					progress: '#FFFFFF'
				},
				pagestart: '',
				pagefinish: '',
				error: '',
				canGoBack: false,
				canGoForward: false,
				PageStart: false, // 记录网页请求的加载状态，true 加载成功 false 加载失败
			};
		},
		onLoad() {
			var pages = getCurrentPages();
			var page = pages[pages.length - 1];
			currentWebview = page.$getAppWebview();
			console.log(currentWebview);
		},
		methods: {
			handlePostMessage: function(data) {
				uni.navigateTo({
					// url 是百度链接: www.baidu.com
					url:"../../pages/detail/detail?url="+data.url
				})
			},
			onPageStart: function(e) {
				console.log(e);
				// 监听页面加载成功
				this.PageStart = true;
				// 其实页面也可以使用这个方法传参
				//this.$refs.webview.evalJs("setLoginToken('我就是个参数啊')");

			},
			onPageFinish: function(e) {
				console.log('onPageFinish')
				this.pagefinish = e.url;
				this.canGoBack = e.canGoBack;
				this.canGoForward = e.canGoForward;
				var tn = currentWebview.getStyle().titleNView;
				tn.titleText = e.detail.title || '第三方网站';
				currentWebview.setStyle({
					titleNView: tn
				});

			}
		
		}
	};
</script>

  B 页面

  <template>
	<view>
		<web-view :src="weburl"></web-view>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				weburl:""
			}
		},
		methods: {
			
		},
		onLoad(options){
			if(options.url){
				this.weburl=options.url
			}
		}
	}
</script>

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
  能够打开B页面的内容，并可以回退到A页面,如果有错误，希望能够返回错误的详细信息
**实际结果**
[这里请贴上你的报错截图或文字]
IDE 提示的错误信息
![image](https://user-images.githubusercontent.com/16119369/79072965-6e35e600-7d16-11ea-989f-20fb6241f950.png)

测试机提示的信息
![image](https://user-images.githubusercontent.com/16119369/79072969-768e2100-7d16-11ea-9fc2-29a5510c2c48.png)

**系统信息:**
 - 测试平台: 
   小米 MAX 2 
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
   MIUI：11.0.2 稳定版    
   Android :7.1.1
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
   2.6.11.20200409
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
    uni-app
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by EThan-Jam** [comment]
发现问题所在了，如果动态的为 webview 的src 赋值，是不成功的，
![image](https://user-images.githubusercontent.com/16119369/79073514-aa1e7a80-7d19-11ea-852f-3eda3d7cb33c.png)
静态赋值时可以的
![image](https://user-images.githubusercontent.com/16119369/79073519-b0145b80-7d19-11ea-8f99-b88396cea720.png)

**Comment by EThan-Jam** [comment]
通过某个微信群里的大佬介绍，可以通过全局变量进行传递，并且在组件的 onShow 是可以动态传值和绑定的，但是不是很稳定(偶尔也会报错)，不知道这是不是一个Bug

**Comment by dcloudhdx** [comment]
验证没有问题，注意：@onPostMessage e.detail.data 为 Array 类型

**Comment by EThan-Jam** [comment]
> 验证没有问题，注意：@onPostMessage e.detail.data 为 Array 类型

嗯嗯，谢谢，已解决了
