### ISSUE TITLE
@tap和uni.navigateTo组合快速点击会触发多次，多次跳转

### ISSUE THREAD

**Issue by Kole6** [dcloudio/uni-app#1557]
**问题描述**
@tap和uni.navigateTo组合快速点击会触发多次，多次跳转

**复现步骤**
在@tap事件下放入uni.navigateTo页面跳转，快速点击会出现多次跳转到相同的页面

**系统信息:**
 - 发行平台: [5+ App]
 - 操作系统 [iOS、Android]
 - HBuilderX版本 [2.6.11]

**补充信息**
@click也是一样

**Comment by Kole6** [comment]
有没有阻止第二次的办法

**Comment by xlgzsgf** [comment]
自己做防抖
