### ISSUE TITLE
iOS应用如何开启相册权限

### ISSUE THREAD

**Issue by luvletterldl** [dcloudio/uni-app#1561]
**问题描述**
编译到iOS原生应用如何开启相册权限

Android平台直接可以在APP模块权限配置里面勾选，iOSApp怎么开启

**Comment by dcloudhdx** [comment]
ios是动态权限，运行时申请，参考hello uni-app 示例
`
https://github.com/dcloudio/hello-uniapp/tree/master/pages/API/image
`
