### ISSUE TITLE
Android BLE中传输数据的最大长度

### ISSUE THREAD

**Issue by CodeMonkeyLin** [dcloudio/uni-app#1562]
**问题描述**
Android BLE中传输数据的最大长度怎么解决

**Comment by dcloudhdx** [comment]
系统与蓝牙设备会限制蓝牙4.0单次传输的数据大小，超过最大字节数后会发生写入错误，建议每次写入不超过20字节
如果数据过长不建议使用 BLE

**Comment by longbomb** [comment]
赶紧出MTU设置吧，小程序都已经弄出来了，现在项目卡在这里没法做

**Comment by dcloudhdx** [comment]
下次发版支持

**Comment by dcloudhdx** [comment]
HBuilderX 2.8.5+ 新增 支持蓝牙相关接口 uni.setBLEMTU、uni.getBLEDeviceRSSI

**Comment by CodeMonkeyLin** [comment]
是否可以考虑直接支持获取原始字节，这样就不用单个写方法获取扫描信息了,android方法为getBytes
https://developer.android.google.cn/reference/android/bluetooth/le/ScanRecord#getBytes()
