### ISSUE TITLE
报bug：nvue 页面 将数据返回上一页异常

### ISSUE THREAD

**Issue by jnuchu** [dcloudio/uni-app#1563]
`back() {
//把结果返回到上一菜单
var pages = getCurrentPages();
pages[pages.length - 2].setData({					
    id: this.id					
}); 
				
uni.navigateBack({
    delta: 1
});
}`

**此段代码在vue页面可正常使用，将id传到上一页，在nvue页面 pages[pages.length - 2] 语句报undefined ，应该为bug。**

**Comment by fxy060608** [comment]
1. setData方法不跨平台，不要使用该方式修改数据
2.跨页面通讯，可以使用uni.$on,uni.$emit 通讯：https://ask.dcloud.net.cn/article/36010
