### ISSUE TITLE
使用new Blob时报错Can't find variable: Blob

### ISSUE THREAD

**Issue by xlgzsgf** [dcloudio/uni-app#1564]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
项目中用到了Blob，**真机调试**时出现的BUG
打开“调试”就不会报错，另外有些正则表达式也是这样
查阅社区发现应该不是个例：
这个帖子：https://ask.dcloud.net.cn/question/80509
底下近两天的评论都复现了这个BUG

**复现步骤**
let blob = new Blob([buffer]);

**预期结果**
正常返回Blob

**实际结果**
ReferenceError: Can't find variable: Blob

**系统信息:**
 - 发行平台: UNIAPP APP端
 - 操作系统 Android 9
 - HBuilderX版本 V2.6.12 alpha

**Comment by zhetengbiji** [comment]
非H5端不是浏览器环境不支持 Dom、Bom 接口，没有 Blob 也没有 document 。
这在uni-app文档开篇的介绍中有说明：[相关文档](https://uniapp.dcloud.io/matter?id=区别于传统-web-开发的注意)
