### ISSUE TITLE
建议支持tabBar的midButton作为tabbar页面使用

### ISSUE THREAD

**Issue by xlgzsgf** [dcloudio/uni-app#1567]
**新功能描述**
建议支持设置midButton的pagePath参数。
如果没有设置则作为按钮，否则作为页面。

**现状及问题**
现在midButton只支持监听点击事件，如果不用前端模拟tabbar，需要跳转页面只能uni.navigateTo()，tabbar就会隐藏，非常影响用户体验。

**Comment by madongbao** [comment]
这个这么久了也没人解决么？都2023年了

**Comment by zhetengbiji** [comment]
> 这个这么久了也没人解决么？都2023年了

是的，三年也没有其他人附言的新需求评估优先级比较低

**Comment by madongbao** [comment]
中间凸起按钮这么难实现么？三年也不给改一下

**Comment by zhetengbiji** [comment]
> 中间凸起按钮这么难实现么？三年也不给改一下

中间凸起按钮是有的，但是作为 tab 页面的需求目前是很少的，如果需求的人多了可以开始评估
