### ISSUE TITLE
关于wx.serviceMarket.invokeService

### ISSUE THREAD

**Issue by hjj5258** [dcloudio/uni-app#1569]
**新功能描述**
如何在uni-app里设置wx.serviceMarket.invokeService的兼容性?

**现状及问题**
[当前现状及由此导致的不便]
无法通过wx.serviceMarket.invokeService来调用一些认证相关的接口
**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]
pages.json、manifest.json中设置过
**补充信息**
[其它你认为有参考价值的信息]
![image](https://user-images.githubusercontent.com/30062564/79525059-90bc5c00-8094-11ea-96e3-d482e029c524.png)

**Comment by hjj5258** [comment]
可以通过兼容性配置让 wx.serviceMarket.invokeService API 的使用不受基础库版本约束，配置方式是：在 app.json / game.json 中指定顶层字段 "servicemarket": true，在预览发布时小程序代码包会自动包含此 API 的兼容代码，在 2.9.4 以下也可使用。仅在手机上使用，工具中调试请选择 2.9.4 基础库。

**Comment by Wangyaqi** [comment]
可以在`manifest.json`内的`mp-weixin`下配置
