### ISSUE TITLE
对于vue-cli 命令行创建项目打包详细说明

### ISSUE THREAD

**Issue by XcGuaN-miepia** [dcloudio/uni-app#1573]
**问题描述**
根据官网文档使用 npm run build:app-plus 之后生成文件到 dist 文件夹内，但是如何打包成 apk 文件没有详细说明

**复现步骤**
1、使用 vue-cli 创建项目
2、运行 npm run build:app-plus 命令
3、生成的 dist 文件夹里面内容不知道怎么办

**预期结果**
官网文档中对于打包生成安卓 ios App 更加详细说明

**实际结果**
目前文档中对于该部分说明较少

**Comment by zhetengbiji** [comment]
uni-app 支持离线打包，详细参考相关文档：
https://ask.dcloud.net.cn/article/103
https://ask.dcloud.net.cn/article/35139
https://ask.dcloud.net.cn/article/35379
