### ISSUE TITLE
缺少 wx.reportPerformance 接口

### ISSUE THREAD

**Issue by loveonelong** [dcloudio/uni-app#1575]
**新功能描述**
小程序测速上报的api
https://developers.weixin.qq.com/miniprogram/dev/framework/performanceReport/

**Comment by hbcui1984** [comment]
[条件编译](https://uniapp.dcloud.net.cn/platform?id=%e6%9d%a1%e4%bb%b6%e7%bc%96%e8%af%91)中可调用微信原生代码，该API暂时不会纳入uni-app跨端规范中。
