### ISSUE TITLE
文档代码可能过时了

### ISSUE THREAD

**Issue by 2234839** [dcloudio/uni-app#1576]
**问题描述**
[web-view](https://github.com/dcloudio/uni-app/blob/master/docs/component/web-view.md) 此处使用的代码 

```javascript
    document.write('<script type="text/javascript" src="https://qqq.gtimg.cn/miniprogram/webview_jssdk/qqjssdk-1.0.0.js"><\/script>');
  } else if (/miniProgram/i.test(userAgent)) {
    // 微信小程序 JS-SDK 如果不需要兼容微信小程序，则无需引用此 JS 文件。
    document.write('<script type="text/javascript" src="https://res.wx.qq.com/open/js/jweixin-1.4.0.js"><\/script>');
  } 
```
这里的条件无法正确检测到是使用了 ios 微信小程序，从而导致无法正确加载 微信的 sdk

**复现步骤**

使用文档中的代码，发现 ios 无法调用 uni.postMessag

**预期结果**

可以正确检测和生效

**实际结果**

wx 对象不存在

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 iOS
 - uni-app版本 uni-app v2.6.14
uni-app cli v2.0.0-alpha-26920200417001
 - 设备信息 iPhone7 Plus

**补充信息**

ios 的 userAgent 提供的信息和正则检测的不符
实际为
> Mozilla/5.0 (iPhone; CPU iPhone OS 13_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 wxwork/3.0.16 MicroMessenger/7.0.1 Language/zh

**Comment by dcloudhdx** [comment]
感谢反馈，已更新文档
