### ISSUE TITLE
保存图片到系统相册saveimagetophotosalbum问题

### ISSUE THREAD

**Issue by xiaomaiyun** [dcloudio/uni-app#1579]
**问题描述**
保存图片到系统相册saveimagetophotosalbum如果后台返回的路径没有文件个数后缀怎么设置文件格式？

**复现步骤**
[复现问题的步骤]
1.运行uniapp看图模板项目
2.后台返回的图片路径没有文件格式，如：https://images.unsplash.com/photo-1562887245-138c2f45013e?ixlib=rb-1.2.1&q=85&fm=jpg&crop=entropy&cs=srgb
2. 点击图片详情页面左下角下载图片到相册
3. 图片下载到手机相册，但是文件格式不正确（没有文件后缀），手机无法通过手机相册查看

[或者可以直接贴源代码]

**预期结果**
进入手机相册即可查看保持的图片

**实际结果**
图片下载到手机相册，但是文件格式不正确（没有文件后缀），手机无法通过手机相册查看

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by dcloudhdx** [comment]
saveImageToPhotosAlbum 不支持网络路径
文档 `https://uniapp.dcloud.io/api/media/image?id=saveimagetophotosalbum`

**Comment by zhetengbiji** [comment]
App端在HBuilderX 2.7.1+已支持
稳妥起见，请参考文档使用：下载文件后再调用uni.saveImageToPhotosAlbum
