### ISSUE TITLE
编译小程序 点击事件有时候无效

### ISSUE THREAD

**Issue by airzhanglin** [dcloudio/uni-app#158]
编译小程序 点击事件有时候无效，需要重新再编辑器执行重新编译才可以

**Comment by xiaoyucoding** [comment]
请使用最新版的 cli 或者下载 QQ 群的体验版 HBuilderX，本周会正式更新 HBuilderX。

**Comment by airzhanglin** [comment]
新问题，把text标签设置为display:block 还有一个行高，view标签包裹text标签也有问题。

**Comment by xiaoyucoding** [comment]
> 新问题，把text标签设置为display:block 还有一个行高，view标签包裹text标签也有问题。

请详细描述问题以及重现问题的环境信息，另外附上一个可以重现问题的 demo。

**Comment by airzhanglin** [comment]
只需要把<text>标签设置为 display：block  存在行高问题，然后view标签包裹一个text标签也存在行高问题；
HBbuilder版本：1.5.1；
微信小程序模拟器版本： 1.02.1901170
![image](https://user-images.githubusercontent.com/16433124/51463715-e5dcc580-1d9e-11e9-94c8-d91243e11dc2.png)

![image](https://user-images.githubusercontent.com/16433124/51463903-63a0d100-1d9f-11e9-8993-c6f322c2b651.png)

**Comment by xiaoyucoding** [comment]
> 只需要把标签设置为 display：block 存在行高问题，然后view标签包裹一个text标签也存在行高问题；
> HBbuilder版本：1.5.1；
> 微信小程序模拟器版本： 1.02.1901170
> ![image](https://user-images.githubusercontent.com/16433124/51463715-e5dcc580-1d9e-11e9-94c8-d91243e11dc2.png)
> 
> ![image](https://user-images.githubusercontent.com/16433124/51463903-63a0d100-1d9f-11e9-8993-c6f322c2b651.png)

如果是小程序平台的话，会与普通的 HTML 有差异，建议直接创建一个微信小程序的示例对比下，如果存在同样的现象那就是小程序平台的引擎实现如此，这个底层的引擎我们是改不了的。

**Comment by airzhanglin** [comment]
> > 只需要把标签设置为 display：block 存在行高问题，然后view标签包裹一个text标签也存在行高问题；
> > HBbuilder版本：1.5.1；
> > 微信小程序模拟器版本： 1.02.1901170
> > ![image](https://user-images.githubusercontent.com/16433124/51463715-e5dcc580-1d9e-11e9-94c8-d91243e11dc2.png)
> > ![image](https://user-images.githubusercontent.com/16433124/51463903-63a0d100-1d9f-11e9-8993-c6f322c2b651.png)
> 
> 如果是小程序平台的话，会与普通的 HTML 有差异，建议直接创建一个微信小程序的示例对比下，如果存在同样的现象那就是小程序平台的引擎实现如此，这个底层的引擎我们是改不了的。

你们上个版本没这个问题哦
