### ISSUE TITLE
Cannot read property '$mp' of undefined

### ISSUE THREAD

**Issue by humordancer** [dcloudio/uni-app#1581]
**问题描述**
![image](https://user-images.githubusercontent.com/34059032/79722970-92e21d00-8317-11ea-919a-20f99405d8f1.png)
现在显示还有很多用户都使用的2.0.9的基础库，需要向下兼容一下，有什么办法可以解决么。

![image](https://user-images.githubusercontent.com/34059032/79723082-c329bb80-8317-11ea-9b60-29fe6fa8da90.png)
![image](https://user-images.githubusercontent.com/34059032/79723205-f0766980-8317-11ea-9bae-677825a00706.png)

这里的$vm实例好像没有注册进来

**预期结果**
希望可以在不需要调整基础库版本情况下 小程序可以正常运行

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
IOS 9.3.5
微信版本6.6.6 
基础库2.0.9

**Comment by 563803119** [comment]
也遇到这个问题了，你那边解决了么 @humordancer

**Comment by humordancer** [comment]
@563803119 我这边ios 9.3.5的系统可以升级到 7.0.2的微信版本 升级微信就好了 需要在商店已下载的地方找到 我是先删除 然后再下载的
