### ISSUE TITLE
在微信公众号里面使用uni.chooseImage上传图片, sourceType不是默认二者都有?

### ISSUE THREAD

**Issue by renxiao1218** [dcloudio/uni-app#1582]
**问题描述**
在微信公众号里面使用uni.chooseImage上传图片, 微信公众号里面没拍照功能了,demo里面也没的

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
默认是的，相当于普通html页面写一个file类型的input，你可以直接用个html测试一下，看是不是微信改了。
