### ISSUE TITLE
小程序webview异常

### ISSUE THREAD

**Issue by fish-uncle** [dcloudio/uni-app#1583]
小程序使用webview
```
<webview src="example.com"/>
```
异常
必须使用
```
<web-view src="example.com"/>
```

**Comment by zhetengbiji** [comment]
能否详细说一下？

**Comment by fish-uncle** [comment]
在小程序中编写中，
`<webview src="example.com"/>`无效，
`<web-view src="example.com"/>`可以使用，
在app中
`<webview src="example.com"/>`可以使用
`<web-view src="example.com"/>`可以使用，

这个容错机制是怎么样的

**Comment by zhetengbiji** [comment]
app端是vue页面还是nvue页面？

**Comment by fish-uncle** [comment]
vue页面

**Comment by zhetengbiji** [comment]
是否启用了v3编译模式？

**Comment by fish-uncle** [comment]
未开启
2.6.8.20200330

**Comment by fxy060608** [comment]
所有内置组件，请使用标准用法： web-view，否则无法保证跨平台
