### ISSUE TITLE
WebView input组件弹起软键盘时，状态栏和当前Webview被顶出

### ISSUE THREAD

**Issue by xiaomaokeke** [dcloudio/uni-app#1590]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
  在.nvue 页面中，嵌套了一个WebView组件和自定义状态栏,input组件，当input组件focus事件触发，弹起软键盘时，WebView和状态栏被顶出去了，也尝试了官方文档中`https://uniapp.dcloud.io/component/input` 为当前页面配置"app-plus"节点下，配置 softinputMode": "adjustResize", 也无效(两种模式尝试了),不知道是WebView的设计初衷是是这样的或是一个Bug,已经专研很多天，网上搜索也只有部分案例，重复居多，插件市场也逛了，没有与我相符合的例子，所以才在这里发问，请官方大佬或路过的大佬帮忙解答回复或提供另外一些可行性方案，谢谢
**复现步骤**
[复现问题的步骤]
1.  启动  .nuve 页面，并使用webview组件访问网络资源，
2. 打开当前 与webview 同级的 input 组件，弹起软键盘
3. 软键盘弹出时，webview和自定义状态栏被撑出

**源代码:**
**自定义 WebView 组件**
```
<template>
	<view class="body">
		<!-- #ifdef APP-PLUS -->
		<div class="statusBar" :style="{height:statusBarHeight+'wx',width:statusBarWidth+'wx',backgroundColor:'#107885'}"></div>
		<!-- #endif -->
		<!-- 空白网页 -->
		<scroll-view scroll-y="true">
			<web-view :webview-styles="webviewStyles" ref="webview" :src="weburl" :style="{height:webViewHeight+'wx',width:webViewWidth+'wx'}"
			 @pagestart="onPageStart" @onPostMessage="handlePostMessage" @onError="onWebViewError" />
		</scroll-view>
		<view class="options">
			<!-- 页面搜索区 搜索框  -->
			<page-search :width="statusBarWidth" @hiddenSearchPanel="hiddenSearchPanel" @calKeyBoardHeight="calKeyBoardHeight" v-if="showSearchPanel"
			 @searchWord="searchWord" />
		</view>
	</view>
</template>

<script>
	import pageSearch from "../../components/other/page-search";
	export default {
		props: {
			weburl: String,
			statusBarHeight: Number,
			statusBarWidth: Number,
			webViewHeight: Number,
			webViewWidth: Number,
		},
		components: {
			pageSearch
		},
		data() {
			return {
				showSearchPanel: true, // 是否显示页内搜索面板
				wv: {},
				pageStart: false, // 页面加载状态
				webviewStyles: {
					progress: {
						color: '#000'
					},
				}
			}
		},
		methods: {
			search() { // 页面搜索
				this.showSearchPanel = true // 显示
			},

			// 监听WebView页面的加载状态,必须执行此步骤
			onPageStart() {
				this.pageStart = true;
			},
			reloadWebviewUrl() { // 刷新网页
				let webview = weex.requireModule('webview');
				webview.reload(this.$refs.webview);
			},
		},
	}
</script>

<style scoped>
	.body {
		position: fixed;
		top: 0;
		right: 0;
		bottom: 0;
		left: 0;
	}

	.options {
		position: fixed;
		bottom: 20px;
		left: 15px;
		z-index: 100;
	}
</style>
```
**自定义input 组件**
```
<template>
	<view class="search-panel" :style="{width:width+'wx'}">
		<view class="search-panel-cancel" @tap="hidden">
			<text class="search-panel-cancel-btn">&#xe605;</text>
		</view>
		<view class="search-panel-input">
			<input type="text" class="input-word" v-model="keyword" @focus="focus" />
		</view>
		<view class="search-panel-btn">
			<button class="btn" type="default" @tap="searchWord">页内搜索</button>
			<button class="btn" type="default" @tap="preWord">上一个</button>
		</view>
	</view>
</template>

<script>
	export default {
		props: {
			width: Number
		},
		data() {
			return {
				keyword: ""
			}
		},
		created() {
			// 引用字体图标
			// #ifdef APP-PLUS
			const domModule = weex.requireModule("dom");
			domModule.addRule('fontFace', {
				'fontFamily': 'iconfont', //注意这里必须是驼峰命名，跟上面的css样式对照
				'src': "url(\'http://at.alicdn.com/t/font_1737303_py03pgxggj.ttf\')"
			})
			// #endif
		},
		methods: {
			hidden() { // 隐藏搜索面板
				this.$emit('hiddenSearchPanel')
			},
			searchWord() { // 搜索关键词
				this.$emit('searchWord', this.keyword)
			},
			preWord() { // 上一个关键词
				this.$emit('preWord', this.keyword)
			},
			focus(e) {
				let height = e.detail.height
				if (height) {
					this.$emit('calKeyBoardHeight',height)
				}

			}
		}
	}
</script>

<style>
	.search-panel {
		position: fixed;
		bottom: -1px;
		background-color: #107885;
		height: 120upx;
		flex-direction: row;
		padding: 2px 0;
		justify-content: center;
		align-items: center;
	}

	.search-panel-cancel {
		flex: 2;
		align-items: center;
		justify-content: center;
	}

	.search-panel-cancel-btn {
		text-align: center;
		color: #FFFFFF;
		font-size: 25px;
	}

	.search-panel-input {
		flex: 5;
		/* #ifndef APP-PLUS-NVUE*/
		border-bottom: 1upx solid #089186;
		/* #endif */
	}

	.input-word {
		color: #FFFFFF;
	}

	.search-panel-btn {
		flex: 5;
		flex-direction: row;
		justify-content: space-around;
	}

	.btn {
		flex: 1;
		width: 80px;
		height: 42px;
		margin-right: 5px;
	}
</style>
```

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
当用户聚焦到input 组件时，软键盘弹起，Webview 和 状态栏不被撑出且页面内容不被挤压，用户输入完毕(input组件不被聚焦)，软键盘收回，inpu组件悬停(定位)到底部
![image](https://user-images.githubusercontent.com/64067386/79871818-87761b00-8417-11ea-87c5-81a896e5ad53.png)

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/64067386/79870092-028a0200-8415-11ea-8a41-5050a71ef91d.png)

**系统信息:**
 - 测试平台: 小米 MAX 2
 - 开发目标: App
 - 操作系统  windows 10
 - HBuilderX版本 [2.6.11.20200409]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]
     小米 MAX 2      Android 7.1.1 MIUI：11.0.2 稳定版

**补充信息**
     另外我为了解决这个问题还想出另外一个方案，在H5页面里使用htlm的input监听键盘弹起，但是键盘弹起时，本想着可以通过监听窗口变化时时计算，使用的jquery的resize方法监听得到window变化，动态设置input 框悬停(position)到软键盘 ，因为在测试时发现软键盘弹出并不会影响Web的窗口变化(宽高度)，望官方大佬和各位路过的大佬解答一下谢谢,如各位大佬需要确切的代码，可以与我发送邮件联系(xiaomaokeke@outlook.com),再次感谢

**Comment by dcloudhdx** [comment]
是否配置了 `"type":"transparent"`，配置后会充满屏幕
```
"app-plus": {
  "softinputMode":"adjustResize",
  "titleNView": {
    "type":"transparent"
  }
}
```

**Comment by xiaomaokeke** [comment]
> 是否配置了 `"type":"transparent"`，配置后会充满屏幕
> 
> ```
> "app-plus": {
>   "softinputMode":"adjustResize",
>   "titleNView": {
>     "type":"transparent"
>   }
> }
> ```
您好，我什么没有配置呢，只是在.nvue中配置了WebView是全屏模式

**Comment by dcloudhdx** [comment]
请提供一个完整的简单工程

**Comment by xiaomaokeke** [comment]
> 请提供一个完整的简单工程

好的，谢谢，这是我的测试工程文件，这里面又两个文件，myWebView 是uniapp， H5文件夹是 webview 访问的 移动Web页面 
链接：https://pan.baidu.com/s/1F4DgDPx5YKK_6t3yaOAKeg 
提取码：0nxh

**Comment by dcloudhdx** [comment]
1. 配置 `"navigationStyle": "custom"` 后会充满整个屏幕，需要自己控制webview据顶部状态的距离
2. 输入框显示不全是你的 input 框的高度没有充满状态栏，上推位置是根据input来计算的

**Comment by xiaomaokeke** [comment]
您好，感谢您耐心的回复和解答我的疑惑，可能您还未明白我的示例意思，这个示例是想通过 inpu聚焦，弹出软键盘并且不影响WebView和自定义的状态栏高度，但是当input 聚焦后，软键盘弹出会将 自定义状态栏和 WebView 全部溢出，经我测试溢出的高度恰恰是软键盘的高度，我也尝试了手动计算(当前WebView高度-软键盘的高度)来显示，不仅没有效果且webview下方还会留出与软键盘相同高度的空白区域
**源代码:**
`
calKeyBoardHeight(height) {// 键盘获取焦点后
				// height 292
				let webviewHeight = this.webViewHeight - height
				this.webViewHeight=webviewHeight
},`
**效果:**
![image](https://user-images.githubusercontent.com/64067386/80594198-2a044e80-8a55-11ea-9846-e6a7af080bff.png)

**Comment by dcloudhdx** [comment]
目前的解决方案是使用 subnvue 盖住顶部，占用状态栏的高度

**Comment by xiaomaokeke** [comment]
> 目前的解决方案是使用 subnvue 盖住顶部，占用状态栏的高度

感谢您的耐心回复，我跟主管商量了，已经放弃这块功能了，谢谢您的帮助
