### ISSUE TITLE
ios uni-app打开的webview里面getEnv plus不为true

### ISSUE THREAD

**Issue by lmf** [dcloudio/uni-app#1591]
**问题描述**
打印userAgent里面不包含uni-app，导致getEnv判断有问题

**系统信息:**
 - 发行平台:APP
 - HBuilderX版本：2.6.11

**Comment by dcloudhdx** [comment]
验证没有问题

1.检查 html 引用的 uni.webview 版本是否为1.5.2，
`<script type="text/javascript" src="https://js.cdn.aliyun.dcloud.net.cn/dev/uni-app/uni.webview.1.5.2.js"></script>`

2.测试代码
```
document.addEventListener('UniAppJSBridgeReady', function() {
  uni.getEnv(function(res) {
    console.log('当前环境：' + JSON.stringify(res)); // 当前环境：{"plus":true}
  });
}
```

**Comment by lmf** [comment]
@dcloudhdx 这是我在ios下打印出来的userAgent：Mozilla/5.0 (iPhone; CPU iPhone OS 13_4_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 Html5Plus/1.0，不包含uniapp

**Comment by dcloudhdx** [comment]
getEnv 和 UA 中是否含 uniapp 没有关系
参考文档 https://uniapp.dcloud.net.cn/component/web-view?id=getenv

**Comment by dcloudhdx** [comment]
已更新 `uni.webview.1.5.2.js`  https://js.cdn.aliyun.dcloud.net.cn/dev/uni-app/uni.webview.1.5.2.js
