### ISSUE TITLE
使用@vue/cli-plugin-unit-mocha进行单元测试时候报错

### ISSUE THREAD

**Issue by lmf** [dcloudio/uni-app#1592]
**问题描述**
在测试.vue文件时候，处理style时候会报Cannot set property 'style' of undefined，定位到报错位置是在@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/codegen/styleInjection.js 102行：
```javascript
    if(!this.options.style){
          this.options.style = {}
    }
```
手动修改这块后，下面的Vue也是会报ReferenceError: Vue is not defined的错

**Comment by lmf** [comment]
@zhetengbiji @fxy060608 uni-app现在应该对单元测试的支持不太好是吧？

**Comment by fxy060608** [comment]
> @zhetengbiji @fxy060608 uni-app现在应该对单元测试的支持不太好是吧？

稍后提供jest的自动化测试
