### ISSUE TITLE
HX2.6.9 之后, 页面过多, 导致编译失败

### ISSUE THREAD

**Issue by namo10234** [dcloudio/uni-app#1596]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
我们的项目页面较多,  有90个左右. HX升级到2.6.9之后, 遇到如下问题:
1. 本地IDE2.6.5, 云打包服务2.6.9 此时可以编译成功, 但是打包APK有问题, 下拉刷新无法触发
2. 将本地IDE升级到2.6.9之后的版本, 本地编译失败, 提示内存溢出,.
3. 将设置->运行配置->node运行内存跳转到8000, 也不行.  
4. 如果将pages.json中的pages中配置的页面删减一部分 ,则可以编译成功(可以排除是某个页面的原因), 

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by dcloudhdx** [comment]
在 HBuilderX 2.7.13 测试正常，更新试试，刷新问题请提供apk
