### ISSUE TITLE
报告在nvue中view嵌套问题

### ISSUE THREAD

**Issue by lztbwlkj** [dcloudio/uni-app#1597]
**预期结果**
     APP端去掉页面内容超出屏幕的自带滚动效果
**实际结果**
项目配置:
 "app-plus" : {
          "renderer": "native", //App端纯原生渲染模式设置
   }
"path": "pages/index/index",
"style": {
	"navigationBarTitleText": "Index",
	"disableScroll": true
}	
		
index.nvue中使用div嵌套view,页面依旧可以滚动 设置无效果，代码如下：
```
<div>
	<view class="" @click="loadData" style="height: 120rpx;background-color: #007AFF;" v-for="i in 20" :key="i">
		{{text}}
	</view>
</div>
```
index.nvue中使用view嵌套view, 页面内容超出屏幕就不会滚动，代码如下：
```
<view>
	<view class="" @click="loadData" style="height: 120rpx;background-color: #007AFF;" v-for="i in 20" :key="i">
	      {{text}}
	</view>
</view>
```

**Comment by dcloudhdx** [comment]
`"disableScroll": true` 应配置在 "app-plus" 节点下
重新编译试试，和div没有关系
