### ISSUE TITLE
uniapp vue3 版本兼容计划? 以及和其他vue3组件库的兼容方案交流

### ISSUE THREAD

**Issue by msdlisper** [dcloudio/uni-app#1598]
**新功能描述**
你好, 我们这边是[mand-mobile](https://github.com/didi/mand-mobile)组件库的开发者, 随着vue3发布, 我们在做3.0版本, 并且准备兼容uniapp. 想和这边交流下uniapp是否后续有vue3的支持.  

**现状及问题**
- 现在vue3基本可以用了,我们准备用vue3来重构mand-mobile组件库, 同时想兼容uniapp, 但不清楚uniapp是否有vue3版本
- 想讨论下我们组件库的开发者如何比较优雅的兼容uniapp

**尝试方案**
在mand-mobile3我们可能会尝试在源码使用条件编译, 输出h5包和兼容uniapp包, 但前提是uniapp能识别composition api, 或者提供实现的方式

**Comment by 2788** [comment]
希望能够有mand-mobile组件库可以使用

**Comment by msdlisper** [comment]
> 希望能够有mand-mobile组件库可以使用

快了, 7月底就可以用, 不过只支持vue2

**Comment by 2788** [comment]
> > 希望能够有mand-mobile组件库可以使用
> 
> 快了, 7月底就可以用, 不过只支持vue2

现在是6月底了, 进度上赶得上吗?  期待mand-mobile

**Comment by msdlisper** [comment]
> 现在是6月底了, 进度上赶得上吗? 期待mand-mobile
现在的进度看7月底可能只有我们内部用..

**Comment by BarryZhan** [comment]
现在8月底了，进度怎么样

**Comment by gbckt** [comment]
> > > > 现在是6月底了，进度上赶得上吗？期待手机
> > >
> > >
> > >现在的进度看7月底可能只有我们内部用..
> >
> >现在8月底了，进度怎么样
>
>现在11月底了，进度怎么样

**Comment by hbcui1984** [comment]
uni-app 在小程序端已支持vue 3.0，详见： https://ask.dcloud.net.cn/article/37834

**Comment by Ljw127** [comment]
> > > > > 现在是6月底了，进度上赶得上吗？期待手机
> > > > 
> > > > 
> > > > 现在的进度看7月底可能只有我们内部用..
> > > 
> > > 
> > > 现在8月底了，进度怎么样
> > 
> > 
> > 现在11月底了，进度怎么样

现在12月份了，进度怎么样

**Comment by lililixiaofei** [comment]
> > > > > > 现在是6月底了，进度上赶得上吗？期待手机
> > > > > 
> > > > > 
> > > > > 现在的进度看7月底可能只有我们内部用..
> > > > 
> > > > 
> > > > 现在8月底了，进度怎么样
> > > 
> > > 
> > > 现在11月底了，进度怎么样
> 
> 现在12月份了，进度怎么样

现在12月中了，进度怎么样

**Comment by allowing** [comment]
> > > > > > > 现在是6月底了，进度上赶得上吗？期待手机
> > > > > > 
> > > > > > 
> > > > > > 现在的进度看7月底可能只有我们内部用..
> > > > > 
> > > > > 
> > > > > 现在8月底了，进度怎么样
> > > > 
> > > > 
> > > > 现在11月底了，进度怎么样
> > 
> > 
> > 现在12月份了，进度怎么样
> 
> 现在12月中了，进度怎么样

现在2021年2月了，进度怎么样

**Comment by 1622583480** [comment]
> > > > > > > > 现在是6月底了，进度上赶得上吗？期待手机
> > > > > > > >
> > > > > > > >
> > > > > > > > 现在的进度看7月底可能只有我们内部用..
> > > > > > >
> > > > > > >
> > > > > > > 现在8月底了，进度怎么样
> > > > > >
> > > > > >
> > > > > >现在11月底了，进度怎么样
> > > >
> > > >
> > > >现在12月份了，进度怎么样
> > >
> > >
> > >现在12月中了，进度怎么样
> >
> >现在2021年2月了，进度怎么样
> 现在2021年6月初了，进度怎么样

**Comment by JsonLocker** [comment]
> > > > > > > > > 现在是6月底了，进度上赶得上吗？期待手机
> > > > > > > > > 现在的进度看7月底可能只有我们内部用..
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 现在8月底了，进度怎么样
> > > > > > > 
> > > > > > > 
> > > > > > > 现在11月底了，进度怎么样
> > > > > 
> > > > > 
> > > > > 现在12月份了，进度怎么样
> > > > 
> > > > 
> > > > 现在12月中了，进度怎么样
> > > 
> > > 
> > > 现在2021年2月了，进度怎么样
> > > 现在2021年6月初了，进度怎么样

现在2021年6月末了，进度怎么样

**Comment by ljw-codeking** [comment]
> > > > > > > > > > 现在是6月底了，进度上赶得上吗？期待手机
> > > > > > > > > > 现在的进度看7月底可能只有我们内部用..
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 现在8月底了，进度怎么样
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 现在11月底了，进度怎么样
> > > > > > 
> > > > > > 
> > > > > > 现在12月份了，进度怎么样
> > > > > 
> > > > > 
> > > > > 现在12月中了，进度怎么样
> > > > 
> > > > 
> > > > 现在2021年2月了，进度怎么样
> > > > 现在2021年6月初了，进度怎么样
> 
> 现在2021年6月末了，进度怎么样



> > > > > > > > > > 现在是6月底了，进度上赶得上吗？期待手机
> > > > > > > > > > 现在的进度看7月底可能只有我们内部用..
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 现在8月底了，进度怎么样
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 现在11月底了，进度怎么样
> > > > > > 
> > > > > > 
> > > > > > 现在12月份了，进度怎么样
> > > > > 
> > > > > 
> > > > > 现在12月中了，进度怎么样
> > > > 
> > > > 
> > > > 现在2021年2月了，进度怎么样
> > > > 现在2021年6月初了，进度怎么样
> 
> 现在2021年6月末了，进度怎么样

现在2021年8月了，进度怎么样

**Comment by ljw-codeking** [comment]
> > > > > > > > > > 现在是6月底了，进度上赶得上吗？期待手机
> > > > > > > > > > 现在的进度看7月底可能只有我们内部用..
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 现在8月底了，进度怎么样
> > > > > > > > 
> > > > > > > > 
> > > > > > > > 现在11月底了，进度怎么样
> > > > > > 
> > > > > > 
> > > > > > 现在12月份了，进度怎么样
> > > > > 
> > > > > 
> > > > > 现在12月中了，进度怎么样
> > > > 
> > > > 
> > > > 现在2021年2月了，进度怎么样
> > > > 现在2021年6月初了，进度怎么样
> 
> 现在2021年6月末了，进度怎么样

现在2021年8月了，进度怎么样

**Comment by 1622583480** [comment]
> > > > > > > > > > > 现在是6月底了，进度上赶得上吗？期待手机
> > > > > > > > > > > 现在的进度看7月底可能只有我们内部用..
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 现在8月底了，进度怎么样
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 现在11月底了，进度怎么样
> > > > > > > 
> > > > > > > 
> > > > > > > 现在12月份了，进度怎么样
> > > > > > 
> > > > > > 
> > > > > > 现在12月中了，进度怎么样
> > > > > 
> > > > > 
> > > > > 现在2021年2月了，进度怎么样
> > > > > 现在2021年6月初了，进度怎么样
> > 
> > 
> > 现在2021年6月末了，进度怎么样
> 
> 现在2021年8月了，进度怎么样
> 现在2021年9月了，vue3支持了进度怎么样了

**Comment by N0ts123** [comment]
> > > > > > > > >>> > > > 现在是6月底了，进度上赶得上吗？期待手机
> > > > > > > > >>> > > > 现在的进度看7月底可能只有我们内部用..
> > > > > > > > >>> > > 
> > > > > > > > >>> > > 
> > > > > > > > >>> > > 现在8月底了，进度怎么样
> > > > > > > > >>> > 
> > > > > > > >>> > > 
> > > > > > > >>> > > 现在11月底了，进度怎么样
> > > > > > >>> > 
> > > > >>> > > > 
> > > > >>> > > > 现在12月份了，进度怎么样
> > > > >>> > > 
> > > >>> > > > 
> > >>> > > > > 现在12月中了，进度怎么样
> > > >>> > > 
> > >>> > > > 
> > >>> > > > 现在2021年2月了，进度怎么样
> > >>> > > > 现在2021年6月初了，进度怎么样
> > >>> 
> > > >>
> > >>> 现在2021年6月末了，进度怎么样
> > >>
> > >>
> > >>现在2021年8月了，进度怎么样
> >>> 现在2021年9月了，vue3支持了进度怎么样了

>> 现在2021年9月下旬了，进度怎么样了

**Comment by PentaTea** [comment]
> > > > > > > > > > > > > > > 现在是6月底了，进度上赶得上吗？期待手机
> > > > > > > > > > > > > > > 现在的进度看7月底可能只有我们内部用..
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 
> > > > > > > > > > > > > > 现在8月底了，进度怎么样
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 
> > > > > > > > > > > > > 现在11月底了，进度怎么样
> > > > > > > > > > > 
> > > > > > > > > > > 
> > > > > > > > > > > 现在12月份了，进度怎么样
> > > > > > > > > > 
> > > > > > > > > > 
> > > > > > > > > > 现在12月中了，进度怎么样
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 现在2021年2月了，进度怎么样
> > > > > > > > > 现在2021年6月初了，进度怎么样
> > > > > > 
> > > > > > 
> > > > > > 现在2021年6月末了，进度怎么样
> > > > > 
> > > > > 
> > > > > 现在2021年8月了，进度怎么样
> > > > > 现在2021年9月了，vue3支持了进度怎么样了
> 
> > > 现在2021年9月下旬了，进度怎么样了

现在2022年2月了, 进度怎么样
