### ISSUE TITLE
BUG: 在微信小程序中js的Object.entries并没有进行兼容处理

### ISSUE THREAD

**Issue by 2460392754** [dcloudio/uni-app#1601]
**问题描述**
在ios9.2版本中js的Object.entries并没有进行兼容处理

**实际结果**
Object.entries is not a function

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 ios9.2版本

**Comment by fxy060608** [comment]
发行至小程序平台时，API的兼容由目标平台处理，可以测试下原始的小程序是否也有问题，如果有问题，可以向小程序平台提一下Bug，参考：https://developers.weixin.qq.com/miniprogram/dev/framework/runtime/js-support.html#%E5%AE%A2%E6%88%B7%E7%AB%AF%20ES6%20API%20%E6%94%AF%E6%8C%81%E6%83%85%E5%86%B5
