### ISSUE TITLE
运行微信小程序失败Callback was already called

### ISSUE THREAD

**Issue by 297242448** [dcloudio/uni-app#1602]
**问题描述**
Hbuilder X 版本：2.6.15
node版本：12.16.2
npm版本：6.14.4

10:58:01.508 正在编译中...
10:58:17.872 d:\Users\Desktop\HBuilderX\plugins\uniapp-cli\node_modules\neo-async\async.js:14
10:58:17.872     throw new Error('Callback was already called.');
10:58:17.881     ^
10:58:17.887 Error: Callback was already called.
10:58:17.894     at throwError (d:\Users\Desktop\HBuilderX\plugins\uniapp-cli\node_modules\neo-async\async.js:14:11)
10:58:17.895     at d:\Users\Desktop\HBuilderX\plugins\uniapp-cli\node_modules\neo-async\async.js:2813:7
10:58:17.903     at _combinedTickCallback (internal/process/next_tick.js:131:7)
10:58:17.903     at process._tickCallback (internal/process/next_tick.js:180:9)
11:01:59.530 已停止运行...

**复现步骤**
[复现问题的步骤]
安装IDE环境，工具-》设置-》运行配置-》微信开发者工具路径
构建项目：新建-》项目-》选择uni-app项目-》uCharts(v1.9.3) 高性能跨全端图标-》创建
编译运行：运行-》运行到小程序模拟器-》微信开发者工具

**Comment by Mamba0000** [comment]
一个垃圾 天天说自己多牛逼 害死人

**Comment by 297242448** [comment]
怎么请教个问题，这个项目还会骂人。求指导

> 一个垃圾 天天说自己多牛逼 害死人

**Comment by SiiZhao** [comment]
> 怎么请教个问题，这个项目还会骂人。求指导
> 
> > 一个垃圾 天天说自己多牛逼 害死人

可以选择举报，哪都有这种低素质的人。
