### ISSUE TITLE
期望App.vue里新增onPageNotFound的监听

### ISSUE THREAD

**Issue by shangjingfei** [dcloudio/uni-app#1604]
**新功能描述**
期望增加onPageNotFound

**现状及问题**
已经生成二维码的页面需要重构，而重构后路径发生改变，这个时候扫描二维码希望做onPageNotFound的监听重定向到新路径

**尝试方案**
在onShow或者onLaunch里映射至新路径，但是这样一来，用户首先看到的是not found的页面，希望可以做到onPageNotFound的监听直接转至新页面

**补充信息**
无

**Comment by fxy060608** [comment]
小程序？

**Comment by andyWHJ** [comment]
> 小程序？
是的 微信小程序 新增了几个app生命周期方法

**Comment by zhetengbiji** [comment]
已支持
