### ISSUE TITLE
在组件中使用相对路径跳转报错

### ISSUE THREAD

**Issue by ym0922** [dcloudio/uni-app#1605]
**问题描述**
我在一个自定义组件在微信小程序（其他端没测试）中跳转页面，跳转失败，日志提示找不到页面

![图片](https://user-images.githubusercontent.com/16172921/80264559-283e3200-86c7-11ea-8f0f-86bf39f82bea.png)
![图片](https://user-images.githubusercontent.com/16172921/80264576-2e341300-86c7-11ea-92ec-e9706a65d2bf.png)

**Comment by fxy060608** [comment]
相对路径解析时，是以当前显示的页面为基准解析的，
组件中不要使用相对路径跳转，最好使用绝对路径
