### ISSUE TITLE
ios微信小程序borderStyle属性无效. 条件: ios系统选择深色模式

### ISSUE THREAD

**Issue by LBC100** [dcloudio/uni-app#1609]
**问题描述**
ios微信小程序borderStyle属性无效. 条件: ios系统选择深色模式

**复现步骤**
[复现问题的步骤]
1.系统: ios. 微信小程序.
2.把ios设置为暗黑模式. 设置->显示与亮度->深色
3.打开微信开发者工具. 点击预览或者真机调试.

**预期结果**
borderStyle生效. 导航栏出现黑色线.

**实际结果**
![image](https://user-images.githubusercontent.com/38514123/80311004-f71d4900-880f-11ea-9df1-040e6f096cb6.png)

**系统信息:**
 - 发行平台: [微信小程序]
 - 操作系统 [如 iOS 13.4.1]
 - HBuilderX版本 [2.6.16.20200424]
 - 设备信息 [如 iPhone6s]

**补充信息**

**Comment by zhetengbiji** [comment]
需反馈到微信社区
