### ISSUE TITLE
昨天更新后，H5端onUnload生命周期失效

### ISSUE THREAD

**Issue by zhangyanzt** [dcloudio/uni-app#161]
`onUnload() {
        console.log('onUnload');
}`
直接这样写都不打印的，其他端正常。

**Comment by zhangyanzt** [comment]
目前已影响到线上项目，求尽快修复

**Comment by fxy060608** [comment]
你的 HBuilderX 版本是多少？可以使用 QQ 群中的群测版本测试下。

**Comment by zhangyanzt** [comment]
之前是1228版本，更新群里的版本之后可以了，谢谢。

**Comment by einsqing** [comment]
h5 onUnload不触发，是什么问题？@fxy060608
