### ISSUE TITLE
使用nvue开发地图时如何获取map对象

### ISSUE THREAD

**Issue by liuqisakuya** [dcloudio/uni-app#1616]
> uni-app的原则是vue语法+小程序api。但小程序的api不如plus.map丰富，地图的重度开发者仍然需要plus的map。
uni-app中单独优化了这个地图的获取，通过$getAppMap可直接得到map对象。
然后参考plus.map的api实现更多地图功能。

自定义地图中，$getAppMap这个方法nvue是不支持的;

而官方又不建议使用app-vue,推荐使用nvue, 但plus.maps.getMapById也无法获取原生map组件；  
  
plus的api很多都是基于map对象来进行操作，所以想使用plus.maps.Map的功能，是不是只能使用plus的API去创建地图，而无法使用uni提供的原生map组件

这是之前在社区的提问，但是并没有人回复  
https://ask.dcloud.net.cn/question/95027

**Comment by dcloudhdx** [comment]
nvue 没有 $getAppMap，callout 是 sdk 的默认行为，目前没有控制方法
