### ISSUE TITLE
uni.openLocation返回没有回调

### ISSUE THREAD

**Issue by a454196824** [dcloudio/uni-app#1620]
**问题描述**
[问题描述：HBulderX 2.3.16 uni.openLocation返回没有回调]

**复现步骤**
[复现问题的步骤]
1.  调用uni.openLocation
2. 点击 返回
3. 不能获取到fail里的回调 IOS和安卓都试过

**Comment by dcloudhdx** [comment]
运行到哪个平台?

**Comment by dcloudhdx** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
