### ISSUE TITLE
页面传参，参数部分丢失

### ISSUE THREAD

**Issue by xiaomaokeke** [dcloudio/uni-app#1624]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
  A 页面 带参数 跳转 B页面，参数部分丢失

**复现步骤**
[复现问题的步骤]
1.  A 页面 使用  uni.navigateTo 跳转 B 页面 携带参数
      `uni.navigateTo({ // 请为h5文件夹下的内容搭建一个 http 服务，并访问
					url:`../../pages/other/other?weburl=http://192.168.1.208:8081? 
          query=abc&kw=你要搜啥子嘛&age=张三`
				})`
2. B页面接收参数
    `onLoad(options) {
			if(options&&options.weburl){
				let weburl=options.weburl
				console.log("访问的url地址",weburl)
				this.weburl=weburl
				
			}
  },`
3. 结果
![image](https://user-images.githubusercontent.com/64067386/80595189-eb6f9380-8a56-11ea-998a-d2ad393fc690.png)

**预期结果**
  携带的所有参数完整无缺,不丢失参数
  

**实际结果**
![image](https://user-images.githubusercontent.com/64067386/80595353-2bcf1180-8a57-11ea-87d8-88707e30eb82.png)

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统Android 7.1.1  MIUI 11.0.2 稳定版
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
![image](https://user-images.githubusercontent.com/64067386/80595439-54570b80-8a57-11ea-9375-9bc1e7e30eff.png)

 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 小米 MAX2

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
自行encode一下weburl

**Comment by xiaomaokeke** [comment]
> encode

您好，谢谢您的回复，但是这个方法也用过了，一样会丢失呢

**Comment by xiaomaokeke** [comment]
> 自行encode一下weburl
感谢，已经可以了，我用错方法了，之前使用的是 encodeURI() 进行编码，今天换过神来 encodeURIComponent 来编码,就可以了，抱歉给您带来了困扰

**Comment by zql20032008** [comment]
请问下，编码之后，decode在哪里做的？
