### ISSUE TITLE
希望官方能优化一下uni.chooseLocation的搜索，能像小程序那样全国范围搜索就好了

### ISSUE THREAD

**Issue by liuhaofei** [dcloudio/uni-app#1626]
**新功能描述**
希望能够全国范围的搜索地址，返回结果能包含省市区

**现状及问题**
目前uni.chooseLocation app端返回的结果不带省，市，区，只有地址名

**Comment by Otto-J** [comment]
https://uniapp.dcloud.net.cn/api/location/location.html
