### ISSUE TITLE
用waterfall有一个bug就是安卓和ios的排列顺序是相反的，安卓排序是右边开始的？

### ISSUE THREAD

**Issue by csq0668** [dcloudio/uni-app#1627]
问题：用waterfall组件有一个bug，就是安卓和ios的排列顺序是相反的，安卓排序是右边开始的？
当数据只有一条时，只显示右边一条数据，**很丑！**，ios则无问题。
机型：所有安卓

**Comment by dcloudhdx** [comment]
HBuilderX 2.6.6+ 已修复

**Comment by csq0668** [comment]
好的，但是现在是在header组件加上filter还是会出现从右边开始排序这种情况

**Comment by dcloudhdx** [comment]
filter 是什么？请提供代码

**Comment by csq0668** [comment]
是一个筛选组件
`
<template name="filter">
	<view>
		
		<view class="grace-filter" :style="{'position': fixed?'sticky':'relative','top':top}" id="grace-filter-header">
			<view class="filter-items" v-for="(item, index) in filters" :key="index" :data-index="index" @click="changeSort(index, null)">
				<text class="filter-text" :class="[activeIndex==index?'text-zhutise':'']" v-if="item.filterType!=2">{{ item.title }}</text>
				<text class="filter-text" :class="[activeIndex==index?'text-zhutise':'']" v-else>{{ activeOption && activeOption.name || item.title }}</text>
				<text class="cuIcon-unfold" :class="[activeIndex==index?'text-zhutise':'']" v-if="item.filterType==2"></text>
				<text class="grace-iconfont" v-else-if="item.filterType==0"></text>
				<image class="filter-img" src="/static/img/sort0.png" v-else-if="activeIndex!=index"></image>
				<image class="filter-img" src="/static/img/sort2.png" v-else-if="activeIndex==index && activeAscState"></image>
				<image class="filter-img" src="/static/img/sort1.png" v-else-if="activeIndex==index"></image>
			</view>

			<view class="text-xxl padding-lr padding-top-xs" @click="changeShape" v-if="showShape">
				<text :class="['text-red', curShapeValue == 2 ? 'cuIcon-apps' : 'cuIcon-list']"></text>
			</view>
			
			<view class='grace-filter-options' v-if="activeIndex == index && showOption" v-for="(item, index) in filters" :key="index">
				<view :class="[activeOption && (opt.value ===  activeOption.value) ? 'option current' : 'option']" :data-index="index"
				 :data-option="opt" v-for="(opt, optIndex) in item.options||[]" :key="optIndex" @click="changeSort(index,opt)">
					{{opt.name}}<text class="option-text cuIcon-right"></text>
				</view>
			</view>
		</view>
	</view>
</template>

<script>
	export default {
		props: {
			// 是否固定至顶部
			fixed: {
				type: Boolean,
				default: function() {
					return true
				}
			},
			// 固定至顶部时离顶部的距离
			top: {
				type: String,
				default: function() {
					return "0upx"
				}
			},
			filters: {
				type: Array,
				default: function() {
					return []
				}
			},
			initIndex: {
				type: Number,
				default: function() {
					return 0
				}
			},
			// 显示的模板类型值，1：为单列，2：为多列
			shapeValue: {
				type: Number,
				default: function() {
					return 2
				}
			},
			// 是否显示模板类型选择
			showShape: {
				type: Boolean,
				default: function() {
					return true
				}
			}
		},
		data() {
			return {
				// 当前激活索引
				activeIndex: 0,
				// 默认升序
				activeAscState: true,
				//默认两列布局图标
				curShapeValue: 2,
				showOption: false,
				activeOption: null
			}
		},
		created: function(event) {
			this.curShapeValue = this.shapeValue;
			this.activeIndex = this.initIndex;
		},
		methods: {
			//排序更改事件
			changeSort: function(index, option) {
				/* const index = e.currentTarget.dataset.index;
				const option = e.currentTarget.dataset.option; */
				const curActiveItem = this.filters[index]
				const filterType = curActiveItem.filterType || 0
				// 点击索引等于自身
				if (this.activeIndex == index) {
					//禁用升降序，则直接返回无需处理
					if (curActiveItem.filterType == 0) return
				}
				// 升降序
				if (curActiveItem.filterType == 1) {
					if (this.activeIndex == index) {
						//排序顺序颠倒
						this.activeAscState = !this.activeAscState
					} else {
						this.activeAscState = curActiveItem.initAscState || false
					}
				}
				// 下拉选项
				else if (curActiveItem.filterType == 2) {
					console.log('curActiveItem.filterType:', curActiveItem.filterType)
					if (this.activeIndex != index) {
						// 点击的不是本列
						this.showOption = true
						//this.activeOption=null
					} else if (this.activeIndex == index && option == null) {
						// 点击的本列下拉箭头，则切换显示状态并返回
						this.showOption = !this.showOption
						return;
					} else {
						// 点击了选项，则关闭显示以便显示查询结果
						this.showOption = false
						this.activeOption = option
					}
				}
				this.activeIndex = index;
				if (curActiveItem.filterType == 2 && this.showOption) {
					// 下拉显示面板，不进行过滤
					return;
				}
				const sortField = curActiveItem.value !== undefined ? curActiveItem.value : index
				var data = {
					"sort": sortField,
					"order": this.activeAscState ? 1 : -1,
					"option": this.activeOption && this.activeOption.value || null
				}
				this.$emit("sortChanged", data)
			},
			changeShape: function() {
				this.curShapeValue = this.curShapeValue == 1 ? 2 : 1
				this.$emit("shapeChanged", this.curShapeValue)
			}
		}
	};
</script>
<style>
	/* 条件筛选及排序 */
	.grace-filter {
		width: 750upx;
		background-color: #ECECEC;
		position: fixed;
		height: 60upx;
		z-index: 9;
		left: 0;
		top: 0;
		flex-direction: row;
		align-items: center;
		flex-wrap: nowrap;
	}

	.filter-items {
		flex-wrap: nowrap;
		width: 187upx;
		justify-content: center;
		align-items: center;
		height: 70upx;
		line-height: 70upx;
		flex-direction: row;
	}

	.filter-text {
		line-height: 70upx;
		margin-left: 10upx;
		font-size: 26upx
	}

	.grace-filter-options {
		width: 750upx;
		position: absolute;
		overflow: hidden;
		z-index: 10;
		padding: 2upx 0;
		right: 0;
		top: 71upx;
		/* background-color: #FFFFFF; */
	}

	.option {
		justify-content: space-between;
		height: 100upx;
		line-height: 100upx;
	}

	.option-text {
		margin-right: 30upx;
		font-size: 30upx;
		color: #F00;
		font-weight: 700;
	}

	.current {
		color: #0080ff;
		font-weight: 700;
	}

	.filter-img {
		width: 36upx;
		height: 36upx;
	}

	.position-relative {
		position: relative;
	}

	.position-fixed {
		position: fixed;
	}

	.text-zhutise {
		color: #F74232;
	}

	.text-grey {
		color: #8799a3;
	}
</style>

`

**Comment by csq0668** [comment]
是一个筛选组件
[filter-nvue.zip](https://github.com/dcloudio/uni-app/files/4557377/filter-nvue.zip)

**Comment by dcloudhdx** [comment]
HBuilderX 2.7.4 alpha android 6.0 没有复现问题，请提供一个简单完整工程

**Comment by dcloudhdx** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
