### ISSUE TITLE
App 平台使用 v-for 循环整数，item不是从0开始

### ISSUE THREAD

**Issue by Yangson-Hung** [dcloudio/uni-app#1629]
**问题描述**
App 平台使用 v-for 循环整数，item不是从0开始。
下面是官方的描述
![image](https://user-images.githubusercontent.com/32238889/80678093-d34a5380-8aec-11ea-8727-346b883d4b04.png)

**代码**
![image](https://user-images.githubusercontent.com/32238889/80678158-f7a63000-8aec-11ea-9cb3-514421f2da50.png)

**结果**
下图是2.6.16.20200424版本的
![image](https://user-images.githubusercontent.com/32238889/80678204-0db3f080-8aed-11ea-8962-446d9c79512e.png)

下图是较早版本2.4.6.20191210的
![image](https://user-images.githubusercontent.com/32238889/80678353-54094f80-8aed-11ea-9de7-5fa9ad89fddf.png)

**系统信息:**
 - 发行平台: App平台
 - 操作系统 Android 9.0
 - HBuilderX版本 2.6.16.20200424
 - 设备信息 坚果Pro3

**Comment by dcloudhdx** [comment]
2.6.16启动了V3编译，V3 版本为了和别的平台拉齐改了起始值，推荐使用index
