### ISSUE TITLE
uni.navigateTo 路由导航在定时器、uni.getStorage等回调函数 无法跳转

### ISSUE THREAD

**Issue by xiaomaokeke** [dcloudio/uni-app#1632]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
我在 App.vue  的onLaunch 生命周期时，添加开启广告功能并设置定时器倒计时关闭广告，在定时器（或uni.getStorage）的回调函数中，使用 uni.navigateTo 导航到指定页面时，提示 **navigateTo:fail page `/pages/pages/页面名称/页面名称` is not found**,但是去除定时器或 uni.getStorage 后，能够正常访问
**复现步骤**
[复现问题的步骤]
1.  在App.vue 的 onLaunch 声明周期，开启定时器关闭广告
2. 在定时器的回调函数中，设置了 uni.navigateTo 跳转到其他页面时
3. 提示   **navigateTo:fail page `/pages/pages/页面名称/页面名称` is not found**

[或者可以直接贴源代码]
`onLaunch: function() {
			//app启动时打开启动广告页
			// var w = plus.webview.open(
			// 	'hybrid/html/advertise/advertise.html',
			// 	'本地地址', {
			// 		top: 0,
			// 		bottom: 0,
			// 		zindex: 999
			// 	},
			// 	'fade-in',
			// 	500
			// );
			//设置定时器，4s后关闭启动广告页
			// setTimeout(() => {
			//plus.webview.close(w);
			// this.navigateToSoftPwd()
			uni.getStorage({ // 获取设置的缓存密码信息
				key: "helloworld",
				success: (res) => {
					if (res.data) {
						uni.navigateTo({
							url: "../pages/laotiesixsixsix/laotiesixsixsix"
						})
					}
				}
			})

			//}, 4000);
			// 
			console.log('App Launch')
		}`
**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
 能够正常跳转到其他页面
**实际结果**
[这里请贴上你的报错截图或文字]
navigateTo:fail page `/pages/pages/laotiesixsixsix/laotiesixsixsix` is not found

**系统信息:**
 - 发行平台: 
           App
 - 操作系统 
           Android 7.1.1 
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号] 
           2.6.16.20200424
 - uni-app版本  
           无
 - 设备信息 [如 iPhone8 Plus] 
          小米 Max 2 MIUI 11.0.2 稳定版

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
不要使用相对路径，使用绝对路径跳转。

**Comment by reverse8341** [comment]
我也无法跳转 ， 求解

**Comment by hbcui1984** [comment]
`/pages/pages/laotiesixsixsix/laotiesixsixsix` 看起来是路径错了。
