### ISSUE TITLE
chooseLocation中的大头针可以不随地图移动而移动吗

### ISSUE THREAD

**Issue by ZzzLazy** [dcloudio/uni-app#1639]
**新功能描述**
chooseLocation实现大头针不随地图移动，始终保持在地图中心位置。

**现状及问题**
chooseLocation跟随地图移动而移动，哪里是中心全凭感觉。

**尝试方案**

**补充信息**

**Comment by dcloudhdx** [comment]
后期会优化

**Comment by zhetengbiji** [comment]
新版已优化过
