### ISSUE TITLE
scroll-view 在 firefox 59.0.1 下监听scorll事件报错，event is not defined

### ISSUE THREAD

**Issue by chong-yu** [dcloudio/uni-app#1640]
**问题描述**
scroll-view 在 firefox 59.0.1 下监听scorll事件报错，event is not defined

**复现步骤**
```
<template>
	<view>
		<scroll-view scroll-y="true" style="height: 50vh;" @scroll="onScroll">
			<view style="height: 400vh;"></view>
		</scroll-view>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				
			}
		},
		methods: {
			onScroll(e) {
				console.log(e)
			}
		}
	}
</script>
```

**预期结果**
正常打印事件信息

**实际结果**
![image](https://user-images.githubusercontent.com/64882735/81137811-8bb34400-8f92-11ea-9a76-4356a5799be9.png)

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 windows 10
 - HBuilderX版本 2.6.16.20200424

**Comment by mehaotian** [comment]
没有复现问题，您可以尝试升级浏览器版本看看是否还有此类问题
