### ISSUE TITLE
关于 scoped 的配置

### ISSUE THREAD

**Issue by hezulong1** [dcloudio/uni-app#1642]
**新功能描述**
在 pages 文件下页面未书写 scoped 属性，但是编译后依然存在，这个可以做成可配置的吗，或者在哪里可以配置

**现状及问题**
我的样式比较少，没必要配置 scoped

**尝试方案**

**补充信息**

**Comment by fxy060608** [comment]
h5平台一定会加scoped，目前不支持配置，即使你的样式少，当你的页面多了，不同页面的样式如果没有scoped，就会互相冲突，和其他平台表现不一样。

**Comment by hezulong1** [comment]
> h5平台一定会加scoped，目前不支持配置，即使你的样式少，当你的页面多了，不同页面的样式如果没有scoped，就会互相冲突，和其他平台表现不一样。

哎，不能配置就不能配置吧😔

我也知道是防止别人滥用，页面串样式，就是想可以配置就好了
