### ISSUE TITLE
【vue-cli-plugin-uni】UNI_CLI_CONTEXT 支持配置，不要移除默认的resolve.modules.node_modules，或者可选择

### ISSUE THREAD

**Issue by novrain** [dcloudio/uni-app#1644]
**新功能描述**
UNI_CLI_CONTEXT 能支持通过环境变量设置，webpack配置中resolve.modules.node_modules可以保留，以满足lerna管理工程的场景

**现状及问题**
lerna管理工程的模式下，无法正常通过lerna指令编译

**尝试方案**
UNI_CLI_CONTEXT 支持配置
resolve.modules.node_modules可以保留

**补充信息**
无

**Comment by fxy060608** [comment]
resolve.modules.node_modules的需求，可以通过vue.config.js，configureWebpack 应该可以解决吧

**Comment by novrain** [comment]
> resolve.modules.node_modules的需求，通过vue.config.js，configureWebpack 应该可以解决吧

貌似不行，代码中应该是固定写死的：

`@dcloudio/vue-cli-plugin-uni/lib/configure-webpack.js`

`
// 移除 node_modules 目录，避免受路径上的 node_modules 影响
        webpackConfig.resolve.modules = webpackConfig.resolve.modules.filter(module => module !==
          'node_modules')
`

**Comment by fxy060608** [comment]
> > resolve.modules.node_modules的需求，通过vue.config.js，configureWebpack 应该可以解决吧
> 
> 貌似不行，代码中应该是固定写死的：
> 
> `@dcloudio/vue-cli-plugin-uni/lib/configure-webpack.js`
> 
> `// 移除 node_modules 目录，避免受路径上的 node_modules 影响 webpackConfig.resolve.modules = webpackConfig.resolve.modules.filter(module => module !== 'node_modules')`

vue.config.js中configureWebpack的生效时机比插件里的晚。所以可以定制resolve.modules

**Comment by novrain** [comment]
> > > resolve.modules.node_modules的需求，通过vue.config.js，configureWebpack 应该可以解决吧
> > 
> > 
> > 貌似不行，代码中应该是固定写死的：
> > `@dcloudio/vue-cli-plugin-uni/lib/configure-webpack.js`
> > `// 移除 node_modules 目录，避免受路径上的 node_modules 影响 webpackConfig.resolve.modules = webpackConfig.resolve.modules.filter(module => module !== 'node_modules')`
> 
> vue.config.js中configureWebpack的生效时机比插件里的晚。所以可以定制resolve.modules

好的，多谢，我尝试下

**Comment by bravekingzhang** [comment]
UNI_CLI_CONTEXT 就不可以设置吗？
