### ISSUE TITLE
【报Bug】input的v-model在android环境下 输入过快 数字死循环抖动

### ISSUE THREAD

**Issue by fish-uncle** [dcloudio/uni-app#1645]
[运行端是h5或app或某个小程序？] app

[运行端版本号] 2.6.8

[项目是cli创建的还是HBuilderX创建的？如果是cli创建的，请更新到最新版cli再试]HBuilderX创建

[编译模式说明：自定义组件模式？纯nvue模式？v3模式？]自定义组件模式

[Android版本号]9

[ColorOS版本号]6.0.1

[MIUI版本号]11.0.5

[手机型号]oppo r15 梦境版/MI 6 X MIKU

[可重现代码片段]
```
<input type="text" v-model="phone"/>
```
<video src="https://web-sr-1258601646.cos.ap-shanghai.myqcloud.com/test/1588755657791850.mp4" width="800px" height="600px" controls="controls"></video>

**Comment by fish-uncle** [comment]
https://web-sr-1258601646.cos.ap-shanghai.myqcloud.com/test/1588755657791850.mp4

**Comment by zhetengbiji** [comment]
HBuilderX 2.7.0 alpha 有相关优化，你可以试一下

**Comment by fish-uncle** [comment]
:sweat:alpha不敢用哈

**Comment by zhetengbiji** [comment]
> 😓alpha不敢用哈

可以和正式版共存的，你可以下载了试用一下。

**Comment by luo772435545** [comment]
很无语这个问题

**Comment by luo772435545** [comment]
用value +@input 又无法清除值，我该怎么做

**Comment by zhetengbiji** [comment]
> 很无语这个问题

请具体描述一下问题

**Comment by luo772435545** [comment]
就是input 用的v-model
输入的时候一卡一卡的，删除的时候一卡一卡，和上面的视频一样；
清除值的时候value='';也是一卡一卡重复删除动作

**Comment by zhetengbiji** [comment]
> 就是input 用的v-model
> 输入的时候一卡一卡的，删除的时候一卡一卡，和上面的视频一样；
> 清除值的时候value='';也是一卡一卡重复删除动作

优化了，试试 HBuilderX 2.7.1 alpha
