### ISSUE TITLE
限制11位数字输入监听不到最后.的输入

### ISSUE THREAD

**Issue by ezjason** [dcloudio/uni-app#1646]
> [运行端是h5或app或某个小程序？] app/h5
> 
> [运行端版本号] 2.6.8
> 
> [项目是cli创建的还是HBuilderX创建的？如果是cli创建的，请更新到最新版cli再试]HBuilderX创建
> 
> [编译模式说明：自定义组件模式？纯nvue模式？v3模式？]自定义组件模式
> 
> [Android版本号]9
> 
> [ColorOS版本号]6.0.1
> 
> [MIUI版本号]11.0.5
> 
> [手机型号]oppo r15 梦境版/MI 6 X MIKU
> 
> [可重现代码片段]
> 

- 
[1588757390143255.mp4.zip](https://github.com/dcloudio/uni-app/files/4585928/1588757390143255.mp4.zip)

> ```
> <input type="text" v-model="phone" maxlength="11"/>
> ```

**Comment by dcloudhdx** [comment]
HBuilderX 2.8.0 测试正常，更新版本试试
