### ISSUE TITLE
uploadFile上传返回结果乱码

### ISSUE THREAD

**Issue by zhangchao123** [dcloudio/uni-app#165]
同样的后台接口，uni.request发起的返回，没有问题uni.uploadFile，返回的汉字乱码！

**Comment by zhetengbiji** [comment]
都有哪端出现此问题？H5？App？

**Comment by jeffreyhong0217** [comment]
我项目中也是出现这个问题，上传成功，后端返回的中文显示乱码，console打印是正常的！请问下有解决吗？

**Comment by ZDSDESIRE** [comment]
小程序端遇到同样的问题，uni.uploadFile上传返回的data.name是转码，非原始文件名

**Comment by zhetengbiji** [comment]
> 小程序端遇到同样的问题，uni.uploadFile上传返回的data.name是转码，非原始文件名

不使用uni-app的情况下使用wx.uploadFile是否正常？如仍然有问题，需要到微信小程序社区反馈一下。
