### ISSUE TITLE
vm.$children 在不同的平台下获取数据不相同

### ISSUE THREAD

**Issue by ZhiGang-Fang** [dcloudio/uni-app#1651]
**问题描述**
在父组件使用 this.$children 获取子组件数据时,发现在微信小程序中能正常获取,而在h5中获取数据和小程序不一致

**复现步骤**
[复现问题的步骤]
`
` mounted () {
    console.log('====================================')
    console.log(this.$children)
    console.log('====================================')
  }`
`

[或者可以直接贴源代码]

**预期结果**
期望在任何平台都能正常能获取数据

**实际结果**

微信小程序结果:
![image](https://user-images.githubusercontent.com/24228407/81378549-0ff3fb80-913a-11ea-8919-c02bd1e6bbb6.png)

H5运行的结果:

![image](https://user-images.githubusercontent.com/24228407/81378808-8e509d80-913a-11ea-9023-cf8364e553b8.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台]
 - 操作系统 [如 iOS 12.1.2]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果:uni-app v2.6.1、uni-app cli v2.0.0-26120200226001]
 - 设备信息 [如 iPhone8 Plus]

**Comment by zhetengbiji** [comment]
已在文档说明：
H5端 `view`、`text` 等内置标签是以 Vue 组件方式实现，`$parent`、`$children` 会获取到这些内置组件

目前提供2种解决方法：
1. 使用条件编译
2. 组件根节点用 div

另外，在各端访问$children是为了实现什么功能？
