### ISSUE TITLE
在内网（没有互联网）环境中，没法生成APPID 怎么打包生成本地资源？

### ISSUE THREAD

**Issue by cartWalk** [dcloudio/uni-app#1654]
**问题描述**
点击生成本地资源，控制台提示 网络链接失败。内网环境没有网络~

**预期结果**
在无网环境中，uniapp可以打包本地资源

**Comment by zhetengbiji** [comment]
手动编辑 manifest.json 写入即可

**Comment by cartWalk** [comment]
> 手动编辑 manifest.json 写入即可

随便写个 字符串 作为appid 控制台提示 ：该项目的appid所有者不是当前登陆的账号，请重新用正确的账号登陆或重新获取。没有网络，所以不能等开发工具的账号~就不能呢个获取appid

**Comment by zhetengbiji** [comment]
尝试使用新版的CLI工程导出

**Comment by hbcui1984** [comment]
你可以在有网环境时获取一个appid，然后配置到所需工程中。

后续，dev.dcloud.net.cn支持在线创建项目，获取appid。
