### ISSUE TITLE
头条小程序iOS真机provide/inject偶尔可以，偶尔不可以

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#1658]
如题，求解决。

可能是时机处理不恰当。

我 `provide this`过去，在iOS下偶尔可以，偶尔不可以。安卓好像没有问题。

幸亏`inject`的不深，不成功的我用`emit`事件来做转发了。

https://github.com/dcloudio/uni-app/issues/1657

**Comment by mehaotian** [comment]
发一下代码吧，或者留一个联系方式

**Comment by wakaryry** [comment]
QQ 382006503

**Comment by zhetengbiji** [comment]
由于底层限制（异步通迅），无法及时设置组件关系，初始化 provide/inject 较晚，可以在 created 或者更迟的生命进行访问。在 computed 中使用时，请加入判断，如：created () {this.isCreated = true},computed: {value () {return this.isCreated ? this.injectData.xxx : ''}}。
