### ISSUE TITLE
可以用swift开发原生插件吗

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#1659]
如题，不知道是否支持。

**Comment by xiaohuapunk** [comment]
可以，插件包最终需要的是 .framework 库，使用 swift 也可以开发依赖库，不过使用 swift 创建库工程需要解决混编的编译问题比较繁琐，建议还是直接使用 oc 开发

**Comment by LichKing-2234** [comment]
ITMS-90426: Invalid Swift Support 
集成了swift的插件的APP上架App Store会遇到这个问题被驳回

**Comment by coderBye** [comment]
可以提供个swift版本的demo嘛？

**Comment by FaceAISDK** [comment]
可以提供个swift版本的demo嘛？+1

**Comment by FaceAISDK** [comment]
> 可以提供个swift版本的demo嘛？

@coderBye 你好，你这边有swift 版本Demo 了吗？
