### ISSUE TITLE
使用 新语法 ??(Nullish coalescing operator) 报错，nullishCoalescingOperator，但是我已经安装了'@babel/plugin-proposal-nullish-coalescing-operator' 插件且用的还是ts

### ISSUE THREAD

**Issue by Jonny-china** [dcloudio/uni-app#1660]
**问题描述**
使用typescript 且 安装了`@babel/plugin-proposal-nullish-coalescing-operator` 插件，仍然报错
`Syntax Error: SyntaxError: This experimental syntax requires enabling the parser plugin: 'nullishCoalescingOperator' (231:71)`

> babel.config.js
```js
const plugins = [
  '@babel/plugin-proposal-optional-chaining',
  '@babel/plugin-proposal-nullish-coalescing-operator'
]

if (process.env.UNI_OPT_TREESHAKINGNG) {
  plugins.push(
    require('@dcloudio/vue-cli-plugin-uni-optimize/packages/babel-plugin-uni-api/index.js')
  )
}

if (process.env.UNI_PLATFORM === 'app-plus' && process.env.UNI_USING_V8) {
  const path = require('path')

  const isWin = /^win/.test(process.platform)

  const normalizePath = path => (isWin ? path.replace(/\\/g, '/') : path)

  const input = normalizePath(process.env.UNI_INPUT_DIR)
  try {
    plugins.push([
      require('@dcloudio/vue-cli-plugin-hbuilderx/packages/babel-plugin-console'),
      {
        file(file) {
          file = normalizePath(file)
          if (file.indexOf(input) === 0) {
            return path.relative(input, file)
          }
          return false
        }
      }
    ])
  } catch (e) {}
}

process.UNI_LIBRARIES = process.UNI_LIBRARIES || ['@dcloudio/uni-ui']
process.UNI_LIBRARIES.forEach(libraryName => {
  plugins.push([
    'import',
    {
      libraryName: libraryName,
      customName: name => {
        return `${libraryName}/lib/${name}/${name}`
      }
    }
  ])
})

module.exports = {
  presets: [
    [
      '@vue/app',
      {
        modules: 'commonjs',
        useBuiltIns: process.env.UNI_PLATFORM === 'h5' ? 'usage' : 'entry'
      }
    ]
  ],
  plugins
}

```

**预期结果**
应该能够正常使用

**实际结果**
![image](https://user-images.githubusercontent.com/31563977/81531206-dc60dd80-9394-11ea-9200-dc554d40881f.png)

**系统信息:**
 - 发行平台: 微信小程序
 - uni-app版本 
       uni-app v2.6.16
       uni-app cli v2.0.0-26920200424005

**Comment by 331000738** [comment]
同问，想使用管道服务，在编译小程序时，Babel配置加了parseOpts后，不使用目标特性时编译时不报错，使用则仍报错。
`module.exports = {

  presets: [

    [

      '@vue/app',

      {

        modules: 'commonjs',

        useBuiltIns: process.env.UNI_PLATFORM === 'h5' ? 'usage' : 'entry'

      }

    ]

  ],

  plugins,

  parserOpts: { 

    plugins: [

      ['pipelineOperator', { 'proposal': 'minimal' }] // babel不报错了，但不能用

    ]

  }

}

`

**Comment by 331000738** [comment]
暂时通过第三方babel插件解决：

![1589705957288](https://user-images.githubusercontent.com/57003774/82140184-6959da00-9860-11ea-88b1-58ef01debfd2.png)

![1589706252231](https://user-images.githubusercontent.com/57003774/82140206-9c03d280-9860-11ea-9915-444c734bc46e.png)

小程序下运行正常。

还是希望小程序下能支持原生tc39 babel插件。

**Comment by 2234839** [comment]
+1 遇到了相同的问题

**Comment by iptop** [comment]
+1 遇到了相同的问题，解决方案
找到 uni-cli-shared 这个包
定位到lib\platform.js 文件

找到这个函数
`
getBabelParserOptions () {
    return {
      sourceType: 'module',
      plugins: [
        'optionalChaining',
        'typescript',
        ['decorators', {
          decoratorsBeforeExport: true
        }],
        'classProperties'
      ]
    }
  }
`
  

把需要的语法加进去就不会报错了

比如说支持下do表达式
 `
 getBabelParserOptions () {
    return {
      sourceType: 'module',
      plugins: [
        'optionalChaining',
        'doExpressions',
        'typescript',
        ['decorators', {
          decoratorsBeforeExport: true
        }],
        'classProperties'
      ]
    }
  }

`
