### ISSUE TITLE
uni.setStorage保存一个时间后，再取出来会不正确

### ISSUE THREAD

**Issue by micropu** [dcloudio/uni-app#1661]
**问题描述**
uni.setStorage保存一个时间后，再取出来会不正确
原时间：Tue May 12 2020 01:59:58 GMT+0800 (中国标准时间)
保存后取出为：2020-05-11T17:59:58.422Z

![QQ图片20200511161155](https://user-images.githubusercontent.com/54704152/81539039-32884d80-93a2-11ea-9fed-6500028dd9af.png)
![QQ图片20200506122852](https://user-images.githubusercontent.com/54704152/81539043-33b97a80-93a2-11ea-8f47-f49c7796746c.png)

**Comment by zhetengbiji** [comment]
哪端？H5？App？哪个小程序？

**Comment by micropu** [comment]
H5




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "折腾笔记"<notifications@github.com&gt;; 
发送时间: 2020年5月12日(星期二) 下午3:06
收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 
抄送: "zhipu"<2001972@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dcloudio/uni-app] uni.setStorage保存一个时间后，再取出来会不正确 (#1661)





 
哪端？H5？App？哪个小程序？

**Comment by zhetengbiji** [comment]
HBuilderX 2.7.2 alpha 已修复
