### ISSUE TITLE
微信小程序端组件使用到解构插槽时，同一个页面使用多个该组件，除了第一个外，后面的插槽的内容的样式会被最后一个影响，测试h5和app的vue页面正常

### ISSUE THREAD

**Issue by EvanMaFYH** [dcloudio/uni-app#1662]
**问题描述**
微信小程序端组件使用到解构插槽时，同一个页面使用多个该组件，除了第一个外，后面的插槽的内容的样式会被最后一个影响，测试h5和app的vue页面正常

**复现步骤**
运行[demo](https://github.com/EvanMaFYH/slot-bug)，可以发现页面中除了第一个外后面的三个都变成了红色，而只有最后一个设置了红色

**预期结果**
预期结果应该只有最后一个是红色的

**实际结果**
除了第一个外后面的三个都变成了红色

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 2.6.16
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
app的vue页面和h5测试正常
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
HBuilderX 2.7.2 alpha 已修复
