### ISSUE TITLE
能通过什么样的方法知道ios设备是否越狱？

### ISSUE THREAD

**Issue by BecksWang** [dcloudio/uni-app#1664]
**新功能描述**
能否通过一个函数判断ios设备是否越狱

**现状及问题**
软件不允许运行在越狱设备，现在不知道怎么判断设备是否越狱

**尝试方案**
看了很多文章都是原生的方法

**补充信息**
[其它你认为有参考价值的信息]

**Comment by zhetengbiji** [comment]
https://uniapp.dcloud.net.cn/tutorial/app-sec-api.html#isroot
