### ISSUE TITLE
picker用户可以自定义颜色

### ISSUE THREAD

**Issue by Tron1234** [dcloudio/uni-app#1666]
**新功能描述**
简洁描述你希望补充完善的增强功能
目前在开发app端和H5端，通过改源码的方式已经将H5端picker改成自己想要的配色，请问app端picker组件样式在哪个路径下

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by bfc846958672** [comment]
你好，可以使用picker-view 来自定义相关颜色， [picker-view 文档地址](https://uniapp.dcloud.net.cn/component/picker-view.html#picker-view)。
