### ISSUE TITLE
picker组件无法清除日期

### ISSUE THREAD

**Issue by Beipy** [dcloudio/uni-app#1670]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

APP调用系统原生日历时无法清除时间功能。

picker 代码中添加input组件，被点击后会同时弹出软键盘和系统日历，会造成视觉污染。
现在为了不让他弹出小键盘我只能使用disabled禁用掉input可输入性。但此时若是想要清空时间日期该如果操作？

`<picker mode="date" :value="fromData.date"  :start="startDate" :end="endDate" @change="bindDateChange" >

						<view class="position-r">
							<input class="SearchInput fz-22 mr-30" type="text" :value="fromData.date" placeholder="请选择训练日期" disabled/>
							<text class="uni-icon arrows—icon fz-18 position-a">&#xe581</text>
						</view>
					</picker>
`

**复现步骤**

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

现在组件的样式图片。  [现在组件图片链接](https://ftp.bmp.ovh/imgs/2020/05/9946ea7b657043b8.png)

原生安卓自带清除功能图片  [自带清除功能图片链接](https://ftp.bmp.ovh/imgs/2020/05/4fd3f64a94e96f9f.jpg)

**Comment by mehaotian** [comment]
感觉你这个需求有问题啊，既然要使用picker ，为什么还用 input ？ 不可能在输入的时候选择日期或者选择日期的的时候输入吧 ？像你这种需求，直接放一个文本在picker内容，同时后面有一个删除按钮不是更好吗 ？
