### ISSUE TITLE
离线打包，启动图和效果设置问题

### ISSUE THREAD

**Issue by xiaomaokeke** [dcloudio/uni-app#1675]
大家好，小生开发很久得App 终于到了打包阶段了，本来项目可以使用uniapp 官方的云打包的，但是在刚开始阶段，会频繁测试功能和打包，感觉云打包比较麻烦(主要的是等待时间太久)，后来决定还是采用离线模式打包，离线模式打包跟着官方的文档和 SDK 中的示例上修修改改，将自己的项目打包八九不离十了，但是还有个问题需要大家帮忙解决，如何修改 启动图和启动效果？
1.启动图我看了官方文档，大部分讲的都是云打包的配置，没有离线打包的相关配置说明，希望官方大佬帮忙补充一下；

启动效果，官方默认的启动效果，会有一个绿色的转圈圈，我不想要那个，只是想要一张安安静静的图片在那里展示即可
![image](https://user-images.githubusercontent.com/64067386/81813782-79b93e80-955a-11ea-872e-0ec0147754d9.png)

云打包出来的效果,会有一个logo ，logo 周围有个加载效果的等待圈，但是本地打包却没有，如何才能实现效果一致呢？
望各位大佬解答一下，小生感激不尽，谢谢！

uni问答平台
https://ask.dcloud.net.cn/question/96472

**Comment by hbcui1984** [comment]
App 可以真机调试，不需要频繁打包验证。

**Comment by xiaomaokeke** [comment]
> App 可以真机调试，不需要频繁打包验证。

您好，感谢回复，我的原意是这样子的，本地打包可否自定义开屏动画（加载效果），官方默认的动态，产品经理不喜欢，他要替换自己设计的，还有就是如题所问的另外一个问题，官方云打包出来的，开屏动画会有logo 和logo 周围有加载动画，但是离线打包的却没有相同的效果，就是想问问，如何自定义呢？我看官方文档中没有这类效果的使用介绍，希望告知一下，谢谢啦

**Comment by ArrayDC** [comment]
云端打包请参考：https://ask.dcloud.net.cn/article/37475
离线打包请参考：https://nativesupport.dcloud.net.cn/AppDocs/usesdk/ios?id=%E9%85%8D%E7%BD%AE%E5%BA%94%E7%94%A8%E5%90%AF%E5%8A%A8%E7%95%8C%E9%9D%A2
