### ISSUE TITLE
我想问下使用uni-app开发以后转成微信，百度，支付宝的问题

### ISSUE THREAD

**Issue by china-yangzai** [dcloudio/uni-app#1677]
**问题描述**
uni-app开发一版以后，由于微信，百度，支付宝登录和授权都不一样，怎么能一键开发呢。不是还要修改逻辑么。
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by hbcui1984** [comment]
uni-app封装了uni.login方法，详见：https://uniapp.dcloud.net.cn/api/plugins/login

**Comment by wakaryry** [comment]
其实登录授权，各个小程序单独适配一下也没有什么问题。我基本都是条件处理的

**Comment by tom1jack** [comment]
为什么我打包成app后，uniapp.login就没反应了

**Comment by tom1jack** [comment]
安卓版的app
