### ISSUE TITLE
uni-app的webview引入页面无法打开摄像机

### ISSUE THREAD

**Issue by qiuyueL** [dcloudio/uni-app#1678]
**问题描述**
用uni-app自带的webview引入第三方h5页面时，需要吊起摄像头进行录像，在Android机上，只能打开照相机。因为h5页面不能上传已经拍摄好的视频，必须是实时录制的，也无法使用本地视频进行上传。

**复现步骤**
[复现问题的步骤]
1.  启动app
2. 点击一个按钮进入带有webview的页面，里面嵌入了第三方人脸验证的页面
3. 点击录制视频，出现的只有照相机、本地视频等。

**预期结果**
webview提供能够监听文件系统被打开的回调，然后通过回调，可以吊起uni-app的摄像机，并且将拍摄的地址链接在回调给webview内部，通过这种方式进行通信。
**实际结果**
![image](https://user-images.githubusercontent.com/21118350/82001497-dec18100-968d-11ea-905a-ae78734d37d2.png)

**系统信息:**
 - 发行平台: [Android]
 - 操作系统 [Android 9.0]
 - HBuilderX版本 [2.6.16]
 - uni-app版本 [2.6.16]
 - 设备信息 [红米]

**补充信息**
原生Android开发提供了webview的监听机制，并且使用其提供的方法，通过原生来吊起摄像头，并且将拍摄的临时uri回调给webview内部。

**Comment by 1369521908** [comment]
https://nativesupport.dcloud.net.cn/AppDocs/FAQ/android
看看这里能不能解决
![image](https://user-images.githubusercontent.com/32727597/112715199-0625e300-8f1a-11eb-8af3-0e44bd0a8669.png)
