### ISSUE TITLE
部分安卓机下导航栏失效

### ISSUE THREAD

**Issue by renjiankun** [dcloudio/uni-app#168]
uni-app项目使用HX打包好apk后在部分安卓手机下第一次登录app时导航栏是好用的，但是退出app在重新登录的话导航栏就会失效，请问这是怎么回事啊，如何解决啊，出现问题的手机型号为华为mate10

**Comment by hbcui1984** [comment]
建议上传 apk，方便验证；
如果apk涉及隐私，不方便公开上传，可以将apk单独发邮件到service@dcloud.io
