### ISSUE TITLE
ble支持mtu设置

### ISSUE THREAD

**Issue by zhubinsheng** [dcloudio/uni-app#1680]
**新功能描述**
简洁描述你希望补充完善的增强功能

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by dcloudhdx** [comment]
后期会支持

**Comment by longbomb** [comment]
> 后期会支持

万人血书尽快支持，好多人等着用呢，否则必须得转去微信小程序。

**Comment by zhubinsheng** [comment]
> > 后期会支持
> 
> 万人血书尽快支持，好多人等着用呢，否则必须得转去微信小程序。

可以让另一端把mtu传过来

**Comment by longbomb** [comment]
> > > 后期会支持
> > 
> > 
> > 万人血书尽快支持，好多人等着用呢，否则必须得转去微信小程序。
> 
> 可以让另一端把mtu传过来

不是两边都要设置MTU吗？好像是取最小的那边吧？只需要硬件设置也可以？

**Comment by zhubinsheng** [comment]
> > > > 后期会支持
> > > 
> > > 
> > > 万人血书尽快支持，好多人等着用呢，否则必须得转去微信小程序。
> > 
> > 
> > 可以让另一端把mtu传过来
> 
> 不是两边都要设置MTU吗？好像是取最小的那边吧？只需要硬件设置也可以？

苹果的系统层自动协商的，安卓的不行，我后来用的小程序开发

**Comment by dcloudhdx** [comment]
功能已开发完毕，下次发版生效

**Comment by longbomb** [comment]
> 功能已开发完毕，下次发版生效

非常感谢

**Comment by dcloudhdx** [comment]
HBuilderX 2.8.5+ 新增 支持蓝牙相关接口 uni.setBLEMTU、uni.getBLEDeviceRSSI

**Comment by Spacesless** [comment]
你们uni.setBLEMTU这Api有效么，我这安卓10设置MTU为128是成功了，手机发送超过20字节的数据，但是设备端还是只能收到20字节

**Comment by zhubinsheng** [comment]
> 你们uni.setBLEMTU这Api有效么，我这安卓10设置MTU为128是成功了，手机发送超过20字节的数据，但是设备端还是只能收到20字节

如何确保手机设置mtu成功？在设备端打印mtu协商的结果，抓空中包的长度

**Comment by longbomb** [comment]
> 你们uni.setBLEMTU这Api有效么，我这安卓10设置MTU为128是成功了，手机发送超过20字节的数据，但是设备端还是只能收到20字节

成功了，你看下你设备端有没有设置MTU，这个MTU设置是双向的，他会取手机端和设备端最小的那一个值协定。（提醒一下，这个MTU设置不能设置太大，150以上传输都有问题，不知道是uni的问题还是蓝牙的问题）
