### ISSUE TITLE
ios真机无法访问自签证的https接口，接口直接abort

### ISSUE THREAD

**Issue by 252085814** [dcloudio/uni-app#1682]
**问题描述**
[问题描述：uniapp打包成安卓和ios真机，接口访问的是自签证的https服务，在uni.request中设置了sslVerify为false，所以安卓访问是正常的，但是ios确不能正常访问，直接返回errMsg:request:fail abort。请问各位遇到过吗，怎么解决？]

**复现步骤**
[复现问题的步骤]
1.  启动
2. 请求接口
3. ios无法访问https自签证接口，安卓可以

**Comment by 252085814** [comment]
有人知道怎么处理吗？跪求~~~

**Comment by dcloudhdx** [comment]
iOS 系统不支持自签名证书
