### ISSUE TITLE
picker 组件 date

### ISSUE THREAD

**Issue by wuchenge** [dcloudio/uni-app#1687]
**问题描述**
picker

**复现步骤**
[复现问题的步骤]
2. 点击  '....'
<picker mode="date" fields="year" :value="birthday" @change="onDateChange">

**预期结果**
不报错就行

**实际结果**
[Vue warn]: Invalid prop: type check failed for prop "start". Expected String with value "1920", got Number with value 1920.

**系统信息:**
h5

**补充信息**
原始组件的开发人员手抖了吧

**Comment by mehaotian** [comment]
确定bug ，应该不影响正常功能，如不想看到错误，可以先手动指定一下开始和结束时间  `start="1900" end="2100"` , 下个版本修复
