### ISSUE TITLE
在app nvue页面使用 文本字符串太长会导致闪退

### ISSUE THREAD

**Issue by csq0668** [dcloudio/uni-app#1689]
用了官方富文本组件，然后文本字符串转数组，直接闪退。

**Comment by wakaryry** [comment]
app-nvue 平台 nodes 属性只支持使用 Array 类型。

这个字符串转数组需要自己转。

**Comment by csq0668** [comment]
我知道了，就是用了官方这个方法html-parser，转了，文本短一点没问题，文本长一点就闪退了

**Comment by wakaryry** [comment]
不知道你这个太长到底是多长。几千个字的我应该还正常

**Comment by csq0668** [comment]
七千字左右就会闪退

**Comment by wakaryry** [comment]
好的

**Comment by wakaryry** [comment]
我现在文本长了，转换是成功了，但是不渲染文本内容。我打算直接用vue页面的rich-text了

**Comment by dcloudhdx** [comment]
请提供测试数据

**Comment by hbcui1984** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
