### ISSUE TITLE
目前安卓测试键盘问题

### ISSUE THREAD

**Issue by FontEndArt** [dcloudio/uni-app#169]
身份证的input对于键盘的掌控力不够   还有带清除按钮的键盘和带小数点键盘的切换问题

直接切换和关闭键盘再使其他input获取焦点时候   键盘变化问题

感觉没有因为单一input而拥有特定的键盘  **尤其是身份证的input**

还请查看后尽可能修复   例子：官网app demo   组件-表单组件-input

**Comment by zhetengbiji** [comment]
目前app端并未实现特殊键盘

**Comment by FontEndArt** [comment]
> 目前应用端并未实现特殊键盘

其实不算是特殊键盘   只是在input切换时候  键盘没有刷新

**Comment by FontEndArt** [comment]
> 目前应用端并未实现特殊键盘

希望可以妥善处理下键盘的状态  比如身份证的是数字键盘也行    目前从密码键盘切换到身份证  依旧是字母的   也有其他的不一一举例说明了
