### ISSUE TITLE
为毛子我nvue页面安卓端字体图标出不来

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#1690]
nvue页面。

我是按照 uni-ui 上面的 icons方法来制作自己的图标的。

不同在于我的data是woff2: `data:application/x-font-woff2;`

小程序和app都测试过，**安卓app显示不出来**。

以前我用网络地址的时候，在头条小程序iOS下图标出不来，但是安卓端app和小程序还是有的。

难道一定要ttf的数据？

```
// #ifdef APP-NVUE
	const dom = weex.requireModule('dom');
	dom.addRule('fontFace', {
		'fontFamily': "mypiconfont",
		'src': "url('data:application/x-font-woff2;charset=utf-8;base64,d09GMgABAA...')"
        }
// #endif 
```

**Comment by dcloudhdx** [comment]
上面的代码只能在app平台上有效，头条需要单独加载字体
参考文档: `https://uniapp.dcloud.io/api/ui/font?id=loadfontface`

**Comment by wakaryry** [comment]
非nvue-app端我全部改用base64的data了。目前测试头条系也可以显示。

nvue-app端的我全部用了网络字体，iOS/Android正常。直接用base64的数据的时候Android不出来。
