### ISSUE TITLE
scroll-view自定义下拉刷新，会被触发两次

### ISSUE THREAD

**Issue by guohongshan** [dcloudio/uni-app#1693]
**问题描述**
scroll-view自定义下拉刷新，下拉时会触发两次refresherrefresh
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
下拉时只触发一次下拉请求

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/31247970/82291991-8f0bee00-99dc-11ea-9aea-ce5ca5fadda6.png)

**系统信息:**
 - 发行平台: [微信小程序、H5平台]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by dcloudhdx** [comment]
文档代码没有复现问题 https://uniapp.dcloud.net.cn/component/scroll-view
请提供测试代码

**Comment by StrivingRabbit** [comment]
此问题在3.1.22中已修复
