### ISSUE TITLE
路由

### ISSUE THREAD

**Issue by Zhjoker** [dcloudio/uni-app#17]
如何使用vue的路由导航

**Comment by hulinNeil** [comment]
不能使用vue路由

**Comment by hbcui1984** [comment]
`uni-app`的路由由框架自动处理，开发者仅需在`pages.json`中完成页面配置，然后使用`uni.navigateTo`接口或`navigator`组件进行跳转即可。

**Comment by Zhjoker** [comment]
ok

**Comment by SilurianYang** [comment]
你可以直接选择使用 [uni-simple-router](https://v3.hhyang.cn/) 它是一款专为 Uni App 量身定制的路由插件，提供无缝集成的特性，使得路由管理变得简单而高效。
