### ISSUE TITLE
request get请求数据没有转换为query string,拼接还是json

### ISSUE THREAD

**Issue by kwinH** [dcloudio/uni-app#1700]
![F56F39EB797C4653E840F6D8106E4A8F](https://user-images.githubusercontent.com/22871248/82417927-e37f9e00-9aae-11ea-8d2b-091e7b4a3860.jpg)

request get请求数据没有转换为query string,拼接还是json

**Comment by Wangyaqi** [comment]
什么版本的HBuilderX，运行在了哪端？

**Comment by hbcui1984** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
