### ISSUE TITLE
textarea 会出现输入的内容一直在自动回退和增加

### ISSUE THREAD

**Issue by cqzhong** [dcloudio/uni-app#1702]
**问题描述**
[textarea 会出现输入的内容时候，光标一直在闪]

**复现步骤**
[复现问题的步骤]
 输入文字内容，然后快速回退删除，并继续输入，会出现光标移至在闪

[或者可以直接贴源代码]
```
      <textarea v-model="remark" :disabled="!isEdit" class="remark-textarea" :placeholder="isEdit ? '请输入备注说明' : ''" />

```

**系统信息:**
 - 发行平台: [安卓手机]
 - 操作系统 [Android]
 - HBuilderX版本 [2.6.16.20200424]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [所有安卓手机]

**Comment by Wangyaqi** [comment]
使用2.7.0以上版本再试一下
