### ISSUE TITLE
发送POST请求时，data的内容不在Form data ，而是request payload

### ISSUE THREAD

**Issue by southpush** [dcloudio/uni-app#1703]
**问题描述**
发送http请求成功了的，但是因为数据后台根本接收不到返回是错误的，打开chrome浏览器看，发现发送的请求数据全在requests payload 里，header已经设置了 Content-Type，不知道是什么造成这个问题的。

**复现步骤**
[复现问题的步骤]

```
		uni.request({
			url: '/WebApi/Post',
			data: {
				C: 'AVEVA.CDMS.WebApi.DBSourceController',
				A: 'Login',
				UserName: 'admin',
				Password: 'admin',
			},
			header: {
				"Content-Type": "application/x-www-form-urlencode",
			},
			method: 'POST',
			success: function( res ) {
				console.log(res)
			},
			fail: function(err) {
				console.log(err)
			}
		})
````

**预期结果**
这是一个登录接口，期望登录成功获得token

**实际结果**
加了Content-Type的
![image](https://user-images.githubusercontent.com/33292427/82547744-cb7e4c00-9b8c-11ea-9c8e-41e38b1c53b3.png)

没加Content-Type的
![image](https://user-images.githubusercontent.com/33292427/82547843-f2d51900-9b8c-11ea-8ed1-f0b97731574e.png)
不管是哪种data都出现在了request payload里，后台获取不到数据

![image](https://user-images.githubusercontent.com/33292427/82547963-23b54e00-9b8d-11ea-840d-9a21e10c9f2a.png)

**系统信息:**
 - 发行平台:  h5
 - 操作系统 win10 chrome
 - HBuilderX版本 2.6.16.20200424
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 

**补充信息**

我一开始使用的是flyio的，但是遇到了同样的问题，数据在request payload里，以前用mpvue开发时没有遇到过这样的问题，第一次使用uniapp，希望有大佬能解答一下

**Comment by Wangyaqi** [comment]
application/x-www-form-urlencoded 结尾少了个d

**Comment by hbcui1984** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
