### ISSUE TITLE
在nvue页面组件中引入.nvue组件，实际却引入了同名的.vue组件？

### ISSUE THREAD

**Issue by frylstar** [dcloudio/uni-app#1705]
**问题描述**

在.nvue页面组件中引入了.nvue组件:
`import mixNavBar from '@/components/mix-nav-bar-order/mix-nav-bar-order.nvue';`

实际引入的却是 `/components/mix-nav-bar-order/mix-nav-bar-order.vue` 组件?
（mix-nav-bar-order目录下存在同名不同后缀的两个文件 .vue 和 .nvue）

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
能够正确引入对应后缀名称的.nvue组件

**系统信息:**
 - 发行平台: [H5平台、5+ App]
 - HBuilderX版本 [2.6.16]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
关闭easycom，再试试，https://uniapp.dcloud.io/collocation/pages?id=easycom

**Comment by frylstar** [comment]
可以了，谢谢~
