### ISSUE TITLE
HBuilder uni-app新闻/资讯app模版下载失败

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-app#1707]
mac 版本 2.7.5.20200519

HBuilder uni-app新闻/资讯模版下载失败 一直下载失败

**Comment by dcloudhdx** [comment]
别的模板是否正常？
暂时从这里拉取 `https://github.com/dcloudio/uni-template-news`

**Comment by dcloudhdx** [comment]
长时间无回复，暂时关闭
