### ISSUE TITLE
钉钉小程序中，子组件created不执行

### ISSUE THREAD

**Issue by diablosin** [dcloudio/uni-app#1709]
**问题描述**
钉钉小程序中，子组件created不执行

**复现步骤**
钉钉小程序中，子组件created不执行

**预期结果**
子组件created有效

**系统信息:**
 - 发行平台: 钉钉小程序
 - 操作系统  iOS 13.4.1、Android 7.0
 - HBuilderX版本 2.7.5.20200519

**Comment by mehaotian** [comment]
上传一个demo 或者贴一个代码片段，在钉钉小程序上测试是正常的，看看你是否有无一些特殊操作
