### ISSUE TITLE
能否支持钉钉e应用？

### ISSUE THREAD

**Issue by xiaooiax** [dcloudio/uni-app#171]

**Comment by cgxqd123** [comment]
> _No description provided._

支付宝的可以的话，钉钉的就可以

**Comment by SilverLeaves** [comment]
@cgxqd123 钉钉和支付宝全局对象不一样。

**Comment by heerorelena** [comment]
钉钉E应用那个蛋疼的要死的开发工具，强烈希望能支持钉钉e应用开发。

**Comment by greatGregLiu** [comment]
什么时候支持钉钉小程序吗？企业用户非常多

https://open-doc.dingtalk.com/microapp/isv/voa7dy

**Comment by hbcui1984** [comment]
参考：https://uniapp.dcloud.io/collocation/package
