### ISSUE TITLE
uni.request promise 版无 Typescript 返回类型

### ISSUE THREAD

**Issue by Ohcui** [dcloudio/uni-app#1710]
**问题描述**

uni.request 的 Typescript 类型定义为

`request(options?: RequestOptions): RequestTask;`

(@dcoudio/types/uni-app/uni.d.ts:60)

官方文档描述支持返回 Promise 对象
https://uniapp.dcloud.io/api/request/request

> 如果希望返回一个 requestTask 对象，需要至少传入 success / fail / complete 参数中的一个。
如果没有传入 success / fail / complete 参数，则会返回封装后的 Promise 对象

**预期结果**
Promise 返回对象在 Typescript 中有正确的类型

**实际结果**
现有类型无法通过 Typescript 类型检查, 后续代码全部 Typescript 类型报错

**系统信息:**
系统无关问题

**Comment by athrunsun** [comment]
[#561](https://github.com/dcloudio/uni-app/issues/561) 也提到了这个问题，官方还未统一处理返回Promise的情况，需要开发者自行处理。

不过我要指出来一下，那个issue的作者提出的solution并没有达到type check的目的。

```ts
type ApiOption = Omit<Partial<RequestOptions>, "success" | "fail" | "complete">;

interface Uni {
    request(options: ApiOption): Promise<any>;
}  
```

- 首先类型声明并没有放到`declare namespace UniApp {}`内部，所以request的这个overload是识别不到的。

- 其次，即使放到`declare namespace UniApp {}`内部，我的方法调用还是没被识别为期望的那个overload。

`src/typings/index.d.ts`:

```ts
declare namespace UniApp {
    type RequestOptionsWithoutCallback = Omit<RequestOptions, 'success' | 'fail' | 'complete'>;

    interface Uni {
        request(options: RequestOptionsWithoutCallback): Promise<[any, any]>;
    }
}
```

这里返回的Promise的类型参数是个tuple，因为根据[文档](https://uniapp.dcloud.io/api/README?id=promise-%e5%b0%81%e8%a3%85)，Promise返回形式返回的是一个数组，数组第一项为错误信息，第二项为返回数据。

调用代码：

```ts
uni.request({ url: '/some/api' });
```

该调用的返回值依然被判定为`UniApp.RequestTask`。我觉得原因是uni-app的那个`UniApp.Uni.request()`的参数`RequestOptions`中，`success`, `fail`, `complete`这三个参数本来就是optional的，即使把它们omit掉创造一个新类型`RequestOptionsWithoutCallback`，跟`RequestOptions`也没有区别。

我现在的解决方式是再封装一下request方法：

```ts
type RequestOptionsWithoutCallback = Omit<UniApp.RequestOptions, 'success' | 'fail' | 'complete'>;

function request(options: RequestOptionsWithoutCallback) {
    return new Promise((resolve, reject) => {
        uni.request({
            ...options,
            success: (result: UniApp.RequestSuccessCallbackResult) => resolve(result),
            fail: (result: UniApp.GeneralCallbackResult) => {
                console.error(result);
                reject(result);
            },
        });
    });
}
```

**Comment by adams549659584** [comment]
![image](https://user-images.githubusercontent.com/10492939/118401401-22333e80-b698-11eb-9599-2006be893e0c.png)
我也遇到了，暂时用这几行代码搞定

**Comment by adams549659584** [comment]
似乎Uni官方的Promise响应不大一样，还得改改就好

**Comment by adams549659584** [comment]
![image](https://user-images.githubusercontent.com/10492939/118401973-5c054480-b69a-11eb-8fc3-e01ecab0ebcc.png)
这样

**Comment by StrivingRabbit** [comment]
关于api 的 Promise 化类型提示。除 `uni.request 有返回值`、`同步的方法（即以 sync 结束）`、`以 create 开头的方法`、`以 manager 结束的方法`、`返回 task 的 api ` 暂不处理外，其他可以升级 @dcloudio/types@3.3.0 试试看

**Comment by StrivingRabbit** [comment]
部分 api promise 化提示已支持，后续进度请跟踪 #3009 查看
