### ISSUE TITLE
安卓 nvue 输入框 上推页面 还是会把input遮挡住

### ISSUE THREAD

**Issue by heymalio** [dcloudio/uni-app#1712]

**Comment by dcloudhdx** [comment]
贴段代码和配置看看

**Comment by heymalio** [comment]
你可以看下 hello uni-app  内置组件 里面的input 然后拉到最底下
在可查看密码的输入框 输入东西
我这边看不到 input 输入的东西

**Comment by dcloudhdx** [comment]
没有复现问题，请提供设备机型及设备详细信息和屏幕截图

**Comment by heymalio** [comment]
链接: https://pan.baidu.com/s/1M7hCiycUyEw-74YfACPKqA 提取码: qwte
我上传了一个视频 你看下
设备 华为 bkkal10 安卓版本 8.1.0

**Comment by heymalio** [comment]
我看了 华为 其他机型 也是一样哈 
弹出的 输入框 把input 都盖住了 用户根本不知道自己输了什么 隐藏了输入框才能知道
ios 却没有这个问题

**Comment by heymalio** [comment]
请问这个怎么解决 我业务 一大堆输入框。。 很着急 这个 软键盘一直被遮挡 input
设置 adjustResize 和 adjustPan 都不管用
到底是bug 还是 怎么可以用hack解决

**Comment by heymalio** [comment]
@dcloudhdx 我把版本回退到 2.16.6 尽然就可以了 软键盘不会遮挡input 那就是 2.7.5版本有问题哈

**Comment by ShineKidd** [comment]
2023 年，求解

**Comment by heymalio** [comment]
@ShineKidd 已弃坑 bug太多了 换flutter了
