### ISSUE TITLE
uni.chooseImage 调用这个Api, 打包成h5, 嵌套在Android端, 还有ios Android 端点击没响应, 没有出现图片选择器

### ISSUE THREAD

**Issue by mhz-tiantian** [dcloudio/uni-app#1713]
uni.chooseImage 调用这个Api, 打包成h5, 嵌套在Android端, 还有ios Android 端点击没响应, 没有出现图片选择器

**Comment by dcloudhdx** [comment]
vue 还是 nvue？

**Comment by frylstar** [comment]
在`Android`端，`webview`内嵌的H5页面无法触发相册选择，需要宿主应用做对应处理（`Android`中的`webview`需要调用系统相册/相机，需要`setWebChromeClient`并重写`WebChromeClient`的方法）。具体你可以自行搜关键字

**Comment by dcloudhdx** [comment]
nvue <web-view> 暂不支持，可以先使用 vue <web-view>

**Comment by dcloudhdx** [comment]
HBuilderX 2.7.6+ nvue webview 已支持选择图片
