### ISSUE TITLE
微信小程序端，自定义组件v-show标签无效

### ISSUE THREAD

**Issue by qingchiapp** [dcloudio/uni-app#1724]
人尽皆知的问题了

**Comment by mehaotian** [comment]
v-show 在小程序的自定义组件上无效，可以使用 v-if 或者手动设置组件的属性来隐藏显示

**Comment by enjoyWeb** [comment]
> v-show 在小程序的自定义组件上无效，可以使用 v-if 或者手动设置组件的样式来隐藏显示

我怎么试了v-if也是失效的呀？

**Comment by zhetengbiji** [comment]
> > v-show 在小程序的自定义组件上无效，可以使用 v-if 或者手动设置组件的样式来隐藏显示
> 
> 我怎么试了v-if也是失效的呀？

目前尚无此类报告，你仔细测试一下，如果确认后，单独详细反馈

**Comment by enjoyWeb** [comment]
> > > v-show 在小程序的自定义组件上无效，可以使用 v-if 或者手动设置组件的样式来隐藏显示
> > 
> > 
> > 我怎么试了v-if也是失效的呀？
> 
> 目前尚无此类报告，你仔细测试一下，如果确认，单独详细反馈

刚才又弄了一下，好像v-show和v-if都是可以，醉了
