### ISSUE TITLE
请问有支持飞书小程序的计划么 

### ISSUE THREAD

**Issue by Tannnnnnnks** [dcloudio/uni-app#1725]
**新功能描述**
飞书现在也挺火的   希望能够支持飞书小程序

**现状及问题**
目前飞书小程序大多数api和微信小程序极其类似

**Comment by Wangyaqi** [comment]
可以试试编成字节跳动小程序在飞书能不能正常使用

**Comment by hbcui1984** [comment]
cli版本已支持，飞书平台定义为：mp-lark。参考：https://uniapp.dcloud.net.cn/quickstart-cli
HBuilderX内置支持已完成，预计2周内发版。
