### ISSUE TITLE
[feat] 编译模式-自定义组件模式，求支持自定义组件的 externalClasses 和 options 等参数

### ISSUE THREAD

**Issue by auven** [dcloudio/uni-app#1726]
**新功能描述**
如题，请求支持 自定义组件的 externalClasses 和 options 等参数

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**

看到 dcloud 社区有类似的问题 [子组件的样式问题](https://ask.dcloud.net.cn/question/90542)

**Comment by fxy060608** [comment]
已支持，但不跨平台
https://github.com/dcloudio/uni-app/commit/03de6b76dd288b70a7854809891e1cf0ffd0ee6b
https://github.com/dcloudio/uni-app/commit/358f05b527bb04ce402d1ae2802628729dd9b430

**Comment by auven** [comment]
@fxy060608  请问目前支持哪些平台，是否有计划支持跨平台

**Comment by fxy060608** [comment]
> @fxy060608 请问目前支持哪些平台，是否有计划支持跨平台

目前应该只有微信和QQ小程序支持，暂无跨平台计划

**Comment by SuperJolly** [comment]
@fxy060608 支持后至少完善一下文档吧，社区上很多帖子都是不知道怎么使用
