### ISSUE TITLE
hBuilder最新版本当把编辑器移动到外接屏幕的时候软件不断闪屏

### ISSUE THREAD

**Issue by qiaoqiao10001** [dcloudio/uni-app#1727]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 'HBuilder'
2. 点击  将IDE移动到外接屏幕'
3. 查看  编辑器不断闪屏

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by wandali2019** [comment]
1. 无法复现。请提供下电脑操作系统、电脑型号、外接显示器等信息。
2. 排查下硬件，也有可能是连接线接口的问题

**Comment by qiaoqiao10001** [comment]
> 1. 无法复现。请提供下电脑操作系统、电脑型号、外接显示器等信息。
> 2. 排查下硬件，也有可能是连接线接口的问题

MacBook pro 13 2019  显示器是飞利浦 可能是显示器问题，我改天换个显示器试试 连接器是绿联 但是其他编辑器例如vscode是不会闪的

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
