### ISSUE TITLE
微信小程序端，写在自定义组件插槽内的样式不生效

### ISSUE THREAD

**Issue by social-uni** [dcloudio/uni-app#1729]
![image](https://user-images.githubusercontent.com/14007972/83118765-5fa66100-a101-11ea-88aa-652726ad902b.png)
![image](https://user-images.githubusercontent.com/14007972/83118785-67fe9c00-a101-11ea-8193-19f27d78bcca.png)

在本页面这么写的样式

![image](https://user-images.githubusercontent.com/14007972/83119615-84e79f00-a102-11ea-9ec3-cc5e0dfc4c64.png)

h5端正常

**Comment by qinkaiyuan** [comment]
![image](https://user-images.githubusercontent.com/14007972/83120320-79e13e80-a103-11ea-92f7-6a6f5f7ae281.png)
![image](https://user-images.githubusercontent.com/14007972/83120324-7bab0200-a103-11ea-9635-1d830877228f.png)

socpe一样，写在本页的元素样式就能生效，写进插槽里面的样式就不生效

**Comment by zhetengbiji** [comment]
fixed b6449e762c0a74ac84add88dc46f5139b2e6388d
