### ISSUE TITLE
页面刷新或重定向后路由中的hash会丢失

### ISSUE THREAD

**Issue by syuenkei** [dcloudio/uni-app#1731]
**问题描述**
路由重定向下
路由前置守卫中日志
location.href ==== http://localhost:8080/callback?type=qqScan#token=89jhkjczx 
location.hash ==== #token=89jhkjczx
App.vue中日志： App Launch   App Show
登录回调页面日志 
 location.href ==== http://localhost:8080/callback?type=qqScan
location.hash ==== 

应用内路由跳转
路由前置守卫中日志
location.href ==== http://localhost:8080/callback?type=qqScan#token=89jhkjczx 
location.hash ==== #token=89jhkjczx
没有App.vue中日志
登录回调页面日志
location.href ==== http://localhost:8080/callback?type=qqScan#token=89jhkjczx 
location.hash ==== #token=89jhkjczx

补充信息
h5路由模式用的是history  
uni-simple-router
考虑到应用重新启动才会丢失hash 应该不是路由插件的原因

**Comment by zhetengbiji** [comment]
试试新版是否正常

**Comment by hbcui1984** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
