### ISSUE TITLE
小程序部分将组件非scoped的style作用到页面上

### ISSUE THREAD

**Issue by longjiahui** [dcloudio/uni-app#1732]
**新功能描述**
小程序部分将组件非scoped的style作用到页面上

**现状及问题**
当前没办法在组件中对子组件样式进行穿透，/deep/无法生效，要写在页面的样式中才可以

**尝试方案**
将在组件中出现的class样式写到页面中去。

**Comment by fxy060608** [comment]
组件配置options的styleIsolation为shared
参考：https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F%E9%9A%94%E7%A6%BB
```javascript
<script>
    export default {
        options: {
            styleIsolation: 'shared'
        },
        data() {
            return {

            };
        }
    }
</script>
```

**Comment by Iongtao** [comment]
> ```js
> styleIsolation
> ```

请问vue3中如何写styleIsolation？ script setup如何写

**Comment by fxy060608** [comment]
> > ```js
> > styleIsolation
> > ```
> 
> 请问vue3中如何写styleIsolation？ script setup如何写

```js
export default {
    options: {
        styleIsolation: 'shared'
    }
}
```
script setup 方式稍后提供支持

**Comment by yuanasdfgh** [comment]
![image](https://user-images.githubusercontent.com/54890571/167681991-a8dd2780-a9fc-4445-b00b-3e4a8f77fcd6.png)
