### ISSUE TITLE
uniapp h5下picker日期选择的start与end无效果

### ISSUE THREAD

**Issue by bin362490109** [dcloudio/uni-app#1737]
**问题描述**
<picker mode="date" :value="date" :start="startDate" :end="endDate" @change="bindDateChange">
<view class="uni-input">{{date}}</view>
</picker>
startDate="2010-01-01" ,endDate="2025-01-01"

**预期结果**
弹出框的日期范围应为2010-01-01到2025-01-01
**实际结果**
实际范围1990-2099 ，没滚动到底，但是结果肯定不对，start 和end 没生效

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
start与end限制的是选择范围，不是显示范围
