### ISSUE TITLE
子组件上加，if=“数组.length”时，子组件内无法watch父组件传进来的值

### ISSUE THREAD

**Issue by social-uni** [dcloudio/uni-app#1738]
h5正常，微信端异常

详见以下链接

[详情](https://www.jianshu.com/p/4c13237cd9a5)

**Comment by qinkaiyuan** [comment]
uniapp坑watch

彭星月
2020.05.21 11:15:54
字数 184
阅读 13
子组件的watch时间监听不生效，原因在组件中使用了v-if对数组，无奈将父组件的v-if去掉，改用其他逻辑处理
父组件使用 talkCP 子组件，将listData传给子组件，但是子组件没有监听到组件的变化

<view v-if="list.length > 0">

<talkCP :listData="list" :userInfo="userInfo" :hasLogin="hasLogin"></talkCP>

<view v-if="list.length > 0 && isFinished" class="flex-center dy-font-color pd20">没有更多数据了</view>

</view>

<view class="dy-font-color flex-center mgt20" v-else>

暂无数据

</view>

子组件

watch: {

listData(val) {

this.postList = val;

}

},

mounted(){

// this.postList = this.listData;

console.log('postList:'+this.postList)

}

**Comment by qinkaiyuan** [comment]
![image](https://user-images.githubusercontent.com/14007972/83336851-6a234f00-a2e9-11ea-8433-745d1a046963.png)

**Comment by qinkaiyuan** [comment]
目前测试不止加上v-if='数组.length' 子组件无法响应式。

而是 传入 数组.length ，子组件就无法响应式

**Comment by mehaotian** [comment]
给一个完整的demo ，你这代码片段看不懂具体的操作。无法复现

**Comment by StrivingRabbit** [comment]
#1827 同类问题，此issue关闭
