### ISSUE TITLE
image组件解析图片组件不正常

### ISSUE THREAD

**Issue by cnJLF** [dcloudio/uni-app#1739]
后端的接口返回的图片地址为："http://127.0.0.1:84/uploads/attach/2020\05\28/913a8d5099f6a34bde933390f28d0df7.jpg"
放入image组件后图片加载不出来，经过控制台查看发现image组件的background-image解析是：
"http://127.0.0.1:84/uploads/attach/2020\5 (/913a8d5099f6a34bde933390f28d0df7.jpg"
请教 这个问题怎么解决？

**Comment by Wangyaqi** [comment]
这种路径的图片你们有线上能访问的吗
