### ISSUE TITLE
uni-app button颜色如何调整？

### ISSUE THREAD

**Issue by lifengand1992** [dcloudio/uni-app#174]
uni-button[type=primary]{
background-color:red;
}
上面这样调整，在app上没有效果，在h5上可以？

**Comment by mehaotian** [comment]
给button 添加类名为 .uni-button 。
button.uni-button[type=primary]{
  background-color:red;
}
给button按钮加上权重试一下。

**Comment by haarlike** [comment]
同问

**Comment by zhetengbiji** [comment]
> 同问

直接修改background-color即可，比如：https://github.com/dcloudio/uni-template-login/blob/master/App.vue

**Comment by Cifer-Y** [comment]
renderer 为 native 的 纯 nvue 项目还是改不了, 有其他办法吗?

**Comment by 297ya** [comment]
行内 style:{xxxx:xxx} 修改
