### ISSUE TITLE
云开发上传图片问题 uniCloud.uploadFile 急急急 线上项目图片突然无法上传

### ISSUE THREAD

**Issue by Nicholas003** [dcloudio/uni-app#1740]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
云开发突然报错网关系统错误
一直是线上项目，之前一直没问题，今天下午两点多久图片都上传不了图片了
我看了我其他的项目是没有问题的
`uni.chooseImage({
				    count: 6, //默认9
				    sizeType: ['original', 'compressed'], //可以指定是原图还是压缩图，默认二者都有
				    sourceType: ['album'], //从相册选择
				    success:async function (img_res) {
				        // console.log(JSON.stringify(res.tempFilePaths));
						console.log(img_res)
						let res = await uniCloud.uploadFile({
							filePath: img_res.tempFilePaths[0],
							onUploadProgress: function(progressEvent) {
								var percentCompleted = Math.round(
									(progressEvent.loaded * 100) / progressEvent.total
								);
								uni.showLoading({
									title: `上传中${percentCompleted}%`
								});
								console.log(percentCompleted)
							}
						});
				    }
				});`
上面代码这样写就会提示网关错误

[或者可以直接贴源代码]

**预期结果**

预期结果就是正常上传图片

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/39424835/83352985-01d47c00-a382-11ea-9d3b-1931d62618a4.png)

**系统信息:**
 - 发行平台: [微信小程序 qq小程序 字节小程序]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - 设备信息 [ iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
不知道呢，其他小程序没问题
我的qq：826861827

**Comment by Nicholas003** [comment]
Uncaught (in promise) Error: 网关系统错误 << no response in 3000ms, address:hsf://172.20.4.182:12200?ROUTE=-1&APP=674bc419-7b5e-47cd-9670-ff603d9f0354&_ENV=DEFAULT&_TIMEOUT=3000&METADATA_DELAYED_PUBLISH=false&_p=hessian2&v=2.0&id=ams-serverless-service-group-1-5-55889c67b5-xwh9j&_TID=56e8105b-b5d6-41d7-ba89-8d4076248b3f&_CONTAINERID=ecc:ams-serverless-service-group-1-5-55889c67b5-xwh9j&_CONNECTTIMEOUT=1000&_SERIALIZETYPE=hessian&ig=defaultGroup
    at complete (index.js:1)
    at Function.o.complete (VM699 WAService.js:1)
    at VM699 WAService.js:1
    at C (VM699 WAService.js:1)
    at i.<anonymous> (VM699 WAService.js:1)
    at i.emit (VM699 WAService.js:1)
    at Ci (VM699 WAService.js:1)
    at VM699 WAService.js:1
    at VM699 WAService.js:1
    at n (VM697 asdebug.js:1)
_construct @ global.js:20
Wrapper @ global.js:20
(anonymous) @ global.js:20
s @ index.js:1
complete @ index.js:1
o.complete @ VM699 WAService.js:1
(anonymous) @ VM699 WAService.js:1
C @ VM699 WAService.js:1
(anonymous) @ VM699 WAService.js:1
i.emit @ VM699 WAService.js:1
Ci @ VM699 WAService.js:1
(anonymous) @ VM699 WAService.js:1
(anonymous) @ VM699 WAService.js:1
n @ VM697 asdebug.js:1
(anonymous) @ VM697 asdebug.js:1
t.emit @ VM697 asdebug.js:1
callback @ VM697 asdebug.js:1
(anonymous) @ VM697 asdebug.js:1
(anonymous) @ VM699 WAService.js:1
(anonymous) @ VM699 WAService.js:1
Promise.then (async)
asyncGeneratorStep @ test_up_img.vue?4e0b:1
_next @ test_up_img.vue?4e0b:1
(anonymous) @ test_up_img.vue?4e0b:1
(anonymous) @ test_up_img.vue?4e0b:1
success @ test_up_img.vue:23
o.(anonymous function) @ VM699 WAService.js:1
(anonymous) @ VM699 WAService.js:1
r @ VM699 WAService.js:1
(anonymous) @ VM699 WAService.js:1
v @ VM699 WAService.js:1
(anonymous) @ VM699 WAService.js:1
(anonymous) @ VM697 asdebug.js:1
(anonymous) @ VM699 WAService.js:1
(anonymous) @ VM699 WAService.js:1
setTimeout (async)
setTimeout @ VM699 WAService.js:1
(anonymous) @ VM697 asdebug.js:1
(anonymous) @ VM697 asdebug.js:1
(anonymous) @ VM697 asdebug.js:1
_ws.onmessage @ VM697 asdebug.js:1

这里是报错信息

**Comment by Wangyaqi** [comment]
现在上传正常吗？

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
