### ISSUE TITLE
uni-ui 组件库 npm 上传后 的 package.json 里  dependencies  引入怎么干掉的 

### ISSUE THREAD

**Issue by ImKarson** [dcloudio/uni-app#1744]
uni-app v2.7.9
uni-app cli v2.0.0-27920200527001

Environment Info:

  System:
    OS: macOS 10.15.3
    CPU: (8) x64 Intel(R) Core(TM) i7-6700HQ CPU @ 2.60GHz
  Binaries:
    Node: 8.15.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 83.0.4103.61
    Firefox: 66.0.5
    Safari: 13.0.5
  npmPackages:
    @dcloudio/types: * => 1.0.0 
    @dcloudio/uni-app-plus: ^2.0.0-27520200518001 => 2.0.0-27920200527001 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-automator: ^2.0.0-27520200518001 => 2.0.0-27920200527001 
    @dcloudio/uni-cli-shared: ^2.0.0-27920200527001 => 2.0.0-27920200527001 
    @dcloudio/uni-h5: ^2.0.0-27920200527001 => 2.0.0-27920200527001 
    @dcloudio/uni-helper-json: * => 1.0.5 
    @dcloudio/uni-migration: ^2.0.0-27520200518001 => 2.0.0-27920200527001 
    @dcloudio/uni-mp-alipay: ^2.0.0-27920200527001 => 2.0.0-27920200527001 
    @dcloudio/uni-mp-baidu: ^2.0.0-27920200527001 => 2.0.0-27920200527001 
    @dcloudio/uni-mp-qq: ^2.0.0-27920200527001 => 2.0.0-27920200527001 
    @dcloudio/uni-mp-toutiao: ^2.0.0-27920200527001 => 2.0.0-27920200527001 
    @dcloudio/uni-mp-weixin: ^2.0.0-27920200527001 => 2.0.0-27920200527001 
    @dcloudio/uni-quickapp-native:  2.0.0-27920200527001 
    @dcloudio/uni-quickapp-webview:  2.0.0-27920200527001 
    @dcloudio/uni-stat: ^2.0.0-27920200527001 => 2.0.0-27920200527001 
    @dcloudio/uni-template-compiler: ^2.0.0-27920200527001 => 2.0.0-27920200527001 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-27920200527001 => 2.0.0-27920200527001 
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-27920200527001 => 2.0.0-27920200527001 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-27920200527001 => 2.0.0-27920200527001 
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-27920200527001 => 2.0.0-27920200527001 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-27920200527001 => 2.0.0-27920200527001 
    @hap-toolkit/dsl-vue:  0.6.13 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.1.2 
    @vue/babel-preset-app:  4.4.1 
    @vue/babel-preset-jsx:  1.1.2 
    @vue/babel-sugar-functional-vue:  1.1.2 
    @vue/babel-sugar-inject-h:  1.1.2 
    @vue/babel-sugar-v-model:  1.1.2 
    @vue/babel-sugar-v-on:  1.1.2 
    @vue/cli-overlay:  4.4.1 
    @vue/cli-plugin-babel: ^4.3.0 => 4.4.1 
    @vue/cli-plugin-router:  4.4.1 
    @vue/cli-plugin-typescript: * => 4.4.1 
    @vue/cli-plugin-unit-mocha: ^4.4.1 => 4.4.1 
    @vue/cli-plugin-vuex:  4.4.1 
    @vue/cli-service: ^4.3.0 => 4.4.1 
    @vue/cli-shared-utils:  4.4.1 
    @vue/component-compiler-utils:  3.1.2 (3.1.2)
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/test-utils: ^1.0.3 => 1.0.3 
    @vue/web-component-wrapper:  1.2.0 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.11 => 2.6.11 
    vue-class-component:  6.3.2 (7.2.3)
    vue-hot-reload-api:  2.3.4 
    vue-jest: ^3.0.5 => 3.0.5 
    vue-loader:  15.9.2 (15.9.2)
    vue-property-decorator:  8.4.2 
    vue-router:  3.0.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler:  2.6.11 
    vue-template-es2015-compiler:  1.9.1 
    vuex:  3.4.0 
  npmGlobalPackages:
    @vue/cli: Not Found

**Comment by ImKarson** [comment]
没人回复吗？？

**Comment by ImKarson** [comment]
急急急急急啊

**Comment by SiiZhao** [comment]
干啥，直接干就行了

**Comment by ImKarson** [comment]
本地上传的么




| |
i_karson
|
|
邮箱：i_karson@163.com
|

Signature is customized by Netease Mail Master

在2020年06月02日 19:36，SiiZhao 写道：

干啥，直接干就行了

**Comment by zhetengbiji** [comment]
你好，能否详细说明一下问题

**Comment by hbcui1984** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
