### ISSUE TITLE
存在project.config.json文件时，qq编译未copy到编译产出中

### ISSUE THREAD

**Issue by LYnnProspery** [dcloudio/uni-app#1748]
```if (process.env.UNI_PLATFORM === 'mp-weixin' || process.env.UNI_PLATFORM === 'mp-qq')```
看qq和微信是一样处理，但是qq没copy过去。
还没找到copy相关的源码，能请教下吗

**Comment by fxy060608** [comment]
cli工程？在项目根目录，创建project.config.json，然后里边可以配置miniprogramRoot指向编译后的目录就行了吧

**Comment by LYnnProspery** [comment]
`"miniprogramRoot": "dist/build/mp-qq",`

即使定了了这种，qq编译产出依然没有把Project.config.json copy过去。微信可以。

btw，有两个问题：

1. 即使写死这种path有用，在同一套代码 会编译到 qq & weixin平台的时候，还需要去手动改dest目录path吗？

2. dev/build也是两个目录，是底层会再兼容dev/build吗？

抱歉还没有充分的看源码，提了一些逻辑性的问题，目前还不是特别清楚Project.config.json 这块copy的逻辑，只看到pages-loader里在跳过不生成 project: {...}

希望能够请教以上两个问题，告知copy的策略代码位置后，也许可以自行看看为什么qq的Project.config.json没有copy过去

**Comment by LYnnProspery** [comment]
btw 能否加个微信，我们是top5小程序，有机会希望能交流下。
wx: l59733984
ps: wx首字母小写L

**Comment by fxy060608** [comment]
你的具体需求是什么？就是把project.config.json复制到qq小程序吗？
假设需要自己完全定制project.config.json的话，那微信和QQ也应该是分开的吧，分别有自己的project.config.json配置

**Comment by dingling001** [comment]
微信怎么把 project.config.json 打到开发环境？

**Comment by dingling001** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
