### ISSUE TITLE
android 10 uni.request 报request fail abort statusCode:1 

### ISSUE THREAD

**Issue by 25juan** [dcloudio/uni-app#1750]
**问题描述**
在Android10上面调用uni.request请求后台数据错误，报错信息为request fail abort statusCode:1 

**复现步骤**
[复现问题的步骤]
```js
uni.request({
	url: "http://rap2.taobao.org:38080/app/mock/230092/test",
	method: 'POST',
	sslVerify: false,
	success: function(result) {
          console.log(result)
	},
	fail: function(e) {
		console.log(e)
		uni.showToast({
			position: 'top',
			icon: 'none',
			title: `网络请求错误,请稍后重试。${JSON.stringify(e)} `
		})

	}
})
```

**预期结果**
希望能够得到正确的ajax返回数据

**实际结果**
网络请求错误,请稍后重试。${JSON.stringify(e)} 
![F199D96E01B45014AD31A69C7EA5AB43](https://user-images.githubusercontent.com/14308183/83515817-8f41d880-a508-11ea-8d0f-294ed5c2e65b.jpg)

**系统信息:**
 - 发行平台: nvue
 - 操作系统 android 10
 - HBuilderX版本 :2.7.9.20200527
 - uni-app版本 最新稳定版本
 - 设备信息 小米9se

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by yuanjianhua** [comment]
怎么解决的呢
