### ISSUE TITLE
titleNview配置tags，点击事件如何触发或监听？

### ISSUE THREAD

**Issue by 364** [dcloudio/uni-app#1751]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
```
{
	"path": "pages/index/index",
	"style": {
		"navigationBarTitleText": "",
		"app-plus": {
			"titleNView": {
				"tags": [{
					"tag": "img",
					"src": "/static/image/icons@2x.png",
					"position": {
						"right": "20px",
						"bottom": "13px",
						"width": "20px",
						"height": "18px"
					}
				}]
			}
		}
	}
}
```

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Wangyaqi** [comment]
可以使用字体图标替代图片使用button替换tag或者自行绘制图片上去[https://www.html5plus.org/doc/zh_cn/nativeobj.html](https://www.html5plus.org/doc/zh_cn/nativeobj.html)

**Comment by dcloudhdx** [comment]
长时间无回复，暂时关闭，如果有问题，请重新打开

**Comment by EVINK** [comment]
楼主有解决的思路吗？

**Comment by EVINK** [comment]
我有一个曲线救国的思路，先用tag把要用的图标位置定好，再在button里加按钮然后也定位在同一个位置，最后把字去掉，相当于间接的点按了tag

**Comment by EVINK** [comment]
@Wangyaqi 应该说的是这个东西，我翻了好久的api才找到…

```js
onLoad {
  // const titleView = this.$mp.page.$getAppWebview().getSubNViews()[0]
  const titleView = this.$mp.page.$getAppWebview().getTitleNView()
      titleView.draw([
        {
          tag: 'font',
          text: '我是居中的标题',
          position: {
          left: 'auto',
          top: 'auto',
          width: '40rpx',
          height: '40rpx'
        }
      }
  ])
}
```

参考 https://ask.dcloud.net.cn/article/1205

**Comment by 364** [comment]
@EVINK 我最后是用`buttons`的字体图标解决的
```
"style": {
    "navigationBarTitleText": "这是标题",
    "app-plus": {
        "titleNView": {
            "buttons": [{
	        "fontSrc": "_www/static/fonts/iconfont.ttf",
		"text": "\ue6a0",
		"fontSize": "18",
		"color": "#333333"
	    }]
	}
    }
}
```
