### ISSUE TITLE
Promise函数 无法接收传参

### ISSUE THREAD

**Issue by dunkong** [dcloudio/uni-app#1754]
**问题描述**
Promise 函数无法接收传参，经查看源码发现是编译过的代码参数名有误，导致参数接收不到

代码片段如下：
`test(a,b,c){
 return new Promise((resolve, reject)=>{
   console.log(a,b,c)
 })
}`
a,b,c无法接收到或者是有个别接收不到，这个问题之前没有，已经严重影响了已上线的项目，目前只测试了微信小程序

**系统信息:**
 - 发行平台:  微信小程序
 - HBuilderX版本 2.7.9.20200527

**补充信息**
经查看源码发现是编译过的代码参数名有误，导致参数接收不到

**Comment by fxy060608** [comment]
贴一下编译后的代码

**Comment by dunkong** [comment]
![image](https://user-images.githubusercontent.com/27876762/83707424-8c500080-a64c-11ea-88ca-02905c69f34d.png)
如图，我传了三个参数，中间的一个参数和Promise的 resolve 重名了，直接导致中间的这个参数读不到了

**Comment by dunkong** [comment]
> 贴一下编译后的代码



> 贴一下编译后的代码

![image](https://user-images.githubusercontent.com/27876762/83707424-8c500080-a64c-11ea-88ca-02905c69f34d.png)
如图，我传了三个参数，中间的一个参数和Promise的 resolve 重名了，直接导致中间的这个参数读不到了

**Comment by dunkong** [comment]
> 贴一下编译后的代码

![image](https://user-images.githubusercontent.com/27876762/83707723-3891e700-a64d-11ea-8749-c91003db2a33.png)
这是未编译之前的，目前已经有好几个项目受到了影响

**Comment by fxy060608** [comment]
> > 贴一下编译后的代码
> 
> ![image](https://user-images.githubusercontent.com/27876762/83707723-3891e700-a64d-11ea-8749-c91003db2a33.png)
> 这是未编译之前的，目前已经有好几个项目受到了影响

你是说this.aname=aname接收不到？
我没看到编译后的代码有啥不对，你base2img传的aname，没在Promise里边使用，跟resolve同名也没任何影响。

**Comment by dunkong** [comment]
> > > 贴一下编译后的代码
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/27876762/83707723-3891e700-a64d-11ea-8749-c91003db2a33.png)
> > 这是未编译之前的，目前已经有好几个项目受到了影响
> 
> 你是说this.aname=aname接收不到？
> 我没看到编译后的代码有啥不对，你base2img传的aname，没在Promise里边使用，跟resolve同名也没任何影响。

就是因为使用了才有影响哈，没使用我倒不用来反馈了，你看下编译后的代码，this.aname=aname只是我传不了值临时用的解决方案，您可以忽略，重点就是编译后重名导致接收不到参数了
![image](https://user-images.githubusercontent.com/27876762/83830218-2d0af280-a717-11ea-9178-f32f4035e9cb.png)

**Comment by fxy060608** [comment]
可以发一个能重现的测试工程
单看你截图的编译后代码，是没有问题，也许你没有截全。
压缩使用的terser，理论上不会出现这种错误
