### ISSUE TITLE
如何类似vue打包之后生成一个配置文件修改接口

### ISSUE THREAD

**Issue by betterLeaf** [dcloudio/uni-app#1755]
![QQ图片20200604103553](https://user-images.githubusercontent.com/26402214/83708593-303aab80-a64f-11ea-89db-d69d3d7d9282.png)

原文链接
https://www.cnblogs.com/Mrrabbit/p/7852792.html

**Comment by SiiZhao** [comment]
这个插件感觉比较脱裤子放屁哦，你直接放个json在static目录，用uni.request 请求不就行了
如果一定搞插件搞写在vue.config.js里

**Comment by betterLeaf** [comment]
> 这个插件感觉比较脱裤子放屁哦，你直接放个json在static目录，用uni.request 请求不就行了
> 如果一定搞插件搞写在vue.config.js里

1. 我现在需要把uni 打包h5之后 会暴露出一个配置文件，到时候玩测试环境和正式环境，修改配置文件的url就可以啦，

2. uni.request无法请求本地的json文件吧

3. json放到static, build之后也会编译到js文件中的呀，并不能起到配置的作用
![image](https://user-images.githubusercontent.com/26402214/83714926-c75b2f80-a65e-11ea-95d9-8fdc94ee358a.png)

4. 希望大哥大姐给个思路，怎么玩啊，万分感激

**Comment by fxy060608** [comment]
仅限 h5 平台
1.static下创建config.js 
```javascript
var API = 'http://example.com';//全局变量
```
2.自定义html模板：https://uniapp.dcloud.io/collocation/manifest?id=h5-template
引用config.js
`<script src="/static/config.js"></script>`
3.其他代码中直接访问全局变量API
```
console.log(API)
```
