### ISSUE TITLE
Picker选择器出现报错，内附demo

### ISSUE THREAD

**Issue by zzlit** [dcloudio/uni-app#1756]
**问题描述**

在picker选择器`mode = multiSelector`的情况下`columnchange`出现报错，vConsole里面报错信息为：
```
Uncaught null
Script error
```
真机调试复现bug概率较大，偶尔正常，小程序开发工具没有问题。

**复现步骤**
demo 安装依赖后直接运行即可
[demo.zip](https://github.com/dcloudio/uni-app/files/4727171/demo.zip)

**系统信息:**
uni-app v2.7.9
uni-app cli v2.0.0-27920200527001

**Comment by zhetengbiji** [comment]
这个问题仅出现在运行到微信小程序吗？

**Comment by zzlit** [comment]
@zhetengbiji 目前是只测试了微信小程序

**Comment by zhetengbiji** [comment]
试试更换基础库版本，如果仍然有问题需要反馈到小程序社区
