### ISSUE TITLE
HBuilderX安装插件显示下载失败，检测网络是否正常！

### ISSUE THREAD

**Issue by 476421978** [dcloudio/uni-app#1757]
MacBook Air 安装的是HBuilderX App开发版，检测过网络正常，防火墙也关闭了，不知道什么原因，求解 #

**Comment by wandali2019** [comment]
1. 首先确保网络正常，如已开启vpn，请关闭。
2. 请确保安装目录正确，需要安装到/Applications目录下。下载HBuilderX后，需要拖到/Applications目录，不能直接双击打开。具体见：https://ask.dcloud.net.cn/article/36085
3.  如果上面两步未解决问题，菜单菜单【帮助】【查看运行日志】，看下日志中的错误。根据错误来解决

**Comment by 476421978** [comment]
OK
