### ISSUE TITLE
uni.reLaunch 跳转 tabBar 传递参数失败？

### ISSUE THREAD

**Issue by AlvinMi** [dcloudio/uni-app#1759]
**问题描述**

场景：H5 和小程序 tabBar 跳转切换的时候传递参数, 其他平台暂测试。

- [switchtab](https://uniapp.dcloud.io/api/router?id=switchtab) 路径后不能带参数。
- uni.redirectTo 和 uni.navigateTo 不能用做 tabBar。

使用 [uni.reLaunch](https://uniapp.dcloud.io/api/router?id=relaunch) 跳转带参数无效果，不会报错。文档是写可以带参数的：

```js
// a.vue
goToFamily() {
  uni.reLaunch({
    url: "/pages/lesson/index?catalog=1",
   });
},
```

```js
// b.vue
onLoad(option) {
  console.log("%c option", "color: red", option);
},
```

控制台打印的参数为空：

![image](https://user-images.githubusercontent.com/21032217/83738611-1b7a0a00-a687-11ea-961f-c37cf69a68f6.png)

我使用 [hello-uniapp](https://github.com/dcloudio/hello-uniapp)。里面的代码也是同样的效果。并没有传递过去参数：

![image](https://user-images.githubusercontent.com/21032217/83738908-790e5680-a687-11ea-92d4-4e42e011785b.png)

在首页打印出来的效果如下：

![bug](https://user-images.githubusercontent.com/21032217/83739123-c12d7900-a687-11ea-983c-789e7c475194.gif)

**Comment by fxy060608** [comment]
该问题已修复，可以使用最新的HBuilder Alpha版本验证下，或更新最新的cli

**Comment by AlvinMi** [comment]
> 该问题已修复，可以使用最新的 HBuilder Alpha 版本验证下，或更新最新的 cli

嗯嗯。更新后 HBuilder 可以收到。

我当前是 2.6.16。 
![image](https://user-images.githubusercontent.com/21032217/83828879-3fcff800-a714-11ea-80c8-a70896a393a4.png)
