### ISSUE TITLE
uni-app和小程序云开发

### ISSUE THREAD

**Issue by OnePieceJoker** [dcloudio/uni-app#176]
uni-app目前可以在微信小程序云开发中应用吗？

**Comment by ACChe** [comment]
uni-app是否支持微信小程序云开发？主要是云函数的文件夹模版。有没有？

**Comment by web-kubor** [comment]
有人解决了这个问题吗，我的设置都开了，但是打包文件都没有云函数的文件夹

**Comment by 502647092** [comment]
首先 云函数还是在微信小程序开发工具打包上传
然后在uni-app里面直接用wx.cloud就好了

**Comment by yaomo** [comment]
uni-app typescript  在APP.vue中，使用wx.cloud.init 报错，“cannot find name 'wx'"

**Comment by web-kubor** [comment]
小程序云开发的配置，在uni-app应该写在哪里

**Comment by web-kubor** [comment]
> 首先 云函数还是在微信小程序开发工具打包上传
> 然后在uni-app里面直接用wx.cloud就好了
> ![image](https://user-images.githubusercontent.com/10203793/57611671-f27f6680-75a5-11e9-9bb7-ef58021b373a.png)
> ![image](https://user-images.githubusercontent.com/10203793/57611695-fdd29200-75a5-11e9-83bb-3c96157b5b6f.png)

在微信开发工具里面上传，uni-app每次重新打包后dist内的相关文件都会清空一下，每次都重新上传吗

**Comment by ACChe** [comment]
对的，每次清空，应该有个脚本打包到dist后也把cloudFunction也拷贝过去吖 。。。

**Comment by 502647092** [comment]
我都是开两个微信IDE的。。。

**Comment by yaomo** [comment]
我是改了vue.config自己copy cloudfunction，但是其他的没法改了

**Comment by zhetengbiji** [comment]
> uni-app typescript 在APP.vue中，使用wx.cloud.init 报错，“cannot find name 'wx'"

安装微信小程序的 miniprogram-api-typings：```npm i miniprogram-api-typings -D```
tsconfig.json: 
```
"types": [
      "webpack-env",
      "@dcloudio/types/uni-app",
      "miniprogram-api-typings"
]
```

**Comment by zhetengbiji** [comment]
> > 首先 云函数还是在微信小程序开发工具打包上传
> > 然后在uni-app里面直接用wx.cloud就好了
> > ![image](https://user-images.githubusercontent.com/10203793/57611671-f27f6680-75a5-11e9-9bb7-ef58021b373a.png)
> > ![image](https://user-images.githubusercontent.com/10203793/57611695-fdd29200-75a5-11e9-83bb-3c96157b5b6f.png)
> 
> 在微信开发工具里面上传，uni-app每次重新打包后dist内的相关文件都会清空一下，每次都重新上传吗

配置 [vue.config](https://uniapp.dcloud.io/collocation/vue-config) 拷贝过去

**Comment by qhhsy** [comment]
需要修改两个地方`vue.config.js`和`manifest.json`
```js
 //  vue.config.js
{
  plugins: [
      new CopyWebpackPlugin([
        {
          from: path.join(__dirname, '../cloudfunctions'),
          to: path.join(__dirname, 'unpackage', 'dist', process.env.NODE_ENV === 'production' ? 'build' : 'dev', process.env.UNI_PLATFORM, 'cloudfunctions'),
        },
      ]),
    ],
}
```
```js
{
"mp-weixin" : {
        /* 微信小程序特有相关 */
        "appid" : "xxx",
        "setting" : {
            "urlCheck" : false,
            "es6" : true,
            "postcss" : true,
            "minified" : true
        },
        // 配置云开发目录，这样小程序工具 就能识别到
        "cloudfunctionRoot": "cloudfunctions/",
        "usingComponents" : true,
        "plugins" : {
            "wxparserPlugin" : {
                "version" : "0.2.1",
                "provider" : "xxx"
            }
        },
        "permission" : {
            "scope.userLocation" : {
                "desc" : "对对对"
            }
        }
    },}
```

**Comment by Yitengyu** [comment]
> miniprogram-api-typings

miniprogram-api-typings也声明了console之类的，会冲突，请教怎么解决

**Comment by Yitengyu** [comment]
> > uni-app typescript 在APP.vue中，使用wx.cloud.init 报错，“cannot find name 'wx'"
> 
> 安装微信小程序的 miniprogram-api-typings：`npm i miniprogram-api-typings -D`
> tsconfig.json:
> 
> ```
> "types": [
>       "webpack-env",
>       "@dcloudio/types/uni-app",
>       "miniprogram-api-typings"
> ]
> ```

miniprogram-api-typings也声明了console之类的，会冲突，请教怎么解决

**Comment by aetherwu** [comment]
> 需要修改两个地方`vue.config.js`和`manifest.json`
> ```

现在 IDE会提示： 

> 文件 functions/saveExtend/index.js 在 project.config.json 'cloudfunctionRoot' 指定的目录, 如果不希望在小程序/小游戏的运行环> 境中执行该文件，请使用 project.config.json "miniprogramRoot" 组织项目目录结构

能否求教这一步该怎么处理呢？我自己尝试了一些，比如直接把uniapp的项目文件打包扔到src里并且设置 Root，但都失败了。
