### ISSUE TITLE
真机调试的没有问题，但是用Hbuildx打包出现错误，提示当前应用运行在自定义调试基座中，发布正式版请打包不要勾选自定义调试基座

### ISSUE THREAD

**Issue by WJinhai** [dcloudio/uni-app#1761]
**问题描述**
真机调试的没有问题，但是用Hbuildx打包安卓apk时出现错误，提示当前应用运行在自定义调试基座中，发布正式版请打包不要勾选自定义调试基座
[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

- [ ] 

**系统信息:**
 - 发行平台:  App
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本   2.7.9
 - uni-app版本   uni-app V2.7.9
                           uni-app cliV2.0.0-27920200527001
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by dcloudhdx** [comment]
如果是发行APP，点击HBuilderX 菜单 -> 原生App云打包，不要勾选打包界面的单选框 "打自定义调试基座"
