### ISSUE TITLE
IOS正式包强制横屏不生效

### ISSUE THREAD

**Issue by qq1255198035** [dcloudio/uni-app#1762]
IOS正式包强制横屏不生效plus.screen.lockOrientation('landscape-primary');
本地真机测试生效

**Comment by dcloudhdx** [comment]
plus.screen.lockOrientation仅锁定屏幕方向

需要配置支持的屏幕方向 pages.json -> globalStyle -> "pageOrientation": "portrait"//横屏配置，全局屏幕旋转设置(仅 APP/微信/QQ小程序)，支持 auto / portrait / landscape

参考文档 https://uniapp.dcloud.net.cn/collocation/pages?id=globalstyle
