### ISSUE TITLE
支持pages.js 用js脚本返回pages

### ISSUE THREAD

**Issue by sanriqing** [dcloudio/uni-app#1764]
**新功能描述**
pages.json 兼容下pages.js ，使用node书写，应该对解析内容复杂度增加不大。

**现状及问题**
页面多了，比如我们的相册项目每个模版都是一个页面。。。注册页面的时候非常繁琐。。而且几千行的pages让人生畏，并且每次注释内容“，”老要删除和填补着实有些麻烦。

**尝试方案**
调用pages.js 生成，目前我们用脚本生成，和watch配合的感觉不是很好。。

**补充信息**
[其它你认为有参考价值的信息]

**Comment by hcl2020** [comment]
我看源代码是支持的 pages.js 的，文档里面没有提到

```
module.exports = function(pagesJson, loader) {
  return {
    pages: [  ...  ],
    globalStyle: {  ...  },
    tabBar: {  ...  }
  };
};
```

**Comment by sanriqing** [comment]
> 我看源代码是支持的 pages.js 的，文档里面没有提到
> 
> ```
> module.exports = function(pagesJson, loader) {
>   return {
>     pages: [  ...  ],
>     globalStyle: {  ...  },
>     tabBar: {  ...  }
>   };
> };
> ```

似乎没有？我看源代码是,这部分写死了，

```javascript
function getPagesJson () {
  return processPagesJson(getJson('pages.json', true))
}
```
