### ISSUE TITLE
webview 新窗口打开video页面，再从video页面返回导致 webview中的input 组件软键盘无法呼出

### ISSUE THREAD

**Issue by xiaomaokeke** [dcloudio/uni-app#1766]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
webview中有input 表单元素和 打开带有 video 组件的新页面(uni-page),从video 页面返回 webview 窗口时，webview中的input 元素聚焦无法呼出软键盘。
**复现步骤**
[复现问题的步骤]
1.  在 index 页面（使用了webview 组件，以下简称index页面）中，点击 uni-Video 组件播放器4 按钮,打开带有 video 组件的页面
![1-index-webview-pan](https://user-images.githubusercontent.com/64067386/83939786-388f1400-a812-11ea-8178-850f8a937b0d.jpg)

2. 从 video 页面，点击顶部返回按钮，返回到 index 页面
![2-open-video-page](https://user-images.githubusercontent.com/64067386/83939792-3f1d8b80-a812-11ea-9c44-e1739a7186dc.jpg)

3. 点击 index 页面 底部输入框，无法弹出软键盘
![3-index-webview-pan](https://user-images.githubusercontent.com/64067386/83939795-447ad600-a812-11ea-9d65-9085f0796a41.jpg)

**说明: 
1.在没有打开带有video组件页面时，index 页面的webview 中的网页表单元素 input聚焦是可以呼出软键盘
![4-default](https://user-images.githubusercontent.com/64067386/83939799-493f8a00-a812-11ea-8289-b6d0f984e66c.jpg)

2.我尝试给当前 webview 刷新页无法呼出软键盘**
[或者可以直接贴源代码]

**预期结果**
video 页面返回后，可以呼出软键盘
![4-default](https://user-images.githubusercontent.com/64067386/83939799-493f8a00-a812-11ea-8289-b6d0f984e66c.jpg)

**实际结果**
[这里请贴上你的报错截图或文字]
![3-index-webview-pan](https://user-images.githubusercontent.com/64067386/83939795-447ad600-a812-11ea-9d65-9085f0796a41.jpg)

**系统信息:**
 - 发行平台: uniApp
 - 操作系统 Android 7.0 NRD90M  / Android 10 / Android 7.1.1
 - HBuilderX版本 2.7.9.20200527
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]
   小米Max2 \ 华为 Mate 30 Pro 5G \ Redmi Note 4

**补充信息**
[可选]
1.video 页面的层级问题

**Comment by xiaomaokeke** [comment]
示例代码:https://github.com/xiaomaokeke/uniapp-webview

**Comment by Fasttian** [comment]
没有复现这个问题，你还有这个问题吗？

**Comment by rexydimen** [comment]
所以这个问题解决了吗？
