### ISSUE TITLE
字体大小无法被修改

### ISSUE THREAD

**Issue by VICTORYGS** [dcloudio/uni-app#177]
![image](https://user-images.githubusercontent.com/33747619/51723552-86c7cb00-2094-11e9-9028-336ec984baf0.png)
![image](https://user-images.githubusercontent.com/33747619/51723617-be367780-2094-11e9-8b4b-eb5b24822277.png)

在main.js中引入一个全局的样式  然后在某个具体页面中的元素重新定义字体大小时,会发现无法被更改; 但是某些元素却又能修改, 当把全局样式的scss注释之后. 才能被修改成功.

**Comment by xiaoyucoding** [comment]
不支持 * 选择器

**Comment by VICTORYGS** [comment]
*可以生效好不好   不信自己试试
