### ISSUE TITLE
picker组件无法选择

### ISSUE THREAD

**Issue by HVE-LK** [dcloudio/uni-app#1774]
环境：编译器V3，hbuilderX2.7.9，真机调试机型：三星s8。
当picker组件的mode = selector时，确认选中时change事件不会触发。
当picker组件的mode = date时，第一次进入页面组件正常，返回上一页再次进入确认选中时change事件不会触发。
其他mode模式未测试。

**Comment by zhetengbiji** [comment]
只有这个机型复现吗？
测试未复现，有没有更详细的工程配置和操作步骤？

**Comment by HVE-LK** [comment]
对的，我是把hbuilderX 升级过后才出现这个问题的，如果方便的话我可以录屏或者给你这边演示。您这边留个电话或者微信，电话：13064321889，微信号：HVE-LK



在 2020-06-17 14:37:12，"折腾笔记" <notifications@github.com> 写道：

只有这个机型复现吗？
测试未复现，有没有更详细的工程配置和操作步骤？

**Comment by HVE-LK** [comment]
稍后换其它手机测试看看是否会出现相同的问题。

**Comment by zhetengbiji** [comment]
> 对的，使用的是自定义基座，我是把hbuilderX 升级过后才出现这个问题的，之前是正常的，因为我这边前端项目比较复杂，如果可以的话这边录屏给您这边看下，现在项目卡在这里了。 在 2020-06-17 14:37:12，"折腾笔记" <notifications@github.com> 写道： 只有这个机型复现吗？ 测试未复现，有没有更详细的工程配置和操作步骤？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

升级后，有重新打包自定义基座吗？

**Comment by HVE-LK** [comment]
{
"name" : "app",
"appid" : "******************",
"description" : "**********",
"versionName" : "v1.1.5",
"versionCode" : 10007,
"transformPx" : false,
"app-plus" : {
"usingComponents" : true,
"nvueCompiler" : "weex",
"compilerVersion" : 3,
/* 5+App特有相关 */// "runmode" : "liberate",
"modules" : {
"Push" : {},
"Statistic" : {},
"Maps" : {}
},
/* 模块配置 */
"distribute" : {
/* 应用发布信息 */
"android" : {
/* android打包配置 */
"permissions" : [
"<uses-feature android:name=\"android.hardware.camera\"/>",
"<uses-feature android:name=\"android.hardware.camera.autofocus\"/>",
"<uses-permission android:name=\"android.permission.ACCESS_COARSE_LOCATION\"/>",
"<uses-permission android:name=\"android.permission.ACCESS_FINE_LOCATION\"/>",
"<uses-permission android:name=\"android.permission.ACCESS_NETWORK_STATE\"/>",
"<uses-permission android:name=\"android.permission.ACCESS_WIFI_STATE\"/>",
"<uses-permission android:name=\"android.permission.CALL_PHONE\"/>",
"<uses-permission android:name=\"android.permission.CAMERA\"/>",
"<uses-permission android:name=\"android.permission.CHANGE_NETWORK_STATE\"/>",
"<uses-permission android:name=\"android.permission.CHANGE_WIFI_STATE\"/>",
"<uses-permission android:name=\"android.permission.FLASHLIGHT\"/>",
"<uses-permission android:name=\"android.permission.INTERNET\"/>",
"<uses-permission android:name=\"android.permission.MODIFY_AUDIO_SETTINGS\"/>",
"<uses-permission android:name=\"android.permission.MOUNT_UNMOUNT_FILESYSTEMS\"/>",
"<uses-permission android:name=\"android.permission.READ_LOGS\"/>",
"<uses-permission android:name=\"android.permission.READ_PHONE_STATE\"/>",
"<uses-permission android:name=\"android.permission.RECEIVE_BOOT_COMPLETED\"/>",
"<uses-permission android:name=\"android.permission.SYSTEM_ALERT_WINDOW\"/>",
"<uses-permission android:name=\"android.permission.VIBRATE\"/>",
"<uses-permission android:name=\"android.permission.WAKE_LOCK\"/>",
"<uses-permission android:name=\"android.permission.WRITE_CONTACTS\"/>",
"<uses-permission android:name=\"android.permission.WRITE_EXTERNAL_STORAGE\"/>",
"<uses-permission android:name=\"android.permission.WRITE_SETTINGS\"/>",
"<uses-permission android:name=\"android.permission.RECEIVE_USER_PRESENT\"/>"
],
"targetSdkVersion" : 28,
"minSdkVersion" : 19,
"abiFilters" : [ "armeabi-v7a", "arm64-v8a" ]
},
"ios" : {},
/* ios打包配置 */
"sdkConfigs" : {
"push" : {
"unipush" : {}
},
"maps" : {
"amap" : {
"appkey_ios" : "**********************",
"appkey_android" : "**********************"
}
},
"oauth" : {},
"statics" : {},
"payment" : {},
"ad" : {}
},
"icons" : {
"android" : {
"ldpi" : "unpackage/res/icons/48x48.png",
"xxxhdpi" : "unpackage/res/icons/192x192.png",
"xxhdpi" : "unpackage/res/icons/144x144.png",
"xhdpi" : "unpackage/res/icons/96x96.png",
"hdpi" : "unpackage/res/icons/72x72.png",
"mdpi" : "unpackage/res/icons/48x48.png"
},
"ios" : {
"appstore" : "unpackage/res/icons/1024x1024.png",
"ipad" : {
"app" : "unpackage/res/icons/76x76.png",
"app@2x" : "unpackage/res/icons/152x152.png",
"notification" : "unpackage/res/icons/20x20.png",
"notification@2x" : "unpackage/res/icons/40x40.png",
"proapp@2x" : "unpackage/res/icons/167x167.png",
"settings" : "unpackage/res/icons/29x29.png",
"settings@2x" : "unpackage/res/icons/58x58.png",
"spotlight" : "unpackage/res/icons/40x40.png",
"spotlight@2x" : "unpackage/res/icons/80x80.png"
},
"iphone" : {
"app@2x" : "unpackage/res/icons/120x120.png",
"app@3x" : "unpackage/res/icons/180x180.png",
"notification@2x" : "unpackage/res/icons/40x40.png",
"notification@3x" : "unpackage/res/icons/60x60.png",
"settings@2x" : "unpackage/res/icons/58x58.png",
"settings@3x" : "unpackage/res/icons/87x87.png",
"spotlight@2x" : "unpackage/res/icons/80x80.png",
"spotlight@3x" : "unpackage/res/icons/120x120.png"
}
}
}
},
"splashscreen" : {
"waiting" : false,
"alwaysShowBeforeRender" : false,
"delay" : 0,
"autoclose" : false
},
"softinput" : {
"navBar" : "auto",
"auxiliary" : true,
"mode" : "adjustPan"
}
},
/* SDK配置 */
"quickapp" : {},
/* 快应用特有相关 */
"mp-weixin" : {
/* 小程序特有相关 */
"usingComponents" : true, //是否启用`自定义组件模式`，为true表示新的`自定义组件模式`，否则为`template模板模式`
"appid" : "****************",
"setting" : {
"urlCheck" : true,
"es6" : true,
"postcss" : true,
"minified" : true
},
"permission" : {
"scope.userLocation" : {
"desc" : "你的位置将用于记录签到签退地点"
}
}
},
"mp-toutiao" : {
"setting" : {
"es6" : false
}
},
"networkTimeout" : {
//请求超时
"request" : 5000
},
"h5" : {
"optimization" : {
"treeShaking" : {
"enable" : true
}
},
"router" : {
"mode" : "hash"
}
}
}
以上是我项目中的manifest.json配置内容

01:15:15.751 编译器版本：2.7.9（v3）详见：https://ask.dcloud.net.cn/article/36599。
01:15:15.751 请注意运行模式下，因日志输出、sourcemap以及未压缩源码等原因，性能和包体积，均不及发行模式。
01:15:15.751 正在编译中...
01:15:24.639 nvue中不支持如下css。如全局或公共样式受影响，建议将告警样式写在ifndef APP-PLUS-NVUE的条件编译中，详情如下：
01:15:24.639 WARNING: `placeholder-color` is not a standard property name (may not be supported) at pages/login/login.nvue:197
01:15:24.654 WARNING: `placeholder-color` is not a standard property name (may not be supported) at pages/login/login.nvue:208
01:15:59.363 DONE Build complete. Watching for changes...
01:15:59.363 项目 'shefeiAPP' 编译成功。
01:15:59.801 正在建立手机连接...
01:16:01.051 手机端调试基座版本号为v1.1.5，版本号相同，跳过基座更新
01:16:01.301 正在同步手机端程序文件...
01:16:06.864 同步手机端程序文件完成
01:16:07.020 正在启动自定义基座...

以上是安装编译过程

<picker class='rui-picker rui-class' fields="month" start="2015-11" :end="endMonth" mode="date" :value="indexMonth" @change='monthChange'>
<view class="row-name">
<view class="picker">{{indexMonth}}</view>
<view class="tit iconfont iconarrow_right"></view>
</view>
</picker>
这个组件的使用

操作我已经录屏了，如果需要的话我可以提供录屏。



在 2020-06-17 15:59:37，"折腾笔记" <notifications@github.com> 写道：

对的，使用的是自定义基座，我是把hbuilderX 升级过后才出现这个问题的，之前是正常的，因为我这边前端项目比较复杂，如果可以的话这边录屏给您这边看下，现在项目卡在这里了。 在 2020-06-17 14:37:12，"折腾笔记" notifications@github.com 写道： 只有这个机型复现吗？ 测试未复现，有没有更详细的工程配置和操作步骤？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

升级后，有重新打包自定义基座吗？

**Comment by zhetengbiji** [comment]
新建一个工程，复制这部分代码，使用其他手机在默认基座测试可以复现之前的问题吗？
