### ISSUE TITLE
微信小程序环境下，vue具名插槽slot内的自定义组件上的class样式丢失

### ISSUE THREAD

**Issue by social-uni** [dcloudio/uni-app#1775]
v3模式，注意，必须为具名插槽才存在此问题，非具名插槽不存在此问题

q-tab标签为自定义组件，上面添加的样式类并没有显示出来

q-tab组件上是有一个q-tab样式类的，但是插入插槽后，样式类丢失

圈中的两个tab分别在插槽外和具名插槽内，可见插槽外的q-tab是有样式类的，可具名插槽内的q-tab样式类丢失

![image](https://user-images.githubusercontent.com/14007972/84112373-353a9900-aa5b-11ea-8906-b91006951383.png)

代码：
![image](https://user-images.githubusercontent.com/14007972/84111875-55b62380-aa5a-11ea-91ac-04ab597fa114.png)

![image](https://user-images.githubusercontent.com/14007972/84112060-a3cb2700-aa5a-11ea-9200-ce8affa56a55.png)

下图为h5环境下正常

![image](https://user-images.githubusercontent.com/14007972/84112398-41265b00-aa5b-11ea-8a10-8bd576788f3b.png)

**Comment by qinkaiyuan** [comment]
可能为这个原因

easycom下不行，手动引入可以

![image](https://user-images.githubusercontent.com/14007972/84113809-d9254400-aa5d-11ea-848e-d6837c00d6eb.png)

**Comment by zhetengbiji** [comment]
#1729
