### ISSUE TITLE
nvue页面同级存在重名的文件夹会导致页面无内容

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#1776]
nvue页面，iOS app，页面名字如果与同级的文件夹重名，可能导致该页面无内容。

比如：`test.nvue` 同级下还存在 `test` 文件夹

**Comment by Wangyaqi** [comment]
没能复现此问题，建议补充更多信息，HBuilderX版本、手机系统版本等，最好能有一个可以复现问题的demo

**Comment by wakaryry** [comment]
那算了。我把文件名字改了就好了。

**Comment by wakaryry** [comment]
- hbx 2.7.9；
- nvue页面；
- iOS 模拟器 iPhone 11 Pro Max 13.5；
- 同级目录下存在同名文件夹和nvue页面；

没有复现就算了。我搞了一上午都是页面无内容，改名字之后就出来了内容。
