### ISSUE TITLE
shopro商城

### ISSUE THREAD

**Issue by ITmonkey-cn** [dcloudio/uni-app#1778]
gitee地址：https://gitee.com/Ssshandingdongren/shopro.git

# Shopro商城简介

shopro商城，一款基于uni-app的前端模板商城。目前适配了（小程序+app+h5+公众号）。主要功能： 登录 注册 签到 富文本 分类 购物车 筛选 地址 商品评论 积分商城 拼团 秒杀 多规格 全端分享 路由拦截 分享海报 多支付方式 订单管理 用户信息等等。

# Shopro演示站

|![微信小程序码](https://images.gitee.com/uploads/images/2020/0609/161525_364852cc_2264724.jpeg "微信小程序码") |![H5二维码](https://images.gitee.com/uploads/images/2020/0609/161626_43f86922_2264724.png "H5二维码") | 
| ------------ | ------------ | 
|  微信小程序 |H5二维码  |

**Comment by Wangyaqi** [comment]
https://github.com/dcloudio/uni-app/issues/6
