### ISSUE TITLE
live-pusher组件statechange的code状态码能不能把文档补全？

### ISSUE THREAD

**Issue by bigBron** [dcloudio/uni-app#1779]
- ios，android在RTMP服务器主动断开情况下返回code也是不一致：android能返回3004，3005状态码，ios不能。
- 实测ios很多code都没有在文档中（1010，1011，1014，1016）。
- 文档里写uni.createLivePusherContext(livePusherId, this).start(callback)中"success" 表示成功，是具体代表什么状态成功？底层协议握手阶段成功？还是数据推流成功？
- 现有API官方推荐那个能正确判断推流成功，跟断播情况的？
- error事件具体返回值文档描述也很模糊，只能靠猜。

uni,hbuilder版本为最新版本
https://uniapp.dcloud.io/component/live-pusher
http://www.html5plus.org/doc/zh_cn/video.html#plus.video.LivePusherEvents

**Comment by chen4444729** [comment]
nvue页面中，iOS的推流组件底层和安卓的是不一样的，所以有的code不是都有。在nvue中安卓的可以参考腾讯推流组件的code码，iOS的和vue页面中的推流组件一致，参考vue的推流组件的code码。vue中的安卓推流组件和iOS一致。

**Comment by dcloudhdx** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
