### ISSUE TITLE
建议新增在pages.json/pages列表中，对每个页面传入参数的属性

### ISSUE THREAD

**Issue by hejun200613224** [dcloudio/uni-app#1785]
**新功能描述**
建议新增在pages.json/pages列表中，对每个页面传入参数的属性，类似vue-router于配置router时直接写入在配置里的、在调用时传入组件的props

**现状及问题**
目前无法对pages调用的vue组件传入参数，只能在navigateTo的时候可以传入参数。导致目前的方法如果需要重复引用同一个vue文件作为页面文件存在困难。类似的可复用pages页面在目前的情况下，需要重复创建多个vue文件并设置多个pages对象一一对应

**尝试方案**
建议参考navigateTo时传入参数的实现方式，实现pages预定义path的参数传入。可以将两处传参进行合并，以navigateTo优先级为高。
或者可以直接参考vue-router实现方式，直接在页面vue组件的props进行接受。

**补充信息**
在既有mobile web项目迁移过程中，由于无法一次性迁移，部分页面需要通过webview引用原html，此时在当前模式下，有2种方式：
1.定义多个webview引用组件，并分别指向原html文件，同时在pages.json一一对应定义路径。
2.定义一个webview引用组件，pages.json设置一项，但是在navigateTo跳转时传入链接。
其弊端为：
1方式需要大量的重复vue文件定义和pages定义
2方式所需传入的参数，在navigateTo配置，而navigateTo往往位于代码深处，不利于后期的继续迁移过程中的修改。
所提新需求可以避免目前2种方式的弊端。

**Comment by fxy060608** [comment]
建议使用方式2，旧项目迁移，肯定要修改navigateTo相关代码逻辑，可以自己封装跳转
方式1的话，你可以考虑做一个自动化生成代码的工具
pages.json中配置参数，意义不大，且无法跨平台支持
