### ISSUE TITLE
uniapp中v-show的问题

### ISSUE THREAD

**Issue by thecoolbb** [dcloudio/uni-app#1787]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
```
<template>
    <view class="uni-container">
		<button @click="arrayInit">array添加项</button>
		<button @click="arrayEmpty">array变为空数组</button>
		<view>array.length > 0 的值 {{ array.length > 0 }}</view>
		<view v-show="array.length > 0">v-show中array.length大于0展示</view>
		<view v-if="array.length > 0">v-if中array.length大于0展示</view>
    </view>
</template>
<script>
    export default {
		data() {
			return{
				array: [],
				isShow: false
			}
		},
		methods: {
			arrayInit() {
				this.array = [1,2,3,4];
			},
			arrayEmpty() {
				this.array = [];
			}
		},
    }
</script>
```
点击"array添加项"按钮，会为array赋值为[1,2,3,4]

**预期结果**
“v-show中array.length大于0展示”内容展示出来
“v-if中array.length大于0展示”内容展示出来

**实际结果**
“v-show中array.length大于0展示”内容没有展示出来
“v-if中array.length大于0展示”内容展示出来

![image](https://user-images.githubusercontent.com/40915232/84387773-1b997d00-ac26-11ea-8ffd-740eae35bd40.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 微信开发者工具中的模拟器
 - HBuilderX版本 2.7.9.20200527
 - uni-app版本 2.0.0-27920200527001
 - 设备信息 iPhone XR

**补充信息**
v-show中的array.length > 0类似这种判断可能没触发dom更新，进行依赖收集时没收集到

**Comment by fxy060608** [comment]
微信Bug
https://developers.weixin.qq.com/community/develop/doc/000c8ee47d87a0d5b6685a8cb57000
可以换成computed测试

**Comment by thecoolbb** [comment]
uniapp中使用this.array = [1,2,3,4];按道理来说是全量更新吧，这在具体实现中是差量更新吗？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"fxy060608"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 上午9:41
收件人:&nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&gt;;
抄送:&nbsp;"daifayang"<498108281@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] uniapp中v-show的问题 (#1787)





 
微信Bug
 https://developers.weixin.qq.com/community/develop/doc/000c8ee47d87a0d5b6685a8cb57000
 可以换成computed测试

**Comment by fxy060608** [comment]
> uniapp中使用this.array = [1,2,3,4];按道理来说是全量更新吧，这在具体实现中是差量更新吗？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"fxy060608"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月12日(星期五) 上午9:41 收件人:&nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 抄送:&nbsp;"daifayang"<498108281@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [dcloudio/uni-app] uniapp中v-show的问题 (#1787) 微信Bug https://developers.weixin.qq.com/community/develop/doc/000c8ee47d87a0d5b6685a8cb57000 可以换成computed测试 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

底层都是差量更新
