### ISSUE TITLE
chooseLocation 返回和确定第一次点击没有反应

### ISSUE THREAD

**Issue by zlab** [dcloudio/uni-app#1789]
**问题描述**
如题

**复现步骤**
[复现问题的步骤]
1.  微信扫码官网H5 demo二维码
2. 接口，使用地图选择位置
3. 选择位置，随便选个位置，☑️（右上角打勾，能否改成确定？），首次没问题
4. 再次选择位置，随便选个位置，点返回或☑️，第一次没有反应
5. 可以重复几次，都是需要点两次才能返回和☑️

[或者可以直接贴源代码]
https://uniapp.dcloud.io/h5/pcguide.html#/h5/

![image](https://user-images.githubusercontent.com/2288630/84461640-8a66ec80-ac9f-11ea-84ae-24ab6887473a.png)

**Comment by zhetengbiji** [comment]
iOS 还是 安卓？

**Comment by zlab** [comment]
ios 10.3.3

**Comment by zlab** [comment]
@zhetengbiji 还没发布吗，2.7.14还是有问题
