### ISSUE TITLE
首页所有的生命周期会执行两次

### ISSUE THREAD

**Issue by jddk** [dcloudio/uni-app#1790]
- 版本：HBuilder X 2.7.9
- 现象：首页的所有生命周期都会执行两次
```javascript
onLoad(){
			console.log('onLoad',new Date().getTime())
		},
		onShow(){
			console.log('onShow',new Date().getTime())
		},
		onReady(){
			console.log('onReady',new Date().getTime())
		}
```
打印后
```
index.vue:11 onLoad 1591945157570
index.vue:14 onShow 1591945157571
index.vue:17 onReady 1591945157573
index.vue:11 onLoad 1591945157576
index.vue:14 onShow 1591945157576
index.vue:17 onReady 1591945157577
```

**Comment by Wangyaqi** [comment]
你这是看的哪里的运行日志？

**Comment by jddk** [comment]
> 你这是运行在了哪端？看的哪里的运行日志？

app和H5都会执行两次生命周期，这个是我在chrome控制台打印出来的

**Comment by Wangyaqi** [comment]
发一下你的项目给我里面带上unpackage目录

**Comment by jddk** [comment]
你好：
&nbsp; &nbsp;我尽可能的删除掉了多余的代码，直接在H5可以复现出来，




我同事的电脑，HBuilX是2.6 版本的不会出现加载两次的问题，前面两天实在是有点懒不想动，今天才把问题反馈过来，抱歉了 ：&gt;


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"王亚琪"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月12日(星期五) 下午5:35
收件人:&nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&gt;;
抄送:&nbsp;"陈世亮"<352056038@QQ.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] 首页所有的生命周期会执行两次 (#1790)





 
发一下你的项目给我里面带上unpackage目录

**Comment by Wangyaqi** [comment]
意思是空项目都能复现这个问题吗？uni-app默认模版这种？

**Comment by jddk** [comment]
> 意思是空项目运行到chrome都能复现这个问题吗？uni-app默认模版这种？

空项目复现不出来的，我在邮件里面有写详细的复现步骤截图和代码，没有收到？

**Comment by jddk** [comment]
> 意思是空项目运行到chrome都能复现这个问题吗？uni-app默认模版这种？

复现出来了吗？

**Comment by hbcui1984** [comment]
> > 意思是空项目运行到chrome都能复现这个问题吗？uni-app默认模版这种？
> 
> 空项目复现不出来的，我在邮件里面有写详细的复现步骤截图和代码，没有收到？

你是在github的自动通知邮件中回复的吧？那个肯定收不到的，没看邮件地址是noreply.github.com

**Comment by Wangyaqi** [comment]
> > 意思是空项目运行到chrome都能复现这个问题吗？uni-app默认模版这种？
> 
> 复现出来了吗？

可以直接发在这个issue里，邮件没有看到

**Comment by jddk** [comment]
> ？
我把可以复现的代码传到GitHub上面了，https://github.com/jddk/uni-appbug  ，里面的README.md写了复现的步骤

**Comment by jddk** [comment]
> > > 意思是空项目运行到chrome都能复现这个问题吗？uni-app默认模版这种？
> > 
> > 
> > 复现出来了吗？
> 
> 可以直接发在这个issue里，邮件没有看到

**Comment by wanxchao** [comment]
该问题还是存在

**Comment by zhetengbiji** [comment]
> 该问题还是存在

具体说明
