### ISSUE TITLE
华为p30曲面屏，navigateTo跳转失效

### ISSUE THREAD

**Issue by qiaolele** [dcloudio/uni-app#1791]
偶发性问题，无论是自定义组件还是正常的组件，偶尔在华为P30曲面屏添加@click事件进行navigateTo跳转失效的问题

**Comment by proactivefly** [comment]
> 偶发性问题，无论是自定义组件还是正常的组件，偶尔在华为P30曲面屏添加@click事件进行navigateTo跳转失效的问题

应该是你的页面爆栈了吧

**Comment by mehaotian** [comment]
有无明显报错 ，除了跳转事件 ，其他事件有影响么 ？

**Comment by hbcui1984** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
