### ISSUE TITLE
h5打包支持下微信小程序scroll-view的自定义下拉刷新功能。

### ISSUE THREAD

**Issue by LastHeaven** [dcloudio/uni-app#1792]
**新功能描述**
简洁描述你希望补充完善的增强功能
微信小程序基础库2.10.1以上版本支持scroll-view的自定义下拉刷新功能了。希望uniapp在打包成h5的时候能够支持scroll-view的下拉刷新功能。

**现状及问题**
[当前现状及由此导致的不便]
现在打包成h5版本是不支持微信小程序scroll-view的下拉刷新功能的。导致要实现自定义下拉刷新得在小程序和h5之间写两套代码。

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by dcloudhdx** [comment]
H5已支持，参考文档 https://uniapp.dcloud.net.cn/component/scroll-view
