### ISSUE TITLE
安卓调试页面高度有问题，导致下方出现空白区域

### ISSUE THREAD

**Issue by tianzhu1992** [dcloudio/uni-app#1795]
机型：小米8  MIUI11
手机端调试基座版本号为2.7.9
安卓调试时，在刚启动时页面高度没有问题，修改代码后自动更新后，页面出现空白现象。
![image](https://user-images.githubusercontent.com/31034218/84598082-b13d4280-ae9a-11ea-91ac-e5644b5d0a3a.png)

![image](https://user-images.githubusercontent.com/31034218/84598005-412ebc80-ae9a-11ea-8156-7a8321a74d1a.png)
![image](https://user-images.githubusercontent.com/31034218/84598026-573c7d00-ae9a-11ea-907b-f6f6b85055e8.png)

**Comment by Wangyaqi** [comment]
用最新的alpha版本试试看看还有没有这个问题

**Comment by runryan** [comment]
重新运行项目
