### ISSUE TITLE
小程序对象中设置key带 . 会引发setData内部处理报错

### ISSUE THREAD

**Issue by sanriqing** [dcloudio/uni-app#1798]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
小程序对象中设置key带 . 会引发setData内部处理报错

**复现步骤**
[复现问题的步骤]
```
<script>
export default {
    data(){
        return {
            cache:{}
        }
    },
    mounted(){
        this.cache['xxx.xxx.xx']=1
    }
}
</script>
```
这个就会报xxx不能从null读取

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
正常不报错

**实际结果**
[这里请贴上你的报错截图或文字]
这个就会报xxx不能从null读取

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

小程序本身应该就有这个问题。预计挺麻烦处理的。。仅提醒按文件地址缓存数据的同学报错原因

**Comment by fxy060608** [comment]
建议调整格式，xxx.xxx.xxx格式的数据，在小程序平台会认为是差量数据，

**Comment by sanriqing** [comment]
> 建议调整格式，xxx.xxx.xxx格式的数据，在小程序平台会认为是差量数据，

已调整，只是报错的时候莫名其妙。所以顺带发个issue提示下，要是能给个更好的解决方案就更好了
