### ISSUE TITLE
reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Exception: TypeError: undefined is not an object (evaluating 'navigator.appName')

### ISSUE THREAD

**Issue by AdminQQZ** [dcloudio/uni-app#1799]
**问题描述**
Android打包或者运行，出现这个，页面出现空白
reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Exception: TypeError: undefined is not an object (evaluating 'navigator.appName')

**复现步骤**
[复现问题的步骤]
需要源码联系我

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by AdminQQZ** [comment]
![QQ截图20200615184747](https://user-images.githubusercontent.com/12959954/84722071-cc03da00-afb4-11ea-8dd4-77fd30c34903.jpg)

**Comment by zhetengbiji** [comment]
App 端不支持 navigator 对像

**Comment by Lysander686** [comment]
我这里也老是出现这个问题,
