### ISSUE TITLE
关于更新大量数据，会导致页面卡顿，数据无法及时渲染的问题

### ISSUE THREAD

**Issue by zxzhgk** [dcloudio/uni-app#18]
由于uni-app 转换小程序是借鉴mpvue 的思路，那么mpvue的这个问题 https://github.com/Meituan-Dianping/mpvue/issues/639 导致的大量数据更新的脏检查优化是怎么处理的，等待mpvue 的下一个版本修复，还是已经对这个问题进行了优化

**Comment by q310550690** [comment]
mpvue 目前问题还很多的，最让人头疼的就是组件 slot 套 子组件，子组件数据无法渲染到页面上，很是蛋疼，也不知道作者什么时候修复。

**Comment by zxzhgk** [comment]
官方估计没时间来查看这个问题了~

**Comment by cgx452306705** [comment]
很像知道有没有办法解决这个问题

**Comment by zxzhgk** [comment]
官方好像已经对底层进行了优化，看文章说是在测试中了

**Comment by xiaoyucoding** [comment]
微信小程序端做了大幅优化，详见：[uni-app 1.8发布，微信端性能翻倍，并增加若干 Vue 语法支持](https://ask.dcloud.net.cn/article/35699)
