### ISSUE TITLE
app样式错乱

### ISSUE THREAD

**Issue by htx1993** [dcloudio/uni-app#1801]
**问题描述**
app启动或切换页面之前，将程序切换到后台（手机home键），然后再打开程序，页面样式错乱，具体表现，高度或宽度塌陷

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/26754673/84739655-98d64080-afde-11ea-90a4-8ff5b233c218.png)
![Screenshot_20200616-143454](https://user-images.githubusercontent.com/26754673/84739721-c02d0d80-afde-11ea-92ba-527727c804e4.jpg)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Wangyaqi** [comment]
测试未能复现可以提供一下demo和如何操作的视频，另外请补充一下HBuilderX版本

**Comment by hbcui1984** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
