### ISSUE TITLE
为什么build完的项目总会有一个你们公司cdn的图片请求呢？

### ISSUE THREAD

**Issue by namet117** [dcloudio/uni-app#1803]
**问题描述**
使用uni-app开发的项目，在build之后，总会有一个`https://cdn.dcloud.net.cn/img/shadow-grey.png` 图片请求，我觉得对我来说没有任何实际作用，请问下怎么给去掉？

**复现步骤**
项目执行build之后，访问就会发现一个 这样的图片请求

**预期结果**
不想要这个图片，希望指导下怎么移除。

**实际结果**
图片一直在，文档也没有解决办法

**系统信息:**
 - 发行平台: H5、微信小程序
 - 操作系统: ALL
 - uni-app版本 uni-app v2.6.11 uni-app cli v2.0.0-26920200409002
 - 设备信息 全部

**Comment by google404** [comment]
统计用的吧，是不是开了统计

**Comment by hbcui1984** [comment]
这个是为了实现导航栏底部阴影效果，如果项目不需要，可以自己在编译后代码中手动删除。

**Comment by namet117** [comment]
@hbcui1984  大佬，请问下这里的实现可否改为使用base64的图片？或者是有什么必要的理由要使用外链图片么？我觉得目前这种实现方式有点很难以理解～ T_T

**Comment by wanganxp** [comment]
> @hbcui1984 大佬，请问下这里的实现可否改为使用base64的图片？或者是有什么必要的理由要使用外链图片么？我觉得目前这种实现方式有点很难以理解～ T_T

多看论坛，比github资料多：https://ask.dcloud.net.cn/question/87293

**Comment by zoollcar** [comment]
有意思的是最近 https://cdn.dcloud.net.cn/img/shadow-grey.png 这个链接还访问不了了，我这日志里记录了好多报错。如果不是访问不了报错，我估计都发现不了。

分享用 pwshell 脚本批量替换 `.\dist\build\h5` 路径下的内容，可以用在部署脚本里

```powershell
$regex = '\s*background(-image)?:\s*url\(\S*?\/\/[\w\.-]*?dcloud.net.cn\S*?\);?[ \t]*'
# 递归遍历文件夹中的所有文件
Get-ChildItem -Path .\dist\build\h5 -Recurse -Include "*.css" | ForEach-Object {
    $content = Get-Content $_.FullName -Raw
    # 替换内容
    $newContent = $content -replace $regex, " "
    # 如果内容发生变化，则写入文件
    if ($content -ne $newContent) {
        Set-Content $_.FullName -Value $newContent -Encoding UTF8
        Write-Host "已替换文件：$($_.FullName)"
    }
}
Write-Host "替换完成！"
```
