### ISSUE TITLE
list 数据问题

### ISSUE THREAD

**Issue by doubleLife-666** [dcloudio/uni-app#1805]
list = that.dataList;
list = otherList;
改变list的数据，dataList也跟着改变
怎么才能让dataList不改变。
萌新求罩

**Comment by martSforever** [comment]
list = [...(that.dataList||[])]

**Comment by martSforever** [comment]
最好是深度复制data数组对象

**Comment by doubleLife-666** [comment]
> 最好是深度复制data数组对象

感谢提供思路

**Comment by heymalio** [comment]
用JSON.parse(JSON.stringify(list)); 

可以解决
