### ISSUE TITLE
typescript开发小程序，使用条件编译时报错

### ISSUE THREAD

**Issue by mirror29** [dcloudio/uni-app#1809]
**问题描述**
typescript开发小程序，使用条件编译时报错

**复现步骤**
```
//util.ts
reportAnalytics(ev: string) {
    // #ifdef MP-BAIDU
    swan.reportAnalytics(ev)
    // #endif
  }
```
创建uni-app项目，运行上面TS代码，即可发现报错，使用Hbuilder X和yarn 创建项目报错不太一致，Hbuilder可以识别条件编译但无法识别百度小程序的swan关键词，yarn 创建的项目两者均无法识别

**预期结果**
希望能正常编译，否则无法使用发行模式对项目的性能会造成很大影响

**实际结果**
报错信息
87:5 Cannot find name 'swan'.
  ```
  85 |   reportAnalytics(ev: string) {
    86 |     // #ifdef MP-BAIDU
  > 87 |     swan.reportAnalytics(ev)
           |     ^
    88 |     // #endif
    89 |   }
    90 | }
```

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
目前百度官方未提供相关API对应的d.ts。可以通过配置跳过对应的检测，也可以自己安装第三方写的d.ts，或者自己写一下用到的API，如果懒得搞，简易也可声明一下：declare const swan: any。

**Comment by mirror29** [comment]
十分感谢！
