### ISSUE TITLE
项目要实现多语言支持，tabbar只能在h5,小程序上实现多语言修改，app上不行

### ISSUE THREAD

**Issue by lzf1201** [dcloudio/uni-app#181]
uni.setTabBarItem这个方法不支持 安卓app，我是在云上打包的。具说这个问题在新版上可以用了，但在云上打包还不支持。

**Comment by zhetengbiji** [comment]
> uni.setTabBarItem这个方法不支持 安卓app，我是在云上打包的。具说这个问题在新版上可以用了，但在云上打包还不支持。

是使用新版HBuilderX打包的吗？使用此API报什么错？

**Comment by lzf1201** [comment]
我是2019.1.21日的版本，我试试有没有最新版本

**Comment by lzf1201** [comment]
没有任何报错信息，没试过本地打包，是云上打包的代码

**Comment by zhetengbiji** [comment]
之前的版本在app端无图标参数应该会报错，下版本可解决。

**Comment by lzf1201** [comment]
我不是图标参数的问题，是text修改的问题，这个问题是不是下个版本能解决？

**Comment by zhetengbiji** [comment]
> 我不是图标参数的问题，是text修改的问题，这个问题是不是下个版本能解决？

之前的版本app端未设置图标会报错，你设置上图标就好了。

**Comment by zhetengbiji** [comment]
> 没有任何报错信息，没试过本地打包，是云上打包的代码

真机运行可以看见错误

**Comment by zhetengbiji** [comment]
> tabbar的text文字修改后能直接响应就行了，下个版本能处理吗？

下个版本修复，图标改为非必填。

**Comment by lzf1201** [comment]
是应为没有图标，所以单文字会无法修改，如果有图标文字的修改也会跟进对吗？？

**Comment by lzf1201** [comment]
![image](https://user-images.githubusercontent.com/9412696/51819155-63a75080-230c-11e9-8446-c0337cc6fe69.png)
这是我选择了英文，头上标题变了，但下面tabbar没变
 
![8f19f0d17f7dcb76bee0f447da2a2bf](https://user-images.githubusercontent.com/9412696/51819254-b41eae00-230c-11e9-8bd8-abc8463b28ac.png)
这是我在h5和小程序上的切到英文的显示样式。tabbar一起变动了

`"tabBar" : {
        "color" : "#7A7E83",
        "selectedColor" : "#007AFF",
        "borderStyle" : "black",
        "backgroundColor" : "#F8F8F8",
        "list" : [
            {
                "pagePath" : "pages/index/index",
				"iconPath" : "static/img/home.png",
				"selectedIconPath" : "static/img/homeHL.png",
                "text" : "我的"
            },
            {
                "pagePath" : "pages/one/one",
				"iconPath" : "static/img/me.png",
				"selectedIconPath" : "static/img/meHL.png",
                "text" : "第一"
            },
            {
                "pagePath" : "pages/two/two",
				"iconPath" : "static/img/heart.png",
				"selectedIconPath" : "static/img/heartHL.png",
                "text" : "第二"
            }
        ]
    }`
这是我pages.json的配置
