### ISSUE TITLE
百度小程序新出的生命周期onInit，希望能尽快支持

### ISSUE THREAD

**Issue by mirror29** [dcloudio/uni-app#1810]
**新功能描述**
百度小程序新出的生命周期onInit，希望能尽快支持，百度文档地址：https://smartprogram.baidu.com/docs/develop/framework/app_service_pagelife/

**现状及问题**
该生命周期主要针对百度小程序的性能优化解决，目前uni-app并不支持，开发出的小程序性能并不是很理想，希望能尽快做到支持

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by zhetengbiji** [comment]
#2197

**Comment by zhetengbiji** [comment]
HBuilderX 3.1.0 alpha 已支持
