### ISSUE TITLE
UNIAPP云打包上架appstore报错ERROR ITMS-90668

### ISSUE THREAD

**Issue by Taylorzhao** [dcloudio/uni-app#1811]
ERROR ITMS-90668: "Invalid Bundle Executable. The executable file 'HBuilder.app/Frameworks/ReactiveObjC.framework/ReactiveObjC' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."

**Comment by chen4444729** [comment]
ReactiveObjC.framework 这个不是官方的库，需要在生成库之前在 Build Phases把Bitcode关闭

**Comment by Taylorzhao** [comment]
这个怎么解决呢？云打包上不了苹果商店，GitHub上已经提issue了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "chenleping"<notifications@github.com&gt;; 
发送时间: 2020年6月22日(星期一) 中午12:24
收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 
抄送: "star"<794682349@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dcloudio/uni-app] UNIAPP云打包上架appstore报错ERROR ITMS-90668 (#1811)





 
ReactiveObjC.framework 这个不是官方的库，需要在生成库之前在 Build Phases把Bitcode关闭

**Comment by Taylorzhao** [comment]
ERROR ITMS-90668: "Invalid Bundle Executable. The executable file 'HBuilder.app/Frameworks/AFNetworking.framework/AFNetworking' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."

ERROR ITMS-90668: "Invalid Bundle Executable. The executable file 'HBuilder.app/Frameworks/Aspects.framework/Aspects' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."

ERROR ITMS-90668: "Invalid Bundle Executable. The executable file 'HBuilder.app/Frameworks/MJExtension.framework/MJExtension' contains incomplete bitcode. To compile binaries with complete bitcode, open Xcode and choose Archive in the Product menu."

**Comment by chen4444729** [comment]
在生成库之前在 Build Phases把Bitcode关闭

**Comment by Taylorzhao** [comment]
云打包，不是离线打包，云打包，本地没有这个配置

**Comment by chen4444729** [comment]
ReactiveObjC.framework,AFNetworking.framework,Aspects.framework,MJExtension.framework这些不是dcloud官方的库，是你们自己生成的framework库还是用的其他第三方的库？如果是你们自己生成的库，在生成库之前在 Build Settings中把Bitcode关闭；如果是使用的第三方的库，你可以联系第三方（让其在生成framework库之前在配置项 Build Settings中把Bitcode关闭），或者找其他的能用的库代替。然后再提交云打包。

**Comment by hbcui1984** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
