### ISSUE TITLE
2.6.5版本云打包问题

### ISSUE THREAD

**Issue by myskybeyond** [dcloudio/uni-app#1812]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
打包后运行项目，样式错误（样式失效），组件的报错。
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
提交云打包后，提醒升级hbuildx，未升级和升级后云打包后的安装包，安装后样式错误，组件报错。
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]
![app主页](https://user-images.githubusercontent.com/37172114/85188674-177ef680-b2db-11ea-8e77-54dbcf644ab7.jpg)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
安卓版本
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
2.6.5
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by myskybeyond** [comment]
样式失效例图，引入的高德定位也出不来了。

**Comment by myskybeyond** [comment]
浏览器效果：
![1](https://user-images.githubusercontent.com/37172114/85189010-a12fc380-b2dd-11ea-9c37-ed930fc5cabf.png)
![2](https://user-images.githubusercontent.com/37172114/85189011-a260f080-b2dd-11ea-9127-ab627e32a4ed.png)
![3](https://user-images.githubusercontent.com/37172114/85189013-a42ab400-b2dd-11ea-9a7e-cf2c34fb6411.png)
手机效果：
![11](https://user-images.githubusercontent.com/37172114/85189016-aa209500-b2dd-11ea-84ff-a45fd1fa8776.jpg)
![22](https://user-images.githubusercontent.com/37172114/85189018-ab51c200-b2dd-11ea-9d91-c8b99302e24d.jpg)
![33](https://user-images.githubusercontent.com/37172114/85189019-ac82ef00-b2dd-11ea-9d78-359831ff552e.jpg)

**Comment by hbcui1984** [comment]
真机运行正常，云端打包后就失效？
