### ISSUE TITLE
uniapp 打包静态资源无法显示

### ISSUE THREAD

**Issue by githublyp** [dcloudio/uni-app#1813]
https://ask.dcloud.net.cn/question/96868
社区提交的bug都不修复吗？你们干什么吃的，口号喊得挺大，问题那么多，社区管理员根本一天瞎混

**Comment by zhetengbiji** [comment]
如果是同样问题，请把 img 改为 image

**Comment by githublyp** [comment]
你说的轻巧，从老项目迁移过来的，得改多少？而且官方既然说可以自动转换，说明这就是一个bug，隐藏了还有其他问题，怎么不管了？

**Comment by githublyp** [comment]
你们已经做的很好了，为什么不把细节搞好，让开发者寒心。。。我都想改源码了

**Comment by githubwenhao** [comment]
- -我现在都不行，ios打包一个图片都看不见我服了
