### ISSUE TITLE
CanvasContext.setFontSize 部分机型不兼容

### ISSUE THREAD

**Issue by dinghaizhou** [dcloudio/uni-app#1814]
**问题描述**
用fillText 画文字每次都要重新调用setFontSize，设置fontSize，否则文字出不来，出现机型小米8，等

**复现步骤**
[复现问题的步骤]
1.
this.ctx.setFontSize(17);
this.ctx.fillText('第一行', 0, 0)
this.ctx.fillText('第二行', 0, 100)
this.ctx.fill()
此时canvas 只能显示 第一行

2、
1.
this.ctx.setFontSize(17);
this.ctx.fillText('第一行', 0, 0)
this.ctx.setFontSize(17);
this.ctx.fillText('第二行', 0, 100)
this.ctx.fill()
此时canvas 才能显示第一行、第二行

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
更新 HBuilderX
