### ISSUE TITLE
使用vue-cli创建的uniapp项目,在mixins时会把methods里的方法赋值给data,导致vue报错

### ISSUE THREAD

**Issue by 643104191** [dcloudio/uni-app#1819]
https://github.com/dcloudio/uni-app/blob/26fffe1d6b82ccbbd4e5ad20d98c51751a3715b9/packages/uni-mp-weixin/dist/index.js#L770

### 使用vue-cli创建的uniapp项目,在mixins时会把methods里的方法赋值给data,导致vue报错

- 这是我的一个公用mixin方法
```javascript
export default function myMixins(id) {
  const data = {
    id,
    propName: '我是data中的数据'
  }
  const methods = {
    myMethods() {
      console.log(this.id)
    }
  }
  return {
    data() {
      return data
    },
    methods
  }
}
```

- 这是我使用mixins的地方
```javascript
export default Vue.extend({
  mixins: [myMixins('1')]
})

```

https://github.com/dcloudio/uni-app/blob/26fffe1d6b82ccbbd4e5ad20d98c51751a3715b9/packages/uni-mp-weixin/dist/index.js#L770
但是`uni-mp-weixin`里`dist/index.js`的770行
```javascript
Object.keys(methods).forEach(methodName => {
  if (context.__lifecycle_hooks__.indexOf(methodName) === -1 && !hasOwn(data, methodName)) {
    data[methodName] = methods[methodName];
  }
});
```
会把methods里的方法赋值给data,最终导致报错`data`中已经声明过`methods`里的一些方法,
是我使用mixins的方法不对吗?

**Comment by fxy060608** [comment]
修改为：
```
return {
    data() {
      return {
id,
    propName: '我是data中的数据'
}
    },
    methods
  }
```

**Comment by 643104191** [comment]
> 修改为：
> 
> ```js
> return {
>     data() {
>       return {
>     id,
>     propName: '我是data中的数据'
> }
>     },
>     methods
>   }
> ```

难道不是一样的?

**Comment by fxy060608** [comment]
> > 修改为：
> > ```js
> > return {
> >     data() {
> >       return {
> >     id,
> >     propName: '我是data中的数据'
> > }
> >     },
> >     methods
> >   }
> > ```
> 
> 难道不是一样的?

你的data函数写法是错误的，导致data被共享了，阅读官方说明：https://cn.vuejs.org/v2/api/#data

**Comment by xiaoyucoding** [comment]
遇到类似的问题，需要按照下面的写法解决：

``` javascript
export default {
  data() {
    // 必须在这里用展开符，直接返回 data 的情况会被共享。
    return {
      ...data
    };
  }
};
```

**Comment by 2234839** [comment]
@xiaoyucoding @643104191 当然不一样，你们这样的做法是不正确的呀， 使用 ` {
      ...data
    }` 也仅仅是浅拷贝了一层，vue 的 data 选项最好返回一份新的数据，这样创建多个实例他们之间是互不影响的，你多个实例返回了同一个数据自然就共享了呀 https://cn.vuejs.org/v2/api/#data 这里讲的很清楚的

**Comment by xiaoyucoding** [comment]
> @xiaoyucoding @643104191 当然不一样，你们这样的做法是不正确的呀， 使用 ` { ...data }` 也仅仅是浅拷贝了一层，vue 的 data 选项最好返回一份新的数据，这样创建多个实例他们之间是互不影响的，你多个实例返回了同一个数据自然就共享了呀 https://cn.vuejs.org/v2/api/#data 这里讲的很清楚的

我的 data 中只会涉及一层基础数据类型，都是一些基础配置信息，因此不考虑深拷贝的问题。
