### ISSUE TITLE
没有方法读取当前pages.json的数据，我无法做程序解偶，只能定制开发

### ISSUE THREAD

**Issue by lzf1201** [dcloudio/uni-app#182]
我试了很多法获取tabbar的数据，但没有成功，开发者没有提供数据读取的接口，包括我直接读pages.json都读不到数据。

**Comment by hbcui1984** [comment]
详细描述一下的需求，业务场景，你需要tabbar的哪些数据？

**Comment by zhetengbiji** [comment]
直接require即可
