### ISSUE TITLE
有没有什么方法从 uni-app 中 copy组件修改后放在自己的项目中使用

### ISSUE THREAD

**Issue by runryan** [dcloudio/uni-app#1825]
**问题描述**
目前遇到的问题是 swiper中包含了下拉刷新组件，在其实也和最后一页，下拉刷新和 swiper 的回弹事件会同时出发，给人页面整体向右下角移动的视觉。

但是 swiper 没有提供禁止回弹的属性。我想的是从 uni-app 的源码中把 swiper 组件拷贝出来，修改它的触摸处理事件，放在项目中当做自定义组件使用。但是 copy 出来后，有依赖 uni-app 中的其他文件，运行时报错。

我的问题是修改源码，以及引用 uni-app 源码的正确姿势是什么样的？

**Comment by zhetengbiji** [comment]
如果仅在H5端使用，拷贝走可以，记得找到相关依赖一起带走啊

**Comment by runryan** [comment]
> 如果仅在H5端使用，拷贝走可以，记得找到相关依赖一起带走啊

哈哈哈，我也试过这个办法，就是牵扯的依赖比较多，可能还要兼容多端的情况。心想整个项目都是基于uniapp做的，是不是可以只把组件搞出来搞搞就可以了。

**Comment by zhetengbiji** [comment]
> > 如果仅在H5端使用，拷贝走可以，记得找到相关依赖一起带走啊
> 
> 哈哈哈，我也试过这个办法，就是牵扯的依赖比较多，可能还要兼容多端的情况。心想整个项目都是基于uniapp做的，是不是可以只把组件搞出来搞搞就可以了。

之前不是只拷贝的组件和组件的相关依赖吗？

**Comment by runryan** [comment]
> > > 如果仅在H5端使用，拷贝走可以，记得找到相关依赖一起带走啊
> > 
> > 
> > 哈哈哈，我也试过这个办法，就是牵扯的依赖比较多，可能还要兼容多端的情况。心想整个项目都是基于uniapp做的，是不是可以只把组件搞出来搞搞就可以了。
> 
> 之前不是只拷贝的组件和组件的相关依赖吗？

我试过了scroll-view，把所有import的文件都到拷贝出来，然后在自己的项目中用，不行。你如果感兴趣也可以试试。如果成功了，还希望分享下经验。

**Comment by zhetengbiji** [comment]
> > > > 如果仅在H5端使用，拷贝走可以，记得找到相关依赖一起带走啊
> > > 
> > > 
> > > 哈哈哈，我也试过这个办法，就是牵扯的依赖比较多，可能还要兼容多端的情况。心想整个项目都是基于uniapp做的，是不是可以只把组件搞出来搞搞就可以了。
> > 
> > 
> > 之前不是只拷贝的组件和组件的相关依赖吗？
> 
> 我试过了scroll-view，把所有import的文件都到拷贝出来，然后在自己的项目中用，不行。你如果感兴趣也可以试试。如果成功了，还希望分享下经验。

具体怎么个不行？你仔细检查检查，之前vivo的同学就是这么用的。

**Comment by runryan** [comment]
> > > > > 如果仅在H5端使用，拷贝走可以，记得找到相关依赖一起带走啊
> > > > 
> > > > 
> > > > 哈哈哈，我也试过这个办法，就是牵扯的依赖比较多，可能还要兼容多端的情况。心想整个项目都是基于uniapp做的，是不是可以只把组件搞出来搞搞就可以了。
> > > 
> > > 
> > > 之前不是只拷贝的组件和组件的相关依赖吗？
> > 
> > 
> > 我试过了scroll-view，把所有import的文件都到拷贝出来，然后在自己的项目中用，不行。你如果感兴趣也可以试试。如果成功了，还希望分享下经验。
> 
> 具体怎么个不行？你仔细检查检查，之前vivo的同学就是这么用的。

哈哈哈，可以了，是一个文件导入错误了。

感谢！！！让我有动力一致探索。

**Comment by runryan** [comment]
> > > > > 如果仅在H5端使用，拷贝走可以，记得找到相关依赖一起带走啊
> > > > 
> > > > 
> > > > 哈哈哈，我也试过这个办法，就是牵扯的依赖比较多，可能还要兼容多端的情况。心想整个项目都是基于uniapp做的，是不是可以只把组件搞出来搞搞就可以了。
> > > 
> > > 
> > > 之前不是只拷贝的组件和组件的相关依赖吗？
> > 
> > 
> > 我试过了scroll-view，把所有import的文件都到拷贝出来，然后在自己的项目中用，不行。你如果感兴趣也可以试试。如果成功了，还希望分享下经验。
> 
> 具体怎么个不行？你仔细检查检查，之前vivo的同学就是这么用的。

我胡汉三又回来了！

我是从uniapp源码中拷贝了scroll-view的源码到自己的项目中。经过一番周折scroll-view能正常显示跑起来。在H5端可以完美运行，但是在iOS中就会有各种API不兼容的情况，各种undefined。

我是在vue文件中写的，其实是想关闭scrollview在iOS中的回弹效果。

直接从源码拷贝组件，想要在各端兼容有些困难重重。

**Comment by zhetengbiji** [comment]
> > > > > > 如果仅在H5端使用，拷贝走可以，记得找到相关依赖一起带走啊
> > > > > 
> > > > > 
> > > > > 哈哈哈，我也试过这个办法，就是牵扯的依赖比较多，可能还要兼容多端的情况。心想整个项目都是基于uniapp做的，是不是可以只把组件搞出来搞搞就可以了。
> > > > 
> > > > 
> > > > 之前不是只拷贝的组件和组件的相关依赖吗？
> > > 
> > > 
> > > 我试过了scroll-view，把所有import的文件都到拷贝出来，然后在自己的项目中用，不行。你如果感兴趣也可以试试。如果成功了，还希望分享下经验。
> > 
> > 
> > 具体怎么个不行？你仔细检查检查，之前vivo的同学就是这么用的。
> 
> 我胡汉三又回来了！
> 
> 我是从uniapp源码中拷贝了scroll-view的源码到自己的项目中。经过一番周折scroll-view能正常显示跑起来。在H5端可以完美运行，但是在iOS中就会有各种API不兼容的情况，各种undefined。
> 
> 我是在vue文件中写的，其实是想关闭scrollview在iOS中的回弹效果。
> 
> 直接从源码拷贝组件，想要在各端兼容有些困难重重。

记不记得之前说过：“如果仅在H5端使用，拷贝走可以，记得找到相关依赖一起带走啊”

非H5端不支持Dom

**Comment by runryan** [comment]
原来如此呀，那么怎样能兼容到APP端呢？如果用纯Vue的方式。

**Comment by zhetengbiji** [comment]
> 原来如此呀，那么怎样能兼容到APP端呢？如果用纯Vue的方式。

理解相关组件，用自己的思路重写不含Dom操作的。

**Comment by runryan** [comment]
我理解你的意思，是解决我问题的方向。

无dom操作的组件，没有学习过，应该从哪里入手呢？我查了资料，是mpvue吗？如果有好的参考资料，麻烦给我po一份链接。

感谢！

**Comment by zhetengbiji** [comment]
> 我理解你的意思，是解决我问题的方向。
> 
> 无dom操作的组件，没有学习过，应该从哪里入手呢？我查了资料，是mpvue吗？如果有好的参考资料，麻烦给我po一份链接。
> 
> 感谢！

学习资料：就是uni-app官方文档。。。。

**Comment by runryan** [comment]
app-vue和H5还好，可以直接用`renderjs`去操作DOM，许多前端的轮子都可以用。到了小程序，就Swiper和ScrollView这种关闭`bounces`的需求，就要自己造轮子，不太好搞。
