### ISSUE TITLE
用getCurrentPages()取出来的值在H5中和小程序中有差异

### ISSUE THREAD

**Issue by sntyy** [dcloudio/uni-app#183]
我要用getCurrentPages()取出上一页并给data中的XXX赋值，在H5运行正常，但在小程序中赋值时发现这个XXX的值是undefined

**Comment by hulinNeil** [comment]
我们从来没提过可以通过getCurrentPages()来进行赋值操作。
在H5里面由于全支持vue所以你这样的操作可能生效，但是在小程序和app里面这样的操作是行不通的。
