### ISSUE TITLE
textarea能够增加confirm事件吗，在app上做通讯需要能够改变confirm-type的同时能够监听。

### ISSUE THREAD

**Issue by LingCn** [dcloudio/uni-app#1830]
**新功能描述**
简洁描述你希望补充完善的增强功能
textarea能够增加confirm事件吗，在app上做通讯需要能够改变confirm-type的同时能够监听。

**现状及问题**
[当前现状及由此导致的不便]
目前使用nvue页面做及时通讯，但是textarea没有所谓的confirm的事件，只能单独加一个发送按钮，期望是实现微信聊天窗口一样的功能

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]
weex组件中textarea不是有return事件吗？在uniapp上不能支持吗

**补充信息**
[其它你认为有参考价值的信息]

**Comment by zhetengbiji** [comment]
你是说nvue中return 事件无效吗？
另外 vue 页面的 textarea 组件在 2.9.9+ 也有相关改进，可以看下
