### ISSUE TITLE
我想生成一个二维码，让别人进行扫码体验，怎么生成

### ISSUE THREAD

**Issue by HomyeeKing** [dcloudio/uni-app#1832]
生成一个多端二维码，让用户扫描即可使用，怎么生成

**Comment by hbcui1984** [comment]
插件市场上有很多，https://ext.dcloud.net.cn/search?q=%E4%BA%8C%E7%BB%B4%E7%A0%81

**Comment by HomyeeKing** [comment]
> 插件市场上有很多，https://ext.dcloud.net.cn/search?q=%E4%BA%8C%E7%BB%B4%E7%A0%81

好吧 我以为框架打包APP的时候会生成对应的二维码，原来还得自己生成
