### ISSUE TITLE
uni.chooseLocation H5页面加载时间长，定位不准

### ISSUE THREAD

**Issue by guoyanfangabcd** [dcloudio/uni-app#1834]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
加载时间具体多久？
位置偏差具体多大？

**Comment by guoyanfangabcd** [comment]
加载时间6-7秒，位置偏差两条街，地图上没显示出来当前位置得拖动找

**Comment by zhetengbiji** [comment]
使用的是移动网络还是WIFI？在室内还是室外？

**Comment by guoyanfangabcd** [comment]
wifi,在室内

**Comment by zhetengbiji** [comment]
> wifi,在室内

尝试切换一下网络和地点试试。
选择位置是直接使用的腾讯地图选点组件：[https://lbs.qq.com/webApi/component/componentGuide/componentPicker](https://lbs.qq.com/webApi/component/componentGuide/componentPicker) 你直接访问这里面的示例（底部扫码）看看效果如何。

**Comment by guoyanfangabcd** [comment]
直接访问腾讯地图组件是很快的，就是直接用uni.chooseLocation慢

**Comment by zhetengbiji** [comment]
> 直接访问腾讯地图组件是很快的，就是直接用uni.chooseLocation慢

你试试官方这个示例的呢：https://uniapp.dcloud.io/h5/pages/API/choose-location/choose-location

**Comment by guoyanfangabcd** [comment]
一样的很慢，多个Android手机都很慢

**Comment by zhetengbiji** [comment]
> 一样的很慢，多个Android手机都很慢

你用Chrome浏览器打开调试，模拟移动设备，然后查看一下网络面板，看下是哪个请求响应的比较慢

**Comment by guoyanfangabcd** [comment]
浏览器不慢，使用微信开发工具和手机慢  微信开发工具可以看到还报错Ignored call to 'alert()'. The document is sandboxed, and the 'allow-modals' keyword is not set.     [Violation] Geolocation access has been blocked because of a Feature Policy applied to the current document. See https://goo.gl/EuHzyv for more details.

**Comment by guoyanfangabcd** [comment]
您用微信开发工具试试看

**Comment by zhetengbiji** [comment]
> 浏览器不慢，使用微信开发工具和手机慢 微信开发工具可以看到还报错Ignored call to 'alert()'. The document is sandboxed, and the 'allow-modals' keyword is not set. [Violation] Geolocation access has been blocked because of a Feature Policy applied to the current document. See https://goo.gl/EuHzyv for more details.

你说的手机是特指的微信内置浏览器吗？还是指的手机内置浏览器？

**Comment by guoyanfangabcd** [comment]
微信内置浏览器和手机内置浏览器都慢

**Comment by zhetengbiji** [comment]
找到这个文件：HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/uni-h5/dist/index.umd.min.js
打开编辑，搜索sandbox:"allow-scripts allow-same-origin allow-forms" 替换为：sandbox:"allow-scripts allow-same-origin allow-forms allow-modals allow-popups"

**Comment by guoyanfangabcd** [comment]
不报错了，手上还是很慢

**Comment by zhetengbiji** [comment]
目前分析定位时间长与定位偏差大是由于选点组件的问题导致，已向腾讯地图提交了工单。

**Comment by guoyanfangabcd** [comment]
好的，谢谢，目前直接使用腾讯的组件还是比较快的所以暂时打算直接使用腾讯组件

**Comment by zhetengbiji** [comment]
> 好的，谢谢，目前直接使用腾讯的组件还是比较快的所以暂时打算直接使用腾讯组件

我这测试直接访问定位组件在微信浏览器内一样很慢（把Chrome的UA改成微信浏览器后结果一致），应该是定位组件判断环境为微信的时候，尝试其他高精度方案（未成功）。

**Comment by guoyanfangabcd** [comment]
哦哦，确实是，期待早日解决呀~

**Comment by zhetengbiji** [comment]
同一个人在 issue 没关闭的情况下，没必要发起多个，以后在此继续留言即可

**Comment by guoyanfangabcd** [comment]
着急丫丫丫丫。。

**Comment by zhetengbiji** [comment]
> 着急丫丫丫丫。。

目前腾讯地图的工单答复：“您好，工程师已收到您的问题，此问题需要工程师这边对后续的版本优化后才能加入。还请您耐心等待”

**Comment by qingdi** [comment]
伤不起。。

**Comment by zhetengbiji** [comment]
> 伤不起。。

嗯

**Comment by zhetengbiji** [comment]
HBuilderX 2.9.9 alpha 重构了 chooseLocation，快更新试试吧

**Comment by qingdi** [comment]
目测还是没解决

**Comment by zhetengbiji** [comment]
> 目测还是没解决

这个已经改了很久了，你怎么目的，能否具体说下？

**Comment by Jaysaury** [comment]
uni.chooseLocation的keyword无效这个官方会解决吗
