### ISSUE TITLE
input输入框在单词联想时点击空白处，没有将输入的内容返回并且报错

### ISSUE THREAD

**Issue by little-thing** [dcloudio/uni-app#1838]
@hbcui1984 
**问题描述**

inout输入时，如果使用的是原生键盘，那么会关联拼写，但是当点击空白处或者监听@input时，会报一个错vm.onInput is not a function，此处onInput为@input自定义调用的方法

**复现步骤**
[复现问题的步骤]
前提条件：使用原生android键盘，环境为微信小程序
1.  启动 '表单组件'
2. 点击  'input输入任意英文'，此时输入框内的英文是带下划线的，再点击空白处收起键盘，让input失去焦点，将触发onInput，这时会报vm.onInput is not a function
3. 查看

[或者可以直接贴源代码]

**预期结果**
预期将原生键盘的input返回，原生微信小程序是支持的

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/42090126/85944486-a63de400-b969-11ea-9193-6879f38f0b9b.png)
此时不点击红色框中的内容直接点击空白处收起键盘，让input失去焦点，那么input组件触发onInput的时候会报错

![image](https://user-images.githubusercontent.com/42090126/85944526-fae15f00-b969-11ea-9df0-e0e4730f97fb.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 Android 7.0
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
我认为应该是处于单词拼写过程中@input调用onInput的时候失败了
但是使用@change是可以成功的，应该是@input的写法问题在mp-weixin端,在这种情况下@emit('input')时丢失了this对象

**Comment by 3115674243** [comment]
@fxy060608

**Comment by kengker** [comment]
我也遇到了相同的问题了，请问怎么解决？

**Comment by Hedaren** [comment]
我也遇到了相同的问题了，请问怎么解决？

**Comment by zhetengbiji** [comment]
你们分别使用的什么输入法？

**Comment by savokiss** [comment]
相同的问题，输入候选词直接点键盘上的回车符，也会报错。
搜狗输入法小米版

**Comment by wenbin-ding** [comment]
也遇到了这个问题，我这里在input上用v-model可以解决，demo:

**自定义组件`custom-input.vue`，封装input**
```
<template>
  <input
    type="text"
    v-model="text"
    @blur="onBlur"
  />
</template>
<script>
export default {
  props: ['value'],
  computed: {
    text: {
      get() { return this.value; },
      set(val) { this.$emit('input', val); }
    }
  },
  methods: {
    onBlur (e) {
      // 触发blur时手动同步值
      this.text = e.detail.value
    }
  }
}
</script>
```

**父组件**
```
<template>
    <custom-input v-model="inputText" />
</template>
<script>
    import customInput from './custom-input';
    
    export default {
        components: {customInput},
        data() { return { inputText: '初始值' }; }
    }
</script>
```
