### ISSUE TITLE
app微信登录有没有方式只获取code，不需要用户的基本信息

### ISSUE THREAD

**Issue by fallsea** [dcloudio/uni-app#184]
如图，由于我们系统安全要求比较高，需要获取到code才可以，请问一下有没有方式来获取。

![tim 20190128141846](https://user-images.githubusercontent.com/30261057/51817933-e5e14600-2307-11e9-99d3-31fa52bbe6a1.png)

**Comment by xiaoyucoding** [comment]
参考：[通过授权的方式获取微信登录的 code](http://ask.dcloud.net.cn/article/35555)

**Comment by fallsea** [comment]
@xiaoyucoding 感谢，我们试一下

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
