### ISSUE TITLE
前端部署404

### ISSUE THREAD

**Issue by githublyp** [dcloudio/uni-app#1840]
https://ask.dcloud.net.cn/question/72168
为什么基本的功能都保证不了，还谈什么为开发者，呵呵。。。bug多的实在不敢用了，一个img标签的问题都修复不了，当初说好的会转换，突然不支持了，这算什么？让人担忧以后会不会出现上了贼船下船难的的情况。

**Comment by uniapp404** [comment]
你说的，我也感觉官方的程序员好像都是二手的 @fxy060608

**Comment by fxy060608** [comment]
https://router.vuejs.org/zh/guide/essentials/history-mode.html

**Comment by githublyp** [comment]
> https://router.vuejs.org/zh/guide/essentials/history-mode.html

大哥，如果是我自己的服务器我倒是可以，现在用的是你们的前端部署托管服务器。你们自己没试过绑定其他域名后单页面访问除了首页可以刷新访问，其他子页面都是404  
```
404 Not Found
The requested URL was not found on this server.

Powered by Tengine
````

**Comment by githublyp** [comment]
而且目前只支持单站点，多目录或多站点都不行

**Comment by Wangyaqi** [comment]
> > https://router.vuejs.org/zh/guide/essentials/history-mode.html
> 
> 大哥，如果是我自己的服务器我倒是可以，现在用的是你们的前端部署托管服务器。你们自己没试过绑定其他域名后单页面访问除了首页可以刷新访问，其他子页面都是404
> 
> ```
> 404 Not Found
> The requested URL was not found on this server.
> 
> Powered by Tengine
> ```

https://uniapp.dcloud.io/uniCloud/hosting?id=host-uni-app

**Comment by Wangyaqi** [comment]
> 而且目前只支持单站点，多目录或多站点都不行@fxy060608

腾讯可以通过自定义重定向规则实现多站点，阿里目前正在实现

**Comment by githublyp** [comment]
> > > https://router.vuejs.org/zh/guide/essentials/history-mode.html
> > 
> > 
> > 大哥，如果是我自己的服务器我倒是可以，现在用的是你们的前端部署托管服务器。你们自己没试过绑定其他域名后单页面访问除了首页可以刷新访问，其他子页面都是404
> > ```
> > 404 Not Found
> > The requested URL was not found on this server.
> > 
> > Powered by Tengine
> > ```
> 
> https://uniapp.dcloud.io/uniCloud/hosting?id=host-uni-app

配置了大哥
```
使用history模式时可以配置如下规则

腾讯云配置重定向规则将404错误码重定向至index.html
阿里云配置错误文档为index.html
```

**Comment by Wangyaqi** [comment]
> https://uniapp.dcloud.io/uniCloud/hosting?id=host-uni-app

阿里云新增域名之后可能需要几个小时才能让其他配置对新域名生效
