### ISSUE TITLE
typescript 无法识别this

### ISSUE THREAD

**Issue by keyiis** [dcloudio/uni-app#1843]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
使用官方cli创建的typescript项目，在增加计算属性后编译就会报错，但是生成的代码可以正常运行
**复现步骤**
[复现问题的步骤]
![image](https://user-images.githubusercontent.com/7766085/86011552-651fff80-ba4f-11ea-97bd-f55c66bbd886.png)

报错信息
![image](https://user-images.githubusercontent.com/7766085/86011899-dbbcfd00-ba4f-11ea-944f-63091ae62b85.png)

**Comment by d1y** [comment]
你 `data` 没有返回 `org` 啊, 我的做法

```vue
interface dataInterface {
  ...
  org: any
}
{
  data(): dataInterface {
    return {
      ...,
      org: {}
    }
  },
  methods: {
     test(){
       try {
         if (this.org.xx) {
           // TODO
         }
       } catch(err) {

       }
     }
  }
}
```

**Comment by Otto-J** [comment]
使用箭头函数
