### ISSUE TITLE
input组件动态设置type导致样式变化

### ISSUE THREAD

**Issue by januwA** [dcloudio/uni-app#1846]
**问题描述**
在h5上，使用input组件动态设置type导致样式变化

正常:
```
<input type='number'  />
```
![image](https://user-images.githubusercontent.com/22570563/86117327-60b41f00-bb01-11ea-878f-ce78fb2ee6c7.png)

意外:
```
<input :type='type'  />
```
![image](https://user-images.githubusercontent.com/22570563/86117353-6b6eb400-bb01-11ea-9d82-7a7a54802c54.png)

**系统信息:**
 - 发行平台: H5
 - 操作系统 PC CHROME
 - HBuilderX版本2.7.14.20200618

**Comment by januwA** [comment]
急，help me

**Comment by januwA** [comment]
同时会导致，设置`maxlength`无效

**Comment by zhetengbiji** [comment]
不支持动态设置type，请使用v-if进行切换

**Comment by januwA** [comment]
@zhetengbiji  非常感谢你的帮助

**Comment by zhaowuyang** [comment]
请优雅的解决此问题
