### ISSUE TITLE
textarea的 cursor-spacing属性 在nvue无效android，是不是不支持？？

### ISSUE THREAD

**Issue by LingCn** [dcloudio/uni-app#1847]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
textarea的 cursor-spacing属性 在nvue无效，是不是不支持？？
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

					<textarea type="text"  class="sendMessage" :scroll-top="messageTop" :cursor-spacing='20'  :auto-height='autoHeight' :adjust-position="is_android" :fixed='true' id='sendMessage' v-model="content" :cursor="cursorLength" @input="lineChange($event)" @focus="onFocus()" @blur="onBlur()"/>

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]
![Screenshot_20200701_103500](https://user-images.githubusercontent.com/22288787/86196863-b252bd00-bb86-11ea-9c2a-808659d328c4.jpg)

**系统信息:**
 - 操作系统 [如 iOS 12.1.2、Android 7.1]
 - HBuilderX版本 [2.7.14.2]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by dcloudhdx** [comment]
暂不支持

**Comment by LingCn** [comment]
这个对于做即时通讯有没有什么绕开的办法吗？不然就是硬伤了呀。
