### ISSUE TITLE
uniapp 2.6.16版本升级到2.7版本后rpx单位转换（一定分辨率下，1920*1080）可能出现问题了

### ISSUE THREAD

**Issue by creatfutrue** [dcloudio/uni-app#1848]
**问题描述**
uniapp 2.6.16版本升级到2.7版本后rpx单位转换（一定分辨率下，1920*1080）可能出现问题了，原本占满全屏的内容现在只有一半了,目前只在vue页面上发现这个问题，nvue不存在此问题.复现问题中第一张正常是（2.6.16)的，第二张不正常的是（2.7.13）,第三张是（2.7.13）里面的nvue页面.

**复现步骤**
[复现问题的步骤]
``
![2 6 16](https://user-images.githubusercontent.com/34222424/86305708-e7254980-bc44-11ea-8120-400b3f0f55cb.jpg)
![2 7 14](https://user-images.githubusercontent.com/34222424/86305891-569b3900-bc45-11ea-920d-da6f0cfa55cf.jpg)
![nvue](https://user-images.githubusercontent.com/34222424/86305900-5c911a00-bc45-11ea-8c7a-8a77dea0da4c.png)

[或者可以直接贴源代码]

**预期结果**
正常显示

**实际结果**
错误显示

**系统信息:**
 - 发行平台: APP
 - 操作系统 ：Android 6.0
 - HBuilderX版本 ：2.7.13
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
猜测是rpx的在（1920*1080）下的转换可能有问题(2.6.16版本以后).

**Comment by Fasttian** [comment]
.vue 测试 rpx 未能复现, 1920*1080 仍然能铺满屏幕, 你可以用下面这个简单的示例，自己测试一下
```
<template>    
    <view class="container">    
        <view class="A">第一行 A</view>  
        <view class="B">第二行 B</view>  
    </view>    
</template>    

<script>    
    export default {    

    }    
</script>  

<style>  
    .container {  
        display: flex;  
        height: 1080px;  
    }  
    .A {  
        width: 375rpx;  
        height: 100%;  
        background-color: #1AAD19;  
    }  

    .B {  
        width: 375rpx;  
        height: 100%;  
        background-color: #FFB400;  
    }  
</style>
```

**Comment by dcloudhdx** [comment]
Bug已确认，计算宽高颠倒导致

**Comment by dcloudhdx** [comment]
HBuilderX 2.8.1+ alpha 版已修复
