### ISSUE TITLE
v-for和class作用域冲突

### ISSUE THREAD

**Issue by uioz** [dcloudio/uni-app#185]
# 设备平台
windows10
HbuilderX 1.5.4.20190127
Android8.1.1

# 描述

代码如下:
```
<view class="item">
  <view v-for="item in list">{{item}}</view>
</view>
<style>
 .item{ background-color:aqua; }
</style>
```

当class定义的类名和`v-for`声明的变量重名,移动端Android(真机运行)会出现奇怪的问题.

最后没有背景颜色,class应该是被替换掉了,或者编译时候被处理了.

# 建议

我去查了一下mpvue的文档居然一样啊,然后我又回来搜索了一遍内容,发现没有该问题的介绍.

重名不是什么大不了的事情,如果不打算修复,请在文档里提一句可好,还有这个 #180 中的v-for问题

**Comment by xiaoyucoding** [comment]
测试了一下，没有重现背景颜色失效的问题。

v-for 在不同平台上表现不一致，请参考 [#180](https://github.com/dcloudio/uni-app/issues/180) 中的解决方案使用。

**Comment by uioz** [comment]
抱歉是我搞错了,在Chrome中编写样式不添加scoped也是可以的,然后真机运行却需要添加scoped,我以为这个选项是默认开启的.

然后样式定义重复又正好在`.item`这个地方和v-for重复了,导致需要修改类名.
