### ISSUE TITLE
uni.uploadFile 分块上传功能

### ISSUE THREAD

**Issue by southpush** [dcloudio/uni-app#1853]
**新功能描述**
希望可以出一个分块上传功能，针对app的

**现状及问题**
现在用户拍照一张照片原图就能有个10m，希望能有分块上传的功能
另外现在我的项目后台那边需要上传每个文件分块的时候带上这是第几块数据，共几块数据的参数，希望能出一个每个分块数据上传完的钩子

**尝试方案**
首先要将文件分块对吧，但是看了下uni.uploadFile，发现app不支持file对象，然后想到的方法是使用plus api将文件File对象slice之后保存下来拿到filePath，再上传，但是plus api写到后边发现FileReader不支持以二进制形式读取文件，就不知道要怎么办了（FileWriter.write()接受的是DOMString）

**补充信息**
plus.uploader 有分块上传，但是不知道能怎么做到上边说的带上分块信息的功能

**Comment by everlose** [comment]
同问

**Comment by everlose** [comment]
同问

**Comment by southpush** [comment]
> 同问

可以试试写原生安卓搞个接口给uniapp，我后来这么解决的

**Comment by 530209190** [comment]
> **新功能描述**
> 希望可以出一个分块上传功能，针对app的
> 
> **现状及问题**
> 现在用户拍照一张照片原图就能有个10m，希望能有分块上传的功能
> 另外现在我的项目后台那边需要上传每个文件分块的时候带上这是第几块数据，共几块数据的参数，希望能出一个每个分块数据上传完的钩子
> 
> **尝试方案**
> 首先要将文件分块对吧，但是看了下uni.uploadFile，发现app不支持file对象，然后想到的方法是使用plus api将文件File对象slice之后保存下来拿到filePath，再上传，但是plus api写到后边发现FileReader不支持以二进制形式读取文件，就不知道要怎么办了（FileWriter.write()接受的是DOMString）
> 
> **补充信息**
> plus.uploader 有分块上传，但是不知道能怎么做到上边说的带上分块信息的功能

请教一下， app端中 文件slice后如何保存？ 我看plus api 上面都是写的一个地址保存到另外一个地址，没有将这种数据保存到另外一个地址的方法呀。
