### ISSUE TITLE
video组件在微信中无法预加载视频封面和时长

### ISSUE THREAD

**Issue by dying318** [dcloudio/uni-app#1854]
video组件在微信中无法预加载视频封面和时长，虽然可以设置封面和时长，但是这需要额外的处理了，原生video组件的preload貌似就可以搞定了吧。

**Comment by zhetengbiji** [comment]
> video组件在微信中无法预加载视频封面和时长，虽然可以设置封面和时长，但是这需要额外的处理了，原生video组件的preload貌似就可以搞定了吧。

H5端运行在微信内置浏览器吗？只有在腾讯系白名单之内的域名才可以使用原始的video（其他国产浏览器类似）。

**Comment by dying318** [comment]
get，感谢
