### ISSUE TITLE
HBuilderX最新版本编译到小程序出现-未找到入口 sitemap.json 文件

### ISSUE THREAD

**Issue by Gyang18** [dcloudio/uni-app#1860]
**问题描述**
项目是在更新版本前就创建的项目，更新后编译到微信小程序出现：

![image](https://user-images.githubusercontent.com/24975063/86424577-83b71c80-bd15-11ea-803f-d27dee4280a8.png)

**复现步骤**
1. 使用最新版本的编辑器运行到微信小程序
2. 出现上述问题

**预期结果**
在微信小程序端会自动生成sitemap.json 文件
**实际结果**
没有生成对应的sitemap.json 文件

![image](https://user-images.githubusercontent.com/24975063/86424725-db558800-bd15-11ea-8c49-266c4c50589b.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统： win10 微信小程序开发工具

 - HBuilderX版本： 2.7.14.20200618（最新版本）
 - 设备信息： 暂无真实手机设备

**补充信息**

**Comment by Deeeeeee** [comment]
遇到同样问题，我是cli 创建的,相关版本号如下
```
 "dependencies": {
    "@dcloudio/uni-app-plus": "^2.0.0-27920200527001",
    "@dcloudio/uni-h5": "^2.0.0-27920200527001",
    "@dcloudio/uni-helper-json": "*",
    "@dcloudio/uni-mp-360": "^2.0.0-27920200527001",
    "@dcloudio/uni-mp-alipay": "^2.0.0-27920200527001",
    "@dcloudio/uni-mp-baidu": "^2.0.0-27920200527001",
    "@dcloudio/uni-mp-qq": "^2.0.0-27920200527001",
    "@dcloudio/uni-mp-toutiao": "^2.0.0-27920200527001",
    "@dcloudio/uni-mp-weixin": "^2.0.0-27920200527001",
    "@dcloudio/uni-quickapp-native": "^2.0.0-27920200527001",
    "@dcloudio/uni-quickapp-webview": "^2.0.0-27920200527001",
    "@dcloudio/uni-stat": "^2.0.0-27920200527001",
    "@dcloudio/uni-ui": "^1.2.1",
    "core-js": "^3.6.5",
    "dayjs": "^1.8.28",
    "flyio": "^0.6.2",
    "js-md5": "^0.7.3",
    "onfire.js": "^2.0.1",
    "regenerator-runtime": "^0.12.1",
    "vue": "^2.6.11",
    "vuex": "^3.2.0"
  },
  "devDependencies": {
    "@dcloudio/types": "*",
    "@dcloudio/uni-automator": "^2.0.0-27920200527001",
    "@dcloudio/uni-cli-shared": "^2.0.0-27920200527001",
    "@dcloudio/uni-migration": "^2.0.0-27920200527001",
    "@dcloudio/uni-template-compiler": "^2.0.0-27920200527001",
    "@dcloudio/vue-cli-plugin-hbuilderx": "^2.0.0-27920200527001",
    "@dcloudio/vue-cli-plugin-uni": "^2.0.0-27920200527001",
    "@dcloudio/vue-cli-plugin-uni-optimize": "^2.0.0-27920200527001",
    "@dcloudio/webpack-uni-mp-loader": "^2.0.0-27920200527001",
    "@dcloudio/webpack-uni-pages-loader": "^2.0.0-27920200527001",
    "@vue/cli-plugin-babel": "^4.4.0",
    "@vue/cli-service": "^4.4.0",
    "babel-plugin-import": "^1.11.0",
    "cross-env": "^7.0.2",
    "jest": "^25.4.0",
    "mini-types": "*",
    "miniprogram-api-typings": "*",
    "node-sass": "^4.14.1",
    "postcss-comment": "^2.0.0",
    "sass-loader": "^8.0.2",
    "vue-template-compiler": "^2.6.11"
  },
```
查看更新日志 1.9版本 就修复了。结果现在又出现这个问题了，麻烦给个解决方案吧
![image](https://user-images.githubusercontent.com/14084787/86425977-21601b00-bd19-11ea-96da-9219952f013b.png)

**Comment by fxy060608** [comment]
更新日志里的新增，是指你可以在项目根目录创建自己的ext.json和sitemap.json，编译器不会自动生成该文件（该文件通常是微信开发者工具自己生成的）

**Comment by Deeeeeee** [comment]
现在的问题是 项目的根目录手动创建了sitemap.json 但是编译到 mp-weixin 中并没有这个文件。所以才会报这个错。

如果在mp-weixin 目录手动添加 每次编译打包 都要重新手动添加，这不合理吧

**Comment by Gyang18** [comment]
可是我的问题是项目最开始创建的时候，是会自动生成的没有出现任何报错，更新了编辑器版本才出现的这个问题

**Comment by fxy060608** [comment]
> 现在的问题是 项目的根目录手动创建了sitemap.json 但是编译到 mp-weixin 中并没有这个文件。所以才会报这个错。
> 
> 如果在mp-weixin 目录手动添加 每次编译打包都会被清掉 都要重新手动添加，这不合理吧

cli工程，在src里边，创建sitemap.json，编译后mp-weixin中没有这个文件？我这里测试没有问题

**Comment by fxy060608** [comment]
> 可是我的问题是项目最开始创建的时候，是会自动生成的没有出现任何报错，更新了编辑器版本才出现的这个问题

HBuilderX 没有自动生成过sitemap.json文件，这个文件是微信开发者工具自己生成的。
你可以尝试从微信开发者工具的项目管理里边，删除该项目，然后重新导入看看。
如果还不行，可以自己在项目根目录创建sitemap.json测试

**Comment by Gyang18** [comment]
好的，我这边刚刚测试一下退回了上次版本就好了，等下我再试试你说的方法

**Comment by Gyang18** [comment]
我这边问题已经解决了，应该就是缓存问题，我的解决步骤如下：

**Comment by Gyang18** [comment]
> > 可是我的问题是项目最开始创建的时候，是会自动生成的没有出现任何报错，更新了编辑器版本才出现的这个问题
> 
> HBuilderX 没有自动生成过sitemap.json文件，这个文件是微信开发者工具自己生成的。
> 你可以尝试从微信开发者工具的项目管理里边，删除该项目，然后重新导入看看。
> 如果还不行，可以自己在项目根目录创建sitemap.json测试

谢谢解答，我这边按照你说的方法已经解决了，应该就是缓存的问题，解决步骤如下：

**Comment by Deeeeeee** [comment]
> > 现在的问题是 项目的根目录手动创建了sitemap.json 但是编译到 mp-weixin 中并没有这个文件。所以才会报这个错。
> > 如果在mp-weixin 目录手动添加 每次编译打包都会被清掉 都要重新手动添加，这不合理吧
> 
> cli工程，在src里边，创建sitemap.json，编译后mp-weixin中没有这个文件？我这里测试没有问题

sorry 之前加在了 主的根目录。没有放到src, 按你说的 已经可以了。多谢！
