### ISSUE TITLE
placeholder-class支持class语法

### ISSUE THREAD

**Issue by thecoolbb** [dcloudio/uni-app#1862]
**新功能描述**
placeholder-class与class具有同样的使用方式

**现状及问题**
placeholder-class不支持v-bind绑定，:placeholder-class="{error: true}"不起作用

**尝试方案**
使用placeholder-style进行v-bind绑定，动态修改placeholder的样式

**补充信息**
基于class同一套逻辑编写

**Comment by Live-forever** [comment]
手机型号: HUAWEI - HRY - AL00a
运行系统: 29
微信版本: 8.0.3
基础版本库: 2.17.0 [536]

问题描述:   input  设置了  placeholder-class , 样式类中设置了 margin-left: 20rpx , 小程序端:   ios 没问题, 安卓手机  input  focus   的时候,  placeholder 文字会往input左边靠, 也就是说  placeholder-class中的样式类设置的margin-left 在安卓手机上 聚焦的时候失效了
