### ISSUE TITLE
swiper swiper-item 图片之间无法设置边距

### ISSUE THREAD

**Issue by xiejibiao** [dcloudio/uni-app#1863]
swiper swiper-item 图片之间应该怎样设置边距啊，两张图片沾在一起，无法设置边距，有点绝望！！！！！
![image](https://user-images.githubusercontent.com/30366768/86429736-02668680-bd23-11ea-8bb7-3c9b2f08f386.png)

**Comment by zhetengbiji** [comment]
小程序还是app，vue还是nvue？有相关设置和兼容性说明先看下文档。

**Comment by xiejibiao** [comment]
H5

**Comment by zhetengbiji** [comment]
> H5

看下文档，有相关配置

**Comment by thl3538** [comment]
文档似乎没有再设置了显示前后图片的边距，再设置前后图片 间隙 的配置把
> > H5
> 
> 看下文档，有相关配置
