### ISSUE TITLE
支付宝小程序预审核 静态编译出错

### ISSUE THREAD

**Issue by zjg2114** [dcloudio/uni-app#1865]
**问题描述**
uniapp编译到支付宝小程序 支付宝预审核 静态编译出错

**复现步骤**
1.编译到支付宝小程序,代码检查时报错,未定义变量
![image](https://user-images.githubusercontent.com/44963328/86440591-4f575680-bd3d-11ea-8b9e-14a64b2c3c66.png)

**预期结果**
编译不报错,通过编译检查

**实际结果**
![WX20200703-145302](https://user-images.githubusercontent.com/44963328/86440530-2fc02e00-bd3d-11ea-9cc4-5f42cf895ec6.png)

**系统信息:**
 - 发行平台: 支付宝小程序
 - HBuilderX版本 [2.7.14]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by dcloudhdx** [comment]
下版优化

**Comment by dcloudhdx** [comment]
HBuilderX 2.8.2+ 已修复
