### ISSUE TITLE
textarea在nvue下使用auto-height，当清除textarea中value的值得时候，行高没有变回1行

### ISSUE THREAD

**Issue by LingCn** [dcloudio/uni-app#1866]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
  textarea在nvue下使用auto-height，当清除textarea中value的值得时候，行高没有变回1行
**复现步骤**
[复现问题的步骤]
```
	<textarea type="text"  class="sendMessage" :scroll-top="messageTop" :cursor-spacing='20'  :auto-height='autoHeight' :adjust-position="is_android" id='sendMessage' v-model="content" :cursor="cursorLength" @input="lineChange($event)" @focus="onFocus()" @blur="onBlur()"/>
```

**实际结果**
[这里请贴上你的报错截图或文字]
![1](https://user-images.githubusercontent.com/22288787/86446322-62225900-bd46-11ea-9eee-824750f5048e.jpeg)
![2](https://user-images.githubusercontent.com/22288787/86446335-65b5e000-bd46-11ea-86a2-d932d287de8a.jpeg)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 13.1.3]
 - HBuilderX版本 [2.7.14.2]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by dcloudhdx** [comment]
提供的代码没有复现问题，请提供一个简单的工程
