### ISSUE TITLE
强烈建议添加pc端类型 max-width 功能

### ISSUE THREAD

**Issue by ctforcp** [dcloudio/uni-app#1867]
目前PC端只要屏幕一大 里面的 rpx 设置的字体等太大，简直没法看
可以通过计算的时候设置一个最大值，超过个值就使用这个值
比如 html 根标签的 font-size 超过 37.5px ,就使用 37.5px (750宽度时的字号)

**Comment by zhetengbiji** [comment]
已支持 https://uniapp.dcloud.io/collocation/pages?id=globalstyle

**Comment by ctforcp** [comment]
nice
