### ISSUE TITLE
编译为H5  怎样才能像app一样出现顶部标题栏

### ISSUE THREAD

**Issue by VICTORYGS** [dcloudio/uni-app#187]
![image](https://user-images.githubusercontent.com/33747619/51956535-fd910980-2482-11e9-86b8-774180da0538.png)

**Comment by xiaoyucoding** [comment]
默认都是有导航栏的，相关的配置请参考文档：[https://uniapp.dcloud.io/collocation/pages?id=h5](https://uniapp.dcloud.io/collocation/pages?id=h5)
