### ISSUE TITLE
如果我想实现应用内换肤功能，有什么好的实现方式

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#1876]
如题。应用内换肤。想看看有什么好的实现方式。

**Comment by Tron1234** [comment]
我已经实现，通过vuex控制当前颜色，然后将配色方案存储到一个json文件，再通过vuex控制当前配色方案

**Comment by wakaryry** [comment]
@Tron1234 我在想，能不能使用某个方式，重新加载整个app的全局css。试图避开vuex

**Comment by Tron1234** [comment]
重新加载的话用户应该会有感知的吧，我目前tabBar以及全局样式是通过vuex控制颜色的，如果是某一个页面上换颜色是通过json的配色文件



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "wakary"; 
发送时间: 2020年7月7日(星期二) 晚上6:18
收件人: "dcloudio/uni-app";
抄送: "Tron1234"<506980247@qq.com>;"Mention";
主题: Re: [dcloudio/uni-app] 如果我想实现应用内换肤功能，有什么好的实现方式 (#1876)





 
@Tron1234 我在想，能不能使用某个方式，重新加载整个app的全局css。试图避开vuex
 
&mdash;
