### ISSUE TITLE
H5端ios平台input textarea focus无效问题

### ISSUE THREAD

**Issue by Tron1234** [dcloudio/uni-app#1878]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
我知道是ios端苹果的限制问题，也看了官方源码，focus()事件在ios上需要通过其他点击事件，通过监听点击事件再给input设置focus()才有效，求官方给个解决办法，老板逼死人

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**

H5端ios平台input focus属性有效

**实际结果**

H5端ios平台input focus属性无效

**系统信息:**
 - 发行平台: H5 App
 - 操作系统  ios13.5
 - HBuilderX版本 2.7.9.20200527
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 iphone8

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
部分现代浏览器设定有用户交互时才可以获取焦点，目前没有其他办法。
