### ISSUE TITLE
H5 IDE运行和 发布后样式编译不一致

### ISSUE THREAD

**Issue by CR903** [dcloudio/uni-app#188]
**问题描述**

在样式中添加条件编译，出现偏差

**复现步骤**

样式写法如下：
![image](https://user-images.githubusercontent.com/7643647/52037284-8c785180-2569-11e9-800c-3ba9d236c53c.png)

**预期结果**
预期发布和运行后得到的结果应该是一致的

**实际结果**
在运行中得到的结果是：
![image](https://user-images.githubusercontent.com/7643647/52037355-bfbae080-2569-11e9-8211-9b60be7a9f99.png)

在发布后的结果是：
![image](https://user-images.githubusercontent.com/7643647/52037404-dfea9f80-2569-11e9-8dd1-ccf073d87e1c.png)

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 macos
 - HBuilderX版本 1.5.4.20190127

**Comment by fxy060608** [comment]
已确认，下个版本修复此问题

**Comment by xiaoyucoding** [comment]
1.7.0 已更新并修复此问题
