### ISSUE TITLE
安卓平台支付宝小程序使用uni.request无法返回想要的数据 打印状态为abort

### ISSUE THREAD

**Issue by yclnycl** [dcloudio/uni-app#1883]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
安卓平台支付宝小程序使用uni.request无法返回想要的数据 打印状态为abort
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
![image](https://user-images.githubusercontent.com/25178232/86779261-f0237a00-c08d-11ea-86f5-d80d8af945c8.png)

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
希望可以返回数据
**实际结果**
[这里请贴上你的报错截图或文字]
实际上安卓支付宝小程序不会返回任何数据,ios平台正常 代码如上图所示封装,真机打印调试的时候发现状态为abort

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by hbcui1984** [comment]
你可以直接使用支付宝原生代码测试一下，如：`my.request`

**Comment by Otto-J** [comment]
最新版本未能复现问题，可能 uniapp 已修复你的问题。如果你发现仍有问题，请留言 reopen 或者新开 issue 艾特我
