### ISSUE TITLE
发布为H5，打包后只有一个index.html入口文件，如何直接多路径访问

### ISSUE THREAD

**Issue by sunscheung** [dcloudio/uni-app#1884]
**问题描述**
1.开发时，访问不同模块：
http://localhost:8080/#/
http://localhost:8080/#/pagesA/select?id=1
http://localhost:8080/#/pagesB/baseInfo

```
├─pages
│  └─index
├─pagesA
   └─select
├─pagesB
   └─baseInfo
```
2.发布为H5，打包后只有一个index.html入口文件，（unpackage\dist\build\h5\index.html）
 如何像开发模式下这样直接通过url访问不同模块？
http://localhost:8080/#/pagesA/select?id=1
http://localhost:8080/#/pagesB/baseInfo

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**Comment by dcloudhdx** [comment]
manifest.json 路由配置
1. hash 模式同本地调试
2. history 模式需要服务器端配置，参考 https://router.vuejs.org/zh/guide/essentials/history-mode.html
