### ISSUE TITLE
小程序开发无法热更新

### ISSUE THREAD

**Issue by geminate** [dcloudio/uni-app#189]
**问题描述**
使用 vue-cli 创建空项目后，dev模式运行，修改代码后，微信小程序中按钮点击事件失效。

**复现步骤**
[复现问题的步骤]
1.  使用 vue-cli 创建空项目
2.  页面中添加一个按钮并添加点击事件，dev模式编译微信小程序
3.  修改事件方法(例如在方法里添加一个console.log)，小程序IDE自动重新加载，但按钮点击失效

**预期结果**
热更新正常的话，按钮点击效果应该是正常的

**实际结果**
按钮无点击效果且无报错

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: 微信小程序IDE + Webstorm

**补充信息**
类似的 issue #86 

![5](https://user-images.githubusercontent.com/13115559/52039940-d9abf180-2570-11e9-80e0-4f1a3f2e39c3.gif)

**Comment by geminate** [comment]
原因找到了，第一次编译之后 index.vue.wxml 
`<template name="336bf41e"><view class="_div data-v-336bf41e page-index page-container"><button bindtap="handleProxy" data-eventid="{{'5Vq-0'}}" data-comkey="{{$k}}" class="_button data-v-336bf41e">测试页</button></view></template>`

按钮的 data-eventid 是 5Vq-0，和 index.js 里
`var render = function() {
  var _vm = this
  var _h = _vm.$createElement
  var _c = _vm._self._c || _h
  return _c(
    "div",
    { staticClass: "page-index page-container" },
    [
      _c(
        "button",
        { attrs: { eventid: "5Vq-0" }, on: { click: _vm.toHttpPage } },
        [_vm._v("测试页")]
      )
    ],
    1
  )
}
var staticRenderFns = []
render._withStripped = true`
可以对应上。

dev 模式下修改代码，热更新后，index.js 中的 eventid 发生了变化，但是 index.vue.wxml 中的 eventid没有跟随更新。

**Comment by fxy060608** [comment]
更新最新版本HBuilderX(1.5.4)，已修复此问题
