### ISSUE TITLE
自动化测试报错，我不知道该在哪里配置微信开发者工具地址

### ISSUE THREAD

**Issue by 2234839** [dcloudio/uni-app#1891]
**问题描述**
我在尝试自动化测试，创建了官方最新的 hello uni-app 项目 然后运行 测试 报错

```
Wechat web devTools not found, please specify executablePath option
```

我不知道该在哪里配置微信开发者工具地址，在 https://uniapp.dcloud.io/collocation/auto/quick-start 的文档上也没有找到

**复现步骤**

1.  创建了官方最新的 hello uni-app 项目
2. 运行 npm run test:mp-weixin

**预期结果**

正常测试

**实际结果**

![图片](https://user-images.githubusercontent.com/28727933/86987859-96c06580-c1c9-11ea-9b08-ef0b70072305.png)

**系统信息:**
版本: 1.47.0-insider (system setup)
提交: 59c7cbcf15745e4a8adb4fc59b63aa93f14d3cc3
日期: 2020-07-08T04:16:37.474Z
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.18363

**Comment by fxy060608** [comment]
https://uniapp.dcloud.io/collocation/auto/quick-start?id=jestconfigjs
//默认查找路径
Windows:  C:/Program Files (x86)/Tencent/微信web开发者工具/cli.bat
MacOS:  Applications/wechatwebdevtools.app/Contents/MacOS/cli
```
testEnvironmentOptions:{
'mp-weixin':{
executablePath:'微信开发者工具路径'
}
}
```

**Comment by 2234839** [comment]
> 
> 
> https://uniapp.dcloud.io/collocation/auto/quick-start?id=jestconfigjs
> //默认查找路径
> Windows: C:/Program Files (x86)/Tencent/微信web开发者工具/cli.bat
> MacOS: Applications/wechatwebdevtools.app/Contents/MacOS/cli
> 
> ```js
> testEnvironmentOptions:{
> 'mp-weixin':{
> executablePath:'微信开发者工具路径'
> }
> }
> ```

我的微信web开发者工具 装在了其他地方，现在我jest.config.js 的配置为

```
module.exports = {
  globalTeardown: "@dcloudio/uni-automator/dist/teardown.js",
  testEnvironment: "@dcloudio/uni-automator/dist/environment.js",
  testEnvironmentOptions: {
    "mp-weixin": {
      executablePath: "‪D:/app2/wxtool/cli.bat",
    },
  },
  testTimeout: 15000,
  reporters: ["default"],
  watchPathIgnorePatterns: ["/node_modules/", "/dist/", "/.git/"],
  moduleFileExtensions: ["js", "json"],
  rootDir: __dirname,
  testMatch: ["<rootDir>/src/**/*test.[jt]s?(x)"],
  testPathIgnorePatterns: ["/node_modules/"],
};

```

![图片](https://user-images.githubusercontent.com/28727933/86989135-5adacf80-c1cc-11ea-9a6d-caf95d8dbe09.png)


运行仍然报错
![图片](https://user-images.githubusercontent.com/28727933/86989174-6cbc7280-c1cc-11ea-98a0-3d81cf7dc597.png)

**Comment by 2234839** [comment]
我在另一台 微信开发者工具装在默认目录的 电脑上尝试成功了

**Comment by dcloudhdx** [comment]
按照你电脑的磁盘目录测试正常
请验证下命令行调用微信开发者是否正常
参考文档 https://developers.weixin.qq.com/miniprogram/dev/devtools/cli.html

**Comment by 2234839** [comment]
> 
> 
> 按照你电脑的磁盘目录测试正常
> 请验证下命令行调用微信开发者是否正常
> 参考文档 https://developers.weixin.qq.com/miniprogram/dev/devtools/cli.html

我可以确定该路径是可用的，因为我写过微信自动化生成二维码的脚本有用到该 cli.bat , 现在我已经将我电脑上的微信开发者工具装到默认目录了，运行成功

**Comment by fxy060608** [comment]
命令行执行，node，进入后，执行：`fs.existsSync('‪D:/app2/wxtool/cli.bat')` 看看返回什么

**Comment by 2234839** [comment]
> 
> 
> 命令行执行，node，进入后，执行：`fs.existsSync('‪D:/app2/wxtool/cli.bat')` 看看返回什么

false, 我找到原因了，这段 字符串前面不知道多了个什么字符
![图片](https://user-images.githubusercontent.com/28727933/86992327-d8560e00-c1d3-11ea-955e-f99fff2e9918.png)
非常感谢两位的回答，另外提个建议在 https://uniapp.dcloud.io/collocation/auto/quick-start 文档中能否提一下微信开发者工具的路径配置

**Comment by 2234839** [comment]
![图片](https://user-images.githubusercontent.com/28727933/86992468-1f440380-c1d4-11ea-939b-5c66d7c3aaf1.png)
我在这里复制的路径导致前面有个奇怪字符
