### ISSUE TITLE
onShareTimeline 编译后被移除

### ISSUE THREAD

**Issue by galenyuan** [dcloudio/uni-app#1892]
**问题描述**
参考 https://developers.weixin.qq.com/minigame/dev/api/share/wx.onShareTimeline.html
微信小程序昨天支持的 onShareTimeline，但测试后发现编译后会被 uni-app 移除

**复现步骤**
页面增加 onShareTimeline 然后查看编译后的代码

[或者可以直接贴源代码]

**预期结果**
不被移除

**实际结果**
被移除

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
#1880
