### ISSUE TITLE
请修复这个通过vue/cli构建的项目由于sass-loader v7+版本之后将data改为prependData导致的构建问题，目前可以通过安装sass-loader7+，node-sass 4.12.0来暂时解决这个问题

### ISSUE THREAD

**Issue by luvletterldl** [dcloudio/uni-app#1893]
![image](https://user-images.githubusercontent.com/26115291/87013066-af963e80-c1fc-11ea-87cd-260e343571e0.png)

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/1861
