### ISSUE TITLE
[bug]android10 uni.reLaunch在键盘弹出时会导致应用闪退

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#1895]
- nvue页面；
- 在Android10：uni.reLaunch导致app奔溃掉；
- 不报错；
- iOS正常，mp正常，H5正常；
- 手机华为p40；

# 测试结果

- 键盘弹出时，relaunch会导致app闪退；
- 键盘弹出时，调用uni.hideKeyboard，然后直接relaunch也会闪退；
- 键盘弹出时，必须给relaunch加一个延时才能正常relaunch，延时过短也可能奔溃；

# 测试代码

[relaunchTest.zip](https://github.com/dcloudio/uni-app/files/4906544/relaunchTest.zip)

**Comment by dcloudhdx** [comment]
Bug已确认

**Comment by dcloudhdx** [comment]
HBuilderX 2.8.1+ alpha 版已修复
