### ISSUE TITLE
如何动态修改page里边的背景颜色

### ISSUE THREAD

**Issue by YUANZHICHENG118** [dcloudio/uni-app#1896]
**问题描述**
[问题描述：做主题切换的时候，想动态修改page的background-color]
page {
	background-color: $uni-bg-color-dark;
	font-size: 28rpx;
}

如何动态需改这里的背景颜色，如果不可以修改，可否给一个做主题切换的思路，谢谢

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by wakaryry** [comment]
目前基本上都是采用vuex来做控制的

**Comment by wakaryry** [comment]
https://github.com/dcloudio/uni-app/issues/1876

**Comment by YUANZHICHENG118** [comment]
vuex 实现页面元素主题已经可以了，现在的问题是给page 设置了这个样式page {
background-color: $uni-bg-color-dark;
font-size: 28rpx;
} 但是这个background-color 好像不能动态修改，想请教下有没有什么办法可以修改这个background-color

**Comment by wakaryry** [comment]
这个 page 的没有控制入口。除非是可以动态加载css文件。

**Comment by YUANZHICHENG118** [comment]
动态加载css 怎么搞，有例子吗？谢谢

**Comment by 2234839** [comment]
> 
> 
> 动态加载css 怎么搞，有例子吗？谢谢

小程序是不能动态加载css的

**Comment by wakaryry** [comment]
没有。建议你不要使用这个page来控制背景色。因为他不可配置。
