### ISSUE TITLE
uniapp中引入colorui运行到app上样式混乱

### ISSUE THREAD

**Issue by cszmzh** [dcloudio/uni-app#1897]
问题描述：
我在uniapp中创建colorui的项目模板，运行到真机安卓上发现样式是错乱的。而在小程序和h5端样式都是正常的，请问是colorui不支持app端的问题嘛？

**Comment by d1y** [comment]
麻烦发下详细代码，或者流程

**Comment by BA-NANA** [comment]
> 麻烦发下详细代码，或者流程

你好，我似乎发现问题所在了，我在win平台使用hbuilderX运行到真机是没有问题的，但我在mac平台下运行到安卓真机会出现样式错误的情况，小程序和hbuilderX我都是安装官方最新的稳定版

**Comment by BA-NANA** [comment]
> 麻烦发下详细代码，或者流程

就是直接使用hbuilderX建立一个新的uniapp项目，选择ColorUI模板，然后直接运行到真机

**Comment by d1y** [comment]
混乱是啥样子, 截个图看看, 真机绝对支持的, 不知道你是哪个环节出了问题

**Comment by BA-NANA** [comment]
> 混乱是啥样子, 截个图看看, 真机绝对支持的, 不知道你是哪个环节出了问题


我是直接使用官方提供的colorui模板，没有进行任何修改
![1](https://user-images.githubusercontent.com/45927088/87241312-7bb55600-c454-11ea-8076-72cf667b1226.png)
第一张图是在小程序里正常运行的界面，第二张图是安卓手机上运行的界面
![2](https://user-images.githubusercontent.com/45927088/87241320-8cfe6280-c454-11ea-8278-2f657ca22566.jpg)

**Comment by d1y** [comment]
代码打个包发来看看
