### ISSUE TITLE
nvue map组件 circles属性在ios端上无法设置透明背景色，安卓正常，vue正常

### ISSUE THREAD

**Issue by liuhaofei** [dcloudio/uni-app#1898]
nvue map组件 circles属性在ios端上设置不了透明背景色，安卓正常，vue正常

**Comment by dcloudhdx** [comment]
是否使用了十六进制透明色？iOS仅支持 rgb/rgba
参考文档 https://uniapp.dcloud.net.cn/component/map

**Comment by dcloudhdx** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues

**Comment by chaffererdog** [comment]
使用十六进制颜色 + alpha 通道的方式，不要使用rgba
如 #RRGGBBAA，其中 AA 是透明度（00 完全透明，FF 完全不透明）。

circles: [
  {
    latitude: mapData[6].latitude,
    longitude: mapData[6].longitude,
    radius: 500,
    color: '#FF000019',  // 红色，透明度 ~10%（0x19 ≈ 0.1）
    fillColor: '#FF000019'
  }
]
透明度计算：

0.1 透明度 ≈ 0.1 * 255 ≈ 26（十进制）→ 十六进制 0x19。

例如：rgba(255,0,0,0.5) → #FF000080（0x80 = 128）。
