### ISSUE TITLE
vue create -p dcloudio/uni-preset-vue#alpha my-alpha-project  报错

### ISSUE THREAD

**Issue by smallsix99** [dcloudio/uni-app#1902]
![image](https://user-images.githubusercontent.com/33114274/87276105-39eae500-c512-11ea-965e-93d24c9b5db7.png)

npm install 其它包是OK的

**Comment by hbcui1984** [comment]
github上图裂了，看不到，要不你到 ask.dcloud.net.cn 发帖吧。

**Comment by zhetengbiji** [comment]
晚点请重试，CLI 的模板在 github 上，github 响应了 500 状态码
