### ISSUE TITLE
radio标签无法直接使用scss

### ISSUE THREAD

**Issue by 419572718** [dcloudio/uni-app#1904]
**问题描述**
radio中的color属性，无法直接使用scss的颜色。

**复现步骤**
`<radio class="check s-check-color" :checked="checked" color="$s-color-active" />`

**预期结果**
![image](https://user-images.githubusercontent.com/68269600/87395858-96b6d000-c5e4-11ea-8c16-a91203bccf24.png)

**实际结果**
![image](https://user-images.githubusercontent.com/68269600/87395915-afbf8100-c5e4-11ea-8dc3-52b469559726.png)

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 : 
 - HBuilderX版本 HBuilderX 2.7.14.20200618
 - uni-app版本
 - 设备信息

**Comment by bfc846958672** [comment]
不支持这种方式
