### ISSUE TITLE
H5 uni.getLocation 无法获取定位

### ISSUE THREAD

**Issue by xiejibiao** [dcloudio/uni-app#1908]
**问题描述**
在google 浏览器 和微信 网页使用 uni.getLocation 方法获取定位，在UC 浏览器，夸克浏览器使用正常

**复现步骤**
test: function () {
	let _this = this
	uni.getLocation({
	type: 'wgs84',
	 success: function (res) {
		_this.longitude = res.longitude
		_this.latitude = res.latitude
	},
	fail:function(res){
		_this.msg = res
	}
});
}

**系统信息:**
H5平台
 - 发行平台: H5平台
 - 操作系统 Android 9.0+
 - HBuilderX版本 2.7.14
 - uni-app版本 v2.7.14
 - 设备信息 华为P20pro

**Comment by zhetengbiji** [comment]
看文档
