### ISSUE TITLE
在苹果手机上调试

### ISSUE THREAD

**Issue by VICTORYGS** [dcloudio/uni-app#191]
一直在转圈, 最后黑屏 退出了 Hbuilder
![image](https://user-images.githubusercontent.com/33747619/52098931-fc3f1880-260b-11e9-96ef-1991e2464210.png)

**Comment by yuxianwen** [comment]
文档都讲了，如果没有更新数据，需要强制结束程序重新打开

**Comment by hbcui1984** [comment]
手机上杀掉进程，重新运行试试

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
