### ISSUE TITLE
增加unicloud云数据库findAndModify方法

### ISSUE THREAD

**Issue by AlexStacker** [dcloudio/uni-app#1914]
**新功能描述**
增加mongo的`findAndModify`等方法。

**现状及问题**
mongo本身提供了 `findAndModify` 等原子操作的方法，可以返回修改后的值，这样可以在一些特殊场景使用使用，比如最近碰到的需要实现排队叫号生成不重复的号码。现有的云数据库不支持 `findAndModify` 这个方法。`update`方法返回的信息太少不能解决问题。

**尝试方案**
增加`findAndModify`方法或者可以通过传递参数的方式在`update`后返回修改后的值。

**补充信息**

**Comment by Wangyaqi** [comment]
腾讯云阿里云均已支持[updateAndReturn](https://uniapp.dcloud.net.cn/uniCloud/cf-database?id=update-and-return)
