### ISSUE TITLE
picker组件第一次打开后选中值等滑动结束后，点击遮罩层关闭弹框，再次打开弹框显示值显示有问题

### ISSUE THREAD

**Issue by zbjy** [dcloudio/uni-app#192]
picker组件第一次打开后，通过滑动选中值等滑动结束后，点击遮罩层关闭弹框，再次打开弹框后选中的值不正确
![image](https://user-images.githubusercontent.com/19985529/52105491-e5a7ba00-2629-11e9-9fbf-471aa73e254f.png)

**Comment by xiaoyucoding** [comment]
1.7.0 已更新并修复此问题

**Comment by chenwen992003** [comment]
软件更新还是存在这个问题。关闭后，再次打开时，选中值永远都是第一项

**Comment by chenwen992003** [comment]
> 1.7.0 已更新并修复此问题

软件更新还是存在这个问题。关闭后，再次打开时，选中值永远都是第一项

**Comment by zhetengbiji** [comment]
> > 1.7.0 已更新并修复此问题
> 
> 软件更新还是存在这个问题。关闭后，再次打开时，选中值永远都是第一项

你说的“问题”和原问题并不相同
你说的“问题”应该是指的是动画惯性较大，选中值较慢的问题（肉眼看到选中了，实际值还未变化中），此问题将在后期改善。

**Comment by chenwen992003** [comment]
> > > 1.7.0 已更新并修复此问题
> > 
> > 
> > 软件更新还是存在这个问题。关闭后，再次打开时，选中值永远都是第一项
> 
> 你说的“问题”和原问题并不相同
> 你说的“问题”应该是指的是动画惯性较大，选中值较慢的问题（肉眼看到选中了，实际值还未变化中），此问题将在后期改善。

第一次打开选中2020年4月7日，关闭后，再次打开时，选中值一直都是2014年1月1日
![微信图片_20190315104930](https://user-images.githubusercontent.com/48112634/54405153-a2ecfd80-4710-11e9-87ba-da92591d2275.png)

**Comment by zhetengbiji** [comment]
> > > > 1.7.0 已更新并修复此问题
> > > 
> > > 
> > > 软件更新还是存在这个问题。关闭后，再次打开时，选中值永远都是第一项
> > 
> > 
> > 你说的“问题”和原问题并不相同
> > 你说的“问题”应该是指的是动画惯性较大，选中值较慢的问题（肉眼看到选中了，实际值还未变化中），此问题将在后期改善。
> 
> 第一次打开选中2020年4月7日，关闭后，再次打开时，选中值一直都是2014年1月1日
> ![微信图片_20190315104930](https://user-images.githubusercontent.com/48112634/54405153-a2ecfd80-4710-11e9-87ba-da92591d2275.png)

此问题和原问题并不相同，请勿合并，需开启新的issue
