### ISSUE TITLE
用Hbuilder模板创建支付宝小程序 不能使用onTitleClick函数 

### ISSUE THREAD

**Issue by WjingMin** [dcloudio/uni-app#1922]
用Hbuilder模板创建支付宝小程序 不能使用onTitleClick函数  无法监听标题栏点击事件

**Comment by Otto-J** [comment]
https://uniapp.dcloud.net.cn/tutorial/page.html#onnavigationbarbuttontap 文档标注了对应兼容性。如果仍有问题，请 reopen 或者新开 issue 艾特我。
