### ISSUE TITLE
关于框架优化

### ISSUE THREAD

**Issue by githublyp** [dcloudio/uni-app#1924]
**新功能描述**
1、对于uniCloud的精简，比如我只有阿里云云，就不需要腾讯相关api，但是uniCloud还有多余功能代码，而且unicloud越来越大，会占用发行包体积？
2、框架构建接口的开放，对于通用的构建步骤能放开钩子函数吗，方便我我们扩展。
3、什么时候可以支持懒加载呢

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by Wangyaqi** [comment]
目前除去阿里云和腾讯云公用逻辑之外两个云厂商的包体积并不大，后续如果补充功能引起包体积变大的话会考虑分离客户端sdk
