### ISSUE TITLE
在view上写的属性，编译后该属性消失了

### ISSUE THREAD

**Issue by huangyunshen** [dcloudio/uni-app#1925]
**问题描述**
我在view组件上写了个属性contenteditable，但是编译到字节跳动小程序后，该属性在节点上找不到了，然后我在开发者工具中强行把改节点的contenteditable属性写上，发现该属性是可以正常使用的，不明白在编译的过程为什么给去掉。

<view
      class="edit-box"
      contenteditable="true"
      @focus="handleFocus"
      @blur="handleBlur"
      @input="handleInput"
      @change="handleChange"
 ></view>

**Comment by dcloudhdx** [comment]
`uni-app` 编译时不会去掉这个属性，看编译后文件 `contenteditable` 还在，编译输出目录 `unpackage\dist\dev\mp-toutiao\...`
应该是字节跳动小程序解析时过滤掉了
