### ISSUE TITLE
忽略特定样式不转成rpx

### ISSUE THREAD

**Issue by xlm2017** [dcloudio/uni-app#1926]
manifest.json中配置了 "transformPx" : true,之后, 会将css样式中的px转成rpx, 
能否设计成某些带ignore-的前缀的css样式忽略转换, 或者css属性忽略转换?

**Comment by zhetengbiji** [comment]
自动转换 px 为 rpx 已不再推荐使用，提供配置是为了兼容历史项目。后期不再推荐自动转换，如非 nvue 页面限制场景，在不同情况有不同的单位适合。

如有特殊需求可以尝试自行配置 vue.config.js
