### ISSUE TITLE
InnerHTML的XSS攻击漏洞问题

### ISSUE THREAD

**Issue by lynnhawk** [dcloudio/uni-app#1927]
我们利用uni-app开发的应用，在进行安全扫描时，发现了InnerHTML的XSS攻击漏洞的高危漏洞。主要涉及到的文件都是框架打包发布时加入的自带代码：
1.
[文件]：
/assets/uni-jsframework.js
/assets/data/wap2app/__wap2apptabbar.js

[代码片段]：
I(i=a)&&I(i=i.domProps)&&I(i=i.innerHTML)){if(i!==e
)){if(i!==e.innerHTML)return!1}else{for(var c=!0,u=e.firstChi
。。。。。。。。。
 

请问我该如何解决？
谢谢

**Comment by zhetengbiji** [comment]
InnerHTML 为框架中使用到的方法，实际无相关安全问题，可忽略。

**Comment by Jvaeyhcd** [comment]
> InnerHTML 为框架中使用到的方法，实际无相关安全问题，可忽略。

但是安全检查这一项过不了怎么办呢？有没有什么办法处理下呢？

**Comment by flingyp** [comment]
这个应该怎么解决呢？
