### ISSUE TITLE
npm引入vant/weapp 小程序找不到component

### ISSUE THREAD

**Issue by Rayzworld** [dcloudio/uni-app#1929]
**问题描述**
我在uniapp通过引入vant-weapp出现了些问题
我npm i @vant/weapp 在usingComponents配置了vant weapp组件
"usingComponents": {
	// "van-button": "@vant/weapp/button"
}
也尝试了换成绝对路径 或者不在usingcomponents配置 在page中import引入等
小程序上一直找不到路径 Component is not found in path "@vant/weapp/button"

查到的解决方案不是很符合预期 **搜索结果多是18年的 采用了把npm包copy到wxcomponents的方式 
不清楚是当时的uniapp不支持npm还是现在引入vant也只能这么解决** 

Any help is much appreciated

**预期结果**
小程序能直接使用uniapp的npm安装的vant

**系统信息:**
 - 发行平台: [如 微信小程序]
 - HBuilderX版本 [2.8.1.20200721-alpha]

**Comment by zhetengbiji** [comment]
目前文档里写的是：小程序组件需要放到指定目录
