### ISSUE TITLE
uni.createInnerAudioContext设置网络音频第一次不播放声音

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#1931]
测试环境：微信小程序，nvue页面，真机调试。

```
const a = uni.createInnerAudioContext()
// a.autoplay = true
a.src = 'your src in net'
// a.play()
```

设置一个src的时候，如果这个src没有播放过，就不会发声。需要第二次设置为这个src的时候才发声。

大概问题就是，没有下载过的src，下载之后不会自动播放声音。

`autoplay`或者手动`play`都有问题。

在小程序开发者工具上面没有问题。真机测试就有了问题。

难道需要我播放之前把每一个音频文件下载一遍？

即使我监听onCanplay第一次也没有声音。

**Comment by dcloudhdx** [comment]
用微信原生小程序验证是否有同样问题

**Comment by wakaryry** [comment]
原生测试了第一次播放报错： `errCode:62, err:load or init native decode so fail`。

第二次播放就可以播放。

**Comment by 1014156094** [comment]
+1
