### ISSUE TITLE
Function(...) is not a function

### ISSUE THREAD

**Issue by fangxingguang** [dcloudio/uni-app#1932]
**问题描述**
最新版Hbuildx2.8.1
微信开发者工具勾选“es6转es5”
开发调试正常，发布到微信小程序报错（版本库选择2.10.4或者之前的版本），导致页面无法显示

VM22:1 thirdScriptError
Function(...) is not a function
TypeError: Function(...) is not a function

![image](https://user-images.githubusercontent.com/2920129/88250511-681eb080-ccda-11ea-957f-f2359a106af2.png)

**复现步骤**
[复现问题的步骤]
1.  发行到微信小程序
2. 微信开发者工具切换版本库到2.10.4
3. 微信开发者工具勾选“es6转es5”
4. 查看报错

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本: HBuilderX2.8.1
 - 微信开发者工具版本: 1.03.2007212

**Comment by dcloudhdx** [comment]
当前版本解决方案，参考这个回复 https://ask.dcloud.net.cn/question/101714

**Comment by dcloudhdx** [comment]
HBuilderX 2.8.2+ alpha 已修复
