### ISSUE TITLE
调用api "setClipboardData" 失败

### ISSUE THREAD

**Issue by oldpotter** [dcloudio/uni-app#194]
**问题描述**
调用api "setClipboardData" ，控制台报错

**复现步骤**
```
							uni.setClipboardData({
								data: 'hello',
								success() {
									
								}
							})
```

**实际结果**
![image](https://user-images.githubusercontent.com/13828653/52520989-7e35de00-2cab-11e9-9ccb-1008db661b11.png)

**Comment by xiaoyucoding** [comment]
哪个平台？H5 平台是不支持这个 API 的。
