### ISSUE TITLE
HBuilderX 莫名崩溃

### ISSUE THREAD

**Issue by 18279493170** [dcloudio/uni-app#1940]
最近使用HBuilderX 开发微信小程序时，HBuilderX在出现点击文档结构显示错乱（编辑界面焦点不是点击的焦点位置，显示其他地方）时，过一会儿百分百会闪退，一天下来最少十几次，严重拖慢开发进度，希望能够重视这个问题并尽早解决更新
当前工具2.7.14.20200618最新版

**Comment by HeyChiang** [comment]
+1，最近遇到了同样的问题

**Comment by fuxianwei** [comment]
+1 今天闪退了4次

**Comment by 18279493170** [comment]
更新版本依旧崩，当前  2.8.3.20200728

**Comment by 18279493170** [comment]
还没解决。。。心累

**Comment by yi-heng** [comment]
1. 提供下电脑操作系统信息、HBuilderX版本
2. 请详细描述下崩溃之前进行的操作
3. 如是windows, 崩溃后，进入HBuilderX bin目录下，看下是否存在dmp文件。如存在，提供下dmp文件。

**Comment by 18279493170** [comment]
pc: win 10
HBuilderx:&nbsp;2.8.3.20200728
崩溃操作：一般在进行copy操作以及打开文档结构图的时候闪崩频繁，日常使用只要不是打开太多文件都不会太频繁，尤其当点击文档结构显示到其他非点击结构处时，百分百闪退
bin文件夹下午dmp文件
望处理，严重拖慢开发进度




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "yi-heng"<notifications@github.com&gt;; 
发送时间: 2020年8月4日(星期二) 上午10:52
收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 
抄送: "；；毅；；；"<1178308665@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [dcloudio/uni-app] HBuilderX 莫名崩溃 (#1940)





  
提供下电脑操作系统信息、HBuilderX版本
 
请详细描述下崩溃之前进行的操作
 
如是windows, 崩溃后，进入HBuilderX bin目录下，看下是否存在dmp文件。如存在，提供下dmp文件。

**Comment by yi-heng** [comment]
文档结构图的问题，2.8.4-alpha已修复。近期会推到正式版。
