### ISSUE TITLE
uni.setStorage 之后跳转  报错：cid unmatched [object Object]，加延时正常

### ISSUE THREAD

**Issue by ldc2726** [dcloudio/uni-app#1941]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
![image](https://user-images.githubusercontent.com/34648806/88454945-0494ae80-cea5-11ea-8525-9c571e12a283.png)
app为什么必须要加个延时，才能正常存储跳转，h5和小程序都是正常的。
如果不做延迟直接跳转就会报错误，而且没有存储进去。
uni.setStorage(OBJECT)
uni.setStorageSync(KEY,DATA)
都不行
**复现步骤**
[复现问题的步骤]
1.登录页进行uni.setStorage(OBJECT)或uni.setStorageSync(KEY,DATA)存储；
2.uni.switchTab直接跳转到tab首页
3.报错
[或者可以直接贴源代码]

**预期结果**
正常跳转

**实际结果**

![image](https://user-images.githubusercontent.com/34648806/88455047-2d1ca880-cea5-11ea-961f-a112510ceb94.png)

**系统信息:**
 - 发行平台: [App]
 - 操作系统 [如 iOS 12.4.1]
 - HBuilderX版本 [2.7.14]
 - uni-app版本 [HBuilderX直接构建]
 - 设备信息 [ iPhone8 Plus]

**补充信息**
[可选]
app端存储可能有问题，success结果返回时没有真正的正确存储完毕，导致的报错，不然怎么加了一秒的延时就正常了呢。

**Comment by ldc2726** [comment]
没有存储上的问题找到了，是因为我的key的名称叫  “token” ，不知道为什么死活存不上，换个名字就行了，可能是关键字吧，但是存储之后不延迟就跳转的话依然会有上述的控台报错

**Comment by githublyp** [comment]
同时经常报这个
[JS Framework] Failed to execute the callback function:
22:43:12.099  TypeError: undefined is not an object (evaluating 'modules[moduleId].call') __ERROR 

真不知道为什么每次框架更新都伴随着一大顿意外恐怖

**Comment by zhetengbiji** [comment]
> 同时经常报这个
> [JS Framework] Failed to execute the callback function:
> 22:43:12.099 TypeError: undefined is not an object (evaluating 'modules[moduleId].call') __ERROR
> 
> 真不知道为什么每次框架更新都伴随着一大顿意外恐怖@fxy060608 安卓没法webview调试

能否详细描述一下

**Comment by githublyp** [comment]
> > 同时经常报这个
> > [JS Framework] Failed to execute the callback function:
> > 22:43:12.099 TypeError: undefined is not an object (evaluating 'modules[moduleId].call') __ERROR
> > 真不知道为什么每次框架更新都伴随着一大顿意外恐怖@fxy060608 安卓没法webview调试
> 
> 应该是app分包优化导致的，分包页面经常报错，我关掉后 世界安静了
