### ISSUE TITLE
H5端发行报错：文件查找失败：'uni-platform/view/components/audio'

### ISSUE THREAD

**Issue by frylstar** [dcloudio/uni-app#1943]
**问题描述**

项目中有组件用到了audio组件，之前打包正常，更新到HbuilderX最新版本2.8.2.20200726出现该报错，
注释audio组件后打包正常
```
[HBuilder] 09:13:40.069 正在编译中...
[HBuilder] 09:16:14.591  INFO  Build optimizing...
[HBuilder] 09:16:14.596  DONE  Build complete. 
[HBuilder] 09:16:14.596 项目 'uniapp' 编译成功。
[HBuilder] 09:16:15.232 开始差量编译...
[HBuilder] 09:18:01.060  DONE  Build complete.
[HBuilder] 09:18:01.063 项目 'uniapp' 编译成功。
[HBuilder] 09:18:01.066 文件查找失败：'uni-platform/view/components/audio' at ..\Work\HbuilderX\HBuilderX\plugins\uniapp-cli\node_modules\@dcloudio\vue-cli-plugin-uni-optimize\.tmp\components.js:63
[HBuilder] 09:18:01.444 项目 'uniapp' 发布h5失败.
```

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [H5平台]
 - HBuilderX版本 [2.8.2.20200726]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
1.h5平台没有audio组件（可以条件编译）
2.你开启了摇树优化

**Comment by frylstar** [comment]
好的，那官方文档上是不是要更新下，目前显示H5平台支持
[audio](https://uniapp.dcloud.io/component/audio?id=audio)
![audio-docs](https://user-images.githubusercontent.com/36854177/88498648-4a14c100-cff6-11ea-88cc-faa36cd5b2ff.png)

**Comment by fxy060608** [comment]
> 好的，那官方文档上是不是要更新下，目前显示H5平台支持
> [audio](https://uniapp.dcloud.io/component/audio?id=audio)
> ![audio-docs](https://user-images.githubusercontent.com/36854177/88498648-4a14c100-cff6-11ea-88cc-faa36cd5b2ff.png)

刚才回复的不正确，H5支持audio组件，只是不建议使用，目前在启用摇树优化时会有问题，可以关闭摇树，或者使用其他api替换

**Comment by frylstar** [comment]
OK，了解了，谢谢~

**Comment by OctoberToEscape** [comment]
你这更新永远卡到5/6  然后最后一个更新不上来，咋办
