### ISSUE TITLE
dev 模式热更新代码后，出错错误

### ISSUE THREAD

**Issue by fuxianwei** [dcloudio/uni-app#1945]
**问题描述**
错误内容：
```
VM3292:1 MiniProgramError
Cannot read property 'call' of undefined
TypeError: Cannot read property 'call' of undefined
```

**复现步骤**
[复现问题的步骤]
修改代码以后，dev热更新出现错误，这个问题是随机出现，刷新小程序开发工具都没用，只能关闭dev服务并重新启动

**预期结果**
不再提示这个错误

**实际结果**

<img width="759" alt="截屏2020-07-27 12 38 47" src="https://user-images.githubusercontent.com/1736689/88504487-800e7100-d007-11ea-80a6-6fc266f85ed2.png">

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 : 2.8.2.20200726
 - 微信开发者工具：1.03.2006090
 - 设备信息 [如 iPhone xs max]

**Comment by fxy060608** [comment]
初步判断，热更新时，模块id生成异常，导致热更新生成的模块与旧模块不匹配导致，但因为无法稳定重现，导致很难排查解决

**Comment by fuxianwei** [comment]
> 初步判断，热更新时，模块id生成异常，导致热更新生成的模块与旧模块不匹配导致，但因为无法稳定重现，导致很难排查解决

复现频率还是挺高了，每次都要重启服务，严重影响开发效率了

**Comment by fxy060608** [comment]
> > 初步判断，热更新时，模块id生成异常，导致热更新生成的模块与旧模块不匹配导致，但因为无法稳定重现，导致很难排查解决
> 
> 复现频率还是挺高了，每次都要重启服务，严重影响开发效率了

可以发一个复现频率高的测试工程，运行环境，我们的同事，没人能重现该问题

**Comment by fuxianwei** [comment]
> > > 初步判断，热更新时，模块id生成异常，导致热更新生成的模块与旧模块不匹配导致，但因为无法稳定重现，导致很难排查解决
> > 
> > 
> > 复现频率还是挺高了，每次都要重启服务，严重影响开发效率了
> 
> 可以发一个复现频率高的测试工程，运行环境，我们的同事，没人能重现该问题

暂时也没法提供测试工程，我这里也是项目大了以后才出现的

**Comment by fxy060608** [comment]
hello uni-app可以重现吗？

**Comment by fuxianwei** [comment]
<img width="696" alt="截屏2020-07-27 16 18 17" src="https://user-images.githubusercontent.com/1736689/88519635-fd94aa00-d024-11ea-9c82-0418007eae41.png">

**Comment by fuxianwei** [comment]
> hello uni-app可以重现吗？

不能重现，这个问题是随着我们项目变大频率越高了，一直没找到复现规律

**Comment by fxy060608** [comment]
> > hello uni-app可以重现吗？
> 
> 不能重现，这个问题是随着我们项目变大频率越高了，一直没找到复现规律

好的， 我们弄一些复杂的项目，测试下，你的项目大约有多大？比如有多少个页面，发行后，小程序包体积是多大？

**Comment by fuxianwei** [comment]
> > > hello uni-app可以重现吗？
> > 
> > 
> > 不能重现，这个问题是随着我们项目变大频率越高了，一直没找到复现规律
> 
> 好的， 我们弄一些复杂的项目，测试下，你的项目大约有多大？比如有多少个页面，发行后，小程序包体积是多大？

你提供一个邮箱给我吧，我看能不能整理一个测试发给你

**Comment by fxy060608** [comment]
> > > > hello uni-app可以重现吗？
> > > 
> > > 
> > > 不能重现，这个问题是随着我们项目变大频率越高了，一直没找到复现规律
> > 
> > 
> > 好的， 我们弄一些复杂的项目，测试下，你的项目大约有多大？比如有多少个页面，发行后，小程序包体积是多大？
> 
> 你提供一个邮箱给我吧，我看能不能整理一个测试发给你

fengxiaoyun#dcloud.io(替换下#号)

**Comment by fuxianwei** [comment]
> > > > > hello uni-app可以重现吗？
> > > > 
> > > > 
> > > > 不能重现，这个问题是随着我们项目变大频率越高了，一直没找到复现规律
> > > 
> > > 
> > > 好的， 我们弄一些复杂的项目，测试下，你的项目大约有多大？比如有多少个页面，发行后，小程序包体积是多大？
> > 
> > 
> > 你提供一个邮箱给我吧，我看能不能整理一个测试发给你
> 
> fengxiaoyun#dcloud.io(替换下#号)

已发送，改几次文件，热更新编译几次就会复现问题

**Comment by fuxianwei** [comment]
这个问题热更新的时候也经常出现：

MiniProgramError
Cannot set property '_scopeId' of undefined
TypeError: Cannot set property '_scopeId' of undefined

**Comment by dcloudhdx** [comment]
使用提供的项目没有复现问题，请提供操作系统平台、微信开发者工具版本、基础库版本、修改时一般改些什么内容，是否有新增删除文件，修改组件名之类的，越详细越好

**Comment by fuxianwei** [comment]
> 使用提供的项目没有复现问题，请提供操作系统平台、微信开发者工具版本、基础库版本、修改时一般改些什么内容，是否有新增删除文件，修改组件名之类的，越详细越好

新增删除文件，或组件名我都会清空编译目录重启服务，刚刚试着重启了电脑目前也没再出现这个问题了
