### ISSUE TITLE
在h5中使用navigator组件问题

### ISSUE THREAD

**Issue by weiyunpeng** [dcloudio/uni-app#195]
**问题描述**

1. 在h5中使用navigator组件，open-type为"navigateBack"，此时将delta设置为1时会报：Expected Number with value 1, got String with value "1".

2. 触发该组件报：<navigator/> should have url attribute when using navigateTo, redirectTo, reLaunch or switchTab

<navigator  open-type="navigateBack" :delta="1"  hover-class="none"></navigator>

**预期结果**

希望navigator增加对navigateBack的支持

**Comment by fxy060608** [comment]
可以使用 :delta="1" 来启用类型转换

**Comment by weiyunpeng** [comment]
> 可以使用 :delta="1" 来启用类型转换

<navigator open-type="navigateBack" :delta="1" hover-class="none"></navigator>
我是这样写的   不管用

**Comment by fxy060608** [comment]
贴一下你的代码

**Comment by weiyunpeng** [comment]
```
<navigator
        class="action"
        open-type="navigateBack"
        :delta="1"
        hover-class="none"
        v-show="!isBar"
      >
        <text v-show="!isBar" class="icon-back"></text>
        {{name}}
      </navigator>
```

**Comment by weiyunpeng** [comment]
另外发现使用open-type="navigateBack"编译后uni-navigator上是没有该属性的，只有参考官方提供的示例那样直接navigateBack才管用。

**Comment by fxy060608** [comment]
已确认问题
1.delta 报类型错误，可以通过:delta来做类型转换
2.navigateBack，必须配置 url 的问题下个版本修复

**Comment by xiaoyucoding** [comment]
1.7.0 已更新并修复此问题

**Comment by weiyunpeng** [comment]
更新到最新版后，关于h5中的:delta="1",浏览器控制台依旧报：`Invalid prop: type check failed for prop "delta". Expected Number with value 1, got String with value "1".
`

**Comment by xiaoyucoding** [comment]
> 更新到最新版后，关于h5中的:delta="1",浏览器控制台依旧报：`Invalid prop: type check failed for prop "delta". Expected Number with value 1, got String with value "1". `

```html
<navigator :delta="1" open-type="navigateBack">back...</navigator>
```
HBuilderX 1.7.0.20190314
测试没有问题，如果依旧存在问题，请单独开一个 issue。
