### ISSUE TITLE
App端是否支持微信开放标签<wx-open-launch-app>？

### ISSUE THREAD

**Issue by bigBron** [dcloudio/uni-app#1952]
**新功能描述**
微信最近出了微信开放标签<wx-open-launch-app>，作用是在微信网页唤起App，目前是否支持此功能，或者有计划支持？

**相关链接**
https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/Wechat_Open_Tag.html
https://developers.weixin.qq.com/doc/offiaccount/OA_Web_Apps/APP_GET_EXTINF.html

**Comment by 2234839** [comment]
这个应该可以直接用的

**Comment by bigBron** [comment]
@2234839 最要是App获取开放标签<wx-open-launch-app>中的extinfo数据这块，不知道是否支持
