### ISSUE TITLE
[Bug report]升级版本后无法编译   编译报错Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by Smallwatermelon** [dcloudio/uni-app#1953]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
版本升级后目前版本是   ^2.0.0-28320200727001
编译报错
TypeError: Cannot read property 'id' of undefined
    at generateComponent (C:\Users\HP\111\node_modules\@dcloudio\webpack-uni-mp-loader\lib\plugin\generate-component.js:67:110)
    at C:\Users\HP\111\node_modules\@dcloudio\webpack-uni-mp-loader\lib\plugin\index-new.js:84:11    at new Promise (<anonymous>)
    at C:\Users\HP\111n\node_modules\@dcloudio\webpack-uni-mp-loader\lib\plugin\index-new.js:72:16    at _next1 (eval at create (C:\Users\HP\111\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:17)
    at eval (eval at create (C:\Users\HP\111\node_modules\tapable\lib\HookCodeFactory.js:33:10), 
<anonymous>:24:1)
    at C:\Users\HP\Desktop\111\node_modules\copy-webpack-plugin\dist\index.js:91:9
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

回退其他版本的代码可以 编译正常
同一代码 Mac 运行正常 window 重新拉代码 都无法 编译 一直编译报错Cannot read property 'id' of undefined
![image](https://user-images.githubusercontent.com/38370858/88751593-7eb98180-d18a-11ea-870c-8f47441da5ae.png)
**复现步骤**
[复现问题的步骤]
1.  yarn
2. 运行编译命令
3. 报错

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
正常编译
**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
yarn 1.22.4
node 12.18.3
unApp     ^2.0.0-28320200727001
 - 发行平台: [ 微信小程序]
 - 操作系统 [如 iOS 12.1.2、Android 7.0] window运行
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Smallwatermelon** [comment]
同一代码  Mac 运行正常    window  重新拉代码  都无法  编译  一直编译报错Cannot read property 'id' of undefined

**Comment by Smallwatermelon** [comment]
回退其他版本的代码可以  编译正常

**Comment by dcloudhdx** [comment]
1. 提供下 `node_modules@dcloudio\webpack-uni-mp-loader\lib\plugin\generate-component.js`  11-30行截图
2. 提供下 npm run info

**Comment by Smallwatermelon** [comment]
1.
2. "dev:mp-weixin": "cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch",

**Comment by Smallwatermelon** [comment]
> 1. 提供下`node_modules@dcloudio\webpack-uni-mp-loader\lib\plugin\generate-component.js`  11-30行截图

> 2. 提供下npm运行信息
npm run dev:mp-weixin

**Comment by Smallwatermelon** [comment]
> 1. 提供下`node_modules@dcloudio\webpack-uni-mp-loader\lib\plugin\generate-component.js`  11-30行截图
> 2. 提供下npm运行信息
npm run dev:mp-weixin:gulp

**Comment by Smallwatermelon** [comment]
> 1. 提供下`node_modules@dcloudio\webpack-uni-mp-loader\lib\plugin\generate-component.js`  11-30行截图
> 2. 提供下npm运行信息

**Comment by Smallwatermelon** [comment]
> 1. 提供下`node_modules@dcloudio\webpack-uni-mp-loader\lib\plugin\generate-component.js`  11-30行截图
> 2. 提供下npm运行信息
1、
![image](https://user-images.githubusercontent.com/38370858/88756230-b2e66f80-d195-11ea-9aeb-c0957263fa1a.png)
2、
先运行的这个npm run dev:mp-weixin:gulp
"dev:mp-weixin:gulp": "yarn init-app && yarn gulp-watch & yarn dev:mp-weixin",
![image](https://user-images.githubusercontent.com/38370858/88756368-0eb0f880-d196-11ea-9998-76a5f9fb6aef.png)

后运行的这个npm run dev:mp-weixin
"dev:mp-weixin": "cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch",
 
![image](https://user-images.githubusercontent.com/38370858/88756447-3ef89700-d196-11ea-9e77-517618aa78b5.png)

**Comment by dcloudhdx** [comment]
把 package.json 依赖包 `@dcloudio/*/^2.0.0-28320200727001` 改为相同版本，然后 `npm install`

**Comment by Smallwatermelon** [comment]
> 把 package.json 依赖包 `@dcloudio/*/^2.0.0-28320200727001` 改为相同版本，然后 `npm install`
我看的都是相同的版本
![image](https://user-images.githubusercontent.com/38370858/88759672-e0cfb200-d19d-11ea-9219-7e69278d07a3.png)

![image](https://user-images.githubusercontent.com/38370858/88759635-ce557880-d19d-11ea-8d6a-727ac9335b71.png)

**Comment by Smallwatermelon** [comment]
> 把 package.json 依赖包 `@dcloudio/*/^2.0.0-28320200727001` 改为相同版本，然后 `npm install`
刚试了一下 回退版本  是正常的   
又升级这个版本还是这样
我试了很多次还是报这个错误

**Comment by ll929** [comment]
@dcloudhdx 
window平台
@dcloudio/webpack-uni-pages-loader@2.0.0-28320200727001 
/libs/plugin/generate-component.js  67行
```javascript 
    const uniModuleId = modules.find(module => module.resource && normalizePath(module.resource) === uniPath).id
```
改为
```javascript
    const uniModuleId = modules.find(module => module.resource && normalizePath(module.resource) === normalizePath(uniPath)).id
```
就可以了

![微信截图_20200729055229](https://user-images.githubusercontent.com/15249643/88762033-ec71a780-d1a2-11ea-829a-aff9c3a20a13.png)
![微信截图_20200729055309](https://user-images.githubusercontent.com/15249643/88762044-f693a600-d1a2-11ea-987f-f5f8acfd0131.png)

**Comment by fxy060608** [comment]
版本不对，最新版应该是：https://github.com/dcloudio/uni-app/blob/dev/packages/webpack-uni-mp-loader/lib/plugin/generate-component.js#L19
