### ISSUE TITLE
easycom模式，支持不使用HBuilder X方式吗?

### ISSUE THREAD

**Issue by qinmudi** [dcloudio/uni-app#1957]
vue-cli-service uni-serve 这种方式直接easycom吗?

**Comment by zhetengbiji** [comment]
支持

**Comment by qinmudi** [comment]
@zhetengbiji  有示例吗，如何配置？

**Comment by qinmudi** [comment]
知道了 之前配置错误

**Comment by yxmg** [comment]
你好 想请教下为什么我用CLI创建的项目easycom没有效果呢？页面还是报「Unknown custom element:」 并没有自动注册「components」下的组件和uView的组件 能否帮忙看下我的配置是否有问题
```json
"easycom": {
    "^u-(.*)": "uview-ui/components/u-$1/u-$1.vue"
},
```
 @qinmudi @zhetengbiji
