### ISSUE TITLE
webview与onPostMessage通讯接受不到消息的问题

### ISSUE THREAD

**Issue by ldc2726** [dcloudio/uni-app#1959]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  html5的代码
![image](https://user-images.githubusercontent.com/34648806/88901741-c5d76d80-d283-11ea-8568-7ce13a6255d2.png)
2. uni-app的代码
![image](https://user-images.githubusercontent.com/34648806/88901804-dd165b00-d283-11ea-929f-2abd82f59f52.png)
3. 环境确认是v3编译
![image](https://user-images.githubusercontent.com/34648806/88901845-edc6d100-d283-11ea-9509-77140bb50054.png)

2. 点击  触发按钮
3. 查看
![image](https://user-images.githubusercontent.com/34648806/88901894-033bfb00-d284-11ea-8ad1-080ebe45c46d.png)

[或者可以直接贴源代码]

**预期结果**
希望可以接受到消息代码，实在不知道为什么了，感觉就是发出去接收不到

**实际结果**
消息h5端触发消息app接受不到
![image](https://user-images.githubusercontent.com/34648806/88902004-2a92c800-d284-11ea-8ca0-3db7d50294ff.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2]
 - HBuilderX版本 [2.7.14]
 - uni-app版本 [uni-app]
 - 设备信息 [ iPhone8 Plus]

**补充信息**
[可选]

**Comment by Wangyaqi** [comment]
你的页面是nvue页面吗

**Comment by ldc2726** [comment]
@Wangyaqi 都试了没反应，我的需求是h5页面的点击事件通知到app端。。所以h5的点击事件触发了通知消息。。。不知道postMessage是不是有什么限制，以上场景能不能实现

**Comment by Wangyaqi** [comment]
> @Wangyaqi 都试了没反应，我的需求是h5页面的点击事件通知到app端。。所以h5的点击事件触发了通知消息。。。不知道postMessage是不是有什么限制，以上场景能不能实现

你的页面是nvue页面吗

**Comment by ldc2726** [comment]
页面就是html5标准的

**Comment by ldc2726** [comment]
@Wangyaqi 就是hbuildx创建的uni-app项目，

**Comment by Wangyaqi** [comment]
使用@message，问题解决，issue关闭
