### ISSUE TITLE
请问页面之间的跳转怎么进行回调

### ISSUE THREAD

**Issue by zramals** [dcloudio/uni-app#196]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

页面A 跳转页面B
B执行一些操作，例如选择某个列表的值，
此时希望A页面中的显示能够根据B的选择进行更改，在B navBack的时候 A具有刚才选择的数据。

请问这种操作，如何进行。
谢谢

**Comment by xiaoyucoding** [comment]
B 页面在合适的时机，一定是返回之前：
```javascript
uni.setStorage({
	key: 'data',
	data: {
		name: 'uni'
	}
});
```
A 页面接收：
```javascript
onShow() {
	uni.getStorage({
		key: 'data',
		success: (result) => {
			console.log(result.data);
		}
	});
},
```

**Comment by zramals** [comment]
> ```js
> uni.setStorage({
>   key: 'data',
>   data: {
>     name: 'uni'
>   }
> });
> ```

我这个B的页面是个公共页面，比如地区选择这种，那么这种方式，我在B中选择了北京，在其他非A得页面在onshow的时候，是不是也就被赋值了

**Comment by xiaoyucoding** [comment]
> > ```js
> > uni.setStorage({
> >   key: 'data',
> >   data: {
> >     name: 'uni'
> >   }
> > });
> > ```
> 
> 我这个B的页面是个公共页面，比如地区选择这种，那么这种方式，我在B中选择了北京，在其他非A得页面在onshow的时候，是不是也就被赋值了

storage 存储的信息是共享的，如果不希望共享可以设置不同的 key 来进行区分，这个灵活掌握就行。
