### ISSUE TITLE
关于$refs在头条以及支付宝下获取异常的问题

### ISSUE THREAD

**Issue by prianyu** [dcloudio/uni-app#1961]
**问题描述**
嵌套组件获取refs在支付宝以及头条下异常的问题（其他小程序正常）

**复现步骤**
[复现问题的步骤]
1.  自定义组件A，A组件slot含自定义组件B，B组件含自定义组件C
2. 为B设置ref属性为`popup`，为C设置ref属性为`picker`
3. 在A的方法里获取$refs

如下：
![image](https://user-images.githubusercontent.com/8599535/89007716-e105b400-d33b-11ea-914b-bcc53b170936.png)

**预期结果：**

`this.$refs.popup`应该获取到组件B，`this.$refs.picker`获取到组件C

**实际结果：**
1. 头条小程序下`this.$refs`里包含了两个组件引用，其中popup是争取的，picker别命名为了undefined，如下：

![image](https://user-images.githubusercontent.com/8599535/89007389-3d1c0880-d33b-11ea-8cfc-3b54c72396e8.png)

同时，this.$refs.popup.$refs为空数组

2. 支付宝下，`this.$refs`仅能获取一级组件的引用，可以通过$refs的嵌套获取到更深层的引用，如`this.$refs.popup.$refs.picker`可以获取到picker

[或者可以直接贴源代码]

**系统信息:**
 - 操作系统： 所有
 - HBuilderX版本： 2.8.3.20200728

**补充信息**
 是否在template解析时出错了

**Comment by wgjh5** [comment]
解决没

**Comment by yurj26** [comment]
HBuilderX 3.6.18.20230117 无复现此问题。因为插槽有渲染作用域，插槽内组件是在父组件渲染的，所以你应该在父组件内获取(this.$refs.picker)
