### ISSUE TITLE
uni.notifyBLECharacteristicValueChange（bug）

### ISSUE THREAD

**Issue by AdminQQZ** [dcloudio/uni-app#1964]
**问题描述**
uni.notifyBLECharacteristicValueChange（bug）
第一次连接蓝牙，并成功开启监听，蓝牙设备数据发送过去后，uni解析完成，在关闭蓝牙。在关闭页面。这一步完成了。

第二 我重新打开该页面，进行蓝牙连接，启动监听，这时候又拿到了上一次的数据，我把蓝牙关闭，同样，只有关闭APP 后，在打开就正常了
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [Android ]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
低功耗蓝牙，关闭后，应该是没有销毁实例，我这边代码是一个开启，一个关闭，根据官方文档来，成对管理的，所以应该是没有出现开启了多个，关闭了一个

**Comment by dcloudhdx** [comment]
根据你的描述无法定位问题，请提供测试工程
