### ISSUE TITLE
音频无法播放errCode返回-5, errMsg返回mediaError

### ISSUE THREAD

**Issue by labike** [dcloudio/uni-app#1965]
**问题描述**
新建了个uni-app项目, 把官网上的音频播放代码拷过去并且将音频文件下载至本地测试了一下正常播放, 然后将代码拷贝到自己的项目中, 文件引入环境都一样结果运行的时候返回errCode: -5, errMsg: mediaError，但是src换成cdn却可以正常播放

**复现步骤**
1. 运行在mumu模拟器中
2. 控制台打印出错误errCode: -5, errMsg: mediaError
```
onLoad() {
			// 播放订单来了
			const innerAudioContext = uni.createInnerAudioContext();
			innerAudioContext.autoplay = true;
			innerAudioContext.src = '../../static/music.mp3';
			innerAudioContext.onPlay(() => {
			  console.log('开始播放');
			});
			innerAudioContext.onError((res) => {
			  console.log(res.errMsg);
			  console.log(res.errCode);
			});
		},
```

**预期结果**
正常播放音频文件

**实际结果**
errCode:-5是什么?mediaError是什么
![1596273180(1)](https://user-images.githubusercontent.com/15871933/89098452-53e55c80-d41a-11ea-94ef-f2c4d2bf7337.png)

**系统信息:**
 - 发行平台: uni-app
 - 操作系统: android
 - HBuilderX版本: 2.8.3.20200728
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息: mumu模拟器

**Comment by dcloudhdx** [comment]
-5 IO错误 | 文件读写操作错误，如文件被其它程序占用等，错误码参考：https://ask.dcloud.net.cn/article/282

**Comment by BonnieTechnology** [comment]
播放网络音频，安卓端正常，ios端出现
![image](https://user-images.githubusercontent.com/37435733/94386847-2b0fe800-017b-11eb-90b6-e1090b6ce97f.png)

**Comment by wakaryry** [comment]
iOS上，我也出现了。我放假之前是好的。放假之后就不正常了。有些页面可以播放，有些页面不能播放。不知道是不是我持有的 audioPlayer过多的问题。
