### ISSUE TITLE
选择手机相册图片uni.chooseImage在快应用不支持

### ISSUE THREAD

**Issue by enjoyWeb** [dcloudio/uni-app#1966]
**问题描述**
选择手机相册图片uni.chooseImage在快应用不支持

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: 快应用
 - 操作系统 Android 7.0
 - HBuilderX版本 2.8.3.20200727-alpha
 - 设备信息 荣耀V20

**补充信息**
无法定位uniapp源码

**Comment by dcloudhdx** [comment]
`quickapp-webview`渲染已支持，`quickapp-native`渲染尚未适配，可直接调用平台代码，参考工程 `https://github.com/dcloudio/hello-quickapp-native`

**Comment by enjoyWeb** [comment]
> `quickapp-webview`渲染已支持，`quickapp-native`渲染尚未适配，可直接调用平台代码，参考工程 `https://github.com/dcloudio/hello-quickapp-native`

在代码里直接写快应用的代码？

**Comment by dcloudhdx** [comment]
可以，也可以贡献你的源码适配相关API，参考 https://ask.dcloud.net.cn/article/37145

**Comment by enjoyWeb** [comment]
> 可以，也可以贡献你的源码适配相关API，参考 https://ask.dcloud.net.cn/article/37145

那也没法把代码发布到https://github.com/dcloudio/uni-app分支dev-quickapp上去吧？

**Comment by enjoyWeb** [comment]
> `quickapp-webview`渲染已支持，`quickapp-native`

你好！想问下quickapp-webview和quickapp-native有什么区别，我是用uniapp项目的时候怎么看是用哪一种渲染？
目前我的项目里manifest.json写得是quickapp-webview，那是已经支持的了吧？那为什么我用uni.chooseImage没有生效？

**Comment by dcloudhdx** [comment]
> > 可以，也可以贡献你的源码适配相关API，参考 https://ask.dcloud.net.cn/article/37145
> 
> 那也没法把代码发布到[https://github.com/dcloudio/uni-app分支dev-quickapp上去吧？](https://github.com/dcloudio/uni-app%E5%88%86%E6%94%AFdev-quickapp%E4%B8%8A%E5%8E%BB%E5%90%A7%EF%BC%9F)
不能直接提交dev分支，按照文档中的pull request方式提交，我们评估后合并

**Comment by dcloudhdx** [comment]
> > `quickapp-webview`渲染已支持，`quickapp-native`
> 
> 你好！想问下quickapp-webview和quickapp-native有什么区别，我是用uniapp项目的时候怎么看是用哪一种渲染？
> 目前我的项目里manifest.json写得是quickapp-webview，那是已经支持的了吧？那为什么我用uni.chooseImage没有生效？

具体区别参考 https://ask.dcloud.net.cn/article/37182
是运行或发行时决定，manifest.json 是不同渲染引擎的配置，uni.chooseImage 是支持的，以真机为准
体验线上的快应用 hello uni-app https://hapjs.org/app/io.dcloud.helloquickapp

**Comment by enjoyWeb** [comment]
> > > `quickapp-webview`渲染已支持，`quickapp-native`
> > 
> > 
> > 你好！想问下quickapp-webview和quickapp-native有什么区别，我是用uniapp项目的时候怎么看是用哪一种渲染？
> > 目前我的项目里manifest.json写得是quickapp-webview，那是已经支持的了吧？那为什么我用uni.chooseImage没有生效？
> 
> 具体区别参考 https://ask.dcloud.net.cn/article/37182
> 是运行或发行时决定，manifest.json 是不同渲染引擎的配置，uni.chooseImage 是支持的，以真机为准
> 体验线上的快应用 hello uni-app https://hapjs.org/app/io.dcloud.helloquickapp

你好，我项目里manifest.json写得是quickapp-webview，而不是quickapp-webview-union（vivo / oppo  ）和quickapp-webview-huawei（华为），uni.chooseImage不生效是因为这个导致的？

**Comment by dcloudhdx** [comment]
> > > > `quickapp-webview`渲染已支持，`quickapp-native`
> > > 
> > > 
> > > 你好！想问下quickapp-webview和quickapp-native有什么区别，我是用uniapp项目的时候怎么看是用哪一种渲染？
> > > 目前我的项目里manifest.json写得是quickapp-webview，那是已经支持的了吧？那为什么我用uni.chooseImage没有生效？
> > 
> > 
> > 具体区别参考 https://ask.dcloud.net.cn/article/37182
> > 是运行或发行时决定，manifest.json 是不同渲染引擎的配置，uni.chooseImage 是支持的，以真机为准
> > 体验线上的快应用 hello uni-app https://hapjs.org/app/io.dcloud.helloquickapp
> 
> 你好，我项目里manifest.json写得是quickapp-webview，而不是quickapp-webview-union（vivo / oppo ）和quickapp-webview-huawei（华为），uni.chooseImage不生效是因为这个导致的？

和这个没关系，webview渲染即使不配置也不影响API，quickapp-webview 包含 quickapp-webview-union/quickapp-webview-huawei，用真机测试下

**Comment by enjoyWeb** [comment]
╭(╯3╰)╮亲！你的信件我已经收到了，我会尽快查看的O(∩_∩)O哈！
