### ISSUE TITLE
一个组件中使用另一个组件 父组件close方法 通过$ref 访问子组件close方法 会出现循环调用现象

### ISSUE THREAD

**Issue by myjustify** [dcloudio/uni-app#1970]
Maximum call stack size exceeded; [Component] Event Listener Error
页面使用$ref[name].close() -> 组件a $ref[name].close() ->组件b

**Comment by zhetengbiji** [comment]
能否描述清楚一些，另外提问模板为什么不用？

**Comment by myjustify** [comment]
<img width="808" alt="截屏2020-08-03 下午1 35 20" src="https://user-images.githubusercontent.com/30165374/89149275-a5165d00-d58e-11ea-9d9a-3a16d3c7c466.png">

页面a  调用组件b的close方法 组件b的close方法调用组件c的close 
就会报错 Maximum call stack size exceeded; [Component] Event Listener Error

我感觉这个按着模版来就有点太繁琐了
