### ISSUE TITLE
钉钉条件编译#ifdef MP-DINGTALK不生效

### ISSUE THREAD

**Issue by zuifengwuchou** [dcloudio/uni-app#1972]
**问题描述**
package.json中配置了钉钉小程序，在代码中加入了钉钉小程序的条件编译代码，并未生效。

**复现步骤**
[复现问题的步骤]
1.  ![QQ图片20200803155657](https://user-images.githubusercontent.com/16287323/89159597-4b1f9280-d5a2-11ea-9b6b-4064364f1732.png)
![QQ图片20200803155706](https://user-images.githubusercontent.com/16287323/89159619-52df3700-d5a2-11ea-8ae5-f896aa55e99b.png)
2. 编译后代码  
![QQ图片20200803155713](https://user-images.githubusercontent.com/16287323/89159664-638fad00-d5a2-11ea-991d-3b3ee9a28cf4.png)

**Comment by dcloudhdx** [comment]
条件编译的js文件是在项目里还是在 uni_modules ？HX版本多少？
