### ISSUE TITLE
nvue ios textarea 失去焦点无法获取event.detail.cursor

### ISSUE THREAD

**Issue by cattails-lgao** [dcloudio/uni-app#1973]
ios在nvue页面,textare失去焦点时，无法获取event.detail.cursor, 在event.detail没有cursor属性。

**复现步骤**
1.ios nvue 失去焦点
`{
	"type": "blur",
	"timeStamp": 1596448960916,
	"target": {
		"id": "",
		"dataset": {},
		"offsetLeft": 0,
		"offsetTop": 0
	},
	"currentTarget": {
		"id": "",
		"dataset": {},
		"offsetLeft": 0,
		"offsetTop": 0
	},
	"detail": {
		"value": ""
	}
}
`
2.android nvue 失去焦点
`{
	"type": "blur",
	"timeStamp": 1596448774734,
	"target": {
		"id": "",
		"dataset": {},
		"offsetLeft": 0,
		"offsetTop": 0
	},
	"currentTarget": {
		"id": "",
		"dataset": {},
		"offsetLeft": 0,
		"offsetTop": 0
	},
	"detail": {
		"value": "",
		"cursor": 0
	}
}
`

**预期结果**
ios 在nvue的textarea组件失去焦点时获取cursor值

**实际结果**
ios在nvue的textarea组件失去焦点时无法获取cursor值

**系统信息:**
 - 发行平台: 
    App
 - 操作系统 
    IOS
 - HBuilderX版本 
    HBuilderX 2.8.3 alpha
 - 设备信息 
    iPhone6 Plus

**Comment by Otto-J** [comment]
功能已支持
