### ISSUE TITLE
uni-app项目无法正常使用radio组件问题

### ISSUE THREAD

**Issue by NIchijouooo** [dcloudio/uni-app#1974]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
按照官方文档使用radio组件出现key值重复无法正常使用问题
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
`<l-form name="student" :linsubmit="submit">
        <view class="form-title">1.你最喜欢的是？</view>
        <l-form-item name="studentName" label-width="20rpx">
            <l-radio-group current="2" :none-checked="false">
                <l-radio v-for="(item,index) in items6" :key="index" placement="right">{{ item.name }}</l-radio>
            </l-radio-group>
        </l-form-item>
</l-form>`
**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
正常渲染 无报错
**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/61217221/89246130-009f2400-d63d-11ea-91ca-2dc971f4eb14.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by hbcui1984** [comment]
hello uni-app中有示例代码，参考比对一下。
