### ISSUE TITLE
getSavedFileInfo

### ISSUE THREAD

**Issue by githublyp** [dcloudio/uni-app#1975]
export function getSavedFileInfo ({
  filePath
} = {}, callbackId) {
  plus.io.resolveLocalFileSystemURL(getRealPath(filePath), entry => {

那如果是我传入临时路径 也是可以获取了？

**Comment by githublyp** [comment]
@fxy060608

**Comment by zhetengbiji** [comment]
以文档为准，如果表现和文档不同，请勿依赖，以免后续内部改动导致异常。

**Comment by githublyp** [comment]
你赢了
