### ISSUE TITLE
rich-text 组件 nodes 的 attrs 值某些格式不支持

### ISSUE THREAD

**Issue by xiaoyucoding** [dcloudio/uni-app#1976]
## 问题描述
`<rich-text>` 组件，如果 nodes 的 attrs 出现以下情况，在小程序端报错。

测试富文本 `<div data-color="rgb(55, 74, 174)">text</div>`

- H5：正常
- 微信小程序：报错 `e.replace is not a function`
- 其它平台：未测试

## 补充
经过进一步测试，删除 `rgb(55, 74, 174)` 中的空格，可以正常渲染。

`uni-app/src/core/view/components/rich-text/html-parser.js` 的第 15 行

``` javascript
if (value.match(/ /) && name !== 'style') {
  value = value.split(' ')
}
```

以上代码引发了此类问题，建议优化一下。

**Comment by Fasttian** [comment]
确认问题，我优化一下

**Comment by xiaoyucoding** [comment]
补充问题：

``` html
<section style="color: red;" data-id="5" data-color="rgb(55, 74, 174)" data-custom="rgb(55, 74, 174)">html1</section>
```

上述富文本信息，在 H5 与微信小程序中的表现如下表：

|平台|渲染结果|库版本|
|:-|:-|:-|
|h5|不显示任何内容|`uni-app v2.8.13` `uni-app cli v2.0.0-28920200927001`|
|mp-weixin|渲染出红色的 html1 文本|基础库：2.12.1|

问题原因：

1. 如主问题中提到的，自定义属性的值中存在空格会被切割，此时返回的数据格式会报错。
2. `<rich-text>` 组件已经支持了 `<section>` 等标签，需要更新 `nodes-parser.js` 中的配置。

参考文档：微信小程序 [rich-text](https://developers.weixin.qq.com/miniprogram/dev/component/rich-text.html) 组件

**Comment by xiaoyucoding** [comment]
搞乱了，微信小程序的库的问题，目前 v2.12.2 版本已经没有这个问题了。
