### ISSUE TITLE
uniapp H5端引入uni.webview.1.5.2.js报错

### ISSUE THREAD

**Issue by csq0668** [dcloudio/uni-app#1977]
在uniapp的h5端的自定义模板中引入https://js.cdn.aliyun.dcloud.net.cn/dev/uni-app/uni.webview.1.5.2.js后,调用uni.getEnv报错

具体看论坛，https://ask.dcloud.net.cn/question/96060

**Comment by dcloudhdx** [comment]
什么需求需要在H5引入，是要将H5嵌入app或小程序 `<web-view>` 组件中吗？

**Comment by csq0668** [comment]
> 什么需求需要在H5日期，是继承H5嵌入应用程序或小程序`<web-view>`组件中吗？

是这样的，我uniapp打包的App内通过`<web-view>`进入uniapp生成的H5页面，H5页面调用 uni 接口打开APP内的页面。现由于H5页面引入uni.webview.1.5.2.js报错，无法触发 UniAppJSBridgeReady 事件，无法达到H5页面使用uni 接口打开APP内的页面的需求。

**Comment by dcloudhdx** [comment]
调用方法不对，应使用 `uni.webview.getEnv()`
参考文档 https://uniapp.dcloud.net.cn/component/web-view

**Comment by csq0668** [comment]
你好，我尝试了一下还是报错`(index):40 Uncaught TypeError: Cannot read property 'getEnv' of undefined
    at HTMLDocument.<anonymous> ((index):40)
    at HTMLDocument._ (uni.webview.1.5.2.js:1)`

**Comment by dcloudhdx** [comment]
不好意思忘记说了，引用顺序放到body下面

**Comment by csq0668** [comment]
你好，是uni.webview.1.5.2.js放到body还是触发 UniAppJSBridgeReady 事件放到body？如果有空 时间允许的话，可否写一个demo给我？多谢了

**Comment by dcloudhdx** [comment]
放到 `</body>...</html>`

**Comment by csq0668** [comment]
哇，可以了，多谢多谢

**Comment by csq0668** [comment]
太感谢了
