### ISSUE TITLE
nvue下app中textarea设置的line-height无效

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#1984]
如题。

**Comment by HeyChiang** [comment]
能用vue就用vue，nvue是真的不行，特定场景用下就行了，官网也是这么说

**Comment by wakaryry** [comment]
hi. 我们是nvue优先的规则。目前就只有canvas页面以及超长度的rich-text使用了vue页面。

**Comment by HeyChiang** [comment]
不清楚是不是兼容问题，这个是官网的文档，希望对你有帮助。

https://ask.dcloud.net.cn/article/13507

> Q：既然uni-app有了nvue，引入了weex，假使只做app不发小程序，是否可以不用vue，所有界面都使用nvue？
理论上所有界面都可以用nvue，但不建议这么用。
首先vue页面没那么糟。只有个别场景用nvue作为补充更合适。比如左右拖来拖去的长列表。
其次weex并没有那么完善，作为局面补充使用更合理，大面积使用时也会遇到很多weex的坑。
所以各取其优势，避其短处，结合使用是最优方案。

**Comment by wakaryry** [comment]
我只是推动 textarea 的 nvue下app端line-height支持。基于nvue，我们自己开源的组件库都出来了，我们所有的内部开发都是nvue。

https://ext.dcloud.net.cn/plugin?id=2190

**Comment by HeyChiang** [comment]
框架很漂亮，收藏了。  

我还以为你是应用开发者，弄错了，告辞~

**Comment by dcloudhdx** [comment]
nvue line-height 目前暂不支持
