### ISSUE TITLE
头条小程序现在支持sjs，请适配uniapp

### ISSUE THREAD

**Issue by Tong952067063** [dcloudio/uni-app#1985]
**新功能描述**
简洁描述你希望补充完善的增强功能
头条小程序现在支持sjs，请适配uniapp
**现状及问题**
[当前现状及由此导致的不便]
uniapp,无法支持头条小程序的sjs
**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by chenzefeng09** [comment]
百度现在也支持sjs了，不知道这两个有没有计划 @zhetengbiji
