### ISSUE TITLE
腾讯云无法使用

### ISSUE THREAD

**Issue by zero7u** [dcloudio/uni-app#1989]
**问题描述**
没有通过HbuildX，直接登录uniCloud，创建腾讯云，造成HbuildX选择云服务空间时，无法识别创建的腾讯云服务，而腾讯云也无法删除，这是什么问题？？

**复现步骤**
1.  从官网打开uniCloud，登录后，创建腾讯云服务
2. HbuildX在```cloudFunctions```右键，选择云服务空间，找不到刚创建的腾讯云服务
3. 腾讯云服务无法删除重建

**预期结果**
希望能正确的，符合预期的使用uniCloud

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 mac
 - HBuilderX版本 2.8.3

**Comment by Wangyaqi** [comment]
web控制台能看到创建的服务空间吗

**Comment by zero7u** [comment]
@Wangyaqi 后来百度解决了问题，原因有两个：
1、刚创建完腾讯云，大概20分钟才会同步到uniCloud插件市场及HbuildX
2、同时有两个服务空间，默认使用第一个创建的，把阿里云的删除之后，就可以正常使用了

谢谢你们做了如此多的工作~
