### ISSUE TITLE
[JS Framework] Failed to receiveTasks, instance (2) is not available.

### ISSUE THREAD

**Issue by liu806784336** [dcloudio/uni-app#1994]
根据其他回答里，是mainjs配置出错，以下是我的main.js配置
import Vue from 'vue';
import App from './App';
import uView from 'uview-ui';
import Validates from "./public/validate.js";
import DataHanding from "public/dataHanding.js"

Vue.use(uView);

Vue.prototype.$Validates = Validates;
Vue.prototype.$DataHanding = DataHanding;

Vue.config.productionTip = false;

App.mpType = 'app'

const app = new Vue({
...App
})
app.$mount()

并且会导致uni.request无法发出请求，仅限于pda端，自己的手机或者浏览器都能正常使用，仅限pda，以下是我的封装：
const promise = new Promise(function(resolve,reject){
uni.request({
url: that.url,
method:that.method,
header:that.header,
data: that.params,
sslVerify:false,
success: (res) => {
resolve(res.data)
},
fail:(err) => {
console.log(err);
reject(err.data)
}
})
})
return promise;

我想咨询一下原因

**Comment by liu806784336** [comment]
请求reject回来的："errMsg": "request:fail abort statusCode:-1"

**Comment by dcloudhdx** [comment]
是Android HBuilderX 2.8.5+吗？

**Comment by Lysander686** [comment]
我也遇到了 这个错误 

        Failed to receiveTasks,


然后调整了一下代码结构, 发现是我把一个组件的所有代码实现都放到了另一个js文件后利用mixin 引入, 手机端就会报' Failed to receiveTasks,'的错误, 但是网页端就正常
