### ISSUE TITLE
uni-app 是否可以把一个组件库编译成多端的

### ISSUE THREAD

**Issue by juzi214032** [dcloudio/uni-app#1995]
**新功能描述**
我想写一个基于uni-app的组件库，但想针对不同端提供原生版本，uni-app可以支持这样的问题吗

**现状及问题**
当前写了一个uni-app的组件库，便只能使用uni-app框架才能使用这个组件库，对于有些场景还是有些许不便

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by sinoit** [comment]
同求经验和踩坑贴

**Comment by jinjinwa** [comment]
有方案了么？

**Comment by zhetengbiji** [comment]
可以参考 uni-app 的条件编译，自己写脚本实现
