### ISSUE TITLE
能否提供路由守卫

### ISSUE THREAD

**Issue by xingzeping** [dcloudio/uni-app#1996]
**新功能描述**
希望增加路由守卫，或者路由改变前的生命钩子

**现状及问题**
检测不到路由的改变，对于安全性较高的小程序，想实现页面级和按钮级的权限鉴权需要自己封装方法，且用户体验不好（跳转后鉴权，会出现白屏闪一下，就算增加过渡页也不如在跳转前鉴权优雅），同时也会降低性能，提高开发代价

**尝试方案**
目前的方案只能重新封装跳转方法，当无法监听tabbar和原生返回的路由跳转，只能在每个页面的onLoad中调用全局鉴权方法，增加在每个页面中增加缺省页用来过渡鉴权过程

**Comment by SilurianYang** [comment]
使用 [ uni-simpler-router](https://hhyang.cn/v2/start/quickstart.html)
