### ISSUE TITLE
案例里有些app都挂了，整体体验也不好

### ISSUE THREAD

**Issue by alexhmyang** [dcloudio/uni-app#1997]
![image](https://user-images.githubusercontent.com/10215059/89735715-15454700-da97-11ea-8963-e34fbcc82d05.png)
案例里有些app都挂了，比如 放在第一位的这个，看了几个小程序案例整体UI体验也不好，建议放一点 拿的出手的案例。

欢迎大家体验我们的 app和小程序

![image](https://user-images.githubusercontent.com/10215059/89735764-60f7f080-da97-11ea-86c2-444a8df45d47.png)

LikeU大数据精准匹配人生伴侣

**Comment by hbcui1984** [comment]
如果是uni-app开发的，欢迎到https://github.com/dcloudio/uni-app/issues/6 提交案例。
