### ISSUE TITLE
uni.showLoading

### ISSUE THREAD

**Issue by kongfutiger** [dcloudio/uni-app#2002]
**新功能描述**
uni.showLoading方法网络不好的时候那个加载的图标一直在转不消失

**现状及问题**
[uni.showLoading方法网络不好的时候那个加载的图标一直在转，一直不消失，而且网络状况变好了后也不消失]

**尝试方案**
[可以设个网络请求的最大超时120秒，即120秒后自动执行hideLoading方法]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by Otto-J** [comment]
https://uniapp.dcloud.net.cn/api/ui/prompt.html#hideloading
