### ISSUE TITLE
不太好用阿。 产品怎么太绑定IDE了

### ISSUE THREAD

**Issue by cay914** [dcloudio/uni-app#2006]
你们的产品需要HBuilder，还要安装组件。
你们的IDE不成熟
vue的components还要放到工程里面，显示太臃肿了

最好还是做IDE组件, idea的plugin或者eclipse的插件，还有通过package.json的方式添加依赖吧。
不然又做IDE，又做框架，你们哪有这么大的精力呢？
用户也没有时间和你们找IDE的坑，也不太灵活
个人建议

**Comment by zhetengbiji** [comment]
https://uniapp.dcloud.io/quickstart?id=_2-%E9%80%9A%E8%BF%87vue-cli%E5%91%BD%E4%BB%A4%E8%A1%8C

https://uniapp.dcloud.io/frame?id=npm%E6%94%AF%E6%8C%81
