### ISSUE TITLE
自定义模板的链接如何生成？

### ISSUE THREAD

**Issue by ivanlee93** [dcloudio/uni-app#201]
就是下图中的
![image](https://user-images.githubusercontent.com/22174857/52775679-316f5000-307b-11e9-9b76-fac42f270205.png)
找了一圈发现github和官网上都没有相关资料

**Comment by xiaoyucoding** [comment]
就是 vue-cli 的自定义模板，可以参考网上的分享：[从vue-cli源码学习如何写模板](https://github.com/dwqs/blog/issues/56)

**Comment by ivanlee93** [comment]
> 就是你开发一个 uni-app 项目，然后托管到云端，直接填写这个云端仓库的名称就可以了。
> 常用的是 GitHub 等，比如 hello-uniapp 填写 dcloudio/hello-uniapp 就可以了。
> 
> 更多关于支持的下载方式，请参考这个插件的说明：[download-git-repo](https://github.com/flipxfx/download-git-repo)

你好，感谢回复，我已经托管到云端了。这是https://github.com/ivanlee93/uni-template-vuex 这是我的地址，但是输入这个地址，会报404错误
