### ISSUE TITLE
scss不支持绝对路径引入？

### ISSUE THREAD

**Issue by zzc5464** [dcloudio/uni-app#202]
**问题描述**
尝试用 @import 绝对路径引入一个scss文件
编译报错
使用相对路径不报错

使用less引入绝对路径不报错
**复现步骤**
@import url('~@/assets/scss/common.scss');  // 报错
@import url(~@/assets/scss/common.scss);  // 报错

[或者可以直接贴源代码]

**预期结果**
希望可以使用绝对路径

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/25889193/52892881-d8660000-31d1-11e9-8156-2fa94758a902.png)

**系统信息:**
   System:
    OS: macOS 10.14.3
    CPU: (4) x64 Intel(R) Core(TM) i5-8210Y CPU @ 1.60GHz
  Binaries:
    Node: 11.2.0 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 72.0.3626.109
    Firefox: Not Found
    Safari: 12.0.3
  npmPackages:
    @dcloudio/uni-cli-shared: * => 0.2.8 
    @dcloudio/uni-h5: * => 0.2.2 
    @dcloudio/uni-mp-alipay: * => 0.0.8 
    @dcloudio/uni-mp-baidu: * => 0.0.7 
    @dcloudio/uni-mp-toutiao: * => 0.0.3 
    @dcloudio/uni-mp-weixin: * => 0.0.5 
    @dcloudio/vue-cli-plugin-uni: latest => 0.9.31 
    @dcloudio/webpack-uni-mp-loader: * => 0.3.2 
    @dcloudio/webpack-uni-pages-loader: * => 0.2.5 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2 
    @vue/babel-preset-app:  3.4.0 
    @vue/babel-preset-jsx:  1.0.0-beta.2 
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2 
    @vue/babel-sugar-inject-h:  1.0.0-beta.2 
    @vue/babel-sugar-v-model:  1.0.0-beta.2 
    @vue/babel-sugar-v-on:  1.0.0-beta.2 
    @vue/cli-overlay:  3.4.0 
    @vue/cli-plugin-babel: 3.3.0 => 3.3.0 
    @vue/cli-service: ^3.4.0 => 3.4.0 
    @vue/cli-shared-utils:  3.4.0 
    @vue/component-compiler-utils:  2.5.2 
    @vue/preload-webpack-plugin:  1.1.0 
    @vue/web-component-wrapper:  1.2.0 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    vue: ^2.5.22 => 2.6.5 (2.6.5)
    vue-hot-reload-api:  2.3.2 
    vue-loader:  15.6.2 
    vue-router:  3.0.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.5.21 => 2.6.5 
    vue-template-es2015-compiler:  1.8.2 
    vuex: ^3.0.1 => 3.1.0 
  npmGlobalPackages:
    @vue/cli: 3.2.1

**Comment by xiaoyucoding** [comment]
没有重现此问题，建议附上更多的截图以及代码信息。

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
