### ISSUE TITLE
在pages.json中的“plugins”配置编译完会被忽略

### ISSUE THREAD

**Issue by andyqier88** [dcloudio/uni-app#2022]
**问题描述**
1.在pages.json中配置“plugins”属性编译文件中不存在
2.基于pages.json中配置“plugins”后，在某个.vue文件中使用小程序插件中的组件（企业微信提供的插件组件，代码中并无此组件）
微信小程序原生的写法如下
"usingComponents": {
	"cell": "plugin://contactPlugin/cell"
}
也会呗忽略掉
**复现步骤**
[复现问题的步骤]
1. pages.json文件中配置：
"plugins": {
		"contactPlugin": {
			"version": "1.3.0",
			"provider": "wx104a1a20c3f81ec2"
		}
	}
微信小程序编译完成没用此配置

**预期结果**
1.希望支持pages.json中的“plugins”配置编译
2.支持在某个.vue文件中使用小程序插件中的组件（企业微信提供的插件组件，代码中并无此组件）
"usingComponents": {
	"cell": "plugin://contactPlugin/cell"
}
中的编译

**Comment by wsl007** [comment]
![image](https://user-images.githubusercontent.com/24606436/102158790-31ca1380-3ebd-11eb-8b6b-6361930ec8c4.png)
可以在这里配置

**Comment by wsl007** [comment]
manifest.json -> 源码视图 -> mp-weixin 里加入 “plugins” : { ... }
