### ISSUE TITLE
【问题BUG？】uni.onBeaconUpdate在微信小程序端不支持部分机型

### ISSUE THREAD

**Issue by DannyJyc** [dcloudio/uni-app#2027]
**问题描述**
起初发现部分苹果手机不执行uni.onBeaconUpdate（不进入回调），后重启设备或删除小程序在进入的方式解决了部分手机。但仍有一部分始终无法执行uni.onBeaconUpdate，而且在测试过程中发现有部分android手机具有同样问题。

[或者可以直接贴源代码]
![image](https://user-images.githubusercontent.com/32889575/90368125-33fd9c00-e09c-11ea-9602-f18cfb952a4a.png)

**预期结果**
![image](https://user-images.githubusercontent.com/32889575/90368431-96ef3300-e09c-11ea-9d85-674077ef7e86.png)

**实际结果**
![image](https://user-images.githubusercontent.com/32889575/90368459-a1a9c800-e09c-11ea-95b9-7bc3191d234a.png)

**系统信息:**
 - 发行平台:  微信小程序
 - 操作系统 Android 10.0 （华为型号ELS-AN00）
 - HBuilderX版本 2.8.5.20200812
 - 设备信息 华为ELS-AN00，EMUI 10.1.0

 - 操作系统 IOS13.6 （IPhone 11）
 - HBuilderX版本 2.8.5.20200812
 - 设备信息 IPhone 11

**补充信息**
起初觉得是手机缓存的原因，后经了解发现微信官方的接口在早期的确出现过这个问题但是并无明确的解决方案，我在想咱们的接口会不会也同理。请尽快排查

**Comment by zhetengbiji** [comment]
在微信小程序上没有“咱们的接口”，都是微信小程序提供的

**Comment by DannyJyc** [comment]
> 在微信小程序上没有“咱们的接口”，都是微信小程序提供的

我懂，但是在小程序这一端可能是什么原因造成的呢？咱们遇见过吗

**Comment by zhetengbiji** [comment]
> > 在微信小程序上没有“咱们的接口”，都是微信小程序提供的
> 
> 我懂，但是在小程序这一端可能是什么原因造成的呢？咱们遇见过吗

目前没有遇到其他人的相关反馈

**Comment by DannyJyc** [comment]
> > > 在微信小程序上没有“咱们的接口”，都是微信小程序提供的
> > 
> > 
> > 我懂，但是在小程序这一端可能是什么原因造成的呢？咱们遇见过吗
> 
> 目前没有遇到其他人的相关反馈

好吧。。。

**Comment by DannyJyc** [comment]
我自己来结贴了！！！

经过大量设备测试后发现是因为定位的问题，只要通过手机自身设置给予微信在使用过程中对“位置”的权限即可。

建议：在调用搜索蓝牙前获取一次当前位置的信息这样可以让没给予微信“位置”权限的用户感知到并授予微信相应权限。

**Comment by zhetengbiji** [comment]
> 我自己来结贴了！！！
> 
> 经过大量设备测试后发现是因为定位的问题，只要通过手机自身设置给予微信在使用过程中对“位置”的权限即可。
> 
> 建议：在调用搜索蓝牙前获取一次当前位置的信息这样可以让没给予微信“位置”权限的用户感知到并授予微信相应权限。

好的，谢谢你的总结，将在文档给出相关提示。

**Comment by fangliangv587** [comment]
这个问题曾碰到过，也是授权定位解决的（测试机是一部只发送文件用的，故而一直未授权位置定位）
