### ISSUE TITLE
本地网页android下打开后直接展示html源码

### ISSUE THREAD

**Issue by lmf** [dcloudio/uni-app#2028]
使用HbuildX2.8.3 打包，X5内核，使用webview组件打开/hybrid/html/index.html时候展示源码，如下图
![WechatIMG147](https://user-images.githubusercontent.com/3777374/90372416-f7816e80-e0a2-11ea-988b-8c5506785d00.jpeg)

**Comment by lmf** [comment]
安装上app后第一次打开正常，退出后第二次打开就不行了

**Comment by lmf** [comment]
试了下这应该就是用了x5内核的问题，不支持本地网页后面带hash方式打开

**Comment by he426100** [comment]
只能弃用x5内核？
