### ISSUE TITLE
request 的 post 请求 当为'application/json'，如何设置不序列化数据？

### ISSUE THREAD

**Issue by chenxia-123** [dcloudio/uni-app#2029]
request 的 post 请求 当为'application/json'，如何设置不序列化数据？
![image](https://user-images.githubusercontent.com/28851121/90391951-91a3df80-e0c0-11ea-85f4-58e19dd4cca3.png)

**Comment by chenxia-123** [comment]
希望这个可写成可选项，默认序列化。在用户需要时，可选择不序列化

**Comment by zhetengbiji** [comment]
你应该是存在误会，才会这样问
你希望服务端得到什么样的数据？现在不能满足吗？
