### ISSUE TITLE
scss文件无法使用//静默注释

### ISSUE THREAD

**Issue by zzc5464** [dcloudio/uni-app#203]
**问题描述**
外部的scss文件，使用了 // 注释会报错。
只可以使用 /**/

**复现步骤**
[复现问题的步骤]
`
// scss 转换函数  报错
/* ok
scss 转换函数 
*/ 
@function C($n) { 
  @return 750/375*$n; 
}

$commonColor: #f40;
`
Error: Unexpected '/'. Escaping special characters with \ may help.

**Comment by xiaoyucoding** [comment]
通过 cli 创建的项目？我这边测试没有重现这个问题。

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
