### ISSUE TITLE
视图内嵌套循环时, 内层循环函数入参顺序与作用域bug

### ISSUE THREAD

**Issue by zhangHongEn** [dcloudio/uni-app#2034]
**问题描述**

版本: 2.0.0-28620200814003

下面代码中, style1会报错, style2可以正常运行, 先使用子作用域再使用根作用域就会报错

```
<template>
  <view>
    <view v-for="(item, index) in content.items" :key="index">
      <view v-for="(citem, index2) in item.hotZoneList" :key="index2"
        :style1="{'left': transSize(citem.left, content)}"
        :style2="{'left': transSize(content, citem.left)}"

      >
      </view>
    </view>
  </view>
</template>

<script>
export default {
  data () {
    return {

      content: {
        items: [
          {
            hotZoneList: [
              {
                left: 0
              }
            ]
          }
        ],
      },

    }
  },
  methods: {
    
    transSize (a, b) {
      console.log(a, b)
    }
  }
}
</script>

<style>

</style>
```

![image](https://user-images.githubusercontent.com/26006485/90488500-9757fe80-e16e-11ea-8c1c-518bf878f31e.png)

**Comment by zhetengbiji** [comment]
试试 2.0.0-28620200814005

**Comment by devilwjp** [comment]
@zhetengbiji 还是不好

**Comment by devilwjp** [comment]
@zhetengbiji 这么严重的问题，赶紧加班搞定吧

**Comment by zhetengbiji** [comment]
> @zhetengbiji 这么严重的问题，赶紧加班搞定吧

好的
不过用你的代码测试未复现，你提供一个完整工程的压缩包，我试试

**Comment by devilwjp** [comment]
@zhetengbiji 我一会提供一个完整案例，具体的情况是这样的，在模板里语句里遇到多重循环，在内层循环里如果使用了method，传入的参数如果是多个，第一个参数如果是内层循环作用域的，那么之后的参数都只能是内层作用域了，不能再是上层循环作用域的值。感觉就是只要找到是内层作用域，就不会再去外层作用域找了，贴主的例子也是这个意思，content是外层作用域的，所以放在第一个参数是可以的，放在第二个就会出错，因为citem是内层作用域，找过内层之后，就找不到content了

**Comment by zhetengbiji** [comment]
> @zhetengbiji 我一会提供一个完整案例，具体的情况是这样的，在模板里语句里遇到多重循环，在内层循环里如果使用了method，传入的参数如果是多个，第一个参数如果是内层循环作用域的，那么之后的参数都只能是内层作用域了，不能再是上层循环作用域的值。感觉就是只要找到是内层作用域，就不会再去外层作用域找了，贴主的例子也是这个意思，content是外层作用域的，所以放在第一个参数是可以的，放在第二个就会出错，因为citem是内层作用域，找过内层之后，就找不到content了

好的，在线等你
单独用你提供的代码在2.0.0-28620200814003测试过，没复现问题。

**Comment by devilwjp** [comment]
@zhetengbiji 
贴主的案例只要去掉style2这一行就会报错了，sytle1和style2共存是好的  
以下代码必将报错  
`
<template>
	<view>
		<view v-for="(item, index) in content.items" :key="index">
			<view v-for="(citem, index2) in item.hotZoneList" :key="index2"
				  :style1="{'left': transSize(citem.left, content)}"
			>
			</view>
		</view>
	</view>
</template>

<script>
    export default {
        data () {
            return {

                content: {
                    items: [
                        {
                            hotZoneList: [
                                {
                                    left: 0
                                }
                            ]
                        }
                    ],
                },

            }
        },
        methods: {

            transSize (a, b) {
                console.log(a, b)
            }
        }
    }
</script>

<style>

</style>

`

**Comment by devilwjp** [comment]
[test8.zip](https://github.com/dcloudio/uni-app/files/5090295/test8.zip)  
完整案例
@zhetengbiji

**Comment by zhetengbiji** [comment]
> @zhetengbiji
> 贴主的案例只要去掉style2这一行就会报错了，sytle1和style2共存是好的
> 以下代码必将报错
> 
> ```
> <template>
> 	<view>
> 		<view v-for="(item, index) in content.items" :key="index">
> 			<view v-for="(citem, index2) in item.hotZoneList" :key="index2"
> 				  :style1="{'left': transSize(citem.left, content)}"
> 			>
> 			</view>
> 		</view>
> 	</view>
> </template>
> 
> <script>
>     export default {
>         data () {
>             return {
> 
>                 content: {
>                     items: [
>                         {
>                             hotZoneList: [
>                                 {
>                                     left: 0
>                                 }
>                             ]
>                         }
>                     ],
>                 },
> 
>             }
>         },
>         methods: {
> 
>             transSize (a, b) {
>                 console.log(a, b)
>             }
>         }
>     }
> </script>
> 
> <style>
> 
> </style>
> ```

也没有，并且打印了如下内容：
![image](https://user-images.githubusercontent.com/6326057/90511823-ad29eb80-e18f-11ea-866f-607356a11260.png)

**Comment by zhetengbiji** [comment]
> [test8.zip](https://github.com/dcloudio/uni-app/files/5090295/test8.zip)
> 完整案例
> @zhetengbiji

收到，我再试试这个完整的

**Comment by devilwjp** [comment]
@zhetengbiji 要发布成微信小程序，别用hbuilder

**Comment by devilwjp** [comment]
@zhetengbiji 贴主没有交待清楚场景，H5肯定是没问题的，因为不需要走模板静态编译，发布成小程序就会出错了，微信小程序和头条小程序都会错

**Comment by devilwjp** [comment]
@zhetengbiji 两周之前的版本是好的，应该是最近表现的问题  
看了下编译后的js，确实是静态编译中出现了作用域查找错误的问题  
![QQ截图20200818202529](https://user-images.githubusercontent.com/38802722/90512820-4efe0800-e191-11ea-97b1-382b9e9be5dd.jpg)

**Comment by zhetengbiji** [comment]
> @zhetengbiji 两周之前的版本是好的，应该是最近表现的问题
> 看了下编译后的js，确实是静态编译中出现了作用域查找错误的问题
> ![QQ截图20200818202529](https://user-images.githubusercontent.com/38802722/90512820-4efe0800-e191-11ea-97b1-382b9e9be5dd.jpg)

用新的项目测试确认复现了问题

**Comment by devilwjp** [comment]
@zhetengbiji 那请尽快修复吧，这问题蛮严重的，多谢

**Comment by zhetengbiji** [comment]
> @zhetengbiji 那请尽快修复吧，这问题蛮严重的，多谢

看了一下，近期未进行相关改动，测试了半年前的版本也有此问题，后续将进行优化。
