### ISSUE TITLE
能否把uni-app依赖的uni-ui组件更新下，也太旧了

### ISSUE THREAD

**Issue by ctocode** [dcloudio/uni-app#2036]
能否把uni-app依赖的uni-ui组件更新下，也太旧了；能否把uni-app依赖的uni-ui组件更新下，也太旧了；能否把uni-app依赖的uni-ui组件更新下，也太旧了；

**Comment by zhetengbiji** [comment]
什么意思？uni-app框架怎么会依赖uni-ui

**Comment by ctocode** [comment]
> 什么意思？uni-app框架怎么会依赖uni-ui

就是 hello-uni 项目 引入的 非 sass版本的uni-ui版本问题
还有uni-ui 项目所依赖的   @@dcloudio的版本
