### ISSUE TITLE
ios端input输入验证码时,点击键盘上方的"来自信息"的验证码,在input的v-model里会得到重复拼接的验证码内容

### ISSUE THREAD

**Issue by 643104191** [dcloudio/uni-app#2038]
**问题描述**
ios端input输入验证码时,
点击键盘上方的"来自信息"的验证码,
在input的v-model里会得到重复拼接的验证码内容,

如:
验证码是 123456
v-model里会得到 __123456123456__

虽然通过renderjs按照apple文档[Enabling Password AutoFill on an HTML Input Element](https://developer.apple.com/documentation/security/password_autofill/enabling_password_autofill_on_an_html_input_element)将autocomplete设置成了one-time-code,但是依然没什么用
![image](https://user-images.githubusercontent.com/27074730/90588414-2536f680-e20e-11ea-90fa-e29cf3fc46fc.png)

如图,在v-model中设置get/set的计算属性
在set中打印得到的value
会有重复拼接的验证码
![image](https://user-images.githubusercontent.com/27074730/90588425-2e27c800-e20e-11ea-9cb0-fb70b3bf9fa9.png)

真机调试编译器版本:2.8.6(v3)
![image](https://user-images.githubusercontent.com/27074730/90588566-8363d980-e20e-11ea-9870-3e4efe558c63.png)

**Comment by diablosin** [comment]
限制输入长度就行

**Comment by 643104191** [comment]
> 限制输入长度就行

目前看起来也只能通过限制长度来实现
