### ISSUE TITLE
typescript模板项目在h5端的控制台无法展示输出内容的文件名

### ISSUE THREAD

**Issue by xuehongjie** [dcloudio/uni-app#2039]
**问题描述**
![image](https://user-images.githubusercontent.com/22795131/90590412-11da5a00-e213-11ea-9c34-a51745e67ea1.png)
使用的typescript模板，在控制台输出变量无法查看相应的js文件

**复现步骤**
1.  使用vue create -p dcloudio/uni-preset-vue my-project命令创建项目
2. 在index.vue的onLoad中新增console.log任意字段

**预期结果**
控制台能够展示输出内容的相应文件名

**实际结果**
控制台文件名展示为null

**系统信息:**
 - 发行平台: H5平台
 - 操作系统: windows
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 
uni-app v2.8.6
uni-app cli v2.0.0-28620200814005

Environment Info:
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  Binaries:
    Node: 10.15.3 - D:\tool\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.4.1 - D:\tool\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.831.0
  npmPackages:
    @ant-design-vue/babel-helper-vue-transform-on:  1.0.1
    @dcloudio/types: * => 2.0.4
    @dcloudio/uni-app-plus: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-automator: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/uni-cli-shared: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/uni-h5: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/uni-helper-json: * => 1.0.5
    @dcloudio/uni-migration: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/uni-mp-360: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/uni-mp-alipay: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/uni-mp-baidu: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/uni-mp-qq: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/uni-mp-toutiao: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/uni-mp-vue: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/uni-mp-weixin: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/uni-quickapp-native: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/uni-quickapp-webview: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/uni-stat: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/uni-template-compiler: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-28620200814005 => 2.0.0-28620200814005
    @hap-toolkit/dsl-vue:  0.6.13
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.1.2
    @vue/babel-preset-app:  4.5.4
    @vue/babel-preset-jsx:  1.1.2
    @vue/babel-sugar-functional-vue:  1.1.2
    @vue/babel-sugar-inject-h:  1.1.2
    @vue/babel-sugar-v-model:  1.1.2
    @vue/babel-sugar-v-on:  1.1.2
    @vue/cli-overlay:  4.5.4
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.4
    @vue/cli-plugin-router:  4.5.4
    @vue/cli-plugin-typescript: * => 4.5.4
    @vue/cli-plugin-vuex:  4.5.4
    @vue/cli-service: ~4.5.0 => 4.5.4
    @vue/cli-shared-utils:  4.5.4
    @vue/component-compiler-utils:  3.2.0 (3.2.0)
    @vue/preload-webpack-plugin:  1.1.2
    @vue/shared: ^3.0.0-rc.4 => 3.0.0-rc.5
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.11 => 2.6.11
    vue-class-component: ^6.3.2 => 6.3.2 (7.2.5)
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.3 (15.9.3)
    vue-property-decorator: ^8.0.0 => 8.5.1
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.2.0 => 3.5.1
  npmGlobalPackages:
    @vue/cli: Not Found

 - 设备信息 [如 iPhone8 Plus]

**Comment by impacnHo** [comment]
你好，请问您解决了吗？

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/2120
