### ISSUE TITLE
IOS的程序盗取支付宝密码？ 

### ISSUE THREAD

**Issue by hezhongfeng** [dcloudio/uni-app#204]
下载的时候需要输入支付宝的验证码是什么操作？

**Comment by zhetengbiji** [comment]
请详细叙述
在**哪里**下载**什么**的时候？
具体怎么需要的？

**Comment by hezhongfeng** [comment]
扫码下载
![_20190216144715](https://user-images.githubusercontent.com/12163050/52895803-53dba780-31fa-11e9-87c0-34a2930d8664.jpg)
![_20190216144720](https://user-images.githubusercontent.com/12163050/52895804-550cd480-31fa-11e9-863b-ff77c1e09690.jpg)
![_20190216144723](https://user-images.githubusercontent.com/12163050/52895805-550cd480-31fa-11e9-91d5-18bc7766349d.jpg)
![tim 20190216144857](https://user-images.githubusercontent.com/12163050/52895807-5d650f80-31fa-11e9-9c75-5fbc15fcfef7.png)

**Comment by zhetengbiji** [comment]
这是苹果商店
你尝试下载一个其他的应用试试
如果你认为这是苹果盗取什么或者有什么疑问可以联系苹果客服解惑

**Comment by hezhongfeng** [comment]
OK

**Comment by hezhongfeng** [comment]
@zhetengbiji 估计是我太久没验证了，目前已经下载下来了，但是应用打开就显示在'hello uni-app'页面，然后就自己关闭了
最新的ios系统，8P
