### ISSUE TITLE
H5 scrollView 开启下拉刷新的时候会有异常

### ISSUE THREAD

**Issue by wyzwhp** [dcloudio/uni-app#2040]
1、scroll-view在开启下拉刷新功能的时候会有异常

[复现问题的步骤]
1.  直接下拉没有问题，都是好的
2. 往下滚一段距离然后再往回滚，滚动条还没到顶部，已经直接触发刷新事件
源码地址https://github.com/dcloudio/uni-app/blob/1de259ec9eebd1d41951d0b8ffc985b6c2e9dd4f/src/core/view/components/scroll-view/index.vue
![image](https://user-images.githubusercontent.com/1272295/90606079-e155e880-e231-11ea-9c8f-e6acc45fdd9b.png)

绿色部分是触发的地方，红色部分是上面赋值

**Comment by wyzwhp** [comment]
问题解决了，原来的代码中缺少一个条件判断
![image](https://user-images.githubusercontent.com/1272295/90711880-6a256080-e2d4-11ea-9b0d-6cd6c69acc1f.png)
红色部分改成self.refresherEnabled && self.refreshState === 'pulling'&&main.scrollTop==0即可

**Comment by StrivingRabbit** [comment]
此问题在新版HX中已修复
