### ISSUE TITLE
父子组件对象的引用问题

### ISSUE THREAD

**Issue by EvanMaFYH** [dcloudio/uni-app#2042]
**问题描述**
子组件有一个Object类型的prop假设为obj，假设父组件传递了obj为{name:'111',age:2}给子组件，在子组件中修改对象的某个属性是不会抛出‘Avoid mutating a prop directly’的错误的，虽然不推荐直接修改组件的prop，但是很多时候确实也会去修改对象中的某个属性，比如写个表单组件，组件内部提供一个清空表单内容的方法，而表单的对象是通过prop传递进来的，但是目前在小程序中在子组件直接修改对象中的属性时，父组件中的表单对象并未发生变化，而h5下是发生了变化的因为正常情况下两个对象指向同一个引用确实应该和h5表现的那样，为啥微信小程序表现的不一样呢

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
原因：因为微信小程序中组件转换为了小程序组件传递的数据并非原始对象，所以修改后，原始对象并不会发生变化。

现状：即这样绕过了vue警告，但仍然是不推荐的写法，目前不会为了实现这个不推荐的写法修改框架。

修改方案：使用事件在组件外部修改数据，或者使用 v-model 简化写法。
