### ISSUE TITLE
微信小程序 input组件 bug

### ISSUE THREAD

**Issue by bloodskyfirst** [dcloudio/uni-app#2045]
**问题描述**
微信小程序中,使用input组件,type为number时,安卓端输入键盘不显示完成按钮,ios端点击完成按钮不触发confirm事件.

**复现步骤**
[复现问题的步骤]
1.  启动 ''
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
<input type="number" value="" @confirm="test(e)" />

test(e){
   console.log(e)
},

**预期结果**
希望完善该功能

**实际结果**

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 :iOS 12、Android 8.1
 - HBuilderX版本 2.85
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 onePluse 5t,iphone XR

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by wakaryry** [comment]
设置 confirm-type 试试。

**Comment by bloodskyfirst** [comment]
今天有时间重新测试了一下,设置了confirm-type  search或者 done 都不能触发confirm事件了. 请自行在手机端测试

代码如下:
<input type="number" :value="testValue"  confirm-type="done" @confirm="test"/>

data() {
        return {
            testValue:'',

methods:{
        test(){
            uni.showToast({
                title:'测试成功',
                icon:'none'
            })
        },

**Comment by bloodskyfirst** [comment]
上面直接赋值三个模块的三个地方,没有完全复制所有代码.所以请好好测试

**Comment by zhetengbiji** [comment]
直接用微信小程序测试，如果仍然有问题，需反馈给微信小程序社区
