### ISSUE TITLE
vue create -p dcloudio/uni-preset-vue 能否创建对应HBuilder 版本的资源

### ISSUE THREAD

**Issue by zhuSass** [dcloudio/uni-app#2047]
需求来源：老项目是通过HBuilder(v2.7) 创建的，现在想改成vue-cli方式来管理项目，但是通过`vue create -p dcloudio/uni-preset-vue`创建默认是下载最新版本，所依赖的包都是最新(v2.8)的版本的包，我想通过改package.json版本进行修改，但是之前通过HBuilder创建的项目没有package.json文件，请教这个该怎么处理
解决思路：
1、提供HBuilder 版本对应的资源包版本
2、dcloudio/uni-preset-vue提供一个参数可以选择对应HBuilder 版本进行创建项目

**Comment by zhetengbiji** [comment]
在 npm 上查看 https://www.npmjs.com/package/@dcloudio/webpack-uni-pages-loader?activeTab=versions
比如 HBuilderX 2.7.5.20200518 对应的版本号 2.0.0-27520200518001

**Comment by zhuSass** [comment]
我的版本是HBuilderX.2.7.14.20200618，那么按照您上面说的应该是2.0.0-271420200618，但是我却在版本里找不到 @zhetengbiji

**Comment by zhetengbiji** [comment]
> 我的版本是HBuilderX.2.7.14.20200618，那么按照您上面说的应该是2.0.0-271420200618，但是我却在版本里找不到 @zhetengbiji

14改9

**Comment by zhuSass** [comment]
感谢！只是还存在一个问题就是我打包的时候还是显示`编译器版本：2.8.8（v3）详见：`也就是还是用2.8.8的进行打包，导致打出来的资源包app那边的盒子(2.7.14)报版本不一致，这个该如何处理

**Comment by zhetengbiji** [comment]
> 感谢！只是还存在一个问题就是我打包的时候还是显示`编译器版本：2.8.8（v3）详见：`也就是还是用2.8.8的进行打包，导致打出来的资源包app那边的盒子(2.7.14)报版本不一致，这个该如何处理 @zhetengbiji

云打包还是本地打包？

**Comment by zhuSass** [comment]
本地打包资源 @zhetengbiji

**Comment by zhetengbiji** [comment]
> 本地打包资源 @zhetengbiji

所有uni相关依赖都要一致的版本，你只改了一个？链接那个是示例

**Comment by zhuSass** [comment]
```
{
  "name": "yjy-mini",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "npm run dev:h5",
    "build": "npm run build:h5",
    "build:app-plus": "cross-env NODE_ENV=production UNI_PLATFORM=app-plus vue-cli-service uni-build",
    "build:custom": "cross-env NODE_ENV=production uniapp-cli custom",
    "build:h5": "cross-env NODE_ENV=production UNI_PLATFORM=h5 vue-cli-service uni-build",
    "build:mp-360": "cross-env NODE_ENV=production UNI_PLATFORM=mp-360 vue-cli-service uni-build",
    "build:mp-alipay": "cross-env NODE_ENV=production UNI_PLATFORM=mp-alipay vue-cli-service uni-build",
    "build:mp-baidu": "cross-env NODE_ENV=production UNI_PLATFORM=mp-baidu vue-cli-service uni-build",
    "build:mp-qq": "cross-env NODE_ENV=production UNI_PLATFORM=mp-qq vue-cli-service uni-build",
    "build:mp-toutiao": "cross-env NODE_ENV=production UNI_PLATFORM=mp-toutiao vue-cli-service uni-build",
    "build:mp-weixin": "cross-env NODE_ENV=production UNI_PLATFORM=mp-weixin vue-cli-service uni-build",
    "build:quickapp-native": "cross-env NODE_ENV=production UNI_PLATFORM=quickapp-native vue-cli-service uni-build",
    "build:quickapp-webview": "cross-env NODE_ENV=production UNI_PLATFORM=quickapp-webview vue-cli-service uni-build",
    "build:quickapp-webview-huawei": "cross-env NODE_ENV=production UNI_PLATFORM=quickapp-webview-huawei vue-cli-service uni-build",
    "build:quickapp-webview-union": "cross-env NODE_ENV=production UNI_PLATFORM=quickapp-webview-union vue-cli-service uni-build",
    "dev:app-plus": "cross-env NODE_ENV=development UNI_PLATFORM=app-plus vue-cli-service uni-build --watch",
    "dev:custom": "cross-env NODE_ENV=development uniapp-cli custom",
    "dev:h5": "cross-env NODE_ENV=development UNI_PLATFORM=h5 vue-cli-service uni-serve",
    "dev:mp-360": "cross-env NODE_ENV=development UNI_PLATFORM=mp-360 vue-cli-service uni-build --watch",
    "dev:mp-alipay": "cross-env NODE_ENV=development UNI_PLATFORM=mp-alipay vue-cli-service uni-build --watch",
    "dev:mp-baidu": "cross-env NODE_ENV=development UNI_PLATFORM=mp-baidu vue-cli-service uni-build --watch",
    "dev:mp-qq": "cross-env NODE_ENV=development UNI_PLATFORM=mp-qq vue-cli-service uni-build --watch",
    "dev:mp-toutiao": "cross-env NODE_ENV=development UNI_PLATFORM=mp-toutiao vue-cli-service uni-build --watch",
    "dev:mp-weixin": "cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch",
    "dev:quickapp-native": "cross-env NODE_ENV=development UNI_PLATFORM=quickapp-native vue-cli-service uni-build --watch",
    "dev:quickapp-webview": "cross-env NODE_ENV=development UNI_PLATFORM=quickapp-webview vue-cli-service uni-build --watch",
    "dev:quickapp-webview-huawei": "cross-env NODE_ENV=development UNI_PLATFORM=quickapp-webview-huawei vue-cli-service uni-build --watch",
    "dev:quickapp-webview-union": "cross-env NODE_ENV=development UNI_PLATFORM=quickapp-webview-union vue-cli-service uni-build --watch",
    "info": "node node_modules/@dcloudio/vue-cli-plugin-uni/commands/info.js",
    "serve:quickapp-native": "node node_modules/@dcloudio/uni-quickapp-native/bin/serve.js",
    "test:android": "cross-env UNI_PLATFORM=app-plus UNI_OS_NAME=android jest -i",
    "test:h5": "cross-env UNI_PLATFORM=h5 jest -i",
    "test:ios": "cross-env UNI_PLATFORM=app-plus UNI_OS_NAME=ios jest -i",
    "test:mp-baidu": "cross-env UNI_PLATFORM=mp-baidu jest -i",
    "test:mp-weixin": "cross-env UNI_PLATFORM=mp-weixin jest -i"
  },
  "dependencies": {
    "@dcloudio/uni-app-plus": "^2.0.0-27920200618001",
    "@dcloudio/uni-h5": "^2.0.0-27920200618001",
    "@dcloudio/uni-helper-json": "*",
    "@dcloudio/uni-mp-360": "^2.0.0-27920200618001",
    "@dcloudio/uni-mp-alipay": "^2.0.0-27920200618001",
    "@dcloudio/uni-mp-baidu": "^2.0.0-27920200618001",
    "@dcloudio/uni-mp-qq": "^2.0.0-27920200618001",
    "@dcloudio/uni-mp-toutiao": "^2.0.0-27920200618001",
    "@dcloudio/uni-mp-vue": "^2.0.0-27920200618001",
    "@dcloudio/uni-mp-weixin": "^2.0.0-27920200618001",
    "@dcloudio/uni-quickapp-native": "^2.0.0-27920200618001",
    "@dcloudio/uni-quickapp-webview": "^2.0.0-27920200618001",
    "@dcloudio/uni-stat": "^2.0.0-27920200618001",
    "@vue/shared": "^3.0.0-rc.4",
    "core-js": "^3.6.5",
    "flyio": "^0.6.2",
    "regenerator-runtime": "^0.12.1",
    "vue": "^2.6.11",
    "vuex": "^3.2.0"
  },
  "devDependencies": {
    "@dcloudio/types": "*",
    "@dcloudio/uni-automator": "^2.0.0-27920200618001",
    "@dcloudio/uni-cli-shared": "^2.0.0-27920200618001",
    "@dcloudio/uni-migration": "^2.0.0-27920200618001",
    "@dcloudio/uni-template-compiler": "^2.0.0-27920200618001",
    "@dcloudio/vue-cli-plugin-hbuilderx": "^2.0.0-27920200618001",
    "@dcloudio/vue-cli-plugin-uni": "^2.0.0-27920200618001",
    "@dcloudio/vue-cli-plugin-uni-optimize": "^2.0.0-27920200618001",
    "@dcloudio/webpack-uni-mp-loader": "^2.0.0-27920200618001",
    "@dcloudio/webpack-uni-pages-loader": "^2.0.0-27920200618001",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-plugin-import": "^1.11.0",
    "cross-env": "^7.0.2",
    "jest": "^25.4.0",
    "mini-types": "*",
    "miniprogram-api-typings": "*",
    "postcss-comment": "^2.0.0",
    "vue-template-compiler": "^2.6.11"
  },
  "browserslist": [
    "Android >= 4",
    "ios >= 8"
  ],
  "uni-app": {
    "scripts": {}
  }
}

```
我把资源包都改了哦

**Comment by zhetengbiji** [comment]
去掉 ^ 重新安装

**Comment by zhuSass** [comment]
当我改成
```
{
  "name": "yjy-mini",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "npm run dev:h5",
    "build": "npm run build:h5",
    "build:app-plus": "cross-env NODE_ENV=production UNI_PLATFORM=app-plus vue-cli-service uni-build",
    "build:custom": "cross-env NODE_ENV=production uniapp-cli custom",
    "build:h5": "cross-env NODE_ENV=production UNI_PLATFORM=h5 vue-cli-service uni-build",
    "build:mp-360": "cross-env NODE_ENV=production UNI_PLATFORM=mp-360 vue-cli-service uni-build",
    "build:mp-alipay": "cross-env NODE_ENV=production UNI_PLATFORM=mp-alipay vue-cli-service uni-build",
    "build:mp-baidu": "cross-env NODE_ENV=production UNI_PLATFORM=mp-baidu vue-cli-service uni-build",
    "build:mp-qq": "cross-env NODE_ENV=production UNI_PLATFORM=mp-qq vue-cli-service uni-build",
    "build:mp-toutiao": "cross-env NODE_ENV=production UNI_PLATFORM=mp-toutiao vue-cli-service uni-build",
    "build:mp-weixin": "cross-env NODE_ENV=production UNI_PLATFORM=mp-weixin vue-cli-service uni-build",
    "build:quickapp-native": "cross-env NODE_ENV=production UNI_PLATFORM=quickapp-native vue-cli-service uni-build",
    "build:quickapp-webview": "cross-env NODE_ENV=production UNI_PLATFORM=quickapp-webview vue-cli-service uni-build",
    "build:quickapp-webview-huawei": "cross-env NODE_ENV=production UNI_PLATFORM=quickapp-webview-huawei vue-cli-service uni-build",
    "build:quickapp-webview-union": "cross-env NODE_ENV=production UNI_PLATFORM=quickapp-webview-union vue-cli-service uni-build",
    "dev:app-plus": "cross-env NODE_ENV=development UNI_PLATFORM=app-plus vue-cli-service uni-build --watch",
    "dev:custom": "cross-env NODE_ENV=development uniapp-cli custom",
    "dev:h5": "cross-env NODE_ENV=development UNI_PLATFORM=h5 vue-cli-service uni-serve",
    "dev:mp-360": "cross-env NODE_ENV=development UNI_PLATFORM=mp-360 vue-cli-service uni-build --watch",
    "dev:mp-alipay": "cross-env NODE_ENV=development UNI_PLATFORM=mp-alipay vue-cli-service uni-build --watch",
    "dev:mp-baidu": "cross-env NODE_ENV=development UNI_PLATFORM=mp-baidu vue-cli-service uni-build --watch",
    "dev:mp-qq": "cross-env NODE_ENV=development UNI_PLATFORM=mp-qq vue-cli-service uni-build --watch",
    "dev:mp-toutiao": "cross-env NODE_ENV=development UNI_PLATFORM=mp-toutiao vue-cli-service uni-build --watch",
    "dev:mp-weixin": "cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch",
    "dev:quickapp-native": "cross-env NODE_ENV=development UNI_PLATFORM=quickapp-native vue-cli-service uni-build --watch",
    "dev:quickapp-webview": "cross-env NODE_ENV=development UNI_PLATFORM=quickapp-webview vue-cli-service uni-build --watch",
    "dev:quickapp-webview-huawei": "cross-env NODE_ENV=development UNI_PLATFORM=quickapp-webview-huawei vue-cli-service uni-build --watch",
    "dev:quickapp-webview-union": "cross-env NODE_ENV=development UNI_PLATFORM=quickapp-webview-union vue-cli-service uni-build --watch",
    "info": "node node_modules/@dcloudio/vue-cli-plugin-uni/commands/info.js",
    "serve:quickapp-native": "node node_modules/@dcloudio/uni-quickapp-native/bin/serve.js",
    "test:android": "cross-env UNI_PLATFORM=app-plus UNI_OS_NAME=android jest -i",
    "test:h5": "cross-env UNI_PLATFORM=h5 jest -i",
    "test:ios": "cross-env UNI_PLATFORM=app-plus UNI_OS_NAME=ios jest -i",
    "test:mp-baidu": "cross-env UNI_PLATFORM=mp-baidu jest -i",
    "test:mp-weixin": "cross-env UNI_PLATFORM=mp-weixin jest -i"
  },
  "dependencies": {
    "@dcloudio/uni-app-plus": "2.0.0-27920200618001",
    "@dcloudio/uni-h5": "2.0.0-27920200618001",
    "@dcloudio/uni-helper-json": "*",
    "@dcloudio/uni-mp-360": "2.0.0-27920200618001",
    "@dcloudio/uni-mp-alipay": "2.0.0-27920200618001",
    "@dcloudio/uni-mp-baidu": "2.0.0-27920200618001",
    "@dcloudio/uni-mp-qq": "2.0.0-27920200618001",
    "@dcloudio/uni-mp-toutiao": "2.0.0-27920200618001",
    "@dcloudio/uni-mp-vue": "2.0.0-27920200618001",
    "@dcloudio/uni-mp-weixin": "2.0.0-27920200618001",
    "@dcloudio/uni-quickapp-native": "2.0.0-27920200618001",
    "@dcloudio/uni-quickapp-webview": "2.0.0-27920200618001",
    "@dcloudio/uni-stat": "2.0.0-27920200618001",
    "@vue/shared": "^3.0.0-rc.4",
    "core-js": "^3.6.5",
    "flyio": "^0.6.2",
    "regenerator-runtime": "^0.12.1",
    "vue": "^2.6.11",
    "vuex": "^3.2.0"
  },
  "devDependencies": {
    "@dcloudio/types": "*",
    "@dcloudio/uni-automator": "2.0.0-27920200618001",
    "@dcloudio/uni-cli-shared": "2.0.0-27920200618001",
    "@dcloudio/uni-migration": "2.0.0-27920200618001",
    "@dcloudio/uni-template-compiler": "2.0.0-27920200618001",
    "@dcloudio/vue-cli-plugin-hbuilderx": "2.0.0-27920200618001",
    "@dcloudio/vue-cli-plugin-uni": "2.0.0-27920200618001",
    "@dcloudio/vue-cli-plugin-uni-optimize": "^2.0.0-27920200618001",
    "@dcloudio/webpack-uni-mp-loader": "2.0.0-27920200618001",
    "@dcloudio/webpack-uni-pages-loader": "2.0.0-27920200618001",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "babel-plugin-import": "^1.11.0",
    "cross-env": "^7.0.2",
    "jest": "^25.4.0",
    "mini-types": "*",
    "miniprogram-api-typings": "*",
    "postcss-comment": "^2.0.0",
    "vue-template-compiler": "^2.6.11"
  },
  "browserslist": [
    "Android >= 4",
    "ios >= 8"
  ],
  "uni-app": {
    "scripts": {}
  }
}

```
然后重新下载，提示
```
Couldn't find any versions for "@dcloudio/uni-mp-vue" that matches "2.0.0-27920200618001"
? Please choose a version of "@dcloudio/uni-mp-vue" from this list:
  2.0.0-alpha-28720200819002
  2.0.0-alpha-28720200819001
  2.0.0-alpha-28720200818001
  2.0.0-alpha-28520200811001
  2.0.0-alpha-28420200805005
  2.0.0-alpha-28420200805004
  2.0.0-alpha-28420200805002
  2.0.0-alpha-28420200805001
  2.0.0-alpha-28320200727005
  2.0.0-alpha-28320200727004
  2.0.0-alpha-28320200727003
  2.0.0-alpha-28320200727002
> 2.0.0-alpha-28320200727001
  2.0.0-alpha-28120200721003
  2.0.0-alpha-28120200721001
  2.0.0-alpha-28120200720003
  2.0.0-alpha-28120200720002
  2.0.0-alpha-26920200407011
  2.0.0-28820200820001
  2.0.0-28720200819002
  2.0.0-28720200819001
  2.0.0-28720200818001
  2.0.0-28620200814005
  2.0.0-28620200814004
  2.0.0-28620200814003
  2.0.0-28620200814002
  2.0.0-28620200814001
  2.0.0-28520200811001
```
@zhetengbiji

**Comment by zhetengbiji** [comment]
> 当我改成
> 
> ```
> {
>   "name": "yjy-mini",
>   "version": "0.1.0",
>   "private": true,
>   "scripts": {
>     "serve": "npm run dev:h5",
>     "build": "npm run build:h5",
>     "build:app-plus": "cross-env NODE_ENV=production UNI_PLATFORM=app-plus vue-cli-service uni-build",
>     "build:custom": "cross-env NODE_ENV=production uniapp-cli custom",
>     "build:h5": "cross-env NODE_ENV=production UNI_PLATFORM=h5 vue-cli-service uni-build",
>     "build:mp-360": "cross-env NODE_ENV=production UNI_PLATFORM=mp-360 vue-cli-service uni-build",
>     "build:mp-alipay": "cross-env NODE_ENV=production UNI_PLATFORM=mp-alipay vue-cli-service uni-build",
>     "build:mp-baidu": "cross-env NODE_ENV=production UNI_PLATFORM=mp-baidu vue-cli-service uni-build",
>     "build:mp-qq": "cross-env NODE_ENV=production UNI_PLATFORM=mp-qq vue-cli-service uni-build",
>     "build:mp-toutiao": "cross-env NODE_ENV=production UNI_PLATFORM=mp-toutiao vue-cli-service uni-build",
>     "build:mp-weixin": "cross-env NODE_ENV=production UNI_PLATFORM=mp-weixin vue-cli-service uni-build",
>     "build:quickapp-native": "cross-env NODE_ENV=production UNI_PLATFORM=quickapp-native vue-cli-service uni-build",
>     "build:quickapp-webview": "cross-env NODE_ENV=production UNI_PLATFORM=quickapp-webview vue-cli-service uni-build",
>     "build:quickapp-webview-huawei": "cross-env NODE_ENV=production UNI_PLATFORM=quickapp-webview-huawei vue-cli-service uni-build",
>     "build:quickapp-webview-union": "cross-env NODE_ENV=production UNI_PLATFORM=quickapp-webview-union vue-cli-service uni-build",
>     "dev:app-plus": "cross-env NODE_ENV=development UNI_PLATFORM=app-plus vue-cli-service uni-build --watch",
>     "dev:custom": "cross-env NODE_ENV=development uniapp-cli custom",
>     "dev:h5": "cross-env NODE_ENV=development UNI_PLATFORM=h5 vue-cli-service uni-serve",
>     "dev:mp-360": "cross-env NODE_ENV=development UNI_PLATFORM=mp-360 vue-cli-service uni-build --watch",
>     "dev:mp-alipay": "cross-env NODE_ENV=development UNI_PLATFORM=mp-alipay vue-cli-service uni-build --watch",
>     "dev:mp-baidu": "cross-env NODE_ENV=development UNI_PLATFORM=mp-baidu vue-cli-service uni-build --watch",
>     "dev:mp-qq": "cross-env NODE_ENV=development UNI_PLATFORM=mp-qq vue-cli-service uni-build --watch",
>     "dev:mp-toutiao": "cross-env NODE_ENV=development UNI_PLATFORM=mp-toutiao vue-cli-service uni-build --watch",
>     "dev:mp-weixin": "cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch",
>     "dev:quickapp-native": "cross-env NODE_ENV=development UNI_PLATFORM=quickapp-native vue-cli-service uni-build --watch",
>     "dev:quickapp-webview": "cross-env NODE_ENV=development UNI_PLATFORM=quickapp-webview vue-cli-service uni-build --watch",
>     "dev:quickapp-webview-huawei": "cross-env NODE_ENV=development UNI_PLATFORM=quickapp-webview-huawei vue-cli-service uni-build --watch",
>     "dev:quickapp-webview-union": "cross-env NODE_ENV=development UNI_PLATFORM=quickapp-webview-union vue-cli-service uni-build --watch",
>     "info": "node node_modules/@dcloudio/vue-cli-plugin-uni/commands/info.js",
>     "serve:quickapp-native": "node node_modules/@dcloudio/uni-quickapp-native/bin/serve.js",
>     "test:android": "cross-env UNI_PLATFORM=app-plus UNI_OS_NAME=android jest -i",
>     "test:h5": "cross-env UNI_PLATFORM=h5 jest -i",
>     "test:ios": "cross-env UNI_PLATFORM=app-plus UNI_OS_NAME=ios jest -i",
>     "test:mp-baidu": "cross-env UNI_PLATFORM=mp-baidu jest -i",
>     "test:mp-weixin": "cross-env UNI_PLATFORM=mp-weixin jest -i"
>   },
>   "dependencies": {
>     "@dcloudio/uni-app-plus": "2.0.0-27920200618001",
>     "@dcloudio/uni-h5": "2.0.0-27920200618001",
>     "@dcloudio/uni-helper-json": "*",
>     "@dcloudio/uni-mp-360": "2.0.0-27920200618001",
>     "@dcloudio/uni-mp-alipay": "2.0.0-27920200618001",
>     "@dcloudio/uni-mp-baidu": "2.0.0-27920200618001",
>     "@dcloudio/uni-mp-qq": "2.0.0-27920200618001",
>     "@dcloudio/uni-mp-toutiao": "2.0.0-27920200618001",
>     "@dcloudio/uni-mp-vue": "2.0.0-27920200618001",
>     "@dcloudio/uni-mp-weixin": "2.0.0-27920200618001",
>     "@dcloudio/uni-quickapp-native": "2.0.0-27920200618001",
>     "@dcloudio/uni-quickapp-webview": "2.0.0-27920200618001",
>     "@dcloudio/uni-stat": "2.0.0-27920200618001",
>     "@vue/shared": "^3.0.0-rc.4",
>     "core-js": "^3.6.5",
>     "flyio": "^0.6.2",
>     "regenerator-runtime": "^0.12.1",
>     "vue": "^2.6.11",
>     "vuex": "^3.2.0"
>   },
>   "devDependencies": {
>     "@dcloudio/types": "*",
>     "@dcloudio/uni-automator": "2.0.0-27920200618001",
>     "@dcloudio/uni-cli-shared": "2.0.0-27920200618001",
>     "@dcloudio/uni-migration": "2.0.0-27920200618001",
>     "@dcloudio/uni-template-compiler": "2.0.0-27920200618001",
>     "@dcloudio/vue-cli-plugin-hbuilderx": "2.0.0-27920200618001",
>     "@dcloudio/vue-cli-plugin-uni": "2.0.0-27920200618001",
>     "@dcloudio/vue-cli-plugin-uni-optimize": "^2.0.0-27920200618001",
>     "@dcloudio/webpack-uni-mp-loader": "2.0.0-27920200618001",
>     "@dcloudio/webpack-uni-pages-loader": "2.0.0-27920200618001",
>     "@vue/cli-plugin-babel": "~4.5.0",
>     "@vue/cli-service": "~4.5.0",
>     "babel-plugin-import": "^1.11.0",
>     "cross-env": "^7.0.2",
>     "jest": "^25.4.0",
>     "mini-types": "*",
>     "miniprogram-api-typings": "*",
>     "postcss-comment": "^2.0.0",
>     "vue-template-compiler": "^2.6.11"
>   },
>   "browserslist": [
>     "Android >= 4",
>     "ios >= 8"
>   ],
>   "uni-app": {
>     "scripts": {}
>   }
> }
> ```
> 
> 然后重新下载，提示
> 
> ```
> Couldn't find any versions for "@dcloudio/uni-mp-vue" that matches "2.0.0-27920200618001"
> ? Please choose a version of "@dcloudio/uni-mp-vue" from this list:
>   2.0.0-alpha-28720200819002
>   2.0.0-alpha-28720200819001
>   2.0.0-alpha-28720200818001
>   2.0.0-alpha-28520200811001
>   2.0.0-alpha-28420200805005
>   2.0.0-alpha-28420200805004
>   2.0.0-alpha-28420200805002
>   2.0.0-alpha-28420200805001
>   2.0.0-alpha-28320200727005
>   2.0.0-alpha-28320200727004
>   2.0.0-alpha-28320200727003
>   2.0.0-alpha-28320200727002
> > 2.0.0-alpha-28320200727001
>   2.0.0-alpha-28120200721003
>   2.0.0-alpha-28120200721001
>   2.0.0-alpha-28120200720003
>   2.0.0-alpha-28120200720002
>   2.0.0-alpha-26920200407011
>   2.0.0-28820200820001
>   2.0.0-28720200819002
>   2.0.0-28720200819001
>   2.0.0-28720200818001
>   2.0.0-28620200814005
>   2.0.0-28620200814004
>   2.0.0-28620200814003
>   2.0.0-28620200814002
>   2.0.0-28620200814001
>   2.0.0-28520200811001
> ```
> 
> @zhetengbiji 似乎并没有2.0.0-27920200618001的版本

你要用的版本没有@dcloudio/uni-mp-vue这个包，删除即可，如果遇到其他包有提示同理

**Comment by zhuSass** [comment]
官方的好像在git上的tag里并没有留下`2.0.0-27xxx`的版本，这个该怎么处理

**Comment by zhuSass** [comment]
删了@dcloudio/uni-mp-vue这个包会对项目有影响吗 @zhetengbiji

**Comment by zhetengbiji** [comment]
> 官方的好像在git上的tag里并没有留下`2.0.0-27xxx`的版本，这个该怎么处理

旧版本比新版本少的包删除即可，旧版本比新版的多的包，增加即可

**Comment by zhetengbiji** [comment]
> 删了@dcloudio/uni-mp-vue这个包会对项目有影响吗 @zhetengbiji

以后升级新版本，加上即可

**Comment by zhuSass** [comment]
> > 官方的好像在git上的tag里并没有留下`2.0.0-27xxx`的版本，这个该怎么处理
> 
> 旧版本比新版本少的包删除即可，旧版本比新版的多的包，增加即可

会不会存在在2.7版本里存在b包，在2.8版本里去掉了b包，但是我进行create uni-app的时候它是按照2.8最新版进行创建依赖的，所以就不存在b包

**Comment by zhuSass** [comment]
没有任何文档或者历史资料可以查看对应版本依赖的npm包吗

**Comment by zhetengbiji** [comment]
> > > 官方的好像在git上的tag里并没有留下`2.0.0-27xxx`的版本，这个该怎么处理
> > 
> > 
> > 旧版本比新版本少的包删除即可，旧版本比新版的多的包，增加即可
> 
> 会不会存在在2.7版本里存在b包，在2.8版本里去掉了b包，但是我进行create uni-app的时候它是按照2.8最新版进行创建依赖的，所以就不存在b包

是有可能的，对于存在差异根据提示自行增删即可

**Comment by zhetengbiji** [comment]
> 没有任何文档或者历史资料可以查看对应版本依赖的npm包吗

目前没有，后续会在文档增加相关说明

**Comment by zhuSass** [comment]
现在提示
```
本应用使用HBuilderX2.7.13编译或对应的cli版本编译，而手机端SDK版本是2.7.14.不匹配的版本可能造成应用异常
```
@zhetengbiji

**Comment by zhuSass** [comment]
可以了，感谢您的回复 @zhetengbiji
