### ISSUE TITLE
微信小程序自定义组件事件传递不传参数报错

### ISSUE THREAD

**Issue by yhllow** [dcloudio/uni-app#2051]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
引入微信小程序自定义组件，绑定组件中不带参数的事件时，报 TypeError: Cannot read property '__args__' of undefined，
比如 van-field 组件的 click-icon 事件，组件源码：
onClickIcon: function () {
            this.$emit('click-icon');
},
绑定传参的组件事件不报错。

**复现步骤**
[复现问题的步骤]
1. 引用 van-field 组件，绑定click-icon事件
2. 运行为微信小程序，点击搜索按钮

[或者可以直接贴源代码]
<van-field :value="vehicle_no" placeholder="点击输入车牌号" right-icon="search" clearable="true" @focus="inputVe"
				 @click-icon="searchEvent" @clear="clearVe" />

Cannot read property '__args__' of undefined; [Component] Event Listener Error @ wxcomponents/vant/field/index#(anonymous)
TypeError: Cannot read property '__args__' of undefined
    at processEventArgs (http://127.0.0.1:55521/appservice/common/vendor.js:1097:29)

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
希望能兼容微信自定义组件不传参的事件

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 MAC版 HBuilderX 2.8.8、2.8.3、2.7.9
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 微信开发者工具

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
微信小程序自定义组件事件传递，不传参数的情况为做兼容

**Comment by yhllow** [comment]
[demo.zip](https://github.com/dcloudio/uni-app/files/5115325/demo.zip)
好的，之前是用微信小程序原生开发的，最近在学习uni-app，把以前项目里的一个页面移植到uni-app，发现微信自定义组件事件调用父组件事件不传参会报错。
另外如果传参，参数取值需要从 arguments 的末尾取值（arguments前面的参数都是undefined，见onOK 函数），不知道是否有更好的用法。
onOk: function(e) {
				// uni-app 微信自定义组件参数在最后
				e = e || arguments[arguments.length - 1];
				consoleUtil.log(e.detail, '输入的车牌号');
				this.showKeyboard = false;
				this.vehicle_no = e.detail;

				this.searchEvent();
			},

**Comment by zhetengbiji** [comment]
我自己新建了一个工程发现没这问题，然后检查你的工程，发现你的使用方式不对，你看下文档：https://uniapp.dcloud.io/frame?id=%E5%B0%8F%E7%A8%8B%E5%BA%8F%E7%BB%84%E4%BB%B6%E6%94%AF%E6%8C%81

**Comment by yhllow** [comment]
好的，是我偷懒了，文档我之前看过，后来在网上看到可以直接在页面中引用自定义组件，就没在 pages.json 里添加 usingComponents -_-，按照官方文档重新配置 pages.json 文件就可以了。
