### ISSUE TITLE
是否支持在uniapp中使用vantUI

### ISSUE THREAD

**Issue by jahnli** [dcloudio/uni-app#2053]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

请问是否支持在uniapp中使用vantUI，有在uniapp中使用vantUI的Demo吗 ？
目前尝试npm安装，提示module failed  postcss  xxx
已有项目使用的VantUI，想直接迁移至uniapp，不想更换为vant webApp

**Comment by AlanKnightly** [comment]
> vant的web版操作了dom，所以只能用于web端
> 
> 我目前项目是vantUI，并非uniapp，而我迁移过来只需要h5端即可

大哥，我们这边是uni-app的老项目想迁移到H5，但是没办法一下子迁移；请问是可以直接像一般web项目一样，直接npm i vantjs引入vant ui 组件使用吗？
