### ISSUE TITLE
v-if ="obj"  obj 初始为对象 之后赋值 undefined v-if 并未生效

### ISSUE THREAD

**Issue by 2234839** [dcloudio/uni-app#2058]
**问题描述**
v-if ="obj"  obj 初始为对象 之后赋值 undefined v-if 并未生效

**复现步骤**

1. 模板代码  
![图片](https://user-images.githubusercontent.com/28727933/91113550-76386600-e6b8-11ea-9c2d-aa4381611f39.png)

2.  setTimeout(()=>{test=undefined},2000)

**预期结果**

显然此处 「333333」 不应该显示才是正确的结果

**实际结果**

![图片](https://user-images.githubusercontent.com/28727933/91113560-7df80a80-e6b8-11ea-8de8-ac04317396b4.png)

**系统信息:**

版本: 1.49.0-insider (system setup)
提交: f57a418b019926b38d2e6949265c33002a8f6f6b
日期: 2020-08-24T06:01:10.507Z
Electron: 9.2.0
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18363
 - uni-app版本 uni-app v2.8.6
                        uni-app cli v2.0.0-28620200814004
 - 小米10  微信小程序

**补充信息**

undefined 的值在v-if 中没有正确更新？

**Comment by zhetengbiji** [comment]
进行如下尝试：
更新到最新2.0.0-28820200820001
或者设置test为null
