### ISSUE TITLE
小程序接口权限相关设置不知道在哪儿设置

### ISSUE THREAD

**Issue by NoBugsss** [dcloudio/uni-app#206]
**问题描述**
[问题描述：微信文档:https://developers.weixin.qq.com/miniprogram/dev/framework/config.html#permission;
微信小程序权限接口没法设置或者在哪儿设置?

]

uni.getLocation({}) 微信小程序需要开通权限

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/12505380/52999525-014ff480-3461-11e9-9637-2d831283f8f2.png)

**Comment by xiaoyucoding** [comment]
#207
