### ISSUE TITLE
【Android】在一个小程序页面中有许多input的时候，依次点击聚焦，无法唤起键盘

### ISSUE THREAD

**Issue by CrazyOctopusDan** [dcloudio/uni-app#2060]
**问题描述**
在小程序页面中需要有多个input组成一个注册页面，然而在点击下面的input的时候，只有在IOS上面可以依次唤起键盘，在Android Q机型上面就会闪烁一下，然后键盘消失。

于是我打开控制台: 
在IOS机型上面检查，点击InputA 再点击inputB，会依次触发 「onFocusA onBlurA onFocusB onBlurA」 

但是 Android 机型上，点击InputA 再点击inputB，会依次触发 『onFocusA onBlurA onBlurB』

**复现步骤**
[复现问题的步骤]
```
<input
	class="input-login" 
	:adjust-position="false"
	:value="pwd"
	placeholder="请输入密码" 
	:password="true"
	placeholder-class="phcolor-input" 
	maxlength="30" 
	@input="inputPwd"
/>
```

**预期结果**
切换点击 input 触发 onFocus，键盘弹起来

**实际结果**
点下一个input，键盘和光标就都没了
![image](https://user-images.githubusercontent.com/18019209/91149089-3dff4a80-e6ed-11ea-8ab2-b24c78cbc8c5.png)

**系统信息:**
 - 发行平台: Android Q
 - 操作系统 Android 9.0
 - 设备信息 三星 S8Plus

**补充信息**
[可选]
缺少了onFocus的钩子是怎么回事？

**Comment by Fasttian** [comment]
小程序上测试未复现

**Comment by CrazyOctopusDan** [comment]
> 小程序上测试未复现
我用华为 红米 三星三台手机测试都复现


![image](https://user-images.githubusercontent.com/18019209/91298747-24383300-e7d3-11ea-852e-62fabb3483d1.png)
随便建立一个页面，随便添加5个input，随便就复现了
![image](https://user-images.githubusercontent.com/18019209/91298871-59448580-e7d3-11ea-8966-c07afde82bca.png)
点击第一个input能够唤起键盘
![image](https://user-images.githubusercontent.com/18019209/91299024-9446b900-e7d3-11ea-8eae-c697f4c9fc3b.png)
再点击第二个input，不聚焦且键盘不唤起
![image](https://user-images.githubusercontent.com/18019209/91299063-a3c60200-e7d3-11ea-865b-c193abd827a8.png)

**Comment by zhetengbiji** [comment]
安卓微信实现的问题，点击输入框外会失去焦点和隐藏键盘

**Comment by sisiban0** [comment]
遇到同样的问题 直接用官方提供的表单 在安卓微信中多个input来回切换 很大概率会导致 下一次的input先聚焦 然后立马失去焦点 导致键盘出不来 需要再次点击input 使其重新获取焦点

**Comment by aushbringer** [comment]
请问您是，发错人了吧？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dcloudio/uni-app"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年11月12日(星期四) 下午4:40
收件人:&nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] 【Android】在一个小程序页面中有许多input的时候，依次点击聚焦，无法唤起键盘 (#2060)





 
遇到同样的问题 直接用官方提供的表单 在安卓微信中多个input来回切换 很大概率会导致 下一次的input先聚焦 然后立马失去焦点 导致键盘出不来 需要再次点击input 使其重新获取焦点

**Comment by sisiban0** [comment]
不好意思 是回复错了 尴尬 第一次留言 不是很懂



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "aushbringer"<notifications@github.com&gt;; 
发送时间: 2020年11月12日(星期四) 下午4:43
收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 
抄送: "493343269"<493343269@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [dcloudio/uni-app] 【Android】在一个小程序页面中有许多input的时候，依次点击聚焦，无法唤起键盘 (#2060)





 请问您是，发错人了吧？ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "dcloudio/uni-app"                                                                                    <notifications@github.com&amp;gt;; 
 发送时间:&amp;nbsp;2020年11月12日(星期四) 下午4:40 
 收件人:&amp;nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&amp;gt;; 
 抄送:&amp;nbsp;"Subscribed"<subscribed@noreply.github.com&amp;gt;; 
 主题:&amp;nbsp;Re: [dcloudio/uni-app] 【Android】在一个小程序页面中有许多input的时候，依次点击聚焦，无法唤起键盘 (#2060) 
 
 
 
 
 
   
 遇到同样的问题 直接用官方提供的表单 在安卓微信中多个input来回切换 很大概率会导致 下一次的input先聚焦 然后立马失去焦点 导致键盘出不来 需要再次点击input 使其重新获取焦点

**Comment by just-myself** [comment]
> 遇到同样的问题 直接用官方提供的表单 在安卓微信中多个input来回切换 很大概率会导致 下一次的input先聚焦 然后立马失去焦点 导致键盘出不来 需要再次点击input 使其重新获取焦点

这个问题怎么说了，没办法解决呀
