### ISSUE TITLE
requireNativePlugin 调用返回 undefined

### ISSUE THREAD

**Issue by XiaoWuWeb** [dcloudio/uni-app#2061]
**问题描述**
使用官方推荐的DCloud-RichAler 弹窗插件。按照步骤下载，引入，调用，结果打印出来的是 undefined

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

**预期结果**
返回可调用 object

**实际结果**
const dcRichAlert = uni.requireNativePlugin('DCloud-RichAlert');
console.log(dcRichAlert);  // undefined
console.log(uni.requireNativePlugin('DCloud-RichAlert'));  // undefined
![Uploading HL)E2SHVIAOCUPQ87XA]330.png…]()
![6O Y8L$EWMX8 `68QU{ T{A](https://user-images.githubusercontent.com/18734555/91162285-79564500-e6fe-11ea-93f2-cdda57ca2846.png)

**系统信息:**
 - 发行平台: 基座调试
 - 操作系统 Android 6.0
 - HBuilderX版本 2.8.8.20200820
 - uni-app版本 
 - 设备信息  PDA（C70）

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by chocolateonly** [comment]
@XiaoWuWeb 哈喽 这个问题 我想知道怎么解决的？
