### ISSUE TITLE
组件Object类型prop的问题

### ISSUE THREAD

**Issue by EvanMaFYH** [dcloudio/uni-app#2063]
**问题描述**
举个例子，有个组件A，他有一个prop为info，类型是Object，在使用该组件的页面中初始传入的值比如为info:{age:'2'}，在页面中有两个输入框，v-model分别绑定的是info.age和info.name，当在info.name输入框内输入1后打印组件内的info值没有发生变化，除非修改下info.age的输入框比如输入了22，此时再打印组件内的info值，才正常显示为{age:'22',name:'1'}   
以上内容在h5下是正常的，在微信小程序上可以复现   
可以参考[demo](https://github.com/EvanMaFYH/obj-prop-bug)

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
同：https://ask.dcloud.net.cn/question/103458

**Comment by EvanMaFYH** [comment]
链接里的回复不大对吧，我并没有在组件中改变prop的值啊，我demo的组件里就一个按钮用来打印prop的值 @zhetengbiji

**Comment by zhetengbiji** [comment]
> 链接里的回复不大对吧，我并没有在组件中改变prop的值啊，我demo的组件里就一个按钮用来打印prop的值 @zhetengbiji

刚看了一下代码，你初始化的时候没有 name 属性（https://github.com/EvanMaFYH/obj-prop-bug/issues/1）

相关文档：https://cn.vuejs.org/v2/guide/reactivity.html#检测变化的注意事项

**Comment by EvanMaFYH** [comment]
你可能没理解我的意思，我这边就是特意没有加name属性，现实场景中就是一个很长的表单对象info，如果像这样必须每个属性都要初始化的话非常麻烦，可以参考[这个表单验证组件](https://ext.dcloud.net.cn/plugin?id=1137)，如果没有初始化某个表单属性，即使这个值变了在表单组件中拿到的表单对象依然没有这个属性导致表单验证出错，除非这个时候其他初始化的属性修改了一下，在表单组件中的表单对象才正常，上面提供的demo就是用来简单复现问题的，所以特意没有加name属性   
这个情况正常使用vue写或者uniapp的h5是不需要初始化的，在微信小程序下会出现问题

**Comment by zhetengbiji** [comment]
> 你可能没理解我的意思，我这边就是特意没有加name属性，现实场景中就是一个很长的表单对象info，如果像这样必须每个属性都要初始化的话非常麻烦，可以参考[这个表单验证组件](https://ext.dcloud.net.cn/plugin?id=1137)，如果没有初始化某个表单属性，即使这个值变了在表单组件中拿到的表单对象依然没有这个属性导致表单验证出错，除非这个时候其他初始化的属性修改了一下，在表单组件中的表单对象才正常，上面提供的demo就是用来简单复现问题的，所以特意没有加name属性
> 这个情况正常使用vue写或者uniapp的h5是不需要初始化的，在微信小程序下会出现问题

新增的属性无法观测，尽量避免这样使用

**Comment by EvanMaFYH** [comment]
这个是不是后续也不考虑支持了

**Comment by EvanMaFYH** [comment]
如果是的话可能要考虑换一种方式去实现了

**Comment by zhetengbiji** [comment]
> 这个是不是后续也不考虑支持了

理论上vue 3就可以了，vue 2实现方式本身有这种限制，vue 文档有相关说明，至于为什么这个示例在H5上恰好被观测到了，此处不再深究。
