### ISSUE TITLE
日期或者时间mode的picker建议增加H5模式选项

### ISSUE THREAD

**Issue by BruceAn1978** [dcloudio/uni-app#2065]
**新功能描述**
picker - 日期/时间选择框

**现状及问题**
H5页面会显示3列的底部选择picker，而真机运行时则是系统内置的操作风格。

**尝试方案**
建议增加真机是以H5还是系统内置方式打开选项。

**补充信息**
一个录入页面同时有多个下拉框输入组件时，其实保持统一的H5底部弹出picker效果挺好的，日期/时间输入框会突然改变为系统弹框方式，整体UI交互挺受影响。

**Comment by zhetengbiji** [comment]
已经支持，fields="year"
稍后将会在文档说明

**Comment by BruceAn1978** [comment]
fields="year"应该是只能选择年份吧，不是我说的在网页和手机端都保持一种底部弹出的picker方式吧。

**Comment by zhetengbiji** [comment]
> fields="year"应该是只能选择年份吧，不是我说的在网页和手机端都保持一种底部弹出的picker方式吧。

day 是日，只要设置了 fields 就是你要的样子了

**Comment by BruceAn1978** [comment]
:+1:
