### ISSUE TITLE
uni-build 打包h5平台代码，是否会build两遍？

### ISSUE THREAD

**Issue by hearAllParties** [dcloudio/uni-app#2067]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
打包命令：```cross-env NODE_ENV=production UNI_PLATFORM=h5 vue-cli-service uni-build```是否会编译一遍文件之后再编译一遍？

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
h5模式接入sentry插件`webpack-sentry-plugin`，设置参数`deleteAfterCompile: true`

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
build出的文件中没有*.js.map文件

**实际结果**
[这里请贴上你的报错截图或文字]
build出的文件中*.js.map文件未删除。实际上`webpack-sentry-plugin`执行了删除.map文件操作，但是删除的文件名和最终build出来的map文件对不上

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
是否启用了摇树优化
