### ISSUE TITLE
H5页面还没有加载出来时，你们为什么要自己加loading？

### ISSUE THREAD

**Issue by HeyChiang** [dcloudio/uni-app#2068]
**问题描述**
我进入页面本来就有自己的加载圈展示，结果你们在我的加载圈之前还展示了一个加载圈，导致页面很难看。

**复现步骤**
[复现问题的步骤]
1.  去掉所有缓冲
2. 在chrome浏览器里将网络改成slow 3G 
3. 查看页面就会出现系统的loading加载

**预期结果**
纯白色显示就好

**实际结果**
多显示了加载圈

![微信图片_20200827000447](https://user-images.githubusercontent.com/12081334/91328093-ffef4d00-e7f8-11ea-9d4b-81c7435dd85c.png)

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [windows 10   chrome浏览器]
 - HBuilderX版本 [2.8.8.20200820]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [chrome 浏览器手机模式  iPhone 6/7/8 ]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by HeyChiang** [comment]
现在，都没有人回答问题了..?

**Comment by Otto-J** [comment]
https://uniapp.dcloud.net.cn/collocation/manifest.html#h5-async
