### ISSUE TITLE
pages.json中的permission选项无法被编译到app.json中

### ISSUE THREAD

**Issue by Lxs-597** [dcloudio/uni-app#207]
**问题描述**
小程序2018年12月26日更新要求使用getLocation定位服务时需要在app.json中配置`permission`字段，但现在uni-app的配置项列表中并未加入该字段，并且pages.json中的`permission`选项不会被编译到app.json中

**复现步骤**
1.  在pages.json中加入
```js
  "permission": {
    "scope.userLocation": {
      "desc": "你的位置信息将用于小程序位置接口的效果展示"
    }
  }
```
2. 点击 运行->运行到小程序模拟器->微信开发者工具
3. 查看模拟器中生成的app.json

**预期结果**
在app.json中生成对应的`permission`配置选项

**实际结果**
未按预期

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 macOS 10.14.2
 - HBuilderX版本 1.5.4.20190127
 - 设备信息 小程序开发者工具1.02.1902010

**Comment by xiaoyucoding** [comment]
[manifest.json->mp-weixin](https://uniapp.dcloud.io/collocation/manifest?id=mp-weixin)
