### ISSUE TITLE
uni.getRecorderManager() onStop 回调函数优化

### ISSUE THREAD

**Issue by zehuichan** [dcloudio/uni-app#2083]
如题：

onStop 的回调函数能否返回如下结果：

```js
{
  tempFilePath: 'string', // 录音文件的临时路径 (本地路径)
  duration: 'number', // 录音总时长，单位：ms
  fileSize: 'number' // 录音文件大小，单位：Byte
}
```

最近的一个多端开发项目，在接入腾讯即时通信 IM SDK时候，用录音管理，app端发现onStop的回调函数与微信小程序的有些出入，导致无法发送语音消息，微信小程序是可以的。

**Comment by Fasttian** [comment]
已在处理中，预计下个版本支持

**Comment by zehuichan** [comment]
@Fasttian 谢谢

**Comment by zehuichan** [comment]
返回录音时长可以了吗，有具体时间吗，v2.8.13还不支持喔

**Comment by Otto-J** [comment]
https://uniapp.dcloud.net.cn/api/media/record-manager.html#getrecordermanager
