### ISSUE TITLE
app webview中uni.getEnv获取不准

### ISSUE THREAD

**Issue by shuipinhuajieyu** [dcloudio/uni-app#2086]
**问题描述**
app环境 webview中uni.getEnv第一次取到的值是 plus
webview.reload 之后uni.getEnv 取到的值是 H5

**预期结果**
一直是 plus

**实际结果**
 H5

**系统信息:**
 - 发行平台: 标准基座
 - HBuilderX版本 2.8.8
 - uni-app版本 3
 - 设备信息 Redmi K20 Pro(MIUI 12.0.2)

**Comment by dcloudhdx** [comment]
请提供测试工程
