### ISSUE TITLE
scroll-view 中在ios端飞书内置浏览器中监听不到滚动事件

### ISSUE THREAD

**Issue by haruka0** [dcloudio/uni-app#2089]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
scroll-view 中在ios端飞书内置浏览器中监听不到滚动事件
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
![image](https://user-images.githubusercontent.com/46950398/91978692-23654b00-ed57-11ea-947a-889431b5fecd.png)
原因应该是这里传了事件e进来，但是代码里却用的是隐含参数event,在飞书ios端隐含参数event表现和e不一致，第一次触发后不再变化，被后面节流20ms内滚动的方法给拦截掉了，因此不能再次触发

**Comment by zhetengbiji** [comment]
使用iOS的飞书测试了一下，未复现你说的问题，理论上iOS平台不同应用使用的webview内核一样，不会出现不同的表现

**Comment by haruka0** [comment]
> 使用iOS的飞书测试了一下，未复现你说的问题，理论上iOS平台不同应用使用的webview内核一样，不会出现不同的表现

我不清楚你是怎么复现的，我之前监听在在scroll-view的滚动到底,滚动到顶的toast都没出现，滚动的也就出现一次。理论上内核一致，但我是用不带任何框架的原生js代码测试过才得出的这个结论。不过这里改掉了就好

**Comment by zhetengbiji** [comment]
> > 使用iOS的飞书测试了一下，未复现你说的问题，理论上iOS平台不同应用使用的webview内核一样，不会出现不同的表现
> 
> 我不清楚你是怎么复现的，我之前监听在在scroll-view的滚动到底,滚动到顶的toast都没出现，滚动的也就出现一次。理论上内核一致，但我是用不带任何框架的原生js代码测试过才得出的这个结论。不过这里改掉了就好

好的
