### ISSUE TITLE
swipe组件不支持根据内容高度动态高度

### ISSUE THREAD

**Issue by andyzhaozhao** [dcloudio/uni-app#2091]
**问题描述**
[问题描述：想做这样一个效果：

![微信图片_20200903101339](https://user-images.githubusercontent.com/7730080/92063635-3404d800-edce-11ea-9bde-3d6d2a970e93.jpg)

使用swipe组件，难点在于其中的列表页只有三行，高度是动态的。swipe无法根据子元素的高度来动态适配。

**Comment by zhetengbiji** [comment]
swiper-item 是根据父元素大小来的，不是根据子元素
你可以使用接口获取子元素大小，自行设置外层元素高度

**Comment by andyzhaozhao** [comment]
> swiper-item 是根据父元素大小来的，不是根据子元素
> 你可以使用接口获取子元素大小，自行设置外层元素高度

建议也可以根据子元素动态设置高度吧。降低用户难度。uniapp论坛很多人都在问这个问题，没有好的解决方案。或者uniapp官方是出于什么原因，无法做到根据子元素来动态决定高度呢

**Comment by zhetengbiji** [comment]
> > swiper-item 是根据父元素大小来的，不是根据子元素
> > 你可以使用接口获取子元素大小，自行设置外层元素高度
> 
> 建议也可以根据子元素动态设置高度吧。降低用户难度。uniapp论坛很多人都在问这个问题，没有好的解决方案。或者uniapp官方是出于什么原因，无法做到根据子元素来动态决定高度呢

你是问为什么不内置这样的功能么？如果功能十分必要且提出此需求的人很多，会考虑内置的。否则用户建议作为扩展插件提交到插件市场。

**Comment by Stephen-Js** [comment]
笑了，真垃圾

**Comment by Stephen-Js** [comment]
> > > swiper-item 是根据父元素大小来的，不是根据子元素
> > > 你可以使用接口获取子元素大小，自行设置外层元素高度
> > 
> > 
> > 建议也可以根据子元素动态设置高度吧。降低用户难度。uniapp论坛很多人都在问这个问题，没有好的解决方案。或者uniapp官方是出于什么原因，无法做到根据子元素来动态决定高度呢
> 
> 你是问为什么不内置这样的功能么？如果功能十分必要且提出此需求的人很多，会考虑内置的。否则用户建议作为扩展插件提交到插件市场。

笑了，关闭issues全靠嘴

**Comment by zhetengbiji** [comment]
> > > > swiper-item 是根据父元素大小来的，不是根据子元素
> > > > 你可以使用接口获取子元素大小，自行设置外层元素高度
> > > 
> > > 
> > > 建议也可以根据子元素动态设置高度吧。降低用户难度。uniapp论坛很多人都在问这个问题，没有好的解决方案。或者uniapp官方是出于什么原因，无法做到根据子元素来动态决定高度呢
> > 
> > 
> > 你是问为什么不内置这样的功能么？如果功能十分必要且提出此需求的人很多，会考虑内置的。否则用户建议作为扩展插件提交到插件市场。
> 
> 笑了，关闭issues全靠嘴

这类需要尽量在业务层封装，或者单独封装插件发到市场，而不是靠嘴冷嘲热笑。
