### ISSUE TITLE
项目打包成H5，IOS，一个tabBar页面本来是不会滚动的，但是跳到二级页面，以手势返回回来，页面就变成会滚动了

### ISSUE THREAD

**Issue by ydydydq** [dcloudio/uni-app#2094]
我将项目打包成H5，在IOS上，一个tabBar页面本来是不会滚动的，但是跳到二级页面后，
以“手势”（手指右滑）返回回来，页面就变成会滚动了。。。。。。
这是Bug吗？

**Comment by zhetengbiji** [comment]
目前还未收到此类反馈
是否有条件进行调试（使用Safari），如果可以的话，调试看看，如果不具体调试条件，提供一个测试链接或者测试工程，帮你看下
