### ISSUE TITLE
android端在4G下不能进行服务请求

### ISSUE THREAD

**Issue by floki2020** [dcloudio/uni-app#2096]
**问题描述**
利用云打包生成的安卓包或在线直接真机测试 在4G的情况下 都不能进行网络请求
苹果打包一切正常 4G/WIFI
**复现步骤**

1.启动app
2.安卓真机切换4G网络 登陆app

**预期结果**
4G网络可以正常进行登陆请求

**实际结果**
1.向后端请求一直没有结果

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统: Android 8.1 
 - HBuilderX版本 [2.8.8.20200820]
 - uni-app版本 [1.5.1]
 - 设备信息 [华为 honor 10]

**Comment by zmobs** [comment]
第一是确认一下   移动的4g 还是联通4g 或者其他运营商。  第二 提供一下 可以的复现的连接和请求代码。

**Comment by floki2020** [comment]
> 第一是确认一下 移动的4g 还是联通4g 或者其他运营商。 第二 提供一下 可以的复现的连接和请求代码。

4G 移动 等你好消息

**Comment by floki2020** [comment]
问题已经解决！感谢各位的帮助
