### ISSUE TITLE
vant-weapp Area 省市区选择组件，在app端下空白

### ISSUE THREAD

**Issue by zehuichan** [dcloudio/uni-app#2097]
小程序，正常

![微信截图_20200904133040](https://user-images.githubusercontent.com/16459997/92204329-cd5ae980-eeb5-11ea-94e4-37c130f79302.png)

APP端，空白，并且后台提示

![微信图片_20200904134858](https://user-images.githubusercontent.com/16459997/92204340-d2b83400-eeb5-11ea-915d-dec92f4d900d.png)

```
13:48:26.481 cid unmatched at view.umd.min.js:1
13:48:26.503 TypeError: Invalid attempt to destructure non-iterable instance.
13:48:26.523 In order to be iterable, non-array objects must have a [Symbol.iterator]() method. at view.umd.min.js:1
```

**Comment by gcindy** [comment]
老哥解决了么？我也遇到这个问题了

**Comment by zehuichan** [comment]
@gcindy 换uview吧，没办法了
