### ISSUE TITLE
tabBar可以自定义内容

### ISSUE THREAD

**Issue by dsonet** [dcloudio/uni-app#210]
**新功能描述**
希望可以自定义Tabbar

**现状及问题**
[当前现状及由此导致的不便]
现在的tabBar内容模板是固定死的,对于需要在tabBar上显示一些其他元素(比如加红标,或者badge)都很难实现

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
微信小程序已经支持tabBar显示的自定义,希望uni-app能跟进这部分的实现
https://developers.weixin.qq.com/miniprogram/dev/framework/ability/custom-tabbar.html

**Comment by hbcui1984** [comment]
设置角标、增加红点是支持的，参考：[uni.setTabBarBadge(OBJECT)](https://uniapp.dcloud.io/api/ui/tabbar?id=settabbarbadge)、[uni.showTabBarRedDot(OBJECT)](https://uniapp.dcloud.io/api/ui/tabbar?id=showtabbarreddot)

**Comment by dsonet** [comment]
@hbcui1984 ,谢谢. 

> 显示 tabBar 某一项的右上角的红点

这个是固定位置.是否能增加位置的指定呢? 另外角标的效果也没办法customize.

**Comment by hbcui1984** [comment]
> @hbcui1984 ,谢谢.
> 
> > 显示 tabBar 某一项的右上角的红点
> 
> 这个是固定位置.是否能增加位置的指定呢? 另外角标的效果也没办法customize.

目前不支持，也暂未列入产品计划

**Comment by wupeaking** [comment]
uni.setTabBarBadge(OBJECT) 不支持支付宝小程序， 有没有其他方案可以在支付宝小程序上实现这个功能呢? @hbcui1984

**Comment by aiplat** [comment]
官网本身没支持支付宝。建议自己做底部菜单。
