### ISSUE TITLE
期望条件编译加入 ios Android区分 

### ISSUE THREAD

**Issue by mrchzh** [dcloudio/uni-app#2101]
**新功能描述**
期望条件编译加入 ios Android区分 

**现状及问题**
虽然这里写的很清楚“
Android 和 iOS 平台不支持通过条件编译来区分，如果需要区分 Android、iOS 平台，请通过调用 uni.getSystemInfo 来获取平台信息。支持ifios、ifAndroid代码块，可方便编写判断。“

假如我有一个功能是安卓跟小程序特有的ios没有，那这时候页面上就很尴尬了，而且还需要增加额外的代码来判断

**尝试方案**
条件为 app || mp-weixin 然后里面再写一个判断即可。。

**补充信息**
[其它你认为有参考价值的信息]

**Comment by mlsjla** [comment]
确实希望能加入。
这样可以大大减少包的大小哦~~~

**Comment by zhetengbiji** [comment]
编译是不区分iOS和安卓的，你们是希望能分别编译iOS和安卓的包吗？

**Comment by mlsjla** [comment]
增加下面的两个标签

**Comment by mlsjla** [comment]
`






`

**Comment by mlsjla** [comment]
#ifdef APP-PLUS-IOS
 #ifdef APP-PLUS-ANDROID

**Comment by zhetengbiji** [comment]
目前编译的时候没办法区分是iOS还是安卓，你是想分别编译iOS和安卓的包吗？

**Comment by mrchzh** [comment]
其实我没太读明白这句话“目前编译的时候没办法区分是iOS还是安卓，你是想分别编译iOS和安卓的包吗？”  编译时不能区分iOS跟安卓么？可以的吧？  还有为啥要"分别编译"iOS跟安卓？它的条件编译 不是遇到正确了就把代码加入到待编译代码里面去么..小菜鸟不知道他这个编译到底是怎么弄得

**Comment by zhetengbiji** [comment]
运行的时候才能判断当前设备类型，编译的时候目前无法判断用户设备是iOS还是安卓。

**Comment by mlsjla** [comment]
@zhetengbiji  确实存在这个问题。 除非改编译流程。 安卓和ios生成不同的资源对吗？  然后再用不同资源打包app

**Comment by zhetengbiji** [comment]
> @zhetengbiji 确实存在这个问题。 除非改编译流程。 安卓和ios生成不同的资源对吗？ 然后再用不同资源打包app

对，现在资源是用的一套，如果区分的话，需要编译两套，包括离线打包和热更新都需要两套。

**Comment by Otto-J** [comment]
https://uniapp.dcloud.net.cn/tutorial/platform.html
