### ISSUE TITLE
___darwin_check_fd_set_overflow

### ISSUE THREAD

**Issue by droidsde** [dcloudio/uni-app#2106]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
ios云打包时候编译错误 ___darwin_check_fd_set_overflow
**复现步骤**
[复现问题的步骤]
使用云打包编译

这个错误是云端打包版本的Xcode是11.3，需要升级到最新版本的Xcode，这个是Xcode的bug
最新版的Xcode在编译socket的FD_SET等函数时出现了问题，导致和旧版本不兼容。

**Comment by caizi12** [comment]
最近使用flutter搭建android开发环境启动avd时候也报一个错，电脑是mac os 1.0.14.6

`dyld: lazy symbol binding failed: Symbol not found: ___darwin_check_fd_set_overflow
  Referenced from: ../emulator/lib64/libandroid-emu-curl.dylib (which was built for Mac OS X 11.1)
  Expected in: /usr/lib/libSystem.B.dylib`

电脑未装xcode，开发android理论不需要吧，是否安装上就ok了？
