### ISSUE TITLE
uniapp支持在onLauch生命周期里做异步，可以阻塞createApp或者createPage

### ISSUE THREAD

**Issue by uWydnA** [dcloudio/uni-app#2109]
**新功能描述**
uniapp编译字节小程序产物时，支持在onLauch生命周期里做异步，可以阻塞createApp或者createPage

**现状及问题**
vue template里的文案依赖一个文案托管平台返回的数据，结合I18N去做，但无法目前任何生命周期里都无法阻塞第一个页面的生成，如果第一个页面有用到任何I18N里的内容，会报错或者undefined，不仅template里的内容会报错，第一个页面<script>标签里的import的包如果有用这个异步返回的数据，都会报错

**尝试方案**
做一个独立空白loading页面，在onLoad中去await异步数据，然后跳转实际的页面

**补充信息**
无

**Comment by zhetengbiji** [comment]
第一个页面由框架加载，无法阻塞
