### ISSUE TITLE
uniapp打包后如何让static里面的文件也加个hash码

### ISSUE THREAD

**Issue by 18696232390** [dcloudio/uni-app#2110]
![image](https://user-images.githubusercontent.com/44156273/92565589-77b78000-f2ad-11ea-91aa-cb6516582b60.png)
现在打完包后，里面的图片，js都没有hash码，如果把前端缓存进浏览器后，那么每次修改图片都要修改名称

**Comment by zhetengbiji** [comment]
#1183

**Comment by 18696232390** [comment]
没改，版本是最新的，static里面的图片都是正常的名字，比如 abc.png, 能不能打包的时候弄成 abc.o43j2b4.png

**Comment by fxy060608** [comment]
> 没改，版本是最新的，static里面的图片都是正常的名字，比如 abc.png, 能不能打包的时候弄成 abc.o43j2b4.png

static里的图片，都是原封不动copy过去的
如果想启用资源的hash处理，需要使用相对路径引用，修改为相对路径后，查看build编译后的资源，在img里边，应该可以找到对应的加了hash的文件
`<image class="logo" src="../../static/logo.png"></image>`

**Comment by hongdou0216** [comment]
可以尽快增加绝对路径的图片加hash的功能吗

**Comment by fxy060608** [comment]
> 可以尽快增加绝对路径的图片加hash的功能吗

这属于vue的标准规范，绝对路径，原样保留
参考：https://vue-loader.vuejs.org/zh/guide/asset-url.html#%E8%BD%AC%E6%8D%A2%E8%A7%84%E5%88%99
