### ISSUE TITLE
在批量上传图片的时候使用参数files出现的问题

### ISSUE THREAD

**Issue by aoyoo111** [dcloudio/uni-app#212]
**问题描述**
在批量上传图片的时候使用参数files,成功上传后返回的结果不管是几张图片,只能返回一个图片的结果

**复现步骤**
在批量上传图片的时候使用参数files,成功上传后返回的结果不管是几张图片,只能返回一个图片的结果

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 Android 7.0+
 - HBuilderX版本 1.6.2.20190220

**Comment by hulinNeil** [comment]
确认下那么是否相同
![image](https://user-images.githubusercontent.com/24296884/53629289-29510c00-3c48-11e9-950a-4c9095fe7598.png)
