### ISSUE TITLE
cli 创建 typescript 项目无法在浏览器中调试 .vue 文件

### ISSUE THREAD

**Issue by fightingcat** [dcloudio/uni-app#2120]
**问题描述**
cli创建项目，模板选 typescript，在浏览器中调试没有 .vue 的 sourcemap，只有 webpack-internal:// 的，没有 uni-app:// 的。

**复现步骤**
用 cli 创建 typescript 项目并运行。

**预期结果**
devtool 中应该能看到 .vue 源文件并进行调试。

**实际结果**
devtool 中看不到正确的 .vue 源文件，只有 webpack 编译成 js 的。

**系统信息:**
 - 发行平台: H5平台
 - 操作系统: Windows 10
 - uni-app版本
    ```
   uni-app v2.8.11
   uni-app cli v2.0.0-28920200907001
   ```

**Comment by fightingcat** [comment]
经过尝试发现是.vue文件中如果使用就会这样，不使用ts就没问题。

**Comment by xueleilei** [comment]
这个问题还没解决吗
