### ISSUE TITLE
slot中input v-model绑定的值不会被清除

### ISSUE THREAD

**Issue by myhyd** [dcloudio/uni-app#213]
如下：新建组件test.vue

	<view class="test-wrap" v-show="visible">
		<view>这是带插槽的组件</view>
		<slot></slot>
	</view>

	export default {
		props: {
			visible: {
				type: Boolean,
				default: false
			}
		},
		data() {
			return {
				
			}
		}
	}

再建一个组件index.vue

	<view>
		<view class="uni-padding-wrap uni-common-mt">
			<switch @change="switch2Change" />
                        <button type="primary" @tap="confirm">点击清空</button>
		</view>
		<test :visible="visible">
			<view style="padding: 20px;background-color: #00BFFF;">
				<input type="text" v-model="content" value="" placeholder="请输入..." />
			</view>
		</test>
	</view>

	引入test组件
	export default {
		components: {
			Test
		},
		data() {
			return {
				title: 'switch',
				visible: false,
				content: ''
			}
		},
		methods: {
			switch2Change: function (e) {
				this.visible = e.target.value;
			},
			confirm() {
				console.log('clear content!');
				this.content = '';
			}
		}
	}

运行到手机，输入内容之后点击按钮清空输入框，输入框内容还在

**Comment by hulinNeil** [comment]
目前使用this.xxx = ""清除v-modal确实存在此问题,你可以在 this.xx = " ",在里面加一个空格应该就没问题了，此问题我们会在后续版本修复

**Comment by zhetengbiji** [comment]
HBuilderX 自 1.8 版本开始，新增自定义组件编译模式，优化对 slot 等的支持情况。[uni-app新老编译模式差异说明](https://ask.dcloud.net.cn/article/35843)

**Comment by zyzaoligei** [comment]
这个问题修复了啊，五年多了

**Comment by zyzaoligei** [comment]
这个问题修复了吗，五年多了
