### ISSUE TITLE
小程序分包优化，让用户可以自行配置当有几个分包共同依赖同一个文件时才打包到主包里

### ISSUE THREAD

**Issue by lbb00** [dcloudio/uni-app#2133]
**新功能描述**
RT.
让用户自己配置有几个分包共同依赖同一个文件时才打包到主包里

**现状及问题**

小程序开启分包优化后，会按照如下规则执行优化策略

```javascript
        const isMainPackage = ( // 非分包 或 两个及以上分包 或 主包内有使用
          matchSubPackagesCount === 0 ||
          matchSubPackagesCount > 1 ||
          (
            matchSubPackagesCount === 1 &&
            hasMainPackage(chunks)
          )
        )
```

这会导致，当公用组件过多时，由于引用判断为count >1，大量的组件都被打到了主包里。
再加之微信小程序对主包和分包的大小限制不合理，统一限制为2M，主包承载了太多通用的组件，极容易超出2M的大小，而分包却远不用担心超出大小的问题。
我们有一个小程序，尽管只有4个tabbar的页面放到了主包中，因上述原因，build后主包的大小仍然超过了2M。

**尝试方案**

既然小程序主包和分包大小都限制为2M，当主包容量不够时，完全可以牺牲分包的体积。将部分组件尝试打包到每个分包里，而不是集中在主包中。

```
optimization
对微信小程序的优化配置
属性 | 类型 | 说明
-- | -- | --
subPackages | Boolean | 是否开启分包优化
```

这里可以新增两个配置，excloud，minCount。minCount默认为1.

**Comment by loveonelong** [comment]
我尝试对split-chunks.js 做魔改，但它报了TypeError: Cannot read property 'call' of undefined这样的错误。

**Comment by loveonelong** [comment]
@fxy060608  uini对issues的回复有点慢啊

**Comment by fxy060608** [comment]
分包优化目前只会处理引入的 js 文件，如果想对vue组件分包优化，需要把vue组件放到对应的分包目录。

**Comment by loveonelong** [comment]
> 分包优化目前只会处理引入的 js 文件，如果想对vue组件分包优化，需要把vue组件放到对应的分包目录。

我们现在遇到的问题在于，uniapp会将公用组件都放在主包里，导致主包超过了体积。

**Comment by yiqianglin** [comment]
> **新功能描述**
> RT.
> 让用户自己配置有几个分包共同依赖同一个文件时才打包到主包里
> 
> **现状及问题**
> 
> 小程序开启分包优化后，会按照如下规则执行优化策略
> 
> ```js
>         const isMainPackage = ( // 非分包 或 两个及以上分包 或 主包内有使用
>           matchSubPackagesCount === 0 ||
>           matchSubPackagesCount > 1 ||
>           (
>             matchSubPackagesCount === 1 &&
>             hasMainPackage(chunks)
>           )
>         )
> ```
> 
> 这会导致，当公用组件过多时，由于引用判断为count >1，大量的组件都被打到了主包里。
> 再加之微信小程序对主包和分包的大小限制不合理，统一限制为2M，主包承载了太多通用的组件，极容易超出2M的大小，而分包却远不用担心超出大小的问题。
> 我们有一个小程序，尽管只有4个tabbar的页面放到了主包中，因上述原因，build后主包的大小仍然超过了2M。
> 
> **尝试方案**
> 
> 既然小程序主包和分包大小都限制为2M，当主包容量不够时，完全可以牺牲分包的体积。将部分组件尝试打包到每个分包里，而不是集中在主包中。
> 
> ```
> optimization
> 对微信小程序的优化配置
> 属性 | 类型 | 说明
> -- | -- | --
> subPackages | Boolean | 是否开启分包优化
> ```
> 
> 这里可以新增两个配置，excloud，minCount。minCount默认为1.

这里楼主有解决方案吗

**Comment by lbb00** [comment]
@yiqianglin 有一个内部改造方案

**Comment by yiqianglin** [comment]
> @yiqianglin 有一个内部根据 https://github.com/juddy-star/wxapp-thin 改造的方案

这个是对文件的直接迁移吧，如果项目里面用了复杂的路径（或者alias）就不好使了；请问大佬有没有办法可以直接在构建的时候做判断呢？
