### ISSUE TITLE
Hbuilder 小程序编译出现TypeError: Cannot read property 'forEach' of undefined，H5正常

### ISSUE THREAD

**Issue by MichaelGaoX** [dcloudio/uni-app#2134]
**问题描述**
小程序编译出现TypeError: Cannot read property 'forEach' of undefined，H5正常
尝试：
1、已经全局在forEach前判断
if(!Array){
  return
}
2、全局v-for 后有带key

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
 TypeError: Cannot read property 'forEach' of undefined
15:01:35.124     at callExprNode.arguments.(anonymous function).elements.map.slotNode (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/uni-template-compiler/lib/template/traverse.js:340:25)
15:01:35.125     at Array.map (<anonymous>)
15:01:35.137     at traverseResolveScopedSlots (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/uni-template-compiler/lib/template/traverse.js:336:45)
15:01:35.138     at traverseCallExpr (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/uni-template-compiler/lib/template/traverse.js:105:10)
15:01:35.151     at traverseExpr (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/uni-template-compiler/lib/template/traverse.js:66:12)
15:01:35.152     at dataNode.properties.forEach.property (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/uni-template-compiler/lib/template/traverse.js:188:43)
15:01:35.167     at Array.forEach (<anonymous>)
15:01:35.168     at traverseDataNode (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/uni-template-compiler/lib/template/traverse.js:181:23)
15:01:35.185     at traverseCreateElement (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/uni-template-compiler/lib/template/traverse.js:159:30)
15:01:35.186     at traverseCallExpr (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/uni-template-compiler/lib/template/traverse.js:105:10)
15:01:35.206     at traverseExpr (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/uni-template-compiler/lib/template/traverse.js:66:12)
15:01:35.206     at traverseRenderList (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/uni-template-compiler/lib/template/traverse.js:417:20)
15:01:35.222     at traverseCallExpr (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/uni-template-compiler/lib/template/traverse.js:105:10)
15:01:35.239     at traverseExpr (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/uni-template-compiler/lib/template/traverse.js:66:12)
15:01:35.240     at traverseCreateElement (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/uni-template-compiler/lib/template/traverse.js:171:41)
15:01:35.255     at traverseCallExpr (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/uni-template-compiler/lib/template/traverse.js:105:10)
15:01:39.693 Module build failed (from ./node_modules/@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/loaders/templateLoader.js):

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本 mac 2.8.11.20200907

**补充信息**

**Comment by xlzy520** [comment]
你可以看看你代码里面有没有设置了两个插槽的地方，然后还加了v-if

我今天调试了一下compiler/lib/template/traverse.js这个文件，找到了报错的文件

**Comment by xlzy520** [comment]
![image](https://user-images.githubusercontent.com/28336270/135428443-1efc5f88-4d7a-4138-b3eb-6f6b4de72a13.png)
![image](https://user-images.githubusercontent.com/28336270/135428719-2e99c9af-c363-443d-8c62-8da9858ed33e.png)
![image](https://user-images.githubusercontent.com/28336270/135428824-d2d37108-26a1-4b9c-9473-fd6a9322d1a6.png)


打印的state参数里面有个resourcePath参数可以看到出问题的源文件

**Comment by zhetengbiji** [comment]
后续版本已优化作用域插槽渲染。
