### ISSUE TITLE
希望增强TS在调用网络或者其他可以Promise化的Api的代码检查能力

### ISSUE THREAD

**Issue by luvletterldl** [dcloudio/uni-app#2140]
**新功能描述**
希望增强`cli`项目的`TS`的能力

**现状及问题**
没有使用`TS`的项目中使用官方内置的[`Promise 封装`](https://uniapp.dcloud.io/api/README?id=promise-%e5%b0%81%e8%a3%85)没有问题，但是`TS`版本中基本没有对官方文档已有的`Promise`化的`Api`做类型检查的完善，都是自己封装自己的，很不规范，希望官方出一个合理的解决方案，对了还有`await`的`uni.request`也希望能有类型检查。🙇‍🙇‍

**Comment by StrivingRabbit** [comment]
uni.request 有返回值，暂不处理，其他 api 的 Promise 化类型提示可以升级 @dcloudio/types@3.3.0 试试看
