### ISSUE TITLE
父组件传值给子组件，参数有prototype的方法或者属性，子组件无法接受

### ISSUE THREAD

**Issue by hatedMe** [dcloudio/uni-app#2141]
**问题描述**
[问题描述：父组件传值给子组件，参数有prototype的方法或者属性，子组件无法接受]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
```javascript
class Node {} 
Node.prototype.s = function() {
  console.log('this is Node methons')
};
const node = new Node();
node.attr = "file";

this.node.s(); //  error 
this.node.attr  // 'file'
```

**预期结果**

```javascript
this.node.s(); //  this is Node methons
this.node.attr  // 'file'
```

**实际结果**
```javascript
this.node.s(); //  error 
this.node.attr  // 'file'
```

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

- 组件传值可能用了浅拷贝或者深拷贝
- 组件传值可能用了浅拷贝或者深拷贝

**Comment by 2234839** [comment]
uni app 的组件传值使用的就是 JSON.stringify ,所以这样是不行的
