### ISSUE TITLE
websocket  bug

### ISSUE THREAD

**Issue by javwen** [dcloudio/uni-app#2144]
**问题描述**
Android 7.1 在安卓平台下，一开始连接上websocket,进入了回调onOpen,发送心跳也正常，后面关掉wifi，检测到无网络，我这边会调用close，但是调用close无效，当我恢复网络的时候进行重连，但是上一个socket没有关掉，在服务端还是存在着通道连接，导致我重新连接上来一个新的，服务端会被把第一个挤掉，关掉老的新的socket还会走onclose监听事件，且往老的socket发送消息也会在新的socket监听事件里面监听到，导致在onClose里面有重连的机制，会陷入死循环，浏览器端断网的情况下会触发服务端关掉连接，浏览器不会出现
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
恢复网络的时候调用上一个socketTask对象的close能够告知服务端关掉上一个socket通道，

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: 5+APP
 - Android 7.0
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
后续已优化websocket相关接口，如仍然有问题可继续反馈
