### ISSUE TITLE
【tabBar 兼容】tabBar文本在iPhone 8机器上无法完整展示

### ISSUE THREAD

**Issue by slowGyro** [dcloudio/uni-app#2146]
**问题描述**
tabBar文本在iPhone 8上无法完整展示，字体顶部出现截断现象。

**复现步骤**
1. 设置以下tabBar信息：
```
"tabBar": {
		"position": "bottom",
		"color": "#C0C6CE",
		"selectedColor": "#007AFF",
		"borderStyle":"#999999",
		"backgroundColor": "#FFFFFF",
		"list": [{
				"text": "首页",
				"pagePath": "pages/index/home/index"
			},
			{
				"text": "数据统计",
				"pagePath": "pages/statistics/summary"
			},
			{
				"text": "消息中心",
				"pagePath": "pages/notice/message"
			},
			{
				"text": "我的",
				"pagePath": "pages/user/mine"
			}
		]
	}

```

1. 在iPhone 8 上真机运行

**预期结果**
tabBar文本完整展示

**实际结果**
文本无法完整展示，字体顶部出现截断现象。
最明显的字体截断现象为“消息中心”的“息”字没有最上面的点。

**系统信息:**
 - 发行平台: IOS
 - 操作系统: iOS 14
 - HBuilderX版本: 2.8.11.20200907
 - uni-app版本: 
 - 设备信息: iPhone8

**补充信息**
在不修改代码的前提下，魅族16X不存在该问题，iPhone XR不存在该问题。
初步推断与机器屏幕大小相关

**Comment by zhetengbiji** [comment]
截图看下

**Comment by slowGyro** [comment]
![Uploading 1.png…]()

**Comment by slowGyro** [comment]
![1](https://user-images.githubusercontent.com/41093753/94328203-14cf2400-ffe3-11ea-88b1-2a2902993e9a.png)

**Comment by xiaohuapunk** [comment]
此问题已确认，iOS14 设备上有问题，下个版本修复

**Comment by zhetengbiji** [comment]
HBuilderX alpha 2.9.1+ 已修复
