### ISSUE TITLE
将uni-app代码转成可阅读、可修改的微信小程序代码

### ISSUE THREAD

**Issue by lirong098** [dcloudio/uni-app#2148]
**新功能描述**
希望，提供一个功能能将uni-app代码转成微信小程序可阅读，可修改的代码。

**现状及问题**
uni-app不更新，随着，业务越来越复杂，uni-app的兼容性越差，难以维护，希望能将现有的uni-app代码转成原生代码。

**尝试方案**
未找到

**Comment by zhetengbiji** [comment]
目前 uni-app 编译成小程序就是使用的小程序原生组件，但想要编译后的代码方便普通用户直接阅读和修改还有很长的路要走。

另外你说的兼容性是指的什么？
