### ISSUE TITLE
getSystemInfoSync返回的高度不正确

### ISSUE THREAD

**Issue by myhyd** [dcloudio/uni-app#215]
代码：
![image](https://user-images.githubusercontent.com/22100972/53237243-306c9d00-36d1-11e9-955a-c1f210edd716.png)

我在onLoad中执行uni.getSystemInfoSync()获取窗口高度,多次进入同一页面，

进入第一次是下边的截图，拿到的高度是572，宽度360
![image](https://user-images.githubusercontent.com/22100972/53237001-9ad10d80-36d0-11e9-9233-a1c8da97959c.png)

第二次拿到的高度是640，宽度360
![image](https://user-images.githubusercontent.com/22100972/53237049-b6d4af00-36d0-11e9-999b-6482f9ddfd3c.png)
，
 - 用了两部Android手机测试都有这个问题， 就是有时候是640有时候是572，我看了这俩差值应该就是statusBar + NavigationBar的高度，看文档的时候我注意到 “H5端windowHeight不包含NavigationBar和TabBar的高度” ，我猜想是不是判断h5和app这块有问题；

 -今天刚更新的 HBuilderX版本  ## 1.6.2.20190220

我看更新日志中有提到这个bug，望及时调整

**Comment by zhetengbiji** [comment]
使用语言描述你的问题

**Comment by zhetengbiji** [comment]
app端建议在页面的onReady时获取
