### ISSUE TITLE
ios14 XR选择日期就会显示bug

### ISSUE THREAD

**Issue by zaofanjun** [dcloudio/uni-app#2150]
![IMG_1860](https://user-images.githubusercontent.com/20752006/94394975-29511f00-0191-11eb-8737-c624b3af44d8.JPG)

官方示例里面选择日期也有显示bug，确认了应该是组件的问题，IOS14的机子上，未升级IOS14的机子显示正常

**Comment by fxy060608** [comment]
微信小程序自己的Bug
https://developers.weixin.qq.com/community/develop/doc/000426943b0ea87e86fa7bcfc51c00
