### ISSUE TITLE
canvas适配pc端

### ISSUE THREAD

**Issue by toKnowMore** [dcloudio/uni-app#2157]
目前canvas所提供的事件仅有touch相关,在pc模式下,完全不起作用,希望后续增加适配调整

**Comment by zhetengbiji** [comment]
事件后面增加 .native 修饰即可使用原生的事件

**Comment by zhetengbiji** [comment]
后续会对封装的鼠标事件进行处理

**Comment by zhetengbiji** [comment]
HBuilderX 2.9.6+ 鼠标事件已增加坐标信息
