### ISSUE TITLE
【报Bug】同样带签名的文件下载地址 安卓无法保存并打开！ 带图！

### ISSUE THREAD

**Issue by hiair2323** [dcloudio/uni-app#216]
详细问题描述（DCloud产品不会有明显的bug，所以你遇到的问题大都是在特定环境下才能重现的问题，请仔细描述你的环境和重现方式，否则DCloud很难排查解决你的问题）
[内容]

重现步骤
[步骤]对象存储带过期时间的签名网址请求 同条件下 测试 安卓 苹果 小程序
[结果]只有安卓保存到临时文件时 保存的全网址的名字
[期望]可以自定义文件标题 或者解决安卓这个bug
[如果语言难以表述清晰，可以拍一个视频或截图，有图有真相]

苹果正常

安卓失败

安卓下载不带签名的文件 正常
IDE运行环境说明
[HBuilder 或 HBuilderX]1.5.4
[IDE版本号]
[windows版本号]
[mac版本号]10.14.3

App运行环境说明
[Android版本号]7.1.2
[iOS版本号]12
[手机型号]vivo
[模拟器型号]

附件
[IDE问题请提供HBuilderX运行日志。菜单帮助-查看运行日志，点右键打开文件所在目录，将log文件压缩成zip包上传]
[App问题请提供可重现问题的代码片段，你补充的细一点，问题就解决的快一点]
[安装包]

联系方式
[QQ]

**Comment by zhetengbiji** [comment]
什么签名？有什么示例不？

**Comment by hiair2323** [comment]
> 什么签名？有什么示例不？

http://219.150.218.130:9000/files/-2018%E5%B9%B4%E6%B8%AF%E8%82%A1%E6%8A%95%E8%B5%84%E5%B1%95%E6%9C%9B%E6%8A%A5%E5%91%8A%EF%BC%9A%E4%B9%98%E9%A3%8E%E8%80%8C%E8%B5%B7%EF%BC%8C%E5%BC%BA%E8%80%85%E6%81%92%E5%BC%BA-20171212-%E5%B9%B3%E5%AE%89%E8%AF%81%E5%88%B8%EF%BC%88%E9%A6%99%E6%B8%AF%EF%BC%89-28%E9%A1%B5-2mb.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=B3XAEB56S9IDOX2UPEVC%2F20190304%2F%2Fs3%2Faws4_request&X-Amz-Date=20190304T035020Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=d0707f9ea810ae1285456437577311f05f06b589e4e14f179a30b3c464339543

**Comment by hiair2323** [comment]
> 什么签名？有什么示例不？

你试下 只有安卓保存不了 因为保存的名字带签名了 所以无法保存 更无法打开

**Comment by zhetengbiji** [comment]
> > 什么签名？有什么示例不？
> 
> http://219.150.218.130:9000/files/-2018%E5%B9%B4%E6%B8%AF%E8%82%A1%E6%8A%95%E8%B5%84%E5%B1%95%E6%9C%9B%E6%8A%A5%E5%91%8A%EF%BC%9A%E4%B9%98%E9%A3%8E%E8%80%8C%E8%B5%B7%EF%BC%8C%E5%BC%BA%E8%80%85%E6%81%92%E5%BC%BA-20171212-%E5%B9%B3%E5%AE%89%E8%AF%81%E5%88%B8%EF%BC%88%E9%A6%99%E6%B8%AF%EF%BC%89-28%E9%A1%B5-2mb.pdf?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=B3XAEB56S9IDOX2UPEVC%2F20190304%2F%2Fs3%2Faws4_request&X-Amz-Date=20190304T035020Z&X-Amz-Expires=604800&X-Amz-SignedHeaders=host&X-Amz-Signature=d0707f9ea810ae1285456437577311f05f06b589e4e14f179a30b3c464339543

资源失效

**Comment by hiair2323** [comment]
过期时间最大7天。。。。。你直接联系我qq好吧 方便复现处理 2083二二0015

**Comment by hiair2323** [comment]
16:48:13.182  _doc/uniapp_temp_1553849281971/download/2017%E5%B9%B4%E4%B8%AD%E5%9B%BD%E4%B8%93%E5%88%A9%E8%B0%83%E6%9F%A5%E6%8A%A5%E5%91%8A.pdf?Expires=1553852852&OSSAccessKeyId=TMP.AQEBrlC9HptQh7g9lunKjkiHtCHvCQ8rHiu-azEqXOcoEkpHEr-y0v3fWFnPMC4CFQCecgjXmaA1KMRRAaaj_f1Mf9le9AIVAKlbpSFuSDkXtKxcth98VKQ7CQZT&Signature=iZvAUjrPuNk8%2FCUi1roNXDkVMvw%3D at pages/info/info.vue:725
16:48:13.369  _doc/uniapp_save/1553849293862.AQEBrlC9HptQh7g9lunKjkiHtCHvCQ8rHiu-azEqXOcoEkpHEr-y0v3fWFnPMC4CFQCecgjXmaA1KMRRAaaj_f1Mf9le9AIVAKlbpSFuSDkXtKxcth98VKQ7CQZT&Signature=iZvAUjrPuNk8%2FCUi1roNXDkVMvw%3D at pages/info/info.vue:731
16:48:41.652  App Hide at App.vue:10

**Comment by dcloudhdx** [comment]
bug已修复
