### ISSUE TITLE
使用@vue/composition-api引入vue组件在小程序端无效

### ISSUE THREAD

**Issue by ianho7** [dcloudio/uni-app#2166]
**问题描述**
使用@vue/composition-api，创建Vue组件，在页面中引入使用，H5端正常，小程序端无效

**复现步骤**

组件源码：
<img width="853" alt="WeChatae7b2597c18d4676b76f7b8f409917b4" src="https://user-images.githubusercontent.com/26101033/95644290-41596480-0ae8-11eb-82dd-241769195b25.png">

页面引入：
<img width="934" alt="WeChatb49c6f88d8cc48397cf440c413330f8d" src="https://user-images.githubusercontent.com/26101033/95644322-76fe4d80-0ae8-11eb-8f8b-afe0929f2ccc.png">

**实际结果**
H5端正常：
<img width="390" alt="WeChatd3707b5740ce5c1707c06a73863e5ccf" src="https://user-images.githubusercontent.com/26101033/95644344-a1e8a180-0ae8-11eb-83ae-1de7ea48ec06.png">

小程序端不显示：
<img width="386" alt="WeChat98be70a6ae183468a60412696e0319e2" src="https://user-images.githubusercontent.com/26101033/95644361-b5940800-0ae8-11eb-8044-d770f9de77a3.png">
<img width="380" alt="WeChatc069e842a248c97cc27dcc5a42d74639" src="https://user-images.githubusercontent.com/26101033/95644370-cb093200-0ae8-11eb-9e34-65001cda2395.png">

**系统信息:**
 - uni-app版本：uni-app v2.9.1 uni-app cli v2.0.0-alpha-29120200927002

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
目前暂不支持通过 defineComponent 定义组件，你可以移除 defineComponent 测试下

**Comment by impacnHo** [comment]
> 目前暂不支持通过 defineComponent 定义组件，你可以移除 defineComponent 测试下

好的，我试下，还有请问下Vue3的什么时候可以正式支持？官网那篇文章给的方法完全无用

**Comment by fxy060608** [comment]
> > 目前暂不支持通过 defineComponent 定义组件，你可以移除 defineComponent 测试下
> 
> 好的，我试下，还有请问下Vue3的什么时候可以正式支持？官网那篇文章给的方法完全无用

完全无用是什么意思？目前vue3仅支持小程序

**Comment by impacnHo** [comment]
> > > 目前暂不支持通过 defineComponent 定义组件，你可以移除 defineComponent 测试下
> > 
> > 
> > 好的，我试下，还有请问下Vue3的什么时候可以正式支持？官网那篇文章给的方法完全无用
> 
> 完全无用是什么意思？目前vue3仅支持小程序

我按照上面的方法构建项目，发现依赖还是Vue2.6，[https://ask.dcloud.net.cn/article/37834](地址)

**Comment by impacnHo** [comment]
> > > 目前暂不支持通过 defineComponent 定义组件，你可以移除 defineComponent 测试下
> > 
> > 
> > 好的，我试下，还有请问下Vue3的什么时候可以正式支持？官网那篇文章给的方法完全无用
> 
> 完全无用是什么意思？目前vue3仅支持小程序

我按照上面的方法构建项目，发现依赖还是Vue2.6，[https://ask.dcloud.net.cn/article/37834](url)

**Comment by impacnHo** [comment]
> > > 目前暂不支持通过 defineComponent 定义组件，你可以移除 defineComponent 测试下
> > 
> > 
> > 好的，我试下，还有请问下Vue3的什么时候可以正式支持？官网那篇文章给的方法完全无用
> 
> 完全无用是什么意思？目前vue3仅支持小程序

地址：https://ask.dcloud.net.cn/article/37834，之前试了下，按照上面的方法构建项目，依赖还是Vue2.6的，评论也有提及到，但是官方还没回应

**Comment by fxy060608** [comment]
> > > > 目前暂不支持通过 defineComponent 定义组件，你可以移除 defineComponent 测试下
> > > 
> > > 
> > > 好的，我试下，还有请问下Vue3的什么时候可以正式支持？官网那篇文章给的方法完全无用
> > 
> > 
> > 完全无用是什么意思？目前vue3仅支持小程序
> 
> 地址：[https://ask.dcloud.net.cn/article/37834，之前试了下，按照上面的方法构建项目，依赖还是Vue2.6的，评论也有提及到，但是官方还没回应](https://ask.dcloud.net.cn/article/37834%EF%BC%8C%E4%B9%8B%E5%89%8D%E8%AF%95%E4%BA%86%E4%B8%8B%EF%BC%8C%E6%8C%89%E7%85%A7%E4%B8%8A%E9%9D%A2%E7%9A%84%E6%96%B9%E6%B3%95%E6%9E%84%E5%BB%BA%E9%A1%B9%E7%9B%AE%EF%BC%8C%E4%BE%9D%E8%B5%96%E8%BF%98%E6%98%AFVue2.6%E7%9A%84%EF%BC%8C%E8%AF%84%E8%AE%BA%E4%B9%9F%E6%9C%89%E6%8F%90%E5%8F%8A%E5%88%B0%EF%BC%8C%E4%BD%86%E6%98%AF%E5%AE%98%E6%96%B9%E8%BF%98%E6%B2%A1%E5%9B%9E%E5%BA%94)

package.json中的依赖不影响，本身用的也不是它，我们内置了自己的vue3引擎

**Comment by impacnHo** [comment]
> > > > > 目前暂不支持通过 defineComponent 定义组件，你可以移除 defineComponent 测试下
> > > > 
> > > > 
> > > > 好的，我试下，还有请问下Vue3的什么时候可以正式支持？官网那篇文章给的方法完全无用
> > > 
> > > 
> > > 完全无用是什么意思？目前vue3仅支持小程序
> > 
> > 
> > 地址：[https://ask.dcloud.net.cn/article/37834，之前试了下，按照上面的方法构建项目，依赖还是Vue2.6的，评论也有提及到，但是官方还没回应](https://ask.dcloud.net.cn/article/37834%EF%BC%8C%E4%B9%8B%E5%89%8D%E8%AF%95%E4%BA%86%E4%B8%8B%EF%BC%8C%E6%8C%89%E7%85%A7%E4%B8%8A%E9%9D%A2%E7%9A%84%E6%96%B9%E6%B3%95%E6%9E%84%E5%BB%BA%E9%A1%B9%E7%9B%AE%EF%BC%8C%E4%BE%9D%E8%B5%96%E8%BF%98%E6%98%AFVue2.6%E7%9A%84%EF%BC%8C%E8%AF%84%E8%AE%BA%E4%B9%9F%E6%9C%89%E6%8F%90%E5%8F%8A%E5%88%B0%EF%BC%8C%E4%BD%86%E6%98%AF%E5%AE%98%E6%96%B9%E8%BF%98%E6%B2%A1%E5%9B%9E%E5%BA%94)
> 
> package.json中的依赖不影响，本身用的也不是它，我们内置了自己的vue3引擎

😯再请教下，那像ref、computed这些api需要怎么引入呢？或者有没有一些demo，因为看官方的preset还是用的Vue2的语法

**Comment by fxy060608** [comment]
跟 vue3 用法一样，import 进来即可使用
```js
<template>
    <view class="content">
        <image class="logo" src="/static/logo.png"></image>
        <view @click="updateReadersNumber">
            <text class="title">{{title}}</text>
            <text class="title">{{book.title}}:{{readersNumber}}</text>
        </view>
    </view>
</template>

<script>
    import {
        ref,
        reactive,
        onLoad
    } from 'vue'
    export default {
        setup() {
            const readersNumber = ref(0)
            const book = reactive({
                title: 'Vue 3 Guide'
            })
            onLoad(() => console.log('onLoad'))
            const updateReadersNumber = function() {
                readersNumber.value++
            }
            return {
                title: 'hello',
                readersNumber,
                updateReadersNumber,
                book
            }
        }
    }
</script>

<style>
    .content {
        text-align: center;
        height: 400rpx;
    }

    .logo {
        height: 200rpx;
        width: 200rpx;
        margin-top: 200rpx;
    }

    .title {
        font-size: 36rpx;
        color: #8f8f94;
    }
</style>

```

**Comment by impacnHo** [comment]
> 跟 vue3 用法一样，import 进来即可使用
> 
> ```js
> <template>
>     <view class="content">
>         <image class="logo" src="/static/logo.png"></image>
>         <view @click="updateReadersNumber">
>             <text class="title">{{title}}</text>
>             <text class="title">{{book.title}}:{{readersNumber}}</text>
>         </view>
>     </view>
> </template>
> 
> <script>
>     import {
>         ref,
>         reactive,
>         onLoad
>     } from 'vue'
>     export default {
>         setup() {
>             const readersNumber = ref(0)
>             const book = reactive({
>                 title: 'Vue 3 Guide'
>             })
>             onLoad(() => console.log('onLoad'))
>             const updateReadersNumber = function() {
>                 readersNumber.value++
>             }
>             return {
>                 title: 'hello',
>                 readersNumber,
>                 updateReadersNumber,
>                 book
>             }
>         }
>     }
> </script>
> 
> <style>
>     .content {
>         text-align: center;
>         height: 400rpx;
>     }
> 
>     .logo {
>         height: 200rpx;
>         width: 200rpx;
>         margin-top: 200rpx;
>     }
> 
>     .title {
>         font-size: 36rpx;
>         color: #8f8f94;
>     }
> </style>
> ```

感谢🙏请问下Vue3大概什么时候更新至正式版

**Comment by UlricGan** [comment]
> 目前暂不支持通过 defineComponent 定义组件，你可以移除 defineComponent 测试下

存在babel编译问题，可以patch源码修改
```
diff --git a/node_modules/@dcloudio/webpack-uni-mp-loader/lib/babel/scoped-component-traverse.js b/node_modules/@dcloudio/webpack-uni-mp-loader/lib/babel/scoped-component-traverse.js
index 42e3205..60a922f 100644
--- a/node_modules/@dcloudio/webpack-uni-mp-loader/lib/babel/scoped-component-traverse.js
+++ b/node_modules/@dcloudio/webpack-uni-mp-loader/lib/babel/scoped-component-traverse.js
@@ -99,6 +99,10 @@ module.exports = function (ast, state = {
             handleObjectExpression(args[0], path, state)
           }
         }
+      } else if (t.isCallExpression(declaration) &&
+        t.isIdentifier(declaration.callee) &&
+        declaration.callee.name === 'defineComponent') {
+        handleObjectExpression(declaration.arguments[0], path, state)
       }
     }
   })

**Comment by TuiMao233** [comment]
目前有木有更好的解决方法，修改源码来说太麻烦了

**Comment by ianho7** [comment]
> 目前有木有更好的解决方法，修改源码来说太麻烦了

后来我换隔壁Taro了就没关注了

**Comment by TuiMao233** [comment]
这个问题貌似新版已经修复了，我用的旧版脚手架。

**Comment by Tonysmark** [comment]
巧了  我这边是小程序没问题, 编译H5报错

**Comment by ruinb0w** [comment]
> 跟 vue3 用法一样，import 进来即可使用
> 
> ```js
> <template>
>     <view class="content">
>         <image class="logo" src="/static/logo.png"></image>
>         <view @click="updateReadersNumber">
>             <text class="title">{{title}}</text>
>             <text class="title">{{book.title}}:{{readersNumber}}</text>
>         </view>
>     </view>
> </template>
> 
> <script>
>     import {
>         ref,
>         reactive,
>         onLoad
>     } from 'vue'
>     export default {
>         setup() {
>             const readersNumber = ref(0)
>             const book = reactive({
>                 title: 'Vue 3 Guide'
>             })
>             onLoad(() => console.log('onLoad'))
>             const updateReadersNumber = function() {
>                 readersNumber.value++
>             }
>             return {
>                 title: 'hello',
>                 readersNumber,
>                 updateReadersNumber,
>                 book
>             }
>         }
>     }
> </script>
> 
> <style>
>     .content {
>         text-align: center;
>         height: 400rpx;
>     }
> 
>     .logo {
>         height: 200rpx;
>         width: 200rpx;
>         margin-top: 200rpx;
>     }
> 
>     .title {
>         font-size: 36rpx;
>         color: #8f8f94;
>     }
> </style>
> ```

h5报错The requested module '/@fs/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli-vite/node_modules/@dcloudio/uni-h5-vue/dist/vue.runtime.esm.js' does not provide an export named 'onLoad'
