### ISSUE TITLE
Hbuilderx编译成小程序后乱码

### ISSUE THREAD

**Issue by kq12** [dcloudio/uni-app#2169]
我用Hbuilderx新建了一个uni-app工程，然后点击运行-->运行到小程序模拟器-->微信开发者工具，会自动打开微信开发者工具，**但是不会打开项目工程**，手动打开后，里边的文件全都是显示【此文件是二进制文件或使用了不支持的文件编码，无法在编辑器中显示，是否仍要打开？】。在Hbuilderx里打开也是一样的。
![image](https://user-images.githubusercontent.com/20240369/95647485-6c50b200-0b02-11eb-99ea-3276c6342a0a.png)
如果点击打开，就全部是乱码。在文本编辑器里打开是正常不乱码的。请问怎么解决？

**Comment by wenzirang** [comment]
跟帖

**Comment by pdc-cool** [comment]
+1

**Comment by yangkebiao** [comment]
你们公司可能存在磁盘加密软件
