### ISSUE TITLE
@dcloudio/types@2.0.8 GetSystemInfoResult 类型定义错误

### ISSUE THREAD

**Issue by huadong** [dcloudio/uni-app#2172]
GetSystemInfoResult类型，

        /**
         * 客户端基础库版本
         */
        SDKVersion: string;

定义应该为：
        SDKVersion?: string;

支付宝小程序没有这个值。

**Comment by zhetengbiji** [comment]
https://uniapp.dcloud.io/api/system/info?id=getsysteminfo

**Comment by huadong** [comment]
> https://uniapp.dcloud.io/api/system/info?id=getsysteminfo

@zhetengbiji 是这个包@dcloudio/types定义错了，版本为：2.0.8。

**Comment by zhetengbiji** [comment]
> > https://uniapp.dcloud.io/api/system/info?id=getsysteminfo
> 
> @zhetengbiji 是这个包@dcloudio/types定义错了，版本为：2.0.8。

没有错，我给你发的是文档，文档里有不同属性在不同平台的支持情况

**Comment by huadong** [comment]
> > > https://uniapp.dcloud.io/api/system/info?id=getsysteminfo
> > 
> > 
> > @zhetengbiji 是这个包@dcloudio/types定义错了，版本为：2.0.8。
> 
> 没有错，我给你发的是文档，文档里有不同属性在不同平台的支持情况

嗯，这种定义，其实也没有对、错。跨平台兼容太多有差异性的东西了。typescript的定义走2/8原则就好。
