### ISSUE TITLE
uni.chooseImage tempFilePaths为空

### ISSUE THREAD

**Issue by zhzhh7378** [dcloudio/uni-app#2173]
**问题描述**
[uni.chooseImage tempFilePaths为空]

**复现步骤**

[uni.chooseImage({
        // count: 1, //默认9
        sizeType: ["original", "compressed"], //可以指定是原图还是压缩图，默认二者都有
        sourceType: ['album'], //从相册选择
        success: res => {
			 console.log("结果"+ JSON.stringify(res));
			 if(res.tempFilePaths){
				 let paths = res.tempFilePaths
				   .filter(f => {
				     console.log("结果", f);
				     return f ? true : false;
				   })
				   .map(e => {
				     return { localPath: e };
				   });
				 if (this.imgList.length != 0) {
				   this.imgList = this.imgList.concat(paths);
				 } else {
				   this.imgList = paths;
				 }
			 }
        },
		fail: (err) => {
			// #ifdef APP-PLUS
			if (err['code'] && err.code !== 0 && this.sourceTypeIndex === 2) {
				this.checkPermission(err.code);
			}
			// #endif
			// #ifdef MP
			uni.getSetting({
				success: (res) => {
					let authStatus = false;
					switch (this.sourceTypeIndex) {
						case 0:
							authStatus = res.authSetting['scope.camera'];
							break;
						case 1:
							authStatus = res.authSetting['scope.album'];
							break;
						case 2:
							authStatus = res.authSetting['scope.album'] && res.authSetting['scope.camera'];
							break;
						default:
							break;
					}
					if (!authStatus) {
						uni.showModal({
							title: '授权失败',
							content: '需要从您的相机或相册获取图片，请在设置界面打开相关权限',
							success: (res) => {
								if (res.confirm) {
									uni.openSetting()
								}
							}
						})
					}
				}
			})
			// #endif
		}
      });]

**预期结果**
[返回图片的信息]

**实际结果**
[ 结果{"errMsg":"chooseImage:ok"}]
![image](https://user-images.githubusercontent.com/14539415/95702897-3c2f1d80-0c80-11eb-9bf6-c0909afec8db.png)

**系统信息:**
 - 发行平台: [5+ App]
 - 操作系统 [Android 10]
 - HBuilderX版本 [2.8.13.20200927]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [小米8青春版、redmi k30]

**补充信息**
[权限检查没问题]
[部分早期Android机型没问题]

**Comment by zhzhh7378** [comment]
![image](https://user-images.githubusercontent.com/14539415/95954717-4f7feb80-0e2e-11eb-8c0b-5de9eb985e83.png)
发现选择相册图片时有的文件夹能选择成功有的不能返回图片，DCIM 文件夹和weixin 文件夹的图片都能选中，系统相册不能正常返回选中的图片。

**Comment by dcloudhdx** [comment]
Android 10 调整了权限控制，更新 HBuilderX 2.9.2+

**Comment by zhzhh7378** [comment]
升级了Hbuilder 另外在调用 uni.chooseImage 前加权限申请的代码，问题解决了。
