### ISSUE TITLE
请问下对Vue3的支持是运行时还是编译时

### ISSUE THREAD

**Issue by Silentdoer** [dcloudio/uni-app#2179]
对Vue3的支持是编译的时候就OK了，还是说是运行的时候判断呢？或者说支持Vue3会不会因为兼容多种写法【兼容多种情况，比如不同的生命周期，一些作废的api等】而导致性能问题？

**Comment by Silentdoer** [comment]
或者说如果只支持Vue3是否会比同时支持Vue2和Vue3更快？

**Comment by fxy060608** [comment]
vue3和vue2是两套不同的编译器和运行时
