### ISSUE TITLE
图片上传选择图片时有些图片会歪

### ISSUE THREAD

**Issue by wangjinxin613** [dcloudio/uni-app#218]
**问题描述**
图片上传选择图片时有些图片会歪

**复现步骤**
机型：小米8
选择一张由摄像头拍摄的照片，大部分的图片会倾斜90度，并非所有的照片都会倾斜。

**Comment by aiplat** [comment]
上传到其他app会这样吗

**Comment by hockor** [comment]
> **问题描述**
> 图片上传选择图片时有些图片会歪
> 
> **复现步骤**
> 机型：小米8
> 选择一张由摄像头拍摄的照片，大部分的图片会倾斜90度，并非所有的照片都会倾斜。

如果你做前端H5开发经验多的话肯定会遇到的，这应该不是框架的问题，给个提示：Exif.js。

**Comment by wangjinxin613** [comment]
> 上传到其他app会这样吗

有些会

**Comment by zlusers** [comment]
请问这个问题解决了吗？ 使用谷歌浏览器，图片太大 就会旋转

**Comment by zxzhgk** [comment]
判断一下图片的朝向属性，这是手机拍照图片问题，跟平台无关

**Comment by dcloudhdx** [comment]
因为压缩图片后 exif 头信息丢失导致，HBuilderX 2.2.5.20190907-alpha 已修复
