### ISSUE TITLE
:class 不能使用字符串模板

### ISSUE THREAD

**Issue by 0131LWG** [dcloudio/uni-app#2182]
**问题描述**
在使用时不能使用:class 字符串模板

**复现步骤**
<img width="514" alt="WeChatce166fb092d50b1cb24ca82a6fbd103f" src="https://user-images.githubusercontent.com/30310735/95956539-07ae9380-0e31-11eb-94a1-6d8b275ebbc4.png">

**预期结果**
可以使用:class加字符串模板动态生成class名称

**实际结果**
没有效果,如使用以下这种方式则直接报错
<img width="570" alt="WeChat4b6b6b4ac5204f6b32a4f3a37965b333" src="https://user-images.githubusercontent.com/30310735/95956792-61af5900-0e31-11eb-8bae-6ec2509a8261.png">
![WechatIMG131](https://user-images.githubusercontent.com/30310735/95956862-7d1a6400-0e31-11eb-892e-1d008737636a.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: 小程序模拟器
 - uni-app版本: "^2.0.0-28920200907001"
 - 设备信息：所有设备

**补充信息**
希望兼容

**Comment by chenli1989** [comment]
修改如下：
```html
<div :class="{
 [`sleep-legend-${item.status}`]: true,
}"></div>
```
