### ISSUE TITLE
v-model,同步没有显示声明的属性无效（小程序）

### ISSUE THREAD

**Issue by arm-liang** [dcloudio/uni-app#2184]
**问题描述**
发现在`小程序`使用uni-app表单组件`u-input`的`v-mode`l双向更新的时候，如果同步的属性`没有显示声明响应式`，那么双向更新就会失效
然而在**网页端**这个特性是**存在**的
> 直接把后端数据赋值给`formData`，然后后端返回的数据小于前端表单中定义的数据，这个时候这种双向更新的特性就会丢失

**复现步骤**
[复现问题的步骤]
1.  在输入框输入内容
3. 查看 输入框下面的name

[或者可以直接贴源代码]
````vue
<template>
  <view>
    <view>
      <u-input v-model="formData.name" />
      <view>name: {{ formData.name }}</view>
    </view>
  </view>
</template>

<script>
export default {
  components: {},
  data() {
    return {
      formData: {}
    }
  },
  methods: {}
}
</script>

<style lang="scss">
</style>

````
**预期结果**
小程序和网页端都可以同步`formData.name`

**实际结果**
小程序直接undefined
![)}WB7V~4FO79E1P E}0_V9U](https://user-images.githubusercontent.com/37470680/95969137-eeadde80-0e40-11eb-8c7b-567c22c53c47.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by chenli1989** [comment]
```js
data() {
    return {
      formData: {
        name: '', // 添加下这个试看看
     }
    }
  },
```

**Comment by arm-liang** [comment]
@chenli1989  老哥你可能没看懂这个情况，网页端和小程序表现不一致，我知道显示声明响应属性就可以进行双向更新。
我这边反馈的是两个平台的不一致性，在后台返回的数据量小于表单中`v-model`更新的数据的时候就会出现无法同步的问题

**Comment by zhetengbiji** [comment]
测试新版已无此问题
