### ISSUE TITLE
视频组件的缓冲事件在支付宝小程序中无法监听

### ISSUE THREAD

**Issue by blueprint1453** [dcloudio/uni-app#2185]
根据视频组件的文档，视频组件中我们写了如下两个监听事件 监听视频缓冲和进度变化
@waiting="onWaiting"
@timeupdate="onTimeupdate"

在支付宝开发者工具中，使用真机预览，发现无法触发上述两个事件
去编译后的dist目录中的代码
<video controls="{{true}}" enable-play-gesture="{{true}}" show-center-play-btn="{{true}}" loop="{{true}}" src="{{item.videoInfo.highVertical}}" object-fit="fill" id="{{item.videoInfo.domId}}" poster="{{item.videoInfo.smallVertical}}" data-event-opts="{{[['error',[['videoErrorCallback',['$event']]]],['play',[['onCurrenVideoPlay',['$event']]]],['pause',[['onCurrenVideoPause',['$event']]]],['waiting',[['onWaiting',['$event']]]],['timeupdate',[['onTimeupdate',['$event']]]]]}}" onError="__e" onPlay="__e" onPause="__e" onWaiting="__e" onTimeupdate="__e"></video></block>

在支付宝平台中，@waiting对应的是onLoading，我们发现@waiting编译后并没有转化为loading或者onLoading事件名

于是我在视频组件中加入了
@loading="onWaiting"这一行，发现就可以了

现在的问题是，为什么框架没有把@waiting="onWaiting"事件编译成支付宝的loading/onLoading事件,waiting事件在支付宝中应该不回起效

**Comment by AcherTT** [comment]
所以，timeupdate还是没找到办法，我看axml文件里onTimeUpdate绑定的是“__e”，就是空的，可是文档没写支付宝不支持timeupdate。哎，啥玩意儿

**Comment by zhetengbiji** [comment]
HBuilderX 3.1.0 alpha 已修复
