### ISSUE TITLE
通过vue-cli命令行创建,开发环境编译到小程序，运行报错 Cannot read property 'extend' of undefined

### ISSUE THREAD

**Issue by wcldyx** [dcloudio/uni-app#2186]
**问题描述**
通过vue-cli 命令行:"vue create -p dcloudio/uni-preset-vue my-project"创建项目, 开发环境编译到小程序，运行报错 Cannot read property 'extend' of undefined，经过检查发现
是 import Vue from 'vue'; 导入的 Vue 为 undefined 导致的,但在h5是正常的

**补充信息**
 import Vue from 'vue'; 导入的 Vue 为 undefined 导致的

**Comment by wcldyx** [comment]
删除 vue.config.js 文件中的 process.env.UNI_USING_VUE3 = true 就正常了

**Comment by fxy060608** [comment]
你可能之前创建过vue3的uni-app工程(uni-preset-vue#vue3)，导致preset缓存了模板，正式版中是不包含vue.config.js的
解决方案
1. 添加 -c : `vue create -p dcloudio/uni-preset-vue my-project -c`
2.手动移除之前的模板cache，路径：`require('os').tmpdir()+'/vue-cli-presets/uni-preset-vue'`
