### ISSUE TITLE
[建议]支持自定义条件编译

### ISSUE THREAD

**Issue by victoryboss** [dcloudio/uni-app#219]
**新功能描述**
支持自定义条件编译，
我一个代码库里，可能需要根据包括多个项目，但是各个项目代码可能不同，
所以需要自定义条件编译。比如选择
#ifdef professtional
.bg{background:#fff}
#endif
#ifdef base
.bg{background:#fff}
#endif

**现状及问题**
条件编译只支持固定的PLATFORM

**尝试方案**
①文件层面，自己写node来选择性的移动文件，然后生成uniapp目录
②代码层面，技术难度有点大。目前想法是遍历所有文件，用fs.readFile()读文件，再用replace()匹配并替换变量值，然后fs.writeFile()回去

**Comment by victoryboss** [comment]
看了相关问题，有类似问题，比如 https://github.com/dcloudio/uni-app/issues/217

**Comment by wanganxp** [comment]
建议接受。会排期

**Comment by victoryboss** [comment]
谢谢您的接受这个建议，祝您工作顺利，祝uniapp越来越好！

**Comment by victoryboss** [comment]
蹩脚的方案，
1、通过 .env 文件，
2、加上 process.NODE_ENV.VUE_APP_ENV 来判断，
3、写特定平台js代码，
不过html和css可能会有多余

**Comment by liuyingqq123** [comment]
> 建议接受。会排期

能帮忙看下https://github.com/dcloudio/uni-app/issues/1008这个问题吗?
自定义的平台,
// #ifdef 无法用or的条件
