### ISSUE TITLE
.stop修饰符在各端到底调用了什么

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#2191]
我现在想js程序内stop，而不是通过v-if来控制修饰符。

我在想，对于各端的处理，.stop修饰符背后到底调用了什么？

是不是就是 event.stopPropagation 方法？

**Comment by zhetengbiji** [comment]
对，但是非H5平台的stopPropagation是由平台框架实现的，平台未直接暴露stopPropagation方法。

**Comment by wakaryry** [comment]
好的。我先试试了。谢谢。

**Comment by zzxqd** [comment]
我有个不那么完美的解决方案。
通过修饰符去绑定事件
给绑定事件的元素样式设```pointer-events: none;```
需要stopPropagation时就```pointer-events: auto;```
这样能近似实现对于一个区域的根据条件判断去阻止冒泡
