### ISSUE TITLE
video组件事件，在android，ios触发行为不一致

### ISSUE THREAD

**Issue by bigBron** [dcloudio/uni-app#2192]
plus.navigator.setFullscreen(true) 开启全屏模式
autoplay为false，手动调用play方法，android下调用play方法，视频播放成功触发play事件，ios下调用play方法，直接触发play事件
在设计组件时候都不考虑在android，ios端下都做成一样表现行为吗

**Comment by zhetengbiji** [comment]
收到，感谢反馈

**Comment by bigBron** [comment]
补充一下，播放链接的是rtmp协议

**Comment by bigBron** [comment]
请问有任何消息反馈吗？@zhetengbiji @ArrayDC

**Comment by zhetengbiji** [comment]
> 请问有任何消息反馈吗？@zhetengbiji @ArrayDC

优先级较低，暂不调整
