### ISSUE TITLE
请问uniapp-h5打包后，对百度SEO的收录问题

### ISSUE THREAD

**Issue by 18696232390** [dcloudio/uni-app#2194]
**问题描述**
最近有个项目，需要让百度收录，但是uniapp我个人感觉像vue，原本打算使用vue进行开发，但是发现vue并不支持seo(个人觉得ssr和nuxt.js太麻烦太坑爹了)，想使用uniapp进行开发，百度了下但没有明确的表示 uniapp不支持seo及收录问题，我想咨询一下uniapp打包后的h5，能否被百度收录？

**复现步骤**
无

**预期结果**
无

**实际结果**
无

**系统信息:**
无

**补充信息**
无

**Comment by zhetengbiji** [comment]
和普通的vue项目一样
单页的内容没有ssr的话不能被不支持SPA的搜索引擎收录，如果只是通用内容的收录可以写在模板html里。

**Comment by 18696232390** [comment]
现在要做一个新闻类的平台，使用uniapp(h5)，请问您说的“通用内容的收录可以写在模板html里。“ 大概是要怎么实现呀

**Comment by zhetengbiji** [comment]
> 现在要做一个新闻类的平台，使用uniapp(h5)，请问您说的“通用内容的收录可以写在模板html里。“ 大概是要怎么实现呀

https://uniapp.dcloud.io/collocation/manifest?id=h5-template

**Comment by 18696232390** [comment]
有什么办法对现有的uniapp项目做ssr改造呀？

**Comment by zhetengbiji** [comment]
> 有什么办法对现有的uniapp项目做ssr改造呀？

和普通vue项目一样，如果遇到框架在造成的阻碍，可以反馈

**Comment by 18696232390** [comment]
请问 Thymeleaf  这个技术支持seo收录吗

**Comment by zhetengbiji** [comment]
> 请问 Thymeleaf 这个技术支持seo收录吗

不了解

**Comment by zhenizhui** [comment]
@18696232390 Thymeleaf是java的后端模板引擎吧，只要服务端能出页面，我认为是支持SEO的

**Comment by chenzefeng09** [comment]
> > 有什么办法对现有的uniapp项目做ssr改造呀？
> 
> 和普通vue项目一样，如果遇到框架在造成的阻碍，可以反馈

uniapp框架代码初始化的过程中有大量的window/document操作，在server上都跑不过去
