### ISSUE TITLE
使用作用域插槽后套两层无法在微信小程序上渲染问题

### ISSUE THREAD

**Issue by zoushenglin** [dcloudio/uni-app#2195]
在hbuilder预览可以展示，在chrome浏览器输入地址也可以访问，但是在微信小程序开发工具上就是空白的，
代码如下
这是父页面代码
`<hgbox-request-goods-list
			ref="requestList" @listItemClick="goDetail"
			:request-data="requestData" height="calc(100vh - 176rpx)">
				<template #img="{shop}">
					<view class="img">
						<hgbox-lazy-preview-img :img-src="shop.picture"></hgbox-lazy-preview-img>
						<view class="binded" v-if="shop.binded === 0">
							未绑定设备
						</view>
					</view>
				</template>
				<template #title="{shop}">
					{{shop.deviceCode}}
				</template>
				<template #subTitle="{shop}">
					货道结构：{{shop.goodsWay}}
				</template>
				<template #description="{shop}">设备ID：{{shop.deviceId}}</template>
				<template #bottomDesc="{shop}">
					<view class="bottom">
						发货时间：{{shop.deliverTime}}
					</view>
				</template>
			</hgbox-request-goods-list>

这是子页面代码
<hgbox-request-list :request-data="requestData" :height="height"
	@listItemClick="listItemClick"
	:auto-request="autoRequest" :width="width">
		<template v-slot:item="{shop}">
			<hgbox-list @listItemClick="listItemClick(shop)">
				<template #img>
					<slot name="img" :shop="shop">
					</slot>
				</template>
				<template #title>
					<slot name="title" :shop="shop">
					</slot>
				</template>
				<template #subTitle>
					<slot name="subTitle" :shop="shop">
					</slot>
				</template>
				<template #description>
					<slot name="description" :shop="shop">
					</slot>
				</template>
				<template #bottomDesc>
					<slot name="bottomDesc" :shop="shop">
					</slot>
				</template>
				<template #rightFuc>
					<slot name="rightFuc" :shop="shop">
					</slot>
				</template>

			</hgbox-list>
		</template>
	</hgbox-request-list>`

chrome浏览器展示截图

微信小程序开发者工具展示截图

**Comment by huadong** [comment]
微信小程序不支持slot-scope/scope。

**Comment by zhetengbiji** [comment]
针对作用域插槽仅能使用解构插槽类型以及不能使用复杂表达式和作用域外数据的问题，进行了改进，有需求的开发者可以使用  3.1.10 alpha 体验，配置方式：在 manifest.json - mp-weixin 增加新的选项 betterScopedSlots，此配置仅在 alpha 版开放，后续可能会取消或更改此选项。

**Comment by zhetengbiji** [comment]
HBuilderX alpha 3.1.19+ 已修复

**Comment by zoushenglin** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
