### ISSUE TITLE
微信小程序分包优化：TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by huadong** [dcloudio/uni-app#2196]
代码描述：
- 工程A：小程序工程
   分包Ap：A工程下的一个分包

- 工程B：为组件工程
   组件Bc：为B工程下的一个组件
   工具模块c.js：为B工程下的工具模块，组件Bc引用工具模块c.js

使用：
1. A工程通过easycom方式引用B工程组件
2. Ap分包使用了组件Bc，并且引用了工具模块c.js

问题描述：
- 不开启分包优化，编译正常，运行正常。
- 开启分包优化，编译正常，**运行报错**。

分析：
分包优化后的c.js模块被编译到**分包**Ap/common/vender.js下，在**总包**的common/vender.js下无此模块。
但发现小程序启动时候，bootstrap会调用checkDeferredModules，这时候当check到组件Bc时，会尝试加载c.js模块，但此模块在分包下。加载失败。

错误代码类似：
```
 TypeError: Cannot read property 'call' of undefined
    at __webpack_require__ (bootstrap:91)
    at Object._ (month.vue?6422:1)
    at __webpack_require__ (bootstrap:91)
    at Object._ (month.vue?6422:1)
    at __webpack_require__ (bootstrap:91)
    at Module._ (month.vue?0ebd:1)
    at __webpack_require__ (bootstrap:91)
    at Object.nodeModulesZhuyinIoxUiLibWidgetIoxCalendarComponentsMonthCreateComponent (month.vue?eba8:7)
    at __webpack_require__ (bootstrap:91)
    at checkDeferredModules (bootstrap:47)
```

**Comment by huadong** [comment]
进一步测试发现问题出现在这里，不知道为什么把所有的组件（包括组件库、子包）都加载了一遍。：
```js
try {
      require("app.js")
    } catch (error) {
      !error.from && console.error('app.js错误:\n',error)
      throw error
    };var decodePathName = decodeURI("wxcomponents/demo-block/index")
__wxAppCode__[decodePathName + ".json"]={"component":true,"usingComponents":{"demo-block":"/wxcomponents/demo-block/index","parser":"/wxcomponents/Parser/index","myaudio":"/wxcomponents/audioplayer/audio","xinghui-ads":"plugin://wx3617beacb2740366/ads"}}
__wxAppCode__[decodePathName + ".wxml"]=$gwx("./" + decodePathName + ".wxml")
```

```js
      var decodePathName = decodeURI("node-modules/@zhuyin/iox-ui/lib/widget/iox-calendar/components/month")
      __wxRoute = decodePathName
      __wxRouteBegin = true
      __wxAppCurrentFile__ = decodePathName + ".js"
      try {
        require(__wxAppCurrentFile__)
      } catch (error) {
        // 插件项目不能hack define和require，走这里，异常只能精准到页面，内部的多层依赖的报错无法精准
        !error.from && console.error('页面【' + decodePathName + ']错误:\n',error)
        throw error
      }
```

**Comment by huadong** [comment]
@fxy060608 请关注一下，目前这个问题阻止了开启分包优化，我看社区和前边有相关的issue提到类似问题，项目大了很要命。

通过分析基本可以判断这个bug技术现象：
1、（比如利用easycom）引入第三方组件，尤其时UNIAPP的组件
2、第三方组件和分包引用了公共的第三方js模块
3、分包优化会把第三方js模块优化编译到分包的vender.js中
4、小程序启动时候，会扫描加载所有引用到的第三方组件（包括只在分包使用的到第三方组件：`问题就出在这了`）
5、第4步会导致加载分包下的js模块，但这时候分包尚未被小程序加载，于是报错凉凉了。

`可能`的解决办法：
在easycom编译中，上述的第4步，不要让小程序启动时候去加载只在分包使用的第三方组件。

**Comment by huadong** [comment]
> 4、小程序启动时候，会扫描加载所有引用到的第三方组件（包括只在分包使用的到第三方组件：`问题就出在这了`）

这一步是不是微信小程序自身行为，不是由UNIAPP框架产生的？

**Comment by huadong** [comment]
提交了一个重现工程：https://github.com/huadong/weapp-subpackages-optimization。

在
`src/packages/helloworld/pages/index.vue`
使用
`import { hello } from '@/utils/tools';`
去触发UNIAPP的分包优化。

**Comment by fxy060608** [comment]
建议发一个可重现该问题的测试工程

**Comment by fxy060608** [comment]
建议将x-test调整到分包目录
原因：
1. 为了保证目录，资源引用一致性，组件自身不会做分包处理
2. 目前会自动分包的，仅限 js，ts 文件（即tools.ts），编译器发现tools.ts仅被helloworld分包引用，会把tools.ts打包到该分包的vendor.js中
3. 小程序加载时，会自动注册当前包内的所有自定义组件，此时x-test引入了tools.ts，但主包内又没有，导致报错

**Comment by huadong** [comment]
> > 4、小程序启动时候，会扫描加载所有引用到的第三方组件（包括只在分包使用的到第三方组件：`问题就出在这了`）
> 
> 这一步是不是微信小程序自身行为，不是由UNIAPP框架产生的？

提交了微信原生自定义组件、小程序验证上述加载行为。从加载行为看，确认这是微信小程序的加载行为。
代码在工程：https://github.com/huadong/weapp-subpackages-optimization，目录/weapp下。

**Comment by huadong** [comment]
> 建议将x-test调整到分包目录

工程大了是没有办法做这样的调整的，因为：
1. 组件x-test是个公用组件，它会被多个分包引用；当每一个具体小程序，可能包含其中1个或者多个分包。如果恰好只包含了1个分包，优化后就报错了。

2. 使用第三方组件（或者组件工程）更为明显，第三方组件有可能引用了其他第三方js模块，而分包正好也引用了这个第三方js模块，这时候也会触发分包优化。

综上所述，在分包优化事后，需要考虑使用分包以外的自定义组件情况；当js模块被分包外的自定义组件引用时，不要进行优化拆离。

**Comment by fxy060608** [comment]
> > 建议将x-test调整到分包目录
> 
> 工程大了是没有办法做这样的调整的，因为：
> 
> 1. 组件x-test是个公用组件，它会被多个分包引用；当每一个具体小程序，可能包含其中1个或者多个分包。如果恰好只包含了1个分包，优化后就报错了。
> 2. 使用第三方组件（或者组件工程）更为明显，第三方组件有可能引用了其他第三方js模块，而分包正好也引用了这个第三方js模块，这时候也会触发分包优化。
> 
> 综上所述，在分包优化时候，需要考虑使用分包以外的自定义组件情况；当js模块被分包外的自定义组件引用时，不要进行优化拆离。

临时解决方案，可以自己在主包里import一下该ts文件

**Comment by huadong** [comment]
> > > 建议将x-test调整到分包目录
> > 
> > 
> > 工程大了是没有办法做这样的调整的，因为：
> > 
> > 1. 组件x-test是个公用组件，它会被多个分包引用；当每一个具体小程序，可能包含其中1个或者多个分包。如果恰好只包含了1个分包，优化后就报错了。
> > 2. 使用第三方组件（或者组件工程）更为明显，第三方组件有可能引用了其他第三方js模块，而分包正好也引用了这个第三方js模块，这时候也会触发分包优化。
> > 
> > 综上所述，在分包优化时候，需要考虑使用分包以外的自定义组件情况；当js模块被分包外的自定义组件引用时，不要进行优化拆离。
> 
> 临时解决方案，可以自己在主包里import一下该ts文件

只能这样了，我的工程里面，在后端API npm独立package工程里，有100+的JS模块，为了控制打包尺寸，采用了tree-shaking的编译。。。

期待能早日优化这个分包算法。

**Comment by huadong** [comment]
@fxy060608 uni-app太庞大了，实在难以通读所有代码，加上webpack的chunk树的module优化机制，当下仅对split-chunks打补丁，并不一定是最优解决方案，希望能审查并接纳这个PR。谢谢！

**Comment by fxy060608** [comment]
微信小程序2.11.1起支持了lazyCodeLoading配置，可以验证下启用该配置后是否可以解决此问题

**Comment by huadong** [comment]
问题依旧。

app.json 增加选项：
> "lazyCodeLoading": "requiredComponents",
![image](https://user-images.githubusercontent.com/2927763/98511762-325d0200-22a0-11eb-8a7b-8bb5d513ca01.png)

上图第4项：
![image](https://user-images.githubusercontent.com/2927763/98511867-5f111980-22a0-11eb-85b0-e1dbe79e0919.png)

**Comment by huadong** [comment]
微信开发者工具已经升级到了最新版：1.03.2010240。
![image](https://user-images.githubusercontent.com/2927763/98512225-f1b1b880-22a0-11eb-92b9-db038aca6159.png)

**Comment by yiqianglin** [comment]
2.0.0-31420210305001还是有这个问题，请问楼主有什么解决方案吗

**Comment by yiqianglin** [comment]
> 微信开发者工具已经升级到了最新版：1.03.2010240。

2.0.0-31420210305001还是有这个问题，请问楼主有什么解决方案吗

**Comment by yiqianglin** [comment]
> @fxy060608 uni-app太庞大了，实在难以通读所有代码，加上webpack的chunk树的module优化机制，当下仅对split-chunks打补丁，并不一定是最优解决方案，希望能审查并接纳这个PR。谢谢！

我们项目也非常庞大，目前也卡这个问题，import并不是非常好的解决方案；同时，会让tree-shaking无效，望楼主解答；

**Comment by huadong** [comment]
> > @fxy060608 uni-app太庞大了，实在难以通读所有代码，加上webpack的chunk树的module优化机制，当下仅对split-chunks打补丁，并不一定是最优解决方案，希望能审查并接纳这个PR。谢谢！
> 
> 我们项目也非常庞大，目前也卡这个问题，import并不是非常好的解决方案；同时，会让tree-shaking无效，望楼主解答；

自从UNIAPP合并了我提交的两个PR，前没有碰到类似问题了。
上边提到的这个工程是检验这个问题的，你可以试试：https://github.com/huadong/weapp-subpackages-optimization。
这个问题的产生是需要满足一下条件的：
1、import了第三方npm包
2、使用了分包
3、使用了分包优化
4、import的第三方包支持tree shaking
5、进行了production编译

就是构建发行版时候会出现。你可以确认一下是否是同样的问题，最好提交一个重现的小工程。

**Comment by JUST-Limbo** [comment]
需要注意的是，你这个示例工程run build会报错，似乎和安装的依赖包types文件夹下的声明有关。
用yarn安装依赖时提示"@zhuyin/mp-api-typings"这个依赖包镜像缺失，用npm安装跑build编译命令报错。

**Comment by huadong** [comment]
> 需要注意的是，你这个示例工程run build会报错，似乎和安装的依赖包types文件夹下的声明有关。
> 用yarn安装依赖时提示"@zhuyin/mp-api-typings"这个依赖包镜像缺失，用npm安装跑build编译命令报错。

@zhuyin/mp-api-typings这个包的3.3.2版本是已经发布到npm上了的：https://www.npmjs.com/package/@zhuyin/mp-api-typings

其实不用它也可以的。

**Comment by JUST-Limbo** [comment]
> > 需要注意的是，你这个示例工程run build会报错，似乎和安装的依赖包types文件夹下的声明有关。  用yarn安装依赖时提示"@zhuyin/mp-api-typings"这个依赖包镜像缺失，用npm安装跑build编译命令报错。
> 
> @zhuyin/mp-api-typings这个包的3.3.2版本是已经发布到npm上了的：https://www.npmjs.com/package/@zhuyin/mp-api-typings
> 
> 其实不用它也可以的。

我将@zhuyin/mp-api-typings依赖删除后，分别执行npm run build和npm run dev:mp-weixin。
将编译后得到的工程文件在微信开发者工具中打开，未出现前文提到的报错，似乎示例工程已经不会出现那个问题了。
