### ISSUE TITLE
$parent 、$children  bug

### ISSUE THREAD

**Issue by Nick091608** [dcloudio/uni-app#2199]
**问题描述**
自定义组件时，在自定义组件里使用$parent执行父组件方法，微信小程序可以正常执行，但是h5端报方法is not a function

子组件
methods: {
        jidan() {
	  this.$parent.progressHandler(123123)
	}
}
父组件
methods: {
  progressHandler(val) {
	console.log(val)
 },
}
**预期结果**
正常打印123123

**实际结果**
this.$parent.progressHandler is not a function

**系统信息:**
 - 发行平台:  谷歌浏览器
 - HBuilderX版本 [如使用HBuilderX，版本号：2.8.13]
 - uni-app版本 [HBuilderX创建项目]

**Comment by zhetengbiji** [comment]
#1651
