### ISSUE TITLE
v-for的key问题

### ISSUE THREAD

**Issue by zhegefeel** [dcloudio/uni-app#220]
**问题描述**
使用template加v-for，添加key,编译到微信小程序，key的位置不对

**系统信息:**
 - 发行平台: [微信小程序]

**Comment by aiplat** [comment]
没发现问题。我用的是v-for="(item,index) in arr" :key="index"

> 
> 
> **问题描述**
> 使用template加v-for，添加key,编译到微信小程序，key的位置不对
> 
> **系统信息:**
> 
>     * 发行平台: [微信小程序]

----------------------------------------------------------------------------------
没发现问题。我用的是v-for="(item,index) in arr" :key="index"

**Comment by zhegefeel** [comment]
vue里面是这么写
<template v-for="(groupItem, groupIndex) in groupList">
         <view class="group" :key="groupIndex"> 
           
        </view>
 </template>

小程序里面要把 :key 加到 <block></block>上面，按照vue的写法，编译到小程序里面， key没有添加上

**Comment by aiplat** [comment]
:key="
groupIndex" 是不会显示在
<view>里的，加个属性名就可以了，:data-k="
groupIndex"

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启

**Comment by mashirozx** [comment]
app似乎不能这样写
![image](https://user-images.githubusercontent.com/16148054/110103873-6b862880-7de1-11eb-97eb-0098b81c16a9.png)
