### ISSUE TITLE
video 无法使用UserMedia API,导致我无法调用摄像头进行拍照

### ISSUE THREAD

**Issue by toKnowMore** [dcloudio/uni-app#2201]
**问题描述**
video 无法使用UserMedia API,导致我无法调用摄像头进行拍照

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
```
if(navigator.getUserMedia) { // Standard, opera
				navigator.getUserMedia(mediaConf, function(stream) {
					video.src = stream;
					video.play();
				}, mediaErr);	
			} else if(navigator.webkitGetUserMedia) { // WebKit-prefixed, chrome
					navigator.webkitGetUserMedia(mediaConf, function(stream){
					video.src = window.webkitURL.createObjectURL(stream);
					video.play();
				}, mediaErr);
			}else if(navigator.mozGetUserMedia){ // firefox
				navigator.mozGetUserMedia(mediaConf,function(stream){					
					video.mozSrcObject = stream;
					video.play();			
			},mediaErr);
				
			}else{
				console.log('your browser do not support UserMedia API');
			}
```

**预期结果**
和浏览器表现一致,可以直接调用摄像头

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: h5

**补充信息**
[可选]
你们对video进行了二次封装,但这个API没有支持

**Comment by zhetengbiji** [comment]
是把h5运行在h5+的webview里面吗？如果不是补充一下浏览器信息

**Comment by toKnowMore** [comment]
就是h5里
`try {
					this.videoContext.srcObject = stream
					this.videoContext.play()
				} catch (err) {
					const CompatibleURL = window.URL || window.webkitURL
					this.videoContext.src = CompatibleURL.createObjectURL(stream)
					this.videoContext.play()
				}`
h5平台需要实现打开摄像头,实时拍照功能,现在没有报错,但是这个流无法播放,video还是一片漆黑

**Comment by toKnowMore** [comment]
这是完整代码
`startVideo() {
	let constraints = {
		audio: false,
					video: {
						width: 1024,
						height: 720,
						facingMode: 'user'
					}
				};
				if (navigator.mediaDevices.getUserMedia || navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia) {
					//调用用户媒体设备, 访问摄像头
					this.getUserMedia(constraints, this.success, this.error);
				} else {
					toast('不支持访问用户媒体');
				}
			}, //访问用户媒体设备的兼容方法
			getUserMedia(constraints, success, error) {
				if (navigator.mediaDevices.getUserMedia) {
					//最新的标准API
					navigator.mediaDevices
						.getUserMedia(constraints)
						.then(success)
						.catch(error);
				} else if (navigator.webkitGetUserMedia) {
					//webkit核心浏览器
					navigator.webkitGetUserMedia(constraints, success, error);
				} else if (navigator.mozGetUserMedia) {
					//firfox浏览器
					navigator.mozGetUserMedia(constraints, success, error);
				} else if (navigator.getUserMedia) {
					//旧版API
					navigator.getUserMedia(constraints, success, error);
				}
			},
			success(stream) {
				try {
					this.videoContext.srcObject = stream
					this.videoContext.play()
				} catch (err) {
					const CompatibleURL = window.URL || window.webkitURL
					this.videoContext.src = CompatibleURL.createObjectURL(stream)
					this.videoContext.play()
				}

			},
			error(error) {
				console.log(error.name, 'error')
			},`

**Comment by toKnowMore** [comment]
浏览器chrome 86.0.4240.75（正式版本） （64 位）

**Comment by zhetengbiji** [comment]
是把h5运行在h5+的webview里面吗？如果不是补充一下浏览器信息

**Comment by zhetengbiji** [comment]
封装的video接口只支持传入普通的路径作为src。

在h5端你可以直接动态创建原生的video标签：document.createElement('video')

**Comment by toKnowMore** [comment]
我怎么插入节点呢?

**Comment by zhetengbiji** [comment]
> 我怎么插入节点呢?

https://developer.mozilla.org/zh-CN/docs/Web/API/Node/appendChild

**Comment by toKnowMore** [comment]
明白了,只不过需要在onReady里操作,谢谢

**Comment by toKnowMore** [comment]
请问一下,这样为什么没法截图
`this.videoCanvas.drawImage(this.videoContext, 0, 0, 200, 320)
				this.videoCanvas.draw()
				uni.canvasToTempFilePath({
					canvasId: 'myCanvas',
					success: (res) => {
						console.log(res)
						let path = res.tempFilePath
						this.url = path
						// this.$http.upload(path, null, null, response => {
						// 	this.url  =  response.data
						// });
					}
				});`

图片一片黑

**Comment by zhetengbiji** [comment]
> 请问一下,这样为什么没法截图
> `this.videoCanvas.drawImage(this.videoContext, 0, 0, 200, 320) this.videoCanvas.draw() uni.canvasToTempFilePath({ canvasId: 'myCanvas', success: (res) => { console.log(res) let path = res.tempFilePath this.url = path // this.$http.upload(path, null, null, response => { // this.url = response.data // }); } });`
> 
> 图片一片黑

绘制video？从文档看目前未支持。可以自己创建一个原生的canvas标签
