### ISSUE TITLE
@dcloudio/types@2.0.12

### ISSUE THREAD

**Issue by huadong** [dcloudio/uni-app#2203]
```
interface Animation {
  //...
}
```
缺了两个关键的函数定义：
- step()
- export()

同时缺少了export()的AnimationData定义。

参考使用文档：https://uniapp.dcloud.io/api/ui/animation?id=animation

另：@dcloudio/types 能提交PR吗？

**Comment by zhetengbiji** [comment]
已更新
@dcloudio/types 目前不能提交pr，是由工具自动生成的

**Comment by huadong** [comment]
感谢更新！
另外，在微信小程序里面，interface Animation{} 接口的height()和width()是可以传入string的，比如auto。

**Comment by huadong** [comment]
@zhetengbiji v2.0.12和v2.0.13怎么在npm撤回了？都依赖它们发布新版本代码了。

**Comment by zhetengbiji** [comment]
> @zhetengbiji v2.0.12和v2.0.13怎么在npm撤回了？都依赖它们发布新版本代码了。

没撤回，是不是你网络不好

**Comment by huadong** [comment]
是的，npm代理缓存了。

👍你github回复太快了，comment撤回都来不及。

**Comment by zhetengbiji** [comment]
> 感谢更新！
> 另外，在微信小程序里面，interface Animation{} 接口的height()和width()是可以传入string的，比如auto。

已更新
