### ISSUE TITLE
启动图BUG啊  求修复啊

### ISSUE THREAD

**Issue by livelyPeng** [dcloudio/uni-app#2205]
"splashscreen" : {
            "alwaysShowBeforeRender" : false,
            "waiting" : true,
            "autoclose" : false,
            "delay" : 2000
        },

这个根本没效果，根本不会等2秒

我alwaysShowBeforeRender这个开启吧 启动图要等待至少7秒 才去首页， 我alwaysShowBeforeRender这个关闭吧，很快去首页了，但是 会出现白屏一下 才去首页 

我以为是APP加载整包导致进入首页慢，如官方提到的：App默认为整包。从uni-app 2.7.12+ 开始，也兼容了小程序的分包配置。其目的不用于下载提速，而用于首页是vue时的启动提速。App下开启分包，除在pages.json中配置分包规则外，还需要在manifest中设置在app端开启分包设置，详见：https://uniapp.dcloud.io/collocation/manifest?id=app-vue-optimization

但是我配置这个："app-plus": {
  "optimization": {
    "subPackages": true
  },
  "runmode" : "liberate" // 开启分包优化后，必须配置资源释放模式
}

然后启动应用有报错：配置了会报错： reportJSException >>>> exception function:createInstanceContext, exception:white screen cause create instanceContext failed,check js stack ->Uncaught TypeError: Cannot read property 'call' of undefined

求帮助下 怎么办啊

**Comment by ArrayDC** [comment]
autoclose设置为false后delay属性不会生效。
