### ISSUE TITLE
uniapp中mock结合axios使用在真机上出现错误

### ISSUE THREAD

**Issue by mabangwang** [dcloudio/uni-app#221]
**问题描述**
uni-app在使用mockjs+axios，在web端显示正常，在安卓机上报错：

Uncaught (in promise) TypeError: XMLHttpRequest is not a constructor at node_modules/_axios@0.18.0@axios/lib/adapters/xhr.js:20

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/45955163/53479616-64223b00-3ab4-11e9-8e3a-adb16785f96c.png)
![image](https://user-images.githubusercontent.com/45955163/53479650-71d7c080-3ab4-11e9-8d17-61f20e88cf97.png)

**系统信息:**
 - 发行平台: 5+ App等]
 - 操作系统 [Android 9.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [华为]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
axios并未支持小程序和app，可以试试flyio
