### ISSUE TITLE
uni.uploadFile 怎么能设置 PUT 请求方式。

### ISSUE THREAD

**Issue by Mlxa0324** [dcloudio/uni-app#2212]
OSS 后端授权请求上传的时候，必须使用 PUT方式上传，uploadFile 里面没办法修改请求的方式。

**Comment by zhetengbiji** [comment]
需求是在那端？

**Comment by snice** [comment]
就算能修改，也上传不了。aliyun oss putObject 文件上传是字节流传输，uni.request字节流传输你去研究下

**Comment by zhetengbiji** [comment]
> 就算能修改，也上传不了。aliyun oss putObject 文件上传是字节流传输（不是标准的文件上传），uni.request字节流传输你去研究下

小程序能上传到阿里云oss吗？

**Comment by Mlxa0324** [comment]
> 需求是在那端？

想着所有端都统一用oss授权访问的方式上传文件。安卓ios小程序。

**Comment by zhetengbiji** [comment]
> > 需求是在那端？
> 
> 想着所有端都统一用oss授权访问的方式上传文件。安卓ios小程序。

小程序现在没有方案吗？

**Comment by PetersonLian** [comment]
马德，服了，依然不能设置PUT请求。我也用的是阿里云oss。真是服了uni.uploadFile不能自己配置PUT。牛逼。这么一个问题一直没解决。用你妈比 uni app

**Comment by Otto-J** [comment]
https://developers.weixin.qq.com/miniprogram/dev/api/network/upload/wx.uploadFile.html
https://developers.weixin.qq.com/community/develop/doc/00026c5ca54e38c13a8899f4856000?highLine=uploadFile%2520put

**Comment by fxtxz2** [comment]
是非腾讯云约束了只能使用PUT上传吧
