### ISSUE TITLE
slider组件的value值设置会导致数据脱离绑定

### ISSUE THREAD

**Issue by simonblowsnow** [dcloudio/uni-app#2213]
**问题描述**
[问题描述：slider组件的value值仅能被动态设置一次，设置后导致数据脱离绑定，既无法再次通过设置数据导致UI改变，用户拖动滑块也无法同步到已绑定的数据，element-ui及其它框架不存在该问题]

**复现步骤**
[复现问题的步骤]
1.  在change事件里添加"更改数组值的代码"
2. 第一次拖动滑块，UI同步滑块至数据位置
3. 再次次拖动滑块，UI滑块不再响应数据设定
4. 查看绑定数据的值是否和UI一致

**补充信息**
[可选]
[经实验，和$set无关]

**Comment by zhetengbiji** [comment]
小程序还是H5？
