### ISSUE TITLE
加速度计、罗盘、陀螺仪多次开启-关闭，得到多次重复数据

### ISSUE THREAD

**Issue by mworkfun** [dcloudio/uni-app#2216]
加速度计、罗盘在安卓手机上多次开启-关闭，得到多次重复数据，应该是每次打开都会生成一个实例，不能正常关闭实例，导致多个实例同时在工作。

加速度计：
1、uni.startAccelerometer(OBJECT);  //开始监听数据
2、uni.onAccelerometerChange(function (res) {   //监听数据
     console.log(res.x);                    //重复1、2、3步骤会得到重复的x,yz轴数据
     console.log(res.y);                   //重复n次就会有n个重复的数据
     console.log(res.z);
    });
3、uni.stopAccelerometer(OBJECT);  //停止监听加速度数据
 
罗盘：
1、uni.startCompass(OBJECT);  //开始监听数据
2、uni.onCompassChange(function (res) {  //监听数据
     console.log(res.direction);    //重复1、2、3步骤会得到重复方向数据，重复n次就会有n个重复的数据
     });
3、uni.stopCompass(); //停止监听

预期结果：
重新开启设备时，应该是这次打开的实例在运行，上次打开实例不会存在。

实际结果：
重新开启设备时，这次打开的实例在运行，上次打开实例也会存在，导致会有多次重复的数据出现。

系统信息:
华为荣耀9，安卓系统
HBuiderX v2.9.3

补充信息：
应该是关闭设备时没有销毁实例，实例任然在运行。

**Comment by zhetengbiji** [comment]
iOS和微信小程序不是这样吗？
多次调用 onCompassChange 就是会有多次监听，后续会实现 offCompassChange 用于取消监听

**Comment by mworkfun** [comment]
好的，感谢！iOS和微信小程序没有试过，只在安卓机上测试。有点不明白开始监听和停止监听这两个API的作用，如：在onload函数里调用了开始监听和onCompassChange，然后在页面其他函数内调用停止监听可以实现停止，但是如果我要再从新监听，如果只调用开始监听是实现不了监听，还有调用一次 onCompassChange才行，可是这样又会导致有重复数据。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "折腾笔记"<notifications@github.com&gt;; 
发送时间: 2020年10月27日(星期二) 下午3:10
收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 
抄送: "??"<1123552240@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dcloudio/uni-app] 加速度计、罗盘、陀螺仪多次开启-关闭，得到多次重复数据 (#2216)





 
iOS和微信小程序不是这样吗？
 多次调用 onCompassChange 就是会有多次监听，后续会实现 offCompassChange 用于取消监听
