### ISSUE TITLE
H5打包不成功，报错js文件过大

### ISSUE THREAD

**Issue by EVANYXW** [dcloudio/uni-app#222]
H5打包不成功，报错js文件过大
![Uploading 1551279510518.jpg…]()

**Comment by EVANYXW** [comment]
⠙  开始编译当前项目至 h5 平台...

 WARNING  Compiled with 1 warnings                                                                                             下午10:44:25

 warning  

asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  static/js/pages-template-echarts-echarts.a9e759cd.js (294 KiB)

 DONE  Build complete. The dist/build/h5 directory is ready to be deployed.

**Comment by fxy060608** [comment]
只是一个警告信息，已经编译成功了，不影响部署
