### ISSUE TITLE
d.ts 中没有包含Promise处理

### ISSUE THREAD

**Issue by TuiMao233** [dcloudio/uni-app#2221]
https://uniapp.dcloud.io/api/README?id=promise-%e5%b0%81%e8%a3%85
![1603566190(1)](https://user-images.githubusercontent.com/49724027/97091468-a4153900-166e-11eb-959f-68d6c7209888.jpg)

**Comment by TuiMao233** [comment]
现在只能用这种曲线救国的方式覆盖上去了，官方什么时候加上去吧
![1603596395(1)](https://user-images.githubusercontent.com/49724027/97098226-67206500-16b5-11eb-896f-27015ea5b94c.jpg)
![image](https://user-images.githubusercontent.com/49724027/97098228-80c1ac80-16b5-11eb-8539-d3c163178fcc.png)
![image](https://user-images.githubusercontent.com/49724027/97098230-8e773200-16b5-11eb-972a-b7d89f287692.png)

**Comment by zhetengbiji** [comment]
因有调整计划，暂未统一处理

**Comment by StrivingRabbit** [comment]
[关于d.ts适配Promise返回](https://github.com/dcloudio/uni-app/issues/1770)

**Comment by StrivingRabbit** [comment]
关于api 的 Promise 化类型提示。除 `uni.request 有返回值`、`同步的方法（即以 sync 结束）`、`以 create 开头的方法`、`以 manager 结束的方法`、`返回 task 的 api ` 暂不处理外，其他可以升级 @dcloudio/types@3.3.0 试试看

**Comment by StrivingRabbit** [comment]
部分 api promise 化提示已支持，后续进度请跟踪 #3009 查看
