### ISSUE TITLE
map组件的controls不显示

### ISSUE THREAD

**Issue by RachelHui12** [dcloudio/uni-app#2223]
**问题描述**
使用uni-app的map组件时不显示控件

**复现步骤**
						<map 
						id="myMap"
						style="width: 100%; height:750px;" 
						:controls="controls"
						:latitude="latitude" 
						:longitude="longitude" 
						:markers="markers" 
						:enable-satellite="false"
						:show-location="true" @markertap=markertap>
						</map>
controls:[{//在地图上显示控件，控件不随着地图移动
				   　　id:1,//控件id
				   　　iconPath:'../../static/img/qq.png',//显示的图标    
				   　　position:{//控件在地图的位置
				      　　left:15,
				      　　top:15,
				      　　width:50,
				      　　height:50
				  　　  },    
				　　}],

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 [Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]

[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
换其他图标路径重新测试一下
