### ISSUE TITLE
uni-app支不支持微信小程序的第三方平台的开发？怎么配置第三方平台小程序所需的ext.json？

### ISSUE THREAD

**Issue by lhf2** [dcloudio/uni-app#223]
uni-app支不支持微信小程序的第三方平台的开发？怎么配置第三方平台小程序所需的ext.json？

**Comment by xiaoyucoding** [comment]
临时方案：
运行至微信小程序后，在生成的微信小程序项目目录下创建 ext.json 文件。

**Comment by xiaoyucoding** [comment]
HBuilderX 1.9.0 发布：

- 微信小程序 新增 支持在根目录下添加 `ext.json` 及 `sitemap.json`

**Comment by keyiis** [comment]
@xiaoyucoding 我使用vscode开发，在项目根目录下放置了ext.json，运行`npm run dev:mp-weixin`后，但是ext.json并没有拷贝到'dist/dev/mp-weixin'目录下。是不支持vscode吗？

**Comment by zhetengbiji** [comment]
> @xiaoyucoding 我使用vscode开发，在项目根目录下放置了ext.json，运行`npm run dev:mp-weixin`后，但是ext.json并没有拷贝到'dist/dev/mp-weixin'目录下。是不支持vscode吗？

src

**Comment by keyiis** [comment]
@zhetengbiji 移到src下就可以了，谢谢
