### ISSUE TITLE
希望支持原生Page开发，便于APP开发中特定场景开发

### ISSUE THREAD

**Issue by snice** [dcloudio/uni-app#2230]
**新功能描述**
希望支持原生Page开发，便于APP开发中特定场景开发

**补充信息**
某些场景下，采用vue\nvue可能无法完全满足开发需求。这个时候可能需要采用纯原生开发界面（单独activity\viewcontroller）,但是原生界面无法和uniapp的页面堆栈混合。

因此，希望提供NativePage接口，并通过原生插件的方式集成。

假定api接口如下：

* 跳转到Native Page
```js
uni.navigateTo({
    native:true,
    url: '/nativepage/test/test'
})
```

其中/nativepage/test/test通过插件配置

**Comment by snice** [comment]
有没有大佬，关注下啊

**Comment by XuZhiFan** [comment]
+1
