### ISSUE TITLE
低版本下apply不支持undefined的写法

### ISSUE THREAD

**Issue by Ulyssesyi** [dcloudio/uni-app#2233]
**问题描述**
在低版本的chrome浏览器（android 5 webview chrome37的内核），由于h5中can-i-use.js中的apply语法为CSS.supports.apply(undefined, css.split(':'))导致了Illegal Invocation的异常。希望能修改为CSS.supports.apply(CSS, css.split(':'))来兼容低版本的手机浏览器

**复现步骤**
使用chrome内核低于37的即可复现

**预期结果**
能支持低版本的浏览器

**实际结果**
无法支持低版本浏览器

**系统信息:**
 - 发行平台: H5平台
 - 操作系统: Android 5.0
 - uni-app版本: 2.9.3
 - 设备信息: android平板

**Comment by WaynePluto** [comment]
目前android 5 webview chrome37的内核的手机还不少，我们挺多用户发现了这个问题导致的白屏，uni-app 2.9.8还没有改，帮顶一下
