### ISSUE TITLE
通过hello uni-app模板创建的项目运行微信小程序自动化测试失败

### ISSUE THREAD

**Issue by smoothdvd** [dcloudio/uni-app#2235]
**问题描述**
通过hello uni-app模板创建的项目运行微信小程序自动化测试失败

**复现步骤**
[复现问题的步骤]
1. jest.config.js
```
module.exports = {
  globalTeardown: '@dcloudio/uni-automator/dist/teardown.js',
  testEnvironment: '@dcloudio/uni-automator/dist/environment.js',
  testEnvironmentOptions: {
    compile: true,
    h5: { // 为了节省测试时间，可以指定一个 H5 的 url 地址，若不指定，每次运行测试，会先 npm run dev:h5
      url: 'http://192.168.x.x:8080/h5/',
      options: {
        headless: false, // 配置是否显示 puppeteer 测试窗口
      },
    },
    'app-plus': { // 需要安装 HBuilderX
      android: {
        executablePath: 'HBuilderX/plugins/launcher/base/android_base.apk', // apk 目录
      },
      ios: {
        // uuid 必须配置，目前仅支持模拟器，可以（xcrun simctl list）查看要使用的模拟器 uuid
        id: '',
        executablePath: 'HBuilderX/plugins/launcher/base/Pandora_simulator.app', // ipa 目录
      },
    },
    'mp-weixin': {
      port: 9520, // 默认 9420
      account: 'wxd92a17dab0137021', // 测试账号
      args: '', // 指定开发者工具参数
      cwd: '', // 指定开发者工具工作目录
      launch: true, // 是否主动拉起开发者工具
      teardown: 'disconnect', // 可选值 "disconnect"|"close" 运行测试结束后，断开开发者工具或关闭开发者工具
      remote: false, // 是否真机自动化测试
      executablePath: '', // 开发者工具cli路径，默认会自动查找,  windows: C:/Program Files (x86)/Tencent/微信web开发者工具/cli.bat", mac: /Applications/wechatwebdevtools.app/Contents/MacOS/cli
    },
    'mp-baidu': {
      port: 9430, // 默认 9430
      args: '', // 指定开发者工具参数
      cwd: '', // 指定开发者工具工作目录
      launch: true, // 是否主动拉起开发者工具
      teardown: 'disconnect', // 可选值 "disconnect"|"close" 运行测试结束后，断开开发者工具或关闭开发者工具
      remote: false, // 是否真机自动化测试
      executablePath: '', // 开发者工具cli路径，默认会自动查找
    },
  },
  testTimeout: 15000,
  reporters: [
    'default',
  ],
  watchPathIgnorePatterns: ['/node_modules/', '/dist/', '/.git/'],
  moduleFileExtensions: ['js', 'json'],
  rootDir: __dirname,
  testMatch: ['<rootDir>/src/**/*test.[jt]s?(x)'], // 测试文件目录
  testPathIgnorePatterns: ['/node_modules/'],
};
```
2.  启动 'yarn test:mp-weixin'

**预期结果**
运行自动化测试

**实际结果**
```
$ cross-env UNI_PLATFORM=mp-weixin jest -i
 FAIL  src/pages/API/set-navigation-bar-title/set-navigation-bar-title.test.js (21.043s)
  ● pages/API/set-navigation-bar-title/set-navigation-bar-title.vue › set-navigation-bar-title 组件标题

    Timeout - Async callback was not invoked within the 15000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 15000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● pages/API/set-navigation-bar-title/set-navigation-bar-title.vue › set-navigation-bar-title 组件标题

    TypeError: Cannot read property '$' of undefined

      18 | 
      19 |     it('set-navigation-bar-title 组件标题', async () => {
    > 20 |     	let view = await page.$('.uni-page-head-title')
         |     	                      ^
      21 |     	expect(await view.text()).toBe('nav-default')
      22 |     })
      23 | })

      at Object.<anonymous> (src/pages/API/set-navigation-bar-title/set-navigation-bar-title.test.js:20:28)
```

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: macOS 10.11
 - uni-app版本:
```
uni-app v2.9.5
uni-app cli v2.0.0-alpha-29520201023001

Environment Info:

  System:
    OS: macOS 11.0.1
    CPU: (4) x64 Intel(R) Core(TM) i5-4690 CPU @ 3.50GHz
  Binaries:
    Node: 15.0.1 - /var/folders/lm/lp8b9ycj1ls07b5hnr4ykxmm0000gn/T/yarn--1603954547228-0.8614967634049582/node
    Yarn: 1.22.10 - /var/folders/lm/lp8b9ycj1ls07b5hnr4ykxmm0000gn/T/yarn--1603954547228-0.8614967634049582/yarn
    npm: 7.0.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 86.0.4240.111
    Firefox: Not Found
    Safari: 14.0.1
  npmPackages:
    @dcloudio/types: * => 2.0.17 
    @dcloudio/uni-app-plus: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-automator: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @dcloudio/uni-cli-shared: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @dcloudio/uni-h5: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @dcloudio/uni-helper-json: * => 1.0.7 
    @dcloudio/uni-migration: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @dcloudio/uni-mp-360: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @dcloudio/uni-mp-alipay: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @dcloudio/uni-mp-baidu: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @dcloudio/uni-mp-qq: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @dcloudio/uni-mp-toutiao: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @dcloudio/uni-mp-vue: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @dcloudio/uni-mp-weixin: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @dcloudio/uni-quickapp-native: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @dcloudio/uni-quickapp-webview: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @dcloudio/uni-stat: ^2.0.0-alpha-29520201023001 => 2.0.0-v3-24020191018001 
    @dcloudio/uni-template-compiler: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-alpha-29520201023001 => 2.0.0-alpha-29520201023001 
    @hap-toolkit/dsl-vue:  0.6.13 
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2 
    @vue/babel-plugin-jsx:  1.0.0-rc.3 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.8 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.8 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.8 
    @vue/cli-plugin-router:  4.5.8 
    @vue/cli-plugin-vuex:  4.5.8 
    @vue/cli-service: ~4.5.0 => 4.5.8 
    @vue/cli-shared-utils:  4.5.8 
    @vue/component-compiler-utils:  3.2.0 (3.2.0)
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/shared: ^3.0.0 => 3.0.2 
    @vue/web-component-wrapper:  1.2.0 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.11 => 2.6.12 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.4 (16.0.0-beta.9, 15.9.4)
    vue-router:  3.0.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.11 => 2.6.12 (2.6.12)
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.2.0 => 3.5.1 
  npmGlobalPackages:
    @vue/cli: Not Found
```

**Comment by VincentGum** [comment]
我这边按照官网文档操作也失败了，蹲一个解决方案。

**Comment by smoothdvd** [comment]
Any progress?

**Comment by zhetengbiji** [comment]
按照文档，检查依赖后，重试

**Comment by smoothdvd** [comment]
一样，微信小程序测试还是不行。
···
> cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch "--auto-port" "9520"
请注意运行模式下，因日志输出、sourcemap以及未压缩源码等原因，性能和包体积，均不及发行模式。若要正式发布，请点击发行菜单或使用cli发布命令进行发布
小程序各家浏览器内核及自定义组件实现机制存在差异，可能存在样式布局兼容问题，参考：https://uniapp.dcloud.io/matter?id=mp

-  开始编译当前项目至 mp-weixin 平台...
Starting type checking service...
Using 1 worker with 2048MB memory limit
DONE  Compiled successfully in 1519ms1:19:13 PM
No type errors found
Version: typescript 3.9.10
Time: 893ms
 DONE  Build complete. The dist/dev/mp-weixin directory is ready. Watching for changes...
 FAIL  tests/unit/example.spec.js (23.127s)
  HelloWorld.vue
    ✕ .uni-panel (2ms)

  ● HelloWorld.vue › .uni-panel

    Timeout - Async callback was not invoked within the 15000ms timeout specified by jest.setTimeout.Error: Timeout - Async callback was not invoked within the 15000ms timeout specified by jest.setTimeout.

      at mapper (node_modules/@jest/core/node_modules/jest-jasmine2/build/queueRunner.js:27:45)

  ● HelloWorld.vue › .uni-panel

    TypeError: Cannot read property '$' of undefined

      12 |
      13 |   it('.uni-panel', async () => {
    > 14 |     const content = await page.$('.content');
         |                                ^
      15 |     expect(content.length).toBe(9);
      16 |   });
      17 |

      at Object.<anonymous> (tests/unit/example.spec.js:14:32)

Test Suites: 1 failed, 1 total
Tests:       1 failed, 1 total
Snapshots:   0 total
Time:        23.218s
Ran all test suites.
/Users/alexgao/Dev/chengshi-news-miniapp/node_modules/@dcloudio/uni-automator/dist/index.js:1
"use strict";function t(t){return t&&"object"==typeof t&&"default"in t?t.default:t}var e=t(require("fs")),n=t(require("path")),s=t(require("debug")),i=t(require("licia/isRelative")),o=t(require("ws")),r=require("events"),a=t(require("licia/uuid")),c=t(require("licia/stringify")),p=t(require("licia/dateFormat")),l=t(require("licia/waitUntil")),u=t(require("licia/fs")),h=t(require("licia/isFn")),d=t(require("licia/trim")),m=t(require("licia/isStr")),g=t(require("licia/startWith")),y=t(require("licia/isNum")),v=t(require("licia/sleep")),w=t(require("licia/isUndef")),f=t(require("address")),P=t(require("default-gateway")),M=t(require("licia/getPort")),k=require("child_process"),E=t(require("licia/toStr"));class b extends r.EventEmitter{constructor(t){super(),this.ws=t,this.ws.addEventListener("message",t=>{this.emit("message",t.data)}),this.ws.addEventListener("close",()=>{this.emit("close")})}send(t){this.ws.send(t)}close(){this.ws.close()}}class I extends r.EventEmitter{constructor(t,e,n){super(),this.puppet=e,this.namespace=n,this.callbacks=new Map,this.transport=t,this.debug=s("automator:protocol:"+this.namespace),this.onMessage=t=>{this.debug(`${p("yyyy-mm-dd HH:MM:ss:l")} ◀ RECV ${t}`);const{id:e,method:n,error:s,result:i,params:o}=JSON.parse(t);if(!e)return this.puppet.emit(n,o);const{callbacks:r}=this;if(e&&r.has(e)){const t=r.get(e);r.delete(e),s?t.reject(Error(s.message)):t.resolve(i)}},this.onClose=()=>{this.callbacks.forEach(t=>{t.reject(Error("Connection closed"))})},this.transport.on("message",this.onMessage),this.transport.on("close",this.onClose)}send(t,e={},n=!0){if(n&&this.puppet.adapter.has(t))return this.puppet.adapter.send(this,t,e);const s=a(),i=c({id:s,method:t,params:e});return this.debug(`${p("yyyy-mm-dd HH:MM:ss:l")} SEND ► ${i}`),new Promise((t,e)=>{try{this.transport.send(i)}catch(t){e(Error("Connection closed"))}this.callbacks.set(s,{resolve:t,reject:e})})}dispose(){this.transport.close()}static createDevtoolConnection(t,e){return new Promise((n,s)=>{const i=new o(t);i.addEventListener("open",()=>{n(new I(new b(i),e,"devtool"))}),i.addEventListener("error",s)})}static createRuntimeConnection(t,e,n){return new Promise((i,r)=>{s("automator:runtime")(`${p("yyyy-mm-dd HH:MM:ss:l")} port=${t}`);const a=new o.Server({port:t});l(async()=>{if(e.runtimeConnection)return!0},n,1e3).catch(()=>{a.close(),r("Failed to connect to runtime, please make sure the project is running")}),a.on("connection",(function(t){s("automator:runtime")(p("yyyy-mm-dd HH:MM:ss:l")+" connected");const n=new I(new b(t),e,"runtime");e.setRuntimeConnection(n),i(n)})),e.setRuntimeServer(a)})}}const C=require("qrcode-terminal");require("qrcode-reader"),/^win/.test(process.platform);async function T(t,e){const[n,s]=function(t){return m(t)?[!0,[t]]:[!1,t]}(e),i=await t(s);return n?i[0]:i}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            

Error: Caught error after test environment was torn down

Connection closed
    at /Users/alexgao/Dev/chengshi-news-miniapp/node_modules/@dcloudio/uni-automator/dist/index.js:1:1471
    at Map.forEach (<anonymous>)
    at b.I.onClose (/Users/alexgao/Dev/chengshi-news-miniapp/node_modules/@dcloudio/uni-automator/dist/index.js:1:1450)
    at b.emit (node:events:394:28)
    at WebSocket.<anonymous> (/Users/alexgao/Dev/chengshi-news-miniapp/node_modules/@dcloudio/uni-automator/dist/index.js:1:888)
    at WebSocket.onClose (/Users/alexgao/Dev/chengshi-news-miniapp/node_modules/@dcloudio/uni-automator/node_modules/ws/lib/event-target.js:136:16)
    at WebSocket.emit (node:events:406:35)
    at WebSocket.emitClose (/Users/alexgao/Dev/chengshi-news-miniapp/node_modules/@dcloudio/uni-automator/node_modules/ws/lib/websocket.js:198:10)
    at Receiver.receiverOnFinish (/Users/alexgao/Dev/chengshi-news-miniapp/node_modules/@dcloudio/uni-automator/node_modules/ws/lib/websocket.js:863:20)
    at Receiver.emit (node:events:394:28)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
···
