### ISSUE TITLE
uni-app使用vant-weapp tree-select组件时，左侧导航栏onClickNav事件无法获取传递的index

### ISSUE THREAD

**Issue by Johnson-xm** [dcloudio/uni-app#2239]
**问题描述**
uni-app使用vant-weapp tree-select组件时，左侧导航栏onClickNav事件无法获取传递的index
**复现步骤**

**Vant Weapp Tree-select组件代码：**
onClickNav(event) {
      const index = event.detail;
      const item = this.data.items[index];
      if (!item.disabled) {
                **//此处参数为对象**
                this.$emit('click-nav', { index });
      }
    },

**使用uni-app开发页面**
<van-tree-select height="auto" :items="items" 
		:main-active-index ="activeIndex" 
		main-item-class="main-item"
		main-active-class = "main-active"
		@clickNav="onClickNav">
...
</van-tree-select>
onClickNav(event) {
	console.log('onClickNav',event);
},

**预期结果**
**Vant Weapp官方案例代码：**
 onClickNav({ detail = {} }) {
    this.setData({
      mainActiveIndex: detail.index || 0,
    });
  },

**实际结果**
onClickNav(event) {
	//**此处event输出结果为undefined**
	console.log('onClickNav',event);
},

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 2.9.3.20201014
 - 设备信息：微信开发者工具

**补充信息**
[根据你的分析，出现这个问题的原因可能在哪里？]

//**经测试，下面的代码已经正确获取到参数**
const params = processEventArgs(
            this.$vm,
            event,
            eventArray[1],
            eventArray[2],
            isCustom,
            methodName
          );

**下面代码中如果参数不是数组，将会自动变成空数组，导致参数未接受。** 
  // 参数尾部增加原始事件对象用于复杂表达式内获取额外数据
  // eslint-disable-next-line no-sparse-arrays
  ret.push(handler.apply(handlerCtx, (Array.isArray(params) ? params : []).concat([, , , , , , , , , , event]))); //该行代码导致未正确获取到参数

**Comment by Johnson-xm** [comment]
Vant Weapp Tree-select组件代码：
onClickNav(event) {
      const index = event.detail;
      const item = this.data.items[index];
      if (!item.disabled) {
                **//此处参数未对象**
                this.$emit('click-nav', { index });
      }
    },
   
uni-app代码：
**下面代码中如果参数不是数组，将会自动变成空数组，导致参数未接受。**
// 参数尾部增加原始事件对象用于复杂表达式内获取额外数据
// eslint-disable-next-line no-sparse-arrays
ret.push(handler.apply(handlerCtx, (Array.isArray(params) ? params : []).concat([, , , , , , , , , , event]))); //该行代码导致未正确获取到参数

**Comment by zhetengbiji** [comment]
fixed
