### ISSUE TITLE
uni.createInnerAudioContext()获取不到时长

### ISSUE THREAD

**Issue by chengpeng12** [dcloudio/uni-app#2243]
uni.createInnerAudioContext() api在第一次播放的时候获取不到音频的时长

**Comment by chengpeng12** [comment]
this.context = uni.createInnerAudioContext();
this.context.src = "http://dp-ftpserver.oss-cn-shanghai.aliyuncs.com/families-school-connection/file/72384b88-4aaa-4074-886a-a84480caa5b4";
this.context.onCanplay(() => {
	this.context.duration;
	setTimeout(()=>{
		this.duration = this.context.duration;
		console.log(this.duration) // 小程序 0 app 0 h5 Infinity
	},1000)
})

**Comment by chengpeng12** [comment]
`this.context = uni.createInnerAudioContext();
			this.context.src = "http://dp-ftpserver.oss-cn-shanghai.aliyuncs.com/families-school-connection/file/72384b88-4aaa-4074-886a-a84480caa5b4";
			this.context.onCanplay(() => {
				this.context.duration;
				setTimeout(()=>{
					this.duration = this.context.duration;
					console.log(this.duration) // 小程序 0 app 0 h5 Infinity
				},1000)
			})`

**Comment by chengpeng12** [comment]
`this.context = uni.createInnerAudioContext();
this.context.src = "http://dp-ftpserver.oss-cn-shanghai.aliyuncs.com/families-school-connection/file/72384b88-4aaa-4074-886a-a84480caa5b4";
this.context.onCanplay(() => {
	this.context.duration;
	setTimeout(()=>{
		this.duration = this.context.duration;
		console.log(this.duration) // 小程序 0 app 0 h5 Infinity
	},1000)
})`

**Comment by chengpeng12** [comment]
this.context = uni.createInnerAudioContext();
this.context.src = "http://dp-ftpserver.oss-cn-shanghai.aliyuncs.com/families-school-connection/file/72384b88-4aaa-4074-886a-a84480caa5b4";
this.context.onCanplay(() => {
	this.context.duration;
	setTimeout(()=>{
		this.duration = this.context.duration;
		console.log(this.duration) // 小程序 0 app 0 h5 Infinity
	},1000)
})

**Comment by zhetengbiji** [comment]
应该是你这个音频有问题，你试试hello uni-app里的音频

**Comment by chengpeng12** [comment]
> 应该是你这个音频有问题，你试试hello uni-app里的音频

确实是音频的问题，万分谢谢
