### ISSUE TITLE
uniapp开发小程序什么支持vue3 jsx开发模式

### ISSUE THREAD

**Issue by tangly1991** [dcloudio/uni-app#2245]
在某些特殊情况下jsx的形式要比普通的vue模板要更好，也更可控
隔壁taro都已经支持vue3 jsx了，希望官方能尽快支持jsx

**Comment by china-bin** [comment]
+1 希望能支持jsx

**Comment by Ttou** [comment]
> 在某些特殊情况下jsx的形式要比普通的vue模板要更好，也更可控
> 隔壁taro都已经支持vue3 jsx了，希望官方能尽快支持jsx

隔壁怎么支持的，试了不行啊

**Comment by hyccpq** [comment]
> > 在某些特殊情况下jsx的形式要比普通的vue模板要更好，也更可控
> > 隔壁taro都已经支持vue3 jsx了，希望官方能尽快支持jsx
> 
> 隔壁怎么支持的，试了不行啊

隔壁可以的，装个vue官方jsx插件@vue/babel-plugin-jsx，和web配置一毛一样小程序就可以用了

**Comment by Ttou** [comment]
> > > 在某些特殊情况下jsx的形式要比普通的vue模板要更好，也更可控
> > > 隔壁taro都已经支持vue3 jsx了，希望官方能尽快支持jsx
> > 
> > 
> > 隔壁怎么支持的，试了不行啊
> 
> 隔壁可以的，装个vue官方jsx插件@vue/babel-plugin-jsx，和web配置一毛一样小程序就可以用了

看看这个[issue](https://github.com/NervJS/taro/issues/9659)，还在合并中

**Comment by hyccpq** [comment]
> > > > 在某些特殊情况下jsx的形式要比普通的vue模板要更好，也更可控
> > > > 隔壁taro都已经支持vue3 jsx了，希望官方能尽快支持jsx
> > > 
> > > 
> > > 隔壁怎么支持的，试了不行啊
> > 
> > 
> > 隔壁可以的，装个vue官方jsx插件@vue/babel-plugin-jsx，和web配置一毛一样小程序就可以用了
> 
> 看看这个[issue](https://github.com/NervJS/taro/issues/9659)，还在合并中

这仅仅只是还不支持.jsx文件，.vue文件里面是可以的，return直接返回jsx一点问题都没有，项目里面从3.0一开始就一直在用了。

**Comment by Ttou** [comment]
@hyccpq 如果用 jsx 写，是不是编译不了 h5？

**Comment by tangly1991** [comment]
> @hyccpq 如果用 jsx 写，是不是编译不了 h5？
h5的话可以直接使用原版vue3写，装@vue/babel-plugin-jsx创建就能支持jsx/tsx
uniapp的vue3版刚出来的时候用过一下，一些vue3变更的模板语法居然被官方替换成vue2的，搞得后面切换原版vue3改了好久，有蛮长时间没用uniapp了，现在不知道改了这个没有
如果还是一样的话，建议开发h5就不要用uniapp了，跟着vue官方的走好些

**Comment by Lisheri** [comment]
> > > > > 在某些特殊情况下jsx的形式更好普通的vue模板要，也可以更远
> > > > > 隔壁芋头已经支持vue3jsx了，希望官方能尽快支持jsx
> > > > 
> > > > 
> > > > 隔壁怎么支持的，试了不行啊
> > > 
> > > 
> > > 隔墙可以的，装个vue官方jsx插件@vue/babel-plugin-jsx，和web配置一毛一样小程序就可以用了
> > 
> > 
> > 看看这个[问题](https://github.com/NervJS/taro/issues/9659)，还在合并中
> 
> 这虽然还不支持.jsx文件，.vue文件里面是可以的，直接返回jsx一点问题都没有，我们项目里面从3.0一开始就一直在用了。去年1月份的时候，我们技术选型的时候就是因为uni不能选的uniapp写jsx才没有选的uniapp，我们本来项目jsx的东西了，迁移贼麻烦。

老哥, 我用的2.x的vue, 配置了babel-plugin-jsx, 但是会报编译错误

这是我的配置:

```js
const plugins = ["@vue/babel-plugin-jsx"]

if (process.env.UNI_OPT_TREESHAKINGNG) {
  plugins.push(require('@dcloudio/vue-cli-plugin-uni-optimize/packages/babel-plugin-uni-api/index.js'))
}

if (
  (
    process.env.UNI_PLATFORM === 'app-plus' &&
    process.env.UNI_USING_V8
  ) ||
  (
    process.env.UNI_PLATFORM === 'h5' &&
    process.env.UNI_H5_BROWSER === 'builtin'
  )
) {
  const path = require('path')

  const isWin = /^win/.test(process.platform)

  const normalizePath = path => (isWin ? path.replace(/\\/g, '/') : path)

  const input = normalizePath(process.env.UNI_INPUT_DIR)
  try {
    plugins.push([
      require('@dcloudio/vue-cli-plugin-hbuilderx/packages/babel-plugin-console'),
      {
        file (file) {
          file = normalizePath(file)
          if (file.indexOf(input) === 0) {
            return path.relative(input, file)
          }
          return false
        }
      }
    ])
  } catch (e) {}
}

process.UNI_LIBRARIES = process.UNI_LIBRARIES || ['@dcloudio/uni-ui']
process.UNI_LIBRARIES.forEach(libraryName => {
  plugins.push([
    'import',
    {
      'libraryName': libraryName,
      'customName': (name) => {
        return `${libraryName}/lib/${name}/${name}`
      }
    }
  ])
})
module.exports = {
  presets: [
    [
      '@vue/app',
      {
        modules: 'commonjs',
        useBuiltIns: process.env.UNI_PLATFORM === 'h5' ? 'usage' : 'entry'
      }
    ],
    // * jsx插件合集
    ["@vue/babel-preset-jsx", { compositionAPI: true }],
  ],
  plugins
}

```
我使用了'@vue/composition-api', 开了compositionAPI, 这个是正常的, 但是都不能在render函数中返回一段jsx, 只要有就会报错, 并不是直接的jsx文件, 就是一个.vue文件内, 而且是用的optionsAPI

**Comment by Ttou** [comment]
@Lisheri 他说的是隔壁那个，uniapp 不支持 jsx

**Comment by fxy060608** [comment]
App，H5 平台可以支持jsx,tsx
小程序平台暂无计划支持

**Comment by Otto-J** [comment]
#4683

**Comment by alamhubb** [comment]
开了个坑，让uniapp的小程序端支持渲染函数了，

https://github.com/alamhubb/uni-render

实现原理

https://github.com/alamhubb/uni-render/blob/main/TechnicalImplementation.md


相关文章

https://zhuanlan.zhihu.com/p/1994149291560813794


vue的jsx是基于渲染函数的，所以准备顺便支持下jsx
