### ISSUE TITLE
view执行动画后，切换页面，动态属性不生效

### ISSUE THREAD

**Issue by zramals** [dcloudio/uni-app#225]
**问题描述**
view执行动画后，切换页面在切换回来，比如跳转，切换tab，view的:style中动态属性不生效

**复现步骤**
view中：
 :animation="animationData" class="hp_searchBar" :style="'height:'+(44+searchTopPosition)+'px'"

data中：
searchTopPosition: sysConst.systemInfo.statusBarHeight,

onload中：
var animation = uni.createAnimation({
				duration: 200,
				timingFunction: 'linear',
			})
this.animation = animation

method中：
this.animation.backgroundColor('#ffffff').step()
this.animationData = this.animation.export()

**预期结果**
切换回页面，view高度是44+ searchTopPosition的高度

**实际结果**
切换回页面，view高度只有44

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统： iOS 12.1.2
 - HBuilderX版本 ：1.6.2 20190220

**Comment by mehaotian** [comment]
您好，你应该是在onload 中去执行的动画吧 ？尝试在 onshow 中执行试试。

**Comment by zramals** [comment]
好 我去试试

**Comment by zramals** [comment]
> 您好，你应该是在onload 中去执行的动画吧 ？尝试在 onshow 中执行试试。

我是在滑动的时候执行动画，变色的动画
动画是没问题的，切完tab以后 动态属性就失效了
:style="'height:'+(44+searchTopPosition)+'px'"这句中的height就会变成44了。。。
我试了把onload中的代码放到onshow也是不行的。。

**Comment by zhetengbiji** [comment]
测试未复现，更新 HBuilderX 试试
