### ISSUE TITLE
v-model绑定数据提交少字

### ISSUE THREAD

**Issue by tenlisen** [dcloudio/uni-app#2254]
**问题描述**
[问题描述：
v-model双向绑定数据，用户在用手写输入时，最后一个没有点击候选字，例如“张三丰”，最后一个“丰”字没有点击候选字，但是输入框已显示“张三丰”三个字，导致提交后少了一个“丰”，最终用户看到的时“张三”。

**Comment by zhetengbiji** [comment]
新版已有相关优化
