### ISSUE TITLE
如何控制tabbar的selectedItem

### ISSUE THREAD

**Issue by wwavelet** [dcloudio/uni-app#2257]
**新功能描述**
uni-app文档中没有看到可控tabbar选中项的方式

**现状及问题**

原生微信通过这个方式可以设置选中项：
`this.getTabBar().setData({
          selected: index,
 });
`

在很多场景中会使用到，比如链接分享出去后用户从链接进入，这时tabbar项必须可控才行。

**尝试方案**
看到网上有说`this.$mp.page.getTabBar()`的方式获取tabbar，但是尝试之后返回的是null

**补充信息**

**Comment by SimonPower** [comment]
vue3版本，onShow下：

this.getTabbar
this.$mp.page.getTabBar

都找不到该方法。

**Comment by fxy060608** [comment]
> vue3版本，onShow下：
> 
> this.getTabbar this.$mp.page.getTabBar
> 
> 都找不到该方法。

getTabBar仅适用于微信小程序自定义tabBar模式，非自定义tabBar模式，请使用uni.setTabBar相关API
获取方式：this.$scope.getTabBar()

**Comment by SimonPower** [comment]
使用的就是自定义tabbar，需要在页面onShow去getTabbar更新选中索引。

**但是在页面的onShow下：**
```
this.$scope.getTabBar()
```
getTabBar还是undefined

**unaippp版本:**

![image](https://user-images.githubusercontent.com/38357267/142347093-ddbf8bae-4fc0-4aa2-809d-4c2483944a17.png)

**Comment by chenglu4343** [comment]
> 使用的就是自定义tabbar，需要在页面onShow去getTabbar更新选中索引。
> 
> **但是在页面的onShow下：**
> 
> ```
> this.$scope.getTabBar()
> ```
> 
> getTabBar还是undefined
> 
> **uniapp版本:**
> 
> ![image](https://user-images.githubusercontent.com/38357267/142347093-ddbf8bae-4fc0-4aa2-809d-4c2483944a17.png)

我通过这种方式成功获取到了tabbar的实例

```html
<script lang="ts">
export default {
  created() {
    const tabbar = this.$scope.getTabBar()
    console.log('tabbar.data', tabbar.data)
  },
}
</script>
```


版本如下

```
"@dcloudio/uni-app": "3.0.0-4060620250520001",
"@dcloudio/uni-app-harmony": "3.0.0-4060620250520001",
"@dcloudio/uni-app-plus": "3.0.0-4060620250520001",
"@dcloudio/uni-components": "3.0.0-4060620250520001",
"@dcloudio/uni-h5": "3.0.0-4060620250520001",
"@dcloudio/uni-mp-alipay": "3.0.0-4060620250520001",
"@dcloudio/uni-mp-baidu": "3.0.0-4060620250520001",
"@dcloudio/uni-mp-harmony": "3.0.0-4060620250520001",
"@dcloudio/uni-mp-jd": "3.0.0-4060620250520001",
"@dcloudio/uni-mp-kuaishou": "3.0.0-4060620250520001",
"@dcloudio/uni-mp-lark": "3.0.0-4060620250520001",
"@dcloudio/uni-mp-qq": "3.0.0-4060620250520001",
"@dcloudio/uni-mp-toutiao": "3.0.0-4060620250520001",
"@dcloudio/uni-mp-weixin": "3.0.0-4060620250520001",
"@dcloudio/uni-mp-xhs": "3.0.0-4060620250520001",
"@dcloudio/uni-quickapp-webview": "3.0.0-4060620250520001",
"@dcloudio/uni-ui": "^1.5.7",
"vue": "^3.5.13",
```
