### ISSUE TITLE
app 里video组件 的@fullscreenchange捕获不到对应id

### ISSUE THREAD

**Issue by Xieweikang123** [dcloudio/uni-app#2259]
如题，在视图中的<video @fullscreenchange="videoScreenChange"></video>(其它省略)
然后写上方法
`	videoScreenChange(e){
			console.log("videoScreenChange",e)
		},`
在H5页面调试输出e，能正常显示video id，但是在手机调试时打印输出则不显示。
![image](https://user-images.githubusercontent.com/30288645/98764130-1da27a80-2416-11eb-8b03-f369e6607c56.png)

**Comment by StrivingRabbit** [comment]
你是怎么使用的 video 组件，该组件默认情况下就是不会返回 id
