### ISSUE TITLE
Picker mode=date 钉钉小程序出现BUG

### ISSUE THREAD

**Issue by Deepx-China** [dcloudio/uni-app#2263]
当前显示

YYYY-MM-DD H:i:s

可否只显示

YYYY-MM-DD

**Comment by pandashuai** [comment]
我也遇到了，你怎么解决的？

**Comment by zhetengbiji** [comment]
#2425

**Comment by Deepx-China** [comment]
> #2425

我最终的解决方案是直接使用“钉钉日期Api”，因为我的应用的需求只是钉钉小程序，如果有多端需求，可使用uniapp判断终端的函数

**Comment by Deepx-China** [comment]
> 我也遇到了，你怎么解决的？

我最终的解决方案是直接使用“钉钉日期Api”，因为我的应用的需求只是钉钉小程序，如果有多端需求，可使用uniapp判断终端的函数
