### ISSUE TITLE
uni-app开发多端组件库，不能被纯vue项目调用

### ISSUE THREAD

**Issue by Kellercai** [dcloudio/uni-app#2267]
想请教一下，如果想用uni-app开发多端组件库，其生成的H5组件可以让非uniapp项目引用。这个方案可行吗？目前发现uni-app的组件库都是提供给uni-app项目使用的，而且uni-app的H5打包方式好像没办法改变。希望官方解答一下。

**Comment by zhetengbiji** [comment]
可以

以下任意方案即可：
1. 取其交集，保证使用的接口在各个平台都支持，无差异的部分
2. 运行时判断环境差异化处理，保留不同平台差异
3. 不同端编译成不同的文件，保留不同平台差异

**Comment by Kellercai** [comment]
> 可以
> 
> 以下任意方案即可：
> 
> 1. 取其交集，保证使用的接口在各个平台都支持，无差异的部分
> 2. 运行时判断环境差异化处理，保留不同平台差异
> 3. 不同端编译成不同的文件，保留不同平台差异

您好，很高兴您的解答。我这里是需要用uniapp生成打包出来的组件可以被纯vue项目使用。可是目前uniapp打包出来的h5文件是一个页面。并不能像组件库那样子暴露出来哦！

**Comment by zhetengbiji** [comment]
> > 可以
> > 以下任意方案即可：
> > 
> > 1. 取其交集，保证使用的接口在各个平台都支持，无差异的部分
> > 2. 运行时判断环境差异化处理，保留不同平台差异
> > 3. 不同端编译成不同的文件，保留不同平台差异
> 
> 您好，很高兴您的解答。我这里是需要用uniapp生成打包出来的组件可以被纯vue项目使用。可是目前uniapp打包出来的h5文件是一个页面。并不能像组件库那样子暴露出来哦！

为什么把要共享的组件用uni-app打包出来？如果是打包出来的uni-app项目能用吗？

**Comment by Kellercai** [comment]
> > > 可以
> > > 以下任意方案即可：
> > > 
> > > 1. 取其交集，保证使用的接口在各个平台都支持，无差异的部分
> > > 2. 运行时判断环境差异化处理，保留不同平台差异
> > > 3. 不同端编译成不同的文件，保留不同平台差异
> > 
> > 
> > 您好，很高兴您的解答。我这里是需要用uniapp生成打包出来的组件可以被纯vue项目使用。可是目前uniapp打包出来的h5文件是一个页面。并不能像组件库那样子暴露出来哦！
> 
> 为什么把要共享的组件用uni-app打包出来？如果是打包出来的uni-app项目能用吗？

您好，因为我们想要在后台做一个前端组件可视化编辑器，然后想把公共的组件抽离出来，一是要提供给管理后台的纯vue项目，二是提供给uniapp系的小程序app等端口。所以我借用了uni ui的脚手架，然后发现打包出来的组件只能被uniapp识别使用。不知道uniapp在打包多端的时候能不能自定义路径呢？

**Comment by zhetengbiji** [comment]
> > > > 可以
> > > > 以下任意方案即可：
> > > > 
> > > > 1. 取其交集，保证使用的接口在各个平台都支持，无差异的部分
> > > > 2. 运行时判断环境差异化处理，保留不同平台差异
> > > > 3. 不同端编译成不同的文件，保留不同平台差异
> > > 
> > > 
> > > 您好，很高兴您的解答。我这里是需要用uniapp生成打包出来的组件可以被纯vue项目使用。可是目前uniapp打包出来的h5文件是一个页面。并不能像组件库那样子暴露出来哦！
> > 
> > 
> > 为什么把要共享的组件用uni-app打包出来？如果是打包出来的uni-app项目能用吗？
> 
> 您好，因为我们想要在后台做一个前端组件可视化编辑器，然后想把公共的组件抽离出来，一是要提供给管理后台的纯vue项目，二是提供给uniapp系的小程序app等端口。所以我借用了uni ui的脚手架，然后发现打包出来的组件只能被uniapp识别使用。不知道uniapp在打包多端的时候能不能自定义路径呢？

应该和路径无关吧

**Comment by LHC8888** [comment]
请问题主有方案了吗 @Kellercai
