### ISSUE TITLE
不支持链式判断符

### ISSUE THREAD

**Issue by liujiayii** [dcloudio/uni-app#2268]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
![QQ图片20201114114736](https://user-images.githubusercontent.com/38902744/99138910-4cfff400-266f-11eb-8d84-5629037be0e3.png)
编译报错
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by TuiMao233** [comment]
使用typescript支持可选操作符

**Comment by liujiayii** [comment]
> 使用typescript支持可选操作符

nvue不支持typescript 原生vue是支持链式判断的

**Comment by TuiMao233** [comment]
估计是uniapp内置的babel没有更新版本，这个得让uni官方解决

**Comment by Soya-xy** [comment]
什么时候可以更新一下啊

**Comment by yuanjianhua** [comment]
这个有没有解决的？
