### ISSUE TITLE
【重大错误】通过事件触发的方法，接收到的args错误（会附带10个undefined和1个事件对象）

### ISSUE THREAD

**Issue by devilwjp** [dcloudio/uni-app#2270]
**问题描述**
发布成微信小程序，通过事件触发的方法，接收到的args，会附带10个undefined和1个事件对象

**复现步骤**
```
<template>
	<view class="content">
		<view>
			<text class="title" @click="test(1)">{{title}}</text>
		</view>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				title: 'Hello'
			}
		},
		methods: {
			test (...args) {
				console.log(args)
				return 'test'
			}
		}
	}
</script>
```
**预期结果**
点击文字后，触发的test方法的args打印出来应该是 `[1]`

**实际结果**
点击文字后，触发的test方法的args答应出来的是  
`[1, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, {...}]`

**系统信息:**
 - 发行平台: 微信小程序（其他未测）
 - 操作系统 微信小程序IDE
 - uni-app版本  
uni-app v2.9.8
uni-app cli v2.0.0-29820201110001
 - 设备信息 PC 微信小程序IDE  

**补充信息**
根据我的分析，问题应该是出在了解析vue template的过程中出错了

**Comment by devilwjp** [comment]
回退到  
uni-app v2.7.8  
uni-app cli v2.0.0-27820200526001  
是好的

**Comment by devilwjp** [comment]
@hbcui1984 关注下这个问题

**Comment by zhetengbiji** [comment]
并非“【重大错误】“
当前结果目前是符合预期的，这是事件转换到小程序时为了解决部分兼容问题采取的一个方案

**Comment by zhetengbiji** [comment]
多余的参数，后续会考虑优化，不对开发者开放

**Comment by devilwjp** [comment]
@zhetengbiji 业务场景中会有不少函数是可变长度参数，并且最后一个参数是callback，现在这些函数用在事件上将出错 ，因为将无法获取到真正的参数长度和最后一个参数

**Comment by zhetengbiji** [comment]
> @zhetengbiji 业务场景中会有不少函数是可变长度参数，并且最后一个参数是callback，现在这些函数用在事件上将出错 ，因为将无法获取到真正的参数长度和最后一个参数

好的，后续会考虑继续改进或采用其他优化方案
