### ISSUE TITLE
uniapp H5版本ssr问题

### ISSUE THREAD

**Issue by chenzefeng09** [dcloudio/uni-app#2278]
**问题描述**
配置uni-app项目h5端的ssr，无法运行
**复现步骤**

demo及复现步骤已总结到链接
https://github.com/chenzefeng09/uniapp-ssr-demo

**预期结果**

根据Issue #2194 中的回复，认为uni-app目前是可以手动配置开启ssr的。

@zhetengbiji 

**实际结果**
只有当测试页面没有style标签的时候才能渲染出节点，如果有style，会报500错误。
无法运行，报错 
`
TypeError: Cannot read property 'style' of undefined
`

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [Mac]
 - HBuilderX版本 [无]
 - uni-app版本 [2.0.0-28620200814002]
 - 设备信息 [Mac Chrome]

**补充信息**
[Node版本 12.19.1]
[uni-app自定义的vue-loader是否对ssr有影响？]

**Comment by jobin-sun** [comment]
同求, 如何解决

**Comment by 18696232390** [comment]
哈哈，老哥，uniapp不支持的ssr的，我最后的解决方案是换成原生的html+vue.js

**Comment by chenzefeng09** [comment]
根据调试定位，上文中的报错TypeError: Cannot read property 'style' of undefined
发生在这段代码中
https://github.com/dcloudio/uni-app/blob/d2d78c459af50216abab6fc41d6f12680fc35756/packages/vue-cli-plugin-uni/packages/vue-loader/lib/codegen/styleInjection.js#L102
如果将这一段自定义代码恢复为原生的vue-loader代码，则运行时不会报错。但是样式依然是乱的，感觉width/height等宽高样式都没有转换过

@zhetengbiji

**Comment by zhetengbiji** [comment]
收到，针对报错部分，后续会进行调整
