### ISSUE TITLE
什么时候APP可以打升级包

### ISSUE THREAD

**Issue by aiplat** [dcloudio/uni-app#228]
**新功能描述**
APP可以打升级包，就是发行时可以制作移动APP资源升级包

**现状及问题**
现在只敢用于小程序的开发

**尝试方案**
理论上发行时可以制作移动APP资源升级包可以直接用VUE打包后的文件制作成.wgt包

**补充信息**
无

**Comment by wanganxp** [comment]
wgt包下个版本支持

**Comment by xiaoyucoding** [comment]
1.7.0 已更新并支持此功能
