### ISSUE TITLE
反馈一个不知道是不是bug的问题

### ISSUE THREAD

**Issue by fuyidaotang** [dcloudio/uni-app#2285]
**问题描述**
一个组件，组件中设置了一个插槽，在某个页面引入该组件，并在该组件中设置了插槽内容，插槽内容是一个v-for循环的结构，v-for="item in list"
这个时候，item是那不到数据的，但是index可以，然后修改item名称为sub，比如 v-for="sub in list" 就能解决这个问题，我在下面贴上详细代码

**复现步骤**

以下为页面中引入
<popup :isShow="redbagListShow" @onHide="closeRedbagList" data-name="redbagListShow">
							<view class="redbag-list">
								<view v-for="(sub, index2) in redPacketList" :key="index2" class="redbag-item flex" @tap="selectRedbag"
								 :data-index="index2">
									<view class="flex">
										<image class="redbag-img" :src="sub.userInfo.userHead" mode="aspectFill"></image>
										<view class="redbag-text">
											<text class="fz28">{{sub.userInfo.userName}}的红包</text>
											<text class="fz20 color-8">共{{sub.packetAmount}}元 已领取{{sub.receiveCount || 0}}/{{sub.packetNumber}}个</text>
										</view>
									</view>
									<view class="redbag-right color-8" v-if="sub.isReceive">已领取</view>
									<view class="redbag-right redbag-btn" v-else>抢红包</view>
								</view>
							</view>
						</popup>

以下为子组件代码
<template>
<view class="pop-wrapper" :hidden="!isShow">
    <view class="blank " @tap="bindBlankClose" catchtouchmove="stopScroll" :style="blankColor ? 'background-color:'+blankColor : ''"></view>
    <view class="popup-panel" catchtouchmove="stopScroll" :style="panelColor ? 'background-color:'+panelColor : ''" v-if="position !== 'center'"> 
        <view class="popup-title" v-if="title">{{title}}</view>
        <view class="pop-close" v-if="!noClose" @tap="close"></view>
        <slot></slot>
    </view>
    <block v-else>
        <slot></slot>
    </block>
</view>
</template>

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统  iOS 12.1.2
 - HBuilderX版本 2.9.7.20201105

**Comment by zhenyuWang** [comment]
HBuilderX 3.7.3 vue2 测试未复现该问题，问题暂时关闭；
若后续依然有问题，可 reopen 该 issue。
