### ISSUE TITLE
safeAreaInsets.bottom 为负值

### ISSUE THREAD

**Issue by mingtianyihou33** [dcloudio/uni-app#2291]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  将pages.json的globalStyle.navigationStyle设置为default
2. 获取系统信息const systemInfo = uni.getSystemInfoSync()
3. 查看systemInfo.safeAreaInsets.bottom

[或者可以直接贴源代码]

**预期结果**
为实际的底部安全区域高度

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/22953606/99936528-50495d00-2d9e-11eb-8cd5-2debb908ea07.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: ios 和安卓都有这个现象
 - HBuilderX版本 2.9.8.20201110
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
目前应该是这么计算的：
systemInfo.safeAreaInsets.bottom = systemInfo.safeArea.height - systemInfo.safeArea.bottom
这样计算才对：
systemInfo.safeAreaInsets.bottom = systemInfo.screenHeight - systemInfo.safeArea.bottom

**Comment by xuanxuan321** [comment]
我也遇到这个问题了，这个bug一致没人修复吗

**Comment by zhetengbiji** [comment]
> 我也遇到这个问题了，这个bug一致没人修复吗

新版已修复（真机），模拟器上的话由于缺少必要的属性（微信小程序开发工具的问题），计算无法准确。

**Comment by zhetengbiji** [comment]
https://ask.dcloud.net.cn/question/133479
