### ISSUE TITLE
uni-app 编译微信小程序，切换input弹出键盘失败

### ISSUE THREAD

**Issue by HPLWC** [dcloudio/uni-app#2298]
**问题描述**
编译成小程序下，同层input标签的切换会闪动，并先将软键盘收起再弹出，且经常出现弹出失败的情况，需再次点击才能弹出

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
```
<div class="child-password-form-input">
    <input type="text" />
</div>
<div class="child-password-form-input">
    <input type="text" />
</div>
```
**预期结果**
键盘不要收起，或者不会出现弹出失败的情况

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: Android 9
 - uni-app版本: `uni-app v2.8.8` `uni-app cli v2.0.0-28820200820001`
 - 设备信息: 小米9

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
如果不是使用uni-app编译的小程序就没有这种情况吗？

**Comment by HPLWC** [comment]
> 如果不是使用uni-app编译的小程序就没有这种情况吗？

原生微信小程序安卓还没发现这个情况

**Comment by HPLWC** [comment]
我重新构建了一个项目，编译包小占用内存也不大的情况下不会出现该问题

**Comment by smoothdvd** [comment]
没问题啊
![IMG_1089](https://user-images.githubusercontent.com/22420/100295104-b6fb9000-2fc3-11eb-9f22-1358f7c0d204.jpeg)

**Comment by HPLWC** [comment]
猜测会不会可能是小程序包太大、内存占用多导致的？

**Comment by HPLWC** [comment]
重新构建了各项目，发现在非tabbar页面会产生这种问题，请问有什么办法解决吗？

**Comment by smoothdvd** [comment]
似乎要加个延时

**Comment by aaa377957570** [comment]
为什么官方会这么垃圾，搜遍全网没有结果

**Comment by zhetengbiji** [comment]
> 为什么官方会这么垃圾，搜遍全网没有结果

微信小程序吗？

**Comment by agnij** [comment]
有结果吗 请问

**Comment by fangfuhaomin** [comment]
这个问题在原生entity的微信小程序也出现，我就是原生出现这个改用uniapp结果还是一样

**Comment by wisdom-ray** [comment]
现在是什么情况，我也有同样的问题

**Comment by zhetengbiji** [comment]
> 这个问题在原生entity的微信小程序也出现，我就是原生出现这个改用uniapp结果还是一样

那说明问题出在更底层，需要反馈到微信小程序社区

**Comment by JohnDn** [comment]
现在都没解决方案？

**Comment by zhetengbiji** [comment]
> 现在都没解决方案？

是微信小程序吗？是的话麻烦去社区反馈一下，微信官方的人员是不会看咱们这里的。
