### ISSUE TITLE
uni-app的textarea绑定foucs无效

### ISSUE THREAD

**Issue by junk123321** [dcloudio/uni-app#23]
详细问题描述
[内容]
uni-app的textarea绑定foucs无效
重现步骤
[步骤]
template里面加上<textarea :focus="textareaFocus" auto-height />
在js写上
	export default {
		data() {
			return {
				textareaFocus: true
			}
		},
		onLoad: function (option) {
			this.textareaFocus = true // 页面加载不能使textarea获得焦点
		},
		methods: {
			focusTextarea() { // 按下按钮也不能使textarea获得焦点
				this.textareaFocus = true
			}
		}
	}
[结果]
页面加载完毕，或者按按钮，都不能使textarea获得焦点
[期望]
页面加载完毕，或者按按钮，textarea获得焦点，弹出键盘，用户可以直接填写内容

运行环境
[系统版本]
andriod 8.0
[浏览器版本]
[IDE版本]
HbuilderX 0.1.46.20180810-alpha

**Comment by junk123321** [comment]
谢谢回复
请问有什么别的办法可以实现类似的效果吗

**Comment by hulinNeil** [comment]
input组件在5+app已支持focus属性（绑定固定值或动态修改）；
textarea组件的focus属性目前在5+app只支持绑定固定值，不支持动态修改。

**Comment by hbcui1984** [comment]
issue超过1个月不回应，暂时关闭，若继续有问题，可以重开或发新issues

**Comment by chygWang** [comment]
@hulinNeil    请问您上面说的意思是  textarea只要初始化设置为true    则可以聚焦？   

  我这边遇到textarea  不聚焦的问题

**Comment by miisystem** [comment]
微信小程序 focus 也是不可控
