### ISSUE TITLE
cli模式下不生成manifest.json，手写manifest.json也不生效

### ISSUE THREAD

**Issue by haohetao** [dcloudio/uni-app#2301]
**问题描述**
cli模式下不生成manifest.json，手写manifest.json也不生效

**复现步骤**
1.  按照官方教程创建hello world项目
2. npm run dev:mp-weixin
3. 微信开发者工具中导入项目

**预期结果**
应该生成正确的project.config.json文件

**实际结果**
project.config.json中的小程序appid是错误的，始终是touristappid

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 
 - HBuilderX版本
 - uni-app版本 
> my-project@0.1.0 info E:\src\my-project
> node node_modules/@dcloudio/vue-cli-plugin-uni/commands/info.js

uni-app v2.9.8
uni-app cli v2.0.0-29820201110001

Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.19041.423.0
  npmPackages:
    @dcloudio/types: * => 2.0.18
    @dcloudio/uni-app-plus: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-automator: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-cli-shared: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-h5: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-helper-json: * => 1.0.9
    @dcloudio/uni-migration: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-mp-360: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-mp-alipay: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-mp-baidu: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-mp-qq: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-mp-toutiao: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-mp-vue: ^2.0.0-29820201110001 => 2.0.0-alpha-29920201125002
    @dcloudio/uni-mp-weixin: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-quickapp-native: ^2.0.0-29820201110001 => 2.0.0-alpha-29920201125002
    @dcloudio/uni-quickapp-webview: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-stat: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-template-compiler: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @hap-toolkit/dsl-vue:  0.6.13
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2
    @vue/babel-plugin-jsx:  1.0.0-rc.3
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.9
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.9
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.9
    @vue/cli-plugin-router:  4.5.9
    @vue/cli-plugin-vuex:  4.5.9
    @vue/cli-service: ~4.5.0 => 4.5.9
    @vue/cli-shared-utils:  4.5.9
    @vue/component-compiler-utils:  3.2.0 (3.2.0)
    @vue/preload-webpack-plugin:  1.1.2
    @vue/shared: ^3.0.0 => 3.0.2
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.11 => 2.6.12
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.5 (16.0.0, 15.9.5)
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.12 (2.6.12)
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.2.0 => 3.6.0
  npmGlobalPackages:
    @vue/cli: Not Found
 - 设备信息

**补充信息**
如果手动创建project.config.json文件在项目根目录会导致dist中没有project.config.json文件(发行目录这个文件完全消失)

**Comment by haohetao** [comment]
排错结果如下
1，发行(hbuilder x)后小程序appid会自动写入manifest.json
2，vue-cli创建的项目manifest.json是在src目录中，hbuilder创建的项目是在项目根目录

**Comment by haohetao** [comment]
希望在开发文档的醒目位置标出此差异，以免新手走弯路

**Comment by zhetengbiji** [comment]
c421424e8d7f18b8f0f5c105cc742bd453be3636
