### ISSUE TITLE
slot scope取到的值在父组件中使用filter时对象为未定义，但直接在dom显示是可以的。

### ISSUE THREAD

**Issue by sunyitao** [dcloudio/uni-app#2302]
**问题描述**
slot scope取到的值在父组件中使用filter时对象为未定义，但直接在dom显示是可以的。

**复现步骤**
错误：提示item未定义
```<view class="cu-tag bg-gray light sm round">{{ item.pile | pileName }}</view>```

正常显示：
```<view class="cu-tag bg-gray light sm round">{{ item.pile }}</view>```

**系统信息:**
 - 发行平台:微信小程序
 - 操作系统 win10小程序模拟器
 - HBuilderX版本 webstorm
 - uni-app版本 
uni-app v2.9.8
uni-app cli v2.0.0-29820201110001
 - 设备信息 小程序模拟器

**补充信息**

**Comment by zhuyaofeng** [comment]
我也发现了这个问题，不知道怎么解决

**Comment by zhetengbiji** [comment]
> 我也发现了这个问题，不知道怎么解决

版本多少？

**Comment by steptobe** [comment]
同样遇到  最新一版

**Comment by zhetengbiji** [comment]
> 同样遇到 最新一版

版本多少？

**Comment by steptobe** [comment]
> > 同样遇到 最新一版
> 
> 版本多少？
2.9.8.20201110  有题主所说问题
3.1.22.20210709 这版这个问题没了  但是v-for的数据就会只显示一个
组件这样写
![image](https://user-images.githubusercontent.com/9783082/127635655-c122262d-25cf-4630-8e5e-2f103abf213f.png)

**Comment by zhetengbiji** [comment]
针对插槽渲染多个实例的方案后续统一会在 #3503 继续跟进
