### ISSUE TITLE
checkbox  不支持v-model

### ISSUE THREAD

**Issue by zheiop** [dcloudio/uni-app#2310]
为什么checkbox无法单独使用，必须依赖checkbox-group。
一个checkbox也必须加一层checkbox-group，使用起来不方便。

**Comment by zhetengbiji** [comment]
因为规范是微信小程序先行指定的，后续其他平台都实现为了相同的用法

为了使用方便，后续很多开发者封装了你喜欢的类型：https://ext.dcloud.net.cn/search?q=checkbox
