### ISSUE TITLE
uni-app推送，请问除了内置的苹果、华为、小米、OPPO、魅族等手机厂商的系统级推送以外，其他的厂商离线消息应该怎么处理呢

### ISSUE THREAD

**Issue by a4638966** [dcloudio/uni-app#2312]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
查文档后，发现内置了苹果、华为、小米、OPPO、魅族等手机厂商的系统级推送，我们现在的推送没有在其中，那其他厂商的手机怎么保证app进程被杀死以后的离线推送呢

**Comment by zhetengbiji** [comment]
厂商推送是用于提高到达率的，无厂商推送时将使用个推自己的保达手段（具体技术要点可以咨询个推看是否可以透露）
