### ISSUE TITLE
Apple M1 环境下无法进行 iOS 离线打包

### ISSUE THREAD

**Issue by Cat7373** [dcloudio/uni-app#2313]
**问题描述**
Apple M1 环境下无法进行 iOS 离线打包

**复现步骤**
1.  确保正在使用 Apple M1 CPU 的设备
2. 导入 SDK 中的 HBuilder-Hello 项目
3. 选择任意 iOS 模拟设备，点击运行

**预期结果**
正常编译并启动模拟器，运行示例项目

**实际结果**
```
ld: in /Users/cat73/Downloads/iOSSDK@2.9.8.80363_20201110/SDK/Libs/libuchardet.a(LangLithuanianModel.o), building for iOS Simulator, but linking in object file built for iOS, file '/Users/cat73/Downloads/iOSSDK@2.9.8.80363_20201110/SDK/Libs/libuchardet.a' for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**系统信息:**
 - 发行平台: App
 - 操作系统 MacOS 11.0.1
 - HBuilderX版本 2.9.8
 - uni-app版本 2.9.8
 - 设备信息 iPhone 12 Pro(模拟器)

**Comment by Cat7373** [comment]
更新：使用 x86 模拟（Rosetta）运行 Xcode 时，可以正常打包，但 Xcode 使用流畅度要弱于基于 Arm 架构运行，此条供已经购买新 Mac 的朋友参考

**Comment by Nicolana** [comment]
有解决办法吗

**Comment by Cat7373** [comment]
记得当时解决了，但现在已放弃此框架，资料已经都删了

**Comment by Nicolana** [comment]
我也想放弃了。哎，奈何重新开发太费时费力

**Comment by Nicolana** [comment]
方便提供下大概思路吗，我尝试下解决。

**Comment by Cat7373** [comment]
忘记具体操作了，反正是改项目配置，改吧改吧就能用了

**Comment by Nicolana** [comment]
我折腾折腾
<img width="606" alt="截屏2021-10-01 下午5 33 25" src="https://user-images.githubusercontent.com/20972473/135598744-b0a305a9-cf7f-4c62-a1cb-342c4938e17c.png">
出来了，贴出来给各位参考

在Exculded Architecture里面添加一个arm64就可以了。

**Comment by Cat7373** [comment]
XCode 用 Rosetta 模拟的情况下应该不需要改什么，用 arm 架构记得需要改一点配置
