### ISSUE TITLE
App.vue里加上template(为了使用keep-alive)后，uni.showModal等弹窗失效

### ISSUE THREAD

**Issue by xlkit456852** [dcloudio/uni-app#2315]
**问题描述**
为了对首页进行keep-alive，在App.vue里加上了一段<template>，原本是只有原始的<script>和<style>
加上的代码如下：
```
<template>
    <view id="app" >
		<keep-alive :include="/index/">
			<router-view></router-view>
		</keep-alive>
	</view>
</template>
```
这样的确是对首页进行了keep alive，但是发现项目里的所有uni.showToast、uni.showModal等弹出窗口全部都不能弹出，但是去掉<template>块后是可以正常弹出的。请问可以如何解决？或者keep-alive这里可以以别的方式使用来避免这种情况出现吗？

**预期结果**
showToast等正常使用

**实际结果**
showToast等不能弹出

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [Chrome]
 - HBuilderX版本 [HBuilderX2.9.7]

**Comment by zhetengbiji** [comment]
默认就有不必自行添加，建议不要覆盖

**Comment by xlkit456852** [comment]
感谢解答。但是默认情况下，我从首页跳转去别的页面后，再回到首页，首页还是会刷新，也会执行onLoad等生命周期函数，没有keep-alive的效果？

**Comment by zhetengbiji** [comment]
> 感谢解答。但是默认情况下，我从首页跳转去别的页面后，再回到首页，首页还是会刷新，也会执行onLoad等生命周期函数，没有keep-alive的效果？

不会的，除非你用了rexxx的接口或者跳到了其他站点

**Comment by zhetengbiji** [comment]
> > 感谢解答。但是默认情况下，我从首页跳转去别的页面后，再回到首页，首页还是会刷新，也会执行onLoad等生命周期函数，没有keep-alive的效果？
> 
> 一般不会出现这种问题的，除非你跳转到了其他站点

**Comment by zhetengbiji** [comment]
你可以发一个测试地址，我看下

**Comment by xlkit456852** [comment]
有可能是因为我用了uni-simple-router这个插件才出现了这种情况。我自己重新建一个空白项目来测试，发现的确是可以keep-alive。但是现在并不知道这个插件是因为哪个地方改变了这种keep-alive的行为。。

**Comment by zhetengbiji** [comment]
> 有可能是因为我用了uni-simple-router这个插件才出现了这种情况。我自己重新建一个空白项目来测试，发现的确是可以keep-alive。但是现在并不知道这个插件是因为哪个地方改变了这种keep-alive的行为。。

可以看下插件源码或者和作者交流一下
