### ISSUE TITLE
无网络状态下报错

### ISSUE THREAD

**Issue by xiaoxiaodemeng** [dcloudio/uni-app#2317]
**预期结果**
不会报错

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/30209304/100702577-e4d63f80-33dc-11eb-8def-196a882cde7c.png)

![image](https://user-images.githubusercontent.com/30209304/100702748-38488d80-33dd-11eb-90ce-e2d927071793.png)

**系统信息:**
 - 发行平台:  微信小程序
 - 操作系统 开发者工具

**Comment by fxy060608** [comment]
你这个错误是微信小程序开发工具自身的错误吧，不是小程序自己的错误
