### ISSUE TITLE
如何实现h5页面重定向路由到404

### ISSUE THREAD

**Issue by lydat** [dcloudio/uni-app#2319]
注意是h5,不是APP

**Comment by SilurianYang** [comment]
[uni-simple-router](https://hhyang.cn/v2/start/h5/redirect.html)

**Comment by lydat** [comment]
> [uni-simple-router](https://hhyang.cn/v2/start/h5/redirect.html)

等破了1000star会考虑这个的,会有没有官方的解决办法
