### ISSUE TITLE
ios9 H5端白屏 官方H5 demo有同样问题

### ISSUE THREAD

**Issue by BrightYang0801** [dcloudio/uni-app#2320]

**Comment by zhetengbiji** [comment]
c752e62e7ebe8738bd8e4bb025b162a2412a11bc

**Comment by BrightYang0801** [comment]
src/platforms/h5/components/app/tabBar.vue 这个文件我本地和你改的内容不一致怎么改

![image](https://user-images.githubusercontent.com/37973515/101140176-8fed3000-364d-11eb-9793-e23aa8956969.png)

**Comment by zhetengbiji** [comment]
你等待发版

**Comment by BrightYang0801** [comment]
已解决，HBuilderX 版本回到 2.8.6.20200814 即可。以后不敢随意升级了，影响用户正常使用的锅背不起。

**Comment by BrightYang0801** [comment]
已解决，HBuilderX 版本回到 2.8.6.20200814 即可

**Comment by ZJH9Rondo** [comment]
> 已解决，HBuilderX 版本回到 2.8.6.20200814 即可

不用Hbuilder怎么解决

**Comment by BrightYang0801** [comment]
> > 已解决，HBuilderX 版本回到 2.8.6.20200814 即可
> 
> 不用Hbuilder怎么解决

降uni-app版本

**Comment by zhetengbiji** [comment]
HBuilderX 3.0.0+ 已修复
