### ISSUE TITLE
mapSearch模块怎么使用

### ISSUE THREAD

**Issue by spiritl7db** [dcloudio/uni-app#2323]
**问题描述**
看uni-app官方文档https://uniapp.dcloud.io/api/location/map?id=mapsearch-%e6%a8%a1%e5%9d%97
没有写如何使用，怎么引用这个模块，以及对各个端的支持程序，都没有体现，希望能解答并补全

**Comment by dcloudhdx** [comment]
仅nvue支持，参考代码 [https://github.com/dcloudio/hello-uniapp/blob/master/pages/API/map-search/map-search.nvue](https://github.com/dcloudio/hello-uniapp/blob/master/pages/API/map-search/map-search.nvue)
