### ISSUE TITLE
编译为支付宝小程序v-for内获取不到data里的数据

### ISSUE THREAD

**Issue by xiaogao67** [dcloudio/uni-app#2326]
**问题描述**
编译为支付宝小程序 v-for内无法获取到data 全都是undefined

**复现步骤**
```
<template>
	<view class="login-content">
		<view v-for="(data, index) in test_list" :key="index">
			{{test_list}} --- {{test_name}}
		</view>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				test_list: ["a", "b", "c", "d"],
				test_name: "test"
			}
		},
	}
</script>

<style>

</style>
```
**预期结果**
在for循环里获取到data里定义的数据

**实际结果**
获取结果为undefined

**系统信息:**
 - 发行平台: 支付宝小程序
 - 操作系统 windows10
 - HBuilderX版本 2.9.3
 - uni-app版本 
 - 设备信息 小程序开发者工具

**补充信息**
尝试过用原生支付宝小程序写这个代码片段，是可以正常获取到的，但是用uni-app编译后无法获取到

**Comment by xiaogao67** [comment]
@zhetengbiji

**Comment by zhenyuWang** [comment]
HBuilderX 3.7.3 测试符合预期，问题暂时关闭；
如后续依然有问题，可 reopen 该 issue。
