### ISSUE TITLE
fcm(谷歌推送、Firebase)配置后不能接收推送

### ISSUE THREAD

**Issue by 516821202** [dcloudio/uni-app#2327]
我按照https://ask.dcloud.net.cn/article/37356配置了，并且手机安装了谷歌服务与vpn，但是在firebase后台推送我却收不到信息。
手机是魅族x8，还有官网只写了配置，没有写使用方法！！！赶项目，请尽快回复！！！！

**Comment by liangxiwei** [comment]
大哥。。赶项目就付费啊
