### ISSUE TITLE
picker 组件 date  中设置start和end在微信小程序bug

### ISSUE THREAD

**Issue by dhlsoft** [dcloudio/uni-app#2331]
**问题描述**
picker设置为date模式，在开始时间为T+1，结束时间为T+365，当选择下一年的，月份不动，日期没刷新，显示当月全部日期，选择月份或者年份切换后，当月日期才刷新

**预期结果**
当时间限制在2020年12月08日-2021年12月8日时，应选不到2021年12月9日后的日期

**实际结果**
能选择到2021年12月31日之前的日期

**系统信息:**
 微信小程序有此问题，其他未发现

**补充信息**
选择年份的时候未判断日期是否应该刷新到截止日期之前

**Comment by dhlsoft** [comment]
这个应该是微信小程序的bug。。。确认一下吧

**Comment by zhetengbiji** [comment]
使用原生小程序工程测试一下如果仍然存在问题，需要把问题提及到微信小程序社区，并且附上代码片段
