### ISSUE TITLE
protobuf 小程序报错 而 H5可以运行

### ISSUE THREAD

**Issue by sdack-cloud** [dcloudio/uni-app#2333]
<img width="577" alt="QQ20201209-201515@2x" src="https://images.gitee.com/uploads/images/2020/1209/201608_63e19a80_1873176.png">

引入包
"google-protobuf": "3.14.0"

<img width="577" alt="QQ20201209-201515" src="https://images.gitee.com/uploads/images/2020/1209/202158_56d7af69_1873176.png">

H5 是可以使用，网络请求都没问题。只是小程序无法识别 proto 难道是语法兼容的的问题吗。

```
var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.xxx.xxx.Msg', null, global);
```
这个是生成protobuf 的 js文件 的头部

goog.exportSymbol() 

这句话应该是声明了 不清楚为什么报错

**Comment by HoujieHubei** [comment]
[微信小程序不支持protobuf](https://developers.weixin.qq.com/community/develop/doc/0c1e8e0253176ecf0b2212d8fb57ff21?highLine=protobuf)
![QQ截图20210610111601.png](https://p9-juejin.byteimg.com/tos-cn-i-k3u1fbpfcp/9ec0acd45c6d4030a2ed84b0ed9e08c2~tplv-k3u1fbpfcp-watermark.image)

**Comment by HoujieHubei** [comment]
[uniapp 微信小程序使用protobuf](https://juejin.cn/post/6965049311100928013)
