### ISSUE TITLE
如何实现不重新打包修改桌面图标

### ISSUE THREAD

**Issue by zcz147258** [dcloudio/uni-app#2336]
**新功能描述**
如何实现不重新打包动态修改桌面图标,
想要实现 热更新桌面图标的功能或者调用原生更新

**现状及问题**
业务需求。

**尝试方案**
native.js 有很多调用原生的方法,就是没有更换桌面图标的方法

**补充信息**
[其它你认为有参考价值的信息]

**Comment by Otto-J** [comment]
已实现
