### ISSUE TITLE
可以用weppack打包小程序?

### ISSUE THREAD

**Issue by aiplat** [dcloudio/uni-app#234]
**新功能描述**
需要weppack配置环境

**现状及问题**
多个小程序放在同一个仓库中,打包时需要weppack配置环境,官网未指出uniapp可不可以直接用weppack打包,兼容性如何

**尝试方案**
现在尝试webpack

**补充信息**
无

**Comment by aiplat** [comment]
看到cli了,现在是可以支持vue3.好吧,升级一下就好了.

**Comment by xiaoyucoding** [comment]
注意下不是 vue 3.x，而是 vue-cli 3.x，不要搞混咯。

**Comment by aiplat** [comment]
是的，我说的就是cli3
