### ISSUE TITLE
注册uni-ui组件的时候编译出错

### ISSUE THREAD

**Issue by fc200** [dcloudio/uni-app#2340]
我是用vscode命令行引入uni-ui组件的
我使用 npm install @dcloudio/uni-ui已经导包成功 可以看到依赖 
但是当我在注册组件的时候    components：{unibadge}  项目编译不通过
 提示:Syntax Error: Error: Can't resolve '@dcloudio/uni-ui/lib/unibadge/unibadge' in 'D:\UniAppCode\dnpicture\src\pages\home'

vue cli  4.5.9

**Comment by bfc846958672** [comment]
目前测试无此问题， uniapp 在package.json的版本为2.0.2-4020420240722003。 请参考uni-ui文档进行安装。[文档地址](https://uniapp.dcloud.net.cn/component/uniui/quickstart.html)。
