### ISSUE TITLE
使用有赞小程序组件的小程序编译成H5后报Unclosed bracket

### ISSUE THREAD

**Issue by hanfengcan** [dcloudio/uni-app#2341]
**问题描述**
如题目所说的那样。原工程从mpvue转换成uni，早期的时候使用了vant的小程序组件。现在因为需求变更需要发布公众号应用。发现编译H5的时候会报错。
![image](https://user-images.githubusercontent.com/4559753/102002669-9b211980-3d39-11eb-95da-b470b389830a.png)

**系统信息:**
 - 发行平台: H5
 - uni-app版本
uni-app v2.8.11
uni-app cli v2.0.0-28920200907001

**补充信息**
解决方法很简单，只要把两个逗号换行就可以了。
![image](https://user-images.githubusercontent.com/4559753/102002745-acb6f100-3d3a-11eb-8808-78516f6b1699.png)
但是，每次执行npm run dev:h5的时候都会出现同样的问题， 需要重新换行

**Comment by 66lizhenhua66** [comment]
更改 wxcomponents/icon/index.wxss 文件即可，每次执行npm run dev:h5就不会有这个问题了

**Comment by hanfengcan** [comment]
> 更改 wxcomponents/icon/index.wxss 文件即可，每次执行npm run dev:h5就不会有这个问题了

对, 最后我发现改源文件就好
