### ISSUE TITLE
js正则replace问题

### ISSUE THREAD

**Issue by Nick091608** [dcloudio/uni-app#2347]
**问题描述**
在uni-app微信小程序中使用replace替换字符串为空无效，必须改成replace(/正则/, ' ')才可以，但是页面却把空格显示出来了

**复现步骤**
[复现问题的步骤]
let value = e.detail.replace(/[^\d.]/g, '');  // 替换飞数字和小数点无效
this.$nextTick(()=>{
	this.$set(this.sku[e.target.dataset.index], 'retail_price', value);
	this.$forceUpdate();
})

**预期结果**
let value = e.detail.replace(/[^\d.]/g, ''); 
使用这个应该可以把非数字和小数点替换成空，界面不显示空格
![image](https://user-images.githubusercontent.com/33303511/102307359-45e64180-3f9f-11eb-8648-17f9aad34c17.png)

**实际结果**
let value = e.detail.replace(/[^\d.]/g, ''); 
使用这个正则没有把非数字和小数点替换成空，界面显示完全无效
![image](https://user-images.githubusercontent.com/33303511/102307302-2cdd9080-3f9f-11eb-971c-7bc5e290caea.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统:  iOS 14
 - HBuilderX版本: 2.8.13.20200927
 - 设备信息: iPhone11 iPhonexr

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
应该和uni-app无关，你再仔细验证一下

**Comment by Nick091608** [comment]
> 应该和uni-app无关，你再仔细验证一下

我验证一天了，这个正则放到其他不是uni-app的项目里就很正常，在uni-app怎么都不管用

**Comment by zhetengbiji** [comment]
打印以下内容：
* 替换前的字符串
* 替换使用到的正则
* 替换后的字符串

**Comment by Nick091608** [comment]
控制台打印的是值是对的，不带空格纯数字小数点，但是页面显示是包含空格的

**Comment by zhetengbiji** [comment]
> 控制台打印的是值是对的，不带空格纯数字小数点，但是页面显示是包含空格的

那应该和正则没有关系，替换成其他的固定值测试是否有效

**Comment by Nick091608** [comment]
写死一个字符串执行这个正则打印出来的值也是只保留数字和小数点，但是页面显示也是带空格

**Comment by zhetengbiji** [comment]
> 写死一个字符串执行这个正则打印出来的值也是只保留数字和小数点，但是页面显示也是带空格

不执行这个正则，先不管正则，测试直接替换input的值为固定值

**Comment by Nick091608** [comment]
![image](https://user-images.githubusercontent.com/33303511/102318252-ffe7a880-3fb3-11eb-8339-30fbadf2bb94.png)
我怀疑是不是不能双向绑定导致的，输入框怎么变，下面都不变

**Comment by zhetengbiji** [comment]
> ![image](https://user-images.githubusercontent.com/33303511/102318252-ffe7a880-3fb3-11eb-8339-30fbadf2bb94.png)
> 我怀疑是不是不能双向绑定导致的，输入框怎么变，下面都不变

当前 input 使用了 v-model 吗？

**Comment by Nick091608** [comment]
uni-app用不了v-model，直接报错，只能用v-bind
![image](https://user-images.githubusercontent.com/33303511/102319256-8d77c800-3fb5-11eb-9e28-1eed9ca6ca80.png)

**Comment by zhetengbiji** [comment]
> uni-app用不了v-model，直接报错，只能用v-bind
> ![image](https://user-images.githubusercontent.com/33303511/102319256-8d77c800-3fb5-11eb-9e28-1eed9ca6ca80.png)

哦，我一直以为你用的input，原来不是input，input可以使用v-model

你试试延迟赋值，甚至用一个按钮点击后重新赋值是否生效

**Comment by Nick091608** [comment]
this.$nextTick(()=>{
this.$set(this.sku[e.target.dataset.index], 'retail_price', value);
this.$forceUpdate();
})
我这个就是啊

**Comment by zhetengbiji** [comment]
> this.$nextTick(()=>{
> this.$set(this.sku[e.target.dataset.index], 'retail_price', value);
> this.$forceUpdate();
> })
> 我这个就是啊

增加更多更久更大的延迟试试

**Comment by Nick091608** [comment]
setTimeout 2秒都不行

**Comment by yuconora** [comment]
这个不是正则的问题吧
看你图片上用的似乎是Vant 这个UI库 看源码里面 van-field 渲染使用的是 data 里面的 innerValue 这个属性 而非 props 里面的 value
```js
    created: function () {
        this.value = this.data.value;
        this.setData({ innerValue: this.value });
    },
```
```html
<input value="{{ innerValue }}" .... />
```
input type="number" 这个属性在微信小程序中 **真机**调试的情况下 是不会出现空格和英文字符包括小数点
![WechatIMG25](https://user-images.githubusercontent.com/14029094/102568148-e82c3380-411d-11eb-94d7-500c4d94cedb.jpeg)

不使用数字键盘 实现方式参考如下：
```vue
<template>
	<view class="container">
		<view class="test" v-for="(item, index) in sku" :key="index">
			<van-field
			type="number" 
			ref="input" 
			:value="item.retail_price" 
			:data-index="index" 
			@input="changeSkuIput" />
			<view>
				{{item.retail_price}}
			</view>
		</view>
	</view>
</template>
<script>
	
	export default {
		data() {
			return {
				sku: [{ retail_price: 0}]
			}
		},
		methods: {
			changeSkuIput(e) {
				const value = e.detail.replace(/[^\d.]/g, ''); // 替换飞数字和小数点无效
				this.$set(this.sku[e.target.dataset.index], 'retail_price', value);
				const ref = this.$refs.input
				ref[e.target.dataset.index].setData &&
					ref[e.target.dataset.index].setData({
						innerValue: value
					})
				
			}
		}
	}
</script>
```

**Comment by leon2017** [comment]
我在IOS也遇到了 ，请问解决了吗
