### ISSUE TITLE
HBuilder X 创建的项目，怎么查看当前uniapp版本号

### ISSUE THREAD

**Issue by 1226362423** [dcloudio/uni-app#2351]
不知道怎么查看当前uniapp的版本号，更新huilderx就相当于更新uniapp吗？还是uniapp可以另外下载更新？没有做区分吗

**Comment by 1226362423** [comment]
HBuilder X版本号就是uniapp的版本号吗，两者有什么区别

**Comment by zhetengbiji** [comment]
是的
