### ISSUE TITLE
uni.uploadFile 上传多文件的相关问题

### ISSUE THREAD

**Issue by 1226362423** [dcloudio/uni-app#2352]
**问题描述**
app 使用 uni.uploadFile 上传多文件 服务端只能接收得到一条数据 h5用相同代码没有问题

**预期结果**
可以上传多张图片

**实际结果**
`uni.uploadFile({
					url:baseUrl + "app/task/createTask",
					files:this.files,
					fileType:"image",
					formData:{
						taskName: this.name,
						type: this.eventId,
						content: this.content,
						usertokencode: userToken,
						level: this.levelId,
						longitude: this.longitude,
						latitude: this.latitude,
						address: this.address,
						tributary: this.tributary,
					},
					success:(uploadFileRes)=>{
						uni.hideLoading();
						console.log("uploadFileRes:"+uploadFileRes.data);
						console.log("statusCode:"+uploadFileRes.statusCode);
						if (uploadFileRes.statusCode == 200) {
							var data=JSON.parse(uploadFileRes.data);
							if (data.code == 0) {
								uni.showModal({
									content: "提交成功",
									showCancel: false,
									success:function(res){
										if(res.confirm){
											uni.navigateBack({
												delta:1,
											})
										}
									}
								})
							} else {
								uni.showModal({
									content: "提交失败:"+data.msg,
									showCancel: false,
								})
							}
						} else {
							uni.showModal({
								content: "提交失败",
								showCancel: false,
							})
						}
					},
				});
			},`

**系统信息:**
 - 发行平台: [app]
 - 操作系统 [如 android]
 - HBuilderX版本 [2.9.8]
 - uni-app版本 [编辑器创建的项目 不知道在哪里看]
 - 设备信息 [如 Android]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
你的files是什么

你可以先仔细对照文档排查一下这块

**Comment by 1226362423** [comment]
for (var i = 0; i < fileList.length; i++) {
						var url=fileList[i].url;
						this.files.push({
							name:"file",
							uri:url,
						});
						console.log("uri:"+url);
}

**Comment by 1226362423** [comment]
还是不行的 移动端app上传文件还是只能传一张图片到服务端 你们测试一下吧 确实会存在这个bug的 服务端的接收name就只能用file，参数名称就叫file 用其他名称会导致服务端接收不到数据

**Comment by fengh16** [comment]
我也遇到了多图上传的问题。我测试的时候代码如下：

```
      let filesPayload = this.imageFiles
        .filter(f => typeof f?.path === 'string' && f.path.length > 0)
        .map((f, idx) => ({
          name: `pictures`,   // 每张图片都是一样的name
          uri: f.path
        }));
```

之后

```
        const task = uni.uploadFile({
          url: `${BASE_URL}/uploadpics/`,
          files: filesPayload,
          formData,
          success: (uploadRes) => {
```

上传多张图片时，在django后端通过`request.FILES.getlist`只能收到最后一张图片。
