### ISSUE TITLE
nuve页面使用map,有个方法,获取当前地理信息,绘制路线,会出现闪退现象

### ISSUE THREAD

**Issue by make-dream** [dcloudio/uni-app#2353]
使用map组件
<map
			class="map"
			show-location="true"
			:style="{ height: patroling ? '60%' : '100%' }"
			:latitude="latitude"
			:longitude="longitude"
			:markers="covers"
			:polyline="polyline"
			:controls="controls"
			:scale="scale"
			id="myMap" 
			ref="myMap"
			@controltap="clickControltap" 
			
		></map>

> 
调用函数方法 
var _self = this
this.mission1 = setInterval(() => {
							uni.getLocation({
								type: 'gcj02', //返回可以用于uni.openLocation的经纬度
								success: res => {
									// const [longitude, latitude] = [this.longitude, this.latitude];
									const longitude = res.longitude
									const latitude = res.latitude
									_self.longitude = res.longitude
									_self.latitude = res.latitude

									_self.covers[0].latitude = latitude;
									_self.covers[0].longitude = longitude;

									let jwAreaBoolean = IsPtInPoly(longitude, latitude, _self.jwAreaMap);
									// console.log(jwAreaBoolean)
									if (true) {
										// 计算两个坐标之间的距离
										// if (this.oldLocation_GPS.longitude != longitude && this.oldLocation_GPS.latitude != latitude) {
										if (_self.oldLocation_GPS.longitude != longitude || _self.oldLocation_GPS.latitude != latitude) {
											//坐标相同不增加距离
											let point1 = new plus.maps.Point(_self.oldLocation_GPS.longitude, _self.oldLocation_GPS.latitude); //起点
											let point2 = new plus.maps.Point(longitude, latitude); // 终点 (一段距离)
											let that = _self,
												riverResult = 0;
											//计算前后两个坐标之间的距离
											plus.maps.Map.calculateDistance(
												point1,
												point2,
												function(event) {
													// console.log(event)
													let distance = event.distance.toFixed(1); // 转换后的距离值
													riverResult = Number(_self.distance) + Number(distance);
													_self.distance = riverResult.toFixed(1);
													// console.log(_self.distance)
												},
												function(e) {
													console.log('计算位置信息失败Failed:' + JSON.stringify(e));
												}
											);
										}
									}
									//计算旧的坐标为之前的坐标
									_self.oldLocation_GPS.longitude = longitude;
									_self.oldLocation_GPS.latitude = latitude;
									_self.trail.push({
										longitude: _self.longitude,
										latitude: _self.latitude
									});
									// _self.points.push({
									// 	longitude,
									// 	latitude
									// });
									console.log('我现在距离崩溃多久....')
									console.log(_self.trail)
									console.log(_self.trail.length)
									console.log('我要崩溃了......')
								}
							});
						}, 1);

trail数组长度超过120,会出现闪退现象
trail=[{
	"longitude": 116.350207,
	"latitude": 39.976357
}, {
	"longitude": 116.350207,
	"latitude": 39.976357
}]

**Comment by ArrayDC** [comment]
请按反馈问题模板详细说明复现问题的环境。
