### ISSUE TITLE
uni.uploadFile 微信小程序 开发环境下正常,真机中不正常

### ISSUE THREAD

**Issue by zcdnsz** [dcloudio/uni-app#2357]
**问题描述**
微信小程序用这个在开发环境下一切正常,整机中不正常

**补充信息**
我排查了下,可能是由于微信小程序前段时间更新了引起的
选择图片后的临时文件 在开发环境下以temp:// 开头 真机中wxfile://开头 可能是这里导致的,
1:我在真机上打开调试模式也正常,关闭调试不正常
2:把uni.uploadFile改为 wx.uploadFile 后正常,
虽然我的项目只在小程序下运行,这样可以解决问题,但是我也报告给官方,希望官方修复下,给其他人以方便吧

**Comment by qiudaoermu** [comment]
1.配置 uploadfile 域名
2.删除小程序，重新进
