### ISSUE TITLE
Canvas画布，不设定type="2d"时可以正常绘画，否则什么都画不出来

### ISSUE THREAD

**Issue by hajtjh** [dcloudio/uni-app#2359]
**问题描述**
Canvas画布，未使用type="2d"时可以正常绘画，但只要增加上这个属性，原有绘画代码均画不出来东西。

**复现步骤**
不增加type="2d"一切正常
`<canvas  canvas-id="vinCanvas" id="vinCanvas" style="width:100vw;height:100vh;" :disable-scroll="true" class="canvas-wrap"></canvas>`

增加完type="2d"之后，什么都不显示，其它代码不变
`<canvas type="2d" canvas-id="vinCanvas" id="vinCanvas" style="width:100vw;height:100vh;" :disable-scroll="true" class="canvas-wrap"></canvas>`

**系统信息:**
 - 发行平台: 微信小程序

**Comment by zhetengbiji** [comment]
不实用uni-app测试是否仍然存在问题，如果存在需报告到微信小程序社区

**Comment by tangzhenming** [comment]
> 不实用uni-app测试是否仍然存在问题，如果存在需报告到微信小程序社区

原生微信小程序没问题，uniapp 增加 2d type 后同楼主不显示绘制图层。

**Comment by Elvira-Ho** [comment]
顶一下 这个问题  我也遇到了 canvas渲染失败
`Cannot read property 'node' of null`

**Comment by hhcol620** [comment]
这个问题有方案解决了嘛

**Comment by Doctor-DC** [comment]
type="2d"是新版canvas，还需要调整id、生成方式等地方

https://developers.weixin.qq.com/miniprogram/dev/framework/ability/canvas-legacy-migration.html

**Comment by zss823158062** [comment]
我也遇到了同样的问题；是不是uniapp编译成微信小程序的时候没适配好呢

**Comment by Otto-J** [comment]
感谢反馈，这是微信新版和旧版 canvas 切换带来的影响。目前首先在文档中进行补充和提示，后续横向对比各家 canvas 组件后给出最终结论。关联 ask 社区问题 https://ask.dcloud.net.cn/question/182711
可以关注此 issues ，有进展我会进行更新。
