### ISSUE TITLE
第一个页面是nvue时，没有全局配置文件问题

### ISSUE THREAD

**Issue by LWD8** [dcloudio/uni-app#236]
![image](https://user-images.githubusercontent.com/28432674/54180376-70f05700-44d6-11e9-89c5-e3598e61458e.png)

默认页面是nvue，不能进行锁定屏幕方向。导致一进来如果是横屏。样式就会错乱问题

**Comment by hulinNeil** [comment]
目前nvue的页面手动切换横竖屏，会导致px重新计算，导致出现你这样的问题，所以有nvue的页面建议锁定手机方向。
![image](https://user-images.githubusercontent.com/24296884/54337086-c52b4080-4668-11e9-8030-51429b4136fb.png)
