### ISSUE TITLE
app 调用uploadFile上传多张图片的问题

### ISSUE THREAD

**Issue by 1226362423** [dcloudio/uni-app#2362]
手机平台为android 红米手机 Android10的系统
app调用uploadfile上传多张图片，实际只传最后一张图片到服务端。files参数里面代码如下：

 ```
for (var i = 0; i < fileList.length; i++) {
						var url=fileList[i].url;
						this.files.push({
							name:"file",
							uri:url,
						});
						console.log("uri:"+url);
					}

```

name ：我这里name是传的一样的，都为file，因为服务端接收的参数就叫file，填别的会导致服务端接收不到参数，那就为空。
文档里面描述的：如果 name 不填或填的值相同，可能导致服务端读取文件时只能读取到一个文件，（但是h5端调试，并不存在这个问题，只有app有这个问题）那么现在我这个name该怎么传？
该问题已经存在15天未解决，请求官方给予技术支持。

**Comment by 1226362423** [comment]
例子里面也是上传单张图片的例子 没有上传多张图片的例子 ，请问可以给一份上传多张图片的例子吗

**Comment by zhetengbiji** [comment]
栗子来喽：https://github.com/dcloudio/hello-uniapp/blob/73487c5751168ef67e34c36382a7543b8128e8bb/platforms/app-plus/feedback/feedback.vue

**Comment by zhetengbiji** [comment]
另外你说的同样的代码在h5可用在app不可用，有没有测试一下iOS是否可用

**Comment by 1226362423** [comment]
> 另外你说的同样的代码在h5可用在app不可用，有没有测试一下iOS是否可用

ios也是不可用的 ，这个问题好像是服务端的问题吧？服务端的接口设计就是如果多张图片 他就是要传多个file参数，参数名就必须叫file，那如果我按照例子来，name为file0 file1服务端就接收不到，这个服务端要怎么去设计接口啊，你们这个例子的后台接口是怎么设计的，整体的逻辑是怎么样的

**Comment by 1226362423** [comment]
移动端有没有内置抓包的工具

**Comment by zhetengbiji** [comment]
> 移动端有没有内置抓包的工具

移动端的抓包工具我也没百度过，用PC端的设置代理即可，比如： Charles、Fiddler

**Comment by zhetengbiji** [comment]
> > 另外你说的同样的代码在h5可用在app不可用，有没有测试一下iOS是否可用
> 
> ios也是不可用的 ，这个问题好像是服务端的问题吧？服务端的接口设计就是如果多张图片 他就是要传多个file参数，参数名就必须叫file，那如果我按照例子来，name为file0 file1服务端就接收不到，这个服务端要怎么去设计接口啊，你们这个例子的后台接口是怎么设计的，整体的逻辑是怎么样的

https://github.com/dcloudio/H5P.Server/blob/master/uploader/index.php

**Comment by 1226362423** [comment]
服务端改了接口接收方式解决了这个问题，可能需要官方解释一下uploadfile方法原理 为什么files里面的name相同为什么会被覆盖，非要给name加个下标 ，就是因为加了这个下标导致服务端接收不到，不是很懂这个files参数其中原理。

**Comment by lalalsls** [comment]
![image](https://user-images.githubusercontent.com/31378186/112108579-5b48b880-8beb-11eb-924f-291616ea5955.png)
官方源码在这里 安卓Q 好像因为获知不到文件原名 所以直接怼了表单名称进入那个addFile 方法了 addFile 方法会按key参数做去重

**Comment by OuIChien** [comment]
> ![image](https://user-images.githubusercontent.com/31378186/112108579-5b48b880-8beb-11eb-924f-291616ea5955.png) 官方源码在这里 安卓Q 好像因为获知不到文件原名 所以直接怼了表单名称进入那个addFile 方法了 addFile 方法会按key参数做去重

您好，请问这个源文件是在哪里？

**Comment by lalalsls** [comment]
> > ![image](https://user-images.githubusercontent.com/31378186/112108579-5b48b880-8beb-11eb-924f-291616ea5955.png) 官方源码在这里 安卓Q 好像因为获知不到文件原名 所以直接怼了表单名称进入那个addFile 方法了 addFile 方法会按key参数做去重
> 
> 您好，请问这个源文件是在哪里？

他好像已经修正这个问题了  现在可以传同名文件了 源码也被改过了  可以用github的搜索定位到这段代码

**Comment by lalalsls** [comment]
> > 服务端改了接口接收方式解决了这个问题，可能需要官方解释一下uploadfile方法原理 为什么files里面的file对象的name相同为什么会被覆盖，而且是前端直接覆盖掉了，非要给name加个下标或者不同 ，就是因为加了这个下标导致服务端接收不到，不是很懂这个相同就覆盖的原理。最后还是这句提示：“如果 name 不填或填的值相同，可能导致服务端读取文件时只能读取到一个文件。”。为什么会造成这个问题？其中原因原理是什么？这个可能有必要说明一下，新手可能不是很明白，特别是涉及前后端合作的，会浪费很多时间在这个上面 @zhetengbiji
> 
> 请问这个问题是怎么解决的？我现在安卓调用接口也遇到了相同的问题

我当时是直接前端给每个文件加标号 然后后台接收的时候处理了一下 不清楚他是否修改了这个bug
