### ISSUE TITLE
怎么才能让某个配置文件单独不编译进项目里

### ISSUE THREAD

**Issue by idxiu** [dcloudio/uni-app#2364]
**问题描述**
[问题描述：怎么才能让某个配置文件单独不编译进项目里

 [或者可以直接贴源代码]
**预期结果**
![image](https://user-images.githubusercontent.com/12675437/102845854-77e91f00-4449-11eb-9ab3-9217b05cbde7.png)

[使用简洁清晰的语言描述你希望生效的预期结果]
直接改这里配置文件就行，不用每次改了再build 才生效。

**实际结果**
 改了不生效，尝试过放在static文件夹里边修改也没起作用

**系统信息:**
 - 发行平台: H5平台

**Comment by zhetengbiji** [comment]
一个简单的方案：在模板html内引入，使用全局变量
