### ISSUE TITLE
关于调用异步的api的问题

### ISSUE THREAD

**Issue by bzqadmin** [dcloudio/uni-app#2366]
我现在遇到了一个这样的问题，我想通过uni.chooseImage()和uni.uploadFile()来上传图片，官方说uni-app的异步接口在不传入success fail complete等回调的时候，返回的就是一个promise,我觉得这样挺好，然后我就可以用Promise.all()来发起真正的上传，但是现在的问题，按照官方的方法返回的不是promise，而是执行的最终结果，也就是上传成功后返回的数据（我上传到七牛），我希望的是，在我点击上传按钮的时候，再上传，而不是直接上传。不知道有没有人遇到过这个问题。

**Comment by bzqadmin** [comment]
自问自答一下，我现在自己的解决办法是把uni.uploadFiles 换成wx.uploadFiles,然后对其promise化，不知别人有没有更好的解决方案

**Comment by StrivingRabbit** [comment]
可以查看 [API Promise 化](https://uniapp.dcloud.io/api/README?id=api-promise-%e5%8c%96) 来做相应的修改
