### ISSUE TITLE
easycom方式使用vant-weapp微信小程序编译报错

### ISSUE THREAD

**Issue by ifelseZ** [dcloudio/uni-app#2369]
**问题描述**
uniapp中使用vant-weapp（最新版） 使用easycom方式引用h5端运行可以，但是微信小程序编译报错，只能采用usingComponents的方式，才不报错

**复现步骤**
看此链接
https://blog.csdn.net/zdq357104345/article/details/111656549

**预期结果**
对vant-weapp的引用可以采用easycom的方式，成功编译微信小程序

**实际结果**
![image](https://user-images.githubusercontent.com/74172838/103095127-76327d80-463a-11eb-9acb-6c63d22af90d.png)

**系统信息:**
 - 发行平台:  微信小程序
 - 操作系统:mac
 - HBuilderX版本:2.9.8
 - uni-app版本：最新

**补充信息**
easycom的问题

**Comment by Jamesnakes** [comment]
你好，这个问题解决了么？
