### ISSUE TITLE
touch 事件的监听，在pc端正常,app端无法触发

### ISSUE THREAD

**Issue by oujin-nb** [dcloudio/uni-app#237]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
touch事件正常触发

**实际结果**
touch 事件的监听，在pc端正常,app端（安卓）无法触发

**补充信息**
[可选]
我看了下外部的包裹容器height:100%会不会是这个原因导致移动端无法正常监听

**Comment by aiplat** [comment]
用小程序的bindtouchstart方法

**Comment by oujin-nb** [comment]
> 用小程序的bindtouchstart方法

可是我是用来开发app的

**Comment by zhetengbiji** [comment]
请补充问题详细信息

**Comment by oujin-nb** [comment]
> 请补充问题详细信息

移动端无法触发touch事件

**Comment by hbcui1984** [comment]
> > 请补充问题详细信息
> 
> 移动端无法触发touch事件

需补充完整示例，比如在什么组件上监听、HBuilderX版本号（或cli版本号）等

**Comment by zxzhgk** [comment]
APP 也是跟小程序一样的检测，只有H5是检测touch

**Comment by oujin-nb** [comment]
我是用了一个第三方库  http://npm.taobao.org/package/kim-vue-touch/v/1.1.1 监听touch事件，h5是没有问题的，但是移动端不行

**Comment by hbcui1984** [comment]
> 我是用了一个第三方库 http://npm.taobao.org/package/kim-vue-touch/v/1.1.1 监听touch事件，h5是没有问题的，但是移动端不行

需要确保该三方库没有使用window对象或dom操作，否则在App端、微信端均不支持。
