### ISSUE TITLE
请支持百度小程序onInit生命周期

### ISSUE THREAD

**Issue by mirror29** [dcloudio/uni-app#2372]
**新功能描述**
请支持百度小程序onInit生命周期

**现状及问题**
目前百度方面已支持Component构造onInit，但使用uni-app编译后无法仍调用该生命周期
相关文档：[https://smartprogram.baidu.com/forum/topic/show/126571](https://smartprogram.baidu.com/forum/topic/show/126571)

**Comment by zhetengbiji** [comment]
#2197

**Comment by zhetengbiji** [comment]
HBuilderX 3.1.0 alpha 已支持
