### ISSUE TITLE
uni.chooseImage(OBJECT)可以增加选择前后置摄像头选项

### ISSUE THREAD

**Issue by selway** [dcloudio/uni-app#2373]
**新功能描述**
uni.chooseImage(OBJECT)可以增加选择前后置摄像头选项

**现状及问题**
H5模式没其它其它选择前后置摄像头选项解决方案，导致在默认需要前置镜头的场景使用很不方便；

**尝试方案**
看过其它方法（相机组件相关方法），但是都不支持H5模式；

**补充信息**
可以完善H5场景的图片解决方案。

**Comment by zhetengbiji** [comment]
好像目前浏览器还没有支持的
