### ISSUE TITLE
ask 社区账号登录问题

### ISSUE THREAD

**Issue by SilurianYang** [dcloudio/uni-app#2376]
**问题描述**

### 无法登录账号，QQ浏览器、google浏览器都试过了。并且缓存全清了。依旧还是不行、 看下面视频

https://user-images.githubusercontent.com/31280665/103165796-0a792c00-4857-11eb-84f8-0abcc45b554e.mp4

**预期结果**

### 能正常登录

**实际结果**
### 不能正常登录

**系统信息:**
网页  https://ask.dcloud.net.cn/explore

**补充信息**
这个号在 `HBuilderX ` 中是可以登录。很久没登录社区了突然想着登录下结果发现不行

**Comment by zhetengbiji** [comment]
具体账号私信社区管理帮你查询

**Comment by philshi** [comment]
请提供下账户邮箱发送到service@dcloud.io，这边排查下具体原因。

**Comment by SilurianYang** [comment]
已经提供 麻烦帮忙排查下

**Comment by SilurianYang** [comment]
官方已处理
