### ISSUE TITLE
vue@3 + typescript 创建的运行无法运行

### ISSUE THREAD

**Issue by huangchj** [dcloudio/uni-app#2379]
创建项目后npm run serve控制台warning
 warning  in ./src/main.ts

"export 'createApp' was not found in 'vue'

 warning  in ./src/App.vue?vue&type=script&lang=ts&

"export 'defineComponent' was not found in 'vue'

浏览器起控制台报错
Uncaught TypeError: Object(...) is not a function
    at eval (App.vue?vue&type=script&lang=ts&:5)

这是怎么回事

**Comment by fxy060608** [comment]
仅支持小程序平台

**Comment by li1234yun** [comment]
> 仅支持小程序平台

请问何时正式全平台支持Vue3呢？现在Vue3已经发布很长时间了，大家可能需要使用新版本进行开发。

**Comment by yangdan8** [comment]
现在已经可以开始用vue3开发全平台了吗？
