### ISSUE TITLE
picker 组件关闭后，再次打开，不是读取的value里的值，选中值始终是第一项

### ISSUE THREAD

**Issue by chenwen992003** [dcloudio/uni-app#238]
第一次打开选中2020年4月7日，关闭后，再次打开时，选中值一直都是2014年1月1日
![微信图片_20190315104930](https://user-images.githubusercontent.com/48112634/54405531-df6d2900-4711-11e9-866c-313dde93baa6.png)

**Comment by dcloudhdx** [comment]
HBuilderX自带模板Hello uni-app 内置组件>表单>Input 是没有问题的, 请检查代码或拷贝示例代码到你的项目中测试
