### ISSUE TITLE
小程序样式穿透无效

### ISSUE THREAD

**Issue by Rainsheep** [dcloudio/uni-app#2380]
**问题描述**
小程序使用/deep/ 穿透无效，父组件怎么控制子组件样式
css 语言为 scss

**Comment by Rainsheep** [comment]
已经解决
https://www.rainsheep.cn/articles/2020/12/29/1609240734107.html

**Comment by yiqianglin** [comment]
> 已经解决
> https://www.rainsheep.cn/articles/2020/12/29/1609240734107.html

如果子组件有自己的样式（scoped；父组件也有对子组件样式（scoped）；按楼主这里的方案；是没办法做到页面样式最优先的；请问这里怎么解决呢
