### ISSUE TITLE
使用基于类的 Vue 组件来做页面时，onLoad函数不回调

### ISSUE THREAD

**Issue by CrazyHuiLiang** [dcloudio/uni-app#239]
**问题描述**
使用下面代码跳转页面
```
uni.navigateTo({
    url: `/pages/SendMoney/SendMoney?userId=${data.id}`
});
```
在新页面中使用下面代码可以有打印出**onLoad called**
```
<script lang="ts">
	export default {
		onLoad: function(option: any) {
			console.log('onLoad called');
		}
	}
</script>
```

如果使用下面这种基于类的写法，onLoad就不回调了。
```
<script lang="ts">
	import {
		Component,
		Vue
	} from 'vue-property-decorator';
	@Component({
		components: {}
	})
	export default class SendMoney extends Vue {
		onLoad(option: any) {
			console.log('onLoad called');
		}
	}
</script>
```

**预期结果**
两种写法应该是等价的，都应该有打印。

**实际结果**
基于类的写法没有回调

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 mac 10.14.3 ,chrome
 - HBuilderX版本: 1.7.0

**Comment by SilasDong** [comment]
刚使用，也遇到一样的问题，有打算解决吗

**Comment by CrazyHuiLiang** [comment]
vue3将推基于函数的写法，这个问题也没有反馈，就不纠结class的支持了

**Comment by zhetengbiji** [comment]
> 刚使用，也遇到一样的问题，有打算解决吗

本来非 Vue 内置的钩子函数需要调用接口注册，例如：``Component.registerHooks('onLoad')``

不过新版已经可以不用注册了，执行 ``npm update`` 更新即可。
