### ISSUE TITLE
npm版本没有publish？

### ISSUE THREAD

**Issue by yuconora** [dcloudio/uni-app#2398]
npm 搜索 @dcloudio 出来的最新版本号 是 2.0.0-29820201110001 
[npm](https://www.npmjs.com/search?q=%40dcloudio)

github 上看 更新日志 已经是 3.0.4.20201231
[更新日志](https://github.com/dcloudio/uni-app/blob/master/docs/release.md)

管理员看到了更新一下 有个功能新版修复了需要使用到

**Comment by zhetengbiji** [comment]
已处理，之前npm上也有，只是在next上
