### ISSUE TITLE
能不能集成一个markdown的编辑器，最新的示例中有分析器了。

### ISSUE THREAD

**Issue by zengqingsong** [dcloudio/uni-app#24]
能不能集成一个markdown的编辑器，最新的示例中有分析器了。编辑器也是非常常用的。

**Comment by zengqingsong** [comment]
这个mavoneditor就不错，不知好不好集成进来
https://www.ctolib.com/mip/topics-114527.html

**Comment by wanganxp** [comment]
主要是dom操作去掉，改改就可以移植过来。但官方精力有限，欢迎大家一起完善，把这些三方优秀组件改造然后开源，我们会推荐给我们的开发者，在我们的hello uni-app示例集成并保留作者声明:)

**Comment by wanganxp** [comment]
最新版hello uni-app示例中已经有了
