### ISSUE TITLE
远端部署H5，页面空白

### ISSUE THREAD

**Issue by Whitiny** [dcloudio/uni-app#240]
**问题描述**
将项目打包成H5，部署到远端linux服务器，浏览器能访问到，但是页面显示空白。
开发人员工具上显示内容：

```
<body>
    <noscript>
        <strong>Please enable JavaScript to continue.</string>
    </noscript>
    <div id="app"></div>
</body>
```

用Nginx和单独的apache部署都会这样，但是用xampp部署却是正常的，这是什么bug？

**Comment by zhetengbiji** [comment]
非bug
部署路径和你配置路径不符
看注意是事项：http://ask.dcloud.net.cn/article/35232
