### ISSUE TITLE
宽屏适配指南中，文字是否有误？

### ISSUE THREAD

**Issue by dandan6002** [dcloudio/uni-app#2401]
**现状及问题**
”宽屏适配指南中“中，有段文字：
“目前做如下调整：leftWindow、rightWindow、topWindow 中有其一存在，则 tabBar 隐藏；不存在，则隐藏。”
是不是少个字呀

“目前做如下调整：leftWindow、rightWindow、topWindow 中有其一存在，则 tabBar 隐藏；不存在，则不隐藏。”

如果不是的话打扰啦哈哈

**Comment by Fasttian** [comment]
文档写错了，已修改，感谢指出

**Comment by dandan6002** [comment]
![image](https://user-images.githubusercontent.com/28375125/103741081-6c921800-5033-11eb-92a3-814ced5c2b5d.png)
清除缓存打开好像没变哦

**Comment by zhetengbiji** [comment]
> ![image](https://user-images.githubusercontent.com/28375125/103741081-6c921800-5033-11eb-92a3-814ced5c2b5d.png)
> 清除缓存打开好像没变哦

莫慌，CDN有一定缓存时间

**Comment by dandan6002** [comment]
哈哈哈，好，辛苦了
