### ISSUE TITLE
苹果打包，提示无法安装此app

### ISSUE THREAD

**Issue by lihua123569** [dcloudio/uni-app#2409]
**问题描述**
苹果打包后分发安装，提示无法安装此app，因为无法验证其完整性。

**复现步骤**
[复现问题的步骤]
1. hbuilderx 3.0.5，原生app-云打包
2. 蒲公英分发后，iphone手机安装
3. 安装完点击打开，提示“提示无法安装此app，因为无法验证其完整性。”

[或者可以直接贴源代码]

**预期结果**
预期可以直接打开用

**实际结果**
安装完点击打开，提示“提示无法安装此app，因为无法验证其完整性。”

**系统信息:**
 - 发行平台: ios
 - 操作系统： iOS 14.2
 - HBuilderX版本：3.0.5
 - uni-app版本 ：3.0.5
 - 设备信息 ：iphone7 plus

**补充信息**
ios证书没有过期

**Comment by csq0668** [comment]
用了正式证书打包了吧，要用测试证书哦

**Comment by doublenian** [comment]
遇到同样的问题，请问怎么解决啊

**Comment by doublenian** [comment]
> **问题描述**
> 苹果打包后分发安装，提示无法安装此app，因为无法验证其完整性。
> 
> **复现步骤**
> [复现问题的步骤]
> 
> 1. hbuilderx 3.0.5，原生app-云打包
> 2. 蒲公英分发后，iphone手机安装
> 3. 安装完点击打开，提示“提示无法安装此app，因为无法验证其完整性。”
> 
> [或者可以直接贴源代码]
> 
> **预期结果**
> 预期可以直接打开用
> 
> **实际结果**
> 安装完点击打开，提示“提示无法安装此app，因为无法验证其完整性。”
> 
> **系统信息:**
> 
> * 发行平台: ios
> * 操作系统： iOS 14.2
> * HBuilderX版本：3.0.5
> * uni-app版本 ：3.0.5
> * 设备信息 ：iphone7 plus
> 
> **补充信息**
> ios证书没有过期

我用ios 12 装就没问题，用ios14 就有问题

**Comment by huifukejian** [comment]
问题解决了吗,我也碰到了, 不知道自定义基座能不能分发

**Comment by zhetengbiji** [comment]
证书问题，分发平台上上应该会有详细的说明（说明哪种证书才可以）
