### ISSUE TITLE
支付宝小程序使用花呗分期插件，⽆法监听到插件提供的onChange事件，报错为事件信息不存在。

### ISSUE THREAD

**Issue by chendeng2017** [dcloudio/uni-app#2410]
**支付宝⼩程序使用花呗分期插件报：“事件信息不存在”**
1，支付宝官网花呗分期插件使用连接：https://opendocs.alipay.com/mini/introduce/antcreditpay-istallment

**按照社区的解决方法无效**
1，在 onLoad 中 添加如下代码，看看是否可以生效 this.$scope. onChange = this. onChange.bind(this) （没有效果）
     链接：https://ask.dcloud.net.cn/question/101302

⼩程序是使⽤uni.app进⾏开发的，通过查看编译产物和框架源码发现，uni⼩程序的事件是通过 dataset进⾏分发的。（详细代码⻅：https://github.com/dcloudio/uni- app/blob/67854ec3b733e72dfb5b123689412fe6ca0b0257/packages/uni-mp- alipay/dist/uni.mp.esm.js#L633）

**这⾥有简单的代码演示⼀下：**
` // 简化后的axml代码`
 `<credit-pay data-event-opts="{{[['^change',[['huebeiChange']]]]}}" onChange="__e" ></credit-pay>`

`1 function handleEvent(event) { `
`2 event = wrapper(event); `
`3 // [['tap',[['handle',[1,2,a]],['handle1',[1,2,a]]]]]` 
`4 const dataset = (event.currentTarget || event.target).dataset ;` 
`5 if (!dataset) {`
 `6 return console.warn('事件信息不存在'); `
`7 }`
 `8 const eventOpts = (dataset.eventOpts || `
`9 dataset['event-opts']); // ⽀付宝 web-view 组件 dataset ⾮驼 峰 `
`10 if (!eventOpts) { `
`11 return console.warn('事件信息不存在'); 1`
`12 } `
`13 // [['handle',[1,2,a]],['handle1',[1,2,a]]] `
`14 const eventType = event.type` 
`15 // .... `
`16 } `
`17`
`18 Page({ `
`19 __r: handleRef,`
 `20 __e: handleEvent, `
`21 __l: handleLink$1 `
`22 })`
- 通过代码⽇志调试发现，返回给uni使⽤的event对象，确实没有dataset对象，导致了报错

在分析⼀下这个axml的代码，会发现这个onChange其实只是⼀个的props，插件只是在某个阶段触发⼀ 下这个函数⽽已，所以这个data-event-opts根本不会被消费，所以上⾯才会报错，下⾯⽤⼀段伪代码解 释⼀下：

`//插件代码demo`
` <view`
 `data-a="a"`
 `onTap="change"`
`></view>`

`Component({`
`methods:{`
`change(e){`
`// 这⾥的e.target.dataset 肯定只会存在a属性`
`// ⽽不会有 event-opts`
`this.props.onChange({})`
`}`
`}`
`})`

- 通过查看相关插件的使⽤⽂档以及实际的⽇志输出证实了这⼀点:
- `onChange(extendParams)`：点击选择分期、增加购物⻋商品数量后分期额 度不⾜、减少购物⻋商品数量后分期可⽤、组件卸载 参数：`extendParams`，详⻅[⼩程序⽀付接⼊指引 -> 接⼊花呗分期说明 -> 接⼊花呗分期说明 -> 单通道模式]
-`demo：`
`onChange(extendParams) {`
`const { hb_fq_num, hb_fq_seller_percent } = extendParams`
`console.log(hb_fq_num, hb_fq_seller_percent);`
`// https://docs.alipay.com/mini/introduce/pay`
`},`

- 所以这是⼀个uni适配的问题，对于这种传⼊性事件函数，不应该⾛dataset的逻辑

**Comment by Yaob1990** [comment]
牛逼 ，life-follow 也存在这个问题

解决的话，可以考虑写小程序的原生组件（非 uni 组件，mycomponents 这个目录下的小程序原生自定义组件）

**Comment by zhetengbiji** [comment]
使用最新版，写 ``@change`` 试试

**Comment by Yaob1990** [comment]
> 使用最新版，写 `@change` 试试
> 
> 3.1.2
> 
> * 支付宝小程序平台 优化 组件支持 vue 事件监听方式（需启用 component2）[详情](https://ask.dcloud.net.cn/question/110978)

```
<life-follow
  a:if="{{show}}"
  sceneId="****"
  checkFollow="{{checkFollow}}"
  onCheckFollow="checkFollowCb"
  onClose="closeCb"
/>
```

life-follow 没有onchange 事件

**Comment by zhetengbiji** [comment]
> > 使用最新版，写 `@change` 试试
> > 3.1.2
> > 
> > * 支付宝小程序平台 优化 组件支持 vue 事件监听方式（需启用 component2）[详情](https://ask.dcloud.net.cn/question/110978)
> 
> ```
> <life-follow
>   a:if="{{show}}"
>   sceneId="****"
>   checkFollow="{{checkFollow}}"
>   onCheckFollow="checkFollowCb"
>   onClose="closeCb"
> />
> ```
> 
> life-follow 没有onchange 事件

哦，那就是 ``@checkFollow="checkFollowCB "`` ``@close="closeCb "``

**Comment by Yaob1990** [comment]
> > > 使用最新版，写 `@change` 试试
> > > 3.1.2
> > > 
> > > * 支付宝小程序平台 优化 组件支持 vue 事件监听方式（需启用 component2）[详情](https://ask.dcloud.net.cn/question/110978)
> > 
> > 
> > ```
> > <life-follow
> >   a:if="{{show}}"
> >   sceneId="****"
> >   checkFollow="{{checkFollow}}"
> >   onCheckFollow="checkFollowCb"
> >   onClose="closeCb"
> > />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > life-follow 没有onchange 事件
> 
> 哦，那就是 `@checkFollow="checkFollowCb"` `@close="closeCb "`

嗯嗯，这样编译出来大概是这样
```js
<life-follow
      vue-id="588c7fd8-1"
      sceneId=""
      checkFollow="{{checkLifeFlow}}"
      data-event-opts="{{[['^checkFollow',[['checkFollowCb']]],['close',[['closeCb']]]]}}"
      onCheckFollow="__e"
      onClose="__e"
      onVueInit="__l"
    ></life-follow>
```
添加 $event 参数之后
```
<life-follow
  a:if="{{show}}"
  sceneId="****"
  checkFollow="{{checkFollow}}"
  @checkFollow="checkFollowCb($event)"
  @close="closeCb($event)"
/>
```
编译之后：
```
<life-follow
      vue-id="588c7fd8-1"
      sceneId="***"
      checkFollow="{{checkLifeFlow}}"
      data-event-opts="{{[['^checkFollow',[['checkFollowCb',['$event']]]],['close',[['closeCb',['$event']]]]]}}"
      onCheckFollow="__e"
      onClose="__e"
      onVueInit="__l"
    ></life-follow>
```

为了区分自定义事件，uniapp, 添加 ^ 前缀，目前 uniapp 没有对 tag 进行区分，感觉这里需要对支付宝部分组件，做一下区分，部分组件不设为自定义事件。

**Comment by zhetengbiji** [comment]
> > > > 使用最新版，写 `@change` 试试
> > > > 3.1.2
> > > > 
> > > > * 支付宝小程序平台 优化 组件支持 vue 事件监听方式（需启用 component2）[详情](https://ask.dcloud.net.cn/question/110978)
> > > 
> > > 
> > > ```
> > > <life-follow
> > >   a:if="{{show}}"
> > >   sceneId="****"
> > >   checkFollow="{{checkFollow}}"
> > >   onCheckFollow="checkFollowCb"
> > >   onClose="closeCb"
> > > />
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > life-follow 没有onchange 事件
> > 
> > 
> > 哦，那就是 `@checkFollow="checkFollowCb"` `@close="closeCb "`
> 
> 嗯嗯，这样编译出来大概是这样
> 
> ```js
> <life-follow
>       vue-id="588c7fd8-1"
>       sceneId=""
>       checkFollow="{{checkLifeFlow}}"
>       data-event-opts="{{[['^checkFollow',[['checkFollowCb']]],['close',[['closeCb']]]]}}"
>       onCheckFollow="__e"
>       onClose="__e"
>       onVueInit="__l"
>     ></life-follow>
> ```
> 
> 添加 $event 参数之后
> 
> ```
> <life-follow
>   a:if="{{show}}"
>   sceneId="****"
>   checkFollow="{{checkFollow}}"
>   @checkFollow="checkFollowCb($event)"
>   @close="closeCb($event)"
> />
> ```
> 
> 编译之后：
> 
> ```
> <life-follow
>       vue-id="588c7fd8-1"
>       sceneId="***"
>       checkFollow="{{checkLifeFlow}}"
>       data-event-opts="{{[['^checkFollow',[['checkFollowCb',['$event']]]],['close',[['closeCb',['$event']]]]]}}"
>       onCheckFollow="__e"
>       onClose="__e"
>       onVueInit="__l"
>     ></life-follow>
> ```
> 
> 为了区分自定义事件，uniapp, 添加 ^ 前缀，目前 uniapp 没有对 tag 进行区分，感觉这里需要对支付宝部分组件，做一下区分，部分组件不设为自定义事件。

这是使用的什么版本编译的，看起来像是旧的，修复后（ be7e519ac669b3e06a41a0f33bb58e12b1dbdf7e ）编译的模板中存在标记 ``data-com-type="wx"``

**Comment by Yaob1990** [comment]
> > > > > 使用最新版，写 `@change` 试试
> > > > > 3.1.2
> > > > > 
> > > > > * 支付宝小程序平台 优化 组件支持 vue 事件监听方式（需启用 component2）[详情](https://ask.dcloud.net.cn/question/110978)
> > > > 
> > > > 
> > > > ```
> > > > <life-follow
> > > >   a:if="{{show}}"
> > > >   sceneId="****"
> > > >   checkFollow="{{checkFollow}}"
> > > >   onCheckFollow="checkFollowCb"
> > > >   onClose="closeCb"
> > > > />
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > life-follow 没有onchange 事件
> > > 
> > > 
> > > 哦，那就是 `@checkFollow="checkFollowCb"` `@close="closeCb "`
> > 
> > 
> > 嗯嗯，这样编译出来大概是这样
> > ```js
> > <life-follow
> >       vue-id="588c7fd8-1"
> >       sceneId=""
> >       checkFollow="{{checkLifeFlow}}"
> >       data-event-opts="{{[['^checkFollow',[['checkFollowCb']]],['close',[['closeCb']]]]}}"
> >       onCheckFollow="__e"
> >       onClose="__e"
> >       onVueInit="__l"
> >     ></life-follow>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 添加 $event 参数之后
> > ```
> > <life-follow
> >   a:if="{{show}}"
> >   sceneId="****"
> >   checkFollow="{{checkFollow}}"
> >   @checkFollow="checkFollowCb($event)"
> >   @close="closeCb($event)"
> > />
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 编译之后：
> > ```
> > <life-follow
> >       vue-id="588c7fd8-1"
> >       sceneId="***"
> >       checkFollow="{{checkLifeFlow}}"
> >       data-event-opts="{{[['^checkFollow',[['checkFollowCb',['$event']]]],['close',[['closeCb',['$event']]]]]}}"
> >       onCheckFollow="__e"
> >       onClose="__e"
> >       onVueInit="__l"
> >     ></life-follow>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 为了区分自定义事件，uniapp, 添加 ^ 前缀，目前 uniapp 没有对 tag 进行区分，感觉这里需要对支付宝部分组件，做一下区分，部分组件不设为自定义事件。
> 
> 这是使用的什么版本编译的，看起来像是旧的，修复后（ [be7e519](https://github.com/dcloudio/uni-app/commit/be7e519ac669b3e06a41a0f33bb58e12b1dbdf7e) ）编译的模板中存在标记 `data-com-type="wx"`

是这个版本：2.0.0-31920210609001

**Comment by zhetengbiji** [comment]
> > > > > > 使用最新版，写 `@change` 试试
> > > > > > 3.1.2
> > > > > > 
> > > > > > * 支付宝小程序平台 优化 组件支持 vue 事件监听方式（需启用 component2）[详情](https://ask.dcloud.net.cn/question/110978)
> > > > > 
> > > > > 
> > > > > ```
> > > > > <life-follow
> > > > >   a:if="{{show}}"
> > > > >   sceneId="****"
> > > > >   checkFollow="{{checkFollow}}"
> > > > >   onCheckFollow="checkFollowCb"
> > > > >   onClose="closeCb"
> > > > > />
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > life-follow 没有onchange 事件
> > > > 
> > > > 
> > > > 哦，那就是 `@checkFollow="checkFollowCb"` `@close="closeCb "`
> > > 
> > > 
> > > 嗯嗯，这样编译出来大概是这样
> > > ```js
> > > <life-follow
> > >       vue-id="588c7fd8-1"
> > >       sceneId=""
> > >       checkFollow="{{checkLifeFlow}}"
> > >       data-event-opts="{{[['^checkFollow',[['checkFollowCb']]],['close',[['closeCb']]]]}}"
> > >       onCheckFollow="__e"
> > >       onClose="__e"
> > >       onVueInit="__l"
> > >     ></life-follow>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 添加 $event 参数之后
> > > ```
> > > <life-follow
> > >   a:if="{{show}}"
> > >   sceneId="****"
> > >   checkFollow="{{checkFollow}}"
> > >   @checkFollow="checkFollowCb($event)"
> > >   @close="closeCb($event)"
> > > />
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 编译之后：
> > > ```
> > > <life-follow
> > >       vue-id="588c7fd8-1"
> > >       sceneId="***"
> > >       checkFollow="{{checkLifeFlow}}"
> > >       data-event-opts="{{[['^checkFollow',[['checkFollowCb',['$event']]]],['close',[['closeCb',['$event']]]]]}}"
> > >       onCheckFollow="__e"
> > >       onClose="__e"
> > >       onVueInit="__l"
> > >     ></life-follow>
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 为了区分自定义事件，uniapp, 添加 ^ 前缀，目前 uniapp 没有对 tag 进行区分，感觉这里需要对支付宝部分组件，做一下区分，部分组件不设为自定义事件。
> > 
> > 
> > 这是使用的什么版本编译的，看起来像是旧的，修复后（ [be7e519](https://github.com/dcloudio/uni-app/commit/be7e519ac669b3e06a41a0f33bb58e12b1dbdf7e) ）编译的模板中存在标记 `data-com-type="wx"`
> 
> 是这个版本：2.0.0-31920210609001

好的，刚看了一下 life-follow 文档是个小程序平台的内置组件，后续更新一下小程序内置组件名单
