### ISSUE TITLE
关于银联小程序的开发（vueH5项目）

### ISSUE THREAD

**Issue by wpl455209682** [dcloudio/uni-app#2416]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
为什么我用uniapp项目引入了银联的vue的授权按钮插件，就会报错，而在普通vue项目上就正常运行？
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
正确的获取授权code

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/39522423/104556945-5f041000-567b-11eb-966d-ef8a944b145e.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]  2.9.8
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]  全部手机

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
查看一下这个UPButton在哪里读取了id属性。需要注意的是，小程序没有dom
