### ISSUE TITLE
map地图marker上label设置背景色无效

### ISSUE THREAD

**Issue by LQS5858** [dcloudio/uni-app#2417]
**问题描述**
map地图marker上label设置背景色无效

**复现步骤**
[复现问题的步骤]
1. hbuilderx启动uniapp项目
2. 进入地图页面
3. marker上label背景色无效果
markers: [{
        latitude: 34.174114,
        longitude: 108.856865,
        iconPath: '/static/img/shangjia.png',
      },
      {
        latitude: 34.178114,
        longitude: 108.856865,
        iconPath: '/static/img/mubiao.png',
      },
      {
        latitude: 34.173114,
        longitude: 108.856865,
        iconPath: '/static/img/siji.png',
        label: {
          content: '',
          color: '#212121',
          bgColor: 'black',
          padding: 10,
          borderRadius: 4,
        },
      }
      ]

**实际结果**
![image](https://user-images.githubusercontent.com/28332210/104700336-f6866300-574e-11eb-8da3-0c3e0609a957.png)

**Comment by dcloudhdx** [comment]
label 的 bgColor 仅 app-nvue/微信/百度小程序支持，确认页面是否是nvue
