### ISSUE TITLE
uni.request 跨域 如何设置携带cookie

### ISSUE THREAD

**Issue by zyfmmj** [dcloudio/uni-app#242]
**问题描述**

**Comment by zhetengbiji** [comment]
h5端可以使用任何ajax库，也可以直接使用xhr对象，其他端不可以。

**Comment by smallturbo** [comment]
@zhetengbiji 大佬 我最近也碰到这个问题了。选择uni-app的初衷就是为了跨端使用。而且项目都进入了全面测试阶段才发现这个问题。在苹果手机没设置跨端追踪的情况下即使使用了`xhrFields`，也无法携带cookie。请问大佬有没有好点的解决办法。
