### ISSUE TITLE
都忙着开发3.0去啦，UNIAPP 2.x 还在维护吗？

### ISSUE THREAD

**Issue by huadong** [dcloudio/uni-app#2420]
很多PR都没有人管了，能否有人看看#2383。

谢谢🙏

**Comment by soulcm** [comment]
同问，麻烦看下 #2449

**Comment by awagege** [comment]
放屁，也不看看3多久没更新了，连个onPageScroll组合式都还没支持

**Comment by huadong** [comment]
一般来说这么多PR不回复是比较匪夷所思的。开源不容易，但贡献PR也不容易。

**Comment by huadong** [comment]
感谢大神 @fxy060608 合并#2383。

@soulcm 估计你的PR也快了。

**Comment by zhetengbiji** [comment]
> 感谢大神 @fxy060608 合并#2383。
> 
> @soulcm 估计你的PR也快了。

正要关闭，还没想好怎么安慰他
