### ISSUE TITLE
拉起钉钉app授权登录

### ISSUE THREAD

**Issue by BaronCoder** [dcloudio/uni-app#2423]
**新功能描述**
uni-app 开发的 App 直接拉起钉钉App 授权登录

**现状及问题**
查看了官方文档暂时不支持uni-app直接拉起钉钉App授权登录,都需要原生配合不是特别方便, 看到社区里也有很多小伙伴在咨询,但社区并未给出回复

**Comment by StrivingRabbit** [comment]
暂不支持，可以在插件市场搜索此类插件
