### ISSUE TITLE
<picker mode="date">组件在钉钉环境出现了日期+时间的情况

### ISSUE THREAD

**Issue by pandashuai** [dcloudio/uni-app#2425]
`<picker mode="date"></picker >`中，明明在类型已经是date, 但在钉钉环境出现`日期+时间`的情况，而在支付宝和微信环境就正常，就只出现日期，该怎么解决啊？

**Comment by zhetengbiji** [comment]
> `<picker mode="date"></picker >`中，明明在类型已经是date, 但在钉钉环境出现`日期+时间`的情况，而在支付宝和微信环境就正常，就只出现日期，该怎么解决啊？

钉钉小程序吗？

**Comment by pandashuai** [comment]
对，钉钉小程序中，出现日期+时间的情况，其它环境正常

**Comment by pandashuai** [comment]
对，钉钉小程序中，出现日期+时间的情况，其它环境正常

**Comment by zhetengbiji** [comment]
> 对，钉钉小程序中，出现日期+时间的情况，其它环境正常

试试，单独测试钉钉小程序（不使用uni-app）是否有此问题，如果仍然有，到钉钉小程序的社区看下有没有类似问题

**Comment by Deepx-China** [comment]
我最终的解决方案是直接使用“**钉钉日期Api**”，因为我的应用的需求只是钉钉小程序，如果有多端需求，可使用uniapp判断终端的函数

**Comment by pandashuai** [comment]
> > 对，钉钉小程序中，出现日期+时间的情况，其它环境正常
> 
> 试试，单独测试钉钉小程序（不使用uni-app）是否有此问题，如果仍然有，到钉钉小程序的社区看下有没有类似问题

钉钉小程序上，有`<picker></picker >`组件但并没有`mode="date"`类型，只有
````
dd.datePicker({
  format: 'yyyy-MM-dd',
  currentDate: '2012-12-12',
  success: (res) => {
    dd.alert({
      content: res.date,
    });
  },
});

````
使用JsApi也是正常的

**Comment by pandashuai** [comment]
> 我最终的解决方案是直接使用“**钉钉日期Api**”，因为我的应用的需求只是钉钉小程序，如果有多端需求，可使用uniapp判断终端的函数

是的，如果没有解决方案，只能类型判断了

**Comment by kooro** [comment]
钉钉小程序，使用uvie的模板创建的项目，u-picker报错
![image](https://user-images.githubusercontent.com/23372053/128817796-c9d167ed-78af-49c5-ac00-c5ff33441c2e.png)
![image](https://user-images.githubusercontent.com/23372053/128817743-f48c7dcd-486a-4923-979b-7b4f814d06eb.png)
