### ISSUE TITLE
老项目配置使用新框架编译到微信小程序报错

### ISSUE THREAD

**Issue by BrightYang0801** [dcloudio/uni-app#243]
![image](https://user-images.githubusercontent.com/37973515/54654216-65b1b280-4af8-11e9-9cf4-1a558f7e49a6.png)

**Comment by BrightYang0801** [comment]
错误内容： appJSON["usingComponents"] 字段需为 object

**Comment by weiyunpeng** [comment]
+1

**Comment by weiyunpeng** [comment]
`npm install -g @vue/cli`

**Comment by fxy060608** [comment]
老项目中使用，需要更新最新的 cli 依赖，
比如 执行 npm update

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
