### ISSUE TITLE
input框设置修改foucs属性值，iOS端编译到支付宝小程序后，无法自动弹出软键盘。

### ISSUE THREAD

**Issue by fukantiankong** [dcloudio/uni-app#2430]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
`<div class="search-goods">
    <div class="input flex cross-center box-justify">
      <input v-model="goodsName" type="text" focus='true' @blur="searchGoodsList" placeholder="请输入商品名称搜索">
      <div class="search" @tap='searchGoodsList'>搜索</div>
    [</div>]
  </div>`
**预期结果**
支付宝小程序设置input框设置修改foucs属性值，自动弹出软键盘

**实际结果**
https://user-images.githubusercontent.com/18223934/105122511-4c715700-5b11-11eb-9e6f-78b39728aac6.png

**系统信息:**
 - 发行平台: 支付宝小程序
 - 操作系统  iOS 14.2  14.3
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run `info`的运行结果]`
 - 设备信息   iPhone7   iPhone8  iPhoneXR

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
实测无此问题，可以使用hello uni-app测试看是否正常
