### ISSUE TITLE
input标签的type属性如果是动态设置的话会导致placeholder-style失效

### ISSUE THREAD

**Issue by hty-zax** [dcloudio/uni-app#2431]
今天偶然发现的，动态设置input的type属性的时候会导致placeholder-style的样式失效，有人遇到过这个问题没？有没有好的解决办法，请教一下。

**Comment by zhetengbiji** [comment]
先使用v-if切换两个

**Comment by zhetengbiji** [comment]
文档里有注明：https://uniapp.dcloud.io/component/input

**Comment by hty-zax** [comment]
> 文档里有注释：[https](https://uniapp.dcloud.io/component/input) : [//uniapp.dcloud.io/component/input](https://uniapp.dcloud.io/component/input)

感谢感谢，看到了，没注意到这个
