### ISSUE TITLE
app希望支持UDP、TCP协议

### ISSUE THREAD

**Issue by BuTingBa** [dcloudio/uni-app#2432]
**新功能描述**
希望编译出的app可以支持UDP、TCP协议。

**现状及问题**
目前仅只有微信小程序支持UDP，其他的都不支持了，连app都不支持，这就有点离谱

**Comment by zhetengbiji** [comment]
收到，不过目前核心库支持这些的优先级不高，着急的话可以先使用插件市场的三方库。

**Comment by Otto-J** [comment]
See docs
https://uniapp.dcloud.net.cn/api/request/UDP.html
