### ISSUE TITLE
升级uni-app以后，chooseLocation组件的搜索功能搜索不到位置

### ISSUE THREAD

**Issue by yutons** [dcloudio/uni-app#2434]
近期我们平台的部分用户反馈地图组件搜索不到位置，经过问题uni-app文档查看，咱们升级了chooseLocation组件，查看源码发现src/platforms/h5/components/system-routes/choose-location/index.vue组件页面的_getList方法的scope做了限制，如下图
![image](https://user-images.githubusercontent.com/25010191/105436272-e82dcf00-5c99-11eb-9780-ebe492f12efc.png)
scpoe参数限制1000米以后只能搜索1000米范围内的地址，建议官方将改参数调整成可配置参数，可以入参自定义搜索范围，以达到不同场景的应用需求

**Comment by zhetengbiji** [comment]
#2453
