### ISSUE TITLE
支付宝bug合集(获取手机号&自定义组件&map@tap)

### ISSUE THREAD

**Issue by meooxx** [dcloudio/uni-app#2435]
**问题描述**
1 支付宝获取手机号方法getPhoneNumber已经申请了权限， 其他平台const { iv, encryptedData } = e.detail 可以取到encryptedData， 支付宝获取不到。解决方案在getPhoneNumber回调中调用如下
```js
	const [err, res] = await uni.getPhoneNumber()
	if(err) {
		uni.showToast({
			title: '授权失败,请重试',
			duration: 1500,
			icon: 'none'
		})
		return
	}
	const resData = {
		encryptedData: res.response
	}
```
2 支付宝的自定义组件周期方法不执行， mounted，created等， 尝试使用原生didUpdated等方法也无效

3 支付宝地图组件绑定@tap ，显示 Cannot read property '$options' of undefined 错误, 且@tap绑定等事件不触发

**复现步骤**
1 支付宝真机调试log getPhoneNumber回调如下：
![image](https://user-images.githubusercontent.com/13815865/105442752-457b4d80-5ca5-11eb-97c2-d3613b99fa65.png)

2 新建自定义组件，在组件中声明created，或者支付宝组件原生生命周期方法。在页面中注册使用，created和原生生命周期不触发。

3 新建自定义组件如 Map，模版中使用原生组件<map  @tap="cb"/>, 页面引用 Map组件。点击地图，console报错， 且cb不触发。

**系统信息:**
 - 发行平台: [支付宝]
 - 操作系统 [mac big sur 11.1]
 - HBuilderX版本 [3.0.5.20210107]
 - uni-app版本 [使用HBuilderX]
 - 设备信息 [xs max 14.3]

**Comment by Deeyu** [comment]
支付宝小程序，自定义组件中map的事件不触发，这个问题怎么解决？直接在页面中使用map组件没问题，封装一个组件就不行了

**Comment by meooxx** [comment]
> 支付宝小程序，自定义组件中map的事件不触发，这个问题怎么解决？直接在页面中使用map组件没问题，封装一个组件就不行了

没办法解决，不要封装

**Comment by Otto-J** [comment]
感谢反馈，就等了。经过我实际测试，最新版的 vue2 运行上面提到的问题，都解决了
- 获取手机号，目前平台发展，目前要求更加严格了，目前使用 button 的 open-type 来获取
- 自定义组件实际测试 mounted 和 created 可以正常触发
- map 组件，子组件使用 map 都可以正常触发 tap 事件。如果其他人对组件使用有疑问，可以参考 https://gitee.com/xiaoxfa/vue2-cli-uni-app-playground/tree/q%2Falipay-map/ 进行测试和反馈


如果仍有问题，请 reopen 或者新开 issue 艾特我。
