### ISSUE TITLE
 Subsequent property declarations must have the same type.  Property 'envVersion' must be of type '"release" | "develop" | "trial" | undefined', but here has type 'string | undefined'

### ISSUE THREAD

**Issue by weiyulong1221** [dcloudio/uni-app#2436]
在tsconfig.json设置 types后打包报错：

tsconfig.json:
 "types": [
      "webpack-env",
      "@dcloudio/types/uni-app"
    ],

package.json: 
"@dcloudio/types": "*",

报错如下： 

8750:9 Subsequent property declarations must have the same type.  Property 'envVersion' must be of type '"release" | "develop" | "trial" | undefined', but here has type 'string | undefined'.
    8748 |          * 要打开的uni-app版本
    8749 |          */
  > 8750 |         envVersion?: string;
         |         ^
    8751 |         /**
    8752 |          * 接口调用成功的回调函数
    8753 |          */

Build failed with errors.

**Comment by zhetengbiji** [comment]
已更新 2.0.23
