### ISSUE TITLE
rewarded-video.md    完整调用示例  不能执行。

### ISSUE THREAD

**Issue by wulinghui** [dcloudio/uni-app#2438]
**新功能描述**
rewarded-video.md    完整调用示例  不能执行。

**现状及问题**
rewarded-video.md    完整调用示例  不能执行。

**尝试方案**
我用的是上面的`广告创建`示例

**补充信息**
rewarded-video.md    完整调用示例   ad.js  有问题。

**Comment by dcloudhdx** [comment]
请详细描述下现象，没有反应还是有错误，运行到哪个平台？

**Comment by StrivingRabbit** [comment]
经测试为发现问题，由于长时间未回复，此问题关闭
