### ISSUE TITLE
unicloud-db 里 v-for 如果 有 嵌套  v-if 会 报错 【Component template should contain exactly one root element. If you are using v-if on multiple elements, use v-else-if to chain them instead.】

### ISSUE THREAD

**Issue by alexhmyang** [dcloudio/uni-app#2439]
**问题描述**

		<unicloud-db ref="udb" v-slot:default="{data,pagination, loading, error, options}"
			  :options="options"
			collection="friendCircle"
			  orderby="createTime desc"
			  field="userId,userName"
			  :getone="false"
			  :action="action"
			  :where="where"
			  @load="onqueryload" @error="onqueryerror">
			  <view v-if="error" class="error">{{error.message}}</view>
			  <view v-else class="list">
			    <view v-for="(item, index) in data" :key="index" class="list-item">
			
		这里如果有 嵌套  v-if 会 报错， 

			    </view>
			  </view>
			  <view v-if="loading" class="loading">加载中...</view>
			</unicloud-db>

18:30:45.495 Module Error (from ./node_modules/@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/loaders/templateLoader.js):
18:30:45.504 (Emitted value instead of an instance of Error) 
18:30:45.518   Errors compiling template:
18:30:45.536   tag <view> has no matching end tag.
18:30:45.551   71 |  			  @load="onqueryload" @error="onqueryerror">
18:30:45.555   72 |  
18:30:45.571   73 |  			  <view class="list">
18:30:45.573      |       ^^^^^^^^^^^^^^^^^^^
18:30:45.587   74 |  			
18:30:45.589   75 |  			
18:30:45.602   Component template should contain exactly one root element. If you are using v-if on multiple elements, use v-else-if to chain them instead.

**Comment by Wangyaqi** [comment]
完整的写法贴一下

**Comment by StrivingRabbit** [comment]
1. 写法错误，请检查修改
2. 长时间未回复
