### ISSUE TITLE
打开微信小程序自带的ES6转ES5，只要页面存在async语法糖，会报错

### ISSUE THREAD

**Issue by ivanlee93** [dcloudio/uni-app#244]
![image](https://user-images.githubusercontent.com/22174857/54657376-2be6a900-4b04-11e9-9249-d772a8f71cf2.png)

![image](https://user-images.githubusercontent.com/22174857/54657309-eaee9480-4b03-11e9-9823-eeaecd55baff.png)

**Comment by zhetengbiji** [comment]
uniapp内置转换，请勿打开小程序工具的的转换

**Comment by ivanlee93** [comment]
> uniapp内置转换，请勿打开小程序工具的的转换

uni官方的cli模板默认就是打开的，之前用mpvue时，也是说内置转换，但是实际上和小程序自带的还是有差别。不打开官方的ES5转换打包后，低版本苹果会有异常。打开就正常

**Comment by aiplat** [comment]
不会啊，可以直接使用。不必打开微信小程序自带的ES6转ES5。

**Comment by lijiaxi** [comment]
支付宝小程序存在同样问题

**Comment by zhetengbiji** [comment]
> > uniapp内置转换，请勿打开小程序工具的的转换
> 
> uni官方的cli模板默认就是打开的，之前用mpvue时，也是说内置转换，但是实际上和小程序自带的还是有差别。不打开官方的ES5转换打包后，低版本苹果会有异常。打开就正常

具体什么异常？

**Comment by fxy060608** [comment]
参考：https://github.com/dcloudio/uni-app/issues/256#issuecomment-477110725

**Comment by xiaoyucoding** [comment]
HBuilderX 1.8.0 已修复此问题，cli 已同步更新。

**Comment by ivanlee93** [comment]
> HBuilderX 1.8.0 已修复此问题，cli 已同步更新。

感谢
