### ISSUE TITLE
百度小程序将废除 swan.login

### ISSUE THREAD

**Issue by akFace** [dcloudio/uni-app#2443]
## 百度小程序 swan.login 将被废弃，替代为 swan.getLoginCode，uni.login 是否能正常使用？
![image](https://user-images.githubusercontent.com/22288837/105825551-ae8ef800-5ffa-11eb-9807-0592add59e37.png)

**Comment by dongziyudongziyu** [comment]
现已兼容提交到dev/65439893aa2011e15af03af570f493b8a543a9c7

**Comment by zhetengbiji** [comment]
> @dongziyudongziyu 请问啥时候发布，现在已经22年9月份了

越在2021年中旬发布，如遇到问题，请详细描述

**Comment by chenyangguang** [comment]
@dongziyudongziyu 同问 fixed 版本啥时候会发布？现在已经是22年10月20号了。

**Comment by zhenyuWang** [comment]
> @dongziyudongziyu 同问 fixed 版本啥时候会发布？现在已经是22年10月20号了。

已经发布，测试可正常使用，你遇到什么问题？参考代码：
```
<template>
  <view class="content">
    <button type="primary" open-type="login" @login="login">test login</button>
  </view>
</template>

<script>
  export default {
    methods: {
      login(){
        uni.login({
          complete(res){
            console.log('uni.login complete',res);
          }
        })
      }
    }
  }
</script>
```

**Comment by hb0730** [comment]
@zhenyuWang 是可以正常授权的，但是百度小程序工具上发布时可能会出现 **不允许使用swan.login方法**

**Comment by zhenyuWang** [comment]
uni.login 已针对百度小程序[兼容性升级](https://smartprogram.baidu.com/forum/topic/show/125547)转为 getLoginCode 调用，测试功能正常。
某些情况下，百度小程序发布时兼容性诊断依然提示swan.login非兼容性改造，可使用 [uni.getLoginCode](https://uniapp.dcloud.net.cn/api/plugins/login.html#getLoginCode) 替代 uni.login 解决。
