### ISSUE TITLE
https://api.bspapp.com/client 超过3秒，请求耗时 太久，什么原因

### ISSUE THREAD

**Issue by alexhmyang** [dcloudio/uni-app#2446]
**问题描述**

![image](https://user-images.githubusercontent.com/10215059/105957369-210fde80-60b4-11eb-9fd3-cdda1b97bacc.png)

百度小程序 调用 https://api.bspapp.com/client 超过3秒，请求耗时 太久，什么原因

![image](https://user-images.githubusercontent.com/10215059/105957503-50bee680-60b4-11eb-90eb-7456bbd2af97.png)

**Comment by hbcui1984** [comment]
阿里云近期优化过云函数及云数据库的响应，再测试一下，如依然有问题，可reopen issue.

**Comment by alexhmyang** [comment]
请求耗时 最近仍然是 400多ms 
api.bspapp.com/client | 439ms
