### ISSUE TITLE
子组件使用驼峰写法，父组件无法使用小写a-a的形式进行调用

### ISSUE THREAD

**Issue by weiyunpeng** [dcloudio/uni-app#245]
**问题描述**
子组件使用驼峰写法，父组件无法使用小写a-a的形式进行调用

**预期结果**
在父组件使用a-a的形式给子组件传参

**实际结果**
在父组件只能使用驼峰写法

**Comment by zhetengbiji** [comment]
举例说明

**Comment by weiyunpeng** [comment]
有一个tab组件，参数是这样定义的
`
props: {
        TabList: {
            type: Array
        }，
    },
`

我在父组件中引入
`import MuTab from "@/components/tab";`
并使用该组件
`<mu-tab
        :TabList="tabList"
      ></mu-tab>`
这样是可以正常显示的。

但如果我在父组件中这样引入
`<mu-tab
        :tab-list="tabList"
      ></mu-tab>`
就会不展示该内容

**Comment by weiyunpeng** [comment]
回退到旧版本，`"usingComponents": false` 后就没这个问题了。应该是自定义组件这一块引起的。

**Comment by fxy060608** [comment]
你这个应该是因为首字母大写导致的，props:{tabList:{type:array}} 应该可以

**Comment by weiyunpeng** [comment]
> 你这个应该是因为首字母大写导致的，props:{tabList:{type:array}} 应该可以

恩，是这样的。 首字母换成小写就正常了。不过旧版本首字母大写也是支持的呢

**Comment by fxy060608** [comment]
> > 你这个应该是因为首字母大写导致的，props:{tabList:{type:array}} 应该可以
> 
> 恩，是这样的。 首字母换成小写就正常了。不过旧版本首字母大写也是支持的呢

旧版本整个处理逻辑交由 Vue 内核处理，Vue 会兼容此写法
新版本 props 相关交由小程序内核处理，小程序不支持该写法，我们倒是可以在运行时兼容，但是会带来性能损失，所以建议还是自己调整一下

**Comment by weiyunpeng** [comment]
> > > 你这个应该是因为首字母大写导致的，props:{tabList:{type:array}} 应该可以
> > 
> > 
> > 恩，是这样的。 首字母换成小写就正常了。不过旧版本首字母大写也是支持的呢
> 
> 旧版本整个处理逻辑交由 Vue 内核处理，Vue 会兼容此写法
> 新版本 props 相关交由小程序内核处理，小程序不支持该写法，我们倒是可以在运行时兼容，但是会带来性能损失，所以建议还是自己调整一下
