### ISSUE TITLE
使用unicloud-db组件，导致编译失败

### ISSUE THREAD

**Issue by DevinChen1** [dcloudio/uni-app#2450]
编译成 字节跳动小程序 报错
或运行为 字节跳动小程序 报错
注释unicloud-db代码后成功编译和运行

**Comment by dcloudhdx** [comment]
Bug已确认，预计在 HBuilderX 3.1.0 修复

**Comment by DevinChen1** [comment]
HBuilderX 3.1.0 什么时候发布，好期待里面的 chooseAndUploadFile
