### ISSUE TITLE
wx-open-launch-app 标签里面的内容不显示，怎么处理？

### ISSUE THREAD

**Issue by Lich3nbo** [dcloudio/uni-app#2451]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
jdk初始化是ok的 没有其他任何报错
jdk引入的是 1.6.0
![image](https://user-images.githubusercontent.com/27914486/106427867-0cac5700-64a3-11eb-9667-d77462330036.png)

index.vue引用代码
![image](https://user-images.githubusercontent.com/27914486/106427951-28176200-64a3-11eb-9459-4e4201df80a6.png)

打开页面后宽高为0
![image](https://user-images.githubusercontent.com/27914486/106428150-775d9280-64a3-11eb-996f-9b21917fed80.png)

**复现步骤**
[复现问题的步骤]
1.  启动 '初始化cdk'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - h5
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - uni-app v2.9.8
uni-app cli v2.0.0-29820201110001

Environment Info:

  System:
    OS: Windows 10
    CPU: (6) x64 Intel(R) Core(TM) i5-9400 CPU @ 2.90GHz
  Binaries:
    Node: 14.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.4 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.14.8 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.449.0
  npmPackages:
    @dcloudio/types: * => 2.0.20
    @dcloudio/uni-app-plus: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-automator: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-cli-shared: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-h5: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-helper-json: * => 1.0.9
    @dcloudio/uni-migration: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-mp-360: ^2.0.0-29820201110001 => 2.0.0-alpha-29920201212001
    @dcloudio/uni-mp-alipay: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-mp-baidu: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-mp-qq: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-mp-toutiao: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-mp-vue: ^2.0.0-29820201110001 => 2.0.0-alpha-30220201224002
    @dcloudio/uni-mp-weixin: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-quickapp-native: ^2.0.0-29820201110001 => 2.0.0-alpha-30220201224002
    @dcloudio/uni-quickapp-webview: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-stat: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/uni-template-compiler: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-29820201110001 => 2.0.0-29820201110001
    @hap-toolkit/dsl-vue:  0.6.13
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.0-rc.2
    @vue/babel-plugin-jsx:  1.0.0-rc.5
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.9
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.9
    @vue/cli-plugin-babel: ^4.5.0 => 4.5.9
    @vue/cli-plugin-router:  4.5.9
    @vue/cli-plugin-vuex:  4.5.9
    @vue/cli-service: ^4.5.0 => 4.5.9
    @vue/cli-shared-utils:  4.5.9
    @vue/component-compiler-utils:  3.2.0 (3.2.0)
    @vue/preload-webpack-plugin:  1.1.2
    @vue/shared: ^3.0.0 => 3.0.4
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.11 => 2.6.12
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.6 (16.1.2, 15.9.6)
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.12 (2.6.12)
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.2.0 => 3.6.0
  npmGlobalPackages:
    @vue/cli: Not Found
 - 设备信息 [如 iPhone8 Plus]
华为mate30

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by RGM-89sc** [comment]
可以试试用定位，并且设置wx-open-launch-weapp透明度为0，覆盖在所需内容的表面
