### ISSUE TITLE
建议choose-location组件增加scope参数，支持自定义搜索范围功能

### ISSUE THREAD

**Issue by yutons** [dcloudio/uni-app#2453]
在修复了“摇树优化后 uni.openLocation、uni.chooseLocation 页面样式错乱的问题”后，"打开地图选择位置"组件仅支持选择当前位置1000米范围以内的位置列表，经过对src/platforms/h5/components/system-routes/choose-location/index.vue源码分析，发现官方优化过程中将scope范围设置成固定1000，导致无法搜索1000米以外的地址。
强烈建议官方针对该问题进行优化，针对chooseLocation组件新增scope参数，支持自定义范围搜索功能！

**Comment by yutons** [comment]
将nearby修改为region也可以解决

**Comment by a516117636** [comment]
uni.chooseLocation的bug这么多，这么久了，为什么不修复啊！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
