### ISSUE TITLE
无法获取header中的token字段的值

### ISSUE THREAD

**Issue by shiruchao** [dcloudio/uni-app#246]
**问题描述**
问题描述：由于不支持cookie采用在header中传递token字段，但是在登录成功后，在success 
 返回值header中无法找到token字段，header中只有一个content-type: "application/json; charset=utf-8"；使用Chrome  network查看接口返回头，是存在token字段，并且也是有值的！

**预期结果**
[在success方法的参数header中能有token字段并且存在值]

**实际结果**
[实际结果在和header中只有ontent-type: "application/json; charset=utf-8"；并没有token字段，也没有其他respons header字段]

**Comment by hulinNeil** [comment]
服务端什么语言，php使用$_SERVER["HTTP_TOKEN"]是可以得到，你将所有的header都打印出来看看。
```javascript
header: {  
     "Content-Type": "application/x-www-form-urlencoded",  
     "Token":res.data.token 
},
```

**Comment by shiruchao** [comment]
服务端是nodejs, 我打印所有的header只有Content-Type字段，其他就没有了

________________________________
shiruchao@outlook.com

发件人： hulin<mailto:notifications@github.com>
发送时间： 2019-03-21 17:46
收件人： dcloudio/uni-app<mailto:uni-app@noreply.github.com>
抄送： shiruchao<mailto:shiruchao@outlook.com>; Author<mailto:author@noreply.github.com>
主题： Re: [dcloudio/uni-app] 无法获取header中的token字段的值 (#246)

服务端什么语言，php使用$_SERVER["HTTP_TOKEN"]是可以得到，你将所有的header都打印出来看看。

header: {
     "Content-Type": "application/x-www-form-urlencoded",
     "Token":res.data.token
},

**Comment by hulinNeil** [comment]
我怎么能获得：
![image](https://user-images.githubusercontent.com/24296884/54744567-443ced80-4c02-11e9-8cb7-d49331a3dd12.png)

**Comment by shiruchao** [comment]
这我就不知道了！
请求
[cid:_Foxmail.1@fe1333a1-16df-7219-85cb-55b7da7c17a7]
打印

[cid:_Foxmail.1@7d8da4aa-1422-d6f7-c794-59bf8299773b]
chrome network


[cid:_Foxmail.1@d6e1f367-0dd1-16bc-2389-79fb6620b3cf]

________________________________
shiruchao@outlook.com

发件人： hulin<mailto:notifications@github.com>
发送时间： 2019-03-21 17:54
收件人： dcloudio/uni-app<mailto:uni-app@noreply.github.com>
抄送： shiruchao<mailto:shiruchao@outlook.com>; Author<mailto:author@noreply.github.com>
主题： Re: [dcloudio/uni-app] 无法获取header中的token字段的值 (#246)

我怎么能获得：
[image]<https://user-images.githubusercontent.com/24296884/54744567-443ced80-4c02-11e9-8cb7-d49331a3dd12.png>

**Comment by hulinNeil** [comment]
这就是最简单的express起的服务，你自己再尝试下吧
![image](https://user-images.githubusercontent.com/24296884/54744916-2a4fda80-4c03-11e9-80bb-fb28ac87a1e8.png)

**Comment by shiruchao** [comment]
体会？我在chrome network中可以看到token啊！但是在成功函数中拿不到，这让我咋体会
________________________________
shiruchao@outlook.com

发件人： hulin<mailto:notifications@github.com>
发送时间： 2019-03-21 18:00
收件人： dcloudio/uni-app<mailto:uni-app@noreply.github.com>
抄送： shiruchao<mailto:shiruchao@outlook.com>; Author<mailto:author@noreply.github.com>
主题： Re: [dcloudio/uni-app] 无法获取header中的token字段的值 (#246)

这就是最简单的express起的服务，你自己再尝试下吧
[image]<https://user-images.githubusercontent.com/24296884/54744916-2a4fda80-4c03-11e9-80bb-fb28ac87a1e8.png>

**Comment by shiruchao** [comment]
我更换其他接口，也是获取不到token值，问题就这样被关闭了？？
