### ISSUE TITLE
Vue3 ref value在onMounted 时为空

### ISSUE THREAD

**Issue by nyrf** [dcloudio/uni-app#2461]
**问题描述**
onMounted 这里应该可以获取到value

**复现步骤**

```vue
<script>
import { onMounted, ref } from 'vue'

export default {
  setup() {
    const headline = ref(null)

    // Before the component is mounted, the value
    // of the ref is `null` which is the default
    // value we've specified above.
    onMounted(() => {
      console.log(headline.value, 'mounted ref')
    })

    return {
      headline
    }
  }
}
</script>

<template>
  <view>
    <view ref="headline">
      Headline
    </view>
  </view>
</template>

```

**预期结果**
输出headline的value

**实际结果**
null

**系统信息:**
 - 发行平台: [微信小程序]
 - uni-app版本`uni-app v3.1.0  uni-app cli v2.0.0-alpha-31020210202006`

**Comment by fxy060608** [comment]
1. 在小程序平台，仅自定义组件支持ref属性
2. 目前不支持使用ref()来绑定组件上的ref
```js
{
setup() {
	// 使用 ComponentInternalInstance 上的refs可以访问自定义组件
	const ins = getCurrentInstance()
	onMounted(() => {
		console.log(ins.refs.test)

	})
	return {}
},
onReady() {
	// 也可以使用vue2的this.$refs来访问
	console.log(this.$refs.test)
}
}
```

**Comment by nyrf** [comment]
> 1. 在小程序平台，仅自定义组件支持ref属性
> 2. 目前不支持使用ref()来绑定组件上的ref
> 
> ```
> <script>
> 	import {
> 		onMounted,
> 		getCurrentInstance
> 	} from 'vue'
> 	export default {
> 		setup() {
> 			// 使用 ComponentInternalInstance 上的refs可以访问自定义组件
> 			const ins = getCurrentInstance()
> 			onMounted(() => {
> 				console.log(ins.refs.test)
> 
> 			})
> 			return {}
> 		},
> 		onReady() {
> 			// 也可以使用vue2的this.$refs来访问
> 			console.log(this.$refs.test)
> 		}
> 	}
> </script>
> <template>
> 	<view>
> 		<test ref="test"></test>
> 	</view>
> </template>
> ```

这个我试了，得到的是undefined，我更新到最新的2.0.0-alpha-31120210203002也是一样
