### ISSUE TITLE
uni-app不支持写es6的class吗？

### ISSUE THREAD

**Issue by Gutwql** [dcloudio/uni-app#2462]
**问题描述**
写es6的class报错

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
``` js
class BaseModule {
	__host;
	__swaggerUrl;
	
	constructor() {
	}
	// 请求拦截，uni-app用不上
	ocrRequestInterceprtor = (params) => {
		
		return params
	}
	// 响应拦截
	ocrReponseInterceprtor = (res) => {
		
		return res
	}
        $http = (url, params) {
		get: () => {
			uni.request({
					url: this.__host + url,
					method: 'GET',
					data: params,
					complete: (res) => {
						return ocrReponseInterceprtor(res)
					}
			});
		},
		post: () => {
			uni.request({
					url: this.__host + url,
					method: 'POST',
					data: params,
					complete: (res) => {
						return ocrReponseInterceprtor(res)
					}
			});
		},
	}
}
```
20:34:14.547 语法错误: D:\code\quick-ocr-uni-app\quick-ocr-uni-app\common\baseModule.js: Unexpected token, expected ";" (19:23)
20:34:14.552   17 | 		return res
20:34:14.553   18 | 	}
20:34:14.557 > 19 | 	$http = (url, params) {
20:34:14.592      | 	                      ^
20:34:14.597   20 | 		get: () => {
20:34:14.601   21 | 			uni.request({
20:34:14.605   22 | 					url: this.__host + url,

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [uni-app]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by yuconora** [comment]
```js
$http = (url, params) {}
```
写掉了箭头吧。。。

```js
$http = (url, params) => {} 
```

**Comment by StrivingRabbit** [comment]
楼上正解，此贴关闭
