### ISSUE TITLE
全局自定义组件在字节跳动不编译

### ISSUE THREAD

**Issue by xiaokar** [dcloudio/uni-app#2463]
**问题描述**
全局自定义组件在字节跳动不编译

**复现步骤**
正常运行到字节跳动小程序

[main.js部分源码]
// 自定义顶部导航
import cuCustom from './common/colorui/components/cu-custom.vue'
Vue.component('cu-custom', cuCustom)
// 自定义底部导航
import home from './components/public/home.vue'
Vue.component('home', home)
import shop from './components/public/shop.vue'
Vue.component('shop', shop)
import mine from './components/public/mine.vue'
Vue.component('mine', mine)

[使用文件的部分源码]
<cu-custom bgColor="bg-gradual-blue">
	<block slot="content">xxx</block>
</cu-custom>

**预期结果**
正常编译使用

**实际结果**
main.js写的全局组件运行或发行都没编译不显示，编译后json文件usingcomponent没东西，修改源vue文件保存后恢复正常，重新运行又失效

**系统信息:**
 - 发行平台:字节跳动小程序
 - 操作系统：win7字节跳动模拟器
 - HBuilderX版本 3.0.7.20210123

**补充信息**
问题可能是uniapp编译不兼容，希望能修复通知一声，谢谢

**Comment by xiaokar** [comment]
[使用文件的部分源码]
`<cu-custom bgColor="bg-gradual-blue">
	<block slot="content">零梦定制</block>
</cu-custom>`

**Comment by StrivingRabbit** [comment]
全局组件是注册到 app.json 中的 usingComponents。可以看一下有没有。我这里使用最新稳定版测试可以正常编译

**Comment by xiaokar** [comment]
> 全局组件是注册到app.json中的using Components。可以看一下有没有。我这里使用最新稳定版测试可以正常编译

app.json是有的，但是需要页面对应的json写入才能正常显示，比如index.vue编译后index.json里using Components为空，给index.vue随便换行保存编译后index.json的using Components就有东西就能正常显示了，已更新最新的hbuilder

**Comment by StrivingRabbit** [comment]
> > 全局组件是注册到app.json中的using Components。可以看一下有没有。我这里使用最新稳定版测试可以正常编译
> 
> app.json是有的，但是需要页面对应的json写入才能正常显示，比如index.vue编译后index.json里using Components为空，给index.vue随便换行保存编译后index.json的using Components就有东西就能正常显示了，已更新最新的hbuilder

HX使用的3.1.9？是cli项目吗？

**Comment by xiaokar** [comment]
> > > 全局组件是注册到app.json中的使用Components。可以看一下有没有。我这里使用最新稳定版测试可以正常编译
> > 
> > 
> > app.json是有的，但是需要页面对应的json能够正常执行正确的显示，例如index.vue编译后index.json里使用Components为空，给index.vue随便换行保存编译后index.json的使用Components就可以了有东西能够正常显示了，已更新最新的hbuilder
> 
> HX使用的3.1.9？是cli项目吗？

是cli，HX版本用了三个都没解决，3.1.8/3.1.9/3.1.11，编译逻辑文件差量编译和全局编译不一样吧？

**Comment by StrivingRabbit** [comment]
使用`2.0.0-31920210514002`测试，执行`build:mp-toutiao`app.json第一次编译也是正常的，usingComponents内也不是空

**Comment by xiaokar** [comment]
> 使用`2.0.0-31920210514002`测试，执行`build:mp-toutiao`app.json第一次编译也是正常的，usingComponents内也不是空。可以提供一个示例吗？

你们五六月份开发工具修好了，感谢

**Comment by StrivingRabbit** [comment]
> > 使用`2.0.0-31920210514002`测试，执行`build:mp-toutiao`app.json第一次编译也是正常的，usingComponents内也不是空。可以提供一个示例吗？
> 
> 你们五六月份开发工具修好了，感谢

好的，那么此issue关闭。如果还有其他问题可以重开或者提新的issue
