### ISSUE TITLE
文件上传，返回data数据 转为了string

### ISSUE THREAD

**Issue by Abyssness** [dcloudio/uni-app#2464]
**问题描述**
文件上传，返回data数据 转为了string

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码]

**预期结果**
文件上传成功，后端返回的数据在 response.data 为json格式，不是string

**实际结果**
返回的data为string

**系统信息:**
 - 发行平台: [H5平台]
 - uni-app版本 
 - uni-app v2.9.8
--uni-app cli v2.0.0-29820201110001

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
什么平台？使用的uni.uploadFile上传的文件吗？可以再详细的描述一下吗？比如截图

**Comment by Fuarmy** [comment]
额，问题好久了，我这边解决了，不想找了，把这个问题关闭了吧；我也记不清是你们的锅还是我没配置对

**Comment by Fuarmy** [comment]
![image](https://user-images.githubusercontent.com/51748206/116225872-e8e86c80-a784-11eb-843f-ac242323be3e.png)
一个是响应后的response，一个是我处理后的；

**Comment by Fuarmy** [comment]
不清楚你们这个uploadFile请求response.data会变成序列化后的字符串，request请求返回的是正常的，是我哪儿没有配置对吗？？？

**Comment by StrivingRabbit** [comment]
request请求`dataType`默认为`json`，会对响应数据做处理。`uploadFile`目前不对响应数据做处理。

目前各平台均为统一，后续考虑优化处理
