### ISSUE TITLE
image设置mode，编译为小程序代码是 mode的值失效

### ISSUE THREAD

**Issue by 915898885yx** [dcloudio/uni-app#2467]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
image设置mode，编译为小程序代码是 mode的值失效
**复现步骤**
[复现问题的步骤]
uniapp代码：
<image mode='top' src="../../static/salv.png" v-if="activeIndex == 1" mode=""></image>
编译后小程序的代码
<image mode src="../../static/salv.png"></image></block><block wx:if="{{activeIndex==2}}">
[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
<image mode=“top” src="../../static/salv.png"></image></block><block wx:if="{{activeIndex==2}}">
**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 小程序开发工具
 - HBuilderX版本 2.9.3
 - uni-app版本 100
 - 设备信息 小程序开发工具

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
请详细描述一下你的使用场景。经测试没有发现此问题，建议升级HX重试。

**Comment by StrivingRabbit** [comment]
因长时间未回复且经测试未发现问题，问题关闭
