### ISSUE TITLE
支付宝小程序支持分包预下载

### ISSUE THREAD

**Issue by eat-happy** [dcloudio/uni-app#2468]
**新功能描述**
支付宝小程序现已支持分包预下载

**现状及问题**
支付宝小程序打包后pages.json内不存在相应配置，请添加

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by StrivingRabbit** [comment]
是支持到支付宝小程序分包的，hello-uniapp编译过去是存在分包配置的。是这个问题吗？
