### ISSUE TITLE
Vue3 中style使用computed计算值时TypeError: _vm.__get_style is not a function

### ISSUE THREAD

**Issue by nyrf** [dcloudio/uni-app#2469]
**问题描述**
Vue3 组件中style使用computed计算值并使用数组style时TypeError: _vm.__get_style is not a function, 在vue2版是可以这么写的

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码]

```vue
<template>
  <view>
    <view :style="[style1]">
      component style computed 数组测试
    </view>
  </view>
</template>

<script>
export default {
  data() {
    return {}
  },

  setup() {
    const style1 = computed(() => {
      return { width: '100rpx' }
    })
    return {
      style1
    }
  }
}
</script>

<style></style>


```
使用vue2写法也不行

```
 computed: {
    style1() {
      return { width: '100rpx' }
    },
    style2() {
      return { height: '100rpx' }
    }
  }
```

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序]
 - HBuilderX版本 [3.1.0]
 - uni-app版本 2.0.0-alpha-31120210203002

**Comment by nyrf** [comment]
话说这都这么久没一个人处理？

**Comment by Sexy6God** [comment]
使用数组的形式绑定style就会出现这个错误

**Comment by jiyuan12354** [comment]
> 话说这都这么久没一个人处理？

楼主找到解决方案了吗，我在vue3引入 uni-ui 也报这个错

**Comment by jiyuan12354** [comment]
> 使用数组的形式绑定style就会出现这个错误

有解决方案或替代方案吗？

**Comment by fxy060608** [comment]
升级至HBuilderX Alpha 3.3.0

**Comment by jiyuan12354** [comment]
哎呀我的妈呀!!!!升级之后项目跑不起来了！！！！！！！
3.2.7 ---> 3.3.0
![image](https://user-images.githubusercontent.com/14569395/144424739-5221ece4-1b5f-42bd-8498-1ccbcfff6108.png)
![image](https://user-images.githubusercontent.com/14569395/144424794-081def5a-e691-401e-8d18-dd32fbe5d02f.png)

**Comment by fxy060608** [comment]
查看引入network/api的地方，不要使用 from 'network/api/...' 这样的方式，可以换成 from '@/network/api....' 或者相对路径

**Comment by jiyuan12354** [comment]
> 查看引入network/api的地方，不要使用 from 'network/api/...' 这样的方式，可以换成 from '@/network/api....' 或者相对路径

原本就是使用的【相对路径】方式引用的，报错跑不起来， 然后改成@/network/api/api还是依然报错
![image](https://user-images.githubusercontent.com/14569395/144531496-f4efca67-039b-4f9c-b901-c50f84234aca.png)

**Comment by jiyuan12354** [comment]
> 查看引入network/api的地方，不要使用 from 'network/api/...' 这样的方式，可以换成 from '@/network/api....' 或者相对路径

换回 3.2.7版本，相同的代码就可以跑起来的

**Comment by fxy060608** [comment]
你截图里的错误信息，是network/api/flyio/dist/npm/wx.js
这个是从哪来的？自己确认不了的话，就发一个测试工程

**Comment by jiyuan12354** [comment]
> 你截图里的错误信息，是network/api/flyio/dist/npm/wx.js 这个是从哪来的？自己确认不了的话，就发一个测试工程

https://github.com/jiyuan12354/test_hbuilderx330

**Comment by fxy060608** [comment]
> > 你截图里的错误信息，是network/api/flyio/dist/npm/wx.js 这个是从哪来的？自己确认不了的话，就发一个测试工程
> 
> https://github.com/jiyuan12354/test_hbuilderx330 麻烦用这个试试，用空白模板新建的项目， manifest.json把项目改成vue3版本，npm install 了 flyio等几个包，然后再main.js `import Api from '@/network/api/api' `就报错

把 network/api/config.js 里边的require代码，换成import方式

```js
import Fly from 'flyio/dist/npm/wx'
import md5 from 'js-md5'
import {
    shim
} from 'promise.prototype.finally'
```

**Comment by jiyuan12354** [comment]
> > > 你截图里的错误信息，是network/api/flyio/dist/npm/wx.js 这个是从哪来的？自己确认不了的话，就发一个测试工程
> > 
> > 
> > https://github.com/jiyuan12354/test_hbuilderx330 麻烦用这个试试，用空白模板新建的项目， manifest.json把项目改成vue3版本，npm install 了 flyio等几个包，然后再main.js `import Api from '@/network/api/api' `就报错
> 
> 把 network/api/config.js 里边的require代码，换成import方式
> 
> ```js
> import Fly from 'flyio/dist/npm/wx'
> import md5 from 'js-md5'
> import {
>     shim
> } from 'promise.prototype.finally'
> ```

非常感谢，解决了， 原来新版本是不能用commonjs规范了
