### ISSUE TITLE
使用async/await 报错  使用的hello uni-app 模板

### ISSUE THREAD

**Issue by lijiaxi** [dcloudio/uni-app#247]
![image](https://user-images.githubusercontent.com/20659256/54795453-41d0a700-4c87-11e9-93ee-96849d35595f.png)

![image](https://user-images.githubusercontent.com/20659256/54795475-557c0d80-4c87-11e9-9866-176a378521e5.png)

**Comment by lijiaxi** [comment]
请问下是要多加项目配置，去掉async 就不会报错，没人遇到过吗

**Comment by chavesgu** [comment]
我也遇到这个问题  你解决了吗

**Comment by lijiaxi** [comment]
微信小程序的话，关闭es6转es5. 支付宝的话暂时没解决，应该可以自己去配置babel转换，不转就行了

**Comment by zzlit** [comment]
请问有解决方案了吗？

**Comment by lijiaxi** [comment]
> 请问有解决方案了吗？

官方已经解决了，更新CLI到最新版本试试吧

**Comment by zzlit** [comment]
> > 请问有解决方案了吗？
> 
> 官方已经解决了，更新CLI到最新版本试试吧

3.6.3我还是有这个问题。。
