### ISSUE TITLE
Androrid 离线打包 HUAWEI MATE 30 Android 10  uni.chooseImage方法无法调起照相机！

### ISSUE THREAD

**Issue by hdwq** [dcloudio/uni-app#2471]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
Androrid 离线打包 HUAWEI MATE 30  Android 10  uni.chooseImage方法无法调起照相机！
**复现步骤**
[复现问题的步骤]
1.  启动 '...' 调用uni.chooseImage方法无法调起相机
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
takePhoto: function(success) {
		uni.chooseImage({
			count: 1,
			// sizeType: ['original'],
			 sizeType: ['compressed'],
			sourceType: ['camera','album'],
			// sourceType: ['camera'],
			success: async (res) => {
				UniUtils.toast('调用成功'+res)
				// #ifdef APP-PLUS
				const src = await PhotoUtils.compressImageHandler(res.tempFilePaths[0] || res.tempFiles[0].path)
				PhotoUtils.getImgBase64ByUrl(src, function(base64) {
					res.base64 = base64;
					success(res);
				});
				// #endif
				// #ifndef APP-PLUS
				PhotoUtils.getImgBase64(res.tempFilePaths[0] || res.tempFiles[0].path, 0.8, function(base64) {
					res.base64 = base64;
					success(res);
				});
				// #endif
			},
			complete() {
				 UniUtils.toast('调用完成')
			},
			fail(res){
				 UniUtils.toast('调用失败=======')
				 UniUtils.toast('调用失败'+res)
			}
		});
	},

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
HUAWEI MATE 30 Android 10 可以正常调起相机，正常使用。
**实际结果**
[这里请贴上你的报错截图或文字]
HUAWEI MATE 30 Android 10 无法调起相机，无法正常使用。

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等] APP
 - 操作系统 [如 iOS 12.1.2、Android 7.0] Android 10 
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]  HBuilderX 版本号 : 3.1.2.20210206
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]  HUAWEI MATE 30 型号 TAS-AL00

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
Android 10的问题

**Comment by ArrayDC** [comment]
请确保离线打包时配置了相机权限，并更新到最新版本SDK。
建议先云端打包确认是否存在问题。
