### ISSUE TITLE
急！！！！：使用web-view配置外部链接地址无法访问（任何地址都不行），没有打包成app，直接h5访问。

### ISSUE THREAD

**Issue by luzongzhu** [dcloudio/uni-app#2472]
**问题描述**
代码如下，使用HbulidX打包成H5页面，直接访问链接
![image](https://user-images.githubusercontent.com/26225234/107142168-f18c8c00-6967-11eb-89d5-c96f3863601b.png)
提示如下错误信息：
The Content Security Policy 'upgrade-insecure-requests' was delivered via a <meta> element outside the document's <head>, which is disallowed. The policy has been ignored.
![image](https://user-images.githubusercontent.com/26225234/107142223-3f08f900-6968-11eb-96af-c1340fb6a510.png)

[或者可以直接贴源代码]

**预期结果**
根据web-view配置外部链接可以直接访问到页面，例如:https://www.baidu.com

**实际结果**
提示错误，有根据错误说加上对应的header但是也没有效果。
The Content Security Policy 'upgrade-insecure-requests' was delivered via a <meta> element outside the document's <head>, which is disallowed. The policy has been ignored.

**系统信息:**
 - 发行平台: [H5平台]
 - HBuilderX版本 [2.5.1.20200103]
 - 设备信息 [chrome]

**Comment by StrivingRabbit** [comment]
webview有高度吗？是不是没有显示出来

**Comment by StrivingRabbit** [comment]
经测试未发现有什么问题，长时间未回复，此问题关闭
