### ISSUE TITLE
某些情况下解析 pages.json 会出现问题，需要优化

### ISSUE THREAD

**Issue by ModyQyW** [dcloudio/uni-app#2473]
**问题描述**
某些情况下解析 pages.json 会出现问题，需要优化。

**复现步骤**

给出以下 pages.json 的内容。

```json
{
  "pages": [
    {
      "path": "pages/index/index",
      "style": {
        "disableScroll": true,
        /* #ifdef MP-ALIPAY */
        "usingComponents": {
          "subscribe-msg": "plugin://subscribeMsg/subscribe-msg"
        }
        /* #endif */
      }
    }
  ],
  "globalStyle": {
    "navigationBarTextStyle": "black",
    "navigationBarTitleText": "uni-app",
    "navigationBarBackgroundColor": "#ffffff",
    "backgroundColor": "#ffffff"
  }
}

```

uni-cli-shared/lib/json.js parseJson 方法调用 preprocessor.preprocess 解析后，会得到以下内容（`"disableScroll": true,`结尾处的英文逗号没有去掉）。

```json
{
  "pages": [
    {
      "path": "pages/index/index",
      "style": {
        "disableScroll": true,
      }
    }
  ],
  "globalStyle": {
    "navigationBarTextStyle": "black",
    "navigationBarTitleText": "uni-app",
    "navigationBarBackgroundColor": "#ffffff",
    "backgroundColor": "#ffffff"
  }
}

```

**预期结果**

```json
{
  "pages": [
    {
      "path": "pages/index/index",
      "style": {
        "disableScroll": true
      }
    }
  ],
  "globalStyle": {
    "navigationBarTextStyle": "black",
    "navigationBarTitleText": "uni-app",
    "navigationBarBackgroundColor": "#ffffff",
    "backgroundColor": "#ffffff"
  }
}

```

**系统信息:**

uni-app v3.1.2
uni-app cli v2.0.0-31220210205002

Environment Info:

  System:
    OS: macOS 11.2
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 12.20.1 - /var/folders/n7/wlydjlk97378gr7ycmnf4dvc0000gn/T/yarn--1612763522118-0.0441889807086695/node
    Yarn: 1.22.10 - /var/folders/n7/wlydjlk97378gr7ycmnf4dvc0000gn/T/yarn--1612763522118-0.0441889807086695/yarn
    npm: 7.5.2 - ~/.nvm/versions/node/v12.20.1/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: 84.0.2
    Safari: 14.0.3
  npmPackages:
    @dcloudio/types: ~2.0.22 => 2.0.22 
    @dcloudio/uni-app-plus: 2.0.0-31220210205002 => 2.0.0-31220210205002 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-automator: 2.0.0-31220210205002 => 2.0.0-31220210205002 
    @dcloudio/uni-cli-shared: 2.0.0-31220210205002 => 2.0.0-31220210205002 
    @dcloudio/uni-h5: 2.0.0-31220210205002 => 2.0.0-31220210205002 
    @dcloudio/uni-helper-json: ~1.0.13 => 1.0.13 
    @dcloudio/uni-migration: 2.0.0-31220210205002 => 2.0.0-31220210205002 
    @dcloudio/uni-mp-vue: 2.0.0-31220210205002 => 2.0.0-31220210205002 
    @dcloudio/uni-stat: 2.0.0-31220210205002 => 2.0.0-31220210205002 (2.0.0-v3-24020191018001)
    @dcloudio/uni-template-compiler: 2.0.0-31220210205002 => 2.0.0-31220210205002 
    @dcloudio/uni-ui: ~1.2.10 => 1.2.10 
    @dcloudio/vue-cli-plugin-hbuilderx: 2.0.0-31220210205002 => 2.0.0-31220210205002 
    @dcloudio/vue-cli-plugin-uni: 2.0.0-31220210205002 => 2.0.0-31220210205002 
    @dcloudio/vue-cli-plugin-uni-optimize: 2.0.0-31220210205002 => 2.0.0-31220210205002 
    @dcloudio/webpack-uni-mp-loader: 2.0.0-31220210205002 => 2.0.0-31220210205002 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: 2.0.0-31220210205002 => 2.0.0-31220210205002 
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.2 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.11 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.11 
    @vue/cli-plugin-babel: ~4.5.11 => 4.5.11 
    @vue/cli-plugin-eslint: ~4.5.11 => 4.5.11 
    @vue/cli-plugin-router:  4.5.11 
    @vue/cli-plugin-unit-jest: ~4.5.11 => 4.5.11 
    @vue/cli-plugin-vuex: ~4.5.11 => 4.5.11 
    @vue/cli-service: ~4.5.11 => 4.5.11 
    @vue/cli-shared-utils:  4.5.11 
    @vue/component-compiler-utils:  3.2.0 (3.2.0)
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/test-utils: ~1.1.3 => 1.1.3 
    @vue/web-component-wrapper:  1.2.0 
    eslint-plugin-vue:  7.5.0 
    jest-serializer-vue:  2.0.2 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ~2.6.12 => 2.6.12 
    vue-class-component:  7.2.6 
    vue-eslint-parser:  7.4.1 
    vue-hot-reload-api:  2.3.4 
    vue-jest:  3.0.7 
    vue-loader:  15.9.6 (16.1.2, 15.9.6)
    vue-property-decorator:  9.1.2 
    vue-router:  3.0.1 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ~2.6.12 => 2.6.12 (2.6.12)
    vue-template-es2015-compiler:  1.9.1 
    vuex: ~3.6.2 => 3.6.2 
  npmGlobalPackages:
    @vue/cli: 4.5.11

**Comment by ModyQyW** [comment]
开发工具 VSCode，如需复现仓库请留言，谢谢。

**Comment by StrivingRabbit** [comment]
使用条件编译请保证，编译前 和 编译后 文件的正确性。
此处问题有解决方法：
- 将逗号也写在条件编译内部

**Comment by ModyQyW** [comment]
> 使用条件编译请保证，编译前 和 编译后 文件的正确性。
> 此处问题有解决方法：
> 
> * 将逗号也写在条件编译内部

我明白这样做可以，如果不打算优化解析，那么也请至少在文档上写明这一个注意点，避免后来者踩坑，谢谢。

**Comment by StrivingRabbit** [comment]
> > 使用条件编译请保证，编译前 和 编译后 文件的正确性。
> > 此处问题有解决方法：
> > 
> > * 将逗号也写在条件编译内部
> 
> 我明白这样做可以，如果不打算优化解析，那么也请至少在文档上写明这一个注意点，避免后来者踩坑，谢谢。

感谢反馈，已完善文档说明
