### ISSUE TITLE
boundingClientRect()回调函数的参数声明类型错误

### ISSUE THREAD

**Issue by ZHowee** [dcloudio/uni-app#2474]
**问题描述**
调用selectorQuery.selectAll()返回的NodesRef对象有复数节点的情况下，再调用boundingClientRect()，其回调函数的参数的数据类型为数组。但是声明文件中该参数只有一个接口NodeInfo，为对象。因此我以length为依据遍历时报错length不在NodeInfo中。希望能完善一下声明。
刚学ts没几天，看到tsconfig.json引入了types:["@dcloudio/types"]，尝试修改了/@dcloudio/types/uni-app/uni.d.ts里的声明，的确在这里，不过不知道怎么改。

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 Android 7.0
 - uni-app版本 3.0.7
 - 设备信息 微信开发者工具模拟器

**Comment by ZHowee** [comment]
想了一下，应该是NodeInfo | NodeInfo[]就好了吧

**Comment by ZHowee** [comment]
继续把vue组件转成ts时发现getCurrentPages()内置的$getAppWebview()方法没有声明。

**Comment by StrivingRabbit** [comment]
5d554d24bd36b920d5ea33b07dcf2cca46e30e2c
