### ISSUE TITLE
使用 uni.showToast 后 使用 uni.hideNavigationBarLoading() 会导致 showToast 隐藏掉

### ISSUE THREAD

**Issue by jianguiweilai** [dcloudio/uni-app#2475]
**问题描述**
使用 uni.showToast 后 使用 uni.hideNavigationBarLoading() 会导致 showToast 隐藏掉

**复现步骤**
[复现问题的步骤]
1.  调用接口后 showToast 了失败
2. 调用了 uni.hideNavigationBarLoading()
3. showToast 的内容一闪而过，便隐藏了

[或者可以直接贴源代码]

uni.showToast({
		icon: 'none',
		title:  '网络连接异常',
});
uni.hideNavigationBarLoading()

**预期结果**
showToast 能够不被隐藏

**实际结果**

![image](https://user-images.githubusercontent.com/15683188/107306897-b487dd00-6ac0-11eb-9363-ede5cc64584e.png)

**系统信息:**
 - 发行平台: uniApp手机调试 可复现， H5 未复现
 - 操作系统 ： Android 
 - HBuilderX版本 当前最新 3.0.7
 - uni-app版本 当前最新
 - 设备信息 vivo x21 、华为手机 等多台手机

**Comment by StrivingRabbit** [comment]
https://uniapp.dcloud.io/api/ui/navigationbar?id=hidenavigationbarloading

1. 此api不支持app平台
2. App平台调用此API时会关闭屏幕中间悬浮显示的loading

*请使用条件编译来调用*
