### ISSUE TITLE
微信小程序无法执行图像裁剪

### ISSUE THREAD

**Issue by tianrenlin** [dcloudio/uni-app#2477]
**H5端是可以的，但是在微信开发工具里面不行**
_HBuilderX2.9.8 微信开发工具 1.05.2102010_
裁剪图片的代码来源：HBuilderX中的uniapp示例，pages/template/crop/crop.vue，经过调试发现在小程序中不执行ctx.draw中的代码，也就导致不能裁剪

**Comment by zhetengbiji** [comment]
其他版本是否正常？

**Comment by StrivingRabbit** [comment]
您好，默认图片可能是跨域了，你可以选择一张本地图片查看裁剪结果
