### ISSUE TITLE
scroll-view 如何手动控制滚动条位置

### ISSUE THREAD

**Issue by 56600535** [dcloudio/uni-app#2478]
## 我该怎么手动控制滚动条的位置
![image](https://user-images.githubusercontent.com/49943200/107912021-ab06e500-6f98-11eb-8693-3933fbbbb5aa.png)
如图，我希望每次发送完后，滚动条位置都处于最下方，该怎么实现

**Comment by StrivingRabbit** [comment]
1. scroll-top可以用来设置竖向滚动条位置
2. scroll-into-view可以滚动到指定元素

**Comment by StrivingRabbit** [comment]
由于此问题长时间未回复，此问题关闭
