### ISSUE TITLE
iOS uni.chooseImage 选择相册 闪退

### ISSUE THREAD

**Issue by JiakunXu** [dcloudio/uni-app#2486]
**问题描述**
HBuilder 开发 uniapp，本地打包 iOS，uni.chooseImage 选择相册时 闪退

**复现步骤**
uni.chooseImage 选择相册

**预期结果**
打开相册

**实际结果**
闪退

**系统信息:**
 - 发行平台: app
 - 操作系统 iOS 14.4
 - HBuilderX版本 3.0.7、3.1.2
 - uni-app版本 
 - 设备信息 iPhone12

**补充信息**
iOSSDK@3.0.7.80407_20210123/HBuilder-Hello 存在同样问题
iOSSDK@3.1.2.80410_20210206/HBuilder-Hello 存在同样问题

**Comment by StrivingRabbit** [comment]
感谢反馈，建议更新到最新版本重试

**Comment by StrivingRabbit** [comment]
您好，是否还有此问题？

**Comment by StrivingRabbit** [comment]
经测试没有发现此问题。又因长时间未回复，此问题关闭
