### ISSUE TITLE
华为meta 20pro，小程序无法调用接口

### ISSUE THREAD

**Issue by bhabgs** [dcloudio/uni-app#2488]
**问题描述**
小程序挨罚情况下，meta20pro手机 无法调用接口
`uni.request is error`
其他手机 都正常。

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [微信小程序]
 - 操作系统 [Android 7.0]
 - 设备信息 [华为meta20pro]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
你说的 ”小程序挨罚情况“ 是什么？
直接使用小程序测试（不使用 uni-app ）问题是否存在，如果仍然存在，直接到小程序社区反馈

**Comment by bhabgs** [comment]
> 你说的 ”小程序挨罚情况“ 是什么？
> 直接使用小程序测试（不使用 uni-app ）问题是否存在，如果仍然存在，直接到小程序社区反馈

小程序开发环境。。。
