### ISSUE TITLE
拖动movable-view由上至下移动，会触发下拉刷新

### ISSUE THREAD

**Issue by crli** [dcloudio/uni-app#2489]
**问题描述**
拖动movable-view由上至下移动，会触发下拉刷新

**复现步骤**
1页面使用onReachBottom下拉刷新方法，使用movable-view组件
2拖动movable-view由上至下移动，会触发下拉刷新

**预期结果**
拖动movable-view由上至下移动，不会触发下拉刷新

**系统信息:**
 - 发行平台: [所有平台]
 - 操作系统 [如 iOS 14.0.0、Android 7.0， chome版本 87.0.4280.141（正式版本）]
 - HBuilderX版本 [2.9.8.20201110]

**Comment by StrivingRabbit** [comment]
手指往上滑动movable-view的时候页面滚动从而触发了触底？能否详细描述一下？
