### ISSUE TITLE
获取元素信息，结果为null 

### ISSUE THREAD

**Issue by githuandong** [dcloudio/uni-app#249]
**问题描述**
通过 `uni.createSelectorQuery()`  获取元素的布局信息，但是一直返回null，使用的官网示例代码

**复现步骤**
 
![image](https://user-images.githubusercontent.com/31892279/54812513-3a7cbe00-4cc6-11e9-8dad-689807fbc188.png)

![image](https://user-images.githubusercontent.com/31892279/54812569-56805f80-4cc6-11e9-8ab4-21ec24cfba4b.png)

  

**预期结果**
获取元素的布局信息

**实际结果**
![image](https://user-images.githubusercontent.com/31892279/54812293-c0e4d000-4cc5-11e9-93a0-b2d5542ec7ce.png)

**系统信息:**
 - 发行平台: app
 - 操作系统 android8.1
 - HBuilderX版本 
![image](https://user-images.githubusercontent.com/31892279/54812388-fe495d80-4cc5-11e9-9853-64aef95ac621.png)

 - uni-app版本 
 - 设备信息 荣耀8x

**Comment by hulinNeil** [comment]
需要在onReady里面调用方法
