### ISSUE TITLE
uni-app 离线打包成apk ,只能在Android studio里打包成apkk吗

### ISSUE THREAD

**Issue by hanyingling** [dcloudio/uni-app#2492]
**问题描述**
uni-app 离线打包成apk ,只能在Android studio里打包成apk吗，在HBuild X里能否实现直接打包出apk

**Comment by zhetengbiji** [comment]
https://ask.dcloud.net.cn/article/37979

**Comment by StrivingRabbit** [comment]
由于时间过长未回复，此问题关闭
