### ISSUE TITLE
寻找uniapp兼职兄弟姐妹

### ISSUE THREAD

**Issue by sunqitao** [dcloudio/uni-app#2493]
手上有个项目急需寻找兼职uniapp开发者

回报会根据工作时间与任务完成度核算

所有人员会根据任务里程碑结算，单个里程碑周期最长为2周(迭代式开发)

参与人员会实行淘汰制，单个里程碑如果评定结果不及格会及时结算淘汰

期待你的参与
回复方式邮件： s@m1c.cn

**Comment by klren0312** [comment]
so email

**Comment by sunqitao** [comment]
> so email

s@m1c.cn
