### ISSUE TITLE
input属性selection-start和selection-end目前无效了，在小程序反而有用

### ISSUE THREAD

**Issue by zpfee** [dcloudio/uni-app#2494]
input属性selection-start和selection-end目前H5和APP下无效了，在小程序反而有用，这个属性对于我目前的项目非常重要，uniapp没有办法直接操作DOM，想要自动选中input中的内容现在束手无策，focus事件中的event对象也不能操作如:e.currentTarget.select(),
MUI反而更灵活

**Comment by MadiniGo** [comment]
我也遇到了类似的需求，兄弟有什么方案吗😩

**Comment by StrivingRabbit** [comment]
同一个问题 #2534 ，此问题关闭
