### ISSUE TITLE
小程序data里存储this会报错

### ISSUE THREAD

**Issue by 2470761262** [dcloudio/uni-app#2496]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果** 
我希望数组里存储可以存储vue组件实例，但是小程序缺报错，H5不会

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/55891373/108975440-76460c80-76c1-11eb-9825-338a40b35043.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
如果是说的本地存储，只能存储可 json 序列化的对象

**Comment by xiyifenheart** [comment]
微信小程序的data只能保存可被JSON序列化的数据，例如function就不能放在data上
