### ISSUE TITLE
快应用使用video show-center-play-btn=“false” 不生效

### ISSUE THREAD

**Issue by wangzhigang** [dcloudio/uni-app#2497]
**问题描述**
[问题描述：用uniapp开发快应用视频播放需求,播放器有一个灰色的背景播放按钮没办法隐藏]

**复现步骤**
[复现问题的步骤]
1.  启动 '快应用都播放页面'
2. 自动播放视频前会出现一个灰色播放按钮，没办法隐藏

[或者可以直接贴源代码]

**预期结果**
[切换播放视频，自动播放视频不出现灰色播放按钮]

**实际结果**

**系统信息:**
 - 发行平台: [如oppo快应用等]
 - 操作系统 [Android 7.0]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [oppo]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
问题重复，此问题关闭 #2498
