### ISSUE TITLE
uniapp中引入外部js，index.html中引入H5是没有问题的，但是打包成app是找不到的

### ISSUE THREAD

**Issue by Xxcool** [dcloudio/uni-app#2499]
uniapp中引入外部js，index.html中引入H5是没有问题的，但是打包成app是找不到的。关键需要引入的js有七八个，都不是模块化，不能通过import这种方式，没有发到npm上也就不用通过npm方式，怎么解决这个问题呢

**Comment by zhetengbiji** [comment]
你要在逻辑层用还是在渲染层用？如果是逻辑层用，你下载下来引入即可， 但是要注意不支持 dom、bom

**Comment by ZhouWeiPeng** [comment]
多看看文档。打包成app是没有index.html的，在app中引入外部js用import，或者renderjs，uniapp官网搜就知道了，在renderjs中可以使用dom和bom

**Comment by ZhouWeiPeng** [comment]
renderjs不支持nvue
