### ISSUE TITLE
Uni App #H5端# 地图中Marker不会更新

### ISSUE THREAD

**Issue by qq1037305420** [dcloudio/uni-app#250]
**问题描述**
Uni App #H5端# 地图中（小程序没有问题）
marker属性变更后，Marker不会及时更新（图标）

**复现步骤**
		swiperIndex(index, oldIndex) {
			this.markers[oldIndex] = Object.assign({}, this.markers[oldIndex], {iconPath: toiletIcon})
			this.markers[index] = Object.assign({}, this.markers[index], {iconPath: selectToiletIcon})
			this.latitude = this.markers[index].latitude;
			this.longitude = this.markers[index].longitude;
		}
![image](https://user-images.githubusercontent.com/28857867/54860199-e0c1d580-4d51-11e9-8516-8842934e3a97.png)
![image](https://user-images.githubusercontent.com/28857867/54860205-ef0ff180-4d51-11e9-87a1-f7a4be71711d.png)

**Comment by xiaoyucoding** [comment]
[Vue 数组更新检测](https://cn.vuejs.org/v2/guide/list.html#%E6%95%B0%E7%BB%84%E6%9B%B4%E6%96%B0%E6%A3%80%E6%B5%8B)
由于 JavaScript 的限制，Vue 不能检测以下变动的数组：
1. 当你利用索引直接设置一个项时，例如：vm.items[indexOfItem] = newValue
2. 当你修改数组的长度时，例如：vm.items.length = newLength

应当使用 Vue.set 方法修改数组内的值：
```javascript
this.$set(this.covers, 0, Object.assign(this.covers[0], {
    iconPath: '/static/uni.png'
}));
```

**Comment by qq1037305420** [comment]
我用Vue.$set的时候 所有Markers就全部消失了
我目前的解决方案是 调用了腾讯地图原生的方法
ifdef H5
markersyncs[index].setIcon()

**Comment by xiaoyucoding** [comment]
> 我用Vue.$set的时候 所有Markers就全部消失了
> 我目前的解决方案是 调用了腾讯地图原生的方法
> 能不能加一个图标全部重绘的功能
> ifdef H5
> markersyncs[index].setIcon()

局部更新怎么会把全局都覆盖掉呢？代码怎么写的，提供个例子验证一下。

**Comment by qq1037305420** [comment]
![image](https://user-images.githubusercontent.com/28857867/55152954-5bdd1e80-518c-11e9-8998-84697b887f65.png)
![image](https://user-images.githubusercontent.com/28857867/55153011-6eefee80-518c-11e9-909f-7130519ec030.png)
![image](https://user-images.githubusercontent.com/28857867/55153207-db6aed80-518c-11e9-820c-e739c3b0833e.png)

**Comment by xiaoyucoding** [comment]
提供下测试代码，截图怎么测试。。。

**Comment by SuperRun** [comment]
这么写markers 清空了是怎么回事

**Comment by EircYangQiXin** [comment]
有其他的解决办法吗？

**Comment by cnsilvan** [comment]
这个问题还没修复？
