### ISSUE TITLE
【bug提交】

### ISSUE THREAD

**Issue by liuhaiqiang999** [dcloudio/uni-app#2501]
**问题描述**
官网pages.json中进行配置 pages中style的app-plus的选项background不生效

编辑器3.1.2
系统macos   10.15.8
模拟器ios14  iPhone12 pro 

![image](https://user-images.githubusercontent.com/42488402/109153673-2aba5e00-77a8-11eb-8cda-1d777e8dc9d2.png)

**Comment by zhetengbiji** [comment]
这是 webview 部分的背景色，在其表层还有 html 的背景色

设置页面的背景色，使用样式 page 选择器（相当于 body）

```
<style>
page{
background:#ccc;
}
<style>
```

**Comment by zhetengbiji** [comment]
另外 bug 提交应该是有模板的吧，也不是你这个格式

**Comment by liuhaiqiang999** [comment]
> 另外bug提交应该是有模板的吧，也不是你这个格式

头一次提交 ==！ 下次修改

**Comment by liuhaiqiang999** [comment]
> 另外bug提交应该是有模板的吧，也不是你这个格式



> 这是webview部分的背景色，在其表层还有html的背景色
> 
> 设置页面样式的背景色，使用页面选择器（相当于body）
> 
> ```
> <风格>
> 页{
> 背景：＃ CCC ;
> }
> </ style >
> ```

学习了解了  谢谢
