### ISSUE TITLE
【提交bug】uni-app分享图文到微信图片不显示

### ISSUE THREAD

**Issue by LingCn** [dcloudio/uni-app#2504]
**问题描述**
uni-app分享图文到微信图片大于20kb，IOS不显示

**复现步骤**
let infoData = wx.getStorageSync('actoken');
				uni.share({
				    provider: "weixin",
				    scene: "WXSceneSession",
				    type: 0,
				    href: this.baseHost+"static/front/recharge/#/goodDetail?id="+this.detail.id +'&shareCode=' + infoData.share_code,
				    title: this.detail.name,
				    summary: this.detail.desp,
				    imageUrl: this.detail.logo_images_mobile[0].image,
				    success: function (res) {
				    },
				    fail: function (err) {
				    }
				});
**实际结果**
[这里请贴上你的报错截图或文字]
<img width="496" alt="error" src="https://user-images.githubusercontent.com/22288787/109273274-ef259f80-784c-11eb-8676-b9b88fca8c7e.png">

**系统信息:**
 - 发行平台: [APP]
 - 操作系统 [如 iOS 12.1.2]
 - HBuilderX版本 [HBuilderX 3.1.2.20210206]
 - 设备信息 [iPhone8 Plus]

**Comment by JiakunXu** [comment]
试试将 this.detail.logo_images_mobile[0].image 处理成 200x200

**Comment by LingCn** [comment]
> 试试将 this.detail.logo_images_mobile[0].image 处理成 200x200

我现在是通过uni.compressImage压缩图片，然后大部分能够分享成功。但是有一些图片也不大但是压缩也不能成功
let that = this;
				uni.downloadFile({
					url:that.detail.logo_images_mobile[0].image,
					success: function (images) {
						uni.compressImage({
						  src: images.tempFilePath,
						  width:'10%',
						  height:'10%',
						  success: res => {
						    that.sureShare(res.tempFilePath)
						  }
						})
					},
					fail(error){
						uni.hideLoading();
						that.sureShare(that.detail.logo_images_mobile[0].image)
					}
				})

**Comment by JiakunXu** [comment]
图片在阿里云，通过 ?x-oss-process=image/resize,m_pad,w_200,h_200 处理后，iOS 分享微信，图片显示正常

**Comment by JiakunXu** [comment]
试试 .jpg

**Comment by LingCn** [comment]
@JiakunXu 因为一些原因没有使用阿里云，目前通过canvas重绘图片实现了ios分享正常

uni.showLoading({
					title:'分享中...'
				})
				uni.downloadFile({
					url:that.detail.logo_images_mobile[0].image,
					success: function (images) {
						var ctx = uni.createCanvasContext("firstCanvas") // 使用画布创建上下文 图片
						ctx.drawImage(images.tempFilePath, 0, 0, 50, 50)// 设置图片坐标及大小，括号里面的分别是（图片路径，x坐标，y坐标，width，height）
						//绘制
						ctx.draw(false,()=>{
							uni.canvasToTempFilePath({
								fileType: "png",
								canvasId:'firstCanvas',
								destWidth:100,
								destHeight:100,
								success: function(response) {
									uni.hideLoading();
									that.sureShare(response.tempFilePath)
								},
								 fail(error) {
									uni.hideLoading();
									that.sureShare(that.detail.logo_images_mobile[0].image)
								 }
							})
						})
					},
					fail(error){
						uni.hideLoading();
						that.sureShare(that.detail.logo_images_mobile[0].image)
					}
				})
