### ISSUE TITLE
【提交bug】 iPhonex以上 屏幕安全区像素差了3-5个px

### ISSUE THREAD

**Issue by liuhaiqiang999** [dcloudio/uni-app#2505]
**问题描述**

如：页面除 原生导航栏和原生底部导航  一共2个元素   第一个scroll-view 第二个 swiper 其中swiper高度为自动获取，如下

在媒体查询中获取到可使用窗口高度【windowHeight】A 后   ，再通过createSelectorQuery获取第一个元素的bottom B

那么A-B = C 应该是屏幕剩下的像素 ，而在测试后 把C给swiper后，发现可以上下滚动几个像素，并且出现了滚动条

安卓手机没发现问题【自己用的不是全面屏】，而发现有问题的手机都是iPhone系列X后的，也就是全面屏，不确定安卓的全面屏手机是否也存在这样的问题，在小屏幕的iPhone上发现没问题

联系：17310646585  Q857523518  可以远程提供演示

**复现步骤**
1.获取屏幕的安全高度
```JavaScript
			uni.getSystemInfo({
				success: function(res) {
					console.log(res.windowHeight);
				}
			});
});
```

2.获取第一个元素scroll-view的bottom
scroll-view元素的代码
```JavaScript
		<scroll-view :scroll-x="true" style="white-space: nowrap;margin-left: 20rpx;  width: 730rpx; height: 100rpx ; background-color: #0077AA; padding-top: 200rpx;"
		 :show-scrollbar="true" :scroll-into-view="scrollintoview" :scroll-with-animation="true" id="tabtop">
			<view style="width: 145rpx; display: inline-block;" v-for="(item,index) in tabBars" :key="item.id" :id="'tab'+index"
			 :class="tabIndex === index ? 'selectText l-color-main' : '' " @click="changeTab(index)">{{item.title}}</view>
		</scroll-view>
```
获取scroll-view距离顶部的距离
```JavaScript
			const query = uni.createSelectorQuery().in(this);
			query.select('#tabtop').boundingClientRect(data => {
			  console.log("得到布局位置信息" + JSON.stringify(data));
			  console.log("节点离页面顶部的距离为" + data.top);
			}).exec();
```

3.通过console.log的输出 手工进行计算
```JavaScript
02:54:53.073 [LOG] : [Number] 640  at pages/index/index.vue:193 
02:54:53.097 [LOG] : 得到布局位置信息{"bottom":150,"height":150,"id":"tabtop","width":365,"left":10,"dataset":{},"right":375,"top":0} at pages/index/index.vue:200 
02:54:53.119 [LOG] : 节点离页面顶部的距离为0 at pages/index/index.vue:201 
```
如iPhone12mini  

640-150 = 490

4.给swiper元素手工进行赋值
```JavaScript

		<swiper style="background-color: #007AFF;   width: 750rpx; height: 490px;" @change="onChangeTab" :current="current">
			<swiper-item v-for="(item,index) in tabBars" :key="item.id" >
				<text>1</text>
			</swiper-item>

		</swiper>
```

5.可以发现 是可以上下滚动 5个像素  其他的如 iPhone12 和 pro 是3个像素 下面2张图片 可以通过放到 PS等工具查看  差了5个像素 图在二楼

**预期结果**
应该不能上下滚动

**实际结果**
可以上下滚动

**系统信息:**
 - 发行平台: APP
 - 操作系统 IOS 11.0  14.4
 - 
 - HBuilderX版本 
 - 3.1.2.20210206
 - uni-app版本 不知道！~
 - 
 - 设备信息 [如 iPhone8 Plus]
 - iPhone12mini  iPhone12  iPhonex iPhone12pro 均有测试均有差距，iPhone8 没有

**补充信息**
据我测试，应该是全面屏出现了问题，具体的就有待你们工程师的努力了

**Comment by liuhaiqiang999** [comment]
![image](https://user-images.githubusercontent.com/42488402/109343884-f4b0d300-78a8-11eb-866e-d75fe4ef6d9f.png)
![image](https://user-images.githubusercontent.com/42488402/109343907-fb3f4a80-78a8-11eb-9e0b-9e0cf4e95dd2.png)

**Comment by liuhaiqiang999** [comment]
初步分析应该是下面的横线，不知道安卓如魅族的好像就有这样的横线 不知道怎么是适配  如果在系统信息中能获取到 有没有横线  要是有再减去这个高度就好了

**Comment by liuhaiqiang999** [comment]
目前IOS平台 都是减6  iPhonemini是6px iPhone12 和 pro测试是3px

**Comment by yuconora** [comment]
看图里面的导航栏是自定义的吧，测量一下高度在94左右 标准iPhoneX 导航栏高度是 statusBar高度+navbar高度（44+44），出现这个原因大概率是 uni.getSystemInfo接口获取的windowHeight是用的标准导航栏获取的 自定义导航栏使用这个接口获取windowHeight是不规范的吧

**Comment by liuhaiqiang999** [comment]
> 看图里面的导航栏是自定义的吧，测量一下高度在94左右 标准iPhoneX 导航栏高度是 statusBar高度+navbar高度（44+44），出现这个原因大概率是 uni.getSystemInfo接口获取的windowHeight是用的标准导航栏获取的 自定义导航栏使用这个接口获取windowHeight是不规范的吧

用的系统自带的导航栏  右侧加了个按钮  中间搞了个搜索框  我发群里 有朋友跟我一起测试了  确实有误差

**Comment by zhetengbiji** [comment]
https://ask.dcloud.net.cn/question/117849

**Comment by StrivingRabbit** [comment]
此问题已在 HX 3.1.6 + 版本修复
