### ISSUE TITLE
原有App中嵌入uni-app遇到的问题

### ISSUE THREAD

**Issue by swdenglian** [dcloudio/uni-app#251]
我目前已经再Android原有的App上嵌入了uni-app, 但是跳转activity的时候会出现uni-app的启动画面，返回我原有的activity时候要点击2次返回键，问这个问题有办法解决吗？

### android
- [ ] 怎么去除启动页或者修改启动页
- [X] 怎么去除android中点击2次返回键才能退出移植的WebApp
- [ ] android 出现报错 ava.lang.NoSuchMethodException: setWebContentsDebuggingEnabled [boolean] 与这个问题类似 https://ask.dcloud.net.cn/question/14325

### 其他
- [ ] 官方有相关的uni-app移植到原有app的demo吗？android 与 ios

---
### 【解决】 怎么去除android中点击2次返回键才能退出移植的WebApp
[参考](http://ask.dcloud.net.cn/article/34959)
```
 //  这个问题算是曲线救国，找不到android 与 uniapp 哪里修改，但是通过 plus 和 js 来解决问题具体方
 //  法为在 App.vue 的 onLaunch 方法中 重写 plus.nativeUI.toast 方法，具体代码如下

onLaunch: function() {
     ....
      // #ifdef APP-PLUS
      let oldToast = plus.nativeUI.toast;
      plus.nativeUI.toast = str => {
		if (str === '再按一次退出应用') {
			plus.runtime.quit();
		}else{
			oldToast(str)
		}
	};
     // #endif
     ....
}

```

**Comment by zxzhgk** [comment]
同求解决方案

**Comment by st-dc** [comment]
你需要的是Widget方式集成5+SDK ，http://ask.dcloud.net.cn/docs/#//ask.dcloud.net.cn/article/81
对原生没有开发经验的同学。建议让有经验的人帮助你完成。否则遇到问题很难快速找到解决方案。

**Comment by swdenglian** [comment]
> 你需要的是Widget方式集成5+SDK ，http://ask.dcloud.net.cn/docs/#//ask.dcloud.net.cn/article/81
> 对原生没有开发经验的同学。建议让有经验的人帮助你完成。否则遇到问题很难快速找到解决方案。

这个并没有多大关系，刚刚接触 uni app 可以控制android 中不用2次放回退出uni app 吗？

**Comment by swdenglian** [comment]
> 你需要的是Widget方式集成5+SDK ，http://ask.dcloud.net.cn/docs/#//ask.dcloud.net.cn/article/81
> 对原生没有开发经验的同学。建议让有经验的人帮助你完成。否则遇到问题很难快速找到解决方案。

原生的同学看官方demo也是一脸闷逼哈哈哈哈 @hbcui1984 @st-dc
