### ISSUE TITLE
当自定义组件与内置组件重名时, 会失去组件间关系

### ISSUE THREAD

**Issue by dnt1996** [dcloudio/uni-app#2511]
**问题描述**
当自定义组件与内置组件重名时, 会失去组件间关系
导致provide和jnject失效

**复现步骤**
RadioGroup.vue
```vue
<template>
    <view>
        <slot></slot>
    </view>
</template>

<script>
export default {
    name: 'RadioGroup',
    provide() {
        return {
            radioGroup: this
        }
    }
}
</script>
```
RadioButton.vue
```vue
<template>
    <view></view>
</template>

<script>
export default {
    name: 'RadioButton',
    inject: {
        radioGroup: 'radioGroup'
    },
    created() {
        console.log(this.radioGroup)
    }
}
</script>
```

pages/index/index
```vue
<template>
    <view>
        <RadioGroup>
            <RadioButton></RadioButton>
            <RadioButton></RadioButton>
        </RadioGroup>
    </view>
</template>

<script lang="ts">
import { defineComponent, ref } from '@vue/composition-api'
import RadioGroup from './RadioGroup.vue' //如果导入名称改为CustomRadioGroup, 代码可以正确运行
import RadioButton from './RadioButton.vue'
export default defineComponent({
    name: 'Test',
    components: { RadioGroup, RadioButton },
    setup() {
        return {
        }
    }
})
</script>

```

**预期结果**
RadioButton组件获取并打印出RadioGroup组件实例

**实际结果**
![image](https://user-images.githubusercontent.com/31310280/109587741-8d15b480-7b42-11eb-9cc2-989300ee8e4b.png)
RadioButton打印出undefined并抛出一个错误

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 windows
 - HBuilderX版本 未使用HX
 - uni-app版本 v2.0.0-31220210205004
 - 设备信息 微信开发者工具v1.05.2102010

**补充信息:**
在RadioButton中使用this.$parent只能获取到页面组件实例
在RadioGroup中使用this.$parent得到undefined, $children也是空数组
仿佛RadioGroup在组件树中消失了一样

**Comment by StrivingRabbit** [comment]
哪里重名了？从你提供的实例没有看出来

**Comment by dnt1996** [comment]
> 哪里重名了？从你提供的实例没有看出来

RadioGroup编译后变成radio-group，和原生的radio-group重名

**Comment by StrivingRabbit** [comment]
哦哦，明白了。只能说暂时请不要和原生组件重名
