### ISSUE TITLE
ts 中 UniApp.IntersectionObserver.relativeTo 不应该返回 void

### ISSUE THREAD

**Issue by ishowman** [dcloudio/uni-app#2513]
**问题描述**
ts 类型定义有问题。按照[文档](https://uniapp.dcloud.io/api/ui/intersection-observer?id=%e4%bb%a3%e7%a0%81%e7%a4%ba%e4%be%8b)中的示例代码，会报 n 个类型错误：
```
 onReady() {
      observer = uni.createIntersectionObserver(this);
      observer.relativeTo('.scroll-view') // ts: Expected 2 arguments, but got 1
      .observe('.ball', (res) => {     // ts: Property 'observe' does not exist on type 'void'
       
      })
  }
```
在 chrome 浏览器中，报错：
```
Error in event handler for "service.requestComponentObserver": "TypeError: Failed to execute 'observe' on 'IntersectionObserver': parameter 1 is not of type 'Element'."
```

**复现步骤**
[复现问题的步骤]
1.  复制[文档](https://uniapp.dcloud.io/api/ui/intersection-observer?id=%e4%bb%a3%e7%a0%81%e7%a4%ba%e4%be%8b)中的示例代码
2.  出现问题描述中的错误信息
3. 按照`https://github.com/dcloudio/uni-app/issues/1428#issuecomment-614611003` 中更新版本依赖，仍然未解决。执行`npm update` 更新依赖，仍然为解决。

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]:  chrome 内核的 h5 
 - 操作系统 [如 iOS 12.1.2、Android 7.0]: win10

 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]：
   - uni-app v2.8.11
   - uni-app cli v2.0.0-28920200907001

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

@dcloudio/types 类型定义有问题

**Comment by StrivingRabbit** [comment]
更新 @dcloudio/types 到 2.0.24
