### ISSUE TITLE
uniCloud 云存储客户端api上传文件成功，却无法加载

### ISSUE THREAD

**Issue by by-retrograde** [dcloudio/uni-app#2514]
uniCloud 云存储客户端api上传文件成功，却无法加载
`// 上传图像
					for (let i = 0; i < this.src.length; i++) {
						uniCloud.uploadFile({
							filePath: then.src[i],
							cloudPath: then.imgInfoList[i].name,
							success(res) {
								console.log(res.fileID)
								// then.sqlSrc.push()
							},
							fail(res) {
								this.$refs.uToast.show({
									title: '系统错误，请重新提交！',
									type: 'error',
								})
							}
						})
					}`

**Comment by Wangyaqi** [comment]
换一下电脑的dns看一下上传的文件能访问吗

**Comment by by-retrograde** [comment]
啊，可以了，但这个问题是什么原因呢，用户去使用的话不会去改dns呀




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dcloudio/uni-app"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月4日(星期四) 上午10:15
收件人:&nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&gt;;
抄送:&nbsp;"Zero"<166997982@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] uniCloud 云存储客户端api上传文件成功，却无法加载 (#2514)





 
换一下电脑的dns看一下上传的文件能访问吗

**Comment by Wangyaqi** [comment]
目前北京地区联通网络访问阿里云存储有点问题，阿里云正在处理

**Comment by Wangyaqi** [comment]
已恢复，可以清理一下系统和浏览器的dns缓存再访问看是否正常
