### ISSUE TITLE
http://127.0.0.1:4930 不在以下 request 合法域名列表中

### ISSUE THREAD

**Issue by mikexfreeze** [dcloudio/uni-app#2515]
**问题描述**
开发模式运行到小程序模拟器，控制台报错

**复现步骤**
![image](https://user-images.githubusercontent.com/16068816/109934632-b469ae80-7d07-11eb-91bd-67f98c57555a.png)

**预期结果**
没有报错

**实际结果**
有报错

**系统信息:**
 - HBuilderX版本 [3.0.7]
 - uni-app版本 [v3.0.7]

**补充信息**
貌似和热更新相关，打包生产版本无此问题

**Comment by zhetengbiji** [comment]
是你请求了局域网中的接口吧
小程序项目设置中，可以取消域名验证
