### ISSUE TITLE
微信小程序自定义组件编译成 h5 环境后 observers 失效

### ISSUE THREAD

**Issue by zhengpq** [dcloudio/uni-app#2518]
**问题描述**
如题，微信小程序自定义组件编译成 h5 环境后 observers 失效

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [H5平台]
 - uni-app版本 [uni-app-plus:  "^2.0.0-31220210205004"]
 - 设备信息 [Chorme]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhengpq** [comment]
将 observers 改成 watch 的写法还是不行，如果有哪位大哥知道解决方法麻烦告知一下，感谢！

**Comment by zhetengbiji** [comment]
未支持此特性，建议先整体组件迁移为 vue 组件

**Comment by zhengpq** [comment]
> 未支持此特性，建议先整体组件迁移为 vue 组件

请问有计划支持这个特性吗？因为目前我们这边的业务都是原生开发，迁移为 vue 组件的话不太现实。我主要是想用 uniapp 来做web 端的小程序组件库交互，因为对比下来，目前就 uniapp 可以把微信小程序的组件很好地转化为 h5 端。

**Comment by zhetengbiji** [comment]
> > 未支持此特性，建议先整体组件迁移为 vue 组件
> 
> 请问有计划支持这个特性吗？因为目前我们这边的业务都是原生开发，迁移为 vue 组件的话不太现实。我主要是想用 uniapp 来做web 端的小程序组件库交互，因为对比下来，目前就 uniapp 可以把微信小程序的组件很好地转化为 h5 端。

计划是有的，不过优先级并不高。

**Comment by zhengpq** [comment]
> > > 未支持此特性，建议先整体组件迁移为 vue 组件
> > 
> > 
> > 请问有计划支持这个特性吗？因为目前我们这边的业务都是原生开发，迁移为 vue 组件的话不太现实。我主要是想用 uniapp 来做web 端的小程序组件库交互，因为对比下来，目前就 uniapp 可以把微信小程序的组件很好地转化为 h5 端。
> 
> 计划是有的，不过优先级并不高。

明白，感谢！

**Comment by code-manito** [comment]
请问楼主解决了吗

**Comment by zhengpq** [comment]
> 请问楼主解决了吗

还没有，还在找解决方法
