### ISSUE TITLE
canvas对象无法获取webjl

### ISSUE THREAD

**Issue by sincez** [dcloudio/uni-app#2519]
**问题描述**
canvas经过封装之后，变成了uni-canvas，这样其他插件通过canvas获取webgl的时候，就会报无法获取，请问如何处理

**复现步骤**
目前使用jsmpeg插件，插件内有一段代码是通过canvas对象获取webgl的，这时候首先会报  this.canvas.getContext is not a function  通过官方方法获取内部原始canvas dom对象，但是获取webgl，就会提示webgl获取失败

[或者可以直接贴源代码]
以下是jsmpeg插件的代码
this.canvas = options.canvas || document.createElement("canvas");
        this.width = this.canvas.width;
        this.height = this.canvas.height;
        this.enabled = true;
        this.hasTextureData = {};
        var contextCreateOptions = {
            preserveDrawingBuffer: !!options.preserveDrawingBuffer,
            alpha: false,
            depth: false,
            stencil: false,
            antialias: false,
            premultipliedAlpha: false
        };
        this.gl = this.canvas.getContext("webgl", contextCreateOptions) || this.canvas.getContext("experimental-webgl", contextCreateOptions);
        if (!this.gl) {
            throw new Error("Failed to get WebGL Context")
        }
**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
期望可以正常获取webgl
**实际结果**
会先报canvas错，如下：
this.canvas.getContext is not a function
获取了内部原始canvas dom后，则会报webgl获取失败

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
目前由于官方对canvas进行了封装，导致了上边的错误

**Comment by zhetengbiji** [comment]
同名的原因，可以通过动态创建解决。

```js
document.createElement('canvas')
```

**Comment by sincez** [comment]
不是很明白，可以说的清楚些吗？谢谢🙏

**Comment by zhetengbiji** [comment]
就是动态创建一个原始 canvas 对象

```js
var canvas=document.createElement('canvas')
canvas. getContext.....
```

**Comment by sincez** [comment]
> 就是动态创建一个原始 canvas 对象
> 
> ```js
> var canvas=document.createElement('canvas')
> canvas. getContext.....
> ```

感谢，我先试试是否可以解决

**Comment by sincez** [comment]
使用这个方法，不报错了，但是canvas图像显示不出来，就是空白，麻烦帮忙看下解决呢

**Comment by zhetengbiji** [comment]
> 使用这个方法，不报错了，但是canvas图像显示不出来，就是空白，麻烦帮忙看下解决呢

看不到是因为你还没把它添加到文档中，比如

```js
document.append(canvas)
```

这个网站有一些基础的 dom 教程，你可以学习一下：https://www.runoob.com/htmldom/htmldom-tutorial.html
