### ISSUE TITLE
uni.requestSubscribeMessage 无法调出

### ISSUE THREAD

**Issue by SophiaWoo** [dcloudio/uni-app#2524]
**问题描述**
在微信小程序正式环境，调用 uni.requestSubscribeMessage时报错。
报错信息：requestSubscribeMessage:fail can only be invoked by user TAP gesture 

**系统信息:**
 - 发行平台: 微信小程序
 - 调试基础库：2.15.0

**补充信息**
复现方式：在组件emit的方法中，先执行了一个异步请求，再调用uni.requestSubscribeMessage。
微信小程序打包正式环境调用报错，打包测试环境调用不报错。可能和uniapp打包方式有关。

**Comment by StrivingRabbit** [comment]
requestSubscribeMessage:fail can only be invoked by user TAP gesture
翻译
requestSubscribeMessage:失败只能被用户点击手势调用

**Comment by SophiaWoo** [comment]
并不需要您的翻译。。。
请看一下补充信息，谢谢。

**Comment by joyobyte** [comment]
意思就是说需要用户手动点击触发，不能主动调用。

**Comment by StrivingRabbit** [comment]
> 并不需要您的翻译。。。
> 请看一下补充信息，谢谢：跑dev构建体验版时，是可以正常调出的；跑build构建的体验版则报错。
> 虽然已经用其他方式解决了问题，但还是希望看看框架层面能不能处理下。

测试时和正式发布时，api调用是不一样的。这个API只能由用户发生点击行为或者发起支付回调后，才可正常触发
