### ISSUE TITLE
百度小程序swan-sitemap组件编译错误

### ISSUE THREAD

**Issue by mirror29** [dcloudio/uni-app#2526]
**问题描述**
在pages.json内使用usingComponents引入百度小程序swan-sitemap 组件时，将页面的json文件编译为
`"usingSwanComponents": {
    "swan-sitemap-list": "dynamicLib://swan-sitemap-lib/swan-sitemap-list"
  }`
正确编译结果应为：
`"usingComponents": {
    "swan-sitemap-list": "dynamicLib://swan-sitemap-lib/swan-sitemap-list"
  }`
导致页面出错

**复现步骤**
[复现问题的步骤]

根据百度小程序文档引入使用swan-sitemap组件即可
文档地址：
[https://smartprogram.baidu.com/docs/develop/framework/sitemap/](https://smartprogram.baidu.com/docs/develop/framework/sitemap/)

**预期结果**
页面正常渲染

**实际结果**
页面未能正常渲染

**系统信息:**
 - 发行平台: 百度小程序
 - 操作系统 iOS 12.1.2、Android 7.0
 - HBuilderX版本 3.1.2
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[根据你的分析，出现这个问题的原因可能在哪里？]

百度基础库版本3.220.20之前使用usingSwanComponents页面渲染正常，应是某次更新后改为了usingComponents而uniapp的编译结果未更新，导致页面出错

**Comment by StrivingRabbit** [comment]
已提交至 dev 2121124c4be41ce164e714150860658f8530fc88

**Comment by zhetengbiji** [comment]
已发布 HBuilderX 3.1.6 alpha

**Comment by quiet-jing** [comment]
此次 pull request [2121124](https://github.com/dcloudio/uni-app/commit/2121124c4be41ce164e714150860658f8530fc88) 会导致动态库引入同时保留 usingSwanComponents 和 usingComponents  若两者同时存在 百度小程序开发着工具不会报错 但是会导致代码无法上传 报错"sitemap"动态库notfound  只能保留节点usingComponents  解决
