### ISSUE TITLE
希望添加一个参数来控制页面显示的最大宽度

### ISSUE THREAD

**Issue by Leslie-Luo** [dcloudio/uni-app#2529]
### 希望添加一个参数来控制页面显示的最大宽度。
目前有`rpxCalcMaxDeviceWidth`和`rpxCalcBaseDeviceWidth`这两个参数来进行宽屏适配，但是在大屏上页面宽度还是会填满整个屏幕，希望增加个参数来约束页面最大显示宽度

例如下图这种设置最大宽度为560px，页面显示内容全部在宽度为560px的这个盒子内，这个这个整体居中，周围留白
![image](https://user-images.githubusercontent.com/22937782/110449993-b95ea180-80fd-11eb-86c6-9bc98c283060.png)

**Comment by Leslie-Luo** [comment]
> 你看这部分[文档](https://uniapp.dcloud.io/collocation/pages?id=globalstyle)里的 maxWidth 是你需要的吗？

我刚刚看到这个了，我设置了maxWidth:560px,现在可以居中显示了
但是设置了最大宽度后，我把显示宽度设置为1000，这个盒子的高度不是按照设置的最大宽度560px计算的
![image](https://user-images.githubusercontent.com/22937782/110455450-67b91580-8103-11eb-879f-a72aea209171.png)
理想中的效果应该是不管浏览器的视口有多大，这个轮播盒子的高度应该是218px
![image](https://user-images.githubusercontent.com/22937782/110455637-a18a1c00-8103-11eb-9cf1-87f58bcc4ace.png)

**Comment by Leslie-Luo** [comment]
@zhetengbiji 您好麻烦看看这个问题

**Comment by zhetengbiji** [comment]
把 rpxCalcMaxDeviceWidth 和 rpxCalcBaseDeviceWidth 都设置为 560 试试

**Comment by Leslie-Luo** [comment]
> 把 rpxCalcMaxDeviceWidth 和 rpxCalcBaseDeviceWidth 都设置为 560 试试

@zhetengbiji 感谢，现在可以了
我一直以为 rpxCalcBaseDeviceWidth 是设计稿转rpx的基准

**Comment by zhetengbiji** [comment]
rpxCalcBaseDeviceWidth 是规定 rpx 计算方式，可能不太好理解，多读几遍文档里的解释也许能理解

**Comment by Leslie-Luo** [comment]
> rpxCalcBaseDeviceWidth 是规定 rpx 计算方式，可能不太好理解，多读几遍文档里的解释也许能理解

@zhetengbiji 是的，仔细多读几遍就理解了  Thanks♪(･ω･)ﾉ
