### ISSUE TITLE
社区网站访问不了，云打包也不行了

### ISSUE THREAD

**Issue by ygy-97** [dcloudio/uni-app#2532]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
能否详细描述一下
另外检查一下你的网络

**Comment by ygy-97** [comment]
![图片](https://user-images.githubusercontent.com/66999373/110905969-44ca7380-8346-11eb-8071-42769c42cf5e.png)
从uniapp官网点击插件市场页面就报错

**Comment by zhetengbiji** [comment]
哪个地区？
使用的哪个运营商的网络？
是否设置代理？
是否设置 DNS？

**Comment by ygy-97** [comment]
> 
> 
> 哪个地区？
> 使用的哪个运营商的网络？
> 是否设置代理？
> 是否设置 DNS？

![Uploading 图片.png…]()

**Comment by zhetengbiji** [comment]
图片没上传成功

你手动设置一下 DNS，比如：114.114.114.114

**Comment by daoying007** [comment]
来 uni-app 微信群交流吧，沟通更及时，加我微信（备注uni-app），拉你进群

更多各种程序员技术交流群（定期更新，长期有效），点这里扫码入群：https://www.yuque.com/docs/share/4c911e59-2da0-4c7b-9a60-e33d5a9ad671

![uni-app 微信群交流](https://user-images.githubusercontent.com/39725475/112411174-720c1e00-8d57-11eb-96f0-050bf531fc1b.jpg)

**Comment by hbcui1984** [comment]
统一到 https://github.com/dcloudio/uni-app/issues/2550 反馈。
