### ISSUE TITLE
uni.chooseLocation，想要获得当前位置名称，高德返回的res.name是“地图位置”这四个字

### ISSUE THREAD

**Issue by a516117636** [dcloudio/uni-app#2533]
**问题描述**
使用uni.chooseLocation，想要获得当前位置名称，高德返回的res.name是“地图位置”这四个字。请问这个bug什么时候能解决，比较急

**系统信息:**
 - 发行平台:app 未测试小程序端

**Comment by StrivingRabbit** [comment]
请详细描述一下你的问题

**Comment by a516117636** [comment]
uni.chooseLocation()存在bug有以下几处：
1、无法搜索全国范围内的地点，很多远的地方搜不到。希望改为全国范围内搜索。
2、调用uni.chooseLocation()后，展示的地点列表中，第一个显示为“地图位置”，如下图所示。选中这个“地图位置”后，打印success返回参数中的name，值为“地图位置“。该name值应为当前地址的位置名称，而非”地图位置“四个字。
![1](https://user-images.githubusercontent.com/17865841/111624295-75b71680-8826-11eb-97e7-40c461bce779.jpg)
另外建议，显示距离如果很远的话，请使用“千米”作为单位。如下图红圈部分所示：
![2222](https://user-images.githubusercontent.com/17865841/111624993-540a5f00-8827-11eb-8c9f-e73e03040052.png)

**Comment by a516117636** [comment]
有修复计划吗？为什么没有回音？

**Comment by zhetengbiji** [comment]
> 有修复计划吗？为什么没有回音？

我不是回复过你了，在这里：https://github.com/dcloudio/uni-app/issues/1060

**Comment by a516117636** [comment]
苍天大地啊，这么优秀的框架存在这么低级的bug，这不合理啊，先把这个修了吧

**Comment by zhetengbiji** [comment]
> 苍天大地啊，这么优秀的框架存在这么低级的bug，这不合理啊，先把这个修了吧

已经回复你优先处理了，你还想闹哪样，什么苍天大地

**Comment by zhetengbiji** [comment]
HBuilderX 3.1.10 alpha 已发布

**Comment by a516117636** [comment]
> HBuilderX 3.1.10 alpha 已发布

uni.chooseLocation搜索结果完全按照距离排序，搜索结果依然不够理想。以下第一张图是uniapp的搜索结果，第二张是高德app的搜索结果，第三张是微信小程序端调用地图的搜索结果，uniapp的app端依然无法达到高德app或者微信小程序端的使用体验，高德app或者微信小程序端能够更快更好地搜索到想要的地点。
![1](https://user-images.githubusercontent.com/17865841/115108121-4e787400-9fa1-11eb-936b-13277176ea16.jpg)
![2](https://user-images.githubusercontent.com/17865841/115108133-5b956300-9fa1-11eb-847c-9b802f45135a.jpg)
![3](https://user-images.githubusercontent.com/17865841/115108146-6819bb80-9fa1-11eb-80dc-7c3d36cfb3b0.jpg)

**Comment by zhetengbiji** [comment]
是的，高德 SDK 开放接口搜索结果和高德自家产品的搜索结果比确实差很多，虽然腾讯开放 API 搜索结果也没有自家地图的好但也没有差这么多。后续框架通过配置不同的参数搜索看能否优化一些。

**Comment by a516117636** [comment]
> 是的，高德 SDK 开放接口搜索结果和高德自家产品的搜索结果比确实差很多，虽然腾讯开放 API 搜索结果也没有自家地图的好但也没有差这么多。后续框架通过配置不同的参数搜索看能否优化一些。

目前这样的搜索结果体验确实很糟糕。既然高德SDK开放接口搜索结果很差，那能否将uniapp默认的定位和地图服务改为百度地图，因为即使不谈SDK开放接口，高德地图app自身的搜索结果也不如百度地图，至于腾讯地图我了解不多。

**Comment by a516117636** [comment]
uni.chooseLocation搜索结果排序问题有进展了吗？现在搜索到的地点就是密密麻麻一堆，去里面翻好久才能找到自己想要的地点，望优化，希望能优化到微信小程序wx.chooseLocation()的效果。

**Comment by zhetengbiji** [comment]
> uni.chooseLocation搜索结果排序问题有进展了吗？现在搜索到的地点就是密密麻麻一堆，去里面翻好久才能找到自己想要的地点，望优化，希望能优化到微信小程序wx.chooseLocation()的效果。

预计今日发布的 alpha 版会携带相关优化

**Comment by zhetengbiji** [comment]
3.1.20.20210623-alpha 已发布
