### ISSUE TITLE
input框聚焦后自动全选内容，input属性selection-start和selection-end无效

### ISSUE THREAD

**Issue by MadiniGo** [dcloudio/uni-app#2534]
input属性selection-start和selection-end目前H5和APP下无效，uniapp没有办法直接操作DOM，想要自动选中input中的内容现在束手无策，focus事件中的event对象也不能操作如:e.currentTarget.select()

**Comment by StrivingRabbit** [comment]
1. 如果在H5，可以使用条件编译，进行dom操作设置dom的selectionStart、selectionEnd来设置选中
2. 暂时App端没有支持input选中

**Comment by StrivingRabbit** [comment]
已提交至 cb23882

**Comment by MadiniGo** [comment]
请问什么时候更新到Hbuilder上

**Comment by StrivingRabbit** [comment]
> 请问什么时候更新到Hbuilder上

最新版的alpha已经带上了，可以下载更新试试
