### ISSUE TITLE
音频组件控制

### ISSUE THREAD

**Issue by ming917** [dcloudio/uni-app#2538]
**新功能描述**
希望能修复一下这个问题

**现状及问题**
H5当调用销毁当前实例destroy()时会触发onCanplay事件

**补充信息**
H5版本由于this._audio.currentTime = 0导致的触发onCanplay事件
![QQ截图20210316141611](https://user-images.githubusercontent.com/50263719/111264281-1d61f800-861f-11eb-91be-f12037c4b125.png)

**Comment by zhetengbiji** [comment]
咋关了，还没发布呢

**Comment by ming917** [comment]
我以为解决了就关了。。。

**Comment by zhetengbiji** [comment]
修复了，还没发版，新版本发布后会自动关闭

**Comment by ming917** [comment]
这样子

**Comment by ming917** [comment]
需要我重开这个issue么，我没找到怎么重开。。。

**Comment by zhetengbiji** [comment]
> 需要我重开这个issue么，我没找到怎么重开。。。

没关系

**Comment by ming917** [comment]
谷歌浏览器可以重开，刚刚其他浏览器没得重开。。。

**Comment by daoying007** [comment]
来 uni-app 微信群交流吧，沟通更及时，加我微信（备注uni-app），拉你进群

更多各种程序员技术交流群（定期更新，长期有效），点这里扫码入群：https://www.yuque.com/docs/share/4c911e59-2da0-4c7b-9a60-e33d5a9ad671

![uni-app 微信群交流](https://user-images.githubusercontent.com/39725475/112411174-720c1e00-8d57-11eb-96f0-050bf531fc1b.jpg)
