### ISSUE TITLE
2.9.8版本在安卓7.0及以上无法使用uni.downloadFile+plus.runtime.install

### ISSUE THREAD

**Issue by Deepx-China** [dcloudio/uni-app#2540]
**问题描述**
```
download(info)
{
	let host = this.http.getHost();
	this.versionBtnAllow = false;
	this.versionUpdateTip = '正在下载补丁包...'
	const task = uni.downloadFile({
		url: host + info.download,  
		success: downloadResult => {
			if (downloadResult.statusCode === 200) {  
				this.versionUpdateTip = '下载成功，正在安装应用'
				plus.runtime.install(downloadResult.tempFilePath, () => {  
					this.versionUpdateTip = '安装完成，重启应用'
					plus.runtime.restart();  
				}, (e) => {  
					this.versionUpdateTip = '安装失败，安装包格式错误'
					this.versionBtnAllow = true
				});  
			} else {
				this.versionUpdateTip = '下载失败，请联系管理员'
				this.versionBtnAllow = true
			}
		},
		fail: err => {
			this.versionUpdateTip = '下载失败，请联系管理员'
			this.versionBtnAllow = true
		}
	});
	task.onProgressUpdate(res => {
		if (res.progress > 99) return
		that.versionUpdateTip = res.progress + ' %'
	})
} 
```
以上代码为离线打包，在安卓6.0.1的机器中执行成功，其余只是下载成功，执行安装报错：
`installWebApp /storage/emulated/0/Android/data/com.zfsw.pda.test/apps/__UNI__99E11CB/doc/uniapp_temp_1615886012488/download/ZFSCM_1.0.7.apk is Illegal path`

**系统信息**
- 发行平台: 5+ App
- 操作系统 Android 7.0 & Android10.0
- HBuilderX版本 2.9.8
- uni-app版本 如上
- 设备信息 华为P20、PDA

**Comment by StrivingRabbit** [comment]
可升级至最新版重试，经测试新版无此问题

**Comment by daoying007** [comment]
来 uni-app 微信群交流吧，沟通更及时，加我微信（备注uni-app），拉你进群

更多各种程序员技术交流群（定期更新，长期有效），点这里扫码入群：https://www.yuque.com/docs/share/4c911e59-2da0-4c7b-9a60-e33d5a9ad671

![uni-app 微信群交流](https://user-images.githubusercontent.com/39725475/112411174-720c1e00-8d57-11eb-96f0-050bf531fc1b.jpg)
