### ISSUE TITLE
向自定义组件传入具名插槽时，在 `<template>` 上使用 `v-slot` 或简写形式 `#` 无法继承插槽宽度和高度

### ISSUE THREAD

**Issue by waantony** [dcloudio/uni-app#2541]
**问题描述**

自定义组件中，有一个具名插槽，设定了这个插槽的宽度和高度，调用这个组件传入插槽时，如果使用旧的 `slot` 属性可以继承到宽度和高度，但在 `<template>` 上使用 `v-slot` 或简写形式 `#` 时， 无法继承插槽宽度和高度。

**复现步骤**

1. 在测试页面创建了一个 `index.vue` 和 `ImageBox` 组件；
2. `ImageBox` 组件代码：

```html
<template>
  <view class="image-box">
    <slot name="image" />
  </view>
</template>

<script>
export default {

}
</script>

<style>
.image-box {
  width: 300rpx;
  height: 200rpx;
  background: #aaa;
  margin-bottom: 20px;
}
</style>
```

3. 在 index.vue 中引入组件，使用三种方式传入具名插槽测试：

```html
<template>
  <view class="view-test">
    <ImageBox>
      <image
        slot="image"
        class="slot-img"
        src="https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=2211569814,2692541245&fm=11&gp=0.jpg"
      />
    </ImageBox>

    <ImageBox>
      <template v-slot:image>
        <image
          class="slot-img"
          src="https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=2211569814,2692541245&fm=11&gp=0.jpg"
        />
      </template>
    </ImageBox>

    <ImageBox>
      <template #image>
        <image
          class="slot-img"
          src="https://ss3.bdstatic.com/70cFv8Sh_Q1YnxGkpoWK1HF6hhy/it/u=2211569814,2692541245&fm=11&gp=0.jpg"
        />
      </template>
    </ImageBox>
  </view>
</template>

<script>
import ImageBox from './ImageBox'
export default {
  components: {
    ImageBox,
  },
}
</script>

<style>
.slot-img {
  width: 100%;
  height: 100%;
}
</style>
```

4. 结果：只有第一种使用旧的 `slot` 属性传入具名插槽时，能够继承到宽度和高度，后两种方式（在 `<template>` 上使用 `v-slot` 和简写形式 `#` ）均无法继承到宽度和高度，渲染效果如下：

![image](https://user-images.githubusercontent.com/42765545/111429224-a79b8080-8733-11eb-991d-2189d6b90ba7.png)

**预期结果**

在 `<template>` 上使用 `v-slot` 和简写形式 `#` 能够继承到宽度和高度。

**实际结果**

见复现步骤附图

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: windows 微信开发者工具
 - HBuilderX版本: 无，使用的 vue-cli 
 - uni-app版本: uni-app v2.9.8; uni-app cli v2.0.0-29820201110001
 - 设备信息: windows 微信开发者工具（iphone6）

**Comment by StrivingRabbit** [comment]
在微信小程序使用自定义组件，请遵循微信小程序的规范 [自定义组件](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html)

**Comment by waantony** [comment]
> 在微信小程序使用自定义组件，请遵循微信小程序的规范 [自定义组件](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html)

但是 uni-app 官网介绍了和 vue 官网一样的这两种写法，但没指出不支持用于小程序，通常这种情况我会当作 uni 在内部是支持了。
![image](https://user-images.githubusercontent.com/42765545/111749986-88385b00-88cd-11eb-9cfa-058e3eed0605.png)

**Comment by StrivingRabbit** [comment]
暂时请按照小程序的写法来，后面会持续优化

**Comment by daoying007** [comment]
来 uni-app 微信群交流吧，沟通更及时，加我微信（备注uni-app），拉你进群

更多各种程序员技术交流群（定期更新，长期有效），点这里扫码入群：https://www.yuque.com/docs/share/4c911e59-2da0-4c7b-9a60-e33d5a9ad671

![uni-app 微信群交流](https://user-images.githubusercontent.com/39725475/112411174-720c1e00-8d57-11eb-96f0-050bf531fc1b.jpg)

**Comment by cat-walk** [comment]
遇到了类似的问题，只有使用旧的 slot 属性，才不会额外创建出一个 view 元素破坏布局。
