### ISSUE TITLE
uniapp生成微信小程序代码时，自定义组件代码生成异常

### ISSUE THREAD

**Issue by 451761830** [dcloudio/uni-app#2544]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

uniapp生成微信小程序代码时，自定义组件代码生成异常，会生成自定义组件带bak的json文件；同时生成的js文件也有问题是空白的

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

![image](https://user-images.githubusercontent.com/48461152/111588291-4c829000-87fe-11eb-9757-72fd43a91e77.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by daoying007** [comment]
来 uni-app 微信群交流吧，沟通更及时，加我微信（备注uni-app），拉你进群

更多各种程序员技术交流群（定期更新，长期有效），点这里扫码入群：https://www.yuque.com/docs/share/4c911e59-2da0-4c7b-9a60-e33d5a9ad671

![uni-app 微信群交流](https://user-images.githubusercontent.com/39725475/112411174-720c1e00-8d57-11eb-96f0-050bf531fc1b.jpg)

**Comment by StrivingRabbit** [comment]
可以详细的描述一下你的问题吗？比如使用的cli还是HX？什么版本的？

**Comment by yiqianglin** [comment]
楼主这里有解决方案吗

**Comment by StrivingRabbit** [comment]
> 楼主这里有解决方案吗

你也碰到了这个问题吗？可以说一下你的HBuilder X版本号吗？

**Comment by thiszhong** [comment]
`cli 2.0.0-alpha-32620210901001`，我是按这个跑插件来着 https://ask.dcloud.net.cn/article/39290 。删除 dist，run dev，这时候是正常的，然后随便做点什么触发下热更新，控制台会报某个组件的 json 文件找不到，原因是名称里多了个 `.bak`，比如我这里是 `avatar.bak.json`，手动删除打包后文件名中的 `.bak`后就好了，只要不删 dist，之后也都是好的
