### ISSUE TITLE
使用renderjs写的下拉刷新，手机开启120Hz刷新卡顿

### ISSUE THREAD

**Issue by Tron1234** [dcloudio/uni-app#2546]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
如题
60Hz App正常
120Hz H5正常、App卡顿

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
下拉流畅使用

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等] App H5
 - 操作系统 [如 iOS 12.1.2、Android 7.0] Android 11
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]   3.1.4.20210305
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]  红米 k40 iphone8

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by daoying007** [comment]
来 uni-app 微信群交流吧，沟通更及时，uni-app等各种程序员技术交流群（定期更新，长期有效），点这里扫码入群：https://www.yuque.com/docs/share/4c911e59-2da0-4c7b-9a60-e33d5a9ad671
