### ISSUE TITLE
在编译的时候 怎么设置可以使某个文件保留原位置不编译

### ISSUE THREAD

**Issue by 623282611** [dcloudio/uni-app#2547]
**问题描述**
怎么设置可以使某个文件保留原位置不编译

**预期结果**
使某个文件保留原位置不编译，仍然保持文件之间的模块化引用

**Comment by 623282611** [comment]
> /static目录的作用就是干这个的

可是我这边的场景不是静态资源
js文件放在static目录里打包后确实还在static目录里，但这个js文件仍然被编译在common.js里了，我希望的是这个js不被编译，仍然保持使用打包前import的方式的引用

**Comment by StrivingRabbit** [comment]
可以尝试将此文件放入static中
此文件中不可使用 ESM 的语法
在其他地方使用 __non_webpack_require__(url) 引入此文件

**Comment by StrivingRabbit** [comment]
由于长时间未回复，此问题关闭
