### ISSUE TITLE
插件项目不能hack define和require，走这里，异常只能精准到页面，内部的多层依赖的报错无法精准

### ISSUE THREAD

**Issue by TuiMao233** [dcloudio/uni-app#2549]
插件项目不能hack define和require，走这里，异常只能精准到页面，内部的多层依赖的报错无法精准

![image](https://user-images.githubusercontent.com/49724027/111981397-993dd200-8b42-11eb-8ba4-fad120c42123.png)

**Comment by daoying007** [comment]
来 uni-app 微信群交流吧，沟通更及时，uni-app等各种程序员技术交流群（定期更新，长期有效），点这里扫码入群：https://www.yuque.com/docs/share/4c911e59-2da0-4c7b-9a60-e33d5a9ad671

**Comment by StrivingRabbit** [comment]
可以在详细的描述一下吗？

**Comment by TuiMao233** [comment]
在 UniApp Vue2 composition api 中使用自定义封装的hook函数async await代码中存在 try catch 将会导致该报错。

**Comment by zhetengbiji** [comment]
可以升级新版试一下：https://uniapp.dcloud.net.cn/tutorial/vue-composition-api.html

如仍有问题，详细描述重启开启
