### ISSUE TITLE
video组件会覆盖自定义导航

### ISSUE THREAD

**Issue by TeemoPeng** [dcloudio/uni-app#255]
**问题描述**
自定义导航，页面里的video会把导航栏盖住；

尝试了用cover-view组件放在video组件中，但是cover-view组件只能盖住video，最后还是会把导航栏盖住

**Comment by xiaoyucoding** [comment]
video 是原生组件层级较高，调整下 top 值之类的让出自定义导航栏的位置。

**Comment by LaoChen1994** [comment]
同问

**Comment by shangchuan123** [comment]
我也遇到了，就app端有这个问题，小程序，h5端可以，在app端视频会穿透自定义导航上面

**Comment by TeemoPeng** [comment]
您好，我现在无法回复您的信息，稍后会与您联系的！
