### ISSUE TITLE
dcloud和hbuildX都无法正常访问及登录

### ISSUE THREAD

**Issue by loveFemi** [dcloudio/uni-app#2550]
dcloud和hbuildX都无法正常访问及登录，网页提示404，IDE提示请检查网络设置

**Comment by zhetengbiji** [comment]
部分网络遇到 dcloud.net.cn 域名无法访问的，可以先手动修改一下 DNS，如：114.114.114.114。或者切换网络。

**Comment by daoying007** [comment]
来 uni-app 微信群交流吧，沟通更及时，uni-app等各种程序员技术交流群（定期更新，长期有效），点这里扫码入群：https://www.yuque.com/docs/share/4c911e59-2da0-4c7b-9a60-e33d5a9ad671

**Comment by hbcui1984** [comment]
如果依然有问题，请反馈所在省市地区及网络运营商，如贵州贵阳联通
