### ISSUE TITLE
按钮授权问题

### ISSUE THREAD

**Issue by Nick091608** [dcloudio/uni-app#2555]
<button
      class="wxq-btn loginWx"
      open-type="getUserInfo"
      @getuserinfo="wxGetUserInfo"
    >
      一键登录
    </button>
![image](https://user-images.githubusercontent.com/33303511/112569903-fd50e680-8e1f-11eb-883c-bca4645f0345.png)

    使用@getuserinfo="wxGetUserInfo" 方式，wxGetUserInfo方法报错
 使用bindgetphonenumber方式不会报错，但是官方不是说可以用@getuserinfo吗？
![image](https://user-images.githubusercontent.com/33303511/112570015-338e6600-8e20-11eb-9555-dfcd5f9f1fbb.png)

**Comment by StrivingRabbit** [comment]
methods中有wxGetUserInfo这个方法吗？或者拼写是否正确

**Comment by StrivingRabbit** [comment]
经测试没有此类问题
---
由于长时间未回复，此问题关闭
