### ISSUE TITLE
能否把uni声明文件中的返回void改为返回promise

### ISSUE THREAD

**Issue by social-uni** [dcloudio/uni-app#2556]
文档中说了，很多返回的都说promise，可是.d.ts文件中还写的 void

uni-app 对部分 API 进行了 Promise 封装，返回数据的第一个参数是错误对象，第二个参数是返回数据。

详细策略如下：

异步的方法，如果不传入 success、fail、complete 等 callback 参数，将以 Promise 返回数据。例如：uni.getImageInfo()
异步的方法且有返回对象，如果希望获取返回对象，必须至少传入一项 success、fail、complete 等 callback 参数。例如：uni.connectSocket()
同步的方法（即以 sync 结束），不封装 Promise。例如：uni.getSystemInfoSync()
以 create 开头的方法，不封装 Promise。例如：uni.createMapContext()
以 manager 结束的方法，不封装 Promise。例如：uni.getBackgroundAudioManager()

**Comment by StrivingRabbit** [comment]
[关于d.ts适配Promise返回](https://github.com/dcloudio/uni-app/issues/1770)

**Comment by StrivingRabbit** [comment]
可以升级 @dcloudio/types@3.3.0 试试看

**Comment by StrivingRabbit** [comment]
部分 api promise 化提示已支持，后续进度请跟踪 #3009 查看
