### ISSUE TITLE
unicloud未来是否考虑支持npm方式、非hbuilderx方式运行云函数？

### ISSUE THREAD

**Issue by social-uni** [dcloudio/uni-app#2557]
看官方在说明中说考虑安全问题不支持。

但个人认为这是伪命题，如果官方说为了打造闭环，玩垄断不支持其他形式，我认为这是实话。

但如果说是安全问题，完全有其他形式可以解决。

希望官方能提供一个npm包，支持配置秘钥的形式，支持npm等非bhuilder形式，使用unicloud

**Comment by hbcui1984** [comment]
暂无计划。
