### ISSUE TITLE
unicloud安全域名是否支持*通配符形式，我的开放云函数允许所有人调用怎么处理呢

### ISSUE THREAD

**Issue by social-uni** [dcloudio/uni-app#2558]
您好，我做的是一个开放的云函数，允许所有人调用，该怎么处理呢，我不知道我的用户域名有哪些，

我想配置成所有用户都可以使用

**Comment by wanganxp** [comment]
没有授权的前端不能直接callfunction到其他人的服务空间。你这个需求可以用云函数url化。

**Comment by social-uni** [comment]
> 没有授权的前端不能直接callfunction到其他人的服务空间。你这个需求可以用云函数url化。

那其实和 uni.request就没什么区别了

**Comment by Wangyaqi** [comment]
暂无计划支持通配符
