### ISSUE TITLE
webview的postMessage交互如何在vue单页应用上使用

### ISSUE THREAD

**Issue by zoeou** [dcloudio/uni-app#2560]
**新功能描述**
简洁描述你希望补充完善的增强功能
如题
**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by StrivingRabbit** [comment]
请详细的描述一下你的问题或需求

**Comment by zoeou** [comment]
如何在vue项目,引用https://js.cdn.aliyun.dcloud.net.cn/dev/uni-app/uni.webview.1.5.2.js

**Comment by zoeou** [comment]
如何在vue项目,引用https://js.cdn.aliyun.dcloud.net.cn/dev/uni-app/uni.webview.1.5.2.js

**Comment by zhetengbiji** [comment]
> 如何在vue项目,引用https://js.cdn.aliyun.dcloud.net.cn/dev/uni-app/uni.webview.1.5.2.js

可以放在 html 文件里，具体百度一下
