### ISSUE TITLE
nvue picker在 multiSelector 模式下报异常

### ISSUE THREAD

**Issue by zfjhui** [dcloudio/uni-app#2561]
**问题描述**
最小demo
`<picker mode="multiSelector"   :range="[[1,2],[3,4]]" > </picker>  `
控制台报如下bug
 TypeError: Cannot use 'in' operator to search for '0' in 0

**Comment by zhetengbiji** [comment]
uniapp 版本多少

**Comment by zfjhui** [comment]
> uniapp 版本多少

最新的3.1.6

**Comment by zfjhui** [comment]
app nvue 临时方案

> 
pages
`
"subNVues": [{
		"id": "z-picker",
		"path": "nvues/z-picker",
		"type": "popup",
		"style": {
			"height": "300px",
			"bottom": "0"
		}
	}]
`
z-picker
`
<template>
	<view bubble="true" @click.stop><component :is="is" v-if="is" @close="close" @success="success"></component></view>
</template>

<script>
export default {
	data() {
		return {
			is: null
		};
	},
	methods: {
		close() {
			uni.getCurrentSubNVue().hide();
		},
		success(a) {
			this.close();
			uni.$emit('z-picker-success', a);
		}
	},
	created() {
		uni.$on('z-picker-component', is => {
			this.is = is;
		});
		uni.getCurrentSubNVue().addEventListener('hide', function() {
			uni.$off('z-picker-success');
		});
	}
};
</script>
`
页面使用
uni.$emit('z-picker-component',自定义组件);
类似于vue开发时的模态框

**Comment by zhetengbiji** [comment]
临时解决办法， 写上 value 属性，如：``:value="[0,0]"``
