### ISSUE TITLE
【建议】unicloud能支持类似方法方式的调用，如果有计划能否告知预计何时

### ISSUE THREAD

**Issue by social-uni** [dcloudio/uni-app#2563]
清池社交软件联盟客服 2021/3/27 0:11:06
还有 ，我突然开个脑洞，你们能不能再提效一点。

清池社交软件联盟客服 2021/3/27 0:11:21
就是 别通过 callfunction去调用云函数

清池社交软件联盟客服 2021/3/27 0:11:33
起码让开发者使用起来

清池社交软件联盟客服 2021/3/27 0:11:38
你们可以再转一遍

清池社交软件联盟客服 2021/3/27 0:11:46
就是开发者用起来就跟调用方法一样

清池社交软件联盟客服 2021/3/27 0:12:03
你们去判断，如果开发者调用的是 云函数包里的方法

Heavensoft 2021/3/27 0:12:14
有意思，应该这样

清池社交软件联盟客服 2021/3/27 0:12:20
然后 hbuilder 解析编译的时候 ，给他转成

清池社交软件联盟客服 2021/3/27 0:12:28
callfunction的写法

清池社交软件联盟客服 2021/3/27 0:13:18
那就方便了很多了

清池社交软件联盟客服 2021/3/27 0:15:16
就是 希望你们能再解耦一下，把必须放在hbuilder的东西放在hbuilder

清池社交软件联盟客服 2021/3/27 0:15:48
比如 和可以把 client db 和unicloud拆开不

清池社交软件联盟客服 2021/3/27 0:16:01
就是 你看 其他的云函数，都是可以支持其他idea的

清池社交软件联盟客服 2021/3/27 0:16:37
我对serverless了解不多。但我今天在群里问 听说 其他云函数是可以支持其他idea的

清池社交软件联盟客服 2021/3/27 0:18:38
还有您说未来的发展目标，忘了回没回复您，我的未来发展目标，短期的就是 让社交软件做起来更简单。

清池社交软件联盟客服 2021/3/27 0:18:53
你们可能是让软件开发更简单，我想让社交软件开发更简单。

清池社交软件联盟客服 2021/3/27 0:19:13
我也想有你们那种目标，可是目前没你们那个体量，所以就先把目标定的小一点

Heavensoft 2021/3/27 0:26:46
感谢你的建议，我刚才一直在想这个事情，
比如有个云函数叫aaa
前端代码可以这么写，
var cf = uniCloud.function("aaa")
cf.get()

这样确实感觉很酷

清池社交软件联盟客服 2021/3/27 0:27:20
额，还不是这样

清池社交软件联盟客服 2021/3/27 0:28:54

清池社交软件联盟客服 2021/3/27 0:29:00
和您这个好像也差不多

清池社交软件联盟客服 2021/3/27 0:29:04
不过 我那个是全局注册的

清池社交软件联盟客服 2021/3/27 0:29:23

清池社交软件联盟客服 2021/3/27 0:29:36
再高级点

清池社交软件联盟客服 2021/3/27 0:30:50

清池社交软件联盟客服 2021/3/27 0:30:55

清池社交软件联盟客服 2021/3/27 0:31:02

清池社交软件联盟客服 2021/3/27 0:31:17
就是 我这个方法是写在 云函数里面的。

清池社交软件联盟客服 2021/3/27 0:31:48

清池社交软件联盟客服 2021/3/27 0:32:09
首先解析这个，然后找到他来自于userAPI，然后 解析

清池社交软件联盟客服 2021/3/27 0:32:12

清池社交软件联盟客服 2021/3/27 0:32:32
您知道这个UserAPI来自云函数

清池社交软件联盟客服 2021/3/27 0:32:38
然后就可以给他转义一下。

Heavensoft 2021/3/27 0:32:44
嗯，import也是一种方法

清池社交软件联盟客服 2021/3/27 0:32:52
然后 可以有个地方 全局配置一下 云函数 的地址啥的

清池社交软件联盟客服 2021/3/27 0:33:15
那样 用起来 方便的不行 爽到飞起

清池社交软件联盟客服 2021/3/27 0:35:08
https://github.com/dcloudio/uni-app/issues/2558

清池社交软件联盟客服 2021/3/27 0:35:08
还有 我有个这个问题

清池社交软件联盟客服 2021/3/27 0:35:12
unicloud安全域名是否支持*通配符形式，我的开放云函数允许所有人调用怎么处理呢

清池社交软件联盟客服 2021/3/27 0:35:25
就是 我想做个开放云函数，谁都可以调用的那种

清池社交软件联盟客服 2021/3/27 0:35:48
我看 控制台 能配置域名，但是我不知道我的用户是谁，没办法配置域名，能配置允许所有人调用吗

Heavensoft 2021/3/27 0:37:36
这个方案很酷，虽然开发效率还是没有clientDB高，但可以组合使用。我感觉值得投入去搞，我们内部会好好讨论下这个事情。感谢

Heavensoft 2021/3/27 0:38:19
以saas方式开放给其他开发者？

清池社交软件联盟客服 2021/3/27 0:38:24
是的

清池社交软件联盟客服 2021/3/27 0:38:40
我想通过配置收费

清池社交软件联盟客服 2021/3/27 0:38:48
客户不需要私有化部署

清池社交软件联盟客服 2021/3/27 0:38:56
我想做的是类似高德api这种

清池社交软件联盟客服 2021/3/27 0:39:03
现在hbuilder是私有化部署这种

清池社交软件联盟客服 2021/3/27 0:39:27
但我觉得云函数这种东西，客户不需要修改开发的东西，完全可以 通过api方式

清池社交软件联盟客服 2021/3/27 0:39:57
云函数，客户需要修改，你就没办法收费卖，因为你卖出去就源码泄露了

清池社交软件联盟客服 2021/3/27 0:40:32
云函数，客户不需要修改，只是私有化部署，和你部署在自己服务，让客户直接调用，效果一样。

清池社交软件联盟客服 2021/3/27 0:40:39
客户还省了私有化部署了

Heavensoft 2021/3/27 0:40:45
为什么这么考虑呢？
我感觉更好的方式是，把你的插件，让开发者可以部署到自己的项目里，你除了几个要保护的云函数加密后，其他不加密，开发者想要改界面或加点其他什么定制，可以自由的处理，这样比saas对开发者更友好。
另外saas有个巨大的麻烦是需要自己处理内容安全，如果你起量了，公安会天天请你喝茶。一旦有一个租户的内容出问题，你的全站会被公安ban掉

清池社交软件联盟客服 2021/3/27 0:41:29
其实我觉得uni也可以考虑这个方向

清池社交软件联盟客服 2021/3/27 0:41:33
就是打通数据

清池社交软件联盟客服 2021/3/27 0:41:39
我在做的是打通数据这个事

清池社交软件联盟客服 2021/3/27 0:41:44
要做一个数据中心

清池社交软件联盟客服 2021/3/27 0:41:54
就比如 你们的uni-id

Heavensoft 2021/3/27 0:42:27
uni-id就是呀，开发者自己的app有账户体系，你的插件也支持uni-id，就可以直接嵌入他的app里了

清池社交软件联盟客服 2021/3/27 0:42:29
如果你们有了 14亿用户的数据，可以所有用uni开发的app，都让用户使用uni授权登录

清池社交软件联盟客服 2021/3/27 0:42:43
但是你们的用户都是开发者把

清池社交软件联盟客服 2021/3/27 0:42:48
没什么 c端用户吧

清池社交软件联盟客服 2021/3/27 0:43:07
你们有把 12亿日活用户 加到这个uni-id体系么

清池社交软件联盟客服 2021/3/27 0:43:19
还是那800w开发者 的uni-id账户体系

清池社交软件联盟客服 2021/3/27 0:43:32
你们这个账户体系 只是你们公司自己用户

清池社交软件联盟客服 2021/3/27 0:43:48
我说你们可以打通 uni体系，内所有app的客户

Heavensoft 2021/3/27 0:43:49
没有。我们不搞saas，每个开发者独立租云，出了事情各封各的

清池社交软件联盟客服 2021/3/27 0:44:02
我不怕做大

清池社交软件联盟客服 2021/3/27 0:44:10
就怕做不大

清池社交软件联盟客服 2021/3/27 0:44:33
内容安全 是社交软件要考虑的问题，微博 不就量挺大的么

清池社交软件联盟客服 2021/3/27 0:44:59
我们可以把每个软件的内容审核权，下放给每个软件

Heavensoft 2021/3/27 0:45:12
我们会让开发者自己管理数据，但数据的规范是我们出的标准，这样各种插件可以围绕规范协作。
就这样，公安还天天盯着我们

Heavensoft 2021/3/27 0:45:43
微博有非常庞大的内容安全审核团队，你这样做就做重了

Heavensoft 2021/3/27 0:45:53
不利于起步

清池社交软件联盟客服 2021/3/27 0:46:21
我觉得我流量起来的时候我就有钱了，有钱了就能解决内容安全问题

清池社交软件联盟客服 2021/3/27 0:46:26
就怕量起不来

清池社交软件联盟客服 2021/3/27 0:47:04
搞搞试试吧，遇到问题解决问题，解决不了再换方向

清池社交软件联盟客服 2021/3/27 0:47:58
其实我理解 client-db应该还 graphql差不多吧，就是 前端直接操作数据库数据。

清池社交软件联盟客服 2021/3/27 0:48:09
然后client-db可以和 前端组件结合

清池社交软件联盟客服 2021/3/27 0:48:12
组成数据组件

清池社交软件联盟客服 2021/3/27 0:49:06
不知道好不好做，数据+组件的组成方式，操作方式比较多，可能比较消耗人力，不知道能不能找到性价比比较高的那个点

Heavensoft 2021/3/27 0:49:15
有参考graphql

清池社交软件联盟客服 2021/3/27 0:49:55
unicloud安全域名是否支持*通配符形式，我的开放云函数允许所有人调用怎么处理呢

清池社交软件联盟客服 2021/3/27 0:50:02
这个通配符的功能，你们会考虑吗

清池社交软件联盟客服 2021/3/27 0:50:16
就是 我想做 saas云函数，会考虑支持吗

Heavensoft 2021/3/27 0:50:35
云函数url化可以实现
这个限制是云厂商限制的

清池社交软件联盟客服 2021/3/27 0:50:53
调用者域名的限制

清池社交软件联盟客服 2021/3/27 0:50:58
是云厂商限制的么

Heavensoft 2021/3/27 0:51:02
是

清池社交软件联盟客服 2021/3/27 0:51:06
好吧那没办法

清池社交软件联盟客服 2021/3/27 0:52:04
那 client-db和 unicloud能解耦吗

清池社交软件联盟客服 2021/3/27 0:52:47
这个我也没想好解决方案

清池社交软件联盟客服 2021/3/27 0:55:46
展示 (ui组件-data-com) ->  业务（unicloud）->  数据(client-db)

清池社交软件联盟客服 2021/3/27 0:56:04
把这三个解耦

清池社交软件联盟客服 2021/3/27 0:56:14
unicloud单抽出去

清池社交软件联盟客服 2021/3/27 0:56:25
会有用户有这种需要么

清池社交软件联盟客服 2021/3/27 0:56:56
普通用户不知道，我有这种需求，是因为 我不用 client-db

清池社交软件联盟客服 2021/3/27 0:57:09
哦  有可能会有这种需求

清池社交软件联盟客服 2021/3/27 0:58:15
uni组件- > 业务 (unicloud)-> client-db
                                           -> 用户自有数据库

清池社交软件联盟客服 2021/3/27 0:58:40
如果 用户 有时候不使用 client-db 而是使用自有数据， unicloud就可以 拿出去了

清池社交软件联盟客服 2021/3/27 3:39:28
我感觉想到解决办法了，首先提供一个upm的包管理工具，兼容npm，只不过都是uni平台的包。

清池社交软件联盟客服 2021/3/27 3:40:27
然后用户upm安装付费包的时候提示用户需要登陆，就类似git clone包的时候要登录

清池社交软件联盟客服 2021/3/27 3:41:08
登陆以后用户买没买这个upm的包，买了就能安没买就不能安。

清池社交软件联盟客服 2021/3/27 3:41:37
安装的都是加密混淆过的代码

清池社交软件联盟客服 2021/3/27 3:42:08
这样安全保证了，收费保证了，也和hbuilder解耦了

清池社交软件联盟客服 2021/3/27 3:42:49
然后jql无法的问题，就无所谓了吗，他非用webstorm开发，不支持无法就不支持被

清池社交软件联盟客服 2021/3/27 3:43:06
就相当于他在用txt开发程序一样

清池社交软件联盟客服 2021/3/27 3:43:37
vim不也没高亮语法提示嘛

清池社交软件联盟客服 2021/3/28 13:22:34
有时间回复下么

**Comment by Wangyaqi** [comment]
现有的callFunction写法已经很简单了，更上层的封装可以由用户自己实现

**Comment by social-uni** [comment]
> 现有的callFunction写法已经很简单了，更上层的封装可以由用户自己实现

那不是更简单，更利于开发者使用嘛，为什么要拒绝这种建议呢，感觉工作量也是可控范围

**Comment by Wangyaqi** [comment]
我们看下是不是在插件市场提供一下有这种能力的插件

**Comment by wanganxp** [comment]
云对象已经上线：https://uniapp.dcloud.io/uniCloud/cloud-obj.html

**Comment by social-uni** [comment]
> 云对象已经上线：https://uniapp.dcloud.io/uniCloud/cloud-obj.html



> 我们看下是不是在插件市场提供一下有这种能力的插件

[云对象已经上线：https://uniapp.dcloud.io/uniCloud/cloud-obj.html](https://github.com/dcloudio/uni-app/issues/2563#issuecomment-1106559397)

这就是进步，不断的追求更好，而不是自我满足
