### ISSUE TITLE
markdown 不支持打开链接

### ISSUE THREAD

**Issue by xgqfrms** [dcloudio/uni-app#2566]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by xgqfrms** [comment]
# markdown 不支持打开链接

**Comment by zhetengbiji** [comment]
> # markdown 不支持打开链接
> ![image](https://user-images.githubusercontent.com/7291672/113085285-1f78a900-9212-11eb-8242-c711bad7ee60.png)

按住 alt 键点击

**Comment by xgqfrms** [comment]
# vscode 是 command，但是放上有提示呀


> 感觉 hbuilder 一点都不好用，Haiyaaaa!


![image](https://user-images.githubusercontent.com/7291672/113098133-a9347080-922a-11eb-841d-d539245bb0c8.png)
