### ISSUE TITLE
Hbuilderx 3.1.5 使用uni.chooseLocation无法加载界面

### ISSUE THREAD

**Issue by Deepx-China** [dcloudio/uni-app#2569]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  Android 离线打包
2.  启动 '点击App'
3. 点击  '按钮'，调用uni.chooseLocation API
4. 查看弹出界面，为图中效果，无报错，无返回

```
chooseLocation() {
    uni.chooseLocation({
       success: res => {
           console.log(res)
       }
   })
}
```

**实际结果**

**系统信息:**
 - 发行平台:  Android App
 - 操作系统 : Android 7.0、Android 10
 - HBuilderX: 3.1.5
 - 设备信息: PDA、huawei p20

![微信图片_20210331153031](https://user-images.githubusercontent.com/20198428/113107094-126db100-9236-11eb-8477-bc06a0125008.jpg)
![微信图片_20210331153039](https://user-images.githubusercontent.com/20198428/113107096-14377480-9236-11eb-830e-88d17fe3a104.jpg)

**Comment by StrivingRabbit** [comment]
离线打包配置地图了吗？

**Comment by Deepx-China** [comment]
> 离线打包配置地图了吗？

我配置了Key，可以获取定位，还需要其他的配置吗？

**Comment by JiakunXu** [comment]
![image](https://user-images.githubusercontent.com/2619626/113474204-1a7d5900-94a1-11eb-8895-47dd70f6c42a.png)

**Comment by Deepx-China** [comment]
@JiakunXu  我在提交问题之前，已配置过该aar文件

**Comment by Deepx-China** [comment]
此问题不是Uniapp的BUG，是我在引入lib包时有缺少，Demo里的必须全部引入

**Comment by JiakunXu** [comment]
少 weex_amap-release.aar
app 地图用的是 nvue 页面

**Comment by JiakunXu** [comment]
少 weex_amap-release.aar
app 地图用的是 nvue 页面

**Comment by Deepx-China** [comment]
> 少 weex_amap-release.aar
> app 地图用的是 nvue 页面

可能是吧，但我的页面是vue的
