### ISSUE TITLE
echarts在chrome上可以正常运行，在手机上跑不出来

### ISSUE THREAD

**Issue by oujin-nb** [dcloudio/uni-app#257]
**问题描述**
echarts在chrome上可以正常运行，在手机上跑不出来

**复现步骤**
[复现问题的步骤]
这是echarts的一个简单demo，在h5上可以正常运行，但是在安卓测试机上的时候就跑不出来了
`<template>
	<view>
		<div id="myChart" class='chart_1'></div>
	</view>
</template>
<script>
	export default {
		mounted() {
			this.drawLine();
		},
		data() {
			return {};
		},
		methods: {
			drawLine() {
				// 基于准备好的dom，初始化echarts实例
				let myChart = this.$echarts.init(document.getElementById('myChart'))
				// 绘制图表
				myChart.setOption({
					title: {
						text: '在Vue中使用echarts'
					},
					tooltip: {},
					xAxis: {
						data: ["衬衫", "羊毛衫", "雪纺衫", "裤子", "高跟鞋", "袜子"]
					},
					yAxis: {},
					series: [{
						name: '销量',
						type: 'bar',
						data: [5, 20, 36, 10, 10, 20]
					}]
				});
			}
		}
	}
</script>

<style lang="scss">
	.chart_1 {
		height: 300upx;
		width: 300upx
	}
</style>
`

**预期结果**
多端正常运行

**实际结果**
app无法支持

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 Android 8.1
 - HBuilderX版本 HBuilderX.1.6.2.20190220
 - 设备信息 [vivox21]

**Comment by zhetengbiji** [comment]
标准 echart 仅能用于 H5，跨端请使用改良的 uchart 或 f2，插件市场有：https://ext.dcloud.net.cn/search?q=%E5%9B%BE%E8%A1%A8。
hello uni-app里也有echart示例，注意如果在部分平台报错的话，使用hello uni-app里面的js（如果自己引用其他版本报错的，参考 hello uni-app 里面的修改一下）
