### ISSUE TITLE
离线打包ios App，苹果登录报错

### ISSUE THREAD

**Issue by pdongxiang** [dcloudio/uni-app#2570]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
1、上架app store需配置苹果登录（Sign In with Apple），按照文档勾选苹果登录以及配置好相应资源
离线打包测试，通过uni.getProvider获取的信息"service":"oauth","provider":["weixin","apple"]，说明可以使用苹果登录。
但是uni.login请求苹果登录报错，{"errMsg":"login:fail Unknown","errCode":1000,"code":1000}
2、使用云打包的自定义基座可以调起苹果登录，但是我的app有一些功能不是uni-app框架的，所以必须使用离线打包的方式提交审核，但是目前离线打包的app苹果登录出现未知错误

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码]
```
uni.getProvider({
	service: 'oauth',
	success: res => {
		console.log('getProvider',  JSON.stringify(res.provider))
	},
	fail: res => {
		console.error('getProvider failed', JSON.stringify(res))
	},
})
uni.login({
	provider: 'apple',
	success:  res => {
		console.log('appleLogin success', JSON.stringify(res))
		if (res.code) {
			this.getUserInfo(res)
		} 
	},
	fail: res => {
		console.error('appleLogin failed', JSON.stringify(res))
	},
})

```

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
获取用户登录数据

**实际结果**
[这里请贴上你的报错截图或文字]
苹果登录报错 {"errMsg":"login:fail Unknown","errCode":1000,"code":1000}

**系统信息:**
 - 发行平台：App Store
 - 操作系统 : ios 14.4
 - HBuilderX版本 : 2.9.8
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 : IPHONE 12

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Tron1234** [comment]
我是用离线打包的一切正常

**Comment by ArrayDC** [comment]
离线打包配置请参考这里：https://nativesupport.dcloud.net.cn/AppDocs/usemodule/iOSModuleConfig/oauth?id=%e8%8b%b9%e6%9e%9c%e7%99%bb%e5%bd%95
