### ISSUE TITLE
v-for中使用methods方法，与v-for数据无关的data中数据一变化，methods就会执行一次

### ISSUE THREAD

**Issue by tansj526** [dcloudio/uni-app#2574]
**问题描述**
v-for中使用methods方法，与v-for数据无关的data数据一变化，methods就会执行一次

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

```
data() {
    return {
      testList: [1,2,3,4],
      count: 1,
    }
  }
  
  getLog(index) {
    console.log(index);
  }
  
  setLog() {
    this.count +=1;
  }
  
<div class="list" v-for="(item, index) in testList" :key="index">
  {{ getLog(index) }}
</div>

<div @click="setLog">点一下getLog就会打印</div>
```

**预期结果**
希望不要一直触发methods方法

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
使用HX3.1.6测试了一下，未发现此问题

**Comment by StrivingRabbit** [comment]
由于长时间未回复，此问题关闭
