### ISSUE TITLE
uni.getStorageInfoSync() app端获取信息不完全

### ISSUE THREAD

**Issue by Tron1234** [dcloudio/uni-app#2577]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
![image](https://user-images.githubusercontent.com/47961959/113499873-1e19ea00-954c-11eb-9cca-07f7f08a4797.png)
1.uni.getStorageInfoSync()获取的
["tempLocation", "alreadyNum", "contactRecord", "tempLocationsimpleCache", "customerFile", "customerRecord",
	"isShowChangeRole", "contactFile", "tabIndex", "role", "uarea_prompry_ae1f2970368944dcb9d67fbf75f0a383",
	"uarea_prompry_ae1f2970368944dcb9d67fbf75f0a383simpleCache", "userInfo"
]
2.plus.storage.getAllKeys()
["tempLocation", "alreadyNum", "contactRecord", "tempLocationsimpleCache", "customerFile", "customerRecord",
	"isShowChangeRole", "contactFile", "token", "tabIndex", "role", "uarea_prompry_ae1f2970368944dcb9d67fbf75f0a383",
	"uarea_prompry_ae1f2970368944dcb9d67fbf75f0a383simpleCache", "userInfo"
]

很明显上面缺失了token,巨坑（吐血中....）

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]    3.1.4.20210305
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
详细描述一下

**Comment by Tron1234** [comment]
这个写的很明白了，在app端用H5plus获取storage中的信息是完全的，uni.getStorageInfoSync()获取的信息缺失我存储的token字段的信息
