### ISSUE TITLE
项目只需生成H5页面，可以直接引入第三方的vue插件吗

### ISSUE THREAD

**Issue by AlanKnightly** [dcloudio/uni-app#2578]
请教大家，在官网查了好久，没看到关于这个问题的直接答案。
如果我只用uni-app来开发打包生成一组h5页面，确定不需要打包成小程序/app。
那我们是可以直接引入vant ui 的web组件使用吗？
我自己试了下打包是ok的，但不确定会有什么需要注意的地方或风险。

希望开发者或尝试过的同学能提供一个切实的回复，万谢。

**Comment by StrivingRabbit** [comment]
如果只是H5，和只用vue开发没有什么差别

此类问题可以去官方群中或者问题社区发帖子，此处做关闭处理
