### ISSUE TITLE
支付宝小程序报toJSON警告

### ISSUE THREAD

**Issue by rookie2435** [dcloudio/uni-app#2579]
用的hello uniapp示例项目，支护宝开发工具v2.0，界面一直报toJSON警告

Property or method "toJSON" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

**Comment by zhetengbiji** [comment]
参考 https://forum.alipay.com/mini-app/post/36301014
