### ISSUE TITLE
暂不支持 v-bind="" 用法

### ISSUE THREAD

**Issue by brucehelen** [dcloudio/uni-app#258]
**问题描述**
Module build failed (from ./node_modules/vue-loader/lib/loaders/templateLoader.js):
暂不支持 v-bind="" 用法

**复现步骤**
源代码用到了v-bind，这个功能现在还不能支持吗？

```bash
npm run dev:mp-weixin
```

```html
        <div v-for="(item, index) in list" :key="index">
          <property-item v-bind="item" @itemclick="onItemClick" @follow="onFollow" />
        </div>
```

**预期结果**
希望支持v-bind指令

**Comment by fxy060608** [comment]
理论上可以支持，但是会带来性能损失，建议可以调整组件设计

**Comment by brucehelen** [comment]
通过常规方式来引用

**Comment by WHATSAF** [comment]
不懂为什么会带来性能损失，如果我一个组件有n多个props，那我该怎么绑定？

**Comment by eno-Zeng** [comment]
v-bind 在编译的时候就会被解析吧, 性能损失也应该只是编译时而不是运行时, 编译时的对这点性能根本不敏感

**Comment by zhetengbiji** [comment]
> v-bind 在编译的时候就会被解析吧, 性能损失也应该只是编译时而不是运行时, 编译时的对这点性能根本不敏感

编译时能推断的类型有限

**Comment by lzw1604748707** [comment]
希望还是可以支持这个功能，哪怕不能用v-bind="$attrs"  v-bind="$props" 也可以
不然基于第三方的二次封装，甚至三次封装，会变得很让人难受 😞  
封吧我要绑定一大串值，不封吧，又有很多地方复用 😑

**Comment by zhetengbiji** [comment]
> 希望还是可以支持这个功能，哪怕不能用v-bind="$attrs" v-bind="$props" 也可以
> 不然基于第三方的二次封装，甚至三次封装，会变得很让人难受 😞
> 封吧我要绑定一大串值，不封吧，又有很多地方复用 😑

受环境限制（小程序原生组件无类似特性），实现起来曲线较大，而收益较小（如包体积增大以及部分用法的兼容问题等），所以目前优先级较低

**Comment by yourVictor** [comment]
感觉还是很有必要实现

**Comment by zhetengbiji** [comment]
> 感觉还是很有必要实现

说出得出此结论的具体理由，可以增加权重。

**Comment by LeiZhang0724** [comment]
uniapp 打包发布h5可以，当时打包发布微信小程序报错，Error: 暂不支持 v-bind="" 用法。不知道怎么解决，是不是配置错了
