### ISSUE TITLE
“ts 中 UniApp.IntersectionObserver.relativeTo 不应该返回 void” 的问题并没有被修复

### ISSUE THREAD

**Issue by ishowman** [dcloudio/uni-app#2580]
原 issue 链接：https://github.com/dcloudio/uni-app/issues/2513

已更新为
```
"name": "@dcloudio/types",
 "version": "2.0.25",
```
仍然存在这些错误问题。

是示例代码有问题还是类型定义有问题？？

**Comment by ishowman** [comment]
@StrivingRabbit  要不你们把类型库开源吧，可以让他人修复。已经影响了开发进度了

**Comment by zhetengbiji** [comment]
> @StrivingRabbit 要不你们把类型库开源吧，可以让他人修复。已经影响了开发进度了

之前开源在 https://github.com/dcloudio/DefinitelyTyped 不过是由工具自动生成的，不可直接修改，后续未继续更新

进度的问题，可以在业务层通过 n 中方法覆盖

**Comment by zhetengbiji** [comment]
> > @StrivingRabbit 要不你们把类型库开源吧，可以让他人修复。已经影响了开发进度了
> 
> 之前开源在 https://github.com/dcloudio/DefinitelyTyped 不过是由工具自动生成的，不可直接修改，后续未继续更新此仓库
> 
> 进度的问题，可以在业务层通过 n 中方法覆盖

**Comment by StrivingRabbit** [comment]
relativeTo返回的还是void？那你在`node_modules\@dcloudio\types\uni-app\uni.d.ts`中搜索`IntersectionObserver`，找到 interface IntersectionObserver。下面的 `relativeTo` 方法是不是返回值是错误的？

**Comment by ishowman** [comment]
> relativeTo返回的还是void？那你在`node_modules\@dcloudio\types\uni-app\uni.d.ts`中搜索`IntersectionObserver`，找到 interface IntersectionObserver。下面的 `relativeTo` 方法返回值是void吗？

对

**Comment by StrivingRabbit** [comment]
> > relativeTo返回的还是void？那你在`node_modules\@dcloudio\types\uni-app\uni.d.ts`中搜索`IntersectionObserver`，找到 interface IntersectionObserver。下面的 `relativeTo` 方法返回值是void吗？
> 
> 对

截图我瞅瞅，我单独更新了一下，我这里已经变更为返回 `IntersectionObserver` 了

**Comment by ishowman** [comment]
> > > relativeTo返回的还是void？那你在`node_modules\@dcloudio\types\uni-app\uni.d.ts`中搜索`IntersectionObserver`，找到 interface IntersectionObserver。下面的 `relativeTo` 方法返回值是void吗？
> > 
> > 
> > 对
> 
> 截图我瞅瞅，我单独更新了一下，我这里已经变更为返回 `IntersectionObserver` 了

重启后可以了，但按示例代码中 `uni.createIntersectionObserver(this)` createIntersectionObserver 第二个参数应该是可选参数。看下是类型写错还是文档示例代码写错了

**Comment by StrivingRabbit** [comment]
> > > > relativeTo返回的还是void？那你在`node_modules\@dcloudio\types\uni-app\uni.d.ts`中搜索`IntersectionObserver`，找到 interface IntersectionObserver。下面的 `relativeTo` 方法返回值是void吗？
> > > 
> > > 
> > > 对
> > 
> > 
> > 截图我瞅瞅，我单独更新了一下，我这里已经变更为返回 `IntersectionObserver` 了
> 
> 重启后可以了，但按示例代码中 `uni.createIntersectionObserver(this)` createIntersectionObserver 第二个参数应该是可选参数。看下是类型写错还是文档示例代码写错了

好的

**Comment by StrivingRabbit** [comment]
> > > > relativeTo返回的还是void？那你在`node_modules\@dcloudio\types\uni-app\uni.d.ts`中搜索`IntersectionObserver`，找到 interface IntersectionObserver。下面的 `relativeTo` 方法返回值是void吗？
> > > 
> > > 
> > > 对
> > 
> > 
> > 截图我瞅瞅，我单独更新了一下，我这里已经变更为返回 `IntersectionObserver` 了
> 
> 重启后可以了，但按示例代码中 `uni.createIntersectionObserver(this)` createIntersectionObserver 第二个参数应该是可选参数。看下是类型写错还是文档示例代码写错了

已改，后续会更新，你先手动处理一下，或者传一个空对象
