### ISSUE TITLE
uni-app内部使用了uni-ui打包后报错

### ISSUE THREAD

**Issue by moxaIce** [dcloudio/uni-app#2586]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
![image](https://user-images.githubusercontent.com/22164796/114500309-56ab7900-9c5a-11eb-8417-c8116a35805a.png)
![image](https://user-images.githubusercontent.com/22164796/114500406-878bae00-9c5a-11eb-84ad-80df61ec24d1.png)

**复现步骤**
[复现问题的步骤]
正常在代码里面引用uni-ui组件

[或者可以直接贴源代码]

**预期结果**
正常只会打出一个文件夹并带有json

**实际结果**
多了一个文件夹，且另一个文件夹没写入json

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by moxaIce** [comment]
mp-weixin 在开发者工具会有这个问题。

**Comment by StrivingRabbit** [comment]
在什么项目中使用？怎么引用的uni-ui?

**Comment by webxmsj** [comment]
同问

**Comment by webxmsj** [comment]
> mp-weixin 在开发者工具会有这个问题。

你好这个问题解决了吗？
