### ISSUE TITLE
腾讯微信新增了getUserProfile接口，getUserInfo接口已阵亡

### ISSUE THREAD

**Issue by coco163** [dcloudio/uni-app#2587]
垃圾微信新增了getUserProfile接口
Uni什么时候能支持？？？

https://developers.weixin.qq.com/community/develop/doc/000cacfa20ce88df04cb468bc52801

![image](https://user-images.githubusercontent.com/5829550/114528856-f5949d00-9c7b-11eb-80eb-35821bf0e6b3.png)

**Comment by 6ok** [comment]
已经支持，如果项目使用的Typescript的话类型还没有更新

**Comment by 6ok** [comment]
uni.getUserProfile({  
                   desc:'Wexin', 
                   success:res=>{  
                       console.log(res)  
                   },  
                   fail:err=>{  
                       console.log(err)  
                   }  
               })

**Comment by rfirefly** [comment]
open-type="getUserInfo" button的还不支持吧？

**Comment by coco163** [comment]
文档还没更新吧

**Comment by zhetengbiji** [comment]
https://uniapp.dcloud.io/api/plugins/login?id=getuserprofile

**Comment by 6ok** [comment]
@dcloudio/types 这个包的repo在哪?

**Comment by zhetengbiji** [comment]
> @dcloudio/types 这个包的repo在哪?

此包是由工具自动生成的，已更新
