### ISSUE TITLE
使用 vue-cli 方式创建的 uniapp 微信小程序，在 pages.json 中配置 condition 不生效

### ISSUE THREAD

**Issue by evestorm** [dcloudio/uni-app#2590]
**问题描述**
使用 vue-cli 方式创建的 uniapp 微信小程序，在 pages.json 中配置 condition 不生效。

**复现步骤**

1.  npm run dev:mp-weixin
2. 打开微信开发者工具
3. 顶部正中间的编译模式中并没有出现相应的配置

```json
{
  "pages": [
    //pages数组中第一项表示应用启动页，参考：https://uniapp.dcloud.io/collocation/pages
    {
      "path": "pages/home/home",
      "style": {
        "navigationBarTitleText": "首页"
      },
    {
      "path": "pages/me/me",
      "style": {
        "navigationBarTitleText": "我的"
      },
  },
  "condition": { //模式配置，仅开发期间生效
    "current": 0, //当前激活的模式（list 的索引项）
    "list": [
      {
        "name": "mall",
        "path": "/pages/me/me"
      }
    ]
  }
}
```

**预期结果**

和官网预期类似：

![image](https://user-images.githubusercontent.com/18142851/114822180-43341580-9df4-11eb-9a43-2b47df6cbf25.png)

**实际结果**

![image](https://user-images.githubusercontent.com/18142851/114822219-4f1fd780-9df4-11eb-8f4b-03b186db31ec.png)

并没有出现配置的模式

**系统信息:**
 - 发行平台: 微信小程序
 - 环境: 
    - OS: macOS 11.2.1
    - Node: 14.15.1
    - npm: 6.14.8
 - IDE: VSCode
 - uni-app版本:
    - uni-app v3.1.8
    - uni-app cli v2.0.0-31820210406002

**Comment by StrivingRabbit** [comment]
测试了一下没有发现此问题。dist/dev/weixin/project.config.json中有没有miniprogram项？

**Comment by evestorm** [comment]
@StrivingRabbit 

我没有用 HBuilderX 打包，直接终端运行 `npm run dev:mp-weixin` 生成的，生成文件的目录结构中没有 `project.config.json` ，只有 `app.json`：

```shell
dist/dev/mp-weixin
├── app.js
├── app.json
├── app.wxss
├── common
├── components
├── pages
├── sitemap.json
└── static
    ├── tabbar
    ├── totast
    └── workbench
```

并且 `app.json` 中也没有 `condition` 属性。

**Comment by evestorm** [comment]
这个issue可以关闭了，今天有空我通过 cli 方式又重新创建了个demo做了测试，发现 condition 配置是有效的。
之前没效果就是 @StrivingRabbit 所说的，dist/dev/mp-weixin 下连 `project.config.js` 都没生成，所以没生效。

project.config.js 没有被生成的触发条件我也找到了，就是在项目根目录下不能存在一个叫做 `project.config.js` 的同名文件，否则打包编译不会生成 `project.config.js` 。
