### ISSUE TITLE
微信插件被编译后无法获取插件自定义事件的回调数据

### ISSUE THREAD

**Issue by Peter-90** [dcloudio/uni-app#2591]
**问题描述**
引入send-coupon微信商家券插件，绑定事件后，无法获取回调函数bindcustomevent中的参数。插件参考该文档
[https://pay.weixin.qq.com/wiki/doc/apiv3/apis/chapter9_3_1.shtml](url)

**复现步骤**
见问题描述

**预期结果**
应该返回bindcustomevent中的参数

**实际结果**
什么都没返回，返回undefined

**系统信息:**
 - 发行平台: 微信小程序
 - uni-app版本：uni-app v3.1.8
uni-app cli v2.0.0-31820210406002

Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 14.16.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.12 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.72
    Firefox: Not Found
    Safari: 14.0.3
  npmPackages:
    @dcloudio/uni-app-plus: ^2.0.0-30520210106003 => 2.0.0-31820210406002 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-cli-shared: ^2.0.0-30520210106003 => 2.0.0-31820210406002 
    @dcloudio/uni-h5: ^2.0.0-30520210106003 => 2.0.0-31820210406002 
    @dcloudio/uni-helper-json: ^1.0.13 => 1.0.13 
    @dcloudio/uni-i18n:  0.0.5 
    @dcloudio/uni-migration: ^2.0.0-30520210106003 => 2.0.0-31820210406002 
    @dcloudio/uni-mp-alipay: ^2.0.0-30520210106003 => 2.0.0-31820210406002 
    @dcloudio/uni-mp-baidu: ^2.0.0-30520210106003 => 2.0.0-31820210406002 
    @dcloudio/uni-mp-qq: ^2.0.0-30520210106003 => 2.0.0-31820210406002 
    @dcloudio/uni-mp-toutiao: ^2.0.0-30520210106003 => 2.0.0-31820210406002 
    @dcloudio/uni-mp-weixin: ^2.0.0-30520210106003 => 2.0.0-31820210406002 
    @dcloudio/uni-stat: ^2.0.0-30520210106003 => 2.0.0-31820210406002 
    @dcloudio/uni-template-compiler: ^2.0.0-30520210106003 => 2.0.0-31820210406002 
    @dcloudio/uni-ui: ^1.2.10 => 1.2.12 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-30520210106003 => 2.0.0-31820210406002 
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-30520210106003 => 2.0.0-31820210406002 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-30520210106003 => 2.0.0-31820210406002 
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-30520210106003 => 2.0.0-31820210406002 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-30520210106003 => 2.0.0-31820210406002 
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.4 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.12 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.12 
    @vue/cli-plugin-babel: ^4.5.10 => 4.5.12 
    @vue/cli-plugin-router:  4.5.12 
    @vue/cli-plugin-vuex:  4.5.12 
    @vue/cli-service: ^4.5.10 => 4.5.12 
    @vue/cli-shared-utils:  4.5.12 
    @vue/component-compiler-utils:  3.2.0 (3.2.0)
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/web-component-wrapper:  1.3.0 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.12 => 2.6.12 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.6 (16.2.0, 15.9.6)
    vue-router:  3.0.1 
    vue-style-loader:  4.1.3 (4.1.3)
    vue-template-compiler: ^2.6.12 => 2.6.12 (2.6.12)
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.6.0 => 3.6.2 
  npmGlobalPackages:
    @vue/cli: 3.8.4
 - 设备信息：所有移动设备

**补充信息**
在编译之后的vender文件中加入log是可以到看到微信插件发券返回的参数的
目前查源码看出
![image](https://user-images.githubusercontent.com/22003137/114841281-3de1c580-9e0a-11eb-930f-4fb960560272.png)
截图处返回的微信插件是对象，然后在源码
![image](https://user-images.githubusercontent.com/22003137/114841618-a29d2000-9e0a-11eb-8d75-e1e3f257882f.png)
当前位置不会被返回，导致取不到。
第一个截图处，被编译的插件是没有comType === 'wx'的
<img width="631" alt="企业微信截图_61698ebd-b0e3-451f-8ade-9f2e9f5a0e5e" src="https://user-images.githubusercontent.com/22003137/114841832-dbd59000-9e0a-11eb-956e-4fbf79287461.png">
### 解决办法
在引入插件上绑定`data-com-type="wx"`即可

望uni团队尽快解决

**Comment by zhetengbiji** [comment]
是这样绑定事件吗 ``@customevent``

**Comment by Peter-90** [comment]
@zhetengbiji 是的

**Comment by zhetengbiji** [comment]
新版有相关优化，使用 ```npx @dcloudio/uvm``` 更新依赖后，如仍然存在问题，上传一个测试工程，并重启开启此 issue。
