### ISSUE TITLE
input组件遇到问题，当type为number的情况下，selection-start和selection-end属性出错

### ISSUE THREAD

**Issue by MadiniGo** [dcloudio/uni-app#2592]
chunk-vendors.js:4077 [Vue warn]: Error in callback for watcher "selectionEndNumber": "InvalidStateError: Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('number') does not support selection."
chunk-vendors.js:301 [system] DOMException: Failed to set the 'selectionStart' property on 'HTMLInputElement': The input element's type ('number') does not support selection.

**Comment by StrivingRabbit** [comment]
HTMLInputElement 当 type="number" 时不支持使用selection-start和selection-end。[详情](https://developer.mozilla.org/zh-CN/docs/Web/API/HTMLInputElement/setSelectionRange)
