### ISSUE TITLE
微信放弃了getuserinfo 的button 事件获取用户信息 改用getUserProfile  但是uni button目前没有提供这个open-type

### ISSUE THREAD

**Issue by Mr-lrf** [dcloudio/uni-app#2593]
// 不推荐使用getUserInfo获取用户信息，预计自2021年4月13日起，getUserInfo将不再弹出弹窗，并直接返回匿名的用户个人信息

 // 推荐使用wx.getUserProfile获取用户信息，开发者每次通过该接口获取用户个人信息均需用户确认，开发者妥善保管用户快速填写的头像昵称，避免重复弹窗
uni open-type="getUserProfile" 还没有提供 怎么办？？？卧槽要放弃拿原生重新写？？？

**Comment by zhetengbiji** [comment]
> // 不推荐使用getUserInfo获取用户信息，预计自2021年4月13日起，getUserInfo将不再弹出弹窗，并直接返回匿名的用户个人信息
> 
> // 推荐使用wx.getUserProfile获取用户信息，开发者每次通过该接口获取用户个人信息均需用户确认，开发者妥善保管用户快速填写的头像昵称，避免重复弹窗
> uni open-type="getUserProfile" 还没有提供 怎么办？？？卧槽要放弃拿原生重新写？？？

uni-app 相关 API 文档已经更新

组件文档未找到微信小程序有相关信息

**Comment by Mr-lrf** [comment]
现在有什么办法获取用户信息呢

**Comment by zhetengbiji** [comment]
> 现在有什么办法获取用户信息呢

看下 API 文档能满足吗：https://github.com/dcloudio/uni-app/issues/2587

**Comment by zhetengbiji** [comment]
你是在哪看到的 open-type="getUserProfile"
