### ISSUE TITLE
uni使用uviewUI，表单子组件，传入参数时，数据更新了，但是input没有更新

### ISSUE THREAD

**Issue by jiaxiaon** [dcloudio/uni-app#2598]
<u-input 
                        v-model="form.phone"
                        type="number" 
                        maxlength="11"
                        class="u-input"
                        @input="changePhone"
                        placeholder="请输入手机号" input-align="right" />

changePhone(val) {
            this.$emit('changePhone', value)
            this.$forceUpdate()
},

**Comment by StrivingRabbit** [comment]
此类问题请去uviewUI仓库下提问

**Comment by yinfoyuan** [comment]
> <u-input
> v-model="form.phone"
> type="number"
> maxlength="11"
> class="u-input"
> @input ="changePhone"
> placeholder="请输入手机号" input-align="right " />
> 
> changePhone(val) {
> this.$emit('changePhone', value)
> this.$forceUpdate()
> },

看了一下源代码  估计是两个值相等就不会在赋值 如果有跳转在返回的情况 跳转后在清除input的值就可以回显了 我遇到的是这种情况
