### ISSUE TITLE
nvue text嵌套slot，app不显示

### ISSUE THREAD

**Issue by blancokitsune** [dcloudio/uni-app#2599]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
 想封装一下iconfont，但是nvue模式下text嵌套slot，app不显示，微信小程序正常显示

**复现步骤**
```vue
<template>
  <view >
    <text class="iconfont"><slot></slot></text>
  </view>
</template>
```

**预期结果**
app和微信小程序预期都正常显示

**实际结果**
微信小程序正常显示，现在app不显示内容

**系统信息:**
 - 发行平台: 微信小程序、App
 - 操作系统：Android 10
 - HBuilderX版本：3.1.9
 - 设备信息：小米8

**补充信息**
改逻辑了？不能text里面嵌slot了？

**Comment by StrivingRabbit** [comment]
<text> 组件内只支持嵌套 <text>，不支持其它组件或自定义组件，否则会引发在不同平台的渲染差异

nvue不支持text下写slot

**Comment by wb121017405** [comment]
这个问题可以提出来写个提示，网页端大多都是p,span,div各种包含一个i标签的图标

切换到小程序还没习惯text标签不能包含view标签，很容易遇到这样的坑

**Comment by StrivingRabbit** [comment]
@wb121017405 https://uniapp.dcloud.io/component/text 在组件文档中是有说明的
