### ISSUE TITLE
countDown组件倒计时结束之后，如何重新赋值？再重新用另外一个值开始倒计时

### ISSUE THREAD

**Issue by TeemoPeng** [dcloudio/uni-app#260]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
countDown组件倒计时结束之后，如何重新赋值？再重新用另外一个值开始倒计时

**复现步骤**
我页面里用了一个countdown组件，想要在倒计时结束的时候，再重新赋值，但是并没有生效，请问如何解决？

<uni-countdown v-if="product.promotionEndTime" font-color="#FFFFFF" bgr-color="#000000" :timer="product.startTime"></uni-countdown>

//开始、结束倒计时
						var currentTime = new Date().getTime();
						let startTime = new Date(_this.product.promotionBeginTime).getTime();
						let endTime = new Date(_this.product.promotionEndTime).getTime();
						if(currentTime < startTime){
							_this.product.flashText = '距离开始还剩：';
							_this.buyDisabled = true;
							_this.product.startTime =_this. product.promotionBeginTime;

							_this.startTimer = setInterval(function(){
								_this.product.promotionBeginRemainingTime--;
								if(_this.product.promotionBeginRemainingTime<=0){
									_this.buyDisabled = false;
									_this.product.flashText = '距离结束还剩：';
									_this.product.startTime = _this.product.promotionEndTime;
									clearInterval(_this.startTimer)
								}
							},1000);

						}

**Comment by Wangyaqi** [comment]
现已支持重新赋值，欢迎使用新版uni-ui体验
