### ISSUE TITLE
部分rpx单位在h5环境下编译结果错误

### ISSUE THREAD

**Issue by sharemeans** [dcloudio/uni-app#2600]
**问题描述**
[NODE_ENV的值为production时，h5打包结果中部分rpx编译为%?xxx?%]

**复现步骤**
`
<style lang="less">
.comp-card{
	.content--wrap{
		padding: 22rpx 24rpx;
	}
}
</style>
`

**预期结果**
rpx编译为px单位

**实际结果**
浏览器审查元素的样式：
`
.comp-card .content--wrap[data-v-8ec74a42] {
    padding: %?22?% %?24?%;
}
`

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [全部]
 - uni-app版本
 uni-app v3.1.9
uni-app cli v2.0.0-31920210412001

Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz
  Binaries:
    Node: 10.16.0 - D:\NodeJS\node.EXE
    Yarn: 1.22.4 - D:\Vue-cli\vue-cli-next\node_modules\.bin\yarn.CMD
    npm: 6.9.0 - D:\NodeJS\npm.CMD
  Browsers:
    Edge: 42.17134.1098.0
  npmPackages:
    @dcloudio/uni-app-plus: 2.0.0-31920210412001 => 2.0.0-31920210412001
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: 2.0.0-31920210412001 => 2.0.0-31920210412001
    @dcloudio/uni-h5: 2.0.0-31920210412001 => 2.0.0-31920210412001
    @dcloudio/uni-i18n:  0.0.5
    @dcloudio/uni-migration: 2.0.0-31920210412001 => 2.0.0-31920210412001
    @dcloudio/uni-mp-alipay: 2.0.0-31920210412001 => 2.0.0-31920210412001
    @dcloudio/uni-mp-baidu: 2.0.0-31920210412001 => 2.0.0-31920210412001
    @dcloudio/uni-mp-qq: 2.0.0-31920210412001 => 2.0.0-31920210412001
    @dcloudio/uni-mp-toutiao: 2.0.0-31920210412001 => 2.0.0-31920210412001
    @dcloudio/uni-mp-weixin: 2.0.0-31920210412001 => 2.0.0-31920210412001
    @dcloudio/uni-stat:  2.0.0
    @dcloudio/uni-template-compiler: 2.0.0-31920210412001 => 2.0.0-31920210412001
    @dcloudio/uni-ui: ^1.2.5 => 1.2.8
    @dcloudio/vue-cli-plugin-hbuilderx: 2.0.0-31920210412001 => 2.0.0-31920210412001
    @dcloudio/vue-cli-plugin-uni: 2.0.0-31920210412001 => 2.0.0-31920210412001
    @dcloudio/vue-cli-plugin-uni-optimize: 2.0.0-31920210412001 => 2.0.0-31920210412001
    @dcloudio/webpack-uni-mp-loader: 2.0.0-31920210412001 => 2.0.0-31920210412001
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: 2.0.0-31920210412001 => 2.0.0-31920210412001
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  3.12.1
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  3.12.1
    @vue/cli-plugin-babel: ^3.12.1 => 3.12.1
    @vue/cli-plugin-eslint: ^3.12.0 => 3.12.1
    @vue/cli-service: ^3.12.0 => 3.12.1
    @vue/cli-shared-utils:  3.12.1
    @vue/component-compiler-utils:  3.1.0
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/shared: ^3.0.0-rc.4 => 3.0.4
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^5.0.0-beta.6 => 5.2.3
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.11 => 2.6.11
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.8.3
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.11 => 2.6.11
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.2
  npmGlobalPackages:
    @vue/cli: Not Found

**补充信息**
旧版本2.0.0-30720210122002没有问题，版本>=2.0.0-314xxx都不行

**Comment by StrivingRabbit** [comment]
使用`2.0.0-31420210305001`和`2.0.0-31920210412001`的包运行`build:h5`后运行打包后文件到浏览器，没有发现你说的现象。

你运行到了什么浏览器？怎么运行的？

**Comment by sharemeans** [comment]
**找到原因了。**
原因在于[fix: 修复 css 媒体查询内的 rpx 单位未转换的问题 question/112279](https://github.com/dcloudio/uni-app/commit/d5d2139a9fdf732996f46987cce4dd4844a555e7)的commit中修复了一个media中rpx未转换的问题：
对应文件：https://github.com/dcloudio/uni-app/commits/master/packages/vue-cli-plugin-uni/packages/h5-vue-style-loader/lib/addStylesClient.js中的正则表达式`/\{[\s\S]+?\}|@media.+\{/g`的media部分没有闭合，导致正则匹配有遗漏。

可以用下面这部分样式测试效果：
```
.uni-scroll-view[data-v-8ec74a42]{-webkit-overflow-scrolling:auto!important}.comp-card[data-v-8ec74a42]{width:100%;display:-webkit-box;display:-webkit-flex;display:-ms-flexbox;display:flex;-webkit-box-orient:vertical;-webkit-box-direction:normal;-webkit-flex-direction:column;-ms-flex-direction:column;flex-direction:column;background:#fff}.comp-card .header--wrap[data-v-8ec74a42]{padding:%?0?% %?24?%;font-size:%?28?%;font-family:PingFangSC-Medium,PingFang SC;font-weight:700;color:#1b2431;position:relative}.comp-card .header--wrap .line[data-v-8ec74a42]{position:absolute;bottom:0;left:%?24?%;width:%?678?%;height:1px;background:#f7f7f7}@media only screen and (-webkit-min-device-pixel-ratio:2){.comp-card .header--wrap .line[data-v-8ec74a42]{-webkit-transform:scaleY(.5);-ms-transform:scaleY(.5);transform:scaleY(.5)}}@media only screen and (-webkit-min-device-pixel-ratio:3){.comp-card .header--wrap .line[data-v-8ec74a42]{-webkit-transform:scaleY(.33);-ms-transform:scaleY(.33);transform:scaleY(.33)}}.comp-card .header--wrap .title[data-v-8ec74a42]{font-size:%?28?%;line-height:%?88?%}.comp-card .content--wrap[data-v-8ec74a42]{padding:%?22?% %?24?%}
```

**Comment by zhetengbiji** [comment]
HBuilderX 3.1.13 已发布
