### ISSUE TITLE
手写输入自动上屏

### ISSUE THREAD

**Issue by 1103409364** [dcloudio/uni-app#2603]
**问题描述**
密码输入框和textarea，v-model绑定变量，手写输入法写完直接出字了，没法选字，拼音输入没问题。

不用v-model时没问题

HBuilder X 3.1.9
手机三星s7edge
安卓版本8.0

**Comment by StrivingRabbit** [comment]
你的意思是，字写完后，直接上屏，没有提供选择字？可否录制一个视频

**Comment by 1103409364** [comment]
对，自动选择第一个自动上屏


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dcloudio/uni-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年4月22日(星期四) 晚上6:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] 手写输入自动选字 (#2603)





 
你的意思是，字写完后，直接上屏，没有提供选择字？可否录制一个视频

**Comment by StrivingRabbit** [comment]
> 对，自动选择第一个自动上屏
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "dcloudio/uni-app" ***@***.***&gt;; 发送时间:&nbsp;2021年4月22日(星期四) 晚上6:56 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [dcloudio/uni-app] 手写输入自动选字 (#2603) 你的意思是，字写完后，直接上屏，没有提供选择字？可否录制一个视频 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

可否提供一个复现视频？

**Comment by 1103409364** [comment]
视频在邮件中




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月23日(星期五) 中午11:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dcloudio/uni-app] 手写输入自动选字 (#2603)





  
对，自动选择第一个自动上屏
 …
 ------------------ 原始邮件 ------------------ 发件人: "dcloudio/uni-app" @.&gt;; 发送时间: 2021年4月22日(星期四) 晚上6:56 @.&gt;; @.@.&gt;; 主题: Re: [dcloudio/uni-app] 手写输入自动选字 (#2603) 你的意思是，字写完后，直接上屏，没有提供选择字？可否录制一个视频 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
可否提供一个复现视频？
 
&mdash;

**Comment by StrivingRabbit** [comment]
> 视频在邮件中
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年4月23日(星期五) 中午11:27 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [dcloudio/uni-app] 手写输入自动选字 (#2603) 对，自动选择第一个自动上屏 … ------------------ 原始邮件 ------------------ 发件人: "dcloudio/uni-app" @.&gt;; 发送时间: 2021年4月22日(星期四) 晚上6:56 @.&gt;; @.@.&gt;; 主题: Re: [dcloudio/uni-app] 手写输入自动选字 (#2603) 你的意思是，字写完后，直接上屏，没有提供选择字？可否录制一个视频 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 可否提供一个复现视频？ &mdash; You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

没有发现有视频或者附件，发到这里吧

**Comment by 1103409364** [comment]
https://share.weiyun.com/S0n2uejN




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年4月23日(星期五) 中午11:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dcloudio/uni-app] 手写输入自动选字 (#2603)





  
视频在邮件中
 …
 ------------------ 原始邮件 ------------------ 发件人: @.&gt;; 发送时间: 2021年4月23日(星期五) 中午11:27 收件人: @.&gt;; 抄送: @.&gt;; @.&gt;; 主题: Re: [dcloudio/uni-app] 手写输入自动选字 (#2603) 对，自动选择第一个自动上屏 … ------------------ 原始邮件 ------------------ 发件人: "dcloudio/uni-app" @.&gt;; 发送时间: 2021年4月22日(星期四) 晚上6:56 @.&gt;; @.@.&gt;; 主题: Re: [dcloudio/uni-app] 手写输入自动选字 (#2603) 你的意思是，字写完后，直接上屏，没有提供选择字？可否录制一个视频 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. 可否提供一个复现视频？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
没有发现有视频或者附件，发到这里吧
 
&mdash;

**Comment by StrivingRabbit** [comment]
你这个input是怎么写的？我瞅瞅。感觉像是重新聚焦然后键盘就变了

**Comment by 1103409364** [comment]
> 你这个input是怎么写的？我瞅瞅。感觉像是重新聚焦然后键盘就变了

`    <input
      class="flex-1 color-base font-30"
      placeholder="请输入您的登录密码"
      placeholder-class="input-placeholder"
      password="true"
      v-model="password1"
    />`

**Comment by zhetengbiji** [comment]
nvue 还是 vue？

**Comment by 1103409364** [comment]
nvue




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dcloudio/uni-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月14日(星期三) 上午10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] 手写输入自动上屏 (#2603)





 
nvue 还是 vue？
