### ISSUE TITLE
组件图片编译至小程序端丢失bug

### ISSUE THREAD

**Issue by a1020292206** [dcloudio/uni-app#2605]
**问题描述**

![image](https://user-images.githubusercontent.com/39959599/115694009-0be4dc00-a393-11eb-8350-446a4eec109f.png)
![image](https://user-images.githubusercontent.com/39959599/115694034-11dabd00-a393-11eb-892f-57232d0a40c2.png)
组件中相对引入图片  在小程序端无法展示

**预期结果**
组件中的图片在小程序端可以正常展示

**Comment by StrivingRabbit** [comment]
静态资源请放置在static中。[详情](https://uniapp.dcloud.io/frame?id=%e7%9b%ae%e5%bd%95%e7%bb%93%e6%9e%84)
