### ISSUE TITLE
组件嵌套不生效

### ISSUE THREAD

**Issue by 134355** [dcloudio/uni-app#261]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
组件内嵌套组件不生效
![image](https://user-images.githubusercontent.com/38032758/55147542-8aa1c780-5181-11e9-8528-bf9f797c3f3a.png)

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by 134355** [comment]
> **问题描述**
> [问题描述：尽可能简洁清晰地把问题描述清楚] 
> 组件内嵌套组件不生效
> ![图片](https://user-images.githubusercontent.com/38032758/55147542-8aa1c780-5181-11e9-8528-bf9f797c3f3a.png)
> 
> **复现步骤**
> [复现问题的步骤]
> 
> 1. 启动'...'
> 2. 点击'....'
> 3. 查看
> 
> [或者可以直接贴源代码]
> 
> **预期结果**
> [使用简洁清晰的语言描述你希望生效的预期结果]
> 
> **实际结果**
> [这里请贴上你的报错截图或文字]
> 
> **系统信息：**
> 
> * 发行平台：[如微信小程序，H5平台，5 + App等]
> * 操作系统[如iOS 12.1.2，Android 7.0]
> * HBuilderX版本[如使用HBuilderX，则需提供HBuilderX版本号]
> * uni-app版本[如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
> * 设备信息[如iPhone8 Plus]
> 
> **补充信息**
> [可选] 
> [根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by 134355** [comment]
组件不支持嵌套本身，flex布局就不能组件化，希望官方大大尽早解决这个问题

**Comment by xiaoyucoding** [comment]
组件的递归调用，支持的平台为 H5 以及微信小程序，微信小程序平台需开启编译为微信小程序原生组件。https://uniapp.dcloud.io/collocation/manifest?id=mp-weixin
支持递归调用的组件，需要在 globalStyle->usingComponents 中声明。例如：
```json
"globalStyle": {
	"navigationBarTextStyle": "black",
	"navigationBarTitleText": "uni-app",
	"navigationBarBackgroundColor": "#F8F8F8",
	"backgroundColor": "#F8F8F8",
	"usingComponents": {
		"collapse-tree-item":"/components/collapse-tree-item"
	}
}
```
HBuilderX 1.8.0 已修复此问题，cli 已同步更新。

**Comment by wuchuixu** [comment]
5+app 还是不能嵌套就关闭问题了？

**Comment by xiaoyucoding** [comment]
> 5+app 还是不能嵌套就关闭问题了？

https://ask.dcloud.net.cn/article/35699
> HBuilderX alpha 1.8.5公测啦！uni-app App平台 升级为新版编译器，提升启动速度、提升组件性能、支持过滤器等更多vue语法。
