### ISSUE TITLE
头条小程序支持sjs语法，但是uni编译之后没有

### ISSUE THREAD

**Issue by yanrome** [dcloudio/uni-app#2621]
uni文档上线说头条不支持sjs，但头条小程序实际已经支持了呢
-----
https://microapp.bytedance.com/docs/zh-CN/mini-app/develop/framework/sjs-syntax-reference/module
-----以前老项目里面写了很多sjs的，现在无法兼容头条小程序

**Comment by Otto-J** [comment]
后续支持
