### ISSUE TITLE
cli创建的项目打包H5在 manifest.json 配置 base 为CDN地址，打包后index.html引入的js文件自动添加 / 前缀

### ISSUE THREAD

**Issue by Leslie-Luo** [dcloudio/uni-app#2624]
**问题描述**
cli创建的项目打包H5在 manifest.json 配置 base 为CDN地址，打包后index.html引入的js文件自动添加 / 前缀

**复现步骤**
用cli创建新项目，修改manifest.json-h5-base，然后执行打包命令

![image](https://user-images.githubusercontent.com/22937782/116505100-a6da3a80-a8ec-11eb-989c-540ab580b47a.png)

**预期结果**
打包后的文件引入地址直接是https开头无 / 

**实际结果**
![image](https://user-images.githubusercontent.com/22937782/116505272-089aa480-a8ed-11eb-8320-b1f322339fa7.png)

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 macOS 11.0.1
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 
 uni-app v3.1.12
 uni-app cli v2.0.0-31920210428001
 - 设备信息 [如 iPhone8 Plus]

**补充信息**

**Comment by peng-xiao-shuai** [comment]
在 manifest 文件中 h5 的配置下添加 publicPath。
<img width="671" alt="1686636910144" src="https://github.com/dcloudio/uni-app/assets/53845479/d63269e3-d12c-4ce4-bcd0-e972a330a499">
