### ISSUE TITLE
video组件的@timeupdate事件不能在app上执行

### ISSUE THREAD

**Issue by zi4086** [dcloudio/uni-app#263]
**问题描述**
_20190331 Update_
把Video放在组件里的时候是没办法执行@timeupdate这个事件的，在模版里直接用是可以执行的

~~默认基座下安卓和iOS上都无法执行@timeupdate，微信小程序可以执行~~

**复现步骤**
```JavaScript
    <video
      @timeupdate="videoUpdate"
    ></video>
```

**系统信息:**
5+ App，默认基座，iOS12，Android 6.0

**Comment by helsonxiao** [comment]
请问你用 video 组件可以正常播放 rtmp 流吗？比如这个地址`src="rtmp://58.200.131.2:1935/livetv/gxtv"`

**Comment by zi4086** [comment]
@helsonxiao 试了不行，你可以试试用5+API自己创建一个播放器试试

**Comment by helsonxiao** [comment]
> @helsonxiao 试了不行，你可以试试用5+API自己创建一个播放器试试

谢谢，刚刚试了下没啥用，只能等待官方修复了......

**Comment by dcloudhdx** [comment]
HBuilderX 1.9.3测试没有问题

**Comment by zi4086** [comment]
我刚测试了一遍，使用最新版本编辑器+自定义组件模式居然好了。感谢 @dcloudhdx

**Comment by zzlbt** [comment]
请问你们在微信小程序上点击播放后，video内的操作按钮还在吗，我点了播放或者全屏按钮后，就无法操作了
