### ISSUE TITLE
怎么运行快手小程序？cli创建之后，npm run dev:mp-kuaishou运行时报错

### ISSUE THREAD

**Issue by candyAndBella** [dcloudio/uni-app#2632]
**问题描述**
通过cli创建了项目，命令行如下
vue create -p dcloudio/uni-preset-vue my-project
选择了Hello uni-app模板
完成后运行npm run dev:mp-kuaishou 报错，请教大家，如何解决？

我的整个步骤是正确的吗？是哪里操作有问题吗？

![微信截图_20210508173747](https://user-images.githubusercontent.com/34698384/117534602-be1fd300-b024-11eb-9d6d-a26c89f79276.png)

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/2522

**Comment by candyAndBella** [comment]
请问我的整个步骤是正确的吗？是哪里操作有问题吗？

**Comment by candyAndBella** [comment]
> #2522

请问我的整个步骤是正确的吗？是哪里操作有问题吗？
