### ISSUE TITLE
目前有方法可以实现Vue3 + Typescript/TSX?

### ISSUE THREAD

**Issue by linkscope** [dcloudio/uni-app#2637]
**新功能描述**
最希望的是可以使用Vue3 + TSX从而达到最完美的TS校验体验，但因为uni-app特殊性，无法直接使用[jsx-next](https://github.com/vuejs/jsx-next)

希望能够使用Vue3 + TS/TSX

**现状及问题**
2021年，还有什么理由不使用TS？经常使用vue模板的开发者一定对vue模板的TS校验不友好深有体会，如果可以，我甚至希望摒弃vue模板。

**尝试方案**
成本最低的方式无疑是在jsx-next的原基础上进行部分改造

**Comment by zhetengbiji** [comment]
进行中 https://github.com/dcloudio/uni-app/tree/next

**Comment by StrivingRabbit** [comment]
[uni-app 项目小程序端、H5 端支持 vue3 介绍](https://ask.dcloud.net.cn/article/37834)

**Comment by fxy060608** [comment]
h5,App可以支持jsx,tsx
小程序平台暂无计划支持
