### ISSUE TITLE
数据源JSON数据72kb，setData 数据传输长度为 3968kb，可以怎么去优化呢？

### ISSUE THREAD

**Issue by yinfoyuan** [dcloudio/uni-app#2638]
数据是通过vuex 设置的
<img width="804" alt="微信截图_20210511201931" src="https://user-images.githubusercontent.com/35027364/117814860-705ed100-b297-11eb-992e-d698ff114fdb.png">

**Comment by StrivingRabbit** [comment]
建议拆分加载，分页加载之类的

**Comment by xuweikang** [comment]
> 数据是通过vuex 设置的
> <img alt="微信截图_20210511201931" width="804" src="https://user-images.githubusercontent.com/35027364/117814860-705ed100-b297-11eb-992e-d698ff114fdb.png">

@yinfoyuan 你的情况和我遇到不知是否一样  #2677 有多个子组件去读这个vuex state，然后发现是重复累加起来的。
