### ISSUE TITLE
能否增加indicator-dot自定义

### ISSUE THREAD

**Issue by TsingfunLee** [dcloudio/uni-app#264]
**新功能描述**
可以自定义swiper-indicator-dots样式。

**现状及问题**
绝大多数时候，indicator-dots需要自己写。有时设计稿仅仅是margin-bottom的数值不同，就需要自己写过。

**尝试方案**
比如；
给indicator-dots指定新class，或增加width, height, border-radius, margin, padding等常用CSS属性设置。

**Comment by zhetengbiji** [comment]
各端的实现并不一致，要想实现此功能，又要封装一层，内置并不合适。
建议有需要的用户自己封装，封装后也可上传到插件市场，分享给他人。
可以隐藏原来的指示器，自己使用view绘制新的指示器，并通过监听change事件修改指示器状态。
