### ISSUE TITLE
百度小程序 mounted执行2次，props报错

### ISSUE THREAD

**Issue by webceoboy** [dcloudio/uni-app#2642]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
1.页面的mounted会执行2次，而且第一次是在onLoad前执行。
2. uni-list-item 的prop link定义是type:[Boolean,String]，传入string后，报错vendor.js:8920 [Vue warn]: Invalid prop: type check failed for prop "link". Expected Boolean, got String with value "navigateTo".
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: 百度
 - 操作系统 ios和win10
 - HBuilderX版本 3.1.13
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 iphone xr

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
经测试基础库`3.290.33`出现此问题，可先临时切换至之前基础库版本解决问题
