### ISSUE TITLE
Failed to resolve loader: sass-loader You may need to install it

### ISSUE THREAD

**Issue by zhiyi-home** [dcloudio/uni-app#2647]
**问题描述**
通过命令创建工程：vue create -p dcloudio/uni-preset-vue my-project
创建好后：运行项目 npm run dev:h5
会提示错误: Failed to resolve loader: sass-loader You may need to install it

**复现步骤**
[复现问题的步骤]
1.  启动 'vue create -p dcloudio/uni-preset-vue my-project'
2. 点击  ' npm run dev:h5'
3. 查看

[或者可以直接贴源代码]

**预期结果**
程序正常启动无错误

**实际结果**

![image](https://user-images.githubusercontent.com/39183806/118797515-40cf4a80-b8cf-11eb-87c7-115a71e54af3.png)

**系统信息:**
 - H5平台
 - Linux
 - vscode
 - vue-cli
 - chrome

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
如果使用yarn add sass-loader后
![image](https://user-images.githubusercontent.com/39183806/118797738-770cca00-b8cf-11eb-9cb5-1d96ac6ea2eb.png)

**Comment by HuangKaiSong** [comment]
问题解决了吗？

**Comment by yangdan8** [comment]
回退sass-loader版本到10.2.0
