### ISSUE TITLE
dev:h5 的时候在manifest.json h5 devServer中添加publicPath为“./”相对路径报错如下

### ISSUE THREAD

**Issue by yrmatou** [dcloudio/uni-app#2649]
**问题描述**
dev:h5 的时候在manifest.json h5 devServer中添加publicPath为“./”相对路径报错
![image](https://user-images.githubusercontent.com/21699695/118845422-57d96100-b8fe-11eb-9bca-326c55fe6523.png)

**复现步骤**
[复现问题的步骤]
![image](https://user-images.githubusercontent.com/21699695/118845664-90793a80-b8fe-11eb-827f-beed56b2f14b.png)

[或者可以直接贴源代码]

**预期结果**
希望这里能直接跟打包模式下一样 改成相对路径不报错，

**系统信息:**
H5平台 dev:h5
![image](https://user-images.githubusercontent.com/21699695/118845959-cfa78b80-b8fe-11eb-89d4-0e532f0f6ea6.png)

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
h5下 publicPath参数有问题

**Comment by aiplat** [comment]
devServer建议配置到vue.config.js
不必使用manifest.json里的
