### ISSUE TITLE
uni-app属性绑定不支持es6模板字符串

### ISSUE THREAD

**Issue by IceDream1024** [dcloudio/uni-app#265]
`
<navigator :key="item.id" :url="'../detail/detail?trailerId=' + item.movieId">
<navigator :key="item.id" :url="`../detail/detail?trailerId=${item.movieId}`"/>
	<image :src="item.cover" class="cover"></image>
</navigator>
`

> 代码如上，用了模板字符串以后h5可以正常显示，微信小程序会报错

**Comment by xiaoyucoding** [comment]
HBuilderX 1.9.0 或最新的 cli 在自定义组件模式下，支持使用此写法。
