### ISSUE TITLE
抖音更新新版本基础库后,uniapp provide inject API失效

### ISSUE THREAD

**Issue by wanchang1121** [dcloudio/uni-app#2651]
**问题描述**
更新新版本基础库后,slot层级的组件父子关系错乱,provide inject API失效
![image](https://user-images.githubusercontent.com/24827038/118929465-23ee5200-b977-11eb-8a7d-8e5ddb0ef7b8.png)
首先是provide inject api失效 找不到实例的引用
然后发现打印出来的实例的$parent  $children 是错误的
![image](https://user-images.githubusercontent.com/24827038/118929619-54ce8700-b977-11eb-8fe0-6df35eacea04.png)
应该是slot层级组件编译后出错
![image](https://user-images.githubusercontent.com/24827038/118929725-77f93680-b977-11eb-8368-aa2bb56ffff8.png)
formItem父组件竟然是icon
![image](https://user-images.githubusercontent.com/24827038/118929939-b5f65a80-b977-11eb-84f6-55696bf844a1.png)
希望尽快解决,目前找不到解决办法

**复现步骤**

1.  编写slot层级的父子组件,然后使用provide  inject API
2. 打开头条开发者工具使用2.6.0.9及以上基础库
3. 打印 inject的父组件实例,  和 组件实例 this
4. 层级混乱

**预期结果**

通过slot搭建的组件父子层级正常,provide  inject API使用正常

**实际结果**

头条开发者工具2.6.0.9及以上基础库  组件层级错乱,  所有孙子组件和父组件在一个层级, $parent也可能是莫名其妙的无关系组件
![image](https://user-images.githubusercontent.com/24827038/118930132-f0f88e00-b977-11eb-965d-525189e625d4.png)
切换2.6.0.9以下,变成正常层级
![image](https://user-images.githubusercontent.com/24827038/118930254-184f5b00-b978-11eb-92a7-728774877720.png)

**系统信息:**
 - 发行平台: 头条小程序
 - 操作系统 ios 安卓
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**

**Comment by surpaimb** [comment]
我也是，uni-col, uni-swipe-action-item等都报：我的信息是
`uni-app tuple$ npm run info

> uni-app@0.1.0 info /Users/tuple/workspace/reminder/uni-app
> node node_modules/@dcloudio/vue-cli-plugin-uni/commands/info.js

uni-app v3.1.4
uni-app cli v2.0.0-31420210305001

Environment Info:

  System:
    OS: macOS 10.15.7
    CPU: (8) x64 Intel(R) Core(TM) i5-8279U CPU @ 2.40GHz
  Binaries:
    Node: 14.15.4 - /usr/local/bin/node
    Yarn: 1.22.0 - /usr/local/bin/yarn
    npm: 6.14.10 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: Not Found
    Safari: 13.1.3
  npmPackages:
    @dcloudio/types: * => 2.0.22 
    @dcloudio/uni-app-plus: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-automator: ^2.0.0-31420210305001 => 2.0.0-31420210305001 
    @dcloudio/uni-cli-shared: ^2.0.0-31420210305001 => 2.0.0-31420210305001 
    @dcloudio/uni-h5: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-helper-json: ^1.0.13 => 1.0.13 
    @dcloudio/uni-i18n:  0.0.3 
    @dcloudio/uni-migration: ^2.0.0-31420210305001 => 2.0.0-31420210305001 
    @dcloudio/uni-mp-360: ^2.0.0-alpha-31920210506002 => 2.0.0-alpha-31920210506002 
    @dcloudio/uni-mp-alipay: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-mp-baidu: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-mp-qq: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-mp-toutiao: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-mp-vue: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-mp-weixin: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-quickapp-native: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-quickapp-webview: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-stat: ^2.0.0-31920210428001 => 2.0.0-31920210428001 (2.0.0-31420210305001)
    @dcloudio/uni-template-compiler: ^2.0.0-31420210305001 => 2.0.0-31420210305001 
    @dcloudio/uni-ui: ^1.3.1 => 1.3.1 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-31420210305001 => 2.0.0-31420210305001 
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-31420210305001 => 2.0.0-31420210305001 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-31420210305001 => 2.0.0-31420210305001 
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-31420210305001 => 2.0.0-31420210305001 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-31420210305001 => 2.0.0-31420210305001 
    @hap-toolkit/dsl-vue:  0.6.13 
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.3 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.11 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.11 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.11 
    @vue/cli-plugin-router:  4.5.11 
    @vue/cli-plugin-typescript: * => 4.5.11 
    @vue/cli-plugin-vuex:  4.5.11 
    @vue/cli-service: ~4.5.0 => 4.5.11 
    @vue/cli-shared-utils:  4.5.11 
    @vue/component-compiler-utils:  3.2.0 (3.2.0)
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/shared: ^3.0.0 => 3.0.7 
    @vue/web-component-wrapper:  1.3.0 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.11 => 2.6.12 
    vue-class-component: ^6.3.2 => 6.3.2 (7.2.6)
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.6 (16.2.0, 15.9.6)
    vue-property-decorator: ^8.0.0 => 8.5.1 
    vue-router:  3.0.1 
    vue-style-loader:  4.1.3 (4.1.3)
    vue-template-compiler: ^2.6.11 => 2.6.12 (2.6.12)
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.2.0 => 3.6.2 
  npmGlobalPackages:
    @vue/cli: 4.5.11`
