### ISSUE TITLE
usingSwanComponents 和 usingComponents 若两者同时存在 百度小程序开发着工具不会报错 但是会导致代码无法上传 报错"sitemap"动态库notfound 

### ISSUE THREAD

**Issue by quiet-jing** [dcloudio/uni-app#2652]
**问题描述**
在pages.json内使用usingComponents引入百度小程序swan-sitemap 组件时，将页面的json文件编译为
"usingSwanComponents": { "swan-sitemap-list": "dynamicLib://swan-sitemap-lib/swan-sitemap-list" }
正确编译结果应为：
"usingComponents": { "swan-sitemap-list": "dynamicLib://swan-sitemap-lib/swan-sitemap-list" },
"usingSwanComponents": { "swan-sitemap-list": "dynamicLib://swan-sitemap-lib/swan-sitemap-list" }
导致页面正常 但是无法上传至百度

**复现步骤**
[复现问题的步骤]
![image](https://user-images.githubusercontent.com/43675851/118940507-5e5dec00-b983-11eb-974f-b44a94b1f211.png)

[或者可以直接贴源代码]

**预期结果**
.json文件编译后只保留字段usingComponents 

**实际结果**

**系统信息:**
 - 发行平台: 百度小程序
 - uni-app版本 v3.1.13

**补充信息**
此问题是在 此次 [issue](https://github.com/dcloudio/uni-app/commit/2121124c4be41ce164e714150860658f8530fc88) close 采用了一次pull request后产生

**Comment by zhetengbiji** [comment]
usingComponents -> usingSwanComponents  考虑增加白名单机制 @StrivingRabbit

**Comment by zhangxu3486432** [comment]
所以这个问题怎么解决的呀，我这边还卡在这！！！

**Comment by zhangxu3486432** [comment]
3.1.13 版本

**Comment by quiet-jing** [comment]
请问老师 @zhetengbiji 当前pullRequest 什么时候能发布至cli版本

**Comment by zhetengbiji** [comment]
> 请问老师 @zhetengbiji 当前pullRequest 什么时候能发布至cli版本

预计会在下周，在此之前可以先在本地临时处理一下

**Comment by quiet-jing** [comment]
> > 请问老师 @zhetengbiji 当前pullRequest 什么时候能发布至cli版本
> 
> 预计会在下周，在此之前可以先在本地临时处理一下

好的 感谢老师

**Comment by zhetengbiji** [comment]
已发布至 2.0.0-alpha-31920210611001
