### ISSUE TITLE
uniapp编译完的代码能不能作为分包引入到行的uniapp中使用呢

### ISSUE THREAD

**Issue by fighterkang** [dcloudio/uni-app#2653]
**新功能描述**
简洁描述你希望补充完善的增强功能

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by fighterkang** [comment]
uniapp编译完的代码能不能作为分包引入到新的uniapp中使用呢

**Comment by Otto-J** [comment]
uni-app 负责把 vue 转成成小程序识别的 wxs wxml 等。可以作为自定义组件引入。
