### ISSUE TITLE
cloudfunction-config字段配置触发器后，无法删除触发器了

### ISSUE THREAD

**Issue by donjan-deng** [dcloudio/uni-app#2654]
**问题描述**
在cloudfunction-config配置了triggers，后来删除了triggers，每次上传云函数，定时触发器都还在，哪怕在控制台删了该触发器。

**复现步骤**
[复现问题的步骤]
1.  cloudfunction-config配置了triggers，上传云函数
2. 控制台看到有定时触发器
3. cloudfunction-config配置删除triggers，上传云函数
4. 控制台看到仍有定时触发器
5. 控制台直接删除定时触发器，现在没有了
6. 再次上传云函数(cloudfunction-config配置里已经没有triggers了)，定时触发器又出现

[或者可以直接贴源代码]

**预期结果**
上传云函数后，没有定时触发器

**实际结果**
定时触发器一直存在，哪怕在控制台手动删除后上传云函数

**系统信息:**

 - HBuilderX版本3.1.13.20210514
 - 阿里云

**Comment by Wangyaqi** [comment]
cloudfunction-config不能删除云端配置，关于6我们排查一下
