### ISSUE TITLE
video 倍数播放iOS 1.25、1.5倍无效，安卓2倍无效

### ISSUE THREAD

**Issue by 1103409364** [dcloudio/uni-app#2657]
**问题描述**
播放m3u8视频，倍数播放iOS 1.25、1.5倍无效 安卓2倍无效。其他倍数有效

**复现步骤**、
`this.videoContext.playbackRate(rate)`

**系统信息:**
 - 发行平台:：App
 - 操作系统 ：ios14.5.1 安卓9.0
 - HBuilderX版本：3.1.13.20210514
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息：iPhoneXR、小米mix2

**Comment by StrivingRabbit** [comment]
是cli项目吗？使用的什么版本的HX？

**Comment by 1103409364** [comment]
> 是cli项目吗？使用的什么版本的HX？

是cli，3.1.13

**Comment by ArrayDC** [comment]
HBuilderX3.2.3+版本已修复
