### ISSUE TITLE
onShareAppMessage 编译到百度小程序配置信息无效

### ISSUE THREAD

**Issue by liyuxian** [dcloudio/uni-app#2659]
**问题描述**
在uni中重写页面的分享信息 运行到百度小程序不生效

**复现步骤**
onShareAppMessage:function(){
		return {
				title: "e充电修改", 
				path: "/pages/my/my",
				imageUrl: 'https://cdn-evone-oss.echargenet.com/mini-program/resource/image/share-icon.png',
				content:'电动车主必备小程序'                
		}
},
**预期结果**
在页面点击右上角分享，分享卡片 title为e充电修改
点击分享卡片跳转"/pages/my/my",
卡片图片为https://cdn-evone-oss.echargenet.com/mini-program/resource/image/share-icon.png'

**实际结果**
![image](https://user-images.githubusercontent.com/15683051/119287290-c6a91800-bc78-11eb-9893-22602b0538ec.png)

**系统信息:**
 - 发行平台: [百度小程序]
 - 操作系统 [Android 8.0]
 - HBuilderX版本 [3.1.7]
 - 设备信息 [红米4]

**补充信息**

**Comment by zhetengbiji** [comment]
https://smartprogram.baidu.com/forum/topic/show/152602
