### ISSUE TITLE
在uni-app配置typescript后报错

### ISSUE THREAD

**Issue by JOU-amjs** [dcloudio/uni-app#266]
**问题描述**
在uni-app配置了typescript后分别在运行web端和小程序端都会报错，报错分别如下：
web端：
![image](https://user-images.githubusercontent.com/29848971/55337909-227d1980-54d2-11e9-95c6-5d036fc2a442.png)
微信小程序端：
![image](https://user-images.githubusercontent.com/29848971/55338195-bc44c680-54d2-11e9-8355-18562ea53093.png)

**复现步骤**
1.  增加tsconfig.json
```json
{
  "include": [
    "main.ts",
    "typings/*.d.ts",
    "pages/**/*",
    "components/**/*"
  ],
  "exclude": [
    "node_modules"
  ],
  "compilerOptions": {
    "target": "es5",
    "strict": true,
    "module": "es2015",
    "moduleResolution": "node"
  }
}
```
2. 增加`typings/vue-shim.d.ts`，内容如下
```typescript
declare module '*.vue' {
  import Vue from 'vue';
  export default Vue;
};
```
3. 增加`typings/vue-property.d.ts`
```typescript
import Vue from 'vue';

declare module "vue/types/vue" {
  interface Vue {
    keepAliveInclude: any
  }
};
```
4. 再将每个.vue文件改造为`Vue.extend({...})`的写法
5. 再提一下，在小程序启动时报的`TS2304:Cannot find name 'createPage'.`后，我在`main.ts`中添加了`declare let createPage: any;`命令，但还是没用

**预期结果**
预期可以正常执行typescript代码，并在项目中继续使用typescript写代码

**实际结果**
上面已贴出

**系统信息:**
 - 发行平台: 微信小程序、H5平台
 - 操作系统: chrome 73.0、微信开发者工具
 - HBuilderX版本: HBuilderX 1.8.1.20190330
 - uni-app版本: 0.1.0-2019033020
 - 设备信息 mac air

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by tanghw** [comment]
用vue create -p dcloudio/uni-preset-vue my-project,选择typescript,然后用hbuildx导入,编译,就报23:29:41.977 Starting type checking service...
23:29:41.991 Using 1 worker with 2048MB memory limit
23:29:47.195 No type errors found
23:29:47.208 Version: typescript 3.4.1
23:29:47.220 Time: 4076ms
23:29:47.227 [tsl] ERROR at main.ts:5
23:29:47.228 TS2304:Cannot find name 'createPage'.
23:29:47.285  ERROR  Error: Build failed with errors.

**Comment by JOU-amjs** [comment]
> 用vue create -p dcloudio/uni-preset-vue my-project,选择typescript,然后用hbuildx导入,编译,就报23:29:41.977 Starting type checking service...
> 23:29:41.991 Using 1 worker with 2048MB memory limit
> 23:29:47.195 No type errors found
> 23:29:47.208 Version: typescript 3.4.1
> 23:29:47.220 Time: 4076ms
> 23:29:47.227 [tsl] ERROR at main.ts:5
> 23:29:47.228 TS2304:Cannot find name 'createPage'.
> 23:29:47.285 ERROR Error: Build failed with errors.

你也是报这个错误吗？现在有解决吗

**Comment by zhetengbiji** [comment]
使用 cli 运行是否正常？如果正常的话，导入 HBuilderX 的时候是怎样导入的？

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
