### ISSUE TITLE
使用的是文晓港的模版 页面局部注册组件不起作用 

### ISSUE THREAD

**Issue by Xubinming** [dcloudio/uni-app#2663]
**问题描述**
查看编译后的文件是有存在引入到了 但是没效果 不管是自定义组件还是引入官方的u-parse组件都是不起效果，但是在main.js里面全局注册组件会出现效果。局部注册和easycom的方式就完成不起作用不知道是我写的有问题还是存在这一的bug

[或者可以直接贴源代码]
![image](https://user-images.githubusercontent.com/35825801/119307798-cface000-bc9e-11eb-8b84-9eb360a34256.png)
![image](https://user-images.githubusercontent.com/35825801/119307918-f539e980-bc9e-11eb-9e9e-31d9c8e53f83.png)

**预期结果**
我这样的使用完成是按照文档的easycom方式引入

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/35825801/119308052-274b4b80-bc9f-11eb-8c5b-6699dcfe1b87.png)
但是页面就是不显示
![image](https://user-images.githubusercontent.com/35825801/119308119-3d590c00-bc9f-11eb-9aea-d2306eb0404d.png)
![image](https://user-images.githubusercontent.com/35825801/119308158-4c3fbe80-bc9f-11eb-9941-f785740d486d.png)

编译出来的是微信小程序
3.1.13.20210514版本的HBuilderX

**Comment by Xubinming** [comment]
有没有大神来解答一下原因啊 被这个问题搞了很久

**Comment by yuconora** [comment]
编译出的组件缺少 content传入
```vue
// 正常编译出来的形式如下
<u-parse vue-id="{{'e95f643c-1-'+index}}" content="{{item}}" class="data-v-5f5527a4" bind:__l="__l"></u-parse>
```
提供的信息太少 无法定位是哪一块出的问题

**Comment by StrivingRabbit** [comment]
使用的什么版本的HX，当时使用的cli项目？使用最新版alpha没有发现此问题

**Comment by Xubinming** [comment]
> 使用什么版本的HX，当时使用的cli项目？使用最新版本alpha测试没有发现这个问题

3.1.13.20210514的HX 没有用工具创建项目 通过命令使用color UI模版来构建项目

**Comment by StrivingRabbit** [comment]
> > 使用什么版本的HX，当时使用的cli项目？使用最新版本alpha测试没有发现这个问题
> 
> 3.1.13.20210514的HX 没有用工具创建项目 通过命令使用color UI模版来构建项目

然后是使用的命令来编译到微信小程序吗？

**Comment by Xubinming** [comment]
不是使用命令编译到小程序 使用的是HX工具的编译

**Comment by Xubinming** [comment]
不是使用命令编译到小程序 使用的是HX工具的编译




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月13日(星期二) 下午5:33
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dcloudio/uni-app] 使用的是文晓港的模版 页面局部注册组件不起作用  (#2663)





   
使用什么版本的HX，当时使用的cli项目？使用最新版本alpha测试没有发现这个问题
  
3.1.13.20210514的HX 没有用工具创建项目 通过命令使用color UI模版来构建项目
  
然后是使用的命令来编译到微信小程序吗？

**Comment by Xubinming** [comment]
不是使用命令编译到小程序 使用的是HX工具的编译

**Comment by StrivingRabbit** [comment]
> 不是使用命令编译到小程序 使用的是HX工具的编译

可否提供一个简单的示例？

**Comment by Xubinming** [comment]
这些自定义的组件 只能在main.js里面注册才能使用

通过uni-app的easycom语法没有效果




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年7月13日(星期二) 晚上6:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dcloudio/uni-app] 使用的是文晓港的模版 页面局部注册组件不起作用  (#2663)





  
不是使用命令编译到小程序 使用的是HX工具的编译
  
可否提供一个简单的示例？
