### ISSUE TITLE
unicloud还能用吗？服务经常不可靠

### ISSUE THREAD

**Issue by githublyp** [dcloudio/uni-app#2664]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看
![image](https://user-images.githubusercontent.com/12792918/119327944-1d811280-bcb6-11eb-9b85-86b418a1dfbb.png)

unicloud后台经常502，今天持续1个小时了，而且官方的公众号都出现问题了，让人担忧cloud服务可靠吗？qq群的管理员基本不回复，不知道uni存在的意思就是挖坑吗？

**Comment by githublyp** [comment]
@hbcui1984 大佬

**Comment by zhetengbiji** [comment]
公众号服务已恢复。

uniCloud 502 为阿里云故障，已由阿里云修复。
