### ISSUE TITLE
uni.canvasToTempFilePath又又又出bug

### ISSUE THREAD

**Issue by Tron1234** [dcloudio/uni-app#2665]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
微信公众号 微信jssdk android端我用的是localIds直接放在img src里面，
                                    iOS端我用的是jssdk里的getLocalImgData转换成base64放在image标签的src中
图片都正常显示，
使用canvas截图同上面一样ctx.drawImage中放的地址android是localIds ios是base64,android调用uni.canvasToTempFilePath就报了这个错误
![image](https://user-images.githubusercontent.com/47961959/119367490-972ff500-bce4-11eb-9093-8219a40f254a.png)
ios则什么都没有，经过测试draw的回调都没有进
![image](https://user-images.githubusercontent.com/47961959/119427961-a479cd80-bd3e-11eb-8a85-ea84e6f2a919.png)
![image](https://user-images.githubusercontent.com/47961959/119428261-24079c80-bd3f-11eb-9a8f-f7859da89df6.png)

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号] 3.1.4
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus] 

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
canvas 无改动，看报错是使用了跨域的图像，你先自行排查一下。若排查不出来，提供一个测试工程。

**Comment by Tron1234** [comment]
使用localIds也属于跨域？？？

**Comment by Tron1234** [comment]
![image](https://user-images.githubusercontent.com/47961959/119433045-025ee300-bd48-11eb-8c28-a71491dbff99.png)

**Comment by zhetengbiji** [comment]
> 使用localIds也属于跨域？？？

你打印一下，看图像的协议域名等和你网页地址的一样吗？

**Comment by Tron1234** [comment]
肯定不一样，微信的localIds是者种格式的
![image](https://user-images.githubusercontent.com/47961959/119433345-a47ecb00-bd48-11eb-923f-79f1220fbec1.png)

**Comment by Tron1234** [comment]
canvas.drawImage那边用的也是这个地址

**Comment by zhetengbiji** [comment]
那就会被浏览器判断为跨域

**Comment by Tron1234** [comment]
需要转成base64？

**Comment by Tron1234** [comment]
ios无法进入draw的回调有可能是什么问题，我排查一下

**Comment by zhetengbiji** [comment]
> ios无法进入draw的回调有可能是什么问题，我排查一下

我猜是绘制未完成

我这边对微信浏览器 jssdk 不是很熟悉，建议你试试 uni.chooseImage 或者请教一下其他使用 jssdk 的开发者。

**Comment by jsonhet** [comment]
我的是canvasId和canvas标签的canvas-id不一致导致的
