### ISSUE TITLE
composition-api 会报onMemoryWarning警告

### ISSUE THREAD

**Issue by alipay404** [dcloudio/uni-app#2666]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 Android 11
 - HBuilderX版本
 - uni-app版本 2.0.0-31920210428001
 - 设备信息 XiaoMi 10

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
只要一使用就报内存不足吗？

**Comment by alipay404** [comment]
> 只要一使用就报内存不足吗？

容易报出内存不足的警告

**Comment by alipay404** [comment]
> 只要一使用就报内存不足吗？

能帮忙反馈下么

**Comment by StrivingRabbit** [comment]
> > 只要一使用就报内存不足吗？
> 
> 能帮忙反馈下么

和我详细的说一下就可以。如果你可以提供一个demo更好了

**Comment by zhetengbiji** [comment]
可以升级新版试一下：https://uniapp.dcloud.net.cn/tutorial/vue-composition-api.html

如仍有问题，描述详细再重启开启
