### ISSUE TITLE
百度小程序生命周期onShareAppMessage中回调函数失效

### ISSUE THREAD

**Issue by mirror29** [dcloudio/uni-app#2668]
**问题描述**
百度小程序生命周期onShareAppMessage中回调函数失效，包括success，fail，complete

**复现步骤**
[复现问题的步骤]
1.  根据文档 https://smartprogram.baidu.com/docs/develop/framework/app_service_pagefunction/ 运行百度小程序官方示例可以成功唤起onShareAppMessage 中回调函数
2. 使用 uni-app 文档  https://uniapp.dcloud.io/api/plugins/share?id=onshareappmessage  编译后无法在百度小程序中获取该回调函数

**预期结果**
能正常获取用户分享状态

**实际结果**
无法获取用户分享状态

**系统信息:**
 - 发行平台:  百度小程序
 - 操作系统 ios 百度12.151.12
 - HBuilderX版本 3.1.12
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**Comment by zhetengbiji** [comment]
https://smartprogram.baidu.com/forum/topic/show/152602
