### ISSUE TITLE
百度小程序swan-sitemap-list组件编译结果有误导致无法发布

### ISSUE THREAD

**Issue by mirror29** [dcloudio/uni-app#2669]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
百度小程序swan-sitemap-list组件编译结果有误导致无法发布，uniapp编译的json在点击发布时会在百度开发者工具报错，结果参考下图
![Snipaste_2021-05-26_09-21-59](https://user-images.githubusercontent.com/26087372/119588893-50392100-be04-11eb-91f7-8c579550f098.png)
根据百度官方文档 https://smartprogram.baidu.com/docs/develop/framework/sitemap/ 可发布成功

**复现步骤**
[复现问题的步骤]
1.  通过uni-app设置百度小程序swan-sitemap-list组件，manifest.json 文件中设置
   `"mp-baidu" : {
        "usingComponents" : true,
        "optimization" : {
            "subPackages" : true
        },
        "dynamicLib" : {
            // 'swan-sitemap-lib' 是个可自己定的别名。
            "swan-sitemap-lib" : {
                // provider 是要引用的动态库的名字，在此为 'swan-sitemap'。
                "provider" : "swan-sitemap"
            }
        },
        "uniStatistics" : {
            "enable" : false
        }
    }`
   page.json 中设置path
  `{
          "path": "index",
          "style": {
            "navigationBarTitleText": "索引页",
            "usingComponents": {
              "swan-sitemap-list": "dynamicLib://swan-sitemap-lib/swan-sitemap-list"
            }
          }
        }`
2. 编译后到百度小程序内查看
3. 点击发布

[或者可以直接贴源代码]

**预期结果**
小程序能正常发布

**实际结果**
小程序未能正常发布，并报错：【调用方错误】swan-sitemap/docIndex.json中，配置的动态库扩展swan-sitemap-list在动态库中不存在，请检查修正后再次发布!

**系统信息:**
 - 发行平台:  百度小程序
 - HBuilderX版本 3.1.13
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
未能按照百度官方文档编译导致

**Comment by StrivingRabbit** [comment]
#2652 同问题，此问题关闭
