### ISSUE TITLE
原生导航栏searchInput，软键盘收起后，安卓系统（小米Redmi 4.x）输入框未失去焦点

### ISSUE THREAD

**Issue by wuchuixu** [dcloudio/uni-app#267]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
pages.json
{
			"path": "pages/search/index",
			"style": {
				"navigationBarTitleText": "搜索",
				"app-plus": {
					"titleNView": {
						"backgroundColor": "#ffffff",
						"searchInput": {
							"autoFocus": true,
							"placeholder": "目的地/关键词",
							"backgroundColor": "#F1F1F1",
							"placeholderColor": "#999999",
							"borderRadius": "16px"
						},
						"buttons": [
							{
								"type": "none",
								"text": "搜索",
								"width": "50px",
								"fontSize": "14px",
								"color": "#1272D3"
							}
						]
					}
				}
			}
		}

pages/search/index.vue

onNavigationBarButtonTap({ index }) {
      uni.hideKeyboard()
    }

**预期结果**
原生导航栏，软键盘收起后，输入框searchInput失去焦点
**实际结果**

原生导航栏searchInput，软键盘收起后，安卓系统（小米Redmi 4.x）输入框未失去焦点
**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 Android 7.0
 - HBuilderX版本 [1.8.1]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [小米Redmi 4.x]
**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
设计如此，例如`微信`、`京东`等应用顶部搜索，在安卓端收起键盘同样不是去焦点
