### ISSUE TITLE
搜索周边的 Wi-Fi，同时可以针对指定 Wi-Fi，传入密码发起连接

### ISSUE THREAD

**Issue by jsonhet** [dcloudio/uni-app#2673]
**新功能描述**
搜索周边的 Wi-Fi，同时可以针对指定 Wi-Fi，传入密码发起连接

**现状及问题**
这个api很重要，微信小程序已经开发这个能力了，强烈建议uniapp的5+api提供相关api
![image](https://user-images.githubusercontent.com/31009976/120128736-527cf000-c1f5-11eb-904a-fc7c5400fc61.png)

**补充信息**
我是一名web开发者，不懂安卓/ios开发，看到uni-app以为看到了app开发的希望，但是发现uni-app做的比较出色的的方面是小程序跨端，而对系统api开放方面似乎并不重视。强烈建议提供这个api，这对相关功能的app很重要

**Comment by ArrayDC** [comment]
请到插件市场 https://ext.dcloud.net.cn/ 搜索相关插件
