### ISSUE TITLE
h5打包失败

### ISSUE THREAD

**Issue by benben77** [dcloudio/uni-app#268]
**问题描述**
构建h5时（npm run build:h5）报错

**复现步骤**
1.  vue-cli-3创建项目：`vue create -p dcloudio/uni-preset-vue my-project`
2. 构建项目：`npm run build:h5`

**预期结果**
成功打包

**实际结果**
打包失败

**系统信息:**
 - 发行平台: h5
 - 操作系统: windows 10
 - uni-app版本：@dcloudio/vue-cli-plugin-hbuilderx@0.9.502

**补充信息**
报错信息：`decl.moveTo is not a function`
来自postcss-merge-rules
依赖关系：
+-- @dcloudio/vue-cli-plugin-hbuilderx@0.9.502

| `-- weex-vue-loader@0.7.0

|   `-- css-loader@0.23.1

|     `-- cssnano@3.10.0

|       `-- postcss-merge-rules@2.1.2

**Comment by xiaoyucoding** [comment]
```
$ npm update
```
更新或者重新创建，是否依旧存在此问题。
