### ISSUE TITLE
picker时间选择器在华为mate30PRO上样式异常

### ISSUE THREAD

**Issue by jie123js** [dcloudio/uni-app#2689]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
能否具体的说明一下，在vue页面还是nvue页面？有没有截图之类的？

**Comment by jie123js** [comment]
现在我一打开居然好了。。好奇怪5.23的时候有bug



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月5日(周六) 下午2:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dcloudio/uni-app] picker时间选择器在华为mate30PRO上样式异常 (#2689)




 
能否具体的说明一下，在vue页面还是nvue页面？有没有截图之类的？

**Comment by StrivingRabbit** [comment]
样式问题是否是发生在wgt热更新之后？

**Comment by jie123js** [comment]
没使用过。。就是用webpack 打包发布的&nbsp;&nbsp;



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月7日(周一) 上午10:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dcloudio/uni-app] picker时间选择器在华为mate30PRO上样式异常 (#2689)




 
样式问题是否是发生在wgt热更新之后？

**Comment by StrivingRabbit** [comment]
好的，那么此问题暂时关闭。如果还出现问题，可以提新的issue或者重开此issue

**Comment by jie123js** [comment]
我想问下，我始终uniapp框架，然后一开始你们的样式在某些手机上出错，但是几天后好了，这是什么情况



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年6月7日(周一) 下午5:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dcloudio/uni-app] picker时间选择器在华为mate30PRO上样式异常 (#2689)




 
Closed #2689.

**Comment by jie123js** [comment]
就是我之前使用你们的picker组件出现了样式很大的问题(没有截图),现在那个样式问题突然就被修复了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dcloudio/uni-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月11日(星期五) 下午3:37
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] picker时间选择器在华为mate30PRO上样式异常 (#2689)





  
我想问下，我始终uniapp框架，然后一开始你们的样式在某些手机上出错，但是几天后好了，这是什么情况
 …
 ---原始邮件--- 发件人: @.&gt; 发送时间: 2021年6月7日(周一) 下午5:24 收件人: @.&gt;; 抄送: @.@.&gt;; 主题: Re: [dcloudio/uni-app] picker时间选择器在华为mate30PRO上样式异常 (#2689) Closed #2689. — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.
  
需要补充详细信息才好分析问题原因。

**Comment by zhetengbiji** [comment]
> 就是我之前使用你们的picker组件出现了样式很大的问题(没有截图),现在那个样式问题突然就被修复了

这里的突然指的是什么情况？是重启还是更新？

**Comment by jie123js** [comment]
就是我们项目会发布版本么.更新代码之类上传新版本(一开始那个样式没解觉,先放着,没管)...后来发布了一个新版本就好了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dcloudio/uni-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月11日(星期五) 下午3:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] picker时间选择器在华为mate30PRO上样式异常 (#2689)





  
就是我之前使用你们的picker组件出现了样式很大的问题(没有截图),现在那个样式问题突然就被修复了
  
这里的突然指的是什么情况？是重启还是更新？

**Comment by zhetengbiji** [comment]
> 就是我们项目会发布版本么.更新代码之类上传新版本(一开始那个样式没解觉,先放着,没管)...后来发布了一个新版本就好了
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "dcloudio/uni-app" ***@***.***&gt;; 发送时间:&nbsp;2021年6月11日(星期五) 下午3:46 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [dcloudio/uni-app] picker时间选择器在华为mate30PRO上样式异常 (#2689) 就是我之前使用你们的picker组件出现了样式很大的问题(没有截图),现在那个样式问题突然就被修复了 这里的突然指的是什么情况？是重启还是更新？ — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

是否更新过 uni-app 框架？如果更新过，可能是框架修复了，看下框架的更新日志。如果没更新过框架可能是之前业务代码有影响到 picker 的或者是之前部署的时候资源有遗漏的。
