### ISSUE TITLE
H5 设置 publicPath，tabBar 依然无效

### ISSUE THREAD

**Issue by edwinhuish** [dcloudio/uni-app#2690]
**问题描述**
npm run build:h5，tabBar 的图片没有安装配置的publicPath正确显示。具体问题和 #707 一致

**复现步骤**
[复现问题的步骤]
1.  manifest.json内配置 "h5": {"publicPath" : "/h5/"}
2. 运行 npm run build:h5 生成代码，并将代码拷贝到网站的 h5 目录下
3. 打开网站 h5 目录的网站路径，如下图， 除tabBar 的图片外，其他图片能够正常显示

![image](https://user-images.githubusercontent.com/5207925/120898777-ff74c400-c65e-11eb-9247-252c80d921b7.png)

**系统信息:**
 - 发行平台: H5平台
 - uni-app版本 ：

uni-app v3.1.13
uni-app cli v2.0.0-31920210514002

Environment Info:

  System:
    OS: Linux 4.19 Debian GNU/Linux 10 (buster) 10 (buster)
    CPU: (4) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.10 - ~/.local/bin/yarn
    npm: 7.15.1 - ~/.local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
  npmPackages:
    @dcloudio/types: * => 2.2.7 
    @dcloudio/uni-app-plus: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-cli-shared: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/uni-h5: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/uni-helper-json: ^1.0.13 => 1.0.13 
    @dcloudio/uni-i18n: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/uni-migration: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/uni-mp-360: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/uni-mp-alipay: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/uni-mp-baidu: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/uni-mp-kuaishou: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/uni-mp-qq: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/uni-mp-toutiao: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/uni-mp-vue: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/uni-mp-weixin: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/uni-quickapp-native: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/uni-quickapp-webview: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/uni-stat: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/uni-template-compiler: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-31920210514002 => 2.0.0-31920210514002 
    @hap-toolkit/dsl-vue:  0.6.13 
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.6 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.13 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.13 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-router:  4.5.13 
    @vue/cli-plugin-vuex:  4.5.13 
    @vue/cli-service: ~4.5.0 => 4.5.13 
    @vue/cli-shared-utils:  4.5.13 
    @vue/component-compiler-utils:  3.2.0 (3.2.0)
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/shared: ^3.0.0 => 3.0.11 
    @vue/web-component-wrapper:  1.3.0 
    eslint-plugin-vue: ^7.10.0 => 7.10.0 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.11 => 2.6.12 
    vue-eslint-parser:  7.6.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.7 (16.2.0, 15.9.7)
    vue-router:  3.0.1 
    vue-style-loader:  4.1.3 (4.1.3)
    vue-template-compiler: ^2.6.11 => 2.6.12 (2.6.12)
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.2.0 => 3.6.2 
  npmGlobalPackages:
    @vue/cli: 4.5.13

**Comment by StrivingRabbit** [comment]
tabbar的icon路径是怎么配置的？

**Comment by edwinhuish** [comment]
@StrivingRabbit 
![image](https://user-images.githubusercontent.com/5207925/120955489-1103bc00-c784-11eb-975e-fea04dc2b3e8.png)

**Comment by StrivingRabbit** [comment]
看你的描述，可以将配置改为：
```json
"h5": {
  "router": {
	  "base": "/h5/"
  }
}
```

**Comment by edwinhuish** [comment]
@StrivingRabbit 我这个 H5 是放在主站的 h5 目录下。 如果设置 router 的base，当api返回 /images/pic.jpg 的图片src时，会自动修改为 /h5/images/pic.jpg，然而这个并不是我需要的。

**Comment by StrivingRabbit** [comment]
> @StrivingRabbit 我这个 H5 是放在主站的 h5 目录下。 如果设置 router 的base，当api返回 /images/pic.jpg 的图片src时，会自动修改为 /h5/images/pic.jpg，然而这个并不是我需要的。

你图片资源在主站`根目录`，但是其他的是放在主站的`h5目录`下的？

**Comment by edwinhuish** [comment]
> > @StrivingRabbit 我这个 H5 是放在主站的 h5 目录下。 如果设置 router 的base，当api返回 /images/pic.jpg 的图片src时，会自动修改为 /h5/images/pic.jpg，然而这个并不是我需要的。
> 
> 你图片资源在主站`根目录`，但是项目是放在主站的`h5目录`下的？还是说`根目录`与`h5目录下`都有需要用到的图片资源？可否具体的描述一下你的网站目录结构？

@StrivingRabbit 项目目录结构是主站是一个正常的PHP站，然后 H5 目录下的是整个H5的代码，包括 H5 的静态资源或者JS,CSS。

但是，H5的内容是通过获取主站的API获取的，这个API是通用API，有相对路径的图片，但是如果修改 router 的base，会导致 H5的router直接将它解析到 H5 目录下了，而不是主站的根目录。

**Comment by StrivingRabbit** [comment]
你如果想又访问H5目录下的资源，又想访问主站根目录下的资源，那么需要访问主站根目录的资源需要加上`http`或者`https`，这样就不会被解析添加`base`了

**Comment by edwinhuish** [comment]
> 你如果想又访问H5目录下的资源，又想访问主站根目录下的资源，那么需要访问主站根目录的资源需要加上`http`或者`https`，这样就不会被解析添加`base`了

前面加http，也就是绝对路径了。这种当然应该没有问题。

本来VUE-CLI 的项目，修改 publicPath 就能达到我刚刚那种需求，但是uni-app除了这个page.json，其他都完全没有问题。

而且。。。为什么要用json这种死格式呢？用 js 格式不是应该更灵活吗？反正都是编译前的文件，根本不会影响编译后的性能啊。。。。

**Comment by zhetengbiji** [comment]
> > 你如果想又访问H5目录下的资源，又想访问主站根目录下的资源，那么需要访问主站根目录的资源需要加上`http`或者`https`，这样就不会被解析添加`base`了
> 
> 前面加http，也就是绝对路径了。这种当然应该没有问题。
> 
> 本来VUE-CLI 的项目，修改 publicPath 就能达到我刚刚那种需求，但是uni-app除了这个page.json，其他都完全没有问题。
> 
> 而且。。。为什么要用json这种死格式呢？用 js 格式不是应该更灵活吗？反正都是编译前的文件，根本不会影响编译后的性能啊。。。。

为了多端统一，与各端小程序对齐，在运行时，路径解析是相对于页面路径的，而不是当前文件路径。后续可能会增加配置项可供调整。

存在 page.js，但未在文档直接公开（未确定）。如需使用可参考： #450 #1764 。

**Comment by edwinhuish** [comment]
> > > 你如果想又访问H5目录下的资源，又想访问主站根目录下的资源，那么需要访问主站根目录的资源需要加上`http`或者`https`，这样就不会被解析添加`base`了
> > 
> > 
> > 前面加http，也就是绝对路径了。这种当然应该没有问题。
> > 本来VUE-CLI 的项目，修改 publicPath 就能达到我刚刚那种需求，但是uni-app除了这个page.json，其他都完全没有问题。
> > 而且。。。为什么要用json这种死格式呢？用 js 格式不是应该更灵活吗？反正都是编译前的文件，根本不会影响编译后的性能啊。。。。
> 
> 为了多端统一，与各端小程序对齐，在运行时，路径解析是相对于页面路径的，而不是当前文件路径。后续可能会增加配置项可供调整。
> 
> 存在 page.js，但未在文档直接公开（未确定）。如需使用可参考： #450 #1764 。

相对于页面路径是能理解的，但是 publicPath 就是更改页面路径了，其他路径在修改 publicPath 都能正常，唯独 page.json 是写死的 '/' 。

关于你所说的page.js，谢谢，我去试试。

**Comment by zhetengbiji** [comment]
> > > > 你如果想又访问H5目录下的资源，又想访问主站根目录下的资源，那么需要访问主站根目录的资源需要加上`http`或者`https`，这样就不会被解析添加`base`了
> > > 
> > > 
> > > 前面加http，也就是绝对路径了。这种当然应该没有问题。
> > > 本来VUE-CLI 的项目，修改 publicPath 就能达到我刚刚那种需求，但是uni-app除了这个page.json，其他都完全没有问题。
> > > 而且。。。为什么要用json这种死格式呢？用 js 格式不是应该更灵活吗？反正都是编译前的文件，根本不会影响编译后的性能啊。。。。
> > 
> > 
> > 为了多端统一，与各端小程序对齐，在运行时，路径解析是相对于页面路径的，而不是当前文件路径。后续可能会增加配置项可供调整。
> > 存在 page.js，但未在文档直接公开（未确定）。如需使用可参考： #450 #1764 。
> 
> 相对于页面路径是能理解的，但是 publicPath 就是更改页面路径了，其他路径在修改 publicPath 都能正常，唯独 page.json 是写死的 '/' 。
> 
> 关于你所说的page.js，谢谢，我去试试。

对，因为 pages 是在编译时解析的。

**Comment by chenghao94** [comment]
@zhetengbiji 请问pages.json里面tabBar里面引用的iconPath路径打包之后的问题，怎么解决的呢
