### ISSUE TITLE
什么时候支持鸿蒙呢？

### ISSUE THREAD

**Issue by yixiong2000** [dcloudio/uni-app#2691]
什么时候支持鸿蒙呢？很期待。

**Comment by qqchuner** [comment]
求支持

**Comment by zhetengbiji** [comment]
理论上可以直接使用，如运行遇到兼容问题，请直接反馈。

**Comment by qqchuner** [comment]
> 理论上可以直接使用，如运行遇到兼容问题，请直接反馈。

你说的安卓的底层，确实可以用。

**Comment by yuangu** [comment]
隔壁的taro已经原生支持了。表示 羡慕啊。 https://www.oschina.net/news/172858/taro-3-5-canary-released

**Comment by Otto-J** [comment]
#4565
