### ISSUE TITLE
uniapp使用插槽问题

### ISSUE THREAD

**Issue by huangjiatian12** [dcloudio/uni-app#2692]
**问题描述**
使用slot插槽功能传递数据时,修改配置文件(比如增加页面修改page.json，修改manifest.json内数据等),会导致slot传递的数据失效

**复现步骤**
index.vue
`\<template>
  \<view class="content">
   \<my-swiper :swiperList="swiperData">
    \<template v-slot="{ itemList }">
     \<swiper-item :list="itemList"></swiper-item>
      \</template>
    \</my-swiper>
  \</view>
\</template>

<script>
import MySwiper from "../../components/swiper";
import swiperItem from "../../components/swiperItem";
export default {
  data() {
    return {
      swiperData: [
        {
          id: 1,
          title: "滴滴滴1",
          list: [
            { id: 1, title: "滴滴滴1-1" },
            { id: 1, title: "滴滴滴1-2" },
            { id: 1, title: "滴滴滴1-3" },
          ],
        },
        {
          id: 2,
          title: "滴滴滴2",
          list: [
            { id: 1, title: "滴滴滴2-1" },
            { id: 1, title: "滴滴滴2-2" },
            { id: 1, title: "滴滴滴2-3" },
          ],
        },
      ],
    };
  },
  components: {
    MySwiper,
    swiperItem,
  },
  onLoad() {},
  methods: {},
};
</script>
`
组件一:swiperItem.vue
`\<template>
  \<view>
    \<view v-for="item in list" :key="item.id">{{ item.title }}</view>
  \</view>
\</template>
<script>
export default {
  props: ["list"],
  data() {
    return {};
  },
};
</script>`
组件二: swiper.vue
`\<template>
  \<view>
    myswiper
    \<view v-for="item in swiperList" :key="item.id">
      \<slot :itemList="item.list"></slot>
    \</view>
  \</view>
\</template>
<script>
export default {
  props: ["swiperList"],
  data() {
    return {};
  }`

**系统信息:**
 - 发行平台: [ 微信小程序]
 - 操作系统 [如 iOS 12.1.2]
 - HBuilderX版本 [3.1.13.20210514]
 - 设备信息 [ iPhone8]

**Comment by ynqq** [comment]
老哥 问题解决了吗 我插槽里面放了个组件 一改pages.json 页面的json文件里面usingComponents就没有那个组件了

**Comment by zhetengbiji** [comment]
> 老哥 问题解决了吗 我插槽里面放了个组件 一改pages.json 页面的json文件里面usingComponents就没有那个组件了

容易复现吗？

**Comment by ynqq** [comment]
> > 老哥问题解决了 我插槽里面放了个组件 一改pages.json 页面的json文件里面usingComponents就没有那个组件了
> 
> 容易复现吗？

很容易复现 改了pages.json 保存就变掉了
我怀疑是我这个uni版本有问题 换个版本打包出来的json文件都不一样了 
又不能随便升级版本 只能把里面的组件拿出来了

**Comment by zhetengbiji** [comment]
> > > 老哥问题解决了 我插槽里面放了个组件 一改pages.json 页面的json文件里面usingComponents就没有那个组件了
> > 
> > 
> > 容易复现吗？
> 
> 很容易复现 改了pages.json 保存就变掉了
> 我怀疑是我这个uni版本有问题 换个版本打包出来的json文件都不一样了
> 又不能随便升级版本 只能把里面的组件拿出来了

这个版本是多少？

**Comment by ynqq** [comment]
> > > > 老哥问题解决了 我插槽里面放了个组件 一改pages.json 页面的json文件里面usingComponents就没有那个组件了
> > > 
> > > 
> > > 容易复现吗？
> > 
> > 
> > 很容易复现 改了pages.json 保存就变掉了
> > 我怀疑是我这个uni版本有问题 换个版本打包出来的json文件都不一样了
> > 又不能随便升级版本 只能把里面的组件拿出来了
> 
> 这个版本是多少？

用的是vue-cli  ^2.0.0-29820201110001

**Comment by zhetengbiji** [comment]
> > > > > 老哥问题解决了 我插槽里面放了个组件 一改pages.json 页面的json文件里面usingComponents就没有那个组件了
> > > > 
> > > > 
> > > > 容易复现吗？
> > > 
> > > 
> > > 很容易复现 改了pages.json 保存就变掉了
> > > 我怀疑是我这个uni版本有问题 换个版本打包出来的json文件都不一样了
> > > 又不能随便升级版本 只能把里面的组件拿出来了
> > 
> > 
> > 这个版本是多少？
> 
> 用的是vue-cli ^2.0.0-29820201110001

把 uni 相关依赖更新到新版试一下 2.0.0-31920210709003

**Comment by ynqq** [comment]
> > > > > > 老哥问题解决了 我插槽里面放了个组件 一改pages.json 页面的json文件里面usingComponents就没有那个组件了
> > > > > 
> > > > > 
> > > > > 容易复现吗？
> > > > 
> > > > 
> > > > 很容易复现 改了pages.json 保存就变掉了
> > > > 我怀疑是我这个uni版本有问题 换个版本打包出来的json文件都不一样了
> > > > 又不能随便升级版本 只能把里面的组件拿出来了
> > > 
> > > 
> > > 这个版本是多少？
> > 
> > 
> > 用的是vue-cli ^2.0.0-29820201110001
> 
> 把 uni 相关依赖更新到新版试一下 2.0.0-31920210709003

我试过这个版本 没问题的 但是项目写了一部分了 不能随便升级 后面看看要不要升级一下 辛苦了 谢谢
