### ISSUE TITLE
onPageShow 编译成支付宝\头条小程序时(其他平台未测试) 不支持

### ISSUE THREAD

**Issue by quiet-jing** [dcloudio/uni-app#2699]
**问题描述**
[问题描述：uni-app组件中监听页面的生命周期onPageShow 编译成微信\百度小程序时是支持该生命周期的 但是在编译成支付宝\头条小程序时(其他平台未测试) 不支持]

**复现步骤**
1. onPageShow 组件监听页面生命周期  不执行该生命周期

**系统信息:**
 - 发行平台: [支付宝\头条小程序]

**补充信息**
[根据你的分析，出现这个问题的原因可能在哪里？]
1. uni-mp-toutiao 代码中 在配置componentOptions节点时与微信\百度一样 配置了pageLifetimes 节点  但是该节点在原生头条 小程序中并不支持 所以导致该问题  
![image](https://user-images.githubusercontent.com/43675851/121336564-39d7ad00-c94e-11eb-9783-68ef85908b71.png)

2. uni-mp-alipay代码中没有对此功能的相关实现

**Comment by Otto-J** [comment]
可以参考这个帖子相关讨论
https://ask.dcloud.net.cn/question/164404

如果仍有问题，请 reopen 或者新开 issue 艾特我。
