### ISSUE TITLE
这些源码怎么运行起来呀，我也想学习学习下

### ISSUE THREAD

**Issue by xiaowang1314** [dcloudio/uni-app#270]
这些源码怎么运行起来呀，我也想学习学习下，我该怎么看懂和运行这个开源代码呀，希望各位大神帮助下小弟。感谢

**Comment by aiplat** [comment]
https://github.com/aiplat/uniapp

**Comment by xiaoyucoding** [comment]
[快速上手](https://uniapp.dcloud.io/quickstart)
