### ISSUE TITLE
编译百度小程序，html 被转成 page，导致rem样式失效

### ISSUE THREAD

**Issue by CaptainLiao** [dcloudio/uni-app#2700]
有如下 css 样式：
````
html {
  font-size: 100px;
}
````
编译成百度小程序后，上面的样式变成了：
````
page {
  font-size: 100px;
}
````

请问为何要更改原来的样式名字呢？

我想保持原样输出，又该如何解决呢？

"@dcloudio/uni-mp-baidu": "^2.0.0-28820200820001",

**Comment by zhetengbiji** [comment]
保留并无用处，小程序不支持此选择器：html

**Comment by CaptainLiao** [comment]
> 保留并无用处，小程序不支持此选择器：html

百度车载小程序支持rem，uniapp编译时把html替换成page后，样式就失效了呀

**Comment by zhetengbiji** [comment]
> > 保留并无用处，小程序不支持此选择器：html
> 
> 百度车载小程序支持rem，uniapp编译时把html替换成page后，样式就失效了呀

你将编译后的 page 手动修改回 html 后可以生效吗？

**Comment by zhetengbiji** [comment]
另外同一个问题请继续在此讨论，无需重复发起

**Comment by CaptainLiao** [comment]
> > > 保留并无用处，小程序不支持此选择器：html
> > 
> > 
> > 百度车载小程序支持rem，uniapp编译时把html替换成page后，样式就失效了呀
> 
> 你将编译后的 page 手动修改回 html 后可以生效吗？

可以生效。在编译后的样式文件中，更改成 html，rem就生效了

**Comment by zhetengbiji** [comment]
> > > > 保留并无用处，小程序不支持此选择器：html
> > > 
> > > 
> > > 百度车载小程序支持rem，uniapp编译时把html替换成page后，样式就失效了呀
> > 
> > 
> > 你将编译后的 page 手动修改回 html 后可以生效吗？
> 
> 可以生效。在编译后的样式文件中，更改成 html，rem就生效了

好的，后续

**Comment by zhetengbiji** [comment]
不过，你设置固定的字体大小，使用 rem 的地方都可以使用 px 替代吧。

**Comment by CaptainLiao** [comment]
> 不过，你设置固定的字体大小，使用 rem 的地方都可以使用 px 替代吧。

没有固定。参见[百度文档](https://sandbox-vehicle.baidu.com/minicloud/developer/docs/zishiying/)

**Comment by zhetengbiji** [comment]
> > 不过，你设置固定的字体大小，使用 rem 的地方都可以使用 px 替代吧。
> 
> 没有固定。参见[百度文档](https://sandbox-vehicle.baidu.com/minicloud/developer/docs/zishiying/)

意思设置这个根字体大小仅仅是为了在不支持自动计算的设备或模拟器上模拟？

**Comment by StrivingRabbit** [comment]
由于长时间未回复，此issue关闭，如果还有问题，可以重开或者提新的issue
