### ISSUE TITLE
html 选择器转成 page，导致百度小程序rem样式失效 

### ISSUE THREAD

**Issue by CaptainLiao** [dcloudio/uni-app#2701]
有如下 css 样式：
````
html {
  font-size: 100px;
}
````
编译成百度小程序后，上面的样式变成了：
````
page {
  font-size: 100px;
}
````

这导致百度小程序rem样式失效 。请问如何解决呢？

"@dcloudio/uni-mp-baidu": "^2.0.0-28820200820001",

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/2700
