### ISSUE TITLE
editor组件在小程序中无法正常渲染 ol li

### ISSUE THREAD

**Issue by Donsome** [dcloudio/uni-app#2703]
- 富文本显示如下
![5MQOJO~2JOHY5B{D_PAOTNB](https://user-images.githubusercontent.com/45633064/121488729-f0e32f80-ca05-11eb-896e-2fe7462858de.png)
- editor打开后,加粗有显示,但是列表就不显示了
![$1{07LU TEOR8 ~7(0Y%AER](https://user-images.githubusercontent.com/45633064/121488787-00627880-ca06-11eb-8025-bf5ea0d2fbea.jpg)
- 所对应的html为
```html
<ol><li>asdf<strong>adfas</strong></li><li><strong>a</strong></li><li><strong>a</strong></li><li><strong>sadf</strong></li></ol>
```

- js设置代码为
```js
setContents(html){
    console.log(html)
    this.editorCtx.setContents({
				    html: html
    });
  }
```

**Comment by zhetengbiji** [comment]
哪个小程序？另外 h5 或者 app 是否正常？

**Comment by Donsome** [comment]
> 哪个小程序？另外 h5 或者 app 是否正常？

-  h5正常

![image](https://user-images.githubusercontent.com/45633064/121645666-0a987b80-cac7-11eb-8d3b-baa5e974dbe3.png)
- 微信小程序不正常
![846804977256179326](https://user-images.githubusercontent.com/45633064/121645959-5f3bf680-cac7-11eb-9379-9a2ce6342a4d.jpg)

**Comment by zhetengbiji** [comment]
> > 哪个小程序？另外 h5 或者 app 是否正常？
> 
> * h5正常
> 
> ![image](https://user-images.githubusercontent.com/45633064/121645666-0a987b80-cac7-11eb-8d3b-baa5e974dbe3.png)
> 
> * 微信小程序不正常
>   ![846804977256179326](https://user-images.githubusercontent.com/45633064/121645959-5f3bf680-cac7-11eb-9379-9a2ce6342a4d.jpg)

微信小程序模拟器还是安卓或者 iOS 有问题？查看微信小程序社区是否有类似问题反馈，如果没有，在那发起新的帖子，等待微信小程序官方人员排查。

**Comment by StrivingRabbit** [comment]
由于长时间没有回复，此issue关闭，如果还有问题可以重开或者提新的issue
