### ISSUE TITLE
uni.chooseImage 第二次无法调起图片选择&拍照界面

### ISSUE THREAD

**Issue by wm20000** [dcloudio/uni-app#2705]
**问题描述**
android嵌入uniapp打包的h5，使用uni.chooseImage 选择图片和拍照。在android里使用，如果选择图片可以正常使用，如果不选择图片，直接返回，再调用uni.chooseImage就无法弹出图片选择框了。
浏览器单独调试h5正常

**复现步骤**
[复现问题的步骤]
1.  调用uni.chooseImage
2. 不做选择，直接返回
3. 再调用uni.chooseImage 不弹出图片选择框

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
没效果，返回再点击也不弹出了，只有杀掉进程重新来才能重复。

**系统信息:**
 - 发行平台: H5
 - 操作系统 android9
 - HBuilderX版本 3.1.13
 - uni-app版本 
 - 设备信息 Mi pad

**补充信息**

**Comment by zhetengbiji** [comment]
是在 [html5 plus](http://www.html5plus.org/doc/h5p.html) 环境中吗？

**Comment by wm20000** [comment]
> 是在 [html5 plus](http://www.html5plus.org/doc/h5p.html) 环境中吗？

不是，是在一个普通的android应用内内置webview里调用的

**Comment by zhetengbiji** [comment]
> > 是在 [html5 plus](http://www.html5plus.org/doc/h5p.html) 环境中吗？
> 
> 不是，是在一个普通的android应用内内置webview里调用的

webview 是没有内置文件选取的，文件选择是由你安卓开发的同事实现的，可能实现的不太稳妥，让他排查一下。

**Comment by zhetengbiji** [comment]
> > 是在 [html5 plus](http://www.html5plus.org/doc/h5p.html) 环境中吗？
> 
> 不是，是在一个普通的android应用内内置webview里调用的

webview 是没有内置文件选取的，文件选择是由你安卓开发的同事实现的，可能实现的不太稳妥，让他排查一下。
