### ISSUE TITLE
H5宽屏适配leftWindow、rightWidow、topWindow存在tabBar不会自动隐藏

### ISSUE THREAD

**Issue by sintrb** [dcloudio/uni-app#2707]
**问题描述**
对于宽屏适配，官方文档上描述的：```H5 宽屏下 tabBar(选项卡) 与窗体的关系：目前做如下调整：leftWindow、rightWindow、topWindow 中有其一存在，则 tabBar 隐藏；不存在，则不隐藏。```
但实际发现tabBar不会因为leftWindow、rightWidow、topWindow的存在而自动隐藏。
原文档见 [宽屏适配指南](https://uniapp.dcloud.net.cn/adapt)

**复现步骤**
1.新建uni-app项目，选择支持PC和nvue的新闻类模板。创建工程之后在pages.json上增加下面的tabBar代码：
```json
  "tabBar": {
  	"color": "#C0C4CC",
  	"selectedColor": "#10BC56",
  	"borderStyle": "black",
  	"backgroundColor": "#ffffff",
  	"list": [
  		{
  			"pagePath": "pages/news/index",
  			"text": "Tab1"
  		},
  		{
  			"pagePath": "pages/ucenter/ucenter",
  			"text": "Tab2"
  		}
  	]
  },
```
2.运行项目到浏览器，切换为PC模式，调整窗口大小，可以看到，进入宽屏适配模式（rightWindow已经显示），底部的tabBar还依然显示，和文档描述不一致，而且也没法用。

**预期结果**
宽屏模式时底部的tabBar隐藏

**实际结果**
没有隐藏，依然显示。实测leftWindow、rightWidow、topWindow的出现都不会让tabBar隐藏。
![结果](https://ishop-static-qn.inruan.com/Fu90DoGR2gjcKvRQKixfl1gq3l0U.png)

**系统信息:**
 - 发行平台: H5
 - HBuilderX版本: Mac 3.1.18.20210609
 - uni-app版本: missing script: info

**Comment by Fasttian** [comment]
H5 宽屏下 tabBar(选项卡) 与 窗口的关系已做调整，目前两者没有任何关系，如果想让 tabBar 显示或隐藏，参考：

__H5 宽屏下 tabBar(选项卡) 的显示与隐藏__

如果在 PC 上不想显示 tabbar 页面可以参考 hello-uniapp，在 app 的首页加载时跳转一个 非tabbar 页, [hello-uniapp](https://hellouniapp.dcloud.net.cn/) 的隐藏 tabbar 不是媒体查询实现的，当前页不是 tabbar 页面（是pages/component/view/view页），所以没有显示tabbar。

如果是想在有 leftwindow 等窗体的时候，隐藏 tabar 页面的 tabbar，可以用 css 实现（好处是可以和leftwindow等窗体联动）：

```html
  .uni-app--showleftwindow + .uni-tabbar-bottom {
  	display: none;
  }
```
