### ISSUE TITLE
canvas 在调用clip剪切后调用drawImage绘制图片无法在封闭选区内绘制

### ISSUE THREAD

**Issue by woleicom** [dcloudio/uni-app#2708]
**问题描述**
canvas 在调用clip剪切后调用drawImage绘制图片无法在封闭选区内绘制
目前需要调用stroke或者fill才可以，但是这样会有边线产生

**复现步骤**
[复现问题的步骤]
![image](https://user-images.githubusercontent.com/9603048/122016053-426b3000-cdf3-11eb-8133-2d927ae6c916.png)
以上代码图片会超出clip剪切的选取
![image](https://user-images.githubusercontent.com/9603048/122016173-629aef00-cdf3-11eb-86be-acb6502d244a.png)
图中红框的地方以及粉色三角do都是已经超出了clip的区域
还有如果用fill纯色绘制，也会有漏边的现象，这在网页canvas绘制中是不会出现的
![image](https://user-images.githubusercontent.com/9603048/122016281-7e9e9080-cdf3-11eb-959e-0ac39ff48499.png)
![image](https://user-images.githubusercontent.com/9603048/122016303-852d0800-cdf3-11eb-89ac-82b3bff587f1.png)

```
ctx.save()
    ctx.moveTo(100,100)
    ctx.lineTo(500,100)
    ctx.lineTo(100,500)
    // ctx.fill()
    ctx.clip()
    ctx.stroke()
    ctx.drawImage(image.path, 0, 0, image.width, image.height, 100,100, 400,400)
    this.ctx.draw(true)
    ctx.restore()
    ctx.save()
    ctx.moveTo(500,100)
    ctx.lineTo(500,500)
    ctx.lineTo(100,500)
    // ctx.fill()
    ctx.clip()
    ctx.drawImage(image.path, 0, 0, image.width, image.height, 100,100, 400,400)
    this.ctx.draw(true)
    ctx.restore()
```

**预期结果**
图片在clip中绘制，或者不产生缝合边空隙

**实际结果**
图片不在clip里绘制，产生了缝合边空隙

**系统信息:**
 - 发行平台: 微信小程序、H5平台
 - 操作系统 小程序、网页
 - uni-app版本
 ```
uni-app v3.1.17
uni-app cli v2.0.0-31920210607001

Environment Info:

  System:
    OS: macOS 11.2.2
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
  Binaries:
    Node: 12.13.0 - /usr/local/bin/node
    Yarn: 1.19.1 - /usr/local/bin/yarn
    npm: 6.12.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 91.0.4472.101
    Firefox: 84.0.2
    Safari: 14.0.3
```

**Comment by StrivingRabbit** [comment]
运行在哪端？
