### ISSUE TITLE
从 HTML 向应用发送消息 没有反应

### ISSUE THREAD

**Issue by 17721524631** [dcloudio/uni-app#2709]
![image](https://user-images.githubusercontent.com/35061684/122023803-7433c500-cdfa-11eb-9861-3d1f916c1cca.png)
官方文档 从 HTML 向应用发送消息 没有反应

以下是代码
![image](https://user-images.githubusercontent.com/35061684/122023873-87df2b80-cdfa-11eb-989b-ac4e651d00a6.png)
![image](https://user-images.githubusercontent.com/35061684/122023965-9b8a9200-cdfa-11eb-97bd-b7c79555c7a6.png)
![image](https://user-images.githubusercontent.com/35061684/122024293-df7d9700-cdfa-11eb-9f1b-3a3e3819c849.png)
![image](https://user-images.githubusercontent.com/35061684/122024064-ae04cb80-cdfa-11eb-8a4e-c94f39260bcc.png)

**Comment by StrivingRabbit** [comment]
H5不支持`@message`，可以使用`window.postMessage`

**Comment by linxiang07** [comment]
> H5不支持`@message`，可以使用`window.postMessage`

怎么用

**Comment by linxiang07** [comment]
> H5不支持`@message`，可以使用`window.postMessage`

文档上说要使用window.postMessage，但是如何使用是让我感到困惑的，能提供一个demo吗

**Comment by StrivingRabbit** [comment]
发：window.postMessage

收：window.addEventListener("message", () => {}, false);

你试试
