### ISSUE TITLE
uni-app 如何实时监测vue的data数据变动

### ISSUE THREAD

**Issue by JoeshuTT** [dcloudio/uni-app#271]
**新功能描述**
uni-app 如何实时监测vue的页面data数据变动

**现状及问题**
之前单端开发,
H5端基于vue.js开发,有Vue devTools插件来帮助查看页面数据变动,
小程序端有开发者工具AppData帮助查看页面数据变动  

现在
uni-app在谷歌浏览器中调试并且安装过vue.js devTools插件的情况下，
是不能看到页面数据变动，但是你像vuex的数据还是都能够看到的

**Comment by zhetengbiji** [comment]
开发模式下 devTools 是有效的

**Comment by JoeshuTT** [comment]
现在确实能调试到页面data了,(不知道是我当初没找到,还是官方修复过了,3个月了已经)谢谢老哥

**Comment by JoeshuTT** [comment]
> 开发模式下 devTools 是有效的

现在确实能调试到页面data了,(不知道是我当初没找到,还是官方修复过了,3个月了已经)谢谢老哥

**Comment by kunjiang** [comment]
> > 开发模式下 devTools 是有效的
> 
> 现在确实能调试到页面data了,(不知道是我当初没找到,还是官方修复过了,3个月了已经)谢谢老哥

查看 vue 的数据是不是必须使用浏览器预览, 并使用浏览器的调试工具才可以啊? 谢谢!

**Comment by JoeshuTT** [comment]
各个平台有

> > > 开发模式下 devTools 是有效的
> > 
> > 
> > 现在确实能调试到页面data了,(不知道是我当初没找到,还是官方修复过了,3个月了已经)谢谢老哥
> 
> 查看 vue 的数据是不是必须使用浏览器预览, 并使用浏览器的调试工具才可以啊? 谢谢!
不是啊 各个平台都有查看数据的方式,h5平台是用 Vue devTools,小程序端有微信小程序开发工具也可以看的
