### ISSUE TITLE
希望能支持基础宽度自定义而不是固定的750

### ISSUE THREAD

**Issue by yangdan8** [dcloudio/uni-app#2710]
**新功能描述**
简洁描述你希望补充完善的增强功能

**现状及问题**
[当前现状及由此导致的不便]
当前需要前端同学自己讲UI给的尺寸转成750px的尺寸下的元素尺寸，比如我们UI就是按照1080设计的，转出来一堆的小数，调试还很不方便，因为显示的值和UI的值又不一致

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by zhetengbiji** [comment]
rpx 是微信小程序定义的宽度固定 750 等分，按 1080 设计的可能并不适用于使用 rpx，不建议硬套。

你可以具体说一下，如有必要可以上传一张设计图示例，帮你参考一下更合适的方案。
