### ISSUE TITLE
google play, 上传不了新的版本, 您的 App Bundle 中包含以下无法识别的语言：zz

### ISSUE THREAD

**Issue by huifukejian** [dcloudio/uni-app#2712]
**问题描述**
您的 App Bundle 中包含以下无法识别的语言：zz。如需查看受支持语言代码的列表，请转到 IANA 注册表。您可以使用 Gradle 属性 resConfigs 排除因第三方库而引入的无效语言。

把app上传到google play上提示这个, 我们的app集成了push, 一键登录, 从HbuildX 打play市场的包从apk换成aab开始的. 现在项目上不了线, 真的急

**Comment by ArrayDC** [comment]
HBuilderX3.1.22+版本已修复此问题
