### ISSUE TITLE
Property 'getUserProfile' does not exist on type 'Uni'

### ISSUE THREAD

**Issue by StevenHX** [dcloudio/uni-app#2714]
1.已经把微信开发工具和Hbuilder升级到最新了，还是报这个错
2.调试可以运行，发行打包就不行
![image](https://user-images.githubusercontent.com/19686601/122352405-afaccb80-cf81-11eb-9d28-ad3d47a4de35.png)

**Comment by StrivingRabbit** [comment]
使用的什么版本的HX打包的？
