### ISSUE TITLE
t.requireNativePlugin is not a function

### ISSUE THREAD

**Issue by social-uni** [dcloudio/uni-app#2717]
使用了 uni-popup 后页面报错，t.requireNativePlugin is not a function

相似bug 

https://gitee.com/dcloud/uni-app/issues/I3OPTQ

原提问

https://github.com/dcloudio/uni-ui/issues/329

**Comment by mehaotian** [comment]
在根目录下新建 vue.config.js ，添加配置
```javascript
module.exports = {
    transpileDependencies: ['@dcloudio/uni-ui']
}
```
如果不行的话，看下配置文件是否正确

**Comment by social-uni** [comment]
> 在根目录下新建 vue.config.js ，添加配置
> 
> ```js
> module.exports = {
>     transpileDependencies: ['@dcloudio/uni-ui']
> }
> ```
> 
> 如果不行的话，看下配置文件是否正确

可以解决
