### ISSUE TITLE
uniapp 音频组件 createInnerAudioContext 在iOS 播放 返回异常 MediaError -6

### ISSUE THREAD

**Issue by michaeltx** [dcloudio/uni-app#2718]
**问题描述**
基于 3.1.18 版本，运行程序到 iphone XR ，音频播放时出错: 异常 MediaError -6
ios 版本 14.2

初步测试跟 音频地址有关系。
可以正常播放的音频：
innerAudioContext.src = "https://www.widex.com.cn//-/media/components/domain/hearingtest/audio/cn/speechinnoise/stereo/4.mp3";

出现异常的地址：
http://124.71.183.68:80/liurs-rgw-bucket/xbzk/f5229ebb80d174229127a18895ca4d64.mp3?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20210618T223059Z&X-Amz-SignedHeaders=host&X-Amz-Expires=604800&X-Amz-Credential=4QMHK2ACD4EIBLDDPJ66%2F20210618%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=55b77e2784e807c90e9c6ab8121d0fe0a04be5e2ee70b9e9f274c0750f8a840f

**Comment by michaeltx** [comment]
![image](https://user-images.githubusercontent.com/14890985/122676520-0a0f8b80-d211-11eb-87de-42a09ae63fac.png)

**Comment by michaeltx** [comment]
![image](https://user-images.githubusercontent.com/14890985/122676546-24e20000-d211-11eb-9ae6-eb91be02c9eb.png)
![image](https://user-images.githubusercontent.com/14890985/122676569-375c3980-d211-11eb-86f1-948682e768a0.png)

**Comment by michaeltx** [comment]
添加debug图片

**Comment by dcloudhdx** [comment]
上面异常的地址无法正常访问，请确认是否需要授权登陆

**Comment by dcloudhdx** [comment]
由于长时间无回复，暂时关闭，如有问题请重新打开
