### ISSUE TITLE
tabBar不显示

### ISSUE THREAD

**Issue by wenji-my** [dcloudio/uni-app#272]
**问题描述**
我在pages.json里配置了tabBar，但是界面上没显示出来，麻烦大神帮我看看是什么问题？

**复现步骤**
[复现问题的步骤]
1.  新建uni-app项目，默认模版
2. 在pages.json配置了tabBar
3. 运行到chrome浏览器

````
"tabBar": {
		"color": "#7A7E83",
		"selectedColor": "#007AFF",
		"borderStyle": "black",
		"backgroundColor": "#F8F8F8",
		"list": [{
				"pagePath": "pages/tabBar/assets/assets",
				"iconPath": "static/component.png",
				"selectedIconPath": "static/componentHL.png",
				"text": "内置组件"
			},
			{
				"pagePath": "pages/tabBar/market/market",
				"iconPath": "static/component.png",
				"selectedIconPath": "static/componentHL.png",
				"text": "接口"
			}
		]
	}
````

**预期结果**
底部有一个tabBar，可以切换页面

**实际结果**
没有tabBar
![QQ20190403-142105](https://user-images.githubusercontent.com/22883182/55457186-c4f4e400-561b-11e9-9832-fd9b6e2b733b.png)

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 mac OS 10.13.6
 - HBuilderX版本 1.8.2.20190401
 - uni-app版本 未知(直接用HBuilderX新建的项目)

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by yuxilins** [comment]
我也是

**Comment by tangshichun** [comment]
怎么解决的

**Comment by jackyhanyu** [comment]
pages数组中第一项表示应用启动页,而不是tabbar list中的第一个项。应该把pages中的第一项和ltab bar list中的第一项，保持一致。而且从源码看，uni-tab bar 的display none,会误导，以为是css的问题。我是uni app新手，类似的问题是这么解决的。

**Comment by saifeiLee** [comment]
大家怎么解决的？

**Comment by hugetiny** [comment]
如果默认display none,就很奇怪，不知道官方怎么回复下

**Comment by yyidota** [comment]
编译后你们看看对应目录里面有没有你们的图标
