### ISSUE TITLE
uniapp，微信小程序下，不支持在模板语法中直接访问全局变量

### ISSUE THREAD

**Issue by social-uni** [dcloudio/uni-app#2721]
代码，onLoad中给vue原型赋值，this.haha可以输出，可是在界面的模板语法中显示undefined
```
  onLoad() {
    Vue.prototype.haha = 'haha'
    console.log(this.haha)
  }
```
以下三个在模板语法中均为 undefined
```
      {{haha}}
      {{this}}
      {{this.haha}}
```

![image](https://user-images.githubusercontent.com/14007972/122867426-0e948b00-d35c-11eb-9344-28a5c65fba55.png)

**Comment by social-uni** [comment]
> 测试未复现问题，使用新版HBuilderX测试一下，若仍有问题，提供一个测试示例

相似问题 ，1 [挂载数据到Vue.prototype上，view无法映射](https://github.com/dcloudio/uni-app/issues/1361)

#1361

2 [uniapp，微信小程序下，不支持在模板语法中直接访问全局变量](https://github.com/dcloudio/uni-app/issues/2721)

#2721

**Comment by yuconora** [comment]
....为啥要这样写 给vue原型赋值 放在 main.js 里面 ，组件调用的时候  类似 vuex 写法 加个 computed 就能访问啊  属性在原型上并没有直接添加到组件上 模版语法访问不到

```js
// main.js
import Vue from 'vue'
import App from './App'

Vue.config.productionTip = false

Vue.prototype.$haha = 'haha'

App.mpType = 'app'

const app = new Vue({
  ...App
})
app.$mount()
```

```vue
// component.vue
<template>
  <view class="content">
     <!--      <view class="title">{{ $haha }}</view>-->
      <view class="title">{{ haha }}</view>
  </view>
</template>

<script>
export default {
  data() {
    return {
      key: '',
    };
  }, 
  computed: {
    haha() {
      return this.$haha
    }
  },
  onLoad() {
  },
  methods: {},
};
</script>

```

**Comment by social-uni** [comment]
> ....为啥要这样写 给vue原型赋值 放在 main.js 里面 ，组件调用的时候 类似 vuex 写法 加个 computed 就能访问啊 属性在原型上并没有直接添加到组件上 模版语法访问不到
> 
> ```js
> // main.js
> import Vue from 'vue'
> import App from './App'
> 
> Vue.config.productionTip = false
> 
> Vue.prototype.$haha = 'haha'
> 
> App.mpType = 'app'
> 
> const app = new Vue({
>   ...App
> })
> app.$mount()
> ```
> 
> ```
> // component.vue
> <template>
>   <view class="content">
>      
>       <view class="title">{{ haha }}</view>
>   </view>
> </template>
> 
> <script>
> export default {
>   data() {
>     return {
>       key: '',
>     };
>   }, 
>   computed: {
>     haha() {
>       return this.$haha
>     }
>   },
>   onLoad() {
>   },
>   methods: {},
> };
> </script>
> ```

使用其他办法是可以避免的，但这是个bug，h5是没有问题的

**Comment by StrivingRabbit** [comment]
1. 微信小程序的模板中并没有this
2. 编译到微信小程序是需要映射到data中的，`Vue.prototype.haha = 'haha'`这样写一下，是不支持直接访问的。

**Comment by social-uni** [comment]
@hbcui1984 @zhetengbiji   请问这个bug被关了，是修复好了吗

**Comment by social-uni** [comment]
![image](https://user-images.githubusercontent.com/14007972/132202726-d7d95585-4218-4145-933e-d7df10a124e8.png)

官方回复，因微信小程序平台不支持，这个无法修复， 贴下，以免以后有兄弟有类似疑问
