### ISSUE TITLE
能否提供命令行或npm script的方式构建apk或ipa

### ISSUE THREAD

**Issue by webxmsj** [dcloudio/uni-app#2728]
**新功能描述**
简洁描述你希望补充完善的增强功能

**现状及问题**
不太想转换熟悉的代码编辑器,  但是期望能够采用uniapp强大的跨端能力, 系统已经安装好相关本地构建的程序及依赖

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by StrivingRabbit** [comment]
[cli打包](https://hx.dcloud.net.cn/cli/pack)

**Comment by CNMathon** [comment]
> [cli打包](https://hx.dcloud.net.cn/cli/pack)

@StrivingRabbit 当前 CLI 似乎不提供开发环境的热更新能力
