### ISSUE TITLE
autoBackButton:false 不生效

### ISSUE THREAD

**Issue by rockey2020** [dcloudio/uni-app#2729]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

uni-app v3.1.18
uni-app cli v2.0.0-31920210609001

Environment Info:

  System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-8850H CPU @ 2.60GHz
  Binaries:
    Node: 16.3.0 - /usr/local/bin/node
    Yarn: 1.22.10 - /usr/local/bin/yarn
    npm: 7.15.1 - /usr/local/bin/npm
  Browsers:
    Chrome: 90.0.4430.93
    Firefox: Not Found
    Safari: 14.1.1
  npmPackages:
    @dcloudio/types: * => 2.2.7 
    @dcloudio/uni-app-plus: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-automator: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/uni-cli-shared: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/uni-h5: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/uni-helper-json: * => 1.0.13 
    @dcloudio/uni-i18n: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/uni-migration: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/uni-mp-360: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/uni-mp-alipay: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/uni-mp-baidu: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/uni-mp-kuaishou: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/uni-mp-qq: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/uni-mp-toutiao: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/uni-mp-vue: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/uni-mp-weixin: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/uni-quickapp-native: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/uni-quickapp-webview: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/uni-stat: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/uni-template-compiler: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-31920210609001 => 2.0.0-31920210609001 
    @hap-toolkit/dsl-vue:  0.6.13 
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  3.12.1 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  3.12.1 
    @vue/cli-plugin-babel: ~3.12.1 => 3.12.1 
    @vue/cli-service: ~3.12.1 => 3.12.1 
    @vue/cli-shared-utils:  3.12.1 
    @vue/component-compiler-utils:  3.2.0 (3.2.0)
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/shared: ^3.0.11 => 3.0.11 
    @vue/web-component-wrapper:  1.3.0 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.13 => 2.6.14 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.7 (15.9.7)
    vue-router:  3.0.1 
    vue-style-loader:  4.1.3 (4.1.3)
    vue-template-compiler: ^2.6.13 => 2.6.13 (2.6.13)
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.6.2 => 3.6.2 
  npmGlobalPackages:
    @vue/cli: 4.5.13

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

这个问题我看到之前也有人反馈,而且你们很多bug都是反反复复,这个版本修好了,下一个版本又出现......真的很无语

**Comment by rockey2020** [comment]
![image](https://user-images.githubusercontent.com/64777114/123442993-0c565900-d608-11eb-8174-9116c628cd48.png)

**Comment by rockey2020** [comment]
![image](https://user-images.githubusercontent.com/64777114/123443057-1d9f6580-d608-11eb-83ee-b712c94910ee.png)

**Comment by StrivingRabbit** [comment]
具体说明一下什么手机、型号、系统版本等信息，经测试并没有复现此问题
