### ISSUE TITLE
uni app canvas 的长宽会自动乘以 dpr 来高清化

### ISSUE THREAD

**Issue by ExiaGo** [dcloudio/uni-app#2733]
**新功能描述**
简洁描述你希望补充完善的增强功能

**现状及问题**
[当前现状及由此导致的不便]
有时候不需要这么大的 canvas，因为 iOS 最大 canvas 是 4096 x 4096 这样各再乘以 3 就会出问题了，会提示画布过大

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]
希望能有个参数是否需要 canvas 高清化

**补充信息**
[其它你认为有参考价值的信息]

**Comment by dcloudhdx** [comment]
1. 后续会提供是否开启高清的配置
2. 什么需求需要设置这么大的 `canvas` ？

**Comment by ExiaGo** [comment]
> 1. 后续会提供是否开启高清的配置
> 2. 什么需求需要设置这么大的 `canvas` ？

十分感谢，其实是合成一幅可印刷的手机壳图片，一般来说画布需要某些特定的尺寸。

**Comment by zhetengbiji** [comment]
HBuilderX alpha 3.4.0+ 已支持
