### ISSUE TITLE
uni.uploadFile 在h5下面不带上cookie

### ISSUE THREAD

**Issue by wzhsh90** [dcloudio/uni-app#2737]
没有withCredentials:true 选项

**Comment by zhetengbiji** [comment]
暂未提供，目前可以直接使用 xhr 或使用其他任意 ajax 库

**Comment by wzhsh90** [comment]
后端response 里面返回了cookie 的，为什么uni-request的返回值header 没有cookie 属性呢？

**Comment by zhetengbiji** [comment]
> 后端response 里面返回了cookie 的，为什么uni-request的返回值header 没有cookie 属性呢？

麻烦看下文档

**Comment by wzhsh90** [comment]
根据 W3C 规范，H5 端无法获取 response header 中 Set-Cookie、Set-Cookie2 这2个字段，对于跨域请求，允许获取的 response header 字段只限于“simple response header”和“Access-Control-Expose-Headers”（详情）
看到了
