### ISSUE TITLE
uni.sendNativeEvent 不能给原生Android 10 发消息 

### ISSUE THREAD

**Issue by fxh615** [dcloudio/uni-app#2738]
uni-app 混合应用启动的时候，可以点击摸个按钮发送消息。通知打开原生的页面。重新切回uni-app 页面。然后黑屏去休息一会儿，回来发现按钮点不动了。最新的HB

**Comment by StrivingRabbit** [comment]
1. 点不动了是什么表现？点击后没有触发事件，还是触发事件了但是没有发送成功消息，还是发送成功消息但是没有接收到？
2. 使用try catch包裹一下，看看有没有什么报错
