### ISSUE TITLE
通过vue-cli命令行形式无法进行app打包

### ISSUE THREAD

**Issue by weiyunpeng** [dcloudio/uni-app#274]
**问题描述**

通过vue-cli命令行形式无法进行app打包

**预期结果**
可以实现cli形式进行打包

**实际结果**
`$ cross-env NODE_ENV=production UNI_PLATFORM=app-plus vue-cli-service uni-build
请使用 HBuilderX 编译运行至 app-plus 平台

Total task duration: 4.62s`

**Comment by aiplat** [comment]
不可能的。这只能HX打包。

**Comment by xiaoyucoding** [comment]
不支持通过 cli 打包 App，需要拖到 HBuilderX 进行打包 App 的操作。

**Comment by weiyunpeng** [comment]
> 不支持通过 cli 直接打包 App，需要拖到 HBuilderX 进行打包 App 的操作。

那用linux系统的想打包app就比较困难了。

**Comment by xiaoyucoding** [comment]
> > 不支持通过 cli 直接打包 App，需要拖到 HBuilderX 进行打包 App 的操作。
> 
> 那用linux系统的想打包app就比较困难了。

linux 版的 HBuilderX 在筹划中，如果有打包 App 需求请切换至 windows 或 mac os 下。
