### ISSUE TITLE
uni.openSetting的属性缺少

### ISSUE THREAD

**Issue by weixisheng** [dcloudio/uni-app#2740]
**问题描述**
文档中`uni.openSetting()`没有微信小程序平台的`withSubscriptions`选项，且`TypeScript`缺少类型支持。

**复现步骤**
```js
uni.openSetting({
    withSubscriptions: true,
    complete() {
       // do sth.
    }
})
```
**预期结果**
`uni.openSetting()`支持`withSubscriptions`选项，`TypeScript`下不会提示错误。

**实际结果**
![image](https://user-images.githubusercontent.com/16042305/124212133-fde4d180-db20-11eb-8f0c-ddc940baa20d.png)

**Comment by StrivingRabbit** [comment]
已提交，后续发布

**Comment by StrivingRabbit** [comment]
types已发布，可以更新试试，如果有问题可以重开此issue
