### ISSUE TITLE
【sos】uniapp vue开发的app项目，华为手机上input输入框卡顿，没有做任何交互以及动画。其它手机都没问题

### ISSUE THREAD

**Issue by chenjincodes** [dcloudio/uni-app#2741]
**问题描述**
【app项目，华为手机上input输入框卡顿，没有做任何交互以及动画。其它手机都没问题】

-----------------------------------------------
【main】【page.json】【app.vue】【login.vue】
本着最小可行原则，把代码撤回到最早版本，问题依旧存在。这是底层系统层面的问题了吧

![image](https://user-images.githubusercontent.com/23471323/124339857-d440ae80-dbe3-11eb-89ce-8a993ef0cfb5.png)

**预期结果**
预期结果：输入【520520520】
![image](https://user-images.githubusercontent.com/23471323/124340154-be33ed80-dbe5-11eb-8c37-e5e17e7184e2.png)

**实际结果**
实际结果是：很卡顿，并且显示的是【520500】
![image](https://user-images.githubusercontent.com/23471323/124340163-c724bf00-dbe5-11eb-97d3-caab9dccbeb6.png)

**系统信息:**
 - 发行平台：App（vue）
 - 操作系统：Android 10
 - HBuilderX版本：3.0.7.20210123
 - uni-app版本：应该是较新的版本，2021年年初初始化的项目
 - 设备信息：HONOR X10

**Comment by StrivingRabbit** [comment]
1. 手机具体型号
2. 华为其他手机是否有卡顿问题？
3. 下载最新的`alpha`试试
