### ISSUE TITLE
微信小程序登录，云函数调用uniID.loginByWeixin，type是login，响应字段中userInfo并不包含用户信息

### ISSUE THREAD

**Issue by danielesk** [dcloudio/uni-app#2742]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
微信小程序登录，云函数调用uniID.loginByWeixin，type是login，应该返回全部用户信息

**实际结果**
实际上只是返回了几个字段
last_login_date
last_login_ip
register_date
register_ip
token
wx_openid
_id
并没有返回全部用户信息，如头像、昵称等

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: 安卓 ios都会出现
 - HBuilderX版本 3.1.18.20210609
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
目前有返回accessToken，如果需要获取用户信息可以自行获取
