### ISSUE TITLE
执行 uniCloud.callFunction({ name: 'check-version', ... 报错 TypeError: u is not a function

### ISSUE THREAD

**Issue by MuNan777** [dcloudio/uni-app#2743]
**问题描述**
在 App.vue 中执行 uniCloud.callFunction({ name: 'check-version' 报错

**复现步骤**
![image](https://user-images.githubusercontent.com/34822980/124361714-13faab00-dc63-11eb-8cb8-0015dffc14b3.png)
内置浏览器运行

**预期结果**
![image](https://user-images.githubusercontent.com/34822980/124361735-2ffe4c80-dc63-11eb-94b8-350099b97424.png)

**实际结果**
![image](https://user-images.githubusercontent.com/34822980/124361742-3ee4ff00-dc63-11eb-9a90-cc0ce51e18c7.png)

**系统信息:**
 - HBuilderX版本 3.1.18
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - System:
    OS: Windows 10
    CPU: (16) x64 AMD Ryzen 7 5800H with Radeon Graphics
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.19041.1023.0
  npmPackages:
    @dcloudio/types: ^2.2.18 => 2.2.18
    @dcloudio/uni-app-plus: ^2.0.0-31920210609001 => 2.0.0-31920210609001
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-automator: ^2.0.0-31920210609001 => 2.0.0-31920210609001
    @dcloudio/uni-cli-shared: ^2.0.0-31920210609001 => 2.0.0-31920210609001
    @dcloudio/uni-h5: ^2.0.0-31920210609001 => 2.0.0-31920210609001
    @dcloudio/uni-helper-json: * => 1.0.13
    @dcloudio/uni-i18n:  0.0.3
    @dcloudio/uni-migration: ^2.0.0-31920210609001 => 2.0.0-31920210609001
    @dcloudio/uni-mp-360: ^2.0.0-31920210609001 => 2.0.0-31920210609001
    @dcloudio/uni-mp-alipay: ^2.0.0-31920210609001 => 2.0.0-31920210609001
    @dcloudio/uni-mp-baidu: ^2.0.0-31920210609001 => 2.0.0-31920210609001
    @dcloudio/uni-mp-qq: ^2.0.0-31920210609001 => 2.0.0-31920210609001
    @dcloudio/uni-mp-toutiao: ^2.0.0-31920210609001 => 2.0.0-31920210609001
    @dcloudio/uni-mp-vue: ^2.0.0-31920210609001 => 2.0.0-31920210609001
    @dcloudio/uni-mp-weixin: ^2.0.0-31920210609001 => 2.0.0-31920210609001
    @dcloudio/uni-quickapp-native: ^2.0.0-31920210609001 => 2.0.0-31920210609001
    @dcloudio/uni-quickapp-webview: ^2.0.0-31920210609001 => 2.0.0-31920210609001
    @dcloudio/uni-stat: ^2.0.0-31920210609001 => 2.0.0-31920210609001 (2.0.0)
    @dcloudio/uni-template-compiler: ^2.0.0-31920210609001 => 2.0.0-31920210609001
    @dcloudio/uni-ui: ^1.3.5 => 1.3.5
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-31920210609001 => 2.0.0-31920210609001
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-31920210609001 => 2.0.0
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-31920210609001 => 2.0.0-31920210609001
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-31920210609001 => 2.0.0-31920210609001
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-31920210609001 => 2.0.0-31920210609001
    @hap-toolkit/dsl-vue:  0.6.13
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.0.6
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.13
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.13
    @vue/cli-plugin-babel: ^4.5.13 => 4.5.13
    @vue/cli-plugin-router:  4.5.13
    @vue/cli-plugin-typescript: ^4.5.13 => 4.5.13
    @vue/cli-plugin-vuex:  4.5.13
    @vue/cli-service: ^4.5.13 => 4.5.13
    @vue/cli-shared-utils:  4.5.13
    @vue/component-compiler-utils:  3.2.2 (3.2.2)
    @vue/composition-api: ^1.0.0-rc.13 => 1.0.0-rc.13
    @vue/preload-webpack-plugin:  1.1.2
    @vue/shared: ^3.1.4 => 3.1.4
    @vue/web-component-wrapper:  1.3.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.14 => 2.6.14
    vue-class-component: ^6.3.2 => 6.3.2 (7.2.6)
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.7 (16.3.0, 15.9.7)
    vue-property-decorator: ^8.0.0 => 8.5.1
    vue-router:  3.0.1
    vue-style-loader:  4.1.3 (4.1.3)
    vue-template-compiler: ^2.6.14 => 2.6.14 (2.6.14)
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.2.0 => 3.6.2
  npmGlobalPackages:
    @vue/cli: Not Found

**补充信息**
![捕获](https://user-images.githubusercontent.com/34822980/124361841-dfd3ba00-dc63-11eb-9efc-50ffdfaef97f.PNG)
修改 node_modules\@dcloudio\vue-cli-plugin-uni\packages\uni-cloud\dist\index.js 对 u 进行判空后就能够正常获取了
![image](https://user-images.githubusercontent.com/34822980/124361872-14477600-dc64-11eb-926a-517ce3ba74f1.png)

**Comment by Wangyaqi** [comment]
看下你的项目里面有没有@dcloudio/uni-i18n 这个包？

**Comment by MuNan777** [comment]
确实是少了这个包 @dcloudio/uni-i18n 安装上就可以，感谢提醒
