### ISSUE TITLE
app热更新问题

### ISSUE THREAD

**Issue by gouqie722** [dcloudio/uni-app#2746]
问题描述：WGT安装包中manifest.json文件的version版本不匹配
复现：线上app的manifest.json 版本为121， wgt的版本为122

**Comment by StrivingRabbit** [comment]
什么意思？WGT的版本不应该比线上App的高吗？

**Comment by StrivingRabbit** [comment]
由于长时间没有回复，此issue关闭，如果还有问题可以重开或提新的issue
