### ISSUE TITLE
支付宝小程序基础库2.7.2新增了onPageNotFound生命周期，通过uni-app编译到支付宝不生效

### ISSUE THREAD

**Issue by zhenfeicheng** [dcloudio/uni-app#2747]
**问题描述**
支付宝小程序基础库2.7.2新增了onPageNotFound生命周期，监听页面不存在，通过uni-app编译到支付宝不生效
https://opendocs.alipay.com/mini/framework/app-detail
https://opendocs.alipay.com/mini/00d5f5
**复现步骤**
1.在uni-app项目的App.vue中定义
 onPageNotFound({path, query, isEntryPage}) {
   //微信小程序生效，支付宝不生效
  },

**预期结果**
预期能够监听支付宝小程序页面不存在
**实际结果**
通过uni-app编译到支付宝不生效，该方法未调用

**系统信息:**
 - 发行平台: 支付宝小程序
 - 操作系统 :任何手机且支付宝基础库版本均在2.7.2及以上，符合触发条件
 - uni-app版本 
 "@dcloudio/uni-app-plus": "^2.0.0-alpha-27920200615002",
"@types/uni-app": "^1.4.3",

**Comment by Fasttian** [comment]
确认 bug

**Comment by zhenfeicheng** [comment]
> 你是下面的哪种情况？
> 
> * uni.navigateTo 已经判断了页面不存在，所以拦截跳转并触发了 fail 回调，因此不会触发onPageNotFound
> * 如果页面实际上已经打开了（比如通过分享卡片、小程序码）且发现页面不存在，才会触发onPageNotFound

以上两种情况都不是，我的情况是项目中新老页面更换了，从PageA变成了PageB，但一些外部配置入口目前仍然是配置的PageA，启动小程序的是就是个空白页面，此时应该可以触发onPageNotFound，onPageNotFound()这个方法放在App.vue文件中，正常应该启动的时候发现启动页面不存在，走这个onPageNotFound，实际未执行，微信小程序这种情况是触发了这个onPageNotFound方法

**Comment by Fasttian** [comment]
建议到ask.dcloud.net.cn发帖，提供一个可以复现的demo，发布完毕后，可邀请DCloud_UNI_TJX，我会尽快去处理。

**Comment by Fasttian** [comment]
[ConvertExcelToJSON-master 2.zip](https://github.com/dcloudio/uni-app/files/6820261/ConvertExcelToJSON-master.2.zip)

**Comment by zhenfeicheng** [comment]
> 提供一个可以复现的demo的zip，我复现一下（如github 不方便上传，可到ask.dcloud.net.cn发帖，发布完毕后，邀请DCloud_UNI_TJX，我会尽快去处理。）

方便提供个邮箱或者qq，我创建个demo发给你

**Comment by Otto-J** [comment]
如果现在还有问题，请发问题给我，可以贴 github repo link
