### ISSUE TITLE
使用websocket中监听后端发送来的消息 获取页面中data中数据产生的bug。

### ISSUE THREAD

**Issue by jetBn** [dcloudio/uni-app#2749]
**问题描述**
在全局建立一个websocket连接然后在子页面中监听后端的消息onMessage方法中会保留上一个页面中data数据，然后更改数据造成页面不刷新。

**复现步骤**
[复现问题的步骤]
1.  启动建立socket连接
2. 点击进入子 页面中监听消息
3. 返回上一级页面然后再进入页面就会出现data保留上一次页面的数据，而且更新data数据页面也不更新

**预期结果**

不会记录上次页面的数据， 设置data中数据页面能进行一个更新

**实际结果**

页面不更新

**系统信息:**
 - 发行平台:  微信小程序、5+ App
 - 操作系统 Android 8.0
 - HBuilderX版本HBuilderX 3.1.4

**Comment by StrivingRabbit** [comment]
返回后，再进入子页面，data怎么保留上一次页面的数据了？具体是什么表现？

不写websocket没这个问题？

**Comment by jetBn** [comment]
> 返回后，再进入子页面，data怎么保留上一次页面的数据了？具体是什么表现？
> 
> 不写websocket没这个问题？

是的  ， 就是在onMessage监听更新data 更新不了 然后退出这个页面再进入 发现保留了上次进入该页面的数据

**Comment by jetBn** [comment]
// 产生bug的相关描述：
                    // 当全局开启一个socket 在页面中监听会产生bug
                    // bug1 当在onshow生命周期添加onMessage事件时候每次进入都会添加一次，当进入多次就糊添加多个监听，多次进入后就收到服务端多次消息进行请求
                    // 解决方法：使用vuex 设置要设置一个tag当一次进入然后改为true，后次进入就不会添加onmessage监听（在此解决了 添加多个监听 但是有产生了新bug）
                    //bug2 在onmessage的监听中获取数据然后更改data中的数据页面不刷新，
                    // 解决方法：
                    // 1.在onmessage中设置一个变量为获取后的数据然后设置data页面也不刷新，尝试使用this。$forceUpdate()也不刷新， 然后data中设置一个tag 进入方法改变tag 更改数据又改变tag页面也不刷新。
                    // 2.尝试使用vuex全局变量此时页面是刷新了但是仍然存在问题（追加数据的时候页面不刷新）。当使用vuex全局状态 多次进入页面后 数组push的时候会始终保留在一个长度，（此也是个bug，尝试过给state中数据添加单个也是失败）（感觉是框架问题）
                    // 当时以为是使用mapState 在computed中缓存的原因 但是直接引用store然后使用也是存在如此问题
                    // 然后通过了watch监听了数据变化，发现根本没用变监听不到 ，怀疑是都是用了（保留）上次打开页面的数据。
                    //---------------------------------------------------------------------------------------
                    // 最后通过进入进入页面关闭socket然后再重新打开socket进行一个监听能获取到数据并且更新页面

**Comment by StrivingRabbit** [comment]
可否提供一个简单的示例？看着你的描述我不好定位问题

**Comment by jetBn** [comment]
> 可否提供一个简单的示例？看着你的描述我不好定位问题

你这有socket的链接吗 ？有的话我可以的提供下 。没有的话我得稍迟一些 我写一个然后提供

**Comment by StrivingRabbit** [comment]
> > 可否提供一个简单的示例？看着你的描述我不好定位问题
> 
> 你这有socket的链接吗 ？有的话我可以的提供下 。没有的话我得稍迟一些 我写一个然后提供

我就用hello-uniapp中的就可以

**Comment by jetBn** [comment]
> > > 可否提供一个简单的示例？看着你的描述我不好定位问题
> > 
> > 
> > 你这有socket的链接吗 ？有的话我可以的提供下 。没有的话我得稍迟一些 我写一个然后提供
> 
> 我就用hello-uniapp中的就可以

ok 我用hello-uniapp中的看看

**Comment by jetBn** [comment]
> > > 可否提供一个简单的示例？看着你的描述我不好定位问题
> > 
> > 
> > 你这有socket的链接吗 ？有的话我可以的提供下 。没有的话我得稍迟一些 我写一个然后提供
> 
> 我就用hello-uniapp中的就可以

用的hello-uniapp是没有问题的 ，因为在onUnload生命周期关闭了连接，我的意思应该就是保证全局，这个连接不关闭。

**Comment by StrivingRabbit** [comment]
> > > > 可否提供一个简单的示例？看着你的描述我不好定位问题
> > > 
> > > 
> > > 你这有socket的链接吗 ？有的话我可以的提供下 。没有的话我得稍迟一些 我写一个然后提供
> > 
> > 
> > 我就用hello-uniapp中的就可以
> 
> 用的hello-uniapp是没有问题的 ，因为在onUnload生命周期关闭了连接，我的意思应该就是保证全局，这个连接不关闭。在所有页面都保持有一个socket连接

什么平台？提供一个简单的示例

**Comment by jetBn** [comment]
发现了 是使用vuex设置socket产生的问题

**Comment by jetBn** [comment]
可能当时vuex实例没有取消 掉 然后使用全局的也有问题了

**Comment by jetBn** [comment]
> > > > > 可否提供一个简单的示例？看着你的描述我不好定位问题
> > > > 
> > > > 
> > > > 你这有socket的链接吗 ？有的话我可以的提供下 。没有的话我得稍迟一些 我写一个然后提供
> > > 
> > > 
> > > 我就用hello-uniapp中的就可以
> > 
> > 
> > 用的hello-uniapp是没有问题的 ，因为在onUnload生命周期关闭了连接，我的意思应该就是保证全局，这个连接不关闭。在所有页面都保持有一个socket连接
> 
> 什么平台？提供一个简单的示例

https://github.com/jetBn/uni-app_websocket

**Comment by StrivingRabbit** [comment]
1. 都什么平台有这个问题？
2. 我看了你提供的示例。你的意思是：
     -  进入应用后 index 连接 socket。再进入 main 页面，此时修改 data 中的数据，页面显示是可以更新的
     - 退出 main 页面，再次进入 main 页面。此时修改 data 中数据，页面不更新。data 保留上一次数据是什么意思？这个 data 是什么 data？

**Comment by jetBn** [comment]
各个平台都会

**Comment by jetBn** [comment]
你现在能监听到多个消息嘛？就是会添加多个onMessage事件 返回多个

**Comment by jetBn** [comment]
已经更新github仓库代码 你可以看下 我加入了 不会更新页面数据的demo

**Comment by StrivingRabbit** [comment]
> 已经更新github仓库代码 你可以看下 我加入了 不会更新页面数据的demo

你这样写当然不行了。你从页面返回，当前vue实例都被销毁了，再进入就是一个新的vue实例，怎么可能再次进入的时候更改还能体现在页面上

**Comment by jetBn** [comment]
> > 已经更新github仓库代码 你可以看下 我加入了 不会更新页面数据的demo
> 
> 你这样写当然不行了。你从页面返回，再进入就是一个新的vue实例，怎么可能再次进入的时候更改还能体现在页面上
那为什么第一次更改数据能更新 ？

**Comment by jetBn** [comment]
那为什么第一个更改数据能更新 ？

**Comment by jetBn** [comment]
> > 已经更新github仓库代码 你可以看下 我加入了 不会更新页面数据的demo
> 
> 你这样写当然不行了。你从页面返回，再进入就是一个新的vue实例，怎么可能再次进入的时候更改还能体现在页面上

不是返回的问题 ？你试试发送消息然后在socket onMessage看看能不能更新 ？ 这是同一个实例吧 ？

**Comment by jetBn** [comment]
你就算我这样写不行 ，那 这个onMessage产生多次监听 这个是怎么产生的？也是每次进入都产生监听一个vue实例化后的页面 ？然后这个页面还不会被销毁 ？ vue在网页中也存在这个问题吗？

**Comment by jetBn** [comment]
还是说 uni-app中的vue 每进入一个页面都产生一个vue的实例 然后vue 这个实例一直保留着 ？

**Comment by StrivingRabbit** [comment]
> 那就算我这样写不行 ，那 这个onMessage产生多次监听 这个是怎么产生的？也是每次进入都产生监听一个vue实例化后的页面 ？然后这个页面还不会被销毁 ？ vue在网页中也存在这个问题吗？

1. onMessage产生多次监听
> 每次使用`onMessage`，会往`callback`队列中添加一个方法，当`socket`接收到消息的时候，会将队列循环全部执行。
2. 第一次进入更改数据能更新 ？
> 这是因为你第一次`onMessage`中使用的`that`变量就是当前`vue`对象的。当你退出页面再进入的时候。触发`onMessage`回调，其中的`that`对象还是上一页面的实例。
3. 每次进入当然会创建一个新的实例，上次的实例会卸载，但是是否会保留在内存中就要看你对这个页面实例的引用关系了。

**Comment by jetBn** [comment]
为什么会往callback队列中添加 因为用的是一个socket实例， 这是因为socket设计的时候就这样 ？

**Comment by StrivingRabbit** [comment]
> 为什么会往callback队列中添加 因为用的是同一个socket实例， 这是因为socket设计的时候就这样 ？

设计如此。

> 你可以使用globalData创建一个function，在页面监听`onMessage`中调用。每次`onShow`里改变`globalData.function`即可实现你想要的效果

**Comment by jetBn** [comment]
为什么我这边再网页中测试实例化一个WebSocket 然后添加多个onmessage 不存在这个多次你说的进入队列的情况 ？
