### ISSUE TITLE
APP的webview错误页和断网页需要自定义

### ISSUE THREAD

**Issue by guo7749** [dcloudio/uni-app#275]
首先感谢dclould做出那么好的产品，我们从wap2app过来，webwiew流畅度不错，也支持h5＋，但是一断网，或者错误，那个体验就完全崩了，希望增加下自定义错误页。

**Comment by Wangyaqi** [comment]
manifest.json内已支持配置  [https://uniapp.dcloud.io/collocation/manifest](https://uniapp.dcloud.io/collocation/manifest)
```
"error": {
            "url": "页面加载错误时打开的页面地址，可以是网络地址，也可以是本地地址"
        },
```
