### ISSUE TITLE
uniapp图片 image图片地址渲染bug(我也不确定是否属于bug，看官方回复0.0)

### ISSUE THREAD

**Issue by Hi-CiYing** [dcloudio/uni-app#2751]
​
测试代码如下，点击按钮后对比一下img和image图片显示

测试环境是H5浏览器

![image](https://user-images.githubusercontent.com/47527212/125019601-e7eb8980-e0a9-11eb-9f7b-dc6ecfc49748.png)

 项目初始运行图
![2](https://user-images.githubusercontent.com/47527212/125019649-ffc30d80-e0a9-11eb-9834-6b96ac76d11b.png)

 点击按钮后可以明显看到打印出来的url路径是空，可是 image渲染的路径却没有变。

![image](https://user-images.githubusercontent.com/47527212/125019708-14070a80-e0aa-11eb-89ed-3c7e8c1c1291.png)

我目前的解决方法是:

最后我只能用v-if判断是否为空，为空的时候显示一个view，如果有需要给view加底色或者底图

v-if不等空的时候显示有图片的image标签

​

**Comment by StrivingRabbit** [comment]
使用的什么版本的HBuilder X？我这里测试没有问题
