### ISSUE TITLE
支付宝小程序中自定义组件使用map时，regionchange事件不触发

### ISSUE THREAD

**Issue by Deeyu** [dcloudio/uni-app#2753]
**问题描述**
支付宝小程序中自定义组件使用map时，regionchange事件不触发（启用小程序基础库 2.0 构建
），不启用2.0时正常触发

**复现步骤**
[复现问题的步骤]
![image](https://user-images.githubusercontent.com/33755522/125158915-a2f94d00-e1a6-11eb-825b-241b4d138a5d.png)
![image](https://user-images.githubusercontent.com/33755522/125158925-ae4c7880-e1a6-11eb-8874-bd96a7004fe1.png)
3. 查看

[或者可以直接贴源代码]

**预期结果**
regionchange事件能够正常派发

**实际结果**
不开启时正常
![image](https://user-images.githubusercontent.com/33755522/125159000-30d53800-e1a7-11eb-85a6-3c4bd7291fc8.png)
2.0开启时不触发
![image](https://user-images.githubusercontent.com/33755522/125158995-27e46680-e1a7-11eb-9b16-714d4a1eae87.png)

**系统信息:**
 - 发行平台: 支付宝小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 3.1.22.20210709]
 - uni-app版本 [3.1.22.20210709]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Otto-J** [comment]
感谢反馈，经过我测试最新的 vue2 最新依赖，可以正常展示 regionchange，可能已经修复过了这个问题。
具体代码可以参考
https://gitee.com/xiaoxfa/vue2-cli-uni-app-playground/tree/q%2Falipay-map/

如果仍有问题，请 reopen 或者新开 issue 艾特我。
