### ISSUE TITLE
自定义下拉刷新组件 + scroll-view 一起用，下拉刷新失效

### ISSUE THREAD

**Issue by 1103409364** [dcloudio/uni-app#2756]
**问题描述**
更新到最新版，[新闻模板](https://ext.dcloud.net.cn/plugin?id=315) 中自定义下拉刷新组件mix-pulldown-refresh和scroll-view 一起用，scroll-view 开启r滚动时，无法触发下拉刷新。

**系统信息:**
HBuilder X - 3.1.22.20210709

**补充信息**
3.1.18版是正常的。
可能是 scroll-view 开启滚动时，触摸事件冒泡被阻止了？

**Comment by StrivingRabbit** [comment]
明白，预计下版修复
