### ISSUE TITLE
打包 h5,  uni.onKeyboardHeightChange  无法触发

### ISSUE THREAD

**Issue by monstereat** [dcloudio/uni-app#2757]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
Hbuildx打包H5页面，APP打开，H5页面 textarea 输入文字，弹出键盘，uni.onKeyboardHeightChange 没有触发，拿不到键盘高度。

**系统信息:**
 - 发行平台:H5平台、
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [3.1.22]
 - 设备信息 [一加7pro，小米6]

**Comment by zhetengbiji** [comment]
H5不支持，文档有标注兼容性：https://uniapp.dcloud.io/api/key?id=onkeyboardheightchange

原因是浏览器未提供相关接口
