### ISSUE TITLE
网络请求几次之后，回调不调用

### ISSUE THREAD

**Issue by brucehelen** [dcloudio/uni-app#276]
**问题描述**
用的uni cli创建的uni-app，调试几次后，页面一直刷新。看网络标签请求都成功了，但是不回调success或者fail回调函数。重启IDE能解决。这个是微信开发者工具BUG还是uni的BUG？

**复现步骤**
[复现问题的步骤]
1.  启动项目，首页每次启动都会请求网络，每次大概4个请求同时发出
2. 修改页面，微信IDE自动刷新，重新请求接口
3. 重复5次左右，后面的网络请求都成功，但是不回调success或者fail回调，导致页面一直在刷新状态

**预期结果**
多次请求，能够正常回调

**实际结果**
多次请求，没有正常回调

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统： Android 9.0
 - uni-app版本： 最新版本

**补充信息**
可能是由于uni封装原因导致微信开发者工具出问题？

**Comment by zhaokgithub** [comment]
同问

**Comment by zhetengbiji** [comment]
> 同问

如果同样在微信小程序端出现问题，请将问题反馈至小程序社区。
