### ISSUE TITLE
【严重】关于错误触发image的load函数bug体验极差

### ISSUE THREAD

**Issue by wsynhaa** [dcloudio/uni-app#2761]
**问题描述**
当往列表中unshift数据时会触发image的load函数，导致触发load方法重新计算图片的大小，就会出现闪动以下，可以看到原因是图片由本来大小再变成通过load函数生成的大小。但是通过往列表中push数据就不会触发图片的load函数，希望官方修复这个bug，因为用户体验很不好。

**复现步骤**
1.先往列表中push一个图片，然后image设置load函数改变图片大小。
2.再往列表中unshift一个数据
3.图片又触发了load函数导致图片闪动

**预期结果**
push和unshift都不再触发load函数

**实际结果**
只有push不触发

**系统信息:**
 - 发行平台:5+ App
 - 操作系统 Android 10.0
 - HBuilderX版本 3.1.22
 - uni-app版本
 - 设备信息 小米8

**补充信息**

https://user-images.githubusercontent.com/43292174/125782181-04b1e2b6-a3a5-4234-be7b-8cc5c072f384.mp4

具体请查看视频详情

**Comment by wsynhaa** [comment]
通过视频可以看出只要从图片前面操作数据就会触发load函数导致闪动

**Comment by Wangyaqi** [comment]
你的消息应该是用一个v-for展示的吧，给带有v-for的元素设置key时不要直接使用index，比如你可以直接使用消息的id作为key，来保证你的image组件能被正常复用

**Comment by wsynhaa** [comment]
> 你的消息应该是用一个v-for展示的吧，给带有v-for的元素设置key时不要直接使用index，比如你可以直接使用消息的id作为key，来保证你的image组件能被正常复用

还真的好了，非常感谢，我这几天咋都没想到是这个问题

**Comment by wsynhaa** [comment]
已解决，很迅速，一如既往的支持uniapp
