### ISSUE TITLE
uniapp里的原生vidoe播放rtsp流地址安卓可以播放但是ios却播放不出来。注释：（地址都是一样的

### ISSUE THREAD

**Issue by qwertyuiop1222** [dcloudio/uni-app#2764]
播放的组件是用的uniapp原生video，但是安卓可以播放rtsp流的地址，但是ios却是有的可以播放rtsp，有的rtsp却播放不出，被video组件捕获到错误，但是同一播放地址在vlc插件可以播放，在打包成apk安卓包也可以播放出来，就单单在打包成ios却播放不出

**Comment by dcloudhdx** [comment]
报了什么错误？请提供一个测试播放地址

**Comment by ArrayDC** [comment]
video组件最近有优化，请更新到最新版本HBuilderX重新测试。
如果还有问题请到 https://ask.dcloud.net.cn/ 提交Bug反馈。
注意：请提供复现问题的视频地址，并详细说明复现问题的设备环境。
