### ISSUE TITLE
vue3 TypeError: Cannot read property 'globalProperties' of undefined

### ISSUE THREAD

**Issue by dw08** [dcloudio/uni-app#2765]
**问题描述**
无法使用vue3 globalProperties进行拓展
**复现步骤**
[复现问题的步骤]
`import {
    createApp
} from 'vue'
import App from './App.vue'
import utils from "@/utils/commonUtils";
const app = createApp(App).mount()

app.config.globalProperties.$utils = utils;`

**预期结果**
可以使用app.config.globalProperties进行拓展

**实际结果**
TypeError: Cannot read property 'globalProperties' of undefined

**系统信息:**
 - 发行平台: 微信小程序

**Comment by StrivingRabbit** [comment]
请在`mount`前使用。
