### ISSUE TITLE
windows版本的我不知道，mac版本做的跟屎一样，闪退、触发bug啥的。跟vscode比就是屎，屎都不如

### ISSUE THREAD

**Issue by Luckywannnnng** [dcloudio/uni-app#2766]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
收到，补充一下 macOS 版本，设备信息等

**Comment by zhetengbiji** [comment]
另外建议详细描述一下闪退的情况，以及具体的”触发bug啥的“。

**Comment by Luckywannnnng** [comment]
我mac版本的hbuildx有时候开发一段时间，部分代码块删除再想撤销回去会乱序代码（command+z，居然在最后文件结尾追加“tyle”之类字符串，我原本那个代码块好的代码也乱序了，还导致我刚刚打的中文字符乱码），也复原不了，完了有时候我编译到其他小程序平台同时运行到浏览器就卡死了。macOS操作系统：10.15.7 ；电脑型号： macbook pro（16 inch 2019）

**Comment by ChihYungHu** [comment]
提问的这个人嘴巴里面是不是含了屎? 有啥资格喷别人, 谁逼你用了? 什么垃圾玩意儿, 呸
