### ISSUE TITLE
关于自定义弹框问题（添加公共template）

### ISSUE THREAD

**Issue by ghost** [dcloudio/uni-app#2768]
在实际使用的过程中，我们希望像普通vue一样在App.vue中添加一些template，后续通过类似vuex来控制，比如这样可以实现一个自定义弹框：

https://github.com/agile-contrib/vue2/blob/master/src/App.vue

不过，在uniapp却没有发现可以添加公共template的地方，感觉这个还挺有用的，不知道是不是我没有找到写法。

**Comment by zhetengbiji** [comment]
目前还未支持，后续会考虑方案，期望是用在哪端？

**Comment by hai2007** [comment]
我们目前用uniapp主要是在混合开发、微信小程序和支付宝小程序。
