### ISSUE TITLE
引入@vue/composition-api的时候报错

### ISSUE THREAD

**Issue by Dizzy-zz** [dcloudio/uni-app#2769]
**问题描述**
import @vue/composition-api的时候报错
错误信息：This dependency was not found:

* vue in ./node_modules/@vue/composition-api/dist/vue-composition-api.mjs

To install it, you can run: npm install --save vue

vue已经install

**复现步骤**
直接 import @vue/composition-api

**预期结果**
不报错，能正常使用@vue/composition-api

**实际结果**
报错，This dependency was not found:

* vue in ./node_modules/@vue/composition-api/dist/vue-composition-api.mjs

To install it, you can run: npm install --save vue

**系统信息:**
 - 发行平台: 支付宝小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 
 - uni-app v3.1.22
uni-app cli v2.0.0-31920210709003
System:
    OS: macOS 11.4
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.3 - ~/.nvm/versions/node/v14.17.3/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.17.3/bin/yarn
    npm: 7.20.0 - ~/.nvm/versions/node/v14.17.3/bin/npm
  Browsers:
    Chrome: 91.0.4472.164
    Firefox: Not Found
    Safari: 14.1.1
  npmPackages:
    @dcloudio/types: * => 2.3.3 
    @dcloudio/uni-app-plus: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-automator: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/uni-cli-shared: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/uni-h5: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/uni-helper-json: * => 1.0.13 
    @dcloudio/uni-i18n: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/uni-migration: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/uni-mp-360: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/uni-mp-alipay: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/uni-mp-baidu: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/uni-mp-kuaishou: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/uni-mp-qq: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/uni-mp-toutiao: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/uni-mp-vue: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/uni-mp-weixin: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/uni-quickapp-native: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/uni-quickapp-webview: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/uni-stat: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/uni-template-compiler: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @hap-toolkit/dsl-vue:  0.6.13 
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.6 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.13 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.13 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-router:  4.5.13 
    @vue/cli-plugin-vuex:  4.5.13 
    @vue/cli-service: ~4.5.0 => 4.5.13 
    @vue/cli-shared-utils:  4.5.13 
    @vue/component-compiler-utils:  3.2.2 (3.2.2)
    @vue/composition-api: ^1.0.3 => 1.0.3 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/shared: ^3.0.0 => 3.1.5 
    @vue/web-component-wrapper:  1.3.0 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.14 => 2.6.14 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.6 (16.3.3, 15.9.6)
    vue-router:  3.0.1 
    vue-style-loader:  4.1.3 (4.1.3)
    vue-template-compiler: ^2.6.11 => 2.6.14 (2.6.14)
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.2.0 => 3.6.2
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Jonny-china** [comment]
@vue/composition-api 版本问题吧，你试试退回到 1.0.0

**Comment by Dizzy-zz** [comment]
> @vue/composition-api 版本问题吧，你试试退回到 1.0.0

回退1.0.0版本依然复现

**Comment by Jonny-china** [comment]
> > @vue/composition-api 版本问题吧，你试试退回到 1.0.0
> 
> 回退1.0.0版本依然复现

老哥确定回退成功了吗，1.0.0 没有 `vue-composition-api.mjs`，你运行 `yarn list @vue/composition-api` 看看版本
![image](https://user-images.githubusercontent.com/31563977/126608465-4efc8760-5122-4330-9d77-647bf8e4405d.png)

**Comment by Dizzy-zz** [comment]
> > > @vue/composition-api 版本问题吧，你试试退回到 1.0.0
> > 
> > 
> > 回退1.0.0版本依然复现
> 
> 老哥确定回退成功了吗，1.0.0 没有 `vue-composition-api.mjs`，你运行 `yarn list @vue/composition-api` 看看版本
> ![image](https://user-images.githubusercontent.com/31563977/126608465-4efc8760-5122-4330-9d77-647bf8e4405d.png)

重新回退了，1.0.0正常运行，谢谢。
