### ISSUE TITLE
滑动组件 swipe-action，不支持 v-for 渲染，这个有点头疼啊 

### ISSUE THREAD

**Issue by ThomasGuoItaly** [dcloudio/uni-app#277]

**Comment by xiaoyucoding** [comment]
HBuilderX alpha 1.8.5公测！uni-app App平台 升级为新版编译器，提升启动速度、提升组件性能、支持过滤器等更多vue语法。详见：[https://ask.dcloud.net.cn/article/35574](https://ask.dcloud.net.cn/article/35574)
请下载 alpha 版并且使用新的编译器，即 app-plus->usingComponents 为 true 的情况下，是否依旧存在此限制。

**Comment by host166** [comment]
需要绑定key值 好好看看mvvm的机制！
