### ISSUE TITLE
【SOS】Android原生插件创建的全局变量如何存储呢？

### ISSUE THREAD

**Issue by wenfengzhaox** [dcloudio/uni-app#2772]
**问题描述**
请问uin 调Android原生插件，原生插件里面创建的全局变量怎么存呀？比如我建立了串口通信连接，我uni页面切换后还需要继续使用这个通信连接的对象，请问怎么处理呢？现在卡住了，请解答，谢谢大家。

**Comment by zhetengbiji** [comment]
不同页面可以公用对象
