### ISSUE TITLE
字节小程序 - 组件 prop .sync 无法生效，

### ISSUE THREAD

**Issue by AnaniZhu** [dcloudio/uni-app#2774]
**问题描述**
字节小程序 - 组件传递 prop .sync ，无法生效
比如 `<A :visible.sync="visible" />`，组件 A 内部执行 `this.$emit('update:visible', false)`, `visible` 并不会被修改

**复现步骤**
https://ask.dcloud.net.cn/question/127397 社区有相同问题，但已经过去一天了，无人回复

**预期结果**
能够正常使用 `.sync` 语法

**实际结果**
.sync 无法同步修改 prop 值。经验证，无法监听到 `@update:xx` 的事件

**系统信息:**
 - 发行平台: 字节小程序
 - 操作系统 字节小程序开发者工具 3.1.1 以及真机（测试机是安卓）上皆无法访问
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号] 未使用
 - uni-app版本 **v3.1.22**
 - 设备信息 字节小程序开发者工具 3.1.1 以及真机（测试机是安卓）上皆无法访问

**补充信息**
[可选]
**uni-app@2.9.8 正常**

经排查 **uni-app@3.1.18** 正常，**uni-app@3.1.22** 出现问题。

从 **2.0.0-31920210609001** 升级到 **2.0.0-31920210707002** 就存在问题。

**Comment by AnaniZhu** [comment]
这个有人回复下么？

**Comment by StrivingRabbit** [comment]
1. 正常时和有问题时，字节开发者工具的版本和基础库版本是否一致？
2. 基础库版本是多少？
