### ISSUE TITLE
关于 Vue3 对 APP 端的支持开放时间排期

### ISSUE THREAD

**Issue by CNMathon** [dcloudio/uni-app#2775]
**新功能描述**
当前 Uniapp APP 端的开发对 Vue3 依旧并不支持，想了解下官方对此任务的优先级和具体上线排期相关的信息，谢谢。

**现状及问题**
依旧无法使用 Vue3 + Typescript 开发 APP

**尝试方案**
N/A

**补充信息**
N/A

**Comment by hbcui1984** [comment]
8月下旬会发布alpha版本。

**Comment by dcloudhdx** [comment]
已发布，迁移指南参考 [https://uniapp.dcloud.net.cn/migration-to-vue3](https://uniapp.dcloud.net.cn/migration-to-vue3)
