### ISSUE TITLE
H5 发布模式，当指定 publicPath 时，tabbar 地址错误，没有使用 CDN 地址

### ISSUE THREAD

**Issue by chuangbo** [dcloudio/uni-app#2776]
**问题描述**
设置了 H5 打包的 publicPath 参数以后，tabbar 的 icon 地址依然是本地路径，建议 H5 下编译时也使用 publicPath

**复现步骤**
[复现问题的步骤]
1.  启动 hbuilder
2. 设置 h5 publicPath 修改 `manifest.json`
    ```json
    {
        ...
        "h5" : {
            "devServer" : {
                "disableHostCheck" : true
            },
            "title" : "小程序",
            "publicPath" : "https://cdn.example.com/",
            "router" : {
                "mode" : "history"
            }
        }
    }
    ```

3. 打包
4. 运行，查看 tabbar icon 地址，依然是本地地址

![image](https://user-images.githubusercontent.com/179978/131810101-ed941182-323f-4d8c-8794-67babd163d95.png)

[或者可以直接贴源代码]

**预期结果**
运行以后 tabbar icon 地址也使用 publicPath

**实际结果**
查看 tabbar icon 地址，依然是本地地址

**系统信息:**
 - 发行平台: H5
 - 操作系统 Mac 11.4
 - HBuilderX版本 3.1.13.20210514
 - uni-app版本 hbuilder 版本
 - 设备信息 Mac

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

与问题 #1053 重复，但是那个被关闭了

**Comment by StrivingRabbit** [comment]
tabbar 现在是没有走 webpack 的编译，不过你可以试试配置网络地址试试。App 、H5、微信小程序应该都是支持的

**Comment by chuangbo** [comment]
有时间试试。如果用网络地址，本地开发就麻烦一些了。请问能不能指引一下大概需要改哪一块，我可以尝试一下吗？
