### ISSUE TITLE
微信小程序做成组件的position: sticky;会失效

### ISSUE THREAD

**Issue by ariesfans** [dcloudio/uni-app#2778]
在页面内  直接使用position: sticky;吸顶所有平台可以
做成组件  引入页面 微信小程序就会失效，移动端及H5都没问题

**Comment by StrivingRabbit** [comment]
什么系统的手机？系统版本是？可能是系统版本过低，不支持position: sticky

**Comment by ariesfans** [comment]
iphone 11 / 14.0.1

**Comment by StrivingRabbit** [comment]
可以去微信社区反馈一下
