### ISSUE TITLE
视频全屏 暂停时画面会自动铺满

### ISSUE THREAD

**Issue by 1135065316** [dcloudio/uni-app#2779]
**问题描述**
uniapp v3.1.22 视频全屏 暂停时画面会自动铺满

**复现步骤**
```
<template>
  <view>
    <video id="video" :src="videoSrc" autoplay></video>
  </view>
</template>

<script>
  export default {
    data() {
      return {
        videoCtx: null,
        videoSrc: 'https://cdn.lelepen.com/uploads/20210611/dcd6003ff8234a8d97591938485a347c.mp4',
      }
    },
    onLoad() {
      this.videoCtx = uni.createVideoContext(`video`, this)
      setTimeout(() => {
        this.videoCtx.requestFullScreen()
      }, 500)
    },
    methods: {
    },
  }
</script>
```
![image](https://user-images.githubusercontent.com/24956626/126925877-d4e35efe-2cac-4856-8818-cce8d59aa368.png)

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 Android 10
 - HBuilderX版本 3.1.22
 - 设备信息荣耀 X10

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
这些系统信息麻烦填写一下

系统信息:

发行平台: [如 微信小程序、H5平台、5+ App等]
操作系统 [如 iOS 12.1.2、Android 7.0]
HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
uni-app版本 [如使用Vue-cli创建/运行项目，则提供npm run info的运行结果]
设备信息 [如 iPhone8 Plus]

**Comment by 1135065316** [comment]
填写了

**Comment by zhetengbiji** [comment]
> 填写了

收到

**Comment by 1135065316** [comment]
还有 拖动进度条,只会触发@waiting, 不会触发@play, 这个应该一直都这样

**Comment by zmobs** [comment]
这个问题，7月26号的alpha版本会修复

**Comment by ArrayDC** [comment]
此问题已修复，请更新到HBuilderX3.2.3+版本。
