### ISSUE TITLE
使用typescript 构建的应用，如何关闭运行时类型检测？

### ISSUE THREAD

**Issue by yanlele** [dcloudio/uni-app#2781]
**问题描述**
使用 uni-app typescript 模板开发小程序。开发过程中每次 recompile 都要跑一边类型检测， 以为项目比价大， 跑类型检测非常的慢。请问有什么办法可以关闭这个 TS 的类型检测吗？

![image](https://user-images.githubusercontent.com/22188674/127291452-b2fad82d-5d08-4d19-9b50-6645bd0c95e6.png)

**Comment by StrivingRabbit** [comment]
用什么工具做的开发？
