### ISSUE TITLE
微信小程序 调试基础库 2.18.1 循环里面带有 空的slot 会报大量警告 循环次数过多可能造成调试工具假死

### ISSUE THREAD

**Issue by yuconora** [dcloudio/uni-app#2782]
**问题描述**
编译成微信小程序 当在文件中使用 [解构插槽 Prop](https://uniapp.dcloud.io/vue-components?id=%e8%a7%a3%e6%9e%84%e6%8f%92%e6%a7%bd-prop)  微信调试基础库版本号为 **2.18.1** 会报 **大量** 警告 ，页面复杂调试工具可能卡死
**复现步骤**
[复现问题的步骤]
1.hbuilderx 新建一个 uniapp 项目 
新建一个组件Test.vue
```vue
// Test.vue
<template>
	<view>
		<block v-for="(item, index) in list" :key="index">
			<slot :item="item"></slot>
		</block>
	</view>
</template>

<script>
export default {
	name: 'Test',
	data() {
		return {
			list: []
		};
	},
	mounted() {
		// length过大 调试工具会报大量警告 可能卡死
		const length = 10
		const list = Array(length).fill(0).map((_item, index) => index)
		this.list = list.slice()
	},
	methods: {}
};
</script>

<style></style>

```

修改 index.vue 代码 引入 Test 组件
```vue
// index.vue
<template>
	<view class="content">
		<test ref="test">
			<template #default="{item}">
				<view class="item" :id="item">{{item}}</view>
			</template>
		</test>
	</view>
</template>

<script>
import Test from '@/components/Test.vue';
export default {
	data() {
		return {
			title: 'Hello'
		};
	},
	components: {
		Test
	},
	methods: {}
};
</script>

<style>
.item {
	width: 100%;
	height: 160rpx;
	background-color: #4cd964;
	padding: 16px;
	box-sizing: border-box;
	margin-bottom: 10px;
}
</style>
```

2. hbuilderx 工具栏选择 -》运行 -》运行到小程序模拟器 -》微信开发工具
微信开发工具选择调试基础库版本 2.18.1
<img width="399" alt="截屏2021-07-28 15 43 03" src="https://user-images.githubusercontent.com/14029094/127283814-bca13ba3-3db7-4aab-b178-785758ec463f.png">
调试窗口 console 里面可以看到大量警告
<img width="696" alt="截屏2021-07-28 15 40 54" src="https://user-images.githubusercontent.com/14029094/127283845-4ba9d8e5-67fb-4972-bdec-a706e0536e28.png">

**预期结果**
可以去除多余的slot 消除警告

**实际结果**
由于警告过多 页面渲染慢 调试工具可能卡死

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本 3.1.22.20210709

**补充信息**
由于微信不支持在循环（wx:for）里面嵌套[同名（匿名）slot](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E7%BB%84%E4%BB%B6-wxml-%E7%9A%84-slot) 而这种情况能用抽象节点的形式来分发内容
<img width="706" alt="截屏2021-07-28 16 50 40" src="https://user-images.githubusercontent.com/14029094/127293566-4a8f9234-5487-40da-a688-740cb799712d.png">

uniapp在 [v2.0.0-28520200811001版本](https://github.com/dcloudio/uni-app/commit/23666102ca928cc401d97464c3600bb10c3d0e32#diff-1945c2d7bc07591deaab7d6dce0062d5505c91e31ac9a7cfbba1a57316a0f699) 之后 总会返回一个默认插槽 支持作用域插槽当作普通插槽使用 当升级到最新的微信调试基础库（目前 2.18.1） 就会导致这个问题的出现 

这个地方是否考虑做一下兼容性调整？ 由于目前项目中没有 **作用域插槽当作普通插槽使用** 这种情况 删掉了返回的默认插槽 项目调试正常
https://github.com/dcloudio/uni-app/blob/d33167a5c6aaf0089cecfcae7a35379d7049cbff/packages/uni-mp-weixin/lib/uni.compiler.js#L27-L51

**Comment by zhetengbiji** [comment]
收到，后续会根据此问题

临时参考：https://github.com/dcloudio/uni-app/issues/495#issuecomment-883848531

**Comment by zhetengbiji** [comment]
直接使用普通插槽在微信工具内测试问题复现。

已经准备了一个代码片段，将反馈到微信小程序社区。

**Comment by xiaofuliang** [comment]
请问解决没，头大！！，现在列表数据多卡的要死了。。。

**Comment by zhetengbiji** [comment]
> 请问解决没，头大！！，现在列表数据多卡的要死了。。。

可以先切换一下基础库版本到 2.17，切换后记得重启一下微信小程序开发工具。

**Comment by dopeisqu** [comment]
请问有办法解决吗？

**Comment by xiaofuliang** [comment]
@zhetengbiji 老是切换基础库版本也不是办法呀，你官方提的那个问题官方也不给处理，怎么办可好。 。。

**Comment by zhetengbiji** [comment]
> @zhetengbiji 老是切换基础库版本也不是办法呀，你官方提的那个问题官方也不给处理，怎么办可好。 。。

我又去反馈了一下，关注的人多了，应该有效果。

**Comment by xiaofuliang** [comment]
@zhetengbiji 反馈的链接发出来下，我也去关注下。。

**Comment by zhetengbiji** [comment]
> @zhetengbiji 反馈的链接发出来下，我也去关注下。。

https://developers.weixin.qq.com/community/develop/doc/000c84808644485f1a9c9fa1f56800

**Comment by zhetengbiji** [comment]
> 本地可以切换基础库调试，线上处理不了呀

这个警告打印应该只是卡死本地调试工具，线上也有影响吗？

**Comment by xiaofuliang** [comment]
> > 本地可以切换基础库调试，线上处理不了呀
> 
> 这个警告打印应该只是卡死本地调试工具，线上也有影响吗？

线上也会卡，我现在列表用的插槽，进到列表要过个10秒左右才会渲染，而且控制台会一直打出警告

**Comment by zhetengbiji** [comment]
> > > 本地可以切换基础库调试，线上处理不了呀
> > 
> > 
> > 这个警告打印应该只是卡死本地调试工具，线上也有影响吗？
> 
> 线上也会卡，我现在列表用的插槽，进到列表要过个10秒左右才会渲染，而且控制台会一直打出警告

线上怎么有控制台？

**Comment by dopeisqu** [comment]
> > > > 本地可以切换基础库调试，线上处理不了呀
> > > 
> > > 
> > > 这个警告打印应该只是卡死本地调试工具，线上也有影响吗？
> > 
> > 
> > 线上也会卡，我现在列表用的插槽，进到列表要过个10秒左右才会渲染，而且控制台会一直打出警告
> 
> 线上怎么有控制台？

数据多的时候会白屏一段时间

**Comment by xiaofuliang** [comment]
> > > > 本地可以切换基础库调试，线上处理不了呀
> > > 
> > > 
> > > 这个警告打印应该只是卡死本地调试工具，线上也有影响吗？
> > 
> > 
> > 线上也会卡，我现在列表用的插槽，进到列表要过个10秒左右才会渲染，而且控制台会一直打出警告
> 
> 线上怎么有控制台？

开发者开启了开发调试看的。。

**Comment by zhetengbiji** [comment]
> > > > > 本地可以切换基础库调试，线上处理不了呀
> > > > 
> > > > 
> > > > 这个警告打印应该只是卡死本地调试工具，线上也有影响吗？
> > > 
> > > 
> > > 线上也会卡，我现在列表用的插槽，进到列表要过个10秒左右才会渲染，而且控制台会一直打出警告
> > 
> > 
> > 线上怎么有控制台？
> 
> 数据多的时候会白屏一段时间

之前发布的版本，在微信客户端更新后受到了影响吗？

**Comment by zhetengbiji** [comment]
> > > > > 本地可以切换基础库调试，线上处理不了呀
> > > > 
> > > > 
> > > > 这个警告打印应该只是卡死本地调试工具，线上也有影响吗？
> > > 
> > > 
> > > 线上也会卡，我现在列表用的插槽，进到列表要过个10秒左右才会渲染，而且控制台会一直打出警告
> > 
> > 
> > 线上怎么有控制台？
> 
> 开发者开启了开发调试看的。。

之前发布的正式版本是否受到了影响？

**Comment by xiaofuliang** [comment]
> > > > > > 本地可以切换基础库调试，线上处理不了呀
> > > > > 
> > > > > 
> > > > > 这个警告打印应该只是卡死本地调试工具，线上也有影响吗？
> > > > 
> > > > 
> > > > 线上也会卡，我现在列表用的插槽，进到列表要过个10秒左右才会渲染，而且控制台会一直打出警告
> > > 
> > > 
> > > 线上怎么有控制台？
> > 
> > 
> > 开发者开启了开发调试看的。。
> 
> 之前发布的正式版本是否受到了影响？

我试过推送调试基础库2.173版本到手机上用，是没有啥影响的，也不会要等待，不会有控制台警告打出

**Comment by dnt1996** [comment]
如果影响到线上了，可以试着给方法赋值空函数
console.warn = noop

**Comment by Leeiio** [comment]
这个问题有进展了吗

**Comment by zhetengbiji** [comment]
> 这个问题有进展了吗

暂无，微信小程序官方已不再回复，后续会考虑绕过办法。

**Comment by zhetengbiji** [comment]
微信开发者工具已优化，此问题关闭

**Comment by monkeying-boy** [comment]
> 微信开发者工具已优化，此问题关闭

把微信开发者工具升级到最新后，虽然不会报错提醒，但是打包成微信小程序后页面实际还是不能正确获取到插槽参数，h5 是正常的。

问题：在循环中使用 slot 导致无法正确获取到插槽提供的参数。

项目版本 @dcloudio/uni-app : "2.0.2-3070320230222001"

**Comment by zhetengbiji** [comment]
> > 微信开发者工具已优化，此问题关闭
> 
> 把微信开发者工具升级到最新后，虽然不会报错提醒，但是打包成微信小程序后页面实际还是不能正确获取到插槽参数，h5 是正常的。
> 
> 问题：在循环中使用 slot 导致无法正确获取到插槽提供的参数。
> 
> 项目版本 @dcloudio/uni-app : "2.0.2-3070320230222001"

后续会优化，问题跟进参考：https://github.com/dcloudio/uni-app/issues/3503
