### ISSUE TITLE
希望可以增加一个对jsx的支持

### ISSUE THREAD

**Issue by Lisheri** [dcloudio/uni-app#2785]
**新功能描述**
希望新增对vue2.x版本的jsx支持

**现状及问题**
之前的H5项目是一个2.x的项目, 里面有大量的jsx存在, 迁移起来过于麻烦

**尝试方案**
无

**补充信息**
希望可以像vue一样通过babel的配置支持jsx

**Comment by Otto-J** [comment]
[#4683 ](https://github.com/dcloudio/uni-app/issues/4683#issuecomment-1888656524)
