### ISSUE TITLE
textarea 设置了 :show-confirm-bar="false"，首次进入小程序并且首次弹出键盘时，键盘与输入框会有空行

### ISSUE THREAD

**Issue by xiejibiao** [dcloudio/uni-app#2786]
**问题描述**
textarea 设置了 :show-confirm-bar="false"，首次进入小程序并且首次弹出键盘时，键盘与输入框会有空行（就是那个完成bar 按钮消失了，可是高度还在）

**复现步骤**

`` 

<textarea class="write-input"
		v-model="comment_content" 
		:placeholder="placeholder"
		:auto-height="true"
		:adjust-position="true"
		:show-confirm-bar="false"
		:fixed="true"
		:cursor-spacing="15">
</textarea>

 ``

**预期结果**
键盘弹起时， :show-confirm-bar="false" 能正确生效，并且没有空行

**实际结果**
![F02C3D08DCD14E2571FC0C733BEE28DF](https://user-images.githubusercontent.com/30366768/127472656-0a082ba4-3df8-4033-ada0-6f54a962bbc1.jpg)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: Android、IOS
 - HBuilderX版本 3.1.22.20210709
 - 设备信息 Android、IOS

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
经测试没有发现此问题，可以提供一个简单可复现的示例吗？

**Comment by gujintao1900** [comment]
ios nvue 下会有相同问题，这个不是稳定的，实机测试快速反复拉起键盘的时候，概率性出现。mac上用模拟器跑也会有这个问题，uni-app 3.2.3 正式版，ios 14.5 模拟器
