### ISSUE TITLE
slot的数据会跑到根节点外

### ISSUE THREAD

**Issue by hottredpen** [dcloudio/uni-app#2788]
**问题描述**
slot的数据会跑到根节点外

**复现步骤**
```
<template>
	<view class="wanl-waterfall">
		<view id="wanl-left-cloumn" class="wanl-cloumn">
			<slot name="left" :leftList="leftList"></slot>
		</view>
		<view id="wanl-right-cloumn" class="wanl-cloumn">
			<slot name="right" :rightList="rightList"></slot>
		</view>
	</view>
</template>
```

瀑布流 预留了 left 和right的slot

[或者可以直接贴源代码]

**预期结果**
左右两边都在shadow-root内

**实际结果**
![image](https://user-images.githubusercontent.com/8263367/127615621-868926a6-29bb-4bb4-9f4f-689ed0f639c5.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统  mac 10.14.6
 - HBuilderX版本 ：3.1.22.20210709
 - uni-app版本 最新
 - 设备信息 mac

**补充信息**

**Comment by zhetengbiji** [comment]
把使用组件的代码也补充一下

**Comment by hottredpen** [comment]
[test01.zip](https://github.com/dcloudio/uni-app/files/6980294/test01.zip)
简化代码时发现了一些细节。wanl-product-ok.vue 这个文件下的布局是可以的

**Comment by zhetengbiji** [comment]
先配置 [scopedSlotsCompiler: legacy](https://uniapp.dcloud.io/collocation/manifest?id=mp-weixin) 试试

**Comment by 838239178** [comment]
我也遇到了这个bug 版本是 3.0.0-alpha-3030820220114004

下图的 swiper-item是通过slot添加的 但是在shadow-root之外

![image](https://user-images.githubusercontent.com/55338151/152482150-0c941f3c-4cb8-43bc-bcdd-2a368e3826b1.png)

**Comment by fxy060608** [comment]
> 我也遇到了这个bug 版本是 3.0.0-alpha-3030820220114004
> 
> 下图的 swiper-item是通过slot添加的 但是在shadow-root之外
> 
> ![image](https://user-images.githubusercontent.com/55338151/152482150-0c941f3c-4cb8-43bc-bcdd-2a368e3826b1.png)
> 
> > 先配置 [scopedSlotsCompiler: legacy](https://uniapp.dcloud.io/collocation/manifest?id=mp-weixin) 试试
> 
> 无效

小程序组件 swiper 不支持使用 slot 来添加 swiper-item,可以到微信社区查找反馈相关问题
