### ISSUE TITLE
vue3+vuex4+ts开发的支付宝小程序运行报Cannot read property '__VUE_DEVTOOLS_GLOBAL_HOOK__' of undefined

### ISSUE THREAD

**Issue by MonthPearl** [dcloudio/uni-app#2789]
**问题描述**
vue3+vuex4+ts开发的支付宝小程序，在main.ts上用app.use(store)，报错Cannot read property '__VUE_DEVTOOLS_GLOBAL_HOOK__' of undefined，运行在微信小程序上不报错
**复现步骤**

在main.ts文件鞋app.use(store)就会报错，代码如下：

//main.ts
import { createApp } from 'vue'
import App from './App.vue'
import { store, key } from '@/store';

const app = createApp(App);
app.use(store,key) //加上这一行支付宝端小程序就报错
app.mount('#app')

**预期结果**
不报错

**实际结果**
![image](https://user-images.githubusercontent.com/38935884/127734944-07fd3950-0bc9-41c5-bc9b-64ecc6683391.png)

**系统信息:**
 - 发行平台: [支付宝小程序]

**Comment by fxy060608** [comment]
如果使用的cli的话，可以在vue.config.js中，调整 webpack 配置，添加 definePlugin 插件，增加 __VUE_PROD_DEVTOOLS__: JSON.stringify(false)

**Comment by MonthPearl** [comment]
> VUE_PROD_DEVTOOLS
在vue.config.js 添加了definePlugin，支付宝端小程序还是报 TypeError: Cannot read property '__VUE_DEVTOOLS_GLOBAL_HOOK__' of undefined
下面是我添加配置的代码：
//vue.config.js
const webpack = require('webpack');

module.exports = {
	configureWebpack:{
		plugins: [
			new webpack.DefinePlugin({
				VUE_PROD_DEVTOOLS: JSON.stringify(false)
			})
		],
	}
}

报错截图如下：
![image](https://user-images.githubusercontent.com/38935884/127769455-c4c0a2b5-4e24-4d6e-abc6-be7c4d53045e.png)

**Comment by StrivingRabbit** [comment]
配置键值为：__VUE_PROD_DEVTOOLS__  试试

**Comment by StrivingRabbit** [comment]
键值为：`__VUE_PROD_DEVTOOLS__`  ，上面回答被MD解析了

**Comment by MonthPearl** [comment]
试了还是报这个错误af-appx.worker.min.js:26 TypeError: Cannot read property '`__VUE_DEVTOOLS_GLOBAL_HOOK__`' of undefined

//vue.config.js
const webpack = require('webpack');
module.exports = {
	configureWebpack:{
		plugins: [
			new webpack.DefinePlugin({
				`__VUE_PROD_DEVTOOLS__`: JSON.stringify(false)
			})
		],
	}
}

![image](https://user-images.githubusercontent.com/38935884/127830069-b47f6666-6c12-4867-ba89-a0afe3a8cc9e.png)

**Comment by StrivingRabbit** [comment]
进入 `@dcloudio/vuex/dist/vuex.esm-browser.js` 和 `@dcloudio/vuex/dist/vuex.esm-bundler.js`。搜索`useDevtools`，你会看到一下代码：
```js
var useDevtools = this._devtools !== undefined
    ? this._devtools
    : (process.env.NODE_ENV !== 'production') || __VUE_PROD_DEVTOOLS__

  if (useDevtools) {
    addDevtools(app, this)
  }
```
将这部分全部注释掉即可

**Comment by fxy060608** [comment]
升级至HBuilderX Alpha3.3.0
