### ISSUE TITLE
默认的cli默认能加入ESLint吗？

### ISSUE THREAD

**Issue by zhuzhengjing** [dcloudio/uni-app#279]
**新功能描述**
希望在默认cli创建的工程中加入ESLint

**现状及问题**
没有ESLint错误不能及时发现，另外不利于统一编码格式

**补充信息**
ESLint对团队协作有帮助，希望能在模板中添加

**Comment by Duo-Huang** [comment]
同求，我试着把vue-cli3的lint配置进来，但是只能通过调用vue-cli-service的lint来执行，我发现uni-serve启动后并不能执行lint

**Comment by wangwen1220** [comment]
同求

**Comment by lanshengzhong** [comment]
同求

**Comment by fxy060608** [comment]
> 同求，我试着把vue-cli3的lint配置进来，但是只能通过调用vue-cli-service的lint来执行，我发现uni-serve/uni-build --watch启动后并不能执行lint

npm update 更新后，支持 watch 的时候，输出 eslint 信息

**Comment by fxy060608** [comment]
> 同求

目前可以手动添加插件实现：
`vue add @vue/eslint`
稍后考虑创建工程时，由开发者选择是否启用

**Comment by niphor** [comment]
@fxy060608  `vue add @vue/eslint` 后
```
"@vue/cli-plugin-eslint": "~4.3.0",
```
IDEA 一直会报：
```
Problem with ESLint reformatting:
xxx.js: Cannot start language service process (show balloon)
```
怎么改eslint的配置都报这个问题
