### ISSUE TITLE
uni-app项目不支持微信小程序的插件功能页functional-pages

### ISSUE THREAD

**Issue by breathcold** [dcloudio/uni-app#2790]
**问题描述**
微信小程序带有的插件功能页functional-pages功能，如果直接在src目录中放入functional-pages/request-payment.js 文件，由于项目是不会直接引用这个，所以打包发布的话没办法打包到对应的mp-weixin根目录中去

**相关资料**
https://developers.weixin.qq.com/miniprogram/dev/framework/plugin/functional-pages/request-payment.html
![8(EY)GA}U6{9)@7N~5YFG Q](https://user-images.githubusercontent.com/24854685/127743195-b09e1c40-231a-45d3-af33-c52af49a4011.png)

[或者可以直接贴源代码]

**预期结果**
functional-pages/request-payment.js  这个文件能够原封不动打包到mp-weixin的根目录

**实际结果**
mp-weixin的根目录目录中没有

**Comment by StrivingRabbit** [comment]
可以在vue.config.js中配置`copy-webpack-plugin`插件用于拷贝此文件夹。安装时记得指定`v5.0.0`版本，高版本写法不兼容。

```
const path = require('path')
const CopyWebpackPlugin = require('copy-webpack-plugin') //最新版本copy-webpack-plugin插件暂不兼容，推荐v5.0.0

module.exports = {
  configureWebpack: {
		  plugins: [
			  new CopyWebpackPlugin([{
				  from: path.join(__dirname, 'functional-pages'),
				  to: path.join(__dirname, 'unpackage/dist', process.env.NODE_ENV ===
					  'production' ?
					  'build' :
					  'dev', process.env.UNI_PLATFORM, 'functional-pages')
			  }])
		  ]
	  }
}
```
