### ISSUE TITLE
vue-cli-plugin-uni 跟 webpack@5不兼容

### ISSUE THREAD

**Issue by qiqihaobenben** [dcloudio/uni-app#2793]
**问题描述**

通过 vue-cli 创建 uni-app 项目，使用 default 模板，完成项目初始化后，执行 npm run serve 此时无报错，安装 sass ，报了vue cli 的错，通过 sass-loader 降级解决，之后再执行 npm run serve，报错 Cannot find module 'html-webpack-plugin'

**复现步骤**
1.  npm install -D sass-loader@^10 sass 安装了 sass 和 loader
2. npm run serve
3. 更改 App.vue 的 style 标签 lang="scss"，然后开始写样式，就报错了。

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
 ERROR  Error: Cannot find module 'html-webpack-plugin'
 Require stack:
- /Users/cfangxu/project/demo/uni-demo/node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-html-append-plugin/index.js
- /Users/cfangxu/project/demo/uni-demo/node_modules/@dcloudio/vue-cli-plugin-uni/lib/h5/index.js
- /Users/cfangxu/project/demo/uni-demo/node_modules/@dcloudio/vue-cli-plugin-uni/index.js
- /Users/cfangxu/project/demo/uni-demo/node_modules/@vue/cli-service/lib/Service.js
- /Users/cfangxu/project/demo/uni-demo/node_modules/@vue/cli-service/bin/vue-cli-service.js

**系统信息:**
 - uni-app版本 v3.1.22
 - uni-app cli v2.0.0-31920210709003
 - "@dcloudio/vue-cli-plugin-uni": "^2.0.0-31920210709003",

**补充信息**
vue-cli-plugin-uni 跟 webpack@5不兼容，webpack5已经没有 html-webpack-plugin 模块了。

**Comment by xhwgood** [comment]
请教下，你这个问题怎么解决的？
