### ISSUE TITLE
map 地图组件，微信小程序闪退

### ISSUE THREAD

**Issue by monstereat** [dcloudio/uni-app#2794]
**问题描述**
map 地图组件，微信小程序闪退。

**复现步骤**
打开页面，小程序闪退。

[或者可以直接贴源代码]
```javascript
<template>
	<view class="container">
		<map class="container" :latitude="lat" :longitude="lng" ></map>
	</view>
</template>

<script>
	export default({
		data(){
			return{
				lat: 39.909026,
				lng: 116.396918,
			}
		},
	})
</script>

<style lang="scss" scoped>
	.container{
		width: 750upx;
		height: 50vh;
	}
</style>
```

**预期结果**
显示定位

**实际结果**
闪退，退出小程序。
调试无报错。

**系统信息:**
 - 发行平台:  微信小程序
 - 操作系统: Android 10
 - HBuilderX版本：3.1.22
 - 设备信息：华为荣耀 HONOR 20S    微信：8.0.9
![image](https://user-images.githubusercontent.com/13077554/127826959-04a8fefb-27d4-4345-af4b-b0a32036191d.png)

**Comment by StrivingRabbit** [comment]
如果是小程序的写法，是否有此问题？

**Comment by monstereat** [comment]
> 如果是小程序的写法，是否有此问题？

刚试了下，小程序的写法也有这个问题，等微信修复吧。
