### ISSUE TITLE
vue3.0开发支付宝小程序在组件使用emit会报错TypeError: Cannot read property 'vnode' of undefined

### ISSUE THREAD

**Issue by MonthPearl** [dcloudio/uni-app#2799]
**问题描述**
vue3.0+ts开发支付宝小程序，在自定义组件中使用emit会报错TypeError: Cannot read property 'vnode' of undefined，在微信小程序端没有问题

**复现步骤**
在组件中只用emit
例如：emit('closeDialog')
在支付宝小程序开发工具中运行报错
![image](https://user-images.githubusercontent.com/38935884/128279529-a3ac1feb-f39b-4aa6-a12c-f78bed724d52.png)

**预期结果**
运行不报错

**系统信息:**
 - 发行平台:支付宝小程序

**Comment by StrivingRabbit** [comment]
具体代码贴一下，看看你是怎么使用的

**Comment by MonthPearl** [comment]
> 具体代码贴一下，看看你是怎么使用的
已定位到问题，是因为在支付宝端this下面没有$元素，已通过下面修改解决了这个问题
![image](https://user-images.githubusercontent.com/38935884/130175634-d6b11185-ded6-4879-9fc3-fa9a48df65d3.png)

**Comment by fxy060608** [comment]
未重现该问题
