### ISSUE TITLE
bug: video 在 app 端有画面无声音

### ISSUE THREAD

**Issue by helsonxiao** [dcloudio/uni-app#280]
**问题描述**
RTMP 直播拉流有画面无声音

**复现步骤**
[复现问题的步骤]
1.  启动 APP
2. 开启直播视频
```
<template>  
    <view>  
        <view class="uni-padding-wrap uni-common-mt">  
            <video id="myVideo" src="rtmp://58.200.131.2:1935/livetv/hunantv"  
                    @error="videoErrorCallback" :danmu-list="danmuList" enable-danmu danmu-btn controls></video>  
        </view>  
    </view>  
</template> 
```

**预期结果**
有画面有声音

**实际结果**
有画面无声音

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等] 5+ App
 - 操作系统: iOS 12.2、Android 8.1.0
 - HBuilderX版本: 1.8.2.20190401
 - uni-app版本: HBuilderX 自带版本
 - 设备信息: 坚果 R1

**Comment by helsonxiao** [comment]
社区已有人回复，等待处理，这个 issue 暂时关闭。
https://ask.dcloud.net.cn/question/68284?notification_id-547961__rf-false__item_id-83011#!answer_83011

**Comment by hangaoke1** [comment]
官方没有后续了吗？

**Comment by ArrayDC** [comment]
新版本有优化，请更新到最新版本HBuilderX。
