### ISSUE TITLE
input组件暴露value属性，但修改后视图不能实时更新（valueSync不能实时更新）

### ISSUE THREAD

**Issue by Ronchan0805** [dcloudio/uni-app#2801]
**问题描述**
Q1、修改input组件的value值但视图不更新,需要再次输入才更新（value值更新了但input组件源码内绑定视图的valueSync仍未更新）
Q2、疑问：uniapp编译到微信小程序后，input组件采用微信原生的input还是uniapp封装的input？

**复现步骤**
1. 子组件内部input绑定:value="defaultValue”，通过input事件@input="handleInput"，其中子组件input事件 handleInput(e) 代码如下：
`this.$emit('input',e.detail.value); setTimeout(() => {this.defaultValue = this.value}, 0);`
2. 父组件使用如下：
`<my-uni-input  v-model="persons"  @input="persons=persons.replace(/[^\d]/g,'')"></my-uni-input>`

**预期结果**
@input中修改的绑定值能实时反应在视图上（能够做到多端兼容）

**实际结果**
![1628131249(1)](https://user-images.githubusercontent.com/74052977/128282414-53fc43f7-25f2-44ec-bc19-7709e438a4f7.jpg)

**系统信息:**
 - 发行平台: 微信小程序、H5平台
 - 操作系统 Android 10.0
 - HBuilderX版本 HBuilderX 3.1.6
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息

**补充信息**
修改复现步骤1中子组件input事件代码如下可以完美解决此问题：
`this.$emit('input',e.detail.value); setTimeout(() => {this.$refs.input.valueSync = this.value}, 0);`
但是，对微信小程序端这段代码是无效的。this.$refs.input编译到微信小程序端是undefined,进而valueSync更获取不到了。

（参考：这个问题与elementui之前的el-input有一个很相似的issue：https://github.com/ElemeFE/element/issues/12850）

**Comment by StrivingRabbit** [comment]
没有更新的原因是这样的：
在你的正则中将不是数字的替换为空值
1. 那么在你输入 666 后，value 和 valueSync 都是 666
2. 在你输入 666a 时，valueSync 为 666a ，但 input 内部不会将两个值同步
3. 此时你将 defaultValue 也就是 input 的 value 修改为处理过后的值。那么修改前和修改后的值为同一个，input 内部无法观测到变更，自然也就不会去修改 valueSync 了

**Comment by Ronchan0805** [comment]
谢谢，但是我又试了一下好像如果一开始输入的就是错误的值那么对defaultValue再次赋值后defaultValue不会改变,这里我又改了下代码
`				this.defaultValue= "";   // 先改为一个不同的值，再赋值回来
				this.$nextTick(() => {
					if (this.value == "" && this.defaultValue == "") {
						this.defaultValue = " ";
						setTimeout(() => {
							this.defaultValue = this.value;
						})
					} else {
						this.defaultValue = this.value
					}
				})`
代码有点臃肿，或许这种正则替换本身就有点不太合适
