### ISSUE TITLE
vue-cli 方式 模板运行提示 Error: Cannot find module 'webpack/lib/RuleSet'

### ISSUE THREAD

**Issue by FlyDancing** [dcloudio/uni-app#2804]
**问题描述**
使用官网提供模板创建模板时，安装完所需依赖，运行npm run build 异常
 ERROR  Error: Cannot find module 'webpack/lib/RuleSet'
        Require stack:
        - D:\Project\Uniapp\vs\my\node_modules\@dcloudio\vue-cli-plugin-uni\lib\configure-webpack.js
        - D:\Project\Uniapp\vs\my\node_modules\@dcloudio\vue-cli-plugin-uni\index.js
        - D:\Project\Uniapp\vs\my\node_modules\@vue\cli-service\lib\Service.js
        - D:\Project\Uniapp\vs\my\node_modules\@vue\cli-service\bin\vue-cli-service.js

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 PC
 - VSCode Lastest
 - uni-app v3.1.22
uni-app cli v2.0.0-31920210709003

Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
  Binaries:
    Node: 14.17.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.19041.423.0
  npmPackages:
    @dcloudio/types: * => 2.4.4 
    @dcloudio/uni-app-plus: ^2.0.0-31920210709003 => 2.0.0-31920210709003 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-automator: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-cli-shared: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-h5: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-helper-json: * => 1.0.13
    @dcloudio/uni-i18n: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-migration: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-360: ^2.0.0-31920210709003 => 2.0.0-alpha-31920210506002
    @dcloudio/uni-mp-alipay: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-baidu: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-kuaishou: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-qq: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-toutiao: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-vue: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-weixin: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-quickapp-native: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-quickapp-webview: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-stat: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-template-compiler: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @hap-toolkit/dsl-vue:  0.6.13
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.0.6
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  5.0.0-beta.2
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  5.0.0-beta.2
    @vue/cli-plugin-babel: ~5.0.0-beta.2 => 5.0.0-beta.2
    @vue/cli-plugin-router:  5.0.0-beta.2
    @vue/cli-plugin-vuex:  5.0.0-beta.2
    @vue/cli-service: ~5.0.0-beta.2 => 5.0.0-beta.2
    @vue/cli-shared-utils:  5.0.0-beta.2
    @vue/component-compiler-utils:  3.2.2 (3.2.2)
    @vue/shared: ^3.0.0 => 3.1.5
    @vue/web-component-wrapper:  1.3.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.11 => 2.6.14
    vue-hot-reload-api:  2.3.4
    vue-loader:  16.4.0 (15.9.8, 15.9.8, 16.4.0)
    vue-router:  3.0.1
    vue-style-loader:  4.1.3 (4.1.3)
    vue-template-compiler: ^2.6.11 => 2.6.14 (2.6.14)
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.2.0 => 3.6.2
  npmGlobalPackages:
    @vue/cli: Not Found
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
升级或者node_module删除重装试试

**Comment by fendo8888** [comment]
这问题解决了没。。我这也遇到了Cannot find module 'webpack/lib/RuleSet'错误
