### ISSUE TITLE
请增加APP跳转微信客服的功能 WXOpenCustomerServiceChat 

### ISSUE THREAD

**Issue by hyperq** [dcloudio/uni-app#2807]
**新功能描述**
请增加APP跳转微信客服的功能

**现状及问题**
uniapp编译成小程序可以使用小程序的客服功能,但是app的话不能使用这一功能,如果需要多端同步,那么聊天功能就需要自行开发,现在微信开放平台提供打开微信客服的功能,希望uniapp团队可以增加这一功能

**尝试方案**
无

**补充信息**
参考文档
https://developers.weixin.qq.com/doc/oplatform/Mobile_App/APP_launch_wechat_customer_service.html

**Comment by zhetengbiji** [comment]
https://www.html5plus.org/doc/zh_cn/share.html#plus.share.ShareService.openCustomerServiceChat
