### ISSUE TITLE
Uni-app打包的app，vuex挂掉

### ISSUE THREAD

**Issue by gxlself** [dcloudio/uni-app#281]
我能说我下的依赖，vuex全局管理，在h5可用，app直接挂掉吗？这应该是大问题吧。。。

**Comment by host166** [comment]
app解析成了什么结构？

**Comment by zengyuanqiu** [comment]
import store from './store'

H5：  new Vue({ store })  像这样是可用的，app中要像下面这样

Vue.prototype.$store = store

**Comment by 97Strong** [comment]
mounted() {
console.log(this.$store.state.vuexData)//有数据
},
html中
<span>{{$store.state.vuexData}}</span>//会是undefined
请问何解？

**Comment by host166** [comment]
你需要关注一下 $store 的注册方式



在 2019-11-29 12:11:20，"午后草" <notifications@github.com> 写道：

mounted() {
console.log(this.$store.state.vuexData)//有数据
},
html中
{{$store.state.vuexData}}//会是undefined
请问何解？
