### ISSUE TITLE
uniapp 使用uni-ui 转换生成的文件不一致

### ISSUE THREAD

**Issue by bfrontend** [dcloudio/uni-app#2810]
**问题描述**
## dist 目录下生成的node_modules目录结构如下：
![image](https://user-images.githubusercontent.com/40289489/128619575-83229b68-fb46-4d37-bede-28abd3a966c1.png)
## dist/build/mp-weixin 及 dist/dev/mp-weixin 下的node_modules 目录结构如下:
![image](https://user-images.githubusercontent.com/40289489/128619616-61d7c3e1-3751-4d9d-80b1-8182da0b4ea0.png)
## 导致 在微信开发者工具中提示 组件找不到
![image](https://user-images.githubusercontent.com/40289489/128619637-4f0a7d1b-394d-4900-bb32-8c4dcb9e748b.png)

**复现步骤**
[复现问题的步骤]
uni cli 初始化项目
调整了 UNI_INPUT_DIR 路径

**预期结果**
功能正常

**实际结果**
微信开发者工具报错

**系统信息:**
![image](https://user-images.githubusercontent.com/40289489/128619673-38171cc3-9594-4136-af66-696666e248ce.png)

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
怎么调整了 UNI_INPUT_DIR 路径？
