### ISSUE TITLE
使用 ts 开发的组件如何编译为 js 环境也能使用的组件。

### ISSUE THREAD

**Issue by TuiMao233** [dcloudio/uni-app#2812]
**问题描述**
看了下貌似不支持使用 rollup 或者 webpack 打包后的 js 组件，
最近要做一款组件库，但有点不太想使用 javascript 写。

**Comment by zhetengbiji** [comment]
试试单文件拆开，单独预编译 ts 部分

**Comment by TuiMao233** [comment]
这会使编译变得有点麻烦，例如将所有组件的 index.ts 编译，在将组件中的 lang="ts" 抹除，将 src="index.ts" 更换为 src="index.js" 在转移到 dist 目录。

还有更好一些的方式吗？

**Comment by TuiMao233** [comment]
好吧，我做到了 https://github.com/TuiMao233/uni-tsc
