### ISSUE TITLE
Vue3 Vite 什么时候支持小程序和App。

### ISSUE THREAD

**Issue by TuiMao233** [dcloudio/uni-app#2814]
**问题描述**
今年能搞定吗？h5项目和小程序项目还要分开写，多端的优势都丢掉了，
隔壁 Taro 已经支持好久了，setup 语法糖也支持了，uniapp 等了好几个月信息都没有反应，
现在情况是怎么样了

**Comment by zhetengbiji** [comment]
使用最新的 alpha 版，无需分开写。

**Comment by zhetengbiji** [comment]
APP 也很快了，预计下下一个 alpha 版。

**Comment by zhetengbiji** [comment]
APP 也很快了，预计下下一个 alpha 版。

**Comment by zhetengbiji** [comment]
App 发布后，接下来就安排小程序端的 Vite 改版。

**Comment by windhc** [comment]
加油

**Comment by hbcui1984** [comment]
HBuilderX 3.2.5.20210827-alpha 版本已支持App平台的vite编译。

**Comment by yenkos** [comment]
@hbcui1984 @zhetengbiji 你好，vue3 + ts，vite环境编译h5正常，但是编译app异常，hbuilderx升级alpha0901也不行。请问app的编译是不是不支持ts，要怎么做才能运行起来app呢。

**Comment by fxy060608** [comment]
> 小程序的 Vite 编译预计什么时候能支持？

开发已经接近尾声，预计会在3.2.12版本之后的版本带上

**Comment by fxy060608** [comment]
HBuilderX Alpha 3.3.0 已支持
