### ISSUE TITLE
红米手机-uni.scanCode无法拉起手机相机

### ISSUE THREAD

**Issue by GreatGhost** [dcloudio/uni-app#2815]
**新功能描述**
简洁描述你希望补充完善的增强功能

**现状及问题**
[已经开启相机权限，红米手机还是无法拉起手机相机]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by LeoHsi-code** [comment]
我也碰到相同的问题了，最后用html5+的api实现的扫码

**Comment by LeoHsi-code** [comment]
附上一个简单的创建扫码控件的代码
`				var barcode = plus.barcode.create('barcode', [plus.barcode.QR], {
					top: '100px',
					left: '0px',
					width: '300px',
					height: '300px',
					position: 'static'
				});
				var pages = getCurrentPages();
				var page = pages[pages.length - 1];
				var currentWebview = page.$getAppWebview();
				currentWebview.append(barcode);`

**Comment by StrivingRabbit** [comment]
同样的功能在其他手机上可以正常运行，但是红米不行？页面类型是什么？( vue 、nvue )

**Comment by dcloudhdx** [comment]
无法拉起表现是什么，黑屏吗？
请提供设备详细信息，手机系统版本、Android版本、hx版本，自定义基座/标准基座/离线打包?

**Comment by LeoHsi-code** [comment]
> 无法拉起表现是什么，黑屏吗？ 请提供设备详细信息，手机系统版本、Android版本、hx版本，自定义基座/标准基座/离线打包?

后续Hbuilder升级后该问题已被修复
