### ISSUE TITLE
回调函数中调用uni.navigateTo方法，无法正常返回

### ISSUE THREAD

**Issue by hellolixy** [dcloudio/uni-app#2816]
**问题描述**
在很多Android端浏览器上，在A页面的回调函数中（比如onLoad,setTimeout等等）调用uni.navigateTo跳转到B页面，点击返回键，无法正常返回到上一页，可能是仍然停留在第二页，或直接退出整个h5应用

![image](https://user-images.githubusercontent.com/11386336/128801791-d50458f7-aa63-4b6f-aaa8-8290216ca8f0.png)

**预期结果**
按返回键正常返回到上一页

**实际结果**
无法正常返回到上一页，可能是仍然停留在第二页，或直接退出整个h5应用

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 Android 10.0
 - HBuilderX版本 3.1.13
 - 设备信息 小米8

**补充信息**
从Android端端点看，跳转后webview cangoback 参数仍为false

**Comment by zhetengbiji** [comment]
在其他时机，比如 onReady 时跳转是否正常？

**Comment by hellolixy** [comment]
> 在其他时机，比如 onReady 时跳转是否正常？

目前发现只要是回调中调用都不行，只有主动点击时，比如点击按钮，调用才正常

**Comment by hellolixy** [comment]
应该是webview内核的问题，老版本的手机都正常。
临时解决方案：
if (mWebView.canGoBack()) {
       mWebView.goBack();
        return true;
} else if (mWebView.canGoBackOrForward(-1)) {
       mWebView.goBackOrForward(-1);
       return true;
}
