### ISSUE TITLE
Vue3版本的 uni-api的Promise返回值结构怎么变了？

### ISSUE THREAD

**Issue by dnt1996** [dcloudio/uni-app#2817]
```javascript
async function test() {
    // vue2版本的uni-api
    const [err, res] = await uni.login()

    // vue3版本的uni-api
    try {
        const res = await uni.login()
    } catch (err) {

    }
}
```
这样变很难受啊, 要改的地方太多了

uni-app版本 2.0.0-alpha-32120210809004

**Comment by dnt1996** [comment]
> 这个按正常来说应该是第二种方式会更好，框架升级会涉及 api 的优化也很正常，
> 
> 不知道 uni 会不会有向 vue3 一样推出个迁移版

不谈迁移成本，我越来越倾向与使用第一种方式
1.避免了上下文切换时try语句中的变量无法在catch和finally中访问的问题
2.error是类型安全的, 如果使用catch来捕获错误error默认为unknown，还要自己写代码来进行类型收缩

**Comment by TuiMao233** [comment]
事实上，平时使用并不需要很多的错误处理，以及微信现在的大多数 api 都已经支持 promise 模式，
当然 也可能是为了与微信的 api 同步
~~~
![image](https://user-images.githubusercontent.com/49724027/129123348-77ce9729-11ea-402b-aa00-ffdbba9a2ac2.png)
~~~

在我使用的情况下，当我知道 promise 返回的是一个数组而不是结果时我是很迷惑的，
我更希望 promise 像平常使用一样能进入 tryCatch 而不是继续往下走，
例如一些比较常用的库 axios，fast-glob，fs-extra，luch-request  一样，
将代码阻止执行，并抛出错误

**Comment by dnt1996** [comment]
> 事实上，平时使用并不需要很多的错误处理，以及微信现在的大多数 api 都已经支持 promise 模式，
> 
> 当然 也可能是为了与微信的 api 同步
> 
> ![image](https://user-images.githubusercontent.com/49724027/129123348-77ce9729-11ea-402b-aa00-ffdbba9a2ac2.png)
> 
> 
> 
> 在我使用的情况下，当我知道 promise 返回的是一个数组而不是结果时我是很迷惑的，
> 
> 我更希望 promise 像平常使用一样能进入 tryCatch 而不是继续往下走，
> 
> 例如一些比较常用的库 axios，fast-glob，fs-extra，luch-request  一样，
> 
> 将代码阻止执行，并抛出错误
> 
> 

哈哈，我有强迫症，代码有any和unknown不能忍

**Comment by dnt1996** [comment]
实际上不是不能接受api变动，只是官方没有明确说明，我也不太好做迁移，万一又变回去了，那就白干了

**Comment by TuiMao233** [comment]
文档都还没出呢，还是不要着急迁移比较好，感觉很容易出幺蛾子

**Comment by dnt1996** [comment]
> 文档都还没出呢，还是不要着急迁移比较好，感觉很容易出幺蛾子

我负责的项目代码已经全部迁移到composition-api了，就想着赶紧切迁到Vue3让这个项目毕业，这样我就有空去玩react了

**Comment by dnt1996** [comment]
```javascript
//vue.config.js
module.exports = {
    chainWebpack(chain) {
            chain
            .plugin('custom-define')
            .use(webpack.DefinePlugin, [{
                __UNI_FEATURE_PROMISE__: JSON.stringify(true)
            }])
            // 必须在uni-app插件定义之前先自定义，否则不生效
            .before('uni-define')
    }
}
```
