### ISSUE TITLE
input组件,小程序端和h5端表现不一致

### ISSUE THREAD

**Issue by zhl1232** [dcloudio/uni-app#282]
**问题描述**
input组件编译会增加一层父节点，父节点的盒子模型在小程序和H5端表现不一致。

![2](https://user-images.githubusercontent.com/30594030/55705441-61025f00-5a11-11e9-8e26-214db6783bf8.png)
![33](https://user-images.githubusercontent.com/30594030/55705445-63fd4f80-5a11-11e9-8a30-0d367e612646.png)

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
把小程序端的父节点改成
view {
  box-sizing:border-box;
}
或者把H5端父节点样式注释,
div {
    /* box-sizing: border-box; */
}
两边表现一致.

**Comment by xiaoyucoding** [comment]
目前会引发排版问题么，请详细描述并提供下测试代码。

**Comment by zxzhgk** [comment]
我碰到的问题是 H5端会导致在IOS下光标偏上，不能直接使用line-height, 而是采用padding 才能使得光标居中

**Comment by fxy060608** [comment]
预计1.9.3修复此问题

**Comment by xiaoyucoding** [comment]
HBuilderX 1.9.3 及 CLI 均已更新
