### ISSUE TITLE
es6 错误语法 不报错问题

### ISSUE THREAD

**Issue by dufeng-code** [dcloudio/uni-app#2821]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
函数内部变量通过if判断后，再通过let const定义并没有提示语法错误,也没有变量提升。
**复现步骤**
[复现问题的步骤]
```js
onLoad({a}){
if(a){
  let a=a
  console.log(a)
  }
}
```
[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
Uncaught ReferenceError: Cannot access 'a' before initialization

**实际结果**
[这里请贴上你的报错截图或文字]
并没有提示语法错误,也没有变量提升,得到值为undefined

**系统信息:**
 微信小程序

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
if{}编译有独立的作用域？
这种结果是不正确的，并且对于排查代码bug有弊端

**Comment by zhetengbiji** [comment]
a 来自顶部函数作用域：参数
