### ISSUE TITLE
H5端video组件 层级设置问题

### ISSUE THREAD

**Issue by DavidBeckhamyes** [dcloudio/uni-app#2824]
**问题描述**
在安卓设备播放状态的层级过高 无法被外部导航栏遮挡 现在H5端有没有什么方法？

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
H5端怎么了？H5上 video 组件就是标准的 video 标签。 你要实现怎么样的效果？
