### ISSUE TITLE
setCallEventHandler 返回的通话状态 都是undefined

### ISSUE THREAD

**Issue by meiqi1992** [dcloudio/uni-app#2825]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
```js
let CTCall = plus.ios.importClass('CTCall');
        let CTCallCenter = plus.ios.importClass('CTCallCenter');
        let center = new CTCallCenter();
        center.init();
        center.setCallEventHandler(function(res) {
            //这里的res 都是undefined
            console.log('callstatus', res)
        })
```

[或者可以直接贴源代码]

**预期结果**
希望setCallEventHandler能返回正确的通话状态

**实际结果**
[这里请贴上你的报错截图或文字]
center.setCallEventHandler(function(res) {
            //这里的res 都是undefined
            console.log('callstatus', res)
        })

**系统信息:**
 - 发行平台: [App]
 - 操作系统 [ iOS 14.4.]
 - HBuilderX版本 [3.1.22]
 - 设备信息 [iphonex xs]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by ArrayDC** [comment]
native.js不能直接触发回调方法
请按uni原生插件扩展开发此功能，参考：https://nativesupport.dcloud.net.cn/NativePlugin/README
