### ISSUE TITLE
『求助』请教一下目前的主题切换是在SCSS中使用map-get获取主题颜色，但是部分UI框架是通过在data中声明例如custom-style:{color: blue}对象的方式修改内部样式，请问一下在Uniapp中如何取到SCSS中当前主题的配置？

### ISSUE THREAD

**Issue by whoooami** [dcloudio/uni-app#2827]
主题切换类似方案：
项目中虽然没有一键换肤的要求，但是产品要求后期能换主题。在开发组件中涉及到主题的地方，要提取一些公用的变量，不要直接写死样式值。但是如果只是定义一些变量的话，只是完成控制颜色等值的提取。后期切换的话需要把所有变量再写一遍并注释之前的。不是很优雅。

一、Scss部分
定义变量以及映射表
`
// 默认主题

$default-theme : (
  base-color: #ddd,
  border-color: #000
);

//红色主题
$red-theme : (
  base-color: red,
  border-color: red
);

//定义映射集合
$themes: (
  default-theme: $default-theme,
  red-theme: $red-theme
);
`

定义方法,循环遍历映射集合，生成对应样式表

`
@mixin themeify {
    @each $theme-name, $theme-map in $themes {
        //!global 把局部变量强升为全局变量
        $theme-map: $theme-map !global;
        //判断html的data-theme的属性值  #{}是sass的插值表达式
        //& sass嵌套里的父容器标识   @content是混合器插槽，像vue的slot
        [data-theme="#{$theme-name}"] & {
            @content;
        }
    }
}

@function themed($key) {
    @return map-get($theme-map, $key);
}

//获取背景颜色
@mixin _background_color($color) {
    @include themeify {
        background-color: themed($color)!important;
    }
}
`

在组件中,引入公共文件，在要用到的地方使用定义好的mixin
`
@import 'theme.scss'
.block {
    width: 1000px;
    @include _background_color("base-color");
}
`

目前直接在页面的scss中使用是正常的，
但是现在目前其它UI框架要通过custom-style放在data中的变量来传？所以来请教一下该如何在Uniapp中读取到scss中定义的主题变量？
`
data: {
     customStyle: {
         color: red
    }
}
`
谢谢～

抱歉代码格式贴上来有点乱了，调了几次都不行 T_T

**Comment by dnt1996** [comment]
sass只在编译时是动态的，运行时请用原生css变量解决

**Comment by whoooami** [comment]
@dnt1996 感谢回复。如果用原生的css变量，那js取变量的换肤功能就还是要再定义一套了。请问下有没有更好的方式实现换肤？

**Comment by dnt1996** [comment]
css变量并不和sass变量冲突

$color-success: var(--color-success)

body {
  --color-success: green;
}

据我个人的认知，没有比css变量更适合做运行时换肤的方案了

**Comment by whoooami** [comment]
好的，我先去看一下相关资料，谢谢您

**Comment by whoooami** [comment]
@dnt1996 再请教一下，我看了想关资料，用CSS变量和目前通过SCSS切换只是方式上的不同。其实我的主要问题是在Uniapp中如何通过JS取出当前CSS中的属性值？

**Comment by dnt1996** [comment]
page-meta了解下

**Comment by whoooami** [comment]
嗯，刚看了一下，不知道我理解的对不对，看起来是在JS中配置的变量通过page-meta渲染，对页面级别的通用属性做一些配置，应该可以一定程度上可以解决问题。但是如果不是通用级别的，如果涉及多个细节组件，看起来会有点影响性能。也会造成原有改动较大。
我目前用的还是上面的SCSS的切换方案，暂时采用的方式在vuex中再定义一套JS的变量进行类似custom-style组件细节修改变更时使用。
感谢您的一直回复～
