### ISSUE TITLE
使用nvue map组件如何自定义气泡窗口？

### ISSUE THREAD

**Issue by Liu-Peter** [dcloudio/uni-app#2828]
**问题描述**
使用nvue map 如何在app端自定义气泡窗口？

**Comment by dcloudhdx** [comment]
支持背景、前景、边框圆角等，可以在绑定气泡时设置这些属性，详情参考 [https://uniapp.dcloud.net.cn/component/map](https://uniapp.dcloud.net.cn/component/map)

**Comment by StrivingRabbit** [comment]
由于长时间未回复，此issue关闭，如果还有问题可以重开或提新的issue
