### ISSUE TITLE
App端uni.getLocation()失效

### ISSUE THREAD

**Issue by liugx2018** [dcloudio/uni-app#2829]
问题描述
App端 uni.getLocation()使用系统定位，此API失效。

复现步骤
uni.getLocation({
	success: ({
		longitude,
		latitude
	}) => {
		console.log(longitude,latitude)
	}
})

系统信息:
APP平台

**Comment by StrivingRabbit** [comment]
信息太少，无法定位问题所在。可以消息的描述一下吗
