### ISSUE TITLE
使用cli初始化demo,onload钩子内报错

### ISSUE THREAD

**Issue by Stan1812** [dcloudio/uni-app#283]
**问题描述**

初始化项目demo,出现这个bug:

VM425:1 thirdScriptError
Cannot read property '$mp' of undefined;at "pages/index/index" page lifeCycleMethod onLoad function
TypeError: Cannot read property '$mp' of undefined

**复现步骤**

在HbuilderX中初始化demo也会报同样的错
Hbuilderx版本：1.8.2.20190401

**系统信息:**
 - 发行平台: [ 微信小程序]
 - 开发平台: [macos]
 - HBuilderX版本 [1.8.2.20190401]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
在 cli 工程执行 npm update,更新最新的 cli，然后测试是否还有问题

**Comment by tailgo** [comment]
> 在 cli 工程执行 npm update,更新最新的 cli，然后测试是否还有问题

今天更新了版本 我也还是会出现这种情况
