### ISSUE TITLE
输入键盘有问题

### ISSUE THREAD

**Issue by Leixiaodong** [dcloudio/uni-app#2830]
**问题描述**
输入键盘有问题。input输入框，如果type="number"，先输入数字，完后再输入type="text"，会导致出现输入时候，出现type="number"的最后一位

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看
```
     <view class="cu-form-group">
            <view class="title">
              <text class="text-red" v-if="(!dataForm.accountName) || checkRes.indexOf('户名')!=-1">*</text>
              <text class="text-df">户名</text>
            </view>
            <input class="text-right" v-model="dataForm.accountName" placeholder="请输入户名">
          </view>

          <view class="cu-form-group">
            <view class="title">
              <text class="text-red" v-if="(!dataForm.accountTel) || checkRes.indexOf('银行预留手机号')!=-1">*</text>
              <text class="text-df">银行预留手机号</text>
            </view>
            <input type="number" class="text-right" v-model="dataForm.accountTel" placeholder="请输入银行预留手机号">
          </view>
```
![image](https://user-images.githubusercontent.com/20106261/129525934-8f582638-3e53-49da-9dfe-0b0f5938d669.png)

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
![image](https://user-images.githubusercontent.com/20106261/129526226-935f959d-b09d-427a-bae0-b0712c9ff48a.png)
![image](https://user-images.githubusercontent.com/20106261/129526164-4c61a8c1-ebbf-4495-94ef-1985ecc8cd1e.png)

**系统信息:**
 - 发行平台: [5+ App]
 - 操作系统 [Android 7.0]
 - HBuilderX版本 [3.1.22]
 - uni-app版本
 - 设备信息 华为，小米

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
1. 用的是搜狗输入法吗？
2. 把输入法中文联想关闭是否还有问题？
3. iOS是否正常？
