### ISSUE TITLE
Module '"vue"' has no exported member 'ref'

### ISSUE THREAD

**Issue by gay5882007** [dcloudio/uni-app#2831]
按照官网步骤用cli方式创建 vue3项目  vue3的组合api都会报错  Module '"vue"' has no exported member 'xxxx',请问是什么原因？

**Comment by zhetengbiji** [comment]
依赖安装的版本多少？

**Comment by gay5882007** [comment]
> 依赖安装的版本多少？

3.0.0

**Comment by zhetengbiji** [comment]
> > 依赖安装的版本多少？
> 
> 3.0.0

哪个依赖的版本是这个？

**Comment by gay5882007** [comment]
> > > 依赖安装的版本多少？
> > 
> > 
> > 3.0.0
> 
> 哪个依赖的版本是这个？
vue 3.0.0   vue-cli是 4.5.13

**Comment by gay5882007** [comment]
> > > 依赖安装的版本多少？
> > 
> > 
> > 3.0.0
> 


> 哪个依赖的版本是这个？

**Comment by gay5882007** [comment]
> > > 依赖安装的版本多少？
> > 
> > 
> > 3.0.0
> 
> 哪个依赖的版本是这个？

![image](https://user-images.githubusercontent.com/48502742/129676129-4afd37b6-2b7c-4c39-a2bb-b22c82d8ff5f.png)

**Comment by zhetengbiji** [comment]
https://ask.dcloud.net.cn/article/37834

**Comment by gay5882007** [comment]
> https://ask.dcloud.net.cn/article/37834

是的  我是按照cli方式来创建的  然后引入组合api vscode就报错  但是开发者工具 代码能正常执行

**Comment by zhetengbiji** [comment]
> > https://ask.dcloud.net.cn/article/37834
> 
> 是的 我是按照cli方式来创建的 然后引入组合api vscode就报错 但是开发者工具 代码能正常执行

你是按的说明里的哪个部分创建的？

**Comment by gay5882007** [comment]
> > > https://ask.dcloud.net.cn/article/37834
> > 
> > 
> > 是的 我是按照cli方式来创建的 然后引入组合api vscode就报错 但是开发者工具 代码能正常执行
> 
> 你是按的说明里的哪个部分创建的？

![image](https://user-images.githubusercontent.com/48502742/129678621-5f7826f7-2316-4683-b767-32691697874c.png)

**Comment by gay5882007** [comment]
> > > https://ask.dcloud.net.cn/article/37834
> > 
> > 
> > 是的 我是按照cli方式来创建的 然后引入组合api vscode就报错 但是开发者工具 代码能正常执行
> 
> 你是按的说明里的哪个部分创建的？

按照 cli创建小程序

**Comment by zhetengbiji** [comment]
如果不使用 ts 运行正常吗？

**Comment by gay5882007** [comment]
> 如果不使用 ts 运行正常吗？
不使用ts模板是可以正常运行也不会报错

**Comment by zhetengbiji** [comment]
> > 如果不使用 ts 运行正常吗？
> > 不使用ts模板是可以正常运行也不会报错

那应该是类型检查的问题，匹配到了 vue2 的

**Comment by gay5882007** [comment]
> > > 如果不使用 ts 运行正常吗？
> > > 不使用ts模板是可以正常运行也不会报错
> 
> 那应该是类型检查的问题，匹配到了 vue2 的

那应该怎么办？ 清除vue2?

**Comment by ogoss** [comment]
> > > > 如果不使用 ts 运行正常吗？
> > > > 不使用ts模板是可以正常运行也不会报错
> > 
> > 
> > 那应该是类型检查的问题，匹配到了 vue2 的
> 
> 那应该怎么办？

查看下package.json中依赖的typescript版本，如果是3.X的话，更新到4.X试试

**Comment by fxy060608** [comment]
可以创建最新的cli工程：npx degit dcloudio/uni-preset-vue#vite my-vue3-project

**Comment by kyon12345** [comment]
这个问题关闭了吗,已经更新到4.x.x版本了(使用最新模板vite+vue3),但是vscode的vetur插件还是会报这个错误,运行倒是正常运行
![image](https://user-images.githubusercontent.com/39485303/229476539-befd2460-95de-4f60-ae6a-2c5fbc54a99e.png)
