### ISSUE TITLE
Module '"vue"' has no exported member 'ref'

### ISSUE THREAD

**Issue by gay5882007** [dcloudio/uni-app#2832]
按照官方给的步骤 使用cli方式创建vue3项目 引入组合api  vscode报错 Module '"vue"' has no exported member 'xxxx' 但是微信开发者工具能正常执行组合api功能

**Comment by zhetengbiji** [comment]
按的哪个步骤？

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/2831

**Comment by gay5882007** [comment]
> 按的哪个步骤？

![image](https://user-images.githubusercontent.com/48502742/129678011-d8aeb631-8c91-406a-83fe-3cab6463125d.png)

**Comment by gay5882007** [comment]
![image](https://user-images.githubusercontent.com/48502742/129678076-b1f235b1-9f10-4033-99ba-bddac45b19f6.png)
