### ISSUE TITLE
uni-swiper-dot组件问题

### ISSUE THREAD

**Issue by 15027302155** [dcloudio/uni-app#2834]
**问题描述**
uni-swiper-dot组件点击不能切换

**复现步骤**
[复现问题的步骤]
1.  在sweiper-dot切换到指示点轮播图时
2.  首先将页面滑动到最后一页，然后点击第一个指示点。
3.  无法切换到current为0的第一个指示点。其他指示点可以点击切换。

**Comment by StrivingRabbit** [comment]
使用 `uni-swiper-dot` 的时候。`swiper` 组件的 `current` 属性，请在  `@change`  事件中进行同步修改。否则这个值是不会和组件内部同步的，一直为开始值，因此会导致切换的问题
