### ISSUE TITLE
uniapp scroll-view iOS14.5.1 不能滚动 且 自动换行

### ISSUE THREAD

**Issue by gfoxlin** [dcloudio/uni-app#2835]
**问题描述**
使用vue 非nvue方式
uniapp scroll-view 设置为水平滚动条后 iOS14.5.1 不能滚动 且 自动换行；

**复现步骤**
[复现问题的步骤]
直接手机上查看即可

[或者可以直接贴源代码]

				<view class="second">
					
					<scroll-view scroll-x="true" class="scroll-view-x" scroll-with-animation="true" :scroll-left="scrllLeft">
						<view v-for="(item, index) in subject_data" :key="index" class="navigator_first" :id="('index'+index)" @tap="selectSubject"
						 :data-sindex="index" :data-sc="item.subject_code" :data-si="item.subIndex" data-currentsubject="0">
							<view class="subject-select-all">
								<view :class="'subject_select ' + (index==subjectSelectedIndex ? '_yes' : '')">{{item}}</view>
								<view :class="'subject_select_underline ' + (index==subjectSelectedIndex ? '_yes' : '')"></view>
							</view>

						</view>
					</scroll-view>
				</view>
**预期结果**
可以正常滑动点击 水平滚动内容

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/4136880/129866042-9a4b0ceb-5231-4b65-ba95-7570f534afe8.png)

**系统信息:**
 - 发行平台: [5+ App]
 - 操作系统 [如 iOS 14.5.1]
 - 设备信息 [如 iPhone XS]

**Comment by StrivingRabbit** [comment]
1. 使用的什么版本的HX，如果的cli，一样说明版本
2. 在其他平台是否正常
