### ISSUE TITLE
打包成app时如何区分多环境

### ISSUE THREAD

**Issue by fuguxu** [dcloudio/uni-app#2836]
用HBuilderX生成的项目，当打包成原生app时，如何区分多环境呢，官方的在package.json里自定义平台没有app-plus选项，请问有啥办法呢

**Comment by StrivingRabbit** [comment]
要区分怎样的环境？

**Comment by fuguxu** [comment]
> 要区分怎样的环境？

比如 sit，uat，pro等，线上不同的环境

**Comment by Hero-King** [comment]
解决了吗 查了好多资料 云打包不支持配置环境啊

**Comment by StrivingRabbit** [comment]
> 解决了吗 查了好多资料 云打包不支持配置环境啊

可以具体描述一下你的需求吗？

**Comment by Hero-King** [comment]
使用Uni-app 打包apk 只有NODE_ENV=production环境 想要打调用点是stage测试环境 的apk 该怎么操作

**Comment by StrivingRabbit** [comment]
> 使用Uni-app 打包apk 只有NODE_ENV=production环境 想要打调用点是stage测试环境 的apk 该怎么操作

webpack 可以使用 `webpack.DefinePlugin` 
vite 可以配置 `define` 字段

**Comment by Hero-King** [comment]
那这样只能使用cli创建项目了  使用hbuilder cli打包

**Comment by StrivingRabbit** [comment]
> 那这样只能使用cli创建项目了 使用hbuilder cli打包

不用啊，在根目录加 vue.config.js 或者 vite.config.js 就可以

**Comment by Hero-King** [comment]
我明白在vue.config.js中自定义环境变量解决调用点问题 就像vue PC项目一样  ; 但是使用Hbuilder打包apk时 想生成测试环境apk 或者生产环境apk  每次都要去改动vue.config.js吗  我的理解app端也需要自定义平台功能

**Comment by StrivingRabbit** [comment]
对，目前就是修改配置文件，然后启用你需要的变量名称，建议不要使用 development ，因为 uni 也会用。然后云打包发自我的 iPhone在 2023年5月8日，12:03，Hero-King ***@***.***> 写道：﻿
我明白在vue.config.js中自定义环境变量解决调用点问题 就像vue PC项目一样  ; 但是使用Hbuilder打包apk时 想生成测试环境apk 或者生产环境apk  每次都要去改动vue.config.js吗  我的理解app端也需要自定义平台功能

**Comment by tong822218** [comment]
这个问题确实很扯，每次打包测试环境的apk，都要去改配置文件的话 ，我不如直接去代码中改一下变量值就好了，，感觉需要再 
package.json 的 uni-app:{ scripts:{}} 这里面支持 app-plus
