### ISSUE TITLE
升级1.8版本后globalData问题

### ISSUE THREAD

**Issue by qianbingjian** [dcloudio/uni-app#284]
**问题描述**
升级到1.8版本后无法获取到globalData对象，请问新版本是移除了吗

**复现步骤**

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**

**补充信息**
[可选]

**Comment by qianbingjian** [comment]
升级到1.8版本后无法获取到globalData对象

**Comment by mehaotian** [comment]
您好，贴一下你的代码，看看你是怎么用的。

**Comment by qianbingjian** [comment]
> 您好，贴一下你的代码，看看你是怎么用的。

![image](https://user-images.githubusercontent.com/19208023/55787967-0be64c00-5aea-11e9-9205-6806b2998eb1.png)
以前的getApp()返回的对象里面包含有globalData,现在直接没有了，非h5端，导致升级后项目直接瘫了

**Comment by mehaotian** [comment]
已经修复问题，globalData 可以向下兼容，但是现在不推荐使用 globalData 。
