### ISSUE TITLE
VideoPlayer层级无法进行调整

### ISSUE THREAD

**Issue by TheSunxijie** [dcloudio/uni-app#2840]
![image](https://user-images.githubusercontent.com/60965715/130343738-bc7987fc-a467-4de7-a192-5823c236bf3e.png)
![image](https://user-images.githubusercontent.com/60965715/130343749-87646ee4-6510-4a4d-80a8-f36f5d65efa2.png)
当拖动，以及进行弹框的时候，视频总是在最上层，导致显示问题和无法看清楚弹框内容

**Comment by StrivingRabbit** [comment]
1. <video/> 组件在非H5端是原生组件，层级高于普通前端组件，覆盖其需要使用cover-view组件或plus.nativeObj.view、subNVue。微信基础库 2.4.0+和字节跳动小程序 已支持 video 组件的同层渲染，也就是video在非全屏时，可以被前端元素通过调节z-index来遮挡，但video全屏时，仍需要cover-view覆盖。
2. 弹框是自定义的吗
