### ISSUE TITLE
Uni-app调用系统日历，同步/添加/修改/删除日程的功能目前官方有大概的排期吗？

### ISSUE THREAD

**Issue by whoooami** [dcloudio/uni-app#2841]
**新功能描述**
如题

**现状及问题**
目前插件市场有部分，但是功能基本有的只有添加/删除。功能不够完善，并且只支持单端。比如支持IOS，不支持Android。，并且系统版本参差不齐。

**尝试方案**
建议平台可以完善这块功能，以满足下面补充信息中描述的新兴功能的需要。让Uniapp可以更流畅的方便的全端开发。

**补充信息**
因为目前各大厂商。比如招聘类、旅行类、甚至某些外卖的系统都会在用户触发功能后写入用户的Calendar以提醒用户，但是Uniapp目前没有官方对此的统一解决方案，对这些新兴的市场功能不太友善。建议平台可以完善这块功能，以满足这些新兴功能的需要。让Uniapp可以更流畅的方便全端开发。

**Comment by whoooami** [comment]
感谢，添加这块用以上可以满足。我们目前需要的是完善的功能。比如日程的同步导入，以检测用户在该时段是否可以安排之类的？

**Comment by hbcui1984** [comment]
官方对这部分无排期，建议使用native.js或自行扩展原生模块来实现。
