### ISSUE TITLE
@dcloudio/types 类型错误

### ISSUE THREAD

**Issue by TuiMao233** [dcloudio/uni-app#2845]
**问题描述**
tsc 打包显示类型错误
@dcloudio/types 版本：2.5.1
**复现步骤**
![image](https://user-images.githubusercontent.com/49724027/130385747-1ea08972-e1da-4730-a103-50d231b34164.png)

没有写返回值
`缺少返回类型批注的“showContentPage”隐式具有“any”返回类型。`
![image](https://user-images.githubusercontent.com/49724027/130385783-b6efea63-7af9-4585-95ff-c58f67cf384e.png)

**Comment by dnt1996** [comment]
只能开启skipLibCheck来解决了，官方的类型声明不知道在哪维护的，想提pr都没地方提

**Comment by Wangyaqi** [comment]
收到，我们调整下

**Comment by zhetengbiji** [comment]
感谢反馈，已更新 2.5.4
