### ISSUE TITLE
This relative module was not found ../../i18n/index.js 

### ISSUE THREAD

**Issue by Luooooooo** [dcloudio/uni-app#2846]
**问题描述**
```
This relative module was not found:

* ../../i18n/index.js in ./node_modules/babel-loader/lib!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--12-1!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/script.js!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib??vue-loader-options!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/style.js!./node_modules/@dcloudio/uni-ui/lib/uni-datetime-picker/uni-datetime-picker.vue?vue&type=script&lang=js&,
./node_modules/babel-loader/lib!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--12-1!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/script.js!./node_modules/@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib??vue-loader-options!./node_modules/@dcloudio/webpack-uni-mp-loader/lib/style.js!./node_modules/@dcloudio/uni-ui/lib/uni-load-more/uni-load-more.vue?vue&type=script&lang=js&
```

**复现步骤**
[复现问题的步骤]
1.  启动 yarn dev:mp-weixin

[或者可以直接贴源代码]

**预期结果**
正常启动

**实际结果**
```
yarn dev:mp-weixin
```

**系统信息:**
 - 发行平台: [微信小程序]
 - 操作系统 [windows] 
 - uni-app版本 [^2.0.0 新安装，最新版本]
 - 设备信息 [如 微信开发者工具]

**补充信息**
1. VUE3 + TS
2. 其中还报“@/static/uni.ttf”找不到，解决是copy到项目的static文件夹
[根据你的分析，出现这个问题的原因可能在哪里？]
VUE3不兼容

**Comment by YuYanDev** [comment]
遇到两个同样问题，/static/uni.ttf问题复制了uni-ui的static文件夹下来后解决了，这个i18n是table组件引入遇到的

**Comment by Luooooooo** [comment]
> 遇到两个同样问题，/static/uni.ttf问题复制了uni-ui的static文件夹下来后解决了，这个i18n是table组件引入遇到的

i18n：其他只要用到i18n的组件都会报错，等待看下个版本是否会修复。
另外强烈建议支持tsx，同时喜欢react和uni，但是uni是基于vue的，vue3部分types还不全😂

**Comment by StrivingRabbit** [comment]
是cli项目吗？使用`2.0.0-alpha-32620210831002`测试没有发现问题

**Comment by Luooooooo** [comment]
> 是cli项目吗？使用`2.0.0-alpha-32620210831002`测试没有发现问题

是的，我没用alpha版本

**Comment by StrivingRabbit** [comment]
@Luooooooo 试试alpha如果没有问题的话，可以先使用alpha。alpha后面会转正
