### ISSUE TITLE
在scss中使用`@use`出现错误

### ISSUE THREAD

**Issue by januwA** [dcloudio/uni-app#2849]
**问题描述**

我在style中使用`@use`
```
<style lang="scss" scoped>
@use "sass:math";

...
</style>
```

但运行时出现错误
```
[ WXSS 文件编译错误] ./pages/home/home.wxss
 unexpected token ""sass:math""
  26 | /* 透明度 */
  27 | /* 文章场景相关 */
> 28 | @use "sass:math";
     |     ^
at files://pages/home/home.wxss#28(env: Windows,mp,1.05.2108130; lib: 2.19.2)
```

**系统信息:**
 - 发行平台:  微信小程序
 - HBuilderX版本 3.2.2.20210818

**补充信息**
我不清楚能不能在uniapp中使用"@use"语法

**Comment by dnt1996** [comment]
你用的如果是node-sass，是不能使用这个语法的，除非切换成dart-sass

**Comment by januwA** [comment]
> 你用的如果是node-sass，是不能使用这个语法的，除非切换成dart-sass

dart-sass 以后会是主流，node-sass会被淘汰

我是用的vue2因该默认使用的是node-sass，有什么方法升级到dart-sass吗?

**Comment by dnt1996** [comment]
npm uninstall node-sass
npm i -D sass fibers

直接切换就可以了，dart-sass和node-sass具体差异请参阅官方文档

**Comment by januwA** [comment]
> npm uninstall node-sass
> npm i -D sass fibers
> 
> 直接切换就可以了，dart-sass和node-sass具体差异请参阅官方文档

在请教下，我是直接在hbuilderx上开发的，我该怎样切换呢？

**Comment by dnt1996** [comment]
没用过hbuilder，不太清楚

**Comment by WM-P** [comment]
在uni.scss
@use就可以了

**Comment by januwA** [comment]
有人吗，现在在vue3项目还是有这个问题

**Comment by januwA** [comment]
```
11:54:30.828   Error: @use rules must be written before any other rules.
11:54:30.841       ╷
11:54:30.841   100 │     @use "sass:color";
```

**Comment by januwA** [comment]
只能在uni.scss文件中使用@use，组件样式直接使用函数就行。

**Comment by MrGao-hy** [comment]
> 只能在uni.scss文件中使用[@use](https://github.com/use)，组件样式直接使用函数就行。

谢谢大佬，也遇到这个问题
