### ISSUE TITLE
vue.config中使用webpack插件或导入webpack报错

### ISSUE THREAD

**Issue by kami67** [dcloudio/uni-app#2850]
**问题描述**
无法使用webpack插件功能
例如：配置webpack.ContextReplacementPlugin或 CompressionWebpackPlugin均出现错误。

**复现步骤**

> 情况1

``` js
const compressionWebpackPlugin = require('compress-webpack-plugin')  

module.exports = {
  chainWebpack: (config) => {
    config.plugin('compressionWebpackPlugin').use(compressionWebpackPlugin, [{
      filename: '[path].gz[query]',
      algorithm: 'gzip',
      test: new RegExp('\\.(' + ['js', 'css'].join('|') + ')$'),
      threshold: 10240,
      minRatio: 0.8,
      deleteOriginalAssets: false
    }])
  }
}
```

> 情况2
``` js
const webpack = require('webpack')

module.exports = {
  configureWebpack: {
    plugins: [
      new webpack.ContextReplacementPlugin(
        /moment[\\\/]locale$/,
        /^\.\/(zh-cn)$/
      )
    ]
  }
}
```

**预期结果**
编译无报错

**实际结果**
![image](https://user-images.githubusercontent.com/44158394/130744489-2ea7cd53-5d74-4ff4-b31e-ce2eb9787ff4.png)

**系统信息:**
 - 发行平台: H5
 - HBuilderX版本 vue-cli版本
 - uni-app版本 2.0.0-31420210305001
 - npm版本 6.14.8
 - vue-cli版本 4.5.7

**补充信息**
是否与uni-app内部引用webpack出现冲突

**Comment by StrivingRabbit** [comment]
由于长时间未回复，此issue关闭，如果还有问题可以重开或提新issue
