### ISSUE TITLE
安卓打包后隐私协议弹框不出现

### ISSUE THREAD

**Issue by xhuishen** [dcloudio/uni-app#2859]
**问题描述**
3.2.3版本HBuilderX打包uniapp隐私协议弹框不出现 
只有3.2.1测试版本的HBuilderX才会弹出隐私协议弹框
已经勾选使用原生隐私协议提示框  并且配置了androidPrivacy.json

**系统信息:**
 - 发行平台: app
 - 操作系统  Android  
 - HBuilderX版本 3.2.3
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**Comment by st-dc** [comment]
androidPrivacy.json里面看看是不是有注释 如果有请删除

**Comment by ArrayDC** [comment]
请更新到HBuilderX最新版本。
注意：需要在androidPrivacy.json中配置完整内容，参考：https://ask.dcloud.net.cn/article/36937
