### ISSUE TITLE
小程序中swiper组件无法隐藏指示点

### ISSUE THREAD

**Issue by weiyunpeng** [dcloudio/uni-app#286]
**问题描述**
小程序中swiper组件无法隐藏指示点

**复现步骤**
`<swiper
        :vertical="vertical"
        :autoplay="true"
        :circular="true"
        :indicator-dots="false"
        interval="3000"
      >
        <swiper-item></swiper-item>
      </swiper>`

**预期结果**
indicator-dots设置为false或者默认不设置indicator-dots时，不显示指示点

**实际结果**
不设置indicator-dots或者indicator-dots设置为false时指示点还在

**系统信息:**
@dcloudio/uni-mp-weixin 0.0.932
@dcloudio/uni-template-compiler 0.9.153
@dcloudio/webpack-uni-mp-loader 0.3.611
@dcloudio/webpack-uni-pages-loader 0.2.821

**Comment by 569202812** [comment]
解决了吗

**Comment by dcloudhdx** [comment]
微信小程序中测试正常

**Comment by 569202812** [comment]
> 微信小程序中测试正常
在我设置了一次 ```:indicator-dots="false"``` 就可以了(去掉就可以了),貌似像是缓存的原因
![image](https://user-images.githubusercontent.com/34082148/56213778-42ded380-608f-11e9-8935-1c037c46c0ae.png)

**Comment by 569202812** [comment]
> 微信小程序中测试正常

![image](https://user-images.githubusercontent.com/34082148/56214324-3f981780-6090-11e9-9e6e-bcdbfc07c148.png)
原来是他这个组件的原因

**Comment by weiyunpeng** [comment]
> > 微信小程序中测试正常
> 
> ![image](https://user-images.githubusercontent.com/34082148/56214324-3f981780-6090-11e9-9e6e-bcdbfc07c148.png)
> 原来是他这个组件的原因

确实是，兼容了下给swiper增加两个属性
` indicator-color="rgba(255,255,255,0)"
   indicator-active-color="rgba(255,255,255,0)"`
设置为透明给隐藏掉了
