### ISSUE TITLE
小程序component中使用/deep/样式穿透不生效，page中使用生效

### ISSUE THREAD

**Issue by Cowjiang** [dcloudio/uni-app#2861]
说明：
此处使用了uview组件库

嵌套关系：
page引用component，在component.vue引用u-select，u-select包含u-popup

问题所在：
1. 在component中，通过样式穿透，无法生效
2. 在page中，使用样式穿透，可以生效
3. 覆写u-select组件，可以使用样式穿透应用于u-popup

例：
/deep/ .u-drawer-content, .u-picker-header {
      border-radius: rpx(30);
}

**Comment by Lisheri** [comment]
微信小程序让样式穿透生效需要在父组件中添加:
options: {
    styleIsolation: 'shared'
 }
