### ISSUE TITLE
uniapp 开发环境下 微信小程序  地图 上下文 没有 removeMarkers 方法

### ISSUE THREAD

**Issue by liuyonghu** [dcloudio/uni-app#2863]
![6J@{{6%C5_C DT6%~2`CY9D](https://user-images.githubusercontent.com/14899215/131840056-f2626fea-d32b-47ea-939b-a8341f34dfa0.png)

**Comment by StrivingRabbit** [comment]
实测是有的，你使用的环境是多少？可否提供一个demo?

**Comment by StrivingRabbit** [comment]
由于长时间未回复，此issue关闭，如果还有问题可以重开或提新的issue
