### ISSUE TITLE
支付宝小程序全局分享设置

### ISSUE THREAD

**Issue by Yaob1990** [dcloudio/uni-app#2864]
支付宝小程序支持全局分享设置，现在的事件调用没有调用到 app.vue 的  onShareAppMessage 事件

文档地址：https://opendocs.alipay.com/mini/framework/app-detail

![image](https://user-images.githubusercontent.com/22534346/131868201-29cd904b-8330-4cd2-9c36-faebca77ca03.png)

fix 地址：https://github.com/dcloudio/uni-app/pull/2844/files

**Comment by Yaob1990** [comment]
@zhanjinfeng 哥，帮忙看下呢

**Comment by StrivingRabbit** [comment]
65c374f21f0679027d3b86908378eed7b25ca47c

**Comment by Yaob1990** [comment]
> [65c374f](https://github.com/dcloudio/uni-app/commit/65c374f21f0679027d3b86908378eed7b25ca47c)
> 
> 已提交至dev。预计下版带上

第二次给 uniapp 提交代码就被合入了，开心😄
