### ISSUE TITLE
node_module下文件改变不会触发自动编译

### ISSUE THREAD

**Issue by huadong** [dcloudio/uni-app#2869]
参考PR #2798

代码居然写死了让webpack忽略node_module下的文件改变，而这个配置完全可以让具体项目自己去设置。

全局写死导致同时开发子项目和主项目时，需要不停的重新编译主项目才能预览，不能进行热编译。

每次提交PR，基本都无人理睬，连句评论回复都没有。不维护了？@fxy060608 @zhetengbiji

**Comment by StrivingRabbit** [comment]
在维护的，会考虑相关变动

**Comment by huadong** [comment]
🙏那就好，以为抗不过疫情了。

这种工程配置选项，用不着在类库里写死。以前也没有写死，不知道哪个工程师一时兴起。。。🙃

**Comment by kiros666** [comment]
@huadong 感谢大佬，折腾了几天，照着你这个进行修改后可以了

ps：希望官方能早日修复这个问题
