### ISSUE TITLE
video组件 层级最高

### ISSUE THREAD

**Issue by LiuXin0807** [dcloudio/uni-app#287]
**问题描述**
当把视频全屏当做背景的时候，不管是通过同级层级处理，还是通过cover-view 的方式来处理，只要视频播放， 文案都会没有视频层级会变成最高。
在ios机型出现，ios12.2是全部机型都是这个问题，之前版本有一部分是这样的问题
安卓OK

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by dcloudhdx** [comment]
请提供示例代码，用下面的代码测试没有问题
```
<video id="myVideo" src="https://img.cdn.aliyun.dcloud.net.cn/guide/uniapp/%E7%AC%AC1%E8%AE%B2%EF%BC%88uni-app%E4%BA%A7%E5%93%81%E4%BB%8B%E7%BB%8D%EF%BC%89-%20DCloud%E5%AE%98%E6%96%B9%E8%A7%86%E9%A2%91%E6%95%99%E7%A8%8B@20181126.mp4">
    <cover-view class="cover-view" style="color: #ccc;">简单的cover-view</cover-view>
</video>
```

**Comment by dcloudhdx** [comment]
Bug已确认，可以使用 nvue 页面解决

**Comment by dcloudhdx** [comment]
更新 HBuilderX 试试

**Comment by dcloudhdx** [comment]
请更新版本再试，如果还有问题再次打开 issues
