### ISSUE TITLE
ios iPhone XS Max 软键盘弹出会出现延迟卡顿

### ISSUE THREAD

**Issue by afsdfsdf232** [dcloudio/uni-app#2871]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
使用的 uni-app 版本多少

**Comment by afsdfsdf232** [comment]
uni-app版本：13.2.3 ，  hbuilder版本：3.2.3.20210825

**Comment by zhetengbiji** [comment]
ios 版本多少？

**Comment by afsdfsdf232** [comment]
14.4.1

**Comment by afsdfsdf232** [comment]
System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i5-10210U CPU @ 1.60GHz
  Binaries:
    Node: 14.17.1 - C:\Program Files\nodejs\node.EXE      
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD        
    npm: 6.14.13 - C:\Program Files\nodejs\npm.CMD        
  Browsers:
    Edge: 44.19041.1023.0
  npmPackages:
    @dcloudio/types: * => 2.4.5
    @dcloudio/uni-app-plus: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-automator: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-cli-shared: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-h5: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-helper-json: * => 1.0.13
    @dcloudio/uni-i18n: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-migration: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-360: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-alipay: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-baidu: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-kuaishou: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-qq: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-toutiao: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-vue: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-weixin: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-quickapp-native: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-quickapp-webview: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-stat: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-template-compiler: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @hap-toolkit/dsl-vue:  0.6.13
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.0.6
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.13
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.13
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.13
    @vue/cli-plugin-eslint: ~4.5.0 => 4.5.13
    @vue/cli-plugin-router:  4.5.13
    @vue/cli-plugin-vuex:  4.5.13
    @vue/cli-service: ~4.5.0 => 4.5.13
    @vue/cli-shared-utils:  4.5.13
    @vue/component-compiler-utils:  3.2.2 (3.2.2)
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/shared: ^3.0.0 => 3.1.5
    @vue/web-component-wrapper:  1.3.0
    eslint-plugin-vue: 7.11.1 => 7.11.1
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.11 => 2.6.14
    vue-eslint-parser:  7.10.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.8 (16.4.1, 15.9.8)
    vue-router:  3.0.1
    vue-style-loader:  4.1.3 (4.1.3)
    vue-template-compiler: ^2.6.11 => 2.6.14 (2.6.14)
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.2.0 => 3.6.2
    vuex-persistedstate: ^4.0.0-beta.3 => 4.0.0
  npmGlobalPackages:
    @vue/cli: Not Found

**Comment by zhetengbiji** [comment]
更新 uni 相关依赖

**Comment by afsdfsdf232** [comment]
执行了yarn upgrade也一样

**Comment by zhetengbiji** [comment]
> 执行了yarn upgrade也一样

手动更新版本并安装一下，方式见文档
