### ISSUE TITLE
app端控制台打印日志经常出现 [object object]

### ISSUE THREAD

**Issue by RenYC** [dcloudio/uni-app#2873]
**问题描述**
app端控制台打印日志经常出现 [object object]

**复现步骤**
[复现问题的步骤]
1.  启动项目
2. onShow声明周期里打印this
3. 查看控制台日志

[或者可以直接贴源代码]

**预期结果**
可以查看this下面挂载了哪些属性或方法

**实际结果**
实际显示 [object object]

**系统信息:**
 - 发行平台: app调试
 - HBuilderX版本 3.2.3

**Comment by StrivingRabbit** [comment]
这是因为 Object 对象直接 toString 的话，会报错。可以使用  JSON.stringify 处理一下
