### ISSUE TITLE
qq和微信小程序都新增了supportedMaterials，uni现在不支持吗

### ISSUE THREAD

**Issue by maskletter** [dcloudio/uni-app#2874]
这个是文档
https://q.qq.com/wiki/develop/miniprogram/frame/open_ability/support_material.html

![image](https://user-images.githubusercontent.com/15777183/132232253-50858c59-c9f7-4a8d-a403-933be7356868.png)

**Comment by Husky-Yellow** [comment]
有个损招，当你在小程序开发者工具编译后，自己手动加这个，然后提交审核

**Comment by fxy060608** [comment]
在manifest.json对应平台下配置`supportedMaterials`

```json
 "mp-qq": {
        "supportedMaterials": []
    },
```
