### ISSUE TITLE
用官网的案例获取webview对象，报错'$getAppWebview' undefined

### ISSUE THREAD

**Issue by Manhoiii** [dcloudio/uni-app#2878]
**问题描述**
https://uniapp.dcloud.io/component/web-view?id=web-view
我使用了App端web-view的扩展中的案例代码，想获取currentWebview对象，但获取不到

源代码：
onReady() {
			console.log(this)
			var currentWebview = this.$scope.$getAppWebview();
				setTimeout(function() {
					wv = currentWebview.children()[0]
					wv.setStyle({top:150,height:1})
			}, 50);
		},

经过网上查询，this.$scope.$parent.$getAppWebview()，this.$mp.page.$getAppWebview() 也同样都会报错
打印过vue组件对象，也没有找到$getAppWebview()

**问题：**
所以vue组件中的$getAppWebview()去哪里了？

**系统信息:**
 - 发行平台：app
 - 操作系统：ios
 - HBuilderX版本：3.1.22
 - 设备信息：ipad 19年版

**Comment by StrivingRabbit** [comment]
使用的 官网案例demo 测试没有什么问题。ios 什么版本？安卓有没有这个问题？

**Comment by Manhoiii** [comment]
ios14的，安卓未测试
**这是我写vue文件：**
`<template>
	<view>
		<view class="content" style="width: 50%;height: 50%;">
			<view class="to_back" @tap="doBack" style="width: 60px; height: 60px; border-radius: 60px;">
				<text class="cuIcon-back" style="color: #FFFFFF;"></text>
			</view>
			<web-view v-if="url" :src="url"></web-view>
		</view>
		
	</view>
</template>

<script>
	var wv;
	export default {
		data() {
			return {
				url:'',
			}
		},
		onReady() {
			console.log(this)
			var currentWebview = this.$scope.$getAppWebview() 
			console.log(currentWebview)
			        setTimeout(function() {
			            wv = currentWebview.children()[0]
			            wv.setStyle({top:150,height:300})
			        }, 1000); 
		},
		onLoad(e){
			this.url = 'http://www.chn-njtc.com/MC?NO=' + e.data
		},
		methods: {
			doBack(){
				uni.switchTab({
					url: '/pages/views/fds-pad/my/order'
				});
			},
		}
	}
</script>

<style>
	.to_back{
		border: 1px solid #dadada;
		width: 150px;
		height: 30px;
		border-radius: 15px;
		background-color: #dadada;
		text-align: center;
		font-size: 16px;
		line-height: 27px;
		margin: 0px 0px 0px 15px;
	}
	.content {
	        display: flex;
	        flex-direction: column;
	        align-items: center;
	        justify-content: center;
		}
		
	.tool-bar {
		color: #fff;
		position: fixed;
		bottom: 13%;
		right: 0rpx;
		width: 136rpx;
		height: 236rpx;
		border-radius: 8rpx;
		z-index: 999999;
	
	.nav-bg {
		width: 136rpx;
		height: 236rpx;
		position: absolute;
		left: 0;
		top: 0;
		z-index: 99999;
		border-radius: 8rpx;
	}
	
	.tool-btn {
		width:100rpx;
		height: 200rpx;
		position: absolute;
		top: 18rpx;
		left: 18rpx;
		display: flex;
		align-items: center;
		justify-content: center;
		flex-wrap: wrap;
	    }
	}

</style>
`


**报错信息：**
[system] TypeError: Cannot read property '$getAppWebview' of undefined
    at VueComponent.onReady (webView.vue:21)

**Comment by Manhoiii** [comment]
ios14的，安卓未测试
**这是我写vue文件：**
`<template>
	<view>
		<view class="content" style="width: 50%;height: 50%;">
			<view class="to_back" @tap="doBack" style="width: 60px; height: 60px; border-radius: 60px;">
				<text class="cuIcon-back" style="color: #FFFFFF;"></text>
			</view>
			<web-view v-if="url" :src="url"></web-view>
		</view>
		
	</view>
</template>

<script>
	var wv;
	export default {
		data() {
			return {
				url:'',
			}
		},
		onReady() {
			console.log(this)
			var currentWebview = this.$scope.$getAppWebview() 
			console.log(currentWebview)
			        setTimeout(function() {
			            wv = currentWebview.children()[0]
			            wv.setStyle({top:150,height:300})
			        }, 1000); 
		},
		onLoad(e){
			this.url = 'http://www.chn-njtc.com/MC?NO=' + e.data
		},
		methods: {
			doBack(){
				uni.switchTab({
					url: '/pages/views/fds-pad/my/order'
				});
			},
		}
	}
</script>

<style>
	.to_back{
		border: 1px solid #dadada;
		width: 150px;
		height: 30px;
		border-radius: 15px;
		background-color: #dadada;
		text-align: center;
		font-size: 16px;
		line-height: 27px;
		margin: 0px 0px 0px 15px;
	}
	.content {
	        display: flex;
	        flex-direction: column;
	        align-items: center;
	        justify-content: center;
		}
		
	.tool-bar {
		color: #fff;
		position: fixed;
		bottom: 13%;
		right: 0rpx;
		width: 136rpx;
		height: 236rpx;
		border-radius: 8rpx;
		z-index: 999999;
	
	.nav-bg {
		width: 136rpx;
		height: 236rpx;
		position: absolute;
		left: 0;
		top: 0;
		z-index: 99999;
		border-radius: 8rpx;
	}
	
	.tool-btn {
		width:100rpx;
		height: 200rpx;
		position: absolute;
		top: 18rpx;
		left: 18rpx;
		display: flex;
		align-items: center;
		justify-content: center;
		flex-wrap: wrap;
	    }
	}

</style>
`


**报错信息：**
[system] TypeError: Cannot read property '$getAppWebview' of undefined
    at VueComponent.onReady (webView.vue:21)

**Comment by StrivingRabbit** [comment]
使用你发的代码，运行没有问题呀，可以获取到。你使用的什么版本的HX？

**Comment by Manhoiii** [comment]
3.1.22

**Comment by StrivingRabbit** [comment]
3.1.22 到 3.2.3 应该是没有动过相关代码，不过你也可以升级下试试

**Comment by Manhoiii** [comment]
打印this后，发现连$scope都找不到，只有$scopedSlots。在$parent下也没有

**Comment by StrivingRabbit** [comment]
我也很好奇为什么你在 iOS App 中获取不到，提供一个可复现的 demo 测试一下

**Comment by Manhoiii** [comment]
最后发现是h5与app有些差异，目前已经解决啦，谢谢
