### ISSUE TITLE
Uni-app H5中页面返回时没调用onShow方法， 小程序正常，H5有问题

### ISSUE THREAD

**Issue by whoooami** [dcloudio/uni-app#2879]
**问题描述**
Uni-app H5中页面返回时没调用onShow方法， 小程序正常，H5有问题

**复现步骤**
H5
1.  进入A页面
2. 从A进入B页面
3. 直接点击返回到A页面，onShow方法没有执行。

[或者可以直接贴源代码]

**预期结果**
和小程序保持一致，执行

**实际结果**
H5未执行

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [Mac]
 - HBuilderX版本 [3.1.22
 - uni-app版本 [uni-app v2.9.3 uni-app cli v2.0.0-29320201014001]
 - 设备信息 [Mac chrome]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
cli  v2.0.0-29320201014001 项目 ？升级后试试，新版测试没有发现此问题

**Comment by whoooami** [comment]
> cli v2.0.0-29320201014001 项目 ？升级后试试，新版测试没有发现此问题

嗯，新版是正常的。感谢～
