### ISSUE TITLE
downloadFile方法携带header，在app里面丢失部分header

### ISSUE THREAD

**Issue by guoqi668** [dcloudio/uni-app#288]
![image](https://user-images.githubusercontent.com/23256656/55859726-3812d300-5ba5-11e9-87e1-9438882c5786.png)
以上代码，传递header 在小程序和h5里面，后端能接收到 header里的token test,在app里面接收不到

**Comment by hbcui1984** [comment]
升级HBuilderX 到最新的 1.9.0+，这个问题应该已解决，同类问题参考：https://ask.dcloud.net.cn/question/68260
