### ISSUE TITLE
pages.json 给页面设置zindex 在android 上导致页面栈混乱，页面栈回退还会变更添加时webview的层级

### ISSUE THREAD

**Issue by bluepeople1** [dcloudio/uni-app#2880]
**问题描述**
pages.json 给页面设置zindex 在android 上导致页面栈混乱，页面栈回退还会变更添加时webview的层级
pages.json 给页面设置zindex 在android 上导致页面栈混乱，页面栈回退还会变更添加时webview的层级，此问题在android 小程序sdk上跑uniapp wgt 有此问题。
按照H5+的plus.webview.WebViewStyle的说明，层级在添加页面时已经根据zindex和添加时间确定。Andoird返回键还会改变页面栈顺序。 IOS SDK不存在此问题

**复现步骤**
1、pages.json 给页面添加zindex
2、uni.navigateto 跳转3个页面
3、操作手机返回键，页面栈乱掉了

**预期结果**
逐层返回页面

**实际结果**
通过andorid studio layout inspector 发现页面显示顺序被调整了
通过getCurrentPages 发现栈顶上的页面和界面上展示的页面不是一个页面，页面栈乱了

**系统信息:**
 - 发行平台: uniapp sdk
 - 操作系统 android 10
 - HBuilderX版本 3.2.6.20210901-alpha
 - uni-app版本 3.2.6.20210901-alpha
 - 设备信息 华为mate30 pro

*

**Comment by zhetengbiji** [comment]
不建议手动设置 zindex ，设置后会使用设置的固定值。

另外手动设置 zindex 的原因是什么？
