### ISSUE TITLE
vue转的微信小程序,父组件用props传递改变父组件自身状态的函数给子组件调用无效

### ISSUE THREAD

**Issue by JokerSora** [dcloudio/uni-app#2881]
父组件里有函数
f(){
this.d="asdf"; //改变状态d
}
通过
<Child :f="f">传递
子组件里
props:{
f:Function //接收
}
methods:(){
useF(){
 this.f();//父组件的d状态不改变
}
}

但是通过 <Child @f="f" />
子组件通过this.$emit("f") 可以改变父组件d的状态

**Comment by StrivingRabbit** [comment]
不建议使用 props 传递 function，建议统一使用事件机制实现类似功能

不同平台底层支持度不一样
微信小程序，支持 props 传递对象属性为 function（不能直接传递 function），
比如 :p="obj"，obj.fn = function(){}
但是百度，头条是不支持传递 function 的。
