### ISSUE TITLE
nvue refresh标签下只放图片不会触发onrefresh

### ISSUE THREAD

**Issue by 1135065316** [dcloudio/uni-app#2883]
**问题描述**
nvue refresh标签下只放图片不会触发onrefresh,
根据文档描述, 把图片放到loading标签下也不生效,
只放文本就能触发onrefresh.

**复现步骤**

```
<swiper>
  <swiper-item>
    <list>
      <refresh @refresh='onrefresh'>
        <image src='xxx.png'></image>
      </refresh>
      <cell></cell>
    </list>
  </swiper-item>
</swiper>
```

**预期结果**
refresh下能放图

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 HarmonyOS 2.0.0
 - HBuilderX版本 3.2.3.20210825
 - 设备信息 HONOR X10

**Comment by 1135065316** [comment]
还有nvue组件源码 在dcloudio/uni-app没找到,是没有开源吗

**Comment by 1135065316** [comment]
还有list下面不包cell就不显示,是不是不太合理

**Comment by StrivingRabbit** [comment]
`@refresh='onrefresh'` 写在 image 上是不是加错地方了？

**Comment by 1135065316** [comment]
> `@refresh='onrefresh'` 写在 image 上是不是加错地方了？

是加在<refresh>上没有触发,报bug的时候写错了

**Comment by st-dc** [comment]
refresh 需要设置高度才可以 你可以对你添加的image设置一个高度
