### ISSUE TITLE
vue3版本下不支持v-model:[prop]

### ISSUE THREAD

**Issue by dnt1996** [dcloudio/uni-app#2884]
```vue
<template>
	<view class="content">
        <Foo v-model:a="title"></Foo>
    </view>
</template>
```

**编译结果**
```html
<view class="content">
    <foo bind:input="__e" vue-id="8dd740cc-1" modelValue="{{title}}"
         data-event-opts="{{[['^input',[['__set_model',['','title','$event',[]]]]]]}}" bind:__l="__l"></foo>
</view>
```

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 windows
 - uni-app版本 2.0.0-32220210818002

**Comment by fxy060608** [comment]
更新至最新的HBuilderX Alpha或 cli 最新版本

**Comment by TianbinTobin** [comment]
> 更新至最新的HBuilderX Alpha或 cli 最新版本

我已经升级到2.0.1-32920211122003版本了，这个问题还是存在，请问最新版本是指哪个版本？3.0.0的版本吗？

**Comment by fxy060608** [comment]
> > 更新至最新的HBuilderX Alpha或 cli 最新版本
> 
> 我已经升级到2.0.1-32920211122003版本了，这个问题还是存在，请问最新版本是指哪个版本？3.0.0的版本吗？

查看：https://ask.dcloud.net.cn/article/37834
重新创建cli工程：`npx degit dcloudio/uni-preset-vue#vite my-vue3-project`
小程序vue3已经更换为vite编译器，原有的webpack不再维护

**Comment by TianbinTobin** [comment]
> > > 更新至最新的HBuilderX Alpha或 cli 最新版本
> > 
> > 
> > 我已经升级到2.0.1-32920211122003版本了，这个问题还是存在，请问最新版本是指哪个版本？3.0.0的版本吗？
> 
> 查看：https://ask.dcloud.net.cn/article/37834 重新创建cli工程：`npx degit dcloudio/uni-preset-vue#vite my-vue3-project` 小程序vue3已经更换为vite编译器，原有的webpack不再维护

我已经重新创建了cli工程，但是原来引入的放到wxcomponents目录下已构建好的vant-weapp组件失效了，并且控制台提示 `无效的 app.json window["usingComponents"]` 目前还没找到原因

**Comment by fxy060608** [comment]
> wxcomponents

发一个测试工程

**Comment by TianbinTobin** [comment]
> 发一个测试工程

https://github.com/TianbinTobin/uni-vue3-test

**Comment by fxy060608** [comment]
> > 发一个测试工程
> 
> https://github.com/TianbinTobin/uni-vue3-test

已确认是有问题，建议单独发一个issue，方便跟踪

**Comment by fxy060608** [comment]
> > 已确认是有问题
> 
> 对比了一下之前2.0.0版本+webpack版本打包出来的的app.json ![image](https://user-images.githubusercontent.com/16282973/145990783-ab4271c0-497b-4a4c-bb2b-6037197bc777.png) 更新后vue3.0+vite版本打包出来的app.json ![image](https://user-images.githubusercontent.com/16282973/145990893-5de100de-2025-42d0-91b1-521bfce5d132.png) 结合提示`无效的 app.json window["usingComponents"]`可以看出问题应该是usingComponents引用的组件不应该放在window内部。

这只是其中一个问题，还有一些细节需要框架这里做处理
