### ISSUE TITLE
cli项目，自己开发的npm包，package.json引用本地路径包，uniapp微信小程序打包到node-modules外面去了

### ISSUE THREAD

**Issue by social-uni** [dcloudio/uni-app#2885]
package.json里面这么写的
```
 "socialuni": "file:socialuni",
```

打包效果成这样的了，socialuni是我的包，被打包到外面去了

![image](https://user-images.githubusercontent.com/14007972/132689266-b26ed792-2926-441b-8a33-f1aba7f068e2.png)

类似问题

https://ask.dcloud.net.cn/question/102374?item_id=173424&rf=false

**Comment by StrivingRabbit** [comment]
提供一个demo测试下

**Comment by StrivingRabbit** [comment]
由于长时间未回复，此issue关闭，如果还有问题可以重开或提新的issue
