### ISSUE TITLE
请问canvas画布如何使用isPointInPath这个API，uniapp的canvas直接只用会报not function

### ISSUE THREAD

**Issue by Boom-BO** [dcloudio/uni-app#2889]
请问canvas画布如何使用isPointInPath这个API
uniapp的canvas直接只用会报not function

![1631439072549](https://user-images.githubusercontent.com/22814819/132982541-8ba5f04f-f2d9-4df1-8980-b6bf2f64f214.jpg)
![1631439124779](https://user-images.githubusercontent.com/22814819/132982571-76633d5c-1629-4ced-bb62-937bbffc64eb.jpg)

**Comment by Boom-BO** [comment]
H5页面

**Comment by StrivingRabbit** [comment]
目前 `createCanvasContent` 不支持使用这个方法。在 H5 可以直接使用 getContext('2d')

**Comment by Boom-BO** [comment]
@StrivingRabbit getContext('2d') 这个在uniApp下会报错，好像必须用createCanvasContent才行呢？

**Comment by StrivingRabbit** [comment]
@Boom-BO  只有 H5 才可以使用 `getContext('2d')` ，其他平台还是要用 `createCanvasContent`
