### ISSUE TITLE
能否将manifest.json根据开发环境和生产环境不同配置

### ISSUE THREAD

**Issue by smoothdvd** [dcloudio/uni-app#2891]
**新功能描述**
能否将manifest.json根据开发环境和生产环境进行不同的配置？

**现状及问题**
开发微信小程序时，在开发环境下使用小程序测试帐号的appid；开发完成后，打包上传时需要手动设置为小程序正式帐号的appid，不太方便。

**Comment by StrivingRabbit** [comment]
暂不提供此类功能，使用正式账号测试会有什么问题吗？

**Comment by georgewei** [comment]
我们也遇到这个问题。

我们的项目至少会配置3个环境：开发环境、测试环境和生产环境。目前小程序的发布方式最多支持两个环境：体验版对应开发环境或测试环境，但不能兼顾；正式版对应生产环境。因此我们现在申请了两个小程序，一个专门用于开发环境，只发布体验版，不发布正式版；另一个用于测试环境和生产环境，在packge.json中区分，在HBuilder X的运行和发行菜单中可以选择。例如如下代码：

`{
  "uni-app": {
    "scripts": {
      "mp-weixin-test": {
        "title": "XX小程序(测试版)",
        "env": {
          "UNI_PLATFORM": "mp-weixin",
          "API_ROOT": "测试环境后端接口地址"
        },
        "define": {
          "MP-WEIXIN": true
        }
      },
      "mp-weixin-prod": {
        "title": "XX小程序(正式版)",
        "env": {
          "UNI_PLATFORM": "mp-weixin",
          "API_ROOT": "生产环境后端接口地址"
        },
        "define": {
          "MP-WEIXIN": true
        }
      }
    }
  }
}
`
这样从开发分支切换到测试分支或生产分支，或反过来，如果要发布，就得临时手工改一下小程序的appid，确实比较麻烦。

也许有人说可以在不同代码分支的manifest.json里写上不同的appid，但我们没有、也不建议这样做。我们的考虑是，确实不同分支的代码因为开发进度和稳定程度不同而有差异，但总体来说，当所有分支的开发进度一致（比如一个阶段完工）时，所有分支的代码应该是一致的，否则很容易在不同分支里埋下不同的逻辑，维护和理解困难。极端情况下，如果需要重建某个分支，该分支独有的代码可能意外丢失（开发人员可能根本不会想到两个分支的代码会有不同）。

基于以上情况，如果HBuilder X能根据不同的环境配置不同的appid，会方便很多。

**Comment by StrivingRabbit** [comment]
可以参考 https://uniapp.dcloud.io/collocation/vue-config 的实现

**Comment by TinsFox** [comment]
可以考虑使用node写个脚本进行修改文件？
