### ISSUE TITLE
小程序组件传参会把undefined转为null

### ISSUE THREAD

**Issue by lolPlatinumPlayer** [dcloudio/uni-app#2892]
**问题描述**
若组件A用了组件B，且组件A把一个值为undefined的data通过prop传给组件B
就会出现bug：组件A里是undefined，组件B里却是null

**系统信息:**
在微信开发者工具上发现的
 - 发行平台:  微信小程序
 - 操作系统 win10
 - HBuilderX版本 3.2.3.20210825
 - uni-app版本 最新
 - vue 2

**Comment by zhetengbiji** [comment]
小程序限制，data 不支持 undefined
