### ISSUE TITLE
小程序v-for迭代对象不全

### ISSUE THREAD

**Issue by lolPlatinumPlayer** [dcloudio/uni-app#2893]
**问题描述**
面对值为undefined的属性不会进行迭代

**系统信息:**
在微信开发者工具上发现的
 - 发行平台:  微信小程序
 - 操作系统 win10
 - HBuilderX版本 3.2.3.20210825
 - uni-app版本 最新
 - vue 2

**Comment by StrivingRabbit** [comment]
为什么要迭代 undefined 的值？需要迭代的值不应该为 undefined

**Comment by lolPlatinumPlayer** [comment]
> 为什么要迭代 undefined 的值？需要迭代的值不应该为 undefined

在其他端都会进行迭代，到小程序里却不会，而且没有任何提示或报错。碰到这情况会让开发者一头雾水，难以定位问题。

**Comment by zhetengbiji** [comment]
用法较罕见，暂不考虑特殊处理
