### ISSUE TITLE
小程序v-for对象，在新增对象属性后，标签上的属性渲染不正确

### ISSUE THREAD

**Issue by lolPlatinumPlayer** [dcloudio/uni-app#2894]
**问题描述**
这里说的属性不正确是包括ref的，这个很可怕

**复现步骤**
模板
```vue
    <ccc v-for="(c,k) in columnDict" :ref="'aaaaa'+k" :key="'saa'+k" :data-a="'aaaaa'+k">
      {{c}} {{k}}
      <div> {{'aaaaa'+k}} </div>
    </ccc>
``` 

新增属性的方法：`this.$set(this.columnDict,键值,null)`

**实际结果**
![企业微信截图_20210915202206](https://user-images.githubusercontent.com/30225536/133432635-6a4e7139-d60e-49af-83f1-b60b571b5279.png)
可以看到原本就有的属性渲染是正确的，第一个$set的属性也是正确的，但是后续$set的属性都是重复的（都会变得和第一个$set的一致）

**系统信息:**
在微信开发者工具上发现的
 - 发行平台:  微信小程序
 - 操作系统 win10
 - HBuilderX版本 3.2.3.20210825
 - uni-app版本 最新
 - vue 2

**Comment by StrivingRabbit** [comment]
1. 升级一下hx试试
2. 提供一个示例，并详细的描述一下你的问题所在，不是太能理解你的问题
