### ISSUE TITLE
hbuilderx最新版启动vue3项目有警告

### ISSUE THREAD

**Issue by wxs77577** [dcloudio/uni-app#2897]
Unrestricted file system access to "C:/soft/HBuilderX/plugins/uniapp-cli-vite/node_modules/@dcloudio/uni-h5/dist/uni-h5.es.js"
13:20:05.902 For security concerns, accessing files outside of serving allow list will be restricted by default in the future version of Vite. Refer to https://vitejs.dev/config/#server-fs-allow for more details.

![image](https://user-images.githubusercontent.com/1990059/133729111-5df1bf84-bfd0-4315-8bd8-6007e11748d4.png)

**Comment by StrivingRabbit** [comment]
升级至最新版试试
