### ISSUE TITLE
可以热更新吗

### ISSUE THREAD

**Issue by tigerleeli** [dcloudio/uni-app#29]
Hbuilder x 可以像Hbuilder 一样生成wgt 热更新吗

**Comment by junwei1114** [comment]
同问

**Comment by zhangfei28** [comment]
恩恩 这个可以有

**Comment by aiplat** [comment]
暂时没有吧

**Comment by xiaoyucoding** [comment]
HBuilderX 1.7.0 起支持热更新，详见：[uni-app 资源在线更新](https://ask.dcloud.net.cn/article/35667)
此问题关闭，如有其它问题请另行提交 issue 反馈。
