### ISSUE TITLE
手机选取图片后得到的是tempFilePaths ，如何得到图片的绝对路径

### ISSUE THREAD

**Issue by VincentHere** [dcloudio/uni-app#2900]
不管是使用uni.chooseImage()  ，还是plus.gallery.pick（）选取图片，得到的路径都不是绝对路径，如何才能拿到图片的绝对路径呢

**Comment by zhetengbiji** [comment]
使用 plus.io 进行转换
另外你要绝对路径做什么用途？

**Comment by leolelechina** [comment]
这个，操作系统不支持。win系统了解下FileSystemDirectoryReader.readEntries()
