### ISSUE TITLE
hbuilderx vue3 npm安装vuex-persistedstate之后报错

### ISSUE THREAD

**Issue by wxs77577** [dcloudio/uni-app#2904]
安装vuex-persistedstate会在node_modules下自动安装vue和vuex，然后启动就报错了，好像hb创建的uniapp项目就不能在项目内安装vue

**Comment by fxy060608** [comment]
测试未发现问题，请详细描述测试环境

**Comment by StrivingRabbit** [comment]
由于长时间未回复，此问题关闭，如果还有问题可以重提或开新的issue
