### ISSUE TITLE
swiper组件可自适应子组件高度

### ISSUE THREAD

**Issue by dwlinn** [dcloudio/uni-app#2905]
**新功能描述**
目前uniapp内置组件swiper不支持根据子组件高度自适应

**现状及问题**
使用uView组件库的tabsSwiper组件嵌套使用swiper,不能根据子元素高度进行自适应，而每一个tab内容都是长列表，高度是动态的，因此不能满足需求。

**尝试方案**
目前可通过社区回复设置样式打补丁fix这个问题，但使用仍然不方便。

**补充信息**
![image](https://user-images.githubusercontent.com/46804832/133885466-2368a02e-0a72-45cf-ae7a-cd720b1a76bf.png)
既然你们官方文档都提到了使用swiper做长列表的问题，那么我认为现在最大的问题不是性能问题，而是自适应高度这一步，就有很多开发者在社区提问。作为一个内置组件，不能支持大多数的使用场景，其实没有必要谈更复杂场景的性能问题。

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/2091
