### ISSUE TITLE
[APP]Js函数调用一半后中止执行返回，但没有任何异常

### ISSUE THREAD

**Issue by whoooami** [dcloudio/uni-app#2907]
**问题描述**
[APP] - Js函数执行一半后中止执行并返回，但没有任何异常

**复现步骤**
封装JS

        let native = {
            test: function() {
    	        //#ifdef APP-PLUS
                console.log("---- native test ----");
    	        const {platform} = uni.getSystemInfoSync()
    	        if (platform == 'android') {
    		        return android.test()
    	        } else if (platform == 'ios') {
    		        return ios.test()
    	        }
                // eval(platform + ".createEvent("+ data + ")");
                // [platform].createEvent.apply(this, data);
                console.log("==== native test ====");
    	        //#endif
            }
        };
        
        let android = {
            test: async function () {
                console.log("===1===");
    	        const it = await this.getIt()
                console.log("===2===");
            },
            getIt: async function() {
                console.log("android getIt");
    	        return new Promise((resolve) => {
    		        plus.runtime.getProperty(plus.runtime.appid, ({appid, name}) => {
    			        resolve({
    				        name,
    				        account_name: appid,
    				        account_type: CalendarContract.ACCOUNT_TYPE_LOCAL,
    				        display_name: name,
    			        })
    		        })
    	        })
            },
            
        };
        
        let ios = {
            test: async function () {
                console.log("===1===");
    	        const it = await this.getIt()
                console.log("===2===");
            },
            getIt: async function() {
                console.log("ios getIt");
            }
        };
        
        module.exports = {
            native
        }

调用JS

        import {native} from "@/common/native/test.js";
        native.test();

**预期结果**

        06:42:36.927  ---- native test ---- at common/native/test.js:4 
        06:42:36.950  ===1=== at common/native/test.js:42 
        06:42:37.004  ios getIt at common/native/test.js:47 
        06:42:37.004  ===2=== at common/native/test.js:44 

**实际结果**

        06:35:02.433 ---- native test ---- at common/native/test.js:4
        06:35:02.453 ===1=== at common/native/test.js:20
        06:35:02.474 android getIt at common/native/test.js:25
        后面的 ===2===没有执行

**系统信息:**
 - 发行平台: APP
 - 操作系统 iOS 13.3、Android 6.0.0
 - HBuilderX版本 3.2.3
 - uni-app版本 
         uni-app v3.2.2
        uni-app cli v2.0.0-32220210818002
        
        Environment Info:
        
          System:
            OS: macOS Sierra 10.12.6
            CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
          Binaries:
            Node: 12.0.0 - ~/.nvm/versions/node/v12.0.0/bin/node
            Yarn: Not Found
            npm: 6.9.0 - ~/.nvm/versions/node/v12.0.0/bin/npm
          Browsers:
            Chrome: 93.0.4577.82
            Firefox: Not Found
            Safari: 12.1
          npmPackages:
            @dcloudio/types: ^2.5.8 => 2.5.8 
            @dcloudio/uni-app-plus: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/uni-app-plus-nvue:  0.0.1 
            @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
            @dcloudio/uni-automator: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/uni-cli-shared: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/uni-h5: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/uni-helper-json: ^1.0.13 => 1.0.13 
            @dcloudio/uni-migration: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/uni-mp-360: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/uni-mp-alipay: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/uni-mp-baidu: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/uni-mp-qq: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/uni-mp-toutiao: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/uni-mp-vue: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/uni-mp-weixin: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/uni-quickapp-native: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/uni-quickapp-webview: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/uni-stat: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/uni-template-compiler: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/vue-cli-plugin-uni: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/webpack-uni-mp-loader: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @dcloudio/webpack-uni-nvue-loader:  0.0.1 
            @dcloudio/webpack-uni-pages-loader: ^2.0.0-32320210825 => 2.0.0-32220210818002 
            @hap-toolkit/dsl-vue:  0.6.13 
            @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
            @vue/babel-helper-vue-transform-on:  1.0.2 
            @vue/babel-plugin-jsx:  1.0.7 
            @vue/babel-plugin-transform-vue-jsx:  1.2.1 
            @vue/babel-preset-app:  4.5.13 
            @vue/babel-preset-jsx:  1.2.4 
            @vue/babel-sugar-composition-api-inject-h:  1.2.1 
            @vue/babel-sugar-composition-api-render-instance:  1.2.4 
            @vue/babel-sugar-functional-vue:  1.2.2 
            @vue/babel-sugar-inject-h:  1.2.2 
            @vue/babel-sugar-v-model:  1.2.3 
            @vue/babel-sugar-v-on:  1.2.3 
            @vue/cli-overlay:  4.5.13 
            @vue/cli-plugin-babel: ^4.5.13 => 4.5.13 
            @vue/cli-plugin-router:  4.5.13 
            @vue/cli-plugin-vuex:  4.5.13 
            @vue/cli-service: ^4.5.13 => 4.5.13 
            @vue/cli-shared-utils:  4.5.13 
            @vue/component-compiler-utils:  3.2.2 (3.2.2)
            @vue/devtools-api:  6.0.0-beta.15 
            @vue/preload-webpack-plugin:  1.1.2 
            @vue/shared: ^3.2.11 => 3.2.11 
            @vue/web-component-wrapper:  1.3.0 
            mpvue-page-factory:  1.0.1 
            mpvue-template-compiler:  1.0.13 
            uni-h5-vue:  2.6.10 
            uni-mp-vue:  2.6.10 
            vue: ^2.6.14 => 2.6.14 
            vue-hot-reload-api:  2.3.4 
            vue-i18n: 8.25.0 => 8.25.0 
            vue-loader:  15.9.8 (16.5.0, 15.9.8)
            vue-router:  3.0.1 
            vue-style-loader:  4.1.3 (4.1.3)
            vue-template-compiler: ^2.6.14 => 2.6.14 (2.6.14)
            vue-template-es2015-compiler:  1.9.1 
            vuex: ^3.6.2 => 3.6.2 (3.6.2)
          npmGlobalPackages:
            @vue/cli: 4.5.6

 - 设备信息 iOS 13.3、Android 6.0.0

**补充信息**
如果把里面的promise {plus.runtime}块注释掉，就可以打印出 ===2===，有没有可能是 Promise 或者是 plus.runtime 的执行问题？

**Comment by whoooami** [comment]
补充一下： 如果把里面的plus.runtime块注释掉，就可以打印出 ===2===，是 plus.runtime 的执行问题？

**Comment by zhetengbiji** [comment]
各种对比测试，自己先排查一下。

**Comment by whoooami** [comment]
> 各种对比测试，自己先排查一下。

对比测试？不好意思，没太明白。其实是因为调试了好久没找到原因，但注释了plus函数段又正常了，所以才想着来问一下？

**Comment by zhetengbiji** [comment]
> > 各种对比测试，自己先排查一下。
> 
> 对比测试？不好意思，没太明白。其实是因为调试了好久没找到原因，但注释了plus函数段又正常了，所以才想着来问一下？

plus.runtime.getProperty的回调是否正常触发？

**Comment by whoooami** [comment]
> > > 各种对比测试，自己先排查一下。
> > 
> > 
> > 对比测试？不好意思，没太明白。其实是因为调试了好久没找到原因，但注释了plus函数段又正常了，所以才想着来问一下？
> 
> 比如plus.runtime.getProperty的回调是否正常触发？

回调正常触发的

**Comment by unique-vv** [comment]
CalendarContract未定义

**Comment by whoooami** [comment]
感谢大神，果然是一个低级错误
