### ISSUE TITLE
快应用  @dcloudio/uni-quickapp-webview 通过uni转换后。代码执行qa.accountAuthorize获取权限报错

### ISSUE THREAD

**Issue by zhudaqian** [dcloudio/uni-app#2908]
**问题描述**
小程序转换成快应用调用获取openId报错，快应用创建的demo没有问题

**复现步骤**
[复现问题的步骤]

      qa.accountAuthorize({
        type:'token',
        success: function(res){
          qa.showModal({
            content:JSON.stringify(res.accessToken)+'success'
          })
        },
        fail: function(res){
          qa.showModal({
            content:JSON.stringify(res)+'fail'
          })
        },
      })
    } catch (error) {
      qa.showModal({
        content:JSON.stringify(error)+'error'
      })
    }

**预期结果**
正确获取到id

**实际结果**

![Screenshot_20210917_192235](https://user-images.githubusercontent.com/17560273/134297551-fceabb47-a22f-44df-8fb9-c68fdc71d036.jpg)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhudaqian** [comment]
https://qapp-chimera.vivo.com.cn/framework/open-ability/account.html#%E5%AE%A2%E6%88%B7%E7%AB%AF-2

**Comment by dcloudhdx** [comment]
检查 manifest.json 中是否有配置 appid
