### ISSUE TITLE
cli版本，用webstrom无法预加载webpack配置

### ISSUE THREAD

**Issue by wyc987350759** [dcloudio/uni-app#2909]
**问题描述**
win10，webstrom版本2020.2.3及以上，最近npm完之后webstrom无法正常识别项目的webpack配置，导致webstrom中大部分功能瘫痪，源码追溯了一下，第一个是@vue/cli-service版本4.5.0在uniapp-cli版本中有问题，会报错'Service must call init() before calling resolveWebpackConfig().'，只要升级到最新版正常；第二个问题是node_modules\@dcloudio\vue-cli-plugin-uni\lib\env.js文件报错，第二十七行‘process.env.UNI_PLATFORM’不被webstrom识别，代码改为“process.env.UNI_PLATFORM && process.env.UNI_PLATFORM.indexOf('mp-') === 0”即正常。

**预期结果**
第一个问题本地升级就可以解决，但第二个问题建议改一下，不会影响你们原有逻辑，只是加了个强校验，让webstrom能走下去，不然每次本地都要手动修改node_modules

**Comment by wyc987350759** [comment]
有人提了和我差不多的问题，只不过他是vscode，我是webstrom，https://github.com/dcloudio/uni-app/pull/2848

**Comment by ModyQyW** [comment]
@wyc987350759 可以先手动修复一下源码，然后用 [patch-package](https://github.com/ds300/patch-package) 记录修复。

**Comment by dnt1996** [comment]
可以用tsconfig.json配置别名
创建global.d.ts来声明全局变量和env

**Comment by StrivingRabbit** [comment]
提一个pr吧

**Comment by ModyQyW** [comment]
已经合并发布，2.0.0-alpha-32820210924001
