### ISSUE TITLE
vue3 页面生命周期钩子的一些bug

### ISSUE THREAD

**Issue by dnt1996** [dcloudio/uni-app#2914]
- onShareAppMessage在页面中调用无效
- onShow, onHide 在自定义组件中调用无效
- @dcloudio/uni-app没有导出onLoad钩子

"@dcloudio/uni-app": "3.0.0-alpha-3020820210923001"
"@dcloudio/uni-mp-vue": "2.0.0-alpha-32820210923001"

[复现代码](https://github.com/dnt1996/uni-app-vue3-test/tree/life-cycle-hook-bug)

**Comment by fxy060608** [comment]
1. onShareAppMessage 目前只支持使用options方式定义，包括onShareTimeline也一样，因为这些配置会影响右上角菜单的显示。如果要支持在setup中使用，需要框架在每个页面都提前定义好这些生命周期。
2. 下个版本，onShow,onHide会支持再组件中使用
3. 预期的设计是在setup中通过props接收页面参数，无需使用onLoad，目前h5,app平台已支持，小程序稍后考虑支持。

**Comment by molvqingtai** [comment]
> 
经测试，HbuildX 创建的App项目，已设置启动阐述， props 并没有值

**Comment by fxy060608** [comment]
> > 
> 
> 经测试，HbuilderX 创建的App项目，已设置启动参数， props 并没有值
1. @dcloudio/uni-app 已经导出 onLoad 
2. 页面 setup 接收 props，使用 HBuilderX Alpha 3.3.0 测试没有问题，如果有问题，贴代码

**Comment by molvqingtai** [comment]
所以必须使用 HBuilderX Alpha 创建项目吗？
HbuilderX: 3.2.16.20211122

page.json
```json
{
  "pages": [
    //pages数组中第一项表示应用启动页，参考：https://uniapp.dcloud.io/collocation/pages
    {
      "path": "pages/index/index",
      "style": {
        "navigationBarTitleText": "uni-app"
      }
    }
  ],
  "globalStyle": {
    "navigationBarTextStyle": "black",
    "navigationBarTitleText": "uni-app",
    "navigationBarBackgroundColor": "#F8F8F8",
    "backgroundColor": "#F8F8F8"
  },
  "condition" : { //模式配置，仅开发期间生效
    "current": 0, //当前激活的模式(list 的索引项)
    "list": [
      {
        "name": "index", //模式名称
        "path": "pages/index/index", //启动页面，必选
        "query": "foo=123" //启动参数，在页面的onLoad函数里面得到
      }
    ]
  }
}

index.vue
```typescript
export default defineComponent({
  name: 'IndexPage',
  setup(props, ctx) {
    console.log('props', props)
  }
})
```

**Comment by fxy060608** [comment]
> 所以必须使用 HBuilderX Alpha 创建项目吗？ HbuilderX: 3.2.16.20211122
> 
> page.json
> 
> ```json
> {
>   "pages": [
>     //pages数组中第一项表示应用启动页，参考：https://uniapp.dcloud.io/collocation/pages
>     {
>       "path": "pages/index/index",
>       "style": {
>         "navigationBarTitleText": "uni-app"
>       }
>     }
>   ],
>   "globalStyle": {
>     "navigationBarTextStyle": "black",
>     "navigationBarTitleText": "uni-app",
>     "navigationBarBackgroundColor": "#F8F8F8",
>     "backgroundColor": "#F8F8F8"
>   },
>   "condition" : { //模式配置，仅开发期间生效
>     "current": 0, //当前激活的模式(list 的索引项)
>     "list": [
>       {
>         "name": "index", //模式名称
>         "path": "pages/index/index", //启动页面，必选
>         "query": "foo=123" //启动参数，在页面的onLoad函数里面得到
>       }
>     ]
>   }
> }
> ```
> 
> index.vue
> 
> ```js
> export default defineComponent({
>   name: 'IndexPage',
>   setup(props, ctx) {
>     console.log('props', props)
>   }
> })
> ```
> 
> log
> 
> ```shell
> 17:01:58.276 App Launch at App.vue:4
> 17:01:58.299 App Show at App.vue:7
> 17:01:58.746 props, [Object] {}  at pages/index/index.vue:48
> ```

这个是 模拟直达页面 的bug，你可以使用 navigateTo 自己跳转传参测试
