### ISSUE TITLE
cli 创建的项目使用import没法引入echarts

### ISSUE THREAD

**Issue by AndwareSsj** [dcloudio/uni-app#292]
**问题描述**
使用cli创建的项目，无法import echarts.js 成功

**Comment by zhetengbiji** [comment]
标准echart仅能用于h5，跨端请使用改良的uchart或f2，插件市场有：https://ext.dcloud.net.cn/search?q=%E5%9B%BE%E8%A1%A8。hello uni-app里也有echart示例，注意如果在部分平台报错的话，使用hello uni-app里面的js（如果自己引用其他版本报错的，参考hello uni-app里面的修改一下）
