### ISSUE TITLE
hbx3.2.9 开启分包字节小程序组件使用作用域插槽报错（because they are in different packages）

### ISSUE THREAD

**Issue by joker-omg** [dcloudio/uni-app#2923]
HBuildX3.2.9版本开启分包后，字节小程序页面中使用公共组件并且使用作用域插槽报错because they are in different packages
![image](https://user-images.githubusercontent.com/43290681/135272927-df3ed358-2006-463e-8749-2cece09f5887.png)

**Comment by wuxushun** [comment]
同样的错误

**Comment by zhetengbiji** [comment]
后续版本已提供相关配置用于优化作用域插槽渲染 [scopedSlotsCompiler](https://uniapp.dcloud.net.cn/collocation/manifest.html#mp-toutiao)
