### ISSUE TITLE
page.json 中 condition > current 修改无效

### ISSUE THREAD

**Issue by bradliu** [dcloudio/uni-app#293]
**问题描述**
总是优先生效第一项，当前需要手动调整 list 顺序  

#8 Solution: HBuilder 已经是最新版了

**复现步骤**
```
"condition": { //模式配置，仅开发期间生效
	"current": 1, //当前激活的模式(list 的索引项)
	"list": [{
		"name": "dev", //模式名称 
		"path": "pages/discovery/main" //启动页面，必选
	},
	{
		"name": "prod", //模式名称
		"path": "pages/index/main" //启动页面，必选
	}]
}
```

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本: 1.8.2.20190401

**Comment by xiaoyucoding** [comment]
看了一下编译后生成代码，project.config.json 里面的配置与源码里面是一致的。
并且主动修改 `condition->miniprogram->current` 的值，也不会主动切换过去。
可能是小程序开发工具，本身对于这个 condition 有缓存等策略导致的。
