### ISSUE TITLE
Vue Cli 创建的项目更新到2.0.0-32920210927002之后无法打包和运行

### ISSUE THREAD

**Issue by mick-sun** [dcloudio/uni-app#2935]
**问题描述**
更新到最新版本之后（2.0.0-32920210927002）Vue Cli 创建的项目无法打包和运行，控制台无报错信息，控制台信息如下：
```bash 
yarn run v1.22.10
$ npm run build:app-plus

> wenerhui-app@0.1.0 build:app-plus
> cross-env NODE_ENV=production UNI_PLATFORM=app-plus vue-cli-service uni-build

编译器版本：3.2.9（v3）看：https://ask.dcloud.net.cn/article/36599。
✨  Done in 3.29s.
```

![image](https://user-images.githubusercontent.com/62009061/135861055-a118ffe9-b050-4faf-8fc5-d3644f2440bb.png)

**Comment by huadong** [comment]
碰到同样问题。

**Comment by huadong** [comment]
同时增加@dcloudio/uni-cli-i18n和@dcloudio/uni-i18n可以正常编译。
yarn add -D @dcloudio/uni-cli-i18n @dcloudio/uni-i18n

**Comment by zhetengbiji** [comment]
已发布版本管理工具 [@dcloudio/uvm](https://www.npmjs.com/package/@dcloudio/uvm)
