### ISSUE TITLE
vue3下的vite编译：uni.scss无效

### ISSUE THREAD

**Issue by sessionboy** [dcloudio/uni-app#2938]
**问题描述**
创建了uni-app，默认模板
vue版本选择3，基于vite的编译

我想要定制主题，但是修改uni.scss没有任何效果，uni.scss无效。

文档里说过uni.scss是由webpack处理的，但我现在用的是vite编译。翻了源码，没有发现相关的vite插件，估计你们没有处理这个问题。

另外内置组件和uni-ui组件，很多样式是写死的，尤其是color和background-color。如果改为统一从uni.scss读取变量，也就不需要webpack或vite来处理了，更方便主题定制。

希望文档多一些vite的例子和说明。

**系统信息:**
 - 电脑： mac pro
 - 发行平台:  app
 - 操作系统 iOS 13
 - HBuilderX版本 : 3.2.9
 - uni-app版本 最新
 - 设备信息 iPhone7

**Comment by sessionboy** [comment]
嗨，这个问题什么时候能解决？vue3为啥不支持webpack编译

**Comment by fxy060608** [comment]
最新HBuilderX alpha及cli 均以支持uni.scss
vue3 统一使用 vite 编译，不再提供 webpack 支持
