### ISSUE TITLE
vue3版本app中vite编译器使用import.meta.glob报错，不能正常使用

### ISSUE THREAD

**Issue by dengqichang** [dcloudio/uni-app#2944]
**问题描述**
vue3版本app中vite编译器使用import.meta.glob报错不能正常使用。然而在vue3版本H5中vite编译器使用import.meta.glob正常使用。
vite官方文档中是支持的，https://cn.vitejs.dev/guide/features.html#glob-import

**复现步骤**
```
let index = import.meta.glob('../index/*.vue');  
for (let i in index) {  
    console.log(i)  
};
```
vue3 vite编译器app编译结果即复现

**预期结果**
vue3 vite编译器下app与h5均可使用import.meta.glob

**实际结果**
vue3 vite编译器下app 使用报错，不能正常使用。  
vue3 vite编译器下h5 使用正常。

**系统信息:**
 - 发行平台: App
 - 操作系统  所有测试手机
 - HBuilderX版本  3.2.9

**Comment by fxy060608** [comment]
请更新至3.2.10以上版本测试

**Comment by wangchunling** [comment]
> 请更新至3.2.10以上版本测试

想问下，如果使用cli的模式开发的，这个问题如何修复呢，相关依赖包版本为： "3.0.0-4010520240507001"
