### ISSUE TITLE
启动项目突然报了这个错？arr[Symbol.iterator] is not a function

### ISSUE THREAD

**Issue by zfy108** [dcloudio/uni-app#295]
![image](https://user-images.githubusercontent.com/20158770/56094234-a4bf0200-5f04-11e9-9399-cdb62ab14ede.png)

**Comment by lincenying** [comment]
刚试了下, 也一样, 目测是 uni的api 不支持 promise 了

**Comment by RWBDante** [comment]
我也遇到了，这接口说改就改么，不对说都没说

**Comment by xiaoyucoding** [comment]
[关于 1.9.0 调用 API 返回 Promise 对象不正确的临时解决方案](https://ask.dcloud.net.cn/article/35837)

**Comment by RWBDante** [comment]
没有解决H5端的问题

**Comment by xiaoyucoding** [comment]
> 没有解决H5端的问题

已补充，请重新下载帖子中的附件。

**Comment by qibao7** [comment]
昨天我也遇到了，async await封装请求 就一直报这个错误

**Comment by RWBDante** [comment]
今天更新到1.9.1 H5端又该出现问题

**Comment by onlyshow** [comment]
<img width="1176" alt="WX20190416-145110@2x" src="https://user-images.githubusercontent.com/12505832/56188110-2de64e00-6057-11e9-8cf9-6f13167af833.png">
<img width="313" alt="WX20190416-145237@2x" src="https://user-images.githubusercontent.com/12505832/56188158-4e160d00-6057-11e9-85f7-56c69d9fcff1.png">
maxos mojave 10.14.4 (18E226)

**Comment by ansuisgod** [comment]
你们都用这个开发项目了才遇到这么多问题，只有你们不断的发现问题我们后面用才不会有这么的坑舍，你们还要继续去试坑。

**Comment by ansuisgod** [comment]
我们以前的公司也是这样，上个版本的bug都修复了，然后这个版本又发现了这个bug，没想到这样的大公司也会遇到这样bug。不知道他们是怎么控制版本的，感觉他们天天都在修复bug但是bug还是多，就应了这一句话，天下没有修复的完的bug。

**Comment by xiaoyucoding** [comment]
1.9.2 已修复此问题，请更新 HBuilderX 或 cli 项目的依赖。
