### ISSUE TITLE
[bug report]navigateTo fail locked

### ISSUE THREAD

**Issue by stwbadz** [dcloudio/uni-app#2951]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
errMsg: navigateTo:fail /pages/xxx/xxx. locked

当用户在性能较差的安卓机型快速双击能够切换页面的按钮，会在新页面弹出上述白色modal弹窗。

**复现步骤**
[复现问题的步骤]
1.  启动 性能较差的安卓机型，打开任意项目
2. 快速连按写了navigateto的按钮，或者快速连续点击底tab  
3. 查看新页面的modal报错

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
没有modal框报错

**实际结果**
[这里请贴上你的报错截图或文字]
出现modal框报错
https://ask.dcloud.net.cn/question/126767?item_id=176936&rf=false
https://ask.dcloud.net.cn/question/112453
有大量这种反馈的帖子无人处理

![20211023-171426](https://user-images.githubusercontent.com/8508854/138550908-28536c2b-3a7b-461f-88c2-84763bfd1931.jpeg)

**系统信息:**
 - 发行平台: 安卓app
 - 操作系统 小米最新系统版本
 - HBuilderX版本 3.2.11.20211021-alpha
 - uni-app版本 3.2.11
 - 设备信息 红米6

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

某个版本的uniapp研发在调试跳转方法时，为了方便看log，把console.error写成了showModal。
打包提交代码时忘记删掉测试代码。导致必现这个bug

**Comment by blacklike** [comment]
目前还有这个问题，请问是怎么处理的？
