### ISSUE TITLE
多个input间切换时，无法聚焦，需要再次点击才能获得焦点

### ISSUE THREAD

**Issue by llk2yq** [dcloudio/uni-app#2954]
**问题描述**

页面内有多个input时，从一个input切换到另一个input时，极大概率无法获得焦点，且键盘会一闪而过无法唤起。需要再次点击
输入框才能获取焦点继续输入。

**复现步骤**
如描述
[dcloud社区有相同的提问，提供了视频](https://ask.dcloud.net.cn/question/131936)

**预期结果**
切换input表现正常。

**实际结果**
切换input无法获取焦点

**系统信息:**
 - 发行平台:：微信小程序
 - 操作系统： 安卓11
 - HBuilderX版本： 3.2.11.20211021-alpha
 - uni-app版本：未知
 - 设备信息：一加8t

**补充信息**
无

**Comment by berial** [comment]
android版本也会出现这个问题
