### ISSUE TITLE
vue3 使用swiper轮播组件直接报错

### ISSUE THREAD

**Issue by cll123456** [dcloudio/uni-app#2957]
**问题描述**
vue3 在支付宝小程序中使用swiper 组件项目直接启动不了

![image](https://user-images.githubusercontent.com/41314419/139030603-ae57f477-3cdf-4fcb-a95b-4282af2ef714.png)

**复现步骤**
[复现问题的步骤]

```js
	<swiper indicator-dots="true" autoplay="true" circular class="swiper--container">
			<swiper-item style="background-color: #007AFF;">第一张</swiper-item>
			<swiper-item style="background-color:#4CD964;">第二章</swiper-item>
			<swiper-item style="background-color: #ABCDEF;">第三章</swiper-item>
		</swiper>
```

**预期结果**
应该和h5一样，可以直接使用轮播组件
![image](https://user-images.githubusercontent.com/41314419/139031115-f26a6132-3798-4ccc-a0e9-5176f4dfdafb.png)

**实际结果**
项目直接启动不了
![image](https://user-images.githubusercontent.com/41314419/139031321-3cbcc1d2-bf12-49f9-bde8-0f702e1d8bd5.png)

**系统信息:**
 - 发行平台: [支付宝小程序]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [3.2.9]
 - 设备信息 [支付宝小程序开发工具]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
未重现该问题，升级HBuilderX Alpha至3.3.0
