### ISSUE TITLE
vue3 icon 和 unicon 在微信小程序和支付宝小程序都不行

### ISSUE THREAD

**Issue by cll123456** [dcloudio/uni-app#2958]
**问题描述**
vue3 icon 和 unicon 在微信小程序和支付宝小程序都不行
![image](https://user-images.githubusercontent.com/41314419/139033733-6ef1d075-b7a5-48ba-bf4d-cef441a55750.png)
![image](https://user-images.githubusercontent.com/41314419/139038320-8c032e7a-5a4a-4a0f-8d8f-ec11b102b152.png)

**复现步骤**
```js

<view class="icons--container">
			<block v-for="(item,index) in iconsArr" :key="index">
				<uni-icons :type="item" size="24" ></uni-icons>
			</block>
			<block class="item" v-for="(value,index) in iconType" :key="index">
				<icon :type="value" size="20"  />
			</block>
		</view>


<script setup>
	import {
		ref
	} from 'vue';

	const iconsArr = ref(['camera', 'home', 'plus-filled', 'search', 'clear']);

	const iconType = ref(['success', 'success_no_circle', 'info', 'warn', 'waiting', 'cancel', 'download', 'search',
		'clear'
	])
</script>
```

**预期结果**
和h5一样，能够正常显示
![image](https://user-images.githubusercontent.com/41314419/139038627-83b2cc95-231b-4740-945f-d4d338bd53d5.png)

**实际结果**
![image](https://user-images.githubusercontent.com/41314419/139033733-6ef1d075-b7a5-48ba-bf4d-cef441a55750.png)
![image](https://user-images.githubusercontent.com/41314419/139038320-8c032e7a-5a4a-4a0f-8d8f-ec11b102b152.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、支付宝小程序]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [3.2.9]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [开发者工具，chrome浏览器]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
小程序编译平台没有正常编译

**Comment by mehaotian** [comment]
提供一下你的 字体文件和用法 demo

**Comment by cll123456** [comment]
一个是uniapp自带的icon,另一个是uni-incons

**Comment by mehaotian** [comment]
> 一个是uniapp自带的icon,另一个是uni-incons

换成这中写法试一试

```html
<script>
	import {
		ref,
		defineComponent
	} from 'vue';
	export default defineComponent({
		data() {},
		props: {},
		setup(props, ctx) {
			const iconsArr = ref(['camera', 'home', 'plus-filled', 'search', 'clear']);

			const iconType = ref(['success', 'success_no_circle', 'info', 'warn', 'waiting', 'cancel', 'download',
				'search',
				'clear'
			])

			return {
				iconsArr,
				iconType
			}
		}
	})
</script>
```

**Comment by cll123456** [comment]
好的，我上面那种语法啥时候支持呢

**Comment by mehaotian** [comment]
> 好的，我上面那种语法啥时候支持呢

下个小程序 的vite版本就会支持
