### ISSUE TITLE
APP端 uni.reLaunch直接退出

### ISSUE THREAD

**Issue by RWBDante** [dcloudio/uni-app#296]
**问题描述**
uni.reLaunch({
                    url: '/pages/login/login'
                });

调用后APP直接退出

HBuilder 1.9版本使用新编译模式有这个问题

在APP.vue里 onLaunch 里 reLaunch页面报如下错误:

18:26:47.367 App Launch__LOG
18:26:47.388 appServiceSDKScriptError
18:26:47.408 r.setStyle is not a function. (In 'r.setStyle(t)', 'r.setStyle' is undefined); at uni.reLaunch
18:26:47.429 ae@(global function):7:14017
18:26:47.449 mn@(global function):7:32824
18:26:47.470 Nn@(global function):7:76986
18:26:47.490 (global function):8:844
18:26:47.511 invoke@(global function):8:889
18:26:47.531 invoke@(global function):8:105643
18:26:47.552 X@(global function):8:163217
18:26:47.572 (global function):8:170670
18:26:47.592 Lc@(global function):8:320619
18:26:47.613 (global function):8:211062
18:26:47.633 (global function):8:417931
18:26:47.653 (global function):8:417973
18:26:47.673 (global function):8:174603
18:26:47.693 (global function):1950:16
18:26:47.714 Nt@(weex framework):1:14826
18:26:47.735 promiseApi@(global function):1949:37
18:26:47.755 onLaunch@(global function):1453:34
18:26:47.776 invokeWithErrorHandling@(global function):4644:31
18:26:47.797 __call_hook@(global function):8451:46
18:26:47.817 onLaunch@(global function):2535:27
18:26:47.838 (global function):8:646769
18:26:47.880 e@(global function):8:647596
18:26:47.899 (global function):8:647786
18:26:47.919 (global function):8:637118
18:26:47.940 createApp@(global function):2549:6
18:26:47.960 (global function):11499:10
18:26:47.981 D:\workspace\front-ops-mobile-b\main.js@(global function):11500:34
18:26:48.002 __webpack_require__@(global function):1664:35
18:26:48.023 checkDeferredModules@(global function):1621:45
18:26:48.044 (global function):1438:61
18:26:48.064 require@(global function):8:671701
18:26:48.085 (global function):8:671316
18:26:48.105 (global function):11827:8
18:26:48.126 require@(global function):8:671701
18:26:48.147 (global function):11829:8
18:26:48.168 anonymous@(global function):14234:7
18:26:48.188 (weex framework):1:41074
18:26:48.209 createInstance@(weex framework):1:41085
18:26:48.231 (weex framework):1:177648__ERROR
18:26:48.250 App Show__LOG

**Comment by mehaotian** [comment]
尽量不要在 onLaunch 的生命周期去调用页面跳转的相关api ，这个时候，可能页面还没准备好，去跳转会有问题。

**Comment by RWBDante** [comment]
不光是onLaunch 生命周期的问题，在页面完全启动的情况下，调用uni.reLaunch APP会直接隐藏到后台

**Comment by mehaotian** [comment]
方便提供一下具体的平台信息，已经手机信息么？最好的话可以附带一个简单的 demo 。方便我们去定位问题。

**Comment by RWBDante** [comment]
我刚才试了一下 在mounted周期里跳转也会报相同的错误，这里总要提供一个能在APP启动期间跳转页面的解决方案吧

**Comment by RWBDante** [comment]
项目相关信息稍后给你，可能会有些晚。我在相同的手机上使用 hello uni 的demo跳转没有问题

**Comment by mehaotian** [comment]
如果想要在 app 启动期间去跳转页面，你应该在首页，如 index.vue 的 onload 生命周期去做跳转。如果这样还是不行的话，我建议还是给我一个demo，看是不是哪里写法有问题。

**Comment by RWBDante** [comment]
我这里在跳转的时候 又有一条报错:
10:03:50.232  Uncaught TypeError: Cannot read property 'evalJS' of undefined at __uniapppicker.html:9

**Comment by RWBDante** [comment]
我在首页的onLoad里跳转报错:
10:07:41.115 reLaunch:fail page "pages/operation/pages/login/login" is not found__ERROR
10:07:42.527  Uncaught TypeError: Cannot read property 'evalJS' of undefined at __uniapppicker.html:9

**Comment by mehaotian** [comment]
明显的路径错误啊
```javascript
// 错误
uni.reLaunch({
	url:'pages/detail/detail'
})

// 正确
uni.reLaunch({
	url:'/pages/detail/detail'
})
```

**Comment by RWBDante** [comment]
首页这里  ./pages/login/login  我多加了个  “ . ”   是我复制过来的错误,我改了下没有问题了，但是我登录页面：
                       uni.reLaunch({
                           url:'/page/operation/index'
                       })
这样写 就会找不到页面：
11:36:48.005 reLaunch:fail page "page/operation/index" is not found__ERROR

只能这样写:
uni.reLaunch({
        url:'../operation/index'
})
这样就没有问题

并且我在组件里的跳转:
uni.reLaunch({
        url: '/pages/login/login'
});

APP就会直接跳出到后台

**Comment by RWBDante** [comment]
这个API 太乱了 ，都把我搞晕了

**Comment by mehaotian** [comment]
并没有复现到 你说的这个问题 ，贴一下你完整的代码 。我看看

**Comment by RWBDante** [comment]
找个时间 给个demo你把

**Comment by RWBDante** [comment]
[uniapp-test.zip](https://github.com/dcloudio/uni-app/files/3089199/uniapp-test.zip)

已上传demo 请解压然后先看 里面的readme

**Comment by dcloudhdx** [comment]
bug已确认，下版修复，临时解决方案在pages.json中配置 "tabBar": {}

**Comment by RWBDante** [comment]
感谢，烦请尽快更新版本，因为业务需求原因需自定义tabbar

**Comment by dcloudhdx** [comment]
HBuilderX 1.9.3已修复
