### ISSUE TITLE
1.9更新后组件里的watch不起作用

### ISSUE THREAD

**Issue by RWBDante** [dcloudio/uni-app#297]
更新后1.9版本后,APP,小程序端里组件的watch不起作用

组件使用的 v-model 传递的prop watch不起作用
只能使用 v-bind

**Comment by mehaotian** [comment]
麻烦，给你具体示例，或者demo 。

**Comment by githublyp** [comment]
目前微信小程序是不行的，watch:{
userInfo:{
    handler(){
      console.log(12121);
    },
    immediate: true,
    deep: true
}
}
动态改变数据之后无法应

**Comment by fxy060608** [comment]
> watch:{
> userInfo:{
> handler(){
> console.log(12121);
> },
> immediate: true,
> deep: true
> }
> }

测试未发现问题，请贴一下详细代码

**Comment by githublyp** [comment]
<template>
  <div>
    <div @tap="add">新增</div>
    <div>{{myData.images.length}}</div>
    <div @tap="del">删除</div>
  </div>
</template>

<script>
  export default {
    name: "test",
    props: {
      propData: Object
    },
    data() {
      return {
        myData: {
          images: []
        }
      }
    },
    watch: {
      propData: {
        handler() {
          this.myData = Object.assign({}, this.myData, this.propData)
        },
        immediate: true,
        deep: true
      }
    },
    methods: {
      del: function () {
        this.$emit('del', this.myData)
      },
      add: function () {
        this.myData.images.push({
          src: '122'
        })
        this.$emit('add', this.myData)
      }
    }
  }
</script>

<style>

</style>
父组件更新propData.images=[]时子组件无反应

**Comment by bacy** [comment]
我使用v-model也出现问题
 watch: {
      value(val) {
        this.dialogShow = val
      },
      dialogShow(val) {
        this.$emit('input', val)
      }
    },
代码大概是这么写的，并未生效

**Comment by Wangyaqi** [comment]
长时间未回复，暂时关闭
