### ISSUE TITLE
小程序端 使用composition-api 获取ref 报错提示tProperty or method "toJSON" is not defined on the instance but referenced during render

### ISSUE THREAD

**Issue by zhangchenna** [dcloudio/uni-app#2979]
```
<template>
  <view>
    <form-grid ref="formGridRef" />
  </view>
</template>

<script>
import { defineComponent, onMounted, ref } from '@vue/composition-api';
import FormGrid from './core/form-grid';

export default defineComponent({
  name: 'qt-form',

  components: {
    FormGrid,
  },

  setup() {
    const formGridRef = ref(null);

    onMounted(() => {
      console.log(formGridRef.value);
    });

    return {
      formGridRef,
    };
  },
});
</script>

```
通过这种方式获取refs 可以拿到 但是微信小程序端提示 

[Vue warn]: Property or method "toJSON" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property. See: https://vuejs.org/v2/guide/reactivity.html#Declaring-Reactive-Properties.

**Comment by zhangchenna** [comment]
`import { defineComponent, onMounted, ref } from '@vue/composition-api';
import { cloneDeep } from 'lodash-es';
import FormGrid from './core/form-grid';

export default defineComponent({
  name: 'qt-form',

  components: {
    FormGrid,
  },

  setup(props, { refs }) {
    const formGridRef = ref(null);

    onMounted(() => {
      console.log(formGridRef.value);
      console.log(refs.formGridRef.$vm);
    });

    return {
      formGridRef: cloneDeep(formGridRef),
    };
  },
});`

**Comment by zhangchenna** [comment]
```
import { defineComponent, onMounted, ref } from '@vue/composition-api';
import { cloneDeep } from 'lodash-es';
import FormGrid from './core/form-grid';

export default defineComponent({
  name: 'qt-form',

  components: {
    FormGrid,
  },

  setup() {
    const formGridRef = ref(null);
    const asd = cloneDeep(formGridRef);

    onMounted(() => {
      console.log(asd.value);
    });

    return {
      formGridRef: asd,
    };
  },
});
```

小程序循环引用造成的报错 深拷贝之后可以解决

**Comment by sufuWang** [comment]
```html
<template>
  <view v-if="isDisplayRecords">
    <Records ref="refRecords" />
  </view>
  <view v-if="isDisplayToolset">
    <Toolset />
  </view>
  <view v-if="isDisplayMessage">
    <Message />
  </view>
  <view v-if="isDisplayMine">
    <Mine />
  </view>
</template>
```
使用 composition-api ref 调用子组件方法，在切换组件时，依然报这个错误，大佬知道这是什么问题吗？

**Comment by zhangchenna** [comment]
> ```
> <template>
>   <view v-if="isDisplayRecords">
>     <Records ref="refRecords" />
>   </view>
>   <view v-if="isDisplayToolset">
>     <Toolset />
>   </view>
>   <view v-if="isDisplayMessage">
>     <Message />
>   </view>
>   <view v-if="isDisplayMine">
>     <Mine />
>   </view>
> </template>
> ```
> 
> 使用 composition-api ref 调用子组件方法，在切换组件时，依然报这个错误，大佬知道这是什么问题吗？

**Comment by zhangchenna** [comment]
不清楚你这种的问题我还没有遇到 遇到我会反馈在这里
