### ISSUE TITLE
vue3H5项目中v-if的错误渲染

### ISSUE THREAD

**Issue by welove42** [dcloudio/uni-app#2984]
**问题描述**
vue3 H5项目中通过v-if="变量"来条件渲染页面时，第一次切换正常，第二次发生错误

**复现步骤**
`<view class="" v-if="isLogin">
			组件
		</view> `
`<button @click="changeForm">按钮</button>`

`data() {
			return {
			isLogin:true
			}
		},`
`methods: {
		changeForm() {
			this.isLogin = !this.isLogin
		},
		},`

**预期结果**
预期通过button点击事件来显示和隐藏组件

**实际结果**
第一次显示隐藏正常，再次操作就发生错误
![image](https://user-images.githubusercontent.com/77881340/141235931-1f7e2ff0-6c0a-4495-8681-8d2f8311f9a8.png)
![image](https://user-images.githubusercontent.com/77881340/141236035-a3c12410-c3c1-44a0-a352-1464b0c9ffd3.png)

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 win10
 - HBuilderX版本 3.2.12

**补充信息**
编译成微信小程序没有这种问题，正常vue3项目也没有这样的bug

**Comment by fxy060608** [comment]
未重现此问题，可以发一个完整的测试工程

**Comment by welove42** [comment]
弄明白了，是我给组件加了个ref，然后组件双向绑定的变量用reactive创建的，变量名跟ref的值一样出的bug😂
