### ISSUE TITLE
hbuilderx 是否考虑开源

### ISSUE THREAD

**Issue by TinsFox** [dcloudio/uni-app#2986]
**新功能描述**

hbuilderx 编辑器是否考虑开源

**现状及问题**
编辑器还是存在许多可以优化的地方，但是官方团队对此的步伐似乎是不紧，那么是否考虑过开源交由社区一起共建。

**Comment by zhangchenna** [comment]
不喜欢可以用 vscode  你不怕apicloud抄过去啊

**Comment by zhetengbiji** [comment]
编辑器一直在改进，具体问题可以到社区反馈。
