### ISSUE TITLE
web-view 本地页面初始化完成后 无法聚焦某一个input

### ISSUE THREAD

**Issue by huoshidehua** [dcloudio/uni-app#2989]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
web-view 本地页面(同样使用vue 开发)初始化完成后
在vue mounted中定位某个input 类似 this.$refs.input.select()
发现没有效果
**复现步骤**
[复现问题的步骤]
1. web-view 页面mounted中使用this.$refs.input.select()无效

[或者可以直接贴源代码]
mounted(){
					this.$nextTick(() => {
						this.form = {};
						this.$refs.locationName.$refs.input.select();
						
					})

				},

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
预期效果是 能够将input 选中

**实际结果**
[这里请贴上你的报错截图或文字]
无效

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by huoshidehua** [comment]
没人回答？只能自己研究了
在vue 页面 创建web-view的时候 使用api 创建 不用元素标签创建
this.wv = plus.webview.create( "/hybrid/html/xxx.html", "xxx", {
				top:uni.getSystemInfoSync().statusBarHeight+44 ,//放置在titleNView下方。如果还想在webview上方加个地址栏的什么的，可以继续降低TOP值
				zindex:10000
			}, {baseUrl:baseUrl,token:token} );
let currentWebview = this.$scope.$getAppWebview()
			currentWebview.append(this.wv);
最关键的一步：文档是什么也没说
plus.webview.show(this.wv)  // 这里必须show 一下 有点类似激活了

**Comment by huoshidehua** [comment]
目前是这样的解决方案  不知道会不会有什么bug 之类的问题

**Comment by pea-cake** [comment]
不错，赞一个

**Comment by Xujalg** [comment]
但这样 不能直接输入吧 虽然光标选中了
