### ISSUE TITLE
1.9版本 APP端 onWindowResize在键盘弹出的情况下不触发

### ISSUE THREAD

**Issue by RWBDante** [dcloudio/uni-app#299]
如题

**Comment by mehaotian** [comment]
在键盘弹出的时候，安卓机器是上推页面，并不会压缩页面，这个时候宽高并没有变化，ios 是要手动设置是否压缩页面。这个时候 onWindowResize 不会触发。

**Comment by RWBDante** [comment]
webview的高度是有变化的啊，页面的样式依然会因此改变

**Comment by mehaotian** [comment]
是安卓 还是ios ？

**Comment by RWBDante** [comment]
安卓

**Comment by mehaotian** [comment]
你说的 webview的高度是有变化的啊，页面的样式依然会因此改变 ，是怎么得出这个结论来的？

**Comment by RWBDante** [comment]
就是键盘弹出 webview的高度变化，我的底部fixed的元素被顶起 但是这个时候 不触发onWindowResize

**Comment by mehaotian** [comment]
好的，我排查一下

**Comment by mehaotian** [comment]
该问题是在自定义组件模式还是非自定义组件模式下？ 还是都有问题？

**Comment by RWBDante** [comment]
自定义组件模式 模式下 非自定义组件模式好像没这个问题

**Comment by mehaotian** [comment]
刚才确认了一下，是自定义组件模式下暂时还不支持onWindowResize ，之后会支持 。

**Comment by mehaotian** [comment]
HBuilderX 1.9.6 Alpha 版发布，已修复该问题。

Alpha版本说明及下载地址参考：https://ask.dcloud.net.cn/article/35765
