### ISSUE TITLE
@vue/cli 创建项目 请求出错

### ISSUE THREAD

**Issue by xyz-fish** [dcloudio/uni-app#2994]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

vue create -p dcloudio/uni-preset-vue my-project 创建项目报错

**复现步骤**
1.  npm install -g @/vue/cli
2. vue create -p dcloudio/uni-preset-vue my-project
3. Failed fetching remote preset dcloudio/uni-preset-vue:
    RequestError: read ECONNRESET  
   ClientRequest.<anonymous>(/Users/.nvm/versions/node/v16.3.0/lib/node_modules/@vue/cli/node_modules/got/index.js:182:22

@vue/cli 版本是4.5.15
node 版本是16.3

**预期结果**

**实际结果**

**系统信息:**
 - mac

**补充信息**
版本问题吗 还是什么

**Comment by WindrunnerMax** [comment]
网络问题吧，建议科学上网

**Comment by zhetengbiji** [comment]
从报错看是网络问题，如无条件，也可以尝试切换不同运营商网络
