### ISSUE TITLE
uniapp开发飞书小程序中的没有openSchema的功能

### ISSUE THREAD

**Issue by checkwoodson** [dcloudio/uni-app#2995]
**新功能描述**
简洁描述你希望补充完善的增强功能
飞书小程序中自带了一个openSchema的功能，是可以直接跳转到浏览器中。但是uniapp好像是没有跳转的 我猜测好像都是跳转的小程序内置的路由
**现状及问题**
[当前现状及由此导致的不便]
希望是能适配Pc端的直接打开浏览器进行地址跳转等功能，或者是打开新的小程序的功能。
**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by Otto-J** [comment]
特定平台的 api 可以使用条件编译来完成。可参考https://ask.dcloud.net.cn/article/40766
