### ISSUE TITLE
使用HbuilderX创建的例子接口和模版页面全部打不开报错

### ISSUE THREAD

**Issue by zengqingsong** [dcloudio/uni-app#3]
21:36:52.155  App Launch at App.vue:4
21:36:52.175  App Show at App.vue:37
21:36:59.987  Do not have handler in current page: pages/API/API. Please make sure that handler has been defined in pages/API/API, or not use handler with 'v-if'
21:37:05.416  success at App.vue:19
21:43:44.963  Do not have handler in current page: pages/API/API. Please make sure that handler has been defined in pages/API/API, or not use handler with 'v-if'

**Comment by wanganxp** [comment]
目前版本在Android4上有兼容问题，下版会修复。
