### ISSUE TITLE
Android app 升级，出现两个app，老版本不被覆盖？有什么解决办法？

### ISSUE THREAD

**Issue by viplife108** [dcloudio/uni-app#300]

**Comment by zxzhgk** [comment]
包名和版本号一致么

**Comment by zfy108** [comment]
为啥版本号改了  就不能覆盖原来的了？
应用版本名称 和 应用版本号有啥区别？
![image](https://user-images.githubusercontent.com/20158770/56212154-08c00280-608c-11e9-9642-2ab5e978f587.png)

**Comment by onlyshow** [comment]
- 包名一致
- 签名一致
- versionCode 大于当前安装

**Comment by hbcui1984** [comment]
应该是两次打包的`Android包名`不同导致的，升级的话，版本号应该不同。
