### ISSUE TITLE
小程序何时升级vite编译器

### ISSUE THREAD

**Issue by fangshikeji** [dcloudio/uni-app#3000]
请问小程序何时升级vite编译器？

**Comment by fxy060608** [comment]
cli已经支持，HBuilderX下个 alpha 版本（预计v3.2.15）支持

**Comment by sufuWang** [comment]
请问 cli 如何选择使用 vite 进行编译呀

**Comment by fxy060608** [comment]
> 请问 cli 如何选择使用 vite 进行编译呀
替换更新自己的 package.json，然后安装
```json
{
  "scripts": {
    "dev:app": "uni -p app",
    "dev:h5": "uni",
    "dev:h5:ssr": "uni --ssr",
    "dev:mp-alipay": "uni -p mp-alipay",
    "dev:mp-baidu": "uni -p mp-baidu",
    "dev:mp-kuaishou": "uni -p mp-kuaishou",
    "dev:mp-lark": "uni -p mp-lark",
    "dev:mp-qq": "uni -p mp-qq",
    "dev:mp-toutiao": "uni -p mp-toutiao",
    "dev:mp-weixin": "uni -p mp-weixin",
    "dev:quickapp-webview": "uni -p quickapp-webview",
    "dev:quickapp-webview-huawei": "uni -p quickapp-webview-huawei",
    "dev:quickapp-webview-union": "uni -p quickapp-webview-union",
    "build:app": "uni build -p app",
    "build:h5": "uni build",
    "build:h5:ssr": "uni build --ssr",
    "build:mp-alipay": "uni build -p mp-alipay",
    "build:mp-baidu": "uni build -p mp-baidu",
    "build:mp-kuaishou": "uni build -p mp-kuaishou",
    "build:mp-lark": "uni build -p mp-lark",
    "build:mp-qq": "uni build -p mp-qq",
    "build:mp-toutiao": "uni build -p mp-toutiao",
    "build:mp-weixin": "uni build -p mp-weixin",
    "build:quickapp-webview": "uni build -p quickapp-webview",
    "build:quickapp-webview-huawei": "uni build -p quickapp-webview-huawei",
    "build:quickapp-webview-union": "uni build -p quickapp-webview-union"
  },
  "dependencies": {
    "@dcloudio/uni-app": "^3.0.0-alpha-3021320211117003",
    "@dcloudio/uni-app-plus": "^3.0.0-alpha-3021320211117003",
    "@dcloudio/uni-h5": "^3.0.0-alpha-3021320211117003",
    "@dcloudio/uni-mp-alipay": "^3.0.0-alpha-3021320211117003",
    "@dcloudio/uni-mp-baidu": "^3.0.0-alpha-3021320211117003",
    "@dcloudio/uni-mp-kuaishou": "^3.0.0-alpha-3021320211117003",
    "@dcloudio/uni-mp-lark": "^3.0.0-alpha-3021320211117003",
    "@dcloudio/uni-mp-qq": "^3.0.0-alpha-3021320211117003",
    "@dcloudio/uni-mp-toutiao": "^3.0.0-alpha-3021320211117003",
    "@dcloudio/uni-mp-weixin": "^3.0.0-alpha-3021320211117003",
    "@dcloudio/uni-quickapp-webview": "^3.0.0-alpha-3021320211117003",
    "vue": "^3.2.22",
    "vue-i18n": "^9.1.7",
    "vuex": "^4.0.2"
  },
  "devDependencies": {
    "@dcloudio/types": "^2.5.13",
    "@dcloudio/uni-automator": "^3.0.0-alpha-3021320211117003",
    "@dcloudio/uni-cli-shared": "^3.0.0-alpha-3021320211117003",
    "@dcloudio/vite-plugin-uni": "^3.0.0-alpha-3021320211117003",
    "autoprefixer": "^10.4.0",
    "vite": "^2.6.14"
  }
}

```

**Comment by sufuWang** [comment]
@fxy060608 请问有 webpack 改造到 vite 的分支嘛？想看下整体的改造方法。感觉替换之后还有许多坑要走

**Comment by sufuWang** [comment]
![image](https://user-images.githubusercontent.com/46395105/142335525-afdf33f3-a54f-47f0-9ea4-2c305016fc1e.png)
dev:mp-weixin 和 dev:h5 的打包结果怎么一样呀？

**Comment by fxy060608** [comment]
> ![image](https://user-images.githubusercontent.com/46395105/142335525-afdf33f3-a54f-47f0-9ea4-2c305016fc1e.png) dev:mp-weixin 和 dev:h5 的打包结果怎么一样呀？

确保package.json中dependencies，devDependencies与上边发的一致

**Comment by sufuWang** [comment]
> > ![image](https://user-images.githubusercontent.com/46395105/142335525-afdf33f3-a54f-47f0-9ea4-2c305016fc1e.png) dev:mp-weixin 和 dev:h5 的打包结果怎么一样呀？
> 
> 确保package.json中dependencies，devDependencies与上边发的一致


大佬这个是我的项目地址：https://github.com/sufuWang/uniapp_vite
使用 cli 起一个 vue3 项目，然后用你的 package.json 代替，打包出来不对，是我配置的原因吗

**Comment by fxy060608** [comment]
> > > ![image](https://user-images.githubusercontent.com/46395105/142335525-afdf33f3-a54f-47f0-9ea4-2c305016fc1e.png) dev:mp-weixin 和 dev:h5 的打包结果怎么一样呀？
> > 
> > 
> > 确保package.json中dependencies，devDependencies与上边发的一致
> 
> 大佬这个是我的项目地址：https://github.com/sufuWang/uniapp_vite 使用 cli 起一个 vue3 项目，然后用你的 package.json 代替，打包出来不对，是我配置的原因吗

你这个项目原来的webpack的吧，
缺少内容，比如vite.config.js,
postcss.config.js也不对，
建议重新创建一个vite项目：`npx degit dcloudio/uni-preset-vue#vite my-vue3-project `
然后把你老项目里的 src 覆盖进去即可

**Comment by sufuWang** [comment]
> > > > ![image](https://user-images.githubusercontent.com/46395105/142335525-afdf33f3-a54f-47f0-9ea4-2c305016fc1e.png) dev:mp-weixin 和 dev:h5 的打包结果怎么一样呀？
> > > 
> > > 
> > > 确保package.json中dependencies，devDependencies与上边发的一致
> > 
> > 
> > 大佬这个是我的项目地址：https://github.com/sufuWang/uniapp_vite 使用 cli 起一个 vue3 项目，然后用你的 package.json 代替，打包出来不对，是我配置的原因吗
> 
> 你这个项目原来的webpack的吧， 缺少内容，比如vite.config.js, postcss.config.js也不对， 建议重新创建一个vite项目：`npx degit dcloudio/uni-preset-vue#vite my-vue3-project ` 然后把你老项目里的 src 覆盖进去即可

大佬，已经解决问题了，感谢
还想问一下 `npx degit dcloudio/uni-preset-vue#vite my-vue3-project` 怎么新建一个 vite & ts 项目？官方文档中有提到这个命令吗？没有找到呀

**Comment by fxy060608** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/46395105/142335525-afdf33f3-a54f-47f0-9ea4-2c305016fc1e.png) dev:mp-weixin 和 dev:h5 的打包结果怎么一样呀？
> > > > 
> > > > 
> > > > 确保package.json中dependencies，devDependencies与上边发的一致
> > > 
> > > 
> > > 大佬这个是我的项目地址：https://github.com/sufuWang/uniapp_vite 使用 cli 起一个 vue3 项目，然后用你的 package.json 代替，打包出来不对，是我配置的原因吗
> > 
> > 
> > 你这个项目原来的webpack的吧， 缺少内容，比如vite.config.js, postcss.config.js也不对， 建议重新创建一个vite项目：`npx degit dcloudio/uni-preset-vue#vite my-vue3-project ` 然后把你老项目里的 src 覆盖进去即可
> 
> 大佬，已经解决问题了，感谢 还想问一下 `npx degit dcloudio/uni-preset-vue#vite my-vue3-project` 怎么新建一个 vite & ts 项目？官方文档中有提到这个命令吗？没有找到呀

目前暂未提供ts模板，跟普通vue3的ts项目差异不大，把原本的main.js调整成main.ts

**Comment by sufuWang** [comment]
> 目前暂未提供ts模板，跟普通vue3的ts项目差异不大，把原本的main.js调整成main.ts
![image](https://user-images.githubusercontent.com/46395105/142370691-9eed2be8-f946-416e-90d5-e35f471c5268.png)
是要改 vite 的配置吗？

**Comment by sufuWang** [comment]
![image](https://user-images.githubusercontent.com/46395105/142557471-661838d2-76ae-4f63-ba01-2b164ce10ef8.png)
vite 虽然可以打包成功，但语法有点问题，打包文件还引入了项目不存在的 npm 包，～*～

**Comment by fxy060608** [comment]
> ![image](https://user-images.githubusercontent.com/46395105/142557471-661838d2-76ae-4f63-ba01-2b164ce10ef8.png) vite 虽然可以打包成功，但语法有点问题，打包文件还引入了项目不存在的 npm 包，～*～

可以直接贴原始代码，描述编译后，运行不正确的现象，对比vite和webpack的代码意义不大

**Comment by sufuWang** [comment]
```html
<view v-for="(n, i) in nodes" v-bind:key="i">
  // ···
  <trees v-else :class="(n.attrs.id||'')+' _'+n.name+' '+(n.attrs.class||'')" :c="(n.attrs.id||'')+' _'+n.name+' '+(n.attrs.class||'')"
    :style="n.attrs.style" :s="n.attrs.style" :nodes="n.children" :lazyLoad="lazyLoad" :loading="loading" />
</view>
```
是这样一个结构

**Comment by fxy060608** [comment]
> ```
> <view v-for="(n, i) in nodes" v-bind:key="i">
>   // ···
>   <trees v-else :class="(n.attrs.id||'')+' _'+n.name+' '+(n.attrs.class||'')" :c="(n.attrs.id||'')+' _'+n.name+' '+(n.attrs.class||'')"
>     :style="n.attrs.style" :s="n.attrs.style" :nodes="n.children" :lazyLoad="lazyLoad" :loading="loading" />
> </view>
> ```
> 
> 是这样一个结构 不支持` <block>` 嘛？原本代码是` <block v-for="(n, i) in nodes" v-bind:key="i">`

你的问题就是block节点，变成了view节点吗？

**Comment by sufuWang** [comment]
![image](https://user-images.githubusercontent.com/46395105/142559136-7db2f738-8360-4068-99c2-49633aa9f3e5.png)

**Comment by fxy060608** [comment]
把 trees.vue 

> crypto

最好发一个可以重现该问题的简单项目

**Comment by sufuWang** [comment]
报语法错误这个问题，在这个项目中可以实现 https://github.com/sufuWang/uniapp_vite
crypto 这个包的问题，应该用 @rollup/plugin-commonjs 可以解决

**Comment by fxy060608** [comment]
> crypto

1. 语法错误的已经修复，稍后发版
2. crypto 的问题可以发个测试工程
3. rollup 插件，是在 vite.config.js 中配置

**Comment by sufuWang** [comment]
> 1. 语法错误的已经修复，稍后发版
> 2. crypto 的问题可以发个测试工程
> 3. rollup 插件，是在 vite.config.js 中配置

tql

![image](https://user-images.githubusercontent.com/46395105/142577026-d04f69f3-20bc-4b56-926a-8cb342e0b5ff.png)
大佬这个问题，应该怎么处理呀，源码中 `url('iconfont.svg')` 来引入同目录下的 svg 文件，报这个错误

**Comment by fxy060608** [comment]
> > 1. 语法错误的已经修复，稍后发版
> > 2. crypto 的问题可以发个测试工程
> > 3. rollup 插件，是在 vite.config.js 中配置
> 
> tql
> 
> ![image](https://user-images.githubusercontent.com/46395105/142577026-d04f69f3-20bc-4b56-926a-8cb342e0b5ff.png) 大佬这个问题，应该怎么处理呀，源码中 `url('iconfont.svg')` 来引入同目录下的 svg 文件，报这个错误

报错误，建议尽量给全信息，比如贴出详细代码，运行到哪个平台出的错误

**Comment by sufuWang** [comment]
>  ![image](https://user-images.githubusercontent.com/46395105/142577026-d04f69f3-20bc-4b56-926a-8cb342e0b5ff.png) 大佬这个问题，应该怎么处理呀，源码中 `url('iconfont.svg')` 来引入同目录下的 svg 文件，报这个错误

![image](https://user-images.githubusercontent.com/46395105/142584792-587a086f-8c6f-4e28-b9ed-ff1862250390.png)
less 文件中通过 url 引入 svg 文件，报上图这个错误，微信小程序端。把 url 中的地址改为绝对地址就可以编译通过

**Comment by ahjsrhj** [comment]
构建完成之后，小程序端没有process变量，一些环境判断无法进行
然后vite dev与build两种构建模式都开放了--mode选项自定义env文件，但是uni dev构建没有--mode选项，请问这个能开放么？
这样就可以不用依赖process变量改用import.meta.env进行处理

**Comment by ahjsrhj** [comment]
![image](https://user-images.githubusercontent.com/8666955/142607464-74eea4b2-e4fd-46cf-8070-d0f2b354133e.png)

**Comment by fangshikeji** [comment]
> cli已经支持，HBuilderX下个 alpha 版本（预计v3.2.15）支持
并没有支持，下个 alpha 版本会支持吗

**Comment by fxy060608** [comment]
> > cli已经支持，HBuilderX下个 alpha 版本（预计v3.2.15）支持
> > 并没有支持，下个 alpha 版本会支持吗

之前发了一次紧急更新，预计 alpha （v3.2.17）支持

**Comment by fxy060608** [comment]
HBuilderX Alpha 3.3.0 已支持
