### ISSUE TITLE
vue3  boundingClientRect 返回值为空

### ISSUE THREAD

**Issue by Haloxylon** [dcloudio/uni-app#3002]
**问题描述**
微信小程序 vue2 uni.createSelectorQuery().in(this)， boundingClientRect获取的数据是正常的；但是改成vue3之后，uni.createSelectorQuery().in()  is not function， 而不绑定in  boundingClientRect获取的数据为空。

**复现步骤**
setup() {} 中

const element = uni.createSelectorQuery();
element
.selectAll('.xxxxx')
.boundingClientRect((data) => {
	console.log(data)
})
.exec();

**Comment by zhanhongtao** [comment]
@Haloxylon  用 getCurrentInstance 方法.  ex: `.in(getCurrentInstance().ctx)`
