### ISSUE TITLE
uni.showActionSheet 如何修改取消按钮的文案

### ISSUE THREAD

**Issue by QianYS** [dcloudio/uni-app#3005]
**问题描述**
uni.showActionSheet 组件中点击打开的弹窗的取消按钮为英文的cancel

**复现步骤**
开发的小程序中
uni.showActionSheet 组件中点击打开的弹窗的取消按钮为英文的cancel

[或者可以直接贴源代码]

**预期结果**
可以修改这个默认的组件的提示文字

**实际结果**
可以修改这个默认的组件的提示文字

**Comment by StrivingRabbit** [comment]
目前不支持修改

**Comment by dcloudhdx** [comment]
3.1.5 起支持框架国际化，详情 [https://uniapp.dcloud.net.cn/tutorial/i18n.html](https://uniapp.dcloud.net.cn/tutorial/i18n.html)
