### ISSUE TITLE
使用vite-plugin-uni自定义vite.config.js后，渲染出来的dom结构出现差异

### ISSUE THREAD

**Issue by aloha66** [dcloudio/uni-app#3007]
**问题描述**

自定义vite.config.js，h5出现dom结构差异，导致图片无法加载出来

**复现步骤**
1.  yarn add -D vite-plugin-uni
2. 发现自动安装的版本是3.0.0-alpha-3000020210521001,然后发现各种module缺失
3. 在[#3000](https://github.com/dcloudio/uni-app/issues/3000#issuecomment-971318831)的提示下，发现可用版本3.0.0-alpha-3021320211117003

```ts
//  vite.config.ts
import { defineConfig } from 'vite'
import uni from '@dcloudio/vite-plugin-uni'

export default defineConfig({
  plugins: [
    uni(),
  ],
})

```

**预期结果**
没有用vite-plugin-uni的时候dom结构
![image](https://user-images.githubusercontent.com/20942781/142575973-0b51a1be-4dd8-46d9-b691-e10ea9359162.png)

**实际结果**
用了vite-plugin-uni的dom结构
![image](https://user-images.githubusercontent.com/20942781/142576112-27106ed8-3227-44af-bcea-04cb0f37d622.png)

**系统信息:**
 - 发行平台: H5
 - 操作系统 win10
 - HBuilderX版本 HBuilderX.3.2.12.20211029，HBuilderX.3.2.14.20211112-alpha
 - 浏览器：chrome96.0.4664.45

**补充信息**
顺便问一下两个问题
1. 这个倒退的版本号我没搞懂
2. 看了其他issue，小程序现在应该还不支持用tsx文件吧？

**Comment by fxy060608** [comment]
建议重新创建工程：`npx degit dcloudio/uni-preset-vue#vite my-vue3-project`
然后把你的src覆盖进去

**Comment by aloha66** [comment]
> 建议重新创建工程：`npx degit dcloudio/uni-preset-vue#vite my-vue3-project` 然后把你的src覆盖进去

could not find commit hash for vite 是我网络问题吗？我卡住了,[改下载这个可以吗？](https://github.com/dcloudio/uni-preset-vue/tree/master/template/default-ts)

**Comment by aloha66** [comment]
可以了
