### ISSUE TITLE
vite构建的小程序项目 使用 style module时 编译报错 Cannot find module 'postcss-modules'

### ISSUE THREAD

**Issue by Iongtao** [dcloudio/uni-app#3008]
**问题描述**
vite构建的小程序项目 使用 style module时 编译报错 Cannot find module 'postcss-modules'

**复现步骤**
[复现问题的步骤]
使用 vite创建项目 安装依赖后 使用style module特性 运行yarn dev:mp-weixin 编译错误
代码：
![image](https://user-images.githubusercontent.com/24762616/142718647-e1287fd6-c72f-4774-9663-d099630ec317.png)
错误代码：
![image](https://user-images.githubusercontent.com/24762616/142718653-90c6e525-c932-4d44-a471-e08471b9c105.png)

**预期结果**
编译正常

**实际结果**
编译错误 
Cannot find module 'postcss-modules'

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 window11
 - HBuilderX版本 无
 - uni-app版本 vite编译器
 - 
![image](https://user-images.githubusercontent.com/24762616/142718715-a56fc278-c484-4d1c-847b-e5c4a57eef52.png)
![image](https://user-images.githubusercontent.com/24762616/142718717-3bd85cb2-2c95-40b0-a408-3be8109331ff.png)

 - 设备信息 微信小程序模拟器

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Iongtao** [comment]
我安装了postcss-modules后 出现了另一个问题
![image](https://user-images.githubusercontent.com/24762616/142719147-c665f1f8-d1c2-4a5d-b09f-a08fdff6bfd3.png)
请问这是什么原因

**Comment by Iongtao** [comment]
style vars特性也无法使用 但是看是源码上是已经有相关实现 不知道为什么会出现这样的错误
![image](https://user-images.githubusercontent.com/24762616/142719776-60743760-88ed-4094-9842-5e070564892e.png)

**Comment by fxy060608** [comment]
这两个特性暂时还没有做跨平台支持

**Comment by Iongtao** [comment]
> 这两个特性暂时还没有做跨平台支持

好的 等待支持

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/2959
