### ISSUE TITLE
求求你们加强对TS的支持吧

### ISSUE THREAD

**Issue by Iongtao** [dcloudio/uni-app#3009]
**新功能描述**
很多api的ts支持真的好差啊 虽然说vue3比vue2时候好了一些吧 但还是好差

**现状及问题**
![image](https://user-images.githubusercontent.com/24762616/142722512-065892eb-4403-420f-a6a2-be256b9f886c.png)
文档注释是这样的
![image](https://user-images.githubusercontent.com/24762616/142722530-dc6a7902-f15d-4375-a44f-c356e898a9de.png)
request请求也不支持promise

**尝试方案**
官网上都写了对promise的支持 结果ts不支持
真的对我们写ts的人来说好心累

**补充信息**
[其它你认为有参考价值的信息]

**Comment by Iongtao** [comment]
隔壁taro对ts支持就好太多了 去偷点Types过来呀

**Comment by WindrunnerMax** [comment]
还有`uni`很多`Api`调用支持`Promise`写法，但是`d.ts`没声明，只能写回调。。。

**Comment by dnt1996** [comment]
唉，vue和uni-app对ts支持太糟糕了，到了vue3也还是有痛点

**Comment by TuiMao233** [comment]
request 返回的就是 task 阿

**Comment by sonofmagic** [comment]
2023年了，现在版本的 uni-app 还是没有对 types 里，原先的回调函数进行重载，返回 promise 类型，依旧还是一个大大的 void

导致:

```ts
const [err, res] = await uni.showModal
```
这种全部报错

**Comment by StrivingRabbit** [comment]
可以升级 @dcloudio/types@3.3.0 试试看

**Comment by sonofmagic** [comment]
> ```ts
> uni.showModal
> ```

我升级到了 `@dcloudio/types@3.3.0` 有个问题哈，现在 API Promise 化，调用结果在 vue2 和 vue3 是不同的

在 Vue3 中，处理 API Promise 化 调用结果的方式不同于 Vue2。[更多](https://uniapp.dcloud.io/api/#api-promise-%E5%8C%96)

Vue3 中，调用成功会进入 then 方法，调用失败会进入 catch 方法
Vue2 中，调用无论成功还是失败，都会进入 then 方法，返回数据的第一个参数是错误对象，第二个参数是返回数据

详见 https://uniapp.dcloud.net.cn/tutorial/migration-to-vue3.html#api-promise-%E5%8C%96-%E8%B0%83%E7%94%A8%E7%BB%93%E6%9E%9C%E7%9A%84%E6%96%B9%E5%BC%8F

 `@dcloudio/types@3.3.0` 这个版本在 vue3 项目下是好的，vue2就不行：
![image](https://user-images.githubusercontent.com/15621541/218426165-48289400-9d5d-45e9-99f8-f7d6cdbceb49.png)

是不是应该给这个包打个 tag 来区别 vue2 还是 vue3 的 dts ？

**Comment by StrivingRabbit** [comment]
@sonofmagic 关于 vue2 可以参考[文档](https://uniapp.dcloud.net.cn/api/#api-promise-%E5%8C%96) 处理，后续也会发布 vue2 的 api promise 处理

**Comment by ModyQyW** [comment]
希望官方对社区关注多一些，跟进社区诉求快一些。

**Comment by StrivingRabbit** [comment]
@dcloudio/types@3.3.1 已发布：
支持 `connectSocket、request、uploadFile、downloadFile` API 的 Promise 化 ts 提示

> 关于 vue2 可以参考[文档](https://uniapp.dcloud.net.cn/api/#api-promise-%E5%8C%96) 处理，后续也会发布 vue2 的 api promise 处理

**Comment by BigFatStar** [comment]
> @dcloudio/types@3.3.1 已发布： 支持 `connectSocket、request、uploadFile、downloadFile` API 的 Promise 化 ts 提示
> 
> > 关于 vue2 可以参考[文档](https://uniapp.dcloud.net.cn/api/#api-promise-%E5%8C%96) 处理，后续也会发布 vue2 的 api promise 处理

使用ts定义request的返回值类型还是会有不准确的问题啊

**Comment by zhetengbiji** [comment]
> > @dcloudio/types@3.3.1 已发布： 支持 `connectSocket、request、uploadFile、downloadFile` API 的 Promise 化 ts 提示
> > > 关于 vue2 可以参考[文档](https://uniapp.dcloud.net.cn/api/#api-promise-%E5%8C%96) 处理，后续也会发布 vue2 的 api promise 处理
> 
> 使用ts定义request的返回值类型还是会有不准确的问题啊

具体讲一下

**Comment by luokang2015** [comment]
> > > @dcloudio/types@3.3.1 已发布： 支持 API 的 Promise 化 ts 提示`connectSocket、request、uploadFile、downloadFile`
> > > > 关于 vue2 可以参考[文档](https://uniapp.dcloud.net.cn/api/#api-promise-%E5%8C%96) 处理，后续也会发布 vue2 的 API promise 处理
> > 
> > 
> > 使用ts定义request的返回值类型还是会有不准确的问题啊
> 
> 具体讲一下

await uni.request({
				url: 'https://fc-mp-8ba27ec2-89fd-48c2-ba92-9c9aca.next.bspapp.com/api/user/getU'
			})
请求云对象url化返回的是个RequestTask类型，不让用await，虽然这个api不使用success就promise化了

**Comment by StrivingRabbit** [comment]
> > > > @dcloudio/types@3.3.1 已发布： 支持 API 的 Promise 化 ts 提示`connectSocket、request、uploadFile、downloadFile`
> > > > > 关于 vue2 可以参考[文档](https://uniapp.dcloud.net.cn/api/#api-promise-%E5%8C%96) 处理，后续也会发布 vue2 的 API promise 处理
> > > 
> > > 
> > > 使用ts定义request的返回值类型还是会有不准确的问题啊
> > 
> > 
> > 具体讲一下
> 
> await uni.request({ url: 'https://fc-mp-8ba27ec2-89fd-48c2-ba92-9c9aca.next.bspapp.com/api/user/getU' }) 请求云对象url化，ts推断返回的是RequestTask类型，不能使用await，虽然这个api不使用success就promise化了，所以我不得不使用await new Promise((resolve)=>{ uni.request({ success: (res)=>{ reslove(res.data as Type) //我的ts实在是太烂了，没有更好的处理方案 } }) })

你使用的 @dcloudio/types 是什么版本？如果没有传 success 返回应该是 Promise

**Comment by luokang2015** [comment]
> > > > > @dcloudio/types@3.3.1 已发布： 支持 API 的 Promise 化 ts 提示`connectSocket、request、uploadFile、downloadFile`
> > > > > > 关于 vue2 可以参考[文档](https://uniapp.dcloud.net.cn/api/#api-promise-%E5%8C%96) 处理，后续也会发布 vue2 的 API promise 处理
> > > > 
> > > > 
> > > > 使用ts定义request的返回值类型还是会有不准确的问题啊
> > > 
> > > 
> > > 具体讲一下
> > 
> > 
> > await uni.request({ url: 'https://fc-mp-8ba27ec2-89fd-48c2-ba92-9c9aca.next.bspapp.com/api/user/getU' }) 请求云对象url化，ts推断返回的是RequestTask类型，不能使用await，虽然这个api不使用success就promise化了，所以我不得不使用await new Promise((resolve)=>{ uni.request({ success: (res)=>{ reslove(res.data as Type) //我的ts实在是太烂了，没有更好的处理方案 } }) })
> 
> 你使用的 @dcloudio/types 是什么版本？如果没有传 success 返回应该是 Promise

"@dcloudio/types": "^3.3.3"

**Comment by Megasu** [comment]
持续关注该问题。👀

**Comment by StrivingRabbit** [comment]
@luokang2015 @Megasu 

将附件中的 js 文件放到项目根目录，然后在 `main.js` 中这样使用即可：

```js
import App from './App'
import Vue from 'vue'
import './uni.promisify.adaptor' // Look here
Vue.config.productionTip = false
App.mpType = 'app'
const app = new Vue({
  ...App
})
app.$mount()
```

[uni.promisify.adaptor.js.zip](https://github.com/dcloudio/uni-app/files/11461228/uni.promisify.adaptor.js.zip)

**Comment by luokang2015** [comment]
> @luokang2015 @Megasu
> 
> 将附件中的 js 文件放到项目根目录，然后在 `main.js` 中这样使用即可：
> 
> ```
> import App from './App'
> import Vue from 'vue'
> import './uni.promisify.adaptor' // Look here
> Vue.config.productionTip = false
> App.mpType = 'app'
> const app = new Vue({
>   ...App
> })
> app.$mount()
> ```
> 
> [uni.promisify.adaptor.js.zip](https://github.com/dcloudio/uni-app/files/11461228/uni.promisify.adaptor.js.zip)

> 

> 
![1683885104995](https://github.com/dcloudio/uni-app/assets/129868056/3fca02f5-100f-4e2a-a313-bf9e8dd2b591)
HBuilderx自己推断的类型是这个，

**Comment by StrivingRabbit** [comment]
> 

在 hx 中用的啊，那升级 hx 到 3.8.2 试试看

**Comment by luokang2015** [comment]
> > 
> 
> 在 hx 中用的啊，那升级 hx 到 3.8.2 试试看

哈哈，那算了，等正式版再升级，
