### ISSUE TITLE
空格开头不显示

### ISSUE THREAD

**Issue by 577715766** [dcloudio/uni-app#301]
<text decode="true">&nbsp;文字信息</text>

上面的写法空格不显示，以前还可以的

<text decode="true">文&nbsp;字信息</text>

写成上面这样的可以正常显示空格

希望修改成空格可以开头

**Comment by fxy060608** [comment]
模板代码因为代码格式化可能会出现换行，空格等非预期字符，故文本节点的首尾空格换行等字符均会被清理掉，如果希望在首尾添加空格，可以使用变量赋值，并结合 text 标签 space 属性来控制空格显示逻辑
