### ISSUE TITLE
webpack 打包不支持 mixins ?

### ISSUE THREAD

**Issue by sufuWang** [dcloudio/uni-app#3015]
使用 `vue create -p dcloudio/uni-preset-vue#vue3 my-vue3-project` 新建项目
在页面中加入 mixins ，会导致页面中的 onLoad 、onShow 等生命周期方法失效，对于 vue 的生命周期函数与旧版本（ webpack 打包）的 mixins 行为一致，同时触发 mixins 和页面中的生命周期函数。
> 在页面中加入 mixins ，会导致页面中的 onLoad 、onShow 等生命周期方法失效

请问这个是 bug 吗？

**Comment by fxy060608** [comment]
vue3 webpack版本不再维护，请切换为vite版本：

npx degit dcloudio/uni-preset-vue#vite my-vue3-project

**Comment by sufuWang** [comment]
得知这一消息，我哭了
