### ISSUE TITLE
vite项目如何引入uni-ui组件

### ISSUE THREAD

**Issue by Iongtao** [dcloudio/uni-app#3016]
**问题描述**
我的项目是cli创建的vite编译的项目
官网文档只有对老版本的vue的 引入方式
vite.config.js中没有transpileDependencies该选项
请问vite中改如何引入uni-ui组件

**复现步骤**
![image](https://user-images.githubusercontent.com/24762616/143204635-ebec480b-6d59-47d8-8d6e-ca4f9c675081.png)

![image](https://user-images.githubusercontent.com/24762616/143203426-a10050b2-3f2d-421e-aaff-b0e8a9ba77be.png)

**预期结果**
引入正常

**实际结果**
组件引入失败

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 微信小程序模拟器
 - HBuilderX版本 cli
 - uni-app版本 
 - 设备信息 微信小程序模拟iphone6

**补充信息**
无

**Comment by fxy060608** [comment]
目前暂未支持`import { uniBadge } from '@dcloudio/uni-ui'`
可以先使用`import uniBadge from '@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue'`

**Comment by Iongtao** [comment]
> 目前暂未支持`import { uniBadge } from '@dcloudio/uni-ui'` 推荐使用easycom配置 或者可以先使用`import uniBadge from '@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue'`

我想请教一下另一个问题：我想去扩展原生button组件， 但我用了volar插件 会对template中的button里属性类型做类型校验就出现了一下问题呢
![image](https://user-images.githubusercontent.com/24762616/143371068-9c42f150-b5ff-495a-bb57-18ef47406a32.png)
button的类型指向的是原生的类型 请问是否有小程序的组件类型替换 还是关闭这个提示

**Comment by fxy060608** [comment]
> 

暂未提供组件类型

**Comment by fxy060608** [comment]
> > 目前暂未支持`import { uniBadge } from '@dcloudio/uni-ui'` 推荐使用easycom配置 或者可以先使用`import uniBadge from '@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue'`
> 
> 我想请教一下另一个问题：我想去扩展原生button组件， 但我用了volar插件 会对template中的button里属性类型做类型校验就出现了一下问题呢 ![image](https://user-images.githubusercontent.com/24762616/143371068-9c42f150-b5ff-495a-bb57-18ef47406a32.png) button的类型指向的是原生的类型 请问是否有小程序的组件类型替换 还是关闭这个提示

暂未提供组件类型

**Comment by JimmieMax** [comment]
在pages.json中添加如下配置
`
	"easycom": {
		"autoscan": true,
		"custom": {
			"^uni-(.*)": "@dcloudio/uni-ui/lib/uni-$1/uni-$1.vue"
		}
	},
`

然后在项目中就可以直接用了

**Comment by Iongtao** [comment]
> 

这个加过了， 但很奇怪 有的组件直接用会报错， 有点却不会，不过现在已经改成了hbuilderx跑项目，也没关系了

**Comment by Lisheri** [comment]
> 

你好, 请问vite是否支持easycom, 我在pages.json中配置后, 没有生效, 不管是我们自己的库, 还是uni-ui还是直接写在src/components/* 下的组件

<img width="769" alt="image" src="https://user-images.githubusercontent.com/49238808/156342788-28b8e2b1-8716-49c9-ae80-55b99216c943.png">

**Comment by Lisheri** [comment]
> 

老哥这个easycom可以用吗~

**Comment by Lisheri** [comment]
> 目前暂未支持`import { uniBadge } from '@dcloudio/uni-ui'` 推荐使用easycom配置 或者可以先使用`import uniBadge from '@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue'`

=。=原来是我外层的lerna影响了, 打扰了, 两个方式都没有问题

**Comment by Iongtao** [comment]
> > 目前暂未支持`import { uniBadge } from '@dcloudio/uni-ui'` 推荐使用easycom配置 或者可以先使用`import uniBadge from '@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue'`
> 
> =。=原来是我外层的lerna影响了, 打扰了, 两个方式都没有问题

应该是好了的吧 我已经没有用命令行的方式去开发项目了 转hbuilder了

**Comment by Lisheri** [comment]
> > > 目前暂未支持`import { uniBadge } from '@dcloudio/uni-ui'` 推荐使用easycom配置 或者可以先使用`import uniBadge from '@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue'`
> > 
> > 
> > =。=原来是我外层的lerna影响了, 打扰了, 两个方式都没有问题
> 
> 应该是好了的吧 我已经没有用命令行的方式去开发项目了 转hbuilder了

没问题, 是外面套了一层monorepo, 导致的路径问题

**Comment by ribuluo000** [comment]
> 

请问是怎么解决的呢？我也遇到了同样的问题。

**Comment by ribuluo000** [comment]
> > > > 目前暂未支持`import { uniBadge } from '@dcloudio/uni-ui'` 推荐使用easycom配置 或者可以先使用`import uniBadge from '@dcloudio/uni-ui/lib/uni-badge/uni-badge.vue'`
> > > 
> > > 
> > > =。=原来是我外层的lerna影响了, 打扰了, 两个方式都没有问题
> > 
> > 
> > 应该是好了的吧 我已经没有用命令行的方式去开发项目了 转hbuilder了
> 
> 没问题, 是外面套了一层monorepo, 导致的路径问题


请问是怎么解决的呢？我也遇到了同样的问题。
