### ISSUE TITLE
vite 打包 style scoped

### ISSUE THREAD

**Issue by sufuWang** [dcloudio/uni-app#3017]
控制台报 `[vite:vue] Cannot read property 'scoped' of undefined`
如何支持 `<style scoped lang="less" src="styles/pages/visit/1212.less"></style>` ?

**Comment by fxy060608** [comment]
建议提问，描述清楚环境，平台，给可重现的测试工程最佳

**Comment by sufuWang** [comment]
![image](https://user-images.githubusercontent.com/46395105/143536176-e9095f15-2849-44f4-be8d-3e58408effed.png)

**Comment by credagit** [comment]
无法重现，发测试工程

**Comment by fxy060608** [comment]
未重现，可以提供一个测试工程

**Comment by sufuWang** [comment]
这个问题偶现，并不是每次打包都会出现
在 vite 项目中，还支持 `uni-composition-api` 和 `@vue/composition-api` 嘛？测试工程 https://github.com/sufuWang/uniapp_vite
报错如下图
![image](https://user-images.githubusercontent.com/46395105/143542484-d5ed5518-8766-4410-9883-ded6059e9f2c.png)

**Comment by fxy060608** [comment]
> 这个问题偶现，并不是每次打包都会出现 在 vite 项目中，还支持 `uni-composition-api` 和 `@vue/composition-api` 嘛？测试工程 https://github.com/sufuWang/uniapp_vite 报错如下图 ![image](https://user-images.githubusercontent.com/46395105/143542484-d5ed5518-8766-4410-9883-ded6059e9f2c.png)

vue3 中不支持 @vue/composition-api

**Comment by sufuWang** [comment]
可以使用 `vue`代替 `@vue/composition-api` ，`uni-composition-api` 应该如何兼容呀？

**Comment by fxy060608** [comment]
可以使用 @dcloudio/uni-app
https://github.com/dcloudio/uni-app/blob/next/packages/uni-app/src/apiLifecycle.ts

**Comment by sufuWang** [comment]
vite 中 alias 设置不生效，报错如下
```
[vite]: Rollup failed to resolve import "@utlis/index" from "src/pages/index/index.vue?mpType=page".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```
vite.config.js 如下
```node
import { defineConfig } from 'vite'
import uni from '@dcloudio/vite-plugin-uni'
const path = require('path')

const resolve = (dir) => path.resolve(__dirname, dir);

export default defineConfig({
  plugins: [
    uni(),
  ],
  resolve: {
    alias: [
      { find: '@components', replacement: resolve('src/components'), },
      { find: '@assets', replacement: resolve('src/assets'), },
      { find: '@utils', replacement: resolve('src/utils'), },
      { find: '@config', replacement: resolve('src/config'), },
      { find: '@pages', replacement: resolve('src/pages'), },
    ]
    // alias: {
    //   '@utils': resolve('src/utils')
    // }
  },
  build: {
    rollupOptions: {      
    }
  }
})

```
测试工程 https://github.com/sufuWang/uniapp_vite

**Comment by sufuWang** [comment]
```html
<img
    src=" https://ass.com/as/12.png"
    alt=""
    class="issue-details-bd__upload--close"
  />
```
报错如下
```
[vite]: Rollup failed to resolve import "/as/12.png" from "src/pages/index/index.vue?mpType=page".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```
测试工程：https://github.com/sufuWang/uniapp_vite

**Comment by sufuWang** [comment]
请问未来会支持 `<block>` 标签嘛？

**Comment by fxy060608** [comment]
> 请问未来会支持 `<block>` 标签嘛？

建议使用template

**Comment by sufuWang** [comment]
好的，请问 `process` 是不在支持了嘛？有什么替代方案？
![image](https://user-images.githubusercontent.com/46395105/143576429-81507341-3c27-483a-b034-fa08ed3d82ea.png)

**Comment by fxy060608** [comment]
> 好的，请问 `process` 是不在支持了嘛？有什么替代方案？ ![image](https://user-images.githubusercontent.com/46395105/143576429-81507341-3c27-483a-b034-fa08ed3d82ea.png)

你怎么使用的？

**Comment by sufuWang** [comment]
```js
const env = process.env.VUE_APP_ENV;
const wxPlatform = process.env.WX_PLATFORM
```
根据环境变量进行映射

**Comment by fxy060608** [comment]
> ```js
> const env = process.env.VUE_APP_ENV;
> const wxPlatform = process.env.WX_PLATFORM
> ```
> 
> 根据环境变量进行映射

你自己定义的这些环境变量？怎么定义的？

**Comment by sufuWang** [comment]
```
 "dev:mp-weixin": "cross-env NODE_ENV=development cross-env VUE_APP_ENV=development UNI_PLATFORM=mp-weixin uni -p mp-weixin",
```

**Comment by fxy060608** [comment]
> ```
>  "dev:mp-weixin": "cross-env NODE_ENV=development cross-env VUE_APP_ENV=development UNI_PLATFORM=mp-weixin uni -p mp-weixin",
> ```
> 
> `process` is not defined 和如何定义环境变量，应该没有关系吧？

应该通过vite.config.js里边配置define来处理，框架不会把整个process.env里边的内容放进运行时的，都是通过替换实现的

**Comment by sufuWang** [comment]
大佬，再报一个 bug ，引入 uuid 库，导致项目打包失败
测试工程：https://github.com/sufuWang/uniapp_vite

**Comment by sufuWang** [comment]
> 可以通过.env 配置环境或 vite.config.js里边配置define来处理，框架不会把整个process.env里边的内容放进运行时的，都是通过替换实现的
> https://cn.vitejs.dev/config/#define
> https://cn.vitejs.dev/guide/env-and-mode.html#env-files

好的，谢谢大佬。
遇到一个 bug ，引入 `uuid` 库导致打包报错，报错如下
```
TypeError: index.requireNativePlugin is not a function
    at Object.getRandomValues (vendor.js? [sm]:5091)
    at rng (vendor.js? [sm]:5105)
    at Object.v4 (vendor.js? [sm]:5125)
    at app.js? [sm]:18
    at p (VM109 WAService.js:2)
    at <anonymous>:3:9
    at doWhenAllScriptLoaded (<anonymous>:1133:21)
    at Object.scriptLoaded (<anonymous>:1161:5)
    at Object.<anonymous> (<anonymous>:1186:22)(env: macOS,mp,1.05.2110290; lib: 2.21.0)
```
测试工程：https://github.com/sufuWang/uniapp_vite

**Comment by fxy060608** [comment]
> > 可以通过.env 配置环境或 vite.config.js里边配置define来处理，框架不会把整个process.env里边的内容放进运行时的，都是通过替换实现的
> > https://cn.vitejs.dev/config/#define
> > https://cn.vitejs.dev/guide/env-and-mode.html#env-files
> 
> 好的，谢谢大佬。 遇到一个 bug ，引入 `uuid` 库导致打包报错，报错如下
> 
> ```
> TypeError: index.requireNativePlugin is not a function
>     at Object.getRandomValues (vendor.js? [sm]:5091)
>     at rng (vendor.js? [sm]:5105)
>     at Object.v4 (vendor.js? [sm]:5125)
>     at app.js? [sm]:18
>     at p (VM109 WAService.js:2)
>     at <anonymous>:3:9
>     at doWhenAllScriptLoaded (<anonymous>:1133:21)
>     at Object.scriptLoaded (<anonymous>:1161:5)
>     at Object.<anonymous> (<anonymous>:1186:22)(env: macOS,mp,1.05.2110290; lib: 2.21.0)
> ```
> 
> 测试工程：https://github.com/sufuWang/uniapp_vite

requireNativePlugin的问题会修复，但uuid这个库是不支持小程序的，即使我们处理了这个报错，你也没法直接用uuid这个库，另外新的issue，可以单独发出来，避免回复太多与当前issue无关的内容

**Comment by sufuWang** [comment]
> 



> [fxy060608](/fxy060608)

大佬，已经新建 issue ，https://github.com/dcloudio/uni-app/issues/3025
