### ISSUE TITLE
属性选择器编译错误

### ISSUE THREAD

**Issue by yiqianglin** [dcloudio/uni-app#3018]
**问题描述**
属性选择器问题；

**复现步骤**
使用cli构建的项目
源码：
![image](https://user-images.githubusercontent.com/15794229/143455001-8684892b-c635-478a-b7ce-26b44cb89e5d.png)

**预期结果**
期望是标签选择器生效

**实际结果**
![image](https://user-images.githubusercontent.com/15794229/143455265-2008c220-f44d-4992-bac5-5c1c7496c1de.png)
实际结果input加上了._的前缀

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 macos
 - uni-app版本 2.0.0-31420210305001
"@dcloudio/vue-cli-plugin-hbuilderx": "^2.0.0-31820210406002"

**Comment by zhetengbiji** [comment]
确认一下是否是此限制导致

> https://uniapp.dcloud.io/frame?id=%e9%80%89%e6%8b%a9%e5%99%a8
> 微信小程序自定义组件中仅支持 class 选择器
