### ISSUE TITLE
如何获取pages.json的数据， 我想做扩展，例如login的拦截，auth的拦截，统一的404入口等

### ISSUE THREAD

**Issue by mainpro** [dcloudio/uni-app#302]
我发现编辑之后的文件里面没有pages.json ，在main.js里面读取不到pages.json

请问应该怎么才能读到pages.json，或者有其他的优雅方式

感谢作者，希望uniapp越来越好

**Comment by lixia9** [comment]
这个问题我也考虑过 npm run dev  和 build的时候执行自己的build文件 根据 pages.json动态生成自己需要的配置文件 pages.js 然后在main.js中使用  分环境打包也是一样的道理

**Comment by onlyshow** [comment]
确实，路由缺少切面，不能统一控制，很难受

**Comment by MadSummer** [comment]
import进来拿不到，目前临时写了个脚本同步一份，希望官方能把这个文件放开

**Comment by mainpro** [comment]
> import进来拿不到，目前临时写了个脚本同步一份，希望官方能把这个文件放开

老哥，用什么方式同步的，我能想到最简单的方式就是项目做完了，再复制一份

**Comment by onlyshow** [comment]
起进程 监听 md5_file和sha1_file 不一样 就copy

**Comment by SilasDong** [comment]
顶上

**Comment by zhetengbiji** [comment]
使用require

**Comment by Devil-Cong** [comment]
@zhetengbiji 根本就不行，拿到的是个空对象

**Comment by bxpxqxd** [comment]
> @zhetengbiji 根本就不行，拿到的是个空对象

复制一个引用就行了

**Comment by xlfsummer** [comment]
可以这样引入
```js
import pages from "uni-pages?{\"type\":\"style\"}";
```

参考源码：
node_modules\@dcloudio\vue-cli-plugin-uni\lib\configure-webpack.js:261
```js
        alias: {
          '@': path.resolve(process.env.UNI_INPUT_DIR),
          'vue$': getPlatformVue(),
          'uni-pages': path.resolve(process.env.UNI_INPUT_DIR, 'pages.json'),
          '@dcloudio/uni-stat': require.resolve('@dcloudio/uni-stat'),
          'uni-stat-config': path.resolve(process.env.UNI_INPUT_DIR, 'pages.json') +
            '?' +
            JSON.stringify({
              type: 'stat'
            })
        },
```

node_modules\@dcloudio\vue-cli-plugin-uni\lib\configure-webpack.js:219
```js
const rules = [{
      test: path.resolve(process.env.UNI_INPUT_DIR, 'pages.json'),
      use: [{
        loader: 'babel-loader'
      }, {
        loader: '@dcloudio/webpack-uni-pages-loader'
      }],
      type: 'javascript/auto'
    },
  // ...
]
```

node_modules\@dcloudio\webpack-uni-pages-loader\lib\index.js:28
```js
module.exports = function (content) {
  if (this.resourceQuery) {
    const params = loaderUtils.parseQuery(this.resourceQuery)
    if (params) {
      if (params.type === 'style') {
        return `export default ${JSON.stringify(getPagesJson())}`
      } else if (params.type === 'stat') {
        return `export default ${JSON.stringify(process.UNI_STAT_CONFIG || {})}`
      }
    }
  }
 // ...
}
```

**Comment by wizardpisces** [comment]
为啥不让读这个文件？不读的人不在乎，有需求的人还是会想办法读取？怎么感觉uniapp 到处都是隐藏的坑

**Comment by 2234839** [comment]
也可以使用 webpack 的 loader 来获取，这或许要比@xlfsummer 的方案更稳一点
```
import("!!raw-loader!../pages.json").then((r) => {
  console.log("[r]", r);
});
```

**Comment by SilurianYang** [comment]
## [uni-read-pages](https://github.com/SilurianYang/uni-read-pages)
## [使用示例](https://hhyang.cn/v2/tutorial/rgRoutes.html#%E5%AE%89%E8%A3%85)

**Comment by 772778995** [comment]
@xlfsummer 的确有用，但是用 vite 该怎么做？

**Comment by fxy060608** [comment]
> @xlfsummer 的确有用，但是用 vite 该怎么做？

vite 版本，可以直接 import
```js
import { pages } from '@/pages.json'
console.log(pages)
```

**Comment by liushuangisme** [comment]
> 可以这样引入
> 
> ```js
> import pages from "uni-pages?{\"type\":\"style\"}";
> ```
> 
> 参考源码： node_modules@dcloudio\vue-cli-plugin-uni\lib\configure-webpack.js:261
> 
> ```js
>         alias: {
>           '@': path.resolve(process.env.UNI_INPUT_DIR),
>           'vue$': getPlatformVue(),
>           'uni-pages': path.resolve(process.env.UNI_INPUT_DIR, 'pages.json'),
>           '@dcloudio/uni-stat': require.resolve('@dcloudio/uni-stat'),
>           'uni-stat-config': path.resolve(process.env.UNI_INPUT_DIR, 'pages.json') +
>             '?' +
>             JSON.stringify({
>               type: 'stat'
>             })
>         },
> ```
> 
> node_modules@dcloudio\vue-cli-plugin-uni\lib\configure-webpack.js:219
> 
> ```js
> const rules = [{
>       test: path.resolve(process.env.UNI_INPUT_DIR, 'pages.json'),
>       use: [{
>         loader: 'babel-loader'
>       }, {
>         loader: '@dcloudio/webpack-uni-pages-loader'
>       }],
>       type: 'javascript/auto'
>     },
>   // ...
> ]
> ```
> 
> node_modules@dcloudio\webpack-uni-pages-loader\lib\index.js:28
> 
> ```js
> module.exports = function (content) {
>   if (this.resourceQuery) {
>     const params = loaderUtils.parseQuery(this.resourceQuery)
>     if (params) {
>       if (params.type === 'style') {
>         return `export default ${JSON.stringify(getPagesJson())}`
>       } else if (params.type === 'stat') {
>         return `export default ${JSON.stringify(process.UNI_STAT_CONFIG || {})}`
>       }
>     }
>   }
>  // ...
> }
> ```

app打包的vue2应用还是拿到空对象，h5能正常拿到
<img width="1200" alt="image" src="https://github.com/dcloudio/uni-app/assets/69240172/9490e9b3-2ae1-4cbf-ac10-316cc949f981">

**Comment by w934423231** [comment]
> > @xlfsummer 的确有用，但是用 vite 该怎么做？
> 
> vite 版本，可以直接 import
> 
> ```js
> import { pages } from '@/pages.json'
> console.log(pages)
> ```
这种打包后会出现问题吗
