### ISSUE TITLE
[Bug] vue3 onTabBarMidButtonTap API回调失效

### ISSUE THREAD

**Issue by SngBlog** [dcloudio/uni-app#3021]
**问题描述**
App.vue onLaunch 回调中注册midbutton回调失效

**复现步骤**
<script>
	export default {
		onLaunch() {
			cc(() => {
				uni.navigateTo({
					url: "pages/xxx/xxx"
				})
			})
		}
	}
</script>

**预期结果**
uni.onTabBarMidButtonTap API重新生效
**实际结果**
并没有生效

**系统信息:**
 - 发行平台: APP平台
 - 操作系统 Android 11 
 - HBuilderX版本 3.2.15 alpha
 - 设备信息 红米K30

**补充信息**

**Comment by fxy060608** [comment]
升级至3.3.0
