### ISSUE TITLE
[帮助壮大社区，而不是从入门到放弃]真诚的建议DCloud官方从从没听说过Uniapp的新手角度梳理一下入门的文档

### ISSUE THREAD

**Issue by whoooami** [dcloudio/uni-app#3024]
**新功能描述**
真的是能帮助壮大社区的，而不是从入门到放弃。

**现状及问题**
现在的文档结构，我只能说小程序、H5还行。如果开发APP，文档结构、名词概念、IDE中英文互译都略显凌乱。并且有的翻译还在变化，这样有时升级后根据错误提示有时搜不出来任何有价值的信息。这种情况能不能给出对应的错误码以及错误码字典？

**尝试方案**
建议可以从新招聘的开发人员对DCloud不熟悉的同事中，找几个让他们从零开始开发一个基础的APP/H5/小程序，并且尽量不问同事的情况下自行记录下来中间的疑惑和过程。然后官方可以针对性进行梳理。

**补充信息**
像这之类的错误
[https://ask.dcloud.net.cn/question/118750](https://ask.dcloud.net.cn/question/118750)
是不是应该在原文档 [https://nativesupport.dcloud.net.cn/AppDocs/usesdk/android ](https://nativesupport.dcloud.net.cn/AppDocs/usesdk/android)中加一个refer, 或者更好的直接在步骤中指出呢？
如果文档可以稍稍的结构化一点，相信大家可以少发很多问答贴耽误DCloud官方开发新Feature，提升平台体验的时间。
个人之见，如有不妥，见谅

**Comment by hzh1990** [comment]
你出钱?

**Comment by whoooami** [comment]
好的，先等我学会制冷了
