### ISSUE TITLE
setTabBarItem设置visible属性无效 

### ISSUE THREAD

**Issue by BHdear** [dcloudio/uni-app#3026]
**问题描述**
uni.setTabBarItem({ index: 0, visible: hasEnableMatchEvaluation, complete: res => console.log(res) })

**预期结果**
调用正确应当隐藏目标项

**实际结果**
设置visible为false时没有隐藏对应项

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本: 3.2.16

**Comment by StrivingRabbit** [comment]
微信小程序不支持隐藏显示tabbar

**Comment by LaiosOvO** [comment]
文档里面不是显示微信小程序是支持的吗

<img width="698" height="430" alt="Image" src="https://github.com/user-attachments/assets/cf4f34ca-5fa9-4c47-adaf-8873b6a9cd3d" />

**Comment by LaiosOvO** [comment]
但是我测试只有替换文字是可以的显示和隐藏以及跳转的组件变不了
