### ISSUE TITLE
打包H5  偶现部分uni-开头样式丢失

### ISSUE THREAD

**Issue by iuping** [dcloudio/uni-app#3029]
**问题描述**
使用cli打包H5，有时候会出现uni-image   uni-toast 等一系列uni开头的样式未打包成功，导致样式错乱，但不是必现

**Comment by StrivingRabbit** [comment]
使用的什么版本打包出现的问题？

**Comment by iuping** [comment]
> 使用的什么版本打包出现的问题？

刚开始是可视化工具创建的项目，但是不能通过cli打包，我后面用命令npx degit dcloudio/uni-preset-vue#vite my-vue3-project
重新创建了vue3项目，把代码挪了过去

**Comment by fxy060608** [comment]
> 

该问题已修复，今天会发一个版本，到时候更新下最新依赖即可

**Comment by fxy060608** [comment]
更新至 HBuilderX Alpha 3.3.0 或 cli：3.0.0-alpha-3030020211201003

**Comment by iuping** [comment]
> 更新至 HBuilderX Alpha 3.3.0 或 cli：3.0.0-alpha-3030020211201003

好的 感谢回复

**Comment by iuping** [comment]
> 更新至 HBuilderX Alpha 3.3.0 或 cli：3.0.0-alpha-3030020211201003

hi，3.0.0-alpha-3030020211201003确实解决了系统样式打包问题，但是这个版本在使用了video标签的页面，热更新报错
![image](https://user-images.githubusercontent.com/41564157/147555479-d3aba782-0bbe-4fbc-b953-443fe21dec14.png)

**Comment by fxy060608** [comment]
> > 更新至 HBuilderX Alpha 3.3.0 或 cli：3.0.0-alpha-3030020211201003
> 
> hi，3.0.0-alpha-3030020211201003确实解决了系统样式打包问题，但是这个版本在使用了video标签的页面，热更新报错 ![image](https://user-images.githubusercontent.com/41564157/147555479-d3aba782-0bbe-4fbc-b953-443fe21dec14.png)

升级至最新：3.0.0-alpha-3030420211227003
发现问题，可以先检查是否有最新版本

**Comment by iuping** [comment]
> 3.0.0-alpha-3030420211227003

这个版本又出现了别的bug  我看了下最新版本是3.0.0-alpha-3030420211228003,  请问alpha版本可用吗？我觉得alpha版本挺多bug，或者我该使用什么正式版本吗？

**Comment by iuping** [comment]
> > > 更新至 HBuilderX Alpha 3.3.0 或 cli：3.0.0-alpha-3030020211201003
> > 
> > 
> > hi，3.0.0-alpha-3030020211201003确实解决了系统样式打包问题，但是这个版本在使用了video标签的页面，热更新报错 ![image](https://user-images.githubusercontent.com/41564157/147555479-d3aba782-0bbe-4fbc-b953-443fe21dec14.png)
> 
> 升级至最新：3.0.0-alpha-3030420211227003 发现问题，可以先检查是否有最新版本

这个版本又出现了别的bug 我看了下最新版本是3.0.0-alpha-3030420211228003, 请问alpha版本可用吗？我觉得alpha版本挺多bug，或者我该使用什么正式版本吗？

**Comment by zhetengbiji** [comment]
> > > > 更新至 HBuilderX Alpha 3.3.0 或 cli：3.0.0-alpha-3030020211201003
> > > 
> > > 
> > > hi，3.0.0-alpha-3030020211201003确实解决了系统样式打包问题，但是这个版本在使用了video标签的页面，热更新报错 ![image](https://user-images.githubusercontent.com/41564157/147555479-d3aba782-0bbe-4fbc-b953-443fe21dec14.png)
> > 
> > 
> > 升级至最新：3.0.0-alpha-3030420211227003 发现问题，可以先检查是否有最新版本
> 
> 这个版本又出现了别的bug 我看了下最新版本是3.0.0-alpha-3030420211228003, 请问alpha版本可用吗？我觉得alpha版本挺多bug，或者我该使用什么正式版本吗？

npm run info 打印一下依赖

**Comment by fxy060608** [comment]
> > > > 更新至 HBuilderX Alpha 3.3.0 或 cli：3.0.0-alpha-3030020211201003
> > > 
> > > 
> > > hi，3.0.0-alpha-3030020211201003确实解决了系统样式打包问题，但是这个版本在使用了video标签的页面，热更新报错 ![image](https://user-images.githubusercontent.com/41564157/147555479-d3aba782-0bbe-4fbc-b953-443fe21dec14.png)
> > 
> > 
> > 升级至最新：3.0.0-alpha-3030420211227003 发现问题，可以先检查是否有最新版本
> 
> 这个版本又出现了别的bug 我看了下最新版本是3.0.0-alpha-3030420211228003, 请问alpha版本可用吗？我觉得alpha版本挺多bug，或者我该使用什么正式版本吗？

vue3 cli 目前只有alpha版，随时保证新版本，有问题直接在github上提就可以了，会随时修复

**Comment by iuping** [comment]
> 



> > > > > 更新至 HBuilderX Alpha 3.3.0 或 cli：3.0.0-alpha-3030020211201003
> > > > 
> > > > 
> > > > hi，3.0.0-alpha-3030020211201003确实解决了系统样式打包问题，但是这个版本在使用了video标签的页面，热更新报错 ![image](https://user-images.githubusercontent.com/41564157/147555479-d3aba782-0bbe-4fbc-b953-443fe21dec14.png)
> > > 
> > > 
> > > 升级至最新：3.0.0-alpha-3030420211227003 发现问题，可以先检查是否有最新版本
> > 
> > 
> > 这个版本又出现了别的bug 我看了下最新版本是3.0.0-alpha-3030420211228003, 请问alpha版本可用吗？我觉得alpha版本挺多bug，或者我该使用什么正式版本吗？
> 
> vue3 cli 目前只有alpha版，随时保证新版本，有问题直接在github上提就可以了，会随时修复


你好~~  最新版本3.0.0-alpha-3030520211229003 中swiper内嵌视频，会导致swiper滑动不了，请问能解决吗？
