### ISSUE TITLE
vue3 ref模板引用是否已支持？

### ISSUE THREAD

**Issue by Iongtao** [dcloudio/uni-app#3031]
**问题描述**
vue3开发的小程序，使用ref去获取子组件的实例调用其组件方法
在nextTick中获取不到 结果一直为null

**复现步骤**
创建const picker = ref(null)

在nextTick(() =>{ console.log(picker.value)})
结果为null

**预期结果**
正确的获取到组件的引用

**实际结果**
![image](https://user-images.githubusercontent.com/24762616/143995938-cd881af0-16d1-40e1-a50b-f4e6c8447578.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 微信小程序模拟器
 - HBuilderX版本 vue-cli
 - uni-app版本 无info脚本
 - 设备信息 微信小程序模拟iphone6

**补充信息**
无

**Comment by fxy060608** [comment]
cli 可以更新至：3.0.0-alpha-3030020211201001

**Comment by yhwork** [comment]
H5的也不支持 ref 获取子组件
