### ISSUE TITLE
【 vite 】地址格式造成打包失败

### ISSUE THREAD

**Issue by sufuWang** [dcloudio/uni-app#3034]
报错如下
```
[vite:css] The "fileName" or "name" properties of emitted files must be 
strings that are neither absolute nor relative paths, 
received "../p_static/assets/wxss/lib/iconfont/iconfont.svg".
```
将引用地址 `p_static` 改为 `static` 将不会报此错误
测试工程：https://github.com/sufuWang/uniapp_vite

**Comment by fxy060608** [comment]
资源建议放进 src 里边

**Comment by sufuWang** [comment]
> 资源建议放进 src 里边

请问有其他方法解决这个问题嘛？

**Comment by fxy060608** [comment]
> > 资源建议放进 src 里边
> 
> 请问有其他方法解决这个问题嘛？

暂不支持

**Comment by sufuWang** [comment]
好的，谢谢

> > > 资源建议放进 src 里边
> > 
> > 
> > 请问有其他方法解决这个问题嘛？
> 
> 暂不支持

好的，谢谢
