### ISSUE TITLE
App.vue不能触发setup吗？动态设置样式也不生效

### ISSUE THREAD

**Issue by aloha66** [dcloudio/uni-app#3039]
**问题描述**
1. 在App.vue里面加入setup函数,没有输出333333
2. 基于1，改用data，然后观察页面样式变化
![image](https://user-images.githubusercontent.com/20942781/144215297-26c2dea3-9931-44ce-845f-458aaa6fd0e5.png)
3. 一样的代码在/page/index/index.vue表现正常

背景：想使用vue3新特性Dynamic CSS来改变颜色。个人对App.vue的理解是可以配置全局样式

**复现步骤**

```vue
// App.vue
<script>
export default {
  data() {
    return {
      color: '#ee2f30',
    }
  },
  setup() {
    console.log(33333333333333)
  },
  onLaunch: function () {
    console.log('App Launch')
  },
}
</script>
<style>
/*每个页面公共css */
.color {
  color: v-bind(color);
}
</style>
```
```vue
// page/index/index.vue
  <view class=" color">ttt </view>
```

**预期结果**
1. 会触发setup
2. 颜色变成红色

**实际结果**
不能触发setup，颜色没有变化

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台]
 - 操作系统 win10
 - uni-app版本 "@dcloudio/uni-h5": "^3.0.0-alpha-3030020211124001",
    "@dcloudio/uni-mp-weixin": "^3.0.0-alpha-3030020211124001",

**Comment by fxy060608** [comment]
App.vue 暂不支持 v-bind 样式
