### ISSUE TITLE
小程序真机调试弹出reporter error:Converting circular structure to JSON

### ISSUE THREAD

**Issue by paresseuxxx** [dcloudio/uni-app#304]
小程序真机调试时使用自定义组件后出现reporter error:Converting circular structure to JSON，自定义组件里面包含swiper，当swiper滑动一次就会出现一次，在开发工具以及h5端并不会出现

再次测试发现调用uni组件scroll-view执行绑定事件@scrolltolower小程序真机测试就会触发reporter error:Converting circular structure to JSON，是否所有组件的@绑定方法都会出现该问题，请问有解决办法吗

**Comment by xiaoyucoding** [comment]
1.9.3 更新已修复此问题

+ 微信小程序 修复 swiper scroll-view 等组件绑定事件在 vconsole 中报 JSON 序列化错误的问题 [详情](https://ask.dcloud.net.cn/question/69277)
