### ISSUE TITLE
hbuilder正式版 H5 打包有bug, 升级到Hbuilder Alpha 3.3.0，uni.showToast 真机显示不出来

### ISSUE THREAD

**Issue by 734839030** [dcloudio/uni-app#3040]
PC chrome 可以显示，android QQ 浏览器 华为浏览器 微信内打开也不行
uni.showToast({
icon: 'error',
title: '请签名'
})

**Comment by fxy060608** [comment]
如果是vue3,请注明

**Comment by StrivingRabbit** [comment]
已有关联问题 #3038 此 issue 关闭
