### ISSUE TITLE
vue3 vite编译到小程序 import 文件不加后缀 .js 报错

### ISSUE THREAD

**Issue by fangshikeji** [dcloudio/uni-app#3041]
![image](https://user-images.githubusercontent.com/76583297/144558417-e636eb7a-7e9b-41f4-b288-55cecff7d530.png)
系统：win10

**Comment by fxy060608** [comment]
未重现，可以发一个测试工程

**Comment by fangshikeji** [comment]
[https://codechina.csdn.net/weixin_41947370/test](url)

编译到h5没有问题

**Comment by fxy060608** [comment]
> https://codechina.csdn.net/weixin_41947370/test

你发的地址访问不了，确保该仓库是对外的

**Comment by fangshikeji** [comment]
> 

是公开的，我让同事试了下可以打开
