### ISSUE TITLE
怎么获取 package.json 里面的 version信息

### ISSUE THREAD

**Issue by wavesbig** [dcloudio/uni-app#3045]
**问题描述**
 使用process.env并未看到相关信息

**Comment by Husky-Yellow** [comment]
package.json就是一个json文件，使用webpack的话，可以直接require进来

**Comment by 569202812** [comment]
> 

我想在vue或者main.js里面引用

**Comment by Husky-Yellow** [comment]
看这个

```
const packageName = require('../package.json').name

const version = require('../package.json').version

console.log('packageName---',packageName);

console.log('version---',version);
```

![image](https://user-images.githubusercontent.com/50540342/144993074-b5673ecf-8c64-4cb9-bc4c-d4b398563a58.png)

![image](https://user-images.githubusercontent.com/50540342/144993039-16ba3b18-f800-42e6-a5b3-9aa7b6f81acc.png)

**Comment by 569202812** [comment]
> 看这个
> 
> ```
> const packageName = require('../package.json').name
> 
> const version = require('../package.json').version
> 
> console.log('packageName---',packageName);
> 
> console.log('version---',version);
> ```
> 
> ![image](https://user-images.githubusercontent.com/50540342/144993074-b5673ecf-8c64-4cb9-bc4c-d4b398563a58.png)
> 
> ![image](https://user-images.githubusercontent.com/50540342/144993039-16ba3b18-f800-42e6-a5b3-9aa7b6f81acc.png)

好的俺试试
