### ISSUE TITLE
vite 打包中引入 unplugin-auto-import/vite 报错

### ISSUE THREAD

**Issue by sufuWang** [dcloudio/uni-app#3046]
使用自动引入插件 `unplugin-auto-import\vite` 和 `vue-global-api` 时，项目报错，报错如下
```
'onServerPrefetch' is not exported by node_modules/vue-demi/lib/index.mjs, 
imported by node_modules/vue-global-api/onServerPrefetch.mjs
```
vue@3.1+ 中已经解决了此 bug ，在 uni-app vite 中使用此插件会复现此 bug ，请问 uni-app vite 版本是否不支持此插件？
测试工程：https://github.com/sufuWang/uniapp_vite/tree/feature/autoImport
ps：使用 vite 新起一个项目，使用此插件并不会出现此 bug

**Comment by sufuWang** [comment]
大佬，这个发布了嘛?

**Comment by fxy060608** [comment]
> 大佬，这个发布了嘛?

已发布：3.0.0-alpha-3030020211206001
