### ISSUE TITLE
vue3 vite编译到小程序通过ref无法获取到元素

### ISSUE THREAD

**Issue by fangshikeji** [dcloudio/uni-app#3048]
![image](https://user-images.githubusercontent.com/76583297/144804133-1e03734e-d7dc-4d99-9523-0054dc099555.png)

测试工程：https://codechina.csdn.net/weixin_41947370/test

**Comment by fxy060608** [comment]
#3031

**Comment by mlsjla** [comment]
测试小程序还是不支持
