### ISSUE TITLE
使用 vue3 + vite 脚手架创建的微信小程序项目，npm link 了一个本地的组件库项目，启动小程序后报错

### ISSUE THREAD

**Issue by linzebingo** [dcloudio/uni-app#3049]
**问题描述**
使用 vue3 + vite 脚手架创建的微信小程序项目，npm link 了一个本地的组件库项目，启动小程序后报错

**复现步骤**
1.  创建项目
2. npm link uni-ui
3.  配置了 pages.json 中的 easycom
4. 配置了 vite.config.js 中的 alias
5. 启动项目，npm run dev:mp-wexin
6. 命令行控制台报错

**预期结果**
预期，不报错，可运行

**实际结果**
`发生异常: Error: Invalid pattern "../../uni-ui/components/z-cell/z-cell.js" for "output.chunkFileNames", patterns can be neither absolute nor relative paths.`

**系统信息:**
 - 发行平台:微信小程序
 - 操作系统: MacOS 11.6
 - uni-app版本：3.0.0-alpha-3030020211201003

**补充信息**
H5 启动不报错，npm install 组件库后不报错，基本断定是 uni-mp-vite 出了问题
node_modules/@dcloudio/uni-mp-vite/dist/plugin/build.js#110

![image](https://user-images.githubusercontent.com/12185104/144814712-95bfea02-8a87-484a-924d-c79816d50b36.png)

**Comment by fxy060608** [comment]
目前不支持link，编译到小程序平台时，组件，页面等目录结构需要与原始目录保持一致，当你引用的资源不在项目目录内，就会出现此问题。

**Comment by linzebingo** [comment]
@fxy060608 

> 目前不支持link，编译到小程序平台时，组件，页面等目录结构需要与原始目录保持一致，当你引用的资源不在项目目录内，就会出现此问题。

@fxy060608 我暂时是这么解决的 o(╯□╰)o
文件：node_modules/@dcloudio/uni-cli-shared/dist/utils.js#58
加入代码：str = str.replace(/\.\.\//g,'')

![image](https://user-images.githubusercontent.com/12185104/144816755-7db989f6-b949-42c9-84bc-9553b24b4797.png)

**Comment by linzebingo** [comment]
请问有支持的计划吗？

**Comment by fxy060608** [comment]
> 请问有支持的计划吗？

1. 升级 vite 版本至2.7.0-beta.11
2. vite.config.js 中配置：
```js
resolve: {
    preserveSymlinks: true,
  },
```

**Comment by linzebingo** [comment]
林某人已收到您的邮件了:)
