### ISSUE TITLE
uni.openLocation返回没有回调!

### ISSUE THREAD

**Issue by JohyC** [dcloudio/uni-app#3050]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
        openLocation(params) {
            const latitude = +params.latitude;
            const longitude = +params.longitude;
            uni.openLocation({
                latitude,
                longitude,
                name: params.shopName || params.title || params.name,
                success(res) {
                    console.log('openLocation success', res);
                    params.success && params.success();
                },
                fail(err) {
                    console.log('openLocation fail', err);
                    params.fail && params.fail();
                },
                complete() {
                    params.complete && params.complete();
                }
            });
        },
//调用
            this.openLocation({
                latitude: this.latitude,
                longitude: this.longitude,
                name: this.name,
                fail() {
                    console.log('return or openLocation fail');
                }
            });

**预期结果**

![image](https://user-images.githubusercontent.com/38210128/144969132-dd4c8ffc-d911-4944-81d2-35fc9838f0e8.png)

**实际结果**

文档说导航返回的时候也会进去fail会调用，但实际没有任何作用！！！

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - -- app h5
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - -- Android 7.0
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - -- HBuilderX3.2.16
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
设计并非如此
