### ISSUE TITLE
官方是否有考虑对uni-app的项目或组件输出到普通web项目做支持

### ISSUE THREAD

**Issue by torns** [dcloudio/uni-app#3051]
**新功能描述**
官方是否有考虑对uni-app的项目或组件输出到普通web项目做支持

**现状及问题**
现在我们团队在利用uni-app做可视化设计器时, 有对现有uni-app体系内的UI库输出到普通vue ui库的需求, 以便uni-ui能脱离uni-app编译环境中使用

**Comment by Otto-J** [comment]
感谢反馈。

技术上是可行的。需要注意的是小程序运行环境和 h5 浏览器运行环境相比，小程序不能访问 window 操作 dom，处理插槽等细节和 vue 存在差异，而且小程序平台始终在高速迭代，某些 api 比如登录、获取用户信息等会时长变化。

如果考虑做成跨平台的组件库，技术上是可行的。https://github.com/dcloudio/uni-ui 是官网做的组件库，可以运行在多端，可以参考。
