### ISSUE TITLE
ReferenceError: performance is not defined

### ISSUE THREAD

**Issue by aloha66** [dcloudio/uni-app#3056]
**问题描述**
yarn dev:h5之后报错，页面无法打开

**复现步骤**
1. yarn
2. yarn dev:h5
3. 查看

**预期结果**
没有报错

**实际结果**
![image](https://user-images.githubusercontent.com/20942781/145155751-6a1a20df-cc9d-4e14-bb40-c9182edf574f.png)

**系统信息:**
 - 发行平台: h5
 - 操作系统 win10
 - uni-app版本 
 -  "@dcloudio/uni-h5": "^3.0.0-alpha-3030020211207001",
 - "@dcloudio/vite-plugin-uni": "^3.0.0-alpha-3030020211207001",

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030020211208001

**Comment by bosens-China** [comment]
问题依然存在
