### ISSUE TITLE
input type为number 问题

### ISSUE THREAD

**Issue by afsdfsdf232** [dcloudio/uni-app#3058]
华为鸿蒙系统页面多个表单输入框，type都为number时候，当在第一个input框输入完时未关闭键盘，直接点击第二个input框，会出现汉字键盘。期望出现的是数字键盘。

![image](https://user-images.githubusercontent.com/37952670/145320401-ef861701-8cb2-4c9f-96f3-801aca1fd1fd.png)

**Comment by StrivingRabbit** [comment]
在其他设备上是否可以复现此问题？苹果或者其他 Android 设备

**Comment by afsdfsdf232** [comment]
安卓和ios没问题，鸿蒙系统有这个问题

**Comment by StrivingRabbit** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    好的，了解了。后续排查一下
