### ISSUE TITLE
uni.request不能返回Promise

### ISSUE THREAD

**Issue by zengyuanqiu** [dcloudio/uni-app#306]
HX 版本为 1.9.1 20190415

![image](https://user-images.githubusercontent.com/30031554/56256981-66d8fe00-60fd-11e9-9e48-5e067b239e47.png)
![image](https://user-images.githubusercontent.com/30031554/56256909-2b3e3400-60fd-11e9-801f-51d883712af6.png)

**Comment by xiaoyucoding** [comment]
1.9.2 已修复此问题
