### ISSUE TITLE
vue3.0组件里调用不了微信小程序onShareAppMessage的方法,怎么解决

### ISSUE THREAD

**Issue by xiangtaot** [dcloudio/uni-app#3061]

**Comment by fxy060608** [comment]
1. 首先需要在页面中定义onShareAppMessage或者自己全局mixin进去（可以是空方法以此来告知小程序此页面支持分享）
2. 组件内
```js
import { onShareAppMessage } from '@dcloudio/uni-app'
onShareAppMessage(()=>{
return {title:'hello'}
})
```

**Comment by xiangtaot** [comment]
这样写我试过的,没有调用的,需要用vue2.0的写法才会生效


| |
15972847938
|
|
***@***.***
|
签名由网易邮箱大师定制


在2021年12月15日 ***@***.***> 写道：

首先需要在页面中定义onShareAppMessage或者自己全局mixin进去（可以是空方法以此来告知小程序此页面支持分享）
组件内
***@***.***/uni-app'onShareAppMessage(()=>{return{title:'hello'}})

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by fxy060608** [comment]
注意事项：
1. cli更新至最新
2. 必须在页面里主动声明onShareAppMessage生命周期之后，才可以在组件中使用
页面
```js
export default {
onShareAppMessage(){}
}
```
组件
```js
import { onShareAppMessage } from '@dcloudio/uni-app'
onShareAppMessage(()=>{
return {title:'hello'}
})
```
