### ISSUE TITLE
checkbox checked值发生改变，但是选中的状态未改变

### ISSUE THREAD

**Issue by webzhiou** [dcloudio/uni-app#3062]
checkbox checked值发生改变，但是选中的状态未改变
checkbox checked值发生改变，但是选中的状态未改变

**Comment by StrivingRabbit** [comment]
提供运行环境，提供可复现的简单示例

**Comment by AnKangZhouWei** [comment]
> 提供运行环境，提供可复现的简单示例
比如购物车功能，顶部一个全选，列表有单选，反复切换测试，有时候会出现，
当我选择全选的时候，改变了checked状态，都是true，但是选中的状态未改变，没有勾选

**Comment by StrivingRabbit** [comment]
@AnKangZhouWei 这么描述我是定位不了问题的

**Comment by AnKangZhouWei** [comment]
> @AnKangZhouWei 这么描述我是定位不了问题的

![1640765688(1)](https://user-images.githubusercontent.com/34094293/147641368-84fc7f7a-da0d-4b21-83fe-ddcb65007c8f.png)
![1640765734(1)](https://user-images.githubusercontent.com/34094293/147641390-b381c3fa-5f10-430c-b916-9f14aa73069e.png)

**Comment by AnKangZhouWei** [comment]
动态去切换checkbox的选中状态的值，值改变了，状态未改变

**Comment by StrivingRabbit** [comment]
@AnKangZhouWei 在 `data` 中定义的 `cartList` ，每个都有 `checked` 属性吗？如果没有请使用 `this.$set` 来改变 `checked` 属性。否则无法观测到变量的更改

**Comment by AnKangZhouWei** [comment]
> @AnKangZhouWei 在 `data` 中定义的 `cartList` ，每个都有 `checked` 属性吗？如果没有请使用 `this.$set` 来改变 `checked` 属性。否则无法观测到变量的更改。可以看一下hello uni-app的示例

早都试过了，还是不得行，checked值为true，勾选的状态未显示勾选状态

**Comment by StrivingRabbit** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    提供一个小的示例，可以复现的demoMessage ID: ***@***.***>
