### ISSUE TITLE
vite vue3项目如何修改子组件样式？

### ISSUE THREAD

**Issue by Iongtao** [dcloudio/uni-app#3063]
**问题描述**
vite vue3项目如何修改子组件样式？
style使用scss预处理

使用 /deep/ 无效 编译错误 大概vue3不支持？
![image](https://user-images.githubusercontent.com/24762616/145347693-4845c9e9-8396-4c9e-8840-7e0379f5c726.png)
![image](https://user-images.githubusercontent.com/24762616/145347782-67041ff5-61e2-426e-909a-b1776e4285c1.png)

使用:deep() 编译成功 但无效果
![image](https://user-images.githubusercontent.com/24762616/145347626-58b3b5e2-44f7-4f65-b522-f508d02707a4.png)

**复现步骤**
使用vite+vue3+scss
在父组件中修改子组件样式 无效
style使用了scoped关键字

**预期结果**
修改子组件样式成功

**实际结果**
修改失败
![image](https://user-images.githubusercontent.com/24762616/145348022-2dc9949e-112a-4800-85ea-eb885c954cc4.png)
![image](https://user-images.githubusercontent.com/24762616/145348046-4aed0f7f-b7bb-4622-a1fb-edb2cfecefc4.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 微信小程序模拟器
 - HBuilderX版本 cli
 - uni-app版本 无
 - 设备信息 模拟iphone6

**补充信息**
无

**Comment by fxy060608** [comment]
小程序默认只能页面穿透到组件，不能组件穿透到组件

**Comment by Iongtao** [comment]
> 小程序默认只能页面穿透到组件，不能组件穿透到组件

哦对 谢谢
