### ISSUE TITLE
微信小程序 map组件的 includePoints api 和 setting.skew 属性不能共用，会影响地图缩放

### ISSUE THREAD

**Issue by RunningTree** [dcloudio/uni-app#3064]
**问题描述**
微信小程序 map组件的 includePoints api 和 setting.skew 属性不能共用，会影响地图缩放

**复现步骤**
1.在map组件设置setting.skew
2.调用mapContext.includePoints Api

**预期结果**
地图缩放到正确比例，地图上的多个标记点全部显示出来

**实际结果**
在小程序界面，地图先显示正确的缩放比例，接着一闪而过，然后再显示，这时marker点没有全部显示在界面上

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 Android 
 - 设备信息 一加6

**Comment by StrivingRabbit** [comment]
使用微信小程序原生测试，是否有这个问题？

**Comment by RunningTree** [comment]
> 使用微信小程序原生测试，是否有这个问题？

是的，存在这个问题，就跟我描述的一样，先是显示正确的缩放比例，接着一闪而过，然后再显示，这时marker点没有全部显示在界面上

**Comment by StrivingRabbit** [comment]
@RunningTree 建议去微信社区反馈一下这个问题
