### ISSUE TITLE
两个v-model的组件嵌套 Maximum call stack size exceeded

### ISSUE THREAD

**Issue by anianXCY** [dcloudio/uni-app#3065]
**问题描述**
钉钉小程序  两个v-model的组件嵌套  内层组件的slot 不能放view 标签或者其他组件 微信小程序 h5 都正常

**复现步骤**
[复现问题的步骤]
点击弹出按钮  报错Maximum call stack size exceeded
把test1 组件的view标签 替换为纯文本就正常

```vue
<template>
  <view>
    <test1 v-model="visibleSync"></test1>
    <button @click="testClick">弹出</button>
  </view>
</template>

<script lang="ts" setup>
import { ref } from 'vue'
import test1 from './test1.vue'
const visibleSync = ref(false)
const testClick = ()=>{
  visibleSync.value = true
}
</script>

```
test1
```vue
<template>
  <test2 v-model="visible">
//这里只能为纯文本 view标签或者其他自定义组件都报错
    <view>我是组件test2的插槽</view>
  </test2>  
</template>

<script lang="ts" setup>
import { ref, watch, defineProps } from 'vue'
import test2 from './test2.vue'
const visible = ref(false)
const props = defineProps({
  modelValue: {
    type: Boolean,
    default: false
  }
})
watch(
  () => props.modelValue,
  val => {
    visible.value = val
  }
)
</script>
```
test2
```vue
<template>
  <view v-show="visible">
  <view>我是组件test2</view>
    <slot></slot>
  </view>
</template>

<script lang="ts" setup>
import { ref, watch, defineProps } from 'vue'
const visible = ref(false)
const props = defineProps({
  modelValue: {
    type: Boolean,
    default: false
  }
})
watch(
  () => props.modelValue,
  val => {
    visible.value = val
  }
)
</script>
```
[或者可以直接贴源代码]

**预期结果**
正常显示 隐藏的内容
![image](https://user-images.githubusercontent.com/45084708/145512279-f24c6de9-931b-466b-b75a-e169c47f6034.png)

**实际结果**
![image](https://user-images.githubusercontent.com/45084708/145511540-59cb41bf-f673-428a-aa1e-0be740a61b32.png)
debug 进去发现 _owner 属性的 alternate 属性 没完没了
![image](https://user-images.githubusercontent.com/45084708/145543497-36781bfd-973a-42eb-b1b9-c881df480abc.png)

**系统信息:**

钉钉小程序开发工具  2.5.6 (2.5.6)
uni app 版本  3.0.0-alpha-3030020211201003

**补充信息**
[可选]
根据报错 进去 找到这个equal (vendor.js:5646) 方法 在@dcloudio/uni-mp-alipay/src/runtime/deepEqual.ts

**Comment by zhetengbiji** [comment]
更新到新版，如仍有问题，可再次开启此问题。
