### ISSUE TITLE
uni-app项目中使用箭头函数，在微信开发者工具中查看函数执行过程中的this变量，都显示为undefined的

### ISSUE THREAD

**Issue by georgewei** [dcloudio/uni-app#3068]
**问题描述**
如题，调试效果如图：
<img width="476" alt="1" src="https://user-images.githubusercontent.com/28130/145913901-bf268902-99ad-4152-a4d4-2a34f92134fd.png">

实际上程序可以正常执行（说明this实际上不是undefined）。这样调试很不方便，要么用console.log()方法在控制台输出想要查看的变量的值，要么在代码里为每个箭头函数声明后加上.bind(this)。之前基于VUE使用VS Code开发网页，可以使用babel-plugin-transform-es2015-arrow-functions这个插件（https://babel.docschina.org/docs/en/babel-plugin-transform-es2015-arrow-functions/ ）来让浏览器的开发者工具正常显示this变量的值。配置如下：

```
  // Add this configuration in package.json
  "devDependencies": {
    "babel-plugin-transform-es2015-arrow-functions": "^6.22.0",
  }
```

```
  // Add this configuration in ./.bablerc
  "plugins": [
    ["babel-plugin-transform-es2015-arrow-functions", { "spec": true }]
  ]
```

我参考以上配置，在uni-app项目中修改配置如下：

```
  // Add this configuration in package.json
  "devDependencies": {
    "babel-plugin-transform-es2015-arrow-functions": "^6.22.0",
  }
```

```
  // Add file ./bable.config.js
module.exports = {
	presets: ["@vue/cli-plugin-babel/preset"],
	plugins: [
		[require('@babel-plugin-transform-es2015-arrow-functions/lib/index'), { "spec": true }]
	]
}
```

在HBuilderX里重新运行程序，在微信开发者工具里调试，发现箭头函数里this变量还是显示为undefined的。我应该怎么配置才能解决这个问题呢？

**预期结果**
使用插件babel-plugin-transform-es2015-arrow-functions后，在微信开发者工具里查看箭头函数执行过程中this变量的值，this变量应该是一个有意义的对象

**实际结果**
this变量的值显示为undefined（尽管程序仍可以正常运行，但调试不便）

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: Mac OS Catanina 10.15.7
 - HBuilderX版本: 3.2.16.20211122

**Comment by yuconora** [comment]
是不是断点位置打错了 默认配置使用箭头函数没问题的

**Comment by georgewei** [comment]
箭头函数执行没问题，在微信开发者工具里单步调试this变量显示为undefined，不方便。希望能解决这个问题

**Comment by StrivingRabbit** [comment]
@georgewei 断点打在执行箭头函数的地方调试下看看
