### ISSUE TITLE
fix(vue3-vite): wxs 打包失败 

### ISSUE THREAD

**Issue by sufuWang** [dcloudio/uni-app#3069]
vue 文件中包含如下 script ，会打包失败，webpack 打包正常
```html
<script module="handler" lang="wxs" src="./handler.wxs"></script>
```
测试工程：https://github.com/sufuWang/uniapp_vite
我尝试解决这个 bug ，表面上已经解决了，但不知道是 vite 的问题，还是 uni-app 的问题，所以向大佬确认一下
此 mr 可以解决此问题，但感觉这个并不是问题本身：https://github.com/vitejs/vite/pull/6106

**Comment by fxy060608** [comment]
应该就是这个问题，你可以用标准的vite+自定义块+build重现该问题

**Comment by sufuWang** [comment]
> 应该就是这个问题，你可以用标准的 vite + custom-blocks(src) + build 重现该问题

vite 中没能复现此问题

**Comment by fxy060608** [comment]
> > 应该就是这个问题，你可以用标准的 vite + custom-blocks(src) + build 重现该问题
> 
> vite 中没能复现此问题

[my-vue-app.zip](https://github.com/dcloudio/uni-app/files/7709142/my-vue-app.zip)
)

**Comment by sufuWang** [comment]
学到了

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030120211215001
