### ISSUE TITLE
Map组件 polygons 

### ISSUE THREAD

**Issue by c1394393468** [dcloudio/uni-app#307]
**新功能描述**
Map组件基础功能完善，polygons支持。
微信小程序 关于map组件的文档
https://developers.weixin.qq.com/miniprogram/dev/component/map.html
支付宝小程序 关于map组件的文档
https://docs.alipay.com/mini/component/map

**现状及问题**
目前微信和支付宝小程序都是支持 polygons 的，不太清楚是文档错误还是没实现该功能。
绘制多边形为map组件基础能力支持，没有该能力很多功能将无法实现。

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]
如果官方未实现，是否可以自己实现并增强map组件(或者更多组件)的能力？

**补充信息**
[其它你认为有参考价值的信息]

**Comment by c1394393468** [comment]
uni-app map文档中 并未有关于polygons的描述，但实际按照微信小程序的写法依然可以实现。暂时未运行到其他平台测试

**Comment by xiaoyucoding** [comment]
1.9.3 更新

+ App平台 自定义组件模式 新增 获取原生地图对象的方法 MapContext.$getAppMap() [详情](https://uniapp.dcloud.io/api/location/map?id=createmapcontext)

通过该 API 获取到原生地图对象后，调用相应的方法添加覆盖物实现。

**Comment by jonahzheng** [comment]
微信小程序下好像无法使用

**Comment by bxpxqxd** [comment]
> 微信小程序下好像无法使用

你的结论和楼主相悖内

**Comment by jonahzheng** [comment]
@bxpxqxd MapContext.$getAppMap()  这个只有原生和h5+ 下才能用
用uni-app的map组件，添加polygons无效

**Comment by bxpxqxd** [comment]
> @bxpxqxd MapContext.$getAppMap() 这个只有原生和h5+ 下才能用
> 用uni-app的map组件，添加polygons无效

仔细看一楼，楼主说的是 polygons 属性
