### ISSUE TITLE
【cli版本3.0.0-alpha-3030120211215001】 defineProps接受参数为undefined

### ISSUE THREAD

**Issue by moke8** [dcloudio/uni-app#3079]
**问题描述**
版本从3030020211201003更新到了3030120211215001后
无论是页面之间传参还是组件传参
defineProps接受参数为undefined

**复现步骤**
const props = defineProps(['id'])
console.log(props)

**预期结果**
id: 10003

**实际结果**
 id: undefined

**系统信息:**
 - 发行平台: 微信小程序
 - uni-app版本 ^3.0.0-alpha-3030120211215001

**Comment by moke8** [comment]
刚刚发现getCurrentInstance取得的值也变成null了，是缺少什么依赖吗

**Comment by fxy060608** [comment]
> 刚刚发现getCurrentInstance取得的值也变成null了，是缺少什么依赖吗

目前测试，仅页面defineProps获取页面参数有bug，组件defineProps是没问题的，getCurrentInstance也没问题，你可以发一个能重现的测试工程

**Comment by moke8** [comment]
代码片段： https://github.com/moke8/bug-test

**Comment by moke8** [comment]
详细测试了，确实是页面的defineProps无法接收，组件确实是可以的，因为页面没有id所以传的值也是空所以理解错误了

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030120211216001
注意事项：目前页面 defineProps，在 setup 中接收页面参数，仅h5,app,微信小程序支持，其他平台均未支持

**Comment by moke8** [comment]
更新后可以了，感谢！
getCurrentInstance还是不行，但是目前影响不大

另外一直有一个问题就是编译模式无效，在pages.json中设置condition，编译出的project.config.json对应内容为空数组，这个问题我需要单独提一个bug吗？

代码片段是： https://github.com/moke8/bug-test

**Comment by fxy060608** [comment]
> https://github.com/moke8/bug-test

getCurrentInstance是用法问题，该方法，只能在setup和生命周期中使用
详情参考：https://v3.cn.vuejs.org/api/composition-api.html#getcurrentinstance

**Comment by moke8** [comment]
好的，condition有时间可以优化一下吗，调试的时候会方便很多

**Comment by fxy060608** [comment]
> 好的，condition有时间可以优化一下吗，调试的时候会方便很多

已修复，cli更新至：3.0.0-alpha-3030120211216002

**Comment by moke8** [comment]
没有问题了，感谢！
