### ISSUE TITLE
h5和微信小程序在使用全局组件上表现不一致

### ISSUE THREAD

**Issue by Eline2017** [dcloudio/uni-app#308]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
1.h5引入底部导航栏的全局组件后，多次点击切换无问题；
2.微信小程序引入导航栏的全局组件后，多次点击后无法跳转到相对应的页面

**预期结果**
两者表现一致

**系统信息:**
 - 发行平台:微信小程序、H5平台
 - 操作系统 ：chrome移动端模拟器、微信开发者工具（v1.02.1904090）

 - HBuilderX版本 ：
![image](https://user-images.githubusercontent.com/23447167/56272684-cd761000-612d-11e9-8cea-883b50338a5b.png)
 
附源码：

[test-uni-app - 副本.zip](https://github.com/dcloudio/uni-app/files/3088625/test-uni-app.-.zip)

**Comment by mehaotian** [comment]
肯定不能用 navigateTo 啊 ，小程序是有打开页面限制的。 可以使用 redirectTo 。

**Comment by Eline2017** [comment]
好的，谢谢
