### ISSUE TITLE
【vite】编译失败，wx语法错误

### ISSUE THREAD

**Issue by sufuWang** [dcloudio/uni-app#3080]
测试工程：https://github.com/sufuWang/uniapp_vite
有一个文件打包错误，文件地址 dist/build/mp-weixin/pages/test/uni-ec-canvas/uni-ec-canvas.wxml
打包后这个文件有一个语法错误
```html
<block v-if="1">
  <canvas v-if="1"></canvas>
</block>
<block v-if="1">
  <canvas v-else></canvas> // 语法错误
</block>
```
顺便想问一下，现在是不是已经可以支持 `<block>` 标签了

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030120211216001
（建议使用 template 标签）
