### ISSUE TITLE
uni.showModal可以同时弹出多个框

### ISSUE THREAD

**Issue by maixiachen** [dcloudio/uni-app#3081]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
 app 真机情况下，uni.showModal 叠加显示。H5环境下没有这种情况。
**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 Android
 - HBuilderX版本 :3.2.16

**Comment by zhetengbiji** [comment]
showModal 为异步接口使用方式与同步接口的 alert 不同
