### ISSUE TITLE
vue3 setup scirpt语法使用onShareAppMessage不生效

### ISSUE THREAD

**Issue by aalexlin** [dcloudio/uni-app#3084]
**问题描述**
vue3 setup scirpt语法使用onShareAppMessage编译到微信小程序，小程序分享不生效

**实际结果**
![image](https://user-images.githubusercontent.com/6197922/146508796-432d8544-f54a-4180-a4b7-05d0e6bc4f10.png)

**系统信息:**
 - 发行平台: 微信小程序

**Comment by fxy060608** [comment]
onShareAppMessage 在页面里只能通过options的方式定义，目前暂未提供setup方式注册，

**Comment by fxy060608** [comment]
当需要在页面内使用onShareAppMessage时，目前可以同时使用script setup和script，如：
```html
<script setup>
import { ref } from 'vue'
const msg = ref('hello')
</script>
<script>
export default {
  onShareAppMessage() {
    return {}
  }
}
</script>
```

**Comment by monyee** [comment]
> 

下面的script中 如何访问上面setup中 定义的变量？

**Comment by fxy060608** [comment]
> > 
> 
> 下面的script中 如何访问上面setup中 定义的变量？

已支持在 setup 中直接使用 onShareAppMessage

**Comment by monyee** [comment]
谢谢 您的来信我稍后会回复您。

**Comment by Statfine** [comment]
@fxy060608  3.0.0-alpha-3060820221027002 版本还是会有这个问题


main.js 全局入口添加了
```
export const GlobalShare = {
  onShareAppMessage() {
    return {
      title: SHARE_DEFAULT_INFO.title,
      path: SHARE_DEFAULT_INFO.path,
      imageUrl: SHARE_DEFAULT_INFO.imageUrl,
      success() {
        uni.showToast({
          title: "分享成功",
        });
      },
      fail() {
        uni.showToast({
          title: "分享失败",
          icon: "none",
        });
      },
    };
  },
};

export function createApp() {
  const app = createSSRApp(App);
  app.use(Store);
  app.mixin(GlobalShare);
  return {
    app,
  };
}

```

页面自定义还是不生效
```
<script lang="ts" setup>
import { onShareAppMessage } from "@dcloudio/uni-app";
onShareAppMessage(() => {
  return {
    title: "自定义分享标题",
    path: "/pages/home/index",
  };
});
</script>

```

**Comment by chaner-y** [comment]
还有有这个问题 我该怎么写啊？帮帮忙

**Comment by xiangtaot** [comment]
watchRoute() {
        uni.onAppRoute((res) => {
          console.log('===>', res);
          let pages = getCurrentPages();
          let view = pages[pages.length - 1];
          if (view) {
            // console.log(view, 'aaaaaa');
            view.onShareAppMessage = function () {
              //你的分享配置
              return {
                imageUrl: '/static/img/share.png',
                title: '全局分享',
                path: '/pages/a/a',
              };
            };
          }
        });
      },
在你的App.vue，onLaunch生命周期执行这个方法即可
