### ISSUE TITLE
【vite】img 标签未被转译

### ISSUE THREAD

**Issue by sufuWang** [dcloudio/uni-app#3085]
```html
    <img class="item_video" :src="videoItems.imgUrl" />
```
打包后为
```html
    <img bind:__l="__l" class="item_video" />
```

**Comment by fxy060608** [comment]
建议使用标准的 image 组件，html组件目前暂不支持转换

**Comment by sufuWang** [comment]
大概多久之后会支持呀？webpack 迁移过来的项目改起来工作量有点大呀（改标签）

**Comment by fxy060608** [comment]
> 大概多久之后会支持呀？webpack 迁移过来的项目改起来工作量有点大呀（改标签）

就是个批量搜索替换吧，感觉没什么工作量，除非还用了什么img标签样式之类的

**Comment by sufuWang** [comment]
有可能还有其他 html 标签呀

**Comment by sufuWang** [comment]
主要是想问，有没有支持 html 的计划，如果有的话，大概什么版本可以上

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030220211217003
注意事项：目前仅转换标签，如果css里边用了标签样式，是不会转换的

**Comment by sufuWang** [comment]
> 已修复，cli更新至：3.0.0-alpha-3030220211217003 注意事项：目前仅转换标签，如果css里边用了标签样式，是不会转换的

好的，大佬的速度好快

**Comment by sufuWang** [comment]
大佬，我用的 @dcloudio/uni-app@3.0.0-alpha-3030220211217004 依旧出现这个问题
```
"@dcloudio/uni-app@3.0.0-alpha-3030220211217004":
  version "3.0.0-alpha-3030220211217004"
  resolved "https://mirrors.tencent.com/npm/@dcloudio%2funi-app/-/uni-app-3.0.0-alpha-3030220211217004.tgz#b2274148c50c1ef81483d67ec58e0ee39cb06104"
  integrity sha512-NvnwSlUPQSrbhly+W1jmF8MfL05x3EHU8U7YiBOnt9M/tZ3l4b1W8kJpEPFzWoMN0B0EyXp5JdkqZMClSmVd1A==
  dependencies:
    "@dcloudio/uni-cloud" "3.0.0-alpha-3030220211217004"
    "@dcloudio/uni-components" "3.0.0-alpha-3030220211217004"
    "@dcloudio/uni-i18n" "3.0.0-alpha-3030220211217004"
    "@dcloudio/uni-shared" "3.0.0-alpha-3030220211217004"
    "@dcloudio/uni-stat" "3.0.0-alpha-3030220211217004"
    "@vue/shared" "3.2.26"
```

**Comment by sufuWang** [comment]
大佬，样式其实也需要转换，请问哪里可以看到每个版本的修复内容呀 ？这样就不用专门提个 issue 来问了

**Comment by fxy060608** [comment]
> 大佬，样式其实也需要转换，请问哪里可以看到每个版本的修复内容呀 ？这样就不用专门提个 issue 来问了

暂未计划提供，浪费编译速度，增加包体积

**Comment by sufuWang** [comment]
> uni-app 是一个使用 Vue.js 开发所有前端应用的框架，开发者编写一套代码，可发布到iOS、Android、Web（响应式）、以及各种小程序（微信/支付宝/百度/头条/飞书/QQ/快手/钉钉/淘宝）、快应用等多个平台

不忘初心啊，大啦，不能转换样式，如何做到上述这点 ？

**Comment by fxy060608** [comment]
> > uni-app 是一个使用 Vue.js 开发所有前端应用的框架，开发者编写一套代码，可发布到iOS、Android、Web（响应式）、以及各种小程序（微信/支付宝/百度/头条/飞书/QQ/快手/钉钉/淘宝）、快应用等多个平台
> 
> 不忘初心啊，大佬，不能转换样式，如何做到上述这点 ？
使用我们的组件才跨平台，你使用html组件，没法完全跨平台

**Comment by sufuWang** [comment]
我理解的是 uni-app 升级，不能丢失原有的功能，webpack 中可以支持的，vite 也应该可以支持，老项目使用新工具打包，不应该修改代码去支持打包工具升级。如果大佬考虑一些其他东西去强制用户修改代码，可以讲明白，后期按照大佬的计划走即可

**Comment by fxy060608** [comment]
> 我理解的是 uni-app 升级，不能丢失原有的功能，webpack 中可以支持的，vite 也应该可以支持，老项目使用新工具打包，不应该修改代码去支持打包工具升级。如果大佬考虑一些其他东西去强制用户修改代码，可以讲明白，后期按照大佬的计划走即可

大版本升级是存在部分不兼容的，就像vue2升级到vue3，稍后文档会补充完善此类说明

**Comment by sufuWang** [comment]
> > 我理解的是 uni-app 升级，不能丢失原有的功能，webpack 中可以支持的，vite 也应该可以支持，老项目使用新工具打包，不应该修改代码去支持打包工具升级。如果大佬考虑一些其他东西去强制用户修改代码，可以讲明白，后期按照大佬的计划走即可
> 
> 大版本升级是存在部分不兼容的，就像vue2升级到vue3，稍后文档会补充完善此类说明

好的
