### ISSUE TITLE
ref模板引用不支持访问使用<script setup> 的子组件定义的属性

### ISSUE THREAD

**Issue by Sexy6God** [dcloudio/uni-app#3087]
**问题描述**
vue3微信小程序中，ref模板引用不支持访问使用<script setup> 的子组件定义的属性

**复现步骤**

Hello组件
```vue
<template>
  <view class="hello">{{title}}</view>
</template>

<script setup lang="ts">
import {ref} from 'vue'
const title = ref('HELLO')
</script>
```

```vue
<template>
  <view class="content">
    <image class="logo" src="/static/logo.png" />
    <view class="text-area">
      <Hello ref="child" />
    </view>
  </view>
</template>

<script setup lang="ts">
import {ref,nextTick} from 'vue'
import {onLoad} from '@dcloudio/uni-app'
const child: any = ref(null)
onLoad(() => nextTick(() => console.log('child title:',child.value.title)))
</script>
```

**实际结果**
<img width="454" alt="截屏2021-12-19 上午11 08 27" src="https://user-images.githubusercontent.com/86021729/146662268-b96575ac-ae0a-478f-8af2-c6b9e714e958.png">

**系统信息:**
 - 发行平台: 微信小程序
 - uni-app版本 : 3.0.0-alpha-3030220211217003

**Comment by fxy060608** [comment]
用法问题，<script setup> 里边定义的内容默认不会暴露的，若想暴露，请使用 `defineExpose`
详情参考：https://v3.cn.vuejs.org/api/sfc-script-setup.html#defineexpose
另外建议在onReady或onMounted生命周期里访问ref

**Comment by Sexy6God** [comment]
#

> 用法问题，<script setup> 里边定义的内容默认不会暴露的，若想暴露，请使用 `defineExpose` 详情参考：https://v3.cn.vuejs.org/api/sfc-script-setup.html#defineexpose 另外建议在onReady或onMounted生命周期里访问ref

明白了
