### ISSUE TITLE
canvas 添加图片显示模糊的问题

### ISSUE THREAD

**Issue by flymzero** [dcloudio/uni-app#309]
**问题描述**
在 canvas 上添加多张图片，在小程序上显示是正常的，在h5上显示模糊，网上大概查了下说

`要设置canvas的画布大小，使用的是canvas.width 和 canvas.height；  
要设置画布的实际渲染大小，使用的style或CSS设置的 width 和height，只是简单的对画布进行缩放。  
譬如：  

<canvas width="640" height="800" style="width:320px; height:400px"></canvas>  `

大概这样，但是 uni 上没有效果，不知道是不是没有这两个属性

**Comment by hbcui1984** [comment]
HBuilderX 1.9.3 已支持canvas在H5平台上的高清显示，建议更新升级。

**Comment by flymzero** [comment]
好的，谢谢
