### ISSUE TITLE
vue3的textarea无法触发bindinput事件、无法双向绑定

### ISSUE THREAD

**Issue by moke8** [dcloudio/uni-app#3090]
**问题描述**
vue3下的textarea
安卓和模拟器一切正常，IOS有问题
textarea无法双向绑定，真机调试时发现textarea的bindinput事件无法触发

**预期结果**
textarea双向绑定

**实际结果**
无法触发bindinput事件

**系统信息:**
 - 发行平台:微信小程序
 - 操作系统 IOS
 - uni-app版本 ^3.0.0-alpha-3030120211216002

**Comment by StrivingRabbit** [comment]
iOS 使用的 v-model 吗？贴一下你的代码看看

**Comment by moke8** [comment]
<textarea
      class="textarea"
      v-model="content"
      placeholder-class="textarea_pl"
      placeholder="请填写10个字以上的问题描述，以便我们能更好地帮您解决问题"
      maxlength="150"
  ></textarea>

const content = ref('')

**Comment by moke8** [comment]
<textarea
                class="textarea"
                v-model="content"
                placeholder-class="textarea_pl"
                placeholder="请填写10个字以上的问题描述，以便我们能更好地帮您解决问题"
                maxlength="150"
            ></textarea>
            <text class="word-num">{{ content.length }}/150</text>


const content = ref('')

我在编辑器里更改过编译出来的bindinput对应事件，加了一个console.log，在调试时无输出

**Comment by StrivingRabbit** [comment]
@moke8 有没有什么报错信息？

**Comment by StrivingRabbit** [comment]
@moke8 将包升级至 `3.0.0-alpha-3030220211217002` 使用吧。这个版本实测没有问题

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030420211227003

**Comment by bihongbin3027** [comment]
我现在也遇到了这个问题 textarea绑定v-model不起作用，已经更新uniapp到最新版本了，还是不行，请问你是如何解决的？

**Comment by AprilLemon** [comment]
> 我现在也遇到了这个问题 textarea绑定v-model不起作用，已经更新uniapp到最新版本了，还是不行，请问你是如何解决的？

一样，目前解决方案就是：用form标签嵌套，textarea@blur 事件重新赋值，提交按钮用form的@submit

**Comment by bihongbin3027** [comment]
@AprilLemon 我现在用了别的组件代替，目前没什么问题了

**Comment by AprilLemon** [comment]
@bihongbin3027 分享一下哪个组件哈

**Comment by bihongbin3027** [comment]
@AprilLemon https://uniapp.dcloud.net.cn/component/uniui/uni-easyinput.html#

**Comment by AprilLemon** [comment]
> @AprilLemon https://uniapp.dcloud.net.cn/component/uniui/uni-easyinput.html#

多谢
