### ISSUE TITLE
最新的vue3+vite+ts模板如何支持pinia和windicss

### ISSUE THREAD

**Issue by Miofly** [dcloudio/uni-app#3091]
最新的vue3+vite+ts模板如何支持pinia和windicss
经测试 H5 上两个库都可以使用，但小程序端都会报错

**Comment by fxy060608** [comment]
发测试工程

**Comment by Miofly** [comment]
> 发测试工程

https://github.com/Miofly/vue3-vite-uniapp

**Comment by fxy060608** [comment]
> > 发测试工程
> 
> https://github.com/Miofly/vue3-vite-uniapp

移除一下配置，重试
```js
build: {
			rollupOptions: {
				external: ['vue-demi']
			}
		},
		optimizeDeps: {
			exclude: [
				'vue-demi'
			]
		}
```

**Comment by Miofly** [comment]
> Reference in new issue

![image](https://user-images.githubusercontent.com/42859910/146769883-1d5a9137-2ec6-45fc-bc50-9d3a60f64943.png)
只会在小程序启动这样，h5不会，移除 build 配置会报如图所示错误

**Comment by fxy060608** [comment]
> 你的node版本是多少？升级到16试试，我这里测试没问题



> > Reference in new issue
> 
> 只会在小程序启动这样，h5不会，移除 build 配置会报如图所示错误。小程序端同样还不支持 windicss ![image](https://user-images.githubusercontent.com/42859910/146769883-1d5a9137-2ec6-45fc-bc50-9d3a60f64943.png)

你的node版本是多少？升级到16试试，我这里测试没问题

**Comment by Miofly** [comment]
> windicss的问题，引入的时候，可以指定layer，不要引入base 如：
> 
> ```js
> import 'virtual:windi-components.css'
> import 'virtual:windi-utilities.css'
> ```

可以了。经过测试如果是用 pnpm 安装的包，就会出现上方的报错情况。使用 yarn 去安装就没这种情况了。谢谢大佬

**Comment by psrx** [comment]
pinia是不是还不能用?

**Comment by psrx** [comment]
你的windicss也正常运行吗?
小程序不支持选择器中出现\,这就导致选择器里不能用特殊符号
但是windicss很多骚操作全用的这个选中的比如 bg-[red]

**Comment by psrx** [comment]
pinia可以用,只需要手动装个vue-demi就好了
`npm i -D vue-demi`
pnpm应该是判断了当前项目的依赖,如果是vue3就不装这个

**Comment by Miofly** [comment]
> 你的windicss也正常运行吗? 小程序不支持选择器中出现,这就导致选择器里不能用特殊符号 但是windicss很多骚操作全用的这个选中的比如 bg-[red]

windicss简单的属性可以用带有特殊符号的就别想了

**Comment by yoyo837** [comment]
在taro上成功启用,但taro还不支持style scoped, 就很难受.
