### ISSUE TITLE
【vite】请问如何降低 es 版本呀？

### ISSUE THREAD

**Issue by sufuwang** [dcloudio/uni-app#3092]
大佬，请问如何对高版本的 js 语法进行转译呀 ？比如 String.replaceAll ，低版本的微信基础库就不支持，如何对高版本语法进行转译呀？尝试了`rollup-plugin-babel`，但是打包失败，是不是小程序不支持呀？

**Comment by ModyQyW** [comment]
试试 [@vitejs/plugin-legacy](https://www.npmjs.com/package/@vitejs/plugin-legacy)？

**Comment by ModyQyW** [comment]
不能直接用 @vitejs/plugin-legacy，但应该可以这样用。

```ts
// vite.config.ts
import uni from '@dcloudio/vite-plugin-uni';

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    uni({
      vueOptions: {
        reactivityTransform: true,
      },
      viteLegacyOptions: {
        targets: ['android >= 6', 'ios >= 10'],
      },
    }),
  ],
});

```

**Comment by sufuwang** [comment]
> `uni-app` 官方没有给出说明，`vite` 文档有相关说明。现在假设 `uni-app` 的构建遵循 `vite` 本身的说明。
> 
> 首先考虑 `build.target`。`vite` 使用的默认值 `modules` 可能过高，可以考虑设置成 `es2015`，也就是 `es6`。
> 
> 其次，`vite` 底层使用了 `esbuild`，而 `esbuild` 不能直接转译代码到 `es5` 或以下，所以必要时用 `@vitejs/plugin-legacy` 转译。
> 
> 下面是一个示例。
> 
> ```ts
> // vite.config.ts
> import uni from '@dcloudio/vite-plugin-uni';
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   build: {
>     target: 'es2015',
>   },
>   plugins: [
>     uni({
>       vueOptions: {
>         reactivityTransform: true,
>       },
>       viteLegacyOptions: {
>         targets: ['defaults', 'android >= 6', 'ios >= 10'],
>       },
>     }),
>   ],
> });
> ```
> 
> 不过既然 Vue3 都用到了 `Proxy`，转译到 `es5` 似乎不是那么必要。个人认为 `build.target` 设置到 `es2015` 应该能解决你的问题。
> 
> 参考：
> 
> * https://cn.vitejs.dev/guide/build.html#browser-compatibility
> * https://cn.vitejs.dev/config/#build-target

好的，非常感谢

**Comment by ModyQyW** [comment]
你好！这是自动回复邮件。你的邮件我已经收到，我会尽快给您回复！谢谢！Hello! This is an auto reply. I have received your email. I will respond to your email as soon as possible. Thanks!

**Comment by ModyQyW** [comment]
你好！这是自动回复邮件。你的邮件我已经收到，我会尽快给您回复！谢谢！Hello! This is an auto reply. I have received your email. I will respond to your email as soon as possible. Thanks!

**Comment by ModyQyW** [comment]
https://github.com/dcloudio/uni-app/issues/3842
