### ISSUE TITLE
自定义编译条件失败

### ISSUE THREAD

**Issue by Iongtao** [dcloudio/uni-app#3093]
**问题描述**
vite项目添加自定义编译条件无效，编译报错：XXXXX is not defined
![image](https://user-images.githubusercontent.com/24762616/146747357-e80c1f2b-5705-46c1-8d29-41c82ec13a48.png)

**复现步骤**
在package.json中添加：
![image](https://user-images.githubusercontent.com/24762616/146747410-681d8f0c-4f00-4977-8765-564b7fd4672c.png)
切配置了 scripts: "dev:weapp-prod": "uni -p dev:custom weapp-prod"
声明编译条件：
![image](https://user-images.githubusercontent.com/24762616/146747554-9512eebe-8186-4b36-9b00-4f249e22c3fa.png)
结果：
![image](https://user-images.githubusercontent.com/24762616/146747584-0d0e62af-f58a-437f-ba90-c625e65b6f18.png)

**预期结果**
自定义编译条件生效， 编译器无错误信息

**实际结果**
![image](https://user-images.githubusercontent.com/24762616/146747671-f2271a51-86f7-407d-98c4-281565500c1a.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 小程序模拟器
 - HBuilderX版本 cli项目
 - uni-app版本 无
 - 设备信息 小程序模拟器

**补充信息**
不知

**Comment by Iongtao** [comment]
中横杆被解析成了下划横杆， 使用纯大写也无效

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030220211217008
同时 package.json 的 scripts 中添加
```json
"dev:custom": "uni -p",
"build:custom": "uni build -p",
```
执行命令：
`npm run dev:custom weapp-prod`
`npm run build:custom weapp-prod`
