### ISSUE TITLE
（vue3+vite）小程序编译警告：Setting data field "uP" to undefined is invalid.

### ISSUE THREAD

**Issue by TianbinTobin** [dcloudio/uni-app#3096]
**问题描述**
当定义一个变量，既作为一个组件的v-if判断条件，又充当另一个组件的props传入时，会产生编译警告
```
<div v-if="show"></div>
<McBottom v-else :loading="show" />
```

**复现步骤**
测试代码仓库：[https://github.com/TianbinTobin/uni-vue3-test](https://github.com/TianbinTobin/uni-vue3-test)

**系统信息:**
 - 发行平台 微信小程序
 - uni-app版本 ^3.0.0-alpha-3030220211217005

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030220211217006
