### ISSUE TITLE
关于 setup script语法 下 onShareAppMessage不生效

### ISSUE THREAD

**Issue by moke8** [dcloudio/uni-app#3097]
**新功能描述**
关于 (https://github.com/dcloudio/uni-app/issues/3084) 
vue3 setup script语法使用onShareAppMessage不生效问题

我在uniapp.d.ts中是看到存在onShareAppMessage方法的定义的
方不方便和onload一样做个完善呢

**现状及问题**
目前开发时的eslint在同时使用setup script和script时会eslint脚本报错
TypeError: Cannot read property 'references' of null

**尝试方案**
现在暂时关闭了eslint

**补充信息**
onShareTimeline和onShareAppMessage  如果方便的话，谢谢！
或者有ts + setup script语法的eslint配置推荐吗？
万分感谢

**Comment by fxy060608** [comment]
onShareAppMessage, onShareTimeline 此类生命周期，在小程序中，必须在定义页面的时候主动声明才会生效，不能动态添加，而 setup 内的代码属于运行时执行的，所以需要使用options方式主动定义，两者可以结合使用
```html
<script setup>
import { onShareAppMessage } from '@dcloudio/uni-app'
onShareAppMessage(() => {
  return { title: 'hello' }
})
</script>
<script>
export default {
  // 主动定义onShareAppMessage，通知小程序显示分享菜单
  onShareAppMessage() { }
}
</script>
```

**Comment by fxy060608** [comment]
eslint配置，参考文档：https://eslint.vuejs.org/user-guide/#installation 即可

**Comment by fxy060608** [comment]
编译器做了优化，当在页面代码中正则匹配到 `onShareAppMessage` 时，就自动为当前页面注册 onShareAppMessage，（如果要在组件中监听 onShareAppMessage ，仍需在页面代码中包含 onShareAppMessage 关键词，可以是注释之类的）

**Comment by moke8** [comment]
感谢！

**Comment by lzdml** [comment]
> > onShareAppMessage, onShareTimeline 此类生命周期，在小程序中，必须在定义页面的时候主动声明才会生效，不能动态添加，而 setup 内的代码属于运行时执行的，所以需要使用options方式主动定义，两者可以结合使用 或者，如果只需要兼容微信的话，也可以在 setup 里边，主动调用`uni.showShareMenu({ menus: ["shareAppMessage", "shareTimeline"] })`来激活分享菜单，这样就不用定义 options 了
> > ```
> > <script setup>
> > import { onShareAppMessage } from '@dcloudio/uni-app'
> > onShareAppMessage(() => {
> >   return { title: 'hello' }
> > })
> > </script>
> > <script>
> > export default {
> >   // 主动定义onShareAppMessage，通知小程序显示分享菜单
> >   onShareAppMessage() { }
> > }
> > </script>
> > ```
> 
> 这样写会报错的呀 script 和script setup不同 报错

是不是因为一个使用的ts, 一个没有指定语言

**Comment by boredream** [comment]
`  // 分享给朋友
  onShareAppMessage((res) => {
    console.log('onShareAppMessage', res)
    return getShareData()
  })

  // 分享到朋友圈
  onShareTimeline((res) => {
    console.log('onShareTimeline', res)
    return getShareData()
  })

  onLoad(() => {
    console.log('onload useShare')
    uni.showShareMenu({ menus: ["shareAppMessage", "shareTimeline"] })
  })`
