### ISSUE TITLE
<script setup>中 onPageScroll 不触发

### ISSUE THREAD

**Issue by iceDays** [dcloudio/uni-app#3099]
**问题描述**
`<script setup>`中 `onPageScroll` 不触发,

**复现步骤**
```html
onPageScroll((e) => {
  console.log(e);
  scrollTop.value = e.scrollTop;

  updateActiveIndex();
});
```

**预期结果**
正常触发

**实际结果**
未触发

**系统信息:**
 - 发行平台: 微信小程序
 - uni-app版本: 3.0.0-alpha-3030220211217007

**补充信息**
添加此声明后可触发
```html
<script lang="ts">
export default defineComponent({
  onPageScroll() {}, // 需要在这里声明
});
</script>
```

**Comment by fxy060608** [comment]
在小程序端，`onPageScroll` 需要在定义页面时主动声明，不能动态添加，在`setup`中的`onPageScroll`是运行期执行，如果框架默认为所有页面都添加`onPageScroll`，会引发性能问题，故需要开发者自己主动声明`onPageScroll`，可以同时使用`<script setup>` 和 `<script>`
```html
<script setup>
onPageScroll((e) => {
  console.log(e);
});
</script>
<script>
// 主动声明 onPageScroll ,通知小程序该页面需要 onPageScroll
export default {
  onPageScroll() {}
};
</script>
```

**Comment by iceDays** [comment]
了解了, 谢谢

**Comment by fxy060608** [comment]
编译器做了优化，当在页面代码中正则匹配到 `onPageScroll` 时，就自动为当前页面注册 onPageScroll 事件，（如果要在组件中监听 onPageScroll ，仍需在页面代码中包含 onPageScroll 关键词，可以是注释之类的）

**Comment by sufuwang** [comment]
请问页面或者组件的哪些生命周期方法在 hooks 中使用时，需要这样处理呀

**Comment by fxy060608** [comment]
onPageScroll
onShareAppMessage
onShareTimeline

**Comment by SoftwareEngineerPalace** [comment]
> 在小程序端，`onPageScroll` 需要在定义页面时主动声明，不能动态添加，在`setup`中的`onPageScroll`是运行期执行，如果框架默认为所有页面都添加`onPageScroll`，会引发性能问题，故需要开发者自己主动声明`onPageScroll`，可以同时使用`<script setup>` 和 `<script>`
> 
> ```
> <script setup>
> import { onPageScroll } from '@dcloudio/uni-app'
> onPageScroll((e) => {
>   console.log(e);
> });
> </script>
> <script>
> // 主动声明 onPageScroll ,通知小程序该页面需要 onPageScroll
> export default {
>   onPageScroll() {}
> };
> </script>
> ```
> 
> 类似问题：#3097

我用了这个方法，没用

**Comment by SoftwareEngineerPalace** [comment]
> **问题描述** `<script setup>`中 `onPageScroll` 不触发,
> 
> **复现步骤**
> 
> ```
> onPageScroll((e) => {
>   console.log(e);
>   scrollTop.value = e.scrollTop;
> 
>   updateActiveIndex();
> });
> ```
> 
> **预期结果** 正常触发
> 
> **实际结果** 未触发
> 
> **系统信息:**
> 
> * 发行平台: 微信小程序
> * uni-app版本: 3.0.0-alpha-3030220211217007
> 
> **补充信息** 添加此声明后可触发
> 
> ```
> <script lang="ts">
> export default defineComponent({
>   onPageScroll() {}, // 需要在这里声明
> });
> </script>
> ```

用了这个方法，也不行

**Comment by SongBana** [comment]
没用

**Comment by yerled** [comment]
> 编译器做了优化，当在页面代码中正则匹配到 `onPageScroll` 时，就自动为当前页面注册 onPageScroll 事件，（如果要在组件中监听 onPageScroll ，仍需在页面代码中包含 onPageScroll 关键词，可以是注释之类的）

有效！

我封了个组件X，在组件X里写onPageScroll逻辑，然后被引用到页面A和页面B，发现页面A里面生效了，页面B没有生效。
最后发现是因为页面A之前引入过onPageScroll（虽然代码删掉了，但是import还在），所以最后我在页面B里也写了个 `import { onPageScroll } from '@dcloudio/uni-app'`,于是页面B真的就生效了！

竟然会有这样的问题存在，完全不讲代码，完全不讲道理，小程序真是SB啊！

**Comment by BonjourYY** [comment]
@yerled 确实是这样，即使在组件里面引入了 onPageScroll，但是在页面里面没有引入的话，还是不行，完全搞不懂框架的思路。

**Comment by tsinghua-lau** [comment]
没用
