### ISSUE TITLE
uni-app form 表单 多按钮 提交

### ISSUE THREAD

**Issue by HSUCHING** [dcloudio/uni-app#310]
**问题描述**
如何在uni-app中，做一个表达的多提交按钮的不同提交.

**复现步骤**
比如一个表单，我有两个提交按钮，比如一个是向前，一个是向后.现在问题来了，如何在提交触发form @submit时，知道是哪个按钮触发的此次提交？

现在的几个思路
1.我统一把button的type:submit，换成普通的submit，然后手动触发form的提交.(暂时不知在uni-app中手工触发form submit)
2.在form @submit 中，可以获取什么按钮的信息吗？
3.form的submit 与 button的click同时进行，让click最后做提交，form的submit只负责拿到提交的信息.

**预期结果**
希望得到一个合理的解决方案.

**实际结果**

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 ios
 - uni-app版本 
 - 设备信息 iPhoneX

**补充信息**

**Comment by fxy060608** [comment]
button上边添加data-type="btn1",data-type="btn2"属性做标记，在事件里获取 currentTarget.dataset.type

**Comment by fxy060608** [comment]
<button @touchstart="handleSubmit(1)" form-type="submit">提交1</button>
<button @touchstart="handleSubmit(2)" form-type="submit">提交2</button>
touchstart 触发比 submit 早，在handleSubmit里边记录当前提交类型this.submitType，submit 里边根据this.submitType做判断
handleSubmit: function(type) {
                this.submitType = type
            }

**Comment by HSUCHING** [comment]
是个方案~~感谢

**Comment by HSUCHING** [comment]
@fxy060608 是个方案，感谢
