### ISSUE TITLE
cli项目编译dev:app编译失败

### ISSUE THREAD

**Issue by Iongtao** [dcloudio/uni-app#3100]
**问题描述**
cli项目编译dev:app编译失败

**复现步骤**
yarn dev:app 编译时异常：
![image](https://user-images.githubusercontent.com/24762616/147053262-1c65d144-e523-45e3-9b51-011ca9b3fd06.png)

**预期结果**
编译正常

**实际结果**
编译失败

**系统信息:**
 - 发行平台: app
 - 操作系统 macos
 - HBuilderX版本 cli
 - uni-app版本 无
 - 设备信息 无

**补充信息**
无

**Comment by Iongtao** [comment]
我是否应该使用hbuildx来运行app？ 但是使用hx运行时也出现错误
![image](https://user-images.githubusercontent.com/24762616/147054277-ccf3932f-d3a0-4e7b-8555-e5b561a89acd.png)

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030220211217009

**Comment by Iongtao** [comment]
> 已修复，cli更新至：3.0.0-alpha-3030220211217009

谢谢，有个问题，我cli 执行dev:app是没问题的 但我该如何调试，官网上写是只能在hbuildx上面去调试 但是hbuildx上运行到ios模拟器是这样的错误：
![image](https://user-images.githubusercontent.com/24762616/147062996-5e75f8c1-731d-453b-bcae-fdab57d63537.png)

**Comment by Iongtao** [comment]
貌似vite不支持编译app?

**Comment by fxy060608** [comment]
> 貌似vite不支持编译app?

支持，升级最新HBuilderX Alpha

**Comment by Iongtao** [comment]
> > 貌似vite不支持编译app?
> 
> 支持，升级最新HBuilderX Alpha

现在cli怎么转到hbuildx中，我刚试了，hx的项目没问题 ，但我这个项目直接是运行不起来的

**Comment by fxy060608** [comment]
> > > 貌似vite不支持编译app?
> > 
> > 
> > 支持，升级最新HBuilderX Alpha
> 
> 现在cli怎么转到hbuildx中，我刚试了，hx的项目没问题 ，但我这个项目直接是运行不起来的

直接整个项目拖入HBuilderX Alpha中运行即可

**Comment by Iongtao** [comment]
> 

谢谢 原来是把src目录当做根目录， 想请问 hx 的ts支持为啥没反应

**Comment by Iongtao** [comment]
> 

装了ts插件但没有ts类型支持和提示

**Comment by fxy060608** [comment]
> > 
> 
> 装了ts插件但没有ts类型支持和提示

目前还在优化中
