### ISSUE TITLE
Vue3使用pug语法引用组件, 编译成微信小程序之后组件未被识别

### ISSUE THREAD

**Issue by byk04712** [dcloudio/uni-app#3102]
**问题描述**
Vue3 使用 pug 语法, 页面在使用组件的时候,编译成小程序之后,组件标签未被识别. h5 和 app 正常

**复现步骤**
[复现问题的步骤]
1.  新创建的vue3 + vite uniapp项目, `npm i pug pug-plain-loader -D` 安装了 pug.
2. pages/index/index.vue 代码如下
```vue
<template lang="pug">
view.content
  //- logo
  image.logo(src="/static/logo.png")
  view.text-area
    text.title {{ title }}

  view.tag
    <!-- #ifdef APP-PLUS -->
    text App端
    <!-- #endif -->

    <!-- #ifdef MP -->
    text 小程序端
    <!-- #endif -->

    <!-- #ifdef H5 -->
    text h5端
    <!-- #endif -->

  hello
</template>

<script>
import Hello from './hello'

export default {
	components: {
		Hello
	},
	setup() {
		return {
			title: '2021 uniapp多端统一'
		}
	}
}
</script>

<style>
// ...这里省略
</style>

```
同级目录 hello.vue代码如下
```vue
<template lang="pug">
view.wrapper
  text.info good afternoon , uniapp 23:00
</template>

<script>
import { defineComponent } from 'vue'

export default defineComponent({
  name: 'Hello'
})
</script>

<style lang="stylus">
.wrapper
  background-color #F0AD4E
  padding 40upx
  
  .info
    font-size 40upx
    color #007AFF
</style>

```
3. 在h5中和app android中展示正常, 在微信小程序中未正确解析识别出 `index.vue` 中的 `hello` 组件

小程序未解析hello组件内容
![小程序未展示hello组件内容](https://user-images.githubusercontent.com/6211302/147120955-e6fdc8ee-d539-4674-848b-871c28050a8f.png)

app和h5正常展示
![app和h5展示正常](https://user-images.githubusercontent.com/6211302/147121039-40274d8b-f229-42ae-8ad3-65d2b95f0704.png)

生成的微信小程序代码
![生成的微信小程序代码](https://user-images.githubusercontent.com/6211302/147120821-2c10159b-4879-4021-a8e5-646702414da9.png)

usingComponent是空的
![usingComponent是空的](https://user-images.githubusercontent.com/6211302/147120881-cb7fd3b0-93f0-4784-876d-d1eda7bee370.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: Mac
 - HBuilderX版本 3.2.16.20211122

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030220211217012
