### ISSUE TITLE
uni.previewImage H5 在微信中预览不显示

### ISSUE THREAD

**Issue by 734839030** [dcloudio/uni-app#3103]
**问题描述**
uni.previewImage H5 在微信中预览不显示问题

**复现步骤**
在微信中和浏览器中使用

**预期结果**
浏览器和微信中表象一致
**实际结果**
见补充信息

**系统信息:**
 - 发行平台: [ 微信H5、H5平台]
 - 操作系统 [android ios 都返回不行，未收集版本号 都不是太老的版本]
 - HBuilderX版本 [3.3.2.20211218-alpha]  

**补充信息**
**预览前**
![image](https://user-images.githubusercontent.com/12107198/147131976-cf0a4c5b-28ca-4b76-8c01-4e196ca7e05b.png)
**浏览器中(正确)**
![image](https://user-images.githubusercontent.com/12107198/147132005-2f788869-3fe4-46f0-934b-76b6f41f79c1.png)
**微信中（错误）**
![image](https://user-images.githubusercontent.com/12107198/147132028-32c90980-dee1-43ef-b60f-86ed427dafc2.png)

**Comment by StrivingRabbit** [comment]
vue3 吗？

**Comment by 734839030** [comment]
> vue3 吗？

不好啥意思没说清楚，是vue3

**Comment by StrivingRabbit** [comment]
@734839030 alpha 3.3.2 实测 安卓和ios都 未复现。微信版本为 8.0.16

**Comment by 734839030** [comment]
android 下复现视频https://bear.seezoon.com/2.mp4


```
<template>
	<view class="content">
		<image class="logo" src="/static/logo.png"></image>
		<view class="text-area">
			<button @click="showSuccess">success</button>
			<button @click="showNone">none</button>
		</view>
		<view>
			<image @click="preview('https://bear.xinrsz.com/file/2021/12/22/26874189b891424f8ffb1d06afd0f887.jpeg')" class="image" src="https://bear.xinrsz.com/file/2021/12/22/26874189b891424f8ffb1d06afd0f887.jpeg" />
		</view>
	</view>
</template>

<script>
	export default {
		data() {

		},
		onLoad() {

		},
		methods: {
			preview(url) {
				if (!url) {
					return;
				}
				uni.previewImage({
					urls: [url]
				})
			},
			showSuccess() {
				uni.showToast({
					icon: 'success',
					title: '我是成功'
				})
			},
			showNone() {
				uni.showToast({
					icon: 'none',
					title: '我是成功'
				})
			}
		}
	}
</script>

<style>
	.content {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
	}

	.logo {
		height: 200rpx;
		width: 200rpx;
		margin-top: 200rpx;
		margin-left: auto;
		margin-right: auto;
		margin-bottom: 50rpx;
	}

	.text-area {
		display: flex;
		justify-content: center;
	}
	.image {
		width: 200rpx;
		height: 200rpx;
	}
	.title {
		font-size: 36rpx;
		color: #8f8f94;
	}
</style>

```

**Comment by StrivingRabbit** [comment]
@734839030 我访问你提供的网址，ios 预览图片正常，android 确实有问题。但是我使用你提供的示例跑在本地，预览没有问题。后续我再排查一下

**Comment by 734839030** [comment]
> @734839030 我访问你提供的网址，ios 预览图片正常，android 确实有问题。但是我使用你提供的示例跑在本地，预览没有问题。后续我再排查一下
这个issuse 麻烦一起处理
https://github.com/dcloudio/uni-app/issues/3038

**Comment by StrivingRabbit** [comment]
现在还有这个问题吗？猜测是微信浏览器在安卓端浏览器内核问题
