### ISSUE TITLE
能对vue-router4做支持吗

### ISSUE THREAD

**Issue by Miofly** [dcloudio/uni-app#3104]

**Comment by fxy060608** [comment]
uni-app提供了一套同小程序一致的路由跳转组件和API，无计划提供vue-router的跨平台支持

**Comment by SilurianYang** [comment]
请使用 [uni-simple-router](https://v3.hhyang.cn/) 它是一款专为 Uni App 量身定制的路由插件，提供无缝集成的特性，使得路由管理变得简单而高效。
