### ISSUE TITLE
app无法获取节点信息

### ISSUE THREAD

**Issue by Iongtao** [dcloudio/uni-app#3105]
**问题描述**
hbuilderx3.3.2.20211218-alpha编译运行app后，uni.createSelectorQuery().in(instance).select(selector).boundingClientRect().exec中
boundingClientRect方法无法正常回调

**复现步骤**
代码如下：
![image](https://user-images.githubusercontent.com/24762616/147306954-32b55610-f5e6-4198-a775-8cd492d4b0a3.png)

控制台出现错误
![image](https://user-images.githubusercontent.com/24762616/147306499-35d2279d-ad00-4624-817a-bcc789c79772.png)

在微信小程序中无此问题

**预期结果**
获取到正确的节点信息

**实际结果**
ios模拟器中无法获得正确的结果

**系统信息:**
 - 发行平台: App
 - 操作系统 ios15.2
 - HBuilderX版本 3.3.2.20211218-alpha
 - uni-app版本 无
 - 设备信息 iphone6模拟

**补充信息**
不知

**Comment by fxy060608** [comment]
1. 发测试工程
2. 最好描述清楚是vue3，还是vue2

**Comment by Iongtao** [comment]
> 1. 发测试工程
> 2. 最好描述清楚是vue3，还是vue2

项目是vue3
我创建了测试工程，发现是uni.createSelectorQuery().in(this)，这个this的问题，我用的是getCurrentInstance获取的当前实例。
如果单单传入instance的话
const query = uni.createSelectorQuery().in(instance)
此代码在微信小程序端有效
但在app中无效
然后我创建测试工程发现在app中需要传入instance.ctx才可以

抱歉我以为我的代码没问题，所以没有第一时间创建测试工程

**Comment by Iongtao** [comment]
使用instance.ctx在微信小程序端也可以

**Comment by fxy060608** [comment]
已修复，升级至HBuilderX 3.3.3
