### ISSUE TITLE
希望提供 vite + vue3 的 uitest 和 e2e 方案

### ISSUE THREAD

**Issue by linzebingo** [dcloudio/uni-app#3108]
**新功能描述**
希望提供 vite + vue3 的 uitest 和 e2e 方案

**现状及问题**
只能找到 vue-cli 版本的测试方案

**Comment by fxy060608** [comment]
跟 vue-cli 版本的使用方式一样
https://uniapp.dcloud.net.cn/collocation/auto/quick-start
