### ISSUE TITLE
H5 modal bug

### ISSUE THREAD

**Issue by bin362490109** [dcloudio/uni-app#311]
**问题描述**
h5 端uni.showModal  点击空白地方 弹窗会消失, app和小程序只有点击确定和取消才会消失。

**复现步骤**
[复现问题的步骤]
1、写个uni.showModal 方法
2、编译到h5，用浏览器打开
3、打开弹出框后，点击空白地方 弹窗消失

**预期结果**
只有点击 确定或则取消才会消失

**实际结果**
点击空白就会消失 ，理论上我需要用户认证看内容，然后点击确认或取消进行下一步

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by xiaoyucoding** [comment]
HBuilderX 1.9.3 及 CLI 均已更新
