### ISSUE TITLE
是否可以跨服务空间进行数据查询？

### ISSUE THREAD

**Issue by pasake** [dcloudio/uni-app#3110]
**新功能描述**
跨服务空间数据查询

**现状及问题**
跨服务空间数据查询

**尝试方案**
跨服务空间数据查询

**补充信息**
跨服务空间数据查询

**Comment by Wangyaqi** [comment]
腾讯云可以直接跨服务空间获取，uniCloud.database可以直接传对应服务空间的信息。阿里云不支持。
