### ISSUE TITLE
vite setup 语法糖提供 name 属性插件不兼容问题

### ISSUE THREAD

**Issue by Miofly** [dcloudio/uni-app#3112]
使用的插件地址：https://github.com/anncwb/vite-plugin-vue-setup-extend
当开启这个插件时会提示如图所示报错
![image](https://user-images.githubusercontent.com/42859910/147428845-0d7ea6db-1893-46fa-99b8-fc0ee97efaa0.png)
报错具体原因如下
![image](https://user-images.githubusercontent.com/42859910/147428902-101090aa-71da-4c7b-8375-9f3d802e20a2.png)

版本号
    "@dcloudio/uni-automator": "^3.0.0-alpha-3030320211225001",
    "@dcloudio/uni-cli-shared": "^3.0.0-alpha-3030320211225001",
    "@dcloudio/vite-plugin-uni": "^3.0.0-alpha-3030320211225001",
    "vite-plugin-vue-setup-extend": "^0.1.0",

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030420211227002
