### ISSUE TITLE
生成bem规则类名  bem()  方法问题

### ISSUE THREAD

**Issue by yuwenlideliunian** [dcloudio/uni-app#3113]
此方法会导致在打包成支付宝小程序时会使class类名之间含有‘，’号导致内置样式失效
![image](https://user-images.githubusercontent.com/52705035/147471221-3ef90143-4c97-4837-a8b6-5526eacf11e2.png)

**Comment by StrivingRabbit** [comment]
消息描述一下你是怎么使用的
