### ISSUE TITLE
【vite】子组件生命周期方法未执行

### ISSUE THREAD

**Issue by sufuWang** [dcloudio/uni-app#3114]
测试工程 https://github.com/sufuWang/uniapp_vite
页面跳转时，页面所使用到的组件的 destroyed 方法未执行

**Comment by fxy060608** [comment]
1. vue3 中的销毁生命周期是 unmounted
2. 已修复，cli更新至：3.0.0-alpha-3030420211227002
建议可以描述清楚一些，比如标明是哪个平台出现的问题，这样可以提高解决问题的效率

**Comment by sufuWang** [comment]
好的
