### ISSUE TITLE
vue3 使用 ref 获取组件实例在微信小程序无效

### ISSUE THREAD

**Issue by Miofly** [dcloudio/uni-app#3115]
在h5端可以用 ref 获取到 image 的实例，在小程序段 ref.value 是 `undefined`
h5端如下
![image](https://user-images.githubusercontent.com/42859910/147482556-c7399b53-d639-4eac-8010-a15308f8a297.png)

小程序端如下
![image](https://user-images.githubusercontent.com/42859910/147482518-e33c8a2e-f272-4034-b35a-f310a28811ff.png)
测试代码如下，
`<template>
	<view class="content">
		<view class="text-area">
			<image ref="mytest" src=""></image>
		</view>
		<IndexChild ref="childTest"></IndexChild>
	</view>
</template>`
`
<script setup lang="ts">
	import { onMounted, ref } from 'vue';
	import IndexChild from './index-child.vue';

	const mytest = ref();
	const childTest = ref();

	onMounted(() => {
		console.log('mytest', mytest);
		console.log('childTest', childTest);
	});
</script>`

git测试地址：https://github.com/Miofly/vue3-vite-uniapp

**Comment by fxy060608** [comment]
小程序端仅自定义组件支持ref，内置组件没有 dom 操作
