### ISSUE TITLE
vue3 支付宝 @getphonenumber 回调异常

### ISSUE THREAD

**Issue by Sexy6God** [dcloudio/uni-app#3116]
**问题描述**
用户点击授权手机号后，控制台报以下异常，getphonenumber事件回调未被执行

<img width="787" alt="截屏2021-12-28 上午8 53 52" src="https://user-images.githubusercontent.com/86021729/147516486-c6748aa3-29a1-40f5-a82e-081ec2fd2377.png">

[源代码]
```vue
<template>
  <button 
    open-type="getPhoneNumber" 
    @getphonenumber="onGetPhoneNumber" 
    @click="onClick"
  >获取手机号</button>
</template>

<script setup lang="ts">
function onClick() {
  console.log('onClick')
}

function onGetPhoneNumber() {
  console.log('onGetPhoneNumber')
}
</script>
```

**系统信息:**
 - 发行平台: [支付宝小程序]
 - uni-app版本 [使用Vue-cli创建项目，3.0.0-alpha-3030420211227001]

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030420211227002
