### ISSUE TITLE
uniapp+若依 开发租房小程序

### ISSUE THREAD

**Issue by smileBoy123456** [dcloudio/uni-app#3117]
gitee地址：https://gitee.com/cookieBoy/house
本程序已经经过测试，可以直接使用,界面可以自己进行修改。本人热爱全栈，热爱vue，热爱java，热爱编程。
望采纳，谢谢

**Comment by fxy060608** [comment]
可以在 https://github.com/dcloudio/uni-app/issues/6 中补充
