### ISSUE TITLE
微信小程序跳转的APPID列表希望可以在uni-app中配置

### ISSUE THREAD

**Issue by qqyemingqq** [dcloudio/uni-app#312]
**新功能描述**
微信小程序跳转的APPID列表希望可以在uni-app中配置

**现状及问题**
现在每次发行之后，app.json中的跳转APPID列表的属性都会被清空，每次发布后都要手动去修改

**补充信息**
微信跳转策略修改官方说明文档：
https://developers.weixin.qq.com/miniprogram/dev/reference/configuration/app.html#navigatetominiprogramappidlist

**Comment by xiaoyucoding** [comment]
[manifest.json->mp-weixin->navigateToMiniProgramAppIdList](https://uniapp.dcloud.io/collocation/manifest?id=mp-weixin)
