### ISSUE TITLE
【vite】打包成功，控制台报错

### ISSUE THREAD

**Issue by sufuWang** [dcloudio/uni-app#3121]
vite 版本项目打包至微信小程序

当代码中缺少某些依赖时，打包过程中不会报错，却在控制台报错，请问为什么在打包过程中不报错呀？

![image](https://user-images.githubusercontent.com/46395105/147562113-a5c40984-0469-4373-86e8-b5ee583490ef.png)
![image](https://user-images.githubusercontent.com/46395105/147562134-7af70855-c579-458f-9040-2083f82fe71a.png)

**Comment by fxy060608** [comment]
这属于运行时错误，不过你可以通过 lint 工具来提前发现此类错误

**Comment by sufuWang** [comment]
只使用 vite 是可以在编译阶段时期，发现这个错误的。uni-app 不支持嘛 ？

**Comment by fxy060608** [comment]
> 只使用 vite 是可以在编译阶段时期，发现这个错误的。uni-app 不支持嘛 ？

发标准的vite可以发现这个错误的示例工程，我测试不可以
