### ISSUE TITLE
vite vue3 差量编译后白屏

### ISSUE THREAD

**Issue by Sexy6God** [dcloudio/uni-app#3122]
**问题描述**
3.0.0-alpha-3030420211227001  差量编译后渲染白屏
3.0.0-alpha-3030320211225001 表现正常

差量编译前：
<img width="755" alt="截屏2021-12-28 下午9 50 42" src="https://user-images.githubusercontent.com/86021729/147573174-f4522a04-36d9-471a-8790-13996281bc82.png">
<img width="318" alt="截屏2021-12-28 下午9 50 51" src="https://user-images.githubusercontent.com/86021729/147573199-fb5d3178-c884-4f26-9a0b-4b7c008439df.png">

差量编译后：
<img width="752" alt="截屏2021-12-28 下午9 51 11" src="https://user-images.githubusercontent.com/86021729/147573239-8cf7daf7-6b2d-4e26-bd27-3a6b21e3886e.png">
<img width="321" alt="截屏2021-12-28 下午9 51 17" src="https://user-images.githubusercontent.com/86021729/147573242-bcfd8b9a-f0da-4196-82c6-315e0ab5abaf.png">

**复现步骤**
[最小可复现Demo](https://github.com/Sexy6God/uni-vue3-vite-compile-bug)

**系统信息:**
 - 发行平台:  微信小程序
 - uni-app版本: Vue-cli项目，3.0.0-alpha-3030420211227001

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030420211228002
