### ISSUE TITLE
vue3 + vite 分包资源没编译出来

### ISSUE THREAD

**Issue by hlbj105** [dcloudio/uni-app#3123]
**问题描述**
vue3 + vite 分包资源没编译出来，

**复现步骤**
![image](https://user-images.githubusercontent.com/16408650/147618334-bac2b8c0-e700-41b2-a170-55b4490d0314.png)

![image](https://user-images.githubusercontent.com/16408650/147618355-31950133-1680-4c05-abbd-89b211316cd7.png)

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本 cli
 - uni-app版本 ^3.0.0-alpha-3030120211217001
 - 设备信息 小程序开发者工具

**补充信息**
[可选]
分包资源没被复制过来

**Comment by hlbj105** [comment]
![image](https://user-images.githubusercontent.com/16408650/147618550-58d1f0bc-54b3-45ef-96e9-049f13ec8ec9.png)

放在assets里就可以，对于老项目升级不太友好哈

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030420211228003
