### ISSUE TITLE
配置pages.js 不生效

### ISSUE THREAD

**Issue by cheneywang** [dcloudio/uni-app#3124]
**问题描述**
配置pages.js 不生效 无法对项目进行按需打包  https://github.com/dcloudio/uni-app/blob/master/packages/uni-cli-shared/lib/pages.js

**Comment by cheneywang** [comment]
next版本无此功能

**Comment by imdake** [comment]
Vue3的都没了

**Comment by Otto-J** [comment]
pages.js 不是对外提供的功能，不能保证功能的稳定性，建议通过 pages.json 完成业务逻辑维护。后续 vue3 不再暴露。
