### ISSUE TITLE
vite vue3  默认插槽无效

### ISSUE THREAD

**Issue by awagege** [dcloudio/uni-app#3126]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**

 <view class="mask" />
    <slot></slot>
  </view>

调用
<Dialog>
      <view class="my-qrcode">
        ....
      </view>
    </Dialog>

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/26294948/147629579-4459959c-5327-4cc8-a784-548f730658b7.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 3.0.0-alpha-3030420211228004
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
此警告不影响，如果效果非预期，发测试工程

**Comment by awagege** [comment]
dom是空的
![image](https://user-images.githubusercontent.com/26294948/147633613-ced35ac1-7642-40cc-92e4-9c4625cf3ac2.png)

**Comment by awagege** [comment]
抱歉，并非bug，是因为emit  input没改成update：modelvalue引起的
