### ISSUE TITLE
h5配置跨域无效

### ISSUE THREAD

**Issue by AnKangZhouWei** [dcloudio/uni-app#3128]
在manifest.json 中配置，浏览器还是报跨域问题
![1640765903(1)](https://user-images.githubusercontent.com/34094293/147641537-b10e5d91-acac-4352-8865-b1524e4b8fff.png)

![1640766008(1)](https://user-images.githubusercontent.com/34094293/147641639-075cb215-9238-4203-a60c-5f398d194a99.png)

**Comment by fxy060608** [comment]
确认自己的用法是正确的，配置proxy，不是让你直接在网页上请求 http://173 这个地址，而是访问 http://localhost:8080/api 这样的接口 重定向 到 http:// 173.*.
