### ISSUE TITLE
运行H5的时候报错

### ISSUE THREAD

**Issue by VICTORYGS** [dcloudio/uni-app#313]
![image](https://user-images.githubusercontent.com/33747619/56339167-a710ad00-61df-11e9-87cd-8aa22d9fa803.png)
跑微信的时候没有报错,跑h5的时候就出错了.不知道什么原因

**Comment by xiaoyucoding** [comment]
精简下代码，排查下是哪部分影响了。
从错误信息看，应该是 titleNView 里面配置的 buttons 出问题了，可以重点往这个方向去排查。
