### ISSUE TITLE
picker-view 报错 v.value.filter is not a function

### ISSUE THREAD

**Issue by molvqingtai** [dcloudio/uni-app#3130]
**问题描述**
HBuilderX 从 v3.2.16 升级到 v3.3.4 导致 picker-view 报错

**复现步骤**
升级 HBuilderX 到最最新版本
```vue
  <picker-view @change="handleChange" class="picker-view" indicator-class="picker-active">
      <picker-view-column>
        <view class="picker-item" v-for="item in [{ officeId: 1, officeName: '123' }]" :key="item.officeId">
          {{ item.officeName }}
        </view>
      </picker-view-column>
    </picker-view>
```

**预期结果**
不报错

**实际结果**
![image](https://user-images.githubusercontent.com/26295698/147653872-e519c153-1d5f-4653-ba51-5d148cb00562.png)

**系统信息:**
 - 5+ App
 - Android 8.1.0
 - HBuilderX 3.3.4.20211228
 - uni-app vue 3.0

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
预计下版修复

**Comment by molvqingtai** [comment]
> 预计下版修复

请问有办法回退版本吗，卸载了 v3.3.4 回退到 v3.2.16，打包基座后提示
“本应用使用 HBuilderX 3.3.4 或对应的 cli 版本编译，而手机端 SDK 版本是 3.2.16”
运行后，这个 picker-view 问题仍然存在，我理解并没有卸载干净
我是 MacOS，怎么才能完全的卸载干净重新安装

**Comment by fxy060608** [comment]
> > 预计下版修复
> 
> 请问有办法回退版本吗，卸载了 v3.3.4 回退到 v3.2.16，打包基座后提示 “本应用使用 HBuilderX 3.3.4 或对应的 cli 版本编译，而手机端 SDK 版本是 3.2.16” 运行后，这个 picker-view 问题仍然存在，我理解并没有卸载干净 我是 MacOS，怎么才能完全的卸载干净重新安装

今天晚上就会发布 3.3.5 修复此问题

**Comment by zhetengbiji** [comment]
项目是 HBuilderX 创建的还是 CLI 创建的？

**Comment by molvqingtai** [comment]
> 

HBuilderX

**Comment by zhetengbiji** [comment]
> > 
> 
> HBuilderX

更新到 3.3.5

**Comment by daalinge** [comment]
3.3.3.20211225 hbuildx更新picker打开后导致其他form表单不能单击，调不起来手机键盘

**Comment by StrivingRabbit** [comment]
@daalinge 更新至 3.3.5
