### ISSUE TITLE
子组件存在两个插槽时渲染不正确

### ISSUE THREAD

**Issue by wzdyxgg** [dcloudio/uni-app#3131]
**问题描述**

使用插槽内容访问子组件中才有的数据时，同时需要访问父组件数据时
子组件存在两个插槽时，无法同时渲染插槽内容
**复现步骤**
子组件
```js
<template>
	<div>
		<slot
			name="head"
			:sku-data="skuData"
		>
		</slot>
		<div>-----------</div>
		<slot
			name="footer"
			:sku-data="skuData"
		>
		</slot>
	</div>
	
</template>
<script>
export default {
    data() {
        return {
            skuData: 'skuData',
        };
    },
    
};
</script>
<style>

</style>
```
父组件
```js
<template>
  <div>
	  <sku>
		 <template #head="{skuData}" >
				{{test}}
				head
				{{skuData}}
		</template>
		  <template #footer="{skuData}">
				{{test}}
				footer
				{{skuData}}
		</template>
	  </sku>
  </div>
  
</template>

<script>
import { ref, onMounted, reactive, onUnmounted, defineComponent, } from "vue";
import sku from './components/sku.vue';
const test =ref('this is test ') 
export default {
 components: {
        sku,
    },
   setup(props){
        return {
            test
        }
    }
}
</script>

<style>

</style>
```
manifest.json微信配置

```js
    "mp-weixin" : {
        "appid" : "",
        "setting" : {
            "urlCheck" : false
        },
        "usingComponents" : true,
		"scopedSlotsCompiler" : "augmented"
    },
```

**预期结果**
父组件同时渲染两个插槽内容

**实际结果**
父组件渲染一个插槽内容
![image](https://user-images.githubusercontent.com/62464191/147660704-d84e8e66-9278-491d-8f2c-d7c0fad73f1e.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 macos10.15.7 
 - HBuilderX版本  HBuilderX 版本3.2.16.20211122  vscode同时存在问题
 - uni-app版本 uni-app v3.3.0
                         uni-app cli v2.0.0-alpha-33020211130001

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
如果是vue3版本，请重新创建最新的vue3 cli项目
`npx degit dcloudio/uni-preset-vue#vite my-vue3-project`
如果使用的HBuilderX，请升级至最新

**Comment by wzdyxgg** [comment]
有没有能够创建vue3的webpack打包的命令行
npx degit dcloudio/uni-preset-vue#vite my-vue3-project是vite打包的

**Comment by fxy060608** [comment]
> 有没有能够创建vue3的webpack打包的命令行 npx degit dcloudio/uni-preset-vue#vite my-vue3-project是vite打包的

不支持webpack，只支持vite

**Comment by wzdyxgg** [comment]
hbuildx最新版的vue3也是用的vite打包吗？未来不再提供webpack的打包方案了吗

**Comment by fxy060608** [comment]
> hbuildx最新版的vue3也是用的vite打包吗？未来不再提供webpack的打包方案了吗

是的，目前没有计划再提供vue3 的 webpack方案
