### ISSUE TITLE
hx编译到微信小程序之后的包有问题

### ISSUE THREAD

**Issue by MQYForverT** [dcloudio/uni-app#3132]
**问题描述**
vue版本：vue3

我在插件市场引入了 秋云chat 插件（插件格式为：uni_modules）

我看了这个插件的代码，里面包含1.4M的在app和h5环境下才会用到的js文件，且，在组件里面也使用了条件编译，只有在app或者h5下才会引用这1.4M的js文件。

但是，为何通过hx编译之后，在小程序那边，还是会出现这1.4M的js文件？然后这就导致我主包过大了。。。上传不了

**复现步骤**
1.在插件市场引入了 秋云chat 插件：https://ext.dcloud.net.cn/plugin?id=271
2.然后编译到微信小程序

**预期结果**
秋云chat 插件里面包含的只在app和h5下才生效的1.4M的js文件： 不应该编译到微信小程序中

**实际结果**
秋云chat 插件里面包含的只在app和h5下才生效的1.4M的js文件： 编译到了微信小程序中

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统：Android 10
 - HBuilderX版本 ：3.35
 - vue版本：vue3
 - 设备信息 ：荣耀v20

**补充信息**
我觉得可能是编译的时候出了问题

**Comment by fxy060608** [comment]
可以自己先手动删除编译后的uni_modules/qiun-data-charts/static/h5目录

**Comment by MQYForverT** [comment]
> 可以自己先手动删除编译后的uni_modules/qiun-data-charts/static目录

可以的，但是只能通过手动吗？我想知道目前为止这个是hx的一个bug吗？在后续更新会解决这个问题？以及大概哪个版本？

**Comment by fxy060608** [comment]
> > 可以自己先手动删除编译后的uni_modules/qiun-data-charts/static目录
> 
> 可以的，但是只能通过手动吗？我想知道目前为止这个是hx的一个bug吗？在后续更新会解决这个问题？以及大概哪个版本？

是Bug，会修复，预计3.3.6

**Comment by jaqi-l** [comment]
> > > 可以自己先手动删除编译后的uni_modules/qiun-data-charts/static目录
> > 
> > 
> > 可以的，但是只能通过手动吗？我想知道目前为止这个是hx的一个bug吗？在后续更新会解决这个问题？以及大概哪个版本？
> 
> 是Bug，会修复，预计3.3.6

这个bug好像在4.28版本又出现了

**Comment by fxy060608** [comment]
> > > > 可以自己先手动删除编译后的uni_modules/qiun-data-charts/static目录
> > > 
> > > 
> > > 可以的，但是只能通过手动吗？我想知道目前为止这个是hx的一个bug吗？在后续更新会解决这个问题？以及大概哪个版本？
> > 
> > 
> > 是Bug，会修复，预计3.3.6
> 
> 这个bug好像在4.28版本又出现了

参考：https://ask.dcloud.net.cn/question/199019
