### ISSUE TITLE
uni-app vite compilerOptions怎么设置

### ISSUE THREAD

**Issue by 651016236** [dcloudio/uni-app#3133]
使用HBuilder X 3.3.2.20211218-alpha
通过vite.config.js设置后报错
import { defineConfig } from 'vite'
import uni from '@dcloudio/vite-plugin-uni'
import vue from '@vitejs/plugin-vue'
/**
 * @type {import('vite').UserConfig}
 */
export default defineConfig({
  plugins: [
	  vue({
		  template: {
                compilerOptions: {
                    isCustomElement: tag => tag === 'iconpark-icon'
                }
            }
        }),
	  uni(),
  ],
})

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030520211229002
```js
import { defineConfig } from "vite";
import uni from "@dcloudio/vite-plugin-uni";
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    uni({
      vueOptions: {
        template: {
          compilerOptions: {
            isCustomElement:tag => tag === 'iconpark-icon'
          },
        },
      },
    }),
  ],
});

```

**Comment by 651016236** [comment]
> 

请问怎么更新cli的版本，我的版本是跟着HBuilderX3.3.2的

**Comment by 651016236** [comment]
> > 
> 
> 请问怎么更新cli的版本，我的版本是跟着HBuilderX3.3.2的

![image](https://user-images.githubusercontent.com/5875767/147798698-6ce7b385-1da3-430b-8ede-b9431ba6a426.png)
好了 package.json指定版本号安装就行了，谢谢

**Comment by lhf19900402** [comment]
尼玛！这个问题困扰了我一天   路过此地  如获至宝  谢谢大侠！
