### ISSUE TITLE
Vite+ts的模板 如何处理 uni 无法识别的问题

### ISSUE THREAD

**Issue by ringgoyao** [dcloudio/uni-app#3139]
使用[npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project](https://gitee.com/dcloud/uni-preset-vue/repository/archive/vite-ts.zip)
这个模板

在vscode里.ts文件里无法识别uni ，请问应该如何配置？

![1f33bc083ac7e012db715923a13b594](https://user-images.githubusercontent.com/5906943/147805028-463ddf06-5b7e-468e-add3-ebaf7d554717.png)

检查了一下tsconfig.json,有引入类型定义
```
 "types": ["@dcloudio/types"] 

```

**Comment by fxy060608** [comment]
上边已经提示了吧，报错的是你代码 uni.getStorage() 没传参数
`uni.getStorage({key:'test'})`

**Comment by ringgoyao** [comment]
![image](https://user-images.githubusercontent.com/5906943/147805211-05af4632-2026-4908-b317-c47d11a0ac5d.png)
问题提的有点问题，eslint识别不了这个uni

**Comment by fxy060608** [comment]
> ![image](https://user-images.githubusercontent.com/5906943/147805211-05af4632-2026-4908-b317-c47d11a0ac5d.png) 问题提的有点问题，eslint识别不了这个uni

你用的什么配置？装的什么插件

**Comment by ringgoyao** [comment]
> > ![image](https://user-images.githubusercontent.com/5906943/147805211-05af4632-2026-4908-b317-c47d11a0ac5d.png) 问题提的有点问题，eslint识别不了这个uni
> 
> 你用的什么配置？装的什么插件

用了eslint+prettier ，vscode是vetur，虽然可以禁用，但是问题应该不在这个地方
[app.zip](https://github.com/dcloudio/uni-app/files/7795406/app.zip)

**Comment by fxy060608** [comment]
> > > ![image](https://user-images.githubusercontent.com/5906943/147805211-05af4632-2026-4908-b317-c47d11a0ac5d.png) 问题提的有点问题，eslint识别不了这个uni
> > 
> > 
> > 你用的什么配置？装的什么插件
> 
> 用了eslint+prettier ，vscode是vetur，虽然可以禁用，但是问题应该不在这个地方 [app.zip](https://github.com/dcloudio/uni-app/files/7795406/app.zip)

你的 eslint 配置有问题，参考：https://eslint.vuejs.org/user-guide/#installation

**Comment by ringgoyao** [comment]
这样太难排查了，有没有一份.eslintrc.js可以参考下？

**Comment by ringgoyao** [comment]
eslinttrc.js里加上忽略全局变量即可，需要重启vscode生效
  globals: {
    uni: true
  }
