### ISSUE TITLE
微信音频分享跳转href使用了mediaUrl

### ISSUE THREAD

**Issue by nmdx** [dcloudio/uni-app#314]
**问题描述**
这估计是一个历史遗留问题了。。

### 1、uni.share的微信音乐分享，分享后跳转链接href使用了mediaUrl，
这个是微信特性还是接口问题？  因为qq分享接口是正常的，点击打开的网页是href值
![](https://ws4.sinaimg.cn/large/006tNc79gy1g26sgqg402j30qt08qwgs.jpg)
**预期结果**
![](https://ws2.sinaimg.cn/large/006tNc79gy1g26st2vbr3j30hs0p0mxq.jpg)
**实际结果**
![](https://ws4.sinaimg.cn/large/006tNc79gy1g26shitqe3j30u011lq3e.jpg)

### 2、 安卓分享到ios平台时候音频无播放按钮
![](https://ws2.sinaimg.cn/large/006tNc79gy1g26sn0ew1ij30kf0hswf2.jpg)

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 Android 8.0
 - HBuilderX版本 1.9.2
 - uni-app版本 1.9.2
 - 设备信息 安卓

**补充信息**
 qq音乐app分享没有这两问题，话说哪里能看到uni.share的源码...

**Comment by dcloudhdx** [comment]
音频分享到微信，目前暂不支持href
