### ISSUE TITLE
vue3 vite编译到微信小程序 分包后无法获取分包下的静态资源

### ISSUE THREAD

**Issue by fangshikeji** [dcloudio/uni-app#3140]
![image](https://user-images.githubusercontent.com/76583297/147811634-8a9f8f15-bc45-4605-b6db-e38b93e5aafc.png)
h5可以正常显示
![image](https://user-images.githubusercontent.com/76583297/147811661-9a1a6f18-4352-477d-b288-8eb750189f55.png)

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/3123
如果使用的HBuilderX，请升级到最新
