### ISSUE TITLE
运行dev:h5以后，uni-xxx系列的组件没有载入样式

### ISSUE THREAD

**Issue by ossso** [dcloudio/uni-app#3141]
**问题描述**
运行dev:h5以后，uni-xxx系列的组件没有载入样式
例如uni-view\uni-image\uni-page-refresh都是没有对应的样式

**Comment by fxy060608** [comment]
上述内容未提供有效的排查信息，详细说明运行环境，版本号等有效信息

**Comment by ossso** [comment]
问题出在已有项目输出H5；uni-h5中的css没有被引入；另外一个项目倒是没这个问题；node_modules已经完全同步重装了，也没有用。我还是自引入这个css吧
