### ISSUE TITLE
v-for 双重循环中无法在第二层循环中读取 (条件属性判断中)到第一层的 item

### ISSUE THREAD

**Issue by kissjin** [dcloudio/uni-app#3145]
**问题描述**
v-for 双重循环中无法在第二层循环中读取到第一层的 item ( 本例中的s)

**复现步骤**
`
 <view v-for="s in [1,2,4,3,5]" :key="s">
    <view v-for="(r,index) in ['e','m']" :key="index">
      <text v-if=" s ==2 ">
        sss
      </text>
    </view>
  </view>`

**预期结果**
能正确的报告的在 条件判断中读取结果  出现在 属性， 条件判断中，

**实际结果**
![c595ffefbbeef9e05b7f5ae6c2203ee](https://user-images.githubusercontent.com/40197934/148002436-a7f748e0-c749-4fa8-8f90-572bb01d4d91.png)
报错位置：
![fdfc2890e8c57eb5bc6dc0cf98626fd](https://user-images.githubusercontent.com/40197934/148002442-cde67073-91dd-488e-b712-e540bfcb511c.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统  windows10
 - HBuilderX版本  "@dcloudio/uni-mp-weixin": "^3.0.0-alpha-3030220211217008",
 - uni-app版本 Vue-cli
 - 设备信息  微信小程序

**补充信息**
微信小程序版本有问题，h5正常 ，使用vue3版本（微信小程序）的创建出现的问题，vue2版本（微信小程序）正常。
作用域的问题，未将上层的item传递到判断中，

**Comment by fxy060608** [comment]
贴原始代码
