### ISSUE TITLE
uni.getLocale  的获取逻辑

### ISSUE THREAD

**Issue by zhoudaxiaa** [dcloudio/uni-app#3148]
**问题描述**
使用uni.getLocale 获取系统语言时，未设置语言时，返回值的逻辑是怎么样的，我试了下，切换成印尼语时，返回的是 en

**复现步骤**
[复现问题的步骤]
使用非内置支持的系统语言，比如印尼语。uni.getLocale() 返回的不是  in-CN，而是en，意思是不是只要不是内置支持的语言，返回的都是en，那不就死循环了，我写了  uni.in-CN.json  也不起效，而我想要根据系统语言自动切换语言，根据uni.getSystemInfoSync() 获取到真实的language，如果进app 就设置 setLocale  又触发了，设置就会重启。。。

**预期结果**
我想要根据系统语言自动切换语言。在设置uni-app.in-CN.json 可以见效

**实际结果**
非支持的语言默认为英文了

**系统信息:**
 - 发行平台: [app]
 - 操作系统 [如 HarmonyOS 2.0.0]
 - HBuilderX版本 [3.3.3]
 - uni-app版本 [uni-app v3.3.3，uni-app cli v2.0.1-33320211224001]
 - 设备信息 [华为mate30]

**补充信息**
感觉getLocale 的时候，会判断是不是内置支持的语言，如果不是就会返回 en。应该实际的系统语言

**Comment by dcloudhdx** [comment]
参考文档 [https://uniapp.dcloud.net.cn/worktile/i18n.html#newlocale](https://uniapp.dcloud.net.cn/worktile/i18n.html#newlocale)
