### ISSUE TITLE
H5,Hbuilder和chrome中正常，在手机浏览器和微信中打开，界面很小，看上去分辨率很高

### ISSUE THREAD

**Issue by endison1986** [dcloudio/uni-app#3151]
RT，不知道如何解决，设置了rpxCalcMaxDeviceWidth, rpxCalcBaseDeviceWidth，rpxCalcIncludeWidth 没有效果

**Comment by zhetengbiji** [comment]
对比图上一下

**Comment by endison1986** [comment]
图一是hbuilder内置的浏览器，pc的chrome也是这个效果
![微信图片_20220105155841](https://user-images.githubusercontent.com/7878324/148181409-3c401a17-3de3-4ccf-87bf-622252671694.png)
图二是微信浏览器里的，手机浏览器也是这个效果
![微信图片_20220105155849](https://user-images.githubusercontent.com/7878324/148181423-cdf9fc02-c0f7-431f-81fd-a0d017aad48f.jpg)

**Comment by zhetengbiji** [comment]
一般情况下无需动 rpxCalc 相关配置。你先试试 hello uni-app 是否正常。

**Comment by endison1986** [comment]
好的，我先试下hello uni-app，另外我使用了thorui，我也跑一下thorui的示例工程

**Comment by endison1986** [comment]
我想我找到原因了，我在onPageNotFound里调用了navigateTo方法，跳转到了存在的页面，这时候页面的样式就出现了问题，显的特别大，但如果我直接通过url访问存在的页面，样式就正常了。

**Comment by endison1986** [comment]
我想我找到原因了，我在onPageNotFound里调用了navigateTo方法，跳转到了存在的页面，这时候页面的样式就出现了问题，显的特别大，但如果我直接通过url访问存在的页面，样式就正常了，并且这个问题只存在手机浏览器中，PC端是正常的。
@zhetengbiji

**Comment by endison1986** [comment]
有什么办法可以解决么，因为我需要通过url来判断实际的页面并进行跳转

**Comment by endison1986** [comment]
有了新的进展，之前我以为是在onPageNotFound里面使用了navigateTo导致的，因为我直接访问原页面，界面大小是正常的，但后来我发现，如果我通过另一个域名直接访问页面，大小也是不对的

目前我的做法是，我先定义了一个二级域名，如`http://a.domain.com`，跳转到隐形URL，`https://www.domain.com/h5/pages/a`，然后我访问域名`http://a.domain.com/myKey`，这样浏览器实际会访问`https://www.domain.com/h5/pages/a/myKey`，然后我在`onPageNotFound`中获取`path`，`navigateTo`到`/pages/a/index?v=myKey`，这种情况下，如果我直接访问`/pages/a/index?v=myKey`页面是正常的，通过`https://www.domain.com/h5/pages/a/myKey`访问也是正常的，但是通过`http://a.domain.com/myKey`就不正常了，所以应该是域名不同导致的

**Comment by endison1986** [comment]
@zhetengbiji  有了新的进展，之前我以为是在onPageNotFound里面使用了navigateTo导致的，因为我直接访问原页面，界面大小是正常的，但后来我发现，如果我通过另一个域名直接访问页面，大小也是不对的

目前我的做法是，我先定义了一个二级域名，如http://a.domain.com，跳转到隐形URL，https://www.domain.com/h5/pages/a，然后我访问域名http://a.domain.com/myKey，这样浏览器实际会访问https://www.domain.com/h5/pages/a/myKey，然后我在onPageNotFound中获取path，navigateTo到/pages/a/index?v=myKey，这种情况下，如果我直接访问/pages/a/index?v=myKey页面是正常的，通过https://www.domain.com/h5/pages/a/myKey访问也是正常的，但是通过http://a.domain.com/myKey就不正常了，所以应该是域名不同导致的

这听上去有点绕，实际上是有一个二级域名跳转到另一个域名，然后在onPageNotFound中跳转到实际的页面

**Comment by zhetengbiji** [comment]
尝试审查（使用 Chrome 远程调试或者使用 Eruda），看看能否发现什么异常之处

**Comment by endison1986** [comment]
这个明天我试下吧
