### ISSUE TITLE
【小程序开发工具】和【真机】不同展现 的问题

### ISSUE THREAD

**Issue by MQYForverT** [dcloudio/uni-app#3153]
**问题描述**
我使用vk-uView-ui插件，在小程序开发工具表现正常，在真机中使用异常

**复现步骤**
[复现问题的步骤]
1.使用hbuildx创建uni项目，使用vue3
2.去市场引入vk-uView-ui插件（https://ext.dcloud.net.cn/plugin?id=6692）
3.使用u-popop相关组件（如：u-popop、u-modal、u-select）

**预期结果**
小程序开发工具和真机表现正常

**实际结果**
在小程序开发工具表现正常，在真机中使用异常

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 ：Android 7.0+
 - HBuilderX版本：3.3.5
 - vue版本：vue3

**补充信息**
[可选]
我也不知道问题出在哪，我看了二者的样式区别，在开发者工具中表现正常，在真机中异常，且二者的样式生成有区别。
不知道是这个插件的问题还是hbx的问题。

**Comment by fxy060608** [comment]
建议先找插件作者确认

**Comment by MQYForverT** [comment]
> 建议先找插件作者确认

作者说是现在hbx升级了编辑器的问题。我换了alpha3.3.6版本，编译上传之后，还是一样的，开发环境下和真机环境不一致。
按道理说和hbx已经没有关系了，可是小程序上传代码后，在真机却不一样，这是微信那边的问题吗？
能帮忙分析一下吗？

**Comment by fxy060608** [comment]
发测试工程，截图说明差异点
