### ISSUE TITLE
H5 tabbar没有展现安全区域高度

### ISSUE THREAD

**Issue by mentoorliubin** [dcloudio/uni-app#3155]
**问题描述**
在pages.json中配置了原生tabbar 但是使用时tabbar世界上没有安全区的高度，与小程序表现不一致

**复现步骤**
官方hello示例也是一样的表现
![图片](https://user-images.githubusercontent.com/52729282/148346318-dafa954d-9280-4cf3-b986-d8889e8afa86.png)
![图片](https://user-images.githubusercontent.com/52729282/148346334-eca2be69-772e-4a34-a356-e737b684d563.png)

**预期结果**
h5端tabbar可以加上安全区高度

**实际结果**
h5端tabbar未加上安全区高度

**系统信息:**
 - 发行平台: H5
 - 操作系统 ios
 - HBuilderX版本3.3.5

**Comment by StrivingRabbit** [comment]
运行到 vue 几？

**Comment by mentoorliubin** [comment]
> 运行到 vue 几？什么浏览器？

运行到vue3,浏览器为微信内置浏览器，同时safair浏览器也是一样的表现

**Comment by StrivingRabbit** [comment]
@mentoorliubin 我测试下看看

**Comment by StrivingRabbit** [comment]
后续会修复，先告诉你如何临时处理，打开根目录的 index.html，找到以下代码：
```html
<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
```
修改为
```html
    <script>
      var coverSupport = 'CSS' in window && typeof CSS.supports === 'function' && (CSS.supports('top: env(a)') ||
        CSS.supports('top: constant(a)'))
      document.write(
        '<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0' +
        (coverSupport ? ', viewport-fit=cover' : '') + '" />')
    </script>
```

**Comment by mentoorliubin** [comment]
> 后续会修复，先告诉你如何临时处理，打开根目录的 index.html，找到以下代码：
> 
> ```
> <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
> ```
> 
> 修改为
> 
> ```
>     <script>
>       var coverSupport = 'CSS' in window && typeof CSS.supports === 'function' && (CSS.supports('top: env(a)') ||
>         CSS.supports('top: constant(a)'))
>       document.write(
>         '<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0' +
>         (coverSupport ? ', viewport-fit=cover' : '') + '" />')
>     </script>
> ```

好的，这个方法是有效的，谢谢
