### ISSUE TITLE
@dcloudio/types NodesRef缺少node方法

### ISSUE THREAD

**Issue by chengzixian** [dcloudio/uni-app#3159]
**问题描述**

vue3 ts项目无法获取到canvas的node实例
以及另一个问题, vue3 <script setup lang="ts"> 的情况下在App.vue 里getApp()无法获取到实例
想要在App.vue里初始化globalData的数据

[或者可以直接贴源代码]

**预期结果**
1、NodesRef增加node方法描述
2、App.vue里能设置globalData

**实际结果**
![image](https://user-images.githubusercontent.com/23517357/148477499-620bd780-0529-4e4d-b5fd-e9f8a3344209.png)
![image](https://user-images.githubusercontent.com/23517357/148477524-9f71c619-fdff-41d6-a4ad-5808ea96b29e.png)

**系统信息:**
 - 发行平台: [微信小程序]
 - 操作系统 [iOS 12.1.2]
 - @dcloudio/types版本 [2.5.15]

**Comment by zhetengbiji** [comment]
问题1 更新 @dcloudio/types 后重试
注意：仅部分小程序支持此功能
