### ISSUE TITLE
vite 子组件无法更改孙子组件的class样式

### ISSUE THREAD

**Issue by JimmieMax** [dcloudio/uni-app#3161]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
子组件无法更改孙子组件的class样式，但在页面组件里可以更改子组件样式
![image](https://user-images.githubusercontent.com/19659812/148525685-ff6e622d-3ab3-4933-85f9-dc9f66e87cc5.png)

**Comment by okxiaoliang4** [comment]
@fxy060608 遇到同样问题，请问是否支持 externalClasses 呢？

**Comment by fxy060608** [comment]
> 

支持，但不跨平台

**Comment by JimmieMax** [comment]
setup写法如何设置options呢

**Comment by okxiaoliang4** [comment]
> setup写法如何设置options呢

@JimmieMax 
再写多一个script
```html
<script setup>
import {defineComponent} from 'vue'
// your code...
</script>

<script>
export default defineComponent({
  options: {
  }
})
</script>
```

**Comment by okxiaoliang4** [comment]
> 支持，但不跨平台

@fxy060608 设置了无效，尝试过好多次了

**Comment by fxy060608** [comment]
> > 支持，但不跨平台
> 
> @fxy060608 设置了无效，尝试过好多次了

确认了下，目前是有问题，短期内可能不太好解决

**Comment by okxiaoliang4** [comment]
@fxy060608 这个问题还没有解决吗？我目前试了一下好像还是不行呢

**Comment by zhenyuWang** [comment]
临时解决方案可参考 https://ask.dcloud.net.cn/question/163695
