### ISSUE TITLE
编译为小程序时，组件开启options: { virtualHost: true } 后，在组件外部定义的class能添加到组件上

### ISSUE THREAD

**Issue by Xyuan-abs** [dcloudio/uni-app#3162]
![image](https://user-images.githubusercontent.com/64180387/148630251-5478f612-9e2c-4f01-900d-f50ddfbe35b1.png)

**新功能描述**
编译为小程序时，组件开启options: { virtualHost: true } 后，在组件外部定义的class能添加到组件上，像编译成h5这样
![image](https://user-images.githubusercontent.com/64180387/148630455-19a7154d-ac5a-4278-b08a-958126f1cd18.png)

**现状及问题**
组件外部定义的class 没有添加到组件上，无法通过添加外部class来设置样式

**尝试方案**
在每个组件外在包一层view  但是太过繁琐了

**Comment by fxy060608** [comment]
这应该是小程序自身实现问题，可以到小程序社区咨询
