### ISSUE TITLE
button标签与@vue/runtime-dom中类型定义冲突

### ISSUE THREAD

**Issue by zhuchentong** [dcloudio/uni-app#3163]
**问题描述**
button标签与@vue/runtime-dom中类型定义冲突

**复现步骤**
在VSCODE中使用`button`标签设置`type`字段是报错

**预期结果**
实现button的类型重写

**实际结果**
![cf2584d13cee8505aa8cba7cffc4c29](https://user-images.githubusercontent.com/4535888/148651380-b4a1e4e9-fda2-41f1-a706-e3c63d548c1a.png)

**系统信息:**
 - uni-app版本 3.2.16.20211122
 - 项目类型 vue3使用cli创建项目

**Comment by lanjun20170501** [comment]
好早就发现这个问题，楼主你有解决吗？

**Comment by zhuchentong** [comment]
> 好早就发现这个问题，楼主你有解决吗？

没有解决 使用了类似uview的UI库了

**Comment by Hisioni** [comment]
mark，一样有这个问题，不知道怎么配置，ts

**Comment by ifzm** [comment]
头疼，不知道怎么覆盖掉

**Comment by moslixiansen** [comment]
2023了,官方还不给vscode做支持吗?
