### ISSUE TITLE
vue3 setup写法 无法用directive 

### ISSUE THREAD

**Issue by JimmieMax** [dcloudio/uni-app#3164]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
![image](https://user-images.githubusercontent.com/19659812/148669020-c490fe69-9b01-415b-a134-12c4dcea95c5.png)
全局和局部的directive都报错
`[plugin:vite:vue] unknown directive{"type":7,"name":"format-money","modifiers":[],"loc":{"start":{"column":13,"line":37,"offset":811},"end":{"column":27,"line":37,"offset":825},"source":"v-format-money"}}`

**Comment by fxy060608** [comment]
说明平台，小程序目前不支持

**Comment by JimmieMax** [comment]
就是小程序

**Comment by fxy060608** [comment]
小程序端没有dom相关操作，不支持此类自定义指令
