### ISSUE TITLE
vite vue3 setup 微信小程序端无法画图

### ISSUE THREAD

**Issue by JimmieMax** [dcloudio/uni-app#3166]
**问题描述**
无法使用canvas画图
```
  const ctx = uni.createCanvasContext('pui-canvas');
  console.log(ctx);
  ctx.setFillStyle('#000000');
  ctx.fillRect(0, 0, 100, 75);
  ctx.draw();
```
canvas有占位，但是不显示画出的内容

**Comment by fxy060608** [comment]
确保自己的调用时机，放到onMounted中

**Comment by JimmieMax** [comment]
已解决，是自己的问题

**Comment by JimmieMax** [comment]
不对，页面里是可以先试，但是在子组件里还是不行

**Comment by JimmieMax** [comment]
> 确保自己的调用时机，放到onMounted中

不对，页面里是可以显示，但是在子组件里还是不行

**Comment by fxy060608** [comment]
> > 确保自己的调用时机，放到onMounted中
> 
> 不对，页面里是可以显示，但是在子组件里还是不行

组件里要传入上下文，比如getCurrentInstance(),
