### ISSUE TITLE
获取组件实例

### ISSUE THREAD

**Issue by okxiaoliang4** [dcloudio/uni-app#3167]
**问题描述**
支付宝端 selectComponent 无法获取组件实例

**复现步骤**
```typescript
const ctx = getCurrentInstance()!.ctx as any
ctx.selectComponent('.custom-header')
```

**预期结果**
selectComponent 返回组件对象

**实际结果**
`undefined`

**系统信息:**
 - 支付宝小程序
 - @dcloudio/uni-app@3.0.0-alpha-3030520211229004

**补充信息**
支付宝端是否无法选择组件对象，那如何查询组件boundingRect呢？

**Comment by okxiaoliang4** [comment]
```javascript
// 支付宝小程序使用查询节点的方式选择组件
ctx.createSelectorQuery().in(ctx).select('xxx').boundingRect()
```

**Comment by okxiaoliang4** [comment]
解决了组件boundingRect查询问题，但是如果想读取组件内数据需要如何操作呢

**Comment by fxy060608** [comment]
> 解决了组件boundingRect查询问题，但是如果想读取组件内数据需要如何操作呢

ref

**Comment by fxy060608** [comment]
> @fxy060608 ref无法获取到，麻烦看看这个issue #3168

目前ref只支持组件，内置组件不支持

**Comment by okxiaoliang4** [comment]
> > @fxy060608 ref无法获取到，麻烦看看这个issue #3168
> 
> 目前ref只支持组件，内置组件不支持

@fxy060608  你好，ref获取组件是空的Proxy对象，无法访问到组件内属性

![image](https://user-images.githubusercontent.com/22525904/155667761-d9af10dc-0f9e-425a-acbb-813945874a92.png)

uni版本：3.0.0-alpha-3030820220114003

**Comment by fxy060608** [comment]
> > > @fxy060608 ref无法获取到，麻烦看看这个issue #3168
> > 
> > 
> > 目前ref只支持组件，内置组件不支持
> 
> @fxy060608 你好，ref获取组件是空的Proxy对象，无法访问到组件内属性
> 
> ![image](https://user-images.githubusercontent.com/22525904/155667761-d9af10dc-0f9e-425a-acbb-813945874a92.png)
> 
> uni版本：3.0.0-alpha-3030820220114003

贴代码，发测试工程

**Comment by okxiaoliang4** [comment]
我忘记`expose`了,sorry
