### ISSUE TITLE
setup ref 无法获取节点

### ISSUE THREAD

**Issue by okxiaoliang4** [dcloudio/uni-app#3168]
**问题描述**
使用setup语法声明ref，小程序环境无法获取template节点

**复现步骤**
```vue
<template>
  <view ref="content"> </view>
<template>

<script setup>
import {onMounted} from 'vue'

const content = ref()
onMounted(() => {
  console.log(content) // 小程序中undefined
})
</script>
```

**预期结果**
节点对象

**实际结果**
`undefined`

**系统信息:**
 - 小程序
 - @dcloudio/uni-app@3.0.0-alpha-3030520211229004

**补充信息**
是否在小程序端可以编译成这样？

编译后wxml:
```vue
<view class="uni_ref_01"></view>
```
```javascript
const content = ref()
content.value = ctx.createSelectorQuery().in(ctx).select('.uni_ref_01') // node
```
如果是组件则相应为
```javascript
const content = ref()
ctx.selectComponent('.uni_ref_01') // component
```

支付宝端没有selectComponent则同为上一种方式
>```javascript
> const content = ref()
> content.value = ctx.createSelectorQuery().in(ctx).select('.uni_ref_01') // node
> ```

**Comment by fxy060608** [comment]
内置组件通过createSelectorQuery获取NodeRef也跟 h5 等平台不一样啊，解决了什么问题呢？就是省了自己手动调用createSelectorQuery吗？

**Comment by okxiaoliang4** [comment]
> 内置组件通过createSelectorQuery获取NodeRef也跟 h5 等平台不一样啊，解决了什么问题呢？就是省了自己手动调用createSelectorQuery吗？

可以这么理解

**Comment by fxy060608** [comment]
> > 内置组件通过createSelectorQuery获取NodeRef也跟 h5 等平台不一样啊，解决了什么问题呢？就是省了自己手动调用createSelectorQuery吗？
> 
> 可以这么理解

1. createSelectorQuery 是异步的，如果封装成ref，可能时机问题不太好把控，毕竟标准的ref，在onMounted中就要可以访问到的
2. 当需要跨平台到H5时，用ref似乎也得区分平台写代码，还不如自己统一使用createSelectorQuery来跨平台调用获取节点信息
