### ISSUE TITLE
style样式使用v-bind绑定动态值在小程序中无效

### ISSUE THREAD

**Issue by jacksonyu** [dcloudio/uni-app#3169]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
在 <style> 中使用 v-bind() 绑定动态值，在 H5 中有效，在微信小程序中无效
 
**复现步骤**
[复现问题的步骤]
```
<template>
	<view>
		<view class="ss">
			123
		</view>
	</view>
</template>

<script setup>
	import { ref } from "vue";
	const c = ref('red')
</script>

<style scoped>
	.ss{
		color: v-bind(c);
		margin-top: 250px;
	}
</style>
```

**预期结果**
在 H5 和小程序中都能生效

**实际结果**
在 H5 中有效，在微信小程序中无效
H5:
![1.jpg](https://s2.loli.net/2022/01/10/Lurnpl6kfh8jeYS.jpg)

小程序：
![2.jpg](https://s2.loli.net/2022/01/10/fbwaq7EFdXPsGjA.jpg)

**系统信息:**
 - 发行平台: 微信小程序、H5平台
 - HBuilderX版本：3.3.5
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
可以更换到Alpha 3.3.6测试

**Comment by jacksonyu** [comment]
> 可以更换到Alpha 3.3.6测试

alpha 3.3.6 问题依旧。

**Comment by fxy060608** [comment]
> > 可以更换到Alpha 3.3.6测试
> 
> alpha 3.3.6 问题依旧。

如果使用HBuilderX，到HBuilderX/plugins/uniapp-cli-vite中
更改package.json中@dcloudio相关包版本为：3.0.0-alpha-3030520211229004
重新yarn安装，运行，如果是windows，提示esbuild的32位包没有找到，到node_modules中，把64位的包重命名为32位的

**Comment by jacksonyu** [comment]
> 



> > > 可以更换到Alpha 3.3.6测试
> > 
> > 
> > alpha 3.3.6 问题依旧。
> 
> 如果使用HBuilderX，到HBuilderX/plugins/uniapp-cli-vite中 更改package.json中@dcloudio相关包版本为：3.0.0-alpha-3030520211229004 重新yarn安装，运行，如果是windows，提示esbuild的32位包没有找到，到node_modules中，把64位的包重命名为32位的

手动更新版本后 问题解决。
谢谢指导。

**Comment by zatsunen** [comment]
我现在@dcloudio相关包版本是3.0.0-alpha-4030520241124001，也还是有这个问题，请问要怎么处理
