### ISSUE TITLE
百度小程序demo中的picker-view展示好像有点问题

### ISSUE THREAD

**Issue by 1353619565** [dcloudio/uni-app#317]
**百度小程序demo中的picker-view展示好像有点问题**
下方的选择器在进行日期选择后，会重置到默认的当前日期，而不是展示当前选择的日期

**复现步骤**
1.  百度APP扫描百度小程序版体验码
2. 点击实例--->组件--->picker-view
3. 日期选择后 下面的选择器会重置到默认的当前日期

**预期结果**
下方的选择器在进行日期选择后不是应该展示当前选择的日期吗

**实际结果**
选择器会重置到默认的当前日期

**Comment by 1353619565** [comment]
支付宝小程序demo中的picker-view也有点问题
进入实例展示后，年份有时会错误展示为1990年，然后滑动月份，上方日期展示中的年份会消失掉

**Comment by zhetengbiji** [comment]
对应小程序平台的开发人员已修复
