### ISSUE TITLE
小程序自定义组件的this如何获取

### ISSUE THREAD

**Issue by dwfrost** [dcloudio/uni-app#3174]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
在使用 wx.createCanvasContext(string canvasId, Object this)方法时，发现在vue3 setup下没有this了，有什么办法获取吗

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

1.父组件

```vue
<template>
    <MyCanvas/>
</template>
<script setup lang="ts">
import MyCanvas from './MyCanvas.vue'
</script>
```

2.子组件

```vue
<template>
    <canvas canvas-id="myCanvas"></canvas>
</template>
<script setup lang="ts">
setTimeout(() => {
  let that = this // @todo 这里获取不到this
  const ctx = wx.createCanvasContext('myCanvas', that)
  ctx.arc(100, 75, 50, 0, 2 * Math.PI)
  ctx.setFillStyle('#EEEEEE')
  ctx.fill()
  ctx.draw()
}, 1000)
</script>
```

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
预期在上文@todo处可以传入组件的this

**实际结果**
[这里请贴上你的报错截图或文字]
实际获取不到this，canvas无法绘制。

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 微信开发者工具windows版
 - HBuilderX版本 无
 - uni-app版本     "@dcloudio/uni-app": "^3.0.0-alpha-3030520211229002",
 - 设备信息 微信开发者工具

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
支持传入 getCurrentInstance()

**Comment by dwfrost** [comment]
在微信开发者工具上获取返回null。
```ts
    import { getCurrentInstance} from 'vue'
    let that = getCurrentInstance()
    console.log(that) // null
```

**Comment by fxy060608** [comment]
> 在微信开发者工具上获取返回null。
> 
> ```ts
>     import { getCurrentInstance} from 'vue'
>     let that = getCurrentInstance()
>     console.log(that) // null
> ```

确保你的调用时机是在setup中，而不是什么setTimeout之类的，如果有问题，发完整代码

**Comment by dwfrost** [comment]
去掉setTimeout了，that有值，不过canvas还是没有绘制，大佬看看是什么原因
```vue
<template>
  <canvas canvas-id="barcode"></canvas>
</template>
<script setup lang="ts">
import { getCurrentInstance } from 'vue'

let that = getCurrentInstance()
console.log('that', that)
const ctx = wx.createCanvasContext('myCanvas', that)
ctx.arc(100, 75, 50, 0, 2 * Math.PI)
ctx.setFillStyle('#EEEEEE')
ctx.fill()
ctx.draw()
</script>

```
![image](https://user-images.githubusercontent.com/26833988/148745045-00b43fc1-5970-4f36-b808-c16881eaa85e.png)

**Comment by dwfrost** [comment]
我错了，写错id了，去掉setTimeout就可以了，谢谢~
