### ISSUE TITLE
webview组件error事件在支付宝小程序端不触发？

### ISSUE THREAD

**Issue by iSept** [dcloudio/uni-app#3177]
**问题描述**
webview组件error事件在支付宝小程序端不触发，不管网页加载正常还是异常，触发的都是load事件，微信小程序端正常

**复现步骤**

```
<template>
  <web-view
    :src="webviewUrl"
    @message="onMessage"
    @load="onLoadH5"
    @error="onErrorH5"
  ></web-view>
</template>

<script>
export default {
  data() {
    return {
      webviewUrl: "",
    };
  },
  onLoad() {
    this.webviewUrl = "https://www.baidu.com/xxx";
  },
  methods: {
    onMessage(e) {},
    onLoadH5(e) {
      console.log("onLoadH5", e);
    },
    onErrorH5(e) {
      console.log("onErrorH5", e);
    },
  },
};
</script>
```

**预期结果**
支付宝小程序端返回error事件结果正常

**实际结果**

支付宝小程序结果：（异常）

![image](https://user-images.githubusercontent.com/39308436/148748992-81a655c7-be58-49b5-a0dc-053a7f1e66f2.png)

微信小程序结果：（正常）

![image](https://user-images.githubusercontent.com/39308436/148749139-5e5d7aca-9c73-41b0-8d21-f0bf7fbec6e5.png)

**系统信息:**
 - 发行平台: 微信小程序、支付宝小程序
 - HBuilderX版本： 3.3.5.20211229
 - uni-app版本： uni-app v3.3.5        uni-app cli v2.0.1-33520211229002

**Comment by zhetengbiji** [comment]
直接使用支付宝小程序（不使用uni-app）测试是否正常？

**Comment by iSept** [comment]
> 直接使用支付宝小程序（不使用uni-app）测试是否正常？

真机测试支付宝小程序会触发error，但是也触发了load事件（不应该触发）
![image](https://user-images.githubusercontent.com/39308436/148894056-d5b7d231-7f6f-4966-b8b4-4b6eb61d20ad.png)



真机测试微信小程序仅仅触发 error
![image](https://user-images.githubusercontent.com/39308436/148894847-cfee630a-5237-4fde-85de-e9ec8cf20fd4.png)

**Comment by zhetengbiji** [comment]
直接使用支付宝小程序（不使用uni-app）测试是否正常？
