### ISSUE TITLE
在hbuilder中允许新建的uni-app报错

### ISSUE THREAD

**Issue by heroofchina** [dcloudio/uni-app#318]
1.在hbuilder中新建uni-app项目，项目名称叫做mp_app,选择登录模版
2.启动 ios 模拟器 iphone 6 (12.2)
3.选项目运行到ios模拟器 ，报错：

 { Error: ENOENT: no such file or directory, open '/Users/username/desktop/mp_app/unpackage/dist/dev/.tmp/app-plus/app.json'
10:27:12.795     at Object.fs.openSync (fs.js:646:18)
10:27:12.810     at Object.fs.readFileSync (fs.js:551:33)
10:27:12.810     at parseConfig (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/weapp-tools/lib/index.js:1:4187)
10:27:12.824     at index (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/weapp-tools/lib/index.js:1:13595)
10:27:12.825     at Promise (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-hbuilderx/packages/webpack-app-plus-plugin/index.js:17:11)
10:27:12.842     at new Promise (<anonymous>)
10:27:12.854     at compiler.hooks.done.tapPromise.compilation (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-hbuilderx/packages/webpack-app-plus-plugin/index.js:12:14)
10:27:12.874     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:17:17)
10:27:12.899     at AsyncSeriesHook.lazyCompileHook (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/tapable/lib/Hook.js:154:20)
10:27:12.900     at Watching._done (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/webpack/lib/Watching.js:97:28)
10:27:12.923     at compiler.emitRecords.err (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/webpack/lib/Watching.js:72:19)
10:27:12.923     at Compiler.emitRecords (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/webpack/lib/Compiler.js:375:39)
10:27:12.950     at compiler.emitAssets.err (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/webpack/lib/Watching.js:53:20)
10:27:12.951     at hooks.afterEmit.callAsync.err (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/webpack/lib/Compiler.js:361:14)
10:27:12.981     at _err0 (eval at create (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/tapable/lib/HookCodeFactory.js:32:10), <anonymous>:20:1)
10:27:13.010     at callback (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/copy-webpack-plugin/dist/index.js:126:17)
10:27:13.041   errno: -2,
10:27:13.041   code: 'ENOENT',
10:27:13.071   syscall: 'open',
10:27:13.072   path: '/Users/username/desktop/mp_app/unpackage/dist/dev/.tmp/app-plus/app.json' }
10:27:13.103 [ERROR] 读取app.json失败...
10:27:13.103 ENOENT: no such file or directory, copyfile '/Users/username/desktop/mp_app/unpackage/dist/dev/.tmp/app-plus/manifest.json' -> '/Users/username/desktop/mp_app/unpackage/dist/dev/app-plus/manifest.json'

hbuilder版本 1.9.2.

系统版本  MAC OSX Mojave 10.14.4和  MAC OSX High Sierra都有这样的问题

**Comment by mehaotian** [comment]
问题未能重现，尝试升级，或者回退编辑器版本试一下。

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
