### ISSUE TITLE
vue3.0 vite setup defineExpose无效

### ISSUE THREAD

**Issue by okxiaoliang4** [dcloudio/uni-app#3180]
**问题描述**
defineExpose定义的属性在实例上没有显示

**复现步骤**
```typescript
const a = ref(true)
defineExpose({
  a
})
```

**预期结果**
实例上暴露出`a`属性

**实际结果**
未暴露

**系统信息:**
 - 小程序
 - @dcloudio/uni-app@3.0.0-alpha-3030520211229004

**Comment by fxy060608** [comment]
如何确认的没有暴露

**Comment by okxiaoliang4** [comment]
> 如何确认的没有暴露

例如´selectComponent´查找出来的实例´$vm´中没有该属性，用´defineComonent´定义的属性方法就有

**Comment by fxy060608** [comment]
目前可以先使用 Template Ref 获取到

**Comment by fxy060608** [comment]
> > 如何确认的没有暴露
> 
> 例如`selectComponent`查找出来的实例`$vm`中没有该属性，用`defineComonent`定义的属性方法就有

目前可以先使用 Template Ref 获取到

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030720220111003

**Comment by zhuddan** [comment]
3.0.0-3090620231104002 
没有暴露
