### ISSUE TITLE
uniCloud的field中选择对象或对象数组用{} + as 有bug 如图

### ISSUE THREAD

**Issue by cn-kelon** [dcloudio/uni-app#3181]
最后只能用.的方式解决的问题  用{}+as 需要注意

![06~ ~64Z{3%HH329LRM)_8S](https://user-images.githubusercontent.com/46063184/149055232-503fa89a-a338-43ec-98fe-c9bd5b64a33d.png)
![$5KP{)36`M047 A1%{`I8ID](https://user-images.githubusercontent.com/46063184/149055267-43fa838b-f737-4d88-a05d-988e2ba59c44.png)
![6{EIEF@0XV3_XT_Q2ZB2@YF](https://user-images.githubusercontent.com/46063184/149055284-1d199afb-343c-4585-9528-298209de139b.png)
![Y4)T(P73)HDLTO70F6DWMFQ](https://user-images.githubusercontent.com/46063184/149055298-3ea7157f-318d-4c28-a42b-c57c79de8cc3.png)
![V7W8C98HI$Q4{V77IB %(O3](https://user-images.githubusercontent.com/46063184/149055326-7234d246-9917-4f7a-a0b1-cc8e1edcd64f.png)

**Comment by Wangyaqi** [comment]
实际上单表是不允许使用花括号的，但是考虑到兼容问题此处未进行限制，使用可能会得到预期之外的结果
