### ISSUE TITLE
UniApp的video标签在微信内置浏览器显示的时长不对为“00:00”

### ISSUE THREAD

**Issue by lzz520** [dcloudio/uni-app#3182]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
IOS下微信内置浏览器打开H5页面，UniApp的video标签在微信内置浏览器显示的时长不对为“00:00”，其他浏览器正常显示
**复现步骤**
[复现问题的步骤]
在微信内置浏览器中打开官方示例查看即可
https://hellouniapp.dcloud.net.cn/pages/component/video/video

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [iPhone11]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
目前微信内置浏览器是自研浏览器内核，对于非白名单的域名一般会强制使用原生播放器替换video组件用于提供一些高级功能或者加载广告等，导致一系列的兼容问题。
