### ISSUE TITLE
升级最新版(1.9.2)HBuilder X H5运行白屏

### ISSUE THREAD

**Issue by CR903** [dcloudio/uni-app#319]
**问题描述**
升级最新版(1.9.2)HBuilder X H5运行白屏

**复现步骤**
运行H5直接白屏

**预期结果**
进入主页，可以运行

**实际结果**
![image](https://user-images.githubusercontent.com/7643647/56407978-cc1b2380-62a4-11e9-9050-829be79140ca.png)

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 Google浏览器
 - HBuilderX版本 1.9.2
 - uni-app版本 HBuilderX内置版本
 - 设备信息
![image](https://user-images.githubusercontent.com/7643647/56408015-0258a300-62a5-11e9-8f92-d23f6178beac.png)

**Comment by XGPASS** [comment]
Safari浏览器也有问题；1.9.2.20190417版本，在iOS8和iOS9上的Safari白屏。iOS10及其以上正常显示；我是直接运行的官方的demo

**Comment by fxy060608** [comment]
1.HBuilderX 运行预览 h5 白屏的问题，1.9.3 alpha 会修复此问题（1.9.2正式版无此问题）
2.Safari 低版本运行 h5 白屏的问题，1.9.3 alpha 会修复次问题

**Comment by CR903** [comment]
1.9.3 alpha 已修复！
