### ISSUE TITLE
Vue3 支付宝小程序mixin props异常

### ISSUE THREAD

**Issue by okxiaoliang4** [dcloudio/uni-app#3191]
**问题描述**
支付宝mixin props异常

**复现步骤**
mixin中带有props字段会出现异常

**预期结果**
正常mixin

**实际结果**
![image](https://user-images.githubusercontent.com/22525904/149279366-594fe366-057c-4bee-89ea-bca0aa9584d0.png)
![image](https://user-images.githubusercontent.com/22525904/149279955-f040afbc-46fc-4e94-b9b3-627ce6662859.png)

**系统信息:**
 - 支付宝小程序
 - @dcloudio/uni-app 3.0.0-alpha-3030520211229001

**补充信息**
![image](https://user-images.githubusercontent.com/22525904/149279545-f195b6af-ca85-42d2-b0be-598184d047f9.png)
https://github.com/dcloudio/uni-app/blob/0edd43ecafaebd2b7a638ecccf3d527702eecf43/src/core/runtime/wrapper/util.js#L183-L201

看起来与源码中不太一样，是否没发布版本？

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030720220111004
