### ISSUE TITLE
Vue3 下无法在开发者工具 AppData 中看到变量

### ISSUE THREAD

**Issue by iceDays** [dcloudio/uni-app#3192]
**新功能描述**
Taro 提供了 DevTools 去查看, uni 是否有类似规划?

相关链接: 
https://github.com/NervJS/taro-rfcs/blob/master/rfcs/0006-vue-devtools.md

**Comment by fxy060608** [comment]
有计划提供，目前时间还没排出来

**Comment by sxdlh123** [comment]
蹲一个 现在只能console.log 属实麻烦。。。

**Comment by Liangqianyong** [comment]
蹲一个

**Comment by Dongary** [comment]
我也来蹲一个

**Comment by zhenyuWang** [comment]
uni-vue-devtools 目前处于灰度中，临时文档：https://flowus.cn/share/dd27ade9-290c-44a4-881a-058fdb8015e7，欢迎体验并反馈意见

**Comment by zhenyuWang** [comment]
HBuilderX 3.7.0 及 cli 3.0.0-alpha-3070020230117001+ 已支持 [Vue Devtools](https://uniapp.dcloud.net.cn/tutorial/debug/uni-vue-devtools.html)

**Comment by asasugar** [comment]
不支持 script setup ? 大部分vue3都是setup写法

**Comment by Dongary** [comment]
我来蹲一个 希望支持  script setup

**Comment by FAOfao931013** [comment]
等一个 支持 setup

**Comment by qinshige** [comment]
蹲一个 希望支持 setup  提升开发体验

**Comment by bugaio** [comment]
蹲一个 希望支持 setup 提升开发体验

**Comment by dodu2014** [comment]
貌似vue3的大多项目都是 setup 语法糖，希望能尽快支持，非常感谢 uniapp 团队的付出。好样的。

**Comment by zhenyuWang** [comment]
对 setup 语法糖的支持可以来 [需求墙](https://vote.dcloud.net.cn/#/?name=uni-app) 反馈或投票，谢谢

**Comment by wendell0316** [comment]
> 对 setup 语法糖的支持可以来 [需求墙](https://vote.dcloud.net.cn/#/?name=uni-app) 反馈或投票，谢谢

我看投票里没有这个选项哎，现在有计划支持了么

**Comment by Su0515** [comment]
蹲一个 希望支持 setup 提升开发体验

**Comment by ghd133** [comment]
25年了，还不支持

**Comment by zhenyuWang** [comment]
可以使用 [uni-vue-devtools](https://uniapp.dcloud.net.cn/tutorial/debug/uni-vue-devtools.html) 工具进行调试
注：暂不支持 vue3 script setup

**Comment by semanticDao** [comment]
> 可以使用 [uni-vue-devtools](https://uniapp.dcloud.net.cn/tutorial/debug/uni-vue-devtools.html) 工具进行调试 注：暂不支持 vue3 script setup

这是最搞笑的. 谁vue3不用setup啊.,

**Comment by GraBerry** [comment]
26年了,还不支持,有别的解决办法吗

**Comment by cheny-github** [comment]
难顶
