### ISSUE TITLE
模板中 `v-for="index of 3"` 不能工作

### ISSUE THREAD

**Issue by fisker** [dcloudio/uni-app#3193]
**问题描述**

RT

**复现步骤**

```vue
<view v-for="index of 3">{{index}}</view>
```

**预期结果**

```vue
<view>1</view>
<view>2</view>
<view>3</view>
```

**实际结果**

空白

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

最新版 uni-app + vite + vue3, 其他信息应该没什么关系

**补充信息**

不使用 `index` 变量名则可以正常工作.

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030820220114001
HBuilderX Alpha 稍后发布3.3.8

**Comment by fisker** [comment]
感谢, 确认已修复.
