### ISSUE TITLE
vue3使用vuex控制台报警告

### ISSUE THREAD

**Issue by zcSkr** [dcloudio/uni-app#3194]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
Non-existent export 'default' is imported from node_modules/@dcloudio/uni-mp-vue/dist/vue.runtime.esm.js

**复现步骤**
[复现问题的步骤]
1.main.js只要引入 import store from './store' 控制台就会报警告
[2.vuex的使用也是参考uni文档](https://uniapp.dcloud.io/migration-to-vue3?id=vue2-%e9%a1%b9%e7%9b%ae%e8%bf%81%e7%a7%bb-vue3%ef%bc%8c%e5%bf%85%e9%a1%bb%e9%80%82%e9%85%8d%e7%9a%84%e9%83%a8%e5%88%86)
3.store/index.js如下
![image](https://user-images.githubusercontent.com/30515821/149617833-736b027e-cee1-491d-98c9-e63ccc905827.png)

**预期结果**
预期不希望出现警告/报错之类的信息。

**实际结果**
![image](https://user-images.githubusercontent.com/30515821/149617751-1d60f9ff-66cd-40ca-ac65-54f536957cbc.png)

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本 3.3.5.20211229

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
自己代码问题，第一行 `import Vue from 'vue'`

**Comment by zcSkr** [comment]
> 自己代码问题，第一行 `import Vue from 'vue'`

感谢🙏

**Comment by GD-Cassie** [comment]
> 

第一行怎么了?
<img width="673" alt="image" src="https://user-images.githubusercontent.com/13307620/181412568-f730925e-70c4-4cfd-af48-5dcd7f79f79d.png">
<img width="1239" alt="image" src="https://user-images.githubusercontent.com/13307620/181412648-ae77f6fd-9d6b-4e8b-bc86-49dded76b570.png">

**Comment by Yohuaye** [comment]
> > 
> 
> 第一行怎么了? <img alt="image" width="673" src="https://user-images.githubusercontent.com/13307620/181412568-f730925e-70c4-4cfd-af48-5dcd7f79f79d.png"> <img alt="image" width="1239" src="https://user-images.githubusercontent.com/13307620/181412648-ae77f6fd-9d6b-4e8b-bc86-49dded76b570.png">

我也遇到这个问题了，请问有解决方案了吗
