### ISSUE TITLE
vue3 + vite 不支持原生HTML标签了吗？

### ISSUE THREAD

**Issue by xcplovelhq** [dcloudio/uni-app#3196]
![image](https://user-images.githubusercontent.com/20986739/149785520-4461dae0-9bdd-4f93-a3d6-8725b5268d17.png)

现在这块新版Vue3 + vite是不支持了吗？

**Comment by xcplovelhq** [comment]
我想问的是小程序的

**Comment by fxy060608** [comment]
> 我想问的是小程序的

标签会转换，标签样式不再支持，不建议这么使用
