### ISSUE TITLE
vue3 在 v-if 中使用 wxs 报错

### ISSUE THREAD

**Issue by jin-yufeng** [dcloudio/uni-app#3199]
**问题描述**
`vue3` 在 `v-if` 中使用 `wxs` 报错，`vue2` 正常

**复现步骤**
```vue
<template>  
    <view>  
        <view v-if="test.aa()">123</view>  
    </view>  
</template>  
<script module="test" lang="wxs">  
    function aa() {  
        return true  
    }  
    module.exports = {  
        aa: aa  
    }  
</script>
```
`vue` 版本选择 `3`，运行到微信小程序

**预期结果**
正常运行

**实际结果**
报错 `ReferenceError: test is not defined`

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本 `3.3.8`

**Comment by okxiaoliang4** [comment]
遇到同样问题

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030820220114003

**Comment by jin-yufeng** [comment]
@fxy060608 `app` 端也有问题，虽然不会报错，但是 `wxs` 返回 `false` 还是会显示

**Comment by fxy060608** [comment]
> @fxy060608 `app` 端也有问题，虽然不会报错，但是 `wxs` 返回 `false` 还是会显示

具体是什么样子的业务需求，需要在 if 里边访问 wxs 中的内容呢？是否有其他方案可以先绕过去

**Comment by okxiaoliang4** [comment]
> > @fxy060608 `app` 端也有问题，虽然不会报错，但是 `wxs` 返回 `false` 还是会显示
> 
> 具体是什么样子的业务需求，需要在 if 里边访问 wxs 中的内容呢？是否有其他方案可以先绕过去

他需求应该是这个，我正好有在vue3.0用他的库适配的时候也是遇到一样问题
https://github.com/jin-yufeng/mp-html/blob/master/src/uni-app/components/mp-html/node/node.vue#L57

**Comment by jin-yufeng** [comment]
不方便改的话我试试其他方案吧

**Comment by okxiaoliang4** [comment]
可以用computed先代替吧？

**Comment by okxiaoliang4** [comment]
之前wxs不行的时候我是先用computed代替了

**Comment by fxy060608** [comment]
> 不方便改的话我试试其他方案吧

建议可以先绕一下，app端修复这个问题会麻烦一些，时间上不一定保证

**Comment by okxiaoliang4** [comment]
@fxy060608 3.0.0-alpha-3031020220124001 这个版本wxs异常问题又出现了

**Comment by fxy060608** [comment]
> @fxy060608 3.0.0-alpha-3031020220124001 这个版本wxs异常问题又出现了

锁死版本不使用^升级

**Comment by okxiaoliang4** [comment]
> > @fxy060608 3.0.0-alpha-3031020220124001 这个版本wxs异常问题又出现了
> 
> 锁死版本不使用^升级

好的
