### ISSUE TITLE
h5 平台 html 中引入 static 目录的 js 文件包含 ifdef 编译报错

### ISSUE THREAD

**Issue by z3214965** [dcloudio/uni-app#3201]
**问题描述**
自定义编写一个umd模块工具，通过html中script引入，vue2中可以找到相应对象，但vue3中提示找不到对应对象

**预期结果**
达到vue2中效果

**实际结果**
![捕获1](https://user-images.githubusercontent.com/18589356/150053593-531349ef-6893-435e-993c-a6a5a05c11a0.PNG)

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 window10
 - HBuilderX版本 最新版本

**Comment by fxy060608** [comment]
详细说明使用方式

**Comment by z3214965** [comment]
@fxy060608 
![捕获2](https://user-images.githubusercontent.com/18589356/150058678-4ecc36ad-f086-4ecc-a181-d3f95bd90077.PNG)
直接在html界面引入

![捕获3](https://user-images.githubusercontent.com/18589356/150058787-dde8fc55-933f-4e90-bff2-dab579c2bf3a.PNG)
直接在组件中使用

**Comment by fxy060608** [comment]
> @fxy060608 ![捕获2](https://user-images.githubusercontent.com/18589356/150058678-4ecc36ad-f086-4ecc-a181-d3f95bd90077.PNG) 直接在html界面引入
> 
> ![捕获3](https://user-images.githubusercontent.com/18589356/150058787-dde8fc55-933f-4e90-bff2-dab579c2bf3a.PNG) 直接在组件中使用

vue3 使用的是index.html，你是不是代码没在这个文件里加？

**Comment by z3214965** [comment]
@fxy060608 
![捕获4](https://user-images.githubusercontent.com/18589356/150061808-b6874d03-ca77-4eee-ba8c-fd3066bbf6a0.PNG)

**Comment by fxy060608** [comment]
> @fxy060608 ![捕获4](https://user-images.githubusercontent.com/18589356/150061808-b6874d03-ca77-4eee-ba8c-fd3066bbf6a0.PNG)

你怎么加的，我这里测试没有问题

```html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport"
            content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0" />
        <title></title>
        <!--preload-links-->
        <!--app-context-->
    </head>
    <body>
        <script src="/static/dlkj.js"></script>
        <div id="app">
            <!--app-html-->
        </div>
        <script type="module" src="/main.js"></script>
    </body>
</html>

```

**Comment by z3214965** [comment]
@fxy060608 
测试项目：git@github.com:z3214965/test-uniapp.git
麻烦你了，谢谢！

**Comment by fxy060608** [comment]
> @fxy060608 测试项目：https://github.com/z3214965/test-uniapp 麻烦你了，谢谢！

临时方案，可以把你的这个 js 上传到一个网络地址，html 中引入该网络地址

**Comment by z3214965** [comment]
@fxy060608 
好的，谢谢！
