### ISSUE TITLE
微信小程序webview和小程序无法实时通讯问题，如何开启v3编译？

### ISSUE THREAD

**Issue by chinafelix** [dcloudio/uni-app#3202]
**问题描述**
微信小程序，在webview的h5里通过uni.postMessage发送，webview里无法实时接收到消息，要在页面返回才能接收到；我看有说开启v3编译的，不知道怎么开启，有文档链接吗？
**复现步骤**
[复现问题的步骤]
如何在manifest.json里开启v3编译？

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by remember-5** [comment]
compilerVersion 但是开启也不行，需要在跳转页面的时候才能监听到消息
