### ISSUE TITLE
微信小程序webview无法和uni实时通讯

### ISSUE THREAD

**Issue by chinafelix** [dcloudio/uni-app#3203]
**问题描述**
开启了v3，微信小程序webview里通过uni.postMessage发送消息，在小程序页面回退能接收，但无法实时接收
**复现步骤**
[复现问题的步骤]
![image](https://user-images.githubusercontent.com/20641047/150078003-e95e8898-e2fc-4f4d-8386-98b7b9826a26.png)
![image](https://user-images.githubusercontent.com/20641047/150078004-e1d5d969-35b5-4373-aa42-50042117781e.png)

**预期结果**
在小程序内实时接收到webview里发送的消息

**实际结果**
无法实时接收，只能在小程序页面回退时才能接收

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: macOS 10.15.2
 - 
uni-app v3.1.12
uni-app cli v2.0.0-31920210428001

Environment Info:
  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 97.0.4692.71
    Firefox: Not Found
    Safari: 13.0.4
  npmPackages:
    @dcloudio/types: * => 2.2.4 
    @dcloudio/uni-app-plus: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-automator: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-cli-shared: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-h5: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-i18n: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-migration: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-mp-360: ^2.0.0-31920210428001 => 2.0.0-alpha-31920210506002 
    @dcloudio/uni-mp-alipay: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-mp-baidu: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-mp-kuaishou: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-mp-qq: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-mp-toutiao: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-mp-vue: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-mp-weixin: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-quickapp-native: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-quickapp-webview: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-stat: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/uni-template-compiler: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-31920210428001 => 2.0.0-31920210428001 
    @hap-toolkit/dsl-vue:  0.6.13 
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.6 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.13 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.13 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.13 
    @vue/cli-plugin-router:  4.5.13 
    @vue/cli-plugin-vuex:  4.5.13 
    @vue/cli-service: ~4.5.0 => 4.5.13 
    @vue/cli-shared-utils:  4.5.13 
    @vue/component-compiler-utils:  3.2.0 (3.2.0)
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/shared: ^3.0.0 => 3.0.11 
    @vue/web-component-wrapper:  1.3.0 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.11 => 2.6.12 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.7 (16.8.2, 15.9.7)
    vue-router:  3.0.1 
    vue-style-loader:  4.1.3 (4.1.3)
    vue-template-compiler: ^2.6.11 => 2.6.12 (2.6.12)
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.2.0 => 3.6.2 
  npmGlobalPackages:
    @vue/cli: 4.5.14

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
看下文档，有说明：微信小程序的限制，和版本无关。

**Comment by remember-5** [comment]
> 看下文档，有说明：微信小程序的限制，和版本无关。

https://developers.weixin.qq.com/miniprogram/dev/component/web-view.html


<img width="1090" alt="image" src="https://user-images.githubusercontent.com/31730796/197931233-56ef4685-2aa4-4d89-8bad-40a7632bf50a.png">
