### ISSUE TITLE
微信小程序不支持render吗？

### ISSUE THREAD

**Issue by mentoorliubin** [dcloudio/uni-app#3205]
**问题描述**
使用render函数，h5可以正常使用，编译微信小程序时报错

**复现步骤**
使用render函数，h5可以正常使用，编译微信小程序时报错
render' is not exported by node_modules/@dcloudio/uni-mp-vue/dist/vue.runtime.esm.js,

**预期结果**
微信小程序是否可以运行render

**实际结果**
微信小程序是否可以运行render

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]

**补充信息**
vue3平台

**Comment by fxy060608** [comment]
不支持 render 函数

**Comment by mentoorliubin** [comment]
> 小程序平台不支持 render 函数

请问是否有替代方法呢，难道要每个页面引用组件吗?

**Comment by fxy060608** [comment]
> > 小程序平台不支持 render 函数
> 
> 请问是否有替代方法呢，难道要每个页面引用组件吗?

如果想在每个页面的template里都使用包含某个组件，那就要在每个页面的template里边写该组件的标签
