### ISSUE TITLE
textarea在安卓端高度自适应会出现滚动条

### ISSUE THREAD

**Issue by ThreeStonesLee** [dcloudio/uni-app#3206]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
文本域textarea在安卓端的小程序里，高度自适应，如果有内容，按住内容，上下动一下，则就会出现滚动条
**复现步骤**
安卓系统的微信扫官方的uni-app框架演示示例中的小程序就可以复现

**预期结果**
textarea高度自适应，有内容不出现滚动条

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统：MIUI 12.5
 - 设备信息 红米K40

**Comment by StrivingRabbit** [comment]
测试没有复现。提供可以复现的简单示例

**Comment by StrivingRabbit** [comment]
在微信小程序端使用的就是官方的组件了，你可以使用微信小程序原生写一个自适应高度的textarea，看看可不可以复现。如果可以的话，可以去微信开发者社区反馈此问题
