### ISSUE TITLE
uni.uploadFile上传文件 报错code":"ERR_INVALID_CHAR

### ISSUE THREAD

**Issue by SS-slient** [dcloudio/uni-app#3207]
**问题描述**
上传文件的时候network 的请求头有问题 ，Provisional headers are shown
![image](https://user-images.githubusercontent.com/49890570/150121515-37b78060-de38-49b6-9e58-90b68ee756bc.png)

**复现步骤**
已经配置了ip域名白名单了
https协议
使用了chooseImg方法
下面是我的代码

获取相册的图片路径也拿到了，

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
正常上传

**实际结果**
上传报错
![image](https://user-images.githubusercontent.com/49890570/150120517-5a669de1-5f7a-4eec-9402-892de1a92662.png)

**补充信息**
在另一个页面同样的写法，都可以正常上传

**Comment by StrivingRabbit** [comment]
这在哪个平台？看看具体的请求详情，带的参数之类的有没有什么异常

**Comment by zhetengbiji** [comment]
和这个黄色叹号的内容无关，请关注自己服务器的响应内容。
