### ISSUE TITLE
uniapp离线打包的apk会有静默外网访问，公司需求无网化，如何全局关闭？

### ISSUE THREAD

**Issue by etjson** [dcloudio/uni-app#3208]
uniapp离线打包的apk会有静默外网访问，公司需求无网化，如何全局关闭？

抓包发现如下两个请求：

https://ac1.dcloud.net.cn/advert/splash（获取开屏广告信息）

https://s1.dcloud.net.cn/collect/plusapp/startup（启动获取用户信息用于统计分析）

这两个对于公司内部app使用来说不需要，不排除有没有其他条件下触发的静默请求，相关安全部门会误会是后门，官方是否支持一下无网化模式，哪怕有网，也不可以做这种静默请求。

官网社区已发帖，给个合理的解释：

[https://ask.dcloud.net.cn/question/138542](https://ask.dcloud.net.cn/question/138542)

![image](https://user-images.githubusercontent.com/41315967/150241706-6c144285-dff0-4c34-934e-d43d60eb084f.png)

dcloud_appkey开启后导致离线打包强制开发者在开发者平台注册账号获取key，当然这可以理解，看了下是为了开发者的产品发布出去的防删改着想，但这个静默请求的行为真的。。

**Comment by etjson** [comment]
已自行处理。

**Comment by ManiuLtd** [comment]
怎么解决的？求指教，遇到同样问题 @etjson

**Comment by censujiang** [comment]
> 已自行处理。

请问一下是怎么解决的？

**Comment by yangrongli9** [comment]
> uniapp离线打包的apk会有静默外网访问，公司需求无网化，如何全局关闭？
> 
> 抓包发现如下两个请求：
> 
> [https://ac1.dcloud.net.cn/advert/splash（获取开屏广告信息）](https://ac1.dcloud.net.cn/advert/splash%EF%BC%88%E8%8E%B7%E5%8F%96%E5%BC%80%E5%B1%8F%E5%B9%BF%E5%91%8A%E4%BF%A1%E6%81%AF%EF%BC%89)
> 
> [https://s1.dcloud.net.cn/collect/plusapp/startup（启动获取用户信息用于统计分析）](https://s1.dcloud.net.cn/collect/plusapp/startup%EF%BC%88%E5%90%AF%E5%8A%A8%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E4%BF%A1%E6%81%AF%E7%94%A8%E4%BA%8E%E7%BB%9F%E8%AE%A1%E5%88%86%E6%9E%90%EF%BC%89)
> 
> 这两个对于公司内部app使用来说不需要，不排除有没有其他条件下触发的静默请求，相关安全部门会误会是后门，官方是否支持一下无网化模式，哪怕有网，也不可以做这种静默请求。
> 
> 官网社区已发帖，给个合理的解释：
> 
> https://ask.dcloud.net.cn/question/138542
> 
> ![image](https://user-images.githubusercontent.com/41315967/150241706-6c144285-dff0-4c34-934e-d43d60eb084f.png)
> 
> dcloud_appkey开启后导致离线打包强制开发者在开发者平台注册账号获取key，当然这可以理解，看了下是为了开发者的产品发布出去的防删改着想，但这个静默请求的行为真的。。

请问你是用的什么抓包工具呀，我用的hbuilder云打包，公司ipv6也检测出apk会访问这两个域名，但是我用抓包工具没看到有访问呀

**Comment by etjson** [comment]
> > uniapp离线打包的apk会有静默外网访问，公司需求无网化，如何全局关闭？
> > 抓包发现如下两个请求：
> > [https://ac1.dcloud.net.cn/advert/splash（获取开屏广告信息）](https://ac1.dcloud.net.cn/advert/splash%EF%BC%88%E8%8E%B7%E5%8F%96%E5%BC%80%E5%B1%8F%E5%B9%BF%E5%91%8A%E4%BF%A1%E6%81%AF%EF%BC%89)
> > [https://s1.dcloud.net.cn/collect/plusapp/startup（启动获取用户信息用于统计分析）](https://s1.dcloud.net.cn/collect/plusapp/startup%EF%BC%88%E5%90%AF%E5%8A%A8%E8%8E%B7%E5%8F%96%E7%94%A8%E6%88%B7%E4%BF%A1%E6%81%AF%E7%94%A8%E4%BA%8E%E7%BB%9F%E8%AE%A1%E5%88%86%E6%9E%90%EF%BC%89)
> > 这两个对于公司内部app使用来说不需要，不排除有没有其他条件下触发的静默请求，相关安全部门会误会是后门，官方是否支持一下无网化模式，哪怕有网，也不可以做这种静默请求。
> > 官网社区已发帖，给个合理的解释：
> > https://ask.dcloud.net.cn/question/138542
> > ![image](https://user-images.githubusercontent.com/41315967/150241706-6c144285-dff0-4c34-934e-d43d60eb084f.png)
> > dcloud_appkey开启后导致离线打包强制开发者在开发者平台注册账号获取key，当然这可以理解，看了下是为了开发者的产品发布出去的防删改着想，但这个静默请求的行为真的。。
> 
> 请问你是用的什么抓包工具呀，我用的hbuilder云打包，公司ipv6也检测出apk会访问这两个域名，但是我用抓包工具没看到有访问呀

用firda，我已经转原生app开发了，uniapp后门实在恶心，[https://jshook.org/](https://jshook.org/)

**Comment by etjson** [comment]
可以使用dobby(native层)和lsplant(java层)两个框架hook掉uniapp sdk中的所有后门，但v8体积感人还是算了，我自己原生打包的只有10M不到，uniapp最低30M，毕竟4个架构的so加起来就要那么大。

其实如果uiniapp允许关闭后门并且入口脱离webview的话，体积大一点我还能接受的，目前两个捆绑问题，第一个是app至少必须拥有网络访问权限，否则闪退，第二个是入口继承了webview，如果被禁用或者webview环境异常也会闪退，对于工具类app是噩梦。

**Comment by wanganxp** [comment]
DCloud有自己的sdk的校验逻辑、崩溃上报、性能分析，但DCloud不是大数据公司，也不关心app的敏感信息。各个应用商店都有隐私合规检测，大家可以去提交试试就知道了，没有隐私和敏感信息。

**Comment by cilla123** [comment]
> > > 已自行处理。
> > 
> > 
> > 请问一下是怎么解决的？
> 
> 直接逆向sdk去改，是写在native层的。

你好，请问是在哪里so文件呢
