### ISSUE TITLE
canvas不能触发touch事件

### ISSUE THREAD

**Issue by moohng** [dcloudio/uni-app#3209]
**问题描述**
真机上canvas不能触发绑定的touch事件

**复现步骤**
1. 通过官方命令创建项目 `npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project`；
2. 安装项目依赖并启动scripts命令 `dev:mp-weixin`；
3. 微信开发者工具打开并真机扫码预览;

``` html
<template>
  <canvas id="cs" type="2d" @touchstart="onTouchStart"></canvas>
</template>

<script lang="ts">
import { defineComponent } from 'vue'

export default defineComponent({
  methods: {
    onTouchStart() {
      uni.showToast({ title: 'touch start', icon: 'none' });
    },
  }
});
</script>
```

**预期结果**
真机上正常弹出toast提示信息

**实际结果**
无任何反应，没有执行 `onTouchStart` 方法

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统：Android 11
 - uni-app版本：v3.0.0-alpha-3030820220114001
 - 设备信息：安卓机

**补充信息**
创建Vue2的正式版项目则没有此问题

**Comment by zhetengbiji** [comment]
关联：https://ask.dcloud.net.cn/question/138565

**Comment by netdreamwing** [comment]
vite + vue3 遇到同样问题，开发者工具没有问题，真机测试所有touch时间都不能触发，tap可触发

版本号：^3.0.0-alpha-3030920220121001

vue2 开发者工具和真机测试都没有问题

**Comment by netdreamwing** [comment]
这个问题影响还是挺大的，之前vue2没问题，项目迁移vue3重构遇到这个问题卡主了，下一个版本能修复吗？ @zhetengbiji

**Comment by fxy060608** [comment]
> 这个问题影响还是挺大的，之前vue2没问题，项目迁移vue3重构遇到这个问题卡主了，下一个版本能修复吗？ @zhetengbiji

已修复，cli更新至：3.0.0-alpha-3030820220114006

**Comment by yjt1216** [comment]
H5 端 canvas 在uni-canvas 包裹下没有touch事件响应

**Comment by h5box** [comment]
我也是
