### ISSUE TITLE
emits 事件监听失效

### ISSUE THREAD

**Issue by okxiaoliang4** [dcloudio/uni-app#3210]
**问题描述**
例如:
```typescript
const emits = defineEmits(['show-fold-popup'])
```
```vue
<component-a @show-fold-popup="onShowFoldPopup"></component-a>
```
当`emits`使用`-`分隔符声明时父组件无法正常监听事件

**预期结果**
父组件正常监听事件

**实际结果**
未捕获到事件

**系统信息:**
 - 微信小程序
 - uni-app@3.0.0-alpha-3030820220114003

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030820220114004

**Comment by xcplovelhq** [comment]
this.$emit也一样会，麻烦修复下

**Comment by xmh0511** [comment]
引入的微信自定义组件也存在该问题
````javascript
<component-of-wx @my-event="onListen" />
````
引用`wxcomponent`中的微信自定义组件
````javascript
....
this.triggerEvent("my-event",{...});
````
在VUE3版本中也是无法监听到事件，VUE2是ok的。
