### ISSUE TITLE
renderjs中不能使用vuex

### ISSUE THREAD

**Issue by z3214965** [dcloudio/uni-app#3211]
**问题描述**
app模式下，renderjs中使用vuex，this.$store未定义，什么问题？

**预期结果**
app中找不到this.$store

**实际结果**
H5中可以找到this.$store，但app中找不到this.$store

**系统信息:**
 - 发行平台: app
 - 操作系统 Android 7.0
 - HBuilderX版本：最新版本

**补充信息**
app模式下，<script lang="renderjs"> 中是否可以使用vuex？

**Comment by fxy060608** [comment]
不能使用
app平台常规的js代码和renderjs代码是分离的，不在同一个环境运行

**Comment by z3214965** [comment]
@fxy060608 
有没有什么解决方案？

**Comment by fxy060608** [comment]
> @fxy060608 有没有什么解决方案？

没有，就好比两个不同的网页，没法共享store

**Comment by z3214965** [comment]
@fxy060608 
好吧，谢谢！

**Comment by z3214965** [comment]
@fxy060608 
你好，我在请教下，app模式下，<script lang="renderjs"> 中怎么和其他页面通讯？

**Comment by fxy060608** [comment]
> @fxy060608 你好，我在请教下，app模式下，<script lang="renderjs"> 中怎么和其他页面通讯？

同微信wxs一样，通过change:prop形式和callMethod通讯
https://developers.weixin.qq.com/miniprogram/dev/framework/view/interactive-animation.html

**Comment by z3214965** [comment]
@fxy060608
还要在麻烦下，帮看下代码！！

**子页面：**
![子界面](https://user-images.githubusercontent.com/18589356/150494609-3bcf29a4-527e-4443-b871-f021d0ca8e53.PNG)

**父页面：**
![父页面](https://user-images.githubusercontent.com/18589356/150494645-bdb8ab00-c4d6-42a6-a4ff-2f8a770c0ee9.PNG)

第一个问题：不知道子页面写的对不对。
第二个问题：父页面怎么调用子界面，设置propValue触发propObserver方法。

麻烦您了，谢谢！

**Comment by fxy060608** [comment]
> @fxy060608 还要在麻烦下，帮看下代码！！
> 
> **子页面：** ![子界面](https://user-images.githubusercontent.com/18589356/150494609-3bcf29a4-527e-4443-b871-f021d0ca8e53.PNG)
> 
> **父页面：** ![父页面](https://user-images.githubusercontent.com/18589356/150494645-bdb8ab00-c4d6-42a6-a4ff-2f8a770c0ee9.PNG)
> 
> 第一个问题：不知道子页面写的对不对。 第二个问题：父页面怎么调用子界面，设置propValue触发propObserver方法。
> 
> 麻烦您了，谢谢！

子组件的props里边定义propValue
父组件传递propValue

**Comment by z3214965** [comment]
@fxy060608 
![父页面](https://user-images.githubusercontent.com/18589356/150500402-34b0fec4-a8ce-4268-a372-a418c61bc6cd.PNG)

![子界面](https://user-images.githubusercontent.com/18589356/150500432-b327a6cb-001e-4dd5-9e39-8c74203864a5.PNG)

![error](https://user-images.githubusercontent.com/18589356/150500454-a06a3a7e-cc95-4c27-ad82-f559d88d7d15.PNG)

按照文档说法propObserver方法中console.log('prop observer')会执行一次，但没有执行

**Comment by fxy060608** [comment]
> @fxy060608 ![父页面](https://user-images.githubusercontent.com/18589356/150500402-34b0fec4-a8ce-4268-a372-a418c61bc6cd.PNG)
> 
> ![子界面](https://user-images.githubusercontent.com/18589356/150500432-b327a6cb-001e-4dd5-9e39-8c74203864a5.PNG)
> 
> ![error](https://user-images.githubusercontent.com/18589356/150500454-a06a3a7e-cc95-4c27-ad82-f559d88d7d15.PNG)
> 
> 按照文档说法propObserver方法中console.log('prop observer')会执行一次，但没有执行

发测试工程

**Comment by z3214965** [comment]
@fxy060608 
https://github.com/z3214965/test-uniapp1
麻烦您了，谢谢！

**Comment by fxy060608** [comment]
> @fxy060608 https://github.com/z3214965/test-uniapp1 麻烦您了，谢谢！

注意语法要换成vue的
```html
<view :change:prop="dlkjM.propObserver" :prop="propValue"></view>
```

**Comment by z3214965** [comment]
@fxy060608 
![error1](https://user-images.githubusercontent.com/18589356/150510454-75f681cb-ae98-48fa-98f0-917a058a9395.PNG)
报错！

**Comment by z3214965** [comment]
@fxy060608 
![error1](https://user-images.githubusercontent.com/18589356/150511757-ce7ede1a-c4b9-4447-a9ba-423aaed3240e.PNG)
报错！

**Comment by fxy060608** [comment]
> @fxy060608 ![error1](https://user-images.githubusercontent.com/18589356/150511757-ce7ede1a-c4b9-4447-a9ba-423aaed3240e.PNG) H5模式下，可以，App模式下，报错！

mapView组件不要使用多节点，加一个根节点包起来

**Comment by fxy060608** [comment]
> @fxy060608 ![error1](https://user-images.githubusercontent.com/18589356/150511757-ce7ede1a-c4b9-4447-a9ba-423aaed3240e.PNG) H5模式下，可以，App模式下，报错！
不要把props定义放到renderjs中
<script>
    export default {
        props: ["propValue"],
    }
</script>

**Comment by z3214965** [comment]
@fxy060608 
可以了，非常感谢！！

**Comment by z3214965** [comment]
@fxy060608
你好，我在请脚下，关于this.$ownerInstance
![捕获1](https://user-images.githubusercontent.com/18589356/150905233-7f00fa76-9636-4167-8bf3-f833b8ea7caa.PNG)
找不到此对象？

**Comment by fxy060608** [comment]
> @fxy060608 你好，我在请教下，关于this.$ownerInstance ![捕获1](https://user-images.githubusercontent.com/18589356/150905233-7f00fa76-9636-4167-8bf3-f833b8ea7caa.PNG) 找不到此对象？

cli的话升级到最新

**Comment by z3214965** [comment]
@fxy060608 
用HBuilderX创建的项目，怎么处理？

**Comment by fxy060608** [comment]
> @fxy060608 用HBuilderX创建的项目，怎么处理？

等发版

**Comment by z3214965** [comment]
@fxy060608 
大致什么时间节点？

**Comment by fxy060608** [comment]
> @fxy060608 大致什么时间节点？

春节前应该会发一个Alpha版本

**Comment by z3214965** [comment]
@fxy060608 
多久升级到stable版？

**Comment by fxy060608** [comment]
> @fxy060608 多久升级到stable版？

那就要春节后一两周之后了

**Comment by z3214965** [comment]
@fxy060608 
了解，谢谢！
