### ISSUE TITLE
vue3 setup写法引入组件后微信小程序不展示，h5正常

### ISSUE THREAD

**Issue by MackJac** [dcloudio/uni-app#3213]
**问题描述**
[问题描述：vue3 setup写法引入组件后微信小程序不展示，h5正常]

**复现步骤**
[复现问题的步骤]
1.  测试demo地址：https://gitee.com/mymjc/uniapp-vue3-demo/tree/master/
2. npm run dev 启动
3. 查看index页面和index1页面是否展示组件内容

[或者可以直接贴源代码]

**预期结果**
index,index1都可以展示box组件内容

**实际结果**
index是setup写法引入组件，未展示
index1是components引入，可展示

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030820220114004
