### ISSUE TITLE
请添加关于 wxsCallMethods 的文档

### ISSUE THREAD

**Issue by RexYuan1114** [dcloudio/uni-app#3218]
**问题描述**
[问题描述：切换为uniapp vite编译版本后, 原有的组件中在WXS中有用到页面示例的callMethod方法的都失效了.经过查找源码发现需在组件中配置wxsCallMethods, 但是在uniapp的文档中完全没有提及这方面的变动.

**复现步骤**
任意uniapp vite编译版本中使用WXS中方法接收到的页面示例调用callMethod即可复现

**预期结果**
添加关于wxsCallMethods的文档内容, 或不配置wxsCallMethods 即可正常使用callMethod

**实际结果**
无

**系统信息:**
 - 发行平台: 微信小程序
 - uni-app版本: 3.0.0-alpha-3030920220121001

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3030820220114005

**Comment by RexYuan1114** [comment]
实测 3.0.0-alpha-3030820220114006 复现

**Comment by fxy060608** [comment]
> 实测 3.0.0-alpha-3030820220114006 复现

发测试工程

**Comment by RexYuan1114** [comment]
> 

[https://github.com/RexYuan1114/uniapp-debug-project.git](url)

**Comment by fxy060608** [comment]
> https://github.com/RexYuan1114/uniapp-debug-project.git

将package.json中的版本锁死：3.0.0-alpha-3030820220114006
重新安装测试

**Comment by RexYuan1114** [comment]
锁死版本后解决
