### ISSUE TITLE
[Vue warn]: Error in nextTick: "TypeError: el.getAttribute is not a function"

### ISSUE THREAD

**Issue by winston1991** [dcloudio/uni-app#3219]
**问题描述**
项目中引入了npm install --save vue-tippy@v4  官网[https://kabbouchi.github.io/](https://kabbouchi.github.io/)
H5时可以正常使用 点击就可以弹出tooltip，但是打包成wgt 或者 app运行就会出现 "TypeError: el.getAttribute is not a function"这个错误。无法使用
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
APP 和H5都能正常使用

**实际结果**

**系统信息:**
 - 发行平台: [H5平台、5+ App]
 - 操作系统 [Android 7.0]
 - HBuilderX版本 [3.2.16]
 - uni-app版本 []
 - 设备信息 [模拟器]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by winston1991** [comment]
补充说明：这个组件是自定义指令， 是不是uniapp不支持自定义指令？

**Comment by winston1991** [comment]
@dcloudhdx

**Comment by StrivingRabbit** [comment]
app端不能直接操作dom元素
