### ISSUE TITLE
uni.onBluetoothDeviceFound 回调方法无效

### ISSUE THREAD

**Issue by Orialian** [dcloudio/uni-app#322]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
uni.onBluetoothDeviceFound 回调方法无效

手机上打开了蓝牙,且手机的蓝牙设备列表是有设备的,并连接了手环,但是 发现设备这个方法的回调没有输出, 获取设备列表也是空的

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

以下是 App.vue 文件中的代码

``` js
<script>
export default {
	onLaunch: function() {
		let _this = this;
		uni.openBluetoothAdapter({
			success(e) {
				_this.startDiscovery()
			},
			fail(e) {
				uni.showToast({
					title: '请检查您的蓝牙是否打开',
					icon: 'none'
				});
			}
		});
	},
	onShow: function() {},
	onHide: function() {},
	methods: {
		// 开始扫描
		startDiscovery() {
			let _this = this;
			uni.startBluetoothDevicesDiscovery({
				interval: 500,
				success(e) {
					console.info('开始扫描');
					_this.foundDevice()
					_this.getDiscovery()
					_this.stopDiscovery()
				}
			});
		},
		// 停止扫描
		stopDiscovery() {
			uni.stopBluetoothDevicesDiscovery({
				success() {
					console.log('关闭蓝牙')
				}
			});
		},
		// 发现设备
		foundDevice() {
			uni.onBluetoothDeviceFound(function(devices) {
				console.log('发现设备');
			});
		},
		// 获取发现的设备
		getDiscovery() {
			uni.getBluetoothDevices({
				success(res) {
					console.log('设备列表')
					console.info(JSON.stringify(res));
				}
			});
		}
	}
};
</script>
```
**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

能够获取当前手机上已搜索到的设备列表

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/34876408/56419503-ff71a880-62cc-11e9-9c85-7741c42a7b10.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by dcloudhdx** [comment]
代码逻辑问题
在开启蓝牙扫描 uni.startBluetoothDevicesDiscovery 的 success 回调中 调用了关闭扫描
