### ISSUE TITLE
微信小程序getPhoneNumber返回参数目前支持code吗

### ISSUE THREAD

**Issue by amihhs** [dcloudio/uni-app#3220]
微信小程序的获取用户手机号接口更新了一下：
目前是不支持新接口吗
**新接口**
[地址](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/getPhoneNumber.html)
```js
//返回参数说明 code 

Page({
  getPhoneNumber (e) {
    console.log(e.detail.code)
  }
})

```

**旧接口**
[地址](https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/getPhoneNumber.html)

```js
//返回参数说明 encryptedData、iv、cloudID 

Page({
 getPhoneNumber (e) {
    console.log(e.detail.errMsg)
    console.log(e.detail.iv)
    console.log(e.detail.encryptedData)
  }
})


```

**Comment by StrivingRabbit** [comment]
如果是微信小程序平台的话，是支持的，因为调用和返回用的就是微信的。现在是什么表现？

**Comment by amihhs** [comment]
我切换基础到最新的2.21.4，返回的参数还是`encryptedData`和`iv` @StrivingRabbit

**Comment by StrivingRabbit** [comment]
@amihhs 看了看微信的文档，感觉新旧接口的使用方式是一致的，你真机试试

**Comment by amihhs** [comment]
已经可以正常返回code
![image](https://user-images.githubusercontent.com/59364234/163148433-a2926e1b-30d1-44ce-b6d8-2b64c816d2e8.png)

**Comment by 2356874721** [comment]
怎么使用新版的交互方式呢，旧版似乎后端交互更加复杂
