### ISSUE TITLE
支付宝小程序中 uni.request get请求 参数data 如果是Object嵌套多层 生成的请求地址里参数出现'Object'

### ISSUE THREAD

**Issue by chris926** [dcloudio/uni-app#3224]
**问题描述**
uni.request get请求 参数data 如果是Object嵌套多层 生成的请求地址里参数出现'Object'
此bug只出现在支付宝小程序中，微信小程序正常生成

实际现象：
以下地址参数中extConfig为data参数的第二层object对象

微信小程序中请求的url地址：https://hostname/superdiancan/getbuinessid?_from_weapp:1&path:pages/scan/scan&scene:1011&extConfig{appid}:2019091967605295&extConfig{welife_bid}:2225426060&extConfig{SC-MALL-SELLER-ID}:2225426060&extConfig{foo}:bar&app_version:PHONEVIP:WX:20201215&suid:ec1886c23fc2e49a&waimai:null&noloading:true&bid:11007

支付宝中却请求的如下地址：
https://hostname/superdiancan/getbuinessid?_from_weapp=1&app_version=PHONEVIP:WX:20201215&bid=11007&extConfig=[object Object]&noloading=true&path=pages/scan/scan&scene=1011&waimai

**Comment by Otto-J** [comment]
我按照下面方式测试未能复现问题

```html
<script lang="ts" setup>

const baseUrl = 'https://request.dcloud.net.cn/api/http/method/get'
const extConfig = {
  a: {
    b: {
      c:1
    }
  }
}

uni.request({
  url: baseUrl+'?'+ encodeURIComponent(JSON.stringify(extConfig)),
  success: (res) => {
    console.log(res)
  }
})
</script>
```

如果仍有问题，请 reopen 或者新开 issue 艾特我。
