### ISSUE TITLE
getBackgroundAudioManager onNext, onPrev不会触发回调

### ISSUE THREAD

**Issue by 1135065316** [dcloudio/uni-app#3227]
**问题描述**
uni.getBackgroundAudioManager()
1. onNext, onPrev不会触发回调
2. 未提供销毁实例的方法

**复现步骤**
```
const bgAudio = uni.getBackgroundAudioManager()

bgAudio.onPrev(() => {
	console.log('onPrev')
})
bgAudio.onNext(() => {
	console.log('onNext')
})
```

**预期结果**
正常触发回调

**实际结果**
未触发回调

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 IOS 15.2.1
 - HBuilderX版本 3.3.10.20220124
 - 设备信息 iphone12

**Comment by dcloudhdx** [comment]
3.4.1 alpha 版本已修复 onPrev、onNext 不触发回调的问题

**Comment by dcloudhdx** [comment]
HBuilderX 3.4.1 alpha 版本已修复 onPrev、onNext 不触发回调的问题

**Comment by ant-zhao** [comment]
onPrev 还是不触发
