### ISSUE TITLE
发行微信小程序pages文件体积变大

### ISSUE THREAD

**Issue by airzhanglin** [dcloudio/uni-app#323]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
不发的时候体积只有300多Kb,但是点击发行之后发现pages下面就成了900多kb了。

**系统信息:**
 - 发行平台: [微信小程序
 - 操作系统 [iOS 12.1.2、Android 7.0]
 - HBuilderX版本 1.9.2
 - uni-app版本 如何查看？

**Comment by zhetengbiji** [comment]
这里所说的变大具体指的哪里的大小？

**Comment by zhetengbiji** [comment]
长时间未回复，暂时关闭
