### ISSUE TITLE
this.$emit 事件监听失效

### ISSUE THREAD

**Issue by xcplovelhq** [dcloudio/uni-app#3232]
问题描述
例如:
父组件
<point-card :data="headerData" @forward-mall="" @forward-order="" />

子组件用this.$emit('forward-mall')使用-分隔符声明时父组件无法正常监听事件

预期结果
父组件正常监听事件

实际结果
未捕获到事件

系统信息:

微信小程序
uni-app@3.0.0-alpha-3031020220124001

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/3210

**Comment by xcplovelhq** [comment]
这个我看了，但是我都高于这个版本了，也是还是不行的

**Comment by fxy060608** [comment]
> 这个我看了，但是我都高于这个版本了，也是还是不行的

package.json 锁死版本，重新安装
