### ISSUE TITLE
H5 hash路由模式下，iOS8页面加载无限reload

### ISSUE THREAD

**Issue by SheldonLaw** [dcloudio/uni-app#3237]
**问题描述**

**复现步骤**
[复现问题的步骤]
1.  启动Hbuilder X
2. 新建项目（默认模板）

![image](https://user-images.githubusercontent.com/16605105/151481193-b74ec05e-ba03-4e6e-9c5b-f73787772f15.png)

3. 设置manifest.json：h5hash路由模式

![image](https://user-images.githubusercontent.com/16605105/151481472-1cde945a-671e-4623-b4b4-75372084eb16.png)

4. 运行项目
5. 在iOS8下访问项目，进入页面会不断reload

**预期结果**
进入页面

**实际结果**

进入页面会不断reload

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [iOS 8.1.2]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
![image](https://user-images.githubusercontent.com/16605105/151481193-b74ec05e-ba03-4e6e-9c5b-f73787772f15.png)
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone5c]

**补充信息**

1. 问题分析
相关reload代码定位：https://github.com/dcloudio/uni-app/commit/a85c32c440048bed80ef30675290889e5bd9e0f1

iOS8在页面加载完后会触发popstate方法，然后uniapp有个版本监听到popstate之后，会reload。进入死循环了。

<img width="864" alt="wecom-temp-0f38bdf6612da94fec6430fd1f60633e" src="https://user-images.githubusercontent.com/16605105/151481987-d6a74a37-bbeb-425c-b179-3dd1cf499ecb.png">

总结：uniapp路由实现时可能遗漏了iOS8等设备在页面加载完会自动触发popstate这种情况。

解决思路：load，popstate，reload短时间内依次触发时，忽略这次reload。

2. hack解决方案：在html中引入hack脚本，过滤异常reload
``` html
<script>
  // @NOTE 处理uniapp路由bug，load，popstate，reload短时间内依次触发时，忽略这次reload
  var reloadHackRecord = {};
  window.addEventListener('load', function(e) {
    reloadHackRecord.load = new Date().getTime();
  });
  var onPopState = function() {
    reloadHackRecord.popstate = new Date().getTime();
    window.removeEventListener('popstate', onPopState);
  }
  window.addEventListener('popstate', onPopState);
  var oldReload = window.location.reload;
  window.location.reload = function() {
    var load = reloadHackRecord.load;
    var popstate = reloadHackRecord.popstate;
    var reload = new Date().getTime();
    var margin = 100; // 经验值
    if (load && popstate && reload && reload > popstate && popstate > load && reload - popstate < margin && popstate - load < margin) {
      window.location.reload = oldReload;
      // @TODO 可以上报看看有多少量
      return;
    }
  }
</script>

```

**Comment by SheldonLaw** [comment]
目前项目内已hack解决，期望官方的跟进。

**Comment by yeshaobin** [comment]
期望官方的跟进。

**Comment by zhetengbiji** [comment]
> 期望官方的跟进。

iOS9以下目前不再处理
