### ISSUE TITLE
单张gif图达到一定大小且有三张或更多张以上的gif图会闪退

### ISSUE THREAD

**Issue by hblz** [dcloudio/uni-app#3238]
**问题描述**
单张gif图达到一定大小且有三张或更多张以上的gif图会闪退

**复现步骤**
<image :src="'https://testing.ff-iot.com:12034/ff_user/InspectionImg/2022/01/20/10C31736CAE04E208C273923A09ED3A4.gif'"></image>
<image :src="'https://testing.ff-iot.com:12034/ff_user/InspectionImg/2022/01/20/4D20A736318045BEA3B815E04B12D248.gif'"></image>
<image :src="'https://testing.ff-iot.com:12034/ff_user/InspectionImg/2022/01/20/AF86A39D0639479E926CDF848724D599.gif'"></image>
<image :src="'https://testing.ff-iot.com:12034/ff_user/InspectionImg/2022/01/20/6E8129730B5E47EE9BBBCC1EB350B3C7.jpg'"></image>
**预期结果**
不闪退

**实际结果**
闪退

**系统信息:**
 - 发行平台: app
 - 操作系统  ios 14及以上
 - HBuilderX版本 3.1.12
 - uni-app版本 IDE
 - 设备信息 [如 iPhone7]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by hblz** [comment]
官方效率这么差吗

**Comment by zhetengbiji** [comment]
是说的 previewImage 接口吗？
