### ISSUE TITLE
vue-cli创建项目，在执行 npm run lint时报错

### ISSUE THREAD

**Issue by kuangche** [dcloudio/uni-app#324]
**问题描述**
preprocessContext[process.env.UNI_PLATFORM.toUpperCase()] = true
这一行代码会报错
TypeError: Cannot read property 'toUpperCase' of undefined

后来发现是需要配置“UNI_PLATFORM”参数
比如这样 "lint": "cross-env NODE_ENV=production UNI_PLATFORM=h5 vue-cli-service lint"
所以问题 执行lint时候代表已经要做上线前的代码检测了，是否没有必要自己加上以上信息了

**Comment by fxy060608** [comment]
cli 已修复，可以 npm update 更新下
@dcloudio/uni-cli-shared@0.2.944
