### ISSUE TITLE
vue3 app-plus环境中组件的生成时机异常

### ISSUE THREAD

**Issue by PentaTea** [dcloudio/uni-app#3241]
**问题描述**
vue3 app-plus环境中组件是在app启动前生成的,与vue2和vue3其他平台行为不一致

**复现步骤**
- main.ts中`const app = createSSRApp(App)`下一行添加`console.log('main')`
- app.vue中保留onLaunch,onShow钩子
- 在任意页面中添加组件,组件中写入:
```
<script>
export default{
  setup(){
console.log('components setup');
  },
  mixins: [(()=>{
    console.log('components');
    return {}
  })()],
}
</script>
```
**预期结果**
应输出:
```
main
App Launch
App Show
components
components setup
```
**实际结果**
- h5,小程序与预期一致
- app真机运行:
```
components
main
App Launch
App Show
components setup
```
**系统信息:**
- hbuildx 3.3.5.20211229
- vite2.7.13 vue3.2.29
- @dcloudio/uni-app 3.0.0-alpha-3031020220124001

**Comment by fxy060608** [comment]
为何要在mixin上边做一个自执行的函数？还要依赖他的执行顺序？
你这个自执行的函数取决于代码编译后的代码顺序，app端所有的js代码是打包成一个的，h5和小程序都是分离的多个js，代码顺序是不可靠的

**Comment by fxy060608** [comment]
> > 为何要在mixin上边做一个自执行的函数？还要依赖他的执行顺序？
> > 你这个自执行的函数取决于代码编译后的代码顺序，app端所有的js代码是打包成一个的，h5和小程序都是分离的多个js，代码顺序是不可靠的
> 
> 哦明白了，app环境会全部打包到appserver文件。。。
> 
> 关于这个顺序是因为我在尝试移植uView-ui组件库
> 
> uView将组件mixin和props默认值都挂载到了全局uni对象中，于是就要求组件生成前执行完plugin的初始化操作。
> 
> 请问这种需求怎么做比较好

没太看懂什么意思，可以贴下代码辅助说明下

**Comment by PentaTea** [comment]
> 没太看懂什么意思，可以贴下代码辅助说明下


> [# uView quickstart: ](https://www.uviewui.com/components/quickstart.html#%E5%A6%82%E4%BD%95%E4%B8%8D%E4%BD%BF%E7%94%A8easycom%E8%80%8C%E5%8D%95%E7%8B%AC%E5%BC%95%E7%94%A8%E6%9F%90%E4%B8%80%E4%B8%AA%E7%BB%84%E4%BB%B6) 从1.7.9开始，uView将$u对象同时挂载到了uni对象上，这意味着您可以在外部的js文件中，通过uni.$u.xxx的形式去调用uView提供的一些工具方法，而不再像从前一样必须在*.vue中通过uni.$u.xxx的形式调用。

- 上述在uni对象挂载$u的操作是在app.use(plugin)安装插件时,[对应插件index文件的install方法中进行的](https://github.com/umicro/uView2.0/blob/8395885c6b768498d0fe856d03cdf1a7f392264b/uni_modules/uview-ui/index.js#L61)
- 你可以看到,在uView的所有组件中 (如 [u-input](https://github.com/umicro/uView2.0/blob/8395885c6b768498d0fe856d03cdf1a7f392264b/uni_modules/uview-ui/components/u-input/u-input.vue#L122)) 都引入了三个mixin
- 其中两个 mixin 是全局混入, [props 依赖了 `uni.$u.props.input.value`](https://github.com/umicro/uView2.0/blob/8395885c6b768498d0fe856d03cdf1a7f392264b/uni_modules/uview-ui/components/u-input/props.js#L6) 来允许用户自定义所有prop的初始值
- 但由于组件生成是在install方法前就执行了的,此时uni对象中还并没有$u,就会报错

总结一下需求就是,插件作者会在 install 方法中扩充一些 utils, 并期望在组件生成时使用

**Comment by PentaTea** [comment]
嗯了解了, 再加上自定义props初始值的需求也可以在setup函数中执行
