### ISSUE TITLE
uniapp sfc playground

### ISSUE THREAD

**Issue by hxgqh** [dcloudio/uni-app#3242]
**新功能描述**
提供基于 https://sfc.vuejs.org/ 的playground项目框架。ElementPlus官方也提供了[类似的参考](https://element-plus.run/)

**现状及问题**
期待提供类似功能

**Comment by Otto-J** [comment]
感谢反馈。

uniapp 支持多平台渲染，运行到小程序平台需要依赖编辑器才能实现预览。

后续可能会规划 h5 平台的 playground
