### ISSUE TITLE
3.0发布计划

### ISSUE THREAD

**Issue by mingyangzhu** [dcloudio/uni-app#3243]
**新功能描述**
请问有3.0稳定版本的发布计划嘛？
**现状及问题**
无

**尝试方案**
无

**补充信息**
无

**Comment by zhetengbiji** [comment]
HBuilderX 正式版携带的为稳定版；CLI 创建的模版默认已经设置为稳定版，并支持使用 @dcloudio/uvm 管理依赖版本；
