### ISSUE TITLE
【vite】使用 require 引入 js 文件报错

### ISSUE THREAD

**Issue by sufuwang** [dcloudio/uni-app#3245]
**问题描述**
尝试使用 require 在 main.js 中引入同路径下的 page.js 文件
```js
import {
	createSSRApp
} from "vue";
import App from "./App.vue";
const pages = require('./page.js')

console.info('pages: ', pages)

export function createApp() {
	const app = createSSRApp(App);
	return {
		app,
	};
}
```

**实际结果**
```js
Error: module "page.js" is not defined
```
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/46395105/152938506-97e6002b-8dab-47d9-a259-389742262220.png">

**系统信息:**
 - 发行平台: 微信小程序
 - uni-app版本. 3.0.0-alpha-3030820220114004

**Comment by fxy060608** [comment]
仅支持es6 module，即：import / export
