### ISSUE TITLE
请问如何关闭uniapp项目，打包出的微信小程序AppData面板中，变量名被混淆问题

### ISSUE THREAD

**Issue by yxw007** [dcloudio/uni-app#3246]
**问题描述**
请问开发模式如何配置关闭掉AppData面板中变量名被混淆？

**复现步骤**
1. npx degit dcloudio/uni-preset-vue#vite my-vue3-project  
2. cd my-vue3-project  
3. npm install
4. npm run dev:mp-weixin
5. 微信小程序工具，打开dist目录下的dev\mp-weixin 等编译完成，点击AppData 即可看到变量名是被混淆掉的

**预期结果**
![image](https://user-images.githubusercontent.com/9338717/153112397-f18dd197-49f6-4587-ba50-7fdabc4e5ce6.png)

**实际结果**
![image](https://user-images.githubusercontent.com/9338717/153112352-36f190c8-37fa-4554-bc44-a0f00df575a0.png)

**系统信息:**
 - 发行平台: 微信小程序

**补充信息**
尝试将vite.config.js 中的build.minify 设为false仍然无效

**Comment by fxy060608** [comment]
为支持更多语法特性及优化性能，不支持显示原始变量，但后续会提供vue devtools支持

**Comment by Suminger** [comment]
蹲

**Comment by lovelts** [comment]
+1

**Comment by darrensYoung** [comment]
现在是还不可使用吧
