### ISSUE TITLE
vue3 vite-ts 模板配置 @dcloudio/vite-plugin-uni outputDir 后构建结果没有变化

### ISSUE THREAD

**Issue by ModyQyW** [dcloudio/uni-app#3248]
**问题描述**

vue3 vite-ts 模板配置 @dcloudio/vite-plugin-uni outputDir 后构建结果没有变化

**复现步骤**

1. `npx degit dcloudio/uni-preset-vue#vite-ts uni-app-vue3-test`
2. `cd uni-app-vue3-test`
3. `npm i -g yarn`
3. 修改 `vite.config.ts` 如下

```ts
import { defineConfig } from "vite";
import uni from "@dcloudio/vite-plugin-uni";
import path from "path";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    uni({
      outputDir: path.resolve(
        process.cwd(),
        "dist",
        process.env.UNI_PLATFORM ?? "h5"
      ),
    }),
  ],
});

```

4. `yarn dev:mp-weixin`

**预期结果**

构建包会出现在 `dist/mp-weixin` 目录下。

**实际结果**

构建包会出现在 `dist/dev/mp-weixin` 目录下。

**补充信息**

目前可以使用 `cross-env` 来规避这个问题，但这个解决方案不算优雅。

```shell
yarn add cross-env -D
```

```json
{
  "scripts": {
    ...,
    "dev:mp-weixin": "cross-env UNI_OUTPUT_DIR=dist/mp-weixin uni -p mp-weixin"
  }
}
```

**Comment by ringgoyao** [comment]
这个功能什么时候可以上线

**Comment by fxy060608** [comment]
目前可以使用 UNI_OUTPUT_DIR 环境变量传递，将来计划支持 vite 的 build.outDir 自定义，短期内暂无排期
