### ISSUE TITLE
uni.createSelectorQuery()获取不到节点信息

### ISSUE THREAD

**Issue by 451761830** [dcloudio/uni-app#3249]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
const query = uni.createSelectorQuery().in(this);
query.select('#id').boundingClientRect(data => {
  console.log("得到布局位置信息" + JSON.stringify(data));
  console.log("节点离页面顶部的距离为" + data.top);
}).exec();
在支付宝IDE运行项目页面中，用此方法获取节点信息获取不到；微信可以
HBuilderX版本：3.3.10

但是在自定义组件中用此方法又可以；

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Otto-J** [comment]
感谢反馈，后续更新了文档。

> 支付宝小程序不支持 in(component)，使用无效果

https://uniapp.dcloud.net.cn/api/ui/nodes-info.html#selectorquery-in

如有问题请补充更多项目上下文，或者复现工程。

**Comment by NoahSun** [comment]
> 感谢反馈，后续更新了文档。
> 
> > 支付宝小程序不支持 in(component)，使用无效果
> 
> https://uniapp.dcloud.net.cn/api/ui/nodes-info.html#selectorquery-in
> 
> 如有问题请补充更多项目上下文，或者复现工程。

@Otto-J [支付宝已支持in方法传入实例](https://opendocs.alipay.com/mini/0cs688)，能否支持一下？使用uni-use的`useSelectorQuery`还是获取不到当前示例下的节点信息
```js
  // 初始化 SelectorQuery 
  function initQuery() {
    if (query.value) {
      return;
    }
    const instance = getCurrentInstance();
    if (instance == null) {
      return;
    }
    // 支付宝平台使用下面语句，查询节点时返回的是null，微信平台正常
    query.value = uni.createSelectorQuery().in(instance);
  }
```
