### ISSUE TITLE
uniapp 编译到微信小程序 ios出现点击弹出层 穿透的问题

### ISSUE THREAD

**Issue by zhubufang** [dcloudio/uni-app#3253]
**问题描述**
编译到微信小程序 
问题一：ios出现点击弹出层 如果弹出层位置有input 或者textarea  会出现点击穿透问题 即input 会获取焦点，
问题二：input聚集的情况下 点击弹出层类组件（例如：picker等）input 不会失去焦点
这两个问题在大部分ios都存在，官方的小程序HelloUniapp也存在这个问题

**复现步骤**
[复现问题的步骤]
![781645062862_ pic](https://user-images.githubusercontent.com/40162775/154389494-9cbd4e60-bc26-4196-a2dc-a231c5095e6a.jpg)
![791645062863_ pic](https://user-images.githubusercontent.com/40162775/154389539-3e43431f-6a9b-4115-a329-409e9a2f3e79.jpg)
![821645062864_ pic](https://user-images.githubusercontent.com/40162775/154389554-88a557a3-a860-4ef8-8dd9-5c9fa9bde02d.jpg)
![831645062864_ pic](https://user-images.githubusercontent.com/40162775/154389570-ed869852-60fc-4e5e-8ef9-86e969847c66.jpg)

[或者可以直接贴源代码]

**预期结果**
点击蒙层 不应该有点击穿透

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序]
 - 操作系统 [如 iOS ]
 - HBuilderX版本 [3.3.11]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息  iPhone8 Plus，13等]

**Comment by Otto-J** [comment]
感谢反馈。

你提到官方的 uni-app 小程序也存在这个问题，可以提供操作步骤吗？如何复现这个问题，或者你可复现的工程。

只发问题截图，无助于定位和解决你的问题。

**Comment by zhubufang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by blackboxo** [comment]
我也碰到这个问题了

**Comment by zhubufang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
