### ISSUE TITLE
uni.chooseFile extension 在android侧获取的MIME问题

### ISSUE THREAD

**Issue by run-forrest** [dcloudio/uni-app#3255]
**问题描述**
uni.chooseFile这个api调用，传递到android侧的时候，获取到的MIME的type只有image/*和*/*,其他限制都没用

**复现步骤**
[复现问题的步骤]
1.  调用uni.chooseFile api
2.android侧onShowFileChooser方法内的FileChooserParams参数获取的值，遍历打印，没有其他MIME type，只有以上两种

**预期结果**
讲道理，应该有其他类型的输出，比如audio/*这种

**实际结果**
只接受到 */* 和image/* 两种类型，无论all和extension怎么设置

**系统信息:**
 - 发行平台:  android app
 - 操作系统 ：Android系统
 - 设备信息 ：华为手机都不行，其他手机应该也一样

**Comment by zhetengbiji** [comment]
目前只有H5平台有此接口，App端如果使用的是三方插件，可以咨询一下插件作者。
