### ISSUE TITLE
uniapp 编译到微信小程序时 对插件内传值 插件内无法获取

### ISSUE THREAD

**Issue by Leon522** [dcloudio/uni-app#3257]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
uniapp 编译到微信小程序时 对插件内传值 插件内无法获取

**复现步骤**
[复现问题的步骤]
npx degit dcloudio/uni-preset-vue#vite my-vue3-project 运行 
引入插件 
微信开发者工具查看

**预期结果**
对插件内传值 插件内能够获取到

**实际结果**
插件内无法获取值
![image](https://user-images.githubusercontent.com/15059173/154725846-54671680-7dc6-47b7-90fc-1884465bded7.png)
![image](https://user-images.githubusercontent.com/15059173/154725928-ece116f9-2759-4994-9d49-1235f9f39909.png)
**系统信息:**
 - 发行平台:  微信小程序
 - uni-app版本 
 - 
![image](https://user-images.githubusercontent.com/15059173/154726246-f7d94d74-853d-4d39-ae94-c60bf5023ac6.png)

 - 设备信息  微信开发者工具

**Comment by fxy060608** [comment]
发测试工程

**Comment by Leon522** [comment]
> 发测试工程

https://gitee.com/leon522/uniapp-demo.git

弄了一个最简单的demo

master分支是vue3版本，内部无法收到参数

vue2分支可以正常显示

**Comment by fxy060608** [comment]
> > 发测试工程
> 
> https://gitee.com/leon522/uniapp-demo.git
> 
> 弄了一个最简单的demo
> 
> master分支是vue3版本，内部无法收到参数
> 
> vue2分支可以正常显示

访问提示403，确认已公开了

**Comment by Leon522** [comment]
> https://gitee.com/leon522/uniapp-demo.git

已公开，可以访问了

**Comment by Leon522** [comment]
> > > 发测试工程
> > 
> > 
> > https://gitee.com/leon522/uniapp-demo.git
> > 弄了一个最简单的demo
> > master分支是vue3版本，内部无法收到参数
> > vue2分支可以正常显示
> 
> 访问提示403，确认已公开了

这个bug预计什么时候能解决呢

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3031120220221001

**Comment by Leon522** [comment]
> 已修复，cli更新至：3.0.0-alpha-3031120220221001

![image](https://user-images.githubusercontent.com/15059173/155066181-151d446e-7ffa-4546-b87a-320c9007e6f7.png)

使用npx @dcloudio/uvm alpha似乎更新失败

**Comment by fxy060608** [comment]
> > 已修复，cli更新至：3.0.0-alpha-3031120220221001
> 
> ![image](https://user-images.githubusercontent.com/15059173/155066181-151d446e-7ffa-4546-b87a-320c9007e6f7.png)
> 
> 使用npx @dcloudio/uvm alpha似乎更新失败

uvm目前不支持vue3,手动修改package.json

**Comment by Leon522** [comment]
> > > 已修复，cli更新至：3.0.0-alpha-3031120220221001
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/15059173/155066181-151d446e-7ffa-4546-b87a-320c9007e6f7.png)
> > 使用npx @dcloudio/uvm alpha似乎更新失败
> 
> uvm目前不支持vue3,手动修改package.json

![image](https://user-images.githubusercontent.com/15059173/155074983-9903e9a8-95d9-4f46-ab72-c9580b5fff3d.png)

改成如图所示的版本，依然无法生效

**Comment by fxy060608** [comment]
将package.json的^去掉，锁定：3.0.0-alpha-3031120220221001

**Comment by Leon522** [comment]
> 

可以了，感谢~
