### ISSUE TITLE
自定义组件点击事件无法触发

### ISSUE THREAD

**Issue by jin-yufeng** [dcloudio/uni-app#3259]
**问题描述**
自定义组件点击事件无法触发

**复现步骤**
```vue
<template>
	<view>
		<aa @tap="customTap"></aa>
	</view>
</template>

<script>
	export default {
		data() {
			return {}
		},
		methods: {
			customTap(e) {
				console.log('customTap', e)
			}
		}
	}
</script>
```
`aa` 是一个自定义组件，点击 `aa`

**预期结果**
触发点击事件

**实际结果**
`h5` 和 `app` 不触发事件，微信小程序可以触发，但事件信息是 `undefined`

**系统信息:**
 - HBuilderX版本 3.3.11

**Comment by fxy060608** [comment]
vue2的基础概念，自定义组件如果要监听原生事件，需要加.native修饰符，即：@tap.native="customTap"

**Comment by weixisheng** [comment]
还没解决吗
