### ISSUE TITLE
微信小程序 onError 捕获异常

### ISSUE THREAD

**Issue by magicwing** [dcloudio/uni-app#326]
[问题描述]
onError 捕获异常时，框架回调onError异常，导致报错死循环

[复现问题的步骤]
1.  app中定义onError(err) { console.log(err) }
2.  app中onLaunch抛出异常 throw new Error('抛出异常')
3.  微信小程序工具的console出现报错死循环

**实际结果**
![image](https://user-images.githubusercontent.com/7157683/56485663-827e4300-6507-11e9-8d5f-4f6e070fd996.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 全部
 - HBuilderX版本 1.9.2.20190417
 - uni-app版本 使用HBuilderX创建项目，版本应该与HBuilderX版本匹配
 - 设备信息 全部

**Comment by fxy060608** [comment]
cli已修复，HBuilderX 预计 1.9.4 Alpha 版本会修复此问题
