### ISSUE TITLE
[vue3] 微信小程序作用域插槽中v-for循环使用自定义组件报错

### ISSUE THREAD

**Issue by xmh0511** [dcloudio/uni-app#3263]
**问题描述**
版本Vue3。 微信小程序中，在使用作用域插槽时，如果在for循环中使用自定义的组件结构，那么就会产生`ReferenceError: i0 is not defined`错误。`scopedSlotsCompiler` 选项的三种模式都尝试过，都报错。

**复现步骤**
````html
<MyComponent>
     <template v-slot:default="slotProps"> 
        <view>
             <view v-for="(item,key) in dataList" :key="key">
                 <custom-component>{{item.title}}</custom-component>
                <!--<text>{{item.title}}</text> 这样使用正常-->
            </view>
        </view>
   </template>
</MyComponent>
`````
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
符合语法，正确执行

**实际结果**
<img width="622" alt="截屏2022-02-22 上午10 13 10" src="https://user-images.githubusercontent.com/17973891/155051832-3548b797-d325-4f0e-9ae9-576b0d844773.png">

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
发完整的测试工程，你截图的代码，作用域插槽没有意义

**Comment by xmh0511** [comment]
> 发完整的测试工程，你贴的代码，作用域插槽没有意义

[wxVue3.zip](https://github.com/dcloudio/uni-app/files/8114014/wxVue3.zip)

完整最小列子。
