### ISSUE TITLE
这个^3.0.0-alpha-3031220220222002版本post-css插件没有生效

### ISSUE THREAD

**Issue by lichengtao1989** [dcloudio/uni-app#3271]
**问题描述**
postcss-pxtorpx-pro，使用到这个插件，px转rpx

**复现步骤**
[复现问题的步骤]
1.  yarn add postcss-pxtorpx-pro -D '...'
2. 配置 postcss.config.js
3. const {
  uniPostcssPlugin
} = require('@dcloudio/uni-cli-shared')

module.exports = {
  plugins: [
    require("postcss-pxtorpx-pro")({
      transform: x => x
    }),
    uniPostcssPlugin(),
    require('autoprefixer')(),
  ]
}

[或者可以直接贴源代码]

**预期结果**
px转化为rpx

**实际结果**
没有转化为rpx

**系统信息:**
 - 发行平台: [ 微信小程序]
 - 操作系统 [macos 12.2.1 ]
 - 
 - uni-app版本 [3.0.0-alpha-3031220220222002]

**Comment by fxy060608** [comment]
使用https://vitejs.dev/config/#css-postcss配置

**Comment by xiaoxiangmoe** [comment]
@fxy060608 因为小程序需要用 rpx，而且设计稿可能某些页面是750px，某些页面是 828px，转换为 rpx 比较统一

**Comment by akFace** [comment]
> @fxy060608 因为小程序需要用 rpx，而且设计稿可能某些页面是750px，某些页面是 828px，转换为 rpx 比较统一


可以使用此插件 https://www.npmjs.com/package/momo-uniapp-px-to-rpx  默认为2倍：将1px转换成2rpx

vite创建的项目使用方式如下：
安装 ```npm install momo-uniapp-px-to-rpx --save```
```ts
// vite.config.ts
export default defineConfig({
  plugins: [
    alias({
      entries: [{ find: "@", replacement: resolve(__dirname, "src") }],
    }),
    uni()
  ],
  css: {
    postcss: {
      plugins: [
        require("momo-uniapp-px-to-rpx"), //插入此行
        require("postcss-import"),
        require("autoprefixer")({
          browsers: ["last 3 versions", "Android >= 4.1", "ios >= 8"],
          remove: false,
        })
      ],
    },
  },
});
```
