### ISSUE TITLE
[vue3] 微信小程序中使用<script setup>时在选项API中读取不到setup中声明的变量

### ISSUE THREAD

**Issue by xmh0511** [dcloudio/uni-app#3272]
**问题描述**
### case 1:
````javascript
<script setup>
    const count = ref(0);
</script>
<script>
   export default {
      mounted(){
        console.log(this.count);  // undefined
     }
   }
</script>
````
### case2:
````javascript
<script>
   export default {
     setup(){
          const count = ref(0);
          return {count};
     }
      mounted(){
        console.log(this.count);  // 0
     }
   }
</script>
````

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
两个例子的行为应该是一致的，都可以在mounted生命周期中读取到`setup`声明的变量

**实际结果**
第一种使用`<script setup>`语法糖的方式在选项API中读取不到`count`的值，而不使用语法糖通过setup函数返回的方式可以在`mounted`中读取到值

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by xmh0511** [comment]
最小化复现方式：
````javascript
<script setup>
import { ref, onMounted, getCurrentInstance } from "vue";
const variable = ref(1);
onMounted(()=>{
    const that = getCurrentInstance().proxy;
    console.log(that.variable); // undefined
});
</script>
`````
可能是<script setup>里面顶层定义的实体没有挂载到当前组件实例对象上，而`setup`的`retrun`做了挂载处理。

**Comment by fxy060608** [comment]
用法不正确，<script setup>作用域默认仅作用于template，如果在实例上访问到，需要使用defineExpose，https://vuejs.org/api/sfc-script-setup.html#defineexpose

**Comment by fxy060608** [comment]
https://github.com/vuejs/core/issues/4967

**Comment by xmh0511** [comment]
@fxy060608  目前就算是用`defineExpose`导出也无法访问到。

**Comment by fxy060608** [comment]
> @fxy060608 目前就算是用`defineExpose`导出也无法访问到。

看 defineExpose 的文档，适合什么场景

**Comment by xmh0511** [comment]
> > @fxy060608 目前就算是用`defineExpose`导出也无法访问到。
> 
> 看 defineExpose 的文档，适合什么场景

所以说，这种导出只能被父组件的引用实例访问到。组件自身想要访问，只能通过setup选项return出来才能访问（开发和发行）

**Comment by fxy060608** [comment]
> > > @fxy060608 目前就算是用`defineExpose`导出也无法访问到。
> > 
> > 
> > 看 defineExpose 的文档，适合什么场景
> 
> 所以说，这种导出只能被父组件的引用实例访问到。组件自身想要访问，只能通过setup选项return出来才能访问（开发和发行）

组件自身通常都可以直接访问到，不需要通过this来访问，你贴的代码的用法，都是不必要的

**Comment by llcat** [comment]
> > > > @fxy060608 目前就算是用`defineExpose`导出也无法访问到。
> > > 
> > > 
> > > 看 defineExpose 的文档，适合什么场景
> > 
> > 
> > 所以说，这种导出只能被父组件的引用实例访问到。组件自身想要访问，只能通过setup选项return出来才能访问（开发和发行）
> 
> 组件自身通常都可以直接访问到，不需要通过this来访问，你贴的代码的用法，都是不必要的

问题在于 `<script setup></script>` 在`develpment`环境下和`production`环境下的体验不一致,  开发环境下`<script setup></script>` 中定义的变量和方法能在`options api`中能访问, 如果不要让开发者混用这两种api, 希望在开发者模式中就禁止这种行为

**Comment by fxy060608** [comment]
> > > > > @fxy060608 目前就算是用`defineExpose`导出也无法访问到。
> > > > 
> > > > 
> > > > 看 defineExpose 的文档，适合什么场景
> > > 
> > > 
> > > 所以说，这种导出只能被父组件的引用实例访问到。组件自身想要访问，只能通过setup选项return出来才能访问（开发和发行）
> > 
> > 
> > 组件自身通常都可以直接访问到，不需要通过this来访问，你贴的代码的用法，都是不必要的
> 
> 问题在于 `<script setup></script>` 在`develpment`环境下和`production`环境下的体验不一致, 开发环境下`<script setup></script>` 中定义的变量和方法能在`options api`中能访问, 如果不要让开发者混用这两种api, 希望在开发者模式中就禁止这种行为

已经贴了vue官方的issue，有异议的话，可以直接在vue官方提问

**Comment by llcat** [comment]
> > > > > > @fxy060608 目前就算是用`defineExpose`导出也无法访问到。
> > > > > 
> > > > > 
> > > > > 看 defineExpose 的文档，适合什么场景
> > > > 
> > > > 
> > > > 所以说，这种导出只能被父组件的引用实例访问到。组件自身想要访问，只能通过setup选项return出来才能访问（开发和发行）
> > > 
> > > 
> > > 组件自身通常都可以直接访问到，不需要通过this来访问，你贴的代码的用法，都是不必要的
> > 
> > 
> > 问题在于 `<script setup></script>` 在`develpment`环境下和`production`环境下的体验不一致, 开发环境下`<script setup></script>` 中定义的变量和方法能在`options api`中能访问, 如果不要让开发者混用这两种api, 希望在开发者模式中就禁止这种行为
> 
> 已经贴了vue官方的issue，有异议的话，可以直接在vue官方提问

嗯, 一路看过来的, 我去官方的相关的issue留言
