### ISSUE TITLE
自定义样式无法直接使用，导致externalclasses不生效

### ISSUE THREAD

**Issue by zhuli2010** [dcloudio/uni-app#3275]
**问题描述**
在当前使用版本3.0.0-alpha-3030520211229004， 包括最新发布的版本，在该文件/node_modules/@dcloudio/uni-mp-compiler/dist/transforms/transformComponent.js，多了一个重写props绑定的函数rewriteBinding。该函数会对自定义属性进行过滤，
<img width="890" alt="image" src="https://user-images.githubusercontent.com/32993260/155450251-11bf990c-0d6d-4638-b208-dff090b0bccf.png">
<img width="365" alt="image" src="https://user-images.githubusercontent.com/32993260/155450282-30e7bf5c-9799-42e7-a00a-10c152a3e9be.png">
因此编译结果，
<img width="616" alt="image" src="https://user-images.githubusercontent.com/32993260/155450639-bd418bb1-2897-4e1a-817f-0a03b01cde4c.png">
<img width="505" alt="image" src="https://user-images.githubusercontent.com/32993260/155450933-bd4b439f-9872-4ea1-84bd-d240c18f32e1.png">
会将对应的externalclasses属性从wxml文件的view上剔除，转移到js文件中，然后这种自定义属性的转换方式，会导致小程序编译无法识别到对应的自定义class 属性

**Comment by zhenyuWang** [comment]
临时解决方案可参考 https://ask.dcloud.net.cn/question/163695

**Comment by Otto-J** [comment]
> 上述临时方案供有需求用户使用，但该方式和 vue2 有明显差异，目前没有计划作为官方支持方式正式推出

https://ask.dcloud.net.cn/question/163695

**Comment by wvfeng** [comment]
> 临时解决方案可参考 https://ask.dcloud.net.cn/question/163695

环境：`@dcloudio/uni-app:3.0.0-4000820240401001` `vue:^3.3.11`

尝试使用临时解决方案中的示例
`<child external:l-class="custom" class="size" />`
在这种形式编译报错

我查看了相关PR [Enhance mp externalclasses and vue props](https://github.com/dcloudio/uni-app/pull/1383)
最终也没明白这个PR是如何使用的，官方也没个文档说明


我参考临时解决方案，找到了文件`node_modules/@dcloudio/uni-mp-compiler/dist/transforms/transformComponent.js`
通过修改方法`isComponentProp`达到了目的，在此记录希望能够帮助有需要的人，修改后的代码如下
`function isComponentProp(name) {
    if (builtInProps.includes(name)) {
        return false;
    }
    if (name.startsWith('data-')) {
        return false;
    }
    if (name.endsWith('-class')) {
        return false;
    }
    return true;
}`
添加了三行
` if (name.endsWith('-class')) {
        return false;
    }`
没有使用`HBuilderX`这种方案也是生效的，只要在项目下找到对应文件修改即可
