### ISSUE TITLE
微信小程序新增  LazyCodeLoading 选项 无法添加在 uniapp weixin 中 按需注入和用时注入

### ISSUE THREAD

**Issue by nshusr** [dcloudio/uni-app#3276]
**新功能描述**
微信小程序添加新选项
https://developers.weixin.qq.com/miniprogram/dev/framework/ability/lazyload.html#%E6%8C%89%E9%9C%80%E6%B3%A8%E5%85%A5
<img width="1211" alt="image" src="https://user-images.githubusercontent.com/45023042/155455631-b1838891-a604-4095-aa8d-cc2ca16f5bd3.png">

**现状及问题**
官方文档中
https://developers.weixin.qq.com/miniprogram/dev/reference/configuration/app.html#lazyCodeLoading

**Comment by PineSongCN** [comment]
没看懂应该怎么配，等一个知道的

**Comment by PineSongCN** [comment]
找到了，直接在manifest.json的mp-weixin配就行。
<img width="445" alt="image" src="https://user-images.githubusercontent.com/39976617/156115740-84f2118d-0eff-417d-afde-cd010aa5b701.png">

**Comment by nshusr** [comment]
> 

打包出来也是有效的吗？

**Comment by nshusr** [comment]
确实有效 ohhhh
