### ISSUE TITLE
uni-app 通过 HBuilderX 创建项目，对 Vue3 语法具体支持到哪个版本？

### ISSUE THREAD

**Issue by Hongbusi** [dcloudio/uni-app#3277]
**现状及问题**
``` js
import { defineProps, defineEmits } from 'vue'

defineProps({
  counter: Number
})

const emit = defineEmits(['test-event'])

const handleClick = () => {
  console.log('click')
  emit('test-event')
}
```

运行的时候报错：

``` bash
`defineProps` is a compiler macro and no longer needs to be imported.
`defineEmits` is a compiler macro and no longer needs to be imported.
```

**补充信息**
通过 HBuilderX 创建的项目，官方文档仅仅提到了 options `setup() {}` 的方式去写 Vue3。

想知道，具体支持 Vue3 的哪一个版本。

谢谢～

**Comment by fxy060608** [comment]
会保持 vue 的版本更新，按最新的使用即可，稍后编译时会提示当前使用的 vue 版本号

**Comment by Hongbusi** [comment]
但是在微信小程序中，不能正常运行。如果把 `script setup` 换成 `setup() {}` 的写法就正常。 @fxy060608

**Comment by fxy060608** [comment]
> 但是在微信小程序中，不能正常运行。如果把 `script setup` 换成 `setup() {}` 的写法就正常。 @fxy060608

写法不正确，不是提示了defineProps，defineEmits都是宏么，不需要从 vue 中 import
如果还有问题，发测试工程

**Comment by Hongbusi** [comment]
在小程序中，不能正常运行。 [demo](https://github.com/Hongbusi/uni-app-demo) @fxy060608

**Comment by fxy060608** [comment]
> 在小程序中，不能正常运行。 [demo](https://github.com/Hongbusi/uni-app-demo) @fxy060608

这个问题 cli 已经修复了，只是 HBuilderX 还没发版，临时解决方案，是把事件名换成驼峰

https://github.com/dcloudio/uni-app/issues/3210

**Comment by Hongbusi** [comment]
好的，多谢～
