### ISSUE TITLE
cli 搭建新项目启动失败

### ISSUE THREAD

**Issue by susgit** [dcloudio/uni-app#3278]
**问题描述**
node版本12.19.0，使用cli搭建项目，yarn serve报错

**复现步骤**
vue create -p dcloudio/uni-preset-vue#alpha my-alpha-project
yarn serve
<img width="532" alt="1645691943(1)" src="https://user-images.githubusercontent.com/68681019/155488796-aea6aea1-fe90-41ae-a95c-3c9c52fdf381.png">
之后删除依赖 重新install
<img width="538" alt="1645691967(1)" src="https://user-images.githubusercontent.com/68681019/155488864-dbf14b71-f146-41bd-95d6-57929ffd57a5.png">

尝试切换为node12，无效。

**Comment by fxy060608** [comment]
降级到 @vue/cli@4 版本测试
