### ISSUE TITLE
SyntaxError: Unexpected keyword 'const'. Const declarations are not supported in strict mode.

### ISSUE THREAD

**Issue by BrightYang0801** [dcloudio/uni-app#328]
**问题描述**
ios系统9及以下版本，小程序报错，白屏。

**补充信息**
[应该是这个原因导致：](https://github.com/mrdulin/blog/issues/35)

**Comment by xiaoyucoding** [comment]
可以提供下体报错的文件么，类似的问题近期处理过，需要确认下是否是相同的问题。

**Comment by BrightYang0801** [comment]
> 可以提供下具体报错的文件么，类似的问题近期处理过，需要确认下是否是相同的问题。

![image](https://user-images.githubusercontent.com/37973515/56547557-6387bb80-65b0-11e9-89f6-8c3faf19924e.png)

我截得图，咋定位到具体文件？？？

**Comment by BrightYang0801** [comment]
![image](https://user-images.githubusercontent.com/37973515/56547609-8b771f00-65b0-11e9-98f1-d924722d38a0.png)

**Comment by xiaoyucoding** [comment]
HBuilderX 1.9.3 及 CLI 均已发布更新，建议更新一下再测试是否依旧存在此问题。

**Comment by BrightYang0801** [comment]
好的
