### ISSUE TITLE
如何在小程序平台保留自定义attr

### ISSUE THREAD

**Issue by PentaTea** [dcloudio/uni-app#3280]
小程序如何保留类似这种属性
![image](https://user-images.githubusercontent.com/26431026/155643868-9206374a-d66b-40c6-873f-317e51b2b0b8.png)

很多原子化css框架都支持属性选择器,如Tailwind,Windi等,可是编译到小程序后属性都被删除了

我调试中发现uni-mp-compiler返回给vue的ast.props中是有完整的attr (vue3)

请问小程序中为何没有自定义attr?是技术上无法实现还是被过滤掉了,有办法让他显示吗

**Comment by fxy060608** [comment]
属性选择器，在小程序组件中不支持：https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/wxml-wxss.html#%E7%BB%84%E4%BB%B6%E6%A0%B7%E5%BC%8F

**Comment by PentaTea** [comment]
好的谢谢(居然还有这种事情
