### ISSUE TITLE
通过vue create -p dcloudio/uni-preset-vue my-project命令行创建的vue2项目编译运行到微信小程序会报错

### ISSUE THREAD

**Issue by hzf-666** [dcloudio/uni-app#3281]
**问题描述**
通过vue create -p dcloudio/uni-preset-vue my-project命令行创建的vue2项目编译运行到微信小程序会报错

**复现步骤**
[复现问题的步骤]
1.  通过命令行创建vue2项目：vue create -p dcloudio/uni-preset-vue my-project
2. 进入刚创建好的项目：cd my-project
3. 编译运行到微信小程序：npm run dev:mp-weixin

[或者可以直接贴源代码]

**预期结果**
项目可以成功运行，不会出现报错

**实际结果**
![image](https://user-images.githubusercontent.com/55825301/155829714-e0ff6536-bed8-4789-86c1-dd550be55fb7.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 ![image](https://user-images.githubusercontent.com/55825301/155829892-d2048e6f-5e8a-4dd6-9b49-6a56247d613e.png)
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - ![image](https://user-images.githubusercontent.com/55825301/155829903-16436095-7f5e-4a5b-8bd3-475b9d60a5ab.png)
 - 设备信息 ![image](https://user-images.githubusercontent.com/55825301/155829892-d2048e6f-5e8a-4dd6-9b49-6a56247d613e.png)

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
运行编译到微信小程序时，vue引入的是vue3版本

**Comment by fxy060608** [comment]
vue2和vue3使用的是不同的工程创建命令
`npx degit dcloudio/uni-preset-vue#vite my-vue3-project`

**Comment by hzf-666** [comment]
> vue2和vue3使用的是不同的创建命令 `npx degit dcloudio/uni-preset-vue#vite my-vue3-project`

我想创建的是vue2的项目，不是vue3的，我的意思是创建vue2项目后编译到微信小程序报错了

**Comment by fxy060608** [comment]
> 运行编译到微信小程序时，vue引入的是vue3版本

为何问题里描述的是 `运行编译到微信小程序时，vue引入的是vue3版本`
创建出来的vue2项目测试没有问题，如果还有问题，可以发测试工程，说明微信开发者工具版本

**Comment by hzf-666** [comment]
> > 运行编译到微信小程序时，vue引入的是vue3版本
> 
> 为何问题里描述的是 `运行编译到微信小程序时，vue引入的是vue3版本` vue2项目只能引入vue2版本 创建出来的vue2项目测试没有问题，如果还有问题，可以发测试工程，说明微信开发者工具版本

[https://github.com/hzf-666/my-project](url)
微信开发者工具版本是：1.05.2203032
npm run dev:mp-weixin 报错信息：
![NPK@T)P{N2OI{P`BT5I81AB](https://user-images.githubusercontent.com/55825301/157427981-19002361-d00c-4de8-8fa8-489fc5c82a14.png)
