### ISSUE TITLE
H5 端的 canvas 无法绘制文字

### ISSUE THREAD

**Issue by liyongning** [dcloudio/uni-app#3286]
**问题描述**
最新版的 uni-app（3.0.0-alpha-3040020220225001） Vue3，H5 侧的 canvas 无法绘制文字

**复现步骤**
直接用官方示例：
```javascript
const ctx = uni.createCanvasContext('myCanvas')

ctx.setFontSize(20)
ctx.fillText('Hello', 20, 20)
ctx.fillText('MINA', 100, 100)

ctx.draw()
```

**预期结果**
<img width="327" alt="image" src="https://user-images.githubusercontent.com/26913352/155883795-ead628dc-3069-4de4-9ded-b9418d539cd4.png">

**实际结果**
<img width="325" alt="image" src="https://user-images.githubusercontent.com/26913352/155883826-c8683754-3811-467c-bc94-5cb711c2473f.png">

**系统信息:**
 - 发行平台: H5平台
 - 操作系统: Mac
 - uni-app版本: 3.0.0-alpha-3040020220225001

**补充信息**
出现上述的原因是因为在处理 fillText 和 strokeText 的第四个参数时未进行判断。

因为 canvasCtx.fillText 和 canvasCtx.strokeText 的第 4 个参数为可选参数，用户可能不传，所以在处理时需要判断一下，否则 undefined * pixelRatio => NaN，会导致 canvas 无法绘制。

会提 PR 进行修复。

**Comment by zhetengbiji** [comment]
已发布到：3.0.0-alpha-3040020220228001
