### ISSUE TITLE
mpType关键字

### ISSUE THREAD

**Issue by c1394393468** [dcloudio/uni-app#329]
**问题描述**
Data中生声明 mpType的变量，会导致本页面所有Data中的赋值失效
但文档中并未将其声明为关键字
**复现步骤**
<text>{{str}}</text>
data中 
mpType: 0,
str: "123"

click 中 
this.str = ”111“

此时data设置失效

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 模拟器
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
官方文档中并未将其保留为关键字
 是否与App.mpType 产生了冲突？

**Comment by xiaoyucoding** [comment]
main.js 中会有定义此属性
```javascript
App.mpType = 'app'
```
建议换个名字，以避免冲突。

**Comment by c1394393468** [comment]
是的，希望文档中也注明下，保留关键字

**Comment by bigGoodMan** [comment]
mpType 这个属性具体是用作什么的
