### ISSUE TITLE
[vue3] 发布模式下import导入wxcomponents中的模块会产生undefined

### ISSUE THREAD

**Issue by xmh0511** [dcloudio/uni-app#3290]
**问题描述**
````javascript
<script>
import moduleA from "@/utilities/moduleA.js"
import wxModule from "@/wxcomponents/wxmodule/dialog.js"
console.log("outside normal: ",moduleA);  // 输出正常
console.log("outside wx: ", wxModule);   // undefined
</script>
````
其中模块都是默认导出
````javascript
export default {
  .....
}
````

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
无论是从哪个目录导入，都应该正常导入模块

**实际结果**
如上面代码所示，从`wxcomponents`目录中导入模块在**发布**模式下，会产生`undefined`

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

通过查看编译后的源码，在发布模式下，所有从`wxcomponents`目录导入的模块会进行特殊处理。`console.log("outside wx: ", wxModule); ` 会自动编译成 `console.log("outside wx: ", t.wxModule); ` 其中 `t` 被声明为 `var t = requires("../wxcomponents/dialog.js")`。 这导致原本名称`wxModule`表示的模块中的对象却被编译成模块中对象里面的属性了。

### 最小复现例子

[testImport.zip](https://github.com/dcloudio/uni-app/files/8150795/testImport.zip)

**Comment by fxy060608** [comment]
wxcomponents是专门放置小程序组件的，编译器会原封不动拷贝到输出目录，不要在代码里引用该目录的js，就像static等目录一样，都不应该有这样的使用方式

**Comment by xmh0511** [comment]
> wxcomponents是专门放置小程序组件的，编译器会原封不动拷贝到输出目录，不要在代码里引用该目录的js，就像static等目录一样，都不应该有这样的使用方式

但这是 `vant-weapp`的使用方式，改UI组件库里很多组件依赖这样的使用方式

**Comment by fxy060608** [comment]
> > wxcomponents是专门放置小程序组件的，编译器会原封不动拷贝到输出目录，不要在代码里引用该目录的js，就像static等目录一样，都不应该有这样的使用方式
> 
> 但这是 `vant-weapp`的使用方式，改UI组件库里很多组件依赖这样的使用方式

看不懂什么意思，如果使用vant，那也只是把vant放到wxcomponents里边，其他地方用vant的组件即可，还要使用它的js代码？

**Comment by xmh0511** [comment]
> > > wxcomponents是专门放置小程序组件的，编译器会原封不动拷贝到输出目录，不要在代码里引用该目录的js，就像static等目录一样，都不应该有这样的使用方式
> > 
> > 
> > 但这是 `vant-weapp`的使用方式，改UI组件库里很多组件依赖这样的使用方式
> 
> 看不懂什么意思，如果使用vant，那也只是把vant放到wxcomponents里边，其他地方用vant的组件即可，还要使用它的js代码？

参考一下 `vant-weapp`中Dialog的用法，他需要在页面中导入`import Dialog from '@/wxcomponents/vant-weapp/dialog/dialog.js';` 其中`dialog.js`是通过`export default Dialog`这样导出的，这样使用在开发模式下没有问题，但是在发布模式下，代码中所有对`Dialog`的引用都会被替换成`t.Dialog` 这就引发了问题，原本语义是通过`Dialog`表示导入的模块，而再发布模式下却是`t`

**Comment by fxy060608** [comment]
> > > > wxcomponents是专门放置小程序组件的，编译器会原封不动拷贝到输出目录，不要在代码里引用该目录的js，就像static等目录一样，都不应该有这样的使用方式
> > > 
> > > 
> > > 但这是 `vant-weapp`的使用方式，改UI组件库里很多组件依赖这样的使用方式
> > 
> > 
> > 看不懂什么意思，如果使用vant，那也只是把vant放到wxcomponents里边，其他地方用vant的组件即可，还要使用它的js代码？
> 
> 参考一下 `vant-weapp`中Dialog的用法，他需要在页面中导入`import Dialog from '@/wxcomponents/vant-weapp/dialog/dialog.js';` 其中`dialog.js`是通过`export default Dialog`这样导出的，这样使用在开发模式下没有问题，但是在发布模式下，代码中所有对`Dialog`的引用都会被替换成`t.Dialog` 这就引发了问题，原本语义是通过`Dialog`表示导入的模块，而再发布模式下却是`t`
> 
> https://vant-contrib.gitee.io/vant-weapp/#/dialog

不要使用函数调用，应该使用组件调用，函数调用它操作的是小程序Page里的数据，跟uni-app是冲突的

**Comment by xmh0511** [comment]
> > > > > wxcomponents是专门放置小程序组件的，编译器会原封不动拷贝到输出目录，不要在代码里引用该目录的js，就像static等目录一样，都不应该有这样的使用方式
> > > > 
> > > > 
> > > > 但这是 `vant-weapp`的使用方式，改UI组件库里很多组件依赖这样的使用方式
> > > 
> > > 
> > > 看不懂什么意思，如果使用vant，那也只是把vant放到wxcomponents里边，其他地方用vant的组件即可，还要使用它的js代码？
> > 
> > 
> > 参考一下 `vant-weapp`中Dialog的用法，他需要在页面中导入`import Dialog from '@/wxcomponents/vant-weapp/dialog/dialog.js';` 其中`dialog.js`是通过`export default Dialog`这样导出的，这样使用在开发模式下没有问题，但是在发布模式下，代码中所有对`Dialog`的引用都会被替换成`t.Dialog` 这就引发了问题，原本语义是通过`Dialog`表示导入的模块，而再发布模式下却是`t`
> > https://vant-contrib.gitee.io/vant-weapp/#/dialog
> 
> 不要使用函数调用，应该使用组件调用，函数调用它操作的是小程序Page里的数据，跟uni-app是冲突的

我认为这应该不是函数调用的问题，是发布模式下对`wxcomponents`中js文件通过**默认**方式导出模块的处理方式存在问题。
````
// 某模块
export default {
   title:"abc"
}
````
````
import ModuleA from "某模块"
console.log(ModuleA.title) // 开发模式正确，发布模式ModuleA为undefined
````

**Comment by fxy060608** [comment]
> > > > > > wxcomponents是专门放置小程序组件的，编译器会原封不动拷贝到输出目录，不要在代码里引用该目录的js，就像static等目录一样，都不应该有这样的使用方式
> > > > > 
> > > > > 
> > > > > 但这是 `vant-weapp`的使用方式，改UI组件库里很多组件依赖这样的使用方式
> > > > 
> > > > 
> > > > 看不懂什么意思，如果使用vant，那也只是把vant放到wxcomponents里边，其他地方用vant的组件即可，还要使用它的js代码？
> > > 
> > > 
> > > 参考一下 `vant-weapp`中Dialog的用法，他需要在页面中导入`import Dialog from '@/wxcomponents/vant-weapp/dialog/dialog.js';` 其中`dialog.js`是通过`export default Dialog`这样导出的，这样使用在开发模式下没有问题，但是在发布模式下，代码中所有对`Dialog`的引用都会被替换成`t.Dialog` 这就引发了问题，原本语义是通过`Dialog`表示导入的模块，而再发布模式下却是`t`
> > > https://vant-contrib.gitee.io/vant-weapp/#/dialog
> > 
> > 
> > 不要使用函数调用，应该使用组件调用，函数调用它操作的是小程序Page里的数据，跟uni-app是冲突的
> 
> 我认为这应该不是函数调用的问题，是发布模式下对`wxcomponents`中js文件通过**默认**方式导出模块的处理方式存在问题。
> 
> ```
> // 某模块
> export default {
>    title:"abc"
> }
> ```
> 
> ```
> import ModuleA from "某模块"
> console.log(ModuleA.title) // 开发模式正确，发布模式ModuleA为undefined
> ```

如上所说，编译器是原封不动拷贝wxcomponents的，而你的dialog.js是需要被编译的，这个在使用上是有冲突的，开发时正确，发行后错误，就是因为本身就不支持这样的用法，一个dialog.js，一会被编译，一会被拷贝，两个会互相覆盖

**Comment by xmh0511** [comment]
> > > > > > > wxcomponents是专门放置小程序组件的，编译器会原封不动拷贝到输出目录，不要在代码里引用该目录的js，就像static等目录一样，都不应该有这样的使用方式
> > > > > > 
> > > > > > 
> > > > > > 但这是 `vant-weapp`的使用方式，改UI组件库里很多组件依赖这样的使用方式
> > > > > 
> > > > > 
> > > > > 看不懂什么意思，如果使用vant，那也只是把vant放到wxcomponents里边，其他地方用vant的组件即可，还要使用它的js代码？
> > > > 
> > > > 
> > > > 参考一下 `vant-weapp`中Dialog的用法，他需要在页面中导入`import Dialog from '@/wxcomponents/vant-weapp/dialog/dialog.js';` 其中`dialog.js`是通过`export default Dialog`这样导出的，这样使用在开发模式下没有问题，但是在发布模式下，代码中所有对`Dialog`的引用都会被替换成`t.Dialog` 这就引发了问题，原本语义是通过`Dialog`表示导入的模块，而再发布模式下却是`t`
> > > > https://vant-contrib.gitee.io/vant-weapp/#/dialog
> > > 
> > > 
> > > 不要使用函数调用，应该使用组件调用，函数调用它操作的是小程序Page里的数据，跟uni-app是冲突的
> > 
> > 
> > 我认为这应该不是函数调用的问题，是发布模式下对`wxcomponents`中js文件通过**默认**方式导出模块的处理方式存在问题。
> > ```
> > // 某模块
> > export default {
> >    title:"abc"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > import ModuleA from "某模块"
> > console.log(ModuleA.title) // 开发模式正确，发布模式ModuleA为undefined
> > ```
> 
> 如上所说，编译器是原封不动拷贝wxcomponents的，而你的dialog.js是需要被编译的，这个在使用上是有冲突的，开发时正确，发行后错误，就是因为本身就不支持这样的用法，一个dialog.js，一会被编译，一会被拷贝，两个会互相覆盖

所以说，这应该是`vant-weapp`的bug? 顺便说一下，这种用法在`vue2`中无论是开发还是发行都没有问题呢。而在`vue3`版本中，`wxcomponents`中的模块通过 `export const Dialog = {}`具名导出，然后在需要引用到的地方`import {Dialog} from "路径"`,在发行模式下也是可以正常使用的。

**Comment by fxy060608** [comment]
> > > > > > > > wxcomponents是专门放置小程序组件的，编译器会原封不动拷贝到输出目录，不要在代码里引用该目录的js，就像static等目录一样，都不应该有这样的使用方式
> > > > > > > 
> > > > > > > 
> > > > > > > 但这是 `vant-weapp`的使用方式，改UI组件库里很多组件依赖这样的使用方式
> > > > > > 
> > > > > > 
> > > > > > 看不懂什么意思，如果使用vant，那也只是把vant放到wxcomponents里边，其他地方用vant的组件即可，还要使用它的js代码？
> > > > > 
> > > > > 
> > > > > 参考一下 `vant-weapp`中Dialog的用法，他需要在页面中导入`import Dialog from '@/wxcomponents/vant-weapp/dialog/dialog.js';` 其中`dialog.js`是通过`export default Dialog`这样导出的，这样使用在开发模式下没有问题，但是在发布模式下，代码中所有对`Dialog`的引用都会被替换成`t.Dialog` 这就引发了问题，原本语义是通过`Dialog`表示导入的模块，而再发布模式下却是`t`
> > > > > https://vant-contrib.gitee.io/vant-weapp/#/dialog
> > > > 
> > > > 
> > > > 不要使用函数调用，应该使用组件调用，函数调用它操作的是小程序Page里的数据，跟uni-app是冲突的
> > > 
> > > 
> > > 我认为这应该不是函数调用的问题，是发布模式下对`wxcomponents`中js文件通过**默认**方式导出模块的处理方式存在问题。
> > > ```
> > > // 某模块
> > > export default {
> > >    title:"abc"
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ```
> > > import ModuleA from "某模块"
> > > console.log(ModuleA.title) // 开发模式正确，发布模式ModuleA为undefined
> > > ```
> > 
> > 
> > 如上所说，编译器是原封不动拷贝wxcomponents的，而你的dialog.js是需要被编译的，这个在使用上是有冲突的，开发时正确，发行后错误，就是因为本身就不支持这样的用法，一个dialog.js，一会被编译，一会被拷贝，两个会互相覆盖
> 
> 所以说，这应该是`vant-weapp`的bug? 顺便说一下，这种用法在`vue2`中无论是开发还是发行都没有问题呢。而在`vue3`版本中，`wxcomponents`中的模块通过 `export const Dialog = {}`具名导出，然后在需要引用到的地方`import {Dialog} from "路径"`,在发行模式下也是可以正常使用的。

vue2中可以，是因为编译后的代码，你的dialog存在了两份，一份在wxcomponents里边，一份被编译到了vendor等js中，而vue3为了优化，编译后的js文件会保持原来的位置，所以dialog存在冲突覆盖的问题。

**Comment by xmh0511** [comment]
@fxy060608 其他目录是可以使用的，如我上面的那个例子所示。但这造成了一个问题，那就是很多`wxcomponents`的第三方库都会用到这样的模块导入和相应的函数调用，这导致我们发行的时候存在大量此类问题所造成的问题

**Comment by fxy060608** [comment]
> @fxy060608 其他目录是可以使用的，如我上面的那个例子所示。但这造成了一个问题，那就是很多`wxcomponents`的第三方库都会用到这样的模块导入和相应的函数调用，这导致我们发行的时候存在大量此类问题所造成的问题

建议尽量使用uni-app的跨平台组件库

**Comment by xmh0511** [comment]
> 

反过来说，这还是说明`vant-weapp`的模块没有符合uni-app的标准来编写吧。如果其中所有的模块都是具名导出，在发布模式下都没有问题的

**Comment by fxy060608** [comment]
> > 
> 
> 反过来说，这还是说明`vant-weapp`的模块没有符合uni-app的标准来编写吧。如果其中所有的模块都是具名导出，在发布模式下都没有问题的
自己加个 vite.config.js 做处理吧，框架目前没计划内置处理
```js
import {
    defineConfig
} from "vite";
import uni from "@dcloudio/vite-plugin-uni";

/**
 * @type {import('vite').UserConfig}
 */
export default defineConfig({
    plugins: [uni(), {
        name: 'fix-wxcomponents',
        enforce: 'post',
        configResolved(config) {
            if (process.env.UNI_PLATFORM === 'mp-weixin') {
                const {
                    output
                } = config.build.rollupOptions
                const {
                    manualChunks
                } = output
                output.manualChunks = (id, api) => {
                    if (id.includes('wxcomponents')) {
                        // 将 wxcomponents 中的 js 编译为 common/wxcomponents.js
                        return 'common/wxcomponents'
                    }
                    return manualChunks(id, api)
                }
            }
        }
    }],
});

```

**Comment by xmh0511** [comment]
@fxy060608  加了这个代码就可以了👍🏻。还是希望官方能内置处理一下这个问题，毕竟很多第三方库包括uni-app的插件市场的很多第三方的轮子都是在`wxcomponent`里面通过模块的方式暴露一些接口并且这些模块都是**默认**导出。

**Comment by flycran** [comment]
uniapp和vant的兼容性相当差，但是双方都不肯做出兼容，出现bug也只会互相甩锅。但uniapp是个编译器，vant只是个组件库，作为编译器应当有理由做出最大的兼容性。维护团队的漠视注定将uniapp生态走向灭亡
