### ISSUE TITLE
[vue3] 目前uni-app不支持vue3支持的自定义事件名kebab-case的写法 

### ISSUE THREAD

**Issue by xmh0511** [dcloudio/uni-app#3291]
**问题描述**
````javascript
export default {
  emits:{
    myEvent:null
  }
   setup(props,context){
       context.emit("myEvent",{data:1});
   }
}
````
````javascript
<Father>
<Child @my-event="doSomething"></Child>
</Father>
````

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
支持vue3的事件命名方式

**实际结果**
监听器没有任何反应，只有写成vue2中的`@myEvent="doSomething"`才有反应

[根据你的分析，出现这个问题的原因可能在哪里？]

https://v3.cn.vuejs.org/guide/component-custom-events.html#%E4%BA%8B%E4%BB%B6%E5%90%8D
> [vue3]
>> -  与组件和 prop 一样，事件名提供了自动的大小写转换。如果在子组件中触发一个以 camelCase (驼峰式命名) 命名的事件，你将可以在父组件中添加一个 kebab-case (短横线分隔命名) 的监听器。

> [vue2]
>> - 不同于组件和 prop，事件名不存在任何自动化的大小写转换。而是触发的事件名需要完全匹配监听这个事件所用的名称。举个例子，如果触发一个 camelCase 名字的事件：
>> - 则监听这个名字的 kebab-case 版本是不会有任何效果的：

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/3210

**Comment by xmh0511** [comment]
> #3210

请问一下，如何更新cli?

**Comment by xmh0511** [comment]
Duplicate with #3210

**Comment by fxy060608** [comment]
> > #3210
> 
> 请问一下，如何更新cli?

可以直接修改package.json中的版本号

**Comment by xmh0511** [comment]
> > > #3210
> > 
> > 
> > 请问一下，如何更新cli?
> 
> 可以直接修改package.json中的版本号

我的项目中没有`package.json`文件，只有`package-lock.json`，具体怎么操作呢？
<img width="389" alt="截屏2022-02-28 下午3 14 42" src="https://user-images.githubusercontent.com/17973891/155941470-93328eb2-2608-46e1-84f4-17571c453951.png">

这是我的bian'ji'q编辑器版本

**Comment by fxy060608** [comment]
> > > > #3210
> > > 
> > > 
> > > 请问一下，如何更新cli?
> > 
> > 
> > 可以直接修改package.json中的版本号
> 
> 我的项目中没有`package.json`文件，只有`package-lock.json`，具体怎么操作呢？ <img alt="截屏2022-02-28 下午3 14 42" width="389" src="https://user-images.githubusercontent.com/17973891/155941470-93328eb2-2608-46e1-84f4-17571c453951.png">
> 
> 这是我的编辑器版本

HBuilderX需要等下次发版
