### ISSUE TITLE
[H5] dataset 值异常

### ISSUE THREAD

**Issue by okxiaoliang4** [dcloudio/uni-app#3292]
**问题描述**
H5 环境 `dataset` 值异常.

**复现步骤**
```vue
<button
  v-for="examItem in item.itemData.items"
  :key="examItem.examCode"
  class="classify-item"
  :open-type="openType"
  :data-item="examItem"
  data-type="show"
  @click="onExamItemClick"
  @getphonenumber="onGetPhoneNumber"
  @getuserinfo="onGetUserInfo"
>
  <image class="classify-item__image" :src="examItem.icon.icon_url" mode="widthFix" />
  <text class="classify-item__text">{{ examItem.examName }}</text>
</button>
```
当处于dev开发模式时
`dataset.item` 的值为正常的对象, 但`build`构建后`dataset.item`为`"[object Object]"`

**预期结果**
`dataset.item`为正常绑定对象

**实际结果**
`dataset.item`为`"[object, Object]"`

**系统信息:**
 - H5
 - uni-app@3.0.0-alpha-3030820220114003

**Comment by fxy060608** [comment]
https://ask.dcloud.net.cn/question/139181
https://github.com/dcloudio/uni-app/commit/86f6afb87e537316de021815883256d7f8b86b4f

**Comment by okxiaoliang4** [comment]
请问有发布的计划了吗？
@fxy060608

**Comment by fxy060608** [comment]
> 请问有发布的计划了吗？ @fxy060608

近期会发布 HBuilderX Alpha 3.4.0
