### ISSUE TITLE
【BUG】uniapp-cli Vue3 开启响应式语法糖 reactivityTransform 会报错没效果

### ISSUE THREAD

**Issue by 1014156094** [dcloudio/uni-app#3301]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
![image](https://user-images.githubusercontent.com/16074662/156338263-e2fc700b-ec83-4200-bdd1-8ad859ecaaf0.png)
![image](https://user-images.githubusercontent.com/16074662/156338322-3b82e16e-0525-4480-9ce9-1c01cc55be33.png)

**复现步骤**
[复现问题的步骤]
如图

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

```bash
import { $ref } from 'vue/macros'
const currentTab = $ref(0)
currentTab = 1
```

**实际结果**
[这里请贴上你的报错截图或文字]
报错并且没效果
![image](https://user-images.githubusercontent.com/16074662/156338263-e2fc700b-ec83-4200-bdd1-8ad859ecaaf0.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等] uni-app-cli
 - 操作系统 [如 iOS 12.1.2、Android 7.0] win11
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号] 无
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果] 如上图
 - 设备信息 [如 iPhone8 Plus] 全部

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
1. 配置错误，正确：
```js
import { defineConfig } from "vite";
import uni from "@dcloudio/vite-plugin-uni";
// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    uni({
      vueOptions: {
        reactivityTransform: true,
      },
    }),
  ],
});
```
2. 暂不支持`import { $ref } from 'vue/macros'`导入，可以直接使用 $ref

**Comment by 1014156094** [comment]
> 配置错误，正确：
> 
> ```js
> import { defineConfig } from "vite";
> import uni from "@dcloudio/vite-plugin-uni";
> // https://vitejs.dev/config/
> export default defineConfig({
>   plugins: [
>     uni({
>       vueOptions: {
>         reactivityTransform: true,
>       },
>     }),
>   ],
> });
> ```

好的谢谢，我看之前在官方文档搜索了没有说明这的配置，最好加上吧 <a href="https://uniapp.dcloud.io/tutorial/migration-to-vue3.html#vue2-项目迁移-vue3-必须适配的部分">https://uniapp.dcloud.io/tutorial/migration-to-vue3.html#vue2-项目迁移-vue3-必须适配的部分</a>
