### ISSUE TITLE
【vue3】组件生命周期函数获取 props 错误

### ISSUE THREAD

**Issue by sufuwang** [dcloudio/uni-app#3305]
**问题描述**
结构很简单，一个页面中有一个组件，在页面 onLoad 中修改 ref 的 value ，通过 props 中传递给组件，在组件 onMounted 中获取，这个 ref 的 value 可能为页面为 ref 的默认值，也有可能为页面 onLoad 中修改后的 value ，这种情况是正常的吗？

**复现步骤**
【测试工程】：https://github.com/sufuwang/uniapp_vite/tree/feature/echart
yarn dev 后多次刷新，可以看到组件 onMounted 中 ref 的 value 是存在两种情况的

**预期结果**
组件在首次加载的时候，就可以拿到页面 onLoad 中修改后的 value

**实际结果**
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/46395105/156768053-c397fbe2-f863-4d60-adac-d23bbbb3d4ba.png">
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/46395105/156768094-33c32a6f-c4cd-45c6-a688-92c5a76d4143.png">

**系统信息:**
 - 发行平台: 微信小程序
 - uni-app版本 3.0.0-alpha-3031120220216001

**Comment by fxy060608** [comment]
为了解决事件错乱，延迟，引发的执行时机不确定，待优化
https://github.com/dcloudio/uni-app/issues/3228

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3040020220301003

**Comment by sufuwang** [comment]
> onMounted 中错乱的问题已修复，cli更新至：3.0.0-alpha-3040020220301003

好的
