### ISSUE TITLE
vue3 中uniapp自定义生命周期无法指定target

### ISSUE THREAD

**Issue by PentaTea** [dcloudio/uni-app#3307]
**问题描述**

**复现步骤**
- 创建新页面A
- 页面中引用组件B
- 组件B的setup中填入`onPageScroll(console.log, getCurrentInstance().parent)`

**预期结果**
运行并滚动页面B,应输出`{scrollTop:...}`

**实际结果**
无反应

可行性测试:
- 组件B中输入
```js
  console.log(123, getCurrentInstance())
  onMounted(() => console.log(456, getCurrentInstance()), getCurrentInstance().parent)
```
可以正常输出
![image](https://user-images.githubusercontent.com/26431026/156911086-143c0d97-4827-4295-ad1d-db309b5cf12a.png)

**Comment by fxy060608** [comment]
不需要手动指定target，会自动绑定到页面实例
注意，因为onPageScroll影响性能，小程序平台，想在组件中监听页面onPageScroll，必须在页面中也注册onPageScroll

**Comment by PentaTea** [comment]
感谢解答
