### ISSUE TITLE
HbuilderX 1.9.3云打包后uni.getLocation定位接口失效

### ISSUE THREAD

**Issue by qingmumao** [dcloudio/uni-app#331]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
HbuilderX 1.9.3云打包后uni.getLocation定位接口失效

**预期结果**
正常定位

**实际结果**
无法定位

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
安卓还是iOS？之前是否正常？

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
