### ISSUE TITLE
[获取文件失败] 以下文件已被配置忽略打包上传，模拟器无法获取

### ISSUE THREAD

**Issue by yxw007** [dcloudio/uni-app#3312]
**问题描述**
采用vue3 setup ， 引入vue组件，打包成微信小程序报错：
![image](https://user-images.githubusercontent.com/9338717/156994468-49f56705-30d8-4606-9637-9509d8c9cbed.png)

**复现步骤**
```
<script setup>
import MiddleBar from "./MiddleBar.vue";
</script>

<template>
<MiddleBar></MiddleBar>
</template>
```

**预期结果**
需要能控制不要忽略

**实际结果**
![image](https://user-images.githubusercontent.com/9338717/156994468-49f56705-30d8-4606-9637-9509d8c9cbed.png)

**系统信息:**
 - 发行平台: 微信小程序
 - uni-app版本 2.0.1-alpha-34020220304001

**补充信息**
应该是打包环境出问题了

**Comment by fxy060608** [comment]
排查自己的配置，编译器不会配置这些东西

**Comment by yxw007** [comment]
> 编译器不会主动配置这些东西

不用setup语法糖无问题，改成setup 模式就出问题了，其他完全一样。

project.config.json 
```
{
  "description": "项目配置文件。",
  "packOptions": {
    "ignore": []
  },
  "setting": {
    "urlCheck": false,
    "es6": false,
    "enhance": true,
    "postcss": false,
    "preloadBackgroundData": false,
    "minified": true,
    "newFeature": false,
    "coverView": true,
    "nodeModules": false,
    "autoAudits": false,
    "showShadowRootInWxmlPanel": true,
    "scopeDataCheck": false,
    "uglifyFileName": false,
    "checkInvalidKey": true,
    "checkSiteMap": true,
    "uploadWithSourceMap": true,
    "compileHotReLoad": false,
    "lazyloadPlaceholderEnable": false,
    "useMultiFrameRuntime": true,
    "useApiHook": true,
    "useApiHostProcess": true,
    "babelSetting": {
      "ignore": [],
      "disablePlugins": [],
      "outputPath": ""
    },
    "useIsolateContext": true,
    "userConfirmedBundleSwitch": false,
    "packNpmManually": false,
    "packNpmRelationList": [],
    "minifyWXSS": true,
    "disableUseStrict": false,
    "showES6CompileOption": false,
    "useCompilerPlugins": false,
    "ignoreUploadUnusedFiles": true,
    "minifyWXML": true
  },
  "compileType": "miniprogram",
  "libVersion": "",
  "appid": "wx69c7fe106abae672",
  "projectname": "纸片屋",
  "condition": {
    "search": {
      "list": []
    },
    "conversation": {
      "list": []
    },
    "game": {
      "list": []
    },
    "miniprogram": {
      "list": [
        {
          "name": "选服页面",
          "query": "",
          "id": 0,
          "pathName": "pages/page-test/page-server"
        }
      ]
    }
  }
}
```
帮忙看下编译生成的配置是否有问题？

**Comment by fxy060608** [comment]
> > 编译器不会主动配置这些东西
> 
> 不用setup语法糖无问题，改成setup 模式就出问题了，其他完全一样。
> 
> project.config.json
> 
> ```
> {
>   "description": "项目配置文件。",
>   "packOptions": {
>     "ignore": []
>   },
>   "setting": {
>     "urlCheck": false,
>     "es6": false,
>     "enhance": true,
>     "postcss": false,
>     "preloadBackgroundData": false,
>     "minified": true,
>     "newFeature": false,
>     "coverView": true,
>     "nodeModules": false,
>     "autoAudits": false,
>     "showShadowRootInWxmlPanel": true,
>     "scopeDataCheck": false,
>     "uglifyFileName": false,
>     "checkInvalidKey": true,
>     "checkSiteMap": true,
>     "uploadWithSourceMap": true,
>     "compileHotReLoad": false,
>     "lazyloadPlaceholderEnable": false,
>     "useMultiFrameRuntime": true,
>     "useApiHook": true,
>     "useApiHostProcess": true,
>     "babelSetting": {
>       "ignore": [],
>       "disablePlugins": [],
>       "outputPath": ""
>     },
>     "useIsolateContext": true,
>     "userConfirmedBundleSwitch": false,
>     "packNpmManually": false,
>     "packNpmRelationList": [],
>     "minifyWXSS": true,
>     "disableUseStrict": false,
>     "showES6CompileOption": false,
>     "useCompilerPlugins": false,
>     "ignoreUploadUnusedFiles": true,
>     "minifyWXML": true
>   },
>   "compileType": "miniprogram",
>   "libVersion": "",
>   "appid": "wx69c7fe106abae672",
>   "projectname": "纸片屋",
>   "condition": {
>     "search": {
>       "list": []
>     },
>     "conversation": {
>       "list": []
>     },
>     "game": {
>       "list": []
>     },
>     "miniprogram": {
>       "list": [
>         {
>           "name": "选服页面",
>           "query": "",
>           "id": 0,
>           "pathName": "pages/page-test/page-server"
>         }
>       ]
>     }
>   }
> }
> ```
> 
> 帮忙看下编译生成的配置是否有问题？

发个测试工程

**Comment by yxw007** [comment]
> 
弄了一个测试工程后，打包运行是ok的。然后对比package.json 依赖版本，发现问题依赖的版本不对了，请问是否有uniapp  2.x 升级到uniapp 3.x 的升级指南？
![image](https://user-images.githubusercontent.com/9338717/157003337-1f97f92e-080d-4d81-8767-cce34a08f845.png)

**Comment by yxw007** [comment]
> > > 编译器不会主动配置这些东西
> > 
> > 
> > 不用setup语法糖无问题，改成setup 模式就出问题了，其他完全一样。
> > project.config.json
> > ```
> > {
> >   "description": "项目配置文件。",
> >   "packOptions": {
> >     "ignore": []
> >   },
> >   "setting": {
> >     "urlCheck": false,
> >     "es6": false,
> >     "enhance": true,
> >     "postcss": false,
> >     "preloadBackgroundData": false,
> >     "minified": true,
> >     "newFeature": false,
> >     "coverView": true,
> >     "nodeModules": false,
> >     "autoAudits": false,
> >     "showShadowRootInWxmlPanel": true,
> >     "scopeDataCheck": false,
> >     "uglifyFileName": false,
> >     "checkInvalidKey": true,
> >     "checkSiteMap": true,
> >     "uploadWithSourceMap": true,
> >     "compileHotReLoad": false,
> >     "lazyloadPlaceholderEnable": false,
> >     "useMultiFrameRuntime": true,
> >     "useApiHook": true,
> >     "useApiHostProcess": true,
> >     "babelSetting": {
> >       "ignore": [],
> >       "disablePlugins": [],
> >       "outputPath": ""
> >     },
> >     "useIsolateContext": true,
> >     "userConfirmedBundleSwitch": false,
> >     "packNpmManually": false,
> >     "packNpmRelationList": [],
> >     "minifyWXSS": true,
> >     "disableUseStrict": false,
> >     "showES6CompileOption": false,
> >     "useCompilerPlugins": false,
> >     "ignoreUploadUnusedFiles": true,
> >     "minifyWXML": true
> >   },
> >   "compileType": "miniprogram",
> >   "libVersion": "",
> >   "appid": "wx69c7fe106abae672",
> >   "projectname": "纸片屋",
> >   "condition": {
> >     "search": {
> >       "list": []
> >     },
> >     "conversation": {
> >       "list": []
> >     },
> >     "game": {
> >       "list": []
> >     },
> >     "miniprogram": {
> >       "list": [
> >         {
> >           "name": "选服页面",
> >           "query": "",
> >           "id": 0,
> >           "pathName": "pages/page-test/page-server"
> >         }
> >       ]
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 帮忙看下编译生成的配置是否有问题？
> 
> 发个测试工程

弄了一个测试工程后，打包运行是ok的。然后对比package.json 依赖版本，发现问题依赖的版本不对了，请问是否有uniapp 2.x 升级到uniapp 3.x 的升级指南？ ![image](https://user-images.githubusercontent.com/9338717/157003337-1f97f92e-080d-4d81-8767-cce34a08f845.png)

**Comment by fxy060608** [comment]
> > > > 编译器不会主动配置这些东西
> > > 
> > > 
> > > 不用setup语法糖无问题，改成setup 模式就出问题了，其他完全一样。
> > > project.config.json
> > > ```
> > > {
> > >   "description": "项目配置文件。",
> > >   "packOptions": {
> > >     "ignore": []
> > >   },
> > >   "setting": {
> > >     "urlCheck": false,
> > >     "es6": false,
> > >     "enhance": true,
> > >     "postcss": false,
> > >     "preloadBackgroundData": false,
> > >     "minified": true,
> > >     "newFeature": false,
> > >     "coverView": true,
> > >     "nodeModules": false,
> > >     "autoAudits": false,
> > >     "showShadowRootInWxmlPanel": true,
> > >     "scopeDataCheck": false,
> > >     "uglifyFileName": false,
> > >     "checkInvalidKey": true,
> > >     "checkSiteMap": true,
> > >     "uploadWithSourceMap": true,
> > >     "compileHotReLoad": false,
> > >     "lazyloadPlaceholderEnable": false,
> > >     "useMultiFrameRuntime": true,
> > >     "useApiHook": true,
> > >     "useApiHostProcess": true,
> > >     "babelSetting": {
> > >       "ignore": [],
> > >       "disablePlugins": [],
> > >       "outputPath": ""
> > >     },
> > >     "useIsolateContext": true,
> > >     "userConfirmedBundleSwitch": false,
> > >     "packNpmManually": false,
> > >     "packNpmRelationList": [],
> > >     "minifyWXSS": true,
> > >     "disableUseStrict": false,
> > >     "showES6CompileOption": false,
> > >     "useCompilerPlugins": false,
> > >     "ignoreUploadUnusedFiles": true,
> > >     "minifyWXML": true
> > >   },
> > >   "compileType": "miniprogram",
> > >   "libVersion": "",
> > >   "appid": "wx69c7fe106abae672",
> > >   "projectname": "纸片屋",
> > >   "condition": {
> > >     "search": {
> > >       "list": []
> > >     },
> > >     "conversation": {
> > >       "list": []
> > >     },
> > >     "game": {
> > >       "list": []
> > >     },
> > >     "miniprogram": {
> > >       "list": [
> > >         {
> > >           "name": "选服页面",
> > >           "query": "",
> > >           "id": 0,
> > >           "pathName": "pages/page-test/page-server"
> > >         }
> > >       ]
> > >     }
> > >   }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 帮忙看下编译生成的配置是否有问题？
> > 
> > 
> > 发个测试工程
> 
> 弄了一个测试工程后，打包运行是ok的。然后对比package.json 依赖版本，发现问题依赖的版本不对了，请问是否有uniapp 2.x 升级到uniapp 3.x 的升级指南？ ![image](https://user-images.githubusercontent.com/9338717/157003337-1f97f92e-080d-4d81-8767-cce34a08f845.png)

2和3差异很大，建议创建一个新的3工程，然后把2的内容迁移过去

**Comment by yxw007** [comment]
> 

好吧，看来只能这么搞了，感谢你的回复~
