### ISSUE TITLE
小程序插件开发支付宝端好像还有点问题

### ISSUE THREAD

**Issue by Yaob1990** [dcloudio/uni-app#3314]
支付宝好像还不行
1. 导致编译失败: main.js 中这句导致小程序 ide 编译失败
module.exports = wx.__webpack_require_UNI_MP_PLUGIN__('0'); 

3. main.js 文件中的方法微信可以调用，支付宝端调用不了。

**Comment by StrivingRabbit** [comment]
以合并pr #3323
