### ISSUE TITLE
vue3-ts项目在hbuilderx中无法运行

### ISSUE THREAD

**Issue by lifuzhao100** [dcloudio/uni-app#3315]
**问题描述**
vue3-ts项目在hbuilderx中无法运行

**复现步骤**
[复现问题的步骤]
1.  npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project
2. 进入项目根目录 yarn install
3. hbuilderx -> 运行 -> 内置浏览器运行

[或者可以直接贴源代码]

**预期结果**
成功运行

**实际结果**
<img width="1048" alt="image" src="https://user-images.githubusercontent.com/16594057/157157132-de0a16fc-93e3-4cec-96da-ec27d013d39a.png">

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 macos Monterey 12.2.1
 - HBuilderX版本 HBuilderX@3.3.11.20220209
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
   - vue --version  
   - 4.5.15
   - 
<img width="588" alt="image" src="https://user-images.githubusercontent.com/16594057/157158642-511ff94d-7f4f-40ba-8aae-387687de398a.png">

 - 设备信息 macos Monterey 12.2.1

**补充信息**
提供esbuild的相关issue，
https://github.com/evanw/esbuild/issues/1646
，但目测跟esbuild无关，因为直接执行 npm run dev:h5是可以正常使用的；

**Comment by fxy060608** [comment]
目前HBuilderX运行cli项目，使用的node是HBuilderX自带的，跟你自己安装的依赖不匹配，可以先手动node_modules中的`esbuild-darwin-arm64`调整为`esbuild-darwin-64`

**Comment by lifuzhao100** [comment]
> 目前HBuilderX运行cli项目，使用的node是HBuilderX自带的，跟你自己安装的依赖不匹配，可以先手动node_modules中的`esbuild-darwin-arm64`调整为`esbuild-darwin-64`

如果不自己安装依赖，hbuilderx有什么方法使用内置的node安装依赖吗？

**Comment by fxy060608** [comment]
> > 目前HBuilderX运行cli项目，使用的node是HBuilderX自带的，跟你自己安装的依赖不匹配，可以先手动node_modules中的`esbuild-darwin-arm64`调整为`esbuild-darwin-64`
> 
> 如果不自己安装依赖，hbuilderx有什么方法使用内置的node安装依赖吗？

使用HBuilderX自带的node和npm来安装依赖，如：
`/Applications/HBuilderX-Alpha.app/Contents/HBuilderX/plugins/node/node /Applications/HBuilderX-Alpha.app/Contents/HBuilderX/plugins/npm/node_modules/npm/bin/npm-cli.js install
`

**Comment by lifuzhao100** [comment]
> > > 目前HBuilderX运行cli项目，使用的node是HBuilderX自带的，跟你自己安装的依赖不匹配，可以先手动node_modules中的`esbuild-darwin-arm64`调整为`esbuild-darwin-64`
> > 
> > 
> > 如果不自己安装依赖，hbuilderx有什么方法使用内置的node安装依赖吗？
> 
> 使用HBuilderX自带的node和npm来安装依赖，如： `/Applications/HBuilderX-Alpha.app/Contents/HBuilderX/plugins/node/node /Applications/HBuilderX-Alpha.app/Contents/HBuilderX/plugins/npm/node_modules/npm/bin/npm-cli.js install `

Get！感谢大佬@[fxy060608](https://github.com/fxy060608)
