### ISSUE TITLE
uniapp 编译vantui小程序 js文件内容缺失问题

### ISSUE THREAD

**Issue by RiuHDuo** [dcloudio/uni-app#3317]
**问题描述**
使用npm run dev:mp-weixin编译小程序,
首次运行正常之后修改，任意文件后触发自动编译后，发现vantui里的一部分文件内容缺失。如下图

**复现步骤**
[复现问题的步骤]
1.  启动 npm run dev:mp-weixin
2. 点击  command + save触发自动编译
3. 查看

[或者可以直接贴源代码]

**预期结果**
wxcomponents里的文件原样生成

**实际结果**
部分js内容缺失
![image](https://user-images.githubusercontent.com/830134/157185963-fc5e27f3-43df-44c7-a6d7-c1f37df32401.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 macos
 - uni-app版本: "@dcloudio/uni-app": "^3.0.0-alpha-3031120220216001",

**补充信息**

**Comment by fxy060608** [comment]
是不是在非wxcomponents目录引入了该文件

**Comment by RiuHDuo** [comment]
> 是不是在非wxcomponents目录引入了该文件 可以参考：#329
上图左侧可以看出是是在wxcomponents目录下，而且 npm run dev:mp-weixin是正常的，要修改并保存任意文件触发自动编译后才会出现

**Comment by fxy060608** [comment]
> > 是不是在非wxcomponents目录引入了该文件 可以参考：#329
> 
> 上图左侧可以看出是是在wxcomponents目录下，而且 npm run dev:mp-weixin是正常的，要修改并保存任意文件触发自动编译后才会出现

看关联问题，通常这种情况是因为你在非wxcomponents里边引用了wxcomponents里的内容，导致wxcompoennts被编译，覆盖了原始的validator.js，关联问题里边有一个vite.config.js的配置回复，自己用一下就知道了

**Comment by RiuHDuo** [comment]
解决了 谢谢
