### ISSUE TITLE
uniapp 编译报错

### ISSUE THREAD

**Issue by wolfewf** [dcloudio/uni-app#3319]
[HBuilder] 16:30:06.560 项目 'youlai-mall-weapp' 开始发布微信小程序...
[HBuilder] 16:30:06.568 项目 'youlai-mall-weapp' 开始编译...
[HBuilder] 16:30:07.512 正在编译中...
[HBuilder] 16:30:07.943 vite v2.7.10 building for production...
[HBuilder] 16:30:10.446 [vite:css] Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
[HBuilder] 16:30:10.447 59 |    color: #f7d680;
[HBuilder] 16:30:10.452 60 |    height: 240upx;
[HBuilder] 16:30:10.453 61 |    background: linear-gradient(left, rgba(0, 0, 0, 0.7), rgba(0, 0, 0, 0.8));
[HBuilder] 16:30:10.458    |     ^
[HBuilder] 16:30:10.458 62 |    border-radius: 16upx 16upx 0 0;
[HBuilder] 16:30:10.462 63 |    overflow: hidden;
[HBuilder] 16:30:10.463 [vite:css] Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
[HBuilder] 16:30:10.469 83 |    color: #36343c;
[HBuilder] 16:30:10.469 84 |    border-radius: 20px;
[HBuilder] 16:30:10.474 85 |    background: linear-gradient(left, #f9e6af, #ffd465);
[HBuilder] 16:30:10.474    |     ^
[HBuilder] 16:30:10.479 86 |    z-index: 1;
[HBuilder] 16:30:10.485 87 |  }
[HBuilder] 16:30:10.606 [vite:css] Gradient has outdated direction syntax. New syntax is like `to left` instead of `right`.
[HBuilder] 16:30:10.613 91 |    align-items: center;
[HBuilder] 16:30:10.613 92 |    color: #606266;
[HBuilder] 16:30:10.618 93 |    background: linear-gradient(left, #fdf5f6, #fbebf6);
[HBuilder] 16:30:10.618    |     ^
[HBuilder] 16:30:10.622 94 |    padding: 12upx 30upx;
[HBuilder] 16:30:10.626 95 |  }
[HBuilder] 16:30:10.867 [plugin:vite:css] Undefined variable.
[HBuilder] 16:30:10.871    ╷
[HBuilder] 16:30:10.873 62 │             margin-left:$uni-spacing-row-sm;
[HBuilder] 16:30:10.892    │                         ^^^^^^^^^^^^^^^^^^^
[HBuilder] 16:30:10.893    ╵
[HBuilder] 16:30:10.901   /Users/wolfe/faying/mall/youlai-mall-weapp/components/mix-list-cell.vue 62:16  root stylesheet
[HBuilder] 16:30:10.901 at components/mix-list-cell.vue:1:0
[HBuilder] 16:30:10.920   Error: Undefined variable.
[HBuilder] 16:30:10.921      ╷
[HBuilder] 16:30:10.926   62 │             margin-left:$uni-spacing-row-sm;
[HBuilder] 16:30:10.930      │                         ^^^^^^^^^^^^^^^^^^^
[HBuilder] 16:30:10.935      ╵
[HBuilder] 16:30:10.935     /Users/wolfe/faying/mall/youlai-mall-weapp/components/mix-list-cell.vue 62:16  root stylesheet
[HBuilder] 16:30:10.940 error during build:
[HBuilder] 16:30:10.941 Error: Undefined variable.
[HBuilder] 16:30:10.945    ╷
[HBuilder] 16:30:10.950 62 │             margin-left:$uni-spacing-row-sm;
[HBuilder] 16:30:10.950    │                         ^^^^^^^^^^^^^^^^^^^
[HBuilder] 16:30:10.955    ╵
[HBuilder] 16:30:10.959   /Users/wolfe/faying/mall/youlai-mall-weapp/components/mix-list-cell.vue 62:16  root stylesheet
[HBuilder] 16:30:10.963     at Object._newRenderError (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/compile-dart-sass/node_modules/sass/sass.dart.js:16144:19)
[HBuilder] 16:30:10.963     at Object._wrapException (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/compile-dart-sass/node_modules/sass/sass.dart.js:15964:16)
[HBuilder] 16:30:10.969     at render_closure1.call$2 (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/compile-dart-sass/node_modules/sass/sass.dart.js:82305:21)
[HBuilder] 16:30:10.969     at _RootZone.runBinary$3$3 (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/compile-dart-sass/node_modules/sass/sass.dart.js:28284:18)
[HBuilder] 16:30:10.974     at _FutureListener.handleError$1 (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/compile-dart-sass/node_modules/sass/sass.dart.js:26806:21)
[HBuilder] 16:30:10.980     at _Future__propagateToListeners_handleError.call$0 (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/compile-dart-sass/node_modules/sass/sass.dart.js:27113:49)
[HBuilder] 16:30:10.980     at Object._Future__propagateToListeners (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/compile-dart-sass/node_modules/sass/sass.dart.js:12137:77)
[HBuilder] 16:30:10.986     at _Future._completeError$2 (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/compile-dart-sass/node_modules/sass/sass.dart.js:26959:9)
[HBuilder] 16:30:10.987     at _AsyncAwaitCompleter.completeError$2 (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/compile-dart-sass/node_modules/sass/sass.dart.js:26618:12)
[HBuilder] 16:30:10.992     at Object._asyncRethrow (/Applications/HBuilderX.app/Contents/HBuilderX/plugins/compile-dart-sass/node_modules/sass/sass.dart.js:11940:17)
[HBuilder] 16:30:10.998 项目 'youlai-mall-weapp' 发布微信小程序失败.

**Comment by fxy060608** [comment]
错误提示的都是 scss 问题
1. 按错误提示，把旧语法修改为新语法
2. scss变量不存在的问题，排查项目根目录是否有uni.scss，相关变量是否在里边有定义
