### ISSUE TITLE
[ WXML 文件编译错误]  unexpected character

### ISSUE THREAD

**Issue by zhuscat** [dcloudio/uni-app#3320]
**问题描述**

源代码中 style 属性是换行的，如：

```html
<view style="
  width: 100px;
  height: 100px;
" />
```

但是编译出来的 WXML 之后还是换行的：

导致出现问题：

```
[ WXML 文件编译错误]
 unexpected character `
`
```

**预期结果**
生成的 WXML 的 style 属性没有换行符

**实际结果**

有换行符

**系统信息:**
 - uni-app版本：3.0.0-alpha-3031220220222002
 - 设备信息：微信开发者工具

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
HBuilderX alpha 3.4.2 已修复
