### ISSUE TITLE
使用vite-plugin-html编译时ERROR

### ISSUE THREAD

**Issue by leeseett** [dcloudio/uni-app#3321]
**问题描述**
vite.config.js 无法使用vite-plugin-html，只要引用这个插件就报错

**复现步骤**
[复现问题的步骤]
1. yarn add vite-plugin-html -D
2. 修改vite.config.js文件，就只引用 import { createHtmlPlugin } from 'vite-plugin-html'
3.yarn dev:mp-weixin
![image](https://user-images.githubusercontent.com/28776735/157219664-0dfd7a08-b77b-4b6d-bb52-a79da616f7e8.png)

**预期结果**
控制台不报错

**实际结果**
![Snipaste_2022-03-08_18-35-03](https://user-images.githubusercontent.com/28776735/157219578-e15f98e8-758f-437a-a203-16c7dd4a7805.png)

ERROR  (node:30592) [DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at D:\work\mdmf\jkmf-stand-promotions\node_modules\vuex\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 win11
 - uni-app版本 3.0.0-alpha-3040120220307001

**Comment by fxy060608** [comment]
1. 你这个插件小程序平台是不需要的吧？
2. 错误跟这个插件应该没关系，是因为 vuex 在高版本 node 上的兼容问题
参考：
https://github.com/vuejs/vuex/issues/2047
https://github.com/vuejs/vuex/pull/2048

**Comment by leeseett** [comment]
> 1. 你这个插件小程序平台是不需要的吧？
> 2. 错误跟这个插件应该没关系，是因为 vuex 在高版本 node 上的兼容问题
>    参考：
>    [Deprecation Warning: Use of deprecated folder mapping "./" in the "exports" field module vuejs/vuex#2047](https://github.com/vuejs/vuex/issues/2047)
>    [Fix deprecated warning in package.json export module (fix #2047) vuejs/vuex#2048](https://github.com/vuejs/vuex/pull/2048)
小程序用不到，H5有用到（就是换个默认的标题）。虽然报ERROR，但是还是能编译通过。我现在不用它了。直接用fs 去修改manifest.json 里边的name字段

**Comment by leeseett** [comment]
> 1. 你这个插件小程序平台是不需要的吧？
> 2. 错误跟这个插件应该没关系，是因为 vuex 在高版本 node 上的兼容问题
>    参考：
>    [Deprecation Warning: Use of deprecated folder mapping "./" in the "exports" field module vuejs/vuex#2047](https://github.com/vuejs/vuex/issues/2047)
>    [Fix deprecated warning in package.json export module (fix #2047) vuejs/vuex#2048](https://github.com/vuejs/vuex/pull/2048)
小程序用不到，H5有用到（就是换个默认的标题）。虽然报ERROR，但是还是能编译通过。我现在不用它了。直接用fs 去修改manifest.json 里边的name字段
