### ISSUE TITLE
v-slot作用域插槽的一些问题

### ISSUE THREAD

**Issue by phy-lei** [dcloudio/uni-app#3325]
**问题描述**
在父组件中，使用父组件的动态值渲染给slot-template，会报undefined。

**复现步骤**
`
<dragList :itemHeight="120" :list="reportTypeList">

    <template v-slot="{ item }">
      <view class="list">
        <name>{{ item.name }}</name>
        <i
          :style="{
            backgroundImage: `url(${imgStaticUrl}/img/ProblemReporting/ProblemReporting.png)`,
          }"
        ></i>
        <text :data-i="world">{{ world }}</text>  // 这里取得是父组件的值，会有问题，undefined
      </view>
    </template>
  </dragList>
`

**预期结果**
能拿到父组件的数据，并渲染

**实际结果**
拿不到值

**系统信息:**
微信小程序

**补充信息**
uniapp版本：2.0.0-alpha。也配置了 "scopedSlotsCompiler": "legacy"

**Comment by gemone** [comment]
`uniapp`: `^3.0.0-alpha-3031320220314001` 同样。

微信小程序报: 

```
TypeError: Cannot read property 'fn' of undefined
```

编译后的代码如下: 

```js
// ... 
   return (_ctx, _cache) => {
      return common_vendor.e({
        a: __props.title
      }, __props.title ? {
        b: common_vendor.p({
          type: "h4",
          title: __props.title
        })
      } : {}, {
        c: common_vendor.f(__props.menus, (menu, index, i0) => {
          return {
            a: common_vendor.t(menu.title),
            b: common_vendor.n(menu.class),
            c: common_vendor.o(menu.tabAction),
            d: common_vendor.d(`menu-${menu.key}`),
// 这里出错
            e: common_vendor.r(menu.d, {
              menu
            }, i0),
            f: `${common_vendor.unref(key)}-${index}`
          };
        }),
        d: common_vendor.sr(popupMenu, "32aef07d-0", {
          "k": "popupMenu"
        }),
        e: common_vendor.p({
          type: "bottom",
          ["background-color"]: "#ffffff"
        })
      });
    };
// ...
```

`r` 函数为 `undefined` ?
