### ISSUE TITLE
关于api Promise封装返回数据格式的疑问

### ISSUE THREAD

**Issue by nieheyong** [dcloudio/uni-app#333]
[官网](https://uniapp.dcloud.io/api/README?id=promise-%E5%B0%81%E8%A3%85)描述: 
> uni-app 对部分 API 进行了 Promise 封装，返回数据的第一个参数是错误对象，第二个参数是返回数据

不知当前api这样设计的原因是什么？
按照js传统来说，Promise成功应该直接resolve结果，错误reject。而不是把错误和结果都resolve成一个数组返回。这样在链式调用或者async function 中也能方便的进行错误处理。

**Comment by xiaoyucoding** [comment]
使用 async 和 await 语法，需要捕获错误信息时，开发者无需自己再写一层 try catch，更加方便使用。

**Comment by nieheyong** [comment]
@xiaoyucoding 
> 使用 async 和 await 语法，需要捕获错误信息时，开发者无需自己再写一层 try catch，更加方便使用。

这样明显增加了复杂度,每个操作都要判断err是不是存在，不存在才能使用result。例如以下代码：
```js

async function test2() {
  let [err1, res1] = await readFile("file1");
  if (!err1) {
    let [err2, res2] = await readFile("file2");
    if (!err2) {
      let [err3, res3] = await readFile("file3");
      if (!err3) {
        return res1 + res2 + res3;
      } else {
        console.log(err3);
      }
    } else {
      console.log(err2);
    }
  } else {
    console.log(err1);
  }
}

async function test1() {
  try {
    let res1 = await readFile("file1");
    let res2 = await readFile("file2");
    let res3 = await readFile("file3");
    return res1 + res2 + res3;
  } catch (e) {
    console.log("错误");
  }
}

```

**Comment by xiaoyucoding** [comment]
> @xiaoyucoding
> 
> > 使用 async 和 await 语法，需要捕获错误信息时，开发者无需自己再写一层 try catch，更加方便使用。
> 
> 这样明显增加了复杂度,每个操作都要判断err是不是存在，不存在才能使用result。例如以下代码：
> 
> ```js
> // 对于uni-app 形式的 Promise 使用
> async function test1() {
>   let [err1, res1] = await readFile("file1");
>   if (!err1) {
>     let [err2, res2] = await readFile("file2");
>     if (!err2) {
>       let [err3, res3] = await readFile("file3");
>       if (!err3) {
>         return res1 + res2 + res3;
>       } else {
>         console.log(err3);
>       }
>     } else {
>       console.log(err2);
>     }
>   } else {
>     console.log(err1);
>   }
> }
> 
> // 常规Promise使用
> async function test2() {
>   try {
>     let res1 = await readFile("file1");
>     let res2 = await readFile("file2");
>     let res3 = await readFile("file3");
>     return res1 + res2 + res3;
>   } catch (e) {
>     console.log("错误");
>   }
> }
> ```

说的是需要捕获错误信息或者处理错误信息的情况，正常调用不处理的话，不需要这样频繁判定。

**Comment by xiaoyucoding** [comment]
> @xiaoyucoding
> 
> > 使用 async 和 await 语法，需要捕获错误信息时，开发者无需自己再写一层 try catch，更加方便使用。
> 
> 这样明显增加了复杂度,每个操作都要判断err是不是存在，不存在才能使用result。例如以下代码：
> 
> ```js
> // 对于uni-app 形式的 Promise 使用
> async function test1() {
>   let [err1, res1] = await readFile("file1");
>   if (!err1) {
>     let [err2, res2] = await readFile("file2");
>     if (!err2) {
>       let [err3, res3] = await readFile("file3");
>       if (!err3) {
>         return res1 + res2 + res3;
>       } else {
>         console.log(err3);
>       }
>     } else {
>       console.log(err2);
>     }
>   } else {
>     console.log(err1);
>   }
> }
> 
> // 常规Promise使用
> async function test2() {
>   try {
>     let res1 = await readFile("file1");
>     let res2 = await readFile("file2");
>     let res3 = await readFile("file3");
>     return res1 + res2 + res3;
>   } catch (e) {
>     console.log("错误");
>   }
> }
> ```

各有各的好处吧，常规的可以一次性捕获错误，但是还需要判定错误信息的内容来处理不同的错误信息。
uni 这样直接返回的话，直接就知道错误信息的来源，不需要再次判定。

感谢你的积极反馈与讨论。

**Comment by fxy060608** [comment]
> @xiaoyucoding
> 
> > 使用 async 和 await 语法，需要捕获错误信息时，开发者无需自己再写一层 try catch，更加方便使用。
> 
> 这样明显增加了复杂度,每个操作都要判断err是不是存在，不存在才能使用result。例如以下代码：
> 
> ```js
> // 对于uni-app 形式的 Promise 使用
> async function test1() {
>   let [err1, res1] = await readFile("file1");
>   if (!err1) {
>     let [err2, res2] = await readFile("file2");
>     if (!err2) {
>       let [err3, res3] = await readFile("file3");
>       if (!err3) {
>         return res1 + res2 + res3;
>       } else {
>         console.log(err3);
>       }
>     } else {
>       console.log(err2);
>     }
>   } else {
>     console.log(err1);
>   }
> }
> 
> // 常规Promise使用
> async function test2() {
>   try {
>     let res1 = await readFile("file1");
>     let res2 = await readFile("file2");
>     let res3 = await readFile("file3");
>     return res1 + res2 + res3;
>   } catch (e) {
>     console.log("错误");
>   }
> }
> ```

所谓的增加复杂度，是因为你要判断 err，事实上并没有让你非要判断 err，相反，当你的业务必须处理 err 时，用常规 await ，必须使用 try catch 才可以处理 err，你可以比较下 try catch 和现在的 err 代码对比

**Comment by nieheyong** [comment]
@fxy060608 
> 所谓的增加复杂度，是因为你要判断 err，事实上并没有让你非要判断 err

只有判断err为空，才能确定data值是正确可用的

>用常规 await ，必须使用 try catch 才可以处理 err，你可以比较下 try catch 和现在的 err 代码对比

 try catch很好用

>判断有 err，完全可以直接 return，使得代码扁平

这样的话每一次调用promise API都要判断有 err 并且return，多了会显得很乱。其次直接return实际上没有处理错误，得通过返回值来判断函数是执行成功返回还是出错返回。

**Comment by nieheyong** [comment]
@xiaoyucoding 
> 各有各的好处吧，常规的可以一次性捕获错误，但是还需要判定错误信息的内容来处理不同的错误信息。 uni 这样直接返回的话，直接就知道错误信息的来源，不需要再次判定

很多时候并不需要判定详细错误信息，例如直接在catch里面弹窗提示文件读取错误就可以了

**Comment by fxy060608** [comment]
更多情况应该是需要处理每一处的 err 来做不同错误处理吧，
如果是业务需求允许简化为直接 try catch 多个 await 的情况，确实使用 try catch 更简单些
后续可以考虑给一个开关，来返回标准结果
`
async function test1() {
    const [err1, res1] = await readFile("file1");
    if (err1) {
        return console.log(err1)
    }
    const [err2, res2] = await readFile("file2");
    if (err2) {
        return console.log(err2)
    }
    const [err3, res3] = await readFile("file3");
    if (err3) {
        return console.log(err3)
    }
    return res1 + res2 + res3
}
`

**Comment by jamieYou** [comment]
曾经回调地狱最大问题是嵌套多层大括号和每一个 error 都得手动判断一遍。
Promise 和 async 都解决了这个问题，实在想不通为什么这边的 api 反而倒退了

**Comment by 467057463** [comment]
同感，希望官方可以按正常的代码风格设计，这样确实用起来不方便

**Comment by SunXiaoguo** [comment]
我估计纯粹是开发人员的个人喜好，用惯了error，不想切换到新模式而已。

**Comment by Yechuanjie** [comment]
> 使用 async 和 await 语法，需要捕获错误信息时，开发者无需自己再写一层 try catch，更加方便使用。

第一次用 `uni-app`，确实没看懂这 `API` Promise化的设计。。在绝大部分情况下，我并不会去使用 `err`，因为程序绝大部分时候是正常进行的。假设调用一个简单的API，比如 `uni.getSetting()` ，我并不需要也不关心 `err`  是什么，然而我需要去写额外的 `err` 变量。

```js
uni.getSetting().then((result) => {
    const [err, data] = result
    console.info(data)
});
```

这样的 `API Promise` 化设计，多数情况看来，确实是没有必要的。既然使用了 `Promise`，那用户就希望在 `then` 函数中获取API响应的结果，而不希望有额外的东西。

而对于 `request` **api** 来说，用户本来就需要去捕捉错误，这可以通过二次封装 `request` 来解决。个人感觉，这不是一个框架应该做的事情。

**Comment by zhetengbiji** [comment]
有调整计划，不过需要考虑旧版用法的兼容问题

**Comment by DarrenHou1993** [comment]
我刚来玩uni-app, 就看到promise封的很奇怪。 本来就是倒退了 还死犟死犟的 哈哈。搞得我还得二次封一下。

**Comment by zhetengbiji** [comment]
> 我刚来玩uni-app, 就看到promise封的很奇怪。 本来就是倒退了 还死犟死犟的 哈哈。搞得我还得二次封一下。

不敢，不敢

**Comment by StrivingRabbit** [comment]
https://gitee.com/dcloud/uni-app/issues/I40O3B，暂时可以这样处理一下

**Comment by arbing** [comment]
我现在是这么处理的，每个`await uni`调用后面加`then(resolveUni)`

TS 类型用 #1770 提到方法打补丁。

<pre>
<code>
/**
 *
 * 统一处理 Promise 方式调用 uni API 的返回值
 *
 * **示例代码**
 *
 * ```js
const userInfo = await uni.getUserInfo({}).then(resolveUni)
 ```
 *
 * **等同于**
 * ```js
const [err, userInfo] = await uni.getUserInfo({})
if (err && err.errMsg) {
    console.error(err.errMsg)
    throw new Error(err.errMsg)
}
 ```
 * @param arr Promise 方式调用 uni API 的返回值
 * @returns
 */
export function resolveUni<S, F>([error, res]: [F, S]) {
  const err = error as any
  if (err && err.errMsg) {
    const { errMsg, ...errArgs } = err
    console.error(errMsg, errArgs)
    throw new Error(errMsg)
  }
  return res
}
</code>
</pre>

**Comment by StrivingRabbit** [comment]
可以查看 [API Promise 化](https://uniapp.dcloud.io/api/README?id=api-promise-%e5%8c%96) 来做相应的修改

**Comment by StrivingRabbit** [comment]
关于api 的 Promise 化类型提示。除 `uni.request 有返回值`、`同步的方法（即以 sync 结束）`、`以 create 开头的方法`、`以 manager 结束的方法`、`返回 task 的 api ` 暂不处理外，其他可以升级 @dcloudio/types@3.3.0 试试看

**Comment by StrivingRabbit** [comment]
部分 api promise 化提示已支持，后续进度请跟踪 #3009 查看
