### ISSUE TITLE
无法引入字节小程序新增组件

### ISSUE THREAD

**Issue by caizirong** [dcloudio/uni-app#3331]
**问题描述**
字节小程序新增了pay-button组件，由于是新增的特殊业务组件，且uniapp暂未适配。
参考官网提供的教程，在项目中增加 ttcomponents 文件夹，然后完成相关配置。
但是在 IDE 及真机上调试均会报错。
**复现步骤**
1.  使用vue-cli创建uniapp模版
2. 增加 ttcomponents/pay-button 文件夹，在文件夹里增加字节小程序自定义组件所需要的 index.ttml，index.ttss，index.json，index.js 文件，index.ttml 中使用了字节小程序内置组件 <pay-button> 。
3. 配置 pages.json 中的 usingComponents
4. 在 IDE 上进行调试查看
5. 发现有相关报错

**预期结果**
正常使用pay-button组件

**实际结果**
![image](https://user-images.githubusercontent.com/22556734/157791372-0721cf7d-6d5f-42c9-987c-b38fe9a3b716.png)
![image](https://user-images.githubusercontent.com/22556734/157791371-ea4d5bf8-4148-4936-9eb5-7945bb6c76e0.png)

**系统信息:**
 - 发行平台: 字节小程序
 - 操作系统 ios14.5
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 3.3.11
 - 设备信息 iphone12

**补充信息**
uniapp是否支持通过这种方式引入小程序新增组件

**Comment by zhetengbiji** [comment]
更新 HBuilderX 即可，如果是 CLI 创建的工程，使用 ```npx @dcloudio/uvm ``` 更新依赖即可。

**Comment by pipione** [comment]
使用最新版的搭配 vue3还是会有异常
