### ISSUE TITLE
在编译slot的时候，h5和小程序表现不一样

### ISSUE THREAD

**Issue by chenzhili** [dcloudio/uni-app#3332]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
目前的环境是：vue3+vite+ts+uni-ui 的 环境；
使用cli的方式开发；
具体版本：
![image](https://user-images.githubusercontent.com/22167727/157809449-8d8fb542-5711-4ef8-b965-87e5acf47c93.png)

1、编写一个组件：
```javascript
// 组件 Theme
<template>
  <view :style="theme">
    <slot></slot>
  </view>
</template>

<script setup lang="ts">
const theme = "--system-primary:#f0f;"
</script>

<style lang="scss" scoped>
<template>
  <Theme>
    <template #default>
      <view class="content">
        <button type="primary">44444ddd</button>
        <view class="test">sdfdf</view>
        <uni-badge size="small" :text="100" absolute="rightBottom" type="primary">aaaa</uni-badge>
      </view>
    </template>
  </Theme>
</template>
</style>
```
2、使用此组件
```javascript
<template>
  <Theme>
    <template #default>
      <view class="content">
        <button type="primary">44444ddd</button>
        <view class="test">sdfdf</view>
        <uni-badge size="small" :text="100" absolute="rightBottom" type="primary">aaaa</uni-badge>
      </view>
    </template>
  </Theme>
</template>
```

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
希望h5和小程序的编译结果保持一致

**实际结果**
// h5的节点编译如下：当前的 view带有 style的被正常包裹
![image](https://user-images.githubusercontent.com/22167727/157809588-872109cd-2d39-4b04-b342-ef2c8e63d677.png)
// 小程序里显示如下： 编译出错成为平级了
![image](https://user-images.githubusercontent.com/22167727/157809692-4e6b55ec-ecc6-46b9-b577-4f317169074f.png)

**系统信息:**
测试平台h5和微信小程序

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
微信小程序就是这么显示的，参考官方slot示例：https://developers.weixin.qq.com/s/1udXLnmi6KY2

**Comment by chenzhili** [comment]
那我在那层定义任何样式或者定义的css的变量，那不是不能影响slot里的变化了吗

**Comment by fxy060608** [comment]
> 那我在那层定义任何样式或者定义的css的变量，那不是不能影响slot里的变化了吗

只是这么显示，结构还是在里边

**Comment by chenzhili** [comment]
目前我定义css变量没有影响；在h5和小程序的表现如下：
![image](https://user-images.githubusercontent.com/22167727/157812773-000c5a4e-9744-4dea-bb96-d175a613c976.png)
![image](https://user-images.githubusercontent.com/22167727/157812850-f40dbac2-ebd8-4fa9-9110-36a30b764794.png)

**Comment by fxy060608** [comment]
> 目前我定义css变量没有影响；在h5和小程序的表现如下： ![image](https://user-images.githubusercontent.com/22167727/157812773-000c5a4e-9744-4dea-bb96-d175a613c976.png) ![image](https://user-images.githubusercontent.com/22167727/157812850-f40dbac2-ebd8-4fa9-9110-36a30b764794.png)

不加scoped测试下

**Comment by chenzhili** [comment]
在引用地方，我去掉scoped后，起作用了，但是去掉scoped后会不会影响到整体的样式的定义呢

**Comment by fxy060608** [comment]
> 在引用地方，我去掉scoped后，起作用了，但是去掉scoped后会不会影响到整体的样式的定义呢

默认只有页面的样式会作用到组件中，组件之间是隔离的

**Comment by chenzhili** [comment]
目前我想统一封装对于微信小程序这种没有统一根节点的主题切换，借住css的变量这块实现在所有注册路由加入变量，就会影响整体css的全局问题吗

**Comment by fxy060608** [comment]
> 目前我想统一封装对于微信小程序这种没有统一根节点的主题切换，借住css的变量这块实现在所有注册路由加入变量，就会影响整体css的全局问题吗

没明白什么意思，建议自己测试下想要的效果

**Comment by chenzhili** [comment]
就是想仿照react的HOC这个，动态切换css变量的挂载，在统一的Theme组件中修改对应的变量，每个page都嵌入此，实现对应的主题切换，如果将所有的组件的scoped都去掉，可能会导致css样式的混乱

**Comment by fxy060608** [comment]
> 就是想仿照react的HOC这个，动态切换css变量的挂载，在统一的Theme组件中修改对应的变量，每个page都嵌入此，实现对应的主题切换，如果将所有的组件的scoped都去掉，可能会导致css样式的混乱

看我之前回复，组件之间默认是隔离，不会互相影响的

**Comment by chenzhili** [comment]
我测试了哈，在 style里不加scoped的时候，h5上有隔离（自主加上了属性作为选择器.test[data-v-33af010c] {
    color: #ff0;
}），在微信上没有隔离（没有加入对应的属性）；

**Comment by fxy060608** [comment]
> 我测试了哈，在 style里不加scoped的时候，h5上有隔离（自主加上了属性作为选择器.test[data-v-33af010c] { color: #ff0; }），在微信上没有隔离（没有加入对应的属性）；

微信的隔离需要靠属性选择器隔离的，直接写代码测试，不需要看节点

**Comment by chenzhili** [comment]
```javascript
<template>
  <Theme>
    <template #center>
      <view class="content">
        <button type="primary">44444ddd</button>
        <view class="test">sdfdf</view>
        <uni-badge size="small" :text="100" absolute="rightBottom" type="primary">aaaa</uni-badge>
      </view>
    </template>
  </Theme>
</template>

<script setup lang="ts">
import { ref } from 'vue'
import { useCusStore } from '../../store/hooks/index'
import Theme from '../../components/Theme/index.vue'
const store = useCusStore();
console.log(store.state.user.info)
const title = ref('Hello')
</script>
<style lang="scss">
.test{
  color:#f0f !important;
}
.content {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  color: $uni-primary;
  .primary {
    background-color: $uni-test;
  }
}
</style>
```
```javascript
<template>  
  <view :style="theme">
    <view class="test">测试是否会影响</view>
    <slot name="center"></slot>
  </view>
</template>

<script setup lang="ts">
const theme = "--system-primary:#f0f;"
</script>

<style lang="scss">
.test{
  color:#0ff;
}
</style>
```
// 我在引入出 加入了 !important 关键字对 test类的 颜色进行了重写，h5和小程序的表现如下：
![image](https://user-images.githubusercontent.com/22167727/157817167-9147f902-8bdd-40ae-930f-13034f9be735.png)
![image](https://user-images.githubusercontent.com/22167727/157817215-8167193d-2430-42a3-948f-f5a3108bf647.png)

**Comment by fxy060608** [comment]
> ```js
> <template>
>   <Theme>
>     <template #center>
>       <view class="content">
>         <button type="primary">44444ddd</button>
>         <view class="test">sdfdf</view>
>         <uni-badge size="small" :text="100" absolute="rightBottom" type="primary">aaaa</uni-badge>
>       </view>
>     </template>
>   </Theme>
> </template>
> 
> <script setup lang="ts">
> import { ref } from 'vue'
> import { useCusStore } from '../../store/hooks/index'
> import Theme from '../../components/Theme/index.vue'
> const store = useCusStore();
> console.log(store.state.user.info)
> const title = ref('Hello')
> </script>
> <style lang="scss">
> .test{
>   color:#f0f !important;
> }
> .content {
>   display: flex;
>   flex-direction: column;
>   align-items: center;
>   justify-content: center;
>   color: $uni-primary;
>   .primary {
>     background-color: $uni-test;
>   }
> }
> </style>
> ```
> 
> ```js
> <template>  
>   <view :style="theme">
>     <view class="test">测试是否会影响</view>
>     <slot name="center"></slot>
>   </view>
> </template>
> 
> <script setup lang="ts">
> const theme = "--system-primary:#f0f;"
> </script>
> 
> <style lang="scss">
> .test{
>   color:#0ff;
> }
> </style>
> ```
> 
> // 我在引入出 加入了 !important 关键字对 test类的 颜色进行了重写，h5和小程序的表现如下： ![image](https://user-images.githubusercontent.com/22167727/157817167-9147f902-8bdd-40ae-930f-13034f9be735.png) ![image](https://user-images.githubusercontent.com/22167727/157817215-8167193d-2430-42a3-948f-f5a3108bf647.png)

h5平台和小程序平台没法保证完全一致

**Comment by chenzhili** [comment]
好的哈，我先尝试换一种方式实现，感谢

**Comment by chenzhili** [comment]
目前有点不清楚uniapp编译到微信小程序的隔离机制，我在应用层加入一个组件，这个组件的style上加入了scoped，按照上面的理解应该是会隔离，用我初始化的主题，但是显示是跟着page页面定义的颜色走的呢（虽然显示是预想的，但是如果按照每个组件是相互隔离的，这块应该跟着初始样式走呢）；
Test组件
```javascript
<template>
  <view class="test1">sfsdfsdfdfdf</view>
  <uni-badge size="small" :text="100" absolute="rightBottom" type="primary">{{a}}</uni-badge>
</template>
<script setup lang="ts">
const a = "12323232323"
</script>
<style lang="scss" scoped>
.test1{
  color:#f00;
}
</style>
```
```javascript
<template>
  <Theme>
    <template #center>
      <view class="content">
        <button type="primary">44444ddd</button>
        <view class="test">sdfdf</view>
        <uni-badge size="small" :text="100" absolute="rightBottom" type="primary">aaaa</uni-badge>
        <Test></Test>
      </view>
    </template>
  </Theme>
</template>
```
![image](https://user-images.githubusercontent.com/22167727/157822213-b087e12d-cbdb-4c65-b792-6aeda78f531e.png)
