### ISSUE TITLE
vue3 + cli 构建，无法正确的将 manifest.json 中 mp-qq 配置节配置的 appid 编译为 project.config.json 中的 qqappid 

### ISSUE THREAD

**Issue by appleone123** [dcloudio/uni-app#3339]
**问题描述**
使用 vue3 + cli 的方式搭建的 uni app 小程序工程，无法正确的将 manifest.json 中 mp-qq 配置节配置的 appid 编译为 project.config.json 中的 qqappid，导致 qq 小程序无法识别 appid。

**复现步骤**
[复现问题的步骤]
1、使用 vue3 + cli 搭建小程序工程
2、manifest.json 中配置 qq 小程序的 appid
3、使用 uni build -p mp-qq 或者 uni -p mp-qq 执行构建

[或者可以直接贴源代码]

**预期结果**
能够正确将 appid 字段编译为 project.config.json 中的 qqappid 字段

**实际结果**
编译出的 project.config.json 中仍然为 appid，不是 qqappid

**系统信息:**
 - 发行平台: qq 小程序
 - 操作系统: macOS 12.2.1 

**补充信息**
dependency：
    "@dcloudio/uni-app": "^3.0.0-alpha-3031220220222002",
    "@dcloudio/uni-app-plus": "^3.0.0-alpha-3031220220222002",
    "@dcloudio/uni-components": "^3.0.0-alpha-3031220220222002",
    "@dcloudio/uni-h5": "^3.0.0-alpha-3031220220222002",
    "@dcloudio/uni-mp-alipay": "^3.0.0-alpha-3031220220222002",
    "@dcloudio/uni-mp-baidu": "^3.0.0-alpha-3031220220222002",
    "@dcloudio/uni-mp-kuaishou": "^3.0.0-alpha-3031220220222002",
    "@dcloudio/uni-mp-lark": "^3.0.0-alpha-3031220220222002",
    "@dcloudio/uni-mp-qq": "^3.0.0-alpha-3031220220222002",
    "@dcloudio/uni-mp-toutiao": "^3.0.0-alpha-3031220220222002",
    "@dcloudio/uni-mp-weixin": "^3.0.0-alpha-3031220220222002",
    "@dcloudio/uni-quickapp-webview": "^3.0.0-alpha-3031220220222002",
devdependency:
    "@dcloudio/types": "^2.5.17",
    "@dcloudio/uni-automator": "^3.0.0-alpha-3031220220222002",
    "@dcloudio/uni-cli-shared": "^3.0.0-alpha-3031220220222002",
    "@dcloudio/vite-plugin-uni": "^3.0.0-alpha-3031220220222002",

**Comment by fxy060608** [comment]
稍后修复，根据测试，QQ小程序开发工具会根据appid自动补充相同的qqappid

**Comment by appleone123** [comment]
更新包：dcloudio/uni-mp-qq@3.0.0-alpha-3040220220310004 后经验证该问题已修复
