### ISSUE TITLE
vue3+vite2 字节小程序跨级传参第三级无法响应

### ISSUE THREAD

**Issue by Lisheri** [dcloudio/uni-app#3340]
**问题描述**

在字节小程序真机预览中, 发现跨级传参无法响应变化（模拟器偶现）

**复现步骤**
[复现问题的步骤]
1. 现有三个组件, 分别是组件1 组件2和组价3
2. 组件1使用组件2, 组件2使用组件3
3. 组件1向组件2传递参数value以及更新函数updateValue组件2将这个value直接传给组件3
4. 组件2中调用updatevalue更新value值, 组件2可以获取变化后的value, 但是组件3无反应

[代码如下]

comp1:

```html
<Tst1 v-model:value="tstVal" />
```

```ts
const tstVal: Ref<string> = ref("");
```

comp2:

```html
<template>
  <input :value="props.value" @input="handleChange" />
</template>
```

```ts
// setup

const props = defineProps<{
  value?: string;
}>()

const handleChange = (e: any) => {
  emit('update:value', e.target.value);
  emit('change', e.target.value);
}
```

comp3:

```html
<template>
  <view>{{ props.value }}</view>
</template>
```

```ts
const props = defineProps<{
  value?: string;
}>()
```

**预期结果**
希望使vue3响应式功能在字节小程序上正常

**实际结果**
传参无法跨三级

**系统信息:**
 - 发行平台: 字节小程序
 - 操作系统 Ios15.3.1
 - 设备信息 iphone12pro
 - 抖音版本 19.8.0

**补充信息**

dependence:
 "@dcloudio/uni-app": "^3.0.0-alpha-3040220220310003",
 "@dcloudio/uni-app-plus": "^3.0.0-alpha-3040220220310003",
"@dcloudio/uni-components": "^3.0.0-alpha-3040220220310003",
"@dcloudio/uni-h5": "^3.0.0-alpha-3040220220310003",
"@dcloudio/uni-mp-alipay": "^3.0.0-alpha-3040220220310003",
"@dcloudio/uni-mp-baidu": "^3.0.0-alpha-3040220220310003",
"@dcloudio/uni-mp-kuaishou": "^3.0.0-alpha-3040220220310003",
"@dcloudio/uni-mp-lark": "^3.0.0-alpha-3040220220310003",
"@dcloudio/uni-mp-qq": "^3.0.0-alpha-3040220220310003",
"@dcloudio/uni-mp-toutiao": "^3.0.0-alpha-3040220220310003",
"@dcloudio/uni-mp-weixin": "^3.0.0-alpha-3040220220310003",
"@dcloudio/uni-quickapp-webview": "^3.0.0-alpha-3040220220310003",
"@dcloudio/vite-plugin-uni": "3.0.0-alpha-3040220220310003",

可能出现错误的原因:
第三级组件入参已经更新, 但是第三级组件没有触发任何的更新操作。我猜测是父组件更新后, 并没有更新其下所有层级需要更新的子组件。

**Comment by Lisheri** [comment]
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/49238808/158292115-55996b30-1c9d-4207-979a-2bbeea10ee38.png">

props监听正常, 但不知道为什么没有触发更新

**Comment by fxy060608** [comment]
发测试工程

**Comment by Lisheri** [comment]
> 

https://microapp.bytedance.com/ide/minicode/Nhc43y6

在这里~

**Comment by fxy060608** [comment]
> > 
> 
> https://microapp.bytedance.com/ide/minicode/Nhc43y6
> 
> 在这里~

发uni-app工程

**Comment by Lisheri** [comment]
https://github.com/Lisheri/vue3-vite2-demo

好了

**Comment by Lisheri** [comment]
[下载zip](https://github.com/Lisheri/vue3-vite2-demo/archive/refs/heads/master.zip)

**Comment by Lisheri** [comment]
字节模拟器也可以复现

基础调试库: 2.40.x+

<img width="1497" alt="image" src="https://user-images.githubusercontent.com/49238808/158301328-7053c3e8-8632-4590-aabd-85e0ae7910de.png">
<img width="642" alt="image" src="https://user-images.githubusercontent.com/49238808/158301403-5f404044-bf1b-4ceb-b46a-2d8952d6a2d3.png">

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3040220220310004

**Comment by Lisheri** [comment]
感谢大佬
