### ISSUE TITLE
Cannot read property 'fn' of undefined

### ISSUE THREAD

**Issue by yxw007** [dcloudio/uni-app#3346]
**问题描述**
支持 配置多slot 

**复现步骤**
1. clone https://github.com/yxw007/uniapp_issue.git
2. yarn install
3. dev:mp-weixin

**预期结果**
支持配置多slot

**实际结果**
![image](https://user-images.githubusercontent.com/9338717/158323059-1bd1bae0-00e8-47a5-af42-3eb2576dc1e3.png)

**系统信息:**
 - 发行平台：微信小程序
 - uni-app版本：3.0.0-alpha-3030820220114008
 - vue： 3.2.30

**补充信息**
起初以为是vue的问题，结果发现vue无问题
[测试代码](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHNjcmlwdD5cbmltcG9ydCBGYW5jeUxpc3QgZnJvbSAnLi9GYW5jeUxpc3QudnVlJ1xuICBcbmV4cG9ydCBkZWZhdWx0IHtcbiAgY29tcG9uZW50czoge1xuICAgIEZhbmN5TGlzdFxuICB9XG59XG48L3NjcmlwdD5cblxuPHRlbXBsYXRlPlxuICA8RmFuY3lMaXN0PlxuICAgIDx0ZW1wbGF0ZSAjZmlyc3Q9XCJ7IGl0ZW0gfVwiPlxuICAgICAgPGRpdiBjbGFzcz1cIml0ZW1cIj5cbiAgICAgICB4eHgge3sgaXRlbS5uYW1lIH19XG4gICAgICA8L2Rpdj5cbiAgICA8L3RlbXBsYXRlPlxuICA8L0ZhbmN5TGlzdD5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZSBzY29wZWQ+XG4ubWV0YSB7XG4gIGZvbnQtc2l6ZTogMC44ZW07XG4gIGNvbG9yOiAjNDJiODgzO1xufVxuPC9zdHlsZT4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3VucGtnLmNvbS9AdnVlL3J1bnRpbWUtZG9tQDMuMi4zMS9kaXN0L3J1bnRpbWUtZG9tLmVzbS1icm93c2VyLmpzXCJcbiAgfVxufSIsIkZhbmN5TGlzdC52dWUiOiI8c2NyaXB0PlxuZXhwb3J0IGRlZmF1bHQge1xuICBkYXRhKCkge1xuICAgIHJldHVybiB7XG4gICAgICBpdGVtczogW11cbiAgICB9XG4gIH0sXG4gIG1vdW50ZWQoKSB7XG4gICAgdGhpcy5pdGVtcyA9IFtcbiAgICAgIHsgbmFtZTpcIml0ZW0xXCIgfSxcbiAgICAgIHsgbmFtZTpcIml0ZW0yXCIgfSxcbiAgICAgIHsgbmFtZTpcIml0ZW0zXCIgfSxcbiAgICAgIHsgbmFtZTpcIml0ZW00XCIgfSxcbiAgICAgIHsgbmFtZTpcIml0ZW01XCIgfSxcbiAgICBdXG4gIH1cbn1cbjwvc2NyaXB0PlxuXG48dGVtcGxhdGU+XG4gIDx1bD5cbiAgICA8bGkgdi1mb3I9XCIoaXRlbSxpbmRleCkgaW4gaXRlbXNcIj5cbiAgICAgIDxzbG90IHYtaWY9XCJpbmRleCA9PT0gMVwiIG5hbWU9XCJmaXJzdFwiIDppdGVtPVwiaXRlbVwiPjwvc2xvdD5cbiAgICAgIDxzbG90IHYtZWxzZSBuYW1lPVwib3RoZXJcIiA6aXRlbT1cIml0ZW1cIj5cbiAgICAgICAgb3RoZXIgaXRlbSB7e2l0ZW0ubmFtZX19XG4gICAgICA8L3Nsb3Q+XG4gICAgPC9saT5cbiAgPC91bD5cbjwvdGVtcGxhdGU+XG5cbjxzdHlsZSBzY29wZWQ+XG4gIHVsIHtcbiAgICBsaXN0LXN0eWxlLXR5cGU6IG5vbmU7XG4gICAgcGFkZGluZzogNXB4O1xuICAgIGJhY2tncm91bmQ6IGxpbmVhci1ncmFkaWVudCgzMTVkZWcsICM0MmQzOTIgMjUlLCAjNjQ3ZWZmKTtcbiAgfVxuICBsaSB7XG4gICAgcGFkZGluZzogNXB4IDIwcHg7XG4gICAgbWFyZ2luOiAxMHB4O1xuICAgIGJhY2tncm91bmQ6ICNmZmY7XG4gIH1cbjwvc3R5bGU+In0=)

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3040420220402006
