### ISSUE TITLE
升级 3.3.13.20220314 后 @touchmove 在微信小程序安卓端异常

### ISSUE THREAD

**Issue by jacksonyu** [dcloudio/uni-app#3347]
**问题描述**
hBuilderX 升级 3.3.13.20220314 后，使用 @touchmove 相关的图片裁切组件在微信小程序安卓端极其卡顿、不跟手，IOS 的微信端正常。
退回上一版本 3.3.11.20220210 后，一切恢复正常。

**复现步骤**
[复现问题的步骤]
1.  新建 uniapp 程序
2. 导入图片裁切的相关组件，或自己写相关组件。这里以这个组件为例：https://ext.dcloud.net.cn/plugin?id=6651
3. 导入上面的组件 bt-cropper
4. 按组件的实例编写代码（如下代码）
5. 编译到小程序-上传小程序-真机实际运行-ios正常，安卓卡顿。
6. hBuilderX 版本回退，重复第五步，一切正常。

```
<template>
    <view class="container">
        <bt-cropper ref="cropper" 
          imageSrc="https://mmbiz.qpic.cn/mmbiz_jpg/Pn4Sm0RsAuhqhqCxysMmyTDGpiaXuGJOOmce6vGrXM1sqKOicJoOQ8gZzgvkSkJlKJ4qtlkvCK2tT7URQJ5icXapg/640?wx_fmt=jpeg&wxfrom=5&wx_lazy=1&wx_co=1">
            <!-- 你想插入的内容 -->
            <button @click="crop">裁切</button>
        </bt-cropper>
    </view>
</template>

<script>
export default {
   methods:{
      crop(){
        // 通过组件定义的ref调用cropper方法，返回一个promise对象
        this.$refs.cropper.crop().then(([err,res])=>{
            if(!err){
                console.log(res)
            }else{
                console.err(err)
            }
        })
      }
   }
}
</script>

<style>
	 .container{
	        height:100vh;
	    }
</style>
```

**预期结果**
拖动缩放时一切正常

**实际结果**
ios正常，安卓卡顿。

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 ：hBuilderX 升级 3.3.13.20220314

**补充信息**
可能是新版本升级 vite 后导致。

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/3228

**Comment by jacksonyu** [comment]
> #3228

不太理解，这个问题是有解决的方案的吗还是这处于处理中的 bug ？
目前留在 3.3.11 版本不升级一切正常

**Comment by fxy060608** [comment]
> > #3228
> 
> 不太理解，这个问题是有解决的方案的吗还是这处于处理中的 bug ？ 目前留在 3.3.11 版本不升级一切正常

该提交是不理想的解决方案，未来发版如果没有更好的方案解决，会使用此方案临时解决touch事件延迟的问题

**Comment by jacksonyu** [comment]
> > > #3228
> > 
> > 
> > 不太理解，这个问题是有解决的方案的吗还是这处于处理中的 bug ？ 目前留在 3.3.11 版本不升级一切正常
> 
> 该提交是不理想的解决方案，未来发版如果没有更好的方案解决，会使用此方案临时解决touch事件延迟的问题

好的，谢谢回复。目前留在旧版，等待新版解决。
