### ISSUE TITLE
uniAPP中 h5和5+app下的android获取canvas像素错误

### ISSUE THREAD

**Issue by 2460392754** [dcloudio/uni-app#335]
**问题描述**
h5:在chrome在模拟h5状态是获取数据错误，非h5是获取像素数据无误
android:获取数据错误
微信小程序: 获取数据正确

**实际结果**
![U4O~K{TQ 3@$5}3AAJAR91](https://user-images.githubusercontent.com/39649938/56562688-8b8d1400-65dc-11e9-92a9-64853ae38825.png)

![76USIZ`)$SLA@DHGRBTE@9A](https://user-images.githubusercontent.com/39649938/56562769-bd05df80-65dc-11e9-9261-920df2ebc1dd.png)

![Screenshot_2019-04-23-15-33-49-128_io dcloud HBui](https://user-images.githubusercontent.com/39649938/56563020-52a16f00-65dd-11e9-9d17-27c2ffb914d6.png)

**系统信息:**
 - HBuilderX版本: 1.9.3.20190422
 - uni-app版本: hBuilderX创建
<br />

 - 发行平台: H5
 - 操作系统: window
 - 浏览器: chrome
<br />

 - 发行平台: 5+ App
 - 操作系统: Android 8.0
 - 设备信息: 小米8
<br />

 - 发行平台: 微信小程序
 - 操作系统: window
 - 版本: 1.02.1904090
<br />

**代码**
```key
<template>
	<view class="content">
		<canvas canvas-id="cav1"></canvas>
		<text>{{ str }}</text>
	</view>
</template>

<script>
export default {
	data() {
		return {
			str: null
		};
	},

	methods: {
		$_init() {
			const ctx1 = this._create('cav1');

			ctx1.setFillStyle('#ccc');
			ctx1.fillRect(0, 0, 2, 2);
			ctx1.setFillStyle('#333');
			ctx1.fillRect(2, 0, 2, 2);
			ctx1.setFillStyle('#666');
			ctx1.fillRect(0, 2, 2, 2);
			ctx1.setFillStyle('#999');
			ctx1.fillRect(2, 2, 2, 2);

			this._draw(ctx1)
				.then(() => {
					const opts = {
						id: 'cav1',
						width: 4,
						height: 4
					};

					return this._getPixel(opts);
				})
				.then(({ data }) => {
					const arr = this._arrFormat(data);
					let tempStr = '';

					for (let i of arr) {
						tempStr += JSON.stringify(i) + '\n';
					}

					this.str = tempStr;
				});
		},

		// 创建 ctx
		_create(id, that) {
			return uni.createCanvasContext(id, that);
		},

		// 渲染 ctx
		_draw(ctx, isSave = false) {
			return new Promise(resolve => {
				ctx.draw(isSave, resolve);
			});
		},

		// 获取 ctx 像素数据
		_getPixel({ x = 0, y = 0, id, width, height }, that) {
			return new Promise((resolve, reject) => {
				uni.canvasGetImageData(
					{
						canvasId: id,
						x,
						y,
						width,
						height,
						success: res => resolve(res),
						fail: err => reject(err)
					},
					that
				);
			});
		},

		// 格式化 rgba 数组
		_arrFormat(data) {
			let arr = [];
			let tempArr = [];

			for (let i = 0, len = data.length; i < len; i++) {
				tempArr.push(data[i]);
				tempArr.length === 4 && (arr.push(tempArr.join(',')), (tempArr = []));
			}

			return arr;
		}
	},

	mounted() {
		this.$_init();
	}
};
</script>

<style>
canvas {
	width: 4px;
	height: 4px;
	margin: 20px;
}
</style>

```

**Comment by dcloudhdx** [comment]
我们对canvas做了高清处理，getImageData目前未做处理
所以返回的 0,0,4,4是左上角的白点，实际canvas宽高为 * devicePixelRatio
请问getImageData后下一步要做什么？
我们可以提供参数是否返回高清后的ImageData，是否可以满足需求

**Comment by 2460392754** [comment]
嗯

**Comment by zhetengbiji** [comment]
微信小程序端，也请以微信小程序端真机为准，小程序模拟器表现可能有误

**Comment by liudao01** [comment]
> 我们对canvas做了高清处理，getImageData目前未做处理 所以返回的 0,0,4,4是左上角的白点，实际canvas宽高为 * devicePixelRatio 请问getImageData后下一步要做什么？ 我们可以提供参数是否返回高清后的ImageData，是否可以满足需求

请提供下返回高清的imageData, 目前我使用canvasGetImageData 这个方法, 返回的data 数据是模糊的,希望能返回高清图片, 很急 谢谢

**Comment by liudao01** [comment]
> 微信小程序端，也请以微信小程序端真机为准，小程序模拟器表现可能有误

目前使用的是android , 运行到安卓基座,获取数据后再打印, 但是打印的是模糊的数据 ,只有轮廓
