### ISSUE TITLE
onTabBarMidButtonTap事件污染全局组件属性

### ISSUE THREAD

**Issue by AK47-dadada** [dcloudio/uni-app#3352]
**问题描述**
我在我的app的所有底部菜单（原生）的页面添加了一个pop弹框组件，其中用show属性去做控制，在组件引入，等到界面加载完成以后，监听uni.onTabBarMidButtonTap事件，点击之后在当前页面弹出。但是发现，假如我的底部菜单页面已经进入缓存阶段（点击过下面的菜单对应的页面），再在当前页面点击mid按钮，做弹出关闭的动作之后，再切换到其它底部菜单对应的页面，会发现弹框已经弹出，请问这是什么原因导致的呢？
这个问题太困扰了，onTabBarMidButtonTap方法是全局的我知道，但是也会污染全局的组件属性吗？

**复现步骤**
[复现问题的步骤]
1.  启动 我在我的app的所有底部菜单（原生）的页面添加了一个pop弹框组件，其中用show属性去做控制，在组件引入，等到界面加载完成以后，监听uni.onTabBarMidButtonTap事件，点击之后在当前页面弹出
2. 点击  假如我的底部菜单页面已经进入缓存阶段（点击过下面的菜单对应的页面），再在当前页面点击mid按钮，做弹出关闭的动作之后，再切换到其它底部菜单对应的页面，会发现弹框已经弹出（但实际上我并未在其它页面做操作）

**预期结果**
每个页面单独控制pop组件的弹出与关闭，而不是指定页面操作之后，其他页面也被污染

**实际结果**
![image](https://user-images.githubusercontent.com/30396595/158931216-5ff91460-2ebc-439d-93af-3050a11d7313.png)
首页弹出状态，这里点击了关闭当前页面弹出后
![image](https://user-images.githubusercontent.com/30396595/158931100-7b3ec981-095b-45b8-a0d6-d3854f12aabb.png)
进入其它页面，实际上在当前页面我并未点击mid按钮，但是它显示已经弹出
![image](https://user-images.githubusercontent.com/30396595/158931311-71ad1ab8-e9b6-42f1-8833-5473fd94eb43.png)

**系统信息:**
 - 发行平台: [H5平台、AppPlus]
 - 操作系统 [chrome最新版本]
 - HBuilderX版本 [暂未使用HB编译打包]
 - uni-app版本 
 - uni-app v3.3.13
uni-app cli v2.0.1-33920220314002

Environment Info:

  System:
    OS: Windows 10
    CPU: (6) x64 Intel(R) Core(TM) i5-9500 CPU @ 3.00GHz
  Binaries:
    Node: 14.16.0 - D:\sofeware\Nodejs\node.EXE
    Yarn: Not Found
    npm: 8.1.3 - D:\sofeware\Nodejs\npm.CMD
  Browsers:
    Edge: Not Found
  npmPackages:
    @dcloudio/types: * => 2.5.18 
    @dcloudio/uni-app-plus: ^2.0.1-33920220208001 => 2.0.1-33920220314002   
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-automator: ^2.0.1-33920220208001 => 2.0.1-33920220314002  
    @dcloudio/uni-cli-i18n: ^2.0.1-33920220208001 => 2.0.1-33920220314002   
    @dcloudio/uni-cli-shared: ^2.0.1-33920220208001 => 2.0.1-33920220314002 
    @dcloudio/uni-h5: ^2.0.1-33920220208001 => 2.0.1-33920220314002         
    @dcloudio/uni-helper-json: * => 1.0.13 
    @dcloudio/uni-i18n: ^2.0.1-33920220208001 => 2.0.1-33920220314002       
    @dcloudio/uni-migration: ^2.0.1-33920220208001 => 2.0.1-33920220314002  
    @dcloudio/uni-mp-360: ^2.0.1-33920220208001 => 2.0.1-33920220314002
    @dcloudio/uni-mp-alipay: ^2.0.1-33920220208001 => 2.0.1-33920220314002
    @dcloudio/uni-mp-baidu: ^2.0.1-33920220208001 => 2.0.1-33920220314002
    @dcloudio/uni-mp-jd: ^2.0.1-33920220208001 => 2.0.1-33920220314002
    @dcloudio/uni-mp-kuaishou: ^2.0.1-33920220208001 => 2.0.1-33920220314002
    @dcloudio/uni-mp-lark: ^2.0.1-33920220208001 => 2.0.1-33920220314002
    @dcloudio/uni-mp-qq: ^2.0.1-33920220208001 => 2.0.1-33920220314002
    @dcloudio/uni-mp-toutiao: ^2.0.1-33920220208001 => 2.0.1-33920220314002
    @dcloudio/uni-mp-vue: ^2.0.1-33920220208001 => 2.0.1-33920220314002
    @dcloudio/uni-mp-weixin: ^2.0.1-33920220208001 => 2.0.1-33920220314002
    @dcloudio/uni-quickapp-native: ^2.0.1-33920220208001 => 2.0.1-33920220314002
    @dcloudio/uni-quickapp-webview: ^2.0.1-33920220208001 => 2.0.1-33920220314002
    @dcloudio/uni-stat: ^2.0.1-33920220208001 => 2.0.1-33920220314002
    @dcloudio/uni-template-compiler: ^2.0.1-33920220208001 => 2.0.1-33920220314002
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.1-33920220208001 => 2.0.1-33920220314002
    @dcloudio/vue-cli-plugin-uni: ^2.0.1-33920220208001 => 2.0.1-33920220314002
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.1-33920220208001 => 2.0.1-33920220314002
    @dcloudio/webpack-uni-mp-loader: ^2.0.1-33920220208001 => 2.0.1-33920220314002
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.1-33920220208001 => 2.0.1-33920220314002
    @hap-toolkit/dsl-vue:  0.6.13
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.1.1
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.16
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.16
    @vue/cli-plugin-babel: ~4.5.15 => 4.5.16
    @vue/cli-plugin-eslint: ~4.5.15 => 4.5.16
    @vue/cli-plugin-router:  4.5.16
    @vue/cli-plugin-vuex:  4.5.16
    @vue/cli-service: ~4.5.15 => 4.5.16
    @vue/cli-shared-utils:  4.5.16
    @vue/component-compiler-utils:  3.3.0 (3.3.0)
    @vue/devtools-api:  6.0.0-beta.15
    @vue/eslint-config-prettier: ^6.0.0 => 6.0.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/shared: ^3.0.0 => 3.2.31
    @vue/web-component-wrapper:  1.3.0
    eslint-plugin-vue: ^6.2.2 => 6.2.2
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.11 => 2.6.14
    vue-eslint-parser:  7.11.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.8 (16.8.3, 15.9.8)
    vue-router:  3.0.1
    vue-style-loader:  4.1.3 (4.1.3)
    vue-template-compiler: ^2.6.11 => 2.6.14 (2.6.14)
    vue-template-es2015-compiler:  1.9.1
    vue3:  1.0.0
    vuex: ^3.2.0 => 3.6.2 (3.6.2)
  npmGlobalPackages:
    @vue/cli: Not Found
 - 设备信息 [win10]

**补充信息**
很困惑，不知道什么原因导致的。

**Comment by fxy060608** [comment]
发测试工程
