### ISSUE TITLE
使用uni.preLogin 报错

### ISSUE THREAD

**Issue by MQYForverT** [dcloudio/uni-app#3353]
**问题描述**
在app中使用uni.preLogin方法，提示[Vue warn]: Error in onShow hook: "TypeError: uni.preLogin is not a function"

**复现步骤**
onShow() {
		//#ifdef APP-PLUS
		const that = this
		uni.preLogin({
			provider: 'univerify',
			success() {
				//预登录成功
				that.show = true
			},
			fail(res) {
				// 预登录失败
				that.show = false
				console.log(res)
			}
		})
		//#endif
	}

**预期结果**
成功，控制台无报错

**实际结果**
失败，
并报错：[Vue warn]: Error in onShow hook: "TypeError: uni.preLogin is not a function"

**系统信息:**
 - 发行平台: app
 - 操作系统 Android 7.0+
 - HBuilderX版本 3.2.9
 - vue版本：2

**补充信息**
无

**Comment by Chul-y** [comment]
错误解决了吗？
