### ISSUE TITLE
vue3 ts vite 通过import引入图片资源 打包后路径出错

### ISSUE THREAD

**Issue by zcjunblog** [dcloudio/uni-app#3354]
**问题描述**
![](https://s1.ax1x.com/2022/03/19/qAePMQ.png)
打包后被编译成base64的正常显示 
其余放到assets目录录下的 路径前会多出一段/pages/index
用官方demo试了也是一样的

**复现步骤**
[复现问题的步骤]
引入
import img_logo from '../../static/img/1.png'
使用
 <image class="logo" :src="img_logo" />
项目使用cli搭建的
**预期结果**
开发环境正常

**实际结果**
打包后生产环境路径出错

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]

**Comment by fxy060608** [comment]
发测试工程

**Comment by zcjunblog** [comment]
> 发测试工程
下载该测试文件  https://www.wenshushu.cn/f/7vsnx90lnvx

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3040220220310006
