### ISSUE TITLE
vue3+ts使用provide/inject在字节小程序中无法传值

### ISSUE THREAD

**Issue by Lisheri** [dcloudio/uni-app#3360]
**问题描述**
使用provide传值, 在子组件中使用inject无法获取到传递的值, 只能拿到默认值, 如不给默认值就是undefined

**复现步骤**
[复现问题的步骤]
1. 父组件provide
2. 子组件inject
3. 打印查看inject返回值, 为undefined(有默认值就是默认值)

**预期结果**
希望正常传值与响应式更新

**实际结果**
<img width="397" alt="image" src="https://user-images.githubusercontent.com/49238808/159424829-4965a30d-8cee-43b7-96dc-dd4001f7d917.png">
<img width="607" alt="image" src="https://user-images.githubusercontent.com/49238808/159424859-8cabe70e-979c-4474-9159-536da2c5a7f2.png">
<img width="1097" alt="image" src="https://user-images.githubusercontent.com/49238808/159424894-ba602813-15cf-4663-958a-eabc75815aee.png">

**系统信息:**
 - 发行平台: 字节小程序模拟器
 - 操作系统: macos12.2
 - uni-app版本: 3.0.0-alpha-3040220220310004

**补充信息**
demo地址: https://github.com/Lisheri/vue3-vite2-demo
[demo链接](https://github.com/Lisheri/vue3-vite2-demo/archive/refs/heads/master.zip)

**Comment by fxy060608** [comment]
目前字节跳动小程序的组件父子关系初始化较晚，在setup阶段，还没有初始化父子关系，导致无法正常使用provide/inject，
临时解决方案，可以使用 options 方式定义 inject（注意你的代码里t.t需要额外判断t已存在，t && t.t）

**Comment by Lisheri** [comment]
行, 感谢老哥~

**Comment by fxy060608** [comment]
> 老哥这个版本今天不发吗~

已更新：3.0.0-alpha-3040220220310007

**Comment by Lisheri** [comment]
> 

感谢哥~

**Comment by Lisheri** [comment]
<img width="1810" alt="image" src="https://user-images.githubusercontent.com/49238808/159618551-090d81c0-d2fe-457a-9ec2-632849dce3cf.png">
老哥, 执行到这个位置的时候有办法知道当前instance的爹是谁吗？

**Comment by fxy060608** [comment]
> <img alt="image" width="1810" src="https://user-images.githubusercontent.com/49238808/159618551-090d81c0-d2fe-457a-9ec2-632849dce3cf.png">
> 
> 老哥, 执行到这个位置的时候有办法知道当前instance的爹是谁吗？

目前在字节上不知道，如果知道，就不会出现provide/inject在setup中不生效的问题

**Comment by Lisheri** [comment]
那老哥, 是否可以针对字节小程序, 暂时先往根节点上挂provides, 如果这样改的话, 是否会有什么影响呢?(除了provide/inject不再是单向向下)
<img width="1248" alt="image" src="https://user-images.githubusercontent.com/49238808/159623598-3a45fe34-25e9-4ad6-944d-04f18158aa92.png">

**Comment by fxy060608** [comment]
> 那老哥, 是否可以针对字节小程序, 暂时先往根节点上挂provides, 如果这样改的话, 是否会有什么影响呢?(除了provide/inject不再是单向向下) <img alt="image" width="1248" src="https://user-images.githubusercontent.com/49238808/159623598-3a45fe34-25e9-4ad6-944d-04f18158aa92.png">

你自己直接app.provide就行了

**Comment by Lisheri** [comment]
> > 那老哥, 是否可以针对字节小程序, 暂时先往根节点上挂provides, 如果这样改的话, 是否会有什么影响呢?(除了provide/inject不再是单向向下) <img alt="image" width="1248" src="https://user-images.githubusercontent.com/49238808/159623598-3a45fe34-25e9-4ad6-944d-04f18158aa92.png">
> 
> 你自己直接app.provide就行了

行~

**Comment by foliet** [comment]
这个bug还是没修复吗

**Comment by qinains** [comment]
在onMounted提供provide，在onMounted能够inject到数据，如
```
// parent.vue
onMounted(() => {
	provide('xxx', value);
})
```
```
// child.vue
onMounted(() => {
	console.log(inject('xxx'));
})
```

**Comment by foliet** [comment]
是这个bug修好了吗？确定是抖音小程序不是微信小程序吗？

**Comment by foliet** [comment]
> 在onMounted提供provide，在onMounted能够inject到数据，如
> 
> ```
> // parent.vue
> onMounted(() => {
> 	provide('xxx', value);
> })
> ```
> 
> ```
> // child.vue
> onMounted(() => {
> 	console.log(inject('xxx'));
> })
> ```
是这个bug修好了吗？确定是抖音小程序不是微信小程序吗？

**Comment by Lisheri** [comment]
> > 在onMounted提供provide，在onMounted能够inject到数据，如
> > ```
> > // parent.vue
> > onMounted(() => {
> > 	provide('xxx', value);
> > })
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > // child.vue
> > onMounted(() => {
> > 	console.log(inject('xxx'));
> > })
> > ```
> 
> 是这个bug修好了吗？确定是抖音小程序不是微信小程序吗？

我去年看还是一样的, 不过好久没搞字节小程序了

**Comment by qinains** [comment]
> 是这个bug修好了吗？确定是抖音小程序不是微信小程序吗？
我现在这么写，能在抖音小程序的<script setup>中使用，如下：
![image](https://github.com/dcloudio/uni-app/assets/528630/1d20a437-8325-44ef-81e8-ea7a6453d3e3)
![image](https://github.com/dcloudio/uni-app/assets/528630/f861e2b2-da2c-44e1-b8ea-5709011c1835)

**Comment by wen-gang** [comment]
还没修复好啊

**Comment by wendell0316** [comment]
> > 是这个bug修好了吗？确定是抖音小程序不是微信小程序吗？
> 
> 我现在这么写，能在抖音小程序的<script setup>中使用，如下： ![image](https://github.com/dcloudio/uni-app/assets/528630/1d20a437-8325-44ef-81e8-ea7a6453d3e3) ![image](https://github.com/dcloudio/uni-app/assets/528630/0c681edb-1c69-4577-b605-a9fb4da2423e)

你的版本是多少呀，为啥我这样写还是不行

**Comment by jkbody** [comment]
> > > 是这个bug修好了吗？确定是抖音小程序不是微信小程序吗？
> > 
> > 
> > 我现在这么写，能在抖音小程序的<script setup>中使用，如下： ![image](https://github.com/dcloudio/uni-app/assets/528630/1d20a437-8325-44ef-81e8-ea7a6453d3e3) ![image](https://private-user-images.githubusercontent.com/528630/308153435-0c681edb-1c69-4577-b605-a9fb4da2423e.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjM5Njc5MTgsIm5iZiI6MTc2Mzk2NzYxOCwicGF0aCI6Ii81Mjg2MzAvMzA4MTUzNDM1LTBjNjgxZWRiLTFjNjktNDU3Ny1iNjA1LWE5ZmI0ZGEyNDIzZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEyNFQwNzAwMThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODExNDc5MzYwMTZmYWVkZDM5ZjY5MzdiZWE5MTkxMGFmMDlhZDk5MmEyMTNjOGMzYWY5YmE0MmIyOTEyYTdlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.tjK_106mZahWrNVz3F-FfTvKlJzNEoBAyf2_Vckm7sM)
> 
> 你的版本是多少呀，为啥我这样写还是不行
我这样写也不行。
