### ISSUE TITLE
vue3 小程序输出usingComponents为空

### ISSUE THREAD

**Issue by okxiaoliang4** [dcloudio/uni-app#3363]
**问题描述**
将uni-app升级到[3.0.0-alpha-3040220220310007](https://www.npmjs.com/package/@dcloudio/uni-app/v/3.0.0-alpha-3040220220310007)版本后，easycom自动导入组件失效

**复现步骤**
1. 升级到[3.0.0-alpha-3040220220310007](https://www.npmjs.com/package/@dcloudio/uni-app/v/3.0.0-alpha-3040220220310007)版本
2. 配置easycom
3. `npm run dev:mp-weixin`

**预期结果**
编译后组件描述json usingComponents包含正确组件

**实际结果**
```json
{
  "navigationBarTitleText": "xxx",
  "navigationStyle": "custom",
  "transparentTitle": "always",
  "titlePenetrate": "YES",
  "enablePullDownRefresh": true,
  "usingComponents": {}
}
```

**系统信息:**
 - 微信小程序
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app@[3.0.0-alpha-3040220220310007](https://www.npmjs.com/package/@dcloudio/uni-app/v/3.0.0-alpha-3040220220310007)
 - 设备信息 [如 iPhone8 Plus]

**补充信息**

**Comment by fxy060608** [comment]
发测试工程

**Comment by okxiaoliang4** [comment]
@fxy060608 [repo](https://github.com/okxiaoliang4/uni-issue)

**Comment by okxiaoliang4** [comment]
奇怪，我新建项目复现不出来，我看看从正常版本到有问题的版本是哪个版本，排查一下到哪个版本有问题

**Comment by okxiaoliang4** [comment]
找到问题了，这几个包没对应更新版本

```shell
@dcloudio/uni-automator
@dcloudio/uni-cli-shared
@dcloudio/vite-plugin-uni
```
