### ISSUE TITLE
苹果h5调用chooseImage，拍照选择没有回调

### ISSUE THREAD

**Issue by w22296437978** [dcloudio/uni-app#3365]
已在社区提交，没有收到回复： https://ask.dcloud.net.cn/question/141759
测试手机：
model=iPhone, system=iOS 15.0.2, platform=ios
```
uni.chooseImage({  
    count: this.count, //默认9  
    sizeType: this.sizeType, //可以指定是原图还是压缩图，默认二者都有  
    // sourceType: ['album'], //从相册选择  
    success: async (res) => {  
        log("选择成功")  
     },  
     fail(err){  
        log("选择失败")  
     }  
 });
```
其中log是封装的向服务器发送日志的插件
在安卓手机拍照或者选择相册都有日志，
但是在苹果手机，拍照时没有日志，在相册选择照片有日志

**Comment by tangsj** [comment]
@w22296437978   问题最后解决没？

**Comment by zhetengbiji** [comment]
> @w22296437978 问题最后解决没？

如果你也是在微信内置浏览器使用，建议使用微信的jssdk。Web平台的chooseImage实现使用的是input file，微信内置浏览器在实现input file上可能存在一些兼容问题，使用jssdk可以避免这些兼容问题。
