### ISSUE TITLE
APP进入每个页面都会报错Uncaught SyntaxError: Unexpected token { at app-renderjs.js:310

### ISSUE THREAD

**Issue by wudexiong** [dcloudio/uni-app#3366]
**问题描述**

使用OPPO R11st 真机测试项目 发现每次进入一个页面控制台都会提示Uncaught SyntaxError: Unexpected token { at app-renderjs.js:310错误 并且在使用了renderjs的页面也会提出错误导致项目部分功能失效！ 用其他手机真机测试没有任何问题！
**复现步骤**
[复现问题的步骤]
1. 真机自定义基座运行启动
2. 进入首页(首页使用了z-paging插件 wxs+renderjs ) Vue3项目 
3. 控制台提示报错

**预期结果**
项目使用到renderjs的时候与其他手机一样是正常的

**实际结果**
使用了renderjs
```
Uncaught SyntaxError: Unexpected token { at app-renderjs.js:310
09:51:56.035 [1648173119189][324ms][wxs]："module pagingRenderjs not found" at uni-app-view.umd.js:3
09:51:56.056 [1648173119189][0ms][wxs]："module pagingRenderjs not found" at uni-app-view.umd.js:3
09:51:56.240 Uncaught SyntaxError: Unexpected token { at app-renderjs.js:310
```
没有使用renderjs
```
Uncaught SyntaxError: Unexpected token { at app-renderjs.js:310
```

**系统信息:**
 - 发行平台: APP
 - 操作系统 [Android 8.1.0]
 - HBuilderX版本 [3.3.13.20220314]
 - uni-app版本 [3.3.13.20220314]
 - 设备信息 [OPPO R11st]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
1.目前测试了很多真机 只有OPPO R11st手机会报错 其他手机运行 都是没有任何问题的
2.vue2项目在该OPPO R11st手机上是没有问题的 项目升级到vue3出现的问题
3.只要使用了renderjs就会报错 并且实际影响的也是使用了renderjs页面的功能。 比如加载的three.js canvas画布就无法显示

**Comment by fxy060608** [comment]
发测试工程

**Comment by wudexiong** [comment]
不需要测试工程，已经找到一处导致这个问题的原因：
调用vite的方法 : `import.meta.globEager` 就会报上述错误
我自己测的时候是新建的项目测试的，vue3 + vite
其他的问题我还在测试，不止一个地方导致这种报错信息...

**Comment by wudexiong** [comment]
@fxy060608 测试工程：https://github.com/wudexiong/uniapp-OPPO-renderjs-bug

**Comment by fxy060608** [comment]
> @fxy060608 测试工程：https://github.com/wudexiong/uniapp-OPPO-renderjs-bug

确认下你的OPPO R11st的 webview 版本号
vue3 要求 webview 必须支持 Proxy 的

**Comment by wudexiong** [comment]
@fxy060608  OPPO R11st的 webview 版本号： Android System WebView 版本 62.0.3202.84
真机调试都是正常的，就是打包成APP不行 这和webview版本应该没有关系吧

**Comment by fxy060608** [comment]
更新至HBuilder Alpha 3.4.6测试
