### ISSUE TITLE
vue3 vite postcss配置失效

### ISSUE THREAD

**Issue by okxiaoliang4** [dcloudio/uni-app#3367]
**问题描述**
使用`postcss-px-to-viewport`将`px`转`vw`在最新版本无效

**复现步骤**
[repo](https://github.com/okxiaoliang4/uni-issue)中给的是正常版本的，将uni-app相关依赖升级到最新版本即可复现问题，无法转换为vw

**预期结果**
`px`正常转`vw`

**实际结果**
无转换

**系统信息:**
 - 微信小程序
 - uni-app@^3.0.0-alpha-3040320220324002

**Comment by fxy060608** [comment]
在vite.config.js中配置
https://vitejs.dev/config/#css-postcss
