### ISSUE TITLE
uni Vue3 版本（HBuilderX 默认模板）：H5启动运行没自带端口号、不能使用媒体组件audio

### ISSUE THREAD

**Issue by huayang0304** [dcloudio/uni-app#3368]
uni vue3 版本（HBuilderX 默认模板）：
问题1：H5启动运行没自带端口号
             终端出现ESC符号
![image](https://user-images.githubusercontent.com/45450994/160077649-df2174c5-cb63-41e5-8e28-cceee523fa29.png)
问题2：无法使用音频媒体组件audio，vite报错
             Cannot find module '@dcloudio/uni-components/style/audio.css'
             Require stack:
15:52:53.711 - E:\HbuilderX\plugins\uniapp-cli-vite\node_modules\@dcloudio\uni-cli-shared\dist\resolve.js
             vue2版本可以正常使用
![image](https://user-images.githubusercontent.com/45450994/160078031-2bd67d25-93d1-4862-92b8-96635aad4dbb.png)

**Comment by fxy060608** [comment]
端口问题：
HBuilderX->工具->插件安装->uni-app（Vue 3）卸载，然后重新安装
audio已废弃，请使用[uni.createInnerAudioContext](https://uniapp.dcloud.net.cn/api/media/audio-context#createinneraudiocontext)

**Comment by huayang0304** [comment]
> 端口问题： HBuilderX->工具->插件安装->uni-app（Vue 3）卸载，然后重新安装 audio已废弃，请使用[uni.createInnerAudioContext](https://uniapp.dcloud.net.cn/api/media/audio-context#createinneraudiocontext)

多谢答疑，问题1果然是插件问题。问题二我尝试了安装https://ext.dcloud.net.cn/plugin?id=1313#detail插件，成功解决了我的问题
