### ISSUE TITLE
官网下载不了 HBuilderX

### ISSUE THREAD

**Issue by huayang0304** [dcloudio/uni-app#3369]
访问 https://www.dcloud.io/hbuilderx.html
点击w无反应
![image](https://user-images.githubusercontent.com/45450994/160081962-ad393caf-6441-4c37-a665-be977eb7e0ec.png)

**Comment by zhetengbiji** [comment]
网络原因，从截图看，页面还未加载完毕。刷新或者切换网络后重试。

**Comment by huayang0304** [comment]
> 

不行，谷歌浏览器加载完毕了，并没有继续请求

**Comment by zhetengbiji** [comment]
> > 
> 
> 不行，谷歌浏览器加载完毕了，并没有继续请求

那你从网络面板看到这个请求成功了还是失败了：https://download1.dcloud.net.cn/hbuilderx/release.json

**Comment by huayang0304** [comment]
> > > 
> > 
> > 
> > 不行，谷歌浏览器加载完毕了，并没有继续请求
> 
> 那你从网络面板看到这个请求成功了还是失败了：https://download1.dcloud.net.cn/hbuilderx/release.json

成功的，秒打开，电脑网速70M/s

**Comment by huayang0304** [comment]
> > > 
> > 
> > 
> > 不行，谷歌浏览器加载完毕了，并没有继续请求
> 
> 那你从网络面板看到这个请求成功了还是失败了：https://download1.dcloud.net.cn/hbuilderx/release.json

![image](https://user-images.githubusercontent.com/45450994/160084809-9dfa9a05-5e95-46c1-853b-e0ee0148ac57.png)

**Comment by zhetengbiji** [comment]
> > > > 
> > > 
> > > 
> > > 不行，谷歌浏览器加载完毕了，并没有继续请求
> > 
> > 
> > 那你从网络面板看到这个请求成功了还是失败了：https://download1.dcloud.net.cn/hbuilderx/release.json
> 
> ![image](https://user-images.githubusercontent.com/45450994/160084809-9dfa9a05-5e95-46c1-853b-e0ee0148ac57.png)

也就是你的网络访问不了这个资源是吧：https://js.cdn.aliyun.dcloud.net.cn/dev/js/jquery-2.1.0.js

**Comment by huayang0304** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 不行，谷歌浏览器加载完毕了，并没有继续请求
> > > 
> > > 
> > > 那你从网络面板看到这个请求成功了还是失败了：https://download1.dcloud.net.cn/hbuilderx/release.json
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/45450994/160084809-9dfa9a05-5e95-46c1-853b-e0ee0148ac57.png)
> 
> 也就是你的网络访问不了这个资源是吧：https://js.cdn.aliyun.dcloud.net.cn/dev/js/jquery-2.1.0.js

是的

**Comment by huayang0304** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 不行，谷歌浏览器加载完毕了，并没有继续请求
> > > 
> > > 
> > > 那你从网络面板看到这个请求成功了还是失败了：https://download1.dcloud.net.cn/hbuilderx/release.json
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/45450994/160084809-9dfa9a05-5e95-46c1-853b-e0ee0148ac57.png)
> 
> 也就是你的网络访问不了这个资源是吧：https://js.cdn.aliyun.dcloud.net.cn/dev/js/jquery-2.1.0.js

![image](https://user-images.githubusercontent.com/45450994/160085428-2f5f47ec-5481-46ea-8b07-014a8af324c7.png)

**Comment by zhetengbiji** [comment]
你的地区和网络运营商能否发一下

**Comment by huayang0304** [comment]
> 

我们是国家电网的内网，不会内网把这地址屏蔽了吧...
四川成都武侯区

**Comment by huayang0304** [comment]
> > 
> 
> 我们是国家电网的内网（可以访问外网），不会内网把这地址屏蔽了吧... 四川成都武侯区

**Comment by zhetengbiji** [comment]
> > > 
> > 
> > 
> > 我们是国家电网的内网（可以访问外网），不会内网把这地址屏蔽了吧... 四川成都武侯区

你尝试修改一下DNS为：114.114.114.114

**Comment by wan201809** [comment]
windows版下载地址：https://download1.dcloud.net.cn/download/HBuilderX.3.3.13.20220314.full.zip

mac版下载地址：https://download1.dcloud.net.cn/download/HBuilderX.3.3.13.20220314.full.dmg

**Comment by huayang0304** [comment]
> 114.114.114.114

不行，我用@[wan201809](https://github.com/wan201809) 评论的地址下载算了，多谢解答

**Comment by zhetengbiji** [comment]
你在终端执行```dig js.cdn.aliyun.dcloud.net.cn```，把输出截图发一下。

**Comment by huayang0304** [comment]
> 你在终端执行`dig js.cdn.aliyun.dcloud.net.cn`，把输出截图发一下。

我安装了 dig 命令，但是dig命令运行系统错误 
看来我无法提供给你截图...
