### ISSUE TITLE
uni.getStorageSync在支付宝小程序有bug

### ISSUE THREAD

**Issue by dutedehuai** [dcloudio/uni-app#337]
**问题描述**
uni.getStorageSync(key, value);在支付宝小程序有bug，当value为false或者0时，返回的是''，应该返回的时上次设置的value，比如上次设置了false，get就应该得到false，而不是''

![image](https://user-images.githubusercontent.com/7028755/56605030-ca02ed00-6635-11e9-92ae-ac590b02d65c.png)

**Comment by xiaoyucoding** [comment]
你可以测试一下，直接使用 my 开头的支付宝小程序的 API 组合使用，是否也是同样的现象。

**Comment by dutedehuai** [comment]
用my开头的没有这个问题
