### ISSUE TITLE
【vue3】props 更新不会导致页面重新渲染

### ISSUE THREAD

**Issue by sufuwang** [dcloudio/uni-app#3370]
**问题描述**
子组件的 props 为 类型为 Object 的 ref 时，且为单个时，props 的改变不会重新渲染当前页面，若在加上一个 props ，即使不为此 props 传值时，页面也会重新渲染

**复现步骤**
[复现问题的步骤]
测试工程： https://github.com/sufuwang/uniapp_vite/tree/bug/props
1.  启动项目
2. /pages/index/index 页面的跳转按钮，跳转至另一个页面后跳回
3. 观察 /pages/index/index 跳转按钮下方数据是没有变化的（不正常）
4. 关闭 src/pages/index/comps/test.vue 的注释，再次执行 2、3 步骤，页面按照预期展示（正常）

<b>示例可能有点绕，总结一下问题，就是子组件的 props 更新，在某些情况下，页面不重新渲染</b>

**预期结果**
<img width="437" alt="image" src="https://user-images.githubusercontent.com/46395105/160082601-a401a9f6-27a4-45ec-b6f4-5d4785fd21db.png">

**实际结果**
<img width="416" alt="image" src="https://user-images.githubusercontent.com/46395105/160082547-61fe75bd-65ff-4d94-885e-c81e31db37fb.png">

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**Comment by huayang0304** [comment]
你的uni vue3项目能否使用  音频媒体audio组件？

**Comment by sufuwang** [comment]
> 你的uni vue3项目能否使用 音频媒体audio组件？

没有用过，不清楚这个问题

**Comment by huayang0304** [comment]
> > 你的uni vue3项目可以使用音频媒体组件吗？
> 
> 没有用过，那个问题

可以帮忙 看下么 ，文件地址 在网盘  或者你随便用个 音频
 <audio src="/static/qingtian.mp3" controls></audio>
https://zhidao.baidu.com/question/1576394695453337780.html

**Comment by huayang0304** [comment]
> > 你的uni vue3项目能否使用 音频媒体audio组件？
> 
> 没有用过，不清楚这个问题

<audio src="/static/qingtian.mp3" controls></audio>

**Comment by sufuwang** [comment]
> > > 你的uni vue3项目可以使用音频媒体组件吗？
> > 
> > 
> > 没有用过，那个问题
> 
> 可以帮忙 看下么 ，文件地址 在网盘 或者你随便用个 音频 audio ‘’ https://zhidao.baidu.com/question/1576394695453337780.html

你把代码发一下呗

**Comment by huayang0304** [comment]
https://uniapp.dcloud.io/component/audio.html

**Comment by huayang0304** [comment]
audio id="au1" src="/static/qingtian.mp3" controls></audio
两边加< >

**Comment by sufuwang** [comment]
> audio id="au1" src="/static/qingtian.mp3" controls></audio 两边加< >

你的是什么问题？

**Comment by huayang0304** [comment]
> audio id="au1" src="/static/qingtian.mp3" controls></audio 两边加< >



> > audio id="au1" src="/static/qingtian.mp3" controls></audio 两边加< >
> 
> 你的是什么问题？

https://github.com/dcloudio/uni-app/issues/3368

**Comment by sufuwang** [comment]
> > audio id="au1" src="/static/qingtian.mp3" controls></audio 两边加< >
> 
> > > audio id="au1" src="/static/qingtian.mp3" controls></audio 两边加< >
> > 
> > 
> > 你的是什么问题？
> 
> #3368

你用我发的测试工程试试，我这边没有报错

**Comment by huayang0304** [comment]
> > > audio id="au1" src="/static/qingtian.mp3" controls></audio 两边加< >
> > 
> > 
> > > > audio id="au1" src="/static/qingtian.mp3" controls></audio 两边加< >
> > > 
> > > 
> > > 你的是什么问题？
> > 
> > 
> > #3368
> 
> 你用我发的测试工程试试，我这边没有报错
是这个么
[uniapp_vite](https://github.com/sufuwang/uniapp_vite)

**Comment by sufuwang** [comment]
用 bug/props 分支吧

**Comment by huayang0304** [comment]
> 用 bug/props 分支吧

好的，我先尝试 重装HBuilderX ，不行用你这个架子

**Comment by huayang0304** [comment]
> 用 bug/props 分支吧

我尝试了你的架子，很遗憾，audio 媒体组件依旧无法使用，Vite报错了，我只有放弃使用 Vue3 版本了

**Comment by sufuwang** [comment]
@fxy060608 大佬，看看这个问题呗

**Comment by fxy060608** [comment]
代码的写法有问题
建议不要写这么不清晰的逻辑，一方面使用ref，一方面使用globalData，又来回赋值，期望影响页面渲染
你出问题的代码可以简化为
```js
const t = { a: 2 }; // 模拟的globalData中的数据
const test = ref({ a: 1 });
test.value = t; // 将globalData的数据赋值给ref
function onClick() {
  t.a += 1;// 修改 t.a 是不会触发页面渲染的，只有修改 test.value.a 才会触发页面渲染
  console.log(t.a === test.value.a); // 此时 t.a 与 test.value.a 是相等的
}
```

**Comment by sufuwang** [comment]
> 代码的写法有问题 建议不要写这么不清晰的逻辑，一方面使用ref，一方面使用globalData，又来回赋值，期望影响页面渲染 你出问题的代码可以简化为
> 
> ```js
> const t = { a: 2 }; // 模拟的globalData中的数据
> const test = ref({ a: 1 });
> test.value = t; // 将globalData的数据赋值给ref
> function onClick() {
>   t.a += 1;// 修改 t.a 是不会触发页面渲染的，只有修改 test.value.a 才会触发页面渲染
>   console.log(t.a === test.value.a); // 此时 t.a 与 test.value.a 是相等的
> }
> ```
@fxy060608   大佬，我重新描述一下这个问题，<b>这种逻辑在 webpack 下正常</b>
使用 globalData 是为了在多个页面中共享数据， a 页面存在一个 hooks ，hooks 中 onShow 中读取 globalData 然后赋给 ref ，并返回 ref 给 a 页面的子组件，以此来触发 a 页面重新渲染。a 页面可以跳转至 b 页面，在 b 页面中可以修改 globalData ，然后回退至 a 页面，触发 hooks 下的 onShow 进行页面重新渲染。
现在问题就出现在 a 页面的子组件，我尝试在子组件中加入 onShow 并解析打印 props ，可以看到 props 是不同的，但子组件(不是页面)没有重新渲染。
<b>在测试工程中</b>，可以复现这个问题，globalData 修改是成功的，并且页面渲染了，但子组件没有根据最新的 props 重新渲染
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/46395105/160340026-74d91bc7-d733-4e76-88b2-a9fd6e85fae5.png">
<img width="2056" alt="image" src="https://user-images.githubusercontent.com/46395105/160340256-7febabd0-129c-4e5b-b232-d43a9b419518.png">

**Comment by fxy060608** [comment]
你跳转回来后，在`onShow`里边赋值`count.value = d.c`是不会触发渲染的
因为你count.value本身就是代理的d.c，你修改d.c的时候，count.value也已经被修改了，执行赋值时，vue判定两个数据没有发生变化，不会执行渲染，你可以选择每次生成一个新对象`count.value = {...d.c}`
你运行到h5平台，或者直接用标准的vue3测试就知道了，
通常这种问题，h5平台也不行的话，基本上意味着是自己写法的问题

**Comment by sufuwang** [comment]
> 



> 你跳转回来后，在`onShow`里边赋值`count.value = d.c`是不会触发渲染的 因为你count.value本身就是代理的d.c，你修改d.c的时候，count.value也已经被修改了，执行赋值时，vue判定两个数据没有发生变化，不会执行渲染 你运行到h5平台，或者直接用标准的vue3测试就知道了， 通常这种问题，h5平台也不行的话，基本上意味着是自己写法的问题
> 
> 你可以选择每次生成一个新对象`count.value = {...d.c}`

@fxy060608 大佬，你这意思我可以理解，但为什么页面和组件的表现不一致

**Comment by fxy060608** [comment]
> > 
> 
> > 你跳转回来后，在`onShow`里边赋值`count.value = d.c`是不会触发渲染的 因为你count.value本身就是代理的d.c，你修改d.c的时候，count.value也已经被修改了，执行赋值时，vue判定两个数据没有发生变化，不会执行渲染 你运行到h5平台，或者直接用标准的vue3测试就知道了， 通常这种问题，h5平台也不行的话，基本上意味着是自己写法的问题
> > 你可以选择每次生成一个新对象`count.value = {...d.c}`
> 
> @fxy060608 大佬，你这意思我可以理解，但为什么页面和组件的表现不一致

页面可以是因为你用了定时器，不停地在修改其他属性，触发了页面渲染，页面渲染时会使用最新的数据，你把你的定时器去掉，页面一样不会渲染

**Comment by sufuwang** [comment]
> > > 
> > 
> > 
> > > 你跳转回来后，在`onShow`里边赋值`count.value = d.c`是不会触发渲染的 因为你count.value本身就是代理的d.c，你修改d.c的时候，count.value也已经被修改了，执行赋值时，vue判定两个数据没有发生变化，不会执行渲染 你运行到h5平台，或者直接用标准的vue3测试就知道了， 通常这种问题，h5平台也不行的话，基本上意味着是自己写法的问题
> > > 你可以选择每次生成一个新对象`count.value = {...d.c}`
> > 
> > 
> > @fxy060608 大佬，你这意思我可以理解，但为什么页面和组件的表现不一致
> 
> 页面可以是因为你用了定时器，不停地在修改其他属性，触发了页面渲染，页面渲染时会使用最新的数据，你把你的定时器去掉，页面一样不会渲染

@fxy060608 现在搞明白了，没有问题了，感谢大佬解答

**Comment by sufuwang** [comment]
> > > 
> > 
> > 
> > > 你跳转回来后，在`onShow`里边赋值`count.value = d.c`是不会触发渲染的 因为你count.value本身就是代理的d.c，你修改d.c的时候，count.value也已经被修改了，执行赋值时，vue判定两个数据没有发生变化，不会执行渲染 你运行到h5平台，或者直接用标准的vue3测试就知道了， 通常这种问题，h5平台也不行的话，基本上意味着是自己写法的问题
> > > 你可以选择每次生成一个新对象`count.value = {...d.c}`
> > 
> > 
> > @fxy060608 大佬，你这意思我可以理解，但为什么页面和组件的表现不一致
> 
> 页面可以是因为你用了定时器，不停地在修改其他属性，触发了页面渲染，页面渲染时会使用最新的数据，你把你的定时器去掉，页面一样不会渲染

@fxy060608  大佬，再请教一个问题，根据你的讲解，我把这个问题替换成了如下代码
```vue
<script lang="ts">
export default defineComponent({
  setup() {
    const refObj = ref<any>(null);
    const obj = { a: 1 };
    onLoad(() => {
      setInterval(() => {
        obj.a = Date.now();
      }, 500);
    });
    onShow(() => {
      refObj.value = obj;
    });
    return {
      refObj,
    };
  },
});
</script>
```
上述这段代码在 webpack 版本中，页面可以重新渲染，而在 vite 版本中不能重新渲染，即使在 onShow 中修改 obj 的引用
```vue
    onShow(() => {
      refObj.value = { ...obj };
    });
```
我觉得 vite 版本更符合响应式机制的思想，但为什么 webpack 版本可以如此更新？这个是 webpack 版本的 bug ，还是考虑什么情况做了此优化呀？

**Comment by fxy060608** [comment]
> ```
> refObj.value = { ...obj };
> ```

这是vue2和vue3响应式实现的差异

`refObj.value = obj` 表示refObj会代理obj对象，你正确的操作应该是修改`refObj.value.a+=1`，这样可以触发渲染，而不是通过`obj.a+=1; refObj.value = obj`来实现，这是不对的，这个方式只能修改a的值，无法触发渲染，`refObj.value = { ...obj };`可以触发，自己可以再试，来回切换页面来触发onShow

**Comment by sufuwang** [comment]
> > ```
> > refObj.value = { ...obj };
> > ```
> 
> 这是vue2和vue3响应式实现的差异
> 
> `refObj.value = obj` 表示refObj会代理obj对象，你正确的操作应该是修改`refObj.value.a+=1`，这样可以触发渲染，而不是通过`obj.a+=1; refObj.value = obj`来实现，这是不对的，这个方式只能修改a的值，无法触发渲染，`refObj.value = { ...obj };`可以触发，自己可以再试，来回切换页面来触发onShow

好的，明白了，感谢大佬
