### ISSUE TITLE
uniapp使用字节自定义组件打包，运行报错

### ISSUE THREAD

**Issue by Leon522** [dcloudio/uni-app#3372]
**问题描述**
uniapp使用字节自定义组件打包，运行报错

**复现步骤**
[复现问题的步骤]
按照官网步骤引入运行报错

**系统信息:**
 - 发行平台: 
 - 字节小程序
 - 操作系统
 -  windows开发者工具
 - HBuilderX版本  
 - 3.3.11

 - 设备信息 
 -  windows开发者工具

![image](https://user-images.githubusercontent.com/15059173/160127404-30c8ebd0-d448-48eb-b54b-02954e4af144.png)
![image](https://user-images.githubusercontent.com/15059173/160127461-2eb87cf3-53ae-407a-8b83-59bc5740fe20.png)

**Comment by Leon522** [comment]
最小可复现demo
[demo-uniapp.zip](https://github.com/dcloudio/uni-app/files/8350793/demo-uniapp.zip)

**Comment by fxy060608** [comment]
你在pages.json中配置的组件名称是`captcha4`,在模板里用的却是`test`
