### ISSUE TITLE
$refs中没有对应dom

### ISSUE THREAD

**Issue by saltFishxxx** [dcloudio/uni-app#3373]
**问题描述**
<template>
	<view>
		<u-toast id="toast" ref="uToast"></u-toast>
		<u--text id="text" text="正在开发中，敬请期待"></u--text>
		<u-button ref="button"></u-button>
		<u-button @click="click">点击</u-button>
	</view>
</template>
<script>
	export default {
		data() {
			return {
			}
		},
		onReady() {
			console.log('refs', this.$refs)
		},
		methods: {
			click() {
				this.$msg({message: 'xxx'})
			},
		}
	}
</script>
运行小程序模拟器，这里引入了uview组件

**预期结果**
$refs中存在toast和button

**实际结果**
均返回undefined

**系统信息:**
下载最新的xbuilder和微信小程序

**Comment by fxy060608** [comment]
看不懂发的什么

**Comment by saltFishxxx** [comment]
之前代码没显示出来，现在看下呢
