### ISSUE TITLE
 'uni.saveFile' not supported 下载文件无法保存

### ISSUE THREAD

**Issue by IOLOII** [dcloudio/uni-app#3374]
**问题描述**
调用save方法时返回错误
{errMsg: "saveFile:fail method 'uni.saveFile' not supported"}

**复现步骤**
```js
downloadTask.onProgressUpdate(function (res) {
  console.log('下载进度' + res.progress)
})
```
```js
uni.saveFile({
  tempFilePath: res.tempFilePath,
  success: function (res) {
    console.log('保存成功')
    console.log(res)
    console.log(res.savedFilePath)
  },
  fail: error => {
    alert('error')
    alert(error.toString())
    console.log(error)
  }
})
```

**预期结果**
正常保存文件到手机或模拟器的磁盘中

**实际结果**
![image](https://user-images.githubusercontent.com/34856171/160253666-79ccfe67-a785-4451-8163-3df1253cf021.png)

**系统信息:**
 - 发行平台: App
 - 操作系统 [Android 7.1.2，Android 11]
 - HBuilderX版本 3.3.11.20220209

 - 设备信息 [android 7 是模拟器，android 11 是pixel 3]

**补充信息**
很多例子也都是这样写的，但是运行的时候报错，尚不清楚原因在哪

**Comment by zhetengbiji** [comment]
H5 不支持

**Comment by IOLOII** [comment]
明白了，在打包app后仍然是h5
因为目前使用的是打包h5然后使用cordova包装成app

那么应该是使用xhbulid上的打包app就可以使用这个api，是吗？
