### ISSUE TITLE
条件编译中能不能加上开发模式或生产模式？

### ISSUE THREAD

**Issue by netangsoft** [dcloudio/uni-app#3375]
条件编译中能不能加上开发模式或生产模式？

虽然可以在js文件中使用`process.env.NODE_ENV !== 'production'`来包裹代码，但是vue/nvue/css/sass/json等文件则不能这样做。
而且js中import的文件也不合法：
```
if (process.env.NODE_ENV !== 'production') {
    import configDataDev from '@/configs/config/development'
}
```

所以，强烈建议条件编译中能加上开发和生产模式的判断。
类似如下：
```
#ifdef DEVELOPMENT
    // ...
#endif

#ifdef PRODUCTION
    // ...
#endif
```
或简写
```
#ifdef DEV
    // ...
#endif

#ifdef PRO
    // ...
#endif
```

**Comment by fxy060608** [comment]
1. 自定义条件编译：https://uniapp.dcloud.net.cn/collocation/package.html#%E6%A6%82%E8%BF%B0
2. ```js
if (process.env.NODE_ENV !== 'production') {
    import configDataDev from '@/configs/config/development'
}
```
import语句是静态分析的，不能动态执行

**Comment by netangsoft** [comment]
@fxy060608 这个自定义条件编译只能自定义web和小程序平台环境，不能自定义app的环境变量
![image](https://user-images.githubusercontent.com/81273619/160330255-c37a9bec-508c-41d9-8197-46e64f9ce0a3.png)
