### ISSUE TITLE
构建出的支付宝小程序  app.js 里默认有onShareAppMessage函数，但返回了undefined，导致支付宝小程序的默认分享功能失效

### ISSUE THREAD

**Issue by pingan1927** [dcloudio/uni-app#3377]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
构建出的支付宝小程序  app.js 里默认有onShareAppMessage函数，但返回了undefined，导致支付宝小程序的默认分享功能失效

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

![image](https://user-images.githubusercontent.com/347649/160344696-767aebd4-a065-4542-8319-e3df7ec285fb.png)

IDE调试面板 getApp()返回的app示例里多了app.onShareAppMessage，当用户分享时，因为没有返回符合要求的分享Object，导致分享失败
![image](https://user-images.githubusercontent.com/347649/160344602-b13d0cd8-fc2e-4556-a8ea-771d75f1e308.png)

https://opendocs.alipay.com/mini/framework/app-detail#onShareAppMessage(object%3A%20Object)

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
源码app.vue 若未声明 onShareAppMessage，则在执行initHooks时也不应该多生成onShareAppMessage

![image](https://user-images.githubusercontent.com/347649/160349023-697393c3-a154-4710-9558-a99c733f5037.png)

![image](https://user-images.githubusercontent.com/347649/160349068-d8361da7-2285-4179-ab16-c27e71514a58.png)

**实际结果**
[这里请贴上你的报错截图或文字]

在支付宝小程序里点击右上角...按钮后 再点分享 无法弹出分享面板

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
3.4.4 已发布
