### ISSUE TITLE
通过插件市场引入uview，会把所有组件都编译成小程序组件，导致无法获取refs。但是使用npm导入就不存在这个问题

### ISSUE THREAD

**Issue by saltFishxxx** [dcloudio/uni-app#3378]
可以查看这个issue：$refs中没有对应dom #3373

**Comment by fxy060608** [comment]
测试没有问题，
确认根据文档 https://www.uviewui.com/components/downloadSetting.html 配置正确，
还有问题的话，发测试工程，或者联系uView作者
