### ISSUE TITLE
v-for里将item作为参数调用，报错item未定义

### ISSUE THREAD

**Issue by DailyLee** [dcloudio/uni-app#338]
开启微信小程序"usingComponents": true之后
v-for item in items，使用方法或者filter将item作为参数调用，错误item未定义
估计是因为，编译之后在vue中this上调用item，所以提示未定义item
 
ps：编程成头条小程序，正常运行

**Comment by newsekaes** [comment]
遇到了同样的问题

**Comment by xiaoyucoding** [comment]
HBuilderX 1.9.3 测试未能重现问题，请提供下可以重现问题的代码。
目前测试代码如下：
```
<template>
	<view>
		<text v-for="item in list" :key="item">{{item | test}}</text>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				list: [1, 2, 3]
			}
		},
		filters: {
			test: function(value) {
				return 'item:' + value;
			}
		},
		methods: {

		}
	}
</script>

<style>

</style>
```

**Comment by newsekaes** [comment]
我感觉是`<view>`标签的原因
```
<template>
    <view>
       	<view v-for="(hello, i) in list" v-bind:key="i" class="status-row">
	    <text class="status-label">{{hello.split('').join(' ')}}</text>
	</view>
    </view>
</template>

<script>
    export default {
        data() {
            return {
                list: [1, 2, 3]
            }
        },
    }
</script>

```

**Comment by DailyLee** [comment]
> HBuilderX 1.9.3 测试未能重现问题，请提供下可以重现问题的代码。
> 目前测试代码如下：
> 
> ```
> <template>
>     <view>
>         <text v-for="item in list" :key="item">{{item | test}}</text>
>     </view>
> </template>
> 
> <script>
>     export default {
>         data() {
>             return {
>                 list: [1, 2, 3]
>             }
>         },
>         filters: {
>             test: function(value) {
>                 return 'item:' + value;
>             }
>         },
>         methods: {
> 
>         }
>     }
> </script>
> 
> <style>
> 
> </style>
> ```

**Comment by DailyLee** [comment]
> HBuilderX 1.9.3 测试未能重现问题，请提供下可以重现问题的代码。
> 目前测试代码如下：
> 
> ```
> <template>
>     <view>
>         <text v-for="item in list" :key="item">{{item | test}}</text>
>     </view>
> </template>
> 
> <script>
>     export default {
>         data() {
>             return {
>                 list: [1, 2, 3]
>             }
>         },
>         filters: {
>             test: function(value) {
>                 return 'item:' + value;
>             }
>         },
>         methods: {
> 
>         }
>     }
> </script>
> 
> <style>
> 
> </style>
> ```

数据结构超过三层，{{item.item.id | test}}会报错

**Comment by xiaoyucoding** [comment]
> > HBuilderX 1.9.3 测试未能重现问题，请提供下可以重现问题的代码。
> > 目前测试代码如下：
> > ```
> > <template>
> >     <view>
> >         <text v-for="item in list" :key="item">{{item | test}}</text>
> >     </view>
> > </template>
> > 
> > <script>
> >     export default {
> >         data() {
> >             return {
> >                 list: [1, 2, 3]
> >             }
> >         },
> >         filters: {
> >             test: function(value) {
> >                 return 'item:' + value;
> >             }
> >         },
> >         methods: {
> > 
> >         }
> >     }
> > </script>
> > 
> > <style>
> > 
> > </style>
> > ```
> 
> 数据结构超过三层，{{item.item.id | test}}会报错

确认问题，后续修复并优化。
filter 的支持并非直接使用的 Vue 引擎，而是 uni 框架自身实现的，目前没有理想中那么强大。
目前的方案是循环之前处理数据，或者不使用这种嵌套较多的数据结构。

**Comment by Fasttian** [comment]
已经修复该问题，请升级到最新版。
