### ISSUE TITLE
HBuilderX工具被杀毒软件报告含有后门?

### ISSUE THREAD

**Issue by mentoorliubin** [dcloudio/uni-app#3380]
<img width="1090" alt="QQ20220328-203342@2x" src="https://user-images.githubusercontent.com/52729282/160398912-0a4b92ea-68a3-4557-86e8-9103249faee0.png">

**Comment by zhetengbiji** [comment]
这是使用的哪款“杀毒软件”？

**Comment by mentoorliubin** [comment]
> 这是使用的哪款“杀毒软件”？

ClearMyMac X

**Comment by mentoorliubin** [comment]
> 这是使用的哪款“杀毒软件”？

CleanMyMac X

**Comment by zhetengbiji** [comment]
> > 这是使用的哪款“杀毒软件”？
> 
> CleanMyMac X

目前HBuilderX在Mac平台仅在apple官方提交了公证：https://developer.apple.com/cn/documentation/xcode/notarizing_macos_software_before_distribution/

未提交到此类三方“杀毒软件”进行公证

**Comment by mentoorliubin** [comment]
> > > 这是使用的哪款“杀毒软件”？
> > 
> > 
> > CleanMyMac X
> 
> 目前HBuilderX在Mac平台仅在apple官方提交了公证：https://developer.apple.com/cn/documentation/xcode/notarizing_macos_software_before_distribution/
> 
> 未提交到此类三方“杀毒软件”进行公证

好的~谢谢

**Comment by wan201809** [comment]
[HBuilderX被误报病毒木马的说明](https://hx.dcloud.net.cn/Tutorial/Security?id=hbuilderx%e8%a2%ab%e8%af%af%e6%8a%a5%e7%97%85%e6%af%92%e6%9c%a8%e9%a9%ac%e7%9a%84%e8%af%b4%e6%98%8e)
