### ISSUE TITLE
v-model.number 修饰符不起作用

### ISSUE THREAD

**Issue by Sexy6God** [dcloudio/uni-app#3381]
**问题描述**
v-model.number 修饰符不起作用

**复现步骤**
```
<template>
  <div class="main">
    <input class="input" v-model.number="num" />
    <button @click="log">输出log</button>
  </div>
</template>

<script setup lang="ts">
  let num = ref(0);

  function log() {
    console.log(typeof num.value);
    console.log('num:', num.value);
  }
</script>
```
[最小可复现Demo](https://github.com/Sexy6God/uni-vue3-vite-compile-bug)

[或者可以直接贴源代码]

**预期结果**
console.log(typeof num.value); 输出 number

**实际结果**
console.log(typeof num.value); 输出 string

**系统信息:**
 - 发行平台: 微信小程序
 - uni-app版本 `3.0.0-alpha-3040320220325003`

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3040320220325004
