### ISSUE TITLE
百度生命周期钩子 onInit 无效

### ISSUE THREAD

**Issue by appleone123** [dcloudio/uni-app#3384]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
vue 3 百度小程序，使用 onInit 生命周期，发现在运行时无法触发

**复现步骤**
1.  使用 HBuilder X 最新 alpha 版本和 vue 3 创建一个示例小程序工程 // 使用 cli + vue 3 同样可复现
2. 在任一页面中增加 onInit 钩子，并在其中打印信息输出
3. 运行时并未打印出 onInit 中的 log

**预期结果**
onInit 能够正常触发

**实际结果**
onInit 未触发

**系统信息:**
 - 发行平台: 百度小程序
 - 操作系统：双端
 - HBuilderX版本 3.4.3.20220325-alpha
 - uni-app版本 3.0.0-alpha-3040320220325003

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
经我这边初步排查，发现 onInit 钩子初始化进入以下函数时，return 语句的 this.$vm 是个 falsy 值，导致后面的 callhook 语句实际并未走到
![image](https://user-images.githubusercontent.com/18554629/160528398-904e01e4-a133-48ba-9de6-dec4374fed2c.png)
对应的 log 点位的实际输出如下：
![image](https://user-images.githubusercontent.com/18554629/160528511-fc434d8e-adcc-4e31-910e-ce61295e97b5.png)
<img width="621" alt="image" src="https://user-images.githubusercontent.com/18554629/160528613-cbce3917-630a-439e-823e-1612dbbf59f9.png">

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3040320220325004

**Comment by appleone123** [comment]
> 

使用 3.0.0-alpha-3040320220325004 版本 cli 仍可复现该问题，未能成功调用 onInit 生命周期钩子，前述 log ： this.$vm is falsy 仍然会输出。依赖列表：
dependencies：
"@dcloudio/uni-app": "^3.0.0-alpha-3040320220325004",
    "@dcloudio/uni-app-plus": "^3.0.0-alpha-3040320220325004",
    "@dcloudio/uni-components": "^3.0.0-alpha-3040320220325004",
    "@dcloudio/uni-h5": "^3.0.0-alpha-3040320220325004",
    "@dcloudio/uni-mp-alipay": "^3.0.0-alpha-3040320220325004",
    "@dcloudio/uni-mp-baidu": "^3.0.0-alpha-3040320220325004",
    "@dcloudio/uni-mp-kuaishou": "^3.0.0-alpha-3040320220325004",
    "@dcloudio/uni-mp-lark": "^3.0.0-alpha-3040320220325004",
    "@dcloudio/uni-mp-qq": "^3.0.0-alpha-3040220220310004",
    "@dcloudio/uni-mp-toutiao": "^3.0.0-alpha-3040320220325004",
    "@dcloudio/uni-mp-weixin": "^3.0.0-alpha-3040320220325004",
    "@dcloudio/uni-quickapp-webview": "^3.0.0-alpha-3040320220325004",
devDependencies：
    "@dcloudio/types": "^2.5.17",
    "@dcloudio/uni-automator": "^3.0.0-alpha-3040320220325004",
    "@dcloudio/uni-cli-shared": "^3.0.0-alpha-3040320220325004",
    "@dcloudio/vite-plugin-uni": "^3.0.0-alpha-3040320220325004",

**Comment by fxy060608** [comment]
> > 
> 
> 使用 3.0.0-alpha-3040320220325004 版本 cli 仍可复现该问题，未能成功调用 onInit 生命周期钩子，前述 log ： this.$vm is falsy 仍然会输出。依赖列表： dependencies： "@dcloudio/uni-app": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-app-plus": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-components": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-h5": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-mp-alipay": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-mp-baidu": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-mp-kuaishou": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-mp-lark": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-mp-qq": "^3.0.0-alpha-3040220220310004", "@dcloudio/uni-mp-toutiao": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-mp-weixin": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-quickapp-webview": "^3.0.0-alpha-3040320220325004", devDependencies： "@dcloudio/types": "^2.5.17", "@dcloudio/uni-automator": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-cli-shared": "^3.0.0-alpha-3040320220325004", "@dcloudio/vite-plugin-uni": "^3.0.0-alpha-3040320220325004",

已修复，更新至：3.0.0-alpha-3040320220325005

**Comment by appleone123** [comment]
> > > 
> > 
> > 
> > 使用 3.0.0-alpha-3040320220325004 版本 cli 仍可复现该问题，未能成功调用 onInit 生命周期钩子，前述 log ： this.$vm is falsy 仍然会输出。依赖列表： dependencies： "@dcloudio/uni-app": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-app-plus": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-components": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-h5": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-mp-alipay": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-mp-baidu": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-mp-kuaishou": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-mp-lark": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-mp-qq": "^3.0.0-alpha-3040220220310004", "@dcloudio/uni-mp-toutiao": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-mp-weixin": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-quickapp-webview": "^3.0.0-alpha-3040320220325004", devDependencies： "@dcloudio/types": "^2.5.17", "@dcloudio/uni-automator": "^3.0.0-alpha-3040320220325004", "@dcloudio/uni-cli-shared": "^3.0.0-alpha-3040320220325004", "@dcloudio/vite-plugin-uni": "^3.0.0-alpha-3040320220325004",
> 
> 已修复，更新至：3.0.0-alpha-3040320220325005

已验证，该版本已修复
