### ISSUE TITLE
关于小程序不支持 tsx 以及 render 函数的问题

### ISSUE THREAD

**Issue by Miofly** [dcloudio/uni-app#3387]
如果一直不支持，有什么替代方法吗？怎么在 template 模板中去渲染 虚拟节点，这个是难道没有支持的计划吗？
比如以下节点如何渲染
![image](https://user-images.githubusercontent.com/42859910/160778667-9122b870-eeaa-4190-9522-30a86bb68589.png)

**Comment by fxy060608** [comment]
目前无计划支持
看不懂你说的虚拟节点的意思

**Comment by zhetengbiji** [comment]
render 函数过于灵活，目前 uni-app 转换小程序方案是 Vue 组件转换成小程序原生组件，而小程序原生组件不支持动态创建节点，所以目前方案不支持。也暂无支持计划。

另外你说的虚拟节点是指的 vnode 吗？小程序平台也不支持 vnode，原因与上一条相同。

你可以说一下你具体的需求，看能否为你提供方案。

**Comment by Miofly** [comment]
> render 函数过于灵活，目前 uni-app 转换小程序方案是 Vue 组件转换成小程序原生组件，而小程序原生组件不支持动态创建节点，所以目前方案不支持。也暂无支持计划。
> 
> 另外你说的虚拟节点是指的 vnode 吗？小程序平台也不支持 vnode，原因与上一条相同。
> 
> 你可以说一下你具体的需求，看能否为你提供方案。

之前在 h5 中组件用了这么一种写法
```
export const renderTNode = (
	instance: ComponentInternalInstance | null,
	name: string,
	options?: Slots | JSXRenderContext
): any => {
	if (instance === null) {
		return h('', null);
	}
	const params = typeof options === 'object' && 'params' in options ? options.params : null;
	const defaultNode = typeof options === 'object' && 'defaultNode' in options ? options.defaultNode : options;
	let propsNode: any;
	if (name in instance.props) {
		propsNode = instance.props[name];
	}

	// if (propsNode === false) return;
	// 同名优先处理插槽
	if (instance.slots[name]) {
		return instance.slots[name]?.call(params);
	}

	if (propsNode === true && defaultNode) {
		return instance.slots[name] ? instance.slots[name]?.call(params) : defaultNode;
	}
	if (typeof propsNode === 'function') return propsNode(h, params);
	const isPropsEmpty = [undefined, params, ''].includes(propsNode);
	if (isPropsEmpty && instance.slots[name]) return instance.slots[name]?.call(params);
	return propsNode;
}
```
例如以下组件渲染，title 这个属性我即可以用 slot 也可以用 props，通过上面的函数返回一个 vNdoe，然后通过 render 渲染。
```
<v-cell>
    <template #title>
         <span>多选12222</span>
     </template>
</v-cell>
<v-cell title="单行1标题" />				
```
小程序确定不支持的话我重新换一个逻辑去判断

**Comment by frankcou** [comment]
> render 函数过于灵活，目前 uni-app 转换小程序方案是 Vue 组件转换成小程序原生组件，而小程序原生组件不支持动态创建节点，所以目前方案不支持。也暂无支持计划。
> 
> 另外你说的虚拟节点是指的 vnode 吗？小程序平台也不支持 vnode，原因与上一条相同。
> 
> 你可以说一下你具体的需求，看能否为你提供方案。

想了解一下为什么taro它可以用tsx开发小程序？

**Comment by zhetengbiji** [comment]
> > render 函数过于灵活，目前 uni-app 转换小程序方案是 Vue 组件转换成小程序原生组件，而小程序原生组件不支持动态创建节点，所以目前方案不支持。也暂无支持计划。
> > 另外你说的虚拟节点是指的 vnode 吗？小程序平台也不支持 vnode，原因与上一条相同。
> > 你可以说一下你具体的需求，看能否为你提供方案。
> 
> 想了解一下为什么taro它可以用tsx开发小程序？

taro 使用的方案不同，具体在 taro2.0 重构的时候有详细说明（重构的原因，重构采用的方案，以及利弊）。
