### ISSUE TITLE
​使用微信小程序页面配置属性disableSwipeBack无效

### ISSUE THREAD

**Issue by 0131LWG** [dcloudio/uni-app#339]
**问题描述**
​使用微信小程序页面配置属性disableSwipeBack无效

**预期结果**
希望取消手机全面屏手势返回，微信小程序已支持

**实际结果**
​使用微信小程序页面配置属性disableSwipeBack无效

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统:: Android版本9
 - uni-app版本: 最新
 - 设备：小米8 屏幕指纹版
 - 微信使用版本: 7.0.4

**补充信息**
框架不支持微信小程序页面配置属性disableSwipeBack

**Comment by xiaoyucoding** [comment]
预期的平台是微信小程序吧，目前是怎么配置的，请提供下关键代码。

**Comment by 0131LWG** [comment]
> 预期的平台是微信小程序吧，目前是怎么配置的，请提供下关键代码。

![image](https://user-images.githubusercontent.com/30310735/56704754-f48d9c80-6740-11e9-884f-14e4d43aec14.png)

**Comment by xiaoyucoding** [comment]
`page->style->mp-weixin->disableSwipBack`

按照这个配置试试呢

**Comment by 0131LWG** [comment]
> `page->style->mp-weixin->disableSwipBack`
> 
> 按照这个配置试试呢

![image](https://user-images.githubusercontent.com/30310735/56710412-9967a400-6758-11e9-9d48-70a38fd375a1.png)
![image](https://user-images.githubusercontent.com/30310735/56710415-9cfb2b00-6758-11e9-9988-1c21f82e6157.png)
报错了呢

**Comment by xiaoyucoding** [comment]
> > `page->style->mp-weixin->disableSwipBack`
> > 按照这个配置试试呢
> 
> ![image](https://user-images.githubusercontent.com/30310735/56710412-9967a400-6758-11e9-9d48-70a38fd375a1.png)
> ![image](https://user-images.githubusercontent.com/30310735/56710415-9cfb2b00-6758-11e9-9988-1c21f82e6157.png)
> 报错了呢

麻烦贴一下微信小程序关于这个配置的文档说明，另外你这个应该是 VSCode 校验的问题吧，看能不能暂时关闭掉。

**Comment by 0131LWG** [comment]
> > > `page->style->mp-weixin->disableSwipBack`
> > > 按照这个配置试试呢
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/30310735/56710412-9967a400-6758-11e9-9d48-70a38fd375a1.png)
> > ![image](https://user-images.githubusercontent.com/30310735/56710415-9cfb2b00-6758-11e9-9988-1c21f82e6157.png)
> > 报错了呢
> 
> 你这个应该是 VSCode 校验 JSON 文件的问题吧，看能不能暂时关闭掉。你直接编译到微信小程序，看最终生成的代码里面，是不是有 disableSwipeBack 这个配置就行。

报错是说disableSwipeBack无效
![image](https://user-images.githubusercontent.com/30310735/56952058-eccc5e80-6b6b-11e9-8473-b5f1886fd76c.png)

**Comment by zhetengbiji** [comment]
更新微信小程序开发工具
