### ISSUE TITLE
uniapp  vue3的项目，引入其他的npm模块直接报错

### ISSUE THREAD

**Issue by XuJianChen1999** [dcloudio/uni-app#3392]
**问题描述**
[uniapp  vue3的项目，引入其他的npm模块直接报错]

**复现步骤**
[复现问题的步骤]
1. `npm init -y` 初始化项目
2. `npm i packageName --save` 安装依赖
3. import package from 'packageName'

```
// main.js代码
import App from './App'
// import {createPinia} from 'pinia'

// #ifdef VUE3
import {createSSRApp} from 'vue'
import {createStore} from 'vuex'
export function createApp() {
  const app = createSSRApp(App)
	// app.use(createPinia())
	
  return {app}
}
// #endif
```

**预期结果**
[可以使用]

**实际结果**
[直接报错]

![image](https://user-images.githubusercontent.com/98016891/161179395-21bd59ff-28c7-46d4-9af1-10d0e9ab1b76.png)

**系统信息:**
 - 发行平台: [H5平台]
 - HBuilderX版本 [3.3.13]
 - uni-app版本 [最新版本]

**Comment by fxy060608** [comment]
建议描述不太清楚的话，就发测试工程
