### ISSUE TITLE
vite2 使用commonjsOptions 导致循环依赖

### ISSUE THREAD

**Issue by alisafyj** [dcloudio/uni-app#3394]
"@dcloudio/uni-app": "^3.0.0-alpha-3040220220310005"
 "vite": "^2.8.6"
 
`commonjsOptions: {
        include: [/src\/plugins\/.*/]
}`

最终common/vendor.js 中会require 进来这个插件打包的文件，导致循环依赖，目标文件中require   common/vendor.js 输出空对象。

辛苦帮忙回答下这个问题是怎么导致的

**Comment by alisafyj** [comment]
![image](https://user-images.githubusercontent.com/25546018/161191511-3fd34ff0-be80-48d7-959b-29f01c35c557.png)
![image](https://user-images.githubusercontent.com/25546018/161191575-0c7a6241-9766-470e-ab19-8e9155fc7273.png)

**Comment by fxy060608** [comment]
发测试工程
