### ISSUE TITLE
编译微信小程序出错

### ISSUE THREAD

**Issue by aihanjiao** [dcloudio/uni-app#3397]
**问题描述**

用最新官方模板写项目编译微信小程序时出错。  
编译h5正常  

[plugin:vite:vue] Error parsing JavaScript expression:
do
This experimental syntax requires enabling the parser plugin: "doExpressions". (1:0)

C:/Users/ahj/web/gschronic/src/pages/followup/index.vue
1  |  <template>
   |  ^
2  |    <view class='box-border flex flex-col bg-gray-200 h-full w-full'>
3  |

<img width="518" alt="1648848943(1)" src="https://user-images.githubusercontent.com/59612542/161344550-bd8e855b-1f57-4c40-b300-8dc10a171c77.png">

**复现步骤**
编译微信小程序即可出错  
编译h5正常  

**预期结果**
微信小程序编译正常

**系统信息:**
 - 发行平台: [微信小程序、H5平台]
 - 操作系统 win11
 - uni-app版本 3.0.0-alpha-3040320220325006
 - 官方vue3最新模板

**补充信息**
有一个很奇怪的办法：把第286行的uni-easyinput改成input就好了  
复现项目地址：https://gitee.com/aihanjiao/uni-app-bug  master分支

**Comment by fxy060608** [comment]
仓库访问不了，403

**Comment by aihanjiao** [comment]
> 仓库访问不了，403

不好意思，现在可以访问了

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3040420220402002

**Comment by aihanjiao** [comment]
> 已修复，cli更新至：3.0.0-alpha-3040420220402002

感谢修复！
