### ISSUE TITLE
@dcloudio/vite-plugin-uni 使用 vitest 【Unhandled Error】

### ISSUE THREAD

**Issue by JimmyZDD** [dcloudio/uni-app#3398]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
uniapp vue3 vite cli 使用vitest做测试框架，运行 `vitest --environment jsdom` 报错
**复现步骤**
安装：
1、安装依赖
    "@vue/test-utils": "^2.0.0-rc.18",
    "jsdom": "^19.0.0",
    "vitest": "^0.8.1"
2、编写测试

3、运行脚本

**预期结果**
$ vitest --environment jsdom
...
Test Files  3 passed (3)
     Tests  5 passed (5)
      Time  2.26s (in thread 24ms, 9498.12%)
**实际结果**
$ vitest --environment jsdom
failed to load config from  xxx/xxx/vite.config.ts

⎯ Unhandled Error ⎯⎯
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at new NodeError (node:internal/errors:371:5)
    at validateString (node:internal/validators:120:11)
    at Object.join (node:path:1172:7)

**Comment by fxy060608** [comment]
发测试工程

**Comment by JimmyZDD** [comment]
[uni-preset-vue-vite-ts-vitest.zip](https://github.com/dcloudio/uni-app/files/8414883/uni-preset-vue-vite-ts-vitest.zip)

**Comment by fxy060608** [comment]
已支持，cli更新至：3.0.0-alpha-3040420220402004
注意：目前仅支持`--no-threads`模式，不支持多线程
如：`vitest --environment jsdom --no-threads`

**Comment by GGGBB** [comment]
**问题描述**
增加slot插槽 运行 vitest --environment jsdom --no-thread 报错
**视图代码**
<script setup lang="ts">
defineProps<{
  msg: string;
}>();
</script>
<template>
  <div class="greetings">
    <h1 class="green">{{ msg }}</h1>
    
    <slot></slot>
  </div>
</template>
**测试代码**
import { describe, it, expect } from 'vitest'
import { mount } from '@vue/test-utils'
import HelloWorld from '../HelloWorld.vue'
describe('HelloWorld', () => {
  it('renders properly', () => {
    const wrapper = mount(HelloWorld, { props: { msg: 'Hello Vitest' } })
    expect(wrapper.text()).toContain('Hello Vitest')
  })
})
**报错信息**
 FAIL  src/components/__tests__/HelloWorld.spec.ts > HelloWorld > renders properly
TypeError: Cannot read property 'isCE' of null
 ❯ Proxy.renderSlot node_modules/.pnpm/@dcloudio+uni-h5-vue@3.0.0-alpha-3050320220727002/node_modules/@dcloudio/uni-h5-vue/dist/vue.runtime.cjs.js:4246:34
    4244| // the compiler and guaranteed to be a function returning an array
    4245| fallback, noSlotted) {
    4246|     if (currentRenderingInstance.isCE ||
       |                                  ^
    4247|         (currentRenderingInstance.parent &&
    4248|             isAsyncWrapper(currentRenderingInstance.parent) &&
 ❯ Proxy._sfc_render src/components/HelloWorld.vue:21:27
 ❯ renderComponentRoot node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:890:44
 ❯ ReactiveEffect.componentUpdateFn [as fn] node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5508:57
 ❯ ReactiveEffect.run node_modules/.pnpm/@vue+reactivity@3.2.37/node_modules/@vue/reactivity/dist/reactivity.cjs.js:189:25
 ❯ instance.update node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5622:56
 ❯ setupRenderEffect node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5636:9
 ❯ mountComponent node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5418:9
 ❯ processComponent node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5376:17
 ❯ patch node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4978:21

**Comment by GGGBB** [comment]
问题描述
[问题描述：尽可能简洁清晰地把问题描述清楚]
增加slot插槽，运行 vitest --environment jsdom --no-threads 报错
报错信息
src/components/__tests__/HelloWorld.spec.ts > HelloWorld > renders properly
TypeError: Cannot read property 'isCE' of null
 ❯ Proxy.renderSlot node_modules/.pnpm/@dcloudio+uni-h5-vue@3.0.0-alpha-3050320220727002/node_modules/@dcloudio/uni-h5-vue/dist/vue.runtime.cjs.js:4246:34
    4244| // the compiler and guaranteed to be a function returning an array
    4245| fallback, noSlotted) {
    4246|     if (currentRenderingInstance.isCE ||
       |                                  ^
    4247|         (currentRenderingInstance.parent &&
    4248|             isAsyncWrapper(currentRenderingInstance.parent) &&
 ❯ Proxy._sfc_render src/components/HelloWorld.vue:21:27
 ❯ renderComponentRoot node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:890:44
 ❯ ReactiveEffect.componentUpdateFn [as fn] node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5508:57
 ❯ ReactiveEffect.run node_modules/.pnpm/@vue+reactivity@3.2.37/node_modules/@vue/reactivity/dist/reactivity.cjs.js:189:25
 ❯ instance.update node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5622:56
 ❯ setupRenderEffect node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5636:9
 ❯ mountComponent node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5418:9
 ❯ processComponent node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:5376:17
 ❯ patch node_modules/.pnpm/@vue+runtime-core@3.2.37/node_modules/@vue/runtime-core/dist/runtime-core.cjs.js:4978:21

**Comment by pangxtao** [comment]
我想问一下，组件内部用了uni.xx API代码，在测试dom中无法运行，有解决方法么

**Comment by yrmatou** [comment]
> 已支持，cli更新至：3.0.0-alpha-3040420220402004 注意：目前仅支持`--no-threads`模式，不支持多线程 如：`vitest --environment jsdom --no-threads`

这个可以的

**Comment by sunpm** [comment]
> 我想问一下，组件内部用了uni.xx API代码，在测试dom中无法运行，有解决方法么

请问有解决方法了吗？文档也没有写 vitest 怎么测试
