### ISSUE TITLE
微信小程序下：v-for 中 item 未定义 

### ISSUE THREAD

**Issue by newsekaes** [dcloudio/uni-app#340]
**问题描述：怀疑是`v-for`下的编译顺序问题**

**复现步骤**
```
<!-- 出问题的代码 -->
<text v-for="(item, i) in list" v-bind:key="i" >
    {{ item.split('').join(' ') }}
</text>
<!-- 无问题的代码 -->
<text v-for="(item, i) in list" v-bind:key="i" >
    {{ item }}
</text>
```
**预期结果**
两个应该都不会报错

**实际结果**
有问题的代码会报错：
>  [Vue warn]: Property or method "item" is not defined on the instance but referenced during render. Make sure that this property is reactive, either in the data option, or for class-based components, by initializing the property.

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统：mac 本地开发环境
 - HBuilderX版本： 1.9.3.20190422
 - 设备信息 [mbp]

**补充信息**
问题原因猜测一下：
期望的编译顺序：`item.split('').join(' ')`代码块作为一个编辑结果插入`.wxml`文件内，小程序去运行这行代码；
实际的编译顺序：`item.split('').join(' ')`首先被编译运行了，其返回值插入了`.wxml`文件内;

**Comment by newsekaes** [comment]
以下方法可行：
```
<template>
    <text v-for="(item, i) in list" v-bind:key="i" >
        {{ itemText(item) }}
    </text>
</template>
<script>
    export default {
        ....
        methods: {
            itemText() { return item.split('').join(' '); }
        }
    }
<script/>
```

**Comment by xiaoyucoding** [comment]
问题同 [#338](https://github.com/dcloudio/uni-app/issues/338)

**Comment by Fasttian** [comment]
已经修复该问题，请升级到最新版。
