### ISSUE TITLE
vue3项目代码变量无法在微信开发者工具中显示，非常不利于调试

### ISSUE THREAD

**Issue by pengjinlong** [dcloudio/uni-app#3401]
**新功能描述**
希望支持开发者工具端AppData查看变量

**现状及问题**
示例代码：
![image](https://user-images.githubusercontent.com/26454874/161880205-018581bb-a9c4-40bc-ab9d-d4f21111d9df.png)
微信小程序AppData显示如下：
![image](https://user-images.githubusercontent.com/26454874/161880250-f5636bb4-ed04-4fb5-ac52-c0e9f07054cc.png)
可以看到字符串类型虽然可以显示，但是命名已经混淆了。而如果是复杂对象类型，就完全不会显示，调试非常不便。

**尝试方案**
无

**补充信息**
    "@dcloudio/uni-automator": "^3.0.0-alpha-3040220220310005",
    "@dcloudio/uni-cli-shared": "^3.0.0-alpha-3040220220310005",
    "@dcloudio/vite-plugin-uni": "^3.0.0-alpha-3040220220310005",

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/3192
