### ISSUE TITLE
Vue3 setup 在支付宝小程序下 defineProps 不会自动赋值

### ISSUE THREAD

**Issue by iceDays** [dcloudio/uni-app#3402]
**问题描述**
Vue3 setup 在支付宝小程序下 defineProps 不会自动赋值, 微信下正常

**复现步骤**
```
uni.navigateTo({ url: "/pages/detail/detail?type=qrcode" });
```
```

<script setup lang="ts">
import { onLoad } from "@dcloudio/uni-app";

interface Props { 
    type: "none" | "qrcode";
}
const props = withDefaults(defineProps<Props>(), {
  type: "none",
});

onLoad((e) => {
  console.log(e); // {type: "qrcode"}
  console.log(props); //  {type: "none"}
})
</script>
```

**预期结果**
支付宝小程序下 props 变量应输出 '{type: "qrcode"}'

**实际结果**
支付宝小程序下 props 实际输出了 '{type: "none"}'

**系统信息:**
 - 发行平台: 支付宝小程序
 - uni-app版本: ^3.0.0-alpha-3040420220402003

**Comment by fxy060608** [comment]
小程序平台，只有微信小程序支持使用props接收页面参数，其他平台不支持

**Comment by fxy060608** [comment]
已全平台支持，cli更新至：3.0.0-alpha-3040420220402005
