### ISSUE TITLE
无法打包为安卓app

### ISSUE THREAD

**Issue by psrx** [dcloudio/uni-app#3403]
**问题描述**
无法打包为安卓app,报css错误

**复现步骤**
1. 启动HBuilderX
2. 点击发行原生App云打包
3. 控制台刷屏报css错误

**预期结果**
正常打包

**实际结果**
[HBuilder] 10:40:49.193 [33m[plugin:vite:css] ERROR: property value `auto` is not supported for `margin-left` (only number and pixel values are supported)
[HBuilder] 10:40:49.194 3032|  }
[HBuilder] 10:40:49.196 3033|  .mx-auto {
[HBuilder] 10:40:49.198 3034|    margin: 0 auto;
[HBuilder] 10:40:49.199    |     ^
[HBuilder] 10:40:49.201 3035|  }

**系统信息:**
 - 发行平台: [安卓App]
 - HBuilderX版本 [3.3.13)]
 - uni-app版本 [3.0.0-alpha-3040320220325006]

**补充信息**
从css角度来说完全是正常的,这个错误不合理...
我不记得文档中有说过不能使用auto

**Comment by fxy060608** [comment]
nvue不支持
可以使用`APP-NVUE`或`APP-VUE`的条件编译做规避

**Comment by psrx** [comment]
> nvue不支持 可以使用`APP-NVUE`或`APP-VUE`的条件编译做规避

但是我并没有主动的使用nvue
还是说打包为安卓app时默认使用nvue?

**Comment by psrx** [comment]
> nvue不支持 可以使用`APP-NVUE`或`APP-VUE`的条件编译做规避

/* 5+App特有相关 */
    "app-plus" : {
        "usingComponents" : true,
        "nvueStyleCompiler" : "uni-app",
        "compilerVersion" : 3,
        "splashscreen" : {
            "alwaysShowBeforeRender" : true,
            "waiting" : true,
            "autoclose" : true,
            "delay" : 0
        },

**Comment by fxy060608** [comment]
你的这些样式是在App.vue中使用的吧
可以先使用条件编译规避掉，稍后修复未使用nvue时，仍报错的问题
```css
/* #ifdef APP-VUE */
    .mx-auto {
        margin: 0 auto;
    }
    /* #endif */
```

**Comment by psrx** [comment]
> 你的这些样式是在App.vue中使用的吧 可以先使用条件编译规避掉，稍后修复未使用nvue时，仍报错的问题
> 
> ```css
> /* #ifdef APP-VUE */
>     .mx-auto {
>         margin: 0 auto;
>     }
>     /* #endif */
> ```

感谢

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3040420220402006

**Comment by psrx** [comment]
> 3040420220402006

链接: https://pan.baidu.com/s/1dayUlkLYD707Eq-wP5RMeA 提取码: dbcy 复制这段内容后打开百度网盘手机App，操作更方便哦

不知道为啥还是不行...你方便的话可以帮我瞅一眼吗

**Comment by fxy060608** [comment]
> > 3040420220402006
> 
> 链接: https://pan.baidu.com/s/1dayUlkLYD707Eq-wP5RMeA 提取码: dbcy 复制这段内容后打开百度网盘手机App，操作更方便哦
> 
> 不知道为啥还是不行...你方便的话可以帮我瞅一眼吗

package.json中的版本没有全部升级到`3.0.0-alpha-3040420220402006`

**Comment by psrx** [comment]
> > > 3040420220402006
> > 
> > 
> > 链接: https://pan.baidu.com/s/1dayUlkLYD707Eq-wP5RMeA 提取码: dbcy 复制这段内容后打开百度网盘手机App，操作更方便哦
> > 不知道为啥还是不行...你方便的话可以帮我瞅一眼吗
> 
> package.json中的版本没有全部升级到`3.0.0-alpha-3040420220402006`

感谢,项目npm和pnpm都支持了,我之前只升级了pnpm的...现在可以了
