### ISSUE TITLE
App.vue 中定义的全局 provide 不生效

### ISSUE THREAD

**Issue by Miofly** [dcloudio/uni-app#3404]
文件 constants.ts
```
export const keySym = Symbol();
```

App.vue
```
import { keySym } from '@/constants';

let myValue = ref('myValue的测试');

function createCheckboxContext () {
     provide(keySym, myValue);
}

createCheckboxContext();
```

index.vue
```
import { keySym } from '@/constants';
function useCheckboxContext () {
     return inject(keySym);
}

console.log(useCheckboxContext());
```
如以上代码所示，目的是使用 `Symbol` 作为 `key` 值作为唯一标识，现在的问题是在 H5 上 `useCheckboxContext()` 能够打印出 `provide` 提供的值，在微信小程序上是 `undefined`

**Comment by Miofly** [comment]
当然不使用 Symbol 在小程序上是正常的，但是为什么会出现这种差异

**Comment by fxy060608** [comment]
建议如果是想全局provide，应该使用app.provide方式

**Comment by Miofly** [comment]
> 建议如果是想全局provide，应该使用app.provide方式

好的，希望早点修复，我的应用场景是两个组件相互使用，上面是我测试时使用的代码

**Comment by fxy060608** [comment]
> > 建议如果是想全局provide，应该使用app.provide方式
> 
> 好的，希望早点修复，我的应用场景是两个组件相互使用，上面是我测试时使用的代码

两个组件相互使用有什么问题吗？你给的示例不行，是因为provide是在App.vue中定义导致的

**Comment by Miofly** [comment]
> function useCheckboxContext () {
>      return inject(keySym);
> }

```
import { InjectionKey } from 'vue';

const key: InjectionKey<any> = Symbol();

export function useContext () {
	return inject(key);
}

export function createContext (val) {
	return provide(key, val);
}
```

组件一
```
<template>
	<view>
		<Child />
	</view>
</template>

<script setup lang="ts">
	import { createContext } from '@/views/home/test';
	import Child from './test-child.vue';

	let test = ref('测试数据');
	createContext(test);

</script>

<style lang="less" scoped>
	.text {
		color: #27b6ff
	}
</style>
```

组件二
```
<template>
	<view>
		这是子组件
	</view>
</template>

<script setup lang="ts">
	import { useContext } from '@/views/home/test';

	console.log(useContext());
</script>
```

**Comment by fxy060608** [comment]
> > function useCheckboxContext () {
> > return inject(keySym);
> > }
> 
> `test.ts`-->单独的 `context.ts` 文件，下面两个组件都从这里引入
> 
> ```
> import { InjectionKey } from 'vue';
> 
> const key: InjectionKey<any> = Symbol();
> 
> export function useContext () {
> 	return inject(key);
> }
> 
> export function createContext (val) {
> 	return provide(key, val);
> }
> ```
> 
> 组件一
> 
> ```
> <template>
> 	<view>
> 		<Child />
> 	</view>
> </template>
> 
> <script setup lang="ts">
> 	import { createContext } from '@/views/home/test';
> 	import Child from './test-child.vue';
> 
> 	let test = ref('测试数据');
> 	createContext(test);
> 
> </script>
> 
> <style lang="less" scoped>
> 	.text {
> 		color: #27b6ff
> 	}
> </style>
> ```
> 
> 组件二 `test-child.vue`
> 
> ```
> <template>
> 	<view>
> 		这是子组件
> 	</view>
> </template>
> 
> <script setup lang="ts">
> 	import { useContext } from '@/views/home/test';
> 
> 	console.log(useContext());
> </script>
> ```
> 
> 微信小程序的提示 ![image](https://user-images.githubusercontent.com/42859910/162143178-b3ba2a2f-b0be-4163-80ab-8376b3207758.png) H5 正常输出 ![image](https://user-images.githubusercontent.com/42859910/162143274-7034f9e0-b1cb-4ac2-8d8e-042e4e8c86a4.png)

测试没有问题，如果有问题，发完整的测试工程

**Comment by Miofly** [comment]
升级版本后正常
