### ISSUE TITLE
vue3，editor 的 ready 事件会导致一些事件绑定提前触发

### ISSUE THREAD

**Issue by appleone123** [dcloudio/uni-app#3406]
**问题描述**
editor 绑定了 ready 后，会导致存在 v-if 条件，且 v-if 的条件在 onLoad 中修改的元素上面绑定的事件在页面加载时提前触发（HBuilder 和 cli 在 vue3 下均可复现）
**复现步骤**
HBuilder 新建一个最简单的示例工程，采用 vue3
共有两个页面，主页代码如下：
```
<template>
	<view class="content">
		<image class="logo" src="/static/logo.png"></image>
		<view class="text-area">
			<text class="title">{{title}}</text>
		</view>
		<button @tap="jump"> click me </button>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				title: 'Hello'
			}
		},
		onLoad() {

		},
		methods: {
			jump(){
				uni.navigateTo({
					url:'../apple/index?apple=1111'
				})
			}
		}
	}
</script>

<style>
	.content {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
	}

	.logo {
		height: 200rpx;
		width: 200rpx;
		margin-top: 200rpx;
		margin-left: auto;
		margin-right: auto;
		margin-bottom: 50rpx;
	}

	.text-area {
		display: flex;
		justify-content: center;
	}

	.title {
		font-size: 36rpx;
		color: #8f8f94;
	}
</style>
```
跳转页代码如下：
```
<template>
	<view v-if="apple" @tap="tapHandler">
		
	</view>
	<editor @ready="editorReadyHandler"></editor>
</template>

<script>
	export default {
		data() {
			return {
				apple: ''
			}
		},
		methods: {
			tapHandler() {
				console.log('this is tapHandler')
			},
			editorReadyHandler(){}
		},
		onLoad(query) {
			this.apple = query.apple
		}
	}
</script>

<style>

</style>
```
将代码运行起来，即可看到本该点击才输出的 log ：“this is tapHandler” 在页面加载后就会输出

**预期结果**
事件正确触发

**实际结果**
事件被提前触发

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本 3.4.4.20220403-alpha

**补充信息**
cli 复现场景的依赖：
dependencies：
    "@dcloudio/uni-app": "^3.0.0-alpha-3040320220325005",
    "@dcloudio/uni-app-plus": "^3.0.0-alpha-3040320220325005",
    "@dcloudio/uni-components": "^3.0.0-alpha-3040320220325005",
    "@dcloudio/uni-h5": "^3.0.0-alpha-3040320220325005",
    "@dcloudio/uni-mp-alipay": "^3.0.0-alpha-3040320220325005",
    "@dcloudio/uni-mp-baidu": "^3.0.0-alpha-3040320220325005",
    "@dcloudio/uni-mp-kuaishou": "^3.0.0-alpha-3040320220325005",
    "@dcloudio/uni-mp-lark": "^3.0.0-alpha-3040320220325005",
    "@dcloudio/uni-mp-qq": "^3.0.0-alpha-3040220220310004",
    "@dcloudio/uni-mp-toutiao": "^3.0.0-alpha-3040320220325005",
    "@dcloudio/uni-mp-weixin": "^3.0.0-alpha-3040320220325005",
    "@dcloudio/uni-quickapp-webview": "^3.0.0-alpha-3040320220325005",
    "@dcloudio/uni-ui": "^1.4.13",
devDependencies：
    "@dcloudio/types": "^2.5.17",
    "@dcloudio/uni-automator": "^3.0.0-alpha-3040320220325005",
    "@dcloudio/uni-cli-shared": "^3.0.0-alpha-3040320220325005",
    "@dcloudio/vite-plugin-uni": "^3.0.0-alpha-3040320220325005",

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3040520220408002

**Comment by appleone123** [comment]
> 3.0.0-alpha-3040520220408002

HBuilder 更新至 3.4.5.20220408-alpha 版本，采用上述代码示例仍可复现该问题。
vu3 cli 工程，更新至 3.0.0-alpha-3040520220408002，仍然可以复现该问题。
cli 工程依赖列表：
dependencies：

    "@dcloudio/uni-app": "^3.0.0-alpha-3040520220408002",
    "@dcloudio/uni-app-plus": "^3.0.0-alpha-3040520220408002",
    "@dcloudio/uni-components": "^3.0.0-alpha-3040520220408002",
    "@dcloudio/uni-h5": "^3.0.0-alpha-3040520220408002",
    "@dcloudio/uni-mp-alipay": "^3.0.0-alpha-3040520220408002",
    "@dcloudio/uni-mp-baidu": "^3.0.0-alpha-3040520220408002",
    "@dcloudio/uni-mp-kuaishou": "^3.0.0-alpha-3040520220408002",
    "@dcloudio/uni-mp-lark": "^3.0.0-alpha-3040520220408002",
    "@dcloudio/uni-mp-qq": "^3.0.0-alpha-3040520220408002",
    "@dcloudio/uni-mp-toutiao": "^3.0.0-alpha-3040520220408002",
    "@dcloudio/uni-mp-weixin": "^3.0.0-alpha-3040520220408002",
    "@dcloudio/uni-quickapp-webview": "^3.0.0-alpha-3040520220408002",
devDependencies：

    "@dcloudio/types": "^2.5.17",
    "@dcloudio/uni-automator": "^3.0.0-alpha-3040520220408002",
    "@dcloudio/uni-cli-shared": "^3.0.0-alpha-3040520220408002",
    "@dcloudio/vite-plugin-uni": "^3.0.0-alpha-3040520220408002",

**Comment by fxy060608** [comment]
> > 3.0.0-alpha-3040520220408002
> 
> HBuilder 更新至 3.4.5.20220408-alpha 版本，采用上述代码示例仍可复现该问题。 vu3 cli 工程，更新至 3.0.0-alpha-3040520220408002，仍然可以复现该问题。 cli 工程依赖列表： dependencies：
> 
> ```
> "@dcloudio/uni-app": "^3.0.0-alpha-3040520220408002",
> "@dcloudio/uni-app-plus": "^3.0.0-alpha-3040520220408002",
> "@dcloudio/uni-components": "^3.0.0-alpha-3040520220408002",
> "@dcloudio/uni-h5": "^3.0.0-alpha-3040520220408002",
> "@dcloudio/uni-mp-alipay": "^3.0.0-alpha-3040520220408002",
> "@dcloudio/uni-mp-baidu": "^3.0.0-alpha-3040520220408002",
> "@dcloudio/uni-mp-kuaishou": "^3.0.0-alpha-3040520220408002",
> "@dcloudio/uni-mp-lark": "^3.0.0-alpha-3040520220408002",
> "@dcloudio/uni-mp-qq": "^3.0.0-alpha-3040520220408002",
> "@dcloudio/uni-mp-toutiao": "^3.0.0-alpha-3040520220408002",
> "@dcloudio/uni-mp-weixin": "^3.0.0-alpha-3040520220408002",
> "@dcloudio/uni-quickapp-webview": "^3.0.0-alpha-3040520220408002",
> ```
> 
> devDependencies：
> 
> ```
> "@dcloudio/types": "^2.5.17",
> "@dcloudio/uni-automator": "^3.0.0-alpha-3040520220408002",
> "@dcloudio/uni-cli-shared": "^3.0.0-alpha-3040520220408002",
> "@dcloudio/vite-plugin-uni": "^3.0.0-alpha-3040520220408002",
> ```

如果确认更新后，还有问题，可以临时在onLoad中延迟赋值，或onReady中赋值试试

**Comment by appleone123** [comment]
> > > 3.0.0-alpha-3040520220408002
> > 
> > 
> > HBuilder 更新至 3.4.5.20220408-alpha 版本，采用上述代码示例仍可复现该问题。 vu3 cli 工程，更新至 3.0.0-alpha-3040520220408002，仍然可以复现该问题。 cli 工程依赖列表： dependencies：
> > ```
> > "@dcloudio/uni-app": "^3.0.0-alpha-3040520220408002",
> > "@dcloudio/uni-app-plus": "^3.0.0-alpha-3040520220408002",
> > "@dcloudio/uni-components": "^3.0.0-alpha-3040520220408002",
> > "@dcloudio/uni-h5": "^3.0.0-alpha-3040520220408002",
> > "@dcloudio/uni-mp-alipay": "^3.0.0-alpha-3040520220408002",
> > "@dcloudio/uni-mp-baidu": "^3.0.0-alpha-3040520220408002",
> > "@dcloudio/uni-mp-kuaishou": "^3.0.0-alpha-3040520220408002",
> > "@dcloudio/uni-mp-lark": "^3.0.0-alpha-3040520220408002",
> > "@dcloudio/uni-mp-qq": "^3.0.0-alpha-3040520220408002",
> > "@dcloudio/uni-mp-toutiao": "^3.0.0-alpha-3040520220408002",
> > "@dcloudio/uni-mp-weixin": "^3.0.0-alpha-3040520220408002",
> > "@dcloudio/uni-quickapp-webview": "^3.0.0-alpha-3040520220408002",
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > devDependencies：
> > ```
> > "@dcloudio/types": "^2.5.17",
> > "@dcloudio/uni-automator": "^3.0.0-alpha-3040520220408002",
> > "@dcloudio/uni-cli-shared": "^3.0.0-alpha-3040520220408002",
> > "@dcloudio/vite-plugin-uni": "^3.0.0-alpha-3040520220408002",
> > ```
> 
> 如果确认更新后，还有问题，可以临时在onLoad中延迟赋值，或onReady中赋值试试

由于需要使用路由参数，已临时通过在 onLoad 中延迟赋值解决，还望尽快修复，感谢！
