### ISSUE TITLE
uni-request的方法内的header对象要怎么删除content-type属性  因为业务需要 不然发get请求总是没有数据

### ISSUE THREAD

**Issue by lovehebe330** [dcloudio/uni-app#3407]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
uni-reques文档有提供可以删除header对象content-type属性的方法吗

**预期结果**
可以删除content-type属性

**实际结果**
[这里请贴上你的报错截图或文字]

**Comment by zhetengbiji** [comment]
目前的实现可以修改，不可删除。描述一下具体的问题。

**Comment by lovehebe330** [comment]
就是接口每次发get请求微信开发者工具返回的response总是 this request has no response data available，post请求是有数据的，后端说要将content-type属性删除后 get请求才能正常返回数据 
![QQ图片20220408140935](https://user-images.githubusercontent.com/20655248/162375322-537f328b-4789-4269-a735-f41d9b85fb71.png)
