### ISSUE TITLE
支付宝template render数据异常

### ISSUE THREAD

**Issue by okxiaoliang4** [dcloudio/uni-app#3408]
**问题描述**
在支付宝端循环组件内嵌套[mp-html组件](https://github.com/jin-yufeng/mp-html/blob/master/dist/uni-app/components/mp-html/mp-html.vue)，[mp-html组件](https://github.com/jin-yufeng/mp-html/blob/master/dist/uni-app/components/mp-html/mp-html.vue)中`nodes` 在 n+1 组件中template渲染为空数组，通过watch监听data中的nodes数组，发现都是有内容的，但是在模板上却是空数组。尝试用最小demo复现不出来，不知道给的信息能否定位到问题，是否需要更多内容？

![image](https://user-images.githubusercontent.com/22525904/162355394-124b47d7-da7d-4334-b152-ba12ba2c4874.png)

在编译后的组件render function中输出是正常的数组内容
```js
function _sfc_render(_ctx, _cache, $props, $setup, $data, $options) {
  console.log($data.nodes) // 这里输出是正常的数组内容
  return common_vendor.e({
    a: !$data.nodes[0]
  }, !$data.nodes[0] ? {} : {
    b: common_vendor.p({
      childs: $data.nodes,
      opts: [$props.lazyLoad, $props.loadingImg, $props.errorImg, $props.showImgMenu],
      name: "span"
    })
  }, {
    c: common_vendor.n(($props.selectable ? "_select " : "") + "_root"),
    d: common_vendor.s($props.containerStyle)
  });
}
```

**复现步骤**

**预期结果**
render正常显示内容

**实际结果**
数组为空

**系统信息:**
 - 支付宝小程序
 - uni-app@^3.0.0-alpha-3040420220402005

**补充信息**
可能是底层`setData`的时候出现问题？

**Comment by fxy060608** [comment]
发测试工程

**Comment by okxiaoliang4** [comment]
> 发测试工程

render的时候是有数据的，但是视图上没更新
![image](https://user-images.githubusercontent.com/22525904/162356569-4292f95a-3c82-4e33-9a78-305be7c209e9.png)

demo无法复现。。我再提供一下debug信息，看看能否有帮助，我也再尝试demo复现一下

**Comment by fxy060608** [comment]
> > 发测试工程
> 
> render的时候是有数据的，但是视图上没更新 ![image](https://user-images.githubusercontent.com/22525904/162356569-4292f95a-3c82-4e33-9a78-305be7c209e9.png)
> 
> demo无法复现。。我再提供一下debug信息，看看能否有帮助，我也再尝试demo复现一下

没有具体的测试工程，很难排查问题

**Comment by okxiaoliang4** [comment]
https://github.com/okxiaoliang4/uni-bug-report
@fxy060608 复现了~麻烦帮忙看看

**Comment by fxy060608** [comment]
> https://github.com/okxiaoliang4/uni-bug-report @fxy060608 复现了~麻烦帮忙看看

访问404

**Comment by okxiaoliang4** [comment]
> > https://github.com/okxiaoliang4/uni-bug-report @fxy060608 复现了~麻烦帮忙看看
> 
> 访问404

sorry，刚刚是private的，现在改成public了~

**Comment by fxy060608** [comment]
> https://github.com/okxiaoliang4/uni-bug-report

没看出来哪里有问题，详细说明下

**Comment by okxiaoliang4** [comment]
![image](https://user-images.githubusercontent.com/22525904/162375796-29e8e43e-487e-40d0-bd59-fbbe27a7a43f.png)

![image](https://user-images.githubusercontent.com/22525904/162376198-a5d1b694-e87e-4ebb-bd26-e678adc19766.png)

与页面上的数据对应不上，n+1个的时候会消失，只在支付宝小程序这样，微信小程序和H5都ok的

**Comment by okxiaoliang4** [comment]
具体一点定位到问题就是mp-html组件nodes变量在render的时候数组还是有值的，但是在视图层上获取到的却是空数组

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3040520220408002
