### ISSUE TITLE
[uni-app vite] manifest.json 中的配置影响范围错误

### ISSUE THREAD

**Issue by aimergenge** [dcloudio/uni-app#3409]
**问题描述**
在 manifest 中，配置 h5 如下：
```
"h5": {
  "publicPath": "/m/",
  "router": {
    "base": "/m/",
    "mode": "history"
  }
},
```
结果 `yarn dev:mp-weixin` 时，import 资源路径错误，路径中多了 `/m/`，说明错误地使用了 h5 的配置。

**复现步骤**
复现仓库：https://github.com/aimergenge/uni-vite-repro

1. yarn && yarn dev:mp-weixin
2. 打开微信开发者工具，查看`index.vue` 中打印出的地址

**预期结果**
地址中不应该包含 `/m/`

**实际结果**
包含了 `/m/`

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 macOS Manterey 12.13.1
 - uni-app版本 3.0.0-alpha-3031320220314002

**Comment by fxy060608** [comment]
该问题已修复：https://github.com/dcloudio/uni-app/issues/3362
