### ISSUE TITLE
关于rich-text不兼容问题

### ISSUE THREAD

**Issue by BigBigBao** [dcloudio/uni-app#341]
rich-text富文本组件在支付宝小程序上无法成功渲染，从调试中得知数据是已经正常请求到，应该还是渲染的问题，请修复

**Comment by xiaoyucoding** [comment]
支付宝小程序的 rich-text 组件是后面才支持的，而且和其它平台肯定有一定的差异。
你可以新建一个支付宝小程序的项目，然后用 rich-text 直接渲染数据结果，看是否正常。

**Comment by BigBigBao** [comment]
> 支付宝小程序平台自身的富文本组件是后面才支持的，而且和其它平台存在一定的
> 差异。你可以新建一个支付宝小程序的项目，然后用rich-text直接渲染数据结果，看是否正常。
新建了一个支付宝项目并直接拿了一个有效的新闻id去请求（官方视频新闻demo中的接口），请求数据是成功的，依旧没有渲染出来

**Comment by BigBigBao** [comment]
新建了一个支付宝项目并直接拿了一个有效的新闻ID去请求（官方视频新闻演示中的接口），请求数据是成功的，依旧没有渲染出来

**Comment by xiaoyucoding** [comment]
> 新建了一个支付宝项目并直接拿了一个有效的新闻ID去请求（官方视频新闻演示中的接口），请求数据是成功的，依旧没有渲染出来

支付宝小程序引擎自身的实现问题，可以去支付宝小程序的社区反馈下。
