### ISSUE TITLE
[uni-app vite 版本] page选择器的表现与之前不一致

### ISSUE THREAD

**Issue by aimergenge** [dcloudio/uni-app#3410]
在之前的版本（非vite）中，设置页面的颜色，我们一直使用的是 `<style> page { ... } </style>`（注意它没有 `scoped`），这样无论在 h5 还是微信小程序都是正常的。
在 h5 下，它会渲染成：
```
body.pagesxxxx-xxx-xxxx { ... }
```
而路由切换时，uniapp会自动切换 body上的这个类名，以保证样式正确呈现。
在小程序下，它会渲染成：
```
page { ... }
```
小程序的页面是独立的渲染上下文（webview)，因此这样没有问题。

而在新版 （vite）中，我似乎无法沿用这种方式。采用上述写法的情况下，小程序是正常的，但 h5 下，编译出的样式不带类名：
```
body { ... }
```
因此page上的样式会相互覆盖而错乱。
如果我采用带 `scoped` 的写法呢，这时 h5 是正常的，但小程序的样式因为带了 `scoped` 而变成了：
```
page.data-v-xxx
```
而page标签没有任何class，这显然无法正常工作。

我尝试在开发者工具中给小程序的page标签手动添加 `data-v-xxx` 类名，但是好像不起作用，大概小程序的 page 标签根本就不支持自定义class。因此我倾向于恢复成之前的方案。

重现仓库：https://github.com/aimergenge/uni-vite-repro

**Comment by fxy060608** [comment]
你说的问题是不是打开新页面时，背景样式是正确的，但是页面后退后，背景样式不正确？

**Comment by fxy060608** [comment]
临时方案：只使用一个style标签，且不带scoped

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3040520220408002
