### ISSUE TITLE
vite构建的项目，在h5的 history 模式下，自带的vue-router路由有bug，重复跳转及后退后，路由会报错无法回退到首页

### ISSUE THREAD

**Issue by yeyifen** [dcloudio/uni-app#3414]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
vite构建的项目，在h5的 history 模式下，自带的vue-router路由有bug，重复跳转及后退后，路由会报错无法回退到首页
**复现步骤**
[复现问题的步骤]
1.  h5路由模式配置为 history
2. 启动 'npm run dev:h5'，并配置一个子页面 /pages/a
3. 通过 this.$router.push('/pages/a')  跳到该页面
4. 用 uniapp生成的标题栏左上角的返回键（或直接用this.$router.back() ）到首页
5. 重复步骤3跟4，大概重复2-3次问题就会出现

**预期结果**
能正常回退到首页

**实际结果**
无法回退到首页，并且浏览器控制台会报错：
uni-h5.es.js:14112 Uncaught TypeError: Cannot read properties of undefined (reading '$page')
    at removeCurrentPages (uni-h5.es.js:14112:26)

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 pc chrome浏览器
 - HBuilderX版本vue-cli模式
 - uni-app版本：按官网文档通过 npx degit dcloudio/uni-preset-vue#vite my-vue3-project  创建的项目
 - 设备信息 pc

**补充信息**
[根据你的分析，出现这个问题的原因可能在哪里？]
在重复步骤3  4 时，同时在控制台打印  getCurrentPages()，发现路由栈数组一直在减少，并不会通过跳转新页面而增加，到报错出现时路由栈数组长度已经为 0 。

**Comment by fxy060608** [comment]
请使用 uni 的路由 API

**Comment by yeyifen** [comment]
我这个有部分是从旧项目迁移过来的，我想继续复用 this.$router.push, 如果直接用uni的路由api，改动会很大，尝试过自己重写一个 this.$router，发现会被uni自己添加的vue-router覆盖掉，或者能否提供方法能禁用掉uni自带的vue-router？

**Comment by fxy060608** [comment]
> 我这个有部分是从旧项目迁移过来的，我想继续复用 this.$router.push, 如果直接用uni的路由api，改动会很大，尝试过自己重写一个 this.$router，发现会被uni自己添加的vue-router覆盖掉，或者能否提供方法能禁用掉uni自带的vue-router？

不能禁用，h5端的路由跳转基于vue-router实现

**Comment by yeyifen** [comment]
好吧，看来只能用回旧版的uniapp了

**Comment by SilurianYang** [comment]
你可以直接选择使用 [uni-simple-router](https://v3.hhyang.cn/) 它是一款专为 Uni App 量身定制的路由插件，提供无缝集成的特性，使得路由管理变得简单而高效。
