### ISSUE TITLE
uni-app配置navigationBarBackgroundColor导航栏背景颜色支持配置渐变色吗

### ISSUE THREAD

**Issue by lovehebe330** [dcloudio/uni-app#3415]
**问题描述**
要将导航栏的背景色配置成渐变色 background: linear-gradient(140deg, #5CB78C 0%, #36A793 100%);
![image](https://user-images.githubusercontent.com/20655248/162554136-672cef6c-3362-4faf-b378-909733a63321.png)
![image](https://user-images.githubusercontent.com/20655248/162554142-8a69d78c-3ff2-4e8c-b223-951ec6e0b7a7.png)
但是报错了 要怎么解决

**Comment by hzh1990** [comment]
{
          "path": "index",
          "style": {
            "navigationStyle": "custom",
            "navigationBarTitleText": ""
          }
        }

然后自己写自定义的navigation

**Comment by novemberzhuababa** [comment]
请问解决了吗？？
