### ISSUE TITLE
vue3  qq 小程序 webview 无法正常打开网页

### ISSUE THREAD

**Issue by appleone123** [dcloudio/uni-app#3419]
**问题描述**
vue3+cli / HbuilderX 创建的 vue3 示例工程均可复现，使用 webview 打开任一网址，在真机上表现为白屏，无法正确加载网页内容或者显示不支持打开非业务域名的错误图片，绑定的 load 和 error 事件均不触发，vue2 则正常

**复现步骤**
[复现问题的步骤]
1.  使用 HbuilderX 创建一个最简单的示例工程，采用 vue3
2. 创建 webpage 页面，页面代码如下：
```
<template>
	<web-view :src="webUrl" @error="handleError" @load="handleLoad"></web-view>
</template>

<script>
	export default {
		data() {
			return {
				webUrl: ''
			}
		},
		onLoad(query) {
			this.webUrl = query?.url
		},
		methods: {
			handleError(e){
				console.log('this is error',e)
				uni.showToast({
					title:'webpage error'
				})
			},
			handleLoad(){
				console.log('this is loaded')
				uni.showToast({
					title:'webpage loaded'
				})
			}
		}
	}
</script>

<style>

</style>

```
3. 在 index 页面中增加 navigator 组件，进行 webview 跳转：
```
<template>
	<view class="content">
		<image class="logo" src="/static/logo.png"></image>
		<view class="text-area">
			<text class="title">{{title}}</text>
		</view>
		<navigator open-type="navigate" url="/pages/webpage/webpage?url=https://www.baidu.com">打开百度</navigator>
		<navigator open-type="navigate" url="/pages/webpage/webpage?url=https://www.bing.com">打开bing</navigator>
		<navigator open-type="navigate" url="/pages/webpage/webpage?url=https://q.qq.com/">打开QQ</navigator>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				title: 'Hello'
			}
		},
		onLoad() {

		},
		methods: {

		}
	}
</script>

<style>
	.content {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
	}

	.logo {
		height: 200rpx;
		width: 200rpx;
		margin-top: 200rpx;
		margin-left: auto;
		margin-right: auto;
		margin-bottom: 50rpx;
	}

	.text-area {
		display: flex;
		justify-content: center;
	}

	.title {
		font-size: 36rpx;
		color: #8f8f94;
	}
</style>

```
5. 编译后在真机查看，iOS 和 Android 真机均无法正常展示 webview 内容

**预期结果**
webview 可以正常展示网页内容或者不支持打开非业务域名的错误图片

**实际结果**
iPhone：
![image](https://user-images.githubusercontent.com/18554629/162682075-f16d4bd9-156d-44c7-acad-e9425456b327.png)
Android：
![image](https://user-images.githubusercontent.com/18554629/162682105-ca109674-3891-48d4-8b55-1ac4a5c417b5.png)

**系统信息:**
 - 发行平台: QQ 小程序
 - 操作系统 ：iOS 15.4.1 Android 11
 - HBuilderX版本 3.4.5.20220408-alpha
 - 设备信息：iPhone XS，魅族 18 Pro。
 - QQ 版本：Android：8.8.85.7685。 iOS：8.8.85.636

**补充信息**
可以确定并非网络环境问题，QQ App 版本均为双平台应用商店最新版本。同一代码，同样通过 HBuilderX 创建同一个示例工程，区别因为采用 vue2，则webview 功能均正常

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/2648

**Comment by fxy060608** [comment]
已修复，cli可以更新至：3.0.0-alpha-3040520220413001
