### ISSUE TITLE
1.9.3版本在安卓9.0中无法使用uni.downloadFile+plus.runtime.install

### ISSUE THREAD

**Issue by 74jian** [dcloudio/uni-app#342]
**问题描述**
```
uni.downloadFile({  
	url: res.installUrl,  
	success: (downloadResult) => {  
		if (downloadResult.statusCode === 200) {  
			plus.runtime.install(downloadResult.tempFilePath, {  
				force: false  
			}, function() {
				plus.runtime.restart();  
			}, function(e) {  
				console.error('install fail...');  
			});  
		}  
	},
	fail: (error) =>{
		plus.nativeUI.toast('下载更新失败，请尝试手动安装')
		plus.runtime.openURL(res.installUrl);
	}  
}); 
```
以上代码在其他版本中运行正常，在安卓9.0的机器中下载没有执行，且直接返回了`"statusCode“:200`，并进入了plus.runtime.install的安装成功方法里，导致如果用户去做更新操作就会直接重启应用

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 Android 9.0
 - HBuilderX版本 1.9.3
 - uni-app版本 如上
 - 设备信息 华为P20，P20 pro，小米8，小米8青春版，vivo NEX等安卓9.0的机型

**补充信息**
如果启用downloadTask方法监听进度，且在方法里打印返回值`console.log(res.totalBytesWritten)`，就会执行下载的操作(如果不打印返回值，依然不会执行下载)，但install会直接进入fail方法

以上，谢谢

**Comment by zhetengbiji** [comment]
自 HBuilderX 1.9.4.20190426 版本修复此问题
