### ISSUE TITLE
vite，vue3；vue-router.esm-bundler.js:2489 报Uncaught (in promise) TypeError: api.now is not a function

### ISSUE THREAD

**Issue by hzh1990** [dcloudio/uni-app#3421]
**问题描述**
vite，vue3；vue-router.esm-bundler.js:2489 报Uncaught (in promise) TypeError: api.now is not a function

**复现步骤**
版本 3.0.0-alpha-3040420220402003

**预期结果**
正常跳转页面

**实际结果**
<img width="1406" alt="image" src="https://user-images.githubusercontent.com/4394948/162689769-b3e2bd0e-8bfe-4ad6-9027-dd4b7183db5c.png">
<img width="725" alt="image" src="https://user-images.githubusercontent.com/4394948/162689802-f97b2ffd-5b13-46a4-8a82-d6a742988741.png">

**系统信息:**
 - 发行平台: H5平台

**Comment by fxy060608** [comment]
请描述重现问题的步骤

**Comment by hzh1990** [comment]
> 请描述重现问题的步骤

有时候有有时候没有。蛋疼

**Comment by hzh1990** [comment]
> 请描述重现问题的步骤

我先关了，在有我在发个demo出来

**Comment by virgosoy** [comment]
可以看看 https://github.com/vuejs/router/issues/1338
