### ISSUE TITLE
video组件的id疑问

### ISSUE THREAD

**Issue by llk2yq** [dcloudio/uni-app#3423]
环境：`vue3` + `vite`，微信小程序环境。

1、当`video`直接是页面的子组件时，id是正常的。
2、当`video`是页面的**孙子组件**（组件内的组件）时，id不正常，具体表现如下：
```html
<video id="test" class="qst-video" />
```
![image](https://user-images.githubusercontent.com/22813922/162899659-0d521955-57ea-498a-b257-27cfb00726f9.png)
也就是说，id会**多一串随机的前缀**，导致无法通过id去`createVideoContext`，又因为不能通过`ref`获取内部组件，所以就很难对这个视频进行操作（播放、暂停等）。

不知道这个现象是bug还是微信特性如此。

以及如何才能在子组件中控制video？

**Comment by fxy060608** [comment]
未重现，发测试工程

**Comment by llk2yq** [comment]
[test-video.zip](https://github.com/dcloudio/uni-app/files/8470502/test-video.zip)
可以试试这个测试项目，在微信开发者工具（最新RC版）中可以查看到。

**Comment by llk2yq** [comment]
@fxy060608

**Comment by fxy060608** [comment]
测试没有问题

```html
<template>
    <div class="my-c">
        <video
            src="https://img.cdn.aliyun.dcloud.net.cn/guide/uniapp/%E7%AC%AC1%E8%AE%B2%EF%BC%88uni-app%E4%BA%A7%E5%93%81%E4%BB%8B%E7%BB%8D%EF%BC%89-%20DCloud%E5%AE%98%E6%96%B9%E8%A7%86%E9%A2%91%E6%95%99%E7%A8%8B@20181126-lite.m4v"
            id="test"
        ></video>
        <button @click="play">播放</button>
        <button @click="pause">暂停</button>
    </div>
</template>
<script setup lang="ts">
import { getCurrentInstance } from 'vue';

const video = uni.createVideoContext('test', getCurrentInstance());
function play() {
    video.play();
}
function pause() {
    video.pause();
}
</script>

```

**Comment by llk2yq** [comment]
@fxy060608 
![image](https://user-images.githubusercontent.com/22813922/162913508-df44f027-32ba-497d-bb9a-09dd419defdc.png)
在开发者工具中id会有一串随机的前缀（可以审查元素看到）。
不过确实是**不影响使用**的，可以直接通过`test`这个id获取到视频。
可能这个前缀是微信的特性吧，在`createVideoContext`时会自动忽略掉前缀。
