### ISSUE TITLE
@dcloudio/vite-plugin-uni 依赖打包异常

### ISSUE THREAD

**Issue by okxiaoliang4** [dcloudio/uni-app#3425]
**问题描述**

```shell
VM1147:5 app.js错误:
 TypeError: store_auth.defineStore is not a function
    at global.js? [sm]:10
    at h (VM1095 WAService.js:2)
    at r (VM1095 WAService.js:2)
    at index.js? [sm]:24
    at h (VM1095 WAService.js:2)
    at r (VM1095 WAService.js:2)
    at auth.js? [sm]:19
    at h (VM1095 WAService.js:2)
    at r (VM1095 WAService.js:2)
    at app.js? [sm]:4(env: Windows,mp,1.05.2111300; lib: 2.23.4)
```

将@dcloudio/vite-plugin-uni更新到版本3.0.0-alpha-3040520220408002后依赖引用关系异常
依赖关系如下：
auth.ts -> pinia
global.ts -> pinia
main.ts -> pinia

在项目中原本`pinia`库是打包在`vendor`中的，更新后却打包到了 storeA中

**复现步骤**
复现demo无法复现

**预期结果**
正常打包到`vendor`中

**实际结果**
![image](https://user-images.githubusercontent.com/22525904/163126688-bd5613b6-b5f6-4f98-94e5-81f78476a060.png)

```ts
// auth.ts
// ...
// pinia 源码
```

```ts
// global.ts
var store_auth = require("./auth.js");
const useGlobalStore = store_auth.defineStore("global", {
  // ...
}
```

**系统信息:**
 - 微信小程序、支付宝小程序
 - uni-app@3.0.0-alpha-3040520220408002

**补充信息**

**Comment by fxy060608** [comment]
发测试工程

**Comment by okxiaoliang4** [comment]
目前尝试最小复现没复现出来，麻烦看看提供的信息能否大概定位到问题，不行的话我再继续尝试复现一下。。

**Comment by okxiaoliang4** [comment]
> 发测试工程

ok, 我再试试看怎么复现

**Comment by fxy060608** [comment]
> > 发测试工程
> 
> ok, 我再试试看怎么复现

可以试着调整下package.json中的版本号，不使用`^`，全部锁死最新的相同版本

**Comment by okxiaoliang4** [comment]
> > > 发测试工程
> 
> > 
> 
> > ok, 我再试试看怎么复现
> 
> 
> 
> 可以试着调整下package.json中`@dcloudio/*`的版本号，不使用`^`，全部锁死最新的相同版本

试过了，我一个一个包升级版本定位，发现只有这个包升级到这个版本才会出现这个问题

**Comment by okxiaoliang4** [comment]
@fxy060608 复现了
https://github.com/okxiaoliang4/uni-bug-report/tree/bug/require

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3040520220413002
