### ISSUE TITLE
vue3版本 微信小程序页面缺乏onSaveExitState生命周期钩子

### ISSUE THREAD

**Issue by pengjinlong** [dcloudio/uni-app#3427]
**问题描述**
微信小程序页面有onSaveExitState生命周期钩子
![image](https://user-images.githubusercontent.com/26454874/163148978-8b9893ac-99c4-41e8-9e0e-457e67196c32.png)
而uniapp vue3版本目前没有导出该钩子
![image](https://user-images.githubusercontent.com/26454874/163150092-6d6aae97-fabf-490f-8242-630017f07751.png)

**系统信息:**
 - 发行平台: [如 微信小程序、]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

    "@dcloudio/types": "^2.5.18",
    "@dcloudio/uni-automator": "^3.0.0-alpha-3040220220310005",
    "@dcloudio/uni-cli-shared": "^3.0.0-alpha-3040220220310005",
    "@dcloudio/vite-plugin-uni": "^3.0.0-alpha-3040220220310005",

**Comment by fxy060608** [comment]
已补充，cli更新至：3.0.0-alpha-3040520220413002
