### ISSUE TITLE
nvue在onReady中对data变量赋值对视图层的:active有影响！

### ISSUE THREAD

**Issue by etjson** [dcloudio/uni-app#3428]
**问题描述**
nvue在onReady中对data变量赋值对视图层的:active有影响！

**复现步骤**
1.  使用 HbuilderX 创建一个最简单的示例工程，采用 vue2
2. 创建 nvue 页面，页面代码如下：
```text
<template>
	<div>
		<div class="app">
			<div class="header jihuo" v-if="jihuo">
				<div class="header_left"></div>
				<div class="header_right">
					<text class="right_text_a">{{ asd }}</text>
				</div>
			</div>
			<div v-else class="header weijihuo">
				<div class="header_left"></div>
				<div class="header_right">
					<text class="right_text_a">{{ asd }}</text>
				</div>
			</div>
		</div>
	</div>
</template>

<script>
export default {
	name: 'index',
	data() {
		return {
			jihuo: false,
			asd: 'asda'
		};
	},
	onReady() {
		this.test();
	},
	methods: {
		test() {
			if (process.env.NODE_ENV != 'production') {
				this.jihuo = true;
			}
		}
	}
};
</script>

<style scoped>
.jihuo {
	background-color: #326598;
	padding: 30rpx 30rpx 30rpx 0;
}

.jihuo:active {
	background-color: #2a557f;
}

.weijihuo {
	background-color: #f4b754;
	padding: 30rpx 30rpx 30rpx 0;
}

.weijihuo:active {
	background-color: #e8aa4d;
}

.header {
	height: 300rpx;
	border-radius: 20rpx;
	flex-direction: row;
}

.app {
	display: flex;
	flex-direction: column;
	padding: 0 30rpx 30rpx 30rpx;
	color: #333;
}
</style>

**预期结果**
在onReady中对data变量赋值对视图层的:active没有影响

**实际结果**
在onReady中对data变量赋值对视图层的:active有影响


**系统信息:**
发行平台：App
操作系统：Android 12
HBuilderX版本：3.3.13
设备信息：小米12pro

**Comment by etjson** [comment]
@fxy060608 可以看一下么？

**Comment by zhetengbiji** [comment]
设置 nvueStyleCompiler 为 weex 试试：https://uniapp.dcloud.io/collocation/manifest.html

**Comment by etjson** [comment]
> 设置 nvueStyleCompiler 为 weex 试试：https://uniapp.dcloud.io/collocation/manifest.html
> 
> 如果仍然有问题，节点上增加 key 属性即可

不行，还是没用。

**Comment by etjson** [comment]
> ```
> <div>
>         <div class="app">
>             <div key="jihuo" class="header jihuo" v-if="jihuo">
>                 <div class="header_left"></div>
>                 <div class="header_right">
>                     <text class="right_text_a">{{ asd }}</text>
>                 </div>
>             </div>
>             <div key="weijihuo" v-else class="header weijihuo">
>                 <div class="header_left"></div>
>                 <div class="header_right">
>                     <text class="right_text_a">{{ asd }}</text>
>                 </div>
>             </div>
>         </div>
>     </div>
> ```

那就是if和else都要加上了，有没有更好的解决方案？这么弄挺多地方要加key的，包括transition也有影响，也是加上key就好了。
