### ISSUE TITLE
运行到App后出现POST请求403forbidden问题

### ISSUE THREAD

**Issue by kongsiyu** [dcloudio/uni-app#343]
**问题描述**
项目运行到App后出现POST请求403forbidden问题：
1.网络环境：局域网
2.在Chrome和微信小程序中，请求正常
3.运行到APP（Android）后POST请求出现请求403，GET请求正常
4.当前仅尝试了1个GET请求和一个POST请求，不确定是否与POST有关
5.后端为java(springmvc)提供api，已进行跨域处理，在spring入口（DispatcherServlet）断点调试未进断点。
6.尝试换过手机均存在同样问题，一台中兴，一台三星s5

APP失败响应结果：{"data":"","statusCode":403,"header":{"Date":"Wed, 24 Apr 2019 10:20:21 GMT","Content-Length":"0","Content-Type":"text/plain"},"errMsg":"request:ok","config":{"baseUrl":"http://192.168.0.167:9081/cust","header":{"content-type":"application/x-www-form-urlencoded"},"data":{"mobile":"13128936474","captcha":"888888"},"method":"POST","contentType":"text","dataType":"json","responseType":"text","url":"http://192.168.0.167:9081/cust/customer/captcha-login","requestId":1556101221636}}

H5成功响应结果：{"data":"**此处省略**","statusCode":200,"header":{"content-type":"application/json;charset=UTF-8"},"errMsg":"request:ok","config":{"baseUrl":"http://192.168.0.167:9081/cust","header":{"Content-Type":"application/x-www-form-urlencoded","-utoken":"1ea8cc0cf7a74626a305d163a164c8fb"},"data":{"mobile":"13128936474","captcha":"888888"},"method":"POST","contentType":"text","dataType":"json","responseType":"text","url":"http://192.168.0.167:9081/cust/customer/captcha-login","requestId":1556098972152}}

**Comment by hu-qi** [comment]
APP应该是需要https 看是android哪个版本，Android9 开始，会默认阻止 http 请求。
建议您试试别的http请求或者https请求

**Comment by kongsiyu** [comment]
@hu-qi Android版本一台为7.1.1 ，一台为6.0.1，开发环境，没法弄https啊，感觉似乎不是这个问题

**Comment by kongsiyu** [comment]
@hu-qi 对了，我抓过包，请求是发出来了的

**Comment by kongsiyu** [comment]
补充说明：
下图是在手机浏览器（左、成功）发起请求与在手机app（右、失败）发起请求的抓包数据对比
![image](https://user-images.githubusercontent.com/8521224/56704762-fce5d780-6740-11e9-9da7-af8e7bb7ade9.png)

**Comment by hu-qi** [comment]
> 补充说明：
> 下图是在手机浏览器（左、成功）发起请求与在手机app（右、失败）发起请求的抓包数据对比
> ![image](https://user-images.githubusercontent.com/8521224/56704762-fce5d780-6740-11e9-9da7-af8e7bb7ade9.png)

看到您APP端的content-type不同 您看下这影响不

**Comment by kongsiyu** [comment]
> > 补充说明：
> > 下图是在手机浏览器（左、成功）发起请求与在手机app（右、失败）发起请求的抓包数据对比
> > ![image](https://user-images.githubusercontent.com/8521224/56704762-fce5d780-6740-11e9-9da7-af8e7bb7ade9.png)
> 
> 看到您APP端的content-type不同 您看下这影响不

我也注意到了这个情况，但是我代码是同一个，而且我确实设置了header里面的contentType，并确定两端调用到uni.request时是一致的”header":{"content-type":"application/x-www-form-urlencoded"},"
