### ISSUE TITLE
vue3版本使用page-meta后编译成H5，uni-view会带上display:none样式

### ISSUE THREAD

**Issue by aalexlin** [dcloudio/uni-app#3430]
**问题描述**
![image](https://user-images.githubusercontent.com/6197922/163325557-ee83ca7b-dcc6-43ac-81b7-2039c6691460.png)

**系统信息:**
 - 发行平台: H5平台
 - uni-app版本: 3.0.0-alpha-3040320220325003

**Comment by fxy060608** [comment]
贴你的页面代码

**Comment by aalexlin** [comment]
![image](https://user-images.githubusercontent.com/6197922/163514691-38bf7cf3-2439-49b1-8574-ab280e27d51b.png)

**Comment by fxy060608** [comment]
用法错误，页面内容不要放置到`page-meta`里边，查看文档 https://uniapp.dcloud.net.cn/component/page-meta.html
```html
<template>
  <page-meta>
  </page-meta>
  <view class="content">
  </view>
</template>
```
