### ISSUE TITLE
支持配置飞书小程序PC大窗口模式

### ISSUE THREAD

**Issue by jerryhwq** [dcloudio/uni-app#3431]
**新功能描述**
飞书支持在app.json中配置PC大窗口模式，希望可以增加相关配置

**现状及问题**
现在需要在生成飞书小程序工程工程后手动添加相关配置

**补充信息**
飞书PC端适配相关文档: https://open.feishu.cn/document/home/develop-a-gadget-in-5-minutes/adapt-to-pc

**Comment by fxy060608** [comment]
`manifest.json`中`mp-lark`节点配置
