### ISSUE TITLE
在nvue中使用pinia，APP端渲染异常

### ISSUE THREAD

**Issue by Sexy6God** [dcloudio/uni-app#3432]
**问题描述**
在vnue中使用pinia，编译到小程序表现正常，APP端渲染异常，没有输出错误提示
小程序：
![截屏2022-04-15 下午2 05 30](https://user-images.githubusercontent.com/86021729/163529905-9d1570ef-6968-439e-b51f-07defc6c9fcd.png)
APP：
![截屏2022-04-15 下午2 11 45](https://user-images.githubusercontent.com/86021729/163530006-495593e8-e50f-4e33-ab5d-40313d32b70e.png)

![截屏2022-04-15 下午2 11 55](https://user-images.githubusercontent.com/86021729/163529920-8d750950-303d-4220-9dc3-2526d018973b.png)

**复现步骤**
[可复现demo](https://github.com/Sexy6God/uni-vue3-vite-compile-bug)

```js
import { defineStore } from 'pinia';
export const useCounterStore = defineStore('counter', () => {
  const count = ref(0);
  function increment() {
    count.value++;
  }
  return { count, increment };
});

```

```vue
<template>
  <view class="main">
    <view class="counter" @click="counterStore.increment">
      <text>{{ counterStore.count }}</text>
    </view>
    <!-- <view class="counter">TEST</view> -->
  </view>
</template>

<script setup lang="ts">
  import { useCounterStore } from '@/store/counter';
  const counterStore = useCounterStore();
  console.log('test pinia');
</script>
```
**系统信息:**
 - 发行平台: [App]
 - HBuilderX版本 [3.4.5.20220408-alpha]
 - uni-app版本 [3.0.0-alpha-3040520220413002]

**Comment by fxy060608** [comment]
需要在main.ts中导出Pinia
```ts
import { createSSRApp } from 'vue';
import * as Pinia from 'pinia';
import { setupStore } from '@/store';
import App from './App.vue';
import 'vue-global-api';

export function createApp() {
    const app = createSSRApp(App);
    setupStore(app);
    return { app, Pinia };
}

```

**Comment by Sexy6God** [comment]
已经在main.ts中导出pinia
![截屏2022-04-15 下午2 58 43](https://user-images.githubusercontent.com/86021729/163534250-40313324-b76a-4e00-9fb5-3cf92142b25f.png)

运行的真机上，出现一下错误
![截屏2022-04-15 下午2 52 28](https://user-images.githubusercontent.com/86021729/163534602-5ba77527-cf21-4fea-b5fa-10bdfb26084f.png)

**Comment by fxy060608** [comment]
> 已经在main.ts中导出pinia ![截屏2022-04-15 下午2 58 43](https://user-images.githubusercontent.com/86021729/163534250-40313324-b76a-4e00-9fb5-3cf92142b25f.png)
> 
> 运行的真机上，出现一下错误 ![截屏2022-04-15 下午2 52 28](https://user-images.githubusercontent.com/86021729/163534602-5ba77527-cf21-4fea-b5fa-10bdfb26084f.png)

HBuilderX版本号是多少？使用最新的3.4.5的Alpha版本

**Comment by Sexy6God** [comment]
刚才那个错误提示已经没有了，有了新的问题，Hbuilder 3.4.5.20220408-alph

![截屏2022-04-15 下午3 05 36](https://user-images.githubusercontent.com/86021729/163536711-a0eb8f8b-f1cb-4afc-85be-56e362430a98.png)
![截屏2022-04-15 下午3 05 42](https://user-images.githubusercontent.com/86021729/163536773-eba56371-e793-4c63-a643-054382d8e324.png)

**Comment by fxy060608** [comment]
> 刚才那个错误提示已经没有了，有了新的问题，HBuilder X 3.4.5.20220408-alph
> 
> ![截屏2022-04-15 下午3 05 36](https://user-images.githubusercontent.com/86021729/163536711-a0eb8f8b-f1cb-4afc-85be-56e362430a98.png) ![截屏2022-04-15 下午3 05 42](https://user-images.githubusercontent.com/86021729/163536773-eba56371-e793-4c63-a643-054382d8e324.png)

你示例工程`counter.ts`的`ref` 没有主动 `import { ref } from 'vue'`，或者你没有在`vite.config.ts`中配置自动导入的插件

**Comment by Sexy6God** [comment]
明白了，Thanks♪(･ω･)ﾉ
