### ISSUE TITLE
map 在h5中 overylay 颜色渲染不生效

### ISSUE THREAD

**Issue by RiuHDuo** [dcloudio/uni-app#3433]
**问题描述**
版本是: "3.0.0-alpha-3040520220413002",
在h5 编译下渲染ployline或者circle 无论如何设置color始终是黑色
还有@tap事件也无效

**复现步骤**

**预期结果**
微信小程序下正常

**实际结果**
![image](https://user-images.githubusercontent.com/830134/163533949-d30b8918-9201-4aee-85e1-ffc07c6dd62c.png)

**系统信息:**
 - 发行平台: H5

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
3.0.0-alpha-3040720220422002 已修复

**Comment by RiuHDuo** [comment]
> 3.0.0-alpha-3040720220422002 已修复
nice job
