### ISSUE TITLE
编译到h5，module not found

### ISSUE THREAD

**Issue by aihanjiao** [dcloudio/uni-app#3435]
**问题描述**
<img width="304" alt="1650014673(1)" src="https://user-images.githubusercontent.com/59612542/163553471-cc6b3016-7c6f-4e9e-80bb-b2f6965c4a60.png">

**复现步骤**
https://gitee.com/aihanjiao/uni-app-bug
直接运行实例工程  
yarn dev:h5

**系统信息:**
 - 发行平台: H5平台
 - uni-app版本：最新

**补充信息**
把src/model/index.ts下的第152行interface名字随便改一个，反正不要叫Diabetes就好了。。。

**Comment by fxy060608** [comment]
是因为你在`pages/followup/index.vue`的`setup`中import了，可以加上`type`标记
```ts
import type { Diabetes, DrugUseInfo, FollowupBaseInfo, FollowupInfo } from '../../model'
```
