### ISSUE TITLE
**bug** vite、vue3小程序分包造成双向绑定失效

### ISSUE THREAD

**Issue by hzh1990** [dcloudio/uni-app#3439]
**问题描述**
小程序打开分包页面，造成页面双效绑定失效。
打开普通页面则没有这种情况

**这个是打开分包页面的情况**
https://user-images.githubusercontent.com/4394948/163671821-48cd6eca-c242-49cf-9604-7b9f4bc4e6f6.mov

**这个是打开普通页面的情况**
https://user-images.githubusercontent.com/4394948/163671854-2f0478e3-c70f-42ef-bd1a-727fbb731c0c.mov

**复现步骤**
[demo](https://github.com/hzh1990/uni-app-bug)
yarn
yarn dev:mp-weixin

**预期结果**
和打开普通页面一致

**系统信息:**
 - 发行平台: mp-weixin
 - uni-app版本 : 3.0.0-alpha-3040620220415002
 - 设备信息:  微信开发者工具，android、ios

**Comment by fxy060608** [comment]
真机测试一下
