### ISSUE TITLE
vue 3 cli / HBuilderX 工程，editor 组件在将文字 format 为 header 样式之后无法正确的取消 header 样式

### ISSUE THREAD

**Issue by appleone123** [dcloudio/uni-app#3443]
**问题描述**
vue3 ，cli / HBuilderX 工程均可复现，editor 组件在给文字设置了 header 样式之后，无法取消 header 样式，根据 editor 文档说明，editorContext 的 format 方法对已经应用样式的选区设置会取消样式，实际并不生效。

**复现步骤**
1.  通过 HBuilderX 创建 vue3 简单示例工程
2. index 页面使用以下代码（百度需要在 pages.json 和 manifest.json 中配置动态组件）
```
<template>
	<view class="content">
		<image class="logo" src="/static/logo.png"></image>
		<editor id="editor" @ready="readyHandler"></editor>
		<button @click="formatH">set H2</button>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				title: 'Hello'
			}
		},
		onLoad() {

		},
		methods: {
			readyHandler(){
				console.log('this is editor ready')
			},
			formatH() {
				// #ifdef MP-WEIXIN
				uni
					.createSelectorQuery()
					.in(this)
					.select('#editor')
					.context(res => {
						res.context.format('header', 'H2')
					})
					.exec()
				// #endif
				// #ifdef MP-BAIDU
				const context = requireDynamicLib('editorLib').createEditorContext('editor')
				context.format('header','H2')
				// #endif
			}
		}
	}
</script>

<style>
	.content {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
	}

	.logo {
		height: 200rpx;
		width: 200rpx;
		margin-top: 200rpx;
		margin-left: auto;
		margin-right: auto;
		margin-bottom: 50rpx;
	}

	.text-area {
		display: flex;
		justify-content: center;
	}

	.title {
		font-size: 36rpx;
		color: #8f8f94;
	}
</style>
```
4. 运行，点击「set H2」按钮，可以看到文字被正常设置为了 h2 样式，再次点击，发现无法取消样式，文字始终为 h2 样式

**预期结果**
editorContext.format 可以正常的对已设置 header 样式的文字取消样式

**实际结果**
editorContext.format 可以无法对已设置 header 样式的文字取消样式

**系统信息:**
 - 发行平台: 微信，百度
 - HBuilderX版本 3.4.5.20220408-alpha

**补充信息**
vue3 cli 工程 
dependencies：
    "@dcloudio/uni-app": "^3.0.0-alpha-3040520220413001",
    "@dcloudio/uni-app-plus": "^3.0.0-alpha-3040520220413001",
    "@dcloudio/uni-components": "^3.0.0-alpha-3040520220413001",
    "@dcloudio/uni-h5": "^3.0.0-alpha-3040520220413001",
    "@dcloudio/uni-mp-alipay": "^3.0.0-alpha-3040520220413001",
    "@dcloudio/uni-mp-baidu": "^3.0.0-alpha-3040520220413001",
    "@dcloudio/uni-mp-kuaishou": "^3.0.0-alpha-3040520220413001",
    "@dcloudio/uni-mp-lark": "^3.0.0-alpha-3040520220413001",
    "@dcloudio/uni-mp-qq": "^3.0.0-alpha-3040520220413001",
    "@dcloudio/uni-mp-toutiao": "^3.0.0-alpha-3040520220413001",
    "@dcloudio/uni-mp-weixin": "^3.0.0-alpha-3040520220413001",
    "@dcloudio/uni-quickapp-webview": "^3.0.0-alpha-3040520220413001",
    "@dcloudio/uni-ui": "^1.4.13",
devDependencies：
    "@dcloudio/types": "^2.5.17",
    "@dcloudio/uni-automator": "^3.0.0-alpha-3040520220413001",
    "@dcloudio/uni-cli-shared": "^3.0.0-alpha-3040520220413001",
    "@dcloudio/vite-plugin-uni": "^3.0.0-alpha-3040520220413001",

**Comment by fxy060608** [comment]
`context.format('header','H2')` => `context.format('header',2)`

**Comment by appleone123** [comment]
> `context.format('header','H2')` => `context.format('header',2)`

已验证，还麻烦修改下文档，文档中写的还是 H2 这种
<img width="1281" alt="image" src="https://user-images.githubusercontent.com/18554629/163808108-202e53ce-7b60-4e86-b7f2-5b57a41bb258.png">

**Comment by fxy060608** [comment]
> > `context.format('header','H2')` => `context.format('header',2)`
> 
> 已验证，还麻烦修改下文档，文档中写的还是 H2 这种 <img alt="image" width="1281" src="https://user-images.githubusercontent.com/18554629/163808108-202e53ce-7b60-4e86-b7f2-5b57a41bb258.png">

@StrivingRabbit 考虑是抹平百度上的差异，还是文档标注
