### ISSUE TITLE
vue3 cli/HBuilderX 工程，editor 的 ready 事件绑定在百度平台大概率无法触发，报错为：no undefined method found

### ISSUE THREAD

**Issue by appleone123** [dcloudio/uni-app#3444]
**问题描述**
vue3 cli/HBuilderX 工程，editor 的 ready 事件绑定在百度平台大概率无法触发，报错为：no undefined method found

**复现步骤**
1、通过 HBuilderX 创建 vue3 简单示例工程
2、index 页面使用以下代码（百度需要在 pages.json 和 manifest.json 中配置动态组件）
```
<template>
	<view class="content">
		<image class="logo" src="/static/logo.png"></image>
		<editor id="editor" @ready="readyHandler"></editor>
		<button @click="formatH">set H2</button>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				title: 'Hello'
			}
		},
		onLoad() {

		},
		methods: {
			readyHandler(){
				console.log('this is editor ready')
			},
			formatH() {
				// #ifdef MP-WEIXIN
				uni
					.createSelectorQuery()
					.in(this)
					.select('#editor')
					.context(res => {
						res.context.format('header', 'H2')
					})
					.exec()
				// #endif
				// #ifdef MP-BAIDU
				const context = requireDynamicLib('editorLib').createEditorContext('editor')
				context.format('header','H2')
				// #endif
			}
		}
	}
</script>

<style>
	.content {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
	}

	.logo {
		height: 200rpx;
		width: 200rpx;
		margin-top: 200rpx;
		margin-left: auto;
		margin-right: auto;
		margin-bottom: 50rpx;
	}

	.text-area {
		display: flex;
		justify-content: center;
	}

	.title {
		font-size: 36rpx;
		color: #8f8f94;
	}
</style>
```
运行，可以看到 readyHandler 事件中的 log 并未输出，取而代之的是如图类似报错：
<img width="913" alt="image" src="https://user-images.githubusercontent.com/18554629/163800044-37abf2dd-713c-4ff5-a999-e726f336ef0c.png">

[或者可以直接贴源代码]

**预期结果**
editor 的 ready 事件可以正确触发

**实际结果**
editor 的 ready 事件触发报错

**系统信息:**
 - 发行平台: 百度
 - HBuilderX版本 3.4.5.20220408-alpha
 - vue3 cli 工程
dependencies：
"@dcloudio/uni-app": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-app-plus": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-components": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-h5": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-mp-alipay": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-mp-baidu": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-mp-kuaishou": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-mp-lark": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-mp-qq": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-mp-toutiao": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-mp-weixin": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-quickapp-webview": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-ui": "^1.4.13",
devDependencies：
"@dcloudio/types": "^2.5.17",
"@dcloudio/uni-automator": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-cli-shared": "^3.0.0-alpha-3040520220413001",
"@dcloudio/vite-plugin-uni": "^3.0.0-alpha-3040520220413001",

**补充信息**
百度无法正确找到绑定到 ready 上面的事件，可能为事件映射绑定过晚导致

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/commit/a317287fa6ceb46d63edae0352f75f09d2cf30c2

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3040620220415003

**Comment by appleone123** [comment]
> 已修复，cli更新至：3.0.0-alpha-3040620220415003

经验证已修复，感谢
