### ISSUE TITLE
vue3 cli/HBuilderX 工程，editor 组件在微信平台下，绑定了 input 和 ready 事件后会导致每次输入都触发 ready 事件，同时不执行 input 事件

### ISSUE THREAD

**Issue by appleone123** [dcloudio/uni-app#3445]
**问题描述**
vue3 cli/HBuilderX 工程，editor 组件在微信平台下，绑定了 input 和 ready 事件后会导致每次输入都触发 ready 事件，同时 input 事件不执行

**复现步骤**
1、通过 HBuilderX 创建 vue3 简单示例工程
2、index 页面使用以下代码
```
<template>
	<view class="content">
		<image class="logo" src="/static/logo.png"></image>
		<editor id="editor" @ready="readyHandler" @input="stateHandler"></editor>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				title: 'Hello'
			}
		},
		onLoad() {

		},
		methods: {
			stateHandler(){
				console.log('this is input')
			},
			readyHandler(){
				console.log('this is editor ready')
			}
		}
	}
</script>

<style>
	.content {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
	}

	.logo {
		height: 200rpx;
		width: 200rpx;
		margin-top: 200rpx;
		margin-left: auto;
		margin-right: auto;
		margin-bottom: 50rpx;
	}

	.text-area {
		display: flex;
		justify-content: center;
	}

	.title {
		font-size: 36rpx;
		color: #8f8f94;
	}
</style>

```
3、运行，在 editor 中输入内容，可以看到控制台随着输入不断的输出 log：this is editor ready，但是没有 input 事件的 log
<img width="1221" alt="image" src="https://user-images.githubusercontent.com/18554629/163801460-55d0f155-c931-4126-9ab5-c5e91772c988.png">

**预期结果**
editor onReady 事件不随输入触发

**实际结果**
editor onReady 事件随输入触发

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本 3.4.5.20220408-alpha
 - vue3 cli 工程
dependencies：
"@dcloudio/uni-app": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-app-plus": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-components": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-h5": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-mp-alipay": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-mp-baidu": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-mp-kuaishou": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-mp-lark": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-mp-qq": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-mp-toutiao": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-mp-weixin": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-quickapp-webview": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-ui": "^1.4.13",
devDependencies：
"@dcloudio/types": "^2.5.17",
"@dcloudio/uni-automator": "^3.0.0-alpha-3040520220413001",
"@dcloudio/uni-cli-shared": "^3.0.0-alpha-3040520220413001",
"@dcloudio/vite-plugin-uni": "^3.0.0-alpha-3040520220413001",

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3040620220415003

**Comment by appleone123** [comment]
> 已修复，cli更新至：3.0.0-alpha-3040620220415003

经验证已修复，感谢～
