### ISSUE TITLE
manifest.json设置orientation为横屏时候nvue页面渲染宽度有问题

### ISSUE THREAD

**Issue by xyzard** [dcloudio/uni-app#345]
**问题描述**
首屏页面为nvue页面，设置manifest.json的orientation为landscape-primary之后；当垂直方向手持手机首次启动app之后首屏页面只有50%以下的宽度；当横向方向手持手机首次启动app之后首屏页面正确渲染为100%宽度。

**Comment by ArrayDC** [comment]
这是因为nvue是相对设备的宽度进行排版的，如果要自适应横竖屏，应该使用flex弹性布局（避免使用容器类view使用px/upx等绝对的宽度）
