### ISSUE TITLE
微信小程序加密网络通道API请求支持

### ISSUE THREAD

**Issue by je45** [dcloudio/uni-app#3450]
**新功能描述**
小程序加密网络通道：https://developers.weixin.qq.com/miniprogram/dev/framework/open-ability/user-encryptkey.html
uniapp好像找不到对应的接口

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by Otto-J** [comment]
uni-app 是最大程度支持各平台兼容的 api，部分 api 可能不受支持。

如果你想使用特定特定平台提供的 api 能力，可以直接使用对应平台前缀，比如 `wx. getLatestUserKey`
