### ISSUE TITLE
H5 vue3 配置base后设计的不合理。

### ISSUE THREAD

**Issue by innovational** [dcloudio/uni-app#3454]
**新功能描述**
希望对 / 开头的路径不做处理

**现状及问题**
除了uniapp 外其他所有的框架设计都是 base只对打包后的代码引入路径生效，不会去插手其他标签。
目前uniapp 在开发环境接管了所有静态资源，打包后对 image标签增加了base路径，**极其不合理**
以下几种场景  base 配置为h5
1. 在index.html 里面写   <script type="text/javascript" src="/static/comJs/wxJsSdk.js"></script>
   在开发环境配置了proxy的情况  请求时会自动加上 base  （这里应该算bug）
   打包后正常。
2. 在imgage 标签 src="/static/1.png" 
   在开发环境配置了proxy的情况  请求时会自动加上 base  （这里其实应该优化，判断是否是 / 开头）
   打包后也会加上base (这就不合理了，画蛇添足了)。

大家配置base 的目的就是为了访问时 www.xx.com/h5 或 www.xx.com/admin 等，并不是所有资源都在base下，
难道uniapp 就没有考虑过 /h5 和  /admin 是两套代码，但资源是一套的情况 ？ 并不是所有资源都在第三方cdn上的

**尝试方案**
目前只能在前端统一加上域名，
但这样感觉不好，如果直接使用当前域名，对开发环境又得单独处理，如果写死正式环境，测试环境，预发布环境又得每个都写。

**补充信息**
参考其他平台的做法，如原生的vite+vue3 打包时的处理

**Comment by fxy060608** [comment]
uni-app是一个跨端框架，不仅仅要考虑h5，相同的代码要保证在小程序，app，h5都可以正常运行
大部分情况下，开发者部署时，资源要么部署到base目录，要么部署到cdn，少数情况是你列出来的，你列出来的情况，可以通过补充完整路径实现

**Comment by innovational** [comment]
> 
首先我在h5下 配置的 base 肯定只对h5生效，其他平台能不能配置base我暂未确认。
其次我举例的第一点开发环境与打包后体验不一致肯定是不应该的。

如果改动成本确实极大，我就关闭这个issue.  
但我依然认为这是优化点（只是优先级可能很低）

**Comment by fxy060608** [comment]
> > 
> 
> 首先我在h5下 配置的 base 肯定只对h5生效，其他平台能不能配置base我暂未确认。 其次我举例的第一点开发环境与打包后体验不一致肯定是不应该的。
> 
> 如果改动成本确实极大，我就关闭这个issue. 但我依然认为这是优化点（只是优先级可能很低）

其他平台不能配置base，这么设计主要是为了照顾大多数情况
举例，小程序，App平台开发者很多会直接写绝对路径引用资源，在h5上，有时候又需要部署在二级目录，如果h5不自动添加base，就会导致，在小程序，App运行是正常的，但到了h5，发现路径不对了
```html
<template><image :src="src"/></template>
<script setup>const src="/static/logo.png"</script>
```

**Comment by innovational** [comment]
> > > 
> > 
> > 
> > 首先我在h5下 配置的 base 肯定只对h5生效，其他平台能不能配置base我暂未确认。 其次我举例的第一点开发环境与打包后体验不一致肯定是不应该的。
> > 如果改动成本确实极大，我就关闭这个issue. 但我依然认为这是优化点（只是优先级可能很低）
> 
> 其他平台不能配置base，这么设计主要是为了照顾大多数情况 举例，小程序，App平台开发者很多会直接写绝对路径引用资源，在h5上，有时候又需要部署在二级目录，如果h5不自动添加base，就会导致，在小程序，App运行是正常的，但到了h5，发现路径不对了
> 
> ```
> <template><image :src="src"/></template>
> <script setup>const src="/static/logo.png"</script>
> ```

ok,  确实是这样 ，我关闭了
