### ISSUE TITLE
卸载hbx重新安装后vue3+pinia编译失败

### ISSUE THREAD

**Issue by haytor** [dcloudio/uni-app#3458]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
问题1 ：升级安装3.4.6.20220420后出现编译CUP高，卡顿严重。完全卸载后重新安装编译 vue3+pinia+ts 提示 : 找不到 pinia/dist/pinia.mjs 

环境说明：
系统：win11  工具版本：HBX 3.4.6  微信工具最新版，vscode 最新版；（编译时微信工具 CUP 100% ，应用文件130个左右）
系统 mac bigSur 工具版本：HBX 3.4.6  微信工具最新版，vscode 最新版； （无卡顿）

以上都出现此问题原因是 新版本已集成，但在 HBuilderX\plugins\uniapp-cli-vite\node_modules\ 下没有pinia包。
本人手动安装后编译成功。

 问题2 ：修改代码后每次保存vite编译后总会删除 project.config.json，微信工具则一直提示：解析 project.config.json 文件失败，请检查其内容或删除此文件
 
 环境说明：
系统：win11  工具版本：HBX 3.4.6  微信工具最新版，vscode 最新版；（10次有9次提示, 发现是每次 project.config.json 文件内容重新生成）
系统 mac bigSur 工具版本：HBX 3.4.6  微信工具最新版，vscode 最新版； （正常无提示）

补充 : 因需要 ts 支持，使用 vscode开发，HBX 来编译至微信开发工具。package.json在开发扩展包下仅安装："@dcloudio/uni-app": "3.0.0-alpha-3040720220422002"，无其它扩展包

**Comment by fxy060608** [comment]
说明操作系统
问题1：
项目根目录是否有package.json？如果没有，创建一个默认的package.json，然后再看看是否还存在编译cpu高，速度慢的问题
问题2：
Mac 未重现，如果确认是必现的，发一个可重现该问题的测试工程

**Comment by haytor** [comment]
> 说明操作系统 问题1： 项目根目录是否有package.json？如果没有，创建一个默认的package.json，然后再看看是否还存在编译cpu高，速度慢的问题 问题2： Mac 未重现，如果确认是必现的，发一个可重现该问题的测试工程

环境已补充，mac 测试后一切正常，win11 上出现问题1/2.

**Comment by zhetengbiji** [comment]
HBuilderX 3.4.7+ 已修复

**Comment by dcloudhdx** [comment]
问题2：
Windows 11 22000.613 HBuilderX 3.4.6 alpha 微信开发者工具 RC 1.05.2203251 没有复现问题

**Comment by dcloudhdx** [comment]
问题2：提供一个简单的测试工程

**Comment by zhuscat** [comment]
> 解析 project.config.json 文件失败，请检查其内容或删除此文件

我也是一直这样
