### ISSUE TITLE
createInnerAudioContext.play()方法没有触发onPlay回调

### ISSUE THREAD

**Issue by HOTAO** [dcloudio/uni-app#346]
**问题描述**
createInnerAudioContext.play()方法没有触发onPlay回调

**复现步骤**
[复现问题的步骤]
```js
var audioCtx = uni.createInnerAudioContext();
audioCtx.onPlay(() => {
        console.log('onPlay');
      });
audioCtx.src = 'you audio url'
audioCtx.play()
```

**预期结果**
打印“onPlay”字符串

**实际结果**
没有打印内容输出

**系统信息:**
 - 发行平台: Android
 - 操作系统 Android 8.0
 - HBuilderX版本 1.9.3
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 小米mix2

**补充信息**
看了一下源码，好像是没有调用回调
![image](https://user-images.githubusercontent.com/13549879/56708235-86e86d00-674e-11e9-9a5c-dedb5d715fc2.png)

**Comment by zhetengbiji** [comment]
你看的是H5部分的源码，H5端不存在这个问题。HBuilderX 1.9.6 开始 App端已修复此问题。
