### ISSUE TITLE
nvue文件中webview的onPostMessage无法接受webview中页面发送的消息

### ISSUE THREAD

**Issue by Iongtao** [dcloudio/uni-app#3465]
**问题描述**
nvue文件中webview的onPostMessage无法接受webview中页面发送的消息

**复现步骤**
html代码如下
<img width="498" alt="image" src="https://user-images.githubusercontent.com/24762616/165016991-12015500-33af-47d6-aab9-55f8148c5f53.png">

nvue代码如下
<img width="873" alt="image" src="https://user-images.githubusercontent.com/24762616/165017075-25893c16-79c5-413b-9ba4-8ff24af14466.png">

界面效果
<img width="452" alt="image" src="https://user-images.githubusercontent.com/24762616/165017297-7052c800-4b1c-44f9-a107-59b06b27b540.png">

通过点击post按钮发送消息

**预期结果**
nvue中接收到消息

**实际结果**
无反应

**系统信息:**
 - 发行平台: App
 - 操作系统 IOS15.2
 - HBuilderX版本 HBuilderX3.4.7
 - uni-app版本 无
 - 设备信息 IPhone 12

**补充信息**
不知

**Comment by Iongtao** [comment]
使用vue的webview是可以接收到消息的

**Comment by Iongtao** [comment]
我调试了下uni.webview.1.5.3.js的源代码 发现在nvue中 最终执行的postMessage是"window.webkit.messageHandlers.__io_org_weex_webview.postMessage"。
我尝试打印了这个方法结果是undefined
**alert(JSON.stringify(window.webkit.messageHandlers.__io_org_weex_webview.postMessage))**
<img width="452" alt="image" src="https://user-images.githubusercontent.com/24762616/165045306-f499d286-b9ce-4a30-ab58-530177294bc1.png">
请问该如何使用正确的postMessage方法

**Comment by dcloudhdx** [comment]
测试没有问题，参考下面的代码

```
<template>
	<view>
		<web-view ref="webview" src="/hybrid/html/local.html" class="webview" @onPostMessage="handlePostMessage"></web-view>
		<button class="button" @click="evalJs">evalJs(改变webview背景颜色)</button>
	</view>
</template>

<script>
	export default {
		data: {
		},
		methods: {
			// webview向外部发送消息
			handlePostMessage: function(data) {
				console.log("接收到消息：" + JSON.stringify(data.detail));
			},
			// 调用 webview 内部逻辑
			evalJs: function() {
				this.$refs.webview.evalJs("document.body.style.background ='#00FF00'");
			}
		}
	}
</script>

<style>
  .webview {
    width: 300px;
    height: 200px;
  }
</style>
```

```
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>本地网页</title>
	</head>
	<body>
		<p class="desc">web-view 组件加载本地 html 示例，仅在 App 环境下生效。点击下列按钮，跳转至其它页面。</p>
		<div class="btn-list">
			<button class="btn btn-red" type="button" id="postMessage">postMessage</button>
		</div>
		<!-- uni 的 SDK -->
		<script type="text/javascript" src="https://unpkg.com/@dcloudio/uni-webview-js@0.0.2/index.js"></script>
		<script type="text/javascript">
			document.addEventListener('UniAppJSBridgeReady', function() {
				document.querySelector("#postMessage").addEventListener('click', function() {
					uni.postMessage({
						data: {
							action: 'message'
						}
					});
				})
			});
		</script>
	</body>
</html>

```

**Comment by Iongtao** [comment]
> 测试没有问题，参考下面的代码
> 
> ```
> <template>
> 	<view>
> 		<web-view ref="webview" src="/hybrid/html/local.html" class="webview" @onPostMessage="handlePostMessage"></web-view>
> 		<button class="button" @click="evalJs">evalJs(改变webview背景颜色)</button>
> 	</view>
> </template>
> 
> <script>
> 	export default {
> 		data: {
> 		},
> 		methods: {
> 			// webview向外部发送消息
> 			handlePostMessage: function(data) {
> 				console.log("接收到消息：" + JSON.stringify(data.detail));
> 			},
> 			// 调用 webview 内部逻辑
> 			evalJs: function() {
> 				this.$refs.webview.evalJs("document.body.style.background ='#00FF00'");
> 			}
> 		}
> 	}
> </script>
> 
> <style>
>   .webview {
>     width: 300px;
>     height: 200px;
>   }
> </style>
> ```
> 
> ```
> <!DOCTYPE html>
> <html>
> 	<head>
> 		<meta charset="utf-8" />
> 		<meta name="viewport" content="width=device-width, initial-scale=1">
> 		<title>本地网页</title>
> 	</head>
> 	<body>
> 		<p class="desc">web-view 组件加载本地 html 示例，仅在 App 环境下生效。点击下列按钮，跳转至其它页面。</p>
> 		<div class="btn-list">
> 			<button class="btn btn-red" type="button" id="postMessage">postMessage</button>
> 		</div>
> 		
> 		<script type="text/javascript" src="https://unpkg.com/@dcloudio/uni-webview-js@0.0.2/index.js"></script>
> 		<script type="text/javascript">
> 			document.addEventListener('UniAppJSBridgeReady', function() {
> 				document.querySelector("#postMessage").addEventListener('click', function() {
> 					uni.postMessage({
> 						data: {
> 							action: 'message'
> 						}
> 					});
> 				})
> 			});
> 		</script>
> 	</body>
> </html>
> ```

你好 我尝试了使用上面的代码 依然无反应
我提供了测试工程，我不清楚是否是环境问题还是什么
[地址](https://github.com/Iongtao/uni-webview)

**Comment by Iongtao** [comment]
@dcloudhdx 请问这个功能是否是未实现的？ 在nvue中webview向app发送消息根本就是没有任务反应。vue文件的webview是可以发送消息 但app无法往webview中发送消息（执行js）

**Comment by Iongtao** [comment]
@dcloudhdx 我刚刚创建了vue2的项目 发现是可以的。 vue3版本的nvue webview是有问题的

**Comment by kytrun** [comment]
借楼一个带 webview 接收消息的相关问题，`const wv = plus.webview.open(url, 'id', styles)` 动态创建的 webview 无法在 template 中使用 `@onPostMessage`，经社区提示可用以下方式：

```
plus.globalEvent.addEventListener('plusMessage', msg => {  
    if (msg.data.args.data.name == 'postMessage') {  
        const info = msg.data.args.data.arg  
    }  
})
```

但官方从未表示这是规范的行为，如果可用，能否在文档中表明，或者作进一步封装保证后续的稳定可用？@dcloudhdx

**Comment by Iongtao** [comment]
> 

我现在是使用webview组件来进行通信的， 但是让我觉得很奇怪吧，webview组件和plus创建的webview行为不统一，是两个不同的对象，我在考虑是否也应该用plus创建的webview来作为窗口，但我不清楚通过plus创建的webview是否能和app进行通信。
请问你上面的方法是否可行呢

**Comment by kytrun** [comment]
> > 
> 
> 我现在是使用webview组件来进行通信的， 但是让我觉得很奇怪吧，webview组件和plus创建的webview行为不统一，是两个不同的对象，我在考虑是否也应该用plus创建的webview来作为窗口，但我不清楚通过plus创建的webview是否能和app进行通信。 请问你上面的方法是否可行呢

@Iongtao vue2 时期亲测可用，目前不确定，需要测试。我偏向于使用 plus，因为其封装的 API 更丰富，可扩展和自定义的部分更多。

**Comment by Iongtao** [comment]
> > > 
> > 
> > 
> > 我现在是使用webview组件来进行通信的， 但是让我觉得很奇怪吧，webview组件和plus创建的webview行为不统一，是两个不同的对象，我在考虑是否也应该用plus创建的webview来作为窗口，但我不清楚通过plus创建的webview是否能和app进行通信。 请问你上面的方法是否可行呢
> 
> @Iongtao vue2 时期亲测可用，目前不确定，需要测试。我偏向于使用 plus，因为其封装的 API 更丰富，可扩展和自定义的部分更多。

我试着用plus创建webview 按照你上面说的接收消息 没有反应 不知道哪里有问题
<img width="955" alt="image" src="https://user-images.githubusercontent.com/24762616/167077099-80d02fcf-c612-40f5-b5d0-8b1075d2e460.png">

项目是vue2写的 webview页面中用 uni.postMessage来发送消息吗？

**Comment by kytrun** [comment]
写在 `App.vue` 的  `onLaunch()` 函数中。

**Comment by Iongtao** [comment]
> 写在 `App.vue`函数中，我之前的代码是 `onLaunch()`中，可以试试不在这个方法中是否也能生效 。
> 
> https://ask.dcloud.net.cn/question/133070

我先吃尝试鞋子啊勒onLaunch中 但是只能接受到app本身的事件消息  webview中通过uni.postMessage无法获取到

**Comment by dcloudhdx** [comment]
> @dcloudhdx 我刚刚创建了vue2的项目 发现是可以的。 vue3版本的nvue webview是有问题的

 已确认Vue3 有问题

**Comment by Iongtao** [comment]
> > @dcloudhdx 我刚刚创建了vue2的项目 发现是可以的。 vue3版本的nvue webview是有问题的
> 
> 已确认Vue3 有问题

请问是否有修复计划

**Comment by fangcong27630** [comment]
同求

**Comment by fangcong27630** [comment]
这个问题就没人处理吗

**Comment by zhetengbiji** [comment]
内部已修复，等待下次发版

**Comment by zhetengbiji** [comment]
3.6.16+ 已修复
