### ISSUE TITLE
 <component is=""/> is not supported 

### ISSUE THREAD

**Issue by JimmyZDD** [dcloudio/uni-app#3469]
**问题描述**
微信小程序 调试
npx uni -p mp-weixin
启动报错
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
"@dcloudio/uni-app": "^3.0.0-alpha-3040520220408002"

**Comment by fxy060608** [comment]
小程序端不支持动态切换组件，请调整为 v-if 切换

**Comment by 2846781956** [comment]
app端支持吗？

**Comment by jieers** [comment]
taro是支持的，有解决方案吗

**Comment by 2846781956** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你的邮件已收到。
