### ISSUE TITLE
在MAC上敲JSON.stringify() 这几个字时Hbuilder 经常闪退

### ISSUE THREAD

**Issue by 188007803** [dcloudio/uni-app#347]
**问题描述**
我在用 Hbuilder X  1.9.3.20190422 MAC版，
电脑是 MacPro 2015款，系统已升至最新。
开发 uni-app 程序
我在vue文件中敲代码敲到 JSON.stringify() 这几个字时经常会 hbuilder 闪退，大概有一半的机率。
有时是自动敲回车自动补全命令时，有时是打括号时，很奇怪。

我用的输入法是鼠须管上的五笔。

**Comment by xiaoyucoding** [comment]
HBuilderX Alpha 1.9.4 已修复此问题

[HBuilderX Alpha 版下载地址](https://ask.dcloud.net.cn/article/35765)
