### ISSUE TITLE
【vue3】Maximum call stack size exceeded

### ISSUE THREAD

**Issue by sufuwang** [dcloudio/uni-app#3473]
**问题描述**
微信小程序中使用 echart ，在 dev 下无报错，在 build 下报错
<img width="521" alt="image" src="https://user-images.githubusercontent.com/46395105/165900040-490d5807-9a86-410c-a841-5b464364a308.png">

echart 使用的是 commonjs 
vite 配置
```
build: {
  minify: 'esbuild',
  target: 'es6',
  commonjsOptions: {
    include: [/echarts.min.js/, /node_modules/],
  },
  terserOptions: {
    compress: {
      drop_console: process.env.VUE_APP_ENV === 'production',
      drop_debugger: true,
    },
  },
},
```

想请教为什么打包之后会出错呀

**Comment by fxy060608** [comment]
发测试工程
