### ISSUE TITLE
支付宝小程序：globalThis is not defined

### ISSUE THREAD

**Issue by JimmyZDD** [dcloudio/uni-app#3474]
**问题描述**
支付宝小程序 使用 globalThis 运行报错

**复现步骤**
yarn
yarn dev:mp-alipay

**实际结果**
![image](https://user-images.githubusercontent.com/20129043/165915497-087d87ad-5caa-403b-a944-16b2b71f97a6.png)

**补充信息**
[uni-vite-ts.zip](https://github.com/dcloudio/uni-app/files/8589585/uni-vite-ts.zip)

**Comment by fxy060608** [comment]
支付宝小程序禁止访问globalThis,global
https://opendocs.alipay.com/mini/framework/implementation-detail
可以使用 https://github.com/antfu/unplugin-auto-import 替换掉 vue-global-api

**Comment by tianzhich** [comment]
请问下我看打包的 vendor.js 里默认就会访问 `globalThis`，但是访问不到，返回了 `undefined`，那我所有 vue 的引用都要用你说这个替代掉吗？
