### ISSUE TITLE
支持 <page-meta> 编写为独立组件而非必须在每个页面都写一遍

### ISSUE THREAD

**Issue by SeasideLee** [dcloudio/uni-app#3475]
**新功能描述**

支持 `page-meta` 编写为独立组件而非必须在每个页面都写一遍

**现状及问题**

当应用涉及到皮肤、主题等色彩配置时，需凭借 `page-meta` 组件的能力来控制页面 `backgroundColor`、`backgroundColorTop`、`backgroundColorBottom` 等属性。一般来说开发者会使用 vuex / pinia 来实现皮肤、主题的控制切换，并暴露一些诸如 `theme`、`mainColor` 之类的 `state` 供其他组件使用。

由于存在「`page-meta` 必须是页面第一个元素」的限制，目前开发者若想要在 `page-meta` 中使用 vuex / pinia 的 `state`，只能在**每个页面**都**引入 store** 然后在 `page-meta` 中**挨个赋值**（全局 mixin 会减轻一些负担，但也不是个好办法），类似下面这样（例子中采用了 `pinia` 的写法）。

```vue
<template>
  <page-meta
    :background-text-style="themeStore.theme"
    :background-color="themeStore.mainColor"
    :background-color-top="themeStore.mainColor"
    :background-color-bottom="themeStore.mainColor"
    :root-background-color="themeStore.mainColor"
    :page-style="`{background-color: ${themeStore.mainColor}`"
    :root-font-size="themeStore.rootFontSize"
  />
</template>

<script setup lang="ts">
import useThemeStore from '@/stores/theme';
const themeStore = useThemeStore();
</script>
```

这在可维护性上实在折磨人，而且大大增加了心智负担。

我希望能将 `page-meta` 独立成一个单独的组件，将上面这段代码写进该组件中，然后直接在各个页面引入该组件就完事。想想多是一件美事，但目前的 `uni-app` 框架不支持这么做，所以提出此问题，希望能有大佬帮我出出主意，也更希望官方能提供将 `page-meta` 独立组件化的能力。

**尝试方案**

我尝试了很多写法，都会导致 `page-meta` 不是页面第一个元素。暂无能绕开的方案。

**补充信息**

暂无补充信息

**Comment by PentaTea** [comment]
看到你使用的vue3，你可以写一个vite插件来给每个页面头部都添加一个page-meta标签
比如我在这个文件中判断是否存在自定义的根页面组件，若不存在则自动添加： 
https://github.com/4chao/preset/blob/master/build/vite-plugin-uni-provider.ts

**Comment by yuxilins** [comment]
我也遇到这个问题，本来想着写个组件 结果不是第一个组件 头疼
