### ISSUE TITLE
使用cli方式创建的vue3+vite项目中使用vuex报错

### ISSUE THREAD

**Issue by mentoorliubin** [dcloudio/uni-app#3476]
**问题描述**
使用cli方式创建的vue3+vite项目中使用vuex报错

**复现步骤**
[复现问题的步骤]
[vite] [plugin:vite:import-analysis] Package subpath './dist/vuex.esm-bundler.js' is not defined by "exports" in /Users/pchy/Code/Next/online-plus/node_modules/vuex/package.json

**Comment by fxy060608** [comment]
未重现，发测试工程，说明测试环境，测试步骤

**Comment by mentoorliubin** [comment]
> 未重现，发测试工程，说明测试环境，测试步骤

<img width="1134" alt="WX20220430-234201@2x" src="https://user-images.githubusercontent.com/52729282/166112566-78581712-77d3-4414-9665-55fcfc7d3bed.png">
[test.zip](https://github.com/dcloudio/uni-app/files/8597256/test.zip)
以上为测试工程，直接创建后的基本工程

**Comment by fxy060608** [comment]
> https://github.com/dcloudio/uni-app/files/8597256/test.zip

下载你的压缩包，在 Mac 上，h5、app、mp-weixin均无问题

**Comment by fxy060608** [comment]
> > 未重现，发测试工程，说明测试环境，测试步骤
> 
> <img alt="WX20220430-234201@2x" width="1134" src="https://user-images.githubusercontent.com/52729282/166112566-78581712-77d3-4414-9665-55fcfc7d3bed.png">
> 
> [test.zip](https://github.com/dcloudio/uni-app/files/8597256/test.zip) 以上为测试工程，直接创建后的基本工程

查看你的node版本号，如果过高，或者过低，均调整升级下，我的是 16

**Comment by mentoorliubin** [comment]
> > > 未重现，发测试工程，说明测试环境，测试步骤
> > 
> > 
> > <img alt="WX20220430-234201@2x" width="1134" src="https://user-images.githubusercontent.com/52729282/166112566-78581712-77d3-4414-9665-55fcfc7d3bed.png">
> > [test.zip](https://github.com/dcloudio/uni-app/files/8597256/test.zip) 以上为测试工程，直接创建后的基本工程
> 
> 查看你的node版本号，如果过高，或者过低，均调整升级下，我的是 16

感谢，确实是node版本的问题，我的是17版本的，降级之后可以正常运行了
