### ISSUE TITLE
IOS11系统中使用for in无法取值

### ISSUE THREAD

**Issue by moke8** [dcloudio/uni-app#3478]
**问题描述**
IOS11系统中，使用for in无法取值，微信受限于系统无法升级停留在版本8.0.15
如
for index in obj
console.log(obj[index])  // 取值内容为index值 而不是 obj[index]的值   

比如[data,data,data] 取值  为 obj[0]    得   0（下标）   而不是 data（实际数据）

**复现步骤**
    for (let index = 0; index < insurancePerson.value.length; index++) {
        console.log('员工数据取值是：')
        console.log(insurancePerson.value[index])
        const workerItem = insurancePerson.value[index]
        if (!workerItem.occupation_id && props.type === 'add') {
            toast(`请为员工${workerItem.name}设置工种`)
            console.log('请为员工设置工种')
            console.log(workerItem)
            console.log(insurancePerson.value)
            return
        }
        if (!/^\d{17}[Xx\d]$/g.test(workerItem.idcard)) {
            toast(`员工${workerItem.name}身份证号格式错误`)
            return
        }
    }

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 IOS11.4.1
 - uni-app版本 3.0.0-alpha-3040720220422004
 - 设备信息 iPhone8

**补充信息**
目前无法在真机调试和开发者工具中复现，该机型真机调试没有问题
使用for in 的index不行，但是手动用 for (index=1;index< length; index++) 的方式没有问题

**Comment by Otto-J** [comment]
看起来是系统较低，部分特性不受支持，可以尝试 es6->es5 功能进行兼容
