### ISSUE TITLE
如何在入口文件里面嵌入骨架屏?

### ISSUE THREAD

**Issue by ranwawa** [dcloudio/uni-app#348]
**业务背景**
- 做首页骨架屏
- 用到的webpack插件: page-skeleton-webpack-plugin
- 插件需要在 `app.vue` 中 `#app` 节点下面放一个节点用于替换骨架屏内容
**遇到的困难**
- `uni-app`中`app.vue` 文件没有template节点
**问题**
- 在哪里修改默认配置,可以自定义入口文件内容
**建议**
- 做文档的时候,可以参考下小程序的开发指南中的底层框架..https://developers.weixin.qq.com/ebook?action=get_post_info&token=935589521&volumn=1&lang=zh_CN&book=miniprogram&docid=0000e82f924ca0bb00869a5de5ec0a
- 把底层的东西也在文档里面讲一讲就最好不过了
- 毕竟我们这种看源码比较吃力的人还是需要引导下的哈

*经过前面章节的学习，相信大家对小程序开发已经非常熟悉了。从这一章开始，我们会向大家介绍在编写小程序代码背后的方方面面的细节，而在这一章里我们会先深入小程序底层，介绍底层的架构设计，一些细节原理，以及大家所熟悉的组件系统。通过这一章的学习，我们可以在之后的小程序开发中编写出更合理的代码，遇到问题可以有依据可循，能想到更好的解决办法。*

**Comment by StrivingRabbit** [comment]
可以参考[自定义模板](https://uniapp.dcloud.io/collocation/manifest?id=h5-template)
