### ISSUE TITLE
运行dev:h5，报错 r is not function

### ISSUE THREAD

**Issue by chinafelix** [dcloudio/uni-app#3482]
**问题描述**
- 小程序运行正常，运行h5端的时候，报错 “ r is not function”，之前用uniapp做过另外一个h5，是正常的；经过排查，发现是node_modules/@babel/runtime/helpers/_typeof.js的模块导出有问题，它使用module.exports 导出，编译成h5时，使用了['default']接收，将module.exports 改成 export default后正常。
- @babel/runtime是脚手架初始化的，为什么有的项目正常，有的项目会出现这种情况？

**系统信息:**
 - 发行平台: H5平台
 - 操作系统: macOS 10.15.2
 - uni-app版本: uni-app v3.2.9
uni-app cli v2.0.0-32920210927002

Environment Info:

  System:
    OS: macOS 10.15.2
    CPU: (4) x64 Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz
  Binaries:
    Node: 14.17.0 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.13 - /usr/local/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Firefox: 99.0.1
    Safari: 13.0.4
  npmPackages:
    @dcloudio/types: * => 2.5.12 
    @dcloudio/uni-app-plus: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-automator: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/uni-cli-i18n: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/uni-cli-shared: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/uni-h5: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/uni-helper-json: * => 1.0.13 
    @dcloudio/uni-i18n: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/uni-migration: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/uni-mp-360: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/uni-mp-alipay: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/uni-mp-baidu: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/uni-mp-kuaishou: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/uni-mp-qq: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/uni-mp-toutiao: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/uni-mp-vue: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/uni-mp-weixin: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/uni-quickapp-native: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/uni-quickapp-webview: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/uni-stat: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/uni-template-compiler: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-32920210927002 => 2.0.0-32920210927002 
    @hap-toolkit/dsl-vue:  0.6.13 
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.1.1 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.14 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.14 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.14 
    @vue/cli-plugin-router:  4.5.14 
    @vue/cli-plugin-typescript: * => 4.5.14 
    @vue/cli-plugin-vuex:  4.5.14 
    @vue/cli-service: ~4.5.0 => 4.5.14 
    @vue/cli-shared-utils:  4.5.14 
    @vue/component-compiler-utils:  3.2.2 (3.2.2)
    @vue/devtools-api:  6.0.0-beta.15 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/shared: ^3.0.0 => 3.2.20 
    @vue/web-component-wrapper:  1.3.0 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.11 => 2.6.14 
    vue-class-component: ^6.3.2 => 6.3.2 (7.2.6)
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.8 (16.8.1, 15.9.8)
    vue-property-decorator: ^8.0.0 => 8.5.1 
    vue-router:  3.0.1 
    vue-style-loader:  4.1.3 (4.1.3)
    vue-template-compiler: ^2.6.11 => 2.6.14 (2.6.14)
    vue-template-es2015-compiler:  1.9.1 
    vue3:  1.0.0 
    vuex: ^3.2.0 => 3.6.2 (3.6.2)
    vuex-class: ^0.3.2 => 0.3.2 
  npmGlobalPackages:
    @vue/cli: Not Found

**Comment by StrivingRabbit** [comment]
使用最新版试试
