### ISSUE TITLE
使用vue3 vite ts，打包后会执行2次初始化

### ISSUE THREAD

**Issue by xushuailing** [dcloudio/uni-app#3483]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  下载模板 https://gitee.com/dcloud/uni-preset-vue/repository/archive/vite-ts.zip
2. 在src/main.ts中打印一句话
3.  安装依赖，打包h5 `yarn build:h5`
4.  部署上线

[或者可以直接贴源代码]

**预期结果**
只执行一次初始化操作

**实际结果**
执行二次

**系统信息:**
 - 发行平台: 微信小程序、H5平台
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - uni-app版本 
 ```
 ❯ npm ls --depth 0  
uni-preset-vue@0.0.0 /Users/xsl/web/github/uni-preset-vue-vite-ts
├── @dcloudio/types@2.6.6
├── @dcloudio/uni-app@3.0.0-alpha-3040820220428001
├── @dcloudio/uni-app-plus@3.0.0-alpha-3040820220428001
├── @dcloudio/uni-automator@3.0.0-alpha-3040820220428001
├── @dcloudio/uni-cli-shared@3.0.0-alpha-3040820220428001
├── @dcloudio/uni-components@3.0.0-alpha-3040820220428001
├── @dcloudio/uni-h5@3.0.0-alpha-3040820220428001
├── @dcloudio/uni-mp-alipay@3.0.0-alpha-3040820220428001
├── @dcloudio/uni-mp-baidu@3.0.0-alpha-3040820220428001
├── @dcloudio/uni-mp-kuaishou@3.0.0-alpha-3040820220428001
├── @dcloudio/uni-mp-lark@3.0.0-alpha-3040820220428001
├── @dcloudio/uni-mp-qq@3.0.0-alpha-3040820220428001
├── @dcloudio/uni-mp-toutiao@3.0.0-alpha-3040820220428001
├── @dcloudio/uni-mp-weixin@3.0.0-alpha-3040820220428001
├── @dcloudio/uni-quickapp-webview@3.0.0-alpha-3040820220428001
├── @dcloudio/vite-plugin-uni@3.0.0-alpha-3040820220428001
├── typescript@4.6.4
├── vite@2.9.8
├── vue@3.2.33
├── vue-i18n@9.1.10
└── vuex@4.0.2
```

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by xushuailing** [comment]
已解决 js 重定向问题

**Comment by xushuailing** [comment]
使用 vite 初始化的 vue-ts 模板，部署上线后重定向的资源，就不存在重复执行的问题。

**Comment by fxy060608** [comment]
未重现
1. 下载zip
2. main.ts
```js
import { createSSRApp } from "vue";
import App from "./App.vue";
console.log('123');
export function createApp() {
  const app = createSSRApp(App);
  return {
    app,
  };
}
```
3. yarn build:h5
4. 使用 serve 本地运行，测试无问题
如果你测试有问题，发完整的测试步骤，或线上访问地址

**Comment by xushuailing** [comment]
> 回未
> 
> 1. 下载zip
> 2. main.ts
> 
> ```js
>  从“vue”导入{  createSSRApp  }  ；从“./App.vue”导入应用程序；控制台。日志（'123' ）；导出函数createApp ( ) { const app = createSSRApp ( App ) ; 返回{
>     应用程序，} ；} 
>    
> 
>    
>      
>    
>   
> ```
> 
> 3. 纱线构建：h5
> 4. 使用服务本地运行，测试无问题
>    如果你测试有问题，发完整的测试步骤，或在线访问地址

vue vite https://tst-app.shencom.cn/recycle-bank1/index.html#/
uniapp vite https://tst-app.shencom.cn/recycle-bank2/index.html#/

**Comment by xushuailing** [comment]
> 未重现
> 
> 1. 下载zip
> 2. main.ts
> 
> ```js
> import { createSSRApp } from "vue";
> import App from "./App.vue";
> console.log('123');
> export function createApp() {
>   const app = createSSRApp(App);
>   return {
>     app,
>   };
> }
> ```
> 
> 3. yarn build:h5
> 4. 使用 serve 本地运行，测试无问题
>    如果你测试有问题，发完整的测试步骤，或线上访问地址

vue vite : https://tst-app.shencom.cn/recycle-bank1/index.html#/
uniapp vite : https://tst-app.shencom.cn/recycle-bank2/index.html#/

**Comment by fxy060608** [comment]
> https://tst-app.shencom.cn/recycle-bank1/index.html#/

为何要采用这种js文件会redirect的方式部署？理论上应该跟uni-app无关
你给的vue vite示例太简单了，可以采用vue+vue-router+路由懒加载再测试下，应该也存在这种问题
