### ISSUE TITLE
在Vue3.0+ts中遇到的问题

### ISSUE THREAD

**Issue by davidchen27** [dcloudio/uni-app#3485]
**问题描述**
使用hideLoading的时候, 控制台出现警告:
[Vue warn]: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead. 
经过调试发现, 是因为在uni.request的complete中调用hideLoading会出现这个情况

**复现步骤**
[复现问题的步骤]
1. 在uni.request前使用uni.showLoading, 显示加载提示
2. 然后下面使用uni.request进行API请求, 在complete或者success或者fail中使用hideLoading
3. loading隐藏了, 但是控制台出现问题描述中的警告信息(只要不在uni.request的回调中使用hideLoading, 就不会出现问题)

[或者可以直接贴源代码]

**预期结果**
控制台干净无警告

**实际结果**
控制台出现警告信息:
[Vue warn]: Slot "default" invoked outside of the render function: this will not track dependencies used in the slot. Invoke the slot function inside the render function instead. 

**系统信息:**
 - 发行平台: h5, h5 ssr
 - 操作系统 windows10
 - uni-app版本 "@dcloudio/uni-app": "3.0.0-alpha-3040820220424001",
 - 设备信息 联想Yoga14s 2021锐龙版

**Comment by davidchen27** [comment]
请问是代码的问题还是😅

**Comment by StrivingRabbit** [comment]
稍后会确认一下问题

**Comment by davidchen27** [comment]
没有页面的跳转, 就是在uni.request的回调中使用uni.hideLoading或者hideToast, 都会出现这个警告

**Comment by StrivingRabbit** [comment]
@davidchen27 vue3 项目运行到 h5 ssr ，没有发现你说的问题

**Comment by davidchen27** [comment]
你试试在h5模式下，刷新下页面几次看看有没有这个情况，如果没有的话， 可能就是我的问题了😂

**Comment by davidchen27** [comment]
我之前描述的不够详细， 我发现，使用await来接收目标函数，才会引发这个警告问题
`function baseRequest<T>(options: RequestOptions): Promise<RequestResult<T>> {
  const { userInfo } = useUserStore()

  return new Promise((resolve, reject) => {
    /* 需要登录的接口, 请求前拦截 */
    if (options.needAuth && !userInfo) {
      uni.showModal({
        title: '登录提示',
        content: '你还未登录, 请先登录!',
        confirmText: '去登录',
        showCancel: false
      })
      uni.navigateTo({
        url: '/login'
      })
      return
    }
    uni.showLoading({
      title: '加载中...',
      mask: true
    })
    uni.request({
      url: baseApi + options.url,
      method: options.method,
      data: options.data || {},
      timeout: TIME_OUT,
      header: Object.assign(
        {
          'content-type':
            options.method === 'GET' ? 'application/json; charset=utf-8' : 'application/x-www-form-urlencoded'
        },
        options.needAuth ? { [TOKEN_NAME]: 123 } : {}
      ),
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      success(result: any) {
        /* 状态码为200, 则直接通过放行 */
        if (result.statusCode === 200 && (result.data as { code: number }).code === 200) {
          resolve(result.data)
          return
        }
        /* 其中一个状态码不为200, 则进行错误拦截处理, 而后再返回 */
        const errorCatch = new ErrorCatch(result.statusCode)
        resolve(errorCatch.call(result))
      },
      fail() {
        reject('网络不给力, 请检查你的网络设置...')
      },
      complete() {
        uni.hideLoading()
      }
    })
  })
}`
就比如这个方法，我用await的方式接收他的返回值， 就会导致描述中的警告问题， 而使用then处理则不会
