### ISSUE TITLE
关于nvue页面中onBackPress生命周期在通过this.$scope.$getAppWebview().close()方法销毁时 onBackPress仍然存在的问题

### ISSUE THREAD

**Issue by Iongtao** [dcloudio/uni-app#3486]
**问题描述**
关于nvue页面中onBackPress生命周期在通过this.$scope.$getAppWebview().close()方法销毁时 onBackPress仍然存在的问题

**复现步骤**
从A页面(vue)路由跳转到B页面(nvue)
在B页面中通过onBackPress拦截返回事件。我这里默认返回true 只通过this.$scope.$getAppWebview().close()来关闭当前页面。
同时监听onUnload事件：
<img width="632" alt="image" src="https://user-images.githubusercontent.com/24762616/167105911-f81140c0-2dc4-4dd6-828d-346b8c4a586d.png">
页面已经被卸载了然后在A页面仍然会触发B页面中的onBackPress事件
B页面中的代码：
<img width="751" alt="image" src="https://user-images.githubusercontent.com/24762616/167106088-a2564af1-567c-45f1-a008-d18b459ddb74.png">

通过默认的回退机制正常

**预期结果**
A页面正常返回

**实际结果**
A页面无法返回

**系统信息:**
 - 发行平台: App
 - 操作系统 ios15.3模拟器
 - HBuilderX版本 3.4.7
 - uni-app版本 
 - 设备信息 iphone8模拟器

**补充信息**
不知

**Comment by fxy060608** [comment]
不要自行关闭webview或nvue，会打乱框架路由
