### ISSUE TITLE
uniapp 采用固定定位，做弹窗APP底部留白问题

### ISSUE THREAD

**Issue by zhufaming** [dcloudio/uni-app#3487]
![132C13914DEE3F04ADE635C712187A30](https://user-images.githubusercontent.com/15395337/167132484-38844d56-649f-4189-9b52-d86040fa9aa6.jpg)
`.a-s-mask{
		position: fixed;
		top: 0px;
		left: 0px;
		right: 0px;
		bottom: 0px; 
		z-index: 10000;
		opacity: 1;
		background-color: rgba(0, 0, 0, 0.6);
		transition: all 0.3s ease; 
	}`

**问题描述**
[想做一个弹窗蒙层，目前是手机APP ，iOS WKWebView，接入H5连接]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
配置webview style的contentAdjust为false或者将元素高度设置为100vh
