### ISSUE TITLE
vue3官方默认模板 运行为h5时，无法在vue-devtools中查看组件状态

### ISSUE THREAD

**Issue by changexbc** [dcloudio/uni-app#3492]
**问题描述**
vue3官方默认模板 运行为h5时，无法在vue-devtools（版本6.1.4）中查看组件状态
![image](https://user-images.githubusercontent.com/8199684/167423817-a4dd08bd-2230-4298-b31b-b6fe21ec4754.png)

**复现步骤**
1. 使用 hbuilderX alpha 3.6.9 新建项目
2. 选择 默认模板 vue3 版本
3. 运行项目到chrome浏览器
4. 在chrome中使用vue-devtools查看Index组件的相关状态
5. 无法显示组件相关状态信息
![屏幕截图 2022-05-09 202656](https://user-images.githubusercontent.com/8199684/167424118-a8d01dbe-89a8-44b3-9c6c-793d5ef54b26.png)

**预期结果**
使用vue-devtools可正常查看组件状态

**实际结果**
使用vue-devtools无法正常查看组件状态

**系统信息:**
 - 发行平台:H5平台
 - 操作系统 Windows 11 家庭中文版 macOS 12.3.1 
 - HBuilderX版本 3.4.9.20220508-alpha
 - 设备信息 windows mac均有此问题

**补充信息**
在edge，firefox上都试过，均有此问题。
只有当前路由根组件无法查看，猜测跟ssr有关，看了下uniapp好像无法使用createApp的方式只能createSSRApp。

**Comment by zhetengbiji** [comment]
HBuilderX alpha 3.4.10+ 已经修复
