### ISSUE TITLE
vue3 ref获取到组件后，没有找到组件内的方法

### ISSUE THREAD

**Issue by pengjinlong** [dcloudio/uni-app#3494]
**问题描述**
vue3 ref获取组件，没有找到组件内的方法

**复现步骤**
[复现问题的步骤]
子组件：
```<template>
  <view>child</view>
</template>

<script setup lang="ts">
import { ref } from 'vue'

function testFunc() {
  console.log('test')
}
</script>

<style lang="scss"></style>
```

父组件：
```
<template>
  <child ref="childRef" />
</template>

<script setup lang="ts">
import { ref, onMounted} from 'vue'
const childRef= ref()

onMounted(() => {
  console.log(childRef.value.testFunc)
  console.log(childRef.value.$scope)
})

</script>

<style lang="scss"></style>

```

**预期结果**
打印出子组件内的方法函数

**实际结果**
微信开发者工具打印如下：
![image](https://user-images.githubusercontent.com/26454874/167548478-e898da97-5adc-444a-9b68-b9ffb4122b25.png)

![image](https://user-images.githubusercontent.com/26454874/167547947-f0cf9d4c-295f-4080-98d7-a6a0f04dc463.png)
打印结果中无法找到组件内的方法，也就是父组件无法直接调用子组件的方法，请求要如何才能调用呢

**系统信息:**
    "@dcloudio/uni-automator": "3.0.0-alpha-3040820220424001",
    "@dcloudio/uni-cli-shared": "3.0.0-alpha-3040820220424001",
    "@dcloudio/vite-plugin-uni": "3.0.0-alpha-3040820220424001",

**Comment by fxy060608** [comment]
https://staging-cn.vuejs.org/api/sfc-script-setup.html#defineexpose
