### ISSUE TITLE
允许重新打包，建议可配置关闭dc_checkappkey

### ISSUE THREAD

**Issue by etjson** [dcloudio/uni-app#3495]
允许重新打包，建议可配置关闭dc_checkappkey，建议提供一个配置项可以操作这个，现在每次打包都要手动去改sdk很麻烦，希望官方直接提供一个配置参数出来关闭它。

**Comment by huaxinbiao** [comment]
改SDK在什么位置呀

**Comment by lony2003** [comment]
@etjson 怎么改SDK呀，在哪个位置
