### ISSUE TITLE
vite.config.ts中的条件编译不生效

### ISSUE THREAD

**Issue by llk2yq** [dcloudio/uni-app#3496]
**问题描述**
`vite.config.ts`中的条件编译不生效

**复现步骤**
[复现问题的步骤]
执行 `npm run dev:h5`,会发现`vite.config.ts`中的条件编译不生效。

[测试工程](https://github.com/dcloudio/uni-app/files/8659215/test-if.zip)

**Comment by llk2yq** [comment]
用`cross-env`绕过了这个问题。

**Comment by fxy060608** [comment]
vite.config.ts不支持条件编译，可以使用ts代码控制，访问：process.env.UNI_PLATFORM
