### ISSUE TITLE
uni-cli  h5模式下拨打电话失败

### ISSUE THREAD

**Issue by chenghao94** [dcloudio/uni-app#3497]
**问题描述**
使用官方uni.makePhoneCall的方法

**复现步骤**
[复现问题的步骤]
      uni.makePhoneCall({
        phoneNumber: this.number,
        success: () => {
          this.$toast('拨打电话成功！');
        },
        fail: () => {
          this.$toast('拨打电话失败！');
        }
      });

**预期结果**
  可以唤起系统的拨打电话

**实际结果**
   直接执行fail回调函数，控制台并没有报错

**系统信息:**
uni-app cli v2.0.1-34720220422002

Environment Info:

  System:
    OS: macOS 12.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Binaries:
    Node: 14.17.4 - /usr/local/bin/node
    Yarn: 1.22.17 - /usr/local/bin/yarn
    npm: 6.14.14 - /usr/local/bin/npm
  Browsers:
    Chrome: 101.0.4951.54
    Firefox: 95.0.2
    Safari: 15.2
  npmPackages:
    @dcloudio/types: * => 2.6.6 
    @dcloudio/uni-app-plus: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-automator: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-cli-i18n: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-cli-shared: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-h5: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-helper-json: * => 1.0.13 
    @dcloudio/uni-i18n: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-migration: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-mp-360: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-mp-alipay: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-mp-baidu: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-mp-jd: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-mp-kuaishou: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-mp-lark: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-mp-qq: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-mp-toutiao: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-mp-vue: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-mp-weixin: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-quickapp-native: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-quickapp-webview: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-stat: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/uni-template-compiler: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/vue-cli-plugin-uni: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/webpack-uni-mp-loader: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.1-33920220208001 => 2.0.1-34720220422002 
    @hap-toolkit/dsl-vue:  0.6.13 
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.1.1 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.17 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.17 
    @vue/cli-plugin-babel: ~4.5.13 => 4.5.17 
    @vue/cli-plugin-router:  4.5.17 
    @vue/cli-plugin-vuex:  4.5.17 
    @vue/cli-service: ~4.5.13 => 4.5.17 
    @vue/cli-shared-utils:  4.5.17 
    @vue/component-compiler-utils:  3.3.0 (3.3.0)
    @vue/devtools-api:  6.0.0-beta.15 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/shared: ^3.0.0 => 3.2.33 
    @vue/web-component-wrapper:  1.3.0 
    @wpg/eslint-config-vue: ^2.0.5 => 2.1.2 
    @wpg/icons-vue:  2.0.0 
    eslint-plugin-vue:  8.7.1 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.11 => 2.6.14 
    vue-eslint-parser:  7.11.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.8 (16.8.3, 15.9.8)
    vue-pswipe:  0.15.3 
    vue-router:  3.5.3 (3.5.3)
    vue-style-loader:  4.1.3 (4.1.3)
    vue-svgicon:  3.2.9 
    vue-template-compiler: ^2.6.11 => 2.6.14 (2.6.14)
    vue-template-es2015-compiler:  1.9.1 
    vue3:  1.0.0 
    vuex: ^3.2.0 => 3.6.2 (3.6.2)

 - 设备信息 
    iphone 13 Safari浏览器

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
其他设备是否成功？

**Comment by chenghao94** [comment]
@zhetengbiji 安卓机器也不行，都是通过手机浏览器访问的页面

**Comment by zhetengbiji** [comment]
> @zhetengbiji 安卓机器也不行，都是通过手机浏览器访问的页面

测试这个页面是否正常：https://hellouniapp.dcloud.net.cn/pages/API/make-phone-call/make-phone-call

**Comment by chenghao94** [comment]
@zhetengbiji 这个例子是可以的呢？所以我就怀疑uni-cli这个框架是不是哪里要配置什么的才能调用打电话

**Comment by chenghao94** [comment]
使用h5的原生方法：window.location.href = `tel:${this.number}`; 是可以打电话的；但是调用uni.makePhoneCall就直接走了fail回调了

**Comment by zhetengbiji** [comment]
> 使用h5的原生方法：window.location.href = `tel:${this.number}`; 是可以打电话的；但是调用uni.makePhoneCall就直接走了fail回调了

回调的错误打印一下看看
