### ISSUE TITLE
v-if条件 编译为微信小程序错误

### ISSUE THREAD

**Issue by innovational** [dcloudio/uni-app#3498]
**问题描述**

源码为
v-if="(['add','apply'].includes(item.type)&&apply[item.type+'List'].length) || !['add','apply'].includes(item.type)"
编译后为
var g0 = ["add", "apply"].includes(item.type) && _vm.apply[item.type + "List"].length
var g1 = item.g0 || !["add", "apply"].includes(item.type)

注意 “var g1 = item.g0 || !["add", "apply"].includes(item.type)” 此处 item.g0 是不对的 应该为 g0 || !["add", "apply"].includes(item.type)

ask地址（里面有复现demo）
https://ask.dcloud.net.cn/question/144808

**Comment by zhetengbiji** [comment]
参考：https://ask.dcloud.net.cn/question/143936
