### ISSUE TITLE
Vue3 支付宝小程序中使用uni.navigateTo()跳转页面，被跳转页面无法收到eventChannel传递的数据。

### ISSUE THREAD

**Issue by cscxj** [dcloudio/uni-app#3499]
**问题描述**
Vue3 支付宝小程序中使用uni.navigateTo()跳转页面，在首页eventChannel.emit()传递数据，在被跳转页面eventChannel.on()监听不到数据。

**复现步骤**
demo仓库: [https://github.com/single-thread/uni-demo](https://github.com/single-thread/uni-demo)
用HBuilderX打开项目编译运行，或直接用支付宝开发者工具打开dist目录查看运行结果

首页：
```javascript
uni.navigateTo({
	url:'/pages/test/test',
	success({ eventChannel }) {
		eventChannel.emit('testData', { value: '测试数据' })
	}
})
```
被跳转页面：
```javascript
onLoad() {
	const eventChannel = this.getOpenerEventChannel();
	eventChannel.on('testData', function(data) {
		console.log(data)
	})
}
```
**预期结果**
跳转页面后控制台输出`{ value: "测试数据" }`

**实际结果**
微信小程序输出`{ value: "测试数据" }`
支付宝小程序没有反应

**系统信息:**
 - 发行平台: 支付宝小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 3.4.7.20220422
 - 设备信息 Redme K40

**补充信息**

**Comment by Otto-J** [comment]
感谢反馈，新版本未能复现这个问题，可能中间已经修复过了这个问题。

我提供的案例可以参考这个项目来验证
https://gitcode.net/xiurensha5731/uni-app-questions/-/tree/q/api-emit2/src/pages
