### ISSUE TITLE
条件编译能不能增加-else-if分支?

### ISSUE THREAD

**Issue by sundaylover** [dcloudio/uni-app#350]
**新功能描述**
很多时候只是需要针对某个平台做兼容性处理，比如我用plus自定义了一个loading，兼容H5页面需要用自带的loading，这种情况只要一个else分支就可以，比如下面这样：

showLoading:function(msg = language.loading){
	//#ifdef H5
	uni.showLoading({title:msg, mask:true})
	//#else
	global.loading = plus.nativeUI.showWaiting(msg, {"padding":"20px", "color":"#f0f0f0", "background":"rgba(35, 26, 0, 0.8)", "back":"none"})
	//#endif
}

多写一个#ifndef感觉很难受

**Comment by victoryboss** [comment]
我觉得必要加else吧，你可以这样写条件编译
//#ifdef H5
uni.showLoading({title:msg, mask:true})
//#endif
//#ifndef H5
uni.showLoading({title:msg, mask:false})
//#endif

**Comment by pasefenny** [comment]
@victoryboss 

这么写不觉得很难受么？明明是一个逻辑判断非要拆成两个，平常的判断都是if-else，这里突然要写成if/ifnot，很不习惯

**Comment by victoryboss** [comment]
构建工具代码层要做这种条件编译  else  处理估计很难，很复杂，要判断的太多，哈哈，我反正不建议

**Comment by pasefenny** [comment]
好吧，表示理解

**Comment by xiaoyucoding** [comment]
没有 ELSE 的规范，感谢反馈。

**Comment by liuyingqq123** [comment]
> 目前没有 ELSE 的规范，这个在定制规范以及后续都调研过，没有较为合理的方案。
> 感谢反馈

能帮忙看下https://github.com/dcloudio/uni-app/issues/1008这个问题吗?
自定义的平台,
// #ifdef 无法用or的条件
