### ISSUE TITLE
vite + vue3 打包没有将 小图片转换base64

### ISSUE THREAD

**Issue by abinnq** [dcloudio/uni-app#3501]
**问题描述**
dev或build 时没有将本地相对路径引用图片转为base64
build时在vite.config 配置 build.assetsInlineLimit: 999999; 也无效

环境：微信小程序
uni版本： 3.0.0-alpha-3040920220506001
vite： 2.9.5
vue： 3

**预期结果**
可以转换为base64

**Comment by abinnq** [comment]
> 模板里image引用的图片base64的意义是什么？

vue-cli升级vite时遇到了旧代码如此引用的，旧版本的vue-cli在模板里image本地图片可以压缩为base64，
建议放在vite升级文档里面，现在改为使用css 引用base64

**Comment by fxy060608** [comment]
> > 模板里image引用的图片base64的意义是什么？
> 
> vue-cli升级vite时遇到了旧代码如此引用的，旧版本的vue-cli在模板里image本地图片可以压缩为base64， 建议放在vite升级文档里面，现在改为使用css 引用base64

我的意思是image标签引用本地图片是可以正常使用的，没有必要转换成base64，转不转都不影响使用，转了反而会增加大小，css中转base64是因为微信不支持在css中引用本地图片，只能转成base64，这个不是压缩，这个会额外增加大小的

**Comment by abinnq** [comment]
> > > 模板里image引用的图片base64的意义是什么？
> > 
> > 
> > vue-cli升级vite时遇到了旧代码如此引用的，旧版本的vue-cli在模板里image本地图片可以压缩为base64， 建议放在vite升级文档里面，现在改为使用css 引用base64
> 
> 我的意思是image标签引用本地图片是可以正常使用的，没有必要转换成base64，转不转都不影响使用，转了反而会增加大小，vue2如果转了，反而是不正确的，css中转base64是因为微信不支持在css中引用本地图片，只能转成base64，这个不是压缩，这个会额外增加大小的

明白了

**Comment by fan-tian-bao** [comment]
> > > 模板里image引用的图片base64的意义是什么？
> > 
> > 
> > vue-cli升级vite时遇到了旧代码如此引用的，旧版本的vue-cli在模板里image本地图片可以压缩为base64， 建议放在vite升级文档里面，现在改为使用css 引用base64
> 
> 我的意思是image标签引用本地图片是可以正常使用的，没有必要转换成base64，转不转都不影响使用，转了反而会增加大小，vue2如果转了，反而是不正确的，css中转base64是因为微信不支持在css中引用本地图片，只能转成base64，这个不是压缩，这个会额外增加大小的

请问一下css中如何转base64呢,vite中的assetsInlineLimit我也有设置

**Comment by dw08** [comment]
src转base64减少http请求。。。至少提供个指引怎么转吧
