### ISSUE TITLE
qq 小程序，editor  组件加载后没有触发 @ready 方法

### ISSUE THREAD

**Issue by makesense2022** [dcloudio/uni-app#3502]
**问题描述**
vue-cli 创建的工程 vue2 代码
editor 组件加载后没有触发 @ready 方法
用的官方的 demo  测试https://uniapp.dcloud.io/component/editor

**复现步骤**
<editor id="editor" class="ql-container" :placeholder="placeholder" @ready="onEditorReady"></editor>

**预期结果**

**实际结果**
onEditorReady 并没有进入

**系统信息:**
 - 发行平台: qq小程序

    "@dcloudio/uni-app": "^3.0.0-alpha-3040620220415003",
    "@dcloudio/uni-app-plus": "^3.0.0-alpha-3040620220415003",
    "@dcloudio/uni-components": "^3.0.0-alpha-3040620220415003",
    "@dcloudio/uni-h5": "^3.0.0-alpha-3040620220415003",
    "@dcloudio/uni-mp-alipay": "^3.0.0-alpha-3040620220415003",
    "@dcloudio/uni-mp-baidu": "^3.0.0-alpha-3040620220415003",
    "@dcloudio/uni-mp-kuaishou": "^3.0.0-alpha-3040620220415003",
    "@dcloudio/uni-mp-lark": "^3.0.0-alpha-3040620220415003",
    "@dcloudio/uni-mp-qq": "^3.0.0-alpha-3040620220415003",
    "@dcloudio/uni-mp-toutiao": "^3.0.0-alpha-3040620220415003",
    "@dcloudio/uni-mp-weixin": "^3.0.0-alpha-3040620220415003",
    "@dcloudio/uni-quickapp-webview": "^3.0.0-alpha-3040620220415003",
    "@dcloudio/uni-ui": "^1.4.13",

**Comment by fxy060608** [comment]
1. 说明vue2,vue3
2. 贴代码

**Comment by fxy060608** [comment]
vue2测试没有问题，
vue3有问题
