### ISSUE TITLE
`picker`在H5端报错

### ISSUE THREAD

**Issue by llk2yq** [dcloudio/uni-app#3505]
**问题描述**
`picker`在H5端报错，微信小程序端暂时未发现此问题。

**复现步骤**
[复现问题的步骤]
打开`picker`后，点击确定，控制台有报错。

![报错信息](https://user-images.githubusercontent.com/22813922/168002753-0823aa29-56b2-42aa-bf20-82c5c603d09a.png)

[测试工程](https://github.com/dcloudio/uni-app/files/8675350/test-picker.zip)

**Comment by llk2yq** [comment]
补充：H5端会报错，但是似乎不影响正常触发`change`事件。

**Comment by fxy060608** [comment]
已修复：https://github.com/dcloudio/uni-app/commit/eb68438047c90a752ad5ea33b7877d54feab1e14

**Comment by llk2yq** [comment]
![image](https://user-images.githubusercontent.com/22813922/168003927-aa880439-2af1-4a5f-8455-486c4e51bd33.png)

@fxy060608 请问一下，上面哪一个是最新的呀？

**Comment by fxy060608** [comment]
> ![image](https://user-images.githubusercontent.com/22813922/168003927-aa880439-2af1-4a5f-8455-486c4e51bd33.png)
> 
> @fxy060608 请问一下，上面哪一个是最新的呀？

可以使用第二个，第一个是我们内部最新

**Comment by llk2yq** [comment]
好的，谢谢。
希望可以改进一下命名规则。

**Comment by llk2yq** [comment]
要怎么样才会不报错啊，升级到了最新的还是会报错.
@fxy060608

**Comment by fxy060608** [comment]
> 要怎么样才会不报错啊，升级到了最新的还是会报错. @fxy060608

锁定版本到：3.0.0-alpha-3040820220424005 试试
