### ISSUE TITLE
【vue3】hooks 中使用页面的生命周期方法

### ISSUE THREAD

**Issue by sufuwang** [dcloudio/uni-app#3506]
**问题描述**
在页面 setup 中调用 hooks ，hooks 中调用 uni 的生命周期方法
```vue
setup() {
  useHooks(); // 内部调用 onPageScroll 方法
  onPageScroll(() => {})
}
```
为什么需要在页面中调用一次 onPageScroll 方法呀？

**系统信息:**
 - uni-app版本 3.0.0-alpha-3040920220508001

**Comment by fxy060608** [comment]
onPageScroll 本身是页面的事件，在小程序端，必须在定义页面的时候就注册进去，没法动态注册（setup 是运行时执行的）
而且 onPageScroll 影响性能，框架也不能默认给所有页面都自动注册上去，所以只能编译时，扫描你的页面代码里，如果包含了 onPageScroll ，再自动注册。
