### ISSUE TITLE
pages.json 支持 【支付宝小程序设置导航栏图标主题】

### ISSUE THREAD

**Issue by JimmyZDD** [dcloudio/uni-app#3508]
**新功能描述**

https://opendocs.alipay.com/mini/framework/page-json
pages.json 支持 页面配置支持【支付宝小程序设置导航栏图标主题】
barButtonTheme   设置导航栏图标主题，仅支持真机预览。"default" 为蓝色图标，"light" 为白色图标。

**现状及问题**
pages.style.barButtonTheme 配置不生效

**Comment by fxy060608** [comment]
通过mp-alipay节点，定义平台特有属性
```json
{
              "navigationBarTitleText": "uni-app",
              "mp-alipay": {
                  "barButtonTheme": "light"
              }
          }
```
