### ISSUE TITLE
Window 和Mac 中 uni-requset 是否支持不一致？

### ISSUE THREAD

**Issue by c1394393468** [dcloudio/uni-app#351]
**问题描述**
HBuilderX 在Window 和Mac 环境下 ，uni-app 的 uni-request 支持是否不一致？  
我在uni-requset 中使用了Promise的方式，
uni.request().then(data => {

}).catch(error => {

})

在windows 环境下是有效的 ，在mac 下报了TypeError: uni.request(...).then is not a function
Mac 版HBuilder 编出来的iOS 无法用 模拟器也不行，Window 编出来的 iOS 能使用

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: iOS 12.2
 - HBuilderX版本：1.9.0.20190412
 - uni-app版本: 跟随HBuilderX
 - 设备信息: iPhone Xs Max 

**补充信息**
HBuilderX 在Window 和Mac 环境下 ，uni-app 的 uni-request 支持是否不一致？

**Comment by fxy060608** [comment]
可更新至最新版本 HBuilderX 重新测试
