### ISSUE TITLE
picker-view组件在安卓机上不能选中

### ISSUE THREAD

**Issue by erices1** [dcloudio/uni-app#3510]
**问题描述**
[问题描述：页面外层使用css direction: rtl时候，picker-view组件在安卓机上不能选中]

**复现步骤**
[复现问题的步骤]
1、可以直接使用官方例子https://hellouniapp.dcloud.net.cn/pages/component/picker-view/picker-view，在最外层view上添加 style="direction: rtl"；在安卓机器上使用，滚动选择器无论滚动到哪都会回到第一个

[或者可以直接贴源代码]

**预期结果**
[希望能正确显示，包括iOS（还未测试）]

**实际结果**
滚动选择器未正确选中想要选择的

**系统信息:**
 - 发行平台: [ 微信小程序、H5平台、5+ App等]
 - 操作系统 [Android 11]
 - HBuilderX版本 [版本号：3.3.13.20220314]
 - 设备信息 [一加7 Pro]

**Comment by bfc846958672** [comment]
HBuilderX4.24 版本测试没有此问题， 关闭此issue。 如果能复现此bug，可reopen继续讨论
