### ISSUE TITLE
vue3发行h5，组件内的uni动态属性报错(开发模式下正常)

### ISSUE THREAD

**Issue by fangshikeji** [dcloudio/uni-app#3512]
![image](https://user-images.githubusercontent.com/76583297/168217739-d47b0293-939b-4c39-87f2-a59a24c9a92f.png)

![image](https://user-images.githubusercontent.com/76583297/168220174-ed8de25a-3015-4c9e-b75b-612e4961b26e.png)

**Comment by fxy060608** [comment]
发行模式默认开启摇树优化，会将未使用的api全部摇掉，如果要动态调用API，可以禁用摇树优化，但会增加编译后的文件大小
建议将代码调整为静态调用，比如使用if else，或switch
手动关闭摇树优化：
https://uniapp.dcloud.net.cn/tutorial/migration-to-vue3.html#h5-%E5%B9%B3%E5%8F%B0%E5%8F%91%E8%A1%8C%E6%97%B6-%E4%BC%9A%E9%BB%98%E8%AE%A4%E5%90%AF%E5%8A%A8%E6%91%87%E6%A0%91
