### ISSUE TITLE
华为快应用广告怎么接入?引入@service.ad报错

### ISSUE THREAD

**Issue by MarRoar** [dcloudio/uni-app#3518]
**需要在uniapp里面引入快引用广告**
原生快应用开发厂商广告的时候需要引入 import ad from "@service.ad"，ad 对象上会有一些方法，用来请求厂商的广告数据。
现在在 uniapp 项目里面也这样引入 ad 时候，编译会报错。
所以想问下有没有大佬在 uniapp 项目里面引入快应用广告的？

**Comment by fxy060608** [comment]
const ad = $app_require$("@app-module/system.ad");

**Comment by ben-lau** [comment]
> const ad = apprequire("@app-module/system.ad");

这个api是在哪里的，找不到
