### ISSUE TITLE
h5绑定事件target中获取不到参数

### ISSUE THREAD

**Issue by weiyunpeng** [dcloudio/uni-app#352]
**问题描述**
在h5中定义事件参数data-val="黑",使用事件处理函数@tap,获取不到target中参数。

**复现步骤**
`<div @tap="tapEvent" data-val="黑"></div>`

methods

tapEvent(e) {
console.log(e.target)
}

**预期结果**
e.target.dataset.val = “黑”

**实际结果**
e.target.dataset.val = undefind

**系统信息:**
 - 发行平台: H5平台
@dcloudio/uni-h5 0.4.8

**补充信息**
观察currentTarget.dataset.val = "黑"是有的。

**Comment by weiyunpeng** [comment]
编译成小程序后发现小程序里也有该问题：都是在currentTarget中有值target中无值。
@dcloudio/uni-mp-weixin 0.0.949

**Comment by fxy060608** [comment]
该场景下，应该使用 currentTarget 获取，currentTarget 是绑定事件的节点，target 是实际触发的节点，两者可能不一致。
