### ISSUE TITLE
uni-app v3 不会把 img 转成 <image class="_img" /> 了？

### ISSUE THREAD

**Issue by zhuscat** [dcloudio/uni-app#3520]
**问题描述**

v2 版本，template 中的 `<img />` 会被转换成 `<image class="_img" />`，样式文件中的 `img` 会被转换成 `._img`
v3 版本，template 中的 `<img />` 会被转换为 `<image role="img" />`，样式文件中的 `img` 没有被转换

**预期结果**
期望跟 v2 保持一致，或者配套转换样式文件

**系统信息:**
 - uni-app版本 3.0.0-alpha-3040920220506001

**Comment by fxy060608** [comment]
不建议使用此类样式，影响编译速度，也影响运行时性能，而且标签样式和class样式权重是不一样的，容易引发冲突
