### ISSUE TITLE
uni-app 3 样式文件中的通配符选择器，编译到 wxss 还会保留，导致编译报错

### ISSUE THREAD

**Issue by zhuscat** [dcloudio/uni-app#3522]
**问题描述**
样式文件中的通配符选择器，编译到 wxss 还会保留，导致开发者工具编译报错

如这样一段代码：

```
* {
  box-sizing: border-box
}
```

在 uni-app 2 中会直接移除，uni-app 3 中还会保留

**系统信息:**
 - 发行平台:  微信小程序
 - uni-app版本 3.0.0-alpha-3041020220516002

**Comment by fxy060608** [comment]
建议使用条件编译移除
