### ISSUE TITLE
uni-app 3 dev 模式下差量编译导致「解析 project.config.json 文件失败，请检查其内容或删除此文件」

### ISSUE THREAD

**Issue by zhuscat** [dcloudio/uni-app#3524]
**问题描述**

当保存文件触发差量编译时，我观察 `project.config.json` 的变化如下：

一开始文件内容如下：

```json5
{
  "description": "项目配置文件，详见文档：https://developers.weixin.qq.com/miniprogram/dev/devtools/projectconfig.html",
  // 其他一些信息，我发现 description 会变化，就看了一下 description 变化过程
  // ....
}
```

2.然后变成空白文件

3.过了一会儿，文件内容重新生成，此时 description 时这样的

```json5
{
  "description": "项目配置文件。",
  // 其他信息
}
```

4.文件内容发生变化，形成最终内容，与一开始一样
```json5
{
  "description": "项目配置文件，详见文档：https://developers.weixin.qq.com/miniprogram/dev/devtools/projectconfig.html",
  // ....
}
```

这个过程中，微信开发者工具会提示解析 project.config.json 文件失败，请检查其内容或删除此文件

尝试用官方的 demo 文件复现没法复现，不知道是不是因为我自己的项目比较大导致编译缓慢才会出现的问题

**系统信息:**
 - 发行平台: 微信小程序
 - uni-app版本 3.0.0-alpha-3041020220516002

**Comment by zhuscat** [comment]
也看到了说同样问题的 issue https://github.com/dcloudio/uni-app/issues/3458#issue-1211752732

**Comment by zhuscat** [comment]
https://user-images.githubusercontent.com/14963619/170173550-f71973c6-a0a0-4722-9b10-755adc71cedf.mov

请问这个是有问题么？我录了个屏

**Comment by zhuscat** [comment]
有一段时间 project.config.json 会被清除，导致开发者工具报错，然后重新编译也会报错，只能重启开发者工具解决

**Comment by zhuscat** [comment]
请问一下是 bug 么

**Comment by lbb00** [comment]
+1
