### ISSUE TITLE
uniapp v3 中无法导入支付宝小程序组件

### ISSUE THREAD

**Issue by xiaoxiangmoe** [dcloudio/uni-app#3525]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
https://github.com/xiaoxiangmoe/issue-can-not-use-miniapp-component

**复现步骤**
[复现问题的步骤]
1.  git clone https://github.com/xiaoxiangmoe/issue-can-not-use-miniapp-component.git
2. cd issue-can-not-use-miniapp-component
3. yarn dev:mp-alipay
4. 用小程序开发者工具打开 dist/dev/mp-alipay 目录
5. 预览，发现错误

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

在 uniapp 的 vue 2 版本，一切都工作得很好
<img width="262" alt="image" src="https://user-images.githubusercontent.com/8111351/169051649-4ea87409-2feb-4b62-a54f-4f24a5efbf78.png">

**实际结果**
但是在 vue 3 版本，崩溃了
<img width="320" alt="image" src="https://user-images.githubusercontent.com/8111351/169051536-9a93d167-56b3-4e6d-a992-1dc12edfa900.png">

**系统信息:**
 - 发行平台:  支付宝小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]

 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

也许是 vite 的插件没有考虑导入原生组件。

**Comment by xiaoxiangmoe** [comment]
@fxy060608 但是我在 vue 组件里怎么配置 usingComponents 呢？

**Comment by xiaoxiangmoe** [comment]
而且这种写法在 vue 2 里是可行的
<img width="909" alt="image" src="https://user-images.githubusercontent.com/8111351/169054013-fc8f09d1-1850-42df-b684-a45f48459746.png">
<img width="770" alt="image" src="https://user-images.githubusercontent.com/8111351/169054127-11ba9123-f86b-4095-b3c2-64a750a6be94.png">

**Comment by fxy060608** [comment]
> https://github.com/xiaoxiangmoe/issue-can-not-use-miniapp-component

配置为全局组件

**Comment by xiaoxiangmoe** [comment]
在 vue 2 里，配置成全局组件或者局部导入都可行，但是在 vue 3 里，我发现都不行……

**Comment by fxy060608** [comment]
> 在 vue 2 里，配置成全局组件或者局部导入都可行，但是在 vue 3 里，我发现都不行……

应该是vue3漏处理了支付宝上的全局组件（支付宝目前不支持配置全局组件，需要我们额外补充到每个页面，组件的json中）

**Comment by xiaoxiangmoe** [comment]
@fxy060608 貌似 sjs 也不支持。我再提交个 bug 报告吧

**Comment by xiaoxiangmoe** [comment]
还有一个就是, 局部导入我应该在哪里修复啊

**Comment by fxy060608** [comment]
> 

还要评估是否支持这样使用，本身vue2文档也没有提到支持这样使用

**Comment by fxy060608** [comment]
> 还有一个就是, 局部导入我应该在哪里修复啊

还要评估是否支持这样使用，本身vue2文档也没有提到支持这样使用

**Comment by xiaoxiangmoe** [comment]
@fxy060608 https://github.com/dcloudio/uni-app/pull/3528

**Comment by xiaoxiangmoe** [comment]
> 还要评估是否支持这样使用，本身vue2文档也没有提到支持这样使用

如果不能这样子用，那有一些 vue 2 小程序项目，就没法迁移到 vue 3 了。

**Comment by fxy060608** [comment]
> > 还要评估是否支持这样使用，本身vue2文档也没有提到支持这样使用
> 
> 如果不能这样子用，那有一些 vue 2 小程序项目，就不方便迁移到 vue 3 了。

官方明确支持的是通过配置全局组件来保证自定义组件里使用，通过vue方式引入只能算是vue2意外支持了，所以vue3实现的时候，是没有考虑过这个的，要不要支持这种使用方式，还是要评估一下的

**Comment by xiaoxiangmoe** [comment]
@fxy060608 easycom 是不是也没法配置非 .vue 组件？

**Comment by fxy060608** [comment]
> 更新最新版本后，全局组件可以用了。需要关闭这个 Issue，重新提一个「支持局部注册原生组件」的建议吗？

可以
