### ISSUE TITLE
uni-app 3 渲染函数被不断触发

### ISSUE THREAD

**Issue by zhuscat** [dcloudio/uni-app#3526]
**问题描述**
在微信开发者工具中出现的一个问题，尝试编写一个最小复现例子但是复现不出来，自己的实际项目可稳定复现
不是所有页面都是这个样子，某些页面才会有这个 BUG

**复现步骤**
1. 进入某个页面后，发现整个小程序会卡死，点击界面元素均不响应
2. 尝试进行 debug 后，发现页面对应的 `_sfc_render` 被疯狂的调用
3. 进一步 debug，发现 `setupRenderEffect` 中的 `componentUpdateFn` 一直被调用 https://github.com/dcloudio/uni-app/blob/d6020a2b0e98b146f89f9f604e695ef555665fa9/packages/uni-mp-vue/dist/vue.runtime.esm.js#L5009
4. 我 debug 了对应 effect 被重新触发的原因，发现一个 target 被反复 set https://github.com/dcloudio/uni-app/blob/d6020a2b0e98b146f89f9f604e695ef555665fa9/packages/uni-mp-vue/dist/vue.runtime.esm.js#L5035
我的代码有一部分大概是这样的：

```html
<template>
  <view>
    <view>HELLO</view>
    <bar :info="{
      id: item?.id,
      name: item?.name,
    }" />
    <view>{{ refreshId }}</view>
  </view>
</template>
```

重点是这个 `:info` 属性，作为 props 传递，并且没有任何地方去修改他

然后我 debug 这个 effect 的 onTrigger，发现内容如下，并且每一次内容是一样的（但应该是不同的对象) ：

https://github.com/dcloudio/uni-app/blob/next/packages/uni-mp-vue/dist/vue.runtime.esm.js#L345

```
target: { info: { id: xxx, name: xxx } }
type: set
key: info
newValue: { id: xxx, name: xxx }
```

我不知道为什么会有这样一个 target

5. 接着我就不知道该如何去排查了，我尝试再打了一些点，我添加的 log 如下：
<img width="867" alt="截屏2022-05-18 22 20 27" src="https://user-images.githubusercontent.com/14963619/169064242-29953118-65be-4f79-be3e-f3d0b34481c5.png">

<img width="777" alt="截屏2022-05-18 22 32 23" src="https://user-images.githubusercontent.com/14963619/169066979-f7ca0418-2aa3-4c5e-968a-20a96ba0e909.png">

然后我发现控制台输出的顺序是这样的，一直如此循环
```
set tick pending true
set mp data
// 触发我定义的 onTrigger 函数
enqueue
flush pre flush cbs
```

也就是说，在 set mp data 和 flush pre flush cbs 之间，只有一个 setData 调用，这个 setData 调用导致了重新渲染？

还有一个比较奇怪的事情是，set mp data callback 不会被打印出来（setData 的 callback 没有被调用)

我这个页面，不是一直会有这个 BUG，有时候进来是好的，有时候进来就会出现这个 BUG

然后我又观察到一个诡异的现象：

当没有出现这个 BUG 的时候，`console.log(mpInstance)` 结果如下：

```
ƒ (e,t){var r=Wi(this),n=r.__treeManager__;return"function"==typeof t&&n.operationFlow.registerSetDataCallback(t,this,r),r.setData(e)}
```

而这个时候，setData 的 callback 会被调用

当出现 BUG 的时候，`console.log(mpInstance)` 在控制台打印不出东西，callback 也不会被调用

然后还有一点是，用真机进行预览，是没有这个 BUG 的（暂时没有发现）

**系统信息:**
 - 发行平台: 微信小程序
 - uni-app版本 3.0.0-alpha-3041020220516002
 - 微信开发者工具版本：Stable 1.05.2204250
 - 基础库版本 2.24.2

**补充信息**

排查了很久，实在找不出原因，如果能提供思路，不胜感激

**Comment by fxy060608** [comment]
manifest.json配置debug:true 然后看下差量更新的日志

**Comment by zhuscat** [comment]
如果我把 info 属性去掉，就不会有问题，非常奇怪，不知道这个 target 是哪来的 `target: { info: { id: xxx, name: xxx } }`：
```
<template>
  <view>
    <view>HELLO</view>
    <bar :info="{
      id: item?.id,
      name: item?.name,
    }" />
    <view>{{ refreshId }}</view>
  </view>
</template>
```

**Comment by fxy060608** [comment]
> 就是这样的内容，不断地循环、疯狂输出，源码我也看了一下，对应的就是 props 对应的 key，第一次是 0，第二次是 1，然后不断地循环 <img alt="截屏2022-05-18 22 48 32" width="1080" src="https://user-images.githubusercontent.com/14963619/169071016-1e81167c-0d3d-4452-a572-4345a5f51f19.png">
> 
> <img alt="截屏2022-05-18 22 48 13" width="1070" src="https://user-images.githubusercontent.com/14963619/169071004-483cb424-e672-49c4-a601-18402931ab19.png">

看日志是有问题，但是想解决，还是要有能重现的工程

**Comment by zhuscat** [comment]
有没有可能的猜测呢？我尝试写一个重现的最小 demo，但是没弄出来，因为根本不知道是哪里导致的问题

**Comment by zhuscat** [comment]
目前发现的是，页面下有个子组件 watch 了 info：

```
watch(() => props.info, () => {
  // 回调函数里用到了 props.info
  console.log(props.info)
})
```

保留 watch 但是把毁掉函数变成一个空函数，就不会有这个问题了

尝试写一个 demo，同样的结构，但是不会有问题

**另外发现的一点是，这个 watch 的回调函数，会在 patch 中间被触发**

**Comment by zhuscat** [comment]
patch start -> setData -> watch props callback -> onTrigger -> ReactiveEffect job enqueue -> patch end

**Comment by zhuscat** [comment]
我发现把这行代码放到 `patch` 后面，就不会有问题了

https://github.com/dcloudio/uni-app/blob/d6020a2b0e98b146f89f9f604e695ef555665fa9/packages/uni-mp-vue/dist/vue.runtime.esm.js#L5026

**Comment by zhuscat** [comment]
目前发现执行顺序是这样的：
页面1 patch start -> 页面1 setData -> 触发了子组件 A 的 `initPropsObserver` 里定义的 `observe` -> 子组件 A `updateComponentProps` -> 触发了子组件 B 的 `initPropsObserver` 里定义的 `observe` -> 子组件 B `updateComponentProps` -> 触发子组件 B 对 `info`  的 watch callback -> trigger 页面1 的 render effect
如此不断循环
<img width="386" alt="截屏2022-05-19 11 02 51" src="https://user-images.githubusercontent.com/14963619/169195341-86f3eccd-7d68-43ad-9b01-7da1dfe9066f.png">

**Comment by zhuscat** [comment]
尝试写了，但是不能复现
目前就是发现：

1. 如果把模板中的对象字面量放到 script 的 computed 里面，就不会有 BUG

```
<Bar :info="{ id: item.id }" />
```

2. 如果把子组件对 info 的 watch callback 变成空函数，就没有 BUG

十分诡异
