### ISSUE TITLE
uniapp v3 中无法使用支付宝小程序 sjs

### ISSUE THREAD

**Issue by xiaoxiangmoe** [dcloudio/uni-app#3527]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
https://github.com/xiaoxiangmoe/issue-can-not-use-miniapp-component

**复现步骤**
[复现问题的步骤]
1.  git clone https://github.com/xiaoxiangmoe/issue-can-not-use-sjs-in-miniapp-component.git
2. cdissue-can-not-use-sjs-in-miniapp-component
3. yarn dev:mp-alipay
4. 发现错误

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

 

**实际结果**

```
[plugin:vite:vue] <script> cannot use the "src" attribute when <script setup> is also present because they must be processed together.
```

**系统信息:**
 - 发行平台:  支付宝小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]

 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

也许是 vite 的插件没有考虑 sjs

**Comment by xiaoxiangmoe** [comment]
@fxy060608

**Comment by fxy060608** [comment]
> @fxy060608

已修复，预计明天发个cli版本，想现在使用的话，可以参考我的提交，先手动修改下

**Comment by xiaoxiangmoe** [comment]
我测了一下，还没有完全修复。
源代码是
<img width="521" alt="image" src="https://user-images.githubusercontent.com/8111351/169088809-1558f7af-6bb4-4897-855b-3f0f670ab4d4.png">
编译产物是
<img width="545" alt="image" src="https://user-images.githubusercontent.com/8111351/169088856-fbec5fa5-3c4c-42c2-8535-2129aa28fac5.png">
效果：
<img width="350" alt="image" src="https://user-images.githubusercontent.com/8111351/169088942-5641713c-6912-4704-94e9-722e22b4651c.png">

---

如果我把编译产物的 `<text>{{_t(utils.message)}}</text>` 改成 `<text>{{(utils.message)}}</text>`。则运行良好，效果是

<img width="345" alt="image" src="https://user-images.githubusercontent.com/8111351/169089151-2f23c87f-00a5-49dd-9a92-25f935f37e19.png">

**Comment by fxy060608** [comment]
> 我测了一下，还没有完全修复。还是上面的 repo。 源代码是 <img alt="image" width="418" src="https://user-images.githubusercontent.com/8111351/169089908-26885a54-f16e-4374-9cad-7080b678e6f6.png">
> 
> <img alt="image" width="521" src="https://user-images.githubusercontent.com/8111351/169088809-1558f7af-6bb4-4897-855b-3f0f670ab4d4.png">
> 
> 编译产物是
> <img alt="image" width="545" src="https://user-images.githubusercontent.com/8111351/169088856-fbec5fa5-3c4c-42c2-8535-2129aa28fac5.png">
> 
> 效果：
> <img alt="image" width="350" src="https://user-images.githubusercontent.com/8111351/169088942-5641713c-6912-4704-94e9-722e22b4651c.png">
> 
> 如果我把编译产物的 `<text>{{_t(utils.message)}}</text>` 改成 `<text>{{(utils.message)}}</text>`。则运行良好，效果是
> 
> <img alt="image" width="345" src="https://user-images.githubusercontent.com/8111351/169089151-2f23c87f-00a5-49dd-9a92-25f935f37e19.png">

已修复，该问题在wxs上也存在

**Comment by xiaoxiangmoe** [comment]
是缓存的问题，我重新编译修复了
