### ISSUE TITLE
支付宝小程序开发环境会出现$slots.XXX of undefined 的问题

### ISSUE THREAD

**Issue by thckbuibuibui** [dcloudio/uni-app#3529]
**问题描述**
支付宝小程序开发环境会出现$slots.XXX of undefined 的问题

**复现步骤**
[复现问题的步骤]
`<view>
<view v-if="!$slots.label">{{ label }}</view>
<slot name="label"></slot>
</view>`

**预期结果**
不会出现错误信息

**实际结果**
[Vue warn]: Error in render: "TypeError: Cannot read property 'label' of undefined"

**系统信息:**
 - 支付宝小程序开发者工具
 - window10
uni-app v3.4.7
uni-app cli v2.0.1-34720220422002

Environment Info:

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i5-10400 CPU @ 2.90GHz
  Binaries:
    Node: 16.13.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.1.2 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.19041.1266.0
  npmPackages:
    @dcloudio/types: * => 2.5.17
    @dcloudio/uni-app-plus: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-automator: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-cli-i18n: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-cli-shared: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-h5: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-helper-json: * => 1.0.13
    @dcloudio/uni-i18n: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-migration: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-360: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-alipay: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-baidu: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-jd: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-kuaishou: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-lark: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-qq: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-toutiao: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-vue: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-weixin: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-xhs: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-quickapp-native: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-quickapp-webview: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-stat: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-template-compiler: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/vue-cli-plugin-uni: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/webpack-uni-mp-loader: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @hap-toolkit/dsl-vue:  0.6.13
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.1.1
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.15
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.15
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.15
    @vue/cli-plugin-eslint: ^4.5.15 => 4.5.15
    @vue/cli-plugin-router:  4.5.15
    @vue/cli-plugin-vuex:  4.5.15
    @vue/cli-service: ~4.5.0 => 4.5.15
    @vue/cli-shared-utils:  4.5.15
    @vue/component-compiler-utils:  3.3.0 (3.3.0)
    @vue/devtools-api:  6.0.0-beta.15
    @vue/eslint-config-standard: ^5.1.2 => 5.1.2
    @vue/preload-webpack-plugin:  1.1.2
    @vue/shared: ^3.2.33 => 3.2.33
    @vue/web-component-wrapper:  1.3.0
    eslint-plugin-vue: ^7.7.0 => 7.20.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.11 => 2.6.14
    vue-eslint-parser:  7.11.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.8 (16.8.3, 15.9.8)
    vue-router:  3.0.1
    vue-style-loader:  4.1.3 (4.1.3)
    vue-template-compiler: ^2.6.11 => 2.6.14 (2.6.14)
    vue-template-es2015-compiler:  1.9.1
    vue3:  1.0.0
    vuex: ^3.6.2 => 3.6.2 (3.6.2)
  npmGlobalPackages:
    @vue/cli: Not Found

**Comment by zhongzhifa** [comment]
有遇到过，支付宝小程序好像是不支持$slots的，可以使用props来声明要不要使用插槽

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/3215

**Comment by zhetengbiji** [comment]
已处理
可以关闭基础库2.0配置或者等待更新

**Comment by zhetengbiji** [comment]
已发布 3.6.0 alpha

**Comment by zxh1220** [comment]
> 已发布 3.6.0 alpha
已经升级了，但了支付宝小程序，还是报上面的错误，还需要关闭基础库2.0配置
