### ISSUE TITLE
使用uni-app 中map组件时，各个平台展示都不太一样，app打包生成出来的还一直缺少maps模块

### ISSUE THREAD

**Issue by dsq1109511798** [dcloudio/uni-app#353]
**问题描述**
使用uni-app 中map组件时，各个平台展示都不太一样，app打包生成出来的还一直缺少maps模块

**Comment by xiaoyucoding** [comment]
1、各个小程序平台都是引擎内置的地图，微信是腾讯地图，百度是百度地图等等。
2、App 端是高德地图
3、H5 平台用的是腾讯地图，这样可以尽可能降低与其它平台的差异。
4、打包时缺少模块，请注意勾选，参考：[map FAQ](https://uniapp.dcloud.io/component/map?id=faq)

**Comment by catalsdevelop** [comment]
@xiaoyucoding 我们现在的产品需要使用海外地图，高德地图在海外完全没有内容，这问题怎么解决？
