### ISSUE TITLE
npx @dcloudio/uvm alpha Invalid version: 3.0.0-alpha-3041020220516004

### ISSUE THREAD

**Issue by zhuscat** [dcloudio/uni-app#3533]
**问题描述**

执行 npx @dcloudio/uvm alpha 报错

**复现步骤**

1.  npx @dcloudio/uvm alpha

**实际结果**
```
npx: 64 安装成功，用时 19.345 秒
(node:52738) UnhandledPromiseRejectionWarning: Error: Invalid version: 3.0.0-alpha-3041020220516004
    at getVue3
```

**Comment by zhetengbiji** [comment]
重试几次

**Comment by Zane0816** [comment]
`Error: Invalid version: 3.6.3.20220917`
npm 版本 8.11.0 依然存在 
请尽快修复 谢谢

**Comment by zhetengbiji** [comment]
> `Error: Invalid version: 3.6.3.20220917` npm 版本 8.11.0 依然存在 请尽快修复 谢谢

vue3 还是 vue2 的项目？

**Comment by artwc** [comment]
$ npx @dcloudio/uvm@latest alpha

npx: installed 64 in 32.852s
C:\Users\...\AppData\Roaming\npm-cache\_npx\15304\node_modules\@dcloudio\uvm\lib\package.js:22
    throw new Error('Invalid version: ' + version)
Error: Invalid version: 3.0.0-alpha-3060820221027001
    at getVue3 (C:\Users\...\AppData\Roaming\npm-cache\_npx\15304\node_modules\@dcloudio\uvm\lib\package.js:22:11)
    ...
依然如此

**Comment by netsesame2** [comment]
今天执行同样报错。

const repos = {
  github: 'https://raw.githubusercontent.com/dcloudio/uni-preset-vue',
  gitee: 'https://gitee.com/dcloud/uni-preset-vue/raw'
}

这两个repo都没有3.0.0-alpha-3060820221027001这个package路径，可能官方还没有上传

**Comment by zhetengbiji** [comment]
> 今天执行同样报错。
> 
> const repos = { github: 'https://raw.githubusercontent.com/dcloudio/uni-preset-vue', gitee: 'https://gitee.com/dcloud/uni-preset-vue/raw' }
> 
> 这两个repo都没有3.0.0-alpha-3060820221027001这个package路径，可能官方还没有上传

已同步国内源，重试一下

**Comment by netsesame2** [comment]
已同步
