### ISSUE TITLE
快应用的 Native 版本，无法运行

### ISSUE THREAD

**Issue by xiaoxiangmoe** [dcloudio/uni-app#3538]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  vue create -p dcloudio/uni-preset-vue miniapp-playground-v4
2. 然后选择 ts 版本
3. yarn dev dev:quickapp-native
4. 用快应用开发者工具打开，发现白屏

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**

"@dcloudio/uni-quickapp-native": "^2.0.1-alpha-34920220508001"

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

也许是没有做最新版本的快应用开发者工具的适配

**Comment by dcloudhdx** [comment]
native渲染目前暂不支持快应用IDE调试，真机调试也是可以审查元素的，如何调试请参考文档 [https://ask.dcloud.net.cn/article/37145](https://ask.dcloud.net.cn/article/37145)
