### ISSUE TITLE
unicloud以后会支持import和export写法吗？

### ISSUE THREAD

**Issue by yongqiang0621** [dcloudio/uni-app#3543]
**新功能描述**
简洁描述你希望补充完善的增强功能

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by Wangyaqi** [comment]
`import uniCloud from 'uni-cloud'`这种写法吗？

**Comment by yongqiang0621** [comment]
主要是云对象的module.export可以改成export这种写法吗

**Comment by yongqiang0621** [comment]
现在是只支持commonjs规范，不支持import和export模块化写法，以后会支持吗

**Comment by Wangyaqi** [comment]
短期内不会支持
