### ISSUE TITLE
vuei18n 在内置浏览器运行H5出现 引用错误问题 ，但是在chrome浏览器中打开能正常运行

### ISSUE THREAD

**Issue by numver** [dcloudio/uni-app#3545]
**问题描述**
vue3 + vite + ts的新建项目中，在 HBuilder 里内置浏览器H5模式下发现引用错误的问题，但是在chrome浏览器打开却能正常运行

内置浏览器H5
![image](https://user-images.githubusercontent.com/9836372/169867844-25465d34-0ff6-4508-9421-603a9c94d915.png)

![image](https://user-images.githubusercontent.com/9836372/169867792-59b4f136-748f-42fa-af14-dee2a9b46ec7.png)

Chrome浏览器
![image](https://user-images.githubusercontent.com/9836372/169869821-0e35cedc-36d1-4411-b028-1674e4b94d7a.png)

当前NODE版本
![image](https://user-images.githubusercontent.com/9836372/169873209-0c4cffeb-e3e2-434b-8b4b-c4bcf1ef60ef.png)

package.json

{
  "name": "uni-preset-vue",
  "version": "0.0.0",
  "scripts": {
    "dev:app": "uni -p app",
    "dev:custom": "uni -p",
    "dev:h5": "uni",
    "dev:h5:ssr": "uni --ssr",
    "dev:mp-alipay": "uni -p mp-alipay",
    "dev:mp-baidu": "uni -p mp-baidu",
    "dev:mp-kuaishou": "uni -p mp-kuaishou",
    "dev:mp-lark": "uni -p mp-lark",
    "dev:mp-qq": "uni -p mp-qq",
    "dev:mp-toutiao": "uni -p mp-toutiao",
    "dev:mp-weixin": "uni -p mp-weixin",
    "dev:quickapp-webview": "uni -p quickapp-webview",
    "dev:quickapp-webview-huawei": "uni -p quickapp-webview-huawei",
    "dev:quickapp-webview-union": "uni -p quickapp-webview-union",
    "build:app": "uni build -p app",
    "build:custom": "uni build -p",
    "build:h5": "uni build",
    "build:h5:ssr": "uni build --ssr",
    "build:mp-alipay": "uni build -p mp-alipay",
    "build:mp-baidu": "uni build -p mp-baidu",
    "build:mp-kuaishou": "uni build -p mp-kuaishou",
    "build:mp-lark": "uni build -p mp-lark",
    "build:mp-qq": "uni build -p mp-qq",
    "build:mp-toutiao": "uni build -p mp-toutiao",
    "build:mp-weixin": "uni build -p mp-weixin",
    "build:quickapp-webview": "uni build -p quickapp-webview",
    "build:quickapp-webview-huawei": "uni build -p quickapp-webview-huawei",
    "build:quickapp-webview-union": "uni build -p quickapp-webview-union"
  },
  "dependencies": {
    "@dcloudio/uni-app": "3.0.0-alpha-3040820220424001",
    "@dcloudio/uni-app-plus": "3.0.0-alpha-3040820220424001",
    "@dcloudio/uni-components": "3.0.0-alpha-3040820220424001",
    "@dcloudio/uni-h5": "3.0.0-alpha-3040820220424001",
    "@dcloudio/uni-mp-alipay": "3.0.0-alpha-3040820220424001",
    "@dcloudio/uni-mp-baidu": "3.0.0-alpha-3040820220424001",
    "@dcloudio/uni-mp-kuaishou": "3.0.0-alpha-3040820220424001",
    "@dcloudio/uni-mp-lark": "3.0.0-alpha-3040820220424001",
    "@dcloudio/uni-mp-qq": "3.0.0-alpha-3040820220424001",
    "@dcloudio/uni-mp-toutiao": "3.0.0-alpha-3040820220424001",
    "@dcloudio/uni-mp-weixin": "3.0.0-alpha-3040820220424001",
    "@dcloudio/uni-quickapp-webview": "3.0.0-alpha-3040820220424001",
    "axios": "^0.27.2",
    "lodash-es": "^4.17.21",
    "pinia": "^2.0.14",
    "pinia-plugin-persist": "^1.0.0",
    "vue": "^3.2.33",
    "vue-i18n": "^9.1.10",
    "vue-types": "^4.1.1"
  },
  "devDependencies": {
    "@dcloudio/types": "^2.6.4",
    "@dcloudio/uni-automator": "3.0.0-alpha-3040820220424001",
    "@dcloudio/uni-cli-shared": "3.0.0-alpha-3040820220424001",
    "@dcloudio/vite-plugin-uni": "3.0.0-alpha-3040820220424001",
    "@types/lodash-es": "^4.17.6",
    "@types/node": "^17.0.35",
    "sass": "^1.52.1",
    "sass-loader": "^13.0.0",
    "typescript": "^4.6.3",
    "vite": "^2.9.6"
  }
}

**Comment by numver** [comment]
经排查发现是因为 这种TS语法糖在uni 上运行就会报错 
![image](https://user-images.githubusercontent.com/9836372/170088721-62886a16-778f-4c52-80cf-261d69f1d584.png)

**Comment by fxy060608** [comment]
内置浏览器版本不够高，不支持??操作符，dev模式运行时，默认不会做语法转义
https://caniuse.com/?search=Nullish%20coalescing%20operator

**Comment by numver** [comment]
> 内置浏览器版本不够高，不支持??操作符，dev模式运行时，默认不会做语法转义 https://caniuse.com/?search=Nullish%20coalescing%20operator

其实??应该是可以的,刚刚简单的console.log一下，是可以正常运行的，但是红框内  ?. 这种TS语法就会报错

**Comment by fxy060608** [comment]
> > 内置浏览器版本不够高，不支持??操作符，dev模式运行时，默认不会做语法转义 https://caniuse.com/?search=Nullish%20coalescing%20operator
> 
> 其实??应该是可以的,刚刚简单的console.log一下，是可以正常运行的，但是红框内 ?. 这种TS语法就会报错
> 
> ![image](https://user-images.githubusercontent.com/9836372/170090680-eed13731-8f7e-48e1-9a88-2aafae4076e2.png)

pc模式，查看 navigator.userAgent 即可看到内核版本，对应版本：https://caniuse.com/?search=Optional%20chaining%20operator

**Comment by numver** [comment]
> > > 内置浏览器版本不够高，不支持??操作符，dev模式运行时，默认不会做语法转义 https://caniuse.com/?search=Nullish%20coalescing%20operator
> > 
> > 
> > 其实??应该是可以的,刚刚简单的console.log一下，是可以正常运行的，但是红框内 ?. 这种TS语法就会报错
> > ![image](https://user-images.githubusercontent.com/9836372/170090680-eed13731-8f7e-48e1-9a88-2aafae4076e2.png)
> 
> pc模式，查看 navigator.userAgent 即可看到内核版本，对应版本：https://caniuse.com/?search=Optional%20chaining%20operator

在实际开发中是以chrome浏览器标准为主，还是已Hbuilder内置浏览器为主

**Comment by fxy060608** [comment]
> > > > 内置浏览器版本不够高，不支持??操作符，dev模式运行时，默认不会做语法转义 https://caniuse.com/?search=Nullish%20coalescing%20operator
> > > 
> > > 
> > > 其实??应该是可以的,刚刚简单的console.log一下，是可以正常运行的，但是红框内 ?. 这种TS语法就会报错
> > > ![image](https://user-images.githubusercontent.com/9836372/170090680-eed13731-8f7e-48e1-9a88-2aafae4076e2.png)
> > 
> > 
> > pc模式，查看 navigator.userAgent 即可看到内核版本，对应版本：https://caniuse.com/?search=Optional%20chaining%20operator
> 
> 在实际开发中是以chrome浏览器标准为主，还是以Hbuilder内置浏览器为主

uni-app 同 vue3 对浏览器的要求：https://caniuse.com/es6
发行时，会自动处理兼容性，开发时，可以使用高版本浏览器开发
