### ISSUE TITLE
import 动态引用文件的问题

### ISSUE THREAD

**Issue by numver** [dcloudio/uni-app#3549]
**问题描述**
由于项目中要用到国际化，语言种类繁多，在项目当中打算通过**import**动态引用相关的语言文件, 在**H5**中是能正常运行的，但是在**APP**当中（目前只测试了**Android**），就会出现如下问题:

**错误信息：** Invalid value "iife" for option "output.format" - UMD and IIFE output formats are not supported for code-splitting builds.

![image](https://user-images.githubusercontent.com/9836372/170167455-89c2370d-2634-4ea5-bc6c-82fec44fcd51.png)

**相关问题**
以下这种用法是直接导致报错的原因：
![image](https://user-images.githubusercontent.com/9836372/170167959-a76cbba6-3065-4701-ae65-3e6017219027.png)

**Comment by fxy060608** [comment]
非h5平台，暂不支持动态导入
