### ISSUE TITLE
小程序组件支持头条吗？

### ISSUE THREAD

**Issue by DailyLee** [dcloudio/uni-app#355]
我看官方文档小程序组件，没有提到头条的小程序组件，uniapp支持吗

**Comment by fxy060608** [comment]
根目录 ttcomponents
详情：https://uniapp.dcloud.io/frame?id=%E5%B0%8F%E7%A8%8B%E5%BA%8F%E7%BB%84%E4%BB%B6%E6%94%AF%E6%8C%81
