### ISSUE TITLE
我该如何在vue3 语法下使用  $forceUpdate强制刷新呢，不知道该从哪里导入这个钩子

### ISSUE THREAD

**Issue by baymax-arch** [dcloudio/uni-app#3556]
import { forceUpdate } from "vue";

报错信息

`'forceUpdate' is not exported by node_modules\@dcloudio\uni-mp-vue\dist\vue.runtime.esm.js`

**Comment by fxy060608** [comment]
https://github.com/vuejs/core/issues/3562
