### ISSUE TITLE
uni.setClipboardData 用不了

### ISSUE THREAD

**Issue by 1014156094** [dcloudio/uni-app#3557]
uni.setClipboardData 在 H5 是用不了的，但文档写了支持H5，到底是支不支持呢？
![image](https://user-images.githubusercontent.com/16074662/170475955-5e07d919-2f50-4727-803c-d760c96ff780.png)

**Comment by StrivingRabbit** [comment]
在 vue 几？

**Comment by 1014156094** [comment]
vue3

**Comment by StrivingRabbit** [comment]
在哪个浏览器上？有没有同意剪切板权限？

**Comment by 1014156094** [comment]
> 在哪个浏览器上？有没有同意剪切板权限？
> […](#)
> 在 2022年5月26日，21:31，Li Ri Peng ***@***.***> 写道： ﻿ vue3 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

手机微信浏览器，电脑谷歌浏览器都不行，剪切失败，我百度看很多都说，这功能是不支持H5的

**Comment by 0zcl** [comment]
vue2&&H5&& ios环境也会复制不了

**Comment by StrivingRabbit** [comment]
已支持
