### ISSUE TITLE
使用Typescript执行微信登录返回的是 code ，但是类型定义是 authResult

### ISSUE THREAD

**Issue by sprhawk** [dcloudio/uni-app#356]
**问题描述**
使用Typescript开发微信小程序。执行 

```
uni.login({
 provider:"weixin",
 success: function(res) {
  if(res) {
     console.log(res);
  }
 },
 fail: function() {
 }
 });
```

res 在 @dcloudio/types 里的定义是 errMsg 和 authResult, 但是实际返回的是 errMsg 和 code.

**复现步骤**
[复现问题的步骤]
```
uni.login({
 provider:"weixin",
 success: function(res) {
  if(res) {
     console.log(res);
  }
 },
 fail: function() {
 }
 });
```
**预期结果**
res.authResult 是 code 的值，或者 res 定义为 
```
interface LoginRes {
    /**
     * 描述信息
     */
    errMsg?: string;
    /**
     * 登录服务商提供的登录信息，服务商不同返回的结果不完全相同
     */
    code?: string;
}
```

**实际结果**
res.authResult is undefined

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - uni-app版本 @dcloudio/types: * => 0.1.5, @dcloudio/uni-mp-weixin: * => 0.0.942, uni-mp-vue:  2.6.10
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
@dcloudio/types 已更新
