### ISSUE TITLE
2.0版本 ts 模板下，onShow 生命周期函数不支持参数类型声明，ts报错

### ISSUE THREAD

**Issue by lxfljw** [dcloudio/uni-app#3565]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
<script lang="ts">
    import Vue from 'vue';
    export default Vue.extend({
        mpType: 'app',
        onLaunch() {
            console.log('App Launch')
        },
        onShow(options) {
            console.log('App Show')
        },
        onHide() {
            console.log('App Hide')
        }
    });
</script>

<style>
    /*每个页面公共css */
</style>

[或者可以直接贴源代码]
(parameter) options: any
(parameter) options: App.LaunchShowOption | undefined
已声明“options”，但从未读取其值。ts(6133)
Argument of type '{ mpType: string; onLaunch(): void; onShow(options: any): void; onHide(): void; }' is not assignable to parameter of type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Rec...'.
  Type '{ mpType: string; onLaunch(): void; onShow(options: any): void; onHide(): void; }' is not assignable to type 'ComponentOptions<Vue, DefaultData<Vue>, DefaultMethods<Vue>, DefaultComputed, PropsDefinition<Rec...'.
    Types of property 'onShow' are incompatible.
      Type '(options: any) => void' is not assignable to type '(((options?: LaunchShowOption | undefined) => void) & (() => void)) | undefined'.
        Type '(options: any) => void' is not assignable to type '((options?: LaunchShowOption | undefined) => void) & (() => void)'.
          Type '(options: any) => void' is not assignable to type '() => void'.
Parameter 'options' implicitly has an 'any' type.
**预期结果**
onshow 使用ts不报类型错误

**实际结果**

**系统信息:**
 System:
    OS: Windows 10
    CPU: (6) x64 Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz
  Binaries:
    Node: 14.18.0 - E:\nvmlink\node.EXE
    Yarn: 1.22.17 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.14.15 - E:\nodejs\npm.CMD
  Browsers:
    Edge: 44.22000.120.0
  npmPackages:
    @dcloudio/types: ^2.6.7 => 2.6.10
    @dcloudio/uni-app-plus: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-automator: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-cli-i18n: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-cli-shared: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-h5: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-helper-json: * => 1.0.13
    @dcloudio/uni-i18n: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-migration: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-360: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-alipay: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-baidu: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-jd: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-kuaishou: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-lark: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-qq: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-toutiao: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-vue: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-weixin: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-xhs: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-quickapp-native: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-quickapp-webview: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-stat: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-template-compiler: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/vue-cli-plugin-uni: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/webpack-uni-mp-loader: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @hap-toolkit/dsl-vue:  0.6.13
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.1.1
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.17
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.17
    @vue/cli-plugin-babel: ~4.5.17 => 4.5.17
    @vue/cli-plugin-router:  4.5.17
    @vue/cli-plugin-typescript: ~4.5.11 => 4.5.17
    @vue/cli-plugin-vuex:  4.5.17
    @vue/cli-service: ~4.5.17 => 4.5.17
    @vue/cli-shared-utils:  4.5.17
    @vue/component-compiler-utils:  3.3.0 (3.3.0)
    @vue/devtools-api:  6.0.0-beta.15
    @vue/preload-webpack-plugin:  1.1.2
    @vue/shared: ^3.0.0 => 3.2.36
    @vue/web-component-wrapper:  1.3.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.11 => 2.6.14
    vue-class-component: ^6.3.2 => 6.3.2 (7.2.6)
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.8 (16.8.3, 15.9.8)
    vue-property-decorator: ^8.0.0 => 8.5.1
    vue-router:  3.0.1
    vue-style-loader:  4.1.3 (4.1.3)
    vue-template-compiler: ^2.6.11 => 2.6.14 (2.6.14)
    vue-template-es2015-compiler:  1.9.1
    vue3:  1.0.0
    vuex: ^3.2.0 => 3.6.2 (3.6.2)
  npmGlobalPackages:
    @vue/cli: Not Found

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？] 
ts 有多个 onshow声明，只需声明一个可选参数即可

**Comment by zhenyuWang** [comment]
onShow options 参数为可选参数，你这边没有加 ？导致类型不匹配，改为 options?:any 即可。
