### ISSUE TITLE
uniapp v3 支付宝小程序中无法声明全局 vue 组件

### ISSUE THREAD

**Issue by xiaoxiangmoe** [dcloudio/uni-app#3566]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
https://github.com/xiaoxiangmoe/issue-can-not-use-uniapp-global-vue-component

**复现步骤**
[复现问题的步骤]
1.  git clone https://github.com/xiaoxiangmoe/issue-can-not-use-uniapp-global-vue-component.git
2. cd issue-can-not-use-uniapp-global-vue-component
3. yarn dev:mp-alipay
4. 用小程序开发者工具打开 dist/dev/mp-alipay 目录
5. 预览，发现错误

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

模拟器能运行

**实际结果**
但是在 vue 3 版本，崩溃了

<img width="332" alt="image" src="https://user-images.githubusercontent.com/8111351/171142814-e96d2698-bb11-40ac-a698-87f61de7dd18.png">

**系统信息:**
 - 发行平台:  支付宝小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]

 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
1. vue 的全局组件，要使用标准的vue注册，在main.js中app.component注册
2. 只有小程序平台的原生三方组件，才需要使用usingComponents注册

**Comment by ai4code** [comment]
今天发现第三方组件支付宝端 编译后属性无效
