### ISSUE TITLE
h5 联想手机页面有时候显示不全

### ISSUE THREAD

**Issue by zm4728** [dcloudio/uni-app#3567]
微信h5 页面
联想z6 手机

首次打开首页显示正常
进入详情页面后有一定概率出现 底部有一节空白
此时返回首页 首页也会出现底部空白
目前暂不清楚具体什么原因
![image](https://user-images.githubusercontent.com/11501291/171147862-9c64f7a8-ac60-4d87-911b-cf5bd3ad9380.png)
![image](https://user-images.githubusercontent.com/11501291/171147936-333c3442-704c-4fa5-b350-a1312ce2bbc0.png)

**Comment by zm4728** [comment]
> 特定浏览器吗？

目前只出现2个机型
好像是因为软键盘的问题
现在我这边在页面跳转之前加了一个关闭软键盘 然后加一个200毫秒的延迟后再跳转页面
暂时正常

**Comment by zhetengbiji** [comment]
> > 特定浏览器吗？
> 
> 目前只出现2个机型 好像是因为软键盘的问题 现在我这边在页面跳转之前加了一个关闭软键盘 然后加一个200毫秒的延迟后再跳转页面 暂时正常

嗯，估计是浏览器的bug，没什么好办法，暂时先从业务逻辑绕一下。
