### ISSUE TITLE
mac系统 uniapp vue3.0 + vite 版本 vuex编译报错

### ISSUE THREAD

**Issue by You00** [dcloudio/uni-app#3568]
**问题描述**
vue3/vite版本，启动编译报错，[vite] [plugin:vite:import-analysis] Package subpath './dist/vuex.esm-bundler.js' is not defined by "exports" in /uni-app-vue3.0/node_modules/vuex/package.json

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [macOS 12.0]
 - uni-app版本 [vue3/vite]
@zhetengbiji    @fxy060608 请大佬赐教

**Comment by fxy060608** [comment]
调整自己的node版本，比如使用16

**Comment by You00** [comment]
> 调整自己的node版本，比如使用16

感谢，已经解决，手动改了vuex包里面的package.json解决的，好像改变node版本的话，运行小程序也是有问题
