### ISSUE TITLE
uni.setClipboardData在企业微信内置浏览器中复制时会弹出键盘

### ISSUE THREAD

**Issue by TStoneLee** [dcloudio/uni-app#3569]
**问题描述**
uni.setClipboardData在企业微信内置浏览器中复制时会弹出键盘
**复现步骤**
在企业微信内置浏览器中调用uni.setClipboardData方法

**预期结果**
正常复制

**系统信息:**
 - 发行平台: H5平台、
 - 操作系统 如 iOS15、Android

**Comment by TStoneLee** [comment]
项目中的版本 "@dcloudio/uni-h5": "^2.0.0-alpha-31920210715002",

**Comment by zhetengbiji** [comment]
安卓还是iOS，除了弹出键盘，其复制功能是否正常？

**Comment by TStoneLee** [comment]
> 安卓&ios都会弹出键盘，复制功能正常
