### ISSUE TITLE
Android的能否也支持页面手势滑动返回

### ISSUE THREAD

**Issue by akFace** [dcloudio/uni-app#357]
**新功能描述**
Android的能否也支持页面手势滑动返回
类似微信的滑动返回，这样体验相当好

**现状及问题**
虽然安卓有三大金刚键，但是手势滑动返回能提升更大的用户体验。
希望能加入这个功能

**尝试方案**
可以集成第三方库来实现
[https://github.com/XBeats/and_swipeback](https://github.com/XBeats/and_swipeback)
[https://github.com/hanhailong/SwipeBackSample](https://github.com/hanhailong/SwipeBackSample)

**Comment by ArrayDC** [comment]
此功能与Android系统返回手势有冲突，不会支持此功能。
