### ISSUE TITLE
按照官网文档安装cli创建项目运行白屏，无任何内容显示，控制台报错

### ISSUE THREAD

**Issue by bluesky4485** [dcloudio/uni-app#3570]
**问题描述**
参考官网文档：https://uniapp.dcloud.io/quickstart-cli.html  安装了cli 并以hello uniapp模板创建了项目，根据提示 yarn serve之后编译有警告，打开网页直接白屏，控制台有个错误：

**复现步骤**
[复现问题的步骤]
1.  npm install -g @vue/cli@4
2. vue create -p dcloudio/uni-preset-vue my-project
3. 选择 hello uni-app 项目
4. yarn serve

[或者可以直接贴源代码]

**预期结果**
编译通过，且能正常访问

**实际结果**
空白页，且console中报错
```
chunk-vendors.js:12075 Uncaught TypeError: Cannot set properties of undefined (setting 'default')
    at _regeneratorRuntime (chunk-vendors.js:12075:19)
    at eval (index.js:78:16)
    at eval (index.js:78:16)
    at Object.Q2AE (index.js:1661:1)
    at __webpack_require__ (index.js:854:30)
    at fn (index.js:151:20)
    at eval (main.js:2:1)
    at Object.Vtdi (index.js:2076:1)
    at __webpack_require__ (index.js:854:30)
    at fn (index.js:151:20)
```
![image](https://user-images.githubusercontent.com/442591/171344939-440cb8f7-5e75-4564-a20e-71a8517739f0.png)

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 [window10]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 
  npm run info

> xydh@0.1.0 info
> node node_modules/@dcloudio/vue-cli-plugin-uni/commands/info.js

uni-app v3.4.7
uni-app cli v2.0.1-34720220422002

Environment Info:

  System:
    OS: Windows 10
    CPU: (16) x64 AMD Ryzen 7 4800H with Radeon Graphics
  Binaries:
    Node: 14.16.0 - D:\ProgramFiles\nodejs\node.EXE
    Yarn: 1.22.10 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.5.5 - D:\ProgramFiles\nodejs\npm.CMD
  Browsers:
    Edge: 44.19041.1266.0
  npmPackages:
    @dcloudio/types: ^2.6.7 => 2.6.11
    @dcloudio/uni-app-plus: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-automator: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-cli-i18n: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-cli-shared: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-h5: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-helper-json: * => 1.0.13
    @dcloudio/uni-i18n: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-migration: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-360: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-alipay: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-baidu: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-jd: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-kuaishou: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-lark: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-qq: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-toutiao: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-vue: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-weixin: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-mp-xhs: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-quickapp-native: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-quickapp-webview: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-stat: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/uni-template-compiler: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/vue-cli-plugin-uni: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/webpack-uni-mp-loader: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.1-34720220422002 => 2.0.1-34720220422002
    @hap-toolkit/dsl-vue:  0.6.13
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.1.1
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.17
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.17
    @vue/cli-plugin-babel: ~4.5.17 => 4.5.17
    @vue/cli-plugin-router:  4.5.17
    @vue/cli-plugin-vuex:  4.5.17
    @vue/cli-service: ~4.5.17 => 4.5.17
    @vue/cli-shared-utils:  4.5.17
    @vue/component-compiler-utils:  3.3.0 (3.3.0)
    @vue/devtools-api:  6.0.0-beta.15
    @vue/preload-webpack-plugin:  1.1.2
    @vue/shared: ^3.0.0 => 3.2.36
    @vue/web-component-wrapper:  1.3.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.11 => 2.6.14
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.8 (16.8.3, 15.9.8)
    vue-router:  3.0.1
    vue-style-loader:  4.1.3 (4.1.3)
    vue-template-compiler: ^2.6.11 => 2.6.14 (2.6.14)
    vue-template-es2015-compiler:  1.9.1
    vue3:  1.0.0
    vuex: ^3.2.0 => 3.6.2 (3.6.2)
  npmGlobalPackages:
    @vue/cli: Not Found
 - 设备信息 [如 iPhone8 Plus]

**补充信息**

**Comment by bluesky4485** [comment]
"dependencies": {
    "@dcloudio/uni-app-plus": "^2.0.1-34720220422002",
    "@dcloudio/uni-h5": "^2.0.1-34720220422002",
    "@dcloudio/uni-helper-json": "*",
    "@dcloudio/uni-i18n": "^2.0.1-34720220422002",
    "@dcloudio/uni-mp-360": "^2.0.1-34720220422002",
    "@dcloudio/uni-mp-alipay": "^2.0.1-34720220422002",
    "@dcloudio/uni-mp-baidu": "^2.0.1-34720220422002",
    "@dcloudio/uni-mp-jd": "^2.0.1-34720220422002",
    "@dcloudio/uni-mp-kuaishou": "^2.0.1-34720220422002",
    "@dcloudio/uni-mp-lark": "^2.0.1-34720220422002",
    "@dcloudio/uni-mp-qq": "^2.0.1-34720220422002",
    "@dcloudio/uni-mp-toutiao": "^2.0.1-34720220422002",
    "@dcloudio/uni-mp-vue": "^2.0.1-34720220422002",
    "@dcloudio/uni-mp-weixin": "^2.0.1-34720220422002",
    "@dcloudio/uni-mp-xhs": "^2.0.1-34720220422002",
    "@dcloudio/uni-quickapp-native": "^2.0.1-34720220422002",
    "@dcloudio/uni-quickapp-webview": "^2.0.1-34720220422002",
    "@dcloudio/uni-stat": "^2.0.1-34720220422002",
    "@vue/shared": "^3.0.0",
    "core-js": "^3.6.5",
    "flyio": "^0.6.2",
    "regenerator-runtime": "^0.12.1",
    "vue": "^2.6.11",
    "vuex": "^3.2.0"
  },
  "devDependencies": {
    "@babel/runtime": "~7.12.0",
    "@dcloudio/types": "^2.6.7",
    "@dcloudio/uni-automator": "^2.0.1-34720220422002",
    "@dcloudio/uni-cli-i18n": "^2.0.1-34720220422002",
    "@dcloudio/uni-cli-shared": "^2.0.1-34720220422002",
    "@dcloudio/uni-migration": "^2.0.1-34720220422002",
    "@dcloudio/uni-template-compiler": "^2.0.1-34720220422002",
    "@dcloudio/vue-cli-plugin-hbuilderx": "^2.0.1-34720220422002",
    "@dcloudio/vue-cli-plugin-uni": "^2.0.1-34720220422002",
    "@dcloudio/vue-cli-plugin-uni-optimize": "^2.0.1-34720220422002",
    "@dcloudio/webpack-uni-mp-loader": "^2.0.1-34720220422002",
    "@dcloudio/webpack-uni-pages-loader": "^2.0.1-34720220422002",
    "@vue/cli-plugin-babel": "~4.5.17",
    "@vue/cli-service": "~4.5.17",
    "babel-plugin-import": "^1.11.0",
    "cross-env": "^7.0.2",
    "jest": "^25.4.0",
    "mini-types": "*",
    "miniprogram-api-typings": "*",
    "postcss-comment": "^2.0.0",
    "sass": "^1.49.8",
    "sass-loader": "^8.0.2",
    "vue-template-compiler": "^2.6.11"
  },

**Comment by zhenyuWang** [comment]
使用 npm 安装依赖可解决该问题，yarn install 报错的原因是因为 npm 和 yarn 安装依赖时合并策略不同，导致依赖版本与预期不同导致。
如果仍要通过 yarn 管理依赖，可修改项目根目录 package.json 中 devDeps 依赖 @babel/runtime 的版本为 ~7.17.9，并增加
``` js
"resolutions":{
    "@babel/runtime": "~7.17.9"
}
```
锁定该依赖版本。

**Comment by bluesky4485** [comment]
没有yarn install过程，是vue create的时候自动安装的。

按照当前的uni-app cli v2.0.1-34720220422002版本，修改并锁定"@babel/runtime": "~7.17.9"这个版本的话，通过npm install安装后，是可以正常运行的。

>
