### ISSUE TITLE
vue3安卓端最低系统版本支持疑问

### ISSUE THREAD

**Issue by Wei1030** [dcloudio/uni-app#3575]
**问题描述**
刚接触uniapp，我使用最新HBuilderX3.4.7创建的uniapp项目，使用最简单的默认模板vue3.运行到安卓系统版本为5.1的模拟器上。应用启动后在HBuilderX的底部控制台报语法错误。应用启动页空白

**复现步骤**
1.  启动 HBuilderX3.4.7，创建新项目，选择uni-app，选择默认模板，vue版本选择3，创建
2. 点击  运行-运行到手机或模拟器-...-选择识别到的模拟器（模拟器是Android Emulator，系统版本5.1.1）
3. 应用启动后**空白**。观察HBuilderX的底部控制台，报错：
![image](https://user-images.githubusercontent.com/40414769/172041668-1830bc6f-0459-432a-ba35-4913f86a005f.png)

**系统信息:**
![image](https://user-images.githubusercontent.com/40414769/172042277-04f85ae1-36d7-413e-9213-71fec5bf2cbb.png)
![image](https://user-images.githubusercontent.com/40414769/172042347-9b42d547-cfca-461d-a2ea-3fc42713ffed.png)

**我的疑问**
官网说uniapp在安卓端自带v8，按我的理解应该不会有这种语法错误啊，虽然vue页面仍然渲染在webview中，但不是说视图和逻辑是分离的吗？官网也说了只有css兼容性问题：
![image](https://user-images.githubusercontent.com/40414769/172042103-90926e36-9b31-4cd6-94bd-cc37e123ee51.png)

**难道这种说话在使用vue3之后就过时了吗？另外官网也说了使用vue3的最低安卓版本要求：**
![image](https://user-images.githubusercontent.com/40414769/172043470-237c66c3-f6a3-42c3-a32b-399c434d7a00.png)

**这是不是和前面的说法互相矛盾？在前面不需要提一嘴吗？**
另外我不理解：
1、不考虑IOS，安卓端不是说自带js引擎吗，安卓端的最低要求是根据什么得出的？

2、实际我使用的5.1版本，已满足要求，还是有问题？难道需要自行升级系统WebView ？那这要求也不能一句不提吧？ 

3、
            ![image](https://user-images.githubusercontent.com/40414769/172043545-4f1db2de-97e6-4a61-bf20-f4e1806f0ab7.png)

不是说视图层和逻辑层是分离的吗？其实我不太明白视图层是什么意思，难道使用vue3之后，视图层也有js代码，而且需要较新语法？（这是不是就和之前其他官网页面的说明冲突？）

4、视图层和逻辑层如何界定的？我在vue文件的script里面写的代码是在视图层还是逻辑层？

以上关于报错的问题原因都是我的猜测，到底是不是更新webview就可以？还是说确实是个bug？我还没有验证。

最后，希望官方尽快更新官网上已经过时的说明，并整理下。说实话，像我这样刚接触的人看来，第一感觉是乱，东一篇说明，西一篇教程，有时还相互矛盾。

**Comment by zhetengbiji** [comment]
是的，vue2 的兼容性，到 vue3 后发生了变化，因为 vue3 依赖了一些新特性。

关于版本兼容，描述的不够具体，已经补充为：

> vue3 支持的范围是：Android > 4.4（具体因系统 webview 版本而异，原生安卓系统升级过系统 webview 一般 5.0 即可，国产安卓系统未使用 x5 内核时一般需 7.0 以上）, ios >= 10

另外关于逻辑层和视图层（也称渲染层）等一些关于应用架构详细介绍后续也会在文档补充，现在可以先参考一下小程序的介绍：https://developers.weixin.qq.com/miniprogram/dev/framework/quickstart/framework.html#%E6%B8%B2%E6%9F%93%E5%B1%82%E5%92%8C%E9%80%BB%E8%BE%91%E5%B1%82
