### ISSUE TITLE
 使用unplugin-vue-components MP平台组件没正确渲染

### ISSUE THREAD

**Issue by hzh1990** [dcloudio/uni-app#3577]
**问题描述**
 使用unplugin-vue-components MP平台组件没正确渲染

**复现步骤**
git clone https://github.com/hzh1990/uni-app-demo.git
cd uni-app-demo
npm install
npm run dev:mp-weixin

**预期结果**
正确渲染出组件与H5一致

**实际结果**
<img width="367" alt="image" src="https://user-images.githubusercontent.com/4394948/172111867-7bc73182-1ea5-4b51-906d-7c81f50ba3eb.png">

**系统信息:**
 - 发行平台: MP
 - 版本 3.0.0-alpha-3041320220531002

**Comment by fxy060608** [comment]
把uni插件放到unplugin-vue-components之后
