### ISSUE TITLE
没有类似vue router的路由守卫功能吗

### ISSUE THREAD

**Issue by a6965921** [dcloudio/uni-app#3579]
没有类似vue router的路由守卫功能吗
![image](https://user-images.githubusercontent.com/1198840/172521425-436c480e-1f20-4612-a77c-f3be899711e5.png)
next可以控制什么时候开始加载页面

**Comment by SilurianYang** [comment]
有的 使用[uni-simple-router](https://v3.hhyang.cn/) 一款专为 Uni App 量身定制的路由插件，提供无缝集成的特性，使得路由管理变得简单而高效。
