### ISSUE TITLE
scroll-view动态获取数据后scroll-into-view无法使用

### ISSUE THREAD

**Issue by zidaneting** [dcloudio/uni-app#358]
`<scroll-view class="scroll" scroll-x=true :scroll-into-view="date_scroll_view_id">
				<view v-for="v in date_list" :class="v['class']"><s :id="v['view_id']">{{v['month']}}/{{v['day']}}</s><em>{{v['text']}}</em><i></i></view>
</scroll-view>`

date_list是我用request方法远程获取数据填充的，填充后，date_scroll_view_id就不能使用了，ID都是一一对应的，不知道怎么回事呢。

**Comment by zhetengbiji** [comment]
此问题出现在哪端？

**Comment by vanbolee** [comment]
app端出现同样的问题，h5正常。scroll-into-view不能响应

**Comment by mirenfawei** [comment]
你怎么解决的我也出现了这个问题

**Comment by mirenfawei** [comment]
在这里面更改scroll-into-view的值就行了
this.$nextTick(function() {
	
});
