### ISSUE TITLE
Vue3+Pinia项目中 莫名其妙的bug  源代码已复制 拿来粘贴可复现 bug  求解决!!!

### ISSUE THREAD

**Issue by Liuyuren111** [dcloudio/uni-app#3580]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  HBuilder X工具 新建项目(默认模板+Vue3)
2.  使用 pinia
  main.js 文件中 新增代码

        import { createSSRApp } from 'vue'
        import * as Pinia from 'pinia';
        export function createApp() {
        const app = createSSRApp(App)
          app.use(Pinia.createPinia());
          return {
              app,
              Pinia,
           } 
         }

3. 在新项目中
   新建目录 api/business/business.js

       import { baseApi } from '@/static/js/conf/conf.js'
       import { request } from '@/static/js/util/request.js'
        export const getShopData = (data) => {
	    return request( `${baseApi}/api/v1/business/shop` , 'get', data)
        }

   新建目录 stores/business.js

        import { defineStore } from 'pinia';
        import { getShopData } from '@/api/business/business.js'
        export const useBusinessStore = defineStore('business', {
           state: () => {
               return {
                  shops: [],
               };
             },
           // 也可以这样定义
           // state: () => ({ count: 0 })
           actions: {
             async getShop(payload) {
             const res = await getShopData(payload)
                try {
                     const res = await getShopData(payload)
                      if (res.code === 200) {
                          this.shops = res.data
                           console.log(this.shops);
                       }
                  } catch (error) {
                        console.log(error);
                        return error
                  }
              },
         },});

   在static目录下新增目录 js/conf/conf.js

         export let baseApi = "https://diancan.glbuys.com";

   在static目录下新增目录 js/utils/request.js

        function request(url, method = "get", data) {
             return new Promise((resolve, reject) => {
                   uni.request({
                         url: url,
                        method: method.toLocaleUpperCase(), // 转换大写
                        data: data,
                        header: {
                             //'custom-header': 'hello' ,//自定义请求头信息
                            'content-type': 'application/x-www-form-urlencoded'
                        },
                         success: (res) => {
                             resolve(res.data)
                           },
                        fail: (res) => {
                           reject(res)
                          }
                       });
                     })
                    }

                 export {
                   request
                  }

4. 在 pages/index/index.vue 中使用
 
          <template>
              <view class="page">
                 <view v-for="(item,index) in shops" :key="index">
                     {{ item.branch_shop_name }}
                  </view>
                </view>
            </template>

            <script setup>
                 import { useBusinessStore } from '@/stores/business.js'
                 import {computed} from 'vue'
                 import { onShow } from '@dcloudio/uni-app'

                  const businessStore = useBusinessStore()

                   businessStore.getShop()

                    const shops = computed(() => {
                         return businessStore.shops
                    })
               </script>

               <style scoped>

               </style>

 5. 代码全部复制完后，刷新项目是可以得到数据的
     在重新启动项目会有一个报错信息   
      ![image](https://user-images.githubusercontent.com/88436209/172556654-4e3d1a05-15be-4e35-b925-3521daa2b86b.png)

     但是这个报错 只要随便一个地方改动下代码( 例如添加空格，在删除空格 )，在刷新 报错就会消失
     假如在重新启动项目还会有这个报错
      ![image](https://user-images.githubusercontent.com/88436209/172556670-e303bd2b-6133-409e-91d6-4fbfe810a108.png)

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
![image](https://user-images.githubusercontent.com/88436209/172555586-48303911-c6a1-4ddc-882f-08191eb027fb.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
不要在static中放置js代码
