### ISSUE TITLE
vue3小程序：v-bind="" is not supported

### ISSUE THREAD

**Issue by jdz321** [dcloudio/uni-app#3583]
**新功能描述**
希望支持Element上的`v-bind=""`

**现状及问题**
vue3小程序：v-bind="" is not supported  
由于小程序不支持JSX，在编写高阶组件时`v-bind=""`将很难有替代方案

**尝试方案**
尝试跪舔各位老板支持该特性

**补充信息**
@dcloudio/uni-mp-compiler能否开源放出来，咱们人多力量大

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/3330

**Comment by zhangrlhaha** [comment]
没有回复吗
