### ISSUE TITLE
无法使用使用arguments参数来获取订阅事件的参数

### ISSUE THREAD

**Issue by amihhs** [dcloudio/uni-app#3584]
**问题描述**
无法使用arguments来获取子组件传递的参数

**复现步骤**
[复现问题的步骤]
```vue
@click="previewImage(arguments, pictureList.original)"
```

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
![image](https://user-images.githubusercontent.com/59364234/172776239-1c9e02f4-777d-468a-8a08-94768d7b2a54.png)

**实际结果**
[这里请贴上你的报错截图或文字]
![1654754703968](https://user-images.githubusercontent.com/59364234/172776007-d30ccbd4-bacb-4bdd-84bd-0cae713b8211.png)

**系统信息:**
 - vue3
 - h5
 - cli `3.0.0-alpha-3041420220607001`

**补充信息**
和这个一样[#1796](https://github.com/dcloudio/uni-app/issues/1796)

**Comment by fxy060608** [comment]
标准的vue3不支持：
https://stackblitz.com/edit/vitejs-vite-5hcsfr?file=src%2FApp.vue
