### ISSUE TITLE
双重循环下slot(插槽)失效

### ISSUE THREAD

**Issue by 321603776** [dcloudio/uni-app#3587]
**问题描述**
微信小程序平台双重循环下slot(插槽)失效，h5平台下显示正常。

**复现步骤**

*TestComponent.vue*
```vue
<template>
	<view>
		<view v-for="(item, index) in 4" :key="index">
			<view v-for="(l_item, l_index) in 4" :key="`${index}_${l_index}`">
				<slot :text="`${item}_${l_item}`"></slot>
			</view>
		</view>
	</view>
</template>
```
*使用*
```vue
<template>
  <TestCompoent>
    <template v-slot="{ text }">
      <view>{{ text }}</view>
    </template>
  </TestCompoent>
</template>

<script setup>
	import TestCompoent from './components/TestComponent.vue'
</script>
```

**预期结果**
slot在微信小程序平台能正常显示

**实际结果**
slot在微信小程序平台未能正常渲染

**系统信息:**
- 发行平台: 微信小程序
- 操作系统 all
- HBuilderX版本 HBuilderX 3.4.13 -alpha(最新稳定版也有这个问题)
- uni-app版本 HBuilderX构建(vue3)
- 设备信息 all

复现项目
[dome.zip](https://github.com/dcloudio/uni-app/files/8875159/dome.zip)

**Comment by 321603776** [comment]
@fxy060608 你好，请问这个版本多久更新呀？

**Comment by fxy060608** [comment]
> @fxy060608 你好，请问这个版本多久更新呀？

HBuilderX的话，需要等下一个Alpha版本，预计要到下周

**Comment by VirensCn** [comment]
我测试发现默认插槽传参要完犊子，，`<slot :text="`${item}_${l_item}`"></slot>`，，你试试删除 `:text`,,你会发现OK了。。或者你转换出来得代码里面，在微信工具里面全局替换`name="d"` 为空，，你会发现OK了。。

**Comment by zui4yi1** [comment]
vue3 cli, bug还是存在。
刚下载了最新的 3.0.0-alpha-3041720220614001，还是不生效。

**Comment by zui4yi1** [comment]
> > @fxy060608 你好，请问这个版本多久更新呀？
> 
> HBuilderX的话，需要等下一个Alpha版本，预计要到下周

vue3 cli, bug还是存在。
刚下载了最新的 3.0.0-alpha-3041720220614001，还是不生效。

**Comment by fxy060608** [comment]
> vue3 cli, bug还是存在。 刚下载了最新的 3.0.0-alpha-3041720220614001，还是不生效。

测试没有问题，如果确认有问题，发测试工程

**Comment by zui4yi1** [comment]
> > vue3 cli, bug还是存在。 刚下载了最新的 3.0.0-alpha-3041720220614001，还是不生效。
> 
> 测试没有问题，如果确认有问题，发测试工程
[demos.zip](https://github.com/dcloudio/uni-app/files/8935511/demos.zip)
已发。麻烦看下是哪里的问题。vue3 cli版本，在vs vode下开发的。目前的现象是h5生效，小程序不生效。代码，只是一层v-for循环内的slot就不生效了。
![微信图片_20220619203906](https://user-images.githubusercontent.com/3435146/174481371-807ae6db-1ebc-4a8b-aff9-ab9411bccfd8.jpg)

**Comment by fxy060608** [comment]
> > > vue3 cli, bug还是存在。 刚下载了最新的 3.0.0-alpha-3041720220614001，还是不生效。
> > 
> > 
> > 测试没有问题，如果确认有问题，发测试工程
> > [demos.zip](https://github.com/dcloudio/uni-app/files/8935511/demos.zip)
> > 已发。麻烦看下是哪里的问题。vue3 cli版本，在vs vode下开发的。目前的现象是h5生效，小程序不生效。代码，只是一层v-for循环内的slot就不生效了。
> > ![微信图片_20220619203906](https://user-images.githubusercontent.com/3435146/174481371-807ae6db-1ebc-4a8b-aff9-ab9411bccfd8.jpg)

cli更新至：3.0.0-alpha-3050020220617002
