### ISSUE TITLE
input的伪类好像无法渲染,:focus设置样式无效

### ISSUE THREAD

**Issue by wanglang1995** [dcloudio/uni-app#359]
![image](https://user-images.githubusercontent.com/38482231/56861851-a80fbe80-69d7-11e9-8137-5cd4880c60b7.png)

**Comment by zhetengbiji** [comment]
[官方文档-框架简介-选择器](https://uniapp.dcloud.io/frame?id=%E9%80%89%E6%8B%A9%E5%99%A8)
