### ISSUE TITLE
不支持顶部await 

### ISSUE THREAD

**Issue by xcplovelhq** [dcloudio/uni-app#3591]
**问题描述**
不支持顶部await 

**复现步骤**
采用<script setup>

const { a, b, c } = await d()
![image](https://user-images.githubusercontent.com/20986739/173270982-efa99abd-4cb0-4b4d-b327-332c670278b3.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 : macos
 - uni-app版本 3.0.0-alpha-3041020220516002
 - 设备信息 :mac

**Comment by fxy060608** [comment]
这个是搭配Suspense使用的吧，目前小程序平台不支持Suspense
