### ISSUE TITLE
【vue3】uniapp 可以使用微信原生组件嘛？

### ISSUE THREAD

**Issue by sufuwang** [dcloudio/uni-app#3596]
**问题描述**
t-button 是一个使用 Component 写的组件，在 <template> 中使用如下
```
<t-button theme="primary">按钮</t-button>
```
被打包成了这样
```
<t-button wx:if="{{o}}" class="data-v-1badc801" u-s="{{['d']}}" u-i="1badc801-6" bind:__l="__l" u-p="{{o}}">按钮</t-button>
```

这是不对的，丢失了 props ，请问如何避免 uniapp 编译此组件

**Comment by fxy060608** [comment]
哪里不对，会保证可以正常访问到theme

**Comment by fxy060608** [comment]
在wxcomponents的原生小程序组件，会保留theme属性

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/3071

**Comment by sufuwang** [comment]
@fxy060608 大佬，有一个问题想请教

我有用到一个 npm 库，是一个微信原生组件库，uniapp 有什么插件可以用吗？

如果没有，我有一个思路，但是这样保留不住 props 属性
1. transform 分析 <template> 中的组件，并在 generateBundle 中修改对应的 usingComponents
2. buildEnd 生成 wxcomponents 目录
大佬，请问我这样做存在什么问题呀

**Comment by fxy060608** [comment]
> @fxy060608 大佬，有一个问题想请教
> 
> 我有用到一个 npm 库，是一个微信原生组件库，uniapp 有什么插件可以用吗？（可以引入原生组件的插件）
> 
> 如果没有，我有一个思路，但是这样保留不住 props 属性，请问我这样做存在什么问题呀
> 
> 1. transform 分析 `<template>` 中的组件，并在 generateBundle 中修改对应 json 文件的 usingComponents
> 2. buildEnd 生成 wxcomponents 目录

不提供npm的微信小程序库支持，可以自动或手动将该npm库，转换到wxcomponents中
