### ISSUE TITLE
h5如何保存图片到本地？

### ISSUE THREAD

**Issue by chinafelix** [dcloudio/uni-app#3598]
**问题描述**
开发h5，内嵌到微信小程序webview，生成海报如何保存到本地相册？

**复现步骤**
1、uni.saveImageToPhotosAlbum、uni.saveFile不支持h5
2、创建a标签，在webview不行
3、调用uni.downLoadFile接口成功，但是只返回一个templatePath，没有保存到相册

**预期结果**
保存到相册

**实际结果**
没有保存到相册

**Comment by zhongzhifa** [comment]
提供一个简单的想法，可以canvas转base64，然后通过webview的message、onPostMessage和小程序进行通信，将base64给小程序，然后在小程序将base64转换成templatePath，然后调用saveImageToPhotosAlbum，不就完了吗？

**Comment by chinafelix** [comment]
@zhongzhifa 微信小程序不支持webview和小程序实时通讯；目前的解决办法是提示用户长按保存图片

**Comment by zhongzhifa** [comment]
怎么可能不支持呢？看微信文档，https://developers.weixin.qq.com/miniprogram/dev/component/web-view.html，bindmessage
