### ISSUE TITLE
监听原生标题栏搜索输入框点击事件无效

### ISSUE THREAD

**Issue by eiixy** [dcloudio/uni-app#360]
**问题描述**
监听原生标题栏搜索输入框点击事件(onNavigationBarSearchInputClicked) 无法触发
onNavigationBarSearchInputChanged和onNavigationBarSearchInputConfirmed都能正常触发

![06AE` U$@6`@3 W(PXZLJCW](https://user-images.githubusercontent.com/22978107/56861905-1fdde900-69d8-11e9-92d4-647798aa46a6.png)
![YVTV MLEEN47)) H9GIEHVK](https://user-images.githubusercontent.com/22978107/56861913-29675100-69d8-11e9-8449-f1915b8b14ca.png)

**系统信息:**
 - 发行平台: H5平台
 - HBuilderX版本1.9.3

**Comment by zhetengbiji** [comment]
searchInput 需配置 disabled 属性为 true
