### ISSUE TITLE
给引入组件添加class样式问题

### ISSUE THREAD

**Issue by yxw007** [dcloudio/uni-app#3601]
**问题描述**
给引入的组件添加class样式，效果应该正确显示

**复现步骤**
[复现问题的步骤]
1. git clone https://github.com/yxw007/uniapp_issue.git
2. git checkout SubComponentStyle
3. cd SubComponentStyle
4. yarn 
5. yarn run dev:mp-weixin

复现[demo](https://github.com/yxw007/uniapp_issue/tree/SubComponentStyle)

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
![image](https://user-images.githubusercontent.com/9338717/173540872-ee41f6fa-a5ac-4a41-ac86-398cda510818.png)
[vue demo](https://sfc.vuejs.org/#eyJBcHAudnVlIjoiPHRlbXBsYXRlPlxuICA8Q29tcCBjbGFzcz1cIkNvbXBcIj48L0NvbXA+XG48L3RlbXBsYXRlPlxuXG48c2NyaXB0IHNldHVwPlxuaW1wb3J0IENvbXAgZnJvbSBcIi4vQ29tcC52dWVcIlxuPC9zY3JpcHQ+XG5cbjxzdHlsZSBzY29wZWQ+XG4uQ29tcHtcbiAgcGFkZGluZzo0MHB4O1xuICBib3JkZXI6NHB4IHNvbGlkICMwMDAwZmY7XG4gIGJveC1zaXppbmc6IGJvcmRlci1ib3g7XG59XG48L3N0eWxlPlxuXG4iLCJpbXBvcnQtbWFwLmpzb24iOiJ7XG4gIFwiaW1wb3J0c1wiOiB7XG4gICAgXCJ2dWVcIjogXCJodHRwczovL3NmYy52dWVqcy5vcmcvdnVlLnJ1bnRpbWUuZXNtLWJyb3dzZXIuanNcIlxuICB9XG59IiwiQ29tcC52dWUiOiI8dGVtcGxhdGU+XG4gIFx0PGRpdiBjbGFzcz1cIml0ZW1cIj5cbiAgICAgIHRoaXMgaXMgYSBpdGVtXG4gICAgICA8ZGl2IGNsYXNzPVwidGV4dFwiPlxuICAgIFx0ICB0aGlzIGlzIGEgQ29tcFxuICAgIFx0PC9kaXY+XG4gIFx0PC9kaXY+XG4gIFxuPC90ZW1wbGF0ZT5cblxuPHNjcmlwdCBzZXR1cD5cbjwvc2NyaXB0PlxuXG48c3R5bGUgc2NvcGVkPlxuICAuaXRlbSB7XG4gICAgcGFkZGluZzoyMHB4O1xuICBcdGJveC1zaXppbmc6IGJvcmRlci1ib3g7XG4gIH1cbiAgXG4gIC5pdGVtIC50ZXh0e1xuICAgIGNvbG9yOiByZWQ7XG4gICAgYm9yZGVyOiAxcHggc29saWQ7XG4gICAgdGV4dC1hbGlnbjogY2VudGVyO1xuICAgXG4gICAgYmFja2dyb3VuZDojMDBmZjAwO1xuICB9XG48L3N0eWxlPiJ9)

**实际结果**
![image](https://user-images.githubusercontent.com/9338717/173540762-eccac627-3dec-42e4-9d39-e5bec6d41b0e.png)

**系统信息:**
 - 发行平台: 微信小程序

**补充信息**

**Comment by fxy060608** [comment]
给组件自行补充display属性，如：
```css
.Comp {
  display: block;
  padding: 40px;
  border: 4px solid #0000ff;
  box-sizing: border-box;
}
```

**Comment by yxw007** [comment]
> thanks , 建议：编译时是否自动添加display属性，这样也更方便用户使用



> 给组件自行补充display属性，如：
> 
> ```css
> .Comp {
>   display: block;
>   padding: 40px;
>   border: 4px solid #0000ff;
>   box-sizing: border-box;
> }
> ```

thanks , 建议：编译时是否自动添加display属性，这样也更方便用户使用

**Comment by yxw007** [comment]
> > > 
> > 
> > 
> > thanks , 建议：编译时是否自动添加display属性，这样也更方便用户使用
> 
> 开发者不一定使用block，可能需要其他值域

嗯，只是使用view标签时，估计大部分用户都默认为块级元素了。
