### ISSUE TITLE
uni.redirect能否支持根据pages.json里的path来跳转而非相对路径。。

### ISSUE THREAD

**Issue by Silentdoer** [dcloudio/uni-app#3604]
**新功能描述**
简洁描述你希望补充完善的增强功能

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by fxy060608** [comment]
支持以/开头的绝对路径跳转，如/pages/index/index
