### ISSUE TITLE
MP平台 setup 找不到变量

### ISSUE THREAD

**Issue by UphkcRNqmafQWcSSSSSS** [dcloudio/uni-app#3606]
**问题描述**
MP平台 setup 找不到变量
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/4394948/173760442-1ee24344-95bb-435b-a727-96d9d90e0a67.png">

**复现步骤**
git clone https://github.com/hzh1990/uniapp-vue3-demo.git
cd uniapp-vue3-demo
npm install
npm run dev:mp-weixin

**预期结果**
能正确渲染

**系统信息:**
 - 发行平台: MP
 - 版本 3.0.0-alpha-3041720220614001

**Comment by fxy060608** [comment]
临时解决方案：let state = ...
