### ISSUE TITLE
上传文件 onProgressUpdate is not a function

### ISSUE THREAD

**Issue by teemosauce** [dcloudio/uni-app#3607]
**问题描述**
上传文件，使用uni.uploadFile返回结果，监听文件上传进度时，在微信小程序上会报uploadTask.onProgressUpdate is not a function
但是直接把uni替换成wx的时候 就没事。
**复现步骤**
[复现问题的步骤]
let option = getUploadOption(files[i].tempFilePath)
let uploadTask = uni.uploadFile(option)
console.log(uploadTask)
uploadTask.onProgressUpdate(res => {
console.log('上传进度' + res.progress);
console.log('已经上传的数据长度' + res.totalBytesSent);
console.log('预期需要上传的数据总长度' + res.totalBytesExpectedToSend);
})

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
<img width="958" alt="image" src="https://user-images.githubusercontent.com/1171851/173767455-bb072c92-91ae-460c-bd6d-e029365efd1c.png">

**系统信息:**
 - 发行平台: [如 微信小程序]
 - 操作系统 [MAC OS]
 - 设备信息 微信开发工具

**补充信息**
[可选]
uniapp编译的时候出了什么问题

**Comment by fxy060608** [comment]
如果希望返回一个 uploadTask 对象，需要至少传入 success / fail / complete 参数中的一个。例如：
```js
var uploadTask = uni.uploadFile({
	url: 'https://www.example.com/upload', //仅为示例，并非真实接口地址。
	complete: ()=> {}
});
uploadTask.abort();
```
如果没有传入 success / fail / complete 参数，则会返回封装后的 Promise 对象：[Promise 封装](https://uniapp.dcloud.net.cn/api/#promise-%E5%B0%81%E8%A3%85)
