### ISSUE TITLE
uniapp npm run build:H5 打包中断，且没报任何错！

### ISSUE THREAD

**Issue by codeHung** [dcloudio/uni-app#3608]
**问题描述**

用的版本（2.0.0-29820201110001），Vue Cli 创建的项目无法打包和运行，控制台无报错信息，控制台信息如下：

![image](https://user-images.githubusercontent.com/64880180/173768596-c399a1e2-5be3-4f49-b316-9463a3097a50.png)

![image](https://user-images.githubusercontent.com/64880180/173769210-0adea634-7af8-4613-83bf-3c3b8b285d99.png)

按照网上的方法 yarn add -D @dcloudio/uni-cli-i18n @dcloudio/uni-i18n，后又开始报saas-loader的错误，这是在套娃吗

**预期结果**
有一些老项目无法切换 版本，麻烦开发团队尽快发修复版解决这个问题

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - build H5
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - Win10
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
  直接用的npm run build:H5 打包

**Comment by fxy060608** [comment]
移除package.json中的saas-loader，重新 install 试试

**Comment by codeHung** [comment]
@fxy060608  试过了，又会报新的问题
