### ISSUE TITLE
iOS上vue的methods、function在模板中无法正常显示文字

### ISSUE THREAD

**Issue by haogefeifei** [dcloudio/uni-app#361]
**问题描述**
栗子1： methods的某个方法返回处理后的文字，template中写{{func()}}是显示不出来的。
栗子2：某个数字data在template中使用vue自带的格式化方法{{data. toFixed(2)}} 也是显示不了

以上问题仅出现在iOS基座调试中。 浏览器调试和Android基座调试都是正常的，表现不一致应该算bug。

栗子1还可以写到computed里顶一下，栗子2这种不能直接写就有点烦了。

**Comment by haogefeifei** [comment]
补充：好像只有在component里才会这样。。

**Comment by ch-zgh-1993** [comment]
@haogefeifei 测试这两种写法在 ios 中组件里使用都是正常的，升级 HBuilderX 到最新版本看是否正常。

**Comment by Wangyaqi** [comment]
长时间未回复，暂时关闭
