### ISSUE TITLE
vue3+vite2 百度小程序跨级传参第三级无法响应

### ISSUE THREAD

**Issue by amihhs** [dcloudio/uni-app#3612]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
跨级传参无法响应变化,真机模拟器都会
![image](https://user-images.githubusercontent.com/59364234/174218788-1953c91a-def5-4f6e-85e8-2a308b4335ee.png)

[或者可以直接贴源代码]
[示例](https://github.com/amihhs/uniapp-baidu-issue)
**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [百度小程序]
 - cli 3.0.0-alpha-3041720220614002

**补充信息**
类似[#issue3340](https://github.com/dcloudio/uni-app/issues/3340)

**Comment by zhetengbiji** [comment]
HBuilderX 3.5.0 alpha 已修复

**Comment by amihhs** [comment]
这个问题在百度小程序真机上还存在问题
![e7f5bbc2f2c1b57a210167d7b5998f3](https://user-images.githubusercontent.com/59364234/176830724-464b7e6a-15c2-4456-b33e-ed88390b0f91.jpg)

正常：
![image](https://user-images.githubusercontent.com/59364234/176830770-5eed0d6b-3096-4863-afca-9d1eb8be5c11.png)

[demo](https://github.com/amihhs/uni-app-issue-3612-2)

**Comment by amihhs** [comment]
@fxy060608

**Comment by amihhs** [comment]
在苹果真机上存在问题，我用的测试机是6s，cli 3.0.0-alpha-3041820220630001
