### ISSUE TITLE
企业微信JSSDK(jweixin)中的chooseImage被覆写，导致返回结果不正确

### ISSUE THREAD

**Issue by litangyu** [dcloudio/uni-app#3613]
**问题描述**
企业微信JS-SDK中的wx.chooseImage被覆写，调用后无法获取localIds(文档中描述的图片返回结果)

**复现步骤**
测试Demo：https://github.com/litangyu/uni-app_issues-3613

1.  启动项目
2. 浏览器打开项目，打开调试模式
3. 在console中打印wx.chooseImage
4. 查看输出

**预期结果**
因JS-SDK未引入，控制台应打印
```
VM132:1 Uncaught ReferenceError: wx is not defined
    at <anonymous>:1:1
```

**实际结果**
输出如下内容
```
(args = {}, ...rest) => {
    if (hasCallback(args)) {
      return wrapperReturnValue(name, invokeApi(name, fn, args, rest));
    }
    return wrapperReturnValue(name, handlePromise(new Promise((res…
```

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 Android 10、macOS Monterey 12.3.1
 - 浏览器：企业微信内置浏览器、Chrome 102.0.5005.115
 - uni-app版本 3.0.0-alpha-3041720220614002
 - 设备信息 荣耀AN00a、MacBook Pro

**补充信息**
经测试，如果引入JS-SDK后调用wx.invoke('chooseImage', obj)，是可以正常返回图片的localIds数据的，所以怀疑uni-app覆写了wx.chooseImage

企业微信JS-SDK 图片接口
https://developer.work.weixin.qq.com/document/path/90495

**Comment by zhetengbiji** [comment]
https://ask.dcloud.net.cn/article/35380

**Comment by litangyu** [comment]
@zhetengbiji 感谢
