### ISSUE TITLE
VS Code用Cli创建项目失败

### ISSUE THREAD

**Issue by hualiao** [dcloudio/uni-app#3614]
**问题描述**
参考文档https://ask.dcloud.net.cn/article/36286用VS Code创建hello-uniapp示例项目，遇到第一个问题是输入vue create -p dcloudio/uni-preset-vue指令后报错
![2022-06-17_140125](https://user-images.githubusercontent.com/5306308/174236053-ace94587-9b60-4089-932a-c87c400278d0.png)
通过把指令改成vue create -p D:\Code\Test\uni-preset-vue-master my-project解决，然后遇到第二个问题

选择Hello uni-app模板提示找不到模板
![2022-06-17_135946](https://user-images.githubusercontent.com/5306308/174236318-d0f83e31-3135-42b0-9873-cec057de6fce.png)

选自定义模板然后地址填成dcloudio/hello-uniapp也不行
![2022-06-17_141400](https://user-images.githubusercontent.com/5306308/174236732-7523dcfd-df46-4ddd-8d2f-3041219963b0.png)

**预期结果**
想确认hello-uniapp（ https://github.com/dcloudio/hello-uniapp）这个示例项目能否用VS Code运行成h5的，手动调整也可以。

**Comment by zhetengbiji** [comment]
从报错看，是从 github 下载超时了，可以更换一下网络后重试。

**Comment by zhetengbiji** [comment]
> 从报错看，是从 github 下载超时了，可以更换一下网络后重试。

手动的话，可以先创建一个默认模板，然后将 hello uni-app 覆盖到 src 目录。
