### ISSUE TITLE
vue3 使用defineEmits自定义事件在百度小程序会出现not found

### ISSUE THREAD

**Issue by amihhs** [dcloudio/uni-app#3616]
**问题描述**
vue3 使用defineEmits自定义事件在百度小程序会出现not found

**复现步骤**
```vue
/* index page*/
<template>
  <view class="content">
    <image class="logo" src="/static/logo.png" />
    <parent @view-item="viewItem" />
  </view>
</template>

<script setup lang="ts">
function viewItem(id: number) {
  console.log("viewItem", id);
}
</script>
```
```vue
/* component */
<script setup lang='ts'>
const emits = defineEmits({
  viewItem: (id: number) => typeof id === "number",
});
function clickHandle(id: number = 1) {
  emits("viewItem", id);
}
</script>

<template>
  <view @click="clickHandle()">
    <view>parent component click</view>
  </view>
</template>

```

**预期结果**
![image](https://user-images.githubusercontent.com/59364234/174514519-377bf931-3fac-49fc-9a4c-a59e04959d40.png)

**实际结果**
![image](https://user-images.githubusercontent.com/59364234/174514541-582091a4-f238-4324-88f8-fe11a2861e84.png)

**系统信息:**
 - 发行平台: [mp-baidu]
 - cli 3.0.0-alpha-3050020220617001

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
临时解决方案：@view-item 改为 @viewItem

**Comment by fxy060608** [comment]
cli更新至：3.0.0-alpha-3050020220617002

**Comment by amihhs** [comment]
百度小程序 v-model拆开写的时候，出现 updateModelValue not found
```vue
<uni-easyinput  :model-value="content"  @update:modelValue="changeHandle"  />
```

**Comment by fxy060608** [comment]
cli 更新至：3.0.0-alpha-3050020220623002
