### ISSUE TITLE
vue-cli 5.0运行报错

### ISSUE THREAD

**Issue by wujinhong** [dcloudio/uni-app#3617]
Error: Cannot find module 'webpack/lib/RuleSet'
必须回退到4.0才能正常运行

**Comment by mxh861001** [comment]
@wujinhong  我回退到4了还是提示这个错误，目前cli的版本号为：@vue/cli 4.5.18

**Comment by zhongzhifa** [comment]
我记得以前有遇到过，按照`"webpack": "^4.5.0"`就好了，你可用试试
