### ISSUE TITLE
v-if=“函数”

### ISSUE THREAD

**Issue by pinkpinkpig** [dcloudio/uni-app#362]
**新功能描述**
希望v-if 可以绑定函数，并可以传递传输进去，然后根据返回的值，进行显示

**现状及问题**
现在是不可以，就算绑定一些复杂的计算操作也不行。
1、当有时需要进行一些复杂的计算才会判断此节点是否显示
2、当for循环时要根据传递的值动态的判断是否显示此节点

**尝试方案**
在第一种情况下可以用一个变量来保存是否显示此节点的判断
在第二种情况下，可以设置一个类型为对象的data, 把需要传递的值（用来判断显示），作为key,然后在for循环前，提前运算，把是否显示的值保存在对应的key下，然后v-if="!!renderData[key]"来判断

**补充信息**
[其它你认为有参考价值的信息]

**Comment by fxy060608** [comment]
目前自定义组件模式下已支持，但建议还是提前处理好，这样可以保证性能最佳
