### ISSUE TITLE
小程序：组件无法使用data-定义props

### ISSUE THREAD

**Issue by amihhs** [dcloudio/uni-app#3620]
**问题描述**
当组件的props 的参数名与页面的变量名一致时，会导致props参数无法正常传递
如下
```vue
<script setup lang='ts'>
import { onLoad } from "@dcloudio/uni-app";
import { reactive, ref } from "vue";
const dataId = ref(-1);
onLoad((options) => {
  if (options.data_id) dataId.value = Number(options.data_id);
});
</script>
<template>
  <view> about page: {{ dataId }} </view>
  <parent :data-id="dataId" :content-id="dataId" />
</template>
```

```vue
<script setup lang='ts'>
const props = withDefaults(
  defineProps<{
    dataId: number;
    contentId: number;
  }>(),
  {
    dataId: -1,
    contentId: -1,
  }
);
</script>

<template>
  <view>
    <view>parent component相同变量名字dataId:{{ props.dataId }}</view>
    <view>parent component不同变量名字contentId:{{ props.contentId }}</view>
  </view>
</template>
```

**复现步骤**
[demo](https://github.com/amihhs/uni-issue-1/tree/master/src)

[或者可以直接贴源代码]

**结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
当props 的参数名为contentId时正常，而dataId却无法正常传递
![image](https://user-images.githubusercontent.com/59364234/174544008-a1674819-808e-45b0-aadd-59d027184604.png)

**系统信息:**
 - 发行平台: [mp-toutiao, mp-baidu]
 - cli 3.0.0-alpha-3050020220617001

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
页面的参数会作为props传入使用

**Comment by amihhs** [comment]
> 页面的参数会作为props传入使用
不是很明白，你说的是url带的参数吗
我测的情况是：在页面定义了个变量dataId的时候，如果组件的props也刚好有个参数叫dataId，这种情况就无法正常传入dataId的数据到组件中

**Comment by fxy060608** [comment]
> > 页面的参数会作为props传入使用
> 
> 不是很明白，你说的是url带的参数吗 我测的情况是：在页面定义了个变量dataId的时候，如果组件的props也刚好有个参数叫dataId，这种情况就无法正常传入dataId的数据到组件中

url带的参数，被自动转换成了页面的props使用，vue组件，props和data是不能重复定义的

**Comment by amihhs** [comment]
> > > 页面的参数会作为props传入使用
> > 
> > 
> > 不是很明白，你说的是url带的参数吗 我测的情况是：在页面定义了个变量dataId的时候，如果组件的props也刚好有个参数叫dataId，这种情况就无法正常传入dataId的数据到组件中
> 
> url带的参数，被自动转换成了页面的props使用，vue组件，props和data是不能重复定义的

好像和url参数没关系, 应该是data-id这种写法的问题，而且我的url参数是下划线的：data_id
但是名字不一样的时候，比如content-id这样就没问题
![image](https://user-images.githubusercontent.com/59364234/174548560-cbbf8a3d-329e-4fa8-a15c-8919b0fd2baa.png)

![image](https://user-images.githubusercontent.com/59364234/174548532-8b2185aa-ba0f-4b0c-9110-a1aedb024569.png)

**Comment by fxy060608** [comment]
data-默认是dataset，不要使用该前缀定义props
