### ISSUE TITLE
import as 不能正常使用

### ISSUE THREAD

**Issue by yoyo837** [dcloudio/uni-app#3622]
使用 `npx degit dcloudio/uni-preset-vue#vite my-vue3-project`初始化的模版，修改`main.js`

```js
import { createApp as createVueApp } from 'vue';
import App from './App.vue';

export function createApp() {
  const app = createVueApp(App);
  return {
    app,
  };
}
```

提示：`Uncaught SyntaxError: Identifier 'createApp' has already been declared.`

**Comment by kmq116** [comment]
你但凡翻译一下这个报错 + js 基础能扎实点，明白作用域和函数声明也不至于问出这种低级问题

**Comment by yoyo837** [comment]
![image](https://user-images.githubusercontent.com/6134547/174573000-2f9e4085-a248-4d83-8567-7143f8f344c7.png)

这个图才是你理解的吧？

**Comment by fxy060608** [comment]
不要随意修改main.js中的代码和函数命名，编译器会注入一些运行时代吗

**Comment by kmq116** [comment]
> ![image](https://user-images.githubusercontent.com/6134547/174571869-5feeebdf-796d-4d67-9d25-278eddaaaed5.png)
> 
> 那你扎实你说说为什么node可以？

uni 的锅，我的

**Comment by zhetengbiji** [comment]
> > 不要随意修改main.js中的代码和函数命名，编译器会注入一些运行时代码的
> 
> 我理解你的意思。但作为第一天接触uni的新人来说, 希望看到更多非dcloudio的成员了解实现原理，参与共建，生态能够不完全只依赖dcloudio, 不然会担心项目在半开源的边界上游走。您这个回复给个人的感觉就是“你别管那么多，按说明使用就可以了”。

如果把前半句删除，给人的感觉会不会好一些

**Comment by yoyo837** [comment]
> uni 的锅，我的

那请问这个有必要修复吗？还是说由于提及的那些“注入”，这个文件基本不允许动？

我个人实际刚开始学习这个，假如`main.js`不允许动，其实是不是可以直接埋到`@dcloudio/uni-app`包里去，入口变成`App.vue`呢？

**Comment by fxy060608** [comment]
@zhetengbiji vue3 升级文档，增加注意事项： main.js 不能修改导出的 createApp 方法名，不能修改从 Vue 中导入的 createSSRApp

**Comment by fxy060608** [comment]
> ```js
> createSSRApp
> ```

createSSRApp 不支持别名
如果想优化（需要同时支持客户端渲染，服务端渲染），可以参考文件：
https://github.com/dcloudio/uni-app/blob/next/packages/uni-h5-vite/src/plugins/mainJs.ts#L41
