### ISSUE TITLE
uni-app 3 父组件 mounted 在子组件 mounted 之前执行

### ISSUE THREAD

**Issue by zhuscat** [dcloudio/uni-app#3624]
**问题描述**
uni app 微信小程序中，能保证子组件的 mounted 在父组件之前执行么，在我的一段代码中发现父组件的 mounted 先执行了

**预期结果**
子组件 mounted 先于父组件执行

**实际结果**
父组件 mounted 先于子组件执行

**系统信息:**
 - 发行平台: 微信小程序
 - uni-app版本：3.0.0-alpha-3041720220614002

**Comment by fxy060608** [comment]
发测试工程
