### ISSUE TITLE
小程序v-for使用index作为key导致无法触发更新

### ISSUE THREAD

**Issue by amihhs** [dcloudio/uni-app#3625]
**问题描述**
小程序v-for使用index作为key导致无法触发更新

**复现步骤**
以uni-datetime-picker为例
[demo](https://github.com/amihhs/uni-issue-1)

**预期结果**
h5正常切换
![image](https://user-images.githubusercontent.com/59364234/174699302-c9c83e3a-6f77-4d8f-be1f-e96f6cce042c.png)

**实际结果**

![image](https://user-images.githubusercontent.com/59364234/174698636-60e41daf-67fb-4483-9f50-894e3933f667.png)

切换月份后，只更新了左上角第一个
![image](https://user-images.githubusercontent.com/59364234/174698651-15541b9e-cdc6-46b4-ac71-33f516227379.png)

**系统信息:**
 - 发行平台: [字节小程序，百度小程序]
 - cli 3.0.0-alpha-3050020220617002

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
cli更新至：3.0.0-alpha-3050020220617003
