### ISSUE TITLE
requestSubscribeMessage API 编译到字节小程序无法正常调出，微信小程序正常

### ISSUE THREAD

**Issue by xu455255849** [dcloudio/uni-app#3626]
**问题描述**
requestSubscribeMessage API 编译到字节小程序无法正常调出，微信小程序正常

**复现步骤**
点击预约按钮，
控制台报错 errMsg: "requestSubscribeMessage:fail must be invoked by user tap gesture", errNo: 21501

**预期结果**
正常弹出订阅弹窗

**实际结果**
errMsg: "requestSubscribeMessage:fail must be invoked by user tap gesture", errNo: 21501

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
此问题在新版 alpha hx 3.4.5，cli 升级至 `3.0.0-alpha-3040520220408001` 以上，已得到修复。使用如下方式即可：

1. 在有点击事件的节点上添加 `data-eventsync="true"` ，**注意：全小写**，例如：
```html
<button type="primary" data-eventsync="true" @click="getUserProfile">获取用户信息</button>
```

**Comment by xu455255849** [comment]
> 此问题在新版 alpha hx 3.4.5，cli 升级至 `3.0.0-alpha-3040520220408001` 以上，已得到修复。使用如下方式即可：
> 
> 1. 在有点击事件的节点上添加 `data-eventsync="true"` ，**注意：全小写**，例如：
> 
> ```
> <button type="primary" data-eventsync="true" @click="getUserProfile">获取用户信息</button>
> ```

好的 🙏，我这边试试

**Comment by okxiaoliang4** [comment]
@StrivingRabbit @fxy060608 我试了加上这个偶尔可以。大概率还是会有这个异常 requestSubscribeMessage:fail must be invoked by user tap gesture

**Comment by StrivingRabbit** [comment]
> @StrivingRabbit @fxy060608 我试了加上这个偶尔可以。大概率还是会有这个异常 requestSubscribeMessage:fail must be invoked by user tap gesture

那不应该的，是不是代码中还有其他异步的地方？

**Comment by okxiaoliang4** [comment]
> > @StrivingRabbit @fxy060608 我试了加上这个偶尔可以。大概率还是会有这个异常 requestSubscribeMessage:fail must be invoked by user tap gesture
> 
> 那不应该的，是不是代码中还有其他异步的地方？

模板ID是通过接口获取的，应该是因为这个原因吧？我试试看

**Comment by uliian** [comment]
如果模板ID是在发起订阅事件的处理方法里获取的，requestSubscribeMessage方法是在回调里调用的，同样也无法正常触发errMsg: "requestSubscribeMessage:fail must be invoked by user tap gesture", errNo: 21501
