### ISSUE TITLE
uniapp 发布到小程序的问题

### ISSUE THREAD

**Issue by a6965921** [dcloudio/uni-app#3627]
uniapp 发布到小程序的问题
页面切换  切换到某个页面的时候 会出现css没加载完就显示页面了  有什么办法可以确保css加载完再显示

**Comment by fxy060608** [comment]
css的加载，是小程序平台自己控制的，如果觉得时机有问题
1. 排查生成的css代码，是否包含了太多的代码
2. 自行控制渲染时机（v-show,v-if），比如，当页面ready时，才显示页面元素
