### ISSUE TITLE
onTabItemTap 

### ISSUE THREAD

**Issue by yuweiweiday** [dcloudio/uni-app#363]
**问题描述**
[问题描述：当前支持onTabItemTap 这个功能吗？若不支持 我怎么处理这个 item 切换]

**Comment by xiaoyucoding** [comment]
[页面生命周期->onTabItemTap](https://uniapp.dcloud.io/frame?id=%E9%A1%B5%E9%9D%A2%E7%94%9F%E5%91%BD%E5%91%A8%E6%9C%9F)
详细见文档的注意事项说明
