### ISSUE TITLE
uni-app 编译微信小程序，一个页面多个input输入框的情况下切换input弹出键盘失败，需要点击两次才行

### ISSUE THREAD

**Issue by jiajiasejon** [dcloudio/uni-app#3635]
**问题描述**
uni-app 编译微信小程序，一个页面多个input输入框的情况下,切换input弹出键盘失败，需要点击两次才行

**复现步骤**
[复现问题的步骤]
1.  首次点击a输入框，键盘弹出，正常
2. 接着去点击b输入框，下方键盘收回，焦点没有聚焦到b输入框，没有键盘弹出
3. 再次点击b输入框，有焦点，键盘弹出

**预期结果**
点击完a输入框后再次点击b输入框可直接聚焦并弹出键盘

**实际结果**
点击完a输入框后需点击两次b输入框才可直接聚焦并弹出键盘

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统  iOS 12.1.2没有此问题、Android 存在
 - HBuilderX版本  3.4.15.20220610
 - uni-app版本 
 - 设备信息 iPhone12。小米11

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
在不使用uni-app的情况下是否存在此问题？如仍然存在请反馈到微信小程序社区

**Comment by kkfive** [comment]
> 在不使用uni-app的情况下是否存在此问题？如仍然存在请反馈到微信小程序社区

我这边遇到的情况是  调试模式下（开发者预览、真机调试）无此问题。
但打包编译上传体验后 则会出现此问题。（只有安卓机能够复现此问题）
测试机型：oppo find x2 （ColorOS 12.1  安卓版本12）
