### ISSUE TITLE
uniapp vue3 vite 差量编译在大型项目中非常慢

### ISSUE THREAD

**Issue by lbb00** [dcloudio/uni-app#3637]
**问题描述**
我们有一个大型的uniapp项目大约有260+页面，之前用的是uniapp vue2，webpack打包。最近在进行升级到uniapp vue3版本，发现项目的差量编译时间非常慢。

**复现步骤**

编译耗时如图：
![screenshot-20220623-133945](https://user-images.githubusercontent.com/12634259/175224072-0a9b5ae2-ea71-4013-8f25-97746fe99e4a.png)

我们分别找了两个页面做测试，一个页面较为复杂，另一个页面作为对比只有极少量代码。没有任何改动，仅保存一下。

**系统信息:**
 - MacBook Pro (16-inch, 2019)  2.6 GHz 六核Intel Core i7  16GB内存
 - 3.0.0-alpha-3050020220622003、3.0.0-alpha-3041520220609002 连个版本都试了

**Comment by lbb00** [comment]
仅有少量代码的页面代码如下：

**Comment by fxy060608** [comment]
说明平台，需要可以重现的测试工程，hello uni-app 大约150个页面，可以测试下

**Comment by betterDan626** [comment]
请问这个情况你们后来是怎么处理的呢，是否该迁移vue3呢

**Comment by lbb00** [comment]
> 请问这个情况你们后来是怎么处理的呢，是否该迁移vue3呢

没有能解决。我们因为代码体积太大的原因不得不升级到vue3

**Comment by antonySee** [comment]
我现在也是这个问题，我电脑配置macbookpro M2Max 32G内存，小程序30+页面，每次运行久了以后，差量编译在2s左右。直接的现象就是，保存的时候，小程序热更新了，2s左右之后差量编译完成，小程序又刷新一次，哎

**Comment by trk113** [comment]
> 我现在也是这个问题，我电脑配置macbookpro M2Max 32G内存，小程序30+页面，每次运行久了以后，差量编译在2s左右。直接的现象就是，保存的时候，小程序热更新了，2s左右之后差量编译完成，小程序又刷新一次，哎

这还慢？ 我五百个页面！ 编译一下几十秒， 一天下来耽误个把小时了。。

**Comment by antonySee** [comment]
> > 我现在也是这个问题，我电脑配置macbookpro M2Max 32G内存，小程序30+页面，每次运行久了以后，差量编译在2s左右。直接的现象就是，保存的时候，小程序热更新了，2s左右之后差量编译完成，小程序又刷新一次，哎
> 
> 这还慢？ 我五百个页面！ 编译一下几十秒， 一天下来耽误个把小时了。。

我靠 那么大包

**Comment by trk113** [comment]
> > > 我现在也是这个问题，我电脑配置macbookpro M2Max 32G内存，小程序30+页面，每次运行久了以后，差量编译在2s左右。直接的现象就是，保存的时候，小程序热更新了，2s左右之后差量编译完成，小程序又刷新一次，哎
> > 
> > 
> > 这还慢？ 我五百个页面！ 编译一下几十秒， 一天下来耽误个把小时了。。
> 
> 我靠 那么大包

《小程序》

**Comment by Otto-J** [comment]
近期讨论脱离原主题了，如果你认为 vue3 的 dev/prod 编译较慢可以提供更多工程信息。提供更多信息有助于复现和定位你的问题。

## 技术参考

vue3 本身是 vite 项目，你可以安装 vite/rollup 插件观察每个阶段的耗时，进一步量化具体是哪块问题较久。目前 uni-app 的底层依赖已经升级到 vite v5，理论上性能优异。

## 后续需求进一步支持

后续如果你认为编译慢，可以提供你的复现工程，或者同比测试 hello-uni-app 官方工程，提供编译信息，做个对比，在 vue3 的 hello-uni-app 项目中包含了大量页面可供参考。

**Comment by Otto-J** [comment]
本帖时间较久，lock 此 issue，后续有进一步的可供分析的信息，请开新贴艾特我。
