### ISSUE TITLE
声明文件中缺失onLoad钩子

### ISSUE THREAD

**Issue by qq326943819** [dcloudio/uni-app#3638]
![image](https://user-images.githubusercontent.com/32457006/175225358-1f1b5ad2-88ee-4cfb-85f1-770bb771d720.png)
![image](https://user-images.githubusercontent.com/32457006/175225650-ef9c2dd3-aa80-4765-b457-b31196e19c56.png)

**Comment by fxy060608** [comment]
升级最新版本

**Comment by qq326943819** [comment]
> 

![image](https://user-images.githubusercontent.com/32457006/175231381-9b1f3ea2-43f8-49a2-a3e6-d69727f05aa9.png)
目前是latest版本

**Comment by fxy060608** [comment]
> > 升级最新版本
> 
> ![image](https://user-images.githubusercontent.com/32457006/175231381-9b1f3ea2-43f8-49a2-a3e6-d69727f05aa9.png) 目前是latest版本

用 vue3 tag 的，目前最新 vue3 最新的包版本：3.0.0-alpha-3050020220622003
