### ISSUE TITLE
类型为 [Boolean, String] 的属性默认值不符合预期

### ISSUE THREAD

**Issue by zhuscat** [dcloudio/uni-app#3639]
**问题描述**

定义一个属性：

```js
  props: {
    initialState: {
      type: [Boolean, String],
      default: ''
    }
  },
```

不给组件传 initialState，initialState 拿到的值为 true

**复现步骤**
1.  可复现项目：https://github.com/zhuscat/uniapp-vue3-demo/tree/props-default
2. 分支为 props-default
3. 看 src/pages/index/foo.vue 中的代码，mounted 中打印 initialState，值为 true

**预期结果**
为空字符串

**实际结果**
为 `true`

**系统信息:**
 - 发行平台: 微信小程序
 - uni-app版本：3.0.0-alpha-3041520220609002

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
在微信小程序测试没有问题

**Comment by zhuscat** [comment]
写错了，是 [Boolean, String]，我更新了下代码，如果是 [String, Boolean] 是没问题的

**Comment by fxy060608** [comment]
这是标准的vue3行为，可以使用原始的vue3测试
https://github.com/vuejs/core/blob/9ecee16f891d3ab22fec92d16b20805b5619bfa3/packages/runtime-core/src/componentProps.ts#L451
