### ISSUE TITLE
vue3 nvue下配置switch组件color属性颜色未改变

### ISSUE THREAD

**Issue by shier112** [dcloudio/uni-app#3640]
**问题描述**
vue3 nvue下switch组件color属性不生效

**复现步骤**
```
// index.nvue
<!-- 颜色没有改变 -->
<switch color="#2F8EFA" checked="true"/>
```

**预期结果**
选中颜色跟随color属性

**实际结果**
选中颜色未跟随color属性

**系统信息:**
 - 发行平台: [APP]
 - 操作系统 [Android 10.0]
 - HBuilderX版本 [3.4.15]
 - uni-app版本 [3.4.15]
 - 设备信息 [华为 nova 7 Pro 5G]

**补充信息**
可否新增未选中时颜色的属性,用来适配深色模式

**Comment by shier112** [comment]
@fxy060608

**Comment by shier112** [comment]
@dcloudhdx 有计划增加未选中时的颜色吗,想适配深色模式,还有就是vue3 nvue的bug有点多😂

**Comment by forqsg** [comment]
我使用的vue2下switch的color属性，设置了颜色，不生效，打开关闭都是灰色，关闭状态下会有一个x号
