### ISSUE TITLE
vue3 百度小程序自动触发点击事件

### ISSUE THREAD

**Issue by amihhs** [dcloudio/uni-app#3647]
**问题描述**
在页面重新渲染是会触发元素的click事件

**复现步骤**
1.跳转的发布页面（分包中）
2.先选择问题，确认后返回发布页面
3.选择图片，会自动跳转回选择问题页面。
[demo](https://github.com/amihhs/uniapp-vue3-issue)

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [百度小程序]
 - cli 3.0.0-alpha-3050020220617004

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
cli 更新至：3.0.0-alpha-3050020220623002
