### ISSUE TITLE
无法获取textarea的cursor

### ISSUE THREAD

**Issue by CR903** [dcloudio/uni-app#365]
**问题描述**
在android调用textarea的blur，无法的到文档中所说的cursor属性值：
![image](https://user-images.githubusercontent.com/7643647/56952336-b3e0b980-6b6c-11e9-9b17-78a946153d24.png)

仅能得到如下属性值：
![image](https://user-images.githubusercontent.com/7643647/56952414-e7234880-6b6c-11e9-829d-aa9b2f21b422.png)

**复现步骤**
1、给textarea指定blur方法，打印event.detail值
2、改变textarea内容后，点击textarea外其他区域。

**预期结果**
得到如文档所说的属性value和cursor值

**实际结果**
只能得到value属性值，并无cursor属性。

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 Android 8.0，IOS没测试过。
 - HBuilderX版本 
![image](https://user-images.githubusercontent.com/7643647/56952749-98c27980-6b6d-11e9-825e-2a666cfdf7a9.png)
 - uni-app版本 IDE自带版本
 - 设备信息 [荣耀8]

**Comment by zhetengbiji** [comment]
HBuilderX 2.1.0 及以上版本已修复

**Comment by MHanL** [comment]
这个问题在微信小程序上面出现了
