### ISSUE TITLE
button 组件的 open-type属性，不支持微信的chooseAvatar

### ISSUE THREAD

**Issue by uckyo** [dcloudio/uni-app#3654]
**问题描述**

button 组件的 open-type属性，不支持微信的chooseAvatar。

用户点击使用微信头像，进入不了bindchooseavatar回调。

uniapp的button文档里open-type里也没有chooseAvatar的取值

![image](https://user-images.githubusercontent.com/105033085/175489695-9645d12e-f315-4610-9ea0-337070f445e4.png)

![image](https://user-images.githubusercontent.com/105033085/175488708-a368b22e-a579-4ac2-845d-ba633689bdd3.png)
![image](https://user-images.githubusercontent.com/105033085/175488915-c35bea7e-4273-4d6b-98d4-51272d9a7277.png)

**Comment by zhenyuWang** [comment]
uni-app 使用 vue 语法，绑定事件使用 @，`bind:chooseavatar` 改为 `@chooseavatar`
