### ISSUE TITLE
微信小程序：支持 project.private.config.json 

### ISSUE THREAD

**Issue by Michael-py001** [dcloudio/uni-app#3655]
**问题描述**
Vue3项目 HBuilder X 3.5.0 alpha 编译到微信小程序 每次重新编译，都会把微信开发者工具之前保存的编译模式清空

**复现步骤**
[复现问题的步骤]
![image](https://user-images.githubusercontent.com/60598432/175494689-8890a20b-0db4-4b5d-9e31-fb18de7615eb.png)

**预期结果**
不清空编译模式

**实际结果**
清空了编译模式

**系统信息:**
微信小程序
HBuilder X 3.5.0 alpha

**Comment by fxy060608** [comment]
如果要持久化编译模式，自己在pages.json中配置[condition](https://uniapp.dcloud.net.cn/collocation/pages.html#condition)

**Comment by Michael-py001** [comment]
@fxy060608 之前的vue2项目都没有像这样丢失编译模式，就是现在vue3使用vite后就变成这样了，不能把`mp-weixin`下的`project.config.json`和`project.private.config.json`保留吗？不然开发环境几十个页面每次都清除保存的编译模式，每次都要自己翻来翻去找那个页面，这样合理吗？

**Comment by fxy060608** [comment]
> @fxy060608 之前的vue2项目都没有像这样丢失编译模式，就是现在vue3使用vite后就变成这样了，不能把`mp-weixin`下的`project.config.json`和`project.private.config.json`保留吗？不然开发环境几十个页面每次都清除保存的编译模式，每次都要自己翻来翻去找那个页面，这样合理吗？

你说的重新编译，是指的重新运行？还是修改代码热更新？

**Comment by Michael-py001** [comment]
开发阶段中途报错了，重新运行就丢失编译模式，这怎么开发？

**Comment by fxy060608** [comment]
> condition

注意看我发的回复：
之前官方支持的标准做法是在pages.json中配置condition来实现微信小程序的编译模式：https://uniapp.dcloud.net.cn/collocation/pages.html#condition

vue2之所以可以，是因为没有完整清空输出目录，意外的保留了 project.private.config.json，才出现了你说的保持了编译模式
vue3会完整清空输出目录
所以这个问题应该是，让uni-app支持配置 project.private.config.json

**Comment by Michael-py001** [comment]
@fxy060608 刚刚更新了3.5.1.20220707-alpha，官方的更新日志说已经解决了，为什么还是会丢失编译模式呢？我观察project.config.json每次都会被删了重新建的

**Comment by fxy060608** [comment]
> @fxy060608 刚刚更新了3.5.1.20220707-alpha，官方的更新日志说已经解决了，为什么还是会丢失编译模式呢？我观察project.config.json每次都会被删了重新建的

测试没有问题，重新编译时，输出目录的project.config.json,project.private.config.json都会保留

**Comment by Michael-py001** [comment]
@fxy060608 找到问题了，我是像平常一样在ide内收到提示升级的，正常升级重启后是依旧没有更新到这个Bug，我在官网重新下载了alpha包运行是正常的，可能是更新包的问题

**Comment by qiuquang** [comment]
> @fxy060608 刚刚更新了3.5.1.20220707-alpha，官方的更新日志说已经解决了，为什么还是会丢失编译模式呢？我观察project.config.json每次都会被删了重新建的

这个文件在修改vue代码不动项目配置的时候能不能不每次都变呀，我们有个插件是用了fs.watchFile(‘mp-weixin/project.config.json’）来实现的，每次都变化的话，那个功能就异常了（另外我不是用的uniapp vue3，我用的uniappvue2+composition API的项目）
