### ISSUE TITLE
uni-app不支持非vue文件里的组件，报错，且页面白屏

### ISSUE THREAD

**Issue by jqhr** [dcloudio/uni-app#3657]
**问题描述**
我这边有个项目是需要动态组件的，就是web端配置json，在手机端解析json并渲染表单，因此我的组件是js动态render的，直接在页面引入这个js会报错，报"Not found -1,0;-1,0,undefined,undefined,0,undefined,undefined at view.umd.min.js:1"。

**复现步骤**
[复现问题的步骤]
1. 我写了个js文件，里面写个了方法，类似
```js
export function createForm({
  components,
 plugins,
mixins,
events,
}) {
 const injectComponents = plugins.filter(p => p.inject).map(p => p.inject)
 const _components = components.map(c => {
  return injectComponents.map(inject => inject(c))
})
 return {
   components: _components,
   mixins: [...mixins],
   props: {
     formJson: {
       type: Object,
        default: () => ({})
      }  
   },
   data() {
     return {
       formInstance: {}
     }
   },
  computed: {
    formItems() {
      return this.formJson.rules.map(rule => {
        // TOOD: 处理rule
        return { ...rule }
      }) 
    }
  },
   created() {
     // TODO: parse formJson
   },
   render(h) {
     // renderComponent是一个渲染方法
     const slots = this.formItems.map(formItem => renderComponent(h, formItem, this.formInstance))
     return h('form', {
     }, slots)
   }
 }
}
```

**预期结果**
预期能渲染组件

**实际结果**
整个页面直接白屏(包含该组件的页面),控制台报“Not found -1,0;-1,0,undefined,undefined,0,undefined,undefined at view.umd.min.js:1”

**系统信息:**
 - 发行平台: [App]
 - 操作系统 [Android 11.0]
 - HBuilderX版本 [3.3.11]
 - uni-app版本 [是HBuilderX创建项目，不清楚版本]
 - 设备信息 [ RealmeX2 ]

希望能支持，@zhetengbiji，@fxy060608，@Wangyaqi

**Comment by fxy060608** [comment]
vue2不支持render函数

**Comment by fxy060608** [comment]
> > vue2不支持render函数
> > 那vue3的render支持的怎么样？有什么限制？

h5和App支持jsx，小程序不支持
