### ISSUE TITLE
为什么上传的开发者是ci机器人了

### ISSUE THREAD

**Issue by a6965921** [dcloudio/uni-app#3664]
![image](https://user-images.githubusercontent.com/1198840/175913129-aea8235a-4717-4cae-a705-cff350c34dc5.png)

**Comment by zhetengbiji** [comment]
请详细说明

**Comment by a6965921** [comment]
开发者不应该是自己吗   我用了hbuilder发布小程序

**Comment by iamxiyang** [comment]
如果你使用的是Hbx的自动发布，会显示ci机器人。
如果你是通过微信开发者工具提交发布的，会显示提交者的信息

**Comment by zhetengbiji** [comment]
哪个平台的小程序？

**Comment by a6965921** [comment]
微信

**Comment by zhetengbiji** [comment]
> 微信

问一下微信那边这里这样显示是否正常。
