### ISSUE TITLE
mp-alipay   manifest.json 文件 enableAppxNg属性配置无效   vue3.0命令行版

### ISSUE THREAD

**Issue by ONwaiting** [dcloudio/uni-app#3667]
enableAppxNg 无论配置true或者false 编译出的文件mini.project.json都是true
vue2.0版 正常

**Comment by fxy060608** [comment]
仅支持enableAppxNg为true

**Comment by fxy060608** [comment]
> 这样的话vue3.0版本淘宝小程序的插件就用不了了，能否支持下可配

淘宝小程序的插件，必须是enableAppxNg为false？文档发一下

**Comment by ONwaiting** [comment]
编辑器试出来的，没有文档
