### ISSUE TITLE
picker组件在H5平台下存在Bug

### ISSUE THREAD

**Issue by powerlau** [dcloudio/uni-app#367]
**问题描述**
uni-app picker组件在H5平台下用手指上下滑动列表，当滑动到某个项目立刻点确定以后，发现根本没有选中那个项目。比如有五个列表项，目前在第一项，当我滑动到第五项的时候，需要再等1、2秒按确定才能选中，如果立刻点确定，那么即使视觉上显示到了第五项，然而选中的依然是第一项。这个问题不管mode是什么模式都存在问题。
同时我也发现有人已经提出过这个问题了，链接如下
https://github.com/dcloudio/uni-app/issues/278
不知道为啥过了这么多天依然没人回复

**Comment by powerlau** [comment]
这个问题相当影响用户体验的，总不能让用户等几秒再按确定吧。

**Comment by changexbc** [comment]
> 这个问题相当影响用户体验的，总不能让用户等几秒再按确定吧。 @mehaotian

到目前为止依然没有修复这个问题，希望h5也可以暴露@start和@end方法让开发者可以来控制确定按钮是否可点击，现在根本没有办法解决这个用户体验的问题  @zhetengbiji
