### ISSUE TITLE
【vue3】能否对 pages.json 的监听使用环境变量控制

### ISSUE THREAD

**Issue by sufuwang** [dcloudio/uni-app#3672]
我需要根据环境变量生成对应的 pages.json 文件，比如环境变量 env 为 a 时，将 pages.a.json 复制一份且重命名为 pages.json，env 为 b 时同理，我需要 `this.addWatchFile('pages.a.json')`，这与 `uni:mp-pages-json` 下的 `this.addWatchFile('pages.json')` 冲突，会造成循环编译，请问能否对 `this.addWatchFile('pages.json')`  设置可选

**Comment by fxy060608** [comment]
自己单独watch自己的pages.a.json，然后同步修改pages.json，为什么会导致循环？

**Comment by sufuwang** [comment]
因为 pages.a.json 的改动，会生成一份新的 pages.json 文件

**Comment by fxy060608** [comment]
> 因为 pages.a.json 的改动，会生成一份新的 pages.json 文件
pages.json本来就要变，你自己手动修改pages.json，不也是要变吗？为何手动修改就不会触发死循环？
不知道你怎么写的，你可以选择，单独写一个js，单独 watch pages.a.json，发现变化，就更新 pages.json

**Comment by sufuwang** [comment]
<img width="970" alt="image" src="https://user-images.githubusercontent.com/46395105/176633209-2fb81047-17b0-48c6-b1ae-2cf5f053bab0.png">

**Comment by sufuwang** [comment]
大佬，你看我的插件和 uni:mp-pages-json 都可以触发流水线重新执行，你说的对，pages.json 必须得 addWatchFile ，有没有什么办法能解决这种情况啊

**Comment by fxy060608** [comment]
> 大佬，你看我的插件和 uni:mp-pages-json 都可以触发流水线重新执行，你说的对，pages.json 必须得 addWatchFile ，有没有什么办法能解决这种情况啊

明白了，你是自己写了vite的插件，然后监听pages.a.json的变化，再写入pages.json，导致循环了
1. vite 插件里边判断pages.a.json是否内容发生变化，变化了再写入pages.json，这样，可以把触发rebuild限定到两次，而不会死循环了
2. 不用vite插件监听，直接自己用fs.watchFile或者其他三方watch，监听pages.a.json的变化，写入pages.json，这样可以避免循环

**Comment by sufuwang** [comment]
> > 大佬，你看我的插件和 uni:mp-pages-json 都可以触发流水线重新执行，你说的对，pages.json 必须得 addWatchFile ，有没有什么办法能解决这种情况啊
> 
> 明白了，你是自己写了vite的插件，然后监听pages.a.json的变化，再写入pages.json，导致循环了
> 
> 1. vite 插件里边判断pages.a.json是否内容发生变化，变化了再写入pages.json，这样，可以把触发rebuild限定到两次，而不会死循环了
> 2. 不用vite插件监听，直接自己用fs.watchFile或者其他三方watch，监听pages.a.json的变化，写入pages.json，这样可以避免循环

@fxy060608 
大佬，你说的没有问题，第一个方案因为要 rebuild 两次，所以我现在是这样做的，你看看有问题没

在我的插件中，load 里面使用 pages.a.json 覆盖 pages-json-js ，然后监听 pages.a.json 文件，只是变化体现不到 pages.json 文件上了
```js
plugins: [
  // 我的插件, enforce: pre
  PagesJsonPlugin({ WxPlatform: process.env.WX_PLATFORM }),
  uni(),
]
```

**Comment by fxy060608** [comment]
> > > 大佬，你看我的插件和 uni:mp-pages-json 都可以触发流水线重新执行，你说的对，pages.json 必须得 addWatchFile ，有没有什么办法能解决这种情况啊
> > 
> > 
> > 明白了，你是自己写了vite的插件，然后监听pages.a.json的变化，再写入pages.json，导致循环了
> > 
> > 1. vite 插件里边判断pages.a.json是否内容发生变化，变化了再写入pages.json，这样，可以把触发rebuild限定到两次，而不会死循环了
> > 2. 不用vite插件监听，直接自己用fs.watchFile或者其他三方watch，监听pages.a.json的变化，写入pages.json，这样可以避免循环
> 
> @fxy060608 大佬，你说的没有问题，第一个方案因为要 rebuild 两次，所以我现在是这样做的，你看看有问题没
> 
> 在我的插件中，load 里面使用 pages.a.json 覆盖 pages-json-js ，然后监听 pages.a.json 文件，只是变化体现不到 pages.json 文件上了
> 
> ```js
> plugins: [
>   // 我的插件, enforce: pre
>   PagesJsonPlugin({ WxPlatform: process.env.WX_PLATFORM }),
>   uni(),
> ]
> ```

通常问题不大，在部分情况下可能会有问题，比如有人import了pages.json，（uniCloud内部就访问了pages.json）,此时还是需要拦截pages.json的加载，返回你真实的pages.a.json

**Comment by sufuwang** [comment]
> > > > 大佬，你看我的插件和 uni:mp-pages-json 都可以触发流水线重新执行，你说的对，pages.json 必须得 addWatchFile ，有没有什么办法能解决这种情况啊
> > > 
> > > 
> > > 明白了，你是自己写了vite的插件，然后监听pages.a.json的变化，再写入pages.json，导致循环了
> > > 
> > > 1. vite 插件里边判断pages.a.json是否内容发生变化，变化了再写入pages.json，这样，可以把触发rebuild限定到两次，而不会死循环了
> > > 2. 不用vite插件监听，直接自己用fs.watchFile或者其他三方watch，监听pages.a.json的变化，写入pages.json，这样可以避免循环
> > 
> > 
> > @fxy060608 大佬，你说的没有问题，第一个方案因为要 rebuild 两次，所以我现在是这样做的，你看看有问题没
> > 在我的插件中，load 里面使用 pages.a.json 覆盖 pages-json-js ，然后监听 pages.a.json 文件，只是变化体现不到 pages.json 文件上了
> > ```js
> > plugins: [
> >   // 我的插件, enforce: pre
> >   PagesJsonPlugin({ WxPlatform: process.env.WX_PLATFORM }),
> >   uni(),
> > ]
> > ```
> 
> 通常问题不大，在部分情况下可能会有问题，比如有人import了pages.json，（uniCloud内部就访问了pages.json）,此时还是需要拦截pages.json的加载，返回你真实的pages.a.json

```js
// CurPagesFilePath: pages.a.json 的地址
// CurPagesFile: pages.a.json 的内容，与 load 中覆盖 pages-json-js 的 json 一致
transform(code, id) {
    if (id.includes('/src/pages.json')) {
      this.addWatchFile(CurPagesFilePath);
      return {
        code: CurPagesFile,
        map: { mappings: '' },
      };
    }
  },
```
@fxy060608  大佬，看看这样能否解决

**Comment by fxy060608** [comment]
> ```js
> pages-json-js
> ```

你不是在load中拦截了pages-json-js么，那同时拦截pages.json是不是就可以了

**Comment by sufuwang** [comment]
> > ```js
> > pages-json-js
> > ```
> 
> 你不是在load中拦截了pages-json-js么，那同时拦截pages.json是不是就可以了

说的对哦

**Comment by sufuwang** [comment]
> > ```js
> > pages-json-js
> > ```
> 
> 你不是在load中拦截了pages-json-js么，那同时拦截pages.json是不是就可以了

```js
  async load(id) {
    if (id.includes('pages-json-js') || id.includes('/src/pages.json')) {
      const code = await getPagesJson({ WxPlatform });
      this.addWatchFile(PagesFile.path);
      return code;
    }
  },
```
@fxy060608 大佬，这是我的插件代码，有一个问题想请教，为什么我更新 vue 文件，也会触发这个插件呀
