### ISSUE TITLE
官网cli 命令行最新模板问题

### ISSUE THREAD

**Issue by BinChenLiao** [dcloudio/uni-app#3673]
(https://user-images.githubusercontent.com/37283139/176642711-4fe6c2ac-adcc-4f04-a577-c412b33b2282.jpg)
添加点击事件点击h5正常  飞书小程序不正常 会触发两次

**Comment by fxy060608** [comment]
目前确认应该是飞书小程序底层调整引发的，在基础库 1.9.58.4 时，是没有问题的，已协调飞书小程序团队进行跟踪解决

**Comment by BinChenLiao** [comment]
> 目前确认应该是飞书小程序底层调整引发的，在基础库 1.9.58.4 时，是没有问题的，已协调飞书小程序团队进行跟踪解决

我联系下我们内部解决

**Comment by fxy060608** [comment]
飞书小程序官方已修复，可以再更新验证下
