### ISSUE TITLE
在pages.json中，tabBar无法配置Style，无法实现自定义顶部导航

### ISSUE THREAD

**Issue by SimonLeeee** [dcloudio/uni-app#3674]
在pages.json中，tabBar配置Style、navigationStyle等等均无效。

**Comment by SimonLeeee** [comment]
同样的，在tabBar的配置中，也无法定义顶部导航的标题navigationBarTitleText

**Comment by fxy060608** [comment]
tabBar里边配置了页面路径，标题等信息，都是在pages中配置

**Comment by SimonLeeee** [comment]
> tabBar里边配置了页面路径。标题等信息，都是在pages中配置

文档里面没有找到可以配置自定义顶部导航的（指带有tabBar的页面）；https://uniapp.dcloud.net.cn/collocation/pages.html#tabbar；

**Comment by SimonLeeee** [comment]
> 

我没有说是页面路径这些信息，我说的是，在带有tabBar的页面，没有办法配置顶部导航的名称，以及自定义顶部的导航。

**Comment by fxy060608** [comment]
> > tabBar里边配置了页面路径。标题等信息，都是在pages中配置
> 
> 文档里面没有找到可以配置自定义顶部导航的（指带有tabBar的页面）；[https://uniapp.dcloud.net.cn/collocation/pages.html#tabbar；](https://uniapp.dcloud.net.cn/collocation/pages.html#tabbar%EF%BC%9B)

首先，页面要先在pages中配置，这里边可以配置各种导航栏信息，其次才可以在tabBar中配置该页面地址。tabBar不是独立存在的。
