### ISSUE TITLE
v-for key 元素复用事件绑定错乱

### ISSUE THREAD

**Issue by zhuscat** [dcloudio/uni-app#3677]
**问题描述**

v-for 用元素「id」作为 key，元素顺序发生变化，会出现 BUG

**复现步骤**
1. 最小可复现项目 https://github.com/zhuscat/uniapp-vue3-demo/tree/v-for-bug
2. 分支 v-for-bug
3. pages/index/index 页面中，先点击 toggle 按钮，点击渲染出的元素，在控制台打印的是元素对应的值
4. 再点击 toggle 按钮，点击渲染的元素，控制台打印的是错乱的，比如点击 2，打印出的是 3

**预期结果**
控制台中打印的是元素对应的值

**实际结果**
控制台中打印的是错乱的

**系统信息:**
 - 发行平台: 微信小程序
 - uni-app版本：3.0.0-alpha-3041520220609002

**补充信息**
微信复用元素，事件绑定还是原来的那个

**Comment by zhuscat** [comment]
开发者工具 手机均可复现

**Comment by zhuscat** [comment]
请问是 BUG 么 @fxy060608

**Comment by zh1011** [comment]
我也遇到了  最后我用了index当做key

**Comment by fxy060608** [comment]
已修复：cli 更新至 3.0.0-alpha-3050120220706002

**Comment by zhaocaiwang** [comment]
为啥我升级版本还是不行

**Comment by zhaocaiwang** [comment]
@zhuscat 可以吗升级这个，我升级还是不行

**Comment by ashin0808** [comment]
3.0.0-alpha-3060420220922001
还是不行
