### ISSUE TITLE
使用uni-upgrade-center - App报错uniCloud.importObject is not a function

### ISSUE THREAD

**Issue by lovehebe330** [dcloudio/uni-app#3680]
**问题描述**
使用uni-upgrade-center - App 升级时在app.vue引入import appUpdate from "@/uni_modules/uni-upgrade-center-app/utils/check-update.js"调用时时报错uniCloud.importObject is not a function

![image](https://user-images.githubusercontent.com/20655248/177124027-0e6a7940-cc44-493a-ad6b-4c74172fdf4f.png)

hbuilder版本为
![image](https://user-images.githubusercontent.com/20655248/177124173-52d0255a-4e20-4169-b980-17d3cf472432.png)

**系统信息:**
- HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Wangyaqi** [comment]
cli项目还是HBuilderX创建的项目？

**Comment by lovehebe330** [comment]
> cli项目还是HBuilderX创建的项目？

cli的项目， 删掉依赖库再yarn install 一下就可以了
