### ISSUE TITLE
wx.chooseLocation在H5环境中，偶现加载报错，地图信息不展示的情况

### ISSUE THREAD

**Issue by jide123456** [dcloudio/uni-app#3681]
**问题描述**
wx.chooseLocation在H5环境中，偶现加载报错的情况，页面不展示位置列表

**复现步骤**
1.启动项目（h5环境）
2.多次调用 wx.chooseLocation
3.报错出现（20，30次调用能复现一次）

**预期结果**
wx.chooseLocation在H5环境中，不报错，页面能正常展示位置列表

**实际结果**
![image](https://user-images.githubusercontent.com/21555863/177300338-072eeeda-c6fb-4f01-8ebd-9c11db202728.png)

**系统信息:**
 - 发行平台: H5平台
 - 操作系统：微信开发者工具
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 3.0.0-alpha-3050020220623003

**补充信息**
猜测：可能和接口的响应顺序有关

**Comment by jide123456** [comment]
https://user-images.githubusercontent.com/21555863/177303754-8e9f8819-2788-40e8-a58b-35bad4a1d66d.mp4

**Comment by jide123456** [comment]
手机访问h5的官方示例也会偶尔出现这个问题； 地点列表不展示； 要移动下地图后才会重新展示； 不操作的话地点列表就一直不展示； 会让用户觉得网卡或者程序挂掉了的感觉

**Comment by zhetengbiji** [comment]
对应的PR已合并，是否测试过和当前issue的关联：即在本地修改后测试是否解决了当前问题？

**Comment by jide123456** [comment]
@zhetengbiji   已测试验证， 在本地修改后， 问题没再复现

**Comment by zhetengbiji** [comment]
> @zhetengbiji 已测试验证， 在本地修改后， 问题没再复现

好的，感谢，3.5.2 alpha 版本已携带此更改。

**Comment by jide123456** [comment]
@zhetengbiji  你好， 这个问题又复现了，我发现最新版本（3.0.0-alpha-3050420220804008）的包里面，没有这段代码，麻烦看下呢
![image](https://user-images.githubusercontent.com/21555863/186108828-14ad3849-3a02-4a1f-8ed9-89d3e46cf261.png)

**Comment by jide123456** [comment]
> @zhetengbiji 你好， 这个问题又复现了，我发现最新版本（3.0.0-alpha-3050420220804008）的包里面，没有这段代码，麻烦看下呢 ![image](https://user-images.githubusercontent.com/21555863/186108828-14ad3849-3a02-4a1f-8ed9-89d3e46cf261.png)

master分支里的代码有我pr的逻辑，但是发出来的包里面没有

**Comment by zhetengbiji** [comment]
> > @zhetengbiji 你好， 这个问题又复现了，我发现最新版本（3.0.0-alpha-3050420220804008）的包里面，没有这段代码，麻烦看下呢 ![image](https://user-images.githubusercontent.com/21555863/186108828-14ad3849-3a02-4a1f-8ed9-89d3e46cf261.png)
> 
> master分支里的代码有我pr的逻辑，但是发出来的包里面没有

收到，vue3 版本对应的为 next 分支。

**Comment by jide123456** [comment]
> > > @zhetengbiji 你好， 这个问题又复现了，我发现最新版本（3.0.0-alpha-3050420220804008）的包里面，没有这段代码，麻烦看下呢 ![image](https://user-images.githubusercontent.com/21555863/186108828-14ad3849-3a02-4a1f-8ed9-89d3e46cf261.png)
> > 
> > 
> > master分支里的代码有我pr的逻辑，但是发出来的包里面没有
> 
> 收到，vue3 版本对应的为 next 分支。

soga， nuxt分支下确实没有这段代码，那我再提个pr吧

**Comment by zhetengbiji** [comment]
> > > > @zhetengbiji 你好， 这个问题又复现了，我发现最新版本（3.0.0-alpha-3050420220804008）的包里面，没有这段代码，麻烦看下呢 ![image](https://user-images.githubusercontent.com/21555863/186108828-14ad3849-3a02-4a1f-8ed9-89d3e46cf261.png)
> > > 
> > > 
> > > master分支里的代码有我pr的逻辑，但是发出来的包里面没有
> > 
> > 
> > 收到，vue3 版本对应的为 next 分支。
> 
> soga， nuxt分支下确实没有这段代码，那我再提个pr吧

刚修改了一下，等发布更新后通知你。

**Comment by jide123456** [comment]
>



> > > > > @zhetengbiji 你好， 这个问题又复现了，我发现最新版本（3.0.0-alpha-3050420220804008）的包里面，没有这段代码，麻烦看下呢 ![image](https://user-images.githubusercontent.com/21555863/186108828-14ad3849-3a02-4a1f-8ed9-89d3e46cf261.png)
> > > > 
> > > > 
> > > > master分支里的代码有我pr的逻辑，但是发出来的包里面没有
> > > 
> > > 
> > > 收到，vue3 版本对应的为 next 分支。
> > 
> > 
> > soga， nuxt分支下确实没有这段代码，那我再提个pr吧
> 
> 刚修改了一下，等发布更新后通知你。

好的，谢谢啦
