### ISSUE TITLE
uni-app 支持vue3中jsx开发模式吗？

### ISSUE THREAD

**Issue by xhan4** [dcloudio/uni-app#3683]

**Comment by fxy060608** [comment]
h5,App支持，小程序端不支持

**Comment by xhan4** [comment]
> h5,App支持，小程序端不支持
像这种用法我应该怎么配置才不报错
<template>
  <componet :is="test"/>
</template>
<script setup>
  const test=()=>{
	   return   <>
                <h1>It is Test</h1>
                </>
  }
</script>

**Comment by xhan4** [comment]
> h5,App支持，小程序端不支持

像这种用法我应该怎么配置才能用？
![image](https://user-images.githubusercontent.com/74229653/177683329-67e6e694-d366-4497-b639-29b8298649ea.png)

**Comment by fxy060608** [comment]
不支持，只支持jsx，tsx文件开发

**Comment by xhan4** [comment]
> 不支持，只支持jsx，tsx文件开发
后续会支持吗？

**Comment by fxy060608** [comment]
> > 不支持，只支持jsx，tsx文件开发
> > 后续会支持吗？

暂无计划，意义不大，可以把 test 抽离出来变成jsx，tsx再导入使用。

**Comment by Miofly** [comment]
弃坑吧，隔壁的 taro 好歹还在努力支持

**Comment by guohuihot** [comment]
没意义？怕是没用过jsx吧

**Comment by fxy060608** [comment]
> 没意义？怕是没用过jsx吧

看回复的上下文，意义不大指的是在vue文件里边，又使用了函数返回jsx代码，正常的jsx，tsx文件是支持的

**Comment by Miofly** [comment]
> > 没意义？怕是没用过jsx吧
> 
> 看回复的上下文，意义不大指的是在vue文件里边，又使用了函数返回jsx代码，正常的jsx，tsx文件是支持的

H5支持，小程序不支持，这种就没有意义，uniapp 的用户集中在小程序端吧

**Comment by fxy060608** [comment]
> > > 没意义？怕是没用过jsx吧
> > 
> > 
> > 看回复的上下文，意义不大指的是在vue文件里边，又使用了函数返回jsx代码，正常的jsx，tsx文件是支持的
> 
> H5支持，小程序不支持，这种就没有意义，uniapp 的用户集中在小程序端吧

小程序端为了性能，使用静态编译方法，jsx，tsx太灵活，静态编译很难完整兼容。

**Comment by Miofly** [comment]
> > > > 没意义？怕是没用过jsx吧
> > > 
> > > 
> > > 看回复的上下文，意义不大指的是在vue文件里边，又使用了函数返回jsx代码，正常的jsx，tsx文件是支持的
> > 
> > 
> > H5支持，小程序不支持，这种就没有意义，uniapp 的用户集中在小程序端吧
> 
> 小程序端为了性能，使用静态编译方案，jsx，tsx太灵活，静态编译很难完整兼容。

这种一般使用者肯定不会关注，只会关注这个库有哪些功能，带来了哪些便利，既然使用了 uniapp，目标就是 H5 代码 小程序代码互通，不可能 H5 写了一套 uniapp 组件库然后里面用到了 jsx，然后小程序或者 app 不支持，template 的语法在大型页面，复杂组件本身就有很多缺陷，不用 jsx 去处理显然是不现实的，能在有限的范围内支持 jsx 应该是需要考虑的。

**Comment by fxy060608** [comment]
> > > > > 没意义？怕是没用过jsx吧
> > > > 
> > > > 
> > > > 看回复的上下文，意义不大指的是在vue文件里边，又使用了函数返回jsx代码，正常的jsx，tsx文件是支持的
> > > 
> > > 
> > > H5支持，小程序不支持，这种就没有意义，uniapp 的用户集中在小程序端吧
> > 
> > 
> > 小程序端为了性能，使用静态编译方案，jsx，tsx太灵活，静态编译很难完整兼容。
> 
> 这种一般使用者肯定不会关注，只会关注这个库有哪些功能，带来了哪些便利，既然使用了 uniapp，目标就是 H5 代码 小程序代码互通，不可能 H5 写了一套 uniapp 组件库然后里面用到了 jsx，然后小程序或者 app 不支持，template 的语法在大型页面，复杂组件本身就有很多缺陷，不用 jsx 去处理显然是不现实的，能在有限的范围内支持 jsx 应该是需要考虑的。

欢迎pr

**Comment by zhangweia** [comment]
哥们，你用上了吗？我jsx语法一直用不起来，搞定的话能不能提供一个例子

**Comment by Miofly** [comment]
> 哥们，你用上了吗？我jsx语法一直用不起来，搞定的话能不能提供一个例子

这个编译工具就没打算支持tsx，放弃吧

**Comment by zhetengbiji** [comment]
> > 哥们，你用上了吗？我jsx语法一直用不起来，搞定的话能不能提供一个例子
> 
> 这个编译工具就没打算支持tsx，放弃吧

支持，参考[文档](https://uniapp.dcloud.net.cn/tutorial/syntax-jsx.html#jsx-tsx-%E6%94%AF%E6%8C%81)

**Comment by Miofly** [comment]
> > 哥们，你用上了吗？我jsx语法一直用不起来，搞定的话能不能提供一个例子
> 
> 支持，参考[文档](https://uniapp.dcloud.net.cn/tutorial/syntax-jsx.html#jsx-tsx-%E6%94%AF%E6%8C%81)

重要的是小程序的支持，真正用uniapp的小程序才是最重要的。

**Comment by zhetengbiji** [comment]
> > > 哥们，你用上了吗？我jsx语法一直用不起来，搞定的话能不能提供一个例子
> > 
> > 
> > 支持，参考[文档](https://uniapp.dcloud.net.cn/tutorial/syntax-jsx.html#jsx-tsx-%E6%94%AF%E6%8C%81)
> 
> 重要的是小程序的支持，真正用uniapp的小程序才是最重要的。

小程序端为了性能，使用静态编译方案，jsx，tsx太灵活，静态编译很难完整兼容。

**Comment by Otto-J** [comment]
#4683

**Comment by james-curtis** [comment]
> 弃坑吧，隔壁的 taro 好歹还在努力支持

似乎隔壁 taro 的 rn 支持比较差点意思

**Comment by jiangyh1024** [comment]
问一下 如果用vue2 是不是不支持 jsx的写法

**Comment by amtf-ly** [comment]
想在uni-admin里面使用jsx似乎也是不能够的，dev的时候正常，打包部署后，就不行了，是因为引入vite.config.js导致无法正确编译admin的其他页面？
