### ISSUE TITLE
[严重]更改代码后不编译

### ISSUE THREAD

**Issue by yxw007** [dcloudio/uni-app#3685]
**问题描述**
1. 问题1：修改代码不动态编译
2. 问题2：子组件不显示（应该是问题1导致）

**复现步骤**
1.  git clone https://github.com/yxw007/uniapp_issue/tree/ComponentDisplayIssus
3. yarn 
4. yarn dev

**预期结果**
开发模式，修改后能实时编译

**实际结果**
请看附件视频

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统
 - uni-app版本: 3.0.0-alpha-3030820220114008

**补充信息**

现象视频：
https://user-images.githubusercontent.com/9338717/177722445-2ff938ce-1f0b-430e-a5b5-840aa4494c38.mp4

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3050120220706002

**Comment by yxw007** [comment]
> 已修复，cli更新至：3.0.0-alpha-3050120220706002

辛苦了，测试这种情况确实解决了。但是我实际项目还碰到其他情况不编译的情况，我另外在提交一个bug吧
