### ISSUE TITLE
使用subNVue解决video覆盖自定义导航栏的问题

### ISSUE THREAD

**Issue by lhf2** [dcloudio/uni-app#3686]
为啥一直报错
<img width="317" alt="image" src="https://user-images.githubusercontent.com/10812579/177749527-4059c116-9027-4e24-99af-5760811df493.png">

我的配置：
<img width="516" alt="image" src="https://user-images.githubusercontent.com/10812579/177749602-95d9640f-4016-484a-836a-ad86472b9c08.png">

目录结构：
<img width="224" alt="image" src="https://user-images.githubusercontent.com/10812579/177749654-8ef85b17-53b8-461a-ac22-605be29fce5a.png">

感觉也没什么问题啊。一直报错；关闭重启了好几次也还是不行，有大佬帮忙看下是为啥吗

**Comment by zhenyuWang** [comment]
使用 subNVue 的页面是包含该配置的页面吗？
如果不是上述原因，请提供可复现 demo，谢谢！
