### ISSUE TITLE
wx上传图片后,由于小程序自动调用了onshow,导致绑定的表单内容会被刷新,致使用户输入丢失.

### ISSUE THREAD

**Issue by HSUCHING** [dcloudio/uni-app#369]
问题描述
在uni-app中，使用上传图片的功能会清空其他表单输入.

复现步骤
在一个表单中，例如上面是个textarea或者radio, 下面是一个上传图片的功能.比如你现在textarea里面输入内容，然后上传图片后，发现上面输入的内容被清空了，你不得不需要重新输入。

预期结果
如何能做到上传图片时不清空其他输入？

实际结果

系统信息:

发行平台: 微信小程序
操作系统 ios
uni-app版本
设备信息 iPhoneX
补充信息

**Comment by fxy060608** [comment]
onShow 为何会导致表单刷新？你自己在 onShow 里边重置数据了吗？
