### ISSUE TITLE
APP端 boundingClientRect exce后报错 TypeError: Cannot read property 'ref' of undefined

### ISSUE THREAD

**Issue by ouzexi** [dcloudio/uni-app#3690]
**问题描述**
代码为
`
uni.createSelectorQuery().in(this).select('xxx').boundingClientRect()exce()
`

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
H5端正常获取节点信息
![image](https://user-images.githubusercontent.com/65105426/178100096-8b9e5d09-a573-429c-879a-54c04a5d6484.png)
安卓端报错
![image](https://user-images.githubusercontent.com/65105426/178100109-3b345f41-157c-4527-8e2f-aff45551bba0.png)

**系统信息:**
 - 发行平台: APP
 - 操作系统 安卓
 - HBuilderX版本 3.4.18
 - uni-app版本
 - 设备信息 安卓

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by hanjiandu** [comment]
请问下怎么解决的，我现在在android上运行也报类似的错误，TypeError: Cannot read property 'nodeId' of undefined
在浏览器上运行是ok的

**Comment by xpxxy** [comment]
+1 这是怎么解决的？
