### ISSUE TITLE
uni-app的H5端如何不默认启用scoped?

### ISSUE THREAD

**Issue by bleakwind** [dcloudio/uni-app#3696]
**问题描述**
uni-app的H5端如何不默认启用scoped?

**复现步骤**
任何H5端的style标签没有加scoped标记都会默认启用scoped

**预期结果**
uni-app的H5端如何不默认启用scoped?

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 任何平台
 - HBuilderX版本 npm构建
 - uni-app版本  uni-app 3.0.0
 - 设备信息 H5端

**Comment by fxy060608** [comment]
暂未提供开关，为保证平台一致性，必须增加scoped来隔离各个页面，组件间的样式影响

**Comment by bleakwind** [comment]
scoped的问题非常好解决, 用scss每个组件顶层设置一个特有样式名就可以做到隔离. 
请问uni-app非要强制隔离如何修改uni-app的组件样式? 还是不允许修改uni-app的组件样式?
感觉做起来束手束脚, 现在不敢用uni-app的组件了, 因为号称抹平差异但是组件在小程序里一塌糊涂, 
我现在解决办法只能用view来自己组合模拟一些界面才能做到统一...

**Comment by fxy060608** [comment]
> scoped的问题非常好解决, 用scss每个组件顶层设置一个特有样式名就可以做到隔离. 请问uni-app非要强制隔离如何修改uni-app的组件样式? 还是不允许修改uni-app的组件样式? 感觉做起来束手束脚, 现在不敢用uni-app的组件了, 因为号称抹平差异但是组件在小程序里一塌糊涂, 我现在解决办法只能用view来自己组合模拟一些界面才能做到统一...

默认隔离不代表就不让改，你可以使用样式穿透解决，大量的uni-app三方UI组件库都做到了跨平台，不太明白你说的在小程序里一塌糊涂是什么意思

**Comment by bleakwind** [comment]
就是H5下用uni-app组件如grid等调试完毕, 编译到小程序下界面乱掉, 最后用view来模拟才做到抹平差异.

我刚刚测试发现style标签加入noscoped标记, 就不会隔离了, 编译后不会自动加入[data-xxx]标记进行隔离.
这是什么原理? 我不用穿透用这个方法可以吗? 穿透加标签太麻烦.
这个方式你们以后会堵上吗?

**Comment by fxy060608** [comment]
> 就是H5下用uni-app组件如grid等调试完毕, 编译到小程序下界面乱掉, 最后用view来模拟才做到抹平差异.
> 
> 我刚刚测试发现style标签加入noscoped标记, 就不会隔离了, 编译后不会自动加入[data-xxx]标记进行隔离. 这是什么原理? 我不用穿透用这个方法可以吗? 穿透加标签太麻烦. 这个方式你们以后会堵上吗?

1. uni-app内置组件没有grid，如果你指的是uni-ui里边的grid，可以到uni-ui仓库发issue，描述下你的问题，看看是不是应该由uni-ui来解决此问题
2. 理论上不会，noscoped可以绕过，是因为编译器只是简单的匹配style上有无scoped，有的话，就不自动补充了

**Comment by bleakwind** [comment]
1. 我说的是uni-ui里的grid, 原来uni-ui跟这里还是两个部分的啊? 明白了, uni-ui真心难用, 第三方如uview又不支持版本3, 唉...
2. 原来是这个原理, 哈哈, 我是不是社区第一个发现这个办法的? -_-!!!
谢谢你辛苦答疑.
close!
