### ISSUE TITLE
麻烦支持vite3

### ISSUE THREAD

**Issue by carlwangx** [dcloudio/uni-app#3699]
**新功能描述**
简洁描述你希望补充完善的增强功能

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by chioio** [comment]
什么傻逼issue

**Comment by zhetengbiji** [comment]
后续会支持

**Comment by social-uni** [comment]
> 什么傻逼issue

人家说的有问题吗？

**Comment by chioio** [comment]
> 

知道什么叫Feature Request，什么叫Issue么，当然，这框架也确实xx

**Comment by zhetengbiji** [comment]
已支持，如使用中遇到具体问题请详细反馈

**Comment by atzcl** [comment]
> 已支持，如使用中遇到具体问题请详细反馈

大佬，请问是 `3.0.0-alpha-3060120220907003` 这个版本吗？看 `peerDependencies ` 还是 `"vite": "2.9.14"` 呢https://cdn.jsdelivr.net/npm/@dcloudio/vite-plugin-uni@3.0.0-alpha-3060120220907003/package.json

**Comment by llk2yq** [comment]
> > 已支持，如使用中遇到具体问题请详细反馈
> 
> 大佬，请问是 `3.0.0-alpha-3060120220907003` 这个版本吗？看 `peerDependencies ` 还是 `"vite": "2.9.14"` 呢https://cdn.jsdelivr.net/npm/@dcloudio/vite-plugin-uni@3.0.0-alpha-3060120220907003/package.json

`3.0.0-alpha-3060120220907003` 这个版本确实可以了。

**Comment by atzcl** [comment]
> https://cdn.jsdelivr.net/npm/@dcloudio/vite-plugin-uni@3.0.0-alpha-3060120220907003/package.json

昨晚试用了，是可以的，这里是想指正下 `peerDependencies` 没有对应更新呢

**Comment by atzcl** [comment]
> > > 已支持，如使用中遇到具体问题请详细反馈
> > 
> > 
> > 大佬，请问是 `3.0.0-alpha-3060120220907003` 这个版本吗？看 `peerDependencies ` 还是 `"vite": "2.9.14"` 呢https://cdn.jsdelivr.net/npm/@dcloudio/vite-plugin-uni@3.0.0-alpha-3060120220907003/package.json
> 
> `3.0.0-alpha-3060120220907003` 这个版本确实可以了。

昨晚试用了，是可以的，这里是想指正下 peerDependencies 没有对应更新呢

**Comment by fxy060608** [comment]
> > > > 已支持，如使用中遇到具体问题请详细反馈
> > > 
> > > 
> > > 大佬，请问是 `3.0.0-alpha-3060120220907003` 这个版本吗？看 `peerDependencies ` 还是 `"vite": "2.9.14"` 呢https://cdn.jsdelivr.net/npm/@dcloudio/vite-plugin-uni@3.0.0-alpha-3060120220907003/package.json
> > 
> > 
> > `3.0.0-alpha-3060120220907003` 这个版本确实可以了。
> 
> 昨晚试用了，是可以的，这里是想指正下 peerDependencies 没有对应更新呢

目前内部还未正式更新支持vite3。未来1-2周会正式更新支持

**Comment by atzcl** [comment]
> 目前内部还未正式更新支持vite3。未来1-2周会正式更新支持

目前在微信小程序端有遇到个小问题，就是 `refs` 的获取，之前是在 `getCurrentInstance().ctx.$refs`，现在升级后变为了 `getCurrentInstance().refs` 了
