### ISSUE TITLE
h5+ app 不支持网络请求返回状态码201

### ISSUE THREAD

**Issue by IceDream1024** [dcloudio/uni-app#370]
Android 系统 h5+app request接口 GET 请求 服务器返回状态码201会出错 (h5 小程序不会出错)
{"data":"Attempt to invoke virtual method 'int java.io.InputStream.available()' on a null object reference","statusCode":201,"header":{"X-Android-Sent-Millis ":"1557200208996","Content-Type ":"application/json","X-Android-Selected-Protocol ":"http/1.0","Date ":"Tue, 07 May 2019 03:36:49 GMT","Content-Length ":"3857","Server ":"Werkzeug/0.15.2 Python/3.7.2","X-Android-Response-Source ":"NETWORK 201","Access-Control-Allow-Origin ":"*","X-Android-Received-Millis ":"1557200209506"},"errMsg":"request:ok"}

将服务器返回状态码改为200才能成功请求，忘官方大大尽快修复这个bug, 便于我这强迫症更好的去遵循http协议规范

**Comment by zhetengbiji** [comment]
HBuilderX 1.9.7 已修复此问题

**Comment by IceDream1024** [comment]
> HBuilderX 1.9.7 已修复此问题

辛苦

**Comment by parker1030** [comment]
2020年了，2.5.6中还有这个bug，不改了吗？
