### ISSUE TITLE
微信小程序由于热更新问题无法通过审核

### ISSUE THREAD

**Issue by chookg** [dcloudio/uni-app#3704]
你的小程序"XXX"，提审时间：2022-07-15 18:31，版本审核未通过。
1:小程序功能不符合规则:
(1):你好，当前提审的小程序包中可能含有页面文件采用内置 JavaScript 解释器（如eval5、estime、evil-eval等）的方式，动态执行JS代码、对小程序wxml代码进行热更新。出于安全考虑，建议你立即调整技术方案，去除相关内容，消除风险。[参考文档](https://developers.weixin.qq.com/community/minihome/doc/0000ae500e4fd0541f2ea33755b801)。可能存在解释器的文件路径如下：1.pages/common/vendor.js;
请根据上述原因对小程序进行修改，并重新提交代码审核。

事实上并未使用热更新功能

**Comment by CommanderXL** [comment]
这个具体是什么原因呢？

**Comment by CommanderXL** [comment]
@chookg 这个具体是什么原因呢？确实就是你们的 `pages/common/vendor.js` 代码里面包含了解释器相关的内容是吗？
