### ISSUE TITLE
我微信小程序使用 uni.navigateBack() 报错

### ISSUE THREAD

**Issue by cuixuhong123** [dcloudio/uni-app#3709]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
我微信小程序使用 uni.navigateBack() 报错
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看
![image](https://user-images.githubusercontent.com/50816484/179457837-b96fec3a-efad-4cda-88d9-6f6ccedc9605.png)

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
看错误应该是用了什么三方的路由库，可以找三方作者确认

**Comment by cuixuhong123** [comment]
我没转三方的路由库

**Comment by cuixuhong123** [comment]
我用 wx.navigateBack()是正常的

**Comment by fxy060608** [comment]
> 我没转三方的路由库

看自己的错误堆栈信息，里边的代码都不是uni-app框架的，排查自己用的三方库，自己点进去堆栈代码里，看一眼就知道是不是三方的了

**Comment by cuixuhong123** [comment]
我找到问题了    uni.navigateTo({
        url: `pagesU/sletetemplate/TemplateDetails?optons=${item.mCode}&show=true&indexs=${this.indexs}&Mname=${JSON.stringify(item.mName)}&qruan=${this.qruan}`,
      });问题这这里

**Comment by cuixuhong123** [comment]
这里怎么会影响下个页面的跳转搞不明白
