### ISSUE TITLE
canvas添加渐变色报错

### ISSUE THREAD

**Issue by zhe-he** [dcloudio/uni-app#371]
**问题描述**
在ctx.setStrokeStyle(gradient1); 此处报错，Uncaught (in promise) TypeError: t.toLowerCase is not a function。
改为 ctx.setStrokeStyle('rgba(255,255,255,0.3)')不报错
**复现步骤**
   ```var ctx = uni.createCanvasContext('mycanvas');
    var gradient1 = ctx.createCircularGradient(50, 50, 100);
    gradient1.addColorStop(0, 'red');
    gradient1.addColorStop(1, 'yellow');
    ctx.setStrokeStyle(gradient1);
    ctx.setLineWidth(2);
    ctx.stroke();
    ctx.closePath();```


**预期结果**
设置一个渐变的线条
**实际结果**
setStrokeStyle报错->Uncaught (in promise) TypeError: t.toLowerCase is not a function。

**Comment by dcloudhdx** [comment]
bug已确认，仅在H5平台有问题，下版修复

**Comment by hbcui1984** [comment]
HBuilderX 1.9.6 Alpha 版发布，已修复该问题。

Alpha版本说明及下载地址参考：[https://ask.dcloud.net.cn/article/35765](https://ask.dcloud.net.cn/article/35765)
