### ISSUE TITLE
onPageScroll 在自定义 composition api 中不生效

### ISSUE THREAD

**Issue by zhuscat** [dcloudio/uni-app#3712]
**问题描述**
比如我自己写了一个 composition api：

```js
function useFoo() {
  onPageScroll(() => {
    console.log('scroll')
  })
}
```

在页面中使用这个 composition api，不会触发 onPageScroll 的回调函数

但是如果我在页面中直接使用 `onPageScroll`，就能触发 useFoo 中的 onPageScroll

```js
// 这样能触发 useFoo 中的回调
useFoo()

// 引入 onPageScroll，给一个空函数
onPageScroll(() => {})
```

**系统信息:**
 - 发行平台: 微信小程序
 - uni-app版本：3.0.0-alpha-3050120220704001

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/3099#issuecomment-999315434
