### ISSUE TITLE
为什么uni app打包后的百度产物，在调用任何路由方法时都会各实例化Page、Component一次，别的平台例如微信只有实例化Component一次

### ISSUE THREAD

**Issue by cjinhuo** [dcloudio/uni-app#3715]
**问题描述**
uni app打包后的百度产物，在调用任何路由方法时都会各实例化Page、Component一次，别的平台只有实例化Component一次

**复现步骤**
正常打包uni app并在百度开发者工具中调试

[或者可以直接贴源代码]

**预期结果**

**实际结果**
![image](https://user-images.githubusercontent.com/22608658/179728105-eb6cd0b8-2c9e-40cf-9a6c-599a0a9cd66c.png)

**系统信息:**
百度基础库：3.500.9

**补充信息**
[可选]
* 是为了兼容component的onShow在onLoad之前运行？

**Comment by zhetengbiji** [comment]
是为了允许页面同时可以作为组件使用，所以页面也是用Component构造的。

**Comment by cjinhuo** [comment]
> 是为了允许页面同时可以作为组件使用，所以页面也是用Component构造的。

为啥微信、字节、支付宝就只初始化Component一次，按理说这才是正常的

**Comment by zhetengbiji** [comment]
> > 是为了允许页面同时可以作为组件使用，所以页面也是用Component构造的。
> 
> 为啥微信、字节、支付宝就只初始化Component一次，按理说这才是正常的

我目前猜测是由于百度平台方的底层实现方式和微信小程序不同导致的。

**Comment by cjinhuo** [comment]
> > > 是为了允许页面同时可以作为组件使用，所以页面也是用Component构造的。
> > 
> > 
> > 为啥微信、字节、支付宝就只初始化Component一次，按理说这才是正常的
> 
> 我目前猜测是由于百度平台方的底层实现方式和微信小程序不同导致的。

从uni app的角度来看，百度和微信的现在实现思路是一模一样的吗？忽略一些生命周期的兼容

**Comment by cjinhuo** [comment]
> 是的，基本差异就是 onInit：https://github.com/dcloudio/uni-app/blob/dev/src/platforms/mp-baidu/runtime/wrapper/component-parser.js

got it
