### ISSUE TITLE
button标签与@vue/runtime-dom中类型定义冲突

### ISSUE THREAD

**Issue by ringgoyao** [dcloudio/uni-app#3719]
**问题描述**

vscode里<button type='primary'></button>

type会被标红，点击调整到@vue/runtime-dom里了
![image](https://user-images.githubusercontent.com/5906943/179877492-d9498300-4bc8-4115-a536-76150e97e18b.png)

**Comment by wuchanghuan1995** [comment]
这是个老bug了,可以这样写试试
![image](https://user-images.githubusercontent.com/70843006/180345480-c445d3a0-536f-4413-9d9f-864eb3dbc9e2.png)

**Comment by ModyQyW** [comment]
可以试试 https://www.npmjs.com/package/uni-app-types？

**Comment by ringgoyao** [comment]
@ModyQyW   试了一下，没生效呢，用的volar+vue3+ts+vite 工程

**Comment by ModyQyW** [comment]
> @ModyQyW 试了一下，没生效呢，用的volar+vue3+ts+vite 工程

欢迎你到对应的仓库提交 issue，提供最小复现和 vscode 配置

**Comment by liwenfengg** [comment]
试了一下,我也没生效

**Comment by ModyQyW** [comment]
@ringgoyao @liwenfengg 能麻烦你们到这个仓库提交 ISSUE、提供最小复现和 vscode 配置吗？
