### ISSUE TITLE
给子组件传【id】关键字属性，props接收不到

### ISSUE THREAD

**Issue by Michael-py001** [dcloudio/uni-app#3722]
**问题描述**
给子组件传【id】关键字属性，props接收不到
**复现步骤**
```html
<UserInfo :id="userId"></UserInfo>
```
![image](https://user-images.githubusercontent.com/60598432/179945837-a58ce555-4f67-4b50-b7f2-2c03961156b2.png)
![image](https://user-images.githubusercontent.com/60598432/179945990-cc874f42-eb43-4929-a3bb-877a954965c8.png)

组件上的id没有渲染，输出id也为空，把我传的id给赋值到组件的id选择器上了，我想要的实际效果就是传个id过去，不是在html上整个id属性

改成其他关键字就正常了

**系统信息:**
版本：vue3
- 发行平台: 微信小程序
- 操作系统 windows
- HBuilderX版本 3.5.1.20220707-alpha

**Comment by fxy060608** [comment]
建议不要使用id作为prop，在小程序平台，id是保留属性

**Comment by Michael-py001** [comment]
好的

**Comment by Michael-py001** [comment]
看样子还真是个Bug，我记得vue2的项目是用id传没问题的😂

**Comment by BombCowpat** [comment]
vue2语法使用id作为props也拿不到值
