### ISSUE TITLE
support webpack5

### ISSUE THREAD

**Issue by VisonM** [dcloudio/uni-app#3723]
#### Are there any plans to support webpack5?

it seems uni is compiled via @vue/services which the new version already supports webpack 5.but simply updating the @vue/services version doesn't seem to work as there are still some uni custom plugins, is there any other way ?

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/3617

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/2945

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/2793

**Comment by ModyQyW** [comment]
https://github.com/dcloudio/uni-app/issues/3001

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/3342

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/2804

**Comment by zhetengbiji** [comment]
使用 vue-cli 创建 alpha 分支已支持，使用中发现问题请反馈。
```
npm install -g @vue/cli@5
vue create -p dcloudio/uni-preset-vue#alpha test
```
已知问题：
* 遗留部分警告未处理。
* Win 平台 dev 模式编译结束（小程序、App）会结束进程。

**Comment by VisonM** [comment]
> 使用 vue-cli 创建 alpha 分支已支持，使用中发现问题请反馈。
> 
> ```
> npm install -g @vue/cli@5
> vue create -p dcloudio/uni-preset-vue#alpha test
> ```
> 
> 已知问题：
> 
> * 遗留部分警告未处理。
> * Win 平台 dev 模式编译结束（小程序、App）会结束进程。

Awesome work! 近期我将基于此进行升级工作。

btw，为什么在webpack4的模式下微信小程序模式打包基本没有cache的构建缓存，在项目体量上来之后，目前一次完整的watch mode 启动（1600多个模块），需要至少30-40s的时间。我看到了类似如下的逻辑

![image](https://user-images.githubusercontent.com/40595135/184097245-68d6b516-02ed-4668-801e-a1dfefad877c.png)

![image](https://user-images.githubusercontent.com/40595135/184097371-ebc48e05-ef22-4a36-9afe-4536b1b41d69.png)

我是否错过了什么说明文档，是否可以配置什么去开启cache优化呢

**Comment by zhetengbiji** [comment]
> > 使用 vue-cli 创建 alpha 分支已支持，使用中发现问题请反馈。
> > ```
> > npm install -g @vue/cli@5
> > vue create -p dcloudio/uni-preset-vue#alpha test
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 已知问题：
> > 
> > * 遗留部分警告未处理。
> > * Win 平台 dev 模式编译结束（小程序、App）会结束进程。
> 
> Awesome work! 近期我将基于此进行升级工作。
> 
> btw，为什么在webpack4的模式下微信小程序模式打包基本没有cache的构建缓存，在项目体量上来之后，目前一次完整的watch mode 启动（1600多个模块），需要至少30-40s的时间。我看到了类似如下的逻辑
> 
> ![image](https://user-images.githubusercontent.com/40595135/184097245-68d6b516-02ed-4668-801e-a1dfefad877c.png)
> 
> ![image](https://user-images.githubusercontent.com/40595135/184097371-ebc48e05-ef22-4a36-9afe-4536b1b41d69.png)
> 
> 我是否错过了什么说明文档，是否可以配置什么去开启cache优化呢

部分情况下（如使用条件编译或编译到多个平台）缓存会错乱，所以禁用了 cache。另外在 webpack5 内置了 cache 功能，但是框架近期更新并未处理和验证相关逻辑，使用时需要注意一下，后续我会单独验证和处理一下这部分。

**Comment by ModyQyW** [comment]
文档是否可以更新一下呢？

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/31850793/185015623-46abb546-2186-4522-b9e0-6d75c5c11a65.png">

**Comment by VisonM** [comment]
> 文档是否可以更新一下呢？
> 
> 
> 
> <img width="1920" alt="image" src="https://user-images.githubusercontent.com/31850793/185015623-46abb546-2186-4522-b9e0-6d75c5c11a65.png">
> 
> 

我认为目前还没有到能正式使用的阶段，@vue/cli的相关uni插件也要同步更新，但是它仅处于alpha阶段，需要大量的验证和测试，
我初步进行了使用，可惜迁移并不太顺利。

**Comment by VisonM** [comment]
btw，development开启了UNI_USING_CACHE以后，再次启动编织从26s，减少到了7s，还在进一步观察是否有缓存所带来的相关问题。它确实会提供值得一试的优化效果

**Comment by ModyQyW** [comment]
> 

我也认为没到能正式使用的阶段，但希望通过写进文档吸引更多的人参与测试。

**Comment by zhetengbiji** [comment]
依赖更新到 2.0.1-alpha-35420220816001

* 默认关闭了 babel-loader 的 cache（调整为和 webpack4 一致）。
* 修复了导致小程序端组件编译失败的一些问题。

**Comment by zhetengbiji** [comment]
> > 
> 
> 我也认为没到能正式使用的阶段，但希望通过写进文档吸引更多的人参与测试。

好的，文档将增加一行相关说明

**Comment by zhaotoday** [comment]
大概什么时候可以正式使用？

**Comment by lvzhenbo** [comment]
希望能够尽快完成支持webpack5，webpack5和新tls版本node18不兼容

**Comment by zhetengbiji** [comment]
> 大概什么时候可以正式使用？

再观察一段时间无开发者报告相关问题

**Comment by lvzhenbo** [comment]
postcss出现一些弃用警告
```
trim: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration​
​remove-scoped: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration​
​add-id: postcss.plugin was deprecated. Migration guide:
https://evilmartians.com/chronicles/postcss-8-plugin-migration​
```

**Comment by zhetengbiji** [comment]
> 希望能够尽快完成支持webpack5，webpack4和新tls版本node18不兼容

目前已处理完已知的兼容问题

**Comment by zhaotoday** [comment]
@zhetengbiji 还有多久可以正式使用？

**Comment by zhetengbiji** [comment]
> @zhetengbiji 还有多久可以正式使用？

从目前的反馈看，已经可以正式使用，将会随着下个正式版的发布调整相关文档。

**Comment by zhaotoday** [comment]
> > @zhetengbiji 还有多久可以正式使用？
> 
> 从目前的反馈看，已经可以正式使用，将会随着下个正式版的发布调整相关文档。

大概几号可以正式使用。

**Comment by zhetengbiji** [comment]
> > > @zhetengbiji 还有多久可以正式使用？
> > 
> > 
> > 从目前的反馈看，已经可以正式使用，将会随着下个正式版的发布调整相关文档。
> 
> 大概几号可以正式使用。

从目前的反馈看，上个月已经可以正式使用。但下个正式版的发布才会调整相关文档。

**Comment by jiekechens** [comment]
![image](https://user-images.githubusercontent.com/100945843/218481482-b7be2705-ab25-40f1-82a0-6b5b1cd75947.png)

**Comment by hedonghui** [comment]
webpack5的支持已经更新到正式版本了吗？我看官网上还没更新文档，求问
