### ISSUE TITLE
input输入框在搜狗输入法下，不能触发input事件

### ISSUE THREAD

**Issue by TStoneLee** [dcloudio/uni-app#3728]
**问题描述**
在安卓系统下（H5），搜狗输入法，input组件，先输入中文，然后再切换到英文模式，输入英文，英文会出现在键盘的上方（此时不要手动选择）（但是输入框是有对应的内容的）此时是不会触发input事件的，如果在手写模式下，也会出现此问题
**复现步骤**
如上描述
**预期结果**
键盘输入时，不选择键盘上面的内容，也要触发input事件
**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: H5平台
 - 操作系统: Android
 -  - uni-app版本 uni-app v3.1.22
uni-app cli v2.0.0-31920210709003

Environment Info:

  System:
    OS: macOS 12.4
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 15.14.0 - ~/.nvm/versions/node/v15.14.0/bin/node
    Yarn: 1.22.19 - ~/.yarn/bin/yarn
    npm: 7.7.6 - ~/.nvm/versions/node/v15.14.0/bin/npm
  Browsers:
    Chrome: 103.0.5060.134
    Firefox: Not Found
    Safari: 15.5
  npmPackages:
    @dcloudio/types: * => 2.3.3
    @dcloudio/uni-app-plus: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-automator: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-cli-shared: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-h5: ^2.0.0-alpha-31920210715002 => 2.0.0-alpha-31920210715002
    @dcloudio/uni-helper-json: * => 1.0.13
    @dcloudio/uni-i18n: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-migration: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-360: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-alipay: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-baidu: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-kuaishou: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-qq: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-toutiao: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-vue: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-mp-weixin: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-quickapp-native: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-quickapp-webview: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-stat: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-template-compiler: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/uni-ui: ^1.3.7 => 1.3.7
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-31920210709003 => 2.0.0-31920210709003
    @hap-toolkit/dsl-vue:  0.6.13
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.0.6
    @vue/babel-plugin-transform-vue-jsx:  1.2.1
    @vue/babel-preset-app:  4.5.13
    @vue/babel-preset-jsx:  1.2.4
    @vue/babel-sugar-composition-api-inject-h:  1.2.1
    @vue/babel-sugar-composition-api-render-instance:  1.2.4
    @vue/babel-sugar-functional-vue:  1.2.2
    @vue/babel-sugar-inject-h:  1.2.2
    @vue/babel-sugar-v-model:  1.2.3
    @vue/babel-sugar-v-on:  1.2.3
    @vue/cli-overlay:  4.5.13
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.13
    @vue/cli-plugin-router:  4.5.13
    @vue/cli-plugin-vuex:  4.5.13
    @vue/cli-service: ~4.5.0 => 4.5.13
    @vue/cli-shared-utils:  4.5.13
    @vue/component-compiler-utils:  3.2.2 (3.2.2)
    @vue/eslint-config-prettier: ^7.0.0 => 7.0.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/shared: ^3.0.0 => 3.1.5
    @vue/web-component-wrapper:  1.3.0
    eslint-plugin-vue: ^7.20.0 => 7.20.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.11 => 2.6.14
    vue-eslint-parser:  7.11.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.9.7 (16.3.1, 15.9.7)
    vue-router:  3.0.1
    vue-style-loader:  4.1.3 (4.1.3)
    vue-template-compiler: ^2.6.11 => 2.6.14 (2.6.14)
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.2.0 => 3.6.2

**Comment by Otto-J** [comment]
输入过程没有上屏时候，需要监听键盘的合成操作
