### ISSUE TITLE
怎么在页面旋转90°之后正确的触发鼠标事件

### ISSUE THREAD

**Issue by c1105590204** [dcloudio/uni-app#3731]
**问题描述**
我使用uni-app开发公众号页面，其中一个页面必须横屏显示，但是没有找到在公众号里面设置横屏的方式，于是通过页面旋转90°（transform: rotate(90deg)）的方式来实现的，但是由于页面中使用了控件picker-view,在滚动列表的时候出现了滚动方向和手势方向的x，y相反的问题，比如我横向拿手机，要竖向滚动的时候，手指必须横向滑动才行，请问有解决手指方向的方法吗？或者其他方式实现这个需求？

**复现步骤**
[复现问题的步骤]
1.  在微信浏览器打开横屏页面
2. picker-view,然后滑动列表
3. 横向滑动才能滚动，竖向滑动无法滚动

[或者可以直接贴源代码]

**预期结果**
滚动方向和手指滑动方向一致

**实际结果**
滚动方向和手指滑动方向相反

**系统信息:**
 - 发行平台: [微信公众号]
 - HBuilderX版本 [HBuilderX 3.4.18]

**补充信息**
[可选]
因为使用了rotate旋转屏幕导致手指识别和屏幕方向相反

**Comment by zhetengbiji** [comment]
目前组件不能判断自身的旋转，故无法通用的进行适配。开发者需要自己实现一个picker来进行适配或者改用提示用户自行解锁设备方向并旋转屏幕。
