### ISSUE TITLE
使用 TS 时 @dcloudio/uni-app 里没有 onLoad 声明，请更新

### ISSUE THREAD

**Issue by xhlsrj** [dcloudio/uni-app#3734]
**新功能描述**
希望补充类型声明

**现状及问题**
TS 检查报错

**尝试方案**
使用 @ts-ignore 来忽略检查

**Comment by zhetengbiji** [comment]
使用的版本多少？说的是Page的吗？

**Comment by xhlsrj** [comment]
> 使用的版本多少？说的是Page的吗？

@dcloudio/uni-app 使用的版本是 3.0.0-alpha-3000020210521001
是的，在 page 里
```ts
<script setup lang="ts">
// @ts-ignore
import { onLoad } from '@dcloudio/uni-app';
```

**Comment by fxy060608** [comment]
> > 使用的版本多少？说的是Page的吗？
> 
> @dcloudio/uni-app 使用的版本是 3.0.0-alpha-3000020210521001 是的，在 page 里
> 
> ```ts
> <script setup lang="ts">
> // @ts-ignore
> import { onLoad } from '@dcloudio/uni-app';
> ```

升级至最新cli
