### ISSUE TITLE
setClipboardData 复制失败后影响了 showModal 后续使用的结构

### ISSUE THREAD

**Issue by chasonma** [dcloudio/uni-app#3739]
**问题描述**
setClipboardData 复制失败后影响了 showModal 后续使用的结构。

**复现步骤**
先调用 uni.setClipboardData 接口，提示复制失败后，后续其他事件上调用 uni.showModal 接口。

**预期结果**
样式结构正常，内容不应该出现在 textarea 文本框上。

**系统信息:**
 - 发行平台: H5
 - uni-app版本: 3.0.0-alpha-3050020220623004

**Comment by chasonma** [comment]
后续其他事件上调用需手动指定 editable: false 才能解决该问题。
```
uni.showModal({
    editable: false
})
```

**Comment by StrivingRabbit** [comment]
vue几？3 吗？

**Comment by chasonma** [comment]
> vue几？3 吗？

对是，vue3

**Comment by StrivingRabbit** [comment]
稍后看看

**Comment by chasonma** [comment]
> 稍后看看

uni.showModal 嵌套调用也存在问题，需要延迟调用。
