### ISSUE TITLE
为什么要强制设置productionSourcemap为false?

### ISSUE THREAD

**Issue by jinceon** [dcloudio/uni-app#3740]
**新功能描述**
为什么要强制设为false?  
有很多前端排错平台，比如sentry，fundebug 等都支持通过sourcemap还原错误堆栈到原始代码。  
强制false非常不方便。  
能说下你们是出于什么考虑，非要设置为false吗？

**现状及问题**
![image](https://user-images.githubusercontent.com/1641265/181160042-3a24c08d-6e06-47eb-a7d6-531fcb8ab32f.png)

**Comment by fxy060608** [comment]
新版本已支持生成sourcemap

https://uniapp.dcloud.io/uni-stat-v2.html#sourcemap-parse-error
