### ISSUE TITLE
微信小程序生命周期钩子 onInit 无效

### ISSUE THREAD

**Issue by XuanyiJiang** [dcloudio/uni-app#3745]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
使用 HBuilder X 3.4.18 创建一个示例小程序工程
在任一页面中增加 onInit 钩子，并在其中打印信息输出
运行时并未打印出 onInit 中的 log

[或者可以直接贴源代码]

**预期结果**
onInit可以正常生效

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 微信小程序开发者工具最新版
 - 操作系统 win10
 - HBuilderX 3.4.18
 - uni-app版本
 - 设备信息

**Comment by fxy060608** [comment]
onInit是百度小程序特有
