### ISSUE TITLE
vue2版本的能不能支持下unplugin-vue2-script-setup

### ISSUE THREAD

**Issue by weiminghaoo** [dcloudio/uni-app#3748]
**新功能描述**
unplugin-vue2-script-setup是一个可以让vue2支持setup的插件，但是目前有个问题，
<template>
  <view class="content">
    <Msg :msg="title"></Msg>
  </view>
</template>
<script lang="ts" setup>
import Msg from './msg.vue'
const title = $ref('Hello')
</script>

这种写法不会在当前页面的.json中引用当前组件，有没有什么解决方案

<img width="357" alt="image" src="https://user-images.githubusercontent.com/29938792/181903889-ed21d5fa-383e-4f1e-ba40-d8358cff0be2.png">
<img width="341" alt="image" src="https://user-images.githubusercontent.com/29938792/181903914-e642b716-6cde-4697-b278-8b95d0609410.png">

**Comment by xiaoxiangmoe** [comment]
@fxy060608 如果 uniapp 不准备支持 vue 2.7 的话，我们得查查这个问题

**Comment by zhetengbiji** [comment]
已支持，更新 uni 相关依赖即可

**Comment by weiminghaoo** [comment]
可用👍
