### ISSUE TITLE
mpvue项目转移过来 css 单位px怎么统一换upx？

### ISSUE THREAD

**Issue by Mixlong** [dcloudio/uni-app#375]

**Comment by stackjie** [comment]
安装px转换upx的插件 

```
npm i postcss-px2upx -D
```

安装完后配置一下 `postcss.config.js`
```
const pkg = require('./package.json')
module.exports = {
  plugins: [
    require('postcss-import'),
    require('autoprefixer')({
      browsers: pkg.browserslist
    }),
    require('postcss-px2upx')({
      baseDpr: 1,
      upxUnit: 0.5
    }),
    require('@dcloudio/vue-cli-plugin-uni/packages/postcss')
  ]
}
```

**Comment by bacy** [comment]
> 安装这个px转换upx的插件就可以继续在项目中使用px单位，编译时会自动转换upx
> 
> ```
> npm i postcss-px2upx -D
> ```
> 
> 安装完后配置一下 `postcss.config.js`
> 
> ```
> const pkg = require('./package.json')
> module.exports = {
>   plugins: [
>     require('postcss-import'),
>     require('autoprefixer')({
>       browsers: pkg.browserslist
>     }),
>     require('postcss-px2upx')({
>       baseDpr: 1,
>       upxUnit: 0.5
>     }),
>     require('@dcloudio/vue-cli-plugin-uni/packages/postcss')
>   ]
> }
> ```

我去，我都手动改成upx，才发现你这条回复，快要崩溃了

**Comment by aiplat** [comment]
可以用em

**Comment by zhangxiongxin** [comment]
> 安装这个px转换upx的插件就可以继续在项目中使用px单位，编译时会自动转换upx
> 
> ```
> npm i postcss-px2upx -D
> ```
> 
> 安装完后配置一下 `postcss.config.js`
> 
> ```
> const pkg = require('./package.json')
> module.exports = {
>   plugins: [
>     require('postcss-import'),
>     require('autoprefixer')({
>       browsers: pkg.browserslist
>     }),
>     require('postcss-px2upx')({
>       baseDpr: 1,
>       upxUnit: 0.5
>     }),
>     require('@dcloudio/vue-cli-plugin-uni/packages/postcss')
>   ]
> }
> ```

你好，按照你给的做法配置了，但是没有自动转换呢，原项目是mpvue写的，单位用的px，是还需要配置hbuilderX吗?

**Comment by bacy** [comment]
> > 安装这个px转换upx的插件就可以继续在项目中使用px单位，编译时会自动转换upx
> > ```
> > npm i postcss-px2upx -D
> > ```
> > 
> > 
> > 安装完后配置一下 `postcss.config.js`
> > ```
> > const pkg = require('./package.json')
> > module.exports = {
> >   plugins: [
> >     require('postcss-import'),
> >     require('autoprefixer')({
> >       browsers: pkg.browserslist
> >     }),
> >     require('postcss-px2upx')({
> >       baseDpr: 1,
> >       upxUnit: 0.5
> >     }),
> >     require('@dcloudio/vue-cli-plugin-uni/packages/postcss')
> >   ]
> > }
> > ```
> 
> 你好，按照你给的做法配置了，但是没有自动转换呢，原项目是mpvue写的，单位用的px，是还需要配置hbuilderX吗?

这个应该得用vue-cli初始化项目才可以。我开始也是用hbuildx搞的，后来还是不太习惯这个编辑器，重新用vue-cli初始化，然后把src代码等等拷贝过来

**Comment by hopkinson** [comment]
请问如果是hbuilder创建的项目，请问现在可以处理这个问题嘛？或者有什么解决方案

**Comment by zhoufanglu** [comment]
[建议使用rpx](https://ask.dcloud.net.cn/article/36130?tdsourcetag=s_pctim_aiomsg)
希望这个可以帮到你
