### ISSUE TITLE
swiper disable-touch属性 在 vue3 版本中 小程序端无效，H5正常

### ISSUE THREAD

**Issue by dang0705** [dcloudio/uni-app#3753]
**问题描述**
swiper disable-touch属性 在 vue3 版本的小程序端无效

**复现步骤**
小程序不能 禁止手动滑动

`<swiper disable-touch :current-item-id="item_id">
 <swiper-item/>
...
</swiper>`

**预期结果**
小程序和H5端表现一致，可以禁用滑动

**实际结果**
小程序和H5端表现不一致，无法禁用滑动

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 ^3.0.0-alpha-3050320220727002
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
微信小程序平台并未支持此属性，具体请查阅文档
