### ISSUE TITLE
UC、QQ浏览器，切换UA后uni.navigateBack()无法返回

### ISSUE THREAD

**Issue by codeflycpn** [dcloudio/uni-app#3756]
**问题描述**
uniapp-h5端， **随意新建一个项目都会有这个问题，使用uc、qq浏览器打开后，切换ua，然后uni.navigateBack({}); 会成功触发但是不会跳转，多试几次就会停留在跳转页    **

**复现步骤**
[复现问题的步骤]
1.  用qq、uc浏览器访问项目
2. 通过qq浏览器切换ua为 安卓、电脑、ios都行
3. 点击跳转、在返回， 只要来回几次就无法再返回了， 有时候第一次就不能返回，有时候两三次

**系统信息:**
项目最新依赖，cli、HBx（都是最新）
uc、qq浏览器最新
**补充信息**
[可选]
未能完全适配qq、uc浏览器

**Comment by codeflycpn** [comment]
已经找出问题

**Comment by varnbu** [comment]
请问你是怎么解决的这个问题
