### ISSUE TITLE
uni.createVideoContext('item', this).play()无效

### ISSUE THREAD

**Issue by blesslz** [dcloudio/uni-app#3757]
**问题描述**
百度小程序中uni.createVideoContext('item', this).play();播放/暂停视频无效

**复现步骤**
[源代码]
<video id="item" ref="item" src="xx.mp4" enable-danmu danmu-btn controls />;
uni.createVideoContext('item', this).play();

**预期结果**

**实际结果**

**系统信息:**
 - 发行平台: 百度小程序
 - 操作系统 Android
 - HBuilderX版本： 3.4.15.20220610
 - 设备信息 ：百度开发者工具

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhenyuWang** [comment]
vue2 已复现该问题，可通过不传入第二个参数（this) 回避该问题，vue3 没有问题，感谢反馈

**Comment by zhenyuWang** [comment]
HBuilderX 3.6.7 已抹平写法差异，支持传入第二个参数
