### ISSUE TITLE
uni-file-picker组件 报错 TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by shaoweb** [dcloudio/uni-app#3758]
**问题描述**
直接下载官网模板，微信小程序启动报错

**复现步骤**
新建项目，选择 Hello uni-app模板

**预期结果**
出现选中的图片上传的按钮

**实际结果**
<img width="680" alt="image" src="https://user-images.githubusercontent.com/25735710/182312369-8fb7a3b3-4d67-4e24-86dd-d8323bdb55a4.png">

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 Android 7.0
 - HBuilderX版本
 - # HBuilder X - Release Notes
======================================
## 3.5.3.20220729
 - uni-app版本 
 -  通过 HBuilderX 创建

**Comment by heachou** [comment]
同样问题

**Comment by fusanqiang** [comment]
同样的问题

**Comment by MemoryFate** [comment]
web端同样的问题

**Comment by moveStar** [comment]
Mac上周出现同样问题   将hbuilderX版本退回3.4.7恢复正常

**Comment by Wangyaqi** [comment]
此问题会在下次发版时修复，感谢反馈

**Comment by Wangyaqi** [comment]
更新HBuilderX 到3.5.5，此问题已修复。cli相应的版本也已修复

**Comment by fusanqiang** [comment]
没有用 HBuilderX 怎么修复？

**Comment by Wangyaqi** [comment]
`npx @dcloudio/uvm`
