### ISSUE TITLE
JS文件中的条件编译报错

### ISSUE THREAD

**Issue by Michael-py001** [dcloudio/uni-app#3759]
**问题描述**
我`.JS`文件中的的代码使用条件编译会报`[plugin:uni:pre] Unexpected identifier`的错误，条件编译必须要在.vue文件里面使用？

**复现步骤**
最小复现demo：
```js
//a.js
export function getData () {
  uni.getSystemInfo({
     // #ifdef MP-WEIXIN 
       xxx代码
    // #endif
  })
}
```
```js
//b.vue
import {getData} from './a.js'
```
```
出现以下报错
[plugin:uni:pre] Unexpected identifier
```

**预期结果**
正确引入

**实际结果**
报错

**系统信息:**
  vue3
 - 发行平台: 微信小程序
 - HBuilderX版本3.5.3.20220727-alpha

**Comment by fxy060608** [comment]
发测试工程，另外建议不要这么使用条件编译，条件编译里边应该包含了一段有效的js代码，而不是把一段有效的js代码，用各种条件编译隔离开

**Comment by Michael-py001** [comment]
不知道是啥原因，刚刚更新了3.5.4.20220805 就正常了
