### ISSUE TITLE
【咨询】在支付宝小程序环境中要怎么获取软键盘的高度？

### ISSUE THREAD

**Issue by yanquanfahei** [dcloudio/uni-app#3766]
**问题描述**
希望能在支付宝小程序环境中获取到键盘高度，在 android 机上 input 唤起软键盘光标与键盘之间没有间距。

**尝试方案**
支付宝小程序文档中提供 [events](https://opendocs.alipay.com/mini/framework/page-detail#events) 的事件处理对象上有个onKeyboardHeight 监听函数来获取到高度。但是在uni-app的项目中尝试了以下写法都无法触发。请问下现在是不支持嘛，还是我的写法有误？
```vue
export default {
  name: 'Page',
  events: {
    onKeyboardHeight() {
      console.log(e, 'onKeyboardHeight');
    }
  }
  // or
  onKeyboardHeight() {
    console.log(e, 'onKeyboardHeight');
  }
}
```

**Comment by zhenyuWang** [comment]
目前暂不支持支付宝小程序 events 事件函数，预计 3.6.7-alpha 支持

**Comment by yanquanfahei** [comment]
好的，感谢回复

**Comment by zhenyuWang** [comment]
HBuilderX 3.6.7 已支持
