### ISSUE TITLE
npm导入uni-ui组件无法修改样式？

### ISSUE THREAD

**Issue by Mixlong** [dcloudio/uni-app#377]

**Comment by mehaotian** [comment]
可以修改 ，使用 /deep/ 覆盖样式 ，在 style 标签上加上 scoped
例:

···html
<template>
	<view class="wrap">
		<uni-badge text="2" type="primary" />
	</view>
</template>
<script>
	import {
		uniBadge
	} from '@dcloudio/uni-ui'
	export default {
		components: {
			uniBadge
		},
	}
</script>
<style lang="scss" scoped>
	// uni-ui 样式覆盖
	.wrap /deep/ .uni-badge--primary {
		background-color: blue;
	}
</style>
<style>
	/* 自己的样式 */
</style>

···
