### ISSUE TITLE
使用 npx @dcloudio/uvm 升级项目，导致ui组件不能使用

### ISSUE THREAD

**Issue by 13799433448** [dcloudio/uni-app#3770]
**问题描述**
使用 npx @dcloudio/uvm 升级项目，导致ui组件不能使用

**复现步骤**
我在项目中使用 npx @dcloudio/uvm 升级项目
![image](https://user-images.githubusercontent.com/52238305/182990725-e6cb14b1-0c70-474e-8ab7-4c0cc3d7f430.png)
左侧是升级前版本，右侧是升级后的

**预期结果**
可以正常使用ui组件

**实际结果**
![image](https://user-images.githubusercontent.com/52238305/182991048-10093b7b-b709-4eb0-87a7-36347a98554b.png)

**系统信息:**
 - 发行平台: 微信小程序

**Comment by zhetengbiji** [comment]
将“不能使用”详细描述一下

**Comment by 13799433448** [comment]
> 将“不能使用”详细描述一下

是我描述有误：应该ui组件失效：
这是我升级之后的效果
![image](https://user-images.githubusercontent.com/52238305/182994619-ee2045d7-f952-4cf6-a0b0-c068a7c08060.png)
升级前的效果是：
这里使用的是 uni-ui的 group 和 grid、icons 组件
![image](https://user-images.githubusercontent.com/52238305/182994777-3fab70ad-80da-4bcc-a059-000068e5b65e.png)

**Comment by zhetengbiji** [comment]
是否存在报错？
另外审查元素，能否看出线索

**Comment by 13799433448** [comment]
> 是否存在报错？ 另外审查元素，能否看出线索

编辑器上没有报错
![image](https://user-images.githubusercontent.com/52238305/183008885-00d1b78c-f9b9-45ac-a48c-c3ef8e6a8d1c.png)

元素审查 发现样式全部没有了

这是我在 vite.config.ts的配置 是否是这里缺少了上面
![image](https://user-images.githubusercontent.com/52238305/183008940-b523fd89-0314-49ea-81ae-83b232d58696.png)

我看官方文档
![image](https://user-images.githubusercontent.com/52238305/183008968-a3c30b20-e333-46ba-93e9-28d8a2455e84.png)
但是对 vue3的配置倒没有仔细描述

**Comment by jozhi** [comment]
同样碰到这个问题，项目是vue3项目，升级过了之后不光ui组件失效，现在 npm run dev:h5之后，chrome控制台报错 
`pinia.mjs:6 Uncaught SyntaxError: The requested module '/webapp/node_modules/pinia/node_modules/vue-demi/lib/index.mjs?v=dffd6942' does not provide an export named 'hasInjectionContext' (at pinia.mjs:6:10)`

这个怎么回退下。

**Comment by zhetengbiji** [comment]
> 同样碰到这个问题，项目是vue3项目，升级过了之后不光ui组件失效，现在 npm run dev:h5之后，chrome控制台报错 `pinia.mjs:6 Uncaught SyntaxError: The requested module '/webapp/node_modules/pinia/node_modules/vue-demi/lib/index.mjs?v=dffd6942' does not provide an export named 'hasInjectionContext' (at pinia.mjs:6:10)`
> 
> 这个怎么回退下。

https://github.com/dcloudio/uni-app/issues/4671
