### ISSUE TITLE
vue3+vite 打包h5 设置相对路径不生效

### ISSUE THREAD

**Issue by xcplovelhq** [dcloudio/uni-app#3784]
**问题描述**
vue3+vite 打包h5 设置相对路径不生效
**复现步骤**
![image](https://user-images.githubusercontent.com/20986739/184274930-a8e09179-26ac-4902-a4c0-d295d5c72853.png)

![image](https://user-images.githubusercontent.com/20986739/184274989-62ad9917-7c46-4447-b946-2d69065285c7.png)

**系统信息:**
cli打包 版本3.0.0-alpha-3050420220804004

**补充信息**

**Comment by zhetengbiji** [comment]
请勿双击打开html，请使用本地http服务预览。

**Comment by xcplovelhq** [comment]
> 请勿双击打开html，请使用本地http服务预览。

我这个就是要直接打开，vue2 是可生效的

**Comment by zhetengbiji** [comment]
> > 请勿双击打开html，请使用本地http服务预览。
> 
> 我这个就是要直接打开，vue2 是可生效的

不支持，目前vue3默认使用的es module,受浏览器安全策略限制

**Comment by xcplovelhq** [comment]
> Reference in

好的，谢谢

**Comment by xcplovelhq** [comment]
> > > 请勿双击打开html，请使用本地http服务预览。
> > 
> > 
> > 我这个就是要直接打开，vue2 是可生效的
> 
> 不支持，目前vue3默认使用的es module,受浏览器安全策略限制

好的，谢谢
