### ISSUE TITLE
v-for 指令问题

### ISSUE THREAD

**Issue by HVE-LK** [dcloudio/uni-app#379]
**问题描述**
`<scroll-view :scroll-x="true" class="selectNav" :scroll-into-view="breadCrumbsIndex" :scroll-with-animation="true"><view :id="item.positionId" v-for="(item,index) in breadNavigate" :key="item.id" class="bread-crumbs-item" @tap="beforeStep(item.positionId,item.id,index)"><text :class="{'nav-active':index!==breadNavigateLength-1}">{{item.name}}</text><text class="zan-icon zan-icon-arrow nav-indicator" v-if="index!==breadNavigateLength-1"></text></view></scroll-view>`

1.在循环体中直接只用breadNavigate.length时，当breadNavigate数组长度改变时，
:class 绑定的值没有动态更新，导致class 样式不准确，不知道这个是设计如此还是bug，:disabled 也存在同样的问题，无法直接使用数组的length属性（长度更新指令或者属性绑定检测不到）。

```
<view class="organization-item" v-for="(item,index) in tissueTypes==='organizationalStructure'?originMetadata:areaMetadata"  :key="item.id"><view class="rightModule" @tap='selectOrganization(index)'>
						<!-- disabled='{{item.disabled}}' -->
						<radio class="radio" v-if="btnConfig.showOrganizationRadio" :checked="item.selected"></radio>
						<view class="text">{{item.name}}</view>
					</view>
					<view class='lower-level' @tap="nextStep(index,item)" v-if="btnConfig.showLowerLevelBtn">
						<text>下级</text>
					</view>
				</view>
```
2.在v-for 指令内部 事件绑定后无法直接传参item，会报如下错误：Bad attr `data-event-opts` with message: unexpected token `organizationalStructure`.。
3.在input 组件上 直接使用v-model 最终获取到的值始终为上一次的值。
4.在部分手机上（android） ，上传图片时会出现整个webview 黑屏/白屏，主要表现在android6.0以及ios10以下。
5.input 组件在失去焦点的时候在position布局下（属于上下层关系），input 组件在失去焦点的时候又会自动获取焦点。

**复现步骤**
见上源代码

**预期结果**
1.v-for指令内部 事件绑定可以传递item。
2.数组的length属性在动态改变的时候，相关的指令以及属性能够检查到并至执行相关动作。
3.文件/图片上传 黑屏问题能够得到修复。
4.v-model 能够获取到最新值。

**实际结果**

**系统信息:**
5+SDK版本：1.9.9.62327
uni版本：1.9.4
系统平台：Android 

**补充信息**
[可选]

**Comment by HVE-LK** [comment]
uni-app 基于目前市面上手机等性能问题，前景还是可以的，但是5+sdk,uni-app 还是太成熟，uni-app问题还是比较多，5+sdk 在性能上还待提高，编译器还待优化。

**Comment by zhetengbiji** [comment]
HBuilderX 2.8.4 alpha 已发布，有对应优化

**Comment by linkfengs** [comment]
> HBuilderX 2.8.4 alpha 已发布，有对应优化

一层v-for确实可以传参了，可是v-for里面继续嵌套v-for就不可以传对应的子集的items

**Comment by zhetengbiji** [comment]
> > HBuilderX 2.8.4 alpha 已发布，有对应优化
> 
> 一层v-for确实可以传参了，可是v-for里面继续嵌套v-for就不可以传对应的子集的items
> `<ul class="quesList"> <li class="quesLi" v-for="(item,index) in quesList" :key="index"> <div class="hotQues" v-for="(it,ii) in item.list" :key="ii+'.'" @click="clickMe(it)"> 123 </div> </li> </ul>`
> 这时还会报之前的错

版本多少

**Comment by linkfengs** [comment]
> > > HBuilderX 2.8.4 alpha 已发布，有对应优化
> > 
> > 
> > 一层v-for确实可以传参了，可是v-for里面继续嵌套v-for就不可以传对应的子集的items
> > `<ul class="quesList"> <li class="quesLi" v-for="(item,index) in quesList" :key="index"> <div class="hotQues" v-for="(it,ii) in item.list" :key="ii+'.'" @click="clickMe(it)"> 123 </div> </li> </ul>`
> > 这时还会报之前的错
> 
> 版本多少

2.8.8.20200820  应该是最新的吧

**Comment by zhetengbiji** [comment]
> > > > HBuilderX 2.8.4 alpha 已发布，有对应优化
> > > 
> > > 
> > > 一层v-for确实可以传参了，可是v-for里面继续嵌套v-for就不可以传对应的子集的items
> > > `<ul class="quesList"> <li class="quesLi" v-for="(item,index) in quesList" :key="index"> <div class="hotQues" v-for="(it,ii) in item.list" :key="ii+'.'" @click="clickMe(it)"> 123 </div> </li> </ul>`
> > > 这时还会报之前的错
> > 
> > 
> > 版本多少
> 
> 2.8.8.20200820 应该是最新的吧

你的是因为``:key="ii+'.'"``，目前小程序端不支持，只能用 ``:key="ii"``
