### ISSUE TITLE
Vue3打包出来的vendor文件存在大量“不明”代码

### ISSUE THREAD

**Issue by moohng** [dcloudio/uni-app#3790]
**问题描述**

vue3打包出来的vendor.js文件中存在大量且重复的“不明代码”，如图：

![image](https://user-images.githubusercontent.com/16220028/185089515-c0143323-ff18-4c4f-8080-54716cdf422f.png)

看起来像是npm环境相关和本地目录相关的东西，大量且重复，所占用的体积差不多是vendor文件的一多半了。

vue2打包出来没有这些代码

**复现步骤**

运行打包命令

**系统信息:**

uniapp版本：3.0.0-alpha-3050420220804004

**Comment by fxy060608** [comment]
发测试工程

**Comment by moohng** [comment]
发现原因了，是我在vite.config.js中的define配置得有问题。

```js
define: {
  'process.env': {
    ...process.env,
    // ...
  }
}
```

不知道算不算bug

**Comment by fxy060608** [comment]
> 发现原因了，是我在vite.config.js中的define配置得有问题。
> 
> ```js
> define: {
>   'process.env': {
>     ...process.env,
>     // ...
>   }
> }
> ```
> 
> 不知道算不算bug

发行模式会自动压缩
比如console.log(process.env.NODE_ENV)
开发模式会显示完整的process.env
发行模式会仅保留NODE_ENV
