### ISSUE TITLE
[Page Lost]英文系统打开官网带参链接，被强制重定向至 en.* 并且之后的参数全部消失，导致文档链接无效

### ISSUE THREAD

**Issue by whoooami** [dcloudio/uni-app#3794]
**问题描述**
比如浏览器打开 https://uniapp.dcloud.io/vue-api?id=componentsolutions
直接被重定向到 https://en.uniapp.dcloud.io/

**复现步骤**

[或者可以直接贴源代码]

**预期结果**
能不能去掉强制跳转，如果要强制能不能带上参数。
**实际结果**

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by whoooami** [comment]
看到上面直接问题已经修复了。
相关的问题：
比如在打包界面显示的视频奖励链接：https://uniapp.dcloud.io/api/a-d/rewarded-video （图1）
点开后自动跳转至: https://en.uniapp.dcloud.io/api/a-d/rewarded-video.html (404图2)
<img width="668" alt="image" src="https://user-images.githubusercontent.com/2926551/185824731-ab3c6a6a-1fca-41ed-95a0-f7b0af6f4e44.png">
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/2926551/185824994-2c7b8394-a74a-490b-b7e6-a4496305d5d9.png">
麻烦也一并处理一下，谢谢

**Comment by whoooami** [comment]
百度搜出来的
https://www.baidu.com/link?url=r4RwEZw3Epex3t9_3NnNweaCnF3odgq-3YtCA5Xr6tsPf8JkMT2mc7jGK01qcso_iQxkRpV3o-6tAzWJHpgXe6rp8_Pre2F0y4Y_d9M2GBe&wd=&eqid=f6bd18aa002699f7000000056312b804

<img width="708" alt="image" src="https://user-images.githubusercontent.com/2926551/188251986-e10ef67a-429c-4fd0-9d53-4be5c5e61a00.png">
<img width="1208" alt="image" src="https://user-images.githubusercontent.com/2926551/188252000-4b074f2d-39a5-4c0e-a106-34aae187a933.png">

**Comment by StrivingRabbit** [comment]
已修复
