### ISSUE TITLE
v3+typescript+hbuilder 提示问题

### ISSUE THREAD

**Issue by jacksonyu** [dcloudio/uni-app#3795]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
![Dingtalk_20220819124107.jpg](https://s2.loli.net/2022/08/19/PnbTMzXFqkoh78J.jpg)

如图提示如此修正？

**复现步骤**
[复现问题的步骤]
使用最新版 hbuilder 创建新 uniapp 项目，把 main.js 改成 ts，把 app.vue , index.vue 等vue 文件改成 ts 格式之后，hbuilder x 提示如上。

**预期结果**
正确提示

**实际结果**
提示错误

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 ：最新 alpha
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by warmthsea** [comment]
建议HbuildX 启动项目，vscode 写代码
