### ISSUE TITLE
安卓 微信小程序 canvas不能触发touch事件

### ISSUE THREAD

**Issue by fuyidaotang** [dcloudio/uni-app#3796]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/15215747/185560955-0c677f49-ead8-4291-9994-a9570d2d4b60.png">
<img width="523" alt="image" src="https://user-images.githubusercontent.com/15215747/185561010-582dfd4b-0eef-4eed-b6b0-452f2aff6c72.png">
不打印，完全没触发start和move，ios正常，就只有安卓有问题
[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
从描述看，应该是微信小程序安卓端的实现问题，需要反馈到微信小程序社区。

**Comment by doglex** [comment]
在外面套一层div，touch事件绑定到div上可以，canvas上似乎不行
