### ISSUE TITLE
[non-writable] modification of global variable "Promise.prototype.finally" is not allowed when using plugins at app.json

### ISSUE THREAD

**Issue by leiroc** [dcloudio/uni-app#380]
**问题描述**
在使用插件的情况下，使用Promise ，封装的 uni.request, 提示如下错误：
[non-writable] modification of global variable "Promise.prototype.finally" is not allowed when using plugins at app.json

注意：微信限制在使用插件的时候修改原生属性，Promise.prototype.finally，不可以重写。

**复现步骤**

1. app.json 中引入插件
2. 使用 uni.request Promise 形式调用，（如果不传入 success、fail、complete 等 callback 参数，将以 Promise 返回数据）

[参考：](https://uniapp.dcloud.io/api/README?id=promise-%E5%B0%81%E8%A3%85)

[或者可以直接贴源代码]

/**
 * 根据id获取歌曲
 * @param {String} id
 */
async function getSongById(id) {
  uni.showLoading({
    title: "加载中..."
  });
  let [error, res] = await uni.request({
    url: URL_SONG,
    header: util.getHttpHeader(),
    data: {
      resourceType: 2,
      resourceId: id
    }
  });
  uni.hideLoading();
  return formatSong(id, res.data);
}

**预期结果**
无报错

**实际结果**
报错：[non-writable] modification of global variable "Promise.prototype.finally" is not allowed when using plugins at app.json

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**

底层对 Promise.prototype.finally，进行了 复写！

**Comment by fxy060608** [comment]
在开发工具中提示的吗？你用的插件是什么？
我这里集成 wxparser 插件，然后用 uni.request promise 测试没发现有这个错误提示

**Comment by leiroc** [comment]
我用的是第三方插件，插件需要在 app.json 中注册哦。工具是微信调试工具，最新的版本。 @fxy060608

**Comment by leiroc** [comment]
@fxy060608 如上。

**Comment by fxy060608** [comment]
我也是用的三方插件做测试，没有提示报错，微信开发者工具是哪个版本，版本号贴出来

**Comment by leiroc** [comment]
版本号：1.02.1905081 @fxy060608

**Comment by fxy060608** [comment]
已确认，你使用的微信开发者工具是预发布版本，可以先使用稳定版，稍后修复此问题

**Comment by leiroc** [comment]
好，很给力！ @fxy060608

**Comment by reikami** [comment]
我也遇到了这个问题，请问这个问题修复了吗？
