### ISSUE TITLE
vue3 vite cli版本 更新后无法识别uni_modules组件

### ISSUE THREAD

**Issue by cpf23333** [dcloudio/uni-app#3801]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
vue3+vite cli版本 更新后无法识别uni_modules组件
**复现步骤**
[复现问题的步骤]
1 从文档快速上手给的gitee链接下载uni-preset-vue-vite压缩包，打开，npm i 及安装sass后运行一切正常 ，app提示版本为3.5.3需要更新
2 执行npx @dcloudio/uvm alpha命令
3 无法识别uni_modules组件，h5和app端测试都是

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]
无法识别uni_modules组件，h5和app运行都是

**系统信息:**
 - 发行平台: h5及安卓
 - 操作系统 Android 12
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
node 14.19.3
npm 6.14.17

[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
发测试工程

**Comment by cpf23333** [comment]
[uni-preset-vue-vite-te.zip](https://github.com/dcloudio/uni-app/files/9392303/uni-preset-vue-vite-te.zip)
测试工程

**Comment by cpf23333** [comment]
> 发测试工程
[uni-preset-vue-vite-te.zip](https://github.com/dcloudio/uni-app/files/9392310/uni-preset-vue-vite-te.zip)

**Comment by fxy060608** [comment]
1. 锁定 @dcloud/* 版本号为3.0.0-alpha-3050420220804008
2. 调整 vite 版本为 2.9.14
```json
"dependencies": {
    "@dcloudio/uni-app": "3.0.0-alpha-3050420220804008",
    "@dcloudio/uni-app-plus": "3.0.0-alpha-3050420220804008",
    "@dcloudio/uni-components": "3.0.0-alpha-3050420220804008",
    "@dcloudio/uni-h5": "3.0.0-alpha-3050420220804008",
    "@dcloudio/uni-mp-alipay": "3.0.0-alpha-3050420220804008",
    "@dcloudio/uni-mp-baidu": "3.0.0-alpha-3050420220804008",
    "@dcloudio/uni-mp-kuaishou": "3.0.0-alpha-3050420220804008",
    "@dcloudio/uni-mp-lark": "3.0.0-alpha-3050420220804008",
    "@dcloudio/uni-mp-qq": "3.0.0-alpha-3050420220804008",
    "@dcloudio/uni-mp-toutiao": "3.0.0-alpha-3050420220804008",
    "@dcloudio/uni-mp-weixin": "3.0.0-alpha-3050420220804008",
    "@dcloudio/uni-quickapp-webview": "3.0.0-alpha-3050420220804008",
    "sass": "^1.54.5",
    "vue": "^3.2.37",
    "vue-i18n": "^9.2.2",
    "vuex": "^4.0.2"
  },
  "devDependencies": {
    "@dcloudio/types": "^3.0.13",
    "@dcloudio/uni-automator": "3.0.0-alpha-3050420220804008",
    "@dcloudio/uni-cli-shared": "3.0.0-alpha-3050420220804008",
    "@dcloudio/uni-stacktracey": "3.0.0-alpha-3050420220804008",
    "@dcloudio/vite-plugin-uni": "3.0.0-alpha-3050420220804008",
    "vite": "2.9.14"
  }
```

**Comment by cpf23333** [comment]
> 1. 锁定 @dcloud/* 版本号为3.0.0-alpha-3050420220804008
> 2. 调整 vite 版本为 2.9.14
> 
> ```json
> "dependencies": {
>     "@dcloudio/uni-app": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-app-plus": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-components": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-h5": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-mp-alipay": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-mp-baidu": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-mp-kuaishou": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-mp-lark": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-mp-qq": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-mp-toutiao": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-mp-weixin": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-quickapp-webview": "3.0.0-alpha-3050420220804008",
>     "sass": "^1.54.5",
>     "vue": "^3.2.37",
>     "vue-i18n": "^9.2.2",
>     "vuex": "^4.0.2"
>   },
>   "devDependencies": {
>     "@dcloudio/types": "^3.0.13",
>     "@dcloudio/uni-automator": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-cli-shared": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-stacktracey": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/vite-plugin-uni": "3.0.0-alpha-3050420220804008",
>     "vite": "2.9.14"
>   }
> ```

测试了下，好像没有效果，已通过查看node_modules方式确定版本是这些

**Comment by cpf23333** [comment]
> 1. 锁定 @dcloud/* 版本号为3.0.0-alpha-3050420220804008
> 2. 调整 vite 版本为 2.9.14
> 
> ```json
> "dependencies": {
>     "@dcloudio/uni-app": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-app-plus": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-components": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-h5": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-mp-alipay": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-mp-baidu": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-mp-kuaishou": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-mp-lark": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-mp-qq": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-mp-toutiao": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-mp-weixin": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-quickapp-webview": "3.0.0-alpha-3050420220804008",
>     "sass": "^1.54.5",
>     "vue": "^3.2.37",
>     "vue-i18n": "^9.2.2",
>     "vuex": "^4.0.2"
>   },
>   "devDependencies": {
>     "@dcloudio/types": "^3.0.13",
>     "@dcloudio/uni-automator": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-cli-shared": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/uni-stacktracey": "3.0.0-alpha-3050420220804008",
>     "@dcloudio/vite-plugin-uni": "3.0.0-alpha-3050420220804008",
>     "vite": "2.9.14"
>   }
> ```

不好意思，方案是可行的，需要删除package-lock.json后再重新安装依赖
