### ISSUE TITLE
微信小程序预览空白，控制台日志显示uni-data-checkbox错误TypeError: Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by KyleTang** [dcloudio/uni-app#3809]
**问题描述**

微信小程序预览空白，控制台日志显示uni-data-checkbox错误TypeError: Cannot read property 'length' of undefined

错误提示为：
**页面【uni_modules/uni-data-checkbox/components/uni-data-checkbox/uni-data-checkbox]错误:
 TypeError: Cannot read property 'length' of undefined**
![001](https://user-images.githubusercontent.com/631193/187055229-10338494-b0e2-40e4-a1c0-01916c32283f.png)
断点跟踪
![002](https://user-images.githubusercontent.com/631193/187055245-5eb5814a-50c8-4a36-b1cb-af42206dbe7e.png)
**经过分析，并不是uni-data-checkbox本身有错误，而是HBuilderX.3.5.3.20220729间接依赖的uni-cloud包有问题。**

**复现步骤**
1.  安装并启动“HBuilderX.3.5.3.20220729”
2. 下载项目工程 https://gitee.com/y_project/RuoYi-App/tree/01ff1e617e30082a1221bfbacbf229f9562fb186/ 
3. 导入项目后，用微信小程序预览

**预期结果**
微信小程序的控制台无任何错误提示，可正常预览（已验证，回退到HBuilderX.3.4.7.20220422是正常的）

**实际结果**
如上截图所示

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 windows 10 
 - HBuilderX版本 HBuilderX.3.5.3.20220729
 - uni-app版本 uni-app-2.0.1-35320220729001， uni-ui 版本1.4.20
 - 设备信息，开发预览无设备

**补充信息**

我下载了旧版本HBuilderX.3.4.7.20220422就好使了（uniapp-cli版本是3.4.7-2022042217，依赖的uni-cli-i18n是^2.0.1-34720220422001）。

从报错的地方溯源分析来看，应该是vue-cli-plugin-uni依赖的uni-cloud里的代码有问题，逻辑考虑不周期，出了异常以后，**出问题应该只影响到局部，现在影响了全局**。现在影响的结果就是HBuilderX.3.5.3.20220729的小程序预览全是空白，根本没法用。

我的HBuilderX.3.5.3.20220729使用“npx patch-hbuilderx-plugins”尝试修复，也是不好使的。

**目前只能回退到 旧版本HBuilderX.3.4.7.20220422** 

同一问题的关联的issue链接：[https://github.com/dcloudio/uni-ui/issues/575#issuecomment-1229357681](https://github.com/dcloudio/uni-ui/issues/575#issuecomment-1229357681)

**Comment by Wangyaqi** [comment]
此问题已在alpha版本修复，HBuilderX正式版还没有发布新版本，也可以在HBuilderX安装目录执行npx patch-hbuilderx-plugins对此问题进行临时修复

**Comment by Wangyaqi** [comment]
npx patch-hbuilderx-plugins 执行后的plugins/uniapp-cli目录 lock文件发来看下

**Comment by KyleTang** [comment]
![01](https://user-images.githubusercontent.com/631193/187406316-622f2916-4e6a-4a76-9105-b41601592f15.png)

[HBuilderX-plugins-uniapp-cli-package-lock.zip](https://github.com/dcloudio/uni-app/files/9451774/HBuilderX-plugins-uniapp-cli-package-lock.zip)

**Comment by zhetengbiji** [comment]
> npx patch-hbuilderx-plugins 执行后的plugins/uniapp-cli目录 lock文件发来看下，另外此问题已在HBuilderX 3.5.5版本修复

重新执行一下，刚处理了一下在不同磁盘补丁应用失败的问题 ```npx patch-hbuilderx-plugins@latest```
