### ISSUE TITLE
根据vite官网修改配置热更新不生效

### ISSUE THREAD

**Issue by ChenXiaoSong12321** [dcloudio/uni-app#3811]
**问题描述**
根据 vite 官网设置 https://cn.vitejs.dev/config/server-options.html#server-watch，修改 node_modules 中包不生效，因为要开发npm包，所以没有热更新比较影响效率

**复现步骤**
1. vite.config.ts 中修改配置，参考： https://cn.vitejs.dev/config/server-options.html#server-watch
2. 修改 node_modules 中包对应的文件

[或者可以直接贴源代码]

**预期结果**
热更新生效

**实际结果**
热更新不生效

**系统信息:**
 - 发行平台: [微信小程序]
 - 操作系统 [macOS]
 - uni-app版本 ["@dcloudio/uni-app": "^3.0.0-alpha-3040220220310005"]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by okxiaoliang4** [comment]
解决了吗

**Comment by Otto-J** [comment]
看起来是想想监听 node_moduels 的文件，官方给出的问题结论是

> 目前没有可行的方式来监听 node_modules 中的文件。若要了解更多详情和可能的临时替代方案，你可以关注 [issue #8619](https://github.com/vitejs/vite/issues/8619)。

但如果你是本地调试，完全可以把对应的包提取到 node_modules 之外，并参与编译构建。
