### ISSUE TITLE
uni-app 小程序端登录 uni.login 拿到的 code 通过 uni.request({url: 'https://www.example.com/loginByWeixin'})  返回404

### ISSUE THREAD

**Issue by joe123345** [dcloudio/uni-app#3812]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhangyongxuan** [comment]
这个好像得自己写服务端接口吧

**Comment by joe123345** [comment]
好像是的，需要自己写接口，直接请求&nbsp;https://www.example.com/loginByWeixin 不行&nbsp;





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月30日(星期二) 上午9:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dcloudio/uni-app] uni-app 小程序端登录 uni.login 拿到的 code 通过 uni.request({url: &#39;https://www.example.com/loginByWeixin&#39;})  返回404 (Issue #3812)





 
这个好像得自己写服务端接口吧

**Comment by joe123345** [comment]
你好, uni.getUserInfo 方法是不是和微信小程序的 wx.getUserInfo 一样，没有授权弹框了。那应该怎么获取用户的userinfo 呢







&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dcloudio/uni-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月30日(星期二) 上午9:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] uni-app 小程序端登录 uni.login 拿到的 code 通过 uni.request({url: 'https://www.example.com/loginByWeixin'})  返回404 (Issue #3812)





 
这个好像得自己写服务端接口吧

**Comment by joe123345** [comment]
问题已解决





&nbsp;




------------------ 原始邮件 ------------------
发件人:                                                                                                                        "dcloudio/uni-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月30日(星期二) 上午9:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] uni-app 小程序端登录 uni.login 拿到的 code 通过 uni.request({url: 'https://www.example.com/loginByWeixin'})  返回404 (Issue #3812)





 
这个好像得自己写服务端接口吧
