### ISSUE TITLE
uni.getEnterOptionsSync() 文档与实际返回不匹配

### ISSUE THREAD

**Issue by hb0730** [dcloudio/uni-app#3813]
**问题描述**
uni.getEnterOptionsSync() 返回的属性与[文档](https://uniapp.dcloud.net.cn/api/getEnterOptionsSync.html#getenteroptionssync)列表属性不一致

返回值: 
```code
groupId: ""
group_id: ""
path: "pages/index/index"
query: {}
refererInfo: {appId: "xxx", extraData: {…}}
scene: "990001"
shareTicket: ""
showFrom: 10
subScene: ""
```
`refererInfo` 与文档不一致

**环境**
`vite+vue3+ts` 
**小程序平台**
`mp-toutiao`

**Comment by StrivingRabbit** [comment]
哪里不一致？

**Comment by StrivingRabbit** [comment]
应该是toutiao的api拼写错误，可以向字节反应
![Snipaste_2022-09-03_14-38-07](https://user-images.githubusercontent.com/33573212/188259084-ef6ffc03-0b29-4188-85f1-164fcef8c6b5.jpg)
