### ISSUE TITLE
image标签加载项目本地图片，H5正常显示  iOS Android 显示空白 

### ISSUE THREAD

**Issue by SimmonHou** [dcloudio/uni-app#3817]
**问题描述**

   image标签加载项目本地图片，H5正常显示  iOS Android 显示空白 
  ps: 可以参考社区18年发布的帖子，https://ask.dcloud.net.cn/article/35056

**系统信息:**

   -HBuilderX 3.5.5.20220825-alpha
   -操作系统: iOS 15
   -设备信息: iPhone XR

**Comment by zhetengbiji** [comment]
参考此贴配置后是否解决？
