### ISSUE TITLE
兼容 vite@3.x

### ISSUE THREAD

**Issue by juukee** [dcloudio/uni-app#3818]
报错
```
运行到H5页面报错：Uncaught ReferenceError: __SERVER_HOST__ is not defined
```

**Comment by RavingRua** [comment]
这个似乎是Vite 3测试环境在有些Windows机器上会出现的问题，最好去Vite的issue里反应。

**Comment by StrivingRabbit** [comment]
![Snipaste_2022-09-02_13-33-23](https://user-images.githubusercontent.com/33573212/188065852-cf5151a9-a29c-4343-aea4-dfaac2d1ee2b.jpg)
创建 cli 项目，安装 vite v3.0.9 。运行正常

**Comment by juukee** [comment]
运行是正常，但是打开浏览器显示页面空白，h5下面提示报错__SERVER_HOST__ is not defined

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/3699
