### ISSUE TITLE
vite.config.js引入unplugin-auto-import报错

### ISSUE THREAD

**Issue by fangshikeji** [dcloudio/uni-app#3820]
![image](https://user-images.githubusercontent.com/76583297/187844721-d894af78-9686-4f7d-82c6-e3b2b98beabb.png)

**Comment by codexu** [comment]
HBuilderX 目前的 node 版本还不支持，可以用 CLI 的方式引入。
参考 https://ask.dcloud.net.cn/question/152267

**Comment by fangshikeji** [comment]
现在有升级HBuilderX node版本的计划吗？

**Comment by fangshikeji** [comment]
> HBuilderX 目前的 node 版本还不支持，可以用 CLI 的方式引入。 参考 https://ask.dcloud.net.cn/question/152267

现在有升级HBuilderX node版本的计划吗？

**Comment by snice** [comment]
unplugin-auto-import@0.7.1

这个版本可以用
