### ISSUE TITLE
微信小程序打包的时候没有吧app.json中的requiredPrivateInfos配置打包进去，导致相关地理位置api无法使用

### ISSUE THREAD

**Issue by yoonayyb** [dcloudio/uni-app#3822]
微信小程序打包的时候没有吧app.json中的requiredPrivateInfos配置打包进去，导致相关地理位置api无法使用

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]
这个是本地配置
![image](https://user-images.githubusercontent.com/48116844/188058102-d59b8153-ce63-4d11-bfed-62eaaa351c7e.png)
这个是打包的小程序
![image](https://user-images.githubusercontent.com/48116844/188058150-13e473ec-4cf1-4109-a26b-8835098f88a5.png)
这个是报错信息
![image](https://user-images.githubusercontent.com/48116844/188058218-dd54e75d-ff07-47ab-a6ba-cf78fac70d05.png)

现在每次打包都要手动添加requiredPrivateInfos配置，然后在上传。希望能改进一下

**Comment by fxy060608** [comment]
manifest.json->mp-weixin 中配置

**Comment by yoonayyb** [comment]
> 
栓Q，可以了

**Comment by yoonayyb** [comment]
> manifest.json->mp-weixin 中配置
栓Q，可以了
