### ISSUE TITLE
微信小程序使用weixin-js-sdk，报错TypeError: Cannot read property 'jWeixin' of undefined

### ISSUE THREAD

**Issue by costaq** [dcloudio/uni-app#3823]
**问题描述**
新建空白项目，只引用了weixin-js-sdk一个库，在index页面引入weixin-js-sdk，进行初始化，浏览器打开无错误，使用微信小程序进行调试，报错TypeError: Cannot read property 'jWeixin' of undefined

**复现步骤**
[复现问题的步骤]
1.  安装weixin-js-sdk，yarn add weixin-js-sdk
2. index.vue，import wx from 'weixin-js-sdk'，在onLoad中进行wx.config初始化
3. 运行微信开发者工具

**实际结果**
![image](https://user-images.githubusercontent.com/24690993/188085749-44f0fe20-0d02-478e-99be-a0119d265a92.png)

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本3.5.3.20220729

**Comment by StrivingRabbit** [comment]
weixin-js-sdk 是用来开发微信网页的，微信小程序环境并不支持 weixin-js-sdk
