### ISSUE TITLE
5+ ios app 加载 webAssembly 时报错

### ISSUE THREAD

**Issue by sunnywanggit** [dcloudio/uni-app#3824]
**问题描述**
新建一个 ios 5+ app 项目，使用 a 标签以 webview 的形式打开外链（https://www.style3d.com/product/1159763?share_state_id=46595&func=resproduct&is_share_page=1&share_lang=zh-CN&debug=1）
![image](https://user-images.githubusercontent.com/53786183/188097792-94979231-0ef3-446d-bdb3-3028ad23573f.png)

在 ios 手机上访问，会报以下错误：
![image](https://user-images.githubusercontent.com/53786183/188098337-de3ea195-b24f-4446-a90a-fe532a8f963c.png)

**预期结果**
期望 5+ App 能正常使用 webAssembly 提供的能力。

**实际结果**
在 5+ App 中使用 webAssembly 报错。

**Comment by StrivingRabbit** [comment]
在 safari 中打开正常吗？

**Comment by StrivingRabbit** [comment]
由于长时间未恢复，issue 关闭，如果还有问题可以重开或者提新 issue
