### ISSUE TITLE
宠物社区/社交应用

### ISSUE THREAD

**Issue by XJingWei** [dcloudio/uni-app#3825]
宠物猫社区，2019年运行至今。目前拥有多端包括：Android、IOS、小程序、H5且都上架市场稳定运行中。在这先感谢uniapp的技术支持。

官网地址：https://youmao.pro/index.html

项目介绍：友猫是宠物猫社交平台，由黄经纬于2019年创建。友猫以“分享主子的美好世界”为使命，用户可以通过短视频、图文等形式记录猫咪日常动态、体重、洗澡、健康状态等。还有：免费领罐头，互相投食关注等你来探索。以及各种类宠物猫的训练,饲养,健康相关信息。并基于兴趣形成互动。截至到2020年7月，93%用户是90后，并持续快速增长。

**Comment by StrivingRabbit** [comment]
#6

**Comment by Goingdown9** [comment]
> 宠物猫社区，2019年运行至今。目前拥有多端包括：Android、IOS、小程序、H5且都上架市场稳定运行中。在这先感谢uniapp的技术支持。
> 
> 官网地址：https://youmao.pro/index.html
> 
> 项目介绍：友猫是宠物猫社交平台，由黄经纬于2019年创建。友猫以“分享主子的美好世界”为使命，用户可以通过短视频、图文等形式记录猫咪日常动态、体重、洗澡、健康状态等。还有：免费领罐头，互相投食关注等你来探索。以及各种类宠物猫的训练,饲养,健康相关信息。并基于兴趣形成互动。截至到2020年7月，93%用户是90后，并持续快速增长。

**Comment by Goingdown9** [comment]
Goo
