### ISSUE TITLE
使用`pinia`报错

### ISSUE THREAD

**Issue by llk2yq** [dcloudio/uni-app#3826]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
vue3+vite项目，使用cli运行到微信开发者工具后报错。

**复现步骤**
[复现问题的步骤]
测试工程：
[test.zip](https://github.com/dcloudio/uni-app/files/9486489/test.zip)

**补充信息**
微信开发者工具报错截图：
![image](https://user-images.githubusercontent.com/22813922/188355000-6604688a-fb5f-4bfa-b1d5-e298fcbbe1c8.png)

打印编译后的store文件中的`common_vendor`是一个空对象。

**Comment by llk2yq** [comment]
@fxy060608 有测试工程，可以看看吗？

**Comment by llk2yq** [comment]
已经临时解决了，将`utils/page.ts`移入到src目录中即可。

**Comment by llk2yq** [comment]
@StrivingRabbit 请问一下是什么问题导致的呢？

**Comment by StrivingRabbit** [comment]
> @StrivingRabbit 请问一下是什么问题导致的呢？

你将 utils 放到 src 外面，打包时会打入到 `vendor.js` 中。形成一个循环引用，再次编译后 `ble.store.js` 中引用到的 `vendor` 为空对象。

如果你放到 src 下，则会用目录引入原文件，不存在上述问题
