### ISSUE TITLE
多个具名插槽使用过滤器、方法报错（仅在第一个插槽有效）

### ISSUE THREAD

**Issue by EmptyG2018** [dcloudio/uni-app#3828]
**问题描述**
在组件中使用多个具名插槽时，使用过滤器、方法会存在报错。但仅在第一个插槽中使用能够正常运行。

![image](https://user-images.githubusercontent.com/49466897/188540142-3c1d1bcd-8cb5-433c-a911-09e8bffb8c00.png)
![image](https://user-images.githubusercontent.com/49466897/188540171-6615fa99-6fd0-4ee0-ab1f-db60c001eca1.png)

**预期结果**
希望能与 vue 效果保持一致。
codesandbox：https://codesandbox.io/s/elated-haslett-9tk7eo?file=/src/App.vue

**实际结果**
![image](https://user-images.githubusercontent.com/49466897/188540225-1e8d1a81-52ae-4f10-9801-4d61b1426679.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: Android 11
 - HBuilderX版本: 3.5.3.20220729
 - 设备信息: MIX4

**Comment by zhetengbiji** [comment]
scopedSlotsCompiler 配置为 augmented 试试
https://uniapp.dcloud.net.cn/collocation/manifest.html#mp-weixin
