### ISSUE TITLE
uni-app项目中的hybrid里的本地页面，如果想用跟uni-app相同的ui框架该怎么做啊？

### ISSUE THREAD

**Issue by zhengguangfa** [dcloudio/uni-app#383]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
uni-app项目中的hybrid里的本地页面，如果想用跟uni-app相同的ui框架该怎么做啊？项目中因为有不少放hybrid里的本地web页面形式做的，想跟uni-app使用统一的ui框架，且也能做成js、less啥的可以打包的那种，该如何做呢？
**复现步骤**
[复现问题的步骤]
webview引入的hybrid页面

**预期结果**
webview引入的hybrid页面也能跟外面的vue页面一样使用跟uni-app一致的ui，并能打包js和less、sass等

**实际结果**

**系统信息:**

**补充信息**

**Comment by StrivingRabbit** [comment]
那就看使用的 ui 框架有没有web版的， 在引入的 hybrid 页面中引入
