### ISSUE TITLE
uni.createIntersectionObserver  监听多个节点时 observeAll: true, 在百度小程序中不生效，百度小程序需要传入 selectAll: true, 方可监听多个节点

### ISSUE THREAD

**Issue by yuyy** [dcloudio/uni-app#3835]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
uni.createIntersectionObserver  监听多个节点时 observeAll: true, 在百度小程序中不生效，百度小程序需要传入 selectAll: true, 方可监听多个节点

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

let params = {
    thresholds: [0.5],
    observeAll: true,
};

if (isBaidu()) {
    params = {
        thresholds: [0.5],
        selectAll: true,
    };
}
 const intersectionObserver = uni.createIntersectionObserver(instance, params)
                    .relativeToViewport();

期望不做端的区分，直接传入observeAll 即可实现在手百内也可监听多个节点

**Comment by zhenyuWang** [comment]
HBuilderX 3.6.7 已支持
