### ISSUE TITLE
input值绑定问题

### ISSUE THREAD

**Issue by onlyshow** [dcloudio/uni-app#384]
**问题描述**
`<input type="text" maxlength="13" v-model="amount" @input="onInput">`
在`onInput`赋值`amount`，每两次事件才生效

**复现步骤**
`
onInput(e) {
    this.amount = '1'
    console.log(this.amount)
}
`

**预期结果**
不管输入什么，都显示为1

**实际结果**
1，12，1，13...

**系统信息:**
 - 发行平台: H5平台
 - HBuilderX版本 1.9.4.20190426

**Comment by zhetengbiji** [comment]
`input` 事件处理函数内实时修改当前值不生效，可以延迟设置，例如：``setTimeout(() => { this.value = 100 }, 0)``
见[官方文档](https://uniapp.dcloud.io/component/input)内注意事项
