### ISSUE TITLE
[Vite 3] 新建项目并升级到 Vite 3 后，编译到微信小程序报错 `ReferenceError: process is not defined`

### ISSUE THREAD

**Issue by ModyQyW** [dcloudio/uni-app#3848]
**问题描述**

新建项目并升级到 Vite 3 后，编译到微信小程序报错 `ReferenceError: process is not defined`

**复现步骤**

1.  `npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project`
2. 修改 `my-vue3-project` `pacakge.json` 中 `vite` 版本为 `^3.1.0`
3. `npm install`
4. `npm run dev:mp-weixin`
5. 使用微信小程序开发工具打开构建产物目录，在控制台中可看到报错

**预期结果**

没有报错，正常运行

**实际结果**

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/31850793/189638893-e5ada5d7-b937-4703-a7f3-adf98d1372de.png">

**系统信息:**

 - 发行平台：微信小程序
 - 操作系统：macOS Monterey 12.5.1
 - Node：v16.16.0
 - NPM：v8.19.1

**补充信息**

我个人猜测，要正常运行可以采用以下方式之一：

1. `uni-app` 这边把 `process.env.xxx` 相关部分换成 `import.meta.env.xxx || process.env.xxx`
2. 在 `vite.config.ts` 中设置 `define` 替换掉相关的 `process.env.xxx`

时间原因并未亲自试验。

另：个人感觉不该由开发者这边承担起这部分工作，1 比较好一些。

**Comment by fxy060608** [comment]
已修复，cli更新至：3.0.0-alpha-3060120220907003

**Comment by fxy060608** [comment]
> 升级依赖到 3.0.0-alpha-3060220220914001 后问题再次出现

升级至：3.0.0-alpha-3060220220914002
001是一个为HBuilderX服务的临时版本

**Comment by fordlee404** [comment]
> > 升级依赖到 3.0.0-alpha-3060220220914001 后问题再次出现
> 
> 升级至：3.0.0-alpha-3060220220914002 001是一个为HBuilderX服务的临时版本

3.0.0-alpha-3060420220922001版本还有这个问题

**Comment by ModyQyW** [comment]
@fordlee404  目前最新的是 3.0.0-alpha-3060820221027002，可以试着升级。不想升太多可以试着升到 3.0.0-alpha-3060420220922009。

**Comment by fordlee404** [comment]
> @fordlee404 目前最新的是 3.0.0-alpha-3060820221027002，可以试着升级。不想升太多可以试着升到 3.0.0-alpha-3060420220922009。

这两个版本还是会有这个问题，我特意用cli方式新建了一个项目试的。

**Comment by ModyQyW** [comment]
我这边项目用 3.0.0-alpha-3060820221027002 不能复现你的问题。你可以尝试确认以下两点，希望能帮到你。

1. 确认 package.json 里版本无误。
2. 确认 lock 文件中安装的版本和 package.json 里的版本一致。

**Comment by fordlee404** [comment]
很遗憾，还是会报错。已经确认版本信息无误了，并且把node_modules目录和lock文件都删掉，重新安装依赖，依然没用。我的复现步骤是：
1. 初始化项目：`npx degit dcloudio/uni-preset-vue#vite my-vue3-project`
2. 升级编译器到aplha版：`npx @dcloudio/uvm alpha`
3. 在main.js中添加： `console.log(process.env)`
4. 启动项目：`npm run dev:mp-weixin`
5. 打开微信小程序开发工具编译，查看控制台报错信息：`WAServiceMainContext.js?t=wechat&s=1667271368208&v=2.27.0:1 ReferenceError: process is not defined`

**Comment by ModyQyW** [comment]
建议你新开一个 issue 或者 @ 一下官方的人

**Comment by fordlee404** [comment]
在dcloud社区提bug了，https://ask.dcloud.net.cn/question/156510

**Comment by fxy060608** [comment]
> 很遗憾，还是会报错。已经确认版本信息无误了，并且把node_modules目录和lock文件都删掉，重新安装依赖，依然没用。我的复现步骤是：
> 
> 1. 初始化项目：`npx degit dcloudio/uni-preset-vue#vite my-vue3-project`
> 2. 升级编译器到aplha版：`npx @dcloudio/uvm alpha`
> 3. 在main.js中添加： `console.log(process.env)`
> 4. 启动项目：`npm run dev:mp-weixin`
> 5. 打开微信小程序开发工具编译，查看控制台报错信息：`WAServiceMainContext.js?t=wechat&s=1667271368208&v=2.27.0:1 ReferenceError: process is not defined`

应该直接访问process.env.*的具体内容，比如 process.env.NODE_ENV（要么是内置好了，要么是自己define了），不支持访问 process.env，因为vite里边除了dev:h5，其他环境是直接替换完整的字符串。可以使用标准vite项目做测试

**Comment by fordlee404** [comment]
感谢 @fxy060608 ，确实直接访问process.env.NODE_ENV是可以的，但是定义在.env中的环境变量还是访问不了。

**Comment by ModyQyW** [comment]
> 感谢 @fxy060608 ，确实直接访问process.env.NODE_ENV是可以的，但是定义在.env中的环境变量还是访问不了。

<https://cn.vitejs.dev/guide/env-and-mode.html> 和 <https://cn.vitejs.dev/config/shared-options.html#envprefix> 可能对你有帮助。

**Comment by fordlee404** [comment]
通过import.meta.env访问到了，同时.env文件中需要配置以VITE_开头，也就是用vite那一套环境变量的配置方法。
