### ISSUE TITLE
[Vite 3] 新建项目、升级到 Vite 3 并设置 `optimizeDeps.disabled: false` 后无法编译到微信小程序

### ISSUE THREAD

**Issue by ModyQyW** [dcloudio/uni-app#3849]
**问题描述**

新建项目、升级到 Vite 3 并设置 `optimizeDeps.disabled: false` 后无法编译到微信小程序

**复现步骤**

1. `npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project`
2. 修改 `pacakge.json` 中 `vite` 版本为 `^3.1.0`
3. 修改 `pacakge.json` 中 `@dcloudio/xxx` 版本为 `3.0.0-alpha-3060120220907003`
4. 修改 `vite.config.ts`，设置 `optimizeDeps.disabled: false`
5. `npm install`
6. `npm run dev:mp-weixin`

命令行显示停留在编译中状态。

**预期结果**

正常编译运行。

**实际结果**

停留在编译中状态，无法正常编译。如果移除 `optimizeDeps.disabled: false`，可正常编译。

**系统信息:**

发行平台：微信小程序
操作系统：macOS Monterey 12.5.1
Node：v16.16.0
NPM：v8.19.1

**补充信息**

该选项出现在 Vite 文档中。希望能支持。

<img width="740" alt="image" src="https://user-images.githubusercontent.com/31850793/189821492-74c86328-e7d7-408f-9c90-a63051a9a709.png">

<https://cn.vitejs.dev/guide/migration.html#experimental>

如果同时设置 `optimizeDeps.disabled: false` 和 `build.commonjsOptions: { include: [] }`，能正常编译，但用微信开发者工具打开存在报错。

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/31850793/189822494-fb243f3b-dd4b-4f74-a6fa-a1e99ef851a0.png">

**Comment by fxy060608** [comment]
目前不建议在小程序，App平台使用该配置，因为小程序平台和App平台，开发和发行均使用rollup打包，不像H5平台存在差异性。稍后会在这两个平台，强制使用 disabled:'build'
