### ISSUE TITLE
canvas canvasToTempFilePath errorHandler TypeError: g.drawImageByCanvas is not a function

### ISSUE THREAD

**Issue by githublyp** [dcloudio/uni-app#385]
**问题描述**
uni.canvasToTempFilePath({
        x: 100,
        y: 200,
        width: 50,
        height: 50,
        destWidth: 100,
        destHeight: 100,
        canvasId: 'myCanvas',
        success: function(res) {
          console.log(res.tempFilePath)
        }
      })
**复现步骤**
[复现问题的步骤]
1.  启动 <canvas canvas-id="myCanvas"></canvas>

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]
含有destWidth和destHeight

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
此问题发生在哪个平台？

**Comment by zhetengbiji** [comment]
由于长时间未响应，此问题关闭。
此问题未复现，请使用新版HBuilderX运行，如有问题另行反馈。
