### ISSUE TITLE
希望在 安卓端 新增 network_security_config 配置

### ISSUE THREAD

**Issue by bugaio** [dcloudio/uni-app#3850]
**新功能描述**
希望在 安卓端 新增 network_security_config 配置,  方便 https的抓包

**现状及问题**
app在提交到 测试环节时, 未root手机 在 抓https包时,  android端 尤为不方便, 希望 添加一个 配置项 来快速配置, 谢谢

**Comment by qhhsy** [comment]
`uni-app`现已支持在云打包时配置`AndroidManifest.xml`，可以自行配置`network_security_config`，请参考文档：[https://uniapp.dcloud.net.cn/tutorial/app-nativeresource-android](https://uniapp.dcloud.net.cn/tutorial/app-nativeresource-android)

**Comment by bugaio** [comment]
> `uni-app`现已支持在云打包时配置`AndroidManifest.xml`，可以自行配置`network_security_config`，请参考文档：https://uniapp.dcloud.net.cn/tutorial/app-nativeresource-android

您好,  
我在 按照官网 尝试 使用 nativeResouces
但是   打自定义基座的 apk中,  res与 assets中 均 未 发现 我的那些 文件 ?
请问  是我哪里  理解错误了么?
<img width="411" alt="image" src="https://user-images.githubusercontent.com/23302175/191208311-2b972ee6-b537-4bdb-939b-24b652bd4f31.png">

**Comment by qhhsy** [comment]
您的`HBuilder X`版本号是多少。此功能`3.6.0+ HBuilder X-alpha`版本支持。

**Comment by bugaio** [comment]
> 您的`HBuilder X`版本号是多少。此功能`3.6.0+ HBuilder X-alpha`版本支持。

最新的  3.6.3.20220917,
测试 项目 是由   HB 创建的,  不是 cli

**Comment by bugaio** [comment]
> 您的APPID发我一下

给您 添麻烦了 , 
__UNI__3D8B2C1

可能是我  姿势不对...因为 对android 也不是 很懂

**Comment by qhhsy** [comment]
> __UNI__3D8B2C1

已收到。可以删了这条信息

**Comment by qhhsy** [comment]
抱歉，文档错误，目录名应该是`nativeResouces` - > `nativeResources `。[文档](https://uniapp.dcloud.net.cn/tutorial/app-nativeresource-android.html#%E5%BA%94%E7%94%A8%E8%B5%84%E6%BA%90)已修改。

**Comment by bugaio** [comment]
> 抱歉，文档错误，目录名应该是`nativeResouces` - > `nativeResources `。[文档](https://uniapp.dcloud.net.cn/tutorial/app-nativeresource-android.html#%E5%BA%94%E7%94%A8%E8%B5%84%E6%BA%90)已修改。

今天试了下  cli项目 ,  
文档只 说了  hbx的版本
> 在HBuilderX 3.6以前，开发者如需使用manifest未封装的配置、或需自定义资源目录 assets、res下的内容，只能离线打包或开发[App原生语言插件 (opens new window)](https://nativesupport.dcloud.net.cn/NativePlugin/README)。
>
> HBuilderX3.6.0起，支持直接在应用项目中配置应用清单文件 AndroidManifest.xml 和资源目录 assets、res。

我做了 测试,  cli版本 必须也要升级后 才行, 
拿 老的 cli版本 , 测试 后  发现无效,   升级 cli 后  解决问题了

这个, 要在 文档上 体现一下么
