### ISSUE TITLE
运行到android一直是开始安装基座

### ISSUE THREAD

**Issue by moke8** [dcloudio/uni-app#3856]
**问题描述**
昨天可以的，今天突然不行了，手机和模拟器均运行不了，并且两者均安装了基座。
但是无论怎么重试/等待，永远都卡在“开始安装基座”
```
18:01:08.618 项目 'zb-app' 开始编译...
18:01:09.681 编译器版本：3.6.1（vue3）
18:01:09.681 请注意运行模式下，因日志输出、sourcemap 以及未压缩源码等原因，性能和包体积，均不及发行模式。
18:01:09.685 正在编译中...
18:01:10.829 vite v2.9.14 building for development...
18:01:12.464 项目 'zb-app' 编译成功。
18:01:12.464 ready in 2962ms.
18:01:13.242 开始安装基座...
18:01:13.377 开始安装基座...
```

**系统信息:**
 - 发行平台: android
 - 操作系统 Android 12.0 （红米k30）、Android 7.0 （雷电模拟器）
 - HBuilderX版本 3.6.1.20220907-alpha
 - uni-app版本 3.0.0-alpha-3060120220907002

**Comment by moke8** [comment]
手机和模拟器上没有任何反应

**Comment by qhhsy** [comment]
请确认手机和电脑是否正常连接。使用使用 ```adb```连接试试
（```adb```存放目录```HbuilderX\plugins\launcher\tools\adbs```）
```adb kill-serve && adb devices```

**Comment by moke8** [comment]
重新安装hbuilder已解决
