### ISSUE TITLE
支付宝插件引入后 编译后 data-com-type="wx"

### ISSUE THREAD

**Issue by lazyXjw** [dcloudio/uni-app#3857]
**问题描述**
支付宝插件引入后 编译后 data-com-type="wx"

**复现步骤**
<flowexchange @onCounterFlowExchange="onCounterExchange" ref="saveRefFlowExchange" :uid="uid" :channel="flowchanel"></flowexchange>  

 编译后 <flowexchange vue-id="2acd03d5-1" uid="{{uid}}" channel="{{flowchanel}}" ref="__r" data-ref="saveRefFlowExchange"   
        data-event-opts="{{[['^onCounterFlowExchange',[['onCounterExchange']]]]}}" data-com-type="wx" onOnCounterFlowExchange="__e"   
        onVueInit="__l"></flowexchange>
支付宝报错
TypeError: Cannot read property 'data-com-type' of undefined
Please check your component:

 "@dcloudio/uni-mp-alipay": "^2.0.0-31820210406002",

**Comment by lazyXjw** [comment]
https://ask.dcloud.net.cn/question/132498

**Comment by zhetengbiji** [comment]
你这个版本比较早期了，参考文档更新一下依赖试试。

**Comment by lazyXjw** [comment]
> 你文档这个版本比较早期了，参考更新一下试试。

<plugin-wrapper vue-id="47ef17c4-13" onPluginWrap="__w" data-event-opts="{{[['^onModalStatusBack',[['onModalStatusBack']]]]}}" data-com-type="wx" data-event-list="onOnModalStatusBack" onOnModalStatusBack="__e" onVueInit="__l" vue-slots="{{['default']}}"><zhidian-modal onOnModalStatusBack="{{'onOnModalStatusBack'+'47ef17c4-13'}}" shopId="2020112000077000000009731298" class="data-v-27ca1b4d data-v-27ca1b4d" onVueInit="__l"></zhidian-modal></plugin-wrapper>


升级到2.0.1-33920220314002后 编译多了一层plugin-wrapper

**Comment by lazyXjw** [comment]
<plugin-wrapper vue-id="47ef17c4-13" onPluginWrap="__w" data-event-opts="{{[['^onModalStatusBack',[['onModalStatusBack']]]]}}" data-com-type="wx" data-event-list="onOnModalStatusBack" onOnModalStatusBack="__e" onVueInit="__l" vue-slots="{{['default']}}"><aa-modal onOnModalStatusBack="{{'onOnModalStatusBack'+'47ef17c4-13'}}" shopId="xxxx" class="data-v-27ca1b4d data-v-27ca1b4d" onVueInit="__l"></aa-modal></plugin-wrapper>

**Comment by lazyXjw** [comment]
> > 你文档这个版本比较早期了，参考更新一下试试。
> 
> 升级到2.0.1-3392022031422后升级为plugin-wrapper

![image](https://user-images.githubusercontent.com/34739183/190588795-15a9d911-e2c3-47f7-a8a7-39908f175f6a.png)

**Comment by zhetengbiji** [comment]
> > > 你文档这个版本比较早期了，参考更新一下试试。
> > 
> > 
> > 升级到2.0.1-3392022031422后升级为plugin-wrapper
> 
> ![image](https://user-images.githubusercontent.com/34739183/190588795-15a9d911-e2c3-47f7-a8a7-39908f175f6a.png)

插件确实需要 plugin-wrapper，如果低版本找不到 plugin-wrapper，更新到 3.5.3 对应的版本

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/3619
