### ISSUE TITLE
严重bug：onReady生命周期会连续执行两次

### ISSUE THREAD

**Issue by 461395813** [dcloudio/uni-app#3858]
微信小程序页面内设置onReady生命周期，打开页面就会连续执行两次

必然复现，默认模板也会出现同样的问题。只在uniapp项目内出现，原生小程序代码不会出现

微信开发工具，安卓，ios都会

hbuilder版本：3.6.2.20220914

**Comment by zhenyuWang** [comment]
HBuilderX 3.6.3 已修复
