### ISSUE TITLE
support keyboard-accessory 

### ISSUE THREAD

**Issue by VisonM** [dcloudio/uni-app#3859]
**新功能描述**
支持 `textarea` 嵌套 `keyboard-accessory` 的正常编译

**现状及问题**
<img width="891" alt="image" src="https://user-images.githubusercontent.com/40595135/190844031-28526271-4d2a-4647-9326-5e2a6ba6b790.png">

<img width="341" alt="image" src="https://user-images.githubusercontent.com/40595135/190844002-94133482-003f-41af-a439-0eb33460113f.png">

**尝试方案**
wxcomponents 直接隔离出来使用，但是并不优雅，而且交互，事件，数据等等都比较怪异。

**补充信息**
主要是要扩展vue-template-compiler 使得textarea的子节点可支持组件而非直接变成字符串（这个本身违背html规范😂）,更新对应的uni-tempate-compiler。如果可行，愿意尝试提交pr

**Comment by Sun-hai-yang** [comment]
你好，请问如何在uniapp小程序里面支持这个keyboard-accessory组件呢，现在的情况是cover-view里面的点击事件触发不了。烦请解答一下，谢谢

**Comment by bigbossx** [comment]
use [wxcomponents](https://zh.uniapp.dcloud.io/tutorial/miniprogram-subject.html#%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E6%94%AF%E6%8C%81)

**Comment by sdz123** [comment]
> @Sun-hai-yang use [wxcomponents](https://zh.uniapp.dcloud.io/tutorial/miniprogram-subject.html#%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E6%94%AF%E6%8C%81)

我靠，还真有遇到这个问题，我今天也碰到了，用keyboard-accessory 组件uniapp识别不了，我自己搞了一个类似的，但键盘弹出来的时候会把页面顶上去，导致fixed定位会上移一段距离，然后键盘顶部的扩展就不能和键盘贴合了；然后又改成用cover-view实现了一个，上面的问题解决了，但cover-view又会出现偶尔点击失效的问题，真尼玛全都是坑，

**Comment by sdz123** [comment]
> > @Sun-hai-yang use [wxcomponents](https://zh.uniapp.dcloud.io/tutorial/miniprogram-subject.html#%E5%B0%8F%E7%A8%8B%E5%BA%8F%E8%87%AA%E5%AE%9A%E4%B9%89%E7%BB%84%E4%BB%B6%E6%94%AF%E6%8C%81)
> 
> 我靠，还真有遇到这个问题，我今天也碰到了，用keyboard-accessory 组件uniapp识别不了，我自己搞了一个类似的，但键盘弹出来的时候会把页面顶上去，导致fixed定位会上移一段距离，然后键盘顶部的扩展就不能和键盘贴合了；然后又改成用cover-view实现了一个，上面的问题解决了，但cover-view又会出现偶尔点击失效的问题，真尼玛全都是坑，

即便是使用wxcomponents也无法解决我的问题，因为我的textarea用的是第三方库，我本来是想单独把keyboard-accessory这个组件定义成wxcomponents，然后在第三方库的源码里的textarea插入这个wxcomponents，但这样无效，只有把完成的textarea和keyboard-accessory都定义在wxcomponents中才能使用keyboard-accessory的功能
