### ISSUE TITLE
建议新增页面滚动到顶部、底部命令

### ISSUE THREAD

**Issue by LiangDingWei** [dcloudio/uni-app#386]
**新功能描述**
建议新增页面滚动到顶部、底部命令

**现状及问题**
[由于项目中用到在一个页面中，可能这个页面每次加载完成后要滚动到底部或者顶部(聊天消息气泡列表)，有一个将页面滚动到目标位置的api，但是这个方法在浏览器或者app端都不好用]

**尝试方案**
[有尝试过使用现有的将页面滚动到目标位置的api，但是动态计算滚动位置也好高度也好都不准确，而且也无法滚动到底部]

**Comment by zhetengbiji** [comment]
目前不会新增滚动到顶部和底部的接口。
你是说 uni.pageScrollTo 在H5和App端有问题吗？在小程序端是否正常？如果有问题可以反馈具体的问题。

**Comment by d1y** [comment]
> 目前不会新增滚动到顶部和底部的接口。
> 你是说 uni.pageScrollTo 在 H5 和 App 端有问题吗？在小程序端是否正常？如果有问题可以反馈具体的问题。

在我们的项目中,实现的并不完美, 是不是我姿势不对

**Comment by Wangyaqi** [comment]
更新HBuilderX再试试，现在应该能滚动到准确位置了
