### ISSUE TITLE
Syntax Error: Error: PostCSS plugin postcss-uniapp-plugin requires PostCSS 8.

### ISSUE THREAD

**Issue by zxc0312** [dcloudio/uni-app#3862]
**问题描述**
开发环境正常，但是生产环境打包报错

+ npm run build

> designer-policy-h5@0.1.0 build /home/jenkins/agent/workspace/kbench-webmxvs8_workbench-h5_dev/designer-policy-h5
> npm run build:h5

> designer-policy-h5@0.1.0 build:h5 /home/jenkins/agent/workspace/kbench-webmxvs8_workbench-h5_dev/designer-policy-h5
> cross-env NODE_ENV=production UNI_PLATFORM=h5 vue-cli-service uni-build

-  Start to compile the current project to the h5 platform...
 ERROR  Failed to compile with 1 error3:18:35 AM

 error  in ./src/pages/index/index.vue?vue&type=style&index=0&id=4faa103a&scoped=true&lang=css&

Syntax Error: Error: PostCSS plugin postcss-uniapp-plugin requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users

 @ ./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-36320220917001@@dcloudio/vue-cli-plugin-uni/packages/h5-vue-style-loader??ref--7-oneOf-1-0!./node_modules/_css-loader@3.6.0@css-loader/dist/cjs.js??ref--7-oneOf-1-1!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-36320220917001@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-36320220917001@@dcloudio/vue-cli-plugin-uni/packages/webpack-preprocess-loader??ref--7-oneOf-1-2!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??ref--7-oneOf-1-3!./node_modules/_postcss-loader@3.0.0@postcss-loader/src??ref--7-oneOf-1-4!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-36320220917001@@dcloudio/vue-cli-plugin-uni/packages/vue-loader/lib??vue-loader-options!./node_modules/_@dcloudio_vue-cli-plugin-uni@2.0.1-36320220917001@@dcloudio/vue-cli-plugin-uni/packages/webpack-scoped-loader!./src/pages/index/index.vue?vue&type=style&index=0&id=4faa103a&scoped=true&lang=css& 4:14-970
 @ ./src/pages/index/index.vue?vue&type=style&index=0&id=4faa103a&scoped=true&lang=css&
 @ ./src/pages/index/index.vue
 @ ./src/pages.json
 @ ./src/main.js
 @ multi ./src/main.js

**预期结果**
打包正常

**实际结果**
打包报错

**Comment by breathcold** [comment]
同问

**Comment by zhetengbiji** [comment]
uni-app版本多少？

**Comment by breathcold** [comment]
我的  2.0.1-33920220314002  也有这个问题，安装最新版也有问题

**Comment by breathcold** [comment]
2.0.0-31820210406002  没有这个问题，但是因为业务需要确实要升级uni版本

**Comment by zhetengbiji** [comment]
> 2.0.0-31820210406002 没有这个问题，但是因为业务需要确实要升级uni版本

本地安装的postcss版本多少？

**Comment by breathcold** [comment]
"postcss-comment": "^2.0.0",
    "postcss-scss": "^4.0.4",

**Comment by breathcold** [comment]
我试过把本地的 postcss  装 8的版本，也不行，那个配置文件走的是uni配置的，我改成了本地的postcss也是这样
const path = require('path')
module.exports = {
  parser: require('postcss-comment'),
  plugins: [
    require('postcss-import')({
      resolve (id, basedir, importOptions) {
        if (id.startsWith('~@/')) {
          return path.resolve(process.env.UNI_INPUT_DIR, id.substr(3))
        } else if (id.startsWith('@/')) {
          return path.resolve(process.env.UNI_INPUT_DIR, id.substr(2))
        } else if (id.startsWith('/') && !id.startsWith('//')) {
          return path.resolve(process.env.UNI_INPUT_DIR, id.substr(1))
        }
        return id
      }
    }),
    require('autoprefixer')({
      remove: process.env.UNI_PLATFORM !== 'h5'
    }),
    require('@dcloudio/vue-cli-plugin-uni/packages/postcss')
  ]
}

**Comment by zhetengbiji** [comment]
```npm run info``` 打印一下依赖信息

**Comment by breathcold** [comment]
这是刚刚安装最新版本的 npm ls, 运行也是报错
`
├── @babel/plugin-syntax-typescript@7.12.13
├── @babel/runtime@7.12.18
├── @commitlint/cli@16.3.0
├── @commitlint/config-conventional@16.2.4
├── @dcloudio/types@2.2.1
├── @dcloudio/uni-app-plus@2.0.1-alpha-36320220919001
├── @dcloudio/uni-automator@2.0.1-alpha-36320220919001
├── @dcloudio/uni-cli-i18n@2.0.1-alpha-36320220919001
├── @dcloudio/uni-cli-shared@2.0.1-alpha-36320220919001
├── @dcloudio/uni-h5@2.0.1-alpha-36320220919001
├── @dcloudio/uni-helper-json@1.0.13
├── @dcloudio/uni-i18n@2.0.1-alpha-36320220919001
├── @dcloudio/uni-migration@2.0.1-alpha-36320220919001
├── @dcloudio/uni-mp-360@2.0.1-alpha-36320220919001
├── @dcloudio/uni-mp-alipay@2.0.1-alpha-36320220919001
├── @dcloudio/uni-mp-baidu@2.0.1-alpha-36320220919001
├── @dcloudio/uni-mp-jd@2.0.1-alpha-36320220919001
├── @dcloudio/uni-mp-kuaishou@2.0.1-alpha-36320220919001
├── @dcloudio/uni-mp-lark@2.0.1-alpha-36320220919001
├── @dcloudio/uni-mp-qq@2.0.1-alpha-36320220919001
├── @dcloudio/uni-mp-toutiao@2.0.1-alpha-36320220919001
├── @dcloudio/uni-mp-vue@2.0.1-alpha-36320220919001
├── @dcloudio/uni-mp-weixin@2.0.1-alpha-36320220919001
├── @dcloudio/uni-mp-xhs@2.0.1-alpha-36320220919001
├── @dcloudio/uni-quickapp-native@2.0.1-alpha-36320220919001
├── @dcloudio/uni-quickapp-webview@2.0.1-alpha-36320220919001
├── @dcloudio/uni-stacktracey@2.0.1-alpha-36320220919001
├── @dcloudio/uni-stat@2.0.1-alpha-36320220919001
├── @dcloudio/uni-template-compiler@2.0.1-alpha-36320220919001
├── @dcloudio/vue-cli-plugin-hbuilderx@2.0.1-alpha-36320220919001
├── @dcloudio/vue-cli-plugin-uni-optimize@2.0.1-alpha-36320220919001
├── @dcloudio/vue-cli-plugin-uni@2.0.1-alpha-36320220919001
├── @dcloudio/webpack-uni-mp-loader@2.0.1-alpha-36320220919001
├── @dcloudio/webpack-uni-pages-loader@2.0.1-alpha-36320220919001
├── @typescript-eslint/eslint-plugin@5.26.0
├── @typescript-eslint/parser@5.26.0
├── @vue/cli-plugin-babel@4.5.12
├── @vue/cli-plugin-typescript@4.5.19
├── @vue/cli-service@4.5.12
├── @vue/shared@3.2.39
├── babel-plugin-import@1.13.5
├── blueimp-md5@2.19.0
├── core-js@3.11.0
├── cross-env@7.0.3
├── eslint-config-airbnb-base@15.0.0
├── eslint-config-prettier@8.5.0
├── eslint-config-standard@17.0.0
├── eslint-import-resolver-alias@1.1.2
├── eslint-import-resolver-webpack@0.13.2
├── eslint-plugin-import@2.26.0
├── eslint-plugin-n@15.2.0
├── eslint-plugin-promise@6.0.0
├── eslint-plugin-vue@8.7.1
├── eslint@8.16.0
├── flyio@0.6.14
├── husky@7.0.4
├── jest@25.5.4
├── lint-staged@12.4.2
├── mini-types@0.1.5
├── miniprogram-api-typings@3.3.2
├── miniprogram-ci@1.4.13
├── node-sass@4.14.1
├── postcss-comment@2.0.0
├── postcss-scss@4.0.4
├── prettier@2.6.2
├── regenerator-runtime@0.12.1
├── sass-loader@9.0.3
├── style-resources-loader@1.4.1
├── stylelint-config-prettier@9.0.3
├── stylelint-config-standard@25.0.0
├── stylelint-scss@4.2.0
├── stylelint@14.8.5
├── typescript@3.9.9
├── uview-ui@1.8.4
├── vue-class-component@6.3.2
├── vue-cli-plugin-style-resources-loader@0.1.5
├── vue-mixin-decorator@1.2.0
├── vue-property-decorator@8.5.1
├── vue-scroller@2.2.4
├── vue-template-compiler@2.6.12
├── vue@2.6.12
├── vuex-class@0.3.2
└── vuex@3.6.2`

` ERROR  Failed to compile with 1 error                                                                                                                                                                     上午11:51:06

 error  in ./src/pages/pMain/chooseDishes.vue?vue&type=style&index=0&lang=css&

Error: PostCSS plugin postcss-uniapp-plugin requires PostCSS 8.
Migration guide for end-users:
https://github.com/postcss/postcss/wiki/PostCSS-8-for-end-users


 @ ./src/pages/pMain/chooseDishes.vue?vue&type=style&index=0&lang=css& 1:0-728 1:744-747 1:749-1474 1:749-1474
 @ ./src/pages/pMain/chooseDishes.vue
 @ ./src/main.ts?{"page":"pages%2FpMain%2FchooseDishes"}

No type errors found
Version: typescript 3.9.9
Time: 9406ms`

**Comment by breathcold** [comment]
cold@colddeMac-mini scan-order % npm run info

> minitemplate@0.1.0 info
> node node_modules/@dcloudio/vue-cli-plugin-uni/commands/info.js

uni-app v3.6.3
uni-app cli v2.0.1-alpha-36320220919001

Environment Info:

  System:
    OS: macOS 11.3
    CPU: (8) x64 Apple M1
  Binaries:
    Node: 14.16.1 - ~/.nvm/versions/node/v14.16.1/bin/node
    Yarn: 1.22.19 - ~/.nvm/versions/node/v14.16.1/bin/yarn
    npm: 8.7.0 - ~/.nvm/versions/node/v14.16.1/bin/npm
  Browsers:
    Chrome: 105.0.5195.125
    Firefox: Not Found
    Safari: 14.1
  npmPackages:
    @dcloudio/types: ^2.1.2 => 2.2.1 
    @dcloudio/uni-app-plus: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-automator: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-cli-i18n: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-cli-shared: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-h5: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-helper-json: * => 1.0.13 
    @dcloudio/uni-i18n: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-migration: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-mp-360: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-mp-alipay: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-mp-baidu: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-mp-jd: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-mp-kuaishou: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-mp-lark: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-mp-qq: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-mp-toutiao: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-mp-vue: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-mp-weixin: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-mp-xhs: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-quickapp-native: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-quickapp-webview: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-stacktracey: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-stat: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/uni-template-compiler: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/vue-cli-plugin-uni: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/webpack-uni-mp-loader: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: ^2.0.1-alpha-36320220919001 => 2.0.1-alpha-36320220919001 
    @hap-toolkit/dsl-vue:  0.6.13 
    @vue/babel-helper-vue-jsx-merge-props:  1.2.1 
    @vue/babel-helper-vue-transform-on:  1.0.2 
    @vue/babel-plugin-jsx:  1.0.5 
    @vue/babel-plugin-transform-vue-jsx:  1.2.1 
    @vue/babel-preset-app:  4.5.12 
    @vue/babel-preset-jsx:  1.2.4 
    @vue/babel-sugar-composition-api-inject-h:  1.2.1 
    @vue/babel-sugar-composition-api-render-instance:  1.2.4 
    @vue/babel-sugar-functional-vue:  1.2.2 
    @vue/babel-sugar-inject-h:  1.2.2 
    @vue/babel-sugar-v-model:  1.2.3 
    @vue/babel-sugar-v-on:  1.2.3 
    @vue/cli-overlay:  4.5.12 
    @vue/cli-plugin-babel: ~4.5.0 => 4.5.12 
    @vue/cli-plugin-router:  4.5.12 
    @vue/cli-plugin-typescript: ~4.5.15 => 4.5.19 
    @vue/cli-plugin-vuex:  4.5.12 
    @vue/cli-service: ~4.5.0 => 4.5.12 
    @vue/cli-shared-utils:  4.5.19 
    @vue/component-compiler-utils:  3.2.0 (3.2.0)
    @vue/devtools-api:  6.0.0-beta.15 
    @vue/preload-webpack-plugin:  1.1.2 
    @vue/reactivity:  3.0.5 
    @vue/shared: ^3.2.39 => 3.2.39 
    @vue/web-component-wrapper:  1.3.0 
    eslint-plugin-vue: ^8.7.1 => 8.7.1 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.11 => 2.6.12 
    vue-class-component: ^6.3.2 => 6.3.2 (7.2.6, 7.2.6)
    vue-cli-plugin-style-resources-loader: ~0.1.5 => 0.1.5 
    vue-eslint-parser:  8.3.0 
    vue-hot-reload-api:  2.3.4 
    vue-loader:  15.9.6 (16.3.0, 15.9.6)
    vue-mixin-decorator: ^1.2.0 => 1.2.0 
    vue-property-decorator: ^8.0.0 => 8.5.1 
    vue-router:  3.0.1 
    vue-scroller: ^2.2.4 => 2.2.4 
    vue-style-loader:  4.1.3 (4.1.3)
    vue-template-compiler: ^2.6.11 => 2.6.12 (2.6.12)
    vue-template-es2015-compiler:  1.9.1 
    vue3:  1.0.0 
    vuex: ^3.6.2 => 3.6.2 (3.6.2)
    vuex-class: ^0.3.2 => 0.3.2 
  npmGlobalPackages:
    @vue/cli: 5.0.0-rc.0

**Comment by zhetengbiji** [comment]
是按照官方文档使用版本管理工具升级的依赖吗？

**Comment by breathcold** [comment]
npx @dcloudio/uvm alpha

**Comment by breathcold** [comment]
我看社区里面也有一些同学在问题，遇到了相同的问题
https://ask.dcloud.net.cn/question/153430

**Comment by breathcold** [comment]
这个包管理器指定版本的貌似很奇怪，传入一个正确的版本号，却提示版本号不对，能帮忙看看是哪里不对吗？

cold@colddeMac-mini scan-order % npx @dcloudio/uvm 2.0.1-33920220121003                              
(node:65196) UnhandledPromiseRejectionWarning: Error: Invalid version: 2.0.1-33920220121003
    at find (/Users/cold/.npm/_npx/f06a30b2e514f95e/node_modules/@dcloudio/uvm/lib/version.js:50:11)
    at start (/Users/cold/.npm/_npx/f06a30b2e514f95e/node_modules/@dcloudio/uvm/bin/index.js:16:25)
    at Object.<anonymous> (/Users/cold/.npm/_npx/f06a30b2e514f95e/node_modules/@dcloudio/uvm/bin/index.js:30:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
(Use `node --trace-warnings ...` to show where the warning was created)
(node:65196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:65196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by zhetengbiji** [comment]
> 这个包管理器指定版本的貌似很奇怪，传入一个正确的版本号，却提示版本号不对，能帮忙看看是哪里不对吗？
> 
> cold@colddeMac-mini scan-order % npx @dcloudio/uvm 2.0.1-33920220121003 (node:65196) UnhandledPromiseRejectionWarning: Error: Invalid version: 2.0.1-33920220121003 at find (/Users/cold/.npm/_npx/f06a30b2e514f95e/node_modules/@dcloudio/uvm/lib/version.js:50:11) at start (/Users/cold/.npm/_npx/f06a30b2e514f95e/node_modules/@dcloudio/uvm/bin/index.js:16:25) at Object. (/Users/cold/.npm/_npx/f06a30b2e514f95e/node_modules/@dcloudio/uvm/bin/index.js:30:1) at Module._compile (internal/modules/cjs/loader.js:1063:30) at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10) at Module.load (internal/modules/cjs/loader.js:928:32) at Function.Module._load (internal/modules/cjs/loader.js:769:14) at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12) at internal/main/run_main_module.js:17:47 (Use `node --trace-warnings ...` to show where the warning was created) (node:65196) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2) (node:65196) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

传入的是 HBuilderX 的版本号，目前不支持直接传入 CLI 的版本号，因为普通开发者不方便理解 CLI 版本号。

**Comment by zhetengbiji** [comment]
我这模拟测试未能复现问题，能否上传一个示例工程，我排查一下。

**Comment by breathcold** [comment]
好，我先试试把存量的package-lock.json删掉再升级试试，不行我再脱敏上传个示例工程

**Comment by breathcold** [comment]
npx @dcloudio/uvm 3.4.6.20220420
升级到这个版本ok了

**Comment by pcdd-group** [comment]
> npx @dcloudio/uvm 3.4.6.20220420 升级到这个版本ok了

依然报错
