### ISSUE TITLE
uni.chooseImage在安卓与鸿蒙手机系统中无法直接调起相机，出现文档选项

### ISSUE THREAD

**Issue by cyhsdcs** [dcloudio/uni-app#3867]
**问题描述**
使用uni.chooseImage并且sourceType指定为camera，打包成h5后在iOS上可以直接调起相机，但是在安卓与鸿蒙系统中就不行，会出现选择文件以上传：拍照、文件
![微信图片_20220920172252](https://user-images.githubusercontent.com/43446212/191220782-90f691bb-bf4b-46f3-bedf-05fa5da255f1.jpg)

**复现步骤**
`uni.chooseImage({
count:1,
sizeType:["compressed"],
sourceType:["camera"],
success: (res) =>{//业务逻辑},
});`

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 Android 鸿蒙

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
受限于平台浏览器或webview的实现，你使用的是Chrome还是系统浏览器？

**Comment by cyhsdcs** [comment]
你好，很高兴收到您的回复，我这边是使用App打开

**Comment by zhetengbiji** [comment]
> 你好，很高兴收到您的回复，我这边是使用App打开

uni-app做的app吗？

**Comment by cyhsdcs** [comment]
> > 你好，很高兴收到您的回复，我这边是使用App打开
> 
> uni-app做的app吗？

您好，我不知道，因为我不能接触到App的具体代码，我写的项目用npm run build之后部署到服务器上供App调用

**Comment by zhetengbiji** [comment]
> > > 你好，很高兴收到您的回复，我这边是使用App打开
> > 
> > 
> > uni-app做的app吗？
> 
> 您好，我不知道，因为我不能接触到App的具体代码，我写的项目用npm run build之后部署到服务器上供App调用

安卓上webview文件选择的功能以及具体展示的样子是App的开发人员实现的
