### ISSUE TITLE
无法创建动画 API `createAnimation` is not yet implemented

### ISSUE THREAD

**Issue by iiixxxiii** [dcloudio/uni-app#387]
**问题描述**
 
无法创建动画 API `createAnimation` is not yet implemented

**复现步骤**
                var animation = uni.createAnimation({
                    duration: 1000,
                    timingFunction: 'ease',
                })

**预期结果**
 创建 animation  对象
**实际结果**
 animation   undefined
报错
index.umd.min.js:1 [system] API `createAnimation` is not yet implemented

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [win 7]
 - HBuilderX版本 [1.9.4]
 - uni-app版本 [自带]
 - 设备信息 [谷歌浏览器]

**Comment by zhetengbiji** [comment]
<img width="923" alt="image" src="https://user-images.githubusercontent.com/6326057/57681442-48194900-7662-11e9-8af4-be6079028a64.png">

**Comment by iiixxxiii** [comment]
一套api没有通用啊,那H5的动画用什么写?

**Comment by zhetengbiji** [comment]
> 一套api没有通用啊,那H5的动画用什么写?

H5端暂未实现该API，可以在css内使用transition和animation，或者使用transition组件

**Comment by iiixxxiii** [comment]
那了不能说下怎么在h5端引入jquery,我动画用jquery写好了

**Comment by iiixxxiii** [comment]
> > 一套api没有通用啊,那H5的动画用什么写?
> 
> H5端暂未实现该API，可以在css内使用transition和animation，或者使用transition组件

那了不能说下怎么在h5端引入jquery,我动画用jquery写好了

**Comment by zhetengbiji** [comment]
> > > 一套api没有通用啊,那H5的动画用什么写?
> > 
> > 
> > H5端暂未实现该API，可以在css内使用transition和animation，或者使用transition组件
> 
> 那了不能说下怎么在h5端引入jquery,我动画用jquery写好了

uni-app在H5端除了模块化引入js外，还可以直接动态加载js（自己百度），或者在html模版里加载：https://uniapp.dcloud.io/collocation/manifest?id=h5-template

**Comment by zhetengbiji** [comment]
HBuilderX 2.1.0 版本开始已经支持

**Comment by newbeekk** [comment]
> HBuilderX 2.1.0 版本开始已经支持

请问，为什么我用的2.2.2+版本的，h5还是没有实现这个动画？

**Comment by cxytomo** [comment]
我遇到的情况是本地运行时好的，真机测试也是好的。但是打包部署后报这个错误
