### ISSUE TITLE
uniapp 做个微信小程序，不能ble广播么？是只能连接客户端吗？

### ISSUE THREAD

**Issue by bbhxwl** [dcloudio/uni-app#3871]
uniapp 做个微信小程序，不能ble广播么？是只能连接客户端吗？

**Comment by zhetengbiji** [comment]
看一下微信小程序有没有想过API，有的话可以直接用。

**Comment by bbhxwl** [comment]
> 看一下微信小程序有没有相关API，有的话可以直接用。

小程序好像有，uniapp上没看见。那也能调用 原生微信的api么。

**Comment by zhetengbiji** [comment]
> > 看一下微信小程序有没有相关API，有的话可以直接用。
> 
> 小程序好像有，uniapp上没看见。那也能调用 原生微信的api么。

可以：https://uniapp.dcloud.net.cn/api/#%E5%90%84%E7%AB%AF%E7%89%B9%E8%89%B2-api-%E8%B0%83%E7%94%A8
