### ISSUE TITLE
uniapp开发微信小程序打包后，代码安全扫描报中风险，显示未加固代码，未加固代码为app.json中的内容

### ISSUE THREAD

**Issue by MRFLLL** [dcloudio/uni-app#3872]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by StrivingRabbit** [comment]
可以参考 [代码加固](https://developers.weixin.qq.com/miniprogram/dev/devtools/code_obfuscation.html) 来操作

**Comment by MRFLLL** [comment]
但是报的这个中风险是app.json    未加固代码片段  app.json'] = { "pages": [" pages/index/index"], "subPackages": [( "root": "packages/mini/". "pages": ["pages/index/index/未加固的JS代码可读性高，直接导致客户端逻辑暴露，攻击者分析后可修改代码逻辑，实现如客户端限制绕过、主动构造URL签名等功能，更容易、更精准的实现攻击测试场景构造

**Comment by StrivingRabbit** [comment]
> 但是报的这个中风险是app.json 未加固代码片段 app.json'] = { "pages": [" pages/index/index"], "subPackages": [( "root": "packages/mini/". "pages": ["pages/index/index/未加固的JS代码可读性高，直接导致客户端逻辑暴露，攻击者分析后可修改代码逻辑，实现如客户端限制绕过、主动构造URL签名等功能，更容易、更精准的实现攻击测试场景构造

可以在微信开发者社区反馈一下，或者看一下微信的文档
