### ISSUE TITLE
static目录条件编译不生效

### ISSUE THREAD

**Issue by rain-off** [dcloudio/uni-app#3874]
**问题描述**
static目录条件编译不生效

**复现步骤**
1.  static中包含app-plus目录
2. 编译微信小程序npm run build:mp-weixin
3. 微信小程序中会把app-plus目录也编译进去

**预期结果**
编译完的小程序不应该存在app-plus目录

**实际结果**
app-plus目录被编译进微信小程序

**Comment by StrivingRabbit** [comment]
vue2 还是 vue3？

**Comment by rain-off** [comment]
> vue2 还是 vue3？

vue2，vue/cli@5 webpack5

**Comment by StrivingRabbit** [comment]
上传一个你使用有问题的示例
