### ISSUE TITLE
实在不想吐槽了，你们的开发都是二手的吧，每次升级一大顿问题。。。

### ISSUE THREAD

**Issue by githublyp** [dcloudio/uni-app#3877]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
![image](https://user-images.githubusercontent.com/12792918/191750515-bf590cde-8910-4230-aa76-0c20f7d586ed.png)
@hbcui1984 
**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by githublyp** [comment]
> 
拉个项目跑个app的你们就知道了。。。话说你们的开发真是爽，都不用自测

**Comment by zhetengbiji** [comment]
> > 
> 
> 拉个项目跑个app的你们就知道了。。。话说你们的开发真是爽，都不用自测

反馈平台是App是吧，版本也提供一下

**Comment by githublyp** [comment]
3.6.3

**Comment by zhetengbiji** [comment]
> 3.6.3

HBuilderX创建的项目还是CLI创建的项目？

**Comment by githublyp** [comment]
cli创建的再HB运行，前两天还是好的，昨天刚升级了917就成这样了。。。

**Comment by zhetengbiji** [comment]
> 

```npm run info``` 的结果提供一下，是使用 ```npx @dcloudio/uvm``` 我们提供的这个版本管理工具升级的依赖吗？

**Comment by githublyp** [comment]
uni-app v3.6.3
uni-app cli v2.0.1-36320220917001

Environment Info:

  System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) 
  Binaries:
    Node: 16.3.0 -
    Yarn: 1.22.10 - 
    npm: 7.21.1 - 
  Browsers:
    Edge: 44.22000.120.0
  npmPackages:
    @dcloudio/types: * => 3.0.15
    @dcloudio/uni-app-plus: latest => 2.0.1-36320220917001
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-automator: latest => 2.0.1-36320220917001
    @dcloudio/uni-cli-i18n: ^2.0.1-34920220609002 => 2.0.1-36320220917001
    @dcloudio/uni-cli-shared: latest => 2.0.1-36320220917001
    @dcloudio/uni-h5: latest => 2.0.1-36320220917001
    @dcloudio/uni-helper-json: * => 1.0.13
    @dcloudio/uni-i18n: latest => 2.0.1-36320220917001
    @dcloudio/uni-migration: latest => 2.0.1-36320220917001
    @dcloudio/uni-mp-360: latest => 2.0.1-36320220917001
    @dcloudio/uni-mp-alipay: latest => 2.0.1-36320220917001
    @dcloudio/uni-mp-baidu: latest => 2.0.1-36320220917001
    @dcloudio/uni-mp-jd: latest => 2.0.1-36320220917001
    @dcloudio/uni-mp-kuaishou: latest => 2.0.1-36320220917001
    @dcloudio/uni-mp-lark: latest => 2.0.1-36320220917001
    @dcloudio/uni-mp-qq: latest => 2.0.1-36320220917001
    @dcloudio/uni-mp-toutiao: latest => 2.0.1-36320220917001
    @dcloudio/uni-mp-vue: latest => 2.0.1-36320220917001
    @dcloudio/uni-mp-weixin: latest => 2.0.1-36320220917001
    @dcloudio/uni-mp-xhs: latest => 2.0.1-36320220917001
    @dcloudio/uni-quickapp-native: latest => 2.0.1-36320220917001
    @dcloudio/uni-quickapp-webview: latest => 2.0.1-36320220917001
    @dcloudio/uni-stat: latest => 2.0.1-36320220917001
    @dcloudio/uni-template-compiler: latest => 2.0.1-36320220917001
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 2.0.1-36320220917001
    @dcloudio/vue-cli-plugin-uni: latest => 2.0.1-36320220917001
    @dcloudio/vue-cli-plugin-uni-optimize: latest => 2.0.1-36320220917001
    @dcloudio/webpack-uni-mp-loader: latest => 2.0.1-36320220917001
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: latest => 2.0.1-36320220917001
    @hap-toolkit/dsl-vue:  0.6.13
    @vue/babel-helper-vue-jsx-merge-props:  1.4.0
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.1.1
    @vue/babel-plugin-transform-vue-jsx:  1.4.0
    @vue/babel-preset-app:  4.5.19
    @vue/babel-preset-jsx:  1.4.0
    @vue/babel-sugar-composition-api-inject-h:  1.4.0
    @vue/babel-sugar-composition-api-render-instance:  1.4.0
    @vue/babel-sugar-functional-vue:  1.4.0
    @vue/babel-sugar-inject-h:  1.4.0
    @vue/babel-sugar-v-model:  1.4.0
    @vue/babel-sugar-v-on:  1.4.0
    @vue/cli-overlay:  4.5.19
    @vue/cli-plugin-babel: ~4.5.18 => 4.5.19
    @vue/cli-plugin-router:  4.5.19
    @vue/cli-plugin-vuex:  4.5.19
    @vue/cli-service: ~4.5.18 => 4.5.19
    @vue/cli-shared-utils:  4.5.19
    @vue/compiler-sfc:  2.7.10
    @vue/component-compiler-utils:  3.3.0 (3.3.0)
    @vue/devtools-api:  6.0.0-beta.15
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.2
    @vue/shared: ^3.0.0 => 3.2.39
    @vue/web-component-wrapper:  1.3.0
    eslint-plugin-vue: ^5.2.3 => 5.2.3
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.11 => 2.7.10
    vue-eslint-parser:  5.0.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.10.0 (16.8.3, 15.10.0)
    vue-monaco-editor: 0.0.19 => 0.0.19
    vue-router:  3.0.1
    vue-style-loader:  4.1.3 (4.1.3)
    vue-template-compiler: ^2.6.11 => 2.7.10 (2.7.10)
    vue-template-es2015-compiler:  1.9.1
    vue3:  1.0.0
    vuex: ^3.2.0 => 3.6.2 (3.6.2)
  npmGlobalPackages:
    @vue/cli: Not Found

**Comment by zhetengbiji** [comment]
是使用 ```npx @dcloudio/uvm``` 我们提供的这个版本管理工具升级的依赖吗？

**Comment by Michael-py001** [comment]
要提bug你就详细描述点，就一个截图谁知道你想说什么

**Comment by githublyp** [comment]
我自己解决了，不麻烦大佬了

**Comment by zhetengbiji** [comment]
> 我自己解决了，不麻烦大佬了

是否可以详细说一下，对其他人也有帮助。
