### ISSUE TITLE
qq小程序相同代码禁止发布，有这方面的解决方案吗？

### ISSUE THREAD

**Issue by social-uni** [dcloudio/uni-app#3882]
![e60ceb5da9051e007937906aa0165ba](https://user-images.githubusercontent.com/14007972/191891943-527e78a7-1322-4c9d-bc6e-551c5e99a588.jpg)

我的两个小程序用的同一套代码，根据后端配置不一样返回不同的内容，展示不同的圈子和内容。

但是因为前端代码一样，qq不让发布，请问有解决办法吗？

uniapp有没有提供什么打包配置，可以使同一套代码，打包出来的结果是不同的东西啊

**Comment by zhetengbiji** [comment]
如果是代码判定，自行增加混淆插件即可。

如果，不是代码层面，而是通过逻辑近似判定，请自行遵守平台规则。
