### ISSUE TITLE
【BUG】Vue3的 v-bind rpx 在H5失效

### ISSUE THREAD

**Issue by Michael-py001** [dcloudio/uni-app#3884]
**问题描述**
最小demo代码：
```html
<script setup>
import {ref} from 'vue'
 const blockLength = ref('120rpx')
</script>
<style lang="scss" scoped>
  .Title {
    font-size: 40rpx;
    font-weight: bold;
    color: #333;
    position: relative;
    z-index: 1;
    margin-bottom: 36rpx;
    &::before {
      content: '';
      position: absolute;
      bottom: -8rpx;
      left: -5px;
      width: v-bind(blockLength);
      height: 16rpx;
      background-color: #194ce5;
      z-index: -1;
      opacity: .9;
      border-radius: 8rpx;
    }
  }
</style>
```
![image](https://user-images.githubusercontent.com/60598432/191914683-22fae3a0-10c7-459b-9b2d-ec78cb1b649a.png)
以下是H5：
![image](https://user-images.githubusercontent.com/60598432/191915211-e7d51c38-4ead-44df-9183-a3d9abab2a3b.png)
以下是微信：
![image](https://user-images.githubusercontent.com/60598432/191915351-7c80d430-26df-407e-8a55-6bc6ca961553.png)

为什么Vu3自带的v-bind css 都被你们阉割了啊，小程序能编译，为什么h5原生的就给阉割了呢？用uniapp迟早都被气死

**系统信息:**
 - 发行平台: [ 微信小程序、H5平台]
 - HBuilderX版本 [3.6.3.20220919-alpha]

**Comment by fxy060608** [comment]
v-bind暂未处理rpx，可以先将rpx换成px等单位

**Comment by Michael-py001** [comment]
这。。。文档也不说明一下，Vue3出这么久了居然也没人提过，你们知道了也不修复，唉，真的无语。。
