### ISSUE TITLE
uniapp未支持vite3，peer vite@"2.9.14" from @dcloudio/vite-plugin-uni@3.0.0-alpha-3060320220917001

### ISSUE THREAD

**Issue by social-uni** [dcloudio/uni-app#3885]
npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project

package.json 中的vite为 2.9.14

将vite版本修改为 3.1.3

运行npm，提示错误

npm ERR! Could not resolve dependency:
npm ERR! peer vite@"2.9.14" from @dcloudio/vite-plugin-uni@3.0.0-alpha-3060320220917001

**Comment by social-uni** [comment]
https://github.com/dcloudio/uni-app/issues/3699

**Comment by ModyQyW** [comment]
试试用 `npm install --legacy-peer-deps`

**Comment by fxy060608** [comment]
可以升级至：3.0.0-alpha-3060420220922004

**Comment by social-uni** [comment]
> 可以升级至：3.0.0-alpha-3060420220922004

依旧存在此问题的

**Comment by social-uni** [comment]
> 试试用 `npm install --legacy-peer-deps`

这个方式可以解决，谢谢

**Comment by fxy060608** [comment]
> > 可以升级至：3.0.0-alpha-3060420220922004
> 
> 依旧存在此问题的

该版本对vite的依赖，已提升至：3.1.3

**Comment by social-uni** [comment]
> > > 可以升级至：3.0.0-alpha-3060420220922004
> > 
> > 
> > 依旧存在此问题的
> 
> 该版本对vite的依赖，已提升至：3.1.3

sorry，我看的3.0.0-alpha-3060420220922001

没想到后面的小版本还有变化
