### ISSUE TITLE
急急急！  vue3 作用域插槽传递 在wx小程序下异常

### ISSUE THREAD

**Issue by leftScience** [dcloudio/uni-app#3886]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
vue3+vite 在h5页面下正常，在wx下作用域插槽传递就不显示了
**复现步骤**
[复现问题的步骤]
[https://gitee.com/hanlin_wang0606/uni-vue3-bug.git](url)

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
可以在最外层插槽里获得数据
**实际结果**
[这里请贴上你的报错截图或文字]
在h5可以，但是微信不行，插槽不显示

**系统信息:**
 - 发行平台: h5 微信小程序
 - 操作系统:macos
 - uni-app版本 官方提供的脚手架

**补充信息**
谢谢官方大佬了，这个问题急急急，请求组织支援

**Comment by fxy060608** [comment]
cli可以更新至：3.0.0-alpha-3060420220922006
