### ISSUE TITLE
PostMessage 在支付宝小程序内无法正常回调

### ISSUE THREAD

**Issue by neo-z** [dcloudio/uni-app#389]
**问题描述**
官网Demo中的，postMessage 内嵌网页与小程序页面通信异常，无反应。

**复现步骤**
[复现问题的步骤]
1.  启动 官方Demo
2. 点击 postMessage
3. 页面无法任何响应

**Comment by zhetengbiji** [comment]
已修复，更新 HBuilderX 到 2.0.3 alpha 即可
