### ISSUE TITLE
没有返回ref的值

### ISSUE THREAD

**Issue by xcplovelhq** [dcloudio/uni-app#3896]
**问题描述**
^3.0.0-alpha-3041020220516002
这个版本后面的ref都没有值了，我直接拿uni-app的demo发现也获取不到

**复现步骤**
<img width="587" alt="image" src="https://user-images.githubusercontent.com/20986739/193079021-3f4e477d-20a3-45d1-8ed3-d99883323d5d.png">

**预期结果**
可以获取到ref的值
**实际结果**
![image](https://user-images.githubusercontent.com/20986739/193078018-3da2b7b2-f55e-4ee5-8092-d93e5658f24a.png)

**系统信息:**
 - 发行平台:  微信小程序
 - uni-app版本3.0.0-alpha-3060420220922001

**Comment by fxy060608** [comment]
小程序平台只有自定义组件支持ref，内置组件不支持，以前的版本也不支持

**Comment by xcplovelhq** [comment]
> 小程序平台只有自定义组件支持ref，内置组件不支持，以前的版本也不支持

我发那个版本号的确是可以获取到uni-popup设置ref的值，更新了版本之后就获取不了了

**Comment by fxy060608** [comment]
> > 小程序平台只有自定义组件支持ref，内置组件不支持，以前的版本也不支持
> 
> 我发那个版本号的确是可以获取到uni-popup设置ref的值，更新了版本之后就获取不了了

你贴的代码是image组件ref，这个是获取不到的，如果是uni-popup，可以发测试工程

**Comment by xcplovelhq** [comment]
大概找到问题的，我这边3.0.0-alpha-3060420220922001这个版本没有把uni_modules打包进去的，升级到3.0.0-alpha-3060320220917001这个版本就暂时没问题
