### ISSUE TITLE
全局样式没有按使用过滤正常吗

### ISSUE THREAD

**Issue by itmanyong** [dcloudio/uni-app#3898]
**问题描述**
uni-vite-vue3创建的项目全局导入的css样式打包时未进行过滤,未使用的样式依然灰被copy到产物中,这是正常的吗?

**复现步骤**
[复现问题的步骤]
1. 使用 npx degit dcloudio/uni-preset-vue#vite my-vue3-project 的工程
2. src目录下App.vue中style内导入外部一个css文件
3. 使用 npm run build:wp-weixin进行构建
4. 查看dist/build/mp-weixin/app.wxss文件

**预期结果**
未使用的样式被过滤掉,不出现在构建的产物之中

**实际结果**
只要导入的样式全部被copy到了产物之中

**系统信息:**
 - 微信小程序
 - win10
 - HbuilderX正式版3.6.4
 - 用Vue-cli创建/运行项目，直接拉取uni-preset-vue#vite最新版本
 - 无需设备

**Comment by fxy060608** [comment]
目前不会对css样式要摇树优化，只要导入就会被构建，css样式很难做到精确的摇树，很多场景下会在模板，js中动态拼装css样式名
