### ISSUE TITLE
小程序转app，app不需要获取login，小程序必须要，怎么解决

### ISSUE THREAD

**Issue by weiwei02580** [dcloudio/uni-app#39]
各位大佬，求指点，怎么兼顾，小程序获取，app不获取呢

**Comment by hbcui1984** [comment]
通过条件编译实现
`
// #ifdef MP-WEIXIN
uni.login({
  provider: 'weixin',
  success: function (loginRes) {
    console.log(loginRes.authResult);
  }
});
// #endif
`

**Comment by udbmnm** [comment]
条件编译
