### ISSUE TITLE
h5 在 IOS 下会使得引入 vant 组件滑动不了

### ISSUE THREAD

**Issue by Zclhlmgqzc** [dcloudio/uni-app#390]
**问题描述**
普通 vue 项目是正常的，但是在 uni-app 里不正常
h5 在 IOS (Safari)下会使得引入 vant 组件滑动不了
Chrome 是正常的

**复现步骤**

```js
import Vue from 'vue'
import { Picker } from 'vant'
Vue.use(Picker)
```
```html
<template>
  <div>
    <van-picker :columns="columns" />
  </div>
</template>
<script>
export default {
  data() {
    return {
      columns: ['杭州', '宁波', '温州', '嘉兴', '湖州']
    }
  }
}
</script>
```
**预期结果**
Safari 跟 Chrome 一样能滑动

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 iOS
 - uni-app版本 最新
 - 设备信息 iPhone8

**补充信息**
uni-app 针对 ios 做了什么优化导致的

**Comment by zhetengbiji** [comment]
测试未复现，使用新版HBuilderX测试一下，如果仍有问题，提供一下测试链接或者工程

**Comment by Wangyaqi** [comment]
长时间未回复，暂时关闭
