### ISSUE TITLE
 setup script语法 下 onShareAppMessage不生效

### ISSUE THREAD

**Issue by xuzhaohang** [dcloudio/uni-app#3901]
<script lang="ts">
export default {
	// 主动定义onShareAppMessage，通知小程序显示分享菜单
	onShareAppMessage() { }
}
</script>
<script setup lang="ts">
import { ref } from 'vue'
import { onShareAppMessage } from '@dcloudio/uni-app'
onShareAppMessage(() => {
  return { title: 'hello' }
})
</script>

**Comment by xuzhaohang** [comment]
`<script lang="ts">
export default {
	// 主动定义onShareAppMessage，通知小程序显示分享菜单
	onShareAppMessage() { }
}
</script>
<script setup lang="ts">
import { ref } from 'vue'
import { onShareAppMessage } from '@dcloudio/uni-app'
onShareAppMessage(() => {
  return { title: 'hello' }
})
</script>`

**Comment by xuzhaohang** [comment]
这个写法无效

**Comment by steavengong** [comment]
同问

**Comment by SongBana** [comment]
> `<script lang="ts"> export default { // 主动定义onShareAppMessage，通知小程序显示分享菜单 onShareAppMessage() { } } </script>
> 
> <script setup lang="ts"> import { ref } from 'vue' import { onShareAppMessage } from '@dcloudio/uni-app' onShareAppMessage(() => { return { title: 'hello' } }) </script>`

按照这个配置的无效 3.0.0-3090620231104002
