### ISSUE TITLE
Vue3/vite-ts: h5 每次回到 tabBar 首页， <script setup lang="ts"> 被调用

### ISSUE THREAD

**Issue by lin09** [dcloudio/uni-app#3902]
**问题描述**
h5 每次回到 tabBar 首页
1. 首页的 `<script setup lang="ts">`  都会被调用
2. 包括首页引用到的组件，组件里的 `<script setup lang="ts">`  也都会被调用
3. navigationBar 的返回除外

**复现步骤**
[复现问题的步骤]
1.  创建项目 `npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project` ，安装依赖
5. 在项目添加 a 、 b 、 c 三个页面，index 、 a 和 b 三个页面设置为 tabBar 页，index 页为首页
6. 在 index 页添加打印 `<script setup lang="ts"> console.log('index page setup') </script>`
7. 在 index 面添加跳转 `<navigator url="/pages/c/index">c page</navigator>`
8. 在 c 面添加跳转 `<navigator url="/pages/index/index" open-type="switchTab">index page</navigator>`
9. 运行项目 `yarn dev:h5`
10. 浏览首页，首页 `<script setup lang="ts">` 被调用
11. 点击底部 tabBar a 页，再点击首页，首页 `<script setup lang="ts">` 又被调用
12. 在首页点击 ’c page‘ 跳转 c 页，再点击 ’index page‘ 跳转回首页，首页 `<script setup lang="ts">` 又被调用

[代码](https://github.com/lin09/nui-vite-ts-h5-tabbar-home-bug)

**预期结果**
首次进 tabBar 首页，调用 `<script setup lang="ts">`，之后每次回到首页，不会再调用 `<script setup lang="ts">`

**实际结果**
每次回到 tabBar 首页，都调用了 `<script setup lang="ts">` 

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 win10 
 - uni-app 3.0.0-alpha-3060420220922001
 - yarn dev:h5
 - 设备信息 Chrome 106.0.5249.103

**Comment by StrivingRabbit** [comment]
https://ask.dcloud.net.cn/question/154498

**Comment by StrivingRabbit** [comment]
alpha 3.6.7 已修复
