### ISSUE TITLE
最新版分享失效

### ISSUE THREAD

**Issue by ringgoyao** [dcloudio/uni-app#3905]
**问题描述**
   版本号：3.0.0-alpha-3060120220907002   小程序分享正常
  升级至    3.0.0-alpha-3060420220922006   小程序分享失效

Vite+Vue3 小程序

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
根据自己不同版本的测试，vite大版本升级，是否有部分功能未处理好？

**Comment by StrivingRabbit** [comment]
哪家小程序？

**Comment by zhetengbiji** [comment]
之前版本是否正常？

目前采用静态分析，生命周期写法存在一些局限性。
尝试将相关逻辑写在页面文件内，或使用 defineComponent 单独定义。

**Comment by fxy060608** [comment]
已修复：3.0.0-alpha-3060720221018001
