### ISSUE TITLE
renderjs 从视图层传一个大对象到逻辑层时，数据接收不到，并且app会崩溃

### ISSUE THREAD

**Issue by zhangzhi93** [dcloudio/uni-app#3906]
**问题描述**
renderjs 从视图层传一个大对象到逻辑层时，数据接收不到，并且app会崩溃

**复现步骤**
```this.$ownerInstance.callMethod('receiveVolumeData', { data })```
其中data是一个大对象
**预期结果**
可以接收到数据，不会崩溃，或者有其他方式

**实际结果**
接收不到数据，app会崩溃

**系统信息:**
uniapp开发android应用，使用了vtk.js

**补充信息**
数据量可能太大，传不过去？最小的数据也在十几兆

**Comment by zhetengbiji** [comment]
建议优化传输方式，比如压缩数据以及分段分块

**Comment by zhangzhi93** [comment]
> 建议优化传输方式，比如压缩数据以及分段分块

![image](https://user-images.githubusercontent.com/16435301/194744340-24e92330-d66b-41e7-b4d7-4d3a8bc32180.png)
传的是一个这样的大对象

**Comment by zhetengbiji** [comment]
> > 建议优化传输方式，比如压缩数据以及分段分块
> 
> ![image](https://user-images.githubusercontent.com/16435301/194744340-24e92330-d66b-41e7-b4d7-4d3a8bc32180.png) 传的是一个这样的大对象

这些方法本来也是传不过去的，能传输的只有可以json序列化的纯数据类型

**Comment by zhangzhi93** [comment]
> > > 建议优化传输方式，比如压缩数据以及分段分块
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/16435301/194744340-24e92330-d66b-41e7-b4d7-4d3a8bc32180.png) 传的是一个这样的大对象
> 
> 这些方法本来也是传不过去的，能传输的只有可以json序列化的纯数据类型

有别的办法吗，生成的这个对象需要vtk，不能写在逻辑层，这个对象是渲染体图象的完备数据。
