### ISSUE TITLE
打包成普通h5，并嵌入到android app中，uni.chooseImage点击无效，无法弹出图片选择器，在浏览器中是正常的

### ISSUE THREAD

**Issue by wangmhaha** [dcloudio/uni-app#3907]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
uni-app 打包为h5， 并嵌入app中，使用uni.chooseImage这个API选择图片，android 端点击后无法打开图片选择器。试过nvue页面同样也不可以。点击无反应。
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX 版本3.6.0.20220901-alpha
 - uni-app版本 通过HbuilderX创建
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by DashSake** [comment]
打扰，大佬，请问这个是怎么解决的，上面那个【文章】的链接打不开了🙏
