### ISSUE TITLE
video show-progress 不生效

### ISSUE THREAD

**Issue by KeJunMao** [dcloudio/uni-app#3908]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
video show-progress 不生效
**复现步骤**
[复现问题的步骤]
```html
    <video
      :controls="true"
      :show-play-btn="false"
      :show-progress="false"
      :show-fullscreen-btn="false"
      :enable-progress-gesture="false"
      src="https://interactive-examples.mdn.mozilla.net/media/cc0-videos/flower.webm"
    ></video>
```

**预期结果**
不显示进度条
**实际结果**
进度条还在，其他的可以

**系统信息:**
 - 发行平台: [H5平台 5+ App]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
- vite + uniapp

**补充信息**
源码里貌似没有对这个做判断

**Comment by StrivingRabbit** [comment]
运行在什么平台？

**Comment by KeJunMao** [comment]
h5无效，app有效

**Comment by StrivingRabbit** [comment]
[20221201.zip](https://github.com/dcloudio/uni-app/files/10140020/20221201.zip)

临时解决方案：请将附件中的文件分别替换至 
- `vue3`：`HX 根目录/plugins/uniapp-cli-vite/node_modules/@dcloudio/uni-h5/dist`
- `vue2`：`HX 根目录//plugins/uniapp-cli/node_modules/@dcloudio/uni-h5/dist`
