### ISSUE TITLE
H5 build打包后,部分内置组件编译不完整

### ISSUE THREAD

**Issue by h-mo-pixel** [dcloudio/uni-app#3909]
**问题描述**
H5 build打包后,部分内置组件编译不完整, 开发环境没问题
例: image内置组件, h5打包编译后,图片不显示

**复现步骤**
官方示例创建项目,代码无任何更改:
1. cli 创建 vue3 的 uni-app ts 项目
2. 运行run build:h5

**预期结果**
dev开发环境, 能显示图片或logo
image内置组件编译后有div,img 标签,能显示图片
![1665369454074](https://user-images.githubusercontent.com/44894251/194793319-cb63ca6a-e6bd-4855-82ae-f5a5b387bf79.jpg)

**实际结果**
build打包后, 不能能显示图片或logo
image内置组件编译后没有div,img 标签,不能显示图片
![1665369522693](https://user-images.githubusercontent.com/44894251/194793326-fc42c043-dbb8-441c-a40f-5690cdfb8dff.jpg)

**系统信息:**
 - 发行平台: [ H5平台 ]
 - 操作系统 [ 浏览器 ]
 - uni-app版本 [ v3.0.0-alpha-3060420220922006, cli创建/运行打包，无报错]

**补充信息**
还有项目中view内置组件也有错误, 编译后的div,img标签是被你们吃了吗?

**Comment by fxy060608** [comment]
已修复，更新至：3.0.0-alpha-3060420220922008
