### ISSUE TITLE
editor组件的bindstatuschange没有返回值

### ISSUE THREAD

**Issue by HoldSkill** [dcloudio/uni-app#391]
**问题描述**
editor组件的bindstatuschange没有返回值

**复现步骤**
[复现问题的步骤]
@statuschange="abc"

abc(e){
 console.log(e);//e为undefined
}
Hbuilder X 1.9.8.20190518
微信开发者工具 2.7.0 SDK

**Comment by zhetengbiji** [comment]
更新 HBuilderX 到 2.0.0 及以上版本
