### ISSUE TITLE
关于uniapp版本号

### ISSUE THREAD

**Issue by wangjieCode** [dcloudio/uni-app#3910]
uniapp的版本号是我见过最奇怪的，大佬们有对版本号说明的文档么，经常搞不清楚

**Comment by zhetengbiji** [comment]
由于历史原因，依赖的版本构成较复杂，普通开发者理解较难，一般不再建议手动处理依赖，推荐使用版本管理工具进行管理：https://uniapp.dcloud.net.cn/quickstart-cli.html#cliversion

**Comment by wangjieCode** [comment]
有计划改为主流的npm version么

**Comment by zhetengbiji** [comment]
> 有计划改为主流的npm version么

计划是有的，不过即使依赖版本名称风格更高，普通开发者也很难手动处理依赖，推荐使用版本管理工具进行管理：https://uniapp.dcloud.net.cn/quickstart-cli.html#cliversion

**Comment by ModyQyW** [comment]
以下属于个人猜测。

<img width="790" alt="image" src="https://user-images.githubusercontent.com/31850793/194875246-9b1a0383-3047-4d74-8856-19113cc7748f.png">

【Vue 适用版本】.y.z-【HBuilderX 版本】【HBuilderX 版本发布时对应四位年份+两位月份+两位日期+三位发版号】

2.0.1-36420220922001：Vue 2 使用，对应 HBuilderX 3.6.4，2022.09.22 第一次发布，001 表示没有在 2022.09.22 发的第一版基础上做修改。

3.0.0-alpha-3060420220922008：Vue 3 使用，对应 3.6.4，2022.09.22 第一次发布，008 表示在 2022.09.22  发的第一版基础上修改发版 7 次。
