### ISSUE TITLE
使用vue3 + 字节自定义组件项目编译异常

### ISSUE THREAD

**Issue by pipione** [dcloudio/uni-app#3915]
**问题描述**
使用vue3 + 字节自定义组件项目编译异常 

**复现步骤**

启动项目就会报错
[miniapp-v4-demo-uniapp.zip](https://github.com/dcloudio/uni-app/files/9750878/miniapp-v4-demo-uniapp.zip)

**预期结果**

正常显示
**实际结果**

<img width="699" alt="image" src="https://user-images.githubusercontent.com/46072182/194991905-ccddcf6c-44c4-4307-8a2f-c353c43c1e43.png">

**系统信息:**
 - 发行平台: 字节小程序
 - 操作系统 macos

**补充信息**

使用vue2可以运行，使用vue3就报错
<img width="617" alt="image" src="https://user-images.githubusercontent.com/46072182/194992043-37130714-772d-49b3-8923-b1ae39882c06.png">

**Comment by fxy060608** [comment]
临时解决方案：Component定义组件时，声明一个lifetimes:{}
