### ISSUE TITLE
vue3 使用字节小程序插件异常。

### ISSUE THREAD

**Issue by pipione** [dcloudio/uni-app#3917]
**问题描述**
vue3 使用字节小程序插件异常。 错误信息如下 
<img width="627" alt="image" src="https://user-images.githubusercontent.com/46072182/195055551-49e9eb2c-f96f-4087-98f2-a9ada68e951e.png">

**复现步骤**
运行提供的代码即可复现
[miniapp-v4-demo-uniapp.zip](https://github.com/dcloudio/uni-app/files/9753710/miniapp-v4-demo-uniapp.zip)

**预期结果**
<img width="309" alt="image" src="https://user-images.githubusercontent.com/46072182/195055795-1a00d9b4-2924-410d-a9d0-ae58173dacbc.png">

**实际结果**
<img width="679" alt="image" src="https://user-images.githubusercontent.com/46072182/195056039-34c01aa4-6510-4430-b3e3-03a7c91506db.png">

**系统信息:**
 - 发行平台: 字节小程序
 - 操作系统 Macos
 - HBuilderX版本  3.6.4.20220922

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
感觉类似于这个问题 https://github.com/dcloudio/uni-app/issues/3915

**Comment by pipione** [comment]
@fxy060608  可以再帮忙看下这个问题吗？ 感觉和它是一类问题 #3915

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/blob/next/packages/uni-mp-toutiao/dist/uni.mp.esm.js
可以把这个文件的内容，覆盖：
HBuilderX/plugins/uniapp-cli-vite/node_modules/@dcloudio/uni-mp-toutiao/dist/uni.mp.esm.js

**Comment by pipione** [comment]
> 

谢谢你，它好了。

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/3918
