### ISSUE TITLE
无法读取字节小程序的配置， 字节小程序有的配置需要配置在app.js

### ISSUE THREAD

**Issue by pipione** [dcloudio/uni-app#3919]
**问题描述**
无法读取字节小程序的配置， 字节小程序有的配置需要配置在app.js

**复现步骤**

https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/component/industry/trading-system/guide
<img width="523" alt="image" src="https://user-images.githubusercontent.com/46072182/195275976-67e106d0-6093-4138-99e5-060b61350f99.png">

上面是官方要求的配置，我写在app.vue 编译出来是这样的 
<img width="769" alt="image" src="https://user-images.githubusercontent.com/46072182/195276267-3b1ade05-2192-43a0-af2f-f3a7f55d249b.png">

**预期结果**
可以正确兼容字节小程序

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台:  字节小程序
 - 操作系统 Macos

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
感觉是uniapp的兼容问题

**Comment by pipione** [comment]
继续打扰一下你， 可以帮忙分析它的原因吗？ 我需要如何处理呢 @fxy060608

**Comment by pipione** [comment]
<img width="796" alt="image" src="https://user-images.githubusercontent.com/46072182/195294355-c0c339e3-d407-4455-978c-02a35e32916a.png">
最终，我使用了这种方式解决了我的问题，但我还是希望官方可以支持它。

**Comment by fxy060608** [comment]
> <img alt="image" width="796" src="https://user-images.githubusercontent.com/46072182/195294355-c0c339e3-d407-4455-978c-02a35e32916a.png">
> 
> 最终，我使用了这种方式解决了我的问题，但我还是希望官方可以支持它。

把这个两个方法，定义到 App.vue 的 methods 中试试
