### ISSUE TITLE
最近想用uni-app做项目， 但是问题太多了，社区生态也不太成熟， 建议官方有人能协助解答问题啊！

### ISSUE THREAD

**Issue by Mr-Kai** [dcloudio/uni-app#392]
最近想用uni-app做项目， 但是问题太多了，社区生态也不太成熟， 有点不敢用了， 一些关键性的问题， 建议官方有人能协助解答问题啊！

**Comment by wanganxp** [comment]
uni-app社区生态很成熟啊，毕竟几十万人在用的产品。这里是社区地址：https://ask.dcloud.net.cn/explore/
