### ISSUE TITLE
引入支付宝官方行业营销插件，编译后报错

### ISSUE THREAD

**Issue by milo-wjh** [dcloudio/uni-app#3920]
vue-cli构建
版本 2.0.1-33520211229002
对接支付宝官方行业营销插件的时候，开启component2，编译后开发工具报错
![image](https://user-images.githubusercontent.com/20457324/195300744-b602b4ce-4d93-4d80-b224-9905ecb1ed87.png)
引用是正常，断点发现
![image](https://user-images.githubusercontent.com/20457324/195301203-be153360-ea87-4b32-861a-46f5143527bc.png)
是否有哪个版本修复了？

**Comment by zhetengbiji** [comment]
3.4.4 以上修复的，简易执行 ```npx @dcloudio/uvm``` 升级到最新正式版

**Comment by milo-wjh** [comment]
收到谢谢
