### ISSUE TITLE
vue3 小程序scrollview  @dragging 失效问题

### ISSUE THREAD

**Issue by lxfljw** [dcloudio/uni-app#3921]
**问题描述**
开发模式下，scrollview 组件的事件 `@dragging="handleDragging"`，会被编译成 `binddragging="{{ j }}"`，但是拖拽并未生效

**复现步骤**
```html
<scroll-view @dragging="handleDragging"></scroll-view>
```

```ts
handleDragging(e) {
  console.log(e)
}
```

**预期结果**
handleDragging 函数触发

**实际结果**
handleDragging 函数无效，实测vue2模板下有效，本次是从 vue2模板升级到vue3模板出现的问题

**系统信息:**
 与系统无关

**备注**
`所有注册的拖拽事件都有问题`

**Comment by fxy060608** [comment]
HBuilderX Alpha 3.6.7 已修复

**Comment by lxfljw** [comment]
> HBuilderX Alpha 3.6.7 已修复

感谢回复，请问 cli编译 有没有修复
