### ISSUE TITLE
【Bug】 Vue3 发行为混合分包，返回页面时报错 $destroyComponentFn is not a function

### ISSUE THREAD

**Issue by lcybb** [dcloudio/uni-app#3923]
**问题描述**
主包使用的是 vue2 开发
混合分包使用 vue3 开发

当主包为 vue2 发行，vue3 发行为混合分包，组合一起发布时 vue3 中的页面返回时出现报错：TypeError: $destroyComponentFn is not a function

**复现步骤**
[复现问题的步骤]
1. 跳转到 vue3 的页面
2. 返回
3. 出现报错

**预期结果**
无报错

**实际结果**
TypeError: $destroyComponentFn is not a function

**系统信息:**
 - 发行平台: 微信小程序
 - uni-app版本: 3.0.0-alpha-3060420220922005
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
(https://github.com/dcloudio/uni-app/commit/44ddf729bae646495e906bb4c0da4cfc9e9b5743#diff-a224c4534d7884c88ec35accd246348ea88bc52f273bfe612238a34e6721077f)  此提交修复过相似问题

**Comment by fxy060608** [comment]
目前不支持这么混合使用

**Comment by lcybb** [comment]
> 目前不支持这么混合使用

除了 $vm 之外还会有其他的影响吗？新功能想使用vue3开发

**Comment by fxy060608** [comment]
> > 目前不支持这么混合使用
> 
> 除了 $vm 之外还会有其他的影响吗？新功能想使用vue3开发

不太确定，没有测试过，目前应该是跑不通的。

**Comment by lcybb** [comment]
> 

因为除了当前 issue，我目前暂时还没遇到其他问题

**Comment by lcybb** [comment]
> > > 目前不支持这么混合使用
> > 
> > 
> > 除了 $vm 之外还会有其他的影响吗？新功能想使用vue3开发
> 
> 不太确定，没有测试过，目前应该是跑不通的。


因为除了当前 issue，我目前暂时还没遇到其他问题

**Comment by fxy060608** [comment]
> > > > 目前不支持这么混合使用
> > > 
> > > 
> > > 除了 $vm 之外还会有其他的影响吗？新功能想使用vue3开发
> > 
> > 
> > 不太确定，没有测试过，目前应该是跑不通的。
> 
> 因为除了当前 issue，我目前暂时还没遇到其他问题

你可以试试把getApp().$vm.$destroyComponent 这一样修改为 getApp().$destroyComponent 看看能不能解决

**Comment by lcybb** [comment]
> > > > > 目前不支持这么混合使用
> > > > 
> > > > 
> > > > 除了 $vm 之外还会有其他的影响吗？新功能想使用vue3开发
> > > 
> > > 
> > > 不太确定，没有测试过，目前应该是跑不通的。
> > 
> > 
> > 因为除了当前 issue，我目前暂时还没遇到其他问题
> 
> 你可以试试把getApp().$vm.$destroyComponent 这一样修改为 getAppVm().$destroyComponent 看看能不能解决

谢谢大佬，尝试了一下，没有报错了

**Comment by fxy060608** [comment]
已修复：3.0.0-alpha-3060720221017002

**Comment by xuweikang** [comment]
面临同样的问题，目前老项目是vue2版本，新组件想接入vue3的语法。能请假下如何弄的么。不胜感激。

**Comment by xuweikang** [comment]
> 面临同样的问题，目前老项目是vue2版本，新组件想接入vue3的语法。能请假下如何弄的么。不胜感激。

因为我的老项目都是vue2，如果我想开的新的vue3项目，把vue3项目打包成混合组件？然后拷贝到老项目么。这样可行么。

**Comment by lcybb** [comment]
> > 面临同样的问题，目前老项目是vue2版本，新组件想接入vue3的语法。能请假下如何弄的么。不胜感激。
> 
> 因为我的老项目都是vue2，如果我想开的新的vue3项目，把vue3项目打包成混合组件？然后拷贝到老项目么。这样可行么。

不可以的，vue3 和 vue2  打包后传递组件参数的方式不一样，所以 vue3 的组件打包给 vue2 使用是用不了的，除非你的组件不需要传递参数

**Comment by xuweikang** [comment]
> > > 面临同样的问题，目前老项目是vue2版本，新组件想接入vue3的语法。能请假下如何弄的么。不胜感激。
> > 
> > 
> > 因为我的老项目都是vue2，如果我想开的新的vue3项目，把vue3项目打包成混合组件？然后拷贝到老项目么。这样可行么。
> 
> 不可以的，vue3 和 vue2 打包后传递组件参数的方式不一样，所以 vue3 的组件打包给 vue2 使用是用不了的，除非你的组件不需要传递参数

那你怎么解决的，我说错了，不是组件，是一个完整的分包内容吧。我感觉我目前的问题，和你的应该是一样的。不想要全部重构掉老的vue2项目，但是后面新的页面想用vue3去做，不知道有什么技术方案，大佬可否分享下？

**Comment by xuweikang** [comment]
> 

你们现在，还是用这种技术方案在线上么？
那这个，比如vue3项目大起来以后，也引入了node-modules，老项目也得下载对应的npm包？

**Comment by xuweikang** [comment]
> > 
> 
> 你们现在，还是用这种技术方案在线上么？ 那这个，比如vue3项目大起来以后，也引入了node-modules，老项目也得下载对应的npm包？

还有图片资源的合并，感觉考虑的问题会很多啊。

**Comment by lcybb** [comment]
> 还有图片资源的合并，感觉考虑的问题会很多啊。

这个方案我已经用在生产了
vue3 项目的 node-modules 和老项目的都没关联了呀
你们小程序的图片静态资源不放在线上吗？

**Comment by xuweikang** [comment]
> 

还有个问题请教下。你是拷贝后然后放到老项目里的么，pages.json里面我引入的时候会报错找不到vue文件。
这是我vue2项目里的页面配置，
  "subPackages": [
    {
      "root": "vue3/",
      "pages": [
       { "path": "packages/debug/index"}
      ]
    }]
  vue3打包后的文件夹我放到vue3目录下了，但是vue3打包后的文件都是js wxml文件，没有.vue文件，而 路由里面配置的应该是找 packages/debug/index.vue 这个文件吧，这个怎么解决的

**Comment by lcybb** [comment]
> 

是把 vue3 打包后的代码，放入vue2打包后的代码中

**Comment by lcybb** [comment]
> 还有个问题请教下。你是拷贝后然后放到老项目里的么，pages.json里面我引入的时候会报错找不到vue文件。 这是我vue2项目里的页面配置， "subPackages": [ { "root": "vue3/", "pages": [ { "path": "packages/debug/index"} ] }] vue3打包后的文件夹我放到vue3目录下了，但是vue3打包后的文件都是js wxml文件，没有.vue文件，而 路由里面配置的应该是找 packages/debug/index.vue 这个文件吧，这个怎么解决的


是把 vue3 打包后的代码，放入vue2打包后的代码中
