### ISSUE TITLE
 安卓 plus.device.getInfo 和  uni.getSystemInfoSync() 获取的deviceId不一致

### ISSUE THREAD

**Issue by zfjhui** [dcloudio/uni-app#3925]
**问题描述**
 首次授权android.permission.READ_PHONE_STATE下
plus.device.getInfo 获取到的结果
```
plus.device.getInfo({
		success(e) {
			console.log(e);
		}
	});
{"imei":"","imsi":[""],"uuid":"f224a5815cb34845"} 
```
getSystemInfoSync() 获取到的结果
```
uni.getSystemInfoSync().deviceId
YluY92BA6nJ6NfixI77sFQ%3D%3D&ie=1
```

代码---
```
requestAndroidPermission('android.permission.READ_PHONE_STATE').then(e => {
	console.log(uni.getSystemInfoSync());
	plus.device.getInfo({
		success(e) {
			console.log(e);
		}
	});
});
```
**预期结果**
 返回结果一致

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台:安卓APP
 - 操作系统 Android 10.0
 - HBuilderX版本3.6.4
 - 设备信息  华为荣耀 X10

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
uniapp初始化时就生成好了 getSystemInfoSync 需要的信息 导致授权后没有重新走逻辑

**Comment by zhetengbiji** [comment]
SystemInfo 里的 deviceId 和  plus.device 并非同一个

另外，更新到 HBuilderX alpha 3.6.7 有相关优化
