### ISSUE TITLE
打包H5后chunk-vendors.js文件大

### ISSUE THREAD

**Issue by CPenguo** [dcloudio/uni-app#3926]
**问题描述**
uniapp打包编译H5后,chunk-vendors.js文件大影响页面加载? 请问如何让进行性能优化? 如:CDN加速等

**Comment by zhetengbiji** [comment]
https://uniapp.dcloud.net.cn/tutorial/performance.html#%E4%BC%98%E5%8C%96%E5%8C%85%E4%BD%93%E7%A7%AF

**Comment by CPenguo** [comment]
> https://uniapp.dcloud.net.cn/tutorial/performance.html#%E4%BC%98%E5%8C%96%E5%8C%85%E4%BD%93%E7%A7%AF

Duplicate of #
