### ISSUE TITLE
uni.login不支持百度，接口报错 Auth Login Params Not Corret

### ISSUE THREAD

**Issue by chenyangguang** [dcloudio/uni-app#3932]
**问题描述**
编译 uni.login 方法到百度平台，百度开发者工具显示 

请求头： https://passport.baidu.com/v3/login/api/auth/?tool_version=4.5.1&tool_mid=a33ce0d54f886b745292b54d8072f9ac&tpl=dev&return_type=2&callback=jsonp
但是返回

`Auth Login Params Not Corret`

**复现步骤**
[复现问题的步骤]
1.  启动 'hbuilderx'
2. 点击  '运行到百度小程序平台'
3. 查看 百度小程序编辑器

**Comment by chenyangguang** [comment]
<img width="1115" alt="image" src="https://user-images.githubusercontent.com/7223579/196579323-230489c2-393c-491d-a847-aa44ad1ccf60.png">

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/2443

**Comment by zhenyuWang** [comment]
测试 请求  https://passport.baidu.com/v3/login/api/auth/?tool_version=4.5.1&tool_mid=a33ce0d54f886b745292b54d8072f9ac&tpl=dev&return_type=2&callback=jsonp 返回 Auth Login Params Not Corret 发生在显示扫码弹框后，点击蒙层取消弹框时触发，如扫码登录，可以登录成功
与百度小程序原生开发表现一致
```
<template>
	<view class="content">
		<button type="primary" open-type="login" @login="login">test login</button>
	</view>
</template>

<script>
	export default {
		methods: {
			login(){
				uni.login({
					complete(res){
						console.log('uni.login complete',res);
					}
				})
			}
		}
	}
</script>
```
