### ISSUE TITLE
APP里没有document怎么动态生成input框

### ISSUE THREAD

**Issue by moke8** [dcloudio/uni-app#3933]
**问题描述**
目前需求需要将一串字符串里的内容匹配为一个或多个input，在用户点击提交时获取到input的内容

目前使用v-html可以将input动态渲染到页面上，但是因为APP里没有document对象，无法获取input内输入的内容

**Comment by moke8** [comment]
求问一下，怎么能够动态生成input并获取内容呢

**Comment by moke8** [comment]
APP环境下不能做动态表单吗

**Comment by zhetengbiji** [comment]
1. 使用 [renderjs](https://uniapp.dcloud.net.cn/tutorial/renderjs.html#renderjs) 可以直接操作 dom
2. 这个需要没必要直接操作dom，直接操作数据即可，以下示例为了方便是伪代码：

```html
<v-for="item in array"><input v-model='item.value'>
```
```js
string = 'a,b,c'
array = string.split(',').map(value=>{value})
```
