### ISSUE TITLE
uni-app更新到v3.0.0-alpha-3060720221014001后运行到微信小程序报错

### ISSUE THREAD

**Issue by self-talking** [dcloudio/uni-app#3935]
**问题描述**
uni-app更新到v3.0.0-alpha-3060720221014001后使用yarn运行到微信小程序报错

**复现步骤**
![image](https://user-images.githubusercontent.com/41891283/196593288-825582bb-0221-46bc-9674-78da20538696.png)

**预期结果**
正常运行

**实际结果**
![image](https://user-images.githubusercontent.com/41891283/196593443-99fd8685-3919-43c0-aa60-b6eba5c79284.png)

**系统信息:**
微信小程序

**Comment by fxy060608** [comment]
升级版本至：3.0.0-alpha-3060720221018002
注意，建议使用锁定版本升级（移除版本号前的^）

**Comment by self-talking** [comment]
![image](https://user-images.githubusercontent.com/41891283/196594549-43fd27fc-ddbc-4976-a601-8204aeab45ae.png)
![image](https://user-images.githubusercontent.com/41891283/196594569-a4345f25-5027-4bd3-bb2d-8077a2be72f5.png)
使用3.0.0-alpha-3060720221018002安装依赖时提示没有这个版本

**Comment by fxy060608** [comment]
> ![image](https://user-images.githubusercontent.com/41891283/196594549-43fd27fc-ddbc-4976-a601-8204aeab45ae.png) ![image](https://user-images.githubusercontent.com/41891283/196594569-a4345f25-5027-4bd3-bb2d-8077a2be72f5.png) 使用3.0.0-alpha-3060720221018002安装依赖时提示没有这个版本

npm官方仓库是有的，可以更换成官方的 registry 试试：https://registry.npmjs.org/

https://www.npmjs.com/package/@dcloudio/uni-app/v/3.0.0-alpha-3060720221018002

**Comment by self-talking** [comment]
可以了,淘宝源还没同步仓库,感谢
