### ISSUE TITLE
selectComponent和selectAllComponents在小程序和H5里生效，但APP不生效。

### ISSUE THREAD

**Issue by zhangdaren** [dcloudio/uni-app#3940]
**问题描述**
selectComponent和selectAllComponents在小程序和H5里生效，但APP不生效。

**复现步骤**
[复现问题的步骤]

//bar.vue
```
<template>
	<view>
		<view>bar</view>
	</view>
</template>
<script>
export default {
	data(){
		return {
			foo:"this is bar"
		}
	}
}
</script>
```

//index.vue
```
<template>
	<view>
		<bar class="bar"></bar>
		<bar class="bar"></bar>

		<bar id="test"></bar>
	</view>
</template>
<script>
import Bar from './bar';
export default {
    components: {
        Bar
    },
   onLoad() {
		setTimeout(()=> {
			var test = this.selectComponent('#test')
			// console.log('#test', test);  //直接打印会报[Vue warn]: Property or method "toJSON" is not defined on the instance but referenced during render....
			console.log('#test', test.$vm.foo);   //正确输出："this is bar"
			var arr = this.selectAllComponents('.bar')
			console.log('.bar', arr.length);
			arr.map(item=>console.log(item.$vm.foo))
		}, 10);
	}
}
</script>
```

**预期结果**
能在APP环境正确打印不报错

**实际结果**
从实际打印来看，selectComponent和selectAllComponents函数是有实现的，如：
``` function(e){return function e(t,n){if(n(t.$vnode||t._vnode))return t;for(var r=t.$children,i=0;i<r.length;i++){var o=e(r[i],n);if(o)return o}}(this,ov(e))}·```

经测，在小程序和H5里生效，但APP不生效。

原因：
是因为APP里面的结构已经变化，直接拿_vnode或$vnode是拿到的。
需访问 ： `node._vnode?.context?._vnode`，才能拿到class及属性信息

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]  APP
 - 操作系统 [如 iOS 12.1.2、Android 7.0]  android 11
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]  v3.6.7 alpha
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
如上，已经很明了。

另,不知为何要多一级$vm呢？

**Comment by bugaio** [comment]
文档里 ,   有这个 api 么,  我没搜到哎

**Comment by zhangdaren** [comment]
> 文档里 , 有这个 api 么, 我没搜到哎

文档里没有，但却能用，这个就很灵动了。
为了拉齐各平台这两个api的差异，我只能重写它了。

**Comment by bugaio** [comment]
> > 文档里 , 有这个 api 么, 我没搜到哎
> 
> 文档里没有，但却能用，这个就很灵动了。 为了拉齐各平台这两个api的差异，我只能重写它了。
> 
> 因为能直接用，导致重写它时，还有那么一点点不方便。

感觉 大概率 是 给 wxs  使用的,  对应的  [微信文档](https://developers.weixin.qq.com/miniprogram/dev/framework/view/interactive-animation.html) ,

**Comment by zhangdaren** [comment]
> > > 文档里 , 有这个 api 么, 我没搜到哎
> > 
> > 
> > 文档里没有，但却能用，这个就很灵动了。 为了拉齐各平台这两个api的差异，我只能重写它了。
> > 因为能直接用，导致重写它时，还有那么一点点不方便。
> 
> 感觉 大概率 是 给 wxs 使用的, 对应的 [微信文档](https://developers.weixin.qq.com/miniprogram/dev/framework/view/interactive-animation.html) ,

好像有这个可能，wxs的这两个api还未来得及测试，感谢哈~

**Comment by zhangdaren** [comment]
> > > 文档里 , 有这个 api 么, 我没搜到哎
> > 
> > 
> > 文档里没有，但却能用，这个就很灵动了。 为了拉齐各平台这两个api的差异，我只能重写它了。
> > 因为能直接用，导致重写它时，还有那么一点点不方便。
> 
> 感觉 大概率 是 给 wxs 使用的, 对应的 [微信文档](https://developers.weixin.qq.com/miniprogram/dev/framework/view/interactive-animation.html) ,

经测：

wxs里面console.log(ownerInstance.selectComponent )输出：
`function (t){if(this.$el&&t){var e=this.$el.querySelector(t),n=e.__vue__||e;return n.$getComponentDescriptor&&n.$getComponentDescriptor(n,!1)}}`

在代码里面console.log(this.selectComponent)输出
`function(e){return function e(t,n){if(n(t.$vnode||t._vnode))return t;for(var r=t.$children,i=0;i<r.length;i++){var o=e(r[i],n);if(o)return o}}(this,ov(e))}·`

似乎不太一样。

测试项目也加载了我重写的selectComponent ：``https://ext.dcloud.net.cn/plugin?id=9847` ，测试并无冲突。

**Comment by zhangdaren** [comment]
经过艰难测试，app要获取同等效果，应该是取`node._vnode.context.$vnode`

**Comment by zhetengbiji** [comment]
在逻辑层 selectComponent 和 wxs/renderjs（视图层）的实现不同，不同端（小程序、App、H5）的表现也不同，并非提供给开发者使用，同时也不在文档提供。

如以后有计划开放给开发者使用，会暴露不同端一致体验的接口。

在此之前请使用 ref。

**Comment by zhangdaren** [comment]
> 在逻辑层 selectComponent 和 wxs/renderjs（视图层）的实现不同，不同端（小程序、App、H5）的表现也不同，并非提供给开发者使用，同时也不在文档提供。
> 
> 如以后有计划开放（逻辑层的 selectComponent）给开发者使用，会暴露不同端一致体验的接口（如：统一返回 vm 实例）。
> 
> 在此之前请使用 ref。

感谢回复，，但我觉得这方面uni-app应该有能力抹平的。

经过测试，我通过一些手段，暂时将这些平台的差异抹平了（因为我是在做小程序转换为uni-app项目，一些语法如果不抹平的话，那需要手动修改的地方实在太多）。

另：自定义组件的dataset似乎有在支持（更新文档没有体现）？没有详测，只是觉得前段时间还不支持，这几天用了最新的版本，是可以支持的，待再详细测试一下

**Comment by zhetengbiji** [comment]
> > 在逻辑层 selectComponent 和 wxs/renderjs（视图层）的实现不同，不同端（小程序、App、H5）的表现也不同，并非提供给开发者使用，同时也不在文档提供。
> > 如以后有计划开放（逻辑层的 selectComponent）给开发者使用，会暴露不同端一致体验的接口（如：统一返回 vm 实例）。
> > 在此之前请使用 ref。
> 
> 感谢回复~
> 
> 经过测试，我通过一些手段，暂时将这些平台的差异抹平了（因为我是在做小程序转换为uni-app项目，一些语法如果不抹平的话，那需要手动修改的地方实在太多）。
> 
> 另：自定义组件的dataset似乎有在支持（更新文档没有体现）？没有详测，只是觉得前段时间还不支持，这几天用了最新的版本，是可以支持的，待再详细测试一下

小程序转 uni-app 的话，是不是更期望返回一个模拟小程序组件实例而不是期望返回 Vue 实例？

你说的 dataset 支持是指的 dataset 支持非字符串的数据类型么？

**Comment by zhangdaren** [comment]
> > > 在逻辑层 selectComponent 和 wxs/renderjs（视图层）的实现不同，不同端（小程序、App、H5）的表现也不同，并非提供给开发者使用，同时也不在文档提供。
> > > 如以后有计划开放（逻辑层的 selectComponent）给开发者使用，会暴露不同端一致体验的接口（如：统一返回 vm 实例）。
> > > 在此之前请使用 ref。
> > 
> > 
> > 感谢回复~
> > 经过测试，我通过一些手段，暂时将这些平台的差异抹平了（因为我是在做小程序转换为uni-app项目，一些语法如果不抹平的话，那需要手动修改的地方实在太多）。
> > 另：自定义组件的dataset似乎有在支持（更新文档没有体现）？没有详测，只是觉得前段时间还不支持，这几天用了最新的版本，是可以支持的，待再详细测试一下
> 
> 小程序转 uni-app 的话，是不是更期望返回一个模拟小程序组件实例而不是期望返回 Vue 实例？
> 
> 你说的 dataset 支持是指的 dataset 支持非字符串的数据类型么？

目前来说，uniapp运行到小程序时，通过this.$scope.selectComponent() 返回的要多一层$vm，这个很容易解决，去掉这一层即可。
app和h5平台，就通过解析node._vnode.context.$vnode节点下面的数据，手动获取id和class，来获取到想要的组件实例，从测试结果来看，没得问题。

dataset是指 前段时间测试，在click回调里，如果当前是自定义组件时，dataset为空，而内置组件(view这些)时，则正常。

前两天偶然测试dataset倒正常了，自定义组件也能取到了，用的最新的hbx alpha版，准备再次测试一番。

**Comment by zhangdaren** [comment]
> > > 在逻辑层 selectComponent 和 wxs/renderjs（视图层）的实现不同，不同端（小程序、App、H5）的表现也不同，并非提供给开发者使用，同时也不在文档提供。
> > > 如以后有计划开放（逻辑层的 selectComponent）给开发者使用，会暴露不同端一致体验的接口（如：统一返回 vm 实例）。
> > > 在此之前请使用 ref。
> > 
> > 
> > 感谢回复~
> > 经过测试，我通过一些手段，暂时将这些平台的差异抹平了（因为我是在做小程序转换为uni-app项目，一些语法如果不抹平的话，那需要手动修改的地方实在太多）。
> > 另：自定义组件的dataset似乎有在支持（更新文档没有体现）？没有详测，只是觉得前段时间还不支持，这几天用了最新的版本，是可以支持的，待再详细测试一下
> 
> 小程序转 uni-app 的话，是不是更期望返回一个模拟小程序组件实例而不是期望返回 Vue 实例？
> 
> 你说的 dataset 支持是指的 dataset 支持非字符串的数据类型么？



大佬，从这里代码来看https://github.com/dcloudio/uni-app/blob/0edd43ecaf/src/core/service/plugins/polyfill.js
是已经在原型上面挂着的呢？是用于所有平台？还是只针对 于小程序？
 从注释上面来说，确实只针对 于小程序

**Comment by zzy-life** [comment]
哈哈哈碰见大佬了，我也是用的你的插件转换的~
目前也是因为用wxs做拖拽发现bug进来的
