### ISSUE TITLE
navigationBarTextStyle: "black"设置不生效

### ISSUE THREAD

**Issue by PXRace** [dcloudio/uni-app#3947]
**问题描述**
navigationBarTextStyle: "black"，支付宝小程序导航栏字体为白色

**复现步骤**

1.  运行到支付宝小程序
2. 首页查看导航栏

**预期结果**
支付宝小程序导航栏字体为黑色

**实际结果**
支付宝小程序导航栏字体为白色

**系统信息:**
 - 发行平台: 支付宝小程序
 - 操作系统 macOS 11.1
 - HBuilderX版本 ：3.6.4.20220922

刚刚搭建的demo，都是默认的black，就不行

**Comment by zhetengbiji** [comment]
感谢提醒，已更新文档

> 支付宝小程序不支持，请使用 [my.setNavigationBar](https://opendocs.alipay.com/mini/api/xwq8e6)
