### ISSUE TITLE
设置page: { height: 100% }在app端不生效

### ISSUE THREAD

**Issue by aalexlin** [dcloudio/uni-app#3950]
**问题描述**
设置page: { height: 100% }在app端不生效，小程序和h5则正常

**复现步骤**
在App.vue文件中设置
page {
  height: 100%;
}

**系统信息:**
 - 发行平台: APP
 - 操作系统: IOS16
 - HBuilderX版本:  3.6.7
 - uni-app版本:  3.0.0-alpha-3060320220919001
 - 设备信息: iphoneSE

**Comment by zhetengbiji** [comment]
如何判断的是否生效？
安卓是否正常？

**Comment by aalexlin** [comment]
![image](https://user-images.githubusercontent.com/6197922/197926898-15442cd0-7e05-4cba-a9ac-fdc68d239c77.png)
现况是这样

**Comment by aalexlin** [comment]
@zhetengbiji 通过debug找到问题了，#app也设置height: 100%就表现一致了。
