### ISSUE TITLE
3.6.4.20220922版本中uni.getLocation()报错

### ISSUE THREAD

**Issue by BoomHammer** [dcloudio/uni-app#3953]
**问题描述**
3.6.4.20220922版本中uni.getLocation()报错，回退到3.4.18.20220630则无此问题
报错信息：{errMsg: "getLocation:fail Cannot read property 'altitudeAccuracy' of undefined"}

**复现步骤**
调用uni.getLocation，代码如下

uni.getLocation({
		type: "gcj02",
		success: ({ longitude, latitude, }) => {
			// 成功的操作
		},
		fail: (err) => {
                        //下面这里报错
			console.log(err)
		}
	});

运行->运行到内置浏览器，执行上述代码。

**预期结果**
uni.getLocation()成功获取到位置信息

**实际结果**
uni.getLocation()失败，报错{errMsg: "getLocation:fail Cannot read property 'altitudeAccuracy' of undefined"}

**系统信息:**
 - HBuilderX版本 3.6.4.20220922

**补充信息**
查看getLocation()源码：uni-app/src/platforms/h5/service/api/location/get-location.js，第82行用到了altitudeAccuracy属性。但是后面有 || 0，理论上来说即使没有altitudeAccuracy也能正常运行啊，但我也找不到别的用altitudeAccuracy的地方了。

**Comment by zhenyuWang** [comment]
测试并未复现该问题，重新运行是否正常？运行到chrome是否正常？

**Comment by BoomHammer** [comment]
> 测试并未复现该问题，重新运行是否正常？运行到chrome是否正常？

![image](https://user-images.githubusercontent.com/47084396/198272412-b4b1799a-fcfa-4ca2-bc60-7c6f86e71375.png)
chrome也会报错

**Comment by zhenyuWang** [comment]
能否提供下测试工程？

**Comment by zhenyuWang** [comment]
长时间未响应，问题暂时关闭；
若后续依然有问题，可reopen这个issue。
