### ISSUE TITLE
picker-view兼容性有问题，picker-view-column内设置高度在app上显示异常

### ISSUE THREAD

**Issue by zui4yi1** [dcloudio/uni-app#3957]
**问题描述**
picker-view-column内每项设置高度，在h5和小程序上显示正常，在app上显示异常，表现有二个方面：
1. 第一列，选中的项不在中间
2. 第二列，与第一列不匹配

**复现步骤**
在以下class=XXXXXXXX内，有设置自定义高度
<picker-view
            :value="defaultSelectors.array"
            :style="{ height: '440rpx' }"
            indicator-class="uni-picker-view-indicator"
            @change="handleColumnChange"
            @pickstart="handlePickStart"
            @pickend="handlePickEnd"
          >
            <picker-view-column v-for="(item, index) in columnData.array" :key="index">
              <view v-for="(item1, index1) in item" :key="`picker_${index1}`" class="XXXXXXXX">
                <view class="font-xt"> {{ item1.label }}</view>
              </view>
            </picker-view-column>
          </picker-view>

**预期结果**
滑动时，第二列与第一列匹配

**实际结果**
1. 第一列，选中的项不在中间
2. 第二列，与第一列不匹配

**系统信息:**
 - 发行平台: [Android]
 - 操作系统: all
 - uni-app版本 [3.5.3 正式版]

**补充信息**
app上未获取正确的高度

**Comment by feliciaZH** [comment]
遇到相同的问题，打算用vant组件去试试

**Comment by bfc846958672** [comment]
如果用 indicator-class 属性，需要用/deep/ 让样式透传，进而作用到组件。

**Comment by bfc846958672** [comment]
长时间未响应，关闭本issue。 如还有问题，可 reopen issue 继续讨论。
