### ISSUE TITLE
uni.upload地址404进了success

### ISSUE THREAD

**Issue by snowchenlei** [dcloudio/uni-app#3959]
使用uni.upload上传文件。服务器返回了404，但是进入了success的回调，而不是fail
![image](https://user-images.githubusercontent.com/26211283/198559919-805a6bd3-99f2-4182-b19b-49f235aef07c.png)

**Comment by zhetengbiji** [comment]
![image](https://user-images.githubusercontent.com/6326057/198560824-4f9fef9c-0032-4f03-970d-55d015bad8fa.png)

**Comment by snowchenlei** [comment]
> ![image](https://user-images.githubusercontent.com/6326057/198560824-4f9fef9c-0032-4f03-970d-55d015bad8fa.png)

拿什么情况才会进fail呢

**Comment by zhetengbiji** [comment]
> > ![image](https://user-images.githubusercontent.com/6326057/198560824-4f9fef9c-0032-4f03-970d-55d015bad8fa.png)
> 
> 拿什么情况才会进fail呢

请求失败，如：网络错误或者服务器无响应
