### ISSUE TITLE
无法加载 uni-h5-vue/dist/null 的内容

### ISSUE THREAD

**Issue by moke8** [dcloudio/uni-app#3961]
**问题描述**
仅H5端，在使用canvas时报错

```
Uncaught TypeError: $event.currentTarget.getBoundingClientRect is not a function                  null:1397
```

点进 null:1397 出现
```
无法加载 http://127.0.0.1:3000/node_modules/_@dcloudio_uni-h5-vue@3.0.0-alpha-3060720221018007@@dcloudio/uni-h5-vue/dist/null 的内容（HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE）
```

**系统信息:**
 - 发行平台: H5
 - HBuilderX版本 CLI
 - uni-app版本 v3.0.0-alpha-3060720221018007

**Comment by fxy060608** [comment]
发测试工程

**Comment by moke8** [comment]
[uni.zip](https://github.com/dcloudio/uni-app/files/9936500/uni.zip)

**Comment by moke8** [comment]
> 发测试工程

已发送

**Comment by moke8** [comment]
有时间可以帮忙看看吗

**Comment by StrivingRabbit** [comment]
最新版 alpha 已修复此问题[3.0.0-alpha-3061220221207002](https://www.npmjs.com/package/@dcloudio/uni-app/v/3.0.0-alpha-3061220221207002)
