### ISSUE TITLE
uni.hideLoading()问题

### ISSUE THREAD

**Issue by LiuXIn011** [dcloudio/uni-app#3965]
**问题描述**
在微信小程序IOS平台，未使用uni.showLoading()的情况下使用uni.hideLoading()会导致页面阻塞，无法进行后续逻辑，且不报错，很难发现和调试。（由于uni.showLoading()和uni.hideLoading()是异步方法，很容易意外的导致这个问题而很难发现。）

**复现步骤**
在微信小程序IOS平台，未使用uni.showLoading()的情况下使用uni.hideLoading()

**预期结果**
正常进行不阻塞

**实际结果**
页面阻塞，无法进行后续逻辑，且不报错。

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 iOS
 - HBuilderX版本 3.6.4.20220922
 - 设备信息 iPhone１１

**Comment by zhetengbiji** [comment]
反馈到微信小程序社区

**Comment by zhetengbiji** [comment]
在微信小程序，实际调用的是 wx.showLoading()

**Comment by LiuXIn011** [comment]
> 在微信小程序，实际调用的是 wx.showLoading、wx.hideLoading
需要官方看一下是谁的问题，也不一定是微信的、

**Comment by zhetengbiji** [comment]
> > 在微信小程序，实际调用的是 wx.showLoading、wx.hideLoading
> > 需要官方看一下是谁的问题，也不一定是微信的、

麻烦你调用一下 wx.hideLoading 测试
