### ISSUE TITLE
蓝牙写入数据bug（ios）

### ISSUE THREAD

**Issue by 5neverstop** [dcloudio/uni-app#397]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
uni.writeBLECharacteristicValue() 写入数据 触发success回调返回 {"errMsg":"writeBLECharacteristicValue:ok"} 。
并报以下错误
15:56:18.239 thirdScriptError
15:56:18.240 Invalid array length argument;undefined
15:56:18.240 Uint8Array@[native code]
15:56:18.240 wt@app-service.js:4:176797
15:56:18.240 app-service.js:4:95330
15:56:18.240 app-service.js:4:209876
15:56:18.240 app-service.js:4:417132
15:56:18.240 app-service.js:4:173417
15:56:18.240 app-service.js:3:75844
15:56:18.240 app-service.js:3:36705
15:56:18.240 callbackFromNative
15:56:18.240 nativeEval
15:56:18.240 global code __ERROR 

之后notify中收到{ "Error": "Error Domain=CBATTErrorDomain Code=6 \"The request is not supported.\" UserInfo={NSLocalizedDescription=The request is not supported.}", "characteristicId": "6E400002-B5A3-F393-E0A9-E50E24DCCA9E", "deviceId": "07434A53-5725-4EDD-B527-21B2A45C8BEA", "serviceId": "6E400001-B5A3-F393-E0A9-E50E24DCCA9E" }

请问如何解决？只在ios中出现，android和微信小程序均可正常使用
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: 5+App
 - 操作系统: ios*
 - HBuilderX版本：1.9.8.20190518
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息  iPhone*

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by superTimi** [comment]
我的也有这种情况，应该不是特例
选用的特征值为{"properties":{"indicate":false,"notify":false,"read":false,"write":true},"uuid":"0000FFF3-0000-1000-8000-00805F9B34FB"}
安卓端没问题

**Comment by dcloudhdx** [comment]
更新 HBuilderX，已修复此问题
