### ISSUE TITLE
npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project  打包wgt

### ISSUE THREAD

**Issue by zwt369** [dcloudio/uni-app#3970]
**问题描述**
npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project 创建的项目 用HBuilderX 打包wgt包报错

HBuilderX 版本：3.6.4.20220922

HBuilder] 17:06:30.560     const cache = options.cache ?? new SplitVendorChunkCache();
[HBuilder] 17:06:30.561                                  ^
[HBuilder] 17:06:30.568 SyntaxError: Unexpected token '?'
[HBuilder] 17:06:30.586     at wrapSafe (internal/modules/cjs/loader.js:915:16)
[HBuilder] 17:06:30.593     at Module._compile (internal/modules/cjs/loader.js:963:27)
[HBuilder] 17:06:30.594     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[HBuilder] 17:06:30.601     at Module.load (internal/modules/cjs/loader.js:863:32)
[HBuilder] 17:06:30.601     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
[HBuilder] 17:06:30.621     at Module.require (internal/modules/cjs/loader.js:887:19)
[HBuilder] 17:06:30.621     at require (internal/modules/cjs/helpers.js:74:18)
[HBuilder] 17:06:30.629     at Object.<anonymous> (/Users/zhang/Desktop/uni-demo/my-vue3-project/node_modules/vite/index.cjs:7:31)
[HBuilder] 17:06:30.629     at Module._compile (internal/modules/cjs/loader.js:999:30)
[HBuilder] 17:06:30.635     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[HBuilder] 17:06:30.666 项目 'my-vue3-project'导出失败

package.json 里面又没有 build:app-plus 的脚本，这种情况怎么打包wgt 文件？

**Comment by zhetengbiji** [comment]
下载 HBuilderX alpha 3.6.8 试试

**Comment by zwt369** [comment]
更新HBuilderX alpha 3.6.8 可以正常打包了，thx
