### ISSUE TITLE
为什么makePhoneCall  API接收的phoneNumber必须要为string类型呢？number不行么~

### ISSUE THREAD

**Issue by hexiaokang** [dcloudio/uni-app#3983]
**新功能描述**
makePhoneCall  API新增phoneNumber对number类型数据的支持

**现状及问题**
目前必须强制转换为string

**尝试方案**
新增number支持

**补充信息**
[其它你认为有参考价值的信息]

**Comment by ModyQyW** [comment]
在使用国内长途电话时，区号前要加拨 0。如果使用 number 类型，0 可能会丢失或导致一些意外情况。

**Comment by hexiaokang** [comment]
> 在使用国内长途电话时，区号前要加拨 0。如果使用 number 类型，0 可能会丢失或导致一些意外情况。该部分可见 [百度百科区号](https://baike.baidu.com/item/%E5%8C%BA%E5%8F%B7/1866086)。

这个理解，但是这个其实可以在逻辑层面做区分的。

**Comment by zhetengbiji** [comment]
暂不统一处理，保持与文档一致。
