### ISSUE TITLE
为什么安卓微信小程序拨打电话没有询问窗？

### ISSUE THREAD

**Issue by EarlySummer2018** [dcloudio/uni-app#3988]
**问题描述**
安卓微信小程序点击调用`uni.makePhoneCall`拨打电话没有询问窗出现直接跳转，iOS则出现询问窗

**复现步骤**
[复现问题的步骤]
调用 uni.makePhoneCall API即可复现

**Comment by zhetengbiji** [comment]
使用 uni.makePhoneCall 实际为 wx.makePhoneCall，是微信小程序平台的实现，请将问题发到微信小程序社区，由微信小程序官方人员来给出解答。

**Comment by EarlySummer2018** [comment]
> 在微信小程序使用 uni.makePhoneCall 实际为 wx.makePhoneCall，是微信小程序平台的实现，请将问题发到微信小程序社区，由微信小程序官方人员来给出解答。

好的
