### ISSUE TITLE
可以提供路由拦截的功能么?至少在h5上面

### ISSUE THREAD

**Issue by ranwawa** [dcloudio/uni-app#399]
目前好像没有拦截功能

**Comment by daywithday** [comment]
路由跳转实际上就是个中间件，你自己写个js方法 然后调用，带上自定义参数判断条件执行不就好了。

**Comment by ranwawa** [comment]
> 路由跳转实际上就是个中间件，你自己写个js方法 然后调用，带上自定义参数判断条件执行不就好了。

navigator链接跳转也会进入这个中间件么,switchTab呢

**Comment by yuzmb** [comment]
如果是简单的获取登录后用户信息，可以用全局mixin + store。判断，如没有，就请求，没权限，就跳登录页

**Comment by zhetengbiji** [comment]
H5端支持，通过 this.$router，参考示例：https://ext.dcloud.net.cn/plugin?id=659
其他端解决方案参考：https://ext.dcloud.net.cn/plugin?id=578

**Comment by ranwawa** [comment]
你的邮件我已收到，查收后会尽快回复！：）
