### ISSUE TITLE
node_modules中的依赖变化后，不会重新编译

### ISSUE THREAD

**Issue by wangjieCode** [dcloudio/uni-app#3991]
版本v3.0.0-alpha-3060420220922001

目前项目使用monorepo去管理，但是其他repo变化后不会触发重新编译，vite的web项目是OK的，是需要配置什么东西么

**Comment by wangjieCode** [comment]
有大佬解答一下么，比较着急😭

**Comment by okxiaoliang4** [comment]
解决了吗？请问怎么解决的呢

**Comment by wangjieCode** [comment]
@okxiaoliang4 
``vite.config.ts`` 添加一下配置
<img width="575" alt="image" src="https://user-images.githubusercontent.com/49115360/230359675-76e8246d-010e-4beb-b0c8-f0769fe7a4cd.png">
这样是可以watch到nodemodules的变化的，但是偶尔会触发多次编译

**Comment by wangjieCode** [comment]
现在我们的monorepo项目开发体验还是比较差的，主要有以下问题
1. 莫名其妙的出现重新编译
2. 编译速度比较慢
3. uniapp的自动导入偶尔会失效，重启项目后恢复正常

**Comment by okxiaoliang4** [comment]
我现在是单独开了个repo作为组件库，后面需要用到的项目里link这个组件库，就也遇到这个问题了，按照你的配置确实可以了谢谢。

**Comment by Caffeine19** [comment]
> [@okxiaoliang4](https://github.com/okxiaoliang4) `vite.config.ts` 添加一下配置 <img alt="image" width="575" src="https://user-images.githubusercontent.com/49115360/230359675-76e8246d-010e-4beb-b0c8-f0769fe7a4cd.png"> 这样是可以watch到nodemodules的变化的，但是偶尔会触发多次编译

请问你们的monorepo也是用的pnpm管理吗，我尝试了你的这个配置，仍然无法触发热更新，舅舅孩子😭
