### ISSUE TITLE
 列表渲染添加数据时，子节点会因为获取__webviewId__属性而触发setData

### ISSUE THREAD

**Issue by jackiotyu** [dcloudio/uni-app#3997]
**问题描述**
 列表渲染添加数据时，子节点会因为获取__webviewId__属性而触发setData

**复现步骤**
[复现问题的步骤]
1. 列表增删数据

[或者可以直接贴源代码]
https://github.com/dcloudio/uni-app/blob/7edf7fb9d55fe164f3d61cf7bb1db5e721f7a753/packages/vue-cli-plugin-uni/packages/mp-vue/dist/mp.runtime.esm.js#L5659

**预期结果**
__webviewId__属性为null时不触发setData
![image](https://user-images.githubusercontent.com/31788042/202104874-968321c9-1ff4-4969-afe9-16c2ab95de19.png)

**实际结果**
因为这些__webviewId__导致了多次setData
![image](https://user-images.githubusercontent.com/31788042/202103591-dc9ba7d5-dac5-4a11-bbe3-d8dc122e64a6.png)
![image](https://user-images.githubusercontent.com/31788042/202105291-61e2cb32-3cfa-454f-8d02-b2eaa21d51ed.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 Android 10.0
 - uni-app版本 uni-app v3.5.3 uni-app cli v2.0.1-35320220729001
 - 设备信息 xiaomi2s

**补充信息**
__webviewId__为null时，也生成了diffData，导致执行setData

**Comment by zhetengbiji** [comment]
执行 ```npx @dcloudio/uvm alpha``` 更新依赖到 alpha 版，如测试仍有问题，提供一个示例。

**Comment by jackiotyu** [comment]
github仓库可以吗？
`npm run dev:mp-weixin` 可以看到，希望能去掉这些不必要的setData
https://github.com/jackiotyu/mp-list
![image](https://user-images.githubusercontent.com/31788042/202129635-384cbd39-c5ef-4b9b-b883-ad48d6885fea.png)

**Comment by jackiotyu** [comment]
alpha 版仍然有这个的 @zhetengbiji 
https://github.com/dcloudio/uni-app/blob/b54a41b95819e420dac9fb6ca5fe8c8d44021ece/packages/vue-cli-plugin-uni/packages/mp-vue/dist/mp.runtime.esm.js#L5659

**Comment by zhetengbiji** [comment]
> github仓库可以吗？ `npm run dev:mp-weixin` 可以看到，希望能去掉这些不必要的setData https://github.com/jackiotyu/mp-list ![image](https://user-images.githubusercontent.com/31788042/202129635-384cbd39-c5ef-4b9b-b883-ad48d6885fea.png)

经测试 alpha 版无此问题

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/3787

**Comment by jackiotyu** [comment]
谢谢👍
