### ISSUE TITLE
uni.getProvider在调试模式可以取得provider list，但云端打包后不能取得

### ISSUE THREAD

**Issue by junk123321** [dcloudio/uni-app#40]
如题，uni.getProvider在调试模式可以取得provider list，形如：['weixin','qq','sinaweibo','xiaomi']，但云端打包后取得的是[]

**Comment by junk123321** [comment]
可能是没填登录鉴权的配置

**Comment by hbcui1984** [comment]
需要在manifest.json中配置相关的SDK
