### ISSUE TITLE
bug: uni.switchTab进行页面跳转,触发了历史页面的onShow方法. 实际不应该触发

### ISSUE THREAD

**Issue by free-pan** [dcloudio/uni-app#400]
**问题描述**

使用uni.switchTab转回某个tab页时,会导致之前所有访问过的页面的onShow方法都被调用一次

**复现步骤**
[复现问题的步骤]
1.  启动 进入首页`index`(`该页是个标签页`)
2. 点击进入一个二级页(使用`uni.navigateTo({url:'../test/a'})`)
3. 再从二级页再点击进入三级页(使用`uni.navigateTo({url:'../test/b'})`)
4. 从三级页点击返回二级页(`uni.navigateTo({url:'./a'})`)
5. 从二级页点击返回标签页[index](`uni.navigateTo({url:'../index/index'})`)

[或者可以直接贴源代码]

**预期结果**

[复现步骤]的第五步点击返回首页时, 应该直接返回标签页, 且不触发`b`,`a`页面的`onShow`方法

**实际结果**

转回了标签页, 但触发了`b`,`a`页面的`onShow`方法

**系统信息:**
 - 发行平台: App
 - 操作系统: Android 9
 - HBuilderX版本: 1.9.8.20190518, 之前的版本也有这个问题
 - uni-app版本: HBuilderX内置的版本
 - 设备信息: 三星S8

**补充信息**

**Comment by fxy060608** [comment]
已确认，预计下个 HBuilderX Alpha 版本修复此问题

**Comment by zhetengbiji** [comment]
HBuilderX 2.0 正式版已修复此问题
