### ISSUE TITLE
Vue3 通过ref对象获取不到对应的dom元素

### ISSUE THREAD

**Issue by whace** [dcloudio/uni-app#4001]
**问题描述**
vue3 项目通过 ref 对象获取不到dom元素

**复现步骤**
![image](https://user-images.githubusercontent.com/20571798/202210441-0cef7cd9-4e46-4810-8c7e-aa612d15cf7d.png)

![image](https://user-images.githubusercontent.com/20571798/202210318-6254997b-531f-4ac6-805d-4a749f89d09e.png)

**预期结果**
希望能根据ref对象获取到对应的dom元素

**实际结果**
没有给ref对象赋值对应的dom元素

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: win11
 - HBuilderX版本: 3.6.4.20220922

**Comment by fxy060608** [comment]
小程序平台没有dom相关操作，ref不支持获取内置组件
