### ISSUE TITLE
在虚拟模块中提供全局注册组件在 wx 小程序中无效

### ISSUE THREAD

**Issue by KeJunMao** [dcloudio/uni-app#4009]
**问题描述**
我尝试开发一个基于插槽的layouts系统，扫描 layouts 目录然后在 `virtualModule` 中引入、注册组件。

另外，我知道 uni 会转化组件注册的代码，所以我刻意没有使用 `\0` + id

我尝试了两种方法, 我的虚拟模块最终导出类似如下：
1. 作为 vue 插件
```ts
`export default {
  install(app) {
    ${components.join("\n")}
  }
}`
```

3. 普通函数
```ts
`export default function(app) {
  ${components.join("\n")}
}`
```

**复现步骤**

1. clone https://github.com/uni-helper/vite-plugin-uni-layouts
2. pnpm install
3. cd playground && pnpm dev:mp-weixin

**预期结果**
能够正确注册组件

**实际结果**
未能正确注册组件

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 MacOs 13
 - uni-app版本 3.0.0-alpha-3060920221114001
 - 设备信息 微信开发者工具

**补充信息**

本质上就是组件嵌套组件，所以使用插槽实现layout应该是可行的吧？

**Comment by fxy060608** [comment]
在小程序平台，全局组件是在编译阶段静态扫描 main.ts 中 .component('...', ...) 方式注册组件的代码，你目前的实现方式，编译阶段无法扫描出来。简单处理的话，可以在 main.ts 中加个占位注释，自己的插件里替换成注册组件的代码。

**Comment by KeJunMao** [comment]
谢谢，明天我试试
