### ISSUE TITLE
editor组件被初始化一次后，后续获取不到editor组件实例

### ISSUE THREAD

**Issue by guodf** [dcloudio/uni-app#4010]
**问题描述**
![image](https://user-images.githubusercontent.com/7540349/202959308-77c4edfb-91e1-4b00-a2e5-9ff1424bd6f3.png)

**复现步骤**
1. 创建uniapp项目，选择vue3版本
2. 创建页面Home
3. 创建页面Index
4. 创建页面Info，当前页面使用editor组件，从[https://uniapp.dcloud.net.cn/component/editor.html#editor](https://uniapp.dcloud.net.cn/component/editor.html#editor)页面复制代码就行
5. 启动运行到Edge浏览器
6. 从Home页面，uni.redirectTo({url:"/pages/index/index"})
7.  从Index页面，uni.redirectTo({url:"/pages/info/info"})
8. 从Info页面点击页面左上角返回或者uni.navigateBack()返回到Index页面
9. 再次进入Info页面，出现文描述中的截图

**预期结果**
可以获取到res.context

**实际结果**
见问题描述

**系统信息:**
 - 发行平台: [H5]
 - 操作系统 [Win11 or MacOS12.5.1]
 - HBuilderX版本 [3.6.4.20220922]
 - uni-app版本 [使用HBuilder创建]
 - 设备信息 [Edge浏览器]

**补充信息**
无

**Comment by zhetengbiji** [comment]
https://ask.dcloud.net.cn/question/154702
