### ISSUE TITLE
scroll-view 设置:scroll-x="true" :enable-flex="true"，编译H5后，uni-scroll-view-content并没有设置display：flex

### ISSUE THREAD

**Issue by milo-wjh** [dcloudio/uni-app#4014]
**问题描述**
scroll-view 设置:scroll-x="true" :enable-flex="true"，编译H5后，uni-scroll-view-content并没有设置display：flex；
其他小程序端正常

**复现步骤**
```
<scroll-view :scroll-x="true" :enable-flex="true" style="height: 50px;">
  <view style="height: 50px;width:100px;" v-for="item in 10">{{item}}</view>
</scroll-view>
```

**预期结果**

**实际结果**
![image](https://user-images.githubusercontent.com/20457324/203262213-8f0aa56c-31d9-4996-96aa-09bea96fbba2.png)

**系统信息:**
 - 发行平台: H5
 - 操作系统 chrome
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号3.6.5

**Comment by milo-wjh** [comment]
没有人遇到同样的问题吗？

**Comment by milo-wjh** [comment]
```
uni-scroll-view[enable-flex="true"] {
    white-space: nowrap;
}
uni-scroll-view[enable-flex="true"] .item {
    display: inline-block;
}
```
只能这样解决了

**Comment by zhetengbiji** [comment]
根据文档显示，此属性目前仅支持微信小程序平台
