### ISSUE TITLE
input 组件 type为digit时 输入小数点 placeholder 显示在数字下面

### ISSUE THREAD

**Issue by TStoneLee** [dcloudio/uni-app#4022]
**问题描述**
input 组件 type为digit时 输入小数点 placeholder 显示在数字下面
**复现步骤**
官方展示的H5组件二维码在IOS16.0.2，使用Safari打开即可复现

**预期结果**
有小数点时placeholder不要展示
 - 操作系统：iOS 16.0.2
 - - 设备信息：iPhoneXs, iPhone14pro

**补充信息**
输入小数点时，input组件的placeholder display:none消失了，但是input却能显示输入的内容

**Comment by StrivingRabbit** [comment]
b2af305e2bb0e420239d5cc27427662d34320ade

**Comment by TStoneLee** [comment]
大佬，inputmode = decimal 在IOS系统上不显示负号，还有一个问题，为什么IOS系统的Safari（没有版本限制）只要输入连续输入两次小数点，则input的显示为空，（如：4.再次输入小数点，则在input不会显示4.而是显示空白，此时placeholder仍处于消失状态）其实是有数据的 cachedValue和valueSync都是有数据的， $event.target.value，this.$refs.input.value则是空
![IMG_AB9E286E25D6-1](https://user-images.githubusercontent.com/33252445/204209579-45795cf4-ecc5-4d64-81a5-6c1d97ac5347.jpeg)

**Comment by TStoneLee** [comment]
如果输入4.再次输入小数点，则$event.target.value，this.$refs.input.value与this.valueSync this.cachedValue没有保持一致（大佬，本地uniapp项目怎么调试呀？h5打包出的dist目录下的index.html打开会报错

**Comment by StrivingRabbit** [comment]
safari 中，确实连续输入 `.` 就会清空数据，又因为并没有触发 input 事件因此导致内部数据没有同步，会调研此问题。
