### ISSUE TITLE
input组件在安卓手机上的问题（pc端没问题）

### ISSUE THREAD

**Issue by zhaohuanggu** [dcloudio/uni-app#4024]
使用input组件写了一个验证码，然后要在上一个验证码输入后下一个验证码输入框聚焦，使用ref去控制，结果发现dom下面根本没有focus这个属性，然后我打印了dom下的属性，都没有能用的，解决了一天都不知道怎么弄，愁死我了。但是用那个uni下的获取dom的api又报错，难道非得我自己去写一个input框？
我发现用nvue时就有focus属性，但是nvue又不能用svg图片，但是这个页面又必须用svg，愁死

**Comment by zhaohuanggu** [comment]
let node=''
					for(let key in newVal){
						if(newVal[key]&&!oldVal[key]&&key<5&&!newVal[key-0+1]){
							node='vali'+(key-0+1)
							this.$refs[node][0].$refs.input.focus()
						}
						if(!newVal[key]&&oldVal[key]&&key>0&&newVal[key-1]&&!newVal[key-0+1]){
							node='vali'+(key-1)
							this.$refs[node][0].$refs.input.focus()
						}
					}
这是我写的代码，我是去监听了验证码输入框的值，根据值的变化让我想要的输入框聚焦，这个代码在pc端是没问题的，但是到安卓手机上就只能this.$refs[node][0]到这里有值，然后这个值是一个对象，对象下面没有focus属性或者方法，然后打印这个下面的focus的值是未定义

**Comment by zhetengbiji** [comment]
不“拿dom”，使用数据驱动对应的属性即可控制焦点获得和失去。

**Comment by zhetengbiji** [comment]
另外你验证码每个数字都是一个输入框吗？

据我了解，市面上其他人是用一个输入框，然后通过样式让它看起来像是多个输入框。不然需要自己控制删除输入粘贴等。

**Comment by zhaohuanggu** [comment]
验证码每个数字都是一个输入框，同时我刚才尝试了，通过数据驱动只能生效一次，后面就不生效了

**Comment by zhaohuanggu** [comment]
我网上找到一个范例实现了像你说的那个，感觉不错，没有对dom进行操作，就用它了

**Comment by zhaohuanggu** [comment]
非常感谢，uniapp在移动端我尽量以后不想着去操作dom

**Comment by zhetengbiji** [comment]
> 验证码每个数字都是一个输入框，同时我刚才尝试了，通过数据驱动只能生效一次，后面就不生效了

vue的特性，文档里也有对应的注意事项：https://uniapp.dcloud.net.cn/component/input.html

**Comment by zhetengbiji** [comment]
> 验证码每个数字都是一个输入框，同时我刚才尝试了，通过数据驱动只能生效一次，后面就不生效了

也可以试试多个数字在一个输入框里，这样可以免去自己处理：新增、删除、粘贴 等

**Comment by zhaohuanggu** [comment]
非常感谢，现在又出现个问题，我删除一个验证码数字后，要聚焦到上一个数字上面，然后这个光标要在这个数字后面，但是我发现这个光标停留在数字前方了，然后看到有cursor属性，用了结果不生效这个怎么做，网上查的text-align也没效果

**Comment by zhaohuanggu** [comment]
for(let key in newVal){
	if(newVal[key]&&!oldVal[key]&&key<5&&!newVal[key-0+1]){
		this.focusIndex=key-0+1
	}
	if(!newVal[key]&&oldVal[key]&&key>0&&newVal[key-1]&&!newVal[key-0+1]){
		this.focusIndex=key-1
	}
}
现在代码这么写的，还是用的focus属性进行控制聚焦，聚焦是实现了，但是聚焦是在已输入数字的前方

**Comment by zhetengbiji** [comment]
可以尝试参考一下其他人的：

[https://ext.dcloud.net.cn/search?q=验证码](https://ext.dcloud.net.cn/search?q=%E9%AA%8C%E8%AF%81%E7%A0%81)
