### ISSUE TITLE
内置组件input在safari浏览器（版本16.1 ）中动态改变disabled，input编辑状态失效

### ISSUE THREAD

**Issue by zhang-shaoqiang** [dcloudio/uni-app#4025]
**问题描述**
[问题描述：在safari浏览器中内置组件input改变disabled属性，从true改为false，input仍不可编辑]

**复现步骤**

```vue
<template>
  <input :disabled="disabled" v-model="value" />
  <button @click="disabled = !disabled">disabled: {{ disabled }}</button>
</template>

<script setup lang="ts">
  import { ref } from 'vue';
  const value = ref<string>('这是输入框默认值');
  const disabled = ref<boolean>(false);
</script>
```

**预期结果**
动态改变input的disabled属性，input的输入状态可控

**实际结果**
disabled从true改为false时，input仍不可编辑

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [IOS16、macOS13.0.1]
 - uni-app版本 [3.0.0-alpha-3061120221128002]
 - 设备信息 [macbook pro]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
经排查，input增加disabled时，input携带了readonly属性，取消disabled时readonly仍存在
<img width="799" alt="image" src="https://user-images.githubusercontent.com/16910047/204311402-a935590e-8abd-44b4-ad0d-df8c0ead63a2.png">

**Comment by StrivingRabbit** [comment]
#21b14ce320e92c3437c64ad3aeb2cb54328fe59c
