### ISSUE TITLE
提高cli编译灵活性

### ISSUE THREAD

**Issue by yaomo** [dcloudio/uni-app#403]
**新功能描述**
cli项目， 可否把uni-build里的逻辑开放出来

**现状及问题**
开发微信小程序的云开发， 比如cloudfunction可以自己改vue.config.js配置自己copy到dist目录，但是如果想自定义微信小程序的project.config.json里的字段却没办法实现，比如自定义”cloud": true,  miniprogramRoot, cloudfunctionRoot 等，另外开发者工具中自定义编译的配置没法保存到miniprogram字段下的list中

**尝试方案**
目前是在根目录下新建cloudfunctions目录，新建project.config.json/vue.config.js，然后通过vue.config.js 配置copy cloudfunction、project.config.json到dist目录中，如图

![image](https://user-images.githubusercontent.com/7162798/58223954-652ed580-7d4e-11e9-9f54-a62f04f6da84.png)
![image](https://user-images.githubusercontent.com/7162798/58223979-7a0b6900-7d4e-11e9-8d32-545e90f40a52.png)
其实也可以像mpvue那样，使用根目录下的project.config.json，微信中自定义编译配置可以自动保存到文件中
问题是这样的话，dist中dev下有个project.config.json ，mp-weixin下也有个project.config.json，也就是uni-app编译出来的

**Comment by fxy060608** [comment]
目前应该可以直接在工程根目录创建 project.config.json，直接把整个工程拖入开发者工具，project.config.json 配置"miniprogramRoot":"dist/dev/mp-weixin/"，云函数目录，自己自由指定即可
这样的话，目前只是 mp-weixin 多了个 project.config.json

**Comment by yaomo** [comment]
> 目前应该可以直接在工程根目录创建 project.config.json，直接把整个工程拖入开发者工具，project.config.json 配置"miniprogramRoot":"dist/dev/mp-weixin/"，云函数目录，自己自由指定即可，也不用配置 copy 逻辑
> 这样的话，只是 mp-weixin 多了个 project.config.json

目前是这么做的，不同的是单独起了个webpack编译cloudfunctions，因为dev和pro还是有些差异的

**Comment by maskhb** [comment]
我也有个类似需求,需要把静态资源起一个服务丢进去,但是 cli 默认配置 Uni-build 占用 devServer 无法修改,现在有没有一个好的解决方案...

**Comment by hbcui1984** [comment]
最新版本已开放`vue.config.js`文件，参考：https://uniapp.dcloud.io/collocation/vue-config

**Comment by kniost** [comment]
并没有解决该问题，在不想编译云函数文件夹到微信中的时候没有解决办法

**Comment by SiiZhao** [comment]
> 并没有解决该问题，在不想编译云函数文件夹到微信中的时候没有解决办法

我不信

**Comment by kniost** [comment]
> > 并没有解决该问题，在不想编译云函数文件夹到微信中的时候没有解决办法
> 
> 我不信

您不信也没办法呀，因为不能配置public路径，所以云函数调用有两种方法：
1. 配置静态文件复制，到小程序的根目录下，但是这样会被微信开发者工具警告，因为把云函数文件夹也一起编译上传了
2. 如之前的问题所说
> 目前应该可以直接在工程根目录创建 project.config.json，直接把整个工程拖入开发者工具，project.config.json 配置"miniprogramRoot":"dist/dev/mp-weixin/"，云函数目录，自己自由指定即可，也不用配置 copy 逻辑
> 这样的话，只是 mp-weixin 多了个 project.config.json

但这样丧失了灵活性，直接开放输出目录就解决了

**Comment by moosoul** [comment]
提供一个解决方案
配置vue.config.js
插件可以用 filemanager-webpack-plugin 插件，该插件可以在打包完成后执行，相当于对打包完之后的project.config.json进行一次move或者copy操作都可以

**Comment by yeyu1271** [comment]
> 目前应该可以直接在工程根目录创建 project.config.json，直接把整个工程拖入开发者工具，project.config.json 配置"miniprogramRoot":"dist/dev/mp-weixin/"，云函数目录，自己自由指定即可，也不用配置 copy 逻辑
> 这样的话，只是 mp-weixin 多了个 project.config.json

现在 cli 项目如果在根目录创建 project.config.json，好像 uniapp 就不会在 dist 里面创建这个 project.config.json 了，导致小程序上传错误
