### ISSUE TITLE
app首次获取uuid不正确

### ISSUE THREAD

**Issue by llk2yq** [dcloudio/uni-app#4030]
首次获取uuid时，会弹出授权，点击授权后获取到的uuid是错误的。
杀掉APP后，再次进入，获取到的uuid是正确的，

[问答社区相关提问](https://ask.dcloud.net.cn/question/154910)

**Comment by StrivingRabbit** [comment]
社区已有相关人员回复

**Comment by llk2yq** [comment]
@StrivingRabbit 没人回复啊，我不是社区提问者，我只是搜到了那个问题。
