### ISSUE TITLE
uniapp离线打包 提示当前运行基座不包含gcanvas原生组件

### ISSUE THREAD

**Issue by ZeeRoc** [dcloudio/uni-app#4037]
1.模块已经配置好
`"modules" : {
            "Canvas" : "nvue canvas"
        }`

2.依赖也加好了
<img width="316" alt="image" src="https://user-images.githubusercontent.com/13727732/205404949-7d6a35a7-dd82-4fd3-ae62-ac18d9a7dc7a.png">

3.然后提示错误
`<Weex>[warn]WXBridgeContext.m:1310, jsLog: [JS Framework] 当前运行的基座不包含原生插件[gcanvas]，请在manifest中配置该插件，重新制作包括该原生插件的自定义运行基座 __WARN`
<img width="771" alt="image" src="https://user-images.githubusercontent.com/13727732/205405004-05a91a71-aa32-4ada-9e96-39ba4193f3b5.png">

**Comment by ZeeRoc** [comment]
@zhetengbiji @fxy060608 @Wangyaqi @dcloudhdx @anne-lxm @hulinNeil

**Comment by ZeeRoc** [comment]
uniapp凉了吗 怎么出了问题一直没人解决？ 都好久了

**Comment by zhetengbiji** [comment]
可能未配置好，可以加原生交流群去学习和讨论一下 ：892918401

**Comment by ZeeRoc** [comment]
你看一下啊配置没问题啊 又不是我一个人出现这个问题

**Comment by ZeeRoc** [comment]
> 可能未配置好，可以加原生交流群去学习和讨论一下 ：892918401
你看一下啊配置没问题啊 又不是我一个人出现这个问题

**Comment by Dronaldo17** [comment]
plist 里的配置了吗？
