### ISSUE TITLE
npx degit dcloudio/uni-preset-vue#vite-ts 创建的项目无法运行在h5

### ISSUE THREAD

**Issue by mentoorliubin** [dcloudio/uni-app#4042]
**问题描述**
npx degit dcloudio/uni-preset-vue#vite-ts 创建的项目无法运行在h5
运行dev:h5时一直卡在编译中无反应  运行其他平台可以用 

**复现步骤**
![image](https://user-images.githubusercontent.com/52729282/205801444-04c8e5a7-dacc-4592-80ed-b25c6a308c9c.png)

**系统信息:**
 - 发行平台: H5

**Comment by StrivingRabbit** [comment]
其实已经运行了，只不过日志没有打印出来，可以直接访问：http://localhost:5173/ 试试

**Comment by chenbimo** [comment]
解决方案：https://gitee.com/yicode-team/yiuni-vue3

**Comment by whitemo123** [comment]
也可以修改package.json,`"dev:h5": "uni -l info",`
