### ISSUE TITLE
钉钉小程序，页面跳转过程中发起请求，报request:fail 12

### ISSUE THREAD

**Issue by luckyhong** [dcloudio/uni-app#4043]
**问题描述**
钉钉小程序，安卓手机：页面跳转过程中发起的请求，出现request:fail 12错误

**复现步骤**
[复现问题的步骤]
1.  启动安卓手机，打开钉钉应用
2. 安装钉钉小程序
3. 通过A页面进入B页面，然后B页面通过按钮点击返回A页面，且A页面会进行接口请求，此时会报request:fail 12

**预期结果**
页面可以正常跳转且请求接口不报错

**实际结果**
接口请求报错：request:fail 12
经过测试，iOS真机是正常的，不会出现request:fail 12

**系统信息:**
 - 发行平台: 钉钉小程序
 - 操作系统：Android 11 
 - 设备信息：OPPO Reno

**Comment by StrivingRabbit** [comment]
可以查看钉钉 (文档)[https://open.dingtalk.com/document/orgapp-client/send-network-requests] 。
由网络原因导致的错误，如网络不通等。
可以在钉钉社区反馈一下
