### ISSUE TITLE
百度没百度到，想在这里看看能不能有人帮忙看看

### ISSUE THREAD

**Issue by zhaohuanggu** [dcloudio/uni-app#4044]
我现在想用uniapp做移动端和ios的项目，点击跳转到whatsapp对应人的聊天窗口里面去，然后现在要先跳转网页，如果对方有安装对应app可以唤起，这个怎么实现啊，百度到的都是java代码，uniapp怎么实现一个都没有百度到。有什么可以提供的网址或者代码吗？

**Comment by llt3677** [comment]
使用URLscheme试试
plus.runtime.openURL( "whatsapp://" )
https://www.html5plus.org/doc/zh_cn/runtime.html#plus.runtime.openURL

**Comment by zhaohuanggu** [comment]
运行环境的问题，我试试

**Comment by zhaohuanggu** [comment]
我每次都需要打包才能在mumu模拟器里看项目运行情况，否则直接通过hbuilder真机运行打开的项目一直在启动页转圈圈，我也不知道为啥，我新建空白项目运行起来也是这样

**Comment by llt3677** [comment]
mumux好用

**Comment by zhaohuanggu** [comment]
好的，我试一下

**Comment by zhaohuanggu** [comment]
感谢
