### ISSUE TITLE
onShareAppMessage在自定义组合函数中不生效

### ISSUE THREAD

**Issue by Nuyoah-ll** [dcloudio/uni-app#4047]
**问题描述**
在页面直接使用onShareAppMessage可以正常分享，但是如果将onShareAppMessage放在自定义组合函数中再使用，则不生效

**复现步骤**

useShare.ts
![image](https://user-images.githubusercontent.com/56406998/206391031-4c73d3db-6595-4939-bea7-46e451811242.png)

home.vue
![image](https://user-images.githubusercontent.com/56406998/206391246-cc79149f-bda9-4fe1-b9b8-4c4a8d9b7274.png)

**预期结果**
onShareAppMessage放在组合函数里也生效

**实际结果**
onShareAppMessage放在组合函数不生效，

**系统信息:**
 - 发行平台:  字节跳动小程序
 - 操作系统: Android
 - uni-app版本: 3.0.0-alpha-3060420220922001

**Comment by fxy060608** [comment]
需要页面中同时定义onShareAppMessage
setup里边是运行时执行的，onShareAppMessage 必须编译时就确定要注册上去。

**Comment by Nuyoah-ll** [comment]
> 需要页面中同时定义onShareAppMessage setup里边是运行时执行的，onShareAppMessage 必须编译时就确定要注册上去，编译时页面会扫描页面代码，包含onShareAppMessage的话，才自动注册。

那如果所有页面的分享参数都不一致，岂不是要在所有页面都写上onShareAppMessage，有没有什么通用解决办法吗，类似我上面写的useShare，传递title之类的（虽然这方法无效）

**Comment by fxy060608** [comment]
> > 需要页面中同时定义onShareAppMessage setup里边是运行时执行的，onShareAppMessage 必须编译时就确定要注册上去，编译时页面会扫描页面代码，包含onShareAppMessage的话，才自动注册。
> 
> 那如果所有页面的分享参数都不一致，岂不是要在所有页面都写上onShareAppMessage，有没有什么通用解决办法吗，类似我上面写的useShare，传递title之类的（虽然这方法无效）

全局mixin

**Comment by Nuyoah-ll** [comment]
> 

好的，谢谢

**Comment by Nuyoah-ll** [comment]
> 需要页面中同时定义onShareAppMessage setup里边是运行时执行的，onShareAppMessage 必须编译时就确定要注册上去，编译时页面会扫描页面代码，包含onShareAppMessage的话，才自动注册。

找到了一个可以生效的实现方法，组合函数里把onShareAppMessage放到onReady里，然后在使用该组合函数的时候，底下随便定义一个onShareAppMessage。请问一下是因为onReady里的onShareAppMessage将编译时候注册上去的空onShareAppMessage覆盖了的原因吗？
![image](https://user-images.githubusercontent.com/56406998/206402026-a7363fc2-a750-4869-8a45-bae50cb77d8b.png)
![image](https://user-images.githubusercontent.com/56406998/206402105-c56112aa-41d0-44fc-b4f5-266de4c259dd.png)

**Comment by fxy060608** [comment]
> > 需要页面中同时定义onShareAppMessage setup里边是运行时执行的，onShareAppMessage 必须编译时就确定要注册上去，编译时页面会扫描页面代码，包含onShareAppMessage的话，才自动注册。
> 
> 找到了一个可以生效的实现方法，组合函数里把onShareAppMessage放到onReady里，然后在使用该组合函数的时候，底下随便定义一个onShareAppMessage。请问一下是因为onReady里的onShareAppMessage将编译时候注册上去的空onShareAppMessage覆盖了的原因吗？ ![image](https://user-images.githubusercontent.com/56406998/206402026-a7363fc2-a750-4869-8a45-bae50cb77d8b.png) ![image](https://user-images.githubusercontent.com/56406998/206402105-c56112aa-41d0-44fc-b4f5-266de4c259dd.png)

不用onReady里边
先在页面定义onShareAppMessage
然后再调用useShare()就行了
把你的两行代码颠倒顺序

**Comment by fxy060608** [comment]
> > 需要页面中同时定义onShareAppMessage setup里边是运行时执行的，onShareAppMessage 必须编译时就确定要注册上去，编译时页面会扫描页面代码，包含onShareAppMessage的话，才自动注册。
> 
> 找到了一个可以生效的实现方法，组合函数里把onShareAppMessage放到onReady里，然后在使用该组合函数的时候，底下随便定义一个onShareAppMessage。请问一下是因为onReady里的onShareAppMessage将编译时候注册上去的空onShareAppMessage覆盖了的原因吗？ ![image](https://user-images.githubusercontent.com/56406998/206402026-a7363fc2-a750-4869-8a45-bae50cb77d8b.png) ![image](https://user-images.githubusercontent.com/56406998/206402105-c56112aa-41d0-44fc-b4f5-266de4c259dd.png)

不用onReady里边
先在页面定义onShareAppMessage
然后再调用useShare()就行了
把你的两行代码颠倒顺序

**Comment by Nuyoah-ll** [comment]
谢谢你，可以了
