### ISSUE TITLE
支持百度小程序的 routes 配置

### ISSUE THREAD

**Issue by appleone123** [dcloudio/uni-app#4050]
**新功能描述**
百度小程序提供了 routes 配置，可以将路由和文件路径解耦，并且百度方会根据该配置执行首屏优化策略，希望 uniapp 能够支持该配置

**现状及问题**
uniapp 的 mainfest.json 中虽然支持 mp-baidu 的配置节，但是该配置节下的配置却是有限制的，我尝试在该配置节下增加 routes 配置，最终编译结果中百度包的 app.json 并未包含 routes 配置，希望能够支持，我方小程序依赖该特性提升性能和进行老路由兼容。

**尝试方案**
mainfest.json 的 mp-baidu 配置节增加 routes 配置，未生效

**补充信息**
百度关于自定义路由的文档链接：https://smartprogram.baidu.com/docs/develop/framework/app_service_customroute/

**Comment by zhenyuWang** [comment]
HBuilderX 3.6.18 测试 manifest.json->mp-baidu 下配置 routes，可以编译到 app.json，请检查配置是否正确，如确认框架问题，提供测试工程

**Comment by appleone123** [comment]
升级 uni-app 包版本后验证可支持 routes 配置
