### ISSUE TITLE
UniApp.RequestPaymentOptions TypeScript 类型错误

### ISSUE THREAD

**Issue by LIN727** [dcloudio/uni-app#4054]
**问题描述**
RequestPaymentOptions 中 orderInfo 字段类型错误，文档中是 String/Object，但 uni.d.ts 文件中定义为 string。抖音小程序支付 orderInfo 为 Object 类型。

**预期结果**
定义 RequestPaymentOptions 中 orderInfo 类行支持 Object 或者直接为 any

**实际结果**
![image](https://user-images.githubusercontent.com/16315216/206978943-2c35cca8-8d8b-4230-821f-947b9a0d02b1.png)

**系统信息:**
 - 发行平台: [抖音小程序]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
感谢反馈，已处理，CLI 创建工程可以单独更新 @dcloudio/types 到 3.2.3，否则请等待 HBuilderX 更新。
