### ISSUE TITLE
通过配置manifest.json来实现微信开发者工具-本地设置-取消勾选 将JS编译成ES5

### ISSUE THREAD

**Issue by Silentdoer** [dcloudio/uni-app#4058]
默认情况下微信开发者工具会自动将JS编译为ES5，但是我想取消，所以配置了uni-app项目的manifest.json里的：
```json
 "setting" : {
    "urlCheck" : false,
    "es6" : false
},
```
其中"es6": false能够使：将JS编译为ES5 取消勾选；
但是这里难道不是应该是"es5": false，或者"es6": true才是取消勾选 将JS编译为ES5 吗？这个值写反了吧？

**Comment by zhenyuWang** [comment]
微信小程序设计如此 [文档](https://developers.weixin.qq.com/miniprogram/dev/devtools/projectconfig.html#setting)
