### ISSUE TITLE
自定义组件编译模式 下 canvas draw(false,()=>{console.log(drawed)}) 不触发回调方法

### ISSUE THREAD

**Issue by frandior** [dcloudio/uni-app#406]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
自定义组件编译模式 下 canvas draw(false,()=>{console.log(drawed)}) 不触发回调方法
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
console.log('beforeDraw')
ctx.draw(false, () => {
    console.log('drawed')
    uni.canvasToTempFilePath({
       width: this.canvasWidth,
       height: this.canvasHeight,
       canvasId: 'Canvas',
       success: res => {
           console.log(res.tempFilePath);
           this.$emit('pushImg',res.tempFilePath)
       } 
   })
});
console.log('图片呢？')
**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
控制台出现
beforeDraw
图片呢？
drawed
**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/23611230/58230045-ca41f580-7d65-11e9-85bc-1599af9d3252.png)

**系统信息:**
 - 发行平台:微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 今天刚更新到最新也这样
 - uni-app版本
 - 设备信息 微信小程序模拟器

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
我是放在自定义组建里的

**Comment by zhetengbiji** [comment]
自定义组件内获取 CanvasContext ：
```js
uni.createCanvasContext('#canvas', this)
```
