### ISSUE TITLE
放出 @dcloudio/vite-plugin-uni 的源代码

### ISSUE THREAD

**Issue by ModyQyW** [dcloudio/uni-app#4066]
**新功能描述**

放出 @dcloudio/vite-plugin-uni 的源代码

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/tree/next/packages/vite-plugin-uni

**Comment by ModyQyW** [comment]
这个是不是可以合并到默认分支 dev 方便找一点？

**Comment by fxy060608** [comment]
> 这个是不是可以合并到默认分支 dev 方便找一点？

dev是vue2
next是vue3
没法合并

**Comment by ModyQyW** [comment]
我认为 dev 和 next 并不能直观地反映和 vue 版本的关系，是否可以在对应分支的 README 文件内补充一下说明呢？

**Comment by fxy060608** [comment]
> 我认为 dev 和 next 并不能直观地反映和 vue 版本的关系，是否可以在对应分支的 README 文件内补充一下说明呢？或者将分支名调整为 vue2 和 vue3？

@zhetengbiji 可以考虑怎么优化下

**Comment by ModyQyW** [comment]
https://github.com/dcloudio/uni-app/pull/4069
