### ISSUE TITLE
支持更多微信小程序项目配置项

### ISSUE THREAD

**Issue by ModyQyW** [dcloudio/uni-app#4067]
**新功能描述**

https://developers.weixin.qq.com/miniprogram/dev/devtools/projectconfig.html

**Comment by fxy060608** [comment]
自己可以直接在项目根目录创建mini.project.json

**Comment by ModyQyW** [comment]
微信小程序需要的是 project.config.json。

我也没有在文档里找到在项目根目录创建 project.config.json 可以有效配置微信小程序的指引。是否可以加一下文档？

**Comment by ModyQyW** [comment]
> 微信小程序需要的是 project.config.json。
> 
> 我也没有在文档里找到在项目根目录创建 project.config.json 可以有效配置微信小程序的指引。是否可以加一下文档？

@fxy060608 创建 uniapp (vue3 + vite + ts) 项目，实测在项目根目录下创建的 project.config.json 不会自动复制到 dist 相关目录下。能否进一步说明下或者在文档内增加一下说明？
