### ISSUE TITLE
vue3 小程序中的数据更新疑惑

### ISSUE THREAD

**Issue by monyee** [dcloudio/uni-app#4070]
**问题描述**

下面是官方文档对性能优化的建议：

[#](https://uniapp.dcloud.net.cn/tutorial/performance.html#%E4%BC%98%E5%8C%96%E6%95%B0%E6%8D%AE%E6%9B%B4%E6%96%B0)优化数据更新
在 uni-app 中，定义在 data 里面的数据每次变化时都会通知视图层重新渲染页面。所以如果不是视图所需要的变量，可以不定义在 data 中，可在外部定义变量或直接挂载在vue实例上，以避免造成资源浪费。

[#](https://uniapp.dcloud.net.cn/tutorial/performance.html#%E9%95%BF%E5%88%97%E8%A1%A8)

如果是vue3这种非显示定义data,扁平式的写法如何优化， 以下几种方式是否会触发setdata ? 影响性能？

1.   定义ref   eg: const name = ref()
2.  定义computed
3.  接收provider  eg: const p = inject('xxx')
4.  watch一个外部响应对象

假设上述几种情况 都未关联页面视图层模板(<template>)插值   （未关联定义的响应变量）

**Comment by fxy060608** [comment]
在vue3中，只要在模板中未使用，均不会触发setData

**Comment by monyee** [comment]
> 在vue3中，只要在模板中未使用，均不会触发setData

awesome !
