### ISSUE TITLE
uni-app 运行支付宝小程序报错

### ISSUE THREAD

**Issue by github-ZH-cn** [dcloudio/uni-app#4072]
**问题描述**
运行到支付宝小程序出现下面报错,微信,h5都没有问题

**复现步骤**
点击运行支持支付宝小程序

![image](https://user-images.githubusercontent.com/67533362/207998810-6a2c4520-2466-47ed-86db-21a0c8f31df7.png)

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
发布平台: 支付宝小程序
操作系统 window11
HBuilderX版3.6.14.20221215
uni-app版本使用hbuilder创建的项目
设备信息 iphone 13

**补充信息**
是不是我代码写的有问题

**Comment by ModyQyW** [comment]
我个人没能从这个截图提取到有效信息。可以提供相关代码吗？

如果你使用了 `try { ... } catch { ... }`，请改成 `try { ... } catch (error) { ... }` 试试。

**Comment by zhetengbiji** [comment]
参考：https://ask.dcloud.net.cn/question/159840
