### ISSUE TITLE
百度开发者工具无法自动热更新(vue3)

### ISSUE THREAD

**Issue by zzzz1Mo** [dcloudio/uni-app#4074]
**问题描述**
uni-app编译至百度开发者工具，无法 **自动** 热更新。

**复现步骤**
1.  新建uni-app项目，选择vue3版本，运行至百度开发者工具；
2. 项目打开后，再在HBuilder内更改代码并保存，例如：onLoad(()=> console.log('pageLoad'))；
3. 查看【百度开发者工具】控制台。

**预期结果**
控制台输出日志’pageLoad‘。

**实际结果**
无日志，须手动点击【百度开发者工具】内的“编译”按钮，等待编译完成(特别慢，空白项目都要等3~5秒)，控制台才有输出。

**系统信息:**
 - 发行平台：百度智能小程序
 - 操作系统：Android 11.0+
 - HBuilderX版本：3.6.13
 - 设备信息：魅族18Pro，iPadAir

**补充信息**
最近有需求开发百度小程序，不知道3.6.13之前版本是不是也无法自动热更新，社区相关问题就一条 [BUG2及回复](https://ask.dcloud.net.cn/question/146145)。
是已有BUG还是我的姿势不对？
请相关人员尽快回复，每次更改代码都需要自己手动点击编译(关键是这个编译过程特别慢)，很影响进度的。

**Comment by StrivingRabbit** [comment]
请切换编译模式为 `依赖分析` 试试
![Snipaste_2022-12-20_17-37-07](https://user-images.githubusercontent.com/33573212/208634148-cdda7b4c-248f-464f-8d0b-88bea7d31249.jpg)

**Comment by zzzz1Mo** [comment]
> 请切换编译模式为 `依赖分析` 试试 ![Snipaste_2022-12-20_17-37-07](https://user-images.githubusercontent.com/33573212/208634148-cdda7b4c-248f-464f-8d0b-88bea7d31249.jpg)

找到问题了，项目信息-本地配置 下 ‘启用快速加载’、‘启用多线程编译’开启后，编译速度显著提升。
但在manifest.json文件下mp-baidu：{} 找不到对应配置项；
导致每次运行or重新运行后，都需要手动打开这两项并切换编译模式为‘依赖分析’；
可否与百度小程序[项目配置文件](https://smartprogram.baidu.com/docs/develop/devtools/editor_set/l)同步一下？

**Comment by StrivingRabbit** [comment]
@zzzz1Mo 
可以在 `HX根目录//plugins/uniapp-cli-vite/node_modules/@dcloudio/uni-mp-baidu/dist/uni.compiler.js` 中搜索 `compilation-args` 将 `selected` 修改为 `-2` 试试看。

**Comment by zzzz1Mo** [comment]
> @zzzz1Mo 可以在 `HX根目录//plugins/uniapp-cli-vite/node_modules/@dcloudio/uni-mp-baidu/dist/uni.compiler.js` 中搜索 `compilation-args` 将 `selected` 修改为 `-2` 试试看。

可行，并更改了默认配置。感谢
