### ISSUE TITLE
@dcloudio/types 3.2.3 MapContext 类型定义与文档不一致

### ISSUE THREAD

**Issue by ModyQyW** [dcloudio/uni-app#4077]
**问题描述**

@dcloudio/types 3.2.3 MapContext 类型定义与文档不一致

**文档内容**

<img width="1379" alt="image" src="https://user-images.githubusercontent.com/31850793/208639746-ac1eb435-d995-4f56-8ce3-4d65dd59ae15.png">

其中，translateMarker 方法 OBJECT 参数列表如下。

<img width="1079" alt="image" src="https://user-images.githubusercontent.com/31850793/208640201-9ea40917-03b3-41a9-a384-142b089eb8b7.png">

**实际结果**

mapContext 缺少了大量方法。

<img width="778" alt="image" src="https://user-images.githubusercontent.com/31850793/208639821-ce0f35a6-d36b-4d03-a33e-9c49fd7de265.png">

其中，translateMarker 方法 OBJECT 参数列表如下。缺少 `success`。

<img width="788" alt="image" src="https://user-images.githubusercontent.com/31850793/208640140-db714696-ea32-43d5-a794-122338330d0e.png">

**Comment by zhetengbiji** [comment]
已更新 v3.2.4
