### ISSUE TITLE
建议app.vue的生命周期onLaunch 参数中包含path与query

### ISSUE THREAD

**Issue by exvu** [dcloudio/uni-app#408]
**新功能描述**
建议添加app.vue的生命周期onLaunch 参数中传递path与query

**现状及问题**
微信小程序能通过onLaunch获取参数，但是今天测试h5平台在app.vue的生命周期onLaunch只能拿到scene这一个参数。

**尝试方案**
对于h5平台 ，临时使用window.location解决无法获取参数的问题

**Comment by zhetengbiji** [comment]
HBuilderX alpha 2.0.2 及以上版本已支持
