### ISSUE TITLE
v-for循环子组件，v-model取不到值

### ISSUE THREAD

**Issue by yp199618** [dcloudio/uni-app#4081]
```
<view v-for="item in list">
    <child v-model="item.name"></child>
</view>

list: [
   {
       name: '张三'
   }
]

// child 
<view> {{value}} | </view>

props: {
    value: String
}
```

预期：显示  `张三 | `
实际：显示 `|`

**Comment by zhetengbiji** [comment]
vue2还是vue3？

**Comment by yp199618** [comment]
不好意思刚看到，vue2,  还蛮严重的一个问题 @zhetengbiji

**Comment by zhetengbiji** [comment]
实际情况是不是要比你写的例子更复杂才能复现？

**Comment by yp199618** [comment]
问题可能出在数据是接口返回的，加个setTimeout应该就能复现了 @zhetengbiji

**Comment by zhetengbiji** [comment]
> 问题可能出在数据是接口返回的，加个setTimeout应该就能复现了 @zhetengbiji

我猜测实际情况可能要比这个更复杂一些，不然应该会有很多人反馈。比如：需要多层v-for嵌套，或者使用了更复杂的表达式

**Comment by yp199618** [comment]
好的，我再试下，不出意外的话明早给你发一份能复现的可执行代码 @zhetengbiji

**Comment by yp199618** [comment]
你好，我又看了下，我应该搞错了，可能是下边问题导致的，

当改变子组件值时，父组件不会跟着改变，这一点和web端表现不一致是否正常呢

[github地址](https://github.com/yp199618/uniapp-demo)

**Comment by zhetengbiji** [comment]
表现确实不同，但是目前设计如此。

小程序上组件目前传输的数据是深克隆（实际进行了JSON序列化转换）的，不再包含之前的引用关系，所以不会导致父组件值变化。

Web上虽然有这样的表现，但是直接修改props的值却是错误用法：违背了Vue的单向数据流。

正确用法应该是通知父组件来修改值，而不是直接修改父组件的值。

**Comment by yp199618** [comment]
好的，明白，谢谢您的指点，祝好！
