### ISSUE TITLE
@dcloudio/types MapContext 的 includePoints 方法不支持 success、fail 和 complete？

### ISSUE THREAD

**Issue by ModyQyW** [dcloudio/uni-app#4082]
@dcloudio/types MapContext 的 includePoints 方法，OBJECT 参数列表只有 points 和 padding。https://uniapp.dcloud.net.cn/api/location/map.html

<img width="1484" alt="image" src="https://user-images.githubusercontent.com/31850793/209255185-c3972d7e-e1f7-43d7-9eee-073a4ae443b8.png">

在微信小程序文档中，还有 success、fail 和 complete。https://developers.weixin.qq.com/miniprogram/dev/api/media/map/MapContext.includePoints.html

<img width="1319" alt="image" src="https://user-images.githubusercontent.com/31850793/209256445-8797eb06-c68c-4179-80bd-ce3385d9df1c.png">

在 uni-app 里 MapContext 的 includePoints 方法是不支持 success、fail 和 complete 吗？

**Comment by zhetengbiji** [comment]
微信小程序已经支持了，其他端未支持，后续会更新一下文档和相关类型定义。

**Comment by zhetengbiji** [comment]
@dcloudio/types 已更新至 3.2.6
