### ISSUE TITLE
支持 uni.promises.[api]，增加官方的带有 TypeScript 类型定义的 Promise 化的 API

### ISSUE THREAD

**Issue by ModyQyW** [dcloudio/uni-app#4084]
**新功能描述**

支持 uni.promises.[api]，增加官方的带有 TypeScript 类型定义的 Promise 化的 API。

```typescript
uni
  .promises
  .getLocation({ ... })
  .then((result) => { ... })
  .catch((error) => { ... })
  .finally(() => { ... })
```

**现状及问题**

目前，uni-app 提供了基于 success、fail、complete 的 API 及其类型定义。对于 Promise 化的 API，没有类型定义。

这降低了开发者的实际体验，迫使开发者只能选择基于 success、fail、complete 的 API，并容易陷入回调地狱中。

**尝试方案**

[uni-promises](https://github.com/uni-helper/uni-promises)

**Comment by StrivingRabbit** [comment]
可以升级 @dcloudio/types@3.3.0 试试看

**Comment by StrivingRabbit** [comment]
部分 api promise 化提示已支持，后续进度请跟踪 #3009 查看
