### ISSUE TITLE
@dcloudio/types 缺少 uni.vibrate 的类型定义

### ISSUE THREAD

**Issue by ModyQyW** [dcloudio/uni-app#4085]
[文档链接](https://uniapp.dcloud.net.cn/api/system/vibrate.html#vibrate)

<img width="1035" alt="image" src="https://user-images.githubusercontent.com/31850793/209276719-1d79f030-bec3-4f3d-8f2d-55e6464d6711.png">

但 @dcloudio/types 缺少 uni.vibrate 的类型定义。

**Comment by zhetengbiji** [comment]
@dcloudio/types 已更新至 3.2.6
