### ISSUE TITLE
不可以使用Object.defineProperty()对uni.request进行修改

### ISSUE THREAD

**Issue by rengy-github** [dcloudio/uni-app#409]
不可以使用Object.defineProperty()对uni.request进行修改，可否支持呢？

**Comment by zhetengbiji** [comment]
在部分平台 uni 为 Proxy 对象，不可修改，可以尝试修改对应平台的 request 方法，如：wx.request

**Comment by StrivingRabbit** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
