### ISSUE TITLE
使用命令行创建最新Vue3/Vite typescript版 v-bind在css中使用编译错误

### ISSUE THREAD

**Issue by xuuui** [dcloudio/uni-app#4090]
**问题描述**
使用命令行创建最新Vue3/Vite typescript版 v-bind在css中使用编译错误

**复现步骤**
命令行创建使用Vue3/Vite typescript版

![1672217618515](https://user-images.githubusercontent.com/36097878/209785806-0fff393b-7e97-4f4d-b7be-edb6209c784a.jpg)

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
h5中
![image](https://user-images.githubusercontent.com/36097878/209785879-e15b98e0-8d0a-4577-b78c-e45dd22fc9c3.png)
微信小程序中
![image](https://user-images.githubusercontent.com/36097878/209786085-63ba5bfd-932b-44a0-9e26-5d44b521643f.png)

**系统信息:**
![image](https://user-images.githubusercontent.com/36097878/209786233-25e15096-48d0-4727-bac3-86d98769dae3.png)

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
更新至 v3.0.0-alpha-3061520221220001 试下

https://github.com/dcloudio/uni-app/issues/4076

**Comment by xuuui** [comment]
更新至 v3.0.0-alpha-3061520221220001后
h5中有值但是显示未定义
![O9DUA09_14ZW8KW{OB`TDFL](https://user-images.githubusercontent.com/36097878/209949476-7ecc064e-6f73-4335-ad3c-ae10c0767744.png)
微信小程序中有值但是没有变量名
![1672315795589](https://user-images.githubusercontent.com/36097878/209949549-f473b3c4-2219-4d4e-8089-8cb276090832.png)
希望能和之前的一样--hash--变量名

**Comment by fxy060608** [comment]
> 更新至 v3.0.0-alpha-3061520221220001后 h5中有值但是显示未定义 ![O9DUA09_14ZW8KW{OB`TDFL](https://user-images.githubusercontent.com/36097878/209949476-7ecc064e-6f73-4335-ad3c-ae10c0767744.png) 微信小程序中有值但是没有变量名 ![1672315795589](https://user-images.githubusercontent.com/36097878/209949549-f473b3c4-2219-4d4e-8089-8cb276090832.png) 希望能和之前的一样--hash--变量名

小程序平台不支持 --hash-cssvars.height 这样的变量赋值，所以才默认启用生产模式的仅保留hash

**Comment by xuuui** [comment]
> > 更新至 v3.0.0-alpha-3061520221220001后 h5中有值但是显示未定义 ![O9DUA09_14ZW8KW{OB`TDFL](https://user-images.githubusercontent.com/36097878/209949476-7ecc064e-6f73-4335-ad3c-ae10c0767744.png) 微信小程序中有值但是没有变量名 ![1672315795589](https://user-images.githubusercontent.com/36097878/209949549-f473b3c4-2219-4d4e-8089-8cb276090832.png) 希望能和之前的一样--hash--变量名
> 
> 小程序平台不支持 --hash-cssvars.height 这样的变量赋值，所以才默认启用生产模式的仅保留hash

或许可以改为下划线命名

**Comment by fxy060608** [comment]
> > > 更新至 v3.0.0-alpha-3061520221220001后 h5中有值但是显示未定义 ![O9DUA09_14ZW8KW{OB`TDFL](https://user-images.githubusercontent.com/36097878/209949476-7ecc064e-6f73-4335-ad3c-ae10c0767744.png) 微信小程序中有值但是没有变量名 ![1672315795589](https://user-images.githubusercontent.com/36097878/209949549-f473b3c4-2219-4d4e-8089-8cb276090832.png) 希望能和之前的一样--hash--变量名
> > 
> > 
> > 小程序平台不支持 --hash-cssvars.height 这样的变量赋值，所以才默认启用生产模式的仅保留hash
> 
> 或许可以改为下划线命名

可以查看vue官方针对此问题的相关提交日志及issue：
https://github.com/vuejs/core/commit/57c901383792176fd7267b7d34d845088dbeff63
