### ISSUE TITLE
关于canvas组件原生化

### ISSUE THREAD

**Issue by pikachen-pick** [dcloudio/uni-app#4092]
**现状及问题**
我习惯于使用原生的canvas，但是uniapp的canvas显然是被二次包装过的，导致我二次上手变得有点困难，能否有一种方式或者完善计划，使得用户可以主动选择使用包装canvas（例如有一个名为uni-canvas的组件）或者原生h5的canvas？

**Comment by zhetengbiji** [comment]
你审查元素就会发现实际上就是uni-canvas组件。canvas会渲染为uni-canvas。你可以尝试修改（不是替换）[ignoredElements](https://v2.vuejs.org/v2/api/#ignoredElements)，跳过vue的处理。或者推荐直接使用document.createElement来创建，也可以将此操作包装在自己的my-canvas组件内。

以上说的是Web端，如果是App可以利用[renderjs](https://uniapp.dcloud.net.cn/tutorial/renderjs#renderjs)实现以上。
