### ISSUE TITLE
HBuilder X 已登录的用户过期问题

### ISSUE THREAD

**Issue by Q-kil** [dcloudio/uni-app#4096]
**问题描述**
原APP项目需要优化，打开 HBuilder X ，上次登录的状态已失效，状态为：未登录。项目没跑起来，报错信息：
![image](https://user-images.githubusercontent.com/28499836/210520626-83896589-7ae7-4444-b812-14b37deaa9f1.png)

**预期结果**
给一个未登录提示

**系统信息:**
 - 发行平台: [H5平台、App]
 - 操作系统 [Chrome版本 108.0.5359.124（正式版本） (arm64)、Android 11.0]
 - HBuilderX版本 [3.5.3.20220729]

**Comment by Q-kil** [comment]
补充报错信息：
`(function () {{var e = m;var _t21 = {};if (1 === e.length) _t21 = e[0], sn = sn.init(_t21), sn.isDefault = !0;else {var _t22 = ["auth", "callFunction", "uploadFile", "deleteFile", "getTempFileURL", "downloadFile", "database", "getCurrentUSerInfo", "importObject"];var _n14;_n14 = e && e.length > 0 ? "应用有多个服务空间，请通过uniCloud.init方法指定要使用的服务空间" : y ? "应用未关联服务空间，请在uniCloud目录右键关联服务空间" : "uni-app cli项目内使用uniCloud需要使用HBuilderX的运行菜单运行项目，且需要在uniCloud目录关联服务空间", _t22.forEach(function (e) {sn[e] = function () {return console.error(_n14), Promise.reject(new M({ code: "SYS_ERR", message: _n14 }));};});}`

**Comment by Wangyaqi** [comment]
登录HBuilderX关联服务空间即可
