### ISSUE TITLE
安卓平板上的微信小程序，字体不稳定

### ISSUE THREAD

**Issue by zui4yi1** [dcloudio/uni-app#4100]
**问题描述**

碰到一个非常奇怪的问题。在安卓平板上访问微信小程序(iOS未尝试)，第一次进入小程序，字体正常；点击“..."重新进入小程序，字体变大。重复步骤，字体循环往复：正常->变大->正常->变大....

**复现步骤**
[复现问题的步骤]
1.  在平板上第一次启动小程序；
2. 查看字体，字体正常。
3. 点击”..."重新进入小程序，
4.  查看字体，字体变大。
5. 再次点击”..."重新进入小程序
6. 查看字体，字体又变正常
7. 重复“重新进入小程序”操作
8. 查看字体，一会正常，一会不正常，很稳定的循环往复。

[或者可以直接贴源代码]
注：我们使用的单位都是rpx, 使用uni cli 在vscode上开发，使用的是vue3
下面是manifest.json的配置
{
  "name": "xxxx",
  "appid": "xxxx",
  "description": "",
  "versionName": "1.0.0",
  "versionCode": "100",
  "transformPx": false,
  "app-plus": {},
  "quickapp": {},
  "mp-weixin": {
    "appid": "xxxxxxxxxxxxx",
    "setting": {
      "urlCheck": false,
      "minified": true,
      "postcss": false,
      "es6": true,
      "bigPackageSizeSupport": false
    },
    "usingComponents": true
  },
  "h5": {
    "devServer": {
      "disableHostCheck": true,
      "proxy": {
        "/api": {
          "target": "xxxxxxxxxxxxxx",
          "changeOrigin": true,
          "secure": false
        }
      }
    }
  },
  "uniStatistics": {
    "enable": false
  }
}

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
小程序的字体稳定正常。

**实际结果**
[这里请贴上你的报错截图或文字]
![a1](https://user-images.githubusercontent.com/3435146/210922622-185feef8-8a09-4a21-ab7b-d827bdcfef64.jpg)
![a2](https://user-images.githubusercontent.com/3435146/210922638-7e316911-92e8-437b-a930-346b01520862.jpg)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

安卓平板（任意系统或品牌均会出现）

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
根据反馈初步分析，需要反馈到微信小程序社区，由安卓客户端的相关开发人员修复。
