### ISSUE TITLE
vue3 vite typescript 微信小程序端重复打包第三方库

### ISSUE THREAD

**Issue by xuuui** [dcloudio/uni-app#4101]
**问题描述**
vue3 vite typescript 微信小程序端重复打包第三方库

**复现步骤**
B库引入A
项目引入A,B库

打包h5,微信小程序

微信小程序端重复打包A
h5端正常

**预期结果**
微信小程序不重复打包

**实际结果**
小程序端verder.js
第一次
![image](https://user-images.githubusercontent.com/36097878/210965976-9f87d2c2-a22f-4a6f-95c4-55ad4bd3f627.png)
第二次
![image](https://user-images.githubusercontent.com/36097878/210966012-6ba21f0f-463c-4456-8f38-27d3dbe45283.png)
h5端 index.js
正常一次
![image](https://user-images.githubusercontent.com/36097878/210966046-ba386901-f372-444d-8b42-e3db81a1fb99.png)

**系统信息:**
![image](https://user-images.githubusercontent.com/36097878/210966354-09364d5f-975a-41bb-9fcb-a24471378556.png)

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
发测试工程

**Comment by xuuui** [comment]
[uni-test.zip](https://github.com/dcloudio/uni-app/files/10359092/uni-test.zip)
根目录pnpm i -r

@r-uni/use 引入 @r-uni/utils
examples/demo引入 @r-uni/utils @r-uni/use
编译后微信小程序@r-uni/utils库函数重复引入，h5正常

**Comment by fxy060608** [comment]
可以调整下 vite.config.ts
注意，调整 preserveSymlinks 的话，会导致pnpm 下 node_modules 中的 vue 组件编译出来的目录很长
```ts
import { defineConfig } from 'vite'
import uni from '@dcloudio/vite-plugin-uni'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [uni(),
  {
    name: 'preserveSymlinks',
    config() {
      return {
        resolve: {
          preserveSymlinks: false
        }
      }
    },
  }
  ],
})

```

**Comment by gaokun** [comment]
@fxy060608 
Hi, 请教一下.
`uni:mp`插件为什么将`preserveSymlinks`设置为了true, 这样pnpm dev:wx启动时, 找不到正确的路径的

(背景: 我遇到了pnpm start正常, 但pnpm dev:wx提示找不到module的情况, 最终debug发现是这个插件的配置导致的)

![image](https://github.com/dcloudio/uni-app/assets/7044628/445a75de-eee7-4325-a758-5fc60ca474b2)
