### ISSUE TITLE
所有页面自带转发功能

### ISSUE THREAD

**Issue by brucehelen** [dcloudio/uni-app#411]
**问题描述**
通过HBuilderX新建一个uni-app默认登录工程，每个页面都有转发（分享）功能

**复现步骤**
[复现问题的步骤]
通过HBuilderX新建一个uni-app默认登录工程，编译到微信小程序，每个页面都会自带分享功能，但是页面其实都没有定义 `onShareAppMessage` 这个函数，按照文档的说明，这里不应该弹出分享菜单。

![image](https://user-images.githubusercontent.com/5308436/58362443-97187700-7ec9-11e9-9c96-3ce7b07a7c5b.png)

**预期结果**
希望定义了 `onShareAppMessage` 函数再显示分享菜单

**实际结果**
页面没有定义`onShareAppMessage `却显示分享菜单。

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统：Android 7.0
 - HBuilderX版本 1.9.9.20190522

**Comment by brucehelen** [comment]
@fxy060608 @hbcui1984 这个问题解决了吗？

**Comment by xiaopin** [comment]
持续关注该问题，因为项目并不是全部页面都有分享功能，只有部分页面允许转发分享

**Comment by chen-can** [comment]
cli模式怎么实现小程序所有页面自带转发功能

**Comment by fxy060608** [comment]
> @fxy060608 @hbcui1984 这个问题解决了吗？

使用最新的 Alpha 版本

**Comment by fxy060608** [comment]
> cli模式怎么实现小程序所有页面自带转发功能

使用 mixin

**Comment by chen-can** [comment]
main.js 引入
//全局方法
import common from './utils/common'
Vue.mixin(common) 无效

**Comment by fxy060608** [comment]
> main.js 引入
> //全局方法
> import common from './utils/common'
> Vue.mixin(common) 无效

npm update 之后再试下

**Comment by chen-can** [comment]
还是无效

**Comment by songStar0904** [comment]
> 使用最新的 Alpha 版本
用的最新的hbuilderx  还是有这个问题啊
版本号：2.0.1.20190614

**Comment by songStar0904** [comment]
> > @fxy060608 @hbcui1984 这个问题解决了吗？
> 
> 使用最新的 Alpha 版本
用的最新的hbuilderx 还是有这个问题啊
版本号：2.0.1.20190614

**Comment by zhetengbiji** [comment]
> > @fxy060608 @hbcui1984 这个问题解决了吗？
> 
> 使用最新的 Alpha 版本
> 用的最新的hbuilderx 还是有这个问题啊
> 版本号：2.0.1.20190614

你使用的不是 Alpha 版本，应该为：2.0.2.20190614-alpha

**Comment by songStar0904** [comment]
> > > @fxy060608 @hbcui1984 这个问题解决了吗？
> > 
> > 
> > 使用最新的 Alpha 版本
> > 用的最新的hbuilderx 还是有这个问题啊
> > 版本号：2.0.1.20190614
> 
> 你使用的不是 Alpha 版本，应该为：2.0.2.20190614-alpha

为什么正式版有这个bug。。。

**Comment by zhetengbiji** [comment]
> > > > @fxy060608 @hbcui1984 这个问题解决了吗？
> > > 
> > > 
> > > 使用最新的 Alpha 版本
> > > 用的最新的hbuilderx 还是有这个问题啊
> > > 版本号：2.0.1.20190614
> > 
> > 
> > 你使用的不是 Alpha 版本，应该为：2.0.2.20190614-alpha
> 
> 为什么正式版有这个bug。。。

等 Alpha 版本测试稳定了就会发布正式版

**Comment by zzlit** [comment]
@fxy060608 @zhetengbiji 同问题但是我`npm update` 没有解决，只有把`package.json`的所有包的版本更新到最新才解决（因为用的`ncu`直接更新的最新，其中哪个版本解决的也不了解），但是现在问题有一个就是我用新项目的搭建的里面包大部分都改成了例如这样子使用 `*`号来代替以前的版本号`"@types/uni-app": "*",`，这样子和以前的那种有什么区别呢？还是说以后就不需要手动去更新`package.json` 而直接 `npm i` 就可以了嘛？
