### ISSUE TITLE
3.6.17.20230112版本无法直接使用wx.qy.login

### ISSUE THREAD

**Issue by zhangheng2022** [dcloudio/uni-app#4112]
**问题描述**

3.6.17.20230112版本无法直接使用wx.qy.login，打印wx.qy报undefined。上个版本正常，微信原生小程序正常

**Comment by zhetengbiji** [comment]
在 HBuilderX 目录下执行 ```npx patch-hbuilderx-plugins```

**Comment by zhetengbiji** [comment]
HBuilderX 3.6.18 已修复
