### ISSUE TITLE
ts 项目，如何为 uni 扩展自定义属性或方法呢？

### ISSUE THREAD

**Issue by dodu2014** [dcloudio/uni-app#4114]
**问题描述**
ts 项目，如何为 uni 扩展自定义属性或方法呢？

**复现步骤**
通过查询 uni 的类型为：UniNamespace.Uni

![image](https://user-images.githubusercontent.com/15245544/212441705-fb1f300b-3923-4be1-99af-f122f4cb6e0b.png)

在自己的typings下新建 shims.uni.d.ts 尝试为 uni 的类型扩展一个$u属性：

```js
declare module '@dcloudio/types' {
  namespace UniNamespace {
    export interface Uni {
      $u?: any;
    }
  }
}
```
🔝这样做无效

```javascript
// 为 UniApp.Uni 扩展 $u 属性
declare namespace UniNamespace {
  export interface Uni {
    $u?: any;
  }
}
```
🔝这样做会报：标识符“Uni”重复

```javascript
// 为 UniApp.Uni 扩展 $u 属性
declare namespace UniNamespace {
  export interface UniInterface {
    $u?: any;
  }
}
```
🔝这样在使用的时候 uni.$u 是可以使用了，但原来的方法就报错，应该是覆盖了 @dcloudio/types 中的定义

😂 应该怎么扩展呢？？？

**预期结果**

**实际结果**

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**Comment by dodu2014** [comment]
发现 "@dcloudio/types": "^2.6.12" 可以这样扩展，如下：

``` js
declare namespace UniApp {
  interface Uni {
    $u: any
  }
}
```

"@dcloudio/types": "^3.2.7" 不行，或者按上面方法都不行

**Comment by zhetengbiji** [comment]
未使用模块时，直接 interface Uni 即可，declare 可以添加或者省略

如果你使用了模块，需要 declare global {   interface Uni {

可以参考一下 @dcloudio/types 中的代码：uni-app/uni/base、uni-app/uni/ext

**Comment by dodu2014** [comment]
thanks @zhetengbiji

**Comment by lxy94** [comment]
在根目录中建了文件shims.uni.d.ts
declare global {
    interface Uni{
        requirePrivacyAuthorize(options: UniNamespace.StartRecordOptions):void
    }
}
咋不太行
