### ISSUE TITLE
uniapp打包成h5,非uniapp的App内嵌入，使用postMessage，在uniapp的h5中window.addEventListener监听message，没有收到事件

### ISSUE THREAD

**Issue by 15873944157** [dcloudio/uni-app#4116]
**问题描述**
uniapp打包成h5,非uniapp的App内嵌入，使用postMessage，在uniapp的h5中window.addEventListener监听message，没有收到事件

**复现步骤**
[复现问题的步骤]
1.  App发送 obj.postMessage(“这是消息”, "*");
2. H5监听
window.addEventListener("message", (e) => {
  // 没有对应的事件触发
}, false);

**预期结果**
收到App发送的事件

**实际结果**
h5没有事件触发

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 Android 6.0
 - HBuilderX版本 HBuilderX 3.6.5.20221121

**Comment by 15873944157** [comment]
App是react-native项目

**Comment by zhetengbiji** [comment]
应使用dispatchEvent
具体可参考：https://www.baidu.com/s?wd=js+%E8%A7%A6%E5%8F%91%E4%BA%8B%E4%BB%B6&tn=84053098_3_dg&ie=utf-8

**Comment by 15873944157** [comment]
> 应使用dispatchEvent 具体可参考：https://www.baidu.com/s?wd=js+%E8%A7%A6%E5%8F%91%E4%BA%8B%E4%BB%B6&tn=84053098_3_dg&ie=utf-8

不是，我其他应用(vue3项目)都正常，而且app里面webview只开放了接口 postMessage，跟事件派发没关系把，ios能正常收到，安卓不行

**Comment by zhetengbiji** [comment]
> > 应使用dispatchEvent 具体可参考：https://www.baidu.com/s?wd=js+%E8%A7%A6%E5%8F%91%E4%BA%8B%E4%BB%B6&tn=84053098_3_dg&ie=utf-8
> 
> 不是，我其他应用(vue3项目)都正常，而且app里面webview只开放了接口 postMessage，跟事件派发没关系把，ios能正常收到，安卓不行

抱歉，不是很了解react-native，以为是和5+类似的webview。

理论上uni-app框架主要处理UI，不会影响window.addEventListener
