### ISSUE TITLE
Can`t find variable: globalThis

### ISSUE THREAD

**Issue by le0l1** [dcloudio/uni-app#4117]
**问题描述**

微信小程序后台报错记录显示报错

![image](https://user-images.githubusercontent.com/20632096/212627826-81cea517-8e0f-4c6a-bef9-da22e48dbeed.png)

生产编译后找到该处函数
![image](https://user-images.githubusercontent.com/20632096/212628001-d7fa80b9-3c3c-4e3c-8555-7d180ae4dabc.png)

**预期结果**
不发生报错

**实际结果**
偶尔会出现`Can't find variable: globalThis`的报错

**补充信息**
从代码上看，应该是uni-app在生成wx代理变量时，未对globalThis做校验导致，也有可能是微信小程序的bug，但需要uni-app做下这块的兼容
https://github.com/dcloudio/uni-app/blob/5a4759618632f777304d17f039793c4bf691cb09/packages/uni-mp-weixin/dist/wx.js#L1-L31

**Comment by fxy060608** [comment]
是否有该错误的设备，微信版本，基础库版本等信息？

**Comment by le0l1** [comment]
> 错

<img width="710" alt="image" src="https://user-images.githubusercontent.com/20632096/212631549-4436e82e-adc4-449a-8365-146814323f14.png">

**Comment by le0l1** [comment]
> 是否有该错误的设备，微信版本，基础库版本等信息？

<img width="710" alt="image" src="https://user-images.githubusercontent.com/20632096/212631600-fe8572f6-b928-44de-801a-a93a1dd80570.png">

**Comment by zhetengbiji** [comment]
HBuilderX 创建的项目，在 HBuilderX 目录下执行 npx patch-hbuilderx-plugins
CLI 创建的项目，在项目下执行 npx @dcloudio/uvm

然后重启 HBuilderX，重新发布

**Comment by yinyanlv** [comment]
@zhetengbiji 请问升级HBuilderX到哪个版本（或者回退至哪个版本）可以解决这个问题？手动执行你发的命令发生报错了

![311674970857_ pic](https://user-images.githubusercontent.com/10555534/215307832-333649dd-7710-4483-9fdc-4720307dd4f0.jpg)

**Comment by zhetengbiji** [comment]
> 

HBuilderX 3.6.18 已修复
