### ISSUE TITLE
分包静态资源加载不了

### ISSUE THREAD

**Issue by liuyehui** [dcloudio/uni-app#412]
**问题描述**
分包目录下的静态资源无法加载

**复现步骤**
1.  添加分包
"subPackages": [
    {
      "root": "packageA",
      "pages": [...]
    }]
2. 分包 packageA 下面添加静态资源 img 目录并在页面中引入
3. 运行时发现这些静态资源加载不到，提示404错误

**预期结果**
分包目录下的静态资源可以用相对路径或绝对路径加载

**实际结果**
分包目录下的静态资源加载不了，提示404错误

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本 1.9.9.20190522

**补充信息**
估计是分包目录下的静态资源没有编译

**Comment by wuhuaxiangjob** [comment]
官方都么有回答的吗，兄弟，你们有啥措施改变这个吗

**Comment by zhetengbiji** [comment]
已修复
