### ISSUE TITLE
@dcloudio/uni-vue-devtools  bug

### ISSUE THREAD

**Issue by mz-dfhp** [dcloudio/uni-app#4120]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

@dcloudio/uni-vue-devtools 版本

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/63582593/213345629-773f4ce9-3700-4d21-9d7e-1e3d142eb754.png)

![image](https://user-images.githubusercontent.com/63582593/213345674-c852af39-5465-4376-941e-ef2d9153e856.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhenyuWang** [comment]
[cli 3.0.0-alpha-3070020230117001+ 支持](https://uniapp.dcloud.net.cn/tutorial/debug/uni-vue-devtools.html)

**Comment by Nick742037091** [comment]
默认安装是3.0.0-alpha-3060920221117001 版本，有兼容问题，升级到3.0.0-Alpha-3070020230117001版本以上
