### ISSUE TITLE
hbuilderx建的uniapp工程 ,   使用vite3 + tailwindcss构建应用 ， 根目录下postcss.config.js 未加载 ， 寻求解惑

### ISSUE THREAD

**Issue by marol1210** [dcloudio/uni-app#4126]
**问题描述**

项目中使用tailwindcss UI ， 未如愿。

方法： vite预支持postcss-load-config , 
            1.  npm i -D tailwindcss   autoprefixer
            2.  配置postcss.config.[c]js (两种格式文件都尝试过) 
            3. tailwind.config.[c]js

**复现步骤**

1.  启动运行到游览器 ， 构建结果代码中，未能识别tailwindcss样式。

主要配置文件
vite.config.js
```
import { defineConfig } from 'vite';
import uni from '@dcloudio/vite-plugin-uni';

export default defineConfig({
  plugins: [
    uni({
      vueOptions: {
        reactivityTransform: true
      }
    })
  ],
  //尝试过以下配置 ，未能如愿
  css: {
     postcss: __dirname
  }
});
```

postcss.config.[c]js
```
console.log('有没有读取')
module.exports = {
  plugins:[
	  require("tailwindcss"),
	  require("autoprefixer"),
  ]
}
```

![image](https://user-images.githubusercontent.com/7519301/215930261-c2d338aa-1f70-4528-af10-3091c77230f6.png)

**预期结果**
读取项目根目录下的postcss.config.[c]js文件，对代码中css内容进行处理 ， 最终包含tailwindcss样式内容。

**实际结果**
未读取postcss.config.[c]js ,  导致未对css内容做处理

**系统信息:**
 - 微信小程序、H5平台
 - 操作系统 window11
 - HBuilderX版本  3.6.18.20230117
 - uni-app版本

**Comment by gyhyfj** [comment]
为什么关闭了呢？遇到了同样的问题

**Comment by cx690** [comment]
24年了，这么久了，这个问题竟然还存在，我使用以下方法处理了问题
```js
// vite.config.ts
export default defineConfig({
	css: {
		postcss: {
			plugins:['xxxplugin']
                }
            }
})
```
