### ISSUE TITLE
线上构建h5报错，Error: PostCSS plugin postcss-discard-comments requires PostCSS 8.

### ISSUE THREAD

**Issue by pcdd-group** [dcloudio/uni-app#4127]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

本地build:h5正常，线上build报错
Error: PostCSS plugin postcss-discard-comments requires PostCSS 8.
本地和线上环境一致，nodejs: v18.12.1
尝试 https://github.com/dcloudio/uni-app/issues/3862 仍失败

**复现步骤**
[复现问题的步骤]
线上执行
npm install
npm run build

**预期结果**
构建成功，生成dist目录

**实际结果**
构建失败，报错：Error: PostCSS plugin postcss-pxtorem requires PostCSS 8
![image](https://user-images.githubusercontent.com/51998152/216330318-c92efba2-f279-4bc8-84fc-2e1518bfc63a.png)

**系统信息:**
 - 发行平台: H5平台
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]

uni-app v3.6.18
uni-app cli v2.0.2-3061820230117002
Environment Info:
  System:
    OS: Windows 10
    CPU: (8) x64 AMD Ryzen 7 3750H with Radeon Vega Mobile Gfx  
  Binaries:
    Node: 18.12.1 - D:\Applications\Scoop\apps\nodejs-lts\current\node.EXE
    Yarn: Not Found
    npm: 9.2.0 - D:\Applications\Scoop\apps\nodejs-lts\current\bin\npm.CMD
  Browsers:
    Edge: 44.22621.1105.0
  npmPackages:
    @dcloudio/types: ^3.0.4 => 3.2.11
    @dcloudio/uni-app: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-app-plus: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-automator: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-cli-i18n: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-cli-shared: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-h5: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-helper-json: * => 1.0.13
    @dcloudio/uni-i18n: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-migration: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-mp-360: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-mp-alipay: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-mp-baidu: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-mp-jd: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-mp-kuaishou: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-mp-lark: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-mp-qq: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-mp-toutiao: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-mp-vue: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-mp-weixin: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-mp-xhs: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-quickapp-native: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-quickapp-webview: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-stacktracey: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-stat: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/uni-template-compiler: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/vue-cli-plugin-uni: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/webpack-uni-mp-loader: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @dcloudio/webpack-uni-pages-loader: ^2.0.2-3061820230117002 => 2.0.2-3061820230117002
    @hap-toolkit/dsl-vue:  0.6.13
    @vue/babel-helper-vue-jsx-merge-props:  1.4.0
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.1.1
    @vue/babel-plugin-transform-vue-jsx:  1.4.0
    @vue/babel-preset-app:  5.0.8
    @vue/babel-preset-jsx:  1.4.0
    @vue/babel-sugar-composition-api-inject-h:  1.4.0
    @vue/babel-sugar-composition-api-render-instance:  1.4.0
    @vue/babel-sugar-functional-vue:  1.4.0
    @vue/babel-sugar-inject-h:  1.4.0
    @vue/babel-sugar-v-model:  1.4.0
    @vue/babel-sugar-v-on:  1.4.0
    @vue/cli-overlay:  5.0.8
    @vue/cli-plugin-babel: ~5.0.0 => 5.0.8
    @vue/cli-plugin-router:  5.0.8
    @vue/cli-plugin-vuex:  5.0.8
    @vue/cli-service: ~5.0.0 => 5.0.8
    @vue/cli-shared-utils:  5.0.8
    @vue/component-compiler-utils:  3.3.0
    @vue/shared: ^3.0.0 => 3.2.47
    @vue/web-component-wrapper:  1.3.0
    eslint-plugin-vue: ^9.9.0 => 9.9.0
    vue: >= 2.6.14 < 2.7 => 2.6.14
    vue-eslint-parser:  9.1.0
    vue-hot-reload-api:  2.3.4
    vue-loader:  17.0.1 (17.0.1)
    vue-style-loader:  4.1.3
    vue-template-compiler: >= 2.6.14 < 2.7 => 2.6.14
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.2.0 => 3.6.2
  npmGlobalPackages:
    @vue/cli: Not Found

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
This is probably not a problem with npm. There is likely additional logging output above.

**Comment by StrivingRabbit** [comment]
使用 
```js
vue create -p dcloudio/uni-preset-vue my-project
```
创建的模板吗？

**Comment by pcdd-group** [comment]
是的，vue2版本

**Comment by pcdd-group** [comment]
使用yarn构建成功了，不过npm构建依然失败。感谢你的建议。

线上环境如下
Node.js: v18.12.1
yarn: v1.22.4
线上构建脚本如下
npm i yarn@1.22.4 -g
yarn --version
yarn config set ignore-engines true
yarn install
yarn build
