### ISSUE TITLE
百度小程序slot嵌套编译有问题

### ISSUE THREAD

**Issue by Tibbersss** [dcloudio/uni-app#413]
**问题描述**
凡是2个组件嵌套，并且2个组件都带slot插槽的，在百度小程序编译时卡在“编译中”，且cpu占用100%。
![image](https://user-images.githubusercontent.com/10751521/58363286-24f95f80-7ed4-11e9-856b-d4f155042051.png)
![image](https://user-images.githubusercontent.com/10751521/58363302-5a05b200-7ed4-11e9-901f-4fdfe8cb2819.png)

**系统信息:**
 - 发行平台: 百度小程序
 - HBuilderX版本 1.9.9

**Comment by fxy060608** [comment]
编译模式是什么？建议更换为自定义组件模式：https://ask.dcloud.net.cn/article/35843

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
