### ISSUE TITLE
uniapp+vue3 + h5 路由跳转报api.now is not a function

### ISSUE THREAD

**Issue by mayafanga** [dcloudio/uni-app#4145]
<img width="402" alt="1" src="https://user-images.githubusercontent.com/34863005/218021517-b275604f-9b0e-40ef-afe4-bae8d952d749.png">
<img width="272" alt="2" src="https://user-images.githubusercontent.com/34863005/218021523-c1f6ee2a-1558-4637-b594-9888ab64bfce.png">

**Comment by zhenyuWang** [comment]
提供下可复现demo

**Comment by zhenyuWang** [comment]
如何复现，测试跳转详情页正常
![image](https://user-images.githubusercontent.com/37523000/218362045-66677082-c142-4e61-ab94-f589bfd7bacf.png)

**Comment by mayafanga** [comment]
我这里也好了，倒是什么也没改

**Comment by zhenyuWang** [comment]
如无问题，可关闭该 issue;
若后续复现该问题并确认框架问题，可 reopen 该 issue 并提供复现  demo。
