### ISSUE TITLE
uni.getSystemInfoSync()获取safeAreaInsets不准确

### ISSUE THREAD

**Issue by aalexlin** [dcloudio/uni-app#4152]
**问题描述**
开发app，在iphone 13pro调用uni.getSystemInfoSync()获取safeAreaInsets，bottom为0
![image](https://user-images.githubusercontent.com/6197922/218649890-e26b7cbc-29d2-4c38-9a9a-362c6578e434.png)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统: IOS16.3
 - HBuilderX版本: 3.6.18
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息: iphone13 pro

**Comment by zhetengbiji** [comment]
其他机型是否正常？
manifest.json 内是否配置了 safearea 原生占位？
