### ISSUE TITLE
cloneWithData导致循环引用报错

### ISSUE THREAD

**Issue by MyPrototypeWhat** [dcloudio/uni-app#4159]
**问题描述**
data里写一个环状链表，就报错了，看了下是这个地方报的错，搜了下issues，发现最早20年就提过...
<img width="807" alt="企业微信截图_1ce721df-ae1f-4a78-a2aa-bfe373fd2877" src="https://user-images.githubusercontent.com/43230886/219567252-bc03e590-dcf7-4f80-8b2f-c1cb5bf3987c.png">
<img width="498" alt="企业微信截图_9f67f9b2-0ca4-4ea3-90e6-fefc26e11074" src="https://user-images.githubusercontent.com/43230886/219564843-0568da06-a300-496c-a870-e9a0484ea2db.png">
**预期结果**

**实际结果**
正常使用循环引用

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 macos
 - uni-app版本 v3.2.16

**补充信息**
不考虑下换一种深拷贝方式吗

**Comment by StrivingRabbit** [comment]
传一个可复现的 demo 我测试一下看看

**Comment by StrivingRabbit** [comment]
#2980

**Comment by MyPrototypeWhat** [comment]
> 传一个可复现的 demo 我测试一下看看
```js
<template>
  <div>
    demo
  </div>
</template>

<script>
export default {
  data() {
    return {
      queue: {
        pending: null
      }
    };
  },
  mounted() {
    const update = {};
    if (this.queue.pending === null) {
      update.next = update;
    } else {
      update.next = this.queue.pending.next;
      this.queue.pending.next = update;
    }
    this.queue.pending = update;
  }
};
</script>

<style lang="scss" scoped></style>
```

**Comment by MyPrototypeWhat** [comment]
能解决不...我看其他issue的回答是 有些平台只能支持string通信，可否根据平台细分优化
或者 我的例子是一个环链表，可否头尾剪开之后 string转化之后 再恢复环状。

感觉data中存循环引用的这种case比较少吧

**Comment by zhetengbiji** [comment]
> 能解决不...我看其他issue的回答是 有些平台只能支持string通信，可否根据平台细分优化 或者 我的例子是一个环链表，可否头尾剪开之后 string转化之后 再恢复环状。
> 
> 感觉data中存循环引用的这种case比较少吧

可以的，莫慌，等待 @StrivingRabbit  继续跟进

**Comment by MyPrototypeWhat** [comment]
> > 能解决不...我看其他issue的回答是 有些平台只能支持string通信，可否根据平台细分优化 或者 我的例子是一个环链表，可否头尾剪开之后 string转化之后 再恢复环状。
> > 感觉data中存循环引用的这种case比较少吧
> 
> 可以的，莫慌，等待 @StrivingRabbit 继续跟进

1

**Comment by StrivingRabbit** [comment]
经测试，微信小程序本身也不支持 setData 循环引用的数据。所以此问题关闭，可以去微信的开发者社区反馈一下 setData 循环引用数据报错的问题

![Snipaste_2023-04-26_18-02-02](https://user-images.githubusercontent.com/33573212/234542303-362662fb-7cbe-4341-93c7-70caee7317fc.jpg)
