### ISSUE TITLE
使用cli生产的项目，h5 可以使用vue.config文件配置？

### ISSUE THREAD

**Issue by SilasDong** [dcloudio/uni-app#417]
使用cli生产的项目，h5 可以使用vue.config文件配置？

**Comment by hbcui1984** [comment]
下个版本放开vue.config配置

**Comment by fxy060608** [comment]
可以使用，但 vue.config.js 部分配置不会生效或可能导致意外情况发生，建议仅使用一些 webpack 插件，loader 之类的处理编译需求
