### ISSUE TITLE
微信小程序表单重置resetFileds失效

### ISSUE THREAD

**Issue by Master-Zhang-Web** [dcloudio/uni-app#4170]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
form组件表单重置resetFileds()方法，APP和H5表现正常，微信小程序端失效

**系统信息:**
 - HBuilderX版本 3.6.18
 - uView 版本 2.0.29

**Comment by zhenyuWang** [comment]
uni-forms 组件吗？

**Comment by Master-Zhang-Web** [comment]
uView-UI的form组件

**Comment by zhenyuWang** [comment]
> uView-UI的form组件

请在 uView 仓库反馈该问题
