### ISSUE TITLE
vue3中到底能不能用jsx？

### ISSUE THREAD

**Issue by zhangweia** [dcloudio/uni-app#4172]
在vue3中到底怎么使用jsx啊，官方的列子能不能详细点出个，一直用不起来

**Comment by zhenyuWang** [comment]
按 [文档](https://uniapp.dcloud.net.cn/tutorial/syntax-jsx.html#jsx-tsx-%E6%94%AF%E6%8C%81) 配置好就可以写 jsx 了，遇到什么问题呢？

**Comment by bugfix2020** [comment]
小程序好像不支持

**Comment by zhenyuWang** [comment]
> 小程序好像不支持

文档中有说明兼容性问题

**Comment by Otto-J** [comment]
#4683

**Comment by alamhubb** [comment]
开了个坑，让uniapp的小程序端支持渲染函数了，

https://github.com/alamhubb/uni-render

实现原理

https://github.com/alamhubb/uni-render/blob/main/TechnicalImplementation.md


相关文章

https://zhuanlan.zhihu.com/p/1994149291560813794


vue的jsx是基于渲染函数的，所以准备顺便支持下jsx
