### ISSUE TITLE
vue3+vite+ts开发钉钉小程序，真机预览时报错w.getCurrentPages is not a function

### ISSUE THREAD

**Issue by adorableseulgi** [dcloudio/uni-app#4174]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
1.  git clone https://github.com/adorableseulgi/uni-dd-demo.git
2. 下载依赖并使用hbx运行钉钉小程序
3. 下载[小程序开发工具](https://openplatform-portal.dg-work.cn/portal/#/helpdoc?apiType=DEV_GUIDE&docKey=3355060)
4. 使用小程序开发工具打开dist/dev/mp-alipay目录，管理端选择mPaaS
5. 在开发者后台创建小程序、设置白名单后，点击右上角真机调试

[或者可以直接贴源代码]

**预期结果**
与模拟器表现一致，可调试真机

**实际结果**
页面一直loading，一段时间后控制台报错：
```
[WORKER] onerror (5) ["Uncaught TypeError: w.getCurrentPages is not a function", "http://127.0.0.1:55379/worker/preload.js", 1, 4170, TypeError: w.getCurrentPages is not a function
    at Object.Tiny.Data.getPagesData (http://127.0.0…]
Zs.onerror @ af-appx.worker.min.js:24
(anonymous) @ /Applications/小程序开发者工具.app/Contents/Resources/app/modules.asar/@alipay/volans-source/out/webview/plain-preload.js:55
emit @ node:events:390
onMessage @ node:electron/js2c/renderer_init:69
preload.js:1

Uncaught TypeError: w.getCurrentPages is not a function
    at Object.Tiny.Data.getPagesData (preload.js:1)
    at preload.js:1
    at EventEmitter.<anonymous> (/Applications/小程序开发者工具.app/Contents/Resources/app/modules.asar/@alipay/volans-source/out/webview/plain-preload.js:55)
    at EventEmitter.emit (node:events:390)
    at Object.onMessage (node:electron/js2c/renderer_init:69)
```

**系统信息:**
 - 发行平台：(专有)钉钉小程序
 - 操作系统：macOS Ventura 13.1
 - HBuilderX版本：3.7.2.20230217-alpha
 - uni-app版本：3.0.0-alpha-3061620221230002
 - 设备信息：小米手机8、iphoneX

**补充信息**
附上报错截图
![291677217618_ pic](https://user-images.githubusercontent.com/15797337/221101978-a0e867d9-6294-4c43-a9be-66483aa1db15.jpg)

![WX20230224-134627@2x](https://user-images.githubusercontent.com/15797337/221101912-7429df7e-91cb-4ed9-9915-a4492c077ba5.png)

**Comment by littlerhub** [comment]
关闭小程序配置中的启用小程序基础库2.0构建
