### ISSUE TITLE
vue3 多个混合分包一起使用导致 wx.$subpackages 报错

### ISSUE THREAD

**Issue by lcybb** [dcloudio/uni-app#4175]
**问题描述**
微信小程序当两个混合分包同时存在，在分包运行顺序不同会导致 wx.$subpackages 会被后加载的分包覆盖，这可能会导致报错

**复现步骤**
[复现问题的步骤]
1.  启动 小程序
2. 点击  Sub1 > Back > Sub2
3. 查看 wx.$subpackages 会被 Sub2 覆盖

[或者可以直接贴源代码]
https://github.com/lcybb/uni-app-subpackage

**预期结果**
不会造成错误

**实际结果**
这会造成微信小程序在部分真机上报错分包无法进入

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
https://github.com/dcloudio/uni-app/blob/0eca276b7a74140d6f97869abf195093b430be68/packages/uni-mp-weixin/dist/wx.js#L32

**Comment by lcybb** [comment]
@fxy060608 大佬有空看下这个 initWx ？

**Comment by zhenyuWang** [comment]
测试你提供的测试工程复现问题，正常分包项目正常 [HBuilderX vue3](https://github.com/zhenyuWang/uniapp-test-project/tree/main/issues/4175-subpackages) [cli vue3](https://github.com/zhenyuWang/uniapp-test-project/tree/main/issues/4175-cli-vue3)
使用该方式分包的需求是什么？推荐使用官方支持分包方式

**Comment by lcybb** [comment]
> 测试你提供的测试工程复现问题，正常分包项目正常 [HBuilderX vue3](https://github.com/zhenyuWang/uniapp-test-project/tree/main/issues/4175-subpackages) [cli vue3](https://github.com/zhenyuWang/uniapp-test-project/tree/main/issues/4175-cli-vue3) 使用该方式分包的需求是什么？推荐使用官方支持分包方式

在分包上不会100%复现出来。在打包小程序插件使用api会复现到，会被 initWx 覆盖 api 的影响。

从小程序使用 wx.navigateTo 跳转到 插件页面 时出现 errMsg: "navigateTo:fail rejected due to no permission currently in plugin"

[cli vue3 plugin-demo](https://github.com/lcybb/uniapp-test/tree/4175-plugin-demo)

**Comment by zhenyuWang** [comment]
测试 navigator 组件可以跳转，api方式不行，应该是 微信小程序的问题，[相关帖子](https://developers.weixin.qq.com/community/develop/doc/000802949480180e67c81f9ff5b400)

**Comment by zhenyuWang** [comment]
问题确认，感谢反馈，这边排查下

**Comment by zhenyuWang** [comment]
HBuilderX 3.7.12 (cli 2.0.2-alpha-3071220230331001) 已修复

**Comment by lcybb** [comment]
> HBuilderX 3.7.12 (cli 2.0.2-alpha-3071220230331001) 已修复

@zhenyuWang 修复后又有个新问题，插件内使用 uni. navigateTo 跳转到插件内的页面也出现错误 Error: MiniProgramError
{"errMsg":"navigateTo:fail rejected due to no permission currently"}，原生是正常的。

[demo](https://github.com/lcybb/uniapp-test/tree/4175-plugin-demo)

**Comment by zhenyuWang** [comment]
@lcybb 参考[以上commit](https://github.com/dcloudio/uni-app/commit/ee8d7f8621ab6d625114a69ccc6785846fc73b5e)更新 @dcloudio/uni-mp-weixin/dist/uni.api.esm.js 试下能否解决问题

**Comment by fulisadawang** [comment]
解决了吗？
