### ISSUE TITLE
vue-cli搭建的新项目支付宝小程序运行失败

### ISSUE THREAD

**Issue by zzlit** [dcloudio/uni-app#418]
模板选择的是默认模板。
vue --version
3.8.2
[](url)
![WX20190528-172654](https://user-images.githubusercontent.com/28583195/58476452-5fd4ef00-8183-11e9-81de-84d4d36a0b43.png)
![WX20190528-172518](https://user-images.githubusercontent.com/28583195/58476467-67949380-8183-11e9-974e-144bd05574d2.png)
![WX20190528-172400](https://user-images.githubusercontent.com/28583195/58476475-6b281a80-8183-11e9-8039-03a031604bd9.png)

**Comment by fxy060608** [comment]
cli 已修复，npm update

**Comment by zzlit** [comment]
> cli 已修复，可执行 npm update

更新完之后都跑不起来了，报错如下，我也安装了所需要的两个包但还是不行，是我操作哪里不对吗？新建了一个项目还是一样的报错。
![WX20190529-094641](https://user-images.githubusercontent.com/28583195/58523409-f098e280-81f6-11e9-9f63-86af3631ca54.png)
![WX20190529-094657](https://user-images.githubusercontent.com/28583195/58523415-f4c50000-81f6-11e9-9bc3-e44d5eb29c72.png)
![WX20190529-094741](https://user-images.githubusercontent.com/28583195/58523419-f68ec380-81f6-11e9-86df-b0fb97480635.png)

**Comment by zzlit** [comment]
> cli 已修复，可执行 npm update

你好，发现了一个问题，package.json里面这个包的版本如下的时候
 `"regenerator-runtime": "^0.13.2"` 运行支付宝小程序会报错

![WX20190529-104125](https://user-images.githubusercontent.com/28583195/58525830-b4b64b00-81ff-11e9-960b-fa52cc3a0c83.png)

改为 `"regenerator-runtime": "^0.12.1"` 这个版本就不会了，具体是其中哪个版本出了问题我也不太清楚，因为我新建新项目的版本是0.12.1，然后当前项目是0.13.2。

**Comment by fxy060608** [comment]
锁定使用0.12.1版本，旧版本创建的工程没有锁定，导致在小程序平台可能有问题，

**Comment by zzlit** [comment]
> 锁定使用0.12.1版本，旧版本创建的工程没有锁定，导致在小程序平台可能有问题，
> 建议在 mp-alipay 下 usingComponents:true ,切换到自定义组件模式

自定义组建模式依然有如的上图警告，麻烦您再看一下
