### ISSUE TITLE
快手小程序 setStorageSync 提示 could not be cloned.

### ISSUE THREAD

**Issue by pipione** [dcloudio/uni-app#4182]
**问题描述**
快手小程序 setStorageSync 提示 could not be cloned.

存储的是 ref.value 的值。

**复现步骤**
快手体验版
setStorageSync 存储一个ref().value 值

**实际结果**

![image](https://user-images.githubusercontent.com/46072182/221745219-31679012-2eb0-4f0b-aeb2-de5e929838dd.png)

**系统信息:**
 - 发行平台: 快手小程序
 - 操作系统 安卓
 - HBuilderX版本 3.7.3.20230223

**补充信息**
存储普通对象可以， 但是存储 ref().value 的值就不行（Proxy）

**Comment by pipione** [comment]
@fxy060608

**Comment by zhenyuWang** [comment]
测试未复现该问题，请检查代码编写，如确认框架问题，提供测试工程，谢谢

**Comment by pipione** [comment]
[test-kuaishou.zip](https://github.com/dcloudio/uni-app/files/10846512/test-kuaishou.zip)
![wecom-temp-c0d2aae57813263f011c8902d14e9c4f](https://user-images.githubusercontent.com/46072182/221752233-492d07f1-f7dc-407d-a822-26297ac9d105.jpg)
@zhenyuWang

**Comment by pipione** [comment]
[test-kuaishou.zip](https://github.com/dcloudio/uni-app/files/10846554/test-kuaishou.zip)
![wecom-temp-c0d2aae57813263f011c8902d14e9c4f](https://user-images.githubusercontent.com/46072182/221753141-aee5eda4-164c-4247-9475-28ed543f5fe5.jpg)

这段代码用抖音小程序运行就没问题

**Comment by pipione** [comment]
@zhenyuWang

**Comment by zhenyuWang** [comment]
HBuilderX 3.7.3 快手开发者工具 1.23.1 测试正常
![image](https://user-images.githubusercontent.com/37523000/221774901-8812bb5e-9dca-42f0-bc9e-c682a9f0e7da.png)

**Comment by pipione** [comment]
是的，开发平台正常。 但是真机就不正常了。 （不使用远程调试， 推送到体验版）

**Comment by zhenyuWang** [comment]
> 是的，开发平台正常。 但是真机就不正常了。 （不使用远程调试， 推送到体验版）

也就是说只有上传体验版才有问题是吗？测试快手小程序原生开发是否存在该问题
另： 后续反馈问题建议提供精确复现条件，减小沟通成本

**Comment by pipione** [comment]
在快手中
远程调试 和 开发工具 不会复现
扫码预览 和 体验版 稳定复现

跟uni-app 框架本身没什么问题， 快手的setStorageSync 无法正常处理Proxy对象， 虽然它是可以通过JSON 序列化的。
