### ISSUE TITLE
<script setup>中 onPageScroll 不触发

### ISSUE THREAD

**Issue by 1eeing** [dcloudio/uni-app#4186]
**问题描述**
`<script setup>`中 onPageScroll 不触发

**复现步骤**
```
<script lang="ts">
export default {
  onPageScroll(data) {
    console.log('fucking scroll ~~~~~~~~~~~')
    if (data.scrollTop <= 50) {
      uni.$emit(events.ON_LOAD_MORE)
    }
  }
};
</script>
```

**预期结果**
正常触发

**实际结果**
未触发

**系统信息:**
 - 发行平台:  App
 - 操作系统: iOS 16.1.1
 - HBuilderX版本: 3.7.3.20230223
 - uni-app版本: 3.0.0-alpha-3061620221230002
 - 设备信息: iPhone 13 pro

**补充信息**
使用场景是页面有长列表需要滚动，给列表容器设置了 overflow: auto 以后 onPageScroll 就不生效；不设置可以，但是无法用手去滚动页面。

**Comment by 1eeing** [comment]
其实我想要的使用场景很简单，我希望页面可以滚动，可以通过 `uni.pageScrollTo 去操作滚动条`，也可以正常监听 `onPageScroll `，在 H5 上没问题，在 App 上就是实现不了

**Comment by yurj26** [comment]
[https://ask.dcloud.net.cn/question/164224](https://ask.dcloud.net.cn/question/164224)

**Comment by 1eeing** [comment]
> https://ask.dcloud.net.cn/question/164224



> > 
> 
> 不行啊，反复试了各种方法了，我代码很简单
> 
> ```
> <template>
>   <div style="height: 100%;overflow-y: auto;">
>     <Message v-if="state === 'connected'" />
>     <div v-else>当前连接已断开</div>
>   </div>
> </template>
> ```
> 
> 存在这个 style，可以手动滚动，但是 onPageScroll 和 uni.pageScrollTo 失效；不加这个 style，这两个 API 可以使用，但是无法手动滚动。这是什么奇怪又诡异的逻辑？试了一大圈方法都不行！！！

@yurj26

**Comment by 1eeing** [comment]
```
<template>
  <view class="box">
    123
  </view>
</template>
<script>
import { onPageScroll } from '@dcloudio/uni-app'
export default {
  setup() {
    onPageScroll((data) => {
      console.log(data)
    })
  }
}
</script>

<style>  .box {
    display: flex;
    justify-content: center;
    align-items: center;
    font-size: 30px;
    height: 200vh;
  }
</style>
```

最小复现代码，环境如题描述，APP 无法滚动！

**Comment by zhetengbiji** [comment]
> > https://ask.dcloud.net.cn/question/164224
> 
> > > 
> > 
> > 
> > 不行啊，反复试了各种方法了，我代码很简单
> > ```
> > <template>
> >   <div style="height: 100%;overflow-y: auto;">
> >     <Message v-if="state === 'connected'" />
> >     <div v-else>当前连接已断开</div>
> >   </div>
> > </template>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 存在这个 style，可以手动滚动，但是 onPageScroll 和 uni.pageScrollTo 失效；不加这个 style，这两个 API 可以使用，但是无法手动滚动。这是什么奇怪又诡异的逻辑？试了一大圈方法都不行！！！
> 
> @yurj26

加上这个 style，是区域滚动而非页面滚动，所以页面滚动相关的不会生效。

**Comment by zhetengbiji** [comment]
> ```
> <template>
>   <view class="box">
>     123
>   </view>
> </template>
> <script>
> import { onPageScroll } from '@dcloudio/uni-app'
> export default {
>   setup() {
>     onPageScroll((data) => {
>       console.log(data)
>     })
>   }
> }
> </script>
> 
> <style>  .box {
>     display: flex;
>     justify-content: center;
>     align-items: center;
>     font-size: 30px;
>     height: 200vh;
>   }
> </style>
> ```
> 
> 最小复现代码，环境如题描述，APP 无法滚动！

“无法滚动”和“script setup以及onPageScroll”无关，你可以删除script节点测试一下。
另外你没说明 Vue2 还是Vue3，以及iOS还是安装，vue还是nvue

**Comment by 1eeing** [comment]
> <template>
>   <view class="box">
>     123
>   </view>
> </template>
> <script>
> import { onPageScroll } from '@dcloudio/uni-app'
> export default {
>   setup() {
>     onPageScroll((data) => {
>       console.log(data)
>     })
>   }
> }
> </script>
> 
> <style>  .box {
>     display: flex;
>     justify-content: center;
>     align-items: center;
>     font-size: 30px;
>     height: 200vh;
>   }
> </style>

Vue 3，vue 不是 nvue。
最小复现代码我贴上面了。
升级 uniapp 版本到 3.0.0-3070320230222002 后可以了。

**Comment by akFace** [comment]
很奇怪，子组件中单独引入使用不生效，需要在主页面中引入才行
```ts
import { onPageScroll } from "@dcloudio/uni-app";
```
