### ISSUE TITLE
Error，uni-app cli项目内使用uniCloud需要使用HBuilderX的运行菜单运行项目，且需要在uniCloud目录关联服务空间

### ISSUE THREAD

**Issue by Createitv** [dcloudio/uni-app#4190]
**问题描述**
通过Cli创建的项目， 访问不到云函数，按照错误提示绑定了服务空间也在HBuilder中运行还是找不到。云函数对象检查也上传到了服务空间. 但是H5中可以访问到！是不是小程序中还需要什么配置

```vue
<template>
	<view class="content">
		<button @click="testco()">请求云对象的方法</button>
	</view>
</template>


<script>
	export default {
		data() {
			return {
			}
		},
		methods: {
			async testco() { // 注意异步
				const helloco = uniCloud.importObject('func') // 导入云对象
        console.log("asada",helloco)
				try {
					const res = await helloco.sum(1,2) //导入云对象后就可以直接调用该对象的sum方法了，注意使用异步await
					console.log(res) // 结果是3
				} catch (e) {
					console.log(e)
				}
			}
		}
	}
</script>
```
![image](https://user-images.githubusercontent.com/39019652/223013421-657cccdc-d133-4d68-8abe-ac7e19c5aa3a.png)

**系统信息:**
 - 发行平台: [微信小程序]
 - HBuilderX版本 [HBuilderX 3.73]
 - uni-app版本 [3.0.0-3061520221228001]

**Comment by Wangyaqi** [comment]
catch到的错误信息是什么？

**Comment by Createitv** [comment]
> catch到的错误信息是什么？

![image](https://user-images.githubusercontent.com/39019652/223027498-8038dbe8-07ea-40fd-bd2d-e324304a8f76.png)

**Comment by Wangyaqi** [comment]
项目是使用HBuilderX的运行菜单运行的吗？

**Comment by Createitv** [comment]
> 项目是使用HBuilderX的运行菜单运行的吗？我这边测试是正常的

是在HBuilderX中运行的。我是一个CLi项目部目再加的UniCloud，运行小程序一直都是在HBuilderX中运行它可以直接打开微信开发者工具。就一直显示没关联服务空间。

**Comment by Createitv** [comment]
> 项目是使用HBuilderX的运行菜单运行的吗？我这边测试是正常的
刚刚又测试了一下， 在H5中运行正常 但是在微信小程序中就报错。有办法吗

**Comment by Wangyaqi** [comment]
小程序里面打开的项目对吗？确定下打开的是dev模式的还是发行模式的

**Comment by Createitv** [comment]
> 小程序开发工具里面打开的项目对吗？确定下打开的是dev模式的还是发行模式的

我用HBuilder里面点的运行而不是发行应该就是 dev模式吧

**Comment by Createitv** [comment]
> 小程序开发工具里面打开的项目对吗？确定下打开的是dev模式的还是发行模式的

我直接用 HBuilder新创建了一个项目用 HBuilder的编译器 在H5 微信小程序中。云函数又都可以使用了，是Cli模式什么需要配置下吗？

**Comment by Wangyaqi** [comment]
不需要额外配置，上面说的是想让你确认下你在小程序开发工具里面有没有选错uni-app项目的输出目录。uni-app发行和运行的输出目录是不一样的

**Comment by Createitv** [comment]
> 不需要额外配置，上面说的是想让你确认下你在小程序开发工具里面有没有选错uni-app项目的输出目录。uni-app发行和运行的输出目录是不一样的

没有选错目录啊，界面也都编译出来了
![image](https://user-images.githubusercontent.com/39019652/223060177-4d078133-96f2-4e08-83dd-33c80f3f9dda.png)

**Comment by zhx446** [comment]
这个问题解决了吗，我也遇到了这个问题

**Comment by Wangyaqi** [comment]
按照提示用HBuilderX的运行菜单运行cli项目即可。切记不是在终端内自己输命令，而是要用HBuilderX的运行按钮

**Comment by chenrenxing** [comment]
楼主这个问题有解决吗 我现在遇到你一样的问题 也是cli创建的项目
