### ISSUE TITLE
你们sourcemap怎么做得怎么回事？同一个项目不同电脑有的能生效，有的失效？？

### ISSUE THREAD

**Issue by 1596944197** [dcloudio/uni-app#4195]
### 对比图（以下运行同一个项目）
```
故障机:
系统:win11
node版本:相同
yarn版本:相同
执行终端:powershell/cmd/wsl-ubuntu20.0.4(该终端未测试)

非故障机:
系统:win10未激活
node版本:16.19.1
yarn版本:1.22.19
执行终端:powershell/cmd
```

### 并且项目生成的sourcemap地址相同
![image](https://user-images.githubusercontent.com/68650762/223942650-4cbb643e-c3bc-439c-8550-0ab6e7cbe532.png)
<img width="515" alt="image" src="https://user-images.githubusercontent.com/68650762/223942763-c4d356ac-63ac-4f43-b992-20464244e123.png">

**Comment by Otto-J** [comment]
是 cli 还是 hbuidlerx？
如果是前者，请确认代码的是否在相同分支，检查是否使用了相通的 npm 包管理工具
如果是后者，检查是否使用了相通的 hbuiderx 版本。

如果可以复现问题，请提供一个简化版本的复现案例
