### ISSUE TITLE
createSelectorQuery  fields

### ISSUE THREAD

**Issue by loewe0202** [dcloudio/uni-app#420]
**问题描述**
[问题描述：fields 在支付宝小程序中报错]

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码]
uni.createSelectorQuery().selectViewport().scrollOffset(res => {
        console.log("竖直滚动位置" + res.scrollTop);
      }).exec();

      let view = uni.createSelectorQuery().select(".center");
      view.fields({
        size: true,
        scrollOffset: true
      }, data => {
        console.log("得到节点信息" + JSON.stringify(data));
        console.log("节点的宽为" + data.width);
      }).exec();

      view.boundingClientRect(data => {
        console.log("得到布局位置信息" + JSON.stringify(data));
        console.log("节点离页面顶部的距离为" + data.top);
      }).exec();

**预期结果**
[获取页面元素节点信息]

**实际结果**
[TypeError: view.fields is not a function
    at Vue.test (index.js:57)
    at Vue.onLoad (index.js:50)
    at vendor.js:8544
    at walkInTree (vendor.js:8510)
    at callHook$2 (vendor.js:8542)
    at Object.onLoad (vendor.js:8567)
    at de (af-appx.worker.ide.min.js:7)
    at pt.load (af-appx.worker.ide.min.js:7)
    at af-appx.worker.ide.min.js:7
    at ae (af-appx.worker.ide.min.js:7)]

**系统信息:**
 - 发行平台: [支付宝小程序]
 - 操作系统 [ IDE]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.9.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 74.0.3729.169
    Firefox: 66.0.5
    Safari: 11.1.2
  npmPackages:
    @dcloudio/uni-app-plus: * => 0.0.236
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: * => 0.2.949
    @dcloudio/uni-h5: * => 0.5.2
    @dcloudio/uni-mp-alipay: * => 0.0.806
    @dcloudio/uni-mp-baidu: * => 0.0.834
    @dcloudio/uni-mp-toutiao: * => 0.0.334
    @dcloudio/uni-mp-weixin: * => 0.0.956
    @dcloudio/uni-template-compiler: * => 0.9.171
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 0.9.510
    @dcloudio/vue-cli-plugin-uni: latest => 0.9.464
    @dcloudio/webpack-uni-mp-loader: * => 0.3.624
    @dcloudio/webpack-uni-pages-loader: * => 0.2.828
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.7.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.7.0
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-service: ^3.7.0 => 3.7.0
    @vue/cli-shared-utils:  3.7.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-router:  3.0.1
    vue-style-loader:  3.1.2 (3.1.2)
    vue-template-compiler: ^2.5.21 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
    weex-vue-loader: ^0.7.0 => 0.7.0
  npmGlobalPackages:
    @vue/cli: 3.7.0]
 - 设备信息 [IDE]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by dcloudhdx** [comment]
更新cli，已修复此问题
因支付宝限制，目前与app/微信有差异，一次只能传入1个参数，多个参数需要再次select

**Comment by cute001** [comment]
HbuilderX  2.1.3.20190723版本中也报错。
