### ISSUE TITLE
打包微信小程序 slot 插槽打包问题

### ISSUE THREAD

**Issue by monkeying-boy** [dcloudio/uni-app#4203]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
uni-app 使用 slot 插槽，打包成微信小程序后没有正确渲染。

在 h5 环境中渲染结果正常
![image](https://user-images.githubusercontent.com/42661516/225565252-e8bc32a2-52f6-4b85-9137-5cf24ac64841.png)

在 微信小程序中渲染结果为空
![image](https://user-images.githubusercontent.com/42661516/225565192-6328f88f-d143-4bb8-a8e4-bcd3512419f3.png)

**复现步骤**
[复现问题的步骤]
git clone https://github.com/monkeying-boy/uni-app-slot.git
1.  启动  yarn dev:mp-weixin

[或者可以直接贴源代码]

**预期结果**
期望和h5 表现一致

**补充信息**
[可选]
看 微信小程序开发者工具上面的 xml 感觉像是没有正确加载组件。

**Comment by monkeying-boy** [comment]
复现 demo [uni-app-slot.zip](https://github.com/dcloudio/uni-app/files/10988799/uni-app-slot.zip)

**Comment by monkeying-boy** [comment]
复现 demo [uni-app-slot.zip](https://github.com/dcloudio/uni-app/files/10988799/uni-app-slot.zip)

**Comment by zhetengbiji** [comment]
![image](https://user-images.githubusercontent.com/6326057/225628920-fbbb74e7-439b-4bd5-b6b4-5b682842b492.png)
这样的效果是否符合预期，如果符合，请等待下次更新：https://github.com/dcloudio/uni-app/issues/3503

**Comment by monkeying-boy** [comment]
> ![image](https://user-images.githubusercontent.com/6326057/225628920-fbbb74e7-439b-4bd5-b6b4-5b682842b492.png) 这样的效果是否符合预期，如果符合，请等待下次更新：#3503

符合预期。麻烦再确认一下如果进行多层 slot 传递是否会出现微信小程序组件打包异常

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/3503 中提到的问题和多层 slot 无关，是微信小程序不支持同一个 slot 渲染多个实例。

多层 slot 的问题可能需要另外讨论。

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/3503#issuecomment-1475812973
