### ISSUE TITLE
uniapp官网package.json问题钉钉小程序

### ISSUE THREAD

**Issue by Too-Be** [dcloudio/uni-app#4205]
**问题描述**
官网有关于钉钉小程序package.json文件是有问题的，我copy之后无法在运行与发行按钮找到钉钉小程序

**复现步骤**
1.根目录下新建package.json
2.copy官网的package.json

**预期结果**
运行与发行按钮出现钉钉小程序选项

**实际结果**
无上述选项
![屏幕截图(32)](https://user-images.githubusercontent.com/96402176/225691462-b4bcaba3-f5b8-4f50-bf87-0b6ca27d280c.png)

**补充信息**
[可选]
package.json代码错误，望改正

**Comment by weixisheng** [comment]
数据不完整啊，官网写法只是扩展uni-app节点，省略了前后的一大段，但是你新建文件就不能这样
