### ISSUE TITLE
swiper设置next-margin属性后 当滑动到最后一个item时后面空出一片空白

### ISSUE THREAD

**Issue by kbgyf** [dcloudio/uni-app#421]
**问题描述**
swiper设置next-margin属性后 当滑动到最后一个item时后面空出一片空白
**复现步骤**
`<swiper class="swiper" :next-margin="60" :indicator-dots="indicatorDots" :autoplay="autoplay" :interval="interval" :duration="duration">
`
**预期结果**
到最后一个item就不在往后transform了
![image](https://user-images.githubusercontent.com/37326126/58543389-fb249d80-8231-11e9-941c-0316b0df89ff.png)

**实际结果**
![image](https://user-images.githubusercontent.com/37326126/58543195-936e5280-8231-11e9-9c7a-930044a8b57d.png)

![image](https://user-images.githubusercontent.com/37326126/58543178-8baeae00-8231-11e9-9061-be5cbeba0585.png)

**系统信息:**
 - 微信小程序
 - iOS 12.3.1
 - HBuilderX版本 1.9.9.20190522
 - iPhone7

**Comment by zhetengbiji** [comment]
并非问题，设计如此

**Comment by he426100** [comment]
> 并非问题，设计如此

能否改一下？ 或者给一个选项？ 第一个的左边、最后一个的右边都不应该留空

**Comment by liubei-1135284904** [comment]
怎么可能设计如此。是bug吧，三张图片循环就是好的，非循环不行，二张循环或非循环都不行，

**Comment by liubei-1135284904** [comment]
真实一个尴尬的问题，
![image](https://github.com/user-attachments/assets/40c552f6-6a17-490c-8dec-ca4a1c28b8c9)
![image](https://github.com/user-attachments/assets/831078d8-00ef-4740-b27d-8ef07c22668a)
