### ISSUE TITLE
 scroll-view无法设置关闭IOS回弹效果

### ISSUE THREAD

**Issue by rohxty** [dcloudio/uni-app#4213]
**问题描述**
如何关闭bounce回弹效果，在scroll-view设置了"bounce" : "none"没有用

**复现步骤**
[复现问题的步骤]
<scroll-view bounce="none"> </scroll-view>

**预期结果**
关闭回弹·效果

**实际结果**
回弹依然存在

**系统信息:**
 - 发行平台:  App
 - 操作系统  iOS 14.6 
 - uni-app版本 3.0.0
 - 设备信息 iPhone 12 mini

**Comment by chaolapaojiao** [comment]
解决了吗 老哥

**Comment by zhetengbiji** [comment]
不支持
