### ISSUE TITLE
心累啊，社区报了这么多`bug`一个都不处理，申请付费咨询也未收到任何回信

### ISSUE THREAD

**Issue by yl-yue** [dcloudio/uni-app#4214]
## 吐槽
第一次感觉这么心累，简直是`bug` **app**了，主要还没人跟踪解决。`uni-ui`的`bug`与不完善最为严重，怪不得社区中那么多三方**UI**，而且都很火，估计也没有开发者像我一样，傻傻的只用**纯官方UI**

`HBuilderX` 与 `uniapp`的`bug`相对少点（但也只能说少点），估计是踩坑的人多的缘故吧。

短短几周，报的`bug`量（见我的提问）：https://ask.dcloud.net.cn/people/ylyue

只有一两个提问不是`bug`，想想还有一些是没有报上来的，我直接改源码修复的，是不是就能理解了。

这给人一种不是缺斤少两就是`bug`帝的感觉，社区解决方案越活跃，其实对官方并不是好事，反倒让人反复踩坑与重复造轮子。

就一个`http`请求拦截器需求，我知道社区与完整的解决方案，但那不正代表`uni.request`的垃圾么，还有UI组件库，社区不论免费的还是收费的都很多，那不正是说明`uni-ui`的垃圾么，确实整死我这种重度强迫症患者，要么继续信赖官方，要么弃坑转社区。

`uniapp`也是观望了好几年了，只能说句唉。

## 感慨
`uniapp`的技术理念，个人认为确实很好，也非常感谢官方的无私开源，但虽然是白嫖，也真的太痛苦了，等了这几年，特意挑这个时间点全面入坑，一开始也报着有坑一起踩的心态，但搞的这几周，确实将人搞崩溃了。

怎么说呢，**大bug未遇到**（此路不通的情况，都是可以换着花样克服的困难），缺斤少两与小bug不断，总结了下，uni团队一直往前赶，并没有稍微暂停下，好好的回顾身后（就像手机、笔记本这些电子产品一样，踩过坑的都知道，大厂与小厂的品控与售后简直了）。

快脚步适配了无数小程序，但最基础的app、h5开发，却还留坑不断。

最后也期望uniapp越来越好吧，毕竟已入坑，而且uniapp的好确实也不用说了，是真牛逼。但这品控质量让人直摇头。

## 最后
估计大家要说，白嫖还这么多事，但不吐不快，也是期望uniapp能更好，而且我也不是那种一毛不拔的人，有能力就支持，没能力或想白嫖的就为爱发电。

**Comment by zhetengbiji** [comment]
感谢反馈，你社区提这些问题，我会分拣一下给对应的开发组。

后续遇到问题还请继续反馈。
