### ISSUE TITLE
pnpm 下使用 uni-ui + easycom 报错

### ISSUE THREAD

**Issue by qiujie8092916** [dcloudio/uni-app#4218]
**问题描述**
如题（从HBuilderX创建的空项目，再通过pnpm install @dcloudio/uni-ui，并依据[ https://zh.uniapp.dcloud.io/collocation/pages.html#easycom](https://zh.uniapp.dcloud.io/collocation/pages.html#easycom)配置）

**实际结果**
微信开发者工具控制台报错：
![dd5dc0fb70565ee18755519736dcd08](https://user-images.githubusercontent.com/18651667/226668166-6ca0bb70-7b0f-4bce-8b43-6d76af0b7966.png)

实际生成的页面`json`文件生成路径：
![13e5665d62a06b342065870b45271eb](https://user-images.githubusercontent.com/18651667/226668182-84a3e506-9b47-447f-a73b-73d2daf41ded.png)

实际编译出来后的`node_modules`：
![31dbc4661a5c7d77bc0766eced03bd4](https://user-images.githubusercontent.com/18651667/226668191-d8fe0de4-34b1-4933-93fa-27f6c9c877c1.png)

**预期结果**
不报错，并且能正常显示`uni-ui`库组件

**系统信息:**
 - 发行平台: 微信小程序等
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本：3.7.3.20230223

**补充信息**
删除`node_modules`，重新用`yarn`安装后，显示正常

**Comment by GrapevineLin** [comment]
easycom不支持软链吧

**Comment by Otto-J** [comment]
感谢反馈，你提到 pnpm 安装 uni-ui 不能正常使用，如果是这个使用场景，我提供一个可以直接运行的 demo，使用的 pnpm + vue-ui
https://gitcode.net/xiurensha5731/uni-app-questions/-/tree/q/uni-ui/src

你可以测试你是否正常，如果不正常请重新 repopen
