### ISSUE TITLE
计算属性中无法访问this.$parent

### ISSUE THREAD

**Issue by zhengzheming** [dcloudio/uni-app#422]
**问题描述**
组件计算属性中访问this.$parent 返回 undefined , 在Vue中是可以获取父实例的。

**复现步骤**
[复现问题的步骤]
在计算属性中console.log(this.$parent)

**预期结果**
希望能在computed中访问 this.$parent

**实际结果**
![image](https://user-images.githubusercontent.com/24381434/58548903-ee597700-823c-11e9-9070-8a5e8fde26ee.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 微信开发者工具

**补充信息**
可能是这里deep copy 的问题.
![image](https://user-images.githubusercontent.com/24381434/58548833-b7836100-823c-11e9-8959-edacee9a1ff0.png)

**Comment by fxy060608** [comment]
升级最新的 HBuilderX 再试下

**Comment by zhengzheming** [comment]
我没有用HBuilderX， 而是vue-cli。所以uniapp现在是支持在计算属性中使用 this.$parent 的吗？

**Comment by zhetengbiji** [comment]
支持
