### ISSUE TITLE
uniapp中抖音小程序端，props为 funciton 时，失效

### ISSUE THREAD

**Issue by kittyShuting** [dcloudio/uni-app#4221]
抖音现在已经支持 props 的类型为 function 的了，具体文档如下所示：
![image](https://user-images.githubusercontent.com/128589459/226865545-2af5dcd2-57ce-4c1e-a859-4aa292b8afe3.png)

可是 uniapp 编译后的抖音小程序的类型还没有支持  function，导致无法试用抖音小程序的这个新特性，希望能支持一下

**Comment by zhetengbiji** [comment]
https://github.com/dcloudio/uni-app/issues/1522
