### ISSUE TITLE
vue3 setup 语法，在renderjs中无法直接通过this获取我逻辑层的数据，但是vue2是可以的

### ISSUE THREAD

**Issue by 007-liang** [dcloudio/uni-app#4224]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
```
<script lang="ts">
  setup(props, { emit }) {
    const mydata = ref({ name: 'qqq' })
    return {
      mydata 
    }
  },
}
</script>


```

```
<script module="render" lang="renderjs">

export default {
  mounted() {
     console.log(this.mydata) // undefined
  },
}
</script>
```

[或者可以直接贴源代码]

**预期结果**
正常输出this.mydata的值

**实际结果**
输出 undefined

输出 undefined

### 平台
项目创建方式: HBuilderX 3.7.8
window11
红米 K20Pro 安卓11
vue3 + ts + renederjs

**Comment by zhetengbiji** [comment]
Vue2 也不支持获取，直接使用属于开发者发现的文档之外规律。

这些数据实际上存在于逻辑层，而 Vue2 由于一些设计原因，部分数据同步到了视图层，且能被 renderjs 获取到，实际上这些数据是不可靠的，尽量不要依赖。
