### ISSUE TITLE
支付宝小程序启动报错

### ISSUE THREAD

**Issue by Mrchen128** [dcloudio/uni-app#4227]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1、支付宝搜索小程序后打开，直接进入404页面；
2、支付宝官方排查之后说代码报错：
`TypeError: this.$vm.$callHook is not a function
at Object.Hd.a.indexOf.e.(anonymous function) [as onPageNotFound] (https://2021003131655821.hybrid.alipay-eco.com/index.worker.js:187:66925)`

[或者可以直接贴源代码]

**预期结果**
希望能不报错，正常进入

**实际结果**
![2622f83f2f4ebea467f28762f7729aeb](https://user-images.githubusercontent.com/43802788/227420524-c59cf5d8-fae1-4342-ad8c-4a3080e28c3c.png)
**系统信息:**
支付宝小程序线上版本（华润万家超市）

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhenyuWang** [comment]
测试你的开发环境 默认模板项目是否存在该问题，如存在尝试升级HBuilderX 版本重试
如不存在，基于报错检查下代码逻辑
如确认框架问题，提供最简可复现demo， 谢谢

**Comment by Mrchen128** [comment]
> 测试你的开发环境 默认模板项目是否存在该问题，如存在尝试升级HBuilderX 版本重试 如不存在，基于报错检查下代码逻辑 如确认框架问题，提供最简可复现demo， 谢谢

开发环境和我们自己的手机都是没有问题的，但是线上环境有一些用户会有此类现象，这些用户我们已知的是使用华为手机鸿蒙系统。另外绝大部分用户删除小程序后再次打开会恢复正常，还有一些反馈还是会复现。

**Comment by Mrchen128** [comment]
> > 测试你的开发环境 默认模板项目是否存在该问题，如存在尝试升级HBuilderX 版本重试 如不存在，基于报错检查下代码逻辑 如确认框架问题，提供最简可复现demo， 谢谢
> 
> 开发环境和我们自己的手机都是没有问题的，但是线上环境有一些用户会有此类现象，这些用户我们已知的是使用华为手机鸿蒙系统。另外绝大部分用户删除小程序后再次打开会恢复正常，还有一些反馈还是会复现。

我这里有一个录屏，是否可以发给你们作为分析的材料

**Comment by Mrchen128** [comment]
> > 测试你的开发环境 默认模板项目是否存在该问题，如存在尝试升级HBuilderX 版本重试 如不存在，基于报错检查下代码逻辑 如确认框架问题，提供最简可复现demo， 谢谢
> 
> 开发环境和我们自己的手机都是没有问题的，但是线上环境有一些用户会有此类现象，这些用户我们已知的是使用华为手机鸿蒙系统。另外绝大部分用户删除小程序后再次打开会恢复正常，还有一些反馈还是会复现。

https://hh-oss-html.miyapay.com/box/38c95f8aa29629ad0d92211805d623e4.mp4，这个是出现问题的录屏

**Comment by zhenyuWang** [comment]
> > 测试你的开发环境 默认模板项目是否存在该问题，如存在尝试升级HBuilderX 版本重试 如不存在，基于报错检查下代码逻辑 如确认框架问题，提供最简可复现demo， 谢谢
> 
> 开发环境和我们自己的手机都是没有问题的，但是线上环境有一些用户会有此类现象，这些用户我们已知的是使用华为手机鸿蒙系统。另外绝大部分用户删除小程序后再次打开会恢复正常，还有一些反馈还是会复现。

建议针对鸿蒙系统测试下你的项目，定位问题点，基于已给出的信息，无法确认是框架问题，而且也无法排查
