### ISSUE TITLE
[Vue warn]: Failed to mount component: template or render function not defined.

### ISSUE THREAD

**Issue by LLily7** [dcloudio/uni-app#423]
**问题描述**
总是报错vue.runtime.esm.js:619 [Vue warn]: Failed to mount component: template or render function not defined.
bug重现原因不详，好多次新建的页面好的，都没怎么写内容就突然开始报这个错了。（刚建的时候一切正常）。懵逼，好几天了反复出现这个问题，

**复现步骤**
[复现问题的步骤]
1.  新建页面，一切正常
2. 编辑页面，没有问题
3. 某个时候（可能什么都没改动）突然报错

上代码吧
![image](https://user-images.githubusercontent.com/28000079/58606765-74be9900-82cf-11e9-899c-e532d5a8442e.png)
![image](https://user-images.githubusercontent.com/28000079/58606782-80aa5b00-82cf-11e9-9eb2-4f31c0c21bfd.png)
![image](https://user-images.githubusercontent.com/28000079/58606792-89029600-82cf-11e9-82f1-de0d2b9dc000.png)

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/28000079/58606797-9586ee80-82cf-11e9-8a54-3dc544151993.png)

**系统信息:**
 - 发行平台:  微信小程序、H5平台
 - 操作系统  windows8
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 hello uni-app
 - 设备信息

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
Vue吧

**Comment by LLily7** [comment]
求大佬救命呀~完全不知道bug重现规律

**Comment by LLily7** [comment]
问题解决惹~https://ask.dcloud.net.cn/question/65281 给其他小伙伴参考。感谢同事的热心帮助

**Comment by fxy060608** [comment]
最新 HBuilderX 已修复此问题
