### ISSUE TITLE
H5 Map组件高德地图`includePoints`无效

### ISSUE THREAD

**Issue by nadirvishun** [dcloudio/uni-app#4230]
**问题描述**
H5 Map组件高德地图`includePoints`无效

**复现步骤**
```javascript
<template>
  <view class="content">
    <map
      ref="map"
      id="map"
      class="map"
      :latitude="latitude"
      :longitude="longitude"
      :markers="markers"
      :polyline="polyline"
      :include-points="points"
    >
    </map>
  </view>
</template>

<script>
export default {
  data() {
    return {
      title: "Hello",
      markerIcon: require("@/static/marker.png"),
      latitude: null,
      longitude: null,
      markers: [],
      polyline: [],
      points: [],
    };
  },
  onReady() {
    this.initMap();
  },
  methods: {
    initMap() {
      let data = [
        {
          longitude: 116.284451,
          latitude: 39.823066,
        },
        {
          longitude: 117.064522,
          latitude: 40.133483,
        },
        {
          longitude: 117.093158,
          latitude: 40.14781,
        },
      ];
      let markers = [];
      let points = [];
      let i = 0;
      for (let item of data) {
        if (i === 0) {
          this.latitude = item.latitude;
          this.longitude = item.longitude;
        }
        let marker = {
          latitude: item.latitude,
          longitude: item.longitude,
          iconPath: this.markerIcon,
          width: 25,
          height: 25,
          callout: {
            //自定义标记点上方的气泡窗口 点击有效
            content: "测试", //文本
            padding: 5,
            color: "#ffffff", //文字颜色
            fontSize: 14, //文本大小
            borderRadius: 2, //边框圆角
            bgColor: "#00c16f", //背景颜色
            display: "BYCLICK", //常显
          },
        };
        markers.push(marker);
        let point = {
          latitude: item.latitude,
          longitude: item.longitude,
        };
        points.push(point);
        i++;
      }
      this.markers = markers;
      this.points = points;
      this.polyline = [
        {
          points: points,
          color: "#0081ff",
          width: 3,
          arrowLine: true,
          dottedLine: true,
        },
      ];
    },
  },
};
</script>

<style>
.map {
  width: 100%;
  height: 400px;
}
</style>
```

**预期结果**
正常应该根据所有的markers来在视图中展示出来

**实际结果**
无效，报错：
```
[Vue warn]: Error in event handler for "boundsready": "Error: Invalid Object: Bounds([object Arguments])"

[system] Error: Invalid Object: Bounds([object Arguments])
```

**系统信息:**
 - 发行平台：H5平台
 - 操作系统：windows浏览器和企业微信浏览器
 - uni-app版本：uni-app v3.7.8  uni-app cli v2.0.2-3070820230322001
 - 设备信息:：安卓及edge浏览器

**补充信息**
- 同时也测试了` this._mapContext.includePoints`方法，同样报错。
- 如果只传递两个坐标过去是生效的，但是`padding`不起作用。
- 看了下高德的api是这样的：`new AMap.Bounds(southWest: LngLat, northEast: LngLat)`，也就是说只支持传递两个坐标：西南角经纬度，东北角经纬度值，并不和文档中描述的将所有markers都传递过去就可以。高德中的有一个用法是`setFitView`，但是在`@dcloudio\uni-h5\src\platforms\h5\view\components\map\index.vue`中`_map`对象并没有对外暴露，导致也没法调用此方法，有没有方法能获取到高德原生的map对象？不暴露出去导致很多功能受限制。
- 顺便还有一个小bug，如果`marker`没有设置`width`和`height`，那么`callout`气泡会遮挡`marker`，还有就是`callout`文档中说识别换行符，实际上不识别`\n`，只识别`<br>`，不知道只是高德地图这样还是其它的也这样。

**Comment by nadirvishun** [comment]
发现可以通过此方法临时解决：
- map组件中增加监听`mapready`
  ```
  <map ref="map" class="map":latitude="latitude" :longitude="longitude" :markers="markers" :polyline="polyline"
       @mapready="handleMapReady" >
  </map>
  ```
- 调用高德的`setFitView`方法
  ```
  handleMapReady() {
    this.$refs.map._map.setFitView()
  }
  ```

**Comment by zhenyuWang** [comment]
1. Map组件 高德 include-points 只支持传入两个坐标点，文档已补充说明
2. mapContext. includePoints 并不支持 H5端，故存在不支持 padding 情况
3. marker未设置宽高，callout 遮挡图片及 \n 换行问题复现，这边排查下
感谢反馈

**Comment by nadirvishun** [comment]
@zhenyuWang  `Map组件 高德 include-points 只支持传入两个坐标点，文档已补充说明`。
感觉这个仅仅是文档说明应该是不够的，因为：
- 用户有多个点时自己并不好区分那个是最靠边的西南角和东北角，这样还是无法完整展示所有的点。
- 其次include-points没有padding参数，导致即便是两个点正常显示也是紧紧靠在边界上。

感觉还是在includePoints相关的方法中直接调用`setFitView()`最方便

**Comment by zhenyuWang** [comment]
> @zhenyuWang `Map组件 高德 include-points 只支持传入两个坐标点，文档已补充说明`。 感觉这个仅仅是文档说明应该是不够的，因为：
> 
> * 用户有多个点时自己并不好区分那个是最靠边的西南角和东北角，这样还是无法完整展示所有的点。
> * 其次include-points没有padding参数，导致即便是两个点正常显示也是紧紧靠在边界上。
> 
> 感觉还是在includePoints相关的方法中直接调用`setFitView()`最方便

1. 只支持两个坐标点问题受高德地图 api 限制，暂无较好方案
2. 两个点紧贴边界问题，可在设置 include-points 时适当调整经纬度值
3. 框架api 需考虑多端一致性，暂无暴露高德地图 setFitView 计划
如存在较多设置地图视野需求，可以考虑其他地图服务商，高德针对该需求的处理相对弱一些

**Comment by nadirvishun** [comment]
@zhenyuWang ，用`setFitView `的话兼容性确实是个问题，所以还是回归到原有方法：
- 计算最靠边的西南角和东北角实际上比较大小就能算出来：
```
 calculateBounds(points) {
   let swLat = points[0].latitude;
   let swLng = points[0].longitude;
   let neLat = points[0].latitude;
   let neLng = points[0].longitude;
   for (let i = 1; i < points.length; i++) {
     const {latitude, longitude} = points[i];
     swLat = Math.min(swLat, latitude);
     swLng = Math.min(swLng, longitude);
     neLat = Math.max(neLat, latitude);
     neLng = Math.max(neLng, longitude);
    }
   return [
     {latitude: swLat, longitude: swLng},
     {latitude: neLat, longitude: neLng}
   ];    
},
```
- 贴边的问题，高德的setBounds方法是有其它参数的`setBounds(bounds, immediately, avoid)`，第三个参数就是padding，也可以设置成一个默认值不贴边。
- 上述两个问题最好是在map组件中由你们官方来兼容下，而不是让用户自己去计算。

**Comment by zhenyuWang** [comment]
感谢反馈，若该需求用户较多，会考虑支持
