### ISSUE TITLE
支付宝小程序，app.json文件内有，"useDynamicPlugins": true，的配置，在uniapp的app.json加入这个配置不会编译出来

### ISSUE THREAD

**Issue by Dizzy-zz** [dcloudio/uni-app#4245]
**问题描述**
支付宝小程序，app.json文件内有，"useDynamicPlugins": true，的配置，在uniapp的app.json加入这个配置不会编译出来

**复现步骤**
<img width="630" alt="image" src="https://user-images.githubusercontent.com/26196307/229487750-1da5889b-f430-4969-b338-c23eebc8d74e.png">

**预期结果**
编译的时候，在app.json里面有这个配置

**实际结果**
编译的时候，在app.json里面没有这个配置

**系统信息:**
 - 发行平台: 支付宝小程序
 - 操作系统: Macos 12.3
 - uni-app版本: 3.0.0-alpha-3070720230316001
 - 设备信息: 支付宝小程序开发者工具

**Comment by zhetengbiji** [comment]
参考一下：https://ask.dcloud.net.cn/article/39114
