### ISSUE TITLE
开发者使用建议

### ISSUE THREAD

**Issue by gezhongqi** [dcloudio/uni-app#4246]
首先本人于22年4月份发布了一篇关于平台的使用建议文章，历时一年由于点击量过高，排名在百度搜索前3名，从而被平台官方盯上了，原因是我写的文章有针对平台的使用的问题进行了说明和建议，说白了就是官方看不惯我说他们一点不好，首先文章是很客观的，也是包含了本人使用的亲身经历和实际发生的问题，为此于2023年3月31日，平台官方人员私自查用了我的私人手机号，并打电话沟通之前我发布的问题(之前2年前发布的问题都没有这么主动)，电话语气十分不屑，官方说是为了沟通问题，但是我用了两年多了，没见过一次打电话，直到官方最后说出了真实用意，让我删除某书上的文章(就是前面提到的建议文章), 我也是没多理会没有时间和这个平台纠缠，隔日我看到平台我发布的问题官方人员进行了回复，目的很明确也是让我删除帖子，然后当天我的文章被百度关闭了推荐，4月4日简书封锁了我的文章，文章阅读量不多2700左右，受到官方重视我也是很荣幸。

情况就是这样，令我吃惊的是平台的营销和公关手段，比他们的平台做的要好不知道几倍，本来我看百度推广下了就下了，无所谓但是你们有点太欺负人了，文章直接给我封锁？怎么我说的某些点，戳到他们的痛楚了？亲身经历你和我说我发的东西不属实，既然这样我们客户很多,平台的客户也有很多，况且我不忙的时候会照顾下他们。

我可能干不过一个《大平台》，但是我有我坚持的底线和原则，用户提出问题应该去解决找方案，而不是这样做，我很少黑任何东西和人，但是平台确实过分，以后我也不会黑了，我会一五一十的说实话，把这些经历分享给大家，好看清某些平台的嘴脸。

声明 本帖子不涉及任何dcloud官方的东西，文章所指为其他平台。

**Comment by gezhongqi** [comment]
下面贴出文章全部内容，文章官方为dcloud由于某书封锁修改了此关键字。
#一、 前言
  首先本人为某混合开发平台-插件开发使用者(原生开发插件供js等前端调用)，刚开始由于客户需求某混合开发平台的插件这方面的插件，故着手开发，开发经验目前2年（被坑埋了2年）。

#二、 入坑准备
  ###1.平台调研
首先如果您想用某混合开发平台这个平台，这第一步也是最重要的一步，就是调研，也就是要明白这个平台的底，要知道目前平台情况，以及使用者的评价，技术方面要了解是否平台能完全满足自身产品的需求，并且要完美兼容，对于一个即将进入新平台开发的产品，这些东西都尤为重要，建议不要向官方咨询，多咨询相关的开发者和使用者。

###2.产品定位
第二步、如果平台调研完毕，如果觉得凑合能用，那就要了解您的产品定位，是纯前端语言(js.h5等)，还是说混合开发语言(android、ios、js等)，为什么要弄清楚这点，因为以我目前了解，纯前端开发模式比混合开发模式要体验好，坑相比较少，但是如果你一旦涉及到原生，就要考虑兼容性，功能可用性，因为很多原生功能某混合开发平台是不支持混合开发的，还有一方面就是混合开发部分坑较多，所以建议前端开发者可以考虑用，但是一旦涉及原生并且复杂的功能，建议多多的调研。

###3.广告问题
这第三点也是最近看到部分开发者反馈的问题，就是广告插件，具体细节我就不多说了，想开发广告插件的要注意。
参考 https://baijiahao.baidu.com/s?id=1678874385127000223&wfr=spider&for=pc

###4.官方支持问题
这个是很重要的一个问题，因为所有你遇到的兼容性问题，以及官方的bug都无法得到官方很有效和及时的支持，本人提过的问题基本都是2年无任何官方人过问的。
不懂技术的人我可以这样形容下目前为何大部分问题需要官方支持才能解决，而不是靠我们原生开发或者前端开发者自己能解决。
某混合开发平台的东西相当于一个黑盒子，云打包后只有apk能查看，或者说在某混合开发平台环境环境下的项目调试，也只能看到前端部分，原生任何报错和异常信息都捕捉不到，而前端人员又无法看到插件黑盒子里的东西，看到了也不一定都懂，所以说白就是一个大黑盒子套了几个小的，每个插件都是一个小黑盒子，任何一个出现问题会影响大的盒子，但是开发者技术人员又无法查看黑盒子出问题的原因，所以只能由官方给出解释和方案,当然前提是他们会给。

###5.风险预估
这个问题也很重要，因为对于插件开发者也好还是前端语言开发者、公司、集成商等等，风险是必须进行承担的，举个例子，最近发现官方兼容性问题导致插件集成后再某机型，特定的项目环境下出现白屏情况，客户认定是我们插件问题，但是其他项目环境和云打包处理都无法复现，其他使用插件客户也无法复现，导致商务合同终止，懂商务的都知道终止意味着损失，不管是客户还是集成商还是其他的参与者，那这个损失由谁承担，答案是使用这个混合开发平台的使用者，也就是我们自己，官方不用承担任何责任以及没有任何形式的补偿，这就产生了很大的风险，当你入坑之后遇到这类问题，很大程度上原因在于无法获得有效的官方支持，导致问题滞后，最终导致合同终止。所以想入坑某混合开发平台的公司想好如果承担的起这个风险可以尝试，目前由于这个风险问题，我们公司目前项目组已经不建议新用户使用某混合开发平台官方开发。

总结:
目前准备工作我建议想入坑的开发者也好公司也罢，这是最基本要调查的一些东西，本人观点，有补充请直言，不是说为了挑刺，确确实实开发过程以及使用过程有些问题，所以最好选择之前要调研好，具体什么区分哪些是宣传文章，哪些是真实使用反馈就不用我细说了吧，做好这些也是对公司和自己的产品负责。


#三、开发者注意事项(插件开发)
###1.做好自己解决问题的准备
因为发帖没人支持，官方嘛给钱估计会给你配合解决。
其次文档方面，很多官方废弃的东西，文档也不是很明确的说明，很多简单的功能以及逻辑，都找不到相应的文档，也是最鸡肋的一部分。
###2.做好任何可能出现问题的预备方案
这个说起来简单，其实蛮难的，因为你也不知道某混合开发平台什么时候抽风给你个奇葩的异常问题，只能说尽量吧.

###3.做好出现问题无法解决准备
这就相对简单了，比如我们之前开发的两款产品插件(为什么只有两款，因为开发不下去), 出现aseets下文件无法正常读写的问题，截止目前官方仍然没有任何回复和修复，目前这个问题属于奇葩问题，原生环境可以，只有在某混合开发平台的某混合开发平台环境环境下出现，而且是偶发，不定时，无法定位原因, 这是我们遇到的问题之一，类似这种可能会出现其他类似奇葩问题。

#四、某混合开发平台环境注意事项
###1.打包注意事项
① 打包时间-自定义基座(免费打包)
![微信截图_20220810113922.png](https://upload-images.jianshu.io/upload_images/18372298-eafc63a2f6ff439b.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)
如上图，打包插件自定义基座29排名，则需要28分钟，如果100人可想而知。
② 打包次数-自定义基座(免费打包)
大概每天10次左右，打包次数限制。

如上是自定义基座的一些注意事项，如果不想受约束，可以付费(你懂得)，最恶心的是当你排了30分钟的队打包，结果给你报打包异常(滑稽)。

####2.调试注意事项
如果使用了原生插件，请注意调试是没法看到原生的log以及任何报错信息，所以一旦出现了异常问题，只能通过“猜”，还有一种就是通过原生环境的项目打包好某混合开发平台的插件的资源，在原生环境下调试,这样可以不受打包以及调试影响，但是不代表原生环境下完美运行在，某混合开发平台环境里就能完美运行.

#五、原生插件兼容性
###1.jar包兼容问题
熟悉android开发的人都知道，如果两个library使用相同的jar，我们会对jar进行兼容性配置在build文件中，以避免文件相同导致冲突和不必要的增量体积，但是在某混合开发平台环境项目中，没有这类配置，我们打包好aar包关于jar的兼容配置都在aar里面，没法灵活动态的修改，这就导致当我们使用jar在相同的library里会出现很多问题，并且某混合开发平台环境环境下 如果没有这个配置，aar内本身的jar和外部的jar也会出现冲突。

###2. assets兼容问题
同样是android的资源文件目录，但是某混合开发平台环境在这方面兼容并不好，由于我们产品的授权文件是在这个目录下，我们调用我们封装的接口会初始化这个文件，将文件写入内部路径，但是在某混合开发平台环境下经常性偶发性的出现无法成功读取assets下的文件。

###3. 其他兼容问题
比如在原生离线打包，可以完美运行，但是在某混合开发平台环境环境下无法成功调用相应功能，诸如此类问题这里就不一一说明了，虽然网上很多人再洗这个平台，但是用过的人都知道，是否适合自己公司的产品，有人说不喜欢用可以不用，但是客户需求导致很多产品是被迫开发插件，所以我觉得官方可以公布所有缺点以及所有bug列表日志，给新用户看看，是否适合自己产品，当然官方敢不敢公布，谁知道呢。

**Comment by hezhuowei** [comment]
广告问题吃相太难看了

**Comment by E-10000** [comment]
确实，这些问题都是客观存在得，但是官方也不闻不问装作不知道

**Comment by tnnevol** [comment]
这脚手架，越写越烦

**Comment by ClarkWain** [comment]
好恶心的框架

**Comment by XiaoRanLiu3119** [comment]
几乎全中,我要吐了,原生插件集成调试全靠猜没毛病,只能在相关的步骤callback,一次次的试,调一次必重打基座,试几次就得花钱买次数,真是6
