### ISSUE TITLE
横竖屏问题

### ISSUE THREAD

**Issue by MQYForverT** [dcloudio/uni-app#4247]
**问题描述**
我在manifest.json文件中指定screenOrientation为["portrait-primary","portrait-secondary", "landscape-primary","landscape-secondary"
],但是无法强制app启动时是竖屏？

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by ArrayDC** [comment]
强制竖屏应该配置：
screenOrientation为["portrait-primary"]

**Comment by ArrayDC** [comment]
如果只是想在特定页面锁定竖屏可以使用5+ API：plus.screen.lockOrientation

**Comment by MQYForverT** [comment]
> 强制竖屏应该配置： screenOrientation为["portrait-primary"]

你好，感谢您的回复。
可是我应用内有视频播放需求，需要全屏。我试过，如果screenOrientation为["portrait-primary"]，那当我横屏的时候，使用plus.screen.lockOrientation('landscape-primary')不起作用
