### ISSUE TITLE
接着关闭我的文章有能耐

### ISSUE THREAD

**Issue by gezhongqi** [dcloudio/uni-app#4251]
首先本人于22年4月份发布了一篇关于平台的使用建议文章，历时一年由于点击量过高，排名在百度搜索前3名，从而被平台官方盯上了，原因是我写的文章有针对平台的使用的问题进行了说明和建议，说白了就是官方看不惯我说他们一点不好，首先文章是很客观的，也是包含了本人使用的亲身经历和实际发生的问题，为此于2023年3月31日，平台官方人员私自查用了我的私人手机号，并打电话沟通之前我发布的问题(之前2年前发布的问题都没有这么主动)，电话语气十分不屑，官方说是为了沟通问题，但是我用了两年多了，没见过一次打电话，直到官方最后说出了真实用意，让我删除某书上的文章(就是前面提到的建议文章), 我也是没多理会没有时间和这个平台纠缠，隔日我看到平台我发布的问题官方人员进行了回复，目的很明确也是让我删除帖子，然后当天我的文章被百度关闭了推荐，4月4日简书封锁了我的文章，文章阅读量不多2700左右，受到官方重视我也是很荣幸。

情况就是这样，令我吃惊的是平台的营销和公关手段，比他们的平台做的要好不知道几倍，本来我看百度推广下了就下了，无所谓但是你们有点太欺负人了，文章直接给我封锁？怎么我说的某些点，戳到他们的痛楚了？亲身经历你和我说我发的东西不属实，既然这样我们客户很多,平台的客户也有很多，况且我不忙的时候会照顾下他们。

我可能干不过一个《大平台》，但是我有我坚持的底线和原则，用户提出问题应该去解决找方案，而不是这样做，我很少黑任何东西和人，但是平台确实过分，以后我也不会黑了，我会一五一十的说实话，把这些经历分享给大家，好看清某些平台的嘴脸。

声明 本帖子不涉及任何dcloud官方的东西，文章所指为其他平台。

**Comment by caizi12** [comment]
文章链接有吗，发出来看看。

**Comment by zhenyuWang** [comment]
你的问题早已在 ask 论坛回复过，请不要再污蔑 DCloud，我们有权采取更多法律手段保护自己不被诽谤

**Comment by tuonioooo** [comment]
啥文章呀 学习一下
