### ISSUE TITLE
vue3+vite+ts打包后图片无法正常显示，我已找到解决方案，但是希望官方解决一下

### ISSUE THREAD

**Issue by feelgooda** [dcloudio/uni-app#4253]
`<img class="icon" src="/static/home/1.png">`
这是我开始写的代码  打包成wgt后集成在andriod项目里，图片无法正常显示
需要修改成`<image class="icon" src="/static/home/1.png"></image>`才能正常显示
我认为这也是一个坑，希望支持一下img 标签

**Comment by StrivingRabbit** [comment]
不支持书写 `image` 标签
