### ISSUE TITLE
可以自定义条件编译条件么?

### ISSUE THREAD

**Issue by ranwawa** [dcloudio/uni-app#426]
比如我要增加
- 微信公众号
- 支付宝生活号

因们他们都是h5环境,但是jssdk以及获取code的代码是不一样的....
![image](https://user-images.githubusercontent.com/30344590/58695261-86836780-83c7-11e9-9dfa-cd00061137d7.png)

我自己在package.json里面添加了.
但是编译时报错~~~

![image](https://user-images.githubusercontent.com/30344590/58695240-79667880-83c7-11e9-859b-0e625bdc1787.png)

**Comment by xiaopin** [comment]
同求，现在一套小程序代码需要发布N个小程序版本（目前使用的原生方式开发，都是直接通过拷贝的方式管理代码，不好维护），发现 [Taro](https://github.com/NervJS/taro) 可以满足需求，但是由于没接触过 React，所以正在纠结如何优雅地处理一套代码发布N个小程序的问题。

**Comment by aiplat** [comment]
这些很简单，肯定可以自定义的。

**Comment by xiaopin** [comment]
@aiplat 能否指点一下呢，感谢！

**Comment by hbcui1984** [comment]
下个版本放开vue.config配置，开发者可自定义环境参数

**Comment by fxy060608** [comment]
已开放自定义条件编译
https://uniapp.dcloud.io/collocation/package
https://uniapp.dcloud.io/collocation/vue-config
