### ISSUE TITLE
cli 打包生产环境时，报错：ReferenceError: _m is not defined

### ISSUE THREAD

**Issue by liwenfengg** [dcloudio/uni-app#4265]
**问题描述**
cli 打包生产环境时，报错：ReferenceError: _m is not defined

**实际结果**
![image](https://user-images.githubusercontent.com/40257198/230875640-65f875f2-21fe-4385-9d49-d66cb43d3713.png)
把生产环境 sourcemap 打开后，点击  ` at _loop2 (vue.runtime.esm.js:2862) ` 跳转到了 ` const opt = computedOptions[key]; ` 
![image](https://user-images.githubusercontent.com/40257198/230875758-27563941-f3e4-4446-9b03-12991aa13240.png)

**系统信息:**
 - 发行平台: 微信小程序

**Comment by liwenfengg** [comment]
`i` `m` console 信息
![image](https://user-images.githubusercontent.com/40257198/230877203-4cb2e7e6-ac69-4b31-95d8-ca1bf2aeba15.png)

**Comment by liwenfengg** [comment]
继续随便点开一个属性

![image](https://user-images.githubusercontent.com/40257198/230880279-f74b94e1-84c4-4681-9689-6fbff6887c4f.png)

发现所有的报错都出在 `computed` 这个地方

![image](https://user-images.githubusercontent.com/40257198/230880425-aa32aea4-3c36-493c-92e1-7d35b247f669.png)

**Comment by wolf427** [comment]
遇到了一样的问题

**Comment by zhenyuWang** [comment]
manifest.json/mp-weixin/setting 增加 "es6": false 试下

**Comment by liwenfengg** [comment]
> manifest.json/mp-weixin/setting 增加 "es6": false 试下

按你说的更改打包后，使用 wechat devtools 打开还是一样的错误。

但是我把这个 `Compile Js to ES5` 取消勾选就可以了。

![image](https://user-images.githubusercontent.com/40257198/232739689-d3475047-d191-4b93-b273-d00745226b61.png)

**Comment by wolf427** [comment]
> 

取消勾选后，本地可以运行，但是上传时会报错

**Comment by zhenyuWang** [comment]
> > 
> 
> 取消勾选后，本地可以运行，但是上传时会报错

确认下配置是否符合预期，这边上传体验版并运行测试正常

**Comment by liwenfengg** [comment]
> > > 
> > 
> > 
> > 取消勾选后，本地可以运行，但是上传时会报错
> 
> 确认下配置是否符合预期，这边上传体验版并运行测试正常

我这边环境更新至 `3.0.0-alpha-3071320230417001` 后已经打包运行正常了

**Comment by wangjieCode** [comment]
各位这个问题你们是如何解决的

**Comment by wolf427** [comment]
这个应该算是微信平台和uni-app sdk兼容性上的一个bug，由于是编译时造成的，溯源起来比较困难，以下是我猜测结果：

微信开发者工具会尝试将源码编译成ES5，但是这个编译过程在最新版的uni/vue(?)上会有兼容性问题，我猜应该是babel语法导致的，所以会在该平台报错，你需要将“编译为ES5”的勾选项去掉，这样应该可以正常本地运行。

但是，微信的JS平台仍有一些ES6语法并不支持，比如我就遇到const a=b??1；会导致本地运行时不报错，但是上传时报错，这种情况你只能做针对性处理，根据上传时的报错信息，去掉不支持的语法，然后再上传。我估计微信开发者工具后续会修复这个bug

> 各位这个问题你们是如何解决的

**Comment by wangjieCode** [comment]
@wolf427  这个问题会影响线上的用户么，是不是每次小程序发布的时候必须要关闭转es5

**Comment by wolf427** [comment]
> @wolf427 这个问题会影响线上的用户么，是不是每次小程序发布的时候必须要关闭转es5

对，理论上不编译为ES5会让部分老版本无法使用，但是照理说连ES6都不支持的微信版本市面上应该可以忽略不计了

**Comment by wangjieCode** [comment]
好的，感谢回复

**Comment by StrivingRabbit** [comment]
> 好的，感谢回复

你遇到这个问题使用的是什么版本的微信开发者工具？

**Comment by wangjieCode** [comment]
<img width="357" alt="image" src="https://user-images.githubusercontent.com/49115360/234224850-94ee3225-79b8-444e-8c50-699ba7286f0b.png">
@StrivingRabbit

**Comment by StrivingRabbit** [comment]
@wangjieCode  新建一个 vue3 的项目，computed 里面随便写一个函数，在 template 中使用一下是否可以复现此问题？

**Comment by wangjieCode** [comment]
3.0.0-3070920230324001这个版本可以复现 alpha的我试一下 @StrivingRabbit

**Comment by wangjieCode** [comment]
@StrivingRabbit 也是可以的，需要我提交一个复现的仓库么

**Comment by StrivingRabbit** [comment]
> @StrivingRabbit 也是可以的，需要我提交一个复现的仓库么

这样最好了，把你复现的提交到 github 吧

**Comment by StrivingRabbit** [comment]
> 

build 出来的产物我这儿跑的没有什么问题，你是什么系统？

![Snipaste_2023-04-25_17-58-59](https://user-images.githubusercontent.com/33573212/234242892-469f8bad-d8f0-4032-a9bb-ab85f77a4353.jpg)

**Comment by wangjieCode** [comment]
mac m1版本的 @StrivingRabbit

**Comment by wangjieCode** [comment]
感谢，最新开发版已恢复正常
