### ISSUE TITLE
uniapp - vue2 - 支付宝小程序 - uni-icon无效，显示为方格

### ISSUE THREAD

**Issue by tengyuanOasis** [dcloudio/uni-app#4267]
**问题描述**
1. uniapp， npm安装的uni-ui组件包 ， 编译为支付宝小程序 ， uni-icon显示为方格（类似一个 “口” 字），

**复现步骤**
[复现问题的步骤]
1.依赖版本:  vue2 
2.uni组件包使用方式： npm安装 ， npm i @dcloudio/uni-ui 
3.使用任意uni-icon , 均显示异常

4.使用uni_module方式引入项目，显示正常

**预期结果**
期望可以像其他uni-ui使用方式一样 ， 显示为正常icon

**实际结果**
<uni-icons size="14" type="forward" color="#bfbfbf" />

![image](https://user-images.githubusercontent.com/58558076/231031309-f85a5589-fb17-4282-9adf-8e7727a36bd7.png)

**系统信息:**
 - 发行平台: [支付宝小程序]
 - 操作系统 [win11]
 - uni-app版本 [ "@dcloudio/uni-mp-alipay": "^2.0.1-36420220922003", ]

**Comment by tengyuanOasis** [comment]
<uni-icons size="14" type="forward" color="#bfbfbf" />

**Comment by 18148764734** [comment]
新版本已修复，此ISSUE暂时关闭，后续若还有疑问，欢迎提出新ISSUE
