### ISSUE TITLE
内置组件可以覆写吗

### ISSUE THREAD

**Issue by Good-WarWolf** [dcloudio/uni-app#4269]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
![image](https://user-images.githubusercontent.com/51135522/231378777-4bd88ea6-851a-450d-9dfa-0e343375ec83.png)

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
可以

**Comment by zhetengbiji** [comment]
描述一下具体的需求，然后给你推荐具体的方案

**Comment by Good-WarWolf** [comment]
> 描述一下具体的需求，然后给你推荐具体的方案

https://github.com/dcloudio/uni-app/issues/4269#issuecomment-1504817596
我是看内置组件textarea监听键盘输入实现的展示文字，我想基于这个能输入表情进去

**Comment by Good-WarWolf** [comment]
> > > 描述一下具体的需求，然后给你推荐具体的方案
> > 
> > 
> > [#4269 (comment)](https://github.com/dcloudio/uni-app/issues/4269#issuecomment-1504817596) 我是看内置组件textarea监听键盘输入实现的展示文字，我想基于这个能输入表情进去
> 
> 你的目标是哪个平台

app 端就行

**Comment by zhetengbiji** [comment]
> > > > 描述一下具体的需求，然后给你推荐具体的方案
> > > 
> > > 
> > > [#4269 (comment)](https://github.com/dcloudio/uni-app/issues/4269#issuecomment-1504817596) 我是看内置组件textarea监听键盘输入实现的展示文字，我想基于这个能输入表情进去
> > 
> > 
> > 你的目标是哪个平台
> 
> app 端就行

* 通过查看[贡献指南](https://github.com/dcloudio/uni-app/blob/dev/.github/CONTRIBUTING.md)，可以在本地修改和替换编译器内置的组件
* 不推荐替换内置组件
* 建议使用自定义组件的方式自行封装一个custom-textarea，如需使用浏览器底层API，可以利用[renderjs](https://uniapp.dcloud.net.cn/tutorial/renderjs#renderjs)
* 可以看一下[插件市场](https://ext.dcloud.net.cn/)是否有类似实现

**Comment by Good-WarWolf** [comment]
> > > > > 描述一下具体的需求，然后给你推荐具体的方案
> > > > 
> > > > 
> > > > [#4269 (comment)](https://github.com/dcloudio/uni-app/issues/4269#issuecomment-1504817596) 我是看内置组件textarea监听键盘输入实现的展示文字，我想基于这个能输入表情进去
> > > 
> > > 
> > > 你的目标是哪个平台
> > 
> > 
> > app 端就行
> 
> * 通过查看[贡献指南](https://github.com/dcloudio/uni-app/blob/dev/.github/CONTRIBUTING.md)，可以在本地修改和替换编译器内置的组件
> * 不推荐替换内置组件
> * 建议使用自定义组件的方式自行封装一个custom-textarea，如需使用浏览器底层API，可以利用[renderjs](https://uniapp.dcloud.net.cn/tutorial/renderjs#renderjs)
> * 可以看一下[插件市场](https://ext.dcloud.net.cn/)是否有类似实现

好的，谢谢大佬
