### ISSUE TITLE
data中使用下划线开头的变量不能正确更新到子组件属性

### ISSUE THREAD

**Issue by ayaka209** [dcloudio/uni-app#427]
**问题描述**
data中使用下划线开头的变量不能正确更新到子组件属性

**复现步骤**
[复现问题的步骤]
```
<xxx :yyy="_show"></xxx>
```
其中_show定义在父组件上，该变量更新不能影响子组件属性
倘若换个名字如m_show，就可以正常运行

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 8.11.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    @dcloudio/uni-app-plus: * => 0.0.236
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: * => 0.2.950
    @dcloudio/uni-h5: * => 0.5.2
    @dcloudio/uni-mp-alipay: * => 0.0.807
    @dcloudio/uni-mp-baidu: * => 0.0.834
    @dcloudio/uni-mp-toutiao: * => 0.0.334
    @dcloudio/uni-mp-weixin: * => 0.0.956
    @dcloudio/uni-template-compiler: * => 0.9.172
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 0.9.511
    @dcloudio/vue-cli-plugin-uni: latest => 0.9.464
    @dcloudio/webpack-uni-mp-loader: * => 0.3.624
    @dcloudio/webpack-uni-pages-loader: * => 0.2.828
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.7.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.7.0
    @vue/cli-plugin-babel: 3.7.0 => 3.7.0
    @vue/cli-service: ^3.7.0 => 3.7.0
    @vue/cli-shared-utils:  3.7.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-router:  3.0.1
    vue-style-loader:  3.1.2 (3.1.2)
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.1.1 => 3.1.1
    weex-vue-loader: ^0.7.0 => 0.7.0

**补充信息**
应该是和编译器有冲突吧，编译器也是用下划线的

暂时没空提供最小化的复现代码，只能空口说了。不好意思。

**Comment by fxy060608** [comment]
声明变量时，不建议使用下划线开头，部分小程序平台内部同步数据时，可能会忽略下划线开头的变量

**Comment by fxy060608** [comment]
以 _ 或 $ 开头的属性 不会 被 Vue 实例代理，因为它们可能和 Vue 内置的属性、API 方法冲突。
参考：https://cn.vuejs.org/v2/api/#data
