### ISSUE TITLE
uni.getAccountInfoSync() 兼容字节跳动小程序

### ISSUE THREAD

**Issue by hqw567** [dcloudio/uni-app#4271]
**新功能描述**
简洁描述你希望补充完善的增强功能
[uni.getAccountInfoSync()](https://uniapp.dcloud.net.cn/api/other/getAccountInfoSync.html#getaccountinfosync) 希望能兼容一下字节跳动小程序的 [tt.getEnvInfoSync()](https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/api/open-interface/env-info/get-env-info-sync)获取
**现状及问题**
[当前现状及由此导致的不便]
![image](https://user-images.githubusercontent.com/74847198/231629741-0bbaebb7-a759-492f-8e05-e1a20b020584.png)
字节跳动小程序 [tt.getEnvInfoSync()](https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/api/open-interface/env-info/get-env-info-sync) 基础库 2.21.0 开始支持本方法
![image](https://user-images.githubusercontent.com/74847198/231630152-68cd72ce-3a0e-420e-8153-9e7927638999.png)

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]
-
**补充信息**
[其它你认为有参考价值的信息]
-

**Comment by zhenyuWang** [comment]
暂时可使用 uni.getEnvInfoSync() 或 tt.getEnvInfoSync()，后续确认支持方案后会在该 issue 回复

**Comment by zhenyuWang** [comment]
已补充 [文档](https://uniapp.dcloud.net.cn/api/other/getEnvInfoSync.html)

**Comment by hqw567** [comment]
![Snipaste_2023-04-28_09-19-08](https://user-images.githubusercontent.com/74847198/235031580-c218f081-0f65-445b-bfa0-456cf97253be.png)
文档错误 https://uniapp.dcloud.net.cn/api/other/getEnvInfoSync.html

**Comment by zhenyuWang** [comment]
> 文档

感谢反馈，已修正
