### ISSUE TITLE
打包的微信小程序的时候 pages.json 文件一直打不进去

### ISSUE THREAD

**Issue by yjw-214** [dcloudio/uni-app#4272]
打包的微信小程序的时候 pages.json 文件一直打不进App.json， 我是用的Vue3/Vite版 

![image](https://user-images.githubusercontent.com/52310369/231635070-fe0320d3-9857-4d29-821c-53ca28bb5b0e.png)
![image](https://user-images.githubusercontent.com/52310369/231635144-e0e74e8f-b961-4e57-a53b-bfcecc8c0e9a.png)
![image](https://user-images.githubusercontent.com/52310369/231635176-0e90a268-1e8b-4830-8c30-5a4fa51769d5.png)

**Comment by zhenyuWang** [comment]
确认下默认模板项目是否存在该问题，如不存在，检查代码修改，如确认框架问题，提供下测试工程，谢谢

**Comment by zhenyuWang** [comment]
长时间未响应，问题暂时关闭；
若后续依然有问题，可 reopen 该 issue。

**Comment by yubo9807** [comment]
官方提供模版，`npm run mp-weixin` pages 没有被打包进去

**Comment by zhenyuWang** [comment]
> 官方提供模版，`npm run dev:mp-weixin` pages 没有被打包进去

提供测试工程，并标注不符合预期的配置
