### ISSUE TITLE
微信小程序的skyline渲染在uniapp种如何支持呀？

### ISSUE THREAD

**Issue by wangjieCode** [dcloudio/uni-app#4279]
**新功能描述**
简洁描述你希望补充完善的增强功能

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by zhenyuWang** [comment]
HBuilderX 3.7.6+ 已支持，如版本过低，请升级，如非版本问题，详细描述你的问题

**Comment by zhenyuWang** [comment]
> 普通cli项目如何使用呀，有文档么

@dcloudio 相关依赖高于对应版本即可使用，文档参考微信小程序文档即可

**Comment by wangjieCode** [comment]
好的，感谢🙏
