### ISSUE TITLE
对支付宝录音功能支持

### ISSUE THREAD

**Issue by monkeying-boy** [dcloudio/uni-app#4285]
**新功能描述**
[根据官方文档](https://uniapp.dcloud.net.cn/api/media/record-manager.html#getrecordermanager)得知**支付宝小程序不支持录音**功能，但是[支付宝小程序](https://opendocs.alipay.com/mini/api/getrecordermanager) 是支持录音功能的，希望官网能即使接入。

**现状及问题**
调用 `uni.authorize` 函数获取 `scope.record` 录音功能权限，但是获取权限失败。具体代码如下：

```
uni.authorize({
  scope: 'scope.record',
  success: () => {
   console.log(‘获取权限成功’)
  },
  fail: (err) => {
          // 目前返回的错误信息
         // {
        //   "error": 4,
        //   "errorMessage": "无权调用该接口"
        // }
    console.log(err, '无法获取录音权限');
  },
});
```
**补充信息**
项目依赖的版本是 `2.0.2-alpha-3071220230324001`

**Comment by Yaob1990** [comment]
麻烦给一个 demo 示例

**Comment by monkeying-boy** [comment]
> 麻烦给一个 demo 示例

示例：
```vue
<template>
  <view>
    <button @tap="startRecord">
      开始录音
    </button>
    <button @tap="endRecord">
      停止录音
    </button>
    <button @tap="playVoice">
      播放录音
    </button>
  </view>
</template>
<script>

const innerAudioContext = uni.createInnerAudioContext();

innerAudioContext.autoplay = true;

export default {
  data() {
    return {
      text: 'uni-app',
      voicePath: '',
      recorderManager: {},
    };
  },
  mounted() {
    // 获取录音权限
    uni.authorize({
      scope: 'scope.record',
      success: () => {
        this.recorderManager = uni.getRecorderManager();
        this.recorderManager.onStop((res) => {
          console.log(`录音结束 ${JSON.stringify(res)}`);
          this.voicePath = res.tempFilePath;
        });
        this.recorderManager.onError((err) => {
          console.log(err, '录音发生错误');
        });
      },
      fail: (err) => {
        console.log('获取录音权限失败', err);
        uni.showToast({
          title: '获取录音权限失败',
          duration: 2000,
        });
      },
    });
  },
  methods: {
    startRecord() {
      console.log('开始录音');

      this.recorderManager.start();
    },
    endRecord() {
      console.log('录音结束');
      this.recorderManager.stop();
    },
    playVoice() {
      console.log('播放录音');

      if (this.voicePath) {
        innerAudioContext.src = this.voicePath;
        innerAudioContext.play();
      }
    },
  },
};
</script>
```
打包成支付宝小程序，在支付宝开发者工具中运行项目，控制台会提示 `{ "error": 4,"errorMessage": "无权调用该接口" }`

**Comment by Yaob1990** [comment]
> 
使用限制
• 基础库 [1.23.4](https://opendocs.alipay.com/mini/framework/lib) 或更高版本；支付宝客户端 10.1.87 或更高版本，若版本较低，建议采取 [兼容处理](https://opendocs.alipay.com/mini/framework/compatibility)。
• 小程序开发者工具（IDE）暂不支持调试此 API，请使用 [真机调试](https://opendocs.alipay.com/mini/ide/remote-debug) 功能在真机进行调试。
• 此 API 支持个人支付宝小程序、企业支付宝小程序使用。


需要真机调试

**Comment by Yaob1990** [comment]
> > 麻烦给一个 demo 示例
> 
> 示例：
> 
> ```
> <template>
>   <view>
>     <button @tap="startRecord">
>       开始录音
>     </button>
>     <button @tap="endRecord">
>       停止录音
>     </button>
>     <button @tap="playVoice">
>       播放录音
>     </button>
>   </view>
> </template>
> <script>
> 
> const innerAudioContext = uni.createInnerAudioContext();
> 
> innerAudioContext.autoplay = true;
> 
> export default {
>   data() {
>     return {
>       text: 'uni-app',
>       voicePath: '',
>       recorderManager: {},
>     };
>   },
>   mounted() {
>     // 获取录音权限
>     uni.authorize({
>       scope: 'scope.record',
>       success: () => {
>         this.recorderManager = uni.getRecorderManager();
>         this.recorderManager.onStop((res) => {
>           console.log(`录音结束 ${JSON.stringify(res)}`);
>           this.voicePath = res.tempFilePath;
>         });
>         this.recorderManager.onError((err) => {
>           console.log(err, '录音发生错误');
>         });
>       },
>       fail: (err) => {
>         console.log('获取录音权限失败', err);
>         uni.showToast({
>           title: '获取录音权限失败',
>           duration: 2000,
>         });
>       },
>     });
>   },
>   methods: {
>     startRecord() {
>       console.log('开始录音');
> 
>       this.recorderManager.start();
>     },
>     endRecord() {
>       console.log('录音结束');
>       this.recorderManager.stop();
>     },
>     playVoice() {
>       console.log('播放录音');
> 
>       if (this.voicePath) {
>         innerAudioContext.src = this.voicePath;
>         innerAudioContext.play();
>       }
>     },
>   },
> };
> </script>
> ```
> 
> 打包成支付宝小程序，在支付宝开发者工具中运行项目，控制台会提示 `{ "error": 4,"errorMessage": "无权调用该接口" }`

使用限制
• 基础库 [1.23.4](https://opendocs.alipay.com/mini/framework/lib) 或更高版本；支付宝客户端 10.1.87 或更高版本，若版本较低，建议采取 [兼容处理](https://opendocs.alipay.com/mini/framework/compatibility)。
• 小程序开发者工具（IDE）暂不支持调试此 API，请使用 [真机调试](https://opendocs.alipay.com/mini/ide/remote-debug) 功能在真机进行调试。
• 此 API 支持个人支付宝小程序、企业支付宝小程序使用。

需要真机调试

**Comment by monkeying-boy** [comment]
> > > 麻烦给一个 demo 示例
> > 
> > 
> > 示例：
> > ```
> > <template>
> >   <view>
> >     <button @tap="startRecord">
> >       开始录音
> >     </button>
> >     <button @tap="endRecord">
> >       停止录音
> >     </button>
> >     <button @tap="playVoice">
> >       播放录音
> >     </button>
> >   </view>
> > </template>
> > <script>
> > 
> > const innerAudioContext = uni.createInnerAudioContext();
> > 
> > innerAudioContext.autoplay = true;
> > 
> > export default {
> >   data() {
> >     return {
> >       text: 'uni-app',
> >       voicePath: '',
> >       recorderManager: {},
> >     };
> >   },
> >   mounted() {
> >     // 获取录音权限
> >     uni.authorize({
> >       scope: 'scope.record',
> >       success: () => {
> >         this.recorderManager = uni.getRecorderManager();
> >         this.recorderManager.onStop((res) => {
> >           console.log(`录音结束 ${JSON.stringify(res)}`);
> >           this.voicePath = res.tempFilePath;
> >         });
> >         this.recorderManager.onError((err) => {
> >           console.log(err, '录音发生错误');
> >         });
> >       },
> >       fail: (err) => {
> >         console.log('获取录音权限失败', err);
> >         uni.showToast({
> >           title: '获取录音权限失败',
> >           duration: 2000,
> >         });
> >       },
> >     });
> >   },
> >   methods: {
> >     startRecord() {
> >       console.log('开始录音');
> > 
> >       this.recorderManager.start();
> >     },
> >     endRecord() {
> >       console.log('录音结束');
> >       this.recorderManager.stop();
> >     },
> >     playVoice() {
> >       console.log('播放录音');
> > 
> >       if (this.voicePath) {
> >         innerAudioContext.src = this.voicePath;
> >         innerAudioContext.play();
> >       }
> >     },
> >   },
> > };
> > </script>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 打包成支付宝小程序，在支付宝开发者工具中运行项目，控制台会提示 `{ "error": 4,"errorMessage": "无权调用该接口" }`
> 
> 使用限制 • 基础库 [1.23.4](https://opendocs.alipay.com/mini/framework/lib) 或更高版本；支付宝客户端 10.1.87 或更高版本，若版本较低，建议采取 [兼容处理](https://opendocs.alipay.com/mini/framework/compatibility)。 • 小程序开发者工具（IDE）暂不支持调试此 API，请使用 [真机调试](https://opendocs.alipay.com/mini/ide/remote-debug) 功能在真机进行调试。 • 此 API 支持个人支付宝小程序、企业支付宝小程序使用。
> 
> 需要真机调试


在真机上也是不行的，ios 16.1.1 ，支付宝客户端 10.3.76,，打包成支付宝小程序后进入后调试工具显示：`{ "error": 4,"errorMessage": "permission denied","message":"permission denied" }`

**Comment by Yaob1990** [comment]
> 

这里大概率和 uniapp 没啥关系了。你可以原生试一下，看是不是有相关权限
