### ISSUE TITLE
安卓支付宝运行h5报错

### ISSUE THREAD

**Issue by github-ZH-cn** [dcloudio/uni-app#4289]
1.浏览器, 微信内置浏览器, 苹果支付宝 运行h5都没有问题 
2.安卓支付宝运行h5报错

![image](https://user-images.githubusercontent.com/67533362/233901871-8fc77af6-74b1-4fc8-b399-7c1e909d7ca3.png)

看不出什么原因报错

**Comment by Otto-J** [comment]
感谢反馈，可以提供精简过的复现工程，并说明操作步骤吗？目前不明确复现步骤、未提供复现工程
