### ISSUE TITLE
编译到支付宝小程序 日志文件占用报错

### ISSUE THREAD

**Issue by ranwawa** [dcloudio/uni-app#429]
### 业务背景
- 在pages.json里面修改东西后
- 重新启动npm run dev:mp-alipay
- 就会报下面的错
### 报错内容
![image](https://user-images.githubusercontent.com/30344590/58742877-2d184880-845a-11e9-91a8-495c6a91fb87.png)
### 我的尝试
- 关掉支付宝小程序开发者工具
- 重新编译
- 编译成功后再打开开发者工具

**Comment by dcloudhdx** [comment]
这是支付宝开发者工具问题，文件被锁定了
