### ISSUE TITLE
请问button等基础组件的ts类型定义的包是哪个

### ISSUE THREAD

**Issue by PineSongCN** [dcloudio/uni-app#4295]
**问题描述**
请问button等基础组件的ts类型定义的包是哪个

**复现步骤**
[复现问题的步骤]
1.  启动 vue3 cli 项目
2. 使用 <button /> 组件
3. 没有ts类型提示

**预期结果**
基础组件有类型提示

**实际结果**
![image](https://user-images.githubusercontent.com/39976617/234201978-e7ca2eba-0516-4d34-bd28-14d2fee26722.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 微信小程序
 - HBuilderX版本 
 - uni-app版本 3.0.0-3070920230324001
 - 设备信息 mac m2

**Comment by PineSongCN** [comment]
@zhetengbiji

**Comment by PineSongCN** [comment]
@StrivingRabbit

**Comment by zhetengbiji** [comment]
HBuilderX版本多少？

**Comment by PineSongCN** [comment]
> HBuilderX版本多少？

使用的cli，vscode

**Comment by zhetengbiji** [comment]
vscode的话，目前uni-app官方团队并未维护请使用新版HBuilderX。

已知社区部分开发者维护了vscode相关提示，但未关注其进度。

**Comment by PineSongCN** [comment]
> vscode的话，目前uni-app官方团队并未维护请使用新版HBuilderX。
> 
> 已知社区部分开发者维护了vscode相关提示，但未关注其进度。

所以有ts包，但是没放出来，只是给hbx用？

**Comment by zhetengbiji** [comment]
> > vscode的话，目前uni-app官方团队并未维护请使用新版HBuilderX。
> > 已知社区部分开发者维护了vscode相关提示，但未关注其进度。
> 
> 所以有ts包，但是没放出来，只是给hbx用？

HBuilderX的组件提示不使用“ts包”和vscode的旧插件通用，而和你现在使用的新插件不通用。

**Comment by PineSongCN** [comment]
> > > vscode的话，目前uni-app官方团队并未维护请使用新版HBuilderX。
> > > 已知社区部分开发者维护了vscode相关提示，但未关注其进度。
> > 
> > 
> > 所以有ts包，但是没放出来，只是给hbx用？
> 
> HBuilderX的组件提示不使用“ts包”和vscode的旧插件通用，而和你现在使用的新插件不通用。

谢谢

**Comment by apexg** [comment]
ts项目,要禁用TypeScript Vue Plugin (Volar) 这个插件,否则组件类型显示不正确
