### ISSUE TITLE
编译器版本(compilerVersion )信息未更新

### ISSUE THREAD

**Issue by VirensCn** [dcloudio/uni-app#4297]
导致APP端提示编译版本与基础环境版本不一致.  经常出现这种(特别是今年)
![image](https://user-images.githubusercontent.com/9736815/234463665-995dd007-cfc3-4ec5-a42b-9a5fdaad2563.png)

**Comment by zhetengbiji** [comment]
这个是测试版本，测试版本一般不处理 compilerVersion（因为无对应版本的基座对外开放），如果你并非期望使用测试版本，那么一直以来的升级方式可能有误。

针对普通开发者的版本管理方式：https://uniapp.dcloud.net.cn/quickstart-cli.html#cliversion
