### ISSUE TITLE
当一个vue文件即是页面，又当组件引用时，页面的样式文件会丢失

### ISSUE THREAD

**Issue by wangjieCode** [dcloudio/uni-app#4299]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/49115360/234485425-96fef67f-2707-4d91-bbee-143fddbbd249.png">

**复现步骤**
[复现问题的步骤]
1.  启动 npm run dev:mp-weixin

仓库地址 https://github.com/wangjieCode/uni-app-test

**系统信息:**
 - 发行平台: 微信小程序
 - uni-app版本 3.0.0-3070920230324001

**Comment by zhenyuWang** [comment]
该问题已修复，升级依赖到最新版本即可
