### ISSUE TITLE
期待解决的问题ing

### ISSUE THREAD

**Issue by alasai** [dcloudio/uni-app#43]
我最关心的问题：
1.怎么统一安卓推送
2.5+怎么丰富打开安卓和苹果的文件管理器，进行文件上传
3.安装第三方包太麻烦了，我如果用很多第三方包，都放在根目录下面的话会显得不整洁
4.赶紧支持增量更新吧
5.希望uni生态越来越好，apicloud虽然是抄袭hbuilder，但是他们的组件很多，希望uni也不用我们开发者再造轮子

**Comment by zhangdaren** [comment]
顶，支持！！！

**Comment by xiaoyucoding** [comment]
- 插件市场已有丰富的组件及模板，找组件和模板请前往 [uni-app 插件市场](https://ext.dcloud.net.cn/)
- UniPush 已上线，详见：[UniPush使用指南](https://ask.dcloud.net.cn/article/35622)
- wgt 包更新已支持：详见：[uni-app 资源在线更新](https://ask.dcloud.net.cn/article/35667)
- 原生功能的增强，可以通过离线打包自行扩展插件实现。如果觉得目录的规范不方便，可以单独发 issue 反馈交流。
