### ISSUE TITLE
基于uni-app开发的电商 App 小冠优选

### ISSUE THREAD

**Issue by mazhaoyou** [dcloudio/uni-app#430]
Android 下载地址：https://www.pgyer.com/e7m7
ios 目前还没正式上线不能下载
H5 访问链接（由于其他原因只支持移动设备访问）：https://wapceshi.paijl.com/test/index.html#/

[其它你认为有参考价值的信息]

**Comment by zhetengbiji** [comment]
案例请发布在 [uni-app项目案例征集](https://github.com/dcloudio/uni-app/issues/6)
另外提醒一下，H5版打开后无法正常使用
