### ISSUE TITLE
requirePlugin报错wx.__webpack_require_UNI_MP_PLUGIN__ is not a function

### ISSUE THREAD

**Issue by Gitby-Leo** [dcloudio/uni-app#4301]
**问题描述**

uniapp打包小程序插件，上传正常
原生微信小程序引入插件requirePlugin("xx")
报错wx.__webpack_require_UNI_MP_PLUGIN__ is not a function

**复现步骤**
```
module.exports = {
  version: "0.0.1",
  sayHello() {
    const a = "Hello";
    return a;
  }
};
```

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by focusLee** [comment]
问题依然存在

**Comment by idea-turtle** [comment]
同问 有解决方案吗？

**Comment by Gitby-Leo** [comment]
@StrivingRabbit 我看issue关闭了但问题还没修复
