### ISSUE TITLE
h5在微信中打开出现了问题

### ISSUE THREAD

**Issue by professionaltools** [dcloudio/uni-app#4304]
**问题描述**
在iOS微信中打开h5页面，页面显示正常，但是在控制台报了一个错误
"e.addEventListener is not a function. (In
'.addEventListener("change", (e=>
{UniServiceJSBridgeS1 .emit(ON_THEME_CHANGE, {theme:e.matches?"dark"."light")]))', 'e.addEventListener' is undefined)"

**复现步骤**

[或者可以直接贴源代码]
package.json依赖如下：
"dependencies": {
    "@dcloudio/uni-app": "3.0.0-alpha-3061220221207001",
    "@dcloudio/uni-app-plus": "3.0.0-alpha-3061220221207001",
    "@dcloudio/uni-components": "3.0.0-alpha-3061220221207001",
    "@dcloudio/uni-h5": "3.0.0-alpha-3061220221207001",
    "@dcloudio/uni-mp-alipay": "3.0.0-alpha-3061220221207001",
    "@dcloudio/uni-mp-baidu": "3.0.0-alpha-3061220221207001",
    "@dcloudio/uni-mp-kuaishou": "3.0.0-alpha-3061220221207001",
    "@dcloudio/uni-mp-lark": "3.0.0-alpha-3061220221207001",
    "@dcloudio/uni-mp-qq": "3.0.0-alpha-3061220221207001",
    "@dcloudio/uni-mp-toutiao": "3.0.0-alpha-3061220221207001",
    "@dcloudio/uni-mp-weixin": "3.0.0-alpha-3061220221207001",
    "@dcloudio/uni-quickapp-webview": "3.0.0-alpha-3061220221207001",
    "axios": "^1.2.1",
    "clipboard": "^2.0.11",
    "crypto-js": "^4.1.1",
    "dayjs": "^1.11.7",
    "html2canvas": "1.0.0",
    "js-cookie": "^3.0.1",
    "pinia": "^2.0.28",
    "qs": "^6.9.4",
    "uview-plus": "^3.1.19",
    "vue": "^3.2.45",
    "vue-i18n": "^9.2.2",
    "vue-monoplasty-slide-verify": "^1.3.1",
    "vue-qr": "^4.0.9"
  },
  "devDependencies": {
    "@dcloudio/types": "^3.2.3",
    "@dcloudio/uni-automator": "3.0.0-alpha-3061220221207001",
    "@dcloudio/uni-cli-shared": "3.0.0-alpha-3061220221207001",
    "@dcloudio/uni-stacktracey": "3.0.0-alpha-3061220221207001",
    "@dcloudio/vite-plugin-uni": "3.0.0-alpha-3061220221207001",
    "@types/crypto-js": "^4.1.1",
    "@types/js-cookie": "^3.0.2",
    "copy-dir": "^1.3.0",
    "rollup-plugin-copy": "^3.4.0",
    "sass": "^1.56.2",
    "sass-loader": "^10.4.1",
    "typescript": "^4.8.4",
    "vconsole": "^3.15.0",
    "vite": "^3.2.4"
  }
**预期结果**

**实际结果**

**系统信息:**
 - 发行平台: H5
 - 操作系统 [如 iOS 13.6.1]
 - 设备信息 [如 iPhone11]

**补充信息**

**Comment by StrivingRabbit** [comment]
升级至 [3.0.0-alpha-3080120230428001](https://www.npmjs.com/package/@dcloudio/uni-app/v/3.0.0-alpha-3080120230428001) 试试
