### ISSUE TITLE
编译到支付宝小程序 引用node_modules中的uni扩展组件无法打包上传

### ISSUE THREAD

**Issue by ranwawa** [dcloudio/uni-app#431]
### 源代码
![image](https://user-images.githubusercontent.com/30344590/58745976-5f8e6980-848b-11e9-9736-e93ab8c8b6e9.png)

### 报错内容
![image](https://user-images.githubusercontent.com/30344590/58745979-6ae19500-848b-11e9-89c1-1237b9b1ab50.png)
### 期望
- 直接引用node_modules里面的uni扩展组件
- 可以直接上传到支付宝小程序
### 我的尝试
- 把所有组件全部复制到components目录下
- 再引入使用

**Comment by zhetengbiji** [comment]
已修复，更新 HBuilderX 到 2.0.2 alpha
