### ISSUE TITLE
子组件使用input传入type时在H5端样式丢失

### ISSUE THREAD

**Issue by yanusosu** [dcloudio/uni-app#433]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
自定义组件封装了input，传入type并且绑定v-model时，在chrome浏览器中样式丢失，微信中没有问题
[或者可以直接贴源代码]
子组件代码：
```
    <input
        v-model="currentValue"
        :type="type"
  
      />

... 
 props: {
    value: {
      type: String | Number,
      default: ""
    },
  
    type: {
      type: String,
      default: "text"
    },
  
```

调用代码：
```
<v-input
        label="test"
         type="text"
        v-model="test"
      ></v-input>
```
**预期结果**
chrome浏览器中应该有样式

**实际结果**
chrome浏览器中：
![TIM截图20190602173546](https://user-images.githubusercontent.com/17284792/58759456-dfd0cf80-855c-11e9-89f9-09e482071871.png)

微信开发者工具中：
![TIM截图20190602173446](https://user-images.githubusercontent.com/17284792/58759451-c7f94b80-855c-11e9-8a40-3c9ae59e6198.png)

**系统信息:**
 - 发行平台: 微信小程序、H5平台
 - uni-app版本 
 System:
    OS: Windows 10
    CPU: (8) x64 Intel(R) Core(TM) i7-4790 CPU @ 3.60GHz
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.13.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.17763.1.0
  npmPackages:
    @dcloudio/uni-app-plus: * => 0.0.240
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: * => 0.2.956
    @dcloudio/uni-h5: * => 0.5.5
    @dcloudio/uni-mp-alipay: * => 0.0.814
    @dcloudio/uni-mp-baidu: * => 0.0.840
    @dcloudio/uni-mp-toutiao: * => 0.0.338
    @dcloudio/uni-mp-weixin: * => 0.0.960
    @dcloudio/uni-template-compiler: * => 0.9.175
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 0.9.517
    @dcloudio/vue-cli-plugin-uni: latest => 0.9.472
    @dcloudio/webpack-uni-mp-loader: * => 0.3.628
    @dcloudio/webpack-uni-pages-loader: * => 0.2.838
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.8.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.8.0
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-service: ^3.8.0 => 3.8.0
    @vue/cli-shared-utils:  3.8.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-router:  3.0.1
    vue-style-loader:  3.1.2 (3.1.2)
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
    weex-vue-loader: ^0.7.0 => 0.7.0
  npmGlobalPackages:
    @vue/cli: Not Found
 - 设备信息 微信开发者工具1.0.2，chrome74

**补充信息**
传入type和v-model冲突？

**Comment by zhetengbiji** [comment]
请提供一个较完整的复现问题的demo

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启

**Comment by feidegenggao** [comment]
我也遇到了同样的问题。请问有解决吗？

**Comment by yyman001** [comment]
问题没解决就关闭,6666,官方神操作

**Comment by zhetengbiji** [comment]
> 问题没解决就关闭,6666,官方神操作

麻烦看下文档：https://uniapp.dcloud.io/component/input
