### ISSUE TITLE
微信平台小程序mergeVirtualHostAttributes不生效

### ISSUE THREAD

**Issue by semdy** [dcloudio/uni-app#4336]
在manifest.json中配置mergeVirtualHostAttributes: true, 在微信小程序平台不生效，组件外部传入的class没有挂到组件根节点上，支付宝平台可以。除非明确地在组件中增加options: { virtualHost: true }。

**Comment by martianmartian** [comment]
微信小程序 及时 组件设置了 virtualHost:true， 也不能开启merge
