### ISSUE TITLE
如何使用uni.$emit函数？

### ISSUE THREAD

**Issue by JerrySir** [dcloudio/uni-app#434]
**问题描述**
我看到有一次提交：
https://github.com/dcloudio/uni-app/commit/e5285d29bbc37ffa521df1c11abc37d085c136cc
并且官方文档中也提到：
https://uniapp.dcloud.io/api/window/communication?id=once
可是我如何用呢？

报错内容：

uni.$once is not a function; [Component] Event Handler Error @ components/change-address#handleEvent
TypeError: uni.$once is not a function

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by fxy060608** [comment]
下载使用最新的 Alpha 版本 HBuilderX http://www.dcloud.io/hbuilderx.html

**Comment by aiplat** [comment]
正常使用

**Comment by JerrySir** [comment]
@fxy060608 非常感谢
