### ISSUE TITLE
vue3版本，支付宝小程序，?? null判断符使用会报错

### ISSUE THREAD

**Issue by Dizzy-zz** [dcloudio/uni-app#4349]
**问题描述**
const obj = {}
console.log(obj?.value ?? '')
这种用法会报错
<img width="351" alt="image" src="https://github.com/dcloudio/uni-app/assets/26196307/ad08f683-260b-44ff-9b69-dc0c88f483cf">
在vite版本为4.1.4的时候会报错，vite版本为3的时候不会报错

**预期结果**
不报错

**系统信息:**
 - 发行平台: 支付宝小程序
 - 操作系统 MacOs13.4
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 3.0.0-3071120230427001

**补充信息**
[可选]
vite4版本的兼容性问题

**Comment by emeiziying** [comment]
```
export default defineConfig({
  build: {
    target: 'es6',
  },
  plugins: [Uni()],
});
```
