### ISSUE TITLE
uniapp 支付宝平台编译运行报错

### ISSUE THREAD

**Issue by afsdfsdf232** [dcloudio/uni-app#4354]
"dependencies": {
        "@commitlint/cli": "12.1.4",
        "@commitlint/config-conventional": "^17.6.3",
        "@dcloudio/uni-app": "3.0.0-3080320230526001",
        "@dcloudio/uni-app-plus": "3.0.0-3080320230526001",
        "@dcloudio/uni-components": "3.0.0-3080320230526001",
        "@dcloudio/uni-h5": "3.0.0-3080320230526001",
        "@dcloudio/uni-mp-alipay": "3.0.0-3080320230526001",
        "@dcloudio/uni-mp-baidu": "3.0.0-3080320230526001",
        "@dcloudio/uni-mp-jd": "3.0.0-3080320230526001",
        "@dcloudio/uni-mp-kuaishou": "3.0.0-3080320230526001",
        "@dcloudio/uni-mp-lark": "3.0.0-3080320230526001",
        "@dcloudio/uni-mp-qq": "3.0.0-3080320230526001",
        "@dcloudio/uni-mp-toutiao": "3.0.0-3080320230526001",
        "@dcloudio/uni-mp-weixin": "3.0.0-3080320230526001",
        "@dcloudio/uni-quickapp-webview": "3.0.0-3080320230526001",
        "@dcloudio/uni-ui": "^1.4.27",
        "conventional-changelog-cli": "^2.2.2",
        "cz-conventional-changelog": "^3.3.0",
        "husky": "^8.0.3",
        "pinia": "^2.0.35",
        "sa-sdk-miniprogram": "^1.19.2",
        "vue": "^3.2.45",
        "vue-i18n": "^9.1.9"
    },
    "devDependencies": {
        "@dcloudio/types": "^3.3.2",
        "@dcloudio/uni-automator": "3.0.0-3080320230526001",
        "@dcloudio/uni-cli-shared": "3.0.0-3080320230526001",
        "@dcloudio/uni-stacktracey": "3.0.0-3080320230526001",
        "@dcloudio/vite-plugin-uni": "3.0.0-3080320230526001",
        "@types/node": "^18.15.13",
        "@typescript-eslint/eslint-plugin": "^5.59.0",
        "@typescript-eslint/parser": "^5.59.0",
        "@vue/eslint-config-prettier": "6.*",
        "@vue/eslint-config-typescript": "^11.0.2",
        "@vue/tsconfig": "^0.1.3",
        "@vuedx/typescript-plugin-vue": "^0.7.6",
        "commitlint": "^17.6.3",
        "cz-customizable": "^6.3.0",
        "eslint": "^8.38.0",
        "eslint-plugin-prettier": "^4.2.1",
        "eslint-plugin-vue": "^9.11.0",
        "prettier": "^2.8.7",
        "sass": "^1.62.1",
        "sass-loader": "10.4.1",
        "typescript": "^4.9.4",
        "vite": "4.1.4",
        "vue-tsc": "^1.0.24"
    },

![image](https://github.com/dcloudio/uni-app/assets/37952670/f69453d3-8ebf-46f2-820e-297c771e80aa)

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Otto-J** [comment]
如果还有这个问题，可以补充一些具体的代码。未能复现，可能已经解决了。
