### ISSUE TITLE
vite+vue3项目，小程序编译不会触发vite的handleHotUpdate钩子

### ISSUE THREAD

**Issue by Moonofweisheng** [dcloudio/uni-app#4357]
**问题描述**
vite+vue3项目，小程序编译不会触发vite的handleHotUpdate钩子

**补充信息**
期望是在每次pages.json更新时读取pages.json并注入全局变量

**Comment by Allen-1998** [comment]
遇到了相同的问题，可以使用 [chokidar](https://github.com/paulmillr/chokidar) 来替代 handleHotUpdate,但不清楚是否有更好的解决方案

**Comment by Lgowen** [comment]
> 遇到了相同的问题，可以使用 [chokidar](https://github.com/paulmillr/chokidar) 来替代 handleHotUpdate,但不清楚是否有更好的解决方案

之前用的大佬的脚手架，没想到在这里又看见了大佬（有什么更好的解决方案了嘛）
