### ISSUE TITLE
使用uni.chooseImage 设置压缩 得到的压缩图片 长宽比例颠倒

### ISSUE THREAD

**Issue by zlm919** [dcloudio/uni-app#437]
**问题描述**
uni.chooseImage 
sizeType设为compressed 时，图片的比例 长宽比例 颠倒了

**复现步骤**
1.  选择 图片
2. 上传
3. 服务器后台查看图片比例

**预期结果**
长宽比例与原图一样

**实际结果**
原图
![upload_21ce9425353d0ffdaf377704bee83ebd](https://user-images.githubusercontent.com/14146110/58945702-f3777280-87b6-11e9-80ae-ab9530f99788.jpg)

压缩后图

![upload_eb2a5b15f8883d78293fc7657f44c669](https://user-images.githubusercontent.com/14146110/58945717-f83c2680-87b6-11e9-901d-17f79eadf4af.jpg)

图片信息
![A08278EFA037B033076A17A195648D72](https://user-images.githubusercontent.com/14146110/58945860-40f3df80-87b7-11e9-820a-43cbbf70c685.jpg)

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 Android 8.0  
 - HBuilderX版本 1.9.9
 - 设备信息  小米 MIX2 系统MIUI10.3

**Comment by dcloudhdx** [comment]
已确认 Bug，会尽快修复

**Comment by dcloudhdx** [comment]
HBuilderX 2.2.5.20190907-alpha 已修复
