### ISSUE TITLE
reuqest delete请求data参数怎么转换成query参数

### ISSUE THREAD

**Issue by jianchengwang** [dcloudio/uni-app#4370]
**新功能描述**
reuqest delete请求data参数不知道怎么转换成query参数

**现状及问题**
当前有很多内置的处理，比如get请求data会转成query参数，delete又不会，

**尝试方案**
目前只能在url后面自己拼接参数，参数多就很麻烦，欢迎给其他好的建议

**补充信息**
建议类似axios有一个param跟data参数，至少不会有歧义也比较灵活

**Comment by zhetengbiji** [comment]
request是沿用的微信小程序的规范，目前来看其定位类似于xhr、fetch，用于提供基础的功能。对于包装param更适合真的配合axios等库来处理。
