### ISSUE TITLE
编译到H5平台在微信打开后编译出的样式大了一倍

### ISSUE THREAD

**Issue by xheartx** [dcloudio/uni-app#438]
**问题描述**
编译到H5平台在微信端打开后 编译出的样式大了一倍，并且但是刷新下就正常了，其他浏览器正常

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
正常显示
![](http://ww1.sinaimg.cn/large/006ohsoyly1g3r9g3o2jyj30ku112gmy.jpg)
![](http://ww1.sinaimg.cn/large/006ohsoyly1g3rdqmk3h3j30d20otdjj.jpg)

**实际结果**
![](http://ww1.sinaimg.cn/large/006ohsoyly1g3r9g3p6kgj30ku112myq.jpg)
![](http://ww1.sinaimg.cn/large/006ohsoyly1g3rdqmmfc7j30d20otjv0.jpg)

**系统信息:**
 - 发行平台: [H5平台]
 - 操作系统 [如 iOS 12.2],
 - HBuilderX版本 [1.9.9.20190522]
 - 设备信息 [iPhone6s]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-3320M CPU @ 2.60GHz
  Binaries:
    Node: 10.14.2 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.10.1 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @dcloudio/uni-app-plus: * => 0.0.236
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: * => 0.2.951
    @dcloudio/uni-h5: * => 0.5.3
    @dcloudio/uni-mp-alipay: * => 0.0.808
    @dcloudio/uni-mp-baidu: * => 0.0.834
    @dcloudio/uni-mp-toutiao: * => 0.0.334
    @dcloudio/uni-mp-weixin: * => 0.0.956
    @dcloudio/uni-template-compiler: * => 0.9.174
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 0.9.512
    @dcloudio/vue-cli-plugin-uni: latest => 0.9.466
    @dcloudio/webpack-uni-mp-loader: * => 0.3.625
    @dcloudio/webpack-uni-pages-loader: * => 0.2.830
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.7.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.7.0
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-service: ^3.7.0 => 3.7.0
    @vue/cli-shared-utils:  3.7.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-router:  3.0.1
    vue-style-loader:  3.1.2 (3.1.2)
    vue-template-compiler: ^2.5.21 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
    weex-vue-loader: ^0.7.0 => 0.7.0

upx 编译到px 的时候，是根据getSystemInfoSync中的windowWidth来计算尺寸的，但是windowWidth第一次进页面是750，导致页面中编译出的样式大了一倍，刷新后windowWidth就是375，然后样式就正常了

**Comment by zhetengbiji** [comment]
未复现该问题
麻烦你使用新版HBuilderX运行试试；以及，运行到其他设备试试
看问题是否仍然能出现
