### ISSUE TITLE
欢迎使用跨端组件库press-ui

### ISSUE THREAD

**Issue by novlan1** [dcloudio/uni-app#4380]
地址：https://github.com/novlan1/press-ui

支持h5、微信小程序、qq小程序

api与vant基本一致

**Comment by novlan1** [comment]
<img src="https://camo.githubusercontent.com/3943355766d088ba9f61ac818031334b31c12f80cce97092baee6f561e68b6d2/68747470733a2f2f6d696b652d313235353335353333382e636f732e61702d6775616e677a686f752e6d7971636c6f75642e636f6d2f70726573732f7172636f64652f70726573732d75692d64656d6f2d7172636f64652d332e706e67" />

**Comment by yang1206** [comment]
支持vue3吗
