### ISSUE TITLE
【报Bug】 vue3 头条小程序 provide 无效 包括抖音/飞书小程序

### ISSUE THREAD

**Issue by SilurianYang** [dcloudio/uni-app#4386]
**问题描述**
头条小程序 无法为后代注入值 其他小程序及H5一切正常

**复现步骤**
使用 `provide` 在同一组件中无限往下一代注入值 下一代无法拿到注入的值
```js
//com.vue
<template>
	<view>
		<div>
			depth：{{ depth }}
		</div>
		<com1></com1>
	</view>
</template>

<script>
	import com1 from './com1.vue'
	import {computed} from 'vue'
	export default {
		components:{
			com1
		},
		inject:{
			depth:{
				from : 'depthValue',
				default:1
			}
		},
		provide(){
			return {
				depthValue:computed(() => this.depth + 1)
			}
		},
		methods: {
			
		}
	}
</script>


// com1.vue
<template>
	<view>
		depth：{{ depth }}
		
		<div v-if="depth<5">
			<ComChild/>
		</div>
	</view>
</template>

<script>
	import {computed} from 'vue'
	export default {
		inject:{
			depth:{
				from : 'depthValue',
				default:1
			}
		},
		provide(){
			return {
				depthValue:computed(() => this.depth + 1)
			}
		},
		methods: {
			
		}
	}
</script>

```

**预期结果**
像其他端一样能正确拿到
![3](https://github.com/dcloudio/uni-app/assets/31280665/97769a61-faca-4fc0-8fd6-f3512afe8525)
![4](https://github.com/dcloudio/uni-app/assets/31280665/7cdcda85-d01f-408e-b428-b8b02523397e)
![5](https://github.com/dcloudio/uni-app/assets/31280665/8649f8aa-cb80-457b-867d-94be6be8e253)

**实际结果**
![1](https://github.com/dcloudio/uni-app/assets/31280665/9dddc876-2021-47e0-b857-ae5d7e41919d)
![2](https://github.com/dcloudio/uni-app/assets/31280665/9f4ada36-0591-4313-8848-a934b45743ca)

**系统信息:**
 - 发行平台: 头条小程序
 - 操作系统: window 开发工具
 - HBuilderX版本  3.7.11.20230427 正式版

**补充信息**
解压该demo到HBuilderX 直接运行到头条小程序查看结果
[douying-provide-invalid.zip](https://github.com/dcloudio/uni-app/files/11757975/douying-provide-invalid.zip)

**Comment by SilurianYang** [comment]
@zhetengbiji

**Comment by GrapevineLin** [comment]
vue2 也同样存在这个问题

**Comment by SilurianYang** [comment]
有可运行的demo都没人鸟，几个月了 @hbcui1984 @zencodex

**Comment by yurj26** [comment]
感谢反馈，这边排查下。

**Comment by yurj26** [comment]
临时解决方案：替换 [文件](https://github.com/dcloudio/uni-app/blob/next/packages/uni-mp-toutiao/dist/uni.mp.esm.js) 到 `HBuilderX根目录/plugins/uniapp-cli-vite/node_modules/@dcloudio/uni-mp-toutiao/dist`

**Comment by yurj26** [comment]
> @yurj26 老师什么时候更新 更新后麻烦在这里通知下 谢谢

HBuilderX 3.93.2023101913-alpha 已修复

**Comment by SilurianYang** [comment]
> > @yurj26 老师什么时候更新 更新后麻烦在这里通知下 谢谢
> 
> HBuilderX 3.93.2023101913-alpha 已修复

🤟🤟🤟🤟🤟👍👍👍

**Comment by zencodex** [comment]
> 有可运行的demo都没人鸟，几个月了

@SilurianYang  提示下，我不是官方人员哦。或许你看过 uapp，误以为我是官方的了吧，uapp 是我个人维护的项目，和官方没关系 🙂

**Comment by SilurianYang** [comment]
> > 有可运行的demo都没人鸟，几个月了
> 
> @SilurianYang 提示下，我不是官方人员哦。或许你看过 uapp，误以为我是官方的了吧，uapp 是我个人维护的项目，和官方没关系 🙂

之前艾特错了 不好意思

**Comment by RichOvernigh** [comment]
问下现在可用了吗， 我uni-app使用 最新版的 3.0.0-alpha-4000020240127001  
在optionsApi 中provide/inject 可以生效，
setup中还是不能用

**Comment by wen-gang** [comment]
现在又不行了？
