### ISSUE TITLE
We can find the malware in the dev branch, please help to check and fix

### ISSUE THREAD

**Issue by mendickmorningstar** [dcloudio/uni-app#4388]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
我们使用VirusTotal进行扫描的时候，发现存在Malware，请尽快修复，并确认是不是供应链攻击。
https://www.virustotal.com/gui/file/a1741dcbdc7dcbfefc0f9f298c4f5baf5a305695aacff933fe28e75b516bcc55/detection

**复现步骤**
[复现问题的步骤]
1.  通过压缩包的方式下载最新的源代码
https://github.com/dcloudio/uni-app/archive/refs/heads/dev.zip
2. 打开virustotal，然后上传源代码包，进行扫描
3. VirusTotal发现恶意代码。

[或者可以直接贴源代码]

**预期结果**
没有任何恶意代码。

**实际结果**
有恶意代码
https://www.virustotal.com/gui/file/a1741dcbdc7dcbfefc0f9f298c4f5baf5a305695aacff933fe28e75b516bcc55/detection
ClamAV
Txt.Malware.Agent-9913425-0

**补充信息**
[可选]
可能存在供应链攻击。

**Comment by zhetengbiji** [comment]
找到一个类似的反馈：https://ask.dcloud.net.cn/question/148550

**Comment by SilurianYang** [comment]
@zhetengbiji  麻烦看看这个问题 https://github.com/dcloudio/uni-app/issues/4386

**Comment by zhetengbiji** [comment]
关联问题：https://ask.dcloud.net.cn/question/184104
