### ISSUE TITLE
cid unmatched [object Object] at view.umd.min.js

### ISSUE THREAD

**Issue by imaxing** [dcloudio/uni-app#4395]
**问题描述**
在使用renderjs渲染内容时, 如果调用了new Vue, 会报错

**复现步骤**
[复现问题的步骤]
1.  git clone https://github.com/imaxing/uniapp-leaflet-example.git
2. 运行到app端
3. 查看控制台

[或者可以直接贴源代码]

**预期结果**
不报错

**实际结果**
![image](https://github.com/dcloudio/uni-app/assets/26427785/a0c7db3f-db5b-4c14-bafc-97bd495a8da9)
![image](https://github.com/dcloudio/uni-app/assets/26427785/cac35f35-f992-49e1-922e-af4e3d6947a8)

**系统信息:**
 System:
    OS: macOS 13.0
    CPU: (10) arm64 Apple M1 Pro
  Binaries:
    Node: 16.17.0 - ~/.nvm/versions/node/v16.17.0/bin/node
    Yarn: 1.22.19 - /opt/homebrew/bin/yarn
    npm: 8.15.0 - ~/.nvm/versions/node/v16.17.0/bin/npm
  Browsers:
    Chrome: 114.0.5735.133
    Firefox: Not Found
    Safari: 16.1
  npmPackages:
    @dcloudio/types: 2.6.12 => 2.6.12
    @dcloudio/uni-app: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-app-plus: 2.0.2-3080420230530001 => 2.0.2-3080420230530001
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-automator: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-cli-i18n: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-cli-shared: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-h5: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-helper-json: * => 1.0.13
    @dcloudio/uni-i18n: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-migration: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-mp-360: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-mp-alipay: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-mp-baidu: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-mp-jd: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-mp-kuaishou: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-mp-lark: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-mp-qq: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-mp-toutiao: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-mp-vue: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-mp-weixin: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-mp-xhs: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-quickapp-native: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-quickapp-webview: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-stacktracey: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/uni-stat: 2.0.2-3071120230427001 => 2.0.2-3071120230427001 (2.0.2-3080320230526001)
    @dcloudio/uni-template-compiler: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/vue-cli-plugin-hbuilderx: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/vue-cli-plugin-uni: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/vue-cli-plugin-uni-optimize: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/webpack-uni-mp-loader: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: 2.0.2-3071120230427001 => 2.0.2-3071120230427001
    @hap-toolkit/dsl-vue:  0.6.13
    @vue/babel-helper-vue-jsx-merge-props:  1.4.0
    @vue/babel-helper-vue-transform-on:  1.0.2
    @vue/babel-plugin-jsx:  1.1.1
    @vue/babel-plugin-transform-vue-jsx:  1.4.0
    @vue/babel-preset-app:  4.5.19
    @vue/babel-preset-jsx:  1.4.0
    @vue/babel-sugar-composition-api-inject-h:  1.4.0
    @vue/babel-sugar-composition-api-render-instance:  1.4.0
    @vue/babel-sugar-functional-vue:  1.4.0
    @vue/babel-sugar-inject-h:  1.4.0
    @vue/babel-sugar-v-model:  1.4.0
    @vue/babel-sugar-v-on:  1.4.0
    @vue/cli-overlay:  4.5.19
    @vue/cli-plugin-babel: ~4.5.15 => 4.5.19
    @vue/cli-plugin-router:  4.5.19
    @vue/cli-plugin-typescript: ~4.5.15 => 4.5.19
    @vue/cli-plugin-vuex:  4.5.19
    @vue/cli-service: ~4.5.15 => 4.5.19
    @vue/cli-shared-utils:  4.5.19
    @vue/compiler-sfc:  2.7.14
    @vue/component-compiler-utils:  3.3.0 (3.3.0)
    @vue/composition-api:  1.7.0
    @vue/devtools-api:  6.0.0-beta.15
    @vue/preload-webpack-plugin:  1.1.2
    @vue/shared: ^3.0.0 => 3.3.4
    @vue/web-component-wrapper:  1.3.0
    find-vue-child:  1.0.1
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.11 => 2.7.14
    vue-hot-reload-api:  2.3.4
    vue-i18n: 7.3.2 => 7.3.2
    vue-loader:  15.10.1 (16.8.3, 15.10.1)
    vue-router:  3.0.1
    vue-style-loader:  4.1.3 (4.1.3)
    vue-template-compiler: 2.6.11 => 2.6.11 (2.7.14)
    vue-template-es2015-compiler:  1.9.1
    vue3:  1.0.0
    vuex: ^3.2.0 => 3.6.2 (3.6.2)
  npmGlobalPackages:
    @vue/cli: 5.0.8

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by imaxing** [comment]
@StrivingRabbit 大佬, 这个问题有空瞄一眼 :)

**Comment by zhetengbiji** [comment]
渲染层的Vue是修改过的，不是你认知中Vue，而且后续渲染层可能会不再包含Vue。

**Comment by zhetengbiji** [comment]
可能关错了，重新打开。
