### ISSUE TITLE
ReferenceError: pleaseSetTranspileDependencies is not defined

### ISSUE THREAD

**Issue by MenchW** [dcloudio/uni-app#4397]
**问题描述**
[问题描述：使用官网提供的vue2脚手架命令安装默认模板同时安装了uview@2.0.31版本，然后使用npm run build命令打包出现了错误：ReferenceError: pleaseSetTranspileDependencies is not defined

![image](https://github.com/dcloudio/uni-app/assets/66238158/b4911b11-0ee5-4e03-b305-8c86e5333f4a)

**预期结果**
正常使用

**实际结果**
控制台报错 页面白屏

**补充信息**
将uview注释掉再执行npm run  build打包部署运行正常

**Comment by lugt** [comment]
在 vue.config.js 中加入

```js
// vue.config.js，如没有此文件则手动创建
module.exports = {
    transpileDependencies: ['uview-ui']
}
```

**Comment by MenchW** [comment]
> 在 vue.config.js 中加入
> 
> ```js
> // vue.config.js，如没有此文件则手动创建
> module.exports = {
>     transpileDependencies: ['uview-ui']
> }
> ```

谢谢,是我没仔细看文档
