### ISSUE TITLE
业务开发使用 rpx，但内置组件以及 uni-ui 的单位都是 px，不会有冲突吗？

### ISSUE THREAD

**Issue by yutucc** [dcloudio/uni-app#4399]
移动端开发，为了实现自适应，都是直接使用 rpx

但是，对于 uniapp的内置组件以及 uni-ui 的组件来说，其单位都是 px

如果保持这样的话，不同屏幕尺寸，业务代码的字体大小会自适应，但是框架的字体大小保持不变

请问这样是合理的么？刚接触 uniapp，对这点比较好奇，不知道有木有更好的解决方案？

**Comment by zhetengbiji** [comment]
使用rpx基于宽度进行缩放适配，直接使用px是基于devicePixelRatio进行缩放适配。不同的方案单独使用或者组合使用其实各有优劣，在互联网上有很多相关的探索分析和讨论，这里暂时不展开解释。比如单一按照宽度来缩放的一个典型缺陷就是同一个设备横屏和竖屏显示的状态其中一个不符合预期的概率很大。

uni-ui 之前是采用的rpx，现在单独使用px进行适配是基于单一的devicePixelRatio缩放方式，后续也可能采用组合方案来进行改进。

**Comment by yutucc** [comment]
可以理解，就单纯移动端而言（不考虑平板）的情况下，全部固定使用 px，如果是基于devicePixelRatio进行缩放适配的话，不同大小的屏幕下，字体的大小不会有太出格的表现

但有个场景想请教一下：
1. 750 的设计稿
2. 设计稿上有一个 750*100 的按钮（在设计稿上的含义就是宽满屏）
3. 如果对于这个按钮，设置 width: 750px; 的话，在大小不同的屏幕下岂不是会很出格？

@zhetengbiji 想请教一下，针对以上场景，目前官方的建议方案是？

**Comment by zhetengbiji** [comment]
> 可以理解，就单纯移动端而言（不考虑平板）的情况下，全部固定使用 px，如果是基于devicePixelRatio进行缩放适配的话，不同大小的屏幕下，字体的大小不会有太出格的表现
> 
> 但有个场景想请教一下：
> 
> 1. 750 的设计稿
> 2. 设计稿上有一个 750*100 的按钮（在设计稿上的含义就是宽满屏）
> 3. 如果对于这个按钮，设置 width: 750px; 的话，在大小不同的屏幕下岂不是会很出格？
> 
> @zhetengbiji 想请教一下，针对以上场景，目前官方的建议方案是？

如果不考虑nvue（weex），目前推荐的是：以devicePixelRatio为基础缩放方式配合百分比媒体查询等组合方案

**Comment by zhetengbiji** [comment]
具体怎能组合最优，这里暂时不展开详细的讨论，因为互联网上很多优秀的人已经做了各种实践分析和分享。建议都看一下，然后根据自己具体的业务情况进行实践。
