### ISSUE TITLE
TypeError: Cannot read property 'for' of undefined 这是个什么错误呢？

### ISSUE THREAD

**Issue by f1084** [dcloudio/uni-app#44]
`模块编译失败：TypeError: Cannot read property 'for' of undefined
14:54:43.057     at fixDefaultIterator (C:\Users\Administrator\Desktop\HBuilderX.0.1.47.20180823-alpha.full\plugins\uniapp\lib\mpvue-template-compiler\build.js:4234:24)
14:54:43.068     at mark (C:\Users\Administrator\Desktop\HBuilderX.0.1.47.20180823-alpha.full\plugins\uniapp\lib\mpvue-template-compiler\build.js:4266:5)
14:54:43.068     at markComponent (C:\Users\Administrator\Desktop\HBuilderX.0.1.47.20180823-alpha.full\plugins\uniapp\lib\mpvue-template-compiler\build.js:4333:5)
14:54:43.078     at baseCompile (C:\Users\Administrator\Desktop\HBuilderX.0.1.47.20180823-alpha.full\plugins\uniapp\lib\mpvue-template-compiler\build.js:4349:15)
14:54:43.090     at compile (C:\Users\Administrator\Desktop\HBuilderX.0.1.47.20180823-alpha.full\plugins\uniapp\lib\mpvue-template-compiler\build.js:4046:28)
14:54:43.101     at Object.module.exports (C:\Users\Administrator\Desktop\HBuilderX.0.1.47.20180823-alpha.full\plugins\uniapp\lib\mpvue-loader\lib\template-compiler\index.js:43:18)`

**Comment by f1084** [comment]
我知道这个是什么原因了。问题出在页面组件内容为空。即template下没有任何内容，就会报这种错

**Comment by hbcui1984** [comment]
目前的编译器，需要template节点下默认有一个view节点。
