### ISSUE TITLE
想要调试uniapp源码，发现cypress太难安装了，有什么好办法吗

### ISSUE THREAD

**Issue by social-uni** [dcloudio/uni-app#4403]
想要调试uniapp源码，发现cypress太难安装了，有什么好办法吗

clone uniapp， npm i，安不上cypress，有什么好办法嘛 太难了，你们官方都怎么弄的呀

**Comment by zhetengbiji** [comment]
试试国内源或者全局番茄

**Comment by social-uni** [comment]
> 试试国内源或者全局番茄，其他注意事项参考 .github/CONTRIBUTING.md

老哥，可以申请加个v嘛，我有挺多问题想问，谢谢

我又遇到一个问题， uniapp 子包可以单独打包吗， 我看  只有个run all build所有项目，太慢了，我想单独打包一个项目可以吗

**Comment by social-uni** [comment]
> 试试国内源或者全局番茄，其他注意事项参考 .github/CONTRIBUTING.md

老哥，我v  qky20001212
