### ISSUE TITLE
如何调试uniapp打包源码？

### ISSUE THREAD

**Issue by social-uni** [dcloudio/uni-app#4409]
怎么调试三方类库的源码啊，我程序里用的是三方类库的打包后的代码， 可读性很差， 我引用本地的三方类库也要把本地的三方类库打包以后才能引用， 怎么能直接引用三方类库的源码啊

![3ba0ff39598b13af4b59bbe0038eff6](https://github.com/dcloudio/uni-app/assets/14007972/919e08a9-20ed-481c-9469-39164cb7fc74)

![9241f3ec5250ca06b8e50eeb97163a0](https://github.com/dcloudio/uni-app/assets/14007972/64a94694-3ea2-452b-94a7-53dfa459c945)

uni.js是源码，源码里引用的 ../dist/cli/index.js 是打包后的代码，可是打包后的代码可读性又很差

得把源码打包了才有这个代码

如果 我直接把这里改成源码 index.ts， 就会出现很多错误

**Comment by StrivingRabbit** [comment]
如果你有第三方类库的源码，你可以调整编译选项打包出来可读性高的源码进行引用调试
