### ISSUE TITLE
input唤起键盘类型问题

### ISSUE THREAD

**Issue by KayanChan** [dcloudio/uni-app#441]
**问题描述**
input唤起键盘类型不一致

**复现步骤**
1.  一个input时，唤起了英文键盘；切换成中文键盘后失焦，再次唤起依然是英文键盘
```html
<input type="text"  placeholder="唤起英文键盘"/>
```

2. 两个相同的input，第一个唤起中文键盘，第二个唤起英文键盘
```html
<input type="text" placeholder="唤起中文键盘"/>
<input type="text"  placeholder="唤起英文键盘"/>
```

**预期结果**
希望可以选择唤起的键盘类型

**系统信息:**
 - 发行平台：5+ App
 - 操作系统：iOS 12.2
 - HBuilderX版本： 1.9.9
 - 设备信息： iPhone7

**Comment by zhetengbiji** [comment]
中文键盘还是英文键盘是由系统和输入法决定的
