### ISSUE TITLE
uniapp是否可以提供storybook的适配？或者提供纯语法的转换器？

### ISSUE THREAD

**Issue by calandnong** [dcloudio/uni-app#4415]
**新功能描述**
如题

**现状及问题**
目前因为手头使用uniapp-vue3的项目越来越多，迫切需要创建一些便捷快速的组件开发模式来维护组件库，之前在web上使用vue3，经常都是使用storybook去渲染组件用例和维护组件文档，这样的方式维护起来会更加方便，目前storybook官方也支持了vue3+vite的模式，希望uniapp-vue3也可以支持。

**尝试方案**
个人尝试了fork一份vite-plugin-uni的源码进行修改，并且fork了一份storybook的vue3-vite插件进行替换底层@vitejs/plugin-vue，然后接入运行是没有的问题，但是发现了uniapp是绑死了类小程序结构的渲染模式，这里的修改可能需要的是使用转换 .vue文件为vue3可以被阅读的源码，这边是否可以提供storybook的适配？或者提供纯语法的转换器？目前看手动迁移vite-plugin-uni的转换语法稳定性会非常差，且无法跟随官方升级

**补充信息**
无

**Comment by calandnong** [comment]
@hbcui1984 这边可以辛苦看下这个问题不？

**Comment by hxgqh** [comment]
强烈支持

**Comment by calandnong** [comment]
> 强烈支持

你们现在也有需要用到吗，我现在是临时写了个vite插件支持，一堆hack手段😂

**Comment by hxgqh** [comment]
> > 强烈支持
> 
> 你们现在也有需要用到吗，我现在是临时写了个vite插件支持，一堆hack手段😂

给你的项目开issue 了～ 你的项目可以使用，有些 bug。

**Comment by Otto-J** [comment]
same #4442
