### ISSUE TITLE
【报BUG】微信小程序，新版组件框架适配

### ISSUE THREAD

**Issue by zzzz1Mo** [dcloudio/uni-app#4419]
**问题描述**
微信小程序 [Skyline 渲染引擎](https://developers.weixin.qq.com/miniprogram/dev/framework/runtime/skyline/introduction.html) 已发布 **正式版**；
适配新版组件框架（必须，否则无法预览、发布）时，须在page、component对应json内新增 `{"addGlobalClass": true}` 配置。

**复现步骤**
1.  HBuilderX新建空白vue3项目，运行至[微信开发者工具(须为最新Nightly版)](https://developers.weixin.qq.com/miniprogram/dev/devtools/nightly.html)
2.  根据 [迁移到 Skyline](https://developers.weixin.qq.com/miniprogram/dev/framework/runtime/skyline/migration/#%E5%BC%80%E5%A7%8B%E8%BF%81%E7%A7%BB) 作如下配置，以开启Skyline渲染引擎：
    > 1. manifest.json文件，mp-weixin 节点下新增 `"lazyCodeLoading": "requiredComponents"`、
    > `"rendererOptions": { "skyline": { "defaultDisplayBlock": true } }` 配置；
    > 2. pages.json 文件，页面style节点下新增 `"renderer": "skyline"`、 `"componentFramework": "glass-easel"` 配置。
3. 依据 [glass-easel 适配指引](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/glass-easel/migration.html#JSON-%E9%85%8D%E7%BD%AE) 开始适配：
    > 1. 项目根目录下新建 `components` 文件夹，并新建自定义组件 `custom-widget` ；
    > 2. 在自定义组件json文件内新增 `"component": true`、`"addGlobalClass": true` 配置。
-------------------------------
**预期结果**
上述3.2步骤可在自定义组件`json`内配置

**实际结果**
自定义组件未提供`json`文件所以无法配置

-------------------------------

**系统信息:**
 - 发行平台：微信小程序
 - 操作系统：Win11 21H2
 - HBuilderX版本：HBuilderX 3.8.7.20230703
 - 设备信息：iPad、魅族18Pro

**补充信息**
结合 [变更点适配](https://developers.weixin.qq.com/miniprogram/dev/framework/custom-component/glass-easel/migration.html#%E5%8F%98%E6%9B%B4%E7%82%B9%E9%80%82%E9%85%8D) 第5、6点，可否在编译`.vue`生成对应`.json`文件时，注入`"addGlobalClass": true`配置？

**Comment by zzzz1Mo** [comment]
微信小程序官方开发组的建议是提供`styleIsolation`配置，因为`addGlobalClass`可能会废弃。 @fxy060608

**Comment by zzzz1Mo** [comment]
解决方案：
D:\Program Files\HBuilderX\plugins\uniapp-cli-vite\node_modules\@dcloudio\uni-cli-shared\dist\json\mp\jsonFile.js

**Comment by asasugar** [comment]
> > HBuilderX 3.8.7+版本将 `json = Object.assign({ "styleIsolation": "apply-shared" }, json)`  改成  `json = Object.assign(json, { "styleIsolation": "apply-shared" } )`

HBuilderX 3.8.7+版本对应的@dcloudio/**依赖版本是多少？比如用vscode的用户，需要升级什么版本的依赖包

**Comment by zzzz1Mo** [comment]
> > > HBuilderX 3.8.7+版本将 改成`json = Object.assign({ "styleIsolation": "apply-shared" }, json)``json = Object.assign(json, { "styleIsolation": "apply-shared" } )`
> 
> HBuilderX 3.8.7+版本对应的@dcloudio/**依赖版本是多少？比如用vscode的用户，需要升级什么版本的依赖包

不知道cli项目的lib具体版本，但cli项目改成`json = Object.assign(json, { "styleIsolation": "apply-shared" } )`也可以

**Comment by allce231** [comment]
> > > > HBuilderX 3.8.7+版本将 改成`` json = Object.assign({ "styleIsolation": "apply-shared" }, json)``json = Object.assign(json, { "styleIsolation": "apply-shared" } ) ``
> > 
> > 
> > HBuilderX 3.8.7+版本对应的@dcloudio/**依赖版本是多少？比如用vscode的用户，需要升级什么版本的依赖包
> 
> 不知道cli项目的lib具体版本，但cli项目改成`json = Object.assign(json, { "styleIsolation": "apply-shared" } )`也可以

你们倒是改呀，现在cli 用户根本找不到那个改这个的文件

**Comment by zzzz1Mo** [comment]
> > > > > HBuilderX 3.8.7+版本将 改成json = Object.assign（json， { “styleIsolation”： “apply-shared” } ） ''` json = Object.assign({ "styleIsolation": "apply-shared" }, json)`
> > > 
> > > 
> > > HBuilderX 3.8.7+版本对应的@dcloudio/**依赖版本是多少？比如用vscode的用户，需要升级什么版本的依赖包
> > 
> > 
> > 不知道cli项目的lib具体版本，但cli项目改成也可以`json = Object.assign(json, { "styleIsolation": "apply-shared" } )`
> 
> 你们倒是改呀，现在cli 用户根本找不到那个改这个的文件 以下版本是改哪个文件 请给个路径
> 
> ```
> "@dcloudio/uni-app": "2.0.2-3090920231225001",
> "@dcloudio/uni-app-plus": "2.0.2-3090920231225001",
> "@dcloudio/uni-h5": "2.0.2-3090920231225001",
> "@dcloudio/uni-i18n": "2.0.2-3090920231225001",
> "@dcloudio/uni-mp-360": "2.0.2-3090920231225001",
> "@dcloudio/uni-mp-alipay": "2.0.2-3090920231225001",
> "@dcloudio/uni-mp-baidu": "2.0.2-3090920231225001",
> "@dcloudio/uni-mp-jd": "2.0.2-3090920231225001",
> "@dcloudio/uni-mp-kuaishou": "2.0.2-3090920231225001",
> "@dcloudio/uni-mp-lark": "2.0.2-3090920231225001",
> "@dcloudio/uni-mp-qq": "2.0.2-3090920231225001",
> "@dcloudio/uni-mp-toutiao": "2.0.2-3090920231225001",
> "@dcloudio/uni-mp-vue": "2.0.2-3090920231225001",
> "@dcloudio/uni-mp-weixin": "2.0.2-3090920231225001",
> "@dcloudio/uni-mp-xhs": "2.0.2-3090920231225001",
> "@dcloudio/uni-quickapp-native": "2.0.2-3090920231225001",
> "@dcloudio/uni-quickapp-webview": "2.0.2-3090920231225001",
> "@dcloudio/uni-stacktracey": "2.0.2-3090920231225001",
> "@dcloudio/uni-stat": "2.0.2-3090920231225001",
> ```

`node_modules\@dcloudio\uni-cli-shared\dist\json\mp\jsonFile.js`
skyline适配只能指望dcloud官方了，暂时先自己改下编译器；开发其他平台记得改回来

**Comment by Otto-J** [comment]
关联 https://ask.dcloud.net.cn/question/178062

**Comment by yurj26** [comment]
感谢反馈，后续请在[https://ask.dcloud.net.cn/question/178062](https://ask.dcloud.net.cn/question/178062)跟进。
