### ISSUE TITLE
scroll-view组件在h5端中，渲染出来里面多一个空div

### ISSUE THREAD

**Issue by York-Liang** [dcloudio/uni-app#442]
**问题描述**
scroll-view组件在h5端中，渲染出来里面多一个空div

**复现步骤**
````
<scroll-view style="height: 100px;" :scroll-x="true" :scroll-with-animation="true">
     <div style="height: 100%;">123</div>
</scroll-view>
````

**预期结果**
这个div设置设置上高度100%，或者移除这个div

**实际结果**
![image](https://user-images.githubusercontent.com/22762945/59016632-46632f80-8874-11e9-9363-810d5b5fca46.png)

**系统信息:**
 System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
  Binaries:
    Node: 10.16.0 - C:\Users\lby\AppData\Local\Temp\yarn--1559807844975-0.28358572773930835\node.CMD
    Yarn: 1.16.0 - C:\Users\lby\AppData\Local\Temp\yarn--1559807844975-0.28358572773930835\yarn.CMD
    npm: Not Found
  Browsers:
    Edge: Not Found
  npmPackages:
    @dcloudio/uni-app-plus: * => 0.0.240
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: * => 0.2.956
    @dcloudio/uni-h5: * => 0.5.5
    @dcloudio/uni-mp-alipay: * => 0.0.813
    @dcloudio/uni-mp-baidu: * => 0.0.840
    @dcloudio/uni-mp-toutiao: * => 0.0.338
    @dcloudio/uni-mp-weixin: * => 0.0.960
    @dcloudio/uni-template-compiler: * => 0.9.175
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 0.9.517
    @dcloudio/vue-cli-plugin-uni: latest => 0.9.471
    @dcloudio/webpack-uni-mp-loader: * => 0.3.628
    @dcloudio/webpack-uni-pages-loader: * => 0.2.837
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.8.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.8.0
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-service: ^3.8.0 => 3.8.0
    @vue/cli-shared-utils:  3.8.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-router:  3.0.1
    vue-style-loader:  3.1.2 (3.1.2)
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
    vuex-persistedstate: ^2.5.4 => 2.5.4
    weex-vue-loader: ^0.7.0 => 0.7.0
  npmGlobalPackages:
    @vue/cli: Not Found

**Comment by zhetengbiji** [comment]
这个 div 是 scroll-view 组件的一部分，是滚动内容的容器，可以设置 100%，不过设置100%没有实际意义，scroll-view 用于展示可滚动的内容，100%高度的话不可滚动不如直接用 view 组件。

**Comment by York-Liang** [comment]
如果是横向滚动，是要给里面的子内容添加高度吗？


516192967@qq.com
 
发件人： 折腾笔记
发送时间： 2019-06-06 21:22
收件人： dcloudio/uni-app
抄送： York-Liang; Author
主题： Re: [dcloudio/uni-app] scroll-view组件在h5端中，渲染出来里面多一个空div (#442)
这个 div 是 scroll-view 组件的一部分，是滚动内容的容器，可以设置 100%，不过设置100%没有实际意义，scroll-view 用于展示可滚动的内容，100%高度的话不可滚动不如直接用 view 组件。

**Comment by zhetengbiji** [comment]
> 如果是横向滚动，是要给里面的子内容添加高度吗？ 516192967@qq.com 发件人： 折腾笔记 发送时间： 2019-06-06 21:22 收件人： dcloudio/uni-app 抄送： York-Liang; Author 主题： Re: [dcloudio/uni-app] scroll-view组件在h5端中，渲染出来里面多一个空div (#442) 这个 div 是 scroll-view 组件的一部分，是滚动内容的容器，可以设置 100%，不过设置100%没有实际意义，scroll-view 用于展示可滚动的内容，100%高度的话不可滚动不如直接用 view 组件。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

需要
