### ISSUE TITLE
官方提供的i18n国际化版本，源码运行到浏览器会报警告，如图

### ISSUE THREAD

**Issue by davidsofter** [dcloudio/uni-app#4420]
**问题描述**
官方提供的i18n国际化版本（最新版），源码运行到浏览器环境会报警告（如图）

**复现步骤**

1.  从HbuilderX创建新项目uni-i18n模板，运行到浏览器中启动 
2. 初始化界面控制台报警告
3. 报错上图
![图片](https://github.com/dcloudio/uni-app/assets/44312985/18c7fe91-a342-426e-9ca2-439ba97ae9a2)

**Comment by davidsofter** [comment]
help！！help！！ 有没有人知道啊

**Comment by kaes1a** [comment]
同问，Vue3的项目

**Comment by Otto-J** [comment]
按照我这个改改，我提供一个可以直接运行的 vue3 版本 demo
https://gitcode.net/xiurensha5731/uni-app-questions/-/tree/q/i18n

**Comment by Otto-J** [comment]
> 按照我这个改改，我提供一个可以直接运行的 vue3 版本 demo
> https://gitcode.net/xiurensha5731/uni-app-questions/-/tree/q/i18n

按照我这个改改，我提供一个可以直接运行的 vue3 版本 demo
https://gitcode.net/xiurensha5731/uni-app-questions/-/tree/q/i18n
