### ISSUE TITLE
onShareAppMessage方法不生效

### ISSUE THREAD

**Issue by R-1018** [dcloudio/uni-app#4426]
**问题描述**
[问题描述：onShareAppMessage方法不生效]

**复现步骤**
 <button open-type="share">
              <image class="up" src="../../../static/iconfont/share.png" mode="scaleToFill"></image>
            </button>
<script setup>
import { ref, reactive, getCurrentInstance, defineProps } from 'vue'
import { onShareAppMessage } from '@dcloudio/uni-app'
// 点击分享
onShareAppMessage(() => {
  let shareobj = {
    title: `您好，我是$1{}，这是我的........。`, //分享的标题
    path: 'pages/index/index?item=' + 1, //好友点击分享之后跳转的页面
  }
  console.log('进入分享函数')
  return shareobj 
})
</script>

**预期结果**
应当可以编辑分享内容

**实际结果**
上个月还可使用 现在莫名其妙不可使用这个函数 分享不进入这个函数了

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by 1227228155** [comment]
> **问题描述** [问题描述：onShareAppMessage方法不生效]
> 
> **复现步骤** ![](../../../static/iconfont/share.png)
> 
> <script setup> import { ref, reactive, getCurrentInstance, defineProps } from 'vue' import { onShareAppMessage } from '@dcloudio/uni-app' // 点击分享 onShareAppMessage(() => { let shareobj = { title: `您好，我是$1{}，这是我的........。`, //分享的标题 path: 'pages/index/index?item=' + 1, //好友点击分享之后跳转的页面 } console.log('进入分享函数') return shareobj }) </script>
> **预期结果** 应当可以编辑分享内容
> 
> **实际结果** 上个月还可使用 现在莫名其妙不可使用这个函数 分享不进入这个函数了
> 
> **系统信息:**
> 
> * 发行平台: [如 微信小程序、H5平台、5+ App等]
> * 操作系统 [如 iOS 12.1.2、Android 7.0]
> * HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
> * uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
> * 设备信息 [如 iPhone8 Plus]
> 
> **补充信息** [可选] [根据你的分析，出现这个问题的原因可能在哪里？]

你好 解决了吗

**Comment by zaxlct** [comment]
没解决，真特么坑

**Comment by R-1018** [comment]
这个方法不要写在组件里面 要写在页面才会生效

**Comment by R-1018** [comment]
> 没解决，真特么坑

写在页面 别写在组件里面
