### ISSUE TITLE
2.0.0 运行提示 Replace Autoprefixer browsers option to Browserslist config.

### ISSUE THREAD

**Issue by DestinyHunter** [dcloudio/uni-app#443]
**问题描述**

2.0.0 运行提示 Replace Autoprefixer browsers option to Browserslist config.

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

![image](https://user-images.githubusercontent.com/20897838/59017572-6eec2900-8876-11e9-8e9f-6101b1b8313e.png)

**Comment by zhe-he** [comment]
修改你的postcss.config.js文件
`把 browsers: pkg.browserslist  改为 browsers: pkg.overrideBrowserslist 即可`

**Comment by fxy060608** [comment]
已调整 uni-preset-vue 中的 postcss.config.js （移除 browsers 配置）
