### ISSUE TITLE
希望小程序真正的首页路由不包含在tabBar的list时，能进入其他页面正常显示tabBar

### ISSUE THREAD

**Issue by aiplat** [dcloudio/uni-app#444]
**问题描述**
在微信小程序中，第一次进入pages/index是正常的，授权后进入是空白。然后关闭小程序重新进入小程序，这时是授权过的，进入后也是空白。这个是tabBar的bug吧。

**复现步骤**
[复现问题的步骤]
小程序路由有以下6个

1.	pages/index  首页，授权路由。授权过后进入pages/project/index，没授权时保留在当前页面。这个路由是小程序真正的首页
2.	pages/project/index  项目首页
3.	pages/project/shop   商城
4.	pages/project/cart   购物车
5.	pages/project/order  订单
6.	pages/project/mine   我的

tabBar设置list包含以上2-6的5个路由

在微信小程序中，第一次进入pages/index是正常的，授权后进入是空白。然后关闭小程序重新进入小程序，这时是授权过的，进入后也是空白。这个是tabBar的bug吧。

[或者可以直接贴源代码]

**预期结果**
正常进入pages/project/index，并能显示tabBar

**实际结果**
进入pages/project/index是空白

**系统信息:**
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-7500 CPU @ 3.40GHz
  Binaries:
    Node: 8.11.3 - D:\Program Files\nodejs\node.EXE
    Yarn: 1.9.4 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 5.6.0 - D:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-cli-shared: * => 0.2.91
    @dcloudio/uni-mp-weixin: * => 0.0.9
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 0.3.5
    @dcloudio/vue-cli-plugin-uni: 0.9.34 => 0.9.34
    @dcloudio/webpack-uni-mp-loader: * => 0.3.6
    @dcloudio/webpack-uni-pages-loader: * => 0.2.8
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0-beta.2
    @vue/babel-plugin-transform-vue-jsx:  1.0.0-beta.2
    @vue/babel-preset-app:  3.5.0
    @vue/babel-preset-jsx:  1.0.0-beta.2
    @vue/babel-sugar-functional-vue:  1.0.0-beta.2
    @vue/babel-sugar-inject-h:  1.0.0-beta.2
    @vue/babel-sugar-v-model:  1.0.0-beta.2
    @vue/babel-sugar-v-on:  1.0.0-beta.2
    @vue/cli-overlay:  3.5.0
    @vue/cli-plugin-babel: 3.3.0 => 3.3.0
    @vue/cli-service: ^3.5.0 => 3.5.0
    @vue/cli-shared-utils:  3.5.0
    @vue/component-compiler-utils:  2.6.0
    @vue/eslint-config-prettier: ^4.0.1 => 4.0.1
    @vue/eslint-config-standard: ^4.0.0 => 4.0.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    eslint-plugin-vue: ^4.0.0 => 4.7.1
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    vue: ^2.6.6 => 2.6.8 (2.6.8)
    vue-eslint-parser:  2.0.3
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-router:  3.0.1
    vue-style-loader:  3.1.2 (3.1.2)
    vue-template-compiler: ^2.5.21 => 2.6.8
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.0
    weex-vue-loader: ^0.7.0 => 0.7.0
  npmGlobalPackages:
    @vue/cli: Not Found

**补充信息**
 希望小程序真正的首页路由不包含在tabBar的list时，能进入其他页面正常显示tabBar

**Comment by fxy060608** [comment]
排查自己的代码跳转逻辑，正常情况是允许首页为非 tabBar，处理完逻辑之后，自动跳转至 tabBar 页面，可以尝试将自动跳转的代码延迟执行看看

**Comment by aiplat** [comment]
没有写错什么。

**Comment by ch-zgh-1993** [comment]
@aiplat 测试未发现问题，升级至最新的 HBuilderX 或者更新 cli 版本。使用以下示例代码进行尝试
[Test_06_28.zip](https://github.com/dcloudio/uni-app/files/3337884/Test_06_28.zip)
。

**Comment by aiplat** [comment]
OK，用uni.switchTab确实可以了，之前用的是navigateTo和redirectTo这两个是不可以的。

**Comment by aiplat** [comment]
> 
> 
> @aiplat 测试未发现问题，升级至最新的 HBuilderX 或者更新 cli 版本。使用以下示例代码进行尝试
> [Test_06_28.zip](https://github.com/dcloudio/uni-app/files/3337884/Test_06_28.zip)
> 。

OK，用uni.switchTab确实可以了，之前用的是navigateTo和redirectTo这两个是不可以的。
