### ISSUE TITLE
storybook支持渲染uniapp的组件&api（vue3）

### ISSUE THREAD

**Issue by calandnong** [dcloudio/uni-app#4442]
### 新功能描述
storybook支持渲染uniapp的组件&api（vue3）

### 现状及问题
目前因为手头使用uniapp-vue3的项目越来越多，迫切需要创建一些便捷快速的组件开发模式来维护组件库，之前在web上使用vue3，经常都是使用storybook去渲染组件用例和维护组件文档，这样的方式维护起来会更加方便，目前storybook官方也支持了vue3+vite的模式，希望uniapp-vue3也可以支持。

### 尝试方案
个人尝试了fork一份vite-plugin-uni的源码进行修改，并且fork了一份storybook的vue3-vite插件进行替换底层@vitejs/plugin-vue，然删除了pages.json和manifest.json相关依赖的代码，并移植了h5的部分依赖，除了uniapp下依赖uniapp的dom操作或pages的逻辑，其他都可以在storybook跑起来了，希望大家可以参与一起共建或者 官方的同志看下这个需求看下是否可以考虑支持一个版本出来？我们可以提供代码共建。

#### 代码仓库
[https://github.com/calandnong/uniapp-vue3-storybook-vite-plugin/tree/dev]([uniapp-vue3-storybook-vite-plugin](https://github.com/calandnong/uniapp-vue3-storybook-vite-plugin))

#### 目前支持的能力列表

渲染的标签支持：
- view
- scroll-view
- swiper
- swiper-item
- movable-area
- movable-view
- icon
- text
- rich-text
- progress
- button
- checkbox-group
- checkbox
- editor
- form
- input
- label
- picker-view
- picker-view-column
- radio-group
- radio
- slider
- switch
- textarea
- navigator
- image

API的支持：
- uni.upxtopx
- uni.chooseImage
- uni.previewImage
- uni.getImageInfo
- uni.chooseFile
- uni.canIUse
- uni.setStorage & 其他的数据缓存api
- uni.request
- uni.uploadFile
- uni.downloadFile
- uni.showLoading
- uni.hideLoading
- uni.hideToast
- uni.showActionSheet
- uni.getLocale
- uni.setLocale
- uni.loadFontFace
- uni.getSystemInfoSync
- uni.getSystemInfo
- uni.getWindowInfo

**Comment by calandnong** [comment]
#4415 这里的需求内容来自这个issue

**Comment by SoftwareEngineerPalace** [comment]
这事进度咋样嘞

**Comment by calandnong** [comment]
> 这事进度咋样嘞

还没进度，个人维护中。。。

**Comment by Otto-J** [comment]
感谢你的贡献，官方目前没有经历来参与维护，这个适合社区驱动来完成。或许你可以尝试和 uni-helper @ModyQyW 建立沟通。

**Comment by calandnong** [comment]
> 感谢你的贡献，官方目前没有经历来参与维护，这个适合社区驱动来完成。或许你可以尝试和 uni-helper @ModyQyW 建立沟通。

了解，感谢回应
