### ISSUE TITLE
写uni-app出现问题 如果传参为http://172.16.0.5:8080/h5/pages/index/?a=qqqq=123 访问时自动刷新到http://172.16.0.5:8080/h5/pages/index/[object%20Object]

### ISSUE THREAD

**Issue by whistlesun** [dcloudio/uni-app#445]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
写uni-app出现问题 如果传参为http://172.16.0.5:8080/h5/pages/index/?a=qqqq=123 访问时自动刷新到http://172.16.0.5:8080/h5/pages/index/[object%20Object]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
希望可以兼容错误的传参，不要刷新到古怪的地方

**Comment by aiplat** [comment]
a=qqqq=123
有何意义?

**Comment by whistlesun** [comment]
因为用淘口令打开时淘宝会自动加上一些参数，里面就有类似这种的，sp_tk=77+lY1U3Z1lWNDBaQzXvv6U=&__share__id__=1 这样的，就会触发以上问题

**Comment by whistlesun** [comment]
> a=qqqq=123
> 有何意义?
我解析了一个淘口令的地址，里面就是这个样子，就是有参数里有等号，这个怎么能兼容下，不要严格校验

https://***/award/?ut_sk=1.WFix2saw9zoDAH6OpiKWNtRn_21380790_1560071456990.TaoPassword-Weixin.windvane&id=2&sourceType=other&uid=1233&suid=91BC6194-CF49-451B-81A7-1F109796E14E&_tbScancodeApproach_=scan&un=a5768f18538526b7&share_crt_v=1&**sp_tk=77+lMklYUllWam9iTUbvv6U=**&spm=a211b4.24895642&visa=13a09278fde22a2e&disablePopup=true&disableSJ=1

**Comment by zhetengbiji** [comment]
对于不合法的参数请使用 encodeURIComponent 进行编码

**Comment by whistlesun** [comment]
> 对于不合法的参数请使用 encodeURIComponent 进行编码

我看已经修复了，但是新版0610的版本里还没好，我们是多久可以使用的呀 @fxy060608 
@zhetengbiji 因为淘口令或自动拼接进来的这些参数，不是我们主观上能控制参数的，如果我们能控制那肯定不会传入那样的内容的

**Comment by fxy060608** [comment]
> > 对于不合法的参数请使用 encodeURIComponent 进行编码
> 
> 我看已经修复了，但是新版0610的版本里还没好，我们是多久可以使用的呀 @fxy060608
> @zhetengbiji 因为淘口令或自动拼接进来的这些参数，不是我们主观上能控制参数的，如果我们能控制那肯定不会传入那样的内容的

HBuilderX 的话，需要等 2.0.1 以上 Alpha 版本，cli 的话，可以直接 npm update

**Comment by whistlesun** [comment]
我用的2.0.2.20190614-alpha这个版本的，但是依然不行呢，还是同样问题

**Comment by whistlesun** [comment]
> > > 对于不合法的参数请使用 encodeURIComponent 进行编码
> > 
> > 
> > 我看已经修复了，但是新版0610的版本里还没好，我们是多久可以使用的呀 @fxy060608
> > @zhetengbiji 因为淘口令或自动拼接进来的这些参数，不是我们主观上能控制参数的，如果我们能控制那肯定不会传入那样的内容的
> 
> HBuilderX 的话，需要等 2.0.1 以上 Alpha 版本，cli 的话，可以直接 npm update

我用的2.0.2.20190614-alpha这个版本的，但是依然不行呢，还是同样问题

**Comment by whistlesun** [comment]
2.0.3.20190703-alpha 版本依然不行
https://***/pages/supercrm/award/?ut_sk=1.WFix2saw9zoDAH6OpiKWNtRn_21380790_1562382041302.TaoPassword-Weixin.windvane&id=last&sourceType=other&uid=168807090&suid=E4621AD2-831A-4910-9D10-B12192428773&_tbScancodeApproach_=scanHistory&un=a5768f18538526b7&share_crt_v=1&sp_tk=77+lOUVLQ1lUS2Rxb1Hvv6U=&spm=a211b4.24894679&visa=13a09278fde22a2e&disablePopup=true&disableSJ=1 参数如上，访问自动跳到https://*/pages/supercrm/award/[object%20Object]

**Comment by whistlesun** [comment]
> > > 对于不合法的参数请使用 encodeURIComponent 进行编码
> > 
> > 
> > 我看已经修复了，但是新版0610的版本里还没好，我们是多久可以使用的呀 @fxy060608
> > @zhetengbiji 因为淘口令或自动拼接进来的这些参数，不是我们主观上能控制参数的，如果我们能控制那肯定不会传入那样的内容的
> 
> HBuilderX 的话，需要等 2.0.1 以上 Alpha 版本，cli 的话，可以直接 npm update

https://**/pages/supercrm/award/?ut_sk=1.WFix2saw9zoDAH6OpiKWNtRn_21380790_1562382041302.TaoPassword-Weixin.windvane&id=last&sourceType=other&uid=168807090&suid=E4621AD2-831A-4910-9D10-B12192428773&tbScancodeApproach=scanHistory&un=a5768f18538526b7&share_crt_v=1&sp_tk=77+lOUVLQ1lUS2Rxb1Hvv6U=&spm=a211b4.24894679&visa=13a09278fde22a2e&disablePopup=true&disableSJ=1 参数如上，访问自动跳到https:///pages/supercrm/award/[object%20Object]

**Comment by fxy060608** [comment]
未重现该问题，请确保已升级最新
![image](https://user-images.githubusercontent.com/566799/62099786-c41a4900-b2c1-11e9-978a-5fde4498d9cc.png)

**Comment by RenShine** [comment]
@fxy060608   hash模式下可以  history模式下不行 我是最新的h builder

**Comment by RenShine** [comment]
@fxy060608  这个bug有个很神奇的地方   就是你直接用history模式启动 bug存在， 改外hash模式 bug消失   再改为hash模式  bug不存在  此时重启hbuilder  用history模式启动  bug依然存在

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/commit/eb992ac49944a32e946afb02b5dae65834cabb9f
