### ISSUE TITLE
vue2 uniapp 编译到小红书  真机调用 this.$refs 报错，IOS 卡死退出app

### ISSUE THREAD

**Issue by jonsen-liu** [dcloudio/uni-app#4452]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
vue2 uniapp 编译到小红书  真机调用 this.$refs 报错，IOS 卡死退出app
开发者工具是可以正常获取到 this.$refs
在小红书那边也提了 Issue https://github.com/redengineer/redmini/issues/833
去年提了一个 今年看还是一样

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Otto-J** [comment]
我看这条 issue，和查阅你提到的 xhs 社区问题，都没有提供复现工程或者单页面源码

提供更多信息，有助于定位和解答你的问题。
