### ISSUE TITLE
支付宝mpaas小程序"styleIsolation": "apply-shared"，页面无法正常显示样式

### ISSUE THREAD

**Issue by weiminghaoo** [dcloudio/uni-app#4476]
**问题描述**
3.7.11.20230427之后的版本（不包括此版本），编译到支付宝端，会在对应页面json中添加"styleIsolation": "apply-shared"，这个配置会导致使用基础库1.0的小程序，样式无法正常显示，这个有什么办法删除这个配置吗？

**复现步骤**
编译到支付宝端，配置中切换到基础库1.0

**实际结果**
![image](https://github.com/dcloudio/uni-app/assets/29938792/75d67186-953c-4e3e-9a32-ffffa263647b)

**系统信息:**
 - 发行平台: [如 支付宝小程序mpaas等使用基础库1.0]
 - 操作系统 [所有]
 - HBuilderX版本 [3.7.11.20230427之后的版本，不包括此版本]
 - uni-app版本 [2.0.2-3071120230427001之后的版本，不包括此版本]
 - 设备信息 [如 iPhone8 Plus]

**Comment by xxdnuvycex77** [comment]
hbuilder 3.8.12 也不支持支付宝/钉钉小程序
编写代码
`options: {
		styleIsolation: 'shared',
	}`
编译后未改变钉钉小程序json内代码

**Comment by Deepx-China** [comment]
俺也一样

**Comment by weiminghaoo** [comment]
> hbuilder 3.8.12 也不支持支付宝/钉钉小程序 编写代码 `options: { styleIsolation: 'shared', }` 编译后未改变钉钉小程序json内代码



> 俺也一样

<img width="905" alt="image" src="https://github.com/dcloudio/uni-app/assets/29938792/760cd2c1-6063-489c-9abe-74da85cb5e8b">
排查两个多月了 到现在一点动静都没有，还是先用老版本吧，HBuilderX 3.7.11.20230427  cli 2.0.2-3071120230427001

**Comment by yurj26** [comment]
参考 [https://ask.dcloud.net.cn/question/172186](https://ask.dcloud.net.cn/question/172186)。

**Comment by yurj26** [comment]
HBuilderX 3.99.2023121601-alpha 已修复，在manifest.json的mp-alipay节点添加styleIsolation属性，设置为shared。

**Comment by Moonofweisheng** [comment]
> HBuilderX 3.99.2023121601-alpha 已修复，在manifest.json的mp-alipay节点添加styleIsolation属性，设置为shared。

我想了解一下uni-app为什么要将默认值设置为apply-shared，因为支付宝小程序本身默认的是shared。

**Comment by yurj26** [comment]
> > HBuilderX 3.99.2023121601-alpha 已修复，在manifest.json的mp-alipay节点添加styleIsolation属性，设置为shared。
> 
> 我想了解一下uni-app为什么要将默认值设置为apply-shared，因为支付宝小程序本身默认的是shared。

为了和微信小程序保持一致，并且其他开发者也建议过此默认值。如果不希望默认值为apply-shared，在manifest.json里修改即可。

**Comment by Moonofweisheng** [comment]
对于库开发者来讲，这个改动算是破坏性更新了，未提供此功能时，支付宝默认为shared，更新过后默认值变为apply-shared，投诉很多😂，目前也是按照uni-app的推荐，让组件库的使用者配置shared了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月6日(周三) 下午3:09
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [dcloudio/uni-app] 支付宝mpaas小程序"styleIsolation": "apply-shared"，页面无法正常显示样式 (Issue #4476)




   
HBuilderX 3.99.2023121601-alpha 已修复，在manifest.json的mp-alipay节点添加styleIsolation属性，设置为shared。
  
我想了解一下uni-app为什么要将默认值设置为apply-shared，因为支付宝小程序本身默认的是shared。
  
为了和微信小程序保持一致，并且其他开发者也建议过此默认值。如果不希望默认值为apply-shared，在manifest.json里修改即可。
