### ISSUE TITLE
h 函数无法使用

### ISSUE THREAD

**Issue by icepy** [dcloudio/uni-app#4479]
**问题描述**

我想动态的通过 h 函数来创建页面，但是发现在 uni-app 中无法工作

**复现步骤**

```js
<template>
  <view class="content"></view>
</template>

<script lang="ts">
import { h } from 'vue'

export default {
  setup(){
    return () => {
      return h('view', { class: 'text-icepy'})
    }
    
  }
}
</script>

<style>
.content {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}
</style>

```

**预期结果**
可以把 view 渲染出来

**实际结果**

报错

![image](https://github.com/dcloudio/uni-app/assets/3321837/75329b8b-c38f-4e67-b485-3b7be0bd3934)

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by MinakoKitani** [comment]
你好，请问你是怎么解决的？
