### ISSUE TITLE
 自定义组件模式 真机调试的情况下 组件class无效

### ISSUE THREAD

**Issue by wybLowly** [dcloudio/uni-app#448]
**问题描述**
例子：封装了一个button组件 调试的时候通过class修改mragin-top 在web中调试没有问题 真机调试无效 其他组件也是同样的问题

**Comment by fxy060608** [comment]
贴代码

**Comment by wybLowly** [comment]
```
//button 组件
<template>
    <view class="flex flex-direction" >
        <button class="cu-btn" :class="classList" :disabled="disabled" type="">
            <slot></slot>
        </button>
    </view>
</template>

<script>
export default {
  name: 'button',
  props: {
	classList: {
	  type: Array,
	  default () {
		return ['bg-green', 'lg']
	  }
	},
	disabled: {
	  type: Boolean,
	  default: false
	}
  }
}
</script>
```
```
//外部使用
<template>
    <cu-button @click.native="submitLogin" class='submit-btn'>确定</cu-button>
</template>
<style>
   .submit-btn{
       margin-top:40upx;    //无效
   }
</style>
```

**Comment by wybLowly** [comment]
> 贴代码



> 贴代码
```
//button 组件
<template>
    <view class="flex flex-direction" >
        <button class="cu-btn" :class="classList" :disabled="disabled" type="">
            <slot></slot>
        </button>
    </view>
</template>

<script>
export default {
  name: 'button',
  props: {
	classList: {
	  type: Array,
	  default () {
		return ['bg-green', 'lg']
	  }
	},
	disabled: {
	  type: Boolean,
	  default: false
	}
  }
}
</script>
```
```
//外部使用
<template>
    <cu-button @click.native="submitLogin" class='submit-btn'>确定</cu-button>
</template>
<style>
   .submit-btn{
       margin-top:40upx;    //无效
   }
</style>
```
上述是其中一个例子  我这边 是自定义组件编译模式 但是 通过class来修改components样式 这边全部不起作用

**Comment by zhe-he** [comment]
这个uni-app官网有说，不支持在组件上加class (个人觉得：需要和内部class合并，真解决是可以解决的，只是比较繁琐)
你可以改为
<view class='submit-btn'>
<cu-button @click.native="submitLogin">确定</cu-button>
</view>

**Comment by wybLowly** [comment]
> 这个uni-app官网有说，不支持在组件上加class (个人觉得：需要和内部class合并，真解决是可以解决的，只是比较繁琐)
> 你可以改为
> 
> ```
> <view class='submit-btn'>
> <cu-button @click.native="submitLogin">确定</cu-button>
> </view>```
> ```

可是我看 官方说的 是template编译模式 不支持组件class  自定义组件 没有说不支持  这个只是我举个例子  但是要是 想单独修改组件内部的一些样式 是无法解决的

**Comment by zhetengbiji** [comment]
测试未复现问题：使用提供的示例代码在自定义组件模式测试，表现正常

**Comment by liushengyi** [comment]
这个问题，我们这边也出现了，测试的是， 如果自定义组件 嵌套比较深（大概4层以上），这个class 就会失效。

**Comment by zhetengbiji** [comment]
> 这个问题，我们这边也出现了，测试的是， 如果自定义组件 嵌套比较深（大概4层以上），这个class 就会失效。

你说的失效是指的编译后的标签上没有这个class，还是编译后标签上有这个class但是样式不生效？

**Comment by liushengyi** [comment]
@zhetengbiji  标签上有这个class样式名，但是样式实际没有生效

**Comment by zhetengbiji** [comment]
> @zhetengbiji 标签上有这个class样式名，但是样式实际没有生效

提供一个示例项目，去ask论坛上传即可

**Comment by liushengyi** [comment]
可能是我之前测试有问题，我新建的demo又一直没有出现（微信）。   但是 支付宝小程序 （就是题主的demo）,确定是无效的。

**Comment by codingories** [comment]
lz 我现在动态设置样式用this.$refs h5页面没问题 但是用iphone7 plus真机测试就有样式问题 请问您找到合适的解决方案了吗？

**Comment by fanyetu** [comment]
> 测试未复现问题：使用提供的示例代码在自定义组件模式测试，表现正常

支付宝小程序测试复现了此问题，请关注一下，谢谢。

**Comment by xiaopin** [comment]
请问这个问题怎么解决？微信小程序上是没问题的，但是支付宝小程序上，这个class就会被去掉导致样式有问题。
