### ISSUE TITLE
头条小程序aweme-user-card组件属性被编译导致aweme-id无法使用

### ISSUE THREAD

**Issue by wangjieCode** [dcloudio/uni-app#4480]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**实际结果**
<img width="1175" alt="image" src="https://github.com/dcloudio/uni-app/assets/49115360/2ecc639e-72c7-49f9-821b-2ef04f0c31de">

**系统信息:**
 - 发行平台: 头条小程序
 - uni-app版本 3.0.0-alpha-3080120230425001

**Comment by wangjieCode** [comment]
<img width="1440" alt="image" src="https://github.com/dcloudio/uni-app/assets/49115360/77fa97bd-b746-4f3c-9ceb-40698ff5d37f">
是不是在这个地方添加一下组件名称就可以正常了，如果是这样我愿意贡献一个pr

**Comment by yurj26** [comment]
升级到最新版，已修复。
