### ISSUE TITLE
Vue3 cli如何设置publicpath

### ISSUE THREAD

**Issue by Rayzworld** [dcloudio/uni-app#4482]
publicPath | String | 引用资源的地址前缀，仅 Vue2 发布时生效。

mainfest不生效 vue.config里配好像也没效果
publicPath 不支持，如果需要配置，请在 manifest.json->h5->router->base 中配置，参考文档：[h5-router](https://zh.uniapp.dcloud.io/collocation/manifest#h5-router)

咋整 路堵死了？

**Comment by snowkeda** [comment]
vite.config.js  中 配置 base

**Comment by Otto-J** [comment]
楼上的回复是正确的。

是的，uni-app 的 vue3 本质是 vite 的工程，需要看对应的 vite 配置文件。
