### ISSUE TITLE
uniapp默认开启了h5端的scoped，是否可配置默认值？

### ISSUE THREAD

**Issue by zxl20070701** [dcloudio/uni-app#4491]
**新功能描述**
当前uniapp打包成h5的时候，vue文件中的style标签默认开启了scoped，是否可以新增一个配置项，设置h5下默认是否开发scoped

**现状及问题**
由于默认开启了scoped，有时候可能导致如下问题：
1、由于h5默认开启了scoped，而微信小程序等没有开启，这导致如果在不同端运行存在较大差异
2、有时候修改组件css使用穿透是麻烦的，我们使用BEM来隔离样式，希望关闭scoped方便开发

**尝试方案**
为了跨端兼容，我们做了如下约定：
1、统一开启scoped
或
2、每个页面或组件有唯一的class命名前缀，不允许出现`view`或`.btn`等“通用”选择器

**补充信息**
感觉如果添加scoped的时候，可以区别页面和组件，感觉组件的scoped开启大部分情况总是好的，而页面有时候关闭scoped也并不总是有害的

**Comment by gaokun** [comment]
在 #3696 中有workaround:

`<style lang="scss" noscoped>`

原理: 因为编译器只是简单的<b>匹配style上有无scoped</b>，有的话，就不自动补充了

**Comment by yelloxing** [comment]
666

**Comment by tieniu1** [comment]
> 在 #3696 中有workaround:
> 
> `<style lang="scss" noscoped>`
> 
> 原理: 因为编译器只是简单的匹配style上有无scoped，有的话，就不自动补充了


现在加上 noscoped 也不生效了。
<style lang="scss" noscoped>
  /* App隐藏头部 */
  uni-page-head {
    display: none !important;
    background: red;
  }
</style>

**Comment by gaokun** [comment]
> > 在 #3696 中有workaround:
> > `<style lang="scss" noscoped>`
> > 原理: 因为编译器只是简单的匹配style上有无scoped，有的话，就不自动补充了
> 
> 现在加上 noscoped 也不生效了。
> 
> <style lang="scss" noscoped> /* App隐藏头部 */ uni-page-head { display: none !important; background: red; } </style>

那就是规则又改了, 我最近没在搞uniapp了 ^_^
