### ISSUE TITLE
manifest.json 和 pages.json 支持用 js 编写

### ISSUE THREAD

**Issue by jamieYou** [dcloudio/uni-app#450]
**新功能描述**
使用 js 文件描述配置，而不是 json 文件

**现状及问题**
json 不支持写函数，导致 devServer 的代理配置不够灵活

**补充信息**
可参考 babel 和 eslint，配置即可支持 json，也支持 js

**Comment by fxy060608** [comment]
可以考虑支持，不过该 js 是编译时执行，非运行时执行，需要导出一个类似现在 pages.json，manifest.json 一样的 json 对象。

**Comment by jamieYou** [comment]
> 可以考虑支持，不过该 js 是编译时执行，非运行时执行，需要导出一个类似现在 pages.json，manifest.json 一样的 json 对象。

嗯，其实就跟babel 类似，`module.exports = {}` 这样导出

**Comment by aiplat** [comment]
可以用node生成

**Comment by zhe-he** [comment]
mark
把现有的manifest.json 和 pages.json 改为 manifest.js[ts] 或 pages.js[ts]
然后 export default { 现有的内容 }
静等大神提merge

**Comment by jamieYou** [comment]
功能实现并不难，问题是我找不到 `@dcloudio/uni-cli-shared` 的源码地址，提不了 pr
@fxy060608 是不是这个 github 并没有把 node 那边的源码公开？

**Comment by jamieYou** [comment]
> mark
> 把现有的manifest.json 和 pages.json 改为 manifest.js[ts] 或 pages.js[ts]
> 然后 export default { 现有的内容 }
> 静等大神提merge
> 
> 这个需求太小众了，优先级很低了

功能实现并不难，问题是我找不到 `@dcloudio/uni-cli-shared` 的源码地址，提不了 pr
@fxy060608 是不是这个 github 并没有把编译相关的源码公开？

**Comment by jamieYou** [comment]
看到 3.0 有支持了，期待 3.0 的发布

**Comment by tiger8888** [comment]
强烈建议啊,比如h5打包中的publicPath,实际情况往往是线上测试环境用一个publicPath,正式环境又是另外一个,你说,我怎么办?
每次都手工改嘛? 很容易出错!

**Comment by jamieYou** [comment]
目前 pages.js 是支持了。但是 manifest.json 还没支持
appid 我想测试环境和正式环境填不同的，或者测试环境不开启，这个也不好做。
如果条件编译支持环境变量就好了

**Comment by xiaofuliang** [comment]
请问你是怎么实现 的

**Comment by xlfsummer** [comment]
> 强烈建议啊,比如h5打包中的publicPath,实际情况往往是线上测试环境用一个publicPath,正式环境又是另外一个,你说,我怎么办?
> 每次都手工改manifest.json嘛? 很容易出错!

如果你路由用的 hash 模式，publicPath 可以考虑使用相对路径

**Comment by jamieYou** [comment]
@xiaofuliang 几个月前的版本，官方已经支持 pages.js 了。但是文档没有说明

保留 pages.json 文件，内容为 `{}`
然后同目录建一个  pages.js
```
module.exports = function () {
 return {}
}
```
这样的话，配置就是以 pages.js 为准了

**Comment by xiaofuliang** [comment]
@jamieYou 刚试了下，可以了，谢谢！ 他这个现在还不支持热更新的吧？每次改了pags.js是要重新启动才会生成

**Comment by xiaofuliang** [comment]
@jamieYou 请问一下现在在pages.js里面不支持条件编译，有什么API可以获取到当前环境是H5还是小程序 还是APP

**Comment by jamieYou** [comment]
@xiaofuliang 
环境变量 process.env.UNI_PLATFORM 或者 process.env.VUE_APP_PLATFORM 里面有平台的信息
我这边修改 pages.js 可以热更新

**Comment by xiaofuliang** [comment]
@jamieYou 你那修改pages.js后不用重启就可以？ 我这边如果是加了page，就要重启，这个page.js不是在启动时编译的吗，会热更新吗？

**Comment by EryouHao** [comment]
@xiaofuliang @jamieYou 请问现在支持多个环境的 appid 设置了吗？
（想根据环境变量进行不同的 appid 设置

**Comment by yarkone** [comment]
history模式的publicPath本地，测试和线上环境真的用的不是同一个，还要手动修改，好麻烦。
望支持js模式

**Comment by soulcm** [comment]
同求支持啊，publicPath不然没法搞了，无法自动赋值

**Comment by iizhangchao** [comment]
> @xiaofuliang @jamieYou 请问现在支持多个环境的 appid 设置了吗？
> （想根据环境变量进行不同的 appid 设置

请问解决这个多环境的appid设置了么？

**Comment by iizhangchao** [comment]
@EryouHao  请问解决这个多环境的appid设置了么？

**Comment by iizhangchao** [comment]
直接使用node来改写文件配置，也能达到目的。
在vue.config.js 来修改appid
```
const fs = require("fs")
const path = require("path")

function setEnvAppId() {
    const appidPro = "wxappidpro"
    const appidDev = "wxappiddev"
    const appid = process.env.NODE_ENV === "production" ? appidPro : appidDev
    const manifestPath = path.join(__dirname, "./src/manifest.json")

    fs.readFile(manifestPath, "utf8", function (err, data) {
        if (err) throw (err)
        const list = JSON.parse(data)
        list["mp-weixin"].appid = appid
        const newContent = JSON.stringify(list, null, 4)

        fs.writeFile(manifestPath, newContent, "utf8", (err) => {
            if (err) throw err
            console.log("appid修改完成")
        })
    })
}

setEnvAppId()
```

**Comment by StrivingRabbit** [comment]
`pages.js`已支持，`manifest.js`暂不支持
