### ISSUE TITLE
【Bug】【支付宝小程序】在使用支付宝小程序原生lottie组件时，会将组件的属性（path、autoplay、repeat-count等）编译导致无法使用

### ISSUE THREAD

**Issue by lanshengzhong** [dcloudio/uni-app#4510]
**问题描述**
在使用支付宝小程序原生lottie组件时，会将组件的属性（path、autoplay、repeat-count等）编译导致无法使用

**复现步骤**

[或者可以直接贴源代码]

**预期结果**
可以使用
**实际结果**

    <lottie class="canvas" id="lottie" :autoplay="true" :optimize="true" :path="`${ossURL}/demo.json`" repeatCount="-1" />

以下为真机调试图片
![image](https://github.com/dcloudio/uni-app/assets/20151096/b4d709ed-0ec3-4ade-a86e-5bbe4e50f524)

**系统信息:**
 - 发行平台: 支付宝小程序
 - 操作系统 IOS16.6
 - uni-app版本 cli 3.0.0-3081220230817001
 - 设备信息 iPhone13

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by yurj26** [comment]
感谢反馈，临时解决方案：替换 [文件](https://github.com/dcloudio/uni-app/blob/next/packages/uni-mp-alipay/dist/uni.compiler.js) 到目录 `/node_modules/@dcloudio/uni-mp-alipay/dist`。

**Comment by yurj26** [comment]
> 感谢反馈，临时解决方案：替换 [文件](https://github.com/dcloudio/uni-app/blob/next/packages/uni-mp-alipay/dist/uni.compiler.js) 到目录 `/node_modules/@dcloudio/uni-mp-alipay/dist`。

HBuilderX 3.93.2023101913-alpha 已修复
