### ISSUE TITLE
hbuilder 3.8.12 也不支持支付宝/钉钉小程序属性 styleIsolation

### ISSUE THREAD

**Issue by Deepx-China** [dcloudio/uni-app#4516]
hbuilder 3.8.12 也不支持支付宝/钉钉小程序
编写代码
`options: {
		styleIsolation: 'shared',
	}`
编译后未改变钉钉小程序json内代码

_Originally posted by @xxdnuvycex77 in https://github.com/dcloudio/uni-app/issues/4476#issuecomment-1709381558_

**Comment by yurj26** [comment]
参考 [https://ask.dcloud.net.cn/question/172186](https://ask.dcloud.net.cn/question/172186)。
