### ISSUE TITLE
【Pinia 在cli使用报错】cli创建的项目，pinia引用报错

### ISSUE THREAD

**Issue by chao921125** [dcloudio/uni-app#4519]
**问题描述**
使用uni-cli创建项目之后，按照官方给的引用报错，在vue的项目中没有错误。错误如下：

"hasInjectionContext" is not exported by "node_modules/.pnpm/pinia@2.1.6_typescript@5.2.2_vue@3.3.4/node_modules/vue-demi/lib/index.mjs", imported by "node_modules/.pnpm/pinia@2.1
.6_typescript@5.2.2_vue@3.3.4/node_modules/pinia/dist/pinia.mjs".
at ../node_modules/.pnpm/pinia@2.1.6_typescript@5.2.2_vue@3.3.4/node_modules/pinia/dist/pinia.mjs:6:9
  4:  * @license MIT
  5:  */
  6: import { hasInjectionContext, inject, toRaw, watch, unref, markRaw, effectScope, ref, isVue2, isRef, isReactive, set,...
              ^
  7: import { setupDevtoolsPlugin } from '@vue/devtools-api';

**复现步骤**
1.  创建 npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project
2. 安装 "pinia": "^2.1.6",
3. 配置 main.ts
```
import { createSSRApp } from "vue";
import * as  Pinia from "pinia";
import App from "./App.vue";

export function createApp() {
  const app = createSSRApp(App);
  app.use(Pinia.createPinia());
  return {
    app,
    Pinia,
  };
}

```

**预期结果**
正常引用，且可使用

**实际结果**
启动报错

**系统信息:**
 - 发行平台: 微信小程序、H5平台
 - 操作系统: Windows10、MacOS 13
 - HBuilderX版本: 如使用HBuilderX 3.8.12.20230817
 - uni-app版本: 3.0.0-3081220230817001
 - 设备信息: 微信小程序 1.06.2307260

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by hc-advokate** [comment]
目前和vue没有直接关系，我在vue的项目中已经将两者全部更新到最新版本均无任何错误，
目前猜测应该是pinia最新版与@vue/runtime-core出现了冲突，大家将pinia的版本降下来就可以解决问题了：
    "pinia": "2.0.36",
