### ISSUE TITLE
依赖中代码出现匹配编译器宏导致报错

### ISSUE THREAD

**Issue by enpitsuLin** [dcloudio/uni-app#4524]
初步排除应该是使用了 [ol](https://www.npmjs.com/package/ol) 其中的依赖引用到了不同版本的 pako 这个库, 而 uniapp 中也用到了(可能不是这个原因)

然后在预处理这个库的代码中匹配到了类似 `# ifdef` 的宏 但是没有结束语句, 然后最后会报 `Unbalanced delimiter found in string` 
 
## workaround

用户可以打个 patch 跳过对 node_modules 中依赖的预处理, 这个修复方法应该是蛮合理的,官方看看可以不可以合并得了

```diff
diff --git a/dist/plugin/esbuild/esbuildPrePlugin.js b/dist/plugin/esbuild/esbuildPrePlugin.js
index b49d7de5e927de355a0320078ee6c63a63cbd8a6..531751c41c585e1e8c849d988772c96b5b3d0477 100644
--- a/dist/plugin/esbuild/esbuildPrePlugin.js
+++ b/dist/plugin/esbuild/esbuildPrePlugin.js
@@ -17,7 +17,7 @@ function esbuildPrePlugin() {
                 if (ext === 'mjs')
                     ext = 'js';
                 let contents = fs_1.default.readFileSync(id, 'utf-8');
-                if (contents.includes('#endif')) {
+                if (contents.includes('#endif')&&!id.includes('node_modules')) {
                     contents = (0, uni_cli_shared_1.preJs)(contents);
                 }
                 return {

```

**Comment by enpitsuLin** [comment]
或者官方好好重写下这个编译宏的逻辑,但我觉得不大可能了,有遇到类似 `Unbalanced delimiter found in string` 的错误可以看看是不是依赖中匹配到了这个字符串

**Comment by Otto-J** [comment]
感谢反馈，你提到了如果 endif 结束逻辑可以忽略 node_modules ，并且提到了 `ol` 这个库。可以进一步解释，忽略 node_modules 和 ol 这个库的关系吗？
有业务场景允许用户通过 npm 的内容直接作为 page/components 页面

**Comment by enpitsuLin** [comment]
时间有点太久了 原先的项目应该是用ol渲染地图，然后它的依赖中有 https://github.com/nodeca/pako 这个库，然后里面有 uni-app 编译宏作注释的，虽然也是成一对的，但不知道为什么没正常处理会报错，然后就patch解决了

https://github.com/nodeca/pako/blob/62cb729e7813176ce2d2694b89c8724680fca383/lib/zlib/deflate.js#L550

**Comment by Lazybin** [comment]
我也遇到了这个问题Unbalanced delimiter found in string  请问是怎么解决的
