### ISSUE TITLE
vue2中 import 带有动态参数引入失败

### ISSUE THREAD

**Issue by bsuooo** [dcloudio/uni-app#4526]
**问题描述**
vue版本中 import 带有动态参数引入失败, 写死路径显示正常.

**预期结果**
动态引入成功

**实际结果**
![image](https://github.com/dcloudio/uni-app/assets/91053541/578e6ef5-e87b-4162-bb43-72d9a77ad0a6)
![image](https://github.com/dcloudio/uni-app/assets/91053541/c7209c50-1cf4-45c7-a6bc-820a3fcdc9f0)

**系统信息:**
 - 发行平台: h5
 - 操作系统 
 - HBuilderX版本 3.6.4.20220922
 - uni-app版本 使用hbuildx 新建项目
 - 设备信息 都可

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Hsensor** [comment]
import(变量)；你知道webpack 会做什么处理吗？你这样编译器怎么能知道要读取那个文件，编译阶段（压根不能知道呀）

**Comment by mmmmr** [comment]
> import(变量)；你知道webpack 会做什么处理吗？你这样编译器怎么能知道要读取那个文件，编译阶段（压根不能知道呀）
有道理, 所以是不支持动态加载文件吗? 我有个vue2 vuecli的项目可以这样使用, 我以为是通用的..
