### ISSUE TITLE
v3 + ts ，支付宝小程序 swiper滑动后页面卡死

### ISSUE THREAD

**Issue by mynamezcc** [dcloudio/uni-app#4527]
**问题描述**
问题描述：v3 + ts ，支付宝小程序 swiper滑动后页面卡死

       <swiper
                    class="swiper"
                    circular
                    :current="currentIndex"
                    :indicator-dots="false"
                    :autoplay="true"
                    :interval="showInfo && showInfo.interval ? showInfo.interval : 5000"
                    :duration="500"
                    @transition="transition"
                    @change="change"
                    @animationfinish="animationfinished"
                >
                    <swiper-item v-for="(item, index) in bannerList" :key="index">
                        <image
                            class="img"
                            :src="dealOssImage(item.image || '', 1125, 1185)"
                            mode="widthFix"
                            @click.stop="bannerClick(item, index)"
                        />
                    </swiper-item>
                </swiper>

**系统信息:**
 - 发行平台: 支付宝小程序
 - 操作系统 IOS16.1.1
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - "@dcloudio/uni-app": "3.0.0-3080720230703001",
        "@dcloudio/uni-app-plus": "3.0.0-3080720230703001",
        "@dcloudio/uni-components": "3.0.0-3080720230703001",
        "@dcloudio/uni-h5": "3.0.0-3080720230703001",
        "@dcloudio/uni-mp-alipay": "3.0.0-3080720230703001",
        "@dcloudio/uni-mp-baidu": "3.0.0-3080720230703001",
        "@dcloudio/uni-mp-jd": "3.0.0-3080720230703001",
        "@dcloudio/uni-mp-kuaishou": "3.0.0-3080720230703001",
        "@dcloudio/uni-mp-lark": "3.0.0-3080720230703001",
        "@dcloudio/uni-mp-qq": "3.0.0-3080720230703001",
        "@dcloudio/uni-mp-toutiao": "3.0.0-3080720230703001",
        "@dcloudio/uni-mp-weixin": "3.0.0-3080720230703001",
        "@dcloudio/uni-quickapp-webview": "3.0.0-3080720230703001",
        "@dcloudio/uni-ui": "^1.4.27",
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by yurj26** [comment]
在原生小程序中测试下是否有问题，如有问题请向支付宝社区反馈。
