### ISSUE TITLE
申请自定义编译平台增加快手小程序

### ISSUE THREAD

**Issue by ckyfighter** [dcloudio/uni-app#4529]
**新功能描述**
简洁描述你希望补充完善的增强功能
{
    /**
     * package.json其它原有配置 
     * 拷贝代码后请去掉注释！
     */
    "uni-app": {// 扩展配置
        "scripts": {
            "custom-platform": { //自定义编译平台配置，可通过cli方式调用
                "title":"自定义扩展名称", // 在HBuilderX中会显示在 运行/发行 菜单中
                "browser":"",  //运行到的目标浏览器，仅当UNI_PLATFORM为h5时有效
                "env": {//环境变量
                    "UNI_PLATFORM": "",  //基准平台
                    "MY_TEST": "", // ... 其他自定义环境变量
                 },
                "define": { //自定义条件编译
                    "CUSTOM-CONST": true //自定义条件编译常量，建议为大写
                }
            }
        }    
    }
}
希望UNI_PLATFORM也支持快手小程序
**现状及问题**
[当前现状及由此导致的不便]
需要使用同一套代码管理多个快手小程序
**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]
目前新建了.env文件使用process.env.NODE_ENV进行区分
**补充信息**
[其它你认为有参考价值的信息]

**Comment by Otto-J** [comment]
已支持快手小程序。
