### ISSUE TITLE
"usingcomponents": true

### ISSUE THREAD

**Issue by SilasDong** [dcloudio/uni-app#453]
**问题描述**
android 使用了"usingcomponents": true后离线打包会出现白屏，去除就可以了，
使用https://github.com/jp1017/Add2UniApp 里面的Android代码打包的

**Comment by zhetengbiji** [comment]
检查使用的sdk版本和HBuilderX版本是否匹配：https://ask.dcloud.net.cn/docs/#//ask.dcloud.net.cn/article/103

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
