### ISSUE TITLE
vue3+vite项目中 开发环境和打包环境refs体现不同?

### ISSUE THREAD

**Issue by Statfine** [dcloudio/uni-app#4533]
**问题描述**
<CustomCom ref="customCom" />
uni -p mp-weixin 启动加载项目，可以通过getCurrentInstance()?.ctx?.$refs.customCom 获取到子组件实例，并调用组件内部方法
uni build -p mp-weixin --minify  导入编译的项目文件getCurrentInstance()?.ctx?.$refs 获取到的是null

**复现步骤**
[复现问题的步骤]
1.  子组件<CustomCom ref="customCom" />
2. uni -p mp-weixin 微信开发工具导入项目
3. getCurrentInstance()?.ctx?.$refs.customCom 获取到子组件实例，并可以调用组件内部方法
4. uni build -p mp-weixin --minify  微信开发工具导入编译的项目文件
5. getCurrentInstance()?.ctx?.$refs  为null

**预期结果**
开发环境的产物和打包产物体现一直

**实际结果**
开发环境的产物和打包产物 

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: mac
 - uni-app版本 3.0.0-alpha-3061620221230002

**Comment by yurj26** [comment]
这是vue框架的行为，可以通过以下方式获取组件实例 [文档](https://cn.vuejs.org/api/built-in-special-attributes.html#ref)

**Comment by Statfine** [comment]
@yurj26  可能你没看清楚我的提问，**“开发环境和打包环境refs体现不同”**  uniapp的build也是vue 框架打包行为吗？

**Comment by yurj26** [comment]
> @yurj26 可能你没看清楚我的提问，**“开发环境和打包环境refs体现不同”** uniapp的build也是vue 框架行为吗？

"开发环境和打包环境refs体现不同"是vue框架的行为，uniapp会遵循vue的行为，另外尽量不要使用文档未声明的方法。
