### ISSUE TITLE
官方是否还对issues进行回复或者对开发者提供帮助

### ISSUE THREAD

**Issue by Statfine** [dcloudio/uni-app#4534]
**问题描述**

**issues最近几个月都没有官方的人员进行回复了，仅有关闭的也都是自行关闭或者想办法(非官方)处理。
想知道官方是否还有人员进行社区的管理和bug的回复处理**

**复现步骤**
![open](https://github.com/dcloudio/uni-app/assets/4608910/77163934-17d6-446b-93a0-8cc6a670f242)

![closed](https://github.com/dcloudio/uni-app/assets/4608910/8c7e42fa-30f5-4957-b64f-2f0f83ec408d)

**预期结果**
**希望官方能够抽空看看社区的提问以及bug**

**Comment by zhetengbiji** [comment]
由于近期忙于 uts/uvue 故而社区维护人员较少，后续会分配更多人员回来维护。
