### ISSUE TITLE
picker 组件 mode = region时数据源在哪里？如何配置

### ISSUE THREAD

**Issue by JerrySir** [dcloudio/uni-app#454]
**问题描述**
我司在选择地址的时候不允许选择香港澳门，这个如何配置？

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
picker 组件中的城市数据是对应平台内置的，不可修改。想修改的话，可以使用第三方组件，如: [mpvue-citypicker](https://github.com/MPComponent/mpvue-citypicker)
