### ISSUE TITLE
createInnerAudioContext获取当前播放时间错误

### ISSUE THREAD

**Issue by Xue-Felix** [dcloudio/uni-app#4542]
**问题描述**
当我第一次播放，播放一段时间后，停止播放， 再次播放，获取到的currentTime是上一次停止播放的时间。
.
**复现步骤**
[复现问题的步骤]
1. 点击“播放按钮”
2. 播放一段时间后（ >10秒左右）
3. 点击“停止播放”
4. 再次点击“播放按钮”

**预期结果**
再次开始播放时，获取到的currentTime是当前播放时间

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统：Android & IOS

**Comment by yurj26** [comment]
在原生小程序中测试下，如有问题，请向微信社区反馈。
