### ISSUE TITLE
条件编译 能不能增加个开发环境

### ISSUE THREAD

**Issue by ctforcp** [dcloudio/uni-app#4546]
**新功能描述**
增加一个开发环境条件

**现状及问题**
有时候为了开发测试方便，有些代码只想在开发阶段生效，要是能添加个开发环境条件编译，就方便很多。

```
#ifdef DEV
// 开发环境的代码
#endif
```

**Comment by calandnong** [comment]
@ctforcp https://uniapp.dcloud.net.cn/collocation/package.html#，官方文档里的这个能力可以看下，或许可以解决你的问题
