### ISSUE TITLE
uniapp cli模式启动后在手机钉钉浏览器白屏，报错"unexpected token ?"

### ISSUE THREAD

**Issue by zjtt** [dcloudio/uni-app#4548]
h5平台，vue3编译依赖版本是3.0.0-3081220230817001"，问题可能出在@dcloudio/vite-plugin-uni依赖的vite版本不对导致的，
"@dcloudio/uni-app": "3.0.0-3081220230817001",

**Comment by notbucai** [comment]
找到问题了吗

**Comment by zjtt** [comment]
收到啦，谢谢

**Comment by Otto-J** [comment]
看报错是宿主浏览器，也及时钉钉浏览器版本比较低，不支持 可选链语法，设置一下 @vitejs/plugin-legacy兼容老版本
