### ISSUE TITLE
遍历对象，循环内使用方法时，传入对象属性报错

### ISSUE THREAD

**Issue by w22296437978** [dcloudio/uni-app#455]
![image](https://user-images.githubusercontent.com/39508539/59257562-c4567a80-8c68-11e9-8d29-fb4d9905d504.png)
![image](https://user-images.githubusercontent.com/39508539/59257443-8bb6a100-8c68-11e9-9600-ad3dce787d14.png)
![image](https://user-images.githubusercontent.com/39508539/59257459-9113eb80-8c68-11e9-96b8-394def836196.png)
![image](https://user-images.githubusercontent.com/39508539/59257480-98d39000-8c68-11e9-9f2a-3a10da5d197c.png)

**Comment by w22296437978** [comment]
最后我把方法抽出来做成组件，在组件属性上引用对象属性解决了这个问题

**Comment by hbbaly** [comment]
遍历对象会报错的，能说的在详细一下么？

**Comment by brucehelen** [comment]
> 遍历对象会报错的，能说的在详细一下么？

只要在模板里面调用methods中定义的方法就会有这个问题。

**Comment by zhetengbiji** [comment]
cd5c3cddca2c12cb895f522479e39e56d99b0e3e

**Comment by zhetengbiji** [comment]
CLI最新的alpha版有相关优化，可以将依赖更新到2.0.0-alpha-28320200727005后测试一下
