### ISSUE TITLE
怎么关闭微信小程序自定义组件 wxcomponents 转 .vue 的行为？

### ISSUE THREAD

**Issue by vortesnail** [dcloudio/uni-app#4550]
**问题描述**
怎么关闭微信小程序自定义组件 wxcomponents 转 .vue 的行为？

**复现步骤**
1. 新建了一个 vue2 的项目；
2. 根目录新建了一个 wxcomponents 文件夹，并写了一个最简单的组件
3. 运行到浏览器，会发现 wxcomponents 下多了一个 .vue 文件

**预期结果**
我不希望做转换，因为我不会在 h5 用到这个自定义组件。

**实际结果**
 wxcomponents 下多了一个 .vue 文件

**系统信息:**
- vue2 项目中会出现这个情况
- vue3 项目默认不会做转换，所以没问题

**补充信息**
![image](https://github.com/dcloudio/uni-app/assets/18679842/48ba68f0-6fb2-4a94-a0b6-53df88459e21)

运行到浏览器后：

![image](https://github.com/dcloudio/uni-app/assets/18679842/01e87969-eedc-4b2d-8107-878aca62feb5)

PS：不是不愿意用，是因为我发现自己写的一个复杂的自定义组件，引进来后，h5 直接编译错误，希望能关掉这个转换操作，避免 h5 编译都出错，因为我不用。

**Comment by xjh123x** [comment]
我也遇到了这个问题，期望官方回复。

**Comment by vortesnail** [comment]
相似问题：https://ask.dcloud.net.cn/question/159200

**Comment by yurj26** [comment]
后续会修复，组件转换失败不会影响编译。
临时解决方案：替换 [文件](https://github.com/dcloudio/uni-app/blob/dev/packages/vue-cli-plugin-uni/lib/env.js) 到 `HBuilderX根目录/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-uni/lib`。

**Comment by yurj26** [comment]
> 后续会修复，组件转换失败不会影响后续编译。 临时解决方案：替换 [文件](https://github.com/dcloudio/uni-app/blob/dev/packages/vue-cli-plugin-uni/lib/env.js) 到 `HBuilderX根目录/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-uni/lib`。

HBuilderX 3.93.2023101913-alpha 已修复

**Comment by vortesnail** [comment]
> > 后续会修复，组件转换失败不会影响后续编译。 临时解决方案：替换 [文件](https://github.com/dcloudio/uni-app/blob/dev/packages/vue-cli-plugin-uni/lib/env.js) 到 `HBuilderX根目录/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-uni/lib`。
> 
> HBuilderX 3.93.2023101913-alpha 已修复

![image](https://github.com/dcloudio/uni-app/assets/18679842/324e8c46-72b1-4f8e-b10e-3713abfb811d)

没生效似乎
