### ISSUE TITLE
如果到时候 Vue Function-based API 出了的话，uni-app 是否会支持?

### ISSUE THREAD

**Issue by jamieYou** [dcloudio/uni-app#456]
这篇文章提到了 vue 3.0 的新 api
https://zhuanlan.zhihu.com/p/68477600

这个 api 把数据和方法的声明都放在了 setup 函数里，而 setup 函数是在组件实例被创建时调用的。
从小程序的角度来看，也就是说在声明组件时，是无法知道 data 有什么，有什么方法存在。只有在组件实例化的时候才能知道。这与小程序的 `Component` 方法的使用相违背。我感觉是无法在小程序里实现了。

**Comment by fxy060608** [comment]
小程序并不是必须在 data 中声明，可以动态设置新的 data 数据，不过这样可能需要考虑首次渲染的性能。

**Comment by fxy060608** [comment]
小程序的 data 不需要全部声明，可以动态设置，事件方法现在走的是代理，初步看来，实现应该问题不大，只是需要考虑到初始化数据的首次渲染性能

**Comment by jamieYou** [comment]
> 小程序的 data 不需要全部声明，可以动态设置，事件方法现在走的是代理，初步看来，实现应该问题不大，只是需要考虑到初始化数据的首次渲染性能

我见 taro 为了能在声明组件时即可获得初始数据，会在声明组件后就 new 一遍 class 获取 state，然后实例化组件时又得 new 一遍 class，感觉会让开发者困扰。

**Comment by fxy060608** [comment]
> > 小程序的 data 不需要全部声明，可以动态设置，事件方法现在走的是代理，初步看来，实现应该问题不大，只是需要考虑到初始化数据的首次渲染性能
> 
> 我见 taro 为了能在声明组件时即可获得初始数据，会在声明组件后就 new 一遍 class 获取 state，然后实例化组件时又得 new 一遍 class，感觉会让开发者困扰。

先 new 一次来获取确实会带来不小的困扰，可能会破坏开发者代码逻辑，持续跟进吧，也许到时候 vue3.0 及 小程序都有新的变化，可以解决这个问题

**Comment by jamieYou** [comment]
@fxy060608 还有一个问题，好像 `onShareAppMessage` 这类方法是要事先定义的吧，这个不能做代理吧，毕竟开发者不一定想让这个页面带分享功能

**Comment by fxy060608** [comment]
> @fxy060608 还有一个问题，好像 `onShareAppMessage` 这类方法是要事先定义的吧，这个不能做代理吧，毕竟开发者不一定想让这个页面带分享功能

新版本已处理过这个问题，cli 可以直接更新，HBuilderX 需要等 Alpha 2.0.1 以上版本

**Comment by fxy060608** [comment]
> @fxy060608 还有一个问题，好像 `onShareAppMessage` 这类方法是要事先定义的吧，这个不能做代理吧，毕竟开发者不一定想让这个页面带分享功能

麻烦一些的做法，可以编译器扫描当前代码及引用关系里，是否包含`onShareAppMessage`
