### ISSUE TITLE
现在支持鸿蒙开发吗

### ISSUE THREAD

**Issue by IchbinHurry** [dcloudio/uni-app#4565]
**新功能描述**
简洁描述你希望补充完善的增强功能

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by yurj26** [comment]
[https://ask.dcloud.net.cn/question/181493](https://ask.dcloud.net.cn/question/181493)
