### ISSUE TITLE
是否支持淘宝小程序？

### ISSUE THREAD

**Issue by wxf-start** [dcloudio/uni-app#4572]
**新功能描述**
兼容淘宝小程序

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by hbcui1984** [comment]
淘宝小程序和支付宝小程序是一样的，发行到支付宝小程序即可。

**Comment by Otto-J** [comment]
可以按照官网适配阿里系的钉钉小程序进行适配。 https://uniapp.dcloud.net.cn/collocation/package.html#%E7%A4%BA%E4%BE%8B-%E9%92%89%E9%92%89%E5%B0%8F%E7%A8%8B%E5%BA%8F

如果开发淘宝小程序过程中有技术问题，欢迎反馈
