### ISSUE TITLE
uni.chooseImage 裁剪图片失败

### ISSUE THREAD

**Issue by 1393037860** [dcloudio/uni-app#4576]
**问题描述**
[问题描述：在安卓/微信开发者工具中使用uni.chooseImage裁剪图片失败, crop参数已设置]

**复现步骤**
uni.chooseImage({
        count: 1,
        crop: { "width": 120, "height": 120, "resize": false },
        success: (res) => {}
})

**预期结果**
希望裁剪正常

**实际结果**
没有裁剪,直接上传了原图尺寸

**系统信息:**
 - 发行平台: [微信小程序]
 - 操作系统 [Android 11.0]
 - HBuilderX版本 [3.8.12.20230817]
 - uni-app版本 []
 - 设备信息 [如 小米11]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by nadirvishun** [comment]
我看文档中描述：
![image](https://github.com/dcloudio/uni-app/assets/5761981/4fd07f0c-92fe-48bd-a2b4-45d32f2d53b1)
确定适配小程序吗？还是仅仅app端生效？

**Comment by yurj26** [comment]
文档已说明仅app端支持。
