### ISSUE TITLE
最新版vue3+ts编译为H5后css样式最后一个样式总是缺少分号结尾

### ISSUE THREAD

**Issue by euwei7** [dcloudio/uni-app#4582]
**问题描述**

按照官网的安装步骤，执行了`npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project`, 安装依赖后编译为H5，查看编译后的css文件发现样式缺少结尾的分号。

**复现步骤**

1.  执行： `npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project.`
2. 执行：`npm i`
3. 执行：`npm build:h5`
4. 查看编译后的css文件

**预期结果**

有分号结尾

**实际结果**

<img width="651" alt="截屏2023-11-05 16 33 11" src="https://github.com/dcloudio/uni-app/assets/120472761/ec938ce4-8226-428c-90f2-7e4dcfe47221">

**系统信息:**
 - 发行平台:  H5平台

**Comment by lincenying** [comment]
css最后一个样式本来就可以不用分号, 所以不用纠结这个
