### ISSUE TITLE
微信小程序端和H5端处理组件引入外部资源产生冲突

### ISSUE THREAD

**Issue by zegui814** [dcloudio/uni-app#4585]
**问题描述**
将代码封装成Vue组件后，从外部传参进去，在组件内部引用静态资源。对于同样的资源在H5端和Web端引用路径出现冲突

**复现步骤**
[复现问题的步骤]
1. 拉取仓库 git clone https://gitee.com/qunje/wdpt-zwbb
2. 进入uniapp目录 cd Web/Hello uni-app
3. 使用HbuilderX打开并分别运行在H5端和微信小程序端

**预期结果**
封装组件后对外部资源的引用方式应该一致

**实际结果**
引用组件：
![image](https://github.com/dcloudio/uni-app/assets/108137214/3c51cc38-d5e7-4224-bdfb-d01a87427488)
组件内部细节：
![image](https://github.com/dcloudio/uni-app/assets/108137214/f1c53fe0-3e11-4aae-a5e8-d31bb93d636b)
H5端：
![image](https://github.com/dcloudio/uni-app/assets/108137214/bbd376d3-3b26-4b63-aa9d-e6ac0424386d)
微信小程序端：
![image](https://github.com/dcloudio/uni-app/assets/108137214/a8a3bfae-2c74-4c48-9c68-4ed8cd32b739)

**系统信息:**
 - 发行平台: 微信小程序、H5平台
 - 操作系统 win11
 - HBuilderX版本 v3.96
 - Hello uni-app版本 v3.4.4

**补充信息**
H5是从引用组件的地方出发引入资源，微信小程序是从组件内部出发引入资源

**Comment by xxhls** [comment]
git 签出版本 7abae9f2

**Comment by xxhls** [comment]
![image](https://github.com/dcloudio/uni-app/assets/108137214/b8ea0e02-ec96-48f4-b6f2-9f214ad1e9e3)
![image](https://github.com/dcloudio/uni-app/assets/108137214/0cc49849-16d5-452b-b823-9f150fb9c776)
使用”import“能临时解决这个问题
