### ISSUE TITLE
uni.createSelectorQuery is not a funciton 

### ISSUE THREAD

**Issue by satan31415** [dcloudio/uni-app#4587]
![9c4bf60c36ddb2d47157cf5f270d9ff](https://github.com/dcloudio/uni-app/assets/7278892/09124183-29eb-460c-b648-5c15bc0357eb)
这段代码, 在开发环境可以运行, 但是一自定义发行打 h5 平台, 就会报 uni.createSelectorQuery is not a funciton

有大佬帮忙看看什么原因吗

**Comment by shichaohui** [comment]
我也遇到这个问题，请问有解决吗？

**Comment by satan31415** [comment]
> 我也遇到这个问题，请问有解决吗？

我这边是因为h5的问题,  h5用不了这玩意

**Comment by satan31415** [comment]
> 我也遇到这个问题，请问有解决吗？

我这边感觉是微信开发者工具的问题, 上传代码上去就会这样, 多上传几次, 这个报错就莫名其妙好了

**Comment by satan31415** [comment]
本地开发不会, 我是只有正式环境才会,

**Comment by shichaohui** [comment]
h5 不能用这个接口？但是开发时在 h5 运行正常的呀，打包后运行才会报错，而且官方文档上也没写这个接口有兼容问题。

**Comment by satan31415** [comment]
多上传几次把, 我记得上次是加了个console.log, 然后上传, 然后就好了,

**Comment by satan31415** [comment]
> h5 不能用这个接口？但是开发时在 h5 运行正常的呀，打包后运行才会报错，而且官方文档上也没写这个接口有兼容问题。

多上传几次把, 我记得上次是加了个console.log, 然后上传, 然后就好了,

**Comment by shichaohui** [comment]
这么离谱，我试试看吧

**Comment by zhetengbiji** [comment]
参考一下这个信息是否有帮助： https://uniapp.dcloud.net.cn/tutorial/migration-to-vue3.html#h5-%E5%B9%B3%E5%8F%B0%E5%8F%91%E8%A1%8C%E6%97%B6-%E4%BC%9A%E9%BB%98%E8%AE%A4%E5%90%AF%E5%8A%A8%E6%91%87%E6%A0%91
