### ISSUE TITLE
开发小程序遇到一个极易出现的奇葩问题，找不到解决方案，请帮忙

### ISSUE THREAD

**Issue by algic** [dcloudio/uni-app#4588]
**问题描述**

以下是这个页面的代码，主要是v-for循环中写了重复的8个或以上相同的组件，且加了属性，就会在开发工具中出现“TypeError: up.split is not a function or its return value is not iterable”错误，某些组件的属性传值会异常。

```
<template>
  <view v-for="i in 1" :key="i">
    <comp test="1"></comp>
    <comp test="1"></comp>
    <comp test="1"></comp>
    <comp test="1"></comp>
    <comp test="1"></comp>
    <comp test="1"></comp>
    <comp test="1"></comp>
    <comp test="1"></comp>
  </view>
</template>
```

**复现步骤**
[复现问题的步骤]
只要使用以上模板的页面，应该就能爆出此错误，这应该是微信小程序环境的问题，但如果必须要这样使用组件，有什么办法绕过没？
组件写1个使用v-for复制8个没有问题，可实际功能中这个组件传递的属性和参数都不相同，不能通过循环生成。
这违反了小程序的什么规则？

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by algic** [comment]
看了下编译出来的wxml文件，发现问题原因是i in 1中的局部变量i，和编译出来的组件里的自动命名参数i冲突了，正好到第8个的参数i冲突了，编译生成的小程序模板如下，结束issue。
`<view wx:for="{{a}}" wx:for-item="item" wx:key="i">
    <comp wx:if="{{b}}" u-i="{{item.a}}" bind:__l="__l" u-p="{{b}}"></comp>
    <comp wx:if="{{c}}" u-i="{{item.b}}" bind:__l="__l" u-p="{{c}}"></comp>
    <comp wx:if="{{d}}" u-i="{{item.c}}" bind:__l="__l" u-p="{{d}}"></comp>
    <comp wx:if="{{e}}" u-i="{{item.d}}" bind:__l="__l" u-p="{{e}}"></comp>
    <comp wx:if="{{f}}" u-i="{{item.e}}" bind:__l="__l" u-p="{{f}}"></comp>
    <comp wx:if="{{g}}" u-i="{{item.f}}" bind:__l="__l" u-p="{{g}}"></comp>
    <comp wx:if="{{h}}" u-i="{{item.g}}" bind:__l="__l" u-p="{{h}}"></comp>
    <comp wx:if="{{i}}" u-i="{{item.h}}" bind:__l="__l" u-p="{{i}}"></comp>
</view>`

**Comment by chenzhe-pro** [comment]
也遇到了这个问题，亲测有效
