### ISSUE TITLE
关于动态获取权限的问题

### ISSUE THREAD

**Issue by jaydon007** [dcloudio/uni-app#46]
iOS端，当用户禁止APP调用相机权限之后，html5+没有判断是否成功调用相机的回调，Android端也是类似的问题。以前用mui解决这个需求是用了第三方的插件本地打包，uni-app就不知道怎么解决了，官方有没有具体的解决方案。

**Comment by wanganxp** [comment]
Native.js可以判断

**Comment by hbcui1984** [comment]
uni-app 最新版同样支持离线打包及原生SDK集成
