### ISSUE TITLE
picker普通模式selector-type自定义不生效

### ISSUE THREAD

**Issue by yangxun521** [dcloudio/uni-app#4600]
**问题描述**
picker普通模式selector-type自定义不生效

**复现步骤**
`<picker mode="selector" :range="examSub.list" range-key="subjectName" :value="examSub.subVal"
 @change="subChange" :selector-type="direction==='landscape' ? 'select' : 'auto'">
	<view>{{examSub.subName}}</view>
</picker>
`

`<picker mode="selector" :range="examSub.list" range-key="subjectName" :value="examSub.subVal"
 @change="subChange" selector-type="select">
	<view>{{examSub.subName}}</view>
</picker>
`
写死这个属性也不生效，但是在平板上确实自动切换成select模式了

**预期结果**
可以手动设置此属性

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 [ Android ]
 - HBuilderX版本 [3.9.6]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [谷歌浏览器手机模式，安卓小米手机自带浏览器]

**Comment by 18148764734** [comment]
并不是这个属性不生效，仔细阅读官方文档，picker在各平台的实现是有UI差异的，有的平台如百度、支付宝小程序的Android端是从中间弹出的；有的平台支持循环滚动如百度小程序；有的平台没有取消按钮如App-iOS端。但均不影响功能使用。

**Comment by yangxun521** [comment]
> 并不是这个属性不生效，仔细阅读官方文档，picker在各平台的实现是有UI差异的，有的平台如百度、支付宝小程序的Android端是从中间弹出的；有的平台支持循环滚动如百度小程序；有的平台没有取消按钮如App-iOS端。但均不影响功能使用。

> 官网文档是这样描述这个 `selector-type` 属性的：
大屏时UI类型，支持 picker、select、auto，默认在 iPad 以 picker 样式展示而在 PC 以 select 样式展示
[https://uniapp.dcloud.net.cn/component/picker.html](url)

他默认在手机上的展示样式是 `picker` ，如果我指定他展示样式为 `select` ，他应该随着我指定的值展示对应的UI效果吧，但是他还是展示默认的


我期望在h5中横屏浏览时，展示UI样式为 `select` ，而不是默认的 `picker` ，期望我的设置生效

**Comment by 18148764734** [comment]
注意看官方文档哦，对于selector-type的描述是：“大屏时UI类型”，这代表只有在大屏时，这个属性才可以自行设置

**Comment by 18148764734** [comment]
已更新回复

**Comment by yangxun521** [comment]
> 已更新回复

原来如此，我好像眼瞎了，抱歉
