### ISSUE TITLE
ios17 输入框键盘无法弹出

### ISSUE THREAD

**Issue by DUZHANGYI** [dcloudio/uni-app#4605]
**问题描述**
ios17上面输入框无法弹出键盘

**复现步骤**
<template>
  <view class="content">
    <image class="logo" src="/static/logo.png" />
    <view class="text-area">
     <input placeholder="aaaaaa"/>
    </view>
  </view>
</template>

**实际结果**
![b02437c7a6ea1aae4646aa4096aed6ec](https://github.com/dcloudio/uni-app/assets/52624444/f8f785a9-4a95-48ec-8249-2fef27c2eec0)

**系统信息:**
 - 发行平台: [ios App]
 - 操作系统 [如 iOS 17.0.1]
 - HBuilderX版本 [HBuilderX 3.96]
 - uni-app版本 [3.0.0-3081220230817001]
 - 设备信息 [iPhone15]

**Comment by Otto-J** [comment]
这个 issue 你关闭了，问题处理好了？可以把经验反馈过来
