### ISSUE TITLE
tabBar 的list 如不配置pages 数组中的第一个项，tabbar将不显示 

### ISSUE THREAD

**Issue by lemonig** [dcloudio/uni-app#4608]
**问题描述**
tabBar 的list 如不配置pages 数组中的第一个项，tabbar将不显示 

**复现步骤**
`"pages": [
		// pages数组中第一项表示应用启动页，参考：https://uniapp.dcloud.io/collocation/pages
		{
			"path": "pages/home/home",
			"style": {
				"navigationBarTitleText": "首页",
				"enablePullDownRefresh": false
			}
		},..]`

`
"tabBar": {
		"color": "#000",
		"selectedColor": "#fff",
		"borderStyle": "#fff",
		"backgroundColor": "#fff",
		"height": "50px",
		"list": [{
			"pagePath": "pages/test/test",
			"text": "测试"
		}, {
			"pagePath": "pages/blank/blank",
			"text": "测试"
		}]
	}
`

**预期结果**
期望list 里可以配置任意路径的page 项

**实际结果**
tabbar 不出现

**系统信息:**
 - 发行平台:H5
 - 操作系统 window chrome dev 模拟器
 - HBuilderX版本 X3.95
 - uni-app版本
 uni-app v3.95
uni-app cli v2.0.2-3090520231028001

Environment Info:

  System:
    OS: Windows 10
    CPU: (2) x64 Intel(R) Pentium(R) CPU G3260 @ 3.30GHz
  Binaries:
    Node: 16.13.1 - E:\devtol\nodeJS\node.EXE
    Yarn: 1.22.17 - E:\devtol\nodeJS\yarn.CMD
    npm: 8.1.2 - E:\devtol\nodeJS\npm.CMD
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
我觉得tabbar应该可以配置任意页面

**Comment by warmthsea** [comment]
https://zh.uniapp.dcloud.io/collocation/pages.html#tabbar

应该按照文档来

**Comment by 18148764734** [comment]
要仔细看官方文档哦，
pages数组的第一项是必须要配置的
pages list必须是至少要有两项以上
