### ISSUE TITLE
vue3 dev环境下uni-app内置组件的默认样式会覆盖掉app.vue全局样式

### ISSUE THREAD

**Issue by 321638914** [dcloudio/uni-app#4611]
**问题描述**
vue3 dev环境下uni-app内置组件自己的样式会覆盖掉app.vue内的全局样式，build打包后没问题。

**复现步骤**
https://stackblitz.com/~/github.com/321638914/uni3-css-test
app.vue内添加`image { width: 100%; height: 100% }`全局样式，但页面上的image标签仍会显示为320px*240px。

**预期结果**
内置组件样式会像vue2版那样正常被app.vue全局样式覆盖。

**实际结果**
app.vue内的`image { width: 100%; height: 100% }`被组件自带样式覆盖
![image](https://github.com/dcloudio/uni-app/assets/85913672/b4f5d2d8-8044-4a39-95a6-e17124ac36ca)
![image](https://github.com/dcloudio/uni-app/assets/85913672/1c90ff0c-ea73-4cc6-b46d-b45af013b9b9)

**系统信息:**
 - 发行平台: H5平台
 - 操作系统: Windows 11
 - HBuilderX版本: 无
 - uni-app版本: 3.0.0-3090620231104002
 - 设备信息: Windows 11

**补充信息**
https://github.com/vitejs/vite/issues/3924

**Comment by yurj26** [comment]
加下 !important
