### ISSUE TITLE
啥时候兼容华为鸿蒙元服务？

### ISSUE THREAD

**Issue by ichenglixue** [dcloudio/uni-app#4615]
华为鸿蒙开发者大会提出了将Uni-App小程序代码 编译为 华为鸿蒙元服务，想请教下，这个功能什么时候上线呢？

**Comment by ichenglixue** [comment]
没人回答吗？

**Comment by Otto-J** [comment]
https://github.com/dcloudio/uni-app/issues/4565 https://github.com/dcloudio/uni-app/issues/2481 https://github.com/dcloudio/uni-app/issues/4615

**Comment by ichenglixue** [comment]
> #4565

看 鸿蒙的发布会上说的，  UniApp  是会支持的。
