### ISSUE TITLE
bug:  Cannot assign to read only property 'push' of object '[object Array]'

### ISSUE THREAD

**Issue by Nick-QI** [dcloudio/uni-app#462]
**问题描述**
ios 浏览器内核下 真机调试,显示 只读文件,无法 push
`
var jsonpArray = global["webpackJsonp"] = global["webpackJsonp"] || [];

var oldJsonpFunction = jsonpArray.push.bind(jsonpArray);

 jsonpArray.push = webpackJsonpCallback;   // 该处在 ios 端,无法修改 push 方法.

 jsonpArray = jsonpArray.slice();

 for(var i = 0; i < jsonpArray.length; i++) webpackJsonpCallback(jsonpArray[i]);

 var parentJsonpFunction = oldJsonpFunction;
`
目前可以解决的方法:   Reflect.defineProperty(jsonpArray, 'push', {
writable: true
})
强行改写

目前期望的结果: 
       希望官方人员看到后能修改下源码

**Comment by bravekingzhang** [comment]
目测这个是iOS真机调试才有的问题，在Android手机上OK

**Comment by Nick-QI** [comment]
> 目测这个是iOS真机调试才有的问题，在Android手机上OK

是的
希望官方看到能修复下这个问题. 
uni-template-compiler 这个是没开源出来的.
我们有解决方案 也没办法给官方提交 pr

**Comment by zhetengbiji** [comment]
> 目测这个是iOS真机调试才有的问题，在Android手机上OK

你也是 cli 创建的项目吗？

**Comment by bravekingzhang** [comment]
我是用IDE创建的。没有用cli

**Comment by zhetengbiji** [comment]
> 我是用IDE创建的。没有用cli

HBuilderX 版本多少？

**Comment by bravekingzhang** [comment]
1.9.9.20190522

**Comment by zhetengbiji** [comment]
> 1.9.9.20190522

更新到 2.0 以上版本测试一下

**Comment by Nick-QI** [comment]
> > 1.9.9.20190522
> 
> 更新到 2.0 以上版本测试一下

目前已经没有这个 bug 了. 
我啥都没更改.
怀疑是微信官方 ide 的 bug. 真机调试的时候
