### ISSUE TITLE
vue3抖音小程序webrtc黑屏

### ISSUE THREAD

**Issue by vincent0202** [dcloudio/uni-app#4627]
**问题描述**
vue2是正常的，vue3下是黑屏

**复现步骤**
[uni-vertc-dy-v3.zip](https://github.com/dcloudio/uni-app/files/13612435/uni-vertc-dy-v3.zip)

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: 抖音小程序
 - 操作系统 Android 13
 - HBuilderX3.98
 - 设备信息 RMX3031

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by yurj26** [comment]
感谢反馈，临时解决方案：替换附件文件到`HBuilderX根目录/plugins/uniapp-cli-vite/node_modules/@dcloudio/uni-mp-toutiao/dist/`，然后重新编译。

[uni.compiler.js.zip](https://github.com/dcloudio/uni-app/files/13630612/uni.compiler.js.zip)

**Comment by yurj26** [comment]
> 感谢反馈，临时解决方案：替换附件文件到`HBuilderX根目录/plugins/uniapp-cli-vite/node_modules/@dcloudio/uni-mp-toutiao/dist/`，然后重新编译。
> 
> [uni.compiler.js.zip](https://github.com/dcloudio/uni-app/files/13630612/uni.compiler.js.zip)

4.0.2024012711-alpha 已修复
