### ISSUE TITLE
subNVue在按返回键时候会被关闭

### ISSUE THREAD

**Issue by huiliaoning** [dcloudio/uni-app#463]
**问题描述**
在live-pusher上面覆盖了3个subNVue窗体，但是只要点击空白处或者按下手机物理返回键subNVue窗体就会被关闭

**预期结果**
因为使用subNVue窗体时为了做一个直播的主播端页面，在live-pusher上面显示实时聊天信息，所以在按物理返回键的时候不希望关闭subNVue窗体

**实际结果**
subNVue窗体被关闭了

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 ：Android7.0
 - HBuilderX版本 [2.0.0]
 - 设备信息 [三星s8]

**Comment by fxy060608** [comment]
不要配置成 popup 类型，popup 类型是弹出模式，会响应关闭逻辑

**Comment by huiliaoning** [comment]
> 不要配置成 popup 类型，popup 类型是弹出模式，会响应关闭逻辑

配置成navigationBar后窗体无法透明了 而且窗体内容也不显示了  麻烦看一下

**Comment by fxy060608** [comment]
> > 不要配置成 popup 类型，popup 类型是弹出模式，会响应关闭逻辑
> 
> 配置成navigationBar后窗体无法透明了 而且窗体内容也不显示了 麻烦看一下
不配置 type 属性
