### ISSUE TITLE
我开发app，用webview跳转我的vue网页，能调用本机的蓝牙么？

### ISSUE THREAD

**Issue by bbhxwl** [dcloudio/uni-app#4635]
我webview的话，有权限调用本机的蓝牙设备么。

**Comment by 18148764734** [comment]
你自己的vue网页是什么平台的网页呢？如果是5+的话，可以直接调用5+的蓝牙接口https://www.html5plus.org/doc/zh_cn/bluetooth.html

**Comment by bbhxwl** [comment]
> 你自己的vue网页是什么平台的网页呢？如果是5+的话，可以直接调用5+的蓝牙接口https://www.html5plus.org/doc/zh_cn/bluetooth.html

就是普通vue自己创建的页面，用的nuxt框架。这个不行么。

**Comment by bbhxwl** [comment]
> 你自己的vue网页是什么平台的网页呢？如果是5+的话，可以直接调用5+的蓝牙接口https://www.html5plus.org/doc/zh_cn/bluetooth.html

5+是个什么概念，是uniapp 自己做的一个框架么？还是什么？

**Comment by 18148764734** [comment]
不好意思，我的询问的方式有误
科普一下：HTML5 Plus移动App，简称5+App,他是基于HTML,JS,CSS编写的运行在手机端的App，这种app可以直接调用通过我们封装好的JS API 去调用手机原生能力。
如果是普通vue的话，可以在 web-view 加载的 HTML 中调用 uni 的 蓝牙 API，需要在 你自己的HTML页面 中引用必要的 JS-SDK。
我们官方文档已经有基本API调用的官方示例
https://uniapp.dcloud.net.cn/component/web-view.html#web-view
当然你也可以具体参考以下这篇文章来实现
https://ask.dcloud.net.cn/article/35083

**Comment by bbhxwl** [comment]
> 不好意思，我的询问的方式有误 科普一下：HTML5 Plus移动App，简称5+App,他是基于HTML,JS,CSS编写的运行在手机端的App，这种app可以直接调用通过我们封装好的JS API 去调用手机原生能力。 如果是普通vue的话，可以在 web-view 加载的 HTML 中调用 uni 的 蓝牙 API，需要在 你自己的HTML页面 中引用必要的 JS-SDK。 我们官方文档已经有基本API调用的官方示例 https://uniapp.dcloud.net.cn/component/web-view.html#web-view 当然你也可以具体参考以下这篇文章来实现 https://ask.dcloud.net.cn/article/35083

我看过这个文档，我看是只能调用这几个api，没别的事呢，我实验也成功了，调用这几个基本的api
![image](https://github.com/dcloudio/uni-app/assets/26525599/2240a6b2-8cf0-47b2-b84b-ec657f537632)

**Comment by 18148764734** [comment]
是的，按照官方用postMessage传回信息给app，在app里面去调用蓝牙接口

**Comment by bbhxwl** [comment]
> 是的，按照官方用postMessage传回信息给app，在app里面去调用蓝牙接口

那和5+ 有什么关系？那不是没什么关系么，只能网页和app通讯，然后调用本机硬件的设备么？没有uniapp 封装好的简单方法么。

**Comment by 18148764734** [comment]
抱歉，上面是我的询问方式有误，如果是你自己的网页那就和5+没关系，第三方网页只能通过和APP的通讯来调取蓝牙接口

**Comment by 18148764734** [comment]
用uniapp来开发APP其实本质上就是用一个大web-view包裹起来并用这个web-view来显示，你在里面是可以直接通过plus调用5+的接口的。而你在这个app里面又嵌入你自己的第三方网页，其实就是子web-view，都同样是web-view,是可以直接通过plus去调用5+的接口的。

**Comment by bbhxwl** [comment]
> 用uniapp来开发APP其实本质上就是用一个大web-view包裹起来并用这个web-view来显示，你在里面是可以直接通过plus调用5+的接口的。而你在这个app里面又嵌入你自己的第三方网页，其实就是子web-view，都同样是web-view,是可以直接通过plus去调用5+的接口的。 至于我说的上面那种通过网页和app通讯的方式虽然也可以实现，但是不仅麻烦，而且这种方式效率会变得很低，因为他要走一条更长的链路。

我有点乱了呢，我现在自己新建的vue项目网站，嵌入uniapp里面，到底能不能用plus调用蓝牙呢，还是必须用postmessage 。uniapp没什么交流的地方呢，官方群基本没人说话了。

**Comment by 18148764734** [comment]
是可以直接用plus调用蓝牙的，除了官方群，uniapp有一个问答社区https://ask.dcloud.net.cn/explore/可以交流
