### ISSUE TITLE
在5+app环境下图像处理库“jimp”后，程序崩溃

### ISSUE THREAD

**Issue by oldpotter** [dcloudio/uni-app#464]
**问题描述**
通过npm安装了jimp,在web浏览器中运行正常，但是在android真机或者模拟器下运行5+app都报错崩溃

**复现步骤**
运行到手机或者模拟器

**实际结果**
出现了 page[pages/XXX/XXX] not found.May be caused by :1. Forgot to add page route in app.json.2. Invoking Page() in async task.

**系统信息:**
 - 发行平台: [5+ App等]

**Comment by zhetengbiji** [comment]
如果H5运行正常，小程序、App端运行报错，可能是使用了不支持的dom、bom等API。

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
