### ISSUE TITLE
运行为 H5 时内联 animation 样式不生效

### ISSUE THREAD

**Issue by obhasqr** [dcloudio/uni-app#4642]
**问题描述**
在内联样式中写的 animation 不生效，使用 class 选择器指定可以正常生效

**复现步骤**
1. 给控件加一个内联 animation 样式
2. 运行到浏览器

测试代码
```Vue
<template>
    <view>
        <view style="animation: scroll linear 4s alternate infinite;" class="testView">test1111</view>
    </view>
</template>

<script setup>
</script>


<style>
@keyframes scroll {
    0% {
        left: 0;
        transform: translateX(0);
    }

    100% {
        left: 100%;
        transform: translateX(-100%);
    }
}

.testView {
    border: 1px solid #ff0000;
    width: fit-content;
    /* animation: scroll linear 4s alternate infinite; */
}
</style>
```

**预期结果**
动画正常播放

**实际结果**
动画不生效

**系统信息:**
 - 发行平台: H5平台
 - HBuilderX版本: 3.99.2023121601-alpha

**补充信息**
运行到微信小程序正常

**Comment by yurj26** [comment]
感谢反馈，这是Vue框架的一个问题，开启style scoped后在内联样式中定义的关键动画不生效。在uni-app h5端中，为了隔离页面间的样式默认启用了scoped，从而导致了此问题，目前已向Vue团队反馈 https://github.com/vuejs/core/issues/9935 ，你可以把动画定义在class中绕过此问题。

**Comment by obhasqr** [comment]
好的，issue状态需要改变吗？

**Comment by yurj26** [comment]
参考下https://github.com/vuejs/core/issues/9935#issuecomment-1872528503 ，这是预期的，由于开启了style scoped，动画名称会在编译时添加scoped id，而内联样式可能包含来自任意地方的动态值，无法动态去添加scoped id，所以vue框架和uni-app框架都无法处理此问题。
