### ISSUE TITLE
关于APP需要对TCP支持的建议

### ISSUE THREAD

**Issue by WsProgrammer** [dcloudio/uni-app#4647]
在这个物联网的时代，智能终端随处可见，号称全平台开发的uniapp的APP竟然不支持TCP通讯协议，完全想不明白官方的想法，关于TCP协议的支持我看了下社区已经被开发者提了很多年啦，官方始终不予支持，这个问题我相信困扰了智能设备APP开发者很久啦，有理由怀疑插件市场那几个付费的TCP插件，应该是官方自己开发卖钱的。。。。

**Comment by tanjy888** [comment]
啥时候用到这种场景，怎么说呢？我准备用uniapp vue3版本开发短视频app，需要拉起抖音，应该问题不大吧。

**Comment by WsProgrammer** [comment]
典型的场景，在无网络的情况下，智能设备可以开通热点，手机直连设备后在局域网内进行调试设备工作，这些都是建立在TCP的基础上的




抽天子令群雄
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dcloudio/uni-app"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月27日(星期三) 中午11:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] 关于APP需要对TCP支持的建议 (Issue #4647)





 
啥时候用到这种场景，怎么说呢？我准备用uniapp vue3版本开发短视频app，需要拉起抖音，应该问题不大吧。

**Comment by Arcaneing** [comment]
需求合理，但我觉得没必要这么吐槽官方。
为嵌入式设备实现一个简易的http服务应该不会占用多少内存。
更多的时候我们开发智能设备会 基于蓝牙和mqtt，对于离线场景我们通常会使用esp32添置一个简易的mqtt服务，并与在线服务中继。

**Comment by Otto-J** [comment]
same #2432
