### ISSUE TITLE
如何全局监听屏幕点击？

### ISSUE THREAD

**Issue by yiluzhang** [dcloudio/uni-app#4648]
我正在做一个看板 APP，需要在指定时间内无操作时回到首页。请问如何在全局监听屏幕点击事件？

**Comment by 18148764734** [comment]
第一种方式：
利用vue-inset-loader在根节点挂载一个全屏包裹的全局view组件
https://blog.csdn.net/m0_46362378/article/details/134429205
并setTImeout，每次点击时重置计时器，计时结束时则返回首页。
第二种方式：
利用render.js的方式操作dom节点添加点击事件监听
`document.addEventListener('touchstart', function(e) {})`
计时器的设置方法同上，都是类似于防抖的思想来实现。
以上两种方式实测可以实现你的需求，如果需要，我可以提供两种方式的DEMO。
