### ISSUE TITLE
failed to load config from D:\HBuilderX\plugins\uniapp-cli-vite\vite.config.js error when starting dev server:

### ISSUE THREAD

**Issue by sishen654** [dcloudio/uni-app#4654]
我新建的 Vue3 模板运行都报错，是最新更新导致的吗

![image](https://github.com/dcloudio/uni-app/assets/65691266/77c826c9-8006-4d01-8cee-dd7ffb35c51c)

**Comment by Otto-J** [comment]
感谢反馈。

问题定位：
看报错是 cli 安装的 esbuild 和 hbuilderx 内置的 esbuild 不兼容，你可能是苹果芯片的电脑。

解决方案：
这个问题已知，临时解决思路见这里 https://ask.dcloud.net.cn/question/145281

后续处理好这个问题，会进行更新。

**Comment by sishen654** [comment]
> 感谢反馈。
> 
> 问题定位： 看报错是 cli 安装的 esbuild 和 hbuilderx 内置的 esbuild 不兼容，你可能是苹果芯片的电脑。推测是在 cli 中安装了 node_moduels，在 hbuiderx 中启动。
> 
> 解决方案： 这个问题已知。可以使用内置 node，或者临时解决思路见这里 https://ask.dcloud.net.cn/question/145281
> 
> 后续处理好这个问题，会进行更新。

解决了，我解决方法是重新装 Hbuilder，然后重新下载依赖。
出现原因好像是我在下载依赖的同时更新，导致更新完成后下载的包有问题吧

**Comment by Otto-J** [comment]
> > 感谢反馈。
> > 问题定位： 看报错是 cli 安装的 esbuild 和 hbuilderx 内置的 esbuild 不兼容，你可能是苹果芯片的电脑。推测是在 cli 中安装了 node_moduels，在 hbuiderx 中启动。
> > 解决方案： 这个问题已知。可以使用内置 node，或者临时解决思路见这里 https://ask.dcloud.net.cn/question/145281
> > 后续处理好这个问题，会进行更新。
> 
> 解决了，我解决方法是重新装 Hbuilder，然后重新下载依赖。 出现原因好像是我在下载依赖的同时更新，导致更新完成后下载的包有问题吧

这是一个有趣的问题。因为 hbuiderx 内置了一个 node 兼容没有 node 的用户，和系统的 node 不同。我现在补充一篇文章，稍等贴在这里。

**Comment by Otto-J** [comment]
你可以帮我验证这个方案吗。

1. 你是 m1/m2/m3 苹果新品的 mac 电脑
2. 使用 `npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project` 下载 vue3+ts 模版
3. 使用 npm/yarn/pnpm 安装依赖
4. 拖进 hbuiderx 点击运行 h5, 这里大概率会失败
5. 打开 hbuiderx 设置 - 运行设置，到最后两行，找到 内置、外置 node，选择 外置 node
6. 打开终端输入 `where npm` 和 `where node` 把返回值放到下面输入框中
7. 重启 hbuiderx，重新运行 h5 这里应该正常了。

你能帮我验证吗


![image](https://github.com/dcloudio/uni-app/assets/9958583/ab6494ee-9882-4d36-be7f-f2312d8f9e86)

**Comment by sishen654** [comment]
> 你可以帮我验证这个方案吗。
> 
> 1. 你是 m1/m2/m3 苹果新品的 mac 电脑
> 2. 使用 `npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project` 下载 vue3+ts 模版
> 3. 使用 npm/yarn/pnpm 安装依赖
> 4. 拖进 hbuiderx 点击运行 h5, 这里大概率会失败
> 5. 打开 hbuiderx 设置 - 运行设置，到最后两行，找到 内置、外置 node，选择 外置 node
> 6. 打开终端输入 `where npm` 和 `where node` 把返回值放到下面输入框中
> 7. 重启 hbuiderx，重新运行 h5 这里应该正常了。
> 
> 你能帮我验证吗
> 
> ![image](https://private-user-images.githubusercontent.com/9958583/294080073-ab6494ee-9882-4d36-be7f-f2312d8f9e86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNDA0MTUsIm5iZiI6MTcwNDM0MDExNSwicGF0aCI6Ii85OTU4NTgzLzI5NDA4MDA3My1hYjY0OTRlZS05ODgyLTRkMzYtYmU3Zi1mMjMxMmQ4ZjllODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDRUMDM0ODM1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZjgwNzY5NDViMmQ0MDE0ZDY1OWIzYmE0MjZkZGNkMTFjODlhNzA0MjNkZDYwMDY5YTI5ZWY1NjlmZjEyYzc3MSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.JrGtg_kqPaNjqR1oBfl9ydN-ZFhVVT9k6yeTrfrNXWM)

windows😂

**Comment by Otto-J** [comment]
没关系，按照我提供的试一试

**Comment by Otto-J** [comment]
or you can add my wechat : xinbao965 ， i nedd your feedback.

**Comment by sishen654** [comment]
> 4\. 拖进 hbuiderx 点击运行 h5, 这里大概率会失败

到第四步就成功了

**Comment by sishen654** [comment]
> > 4. 拖进 hbuiderx 点击运行 h5, 这里大概率会失败
> 
> 到第四步就成功了



> > 4. 拖进 hbuiderx 点击运行 h5, 这里大概率会失败
> 
> 到第四步就成功了

windows

**Comment by Otto-J** [comment]
好，如果再遇到这个问题，请继续和我沟通，感谢你的反馈

**Comment by guizimo** [comment]
> 你可以帮我验证这个方案吗。
> 
> 1. ~你是 m1/m2/m3 苹果芯片的 mac 电脑~
> 2. 使用 `npx degit dcloudio/uni-preset-vue#vite-ts my-vue3-project` 下载 vue3+ts 模版
> 3. 使用 npm/yarn/pnpm 安装依赖
> 4. 拖进 hbuiderx 点击运行 h5, 这里大概率会失败
> 5. 打开 hbuiderx 设置 - 运行设置，到最后两行，找到 内置、外置 node，选择 外置 node
> 6. 打开终端输入 `where npm` 和 `where node` 把返回值放到下面输入框中，看我截图
> 7. 重启 hbuiderx
> 8. 重新运行 h5 。这里应该正常了。
> 
> 你能帮我验证吗
> 
> ![image](https://private-user-images.githubusercontent.com/9958583/294080073-ab6494ee-9882-4d36-be7f-f2312d8f9e86.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODQ3MzgsIm5iZiI6MTcxNDM4NDQzOCwicGF0aCI6Ii85OTU4NTgzLzI5NDA4MDA3My1hYjY0OTRlZS05ODgyLTRkMzYtYmU3Zi1mMjMxMmQ4ZjllODYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjlUMDk1MzU4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9N2M4OWQ5ZjQ0MTAxMDVhNDkyZDBmZjJjODE2MmNhYjAxMGIyYjViYjY4YThmNGE0ZDI4ODI0NjVkZTQ0MmM0NCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.AIPDOWKrhCUeAplssJz40xfjLPH7KWlxFWa9aR-Aa8U)

我是M1 Pro，照着这个步骤尝试了一下，确实是恢复正常了。👍
