### ISSUE TITLE
can i use vuetify with uni-app?

### ISSUE THREAD

**Issue by jinan5694** [dcloudio/uni-app#4655]
**新功能描述**
简洁描述你希望补充完善的增强功能

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by Otto-J** [comment]
感谢反馈。

如果 uni-app 运行在 h5 环境，和普通 web 项目无异，这个时候，你可以选择 vuetify 。

如果你需要运行在小程序环境，需要自行测试判断，因为微信小程序不同于浏览器环境，可能会有兼容问题，需要自行兼容和处理。你也可以搜索 vuetify+uniapp 搜索是否有相似选型方案。

uniapp 官方推荐使用 [uni-ui](https://uniapp.dcloud.net.cn/component/uniui/uni-ui.html) ，这个 UI 库是官方维护并且经过测试验证，供你参考。
