### ISSUE TITLE
vite vue3的uniapp，打包h5后怎么修改目录结构，只打包h5，不用考虑别的平台

### ISSUE THREAD

**Issue by moumunn** [dcloudio/uni-app#4657]
**问题描述**
vite vue3执行npm run build后产生的dist目录结构为
![100028](https://github.com/dcloudio/uni-app/assets/77449729/2f853d8b-9dbd-4112-9a0c-5c0ef6500a24)
希望他变成
![100117](https://github.com/dcloudio/uni-app/assets/77449729/42f1ce89-7654-424b-acc5-bf25c849333b)
怎么配置生成路径呢，去掉build/h5这层，直接保留static，只考虑h5平台，不用考虑别的平台

**Comment by Otto-J** [comment]
感谢反馈，这个 build/h5 是怎么来的？我使用 https://gitcode.net/xiurensha5731/uni-app-questions/-/tree/main 这个基础案例，构建之后发现只有 assets 和 static 目录，和你的有什么区别，能在这个 demo 的基础上补充更多信息让我复现问题吗？

**Comment by moumunn** [comment]
不好意思不好意思，代码没贴全，是我在vite.config.js中配置了build.rollupOptions.output.dir为'./dist'，然后build后的目录结构就是issues里的第一个截图了，我就想给他去掉build/h5这层目录，
如果不在vite.config.js中配置build的话输出的目录是 dist/build/h5/xxx，如果这样的话可以去掉 build/h5 这层目录吗，就是把assets、static、index.html这三个文件直接放在 dist 下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月2日(星期二) 下午3:31
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dcloudio/uni-app] vite vue3的uniapp，打包h5后怎么修改目录结构，只打包h5，不用考虑别的平台 (Issue #4657)





 
感谢反馈，这个 build/h5 是怎么来的？我使用 https://gitcode.net/xiurensha5731/uni-app-questions/-/tree/main 这个基础案例，构建之后发现只有 assets 和 static 目录，和你的有什么区别，能在这个 demo 的基础上补充更多信息让我复现问题吗？

**Comment by Otto-J** [comment]
调整了 build.rollupOptions.output.dir为'./dist' 造成这个奇怪的原因，我觉得调整后更奇怪了。看后面的补充，我理解你的目标是想拿掉 dist/build/h5/xx ，改成 dist/xx。

后面这个方案更直接一点，不用考虑打包过程中相对路径的问题。你可以补充一个 npm script ，在执行完 npm run build:h5 之后执行，

```bash
mv dist/build/h5/ dist2 && rm -rf dist && mv dist2 dist
```

这样可以么？

**Comment by moumunn** [comment]
是在scripts里面单独加一条配置吗
"copy": "mv dist/build/h5/ dist2 &amp;&amp; rm -rf dist &amp;&amp; mv dist2 dist"
还是在"build:h5" 本身修改
"build:h5": "uni build mv dist/build/h5/ dist2 &amp;&amp; rm -rf dist &amp;&amp; mv dist2 dist"
第一个copy报错mv不是命令，第二个build之后还是跟原目录一样没变化



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月2日(星期二) 下午3:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dcloudio/uni-app] vite vue3的uniapp，打包h5后怎么修改目录结构，只打包h5，不用考虑别的平台 (Issue #4657)





 
调整了 build.rollupOptions.output.dir为'./dist' 造成这个奇怪的原因，我觉得调整后更奇怪了。看后面的补充，我理解你的目标是想拿掉 dist/build/h5/xx ，改成 dist/xx。
 
后面这个方案更直接一点，不用考虑打包过程中相对路径的问题。你可以补充一个 npm script ，在执行完 npm run build:h5 之后执行，
 mv dist/build/h5/ dist2 &amp;&amp; rm -rf dist &amp;&amp; mv dist2 dist
 
这样可以么？

**Comment by Otto-J** [comment]
我提供的是 Linux 命令，可能你是 `windows` ，试试这个 `move dist\build\h5\ dist2 && rmdir /s /q dist && move dist2 dist` ，如果你有 cicd 流程，记得切换在。

大概是这样
```json
{
"copy":"move xxx"
"build":"npm run build:h5 && npm run copy"
}
```

**Comment by moumunn** [comment]
可以了可以了，感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月2日(星期二) 晚上6:01
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dcloudio/uni-app] vite vue3的uniapp，打包h5后怎么修改目录结构，只打包h5，不用考虑别的平台 (Issue #4657)





 
我提供的是 Linux 命令，可能你是 windows ，试试这个 move dist\build\h5\ dist2 &amp;&amp; rmdir /s /q dist &amp;&amp; move dist2 dist ，如果你有 cicd 流程，记得切换在。
 
大概是这样
 { "copy":"move xxx" "build":"npm run build:h5 &amp;&amp; npm run copy" }
