### ISSUE TITLE
typescript 的@dcloudio/types 中没有onNavigationBarButtonTap和onBackPress的定义

### ISSUE THREAD

**Issue by SilasDong** [dcloudio/uni-app#466]

**Comment by zhetengbiji** [comment]
已更新

**Comment by SilasDong** [comment]
/**
         * 监听原生标题栏搜索输入框搜索事件，用户点击软键盘上的“搜索”按钮时触发。
         */
        onNavigationBarSearchInputConfirmed?(): any;
        /**
         * 监听原生标题栏搜索输入框点击事件
         */
        onNavigationBarSearchInputClicked?(): any;

这两个方法应该有一个参数吧

**Comment by zhetengbiji** [comment]
> /**
> * 监听原生标题栏搜索输入框搜索事件，用户点击软键盘上的“搜索”按钮时触发。
> _/ onNavigationBarSearchInputConfirmed?(): any; /_*
> * 监听原生标题栏搜索输入框点击事件
> */
> onNavigationBarSearchInputClicked?(): any;
> 
> 这两个方法应该有一个参数吧

onNavigationBarSearchInputConfirmed 是有的，已修正
