### ISSUE TITLE
导致编译巨慢的隐形BUG

### ISSUE THREAD

**Issue by ilxqx** [dcloudio/uni-app#4661]
**问题描述**
因为引用一个组件，导致编译巨卡巨慢，具体看复现Demo

**复现步骤**
复现代码和说明：https://github.com/ilxqx/uniapp-bug-demo

**预期结果**
不影响编译速度

**实际结果**
导致编译速度巨慢

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 MacOS13.6.3
 - HBuilderX版本 vue3-vite-cli
 - uni-app版本 node: v20.10.0  npm: 10.2.3

**Comment by yurj26** [comment]
4.0.2024012711-alpha 已修复
