### ISSUE TITLE
跨自定义组件的后代选择器（>>>）app 和 h5 使用报错

### ISSUE THREAD

**Issue by obhasqr** [dcloudio/uni-app#4663]
**问题描述**
按照文档说明使用跨自定义组件的后代选择器 `>>>` 时运行到 app 和 h5 会报错，微信小程序运行正常
![image](https://github.com/dcloudio/uni-app/assets/5682731/c3f16d7e-5585-4466-9183-e4f19b751694)
文档：[https://uniapp.dcloud.net.cn/api/ui/nodes-info.html#selectorquery-select](https://uniapp.dcloud.net.cn/api/ui/nodes-info.html#selectorquery-select)

**复现步骤**
```Javascript
const query = uni.createSelectorQuery()
query.select('.pagefull >>> .' + aid).boundingClientRect()
query.exec((res) => { /* code */ })
```

**预期结果**
可以正常使用

**实际结果**
运行报错

**系统信息:**
 - HBuilderX版本：3.99
 - Vue 3

**Comment by obhasqr** [comment]
代码和你们自己的文档链接都贴出来了还要什么复现方式？

**Comment by Otto-J** [comment]
你是对的，经过测试，uni-app h5 未实现跨组件后代选择器，也就是 `>>>` 。尝试简单地替换 `>>>` 为空不妥当，需要更大范围的支持，文档中后续进行标注适用范围。

推荐你使用普通的空格 后代选择器进行测试，如果你有好的实现方案，欢迎贡献 PR 或者提供改进意见。

**Comment by Otto-J** [comment]
vue3+h5，the source code is here:
https://github.com/dcloudio/uni-app/blob/next/packages/uni-h5/src/service/api/ui/requestComponentInfo.ts

搜索 `function getNodesInfo(` 可以看到对应的实现逻辑
