### ISSUE TITLE
vue3环境下，uni.setTabbarItem动态设置pagePath失效

### ISSUE THREAD

**Issue by FreeCodersix** [dcloudio/uni-app#4664]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
命令行创建的项目，vue3版本，根据用户角色使用uni.setTabbarItem动态设置pagePath，然后使用switchTab跳转报错
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
成功跳转
**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://github.com/dcloudio/uni-app/assets/33892855/974b2491-edfa-4508-9dc3-30a4f0bf37c1)
跳转失败

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 Android 13
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Otto-J** [comment]
感谢反馈。你想同台设置 tabItem 的 pagePath，这个在微信小程序中不支持，微信不提供这个 api。

 uni-app 文档提示了 h5/app 支持该功能。

文档链接
https://uniapp.dcloud.net.cn/api/ui/tabbar.html#settabbaritem

微信文档，没有对应参数。
https://developers.weixin.qq.com/miniprogram/dev/api/ui/tab-bar/wx.setTabBarItem.html

微信小程序社区
https://developers.weixin.qq.com/community/search?query=setTabBarItem%2520%25E9%25A1%25B5%25E9%259D%25A2%25E8%25B7%25AF%25E5%25BE%2584&page=1&block=1&random=1704439001539&type=1

**Comment by FreeCodersix** [comment]
那如果想实现动态tabbar该如何操作呢

**Comment by Otto-J** [comment]
绕过方案可以考虑，页面内进行组件判断。页面 > 页面 1 组件 + 页面 2组件。也可以搜索 小程序 动态 tabbar 找到其他方案，供你参考。
