### ISSUE TITLE
子页面更新 store 触发了父页面的updated

### ISSUE THREAD

**Issue by jinan5694** [dcloudio/uni-app#4667]
**问题描述**
前提：在 store 中共享了一个 list 数据

**复现步骤**
1. list 页面使用 store 中的数据渲染列表，点击 item 跳转到 detail 页面（uni.navigateTo）并把 id 传到 detail 页面。

2. detail 页面在 onload 中获取 id，之后按 id 到store中获取完整item 对象。赋值到detail页面的 data中。
```js
this.item = Object.assign({}, this.item, itemFindFromStoreById)
```
3. detail 页面修改信息后，更新 store

```js
this.$set(storeList, indexOfCurrentId, this.item)
```
4. 这时 list 页面的updated 执行了。（预先写了log）

**预期结果**
父页面跳转到子页面是，子页面是新创建的。
子页面返回时，（子页面会销毁，执行unload 方法），之后，执行父页面的onshow方法。

请问，这时父页面只是被隐藏了，依旧会在后台更新视图，还是一个意外的执行结果？

应该怎么理解这种行为呢？
是否可以合理的利用这种机制来实现一些数据回更的场景？
将来是否会调整这种机制？

复现仓库

https://github.com/jinan5694/uni-issue-4667

**Comment by Otto-J** [comment]
感谢反馈，看你的描述不清楚你的问题。
请补充：你是 cli 还是 hbuiderx 运行？是 vue2 还是 vue3? 运行在哪个平台上？ list 页面是怎么监听的 store?

请提供一个可复现的案例，方便定位你的问题

**Comment by jinan5694** [comment]
@Otto-J 复现仓库已更新在正文

**Comment by jinan5694** [comment]
感谢您的反馈！

在确认一个问题。保活的页面是在后台渲染的吧？例如当前这个场景。updated 触发说明页面已经完成渲染。只是在后台暂时看不到。当返回页面就可以直接看到渲染后的内容。而不需要再等待他渲染。另外，如果触发更新的比较多，也会导致页面切换的卡顿。

是这样吗？

**Comment by Otto-J** [comment]
不太理解你的使用场景。两个页面都存在，应该是不受影响的，如果你有使用场景，可以写个 demo 试一试，也期待你的反馈。
