### ISSUE TITLE
v-if使用问题

### ISSUE THREAD

**Issue by hbbaly** [dcloudio/uni-app#467]
**问题描述**
1.在支付宝小程序中使用 v-if="(item||[]).length或者,v-if="typeof item === 'string'"没有问题，
2.在微信中使用上例中的代码会报错

**复现步骤**
代码： 
![image](https://user-images.githubusercontent.com/34227573/59490600-b3e80f00-8eb7-11e9-8a6e-f8ad1e2d8d22.png)

**预期结果**
可以向支付宝小程序环境那样正常运行

**实际结果**
报错示意图：

![image](https://user-images.githubusercontent.com/34227573/59490508-75eaeb00-8eb7-11e9-9b43-e93f4c4b63d8.png)

**系统信息:**
 - 发行平台:  微信小程序
 - HBuilderX版本 2.0.1.20190614
 - 设备信息 [如 iPhone6]

**补充信息**
通过computed解决的
![image](https://user-images.githubusercontent.com/34227573/59490901-628c4f80-8eb8-11e9-8758-b3e742adcd1f.png)

**Comment by hbcui1984** [comment]
这是微信小程序原生的限制，跟框架无关。

你使用如下原生代码测试，在微信开发者工具中直接编译报错：

`
<view wx:if="{{typeof age == 'number'}}">
    条件显示
  </view>
`
