### ISSUE TITLE
click点击事件问题

### ISSUE THREAD

**Issue by hbbaly** [dcloudio/uni-app#468]
**问题描述**
在支付宝小程序中这么使用代码 @click="chooseV !== index && choose(item, index) 不会有报错，正常运行。
2. 微信环境中会出现点击事件不生效，并且没有任何提示语

**复现步骤**
![image](https://user-images.githubusercontent.com/34227573/59491362-23123300-8eb9-11e9-856e-527a4deacfd8.png)

**预期结果**
希望能够正常使用

**实际结果**
点击事件不生效

**系统信息:**
 - 发行平台:  微信小程序
 -   微信开发工具
 - HBuilderX版本 2.0.1.20190614
 - 设备信息 [如 iPhone6]

**补充信息**

**Comment by fxy060608** [comment]
建议，将 chooseV 传入 choose 函数中，做判断
这样的写法属于复杂表达式，即使可以支持，对性能也会有些影响

**Comment by hbbaly** [comment]
> 建议，将 chooseV 传入 choose 函数中，做判断
> 这样的写法属于复杂表达式，即使可以支持，对性能也会有些影响

支付宝小程序可以这样，而且支付宝小程序也上线了，把写支付宝小程序代码编译微信小程序，好多地方都要改。

**Comment by zhetengbiji** [comment]
96443deec87a2734b367a35fec0ab101c431fbc6
