### ISSUE TITLE
近期会新增小程序jsx的支持吗

### ISSUE THREAD

**Issue by weikangqq** [dcloudio/uni-app#4682]
**新功能描述**
简洁描述你希望补充完善的增强功能
新增小程序jsx的支持
**现状及问题**
[当前现状及由此导致的不便]
新增小程序jsx的支持
**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]
新增小程序jsx的支持
**补充信息**
[其它你认为有参考价值的信息]
新增小程序jsx的支持

**Comment by Otto-J** [comment]
same #4683
