### ISSUE TITLE
新增小程序jsx的支持

### ISSUE THREAD

**Issue by weikangqq** [dcloudio/uni-app#4683]
**新功能描述**
简洁描述你希望补充完善的增强功能
新增小程序jsx的支持
**现状及问题**
[当前现状及由此导致的不便]
新增小程序jsx的支持
**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]
新增小程序jsx的支持
**补充信息**
[其它你认为有参考价值的信息]
新增小程序jsx的支持

**Comment by Otto-J** [comment]
这是一个非常好的问题，后续会尝试把这个问题整理为文章。

现状：目前 uni-app 目前是支持使用 jsx/tsx 编写代码运行到 h5/app 上，只是不支持小程序平台。

这个问题的结论是：这个问题的答案是 `no_planned`

为什么不规划？
在 github issue/ ask 社区中应该有过相似的讨论，后续做一些链接索引。因为小程序平台运行的不是完整的 es2016 运行环境，也不是完整的浏览器环境。小程本身有自己的 html 规范，和 vue template 非常相似，即使使用 jsx 编写组件，也需要编译成 `wx:if`  `wx:for` 这种语法，比如三木运算符、array.map 等需要进行转化，工作量巨大，也无法 100% 兼容 jsx 写法，无法在编译时做更多性能优化的工作，用户也会带来更多未覆盖到的边缘问题。

使用 vue template 写法就相对容易可控，而且目前开发和问题修复的经验比较成熟。后续基于 vue template 继续兼容新的小程序平台、app 的经验可以复用到 uni-app-x 的开发中去。

**Comment by alamhubb** [comment]
开了个坑，让uniapp的小程序端支持渲染函数了，

https://github.com/alamhubb/uni-render

实现原理

https://github.com/alamhubb/uni-render/blob/main/TechnicalImplementation.md


相关文章

https://zhuanlan.zhihu.com/p/1994149291560813794


vue的jsx是基于渲染函数的，所以准备顺便支持下jsx
