### ISSUE TITLE
uniapp vue项目支持打包为鸿蒙.hap格式应用吗

### ISSUE THREAD

**Issue by yinjiazeng** [dcloudio/uni-app#4688]
纯鸿蒙快上线了，看了官网说未来uniappX会适配鸿蒙，但是我们有很多uniapp vue开发的项目，一套代码多端，这些项目全部用uniappX开发一遍难度挺大的，能否支持vue项目打包为纯鸿蒙应用。

**Comment by Otto-J** [comment]
#4565 #2481 #4615 

具体进展在这里沟通 https://ask.dcloud.net.cn/question/181493
