### ISSUE TITLE
uni.getLocation(OBJECT)成功回调adress

### ISSUE THREAD

**Issue by vlijiantao** [dcloudio/uni-app#469]
**新功能描述**
uni.getLocation(OBJECT)成功回调后address能不能把行政区域代码也带上。

**现状及问题**
现在需要行政区域代码调用uni.getLocation(OBJECT)后我还得根据address里的省市县去调下高德地图的api去获取下行政区域代码，既然都有省市县信息了把行政区域代码也公布出来。

**尝试方案**
既然都有省市县信息了把行政区域代码也公布出来

**补充信息**

**Comment by vlijiantao** [comment]
期待有回复。

**Comment by dcloudhdx** [comment]
已支持，需要传参数 geocode (默认false，是否解析地址信息)，[文档](https://uniapp.dcloud.io/api/location/location?id=getlocation)

**Comment by shuaqq2004** [comment]
@dcloudhdx  还没有支持， address 对象里面缺少区域编码。

目前 address对象只有cityCode， 没有adCode ， 
高德地图和百度地图 的API里面均支持 adCode 行政区域编码的字段。

**Comment by buchipingguo** [comment]
急切需要adCode
