### ISSUE TITLE
uni-datetime-picker 建议暴露 弹窗弹出 收起的事件

### ISSUE THREAD

**Issue by TryChai** [dcloudio/uni-app#4694]
**新功能描述**
uni-datetime-picker 能暴露弹窗弹出收起的事件 ，最好能把弹窗挂到最外层

**现状及问题**
层级问题 
![image](https://github.com/dcloudio/uni-app/assets/30064871/f6fc9d90-d617-4d7c-982d-79629f7e0437)
其他的定位层没法 

**尝试方案**
暴露弹出 收起的方法

**补充信息**
[其它你认为有参考价值的信息]

**Comment by Otto-J** [comment]
感谢反馈。

后续uni-ui 问题可以去 uni-ui 仓库 https://github.com/dcloudio/uni-ui 进行反馈。
cc @18148764734 你可以看看

**Comment by 18148764734** [comment]
感谢反馈，后续添加则会在此回复

**Comment by 18148764734** [comment]
已添加弹出事件:open
收起事件为maskClick,不再考虑添加close
弹窗目前z-index层级为99，用户可根据该值设置自己的组件
