### ISSUE TITLE
有什么办法能够绕过uni-app封装层调用到更多的h5地图的能力？

### ISSUE THREAD

**Issue by wangzz** [dcloudio/uni-app#4698]
目前uni-app只封装了有限的h5地图能力，如果希望调用腾讯地图h5版的更多地图能力，有什么可行的方式吗？

之前给了下面两种建议方式：

![image](https://github.com/dcloudio/uni-app/assets/2884882/5614f208-ab85-4fb7-8f8e-6c38231bacaa)

我们想基于uni-app去开发在h5和微信小程序中运行的业务，所以目前只能走第1种方式。要想绕过uni-app封装层去调用更多的h5地图能力，需要获取到h5的地图实例。通过看uni-app map组件的源码发现，获取到的地图实例是经过封装过的，并不是厂商提供的原始地图实例，因此没法自己去封装能力，我看到的map组件代码在这里： [this._maps = result](https://github.com/dcloudio/uni-app/blob/930c6d04bc26067ed5f7b8a1e782ad43760509fd/src/platforms/h5/view/components/map/index.vue#L220)。

请问uniapp类似下面腾讯地图官方demo里的创建底图实例的代码在哪个地方？如果能找到这个地方的源码我们就能基于此继续按第1钟思路自行进行能力扩展
https://lbs.qq.com/webDemoCenter/glAPI/glMap/createMap
![image](https://github.com/dcloudio/uni-app/assets/2884882/69dfe4c9-aa0d-48f0-99ea-716723af3616)

希望能够指导下🙏🏻

**Comment by zhetengbiji** [comment]
希望你回继续回原来的issue下补充讨论，不要一个一个的新开。

**Comment by wangzz** [comment]
之前的issues已经被关闭，并且在后边讨论等了很久没有任何人回复
https://github.com/dcloudio/uni-app/issues/4668

如果会回复，我也不希望重新开个issue

**Comment by Otto-J** [comment]
更多讨论请移步。
 https://github.com/dcloudio/uni-app/issues/4668#issuecomment-1911443924

本问题和 #4668 一样，不再进行更多讨论。
