### ISSUE TITLE
支持抖音小程序新增能力

### ISSUE THREAD

**Issue by chaoranwill** [dcloudio/uni-app#4699]
**新功能描述**
1. 支持配置抖音小程序数据预取能力 https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/guide/experience-optimization/list/data-preload

2. getSystemInfoSync 、getSystemInfo useCache 参数使用支持：https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/api/device/system-information/tt-get-system-info-sync/

3. Fragment 组件节点 https://developer.open-douyin.com/docs/resource/zh-CN/mini-app/develop/framework/custom-component/component-model-and-style/#7417c627

**现状及问题**
开发成本增加，无法接入有效的优化能力如数据预取

**Comment by yurj26** [comment]
1. 把相关配置定义在`manifest.json`文件的`mp-toutiao`里，会自动同步到`app.json`文件中
2. 直接使用即可，`uni.getSystemInfoSync(true)` 或 `uni.getSystemInfo({useCache: true})`
3. 后续会支持

**Comment by yurj26** [comment]
问题3下个版本会支持，临时解决方案：

1. vue2 项目替换 [文件](https://github.com/dcloudio/uni-app/blob/dev/packages/uni-mp-toutiao/dist/index.js) 到 `HBuilderX根目录/plugins/uniapp-cli/node_modules/@dcloudio/uni-mp-toutiao/dist/`
vue3 项目替换 [文件](https://github.com/dcloudio/uni-app/blob/next/packages/uni-mp-toutiao/dist/uni.mp.esm.js) 到 `HBuilderX根目录/plugins/uniapp-cli-vite/node_modules/@dcloudio/uni-mp-toutiao/dist/`

2. 在组件中添加 `virtualHost` 属性，具体可以参考 [文档](https://uniapp.dcloud.net.cn/tutorial/vue-api.html#%E5%85%B6%E4%BB%96%E9%85%8D%E7%BD%AE)
```
export default {
  data(){ return { } },
  options: {
    virtualHost: true
  }
}
```

**Comment by yurj26** [comment]
请升级到最新版，已支持。
