### ISSUE TITLE
关于组件slot

### ISSUE THREAD

**Issue by cgxqd123** [dcloudio/uni-app#47]
官方文档说不支持slot的写法，为什么我写slot，有效果呢，是不是官方更新了，文档没有更新的呢？？

**Comment by hulinNeil** [comment]
slot不支持加scoped，其他的已经支持了

**Comment by zengqingsong** [comment]
最新版本HX对Slot支持非常不稳定，前几天编译还好好的程序，今天编译界面全部显示不了，就是slot部分莫名其妙的不显示，但是查看代码有生成。不知道是不是姿势不对。

**Comment by zengqingsong** [comment]
删除HX重新安装就好了，不知是啥原因。

**Comment by hbcui1984** [comment]
> 上

最好提供一些实例代码，核心代码片段即可

**Comment by hbcui1984** [comment]
> slot里面嵌套封装的组件的时候，被封装的组件app上不渲染，H5可以

最好提供一些实例代码，核心代码片段即可

**Comment by my3188** [comment]
官方自己的组件uni-collapse  uni-collapse-item  你试试就知道，用一个[name:xx,list:[{age:2,color:'red'’}]]
list本应该要渲染到 uni-collapse-item里面  根本就不渲染，他们的论坛好多人问题，就是没个回应

**Comment by zhetengbiji** [comment]
[uni-app新老编译模式差异说明](https://ask.dcloud.net.cn/article/35843)
