### ISSUE TITLE
app中，input focus后如何关闭弹出键盘

### ISSUE THREAD

**Issue by hjj5258** [dcloudio/uni-app#470]
**新功能描述**
简洁描述你希望补充完善的增强功能
希望能解决input对焦后，不弹出键盘。
**现状及问题**
[当前现状及由此导致的不便]
触摸屏：扫码查询
需要自动对焦不触发唤醒键盘。
**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]
尝试了@focus后，使用uni.hideKeyboard()方法
**补充信息**
[其它你认为有参考价值的信息]

**Comment by zhetengbiji** [comment]
你到底是想隐藏键盘还是想显示键盘？

**Comment by hjj5258** [comment]
> 你到底是想隐藏键盘还是想显示键盘？

可以使用input焦点，但不显示键盘。

**Comment by zhetengbiji** [comment]
> > 你到底是想隐藏键盘还是想显示键盘？
> 
> 可以使用input焦点，但不显示键盘。

这个不可以，你可以尝试禁用input，自己绘制光标，或者完全使用view模拟

**Comment by hjj5258** [comment]
> > > 你到底是想隐藏键盘还是想显示键盘？
> > 
> > 
> > 可以使用input焦点，但不显示键盘。
> 
> 这个不可以，你可以尝试禁用input，自己绘制光标，或者完全使用view模拟

感谢

**Comment by zhao-hw** [comment]
> > 你到底是想隐藏键盘还是想显示键盘？
> 
> 可以使用input焦点，但不显示键盘。

请问最后是怎么解决的？我是要用扫码枪，但有焦点才能拿到扫描结果，又不想有键盘被唤醒
