### ISSUE TITLE
向组件传递变量问题

### ISSUE THREAD

**Issue by hbbaly** [dcloudio/uni-app#471]
**问题描述**
在支付宝小程序环境中，传递变量可以 这样`:data-arr="scrollXData"`，
但是在微信小程序环境，会导致组件内`接受不到`从父组件传递过来的变量

**复现步骤**
[复现问题的步骤]

![image](https://user-images.githubusercontent.com/34227573/59501331-e270e480-8ecd-11e9-8667-a6437d63c57a.png)

**预期结果**
能否支持data开头的变量传递

**实际结果**

**系统信息:**
 发行平台: 微信小程序
微信开发工具
HBuilderX版本 2.0.1.20190614
设备信息 [如 iPhone6]

**补充信息**

**Comment by fxy060608** [comment]
data-开头的数据，属于节点 dataset，不属于 props ，在事件中通过 event.currentTarget.dataset 获取

**Comment by hbbaly** [comment]
> data-开头的数据，属于节点 dataset，不属于 props ，在事件中通过 event.currentTarget.dataset 获取

是应该这样，但是不知道为什么支付宝小程序可以
