### ISSUE TITLE
我需要自定义 cli 命令，我该怎么办

### ISSUE THREAD

**Issue by hlovingness** [dcloudio/uni-app#4718]
我司需要把uniapp项目集成到自己的cli命令里面，比如 tbl dev，然后在里面增加一些功能，来代替 uni 命令，我是否可以再基础上封装一层，不知道能不能提供下思路，我只需要单封装uni命令替换为 tbl 命令

**Comment by Otto-J** [comment]
从你的描述看，你是希望封装 uni 实现，参数透传：比如启动微信小程序 dev 模式 `uni -p mp-weixin`，比如打包微信小程序 `uni build -p mp-weixin` ，这里你可以在自己的 cli args 参数中进行透传，最终使用 exec 来执行 uni 的逻辑。

比如 `tbl dev` 你可以在 tbl 的 bin 逻辑中，解析参数为 `dev`，动态拼写逻辑，伪代码：

```js
var args = ['dev']
if(args[0]==='dev']){
  var cmd = 'uni -p weixin'
// exec
}
```

具体的细节需要你结合实际场景补充完善。
