### ISSUE TITLE
input组件的blur事件在使用v-for循环的时候会被重复触发

### ISSUE THREAD

**Issue by jaycezhang789** [dcloudio/uni-app#4727]
**问题描述**
使用ipnut组件的时候，blur事件会被重复触发

**复现步骤**
<img width="865" alt="截屏2024-02-10 02 08 01" src="https://github.com/dcloudio/uni-app/assets/88314265/efff86f3-2cb6-40b8-a336-7b470e6260a7">

**预期结果**
预期是输入完成，输入框失焦的时候触发一次。但是实际在连续输入的时候，每输入一个字符，就会触发一次，每次输入都会触发多次blur事件。同时如果绑定focus事件，focus事件也会被触发多次。
（如果不加focus属性，会在输入一个字符后立刻失焦）

**实际结果**
<img width="801" alt="截屏2024-02-10 02 11 18" src="https://github.com/dcloudio/uni-app/assets/88314265/ed3c86b2-5396-4c40-8855-def8bdd3f090">
原本文字是测试1，连续输入12345678，加上实际应该blur的那一次，总共触发9次blur事件。

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本  ：HBuilderX 3.99
 - 设备信息 ：iPhone8

**补充信息**
（已知是和item.title有关， 如果直接定义title=ref('')，直接绑定title，则blur触发正常）

**Comment by wangjinxin613** [comment]
是因为key的问题，key换成:key="index"就好了，key设置成item.tiitle的话，每次输入新内容都会导致key发生变化，key变化导致组件重新渲染了，所以每次输入都会触发blur事件
