### ISSUE TITLE
uniapp在企业微信的浏览器测试各种不兼容 访问下一个界面内存丢失

### ISSUE THREAD

**Issue by lozn00** [dcloudio/uni-app#4737]
**问题描述**

uniapp 企业微信中的网页版有很多问题，
1.用api重启到某个界面后，我点返回会发现并没有关闭之前退出登录的界面，

2. 在首页刷新或者点击进入一个界面再退回来会发现内存中的东西丢失了，也就是说取数据不能像微信那样从内存变量中取。

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 iphone 15pro  ios 17.2.1 企业微信 4.1.20
 - 
 - HBuilder 3.99
 vue3 vite

**Comment by zhetengbiji** [comment]
你说的“内存”比较模糊，可以以具体代码举例一下

**Comment by Otto-J** [comment]
我看了你的描述，提到了页面刷新，在企业微信中展示页面时候和浏览器 h5表现一致，刷新后需要自行维护用户状态，比如后端提供用户状态，前端自行存储状态，解决刷新的问题。

从你的描述看，不清楚具体问题，如果上面提供的方案不满足你的要求，请提供具体复现代码，有助于理解和复现定位你的问题。

**Comment by Otto-J** [comment]
请提供复现工程吧，补充具体的复现步骤。我不太清楚你遇到的具体问题。

**Comment by bfc846958672** [comment]
长时间未响应，关闭本issue。 如还有问题，可 reopen issue 继续讨论。
