### ISSUE TITLE
主包加载了分包的js文件，导致 vendor.js 过大

### ISSUE THREAD

**Issue by francyfrees** [dcloudio/uni-app#4746]
**问题描述**
![image](https://github.com/dcloudio/uni-app/assets/33947113/0a02369c-95e4-4250-87ee-36db5c565c03)
![image](https://github.com/dcloudio/uni-app/assets/33947113/0a841e0c-4617-4229-a326-35489eb55fea)
![image](https://github.com/dcloudio/uni-app/assets/33947113/c6b2fb73-0941-49d1-88b8-716e29b9cd6b)

问：
utils.js  不应该在分包里边吗？

**Comment by magicalTom** [comment]
怎么解决的
