### ISSUE TITLE
支付宝小程序slot内嵌套循环失效

### ISSUE THREAD

**Issue by xlfsummer** [dcloudio/uni-app#476]
**问题描述**
支付宝小程序slot内嵌套循环失效

**复现步骤**
1.  使用 cli 创建一个默认模板
2. 创建一个简单的组件，包含`<slot/>`
3. 在 index 页面引用组件，在组件标签内写一个嵌套的 v-for
4. `npm run dev:mp-alipay` 编译到支付宝平台，通过支付宝小程序工具打开

index.vue
```html
<template>
  <simple-wrapper>
    <view v-for="ia in nestList" :key="ia.name">
      <view>{{ia.name}}</view>
      <view v-for="ib in ia.value" :key="ib">-{{ib}}</view>
    </view>
  </simple-wrapper>
</template>

<script>
  import SimpleWrapper from "../../components/simpleWrapper.vue";
  export default {
    components: {
      SimpleWrapper
    },
    data() {
      return {
        nestList: [
          {name: "a", value: ["a1", "a2"]},
          {name: "b", value: ["b1", "b2"]}
        ]
      }
    }
  }
</script>
```
SimpleWrapper.vue
```html
<template>
  <view>
    <slot />
  </view>
</template>

<script>
export default {
}
</script>
```

**环境配置**
未使用自定义组件编译模式

**预期结果**
显示出 a a1, a2, b, b1, b2

**实际结果**
仅显示出 a b
![image](https://user-images.githubusercontent.com/20750969/59586158-cf9c2100-9114-11e9-8b99-f51371a453a6.png)

**示例仓库**
https://github.com/xlfsummer/demo-alipay-component-loop-issue

**Comment by robin901118** [comment]
https://uniapp.dcloud.io/use?id=vue-%E7%BB%84%E4%BB%B6
文档有说明：组件里使用 slot 嵌套的其他组件时不支持 v-for
