### ISSUE TITLE
jest在vue3的cli模式下，测试h5失败

### ISSUE THREAD

**Issue by qinains** [dcloudio/uni-app#4766]
**问题描述**
jest在cli模式下，测试h5失败

**复现步骤**
[复现问题的步骤]
项目代码在这里[jest_test_project.zip](https://github.com/dcloudio/uni-app/files/14539199/jest_test_project.zip)
解压，然后进入项目目录中，执行
```
pnpm i
pnpm run test:h5
```
然后项目一直显示
![image](https://github.com/dcloudio/uni-app/assets/528630/18caa6ec-d133-4f96-b1ee-42e3b2dfa739)

**预期结果**
期望代码能够执行下，显示出测试结果

**实际结果**
卡主了，代码执行不下去

**系统信息:**
 - 发行平台:  H5平台
 - 操作系统：Windows11
 - uni-app版本：通过`npx degit dcloudio/uni-preset-vue#vite my-vue3-project`创建

**补充信息**
浏览器端抛出以下错误，可能是ws链接不上的问题
![image](https://github.com/dcloudio/uni-app/assets/528630/2a3a201b-ed16-43bf-b40d-3581da4e8348)

**Comment by wangjinxin613** [comment]
可以看看是否开启防火墙或者代理、vpn之类的，关掉试试，如果还不行，检查一下9520端口是否开启

**Comment by qinains** [comment]
没有开启防火墙或者代理、vpn之类的，运行`pnpm exec uni --auto-port 9520`，再把jest.config.js的testEnvironmentOptions -> h5 -> url 注释掉，就可以运行。

**Comment by wangjinxin613** [comment]
> 没有开启防火墙或者代理、vpn之类的，运行`pnpm exec uni --auto-port 9520`，再配置jest.config.js的testEnvironmentOptions -> h5 -> url 为对应的URL和端口号，就可以运行。 @wangjinxin613

运行正常吗？

**Comment by qinains** [comment]
运行正常
