### ISSUE TITLE
性能：只是想问一下，对webgl的支持这么样。

### ISSUE THREAD

**Issue by DevSoft2016** [dcloudio/uni-app#477]
**新功能描述**
提高渲染性能
**现状及问题**
半只脚入门也不敢说什么问题。只是感觉这个可以有。
但是技术难道太高。先插个眼吧。

**尝试方案**
木的好办法

**补充信息**
[其它你认为有参考价值的信息]

**Comment by zhetengbiji** [comment]
未内置封装，在H5端你可以直接使用其API或者引入其他类库，其他端不支持。
