### ISSUE TITLE
video后续支持字幕么

### ISSUE THREAD

**Issue by pitilesszgw** [dcloudio/uni-app#4777]
目前在app上运行video，其他功能都满足，目前就是需要用到srt字幕，有什么好的方法么，不行的话只能用原生封装成插件调用了

**Comment by bfc846958672** [comment]
目前在app端没有支持字幕的计划。暂时只能通过原生插件或uts插件进行外挂字幕

**Comment by chenweiliang6** [comment]
大佬，有封装好的原生插件能分享分享吗

**Comment by chenweiliang6** [comment]
> 目前在app端没有支持字幕的计划。暂时只能通过原生插件或uts插件进行外挂字幕

那有什么现成的插件可以用来切换mkv的字幕和音轨的吗
