### ISSUE TITLE
ios softinput 全局设置无效

### ISSUE THREAD

**Issue by magicwing** [dcloudio/uni-app#478]
**问题描述**
ios 5+app 设置全局软键盘模式 manifest.json => app-plus => softinput => mode => adjustResize 没有效果
但是，在设置单个页面 pages.json => app-plus => softinputMode => adjustResize 是有效的

**复现步骤**
**预期结果**
**实际结果**

**系统信息:**
 - 发行平台: 5+App (ios)
 - 操作系统 ios 12.3.1
 - HBuilderX版本 2.0.0.20190610
 - uni-app版本 同上
 - 设备信息 iPhone6s

**补充信息**

**Comment by mehaotian** [comment]
安卓支持manifest配置，iOS不支持
