### ISSUE TITLE
移动端video如何播放本地m3u8文件

### ISSUE THREAD

**Issue by pitilesszgw** [dcloudio/uni-app#4784]
移动端video如何播放本地m3u8文件，目前文档上只支持网络m3u8，本地的m3u8是否后续可以支持，或者通过格式转换其他方法实现。

**Comment by bfc846958672** [comment]
逻辑上是可以支持的，需要自行保证本地m3u8的索引文件能访问的本地的m3u8视频切片。 建议用工具将m3u8文件转其他常见视频格式mp4，avi，mkv等

**Comment by bfc846958672** [comment]
长时间未响应，关闭本issue。 如还有问题，可 reopen issue 继续讨论。
