### ISSUE TITLE
可视化创建的项目，怎么总报错啊 

### ISSUE THREAD

**Issue by chergn** [dcloudio/uni-app#4786]
![image](https://github.com/dcloudio/hello-uniapp/assets/43592730/fb015e4c-cbf8-4955-b817-628fff776352)

然后npm安装了一些插件：
![image](https://github.com/dcloudio/hello-uniapp/assets/43592730/4c584bfe-7c87-468c-a037-42595293f8bf)

能正常运行，但是时不时的，没规律，就偶尔报错：
![image](https://github.com/dcloudio/hello-uniapp/assets/43592730/3714f90e-99e1-43be-a822-21f16d7aa8b0)

一报错我就：
![image](https://github.com/dcloudio/hello-uniapp/assets/43592730/c312f749-4e49-4ead-aa2f-7968d1168c96)

**Comment by bfc846958672** [comment]
可以使用脚手架cli进行创建，或者最新版本的hbuilderX构建 [环境安装文档](https://uniapp.dcloud.net.cn/quickstart-cli.html#install-vue-cli)

**Comment by bfc846958672** [comment]
长时间未响应，关闭本issue。 如还有问题，可 reopen issue 继续讨论。
