### ISSUE TITLE
cli模式下manifest.json中部分字段没有编译

### ISSUE THREAD

**Issue by weiyunpeng** [dcloudio/uni-app#479]
**问题描述**
使用cli命令进行小程序编译，manifest.json中的mp-weixin -> permission字段没有编译。在编译后的app.json中并没有permission字段

**预期结果**
manifest.json的mp-weixin增加permission字段后可以编译到app.json中

**Comment by zhetengbiji** [comment]
测试未复现该问题，你更新依赖试试

**Comment by weiyunpeng** [comment]
> 测试未复现该问题，你更新依赖试试

@dcloudio/uni-mp-weixin 0.0.964
@dcloudio/uni-template-compiler 0.9.179
@dcloudio/webpack-uni-mp-loader 0.3.630
@dcloudio/webpack-uni-pages-loader 0.2.846

运行命令：`cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch`

manifest.json中：`"mp-weixin": {
    "setting": {
      "urlCheck": true
    },
    "usingComponents": true,
    "permission": {
      "scope.userLocation": {
        "desc": "你的位置信息将用于获取位置"
      }
    }
  }`

编译后的dev->mp-weixin->app.json中依然没有`"permission": {
      "scope.userLocation": {
        "desc": "你的位置信息将用于获取位置"
      }
    }`

**Comment by zhetengbiji** [comment]
> > 测试未复现该问题，你更新依赖试试
> 
> @dcloudio/uni-mp-weixin 0.0.964
> @dcloudio/uni-template-compiler 0.9.179
> @dcloudio/webpack-uni-mp-loader 0.3.630
> @dcloudio/webpack-uni-pages-loader 0.2.846
> 
> 运行命令：`cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch`
> 
> manifest.json中：`"mp-weixin": { "setting": { "urlCheck": true }, "usingComponents": true, "permission": { "scope.userLocation": { "desc": "你的位置信息将用于获取位置" } } }`
> 
> 编译后的dev->mp-weixin->app.json中依然没有`"permission": { "scope.userLocation": { "desc": "你的位置信息将用于获取位置" } }`

你使用 cli 创建一个空工程测试一下

**Comment by weiyunpeng** [comment]
> > > 测试未复现该问题，你更新依赖试试
> > 
> > 
> > @dcloudio/uni-mp-weixin 0.0.964
> > @dcloudio/uni-template-compiler 0.9.179
> > @dcloudio/webpack-uni-mp-loader 0.3.630
> > @dcloudio/webpack-uni-pages-loader 0.2.846
> > 运行命令：`cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch`
> > manifest.json中：`"mp-weixin": { "setting": { "urlCheck": true }, "usingComponents": true, "permission": { "scope.userLocation": { "desc": "你的位置信息将用于获取位置" } } }`
> > 编译后的dev->mp-weixin->app.json中依然没有`"permission": { "scope.userLocation": { "desc": "你的位置信息将用于获取位置" } }`
> 
> 你使用 cli 创建一个空工程测试一下

空工程也是这情况，编译后的app.json中没有permission内容

**Comment by weiyunpeng** [comment]
执行`cross-env NODE_ENV=production UNI_PLATFORM=mp-weixin vue-cli-service uni-build` 或者 `cross-env NODE_ENV=development UNI_PLATFORM=mp-weixin vue-cli-service uni-build --watch` 。


在`manifest.json`中加入`permission` 以及 `navigateToMiniProgramAppIdList`字段，都无法编译到`app.json`中

**Comment by zhetengbiji** [comment]
上传一下你的测试工程（请删除node_modules目录，保留package-lock.json）

**Comment by weiyunpeng** [comment]
[test.zip](https://github.com/dcloudio/uni-app/files/3372148/test.zip)

**Comment by zhetengbiji** [comment]
> test.zip

此工程无法运行，缺少太多的依赖。
另外此工程没有package-lock.json，无法保证和你的测试环境一致。另外你之前所说的空工程也有问题，你的空工程是指的使用cli新建的默认工程么，如果不是的话，测试一下，如果是的话，把这个工程发来。

**Comment by weiyunpeng** [comment]
我用的是yarn  生成的是yarn.lock

**Comment by zhetengbiji** [comment]
> 我用的是yarn 生成的是yarn.lock

好的，你之前所说空工程也有问题，你的空工程是指的使用cli新建的默认工程么，如果不是的话，测试一下，如果是的话，把这个工程发来。

**Comment by weiyunpeng** [comment]
找到原因了， 你试着在最外层目录增加一个`project.config.json`文件

**Comment by fxy060608** [comment]
编译器发现目录有 project.config.json 时，会以 project.config.json 为主，不再启用 manifest.json 相关配置

**Comment by weiyunpeng** [comment]
> 编译器发现目录有 project.config.json 时，会以 project.config.json 为主，不再启用 manifest.json 相关配置

manifest.json中配置的内容与 project.config.json的内容并没有关系的。
而实际需求上单配project.config.json会多一些。

**Comment by fxy060608** [comment]
> > 编译器发现目录有 project.config.json 时，会以 project.config.json 为主，不再启用 manifest.json 相关配置
> 
> manifest.json中配置的内容与 project.config.json的内容并没有关系的。
> 而实际需求上单配project.config.json会多一些。

npm update,已修复存在 project.config.js 时，manifest.json 部分配置未同步至 app.json 的问题

**Comment by weiyunpeng** [comment]
> > > 编译器发现目录有 project.config.json 时，会以 project.config.json 为主，不再启用 manifest.json 相关配置
> > 
> > 
> > manifest.json中配置的内容与 project.config.json的内容并没有关系的。
> > 而实际需求上单配project.config.json会多一些。
> 
> npm update,已修复存在 project.config.json 时，manifest.json 部分配置未同步至 app.json 的问题

可以了，谢谢
