### ISSUE TITLE
不是bug

### ISSUE THREAD

**Issue by 2846781956** [dcloudio/uni-app#4796]
我想知道uniapp的基础组件有开源吗？想学习一下源码。具体在哪个目录？

**Comment by zhetengbiji** [comment]
有，目录结构可以看一下贡献指南的介绍。

**Comment by 2846781956** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你的邮件已收到。

**Comment by 2846781956** [comment]
这是来自QQ邮箱的自动回复邮件。你好，你的邮件已收到。
