### ISSUE TITLE
uni.switchTab 跳转之后tabbar不见了

### ISSUE THREAD

**Issue by Treblex** [dcloudio/uni-app#480]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
当B（tabbar页面）下当子页面，跳转到A（tabber页面）时，tabbar消失了
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by YouMaster930615** [comment]
没有人来维护么

**Comment by zhetengbiji** [comment]
请把问题补充详细

**Comment by zhetengbiji** [comment]
> 没有人来维护么

如有同类问题，也请具体说明，请勿灌水

**Comment by Treblex** [comment]
很详细了  比如说我的用户中心下跳转一个子页面   然后使用relanch或者swichtab返回，之后用户中心是正常的，跳转到其他到tabar页面都没有tabbar显示   有时间我发个demo

**Comment by Treblex** [comment]
> **问题描述**
> [问题描述：尽可能简洁清晰地把问题描述清楚]
> 当B（tabbar页面）下当子页面，跳转到A（tabber页面）时，tabbar消失了
> **复现步骤**
> [复现问题的步骤]
> 
> 1. 启动 '...'
> 2. 点击  '....'
> 3. 查看
> 
> [或者可以直接贴源代码]
> 
> **预期结果**
> [使用简洁清晰的语言描述你希望生效的预期结果]
> 
> **实际结果**
> [这里请贴上你的报错截图或文字]
> 
> **系统信息:**
> 
> * 发行平台: [如 微信小程序、H5平台、5+ App等]
> * 操作系统 [如 iOS 12.1.2、Android 7.0]
> * HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
> * uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
> * 设备信息 [如 iPhone8 Plus]
> 
> **补充信息**
> [可选]
> [根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Treblex** [comment]
新建了demo没有复现  只在我到项目里出现了    我排查一下问题先
