### ISSUE TITLE
input type=text Error

### ISSUE THREAD

**Issue by 07ke** [dcloudio/uni-app#4800]
https://github.com/dcloudio/uni-app/blob/983c17993ea244ef39835eaf47edf16b9a592b49/packages/uni-components/src/vue/input/index.tsx#L28C4-L48C7

input type=text。computed判断有问题。渲染永远为空。ios无法输入中文。

![image](https://github.com/dcloudio/uni-app/assets/17754548/ca375053-c35a-494e-b2b4-9c4151b9ac42)

**Comment by zhetengbiji** [comment]
详细描述一下
