### ISSUE TITLE
input组件封装成模板后用form组件的submit方法在微信小程序上无法获取到值

### ISSUE THREAD

**Issue by robin901118** [dcloudio/uni-app#481]
**问题描述**
我有一个input组件做成了自定义的component,然后引入页面中用form组件包裹，触发form组件的submit事件在微信小程序上无法获取到component里面input的值。如果把input组件抽离component单独放到form组件下是可以获取到的。只在微信小程序上复现，支付宝小程序上是正常可以获取到的。代码如下：

``` 
//page

<form @submit="loginSubmit">
   <myInput inputName="password"></myInput>
   <button formType="submit">登录</button>
</form>

<script>
import myInput from "../../components/myInput/myInput.vue";
export default {
	components: {myInput},
	methods: {
		/* 登录表单提交 */
		loginSubmit(e){
			console.log(e);   // 正常打印，但是e.detail.value为空对象
			console.log('form发生了submit事件，携带数据为：' + JSON.stringify(e.detail.value))
                 }
	}
}
</script>

````

``` 
//component

<template name="myInput">
	<label class="label">
		<input type="text" :name="inputName" :password="isPassword">
	</label>
</template>

<script>
	export default {
		name:"myInput",
		props:{
			isPassword:{
				type:Boolean,
				default:false
			},
			inputName:{
				type:String,
				required:true
			}
		}
	}
</script>
````

**复现步骤**
[复现问题的步骤]
1.  启动微信小程模拟器
2.  输入内容
3.  点击登录按钮
4.  查看控制台log
5.  显示：form发生了submit事件，携带数据为：{}

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: windows7
 - HBuilderX版本:  HBuilderX 2.0.1.20190614
 - uni-app版本:
System:
    OS: Windows 7
    CPU: (4) x64 Intel(R) Core(TM) i5-4460  CPU @ 3.20GHz
  Binaries:
    Node: 10.15.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.6.0 - C:\Program Files (x86)\Yarn\bin\yarn.CMD
    npm: 6.4.1 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @dcloudio/uni-app-plus: * => 0.0.243
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: * => 0.2.963
    @dcloudio/uni-h5: * => 0.5.10
    @dcloudio/uni-mp-alipay: * => 0.0.817
    @dcloudio/uni-mp-baidu: * => 0.0.845
    @dcloudio/uni-mp-qq: * => 0.0.101
    @dcloudio/uni-mp-toutiao: * => 0.0.341
    @dcloudio/uni-mp-weixin: * => 0.0.962
    @dcloudio/uni-template-compiler: * => 0.9.179
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 0.9.528
    @dcloudio/vue-cli-plugin-uni: latest => 0.9.481
    @dcloudio/webpack-uni-mp-loader: * => 0.3.630
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: * => 0.2.846
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.8.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.8.0
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-service: ^3.0.1 => 3.8.4
    @vue/cli-shared-utils:  3.8.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: Not Found

**Comment by fxy060608** [comment]
自定义组件增加选项：behaviors: ['uni://form-field']

**Comment by robin901118** [comment]
> 自定义组件增加选项：behavior：['uni：// form-field']

不行的，引用之后报错，报错内容：TypeError: Cannot read property 'type' of null
然后我查询了微信小程序官方文档改成：behavior：['wx：// form-field']，这时候不报错了，但是还是无法访问到组件内部的值

**Comment by fxy060608** [comment]
1.npm update，更新最新依赖库
2.自定义组件中的代码调整为：
```javascript
<template name="myInput">
	<view class="label">
		<input type="text" v-model="value">
	</view>
</template>

<script>
	export default {
        behaviors: ['uni://form-field'],
		props: {
			isPassword: {
				type: Boolean,
				default: false
			}
		}
	}
</script>
使用时：
```html
<myInput name="password"></myInput>
```
```

**Comment by robin901118** [comment]
> 1.npm update，更新最新依赖库
> 2.自定义组件中的代码调整为：
> 
> ```js
> < template name = “ myInput ” > 
> 	< view class = “ label ” > 
> 		< input type = “ text ” v - model = “ value ” > 
> 	< / view > 
> < / template >
> 
> < script > 
> 	export  default {
>         行为： [ ' uni：// form-field ' ]，
> 		道具： {
> 			isPassword ： {
> 				type ： Boolean，
> 				默认值： false
> 			}
> 		}
> 	}
> < / script >
> ```
> 
> 使用时：
> 
> ```
> < myInput  name = “ password ” > </ myInput >
> ```

谢谢，更新之后已解决，刚开始还是不行，后来发现是因为我的name属性传入组件内部造成无法获取，放在组件上面就可以获取到了，万分感谢~

**Comment by ZCY-G** [comment]
app端怎么解决？

**Comment by ZCY-G** [comment]
放在slot里也不行？
