### ISSUE TITLE
目前Hbuilder的编译器最新版本是3.98 但是我执行了npx @dcloudio/uvm@latest命令之后 vue-cli的最新版本却是3.6.10 这两个版本怎么不一致呢

### ISSUE THREAD

**Issue by Tongzhongren** [dcloudio/uni-app#4817]
目前Hbuilder的编译器最新版本是3.98 但是我执行了npx @dcloudio/uvm@latest命令之后 vue-cli的最新版本却是3.6.10 这两个版本怎么不一致呢
![微信图片_20240407152800](https://github.com/dcloudio/uni-app/assets/70741309/3d29a155-de03-45d9-a92c-9e15e839db8d)

**Comment by zhetengbiji** [comment]
同：https://ask.dcloud.net.cn/question/189122
