### ISSUE TITLE
slot 小程序编译后dom结构有问题

### ISSUE THREAD

**Issue by myjustify** [dcloudio/uni-app#482]
**问题描述**
slot 小程序编译后dom结构有问题
**复现步骤**
**cusForm.vue**

```
<template>
	<view class="cusForm">
		<form @submit="formSubmit" @reset="formReset">
			<slot></slot>
		</form>
	</view>
</template>
```

**组件引用**

```
 <cusForm>
     <input type="text" value="" name='id' require/>
     <button type="primary" form-type="submit">提交</button>
</cusForm>
```

**预期结果**

```
<form>
     <input />
     <button />
</form>
```

**实际结果**
> 
![AUJ%S IP$NZRJ8`FE16FTRH](https://user-images.githubusercontent.com/30165374/59739924-08fd9980-9299-11e9-8847-a0052d2fa81b.png)

**Comment by fxy060608** [comment]
应该是小程序 wxml 面板显示的问题，实际节点应该在 form 里边
![image](https://user-images.githubusercontent.com/566799/59761743-285feb00-92c8-11e9-9265-4debb3069656.png)

**Comment by myjustify** [comment]
不是小程序面板的问题  测试了下 submit 无法触发

**Comment by fxy060608** [comment]
你说的 submit 不触发，跟这个 dom 结构没有任何关系
1.dom 结构如我截图所示，仅 wxml 显示不正确，真实渲染是正确的，可以自己写原生小程序验证
2.submit 不触发，是因为你的 input 和 button 都是 slot 插入，小程序 form 组件不支持该方式使用
参考：https://developers.weixin.qq.com/community/develop/doc/0006669dda4fc821bfc656dda5bc00?highLine=form%2520slot
