### ISSUE TITLE
defineModel 无法使用,提示 "useModel" is not exported

### ISSUE THREAD

**Issue by LengGeng** [dcloudio/uni-app#4827]
"useModel" is not exported by "node_modules/.pnpm/@dcloudio+uni-mp-vue@3.0.0-alpha-4010120240403003/node_modules/@dcloudio/uni-mp-vue/dist/vue.runtime.esm.js", imported by "src/components/categories/CategoryScrollSelector.vue?vue&type=script&setup=true&lang.ts".
at components/categories/CategoryScrollSelector.vue:1:9
  1: import { useModel as _useModel, defineComponent as _defineComponent } from 'vue'
              ^
  2: import { unref as _unref, toDisplayString as _toDisplayString, t as _t, o as _o, f as _f, n as _n } from "vue"

**Comment by lph993** [comment]
hbuilderx vue版本低 用不了

**Comment by feibi** [comment]
+1

**Comment by w4ng3** [comment]
+1

**Comment by crrzzzz** [comment]
+1

**Comment by li1164267803** [comment]
+1

**Comment by extclp** [comment]
@fxy060608  h5可以使用了, 但是微信小程序还是不行

**Comment by Skiyee** [comment]
有朋友测过了？
现在怎么样了？

**Comment by Otto-J** [comment]
我测试微信小程序，运行 ok，可以参考下面 demo 运行

https://gitcode.net/xiurensha5731/uni-app-questions/-/blob/main/src/pages/index/index.vue

index page
```html
<template>
  <div>
   <div>你输入了：{{ str }}</div>
    <myInput v-model:count="str"></myInput>
  </div>
</template>
<script lang="ts" setup>
import { ref } from "vue";
import myInput from "../../components/my-input.vue";
const str = ref("2");
</script>
```

对应组件 my-input

```html
<template>
  <div>
    <input
      type="text"
      v-model="count"
      style="height: 20px; border: 1px solid black"
    />
  </div>
</template>
<script lang="ts" setup>
const count = defineModel<string>("count", { default: "" });
</script>

<style></style>
```
