### ISSUE TITLE
h5 ios input失去焦点后页面不回弹

### ISSUE THREAD

**Issue by BrightYang0801** [dcloudio/uni-app#483]

**Comment by zhetengbiji** [comment]
请将问题内容补充具体

**Comment by BrightYang0801** [comment]
> 请将问题内容补充具体

uni-app h5官方demo 表单组件=>input示例失去焦点后页面都不回弹。

**Comment by zhetengbiji** [comment]
使用的的什么浏览器？你说的不回弹是指的什么？

**Comment by BrightYang0801** [comment]
> iOS版本多少？使用的什么浏览器？你说的不回弹是指的什么？

ios版本12.0.1，微信内置浏览器，不回弹的意思是点击input聚焦页面弹起，然后点击其它地方失去焦点，页面还是弹起状态，截图了。

![image](https://user-images.githubusercontent.com/37973515/59907151-f6bc6080-943c-11e9-9b83-9d071c80c62b.png)
![image](https://user-images.githubusercontent.com/37973515/59907170-0045c880-943d-11e9-808e-db5f7e9b4282.png)
![image](https://user-images.githubusercontent.com/37973515/59907185-0a67c700-943d-11e9-9720-e18c285acff2.png)

**Comment by zhetengbiji** [comment]
这个是微信浏览器的 Bug，使用普通的 HTML 即可复现

```html
<!DOCTYPE html>
<html>
	<head>
		<meta charset="utf-8" />
		<title></title>
		<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0" />
	</head>
	<body>
		<br><br><br><br><br><br><br><br><br><br><br>
		<br><br><br><br><br><br><br><br><br><br><br>
		<input />
	</body>
</html>
```
