### ISSUE TITLE
swiper 如何屏蔽手动滑动？

### ISSUE THREAD

**Issue by CjoyHome** [dcloudio/uni-app#484]
swiper 如何屏蔽手动滑动？
`@touchmove.stop.prevent="stopTouchMove" 
stopTouchMove() {
		return false;
}
`
无效

**Comment by zhetengbiji** [comment]
stop 不会生效，因为 stop 是阻止向父节点冒泡，正确方法是在 swiper-item 内部的 view 上阻止

另外有一个简单办法：用一个view盖在上面即可阻止
