### ISSUE TITLE
uni-ui searchbar组件placeholder样式无法更改

### ISSUE THREAD

**Issue by CodeMonkeyLin** [dcloudio/uni-app#4848]
能否加个配置修改uni-ui searchbar组件placeholder样式

**Comment by PeiXiaoMeng** [comment]
@CodeMonkeyLin 你希望改什么？placeholder的color？

**Comment by bfc846958672** [comment]
目前不会支持该功能。  不过你可以通过直接修改uni_modules里面的placeholder源码来实现自定义的placeholder样式
