### ISSUE TITLE
微信小程序切换网络重新刷新进入就白屏，用微信小程序原生开发没问题

### ISSUE THREAD

**Issue by fengzhongye** [dcloudio/uni-app#4852]

**Comment by fengzhongye** [comment]
微信小程序切换网络重新刷新进入(进入的时候会调用后台接口，调用极其缓慢)，有时候会白屏，用微信小程序原生开发没问题

<img width="248" alt="1713496956579" src="https://github.com/dcloudio/uni-app/assets/4496435/87c1477d-dc11-4d57-a33a-76b164290607">

**Comment by fengzhongye** [comment]
![image](https://github.com/dcloudio/uni-app/assets/4496435/6ed3e17c-d925-43bf-b897-6ca4b2f7f8cd)

**Comment by bfc846958672** [comment]
模拟器还是真机预览，提供一下demo工程

**Comment by bfc846958672** [comment]
长时间未响应，关闭本issue。 如还有问题，可 reopen issue 继续讨论。
