### ISSUE TITLE
uploadfile 提点意见

### ISSUE THREAD

**Issue by lunxian8** [dcloudio/uni-app#4859]
1、使用uploadfile 多文件上传封装文件数组的话 name重复会去除，name不重复会导致后台接受不到 （java 代码  MultipartFile[] file） ，这个问题呢必须用MultipartRequest这样解决。 2、因为这个方法同时存在业务字段，uploadfile 里用formData封装，如果提交不上传文件看了一下这个方法是没有进行后台提交的，导致要判断文件是否存在不存则再写个提交表单方法调用，可是后台接收类型导致Content-Type: multipart/form-data;接收不了因为没有boundary=--------------------------995510366882285018455302 后面应该是自动生成的boundary ，用postman等工具测试可用，如果改为application/x-www-form-urlencoded 那么因为后台有MultipartRequest又用不了，被迫改为了两个方法，一个纯表单，一个表单带文件，前端后端都是两个，被这个困扰到了，感觉很不方便。或许是我们操作姿势不对？

**Comment by bfc846958672** [comment]
你好，请准确描述一下你的问题。

**Comment by bfc846958672** [comment]
可以去插件市场找一下合适的文件上传组件。[插件市场-文件上传](https://ext.dcloud.net.cn/search?q=%E6%96%87%E4%BB%B6%E4%B8%8A%E4%BC%A0)

**Comment by lunxian8** [comment]
tks ！！ 帮助前端同事协调 时间久远忘记了，问题已经解决。
