### ISSUE TITLE
d.ts 声明文件部分函数没有声明void返回值

### ISSUE THREAD

**Issue by weoil** [dcloudio/uni-app#486]
**问题描述**
@dcloudio/types/uni-app/uni.d.ts这个声明文件里面的 部分的函数没有声明返回值,导致编译的时候报错

```
 $on(eventName?: string, callback?: () => void);
$emit(eventName?: string, param?: any);
$off(eventName?: string | any [], callback?: () => void);
```
**预期结果**
更改声明文件,增加返回值声明
```
$emit(eventName?: string, param?: any):void;
```

**实际结果**
![image](https://user-images.githubusercontent.com/24948543/59896410-0b87fc80-941b-11e9-8861-62210c5d6e2c.png)

**Comment by zhetengbiji** [comment]
更新到 0.2.2 即可
