### ISSUE TITLE
抖音小程序canvas不支持ctx.getImageData和uni.canvasGetImageData

### ISSUE THREAD

**Issue by zxl20070701** [dcloudio/uni-app#4867]
这个以后会提供吗？因为项目中有些功能依赖他们

**Comment by bfc846958672** [comment]
你好， getImageData 这个api需要抖音小程序支持才行，看抖音小程序文档并没有相关说明。

**Comment by zxl20070701** [comment]
嗯，我看抖音小程序宣称的按照H5的canvas来，事实上不能说一模一样，只能说相差甚远。
