### ISSUE TITLE
希望picker组件 加点功能

### ISSUE THREAD

**Issue by ABasket** [dcloudio/uni-app#487]
**新功能描述**
1.能够监听确定按钮
2.能够给某列某些值做条件判断
3.能够用其他按钮控制picker的显示隐藏

**现状及问题**
现在有个需求
 要求禁掉某些值 而不是过滤掉  
按确定按钮做判断 阻止picker隐藏
初始化就显示picker

可能我看文档看的不仔细。(/ □ \) 有解决方案 麻烦告诉一下

**Comment by zhetengbiji** [comment]
目前内置组件不会为此修改，你可以尝试一下插件市场里其他人写的picker组件，如果还不能满足就自己修改一下。
