### ISSUE TITLE
建议增加sub-modules文件目录,给所有分包共享使用

### ISSUE THREAD

**Issue by charlesluo2014** [dcloudio/uni-app#4876]
在开发过程中，由于小程序大小限制，用uniapp开发很容易就超过2M限制，解决大小限制只能分包，但是分包的时候有很多组件是在分包中共享的，有各个分包中依赖共同组建的需求。所以建议增加sub-modules目录，在编译打包的时候，将内容放到各个分包的对应目录中

**Comment by zhouyu1993** [comment]
自己建一个 sub-modules 文件就行了吧

**Comment by bfc846958672** [comment]
长时间未响应，关闭本issue。 如还有问题，可 reopen issue 继续讨论。

**Comment by zhouyu1993** [comment]
已收到。谢谢，我会尽快回复你。
