### ISSUE TITLE
subNVues不配置type背景无法透明

### ISSUE THREAD

**Issue by huiliaoning** [dcloudio/uni-app#488]
**问题描述**
之前提问是点击物理返回键subNVues窗体被关闭，官方回复说不设置type属性。
但是发现在live-pusher上使用subNVues只有在配置为popup时候才可以半透明，不配置type属性的话无论如何都没办法实现背景透明

**预期结果**
希望不配置type时候使用 subNVues 的背景可以透明

**系统信息:**
 - 发行平台: app
 - 操作系统 ：Android 7.0
 - HBuilderX版本：2.0.1.20190614
 - uni-app版本 ：最新版本
 - 设备信息 ：三星S8

**Comment by fxy060608** [comment]
截图说明你想要实现的效果图

**Comment by huiliaoning** [comment]
![微信图片_20190621143337](https://user-images.githubusercontent.com/16914915/59902759-b0153900-9431-11e9-996a-55d9328a5837.jpg)
白色区域本来是live-pusher图像  但是调用uni.getSubNVueById('talks').show()显示SubNVue窗体后就成了现在的样子 


以下是页面配置：
"subNVues": [{
							"id": "talks",
							"path": "pages/video/talk",
							"style": {
								"position": "absolute",
								"bottom": "55px",
								"left": "0",
								"width": "230px",
								"height": "110px",
								"background": "transparent"
							}
						}
					]

**Comment by huiliaoning** [comment]
> 截图说明你想要实现的效果图

![微信图片_20190621143337](https://user-images.githubusercontent.com/16914915/59902927-1ef29200-9432-11e9-95f6-99b7a3c78409.jpg)

白色区域本来是live-pusher图像 但是调用uni.getSubNVueById('talks').show()显示SubNVue窗体后就成了现在的样子

以下是页面配置：
"subNVues": [{
"id": "talks",
"path": "pages/video/talk",
"style": {
"position": "absolute",
"bottom": "55px",
"left": "0",
"width": "230px",
"height": "110px",
"background": "transparent"
}
}
]

**Comment by ch-zgh-1993** [comment]
在配置type时候使用 subNVues 的背景是可以透明的。
```json
// subnvue 配置如下
{
	"id": "video_mask",
	"path": "subnvue/subnvue/video-mask",
	"style": {
		"position": "absolute",
		"bottom": "30px",
		"left": "0",
		"width": "230px",
		"height": "110px",
		"background": "transparent"
	}
}
```
在 nvue 页面中，注意也需要设置外层容器背景为 transparent 。实际效果如下： 黑色为 live-pusher 组件，video-mask 为 transparent.

![D1338C2F831C57EF92319A886076C8EB](https://user-images.githubusercontent.com/20807348/59905171-f79ec380-9437-11e9-902e-578b9c1a59c6.jpg)

**Comment by huiliaoning** [comment]
方便把你的live-pusher完整页面代码发出来吗 我就说是按照你刚才说的那样做的 但就是不透明，或者加个qq我把我的完整代码发给你帮忙看一下  谢谢

**Comment by huiliaoning** [comment]
![微信图片_20190621164051](https://user-images.githubusercontent.com/16914915/59909994-8c5aee80-9443-11e9-92e9-f8a84b3ccaae.jpg)
三星S8效果

![微信图片_20190621164159](https://user-images.githubusercontent.com/16914915/59910022-97ae1a00-9443-11e9-880b-24d195cc8ff2.jpg)
华为新版手机效果

**Comment by ch-zgh-1993** [comment]
设置 live-pusher 宽高了吗？设置了也是白色的话，留下你的qq.

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
