### ISSUE TITLE
uni.showLoading

### ISSUE THREAD

**Issue by qhl123456** [dcloudio/uni-app#4880]
希望uni.showLoading和uni.showModal、uni.showToast等API可以加一个maxCount的最大显示数的API，不用每个项目的拦截器都需要配置一个flag去判断，有时多个接口报错时，uni.showModal出现了多个，导致线上客户一直再点击，避免从代码层面出现问题，类似antdegisn这种
![image](https://github.com/dcloudio/uni-app/assets/74643840/7d0e7318-5ff9-4b94-baa2-f9150ff77c6b)

**Comment by LeoKun1231** [comment]
加一

**Comment by zhetengbiji** [comment]
收到，后续根据需求考虑是否内置，毕竟积少成多框架会越来越大
