### ISSUE TITLE
如何获取软键盘高度？

### ISSUE THREAD

**Issue by ABasket** [dcloudio/uni-app#489]
如题。

**Comment by zhetengbiji** [comment]
HBuilderX 2.3.0 已支持 

+ App平台 新增 uni.onKeyboardHeightChange 支持监听键盘高度变化
+ App平台 优化 input 组件 @focus 事件支持获取键盘高度

**Comment by shengliZhang** [comment]
App平台 新增 uni.onKeyboardHeightChange 支持监听键盘高度变化
App平台 优化 input 组件 @Focus 事件支持获取键盘高度

以上方法在在真机中运行是ok的，但是云打包出apk后 就是不执行，导致获取不到键盘的高度。

@zhetengbiji 
Hbuilder X 3.8.12.20230817
