### ISSUE TITLE
请教一下vite.config.ts改成vite.config.mts相关问题

### ISSUE THREAD

**Issue by Sharang-heng** [dcloudio/uni-app#4896]
由于我需要引用unocss
![image](https://github.com/dcloudio/uni-app/assets/69613396/125825a9-62f1-42ff-b57b-2a59f93ee304)
然后按照他们的建议我将vite.config.ts改成vite.config.mts
代码为
```
import { defineConfig } from "vite";
import uni from "@dcloudio/vite-plugin-uni";

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [uni()],
});
```
执行时会报
uni is not a function
请教一下该怎么解决？

**Comment by extclp** [comment]
参考 https://github.com/dcloudio/uni-app/issues/4815#issuecomment-2094223871

**Comment by zxhbloomer** [comment]
似乎cjs也有问题，h5可以，app运行不起来

**Comment by bfc846958672** [comment]
评论区中已有可用的解决方案，关闭本issue。 如还有问题，可 reopen issue 继续讨论。
