### ISSUE TITLE
css 变量未生效

### ISSUE THREAD

**Issue by Bo-Teng** [dcloudio/uni-app#4902]
**Hbuilder X 4.08**
在App.vue中定义了一个--text-color
![image](https://github.com/dcloudio/uni-app/assets/73982811/887c42a8-b950-4fc3-ba34-be87386af4b4)
在其他页面中使用这个变量但是未生效
![image](https://github.com/dcloudio/uni-app/assets/73982811/473dd11d-4530-4c7b-9483-70a96b97ea1f)
在小程序的开发者工具中能看到page节点下没有看到 **--text-color** 这个变量，在浏览器中html这个节点有这个变量，但是在**.device-introduction**这个节点下没有**color:var(--text-color)** 

请问是什么原因导致了这个问题

**Comment by chasonma** [comment]
不生效可能是 :root 在小程序下是不支持的，可以使用条件编译区分，参考如下：
```
/* #ifdef H5 */
:root {
  --text-color: red;
}
/* #endif */

/* #ifdef MP */
view {
  --text-color: red;
}
/* #endif */
```

**Comment by Bo-Teng** [comment]
好的谢谢
