### ISSUE TITLE
关于打包成h5端分析打包完后的文件为啥每个js都会把uview-ui框架打包进去 

### ISSUE THREAD

**Issue by xiaoxiaohuayu** [dcloudio/uni-app#4908]
<img width="1592" alt="image" src="https://github.com/dcloudio/uni-app/assets/30976418/56dcb6e9-1f23-47ec-9aef-7fda63f15a07">

**Comment by bfc846958672** [comment]
vue3 可以通过设置vite配置来将 公共模块提取出来
 ```      
 optimizeDeps: {
         include: ['common-module-name'], // 指定要优化的公共模块名称
       },
```

**Comment by xiaoxiaohuayu** [comment]
> vue3 可以通过设置vite配置来将 公共模块提取出来
> 
> ```
> optimizeDeps: {
>         include: ['common-module-name'], // 指定要优化的公共模块名称
>       },
> ```

那如果是vue2呢？

**Comment by Otto-J** [comment]
问题搜索 webpack 的 optimization.splitChunks 来处理
