### ISSUE TITLE
支付宝小程序自定义子组件无法获取到父组件传递的方法属性

### ISSUE THREAD

**Issue by meicx** [dcloudio/uni-app#491]
支付宝小程序在传递给子组件方法时，子组件获取为undefined，在父组件自身的template打印结果也是undefined，这个问题该怎么解决？
![image](https://user-images.githubusercontent.com/19547619/59964846-f0131380-9538-11e9-9d81-48d0947fd0a1.png)
![image](https://user-images.githubusercontent.com/19547619/59964849-f86b4e80-9538-11e9-869f-dc86b52a07bd.png)

**Comment by Wangyaqi** [comment]
这是想实现什么，有完整的代码吗

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
