### ISSUE TITLE
在微信小程序中，editor 组件如何获取焦点？

### ISSUE THREAD

**Issue by XionGuo37** [dcloudio/uni-app#4914]
例如我想在点击一个按钮后，自动聚焦 editor

**Comment by bfc846958672** [comment]
你好，可以尝试插入空文本聚焦，但是不保证全平台可行， [相关讨论](https://developers.weixin.qq.com/community/develop/doc/000c0853afc55878d63c4bab451000?highLine=EditorContext%2520%25E8%2581%259A%25E7%2584%25A6)
