### ISSUE TITLE
uniapp + tailwindcss 在H5环境下运行。为什么只设置了border-t上边框，但是显示有4个边框。小程序没问题，H5就不行，调试的css样式中还找不到其他三个边框的属性。大佬们有什么办法去改吗？

### ISSUE THREAD

**Issue by guoyanshuo** [dcloudio/uni-app#4924]
![0065d830d37fb63a12e9ff3c1be045e](https://github.com/dcloudio/uni-app/assets/67988151/b7cce1e5-aa01-491f-ba94-c2cb272cecee)
![5ce6b26f70644e6a443b89a6acdd663](https://github.com/dcloudio/uni-app/assets/67988151/5444c805-14f5-42fe-9e97-fe24f7735cf9)

**Comment by Otto-J** [comment]
你提到微信可以 h5 不行，提供下复现工程吧，切换浏览器、隐私模式正常吗？手动写 css/style 是否表现正常？

**Comment by chasonma** [comment]
改成 border-0 border-t

**Comment by guoyanshuo** [comment]
> 改成 border-0 border-t

感谢回复。 写成border-0 border-t 就只有上边框了。要改的比较多，直接在全局加了个border-width: 0;   h5出现这个问题就比较奇怪

**Comment by guoyanshuo** [comment]
> 你提到微信可以 h5 不行，提供下复现工程吧，切换浏览器、隐私模式正常吗？手动写 css/style 是否表现正常？

感谢回复。写成border-0 border-t，或者border-width: 0;  就没问题了。

**Comment by Otto-J** [comment]
这个问题我怀疑还是业务问题，你的解决方案是补充完整 css 覆盖行为。

我运行 tailwind +uni-app+vue3到 web 平台，

```html
 <div class="border-t  text-3xl font-bold underline">
    Hello world!
    </div>
```

只有上面的边框，如果你感兴趣可以进一步分析，如果不需要这个问题就不继续跟进了，怀疑还是你义务上或者运行时有css 影响

**Comment by guoyanshuo** [comment]
> 这个问题我怀疑还是业务问题，你的解决方案是补充完整 css 覆盖行为。
> 
> 我运行 tailwind +uni-app+vue3到 web 平台，
> 
> ```
>  <div class="border-t  text-3xl font-bold underline">
>     Hello world!
>     </div>
> ```
> 
> 只有上面的边框，如果你感兴趣可以进一步分析，如果不需要这个问题就不继续跟进了，怀疑还是你义务上或者运行时有css 影响
> 
> 补充：我看到你已经关闭了，那这个问题如果你有意继续追查可以继续联系我，提供相关工程

您好，我把问题代码上传到git仓库了，https://github.com/guoyanshuo/uni-tailwind-border-error.git  。执行npm run dev:h5 运行H5页面。还是存在border-t的问题，而且不加border-solid的话，所有边框都不显示。 您方便的时候请帮忙看一下为什么会出现这个问题。
![f5fb896586dea41765b174314816872](https://github.com/dcloudio/uni-app/assets/67988151/42b402f5-14d8-4bcc-a2e1-f3f16db66bbf)
