### ISSUE TITLE
百度小程序 tabbar页面 组件内onShow生命周期只第一次触发

### ISSUE THREAD

**Issue by JaxBBLL** [dcloudio/uni-app#493]
**问题描述**
[问题描述：百度小程序 tabbar页面 组件内onShow生命周期只第一次触发]

**系统信息:**
 - 发行平台: [百度小程序]
 - 操作系统 []
 - HBuilderX版本 [2.0.1.20190614]
 - 设备信息 [红米 note7]

**Comment by dcloudhdx** [comment]
HBuilderX 2.1.3，百度开发者工具 2.4.6，测试没有问题

这个问题可能是百度开发者工具的 bug，更新版本试试
