### ISSUE TITLE
cli项目无法打包本地原生插件

### ISSUE THREAD

**Issue by Es-Rell** [dcloudio/uni-app#4932]
### 项目结构如下：
![image](https://github.com/dcloudio/uni-app/assets/29221830/f5ddcadf-45dd-4a43-968c-c78abda065db)
![image](https://github.com/dcloudio/uni-app/assets/29221830/ca1c1bd4-b5bc-464b-8955-59cbf005c178)

**原生插件:`DCloud-PushSound`**

打包后的`dist/dev/app`或`dist/build/app`均未包含`nativeplugins`文件夹及华为推送文件`agconnect-services.json`，所以自定义基座以及云打包生成的apk文件都是云端插件生成的结果，通过生成的apk反编译得到依旧生成云端插件默认铃声`pushsound.mp3`而非本地插件文件`neworder.mp3`
![image](https://github.com/dcloudio/uni-app/assets/29221830/a6e13646-2e5c-4dcb-ac1d-0268dea76d61)

**以上实测同套代码uniapp项目正常**

**Comment by oyal** [comment]
你解决了吗？我有同样的问题，本地打包无法加载本地的插件

**Comment by Es-Rell** [comment]
> 你解决了吗？我有同样的问题，本地打包无法加载本地的插件

解决了，cli项目需要使用uniapp官方的cli命令打包
