### ISSUE TITLE
uni-app 在ios 6.6.7版本的微信下报错，新建项目就报错，无法正确运行

### ISSUE THREAD

**Issue by lentg** [dcloudio/uni-app#494]
如题

**Comment by zhetengbiji** [comment]
报错信息是什么

**Comment by lentg** [comment]
![Uploading 659158719.jpg…]()

**Comment by fxy060608** [comment]
查看一下微信基础库版本号

**Comment by lentg** [comment]
不太对啊，我用Taro就没问题啊，用uni-app，新建的项目也出问题

**Comment by lentg** [comment]
> 查看一下微信基础库版本号



> 报错信息是什么

不太对啊，我用Taro和微信原生都没问题啊，用uni-app，新建的项目也出问题
更改了 微信基础库版本号 就提示要更新微信了。再说6.6.7的微信版本也不算低啊

**Comment by zhetengbiji** [comment]
> > 查看一下微信基础库版本号
> 
> > 报错信息是什么
> 
> 不太对啊，我用Taro和微信原生都没问题啊，用uni-app，新建的项目也出问题
> 更改了 微信基础库版本号 就提示要更新微信了。再说6.6.7的微信版本也不算低啊

报错信息是什么？

**Comment by lentg** [comment]
> > > 查看一下微信基础库版本号
> > 
> > 
> > > 报错信息是什么
> > 
> > 
> > 不太对啊，我用Taro和微信原生都没问题啊，用uni-app，新建的项目也出问题
> > 更改了 微信基础库版本号 就提示要更新微信了。再说6.6.7的微信版本也不算低啊
> 
> 报错信息是什么？

如上面发的图片

**Comment by lentg** [comment]
> 报错信息是什么

新建项目报这错，在微信7.0.4下没问题的项目，在微信6.6.7下也出这错

**Comment by fxy060608** [comment]
不是微信版本，是小程序基础库版本

**Comment by lentg** [comment]
小程序基础库版本也修改了，也不行。我用原生和taro没出现问题啊?

**Comment by fxy060608** [comment]
小程序基础库版本是多少

**Comment by lentg** [comment]
登录后台修改的，由低往高修改了好几个都不行。
