### ISSUE TITLE
uniapp 微信小程序编译错误

### ISSUE THREAD

**Issue by ywenhao** [dcloudio/uni-app#4944]
uniapp,用vue3 setup里面，import 导入一张图片，编译成微信小程序会出现Logo is not defined，查看编译后的代码是被编译成了_ctx.Logo

```vue
<template>
  <image  :src="Logo" />
</template>

<script setup lang="ts"> 
import Logo from '@/static/logo.png'

// 正常打印
console.log(Logo)
</script>
```

**Comment by ywenhao** [comment]
![image](https://github.com/dcloudio/uni-app/assets/37856060/74d8f0b6-ec01-46cc-9053-3cb123f672d9)

**Comment by ywenhao** [comment]
挺重大的bug,麻烦官方修改一下。或者告知一下负责这一模块的文件位置，方便我们提pr

**Comment by GRCmade** [comment]
现在是正常的，图片也可以正常显示了！

**Comment by ywenhao** [comment]
> 现在是正常的，图片也可以正常显示了！

ok, 好了
