### ISSUE TITLE
组件放到同目录下，编译到小程序时报错，

### ISSUE THREAD

**Issue by gao-xiang** [dcloudio/uni-app#4952]
组件放到页面文件的同组目录下，
import AddressPanel from './components/AddressPanel.vue'

<AddressPanel  />

只要是这样导入的组件就报错，

[plugin:vite:vue] [plugin vite:vue] src/pages/goods/goods.vue (364:1): Error parsing JavaScript expression:
_o($event => ($setup.openSkuPopup($literal-const.SkuMode.Both)))
Unexpected token (1:43)

或是以下错误：

[plugin:uni:mp-using-component] Unexpected token C in JSON at position 38 

https://gitee.com/Megasu/uniapp-shop-vue3-ts/

执行升级到最新   npx @dcloudio/uvm@latest alpha

执行：pnpm dev:mp-weixin   就会报错

**Comment by spg1025348744** [comment]
同样问题

**Comment by gd4Ark** [comment]
uni-mp-compiler 的问题，最小可复现例子：
```js
JSON.parse('{ "name": "$setup[\"SearchBar\"]" }')
```

可单独回退 vite-plugin-uni 到 4000320240311001 解决，正常应该是：
```js
JSON.parse('{ "name": "SearchBar" }')
```

**Comment by icksky** [comment]
引用 `src/components` 下面的组件, 出现错误 `[plugin:commonjs] Unexpected token C in JSON at position 33
at pages/index/index.vue:1:0`

**Comment by kasnti** [comment]
同样的问题，而且是最近才发生的

**Comment by icksky** [comment]
> 引用 `src/components` 下面的组件, 出现错误 `[plugin:commonjs] Unexpected token C in JSON at position 33 at pages/index/index.vue:1:0`

试了更早一些的版本 (`4010720240511003`), 报错是 `[plugin:uni:mp-using-component] Unexpected token C in JSON at position 33`

**Comment by gao-xiang** [comment]
vite-plugin-uni 单独回退到 4000320240311001，虽然编译不报错，但是又会报其它的错误，页面无法正常显示。

**Comment by FliPPeDround** [comment]
经测试`3.0.0-4000820240401001`版本可以在小程序dev模式下手动导入组件，正确编译

可以使用`npm create uni@latest`创建项目测试

**Comment by fxy060608** [comment]
可以下载该附件，覆盖到node-modules中 
@dcloudio/uni-mp-compiler/dist/transforms/transformElement.js 
@dcloudio/uni-mp-compiler/dist/transforms/transformExpression.js
验证是否还有问题。
[transforms.zip](https://github.com/user-attachments/files/15542712/transforms.zip)

**Comment by icksky** [comment]
@fxy060608 并没有 `@dcloudio/uni-mp-compiler` 目录; 搜索 `const transformExpression` 方法, 位于 `node_modules\@dcloudio\uni-cli-shared\lib\@vue\compiler-sfc\dist\compiler-sfc.esm-browser.js`;

**使用版本:**  `3.0.0-alpha-4010820240531001`

**Comment by fxy060608** [comment]
> @fxy060608 并没有 `@dcloudio/uni-mp-compiler` 目录; 搜索 `const transformExpression` 方法, 位于 `node_modules\@dcloudio\uni-cli-shared\lib\@vue\compiler-sfc\dist\compiler-sfc.esm-browser.js`;
> 
> **使用版本:** `3.0.0-alpha-4010820240531001`

用pnpm的话，执行 `path.resolve(require.resolve('@dcloudio/uni-mp-compiler/dist/',{paths:[require.resolve('@dcloudio/uni-mp-weixin/package.json')]}),'../transforms')` 打印路径

**Comment by gao-xiang** [comment]
> 可以下载该附件，覆盖到node-modules中 @dcloudio/uni-mp-compiler/dist/transforms/transformElement.js @dcloudio/uni-mp-compiler/dist/transforms/transformExpression.js 验证是否还有问题。 [transforms.zip](https://github.com/user-attachments/files/15542712/transforms.zip)

覆盖后问题还是报一样的错误。

**Comment by icksky** [comment]
> 可以下载该附件，覆盖到node-modules中 @dcloudio/uni-mp-compiler/dist/transforms/transformElement.js @dcloudio/uni-mp-compiler/dist/transforms/transformExpression.js 验证是否还有问题。 [transforms.zip](https://github.com/user-attachments/files/15542712/transforms.zip)

@fxy060608 我这替换后仍然报错: `[plugin:uni:mp-using-component] Unexpected token C in JSON at position 33`

**Comment by gd4Ark** [comment]
> 可以下载该附件，覆盖到node-modules中 @dcloudio/uni-mp-compiler/dist/transforms/transformElement.js @dcloudio/uni-mp-compiler/dist/transforms/transformExpression.js 验证是否还有问题。 [transforms.zip](https://github.com/user-attachments/files/15542712/transforms.zip)

依旧报错，报错原因是在 https://github.com/dcloudio/uni-app/blob/d034ae8ee7dd3aa185d6d07a96cc51fc7e81e878/packages/uni-cli-shared/src/mp/usingComponents.ts#L421-L423 无法被正常 JSON.parse，因为在 JSON.stringify 的时候 setup 引入的组件 key 为 `"$setup[\"SearchBar\"]"` https://github.com/dcloudio/uni-app/blob/d034ae8ee7dd3aa185d6d07a96cc51fc7e81e878/packages/uni-mp-compiler/src/codegen.ts#L235-L237

尝试过在这里将 key 中的 `$SETUP` 移除即可正常运行：
https://github.com/dcloudio/uni-app/blob/2cb26a72ef798b1275c09ac912e29590ccc1d8b0/packages/uni-mp-compiler/src/codegen.ts#L229-L231

替换为：
```js
// 调整为setup命名
let setupName = name

// $setup["test"] => test
if (name.includes('$setup[')) {
  setupName = name.match(/"(.+)"/)[1]
}

bindingComponents[tag].name = setupName
components.push(setupName)
```

**Comment by gd4Ark** [comment]
顺带一提，这里的替换是有问题的
https://github.com/dcloudio/uni-app/blob/ceef05813ae0a4fddaee89191f83a4328e6b00ed/packages/uni-cli-shared/src/mp/usingComponents.ts#L277

运行结果：
```js
"$setup[\"test\"]".replace('$setup["', '').replace('"', '');
// 'test]'
```

应该改成：
```js
"$setup[\"test\"]".replace('$setup["', '').replace('"]', '');
```

前面 uni-app/packages/uni-mp-compiler/src/codegen.ts 也可以复用这个逻辑

**Comment by gd4Ark** [comment]
> 可以下载该附件，覆盖到node-modules中 @dcloudio/uni-mp-compiler/dist/transforms/transformElement.js @dcloudio/uni-mp-compiler/dist/transforms/transformExpression.js 验证是否还有问题。 [transforms.zip](https://github.com/user-attachments/files/15542712/transforms.zip)

这个修复能够解决 https://github.com/dcloudio/uni-app/issues/4956

**Comment by fxy060608** [comment]
目前可以通过定制vite.config.js来规避该问题：
```
import { defineConfig } from 'vite'
import uni from '@dcloudio/vite-plugin-uni'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    uni(),
    { // 自定义插件禁用vite:vue插件的devToolsEnabled，强制编译 vue 模板时 inline 为 true
      name: 'fix-vite-plugin-vue',
      configResolved(config) {
        const plugin = config.plugins.find((p) => p.name === 'vite:vue')
        if (plugin && plugin.api && plugin.api.options) {
          plugin.api.options.devToolsEnabled = false
        }
      },
    },
  ],
})
```

**Comment by gd4Ark** [comment]
> ```ts
> @dcloudio/vite-plugin-uni
> ```

没用，依旧报错

**Comment by fxy060608** [comment]
> https://gitee.com/Megasu/uniapp-shop-vue3-ts/

我用https://gitee.com/Megasu/uniapp-shop-vue3-ts/这个测试工程没有问题，
你那里还有问题的话，提供测试工程

**Comment by gao-xiang** [comment]
> 目前可以通过定制vite.config.js来规避该问题：
> 
> ```ts
> import { defineConfig } from 'vite'
> import uni from '@dcloudio/vite-plugin-uni'
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   plugins: [
>     uni(),
>     { // 自定义插件禁用vite:vue插件的devToolsEnabled，强制编译 vue 模板时 inline 为 true
>       name: 'fix-vite-plugin-vue',
>       configResolved(config) {
>         const plugin = config.plugins.find((p) => p.name === 'vite:vue')
>         if (plugin && plugin.api && plugin.api.options) {
>           plugin.api.options.devToolsEnabled = false
>         }
>       },
>     },
>   ],
> })
> ```
测试这个临时方法有效。

**Comment by gd4Ark** [comment]
> > @fxy060608
> > 没用，依旧报错
> 
> 我用 https://gitee.com/Megasu/uniapp-shop-vue3-ts/ 这个测试工程没有问题， 你那里还有问题的话，提供测试工程

这个确实是有效的

**Comment by Dongary** [comment]
> > 目前可以通过定制vite.config.js来规避该问题：
> > ```ts
> > import { defineConfig } from 'vite'
> > import uni from '@dcloudio/vite-plugin-uni'
> > 
> > // https://vitejs.dev/config/
> > export default defineConfig({
> >   plugins: [
> >     uni(),
> >     { // 自定义插件禁用vite:vue插件的devToolsEnabled，强制编译 vue 模板时 inline 为 true
> >       name: 'fix-vite-plugin-vue',
> >       configResolved(config) {
> >         const plugin = config.plugins.find((p) => p.name === 'vite:vue')
> >         if (plugin && plugin.api && plugin.api.options) {
> >           plugin.api.options.devToolsEnabled = false
> >         }
> >       },
> >     },
> >   ],
> > })
> > ```
> 
> 测试这个临时方法有效。使用自定义工程项目。

这个确实有效

**Comment by justnewbee** [comment]
自从有一次升级报错后，我就一直没有升级成功，尝试了好几次都各种报错，万分不明白为啥 alpha 的要推升级，为啥这种问题会暴露出来
uniapp 是不要口碑了么

我一直用的 uni 相关的依赖（都只能写死版本）：

dev deps

```
"@dcloudio/types": "3.4.8",
"@dcloudio/uni-automator": "3.0.0-3090920231225001",
"@dcloudio/uni-cli-shared": "3.0.0-3090920231225001",
"@dcloudio/uni-stacktracey": "3.0.0-3090920231225001",
"@dcloudio/vite-plugin-uni": "3.0.0-3090920231225001",
```

prod deps

```
"@dcloudio/uni-app": "3.0.0-3090920231225001",
"@dcloudio/uni-app-plus": "3.0.0-3090920231225001",
"@dcloudio/uni-components": "3.0.0-3090920231225001",
"@dcloudio/uni-h5": "3.0.0-3090920231225001",
"@dcloudio/uni-mp-alipay": "3.0.0-3090920231225001",
"@dcloudio/uni-mp-baidu": "3.0.0-3090920231225001",
"@dcloudio/uni-mp-jd": "3.0.0-3090920231225001",
"@dcloudio/uni-mp-kuaishou": "3.0.0-3090920231225001",
"@dcloudio/uni-mp-lark": "3.0.0-3090920231225001",
"@dcloudio/uni-mp-qq": "3.0.0-3090920231225001",
"@dcloudio/uni-mp-toutiao": "3.0.0-3090920231225001",
"@dcloudio/uni-mp-weixin": "3.0.0-3090920231225001",
"@dcloudio/uni-mp-xhs": "3.0.0-3090920231225001",
"@dcloudio/uni-quickapp-webview": "3.0.0-3090920231225001",
"@dcloudio/uni-ui": "1.5.0",
```

希望能早点解决这种低级的问题吧

**Comment by Otto-J** [comment]
> 自从有一次升级报错后，我就一直没有升级成功，尝试了好几次都各种报错

报错是什么意思，是升级 uvm 报错，还是业务代码报错？
如果是前者，明确下版本。
如果是后者请开新 Issue 做进一步描述。

**Comment by redwolf1996** [comment]
同样的问题，错误百出，只能回退版本，官方根本没测试就放出来了

**Comment by time51656** [comment]
please fix this

**Comment by luoyingzhi** [comment]
> 目前可以通过定制vite.config.js来规避该问题：
> 
> ```ts
> import { defineConfig } from 'vite'
> import uni from '@dcloudio/vite-plugin-uni'
> 
> // https://vitejs.dev/config/
> export default defineConfig({
>   plugins: [
>     uni(),
>     { // 自定义插件禁用vite:vue插件的devToolsEnabled，强制编译 vue 模板时 inline 为 true
>       name: 'fix-vite-plugin-vue',
>       configResolved(config) {
>         const plugin = config.plugins.find((p) => p.name === 'vite:vue')
>         if (plugin && plugin.api && plugin.api.options) {
>           plugin.api.options.devToolsEnabled = false
>         }
>       },
>     },
>   ],
> })
> ```
这方法可以

**Comment by daiwanxing** [comment]
> ```ts
>    { // 自定义插件禁用vite:vue插件的devToolsEnabled，强制编译 vue 模板时 inline 为 true
>       name: 'fix-vite-plugin-vue',
>       configResolved(config) {
>         const plugin = config.plugins.find((p) => p.name === 'vite:vue')
>         if (plugin && plugin.api && plugin.api.options) {
>           plugin.api.options.devToolsEnabled = false
>         }
>       },
>     },
> ```

在 `3.0.0-4010520240507001` 版本通过此方案临时解决了。希望官方赶紧测试后再发布

**Comment by 1eeing** [comment]
每次升级一大堆问题，真烦

**Comment by liuqi-web** [comment]
这个在新版解决了吗？
