### ISSUE TITLE
input组件 :maxlength="-1"无法触发input事件，导致组件失效

### ISSUE THREAD

**Issue by Guan-Meng-Yuan** [dcloudio/uni-app#4955]
uni版本：3.0.0-alpha-4010820240531001
平台：支付宝小程序 iOS
复现链接 [https://github.com/Guan-Meng-Yuan/wot-design-bug-report](https://github.com/Guan-Meng-Yuan/wot-design-bug-report)
相关issue链接：[https://github.com/Moonofweisheng/wot-design-uni/issues/352](https://github.com/Moonofweisheng/wot-design-uni/issues/352)

**Comment by Otto-J** [comment]
感谢反馈，经过我实际测试，最新版本的依赖，运行你提供的项目。可以正常触发 input 事件，可能中间问题已经解决了。如果仍有问题，请 reopen 或者新开 issue 艾特我。
