### ISSUE TITLE
vue3 微信小程序使用 uni://form-field 报错、嵌套组件时拿不到 submit 的 value

### ISSUE THREAD

**Issue by Bo-Teng** [dcloudio/uni-app#4960]
自定义组件：
![image](https://github.com/dcloudio/uni-app/assets/73982811/1f7b8b44-e611-4aac-8fb1-3e9077582fff)
使用：
![image](https://github.com/dcloudio/uni-app/assets/73982811/384635ae-0d7f-44dc-a9b9-2d4eba726ae2)
报错截图：
![image](https://github.com/dcloudio/uni-app/assets/73982811/793bbf9d-4778-47e3-8df9-c6b8444d369f)

相关环境：

- vue3 
- hbuilder x 4.15
-  微信基础库 3.4.5

**Comment by Otto-J** [comment]
提供下代码吧，图片复制不了。
提供更多信息，有助于定位和解答你的问题。

**Comment by Bo-Teng** [comment]
@Otto-J  
大致的复现代码就是这样
组件：
```
```
<template>
	<input type="text" />
</template>

<script>
export default {
	behaviors: ['uni://form-field']
};
</script>
```
使用
<template>
	<view class="content">
		<form action="">
			<CInput />
		</form>
	</view>
</template>

<script>
import CInput from '../CInput.vue';
export default {
	components: {
		CInput
	}
};
</script>
```

控制台错误：
Error: Behaviors should be constructed with Behavior()
    at fi (WASubContext.js?t=wechat&s=1717723544469&v=3.4.5:1)
    at Ci (WASubContext.js?t=wechat&s=1717723544469&v=3.4.5:1)
    at Module.Ei (WASubContext.js?t=wechat&s=1717723544469&v=3.4.5:1)
    at Wr (WASubContext.js?t=wechat&s=1717723544469&v=3.4.5:1)
    at t.<anonymous> (WASubContext.js?t=wechat&s=1717723544469&v=3.4.5:1)
    at WASubContext.js?t=wechat&s=1717723544469&v=3.4.5:1
    at Component (vendor.js? [sm]:7481)
    at Object.createPage2 [as createPage] (vendor.js? [sm]:7436)
    at button.js? [sm]:42
    at WASubContext.js?t=wechat&s=1717723544469&v=3.4.5:1(env: Windows,mp,1.06.2404301; lib: 3.4.5)
Component @ vendor.js? [sm]:7481
createPage2 @ vendor.js? [sm]:7436
(anonymous) @ button.js? [sm]:42

**Comment by Bo-Teng** [comment]
@Otto-J  
我刚才改成了vue2编译，发现是没有报错

**Comment by obhasqr** [comment]
我也遇到了这个问题，版本是hbx 4.18，vue3，尝试将 "uni://form-field" 改为 "wx://form-field" 可以正常运行

**Comment by Bo-Teng** [comment]
@obhasqr  虽然可以没有报错，但是在form的submit中拿不到input的值

**Comment by Bo-Teng** [comment]
@Otto-J  hi,老哥希望有空能回复一下这个问题

**Comment by Otto-J** [comment]
嗯，我看下这个问题。有进展我会更新

**Comment by Bo-Teng** [comment]
@Otto-J  我在上回答有提到，虽然按照这个方法是可以解决控制台报错，但是form组件的submit事件里拿不到input的value值，
![image](https://github.com/dcloudio/uni-app/assets/73982811/623eb842-276d-4b2d-bfbc-9291d2bbdb16)

而且我绑定在CIpnut上的name属性在微信开发者工具编译后的代码中没有看到
![image](https://github.com/dcloudio/uni-app/assets/73982811/12d3a33d-6bcc-48b3-a5b5-32f1af87f445)

如果在编译后手动加上name拿到的值就会是一个null,而我期望是能拿到真实的值（微信文档提供的代码片段）
[片段地址](https://developers.weixin.qq.com/s/3FjTHCmY7ghg)
![image](https://github.com/dcloudio/uni-app/assets/73982811/aeee6fe8-920c-41c7-a9eb-3389942aa3d9)

**Comment by Otto-J** [comment]
使用 ` behaviors: ['wx://form-field']` 可以，` behaviors: ['uni://form-field']` 失败的问题找到了，稍等我提供解决方案。

你提到的不同代码我看一下

**Comment by obhasqr** [comment]
@Otto-J 大佬微信小程序提供的其他内置 behaviors 支持吗？我在之前版本用 uni://form-field-group 也是可以的，这次遇到出错后改为 wx://form-field-group 也能工作，但是看你的提交里没有真的其他 behaviors 的处理，不知道这么用会不会有问题？
微信小程序内置 behaviors：https://developers.weixin.qq.com/miniprogram/dev/component/form.html#%E4%BD%BF%E7%94%A8%E5%86%85%E7%BD%AE-behaviors

**Comment by Otto-J** [comment]
无论 vue2 vue3 只要使用了自定义组件来包装 form ，触发 submit 就拿不到

> @Otto-J 大佬微信小程序提供的其他内置 behaviors 支持吗？我在之前版本用 uni://form-field-group 也是可以的，这次遇到出错后改为 wx://form-field-group 也能工作，但是看你的提交里没有真的其他 behaviors 的处理，不知道这么用会不会有问题？ 微信小程序内置 behaviors：https://developers.weixin.qq.com/miniprogram/dev/component/form.html#%E4%BD%BF%E7%94%A8%E5%86%85%E7%BD%AE-behaviors

感谢反馈，这个我看文档中目前只提到了 wx://form-field 这个，其他的
wx://form-field-group
wx://form-field-button
粗看逻辑应该也会走到下面这里。

[      behaviors.push(behavior.replace('uni://', '__GLOBAL__' + '://'))
](https://github.com/dcloudio/uni-app/blob/f11ad857866540d01faad82b0ca7c2f7de69c30e/packages/uni-mp-core/src/runtime/componentOptions.ts#L122)

这个问题解决了我会看下是否可以明确支持。如果你担心编译结果有问题，可以在产物 vendor.js 里搜索 `return MPComponent(options);` 打印在 options，这是最终编译结果，你可以尝试看看

**Comment by obhasqr** [comment]
@Otto-J 好的，我这边目前直接用 wx://form-field-group 是可以的
![image](https://github.com/dcloudio/uni-app/assets/5682731/ce67b500-8db8-4846-bfc8-19504b17deb1)

**Comment by Otto-J** [comment]
解决了，是刚才解决的问题。请你按照下面的方式先临时绕过

找到依赖安装位置，
HBuilderX 用户打开 `/Applications/HBuilderX-Dev.app/Content
s/HBuilderX/plugins/uniapp-cli-vite/node_modules/@dcloudio/uni-mp-weixin/dist/uni.
mp.esm.js`
cli 用户打开 `node_modules/@dcloudio/uni-mp-weixin/dist/uni.mp.esm.js`

搜索 `__GLOBAL__://` 得到 2 个结果，如果你是微信手动修改为 `wx://` 。

我的修复也是解决这个问题。

可以使用下面代码验证

component file
```html
<template>
  <div>
    <input type="text" style="border: solid 1px #999999;height: 80px;" :value="modelValue" @input="onInput" />
  </div>
</template>

<script>
export default {
  behaviors: ['uni://form-field'],
  props: {
    modelValue: {
      type: String,
      default: ''
    },
  },
  methods: {
    onInput(e) {
      this.$emit('update:modelValue', e.detail.value)
    }
  },
};
</script>
```

index. page
```html
<template>
    <view class="content">
        <view>input</view>
        <form @submit="onSumbit">
            <div>value:: {{ testValue.userName }}</div>
            <CInput name='userName' v-model="testValue.userName" />
            <button form-type="submit">Submit</button>
        </form>
    </view>
</template>

<script>
import CInput from '../../components/c1.vue';
export default {
    components: {
        CInput
    },
    data() {
        return {
            testValue: {
                userName: 'otto'
            }
        }
    },
    methods: {
        onSumbit(e) {
            console.log(33, e.detail.value);
        }
    }
};
</script>
```
控制台展示 `33 {userName: "otto23"}`

#Bo-Teng

**Comment by Otto-J** [comment]
关联 ask
https://ask.dcloud.net.cn/question/192627
https://ask.dcloud.net.cn/question/192246
https://ask.dcloud.net.cn/question/175405

**Comment by Bo-Teng** [comment]
@Otto-J  感谢
