### ISSUE TITLE
如何自定义 babel

### ISSUE THREAD

**Issue by oooplz** [dcloudio/uni-app#4961]
[babel-plugin-lodash](https://github.com/lodash/babel-plugin-lodash) 用不了
跟着官方教程来用不了 我要崩溃了 能不能给个案例，目前是 vue2 vue.config.js

**Comment by Otto-J** [comment]
感谢反馈，请提供更多信息：
- 你需要用到 lodash 的那些函数，使用 lodash/fp 指定导入不可以吗？
- 你要运行到那个平台？h5 还是小程序、app？复现工程是否可以提供

提供更多信息，有助于定位和解答你的问题。

**Comment by oooplz** [comment]
需要使用它是因为打包某些平台有代码大小限制，老项目了，所以不可能人工修改为 lodash/fp，代码中全部使用 ``import _ form ldoash;`` 语句引用，我们项目已经花时间调整了分包和公共组件，目前没有这方面的困扰了，留下 issue 看是否能帮助其他人，另外 vue3 已经趋向稳定了，所以大概率不会有其他人遇到这种问题。感谢回复
