### ISSUE TITLE
iPhone 操作系统升级到最新版（测试版），所有页面上下滑动失效

### ISSUE THREAD

**Issue by AJMstr** [dcloudio/uni-app#497]
用 uni-app 开发的app，在iPhone手机上，最新操作系统（测试版）下，所有页面上下滑动失效。
包括 官方提供的 “hello uni-app”都有这个问题

**Comment by hbcui1984** [comment]
具体版本号多少？

**Comment by AJMstr** [comment]
ios 13 beta 2

**Comment by zhetengbiji** [comment]
HBuilderX 2.3.0 已修复
