### ISSUE TITLE
uniapp 我使用npx升级到最新以后编译小程序使用import报错了

### ISSUE THREAD

**Issue by hgaoping** [dcloudio/uni-app#4975]
引入一个VUE组件

import test from './test.vue'

调用组件
<template>
  <test />
</template>

编译微信小程序报错
[plugin:uni:mp-using-component] Expected ',' or '}' after property value in JSON at position 25

相关版本，为什么我明明说是升级到正式版结果是升级到alpha
 "dependencies": {
    "@dcloudio/uni-app": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-app-plus": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-components": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-h5": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-mp-alipay": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-mp-baidu": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-mp-jd": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-mp-kuaishou": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-mp-lark": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-mp-qq": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-mp-toutiao": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-mp-weixin": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-mp-xhs": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-quickapp-webview": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-ui": "^1.5.5",
    "pinia": "^2.1.7",
    "vue": "^3.4.27",
    "vue-i18n": "^9.13.1"
  },
  "devDependencies": {
    "@dcloudio/types": "^3.4.8",
    "@dcloudio/uni-automator": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-cli-shared": "3.0.0-alpha-4010520240507001",
    "@dcloudio/uni-stacktracey": "3.0.0-alpha-4010520240507001",
    "@dcloudio/vite-plugin-uni": "3.0.0-alpha-4010520240507001",
    "@uni-helper/uni-app-types": "^0.5.13",
    "@uni-helper/uni-ui-types": "^0.5.14",
    "@vue/runtime-core": "^3.4.27",
    "@vue/tsconfig": "^0.5.1",
    "miniprogram-api-typings": "^3.12.2",
    "pinia-plugin-persistedstate": "^3.2.1",
    "sass": "^1.77.4",
    "typescript": "^5.4.5",
    "vite": "5.2.8",
    "vue-tsc": "^2.0.19"
  }

**Comment by Otto-J** [comment]
感谢反馈，请参考 https://github.com/dcloudio/uni-app/issues/4952
如果仍有问题，请继续评论和回复

**Comment by Max0897** [comment]
+1
