### ISSUE TITLE
uniapp 我使用npx升级到 3.0.0-alpha-4010520240507001 以后编译编译微信小程序报错了

### ISSUE THREAD

**Issue by sonofmagic** [dcloudio/uni-app#4977]
升级 uni-app 到 3.0.0-alpha-4010520240507001 版本之后，执行编译到微信小程序报错:

```
node_modules/@dcloudio/uni-cli-shared/dist/vue/transforms/transformComponent.js:6
function createTransformComponentLink(name, type = compiler_core_1.NodeTypes.DIRECTIVE) {
                                                                             ^

TypeError: Cannot read properties of undefined (reading 'DIRECTIVE')
    at createTransformComponentLink (/Users/icebreaker/Documents/GitHub/uni-app-vite-vue3-tailwind-vscode-template/node_modules/@dcloudio/uni-cli-shared/dist/vue/transforms/transformComponent.js:6:78)
    at Object.<anonymous> (/Users/icebreaker/Documents/GitHub/uni-app-vite-vue3-tailwind-vscode-template/node_modules/@dcloudio/uni-cli-shared/dist/vue/transforms/index.js:55:88)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
```

报的这个错误，起都起不来

回滚到 `3.0.0-4000820240401001` 版本，可以正常启动

**Comment by Otto-J** [comment]
感谢反馈，升级到最新的 @3.0.0-alpha-4010920240606001 是否可以解决你的问题

如果不可以的话：

使用标准模板可以启动吗？
请提供复现工程或者单页面代码，排查下是通用的方法有问题，还是有边缘情况没考虑到。
https://uniapp.dcloud.net.cn/quickstart-cli.html#%E5%88%9B%E5%BB%BAuni-app

**Comment by sonofmagic** [comment]
项目升级到 `@3.0.0-alpha-4010920240606001` 的确解决了这个问题。

## 复现工程:

### ✅ uni-app `3.0.0-4000820240401001` 版本，正常运行

[uni-app-vite-vue3-tailwind-vscode-template/main 分支](https://github.com/sonofmagic/uni-app-vite-vue3-tailwind-vscode-template) 

### ❌ uni-app `3.0.0-alpha-4010520240507001` 版本，运行失败

[uni-app-vite-vue3-tailwind-vscode-template/uni-app-3.0.0-alpha-4010520240507001 分支](https://github.com/sonofmagic/uni-app-vite-vue3-tailwind-vscode-template/tree/uni-app-3.0.0-alpha-4010520240507001) 

> [!NOTE]
> 一开始升级到 `3.0.0-alpha-4010520240507001` ，报出的是上面 https://github.com/dcloudio/uni-app/issues/4977#issue-2342250524 那个错误，后来我尝试升级 `uni-app` 相关依赖到 `3.0.0-alpha-4010920240606001` 之后，回到这个分支重新 `yarn` 安装包之后，现在不报那个 `@vue/compiler-core` 的错误了，反而报了:
> ```
> [plugin:uni:mp-using-component] Expected ',' or '}' after property value in JSON at position 37
> at pages/index/index.vue:1:0
> ```
> 不过这个问题，我看到其他 issue 里面已经有解了 https://github.com/dcloudio/uni-app/issues/4952

### ✅ uni-app `3.0.0-alpha-4010920240606001` 版本，正常运行

[uni-app-vite-vue3-tailwind-vscode-template/uni-app-3.0.0-alpha-4010920240606001 分支](https://github.com/sonofmagic/uni-app-vite-vue3-tailwind-vscode-template/tree/uni-app-3.0.0-alpha-4010920240606001
)
## 复现步骤

1. `fork / clone` 上述链接中的[项目](https://github.com/sonofmagic/uni-app-vite-vue3-tailwind-vscode-template)  指定分支
2. 执行 `yarn` 安装包
3. 执行 `yarn dev` 运行，此时可见错误出现于命令行。

## 预期行为

执行 `yarn dev` 和 `yarn build` 命令，正常运行，且可见于微信开发者工具

**Comment by Otto-J** [comment]
嗯，是的，目前是已知、已解决的问题。最新版本的的 alpha 可以解决。

感谢再次反馈，后续如果仍有问题请继续留言
