### ISSUE TITLE
使用uni.chooseLocation  API定位时偏移过大

### ISSUE THREAD

**Issue by jy-githup** [dcloudio/uni-app#4978]
H5端，使用了高德地图，运行在专有钉钉环境中
原生获取定位信息准确，再次使用API中的方法进行定位时偏差很大
![WechatIMG185](https://github.com/dcloudio/uni-app/assets/66984015/87dd61c4-952a-41f0-ad45-93cbdc168be8)

**Comment by Otto-J** [comment]
请提供更多信息，vue 版本，单页面源码。

你的意思是现在运行到 web ，嵌套在钉钉小程序中，客户端可以获取正确的位置，web 不可以，怎么理解再次使用 api 的方法，使用的什么方法？

提供更多信息，有助于定位和解答你的问题。

**Comment by jy-githup** [comment]
vue版本：vue2
H5页面，可在浏览器中运行，本地调试定位准确，打包部署到专有钉钉，浙政钉后定位会偏移
基于高德地图，已经配置了高德地图API密钥
<img width="806" alt="image" src="https://github.com/dcloudio/uni-app/assets/66984015/80e66b5e-c512-4c4c-a6f2-52ef23efdde1">
<img width="979" alt="image" src="https://github.com/dcloudio/uni-app/assets/66984015/13810cce-8263-4bc2-bd71-514f61a8752b">
<img width="618" alt="image" src="https://github.com/dcloudio/uni-app/assets/66984015/e1b8f8f6-ba4c-4942-8b10-029398348830">

**Comment by jy-githup** [comment]
暂时想不到什么原因，或是什么地方遗漏了，请大佬提供一下思路

**Comment by Otto-J** [comment]
相同的位置，用一个定位准确、使用另一个定位方案不准确，这种一般是坐标系的原因。

我看到你使用了浏览器的定位和地图 sdk，一般就是这个原因了。你翻找下 sdk 帮助文档，搜索一下 坐标是，或者问题看看

**Comment by Otto-J** [comment]
https://lbs.amap.com/api/webservice/guide/api/convert
坐标转换是一类简单的HTTP接口，能够将用户输入的非高德坐标（GPS坐标、mapbar坐标、baidu坐标）转换成高德坐标。
