### ISSUE TITLE
uni.onSocketMessage在APP端不能检测信息

### ISSUE THREAD

**Issue by huiliaoning** [dcloudio/uni-app#498]
**问题描述**
uni.onSocketMessage在Chrome浏览器预览时候可以成功的监测能检测到socket连接成功和服务端推送的消息，在真机运行预览只能候能检测到socket连接成功，但不能监测服务端推送的消息，这个问题时好时坏，把调试基座关了再打开重复几次过程中偶尔会成功，目前确定socket服务端没有任何问题。

以下是源代码：
onLoad(res) {

			uni.connectSocket({
				url: 'ws://116.62.61.131:8282',
			});
			uni.onSocketOpen(function(res) {

				console.log('WebSocket连接已打开！');
			});

			uni.onSocketError(function(res) {
				console.log('WebSocket连接打开失败，请检查！');
			});

			uni.onSocketMessage((res) => {
				var message = JSON.parse(res.data);
				console.log(JSON.parse(res.data));
				switch (message.message_type) {
					case 'int':
						uni.setStorageSync('client_id', message.content)
						this.$http.post('/home/chat/binduid', {
							client_id: message.content,
							roomid: 1,
							uid: 1
						}).then((res) => {
							if (res.result == 'success') {
								console.log('加入聊天室成功')
							} else {
								console.log('加入聊天室失败')
							}

						})
						break;
					case 'text':
						uni.$emit('push-message', message);
						break;
				}
			});
			//每30秒发送一次心跳
			setInterval(() => {
				uni.sendSocketMessage({
					data: 'heart beat'
				});
			}, 3000)
}

**Comment by zhetengbiji** [comment]
出问题的是iOS还是安卓？

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启

**Comment by qinkaiyuan** [comment]
onSocketError

websocket连接服务器错误时

小程序端会触发 onSocketError，onSocketClose 这两个事件

而 app端只会 触发 onSocketError 不会触发 onSocketClose 

代码如下：

```
public static websocketConnect() {
    uni.connectSocket({
      url: CommonUtil.websocketUrl + 'webSocket/message, 
      complete(res) {
        console.log(res)
      }
    })

    uni.onSocketOpen(res => {
      console.log(res)
    })

    uni.onSocketError(res => {
      console.log("触发了错误")
    })

    uni.onSocketClose(res => {
      console.log("触发了关闭")
    })
  }
```

**Comment by yujun96** [comment]
解决了吗？大哥？？我也碰到这个问题，特别急
