### ISSUE TITLE
rich-text 重复文案 

### ISSUE THREAD

**Issue by successColin** [dcloudio/uni-app#4985]
微信小程序
重新实施步骤
1、rich-text :nodes="detail"
2、<p style="line-height: 2;">西兴古镇</p>↵<p style="line-height: 2;">杭州藏在闹市之中的千年古镇&mdash;西兴古镇💯</p>↵<p style="line-height: 2;">位于钱塘江南岸，地铁1号线&ldquo;西兴站&rdquo;出站不远即可到达，它的名气远远没有其他古镇大，甚至在杭州的景点目录里也是作为小众游览点🕵️&zwj;♀️。</p>↵<p style="line-height: 2;">西兴古镇因春秋末期越国大夫范蠡🧜&zwj;♀️在此筑城拒吴而得名，整个古镇以线形展开，保持一河两街的基本格局，一边是石板路上的民居，另一边则是小桥流水。</p>↵<p style="line-height: 2;">2002年，西兴老街列入杭州市十大历史保护街区之一，经过专家的讨论，古镇不走商业化的路子，确定了原封不动、完整保护的方案☺️。</p>↵<p style="line-height: 2;">古镇两岸密布着保存完好的明清时期的民居🏠，这里大多住着本地的居民，过着正常的生活，只有偶尔几家做着小本生意，因为没有商业化店铺的入驻，这里的游人也非常稀少。</p>
![1950379fddc91d86fca040f28e2fe7c](https://github.com/dcloudio/uni-app/assets/42706993/69ead644-9e86-4e83-be05-49fe7e813b8b)
![4a2b626f-82cb-40ca-8b59-59d6cff1e369](https://github.com/dcloudio/uni-app/assets/42706993/1a24ab59-28cc-4c24-afa1-3440ebcc068c)

实际结果是什么？
重复出现 位于钱塘江南岸，地铁1号线，等文案

**Comment by Otto-J** [comment]
是 vue2 还是 vue3 发布到微信小程序的 rich-text ？


提供下单页面源码吧。重点排查下相关生命周期、事件。

**Comment by bfc846958672** [comment]
长时间未响应，关闭本issue。 如还有问题，可 reopen issue 继续讨论。
