### ISSUE TITLE
vue3版本app中vite编译器使用import.meta.glob报错，不能正常使用

### ISSUE THREAD

**Issue by wangchunling** [dcloudio/uni-app#4995]
使用cli开发模式，相关依赖版本为 "3.0.0-4010520240507001"
开发支付宝小程序时，import.meta.glob报错。
![image](https://github.com/dcloudio/uni-app/assets/6300399/2c4952d4-ddcc-444d-b3c4-71d62909ea56)

**Comment by Otto-J** [comment]
经过验证，最新版本的 cli 相关依赖升级到 vite v5，使用 glob 正常使用。vite v5 其中一个改动是废弃了 globEager 的支持，如狗是写法报错，请参考最新 vite 文档 https://cn.vitejs.dev/guide/features.html#glob-import
