### ISSUE TITLE
使用cli版本模式开发，import.meta.glob 或者 globEager报错

### ISSUE THREAD

**Issue by wangchunling** [dcloudio/uni-app#4996]
请更新至3.2.10以上版本测试

_Originally posted by @fxy060608 in https://github.com/dcloudio/uni-app/issues/2944#issuecomment-943165992_

**Comment by bfc846958672** [comment]
提供一下可复现的demo工程

**Comment by bfc846958672** [comment]
长时间未响应，关闭本issue。 如还有问题，可 reopen issue 继续讨论。
