### ISSUE TITLE
vite创建的ts项目，button组件的类型不正确

### ISSUE THREAD

**Issue by like0413** [dcloudio/uni-app#4998]
![image](https://github.com/dcloudio/uni-app/assets/48686374/4d3f0af1-68da-42e5-bde5-e59940f35dbd)
tsconfig.json：
![image](https://github.com/dcloudio/uni-app/assets/48686374/6132a093-b0a1-4678-b545-a31ea23e51cd)

识别成原生button了？

**Comment by extclp** [comment]
要类型的话参考 https://uni-helper.js.org/uni-app-types

**Comment by bfc846958672** [comment]
长时间未响应，关闭本issue。 如还有问题，可 reopen issue 继续讨论。
