### ISSUE TITLE
vue3 + js，setup 中 import 组件，编译到微信小程序报错

### ISSUE THREAD

**Issue by sunpm** [dcloudio/uni-app#5002]
复现：https://github.com/sunpm/uniapp-issue

模板是官方的，只是加了 Demo.vue 组件，然后在 index.vue 中引入

## 报错
[plugin:commonjs] Unexpected token D in JSON at position 25
at pages/index/index.vue:1:0

## 开发环境
System:
OS: macOS 12.6.5
Binaries:
Node: 18.17.1
Pnpm: 9.1.1
npm: 9.6.7

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/4952

**Comment by sunpm** [comment]
> #4952

谢谢
