### ISSUE TITLE
微信小程序，拖动顶部选项卡异常

### ISSUE THREAD

**Issue by TheBigBright** [dcloudio/uni-app#501]
**问题描述**
微信小程序端，拖动顶部选项卡异常，如果快速滑动切换选项卡，会自动滑动选项卡。已关闭微信小程序开发工具ES6转ES5。安卓App无此问题。

**Comment by hbcui1984** [comment]
问题描述再详细一些，可以配合截图或录屏

**Comment by BigBright2019** [comment]
![20190627_161936](https://user-images.githubusercontent.com/24493654/60249490-86f41d00-98f7-11e9-8dec-8d65de020ff5.gif)

如上图所示，左右晃动，测试设备：一加六，国际版wechat v7.0.4

**Comment by BigBright2019** [comment]
> 问题描述再详细一些，可以配合截图或录屏

麻烦看下吧，谢谢。

**Comment by zhetengbiji** [comment]
示例有问题，解决方式参考：[hello uni-app](https://github.com/dcloudio/hello-uniapp/commit/4e767e71195613f473e0b49cb67fe8d76f08f2a8)
