### ISSUE TITLE
vue3中useAttrs在计算属性中无法使用

### ISSUE THREAD

**Issue by xw-xw12** [dcloudio/uni-app#5014]
升级版本后useAttrs 无法使用，需要在使用前先用变量接一下
`const attrs = useAttrs()`
`import { computed,useAttrs } from 'vue'
const params = computed(()=>{
	return {
		selection:selection.value,
		...useAttrs()
	}
})`
报错信息为
 Cannot read properties of null (reading 'setupContext')

**Comment by bfc846958672** [comment]
我这边正常使用useAttr，可以提供一下复现工程

**Comment by bfc846958672** [comment]
长时间未响应，关闭本issue。 如还有问题，可 reopen issue 继续讨论。
