### ISSUE TITLE
input  h5 父级有transform:scale(1.8)  -> transform:scale(1) 动画的话 input 高计算错误 没有回到 scale(1) 高度

### ISSUE THREAD

**Issue by DestinyHunter** [dcloudio/uni-app#502]
**问题描述**

input  h5 父级有transform:scale(1.8)  -> transform:scale(1) 动画的话 input 高计算错误 没有回到 scale(1) 高度

**预期结果**
设置input height:40; min-height: 40;  得到 40 高度的input

**实际结果**
 得到 40.7 高度的input

**系统信息:**
 - 发行平台: H5
 - HBuilderX版本 2.02

**Comment by zhetengbiji** [comment]
你可以尝试一下使用 [CLI](https://uniapp.dcloud.io/quickstart?id=%E9%80%9A%E8%BF%87vue-cli%E5%91%BD%E4%BB%A4%E8%A1%8C)运行是否仍然存在此问题

**Comment by DestinyHunter** [comment]
就是用的 cli

**Comment by zhetengbiji** [comment]
测试未复现此问题，请提供一下复现问题的demo以及步骤

**Comment by DestinyHunter** [comment]
```
<view class="dialog" :class="show ? 'show' : ''"><input type="text" value="高度不对" /></view>
<button type="primary" @click="showDialog">dialog</button>
```
```
methods: {
	showDialog() {
		this.show = !this.show
	}
}
```

```
.dialog {
	display: none;
	background: white;
	width: 500upx;
	height: 400upx;
	position: fixed;
	top: 50%;
	left: 50%;
	margin: -200upx 0 0 -250upx;
	transform: scale(1.8);
	transition: 0.3s;
	input {
		width: 500upx;
		height: 80upx;
		background: black;
	}
	&.show {
		display: block;
		transform: scale(1);
	}
}
```

上边写错了  高变成70多
![image](https://user-images.githubusercontent.com/20897838/60418012-781dab00-9c14-11e9-8959-afb6ed724528.png)
![image](https://user-images.githubusercontent.com/20897838/60418027-8370d680-9c14-11e9-88cc-90d7c3c43670.png)

**Comment by zhetengbiji** [comment]
> ```
> <view class="dialog" :class="show ? 'show' : ''"><input type="text" value="高度不对" /></view>
> <button type="primary" @click="showDialog">dialog</button>
> ```
> 
> 
> ```
> methods: {
> 	showDialog() {
> 		this.show = !this.show
> 	}
> }
> ```
> 
> 
> ```
> .dialog {
> 	display: none;
> 	background: white;
> 	width: 500upx;
> 	height: 400upx;
> 	position: fixed;
> 	top: 50%;
> 	left: 50%;
> 	margin: -200upx 0 0 -250upx;
> 	transform: scale(1.8);
> 	transition: 0.3s;
> 	input {
> 		width: 500upx;
> 		height: 80upx;
> 		background: black;
> 	}
> 	&.show {
> 		display: block;
> 		transform: scale(1);
> 	}
> }
> ```
> 
> 
> 上边写错了  高变成70多
> 
> ![image](https://user-images.githubusercontent.com/20897838/60418012-781dab00-9c14-11e9-8959-afb6ed724528.png)
> 
> ![image](https://user-images.githubusercontent.com/20897838/60418027-8370d680-9c14-11e9-88cc-90d7c3c43670.png)

更新一下依赖（npm update），你这结构看起来是老版本的

**Comment by DestinyHunter** [comment]
> > ```
> > <view class="dialog" :class="show ? 'show' : ''"><input type="text" value="高度不对" /></view>
> > <button type="primary" @click="showDialog">dialog</button>
> > ```
> > 
> > 
> > ```
> > methods: {
> > 	showDialog() {
> > 		this.show = !this.show
> > 	}
> > }
> > ```
> > 
> > 
> > ```
> > .dialog {
> > 	display: none;
> > 	background: white;
> > 	width: 500upx;
> > 	height: 400upx;
> > 	position: fixed;
> > 	top: 50%;
> > 	left: 50%;
> > 	margin: -200upx 0 0 -250upx;
> > 	transform: scale(1.8);
> > 	transition: 0.3s;
> > 	input {
> > 		width: 500upx;
> > 		height: 80upx;
> > 		background: black;
> > 	}
> > 	&.show {
> > 		display: block;
> > 		transform: scale(1);
> > 	}
> > }
> > ```
> > 
> > 
> > 上边写错了  高变成70多
> > ![image](https://user-images.githubusercontent.com/20897838/60418012-781dab00-9c14-11e9-8959-afb6ed724528.png)
> > ![image](https://user-images.githubusercontent.com/20897838/60418027-8370d680-9c14-11e9-88cc-90d7c3c43670.png)
> 
> 更新一下依赖（npm update），你这结构看起来是老版本的

好的.. 确实是我没更新的问题. 最新的没问题

**Comment by DestinyHunter** [comment]
gg
