### ISSUE TITLE
cli 创建的工程app 打包提示failed to load config from /Users/macbookpro/Desktop/uniApp/i/my-vue3/vite.config.js

### ISSUE THREAD

**Issue by zhouxianjia** [dcloudio/uni-app#5021]
23:48:36.788 failed to load config from /Users/macbookpro/Desktop/uniApp/i/my-vue3/vite.config.js
23:48:36.794 error during build:
23:48:36.796 Error: 
23:48:36.804 You installed esbuild for another platform than the one you're currently using.
23:48:36.811 This won't work because esbuild is written with native code and needs to
23:48:36.817 install a platform-specific binary executable.
23:48:36.818 Specifically the "@esbuild/darwin-arm64" package is present but this platform
23:48:36.825 needs the "@esbuild/darwin-x64" package instead. People often get into this
23:48:36.832 situation by installing esbuild with npm running inside of Rosetta 2 and then
23:48:36.839 trying to use it with node running outside of Rosetta 2, or vice versa (Rosetta
23:48:36.840 2 is Apple's on-the-fly x86_64-to-arm64 translation service).
23:48:36.847 If you are installing with npm, you can try ensuring that both npm and node are
23:48:36.848 not running under Rosetta 2 and then reinstalling esbuild. This likely involves
23:48:36.856 changing how you installed npm and/or node. For example, installing node with
23:48:36.864 the universal installer here should work: https://nodejs.org/en/download/. Or
23:48:36.865 you could consider using yarn instead of npm which has built-in support for
23:48:36.874 installing a package on multiple platforms simultaneously.
23:48:36.882 If you are installing with yarn, you can try listing both "arm64" and "x64"
23:48:36.892 in your ".yarnrc.yml" file using the "supportedArchitectures" feature:
23:48:36.893 https://yarnpkg.com/configuration/yarnrc/#supportedArchitectures
23:48:36.902 Keep in mind that this means multiple copies of esbuild will be present.
23:48:36.911 Another alternative is to use the "esbuild-wasm" package instead, which works
23:48:36.921 the same way on all platforms. But it comes with a heavy performance cost and
23:48:36.922 can sometimes be 10x slower than the "esbuild" package, so you may also not
23:48:36.931 want to do that.

以上是app 模拟器上运行是报错的的提示 
MacOS   M1

**Comment by bfc846958672** [comment]
你好，社区有多种解决方案， [详情](https://ask.dcloud.net.cn/question/145281)
