### ISSUE TITLE
wd-icon 图标在非 http\https 协议中无法显示

### ISSUE THREAD

**Issue by mqyun** [dcloudio/uni-app#5022]
<img width="1352" alt="image" src="https://github.com/dcloudio/uni-app/assets/28822796/c0deaf32-61e6-40bb-bdd2-c236ebc603eb">
组件依赖的字体库取的是当前环境的协议头，如果运行环境是 file 协议的话，这个资源引用报错。

**Comment by GRCmade** [comment]
直接改成http不好使吗
