### ISSUE TITLE
升级到 3.0.0-alpha-4010520240507001 执行uni -p mp-weixin 编译失败

### ISSUE THREAD

**Issue by CrazyWalk** [dcloudio/uni-app#5023]
执行后：[plugin:uni:mp-using-component] Unexpected token H in JSON at position 31

之前用的3.0.0-alpha-4010920240606001 没有此问题

之前的帖子：https://github.com/dcloudio/uni-app/issues/4975
并没有修复完毕。 
![image](https://github.com/dcloudio/uni-app/assets/14954665/389d09d1-f94d-4cc9-b837-35f0757422c4)

**Comment by bfc846958672** [comment]
通过npx @dcloudio/uvm@latest 命令升级一下版本，[相关问题链接](https://ask.dcloud.net.cn/question/194783?item_id=277348&rf=false)

**Comment by CrazyWalk** [comment]
> 通过npx @dcloudio/uvm@latest 命令升级一下uniapp版本，[相关问题链接](https://ask.dcloud.net.cn/question/194783?item_id=277348&rf=false
感谢，已得到修复
