### ISSUE TITLE
H5 中uni-easyinput type为number时 显示有Bug

### ISSUE THREAD

**Issue by WGLKing** [dcloudio/uni-app#5028]
在H5 中uni-easyinput type为number时 v-model初始化为null时下面这代代码有执行报错

const value = typeof props2.modelValue === "undefined" ? props2.value : props2.modelValue;
  const cache = ref(typeof value !== "undefined" ? value.toLocaleString() : "");

**Comment by bfc846958672** [comment]
https://github.com/dcloudio/uni-app/pull/5040
