### ISSUE TITLE
app崩溃后怎么把错误日志上传到服务器

### ISSUE THREAD

**Issue by vlijiantao** [dcloudio/uni-app#503]
**问题描述**
app崩溃后怎么把错误日志上传到服务器？

**补充信息**
想做到用户app崩溃后自动把崩溃信息上传到服务器，服务器提供上传错误的接口。想知道是否有对应的事件或者生命周期可以监听到呢？？？

**Comment by zhetengbiji** [comment]
这个自己监听的话需要在原生层做，如果勾选了友盟统计，在友盟后台可以看到。
