### ISSUE TITLE
uniapp微信小程序打包成h5，无法以uni["navigateTo"]的方式使用uni.navigateTo

### ISSUE THREAD

**Issue by AaronWongM** [dcloudio/uni-app#5032]
uniapp微信小程序打包成h5，无法以uni["navigateTo"]的方式使用uni.navigateTo，小程序使用正常
会报错TypeError: uni[n] is not a function

```js
// 公共跳转方法  
jumpPage(url, jumpType = "navigateTo") {  
    uni[jumpType]({  
        url  
    })  
}
```
使用时
```js
// 判断是否要保留当前页的逻辑  
...  
// 得出应该使用的跳转方式  
const jumpType = true ? "navigateTo" : "redirectTo"  
// 跳转  
jumpPage('page/index/index', jumpType )
```

**Comment by GRCmade** [comment]
我这里测试的正常，可能是你得写成：
```
uni[jumpType]({  
        url:url  
    })  
```
![7db8af8578f4b128ba1cbb018eca7aca](https://github.com/user-attachments/assets/c37e0f8b-aebd-4a3b-9295-1d5f6e0d1b0f)

**Comment by AaronWongM** [comment]
> 我这里测试的正常，可能是你得写成：
> 
> ```
> uni[jumpType]({  
>         url:url  
>     })  
> ```
> 
> ![7db8af8578f4b128ba1cbb018eca7aca](https://private-user-images.githubusercontent.com/97457593/348243007-c37e0f8b-aebd-4a3b-9295-1d5f6e0d1b0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwMTM1MjQsIm5iZiI6MTcyMTAxMzIyNCwicGF0aCI6Ii85NzQ1NzU5My8zNDgyNDMwMDctYzM3ZTBmOGItYWViZC00YTNiLTkyOTUtMWQ1ZjZlMGQxYjBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE1VDAzMTM0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMzEwODYzZDFhNmJlNjJhODNiY2MxMzYxZGQyMGI0OWVmNTYwYTk5YWNmM2Y4YzAzOGU2ZGFiNjg3YzRhNjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WiJXorawe6-vEOBxf7YbqN5ZjPXZWQIqSLtXetIvb4o)

本地运行是没有问题的，但是点击hbuilderX的发行->网站-PC Web或手机H5之后，将打包出来的文件部署到线上，才会报错，此时在控制台打印uni是没有对应的跳转方法的

**Comment by GRCmade** [comment]
感谢反馈，确认有这个问题，你先暂时使用uni.这种方式吧，之后会调整

**Comment by bfc846958672** [comment]
发行模式下， 代码会压缩， 方法名也会压缩调整，所以用原来的方法名时无效的，可以采用一下方案
```
switch(type) {
	case : 'navigateTo': uni.navigateTo({ url });break;
	case : 'redirectTo': uni.redirectTo({ url });break;
}
```
