### ISSUE TITLE
使用uni.authorize()出现授权弹窗，但是没有点击允许之后的回调？

### ISSUE THREAD

**Issue by Zillionnn** [dcloudio/uni-app#504]
**问题描述**
使用uni.authorize()出现授权弹窗，但是没有点击允许之后的回调？
**复现步骤**
      const _self = this;
      console.log("get AUTHOR??",e);
      uni.authorize({
        scope: "scope.userInfo",
        success: function(a, b, c) {
          console.log("AUTH", a, b, c);
          _self.mpWxLogin();
        },
        fail: (err) => {
          console.error('AUTH ERROR',err);          
        }
      });

失败之后再点了授权按钮还是 失败，除非退出小程序，再进入，就不用授权了；

**预期结果**
  出现授权弹窗后，点击允许 后的回调
**实际结果**

**系统信息:**
xiaomi8 se

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Zillionnn** [comment]
目前解决在complete 一直调用登录
    complete: () => {
          _self.mpWxLogin();
        }

**Comment by StrivingRabbit** [comment]
在小程序端，调用的就是特定小程序的api。
