### ISSUE TITLE
uni.getLocation 经度纬度出现偏差

### ISSUE THREAD

**Issue by Yx8080** [dcloudio/uni-app#5044]
uni.getLocation({
      type: 'gcj02',
      altitude: true,
      geocode: true,
      highAccuracyExpireTime: 8000,
      success: (getLocationRes) => {
        console.info('[uni.getLocation.async] success', getLocationRes);
        if (!analyseAddress) {
          resolve({
            longitude: getLocationRes.longitude,
            latitude: getLocationRes.latitude,
            address: getLocationRes.address,
          });
        } else {
          getAnalyzingAddress({
            longitude: getLocationRes.longitude,
            latitude: getLocationRes.latitude,
          }).then(data => {
            resolve(data);
          });
        }
      },
      fail: () => {
        console.info('[uni.getLocation.async] fail');
        resolve({
          longitude: null,
          latitude: null,
          address: null,
        });
      },
      complete: (res) => {
        console.info('[uni.getLocation.async] complete', res);
      },
    });
    
    解析的经度纬度出现偏差超过3公里，速度修复

**Comment by Yx8080** [comment]
差点被客户骂死

**Comment by bfc846958672** [comment]
你好，是否设置 isHighAccuracy （高精度）字段

**Comment by bfc846958672** [comment]
长时间未响应，关闭本issue。 如还有问题，可 reopen issue 继续讨论。
