### ISSUE TITLE
uni-app uni-forms组件bug

### ISSUE THREAD

**Issue by youtao** [dcloudio/uni-app#5047]
**Android端**

**uni-forms.vue**这个组件下面代码有bug
`let getbinddata = getApp().$vm.$.appContext.config.globalProperties.binddata;`

应改为：
```
const apps = getApp();
const app = apps.length ? apps[apps.length - 1] : apps;
```
![image](https://github.com/user-attachments/assets/5f10cb7c-9c16-436b-8ec0-84e533a6ef2b)
![image](https://github.com/user-attachments/assets/858345c8-4100-42c2-89d1-11b4d9057279)
![image](https://github.com/user-attachments/assets/e666217c-6810-410c-9056-fee5eeaa6174)

**Comment by bfc846958672** [comment]
提供一下可复习的demo 工程

**Comment by bfc846958672** [comment]
长时间未响应，关闭本issue。 如还有问题，可 reopen issue 继续讨论。
