### ISSUE TITLE
ios调用uni.getLocation偶现getLocation:fail Error Domain=PGLocation Code=2

### ISSUE THREAD

**Issue by Chenmin926** [dcloudio/uni-app#5053]
如下调用，有时候会抛出如下错误
{"errMsg":"getLocation:fail Error Domain=PGLocation Code=2 \"不能获取到位置\" UserInfo={NSLocalizedDescription=不能获取到位置},https://ask.dcloud.net.cn/article/282","errCode":-1502,"code":-1502}

export function getLocation() {
	return new Promise((resolve, reject) => {
		uni.getLocation({
      type: 'gcj02',
      success: res => {
        console.log("🚀 ~ returnnewPromise ~ res:", res)
        resolve(res)
      },
      fail: async err => {
				console.log(err)
				        insertLog('publicMethods', 'getLocation', '定位失败', err)
        reject(err)
        // #ifdef APP
        await checkLocation()
        // #endif
      }
    })
	})
}

**Comment by bfc846958672** [comment]
位置服务不可用，如系统定位服务关闭, 文档详情[](https://www.html5plus.org/doc/zh_cn/geolocation.html#plus.geolocation.GeolocationError)
![image](https://github.com/user-attachments/assets/17b83172-1313-4573-abe3-ff885e9a7368)

**Comment by bfc846958672** [comment]
参考这个[ask 187279](https://ask.dcloud.net.cn/question/187279)，是否正确设置 高德的bundleid

**Comment by Chenmin926** [comment]
@bfc846958672 
![image](https://github.com/user-attachments/assets/d14cb478-6e7f-464b-bca1-b0d42116a756)
发现我们这个应用没有开启Geolocation，只是在下面的Maps配置了，但是为什么定位还是可以用

**Comment by bfc846958672** [comment]
uni.getLocation 默认会获取系统定位

**Comment by Chenmin926** [comment]
@bfc846958672 如果启用了高德或者其他厂商的定位，他们失败以后还会切换到系统定位吗？
