### ISSUE TITLE
uni.showLoading 能否开放接口，让开发者传入自定义的组件进去做显示

### ISSUE THREAD

**Issue by applebest** [dcloudio/uni-app#5054]

**Comment by bfc846958672** [comment]
你好，目前不支持，uni.showLoading在app端和小程序端都是采用原生loading。 可以开发一个自定义loading组件，动态控制显示隐藏

**Comment by applebest** [comment]
> 你好，目前不支持，uni.showLoading在app端和小程序端都是采用原生loading。 可以开发一个自定义loading组件，动态控制显示隐藏

组件的方式需要在模板层 嵌入，再ref控制显示隐藏，多个地方公用的话，模板层代码比较多。  有什么方案能够在任意函数能通过类似uni.showLoadingn的方式显示 ，消失吗？

**Comment by bfc846958672** [comment]
可以参考elementUI的 [messagebox组件](https://element.eleme.cn/#/zh-CN/component/message-box)源码实现。 大概思路就是当前页面动态生成 loading内容，然后插入的当前页面中。
