### ISSUE TITLE
video标签,安卓支付宝小程序direction="0"时还是横屏播放

### ISSUE THREAD

**Issue by jinx0321** [dcloudio/uni-app#5055]
安卓12(红米k40)
支付宝安卓版本10.6.18

video标签里已经指定了direction="0",但是安卓的支付宝小程序还是横屏播放,ios支付宝小程序是好的

**Comment by jinx0321** [comment]
vue版本是2

**Comment by bfc846958672** [comment]
经测试，这是原生支付宝小程序的bug。可以在支付宝小程序社区，反馈该bug
