### ISSUE TITLE
通过CLI创建的项目，更新到最新版本后，编译到小程序，保存页面时会有报错

### ISSUE THREAD

**Issue by SAO-Asuna** [dcloudio/uni-app#5063]
![Uploading image.png…]()
11:46:57.082 开始差量编译...
11:46:57.426 [plugin:commonjs] Transform failed with 1 error:
11:46:57.434 /Users/kirito/uniapp/project/test-new/src/App.vue?vue&type=script&setup=true&lang.ts:1:8: ERROR: Expected ">" but found "setup"
11:46:57.444 at App.vue:1:8
11:46:57.463   Expected ">" but found "setup"
11:46:57.470   1  |  <script setup lang="ts">
11:46:57.478      |          ^
11:46:57.490   2  |  import { onLaunch, onShow, onHide } from "@dcloudio/uni-app";
11:46:57.497   3  |  onLaunch(() => {

**Comment by SAO-Asuna** [comment]
[Uploading test-new.zip…]()
复现工程

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/5061

**Comment by SAO-Asuna** [comment]
感谢，了解了
