### ISSUE TITLE
Android 14，Google手机，chooseImage 从相册选择图片问题，count失效

### ISSUE THREAD

**Issue by webQin** [dcloudio/uni-app#5068]
// 动态权限，在使用时再获取
permision.requestPermissions('android.permission.READ_MEDIA_IMAGES').then(res => {}）
// 选择图片
uni.chooseImage({
          count: 1, // 默认9
          sourceType: ['album'], // 从相册或者相机选择
          success: (res) => { }
}）

触发条件：
1、Android 14，Google手机

**Comment by webQin** [comment]
plus.android.requestPermissions 【android.permission.READ_MEDIA_IMAGES】，在Google手机，安卓14版本，部分访问有效和不允许访问，返回的都在deniedAlways

**Comment by Otto-J** [comment]
这个不能快速定位，你去掉权限申请的代码，然后再试一下有没有问题。还有问题的话提供一个测试示例吧。提供更多信息，有助于定位和解答你的问题。
