### ISSUE TITLE
uni.getLocation 国际化描述没有切换语言

### ISSUE THREAD

**Issue by wwzill0928** [dcloudio/uni-app#5069]
![image](https://github.com/user-attachments/assets/13d12ab9-2a27-497f-8870-1940872a0607)
![image](https://github.com/user-attachments/assets/0a13c4f3-5501-412b-99bb-9da7c9f35bb3)
标题 和 按钮换语言了。但是描述还是中文

![image](https://github.com/user-attachments/assets/d20d3769-e881-4eab-b03d-66968a00d432)
![image](https://github.com/user-attachments/assets/67c3ebd1-b87d-4356-a1ec-c63376a42990)
我看其他app是会跟着变的，哪个描述。

然后默认语言也是西班牙语
![image](https://github.com/user-attachments/assets/406b2d44-c406-40b7-87e3-9ba6b3d61d04)
input type=file 也是还是中文
![image](https://github.com/user-attachments/assets/89ed9a88-081d-4bc0-a118-939ef7d4fb70)

**Comment by wwzill0928** [comment]
有没有人帮忙解决一下啊啊啊啊啊啊 ～～～～～

**Comment by wwzill0928** [comment]
运行/运行到手机或模拟器/运行到app IOS基座 这样配置10S隐私信息访问的许可描述是不生效的。最后我发行/原生app 云打包就可以啦。

**Comment by bfc846958672** [comment]
10S隐私信息访问的许可描述在真机调试的情况下，需要打自定义基座才能生效
