### ISSUE TITLE
app上对象【动态属性值】出不来，在h5上是可以的。app上要怎么弄？

### ISSUE THREAD

**Issue by vlijiantao** [dcloudio/uni-app#507]
简要代码：
![image](https://user-images.githubusercontent.com/37172114/60383052-ab3e2e00-9a9e-11e9-88d9-07c86bad4f94.png)

method:
getVal(label,groupName){
				return this.detail[label]
			}

**预期结果**
温度
![image](https://user-images.githubusercontent.com/37172114/60383033-60241b00-9a9e-11e9-81eb-d5f6a3c06a1b.png)

测试数据：
this.detail={"dataId":10,"messageId":1127952332114364400,"productId":4,"deviceId":6,"reportTime":"2019-05-13 16:31:10","tempControlTarget":48,"tempBack":44,"tempHeating":60,"tempSalt":75,"pumpStat":true,"valveStat":false,"heatingStat":true,"heatingPwm":0.37,"runStat":"running","runMode":"auto","errorCode":null}

this.itemArray=[{"groupName":"温度","items":[{"label":"控制目标温度","value":"tempControlTarget","checked":true},{"label":"回水温度","value":"tempBack","checked":true},{"label":"锅炉出水温度","value":"tempHeating","checked":true},{"label":"储热盐温度","value":"tempSalt","checked":true}]},{"groupName":"状态","items":[{"label":"加热棒状态","value":"heatingStat","checked":true},{"label":"短路阀门状态","value":"valveStat","checked":true},{"label":"循环水泵状态","value":"pumpStat","checked":true}]},{"groupName":"功率","items":[{"label":"加热功率比","value":"heatingPwm","checked":true}]}]

**实际结果**
h5上运行可以正常显示，app显示不出来属性值。

**Comment by vlijiantao** [comment]
在appshang ,v-for里直接取值是可以的，例如：{{item.label}}，但是{{function(param1,param2)}}这样的是不行的，是不支持吗？

**Comment by zhetengbiji** [comment]
是否是自定义组件编译模式？

**Comment by zhetengbiji** [comment]
此问题长期无回应，暂时关闭
