### ISSUE TITLE
无法使用缓存图片这类静态资源，每次都是返回200

### ISSUE THREAD

**Issue by adgad2** [dcloudio/uni-app#5071]
rt，oss上对图片已经设置了Cache-Control: max-age=86400，但是每次还是会请求oss服务器，不会返回304

GET /static/touxiang/xxxxx.jpg HTTP/1.1
Host: XXXXXXXXX
Connection: keep-alive
User-Agent: Mozilla/5.0 (Linux; Android 10; MIX 2S Build/QKQ1.190828.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/80.0.3987.99 Mobile Safari/537.36 uni-app Html5Plus/1.0 (Immersed/27.636364)
Sec-Fetch-Dest: image
Accept: image/webp,image/apng,image/*,*/*;q=0.8
X-Requested-With: com.gpkj.obachaowan
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: no-cors
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7

我安卓手机使用浏览器抓包看到每次请求图片都是这个请求头，然后每次返回的都是200，实际请求了服务器，ios好像没有这个问题，第二次，使用抓包工具没有看到第二次请求

**Comment by Otto-J** [comment]
一个网络资源强缓存是否生效，主要看 header 是否包含了过期信息。确保后续请求中包含 If-None-Match 和 If-Modified-Since

看你header 不包含这个。建议你进一步排查发起请求的相关配置，如果是 uniapp 项目请提供复现工程。

**Comment by bfc846958672** [comment]
长时间未响应，关闭本issue。 如还有问题，可 reopen issue 继续讨论。
