### ISSUE TITLE
安卓原生跳转到指定页面，然后会首先回到uniapp 的首页

### ISSUE THREAD

**Issue by wl386123298** [dcloudio/uni-app#5074]
前提：安卓离线打包 wgt 放在原生中使用
首先uniapp 的首页是 A，其中有 B，C，D 页面
原生通过 uniapp 的 sdk 跳转到 B，然后B依次跳转到 C，D页面，现在按返回键，返回到 B 页面后，再返回则会回到首页 A 页面

请问这是否是正常表现，如果是正常表现，请问有什么途径能关闭，毕竟从用户的角度来说，我从哪里跳转，我返回就应该回到上一个页面

**Comment by bfc846958672** [comment]
生通过 uniapp 的 sdk 跳转到 B，然后B依次跳转到 C，D页面，现在按返回键，返回到 B 页面，
-----------
是指按了2次返回键返回到了 B页面么，

**Comment by bfc846958672** [comment]
返回到 B 页面后，再返回则会回到首页 A 页面

--------------
看你的描述是，你从D页面 返回到了 C页面，然后C页面返回到B页面， 再按返回键 返回到A页面。  这个返回逻辑是正常的。

**Comment by wl386123298** [comment]
> 返回到 B 页面后，再返回则会回到首页 A 页面
> 
> 看你的描述是，你从D页面 返回到了 C页面，然后C页面返回到B页面， 再按返回键 返回到A页面。 这个返回逻辑是正常的。

那么有什么办法或者 Api不返回到 A 页面

**Comment by bfc846958672** [comment]
方案一：可以配置 onBackPress 监听返回事件，然后返回中用getCurrentPages 判断是不是要返回到A页面，是A页面就阻止返回
方案二： 将B页面设置为首页，A页面成B页面的一个组件
