### ISSUE TITLE
vm.$children 在支付宝小程序中永远为空数组，导致uview2.x 大量组件实际不可用

### ISSUE THREAD

**Issue by Tommy0121** [dcloudio/uni-app#5077]
![image](https://github.com/user-attachments/assets/5f83f1af-0a71-446d-ae50-4a49e0ab728f)
![image](https://github.com/user-attachments/assets/c2932da9-3806-4cd8-9974-3e1053aed8e8)
![image](https://github.com/user-attachments/assets/91aed7da-eac8-4e10-8fe1-baadbf59e5a7)

**Comment by Tommy0121** [comment]
[demo.zip](https://github.com/user-attachments/files/16536579/demo.zip)
demo文件解压后yarn install && yarn alipay:dev

**Comment by Tommy0121** [comment]
打个label然后不管了是吧

**Comment by bfc846958672** [comment]
你好 我这边用提供的工程发现是有对应的children的，方便提供一些更详细的操作流程么
![image](https://github.com/user-attachments/assets/a54f7369-e0fe-4efe-8a39-c52d43e83356)

**Comment by Tommy0121** [comment]
已找到问题，忘了回复，抱歉
问题在于支付宝小程序未开启component2
按照uview的文档在 manifest.json 中添加 
```
"mp-alipay" : {
	"component2": true
},
```
并没有真的打开支付宝小程序的component2

需要手动在支付宝小程序开发工具打开component2
![image](https://github.com/user-attachments/assets/78590c2e-1903-4ec6-b7f8-c944b760465e)
