### ISSUE TITLE
Uniapp 通过plus.android的方式去更改原生底部导航栏(navigatorbar)的颜色，改完会影响 uniapp 相关页面跳转

### ISSUE THREAD

**Issue by wl386123298** [dcloudio/uni-app#5079]
假设 Uniapp 有 A ， B，C，D 相关页面，现在 A->B, B页面通过下列方法修改颜色，然后 B 返回到 A，A 在分别打开 C,D 等页面，
最终表现是页面有跳转，但是相关页面没有显示，相关页面的接口请求是调用的，说明页面是跳转过去的，但是界面还是在 A 页面

通过下面方法更改原生activity 的底部导航栏颜色
```
export function setAndroidNavigatorBarColor(navigationBarColor:string){
  const platform = uni.getSystemInfoSync().platform
  if (platform === 'android') {
    //底部导航栏(虚拟按键)背景颜色
    var Color = plus.android.importClass("android.graphics.Color");
    plus.android.importClass("android.view.Window");
    var mainActivity = plus.android.runtimeMainActivity();
    var window_android = mainActivity.getWindow();
    window_android.setNavigationBarColor(Color.parseColor(navigationBarColor));
  }
}
```

**Comment by bfc846958672** [comment]
提供一下可复现的工程demo

**Comment by bfc846958672** [comment]
我这边复现出该问题， 且长时间未响应，关闭本issue。 如还有问题，可 reopen issue 继续讨论。

**Comment by gitlilimin** [comment]
@bfc846958672 我也遇到同样的问题了，这不需要demo，用你们官方示例就能复现。只要某个页面调用了上面的代码，页面返回以后，就会随机有一些页面无法跳转

**Comment by gitlilimin** [comment]
@wl386123298 我测试了一些情况，感觉是Android内部问题，我的设备是
小米 17 Pro
HyperOS 3.0.45.0
Android 16

```js
const color = -1 // 排除Color类的影响，这里直接使用Color类转出的颜色，-1是白色，-65536是红色
plus.android.importClass('android.view.Window')
var mainActivity = plus.android.runtimeMainActivity()
var window_android = mainActivity.getWindow()
window_android.setNavigationBarColor(color)
```

发现问题关键是，它似乎只支持很少一部分颜色，我目前发现支持的颜色有：
- -1 纯白 完全支持
- 0 深黑（感觉不是纯黑，带80%透明度） 完全支持

其他颜色似乎不支持，一旦设置过这种颜色，哪怕后面再次设置回之前的颜色，也会出现跳转问题。而且跟题主说的情况一致，跳转的页面实际代码是执行了的。看到的动效类似于 从A跳转B，跳转动画没播放完就被返回A了，再次点击跳转B，会白屏。控制台无报错。以下颜色是我试过会出问题的
- -65536 纯红色
- -16776961 纯蓝色
