### ISSUE TITLE
闺蜜圈 APP /小程序 /h5

### ISSUE THREAD

**Issue by obaby** [dcloudio/uni-app#5080]
一款跟好用的大姨妈记录 app
https://guimiquan.cn

![1831702430568_ pic](https://github.com/user-attachments/assets/b698a745-43eb-4c45-aac1-9f4d49080698)
![1841702430573_ pic](https://github.com/user-attachments/assets/02b84d04-0d56-4280-b62a-5da211a0588f)
![1851702430576_ pic](https://github.com/user-attachments/assets/2c49a919-0de8-478c-b8cb-93af769aeb6f)

![dayima_qrcode](https://github.com/user-attachments/assets/607a0e25-be75-480d-8ad0-0d676c46a044)

**Comment by bfc846958672** [comment]
已收录
