### ISSUE TITLE
IOS 原生插件

### ISSUE THREAD

**Issue by coderBye** [dcloudio/uni-app#5090]
将uniapp项目放入`Pandora/apps/ `目录下, 并修改control.xml 到id后，运行项目xcode出现下面报错
Framework 'AlipaySDK' not found
![image](https://github.com/user-attachments/assets/df30d9c8-f0d0-4e3f-b7a8-81f82610931d)

<img width="931" alt="image" src="https://github.com/user-attachments/assets/c5693a00-76c1-45d6-843b-7f5ce2ba47b9">

macos version：14.0
xcode version: 15.0.1
手机模拟器版本: 17.0.1

**Comment by bfc846958672** [comment]
相关[ask 196668](https://ask.dcloud.net.cn/question/196668) 帖子，已有解决方案
