### ISSUE TITLE
境外uni-app

### ISSUE THREAD

**Issue by WinstonAlfred** [dcloudio/uni-app#5092]
我是外国人想做个智慧餐饮小程序。如果不能用unicloud你们推荐用什么云开发？然后能可以用微信或者支付宝支付吗？

**Comment by bfc846958672** [comment]
云厂商可以自行调研， 海外支付不推荐用微信和支付宝，可以推荐选择海外支付厂商 [海外支付厂商](https://uniapp.dcloud.net.cn/tutorial/app-payment-google.html)。

**Comment by bfc846958672** [comment]
推荐用 aws 云开发， 国外支付可以用微信或者支付宝，但是考虑国外用户群体，更推荐 选海外的支付厂商

**Comment by dbstd2333** [comment]
maybe cloud-dev is not best solution，use js framework（like express，fastfy）to code backend by your self maybe is better

**Comment by hbcui1984** [comment]
@WinstonAlfred  你现在的卡点是实名认证和手机号验证吧？你可以发邮件到service@dcloud.io，单独说明你的情况，和官方协商单独的报备方案。至于海外用户，uniCloud是可以使用的，只是在海外节点上，访问速度可能有些延迟。

如果你的前端是uni-app，最好用的云开发就是uniCloud。
