### ISSUE TITLE
vue3+uniapp项目中pages.json配置国际化切换不生效，只显示一种语言，页面其他地方正常切

### ISSUE THREAD

**Issue by QuanJ04** [dcloudio/uni-app#5094]
请问uniapp h5项目中pages.json配置了国际化tabbar但是切换语言不生效怎么解决，只能显示一种语言，除了pages.json不会实时切换，页面上其他地方都能实时切换，希望得到回复，谢谢

**Comment by bfc846958672** [comment]
发一下可复现demo工程

**Comment by punghunger** [comment]
我遇到相似问题，开发环境下能切换，打包正式环境后台就无法切换，显示%tabBar.all%
项目附件
[tts.zip](https://github.com/user-attachments/files/16686928/tts.zip)

**Comment by bfc846958672** [comment]
> 我遇到相似问题，开发环境下能切换，打包正式环境后台就无法切换，显示%tabBar.all% 项目附件 [tts.zip](https://github.com/user-attachments/files/16686928/tts.zip)

我用android 8.0 测试代码 tabBar里面会根据语言正常变化
