### ISSUE TITLE
热更新无法监听 node_modules 文件的变化

### ISSUE THREAD

**Issue by 13421468608** [dcloudio/uni-app#5096]
使用 cli 创建的项目，使用 Monorepo  的工程结构，但是我发现 uniapp的热更新无法监听 node_modules 文件的变化，我看了 vite 的说明， 在 server中配置了 ignored，但是依旧无效，参考：https://github.com/vitejs/vite/issues/8619
请问有什么方法可以让 热更新监听到 node_modules 中的文件的变化？

**Comment by Otto-J** [comment]
cli 本身是基于 vite 的项目，所以可以直接参考 vite 官方的答复。关联 https://github.com/dcloudio/uni-app/issues/3811#issuecomment-1911999608

**Comment by 13421468608** [comment]
https://github.com/dcloudio/uni-app/issues/3811#issuecomment-1911999608 让我参考的就是https://github.com/vitejs/vite/issues/8619 ，试过了并没有用。
并且我现在遇到了 workspace:* 注入的依赖被重复打包到 vendor.js 的问题。我查了社区，发现也有人遇到类似的问题。https://ask.dcloud.net.cn/question/157763，通过 vite 怎么都修改不了这个问题。请问有解决方案吗

**Comment by 13421468608** [comment]
热更新问题已在 https://github.com/dcloudio/uni-app/issues/3991 中找到答案，感谢

**Comment by Caffeine19** [comment]
> 热更新问题已在 [#3991](https://github.com/dcloudio/uni-app/issues/3991) 中找到答案，感谢

请问你们使用的也是pnpm作为monorepo的管理工具吗，我尝试了这个issue里提到的方法，并不能触发热更新
