### ISSUE TITLE
uni.webview.js在京东小程序调用路由方法报错

### ISSUE THREAD

**Issue by shiminJ** [dcloudio/uni-app#5099]
问题：h5页面在京东小程序的webview中无法调用uni.webView.navigateTo跳转到原生小程序页面
根源：
京东小程序的判断有误
<img width="1180" alt="image" src="https://github.com/user-attachments/assets/1316d2ff-43ba-4044-b427-6bd62e668965">

**Comment by bfc846958672** [comment]
https://github.com/dcloudio/uni-app/pull/5127 fix
