### ISSUE TITLE
2个疑似Bug：微信小程序，this.selectComponent调用子组件，修改data并不能响应到VIEW层

### ISSUE THREAD

**Issue by microkof** [dcloudio/uni-app#510]
*第1个疑似Bug：*

我开发微信小程序，采用uni-app推荐的vue组件写法写了一个组件。

当我写 `this.selectComponent('#xxid').data` 确实可以打印出组件内的data，但是，`this.selectComponent('#xxid').fangfa()`会报错，说`fangfa`不是一个function。

但是用`this.selectComponent('#xxid').data.fangfa()`就可以成功执行。

所以疑问是：为什么在uni-app中，直接`.fangfa()`不行，必须`.data.fangfa()`？这个跟微信小程序官方写法不统一，uni-app手册里没见到相关说明。

*第2个疑似Bug：*

好吧，我于是用了`.data.fangfa()`，调用了组件内的方法，但是`fangfa`修改了组件的data之后，并不能响应到view层。

复现方法：

子组件代码大致是：

```
<template>
  <view :style="abc">汉字</view>
</template>

<script>
export default {
  data() {
    return {
      abc: ''
    }
  },
  methods: {
    fangfa() {
      this.abc= 'color: red'
      console.log(this)
    }
  }
}
</script>

```

父组件代码大致是，随便找个元素绑click事件：

```
<ripple-effect id="ripple-effect"></ripple-effect>
...
...
...
this.selectComponent('#ripple-effect').data.fangfa()
```

当click，控制台会打印出this的内容，会发现`abc`确实变了，但是，`<view :style="abc">汉字</view>`里面的style是空串，说明并没有响应到view。

跪求！求官方大大帮忙看一下。

**Comment by fxy060608** [comment]
selectComponent 获取到的是小程序的组件对象，并非 Vue 的 vm 对象
如果要访问子组件，可以通过 Vue 的 ref 方式访问
尽可能使用 Vue 提供的组件间通讯机制

**Comment by microkof** [comment]
> selectComponent 获取到的是小程序的组件对象，并非 Vue 的 vm 对象
> 如果要访问子组件，可以通过 Vue 的 ref 方式访问
> 尽可能使用 Vue 提供的组件间通讯机制

thanks a lot！
