### ISSUE TITLE
el-form-item 的name在子组件内部未曾接收到，是否有长度限制？

### ISSUE THREAD

**Issue by gamerssong** [dcloudio/uni-app#5100]
![1724231551034](https://github.com/user-attachments/assets/b4bedc31-bc54-43f6-8677-75227a1ff9a1)
![1724231590425](https://github.com/user-attachments/assets/93e36aee-2e75-4604-bd0d-6598940f8a7d)
同样的参数在子组件内接收的值不一样，导致校验失败无效，传值是有限制吗？

**Comment by bfc846958672** [comment]
你好，提供一下复现的demo工程
