### ISSUE TITLE
app端 defineProps里的内容不能正确渲染到template

### ISSUE THREAD

**Issue by LeoKun1231** [dcloudio/uni-app#5105]
如题，我从一个index界面跳转到test界面，通过defineProps接收，setup里面打印正常，但是template不渲染。只有在app端才会这样，h5、微信小程序一切正常。版本：3.0.0-4020420240722002

这是仓库：https://github.com/LeoKun1231/test-defineProps

![88319c51be013be190cd192129f241c](https://github.com/user-attachments/assets/b7d25e57-c101-425f-86f3-dea38fb5ca03)
![dfb3f169890057292146820c059d9bf](https://github.com/user-attachments/assets/9b2e7657-afeb-4448-bc2e-3dee80454f7a)

**Comment by qhl123456** [comment]
+1，希望解决下，小程序可以用，app端不行，小程序转app的话就很麻烦，所有这种地方都要做修改

**Comment by bfc846958672** [comment]
你好，这个bug已经修复了，[props 默认值修复](https://github.com/dcloudio/uni-app/commit/94253d8fa602fae630e43dac615c14c97c8ae04a) 下次发版修复。可以临时对props的属性进行computed包装使用
```
//template
<view>{{props_str}}</view>
// script
let props_str= computed(() => props.str)
```
