### ISSUE TITLE
iOS17.1 input type="digit"，输入带有小数点的值无法删除

### ISSUE THREAD

**Issue by zhoushuozh** [dcloudio/uni-app#5106]
CLI版本号： 2.0.2-4020420240722003
打包方式：云打包
vue版本：vue2

input type="digit"，输入带有小数点的值，删除到小数点后一位时，就无法继续删除。
目前在iOS 17.1和iOS 17.1.1上的app端有复现，使用iOS 17.1的Safari打开官方H5示例也可以复现。https://hellouniapp.dcloud.net.cn/pages/component/input/input

![](https://ice.frostsky.com/2024/08/23/af23b40ecc5f9e123378d37740ed66d2.gif)

**Comment by StrivingRabbit** [comment]
https://ask.dcloud.net.cn/question/197122?item_id=281294&rf=false
