### ISSUE TITLE
什么时候能支持钉钉小程序

### ISSUE THREAD

**Issue by guoglee** [dcloudio/uni-app#511]
**新功能描述**
简洁描述你希望补充完善的增强功能
什么时候能支持钉钉小程序
**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by zhangzhenfei** [comment]
+1

**Comment by MasterBetter** [comment]
+1

**Comment by hbcui1984** [comment]
同 #492
