### ISSUE TITLE
uniapp 开发微信小程序支持 cdn 引入js文件吗

### ISSUE THREAD

**Issue by rookie-luochao** [dcloudio/uni-app#5114]

**Comment by bfc846958672** [comment]
微信小程序本身不支持 cdn 引入js文件，所以uniapp也没法支持。

**Comment by rookie-luochao** [comment]
> 微信小程序本身不支持 cdn 引入js文件，所以uniapp也没法支持。

好的谢谢😁，所以优化整体打包大小只能通过分包策略吗？

**Comment by bfc846958672** [comment]
是的

**Comment by bfc846958672** [comment]
可以尝试将相关业务逻辑写成微信小程序插件，然后代码中引入插件。这样也可以简化微信小程序整体大小
