### ISSUE TITLE
关于createPushMessage的图标的一个问题或者说是一个建议新增的功能吧

### ISSUE THREAD

**Issue by xueyin220807** [dcloudio/uni-app#5115]
官方文档uni.createPushMessage(OBJECT)中有参数icon
关于通知栏，我发现：
一个规律，通知栏图标分为“3”个图标，

1：以当前应用名左边的一个图标，这个在通知栏位置最靠上。（小图）
2：当前应用有多个通知时，每个通知最左侧的图标（小图）
2：当前应用只有一个通知时，当前应用通知栏最右侧的图标（大图）
其中“2”和“3”都是我们自定义的这个icon，只是尺寸不同，但是“1”则没有配置参数

**Comment by xueyin220807** [comment]
建议能新增这个顶部的“1”这种情况的小图标的配置

**Comment by xueyin220807** [comment]
补充下是安卓13，其它暂时还没有测试过

**Comment by bfc846958672** [comment]
2，3 的通知栏可以理解，1 没理解，提供一个截图看下

**Comment by bfc846958672** [comment]
长时间未响应，关闭本issue。 如还有问题，可 reopen issue 继续讨论。

**Comment by chergn** [comment]
怎么让项目支持unocss+iconify图标啊
