### ISSUE TITLE
WebStorm中条件编译报错如何解决？不知是eslint还是ide本身问题，代码附上

### ISSUE THREAD

**Issue by chow5566** [dcloudio/uni-app#5117]
![image](https://github.com/user-attachments/assets/29c5273e-996b-4214-97be-f4bbc249199c)

`// #ifndef MP-WEIXIN
import * as echarts from 'echarts';
// #endif
// #ifdef MP-WEIXIN
const echarts = require('./static/echarts.min.js');
// #endif`
我知道可以通过这样解决
`let echarts;
// #ifndef MP-WEIXIN
import * as echartsModule from 'echarts';
echarts = echartsModule;
// #endif
// #ifdef MP-WEIXIN
echarts = require('./static/echarts.min.js');
// #endif`
但终归不是个正常写法，而且一堆第三方组件也爆红

**Comment by bfc846958672** [comment]
这是eslint 不识别条件编译导致的， 解决方法之一是写一个eslint自定义的规则。 图里的问题就是eslint 检测到重复命名导致的，这种情况可以对这一行代码或者这个文件 做禁用单个规则 no-redeclare 来快速解决

**Comment by chow5566** [comment]
> 这是eslint 不识别条件编译导致的， 解决方法之一是写一个eslint自定义的规则。 图里的问题就是eslint 检测到重复命名导致的，这种情况可以对这一行代码或者这个文件 做禁用单个规则 no-redeclare 来快速解决

有没有办法识别出条件编译，只对条件编译不抛出错误？

**Comment by bfc846958672** [comment]
> > 这是eslint 不识别条件编译导致的， 解决方法之一是写一个eslint自定义的规则。 图里的问题就是eslint 检测到重复命名导致的，这种情况可以对这一行代码或者这个文件 做禁用单个规则 no-redeclare 来快速解决
> 
> 有没有办法识别出条件编译，只对条件编译不抛出错误？

已现有的eslint 的规则不能实现。
