### ISSUE TITLE
Vue.$set 在 使用upx的模板中有问题

### ISSUE THREAD

**Issue by JE-lee** [dcloudio/uni-app#512]
**问题描述**
在模板中使用
```html
<view :style="'left' + site.styleLeft + 'upx'"></view>
```
设置
```javascript
this.$set(this.site, 'styleLeft', 130)
```
之后在**微信小程序中**无法生效

**将模板的upx 改为px之后又正常**
```html
<view :style="'left' + site.styleLeft + 'px'"></view>
```

**系统信息:**
 - 发行平台: [微信小程序]
 - 操作系统 [win 10]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [微信开发者工具]

**Comment by fxy060608** [comment]
目前小程序平台暂不支持在动态 style 中使用 upx，你可以选择使用 rpx 或 px
