### ISSUE TITLE
uni.createInnerAudioContext无法在onCanplay下获得无法正确的duration

### ISSUE THREAD

**Issue by lp20010415** [dcloudio/uni-app#5125]
npm run dev:mp-weixin，在微信开发者工具中进行真机模拟时，获取的duration为0。而不是真机模拟的情况下可以秒获取。

在onLoad()中创建的
```
// 播放音频
this._audio = uni.createInnerAudioContext();

this._audio.onCanplay((res) => {
	console.log("音频进入可播放状态");
	console.log(this._audio.duration);

})
this._audio.onPlay((res) => {
	console.log("音频进入播放状态")
	console.log(this._audio.duration);
})
```

非真机模拟下:
![image](https://github.com/user-attachments/assets/92a38ce0-870c-4fc3-8ee2-fe392dedbe93)

真机模拟下:
![image](https://github.com/user-attachments/assets/312b821f-7dc6-4f04-b02b-0de1c2670d6f)

寻找解决的很方法很久了。。。。找了一天了。ε=(´ο｀*)))唉，这是微信的问题，还是？？？
感谢你的回复，感谢！感恩！

**Comment by bfc846958672** [comment]
你好，这是微信的bug， [帖子详情](https://developers.weixin.qq.com/community/develop/article/doc/0004cc8fe181982bf1d1f8b0b61813)，可以根据帖子，轮训获取duration， 或者在服务器端提前把音频时长算出来，返回给前端

**Comment by lp20010415** [comment]
> 你好，这是微信的bug， [帖子详情](https://developers.weixin.qq.com/community/develop/article/doc/0004cc8fe181982bf1d1f8b0b61813)，可以根据帖子，轮训获取duration， 或者在服务器端提前把音频时长算出来，返回给前端

ε=(´ο｀*)))唉，轮训就没意思了，不过uni.getBackgroundAudioManager很好用，它在真机模拟也可在onPlay中可获取。
