### ISSUE TITLE
uniapp分包到底怎么弄？是操作失误还是没生效

### ISSUE THREAD

**Issue by mimimiaomiao1** [dcloudio/uni-app#5129]
![cd200d82ddad7ccfe984bf4e66f28234](https://github.com/user-attachments/assets/9b9069a3-7e46-4a90-b83f-3ab7528764cb)
![22950cd200aead0e1813d909fa3687ba](https://github.com/user-attachments/assets/a637f953-2410-4327-98b3-6d5017407431)
![debaad2e22344aef2b7a917c693a4122](https://github.com/user-attachments/assets/8ee3337f-ed41-4f87-8fae-890360c7dd87)

我这有个问题，实在搞不懂了。。这个deviceInfo是分包，subPackages也是这么写的，照着网上写的，然后微信开发工具里我用依赖分析发现，他俩被打包在了主包内的vendor.js中。。  分包内并没有vendor.js这个文件。

"optimization" : {
            "subPackages" : true
        },这个我也写了。。

**Comment by bfc846958672** [comment]
这只是引用关系了，具体分包状况看矩形树图。
