### ISSUE TITLE
关闭webwebview 

### ISSUE THREAD

**Issue by wzenker** [dcloudio/uni-app#5138]

**Comment by wzenker** [comment]
this.$scope.$getAppWebview().children()[0].close(); 在ios16中不起作用呢

**Comment by wzenker** [comment]
h5中关闭webview有什么最佳解决方案

**Comment by bfc846958672** [comment]
h5不支持getAppWebview api，  不理解你的需求，详细描述一下

**Comment by wzenker** [comment]
具体的场景是这样的：uniapp用webview加载了一个h5页面，h5页面需要在一定的场景下关闭webview，我的实现时h5通过postmessage发送一个指令，uniapp接收到这个指令后，执行this.$scope.$getAppWebview().children()[0].close()，此时发现个别机型并不能执行成功

**Comment by bfc846958672** [comment]
uniapp接收到这个postmessage指令后， 用v-if 控制webview 试试呢

**Comment by wzenker** [comment]
这个我试试，关闭了之后在执行 uni.navigateBack();是吧

**Comment by bfc846958672** [comment]
> 这个我试试，关闭了之后在执行 uni.navigateBack();是吧

不了解你的业务。 

如果需要关闭webview之后，返回上一级页面，是需要调用uni.navigateBack() 这个的
