### ISSUE TITLE
包含web-view的组件，要点两次返回才能回到父组件

### ISSUE THREAD

**Issue by yinyongxian** [dcloudio/uni-app#514]
**问题描述**
包含web-view的组件，要点两次返回才能回到父组件

**复现步骤**
父组件
url 如 https://www.baidu.com
`uni.navigateTo({
	url: `/pages/webPage/webPage?pageUrl=${url}}`
});`
子组件
`<template>
	<view>
		<web-view :src="pageUrl"></web-view>
	</view>
</template>`

**预期结果**
点一次返回才能回到父组件

**实际结果**
点二次返回才能回到父组件

[](url)
**系统信息:**
 - 发行平台:微信小程序、H5平台
 - 操作系统 Android 7.0
 - HBuilderX版本 2.0.1

**Comment by zhetengbiji** [comment]
如果webview内加载的页面进行过跳转，会优先进行webview内页面的后退，当无history可以后退时，才会关闭页面，此逻辑目前不可更改
