### ISSUE TITLE
原生APP打包时希望可以选择不同的.env环境变量配置文件。

### ISSUE THREAD

**Issue by VirensCn** [dcloudio/uni-app#5141]
项目下有多个.env.production_xxxxx ，在打包时希望可以选择不同的配置文件。

**Comment by bfc846958672** [comment]
按照 [vite env](https://cn.vitejs.dev/guide/env-and-mode#env-files)文档自行配置多个环境，比如.env.a ,.env.b,.env.production

**Comment by bfc846958672** [comment]
用cli 项目， cli命令行打包可以补充 --mode 参数

**Comment by VirensCn** [comment]
> 用cli 项目， cli命令行打包可以补充 --mode 参数

这个只能用于打包相关的资源，不能生成apk吧。

**Comment by bfc846958672** [comment]
需求描述的再具体一点，最好贴一下代码

**Comment by VirensCn** [comment]
![image](https://github.com/user-attachments/assets/92839ade-d724-4bad-abc6-bb88ab59eaf3)

还有 https://hx.dcloud.net.cn/cli/pack?id=params 
这个地方支持设置环境变量文件，

**Comment by Otto-J** [comment]
这个问题，你可以换个思路绕过。这个举一个绕过方式，官方就不做额外的支持了。

比如 vue3 项目，可以编写一个 vite 插件，在项目开始时候注入相应变量，从而实现根据平台注入不同的环境变量

下面这个案例，发现当前启动应用是 ios 时候，注入环境变量，在 app.vue 可以可以打印。

```ts
import {
	defineConfig
} from 'vite';
import uni from '@dcloudio/vite-plugin-uni';

let hasRenamed = false;
export default defineConfig({
	plugins: [{
			name: 'vite-plugin-rename-env',
			enforce: 'pre', // 确保插件在其他插件之前执行
			configResolved(config) {
				// 打印当前环境变量
				const isIos = process.env.UNI_APP_PLATFORM === 'ios'
				if (isIos && !hasRenamed) {
					process.env.VITE_CURRENT_MODE = 'ios'

				}
			}
		},
		uni(),
	],
});

```

**Comment by VirensCn** [comment]
但是这样也有一个问题，我需要的是打包同一个平台时有不同的环境变量参数(VITE_APP开头的那些自定义变量)

**Comment by toesbieya** [comment]
云打包没辙

目前只能打包前写个脚本生成一个指定mode的文件，vite配置里读取mode

然后修改vite-plugin-uni里的initEnv方法，把mode的赋值去掉，或者在vite配置里自己loadEnv，然后替换字符串

**Comment by toesbieya** [comment]
我估计uniapp的人自己都不用的，这回复的都牛头不对马嘴

**Comment by VirensCn** [comment]
> 我估计uniapp的人自己都不用的，这回复的都牛头不对马嘴

我先就是写了个脚本，在打包前现在执行这个，生成`.env.production.local`，然后再正常运行`package.json`命令

正好这样就可以完成`manifest.json`文件修改，app的包路径修改。

```json
{
  "scripts": {
    "build:safemode:dev": "node ./build/app-prepare.js mode=production_dev && node ./build/app-build.js"
  }
}
```
`.env.production_dev`文件替换参数定义
![image](https://github.com/user-attachments/assets/632eb520-4823-43f7-a05f-498194a70dd0)

脚本部分
[build.zip](https://github.com/user-attachments/files/18253684/build.zip)

**Comment by iShawnWang** [comment]
为什么最终的结果是: `Closed as not planned` ?

**Comment by iShawnWang** [comment]
@Otto-J
