### ISSUE TITLE
[⁠TypeError⁠]‍ {message: "(0 , _tslib.__spreadArray) is not a function"}

### ISSUE THREAD

**Issue by mycodemanager** [dcloudio/uni-app#5145]
使用antv/g2plot插件，会出现这个错误，奇怪的是用命令创建的项目没问题，但是用hBuilderX创建的项目就会报这个错误
![Uploading image.png…]()

**Comment by bfc846958672** [comment]
图片看不到，提供一些可复现的demo工程
