### ISSUE TITLE
uni.getRecorderManager() 在鸿蒙 next 上调不起录音或者无效果

### ISSUE THREAD

**Issue by wl386123298** [dcloudio/uni-app#5146]
uni.getRecorderManager() 在鸿蒙 next 上无效果，也无法调起录音，但是文档上描述说支持鸿蒙 next

**Comment by StrivingRabbit** [comment]
使用的那个版本的 sdk？怎么调用的？把你出问题的代码贴上来

**Comment by wl386123298** [comment]
> 使用的那个版本的 sdk？怎么调用的？把你出问题的代码贴上来

sdk版本： "@dcloudio/uni-app": "3.0.0-4020420240722002",
    "@dcloudio/uni-app-harmony": "3.0.0-4020420240722002",

**Comment by StrivingRabbit** [comment]
兼容性标错了，可以等待 hx 4.28 发布。或者将附件在 `@dcloudio/uni-app-harmony/dist` 中替换同名文件试试看


[uni.api.ets.zip](https://github.com/user-attachments/files/16974740/uni.api.ets.zip)

**Comment by wl386123298** [comment]
> 兼容性标错了，可以等待 hx 4.28 发布。或者将附件在 `@dcloudio/uni-app-harmony/dist` 中替换同名文件试试看
> 
> [uni.api.ets.zip](https://github.com/user-attachments/files/16974740/uni.api.ets.zip)

4.28 啥时候发布呢
