### ISSUE TITLE
targetSdkVersion升级到34后，fcm消息推送点击后，plus.push.addEventListener("receive",function) 和plus.push.addEventListener("click",function)无法触发

### ISSUE THREAD

**Issue by Overclockers** [dcloudio/uni-app#5148]
问题描述
targetSdkVersion升级到34后，fcm消息推送点击后，plus.push.addEventListener("receive",function) 和plus.push.addEventListener("click",function)无法触发相应的监听事件

降级到targetSdkVersion为33后，就正常

复现步骤
[复现问题的步骤]
点击消息推送

预期结果
进入相关的事件监听回调方法处理

实际结果
进入相关的事件监听回调方法处理

系统信息:

发行平台: APP
操作系统 Android 14
HBuilderX版本 HBuilderX 3.99
采用离线打包的模式

**Comment by Otto-J** [comment]
感谢反馈，请使用最新的 alpha 再次测试一下，如果仍有问题，请 reopen  

> App-Android平台 修复 运行调试 离线打包基座，targetSdk34下真机运行失败 [详情](https://issues.dcloud.net.cn/pages/issues/detail?id=2424)
