### ISSUE TITLE
uni.chooseVideo 无法触发回调 后续如再次打开系统相册，提示相册已打开 无法继续操作

### ISSUE THREAD

**Issue by foxantony360** [dcloudio/uni-app#515]
详细问题描述
选择视频接口 uni.chooseVideo只能成功运行一次，并且没有触发任何回调 无论成功失败
如果再次调用uni.chooseVideo接口， 直接走失败回调
使用 plus.gallery.pick(successCB, errorCB, options); 测试提示 msg：相册已打开 code：

IDE运行环境说明
HBuilderX最新版

uni-app运行环境：5+app

[手机型号] 三星S8

**Comment by zhetengbiji** [comment]
其他机型是否正常？
手机的系统版本多少？

**Comment by zhetengbiji** [comment]
此问题长期无回应，暂时关闭
