### ISSUE TITLE
h5 可以路由到其他页面吗？打包完成之后只有一个index.html。

### ISSUE THREAD

**Issue by sun-wenming** [dcloudio/uni-app#516]
**问题描述**
#### h5 浏览
h5 无法直接访问二级页面吗？只能访问启动页？因为打包完成之后只有一个index.html。
在微信中授权功能，需要直接重定向二级页面获取code值，目前是重定向了启动页`index.html`

**复现步骤**
3. 查看
可以访问启动页(**pages数组中第一项表示应用启动页**)，无法直接访问非启动页 ( 页面显示内容为 ： 404)。因为只能路由到  `index.html` 其他无法路由。

```
{
	"pages": [ //pages数组中第一项表示应用启动页
		{
			"path": "pages/proxy/index/index",
			"style": {
				"navigationBarTitleText": "",
				"disableScroll": true,
				"navigationBarBackgroundColor": "#6C4FE7",
				"navigationBarTextStyle": "white"
			}
		}, {
			"path": "pages/proxy/apply/apply",
			"style": {
				"navigationBarTitleText": "申请金牌播主",
				"navigationBarBackgroundColor": "#6C4FE7",
				"navigationBarTextStyle": "white"

			}
		}
}
```
**预期结果**
可以访问或重定向 h5 二级页面
**实际结果**
打完包之后只有 `index.html` ，所有页面访问需要先经过 `index.html`

**系统信息:**
与系统无关

**补充信息**
我想到一个方法是通过给启动页`index.html`参数，让启动页通过参数自动跳转到相应页面，请问有其他合适的方案吗？使之可以直接访问二级页面。

**Comment by zhetengbiji** [comment]
HTML5 History 模式需要服务端配置，参考：https://router.vuejs.org/zh/guide/essentials/history-mode.html

**Comment by sun-wenming** [comment]
谢谢，很帮的思路。我找到了适合 Golang web框架`gin`的HTML5 History 模式处理方法。希望对他人有用。
https://github.com/gin-gonic/gin/issues/1048
