### ISSUE TITLE
uniapp/小程序怎么判断出蓝牙设备的类型，例如 耳机、打印机这种的类型

### ISSUE THREAD

**Issue by hafe-github** [dcloudio/uni-app#5161]
uniapp低功耗蓝牙，搜索到设备列表后，需要判断不同设备的类型，例如耳机、打印机、键盘等类型。这个可以通过那个API进行判断处理吗?或者有什么plus可供使用吗?

**Comment by bfc846958672** [comment]
目前没有相关api， 需要自行判断处理
