### ISSUE TITLE
app.vue 页面跳转不触发

### ISSUE THREAD

**Issue by front-endLiu** [dcloudio/uni-app#5168]
升级至4.28.2024092502，app.vue在onLaunch不能触发页面跳转，4.24版本没问题的

**Comment by bfc846958672** [comment]
你好， 我这边用HBuilder 4.28 没有复现，提供一些你那边的demo工程

**Comment by bfc846958672** [comment]
长时间未响应，关闭本issue。 如还有问题，可 reopen issue 继续讨论。
