### ISSUE TITLE
vue3 vite配置了  vue: "vue/dist/vue.esm-bundler.js",  does not provide an export named 'injectHook'

### ISSUE THREAD

**Issue by angryWang** [dcloudio/uni-app#5169]
vue3 vite 项目配置了 
    resolve: {
            alias: {
                vue: "vue/dist/vue.esm-bundler.js",
            },
        },
运行h5项目就会白板
SyntaxError: The requested module '/node_modules/vue/dist/vue.esm-bundler.js?v=9f72505d' does not provide an export named 'injectHook'
配置过 @dcloudio/vite-plugin-uni 插件

**Comment by bfc846958672** [comment]
不能对vue进行alias设置。
  uniapp插件内部有对 vue 做alias设置，以便指向uniapp内部定制化的vue 库。
