### ISSUE TITLE
在template标签里的this指向问题，H5中this.$store可以访问到在vue prototype上挂载的数据，在app真机调试就不行。

### ISSUE THREAD

**Issue by jiao1187875445** [dcloudio/uni-app#517]
在template标签里的this指向问题，H5中this.$store可以访问到在vue prototype上挂载的数据，在app真机调试就不行。
===============index.vue=============
`<template>
		<view>
			<text class="title">{{this.$const.DOMAIN_TECHNIQUE}}</text>
		</view>
</template>`
===============main.js==============
`import Vue from 'vue'
import App from './App'
import store from './store/index.js'
import api from './common/api.js'
import constant from './common/constant.js'

Vue.prototype.$api = api;

Vue.prototype.$const = constant;

Vue.prototype.$store = store;

Vue.config.productionTip = false;

App.mpType = 'app'

const app = new Vue({
	store,
    ...App
})
app.$mount()`
===================constant.js==============
const PROTOCOL = 'http://';	

const DOMAIN = process.env.NODE_ENV === 'development' ? 'aaa.net' : 'aaa.cn'

const DOMAIN_TECHNIQUE = PROTOCOL + 'jishu.' + DOMAIN;	

export default {
	DOMAIN,		
	PROTOCOL,	
	DOMAIN_TECHNIQUE,
}

**Comment by zhetengbiji** [comment]
测试未复现问题，使用新版HBuilderX测试一下，若仍有问题，提供一个测试示例

**Comment by social-uni** [comment]
> 测试未复现问题，使用新版HBuilderX测试一下，若仍有问题，提供一个测试示例

相似问题 ，1 [挂载数据到Vue.prototype上，view无法映射](https://github.com/dcloudio/uni-app/issues/1361)

2 [uniapp，微信小程序下，不支持在模板语法中直接访问全局变量](https://github.com/dcloudio/uni-app/issues/2721)
