### ISSUE TITLE
vue3-cli项目依赖更新后无法正常构建

### ISSUE THREAD

**Issue by peerless-hero** [dcloudio/uni-app#5170]
vue3-cli项目，根据控制台提示，使用命令“npx @dcloudio/uvm@latest”将uni相关依赖更新为9月25日发布的3.0.0-4020820240925001版本之后，原本可以正常打包构建的项目直接构建失败了。

<img alt="bug" src="https://github.com/peerless-hero/uniapp-bug/raw/vite-plugin-uni-3.0.0-4020820240925001/src/static/bug.png" />

经过逐一排查，发现是vite-plugin-uni这个依赖导致的问题。

这里提供可供复现的demo源码：
仓库地址：[https://github.com/peerless-hero/uniapp-bug/tree/vite-plugin-uni-3.0.0-4020820240925001](https://github.com/peerless-hero/uniapp-bug/tree/vite-plugin-uni-3.0.0-4020820240925001)

目前我是单独回滚了vite-plugin-uni这个依赖的版本，但不确定有没有隐患问题，所以还望官方尽早修复。

**Comment by chergn** [comment]
怎么让项目支持unocss+iconify图标啊

**Comment by peerless-hero** [comment]
> 怎么让项目支持unocss+iconify图标啊

麻烦另开新的issues，这个与本议题无关。

**Comment by peerless-hero** [comment]
当前问题已在最新的 **3.0.0-4020920240930001** 版本修复！
