### ISSUE TITLE
wxcomponents 下的 ts 为啥不能被编译成js

### ISSUE THREAD

**Issue by kcikkick** [dcloudio/uni-app#5176]
<img width="356" alt="企业微信截图_109447ac-53e2-4ead-8d5c-31353cf35f6b" src="https://github.com/user-attachments/assets/06630db8-c2f2-4475-9768-269baf8d0da5">
<img width="538" alt="企业微信截图_16c007c1-60f7-4e87-8635-08bba2fd5cd2" src="https://github.com/user-attachments/assets/e36b7838-fb3e-4c20-9de3-3a0c4dc2c9de">
<img width="203" alt="企业微信截图_2a472142-2eb6-48dd-a00d-a23059b065bb" src="https://github.com/user-attachments/assets/9e3fc40b-4667-42a7-a891-132d0c663f99">

求大佬帮忙

**Comment by fxy060608** [comment]
uni-app的编译器只会原封不动的copy wxcomponents目录，不会编译里边的东西，wxcomponents的编译是微信小程序处理的

**Comment by kcikkick** [comment]
@fxy060608 大佬这个要怎么在项目加呢？

**Comment by fxy060608** [comment]
> @fxy060608 大佬这个要怎么在项目加呢？

如果必须在wxcomponents里边写ts，那可以配置tsc的命令，自己用tsc来编译wxcomponents里边的ts文件为js
如果是用的三方组件，那可以使用三方组件编译出来js版本，不使用ts源码。

**Comment by fxy060608** [comment]
> @fxy060608 可以支持下吗？我这边开发也要实时更新

配置好tsconfig.json，指向wxcomponents，起个命令行，tsc -w 就可以watch文件编译ts了。

**Comment by kcikkick** [comment]
@fxy060608 大佬，下面的配置文件需要改哪里吗？

{
  "compilerOptions": {
    "target": "esnext",
    "module": "esnext",
    "strict": true,
    "jsx": "preserve",
    "importHelpers": true,
    "moduleResolution": "node",
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "experimentalDecorators":true,
    "sourceMap": true,
    "resolveJsonModule": true,
    "noImplicitAny": true,
    "baseUrl": ".",
    "types": [
      "node",
      "webpack-env",
      "@dcloudio/types/uni-app",
      "miniprogram-api-typings"
    ],
    "paths": {
      "@/*": [
        "./src/*"
      ]
    },
    "lib": [
      "esnext",
      "dom",
      "dom.iterable",
      "scripthost"
    ]
  },
  "exclude": [
    "node_modules",
    "unpackage",
    "outdated"
  ]
}
