### ISSUE TITLE
input type为digit情况下，chorm版本的手机模式下，含有小数点删除到小数点处会将光标定位到最前面

### ISSUE THREAD

**Issue by yunanshen** [dcloudio/uni-app#5185]

**Comment by Otto-J** [comment]
感谢反馈，试一下最新的依赖、最新的 HBuilderX alpha 是否还有这个问题，并说一下 vue 版本，这个问题印象中修复过

**Comment by Otto-J** [comment]
经过我测试最新的 HBuilderX alpha 运行 vue2/vue3 到 web 平台，使用 `		<input type="digit" style="border: 1px solid red;" />` 运行到手机 edge 浏览器、微信内置浏览器 都可以正常删除小数点，光标不变。

如果有新的进展请 reopen 并补充单页面源码，提供更多环境信息
