### ISSUE TITLE
微信小程序端视频封面图无法显示？

### ISSUE THREAD

**Issue by LadyChatterleyLover** [dcloudio/uni-app#519]
微信小程序端视频封面图无法显示，浏览器端和手机端都是正常的？怎么解决呢？

**Comment by zhetengbiji** [comment]
使用原生小程序项目测试一下，如果仍然有问题，可以反馈给微信小程序社区

**Comment by zhetengbiji** [comment]
此问题长时间未回应，暂时关闭

**Comment by zzlbt** [comment]
微信小程序视频点击播放后，操作按钮就消失了，楼上有遇到这样的情况吗
