### ISSUE TITLE
input控件在电脑chrome中能够正常渲染，但是在微信小程序中不渲染出来

### ISSUE THREAD

**Issue by Thomas-Lei** [dcloudio/uni-app#520]
![image](https://user-images.githubusercontent.com/26401787/60637077-8d304f00-9e4b-11e9-8493-97dd5919e0fb.png)

**Comment by Thomas-Lei** [comment]
这个问题应该是v-for造成的，我不用v-for就没有问题了。
				<view class="uni-list" v-if="question.questiontype == 'BLANK'">
					<textarea @input = "oninput()" :disabled = "disableQuestion" :key="answerofquestion(question.id).id" v-model="answerofquestion(question.id).name" class="tpw-anwser-input"></textarea>
				</view>

**Comment by zhetengbiji** [comment]
测试未复现，使用新版HBuilderX测试一下，若仍有问题，请提供一个测试工程
