### ISSUE TITLE
对象绑定值 如果是一个空对象 在手机上会显示undefined，h5和小程序上会不显示

### ISSUE THREAD

**Issue by SilasDong** [dcloudio/uni-app#521]
比如
{{detail.name}}
如果name是空，在Android手机上就会显示undefined，h5不会，
这样每个都需要改成{{detail.name || ''}}

每个写法都要做一个判断空，看看能不能跟h5统一

**Comment by zhetengbiji** [comment]
考虑性能影响，暂不统一封装
