### ISSUE TITLE
微信小程序端的 `wx.getSystemInfo` / `wx.getSystemInfoSync` 停止维护

### ISSUE THREAD

**Issue by xiaohe0601** [dcloudio/uni-app#5215]
微信小程序端的 `wx.getSystemInfo` / `wx.getSystemInfoSync` / `wx.getSystemInfoAsync` 停止维护，uniapp的框架中仍然有使用到，控制台报出大量警告。

```
wx.getSystemInfoSync is deprecated.
Please use wx.getSystemSetting/wx.getAppAuthorizeSetting/wx.getDeviceInfo/wx.getWindowInfo/wx.getAppBaseInfo instead.

cn @vendor.js:formatted:1
ft @vendor.js:formatted:1
ht @vendor.js:formatted:1
...
```

> [wx.getSystemInfoSync](https://developers.weixin.qq.com/miniprogram/dev/api/base/system/wx.getSystemInfoSync.html)
>
> 从基础库 [2.20.1](https://developers.weixin.qq.com/miniprogram/dev/framework/compatibility.html) 开始，本接口停止维护，请使用 [wx.getSystemSetting](https://developers.weixin.qq.com/miniprogram/dev/api/base/system/wx.getSystemSetting.html)、[wx.getAppAuthorizeSetting](https://developers.weixin.qq.com/miniprogram/dev/api/base/system/wx.getAppAuthorizeSetting.html)、[wx.getDeviceInfo](https://developers.weixin.qq.com/miniprogram/dev/api/base/system/wx.getDeviceInfo.html)、[wx.getWindowInfo](https://developers.weixin.qq.com/miniprogram/dev/api/base/system/wx.getWindowInfo.html)、[wx.getAppBaseInfo](https://developers.weixin.qq.com/miniprogram/dev/api/base/system/wx.getAppBaseInfo.html) 代替

#### 版本信息
- uniapp：3.0.0-4020920240930001
- vue：3.4.38

**Comment by tianzhich** [comment]
好像现在 build 后的版本调用这个接口没获取到信息了，dev 还可以

**Comment by Johnwjl** [comment]
+1

**Comment by bombzj** [comment]
+1

**Comment by xingstudy** [comment]
+1

**Comment by Get-wy** [comment]
还是没有解决吗 半年了 哥们

**Comment by GRCmade** [comment]
> 还是没有解决吗 半年了 哥们

uniapp框架的警告已经删除，如果还存在警告，需要自己删除代码中使用到的
