### ISSUE TITLE
在图片的src写函数，最后不会渲染图片处理

### ISSUE THREAD

**Issue by SilasDong** [dcloudio/uni-app#522]
比如我在一个基础混合器里面做一个图片路径的统一处理
<image :src=‘showImage’ > </image>

showImage() {
    // 判断是否是逗号，取第一张
}

在h5和小程序上可以正常显示，但是Android上面  不会出现图片

**Comment by zhetengbiji** [comment]
提供一下复现问题的示例项目

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
