### ISSUE TITLE
运行为鸿蒙应用，在h5中想通过urlSchemes协议唤起App，提示ERR_UNKNOWN_URL_SCHEME

### ISSUE THREAD

**Issue by LBINGXIN** [dcloudio/uni-app#5221]
运行为鸿蒙应用，在h5中想通过urlSchemes协议例如hbuilder://www.test.com:80唤起app，提示ERR_UNKNOWN_URL_SCHEME
在harmony-configs/entry/src/main/module.json5做个根据文档的配置了scheme, https://developer.huawei.com/consumer/cn/doc/best-practices-V5/bpta-web-app-jump-and-pull-up-V5#section37419543116
skills: [
  {
    entities: ['entity.system.home', 'entity.system.browsable'],
    actions: ['action.system.home', 'ohos.want.action.viewData'],
    uris: [
      {
        scheme: 'hbuilder',
        host: 'www.test.com',
        port: '80', 
      },
    ],
  },
],

**Comment by StrivingRabbit** [comment]
看一下编译出来的项目的配置是否符合预期，编译出来的项目在 unpackage/debug 下
