### ISSUE TITLE
使用 TypeScript 时为组件定义非 Vue.js 原生属性时出现类型错误

### ISSUE THREAD

**Issue by t532** [dcloudio/uni-app#523]
**问题描述**
使用 TypeScript 时为组件定义非 Vue.js 原生属性时出现类型错误。

**复现步骤**
定义一个组件：
```vue
...
<script>
export default {
    ...
    onLoad() {
        ...
    }
    ...
}
</script>
```

**预期结果**
通过静态类型检查并且运行期在适当的时间触发钩子。

**实际结果**
无法通过静态类型检查，但运行期在适当的时间触发了钩子。
（错误信息：`Object literals may only specify known properties, but onLoad(): void does not exist on type ComponentOptions<...>.`）

**系统信息:**
 - 发行平台: 所有。
 - 操作系统: 所有。
 - uni-app版本: latest.
 - 设备信息: 所有。

**补充信息**
问题的产生原因是 uni-app 没有对 Vue.js 的类型定义做扩展。

**解决方案**
在类型声明（`.d.ts`）文件中添加：
```ts
import Vue from 'vue'
import { DefaultData, DefaultMethods, DefaultComputed, PropsDefinition, DefaultProps } from 'vue/types/options'
declare module 'vue' {
    interface ComponentOptions<
        V extends Vue,
        Data=DefaultData<V>,
        Methods=DefaultMethods<V>,
        Computed=DefaultComputed,
        PropsDef=PropsDefinition<DefaultProps>,
        Props=DefaultProps> {
        mpType?: string;
        onLaunch?(): void;
        onShow?(): void;
        onHide?(): void;
        onUniNViewMessage?(payload: {
            data: Record<string, string>;
        }): void;
        onLoad?(querystring: Record<string, string>): void;
        onShow?(): void;
        onReady?(): void;
        onHide?(): void;
        onUnload?(): void;
        onResize?(): void;
        onPullDownRefresh?(): void;
        onReachBottom?(): void;
        onTabItemTap?(event: {
            index: string;
            pagePath: string;
            text: string;
        }): void;
        onShareAppMessage?(): void;
        onPageScroll?(event: {
            scrollTop: number;
        }): void;
        onNavigationBarButtonTap?(event: {
            index: number;
        }): void;
        onBackPress?(event: {
            from: string;
        }): void;
        onNavigationBarSearchInputChanged?(): void;
        onNavigationBarSearchInputConfirmed?(): void;
        onNavigationBarSearchInputClicked?(): void;
        // other non-vue properties ...
    }
}
```

**Comment by zhetengbiji** [comment]
是 CLI 创建的 TS 项目吗？

**Comment by t532** [comment]
@zhetengbiji 是的。

**Comment by t532** [comment]
@zhetengbiji cli 模板中 `tsconfig.json` 的 `"types"` field 的确包含了 `@dcloudio/types`，但 vscode 似乎无法很好地适配。

这是 vscode 的问题，所以我 close 这个 issue。

**Comment by SuperIron** [comment]
添加 import '@dcloudio/types/uni-app'; 后

**Comment by SuperIron** [comment]
你好 添加 import '@dcloudio/types/uni-app'; 后
类型不会报错 但是会提示依赖找不到
 -- This dependency was not found:
 -- To install it, you can run: npm install --save @dcloudio/types/uni-app

**Comment by SuperIron** [comment]
> **问题描述**
> 使用 TypeScript 时为组件定义非 Vue.js 原生属性时，vscode 检测为类型错误。
> 
> **复现步骤**
> 定义一个组件：
> 
> ```
> ...
> <script>
> export default {
>     ...
>     onLoad() {
>         ...
>     }
>     ...
> }
> </script>
> ```
> 
> **预期结果**
> 通过静态类型检查并且运行期在适当的时间触发钩子。
> 
> **实际结果**
> 无法通过 vscode 的静态类型检查，但通过了 build script 的静态类型检查。运行期在适当的时间触发了钩子。
> （错误信息：`Object literals may only specify known properties, but onLoad(): void does not exist on type ComponentOptions<...>.`）
> 
> **系统信息:**
> 
> * 发行平台: 无关。
> * 操作系统: 无关。
> * uni-app版本: latest.
> * 设备信息: 无关。
> 
> **补充信息**
> 问题的产生原因是 vscode 无法适配 `tsconfig.json` 中的 `"types"` field。
> 
> **解决方案**
> 在所有 .vue 文件的 `<script>` 中添加：
> 
> ```ts
> import '@dcloudio/types/uni-app';
> ```
你好

**Comment by SuperIron** [comment]
> @zhetengbiji cli 模板中 `tsconfig.json` 的 `"types"` field 的确包含了 `@dcloudio/types`，但 vscode 似乎无法很好地适配。
> 
> 这是 vscode 的问题，所以我 close 这个 issue。
> 
> 另：要解决这个问题，可以通过在每个 `.vue` 文件的 `<script>` 中添加：
> 
> ```ts
> import '@dcloudio/types/uni-app';
> ```

你好 import '@dcloudio/types/uni-app'; 会提示  
This dependency was not found: 
To install it, you can run: npm install --save @dcloudio/types/uni-app
同vscode + ts

**Comment by zfben** [comment]
这个问题解决了吗？
