### ISSUE TITLE
vue自定义组件父子传参时小程序出现的问题

### ISSUE THREAD

**Issue by Yiusing** [dcloudio/uni-app#524]
**问题描述**
vue中定义了父子组件，当父组件向子组件通过 return一个函数传递给子组件时，子组件拿到的porps是undefined。

**复现步骤**
```
<!-- parent -->
  <child :fn="fn( )"></child>
  <script>
    export default {
       methods:{
           fn( ) {
              return value => { console.log(value) }
           }
       }
    }
  </script>
<!-- parent -->

<!-- child -->
 export default {
    props:{
       fn:Function
    }
 }
<!-- child -->
```

**预期结果**
在子组件的props中 fn的值为 value=>{console.log(value)}该函数

**实际结果**
在子组件的props中 fn的值为 null

**系统信息:**
 - 发行平台:  微信小程序
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**Comment by yjj5855** [comment]
我也遇到了 
![image](https://user-images.githubusercontent.com/6870430/69227805-6f2a7780-0bbd-11ea-8614-5c8f34b44fd9.png)

请问有解决办法吗？

**Comment by yjj5855** [comment]
# 微信小程序中 
1. 在uni-mp-weixin/dist/index.js的function parseBaseComponent
```
properties:initProperties(vueOptions.props,false,vueOptions.__file)
中调用了createObserver方法


function createObserver (name) {
  return function observer (newVal, oldVal) {
    if (name === 'rules') {
      console.error(newVal, oldVal) // 输出得到
    }
    if (this.$vm) {
      this.$vm[name] = newVal; // 为了触发其他非 render watcher
    }
  }
}
```
![image](https://user-images.githubusercontent.com/6870430/69332811-66f03c00-0c92-11ea-900c-ef757bcdfc68.png)

# 输出了2次数据变化
第一次是从初始默认状态 转变为 父组件data赋值给子组件prop，没有问题，有`validator`属性
第二次`validator`属性消失，经过错误报告发现是` this.$vm.$mount();`挂载之后触发了变化
在差量更新的方法中用了`JSON.parse(JSON.stringify(ret))`，所以导致`validator`属性消失
```
function cloneWithData(vm) {
  // 确保当前 vm 所有数据被同步
  var ret = Object.create(null);
  var dataKeys = [].concat(
    Object.keys(vm._data || {}),
    Object.keys(vm._computedWatchers || {}));

  dataKeys.reduce(function(ret, key) {
    ret[key] = vm[key];
    return ret
  }, ret);
  //TODO 需要把无用数据处理掉，比如 list=>l0 则 list 需要移除，否则多传输一份数据
  Object.assign(ret, vm.$mp.data || {});
  if (
    Array.isArray(vm.$options.behaviors) &&
    vm.$options.behaviors.indexOf('uni://form-field') !== -1
  ) { //form-field
    ret['name'] = vm.name;
    ret['value'] = vm.value;
  }
  return JSON.parse(JSON.stringify(ret)) // 不能被解析的属性都会丢失
}
```

# 错误文件在
![image](https://user-images.githubusercontent.com/6870430/69335889-97d36f80-0c98-11ea-85f5-31b55f07b526.png)

**Comment by Yiusing** [comment]
hi
我没有解决到这个问题
我用了另外一个方案去替代了
既然你找到了问题，希望官方能解决一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"yjj5855"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月21日(星期四) 晚上7:54
收件人:&nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&gt;;
抄送:&nbsp;"Yiusing"<376126723@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] vue自定义组件父子传参时小程序出现的问题 (#524)




微信小程序中
  
在uni-mp-weixin/dist/index.js的function parseBaseComponent
  properties:initProperties(vueOptions.props,false,vueOptions.__file) 中调用了createObserver方法 function createObserver (name) {   return function observer (newVal, oldVal) {     if (name === 'rules') {       console.error(newVal, oldVal) // 输出得到     }     if (this.$vm) {       this.$vm[name] = newVal; // 为了触发其他非 render watcher     }   } }  

 
输出了2次数据变化
 
第一次是从初始默认状态 转变为 父组件data赋值给子组件prop，没有问题，有validator属性
 第二次validator属性消失，经过错误报告发现是 this.$vm.$mount();挂载之后触发了变化
 在差量更新的方法中用了JSON.parse(JSON.stringify(ret))，所以导致validator属性消失
 function cloneWithData(vm) {   // 确保当前 vm 所有数据被同步   var ret = Object.create(null);   var dataKeys = [].concat(     Object.keys(vm._data || {}),     Object.keys(vm._computedWatchers || {}));   dataKeys.reduce(function(ret, key) {     ret[key] = vm[key];     return ret   }, ret);   //TODO 需要把无用数据处理掉，比如 list=&gt;l0 则 list 需要移除，否则多传输一份数据   Object.assign(ret, vm.$mp.data || {});   if (     Array.isArray(vm.$options.behaviors) &amp;&amp;     vm.$options.behaviors.indexOf('uni://form-field') !== -1   ) { //form-field     ret['name'] = vm.name;     ret['value'] = vm.value;   }   return JSON.parse(JSON.stringify(ret)) // 不能被解析的属性都会丢失 }  
错误文件在

**Comment by www295686243** [comment]
@Yiusing 请教下，你另一种方案是如何做的，目前官方还没解决这个问题，这让我无法设计通用组件

**Comment by Nstd** [comment]
2020年了，这个问题还没修复吗？

**Comment by Lliuxs** [comment]
还没解决这个问题吗？

**Comment by StrivingRabbit** [comment]
不支持传递不可序列化的数据，数据会丢失。请改用其他方式处理
