### ISSUE TITLE
支付宝H5页面中的地图组件定位有误

### ISSUE THREAD

**Issue by zysallen** [dcloudio/uni-app#525]
**新功能描述**
支付宝H5页面中的地图组件定位有误

**现状及问题**
支付宝H5页面中使用地图组件的`show-location`，发现定位不准确，但是在其他环境是没问题的，怀疑是支付宝H5的兼容性问题

**尝试方案**
尝试更改源码中`src\platforms\h5\view\components\map\index.vue `的`uni.getLocation`方法中的`type`参数，根据不同平台使用不同的坐标系，问题解决，代码如下：
```
uni.getLocation({
    type: IS_ALI_ENV ? 'wgs84' : 'gcj02',     //如果是支付宝H5环境就用wgs84坐标系
    success: res => {
        //...
    } ,
    fail: res => {
        //...
    } 
})
```
**补充信息**

**Comment by zhetengbiji** [comment]
是不是没有配置腾讯地图的key，另外单独调用 uni.getLocation 获取 gcj02 坐标是否正确？
