### ISSUE TITLE
自定义组件模式 图片无法显示

### ISSUE THREAD

**Issue by chen-can** [dcloudio/uni-app#526]
在自定义组件模式下，h5端图片使用绝对路径可以显示图片，但是在小程序端无法使用

**Comment by zhetengbiji** [comment]
使用BuilderX创建的项目还是CLI？如果是HBuilderX，版本号多少？

**Comment by chen-can** [comment]
等了这么久终于有回复了 
cli 创建的 也试过HBuilderX 版本号 2.0.7.20190711-alpha

**Comment by zhetengbiji** [comment]
非自定义组件模式下是否能正常显示？使用相对路径是否可以显示？

**Comment by hbcui1984** [comment]
代码示例上传一下

**Comment by chen-can** [comment]
子组件代码
<template>
  <div>
    <image :src="url" alt />
  </div>
</template>

<script>
export default {
  props: {
    url: {
      type: String
    }
  }
};
</script>
父组件代码
<template>
  <div>
   <test :url="url" />
  </div>
</template>

<script>
export default {
  data() {
    return {
      url: "../../../static/image/tab-ic-hom-selected.png"
    };
  },
};
</script>
目前测试用的是cli 模式

**Comment by chen-can** [comment]
请问下使用 / 在uni-app cli 模式代表的是不是src 目录
现在我路径改为“/static/image/tab-ic-hom-selected.png” 可以正常显示
