### ISSUE TITLE
{{}}中绑定methods中的方法返回值无效

### ISSUE THREAD

**Issue by zhaokgithub** [dcloudio/uni-app#529]
<template>
				
<view style="text-align: left;">{{formatDate(update_time) }}{{test()}}</view>
</template>

methods: {
		
		formatDate:function(timestap){
			let time = new Date(timestap)
                        console.log(time)//有值的
			return time
		}
}

**Comment by fxy060608** [comment]
编译模式是什么？仅自定义组件编译模式支持该写法 https://ask.dcloud.net.cn/article/35843

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
