### ISSUE TITLE
小程序崩溃问题

### ISSUE THREAD

**Issue by lichengqi** [dcloudio/uni-app#530]
**问题描述**
当有方法或者 computed字段在dom渲染中 如果报错导致微信小程序整站瘫痪

**复现步骤**
[复现问题的步骤]
1.  启动 '附件里面的项目'
2. 点击  ”变变变“发现第一个页面可以正常更新'
3. 点击去错误页面
4.点击变错误一或者变错误 导致错误页面报错
5.返回第一个页面 点击“变变变”按钮失效了。如果页面更多发现整站都瘫痪了
6.一旦报错退出小程序重启都没有用 要删除小程序

[源码见附件]

**预期结果**
[希望报错之后不导致整站崩溃，或者有什么解决方案]

**实际结果**
[源码和效果见附件]

**系统信息:**
 - 发行平台: [微信小程序]
 - 操作系统 [任何操作系统]
 - HBuilderX版本 [1.9.4]
 - uni-app版本 []
 - 设备信息 [任何设备]

**补充信息**
[可选]
希望可以尽快解决。问题比较严重。
[unibug.zip](https://github.com/dcloudio/uni-app/files/3366447/unibug.zip)

**Comment by fxy060608** [comment]
HBuilderX 2.1.0正式版已修复此问题
