### ISSUE TITLE
uni.clearStorage(); 在安卓红米note7中无法触发success/fail回调

### ISSUE THREAD

**Issue by haishangfeie** [dcloudio/uni-app#531]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
我尝试使用uni.clearStorage();清空app中的缓存，但执行后success和fail这两个回调函数均没有触发
**复现步骤**
[复现问题的步骤]
1.  设置一个缓存
2. 1s后使用
```
  uni.clearStorage({
    success() {
      console.log('uni.clearStorage success');
    },
    fail(err) {
      console.log(err);
      console.log('uni.clearStorage err');
    }
  });
```
3. 查看HBuilderX.exe输出

**预期结果**
清除缓存后success/fail可以正常触发

**实际结果**
success/fail未触发

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 Android 9.0
 - HBuilderX版本  2.0.1.20190614
 - 设备信息 红米note7

**Comment by zhetengbiji** [comment]
试一下 HBuilderX alpha 2.0.3以上版本是否能出现此问题

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
