### ISSUE TITLE
 h5端在IOS手机和部分安卓机中上传照片有问题

### ISSUE THREAD

**Issue by FLQ77** [dcloudio/uni-app#533]
**问题描述**

在h5端使用图片上传功能，IOS手机和部分安卓手机只能使用拍照，选取相册失效，在官方H5体验版中也是出现同样问题

**Comment by zhetengbiji** [comment]
被认定为“选取相册失效”的表现是什么？（比如没有相册选项？选取文件后不触发回调？）
iOS手机和部分安卓手机的机型和系统信息是什么？
另外，为什么不使用问题模版？

**Comment by FLQ77** [comment]
失效是指 选取文件后不触发回调，机型的话（因为是客服那边反馈过来的数据，大概包括常见的IOS机型，目前自己测过的有苹果8和苹果6，安卓的话小米Max，系统信息就不太清楚），小菜鸡不怎么会提问，不好意思没有使用提问模板

**Comment by FLQ77** [comment]
问题解决了，可能原因是在调用uni.chooseImage时没有设置sourceType参数，导致在微信中打开h5选取相册图片无法触发回调
