### ISSUE TITLE
video标签宽高和下拉刷新在app端和h5小程序表现不一致

### ISSUE THREAD

**Issue by d0apga** [dcloudio/uni-app#534]
**问题描述**
1.打包成app时，video宽高表现和h5、微信小程序不一致
2.在启用下拉刷新时，在弹出的弹层使用scroll-view时，在app端无法下拉弹出层列表，h5和微信小程序可以下拉，但是如果app进列表页面时，先将列表拉到最下面，那么再弹出层可以正常下拉

**复现步骤**
[复现问题的步骤]

1.

[或者可以直接贴源代码]

**预期结果**
1.video标签在app下面应该超出隐藏
2.启用下拉刷新的页面，在弹出层也应可正常下拉

**实际结果**
1.h5版本
![h5](https://user-images.githubusercontent.com/1168900/60815286-e1c82700-a1c9-11e9-9e1d-a46724977c0e.gif)
2.微信小程序版本
![mp](https://user-images.githubusercontent.com/1168900/60815310-ec82bc00-a1c9-11e9-9892-49efc3bed00d.gif)
3.app版本
[ScreenRecord-2019-07-08-21-48-04.zip](https://github.com/dcloudio/uni-app/files/3368645/ScreenRecord-2019-07-08-21-48-04.zip)

**系统信息:**
 - 发行平台: 微信小程序、H5平台、5+ App
 - 操作系统 Android 9.0
 - HBuilderX版本 2.0.4.20190706-alpha
 - uni-app版本 
 - 设备信息 米6, AospExtended-6.6

**补充信息**
附加项目:
[feat-test.zip](https://github.com/dcloudio/uni-app/files/3368644/feat-test.zip)

**Comment by zhetengbiji** [comment]
1. App端video是原生组件，目前无法被其他非原生组件遮住
2.App端和小程序都是在scroll-view上无法下拉刷新的，H5后期会做成一致。
