### ISSUE TITLE
英文界面及文档

### ISSUE THREAD

**Issue by grammyleung** [dcloudio/uni-app#535]
**新功能描述**
有可能把IDE界面“英化”一下吗？打出这个词的时候还是小激动一下的，以前都是外文软件在汉化，现在终于有英化的需求了。

**现状及问题**
需要让外籍团队成员使用HBuilder及UniApp进行开发，反馈是界面难用没文档。

**尝试方案**
开源社区多语言化贡献的方案

**补充信息**
木有

**Comment by lirc572** [comment]
+1，在用vue开发android/ios的方案里uni-app算挺好用的，如果有英文文档和英文界面ide的话应该会吸引不少国外开发者。
如果有需要的话可以帮忙翻译

**Comment by StrivingRabbit** [comment]
IDE 和 文档现已有英文页面
