### ISSUE TITLE
vue-cli创建的vue项目能使用uni的扩展组件吗

### ISSUE THREAD

**Issue by guxingke201** [dcloudio/uni-app#536]
**新功能描述**
uni的扩展组件能用在历史vue项目中
**现状及问题**
公司的技术栈是vue，以前用vue开发了很多h5页面，现在想统一ui库，希望历史的h5页面和小程序用同一个ui库
**尝试方案**

**补充信息**

**Comment by fxy060608** [comment]
目前 h5 的内置组件均在该仓库 src/core/view/components 及 src/platforms/h5/view/components 中
目前暂未提供非 uni-app 项目中直接使用的组件库包，需要自己整理一下
