### ISSUE TITLE
不支持vue.config.js配置

### ISSUE THREAD

**Issue by lmf** [dcloudio/uni-app#537]
**问题描述**
会用manifest.json配置覆盖vue.config.js的配置，h5下devServer相关配置不太方便，也不太合理

**Comment by fxy060608** [comment]
npm update,已优化 devServer 配置，当 manifest.json 中无配置，vue.config.js 有时，会使用 vue.config.js 中的 devServer 配置

**Comment by lmf** [comment]
> npm update,已优化 devServer 配置，当 manifest.json 中无配置，vue.config.js 有，会使用 vue.config.js 中的 devServer 配置

@fxy060608 很迅速，赞！还有个问题我npm run build之后直接堆溢出了：
<img width="972" alt="image" src="https://user-images.githubusercontent.com/3777374/60880000-53a97a80-a275-11e9-93d9-0789c5e2b663.png">

**Comment by fxy060608** [comment]
> > npm update,已优化 devServer 配置，当 manifest.json 中无配置，vue.config.js 有，会使用 vue.config.js 中的 devServer 配置
> 
> @fxy060608 很迅速，赞！还有个问题我npm run build之后直接堆溢出了：
> <img alt="image" width="972" src="https://user-images.githubusercontent.com/3777374/60880000-53a97a80-a275-11e9-93d9-0789c5e2b663.png">

必现吗？是所有工程都这样，还是特定工程这样？可以发一个重现该问题的测试工程

**Comment by lmf** [comment]
不是必现，应该是编译时候占的内存超过限制了，我先关了
