### ISSUE TITLE
uni.getStorageSync 出错

### ISSUE THREAD

**Issue by lwpassvoice** [dcloudio/uni-app#538]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
uni.getStorageSync有时候会报错，不知道为什么会去parse一下

**复现步骤**
[复现问题的步骤]
浏览器中设置 localstorage.token = 33e0d4d6-a71f-4f49-a679-e4d3b57c581d

页面获取token： uni.getStorageSync('token');

![}B2{`O@ZF@6GO7HEZYL)@(O](https://user-images.githubusercontent.com/22510735/60871473-6c119900-a265-11e9-97cd-b65494a37b99.png)
![S9FFM$EE4X65Z$ 1RNF(N48](https://user-images.githubusercontent.com/22510735/60871482-703db680-a265-11e9-808b-21f826fd4f53.png)

使用官方demo实验也是这样
![4 N@6R9$E6W$_3O0JK0E`B8](https://user-images.githubusercontent.com/22510735/60872398-2fdf3800-a267-11e9-88df-350414fc6c7f.png)
![3G$ )5_7MM$}7D@%3OJ3Y5B](https://user-images.githubusercontent.com/22510735/60872411-32da2880-a267-11e9-9f0b-c8759ccc172e.png)

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: H5
 - 操作系统 windows7
 - HBuilderX版本 2.0.1.20190614
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 chrome浏览器73

**补充信息**
好像源码里对localstorage的值parse了下？

**Comment by zhetengbiji** [comment]
使用localstorage.token存储，就使用localstorage.token读取，请勿混合使用， uni.setStorage存储的值不限于字符串，所以使用JSON。
