### ISSUE TITLE
uni.d.ts 文件中声明的 upx2px() 函数没有定义 number, newDeiceWidth 参数。

### ISSUE THREAD

**Issue by simicn** [dcloudio/uni-app#539]
**问题描述**

uni.d.ts 文件中声明的 upx2px() 函数没有定义 number, newDeiceWidth 参数。

![image](https://user-images.githubusercontent.com/902283/60877669-d5e37000-a270-11e9-9322-2f11877b852e.png)

![image](https://user-images.githubusercontent.com/902283/60877033-97998100-a26f-11e9-94dd-5cfee31197f4.png)

**Comment by zhetengbiji** [comment]
已更新
