### ISSUE TITLE
uni.request 长整形数据返回异常问题

### ISSUE THREAD

**Issue by jonahzheng** [dcloudio/uni-app#540]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
https://blog.csdn.net/jonahzheng/article/details/95348808
通过uni.request访问接口数据是，发现返回的数据中长整形数据都异常，用其他http工具比如postman或jquery的方法又是正常的。
比如1145876441225760769变成1145876441225760800，被取整的感觉。

[暂时方案]
长整形的数据变成字符串返回就可以了，比如{"id":"1145876441225760769"}

**系统信息:**
 - 发行平台:微信小程序
 - 操作系统：mac
 - HBuilderX版本 [2.0.1.20190614 mac]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [微信小程序开发工具]

**Comment by zhetengbiji** [comment]
其他端（比如app、H5）是否有此问题，如其他端正常，请将问题反馈至微信小程序社区

**Comment by jonahzheng** [comment]
> 其他端（比如app、H5）是否有此问题，如其他端正常，请将问题反馈至微信小程序社区

看到了 uni.request的实现
https://github.com/dcloudio/uni-app/blob/master/src/core/service/api/network/request.js

`    if (responseType === 'TEXT' && dataType === 'JSON') {
      try {
        res = JSON.parse(res)
      } catch (error) {
        // 和微信一致解析失败不抛出错误
        // invoke(callbackId, {
        //   errMsg: 'request:fail json parse error'
        // })
        // return
      }`

152行 用了JSON.parse,这个函数的对int的长度的有限制
https://stackoverflow.com/questions/15699953/how-do-i-parse-json-into-an-int

**Comment by jonahzheng** [comment]
> let aa = '{"id":1116921417036771380}'
let bb = JSON.parse(aa);
console.log(bb.id);

输出 1116921417036771300

**Comment by zhetengbiji** [comment]
> > let aa = '{"id":1116921417036771380}'
> > let bb = JSON.parse(aa);
> > console.log(bb.id);
> 
> 输出 1116921417036771300

嗯，这是JS的限制，你的数值超出了 [MAX_SAFE_INTEGER](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER)

**Comment by jonahzheng** [comment]
https://www.npmjs.com/package/bignumber.js
