### ISSUE TITLE
uni.showToast在H5中的显示时间问题

### ISSUE THREAD

**Issue by ZhangyilinCN** [dcloudio/uni-app#541]
**问题描述**
在h5中使用uni.showToast提示框，持续时间太短

**复现步骤**

submitFN(e) {
			uni.showLoading({
				mask:true,
				title:'请稍后'
			})
			uni.request({
				url:‘xxxxxxxxxxxx’,
				method:'POST',
				data:e.detail.value,
				success: (res) => {
					console.log(res);
					if(res.data.status==200) {
						uni.setStorageSync('userInfo',res.data.data);
					}else {
						uni.showToast({
							title:res.data.msg,
							duration:999999
						})
					
					}
				},
				complete() {
					uni.hideLoading();
				}	
			})
		}

**Comment by fxy060608** [comment]
HBuilderX 2.1.0正式版已修复此问题
