### ISSUE TITLE
typescript 的type文件报错

### ISSUE THREAD

**Issue by SilasDong** [dcloudio/uni-app#542]
10:58:27.524 ERROR in F:/linux/vscode/eq/city-house/node_modules/@dcloudio/types/uni-app/uni.d.ts
10:58:27.549 24:5 '$on', which lacks return-type annotation, implicitly has an 'any' return type.
10:58:27.555     22 |      * 参考: [http://uniapp.dcloud.io/api/window/communication?id=on](http://uniapp.dcloud.io/api/window/communication?id=on)
10:58:27.583     23 |      */
10:58:27.588   > 24 |     $on(eventName?: string, callback?: () => void);
10:58:27.618        |     ^
10:58:27.624     25 |     /**
10:58:27.639     26 |      * 触发自定义事件，附加的参数会传递给事件监听器。
10:58:27.650     27 |      *
10:58:27.684 ERROR in F:/linux/vscode/eq/city-house/node_modules/@dcloudio/types/uni-app/uni.d.ts
10:58:27.689 30:5 '$emit', which lacks return-type annotation, implicitly has an 'any' return type.
10:58:27.701     28 |      * 参考: [http://uniapp.dcloud.io/api/window/communication?id=emit](http://uniapp.dcloud.io/api/window/communication?id=emit)
10:58:27.708     29 |      */
10:58:27.721   > 30 |     $emit(eventName?: string, param?: any);
10:58:27.725        |     ^
10:58:27.737     31 |     /**
10:58:27.741     32 |      * 监听一个自定义事件。事件只触发一次，在第一次触发之后移除事件监听器。
10:58:27.768     33 |      *
10:58:27.772 ERROR in F:/linux/vscode/eq/city-house/node_modules/@dcloudio/types/uni-app/uni.d.ts
10:58:27.785 36:5 '$once', which lacks return-type annotation, implicitly has an 'any' return type.
10:58:27.791     34 |      * 参考: [http://uniapp.dcloud.io/api/window/communication?id=once](http://uniapp.dcloud.io/api/window/communication?id=once)
10:58:27.805     35 |      */
10:58:27.818   > 36 |     $once(eventName?: string, callback?: () => void);
10:58:27.822        |     ^
10:58:27.838     37 |     /**
10:58:27.843     38 |      * 移除自定义事件监听器。如果没有指定事件名，则移除所有事件监听器。如果提供事件名，则移除该事件的所有监听器。如果提供了事件名和回调，则只移除这个回调的监听器。
10:58:27.874     39 |      *
10:58:27.894 ERROR in F:/linux/vscode/eq/city-house/node_modules/@dcloudio/types/uni-app/uni.d.ts
10:58:27.901 42:5 '$off', which lacks return-type annotation, implicitly has an 'any' return type.
10:58:27.914     40 |      * 参考: [http://uniapp.dcloud.io/api/window/communication?id=off](http://uniapp.dcloud.io/api/window/communication?id=off)
10:58:27.923     41 |      */
10:58:27.944   > 42 |     $off(eventName?: string | any [], callback?: () => void);
10:58:27.951        |     ^
10:58:27.968     43 |     /**
10:58:27.974     44 |      * 通过id 获取 subNVues 原生子窗体的实例
10:58:28.002     45 |      *
10:58:28.007 ERROR in F:/linux/vscode/eq/city-house/node_modules/@dcloudio/types/uni-app/uni.d.ts
10:58:28.023 942:5 'show', which lacks return-type annotation, implicitly has an 'any' return type.
10:58:28.031     940 |      * 显示原生子窗体
10:58:28.052     941 |      */
10:58:28.069   > 942 |     show(options?: 'slide-in-right' | 'slide-in-left' | 'slide-in-top' | 'slide-in-bottom' | 'fade-in' | 'zoom-out' | 'zoom-fade-out' | 'pop-in');
10:58:28.164         |     ^
10:58:28.184     943 |     /**
10:58:28.196     944 |      * 隐藏原生子窗体
10:58:28.277     945 |      */
10:58:28.282 ERROR in F:/linux/vscode/eq/city-house/node_modules/@dcloudio/types/uni-app/uni.d.ts
10:58:28.298 946:5 'hide', which lacks return-type annotation, implicitly has an 'any' return type.
10:58:28.303     944 |      * 隐藏原生子窗体
10:58:28.328     945 |      */
10:58:28.336   > 946 |     hide(options?: 'slide-out-right' | 'slide-out-left' | 'slide-out-top' | 'slide-out-bottom' | 'fade-out' | 'zoom-in' | 'zoom-fade-in' | 'pop-out');
10:58:28.359         |     ^
10:58:28.376     947 |     /**
10:58:28.382     948 |      * 设置原生子窗体的样式
10:58:28.407     949 |      */

**Comment by zhetengbiji** [comment]
更新 @dcloudio/types 即可
