### ISSUE TITLE
show-center-play-btn不能隐藏

### ISSUE THREAD

**Issue by CENcw** [dcloudio/uni-app#543]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
想自己自定义播放按钮，隐藏组件默认的中间的播放按钮，真机和本地浏览都不能隐藏
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
				<video id="myVideo" src="https://img.cdn.aliyun.dcloud.net.cn/guide/uniapp/%E7%AC%AC1%E8%AE%B2%EF%BC%88uni-app%E4%BA%A7%E5%93%81%E4%BB%8B%E7%BB%8D%EF%BC%89-%20DCloud%E5%AE%98%E6%96%B9%E8%A7%86%E9%A2%91%E6%95%99%E7%A8%8B@20181126.mp4"
				 @error="videoErrorCallback" :danmu-list="danmuList"  show-play-btn=false  show-center-play-btn=false  poster="https://img-cdn-qiniu.dcloud.net.cn/uniapp/doc/poster.png"></video>
**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by dcloudhdx** [comment]
show-play-btn="false" 是字符串 false
:show-play-btn="false" 是 Boolean false

<video :show-play-btn="false" :show-center-play-btn="false">
