### ISSUE TITLE
video组件在安卓可以正常监听touchstart、touchmove 和touchend事件，但是在ios端不可以

### ISSUE THREAD

**Issue by foxantony360** [dcloudio/uni-app#544]
**问题描述**
video组件在安卓可以正常监听touchstart、touchmove 和touchend事件，但是在ios端不可以

**复现步骤**
video组件在安卓可以正常监听touchstart、touchmove 和touchend事件，但是在ios端不可以，在ios端尝试通过给video覆盖一个cover-view，然后给cover-view绑定touchstart、touchmove 和touchend的事件后发现只有点击一下cover-view的那一刻同时触发一次touchstart和touchend事件，手指移动过程并没有touchmove事件的触发，手指停止移动时候也没有touchend事件的触发

**预期结果**
希望在ios像安卓那样，可以持续监测touchmove，并且是在手指停止移动时候才触发touchend，而不是点击那一刻同时触发touchstart和touchend事件

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统：所有ios版本
 - HBuilderX版本：最新版
 - uni-app版本 ：最新版本

**Comment by dcloudhdx** [comment]
HBuilderX 2.6.12+ alpha 版本已支持
