### ISSUE TITLE
HX编辑器，全局搜索无效（macOS系统）

### ISSUE THREAD

**Issue by XuHui19930327** [dcloudio/uni-app#547]
**问题描述**
例：在common/uni.css文件定义uni-media-list-body，界面不显示当前uni.css文件时，无法搜索到uni-media-list-body

**复现步骤**
[复现问题的步骤]
1.  创建common/uni.css，并定义uni-media-list-body
2. 切换到其他文件，例如：pages/indext.vue
3. 搜索uni-media-list-body

[或者可以直接贴源代码]

**预期结果**
能搜索到该项目所有包含uni-media-list-body的文件

**实际结果**
不能搜索到common/uni.css里，包含uni-media-list-body字段

**Comment by wanganxp** [comment]
搜索分文件搜索和多文件搜索，注意区分。如果使用单文件搜索，只搜当前高亮的文件。另，ide相关的同事不在github上，无法及时回复，有ide相关问题，建议在论坛报：https://ask.dcloud.net.cn/explore/
