### ISSUE TITLE
vue3项目如何转成uni-app ？

### ISSUE THREAD

**Issue by qq727127158** [dcloudio/uni-app#548]
**新功能描述**
简洁描述你希望补充完善的增强功能

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by wanganxp** [comment]
去掉dom相关的操作，路由配到pages.json里。标签改不改倒无所谓，继续写div也能用。

**Comment by hbcui1984** [comment]
Vue 3.0正式发布后，uni-app会同步做升级兼容处理，工作量不大，并且会尽可能保证向下兼容。

**Comment by zouhangwithsweet** [comment]
Vue3.0@beta 版本已经发布，官方对Vue3升级的进度可以透露一下吗~ 还有个问题就是Vue2.0的uni-app升级的话，breaking change 多吗？

**Comment by denvey** [comment]
请问现在支持vue3了吗

**Comment by uinio** [comment]
建议重构，vue3保留2的功能，但是vue3 主要为了新API 设计，2的功能也许在将来的版本移除。
