### ISSUE TITLE
uni-app必须使用云端打包吗？

### ISSUE THREAD

**Issue by brucehelen** [dcloudio/uni-app#55]
之前没用过dcloud的产品，但是了解过。最近在找vue编写app的框架，发现uni-app还不错。这个框架没开源吗？为啥只看到云端编译，核心的代码都放到了服务器吗？

**Comment by hbcui1984** [comment]
HBuilderX 1.0.0 版本发布，开放 uni-app支持原生sdk集成，离线打包，自由扩展原生能力 [参考](http://ask.dcloud.net.cn/docs/#//ask.dcloud.net.cn/article/104)

**Comment by EVINK** [comment]
uni-app 搞个cli更好呀

**Comment by hbcui1984** [comment]
> uni-app 搞个cli更好呀

npm run build:app-plus
