### ISSUE TITLE
uni.request的method不支持PATCH？

### ISSUE THREAD

**Issue by pcloth** [dcloudio/uni-app#550]
https://developer.mozilla.org/zh-CN/docs/Web/HTTP
一共有9个，少了这个PATCH呀。

**Comment by zhetengbiji** [comment]
请以文档（[request](https://uniapp.dcloud.io/api/request/request?id=request)）为准，运行环境不止web

**Comment by HADB** [comment]
为啥不支持 PATCH 方法，是有什么困难吗？

**Comment by eno-Zeng** [comment]
因为微信的 wx.request 没有支持 patch，真是垃圾

**Comment by pcloth** [comment]
其实就是懒得适配，其他api一大堆备注比如：app不兼容，仅兼容支付宝小程序，轮到[request](https://uniapp.dcloud.io/api/request/request?id=request)了就是因为不只是web，所以不提供了
