### ISSUE TITLE
markdown todo list 问题

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#552]
**问题描述**
markdown todo list 语法不应该是 `- [ ]` 与 `- [x]`吗？

而且在HX中使用 `[] [x]`，在预览中也不能显示成todo list。使用`- [ ]  -[x]`也不能正确显示。

![image](https://user-images.githubusercontent.com/7576559/61192799-aeb1f600-a6e9-11e9-87d6-0f5219bc985a.png)

且看github的todo list：

[ ] Hello it's uni-app
[x] Hello it's done

- [ ] Well, nice
- [x] Hi, good

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by wanganxp** [comment]
需求已知。不同平台的渲染器样式都不一样，发布后的效果也有差异。
对于hx而言，主要是在编辑器里可以方便的设任务列表，双击改变任务状态。那个右侧的预览只是一个大概效果，如果要发布的话，还得看计划发布的平台自身的支持情况。至于hx右侧的预览效果处理，有时间会优化，但不会是很高的优先级

**Comment by wakaryry** [comment]
task/todo list 语法，大多数 用的都是 `- [ ] ` 和 `- [x]` 形式。 而 `[ ]` 和 `[x]` 目前我没有碰到能过解析成功的。
我的意思是 应该推荐使用 `- [ ] ` 和 `- [x]`。

这个也不急的东西。本来用task也少。而且为了能够在其他的markdown编辑器里面成功预览，直接使用了`- [ ] ` 和 `- [x]`。

其实如果是自己来解析markdown的话，用什么 标记 都无所谓。只不过大家用的都是 别人的ide，我们不能修改它的 解析规则。

**Comment by wanganxp** [comment]
哦，明白你的意思了。我们优化下markdown的帮助文档，告诉大家如果发布的话，推荐加上行首的-
