### ISSUE TITLE
引用阿里巴巴iconfont图标部分失效

### ISSUE THREAD

**Issue by xgxchina** [dcloudio/uni-app#553]
**问题描述**
我使用阿里巴巴图标，在app和微信小程序都可以正常显示，但在字节跳动开发工具显示时只有一个正方形

**复现步骤**
[复现问题的步骤]
1.  在阿里巴巴官网选好图标添加到我的项目，然后点击生成在线链接，复制链接内容
2. 在项目的static目录下创建ico文件夹，在ico文件夹内创建iconfont.css文件，讲1的复制内容粘贴，并补上https前缀
3. 在阿里巴巴官网我的项目中找到要使用图标的uniconde码，复制到uniapp内，并用<text>标签包裹，标签上填写相应的样式类

[或者可以直接贴源代码]
**iconfont.css文件代码**：
@font-face {
  font-family: 'icon';  /* project id 1291269 */
  src: url('https://at.alicdn.com/t/font_1291269_7pxstwxgjhc.eot');
  src: url('https://at.alicdn.com/t/font_1291269_7pxstwxgjhc.eot?#iefix') format('embedded-opentype'),
  url('https://at.alicdn.com/t/font_1291269_7pxstwxgjhc.woff2') format('woff2'),
  url('https://at.alicdn.com/t/font_1291269_7pxstwxgjhc.woff') format('woff'),
  url('https://at.alicdn.com/t/font_1291269_7pxstwxgjhc.ttf') format('truetype'),
  url('https://at.alicdn.com/t/font_1291269_7pxstwxgjhc.svg#icon') format('svg');
}
.icon { 
  font-family:"icon" !important; 
  font-style:40upx; 
  -webkit-font-smoothing: antialiased; 
  -moz-osx-font-smoothing: grayscale; 
	display: flex;
	align-items: center;
	justify-content: center;
}
**main.js文件引入样式文件代码**： import './static/ico/iconfont.css'

**uniapp页面使用代码**：
<text class="icon">&#xe79e;</text>

**预期结果**
微信小程序、字节跳动小程序、百度小程序、支付宝小程序、android、ios、H5都可以显示字体图标

**实际结果**
微信小程序、支付宝小程序、android、ios、H5可以显示，字节跳动小程序、百度小程序不显示

**系统信息:**
 - 运行平台: 微信小程序、字节跳动小程序、百度小程序、支付宝小程序、android、ios
 - HBuilderX版本：2.0.1.20190614（macbook air）
 

**补充信息**
感觉是使用字体图标有些错误

**Comment by zhetengbiji** [comment]
在字节跳动小程序组件内引入字体会失效，解决方式：在App.vue内的style节点引入。
你可以测试一下原生字节跳动小程序是否存在此问题，如果存在可以同时反馈给字节跳动小程序官方。

**Comment by xgxchina** [comment]
微信小程序是编译后文件是<text class="icon">uniconde</text>,但是字节跳动多包了一层<span></span>标签，原生字节跳动小程序是支持iconfont的

**Comment by xgxchina** [comment]
> 在字节跳动小程序组件内引入字体会失效，解决方式：在App.vue内的style节点引入。
> 你可以测试一下原生字节跳动小程序是否存在此问题，如果存在可以同时反馈给字节跳动小程序官方。

微信小程序是编译后文件是uniconde,但是字节跳动多包了一层标签，原生字节跳动小程序是支持iconfont的
