### ISSUE TITLE
uni.scanCode(OBJECT)

### ISSUE THREAD

**Issue by liuyunzyj** [dcloudio/uni-app#554]
**新功能描述**
简洁描述你希望补充完善的增强功能
希望能使用前置摄像头扫码，供用户自定义切换前后摄像头扫码
**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by liuyunzyj** [comment]
这个问题官方能处理下麽？

**Comment by zhetengbiji** [comment]
如果需要的人多，可以考虑支持

**Comment by liuyunzyj** [comment]
app这块有业务是需要的啊

**Comment by Otto-J** [comment]
https://uniapp.dcloud.net.cn/api/system/barcode.html#scancode
