### ISSUE TITLE
2.1.0正式版编译失败

### ISSUE THREAD

**Issue by suchasmsc** [dcloudio/uni-app#555]
**问题描述**
2.0.1正式版可以正常编译的项目在2.1.0里头就不行了，α版本也是同样的错误
15:40:51.294 FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
15:40:51.295  1: node_module_register
15:40:51.303  2: v8::internal::Factory::NewFixedArray
15:40:51.304  3: v8::internal::HashTable<v8::internal::SeededNumberDictionary,v8::internal::SeededNumberDictionaryShape>::IsKey

**Comment by fxy060608** [comment]
环境变量增加一个 NODE_OPTIONS=--max_old_space_size=4096 试试
