### ISSUE TITLE
最新版hello-uniapp编译不过

### ISSUE THREAD

**Issue by menqi20** [dcloudio/uni-app#56]
错误信息:
14:00:09.289 文件查找失败：'E:/code/uin-app/uni-app/examples/hello-uniapp/platforms/app-plus/tabbar-nvue/tabbar-nvue.vue' at platforms\app-plus\tabbar-nvue\tabbar-nvue.js:3

**Comment by hbcui1984** [comment]
nvue 实际上weex引擎，依赖最新版本的HBuilderX内置基座，请升级HBuilderX到最新版验证问题。
