### ISSUE TITLE
uni-picker app样式修改

### ISSUE THREAD

**Issue by zhengybo** [dcloudio/uni-app#562]
**问题描述**
 picker 的 确认按钮样式无法修改

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
![image](https://user-images.githubusercontent.com/22511317/61505868-de773b80-aa12-11e9-9c5d-937fc3b31e11.png)
这里是h5的

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/22511317/61505898-f484fc00-aa12-11e9-9ef0-f5fd0a0776dc.png)
这里是app 的

**系统信息:**
 - 发行平台: [H5/台、5+ App ]
 - 操作系统 [win7 、Android 8.0]
 - HBuilderX版本 [2.1.1.20190716]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [荣耀v8]

**补充信息**
[可选]
app 节点 和h5节点不一致， 但在app全局样式里 已经改了。 疑似 app里面样式 无法修改。

**Comment by zhetengbiji** [comment]
每个平台的内部实现并不相同，你在特定平台发现的一些规律并不一定能套用到其他平台。

**Comment by zhengybo** [comment]
恩， 那app上能修改 ？，  没看到 官网例子 能改样式的， picker 按钮颜色 ，或者app是无法修改的？

**Comment by zhengybo** [comment]
恩， 那app上能修改 ？， 没看到 官网例子 能改样式的， picker 按钮颜色 ，或者app是无法修改的？

**Comment by zhetengbiji** [comment]
> 恩， 那app上能修改 ？， 没看到 官网例子 能改样式的， picker 按钮颜色 ，或者app是无法修改的？

并不能修改，H5平台也未开放样式修改方式，一旦框架调整你的方式可能失效，请以文档为准。

如果对picker组件有自定义需求可以参考插件市场里的第三方picker组件。

**Comment by fakerLinXiao** [comment]
@zhengybo 请问现在开放APP端的样式修改了吗？ 因为在使用这些组件的时候难免有一两个小地方的修改。
