### ISSUE TITLE
uni-app 页面跳转问题

### ISSUE THREAD

**Issue by zwpforstudy** [dcloudio/uni-app#563]
**问题描述**
使用「路由与页面跳转」里的接口的时候，发现在百度小程序和头条小程序里url的形式并不统一，百度的能跳，头条的跳不了

**预期结果**
百度小程序和头条小程序里能跳转页面

**实际结果**
当前页面：是pages/login/login
代码：![image](https://user-images.githubusercontent.com/16854093/61507049-d6b99600-aa16-11e9-90fa-e10c3858334a.png)
头条小程序里报错信息是：
![image](https://user-images.githubusercontent.com/16854093/61506664-6c542600-aa15-11e9-8400-a7557b78250d.png)
跳转地址是 this.from /pages/index/index
但是头条小程序自己加了当前页面的前半段pages/login/

**系统信息:**
 - 发行平台: 头条开发者工具
 - uni-app版本
![image](https://user-images.githubusercontent.com/16854093/61507001-9fe38000-aa16-11e9-998f-9f7f395c0190.png)
![image](https://user-images.githubusercontent.com/16854093/61507031-bd184e80-aa16-11e9-8be4-871a4f7d386e.png)

**补充信息**
想说文档能不能写的更清楚点呢，举例也不清晰，每次遇到问题看文档根本找不到答案，只能一步一步的试错
![image](https://user-images.githubusercontent.com/16854093/61507218-6fe8ac80-aa17-11e9-9245-941c0bd49bbd.png)
比如这里的举例test，那请问test是 对于小程序来说是/pages/xxx/xxx呢还是 直接xxx 就好

**Comment by fxy060608** [comment]
最好只是用绝对路径跳转，即/pages/xxx/xxx

**Comment by zwpforstudy** [comment]
@fxy060608 好的，谢谢
