### ISSUE TITLE
uni-app 在小程序中使用双层v-for 事件传参问题

### ISSUE THREAD

**Issue by kingport** [dcloudio/uni-app#564]
**问题描述**
双层v-for的时候在第二层循环中添加点击事件获取不到参数

**复现步骤**
[复现问题的步骤]

![image](https://user-images.githubusercontent.com/26566472/61602368-c3533880-ac6b-11e9-8689-8ab169851c34.png)

**预期结果**
希望得到当前二级Item，

**实际结果**
永远打印的是0 或者是父级第一个item

**系统信息:**
 - 发行平台: [如 微信小程序

**补充信息**
[可选]
刚开始我以为是默认事件的原因

**Comment by leyue** [comment]
同样的问题，网上一堆人提到双重循环的bug。解决了吗？？？ 没有任何回复直接就close这就是你们处理issue的方式吗。。。

**Comment by jaceechan** [comment]
相同问题，请问怎么解决？

**Comment by sanriqing** [comment]
附议，不解决吗。。。
