### ISSUE TITLE
全局水印

### ISSUE THREAD

**Issue by wangtaicheng** [dcloudio/uni-app#567]
**新功能描述**
为每个页面添加一些自动组件

**现状及问题**
目前app有个要添加水印的需求，已经再插件市场中找到了相应的插件，但是需要没有页面都要修改，没有方法可以添加一个全局的，不用每个页面都修改代码

**尝试方案**
App.vue 添加如下代码没有左右。
```
<template>
  <div >
    <xxx-comp></xxx-comp>
  </div>
</template>
```

**补充信息**
[其它你认为有参考价值的信息]

**Comment by zhetengbiji** [comment]
无此用法，由于各端限制，将来也不会支持
