### ISSUE TITLE
h5 以 router.mode 为 hash 打包时应允许 router.base 设置为相对路径

### ISSUE THREAD

**Issue by xlfsummer** [dcloudio/uni-app#571]
**新功能描述**
h5 以 router.mode 为 `"hash"` 时打包时应允许 router.base 设置为相对路径

**现状及问题**
需求里 router.base 是一个变量，我把 router.base 和 publicPath 都设置为相对路径 `./`，js, css 可以正常加载，但底部栏图标无法正常加载

**建议**
`node_modules\@dcloudio\webpack-uni-mp-loader` 中有如下处理
```javascript
  if (base.indexOf('/') !== 0) {
    base = '/' + base
  }
```
可以改成
```javascript
  let mode = h5.mode;

  if (base.indexOf('/') !== 0 && mode !== "hash") {
    base = '/' + base
  }
```
既然是 hash 的路由模式，router.base 允许相对路径，应该也不会影响其它资源的加载。

**Comment by smalike** [comment]
这种应该强烈支持一下，特别是在部署路径有随机 ID 到情况。

**Comment by dcloudhdx** [comment]
HBuilderX 2.6.8+ 已支持使用相对路径 `./` 部署
