### ISSUE TITLE
Typescript中App实例的onShow不允许带参数

### ISSUE THREAD

**Issue by ben-lau** [dcloudio/uni-app#573]
**问题描述**
Typescript项目中，mpType为app的vue实例，onShow的定义为不带参数的函数()=>void，查看了声明文件原因为 type Hooks = App.AppInstance & Page.PageInstance；
而在小程序中，App内的onShow是可以获取参数的，目的是在小程序进入后台，扫码后能在app识别，

**复现步骤**
[复现问题的步骤]
import Vue from 'vue';
export default Vue.extend({
  mpType: 'app',
  onLaunch() {
    console.log('App Launch');
  },
  onShow(params:any) { // 这里有问题
    console.log(params);
  },
  onHide() {
    console.log('App Hide');
  }
});

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]
![image](https://user-images.githubusercontent.com/16952163/61705980-8f663900-ad79-11e9-9683-8e189f05f8f2.png)

**系统信息:**
 @dcloudio/uni-app-plus: * => 0.0.248
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: * => 0.2.973
    @dcloudio/uni-h5: * => 0.7.3
    @dcloudio/uni-mp-alipay: * => 0.0.822
    @dcloudio/uni-mp-baidu: * => 0.0.852
    @dcloudio/uni-mp-qq: * => 0.0.106
    @dcloudio/uni-mp-toutiao: * => 0.0.346
    @dcloudio/uni-mp-weixin: * => 0.0.967
    @dcloudio/uni-template-compiler: * => 0.9.180
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 1.0.121
    @dcloudio/vue-cli-plugin-uni: latest => 0.9.497
    @dcloudio/vue-cli-plugin-uni-optimize: latest => 0.1.4
    @dcloudio/webpack-uni-mp-loader: * => 0.3.639
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: * => 0.2.854
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.9.2
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.9.0
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-service: ^3.9.0 => 3.9.3
    @vue/cli-shared-utils:  3.9.0
    @vue/component-compiler-utils:  2.6.0 (3.0.0)
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.1
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
params?:App.LaunchShowOption
