### ISSUE TITLE
使用函数式组件，提示错误：“Error in render: "TypeError: Cannot read property '_c' of undefined"”

### ISSUE THREAD

**Issue by CaptainLiao** [dcloudio/uni-app#575]
**问题描述**
在 uniapp 中，使用函数式组件，会报错：Error in render: "TypeError: Cannot read property '_c' of undefined"。

**复现步骤**
声明一个简单的函数式组件， 如下
````
<template functional>
<div>sss</div>
</template>
````

**预期结果**
组件正确被渲染出来。

**实际结果**
![image](https://user-images.githubusercontent.com/17636663/61759113-f592a080-adf9-11e9-8945-49b1d87f1f4b.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: win 10
System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
  Binaries:
    Node: 8.11.2 - E:\node-v8.11.2-win-x64\node.EXE
    Yarn: 1.6.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 5.6.0 - E:\node-v8.11.2-win-x64\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @dcloudio/uni-app-plus: * => 0.0.243
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: * => 0.2.962
    @dcloudio/uni-h5: * => 0.5.10
    @dcloudio/uni-mp-alipay: * => 0.0.817
    @dcloudio/uni-mp-baidu: * => 0.0.844
    @dcloudio/uni-mp-toutiao: * => 0.0.341
    @dcloudio/uni-mp-weixin: * => 0.0.966
    @dcloudio/uni-template-compiler: * => 0.9.179
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 1.0.101
    @dcloudio/vue-cli-plugin-uni: latest => 0.9.479
    @dcloudio/webpack-uni-mp-loader: * => 0.3.630
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: * => 0.2.845
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.8.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.8.0
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-plugin-eslint: ^3.8.0 => 3.8.0
    @vue/cli-service: ^3.6.0 => 3.8.3
    @vue/cli-shared-utils:  3.8.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    mpvue-wxparse:  0.6.5
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-router:  3.0.1
    vue-style-loader:  3.1.2 (3.1.2)
    vue-template-compiler: ^2.5.21 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
    weex-vue-loader: ^0.7.0 => 0.7.0

**Comment by dcloudhdx** [comment]
直接使用没有问题，请提供完整示例

**Comment by fxy060608** [comment]
暂不支持函数式组件

**Comment by nyrf** [comment]
@fxy060608 请问下函数式组件vue3后续还有计划支持么？很多时候模板还是不够灵活

**Comment by fxy060608** [comment]
> @fxy060608 请问下函数式组件vue3后续还有计划支持么？很多时候模板还是不够灵活

你说的是手写render函数吧，暂无计划支持

**Comment by nyrf** [comment]
> > @fxy060608 请问下函数式组件vue3后续还有计划支持么？很多时候模板还是不够灵活
> 
> 你说的是手写render函数吧，暂无计划支持

是的，了解。麻烦看下vue3下ref在onMounted时得不到值的问题谢谢。https://github.com/dcloudio/uni-app/issues/2461
