### ISSUE TITLE
增加在线playground, 方便预览组件

### ISSUE THREAD

**Issue by Onesimu** [dcloudio/uni-app#579]
**新功能描述**
简洁描述你希望补充完善的增强功能

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]
比如weex的playground
http://dotwe.org/vue/

**Comment by StrivingRabbit** [comment]
现文档中已有组件的效果展示
![Snipaste_2022-09-03_15-30-27](https://user-images.githubusercontent.com/33573212/188260821-4ee62731-04e2-4fa8-85ff-4ac71dcd22bf.jpg)
