### ISSUE TITLE
app转场黑屏

### ISSUE THREAD

**Issue by zhengybo** [dcloudio/uni-app#582]
**问题描述**
app+h5 当切换页面到深色背景的时候页面有黑屏或者白屏问题
android 不明显

**复现步骤**
navigateTo到背景色深的界面 或者 redirectTo

[或者可以直接贴源代码]

**预期结果**
不黑屏或者能把背景色变成转场页面的颜色

**实际结果**
存在黑屏及根节点page的背景色

**系统信息:**
 - 发行平台: [5+ App等]
 - 操作系统 [iOS Android ]
 - HBuilderX版本 [2.1.3.20190723]
 - uni-app版本 []
 - 设备信息 [荣耀v8 ios]

**补充信息**
由于渲染性能问题导致的，页面变化不及时，黑屏是根节点page的颜色，转场没渲染的时候显示的根节点的颜色。
有什么办法可以平滑转场或者可以 动态设置根节点颜色？

**Comment by zhetengbiji** [comment]
后续已改善，新页面可通过样式设置
```html
<style>
page{
background-color: #ffffff;
}
</style>
