### ISSUE TITLE
请教个问题. Storage与vue的Store都可以用来做存储。 可区别到底是什么呢？

### ISSUE THREAD

**Issue by netyilei** [dcloudio/uni-app#583]
如题。
我知道Storage不需要定义 直接可以随意存储。而vue的store需要提前定义。

但是说到底都是用来做存储的。 不晓得两者都存在的意义是什么，只用一样是不是会更统一呢？

请各位老鸟给讲解下两者在使用中真正的不同吧。 我以后还要对号入座不同需求不同存储用不同的

**Comment by zhetengbiji** [comment]
https://www.baidu.com/s?wd=Storage%E4%B8%8Evue%E7%9A%84Store%E9%83%BD%E5%8F%AF%E4%BB%A5%E7%94%A8%E6%9D%A5%E5%81%9A%E5%AD%98%E5%82%A8%E3%80%82+%E5%8F%AF%E5%8C%BA%E5%88%AB%E5%88%B0%E5%BA%95%E6%98%AF%E4%BB%80%E4%B9%88%E5%91%A2%EF%BC%9F&tn=84053098_3_dg&ie=utf-8
