### ISSUE TITLE
安卓 自定义模式下 onMessage问题

### ISSUE THREAD

**Issue by cookie-session** [dcloudio/uni-app#587]
**新功能描述**
简洁描述你希望补充完善的增强功能
希望能把安卓端WSS协议 OnMessage 功能优化一下，太致命了。
**现状及问题**
[当前现状及由此导致的不便]
目前安卓端WSS 协议下 OnMessage 收不到服务器返回的信息（其实socket是连接正常的，就是收不到服务器给的信息），导致只能使用WS协议，现在谁还用WS协议 如此的不安全
**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]
 目前未找到解决办法
**补充信息**
[其它你认为有参考价值的信息]

**Comment by cookie-session** [comment]
WSS证书来自阿里云

**Comment by zhetengbiji** [comment]
试试新版

**Comment by StrivingRabbit** [comment]
由于长时间未回复，此问题关闭，如果还有问题可以重开或者提新issue
