### ISSUE TITLE
vue.config.js自定义配置部分失效

### ISSUE THREAD

**Issue by fangdiao** [dcloudio/uni-app#588]
**新功能描述**
简洁描述你希望补充完善的增强功能
希望支持outputDir，publicPath等属性的自定义配置
**现状及问题**
[当前现状及由此导致的不便]
`const path = require('path');
module.exports = {
  outputDir: path.resolve(__dirname, './dist')
};`
outputDir修改不成功
**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by fxy060608** [comment]
已开放 vue.config.js https://uniapp.dcloud.io/collocation/vue-config
部分配置不支持，比如 outputDir，如果支持的话，会导致 HBuilderX 无法正确运行至各个平台
