### ISSUE TITLE
转成微信小程序全局组件没有写入app.json导致全局组件失效

### ISSUE THREAD

**Issue by xiaomengheiheihei** [dcloudio/uni-app#589]
**问题描述**
因为要根据公司模板开发，所以修改了@dcloudio/vue-cli-plugin-uni这个依赖，在build.js最后复制index.html为ejs文件，别的未做修改。然后我在转换成小程序之后全局组件没有写入app.json导致全局组件失效，h5端正常，

**复现步骤**
[复现问题的步骤]
修改了@dcloudio/vue-cli-plugin-uni--》commands --》 build.js
done(`Build complete. ${dirMsg}`)
// 如果是狮子座模板需要添加views下的index.ejs
 if (process.env.UNI_PLATFORM === 'h5' && getManifestJson().h5.isEjs) {
            console.log('编译成功，请等待生成狮子座渲染文件...')
            fs.emptyDir('./views');
            let html = fs.readFileSync('./public/index.html', 'utf-8')
            // 遍历静态文件插入ejs
            ergodicStatic('./public/static/js', html).then((res) => {
              fs.writeFile('./views/index.ejs', res, (err) => {
                if (err) throw err;
                console.log('狮子座渲染文件生成，可以部署啦！')
              })
            })
 }

**预期结果**
可以正常写入app.json

**实际结果**

未能正常写入app.json

**补充信息**
在执行updateUsingComponents方法时是拿到了全局组件信息的，但是在template-new.js中getGlobalUsingComponents方法获取的全局组件全为空，导致传入vueLoader的全局组件为空

**Comment by fxy060608** [comment]
最好不要直接修改build.js，从你贴的代码看，可以直接写个脚本修改编译后的结果就行了，改了之后升级也麻烦，从贴的代码来看，应该不影响全局组件引入的逻辑，你可以还原下修改的内容，确认下是不是因为自己修改导致的
