### ISSUE TITLE
是否可以在linux系统上通过命令行发布打包APP？

### ISSUE THREAD

**Issue by HanZhaoYoung** [dcloudio/uni-app#590]
**问题描述**
是否可以在linux系统上通过命令行发布打包APP？

**复现步骤**
是否可以在linux系统上通过命令行发布打包APP？

**预期结果**
能在linux系统上通过命令行发布打包APP

**实际结果**
在官网暂未找到文档

**系统信息:**
 - 发行平台: 小程序、H5平台、App
 - 操作系统: Linux
 - HBuilderX版本 latest
 - uni-app版本 latest

**Comment by hbcui1984** [comment]
通过离线打包，自己封装命令行的方式是可以的
