### ISSUE TITLE
只生成app.js和chunk-vendors.js文件

### ISSUE THREAD

**Issue by xiaomengheiheihei** [dcloudio/uni-app#591]
**新功能描述**
配置可以更灵活一些，我的需求是不需要每个页面都导出一个脚本文件，只需要有入口脚本和chunk-vendors就可以了，不需要页面加载时动态脚在js文件，目前自己处理这块，但是还是会自动加载脚本，导致打开页面时就会有一个404请求

**现状及问题**
因为部署平台的限制，每次打开一个新页面时都会有一个脚本加载404的问题

**尝试方案**
用脚本动态修改了index.html文件，把所有脚本一次性添加了

**补充信息**
[其它你认为有参考价值的信息]

**Comment by fxy060608** [comment]
目前使用 cli 创建的工程可以自行定制
在 babel.config.js 中增加以下代码（自行安装 babel-plugin-remove-webpack 依赖）

```javascript
const plugins = []

if (process.env.UNI_PLATFORM === 'h5') {//仅 h5 下不生成
    plugins.push('dynamic-import-node')
    plugins.push('remove-webpack')
}
```
