### ISSUE TITLE
uni-app css样式中使用深度作用选择器 app端没有生效

### ISSUE THREAD

**Issue by lanfanxiou** [dcloudio/uni-app#593]
uni-app css样式中使用深度作用选择器 app端没有生效
`<style lang="scss" scoped>
	#scroll{
		/deep/ .img-lazyLoad image{
			width: 78upx;
			height: 290upx;
		}
	}
</style>
or
<style scoped>
	#scroll >>> .img-lazyLoad image{
	  width: 78upx;
	  height: 290upx;
	}
</style>`

**Comment by Nick-QI** [comment]
[https://developers.google.com/web/updates/2017/10/remove-shadow-piercing?hl=zh-cn](url)
shadow dom 的 /deep/ 已经被取消了
