### ISSUE TITLE
可以提供针对视觉障碍用户的方案吗，开发出来的产品若是对视觉障碍的用户有什么好的建议或方案可参考。

### ISSUE THREAD

**Issue by istarvip** [dcloudio/uni-app#594]
**新功能描述**
简洁描述你希望补充完善的增强功能

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by zhetengbiji** [comment]
目标平台是小程序还是App或者H5？

**Comment by wanganxp** [comment]
微信小程序和H5都自带视觉障碍支持，可以在uni-app里使用。其他端不支持

**Comment by istarvip** [comment]
小程序和H5都是自动添加WAI-ARIA 规范吗，还是手动在标签中添加。

**Comment by istarvip** [comment]
> 目标平台是小程序还是App或者H5？

 小程序和H5都是自动添加WAI-ARIA 规范吗，还是手动在标签中添加。

**Comment by istarvip** [comment]
> 微信小程序和H5都自带视觉障碍支持，可以在uni-app里使用。其他端不支持

 小程序和H5都是自动添加WAI-ARIA 规范吗，还是手动在标签中添加。

**Comment by zhetengbiji** [comment]
> > 微信小程序和H5都自带视觉障碍支持，可以在uni-app里使用。其他端不支持
> 
> 小程序和H5都是自动添加WAI-ARIA 规范吗，还是手动在标签中添加。

目前H5需要手动在标签内添加相关属性
