### ISSUE TITLE
uniapp如何全局换肤？

### ISSUE THREAD

**Issue by zhengyanghuaer** [dcloudio/uni-app#596]

**Comment by bxpxqxd** [comment]
写好几个皮肤，切换根元素的class，多个页面可使用vuex来同步状态。

**Comment by hbcui1984** [comment]
是要上线后动态换肤？

**Comment by zhengyanghuaer** [comment]
是滴是滴




------------------ 原始邮件 ------------------
发件人: "崔红保"<notifications@github.com>;
发送时间: 2019年8月7日(星期三) 晚上7:21
收件人: "dcloudio/uni-app"<uni-app@noreply.github.com>;
抄送: "Sight"<923987364@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [dcloudio/uni-app] uniapp如何全局换肤？ (#596)




是要上线后动态换肤？

**Comment by zhoubopro** [comment]
> 写好几个皮肤，切换根元素的class，多个页面可使用vuex来同步状态。

uniapp5+如何切换根class元素

**Comment by bxpxqxd** [comment]
> > 写好几个皮肤，切换根元素的class，多个页面可使用vuex来同步状态。
> 
> uniapp5+如何切换根class元素

跟元素就是template节点下第一个元素

**Comment by zhoubopro** [comment]
> > > 写好几个皮肤，切换根元素的class，多个页面可使用vuex来同步状态。
> > 
> > 
> > uniapp5+如何切换根class元素
> 
> 跟元素就是template节点下第一个元素

我说的根是只<html>或者<body>,
<template>下面那个只是当前pages的页面，跳转的时候<template>下面那个根就变了， 起不到全局换肤的作用。

**Comment by bxpxqxd** [comment]
> > > > 写好几个皮肤，切换根元素的class，多个页面可使用vuex来同步状态。
> > > 
> > > 
> > > uniapp5+如何切换根class元素
> > 
> > 
> > 跟元素就是template节点下第一个元素
> 
> 我说的根是指html或者body,
> template下面那个只是当前pages的页面，跳转的时候template下面那个根就变了， 起不到全局换肤的作用。

不不，我原话里指就是template节点下第一个元素
