### ISSUE TITLE
求支持 飞书、 钉钉 小程序

### ISSUE THREAD

**Issue by hetz** [dcloudio/uni-app#598]
**新功能描述**
目前不支持 飞书、钉钉小程序

**现状及问题**
跨平台希望支持更多场景

**尝试方案**
未找到

**补充信息**
[其它你认为有参考价值的信息]

**Comment by wanganxp** [comment]
不了解飞书，不过下版会开放自定义条件编译平台。

**Comment by hetz** [comment]
> 不了解飞书，不过下版会开放自定义条件编译平台。

这里的 自定义条件编译平台，说是有可能可以 基于 词法分析树写一个自己编译目标的实现吗？

**Comment by hbcui1984** [comment]
参考：https://uniapp.dcloud.io/collocation/package
