### ISSUE TITLE
uniapp $getAppMap()获取原生地图没有方法

### ISSUE THREAD

**Issue by guowenxi** [dcloudio/uni-app#600]
在uniapp中使用 
`uni.createMapContext('maps',this).$getAppMap()`
这个方法后 能获取当前<map>的对象,
`uni.createMapContext('maps',this).$getAppMap().calculateDistance`
当调用5+app里 map 的方法时候显示为 undefined
onstatuschanged 方法可以找到
onclick  也为 undefined

**Comment by Wangyaqi** [comment]
没能复现你的问题，我能看一下你的代码吗
$getAppMap() 注意事项：
- 在页面中，必须在 onReady 中调用。
- 在组件中，必须在 mounted 中调用。

**Comment by makan666** [comment]
TypeError: uni.createMapContext(...).$getAppMap is not a function
