### ISSUE TITLE
uni-app App端不支持引用本地3MB大小的字体文件么？

### ISSUE THREAD

**Issue by bigzhu0608** [dcloudio/uni-app#601]
**问题描述**
测试发现，App端不支持引用本地字体文件，字体文件大小（3.1MB）

**复现步骤**
```
<style>
/*每个页面公共css */
page {
  height: 100%;
}
/* #ifdef APP-PLUS || H5 */
@font-face {
  font-family: "FZSSJW";
  src: url("~@/static/FZSSJW.TTF");
}
/* #endif */
</style>
```

**预期结果**
能够打包本地static文件夹中的字体，加快加载速度。

**实际结果**
打包后没有效果，引用没有生效

**系统信息:**
 - 发行平台: 5+ App等
 - HBuilderX版本 最新版本

**Comment by zhetengbiji** [comment]
参考示例：https://ext.dcloud.net.cn/plugin?id=954
