### ISSUE TITLE
uniapp不支持小程序插件开发，准备弃坑，大佬uniapp如何一键转小程序？

### ISSUE THREAD

**Issue by einsqing** [dcloudio/uni-app#602]
uniapp不支持小程序插件开发，准备弃坑，大佬uniapp如何一键转小程序？

**Comment by wanganxp** [comment]
如果你指的是uni-app里引用微信小程序插件，那是支持的，根目录下可以放ext.json。
如果你是开发一个微信小程序插件，没有仔细研究过，不过似乎意义不大，微信小程序的插件只有微信能用，不跨端。
注意插件不是组件，不要混淆概念。
