### ISSUE TITLE
uni.authorize调不通是怎么回事

### ISSUE THREAD

**Issue by mrsevent** [dcloudio/uni-app#605]
无法调用，显示没有这个函数

**补充信息**
[其它你认为有参考价值的信息]

**Comment by hbcui1984** [comment]
请按照上报Bug模板，提供详细信息

**Comment by Wangyaqi** [comment]
长时间未回复暂时关闭

**Comment by ilick** [comment]
onShow(){
			uni.authorize({
			    scope: 'scope.record',
			    success() {
			        
			    },
				
			})
		},

**Comment by ilick** [comment]
报错： TypeError: uni.authorize is not a function. (In 'uni.authorize({ scope: 'scope.record', success: function success() {} })', 'uni.authorize' is undefined)

**Comment by Wangyaqi** [comment]
> 报错： TypeError: uni.authorize is not a function. (In 'uni.authorize({ scope: 'scope.record', success: function success() {} })', 'uni.authorize' is undefined)

你在哪端用的

**Comment by ilick** [comment]
app端&nbsp;
&nbsp;

你说&nbsp; 我听


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "王亚琪"<notifications@github.com&gt;; 
发送时间: 2020年2月24日(星期一) 中午1:32
收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 
抄送: "澈"<1029933097@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [dcloudio/uni-app] uni.authorize调不通是怎么回事 (#605)



 
报错： TypeError: uni.authorize is not a function. (In 'uni.authorize({ scope: 'scope.record', success: function success() {} })', 'uni.authorize' is undefined)
  
你在哪端用的

**Comment by Wangyaqi** [comment]
app端不支持，也不需要这个

**Comment by ilick** [comment]
那怎么在录音之前打开麦克风权限？
&nbsp;

你说&nbsp; 我听


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "王亚琪"<notifications@github.com&gt;; 
发送时间: 2020年2月24日(星期一) 中午1:38
收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 
抄送: "澈"<1029933097@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [dcloudio/uni-app] uni.authorize调不通是怎么回事 (#605)




app端不支持，也不需要这个

**Comment by Wangyaqi** [comment]
App端权限需要提前在manifest里配置


| |
我
|
|
wangyaqi988@163.com
|
签名由网易邮箱大师定制
在2020年2月24日 13:39，ilick<notifications@github.com> 写道：
那怎么在录音之前打开麦克风权限？
&nbsp;

你说&nbsp; 我听


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "王亚琪"<notifications@github.com&gt;;
发送时间: 2020年2月24日(星期一) 中午1:38
收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&gt;;
抄送: "澈"<1029933097@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;;
主题: Re: [dcloudio/uni-app] uni.authorize调不通是怎么回事 (#605)




app端不支持，也不需要这个

**Comment by ilick** [comment]
已经勾选了，但是进入app没有提示权限授权的弹窗&nbsp;
&nbsp;

你说&nbsp; 我听


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "王亚琪"<notifications@github.com&gt;; 
发送时间: 2020年2月24日(星期一) 中午1:40
收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 
抄送: "澈"<1029933097@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [dcloudio/uni-app] uni.authorize调不通是怎么回事 (#605)



App端权限需要提前在manifest里配置
 
 
 | |
 我
 |
 |
 wangyaqi988@163.com
 |
 签名由网易邮箱大师定制
 在2020年2月24日 13:39，ilick<notifications@github.com&gt; 写道：
 那怎么在录音之前打开麦克风权限？
 &amp;nbsp;
 
 你说&amp;nbsp; 我听
 
 
 &amp;nbsp;
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------
 发件人: "王亚琪"<notifications@github.com&amp;gt;;
 发送时间: 2020年2月24日(星期一) 中午1:38
 收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&amp;gt;;
 抄送: "澈"<1029933097@qq.com&amp;gt;; "Comment"<comment@noreply.github.com&amp;gt;;
 主题: Re: [dcloudio/uni-app] uni.authorize调不通是怎么回事 (#605)
 
 
 
 
 app端不支持，也不需要这个

**Comment by Wangyaqi** [comment]
重新开贴传一下你的项目，做一下详细描述
