### ISSUE TITLE
Android平台在onshow方法里调用setScreenBrightness接口程序卡死

### ISSUE THREAD

**Issue by phyamor** [dcloudio/uni-app#606]
**问题描述**
Android平台APP在onshow方法里调用setScreenBrightness接口程序卡死
只在Android平台APP发现这个问题。IOS的APP没有问题

**复现步骤**
1.在onShow里调用setScreenBrightness设置屏幕亮度为最大值1
2. 查看Log，这两行log就会疯狂的循环打印
App Hide at App.vue:10
App Show at App.vue:7
3. 看起来是只要在onShow里调用setScreenBrightness方法，会触发应用onShow方法执行，从而造成了死循环。但是由于业务需求，又必须在每次该界面显示的时候都需要将屏幕亮度设置为最大。

**预期结果**
希望调用setScreenBrightness不会触发onShow方法

**实际结果**
调用setScreenBrightness会触发onShow方法

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 Android 6.0
 - HBuilderX版本  2.1.3.20190723
 - uni-app版本 
 - 设备信息 LenovoTB-7703X

**Comment by Wangyaqi** [comment]
在 Android 6.0 上确实发现了这个问题，我们会尽快修复，感谢反馈

**Comment by Wangyaqi** [comment]
如果遇到需要申请权限的操作，请尽量放在onReady执行，不要在onShow里面执行
