### ISSUE TITLE
picker组件的range中的数组渲染问题

### ISSUE THREAD

**Issue by ly15927086342** [dcloudio/uni-app#609]
picker组件的range中的数组team是在created事件中通过云函数访问服务器获取得到的，打印出已获取。但是打开picker没有显示range的team。

代码如下：

```
<picker class="picker" mode="selector" range-key="name" @change="bindPickerChange" :value="selectTeamName" :range="teams">
<view class="title-bar">
<text>现役球员</text>
<text>{{selectPlayer.name}}</text>
</view>
</picker>
```

```
export default{
data(){
return{
teams:[]
}
},
created() {
			uni.showLoading();
			let that = this;
			wx.cloud.callFunction({
				name: 'getAll',
				data: {
					tbname: 'nbateam',
					rule: null,
					value: null
				},
			}).then(res => {
				console.log(res.result)
				res.result.data.forEach(item => {
					that.teams.push({
						name: item.name,
						url: item.img
					})
				})
				uni.hideLoading();
			}).catch(err => {
				uni.hideLoading();
				console.error();
			})
		},
...
}
```

请问是为什么？

**Comment by Wangyaqi** [comment]
把你javascript代码里面的bindPickerChange，selectTeamName那块贴上来

**Comment by ly15927086342** [comment]
> 把你javascript代码里面的bindPickerChange，selectTeamName那块贴上来

`data(){
return{
...
selectTeamName: 0,
...
}
},
methods:{
bindPickerChange(e) {
	this.selectTeamName = e.target.value;//传进index
}
}
`

**Comment by Wangyaqi** [comment]
还是没能复现出来你的问题
`
<template>
	<view class="content">
		<picker class="picker" mode="selector" range-key="name" @change="bindPickerChange" :value="selectTeamName" :range="teams">
			<view class="title-bar">
				<text>现役球员</text>
				<text>{{selectPlayer.name}}</text>
			</view>
		</picker>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				teams: [],
				selectTeamName: 0
			}
		},
		computed: {
			selectPlayer() {
				return this.teams[this.selectTeamName]
			}
		},
		created() {
			uni.showLoading();
			let that = this;
			setTimeout(function() {
				let res = {
					result: {
						data: [{
							name: "姓名1",
							img: "https://img-cdn-qiniu.dcloud.net.cn/uniapp/doc/uniapp4@2x.png"
						}, {
							name: "姓名2",
							img: "https://img-cdn-qiniu.dcloud.net.cn/uniapp/doc/uniapp4@2x.png"
						}, {
							name: "姓名3",
							img: "https://img-cdn-qiniu.dcloud.net.cn/uniapp/doc/uniapp4@2x.png"
						}, {
							name: "姓名4",
							img: "https://img-cdn-qiniu.dcloud.net.cn/uniapp/doc/uniapp4@2x.png"
						}, {
							name: "姓名5",
							img: "https://img-cdn-qiniu.dcloud.net.cn/uniapp/doc/uniapp4@2x.png"
						}]
					}
				};
				res.result.data.forEach(item => {
					that.teams.push({
						name: item.name,
						url: item.img
					})
				});
				uni.hideLoading();
			}, 1000);
		},
		methods: {
			bindPickerChange(e) {
				this.selectTeamName = e.target.value;
			}
		}
	}
</script>

<style>
</style>

`
你试试新建一个项目跑这个也有问题吗，会不会是返回的res.result的格式不太对

**Comment by ly15927086342** [comment]
> 还是没能复现出来你的问题
> 
> ```
> <template>
> 	<view class="content">
> 		<picker class="picker" mode="selector" range-key="name" @change="bindPickerChange" :value="selectTeamName" :range="teams">
> 			<view class="title-bar">
> 				<text>现役球员</text>
> 				<text>{{selectPlayer.name}}</text>
> 			</view>
> 		</picker>
> 	</view>
> </template>
> 
> <script>
> 	export default {
> 		data() {
> 			return {
> 				teams: [],
> 				selectTeamName: 0
> 			}
> 		},
> 		computed: {
> 			selectPlayer() {
> 				return this.teams[this.selectTeamName]
> 			}
> 		},
> 		created() {
> 			uni.showLoading();
> 			let that = this;
> 			setTimeout(function() {
> 				let res = {
> 					result: {
> 						data: [{
> 							name: "姓名1",
> 							img: "https://img-cdn-qiniu.dcloud.net.cn/uniapp/doc/uniapp4@2x.png"
> 						}, {
> 							name: "姓名2",
> 							img: "https://img-cdn-qiniu.dcloud.net.cn/uniapp/doc/uniapp4@2x.png"
> 						}, {
> 							name: "姓名3",
> 							img: "https://img-cdn-qiniu.dcloud.net.cn/uniapp/doc/uniapp4@2x.png"
> 						}, {
> 							name: "姓名4",
> 							img: "https://img-cdn-qiniu.dcloud.net.cn/uniapp/doc/uniapp4@2x.png"
> 						}, {
> 							name: "姓名5",
> 							img: "https://img-cdn-qiniu.dcloud.net.cn/uniapp/doc/uniapp4@2x.png"
> 						}]
> 					}
> 				};
> 				res.result.data.forEach(item => {
> 					that.teams.push({
> 						name: item.name,
> 						url: item.img
> 					})
> 				});
> 				uni.hideLoading();
> 			}, 1000);
> 		},
> 		methods: {
> 			bindPickerChange(e) {
> 				this.selectTeamName = e.target.value;
> 			}
> 		}
> 	}
> </script>
> 
> <style>
> </style>
> ```
> 
> 你试试新建一个项目跑这个也有问题吗，会不会是返回的res.result的格式不太对

我是teams绑了两个picker，然后第二个picker会有这问题，是不是不能绑两个？

**Comment by Wangyaqi** [comment]
两个picker也不会有问题，要不你发一下你这个完整的代码吧，发到我邮箱也可以 wangyaqi@dcloud.io

**Comment by ly15927086342** [comment]
> 两个picker也不会有问题，要不你发一下你这个完整的代码吧，发到我邮箱也可以 [wangyaqi@dcloud.io](mailto:wangyaqi@dcloud.io)

我又试了下，这回貌似可以了，谢谢！
