### ISSUE TITLE
uni-app什么时候能支持快应用

### ISSUE THREAD

**Issue by lingyusu** [dcloudio/uni-app#61]
如题

**Comment by nkoo21** [comment]
快应用还没有计划支持

**Comment by 350050183** [comment]
这么久了，快应用还没支持到位吗？快应用的需求比什么百度、头条、支付宝应该优先安排吧？快应用直接在各品牌手机市场就有入口了，那个才是流量。

**Comment by chenzefeng09** [comment]
期待直出快应用代码

**Comment by 350050183** [comment]
https://cmljs.org/#/ 和 https://taro.aotu.io/ 都已经支持了，uniapp明显落后于人了

**Comment by dcloudhdx** [comment]
近期会支持

**Comment by 350050183** [comment]
> 近期会支持

请问有时间表吗？

**Comment by enjoyWeb** [comment]
快应用还没支持麽(⊙o⊙)…

**Comment by dcloudhdx** [comment]
HBuilderX 2.7.12+ 已支持 https://uniapp.dcloud.io/quickstart?id=quickapp-webview
