### ISSUE TITLE
Vue 更新数据时 样式不能及时更新

### ISSUE THREAD

**Issue by loewe0202** [dcloudio/uni-app#614]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
```code

<template>
  <view class="content">
    <button v-if="skuInfo.listSellMaps">当前数组长度：{{skuInfo.listSellMaps.length}}</button>
    <!-- 产品参数滑块 -->
    <scroll-view class="goods-detail-parameter" scroll-x="true" v-if="skuInfo.listSellMaps">
      <view class="weui-row-list" :class="{'weui-flex-center': skuInfo.listSellMaps.length < 5 }">
        <view :id="index" class="weui-col goods-detail-parameter-item" v-for="(item, index) in skuInfo.listSellMaps" :key="index">
          <img mode="aspectFit" lazy-load :src="item.icon" show-menu-by-longpress />
          <view class="goods-detail-parameter-title">{{item.title}}</view>
          <view class="goods-detail-parameter-subtitle">{{item.subTitle}}</view>
        </view>
      </view>
    </scroll-view>
    <button @click="changeData">修改数据</button>
  </view>
</template>
<script>
export default {
  data() {
    return {
      skuInfo: {
        listSellMaps: []
      }
    }
  },
  onLoad() {
    this.changeData();
  },
  methods: {
    changeData() {
      let temp = {
          subTitle: "拍照清晰",
          icon: "https://dsfs.oppo.com/product/2019/K3/images/parameter/app-7-fdebcf8aec3092cd11d288190af4c643.png",
          title: "像素高"
        },
        randomNum = this.randomFn(3, 8),
        tempObject = {
          listSellMaps: []
        }
      for (let i = 0; i < randomNum; i++) {
        temp.id = i;
        tempObject.listSellMaps.push(temp);
      }
      this.skuInfo = Object.assign({}, this.skuInfo, tempObject);
    },
    randomFn(min, max) {
      var random = max - min + 1;
      return Math.floor(Math.random() * random + min);
    }
  }
}
</script>
<style>
.goods-detail-parameter {
  font-size: 11px;
  line-height: 1;
  color: #333;
  white-space: nowrap;
}

.weui-row-list {
  display: flex;
  flex-wrap: nowrap;
}

.weui-flex-center {
  align-items: center;
  justify-content: center;
}

.weui-col {
  flex: 0 0 auto;
}

.goods-detail-parameter-item {
  display: inline-block;
  position: relative;
  padding: 26rpx 10rpx 0;
  height: 164rpx;
  width: 166rpx;
  text-align: center;
}

.goods-detail-parameter-item image {
  width: 50rpx;
  height: 50rpx;
  display: block;
  margin: auto;
}

.goods-detail-parameter-title {
  width: auto;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  word-wrap: normal;
  margin: 8rpx 0 10rpx;
}

.goods-detail-parameter-subtitle {
  width: auto;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  word-wrap: normal;
  color: #666;
}

button {
  margin: 15px;
}
</style>

```
**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
更新数据后 样式能根据数组 length 动态修改样式

**实际结果**
[这里请贴上你的报错截图或文字]
数据变更一次之后样式不再变更

**系统信息:**
 - 发行平台: [微信小程序]
 - 操作系统 [微信开发者工具]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]

System:
    OS: macOS High Sierra 10.13.6
    CPU: (8) x64 Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz
  Binaries:
    Node: 10.15.3 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.10.2 - /usr/local/bin/npm
  Browsers:
    Chrome: 75.0.3770.142
    Firefox: 66.0.5
    Safari: 11.1.2
  npmPackages:
    @dcloudio/uni-app-plus: * => 0.0.248
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: * => 0.2.976
    @dcloudio/uni-h5: * => 0.7.3
    @dcloudio/uni-mp-alipay: * => 0.0.822
    @dcloudio/uni-mp-baidu: * => 0.0.852
    @dcloudio/uni-mp-qq: * => 0.0.106
    @dcloudio/uni-mp-toutiao: * => 0.0.346
    @dcloudio/uni-mp-weixin: * => 0.0.967
    @dcloudio/uni-template-compiler: * => 0.9.180
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 1.0.125
    @dcloudio/vue-cli-plugin-uni: latest => 0.9.503
    @dcloudio/vue-cli-plugin-uni-optimize: latest => 0.1.5
    @dcloudio/webpack-uni-mp-loader: * => 0.3.639
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: * => 0.2.858
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.9.2
    @vue/babel-preset-jsx:  1.1.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.9.0
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-service: ^3.9.0 => 3.9.3
    @vue/cli-shared-utils:  3.9.0
    @vue/component-compiler-utils:  2.6.0 (3.0.0)
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.1
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: 3.7.0

 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

目测应该是这里有编译问题skuInfo.listSellMaps.length

**Comment by fxy060608** [comment]
目前可以将跟数组 length 相关的模板写法，换成计算属性解决该问题
```html
<view class="weui-row-list" :class="clz">...</view>
```

```javascript
computed: {
            clz() {
                return this.skuInfo.listSellMaps.length < 5 ? 'weui-flex-center' : ''
            }
        },
```
