### ISSUE TITLE
how to use npm script to run project in real machine?

### ISSUE THREAD

**Issue by webxmsj** [dcloudio/uni-app#616]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
如何使用npm 运行 app-plus  在真机设备中， 目前是提示到hbuilderx中运行
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
使用 `npm run dev:app` 能将项目以app方式运行在真机设备中
**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by webxmsj** [comment]
> **问题描述**
> [问题描述：尽可能简洁清晰地把问题描述清楚]
> 如何使用npm 运行 app-plus 在真机设备中， 目前是提示到hbuilderx中运行
> **复现步骤**
> [复现问题的步骤]
> 
> 1. 启动 '...'
> 2. 点击  '....'
> 3. 查看
> 
> [或者可以直接贴源代码]
> 
> **预期结果**
> [使用简洁清晰的语言描述你希望生效的预期结果]
> 使用 `npm run dev:app` 能将项目以app方式运行在真机设备中
> **实际结果**
> [这里请贴上你的报错截图或文字]
> 
> **系统信息:**
> 
> * 发行平台: [如 微信小程序、H5平台、5+ App等]
> * 操作系统 [如 iOS 12.1.2、Android 7.0]
> * HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
> * uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
> * 设备信息 [如 iPhone8 Plus]
> 
> **补充信息**
> [可选]
> [根据你的分析，出现这个问题的原因可能在哪里？]

![image](https://user-images.githubusercontent.com/40289489/62405061-9ccac100-b5cc-11e9-9d17-5fda97a9d503.png)

**Comment by fxy060608** [comment]
cli 项目运行发布 app 需要使用 HBuilderX http://www.dcloud.io/hbuilderx.html
下载安装后，将 cli 工程拖入 HBuilderX，点击运行至手机或模拟器即可

**Comment by webxmsj** [comment]
> cli 项目运行发布 app 需要使用 HBuilderX http://www.dcloud.io/hbuilderx.html
> 下载安装后，将 cli 工程拖入 HBuilderX，点击运行至手机或模拟器即可

不想用 hbuilderx(不太喜欢)
