### ISSUE TITLE
H5环境下, uni.relaunch 到首页, 底部 tabbar 无法正常展示选择

### ISSUE THREAD

**Issue by Nick-QI** [dcloudio/uni-app#617]
H5 环境下
路由: 
<img width="638" alt="WX20190803-150408@2x" src="https://user-images.githubusercontent.com/29225479/62408749-247df300-b600-11e9-8405-427fc3574567.png">

路由跳转:
<img width="807" alt="WX20190803-150627@2x" src="https://user-images.githubusercontent.com/29225479/62408766-4f684700-b600-11e9-8990-24dea4a26e8b.png">

H5 url: 直接重定向为首页,  展示为 origin + '/' , 而非 orgin + '/pages/index/index'

**Comment by fxy060608** [comment]
框架会自动识别，/和/pages/index/index 都会被认为是首页
如：https://uniapp.dcloud.io/h5/ 示例里边”接口->界面->页面跳转->关闭所有页面，打开首页“，tabBar选中的还是首页

**Comment by Nick-QI** [comment]
> 框架会自动识别，/和/pages/index/index 都会被认为是首页
> 如：https://uniapp.dcloud.io/h5/ 示例里边”接口->界面->页面跳转->关闭所有页面，打开首页“，tabBar选中的还是首页

可我这边通过 relaunch  到首页 tabbar 还是无法选中
<img width="683" alt="WX20190803-154906@2x" src="https://user-images.githubusercontent.com/29225479/62409191-3f536600-b606-11e9-8760-fe50c44041bd.png">

**Comment by fxy060608** [comment]
我这里无法访问你的网站，你可以升级最新 HBuilderX 或 cli 再验证下，如果还有问题，你可以弄一个简单的可验证该问题的工程到 http://ask.dcloud.net.cn/发一下，然后贴一下地址，我看看怎么回事
