### ISSUE TITLE
text组件的space不生效

### ISSUE THREAD

**Issue by yuweiping** [dcloudio/uni-app#618]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
text组件的space参数不生效，原因是匹配空格的正则写的不正确。源码里htmlString = htmlString.replace(/ /g, SPACE_UNICODE[this.space])应该是htmlString = htmlString.replace(/ \s/g, SPACE_UNICODE[this.space])

**Comment by fxy060608** [comment]
text 组件的 space 规范是指的空格
你说的 \s 正则，包括空格、制表符、换页符和换行符，与规范不匹配。
