### ISSUE TITLE
app部分类型静态资源没有本地打包

### ISSUE THREAD

**Issue by magicwing** [dcloudio/uni-app#619]
**问题描述**
目录 static/app-plus 下存放 xxx.json 然后 通过HBuilderX的本地打包APP资源，
结果 
unpackage\dist\build\.tmp\app-plus\static\app-plus 存在 xxx.json
unpackage\dist\build\app-plus 不存在 xxx.json
unpackage\resources\%appid%\www\static\app-plus 不存在 xxx.json

**预期结果**
后面2个路径应该也存在 xxx.json 资源

**系统信息:**
 - HBuilderX版本 [2.1.3.20190723]

**Comment by fxy060608** [comment]
预计HBuilderX Alpha 2.1.5 版本修复此问题
