### ISSUE TITLE
uni.getUserInfo接口官方示例无法拿到用户信息

### ISSUE THREAD

**Issue by carzyYY** [dcloudio/uni-app#62]
uni.login({
  provider: 'weixin',
  success: function (loginRes) {
    console.log(loginRes.authResult);
    // 获取用户信息
    uni.getUserInfo({
      provider: 'weixin',
      success: function (infoRes) {
        console.log('用户昵称为：' + infoRes.userInfo.nickname);
      }
    });
  }
});

**Comment by hbcui1984** [comment]
JavaScript 是大小写敏感的，用户昵称是nickName，不是nickname。

**Comment by carzyYY** [comment]
嗯嗯，官网的示例有问题

**Comment by carzyYY** [comment]
> JavaScript 是大小写敏感的，用户昵称是nickName，不是nickname。

嗯嗯，官网的示例有问题
