### ISSUE TITLE
需要微信小程序能在分包内引入插件代码包

### ISSUE THREAD

**Issue by magicwing** [dcloudio/uni-app#620]
**新功能描述**
微信小程序可以配置插件在某分包中，当使用时加载（官方有相关文档）。
分包加载插件可以避免插件占用主包有限的使用大小

**现状及问题**
按照小程序官方配置不起效，导致插件只能在主包加载占用有限的使用大小

**Comment by fxy060608** [comment]
最新的 cli 及 HBuilderX Alpha2.1.6 已支持在分包配置插件
