### ISSUE TITLE
Android集成uni-app,是否只能将包和相关配置文件放在assets只读目录下？

### ISSUE THREAD

**Issue by compaqlaji** [dcloudio/uni-app#622]
**问题描述**
    Android集成uni-app,是否只能将包和相关配置文件放在assets只读目录下？
    我尝试将uni-app离线包放到sdcard下面，并通过widget的方式去加载（app = SDK.startWebApp(...appBasePath...）)，uni-app提供的模板工程中有一部分能运行起来，有的却加载失败或者加载不全（比如新闻，资讯页面加载不出来）。
   所以想请教下有没有其他办法？毕竟assets是只读目录，实际中很多需求没法做。

**Comment by compaqlaji** [comment]
E weex    : reportJSException >>>> instanceId:2, exception function:createInstance, exception:Exception: TypeError: Vue.prototype.__merge_style is not a function. (In 'Vue.prototype.__merge_style', 'Vue.prototype.__merge_style' is undefined)

**Comment by hellolixy** [comment]
同问

**Comment by ArrayDC** [comment]
应用资源必须放到指定的目录。
