### ISSUE TITLE
微信小程序子组件onLoad生命周期无效，created有效

### ISSUE THREAD

**Issue by FEpccBo** [dcloudio/uni-app#623]
微信小程序子组件onLoad生命周期无效，created有效

[复现问题的步骤]
使用子组件时 onLoad生命周期不触发 created会触发

![image](https://user-images.githubusercontent.com/22088905/62507412-e1f22b80-b836-11e9-9ac3-feedb2164ec8.png)
![image](https://user-images.githubusercontent.com/22088905/62507422-e9193980-b836-11e9-98bf-0ca8d2139480.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统
 - HBuilderX版本 2.1.3.20190723

**Comment by fxy060608** [comment]
子组件只支持 Vue 的相关生命周期，不支持页面生命周期
