### ISSUE TITLE
image 元素自关闭功能

### ISSUE THREAD

**Issue by smalike** [dcloudio/uni-app#625]
**新功能描述**
`<image></image>` 优化为自关闭标签 `<image>`

**现状及问题**
与 vuejs 编码冲突，无法实现格式化工作。https://github.com/vuejs/vue/issues/6452#issuecomment-324886989

**尝试方案**
尝试 `<image>`

**Comment by hbcui1984** [comment]
HBuilderX 2.2.5.20190907-alpha 版本，已优化该问题
