### ISSUE TITLE
H5端地图缩放问题 

### ISSUE THREAD

**Issue by kentwangit** [dcloudio/uni-app#629]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
在H5端缩放地图不能缩小到全国范围。

**预期结果**
希望可以将src/platforms/h5/view/components/map/index.vue中 
minZoom=5 修改为 minZoom=3

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: H5平台

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
文档上就是5，各端应该是一致的。
