### ISSUE TITLE
接口域名小程序必须是https的，app也必须是https的域名吗

### ISSUE THREAD

**Issue by tryharderAgain** [dcloudio/uni-app#63]

**Comment by hbcui1984** [comment]
发布小程序必需HTTPS，这是微信官方限制的。

若不考虑小程序端，仅发布App端，则uni-app无限制。

但依然建议使用HTTPS，一方面是保证用户数据安全，另一方面上传 app store也有该要求，虽然苹果官方目前尚未绝对禁用HTTP。
