### ISSUE TITLE
编辑成微信小程序后类名重复

### ISSUE THREAD

**Issue by wangwen1220** [dcloudio/uni-app#633]
**问题描述**
生成微信小程序后会产生两个一样的类名，如下图所示

**复现步骤**
![image](https://user-images.githubusercontent.com/1627874/62680590-2540cb80-b9ea-11e9-9a1a-cbf028ff2814.png)

**预期结果**
不要生成重复的类名

**实际结果**
产生的重复的类名

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 [win10]
 - uni-app版本
npmPackages:
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: * => 0.2.980
    @dcloudio/uni-h5: * => 0.7.4
    @dcloudio/uni-mp-alipay: * => 0.0.823
    @dcloudio/uni-mp-baidu: * => 0.0.853
    @dcloudio/uni-mp-qq: * => 0.0.107
    @dcloudio/uni-mp-toutiao: * => 0.0.347
    @dcloudio/uni-mp-weixin: * => 0.0.969
    @dcloudio/uni-template-compiler: * => 0.9.181
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 1.0.126
    @dcloudio/vue-cli-plugin-uni: latest => 0.9.507
    @dcloudio/vue-cli-plugin-uni-optimize: latest => 0.1.5
    @dcloudio/webpack-uni-mp-loader: * => 0.3.639
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: * => 0.2.861
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.10.0
    @vue/babel-preset-jsx:  1.1.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.10.0
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-service: ^3.10.0 => 3.10.0
    @vue/cli-shared-utils:  3.10.0
    @vue/component-compiler-utils:  2.6.0 (3.0.0)
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.1
    vue-router:  3.0.1
    vue-router-uni: ^1.0.1 => 1.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: Not Found

**Comment by ben-lau** [comment]
这是小程序的特性  自己调试下就知道了  组件内类名都会有两个

**Comment by fxy060608** [comment]
同上，该问题是微信小程序自己的。

**Comment by wangwen1220** [comment]
小程序组件确实会这样，但是自定的非小程序组件也是这样
