### ISSUE TITLE
页面引入lodash，打包微信小程序后报错

### ISSUE THREAD

**Issue by zhangyt93** [dcloudio/uni-app#641]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]页面引入lodash，打包微信小程序后报错TypeError: Cannot read property 'prototype' of undefined，打包后的mp-weixin/common/vendor.js如果格式化此文件就恢复正常，开发使用的时候是没问题的，打包成H5无报错

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看
![image](https://user-images.githubusercontent.com/17688171/62684053-6806a180-b9f2-11e9-8c39-11f585f0e7a0.png)
![image](https://user-images.githubusercontent.com/17688171/62684020-532a0e00-b9f2-11e9-8863-de937e63e703.png)

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by dcloudhdx** [comment]
暂时在 manifest 添加配置
`
"mp-weixin" : {
	"setting" : {
		"es6" : false
	}
}
`

**Comment by fxy060608** [comment]
使用最新的 HBuilderX 或更新 cli，已解决此问题
