### ISSUE TITLE
input设置confirm-type时如果给input自定义高度会出现样式问题

### ISSUE THREAD

**Issue by ruiyong-lee** [dcloudio/uni-app#643]
**问题描述**
input设置confirm-type时，如果给input自定义高度会出现样式问题，placeholder是正常的，但是输入的文字会偏移到上面

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
因为设置confirm-type时input又包裹了一层view，里面的样式写法有问题

**Comment by ruiyong-lee** [comment]
uni-input-form应该也要设置height: 100%

**Comment by zhetengbiji** [comment]
HBuilderX 2.3.0 已修复
