### ISSUE TITLE
button封装成组件后，用form的submit方法然后无法点击

### ISSUE THREAD

**Issue by hopkinson** [dcloudio/uni-app#645]
**问题描述**
![image](https://user-images.githubusercontent.com/13248613/62691595-93dd5380-ba01-11e9-98ed-ab73ee33e863.png)
我打算把button封装成一个组件，然后传入formType="submit"，发现@submit的方法没触发到， button组件的@click事件也没触发。

**预期结果**
form的submit事件和按钮的click事件都可以响应

**实际结果**
form的submit事件和按钮的click事件都无法响应

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统： PC
 - HBuilderX版本：2.1.3.20190723
 - uni-app版本：最新
 - 设备信息 PC

**Comment by hopkinson** [comment]
<form @submit="handleTplSuccess" report-submit>
	<button formType="submit" @click="Popup.share = true">
		<c-button text="砍"></c-button>
	</button>
</form>

**Comment by D-WYQ** [comment]
放一下你m-button组件里面的代码

**Comment by javascripth** [comment]
怎么封装的发出来

**Comment by Wangyaqi** [comment]
长时间未回复暂时关闭
