### ISSUE TITLE
[Bug] uni-app pages.json 条件编译出错

### ISSUE THREAD

**Issue by yuzmb** [dcloudio/uni-app#648]
**问题描述**
[uni-app pages.json 条件编译出错，条件编译写到最后一个，就会报错，undefined，pages.json 解析失败]

![image](https://user-images.githubusercontent.com/13777514/62712130-d7998280-ba2c-11e9-9bdf-4a46c8d9b850.png)

看图。

如果这样写
条件编译不写到最后一个值
![image](https://user-images.githubusercontent.com/13777514/62712241-06175d80-ba2d-11e9-87ee-67a087eb87b5.png)
那么打包是ok的

**Comment by yuzmb** [comment]
搞不懂为什么是这样，应该是pages.js中同步读取里的方法报错了

**Comment by wanganxp** [comment]
你一张图图，那个json编译后肯定是错的，因为多了一个逗号。你应该把 修改密码 后面的逗号，放到条件编译里来

**Comment by yuzmb** [comment]
![image](https://user-images.githubusercontent.com/13777514/62712797-21cf3380-ba2e-11e9-8ed3-6948c4fa6898.png)
要这样写，尴尬。。
