### ISSUE TITLE
主包加载了分包的js文件，导致 vendor.js 过大

### ISSUE THREAD

**Issue by CaptainLiao** [dcloudio/uni-app#649]
**问题描述**
在 uniapp 中使用分包，build 编译成功后，发现 vender.js 文件引入了在分包中的 .js 文件，导致主包过大。无法上传到微信小程序。

**复现**
1. 分包
````
"subPackages": [
  {
    "root": "packageA",
    "pages": [...]
  }
]
````
2. 在分包 packageA 中新建 test.js 文件，内容如下：
````
export default function a() {
   const b = '测试分包内容';
   return b;
}
````
3. 以微信小程序模式 build，编译后，在 dist\build\mp-weixin\common\vender.js 中可见分包 packageA 中的 test.js 内容。

4. *test.js 不应该出现在主包的 vender.js 内*

**Comment by CaptainLiao** [comment]
vender.js -> vendor.js

**Comment by CaptainLiao** [comment]
@fxy060608 
请问有修复的计划么

**Comment by GuoJieLun** [comment]
+1 ,我也是这样的问题

**Comment by fxy060608** [comment]
目前 cli 更新了，
manifest.json临时增加了这个配置(暂未对外开放，最终配置项可能会有调整，临时这样使用测试一下)
目前支持分包的有 mp-weixin,mp-qq,mp-baidu，其他平台配置了也不生效
"mp-weixin":{
"optimization":{
          "subPackages":true  
        }
}

分包优化具体逻辑
1.针对静态文件：分包下支持 static 等静态资源拷贝
2.针对 js 文件：当某个 js 仅被一个分包引用时，该 js 会被打包到该分包内，否则仍打到主包（即被主包引用，或被超过 1 个分包引用）
3.针对 自定义组件：若某个自定义组件仅被一个分包引用时，且未放入到分包内，编译时输出提示信息

**Comment by CaptainLiao** [comment]
@fxy060608 

非常感谢！

更新了 cli，js 文件被正确的打到对应的分包或主包。

但在 build 或 dev 模式下运行小程序时，分包页面找不到对应的分包 vendor.js。譬如 individual 是一个分包，打开任意页面如下报错：
![image](https://user-images.githubusercontent.com/17636663/63247150-e981ed80-c296-11e9-818b-0558c0145b05.png)

图片上分包vendor.js 的路径实际为：projects/individual/common/vendor.js。但这里的路径中却多了一个 /pages。

麻烦看看是什么问题。

Environment Info:
  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
  Binaries:
    Node: 10.16.3 - E:\Program Files\node-v10.16.3-win-x64\node.EXE
    Yarn: 1.6.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.9.0 - E:\Program Files\node-v10.16.3-win-x64\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @dcloudio/uni-app-plus: * => 0.0.252
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: * => 0.2.986
    @dcloudio/uni-h5: * => 0.7.4
    @dcloudio/uni-mp-alipay: * => 0.0.826
    @dcloudio/uni-mp-baidu: * => 0.0.856
    @dcloudio/uni-mp-toutiao: * => 0.0.350
    @dcloudio/uni-mp-weixin: * => 0.0.972
    @dcloudio/uni-template-compiler: * => 0.9.181
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 1.0.134
    @dcloudio/vue-cli-plugin-uni: latest => 0.9.519
    @dcloudio/webpack-uni-mp-loader: * => 0.3.641
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: * => 0.2.871
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.10.0
    @vue/babel-preset-jsx:  1.1.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.10.0
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-plugin-eslint: ^3.8.0 => 3.10.0
    @vue/cli-service: ^3.6.0 => 3.10.0
    @vue/cli-shared-utils:  3.10.0
    @vue/component-compiler-utils:  2.6.0 (3.0.0)
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.1
    vue-router:  3.0.1
    vue-style-loader:  3.1.2 (3.1.2)
    vue-template-compiler: ^2.5.21 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
    weex-vue-loader: ^0.7.0 => 0.7.0

**Comment by fxy060608** [comment]
> @fxy060608
> 
> 非常感谢！
> 
> 更新了 cli，js 文件被正确的打到对应的分包或主包。
> 
> 但在 build 或 dev 模式下运行小程序时，分包页面找不到对应的分包 vendor.js。
> 
> 譬如 individual 是一个分包，编译后结构如下：
> |--common
> |--projects
> |----individual
> |------common/vendor.js
> |------pages
> |--------about
> |----------index
> |----main
> 
> 打开individual/pages/about/index页面如下报错：
> ![image](https://user-images.githubusercontent.com/17636663/63247150-e981ed80-c296-11e9-818b-0558c0145b05.png)
> 
> 图片上分包vendor.js 的路径实际为：projects/individual/common/vendor.js。**但这里的路径中却多了一个 /pages。**
> 
> 麻烦看看怎么解决呢。
> 
> Environment Info:
> System:
> OS: Windows 10
> CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
> Binaries:
> Node: 10.16.3 - E:\Program Files\node-v10.16.3-win-x64\node.EXE
> Yarn: 1.6.0 - ~\AppData\Roaming\npm\yarn.CMD
> npm: 6.9.0 - E:\Program Files\node-v10.16.3-win-x64\npm.CMD
> Browsers:
> Edge: 42.17134.1.0
> npmPackages:
> @dcloudio/uni-app-plus: * => 0.0.252
> @dcloudio/uni-app-plus-nvue: 0.0.1
> @dcloudio/uni-app-plus-nvue-v8: 0.0.1
> @dcloudio/uni-cli-shared: * => 0.2.986
> @dcloudio/uni-h5: * => 0.7.4
> @dcloudio/uni-mp-alipay: * => 0.0.826
> @dcloudio/uni-mp-baidu: * => 0.0.856
> @dcloudio/uni-mp-toutiao: * => 0.0.350
> @dcloudio/uni-mp-weixin: * => 0.0.972
> @dcloudio/uni-template-compiler: * => 0.9.181
> @dcloudio/vue-cli-plugin-hbuilderx: latest => 1.0.134
> @dcloudio/vue-cli-plugin-uni: latest => 0.9.519
> @dcloudio/webpack-uni-mp-loader: * => 0.3.641
> @dcloudio/webpack-uni-nvue-loader: 0.0.1
> @dcloudio/webpack-uni-pages-loader: * => 0.2.871
> @vue/babel-helper-vue-jsx-merge-props: 1.0.0
> @vue/babel-plugin-transform-vue-jsx: 1.0.0
> @vue/babel-preset-app: 3.10.0
> @vue/babel-preset-jsx: 1.1.0
> @vue/babel-sugar-functional-vue: 1.0.0
> @vue/babel-sugar-inject-h: 1.0.0
> @vue/babel-sugar-v-model: 1.0.0
> @vue/babel-sugar-v-on: 1.1.0
> @vue/cli-overlay: 3.10.0
> @vue/cli-plugin-babel: 3.5.1 => 3.5.1
> @vue/cli-plugin-eslint: ^3.8.0 => 3.10.0
> @vue/cli-service: ^3.6.0 => 3.10.0
> @vue/cli-shared-utils: 3.10.0
> @vue/component-compiler-utils: 2.6.0 (3.0.0)
> @vue/preload-webpack-plugin: 1.1.1
> @vue/web-component-wrapper: 1.2.0
> mpvue-page-factory: 1.0.1
> mpvue-template-compiler: 1.0.13
> uni-h5-vue: 2.6.10
> uni-mp-vue: 2.6.10
> vue: ^2.6.10 => 2.6.10
> vue-hot-reload-api: 2.3.3
> vue-loader: 15.7.1
> vue-router: 3.0.1
> vue-style-loader: 3.1.2 (3.1.2)
> vue-template-compiler: ^2.5.21 => 2.6.10
> vue-template-es2015-compiler: 1.9.1
> vuex: ^3.0.1 => 3.1.1
> weex-vue-loader: ^0.7.0 => 0.7.0

再 npm update 一下试试

**Comment by CaptainLiao** [comment]
@fxy060608 
更新了，还是报错：
![image](https://user-images.githubusercontent.com/17636663/63254992-51403480-c2a7-11e9-9d4d-e9cae5bb12f4.png)

**Comment by fxy060608** [comment]
> @fxy060608
> 更新了，还是路径解析错误，不过这次更奇怪：
> ![image](https://user-images.githubusercontent.com/17636663/63254992-51403480-c2a7-11e9-9d4d-e9cae5bb12f4.png)

贴一下 编译后的 pages/about/index.js 这个代码最开始的那个 require

**Comment by CaptainLiao** [comment]
@fxy060608 
![image](https://user-images.githubusercontent.com/17636663/63256857-18a25a00-c2ab-11e9-9eee-1f75c4fdc19d.png)

**Comment by fxy060608** [comment]
可以在 npm update 一下，windows 上路径有问题

**Comment by CaptainLiao** [comment]
@fxy060608 

感谢！问题解决了。

**Comment by wuhuaxiangjob** [comment]
> 目前 cli 更新了，
> manifest.json临时增加了这个配置(暂未对外开放，最终配置项可能会有调整，临时这样使用测试一下)
> 目前支持分包的有 mp-weixin,mp-qq,mp-baidu，其他平台配置了也不生效
> "mp-weixin":{
> "optimization":{
> "subPackages":true
> }
> }
> 
> 分包优化具体逻辑
> 1.针对静态文件：分包下支持 static 等静态资源拷贝
> 2.针对 js 文件：当某个 js 仅被一个分包引用时，该 js 会被打包到该分包内，否则仍打到主包（即被主包引用，或被超过 1 个分包引用）
> 3.针对 自定义组件：若某个自定义组件仅被一个分包引用时，且未放入到分包内，编译时输出提示信息

问一下，这个针对分包的优化什么时候能开放，针对> 1.针对静态文件：分包下支持 static 等静态资源拷贝我看现在官网还是不支持的？什么时候能放开
