### ISSUE TITLE
tabbar 设置 position:top好像不管用啊

### ISSUE THREAD

**Issue by wangjinxin613** [dcloudio/uni-app#65]
uni.hideTabbar() 能不能支持一下app

**Comment by guangshao** [comment]
请问你解决了吗?

**Comment by hbcui1984** [comment]
> uni.hideTabbar() 能不能支持一下app

本周发版解决

**Comment by guangshao** [comment]
> > uni.hideTabbar() 能不能支持一下app
> 
> 本周发版解决

请问什么时候发新的版本

**Comment by wangjinxin613** [comment]
> > > uni.hideTabbar() 能不能支持一下app
> > 
> > 
> > 本周发版解决
> 
> 请问什么时候发新的版本

已经发了啊

**Comment by hbcui1984** [comment]
HBuilderX 1.5.0 版本已正式发布，支持uni.hideTabbar;
