### ISSUE TITLE
主包加载了分包的js文件，导致 vendor.js 过大

### ISSUE THREAD

**Issue by CaptainLiao** [dcloudio/uni-app#650]
问题描述
在 uniapp 中使用分包，build 编译成功后，发现 vendor.js 文件引入了在分包中的 .js 文件，导致主包过大。无法上传到微信小程序。

复现

分包
"subPackages": [
  {
    "root": "packageA",
    "pages": [...]
  }
]
在分包 packageA 中新建 test.js 文件，内容如下：
export default function a() {
   const b = '测试分包内容';
   return b;
}
以微信小程序模式 build，编译后，在 dist\build\mp-weixin\common\vendor.js  中可见分包 packageA 中的 test.js 内容。

test.js 不应该出现在主包的 vendor.js 内

**Comment by itzwg** [comment]
同样的问题，加入"optimization": { "subPackages": true } 无效
<img width="523" alt="image" src="https://github.com/dcloudio/uni-app/assets/88881919/381e7af6-f28c-48e1-8124-b25d73ad9a22">

**Comment by Vanisper** [comment]
> 同样的问题，加入"optimization": { "subPackages": true } 无效 <img alt="image" width="523" src="https://private-user-images.githubusercontent.com/88881919/255450384-381e7af6-f28c-48e1-8124-b25d73ad9a22.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA2MTI1NTcsIm5iZiI6MTcyMDYxMjI1NywicGF0aCI6Ii84ODg4MTkxOS8yNTU0NTAzODQtMzgxZTdhZjYtZjI4Yy00OGUxLTgxMjQtYjI1ZDczYWQ5YTIyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEwVDExNTA1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzMWVlMzJiNTE0M2RjMTFmM2E3NjM2MWUyMDRiZTljZWZjZjI0OTdkZjc5Nzc4NGYwMmJiNjc5NmI2Nzc5YWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sFIg1ThFF_-y3yI_lYDZqdgYCXcGOoL-TYxd4ZGneaQ">

看我发的issue  [https://github.com/dcloudio/uni-app/issues/5025](https://github.com/dcloudio/uni-app/issues/5025)
