### ISSUE TITLE
组件内如何使用微信视频插件

### ISSUE THREAD

**Issue by bluefox1688** [dcloudio/uni-app#652]
我已在manifest.json里配置了plugins插件
`
    "mp-weixin" : {
        "appid" : "wx",
        "setting" : {
            "urlCheck" : false,
            "minified" : true
        },
        "usingComponents" : true,
        "plugins": {
            "tencentvideo": {
                "version": "1.3.6",
                "provider": "wxa75efa648b60994b"
            }
        }
    },
`

**请问一下，在组件里使用注册此插件？**
我测试了
`import txvVideo from 'plugin://tencentvideo/video';`
注册方法，但提示未找到。
目前我只需要在微信端使用此插件

**Comment by Wangyaqi** [comment]
const TxvContext = requirePlugin("tencentvideo");  
使用微信小程序插件注意查看插件文档 [https://mp.weixin.qq.com/wxopen/plugindevdoc?appid=wxa75efa648b60994b&token=618535222&lang=zh_CN](https://mp.weixin.qq.com/wxopen/plugindevdoc?appid=wxa75efa648b60994b&token=618535222&lang=zh_CN)

**Comment by bluefox1688** [comment]
@Wangyaqi 您好，我试了一下你这个办法。
发现是能注册插件后，才可以用的
我现在的情况是，在uniapp无法注册插件

**Comment by Wangyaqi** [comment]
你是用HBuilderX创建的工程还是vue-cli创建的工程，如果是HBuilderX的话告诉我一下版本号

**Comment by bluefox1688** [comment]
HBuilderX 2.1.3.20190723

**Comment by Wangyaqi** [comment]
去官网下个alpha版试试

**Comment by Wangyaqi** [comment]
[wx-plugin-test.zip](https://github.com/dcloudio/uni-app/files/3488507/wx-plugin-test.zip)
这个是我写的一个小demo，你可以跑一下看看

**Comment by bluefox1688** [comment]
@Wangyaqi 好的，非常感谢

**Comment by bluefox1688** [comment]
我试用了你的demo，但发现还是无法注册腾讯视频插件，无法播放

**Comment by Wangyaqi** [comment]
腾讯视频插件使用比较麻烦，你可以先用一个简单的插件试一下插件的用法，比如腾讯地铁图插件，然后再排查是哪块出了问题

**Comment by bluefox1688** [comment]
就是在`json`文件里，没有这个配置
`
usingComponents: {
        'txv-video': 'plugin://tencentvideo/video',
 }
`
才导致了无法插件，我自己在`dev`里手工注册这个插件，就可以播放。
然后我测试了在`vue`文件里注册，试了很多办法，在`json`就是没有这个注册插件

**Comment by Wangyaqi** [comment]
manifest.json里面配置了吗,还有HBuilderX更新了吗

**Comment by bluefox1688** [comment]
hbx已经更新到alpha了
manifest.json也都配置的，如果不配置，即使手工注册`usingComponents: { 'txv-video': 'plugin://tencentvideo/video', }`也无法插件

**Comment by Wangyaqi** [comment]
了解了，就是组件的json文件没有地方配置是吧

**Comment by bluefox1688** [comment]
嗯嗯，是的
我另外尝试在`vue`文件的注册事件`components`来注册`'txv-video': 'plugin://tencentvideo/video',`，但被hbx过滤了，没有同步在`json`文件里同步生成`'txv-video': 'plugin://tencentvideo/video',`。
最终导致无法播放。

**Comment by bluefox1688** [comment]
目前我们只能在`build`后，再手工在json文件里配置，超级麻烦

**Comment by bluefox1688** [comment]
我说的`json`是指`页面`的`json`文件

**Comment by Wangyaqi** [comment]
页面的可以在pages.json里面配置

**Comment by bluefox1688** [comment]
`pages.json`我也试过，在页面的`json`文件还是没有同步`'txv-video': 'plugin://tencentvideo/video'`

**Comment by Wangyaqi** [comment]
配置在style的mp-weixin下面试试，我现在没在电脑前，只能让你多试试看了

**Comment by bluefox1688** [comment]
![image](https://user-images.githubusercontent.com/11862797/64919465-a2c3dc80-d7dd-11e9-9de2-bde176c13122.png)
那你看看，这是我在`pages.json`注册的，是用`usingComponents`关键词还是其他？

**Comment by Wangyaqi** [comment]
在style下面配置mp-weixin里面的配置会被单独拷贝到微信小程序里

**Comment by bluefox1688** [comment]
我在`pages.json`注册成功了，但还是有一个问题。
如果我是把`txv-video`放在组件里的话，即使在`pages.json`注册成功，组件里也无法播放，因为在pages.json只是注册到了页面，没有注册到组件里
因为项目的架构需求，视频插件只能放在组件里

**Comment by Wangyaqi** [comment]
那你配置在globalStyle里面，看看组件没能用不

**Comment by bluefox1688** [comment]
感谢 感谢，放在`globalStyle`终于可以了
