### ISSUE TITLE
在小程序中关于form-submit的问题

### ISSUE THREAD

**Issue by ZhangyilinCN** [dcloudio/uni-app#655]
就是在小程序端form中有自定义组件，然后在组件中会有input，然后在submit的事件中会拿不到组件中input的name和val，但是在h5是可以的，不知道什么原因
<form @submit="onFormSubmitFn">
     <cmpt></cmpt>
     <button formType="submit">提交</button>
</form>
cmpt组件：
<input type="text"  name='aaaa' >

**Comment by Wangyaqi** [comment]
[https://developers.weixin.qq.com/miniprogram/dev/component/input.html](https://developers.weixin.qq.com/miniprogram/dev/component/input.html)
参照微信小程序文档input部分的BUG&TIP第4条
> 对于将 input 封装在自定义组件中、而 form 在自定义组件外的情况， form 将不能获得这个自定义组件中 input 的值。

**Comment by fxy060608** [comment]
https://github.com/dcloudio/uni-app/issues/481

**Comment by fxy060608** [comment]
Duplicate of #481
