### ISSUE TITLE
编辑器Bug太多，建议转VSCode 插件方式，不要重复造轮子

### ISSUE THREAD

**Issue by Q-Qplus1s** [dcloudio/uni-app#657]
**新功能描述**
建议转为VSCode插件开发的方式支持uni-app，不要重复造轮子（质量很差的轮子）

**现状及问题**
编辑器功能太差，严重影响开发效率，各种细节bug太多，可以列举N个

1. bug 1：windows下双屏模式，打开编辑器分页时，菜单栏无法调节

2. bug 2：收起按钮点击后应该收起整个标签包围，而不是只收起标签头
![bug2](https://user-images.githubusercontent.com/50064165/62764043-90a89d00-babf-11e9-8cb2-808a1be6b481.png)
![bug2-1](https://user-images.githubusercontent.com/50064165/62764079-a1f1a980-babf-11e9-8ced-8adf9f537f01.png)

3. 代码提示检查功能等，周边配套太差，具体。。。。。。用过都知道

**尝试方案**
没有方案可以尝试，周边支持生态插件太少

uni-app 是个不错的东西，但是编辑器实在太差了

**Comment by wanganxp** [comment]
首先，uni-app的cli模式内置d.ts，支持其他ide。
其次，HBuilderX不是为uni-app做的，HBuilderX 340万开发者，uni-app的开发者在其中是少数，大部分还是web开发者。HBuilderX的那个团队本来就是做ide的，虽然市场占有率暂时不如vscode，但和sublime、webstorm是差不多的。可以去百度指数查证。
然后，回复下你报的问题：
1. “菜单里无法调节“，没看懂，请具体描述
2. 感谢反馈，我们会处理优化
3. 不知道你具体遇到什么问题了，HBuilderX在vue和uni-app相关的代码提示、转到定义，可比vscode强太多了，至于语法校验，也有eslint等插件（菜单工具-插件安装里）。如果你想在项目下安装eslint，最新的alpha版也支持了

**Comment by Q-Qplus1s** [comment]
@wanganxp 菜单无法调节复现：
1. 打开编辑器打开两个代码文件在编辑器内左右分屏显示
2. win10 下 拖动编辑器串口到右边，使得屏幕整体左右分屏
3. 尝试调节项目管理器宽度（侧边栏）
4. 发现无法调节，而且很窄

**Comment by wanganxp** [comment]
> @wanganxp 菜单无法调节复现：
> 
> 1. 打开编辑器打开两个代码文件在编辑器内左右分屏显示
> 2. win10 下 拖动编辑器串口到右边，使得屏幕整体左右分屏
> 3. 尝试调节项目管理器宽度（侧边栏）
> 4. 发现无法调节，而且很窄

你是说，有2台显示器时，每个显示器都有一个HBuilderX窗体，其中一个窗体的项目管理器右侧分割线拖不到？导致没法调节项目管理器宽度？

**Comment by Innjiafan** [comment]
@wanganxp win10双显示器，其中一个显示器的菜单栏布局会变形，显示不正常

**Comment by Innjiafan** [comment]
![0539ca0f9151faaf6183a34b4b8e839](https://user-images.githubusercontent.com/18746707/81149807-7c8fbe80-8fb1-11ea-8595-2b3bab4ce900.png)
@wanganxp
