### ISSUE TITLE
uni-H5:history模式下传参,url:payment/pay?xxx被刷新为payment/[object%20Object]

### ISSUE THREAD

**Issue by haoziye** [dcloudio/uni-app#661]
**问题描述**
uni-app,H5:history模式下传参,url:payment/paymentSuccess?xxx被刷新为payment/[object%20Object]，丢失了路径【paymentSuccess】;
此时xxx代表的参数（包含json串），是传进onload函数里了，但是刷新操作会找不到页面，显示为空白页

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 win10
 - HBuilderX 2.2.0

**Comment by haoziye** [comment]
进入页面：
![截图](https://user-images.githubusercontent.com/11716085/62844467-29276300-bcf4-11e9-871e-c8c183163eec.PNG)
刷新后：
![截图2](https://user-images.githubusercontent.com/11716085/62844472-2dec1700-bcf4-11e9-8f49-3ab701bb567a.PNG)

**Comment by haoziye** [comment]
hash模式不会这样；
Vue项目不会这样。
求解惑

**Comment by Wangyaqi** [comment]
没能复现你的问题

**Comment by zhanghan19970306** [comment]
我也出新了这个问题 没有人员来解决吗

**Comment by zhetengbiji** [comment]
> 我也出新了这个问题 没有人员来解决吗

一般是由于错误的格式导致，比如参数值为json但是未使用encodeURIComponent进行编码
