### ISSUE TITLE
h5 使用uni.createInnerAudioContext获取当前音频长度问题

### ISSUE THREAD

**Issue by weiyunpeng** [dcloudio/uni-app#662]
**问题描述**
h5 使用uni.createInnerAudioContext获取当前音频长度，从audio的属性来看
是有值的，打印audio.duration却是NaN
**复现步骤**
```js
const audio = uni.createInnerAudioContext();
audio.src = 'https://img-cdn-qiniu.dcloud.net.cn/uniapp/audio/music.mp3';
console.log(audio.duration);
```

**预期结果**
能获取到当前音频长度

**实际结果**
当前音频长度为NaN

**Comment by Wangyaqi** [comment]
`
audio.onCanplay(function(e){
	console.log(audio.duration);
});
`

**Comment by weiyunpeng** [comment]
thanks
