### ISSUE TITLE
picker mode 为 region 时，选择四川 德阳 什邡 时 detail下postcode错误，该为618400

### ISSUE THREAD

**Issue by syjinghao** [dcloudio/uni-app#663]
![image](https://user-images.githubusercontent.com/45507382/62849558-a6fa6700-bd12-11e9-9d49-b6253ce22f5c.png)
![image](https://user-images.githubusercontent.com/45507382/62849574-b5e11980-bd12-11e9-84e3-fabd771f225d.png)

**Comment by Wangyaqi** [comment]
citycode并不是邮编

**Comment by syjinghao** [comment]
e.detail.postcode.自己去看。

**Comment by syjinghao** [comment]
> citycode并不是邮编

**Comment by syjinghao** [comment]
> citycode并不是邮编

e.detail.postcode.自己去看。

**Comment by Wangyaqi** [comment]
我刚刚看成hello uni-app里面的mpvue-picker了，这个直接转成了对应的小程序的组件，数据都是对应的小程序提供的

**Comment by hbcui1984** [comment]
如果是微信小程序端的问题，则是微信数据准确性的问题了；如果是其它平台，则可以自己修改city.data.js文件
