### ISSUE TITLE
编辑器标签过多希望可滚轮滚动

### ISSUE THREAD

**Issue by yanaxua** [dcloudio/uni-app#666]
**新功能描述**
编辑器打开的文件过多时,标签栏出现滚动按钮,可以通过鼠标滚动来控制,类似vscode

**现状及问题**
现在只能通过点击右侧的切换按钮操作,这样操作距离有点远并且非常不便

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by wanganxp** [comment]
后续会提供。
其实现在可以用ctrl+tab（mac好像是alt+tab），可以ctrl+p（command+p）。这些用起来更方便快捷
