### ISSUE TITLE
支付宝小程序真机不能设置cookie

### ISSUE THREAD

**Issue by LYnnProspery** [dcloudio/uni-app#667]
**问题描述**
请求头中cookie无法携带

**复现步骤**
```js
uni.request({
    url: 'xxx',
    data: param,
    method: 'POST',
    header: {
        'content-type': 'application/x-www-form-urlencoded',
        'cookie': 'did=alipay123',
    },
});
```
[或者可以直接贴源代码]

**预期结果**
真机上的请求头中带有cookie: did=alipay123

**实际结果**
并没有关的cookie。只有一个貌似是因为不校验证书写上的accessproxy_session

**系统信息:**
 - 发行平台: 支付宝
 - 操作系统 ios12
 - uni-app版本 :
```
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
  Binaries:
    Node: 10.13.0 - /usr/local/bin/node
    Yarn: 1.12.3 - /usr/local/bin/yarn
    npm: 6.4.1 - /usr/local/bin/npm
  Browsers:
    Chrome: Not Found
    Firefox: Not Found
    Safari: 12.1.1
  npmPackages:
    @dcloudio/types: * => 0.2.6 
    @dcloudio/uni-app-plus: * => 0.0.249 
    @dcloudio/uni-app-plus-nvue:  0.0.1 
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
    @dcloudio/uni-cli-shared: * => 0.2.978 
    @dcloudio/uni-h5: * => 0.7.4 
    @dcloudio/uni-mp-alipay: * => 0.0.823 
    @dcloudio/uni-mp-baidu: * => 0.0.853 
    @dcloudio/uni-mp-qq: * => 0.0.107 
    @dcloudio/uni-mp-toutiao: * => 0.0.347 
    @dcloudio/uni-mp-weixin: * => 0.0.969 
    @dcloudio/uni-template-compiler: * => 0.9.181 
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 1.0.126 
    @dcloudio/vue-cli-plugin-uni: latest => 0.9.507 
    @dcloudio/vue-cli-plugin-uni-optimize: latest => 0.1.5 
    @dcloudio/webpack-uni-mp-loader: * => 0.3.639 
    @dcloudio/webpack-uni-nvue-loader:  0.0.1 
    @dcloudio/webpack-uni-pages-loader: * => 0.2.860 
    @ks/ks-mina-sdk-cookie: ^2.4.5 => 2.4.7 
    @ks/ks-mina-sdk-error: ^2.4.5 => 2.4.7 
    @ks/ks-mina-sdk-login: ^2.4.5 => 2.4.7 
    @ks/ks-mina-sdk-shared:  2.4.7 
    @ks/ks-mina-sdk-storage: ^2.4.5 => 2.4.7 
    @ks/ks-mina-sdk-wxio: ^2.4.5 => 2.4.7 
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
    @vue/babel-plugin-transform-vue-jsx:  1.0.0 
    @vue/babel-preset-app:  3.10.0 
    @vue/babel-preset-jsx:  1.1.0 
    @vue/babel-sugar-functional-vue:  1.0.0 
    @vue/babel-sugar-inject-h:  1.0.0 
    @vue/babel-sugar-v-model:  1.0.0 
    @vue/babel-sugar-v-on:  1.1.0 
    @vue/cli-overlay:  3.10.0 
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1 
    @vue/cli-plugin-typescript: ^3.5.1 => 3.10.0 
    @vue/cli-service: ^3.10.0 => 3.10.0 
    @vue/cli-shared-utils:  3.10.0 
    @vue/component-compiler-utils:  2.6.0 (3.0.0)
    @vue/preload-webpack-plugin:  1.1.1 
    @vue/web-component-wrapper:  1.2.0 
    mpvue-page-factory:  1.0.1 
    mpvue-template-compiler:  1.0.13 
    uni-h5-vue:  2.6.10 
    uni-mp-vue:  2.6.10 
    vue: ^2.6.10 => 2.6.10 
    vue-class-component: ^6.3.2 => 6.3.2 (7.1.0)
    vue-hot-reload-api:  2.3.3 
    vue-loader:  15.7.1 
    vue-property-decorator: ^8.2.1 => 8.2.1 
    vue-router:  3.0.1 
    vue-rx: ^6.1.0 => 6.2.0 
    vue-style-loader:  4.1.2 
    vue-template-compiler: ^2.6.10 => 2.6.10 
    vue-template-es2015-compiler:  1.9.1 
    vuex: ^3.0.1 => 3.1.1 
  npmGlobalPackages:
    @vue/cli: 3.4.1
````
 - 设备信息 iphonexr

**补充信息**
看源码感觉只是透传，怀疑是支付宝的问题？

**Comment by zhetengbiji** [comment]
> **问题描述**
> 请求头中cookie无法携带
> 
> **复现步骤**
> 
> ```js
> uni.request({
>     url: 'xxx',
>     data: param,
>     method: 'POST',
>     header: {
>         'content-type': 'application/x-www-form-urlencoded',
>         'cookie': 'did=alipay123',
>     },
> });
> ```
> 
> [或者可以直接贴源代码]
> 
> **预期结果**
> 真机上的请求头中带有cookie: did=alipay123
> 
> **实际结果**
> 并没有关的cookie。只有一个貌似是因为不校验证书写上的accessproxy_session
> 
> **系统信息:**
> 
> * 发行平台: 支付宝
> * 操作系统 ios12
> * uni-app版本 :
> 
> ```
> System:
>     OS: macOS 10.14.5
>     CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
>   Binaries:
>     Node: 10.13.0 - /usr/local/bin/node
>     Yarn: 1.12.3 - /usr/local/bin/yarn
>     npm: 6.4.1 - /usr/local/bin/npm
>   Browsers:
>     Chrome: Not Found
>     Firefox: Not Found
>     Safari: 12.1.1
>   npmPackages:
>     @dcloudio/types: * => 0.2.6 
>     @dcloudio/uni-app-plus: * => 0.0.249 
>     @dcloudio/uni-app-plus-nvue:  0.0.1 
>     @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
>     @dcloudio/uni-cli-shared: * => 0.2.978 
>     @dcloudio/uni-h5: * => 0.7.4 
>     @dcloudio/uni-mp-alipay: * => 0.0.823 
>     @dcloudio/uni-mp-baidu: * => 0.0.853 
>     @dcloudio/uni-mp-qq: * => 0.0.107 
>     @dcloudio/uni-mp-toutiao: * => 0.0.347 
>     @dcloudio/uni-mp-weixin: * => 0.0.969 
>     @dcloudio/uni-template-compiler: * => 0.9.181 
>     @dcloudio/vue-cli-plugin-hbuilderx: latest => 1.0.126 
>     @dcloudio/vue-cli-plugin-uni: latest => 0.9.507 
>     @dcloudio/vue-cli-plugin-uni-optimize: latest => 0.1.5 
>     @dcloudio/webpack-uni-mp-loader: * => 0.3.639 
>     @dcloudio/webpack-uni-nvue-loader:  0.0.1 
>     @dcloudio/webpack-uni-pages-loader: * => 0.2.860 
>     @ks/ks-mina-sdk-cookie: ^2.4.5 => 2.4.7 
>     @ks/ks-mina-sdk-error: ^2.4.5 => 2.4.7 
>     @ks/ks-mina-sdk-login: ^2.4.5 => 2.4.7 
>     @ks/ks-mina-sdk-shared:  2.4.7 
>     @ks/ks-mina-sdk-storage: ^2.4.5 => 2.4.7 
>     @ks/ks-mina-sdk-wxio: ^2.4.5 => 2.4.7 
>     @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
>     @vue/babel-plugin-transform-vue-jsx:  1.0.0 
>     @vue/babel-preset-app:  3.10.0 
>     @vue/babel-preset-jsx:  1.1.0 
>     @vue/babel-sugar-functional-vue:  1.0.0 
>     @vue/babel-sugar-inject-h:  1.0.0 
>     @vue/babel-sugar-v-model:  1.0.0 
>     @vue/babel-sugar-v-on:  1.1.0 
>     @vue/cli-overlay:  3.10.0 
>     @vue/cli-plugin-babel: 3.5.1 => 3.5.1 
>     @vue/cli-plugin-typescript: ^3.5.1 => 3.10.0 
>     @vue/cli-service: ^3.10.0 => 3.10.0 
>     @vue/cli-shared-utils:  3.10.0 
>     @vue/component-compiler-utils:  2.6.0 (3.0.0)
>     @vue/preload-webpack-plugin:  1.1.1 
>     @vue/web-component-wrapper:  1.2.0 
>     mpvue-page-factory:  1.0.1 
>     mpvue-template-compiler:  1.0.13 
>     uni-h5-vue:  2.6.10 
>     uni-mp-vue:  2.6.10 
>     vue: ^2.6.10 => 2.6.10 
>     vue-class-component: ^6.3.2 => 6.3.2 (7.1.0)
>     vue-hot-reload-api:  2.3.3 
>     vue-loader:  15.7.1 
>     vue-property-decorator: ^8.2.1 => 8.2.1 
>     vue-router:  3.0.1 
>     vue-rx: ^6.1.0 => 6.2.0 
>     vue-style-loader:  4.1.2 
>     vue-template-compiler: ^2.6.10 => 2.6.10 
>     vue-template-es2015-compiler:  1.9.1 
>     vuex: ^3.0.1 => 3.1.1 
>   npmGlobalPackages:
>     @vue/cli: 3.4.1
> ```
> 
> * 设备信息 iphonexr
> 
> **补充信息**
> 看源码感觉只是透传，怀疑是支付宝的问题？

直接写一个支付宝小程序测试一下，如果仍然存在，可以反馈给支付宝小程序官方

**Comment by LYnnProspery** [comment]
已跟支付宝开发团队确认。不支持客户端请求设置cookie。

btw，这个ft难道现在线上的支付宝小程序都不用Cookie字段而用header中的其他字段？

**Comment by ranwawa** [comment]
> **问题描述**
> 请求头中cookie无法携带
> 
> **复现步骤**
> 
> ```js
> uni.request({
>     url: 'xxx',
>     data: param,
>     method: 'POST',
>     header: {
>         'content-type': 'application/x-www-form-urlencoded',
>         'cookie': 'did=alipay123',
>     },
> });
> ```
> 
> [或者可以直接贴源代码]
> 
> **预期结果**
> 真机上的请求头中带有cookie: did=alipay123
> 
> **实际结果**
> 并没有关的cookie。只有一个貌似是因为不校验证书写上的accessproxy_session
> 
> **系统信息:**
> 
> * 发行平台: 支付宝
> * 操作系统 ios12
> * uni-app版本 :
> 
> ```
> System:
>     OS: macOS 10.14.5
>     CPU: (8) x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
>   Binaries:
>     Node: 10.13.0 - /usr/local/bin/node
>     Yarn: 1.12.3 - /usr/local/bin/yarn
>     npm: 6.4.1 - /usr/local/bin/npm
>   Browsers:
>     Chrome: Not Found
>     Firefox: Not Found
>     Safari: 12.1.1
>   npmPackages:
>     @dcloudio/types: * => 0.2.6 
>     @dcloudio/uni-app-plus: * => 0.0.249 
>     @dcloudio/uni-app-plus-nvue:  0.0.1 
>     @dcloudio/uni-app-plus-nvue-v8:  0.0.1 
>     @dcloudio/uni-cli-shared: * => 0.2.978 
>     @dcloudio/uni-h5: * => 0.7.4 
>     @dcloudio/uni-mp-alipay: * => 0.0.823 
>     @dcloudio/uni-mp-baidu: * => 0.0.853 
>     @dcloudio/uni-mp-qq: * => 0.0.107 
>     @dcloudio/uni-mp-toutiao: * => 0.0.347 
>     @dcloudio/uni-mp-weixin: * => 0.0.969 
>     @dcloudio/uni-template-compiler: * => 0.9.181 
>     @dcloudio/vue-cli-plugin-hbuilderx: latest => 1.0.126 
>     @dcloudio/vue-cli-plugin-uni: latest => 0.9.507 
>     @dcloudio/vue-cli-plugin-uni-optimize: latest => 0.1.5 
>     @dcloudio/webpack-uni-mp-loader: * => 0.3.639 
>     @dcloudio/webpack-uni-nvue-loader:  0.0.1 
>     @dcloudio/webpack-uni-pages-loader: * => 0.2.860 
>     @ks/ks-mina-sdk-cookie: ^2.4.5 => 2.4.7 
>     @ks/ks-mina-sdk-error: ^2.4.5 => 2.4.7 
>     @ks/ks-mina-sdk-login: ^2.4.5 => 2.4.7 
>     @ks/ks-mina-sdk-shared:  2.4.7 
>     @ks/ks-mina-sdk-storage: ^2.4.5 => 2.4.7 
>     @ks/ks-mina-sdk-wxio: ^2.4.5 => 2.4.7 
>     @vue/babel-helper-vue-jsx-merge-props:  1.0.0 
>     @vue/babel-plugin-transform-vue-jsx:  1.0.0 
>     @vue/babel-preset-app:  3.10.0 
>     @vue/babel-preset-jsx:  1.1.0 
>     @vue/babel-sugar-functional-vue:  1.0.0 
>     @vue/babel-sugar-inject-h:  1.0.0 
>     @vue/babel-sugar-v-model:  1.0.0 
>     @vue/babel-sugar-v-on:  1.1.0 
>     @vue/cli-overlay:  3.10.0 
>     @vue/cli-plugin-babel: 3.5.1 => 3.5.1 
>     @vue/cli-plugin-typescript: ^3.5.1 => 3.10.0 
>     @vue/cli-service: ^3.10.0 => 3.10.0 
>     @vue/cli-shared-utils:  3.10.0 
>     @vue/component-compiler-utils:  2.6.0 (3.0.0)
>     @vue/preload-webpack-plugin:  1.1.1 
>     @vue/web-component-wrapper:  1.2.0 
>     mpvue-page-factory:  1.0.1 
>     mpvue-template-compiler:  1.0.13 
>     uni-h5-vue:  2.6.10 
>     uni-mp-vue:  2.6.10 
>     vue: ^2.6.10 => 2.6.10 
>     vue-class-component: ^6.3.2 => 6.3.2 (7.1.0)
>     vue-hot-reload-api:  2.3.3 
>     vue-loader:  15.7.1 
>     vue-property-decorator: ^8.2.1 => 8.2.1 
>     vue-router:  3.0.1 
>     vue-rx: ^6.1.0 => 6.2.0 
>     vue-style-loader:  4.1.2 
>     vue-template-compiler: ^2.6.10 => 2.6.10 
>     vue-template-es2015-compiler:  1.9.1 
>     vuex: ^3.0.1 => 3.1.1 
>   npmGlobalPackages:
>     @vue/cli: 3.4.1
> ```
> 
> * 设备信息 iphonexr
> 
> **补充信息**
> 看源码感觉只是透传，怀疑是支付宝的问题？

你这一套环境和版本信息是怎么生成的呢?????还是人肉复制粘贴的?

**Comment by lixiang-king** [comment]
请问这个问题解决了吗？
