### ISSUE TITLE
web-view组件的postMessage无效

### ISSUE THREAD

**Issue by robin901118** [dcloudio/uni-app#670]
**问题描述**
需要实现H5页面和小程序之间的通信，文档上写可以用postMessage，于是写了以下代码：

（H5端）
```html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta content="width=device-width,initial-scale=1.0,user-scalable=no,viewport-fit=cover" name="viewport"/>
    <meta content="yes" name="apple-mobile-web-app-capable"/>
    <meta content="no" name="apple-touch-fullscreen"/>
    <meta content="black" name="apple-mobile-web-app-status-bar-style"/>
    <meta content="telephone=no" name="format-detection"/>
    <title>Title</title>
    <!-- 微信 JS-SDK 如果不需要兼容微信小程序，则无需引用此 JS 文件。 -->
    <script type="text/javascript" src="https://res.wx.qq.com/open/js/jweixin-1.4.0.js"></script>
    <!-- uni 的 SDK -->
    <script type="text/javascript" src="https://js.cdn.aliyun.dcloud.net.cn/dev/uni-app/uni.webview.1.5.1.js"></script>
</head>
<body>
<script>
  document.addEventListener('UniAppJSBridgeReady', function() {
    uni.postMessage({
      data: {
        action: 'postMessage'
      }
    });
  });
</script>
</body>
```

（uni端）

```
<template>
	<view class="content">
		<web-view
			:src="url"
			@message="test">
		</web-view>
	</view>
</template>

<script>
	export default {
		data(){
			return{
				url:""//服务器部署地址（提issue所以暂时隐藏了）
			}
		},
		methods:{
			test(e){
				console.log(1234);
			}
		}
	}
</script>

<style lang="scss">
	@import "./webviewMap";
</style>

```

ps：因为我这个是个人账号，所以不支持业务域名的配置，所以在小程序调试中，我是开启了不校验合法域名这个选项。其实调用跳转页面如：uni.switchTab()  ,  uni.navigateTo()等等这些API是有效果的，唯独postMessage没有效果，我看社区里也有人反馈说在某个钩子触发时机（onHide等等）会一次性返回一个数组，但是我这也没触发。

**预期结果**
希望正确触发@message

**实际结果**
没有反应

**系统信息:**
- 小程序基础库版本：2.4.0
- HBuilderX版本：2.2.1.20190813
- npm run info运行信息如下：
  npmPackages:
    @dcloudio/uni-app-plus: 0.0.244 => 0.0.244
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: * => 0.2.963
    @dcloudio/uni-h5: * => 0.5.10
    @dcloudio/uni-mp-alipay: 0.0.818 => 0.0.818
    @dcloudio/uni-mp-baidu: 0.0.846 => 0.0.846
    @dcloudio/uni-mp-qq: 0.0.102 => 0.0.102
    @dcloudio/uni-mp-toutiao: 0.0.342 => 0.0.342
    @dcloudio/uni-mp-weixin: 0.0.963 => 0.0.963
    @dcloudio/uni-template-compiler: * => 0.9.179
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 0.9.528
    @dcloudio/vue-cli-plugin-uni: latest => 0.9.482
    @dcloudio/webpack-uni-mp-loader: * => 0.3.630
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: * => 0.2.846
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.8.0
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.8.0
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-service: ^3.0.1 => 3.8.4
    @vue/cli-shared-utils:  3.8.0
    @vue/component-compiler-utils:  2.6.0
    @vue/preload-webpack-plugin:  1.1.0
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.0
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: Not Found

**Comment by Wangyaqi** [comment]
新建Hello uni-app 项目里面有postMessage的例子，你看那个能正常触发吗

**Comment by robin901118** [comment]
> 新建你好uni-app项目里面有postMessage的例子，你看那个能正常触发吗

hello uni-app里面例子正常，并且我把我的webview的链接拷贝到hello template里也是正常的，但是在我自己的项目里，就算拷贝hello template里的例子也是没响应。纠结得很

**Comment by robin901118** [comment]
实现了，是因为我把这个页面做成了tabBar页面，可能导致我切换tabBar的时候没有其触发的钩子，所以无反应，当我做成二级页面的时候就可以正常触发了，不得不说还是有点坑的，如果能实现立即反馈而不是延迟反馈就好了。

**Comment by zhetengbiji** [comment]
> 实现了，是因为我把这个页面做成了tabBar页面，可能导致我切换tabBar的时候没有其触发的钩子，所以无反应，当我做成二级页面的时候就可以正常触发了，不得不说还是有点坑的，如果能实现立即反馈而不是延迟反馈就好了。

可以和微信小程序官方反馈一下，另外个人账号是不能使用web-view组件的。
