### ISSUE TITLE
【App】uni.getImageInfo 当图片不存在时不能正确返回结果

### ISSUE THREAD

**Issue by magicwing** [dcloudio/uni-app#671]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
获取网络图片地址中的图片已经不存在了，当访问cdn图片不存在时会跳转到特定报错页面（比如：阿里会跳转到 http://promotion.alicdn.com/help/oss/error.html）
这种情况下通过 uni.getImageInfo 获取图片信息会造成 success、fail、complete都不被回调，或者超时后回调success，参数中的height和width都是null。

**预期结果**
图片不存在的话就在fail中返回结果（平台编译后的微信小程序时正常的）

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 android和ios 都存在问题
 - HBuilderX版本 2.1.3.20190723

**Comment by dcloudhdx** [comment]
Bug已确认

**Comment by dcloudhdx** [comment]
最新版本 HBuilderX 已修复
