### ISSUE TITLE
nodemodules重新安装后build h5出现bug

### ISSUE THREAD

**Issue by lizhu16** [dcloudio/uni-app#673]
**问题描述**
nodemodules 安装后build H5失败出现错误
![image](https://user-images.githubusercontent.com/26211118/63067731-ec04e000-bf42-11e9-961b-5173c6d979ef.png)
getPlatformCopy is not function
经查找\node_modules\@dcloudio\vue-cli-plugin-uni\lib\copy-webpack-options.js:24:6)下使用@dcloudio/uni-cli-shared/lib/platformz中的getPlatformCopy 函数
![image](https://user-images.githubusercontent.com/26211118/63067760-0e96f900-bf43-11e9-86bc-435845e72b97.png)
@dcloudio/uni-cli-shared/lib/platform中实际无此函数
![image](https://user-images.githubusercontent.com/26211118/63067828-6d5c7280-bf43-11e9-8532-295b12c38e5a.png)
打包失败

**复现步骤**
[复现问题的步骤]
1.  npm run build:h5

**Comment by lizhu16** [comment]
![image](https://user-images.githubusercontent.com/26211118/63068534-09877900-bf46-11e9-9bc3-70da517d5e3e.png)
此版本有问题

**Comment by fxy060608** [comment]
你可以看下你本地下载的 uni-cli-shared是不是 0.2.984 版本，我这里测试没问题
后续会统一各个安装包的版本号，方便统一升级。

**Comment by ranwawa** [comment]
遇到各种打包失败的问题,,,,,清空node_modules,清空缓存,删除lock.json 或者yarn.lock再重新安装

**Comment by lizhu16** [comment]
> 你可以看下你本地下载的 uni-cli-shared是不是 0.2.984 版本，我这里测试没问题
> 后续会统一各个安装包的版本号，方便统一升级。

还有个问题问一下，自定义组件的样式打包后小程序不生效如何解决

**Comment by fxy060608** [comment]
> > 你可以看下你本地下载的 uni-cli-shared是不是 0.2.984 版本，我这里测试没问题
> > 后续会统一各个安装包的版本号，方便统一升级。
> 
> 还有个问题问一下，自定义组件的样式打包后小程序不生效如何解决

可以新开 issue，详细描述问题
