### ISSUE TITLE
支付宝小程序运行时没有initTriggerEvent

### ISSUE THREAD

**Issue by LYnnProspery** [dcloudio/uni-app#674]
**问题描述**
支付宝小程序页面不能事件的通信

支付宝中Page initHook 是直接调了钩子
```js
initHooks(pageOptions, hooks, vuePageOptions)
```

而其他的都会进行一些extra的初始化，比如 initTriggerEvent
```js
function initHook (name, options) {
  const oldHook = options[name]
  if (!oldHook) {
    options[name] = function () {
      initTriggerEvent(this)
    }
  } else {
    options[name] = function (...args) {
      initTriggerEvent(this)
      return oldHook.apply(this, args)
    }
  }
}

Page = function (options = {}) {
  initHook('onLoad', options)
  return MPPage(options)
}

Component = function (options = {}) {
  initHook('created', options)
  return MPComponent(options)
}

```
这样会导致 支付宝小程序的页面中如果有类似emit的行为，就会抛出`triggerEvent is not a function`，因为mpIntance上并没有挂在这个方法

**Comment by LYnnProspery** [comment]
这么做的原因是什么？

**Comment by fxy060608** [comment]
应该是当时支付宝不支持重写 Page，Component
不过已经在其他地方给 mpInstance 补充了 triggerEvent.
[https://github.com/dcloudio/uni-app/blob/master/src/platforms/mp-alipay/runtime/wrapper/component-parser.js](url)

你是怎么使用的，会报没这个方法？

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启

**Comment by huadong** [comment]
> 应该是当时支付宝不支持重写 Page，Component
> 不过已经在其他地方给 mpInstance 补充了 triggerEvent.
> https://github.com/dcloudio/uni-app/blob/master/src/platforms/mp-alipay/runtime/wrapper/component-parser.js
> 
> 你是怎么使用的，会报没这个方法？

@fxy060608 支付宝小程序里面，目前还会报这个错误。具体当在**页面**使用this.$emit()时候，没有类似component-parser.js
那样补充了triggerEvent()。

同时，如果给page补充了triggerEvent()，还需要判断this.props是否存在，调试发现支付宝小程序的页面this.props为undefined.
