### ISSUE TITLE
支付宝小程序 自定义组件编译模式 进入真机闪退

### ISSUE THREAD

**Issue by ranwawa** [dcloudio/uni-app#680]
所有依赖包都是今天的最新版本
自定义组件模式编译后,pc上可以正常操作
但是真机预览或真机调试,在请求接口时就会自动退出小程序
应该是桥接层的故障

换成模板编译模式后就好了

**Comment by Wangyaqi** [comment]
没复现你的问题，现在还有这个问题吗？如果有的话可以发一份代码我们试试看

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
