### ISSUE TITLE
input组件中获取不到键盘的高度

### ISSUE THREAD

**Issue by XQY279** [dcloudio/uni-app#682]
```vue
<input type="text" placeholder="输入对他说的话"
			@focus="inputfocus($event)"
			:focus="isfocus"
			cursor-spacing="5px"
			comfirm-type="done"
			v-model="text" />
```

```javascript
inputfocus(e){
	console.log(e.detail)
}
```

这是文档API的描述：输入框聚焦时触发，event.detail = { value, height }，height 为键盘高度

然而上述代码中取到的没有 height；
只有：
```json
{"value" : ""}
```

**Comment by zhetengbiji** [comment]
文档已修正：[修改 input textarea 文档](https://github.com/dcloudio/uni-app/commit/d5ca47c0f9a28205cf447f483bea74ebda792508)

**Comment by XQY279** [comment]
我想 获取键盘的高度需要怎么获取呢

**Comment by zhetengbiji** [comment]
> 我想 获取键盘的高度需要怎么获取呢

请关注近期更新内容，大概下一个alpha版本会支持
