### ISSUE TITLE
@dcloudio/webpack-uni-pages-loader 生成对应平台小程序的 project.config.json 有误

### ISSUE THREAD

**Issue by solarhell** [dcloudio/uni-app#683]
**问题描述**
查看源码发现，对应平台小程序的项目配置文件(`project.config.json`)由 `@dcloudio/webpack-uni-pages-loader` 这个包负责。
他是将 `src/mainfest.json` 里对应的部分copy过去。
QQ小程序 AppID 和 基础库版本 应为 `qqappid` 和 `qqLibVersion`。
目前编译后发现这里引入的是为微信小程序配置的id和基础库版本。

**复现步骤**

1. 修改mainfest.json，为微信、qq小程序设置appId
2. 编译QQ小程序
3. 在QQ小程序中导入项目，会发现AppID不能自动填充。实际上是因为编译后的json有误。

**系统信息:**
Environment Info:

  System:
    OS: macOS 10.14.6
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
  Binaries:
    Node: 12.8.0 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.10.3 - /usr/local/bin/npm
  Browsers:
    Chrome: 76.0.3809.100
    Firefox: 68.0.1
    Safari: 12.1.2
  npmPackages:
    @dcloudio/types: * => 0.3.0
    @dcloudio/uni-app-plus: * => 0.0.252
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: * => 0.2.985
    @dcloudio/uni-h5: * => 0.7.4
    @dcloudio/uni-mp-alipay: * => 0.0.826
    @dcloudio/uni-mp-baidu: * => 0.0.856
    @dcloudio/uni-mp-qq: * => 0.0.110
    @dcloudio/uni-mp-toutiao: * => 0.0.350
    @dcloudio/uni-mp-weixin: * => 0.0.972
    @dcloudio/uni-stat: ^0.0.101 => 0.0.101
    @dcloudio/uni-template-compiler: * => 0.9.181
    @dcloudio/vue-cli-plugin-hbuilderx: ^1.0.122 => 1.0.133
    @dcloudio/vue-cli-plugin-uni: ^0.9.498 => 0.9.517
    @dcloudio/webpack-uni-mp-loader: * => 0.3.640
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: * => 0.2.868
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.9.2
    @vue/babel-preset-jsx:  1.0.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.0.0
    @vue/cli-overlay:  3.10.0
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-plugin-typescript: ^3.5.1 => 3.10.0
    @vue/cli-service: ^3.9.0 => 3.10.0
    @vue/cli-shared-utils:  3.10.0
    @vue/component-compiler-utils:  2.6.0 (3.0.0)
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-class-component: ^6.3.2 => 6.3.2 (7.1.0)
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.1
    vue-property-decorator: ^8.2.1 => 8.2.1
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
    vuex-class: ^0.3.2 => 0.3.2

**一些别的建议**
应该把5个小程序平台，是否需要es6转es5，css样式补全，等等这些信息都写死在编译出的json中，否则开发时经常需要去思考勾选。甚至会影响最终发布的产物。

**Comment by Wangyaqi** [comment]
确实有这个问题，感谢反馈

**Comment by fxy060608** [comment]
已修复 qqappid ，qqLibVersion 的问题，可以 npm update 更新
