### ISSUE TITLE
【报Bug】h5新功能 摇树优化 发布h5 失败！

### ISSUE THREAD

**Issue by hiair2323** [dcloudio/uni-app#685]
http://ask.dcloud.net.cn/question/76509

没有启用发布结果

[HBuilder] 09:12:31.906 项目 'dev-yanbaoke' 开始发布h5...  
[HBuilder] 09:12:31.907 项目 'dev-yanbaoke' 开始编译...  
[HBuilder] 09:13:13.546  DONE  Build complete.   
[HBuilder] 09:13:13.556 项目 'dev-yanbaoke' 编译成功.  
[HBuilder] 09:13:14.575 项目 'dev-yanbaoke'导出h5成功  
启用以后发布结果 失败！！

[HBuilder] 09:17:52.637  INFO  Build optimizing...  
[HBuilder] 09:17:52.648  DONE  Build complete.   
[HBuilder] 09:17:52.649 项目 'dev-yanbaoke' 编译成功.  
[HBuilder] 09:18:14.045  DONE  Build complete.  
[HBuilder] 09:18:14.054 项目 'dev-yanbaoke' 编译成功.  
[HBuilder] 09:18:14.061 文件查找失败：'uni-view/components/icon' at ../../../../../../Applications/HBuilderX.app/Contents/HBuilderX/plugins/uniapp-cli/node_modules/@dcloudio/vue-cli-plugin-uni-optimize/.tmp/components.js:43  
[HBuilder] 09:18:14.118 项目 'dev-yanbaoke' 发布h5失败.

**Comment by hbcui1984** [comment]
H5平台暂时没有icon组件，建议先通过条件编译绕开
