### ISSUE TITLE
softinput : adjustResize, 安卓 全局设置无效, adjustPan 的话会吧自定义navigation 也顶上去

### ISSUE THREAD

**Issue by DestinyHunter** [dcloudio/uni-app#686]
**问题描述**
softinput : adjustResize, 安卓 全局设置无效, adjustPan 的话会吧自定义navigation 也顶上去

**系统信息:**
 - 发行平台: 5+ App
 - HBuilderX版本 2.1.3 以上

**Comment by zhetengbiji** [comment]
怎么设置的？

**Comment by DestinyHunter** [comment]
```
"app-plus" : {
   
        "softinput" : {
            "mode" : "adjustResize" //软键盘弹出模式，
        }
}
```

**Comment by DestinyHunter** [comment]
关键的是adjustPan 会把自定义navigation 也顶上去

**Comment by zhetengbiji** [comment]
> "app-plus" : {
>    
>         "softinput" : {
>             "mode" : "adjustResize" //软键盘弹出模式，
>         }
> }

你这个用法是从哪里看到的？

**Comment by DestinyHunter** [comment]
官网 https://uniapp.dcloud.io/component/input?id=%E5%85%B3%E4%BA%8E%E8%BD%AF%E9%94%AE%E7%9B%98%E5%BC%B9%E5%87%BA%E7%9A%84%E9%80%BB%E8%BE%91%E8%AF%B4%E6%98%8E

**Comment by zhetengbiji** [comment]
> 官网 https://uniapp.dcloud.io/component/input?id=%E5%85%B3%E4%BA%8E%E8%BD%AF%E9%94%AE%E7%9B%98%E5%BC%B9%E5%87%BA%E7%9A%84%E9%80%BB%E8%BE%91%E8%AF%B4%E6%98%8E

改为在 pages.json 中配置 "softinputMode": "adjustResize"

**Comment by DestinyHunter** [comment]
pages.json  不是 今iOS 支持吗 
![image](https://user-images.githubusercontent.com/20897838/63248196-5f875400-c299-11e9-8068-5365f2786d5c.png)

**Comment by zhetengbiji** [comment]
> pages.json 不是 今iOS 支持吗
> ![image](https://user-images.githubusercontent.com/20897838/63248196-5f875400-c299-11e9-8068-5365f2786d5c.png)

已经修改：[9ed86c8]( https://github.com/dcloudio/uni-app/commit/9ed86c8985df5f168b289b65a80b9a6d788e4590)
