### ISSUE TITLE
uni.pageScrollTo 不起作用

### ISSUE THREAD

**Issue by harleybox** [dcloudio/uni-app#689]
**问题描述**
[goTop() {
					uni.pageScrollTo({
						scrollTop: 60,
						duration: 300,
					});
					console.log("111")
				},](url)

模拟器和真机，uni.pageScrollTo不工作，2018年官方貌似确认过bug，请问什么时候能解决？

https://ask.dcloud.net.cn/question/62687

**Comment by Wangyaqi** [comment]
没复现你这个问题，贴一下你的完整的可以复现问题的代码

**Comment by harleybox** [comment]
多谢回复，我在官方的demo里面 tabbar.nuve这个文件里面，修改下面这个函数，不工作

`ontabtap(e) {
                let index = e.target.dataset.current || e.currentTarget.dataset.current;
                this.switchTab(index);
				
					uni.pageScrollTo({
						scrollTop: 1,
						duration: 0,
					});
				console.log(e);
				
           },`

**Comment by Wangyaqi** [comment]
这个页面下面的滚动是用scroll-view实现的，操作scroll-view的scroll-top即可

**Comment by harleybox** [comment]
已解决，谢谢
