### ISSUE TITLE
分页使用uParse解析富文本报错

### ISSUE THREAD

**Issue by 20180119** [dcloudio/uni-app#695]
**问题描述**
分页使用uParse解析富文本报错：Cannot read property '$options' of undefined，这个错误不是uParse插件报的错

**实际结果**
![image](https://user-images.githubusercontent.com/35593523/63312328-c8bba580-c333-11e9-9252-074508d667e3.png)

**系统信息:**
 - 发行平台: 百度开发工具
 - 操作系统: [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本: 2.2.1.20190813
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息: 所有模拟设备

**Comment by 20180119** [comment]
经过打印，发现自定义组件对象没有生成$vm 

![1566282299(1)](https://user-images.githubusercontent.com/35593523/63322568-50b2a700-c356-11e9-9bdc-8c6c9f11d41e.jpg)

**Comment by Wangyaqi** [comment]
提供一下复现bug的代码，打包发上来

**Comment by 20180119** [comment]
这是复现代码
[mp-baidu.zip](https://github.com/dcloudio/uni-app/files/3544810/mp-baidu.zip)

**Comment by Wangyaqi** [comment]
发一下源码，你现在发的是编译后的

**Comment by 20180119** [comment]
pages/test/test
[uni-app-test.zip](https://github.com/dcloudio/uni-app/files/3544919/uni-app-test.zip)

**Comment by Wangyaqi** [comment]
现在再试还有问题吗，更新百度小程序开发工具和HBuilderX

**Comment by StrivingRabbit** [comment]
由于长时间未回复，此问题关闭，如果还有问题可以重开或者提新issue
