### ISSUE TITLE
oppo手机 安卓5.1    通过webview加载页面 无法点击  

### ISSUE THREAD

**Issue by canghaisangtian** [dcloudio/uni-app#698]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

oppo手机 安卓5.1    通过webview加载页面 无法点击     官方案例也有这个问题

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 Android 5.1
 - HBuilderX版本  最新版本
 - uni-app版本  最新版本

**Comment by Wangyaqi** [comment]
可以用chrome的调试工具看一下webview里的页面有没有报错

**Comment by canghaisangtian** [comment]
安卓5.1 跳转页面没有响应  在安卓8   没有发现问题

**Comment by JigsawLee** [comment]
+1

**Comment by dcloudhdx** [comment]
更新 HBuilderX 2.5.5+
