### ISSUE TITLE
ios13真机调试官方demo失败

### ISSUE THREAD

**Issue by harleybox** [dcloudio/uni-app#699]
ios13 public beta最新  ，hbuild 2.2.2
真机调试官方demo

12:29:40.752 编译器版本：2.2.2
12:29:40.759 当前项目编译模式：自定义组件模式。编译模式差异见：https://ask.dcloud.net.cn/article/35843
12:29:40.773 当前nvue编译模式：uni-app 。编译模式差异见：https://ask.dcloud.net.cn/article/36074
12:29:59.353  DONE  Build complete. Watching for changes...
12:29:59.362 项目 'hello' 编译成功.
12:29:59.628 正在建立手机连接...
12:30:06.478 正在同步手机端程序文件...
12:30:19.107 打开文件服务失败，请尝试拔掉数据线后重新连接手机，或重启手机再试
12:30:19.140 已停止运行...

**Comment by wanganxp** [comment]
iOS13的支持正在处理，请关注更新

**Comment by dcloudhdx** [comment]
HBuilderX 2.3.0+ 已支持
