### ISSUE TITLE
uni.showActionSheet是否关闭弹层

### ISSUE THREAD

**Issue by wsygdiv** [dcloudio/uni-app#7]
uni.showActionSheet选中不关闭弹层的方法有没有

**Comment by xiaoyucoding** [comment]
不支持。
不是很清楚什么业务场景下会有这种需求，能否详细叙述一下，目前可以自己用组件来模拟实现。

**Comment by hbcui1984** [comment]
issue超过1个月不回应，暂时关闭，若继续有问题，可以重开或发新issues
