### ISSUE TITLE
增加日历组件，支持标准日历和带周数显示的校历

### ISSUE THREAD

**Issue by zengqingsong** [dcloudio/uni-app#70]
[mpvue-calendar.zip](https://github.com/dcloudio/uni-app/files/2514037/mpvue-calendar.zip)

**Comment by zengqingsong** [comment]
希望集成到hello world中

**Comment by hbcui1984** [comment]
> 希望集成到hello world中

这是一个开源组件吧？开源地址在哪里？

**Comment by hbcui1984** [comment]
uni-app 已开放[插件市场](https://ext.dcloud.net.cn)，日历组件可参考 http://ext.dcloud.net.cn/plugin?id=56
