### ISSUE TITLE
自定义组件模式 动态绑定class 不支持filters

### ISSUE THREAD

**Issue by myjustify** [dcloudio/uni-app#700]
**问题描述**
自定义组件模式 动态绑定class 不支持filters

**复现步骤**

> <view class='recoder' v-if="activeIndex==1">
			<view class="recoderItem" v-for="(item,index) in [1,2,3,4]" :key='index'>
				<view class="flex-row-b recoderItemHeader">
					<view class="">申请时间：2019-04-01 12:00:00</view>
					<view :class="item|statusCss">已取消</view>
				</view>
				<view class="item-content">
					<view class="flex-row">
						<view class="item-content-l">车牌号：</view>
						<view class="">豫A4444</view>
					</view>
					<view class="flex-row">
						<view class="item-content-l">年审时间：</view>
						<view class="">2020-02-01</view>
					</view>
					<view class="flex-row">
						<view class="item-content-l">姓名：</view>
						<view class="">段勇</view>
					</view>
				</view>
				<view class="item-footer flex-row-end">
					<button type="primary" plain>撤销</button>
				</view>
			</view>
		</view>

> filters:{
			statusCss:function(value){
				console.log(value)
				return value+'ass';
			}
		}

![image](https://user-images.githubusercontent.com/30165374/63405275-ddbe3480-c418-11e9-8813-5b0635df5322.png)

**Comment by Wangyaqi** [comment]
目前这种写法有兼容问题，可以用methods实现，比如这样
```
<template>
	<view class="content">
		<view class="" v-for="(item,index) in list" :key="index">
			<view :class="[getClass(item)]">

			</view>
		</view>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				list: [1, 2, 3, 4, 5, 6]
			}
		},
		onLoad() {

		},
		methods: {
			getClass(item) {
				return item + "1"
			}
		}
	}
</script>
```

**Comment by myjustify** [comment]
多谢
