### ISSUE TITLE
[BUG BUG] tabbar 英文文字 显示不全

### ISSUE THREAD

**Issue by manly0305** [dcloudio/uni-app#701]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
Category  的 g 的 y 显示不全， 在IOS 真机和模拟器都是这样。 

[或者可以直接贴源代码]

**预期结果**
显示全

**实际结果**
Category  的 g 的 y 显示不全， 在IOS 真机和模拟器都是这样。
<img width="405" alt="Screen Shot 2019-08-21 at 17 21 25" src="https://user-images.githubusercontent.com/8382355/63420102-99429100-c438-11e9-821b-1790ae17faf6.png">

**系统信息:**
 - 发行平台:  App
 - 操作系统 iOS 12.1.2

**Comment by Wangyaqi** [comment]
确实有这个问题，感谢反馈

**Comment by manly0305** [comment]
@Wangyaqi    
We are trying to build uni-apps for other country .
Any plan to fix this ?

**Comment by manly0305** [comment]
@Wangyaqi   
Please let me know

**Comment by zhetengbiji** [comment]
> @Wangyaqi
> We are trying to build uni-apps for other country .
> Any plan to fix this ?

处理中

**Comment by manly0305** [comment]
@zhetengbiji 
有更新么？

**Comment by zhetengbiji** [comment]
> @zhetengbiji
> 有更新么？

有的，更新 HBuilderX 2.3.6

**Comment by zhetengbiji** [comment]
> @zhetengbiji
> 有更新么？

你的HBuilderX不提示更新的吗？

**Comment by manly0305** [comment]
@zhetengbiji

Sure . Thank you !

**Comment by zhetengbiji** [comment]
> @zhetengbiji
> 
> Sure . Thank you !

你测试一下，然后反馈一下情况

**Comment by manly0305** [comment]
Cool! It works
