### ISSUE TITLE
关闭导航栏后window-top在h5还是导航栏高度

### ISSUE THREAD

**Issue by ben-lau** [dcloudio/uni-app#705]
我在h5端关闭了导航栏
![image](https://user-images.githubusercontent.com/16952163/63479479-0d287c00-c4c1-11e9-9cab-32782397c38b.png)
在我一个组件内的遮罩层用了window-top
![image](https://user-images.githubusercontent.com/16952163/63479510-26c9c380-c4c1-11e9-8001-02749420573a.png)
在安卓端正常  top是0  在ios端还是有导航栏的高度

**Comment by Wangyaqi** [comment]
确认BUG，感谢反馈
在globalStyle中配置有BUG，在pages的style里面配置正常

**Comment by Wangyaqi** [comment]
已修改，下次发版生效
