### ISSUE TITLE
TabBar打包成静态文件后图标不显示

### ISSUE THREAD

**Issue by yetrom** [dcloudio/uni-app#707]
**问题描述**
npm run build:h5，打包后的tabbar图标不显示

**复现步骤**
[复现问题的步骤]
1.  manifest.json内配置
	"h5": {"publicPath" : "./"}

2.用npm run build:h5打包成静态文件

3.在开发环境下能显示的tabBar图标编译后无法显示

**补充信息**
可以看见，tabBar会自动在路径前加【/】，导致图片无法读取
![B{}E1B~Q3L%4O8QSP3PJ8 5](https://user-images.githubusercontent.com/20130679/63490038-4de6bc00-c4e6-11e9-8921-4525b04da7bc.png)
![}L(0PS9VZQEY 8NKN@$U3BM](https://user-images.githubusercontent.com/20130679/63490041-50491600-c4e6-11e9-8023-b69f2f25c581.png)

**Comment by Jewill** [comment]
遇见相同问题，请问有解决方案了吗

**Comment by zhetengbiji** [comment]
目前不支持相对路径

**Comment by Rain20199** [comment]
怎么解决的啊？

**Comment by Rain20199** [comment]
怎么解决的啊？

**Comment by Rain20199** [comment]
怎么解决的啊？

**Comment by Rain20199** [comment]
找到打包后的indexxxxxx.js文件  把uniConfig.router={mode:"hash",base:"/"}改成e.uniConfig.router={mode:"hash",base:"./"}即可

**Comment by zhetengbiji** [comment]
后续已经支持

**Comment by idabaicai** [comment]
请问这个问题解决了吗，我也遇到这种问题了。
