### ISSUE TITLE
安卓手机下使用uni-app版本打包的html文件在hbuilderx版本里的plus.webview.create打开会报错

### ISSUE THREAD

**Issue by Chenthy** [dcloudio/uni-app#708]
- **问题描述**

安卓手机下使用uni-app版本打包的html文件在hbuilderx版本里的plus.webview.create打开会报错

**复现步骤**
HBuilderX版本代码
 subWebview = plus.webview.create(that.plusUrl, 'gameView', styles);
      currentWebview.append(subWebview)
      subWebview.show()
uni-app版本代码
 <iframe :src="gameUrl"
            class="iframe"
            :style="styleObject"></iframe>
this.gameUrl = plus.storage.getItem('plus-game-url')

**预期结果**
ios不会 android会报错:，安装能正常像ios运行

**实际结果**

13:59:34.324 [system] at hybrid/html/login/static/js/chunk-vendors.81101969.js:1

**Comment by Wangyaqi** [comment]
有更完整的代码吗，有的话可以发上来，或者打个包发到ask论坛

**Comment by Chenthy** [comment]
> 有更完整的代码吗，有的话可以发上来，或者打个包发到问论坛

是自己代码写的有问题，在uni-app cli版本里的代码写错了，跳转了一个不存在的路由，但是很奇怪为什么ios运行不报错。
