### ISSUE TITLE
老是编译编译着就卡死了

### ISSUE THREAD

**Issue by asd26269546** [dcloudio/uni-app#71]
一卡就是几分钟还不带有反应的，我就先加个路由，就卡死了

**Comment by fxy060608** [comment]
能否截图说明一下具体情况
HBuilderX 整个卡死？
编译器卡死？需要重新运行？

**Comment by hbcui1984** [comment]
> 我这里也是同样的现象，mac 连接手机，基本上一报错就卡住了，不编译了。
> 
> 编译3-5次后也会卡住
> 
> 还有就是点击多次重新编译，会有多个进程同时进行编译，现象就是控制台输出多行一样的内容。

编译时如果出现错误，会停止编译，不会继续执行；修改代码后，需再次点击运行菜单，逻辑就是这样的。

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
