### ISSUE TITLE
[BUG] 编译报错TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by GuoJieLun** [dcloudio/uni-app#711]
**问题描述**
如图,
![image](https://user-images.githubusercontent.com/9344885/63497692-e08f5700-c4f6-11e9-9f8f-dbaa6b04b40b.png)

**复现步骤**
[复现问题的步骤]
1.  编写vue界面后,刷新小程序就报错

**预期结果**
 刷新后编译不报错
**实际结果**
自动刷新时不时报错 `TypeError: Cannot read property 'call' of undefined` .
需要重新点击运行小程序才能打开

**系统信息:**
 - 平台: [mac]
 - HBuilderX版本 [2.2.2]
 - 设备信息 [小程序编辑器]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by hbcui1984** [comment]
检查你的代码中是否有啥特殊写法，或者测试 hello uni-app发行到小程序端，能否复现问题

**Comment by fxy060608** [comment]
是不是在 pages.json 中删除了某个页面之后热更新出现的该问题？

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启

**Comment by chenpengjun** [comment]
同样遇到这个问题，不知道问题在哪，不能编辑，一编辑就报这个错误

**Comment by Smmw** [comment]
@fxy060608 我是 在移动了页面的文件夹位置 然后删除pages.json 中某个页面后一直有这样的问题，请问 怎么解决呢？

**Comment by chenpengjun** [comment]
@Smmw  删掉unpackage下的dist目录，重新启动服务就行

**Comment by Smmw** [comment]
@chenpengjun 谢谢你，试过了。这个方法不行。🙏

**Comment by ctt8520** [comment]
楼主解决了吗 ？现在遇到这个问题 百度谷歌了好多都不行

**Comment by Wangyaqi** [comment]
你们HBuilderX版本都是多少的

**Comment by ctt8520** [comment]
2.3.6.20191020

> 你们HBuilderX版本都是多少的

2.3.6.20191020

**Comment by Wangyaqi** [comment]
> 2.3.6.20191020
> 
> > 你们HBuilderX版本都是多少的
> 
> 2.3.6.20191020

能知道具体怎么操作会触发这个BUG吗

**Comment by ctt8520** [comment]
> > 2.3.6.20191020
> > > 你们HBuilderX版本都是多少的
> > 
> > 
> > 2.3.6.20191020
> 
> 能知道具体怎么操作会触发这个BUG吗

我是正常编译就会报这个错，但是报错以在多编译几次就又好了

**Comment by chenpengjun** [comment]
@Smmw @ctt8520
我们团队开发的时候都遇到这个问题，很影响开发效率。解决方案就是，关掉服务，删除unpackage dist目录，再重新启动服务。再试试看能不能帮到你们

**Comment by ctt8520** [comment]
> @Smmw @ ctt8520
> 我们团队开发的时候都遇到了这个问题，很影响开发效率。解决方案就是，关掉服务，删除unpackage dist目录，再重新启动服务。再试试看能不能帮到你们

谢谢 我试试

**Comment by Smmw** [comment]
> @Smmw @ctt8520
> 我们团队开发的时候都遇到这个问题，很影响开发效率。解决方案就是，关掉服务，删除unpackage dist目录，再重新启动服务。再试试看能不能帮到你们

好的，谢谢！我一会试一试

**Comment by yolkerrr** [comment]
![image](https://user-images.githubusercontent.com/58155364/70602247-ec7e6080-1c2e-11ea-97e9-118568e88292.png)
![image](https://user-images.githubusercontent.com/58155364/70602279-ff913080-1c2e-11ea-9e79-aea9baf13f39.png)
![image](https://user-images.githubusercontent.com/58155364/70602386-4b43da00-1c2f-11ea-9de1-dfee7f429e9d.png)

HBuilder版本：2.4.6
小程序开发工具版本：v1.0.2.1910120
系统：window 64bit
热更新编译大概十几次会出现一次，得重启微信开发工具才能重新热更新

页面引用goods.js如下
![image](https://user-images.githubusercontent.com/58155364/70602499-8c3bee80-1c2f-11ea-8ccc-c8b9e2d0b8ef.png)

goods.js引用fetch.js如下
![image](https://user-images.githubusercontent.com/58155364/70602544-a83f9000-1c2f-11ea-8b64-b7bf9d25931e.png)

fetch.js引用config.js如下
![image](https://user-images.githubusercontent.com/58155364/70602642-d1f8b700-1c2f-11ea-87d3-6b6c41f00ad3.png)

而config.js只是export default{} 一个对象

希望能尽快更新版本解决这种bug或者说是我写的语法不对可以告知

**Comment by FirmDiary** [comment]
没后续了？

**Comment by BeefFat** [comment]
后续呢

**Comment by tangchuanxi** [comment]
哇哦 我也是这个问题呦 每天重启几十次

**Comment by hiblacker** [comment]
+1

**Comment by webpig** [comment]
经常有这个问题

**Comment by nyrf** [comment]
到现在了还有这个问题，动不动就出现，只有在小程序端，都没人管？

**Comment by iceycc** [comment]
我也碰到了 好烦 有解决的么

**Comment by soulcm** [comment]
同问啊，我也遇到，咋就没人解决了？？？

**Comment by se7en94** [comment]
2021年了，还是没解决这个问题么，我也遇到了

**Comment by PhoenixLeeSin** [comment]
2022年了 依旧没解决  世界第一 🐂

**Comment by jason-liang** [comment]
什么情况啊 真是坑啊 我也出现了这个问题

**Comment by HobaiRiku** [comment]
最近刚更新3.3.13.20220314，这个问题超级明显

**Comment by musicvv521** [comment]
我也遇见了2022-3-25. 而且我的小程序跑项目上面会出现莫名其妙的方框，不遮挡，真机上没有。

**Comment by liujianying** [comment]
2022年了 依旧没解决 世界第一 🐂

**Comment by LuckLin520** [comment]
现在出现频率越来越高了，一天要重启40多次

**Comment by MachoManCk** [comment]
还不解决？uni-app 在装死？

**Comment by hyb1234hi** [comment]
2022年10月，还是没解决

**Comment by zhetengbiji** [comment]
需要能复现的开发者提供对应的测试项目配合

**Comment by MachoManCk** [comment]
这个没办法，我升级Hbulder后，也是有这个报错
Object(...) is not a function Cannot read properties of undefined (reading 'call') 




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年10月18日(星期二) 下午3:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dcloudio/uni-app] [BUG] 编译报错TypeError: Cannot read property &#39;call&#39; of undefined (#711)





 
需要能复现的开发者提供对应的测试项目配合

**Comment by xuweikang** [comment]
2022-11-22 还是有这个问题

**Comment by martianmartian** [comment]
https://blog.csdn.net/weixin_46016926/article/details/119835761
貌似这个博客说的是对的，[我的是因为导入的接口文件名字和当前页面名称一样. 也就是我在首页index.vue中导入了index.js 的接口文件。  后来修改了接口文件名称就好了](url)
但是这样的问题显然不应该出现的

**Comment by icegeeker** [comment]
2022.11.30了，还是有这个问题。按照博客里说的重新改名了也不行。

**Comment by agonyt** [comment]
同样遇见这个问题，关了小程序，关了HbuilderX，重新打开重新编译，就好了。。。

**Comment by lingwecho** [comment]
大家可以这样尝试一下，在hbuilder编辑器操作，运行-运行到小程序模拟器，勾选运行时是否压缩代码。我勾选了这个之后，再次编译好像不会出现这个问题了。

**Comment by yuanzhuohao** [comment]
上面的办法都试过，不行。有人解决了吗？

**Comment by MachoManCk** [comment]
弃掉Hb，改为cli，解决了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhuohao ***@***.***&gt;; 
发送时间: 2023年3月16日(星期四) 上午6:41
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dcloudio/uni-app] [BUG] 编译报错TypeError: Cannot read property &#39;call&#39; of undefined (#711)





 
上面的办法都试过，不行。有人解决了吗？

**Comment by nacker1** [comment]
2023年4月 问题依旧存在，越写越火大，这是哪门的效率提升工具，一天8小时 一半时间交待在这个问题上。

**Comment by zhetengbiji** [comment]
> 2023年4月 问题依旧存在，越写越火大，这是哪门的效率提升工具，一天8小时 一半时间交待在这个问题上。

除了“越火大”外，有没有什么有效线索提供一下

**Comment by MachoManCk** [comment]
改用cli吧，弃用Hb



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Zhuohao ***@***.***&gt;; 
发送时间: 2023年4月3日(星期一) 中午11:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [dcloudio/uni-app] [BUG] 编译报错TypeError: Cannot read property &#39;call&#39; of undefined (#711)





  
2023年4月 问题依旧存在，越写越火大，这是哪门的效率提升工具，一天8小时 一半时间交待在这个问题上。
  
除了“越火大”外，有没有什么有效线索提供一下

**Comment by herman7** [comment]
2023年6月，依旧未解决 
version: 3.7.11

**Comment by imtns** [comment]
![1734062631702](https://github.com/user-attachments/assets/c5b74a2d-7c6d-425a-aeba-17b90843c122)
小程序开发了很久一直热更新没有问题，今天突然热更新出现了TypeError: Cannot read property 'call' of undefined， 重启了好多遍，但是热更新几次就出现了，想起来昨天在文件夹里新建了一个index.js文件，   删掉了后就再也没出现过了，推测文件夹里不能同时出现js和vue文件。。。
