### ISSUE TITLE
[App]uni.chooseImage选择大图时候闪退

### ISSUE THREAD

**Issue by magicwing** [dcloudio/uni-app#713]
**问题描述**
ios在使用uni.chooseImage选择大图（大于15MB）时候闪退，参数original 原图和compressed 压缩图都一样闪退，xcode错误日志如下：
Received memory pressure event 16 vm pressure 0
Message from debugger: Terminated due to memory issue
预计android也存在相应问题。

**预期结果**
如果无法加载至少fail给予相关错误提示，或者不加载给予图片信息（例如大小），这样我可以通过压缩图片后在加载。

**系统信息:**
 - 发行平台: 5+app
 - 操作系统 iOS 12.4
 - HBuilderX版本 2.1.3.20190723
 - 设备信息 [iPhone6]

**Comment by dcloudhdx** [comment]
请提供测试图片

**Comment by magicwing** [comment]
[15M图片.zip](https://github.com/dcloudio/uni-app/files/3539471/15M.zip)


> 请提供测试图片

**Comment by dcloudhdx** [comment]
Bug已修复，下次发版生效
