### ISSUE TITLE
H5  navigateBack  BUG

### ISSUE THREAD

**Issue by zhouqj1414657557** [dcloudio/uni-app#717]
**问题描述**
 H5 里面如果子页面用户手动进行了刷新操作，那么子页面会丢失路由栈信息（也就是说路由会全部出栈）子页面调用 navigateBack 回到父页面

**Comment by zhouqj1414657557** [comment]
子页面无法调用navigateBack方法，无法回到上一个页面

**Comment by joel785454405** [comment]
你是不是开了vue-devtools

**Comment by zhouqj1414657557** [comment]
不是呀，就是用户用了浏览器自带的刷新，刷新过后getCurrentPages() 只能获取到当前的页面信息，
uni.navigateBack(); 也无法回到上一个页面。我感觉是用户刷新过后，路由全部出栈了

**Comment by bxpxqxd** [comment]
> 不是呀，就是用户用了浏览器自带的刷新，刷新过后getCurrentPages() 只能获取到当前的页面信息，
> uni.navigateBack(); 也无法回到上一个页面。我感觉是用户刷新过后，路由全部出栈了

肯定的啊

**Comment by zhouqj1414657557** [comment]
哪 这个有其他方案实现相似功能吗

**Comment by bxpxqxd** [comment]
> 哪 这个有其他方案实现相似功能吗

什么功能？你想要的是一个硬着头皮后退模式吗？就是不管上个页面状态如何，硬着头皮后退url即可，如果是的话用 ``history.back()``

**Comment by zhouqj1414657557** [comment]
> > 哪 这个有其他方案实现相似功能吗
> 
> 什么功能？你想要的是一个硬着头皮后退模式吗？就是不管上个页面状态如何，硬着头皮后退url即可，如果是的话用 `history.back()`

因为这个我感觉仅仅只是uniApp 的路由出栈了，真正的系统路由还是存在的，因为我用手机自带的返回页面是可以返回到上一个页面的，所以vue的路由信息应该还是存在的，看来只有先尝试用你的这个方案了

**Comment by bxpxqxd** [comment]
> > > 哪 这个有其他方案实现相似功能吗
> > 
> > 
> > 什么功能？你想要的是一个硬着头皮后退模式吗？就是不管上个页面状态如何，硬着头皮后退url即可，如果是的话用 `history.back()`
> 
> 因为这个我感觉仅仅只是uniApp 的路由出栈了，真正的系统路由还是存在的，因为我用手机自带的返回页面是可以返回到上一个页面的，所以vue的路由信息应该还是存在的，看来只有先尝试用你的这个方案了

这个方案叫做：硬着头皮后退模式
没有什么“真正的系统路由”这种东西，浏览器的叫 history，只是记录了你的访问历史。

**Comment by zhouqj1414657557** [comment]
> 这个方案叫做：硬着头皮后退模式
> 没有什么“真正的系统路由”这种东西，浏览器的叫 history，只是记录了你的访问历史。

哈哈  好的，我懂你意思了

**Comment by zhouqj1414657557** [comment]
万分感谢 @bxpxqxd
