### ISSUE TITLE
[App]release版每次启动会在temp文件夹下生成时间戳名字的文件

### ISSUE THREAD

**Issue by magicwing** [dcloudio/uni-app#718]
**问题描述**
app每次启动都会在 android/data/包名/apps/appid名字/temp下 生成 时间戳文件，
导出查看比对，发现和app-service.js代码基本一致，而且每次生成的时间戳文件都一样，
这个问题在android平台debug版app没有发现，在release版有发现，ios没有了解过官方可否确认一下。
每个文件都有1-2m左右，而且不会主动删除，三方清理app也不会列入清理列表中，造成了空间多余的占用。

**预期结果**
这种时间戳文件是否就生成一次，或者限制数量保留最近的几个，或者能不生成。

**实际结果**
图片是Helloword页面打包后的app生成时间戳文件情况
![X~YDRE6HF{ %JQA4S C$VNL](https://user-images.githubusercontent.com/7157683/63633325-4c99c880-c679-11e9-96ac-255aa246f0d6.png)

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 Android 7.0
 - HBuilderX版本 2.1.3.20190723
 - 设备信息 红米Note4X

**Comment by ArrayDC** [comment]
正式版发版不会生成临时文件，不要使用自定义基座打包发版。
