### ISSUE TITLE
支持微信小程序 style v2

### ISSUE THREAD

**Issue by solarhell** [dcloudio/uni-app#721]
**新功能描述**
微信客户端 7.0 开始，UI 界面进行了大改版。小程序也进行了基础组件的样式升级。app.json 中配置 "style": "v2"可表明启用新版的组件样式。

**现状及问题**
现在page.json并不支持此项配置。

**补充信息**
https://developers.weixin.qq.com/miniprogram/dev/reference/configuration/app.html#style

**Comment by fxy060608** [comment]
manifest.json->mp-weixin->style->v2

**Comment by solarhell** [comment]
解决了 谢谢
