### ISSUE TITLE
onPageScroll 在滚动停止后还继续执行

### ISSUE THREAD

**Issue by AnvinMao** [dcloudio/uni-app#722]
**问题描述**
Android平台，惯性滑动停止后 onPageScroll 还会继续执行

**复现步骤**
[复现问题的步骤]
1、长列表
2、Android 5+ app
3、长距离惯性滑动

[或者可以直接贴源代码]

**预期结果**
滚动停止后即刻停止onPageScroll的执行，并得到当前页面的滚动距离

**实际结果**
滚动停止后，onPageScroll会继续执行，直到执行完毕才会停止

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 Android 8.0
 - HBuilderX版本  HBuilderX 2.2.2.20190816

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
你是怎么判断onPageScroll继续触发的？

**Comment by AnvinMao** [comment]
> 你是怎么判断onPageScroll继续触发的？

控制台输出 onPageScroll 参数

**Comment by zhetengbiji** [comment]
> > 你是怎么判断onPageScroll继续触发的？
> 
> 控制台输出 onPageScroll 参数

是因为控制台的日志输出有延迟

**Comment by AnvinMao** [comment]
> > > 你是怎么判断onPageScroll继续触发的？
> > 
> > 
> > 控制台输出 onPageScroll 参数
> 
> 是因为控制台的日志输出有延迟

实际APP运行上，确实是存在滚动停止后还会继续触发！！如果不存在这情况，我也没必要去调试

**Comment by zhetengbiji** [comment]
> > > > 你是怎么判断onPageScroll继续触发的？
> > > 
> > > 
> > > 控制台输出 onPageScroll 参数
> > 
> > 
> > 是因为控制台的日志输出有延迟
> 
> 实际APP运行上，确实是存在滚动停止后还会继续触发！！如果不存在这情况，我也没必要去调试

仅存在于app端的安卓上吗？iOS或者小程序以及H5平台是否存在？

**Comment by fxy060608** [comment]
> > > > 你是怎么判断onPageScroll继续触发的？
> > > 
> > > 
> > > 控制台输出 onPageScroll 参数
> > 
> > 
> > 是因为控制台的日志输出有延迟
> 
> 实际APP运行上，确实是存在滚动停止后还会继续触发！！如果不存在这情况，我也没必要去调试

onPageScroll 的触发是视图 view 层通知业务代码 service 层，两者不在同一个环境，不是同步执行，可以简单理解 view 层每个滚动事件会进入一个队列，由另一个环境 service 顺序执行该队列，不要在 onPageScroll 里边执行复杂逻辑

**Comment by AnvinMao** [comment]
> > > > > 你是怎么判断onPageScroll继续触发的？
> > > > 
> > > > 
> > > > 控制台输出 onPageScroll 参数
> > > 
> > > 
> > > 是因为控制台的日志输出有延迟
> > 
> > 
> > 实际APP运行上，确实是存在滚动停止后还会继续触发！！如果不存在这情况，我也没必要去调试
> 
> 仅存在于app端的安卓上吗？iOS或者小程序以及H5平台是否存在？

`<template>
	<view class="content">
		<view class="fix-header">ScrollTop = {{scrollTop}}</view>
		<view class="data-list">
			<view v-for="(item, index) in dataList" :key="index" class="data-item">
				<view v-if="item != null">{{item.name}}</view>
			</view>
		</view>
	</view>
</template>

<script>
	let index = 0;
	export default {
		data() {
			return {
				scrollTop: 0,
				dataList: []
			};
		},
		onLoad() {
			index = 1
			this.loadData()
		},
		onReachBottom() {
			this.loadData()
		},
		onPageScroll(e) {
			this.scrollTop = e.scrollTop
		},
		methods:{
			loadData() {
				for (let i = 0; i < 300; i++) {
					this.dataList.push({
						id: index,
						name: "title_" + index
					})
					
					index++
				}
			}
		}
	}
</script>

<style>
	.content {
		background: #eee;
	}
	.fix-header {
		position: fixed;
		width: 100%;
		line-height: 80upx;
		height: 80upx;
		padding: 0 30upx;
		background: #FFFFFF;
	}
	.data-list {
		padding-top: 90upx;
	}
	.data-item {
		width: 100%;
		line-height: 120upx;
		height: 120upx;
		padding: 0 30upx;
		background: #FFFFFF;
		margin-bottom: 10upx;
	}
</style>
`

发现问题，感觉这个是由于v-for里的v-if引起的，如上面的代码，如果v-if="item != null"去掉则不会出现那问题，加了v-if就会

**Comment by AnvinMao** [comment]
```
<template>
	<view class="content">
		<view class="fix-header">ScrollTop = {{scrollTop}}</view>
		<view class="data-list">
			<view v-for="(item, index) in dataList" :key="index" class="data-item">
				<view v-if="item != null">{{item.name}}</view>
			</view>
		</view>
	</view>
</template>

<script>
	let index = 0;
	export default {
		data() {
			return {
				scrollTop: 0,
				dataList: []
			};
		},
		onLoad() {
			index = 1
			this.loadData()
		},
		onReachBottom() {
			this.loadData()
		},
		onPageScroll(e) {
			this.scrollTop = e.scrollTop
		},
		methods:{
			loadData() {
				for (let i = 0; i < 300; i++) {
					this.dataList.push({
						id: index,
						name: "title_" + index
					})
					
					index++
				}
			}
		}
	}
</script>

<style>
	.content {
		background: #eee;
	}
	.fix-header {
		position: fixed;
		width: 100%;
		line-height: 80upx;
		height: 80upx;
		padding: 0 30upx;
		background: #FFFFFF;
	}
	.data-list {
		padding-top: 90upx;
	}
	.data-item {
		width: 100%;
		line-height: 120upx;
		height: 120upx;
		padding: 0 30upx;
		background: #FFFFFF;
		margin-bottom: 10upx;
	}
</style>

```

发现问题，比如上面的代码，如果列表里v-for中有用了v-if就会出现onPageScroll的问题，没有v-if="item != null" 就不会

**Comment by fxy060608** [comment]
> @fxy060608 @zhetengbiji
> 
> ```
> <template>
> 	<view class="content">
> 		<view class="fix-header">ScrollTop = {{scrollTop}}</view>
> 		<view class="data-list">
> 			<view v-for="(item, index) in dataList" :key="index" class="data-item">
> 				<view v-if="item != null">{{item.name}}</view>
> 			</view>
> 		</view>
> 	</view>
> </template>
> 
> <script>
> 	let index = 0;
> 	export default {
> 		data() {
> 			return {
> 				scrollTop: 0,
> 				dataList: []
> 			};
> 		},
> 		onLoad() {
> 			index = 1
> 			this.loadData()
> 		},
> 		onReachBottom() {
> 			this.loadData()
> 		},
> 		onPageScroll(e) {
> 			this.scrollTop = e.scrollTop
> 		},
> 		methods:{
> 			loadData() {
> 				for (let i = 0; i < 300; i++) {
> 					this.dataList.push({
> 						id: index,
> 						name: "title_" + index
> 					})
> 					
> 					index++
> 				}
> 			}
> 		}
> 	}
> </script>
> 
> <style>
> 	.content {
> 		background: #eee;
> 	}
> 	.fix-header {
> 		position: fixed;
> 		width: 100%;
> 		line-height: 80upx;
> 		height: 80upx;
> 		padding: 0 30upx;
> 		background: #FFFFFF;
> 	}
> 	.data-list {
> 		padding-top: 90upx;
> 	}
> 	.data-item {
> 		width: 100%;
> 		line-height: 120upx;
> 		height: 120upx;
> 		padding: 0 30upx;
> 		background: #FFFFFF;
> 		margin-bottom: 10upx;
> 	}
> </style>
> ```
> 
> 发现问题，比如上面的代码，如果列表里v-for中有用了v-if就会出现onPageScroll的问题，没有v-if="item != null" 就不会

原因分析：
因为 onPageScroll 中，修改了 scrollTop，需要页面渲染显示该数字，导致页面 vdom 会重新生成并对比，此时，因为你的循环中使用了 v-if，导致框架生成 vdom 时，性能较低，阻塞了 js 执行，从而导致 onPageScroll 执行性能低下
解决方案：
1.移除 v-if 判断
2.如果必须有 v-if，则可以将 fix-header 作为一个单独组件使用

示例：

fixed-header.vue
```html
<template>
    <view class="fix-header">ScrollTop = {{scrollTop}}</view>
</template>

<script>
    export default {
        data() {
            return {
                scrollTop: 0
            }
        }
    }
</script>

<style>
</style>

```
```html
<template>
    <view class="content">
        <fixedHeader ref="header" />
        <view class="data-list">
            <view v-for="(item, index) in dataList" :key="item.id" class="data-item">
                <view v-if="item.id">{{item.name}}</view>
            </view>
        </view>
    </view>
</template>
<script>
import fixedHeader from './fixed-header'
...
onPageScroll(e) {
            this.$refs.header.scrollTop = e.scrollTop // 直接修改组件内数据可优化性能
        },
...
</script>
```

**Comment by AnvinMao** [comment]
> > @fxy060608 @zhetengbiji
> > ```
> > <template>
> > 	<view class="content">
> > 		<view class="fix-header">ScrollTop = {{scrollTop}}</view>
> > 		<view class="data-list">
> > 			<view v-for="(item, index) in dataList" :key="index" class="data-item">
> > 				<view v-if="item != null">{{item.name}}</view>
> > 			</view>
> > 		</view>
> > 	</view>
> > </template>
> > 
> > <script>
> > 	let index = 0;
> > 	export default {
> > 		data() {
> > 			return {
> > 				scrollTop: 0,
> > 				dataList: []
> > 			};
> > 		},
> > 		onLoad() {
> > 			index = 1
> > 			this.loadData()
> > 		},
> > 		onReachBottom() {
> > 			this.loadData()
> > 		},
> > 		onPageScroll(e) {
> > 			this.scrollTop = e.scrollTop
> > 		},
> > 		methods:{
> > 			loadData() {
> > 				for (let i = 0; i < 300; i++) {
> > 					this.dataList.push({
> > 						id: index,
> > 						name: "title_" + index
> > 					})
> > 					
> > 					index++
> > 				}
> > 			}
> > 		}
> > 	}
> > </script>
> > 
> > <style>
> > 	.content {
> > 		background: #eee;
> > 	}
> > 	.fix-header {
> > 		position: fixed;
> > 		width: 100%;
> > 		line-height: 80upx;
> > 		height: 80upx;
> > 		padding: 0 30upx;
> > 		background: #FFFFFF;
> > 	}
> > 	.data-list {
> > 		padding-top: 90upx;
> > 	}
> > 	.data-item {
> > 		width: 100%;
> > 		line-height: 120upx;
> > 		height: 120upx;
> > 		padding: 0 30upx;
> > 		background: #FFFFFF;
> > 		margin-bottom: 10upx;
> > 	}
> > </style>
> > ```
> > 
> > 
> > 发现问题，比如上面的代码，如果列表里v-for中有用了v-if就会出现onPageScroll的问题，没有v-if="item != null" 就不会
> 
> 原因分析：
> 因为 onPageScroll 中，修改了 scrollTop，需要页面渲染显示该数字，导致页面 vdom 会重新生成并对比，此时，因为你的循环中使用了 v-if，导致框架生成 vdom 时，性能较低，阻塞了 js 执行，从而导致 onPageScroll 执行性能低下
> 解决方案：
> 1.移除 v-if 判断
> 2.（推荐方案）如果必须有 v-if，则可以将 fix-header 作为一个单独组件使用，并独立修改 scrollTop
> 
> 示例：
> 
> fixed-header.vue
> 
> ```
> <template>
>     <view class="fix-header">ScrollTop = {{scrollTop}}</view>
> </template>
> 
> <script>
>     export default {
>         data() {
>             return {
>                 scrollTop: 0
>             }
>         }
>     }
> </script>
> 
> <style>
> </style>
> ```
> 
> ```
> <template>
>     <view class="content">
>         <fixedHeader ref="header" />
>         <view class="data-list">
>             <view v-for="(item, index) in dataList" :key="item.id" class="data-item">
>                 <view v-if="item.id">{{item.name}}</view>
>             </view>
>         </view>
>     </view>
> </template>
> <script>
> import fixedHeader from './fixed-header'
> ...
> onPageScroll(e) {
>             this.$refs.header.scrollTop = e.scrollTop // 直接修改组件内数据可优化性能
>         },
> ...
> </script>
> ```

谢谢大佬！
