### ISSUE TITLE
引入uniapp 组件显示undefined ,样式未生效

### ISSUE THREAD

**Issue by lizhu16** [dcloudio/uni-app#723]
**问题描述**
引入uniapp的组件显示undefined,节点样式未生效

**复现步骤**
![image](https://user-images.githubusercontent.com/26211118/63663812-7af0e280-c7f6-11e9-989d-b54ff746ee99.png)

**实际结果**
![image](https://user-images.githubusercontent.com/26211118/63663740-2cdbdf00-c7f6-11e9-9fc3-0acf8ea9efb9.png)
![image](https://user-images.githubusercontent.com/26211118/63663833-91973980-c7f6-11e9-9a41-f059e69837a8.png)

**Comment by Wangyaqi** [comment]
直接运行```Hello uni-app``` 扩展组件 里面的 ```loadmore``` 会出现这个问题吗

**Comment by lizhu16** [comment]
> 直接运行`Hello uni-app` 扩展组件 里面的 `loadmore` 会出现这个问题吗

用的就是uniapp扩展组件中的loadmore

**Comment by Wangyaqi** [comment]
我的意思是直接运行hello uni-app项目会出现这个undefined吗

**Comment by lizhu16** [comment]
> 我的意思是直接运行hello uni-app项目会出现这个undefined吗

不会，没找到是哪儿的问题，用自定义组件没有undefined,样式未生效

**Comment by Wangyaqi** [comment]
启用自定义组件模式了吗
[https://uniapp.dcloud.io/collocation/manifest?id=mp-weixin](https://uniapp.dcloud.io/collocation/manifest?id=mp-weixin)

**Comment by lizhu16** [comment]
> 启用自定义组件模式了吗
> https://uniapp.dcloud.io/collocation/manifest?id=mp-weixin

![image](https://user-images.githubusercontent.com/26211118/63668113-b694a800-c808-11e9-9958-55d9ca6944b2.png)
启用了

**Comment by lizhu16** [comment]
> 启用自定义组件模式了吗
> https://uniapp.dcloud.io/collocation/manifest?id=mp-weixin

启用了
![image](https://user-images.githubusercontent.com/26211118/63668410-a0d3b280-c809-11e9-812b-c7a53d5ece6d.png)

**Comment by Wangyaqi** [comment]
```status:'more'||'loading'||'noMore'```，没有loadingType这个参数吧

**Comment by lizhu16** [comment]
> `status:'more'||'loading'||'noMore'`，没有loadingType这个参数吧

![image](https://user-images.githubusercontent.com/26211118/63668518-f3ad6a00-c809-11e9-80ef-56ece9c19b34.png)
刚开始写没加这个，后来拷贝的文档

**Comment by Wangyaqi** [comment]
应该是这块文档有问题，一会我修改一下

**Comment by lizhu16** [comment]
> 应该是这块文档有问题，一会我修改一下

没用loadingType也不行

**Comment by Wangyaqi** [comment]
你把删减之后能复现这个问题的代码打包发上来我试试

**Comment by lizhu16** [comment]
这里是: 
[project.zip](https://github.com/dcloudio/uni-app/files/3539738/project.zip)

**Comment by lizhu16** [comment]
> 你把删减之后能复现这个问题的代码打包发上来我试试

这里是: 
[project.zip](https://github.com/dcloudio/uni-app/files/3539753/project.zip)


还有一个问题 , 在 search 文件 小程序子组件样式无法展示 #693

**Comment by Wangyaqi** [comment]
你发我项目里面组件是放在load-more/load-more.vue，引用组件的时候也是load-more/load-more.vue，统一改成uni-load-more/uni-load-more.vue还是有这个问题吗

**Comment by lizhu16** [comment]
> 你发我项目里面组件是放在load-more/load-more.vue，引用组件的时候也是load-more/load-more.vue，统一改成uni-load-more/uni-load-more.vue还是有这个问题吗

还是有, 目录及文件名称已修改,引用目录也已修改
效果为: http://qntemp.bejson.com/upload/247833604880582502019-8-26-loadMore%E9%97%AE%E9%A2%98.png

**Comment by Wangyaqi** [comment]
找到问题了。。。 你的项目里面 .env.development里面配置了```VUE_CLI_BABEL_TRANSPILE_MODULES = true```，去掉就正常了，你的另外一个问题也是这个导致的

**Comment by lizhu16** [comment]
> 找到问题了。。。 你的项目里面 .env.development里面配置了`VUE_CLI_BABEL_TRANSPILE_MODULES = true`，去掉就正常了，你的另外一个问题也是这个导致的

万分感谢

**Comment by akiko123456** [comment]
怎么解决的啊
