### ISSUE TITLE
base64格式的图片，显示有问题

### ISSUE THREAD

**Issue by jwhklk** [dcloudio/uni-app#725]
**问题描述**
从数据库抓取的base64格式的图片数据，放到image组件下的src参数里面，渲染后，被加上了相对路径变成了 《img src="/pages/user/data:image/svg+xml;base64,PHN2...." /》

**复现步骤**
[复现问题的步骤]
1.  将base64图片地址赋给组件的data
2. 将数据绑定到image组件的src中
3. 渲染后图片加载不出来，查看h5页面元素，发现图片src里面多了”/pages/***/“相对路劲信息

**Comment by swiftest0** [comment]
相同的问题，原因在于对data协议的解析上 #668

**Comment by jwhklk** [comment]
> 相同的问题，原因在于对data协议的解析上 #668

如何解决？

**Comment by swiftest0** [comment]
目前官方还没提供方案的情况下，可以先这样处理：

把这些地方的正则改成：/^data:/
[https://github.com/dcloudio/uni-app/search?q=BASE64_RE&unscoped_q=BASE64_RE](url)

**Comment by zhetengbiji** [comment]
HBuilderX 2.3.0 已修复

**Comment by sixsir** [comment]
> HBuilderX 2.3.0 已修复

我现在用的 2.6.9 也还是有这个问题呢？ 无语，要怎么修改呢
