### ISSUE TITLE
H5端下，图片预览功能不要修改url，并增加关闭按钮

### ISSUE THREAD

**Issue by zhangyanzt** [dcloudio/uni-app#727]
**新功能描述**
H5端下，图片预览功能不要修改url，并增加关闭按钮
**现状及问题**
当前点击图片放大预览，会将页面url修改为/preview-image，并且弹出的预览大图页面没有关闭按钮，有用户在这个页面会不知所措，并尝试刷新页面，但这个路由不存在，刷新后就直接404了。
**尝试方案**
已尝试自定义h5预览功能，但因为跟其他端代码不一致，开发时多了一些麻烦。

**Comment by fxy060608** [comment]
uni.previewImage 从规范来说，是打开新窗口预览图片，要触发页面 onHide 生命周期的。
刷新 404？没发现这个问题，参考示例：https://uniapp.dcloud.io/h5/pages/API/image/image
刷新后会不显示任何图片，但点击仍会返回前一个页面
稍后优化刷新带来的体验问题

**Comment by zhangyanzt** [comment]
需要部署的时候通过url重写规则做兼容，我们线上的项目因为url重写规则比较多，为避免冲突，只重写了pages下的页面，所以出现这个问题，已经做了兼容处理，能解决刷新问题那更好。
