### ISSUE TITLE
computed计算属性，如果跳转其他页面再返回，computed是不执行的

### ISSUE THREAD

**Issue by HoldSkill** [dcloudio/uni-app#73]
如题，computed计算属性，如果跳转其他页面再返回，computed是不执行的

**Comment by zxzhgk** [comment]
这是一个坑 ，包括watch  同一个组件第二次进入就会不执行，希望官方能赶快修复

**Comment by zxzhgk** [comment]
问题复现步骤：

进入一个页面 这个页面含有watch； 此时watch会正常跟踪对应值的变化

退出页面

再次进入这个页面，此时watch 里的函数不会跟踪对应值的变化

期望的表现：

希望子组件有正常的生命周期，computed,watch 都存在以上问题

观察到的表现：

watch 里的函数在同一组件重复进入后不会跟踪对应值的变化，computed也一样

屏幕截图或动态图：


![image.png](https://upload-images.jianshu.io/upload_images/3356839-d8edb72e181fd5db.png?imageMogr2/auto-orient/strip%7CimageView2/2/w/1240)

再次进入页面后，无法触发watch

**Comment by zxzhgk** [comment]
watch  不执行的暂时解决办法
在onLoad  钩子中手动执行 watch

**Comment by HoldSkill** [comment]
mpVue不会有这个问题的

**Comment by zxzhgk** [comment]
@HoldSkill mpvue 详情跳详情目前也有这个问题

**Comment by q310550690** [comment]
说到底就是页面返回后并不会销毁组件导致的

**Comment by xiaoyucoding** [comment]
- [uni-app 1.8发布，微信端性能翻倍，并增加若干 Vue 语法支持](https://ask.dcloud.net.cn/article/35699)
- [uni-app 1.9发布，App平台升级为自定义组件模式，支持更多Vue语法](https://ask.dcloud.net.cn/article/35818)

相应的平台，启用自定义组件模式 `usingComponents: true` 即可。
