### ISSUE TITLE
自定义基座，键盘不会把页面顶上去

### ISSUE THREAD

**Issue by zhangzhenfei** [dcloudio/uni-app#730]
**问题描述**
自定义基座，键盘不会把页面顶上去
使用标准默认基座，键盘是可以吧页面顶上去的，并且云打包后，也不会吧页面顶上去

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [5+ App]
 - 操作系统 [Android 8.1]
 - HBuilderX版本 [2.2.4.20190823-alpha]
 - 设备信息 [小米]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
你是想使用adjustResize模式吗？

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
