### ISSUE TITLE
HBuilderX升级2.2版本后，APP总是报错自动重启

### ISSUE THREAD

**Issue by foxantony360** [dcloudio/uni-app#734]
**问题描述**
做了一个直播播放页面，直播播放页面使用到了subNvue，第一次打开页面时正常，退出观看直播，再打开这个页面，就报以下异常了，并且APP自动重启，此问题不断的复现，在官方社区也看到很多人遇到了此问题，但是没有一个明确的解决办法，
16:02:28.990 02:24.018 11817 12142 E console : [ERROR] reportJSException >>>> exception function:callReportCrash, exception:weex core process crash and restart exception
16:02:29.283 Error: [JS Framework] Failed to receiveTasks, instance (1) is not available.
16:02:29.306 Error: [JS Framework] Failed to receiveTasks, instance (5) is not available.
16:02:29.320 Error: [JS Framework] Failed to receiveTasks, instance (4) is not available.
16:02:29.428 Error: [JS Framework] Using invalid instance id "1" when calling destroyInstance.
16:02:29.451 Error: [JS Framework] Using invalid instance id "4" when calling destroyInstance.
16:02:29.468 Error: [JS Framework] Using invalid instance id "5" when calling destroyInstance.
16:02:29.492 Error: [JS Framework] Failed to receiveTasks, instance (1) is not available.

**系统信息:**
 HbuildX版本：2.2.1.20190813

还会报以下错误：

17:29:04.310 28:59.736 13669 15389 E console : [ERROR] reportJSException >>>> exception function:callReportCrash, exception:weex core process crash and restart exception
17:29:04.661 Service "weexPlus" has been registered already!
17:29:04.694 Service "UniApp" has been registered already!
17:29:04.710 Error: [JS Framework] Using invalid instance id "18" when calling destroyInstance.
17:29:04.725 Error: [JS Framework] Using invalid instance id "21" when calling destroyInstance.
17:29:04.745 Error: [JS Framework] Using invalid instance id "22" when calling destroyInstance.

**Comment by MonaLudo** [comment]
HBuilder很垃圾的！！！

**Comment by libojacky** [comment]
2.3.2.20190921
使用subNvue 依然有问题
Error: [JS Framework] Failed to receiveTasks, instance (2) is not available.

**Comment by dcloudhdx** [comment]
更新 HBuilderX 到最新版

**Comment by dcloudhdx** [comment]
因问题长时间没有回复，暂时关闭

**Comment by yao631029659** [comment]
已经更新了,还是这样.

**Comment by linilini** [comment]
我这也是，一直不停的报这个错Error: [JS Framework] Failed to receiveTasks, instance (2) is not available.

**Comment by MrccoHHH7** [comment]
2022年了，我也遇到了这个问题。。。。。。

**Comment by zhetengbiji** [comment]
> 2022年了，我也遇到了这个问题。。。。。。

一样的错误吗？

**Comment by Rayzworld** [comment]
3.8.12 遇到这个问题

**Comment by 3129430571** [comment]
2024年了，还是一样的错误
