### ISSUE TITLE
picker为啥不能修改样式了

### ISSUE THREAD

**Issue by pog2g** [dcloudio/uni-app#735]
picker为啥不能自定义样式，，这种需求很多啊。。
比如整个app背景是黑色，，一个picker，死白色(一颗老鼠shi坏了一锅汤)。

官方好多组件样式都很弱，虽说html很方便，，但uniapp看来也不是很方便到哪啊。很多常用组件要么还没原生多，要么自定义带来各种问题(一个平台可以一个平台不可以。问题一大堆)

做兼容所有系统，带来各种问题。还不如专心搞好常用的系统。。想通吃哪来那么容易，东抓一点西抓一点搞到最后没一个好的。。。。

**Comment by zhetengbiji** [comment]
由于内置picker是原生组件（除H5平台），所以不能自定义样式
可以使用第三方picker组件：[https://ext.dcloud.net.cn/search?q=picker](https://ext.dcloud.net.cn/search?q=picker)
