### ISSUE TITLE
微信H5 模式下动态修改document.title属性的问题

### ISSUE THREAD

**Issue by wLeeming** [dcloudio/uni-app#737]
**新功能描述**
问题来源: H5平台 优化 自动修改 document.title 为 navigationBarTitleText 的值 #394
期望功能: 希望通过配置或接口,由开发者自己决定是否要自动修改 document.title

**现状及问题**
我们是一个微信H5商城, 需要让标题显示为一个固定的值(比如:XXX商城), 不想跟随
navigationBarTitleText变化. 

**尝试方案**
1.尝试在页面的onShow方法中设置document.title,可以实现需求,但冗余代码过多
2.在路由插件的后置钩子函数中修改document.title, 会有闪烁的问题

**Comment by fxy060608** [comment]
如果 onShow 可以解决的，全局加个 mixin 就行了，不用每个页面写 onShow

**Comment by StrivingRabbit** [comment]
由于长时间未回复，此问题关闭，如果还有问题可以重开或者提新issue
