### ISSUE TITLE
map组件show-location属性有问题

### ISSUE THREAD

**Issue by bigGoodMan** [dcloudio/uni-app#738]
**问题描述**
map组件show-location在微信公众号网页上定位不显示

**复现步骤**
`<map id="mymap" :longitude="longitude" :latitude="latitude" scale="14" :markers="markers" @markertap="markertap"
		 show-location :style="{width: '100%', height: kHeight+'px'}">
		</map>`
`wx.ready(function() {
				wx.getLocation({
					type: 'gcj02', // 默认为wgs84的gps坐标，如果要返回直接给openLocation用的火星坐标，可传入'gcj02'
					success: function(res) {
							var latitude = res.latitude;
							var longitude = res.longitude;
							console.log('成功：', latitude, longitude) // 拿到坐标
							that.setData({
								latitude: latitude,
								longitude: longitude
							});
					},
					fail: function(res) {
						that.setData({
							latitude: 30.274725,
							longitude: 120.103280
						});
					}
				});`

**预期结果**
用户当前的位置

**实际结果**
不显示

**系统信息:**
 - 发行平台: [微信h5]
 - 操作系统 [所有]
 - HBuilderX版本 [2.0.1.20190614]
 - 设备信息 [所有]

**补充信息**

**Comment by Wangyaqi** [comment]
```wx.ready```写在哪里了

**Comment by bigGoodMan** [comment]
> `wx.ready`写在哪里了

这个定位没有调用微信的api吧，这是直接用腾讯地图的api调的地图。（我试过 用微信获得的坐标赋值到longitude，latitude，依然是没用）。但是我刷新当前页面就可以，我是单页面的，从其它要么进来获得不到位置。

**Comment by zhetengbiji** [comment]
1. 需要 https 协议
2. 需要配置腾讯地图 key
