### ISSUE TITLE
app与webview实时通讯

### ISSUE THREAD

**Issue by Sunrise1970** [dcloudio/uni-app#739]
**新功能描述**
希望能提供app与webview实时通讯的方法

**现状及问题**
网页向应用 postMessage 时，会在特定时机（后退、组件销毁、分享）触发并收到消息。只能在这几个时机触发，但是实际业务很多都是要在当前页面完成的，而不是后退一页触发回调。

**尝试方案**
目前是在发送消息时，重定向到webview，这样就可以粗发回调，但是这样要重新刷新一下webeiw。
toMessage () {
      window.uni.postMessage({
        data: {
          action: 'message'
        }
      })
      window.uni.redirectTo({
        url: 'login'
      })
    }

**Comment by dcloudhdx** [comment]
V3编译已支持(见 manifest 配置)，nvue web-view支持
