### ISSUE TITLE
上传图片demo中，第二次上传会显示找不到图片路径

### ISSUE THREAD

**Issue by kerwin-cn** [dcloudio/uni-app#74]
上传图片那个demo

代码

             uni.chooseImage({
                    count: 1,
                    sourceType: ['album'],
                    sizeType: ['compressed'],
                    success: (res) => {
                        var imageSrc=res.tempFilePaths[0];
                        console.log('chooseImage success, temp path is', imageSrc)
                        
                        
                        uni.uploadFile({
                            filePath: imageSrc,
                            header:{
                                'Accept': 'application/json',
                                'Authorization':'Bearer '+ XXX
                            },
                            url: 'XXXXX',//这里用官方demo的就可以反复上传，用自己的地址就只能一次，自己的接口反复测试无问题！
                            name: 'image',
                            success: (res) => {
                                console.log('uploadImage success, res is:', res)
                                uni.showToast({
                                    title: '上传成功',
                                    icon: 'success',
                                    duration: 1000
                                })
                                this.imageSrc = imageSrc
                            },
                            fail: (err) => {
                                console.log('uploadImage fail', err);
                                uni.showModal({
                                    content:err.errMsg,//这里报错 filePath 文件地址为空
                                    showCancel:false
                                })
                            },
                        }）

                    },
                    fail: (err) => {
                        console.log('chooseImage fail', err)
                    }
                })

控制台结果
> 11:10:35.824
 [LOG] : chooseImage success, temp path is _doc/uniapp_temp/compressed/1540782634871.JPG

现象就是第一次上传可以，第二次上传就不可以了，用官方demo的上传接收地址可以反复上传，换了自己的上传url地址就只能成功一次，报错地址显示filePath为空

**Comment by hulinNeil** [comment]
这是hello uniapp 里上传demo 的服务端文件，你放到你服务器试试：https://github.com/dcloudio/H5P.Server/blob/master/uploader/index.php

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
