### ISSUE TITLE
icon图标不显示

### ISSUE THREAD

**Issue by harleybox** [dcloudio/uni-app#740]
使用官方组件uni-icon
<uni-icon type="contact" size="24" color="#808080"></uni-icon>

ios真机和模拟器中不显示，H5模拟器中可以显示

**Comment by Wangyaqi** [comment]
你用的是哪里来的uni-ui

**Comment by harleybox** [comment]
https://uniapp.dcloud.io/extendUI?id=icon-%e5%9b%be%e6%a0%87

import uniIcon from "@/components/uni-icon.vue"
export default {
    components: {uniIcon}
}

<uni-icon type="contact" size="30"></uni-icon>

按照官方文档

**Comment by Wangyaqi** [comment]
把你的代码打包一下发上来吧，这个页面你是搜索进去的吗，这个已经是旧的废弃了，插件市场上的文档比较新一些，最近可能会有一次整体的更新 [https://ext.dcloud.net.cn/plugin?id=28](https://ext.dcloud.net.cn/plugin?id=28)

**Comment by harleybox** [comment]
这个组件已经废弃了？还是所有的extendUI都废弃了，我看官方的demo里面不都有吗

**Comment by Wangyaqi** [comment]
这个文档已经废弃了，组件还能用

**Comment by harleybox** [comment]
ok,明白，谢谢
