### ISSUE TITLE
fields方法出现的问题

### ISSUE THREAD

**Issue by jwhklk** [dcloudio/uni-app#742]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1， 复制下面到吗到某个组件的methods
2，组件加载的时候调用改方法
3、在支付宝小程序运行该组件

[或者可以直接贴源代码]
let view = uni.createSelectorQuery().select("#sss");
view.fields({size: true}, function(data){
              console.log(data);
}).exec();
**预期结果**
输入相应节点的对应的尺寸信息

**实际结果**
TypeError: execCallback is not a function

**系统信息:**
 - 发行平台: [ 如 支付宝小程序，运行平台支付宝开发者工具0.60.12 (0.60.12)  ]

**Comment by Wangyaqi** [comment]
不要把exec跟上半句分开
```
view.fields({
size: true
}, function(data){
console.log(data);
}).exec();
```
这么才是正确的

**Comment by jwhklk** [comment]
> 不要把exec跟上半句分开
> 
> ```
> view.fields({
> size: true
> }, function(data){
> console.log(data);
> }).exec();
> ```
> 
> 这么才是正确的

代码贴错了，跟后面也是一样效果，你可以再支付宝开发者工具里面看看

**Comment by Wangyaqi** [comment]
没复现出来，我这不会报错，你把代码打包一下发上来，也可以试试先更新一下支付宝开发者工具

**Comment by jwhklk** [comment]
> 没复现出来，我这不会报错，你把代码打包一下发上来，也可以试试先更新一下支付宝开发者工具

https://github.com/jwhklk/uniapp_test_fields.git
下载这个例子，在支付宝开发者工具里面跑一下试试呢

**Comment by jwhklk** [comment]
> 没复现出来，我这不会报错，你把代码打包一下发上来，也可以试试先更新一下支付宝开发者工具

运行后，vendor.js这个文件的第990行exec函数是需要传一个callback参数的，但是调试一下，没传过去，callback参数为空

**Comment by Wangyaqi** [comment]
你的HBuilderX是什么版本

**Comment by jwhklk** [comment]
> 你的HBuilderX是什么版本，我分别用最新的正式版和最新的alpha版都没报错

用了最新的Alpha版，确实没问题，打包的时候vendor.js里面多了一句 
if (isFn(execCallback)) {  execCallback(res); }
好吧，确实可以了
