### ISSUE TITLE
onLoad(option)       option传参异常

### ISSUE THREAD

**Issue by manly0305** [dcloudio/uni-app#743]
<img width="1601" alt="Screen Shot 2019-09-04 at 18 13 48" src="https://user-images.githubusercontent.com/8382355/64246849-2a892b80-cf40-11e9-965b-4984bc88df4a.png">

如图Ios 模拟器下
传递的`='       丢失了   encodeURI     也不能解决

**Comment by Wangyaqi** [comment]
用```encodeURIComponent```

**Comment by manly0305** [comment]
Yes . You are right . I fixed this issue couple days agao .  ```encodeURIComponent``` works
