### ISSUE TITLE
uni.canvasToTempFilePath 在H5下x,y需要乘以pixelRatio

### ISSUE THREAD

**Issue by invinbg** [dcloudio/uni-app#746]
**问题描述**
- uni.canvasToTempFilePath 在H5下x,y需要乘以pixelRatio
-  APP-PLUS环境不需要计算上pixelRatio
- 其他环境下未测试

**复现步骤**
1.  在Canvas上绘画一个正方形
2. 截取相同的位置、大小的图片
3. 查看
```
const ctx = uni.createCanvasContext('myCanvas')
ctx.setFillStyle('red')
ctx.fillRect(canvasL, canvasT, canvasW, canvasH)
ctx.draw()


uni.canvasToTempFilePath({
    x: canvasL,
    y: canvasT,
    width: canvasW,
    height: canvasH,
    quality: 0.8,
    canvasId: 'myCanvas',
    success: function (res) {
        uni.previewImage({
              urls: [res.tempFilePath]
        })
    },
    fail: function(e) {
    }
});
```

**预期结果**
截取的图片应该是红色正方形

**实际结果**
实际x,y没计算上pixelRatio会偏移

1. 绘制矩形
![avatar](http://chuantu.xyz/t6/702/1567662109x1031866013.jpg)

2. canvasToTempFilePath后预览
![avatar](http://chuantu.xyz/t6/702/1567662020x1031866013.jpg)

**Comment by javascriptchen** [comment]
您好，请提供一下相关的测试代码
