### ISSUE TITLE
支付宝小程序view.boundingClientReact.exec()报错

### ISSUE THREAD

**Issue by haluhsu** [dcloudio/uni-app#747]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
HbuilderX版本：20190713
支付宝小程序获取元素高度并执行view.boundingClientReact方法在exec回调时报错

**源代码**
let view = uni.createSelectorQuery().select('.city-index-body');
view.boundingClientRect(data => {
  this.itemTopHeight = data.top
}).exec();

**预期结果**
可以在支付宝端获取元素到顶端的高度

**实际结果**
报错提示：
TypeError:execCallback is not a funciton

**系统信息:**
 - 发行平台: 支付宝小程序
 - 操作系统 ：支付宝开发者工具
 - HBuilderX版本： 20190713
 - uni-app版本: 20190713
 - 设备信息：iphone6

**补充信息**
原因： 打包出来的vender.js里面有个createSelectorQuery方法，其中的query.exec方法必须传入一个callback参数，但是不传就会这样报错，能不能做个兼容?

**Comment by Wangyaqi** [comment]
这个问题已经修复了，用最新的HBuilderX alpha版即可
