### ISSUE TITLE
HBuilder 新闻 demo 在 Google 浏览器上列表滑动不了

### ISSUE THREAD

**Issue by dazeGitHub** [dcloudio/uni-app#749]
**问题描述**
HBuilder 新闻 demo 在 Google 浏览器上列表滑动不了

**复现步骤**
[复现问题的步骤]
运行 HBuilder uniapp 自带的新闻 demo，在 Google 浏览器上列表滑动不了，在 Android 上可以

**预期结果**
列表可以在 google 浏览器上滑动

**实际结果**
列表可以在 google 浏览器上无法滑动

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 Google 76.0.3809.87
 - HBuilderX版本 2.2.2.20190816
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 Google 浏览器

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by javascriptchen** [comment]
请修改\pages\list\list.nvue文件的第344行代码。
```
.scroll-v {
	flex: 1;
	/* #ifndef MP-ALIPAY */
	flex-direction: column;
	/* #endif */
	width: 750upx;
	height: 100%;//加上这句代码
}
```
稍后我们会修复新闻模板这个bug，感谢您提出的问题。
