### ISSUE TITLE
HBuilder 使用的几个建议

### ISSUE THREAD

**Issue by dazeGitHub** [dcloudio/uni-app#750]
**新功能描述**
简洁描述你希望补充完善的增强功能

**现状及问题**
1. uniapp  不同项目运行到安卓手机上会覆盖，难道包名一样？但是在 HBuilder 里找不到设置安卓包名的地方
2. 搜索时搜索的内容标示不明显，默认所有找到的关键字的背景是淡白色，找不到在哪，
3. 文件在左侧无法定位，打开的文件左侧资源管理器没法同步定位，都不知道当前打开的文件在哪，
4. 无法注释多行，在 <template> 节点中如果要注释的一段代码里边已经有注释了，则注释整个代码不好使

**尝试方案**
没有解决方案，很难受

**补充信息**
[其它你认为有参考价值的信息]

**Comment by wanganxp** [comment]
1. 运行的包名是固定的，打包界面自己输入包名。
2. 嗯，深色主题下确实是淡白色，这个还不支持自定义。按F3可置焦，右侧滚动条信息点也有标识
3. 可以点右键-在项目管理器定位，也可以在项目管理器右上角的菜单里选与编辑器总是关联
4. 可以注释多行，ctrl+/是行注释，ctrl+shift+/是块注释。如果你有具体问题，提供明细

**Comment by dazeGitHub** [comment]
好的，谢谢
