### ISSUE TITLE
自定义的vue组件 行为不符合预期

### ISSUE THREAD

**Issue by chaohony** [dcloudio/uni-app#751]
按照官方的教程去使用vue组件, 但是微信小程序端编译出来的代码却没有实现预期的组件化

如下, 我就写了最简单的一个测试样例, 在index页面引入test组件

<img width="787" alt="2" src="https://user-images.githubusercontent.com/29838799/64354781-a794cd80-d032-11e9-8bf4-a4959f7ef46a.png">

这是test组件
<img width="768" alt="3" src="https://user-images.githubusercontent.com/29838799/64354856-c98e5000-d032-11e9-886c-c83a09e03ef7.png">

然后这是微信小程序端显示出来的效果, 正常编译的肯定是不带<test></test>, 因为这个问题导致了其他的一些模块功能错乱, 我跟那些正常实现组件化的代码对比好久没找出不一样的地方.  不知道自己究竟哪里写错了

<img width="806" alt="1" src="https://user-images.githubusercontent.com/29838799/64354935-ea56a580-d032-11e9-83a6-970c88f0f9d6.png">

**Comment by fxy060608** [comment]
没看懂什么意思，截图微信小程序的 wxml 结构不对吗，自定义组件难道不是这样的结构？

**Comment by chaohony** [comment]
> 没见的什么意思，截图微信小程序的wxml结构不对吗，自定义组件难道不是这样的结构？

不是这样的  自定义组件不应该不显示组件的标签名 现在是把<test></test>原样显示出来了

**Comment by fxy060608** [comment]
在小程序上就是这样的，自定义组件会增加一层节点，与 vue 在 h5 上有差异
