### ISSUE TITLE
H5端WebSocket也不支持ArrayBuffer😭

### ISSUE THREAD

**Issue by swiftest0** [dcloudio/uni-app#753]
**问题描述**
文档里只说明App暂不支持ArrayBuffer，但实测H5也不支持
onMessage接收到的数据类型为: Blob

**补充信息**
问题原因：H5端未设置binaryType

另外，App端何时能舍弃plus-websocket，是否有明确开发计划？

**Comment by zhetengbiji** [comment]
进行中，在此之前也可以先使用插件 [plus-websocket](http://ext.dcloud.net.cn/plugin?id=647)

**Comment by zhetengbiji** [comment]
H5 方面的问题更新 HBuilderX 2.2.5.20190907-alpha 即可
