### ISSUE TITLE
二维码扫描是冻屏

### ISSUE THREAD

**Issue by RilyZhang** [dcloudio/uni-app#754]
**问题描述**
二维码扫描是偶尔会出现冻屏现象，在相机界面卡住。点击系统返回键，解析成功。

**复现步骤**
[复现问题的步骤]
1.  点击二维码扫描
2.  调起二维码扫描

[或者可以直接贴源代码]

**预期结果**
扫描二维码并返回解析结果

**实际结果**
相机扫描界面卡死

**系统信息:**
 - 发行平台: App
 - 操作系统 MIUI 10.3.4 | 稳定版
 - HBuilderX版本 2.2.2.20190816
 - 设备信息 Redmi Note 7

**Comment by dcloudhdx** [comment]
更新 HBuilderX 已优化扫码偶现相机无法初始化问题
