### ISSUE TITLE
全局注册组建内部无法触发onPageScroll

### ISSUE THREAD

**Issue by gentlemanMa** [dcloudio/uni-app#757]
**问题描述**
在main.js中注册了一个全局组件，组件内部无法监听onPageScroll，

`onPageScroll(e) {}`

**补充信息**
微信小程序

**Comment by gentlemanMa** [comment]
貌似不是全局组件也不能触发onPageScroll生命周期钩子

**Comment by zhetengbiji** [comment]
页面生命周期需要在页面（页面组件）内使用
