### ISSUE TITLE
`im` 自动滚动到底部有没有良好的解决方案

### ISSUE THREAD

**Issue by d1y** [dcloudio/uni-app#758]
在业务逻辑中(`im`)并没有找到很好的解决方案, 官方会做自动到底部的功能吗?

目前我已知解决方案有

- uni.pageScrollTo :: 不知道怎么玩
- `<scroll-view>`设置高度,设置`scroll-top`

有没有更好的解决方案? 是不是我姿势不对?

**Comment by javascriptchen** [comment]
https://uniapp.dcloud.io/api/ui/scroll?id=pagescrollto
我想了一个hack方法，你可以暂时这样解决
```
uni.pageScrollTo({
    scrollTop: 9999,
    duration: 300
});
```

**Comment by d1y** [comment]
> [uniapp.dcloud.io/api/ui/scroll?id=pagescrollto](https://uniapp.dcloud.io/api/ui/scroll?id=pagescrollto)
> 我想了一个 hack 方法，你可以暂时这样解决
> 
> ```
> uni.pageScrollTo({
>     scrollTop: 9999,
>     duration: 300
> });
> ```

这个方法绝了, 我目前使用的解决方案是使用`<scroll-view>`的`scroll-top`属性配合来食用的

**Comment by javascriptchen** [comment]
用scroll-top，你不是还得设9999吗

**Comment by d1y** [comment]
> 用 scroll-top，你不是还得设 9999 吗

对的, 这里还有一个坑,就是当我更新需要渲染的`list`的时候,设置`9999`是不可用的,这个坑我找了很久都没有解决方案,后来我想到了一个小妙招:

```js
const that = this
setTimeout(()=> {
  that.scrollTop = 9999
}, 200)

```

(在渲染之后,过几秒在执行这个方法就可以解决了)

**Comment by javascriptchen** [comment]
> > 用 scroll-top，你不是还得设 9999 吗
> 
> 对的, 这里还有一个坑,就是当我更新需要渲染的`list`的时候,设置`9999`是不可用的,这个坑我找了很久都没有解决方案,后来我想到了一个小妙招:
> 
> ```js
> const that = this
> setTimeout(()=> {
>   that.scrollTop = 9999
> }, 200)
> ```
> 
> (在渲染之后,过几秒在执行这个方法就可以解决了)

感觉这个需求。。是产品经理设计的问题，哪有让人到底部开始看的。。。你还是用uni.pageScrollTo吧，这个api有个过渡动画会好看一些，你可以放在onReady生命周期里面执行

**Comment by d1y** [comment]
> 感觉这个需求。。是产品经理设计的问题，哪有让人到底部开始看的。。。你还是用 uni.pageScrollTo 吧，这个 api 有个过渡动画会好看一些，你可以放在 onReady 生命周期里面执行

`uni.pageScrollTop` 这个 `api` 我试过,貌似是我姿势的问题, 没有解决我的需求

**Comment by javascriptchen** [comment]
> > 感觉这个需求。。是产品经理设计的问题，哪有让人到底部开始看的。。。你还是用 uni.pageScrollTo 吧，这个 api 有个过渡动画会好看一些，你可以放在 onReady 生命周期里面执行
> 
> `uni.pageScrollTop` 这个 `api` 我试过,貌似是我姿势的问题, 没有解决我的需求

我试过了，是可以这样用的，不行你放在setTimeout里执行试试

**Comment by iQiQif** [comment]
可以用`uni.createSelectorQuery().select('.page')`获取到页面整个高度
延迟100毫秒后用`uni.pageScrollTo`去滚动到获取到的高度位置

**Comment by d1y** [comment]
> 可以用`uni.createSelectorQuery().select('.page')`获取到页面整个高度
> 延迟100毫秒后用`uni.pageScrollTo`去滚动到获取到的高度位置

对的,现在我就是这样解决的,但是为什么要加延时才能生效呢?大佬你知道吗

**Comment by iQiQif** [comment]
> > 可以用`uni.createSelectorQuery().select('.page')`获取到页面整个高度
> > 延迟100毫秒后用`uni.pageScrollTo`去滚动到获取到的高度位置
> 
> 对的,现在我就是这样解决的,但是为什么要加延时才能生效呢?大佬你知道吗

加延迟是因为我的业务需求，你可以去掉试试

**Comment by d1y** [comment]
> > > 可以用`uni.createSelectorQuery().select('.page')`获取到页面整个高度
> > > 延迟100毫秒后用`uni.pageScrollTo`去滚动到获取到的高度位置
> > 
> > 
> > 对的,现在我就是这样解决的,但是为什么要加延时才能生效呢?大佬你知道吗
> 
> 加延迟是因为我的业务需求，你可以去掉试试

如果去掉的话, 就不会生效, 必须要使用 `settimeout(fn, 100)`
