### ISSUE TITLE
动态修改Canvas大小再导出图片并预览，无法修改图片尺寸

### ISSUE THREAD

**Issue by invinbg** [dcloudio/uni-app#760]
**问题描述**
动态修改Canvas大小再导出图片并预览，二次修改大小后绘画的图象大小始终保持第一次生成的图象大小，如果不预览则正常

**复现步骤**
1.  使用`createCanvasContext`创建createCanvasContext
2. `drawImage`绘制图像到画布再`draw`画到 canvas 中
3. `canvasToTempFilePath`导出图象并`previewImage`预览

**预期结果**
每次导出的图象应跟实际改变后的大小一致

**实际结果**
二次修改大小后绘画的图象大小始终保持第一次生成的图象大小

代码如下：
```
const _this = this
const ctx = uni.createCanvasContext('myCanvas', _this);

ctx.drawImage(_this.src, _this.x - _this.cropOffsertX, _this.y - _this.cropOffsertY, _this.imageWidth, _this.imageHeight);
ctx.draw(false, () => {
    uni.canvasToTempFilePath({
        x: _this.x - _this.cropOffsertX,
        y:  _this.y - _this.cropOffsertY,
        width: _this.imageWidth,
        height: _this.imageHeight,
        canvasId: 'myCanvas',
        success: function (res) {
            // 取消预览则正常
            uni.previewImage({
                urls: [res.tempFilePath]
            })
        },
        fail: function(e) {
        }
    }, _this);
})
```

**系统信息:**
 - 发行平台: [H5平台]
 - HBuilderX版本 [2.2.2.20190816]
 - 设备信息 [chrome]

**补充信息**

取消预览则正常，个人判定`previewImage`组件与之冲突

**Comment by javascriptchen** [comment]
请提供可以复现的示例代码

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
