### ISSUE TITLE
微信小程序胶囊按钮,返回和预期不一样,是一个promise

### ISSUE THREAD

**Issue by Joey-996** [dcloudio/uni-app#761]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
uni.getMenuButtonBoundingClientRect()
**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
返回的不是胶囊菜单的信息而是一个promise,状态是等待中

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Wangyaqi** [comment]
`
let menuButtonInfo = uni.getMenuButtonBoundingClientRect()
`
这是个同步接口这么调用，另外HBuilderX版本需要在2.2.5-alpha或更高才能使用

**Comment by Joey-996** [comment]
> `let menuButtonInfo = uni.getMenuButtonBoundingClientRect()`
> 这是个同步接口这么调用，另外HBuilderX版本需要在2.2.5-alpha或更高才能使用
我说呢,十分感谢
