### ISSUE TITLE
在ios8下，进入官方的hello uni-app的实例中，点击不进行跳页

### ISSUE THREAD

**Issue by ZhangyilinCN** [dcloudio/uni-app#763]
手机ios 8  进入官方的hello uni-app中，
点击 内置组件--视图容器 -- view等没有反应，不跳页，
所有的跳页都没有反应。
使用uni-app写的H5页面，在ios8上打开，也是无法跳页

**Comment by zhetengbiji** [comment]
使用的是系统浏览器吗？

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
