### ISSUE TITLE
picker组件 多列选择器 如何修改分隔符为空格

### ISSUE THREAD

**Issue by 1249682741** [dcloudio/uni-app#764]
如题， 我想将picker组件的多列选择器的分隔符由逗号修改为 空格。 该如何修改。修改大神们能够指点一下

**Comment by javascriptchen** [comment]
猜了一下你是意思，你是想进行把‘1,2,3’转化成'1 2 3'吗？
如果我猜对了，那解决方法很简单
let str = ‘1,2,3’.split(',').join(' ');//‘1 2 3’

**Comment by 1249682741** [comment]
很抱歉， 突然发现是我在用这个picker的组件时写的代码有问题。
`<picker 
    class="picker" 
    mode="multiSelector" 
    :range="data" 
    value="multiIndex" 
    range-key="name" 
    @columnchange = "columnchange">
    <view class="uni-input">
          {{data[0][multiIndex[0]].name}} , {{data[1][multiIndex[1]].name}} , {{data[2][multiIndex[2]].name}}
    </view>
</picker>`
原来是我在上面view 标签的显示里面添加了, 导致出现了分隔符。
打扰了，各位大佬
