### ISSUE TITLE
uni.onKeyboardHeightChange在安卓下没有触发！

### ISSUE THREAD

**Issue by hangaoke1** [dcloudio/uni-app#765]
**问题描述**
IOS正常，android下直接不触发事件

**复现步骤**

[或者可以直接贴源代码]

**预期结果**
android下也正常触发事件

**实际结果**
安卓下软键盘弹起，事件不触发

**系统信息:**
 - 发行平台: [5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 8.0]
 - HBuilderX版本 [alpha 2.2.5]
 - uni-app版本 []
 - 设备信息 [小米8]

**补充信息**
安卓端实现bug

**Comment by javascriptchen** [comment]
是这个api吗？https://uniapp.dcloud.io/api/key?id=onkeyboardheightchange

**Comment by javascriptchen** [comment]
方便提交一下测试代码吗？

**Comment by hangaoke1** [comment]
@javascriptchen 

```html
<template>
  <view class=" page-test">
   <input class="u-input" type="text" @focus="handleFocus">
  </view>
</template>

<script>
export default {
  data() {
    return {};
  },
  onReady() {
    uni.onKeyboardHeightChange(res => {
      uni.showToast({
        title: '' + res.height
      })
    })
  },
  methods: {
    handleFocus(event) {
      // console.log(event.detail.height)
      // uni.showToast({
      //   title: '' + event.detail.height
      // })
    }
  }
};
</script>

<style lang="less">
.m-page {
  position: relative;
  width: 750rpx;
  flex: 1;
}
.u-input {
  width: 700rpx;
  border: 1px solid #fff;
  margin:  0 auto;
}
</style>

```

**Comment by hangaoke1** [comment]
@javascriptchen 用的是2.2.5 alpha版本编辑器，同样的代码ios下是正常的，android下未触发键盘事件，同时更新编辑器后右侧出现1px白边，有时间的话也麻烦排查一下

**Comment by hangaoke1** [comment]
@javascriptchen 如果是bug，请确认一下。还有此方法未提供事件监听解除，不知道是不是设计的时候漏了

**Comment by javascriptchen** [comment]
> @javascriptchen 如果是bug，请确认一下。还有此方法未提供事件监听解除，不知道是不是设计的时候漏了

是bug，我们需要找其他组改一下

**Comment by hangaoke1** [comment]
@javascriptchen 好的，感谢跟进

**Comment by hangaoke1** [comment]
@javascriptchen 看到hbuildx更新了，目前还存在的问题 1. android uniapp模式下.vue文件下事件仍然未触发 2. focus回调中参数height的值也是0，不知道能否确认下

**Comment by zhetengbiji** [comment]
> @javascriptchen @hbcui1984 看到hbuilderx更新了，目前还存在的问题
> 
> 1. android vue onKeyboardHeightChange事件仍然未触发
> 2. android vue focus回调中参数height的值为0
> 3. android nvue input的adjust-position属性无效，页面被顶起
> 
> 不知道能否确认下

1、2 应该在 2.2.6-alpha修复了，3 确认在安卓有问题

**Comment by hangaoke1** [comment]
@zhetengbiji 1,2在nvue下是正常了，但是在vue下还是没有生效，还麻烦你们那边确认一下

**Comment by zhetengbiji** [comment]
> @zhetengbiji 1,2在nvue下是正常了，但是在vue下还是没有生效，还麻烦你们那边确认一下

测试vue下正常，你使用的HBuilderX版本多少

**Comment by hangaoke1** [comment]
@zhetengbiji 应该是input上加了:adjust-position="false" 属性后出现1，2无效

**Comment by hangaoke1** [comment]
```html
<template>
  <view class="page-test"><input :adjust-position="false" class="u-input" type="text" @focus="handleFocus" /></view>
</template>

<script>
export default {
  data() {
    return {};
  },
  onReady() {
    uni.onKeyboardHeightChange(res => {
      uni.showToast({
        title: '' + res.height
      });
    });
  },
  methods: {
    handleFocus(event) {
      // uni.showToast({
      //   title: '' + event.detail.height
      // })
    }
  }
};
</script>

<style lang="less">
.m-page {
  position: relative;
  width: 750rpx;
  flex: 1;
}
.u-input {
  position: fixed;
  margin-top: 200rpx;
  margin-left: 25rpx;
  width: 700rpx;
  bottom: 100rpx;
  border: 1px solid #000;
}
</style>

```

**Comment by zhetengbiji** [comment]
> @zhetengbiji 应该是input上加了:adjust-position="false" 属性后出现1，2无效

已确认，感谢反馈

**Comment by zhetengbiji** [comment]
HBuilderX 2.3.0 已修复

**Comment by shengliZhang** [comment]
问题并没有解决啊，依然存在啊。鸿蒙系统的手机都有这个问题。
基座运行是ok的，云打包后 监听就不执行。
@zhetengbiji 

Hbuilder X 3.8.12.20230817

**Comment by zhetengbiji** [comment]
> 问题并没有解决啊，依然存在啊。鸿蒙系统的手机都有这个问题。 基座运行是ok的，云打包后 监听就不执行。 @zhetengbiji
> 
> Hbuilder X 3.8.12.20230817

应该是不同类型的问题，建议单独到社区反馈

**Comment by shengliZhang** [comment]
是同一个问题，我就是想获取键盘的高度。但是键盘的事件就是不执行，包括Input标签上的@focus和@keyboardheightchange事件都不执行。
@zhetengbiji
