### ISSUE TITLE
小程序在v-bind中不支持过滤器 

### ISSUE THREAD

**Issue by ruiyong-lee** [dcloudio/uni-app#767]
**问题描述**
小程序打包的时候，在v-bind中不支持过滤器，直接报错，比如：:class="rawId | formatId"

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
小程序v-bind中支持过滤器

**实际结果**
小程序v-bind中不支持过滤器

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 iOS 13
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
可能编译有问题

**Comment by javascriptchen** [comment]
https://uniapp.dcloud.io/use?id=%e6%a8%a1%e6%9d%bf%e8%af%ad%e6%b3%95
请检查manifest中"usingComponents":false

**Comment by ruiyong-lee** [comment]
@javascriptchen 这个是万能的回答么？？？请注意我的题目，是:class="rawId | formatId"，不是{{rawId | formatId}}

**Comment by Wangyaqi** [comment]
`:class`暂不支持过滤器，请使用methods代替

**Comment by CheJJ** [comment]
> @javascriptchen 这个是万能的回答么？？？请注意我的题目，是:class="rawId | formatId"，不是{{rawId | formatId}}
> ![image](https://user-images.githubusercontent.com/12726826/64606107-0e7e0200-d3f8-11e9-81ff-40350b3f8970.png)

没毛病，点开这个链接，人家支持的写法不是已经列出来了嘛

**Comment by ruiyong-lee** [comment]
@Wangyaqi 目前只能这样，我的意思是未来可能会支持么？

**Comment by ruiyong-lee** [comment]
@CheJJ 这个是vue官网，不是uni-app官网，uni-app官网没写支不支持v-bind

**Comment by CheJJ** [comment]
> @CheJJ 这个是vue官网，不是uni-app官网，uni-app官网没写支不支持v-bind

你是睁着眼说瞎话嘛
<img width="793" alt="WX20190910-184028@2x" src="https://user-images.githubusercontent.com/53925673/64607138-7c2b2d80-d3fa-11e9-970b-a653f4514d2b.png">

**Comment by ruiyong-lee** [comment]
@CheJJ 我说的我的截图是vue官网，他给的链接点进去那个是uni-app官网，里面哪里介绍所谓“人家支持的写法不是已经列出来了嘛”

**Comment by CheJJ** [comment]
> @CheJJ 我说的我的截图是vue官网，他给的链接点进去那个是uni-app官网，里面哪里介绍所谓“人家支持的写法不是已经列出来了嘛”

<img width="816" alt="WX20190910-184125@2x" src="https://user-images.githubusercontent.com/53925673/64607650-7d108f00-d3fb-11e9-9288-9bbe7882f20c.png">

**Comment by Wangyaqi** [comment]
打住打住，问题解决，皆大欢喜

**Comment by ruiyong-lee** [comment]
@CheJJ 算了，我不和你杠了，那是介绍class的写法又不是过滤器，上面也没写不支持过滤器。我都说了H5这样写没问题，H5这样写没问题，H5这样写没问题，就是来问下小程序为什么不行，将来能不能行，就这么简单。

**Comment by zhetengbiji** [comment]
> @CheJJ 算了，我不和你杠了，那是介绍class的写法又不是过滤器，上面也没写不支持过滤器。我都说了H5这样写没问题，H5这样写没问题，H5这样写没问题，就是来问下小程序为什么不行，将来能不能行，就这么简单。

由于其他端非完整的浏览器环境，受运行环境限制，只能提供有限的语法支持
