### ISSUE TITLE
picker-view 默认进入总是选择第一项呢？选择之后再重新选择没问题，但是首次进入页面总是选择第一项！！！

### ISSUE THREAD

**Issue by XinjianQi** [dcloudio/uni-app#768]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by javascriptchen** [comment]
picker-view可以设置默认值的，看下面的网站。
[https://blog.csdn.net/lygzscnt12/article/details/82596713](https://blog.csdn.net/lygzscnt12/article/details/82596713)

**Comment by XinjianQi** [comment]
> picker-view可以设置默认值的，看下面的网站。
> https://blog.csdn.net/lygzscnt12/article/details/82596713

我知道哈，但是用这个二级联动的选择城市的，默认值怎么不行呢？demo好像也不行。

**Comment by javascriptchen** [comment]
您好，方便提供相应的测试代码吗？

**Comment by XinjianQi** [comment]
> 您好，方便提供相应的测试代码吗？

测试代码就是 uni-app demo里的代码

**Comment by javascriptchen** [comment]
我之前试过可以啊，你新建个项目，写个不能设置默认值的demo，我看一下代码怎么写的
