### ISSUE TITLE
为什么不考虑直接支持现有的mpvue项目？

### ISSUE THREAD

**Issue by NextBoy** [dcloudio/uni-app#77]
mpvue项目直接拿来用，要是能支持多好，直接复用

**Comment by wanganxp** [comment]
其实代码是不用改的，主要是改配置，manifest.json和pages.json。
这些配置的增加，一方面是跨端必须的，很多配置必须扩展才能适应不同平台。另一方面是为了简化开发，比如不需要每个页面下都放一个main.js
