### ISSUE TITLE
HBuilderX编辑器打包一直失败

### ISSUE THREAD

**Issue by Mixlong** [dcloudio/uni-app#770]
**问题描述**
更新编辑器后打包存在现象

 
 
**系统信息:**
 - 发行平台: [如 微信小程序]
 

**补充信息**
 
![TIM图片20190912102246](https://user-images.githubusercontent.com/27038897/64749227-65462180-d547-11e9-8ab9-5726ff650c53.png)

**Comment by fxy060608** [comment]
手动删除该目录，然后重新发行

**Comment by dcloudhdx** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
