### ISSUE TITLE
关于内置终端同步代码的问题

### ISSUE THREAD

**Issue by d-ouyang** [dcloudio/uni-app#771]
**问题描述**
两个分支上的代码，feature 分支开发完毕，切换分支进行 merge，存在代码丢失

**复现步骤**
PS：b 分支由 a 分支切出
1.  在 a 分支上补充了部分功能，版本领先于 b 分支
2. 切换到 b 分支， merge a 分支，发现 a 的新功能代码丢失
3. 发现不对劲后切回 a 分支， 新功能代码也不见了
4. 从远程 a 分支拉最新代码，新功能代码也没有
5. 将本地 a 分支代码 放到 vscode，新功能代码存在
6. 关闭 HbuildX， 重新打开， 新功能代码也出现了

[或者可以直接贴源代码]

**预期结果**
切换分支时代码及时更新同步， 不然没注意到，就会将之前的代码 merge 覆盖

**实际结果**
分支代码切换时没有及时更新，需要关闭编辑器才能代码同步

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本  2.2.2.20190816
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by wandali2019** [comment]
目前最新版是2.5.1，请升级。

**Comment by StrivingRabbit** [comment]
由于长时间没有回复，此issue关闭。如果还有问题请重开或者提新issue
