### ISSUE TITLE
README.md的错误别字

### ISSUE THREAD

**Issue by liushuai0109** [dcloudio/uni-app#772]
**问题描述**
这句话的错别字【登陆】->【登录】
![image](https://user-images.githubusercontent.com/674525/64760537-8a00c000-d56c-11e9-96fa-a1f23e0986a8.png)

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
语文没学好

**Comment by SiiZhao** [comment]
哈哈哈，你直接改就行
