### ISSUE TITLE
建议app环境下新增input框在获取焦点的时候默认全选内容

### ISSUE THREAD

**Issue by CuteFakin** [dcloudio/uni-app#773]
**新功能描述**
app环境下新增input框在获取焦点的时候默认全选内容

**现状及问题**
获取焦点的时候没有任何方法可以全选内容，希望新增例如event.currentTarget,selectAll()之类的方法，很多时候app输入框为了用户体验会需要获取焦点就选中内容，用户只需要输入新的值即可，而不用先退格删除input的内容

**Comment by dhcai** [comment]
根你有同样的需求，社区里有人提出来，不知道官方为啥不给解决方案，希望官方人员能实现select()方法

**Comment by CuteFakin** [comment]
> 根你有同样的需求，社区里有人提出来，不知道官方为啥不给解决方案，希望官方人员能实现select()方法

难受的一批，客户提出的需求~

**Comment by CheJJ** [comment]
> > 根你有同样的需求，社区里有人提出来，不知道官方为啥不给解决方案，希望官方人员能实现select()方法
> 
> 难受的一批，客户提出的需求~

什么狗屁的一批两批，看下文档里的selection-start、selection-end能满足你需求不

**Comment by CheJJ** [comment]
> 根你有同样的需求，社区里有人提出来，不知道官方为啥不给解决方案，希望官方人员能实现select()方法

如果n年前人家就解决了呢，问为什么之前最好先确定有没有是不是

**Comment by CuteFakin** [comment]
> > > 根你有同样的需求，社区里有人提出来，不知道官方为啥不给解决方案，希望官方人员能实现select()方法
> > 
> > 
> > 难受的一批，客户提出的需求~
> 
> 什么狗屁的一批两批，看下文档里的selection-start、selection-end能满足你需求不
回答前，能不能自己先看文档清楚？selection-start、selection-end只有在自动聚焦的时候才有用好么？

**Comment by huoshidehua** [comment]
一年多了 也没给解决啊

**Comment by zhetengbiji** [comment]
收到后续会考虑在App、H5端去除“自动聚集时有效”的限制

**Comment by StrivingRabbit** [comment]
已提交至 cb23882

**Comment by StrivingRabbit** [comment]
由于长时间未回复，此issue关闭。如果还有问题可以重开或者提新issue
