### ISSUE TITLE
为使用vue-cli命令行创建的项目提供更新命令

### ISSUE THREAD

**Issue by dupfei** [dcloudio/uni-app#774]
**新功能描述**
为使用vue-cli命令行创建的项目提供更新命令

**现状及问题**
目前更新项目到最新版本都是使用npm、yarn直接更新项目依赖，但是有时候更新之后会运行报错，提示缺少某些依赖。希望增加更新命令，一键更新相关依赖到最新版本。

**Comment by zhetengbiji** [comment]
https://www.npmjs.com/package/@dcloudio/uvm
