### ISSUE TITLE
抖音小程序在app.vue赋值this.$options.globalData后，在页面无法取值

### ISSUE THREAD

**Issue by bluefox1688** [dcloudio/uni-app#780]
**问题描述**
我是把微信小程序迁移到抖音小程序，然后在app.vue的`onLaunch`赋值this.$options.globalData.xxx参数，在某个`pages`的页面使用   `getApp().globalData`获取不到在app.vue赋值的值。

这个是在app.vue的`onLaunch`赋值截图
![image](https://user-images.githubusercontent.com/11862797/64932409-5924d180-d871-11e9-86de-eb2a8e815c9a.png)

在微信小程序是正常的，但在抖音小程序取值失败

**系统信息:**
 - 发行平台: [微信小程序、抖音小程序]
 - HBuilderX版本 [ 2.2.2.20190816 和 2.2.6.20190914-alpha 都测试过 ]

**Comment by javascriptchen** [comment]
你试一下这样声明globalData有没有问题
```html
<script>  
    export default {  
        globalData: {  
            text: 'text'  
        }
    }  
</script>
```
`getApp().globalData.text`这样来取值

**Comment by bluefox1688** [comment]
您好，我已经先定义过了，但还是无法取值

**Comment by javascriptchen** [comment]
您好，方便提供可以复现的测试代码吗？

**Comment by bluefox1688** [comment]
[uni-tt-demo.zip](https://github.com/dcloudio/uni-app/files/3619732/uni-tt-demo.zip)

这个是复现后的测试代码，您跑跑试试

**Comment by bluefox1688** [comment]
![image](https://user-images.githubusercontent.com/11862797/65018990-e98c1080-d95c-11e9-821b-91293844fd38.png)
这是 console 打印的数据，实事上已经在app.vue赋值过的

**Comment by bluefox1688** [comment]
![image](https://user-images.githubusercontent.com/11862797/65019042-04f71b80-d95d-11e9-9ed1-6596042dc966.png)

**Comment by bluefox1688** [comment]
@javascriptchen 您好，有结果了吗？

**Comment by javascriptchen** [comment]
[tt-demo-solute.zip](https://github.com/dcloudio/uni-app/files/3625367/tt-demo-solute.zip)
你先把把对globalData变量的赋值操作放在你的首页也可以吧？头条小程序好像不支持在App.vue中改变globalData。

**Comment by javascriptchen** [comment]
你先把把对globalData变量的赋值操作放在你的首页也可以吧？头条小程序好像不支持在App.vue中改变globalData。
[tt-demo-resolve.zip](https://github.com/dcloudio/uni-app/files/3625418/tt-demo-resolve.zip)

**Comment by bluefox1688** [comment]
嗯嗯，现在只能换一个方式来实现了

**Comment by fxy060608** [comment]
> 嗯嗯，现在只能换一个方式来实现了

this.$options.globalData 换成 this.$scope.globalData

可以把 this.$scope 理解成 getApp()

**Comment by bluefox1688** [comment]
@fxy060608 谢谢，我试试

**Comment by bluefox1688** [comment]
用 `this.$scope.globalData` 确实是可以
那我关闭issues了
