### ISSUE TITLE
开发微信小程序报错

### ISSUE THREAD

**Issue by ben-lau** [dcloudio/uni-app#781]
编译到小程序开发（npm run dev:mp-weixin）后，打开微信开发者工具报错

![image](https://user-images.githubusercontent.com/16952163/64934557-364cea00-d87e-11e9-89e9-97ad68428c24.png)

![image](https://user-images.githubusercontent.com/16952163/64934565-3cdb6180-d87e-11e9-9a25-1ce9339a1b3d.png)

uni-app v2.0.0-22420190823019

Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: ^2.0.0-22420190823019 => 2.0.0-22420190823019
    @dcloudio/uni-h5: ^2.0.0-22420190823019 => 2.0.0-22420190823019 (1.0.0-alpha-22120190814002)
    @dcloudio/uni-mp-alipay: ^2.0.0-22420190823019 => 2.0.0-22420190823019
    @dcloudio/uni-mp-baidu: ^2.0.0-22420190823019 => 2.0.0-22420190823019
    @dcloudio/uni-mp-qq: ^2.0.0-22420190823019 => 2.0.0-22420190823019
    @dcloudio/uni-mp-toutiao: ^2.0.0-22420190823019 => 2.0.0-22420190823019
    @dcloudio/uni-mp-weixin: ^2.0.0-22420190823019 => 2.0.0-22420190823019
    @dcloudio/uni-stat:  2.0.0-22420190823019
    @dcloudio/uni-template-compiler: ^0.9.183 => 0.9.183
    @dcloudio/vue-cli-plugin-hbuilderx: ^1.0.137 => 1.0.137
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-22420190823019 => 2.0.0-22420190823019
    @dcloudio/vue-cli-plugin-uni-optimize: ^0.1.9 => 0.1.9
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-22420190823019 => 2.0.0-22420190823019
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-22420190823019 => 2.0.0-22420190823019
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.11.0
    @vue/babel-preset-jsx:  1.1.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.11.0
    @vue/cli-plugin-babel: ^3.11.0 => 3.11.0
    @vue/cli-service: ^3.11.0 => 3.11.0
    @vue/cli-shared-utils:  3.11.0
    @vue/component-compiler-utils:  3.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.1
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
    vuex-persistedstate: ^2.5.4 => 2.5.4
  npmGlobalPackages:
    @vue/cli: Not Found

**Comment by ben-lau** [comment]
换回旧版就没问题  代码没动

uni-app v2.0.0-22420190823019

Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i3-4160 CPU @ 3.60GHz
  Binaries:
    Node: 10.15.3 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.11.3 - C:\Program Files\nodejs\npm.CMD
  Browsers:
    Edge: 44.18362.267.0
  npmPackages:
    @dcloudio/uni-app-plus: * => 0.0.253
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: * => 0.2.994
    @dcloudio/uni-h5: ^0.8.0 => 0.8.0 (1.0.0-alpha-22120190814002)
    @dcloudio/uni-mp-alipay: 0.0.827 => 0.0.827
    @dcloudio/uni-mp-baidu: * => 0.0.857
    @dcloudio/uni-mp-qq: 0.0.111 => 0.0.111
    @dcloudio/uni-mp-toutiao: 0.0.351 => 0.0.351
    @dcloudio/uni-mp-weixin: * => 0.0.973
    @dcloudio/uni-stat:  2.0.0-22420190823019
    @dcloudio/uni-template-compiler: * => 0.9.183
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 1.0.137
    @dcloudio/vue-cli-plugin-uni: latest => 2.0.0-22420190823019
    @dcloudio/vue-cli-plugin-uni-optimize: latest => 0.1.9
    @dcloudio/webpack-uni-mp-loader: ^0.3.643 => 0.3.644
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: * => 0.2.875
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.11.0
    @vue/babel-preset-jsx:  1.1.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.11.0
    @vue/cli-plugin-babel: ^3.5.1 => 3.11.0
    @vue/cli-service: ^3.9.0 => 3.11.0
    @vue/cli-shared-utils:  3.11.0
    @vue/component-compiler-utils:  3.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.1
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
    vuex-persistedstate: ^2.5.4 => 2.5.4
  npmGlobalPackages:
    @vue/cli: Not Found

**Comment by fxy060608** [comment]
查看 package.json 中 regenerator-runtime 的版本号，锁定为：0.12.1，然后测试

**Comment by ben-lau** [comment]
> 查看 package.json 中 regenerator-runtime 的版本号，锁定为：0.12.1，然后测试

可以了  测试通过

但是有个问题

![image](https://user-images.githubusercontent.com/16952163/64943704-10840d00-d89f-11e9-86a7-73619538723f.png)
你们的依赖包版本号能不能统一一下  我这里查到这三个包最新的是这个版本号  更新后（删除lock更新）运行build:h5报错
![image](https://user-images.githubusercontent.com/16952163/64943786-3d382480-d89f-11e9-8bfe-2126575f0532.png)

改回成这样就没问题了
![image](https://user-images.githubusercontent.com/16952163/64943810-4c1ed700-d89f-11e9-9f0d-e6059260987c.png)

你们的依赖包可以统一只依赖一个或者统一下版本号比较好  不然很难更新

**Comment by fxy060608** [comment]
版本已经统一了，你是怎么更新成这样的版本的？npm update？
新创建的项目，版本应该都是一致的。

**Comment by ben-lau** [comment]
vscode填写依赖版本时会有提示的  就是说拿到这个版本号是你们在npm发布的最新版本

![image](https://user-images.githubusercontent.com/16952163/64946571-c2263c80-d8a5-11e9-936f-2e3359ac8b6d.png)
![image](https://user-images.githubusercontent.com/16952163/64946662-eeda5400-d8a5-11e9-8f15-1ee5c84972dc.png)


我不可能你们每次升级我都重新创建项目吧  我会手动在package里看看这个版本号是否最新

**Comment by fxy060608** [comment]
那三个版本不一致的库已调整

**Comment by lemonwong** [comment]
> > 查看 package.json 中 regenerator-runtime 的版本号，锁定为：0.12.1，然后测试
> 
> 可以了 测试通过
> 
> 但是有个问题
> 
> ![image](https://user-images.githubusercontent.com/16952163/64943704-10840d00-d89f-11e9-86a7-73619538723f.png)
> 你们的依赖包版本号能不能统一一下 我这里查到这三个包最新的是这个版本号 更新后（删除lock更新）运行build:h5报错
> ![image](https://user-images.githubusercontent.com/16952163/64943786-3d382480-d89f-11e9-8bfe-2126575f0532.png)
> 
> 改回成这样就没问题了
> ![image](https://user-images.githubusercontent.com/16952163/64943810-4c1ed700-d89f-11e9-9f0d-e6059260987c.png)
> 
> 你们的依赖包可以统一只依赖一个或者统一下版本号比较好 不然很难更新

请问一下  你是怎么使用的vuex-persistedstate  我的在微信小程序上会提示 Invalid storage instance given
`export default new Vuex.Store({
	state,
	getters,
	mutations,
	actions,
	plugins: debug ? [createLogger(), createPersistedState({
		reducer: (persistedState) => {
			const stateFilter = Object.assign({}, persistedState);
			const blackList = ["imgIdFace"];
			blackList.forEach((item) => {
				delete stateFilter[item];
			});
			return stateFilter;
		}
	})] : [createPersistedState({
		reducer: (persistedState) => {
			const stateFilter = Object.assign({}, persistedState);
			const blackList = ["imgIdFace"];
			blackList.forEach((item) => {
				delete stateFilter[item];
			});
			return stateFilter;
		}
	})]
});`

**Comment by ben-lau** [comment]
> 请问一下 你是怎么使用的vuex-persistedstate 我的在微信小程序上会提示 Invalid storage instance given
> `export default new Vuex.Store({ state, getters, mutations, actions, plugins: debug ? [createLogger(), createPersistedState({ reducer: (persistedState) => { const stateFilter = Object.assign({}, persistedState); const blackList = ["imgIdFace"]; blackList.forEach((item) => { delete stateFilter[item]; }); return stateFilter; } })] : [createPersistedState({ reducer: (persistedState) => { const stateFilter = Object.assign({}, persistedState); const blackList = ["imgIdFace"]; blackList.forEach((item) => { delete stateFilter[item]; }); return stateFilter; } })] });`

头皮发麻  这你都能看到
我这边用可以直接用  但是我配置了getItem setItem getState setState reducer
直接用的时候也没发现问题
