### ISSUE TITLE
IntersectionObserver报错

### ISSUE THREAD

**Issue by Andyliwr** [dcloudio/uni-app#783]
**问题描述**
使用IntersectionObserver运行h5一直报Cannot read property 'bottom' of null错误
使用方法是按照官方文档来写的
![image](https://user-images.githubusercontent.com/12456160/65001600-c04e8e80-d922-11e9-9e47-6c7f1d11a988.png)

**预期结果**
不报错

**实际结果**
![image](https://user-images.githubusercontent.com/12456160/65001625-e4aa6b00-d922-11e9-9f06-a8a9eae35cb2.png)
![image](https://user-images.githubusercontent.com/12456160/65001645-fb50c200-d922-11e9-8dce-2d7bdf0b5a76.png)

**Comment by javascriptchen** [comment]
你好，请提供一份可以复现的示例代码，来进行测试

**Comment by dcloudhdx** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
