### ISSUE TITLE
weex模块 最小集成方案是什么 集成到现有App内

### ISSUE THREAD

**Issue by tzh2017** [dcloudio/uni-app#784]
如题

**Comment by javascriptchen** [comment]
weex集成到安卓 [https://weex.apache.org/zh/guide/develop/integrate-to-android-app.html#_1-%E8%AE%BE%E7%BD%AEgradle%E4%BE%9D%E8%B5%96](https://weex.apache.org/zh/guide/develop/integrate-to-android-app.html#_1-%E8%AE%BE%E7%BD%AEgradle%E4%BE%9D%E8%B5%96)

weex集成到ios [https://weex.apache.org/zh/guide/develop/integrate-to-iOS-app.html](https://weex.apache.org/zh/guide/develop/integrate-to-iOS-app.html)

**Comment by tzh-goon** [comment]
uniapp nvue 需要添加别的依赖么

**Comment by wanganxp** [comment]
原生App集成uni-app的nvue页面，内嵌5+SDK：
https://ask.dcloud.net.cn/article/81
https://ask.dcloud.net.cn/article/84

**Comment by tzh-goon** [comment]
uniapp-release.aar 这个包源码有么，有些我们没有使用fresco，需要自己重新打包

**Comment by tzh-goon** [comment]
你好 我希望使用uniapp nvue能力，但是不需要5+能力，该如何集成呢？

**Comment by tzh-goon** [comment]
有人在么

**Comment by zhetengbiji** [comment]
> 你好 我希望使用uniapp nvue能力，但是不需要5+能力，该如何集成呢？

uni-app 是基于5+的，框架内部很多地方都有用到5+的能力，所以不能釜底抽薪的去掉。

**Comment by StrivingRabbit** [comment]
由于长时间未回复，此问题关闭，如果还有问题可以重开或者提新issue
