### ISSUE TITLE
为什么page的onshow周期执行在vue的beforeMount之前呢

### ISSUE THREAD

**Issue by monkeyMall** [dcloudio/uni-app#787]
在编译成字节跳动小程序时，page的onshow周期执行在vue的beforeMount之前

**Comment by fxy060608** [comment]
onShow 本来就应该在 beforeMount 之前吧，另外这是两套生命周期规范，尽量不要混搭使用

在 page 里，尽量不要混搭使用小程序生命周期和 vue 生命周期
page 里边统一使用小程序生命周期
组件 里统一使用 vue 生命周期
