### ISSUE TITLE
video组件中的show-progress 无效

### ISSUE THREAD

**Issue by Yvan0329** [dcloudio/uni-app#788]
**问题描述**

使用uniapp中video组件的时候，通过show-progress设置video的进度条显示隐藏并没有效果，看源码也没有进行v-if的判断，我想隐藏播放条，不让用户点击播放条。

**复现步骤**
无

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 [Android 9.0]
 - HBuilderX版本 2.22
 - 设备信息 红米

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by maikechen729** [comment]
setStyles: 设置视频播放控件参数

**Comment by dcloudhdx** [comment]
Bug 已修复，下次发版生效

**Comment by ArrayDC** [comment]
HBuilderX2.3.4（alhpa）版本已修复此问题
