### ISSUE TITLE
uni-app有办法引入第三方原生sdk吗

### ISSUE THREAD

**Issue by kai0754** [dcloudio/uni-app#79]
就是想问问在项目中能不能引入第三方的原生sdk。毕竟有些sdk比较冷门。谢谢。

**Comment by hbcui1984** [comment]
uni-app支持原生SDK的方式接入，详细参考：https://ask.dcloud.net.cn/docs/#//ask.dcloud.net.cn/article/104

**Comment by kai0754** [comment]
我知道了，是将uniapp写的变成一个sdk用于引入。但其实我是想要将uniapp写的作为一个主题，从而引入其他的sdk。不过好像是不可以实现的，目前没有看到有什么办法。值得一说的是，现在我们有个项目用了uniapp，效果是惊艳的，并且我在我12年买的小米1（刷了安卓4的系统）上跑了而且还挺流畅的。niubility啊。
