### ISSUE TITLE
支付宝小程序使用自定义组件 ide报错

### ISSUE THREAD

**Issue by chen-can** [dcloudio/uni-app#790]
在 IDE 中的 详情 > 项目配置 中，勾选 启用 component2 编译 。
使用最新基础库1.18.3 在mycomponents 放入vant-ailapp 中的dist 文件
报出以下错误
TypeError: Cannot read property 'mountedHandles' of undefined
    at Object.didMount (http://127.0.0.1:53737/index.worker.js?t=1568796559287:18457:82)
    at http://127.0.0.1:53737/index.worker.js?t=1568796559287:17322:24
    at Array.forEach (<anonymous>)
    at Object.ctx.(anonymous function) (http://127.0.0.1:53737/index.worker.js?t=1568796559287:17321:31)
    at g (http://127.0.0.1:52044/1.18.3/af-appx.worker.ide.min.js:7:62991)
    at o.i.componentDidMount (http://127.0.0.1:52044/1.18.3/af-appx.worker.ide.min.js:7:65402)
    at zr (http://127.0.0.1:52044/1.18.3/af-appx.worker.ide.min.js:24:50136)
    at Fr (http://127.0.0.1:52044/1.18.3/af-appx.worker.ide.min.js:24:47604)
    at Nr (http://127.0.0.1:52044/1.18.3/af-appx.worker.ide.min.js:24:47108)
    at Object.batchedUpdates (http://127.0.0.1:52044/1.18.3/af-appx.worker.ide.min.js:24:53461)
setTimeout (async)
e.setTimeout @ af-appx.worker.ide.min.js:7
console.error @ bridge.js:1
En @ af-appx.worker.ide.min.js:24
Ln.o.function.o.componentDidCatch.n.callback @ af-appx.worker.ide.min.js:24
ht @ af-appx.worker.ide.min.js:24
gt @ af-appx.worker.ide.min.js:24
zr @ af-appx.worker.ide.min.js:24
Fr @ af-appx.worker.ide.min.js:24
Nr @ af-appx.worker.ide.min.js:24
batchedUpdates @ af-appx.worker.ide.min.js:24
K @ af-appx.worker.ide.min.js:7
renderVDOM @ af-appx.worker.ide.min.js:7
(anonymous) @ af-appx.worker.ide.min.js:7
runBatch @ af-appx.worker.ide.min.js:7
updateVDOM @ af-appx.worker.ide.min.js:7
initComponents @ af-appx.worker.ide.min.js:7
preload @ af-appx.worker.ide.min.js:7
load @ af-appx.worker.ide.min.js:7
(anonymous) @ af-appx.worker.ide.min.js:7
(anonymous) @ af-appx.worker.ide.min.js:7
Promise.then (async)
R @ af-appx.worker.ide.min.js:7
L @ af-appx.worker.ide.min.js:7
(anonymous) @ af-appx.worker.ide.min.js:7
(anonymous) @ bridge.js:1
document.dispatchEvent @ bridge.js:1
(anonymous) @ VM103:1
WebFrame.(anonymous function) @ VM101 web-frame.js:56
electron.ipcRenderer.on @ VM83 web-frame-init.js:36
emit @ VM18 events.js:182
[WORKER] onerror (5) ["Cannot read property 'mountedHandles' of undefined", "", 0, 0, TypeError: Cannot read property 'mountedHandles' of undefined
    at Object.didMount (http://127.0.0…]

**Comment by javascriptchen** [comment]
您好，方便提供相应的测试代码吗？

**Comment by chen-can** [comment]
[uni-test.zip](https://github.com/dcloudio/uni-app/files/3625482/uni-test.zip)

**Comment by javascriptchen** [comment]
![image](https://user-images.githubusercontent.com/26818851/65136204-c1261400-da39-11e9-9e13-3fae68ceaefe.png)
无法重现你的问题

**Comment by chen-can** [comment]
@javascriptchen 不好意思忘记在pages.json 加
"usingComponents": {
          "van-button": "/mycomponents/vant/dist/button/index"
        }

**Comment by chen-can** [comment]
请问是不是uni-app支付宝小程序自定义组件都不支持

**Comment by javascriptchen** [comment]
> 请问是不是uni-app支付宝小程序自定义组件都不支持
不是的
你可以用uni-ui，uni-ui支持全端的小程序

**Comment by chen-can** [comment]
@javascriptchen  希望能够支持以下UI组件库
https://ant-move.github.io/vant-ailapp-docs/#/intro
https://ant-move.github.io/iview-alipay-docs/#/docs/guide/start
还有请问下问题复现了吗 有没有什么联系方式我们私聊

**Comment by javascriptchen** [comment]
> @javascriptchen 希望能够支持以下UI组件库
> https://ant-move.github.io/vant-ailapp-docs/#/intro
> https://ant-move.github.io/iview-alipay-docs/#/docs/guide/start
> 还有请问下问题复现了吗 有没有什么联系方式我们私聊
> 
> 我测试过直接吧以上2个放在支付宝小程序都可以正常使用

复现了，
wx:Nowill_2301

**Comment by javascriptchen** [comment]
> @javascriptchen 希望能够支持以下UI组件库
> https://ant-move.github.io/vant-ailapp-docs/#/intro
> https://ant-move.github.io/iview-alipay-docs/#/docs/guide/start
> 还有请问下问题复现了吗 有没有什么联系方式我们私聊
> 
> 我测试过直接吧以上2个放在支付宝小程序都可以正常使用

您好，刚测试过阿里自己的扩展组件库是可以的
[https://docs.alipay.com/mini/component-ext/ui-overview](https://docs.alipay.com/mini/component-ext/ui-overview)
暂时不支持vant-ui的支付宝自定义组件，后续我们会支持。
感谢您的提问。

以下是支付宝小程序扩展组件相关测试代码
[uni-test.zip](https://github.com/dcloudio/uni-app/files/3630049/uni-test.zip)

**Comment by chen-can** [comment]
@javascriptchen 我使用了支付宝小程序扩展组件相关测试代码 发现事件无法绑定
控制台输出：事件信息不存在 我在用vant-ailapp 也出现这样的错误

**Comment by javascriptchen** [comment]
> @javascriptchen 我使用了支付宝小程序扩展组件相关测试代码 发现事件无法绑定
> 控制台输出：事件信息不存在 我在用vant-ailapp 也出现这样的错误

你发你的测试代码我看看，我引入支付宝小程序扩展组件是可以用的啊

**Comment by chen-can** [comment]
@javascriptchen 就是你发给我的包

**Comment by andyWHJ** [comment]
> > @javascriptchen 希望能够支持以下UI组件库
> > https://ant-move.github.io/vant-ailapp-docs/#/intro
> > https://ant-move.github.io/iview-alipay-docs/#/docs/guide/start
> > 还有请问下问题复现了吗 有没有什么联系方式我们私聊
> > 我测试过直接吧以上2个放在支付宝小程序都可以正常使用
> 
> 您好，刚测试过阿里自己的扩展组件库是可以的
> https://docs.alipay.com/mini/component-ext/ui-overview
> 暂时不支持vant-ui的支付宝自定义组件，后续我们会支持。
> 感谢您的提问。
> 
> 以下是支付宝小程序扩展组件相关测试代码
> [uni-test.zip](https://github.com/dcloudio/uni-app/files/3630049/uni-test.zip)

你好，这个zip包里面card组件的点击事件，你可以试一下，会提示事件信息不存在

**Comment by HoHoibin** [comment]
解决了吗

**Comment by mehaotian** [comment]
> > > @javascriptchen 希望能够支持以下UI组件库
> > > https://ant-move.github.io/vant-ailapp-docs/#/intro
> > > https://ant-move.github.io/iview-alipay-docs/#/docs/guide/start
> > > 还有请问下问题复现了吗 有没有什么联系方式我们私聊
> > > 我测试过直接吧以上2个放在支付宝小程序都可以正常使用
> > 
> > 
> > 您好，刚测试过阿里自己的扩展组件库是可以的
> > https://docs.alipay.com/mini/component-ext/ui-overview
> > 暂时不支持vant-ui的支付宝自定义组件，后续我们会支持。
> > 感谢您的提问。
> > 以下是支付宝小程序扩展组件相关测试代码
> > [uni-test.zip](https://github.com/dcloudio/uni-app/files/3630049/uni-test.zip)
> 
> 你好，这个zip包里面card组件的点击事件，你可以试一下，会提示事件信息不存在

目前先这样绕过解决一下,在 `onLoad` 添加如下代码 `this.$scope.cardClick = this.cardClick.bind(this)`

其他组件的其他方法类似 ，先手动把事件绑定到 `this.$scope` 上面

```html
<template>
	<view class="content">
		<image class="logo" src="/static/logo.png"></image>
		<view>
			<text class="title">{{title}}</text>
		</view>
     <card
       :thumb="title"
       title="卡片标题2"
       subTitle="副标题非必填2"
       onClick="cardClick"
       info="点击了第二个card"
     />
	</view>
</template>

<script>
	export default {
		data() {
			return {
				title: 'Hello'
			}
		},
		onLoad() {
			this.$scope.cardClick = this.cardClick.bind(this)
		},
		methods: {
			cardClick(){
				console.log('卡片被点击了');
			}
		}
	}
</script>

```
