### ISSUE TITLE
打包后所有页面都默认开启了页面分享

### ISSUE THREAD

**Issue by qhbhq** [dcloudio/uni-app#792]
**问题描述**

页面没有定义 onShareAppMessage 方法，但是 npm run build 打包后会默认给所有页面加上该方法，npm run serve 开发不会出现该问题

**复现步骤**

npm run serve:mp-weixin 正常：

![image](https://user-images.githubusercontent.com/17266004/65149732-39e69980-da55-11e9-88d0-8b99c7e94014.png)

npm run build:mp-weixin 有问题：

![image](https://user-images.githubusercontent.com/17266004/65149699-29ceba00-da55-11e9-8bf7-337af5060e2d.png)

**预期结果**

npm run build 打包后不应该给所有页面加上 onShareAppMessage 方法

**实际结果**

npm run build 打包后默认给所有页面加上 onShareAppMessage 方法

**系统信息:**

 - 发行平台 微信小程序
 - 操作系统 iOS、Android
 - uni-app 版本 v2.0.0-22420190823021

**Comment by javascriptchen** [comment]
你好，方便提供可以复现的测试代码吗？

**Comment by qhbhq** [comment]
@javascriptchen 

刚又按以下步骤试了一下，可复现：
1. 使用最新的 vue-cli 执行 vue create -p dcloudio/uni-preset-vue my-project
2. 选择默认模版（这里的页面没有定义 onShareAppMessage）
3. npm run build:mp-weixin 后的代码却有 onShareAppMessage

DEMO：[build.zip](https://github.com/dcloudio/uni-app/files/3629176/build.zip)

**Comment by javascriptchen** [comment]
你要用真机调试才能看出效果的，小程序编辑器看的效果是不准确的。
给你看我加了onShareAppMessage跟不加onShareAppMessage的视频跟源码。
[分享.zip](https://github.com/dcloudio/uni-app/files/3629495/default.zip)

**Comment by qhbhq** [comment]
@javascriptchen 

看了你的视频，你是不是在 npm run dev 下看的，那是正常的，build 完就不正常了，真机也是

**Comment by qhbhq** [comment]
@javascriptchen 

这是用你的代码 build 完在真机上的视频
[build-分享.mp4.zip](https://github.com/dcloudio/uni-app/files/3629651/build-.mp4.zip)

**Comment by javascriptchen** [comment]
> @javascriptchen
> 
> 这是用你的代码 build 完在真机上的视频
> [build-分享.mp4.zip](https://github.com/dcloudio/uni-app/files/3629651/build-.mp4.zip)

目前确定了是有这个bug，因为build的代码里面带着onShareAppMessage导致的，我们正在想办法解决，感谢您的反馈。
