### ISSUE TITLE
运行到手机或模拟器中打开调式时post方式的参数丢失

### ISSUE THREAD

**Issue by limaofeng2010** [dcloudio/uni-app#793]
**问题描述**
运行到手机或模拟器时，如果打开调式方式时，post方式的参数丢失在后台接受过程中丢失

**复现步骤**
* 调试方式未打开，当使用post方式时，后端spring boot 会接收到请求参数
* 调试方式打开时，当使用post方式时，后端spring boot 接收到请求参数为“”
* 调试方式打开时，当使用get方式时，后端spring boot 会接收到请求参数为

**系统信息:**
 - 发行平台: [App]
 - 操作系统 [Android 7.0]
 - HBuilderX 2.2.2
 - uni-app版本： 不知
 - 设备信息 redmi 4A

**补充信息**
post时，中间调试工具是否去掉了contentType

**Comment by javascriptchen** [comment]
您好，请问您说的打开调试方式，是HBuilder运行到真机，再点的调试吗？不是调试模式可以收到参数吗？

**Comment by dcloudhdx** [comment]
调试时，暂不支持

**Comment by StrivingRabbit** [comment]
由于长时间未回复，此问题关闭，如果还有问题可以重开或者提新issue
