### ISSUE TITLE
页面滚动存在未知错误(元素闪现,固定定位元素随页面滚动等)

### ISSUE THREAD

**Issue by 401819111** [dcloudio/uni-app#794]
**问题描述**
只有app端有问题,小程序没问题,h5未测试
有一个比较长的列表longList,有一个固定定位的元素item(通过v-show控制显示状态,默认隐藏),
在onPageScroll中监听滚动距离,当距离大于屏幕高度时显示item显示,点击item页面回到顶部(因为高度变小了,所以会再次隐藏)
出现的问题:

点击后item立刻隐藏了(此时还没滚动到小于屏幕高度的位置).
我把滚动时间设置成5秒(方便找原因),发现在某个高度时,这个已隐藏的固定定位元素会随着正在滚动的页面滚动下来(看起来就像没设置固定定位一样)
滚动到最终位置时item会闪一下(出现再消失)

具体的deemo和问题等可以见我在官方论坛提的bug
https://ask.dcloud.net.cn/question/78974

**Comment by zhetengbiji** [comment]
HBuilderX 2.3.2 已修复

**Comment by 401819111** [comment]
> HBuilderX 2.3.2 已修复

还有个类似的错误
https://github.com/dcloudio/uni-app/issues/884#issue-509685070
