### ISSUE TITLE
配置 h5 devServer proxy 无效

### ISSUE THREAD

**Issue by yioMe** [dcloudio/uni-app#796]
编辑器版本 2.3.0.20190919-alpha for mac
配置如下
` "h5" : {
		"router": { "mode": "history", "base": "/" },
        "devServer" : {
            "https" : false,
			"port" : 8080, //端口号
			"disableHostCheck": true,
			"proxy": {
				"/api/*": {
					"target": "http://192.10.110.186:7001/",
					"changeOrigin": true,
					"ws": true,
					"pathRewrite": {
						"^/api": ""
					}
				}
			}
        }
    }`

`getData() {
				uni.request({
					url:"api/test",
				})
			}`

请求时地址没有正确的使用  target 地址

😯是我配置有问题吗

**Comment by yioMe** [comment]
已经解决
`"devServer": {
			"port": 8000,
			"disableHostCheck": true,
			"proxy": {
				"/api": {
					"target": "http://127.0.0.1:1232/api", // 需要跨域的域名
					"changeOrigin": true,
					"secure": false,
					"pathRewrite": {
						"^/api": ""
					}
				}
			}
		}`

**Comment by yoyo837** [comment]
没看出来区别呢
