### ISSUE TITLE
【ios BUG】 ios下webview页面样式不正确

### ISSUE THREAD

**Issue by hangaoke1** [dcloudio/uni-app#797]
**问题描述**
打开baidu页面样式gg

**复现步骤**
index.nvue
```html
<template>
  <view>
     <view @click="handleClick">打开页面</view>
  </view>
</template>

<script>
import { openUrl } from '@/util/index.js'
export default {
  methods: {
   handleClick() {
      openUrl('https://www.baidu.com')
    }
  }
};
</script>
```
util/index.js
```js
export const openUrl = function(url, titletext = '页面') {
  var w = plus.webview.create(url, url, {
    plusrequire:"none",
    top: 0,
    popGesture: "close",
    backgroundColorTop: "#fff",
    backButtonAutoControl: 'close',
    titleNView: {
      autoBackButton: true,
      titletext
    }
  });
  w.show('slide-in-right');
}
```

**预期结果**
ios 下面 baidu页面正常显示

**实际结果**
![image](https://user-images.githubusercontent.com/19623160/65324317-772a6300-dbde-11e9-8f05-cca472199330.png)

**系统信息:**
 - 发行平台: [5+ App]
 - 操作系统 [如 iOS 12.1.2
 - HBuilderX版本 [如使用HBuilderX alpha 2.3.0]
 - 设备信息 [如 iPhoneXR]

**补充信息**
ios bug

**Comment by dcloudhdx** [comment]
下版修复，当前版本解决方案
`
wv = plus.webview.create("","custom-webview",{
	plusrequire:"none", //禁止远程网页使用plus的API，有些使用mui制作的网页可能会监听plus.key，造成关闭页面混乱，可以通过这种方式禁止
	'uni-app': 'none', //不加载uni-app渲染层框架，避免样式冲突
	top:uni.getSystemInfoSync().statusBarHeight+44 //放置在titleNView下方。如果还想在webview上方加个地址栏的什么的，可以继续降低TOP值
})
`
参考文档 https://uniapp.dcloud.io/component/web-view?id=app%e7%ab%afweb-view%e7%9a%84%e6%89%a9%e5%b1%95

**Comment by dcloudhdx** [comment]
HBuilderX 2.3.5+ 已修复
