### ISSUE TITLE
ios 13, hbuild 2.3.1 

### ISSUE THREAD

**Issue by harleybox** [dcloudio/uni-app#799]
ios 13, hbuild 2.3.1 
下拉scroll-view区块可以刷新；下拉scroll item到顶，再下拉这部分还是不会刷新，而且感觉有点卡，动画不流畅
ios12的时候下拉scroll item到顶是偶尔不会刷新，但是没那么卡
![image](https://user-images.githubusercontent.com/765200/65366826-b64ac980-dc5b-11e9-9467-2801003a3075.png)

**Comment by StrivingRabbit** [comment]
此问题在新版已修复
