### ISSUE TITLE
动态修改tabbarItem的展示和隐藏，或者可以动态添加，不只是单纯设置text等属性

### ISSUE THREAD

**Issue by fengjiel** [dcloudio/uni-app#800]
**新功能描述**
希望有一个功能可以支持动态修改tabbarItem的展示和隐藏，或者可以动态添加，不只是单纯设置text等属性

**现状及问题**
目前不支持

**尝试方案**
自己写组件需要加在每个页面同时跳转会闪

**补充信息**

**Comment by wanganxp** [comment]
小程序平台自身不支持。app建议使用nvue实现这种需求，体验好

**Comment by fengjiel** [comment]
主要是做移动端和小程序平台  请问好的解决方案吗 @wanganxp

**Comment by zhetengbiji** [comment]
App 和 H5 已支持动态显示隐藏：https://uniapp.dcloud.net.cn/api/ui/tabbar.html
