### ISSUE TITLE
<web-view> 加载的网页中支持调用部分 uni 接口：uni.navigateTo

### ISSUE THREAD

**Issue by wangjinxin613** [dcloudio/uni-app#802]
<web-view> 加载的网页中支持调用部分 uni 接口：uni.navigateTo

如果小程序端或者app端引用一个webview网页，而且这个网页使用uniapp的h5编译的

那么这几个接口就冲突了，是执行h5的uni.navigateTo 还是执行 app或者小程序的uni.navigateTo

**Comment by Wangyaqi** [comment]
H5里面调用的就执行H5的，不会冲突
