### ISSUE TITLE
父子组件传值问题

### ISSUE THREAD

**Issue by hansu123** [dcloudio/uni-app#803]
问题：
父子组件传递数据的时候
父组件数据是一个对象的话，对象属性值为函数时，子组件无法接收到该数据

example：
父组件数据
rules:{
name:()=>{}
}
子组件无法接收到name属性和name属性值

**Comment by javascriptchen** [comment]
你把要传值的这个属性写在computed里面试试

**Comment by StrivingRabbit** [comment]
此问题由于长时间未回复，此issue关闭。如果还有问题可以重开或者提新issue
