### ISSUE TITLE
注册全局组件问题

### ISSUE THREAD

**Issue by hansu123** [dcloudio/uni-app#804]
在main.js中使用函数注册全局组件
const globalComponents = require.context('@/components/global', true, /\.vue$/);
globalComponents.keys().forEach(filename=>{
	let key=filename.replace(/(^\.\/)|(\.vue$)/ig,"")
	Vue.component(key,globalComponents(filename).default)
})
报如下错误：
Vue.component()的第一个参数必须为静态字符串
望尽快解决！！！

**Comment by fxy060608** [comment]
组件注册目前是编译时静态扫描的，不支持动态注册

**Comment by ben-lau** [comment]
其实这个想想小程序是做不到的  就应该知道uniapp也不会有这个支持
小程序组件注册本来就是静态

**Comment by liusheng22** [comment]
> 其实这个想想小程序是做不到的 就应该知道uniapp也不会有这个支持 小程序组件注册本来就是静态

可以用 loader/plugin 试试，支持 vue2/vue3：

[github案例](https://github.com/liusheng22/uni-global-component-inject)
[npm 安装](https://www.npmjs.com/package/uni-global-component-inject)
