### ISSUE TITLE
`<input>`失去焦点后无法在输入

### ISSUE THREAD

**Issue by d1y** [dcloudio/uni-app#805]
**问题描述**

在`chrome`浏览器下的`<input>`原生组件,在第一次输入之后, 就无法获取到焦点输入了

**复现步骤**

![](https://files.catbox.moe/uzvv2w.gif)

**系统信息:**
 - 发行平台: H5
 - 操作系统 macOS 10.15
 - uni-app版本 uni-app v2.0.0-22420190823019

**Comment by javascriptchen** [comment]
你用真机试试，真机上可以吗？

**Comment by d1y** [comment]
> 你用真机试试，真机上可以吗？

很奇怪,在真机上并无此问题

**Comment by javascriptchen** [comment]
> > 你用真机试试，真机上可以吗？
> 
> 很奇怪,在真机上并无此问题

很多时候你不能相信小程序编辑器的，要以最终上传到平台的效果为准，qq小程序真机调试就是不准的

**Comment by d1y** [comment]
> > > 你用真机试试，真机上可以吗？
> > 
> > 
> > 很奇怪,在真机上并无此问题
> 
> 很多时候你不能相信小程序编辑器的，要以最终上传到平台的效果为准，qq小程序真机调试就是不准的

真是神奇的bug, 猜测可能是`input`事件是`tap`而不是`click`
&V$
