### ISSUE TITLE
官方APP demo, ios 总是闪退，弹的广告也无法关闭

### ISSUE THREAD

**Issue by fansiyao** [dcloudio/uni-app#806]
官方APP demo, ios 总是闪退，弹的广告也无法关闭

**Comment by javascriptchen** [comment]
是hello-uniapp吗？请提供一下ios版本号

**Comment by fansiyao** [comment]
9.3.1、6s plus




------------------ 原始邮件 ------------------
发件人: "Haoqun Jiang"<notifications@github.com>; 
发送时间: 2019年9月23日(星期一) 上午10:48
收件人: "dcloudio/uni-app"<uni-app@noreply.github.com>; 
抄送: "原点"<645127912@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [dcloudio/uni-app] 官方APP demo, ios 总是闪退，弹的广告也无法关闭 (#806)




是hello-uniapp吗？请提供一下ios版本号

**Comment by javascriptchen** [comment]
> 9.3.1、6s plus
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Haoqun Jiang"<notifications@github.com>; 发送时间: 2019年9月23日(星期一) 上午10:48 收件人: "dcloudio/uni-app"<uni-app@noreply.github.com>; 抄送: "原点"<645127912@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [dcloudio/uni-app] 官方APP demo, ios 总是闪退，弹的广告也无法关闭 (#806) 是hello-uniapp吗？请提供一下ios版本号 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.

ios9的测试机我们是真的没有。。。您那边有没有ios12或ios13的手机吗，是可以的吗？
