### ISSUE TITLE
编译出的小程序缺少app.json或project.config.json文件

### ISSUE THREAD

**Issue by xnng** [dcloudio/uni-app#807]
**问题描述**
编译出的小程序缺少`app.json`或`project.config.json`文件，导致微信开发者工具无法打开项目。

**复现步骤**

通过如下方式运行的项目，然后用微信开发者工具无法打开对应的小程序文件夹

```bash
npm install -g @vue/cli
vue create -p dcloudio/uni-preset-vue test
yarn dev:mp-weixin
```

**预期结果**

正常打开

**实际结果**

![image](https://user-images.githubusercontent.com/38936252/65397812-ab23a500-dde5-11e9-8b04-01da697d9031.png)

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统: win10
 - uni-app版本: v2.3.2

**补充信息**

我不确定是否打开错目录了，但是确实没有任何一个文件夹可以提供`app.json`或`project.config.json`文件，微信开发者工具无法打开此项目。

**Comment by javascriptchen** [comment]
你多了一层路径，`test/dist`被你写成了`test/uniapp/dist`

**Comment by javascriptchen** [comment]
![test807](https://user-images.githubusercontent.com/26818851/65399355-c34bf200-ddee-11e9-98e0-95fb74135524.gif)

**Comment by xnng** [comment]
感谢
