### ISSUE TITLE
最新版cli出现https://tongji.dcloud.io 不在以下 request 合法域名列表中

### ISSUE THREAD

**Issue by zzlit** [dcloudio/uni-app#808]
版本：
uni-app v2.2.4
uni-app cli v2.0.0-23220190921001

编译后出现
https://tongji.dcloud.io 不在以下 request 合法域名列表中，请参考文档：https://developers.weixin.qq.com/miniprogram/dev/framework/ability/network.html

**Comment by javascriptchen** [comment]
HBuilderX 2.2.3起，新增了uni统计，一份报表看全端数据，详见 https://tongji.dcloud.io 。
在小程序端，使用uni统计需在安全域名名单中新增 tongji.dcloud.io 。如不需要uni统计，可在manifest中关闭。开通和关闭详见：https://ask.dcloud.net.cn/article/36303
