### ISSUE TITLE
navbar组件触发了 'click-left'与'clickLeft', 导致方法触发两次

### ISSUE THREAD

**Issue by shuaipao** [dcloudio/uni-app#809]
**问题描述**
navbar组件触发了 'click-left'与'clickLeft', 导致方法触发两次,

**复现步骤**
[复现问题的步骤]
methods: {
	/**
	 * 左侧按钮点击事件
	 */
	onClickLeft() {
		this.$emit('clickLeft')
		this.$emit('click-left')
	},
	/**
	 * 右侧按钮点击事件
	 */
	onClickRight() {
		this.$emit('clickRight')
		this.$emit('click-right')
	}
}
<uni-nav-bar @click-left='back' left-icon="back" shadow='false' title="" backgroundColor="#FEE24A" color="white"></uni-nav-bar>

此处back事件触发了两次

[或者可以直接贴源代码]

**预期结果**
这里触发back事件方法应该只有一次

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本 2.3.2.20190921
 - uni-app版本 
 - 设备信息 微信开发者工具

**补充信息**
[可选]
我觉得是在内部的某种机制下驼峰命名与下划线命名的两个事件都触发了

**Comment by Wangyaqi** [comment]
确实是这样的，并不是BUG就是这么设定的，尽量不要驼峰和连接符的写法混在一起
