### ISSUE TITLE
如何使用原声的form、

### ISSUE THREAD

**Issue by keke996** [dcloudio/uni-app#81]
如何使用原声的form表单

**Comment by keke996** [comment]
如何使用原声的form表单提交数据并跳转action中的url

**Comment by zhetengbiji** [comment]
如果是h5版可以使用js动态生成form

**Comment by YqxLzx** [comment]
> 

如果要同事打包到安卓端呢？

**Comment by zhetengbiji** [comment]
> > 
> 
> 如果要同事打包到安卓端呢？

https://uniapp.dcloud.net.cn/tutorial/renderjs.html#renderjs
