### ISSUE TITLE
css   page  页面内设置 编译问题

### ISSUE THREAD

**Issue by hxzAugustinus** [dcloudio/uni-app#810]
**问题描述**
  当在某一个页面的css中 使用 page:{} ，在h5端编译时，会提取本页面的所有background相关属性

**复现步骤**
在/pages/home/home.vue 页面
```
<style lang="scss">
page {
  height: calc(100% - 40px);
  .home-page {
    background-color: #f7f7f7;
    height: 100%;
    .card-box {
        .....
    }
 }
}
</style>
```

**预期结果**
编译后不提取子元素的background相关属性

**实际结果**
在h5端编译后 ，Chrome浏览器里看到的代码如下：
![error1](https://user-images.githubusercontent.com/14306029/65413623-6bc87900-de24-11e9-8023-567f83e8d4c5.jpg)
可以看到编译后添加了该页面所有子元素的background、background-color、background-image等，导致在Safari等一些浏览器上侧的地址栏和下侧的工具栏由于本身有透明度会使得颜色混乱（显示颜色取决于该页面最后一个background相关属性及相关权重）

**系统信息:**
 - 发行平台 ： H5平台
 - 操作系统 ： iOS 
 - 设备信息：safari

**Comment by fxy060608** [comment]
为什么要把.home-page包裹在 page 里边呢？应该提到外边吧
page 是一个特殊选择器，不同平台实现不同，最好只是单独给 page 设置样式，而不是使用 page 作为父选择器

**Comment by hxzAugustinus** [comment]
👌，使用平级的 page 和 .home-page不会出现提取ackground相关属性，多谢回复
