### ISSUE TITLE
当使用nvue，且编译模式为uni-app时，style设置750rpx，实际显示不到满屏

### ISSUE THREAD

**Issue by GOGOGOSIR** [dcloudio/uni-app#812]
当使用nvue，且编译模式为uni-app时，style设置750rpx，实际显示不到满屏
![image](https://user-images.githubusercontent.com/26272801/65439372-a1d42000-de59-11e9-84d4-a3f8cc3f2c49.png)
![image](https://user-images.githubusercontent.com/26272801/65439417-b31d2c80-de59-11e9-8d2e-14b1aa6348c8.png)
![image](https://user-images.githubusercontent.com/26272801/65439706-3048a180-de5a-11e9-90b0-8c994a5f2509.png)

**Comment by javascriptchen** [comment]
你试试
```
position:absolute;
left:0;
right:0;
height:200rpx;
background-color:red;
```

**Comment by GOGOGOSIR** [comment]
感谢你的解答，我现在就怕uniapp模式下rpx的单位转换有误差，weex模式下的px转换是正常的，如果在某些需求下，必须通过rpx设置其宽高，这样的误差，我担心会影响页面的布局

**Comment by javascriptchen** [comment]
> 感谢你的解答，我现在就怕uniapp模式下rpx的单位转换有误差，weex模式下的px转换是正常的，如果在某些需求下，必须通过rpx设置其宽高，这样的误差，我担心会影响页面的布局

嗯，我们同事也跟我说了有这个问题，我们尽快排查原因

**Comment by hangaoke1** [comment]
同遇到,ios是正常的，安卓有问题

**Comment by dcloudhdx** [comment]
HBuilderX 2.3.5+ 已修复
