### ISSUE TITLE
onLoad中调用uni.startPullDownRefresh()在android端不生效

### ISSUE THREAD

**Issue by hiXing** [dcloudio/uni-app#813]
**问题描述**
在onLoad中调用uni.startPullDownRefresh()方法，在Android真机下不会走onPullDownRefresh()方法，也不会显示刷新的动画，在iOS模拟器中可以

**系统信息:**
 - 发行平台: App
 - 操作系统 [ iOS 12.4、Android 9.0]
 - HBuilderX版本 [2.3.2.20190921]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [ iPhone6 Plus模拟器、vivo X21i真机]

**Comment by Wangyaqi** [comment]
可以更新一下HBuilderX看看还有没有这个问题

**Comment by dcloudhdx** [comment]
issue长时间未反馈，暂时关闭，若继续有问题，可以重开或发新issues
