### ISSUE TITLE
支付宝小程序在安卓端  input 输入框 删除时，出现重影，字体抖动

### ISSUE THREAD

**Issue by chen-can** [dcloudio/uni-app#814]
在安卓端  使用input组件进行点击清除输入框值，点击键盘上删除键时，出现重影，字体抖动
似乎对vue 支持不太优化
可以使用https://ext.dcloud.net.cn/plugin?id=425 做测试

特别注意安卓端 使用v-model也能够复现

**Comment by Wangyaqi** [comment]
不要在@input里面给input赋value，这种写法肯定会抖

**Comment by chen-can** [comment]
请问如何赋值，能否给个示例代码

**Comment by Wangyaqi** [comment]
是我看错了，这个有问题，删除的时候确实有这个毛病，我再试试哪的问题

**Comment by chen-can** [comment]
那扩展组件呢

**Comment by chen-can** [comment]
![image](https://user-images.githubusercontent.com/35422769/65762619-080bbc00-e154-11e9-9718-8905f82cbf0f.png)
使用官方的或https://ant-move.github.io/vant-ailapp-docs/#/changelog 事件都无法点击 编译器还会报错

**Comment by Wangyaqi** [comment]
直接在支付宝小程序里面像下面这么写也会闪，那这块暂时应该处理不了，想办法绕一下吧

```html
<input placeholder="Input" onInput="onInput" value="{{value}}" />
```
```javascript
Page({
   data: {
    value: 'hello'
  },
  onInput(e) {
    this.setData({
      value: e.detail.value,
    });
  }
});
```

**Comment by chen-can** [comment]
@Wangyaqi 利用函数防抖可以解决这个问题
