### ISSUE TITLE
uni.getAccountInfoSync is not a function

### ISSUE THREAD

**Issue by CLD5186** [dcloudio/uni-app#816]
问题：uni-app升级最新依赖报错。uni.getAccountInfoSync is not a function。
实际情况：wx.getAccountInfoSync方法最低支持2.2.2的基础版本库。因为项目面对C端用户，有些用户的微信可能比较低，原来的做法是在App.vue里面去做一层基础库支持的判断，然后给用户提示。现在升级了新的依赖之后，发现应用根本无法进入到App.vue里面或者说相关判断提示没有触发。查看打包之后的common/vendor.js里面找到
<img width="1162" alt="WeChata21966e5127dfc53edfbee59dbf055d6" src="https://user-images.githubusercontent.com/21166810/65489330-7e52b900-dedd-11e9-980d-8a633e579ff1.png">
根据这个方法，在依赖包中对uni-stat文件做了修改，对getPackName方法，删除了uni.getAccountInfoSync方法的调用。

不知道这样做会不会影响别的地方。删除之后，能够正常触发App.vue里面的方法，提供用户基础库过低的提示。

**Comment by Wangyaqi** [comment]
最好不要去掉，可以用canIuse判断一下

**Comment by mehaotian** [comment]
```javascript
export const getPackName = () => {
  let packName = ''
  if (getPlatformName() === 'wx' || getPlatformName() === 'qq') {
    // 兼容微信小程序低版本基础库
    if(uni.canIUse('getAccountInfoSync')){
      packName = uni.getAccountInfoSync().miniProgram.appId || '';
    }
  }
  return packName
}
```
用以上写法，推荐使用 2.3.x 以上的基础库版本 ，低版本可能会引发其他的问题。

**Comment by CLD5186** [comment]
> ```js
> export const getPackName = () => {
>   let packName = ''
>   if (getPlatformName() === 'wx' || getPlatformName() === 'qq') {
>     // 兼容微信小程序低版本基础库
>     if(uni.canIUse('getAccountInfoSync')){
>       packName = uni.getAccountInfoSync().miniProgram.appId || '';
>     }
>   }
>   return packName
> }
> ```
> 
> 用以上写法，推荐使用 2.3.x 以上的基础库版本 ，低版本可能会引发其他的问题。

好的，直接删除确实有点粗暴。不知道官方人员有没有看到，希望他们能在之后更新中增加上去。。。

**Comment by Wangyaqi** [comment]
> > ```js
> > export const getPackName = () => {
> >   let packName = ''
> >   if (getPlatformName() === 'wx' || getPlatformName() === 'qq') {
> >     // 兼容微信小程序低版本基础库
> >     if(uni.canIUse('getAccountInfoSync')){
> >       packName = uni.getAccountInfoSync().miniProgram.appId || '';
> >     }
> >   }
> >   return packName
> > }
> > ```
> > 
> > 
> > 用以上写法，推荐使用 2.3.x 以上的基础库版本 ，低版本可能会引发其他的问题。
> 
> 好的，直接删除确实有点粗暴。不知道官方人员有没有看到，希望他们能在之后更新中增加上去。。。

下个版本会加上去
