### ISSUE TITLE
支付宝小程序，获取手机号方法

### ISSUE THREAD

**Issue by chen-can** [dcloudio/uni-app#819]
查看https://ask.dcloud.net.cn/question/58685
提示说HBuilderX 2.2.5(alpha) 以上版本已支持 直接配置 open-type="getPhoneNumber"
但是我的项目使用的是cli模式
还有cli 模式如何更新uni-app npm update 只能更新部分
如何查看cli 模式uni-app 版本

**Comment by Wangyaqi** [comment]
你可以对比一下cli新创建的项目和npm update之后的版本号有什么差异，获取手机号之前必须调用login，服务端解析支付宝加密数据也是需要login返回的code

**Comment by chen-can** [comment]
cli 新版不支持open-type="getPhoneNumber"

**Comment by Wangyaqi** [comment]
支持

**Comment by chen-can** [comment]
@Wangyaqi 看下https://github.com/dcloudio/uni-app/issues/827
