### ISSUE TITLE
在微信浏览器下video标签无法自动播放视频

### ISSUE THREAD

**Issue by VincentChengzc** [dcloudio/uni-app#820]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
```
       <video
                id='myVideo'
                v-if="status == 0 && loadFinish"
                autoplay
                muted=“muted”
                :src="/static/video/loading.mp4'"
                @ended='statusPlus'
                :controls="false"
            ></video>
```

[或者可以直接贴源代码]

**预期结果**
打开对应页面时候可以自动播放video里面的的视频

**实际结果**
实际结果需要用户点击播放才可以播放视频

**系统信息:**
 - 发行平台: H5的微信浏览器
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Wangyaqi** [comment]
大多数手机浏览器要求视频播放需要用户触发，尤其是IOS端

**Comment by VincentChengzc** [comment]
> 大多数手机浏览器要求视频播放需要用户触发，尤其是IOS端。
> 可以尝试在`WeixinJSBridgeReady`里面触发视频播放

           this.videoContext = uni.createVideoContext('myVideo1')
                this.videoContext.requestFullScreen();
                //weixin
                document.addEventListener("WeixinJSBridgeReady", () => {
                    alert(111)
                    this.videoContext.play();
                }, false);
我曾经试过但是无法触发play()事件

**Comment by Wangyaqi** [comment]
WeixinJSBridgeReady只会在页面加载的时候触发一次，这么是用不了的。只能指引用户点击播放了

**Comment by VincentChengzc** [comment]
@Wangyaqi 
主要是产品这边找到一个例子，打开后 可以自动播放

**Comment by Wangyaqi** [comment]
> @Wangyaqi
> 主要是产品这边找到一个例子，打开后 可以自动播放

例子是什么，发来看看

**Comment by VincentChengzc** [comment]
@Wangyaqi 
https://ym.qq.com/act/a20190514ymssg/index.html?ADTAG=tgi.wx.share.message&from=singlemessage&isappinstalled=0

**Comment by Wangyaqi** [comment]
人家这是点击事件触发的视频播放，没有自动播放

**Comment by iQiQif** [comment]
微信浏览器现在好像已经禁止自动播放视频了，是微信的问题
