### ISSUE TITLE
uni-hello官方示例的左滑组件uni-swipe-action实现有些复杂，能否简化?

### ISSUE THREAD

**Issue by sonicsunsky** [dcloudio/uni-app#821]
uni-hello官方示例的左滑组件uni-swipe-action实现有些复杂，能否简化?

uni-swipe-action当前使用wxs实现左滑删除效果，感觉实现逻辑比较复杂，有些过度封装，是否能在wxs的基础上简化下逻辑便于维护? 

当前uni-swipe-action组件中的mp.js和mpother.js和index.wxs确实不太好维护，不少地方还缺少注释，光代码就得看半天才能弄明白

**Comment by Wangyaqi** [comment]
为了在支持wxs的环境得到更好的运行效果才这么写的，如果对性能要求不是非常高，可以去掉wxs，去除`mixins: [mp],`全平台启用`mixins: [mixins]`
