### ISSUE TITLE
uni.getImageInfo()没有返回orientation 值

### ISSUE THREAD

**Issue by VincentChengzc** [dcloudio/uni-app#825]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
调用uni.getImageInfo()
只返回了{errMsg: "getImageInfo:ok", width: 750, height: 1334, path: "blob:http://192.168.118.72:8080/98556f49-11be-4976-bf20-45cfd8ec236d"}
没有返回orientation
[或者可以直接贴源代码]

**预期结果**
返回orientation值

**实际结果**
只返回了{errMsg: "getImageInfo:ok", width: 750, height: 1334, path: "blob:http://192.168.118.72:8080/98556f49-11be-4976-bf20-45cfd8ec236d"}

**系统信息:**
 - 发行平台: h5平台
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Wangyaqi** [comment]
orientation字段不支持H5，如果想实现可以借助exif.js之类的库。这个比较大我们不方便做内置

**Comment by VincentChengzc** [comment]
@Wangyaqi 因h5拍照照片会旋转90度.是不是只有这一种办法

**Comment by Wangyaqi** [comment]
> @Wangyaqi 因h5拍照照片会旋转90度.是不是只有这一种办法
可以参考一下这个，这个比较旧了，你可以改造一下
https://github.com/Wangyaqi/imageOrientationSimplified

**Comment by VincentChengzc** [comment]
好的谢谢h5下  已通过https://github.com/q310550690/uni-app-cpimg此方案解决
