### ISSUE TITLE
当data中的属性为下划线开头时，methods中this不到

### ISSUE THREAD

**Issue by zhi-he** [dcloudio/uni-app#826]
**问题描述**
在微信小程序开发工具中当data中的属性为下划线开头时，如 _p，methods中this不到，this._p发现该属性是undefined

**Comment by fxy060608** [comment]
详细参考 Vue 的官方文档：https://cn.vuejs.org/v2/api/#data

`
以 _ 或 $ 开头的属性 不会 被 Vue 实例代理，因为它们可能和 Vue 内置的属性、API 方法冲突。
`

**Comment by zhi-he** [comment]
长见识了，谢谢



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "fxy060608"<notifications@github.com&gt;; 
发送时间: 2019年9月26日(星期四) 下午4:27
收件人: "dcloudio/uni-app"<uni-app@noreply.github.com&gt;; 
抄送: "幽冥&amp;#x266A;"<731701134@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [dcloudio/uni-app] 当data中的属性为下划线开头时，methods中this不到 (#826)




详细参考 Vue 的官方文档：https://cn.vuejs.org/v2/api/#data
 
以 _ 或 $ 开头的属性 不会 被 Vue 实例代理，因为它们可能和 Vue 内置的属性、API 方法冲突。
