### ISSUE TITLE
支付宝编译样式出错

### ISSUE THREAD

**Issue by chen-can** [dcloudio/uni-app#827]
使用组件时，修改内容保存编译后样式消失，但如果重新执行npm run dev 编译 样式又恢复正常

**Comment by Wangyaqi** [comment]
已修复，感谢反馈

**Comment by chen-can** [comment]
怎么更新

**Comment by Wangyaqi** [comment]
还没发版，你可以把上面commit修改的文件替换到你的cli项目里面去

**Comment by chen-can** [comment]
全局搜索没有找到这个文件@Wangyaqi

**Comment by Wangyaqi** [comment]
node_modules\@dcloudio\uni-cli-shared\lib

**Comment by chen-can** [comment]
多谢  请问https://github.com/dcloudio/uni-app/issues/830这个是一样的错误吗
