### ISSUE TITLE
HbuilderX功能完善建议

### ISSUE THREAD

**Issue by MikuBlog** [dcloudio/uni-app#828]
**新功能描述**

对同一文件分栏显示

**现状及问题**

在进行vue开发的时候，js、css都写一起。不采用分模块开发的形式会导致当前页面代码非常的长。

**Comment by wanganxp** [comment]
对标签卡点右键，复制标签卡
另外ctrl+alt+鼠标左键，是分栏打开转到定义，支持同文件分栏

**Comment by MikuBlog** [comment]
@wanganxp 感谢指导。不过能否做到像vscode那样的直接拖拽分栏？
