### ISSUE TITLE
image 标签 oss 图片 style 就无法显示

### ISSUE THREAD

**Issue by vvphp** [dcloudio/uni-app#829]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看
H5 小程序可以显示   Ios基座测试时无法显示

http://gift.cdn.sanxiake.cn/upload/goods/20190718/1563413595_5698.jpg/listimg
http://gift.cdn.sanxiake.cn/upload/goods/20190718/1563413595_5698.jpg-listimg
http://gift.cdn.sanxiake.cn/upload/goods/20190718/1563413595_5698.jpg_listimg
http://gift.cdn.sanxiake.cn/upload/goods/20190718/1563413595_5698.jpg!listimg
http://gift.cdn.sanxiake.cn/upload/goods/20190718/1563413595_5698.jpg@!listimg

15:21:24.412  image发生error事件，携带值为GET http://gift.cdn.sanxiake.cn/upload/goods/20190718/1563413595_5698.jpg/listimg 404 (Not Found) at pages/wawa/list/list.vue:62 __ERROR 
15:21:24.435  image发生error事件，携带值为GET http://gift.cdn.sanxiake.cn/upload/goods/20190718/1563413595_5698.jpg/listimg 404 (Not Found) at pages/wawa/list/list.vue:62 __ERROR 

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by dcloudhdx** [comment]
在HBuilderX 2.3.6 测试没有复现该问题
`
<template>
	<view class="content">
		<image class="logo" src="http://gift.cdn.sanxiake.cn/upload/goods/20190718/1563413595_5698.jpg-listimg" @load="imageload" @error="imageerror"></image>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				title: 'Hello'
			}
		},
		onLoad() {
		},
		methods: {
			imageload(e) {
				console.log("load " + JSON.stringify(e));
			},
			imageerror(e) {
				console.log("error " + JSON.stringify(e));
			}
		}
	}
</script>
`

**Comment by vvphp** [comment]
HBuilderX   2.3.7.20191024   MacOs
`<template>
	<view class="content">
		<image class="logo" src="http://gift.cdn.sanxiake.cn/upload/goods/20190718/1563413595_5698.jpg-listimg" @load="imageload" @error="imageerror" style="width:200px;height: 200px;"></image>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				title: 'Hello'
			}
		},
		onLoad() {
		},
		methods: {
			imageload(e) {
				console.log("load " + JSON.stringify(e));
			},
			imageerror(e) {
				console.log("error " + JSON.stringify(e));
			}
		}
	}
</script>`


[广告] 17:08:49.929 开源不易，需要鼓励。去给 uni-app 项目 点个 star 吧 [不再提示]
[广告] 17:08:49.931 DCloud 新春招聘开启，欢迎前端、Android、C++/QT来投简历! 详情点击
17:08:49.972 项目 'freebox' 开始编译...
17:08:50.807 编译器版本：2.3.7，当前项目编译模式：自定义组件模式。编译模式差异见：https://ask.dcloud.net.cn/article/35843
17:08:56.327  DONE  Build complete. Watching for changes...
17:08:56.332 项目 '' 编译成功.
17:08:56.551 正在建立手机连接...
17:08:58.886 正在安装手机端HBuilder调试基座...
17:09:18.734 正在同步手机端程序文件...
17:09:21.872 同步手机端程序文件完成
17:09:21.898 联机调试并非打包，调试基座 HBuilder 是默认的测试包，权限、图标都不可自定义。只有在点菜单"发行-发行为原生安装包"时才能自定义这些设置
17:09:21.919 iOS9.0及以上系统需要在"设置"-"通用"-"设备管理"(或"描述文件")中信任DCloud企业证书(Digital Heaven开头的证书)才可以正常使用
17:09:21.944 如手机上HBuilder调试基座未启动，请手动启动。如应用未更新，请在手机上杀掉基座进程重启
17:10:04.427  自定义启动地址:`pages/test/test` 
17:10:05.610  App Launch at App.vue:9 
17:10:05.630  App Show at App.vue:12 
17:10:06.602  error {"target":{"offsetTop":0,"id":"","offsetLeft":0,"dataset":{"eventOpts":[["load",[["imageload",["$event"]]]],["error",[["imageerror",["$event"]]]]]},"errMsg":"GET http://gift.cdn.sanxiake.cn/upload/goods/20190718/1563413595_5698.jpg-listimg 404 (Not Found)"},"currentTarget":{"offsetTop":0,"id":"","offsetLeft":0,"dataset":{"eventOpts":[["load",[["imageload",["$event"]]]],["error",[["imageerror",["$event"]]]]]}},"detail":{"errMsg":"GET http://gift.cdn.sanxiake.cn/upload/goods/20190718/1563413595_5698.jpg-listimg 404 (Not Found)"},"timeStamp":1789,"type":"error","mp":{"target":{"offsetTop":0,"id":"","offsetLeft":0,"dataset":{"eventOpts":[["load",[["imageload",["$event"]]]],["error",[["imageerror",["$event"]]]]]}},"currentTarget":{"offsetTop":0,"id":"","offsetLeft":0,"dataset":{"eventOpts":[["load",[["imageload",["$event"]]]],["error",[["imageerror",["$event"]]]]]}},"detail":{"errMsg":"GET http://gift.cdn.sanxiake.cn/upload/goods/20190718/1563413595_5698.jpg-listimg 404 (Not Found)"},"timeStamp":1789,"type":"error"}} at pages/test/test.vue:21

**Comment by dcloudhdx** [comment]
还是无法复现，请提供一个完整的简单示例工程

```
<template>
	<view class="content">
		<image class="logo" src="http://gift.cdn.sanxiake.cn/upload/goods/20190718/1563413595_5698.jpg-listimg" @load="imageload" @error="imageerror"></image>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				title: 'Hello'
			}
		},
		onLoad() {

		},
		methods: {
			imageload(e) {
				console.log("load " + JSON.stringify(e));
			},
			imageerror(e) {
				console.log("error " + JSON.stringify(e));
			}
		}
	}
</script>
```
```
[广告] 17:23:24.833 开源不易，需要鼓励。去给 uni-app 项目 点个 star 吧 [不再提示]
[广告] 17:23:24.833 DCloud 新春招聘开启，欢迎前端、Android、C++/QT来投简历! 详情点击
17:23:24.848 项目 'test-image-onload' 开始编译...
17:23:26.140 编译器版本：2.3.7，当前项目编译模式：自定义组件模式。编译模式差异见：https://ask.dcloud.net.cn/article/35843
17:23:31.528  DONE  Build complete. Watching for changes...
17:23:31.528 项目 'test-image-onload' 编译成功.
17:23:31.824 正在建立手机连接...
17:23:33.590 正在同步手机端程序文件...
17:23:34.459 同步手机端程序文件完成
17:23:35.272 正在启动HBuilder调试基座...
17:23:37.178 应用【test-image-onload】已启动...
17:23:38.080 App Launch at App.vue:4
17:23:38.102 App Show at App.vue:7
17:23:38.873 load {"type":"load","timeStamp":1192,"target":{"offsetTop":96,"dataset":{"eventOpts":[["load",[["imageload",["$event"]]]],["error",[["imageerror",["$event"]]]]]},"offsetLeft":133,"id":"","width":200,"height":200},"currentTarget":{"offsetTop":96,"dataset":{"eventOpts":[["load",[["imageload",["$event"]]]],["error",[["imageerror",["$event"]]]]]},"offsetLeft":133,"id":""},"detail":{"width":200,"height":200},"mp":{"type":"load","timeStamp":1192,"target":{"offsetTop":96,"dataset":{"eventOpts":[["load",[["imageload",["$event"]]]],["error",[["imageerror",["$event"]]]]]},"offsetLeft":133,"id":""},"currentTarget":{"offsetTop":96,"dataset":{"eventOpts":[["load",[["imageload",["$event"]]]],["error",[["imageerror",["$event"]]]]]},"offsetLeft":133,"id":""},"detail":{"width":200,"height":200}}} at pages\index\index.vue:19
```

**Comment by vvphp** [comment]
系统是macOs  HBuilderX 2.3.7.20191024
我新建一个新项目，就这一个页面，也无法正常显示图片

[test-img.zip](https://github.com/dcloudio/uni-app/files/3778566/test-img.zip)

[广告] 20:00:50.633 开源不易，需要鼓励。去给 uni-app 项目 点个 star 吧 [不再提示]
[广告] 20:00:50.634 DCloud 新春招聘开启，欢迎前端、Android、C++/QT来投简历! 详情点击
20:00:50.654 项目 'test-img' 开始编译...
20:00:51.433 编译器版本：2.3.7，当前项目编译模式：自定义组件模式。编译模式差异见：https://ask.dcloud.net.cn/article/35843
20:00:56.077  DONE  Build complete. Watching for changes...
20:00:56.078 项目 'test-img' 编译成功.
20:00:56.628 正在建立手机连接...
20:00:59.757 正在同步手机端程序文件...
20:01:00.537 同步手机端程序文件完成
20:01:00.558 联机调试并非打包，调试基座 HBuilder 是默认的测试包，权限、图标都不可自定义。只有在点菜单"发行-发行为原生安装包"时才能自定义这些设置
20:01:00.582 iOS9.0及以上系统需要在"设置"-"通用"-"设备管理"(或"描述文件")中信任DCloud企业证书(Digital Heaven开头的证书)才可以正常使用
20:01:00.603 如手机上HBuilder调试基座未启动，请手动启动。如应用未更新，请在手机上杀掉基座进程重启
20:01:08.736  App Launch at App.vue:4 
20:01:08.759  App Show at App.vue:7 
20:01:08.784  error {"target":{"offsetTop":0,"id":"","offsetLeft":0,"dataset":{"eventOpts":[["load",[["imageload",["$event"]]]],["error",[["imageerror",["$event"]]]]]},"errMsg":"GET http://gift.cdn.sanxiake.cn/upload/goods/20190718/1563413595_5698.jpg-listimg 404 (Not Found)"},"currentTarget":{"offsetTop":0,"id":"","offsetLeft":0,"dataset":{"eventOpts":[["load",[["imageload",["$event"]]]],["error",[["imageerror",["$event"]]]]]}},"detail":{"errMsg":"GET http://gift.cdn.sanxiake.cn/upload/goods/20190718/1563413595_5698.jpg-listimg 404 (Not Found)"},"timeStamp":1414,"type":"error","mp":{"target":{"offsetTop":0,"id":"","offsetLeft":0,"dataset":{"eventOpts":[["load",[["imageload",["$event"]]]],["error",[["imageerror",["$event"]]]]]}},"currentTarget":{"offsetTop":0,"id":"","offsetLeft":0,"dataset":{"eventOpts":[["load",[["imageload",["$event"]]]],["error",[["imageerror",["$event"]]]]]}},"detail":{"errMsg":"GET http://gift.cdn.sanxiake.cn/upload/goods/20190718/1563413595_5698.jpg-listimg 404 (Not Found)"},"timeStamp":1414,"type":"error"}} at pages/index/index.vue:21

**Comment by vvphp** [comment]
是不是这个问题在windows系统里面不存在

**Comment by dcloudhdx** [comment]
已复现问题，下版修复
当前版本的解决办法是 http://gift.cdn.sanxiake.cn/upload/goods/20190718/1563413595_5698.jpg?-listimg

**Comment by vvphp** [comment]
oss 图片 style 不支持这种拼接，我等修复。谢谢

**Comment by dcloudhdx** [comment]
这个问题是webp导致，ios不支持，oss可以配置

**Comment by vvphp** [comment]
哦，这个问题是我忽略了，谢谢！
