### ISSUE TITLE
uni-app 编译报错

### ISSUE THREAD

**Issue by chen-can** [dcloudio/uni-app#830]
![image](https://user-images.githubusercontent.com/35422769/65750821-dab31400-e13b-11e9-95b5-ba98368af41d.png)

uni-app cli 版本是2.0.0-23320190923002
升级后组件报错 
还有我知道小程序是不支持transition的 我使用其它组件也有这样的报错提示 重新编译下就正常

**Comment by chen-can** [comment]
hbuilderx 能安装其它依赖吗

**Comment by Wangyaqi** [comment]
替换文件之后正常了是吗

**Comment by chen-can** [comment]
目前暂时没有什么毛病
![image](https://user-images.githubusercontent.com/35422769/65762036-a860e100-e152-11e9-9b4c-f41f903452e9.png)

**Comment by chen-can** [comment]
https://github.com/dcloudio/uni-app/issues/814

**Comment by chen-can** [comment]
还有支付宝小程序使用自定义组件 ide报错  https://github.com/dcloudio/uni-app/issues/790
这么久了都没有声音 @Wangyaqi
