### ISSUE TITLE
uni-app,android能否实现分环境打包？（国内，国外，国内测试，国外测试）

### ISSUE THREAD

**Issue by summer1874** [dcloudio/uni-app#832]
第一次使用uniapp，有几个问题请教一下。

1. [判断运行环境](https://uniapp.dcloud.io/frame?id=%E8%BF%90%E8%A1%8C%E7%8E%AF%E5%A2%83%E5%88%A4%E6%96%AD)官方提供的只有开发和正式的区分。如何区分多个环境?
2. 目前使用的是用HBuilderX 创建的项目，那么用cli创建可以打包成app么？（如果可以是否能够实时进行真机调试？），`npm run %PLATFORM%`的取值没有 `app`这项。
3. 如何实现路由鉴权？

**Comment by Wangyaqi** [comment]
1，可以参考 https://uniapp.dcloud.io/collocation/package 自定义平台
2，运行到APP必须在HBuilderX中运行，把cli创建的项目在HBuilderX内运行即可
3，路由鉴权可以参考一下插件市场 https://ext.dcloud.net.cn/search?q=%E8%B7%AF%E7%94%B1

**Comment by fuguxu** [comment]
> 1，可以参考 https://uniapp.dcloud.io/collocation/package 自定义平台
> 2，运行到APP必须在HBuilderX中运行，把cli创建的项目在HBuilderX内运行即可
> 3，路由鉴权可以参考一下插件市场 https://ext.dcloud.net.cn/search?q=%E8%B7%AF%E7%94%B1

你好，第1点里自定义平台没有app这个选项，请问如何区分app多个环境呢？

**Comment by fuguxu** [comment]
请问第1点解决了吗，同问

**Comment by zhetengbiji** [comment]
app 暂不支持自定义平台，后续会考虑提供自定义平台方式

目前可以使用自定义环境变量的方式

**Comment by Hero-King** [comment]
怎么自定义环境变量? apk云打包直接设置env 是production

**Comment by tong822218** [comment]
同问

**Comment by chaosforfun** [comment]
> app 暂不支持自定义平台，后续会考虑提供自定义平台方式
> 
> 目前可以使用自定义环境变量的方式

2024年了，app支持自定义平台了吗

**Comment by ghostcode** [comment]
> 把cli创建的项目在HBuilderX内运行即可

马上2025年了

**Comment by ghostcode** [comment]
> app 暂不支持自定义平台，后续会考虑提供自定义平台方式
> 
> 目前可以使用自定义环境变量的方式

快2025年了

**Comment by Joseph-Wheat-Carryier** [comment]
恕我直接开喷，uniapp的全套生态就是依托答辩，广大开发者都是捏着鼻子在uniapp这个粪坑里开发
