### ISSUE TITLE
我们是否对 Web Audio API 有良好支持？

### ISSUE THREAD

**Issue by PsiACE** [dcloudio/uni-app#833]
**问题描述**
我迁移了一个简单的 Vue Tuner 应用
当它仅仅是 Vue 应用时，一切工作良好，包括电脑和手机。
但迁移到 uni-app 后，则仅仅支持电脑端

**复现步骤**
[van-music-master.zip](https://github.com/dcloudio/uni-app/files/3662626/van-music-master.zip)
解压，安装好依赖后
yarn run serve

**预期结果**
手机端和电脑端应当正常运行，就像 https://jacobmstein.github.io/tuner/ 那样

**实际结果**
电脑端正常，
手机端 Chrome 会提示不支持，而且也不提示使用麦克风,无法工作。
手机端 Firefox 会不提示使用麦克风，无法工作。

**系统信息:**
 - 发行平台: [H5平台]
 - uni-app版本 [v2.3.3]

**Comment by dcloudhdx** [comment]
App平台暂不支持，H5平台没有限制

**Comment by PsiACE** [comment]
但是目前在手机浏览器无法正常使用呢

**Comment by Wangyaqi** [comment]
如果需要调用麦克风需要localhost或者https

**Comment by PsiACE** [comment]
> 如果需要调用麦克风需要localhost或者https

是的，localhost，但不起作用

**Comment by PsiACE** [comment]
任何进展？

**Comment by FlyingWHR** [comment]
请问是否有后续进展？
