### ISSUE TITLE
createIntersectionObserver在支付宝小程序中使用出错

### ISSUE THREAD

**Issue by jin-yufeng** [dcloudio/uni-app#834]
**问题描述**
使用`uni.createIntersectionObserver(this)`在支付宝小程序中运行会出错

**复现步骤**
代码是[文档](https://uniapp.dcloud.io/api/ui/intersection-observer?id=createintersectionobserver)中的示例代码
运行到支付宝小程序即可

**预期结果**
不出错，正常监听

**实际结果**
出现错误，无法监听
![1](https://user-images.githubusercontent.com/48236054/65812185-1dd1bd80-e1f6-11e9-9c7d-c48cc5e6ab09.png)

**系统信息:**
 - 发行平台：支付宝小程序
 - 开发者工具：支付宝小程序开发者工具 `0.70.9`
 - HBuilderX版本：`2.2.3`

**Comment by leiyaguang** [comment]
擦 就没人回复一下么

**Comment by Wangyaqi** [comment]
已修复，请使用最新alpha验证
