### ISSUE TITLE
app整个都是黑色背景, 闪屏严重 每次进页面都闪一下白色背景

### ISSUE THREAD

**Issue by DestinyHunter** [dcloudio/uni-app#835]
一直有这个问题, ios 下尤其严重,  社区反馈无人回复, 还有 如果全屏 背景图片的话,title 和tabbar 如何透明显示背景 又遮挡 滑动的内容, ios 滑动整个view, 背景图片也跟着一起动

**Comment by javascriptchen** [comment]
闪屏问题：[https://uniapp.dcloud.io/collocation/App?id=%E5%85%A8%E5%B1%80%E6%A0%B7%E5%BC%8F](https://uniapp.dcloud.io/collocation/App?id=%E5%85%A8%E5%B1%80%E6%A0%B7%E5%BC%8F)
title是你自己写的还是平台自带的？
tabbar无法设置透明背景
ios 滑动整个view请给一份复现代码

**Comment by DestinyHunter** [comment]
就是写在app.vue 里的 还是首行写的, 还有一个背景图片
![image](https://user-images.githubusercontent.com/20897838/65831493-bcd8e100-e2ec-11e9-987a-00f92336146b.png)
![image](https://user-images.githubusercontent.com/20897838/65831510-f6115100-e2ec-11e9-860c-81e12c00263c.png)

**Comment by DestinyHunter** [comment]
我看 打包后都是加载js去渲染的页面. 可不可以直接在manifest.json/pages.json  里面加个配置项, 专门设置页面的背景颜色. 打包直接静态注入到页面的head ,不走js 会不会好点

**Comment by javascriptchen** [comment]
![背景色黑色](https://user-images.githubusercontent.com/26818851/65832537-b2701480-e2f7-11e9-9521-58db31f1f938.gif)
你看我写的demo，你是不是第一个color.less有改page为白色的css样式啊，仔细检查下

**Comment by DestinyHunter** [comment]
我试了你的demo 在微信开发者工具上确实没有问题, 我的项目也没有明显的白屏, 但是打包成app 就不行了, 尤其是ios  

[RPReplay_Final1569763723.zip](https://github.com/dcloudio/uni-app/files/3667409/RPReplay_Final1569763723.zip)
这个是你的demo打包的app 什么也没有的情况下 也是闪一下白屏, 录屏有些失真,真机看的时候很明显,
如果页面有东西, js 再大点, 就会是下面的样子.更为严重了,

[2.zip](https://github.com/dcloudio/uni-app/files/3667413/2.zip)


hbuilderx 2.3.3 

微信开发者工具 稳定版  1.02.1907200

**Comment by DestinyHunter** [comment]
?? @javascriptchen

**Comment by zhetengbiji** [comment]
> 我试了你的demo 在微信开发者工具上确实没有问题, 我的项目也没有明显的白屏, 但是打包成app 就不行了, 尤其是ios
> 
> [RPReplay_Final1569763723.zip](https://github.com/dcloudio/uni-app/files/3667409/RPReplay_Final1569763723.zip)
> 这个是你的demo打包的app 什么也没有的情况下 也是闪一下白屏, 录屏有些失真,真机看的时候很明显,
> 如果页面有东西, js 再大点, 就会是下面的样子.更为严重了,
> 
> [2.zip](https://github.com/dcloudio/uni-app/files/3667413/2.zip)
> 
> hbuilderx 2.3.3
> 
> 微信开发者工具 稳定版 1.02.1907200

感谢反馈，后续将进行优化

**Comment by DestinyHunter** [comment]
希望 假期来了之后能解决掉,, 不然现在这种情况 app 没办法使用

**Comment by zhetengbiji** [comment]
> 希望 假期来了之后能解决掉,, 不然现在这种情况 app 没办法使用

目前和假期无关

**Comment by DestinyHunter** [comment]
> > 希望 假期来了之后能解决掉,, 不然现在这种情况 app 没办法使用
> 
> 目前和假期无关

有暂时的解决办法吗. 怎么修改下打包工具. 每个页面上面单独注入背景.,

**Comment by DestinyHunter** [comment]
有解决办法吗.现在,

**Comment by DestinyHunter** [comment]
我想给每个页面头部/公共头部单独注入一段 背景为黑色的css 怎么弄

**Comment by DestinyHunter** [comment]
@zhetengbiji ??

**Comment by DestinyHunter** [comment]
还没有办法吗..

**Comment by DestinyHunter** [comment]
@zhetengbiji @javascriptchen 没有信息了...

**Comment by zhetengbiji** [comment]
项目有排期，请勿一直发消息

**Comment by DestinyHunter** [comment]
这个不解决.我们的app没法使用啊. 目前几个app都是深色背景的.这个问题导致用户体验糟糕透了....希望能早点解决

**Comment by zhetengbiji** [comment]
设置页面背景色：（pages.json内设置style->background）

**Comment by DestinyHunter** [comment]
![image](https://user-images.githubusercontent.com/20897838/68125951-abb76b80-ff4d-11e9-9f0e-78491f47c1c1.png)
是这个吗? 我globalStyle 里面设置了

**Comment by DestinyHunter** [comment]
试了下 并没有效果

**Comment by Shangyunliang** [comment]
很严重啊. ios特明显. 而且背景色不一定是固定的. scrollview一滚动 背景色全出来了. 紧接着组件才显示. 但是肉眼可见 闪动了一下. 不知道是不是一个问题 求官方修复

**Comment by huzhijia** [comment]
> 很严重啊. ios特明显. 而且背景色不一定是固定的. scrollview一滚动 背景色全出来了. 紧接着组件才显示. 但是肉眼可见 闪动了一下. 不知道是不是一个问题 求官方修复
你这边怎么处理的

**Comment by DestinyHunter** [comment]
还没有解决

**Comment by zhetengbiji** [comment]
后续关于深色主题的优化，已统一进行处理 https://uniapp.dcloud.net.cn/tutorial/darkmode.html
