### ISSUE TITLE
请问uni里面获取canvas的原始dom怎么获取?通过querySelector获取到的是封装过的

### ISSUE THREAD

**Issue by VincentChengzc** [dcloudio/uni-app#839]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
请问uni里面获取canvas的原始dom怎么获取?通过querySelector获取到的是封装过的

[或者可以直接贴源代码]

**预期结果**
获取canvas的原始dom

**实际结果**
获取到的是封装过的

**系统信息:**
 - 发行平台: H5
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
仅H5平台和普通vue项目是一样的，可以通过ref获取canvas组件后通过$el获取，甚至直接使用document.querySelector('canvas')

**Comment by VincentChengzc** [comment]
@zhetengbiji 你好，请不要close那么快。因为并没有解决问题。
我需要的是：<canvas id="myCanvas" width="500" height="500"></canvas>。

但是通过$el和document.querySelector('canvas')能拿到的元素是：

<uni-canvas data-v-1badc801="" canvas-id="myCanvas" id="myCanvas"><canvas width="600" height="300" style="height: 150px; width: 300px;"></canvas><div style="position: absolute; top: 0px; left: 0px; width: 100%; height: 100%; overflow: hidden;"></div><uni-resize-sensor><div><div></div></div><div><div></div></div></uni-resize-sensor></uni-canvas>

**Comment by zhetengbiji** [comment]
> document.querySelector('canvas')
$el获取到的就是uni-canvas请继续访问子元素canvas，document.querySelectors是由浏览器提供的不会有问题

**Comment by VincentChengzc** [comment]
@zhetengbiji emmm就是不知道如何获取。。麻烦告知下。谢谢。

**Comment by zhetengbiji** [comment]
> @zhetengbiji emmm就是不知道如何获取。。麻烦告知下。谢谢。

使用querySelector即可

**Comment by VincentChengzc** [comment]
@zhetengbiji  document.getElementById('myCanvas').querySelector('canvas');？拿不到啊

**Comment by zhetengbiji** [comment]
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/6326057/65830294-be9ca780-e2e0-11e9-8cf8-72e829914807.png">
测试没问题，注意时机

**Comment by zhetengbiji** [comment]
对于如何使用，尽量不要在github提问，可以到开发交流群和大伙一起交流。

**Comment by VincentChengzc** [comment]
@zhetengbiji 好的，下次到群里提问。

但是我仍然是获取不到dom元素
     <canvas
            ref='test'
            id='myCanvas'
            canvas-id="myCanvas"
        ></canvas>

            var abc = document.getElementById('myCanvas').querySelector('canvas');
            var canvas = document.querySelector('#myCanvas');
            console.log(321, this.$refs.test.$el);
            console.log(canvas);

**Comment by zhetengbiji** [comment]
> @zhetengbiji 好的，下次到群里提问。
> 
> 但是我仍然是获取不到dom元素
> 
> ```
>      <canvas
>             ref='test'
>             id='myCanvas'
>             canvas-id="myCanvas"
>         ></canvas>
> ```
> 
> ```
>             var abc = document.getElementById('myCanvas').querySelector('canvas');
>             var canvas = document.querySelector('#myCanvas');
>             console.log(321, this.$refs.test.$el);
>             console.log(canvas);
> ```

自己调试一下，还有就是之前说的：注意时机！！！

**Comment by cheerryio** [comment]
@zhetengbiji 

> @zhetengbiji 好的，下次到群里提问。
> 
> 但是我仍然是获取不到dom元素
> 
> ```
>      <canvas
>             ref='test'
>             id='myCanvas'
>             canvas-id="myCanvas"
>         ></canvas>
> ```
> 
> ```
>             var abc = document.getElementById('myCanvas').querySelector('canvas');
>             var canvas = document.querySelector('#myCanvas');
>             console.log(321, this.$refs.test.$el);
>             console.log(canvas);
> ```

js代码放在页面onReady生命周期中执行
```
<template>
     <canvas
            ref='test'
            id='myCanvas'
            canvas-id="myCanvas"
      ></canvas>
</template>

<script>
	export default {
		onReady: function() {
			var abc = document.getElementById('myCanvas').querySelector('canvas');
			var canvas = document.querySelector('#myCanvas');
			console.log(this.$refs.test.$el);
			 console.log(canvas);
			 console.log(abc);
		}
	}
</script>

<style>
</style>
```

**Comment by qing25184** [comment]
app 端如何获取canvas?

**Comment by qing25184** [comment]
doument....报错

**Comment by zhetengbiji** [comment]
> app 端如何获取canvas?

dom 在视图层，目前可以使用 [renderjs](https://uniapp.dcloud.io/frame?id=renderjs)。后续改成原生 canvas 后就不可以了。

**Comment by nadirvishun** [comment]
例如：`<canvas ref='test'></canvas>`，用`this.$refs.test.$refs.canvas`来获取
