### ISSUE TITLE
原生tabbar上面的一条黑线可以实现更改吗

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#840]
原生tabbar，上面有一条分割线，在app上面显示很粗很黑，想变淡变细一些。可以实现更改吗？

**Comment by zhetengbiji** [comment]
近期将发布alpha版，有对tabbar的优化

**Comment by wakaryry** [comment]
@zhetengbiji 好的。期待更多的可配置。

**Comment by zhetengbiji** [comment]
HBuilderX  2.3.4以上版本border默认已变细，borderStyle支持配置其他颜色值，文档：[https://uniapp.dcloud.io/collocation/pages?id=tabbar](https://uniapp.dcloud.io/collocation/pages?id=tabbar)
