### ISSUE TITLE
h5   optimization中 开启 treeShaking  编译会删除使用到的组件

### ISSUE THREAD

**Issue by hxzAugustinus** [dcloudio/uni-app#841]
**问题描述**
当启动h5的treeShaking时，编译结果会删除一些我使用到的组件

**复现步骤**
在 manifest.json 中配置如下
```
{
  "h5": {
    "title": "xxx",
    "router": {
      "mode": "history",
      "base": ""
    },
    "optimization": {
      "treeShaking": {
        "enable": true
      }
    },
    "domain": "https://xxx.cn"
  }
}
````
开发环境编译运行截图
![development](https://user-images.githubusercontent.com/14306029/65858810-72fa0480-e399-11e9-8190-9df8ffc85ee5.jpg)

生产环境编译运行截图
![production-onshake](https://user-images.githubusercontent.com/14306029/65858946-b81e3680-e399-11e9-9cd7-36452739ce0b.png)

可以看到编译把picker 和 actionsheet 给删除了，但我确定在非首页使用到大量的picker ，当我
在 manifest.json中移除treeShaking，又恢复正常了

**预期结果**
treeShaking开启后 picker正常使用

**实际结果**
treeShaking开启后  picker无法使用

**系统信息:**
 - 发行平台:  H5平台
 - HBuilderX版本  2.3.3.20190923

**Comment by LIJUN-XU** [comment]
h5 的配置 里面有domain ，在文档中没有看到。请问在哪里能查到
