### ISSUE TITLE
API条件编译无效[nvue/app]

### ISSUE THREAD

**Issue by lipingruan** [dcloudio/uni-app#844]
**问题描述**

在app运行时
`nvue`页面及其引用的`JS模块`内的条件编译不生效

**复现步骤**

nvue file:
```javascript
const testModule = require ( 'testModule' );
```

testModule file:
```javascript

// #ifdef MP || APP-PLUS || APP-PLUS-NVUE
	console.log ( 'run in APP' );
// #endif

// #ifdef H5
	console.log ( 'run in H5' );
// #endif
```

**预期结果**

console:
> run in APP

**or**

console:
> run in  H5

**实际结果**

console:
> run in APP
> run in H5

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统: Android 9
 - HBuilderX版本: 2.3.3.20190923

**补充信息**

**Comment by javascriptchen** [comment]
[github844.zip](https://github.com/dcloudio/uni-app/files/3700460/github844.zip)
我写的测试代码是可以的，你看下跟你的有什么区别吗

**Comment by lipingruan** [comment]
[test.zip](https://github.com/dcloudio/uni-app/files/3761854/test.zip)

不好意思啊最近在忙其它的, 

操作是这样的: 

1. `yarn` 安装依赖

2. 运行, 首页未报错

3. 点击LOGO图片进入 `test2019` 的 `nvue` 页面

4. `nvue` 报错 (`require...` 这也算是一个问题), 同时并未执行页面内的条件编译

5. 排查问题, 在 `fucking-util-signature-all`模块的 `index.js` 文件内的条件编译内分别添加上log打印信息

6. 重新运行, issue 即复现

**Comment by lipingruan** [comment]
@javascriptchen

**Comment by lipingruan** [comment]
@javascriptchen 你好, 请问这个问题有相关进展吗?
我这边最新反馈到的问题是: 
  nvue里执行 `require('constants')`报错: 
> ReferenceError: Can't find variable: require

猜测主要原因就是这个.

**Comment by dcloudhdx** [comment]
早期版本 nvue 不支持条件编译，问题已修复很久了
