### ISSUE TITLE
picker在PC端怎么滑动

### ISSUE THREAD

**Issue by rangqian123** [dcloudio/uni-app#846]
**问题描述**
公司需求PC客户端和小程序端共用一套程序（没有WAP版），现在小程序的没问题，PC端无法滑动，现在PC的picker换成其他的也不好改了，页面有10多个地方都用了picker

**Comment by zhetengbiji** [comment]
目前仅适配移动端，未针对鼠标事件进行优化，对于PC端且无触摸的设备可以尝试使用 [touchemulator](https://github.com/hammerjs/touchemulator) 模拟触摸
