### ISSUE TITLE
IOS13 input password 为true，密码类型输入的时候，会引起输入混乱

### ISSUE THREAD

**Issue by zhangzhenfei** [dcloudio/uni-app#847]
详细问题描述
IOS13 input password 为true，密码类型输入的时候，会引起输入混乱，会导致附近的input输入无效

[内容]

input password true，设置密码类型

[步骤]

点击拉起键盘输入，切换下一个输入框，会导致输入拉不起手机中文键盘，只能出来密码输入类型的键盘

IDE运行环境说明
2.3.3.20190924-alpha

[IDE版本号]

2.3.3.20190924-alpha

[mac版本号]

uni-app运行环境说明
app 环境

[运行端版本号]

[项目是cli创建的还是HBuilderX创建的？如果是cli创建的，请更新到最新版cli再试]

[编译模式是老模板模式还是新的自定义组件模式？]

自定义组件模式

**Comment by zhangzhenfei** [comment]
附件bug视频

https://ask.dcloud.net.cn/file/download/file_name-MTU2OTgzNDIwNTQ0NTA2NC5tcDRfLnppcA==__url-Ly9pbWctY2RuLXFpbml1LmRjbG91ZC5uZXQuY24vdXBsb2Fkcy9xdWVzdGlvbnMvMjAxOTA5MzAvODI0YTA5YzA5MjA5Y2Q0MTc4YjQ5NzQ5YTkzOGRmZDA=

**Comment by zhetengbiji** [comment]
后续进行过相关优化，可以更新最新版本试试

**Comment by StrivingRabbit** [comment]
由于长时间未回复，此问题关闭，如果还有问题可以重开或者提新issue
