### ISSUE TITLE
tabbar 动态显示或隐藏某一个tab

### ISSUE THREAD

**Issue by coding-life-1** [dcloudio/uni-app#849]
**新功能描述**
简洁描述你希望补充完善的增强功能

**现状及问题**
[当前现状及由此导致的不便]

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by javascriptchen** [comment]
不可以，但是你可以自己写个tabbar实现一下，很简单

**Comment by coding-life-1** [comment]
@javascriptchen 谢谢，自己实现了，但是由于uniapp暂不支持动态组件，组件切换后没办法保持状态，每次切换都重新load组件，这个要怎么解决

**Comment by javascriptchen** [comment]
> @javascriptchen 谢谢，自己实现了，但是由于uniapp暂不支持动态组件，组件切换后没办法保持状态，每次切换都重新load组件，这个要怎么解决

你可以看一下`hello-uniapp`项目，在`main.js`中，
```
import pageHead from './components/page-head.vue'
Vue.component('page-head', pageHead)
```
保存组件的状态，可以用vuex或者globalData

**Comment by coding-life-1** [comment]
@javascriptchen 👌
