### ISSUE TITLE
uni.d.ts 文件中声明的 share 方法的传入参数 ShareOptions 与文档不一致

### ISSUE THREAD

**Issue by simicn** [dcloudio/uni-app#850]
**问题描述**
uni.d.ts 文件中声明的 share 方法的传入参数 ShareOptions 与[文档](https://uniapp.dcloud.io/api/plugins/share?id=share)不一致：

- uni.d.ty 中 type 为 String 类型，文档为 Number;
- success 和 fail 回调函数没有定义返回值。

![image](https://user-images.githubusercontent.com/902283/66502105-3c3d9000-eaf7-11e9-810e-20f9bd0144c5.png)

**Comment by zhetengbiji** [comment]
已修正

**Comment by simicn** [comment]
> 已修正

什么时候才发布呢？
我现在通过 npm update 更新后没有看到有修改。
我是通过vue-cli命令行创建的项目。

**Comment by zhetengbiji** [comment]
> > 已修正
> 
> 什么时候才发布呢？
> 我现在通过 npm update 更新后没有看到有修改。
> 我是通过vue-cli命令行创建的项目。

4天以前
你查看@dcloudio/types版本是0.3.6吗

**Comment by simicn** [comment]
> > > 已修正
> > 
> > 
> > 什么时候才发布呢？
> > 我现在通过 npm update 更新后没有看到有修改。
> > 我是通过vue-cli命令行创建的项目。
> 
> 4天以前
> 你查看@dcloudio/types版本是0.3.6吗

我 npm update 后 @dcloudio/types 的版本还是 0.2.8。
![image](https://user-images.githubusercontent.com/902283/66899364-64fce280-f02d-11e9-83f9-a14a788af59c.png)

另外比较困惑的是通过 vue-cli 创建 uni-app 项目的版本升级方式：

- 文档说通过 npm update 可升级：
![image](https://user-images.githubusercontent.com/902283/66899769-1865d700-f02e-11e9-93d6-09674c2ebbd3.png)

- yarn 运行时提示有新版本，按操作步骤执行后发现并没有升级到新版本：
![image](https://user-images.githubusercontent.com/902283/66899563-c4f38900-f02d-11e9-8f9f-e7f3f4d6926e.png)

- 不知道当前 uni-app 的最新版本号是什么，我通过查看 [Github Release](https://github.com/dcloudio/uni-app/releases)、[官方文档更新日志](https://uniapp.dcloud.io/release)查找最新版本，但是对应到项目中的 package.json 文件中确不知道该如何手动修改 package.json 中 @dcloudio 相关包版本为最新版本。
![image](https://user-images.githubusercontent.com/902283/66900046-a2ae3b00-f02e-11e9-825c-5d25351abc48.png)
![image](https://user-images.githubusercontent.com/902283/66900067-ab067600-f02e-11e9-8eee-16b8c799eb6b.png)

**Comment by simicn** [comment]
> > > 已修正
> > 
> > 
> > 什么时候才发布呢？
> > 我现在通过 npm update 更新后没有看到有修改。
> > 我是通过vue-cli命令行创建的项目。
> 
> 4天以前
> 你查看@dcloudio/types版本是0.3.6吗

手动把 @dcloudio/types 版本升级到 0.3.6 后还是一样
![image](https://user-images.githubusercontent.com/902283/66907815-84e7d280-f03c-11e9-93d5-7aaf1b91a788.png)

**Comment by simicn** [comment]
> > > > > 已修正
> > > > 
> > > > 
> > > > 什么时候才发布呢？
> > > > 我现在通过 npm update 更新后没有看到有修改。
> > > > 我是通过vue-cli命令行创建的项目。
> > > 
> > > 
> > > 4天以前
> > > 你查看@dcloudio/types版本是0.3.6吗
> > 
> > 
> > 手动把 @dcloudio/types 版本升级到 0.3.6 后还是一样
> > ![image](https://user-images.githubusercontent.com/902283/66907815-84e7d280-f03c-11e9-93d5-7aaf1b91a788.png)
> 
> OK了，更到0.3.7

更新到 0.3.7 后 type 参数类型改为 int 了，但是 success 和 fail 方法的回调函数没有返回值。
![image](https://user-images.githubusercontent.com/902283/66910419-207b4200-f041-11e9-8b3e-f3f02ee80631.png)

**Comment by zhetengbiji** [comment]
> > > > > > 已修正
> > > > > 
> > > > > 
> > > > > 什么时候才发布呢？
> > > > > 我现在通过 npm update 更新后没有看到有修改。
> > > > > 我是通过vue-cli命令行创建的项目。
> > > > 
> > > > 
> > > > 4天以前
> > > > 你查看@dcloudio/types版本是0.3.6吗
> > > 
> > > 
> > > 手动把 @dcloudio/types 版本升级到 0.3.6 后还是一样
> > > ![image](https://user-images.githubusercontent.com/902283/66907815-84e7d280-f03c-11e9-93d5-7aaf1b91a788.png)
> > 
> > 
> > OK了，更到0.3.7
> 
> 更新到 0.3.7 后 type 参数类型改为 int 了，但是 success 和 fail 方法的回调函数没有返回值。
> ![image](https://user-images.githubusercontent.com/902283/66910419-207b4200-f041-11e9-8b3e-f3f02ee80631.png)

收到，更新 0.4.1，d.ts 是工具生成的，暂时把缺省参数的统一处理为 any 了，后续完善细节。

**Comment by simicn** [comment]
更新到 0.4.1 可以了，谢谢 @zhetengbiji 。
