### ISSUE TITLE
通过 createSelectorQuery 的 node()无法获取canvas实例

### ISSUE THREAD

**Issue by ivanlee93** [dcloudio/uni-app#851]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
![image](https://user-images.githubusercontent.com/22174857/66533670-594d7f80-eb46-11e9-9277-03ff7d7a42d7.png)

如上代码，不会进入console.log，换成boundingClientRect则正常，但是小程序中 Canvas 实例必须使用.node获取

**复现步骤**
不会执行回调

**系统信息:**
小程序端，微信开发者工具

**补充信息**
无

**Comment by Wangyaqi** [comment]
给canvas写上`type="webgl"`

**Comment by xiaoAoTing** [comment]
遇到了相同的问题，node 回调不会执行。

```html
<canvas canvas-id="myChart" type="webgl" id="myChart" ref="chartRef"></canvas>
```

```js
uni
  .createSelectorQuery()
  .select('#myChart')
  .node((res) => {
    console.log('res::: ', res)
  })
```
