### ISSUE TITLE
【Bug】nvue使用barcode组件扫码成功后返回值为空

### ISSUE THREAD

**Issue by hackyoMa** [dcloudio/uni-app#852]
实际返回值：
success1:{"type":"success","timeStamp":1569374595866,"target":{"id":"1","dataset":{},"offsetLeft":0,"offsetTop":0},"currentTarget":{"id":"1","dataset":{},"offsetLeft":0,"offsetTop":0},"detail":{}}
期望返回值
应带有图片文件及二维码内容

代码：https://uniapp.dcloud.io/component/barcode

**Comment by Wangyaqi** [comment]
可以等2.3.4-alpha发布后再试试还有没有这个问题

**Comment by dcloudhdx** [comment]
HBuilderX 2.3.6 测试正常

**Comment by dxy1046** [comment]
使用代码：https://uniapp.dcloud.io/component/barcode，点击“开始扫码识别”报				undefined is not an object (evaluating 'this.$refs.barcode.cancel');请问如何解决
