### ISSUE TITLE
字节跳动工具版本更新后，项目不断报错

### ISSUE THREAD

**Issue by trebleH** [dcloudio/uni-app#854]
**问题描述**
今天更新字节跳动开发工具后，运行的所有uniapp项目都会不断报错，下面是普通项目和登陆模版的两个错误，但是用真机调试时就不会报错，不清除怎么回事！

![企业微信截图_20191011195440](https://user-images.githubusercontent.com/42934148/66649530-00263e80-ec61-11e9-8caf-e3045d515369.png)

![企业微信截图_20191011195615](https://user-images.githubusercontent.com/42934148/66649622-395eae80-ec61-11e9-975c-0f2b2dd1bc22.png)

**系统信息:**
 - 发行平台: 头条小程序
 - HBuilderX版本 ：2.3.3.20190923
 - uni-app版本 HBuilderX创建

**Comment by SiiZhao** [comment]
那可能新版工具有问题

**Comment by trebleH** [comment]
> 那可能新版工具有问题

可是用字节工具创建的项目就没有问题,uniapp创建的就有，感觉是不兼容了

**Comment by SiiZhao** [comment]
> > 那可能新版工具有问题
> 
> 可是用字节工具创建的项目就没有问题,uniapp创建的就有，感觉是不兼容了

嗯，可能是新版工具有bug，不兼容某些写法了

**Comment by wanganxp** [comment]
我用字节跳动工具1.7.8，跑hello uni-app，没遇到问题。不过我用的是2.3.4 alpha，你可以更新看看

**Comment by Wangyaqi** [comment]
字节跳动小程序开发工具更新到1.7.8就好了
![image](https://user-images.githubusercontent.com/12015319/66897431-92479180-f029-11e9-980c-24ec9869b9f8.png)
