### ISSUE TITLE
业务求助: 支付宝小程序,如何在编译后的main.js文件头部添加代码

### ISSUE THREAD

**Issue by ranwawa** [dcloudio/uni-app#858]
由于种种原因,需要在打包后的main.js文件里面引入*友盟统计代码*
不能直接在源文件的app.vue和main.js里面引入

用不来webpack,所以想直接问一下,要实现这样的功能,怎么配置

![image](https://user-images.githubusercontent.com/30344590/66743517-aca83080-eeac-11e9-9e08-0ffee09f488e.png)

**Comment by Wangyaqi** [comment]
能描述一下具体为什么要这么弄吗

**Comment by ranwawa** [comment]
> 能描述一下具体为什么要这么弄吗

### 业务背景
- 公司要求,使用`友盟+`统计支付宝小程序流量
- 友盟提供了一个sdk叫`umtrack-alipay`
- 这个sdk依赖于`@alipay/af-appx`这个包,但是这个包没有随`umtrack-alipay`一起安装,并且在网络上也找不到`@alipay/af-appx`这个包
- 经测试发现,`@alipay/af-appx`是内置在支付宝开发者工具里面的

### 存在的问题
- 在APP.vue里面引用`umtrack-alipay`就会报错`@alipay/af-appx`找不到
- 但是同样的代码,在原生支付宝开发者工具里面引用是不会报这个错的

所以就有了这个需求

**Comment by wanganxp** [comment]
我们研究一下。不过用uni-app自带的uni统计不好吗？给公司推荐一下

**Comment by ranwawa** [comment]
> 我们研究一下。不过用uni-app自带的uni统计不好吗？给公司推荐一下

谢谢你的回复.

公司有上百个站点,统一的统计代码.
我尽量建议他们在支付宝小程序上用Uni的统计

**Comment by ranwawa** [comment]
统计插件官方已经处理这个问题了

**Comment by ranwawa** [comment]
> 我们研究一下。不过用uni-app自带的uni统计不好吗？给公司推荐一下
@wanganxp  uni自带的统计绑定在配置文件里面,不好区分测试和正式环境..事件上报不支持显示参数..统计数据也没有导出功能或者说对应的api
