### ISSUE TITLE
uni-app安卓端input输入框输入字符卡顿

### ISSUE THREAD

**Issue by huguoyan1989** [dcloudio/uni-app#859]
**问题描述**
我现在有abcde5个界面，abcd是tabbar，a是首页，e中包含input，如果从a跳转到e则input不会输入卡顿，但是从bcd跳转到e则input会输入卡顿，如果把d调整为首页，从d跳转到e和从a跳转到e都不会出现输入卡顿。
在小程序、iOS端各种情况都不会出现卡顿现象

**系统信息:**
 - 发行平台: [Android]
 - 操作系统 [Android7.0 8.0 9.0]
 - HBuilderX版本 [2.3.4.20191014-alpha]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [小米5s，荣耀8c，小米8]

**Comment by Wangyaqi** [comment]
请补充一下测试工程，这边没能复现

**Comment by huguoyan1989** [comment]
> 请补充一下测试工程，这边没能复现

能留一下邮箱么，我把工程发到您的邮箱吧

**Comment by Wangyaqi** [comment]
wangyaqi988@163.com 发这个就可以

**Comment by Wangyaqi** [comment]
暂时做这些修改是可以的，我再具体排查一下原因

[logistics-修改.zip](https://github.com/dcloudio/uni-app/files/3737798/logistics-.zip)

**Comment by huguoyan1989** [comment]
> 暂时做这些修改是可以的，我再具体排查一下原因
> 
> [logistics-修改.zip](https://github.com/dcloudio/uni-app/files/3737798/logistics-.zip)

嗯，这样是可以了，但是我还是需要滚动文字的，麻烦您帮忙排查一下吧

**Comment by Wangyaqi** [comment]
BUG已修复，下次更新生效，感谢关注。目前你可以在页面onHide停掉swiper，页面onShow开始swiper来暂时规避这一问题
