### ISSUE TITLE
开发小程序的时候，重新加载后，链接失效

### ISSUE THREAD

**Issue by thunderwin** [dcloudio/uni-app#86]
开发小程序的时候，每次更新代码后，小程序开发者工具的确会自己重新加载，但是重新加载的小程序的按钮功能全部失效，点击没有任何反应。必须Hbuiderx 里面重新启动小程序开发者工具预览。非常麻烦

**Comment by thunderwin** [comment]
补充下，我是Mac

**Comment by thunderwin** [comment]
问题自己找到了！原因是首次编译和第二次编译后，对css 的解析不一致，造成点击按钮时没有点到链接，这也算一个bug

**Comment by thunderwin** [comment]
到处都有这个BUG，请解决下。。

**Comment by hbcui1984** [comment]
将HBuilderX和微信开发者工具，都升级到最新版本，然后验证一下；
我也是mac，但没出现过你说的问题。

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，若问题重现或有更详细资料后可再次开启
