### ISSUE TITLE
对象数据变化后，h5正常，微信小程序数据变化后无法重新渲染

### ISSUE THREAD

**Issue by qinkaiyuan** [dcloudio/uni-app#864]
对象中拥有name属性，

在方法中修改name属性

页面无法重新渲染，h5正常，微信小程序不行

**Comment by Wangyaqi** [comment]
没复现你的问题，可以补充一下能复现此问题的代码吗

**Comment by qinkaiyuan** [comment]
> 没复现你的问题，可以补充一下能复现此问题的代码吗

```
export default class Talk {
  public id: number = null
  public content: string = null
  public imgs: TalkImg [] = null
  public user: User = null
  public createTime: Date = null
  public comments: Comment[] = null
  public commentNum: number = null
  public hugNum: number = null
  public reportNum: number = null
  public hasHugged: boolean = null
  //是否已关注
  public hasFollowed: boolean = null
}

export default class TalkItem extends Vue {
    @Prop() readonly talk: Talk

     addHug() {
      this.talk.hugNum++
     }
}
```

界面上使用 talk.hugNum 无论如何触发addHug 界面值都不会变化，但是js里面会变

**Comment by qinkaiyuan** [comment]
```
<text v-if="talk.hugNum" class="ml-5px">
    {{talk.hugNum}}
</text>
```

**Comment by Wangyaqi** [comment]
你是要直接在组件内修改props吗，这样很可能会有问题，最好是传到父组件内处理

**Comment by qinkaiyuan** [comment]
> 你是要直接在组件内修改props吗，这样很可能会有问题，最好是传到父组件内处理

h5端是正常的呀。我修改的不是对象的引用，而是对象的属性啊

**Comment by qinkaiyuan** [comment]
> 你是要直接在组件内修改props吗，这样很可能会有问题，最好是传到父组件内处理

就是我想问这是不是bug，还是我的使用方式有问题，如果是我的使用方式有问题的话文档中有没有写，如果没有的话是否需要补充一下，能否加个微信啊

**Comment by Wangyaqi** [comment]
你把项目精简一下发上来，我改改看

**Comment by qinkaiyuan** [comment]
> 你把项目精简一下发上来，我改改看

https://github.com/qinkaiyuan/uniapp_wxvuenofreshbug.git

**Comment by qinkaiyuan** [comment]
> 你把项目精简一下发上来，我改改看

我试了下，是子组件无法更新父组件对象属性的问题，但是h5是可以的，vue的说明也是说 无法变更对象引用，没说不能改变对象的值，所以这到底是什么问题呢，请您帮忙看一下，谢谢

**Comment by Wangyaqi** [comment]
已经向你的仓库提交PR，H5里面虽然能在组件内部修改props，但是这不是vue推荐的做法。[Vue风格指南](https://cn.vuejs.org/v2/style-guide/#%E9%9A%90%E6%80%A7%E7%9A%84%E7%88%B6%E5%AD%90%E7%BB%84%E4%BB%B6%E9%80%9A%E4%BF%A1-%E8%B0%A8%E6%85%8E%E4%BD%BF%E7%94%A8)里有写
>一个理想的 Vue 应用是 prop 向下传递，事件向上传递的。

**Comment by qinkaiyuan** [comment]
> 已经向你的仓库提交PR，H5里面虽然能在组件内部修改props，但是这不是vue推荐的做法。[Vue风格指南](https://cn.vuejs.org/v2/style-guide/#%E9%9A%90%E6%80%A7%E7%9A%84%E7%88%B6%E5%AD%90%E7%BB%84%E4%BB%B6%E9%80%9A%E4%BF%A1-%E8%B0%A8%E6%85%8E%E4%BD%BF%E7%94%A8)里有写
> 
> > 一个理想的 Vue 应用是 prop 向下传递，事件向上传递的。

所以为什么h5可以 微信小程序不可以啊，是bug吗？或者需要特殊说明吗

**Comment by Wangyaqi** [comment]
不算是BUG，在其他平台就是受限的

**Comment by owen-gxz** [comment]
这个问题我也遇到了。。这个东西如何解决？需要传到最外层才可以修改值，这样很不方便阿。    
比如：     
index.vue（传列表给下一级）  -> messages.vue（传单个对象给下一级） -> radio.vue  （循环遍历单选按钮列表）          
这样的三级页面，在radio需要修改传过来的对象的selected的值。。这个时候需要把设置的值传到index页面才可以修改麻？？

**Comment by Vitaminaq** [comment]
for (let i = 0; i < lsn; i++) {
			if (ls[i].name === id) {
				ls[i].value = 1;
				this.lines = [...ls];
				return;
			}
		}
我碰到的问题是本组件的数组解构强制更新后，视图有时能更新，有时不更新，不更新的时间多点几次，就能更新视图了，不知道你们有没有碰到过，怎么解决的

**Comment by bugaio** [comment]
大概  是 这样的吧,   小程序  中 `:dxd="dxd"`,  传递到  子组件时  好像是 `stringify`之后  在 `parse`之后的, 所以 和 传进来的 不是同一个 对象了, 
但是 只是  测试的结果,  我没有 找到 文档 支持。
``` js
props: {
	dxd: Object
},
// 在子组件  保存到  globalData 中
mounted() {
	getApp().globalData.dxd = this.dxd;
}


// 在父组件 
onReady() {
    let aa = getApp().globalData;
    console.log(aa.dxd === this.dxd);
}
```
结论 就是   在 app/h5 传递的是  同一个对象,   在小程序中  不是

**Comment by social-uni** [comment]
> 不算是BUG，在其他平台就是受限的。另外即使在H5里面也不要这么写，会被领导训一顿的

@Wangyaqi  多端不统一不算bug吗，h5和其他端不一致，uniapp目标不是多端统一吗，你可以说这个问题不好改，但是这不是bug吗

你看看他们也有这个问题
