### ISSUE TITLE
Uncaught ReferenceError: WeexPlus is not defined at __uniappview

### ISSUE THREAD

**Issue by 2601940602** [dcloudio/uni-app#867]
在项目的pages文件配置condition list属性后，如果项目存在nvue页面编译时会出现此错误
Uncaught ReferenceError: WeexPlus is not defined at __uniappview.html:1781
Uncaught TypeError: Cannot read property 'stack' of null at uniapp://ready:182

解决方案: 删掉此配置，试着用条件编译去解决这个问题，但无效

![image](https://user-images.githubusercontent.com/31914597/66907406-de033680-f03b-11e9-8119-ff40288ef0e2.png)

**Comment by Wangyaqi** [comment]
studentClass是一个nvue页面，应用首页是一个vue页面是吗

**Comment by 2601940602** [comment]
> studentClass是一个nvue页面，应用首页是一个vue页面是吗

studentClass不是nvue页面，首页是一个nvue页面

**Comment by Wangyaqi** [comment]
此问题已修复
