### ISSUE TITLE
上拉页面触底加载下页数数时，如果循环体中有v-if则不渲染页面

### ISSUE THREAD

**Issue by rockychen2016** [dcloudio/uni-app#868]
**问题描述**
[问题描述：上拉触底时，如果页面元素循还体中加有条件元素，如上拉触底时加载下一页数数，此时可以看到可以请求成功的，]

`<template>
	<view>
		<cu-custom bgColor="bg-gradual-blue" :isBack="true">
			<block slot="backText">返回</block>
			<block slot="content">访客池({{pageInfo.total}})人</block>
			<block slot="right">
				<view class="topBtn" @tap="onSelected"><icon class="cuIcon-check"></icon> <text>选择</text></view>
				<view class="topBtn" @tap="onDelete"><icon class="cuIcon-delete"></icon> <text>删除</text></view>
			</block>
		</cu-custom>
			<view class="cu-list menu-avatar" @longpress="onShowCheckbox">
				<view class="cu-item" v-for="(item, index) in curData" :key="index">
					<view class="cu-avatar round lg" :style="'background-image:url('+ hostUrl + item.headimage +')'"></view>
					<view class="content">
						<view class="text-grey">
							<text class="nickname">{{item.nickname}}</text>
						</view>
						<view class="text-gray text-sm flex">
							<view class="text-cut">
								来源：{{REG_FROM[item.regSiteFrom || 0]}}
							</view> 
						</view>
					</view>
					<view class="action" style="width: 300upx; text-align: right;">
						<view class="text-grey text-xs">首次来访</view>
						<view class="text-grey text-xs">{{dateformat(item.createTime)}}</view>
					</view>
					<view v-if="showcheckbox===1">1111111</view>
				</view>
				<view v-if="showLoadMore" class="moreText">{{loadMoreText}}</view>
				<view v-else-if="showNoMore" class="moreText">{{noMoreText}}</view>
			</view>
	</view>
</template>

<script>
	import dateUtil from '../../libs/common/dateUtil.js';
	export default{
		data() {
			return {
				curData:[],
				pageInfo:{
					curPage:0,
					pageCount:20,
					total:0
				},
				hostUrl:'',
				REG_FROM:{
					"0" : "未知",
					"1" : "PC桌面",
					"2" : "WEB端",
					"3" : "APP端",
					"4" : "微信小程序",
					"5" : "微信公众号",
					"6" : "H5页面",
					"7" : "头条",
					"8" : "支付宝",
					"9" : "百度"
				},
				loadMoreText: "努力加载中...",
				showLoadMore: false,
				noMoreText:'--- 我是有底线的 ---',
				showNoMore:false,
				showcheckbox:1
			}
		},
		methods:{
			dateformat:function(str){
				return dateUtil.format(str);
			},
			getSelectedData:function(){
				let data = [];
				for (let i=0;i<this.curData.length;i++) {
					let _item = this.curData[i];
					if(_item.checked){
						data.push(item.id);
					}
				}
				return data;
			},
			checkboxChange:function(e){
				let values = e.detail.value;
				console.log(values);
			},
			onShowCheckbox:function(e){
				this.showcheckbox = this.showcheckbox==1 ? 0 : 1;
			},
			onSelected:function(e){
				let data = this.getSelectedData();
				if(data.length<1){
					this.$util.alert('长按屏幕,可多选或取消多选!');
					return;
				}
				console.log(data.join(','))
			},
			onDelete:function(e){
				let data = this.getSelectedData();
				if(data.length<1){
					this.$util.alert('长按屏幕,可多选或取消多选!');
					return;
				}
				console.log(data.join(','))
			},
			loadData:function(callback){
				if(this.pageInfo.curPage === 0){
					this.curData = [];
				}
				let _this = this;
				let p = {
					page:this.pageInfo.curPage + 1,
					rows:this.pageInfo.pageCount
				};
				_this.$http.get(this, '/kf/member/guestPool', p, function(result){
					if(result.success){
						_this.hostUrl = result.hostUrl;
						let data = result.rows || [];
						if(data.length > 0){
							_this.pageInfo.curPage = result.curPage;
							_this.pageInfo.total = result.total;
							_this.curData = _this.curData.concat(data);
						}
						if(_this.curData.length >= _this.pageInfo.total){
							_this.showNoMore = true;
						}
					}else{
						_this.$util.showToastError(result.message || '加载数据失败!');
					}
					if(callback && typeof callback === 'function'){
						callback();
					}
				});
			}
		},
		onReachBottom:function(e){
			if(this.showNoMore){
				return;
			}
			this.showLoadMore=true;
			let _this = this;
			setTimeout(function(){
				_this.loadData(function(){
					_this.showLoadMore=false;
				})
			},300)
		},
		onLoad() {
			uni.showLoading({
				title:'加载中.',
				mask:true
			});
			this.loadData(function(){
				uni.hideLoading();
			});
		}
	}
</script>
<style lang="less" scoped>
	.topBtn{
		display: inline-block;
		margin-top: -10upx;
		margin-right: 20upx;
		font-size: 28upx;
		&:active{
			opacity: 0.5;
		}
	}
	.cu-item{
		&>view.checkbox{
			position: absolute;
			left: 20upx;
			top: 18upx;
			z-index: 100;
		}
	}
</style>
`

**预期结果**
[上拉页面触底时会自动加载下一页的数据]

**实际结果**
以上代码加上了<view v-if="showcheckbox===1">1111111</view>这个带条件的节点，就会出现一直显示“努力加载中”（控制打印显示，有实际请求但页面不渲染）

**系统信息:**
 - 发行平台: [5+ App]
 - 操作系统 [Android 8.0]
 - HBuilderX版本 [2.3.3.20190923]
 - 设备信息 [华为荣耀V9]

**Comment by javascriptchen** [comment]
有什么报错吗，能提供可以测试的代码吗？

**Comment by StrivingRabbit** [comment]
由于长时间未回复，此问题关闭，如果还有问题可以重开或者提新issue
