### ISSUE TITLE
IOS端取消键盘横条后,点击非input区域依然不会收起软键盘

### ISSUE THREAD

**Issue by ExtraordinaryPlum** [dcloudio/uni-app#869]
**问题描述**
[IOS端取消键盘横条后,点击非input区域依然不会收起软键盘]

**复现步骤**
[复现问题的步骤]
"softinput" : {
            "navBar" : "none", // 是否显示软键盘上的导航条  iOS上如果软键盘上方有带有“完成”的横条，则需要点完成才能收起键盘；如果没有软键盘上方横条，则点击非input/textarea区域即可收起软键盘

**预期结果**
ios点击非input/textarea区域收起软键盘

**实际结果**
隐藏横条依然不会收起软键盘

**系统信息:**
ios平台  iPhone XR

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
ios更新后之前的不适用?

**Comment by zhetengbiji** [comment]
文档：[app平台ios端软键盘上方横条去除方案](https://uniapp.dcloud.io/component/input?id=app平台ios端软键盘上方横条去除方案)

**Comment by ExtraordinaryPlum** [comment]
已经去除横条,点击非input区域不会自动收起软键盘

**Comment by zhetengbiji** [comment]
> 已经去除横条,点击非input区域不会自动收起软键盘

按我发的文档试试
