### ISSUE TITLE
上拉加载onReachBottom无效，需回到顶部再下拉

### ISSUE THREAD

**Issue by zhengyanghuaer** [dcloudio/uni-app#870]

**Comment by javascriptchen** [comment]
你可以下一个hello-uniapp试一下，对比看一下是不是你自己写的有问题。
[https://github.com/dcloudio/hello-uniapp](https://github.com/dcloudio/hello-uniapp)

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
