### ISSUE TITLE
使用nuve，且其编译模式为uniapp的时候，内容超出屏幕高度隐藏滚动条

### ISSUE THREAD

**Issue by GOGOGOSIR** [dcloudio/uni-app#872]
使用nuve，且其编译模式为uniapp的时候，当内容超出可视区域的时候他会默认显示滚动条，但是在很多业务场景下，可能要隐藏改滚动条，可否将其作为一个配置项，使得在每个页面单独配置，这样灵活性会大幅提高

**Comment by dcloudhdx** [comment]
1. pages 配置 "disableScroll": true
2. 在页面添加滚动容器 例如 `<scroll-view :show-scrollbar="false">`、`<list>`，
设置属性  :show-scrollbar="false"
