### ISSUE TITLE
h5中横屏后的适配问题

### ISSUE THREAD

**Issue by ray8367** [dcloudio/uni-app#875]
在h5中横屏后由于宽度变宽了，使用rpx后元素的宽高就会变得很大。我想要使用竖屏状态下的字体大小应该怎么做。

尝试过在beforeCreate中修改跟元素的字体大小，大小修改成功了，但是页面中的使用rpx单位设置的值还是被放大。

请教应该怎么做

**Comment by Wangyaqi** [comment]
使用px作为单位

**Comment by ray8367** [comment]
> 使用px作为单位

这么难受的嘛，偏偏在app中rpx中又是正确的

**Comment by Wangyaqi** [comment]
没有正确不正确这一说，只有合适不合适。想窗口宽度改变之后字体大小不改变用px是最简单的方法了，你是已经做完了项目才想着适配横屏的吗

**Comment by ray8367** [comment]
> 没有正确不正确这一说，只有合适不合适。想窗口宽度改变之后字体大小不改变用px是最简单的方法了，你是已经做完了项目才想着适配横屏的吗

没有，刚开始做，第一次接触uniapp的项目，还好只是部分页面需要横屏，其他页面还是锁定竖屏好了

**Comment by zhetengbiji** [comment]
目前 rpx 未适配横竖屏切换，后续将进行优化（app和h5）

**Comment by ray8367** [comment]
> 目前 rpx 未适配横竖屏切换，后续将进行优化（app和h5）
了解
