### ISSUE TITLE
nvue页面中如何统一设置页面窗口的背景色

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#876]
在使用vue的时候，一般在app.vue中加一个：`page { background: #F5F7F9;}` 来统一设置背景色。

现在使用nvue，却发现好像没有统一设置的入口。

请指点。谢谢。

**Comment by wakaryry** [comment]
现在是在 每个`nvue`页面的根结点设置的 `flex:1; background-color: #F5F7F9;`

**Comment by Wangyaqi** [comment]
这方法就挺合适的

**Comment by wakaryry** [comment]
这个限制了根节点flex:1。内容超出一屏，无法滑动。这就变成了我需要知道这个页面的内容是不是会超出一屏，是的话，我就不加flex:1，不超出我就加。

显然已经失去了意义，还不如我自己在根目录套一个scroller，铺满一屏，然后加个背景色。

看来这个在nvue页面中，得每个页面都自己处理。就和原生开发一样。
