### ISSUE TITLE
tabbar 选中问题 2.3.5

### ISSUE THREAD

**Issue by DestinyHunter** [dcloudio/uni-app#878]
**问题描述**
2.3.5  tabbar selectedIconPath 不显示. 点击切换tabbar 不显示 选中的图片. 需要再点击一下才显示
App端

**Comment by zhetengbiji** [comment]
> **问题描述**
> 2.3.5 tabbar selectedIconPath 不显示. 点击切换tabbar 不显示 选中的图片. 需要再点击一下才显示
> App端

目前测试未复现，补充说明其他条件

**Comment by DestinyHunter** [comment]
> > **问题描述**
> > 2.3.5 tabbar selectedIconPath 不显示. 点击切换tabbar 不显示 选中的图片. 需要再点击一下才显示
> > App端
> 
> 目前测试未复现，补充说明其他条件
刚找到了问题,项目是多语言的, tabbar 页面onshow 的时候 会用setTabBarItem 重新赋值tabbar, 
![image](https://user-images.githubusercontent.com/20897838/67137094-64995d00-f262-11e9-9706-5fbc8e4f9c6f.png)

导致setect 失效, 上一个版本没问题

**Comment by zhetengbiji** [comment]
> > > **问题描述**
> > > 2.3.5 tabbar selectedIconPath 不显示. 点击切换tabbar 不显示 选中的图片. 需要再点击一下才显示
> > > App端
> > 
> > 
> > 目前测试未复现，补充说明其他条件
> 
> 刚找到了问题,项目是多语言的, tabbar 页面onshow 的时候 会用setTabBarItem 重新赋值tabbar,
> ![image](https://user-images.githubusercontent.com/20897838/67137094-64995d00-f262-11e9-9706-5fbc8e4f9c6f.png)
> 
> 导致setect 失效, 上一个版本没问题

你的意思是如果调用uni.setTabBarItem时，缺省了iconPath、selectedIconPath参数会导致异常是吧。

**Comment by DestinyHunter** [comment]
> > > > **问题描述**
> > > > 2.3.5 tabbar selectedIconPath 不显示. 点击切换tabbar 不显示 选中的图片. 需要再点击一下才显示
> > > > App端
> > > 
> > > 
> > > 目前测试未复现，补充说明其他条件
> > 
> > 
> > 刚找到了问题,项目是多语言的, tabbar 页面onshow 的时候 会用setTabBarItem 重新赋值tabbar,
> > ![image](https://user-images.githubusercontent.com/20897838/67137094-64995d00-f262-11e9-9706-5fbc8e4f9c6f.png)
> > 导致setect 失效, 上一个版本没问题
> 
> 你的意思是如果调用uni.setTabBarItem时，缺省了iconPath、selectedIconPath参数会导致异常是吧。

不缺也会异常,会导致原本应该选中的item.变成没有选中的状态,再点击一下才是选中的,
![image](https://user-images.githubusercontent.com/20897838/67137245-96abbe80-f264-11e9-90c4-457ec5dba4cc.png)
参数都有也是一样, 刚刚试了

**Comment by zhetengbiji** [comment]
> > > > > **问题描述**
> > > > > 2.3.5 tabbar selectedIconPath 不显示. 点击切换tabbar 不显示 选中的图片. 需要再点击一下才显示
> > > > > App端
> > > > 
> > > > 
> > > > 目前测试未复现，补充说明其他条件
> > > 
> > > 
> > > 刚找到了问题,项目是多语言的, tabbar 页面onshow 的时候 会用setTabBarItem 重新赋值tabbar,
> > > ![image](https://user-images.githubusercontent.com/20897838/67137094-64995d00-f262-11e9-9706-5fbc8e4f9c6f.png)
> > > 导致setect 失效, 上一个版本没问题
> > 
> > 
> > 你的意思是如果调用uni.setTabBarItem时，缺省了iconPath、selectedIconPath参数会导致异常是吧。
> 
> 不缺也会异常,会导致原本应该选中的item.变成没有选中的状态,再点击一下才是选中的,
> ![image](https://user-images.githubusercontent.com/20897838/67137245-96abbe80-f264-11e9-90c4-457ec5dba4cc.png)
> 参数都有也是一样, 刚刚试了

安卓还是iOS？

**Comment by DestinyHunter** [comment]
安卓, ios 还没测试. 我去测试下

**Comment by DestinyHunter** [comment]
苹果没有问题,

**Comment by developertry** [comment]
> 苹果没有问题,

DCloud_Android，616422331，加个 QQ了解详情。

**Comment by DestinyHunter** [comment]
> > 苹果没有问题,
> 
> DCloud_Android，616422331，加个 QQ了解详情。

QQ号打错了吧 查出来的不是DCloud_Android

**Comment by zhetengbiji** [comment]
HBuilderX 2.3.6 已修复
