### ISSUE TITLE
nvue下本地图标的使用

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#879]
nvue下可以像vue中使用css 图标吗？
我引入了图标，但是在nvue中app无法显示，到H5/mp显示。
`<text class="iconfont">&#xe62a;</text>`

还有就是 如果我把图标 unicode 作为 prop 传入组件，在H5/mp也不支持显示。

**Comment by Wangyaqi** [comment]
可以参考uni-ui nvue分支  [https://github.com/dcloudio/uni-ui/blob/nvue-uni-ui/src/components/uni-icons/uni-icons.vue](https://github.com/dcloudio/uni-ui/blob/nvue-uni-ui/src/components/uni-icons/uni-icons.vue)

**Comment by wakaryry** [comment]
我看了一下链接的vue文件，突然好奇：nvue组件或者页面中可以引入vue组件吗？

我看是vue格式，但是里面代码似乎告诉我可以在nvue格式文件中使用。

还有 `APP-NVUE`   `APP-PLUS-NVUE` ，这两个有什么区别吗？

**Comment by Wangyaqi** [comment]
组件的后缀不重要，是nvue还是vue最终是由页面决定的

**Comment by wakaryry** [comment]
意思是，我写一个vue格式的组件，在里面做好条件编译。

- nvue页面引入这个vue格式的组件，编译到app端则会使用app端对应的条件；
- nvue页面引入这个vue格式的组件，编译到非app端则会对应其他相应的编译条件。

**Comment by Wangyaqi** [comment]
是的

**Comment by wakaryry** [comment]
可以。
那组件就不用写成nvue格式了。
页面还是得分nvue和vue，组件会根据最终引入的页面来决定。

即使是vue格式的组件，在nvue页面中引入，编译到app端，依然是对应成原生的。

谢谢。

**Comment by wakaryry** [comment]
这个数据是不是有什么严格的要求？我从iconfont.cn生成的icons，`data:application/x-font-woff2;charset=utf-8;base64`，放进去就是不显示成图片。我和官方的区别就是 我的 woff2 数据

**Comment by Wangyaqi** [comment]
直接写到页面用`&#xe6b1;`，使用变量的时候用`\ue6b1`

**Comment by wakaryry** [comment]
好尴尬。出来了一次。然后就变成了 `？`

**Comment by Wangyaqi** [comment]
IOS端还是安卓端？ fontFamily写的是什么？

**Comment by wakaryry** [comment]
fontFamily是我自己定义的 `mypicons` 。不知道为什么，我把base64的数据全删了，结果图标显示出来了。好囧。iOS上面。没有Android测试。

**Comment by Wangyaqi** [comment]
fontFamily用iconfont试试看，就是默认的字体名

**Comment by wakaryry** [comment]
换成iconfont出来了。不过不知道是不是我删除了基座，重新编译的原因。我再每次删除基座多试试看看到底是啥情况。
但是我用上面链接给的官方的组件就一直可以显示。

**Comment by wakaryry** [comment]
是这样，如果icons的 base64 数据 有变化，或者更换了fontFamily的名字，需要 删除 基座，重新编译 才能有效。

# 总结如下

- 设置一个独特的 fontFamily；
- 更改icons数据之后，如果icons出不来，删除基座重新编译；
- 直接写到页面用`&#xe6b1;`，使用变量的时候用`\ue6b1`；
- nvue页面引入组件，组件可以是vue后缀的，编译到app端会是相应的nvue规范。
