### ISSUE TITLE
关于从详情页返回列表页的bug

### ISSUE THREAD

**Issue by lingyusu** [dcloudio/uni-app#88]
相关名词说明：A页面和B页面为列表页，C为详情页

场景：A列表项点进详情页，再返回A页面，A页面向下滚动，再点列表项进详情页再返回，会不时的出现A页面滚动条回到顶部的情况（正常情况应该是停在原先滚动的位置，该情况非必现）,相同操作在B列表页面不会出现该情况

特别说明：AB页面均为tabbar的页面，且A页面为tabbar的第一个，我尝试过把B页面放在tabbar的第一个位置也会出现该情况

**Comment by hbcui1984** [comment]
App端？H5端？

**Comment by lingyusu** [comment]
> App端？H5端？

目前是只测了小程序，其他端还没测

**Comment by mehaotian** [comment]
没有复现到你说的问题 ，请提供更详细的平台信息。
1. IDE 版本
2. 小程序基础库版本
3. 如果是APP端提供手机型号以及系统版本号

**Comment by wyujie** [comment]
> 没有复现到你说的问题 ，请提供更详细的平台信息。
> 
> 1. IDE 版本
> 2. 小程序基础库版本
> 3. 如果是APP端提供手机型号以及系统版本号


H5遇到了，HBuilderX当前最新版。
我体验了下 ColorUI，也有类似的情况。

**Comment by wyujie** [comment]
> > 没有复现到你说的问题 ，请提供更详细的平台信息。
> > 
> > 1. IDE 版本
> > 2. 小程序基础库版本
> > 3. 如果是APP端提供手机型号以及系统版本号
> 
> H5遇到了，HBuilderX当前最新版。
> 我体验了下 ColorUI，也有类似的情况。

明白了，scroll-view 会滚动到顶部

**Comment by zhetengbiji** [comment]
一般是由于 scroll-view 设置了 scroll-top 属性为0导致，如果绑定了 scroll-top 属性，可以在 scroll 事件的时候修改 scroll-top 的值来避免。
