### ISSUE TITLE
【App】ios13扫码调用相册关闭后无法再次打开相册

### ISSUE THREAD

**Issue by magicwing** [dcloudio/uni-app#886]
**问题描述**
ios13版本 调用扫码接口，点击右上角【相册】，相册由下向上弹出且上面部分可以看到后面的扫码界面，此时【手指按住相册标题栏】手势下滑操作会关闭相册，然后再次点击【相册】不回弹出，即使关闭扫码，再次调用也无法打开相册，必须重启app才行。

**复现步骤**
如上

**预期结果**
可以再次打开相册

**实际结果**
无法再次打开

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 iOS 13
 - HBuilderX版本 2.3.3.20190923
 - 设备信息 iPhone6

**Comment by javascriptchen** [comment]
可能是我手速不够快，所以无法手势下滑关闭相册吗？
设备信息 ios13，iphone6s
HBuilderX版本 2.3.6

**Comment by magicwing** [comment]
> 可能是我手速不够快，所以无法手势下滑关闭相册吗？
> 设备信息 ios13，iphone6s
> HBuilderX版本 2.3.6

手指按住标题栏下滑

**Comment by javascriptchen** [comment]
我用的是hello-uniapp里的扫码，换了两个6s ios13手机都不能下滑关闭

**Comment by magicwing** [comment]
> 我用的是hello-uniapp里的扫码，换了两个6s ios13手机都不能下滑关闭
![1](https://user-images.githubusercontent.com/7157683/67185694-fd71d900-f418-11e9-8863-a5cb1add04a7.gif)

附上我操作录像

**Comment by javascriptchen** [comment]
你这是什么手机，6不能升ios13啊

**Comment by magicwing** [comment]
> 你这是什么手机，6不能升ios13啊
iphone 6s  图片开头有系统信息 （没有越狱）

![image](https://user-images.githubusercontent.com/7157683/67195147-079cd300-f42b-11e9-9eac-6d81935dcfb9.png)

**Comment by javascriptchen** [comment]
你试试hello-uniapp里面的扫码能有这样的操作吗？

**Comment by magicwing** [comment]
> 你试试hello-uniapp里面的扫码能有这样的操作吗？

明天再给你回复

**Comment by magicwing** [comment]
> 你试试hello-uniapp里面的扫码能有这样的操作吗？

我用 2.3.3.20190923 版本的IOS SDK 中自带的Hello录了视频，同样可以操作，也存在相册问题
![1](https://user-images.githubusercontent.com/7157683/67365682-a0a32980-f5a4-11e9-99ac-b1931889bb44.gif)

**Comment by dcloudhdx** [comment]
我们暂时无法复现，是个别手机可以下滑吗？

**Comment by magicwing** [comment]
> 我们暂时无法复现，是个别手机可以下滑吗？

目前只有一台ios测试机，如果无法复现就算了
