### ISSUE TITLE
【App】华为手机无法切换键盘

### ISSUE THREAD

**Issue by magicwing** [dcloudio/uni-app#887]
**问题描述**
0、如题的问题可能是特定手机存在问题，其中【华为荣耀10】测试手机执行如下步骤发现问题，其他手机没有问题。
1、页面有2个input 第一个的type=text，第二个的type=number。
2、进入页面后（这个时候键盘还没有弹出），点击第一个input弹出文字键盘，再点击第二个input键盘依旧时文字键盘，正常情况应该切换数字键盘
3、重新进入页面，点击第二个input弹出数字键盘，再点击第一个input依旧是数字键盘，正常情况应该切换文字键盘
4、把第二个input的password设置成true，那么执行步骤2，第二个input的键盘可以正常切换

**复现步骤**
如上

**预期结果**
切换对应类型键盘

**实际结果**
键盘为第一次弹出的键盘

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 Android 9
 - HBuilderX版本 2.3.3.20190923
 - 设备信息 华为 荣耀10

**Comment by Wangyaqi** [comment]
系统自带输入法还是第三方的输入法

**Comment by magicwing** [comment]
> 系统自带输入法还是第三方的输入法

华为系统中自带的《百度输入法华为版》，text和number之间不切换，text和password之间会有键盘切换的过程

**Comment by magicwing** [comment]
> 系统自带输入法还是第三方的输入法

我去安装了搜狗输入法发现是可以的，百度的不行，但是默认安装百度手机输入法的机器也是比较多的，不知道官方可否解决

**Comment by Wangyaqi** [comment]
经测试发现百度输入法有问题，换成其他输入法正常。这个问题暂时无法解决，普通网页中百度输入法也是这种表现

**Comment by magicwing** [comment]
> 经测试发现百度输入法有问题，换成其他输入法正常。这个问题暂时无法解决，普通网页中百度输入法也是这种表现

了解了

**Comment by subarashii** [comment]
这么久过去了，百度输入法居然还是没有解决这个问题，不知道是否有其他技术方案能规避这个问题

**Comment by magicwing** [comment]
自己做软键盘




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "dcloudio/uni-app"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月9日(星期二) 晚上10:05
收件人:&nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&gt;;
抄送:&nbsp;"黑白埋"<83743083@qq.com&gt;;"State change"<state_change@noreply.github.com&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] 【App】华为手机无法切换键盘 (#887)





 
这么久过去了，百度输入法居然还是没有解决这个问题，不知道是否有其他技术方案能规避这个问题

**Comment by Jervis2049** [comment]
我也遇到这个问题了，还没有解决方案。
