### ISSUE TITLE
【App】ios13 input和picker切换键盘不回缩

### ISSUE THREAD

**Issue by magicwing** [dcloudio/uni-app#888]
**问题描述**
ios13 在页面中有一个input和picker原生组件，点击input弹出软键盘，然后直接点击picker，此时picker选择框弹出，而软键盘没有回退。

**复现步骤**
如上

**预期结果**
键盘应该回缩

**实际结果**
键盘不回缩同时picker选择框弹出

**系统信息:**
发行平台: 5+ App
操作系统 iOS 13
HBuilderX版本 2.3.3.20190923
设备信息 iPhone6

**Comment by javascriptchen** [comment]
确认是bug，感谢反馈
