### ISSUE TITLE
【App】RichText显示开头有空格的内容时，开头空格不显示

### ISSUE THREAD

**Issue by magicwing** [dcloudio/uni-app#889]
**问题描述**
内容：“<p>    尊敬的客户xxx，在【xxxx-xx-xx  xx:xx】....</p>”，
RichText开头的空格不显示，但是内容中间的空格可以正常显示。

**复现步骤**
如上

**预期结果**
开头空格可以显示（小程序没有问题）

**实际结果**
开头的空格不显示

**系统信息:**
发行平台: 5+ App
操作系统 iOS 13 Android 9
HBuilderX版本 2.3.3.20190923
设备信息 iPhone6，华为荣耀10

**Comment by javascriptchen** [comment]
你测得哪端小程序没问题？我试了微信小程序跟app表现一样啊，都是trim的样子

**Comment by magicwing** [comment]
> 你测得哪端小程序没问题？我试了微信小程序跟app表现一样啊，都是trim的样子

代码如下：（注意要加入space=“nbsp” 开头连续2个空格）

<rich-text nodes="{{userInfo}}" space="nbsp" />

 data: {
	userInfo: '<p>  尊敬的客户，在【xxxx-xx-xx xx:xx】</p><p>尊敬的客户，在【xxxx-xx-xx xx:xx】</p>',
  },

小程序是没有问题的
![Screenshot_2019-10-21-15-46-23-264_com tencent mm](https://user-images.githubusercontent.com/7157683/67186147-ff886780-f419-11e9-88eb-38b77e4aa648.png)

**Comment by javascriptchen** [comment]
![image](https://user-images.githubusercontent.com/26818851/67186869-8853d300-f41b-11e9-89f5-981971997f18.png)
```
strings: '  测试   123   000   ',
strings1: '测试   123   000   '
```

**Comment by magicwing** [comment]
同样用了 官方提供的hello  一定要加入space="nbsp" 否则没有效果
![image](https://user-images.githubusercontent.com/7157683/67188735-8be95900-f41f-11e9-8376-49963f214247.png)

**Comment by javascriptchen** [comment]
[https://uniapp.dcloud.io/component/rich-text](https://uniapp.dcloud.io/component/rich-text)
我们的RichText跟微信小程序还是不太一样的，看我们官方文档吧，我们并没有适配这个配置项。所以才会造成小程序端可以用，app端不支持的效果。
