### ISSUE TITLE
日历2月能选31天

### ISSUE THREAD

**Issue by kong-qi** [dcloudio/uni-app#89]
日历控件没有现在日期啊，2月份能选择31天

**Comment by kong-qi** [comment]
![H5的，你自己看看](https://kqdown.oss-cn-shenzhen.aliyuncs.com/picker.jpg
)H5的，你自己看看

**Comment by hbcui1984** [comment]
> ![H5的，你自己看看](https://camo.githubusercontent.com/61e0ae4e45391cfad12f7816dd2345785bd11d43/68747470733a2f2f6b71646f776e2e6f73732d636e2d7368656e7a68656e2e616c6979756e63732e636f6d2f7069636b65722e6a7067)H5的，你自己看看

收到，马上解决

**Comment by kong-qi** [comment]
所有的日期天数都没有做限制，有的只能选30，有个月份只有30天，这个BUG太大了。这日历不搞，没法用

**Comment by zhetengbiji** [comment]
此问题将在下版修复
