### ISSUE TITLE
weex的编译模式下，键盘弹起会将textarea顶上去

### ISSUE THREAD

**Issue by GOGOGOSIR** [dcloudio/uni-app#890]
原因：因为配置页面键盘弹起的api只有这两个
![image](https://user-images.githubusercontent.com/26272801/67187666-488deb00-f41d-11e9-96ab-0c2eafe5af15.png)
结果：这就使得当开启键盘的时候，内容会被顶上去，
![)B(YU6UV@SCCYRX8Z8NL50B](https://user-images.githubusercontent.com/26272801/67187749-796e2000-f41d-11e9-8469-d5c6f470f097.jpg)
![X@U84GNR_{A)5@SE(0P}KV6](https://user-images.githubusercontent.com/26272801/67187761-80952e00-f41d-11e9-866a-48547e34dc33.jpg)

代码：
![image](https://user-images.githubusercontent.com/26272801/67187782-90147700-f41d-11e9-86d4-7e3fc0786a81.png)
![image](https://user-images.githubusercontent.com/26272801/67187816-a4587400-f41d-11e9-8dfa-279fed6e7ca8.png)

**Comment by GOGOGOSIR** [comment]
现在有uniapp编译模式，可以在textarea组件里直接配置adjust-position="false"即可，但是希望官方，能否在
![image](https://user-images.githubusercontent.com/26272801/67187955-f3060e00-f41d-11e9-9f08-d5a73ed56e76.png)zhege这里增加一个不随键盘弹起，页面上顶的配置项，以便解决weex模式编译下的弹起问题，感谢！

**Comment by javascriptchen** [comment]
你是必须使用adjustResize吗？如果不是必须使用，那就换成adjustPan就能解决了

**Comment by GOGOGOSIR** [comment]
感谢您的回复，我的需求是键盘弹起，textarea框不向上顶起，hbuilderx的编辑器，提示选项里有个nothing选项符合我的需求，但是设置了不起作用
![image](https://user-images.githubusercontent.com/26272801/67296066-8cb2e580-f51a-11e9-8208-e2506a7e5cbd.png)

**Comment by GOGOGOSIR** [comment]
今天写代码的时候还发现一个小问题，当一个页面的背景色不是白色的时候，通过uni.navigateTo跳转自带pop-in动画的时候，屏幕会闪一下（白色的），如果换成白色背景，就不会这样，可能是page的背景色默认为白色，当页面加载的时候从白色转变为其他颜色要一定的时候，但这个时候由于路由动画已经开始，也就会有页面闪一下的问题

**Comment by javascriptchen** [comment]
> 感谢您的回复，我的需求是键盘弹起，textarea框不向上顶起，hbuilderx的编辑器，提示选项里有个nothing选项符合我的需求，但是设置了不起作用
> ![image](https://user-images.githubusercontent.com/26272801/67296066-8cb2e580-f51a-11e9-8208-e2506a7e5cbd.png)
[https://uniapp.dcloud.io/component/input?id=%E5%85%B3%E4%BA%8E%E8%BD%AF%E9%94%AE%E7%9B%98%E5%BC%B9%E5%87%BA%E7%9A%84%E9%80%BB%E8%BE%91%E8%AF%B4%E6%98%8E](https://uniapp.dcloud.io/component/input?id=%E5%85%B3%E4%BA%8E%E8%BD%AF%E9%94%AE%E7%9B%98%E5%BC%B9%E5%87%BA%E7%9A%84%E9%80%BB%E8%BE%91%E8%AF%B4%E6%98%8E)
你换一下"softinputMode": "adjustResize"就好了

**Comment by StrivingRabbit** [comment]
由于长时间未回复，此问题关闭，如果还有问题可以重开或者提新issue
