### ISSUE TITLE
nvue中style属性的padding/margin不支持简写

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#891]
`nvue`中`class`选择器中`padding/margin`的简写支持，`style`中只支持`margin:16px`这种，不支持`margin:0 16px`这种。

**Comment by javascriptchen** [comment]
nvue使用的是weex渲染引擎，所以遵守weex的css写法，具体可参考：
[https://weex.apache.org/zh/docs/styles/common-styles.html#%E7%9B%92%E6%A8%A1%E5%9E%8B](https://weex.apache.org/zh/docs/styles/common-styles.html#%E7%9B%92%E6%A8%A1%E5%9E%8B)

**Comment by wakaryry** [comment]
这个主要是class中支持很多简写。到了style中就只支持一种简写。不知道weex中是不是就是这样。

**Comment by zhetengbiji** [comment]
> 这个主要是class中支持很多简写。到了style中就只支持一种简写。不知道weex中是不是就是这样。

可以使用 [Weex Playground](http://dotwe.org/vue) 在手机上测试一下

**Comment by wakaryry** [comment]
是在`weex`中只有`class`支持所有的简写，`style`中只支持`margin: 8px`这一种简写，其他都不支持。
