### ISSUE TITLE
Hbuilder  自定义条件编译平台 UNI_PLATFORM=app-plus不允许

### ISSUE THREAD

**Issue by pillarBoy** [dcloudio/uni-app#892]
**问题描述**
package.json 配置 自定义条件编译平台时出现问题，UNI_PLATFORM=app-plus，不支持

```
"dev-h5": {
	"title":"大大大",
	"env": {
		"UNI_PLATFORM": "app-plus"
	 },
	"define": {
	   "DEV-H5": true
	}
},
"mp-dev": { 
	"title":"钉钉小程序", 
	"env": { 
		"UNI_PLATFORM": "mp-weixin"
	},
	"define": { 
		"MP-DEV": true 
	}
},
```
如上代码，只要`"UNI_PLATFORM": "app-plus"` Hbuild就不会显示这一项，其他基准平台，没有问题

**预期结果**
UNI_PLATFORM修复支持app-plus平台

**实际结果**
![image](https://user-images.githubusercontent.com/18287936/67258000-336a9800-f4c1-11e9-87fe-01d0a157991c.png)

**系统信息:**
 - HBuilderX版本 [2.3.6.20191020]
 - [本人电脑] win10家庭中文版

**Comment by javascriptchen** [comment]
已经反馈给ide组

**Comment by Wangyaqi** [comment]
目前不支持app-plus作为基准平台

**Comment by StrivingRabbit** [comment]
由于长时间未回复，此问题关闭，如果还有问题可以重开或者提新issue
