### ISSUE TITLE
能否增加 iOS端 针对"uni.request"方法的"sslVerify"参数配置

### ISSUE THREAD

**Issue by Saeey** [dcloudio/uni-app#893]
**新功能描述**
iOS端 增加针对"uni.request"方法的"sslVerify"参数配置

**现状及问题**
当前公司使用的ssl证书为个人申请的证书,导致升级到最近版本后无法通讯

**补充信息**
希望尽快升级,万分感谢

**Comment by zhetengbiji** [comment]
升级之前是正常的吗？

**Comment by Saeey** [comment]
是的,升级之前为正常,升级后安卓版本可以通过配置sslVerify为false正常使用,但是iOS无法配置

**Comment by zhetengbiji** [comment]
> 是的,升级之前为正常,升级后安卓版本可以通过配置sslVerify为false正常使用,但是iOS无法配置

升级之前iOS正常吗？正常和不正常的版本号分别是多少？

**Comment by Saeey** [comment]
我现在使用的版本是.
2.1.3.20190723
这个版本是可以正常使用的


升级到最近版本后,
我根据2.3.3.20190923版本的更新提示"App-Android平台 新增 uni.request 网络请求增加参数 sslVerify，配置是否验证 ssl 证书。但建议使用普遍受信的证书而不是忽略证书校验"
在代码中配置了sslVerify: false,
安卓版本可以正常进行网络通讯,但是iOS无法进行网络通讯,最新的版本也是无法进行网络通讯,
在HBuilderX中的控制台中报错如下
"request:fail abort __ERROR"

**Comment by zhetengbiji** [comment]
iOS没有sslVerify也无法增加sslVerify配置，你的证书在iOS的浏览器中能正常使用吗？

**Comment by Saeey** [comment]
我将我的HBuilderX更新到了最新版本(2.3.6.20191020)
进行了运行到不同平台的测试
运行到Android设备:正常网络通讯(可以通过https协议调用自己服务器的登录接口以及其他服务)
运行到iOS设备:通讯失败
运行到内置浏览器:通讯失败
运行到内置浏览器后通过iOS设备的浏览器进行局域网访问:通讯失败(- Network: http://192.168.1.170:8080/)
运行到内置浏览器后通过Android设备的浏览器进行局域网访问:通讯失败
运行到Chrome浏览器:通讯失败

**Comment by zhetengbiji** [comment]
> 我将我的HBuilderX更新到了最新版本(2.3.6.20191020)
> 进行了运行到不同平台的测试
> 运行到Android设备:正常网络通讯(可以通过https协议调用自己服务器的登录接口以及其他服务)
> 运行到iOS设备:通讯失败
> 运行到内置浏览器:通讯失败
> 运行到内置浏览器后通过iOS设备的浏览器进行局域网访问:通讯失败(- Network: http://192.168.1.170:8080/)
> 运行到内置浏览器后通过Android设备的浏览器进行局域网访问:通讯失败
> 运行到Chrome浏览器:通讯失败

可能是你们的证书有问题，你试试小程序呢，另外在app平台也可以试试http://www.html5plus.org/doc/zh_cn/xhr.html

**Comment by Saeey** [comment]
我用XMLHttpRequest替换了uni.request,已经可以正常使用了,万分感谢XD
