### ISSUE TITLE
支付宝小程序中中 nodesRef.fields(object,callback) dataset 无返回

### ISSUE THREAD

**Issue by smallos** [dcloudio/uni-app#894]
**问题描述**
获取位置么，微信里面可以获得dataset，但是支付宝小程序没有返回

**复现步骤**
[复现问题的步骤]
1.  启动 '
let view = uni.createSelectorQuery().in(this).selectAll(`.demo`);
view.fields({
          rect: true,
          dataset: true,
          computedStyle: true,
        }, data => {
console.log(data)
}'

入下图，一边是微信，有返回dataset字段，但是支付宝x小程序无返回
![image](https://user-images.githubusercontent.com/12025733/67277248-ff12ce00-f4f8-11e9-9eba-4fff3f56daa9.png)

**系统信息:**
 - 发行平台: 微信小程序、支付宝小程序

 - uni-app版本

uni-app v2.3.6
uni-app cli v2.0.0-23620191020003

**补充信息**
请问下，这块源码有哪里可以看到吗？如果那边可以看到可以自己去查看问题

**Comment by Wangyaqi** [comment]
支付宝小程序本身不支持`fields`, 目前的`fields`返回值是我们封装的。现在没法在这里获取dataSet，文档已补充，感谢反馈
