### ISSUE TITLE
css fontfamily在android真机上失效

### ISSUE THREAD

**Issue by weypro** [dcloudio/uni-app#896]
**问题描述**
uniapp编写的项目以h5方式在chrome上可以正常显示fontfamily指定的字体（比如楷体），而在华为手机android8.1上却无法正常显示，一直是默认字体，请问如何解决？
hbuilderx2.3.3，试过全局css，然而并没有用

**Comment by zhetengbiji** [comment]
使用普通的html测试，看是否正常

**Comment by weypro** [comment]
> 使用普通的html测试，看是否正常

正常

**Comment by zhetengbiji** [comment]
上传一个示例工程

**Comment by weypro** [comment]
问题解决
在https://transfonter.org/上转换字体为base64位css引入指定@font-face即可
