### ISSUE TITLE
uni.startPullDownRefresh() 在h5页面只会触发一次，success和complete都执行了，但是onPullDownRefresh里面的方法没有执行

### ISSUE THREAD

**Issue by zhangyq233** [dcloudio/uni-app#899]
uni.startPullDownRefresh() 在h5页面只会触发一次，success和complete都执行了，但是onPullDownRefresh里面的方法没有执行

最新版本IDE

**Comment by javascriptchen** [comment]
这个应该是你代码写的有毛病，你log下，看看有没有执行方法

**Comment by zhangyq233** [comment]
> 这个应该是你代码写的有毛病，你log下，看看有没有执行方法

你好  真的没有执行  我有log了。  在社区也有很多人反应，但是没有人解答。   需要setTimout 200 才会触发

**Comment by zhangyq233** [comment]
> 这个应该是你代码写的有毛病，你log下，看看有没有执行方法

在微信小程序端都可以触发  就是在h5端只会触发一次，关闭页面在进入 就不会触发了

**Comment by zhangyq233** [comment]
> 这个应该是你代码写的有毛病，你log下，看看有没有执行方法

步骤：
1、在B页面onLoad 编写uni.startPullDownRefresh()
2、第一次从A页面进入B页面，会触发下拉刷新
3、关闭B页面，再次从A页面进入B页面，不会触发下拉刷新了
4、在h5端才会这样，微信小程序不会这样
5、现在兼容方式 setTimeout uni.startPullDownRefresh()

**Comment by javascriptchen** [comment]
> > 这个应该是你代码写的有毛病，你log下，看看有没有执行方法
> 
> 步骤：
> 1、在B页面onLoad 编写uni.startPullDownRefresh()
> 2、第一次从A页面进入B页面，会触发下拉刷新
> 3、关闭B页面，再次从A页面进入B页面，不会触发下拉刷新了
> 4、在h5端才会这样，微信小程序不会这样
> 5、现在兼容方式 setTimeout uni.startPullDownRefresh()

好的，我试试

**Comment by StrivingRabbit** [comment]
现在还有这个问题吗？
