### ISSUE TITLE
安装失败 return code=-402620395

### ISSUE THREAD

**Issue by BrightYang0801** [dcloudio/uni-app#902]
HBuilderX版本2.0.1运行到真机调试（苹果8plus） ，昨天还是好的，今天卸载了官方基座重新装提示 安装失败 return code=-402620395

**Comment by javascriptchen** [comment]
要不你更新下最新版HBuilder试试？

**Comment by dcloudhdx** [comment]
之前是否使用了自定义基座，如果是重新打基座，或试试非自定义基座

**Comment by BrightYang0801** [comment]
最新版的HBuilder可以了
