### ISSUE TITLE
键盘隐藏api失效

### ISSUE THREAD

**Issue by 2410655661** [dcloudio/uni-app#903]
1.在methods中调用uni.hideKeyboard()方法；
2.安卓手机正常，隐藏掉调用的手机键盘

3.苹果手机出现异常，手机键盘没有隐藏掉，无任何报错；

**Comment by zhetengbiji** [comment]
已确认，先使用 [plus.key.hideSoftKeybord](http://www.html5plus.org/doc/zh_cn/key.html#plus.key.hideSoftKeybord)

**Comment by zhetengbiji** [comment]
HBuilderX 2.3.8 alpha 已修复

**Comment by cntlis** [comment]
安卓下也不能用啊
