### ISSUE TITLE
官方这种写法，编译会报错！

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-app#904]
![image](https://user-images.githubusercontent.com/24872469/67555031-25c44500-f743-11e9-801f-0743411adbb8.png)
报错
![image](https://user-images.githubusercontent.com/24872469/67555055-2fe64380-f743-11e9-89e8-3f33e854bc0c.png)
请问应该怎么写

**Comment by zhetengbiji** [comment]
行尾加上逗号

**Comment by huanghaodong** [comment]
> 行尾加上逗号

行尾加逗号，也会报错
![image](https://user-images.githubusercontent.com/24872469/67555820-9c157700-f744-11e9-9e94-0544e107c7de.png)
![image](https://user-images.githubusercontent.com/24872469/67555833-a59edf00-f744-11e9-997f-0ac6e71c35f6.png)

**Comment by zhetengbiji** [comment]
单独引入每个都正常吗？

**Comment by huanghaodong** [comment]
> 单独引入每个都正常吗？

单独引入正常

**Comment by StrivingRabbit** [comment]
逗号加在 #ifdef 里面，否则解析json文件时，多一个无用逗号解析失败
