### ISSUE TITLE
在 uni-app 中使用 easy-mock

### ISSUE THREAD

**Issue by wangkaiChen1118** [dcloudio/uni-app#905]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
使用 easy-mock 官网模拟一个在线的接口，微信小程序端和h5端请求正常，可以拿到回调，ios真机调试报错 request:fail abort __ERROR
**复现步骤**
[复现问题的步骤]
1，在 easymock 官网模拟一个 get 请求接口
https://www.easy-mock.com/mock/5db29ee9d9f3aa5b4d90372e/super-hero/index/swiper/list
![image](https://user-images.githubusercontent.com/51146877/67557780-4a6eeb80-f748-11e9-880e-8e476437c2fd.png)

2，在项目的首页 onLoad() 生命周期中发送请求
onLoad() {
			uni.request({
				method:"GET",
				url:"https://www.easy-mock.com/mock/5db29ee9d9f3aa5b4d90372e/super-hero/index/swiper/list",
				success:(res)=>{
					console.log(res)
					this.imgs = res.data.list
				}
			})
		}

3，实际效果看下图

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
微信小程序端
![image](https://user-images.githubusercontent.com/51146877/67556913-991b8600-f746-11e9-842a-773c42f74695.png)
![image](https://user-images.githubusercontent.com/51146877/67556930-a33d8480-f746-11e9-94df-307ce55fbcf8.png)

h5 端
![image](https://user-images.githubusercontent.com/51146877/67557007-c9632480-f746-11e9-9c7e-6951d4605eb7.png)

ios 真机调试
![image](https://user-images.githubusercontent.com/51146877/67554955-f6153d00-f742-11e9-9bc9-26dd76f4f924.png)

**系统信息:**
 - 发行平台: 微信小程序，chrome h5 ，ios真机调试
 - 操作系统 ios 13.1.3
 - HBuilderX版本 2.3.7.20191024
 - uni-app版本uni-app 用的是hbuilderX 生成的默认模板项目
 - 设备信息  iPhone6Plus

**Comment by javascriptchen** [comment]
后端接口https 数字证书，没有被信任导致的 没有发起request请求。 更换证书问题解决。
easy-mock的数字证书有问题

**Comment by zhetengbiji** [comment]
![image](https://user-images.githubusercontent.com/6326057/67615938-05f55580-f805-11e9-86b6-9e08f99dc825.png)

**Comment by wakaryry** [comment]
可以尝试使用rap2

**Comment by wangkaiChen1118** [comment]
> ok 感谢，使用 rap2 完美解决

**Comment by wangkaiChen1118** [comment]
> 可以尝试使用rap2

使用 rap2 完美解决，感谢!!!
