### ISSUE TITLE
vue组件内使用支付宝组件，支付宝组件如何向vue组件传参

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-app#906]
vue组件内使用支付宝组件，支付宝组件如何向vue组件传参？支付宝小程序文档说的子组件是调用父组件方法实现传参。

.vue文件
![image](https://user-images.githubusercontent.com/24872469/67613887-886e1d00-f7e5-11e9-8f06-d4463aba4b31.png)
![image](https://user-images.githubusercontent.com/24872469/67613899-bf443300-f7e5-11e9-81c1-2e1d2c5d6556.png)

支付宝组件.js
![image](https://user-images.githubusercontent.com/24872469/67561983-75f5d400-f750-11e9-8093-866081991016.png)

这样写出现如下提示:
![image](https://user-images.githubusercontent.com/24872469/67613884-73918980-f7e5-11e9-8c8b-b8ccf1ec5a13.png)

文档没有相关写法，是否不支持支付宝组件向vue文件传参？

**Comment by javascriptchen** [comment]
你把这个支付宝组件改成vue组件就好了

**Comment by javascriptchen** [comment]
支付宝文档说的是，uni-app编译出来支付宝项目中的的父组件，你这样写是不行的

**Comment by huanghaodong** [comment]
> 你把这个支付宝组件改成vue组件就好了

要用支付宝原生button，所以改不了

**Comment by huanghaodong** [comment]
> 支付宝文档说的是，uni-app编译出来支付宝项目中的的父组件，你这样写是不行的

是不行，所以就想知道该怎么写

**Comment by javascriptchen** [comment]
你用uniapp自带的button组件啊，button组件在各个小程序端都是用的各个小程序自己的button的，你试试就知道了

**Comment by zhetengbiji** [comment]
参考一下文档：[https://uniapp.dcloud.io/frame?id=小程序组件支持](https://uniapp.dcloud.io/frame?id=小程序组件支持)
