### ISSUE TITLE
button组件，支持支付宝open-type="getAuthorize"，却不支持授权成功和失败的回调。

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-app#908]
button组件，文档说支持支付宝小程序open-type="getAuthorize"，却不支持授权成功回调onGetAuthorize和失败回调onError，我要getAuthorize有何用？！
![image](https://user-images.githubusercontent.com/24872469/67612719-aa60a300-f7d7-11e9-921c-fd93a9a53287.png)

支付宝开发工具：
![image](https://user-images.githubusercontent.com/24872469/67612726-cc5a2580-f7d7-11e9-88f9-5edf8d6ebee0.png)

**Comment by zhetengbiji** [comment]
如果是在vue中使用，使用@xxx替代onXxx

**Comment by huanghaodong** [comment]
> 如果是在vue中使用，使用@xxx替代onXxx

确实可以。谢谢。但是改成@仍无法解决这个[https://github.com/dcloudio/uni-app/issues/906](https://github.com/dcloudio/uni-app/issues/906)，还麻烦您看一下
