### ISSUE TITLE
开发小程序编译时提示：文件查找失败

### ISSUE THREAD

**Issue by yimihua001** [dcloudio/uni-app#91]
文件查找失败：'fs' at ..\HBuilderX\plugins\uniapp\node_modules\debug\src\node.js
文件查找失败：'net' at ..\HBuilderX\plugins\uniapp\node_modules\debug\src\node.js
不知道该如何处理，麻烦帮忙解决，谢谢！

**Comment by zxzhgk** [comment]
你node安装了么

**Comment by zxzhgk** [comment]
或者可能是你本地node版本太低

**Comment by xiaoyucoding** [comment]
从错误日志看，是因为在 uni-app 中引入了 Node.js 环境才可用的模块。
fs、net 这种都是 Node.js 环境才存在的模块，uni-app 属于前端框架，也就是说通过 npm 引入的模块都必须是浏览器环境可用的。

**Comment by hbcui1984** [comment]
长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
