### ISSUE TITLE
在weex模式下使用slider组件嵌套会出现卡顿

### ISSUE THREAD

**Issue by GOGOGOSIR** [dcloudio/uni-app#911]
问题：
当我使用slider组件嵌套做一个页面切换的时候，当外部的那个slider切换了三次后，返回其内部的slider在切换第一帧的动画缺失
代码：
![image](https://user-images.githubusercontent.com/26272801/67633675-acb52100-f8ed-11e9-991e-a9965f443c21.png)

demo:
[demo.zip](https://github.com/dcloudio/uni-app/files/3775745/demo.zip)

**Comment by GOGOGOSIR** [comment]
朋友，这个问题能够优化吗？感谢！

**Comment by GOGOGOSIR** [comment]
内部嵌套的那个slider在外部的slider滑动大于2次时，切回内部嵌套的slider，滑动的第一帧动画丢失，下面我做了个小demo,供验证这个问题

**Comment by ArrayDC** [comment]
weex模式已不再维护，请更新到最新版本HBuilderX使用uni-app模式。
