### ISSUE TITLE
uni.requestPayment  APP拉起微信支付文档不正确

### ISSUE THREAD

**Issue by jinbiaode** [dcloudio/uni-app#913]
App 支付

uni.requestPayment({
    provider: 'alipay',
    orderInfo: 'orderInfo', //微信、支付宝订单数据
    success: function (res) {
        console.log('success:' + JSON.stringify(res));
    },
    fail: function (err) {
        console.log('fail:' + JSON.stringify(err));
    }
});

上述是文档中标注的方法！  完全不对。根本不是这样的，问了好多人 百度了好久  
发现orderInfo 字段里  根本不是填单号，而是填很多下单的数据，真坑啊！
赶紧把这个app文档完善，感谢！！！！！！！！！！！

**Comment by CheJJ** [comment]
你直接提pr就行，他们文档底部不是有个编辑么

**Comment by jewei-coder** [comment]
支付宝是填单号,微信不是.

**Comment by dcloudhdx** [comment]
文档已更新 `https://uniapp.dcloud.io/api/plugins/payment?id=orderinfo`
App端，支付宝支付 orderInfo 为 String 类型。
App端，微信支付 orderInfo 为 Object 类型。
