### ISSUE TITLE
【Android Bug】安卓下Tabbar页面存在性能问题，滚动卡顿

### ISSUE THREAD

**Issue by hangaoke1** [dcloudio/uni-app#915]
**问题描述**
2.3.5之后安卓下tabbar页面滚动存在卡顿现象，同样的代码在非tabbar页面运行流畅，版本回退到2.3.5之前tabbar页面也运行流畅

**复现步骤**
[复现问题的步骤]
无

**预期结果**
tabbar页面同非tabbar页面一样流畅

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [5+ App]
 - 操作系统 [Android 8.0]
 - HBuilderX版本 [如使用HBuilderX 3.5.7]
 - 设备信息 [小米 8]

**补充信息**
tabbar页面负优化，代码存在性能问题

**Comment by zhetengbiji** [comment]
参考一下：https://ask.dcloud.net.cn/article/36537

**Comment by StrivingRabbit** [comment]
由于长时间未回复，此问题关闭，如果还有问题可以重开或者提新issue
