### ISSUE TITLE
uni-app使用支付宝官方扩展组件提示事件信息不存在

### ISSUE THREAD

**Issue by chen-can** [dcloudio/uni-app#917]
引入官方card组件，执行点击事件
![image](https://user-images.githubusercontent.com/35422769/67663029-851e9100-f99f-11e9-95bc-3e331fd9b6ae.png)
这个问题前3个月已经提出了 怎么还没有回复 是不支持小程序自定义组件mycomponents 吗
如果是请修改文档 以免后续开发者不断踩坑

**Comment by chen-can** [comment]
https://github.com/dcloudio/uni-app/issues/790 还有这个问题 至今没有给出回复

**Comment by andyWHJ** [comment]
麻烦官方给个回复，谢谢

**Comment by mehaotian** [comment]
目前先这样绕过解决一下,在 `onLoad` 添加如下代码 `this.$scope.cardClick = this.cardClick.bind(this)`

其他组件的其他方法类似 ，先手动把事件绑定到 `this.$scope` 上面

```html
<template>
	<view class="content">
		<image class="logo" src="/static/logo.png"></image>
		<view>
			<text class="title">{{title}}</text>
		</view>
     <card
       :thumb="title"
       title="卡片标题2"
       subTitle="副标题非必填2"
       onClick="cardClick"
       info="点击了第二个card"
     />
	</view>
</template>

<script>
	export default {
		data() {
			return {
				title: 'Hello'
			}
		},
		onLoad() {
			this.$scope.cardClick = this.cardClick.bind(this)
		},
		methods: {
			cardClick(){
				console.log('卡片被点击了');
			}
		}
	}
</script>

```

**Comment by tyust512** [comment]
请问你是在页面的onLoad生命周期加了这代码，就解决了？能说下原理吗

**Comment by 3crazyspecial** [comment]
请问这个问题还是只能绕过吗？

**Comment by zhetengbiji** [comment]
> 请问这个问题还是只能绕过吗？
> 
> 目前这个方式在不使用 store 的场景下是可行的，不过有 store 后函数就不对了

很久以前已经修复

**Comment by 3crazyspecial** [comment]
> 

这个是什么版本呢？

**Comment by 3crazyspecial** [comment]
> > 请问这个问题还是只能绕过吗？
> > 目前这个方式在不使用 store 的场景下是可行的，不过有 store 后函数就不对了
> 
> 很久以前已经修复

我目前发现还是不行，主要是 Vue 的  store，目前发现编译后的代码执行回调函数是 publicInstance 中我的 method 是 undefinded

![image](https://user-images.githubusercontent.com/26181170/197106428-8249840b-cf1b-4680-ab79-85cfe042e86a.png)

目前不知道是啥原因，这个修复的版本是多少呢？

**Comment by zhetengbiji** [comment]
> > > 请问这个问题还是只能绕过吗？
> > > 目前这个方式在不使用 store 的场景下是可行的，不过有 store 后函数就不对了
> > 
> > 
> > 很久以前已经修复
> 
> 我目前发现还是不行，主要是 Vue 的 store，目前发现编译后的代码执行回调函数是 publicInstance 中我的 method 是 undefinded
> 
> ![image](https://user-images.githubusercontent.com/26181170/197106428-8249840b-cf1b-4680-ab79-85cfe042e86a.png)
> 
> 目前不知道是啥原因，这个修复的版本是多少呢？

建议使用最新的alpha版测试一下，另外你的代码写法看一下，是不是监听事件的方式错了

**Comment by 3crazyspecial** [comment]
> > > > 请问这个问题还是只能绕过吗？
> > > > 目前这个方式在不使用 store 的场景下是可行的，不过有 store 后函数就不对了
> > > 
> > > 
> > > 很久以前已经修复
> > 
> > 
> > 我目前发现还是不行，主要是 Vue 的 store，目前发现编译后的代码执行回调函数是 publicInstance 中我的 method 是 undefinded
> > ![image](https://user-images.githubusercontent.com/26181170/197106428-8249840b-cf1b-4680-ab79-85cfe042e86a.png)
> > 目前不知道是啥原因，这个修复的版本是多少呢？
> 
> 建议使用最新的alpha版测试一下，另外你的代码写法看一下，是不是监听事件的方式错了

代码监听方式没有问题的，用的一个空项目，目前发现精简代码后发现，不使用 Router 就没问题

**Comment by zhetengbiji** [comment]
> > > > > 请问这个问题还是只能绕过吗？
> > > > > 目前这个方式在不使用 store 的场景下是可行的，不过有 store 后函数就不对了
> > > > 
> > > > 
> > > > 很久以前已经修复
> > > 
> > > 
> > > 我目前发现还是不行，主要是 Vue 的 store，目前发现编译后的代码执行回调函数是 publicInstance 中我的 method 是 undefinded
> > > ![image](https://user-images.githubusercontent.com/26181170/197106428-8249840b-cf1b-4680-ab79-85cfe042e86a.png)
> > > 目前不知道是啥原因，这个修复的版本是多少呢？
> > 
> > 
> > 建议使用最新的alpha版测试一下，另外你的代码写法看一下，是不是监听事件的方式错了
> 
> 代码监听方式没有问题的，用的一个空项目，目前发现精简代码后发现，不使用 Router 就没问题

使用的 uni-app 版本多少？
怎么监听的事件？

**Comment by zhetengbiji** [comment]
> 编辑器版本 3.6.4.20220922，下图中 mycom 是支付宝原生组件，组件内部正常执行，但是回调函数没有执行，根据上面的判断是没有找到相关函数，目前做依赖判断的时候发现添加 uni-simple-router 后开始不符合预期
> 
> ```
> <template>
> 	<view class="content">
> 		<image class="logo" src="/static/logo.png"></image>
> 		<view class="text-area">
> 			<text class="title">{{title}}</text>
> 		</view>
> 		<mycom onLoad="onLoad" ></mycom>
> 	</view>
> </template>
> 
> <script>
> 	let pluginIns;
> 	export default {
> 		data() {
> 			return {
> 			}
> 		},
> 		onLoad() {
> 			this.$scope.onLoad = this.onLoad.bind(this)
> 		},
> 		methods: {
> 			onLoad: () => {
>                                  console.log('onLoad')
> 			}
> 		}
> 	}
> </script>
> ```

1. 你这事件写法是错误的，应该用 v-on（@） 的方式监听事件
2. 不建议用和生命周期同名的方法
3. 建议升级到 3.6.7

修改后如下：

```html
<template>
	<view class="content">
		<image class="logo" src="/static/logo.png"></image>
		<view class="text-area">
			<text class="title">{{title}}</text>
		</view>
		<mycom @load="onMyLoad" ></mycom>
	</view>
</template>

<script>
	let pluginIns;
	export default {
		data() {
			return {
			}
		},
		methods: {
			onMyLoad: () => {
                                 console.log('onLoad')
			}
		}
	}
</script>
```

**Comment by 3crazyspecial** [comment]
使用 1 的方式会提示时间信息不存在，使用的是本 issue 前面的绑定方法，2 已经修改，3 已经升级，router 存在情况下还能不能正常回调

**Comment by zhetengbiji** [comment]
> 使用 1 的方式会提示时间信息不存在，使用的是本 issue 前面的绑定方法，2 已经修改，3 已经升级，router 存在情况下还能不能正常回调

测试工程提供一下

**Comment by 3crazyspecial** [comment]
> 

https://github.com/3crazyspecial/uni-test-demo

可以查看这个 demo，第一次 commit 是没有添加 router 可以正常回调，第二次添加后无法正常回调，谢谢

**Comment by zhetengbiji** [comment]
> > 
> 
> https://github.com/3crazyspecial/uni-test-demo
> 
> 可以查看这个 demo，第一次 commit 是没有添加 router 可以正常回调，第二次添加后无法正常回调，谢谢

经过测试你自行挂载到 this.$scope 的方式被三方库影响了。

使用 v-on 的方式监听事件不受影响，但是存在触发时机较早会报错的 bug，将在下个版本修复

临时解决办法：使用 v-on 的方式监听，并增加延迟

```html
<template>
	<view class="content">
		<image class="logo" src="/static/logo.png"></image>
		<view class="text-area">
			<text class="title">{{title}}</text>
		</view>
		<!-- 支付宝原生组件 -->
		<demo @hello="handleHello" @xxx="xx"></demo>
		<view v-if="callbackSuccess">回调成功</view>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				callbackSuccess: false
			}
		},
		methods: {
			handleHello(){
				console.log('outer hello');
				this.callbackSuccess = true;
			}
		}
	}
</script>

<style>
	.content {
		display: flex;
		flex-direction: column;
		align-items: center;
		justify-content: center;
	}

	.logo {
		height: 200rpx;
		width: 200rpx;
		margin-top: 200rpx;
		margin-left: auto;
		margin-right: auto;
		margin-bottom: 50rpx;
	}

	.text-area {
		display: flex;
		justify-content: center;
	}

	.title {
		font-size: 36rpx;
		color: #8f8f94;
	}
</style>

```

```js
Component({
	props: {
		onHello: () => {
			console.log('inner hello');
		}
	},
	didMount() {
		console.log(this.props);
		setTimeout(() => {
			this.props.onHello();
		}, 0)
	}
})
```
