### ISSUE TITLE
v-for遍历对象时，(value, key,  index) in obj，index永远为undefined

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-app#918]
v-for遍历对象时，(value, key,  index) in obj，index永远为undefined
编译环境：微信小程序
HBuilderX：2.3.7.20191024

**Comment by javascriptchen** [comment]
在非H5平台 循环对象时不支持第三个参数，如 v-for="(value, name, index) in object" 中，index 参数是不支持的。
(https://uniapp.dcloud.io/use?id=%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9)[https://uniapp.dcloud.io/use?id=%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9]

**Comment by huanghaodong** [comment]
好吧
