### ISSUE TITLE
video标签结合 v-for 指令的使用，导致布局异常

### ISSUE THREAD

**Issue by wangkaiChen1118** [dcloudio/uni-app#922]
**问题描述**
video标签配合 v-for 指令列表渲染 视频 ，在ios真机上的布局异常的bug

**复现步骤**
1，以下是标签结合 v-for 指令的使用
![image](https://user-images.githubusercontent.com/51146877/67751440-13f8df80-fa6c-11e9-8f66-1af582cc8c04.png)

<view v-for="item in trailers" :key="item.id">
   <video :src="item.video" :poster="item.poster" controls></video>
</view>

2，以下是  trailers 数组中每个 item 对象
  {
      "name": "Patricia Perez",
      "id": 5012,
      "video": "https://webstatic.bh3.com/video/bh3.com/pv/2.9pv.mp4",
      "poster": "https://static-event.benghuai.com/bh3_homepage/images/pic/picture/39.png"
    }

3，
在 chrome的 h5页面上显示正常
![image](https://user-images.githubusercontent.com/51146877/67748608-443d7f80-fa66-11e9-8418-6e3d7a7b8262.png)
在 微信小程序上显示正常
![image](https://user-images.githubusercontent.com/51146877/67748715-85ce2a80-fa66-11e9-8f61-17ed4bd4f62a.png)
在 ios 真机调试上的效果
![image](https://user-images.githubusercontent.com/51146877/67751957-098b1580-fa6d-11e9-81c8-e150b34bc70e.png)

**系统信息:**
 - 发行平台: ios
 - 操作系统 ios 13.1.3 
 - HBuilderX版本 2.3.7.20191024
 - uni-app版本 uni-app 是hbuilderX 创建的项目，是最新的版本
 - 设备信息 iponeX   iphone6plus 

**补充信息**
可以确定不是样式导致的bug，但是其他方面排查不出来，
iponeX 和 iphone6plus 上都测试过，都有这个bug，
另外 安卓的真机调试也测了，三星s8+，无此bug
![image](https://user-images.githubusercontent.com/51146877/67751225-aa78d100-fa6b-11e9-802b-d2e9e99a583f.png)

**Comment by Wangyaqi** [comment]
写上playsinline试试

**Comment by wangkaiChen1118** [comment]
> **问题描述**
> video标签配合 v-for 指令列表渲染 视频 ，在ios真机上的布局异常的bug
> 
> **复现步骤**
> [复现问题的步骤]
> 1，以下是标签结合 v-for 指令的使用
> 
> 
> 2，以下是 trailers 数组中每个 item 对象
> {
> "name": "Patricia Perez",
> "id": 5012,
> "video": "https://webstatic.bh3.com/video/bh3.com/pv/2.9pv.mp4",
> "poster": "https://static-event.benghuai.com/bh3_homepage/images/pic/picture/39.png"
> }
> 
> 3，
> 在 chrome的 h5页面上显示正常
> ![image](https://user-images.githubusercontent.com/51146877/67748608-443d7f80-fa66-11e9-8418-6e3d7a7b8262.png)
> 在 微信小程序上显示正常
> ![image](https://user-images.githubusercontent.com/51146877/67748715-85ce2a80-fa66-11e9-8f61-17ed4bd4f62a.png)
> 在 ios 真机调试上的效果
> ![image](https://user-images.githubusercontent.com/51146877/67751749-ab5e3280-fa6c-11e9-936f-20f79fa0e5f9.png)

> 
> **系统信息:**
> 
> * 发行平台: ios
> * 操作系统 ios 13.1.3
> * HBuilderX版本 2.3.7.20191024
> * uni-app版本 uni-app 是hbuilderX 创建的项目，是最新的版本
> * 设备信息 iponeX   iphone6plus
> 
> **补充信息**
> 可以确定不是样式导致的bug，但是其他方面排查不出来，
> iponeX 和 iphone6plus 上都测试过，都有这个bug，
> 另外 安卓的真机调试也测了，无此bug
> ![image](https://user-images.githubusercontent.com/51146877/67751225-aa78d100-fa6b-11e9-802b-d2e9e99a583f.png)

**Comment by wangkaiChen1118** [comment]
> 写上playsinline试试

请问是 display:inline  吗

**Comment by Wangyaqi** [comment]
[https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/video](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/video)
在这个文章内找

**Comment by wangkaiChen1118** [comment]
> 写上playsinline试试

![image](https://user-images.githubusercontent.com/51146877/67758469-b0c17a00-fa78-11e9-83a6-e59c39ee96fd.png)

![image](https://user-images.githubusercontent.com/51146877/67757384-ac945d00-fa76-11e9-96d6-a64b727a3b27.png)

**Comment by Wangyaqi** [comment]
webkit-playsinline也写上看看，还不行可以把项目精简之后发上来我们看一下

**Comment by wangkaiChen1118** [comment]
> webkit-playsinline也写上看看，还不行可以把项目精简之后发上来我们看一下

[super-hero.zip](https://github.com/dcloudio/uni-app/files/3786688/super-hero.zip)

**Comment by wangkaiChen1118** [comment]
> > webkit-playsinline也写上看看，还不行可以把项目精简之后发上来我们看一下
> 
> [super-hero.zip](https://github.com/dcloudio/uni-app/files/3786688/super-hero.zip)

另外，如果不适用 v-for 指令， 这个地方直接 cv 放四个视频，是没有这个bug 的

**Comment by wangkaiChen1118** [comment]
> > > webkit-playsinline也写上看看，还不行可以把项目精简之后发上来我们看一下
> > 
> > 
> > [super-hero.zip](https://github.com/dcloudio/uni-app/files/3786688/super-hero.zip)
> 
> 另外，如果不适用 v-for 指令， 这个地方直接 cv 放四个视频，是没有这个bug 的

还有就是，我用同样的结构代码，放在第二个 tab 页面中，也无此bug，可以多 c v 几次

**Comment by wangkaiChen1118** [comment]
> webkit-playsinline也写上看看，还不行可以把项目精简之后发上来我们看一下

![image](https://user-images.githubusercontent.com/51146877/67826091-566efa80-fb06-11e9-9e56-0934dd86c817.png)
我代码都没动过，这又变好了？？ 我昨天测试了很多遍，都不行，手机重启也不行，今天早上打开也不行，刚才重新打开，突然又变好了，我晕了

**Comment by wangkaiChen1118** [comment]
> > webkit-playsinline也写上看看，还不行可以把项目精简之后发上来我们看一下
> 
> ![image](https://user-images.githubusercontent.com/51146877/67826091-566efa80-fb06-11e9-9e56-0934dd86c817.png)
> 我代码都没动过，这又变好了？？ 我昨天测试了很多遍，都不行，手机重启也不行，今天早上打开也不行，刚才重新打开，突然又变好了，我晕了

![image](https://user-images.githubusercontent.com/51146877/67826299-03497780-fb07-11e9-9981-435dbb24b34f.png)
果然，多测试几次，又不行了

**Comment by Wangyaqi** [comment]
嗯，我们正在排查是什么问题

**Comment by wangkaiChen1118** [comment]
> 嗯，我们正在排查是什么问题

辛苦

**Comment by Wangyaqi** [comment]
给super hero那块的scroll-view写上高度

**Comment by wangkaiChen1118** [comment]
> 给super hero那块的scroll-view写上高度

这段时间在写其他东西，感谢感谢!!!

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
