### ISSUE TITLE
H5 build 开启 treeShaking，编译失败

### ISSUE THREAD

**Issue by CaptainLiao** [dcloudio/uni-app#923]
**问题描述**
H5 build 开启 treeShaking，编译失败

**复现步骤**
manifest.json 添加 H5 treeShaking：
````
	"h5": {
		"optimization": {
			"treeShaking": {
				"enable": true
			}
		}
	}
````

执行 npm run build
````

|  开始编译当前项目至 h5 平台...

 ERROR  Failed to compile with 1 errors                                                                                                                            17:04:49
 error  in ./node_modules/@dcloudio/uni-h5/src/platforms/h5/components/app/index.vue?vue&type=style&index=0&id=06e9f3d8&scoped=true&lang=css&

Module build failed (from ./node_modules/postcss-loader/src/index.js):
Error: Failed to find '~uni-core/view/index.css'
  in [
    F:\demo\boilerplate-code\uniapp-project\node_modules\@dcloudio\uni-h5\src\platforms\h5\components\app
  ]
    at resolveModule.catch.catch (F:\demo\boilerplate-code\uniapp-project\node_modules\postcss-import\lib\resolve-id.js:35:13)
    at <anonymous>
````

删除 treeShaking 配置后，编译成功。

多次尝试（删除 node_modules/ ; 重新创建项目等）均如此。

**环境**
uni-app v2.3.7
uni-app cli v2.0.0-23720191024001

Environment Info:

  System:
    OS: Windows 10
    CPU: (4) x64 Intel(R) Core(TM) i5-4590 CPU @ 3.30GHz
  Binaries:
    Node: 8.12.0 - E:\Program Files\node-v8.12.0-win-x64\node.EXE
    Yarn: 1.6.0 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 6.4.1 - E:\Program Files\node-v8.12.0-win-x64\npm.CMD
  Browsers:
    Edge: 42.17134.1.0
  npmPackages:
    @dcloudio/uni-app-plus: ^2.0.0-23720191024001 => 2.0.0-23720191024001
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: ^2.0.0-23720191024001 => 2.0.0-23720191024001
    @dcloudio/uni-h5: ^2.0.0-23720191024001 => 2.0.0-23720191024001
    @dcloudio/uni-helper-json: * => 1.0.3
    @dcloudio/uni-mp-alipay: ^2.0.0-23720191024001 => 2.0.0-23720191024001
    @dcloudio/uni-mp-baidu: ^2.0.0-23720191024001 => 2.0.0-23720191024001
    @dcloudio/uni-mp-qq: ^2.0.0-23720191024001 => 2.0.0-23720191024001
    @dcloudio/uni-mp-toutiao: ^2.0.0-23720191024001 => 2.0.0-23720191024001
    @dcloudio/uni-mp-weixin: ^2.0.0-23720191024001 => 2.0.0-23720191024001
    @dcloudio/uni-stat: ^2.0.0-23720191024001 => 2.0.0-23720191024001
    @dcloudio/uni-template-compiler: ^2.0.0-23720191024001 => 2.0.0-23720191024001
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-23720191024001 => 2.0.0-23720191024001
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-23720191024001 => 2.0.0-23720191024001
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-23720191024001 => 2.0.0-23720191024001
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-23720191024001 => 2.0.0-23720191024001
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-23720191024001 => 2.0.0-23720191024001
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.12.1
    @vue/babel-preset-jsx:  1.1.1
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.1.1
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  4.0.5
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-plugin-router:  4.0.5
    @vue/cli-plugin-vuex:  4.0.5
    @vue/cli-service: ^4.0.0 => 4.0.5
    @vue/cli-shared-utils:  4.0.5
    @vue/component-compiler-utils:  3.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.1
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1

**Comment by CaptainLiao** [comment]
@fxy060608 麻烦看一下

**Comment by zhetengbiji** [comment]
新建个工程测试有这个问题吗？

**Comment by CaptainLiao** [comment]
@zhetengbiji  是新建的工程测试有问题

**Comment by zhetengbiji** [comment]
> @zhetengbiji 是新建的工程测试有问题

新建的哪个工程？

**Comment by CaptainLiao** [comment]
> 新建的哪个工程？

vue create -p dcloudio/uni-preset-vue my-project

选择默认模板

manifest.json 中，h5 开启 treeShaking

npm run dev:h5 编译成功

npm run build:h5  编译失败 

关闭 h5 的treeShaking，npm run build:h5 编译成功

**Comment by dcloudhdx** [comment]
npm update 已修复
