### ISSUE TITLE
2.2.2升级到2.3.7后安卓端mpvue-echarts不显示也不报错

### ISSUE THREAD

**Issue by vlijiantao** [dcloudio/uni-app#924]
Hbuildx2.2.2升级到2.3.7后安卓端mpvue-echarts不显示也不报错
已上线的安卓app在2.2.2版本上是正常使用的。最近有需求要改，打开hbuildx升级到了2.3.7版本，升级完成以后运行，mpvue-echarts的折线图不显示了，后按照官方提供的 https://ask.dcloud.net.cn/article/35851方法，把mpvue-ehcharts的echarts.vue替换成了最新的，
替换最新的 mpvue-echarts 组件， 源码地址：https://github.com/dcloudio/hello-uniapp/blob/master/components/mpvue-echarts/src/echarts.vue
官方提供方法：
使用方式修改 ：在 echarts 组件 :onInit 属性中添加代码，添加 ec-canvas 样式，移除:echarts="echarts"

// @/pages/template/echarts/echarts.vue  
<template>  
    <view class="container">  
        // 添加 ec-canvas 样式保证组件排版，同时移除旧的:echarts="echarts"  
        <mpvue-echarts class="ec-canvas" :onInit="onInit" canvasId="line" ref="lineChart" />  
    </view>  
</template>  
<script>  
    export default {  
        // ...  
        methods: {  
            // ...  
            onInit(canvas, width, height) {  
                // 在方法第一行添加如下代码  
                echarts.setCanvasCreator(() => canvas);  
                // ...  
            }  
            // ...  
        }  
    }  
</script>

修改后图表还是不显示，也不报错误。不知道该怎么解决？求回复。
代码如下：
<view style="width: 300px;height: 100%;">
				<mpvue-echarts class="ec-canvas" @onInit="onInit" canvasId="runChartline" ref="runChartline" />
			</view>

![图片](https://user-images.githubusercontent.com/37172114/67819706-4993dc00-faf1-11e9-9c50-be3305574b2d.png)
![图片](https://user-images.githubusercontent.com/37172114/67819722-57496180-faf1-11e9-9a19-965a5522e7bc.png)

**Comment by lincenying** [comment]
题主解决了吗? 非nvue下, 所有组件都不能正常使用了
