### ISSUE TITLE
IOS 图片选择器选择iCloud云多图片会偶尔出现应用闪退现象

### ISSUE THREAD

**Issue by 1072690884** [dcloudio/uni-app#926]
uni.chooseImage(OBJECT)
1.选择图片选择iCloud云多图片会偶尔出现应用闪退现象；
偶尔复现不容易给出demo；
不过iphonex之后的设备出现几率也挺高的；
2.iphonex之后刘海屏选择图片控件的完成等按钮与home条位置冲突；
uni.previewImage(OBJECT)图片预览功能；
顶部显示页码与状态栏冲突样式重叠

**Comment by 1072690884** [comment]
> uni.chooseImage(OBJECT)
> 选择图片选择iCloud云多图片会偶尔出现应用闪退现象；
> 偶尔复现不容易给出demo；
> 不过几率也挺高的
uni.previewImage(OBJECT)图片预览功能；
顶部显示页码与状态栏冲突样式重叠

**Comment by dcloudhdx** [comment]
1. 暂时没有找到复现的方法，在跟进

**Comment by xiaohuapunk** [comment]
> uni.chooseImage(OBJECT)
> 1.选择图片选择iCloud云多图片会偶尔出现应用闪退现象；
> 偶尔复现不容易给出demo；
> 不过iphonex之后的设备出现几率也挺高的；
> 2.iphonex之后刘海屏选择图片控件的完成等按钮与home条位置冲突；
> uni.previewImage(OBJECT)图片预览功能；
> 顶部显示页码与状态栏冲突样式重叠

1.选择图片控件按钮与 homebar 重叠的问题下个版本会修复，

2.`uni.previewImage(OBJECT)` 图片预览功能；顶部显示页码与状态栏冲突样式重叠，请问具体是什么机型，系统版本多少？我们没有复现此问题

**Comment by ArrayDC** [comment]
此问题已修复
