### ISSUE TITLE
问一个问题：做动画，weex中animation模块和css的transition有没有什么性能上的差异

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#927]
我现在写nvue的，app端都是用weex的animation模块来做动画，其他是css，每次都是条件编译。

我想问一下，weex的animation模块，和css动画，他们在app端会不会存在什么性能差异，没有的话，我就全部写成css动画了，不是很特别的就不为app引入animation模块。

谢谢。

**Comment by Wangyaqi** [comment]
几乎没有差异

**Comment by wakaryry** [comment]
可以。看来几乎可以全部换成css来做动画了。
