### ISSUE TITLE
安卓后台悬浮窗api支持吗?怎么实现?WindowManager/SYSTEM_ALERT_WINDOW

### ISSUE THREAD

**Issue by jewei-coder** [dcloudio/uni-app#928]
**问题描述**
[问题描述：想实现安卓悬浮窗]

**复现步骤**
[复现问题的步骤]
想要实现安卓后台悬浮窗,支持在手机桌面活动,类似以前的手机杀毒软件后台显示一个球球的

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
想要实现安卓后台悬浮窗,支持在手机桌面活动,类似以前的手机杀毒软件后台显示一个球球的

**系统信息:**
 - 发行平台: 安卓
 - 操作系统 [Android 7.0]

**Comment by wanganxp** [comment]
需要写原生插件，教程见插件市场
