### ISSUE TITLE
支付宝小程序中 for 循环中的多个 ref 生成的组件数组长度始终为1

### ISSUE THREAD

**Issue by xlfsummer** [dcloudio/uni-app#930]
**问题描述**
在 v-for 循环中使用 `ref="comp"`, 微信和百度正常，this.$refs.comp 为多个组件的数组
![image](https://user-images.githubusercontent.com/20750969/67849712-02820700-fb42-11e9-9171-07b73e93a82a.png)

在支付宝中，this.$refs.comp 虽然为数组，但只包含了一个组件
![image](https://user-images.githubusercontent.com/20750969/67849863-3eb56780-fb42-11e9-847f-60589ee82e74.png)

**预期结果**
支付宝端结果与微信一致

**系统信息:**
uni-app v2.3.7
uni-app cli v2.0.0-23720191024001

**补充信息**
查看支付宝 dist/dev 中的 vendor.js， 有如下代码
![image](https://user-images.githubusercontent.com/20750969/67850091-a4095880-fb42-11e9-9483-d5b413f3f4d7.png)

改成这样即可正常得到包含多个组件的 ref
![image](https://user-images.githubusercontent.com/20750969/67850121-b2577480-fb42-11e9-9631-f2fc95f0bbe4.png)
![image](https://user-images.githubusercontent.com/20750969/67850189-d87d1480-fb42-11e9-8925-2171770df0a3.png)

**Comment by Wangyaqi** [comment]
已确认bug，感谢反馈

**Comment by xlfsummer** [comment]
> 已确认bug，感谢反馈

请问有修复计划吗

**Comment by jiahuibin** [comment]
头条小程序在真机上也有这样的错误，在模拟器上没有这个问题
