### ISSUE TITLE
plus.push.addEventListener使用华为产商推送消息‘click’监听无效

### ISSUE THREAD

**Issue by TheLch01** [dcloudio/uni-app#931]
**问题描述**
uni push推送，使用华为产商推送，位于onLaunch中plus.push.addEventListener监听失效

**复现步骤**
通过服务端推送离线消息，点击华为通知栏接收到的消息唤起app，通过断点调试，发现程序未进入plus.push.addEventListener。

   plus.push.addEventListener('click', function(message) { 
	console.log('------------push click-----------');
	plus.nativeUI.toast('push click');  
	var vInfo = plus.push.getClientInfo();
	handlePush(message);  
 }); 

**预期结果**
点击通知栏唤起APP，能够获取到透传消息的内容。

**实际结果**
断点跳过plus.push.addEventListener

**系统信息:**
 - 发行平台: uni-app Android 
 - 操作系统 Android 9.0
 - HBuilderX 2.3.7.20191024
 - 设备信息 华为 P30

**Comment by ArrayDC** [comment]
此问题已修复，请更新到最新版本HBuilderX
