### ISSUE TITLE
nvue中list的scroll事件返回的isDragging看不懂

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#932]
isDragging {boolean}: 用户是否正在拖动列表。

但是我根据反馈的值来看，有点看不懂这个值的意思。

是不是用户手指一直在屏幕上拖拽的时候，才会是`true`。手指放开，屏幕滚动，应该是`false`。

但是我现在在真机`ios`上面，几乎难以获取到`false`，不管啥情况都是返回`true`。偶尔冒出来几次`false`。好像是回弹的时候才触发返回`false`。

**Comment by Wangyaqi** [comment]
确认有这个问题，感谢反馈

**Comment by mehaotian** [comment]
bug 已经修复，请下载或更新 HBuilderX alpha 2.4.0 验证

**Comment by wakaryry** [comment]
好的。可以。先关闭了。
