### ISSUE TITLE
uni-app 小程序 web-view 与 小程序页面跳转问题

### ISSUE THREAD

**Issue by tzzhmm** [dcloudio/uni-app#933]
**问题描述**

**问题一:**
页面由 **小程序A页面 -> web-viewA页面 -> 小程序B页面** , 在由 **小程序B页面 返回至(点击左上角返回按钮 / 手势右划返回) web-viewA页面** , 出现 http://about 不是业务域名提示.

**复现步骤**
[ 华为 ] : Mate10Pro & P30 , 详见 ↓ url 视频
https://v.qq.com/x/page/b30155qiy9d.html

使用原生小程序不复现此问题:  代码片段为
https://developers.weixin.qq.com/s/S8ALwwmn7zcD
视频url: https://v.qq.com/x/page/o3015pfeniz.html

此问题uni-app 小程序 与 原生小程序区别:
uni-app内web-view的src是经过动态拼接生成的 , 访问页面一致
原生小程序内web-view的src是写死的 , 访问页面一致

**注: 将 uni-app 内的 src 写死后不复现 , 访问页面一致 , 业务上 src 的 url 参数是需要拼接 , 不能写死**

**预期结果**
正常由 小程序B页面 -> web-viewA页面

**系统信息:**

 - 发行平台: 小程序

 - uni-app版本
```
uni-app v2.0.0-22420190823019

Environment Info:

  System:
    OS: Windows 7
    CPU: (4) x64 Intel(R) Core(TM) i7-3520M CPU @ 2.90GHz
  Binaries:
    Node: 10.16.0 - C:\Program Files\nodejs\node.EXE
    Yarn: Not Found
    npm: 6.9.0 - C:\Program Files\nodejs\npm.CMD
  npmPackages:
    @dcloudio/uni-app-plus: * => 0.0.253 (0.0.252)
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: * => 0.2.994
    @dcloudio/uni-h5: * => 0.9.0
    @dcloudio/uni-mp-alipay: * => 0.0.827
    @dcloudio/uni-mp-baidu: * => 0.0.857 (0.0.856)
    @dcloudio/uni-mp-qq: * => 0.0.112 (0.0.111)
    @dcloudio/uni-mp-toutiao: * => 0.0.352 (0.0.351)
    @dcloudio/uni-mp-weixin: * => 0.0.973 (0.0.972)
    @dcloudio/uni-stat:  2.0.0-22420190823019
    @dcloudio/uni-template-compiler: * => 0.9.183
    @dcloudio/uni-ui: ^1.0.1 => 1.0.1
    @dcloudio/vue-cli-plugin-hbuilderx: latest => 2.0.0-22420190823019
    @dcloudio/vue-cli-plugin-uni: latest => 2.0.0-22420190823019
    @dcloudio/vue-cli-plugin-uni-optimize: latest => 2.0.0-22420190823019
    @dcloudio/webpack-uni-mp-loader: * => 0.3.644
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: * => 0.2.875
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.11.0
    @vue/babel-preset-jsx:  1.1.0
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.0.0
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.11.0
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-service: ^3.9.0 => 3.11.0
    @vue/cli-shared-utils:  3.11.0
    @vue/component-compiler-utils:  3.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.3
    vue-loader:  15.7.1
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: Not Found
```
 

- 设备信息
华为Mate10Pro :
版本号: BLA-AL00 8.1.0.351
EMUI版本: 8.1.0
Android版本: 8.1.0

**Comment by Wangyaqi** [comment]
about哪来的，链接拼接的时候带的字符串吗

**Comment by tzzhmm** [comment]
> 关于哪来的，链接拼接的时候带的串联吗

不是 , 是从:  小程序B页面 -> web-viewA页面 (点击左上角/手势右划), 时候报的

定位到一个问题 , web-view打开的 H5 页面有引入 uniapp.js (需要在H5页面跳转至小程序)
使用的是 cdn 加速  : https://file.haomai-market.com/static/js/uni.webview.1.5.1.js 
但是在小程序内有时会报错,报错信息如下,会不会是这里影响的:
`Mixed Content: The page at 'https://dev5h5.91jindouyun.com/rebateTemplate?a=2157207360690980689&c=2156201509641909059&e=4156696206301909056&n=-1404236617&headimgurl=https%3A%2F%2Fwx.qlogo.cn%2Fmmopen%2Fvi_32%2FQ0j4TwGTfTK7svCicKkCPyibasWQHQlqGjvFVd8s1ogtnl0qXRBe6YAO9jqPmv0ZBbcaenu3vjqA31PZEfB8jGGQ%2F132&nickname=%E5%B0%B1%E6%98%AF%E7%8E%B0%E5%9C%A8&openId=ozUcd5DeipiJ1e9Mqo0ocOduzxPU&sex=1&userCode=3157247679617694646&source=MINIAPP&t=0&u=0&f=0&k=0&l=0' was loaded over HTTPS, but requested an insecure script 'http://file.haomai-market.com/static/js/uni.webview.1.5.1.js'. This request has been blocked; the content must be served over HTTPS.`

**Comment by Wangyaqi** [comment]
那你把uni.webview.1.5.1.js改成用我们cdn上的https的链接试试

**Comment by tzzhmm** [comment]
> 那你把uni.webview.1.5.1.js改成用我们cdn上的https的链接试试

您好,请问您那边的cdn链接是啥呢,我没有找到

**Comment by Wangyaqi** [comment]
[https://js.cdn.aliyun.dcloud.net.cn/dev/uni-app/uni.webview.1.5.1.js](https://js.cdn.aliyun.dcloud.net.cn/dev/uni-app/uni.webview.1.5.1.js)

**Comment by tzzhmm** [comment]
不会报错了,但是我的开发者工具也会报 http:// 不是业务域名提示.

**Comment by tzzhmm** [comment]
> https://js.cdn.aliyun.dcloud.net.cn/dev/uni-app/uni.webview.1.5.1.js

方便留您个联系方式吗,代码发您

**Comment by Wangyaqi** [comment]
wangyaqi988@163.com

**Comment by mutouaaaaaa** [comment]
你俩的头像，，好好玩
