### ISSUE TITLE
页面onUnload时，onHide方法不触发

### ISSUE THREAD

**Issue by tansj526** [dcloudio/uni-app#937]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
官方Demo也能复现此问题，当页面卸载时，onHide方法不触发

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
希望onHide方法触发

**系统信息:**
 - 发行平台: [微信小程序]
 - 操作系统 [所有]

**Comment by zhetengbiji** [comment]
应该没错，试试原生小程序是否如此

**Comment by fxy060608** [comment]
页面被关闭，只会触发onUnload
