### ISSUE TITLE
nvue能不通过扩展名来定义吗?

### ISSUE THREAD

**Issue by lincenying** [dcloudio/uni-app#938]
**新功能描述**
希望能通过其他可配置的方式来判断是否使用nvue, 不通过.nvue扩展名来判断, 依然使用.vue作为扩展名

**现状及问题**
绝大多数的编辑器对.nvue的支持太弱了

**尝试方案**
[如果你有尝试绕开或其它解决方案，在这里描述你的建议方案]

**补充信息**
[其它你认为有参考价值的信息]

**Comment by wakaryry** [comment]
不创建nvue不就不使用nvue页面了吗？大多数页面可以是nvue页面一套实现的，实现不了的，就用vue页面，也不需要创建nvue页面。

你可以组件全部使用vue的格式，在组件里面做好条件编译兼容就可以。

**Comment by lincenying** [comment]
我的意思是说, 比如现在的nvue组件的扩展名一定得是.nvue,  能否不管是nvue组件还是普通的vue组件, 都用.vue作为扩展名, 在组件里或者其他什么地方申明这个文件是走nvue编译的

**Comment by wakaryry** [comment]
> 比如现在的nvue组件的扩展名一定得是.nvue, 能否不管是nvue组件还是普通的vue组件, 都用.vue作为扩展名

事实上，你上面的结论是错的。

nvue组件是可以写成vue格式的。

nvue页面必须是nvue格式。nvue页面调用vue组件，编译到app，会将vue组件对应成nvue组件，检验weex规范；编译到mp/h5就直接是mp/h5的，就合vue页面调用vue组件一样。

这个申明就是看你的页面是什么格式，最终编译到什么平台。

所以不管是nvue组件还是vue组件，你都可以写成是vue格式。最终被当作什么，取决于调用的最终页面，以及编译到的终端平台。

**Comment by wakaryry** [comment]
https://github.com/dcloudio/uni-app/issues/879

**Comment by Wangyaqi** [comment]
需求已了解，会讨论一下具体实现

**Comment by lincenying** [comment]
> > 比如现在的nvue组件的扩展名一定得是.nvue, 能否不管是nvue组件还是普通的vue组件, 都用.vue作为扩展名
> 
> 事实上，你上面的结论是错的。
> 
> nvue组件是可以写成vue格式的。
> 
> nvue页面必须是nvue格式。nvue页面调用vue组件，编译到app，会将vue组件对应成nvue组件，检验weex规范；编译到mp/h5就直接是mp/h5的，就合vue页面调用vue组件一样。
> 
> 这个申明就是看你的页面是什么格式，最终编译到什么平台。
> 
> 所以不管是nvue组件还是vue组件，你都可以写成是vue格式。最终被当作什么，取决于调用的最终页面，以及编译到的终端平台。

但是pages下的路由组件就没办法了...想让路由组件走nvue, 只能用.nvue扩展名才行.

**Comment by wakaryry** [comment]
那就等uni的实现吧。其实对于官方来说，用什么格式都可以，只要提供一个完备的判别方式就行。

**Comment by Wangyaqi** [comment]
目前还牵扯到有人会写两份代码的问题。一份nvue的一份vue的，nvue的自动在app端生效，其他端用vue的，这个也是要考虑的
