### ISSUE TITLE
switch组件调节开关大小操作导致在支付宝小程序奔溃

### ISSUE THREAD

**Issue by touxing** [dcloudio/uni-app#940]
**问题描述**
使用 switch 组件，同时修改 color 和 style="transform:scale(0.7)" 调节 switch 大小导致支付宝小程序奔溃问题

**复现步骤**
[复现问题的步骤]

1. 导致出现错误的代码
```js
 <switch   style="transform:scale(0.7);"  :checked="true" />
```
2. 运行
`yarn dev:mp-alipay`

**预期结果**
可以达到正常切换开关的效果，不导致小程序奔溃

**实际结果**
[这里请贴上你的报错截图或文字]
![微信截图_20191101143632](https://user-images.githubusercontent.com/16403653/68007013-59f4b400-fcb5-11e9-810a-247a67dc6b10.png)
![微信截图_20191101142645](https://user-images.githubusercontent.com/16403653/68007022-60832b80-fcb5-11e9-9731-9f6981378748.png)

**系统信息:**
 - 发行平台: 支付宝小程序
 - 操作系统: 支付宝小程序开发模拟器
 - uni-app版本 
Environment Info:

  System:
    OS: Windows 10
    CPU: (12) x64 Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
  Binaries:
    Node: 10.16.0 - D:\Apps\nodejs\node.EXE
    Yarn: 1.17.3 - D:\Apps\Yarn\bin\yarn.CMD
    npm: 6.9.0 - D:\Apps\nodejs\npm.CMD
  Browsers:
    Edge: Not Found
  npmPackages:
    @dcloudio/uni-app-plus: ^2.0.0-23620191020003 => 2.0.0-23320190923002
    @dcloudio/uni-app-plus-nvue:  0.0.1
    @dcloudio/uni-app-plus-nvue-v8:  0.0.1
    @dcloudio/uni-cli-shared: ^2.0.0-23620191020003 => 2.0.0-23320190923002
    @dcloudio/uni-h5: ^2.0.0-23620191020003 => 2.0.0-23320190923002
    @dcloudio/uni-helper-json: * => 1.0.3
    @dcloudio/uni-mp-alipay: ^2.0.0-23620191020003 => 2.0.0-23320190923002
    @dcloudio/uni-mp-baidu: ^2.0.0-23620191020003 => 2.0.0-23320190923002
    @dcloudio/uni-mp-qq: ^2.0.0-23620191020003 => 2.0.0-23320190923002
    @dcloudio/uni-mp-toutiao: ^2.0.0-23620191020003 => 2.0.0-23320190923002
    @dcloudio/uni-mp-weixin: ^2.0.0-23620191020003 => 2.0.0-23320190923002
    @dcloudio/uni-stat: ^2.0.0-23620191020003 => 2.0.0-23320190923002
    @dcloudio/uni-template-compiler: ^2.0.0-23620191020003 => 2.0.0-23320190923002
    @dcloudio/vue-cli-plugin-hbuilderx: ^2.0.0-23620191020003 => 2.0.0-23320190923002
    @dcloudio/vue-cli-plugin-uni: ^2.0.0-23620191020003 => 2.0.0-23320190923002
    @dcloudio/vue-cli-plugin-uni-optimize: ^2.0.0-23620191020003 => 2.0.0-23320190923002
    @dcloudio/webpack-uni-mp-loader: ^2.0.0-23620191020003 => 2.0.0-23320190923002
    @dcloudio/webpack-uni-nvue-loader:  0.0.1
    @dcloudio/webpack-uni-pages-loader: ^2.0.0-23620191020003 => 2.0.0-23320190923002
    @vue/babel-helper-vue-jsx-merge-props:  1.0.0
    @vue/babel-plugin-transform-vue-jsx:  1.0.0
    @vue/babel-preset-app:  3.12.0
    @vue/babel-preset-jsx:  1.1.1
    @vue/babel-sugar-functional-vue:  1.0.0
    @vue/babel-sugar-inject-h:  1.0.0
    @vue/babel-sugar-v-model:  1.1.1
    @vue/babel-sugar-v-on:  1.1.0
    @vue/cli-overlay:  3.12.0
    @vue/cli-plugin-babel: 3.5.1 => 3.5.1
    @vue/cli-service: ^3.12.1 => 3.12.0
    @vue/cli-shared-utils:  3.12.0
    @vue/component-compiler-utils:  3.0.0
    @vue/preload-webpack-plugin:  1.1.1
    @vue/web-component-wrapper:  1.2.0
    mpvue-page-factory:  1.0.1
    mpvue-template-compiler:  1.0.13
    uni-h5-vue:  2.6.10
    uni-mp-vue:  2.6.10
    vue: ^2.6.10 => 2.6.10
    vue-hot-reload-api:  2.3.4
    vue-loader:  15.7.1
    vue-router:  3.0.1
    vue-style-loader:  4.1.2
    vue-template-compiler: ^2.6.10 => 2.6.10
    vue-template-es2015-compiler:  1.9.1
    vuex: ^3.0.1 => 3.1.1
  npmGlobalPackages:
    @vue/cli: Not Found

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
可能switch组件没处理好 color 和 style 两个属性同时传值的问题

**Comment by javascriptchen** [comment]
我们这里无法复现，你可以试试写个支付宝小程序原生的会不会崩溃，这种css属性应该不会导致崩溃，因为我们hello-uniapp里也用到了缩放switch，也没有用户反馈switch崩溃

**Comment by touxing** [comment]
小程序开发工具模拟器出现的问题，编译在真机预览没有出现这个问题，感谢回复，这个issue关闭
