### ISSUE TITLE
position为fixed的时候圆角设置出现问题

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#942]
我现在是`nvue`页面（`vue`页面好像也有这样的问题）。我在一个`position`为`fixed`的`view`上面，设置了`top`的两个圆角，没有设置`bottom`的，在`ios`真机上面显示没有圆角。

如果我把`bottom`的两个圆角设置成`0`，会发现偶尔四个角全是圆的，偶尔全部没有圆角。

只有把四个角全部设置成一样的时候才能正常使用。

不知道是不支持这么使用，还是的确这是个问题。

谢谢。

**Comment by zhetengbiji** [comment]
iOS还安卓，试试原始的weex是否有此问题？

**Comment by wakaryry** [comment]
ios. android没有测试。到时看看weex是不是也这样吧。

**Comment by wakaryry** [comment]
应该是weex的问题吧。
