### ISSUE TITLE
css绑定，在小程序下，如果绑定了对象，对象变了之后不会发生改变

### ISSUE THREAD

**Issue by zhangyq233** [dcloudio/uni-app#943]
代码请查看[test.zip](https://github.com/dcloudio/uni-app/files/3800390/test.zip)

![image](https://user-images.githubusercontent.com/28673757/68070039-6eaf7580-fda3-11e9-836f-45b203aa40b2.png)
![image](https://user-images.githubusercontent.com/28673757/68070046-97d00600-fda3-11e9-99bc-b1715f1c8218.png)
![image](https://user-images.githubusercontent.com/28673757/68070053-c817a480-fda3-11e9-9c13-174ad98bf1f7.png)

**Comment by javascriptchen** [comment]
[test.zip](https://github.com/dcloudio/uni-app/files/3803122/test.zip)

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
