### ISSUE TITLE
在微信小程序中图片的显示问题

### ISSUE THREAD

**Issue by ZhangyilinCN** [dcloudio/uni-app#947]
源码：
<template>
	<view class="content">
		<image src="../../static/e5d6d932b52d0766cecb7e3fccdb4d3bCuOPMc2019.png" class='img' mode="aspectFit"></image>
	</view>
</template>

<script>
	export default {
	}
</script>

<style>
	.img {
		width: 200rpx;
		height: 120rpx;
		border: 1px solid #000;
		background: red;
	}
</style>

在安卓手机中浏览的话左侧会显示出来背景的红色， 图片的尺寸是400*240的；

**Comment by Wangyaqi** [comment]
可以试一下，直接在微信小程序里面写会不会也是这个问题
