### ISSUE TITLE
uni.createInnerAudioContext微信端无法正常播放音乐

### ISSUE THREAD

**Issue by hzjzxp** [dcloudio/uni-app#948]
**问题描述**
uni.createInnerAudioContext在Android微信7.0.8上无法播放音乐的问题吗？在7.0.8以前的版本没问？

let music =  uni.createInnerAudioContext();
music.src = 'https://img-cdn-qiniu.dcloud.net.cn/uniapp/audio/music.mp3';
music.loop = true;
music.autoplay = true;

**预期结果**
微信端任何版本  运行该代码，页面加载完成，声音自动播放，

**实际结果**
Android微信7.0.8上无法播放音乐的问题吗？在7.0.8以前的版本可正常播放

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 Android 9.0
 - HBuilderX版本 2.3.7.20191024
 - uni-app版本 6.9.0

**补充信息**
使用 embed 组件可正常播放音乐

**Comment by liumingchu** [comment]
微信不允许，不过有绕过方案
百度：微信浏览器自动播放

**Comment by hzjzxp** [comment]
嗯，谢谢，已解决，请关闭问题吧！
