### ISSUE TITLE
nvue里click等事件没有返回坐标信息

### ISSUE THREAD

**Issue by Liu-Peter** [dcloudio/uni-app#949]
**问题描述**
请问如何在nvue里点击获取坐标信息？ nvue里click等事件没有返回坐标信息

**复现步骤**

	<div class="home_body">
		<div @click="test">
			点击
		</div>
	</div>

<script>
	export default {
		data() {
			return {
				key:""
			}
		},
		methods:{
			test:function(e){
				console.log(e)
			},
		}
	}
</script>
**预期结果**
在普通vue页面里click等事件里会返回坐标信息，希望nvue也可以

**实际结果**

{
	"type": "click",
	"timeStamp": 1572920901133,
	"target": {
		"id": "",
		"dataset": {
			"img": "https://tuangouimg.zhaoju.com/Uploads/image/goods/2019-10-29/5db79b6ce0199.png"
		},
		"offsetLeft": 0,
		"offsetTop": 0
	},
	"currentTarget": {
		"id": "",
		"dataset": {
			"img": "https://tuangouimg.zhaoju.com/Uploads/image/goods/2019-10-29/5db79b6ce0199.png"
		},
		"offsetLeft": 0,
		"offsetTop": 0
	},
	"detail": {}
}

**Comment by javascriptchen** [comment]
使用uni.createSelectorQuery，注意一次只能查一个，而且只能传入id。

**Comment by Wangyaqi** [comment]
nvue暂时不可以，具体要实现什么需求呢

**Comment by Liu-Peter** [comment]
> nvue暂时不可以，具体要实现什么需求呢

想实现点击位置到购物车的抛物线动画

**Comment by Wangyaqi** [comment]
获取一下点击的元素位置，然后再做动画行不

**Comment by Liu-Peter** [comment]
> 获取一下点击的元素位置，然后再做动画行不

那要怎么获取呢？

**Comment by Liu-Peter** [comment]
> 获取一下点击的元素位置，然后再做动画行不
在不？要怎么获取呢？

**Comment by dcloudhdx** [comment]
当前版本解决方案，点击前获得坐标，注意nvue select 仅支持id，可以同时select 多次
```
const query = uni.createSelectorQuery().in(this);
query.select('#id1').boundingClientRect();
query.select('#id2').boundingClientRect();
query.select('#id2').boundingClientRect();
query.exec(data => {
});
```

**Comment by Liu-Peter** [comment]
> 当前版本解决方案，点击前获得坐标，注意nvue select唯一支持id，可以同时选择多个
> 
> ```
> const query = uni.createSelectorQuery().in(this);
> query.select('#id1').boundingClientRect();
> query.select('#id2').boundingClientRect();
> query.select('#id2').boundingClientRect();
> query.exec(data => {
> });
> ```

好的，谢谢
