### ISSUE TITLE
uni-app修改代码后，在微信小程序里面出现 Page is not constructed because it is not found

### ISSUE THREAD

**Issue by xgj1988** [dcloudio/uni-app#950]
**问题描述**
uni-app修改代码后，在微信小程序里面出现 Page is not constructed because it is not found报错.

**复现步骤**
没有找到如何重新,

[或者可以直接贴源代码]

**预期结果**
偶尔在uni-app里面修改代码后，在微信小程序出现 Page is not constructed because it is not found.
 
**实际结果**
[这里请贴上你的报错截图或文字]
 
![image](https://user-images.githubusercontent.com/8272614/68174962-9e849600-ffba-11e9-8f59-cbd8bdfdecb5.png)

**系统信息:**
 - 发行平台:  微信小程序 
 - 操作系统 :windows 10 
 - HBuilderX版本  2.3.7.20191024
 - uni-app版本 hbuilderx创建的

**补充信息**
[可选]
我的工作流程是这样的，就是我在webstorm里面写的代码。然后保存后hbuilderX自动编译，然后微信小程序自动编译，但是偶尔会出现这个问题，我发现好像是源代码有语法错误就会出现，但是具体怎么导致的还不清楚。。每次都要重新把微信小程序开发工具关闭后再打开才可以。

**Comment by javascriptchen** [comment]
把服务停止，然后把输出目录整个删除，在重新启动服务生成一下目录试试。

**Comment by LLily7** [comment]
请问解决了吗？我也是这样，每天要因此重启几十遍。。。

**Comment by xgj1988** [comment]
@LLily7  等编译完之后再切换界面。，不要马上切换。。这样可以很大的降低概率。
