### ISSUE TITLE
增加错误页面路由

### ISSUE THREAD

**Issue by fengjiel** [dcloudio/uni-app#951]
**新功能描述**
可以自定义h5错误页面 如404 等等 希望可以预设配置  可以自定义编写页面
**现状及问题**
目前如果进入错误页面则是一片空白

**Comment by javascriptchen** [comment]
[https://uniapp.dcloud.io/collocation/manifest](https://uniapp.dcloud.io/collocation/manifest)
"error": {
            "url": "页面加载错误时打开的页面地址，可以是网络地址，也可以是本地地址"
  },

**Comment by hbcui1984** [comment]
issue长时间未响应，暂时关闭，如果问题复现或有更详细资料后可再次开启
