### ISSUE TITLE
【App】ios主题是黑色时，picker的日期模式选中文字和背景色同色

### ISSUE THREAD

**Issue by magicwing** [dcloudio/uni-app#952]
**问题描述**
ios 在设置 显示与亮度 中选择深色（黑色）主题时，picker的日期模式选中文字是白色、背景色也是白色，无法看清，其他未选中的文字颜色是白色。微信小程序没有问题

下图预览
![微信图片_20191105120046](https://user-images.githubusercontent.com/7157683/68177485-6b92d000-ffc3-11e9-8a79-3fa3eb75a679.png)

**预期结果**
和微信小程序一样即可，至少能看清

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 iOS 13+
 - HBuilderX版本 2.3.3.20190923
 - 设备信息 [如 iPhone6s]

**Comment by javascriptchen** [comment]
hello-uniapp未复现，检查下你代码哪里写的把样式覆盖了
[RPReplay_Final1572935435.MP4.zip](https://github.com/dcloudio/uni-app/files/3807518/RPReplay_Final1572935435.MP4.zip)

**Comment by magicwing** [comment]
> hello-uniapp未复现，检查下你代码哪里写的把样式覆盖了
分析原因不是代码问题，小程序和android没有，只有ios存在，代码中不存在针对ios的样式
这个是我录下的 hello-uniapp 复现 时间类的原生组件有问题
![1](https://user-images.githubusercontent.com/7157683/68186722-c6d2bb80-ffdf-11e9-81d4-ea61147c07dc.gif)

**Comment by javascriptchen** [comment]
你还有其他ios13设备吗，用别的设备试一下看看

**Comment by magicwing** [comment]
> 你还有其他ios13设备吗，用别的设备试一下看看

是客户反馈的，设备是iPhone8 ios13+，只有1台，一般也没有测试到更改主题色的情况

**Comment by javascriptchen** [comment]
> > 你还有其他ios13设备吗，用别的设备试一下看看
> 
> 是客户反馈的，设备是iPhone8 ios13+，只有1台，一般也没有测试到更改主题色的情况

你试试更新hx试试行不行，我们这里没有能复现的手机，没法调

**Comment by magicwing** [comment]
> > > 你还有其他ios13设备吗，用别的设备试一下看看
> > 
> > 
> > 是客户反馈的，设备是iPhone8 ios13+，只有1台，一般也没有测试到更改主题色的情况
> 
> 你试试更新hx试试行不行，我们这里没有能复现的手机，没法调
如下修复了
![image](https://user-images.githubusercontent.com/7157683/69022029-c92c1100-09f4-11ea-90f5-e2c603cd05df.png)
