### ISSUE TITLE
如何关闭生产环境构建时的 css 压缩

### ISSUE THREAD

**Issue by WangLeto** [dcloudio/uni-app#953]
**问题描述**
想知道怎么可以关闭生产环境构建时的 css 压缩配置，目前在飞书小程序（基本对齐头条小程序）中使用压缩过的 css 会造成部分样式解析出错。
在 vue.config.js 中配置吗？似乎在 mini-css-extract-plugin 中使用了 optimization.minimizer 选项，没有找到关闭的方法…

**Comment by javascriptchen** [comment]
没有这个配置哦，你可以直接把开发版的代码上传上去

**Comment by WangLeto** [comment]
在项目根目录添加 vue.config.js 文件，写入如下配置：
```javascript
module.exports = {
  chainWebpack: config => {
    config.plugins.delete('optimize-css')
  }
}
````
即可取消生产环境构建时的 css 压缩优化。
参考链接：https://forum.vuejs.org/t/minimize-css-in-vue-cli-3/38286/2

**Comment by Wangyaqi** [comment]
👍👍👍
