### ISSUE TITLE
打包 qq 小程序后, 都是微信小程序语法导致应用无法运行

### ISSUE THREAD

**Issue by imaxing** [dcloudio/uni-app#954]
#### 官方模板测试

![image](https://user-images.githubusercontent.com/26427785/68186821-04374900-ffe0-11e9-86be-d1613573ac02.png)

#### 打包结果

![image](https://user-images.githubusercontent.com/26427785/68186908-3c3e8c00-ffe0-11e9-9e55-9e4643c88316.png)

**预期 qq:if  不是 wx:if**

**Comment by javascriptchen** [comment]
你确定你没输错命令？

**Comment by javascriptchen** [comment]
你不需要管编译出来什么，你试试功能是否正常？
