### ISSUE TITLE
upx2px 的方法, 返回1px 

### ISSUE THREAD

**Issue by liujianglc** [dcloudio/uni-app#955]
export function upx2px (number, newDeviceWidth) {
  if (deviceWidth === 0) {
    checkDeviceWidth()
  }

  number = Number(number)
  if (number === 0) {
    return 0
  }
  let result = (number / BASE_DEVICE_WIDTH) * (newDeviceWidth || deviceWidth)
  if (result < 0) {
    result = -result
  }
  result = Math.floor(result + EPS)
  if (result === 0) {
    if (deviceDPR === 1 || !isIOS) {
      return 1     // 我觉得 这里,返回 number * 1 
    } else {
      return 0.5 // 我觉得这里, 返回 number * 0.5
    }
  }
  return number < 0 ? -result : result
}

**实际结果**
[这里请贴上你的报错截图或文字]
实际结果是, 浏览器没有从   __GLOBAL__.getSystemInfoSync() 获得windowWidth, 并且是安卓平台,   if (deviceDPR === 1 || !isIOS) { } , 进入到这里后, 其实我们更期望是  1 * number, 而不是 返回1个像素.  现在页面缩成了一团

**系统信息:**
 - 发行平台: [如 H5平台]
 - 操作系统 [如Android 9 ]

**Comment by dcloudhdx** [comment]
预计在 HBuilderX 2.8.1 alpha 版修复
