### ISSUE TITLE
methods中的onShow方法消失了

### ISSUE THREAD

**Issue by lwpassvoice** [dcloudio/uni-app#956]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
在methods中添加名为onShow的方法，调用的时候报this.onShow is not a function
```
		methods: {
			onShow() {
				console.log('methods: onshow');
			},

```
**复现步骤**
[复现问题的步骤]
![image](https://user-images.githubusercontent.com/22510735/68210677-ff3ebd80-0010-11ea-80eb-473e334c16a6.png)
![image](https://user-images.githubusercontent.com/22510735/68210802-4927a380-0011-11ea-93dc-80e9f5bcace7.png)
![image](https://user-images.githubusercontent.com/22510735/68210860-69576280-0011-11ea-8a1e-f15b9f7aa207.png)

使用vant ui的 Tab 标签页，也会出现类似情况，因为它定义了名为onShow的方法。。
https://youzan.github.io/vant/#/zh-CN/tab#dai-ma-yan-shi
```
import Vue from 'vue';
import { Tab, Tabs } from 'vant';

Vue.use(Tab).use(Tabs);

<van-tabs v-model="active">
  <van-tab title="标签 1">内容 1</van-tab>
  <van-tab title="标签 2">内容 2</van-tab>
  <van-tab title="标签 3">内容 3</van-tab>
  <van-tab title="标签 4">内容 4</van-tab>
</van-tabs>
export default {
  data() {
    return {
      active: 2
    };
  }
}
```
[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 win7 chrome70
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
2.3.7.2019.10.24

 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Wangyaqi** [comment]
不要在method里面用跟生命周期同名的方法

**Comment by lwpassvoice** [comment]
> 不要在method里面用跟生命周期同名的方法

像vant这种第三方库可能会用到跟生命周期同名的方法，如果不考虑这种情况的话可能就没法用了
