### ISSUE TITLE
微信小程序无法使用 this.$refs.node.$emit?

### ISSUE THREAD

**Issue by wYuJian** [dcloudio/uni-app#957]
子组件中有方法toggleModal
<login-warn ref='loginWarn'/>
页面中使用uni.$refs.loginWarn.$emit('toggleModal');无法触发

**Comment by wYuJian** [comment]
this.$refs.loginWarn.$emit('toggleModal');

**Comment by Wangyaqi** [comment]
this.$refs.loginWarn.toggleModal();

**Comment by wYuJian** [comment]
> this.$refs.loginWarn.toggleModal();

谢谢
