### ISSUE TITLE
uni.onBluetoothAdapterStateChange(CALLBACK) 监听蓝牙是否开启每次都会执行两遍

### ISSUE THREAD

**Issue by 1AKO1** [dcloudio/uni-app#958]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
期待监听蓝牙适配器状态，但是每次都会执行两次回调函数，第一次执行还没什么意义，不知道是我使用方式有问题还是 UNI的bug。。
**复现步骤**
[复现问题的步骤]
1. 启动：在main.js中调用uni.onBluetoothAdapterStateChange 然后在回调函数中打印返回值
2. 点击：多次重复开启于关闭蓝牙开关
3. 查看：控制台就可以看到每一次都会打印两条数据。第一条没有参考价值。。

**预期结果**
每次监听到蓝牙适配器状态改变之后只执行一次回调函数返回我当前蓝牙适配器状态即可

**实际结果**
[这里请贴上你的报错截图或文字]
//关闭蓝牙按钮
adapterState changed, now is, [Object] {"discovering":false,"available":false}  at main.js:28
adapterState changed, now is, [Object] {"discovering":false,"available":false}  at main.js:28
//打开蓝牙按钮
 adapterState changed, now is, [Object] {"discovering":false,"available":false}  at main.js:28
adapterState changed, now is, [Object] {"discovering":false,"available":true}  at main.js:28

**系统信息:**
 - 发行平台:  APP
 - 操作系统： Android 8.0
 - HBuilderX版本  2.3.7.20191024
 - uni-app版本 2.3.7.20191024
 - 设备信息  MI MIX

**Comment by dcloudhdx** [comment]
请提供示例代码

**Comment by mworkfun** [comment]
我也遇到此问题：
在调试安卓APP时，在使用uni.onBluetoothDeviceFound(CALLBACK) 监听寻找到新设备的事件时，第一次开启蓝牙模块监听时得到的蓝牙名称是正确的，在关闭蓝牙，再开启蓝牙模块，接着再监听寻找到新设备的事件时同一个蓝牙会得到1次相同的结果。再开启蓝牙模块，接着再监听寻找到新设备的事件时同一个蓝牙会得到3次相同的结果......N此同一个蓝牙就会n次相同的结果。这样是不对的

调用蓝牙步骤：
1、uni.openBluetoothAdapter({})       //开启蓝牙设备
2、uni.getBluetoothAdapterState({})  //获取蓝牙状态
3、uni.startBluetoothDevicesDiscovery({})  //搜索蓝牙
4、uni.onBluetoothDeviceFound(function(devices) {}  //监听蓝牙
5、console.log 蓝牙           //终端打印蓝牙数据
6、uni.stopBluetoothDevicesDiscovery({})   //关闭蓝牙搜索
7、uni.closeBluetoothAdapter({})  //关闭蓝牙设备
