### ISSUE TITLE
uni.request发送网络请求，response的header中没有服务器返回的字段

### ISSUE THREAD

**Issue by LeoDicaprio** [dcloudio/uni-app#96]
![b8ee8c7d1a38328b707cc1a383971b97](https://user-images.githubusercontent.com/17870701/49281881-ad201e80-f4c8-11e8-9124-88e941116e7b.jpg)
例如：接口返回的response.header中的Authorization怎么获取到？直接打印了response.header是没有这个的，只有cache-control和content-type
![b14a7b0bd0963492419a9a2f1059016d](https://user-images.githubusercontent.com/17870701/49281908-bdd09480-f4c8-11e8-89ad-2406d6580709.jpg)

是看着文档操作的
![9dec5b8a451324a5ed579794bd59b78b](https://user-images.githubusercontent.com/17870701/49281937-d17bfb00-f4c8-11e8-94ec-45a4b44950ac.jpg)

**Comment by zhetengbiji** [comment]
header里的这部分js是不能获取的，类似问题：[get-authorization-from-http-request-header](https://stackoverflow.com/questions/24991151/get-authorization-from-http-request-header)。

**Comment by charsen** [comment]
可以在服务端中，需要允许的header类型里加上 ‘Authorization’ ，比如 cros 的设置中，

res.header('Access-Control-Expose-Headers', 'Authorization');
