### ISSUE TITLE
button 如何 改变其样式，特别是在必须用到open-type='share'的时候

### ISSUE THREAD

**Issue by xgj1988** [dcloudio/uni-app#960]
**问题描述**
因为微信小程序分享只能用<button open-type='share'>，所以不得不用button，但是我们的分享界面是这样
![image](https://user-images.githubusercontent.com/8272614/68301122-3d53e400-00da-11ea-990d-30eb921c6c99.png)

但是 结果用了button 是这样。。
![image](https://user-images.githubusercontent.com/8272614/68301060-1c8b8e80-00da-11ea-952c-5ae8a7b53751.png)

好难啊，为什么不能在任意标签上面加open-type呢。。

**复现步骤**
无

` 
<button v-for="(item, index) in bottomData" :key="index" class="uni-share-content-box"
                            open-type="share">
                        <view class="uni-share-content-image">
                            <image :src="item.icon" class="image"/>
                        </view>
                        <view class="uni-share-content-text">{{ item.text }}</view>
                    </button>
`

**预期结果**
button 按钮加了open-type如何让button 的样式消失

**实际结果**
button 样式覆盖了我的正式样式

**系统信息:**
 - 发行平台: 微信小程序
 - 操作系统 :微信
 - HBuilderX版本 : 2.3.7.20191024

**Comment by Wangyaqi** [comment]
这是微信小程序的限制没办法
