### ISSUE TITLE
uni.getUserInfo获取支付宝小程序回调errMsg : "getUserInfo:fail 未授权读取用户信息"

### ISSUE THREAD

**Issue by Chale0524** [dcloudio/uni-app#961]
**问题描述**
点击按钮使用uni.getUserInfo获取“获取用户基础信息”回调返回errMsg : "getUserInfo:fail 未授权读取用户信息"；使用my.getOpenUserInfo()就返回正常数据
![image](https://user-images.githubusercontent.com/43983622/68359215-26eb6e00-0156-11ea-9382-dcf4090c481f.png)
![image](https://user-images.githubusercontent.com/43983622/68359227-31a60300-0156-11ea-9488-d39cae0748b7.png)

**Comment by javascriptchen** [comment]
uni.getUserInfo使用前需要使用my.getAuthCode，具体代码如下，感谢反馈
[alipay-getUserInfo.zip](https://github.com/dcloudio/uni-app/files/3818885/alipay-getUserInfo.zip)

**Comment by javascriptchen** [comment]
你需要先登录，后获取用户信息，示例代码如下
[alipay-getUserInfo.zip](https://github.com/dcloudio/uni-app/files/3819016/alipay-getUserInfo.zip)
