### ISSUE TITLE
通过vue-cli命令行快速上手报错！

### ISSUE THREAD

**Issue by fandudu** [dcloudio/uni-app#962]
目前是mpvue使用者，了解了uni-app解决mpvue的痛点，于是决定尝试一下；
参考https://uniapp.dcloud.io/quickstart
快速上手2.通过vue-cli命令行直接报错！！

![image](https://user-images.githubusercontent.com/15722726/68364652-90c14300-0169-11ea-928b-6bcce186120d.png)

**Comment by Wangyaqi** [comment]
这是安装vue-cli报的错，node版本多少，如果比较低可以试试升级一下

**Comment by CheJJ** [comment]
安装全局模块不要使用sudo

**Comment by fandudu** [comment]
通过cnpm解决
