### ISSUE TITLE
uni-app 不支持Blob类型发送socket消息吗？

### ISSUE THREAD

**Issue by JerrySir** [dcloudio/uni-app#963]
**问题描述**
我们发送socket消息需要使用Blob类型的，但是现在 new Blob报错

17:07:55.138 [ERROR] : ReferenceError: Can't find variable: Blob __ERROR

请问如何解决？

**复现步骤**
[复现问题的步骤]
var aFileParts = ['<a id="a"><b id="b">hey!</b></a>']; // 一个包含DOMString的数组
var oMyBlob = new Blob(aFileParts, {type : 'text/html'}); // 得到 blob

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by zhetengbiji** [comment]
非H5端不支持（H5端无限制，可以直接使用WebSocket）
