### ISSUE TITLE
UNI-APP H5 如何实现统一 404 页面功能 

### ISSUE THREAD

**Issue by wayoo** [dcloudio/uni-app#965]
**问题描述**
访问 H5 的链接一个不存在的路径，目前是空白页面，怎么重定向到一个固定的页面呢？

**Comment by javascriptchen** [comment]
[https://ask.dcloud.net.cn/article/73](https://ask.dcloud.net.cn/article/73)
配置manifest.json文件
error.html需要放到根目录下的hybrid/html目录下，否则不会被编译进去
```
"app-plus": {  
    "error": {  
        "url": "hybrid/html/error.html"  
    },  
    //...  
},  
```
