### ISSUE TITLE
输入框在微信中使用，软键盘占位问题

### ISSUE THREAD

**Issue by Luolei1992** [dcloudio/uni-app#966]
ios微信端扫码打开组件uni-app下的表单组件-input，上滑组件，点击最下方输入框，弹出键盘，点击完成失焦后页面没有恢复到原状态，下方有空白区，如图

![微信图片_20191108112749](https://user-images.githubusercontent.com/23149226/68447607-82cbfa80-021b-11ea-80af-5a6c354aa2a2.jpg)
![微信图片_20191108112743](https://user-images.githubusercontent.com/23149226/68447610-83649100-021b-11ea-89fc-dfb87051d99e.jpg)

**Comment by Wangyaqi** [comment]
百度一下 微信浏览器输入框bug ，看看哪一条适合你
