### ISSUE TITLE
uniapp小程序中v-model 使用watch监听数据改变(空格)出现第二次失败问题.

### ISSUE THREAD

**Issue by zoucc** [dcloudio/uni-app#967]
**问题描述**
input 用watch监听v-model 绑定的数据时候,判断是否输入空格,是的话input置空.
第一次成功,第二次输入空格后不成功.数据不会置空(使用脚手架vue-cli可以成功).

**复现步骤**

<input type="text" v-model="oldPwd" ref="oldPwd" placeholder="请输入旧密码" />
watch:{
	oldPwd:function (newData,oldData) {
				 const reg= /\s+/g;
				if(reg.test(this.oldPwd )){
					this.oldPwd = ""; 
					// this.newPwd = this.newPwd.replace(reg,null);
					console.log("改变的数据"+this.newPwd)
					return;
				}
}

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
  

**系统信息:**
 - 发行平台:  微信小程序]
 - 操作系统 [Android 9.0]
 - HBuilderX版本 2.3.3.20190923

**补充信息**

**Comment by javascriptchen** [comment]
安卓、ios均未复现
[RPReplay_Final1573469941.MP4.zip](https://github.com/dcloudio/uni-app/files/3831002/RPReplay_Final1573469941.MP4.zip)

**Comment by zoucc** [comment]
我的操作是开始就输入空格.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"陈晨"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月11日(星期一) 晚上7:02
收件人:&nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&gt;;
抄送:&nbsp;"⁬"<1285116491@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] uniapp小程序中v-model 使用watch监听数据改变(空格)出现第二次失败问题. (#967)




安卓、ios均未复现
 RPReplay_Final1573469941.MP4.zip

**Comment by javascriptchen** [comment]
```
oldPwd: function(newData, oldData) {
	console.log("newData: " + newData);
	console.log("oldData: " + oldData);
	const reg = /\s$/g;
	if (reg.test(this.oldPwd)) {
		this.oldPwd = "";
		this.newPwd = this.newPwd.replace(reg, '');
		console.log("改变的数据" + this.newPwd) 
		return;
	}
}
```
数据你trim一下，记得关一下issue
