### ISSUE TITLE
自定义条件编译平台，UNI_PLATFORM在设置为app-plus时不生效？

### ISSUE THREAD

**Issue by shizhongzheng** [dcloudio/uni-app#969]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
自定义条件编译平台，UNI_PLATFORM在设置为app-plus时不生效？设置为h5、mp-weixin等选项则都可以在HbuilderX上看到对应的自定义发布选项。
**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]
```
"uni-app": {
  "scripts": {
    "s-only": {
      "title": "独立版",
      "env": {
	"UNI_PLATFORM": "app-plus"
	},
       "define": {
	  "S-ONLY": true
       }
    }
  }
}
```
**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]
env的UNI_PLATFORM填为app-plus时可以在编辑器上看到对应的自定义运行/发布选项
**实际结果**
[这里请贴上你的报错截图或文字]
UNI_PLATFORM设置为app-plus时，没有生效，编辑器上自定义运行/发布选项不会出现对应选项

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等] APP-PLUS
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
HbuilderX 2.3.7.20191024
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by shizhongzheng** [comment]
目前不支持App端的自定义条件编译平台。

官方文档如下列举了app-plus
> UNI_PLATFORM仅支持填写uni-app默认支持的基准平台，目前仅限如下枚举值：app-plus、h5、mp-weixin、mp-alipay、mp-baidu、mp-toutiao、mp-qq
 ——https://uniapp.dcloud.io/collocation/package

https://ask.dcloud.net.cn/question/82559?item_id=104796&rf=false

**Comment by hbcui1984** [comment]
暂不支持`app-plus`平台，已修改文档说明。
