### ISSUE TITLE
想用uniapp只开发app，有以下问题不太清楚，望大佬指导，感激不尽。

### ISSUE THREAD

**Issue by huanghaodong** [dcloudio/uni-app#971]
1、只需要编译成app，页面是否全部用nvue性能更好？
2、nvue编译成app，是否全部生成的原生组件，而不是webview？
3、nvue页面的编译模式，分别用weex 组件编译模式和uni-app 组件编译模式，分别编译成app，app的性能有差异吗？
4、用uni-app 组件编译模式，就不支持weex ui了吗？
5、nvue里用BindingX和css3，在app中哪个效果更好？
6、.nvue和.vue能否通过uni.$on、uni.$emit以及uni.navigateTo带参数，来通信？我试了下好像可以，那文档这个 [https://uniapp.dcloud.io/use-weex?id=nvue-和-vue-相互通讯](https://uniapp.dcloud.io/use-weex?id=nvue-%e5%92%8c-vue-%e7%9b%b8%e4%ba%92%e9%80%9a%e8%ae%af)为何看来如此麻烦？
7、nvue可否使用拓展组件（uni-ui）
8、条件编译的APP-PLUS-NVUE和APP-PLUS区别区别是撒？
9、在.nvue中使用input组件，默认用的是weex的input还是uni-app的input？
10、如同时存在.vue和.nvue页面，要写一个公共组件共它们共同使用，这个公共组件应该是.vue还是.nvue？

**Comment by wakaryry** [comment]
1. nvue会对应weex渲染，原生体验更好；
2. 不是webview；
3. 没有性能差异，uni-app模式是指使用uni的组件可以对应成weex，nvue还可以生成mp/H5；
4. 支持weex-ui，不过只在app支持；
5. 频繁交换数据的使用bindingX（见bindingX说明）。css动画和animation模块基本上没有性能差异；
6. 可以使用uni.$on、uni.$emit以及uni.navigateTo。这个文档里面的其实我没有用过；
7. uni-ui会进行更新，适配nvue页面开发（现在有一个nvue分支）；
8. 前者是为了在nvue页面使用的，APP-PLUS只是指app平台，有可能是vue页面，有可能是nvue页面；
9. 在app端对应成weex的；
10. 公共组件写成vue格式。其实所有的组件都可以写成vue格式，最终是什么取决于引用的页面以及编译到的平台。

**Comment by huanghaodong** [comment]
> 1. nvue会对应weex渲染，原生体验更好；
> 2. 不是webview；
> 3. 没有性能差异，uni-app模式是指使用uni的组件可以对应成weex，nvue还可以生成mp/H5；
> 4. 支持weex-ui，不过只在app支持；
> 5. 频繁交换数据的使用bindingX（见bindingX说明）。css动画和animation模块基本上没有性能差异；
> 6. 可以使用uni.$on、uni.$emit以及uni.navigateTo。这个文档里面的其实我没有用过；
> 7. uni-ui会进行更新，适配nvue页面开发（现在有一个nvue分支）；
> 8. 前者是为了在nvue页面使用的，APP-PLUS只是指app平台，有可能是vue页面，有可能是nvue页面；
> 9. 在app端对应成weex的；
> 10. 公共组件写成vue格式。其实所有的组件都可以写成vue格式，最终是什么取决于引用的页面以及编译到的平台。

经测试，只有weex编译模式才支持weex ui，uni-app 编译模式有样式问题。

**Comment by wakaryry** [comment]
那个不太清楚。我是为 nvue 页面 重新写了 一套组件，可以实现 一套组件 对应weex/mp/h5.

近期会完成主题化可配置和文档。不过不是对外免费提供的。

**Comment by hbcui1984** [comment]
> > 1. nvue会对应weex渲染，原生体验更好；
> > 2. 不是webview；
> > 3. 没有性能差异，uni-app模式是指使用uni的组件可以对应成weex，nvue还可以生成mp/H5；
> > 4. 支持weex-ui，不过只在app支持；
> > 5. 频繁交换数据的使用bindingX（见bindingX说明）。css动画和animation模块基本上没有性能差异；
> > 6. 可以使用uni.$on、uni.$emit以及uni.navigateTo。这个文档里面的其实我没有用过；
> > 7. uni-ui会进行更新，适配nvue页面开发（现在有一个nvue分支）；
> > 8. 前者是为了在nvue页面使用的，APP-PLUS只是指app平台，有可能是vue页面，有可能是nvue页面；
> > 9. 在app端对应成weex的；
> > 10. 公共组件写成vue格式。其实所有的组件都可以写成vue格式，最终是什么取决于引用的页面以及编译到的平台。
> 
> 经测试，只有weex编译模式才支持weex ui，uni-app 编译模式有样式问题。

在`uni-app`编译模式下，weex-ui等三方组件库可能会出现样式问题，主要是weex中px响应式的原因；可手动修改部分代码实现兼容。

**Comment by huanghaodong** [comment]
谢谢各位耐心解答
