### ISSUE TITLE
横竖屏切换

### ISSUE THREAD

**Issue by LwLuna** [dcloudio/uni-app#973]
从一个竖屏页面跳转到横屏页面，竖屏变成横屏了，但是显示的页面还是竖屏的页面，所有点击事件都失效感觉页面卡死。怎么处理横竖屏切换，点击返回可以回到上个页面

**Comment by javascriptchen** [comment]
如果想要旋转屏幕适应屏幕宽度，使用rpx布局。
事件失效卡死应该是你代码写的有问题，看下哪里报错了。
返回可以使用uni.navigateBack()

**Comment by LwLuna** [comment]
> 
> 
> 如果想要适应屏幕宽度，使用rpx布局。
> 事件失效卡死应该是你代码写的有问题，看下哪里报错了。
> 返回可以使用uni.navigateBack()
 我是从a.vue(竖屏)跳转到b.vue(横屏)，b也显示的是横屏但是页面内容显示的是a页面的内容，而且我点物理返回键也没有反应了

**Comment by hbcui1984** [comment]
不同页面横竖屏模式不同？

**Comment by LwLuna** [comment]
> 
> 
> 不同页面横竖屏模式不同？


是的，我现在就是这样的问题不同页面的横竖模式不同就会出现我说的那个问题

**Comment by LwLuna** [comment]
是的，我现在就是这样的问题不同页面的横竖模式不同就会出现我说的那个问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"崔红保"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月11日(星期一) 下午2:09
收件人:&nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&gt;;
抄送:&nbsp;"棒棒糖"<1053419668@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] 横竖屏切换 (#973)




不同页面横竖屏模式不同？

**Comment by dcloudhdx** [comment]
App 还是 微信小程序，APP平台不支持单个页面配置横屏，只能通过锁定屏幕方向来控制，在哪个页面锁定了屏幕方向？
