### ISSUE TITLE
canvas在ios和安卓中使用底图会模糊

### ISSUE THREAD

**Issue by php9527** [dcloudio/uni-app#974]
**问题描述**
canvas在ios和安卓中使用底图会模糊

**复现步骤**
[复现问题的步骤]
就app会出现这种模糊现象，画图代码如下：
![2611573444247_ pic_hd](https://user-images.githubusercontent.com/8923685/68559862-8ceb3480-0479-11ea-9209-77e3d14ca26d.jpg)

**预期结果**
![2601573444180_ pic](https://user-images.githubusercontent.com/8923685/68559819-5ca39600-0479-11ea-99e3-fa86c4538fb3.jpg)

**实际结果**
![2581573444085_ pic](https://user-images.githubusercontent.com/8923685/68559763-25cd8000-0479-11ea-8fcf-3c8bff574bda.jpg)

**系统信息:**
 - 发行平台: app
 - 操作系统 ios和安卓都会
 - HBuilderX版本 2.1.3.20190723
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]

**Comment by Wangyaqi** [comment]
上传一份精简后的工程上来，我们验证一下

**Comment by Wangyaqi** [comment]
长时间未回复，暂时关闭
