### ISSUE TITLE
tabBar高度设置无效

### ISSUE THREAD

**Issue by lwpassvoice** [dcloudio/uni-app#975]
**问题描述**

**复现步骤**

pages.json 里设置 tabBar 高度，实际显示的确是默认高度
```
	"tabBar": {
		"color": "#C8CAD2",
		"selectedColor": "#4285ED",
		"borderStyle": "white",
		"backgroundColor": "#ffffff",
		"height": "160px",
		"list": [{
```

![image](https://user-images.githubusercontent.com/22510735/68577647-778efe00-04ab-11ea-9da0-6cd32058a743.png)
![image](https://user-images.githubusercontent.com/22510735/68577971-16b3f580-04ac-11ea-99d7-307249ee78fb.png)

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: H5平台
 - 操作系统 window7
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]
![image](https://user-images.githubusercontent.com/22510735/68577924-fb48ea80-04ab-11ea-8d03-d2fb97eb0458.png)

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by mehaotian** [comment]
只有 App 2.3.4版本之后才支持，其他平台不支持。
