### ISSUE TITLE
picker在微信小程序中mode=time  start end   范围属性真机测试不生效

### ISSUE THREAD

**Issue by lupeiwen** [dcloudio/uni-app#976]
**问题描述**
picker组建在微信小程序中mode=‘time’ start / end  属性不生效
**复现步骤**

**预期结果**
修复start 和 end 属性范围效果

**实际结果**
start 和 end 不能约束 可选的时间范围

**系统信息:**
 - 发行平台: 微信小程序
 - HBuilderX版本 2.3.7.20191024

**补充信息**

**Comment by javascriptchen** [comment]
文档中有写，5+App 不支持[https://uniapp.dcloud.io/component/picker?id=picker](https://uniapp.dcloud.io/component/picker?id=picker)

**Comment by javascriptchen** [comment]
微信版本：7.0.8
系统：ios13
未复现

**Comment by lupeiwen** [comment]
`<picker mode="time" value="10:24" start="10:24" @change="checkDate">
          <view v-else>{{overDate}}</view>
  </picker>`
微信版本：7.0.8
安卓：10
ios: 13.1.3
在开发者工具中正常，真机测试下出现 start 不生效

**Comment by lupeiwen** [comment]
> `<template>
	<view class="content">
		<view class="uni-title uni-common-pl">日期选择器</view>
		<view class="uni-list-cell">
			<view class="uni-list-cell-left">
				当前选择
			</view>
			<picker mode="time" :value="date" :start="startDate" :end="endDate" @change="bindDateChange">
				<view class="uni-input">{{date}}</view>
			</picker>
		</view>
	</view>
</template>

<script>
	export default {
		data() {
			return {
				date: '10:24',
				startDate: '10:24',
				endDate: '20:20'
			}
		},
		onLoad() {

		},
		methods: {

		}
	}
</script>`
> 微信版本：7.0.8
> 安卓：10
> ios: 13.1.3
> 在开发者工具中正常，真机测试下出现 start 不生效

**Comment by lupeiwen** [comment]
小哥 真的没问题吗？ 我原以为自己是项目代码有啥冲突 之后单独建了个demo 但还是 一样的问题 在开发工具上是正常的，真机预览 测试 就会出现 start 不能生效的问题
<template>
<view class="content">
<view class="uni-title uni-common-pl">日期选择器</view>
<view class="uni-list-cell">
<view class="uni-list-cell-left">
当前选择
</view>
<picker mode="time" :value="date" :start="startDate" :end="endDate" @change="bindDateChange">
<view class="uni-input">{{date}}</view>
</picker>
</view>
</view>
</template>

<script>
export default {
data() {
return {
date: '10:24',
startDate: '10:24',
endDate: '20:20'
}
},
onLoad() {

},
methods: {
bindDateChange(e){
this.date = e.target.value
}
}
}
</script>

在 2019-11-12 11:28:42，"陈晨" <notifications@github.com> 写道：


微信版本：7.0.8
系统：ios13
未复现

**Comment by javascriptchen** [comment]
![image](https://user-images.githubusercontent.com/26818851/68727825-76bbb080-0600-11ea-8c2d-2c9619bac261.png)

[RPReplay_Final1573612050.MP4.zip](https://github.com/dcloudio/uni-app/files/3839156/RPReplay_Final1573612050.MP4.zip)
我用的是hello-uniapp测试的

**Comment by lupeiwen** [comment]
要在真机上测试的 hello-uniapp中的 picker 问题也是一样的 我没有改代码 真机预览 同样 start / end 不生效 微信开发工具中一切正常
微信 7.0.8

在 2019-11-13 10:30:42，"陈晨" <notifications@github.com> 写道：


RPReplay_Final1573612050.MP4.zip
我用的是hello-uniapp测试的

**Comment by javascriptchen** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    你看我发的视频了吗？
    
        
            
        
    
    
      
    
        
                    
            
                
                    
                            
                                
                            
                            
                                458679677
                            
                    
                        
                            
                                    458679677@qq.com
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 
    

    在2019年11月13日 10:58，路培文<notifications@github.com> 写道： 


要在真机上测试的 hello-uniapp中的 picker 问题也是一样的 我没有改代码 真机预览 同样 start / end 不生效 微信开发工具中一切正常

微信 7.0.8



在 2019-11-13 10:30:42，"陈晨" <notifications@github.com> 写道：





RPReplay_Final1573612050.MP4.zip

我用的是hello-uniapp测试的



—

You are receiving this because you authored the thread.

Reply to this email directly, view it on GitHub, or unsubscribe.



—You are receiving this because you modified the open/close state.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by lupeiwen** [comment]
不好意思 我是 用的安卓 10 微信 7.0.8 手机型号 华为 mate20 pro
用同事手机 ios 13 测试 正常

在 2019-11-13 11:02:59，"陈晨" <notifications@github.com> 写道：






font{
line-height: 1.6;
}
ul,ol{
padding-left: 20px;
list-style-position: inside;
}



你看我发的视频了吗？

















458679677




458679677@qq.com








签名由
网易邮箱大师
定制




在2019年11月13日 10:58，路培文<notifications@github.com> 写道：


要在真机上测试的 hello-uniapp中的 picker 问题也是一样的 我没有改代码 真机预览 同样 start / end 不生效 微信开发工具中一切正常

微信 7.0.8



在 2019-11-13 10:30:42，"陈晨" <notifications@github.com> 写道：





RPReplay_Final1573612050.MP4.zip

我用的是hello-uniapp测试的

**Comment by zhetengbiji** [comment]
其他机型是否正常？

**Comment by saifeiLee** [comment]
我遇到了同样的问题，picker日期组件的start/end并不能约束可选范围
