### ISSUE TITLE
云打包iOS如何配置 Allow Arbitrary Loads 项

### ISSUE THREAD

**Issue by JerrySir** [dcloudio/uni-app#977]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by javascriptchen** [comment]
[https://ask.dcloud.net.cn/article/941](https://ask.dcloud.net.cn/article/941)看第18个，试试能不能解决

**Comment by JerrySir** [comment]
问题是云打包，能在HBuilder里面设置吗？

**Comment by javascriptchen** [comment]
[https://my.oschina.net/hmj/blog/104196](https://my.oschina.net/hmj/blog/104196)

**Comment by ArrayDC** [comment]
云端打包默认Allow Arbitrary Loads值为true，如果希望修改为false可以在manifest.json文件的 "app-plus" -> "distribute" -> "ios"节点添加以下数据：
`
        "plistcmds": [
          "set :NSAppTransportSecurity:NSAllowsArbitraryLoads false"
        ]
`
