### ISSUE TITLE
uni chooseImage h5获取上传的原始文件名

### ISSUE THREAD

**Issue by cc4dogman** [dcloudio/uni-app#978]
**新功能描述**
uni chooseImage 获取上传的原始文件名

**现状及问题**
目前返回了经过转换后的本地路径，无法获取其原始文件名做一些逻辑处理

**尝试方案**
后缀的话通过uni.request解决，但某些场景下需要根据文件名提取一些数据出来

**补充信息**
能否在上传后返回一下原始文件名，这个属性应该在各个平台兼容会简单点，或者先满足h5的

**Comment by Wangyaqi** [comment]
获取原始文件名是为了什么，可以详细描述一下需求吗

**Comment by cc4dogman** [comment]
比如对文件进行md5签名，但签名内容不能放到exif里面，这样文件md5会变，所以只能放在文件名上，目前直接把源码copy出来改了下，本地引入解决了

**Comment by zhetengbiji** [comment]
2.4.4+ 已支持

**Comment by e112121** [comment]
微信小程序可以兼容下获取获取原始文件名的问题嘛
