### ISSUE TITLE
有关uni-app建立项目的webview的顶部进度条问题

### ISSUE THREAD

**Issue by Houweix** [dcloudio/uni-app#98]
使用uni-app创建一个项目后，里面有一个webview的标签，我怎样关闭顶部的进度条呢。

**Comment by xiaoyucoding** [comment]
在 5+App 上新增 webview-styles 属性来自定义进度条，详细参考：[https://uniapp.dcloud.io/component/web-view](https://uniapp.dcloud.io/component/web-view) 中的说明及注意事项。
