### ISSUE TITLE
背景音频播放bug

### ISSUE THREAD

**Issue by JinJieGu** [dcloudio/uni-app#981]
**问题描述**
uni.createInnerAudioContext()和uni.getBackgroundAudioManager()同时播放时uni.createInnerAudioContext()创建的实例无法正常播放

**复现步骤**
[复现问题的步骤]
1.  启动 '...'
2. 点击  '....'
3. 查看

[或者可以直接贴源代码]

**预期结果**
[使用简洁清晰的语言描述你希望生效的预期结果]

**实际结果**
[这里请贴上你的报错截图或文字]

**系统信息:**
 - 发行平台: 5+ App
 - 操作系统 Android 9.0
 - HBuilderX版本 2.3.7
 - uni-app版本 
 - 设备信息 华为v10

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by javascriptchen** [comment]
请提供一下示例代码
