### ISSUE TITLE
在安卓7.1及安卓6 uni-h5 getNetworkType 会出现问题，麻烦多做个判断

### ISSUE THREAD

**Issue by zhangyq233** [dcloudio/uni-app#983]
![image](https://user-images.githubusercontent.com/28673757/68727381-3c9ddf00-05ff-11ea-82b6-ad0ef2e84404.png)
![image](https://user-images.githubusercontent.com/28673757/68727398-44f61a00-05ff-11ea-8ddf-eee29032b6e3.png)
![image](https://user-images.githubusercontent.com/28673757/68727494-87b7f200-05ff-11ea-93e5-42d3394a9153.png)
![image](https://user-images.githubusercontent.com/28673757/68727594-cea5e780-05ff-11ea-9cff-841e8df10f86.png)

**Comment by javascriptchen** [comment]
换成`connection. effectiveType&&connection. effectiveType. replace( 'slow-','')`就好了

**Comment by zhangyq233** [comment]
> 换成`connection. effectiveType&&connection. effectiveType. replace( 'slow-','')`就好了

你好 我这串代码你们框架里面写的。  麻烦看下我的第二张截图，是你们的路径。 麻烦你们改一下
