### ISSUE TITLE
希望在 image 组件上加一个 cache 属性可以自动缓存图片

### ISSUE THREAD

**Issue by liaohui5** [dcloudio/uni-app#984]
**新功能描述**
希望加一个为image组件加一个 `cache` 属性, cache为true的时候自动把图片缓存到本地
![image](https://user-images.githubusercontent.com/29266093/68744413-856d8c00-062f-11ea-9d4c-0336b01777a0.png)

**现状及问题**
如果加载几个高清图, 就会特别的慢

**尝试方案**
我试过把图片下载到本地, 然后通过相对/绝对路径来访问, 发现都不行, 社区的 [imageCache插件](https://ext.dcloud.net.cn/plugin?id=882)也会报错 

**补充信息**
[其它你认为有参考价值的信息]

**Comment by Wangyaqi** [comment]
组件`ImageCache.vue` 67行convertLocalFileSystemURL 改为  convertAbsoluteFileSystem 试一下

**Comment by liaohui5** [comment]
还是不行,&nbsp;

运行环境信息如下:
品牌: 小米8
os : android 9
HBuilderX: 2.3.7.20191024
运行平台: app









------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"王亚琪"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月14日(星期四) 下午4:22
收件人:&nbsp;"dcloudio/uni-app"<uni-app@noreply.github.com&gt;;
抄送:&nbsp;"廖辉"<1182468610@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [dcloudio/uni-app] 希望在 image 组件上加一个 cache 属性可以自动缓存图片 (#984)




组件ImageCache.vue 67行convertLocalFileSystemURL 改为  convertAbsoluteFileSystem 试一下

**Comment by Wangyaqi** [comment]
上传一下你的测试项目，我用我的手机测试可以 同样是安卓9，另外你可以升级一下HBuilderX测试一下

**Comment by liaohui5** [comment]
> 上传一下你的测试项目，我用我的手机测试可以 同样是安卓9，另外你可以升级一下HBuilderX测试一下

已经通过其他方法间接解决了, 不过我还是希望官方加一下这样一个属性,还是挺常用的

**Comment by Leeiio** [comment]
官方回应一下？

**Comment by kinsui** [comment]
> > 上传一下你的测试项目，我用我的手机测试可以 同样是安卓9，另外你可以升级一下HBuilderX测试一下
> 
> 已经通过其他方法间接解决了, 不过我还是希望官方加一下这样一个属性,还是挺常用的

请问是什么方法
