### ISSUE TITLE
希望增加目录别名设置，从而方便书写代码引用路径

### ISSUE THREAD

**Issue by liu927971519** [dcloudio/uni-app#985]
**新功能描述**
支持下述引用方式
import Utils from '@/utils'

**现状及问题**
目前引用
import Utils from '../../utils'
书写过多级相对路径

**尝试方案**
通过配置目录别名方式，从而方便书写代码引用路径

**Comment by XieB** [comment]
同求，我看thor ui已经用别名了，不知道哪里设置

**Comment by Wangyaqi** [comment]
你们的项目里面不能用`@`吗？

**Comment by liu927971519** [comment]
非常感谢

**Comment by liu927971519** [comment]
非常感谢。支持自定义别名吗
> 你们的项目里面不能用`@`吗？

**Comment by liu927971519** [comment]
非常感谢。支持其他自定义别名吗
> 你们的项目里面不能用`@`吗？
