### ISSUE TITLE
uni.request() 怎么样处理 400，500 这样类型错误的？

### ISSUE THREAD

**Issue by Simingchen** [dcloudio/uni-app#986]
**问题描述**
uni.request() 怎么样处理 400，500 这样类型错误的？

**复现步骤**
[复现问题的步骤]

[或者可以直接贴源代码]

uni.request({
    url: 'https://www.example.com/request', //仅为示例，并非真实接口地址。
    data: {
        text: 'uni.request'
    },
    header: {
        'custom-header': 'hello' //自定义请求头信息
    },
    success: (res) => {
        console.log("成功" + JSON.stringify(res));
    },
    complete: (res)=> {
        console.log("完成" + JSON.stringify(res));
    },
    fail: (res)=> {
        console.log("失败" + JSON.stringify(res));
    },
});

**预期结果**
success,complete,fail 没有对请求错误，404，500等错误处理，要捕获这样的code，需要在哪里获取？

**Comment by Wangyaqi** [comment]
可以自己包装一下uni.request来实现

**Comment by wakaryry** [comment]
https://ext.dcloud.net.cn/plugin?id=737

参考一下。
