### ISSUE TITLE
nvue下app端js全局变量被重置

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#989]
在使用的过程中，我的全局js 变量在app端总是被重置。在ios和Android上面都有过测试。在mp和H5上可以正常使用。

```js
export const tokenInfo = {
	access: null,
	accessTime: null,
	refresh: null,
	refreshTime: null
}
```

我从`storage`中获取保存的`aceess/refresh`等信息，然后放入`tokenInfo`中，接下来我就利用`tokenInfo`进行请求测试，接下来的请求中往往第一个请求能够获取到`tokenInfo`，第二个请求获取`tokenInfo`的时候每一个`item`就都是空了。

我有一个 请求库，请求库需要用到这个 `tokenInfo`，每一次请求都会检测 tokenInfo 是否过期，过期就刷新token，或者终止请求等。

因为vuex中的actions引入了这个请求库，所以我暂时没有把 tokenInfo放入 vuex中，只是 用了 一个全局的js文件来存储。

莫非我要放弃所有的actions，然后把 tokenInfo 放在 vuex中？

附带测试源码。

比较急。谢谢。

[nvueTest.zip](https://github.com/dcloudio/uni-app/files/3845448/nvueTest.zip)

**Comment by wakaryry** [comment]
@hbcui1984 比较急。这种情况应该怎么处理比较好。

**Comment by Wangyaqi** [comment]
const  -> let

**Comment by wakaryry** [comment]
没有用。一样的。

**Comment by fxy060608** [comment]
nvue下每个页面默认是隔离的，引用的相同模块，不会共享状态，如果需要共享，请使用 globalData 方案

**Comment by wakaryry** [comment]
关键是这个变量我不是在页面中使用。我是在请求拦截器的js中使用。

我已经将它放入vuex中了，正在测试。

vuex中专门建立了一个token模块，这个模块不引用request。

其它模块会引入request，request中会使用到store。

不知道这样会不会引起循环引用。

**Comment by wakaryry** [comment]
request中引入store，request中会使用store的token模块。store的token模块不引入request，其它store的模块中会引入request。

目前运行正常。

nvue中全局js变量不共享，但是需要在非页面的js中共享变量的时候，考虑使用vuex。合理设置模块，可以避免循环引入。

[nvueTest.zip](https://github.com/dcloudio/uni-app/files/3846331/nvueTest.zip)

**Comment by wakaryry** [comment]
先关闭了。有问题再说。遇到我类似问题的或者有更好解决办法的可以找我。QQ：382006503

**Comment by wakaryry** [comment]
没有想到，前面测试通过的，现在项目中又无法通过。

暂时总结如下：

- 全局js变量，在nvue中不可用，会被重置；
- store/vuex在非mixin或者页面的js中不可用，取出来的值都是初始值；

所以我现在使用getApp，看看能不能在工具类的js里面使用。

如果getApp还不行，那就不得不每一次都要从storage里面去取出来了。
