### ISSUE TITLE
nvue uniapp编译模式，仅 iOS下，textarea 设置auto-height，传入初始值，textarea 高度没有自适应而是还是只显示一行

### ISSUE THREAD

**Issue by atlaseye** [dcloudio/uni-app#992]
**问题描述**
nvue uniapp编译模式，仅 iOS下，textarea 设置auto-height，传入初始值，textarea 高度没有自适应而是还是只显示一行；这里，初始化的文字肯定是多于一行的。

同样代码，nvue 安卓下没问题，H5下没问题，但 nvue iOS 下有这个问题。

**复现步骤**
<textarea v-if="line.lineType.substring(0,4)==='text'"
            :id="line.lineId"
            :style="[textareaStyle(line)]"
            :auto-height="true"
            :value="isReady? line.content : ''"
            :maxlength="800000"
            :show-confirm-bar="false"
            :focus="lines.length>1 && index===lines.length-1"
            @input="input"
            @focus="focus"
            @blur="blur"
          ></textarea>

**预期结果**
预期结果，显示出来的 textarea 应该是多行，因为line.content是一个超过 40 个字的字符串，一行显示不下。

**实际结果**
安卓 nvue，显示多行。
H5，显示多行。
iOS，显示 1 行。需要手动在 textarea 里敲一个字后，就显示正确了。

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统
iOS12, iOS13, android
 - HBuilderX版本 最新版
 - uni-app版本
2.3.7
 - 设备信息 [如 iPhone8 Plus]
iPhone6, iPhone XS Max真机
iPhone 11Pro 模拟器，均有这个问题

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]
仅猜测，textarea自适应高度的逻辑，有需要平台特殊处理的点吧可能。

**Comment by Wangyaqi** [comment]
nvue下不支持auto-height，目前编写nvue需要对照[weex文档](https://weex.apache.org/zh/docs/components/textarea.html#%E5%B1%9E%E6%80%A7)

**Comment by dcloudhdx** [comment]
Bug已确认

**Comment by hblz** [comment]
这个问题啥时候可以修复

**Comment by xiaohuapunk** [comment]
> 这个问题啥时候可以修复

下次发版就会带上

**Comment by dcloudhdx** [comment]
HBuilderX 2.8.2+ alpha 已修复
