### ISSUE TITLE
nvue uni-app编译模式，安卓下，textarea设置font-weight无效，iOS 没问题

### ISSUE THREAD

**Issue by atlaseye** [dcloudio/uni-app#993]
**问题描述**
nvue uni-app编译模式，textarea设置font-weight无效。比如设置font-weight:800，并没有显示粗体。

**复现步骤**
<textarea v-if="line.lineType.substring(0,4)==='text'"
            :id="line.lineId"
            :style="[textareaStyle(line)]"
            :auto-height="true"
            :value="isReady? line.content : ''"
            :maxlength="800000"
            :show-confirm-bar="false"
            :focus="lines.length>1 && index===lines.length-1"
            @input="input"
            @focus="focus"
            @blur="blur"
          ></textarea>

textareaStyle(line) {
        let res = {'font-family': 'Pingfang SC'};
        let themestyle = this.$theme.headline();
        console.log('textareaStyle', line);
        if (line.lineType === 'text-bold') themestyle = this.$theme.subtitle2();
        if (line.lineType === 'text-color') themestyle.color = this.$theme.colorPrimary();
        res = Object.assign(res, themestyle);
        console.log('res', res);
        return res;
      },

**预期结果**
font-weight: 800的设置应该使整个TextArea用户输入的文字显示为粗体。

**实际结果**
实际没有显示粗体，还是普通的 weight。
（color、font-family，background-color 这些经过测试都是生效的，只有 font-weight 不生效）
这样，目前没有办法使nvue下的textarea显示粗体内容。

另外，同样代码，H5端 一切正常。

**系统信息:**
 - 发行平台: [如 微信小程序、H5平台、5+ App等]
 - 操作系统 [如 iOS 12.1.2、Android 7.0]
 - HBuilderX版本 [如使用HBuilderX，则需提供 HBuilderX 版本号]
 - uni-app版本 [如使用Vue-cli创建/运行项目，则提供`npm run info`的运行结果]
 - 设备信息 [如 iPhone8 Plus]

**补充信息**
[可选]
[根据你的分析，出现这个问题的原因可能在哪里？]

**Comment by Wangyaqi** [comment]
只支持normal 和 bold 不支持 数字

**Comment by sophieChenyx** [comment]
我也遇到了这个问题
安卓手机 设置 font-weight:600 
字体不现实加粗 不仅仅是 textara 别的标签中的内容也会这样
只能使用 font-weight: bold/normal 
IOS 未进行测试
