### ISSUE TITLE
nvue 如何关闭bounce回弹效果，在app-plus设置了"bounce" : "none"没有用

### ISSUE THREAD

**Issue by Liu-Peter** [dcloudio/uni-app#996]
**问题描述**
[问题描述：尽可能简洁清晰地把问题描述清楚]
nvue 如何关闭bounce回弹效果，在app-plus设置了"bounce" : "none"没有用
**复现步骤**

"style" : {  			               
			            "app-plus" : {  
			                    "titleNView" : false,  
			                    "bounce" : "none"  
			                }  
			            }

**实际结果**
模拟器iPhone11 Pro Max——13.2
回弹依旧存在

**Comment by javascriptchen** [comment]
nvue页面没有bounce回弹效果，只有几个列表组件有bounce效果，包括 list、recycle-list、waterfall。
[https://uniapp.dcloud.io/use-weex?id=nvue%e5%bc%80%e5%8f%91%e4%b8%8evue%e5%bc%80%e5%8f%91%e7%9a%84%e5%b8%b8%e8%a7%81%e5%8c%ba%e5%88%ab](https://uniapp.dcloud.io/use-weex?id=nvue%e5%bc%80%e5%8f%91%e4%b8%8evue%e5%bc%80%e5%8f%91%e7%9a%84%e5%b8%b8%e8%a7%81%e5%8c%ba%e5%88%ab)

**Comment by wakaryry** [comment]
下一版预计会设置 是否 最外层包裹scroll-view。这样就可以去掉了。

https://github.com/dcloudio/uni-app/issues/998

**Comment by dcloudhdx** [comment]
更新 HBuilderX 到最新版
1. pages 配置 "disableScroll": true
2. 页面 `<scroll-view "bounce"="none">`
