### ISSUE TITLE
可以考虑去掉或者可以配置页面自动包裹的外层scroll

### ISSUE THREAD

**Issue by wakaryry** [dcloudio/uni-app#998]
现在官方会自动在页面外层包裹scroll。不过建议去掉。或者提供可以去掉的配置。主要考虑如下：

- 一般开发者会根据需要自己添加scroll；
- 下拉刷新等大多数人应该不会使用自带的，开发者依然需要引入scroll；

**Comment by Wangyaqi** [comment]
感谢反馈，调研中

**Comment by fxy060608** [comment]
预计下个版本支持：在 pages.json 对应的页面中配置 disableScroll:true 禁用 scroll-view 的自动包裹

**Comment by wakaryry** [comment]
https://github.com/dcloudio/uni-app/issues/1018

看看这个测试。别人给我反馈nvue中scroll-view在安卓上面y方向全部不能滚动。

**Comment by fxy060608** [comment]
这个就是因为最外层有 scroll-view 导致内部的 scroll-view 无法滚动，在 android 上同方向嵌套有问题

**Comment by wakaryry** [comment]
@fxy060608 好的。谢谢。

希望越来越好。

**Comment by wakaryry** [comment]
> 预计下个版本支持：在 pages.json 对应的页面中配置 disableScroll:true 禁用 scroll-view 的自动包裹

提醒一下：要是可以加一个全局 配置 更完美。

**Comment by wakaryry** [comment]
暂时关闭了。2.4.4 已经开始 可以配置了。
