### ISSUE TITLE
video弹幕bug

### ISSUE THREAD

**Issue by i5920** [dcloudio/uni-app#999]
**问题描述**
正常：mac下谷歌浏览器/ios应用/android应用
异常：安卓uc浏览器/安卓微信内置浏览器/安卓QQ内置浏览器

**Comment by zhetengbiji** [comment]
此类国产浏览器一般将网页内的video替换为其定制原生播放器，使原有功能失效（甚至插播广告），很难自行优化体验。
如哔哩哔哩等弹幕网也无法正常显示弹幕（其在QQ浏览器加入了白名单可以正常显示）
